### ISSUE TITLE
getLocaleByPath(Astro.url.pathname) not working as expected

### ISSUE THREAD

**Issue by veniplex** [withastro/astro#10017]
### Astro Info

```block
Astro                    v4.3.3
Node                     v21.6.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/svelte
                         @astrojs/tailwind
```

### Describe the Bug

I am setting up a new site with the newest Astro version and I want to start by implementing a language dropdown, so the user can decide which language to use.

In a `LanguageSwitcher.astro` component I want to get the current language served to the user by using `getLocaleByPath(Astro.url.pathname)`. This is not working, because `Astro.url.pathname` i. e. returns `/en/`, but `getLocaleByPath(path)` is only working without providing the leading and trailing `/`. Is this expected or a bug? Or is it even the complete wrong way to get this done? :D...

I appreciate every suggestion. Thanks!

### What's the expected result?

`getLocaleByPath(Astro.url.pathname)` should return the current language served to the user.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7fefhn?file=src%2Fcomponents%2FLanguageSwitcher.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by log101** [comment]
`Astro.url.pathname` is effected by the [`build.format` configuration setting](https://docs.astro.build/en/reference/configuration-reference/#buildformat). So it is probably an expected output.
[This](https://docs.astro.build/en/recipes/i18n/#translate-ui-strings) documentation page seems to be splitting the pathname to get the language. And the next part is about creating a language picker, you might want to take a look.

**Comment by veniplex** [comment]
> `Astro.url.pathname` is effected by the [`build.format` configuration setting](https://docs.astro.build/en/reference/configuration-reference/#buildformat).

This makes sense, but would it not be better if the `getLocaleByPath()` supports the output generated by `Astro.url.pathname`? I just don't know how to get the current language in another consistent way.

> So it is probably an expected output. [This](https://docs.astro.build/en/recipes/i18n/#translate-ui-strings) documentation page seems to be splitting the pathname to get the language. And the next part is about creating a language picker, you might want to take a look.

Thanks for that. I already implemented i18n wth this instruction in an older build, but I want to try the new built-in way :).

**Comment by veniplex** [comment]
Okay, don't know how I missed it but there is actually a [`Astro.currentLocale`](https://docs.astro.build/en/reference/api-reference/#astrocurrentlocale) prop available, which does exactly what I was trying to do!
