### ISSUE TITLE
Astro.slots.has() returns true when slot exists inside a falsy conditional block.

### ISSUE THREAD

**Issue by ekfuhrmann** [withastro/astro#10024]
### Astro Info

```block
Astro                    v4.3.3
Node                     v20.3.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/tailwind
```

### Describe the Bug

While working with named `slots` I ran into a problem where if a named slot is contained within a falsy conditional block, `Astro.slots.has()` will return `true`, even though it shouldn't actually be there.

To illustrate the problem better, see the following snippets which will be derived from the example found inside the [API docs](https://docs.astro.build/en/reference/api-reference/#astroslots).

### Example.astro
```astro
---
---

<div>
  <slot />

  {Astro.slots.has('more') && (
    <aside>
      <h2>More</h2>
      <slot name="more" />
    </aside>
  )}
</div>

```

### index.astro
```astro
---
import Example from 'Example.astro'
---

<Example>
  {false && <div slot="more" />}
</Example>
```

### What's the expected result?

You should expect that nothing should be returned inside of `index.astro` since the named `slot` is supposed to not render by being inside a false conditional, but what actually happens is that `Astro.slots.has("more")` actually returns true in this case, resulting in the following compiled code:

```html
<div>
  <aside> 
    <h2>More</h2>
  </aside>
</div>
```

If I were to just have the following, than `Astro.slots.has("more")` properly returns `false`.
### index.astro
```astro
---
import Example from 'Example.astro'
---

<Example />
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ebze8m?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ekfuhrmann** [comment]
Thanks for digging that up. The workaround solution seems to be working well, so I'm happy with that.

Just to pass it forward for anyone who comes across this you can use the following for named slots:
```astro
<Component>
  {condition && <p slot={condition && 'named-slot'}>Slot content</p>}
</Component>
```

**Comment by robclancy** [comment]
Thanks for the solution but damn this is fucking stupid that it doesn't work. Just wasted so much time (for the second time on slots, because of other stupid restrictions in them).
