### ISSUE TITLE
reloading astro site hangs after a few reloads, random 504 errors

### ISSUE THREAD

**Issue by ctappy** [withastro/astro#10056]
### Astro Info

```block
"@astrojs/partytown": "^1.2.3",
    "astro": "^3.6.0",
    "bootstrap": "^5.3.2",
    "sass": "^1.69.5"
```

### If this issue only occurs in one browser, which browser is a problem?

*

### Describe the Bug

the initial load on a fresh page view always work. After refreshing the page occasionally the page will hang with no response at all

We tested the same server different website and did not have an issue, so not related to server/networking.

Since there are no errors in chrome/safari/firefox and no errors in astros logs, this is fairly vague. What would be a good way to narrow the issue? Thanks!

### What's the expected result?

always refresh without hanging

### Link to Minimal Reproducible Example

https://astro.new/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Astro's code doesn't include generating a 504 response so chances are, another part of your infrastructure is invovled.

**Comment by ctappy** [comment]
thanks!
