### ISSUE TITLE
Safari fails to load islands: Unhandled Promise Rejection: ReferenceError: Cannot access uninitialized variable.

### ISSUE THREAD

**Issue by mb21** [withastro/astro#10055]
### Astro Info

```block
Astro                    v4.3.5
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/solid-js
```

### If this issue only occurs in one browser, which browser is a problem?

Safari (reproducable in Safari 17.3 on macOS and Safari on iOS 17.3)

### Describe the Bug

I have two framework islands on my page (solid.js in this case, but I believe that's irrelevant). One of the islands sometimes fails to load completely. It's not always the same island that fails: sometimes both load, and sometimes one and sometimes the other (also sometimes it starts load, rendering something client-side, but then seems to fail later as the buttons are not working). Interestingly, the error logged to the safari console happens always in the DOM of the first island (even though that island then works perfectly fine, while the other one is broken):

In Safari dev tools it looks as follows (note which function call is underlined):
<img width="876" alt="image" src="https://github.com/withastro/astro/assets/157497/e816441d-6ff5-41bb-9eab-75acc1728fb0">

Here the relevant code as text:
```
                <script>
                (() => {
                    var e = async t => {
                        await (await t())()
                    };
                    (self.Astro || (self.Astro = {})).only = e;
                    window.dispatchEvent(new Event("astro:only"));
                })();
```

I've only managed to reproduce this in a production build, but even a production build running locally. All network requests completed with a 200.

Seems the code where the error occurs is just above [this code](https://github.com/withastro/astro/blob/31e2a777b2747d9b89dca4eb8534ecc4b01fc340/scripts/cmd/prebuild.js#L52). So probably it's an import that's generated by esbuild? That double await seems kinda funky anyway, or is that something you recognize?

I found this interesting [comment on the svelte issue tracker](https://github.com/sveltejs/kit/issues/2889#issuecomment-1501034784):

> We finally resolved this issue by removing the esnext build target in our vite config, which was there for a couple of top-level awaits. [This](https://bugs.webkit.org/show_bug.cgi?id=242740) bug in webkit is what ultimately made us try this update.

[TL;DR](https://github.com/sveltejs/kit/issues/11364#issuecomment-1880029654):

> [in Safari], the following code fails when importing the dependency more than once.
> 
> ```js
> export let bar = 'foo'
> await 0
> ```

I tried changing `astro.config` to:

```js
export default defineConfig({
  vite: {
    build: {
      target: 'es2021',
    },
  ...
```

but when building then I get:

> Top-level await is not available in the configured target environment ("es2021" + 2 overrides)

Somebody else has seen this error in their astro project and/or even managed to fix it?

### What's the expected result?

All islands hydrate properly.

### Link to Minimal Reproducible Example

So far I've not been able to reproduce this with a minimal example. Perhaps it requires a certain amount of code to trigger the race condition?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mb21** [comment]
Okay, I actually traced this down to a top-level await in one of the modules (awaiting a dynamic import, nested in a bunch of ifs etc. – that's why I didn't see it for so long). That module was included in both islands and that's why it triggered the Safari bug.

Minimal repro: https://stackblitz.com/edit/github-4s1seb?file=src%2Fcomponents%2FCounter.tsx

So I suppose I'll have to work around that myself. Not sure if there would be a way for Astro to surface this error better... but I believe there are a bunch of tickets for improving error handling of islands already... so feel free to close this issue.

**Comment by lilnasy** [comment]
I remember trying to fix this. I can't recall if it was a reported issue or something I had run into in  a project. I didn't get anywhere, however, I remember that much.

**Comment by lilnasy** [comment]
I can see the error in dev, not in the final build, and the component code runs correctly despite it. Does that sound right?

**Comment by mb21** [comment]
Yes, I think it doesn't depend on dev or prod build. it's just a race condition... but if two modules happen to load the same module (the one with the top-level await), then you run into this.

**Comment by mb21** [comment]
It's probably Safari... actually the minmimal example (instead of Counter.tsx) is just a framework component that contains:

```
export let bar = 'foo'
await 0
```

But yeah, probably there's not much Astro can do. So maybe good that there is this issue now so people find it via google, but that's all we can do here.

**Comment by mb21** [comment]
@MrHBS yes, that's the one I linked above.
