### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/cssesc/cssesc.js?v=b2d6e5fb' does not provide an export named 'default' (at transition.js:3:8)

### ISSUE THREAD

**Issue by thedtvn** [withastro/astro#10052]
### Astro Info

```block
Astro                    v4.3.5
Node                     v20.11.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @sentry/astro
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

Uncaught SyntaxError: The requested module '/node_modules/cssesc/cssesc.js?v=b2d6e5fb' does not provide an export named 'default' (at transition.js:3:8)
![image](https://github.com/withastro/astro/assets/80153297/30e8914f-38af-440c-85c1-57abb03413d5)

### What's the expected result?

iut work

### Link to Minimal Reproducible Example

null

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jxxe** [comment]
Did you manage to resolve this?

**Comment by thedtvn** [comment]
> Did you manage to resolve this?

@jxxe yes by remove some lib

**Comment by yoyo837** [comment]
I had the same error but I didn't know what it was related to, I just simply updated the 3 dependencies. Even if I revert the changes, it still doesn't work (the lock file is restored and node_modules is deleted).

**Comment by thedtvn** [comment]
> I had the same error but I didn't know what it was related to, I just simply updated the 3 dependencies. Even if I revert the changes, it still doesn't work (the lock file is restored and node_modules is deleted).

@yoyo837 i fix it by remove lib 
[astro-resume](https://www.npmjs.com/package/@ayco/astro-resume)
