### ISSUE TITLE
`vite.resolve.alias` does not appear to work as expected

### ISSUE THREAD

**Issue by bcheidemann** [withastro/astro#10064]
### Astro Info

```block
Astro                    v4.3.5
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### Describe the Bug

```js
export default defineConfig({
  integrations: [react()],
  vite: {
    resolve: {
      alias: {
        'next/image': resolve('./src/shims/next/image.tsx'),
        'next-image': resolve('./src/shims/next/image.tsx'),
      }
    }
  }
});
```

In the above config, `import Image from 'next-image'` is resolved correctly to the shim, but `import Image from 'next/image'` is not and is instead resolved as if there was no alias in place.

### What's the expected result?

Importing `next/image` would be resolved to the shim.

### Link to Minimal Reproducible Example

https://github.com/bcheidemann/astro-resolve-alias-reproduction

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Is the github repo private?

**Comment by lilnasy** [comment]
Feel free to reopen
