### ISSUE TITLE
`transition:name` no longer works with special characters after the introduction of cssesc

### ISSUE THREAD

**Issue by SenseiMarv** [withastro/astro#10081]
### Astro Info

```block
Astro                    v4.2.5
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

After the merge of https://github.com/withastro/astro/pull/9822, the usage of special characters in the `transition:name` prop breaks transitions. I use the page title to create a unique transition name on my website that includes whitespaces. After upgrading Astro to v4.2.5, I noticed that this implementation no longer worked.

I have reproduced the problem in a minimal reproducible example. Here are two versions of the same implementation, one working with Astro v4.2.4 and one broken with v4.2.5:
[Working (Astro v4.2.4)](https://stackblitz.com/edit/withastro-astro-eqnptw?file=src%2Fpages%2Findex.astro)
[Broken (Astro v4.2.5)](https://stackblitz.com/edit/withastro-astro-73q1em?file=src%2Fpages%2Findex.astro)

While preparing the examples, I noticed that other special characters like `.` or `/` also break the transitions.

### What's the expected result?

It is possible to use special characters in the `transition:name` prop. If this is not an intended use case, it should be documented in the docs that special characters will not work.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-73q1em?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, we might need to remove the use of cssesc, going to talk with people about it.

**Comment by martrapp** [comment]
Hi @SenseiMarv, it seems that Chrome is having some trouble with the characters you mentioned. The output from cssesc does seem to be spec-compliant for view-transition-names, but yes that doesn't help much if the browser just ignores such names ;-) So I think we transform those chars before escaping.

**Comment by SenseiMarv** [comment]
@martrapp I also wasn't sure enough where in the chain things get broken when creating the issue.

For example, the output of

```ts
const title = "Welcome to Astro."
const transitionName = `hero-${title}`
console.log(cssesc(transitionName, { isIdentifier: true }))
```

is `hero-Welcome\ to\ Astro\.`, which looks fine to me.

**Comment by martrapp** [comment]
Yes, best of all, in Chrome, if you assign a badly escaped string to `el.style.viewTransitionName`, it will not accept it. In deed it will accept `hero-Welcome\ to\ Astro\.` But when it contains escaped characters in the \x00 to \x7f range, Chrome seems to just ignore the whole name. A fix is on the way ,-)
