### ISSUE TITLE
📘 DOC: Add RSS feed to blog

### ISSUE THREAD

**Issue by canac** [withastro/astro#1009]
It would be awesome to add an RSS feed to the Astro blog so that we can follow along using feed readers.

**Comment by jasikpark** [comment]
That would be nice! I think atm the index page is just hand-rolled so the rss feed might end up being too?

**Comment by jasikpark** [comment]
Oh nice! I didn't see the transition to use markdown on the `www` blog posts

**Comment by dboulet** [comment]
Glad to see this issue get resolved, but as an outside observer I’m a little confused. The day after this was merged, the entire astro.build website was moved to a new repo with a completely redesigned website which doesn’t include this change. 🤔

**Comment by rbardini** [comment]
Indeed! I tried looking into the new website source, but the repository linked [here](https://github.com/withastro/astro/tree/main/www) gives me a 404 😕

**Comment by jonathantneal** [comment]
Yea, your fix is meant to stay! Moving the repos is making it easier for more people to contribute. We’re already seeing this in the docs. I’ll make sure this gets moved over.
