### ISSUE TITLE
vitest emits warnings when configured as in astro's vitest example template

### ISSUE THREAD

**Issue by davepeck** [withastro/astro#10118]
### Astro Info

```block
Astro                    v4.3.7
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Create a `vitest.config.ts` that's identical to the one found in [astro's official `with-vitest` example](https://github.com/withastro/astro/blob/main/examples/with-vitest/vitest.config.ts). 

Then run `vitest`. I see:

```
14:41:41 [WARN] [vite] (!) Experimental optimizeDeps.disabled and deps pre-bundling during build were removed in Vite 5.1.
    Setting it to false now has no effect.
    Please remove optimizeDeps.disabled from your config.
  
14:41:41 [WARN] [vite] (!) Experimental ssr.optimizeDeps.disabled and deps pre-bundling during build were removed in Vite 5.1.
    Setting it to false now has no effect.
    Please remove ssr.optimizeDeps.disabled from your config.
```

Looks like I have `vite/5.1.2` and `vitest/1.2.2` installed.

Peering under the hood, It looks like the generated config from `getViteConfig(...)` includes both the `optimizeDeps` and the `ssr` keys; I see:

```
{
   ...
   optimizeDeps: { entries: [ 'src/**/*' ], exclude: [ 'astro', 'node-fetch' ] },
   ...
ssr: {
    noExternal: [
      'astro',
      'astro/components',
      '@nanostores/preact',
      '@fontsource/*'
    ],
    external: []
  },
   ...
}
```

### What's the expected result?

No warnings from `vitest`/`vite`.

### Link to Minimal Reproducible Example

https://github.com/literalgarage/astro-vitest-minimal-repro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by davepeck** [comment]
Update: I just saw [this recently merged PR](https://github.com/withastro/astro/pull/9719). If I'm reading the tea leaves correctly, my version of astro should include those changes. Perhaps there's still a little more work to do to fix up our use of `vite` config everywhere?

**Comment by bluwy** [comment]
The warnings comes from Vitest:

https://github.com/vitest-dev/vitest/blob/aa72740a61228c4c2cf0bd26f7ee8a63b38954cd/packages/vitest/src/node/plugins/optimizer.ts#L15-L17

https://github.com/vitest-dev/vitest/blob/aa72740a61228c4c2cf0bd26f7ee8a63b38954cd/packages/vitest/src/node/plugins/utils.ts#L22

You should report this upstream.

**Comment by davepeck** [comment]
Linking to https://github.com/vitest-dev/vitest/issues/5211
