### ISSUE TITLE
Discrepancy in getImage in dev vs build

### ISSUE THREAD

**Issue by MrGreenTea** [withastro/astro#10126]
### Astro Info

```block
Astro                    v4.3.2
Node                     v20.10.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
                         @astrojs/tailwind
```

### Describe the Bug

When accidentally passing the imported object to `getImage` (and not as `{ src: ImportedImage }`) then when using `astro dev` we get a `LocalImageUsedWrongly` error. But the image is used without issue and included as expected in the `astro build` output.

When using `getImage` from `astro:assets` and accidentally passing the imported object like this:

```astro
import { getImage } from 'astro:assets';
import MyCoolImage from '@assets/component/image.jpeg';
const optimizedImage = await getImage(MyCoolImage);

<img src={optimizedImage.src} />
```

You will get different behaviour during `astro dev` and `astro build`.

### What's the expected result?

To get an error explaining that the image has to be passed as `{ src: MyCoolImage }` and that it's not an import issue.

### Link to Minimal Reproducible Example

https://file.io/hmwoBKrygvT6

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Yes! I'm hoping to make ImageMetadata a branded type or something so that it's at least a type error. It's a bit hard unfortunately to provide the same error message in dev and build for that one because we lose the required info since the path of the image changes in build. But anything to improve the situation there would be helpful, for sure.
