### ISSUE TITLE
Redirects for dynamic routes break when files with same name but different extensions exist

### ISSUE THREAD

**Issue by 3w36zj6** [withastro/astro#10122]
### Astro Info

```block
Astro                    v4.3.7
Node                     v20.11.0
System                   Linux (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

I am developing a blog based on the [Astro Starter Kit: Blog](https://github.com/withastro/astro/tree/main/examples/blog). The articles can be fetched at `/blog/[...slug]`, so I've made it possible to fetch the OGP images of the articles at `/blog/[...slug].png`. 

The problem starts here. I add a redirect from `/posts/[...slug]` to `/blog/[...slug]` in the Astro Config. However, when I access `/posts/[...slug]`, it redirects to `/blog/[...slug].png` instead of `/blog/[...slug]`.

### What's the expected result?

Access to `/posts/[...slug]` is redirected to `/blog/[...slug]`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ndv9vp

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by 1574242600** [comment]
@matthewp 
Excuse me, I found where the issue is, but I'm not sure if this is the expected behavior.  

https://github.com/withastro/astro/blob/8d5ea2df5d52ad9a311c407533b9f4226480faa8/packages/astro/src/core/routing/manifest/create.ts#L392-L394

When executing `/blog/[...slug].png`, the value of `segments` is
```js
[
  [
    {
      content: "blog",
      dynamic: false,
      spread: false,
    },
  ],
  [
    {
      content: "...slug",
      dynamic: true,
      spread: true,
    },
    {
      content: ".png",
      dynamic: false,
      spread: false,
    },
  ],
]
```
So  the value of  `route` is `/blog/[...slug]`, But the issue is that when executing `/blog/[...slug]`, the result for `route` still remains `/blog/[...slug]`, now `routes` include `/blog/[...slug]` and `/blog/[...slug].png`, but their `route` values are both `/blog/[...slug]`, with `/blog/[...slug].png` being overridden in routeMap.

https://github.com/withastro/astro/blob/8d5ea2df5d52ad9a311c407533b9f4226480faa8/packages/astro/src/core/routing/manifest/create.ts#L655-L660

**Comment by Fryuni** [comment]
Indeed, that `.map(([{ dynamic, content }])` incorrectly assumes that a segment is a single part. This probably causes other errors in corner cases. It should apply that for each part of the segment and concatenate them.

Do you want to open a PR for that since you already investigated?

**Comment by 1574242600** [comment]
> Indeed, that `.map(([{ dynamic, content }])` incorrectly assumes that a segment is a single part. This probably causes other errors in corner cases. It should apply that for each part of the segment and concatenate them.
> 
> Do you want to open a PR for that since you already investigated?

But I think that is the expected behavior, as there is no information in the documentation regarding the use of `/blog/[...slug].png.ts` or `/blog/[slug].png.ts`. There should be a warning about this behavior in the documentation.

**Comment by Fryuni** [comment]
Confirmed that this is a problem, partially dynamic segments are being truncated and affecting routing.

**Comment by arjendevos** [comment]
Issue still exists in version `"astro": "^4.7.1"`

Using it like this:
```ts
redirects: {
    "/nl/blog/[slug]": "/blog/[slug]",
  },
```
but it redirects to the `.png`

**Comment by 1574242600** [comment]
Could you provide a repro? The last repro can no longer be reproduced in 4.7.1.

**Comment by arjendevos** [comment]
@1574242600 I am debugging it, but I couldn't reproduce it on the stackblitz. I think I have some weird cache issues that is causing this. Will update once I've found the issue.

**Comment by arjendevos** [comment]
@1574242600 Confirmed. It seems to be a cache issue. Only happening with 1 url. Can't pinpoint where the cache is coming from but other urls work fine. Incognito also works fine.
