### ISSUE TITLE
Static File Endpoints broken with `trailingSlash: "always"` in development

### ISSUE THREAD

**Issue by kripod** [withastro/astro#10149]
### Astro Info

```block
Astro                    v4.4.0
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             astro-icon
                         @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
```

### Describe the Bug

Since `astro@4.1.0`, [Static File Endpoints](https://docs.astro.build/en/guides/endpoints/#static-file-endpoints) return 404 in development (running `astro dev`) when `trailingSlash: "always"` is set in the Astro config.

### What's the expected result?

Static File Endpoints should work as they did before merging https://github.com/withastro/astro/pull/9597.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fy7uro?file=src%2Fpages%2Ftest.json.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Are they broken only in development (just to understand, obviously this is still very important).

**Comment by kripod** [comment]
Yes, the breakage only occurs in dev mode.

**Comment by ematipico** [comment]
I'll look into. it

**Comment by ematipico** [comment]
Hi @kripod, we talked about this internally.

This isn't a bug. We actually that bug, and now the routing behaves consistently. As you set `trailingSlash: always`, it's expected that routes should respond to a trailing slash, endpoints too. Essentially, you were leveraging a bug. 

We will monitor the situation and see if this bugfix impacts too many users.

**Comment by kripod** [comment]
@ematipico I think my issue report may have been misunderstood.

Trailing slashes are a valid requirement for most API endpoint URLs, except for the ones which are meant to serve static files, e. g. `.png` images. Having to refer to those assets via `/something.png/` instead of `/something.png` may be outright invalid in production, even when trailing slashes are preferred.

**Comment by drewtownchi** [comment]
We've been having this issue for months.  We have a search.json.ts static file endpoint in the pages dir.  In prod we need to not add a trailing slash to the end of the route and in dev we need to make sure there is a trailing slash. It's not an optimal situation.

**Comment by diraneyya** [comment]
This is really one of those silly things that can waste so much time and energy. It deserves a revisit. I mean: revisiting the option itself, the documentation around it, and specifically the impact of this setting on serving images locally through the `/_image` endpoint.
