### ISSUE TITLE
Issues with i18n config typing

### ISSUE THREAD

**Issue by delucis** [withastro/astro#10157]
### Astro Info

```block
Astro                    v4.4.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Any (n/a)

### Describe the Bug

Using this issue to report two related issues with the types for the `i18n` config.

1. The types for `i18n.routing` are inaccurately strict. For example, the following is valid configuration and [shown in the Astro docs](https://docs.astro.build/en/guides/internationalization/#configure-i18n-routing):

	```ts
	import { defineConfig } from 'astro/config';
	
	export default defineConfig({
	  i18n: {
	    defaultLocale: 'en',
	    locales: ['en', 'fr'],
	    routing: {
	      prefixDefaultLocale: true,
	    },
	  },
	});
	```
	
	However, the above is considered a type error (you need an `astro.config.ts` or a `// @ts-check` comment to see this most likely). `strategy` and `redirectToDefaultLocale` are both typed as required in `i18n.routing`.

2. When setting `i18n` configuration from an Astro integration via the `updateConfig()` method, it seems to expect one of the internal enum values like `'pathname-prefix-other-locales'` rather than the proper configuration object. I suspect the issue is that `updateConfig()` is typed with `AstroConfig` instead of `AstroUserConfig`, which I think is inaccurate?

### What's the expected result?

1. The types should not require `i18n.routing` be set with all values.

2. The `updateConfig()` integration method should accept the same shape as when setting the config directly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cosd7e?file=astro.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Moved this back to "needs triage" after looking at the code. I'm not completely certain that this is a bug or not. The code all uses `AstroConfig` rather than `AstroUserConfig`. And you do get the zod-parsed config during setup. So I think the expectation is that integrations will mutate the resolved config, rather than user-defined config.

**Comment by ematipico** [comment]
I was under the impression that user config and integrations config is the same.

If not, they should. The transformation that I applied was supposed to be internal to Astro.

What's the best course of action?

**Comment by delucis** [comment]
> What's the best course of action?

I’m not super familiar with how the i18n code uses the config, but Matthew suggested above that AstroSettings could get the transformed form. In other words this mapping of the config to the string form would happen there?

https://github.com/withastro/astro/blob/9b78c992750cdb99c40a89a00ea2a0d1c00877d7/packages/astro/src/core/config/schema.ts#L366-L396

Would i18n code be able to read that off `AstroSettings`? (Or be refactored to skip this transformation and check the config object directly?)
