### ISSUE TITLE
Node adapter ignores `server.headers` under `astro preview`

### ISSUE THREAD

**Issue by nvzqz** [withastro/astro#10161]
### Astro Info

```block
Astro                    v4.4.0
Node                     v21.5.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

When running `astro dev`, the [headers set by `astro.config.ts`](https://docs.astro.build/en/reference/configuration-reference/#serverheaders) are received in responses. However, they are not received when running `astro preview`.

The headers I'm trying to use are:

```ts
{
  "Cross-Origin-Opener-Policy": "same-origin",
  "Cross-Origin-Embedder-Policy": "require-corp",
}
```

### What's the expected result?

Receive configured headers when running `astro preview`.

### Link to Minimal Reproducible Example

https://github.com/nvzqz/astro-missing-headers

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by log101** [comment]
#5564 Add headers to Vite preview server, but in SSR mode Node integration uses the server defined in [createServer](https://github.com/withastro/astro/blob/3c73441eb2eaba767d6dad1b30c0353195d28791/packages/integrations/node/src/standalone.ts#L47) as far as I understood. Could we pass the headers provided by user in this function?

**Comment by bluwy** [comment]
Yeah I think it also has to accept `headers` there. Likely we need to expand this first though:

https://github.com/withastro/astro/blob/9b78c992750cdb99c40a89a00ea2a0d1c00877d7/packages/astro/src/%40types/astro.ts#L2743-L2751

So that we can get the headers from:

https://github.com/withastro/astro/blob/9b78c992750cdb99c40a89a00ea2a0d1c00877d7/packages/integrations/node/src/preview.ts#L11

**Comment by log101** [comment]
Alright I'll be working on that, if you don't mind.

**Comment by log101** [comment]
I couldn't solve the 404 problem, if user added custom headers at `server.headers` config they are present at all responses including 404. I'm not sure how could this problem be solved as 404 responses seems to be handled at the [main app](packages/astro/src/core/app/index.ts), which merges the responses. Also is this comment is relevant to the context?:

https://github.com/withastro/astro/blob/7fe25158cdbb0c8b724913ffdbdf00f9fcdb7192/packages/astro/src/core/app/index.ts#L450-L458
