### ISSUE TITLE
Redirects on Vercel 

### ISSUE THREAD

**Issue by daherlive** [withastro/astro#10160]
### Astro Info

```block
Astro                    v4.4.0
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/react
                         @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/partytown
```

### If this issue only occurs in one browser, which browser is a problem?

Safari

### Describe the Bug

Guys, I'm developing a website project with a blog that has many redirects from old URLs to new ones with updated slugs. However, as I am using Vercel  and the redirect limit is exceeded. Has anyone faced a similar issue and find some solution to handle with this Vercel's limitation?

I've followed the docs instructions and added the paths on astro.config :
`redirects: {
    '/test/': '/news/test/',
....
}`

### What's the expected result?

Get some feature to fix this.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Does the old URL exist on your file system? If not, you can't use an astro redirect
