### ISSUE TITLE
Tailwind classes isn't work in the components

### ISSUE THREAD

**Issue by coofcoding** [withastro/astro#10176]
### Astro Info

```block
Astro                    v4.3.5
Node                     v20.11.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

All browsers in general

### Describe the Bug

I tried to assign a custom color for each repetition but in the development environment the color doesn't change, only works in the second object but not in others, and when I look in the Developer tools, the class is assigned successfully.

**Object**
![object](https://github.com/withastro/astro/assets/155861737/8009ec60-21d1-419f-9911-0e49ee3de111)

**Component with the class**
![component](https://github.com/withastro/astro/assets/155861737/9849e11e-27e7-4fb9-b7ed-9ab05bd5bcd7)

**Web result**
![image](https://github.com/withastro/astro/assets/155861737/9ef5e016-044e-41b5-9cf3-5904d94ab0be)

**Developer tools**
![image](https://github.com/withastro/astro/assets/155861737/ae864d7a-7323-4bda-8878-a4fde3ab7585)

After setting the color that I need in the component, something like this:
![component2](https://github.com/withastro/astro/assets/155861737/1bef44a6-3e0c-45f4-81a4-1ad16ea14b4d)
**This is the result**
![image](https://github.com/withastro/astro/assets/155861737/6696b312-16a8-4ea6-840d-3341dd9bae94)

And if I set the variable again, it works but the other colors are reseted.
![image](https://github.com/withastro/astro/assets/155861737/0f464120-d6b5-44bf-b3ac-6d68f8f3c292)

### What's the expected result?

this is what it has to look like:
![image](https://github.com/withastro/astro/assets/155861737/d63feaf2-9b53-46ab-a1a6-e99579682535)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/tailwind-classes-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You cannot use dynamic class names in Tailwind. https://tailwindcss.com/docs/content-configuration#dynamic-class-names
