### ISSUE TITLE
SSR routing issue for `[dynamic]` and `static-[dynamic]` routes in the same directory causes unexpected route matching

### ISSUE THREAD

**Issue by lucaswalter** [withastro/astro#10173]
### Astro Info

```block
Astro                    v4.4.0
Node                     v21.6.2
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/svelte
                         @astrojs/react
                         @astrojs/mdx
                         astro-robots-txt
```

### Describe the Bug

I have the following routes on my website. When I attempt to navigate to `/games/best-pvp-steam-games` (where **pvp** is a known tagSlug) the `[id].astro` route is being hit instead of my `/games/best-[tagSlug]-steam-games.astro` route. This previously worked in astro version `4.1.3` but does not work for me in later versions.

More discussion: https://discord.com/channels/830184174198718474/1209205625783849011

**Routes**
`/games/[id].astro`
`/games/best-[tagSlug]-steam-games`
`/games/best-rated-steam-games`

**Current Dependencies**
"astro": "^4.4.0",

### What's the expected result?

1. I expect that this url will match my `/games/best-[tagSlug]-steam-games.astro` instead of the `[id].astro` route

### Link to Minimal Reproducible Example

https://github.com/lucaswalter/Astro-Routing-Repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
What's the workaround?

**Comment by Fryuni** [comment]
Currently is to either:
- Have one single `[id].astro` route and if the ID matches a pattern render a different component
- Have those dynamic parts in different segments, but this changes the URL so not always a possibility

**Comment by ematipico** [comment]
I will look into it
