### ISSUE TITLE
Vercel adapter: parameter "functionPerRoute" generate serverless function even for prerendered routes

### ISSUE THREAD

**Issue by bentouch-digital** [withastro/astro#10211]
### Astro Info

```block
Astro                    v4.4.2
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          yarn
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         astro-icon
                         @astrojs/vue
                         @storyblok/astro
                         extract-tailwind-classes
                         redirections
```

### If this issue only occurs in one browser, which browser is a problem?

All

### Describe the Bug

Actually, when I build the projet with the Vercel adapter and the parameter `functionPerRoute` to `true`, it generates serverless functions for all routes, prerendered ones too. I have a route named [...slug].astro that generates only prerendered pages. But with this configuration it generates a serverless function [...slug].astro, as the result, all 404 errors fallback on this serverless function and a response is returned with code 200. If i set `functionPerRoute`to `false`, it's works as intended.

### What's the expected result?

Must not generate serverless functions for prerendered pages.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9beo4b

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Your example doesn't have prerendered pages. Please update the example to match the problem you're describing.

**Comment by dylanalizon** [comment]
> Your example doesn't have prerendered pages. Please update the example to match the problem you're describing.

@matthewp Hello, the ouput is "hybrid", unless I'm mistaken all pages are prerendered by default, so the index.astro is a prerendered one.

**Comment by lilnasy** [comment]
## Good first issue!
This is an opportunity for astro users to learn about how astro works by fixing a small but real bug. You can expect to get help setting up the dev environment, and understanding the project structure in `#dev` channel of our discord server (https://astro.build/chat). 

### What's the bug?
The `functionPerRoute` config creates more functions than necessary.

### What's going wrong here?
Adapters depend on Astro's Integration API to provide them with the routes to make functions out of. The routes are provided in a map called `entrypoints`.

Neither Astro nor the vercel adapter makes a distinction between prerendered and on-demand rendered routes - all are turned into functions. Only non-prerendered routes should be exposed to the adapter.

### Where do I start looking?
The part where Astro's internals pass the `entrypoints` map to the adapter is here: https://github.com/withastro/astro/blob/eb8bffe67a1e17e30162dae84229ea2737b6c529/packages/astro/src/core/build/plugins/plugin-manifest.ts#L98-L106

The part where Astro's internals populate the `entrypoints` map in the first place is here:
https://github.com/withastro/astro/blob/eb8bffe67a1e17e30162dae84229ea2737b6c529/packages/astro/src/core/build/plugins/plugin-ssr.ts#L201-L206
