### ISSUE TITLE
[WARN] `Astro.request.headers` is not available in "static" output mode.

### ISSUE THREAD

**Issue by mrcnski** [withastro/astro#10212]
### Astro Info

```block
Astro                    v4.4.3
Node                     v21.5.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Since upgrading to Astro 4.4.3 I'm getting this warning in the console:

```
[WARN] `Astro.request.headers` is not available in "static" output mode. To enable header access: set `output: "server"` or `output: "hybrid"` in your config file.
```

### What's the expected result?

I was not getting this warning on Astro 4.3.7. 

I'm not doing anything with `headers` AFAIK, but it would be nice to have a trace to know where this warning is coming from.

I tried for some time but I'm having trouble reproducing this on **Stackblitz** or in a fresh project. As mentioned above, a trace would be nice. My project is simple, my only dependencies are Astro and Typescript. 

### Link to Minimal Reproducible Example

https://stackblitz.com/see-above

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Reyno-Skeps** [comment]
Can confirm, running into the same issue right now.

**Comment by Princesseuh** [comment]
Will be fixed by https://github.com/withastro/astro/pull/10196, sorry for the inconvenience. It's a bug with i18n in particular

**Comment by bluwy** [comment]
https://github.com/withastro/astro/pull/10196 has been merged

**Comment by mrcnski** [comment]
I've confirmed that this has been fixed as of 4.4.5, thanks everybody.

**Comment by eitelkrauss** [comment]
I just upgraded to 4.5.9 and I'm running into this issue.  The warning is only for my prerendered pages.  I have `output: 'server'`

**Comment by boredland** [comment]
can confirm this still is a problem with `hybrid`, `i18n` and such a .astro file:

```
---
import { getHeadersLocale } from '../utils/headersLocale'

const locale = getHeadersLocale(Astro.request.headers.get('accept-language') ?? 'en')
  
return Astro.redirect(`/${locale}`)
---
```

**Comment by matthewp** [comment]
This is intentional. You can't read headers in a static page. We do this on purpose so that you don't rely on behavior that will lead to build-time and run-time differences.

**Comment by eitelkrauss** [comment]
@matthewp I'm not reading any headers though.

**Comment by daolanfler** [comment]
```astro
---
import ThemeToggle from "./ThemeToggle";
const cookie = Astro.cookies.get("theme");

export const prerender = false;
---

<ThemeToggle themeCookie={cookie?.value} client:load />
```

I have a ThemeToggle component like this, this component is accessing cookie in headers. And my astro.config.mjs is `output: hybrid`. This component runs on server instead of client as I've specified `prerender=false`, but I still  get the warning, and I thinks it's ok to access headers in this situation...

**Comment by rottmann** [comment]
Hint: this error occurs on symbolic linked files too, even if prerender is set to false.

**Comment by jahands** [comment]
Same here, running Astro on Cloudflare Workers. Just upgraded and started getting this warning. I also have an endpoint that started failing with this error on the server side:
```
(error) 12:28:48 [ERROR] TypeError: Can't modify immutable headers.
    at setOriginHeader (_worker.js:163:25960)
    at RenderContext.create (_worker.js:165:3228)
    at async bn.render (_worker.js:180:186)
    at async Object.fetch (_worker.js:180:5208)
```
(not sure if related or if this is a separate issue.)

**Comment by yoyo837** [comment]
Same warning in 4.16.14

**Comment by Mistwell** [comment]
Same warning in "astro": "^4.16.13",
just have 2 static mainpages with i18n

**Comment by ematipico** [comment]
@Mistwell update to the latest, this was fixed

**Comment by yoyo837** [comment]
`4.16.15` fixed this.

**Comment by vv3rd** [comment]
Encountered this issue on `4.16.15` when `Astro.rewrite` is used. 
To reproduce create src/pages/[your_locale_of_choice]/test.astro with
```astro
---
return Astro.rewrite('/anohter-page')
---
```

Warning goes away if you pass new instance of Request
```astro
return Astro.rewrite(new Request(new URL('/another-page', Astro.url.origin)));
```
