### ISSUE TITLE
i18n fallback : existing translated files are not built

### ISSUE THREAD

**Issue by jsiot76** [withastro/astro#10226]
### Astro Info

```block
Astro                    v4.4.4
Node                     v20.10.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When **building a project**, routing fallback is working fine for missing translations, generating redirection pages, **excepted for index.astro page**, redirection page is also built, even if index.astro file exists in translation folder.
_All pages are correctly shown when running project in dev mode._
This appeared since **4.2.0** version.

I created a stackblitz reproductible example, base on astro fixture code: astro/packages/astro/test/fixtures/i18n-routing-fallback

```text

├── dist/
│	└── blog
│	└── end
│	└── it
│	└── pt
|	|	└── blog
|	|	└── end
|	|	└── start
|	|	|	└── index.html : translated page
|	|	└── index.html : redirection page => it should be translated page
├── src/
│	├── pages/
│	│	└── blog
│	|	│	└── [id].astro
│	├── pt/
│	│	└── blog
│	|	|	└── [id].astro
│	|	└── index.astro : translated index page => generated as redirection page
│	|	|
│	|	└── start.astro
│	└── end.astro
│	└── index.astro
│	└── start.astro
 
```

### What's the expected result?

index.astro page should be correctly built in [locale] folder instead of index.html redirection page.

```text
├── dist/
│	└── blog
│	└── end
│	└── it
│	└── pt
|	|	└── blog
|	|	└── end
|	|	└── start
|	|	|	└── index.html : translated page
|	|	└── index.html : correct translated page
├── src/
│	├── pages/
│	│	└── blog
│	|	│	└── [id].astro
│	├── pt/
│	│	└── blog
│	|	|	└── [id].astro
│	|	└── index.astro
│	|	|
│	|	└── start.astro
│	└── end.astro
│	└── index.astro
│	└── start.astro
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-mrykc9?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jsiot76** [comment]
```
my astro.config.mjs

import { defineConfig } from 'astro/config';

export default defineConfig({
  base: 'new-site',
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'pt', 'it'],
    fallback: {
      it: 'en',
      pt: 'en',
    },
  },
});

```

**Comment by log101** [comment]
My initial debugging shows that the `/pt` index page is actually built correctly first. But in the router explosion stage, `/index.astro` generates multiple `/pt` pages under it, and one of them returns a redirect response which in turn overwrites '/pt/index.html`  file. I suppose the problem lies within the route explosion logic.

https://github.com/withastro/astro/blob/7fe25158cdbb0c8b724913ffdbdf00f9fcdb7192/packages/astro/src/core/build/generate.ts#L285-L286

I'll continue working on the problem.
