### ISSUE TITLE
Using HTTP/2 with astro dev

### ISSUE THREAD

**Issue by alexvuka1** [withastro/astro#10238]
### Astro Info

```block
Astro                    v4.4.3
Node                     v20.11.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

By default, astro is setting `vite.server.proxy` internally, which causes http/2 to be disabled according to the vite [documentation](https://vitejs.dev/config/server-options#server-https). Hence to use http/2 we need to set `proxy: false`. However, this makes it so that `Astro.request.url='https://undefined/'`.

NOTE: The provided minimal reproducible example works on stackblitz, but not locally. To reproduce - download it locally, install deps, run astro dev and check the console logs.

### What's the expected result?

I would like to be able to use http/2 with astro dev.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-j1fdfd-tvtekj?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@ascorbic This is a good one to research to understand more what's going on. Here's where we set `proxy`: https://github.com/withastro/astro/blob/main/packages/astro/src/core/create-vite.ts#L177-L179. I'm not sure why we do that though. Maybe it's not needed? And why does setting it to false cause the host to be undefined?
