### ISSUE TITLE
tailwindcss will be reset mdx's conent style ??

### ISSUE THREAD

**Issue by lkzwc** [withastro/astro#10232]
### Astro Info

```block
"@astrojs/mdx": "^2.1.1",
    "@astrojs/rss": "^4.0.5",
    "@astrojs/sitemap": "^3.1.1",
    "@astrojs/tailwind": "^5.1.0",
    "astro": "^4.4.4",
    "tailwindcss": "^3.4.1"
```

### If this issue only occurs in one browser, which browser is a problem?

google

### Describe the Bug

In MDX, the content in MD format will be overwritten by tailwindcss, such as h1 h2, li, and so on

### What's the expected result?

this is the fact

![image](https://github.com/withastro/astro/assets/84896877/c9e89928-d735-4dc0-82d2-4fe714abca7c)

we want to see, the more info in this repository [respository](https://github.com/lkzwc/astrodemo)

![image](https://github.com/withastro/astro/assets/84896877/2a662722-a415-460e-a7d2-5a7e364d5129)

### Link to Minimal Reproducible Example

https://github.com/lkzwc/astrodemo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is expected. The default tailwind stylesheet includes a CSS reset which resets the list style. If you want to bring that back, set https://docs.astro.build/en/guides/integrations-guide/tailwind/#applybasestyles to `false` and import a CSS file with this only:

```css
@tailwind components;
@tailwind utilities;
```

**Comment by lkzwc** [comment]
> This is expected. The default tailwind stylesheet includes a CSS reset which resets the list style. If you want to bring that back, set https://docs.astro.build/en/guides/integrations-guide/tailwind/#applybasestyles to `false` and import a CSS file with this only:
> 
> ```css
> @tailwind components;
> @tailwind utilities;
> ```

Thank you , That's why?

**Comment by lkzwc** [comment]
> https://docs.astro.build/en/guides/integrations-guide/tailwind/#applybasestyles

Is there any way to only set MDX settings？ After modifying according to what you said, the other styles on the interface have been modified。

**Comment by lkzwc** [comment]
> No, the CSS applies globally. Make sure all your layouts import the CSS file, or if you want to auto apply to all pages like `@astrojs/tailwind`, you can use an integration:
> 
> https://github.com/withastro/astro/blob/03242c6c2259dc583b21c12ad60109ac72aa9d52/packages/integrations/tailwind/src/index.ts#L97-L98

The MD file will eventually be parsed into an page. so ??

I solve it ,use @tailwindcss/typography ，Whether need to add it for troubleshooting ？
