### ISSUE TITLE
<Code /> component theme "css-variables" incorrectly typed

### ISSUE THREAD

**Issue by Ehesp** [withastro/astro#10246]
### Astro Info

```block
Astro                    v4.2.6
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

The following code throws a TypeScript error: `Type '"css-variables"' is not assignable to type 'BundledTheme | ThemeRegistration | ThemeRegistrationRaw | undefined'.ts(2322)`

```
<Code theme="css-variables" />
```

This is a valid theme from Shiki, and the outcome is it works as expected (and expects some defined css variables).

### What's the expected result?

No TS error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uhurkz?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Ahh we should probably use this type:

https://github.com/withastro/astro/blob/6bf102aebed88286b392aa1c61c8f7e2e22a39fc/packages/markdown/remark/src/types.ts#L36

Here instead:

https://github.com/withastro/astro/blob/6bf102aebed88286b392aa1c61c8f7e2e22a39fc/packages/astro/components/Code.astro#L31

https://github.com/withastro/astro/blob/6bf102aebed88286b392aa1c61c8f7e2e22a39fc/packages/astro/components/Code.astro#L36

`ThemePresets` replaces `BuiltinTheme`
