### ISSUE TITLE
`transition:animate="none"` still fades content

### ISSUE THREAD

**Issue by metonym** [withastro/astro#10241]
### Astro Info

```block
Astro                    v4.4.5
Node                     v18.18.2
System                   macOS (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
```

### Describe the Bug

I'm using View Transitions and explicitly want there to be no animations:

```html
<ViewTransitions transition:animate="none" />
```

However, I can observe a subtle fade/fade out. The docs say that [`prefers-reduced-motion`](https://docs.astro.build/en/guides/view-transitions/#prefers-reduced-motion) is respected (which is great). However, my expectation was that `animate="none"` would override this behavior, regardless of the preferred motion setting.

This behavior can be observed on the following site: https://svhe.onrender.com/

Source code for the View Transition usage: https://github.com/metonym/svelte-highlight/blob/master/www/layouts/Layout.astro#L17

Repro steps:

1. Ensure prefers reduced motion is disabled in system settings.
2. Visit the site.
3. Navigate between "Languages" or "Styles"
4. Note the fade animation.

### What's the expected result?

The expected result is that explicitly setting `transition:animate="none"` will not entail any animation.

### Link to Minimal Reproducible Example

https://github.com/metonym/svelte-highlight/blob/master/www/layouts/Layout.astro#L17

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @metonym, after a quick glance at you code:
```
  <ViewTransitions transition:animate="none" />
```
Here `transition:animate="none"` defines a new transition group but it does not change the overall animation behavior. The `<ViewTransitions />` component has a `fallback` property that can be set to `none` but that only controls the behavior on browsers that do not nativly support view transitions.

If you want to switch off all animations do the following:
A) remove all `tranistion:animate` and `transition:name` directives from your pages as they introduce additional animations.

This leaves a single transition group named `root` that the browser introduces automatically for the `<html>` element. This group defines three animations:

![image](https://github.com/withastro/astro/assets/94928215/29a86901-1411-42d9-b344-0749415b720b)

B) Switch these animations off by setting a single `transition:animate="none"` on the `<html>` element in your layout like this:
```
<html transition:animate="none">
```
This reduced the animations:

![image](https://github.com/withastro/astro/assets/94928215/82c111e3-b870-401a-85c5-6642c0f236d4)

Technically, that only switched off the browser generated fade of the old and new image. There still remains the group animation that scales and moves the new `<html>` element into the place of the old `<html>` element. As this "moves" the whole page into the same position, it should not be visible at all. I'll see whether we can also get rid of those, even now, you should be able to block all visible animations.

As an alternative to setting `transition:none` on the `<html>` element, you can remove all animations of the root during view transitions by adding this to your Layout:

```
<style is:global>
	::view-transition-group(root),
	::view-transition-old(root),
	::view-transition-new(root) {
		animation: none;
	}
</style>
```
You might even replace the word `root` with a `*` and silence all animations of all transition groups at once if you have more than just the `root` group.

**Comment by metonym** [comment]
@martrapp Perfect, thank you for the detailed explanation! Going with the workaround for now.

**Comment by martrapp** [comment]
Good to hear! Ping me on this issue, if there are further questions. The PR mentioned above now also addresses the groups morph animation. Closing this issue now.
