### ISSUE TITLE
Astro cookies should not be usable on a hybrid SSG page without prerender: false when running in dev mode

### ISSUE THREAD

**Issue by Brian-Pob** [withastro/astro#10256]
### Astro Info

```block
Astro                    v4.4.4
Node                     v18.15.0
System                   macOS (arm64)
Package Manager          bun
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

When running in a local dev server, I am able to use Astro cookies when running in hybrid mode **without** `export const prerender = false;`. This persists on all browsers tested on my hardware.

### What's the expected result?

I should not be able to use Astro cookies when running in hybrid mode **without** `export const prerender = false;` on a dev server. I expected some type of warning or perhaps an error.

### Link to Minimal Reproducible Example

https://github.com/Brian-Pob/astro-ssg-cookies-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Cookies related code at https://github.com/Brian-Pob/astro-ssg-cookies-bug/blob/main/src/components/Footer.astro. As discussed on Discord, sounds like a legit issue to me. Thanks for creating this issue!

**Comment by Princesseuh** [comment]
Just bumping it down because it's more so a convenience thing than an actual breaking bug

**Comment by florian-lefebvre** [comment]
My bad! I often suck at assigning the right priority, thank you!

**Comment by ascorbic** [comment]
I've tested this in `astro@4.15.10` and it now correctly logs a warning, so I'm going to close this.
