### ISSUE TITLE
Astro does not respect vite `build`/`serve` commands

### ISSUE THREAD

**Issue by nmattia** [withastro/astro#10262]
### Astro Info

```block
Astro                    v4.3.6
Node                     v20.11.1
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When astro loads the vite config it does not set the correct `command` from vite's `UserConfig`.

For instance, running `astro build` with a plugin that has `apply: "serve"` will load the plugin nonetheless.

```js
// vite.config.js
definedConfig({
  plugins: [
    { apply: "serve",  ...somePlugin() }
 ]
});
```

will apply `somePlugin`. Same goes with `command` is read and used instead of `apply`.

### What's the expected result?

Astro should set the correct `command` when loading the vite config.

NOTE: I could not add a minimal reproducible example because the playground seems broken (errors out on the default example):

```
~/projects/github-ngr3mk
❯ astro build
ech[callSiteLocation@
depd@
@
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:54:14872
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:54:15558
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:54:13457
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:54:10539
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:54:13780
@
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:54:14872
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:54:15558
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:54:13457
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:54:10539
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:189:2456
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:352:378392
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:352:379993
@https://githubngr3mk-ie4y.w-corp-staticblitz.com/blitz.6f234770.js:352:378526]
o
~/projects/github-ngr3mk 1s
❯ echo $?
1
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ngr3mk

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by log101** [comment]
It seems like changing the apply property does make a difference. I created [this](https://stackblitz.com/~/github.com/log101/astro-vite-inconsistency) example based on yours. When `apply: "build"`, `astro build` command works. But when `apply: "serve"` you get an error as expected.

**Comment by bluwy** [comment]
It's working fine for me: https://stackblitz.com/edit/github-co8sdk. I think we need a proper repro to debug this. It's failing for you @nmattia likely because it's running Astro v0.

**Comment by nmattia** [comment]
@bluwy thanks, playground works now.

I've tried to reproduce this and turns out it's a slightly different issue. Here is a repro:

```typescript
// astro.config.ts
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  vite: { /* some vite config, optional */ }
});
```

```typescript
// vite.config.ts
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [
    {
      name: 'a',
      apply: 'serve',
      buildStart() {
        console.log('serve');
      },
    },
  ]
})
```

If you run `npm run build` then you'll see that `serve` is printed to the console. The reason seems to be that if the Astro config is a `.ts` file (and not `/\.[cm]?js$/`) then astro will spin up a `vite` server which will then load `serve`-style plugins.

This is even more confusing in my case (code not shared) where the `vite.config.ts` was in a parent directory and Astro should never even have had to read it (I suspect vite's [`createServer`](https://github.com/withastro/astro/blob/8ce9fffd44b0740621178d61fb1425bf4155c2d7/packages/astro/src/core/config/vite-load.ts#L8) just goes up the directories looking for a vite config).

**Comment by bluwy** [comment]
Thanks! I can repro that now too. I'm not sure why we didn't do it before, but the code you linked should be passing `configFile: false` so it doesn't load any Vite config files. Feel free to send a PR to fix that!

**Comment by nmattia** [comment]
@bluwy there you go! https://github.com/withastro/astro/pull/10360

Full disclosure I didn't really manage to get the codespace working (it was running low on resources) and it's my first PR. There might be a bunch of failures & things missing, but hope it helps!

**Comment by bluwy** [comment]
No problem. The changes seem to be good
