### ISSUE TITLE
Inconsistent JavaScript when 2 buttons in form field

### ISSUE THREAD

**Issue by wildfiremedia** [withastro/astro#10260]
### Astro Info

```block
Astro                    v4.4.5
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @inox-tools/custom-routing
```

### If this issue only occurs in one browser, which browser is a problem?

Firefox

### Describe the Bug

2 buttons in <form> field, it worked fine in dev mode but not working in build mode.

### What's the expected result?

The listener should response to click.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ee8yw2?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wildfiremedia** [comment]
I'm struggle to get the project running in Stackblitz but it seem to fail. The actual code is how it fail when there are 2 buttons in the form that doesn't work in Build mode.

**Comment by wildfiremedia** [comment]
To narrow down, I can't get toggle `hidden` on the form, seem that the hidden is affected by the form?

```
<form id="delete1" class="hidden" action="/hello" method="post"></form>
```

I have also notice the Tailwind styling of bg-green-400 could not override the previous colour I have set. I'm concern that there are some kind of bugs with Tailwind.

**Comment by wildfiremedia** [comment]
To narrow down, the `<form>` could not toggle using `hidden` class, seem that the hidden is affected on the form?

```
<button id="toggleform">Toggle Form</button>
<form id="delete1" class="hidden" action="/hello" method="post"></form>
```

**Comment by mingjunlu** [comment]
Hi @wildfiremedia,

> I'm struggle to get the project running in Stackblitz but it seem to fail.

You might have forgotten to import `Layout` to `src/pages/index.astro`.

---

After importing `Layout`, I executed `npm run build` and deployed manually to Netlify.
Here's the link: https://willowy-dragon-69b766.netlify.app

The `<div id="openmsg">`'s `hidden` class is removed after I click `Button 1`.
The event handler seems to be executed as expected.

**Comment by wildfiremedia** [comment]
When you click "Button 1", a message should display "Dummy button". In your test, "Dummy button" is not hidden by default.

**Comment by mingjunlu** [comment]
Could you update the [minimal reproducible example](https://stackblitz.com/edit/github-ee8yw2?file=src%2Fpages%2Findex.astro) so that we could be on the same page?

**Comment by wildfiremedia** [comment]
@mingjunlu  Please find the comments in the code.
https://stackblitz.com/edit/github-ee8yw2-kvnjow?file=src%2Fpages%2Findex.astro

**Comment by mingjunlu** [comment]
I added the following snippet to `Layout.astro`.

```css
<style>
  .hidden {
    display: none;
  }
</style>
```

And here's the re-deployed site:
https://65df1b82f94f0712bdef4149--willowy-dragon-69b766.netlify.app/

**Comment by wildfiremedia** [comment]
But I'm using Tailwind which `hidden` is a utility class.

**Comment by mingjunlu** [comment]
I've created a minimal repo with Tailwind here:
https://stackblitz.com/edit/github-tcp992?file=src%2Fpages%2Findex.astro

And here's the deployed site:
https://65df2041dc33c3170baba2cd--willowy-dragon-69b766.netlify.app/

**Comment by wildfiremedia** [comment]
Issue it's a problem on my side, on local machine, no error was found on VSCode but work fine on dev. When running build mode, look like the addlistener is being removed, so there is a deeper bug that Astro team need to trace it. Mystery.
