### ISSUE TITLE
Using the `true` option in `server.host` doesn't work

### ISSUE THREAD

**Issue by patrikwalker** [withastro/astro#10264]
### Astro Info

```block
Astro                    v4.4.5
Node                     v20.11.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/alpinejs
                         @astrojs/tailwind
```

### Describe the Bug

The `server.host` option with `output: "server"` option doesn't build the correct output when used with the `true` value. The resulting code just checks for `typeof options.host === "boolean"` and uses `"localhost"` in this case, not considering the actual value of the (boolean) option. The documentation states that true should instead result in listening to all addresses. Our current workaround is to just use `"0.0.0.0"` instead of `true`.
 https://github.com/withastro/astro/blob/e56c428f3bfc3a4a8ed799993f80a29a580cb820/packages/integrations/node/src/standalone.ts#L15

### What's the expected result?

Setting the `server.host` option should result in a server listening to all addresses.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pbnej2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
## Good first issue!
This is an opportunity for astro users to learn about how astro works by fixing a small but real bug. You can expect to get help setting up the dev environment, and understanding the project structure in `#dev` channel of our discord server (https://astro.build/chat). 

### What's the bug?
The node adapter listens on the wrong address when `config.server.host` is set to `true`.

### What's going wrong here?
The node adapter reads [`config.server.host`](https://docs.astro.build/en/reference/configuration-reference/#serverhost) to decide what hostname to start the production server on, when a host is not explicitly provided. When this config is set to `true`, Vite dev server's behavior is to listen on `0.0.0.0`. The node adapter fails to match this behavior, and instead falls back to the default: `"localhost"`.

### Where do I start looking?
The OP has already identified the relevant line of code in the issue description!

**Comment by SatanshuMishra** [comment]
I would love to take a shot at working on this if that's alright! However, this is my first PR with in the astro repository, so I may need some guidance.

**Comment by ematipico** [comment]
@patrikwalker The [CONTRIBUTING.md](https://github.com/withastro/astro/blob/main/CONTRIBUTING.md) is always a good place to start. 

Any questions, feel free to make them here

**Comment by lilnasy** [comment]
A fix would be small and quick enough that assigning someone is not necessary.

@SatanshuMishra I am unassigning to keep this issue open to anyone who wants to create a PR.

**Comment by SatanshuMishra** [comment]
Sounds good! I should have a PR up for this hopefully by the end of the day!

**Comment by lilnasy** [comment]
Hey, sorry for unassigning you. I wasn't sure if you were working on this. I could've waited longer.

**Comment by lilnasy** [comment]
Oops, sorry for unassigning you. I wasn't sure if you were around. I could've waited longer. Sorry for undoing your assignment, @ematipico.
