### ISSUE TITLE
Stackblitz not running

### ISSUE THREAD

**Issue by wildfiremedia** [withastro/astro#10261]
### Astro Info

```block
NA
```

### Describe the Bug

Starting a new project, it has problem running dev and exit, this need fix.

### What's the expected result?

Should be running.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
I assume you are running Firefox. This is an issue on Stackblitz'z side, as it runs just fine in other browsers. We've reported the issue to Stackblitz and they're currently investigating. Sorry for the inconvenience.
