### ISSUE TITLE
`404.astro` Is Not Rendered When Unsupported Locale In `/[lang]/` Is Typed

### ISSUE THREAD

**Issue by Barzi-Ahmed** [withastro/astro#10276]
### Astro Info

```block
Astro                    v4.4.6
Node                     v20.11.1
System                   Windows (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

Hello, 

My website is multilingual, in Astro configuration I've written the following:
```
  i18n: {  
  defaultLocale: "en",
  locales: ["ku", "en", "ar"],
  routing: {
    prefixDefaultLocale: true,
	redirectToDefaultLocale: false
   }
}
```
And this is my directory structure:
![image](https://github.com/withastro/astro/assets/135956133/ab3c2408-edb2-4cdc-b9fe-98300baf70b1)

If I type "/en/contact/" in my browser URL, the page loads successfully, if I type "/en/category/" my 404.astro page loads as expected because that page doesn't exist, but if I type "/fr/contact/" I get the browser's own 404 error page, not my own 404.astro page, I do want it to return 404 because "fr" locale is not supported by my website, but I want it to use my 404.astro not the browser's own 404 page.

P.S.
I'm sorry I don't know how to use CodeSanbox, but I have provided link contain my project source code as zip, please use it for recreating the issue. 

### What's the expected result?

Load my 404.astro page when an unsupported locale is typed in /[lang]/.

### Link to Minimal Reproducible Example

https://filebin.net/lauq80leuinyfohc

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Thanks for reporting the issue!

Unfortunately, the reproduction provided is too big. We ask for a _minimal_ project based on one of our starter templates (https://astro.new) so we can investigate the issue efficiently.

You don't have to use codesandbox. A stackblitz or a github repo works too!

**Comment by lilnasy** [comment]
Also, could you clarify whether `404.astro` is ignored in the dev server, or in the production server?

**Comment by lilnasy** [comment]
@Barzi-Ahmed You have a middleware that returns an empty 404 response. Could that be the reason `404.astro` doesn't render?
