### ISSUE TITLE
Unable to Ignore irrelevant files in build

### ISSUE THREAD

**Issue by tadaspetra** [withastro/astro#10289]
### Astro Info

```block
Astro                    v3.6.4
Node                     v20.5.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/react
                         @astrojs/mdx
                         @astrojs/tailwind
```

### Describe the Bug

I am using Obisidian to edit my Markdown files, and the flow is so nice. However, it does break the site in local development.

I have the Obsidian files that don't need to be pushed added to the `.gitignore` so the production site doesn't get affected, but I cannot work with it locally.

<img width="402" alt="Screenshot 2024-03-01 at 8 22 04 AM" src="https://github.com/withastro/astro/assets/60107328/cd7544dd-a77e-459b-b39f-29aec1499681">

### What's the expected result?

Would be great if there was an `.astroignore` file, that ignored everything from the build script, or something in the Astro defineConfig that let you ignore these files from the build process. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-y7uzqk?file=src%2Fcontent%2Fhello.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Can you explain what do you mean by ignoring from the build process? If you don't want to build a file make sure it's not imported in your source code. If the file is in content collections, you can also [prefix with an underscore](https://docs.astro.build/en/guides/content-collections/#what-are-content-collections) to ignore the content.

**Comment by tadaspetra** [comment]
Yes, the files are in the content collections. Prefixing with an underscore works here, however it would be great if there was a way to do exclude it with a configuration somewhere so the file name doesn't need to be changed.

**Comment by bluwy** [comment]
The way we support excluding for now is through the underscore. It would be harder to teach if there's many ways to achieve the same behaviour. I'll close this for now as there's a solution to it today.

**Comment by MelleNi** [comment]
Is there a way to achieve the same thing outside of content collections?

**Comment by almereyda** [comment]
Excluding files by not including them into the globbing pattern of a content collection has helped here to avoid issues with an Obsidian vault inside the same directory:

- src/content/config.ts

```ts
import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { docsSchema } from "@astrojs/starlight/schema";

export const collections = {
  docs: defineCollection({
    loader: glob({ pattern: "**/[^_]*.{md,mdx}", base: "src/content/docs" }),
    schema: docsSchema(),
  }),
};
```

<details><summary>References</summary>

- [Astro Content Loader API | Docs](https://docs.astro.build/en/reference/content-loader-reference/)
- [Astro Glob Loader Config Generator](https://astro-glob-loader-config-generator.netlify.app/)

</details>
