### ISSUE TITLE
Astro.props is type as any when use Polymorphic

### ISSUE THREAD

**Issue by RodrigoTomeES** [withastro/astro#10347]
### Astro Info

```block
Astro                    v4.4.13
Node                     v20.9.0
System                   Windows (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
```

### Describe the Bug

Astro.props is type as any

![image](https://github.com/withastro/astro/assets/13077343/3e0fa762-9c0b-4f6e-a49e-0e9b948f0c9d)

```astro
---
import type { HTMLTag, Polymorphic } from "astro/types"

type Props<Tag extends HTMLTag> = Polymorphic<{
	as: Tag
	variant: keyof typeof variantClasses
	color: keyof typeof colorClasses
}>

const { as: Tag, class: className, variant, color, ...props } = Astro.props

const variantClasses = {
	h2: "text-lg font-medium uppercase lg:text-2xl",
	h3: "text-2xl font-semibold uppercase",
	body: "text-xl",
	medium: "text-md",
}

const colorClasses = {
	white: "text-white",
	black: "text-black",
	primary: "text-accent",
	neutral: "text-neutral-300",
}

const classes = [
	variantClasses[variant as keyof typeof variantClasses],
	colorClasses[color as keyof typeof colorClasses],
	className,
]
---

<Tag class:list={classes} {...props}>
	<slot />
</Tag>
```

### What's the expected result?

That has the types of Props.

In the codesandbox the error not appear but try it in vscode and it will appear

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yq21np?file=tsconfig.json,src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
I suspect that this is a compiler issue, most likely related to https://github.com/withastro/compiler/issues/927 in some ways

**Comment by lilnasy** [comment]
Maybe we need to document that `Props` needs default values when it is a generic.

```diff
-type Props<Tag extends HTMLTag> = Polymorphic<{
+type Props<Tag extends HTMLTag = HTMLTag> = Polymorphic<{
	as: Tag
	variant: keyof typeof variantClasses
	color: keyof typeof colorClasses
}>
```

**Comment by RodrigoTomeES** [comment]
> Maybe we need to document that `Props` needs default values when it is a generic.
> 
> ```diff
> -type Props<Tag extends HTMLTag> = Polymorphic<{
> +type Props<Tag extends HTMLTag = HTMLTag> = Polymorphic<{
> 	as: Tag
> 	variant: keyof typeof variantClasses
> 	color: keyof typeof colorClasses
> }>
> ```

The documentation doesn't mention anything about requiring a default value. 🤔

https://docs.astro.build/en/guides/typescript/#polymorphic-type

**Comment by RodrigoTomeES** [comment]
> I should clarify, I meant that we _should_ mention it.

I tried this solution but now I have this error:
<img width="852" alt="Screenshot 2024-03-07 at 12 16 10" src="https://github.com/withastro/astro/assets/13077343/642b7f53-7686-4aa1-b533-94350da9f0bb">

**Comment by Eveeifyeve** [comment]
I felt this would be a cool idea cause it will help devs with type safety.

**Comment by nasheomirro** [comment]
> I tried this solution but now I have this error: <img alt="Screenshot 2024-03-07 at 12 16 10" width="852" src="https://private-user-images.githubusercontent.com/13077343/310857211-642b7f53-7686-4aa1-b533-94350da9f0bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTkyMjksIm5iZiI6MTcxMDI1ODkyOSwicGF0aCI6Ii8xMzA3NzM0My8zMTA4NTcyMTEtNjQyYjdmNTMtNzY4Ni00YWExLWI1MzMtOTQzNTBkYTlmMGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE1NTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3N2ZhY2VhMWYxMjZkNjk0OGY2M2Q2YjdiMGY3ZjJiNGY5ZDI1OGYwMjdmMzY3NjhkYzJlM2YzYzAwZTZjYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gVlsVmlkd8n6dvccun1xiUaEYgTF_GjSmC0ZkCSiq3c">

try adding a default value for the tag as well. I'm not sure what changed but it seems the `Polymorphic` type now makes `as` optional, correct me if I'm wrong but I remember the previous behavior was that the component requires you to always provide an `as` prop.

**Comment by RodrigoTomeES** [comment]
> > I tried this solution but now I have this error: <img alt="Screenshot 2024-03-07 at 12 16 10" width="852" src="https://private-user-images.githubusercontent.com/13077343/310857211-642b7f53-7686-4aa1-b533-94350da9f0bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTkyMjksIm5iZiI6MTcxMDI1ODkyOSwicGF0aCI6Ii8xMzA3NzM0My8zMTA4NTcyMTEtNjQyYjdmNTMtNzY4Ni00YWExLWI1MzMtOTQzNTBkYTlmMGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE1NTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3N2ZhY2VhMWYxMjZkNjk0OGY2M2Q2YjdiMGY3ZjJiNGY5ZDI1OGYwMjdmMzY3NjhkYzJlM2YzYzAwZTZjYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gVlsVmlkd8n6dvccun1xiUaEYgTF_GjSmC0ZkCSiq3c">
> 
> ~try adding a default value for the tag as well.~ I'm not sure what changed but it seems the `Polymorphic` type now makes `as` optional, correct me if I'm wrong but I remember the previous behavior was that the component requires you to always provide an `as` prop.
> 
> Edit: In addition to adding a default value, you need to cast it with `any` as well, just the easiest work-around I've found so far:
> 
> ```astro
> ---
> import type { Polymorphic, HTMLTag } from "astro/types";
> 
> type Props<T extends HTMLTag = HTMLTag> = Polymorphic<{ as: T }>;
> const { as: Tag = "div" as any, ...attrs } = Astro.props;
> ---
> 
> <Tag {...attrs}>
>   <slot />
> </Tag>
> ```

You are right, with the default value as is optional

**Comment by matthewp** [comment]
Not providing a type argument default is an error. You can see this by assigning a variable to the type like so:

<img width="241" alt="Screen Shot 2024-05-13 at 3 23 47 PM" src="https://github.com/withastro/astro/assets/361671/6d7c2a7d-7f01-4956-bdf2-ed0bdc998e82">

Since your type has an error then `Astro.props` cannot be declared as that type, which is why it's showing as `any`. Closing as there's nothing that can be done here.
