### ISSUE TITLE
Unable to `import` files in API routes in `@astrojs/vercel>7.0.0`

### ISSUE THREAD

**Issue by joe-bell** [withastro/astro#10380]
### Astro Info

```block
Astro                    v4.4.15
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

Went down a big ol' rabbit hole this weekend trying to upgrade to the latest version of `@astrojs/vercel` – unfortunately I wasn't able to find a way forwards

In an earlier issue I raised (https://github.com/withastro/astro/issues/8402), I experienced issues importing local files within API routes via Node.js `path` methods

The solution that ended up working in this case was to use `URL` with the relative path:

```ts
const imgUrl = new URL('../../../src/images/hello-there.jpg', import.meta.url);
```

You can see this working via the following links:
- Code: https://github.com/joe-bell/astro-bug-vercel-includefiles
- Preview: https://astro-bug-vercel-includefiles.vercel.app

## Issue

In any version after `@astrojs/vercel@7.0.0` I am unable to use this import solution anymore
- Code: https://github.com/joe-bell/astro-bug-vercel-includefiles/pull/2
- Preview: https://astro-bug-vercel-includefiles-7nmxeo4io-joebell.vercel.app
- Error Log: https://github.com/withastro/astro/assets/7349341/795f8091-da9c-47d2-b912-82e296733fad

### Additional Issue

> [!NOTE]
> This may be fixed by the above being resolved

In the stable implementation above (using `@astrojs/vercel@7.0.0`) I am unable to import files in an API route that **isn't** in the root of the `/pages` directory 
- Code: https://github.com/joe-bell/astro-bug-vercel-includefiles/pull/1
- Preview: https://astro-bug-vercel-includefiles-git-nested-page-joebell.vercel.app/api/hello-there
- Error Log: https://github.com/withastro/astro/assets/7349341/56f5f484-c198-4d9c-a6b7-9ba478a58b73

### What's the expected result?

Mimic behaviour of the stable implementation:
https://github.com/joe-bell/astro-bug-vercel-includefiles

### Link to Minimal Reproducible Example

https://github.com/joe-bell/astro-bug-vercel-includefiles/pull/2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Going to remove the bug label, trying to understand if it is actually possible to do FS operations in a serverless environment.

**Comment by joe-bell** [comment]
The issue is that the endpoint no longer works at all and errors in Vercel 😢 (before vs. after provided in the description above)

This was an approach recommended to me in #8402, and stopped working on versions later than `@astrojs/vercel@7.0.0` 

Vercel themselves recommend using this approach for `@vercel/og`:
https://vercel.com/docs/functions/og-image-generation/og-image-examples#using-a-custom-font (Click "other framework")

If this isn't an approach Astro recommends, then I would really appreciate advice on what the alternative should be instead

**Comment by ematipico** [comment]
Two things:
- can you see if there's some error? Just saying that doesn't work doesn't help. Try with some try catch/catch or more logging
- the snippet shows that they use **fetch** instead of **readFile**. Did you try that approach?

**Comment by joe-bell** [comment]
After a chat with @FredKSchott, I tried out using `import` for files instead

Unfortunately Vite's built-in `?raw` query spits out unusable data, but I was able to workaround the issue by using `vite-plugin-arraybuffer` to get what I needed for this:

https://github.com/joe-bell/astro-bug-vercel-includefiles/pull/3

I think it's say this is an upstream issue with Vite (https://github.com/vitejs/vite/issues/12366), however, I do think some docs for importing files within Astro would be super valuable (this isn't the first time I've ran into this hurdle!)

Continuing the convo here and marking as closed – thanks 🙏 
https://github.com/withastro/roadmap/discussions/679
