### ISSUE TITLE
@shikijs/twoslash doesn't work

### ISSUE THREAD

**Issue by TheOrdinaryWow** [withastro/astro#10382]
### Astro Info

```block
Astro                    v4.4.15
Node                     v18.17.0
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Safari, Arc(Chrome)

### Describe the Bug

Used the official `Blog` template, made minimal changes required to enable `@shikijs/twoslash`, nothing happened.

Modified config is followed:

```mjs
import {defineConfig} from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';

import tailwind from "@astrojs/tailwind";
import {transformerTwoslash} from "@shikijs/twoslash";

export default defineConfig({
    site: 'https://example.com',
    markdown: {
        syntaxHighlight: 'shiki',
        shikiConfig: {
            theme: 'monokai',
            transformers: [
                transformerTwoslash(),
            ],
        }
    },
    integrations: [mdx(), sitemap(), tailwind()]
});
```

I have already checked Pull #4292 as well as Issue #4258, and have tried using `remarkPlugins` instead of Shiki's `transformers`, yet none works.

I wonder if it's me did something wrong, or it'd be nice if there's a solution.

### What's the expected result?

Twoslash will show up, as in [install documentation](https://shiki.style/packages/twoslash#install).

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/sad-payne-l8gjl3

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kyrylolvov** [comment]
@TheOrdinaryWow Were you able to fix the issue?

**Comment by kyrylolvov** [comment]
@bluwy So for twoslash to work, an update to Astro 4.5, css import and writing `ts twoslash` is enough?

**Comment by bluwy** [comment]
Yes. You'll get the default styling provided by `import '@shikijs/twoslash/style-rich.css'` which you should see applied in the rendered code blocks.

**Comment by oxwazz** [comment]
@TheOrdinaryWow @bluwy, i have example commit for integration **@shikijs/twoslash** & fix popup not fully displayed

i use **floating-ui** for the implementation, the commit little bit messy but, easy to follow. 

commit: [integration twoslash](https://github.com/oxwazz/oxwazz.github.io/commit/463a316a68d71d5be3ef8a679d64ab7e23ce13b4)

![image](https://github.com/withastro/astro/assets/58234878/26417eb5-3ccb-4f82-9c00-2c8cceeda770)
