### ISSUE TITLE
Cloudflare runtime no longer accessible from 404.astro

### ISSUE THREAD

**Issue by TorbjornHoltmon** [withastro/astro#10421]
### Astro Info

```block
Astro                    v4.5.2
Node                     v21.6.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             none
```

### Describe the Bug

Cloudflare pages runtime bindings are no longer accessible from the 404.astro page.

Download repro, build, and run `pnpm preview`.

On the index page, you will see the object keys for `Astro.locals.runtime` and `Astro.locals`. Here you will see that the runtime is accessible.

Going to a page that does not exist and landing on the 404.astro page, you will see that the object keys are now empty.

### What's the expected result?

Cloudlfare pages bindings should be accessible from the 404.astro page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xsxm5k?file=src%2Fpages%2F404.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by hkbertoson** [comment]
I don't see any bindings defined in your Config. I just tested this out on my repo and it works just fine. I can access `Astro.locals` on all my pages.

**Comment by TorbjornHoltmon** [comment]
![CleanShot 2024-03-13 at 16 21 19@2x](https://github.com/withastro/astro/assets/46750288/c6a3799c-42a3-40cb-9d19-4cfdece5e735)
![CleanShot 2024-03-13 at 16 21 47@2x](https://github.com/withastro/astro/assets/46750288/84b60ca3-13d4-4a00-894a-a16ce9181596)

**Comment by hkbertoson** [comment]
Oh I see it now. Interesting. Have you checked out the Discord? [Setting Up Cloudflare Functions for an Astro Project](https://discord.com/channels/830184174198718474/1208922478253056011)

This post helped me a lot. 

Then I also made this post as well that helped. [Cloudflare API Routes](https://discord.com/channels/830184174198718474/1214769775356411915)

The docs need some work I have noticed. 

You don't need to run `wrangler pages dev ./dist --kv KV`  You just need to define your bindings in your `astro.config` and then define them in the Cloudflare Dashboard.

**Comment by TorbjornHoltmon** [comment]
This is issue is probably related to the very recent changes to how 404.astro works.

The bindings you define in the Astro config is for local development only.

Running the built app through wrangler with bindings is basically the same thing as running it Cloudflare.

I am not asking for help here, I am just reporting a reproducible bug.

**Comment by lilnasy** [comment]
Do you know if this behavior changed with a specific version?
