### ISSUE TITLE
Its not possible to force a full page reload using the navigate function

### ISSUE THREAD

**Issue by Arttii** [withastro/astro#10424]
### Astro Info

```block
Astro                    v4.1.0
Node                     v18.14.1
System                   Linux (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/react
                         @astrojs/tailwind
                         astro-auth
                         astro-icon
```

### Describe the Bug

When using links its possible to force  a full-page reload, but let's say when initiating a navigation on a button click from as astro island using the `navigate` function does not expose the same functionality.

### What's the expected result?

There should be an option to force a full page reload.

### Link to Minimal Reproducible Example

tbd

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You can use the normal JavaScript way to navigate between pages to have a full page reload. `window.location.href = "your url";`

`navigate()` is specific to View Transitions.
