### ISSUE TITLE
`@astrojs/vercel` adapter isn't building server endpoints.

### ISSUE THREAD

**Issue by dreyfus92** [withastro/astro#10440]
### Astro Info

```block
Astro                    v4.5.3
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          bun
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/prefetch
                         astro-expressive-code
                         @astrojs/mdx
                         @astrojs/react
                         astro-icon
```

### Describe the Bug

When building the project, the adapter does not add the endpoint when setting the `output` to hybrid and `prerender` to false.

> [!NOTE]
> If you remove the prerender or set it to true which is the def in `hybrid` mode it will add it and recognize it as a λ but it acts as a static endpoint.

### What's the expected result?

To add that server endpoint to the bundle.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-qrtbuk?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dreyfus92** [comment]
Hey @arnvgh, that's correct, the adapter doesn't support preview 😁 For some reason the adapter isn't bundling the server endpoints while this conditions are met.

**Comment by mingjunlu** [comment]
I cloned the minimal reproduction, made the endpoint return the current timestamp, then deployed to Vercel. Here's the link of the API endpoint:
https://withastro-astro-qrtbuk.vercel.app/api/hello

Each time I visit the URL, it returns a different timestamp. It seems to act like a dynamic endpoint. Perhaps it's the output message while building that confuses people?

**Comment by dreyfus92** [comment]
@mingjunlu, can you share a screenshot building locally that project?

**Comment by mingjunlu** [comment]
```
~/Downloads/withastro-astro-qrtbuk (main) $ npm run build

> @example/basics@0.0.1 build
> astro build

14:41:27 [build] output: "hybrid"
14:41:27 [build] directory: /Users/xxxxx/Downloads/withastro-astro-qrtbuk/.vercel/output/
14:41:27 [build] adapter: @astrojs/vercel/serverless
14:41:27 [build] Collecting build info...
14:41:27 [build] ✓ Completed in 53ms.
14:41:27 [build] Building hybrid entrypoints...
14:41:27 [vite] ✓ built in 411ms
14:41:27 [build] ✓ Completed in 427ms.

 prerendering static routes 
14:41:27 ▶ src/pages/index.astro
14:41:27   └─ /index.html (+4ms)
14:41:27 ✓ Completed in 11ms.

14:41:27 
 finalizing server assets 

14:41:27 [build] Rearranging server assets...
14:41:27 [WARN] [@astrojs/vercel/serverless] Your project is being built for Node.js 20 as the runtime, which is currently in beta for Vercel Serverless Functions.
14:41:27 [@astrojs/vercel/serverless] Bundling function ../../_functions/entry.mjs
14:41:28 [build] Server built in 1.13s
14:41:28 [build] Complete!
```

**Comment by dreyfus92** [comment]
I just found what happened, it isn't the adapter is my package manager. Thank you both for taking the time to test this @mingjunlu @arnvgh. I'm gonna close this 😁
