### ISSUE TITLE
Hot reload not working in dev

### ISSUE THREAD

**Issue by derekdevv** [withastro/astro#10450]
### Astro Info

```block
Astro                    v4.5.4
Node                     v21.6.2
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Firefox and Safari have the same issue

### Describe the Bug

after npm create astro@latest, and choosing all default options in setup wizard, run npm run dev, then change the text in index.astro (I changed 'Tweak the "Welcome to Astro" message above.' to 'hello'), there's no change on the browser.

### What's the expected result?

I expect hot reload to work and the updated text would show on the browser.

im unable to reproduce on stackblitz, but will include a github repo

### Link to Minimal Reproducible Example

https://github.com/derekdevv/test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
https://github.com/withastro/astro/assets/69170106/b4971301-3e46-43d7-9b9e-74472e7de30f

It seems to work just fine.

**Comment by derekdevv** [comment]
> video.mp4 
> 
> It seems to work just fine.

Hmm im not sure why it doesn’t work on mine, do you have any suggestion on how should i investigate this or things that i should try? Thanks!

**Comment by derekdevv** [comment]
my apologies, seems like the issue is resolved after a restart of my machine.
