### ISSUE TITLE
Astro DB - deploy to Vercel fails - Cannot find module 'astro:db' or its corresponding type declarations.

### ISSUE THREAD

**Issue by thomasledoux1** [withastro/astro#10467]
### Astro Info

```block
Astro                    v4.5.5
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/react
                         auto-import
                         @astrojs/code-snippets
                         @astrojs/mdx
```

### Describe the Bug

Locally everything is working fine when using Astro DB in my code, but once deployed to Vercel I keep getting build errors like :

```
19:06:24.154 | db/config.ts:1:47 - error ts(2307): Cannot find module 'astro:db' or its corresponding type declarations.
19:06:24.155 |  
19:06:24.155 | 1 import { column, defineDb, defineTable } from "astro:db";
19:06:24.155 | ~~~~~~~~~~
19:06:24.156 |  
19:06:24.159 | db/seed.ts:1:30 - error ts(2307): Cannot find module 'astro:db' or its corresponding type declarations.
19:06:24.159 |  
19:06:24.159 | 1 import { db, PageView } from "astro:db";
19:06:24.160 | ~~~~~~~~~~
19:06:24.160 |  
19:06:29.193 | src/pages/page-views.astro:109:5 - error ts(2578): Unused '@ts-expect-error' directive.
19:06:29.193 |  
19:06:29.193 | 109     // @ts-expect-error
19:06:29.193 | ~~~~~~~~~~~~~~~~~~~
19:06:29.193 | src/pages/page-views.astro:101:7 - error ts(2578): Unused '@ts-expect-error' directive.
```

### What's the expected result?

The type should be generated, also when deploying to Vercel.
I tried to run "astro sync", but that didn't generate anything in the code, so nothing additional to deploy to Vercel..

### Link to Minimal Reproducible Example

https://github.com/thomasledoux1/website-thomas-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is a type error caused by the fact that `astro sync` (both the command, and the internal `sync` function) does not generate the types for Astro DB before `astro check` runs.

A workaround in the meantime is removing `astro check` from your build script.

**Comment by bholmesdev** [comment]
@thomasledoux1 `astro check` and `astro sync` now generate types in v0.8.6! Can you try installing the latest `@astrojs/db` package?

**Comment by thomasledoux1** [comment]
@bholmesdev that fixed it! Thanks :)
