### ISSUE TITLE
Video doesn't autoplay after navigating pages with View Transitions

### ISSUE THREAD

**Issue by alexnguyennz** [withastro/astro#10461]
### Astro Info

```block
Astro                    v4.5.5
Node                     v20.9.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Safari

### Describe the Bug

A video with `autoplay` doesn't seem to play after navigating to the page on Safari (iOS) on a site using View Transitions. This issue doesn't happen with `fallback="none"`.

### What's the expected result?

Video plays - for the StackBlitz example, navigate to the About page

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yj7z7q

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by alexnguyennz** [comment]
After looking at each fallback, it looks like this is not related to the View Transitions but changing the DOM that some browsers don't like:

https://stackoverflow.com/questions/17994666/video-auto-play-is-not-working-in-safari-and-chrome-desktop-browser

The issue also doesn't happen when using the video's `src` attribute instead of a separate `source` element.

```
<video id="video" src="/mov_bbb.mp4" autoplay muted playsinline></video>
```

So I will close this as this looks like a browser issue and a script can be used to manually play it.

**Comment by JonasGruenwald** [comment]
Hm I'm facing the same issue, but the mentioned workaround seems to only work partially for me.

If I do `video` with `source` inside, results are like this:

* Chrome: Works without issues
* Safari: doesn't work after view transition
* Firefox: doesn't work after view transition

If I do `video` with `src` attribute, or manually calling `play()`, it's like this:

* Chrome: Works without issues
* Safari: Works without issues
* Firefox: doesn't work after view transition

I can reproduce this on your linked example @alexnguyennz – firefox does not play the video even after switching to using src directly, might be worth re-opening the issue, or is there a way to work around this?
