### ISSUE TITLE
CSS imported into (solid) islands is not loaded on subsequent page loads when using view transitions and client:only in dev

### ISSUE THREAD

**Issue by knpwrs** [withastro/astro#10466]
### Astro Info

```block
Astro                    v4.5.5
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/solid-js
                         @astrojs/mdx
                         @sentry/astro
```

### If this issue only occurs in one browser, which browser is a problem?

I have seen this happen in both Chrome and Firefox.

### Describe the Bug

When importing CSS into a solid island (may be other islands too, I haven't tested other frameworks), the CSS loads fine on the initial page load, but when you navigate away and come back (with view transitions) the CSS is not loaded properly and the page looks broken.

This only appears to affect `client:only` (at least when using `client:visible` the CSS always loads correctly).

The included example sets builds on the official solid example. Click on the `Another page` link and then click the `Counter` link.

The fix is to move the CSS import from `Counter.tsx` to `index.astro`, then the CSS is always loaded properly under every circumstance, including with view transitions and `client:only`.

### What's the expected result?

CSS imported in islands should load properly when navigating around the site using view transitions and `client:only`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-eqw3jl?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
cc @martrapp

This only seems to affect the dev server, probably because of how Vite injects the CSS with a wonky link in the `head`, not sure.

**Comment by martrapp** [comment]
I'm away from keyboard this week ;-)
The client-side router got special support for client:only styles some month ago. 
This may be a degression from recent changes or solid specific.
Can look deeper into this at the end of the week.
