### ISSUE TITLE
Link innerHTML disappearing on click

### ISSUE THREAD

**Issue by Markeyjuju** [withastro/astro#10482]
### Astro Info

```block
Astro                    v4.3.2
Node                     v18.17.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

ios Safari

### Describe the Bug

When clicking this link component with a glitch effect, the text content disappears. 

The more interesting thing is that the effect works on desktop just fine, and on mobile across the website. 

The dropdown menu, on mobile is where the problem is. Although its the same component.

### What's the expected result?

For every instance of the component to work.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-buvjmg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Markeyjuju** [comment]
Well I am actually not sure that it is an astro issue...😅 It may be my code, it may be safari. But the issue is that this component doesn't work consistently on ios safari.

**Comment by Markeyjuju** [comment]
I don't think it's an issue on my code, since it works just fine on desktop and partially on ios. I don't think it's ios safari since the component does work in some instances. 

It's just that weirdly the innerHTML disappears instead of firing the effect on click in my mobile menu. I also doubt it's the styles since upon inspection, the text content between the tags that disappears. 

So that tells me that the javascript runs, just incorrectly.

**Comment by Princesseuh** [comment]
Closing because this doesn't seem to be an issue with Astro,
