### ISSUE TITLE
error using where clause on db.delete() in astro:db

### ISSUE THREAD

**Issue by MatthewSaintBull** [withastro/astro#10489]
### Astro Info

```block
Astro                    v4.5.5
Node                     v18.19.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         astro:db
                         @astrojs/db/file-url
                         @astrojs/react
```

### Describe the Bug

Following the docs [here](https://docs.astro.build/it/guides/astro-db/)
trying to delete an item from the db with this code

```javascript
import type { APIRoute } from "astro";
import { db, Project } from 'astro:db';

export const DELETE: APIRoute = async (ctx) => {
    const projectId = Number(ctx.params.id);
    await db.delete(Project).where({
        id: projectId
    });
    return new Response(null, { status: 204 });
}
```

I get this error 

> Object literal may only specify known properties, and 'prjId' does not exist in type 'SQL<unknown>'.ts(2353)

and triggering the function, the server crashes with this error

> thread '<unnamed>' panicked at src/statement.rs:47:9:
not yet implemented: unsupported type
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      npm run dev

I solved using the "eq" method instead of a JSON passed in the where clause. Like this

```javascript
import type { APIRoute } from "astro";
import { db, eq, Project } from 'astro:db';

export const DELETE: APIRoute = async (ctx) => {
    const projectId = Number(ctx.params.id);
    await db.delete(Project).where(eq(Project.id, projectId));
    return new Response(null, { status: 204 });
}
```

Does someone knows why it happens this? 

Thanks

### What's the expected result?

I expect to see that there is a deletion on my db

### Link to Minimal Reproducible Example

--- If needed I will create later

**Comment by ematipico** [comment]
I believe the docs are incorrect. Checking the drizzle ORM APIs, and I can't find a reference where you can use `where()` by passing an object. I will check with the docs team.

**Comment by ematipico** [comment]
Raised a PR here: https://github.com/withastro/docs/pull/7482

Closing. Users should use the `eq` function. "Raw" objects aren't supported.

**Comment by MatthewSaintBull** [comment]
> Raised a PR here: [withastro/docs#7482](https://github.com/withastro/docs/pull/7482)
> 
> Closing. Users should use the `eq` function. "Raw" objects aren't supported.

Thanks
