### ISSUE TITLE
astro:db filtering infers type to `any`

### ISSUE THREAD

**Issue by robbertstevens** [withastro/astro#10486]
### Astro Info

```block
Astro                    v4.5.6
Node                     v20.9.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         astro:db
                         @astrojs/db/file-url


Linux on WSL (no idea if that matters)
```

### Describe the Bug

I have a table: 
```typescript
const Pack = defineTable({
  columns: {
    id: column.text({ primaryKey: true }),
    name: column.text(),
    cover_image: column.text(),
  },
});
```

I query the table like this 
```typescript
const pack = await db
  .select()
  .from(Pack)
  .where(eq(Pack.id, String(id)))
```

The inferred type of pack constant is any. Without filtering the type is `SelectResult[]` with filtering (`.where`, `.limit`, etc) the type is some kind of `SQLLiteSelectWithout<T>` variant.

When adding `.get` to get a single items it also infers to a `any`.

![image](https://github.com/withastro/astro/assets/726557/2334f7b4-8c1e-407c-9bbd-89dd8824ba98)
![image](https://github.com/withastro/astro/assets/726557/9b637f46-cc9e-4924-a126-1c2eadeafebc)
![image](https://github.com/withastro/astro/assets/726557/3e7685c6-8dbf-4548-a8a2-2cb46736985b)
![image](https://github.com/withastro/astro/assets/726557/59147894-ad42-4e35-9ac8-a94ceb07539d)

Added the link to the discord topic: https://discord.com/channels/830184174198718474/1218658824668315798/1218658824668315798

### What's the expected result?

I would expect that the type is inferred correctly. In this case the type would either be something that represent the table `Pack` or an array that represents `Pack[]` I guess that would mean a `SelectResult` or `SelectResult[]`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bjgty7?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
I see the types being simplified correctly in the repro.

![image](https://github.com/withastro/astro/assets/69170106/93a3b85a-e488-4972-9a2f-f0d3f9af7d86)

**Comment by robbertstevens** [comment]
Strange, any idea why ide would my give the wrong types?

**Comment by lilnasy** [comment]
Could there be something else about your project that's interfering? Is the schema more complex? Do you see the correct types in another environment - codespaces or gitpod for example?

**Comment by matthewp** [comment]
Did you see this before starting `astro dev` or `astro build`? The types are not built before this, so you could definitely see `any`s and other type problems before this.

**Comment by robbertstevens** [comment]
> Could there be something else about your project that's interfering? Is the schema more complex? Do you see the correct types in another environment - codespaces or gitpod for example?

Yes on my windows and op my macbook I have the same issue. 



> Did you see this before starting `astro dev` or `astro build`? The types are not built before this, so you could definitely see `any`s and other type problems before this.

I get this during `astro dev` and after `astro build` 

my tsconfig
```json
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~app/*": ["src/*"]
    }
  }
}
```

my astro.config.mjs
```javascript
export default defineConfig({
  integrations: [tailwind(), db()],
  output: "server",
  adapter: vercel()
});
```

env.d.ts
```typescript
/// <reference path="../.astro/db-types.d.ts" />
/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
```

db-types.d.ts
```
declare module 'astro:db' {
	export const Pack: import("@astrojs/db/runtime").Table<
		"Pack",
		{"id":{"type":"text","schema":{"unique":true,"deprecated":false,"name":"id","collection":"Pack","primaryKey":true}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Pack","primaryKey":false,"optional":false}},"coverImage":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"coverImage","collection":"Pack","primaryKey":false,"optional":false}},"createdAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"createdAt","collection":"Pack","default":{"__serializedSQL":true,"sql":"CURRENT_TIMESTAMP"}}}}
	>;
}
```

**Comment by robbertstevens** [comment]
Maybe `astro check` gives some insight 
![image](https://github.com/withastro/astro/assets/726557/bab70a69-b090-4729-90ae-1751383cdebe)

**Comment by robbertstevens** [comment]
It looks like it's an problem with IntelliJ IDEA, when I run the code in VScode then I do get the correct typings.

**Comment by lilnasy** [comment]
Is the error from `astro check` unrelated?

**Comment by robbertstevens** [comment]
I am 100% certain it's the Intellij IDEA Astro plugin that doesn't work.
