### ISSUE TITLE
API endpoint crashes when using formData

### ISSUE THREAD

**Issue by Reyno-Skeps** [withastro/astro#10490]
### Astro Info

```block
Astro                    v4.4.7
Node                     v18.19.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  none
Integrations             @astrojs/vue
                         @astrojs/tailwind
                         @storyblok/astro
                         @astrojs/partytown
                         @astrojs/sitemap
```

### Describe the Bug

When copying the exact API code example from [the docs](https://docs.astro.build/en/recipes/build-forms-api/#recipe) and submitting the request you'll get the following error: 

> Request.formData: Could not parse content as FormData

This is happening from v4.4.7 and onwards.

### What's the expected result?

That after submitting the request I get the message `"Missing required fields"` or `"Success!"`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7xqxvl?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@Reyno-Skeps This is intended. We also log a warning:

```
11:24:58 [WARN] [router] /api/v1/contact POST requests are not available for a static site. Update your config to `output: 'server'` or `output: 'hybrid'` to enable.
```

**Comment by Reyno-Skeps** [comment]
@ematipico Right, forgot to add the `output: hybrid` in the config, which I have locally.

What I get from your comment that from v4.4.7 onwards we need to add `export const prerender = false;` to API endpoints which seems a bit weird to me since API endpoints are never static. But yes then it works. Thanks
