### ISSUE TITLE
SolidJS client:only don't work `Unrecognized value. Skipped inserting`

### ISSUE THREAD

**Issue by SyntheticBird45** [withastro/astro#10500]
### Astro Info

```block
Astro                    v4.5.6
Node                     v21.6.2
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/preact
                         @astrojs/solid-js
```

### If this issue only occurs in one browser, which browser is a problem?

Firefox

### Describe the Bug

The following Solid component:
```tsx
// /src/components/alert.tsx
export function AlertList() {
	return <div></div>;
}
```
Failed to render in Firefox using the following astro document:
```astro
// /src/components/Alerts.astro. Imported into index.astro
---
import { AlertList } from '../components/alert.tsx';
---
<ul class="bg-[black] bg-opacity-20 h-screen w-72 sm:w-96 absolute right-0 top-0">
	<AlertList client:only="solid-js" />
</ul>
```
Returns `Unrecognized value. Skipped inserting` in firefox console. Works perfectly fine without `client:only` directive

### What's the expected result?

No warning in console and div spawned

Warning: solid isn't installed on the stackblitz link

### Link to Minimal Reproducible Example

https://github.com/SyntheticBird45/astro-solid-reproducible

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mingjunlu** [comment]
Hi @SyntheticBird45,

Could you update the minimal reproduction example to make sure SolidJS is installed?

**Comment by SyntheticBird45** [comment]
Tested and published at https://github.com/SyntheticBird45/astro-solid-reproducible

**Comment by SyntheticBird45** [comment]
Also prior to what I thought. Chrome also send the same warning message

**Comment by mingjunlu** [comment]
@SyntheticBird45 Thanks for providing an updated reproduction!

I noticed that you're using both and SolidJS and Preact in the reproduction repo. However, the `astro.config.mjs` doesn't specify which files belong to which framework. According to Astro Docs, when [combining multiple JSX frameworks](https://docs.astro.build/en/guides/integrations-guide/solid-js/#combining-multiple-jsx-frameworks), it is required to use the `include` config.

After I add those includes, the warning in console goes away. Could you try if this works?

```diff
export default defineConfig({
  // Build options
  build: {
    format: 'preserve'
  },
  // Integrations and settings
  integrations: [
    tailwind({
      nesting: false, // CSS nesting isn't yet stabilized in all browsers
      applyBaseStyles: true // Disabling default base.css
    }),
    preact({
+     include: ['src/components/another-preact-componet.tsx']
    }),
    solidJs({
+     include: ['src/components/alert.tsx']
    })
  ]
});
```

**Comment by lilnasy** [comment]
@mingjunlu Great work investigating! I confirmed this too - moving the solid integration before preact is also sufficient to make things work. The bug occurs because preact's plugin compiles the tsx file instead of solid's.

**Comment by SyntheticBird45** [comment]
@mingjunlu It worked! I should have read the docs more carefully. Many thx
