### ISSUE TITLE
`--mode` flag is not setting `import.meta.env.MODE` when running `astro dev`

### ISSUE THREAD

**Issue by yacoubb** [withastro/astro#10509]
### Astro Info

```block
Astro                    v4.5.8
Node                     v20.11.1
System                   Linux (x64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

When running `astro dev --mode staging`
- `import.meta.env.MODE` is still `development`
- `.env.development` is loaded
- `.env.staging` is **not** loaded

In the stackblitz example, try running:
`npm run dev`
and
`npm run dev -- --mode staging`

### What's the expected result?

- `import.meta.env.MODE` should be `staging`
- `.env.staging` should be loaded instead of `.env.development`
- 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dyvxr5?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by yacoubb** [comment]
From a brief look at the source code, the `resolveConfig` method in `dist/core/config/config.js` extracts `mode` into `inlineOnlyConfig` and discards it.
Additionally, when passing `--mode`, the `inlineOnlyConfig.configFile` value is `undefined`.

Should the `mode` flag not be passed to vite?

**Comment by ematipico** [comment]
`--mode` can only accept `development` or `production`, you can't pass your own value

**Comment by yacoubb** [comment]
> `--mode` can only accept `development` or `production`

Why? Vite doesn't have this limitation, why should astro?
It's handy to be able to quickly switch between development and staging environments using env files

**Comment by ematipico** [comment]
Feel free to open a discussion and propose some enhancements. The `dev` command, also, doesn't accept a `--mode` flag:

```
  astro dev [...flags]

   Flags 
                   --port  Specify which port to run on. Defaults to 4321.
                   --host  Listen on all addresses, including LAN and public addresses.
  --host <custom-address>  Expose on a network IP address at <custom-address>
                   --open  Automatically open the app in the browser on server start
              --help (-h)  See all available flags.
```

**Comment by yacoubb** [comment]
Thanks, will do. Seems like missing functionality to me.

Where can I open a discussion?

**Comment by ematipico** [comment]
Here: https://github.com/withastro/roadmap

**Comment by yacoubb** [comment]
> Here: https://github.com/withastro/roadmap

Cheers, I opened https://github.com/withastro/roadmap/discussions/870 ❤️

**Comment by nkneupper** [comment]
@ematipico bumping this thread with my own contribution to the roadmap request https://github.com/withastro/roadmap/discussions/870#discussioncomment-11821483

Please note that the official documentation (linked in my comment) **does** state that the `--mode` flag is possible with `astro dev`. If implementing this `--mode` flag is out of scope, at the very least could the documentation be updated to reflect this limitation?
