### ISSUE TITLE
Headers set in middleware are overridden by config headers

### ISSUE THREAD

**Issue by nvzqz** [withastro/astro#10515]
### Astro Info

```block
Astro                    v4.5.8
Node                     v21.7.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

Headers set by middleware are ignored if those headers are also in the Astro config.

### What's the expected result?

I expect headers set by middleware to take precedence over the static headers in the Astro config.

### Link to Minimal Reproducible Example

https://github.com/nvzqz/astro-middleware-headers-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mingjunlu** [comment]
Hi, I'm trying to figure out what goes wrong here, and I would appreciate some clarification on this.

As far as I know, [`server.headers`](https://docs.astro.build/en/reference/configuration-reference/#serverheaders) sets the **response** headers, while [this line in the middleware](https://github.com/nvzqz/astro-middleware-headers-repro/blob/main/src/middleware.ts#L4) sets the **request** headers. Is the latter supposed to override the former? 🤔

**Comment by ematipico** [comment]
I don't think so. Maybe the reproduction is incorrect.

@nvzqz could you please clarify?

**Comment by nvzqz** [comment]
@mingjunlu thanks for noticing the silly mistake. Indeed updating the headers on the response from calling `next()` works correctly. Next time I'll avoid submitting issues late at night 😅
