### ISSUE TITLE
Tailwind Typography isn't working with integration

### ISSUE THREAD

**Issue by arch-fan** [withastro/astro#10519]
### Astro Info

```block
Astro                    v4.5.8
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             astro:db
                         @astrojs/db/file-url
                         @astrojs/tailwind
                         astro-icon
                         @astrojs/svelte
```

### Describe the Bug

Typographies styles should be applied, but they aren't. 

It seems like tailwind loads the plugin, but isn't working

### What's the expected result?

Prose style being applied

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3wzga9?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mingjunlu** [comment]
Hi @arch-fan,

I noticed that there are two `plugins` properties in the tailwind config file. Could you try removing the duplicate one and see if it works?

```diff
 /** @type {import('tailwindcss').Config} */
 export default {
   plugins: [require('@tailwindcss/typography')],
   content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
   theme: {
     extend: {},
   },
-  plugins: [],
 };
```

**Comment by arch-fan** [comment]
This is my face right now.

![image](https://github.com/withastro/astro/assets/55891793/11f6bf06-094c-4273-a66a-1c79312a510b)

Thank you!
