### ISSUE TITLE
Invalid text encoding in 404.astro

### ISSUE THREAD

**Issue by amr3k** [withastro/astro#10518]
### Astro Info

```block
Astro                    v4.5.8
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

The `404.astro` page doesn't render Arabic characters correctly.

### What's the expected result?

Render Arabic text normally as it was written

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-qpk7bs?file=src%2Fpages%2F404.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mingjunlu** [comment]
Hi @amr3k,

You need to include `<meta charset="utf-8" />` inside `<head>` in `src/pages/404.astro`.

**Comment by amr3k** [comment]
Thanks @mingjunlu 

I got drowned into details that I forgot about the basics :(

But on a side note, shouldn't this be automatically added to the root layout?

I'm new to astro, but I know in svelte there's `app.html` file that contains the html boilerplate, does Astro have such thing?

**Comment by Princesseuh** [comment]
Astro doesn't have an equivalent of SvelteKit's `index.html` because it doesn't render "an app" from a single route like SvelteKit (or other similar frameworks) does.
