### ISSUE TITLE
Passing an object via VueJS props removes functions/methods

### ISSUE THREAD

**Issue by gkatsanos** [withastro/astro#10516]
### Passing objects with methods as props to Framework components

re: https://docs.astro.build/en/guides/framework-components/#passing-props-to-framework-components

I am instantiating an object from a class that has properties and methods.
The methods use astro.cookies to set/get/delete cookies (its an ab testing library)

I want to pass this object as a prop to a VueJS component. 

After some digging I realized the properties are there, the methods are not, as explained in the documentation:

> You can pass a function as a prop to a framework component, but it only works during server rendering. If you try to use the function in a hydrated component (for example, as an event handler), an error will occur.

This is because functions can’t be serialized (transferred from the server to the client) by Astro.

I could instatiate this object in client-side inside my Vue component but I wouldn't have access to the Astro context so I couldn't use the Astro cookies API. (I guess I'd have to rewrite the script for client side or add some conditions?)

Any ideas/workarounds?

### Describe the Bug

Methods not there

### What's the expected result?

Methods there

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
There's nothing we can do about it, this is a limitation of the client/server model with components. Props have to be serializable and functions are not. FYI Next.js 13 (and the app router) have the same limitation. To solve your issue, you may want to pass the cookies and fallback to something else on the client. For example:

```astro
---
import Test from "./Test.vue"
---
<Test cookies={Astro.cookies} client:load />
```
```vue
<script setup lang="ts">
import type { AstroCookies } from "???"

const props = defineProps<{
	cookies?: AstroCookies
}>()

const cookies = useIsomorphicCookies(props.cookies)

function useIsomorphicCookies(cookies?: AstroCookies) {
	if (cookies) {
		return cookies
	}
	return {
		// your client side implementation
	}
}
</script>
```
I have not tested it but that sounds like the only way, or you may need to rethink what you originally planned. Join the Discord server at https://astro.build/chat to get proper support!

**Comment by gkatsanos** [comment]
I ended up rewriting my script in a similar way, for every instance of `astro.context.cookies` I wrapped it in a `if (import.meta.env.SSR) {...` and an `else document.cookies` and then just initialized the script both in my middlewares and in the onMounted() hook 

I guess the difference with a FW like Nuxt is that the APIs are the same aka you can access the request directly without looking if its SSR or Client side. Right?

**Comment by florian-lefebvre** [comment]
Yeah I think Nuxt does more magic under the hood
