### ISSUE TITLE
view transition cause `unhandledrejection` events

### ISSUE THREAD

**Issue by mef** [withastro/astro#10534]
### Astro Info

```block
Astro                    v4.4.4
Node                     v20.6.1
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/svelte
                         astrojs-service-worker
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Safari

### Describe the Bug

The following error message pops up occasionally on my analytics, tracking Javascript error happening client-side.

> Unhandled rejection (reason: replaceWith@[native code] h@https://example.com/_astro/client._Xq126TT.js:1:5757 

(replaced actual domain name with example.com)

These errors only happen on iOS (versions 14 to 17) and OSX, in Safari and Chrome browsers.

The code causing the event in `client._Xq126TT.js` is:

    document.body.replaceWith(s.newDocument.body);

This seems to correspond to [this line](https://github.com/withastro/astro/blob/8cac744746a62903dbaa345a6e3cb0e13c6ff4d7/packages/astro/src/transitions/router.ts#L368) inside `transitions/router.ts`.

Approximately 1% of the visits from iOS get this error.

I am unable to provide a precise reproduction scenario as I do not own the devices in question, and am not aware of the actions taken by the users to cause the issue.

### What's the expected result?

No error / exception is raised when using Astro website.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Can you whare a screenshot of the full error?

**Comment by mef** [comment]
Yes, here is the full message visible in the analytics tool:

```
Unhandled rejection (reason: replaceWith@[native code]
f@https://example.com/_astro/client.rHCLZIs3.js:1:5969
f@[native code]
@https://example.com/_astro/client.rHCLZIs3.js:1:1605
asyncFunctionResume@[native code]
@https://example.com/_astro/client.rHCLZIs3.js:1:6680
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]).
```

The corresponding code in the compiled `client.rHCLZIs3.js` file is the following:

* client.rHCLZIs3.js:1:5969 - The variable `s` in `document.body.replaceWith(s.newDocument.body)`
* client.rHCLZIs3.js:1:1605 - the call to function `swap` in `return document.dispatchEvent(o),o.swap(),o`
* client.rHCLZIs3.js:1:6680 - the variable `e` in `const h=document.title,y=await K(e,T,f)`
