### ISSUE TITLE
Astro.redirect() does not update the referrer in request header

### ISSUE THREAD

**Issue by GetLiberated** [withastro/astro#10530]
### Astro Info

```block
Astro                    v4.3.1
Node                     v21.1.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/preact
                         @astrojs/tailwind
```

### Describe the Bug

Timeline:
I click `<a href>` and navigate to a page that has Astro.redirect() in it.
The page redirects me to another page. 
I check the referrer from the request header on the redirected page.
What I get is the original page where I click the `<a href>` instead of the previous page that redirects me.

Example:
I click `<a href="/page">` on _/_
I got redirected from _/page_ to _/page/1_ by `Astro.redirect("/page/1")`
When I `console.log(Astro.request.headers.get('Referer'))` on _/page/1_ I got _/_ instead of _/page_

### What's the expected result?

I expect to get the previous page that redirects user to the current page as the referrer.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ushock-jfqf1a?file=src%2Fpages%2Fpage%2F1.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Fryuni** [comment]
That is not a bug. It is how HTTP redirects work. The client is expected to repeat the same request, with the same referrer, to the target of the redirect.

What is contained in the referrer depends on the referrer policy of the page that initiated the chain (`/` in your example).

Some platforms, especially marketing platforms, do some tricks to hide the referrer by redirecting to a page with an HTML that does a second and even a third redirect, each with different parameters. If you want to search more about it, it is called "double meta redirect"

**Comment by matthewp** [comment]
Thanks for the explanation @Fryuni!
