### ISSUE TITLE
remarkShakuCodeAnnotate being used as a RemarkPlugin causes a type error

### ISSUE THREAD

**Issue by aaronlifton** [withastro/astro#10541]
### Astro Info

```block
Astro                    v4.5.2
Node                     v21.6.2
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             custom-image-resizer-integration
                         @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
                         @astrojs/svelte
                         astro-icon
                         @astrojs/react
                         astro-robots-txt
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

The [astro example](https://stackblitz.com/edit/github-yunziv?file=src%2Fcontent%2Fblog%2Fshaku.mdx), linked from [here](https://www.npmjs.com/package/shaku-code-annotate-shiki), for the remark-shaku-code-annotatate remark plugin, demonstrates that the plugin can be listed under `remarkPlugins` in `astro.config.mjs` as follows:
```ts
markdown: {
    remarkPlugins: [
      [
        remarkShakuCodeAnnotate,
        {
          themes: ['github-light', 'github-dark'],
        },
      ],
    ],
  },
```

This works, but if i change the astro config to a typescript (.ts) file from a .mjs file, I get this reproducible type error:
```ts
Diagnostics:
1. Type '[(options: ShakuHighlighterOptions) => Transformer, { fallbackToShiki: true; theme: string; langs: string[]; }]' is not assignable to type 'string | [string, any] | RemarkPlugin<any[]> | [RemarkPlugin<any[]>, any]'.
     Type '[(options: ShakuHighlighterOptions) => Transformer, { fallbackToShiki: true; theme: string; langs: string[]; }]' is not assignable to type '[string, any] | RemarkPlugin<any[]> | [RemarkPlugin<any[]>, any]'.
       Type '[(options: ShakuHighlighterOptions) => Transformer, { fallbackToShiki: true; theme: string; langs: string[]; }]' is not assignable to type '[string, any]'.
         Type at position 0 in source is not compatible with type at position 0 in target.
           Type '(options: ShakuHighlighterOptions) => Transformer' is not assignable to type 'string'. [2322]
```

Even though Transformer is a valid return type of a `RemarkPlugin` (`unified.Plugin`), and it looks like a valid `PluginTuple` (`[RemarkPlugin, any]`), it seems the type of this plugin is inconsistent with the types included in `node_modules/@astrojs/markdown-remark/dist/types.d.ts`. So, I cannot cast `remarkShakuCodeAnnotate` as a `RemarkPlugin` without casting it to `unknown` first, which seems like a bug:
```ts
[
	remarkShakuCodeAnnotate as unknown as RemarkPlugin,
	{
		fallbackToShiki: true,
		theme: "material-theme-darker",
		langs: ["tsx", "jsx", "typescript", "sh", "fish", "json"],
	},
],
```

### What's the expected result?

I expect there to be no type error, since the code works when the config file is a .mjs instead of a .ts file.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yunziv-pede1v?file=astro.config.ts%3AL13

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Could the issue be that `remarkShakuCodeAnnotate` is exported as a unified v10 plugin? Astro uses unified v11. I don't think Astro has a bug here, currently we define a remark plugin as:
https://github.com/withastro/astro/blob/b3028caecf1a96310e2ee7a65075a81c231d87be/packages/markdown/remark/src/types.ts#L20-L23

which is similar to how unified defines it: https://github.com/unifiedjs/unified/blob/b69689bba52a918d87aa62f295ccffa8d9aa8ef8/lib/index.js#L75-L87

**Comment by matthewp** [comment]
Closing with no response, please open a new issue if you still have the problem with unified v11. Thanks!
