### ISSUE TITLE
In the new version of Astro, the Sharp depency could not be installed in China

### ISSUE THREAD

**Issue by fitoe** [withastro/astro#10542]
### Astro Info

```block
Cring, I am so sad. 
It is a problem only in China, we can not install the `sharp` depency for the network reason.
Also we can not visit FB twitter etc.

I kown Astro use sharp to process images, but I realy can not to install it in npm. 
So I can not going to use Astro any more.
could the feature be optional ?

Thanks !!
```

### If this issue only occurs in one browser, which browser is a problem?

npm

### Describe the Bug

can not install sharp in npm

### What's the expected result?

Can not to use Astro

### Link to Minimal Reproducible Example

I can not

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello, you have multiple solutions for this:

- Use another image service than Sharp, [either Squoosh](https://docs.astro.build/en/guides/images/#configure-squoosh) or if you're using Netlify or Vercel you can use theirs (see their respective settings)
- Install Sharp 0.32.x from a npm mirror
- Use Sharp 0.33.x, which has its binaries directly on npm (which I believe should work for China? You might still need to install from a mirror)
- Compile directly from source, see the installation page here: https://sharp.pixelplumbing.com/install

**Comment by bis0072** [comment]
use VPN

**Comment by KonghaYao** [comment]
run This before install dependencies. @fitoe 
```sh
npm config set sharp_binary_host "https://npmmirror.com/mirrors/sharp"
npm config set sharp_libvips_binary_host "https://npmmirror.com/mirrors/sharp-libvips"
```

**Comment by ematipico** [comment]
Closing. There isn't much we can do.
