### ISSUE TITLE
Astro DB isn't creating tables and `db/seed.ts` isn't watched

### ISSUE THREAD

**Issue by oliverturner** [withastro/astro#10544]
### Astro Info

```block
Astro                    v4.5.9
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro:db
                         @astrojs/db/file-url
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

Having run `npx astro add db` I have 

1. Added a basic table definition to `db/config.ts` 
2. Added an array of 2 records to `db/seed.ts`

When running npm run dev:

- ✅ `.astro/content.db` is created
- ❌ `.astro/content.db` has no tables and is 0 bytes in size
- ❌ `db/seed.ts` does not run
- ✅ Changes to `db/config.ts` do restart the server
- ✅ `.astro/content.db` is recreated
- ❌ `.astro/content.db` has no tables and is 0 bytes in size
- ❌ Changes to `db/seed.ts` do not restart the server

### What's the expected result?

When running `npm run dev`:
1. `.astro/content.db` is created with the defined tables
1. `db/seed.ts` runs and populates the tables with the provided data
1. Changes to `db/config.ts` result in the dev server restarting
1. Changes to `db/seed.ts` result in the dev server restarting

### Link to Minimal Reproducible Example

https://github.com/oliverturner/astro-db-repro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @oliverturner, the reason these things aren't running yet is because we do it lazily, the first time you query. So if you add a query to your index.astro you should see these things happen.

However, agree that this is confusing and not the best experience. We're going to change it so that it does it after the dev server has started.

**Comment by oliverturner** [comment]
Thanks for the explanation Matthew 🫶
