### ISSUE TITLE
Type is not available when we use select query with relationship

### ISSUE THREAD

**Issue by withden** [withastro/astro#10559]
### Astro Info

```block
Astro                    v4.5.8
Node                     v18.18.2
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             astro:db
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

It's not a production bug. I face a type of issue when I use a select query with relationships (inner join & any kind of joins)

-- In Database config
```ts title="db/config.ts" {3, 10}
const Category = defineTable({
  columns: {
    id: column.number({ primaryKey: true }),
  },
});

const Blog = defineTable({
  columns: {
    categoryId: column.number({ references: () => Category.columns.id }),
  },
});
```
-- In Select query
```ts title="src/pages/index.astro" 
const blogs = await db.select().from(Blog).innerJoin(Category, eq(Blog.categoryId, Category.id));
console.info(blogs[0]);
```

Here blogs[0] do not give any type of hint

### What's the expected result?

```ts title="src/pages/index.astro" 
const blogs = await db.select().from(Blog).innerJoin(Category, eq(Blog.categoryId, Category.id));
console.info(blogs[0]['Blog']);
console.info(blogs[0]['Category']);
```

So here single blog (blogs[0]) has 2 objects, which need to be added into types.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/bug-astro-db-types

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I can see the type. The types are code generated when running the server. Is it possible that you applied the changes when the server wasn't running?
