### ISSUE TITLE
Query Params get deleted

### ISSUE THREAD

**Issue by kb1995** [withastro/astro#10565]
### Astro Info

```block
Astro                    v4.5.9
Node                     v18.17.0
System                   macOS (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @storyblok/astro
                         @astrojs/tailwind
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

I'm not sure if this is exactly a bug, given that I spotted that this [issue](https://github.com/withastro/astro/issues/9440) has been merged but I'm confused. It seems that URL params don't work if a page is prerendered, but none of my pages can have query params - they just disappear from the URL a couple of ms after the page loads, regardless if a page is prerendered or not.

I don't know why this should happen even if a page is prerendered - we should still have the ability to add things like UTM parameters and client side filtering

For example, if I navigate to http://localhost:4321/?test=123, it automatically gets redirected to http://localhost:4321

---

I just tested the following scenarios and in all of them, the query params get deleted:

- server
- server + prerender 
- server + prerender but visit a non-prerendered page
- static

I'm not sure if I'm missing something obvious, but I don't think that the removeParams in https://github.com/lilnasy/astro/blob/43204d6a6062b2d82b420bc9b7c1b713517676ad/packages/astro/src/vite-plugin-astro-server/route.ts works as expected.

---

### What's the expected result?

The query URL params should stay in the URL, in order for me to add client-side filtering and UTM parameters.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
https://github.com/withastro/astro/assets/69170106/ce2c70ae-ad4d-41bc-8cfa-2c27747ead5b

It currently behaves like you expect it to.

**Comment by azurewood** [comment]
It gets deleted between view transitions / page routes. Within the same page route, it should be fine.

**Comment by kb1995** [comment]
> It gets deleted between view transitions / page routes. Within the same page route, it should be fine.

How can I disable this behaviour? Have a look at my staging environment -> https://amw-sigma.vercel.app/

If I go to https://amw-sigma.vercel.app/test=123, I get redirected to https://amw-sigma.vercel.app/

**Comment by kb1995** [comment]
> video.mp4 
> It currently behaves like you expect it to.

This doesn't work on my staging website (https://amw-sigma.vercel.app/) -> I get a full page refresh and the parameters disappear

**Comment by kb1995** [comment]
The bug was caused by another non-Astro-related line of code in my codebase. It's save to close...
