### ISSUE TITLE
Simple usage of `Polymorphic` type results in TypeScript error

### ISSUE THREAD

**Issue by charlie-hadden** [withastro/astro#10577]
### Astro Info

```block
> astro info

Astro                    v4.5.10
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Astro 4.5.10 seems to have introduced a regression with the `Polymorphic` type which now causes these errors:

```
ts(2590): Expression produces a union type that is too complex to represent.
```

Running `npm run astro check` in the linked stackblitz will show the issue.

### What's the expected result?

The type to work as it did previously.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-gl13vj?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by adriandpdev** [comment]
i have the same problem

**Comment by AkaraChen** [comment]
I have the same problem too, using [luna landing](https://github.com/JimmyCamus/luna-landing), files are [Action.astro](https://github.com/JimmyCamus/luna-landing/blob/main/src/components/Action.astro) and [Brands.astro](https://github.com/JimmyCamus/luna-landing/blob/main/src/sections/Brands.astro)

**Comment by Code-Victor** [comment]
I'm experiencing the same issues in Astro 4.13.3
```ts
type Props<Tag extends HTMLTag> = Polymorphic<{
  as: Tag;
}> &
  VariantProps<typeof buttonVariants>;
```

**Comment by gambolputty** [comment]
Me too with Astro 4.14.2

```typescript
type Props<Tag extends HTMLTag> = Polymorphic<{
  as: Tag;
  id?: string;
  collapsible?: boolean;
  theme?: VariantProps<typeof cardClasses>["theme"];
}>;
```

```shell
src/components/Error.astro:54:7 - error ts(2590): Expression produces a union type that is too complex to represent.

 54       <Card aria-label={title} theme="lavender">
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 55         <CardBody class="text-center">
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 79         </CardBody>
    ~~~~~~~~~~~~~~~~~~~
 80       </Card>
    ~~~~~~~~~~~~~

```

**Comment by walmartwarlord** [comment]
@gambolputty opened a new issue [here](https://github.com/withastro/astro/issues/11880). It doesnt seem to be fixed. Not sure why it's closed.

**Comment by wobsoriano** [comment]
We were able to fix this by setting a default element type here - https://github.com/clerk/javascript/pull/4057
