### ISSUE TITLE
Module '"astro:i18n"' has no exported member 'getRelativeLocaleUrl'

### ISSUE THREAD

**Issue by atennert** [withastro/astro#10574]
### Astro Info

```block
Astro                    v4.5.9
Node                     v20.11.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When building an astro project using something out of `astro:i18n`, the build fails with:

```
src/pages/index.astro:4:10 - error ts(2305): Module '"astro:i18n"' has no exported member 'getRelativeLocaleUrl'.

4 import { getRelativeLocaleUrl } from "astro:i18n";
           ~~~~~~~~~~~~~~~~~~~~
```

## How to get there
* create a new project using `npm create astro@latest`
* Include sample files
* Add i18n to configuration, p.ex.:
  ```js
    i18n: {
        defaultLocale: 'en',
        locales: ['en', 'de']
    }
  ```
* use something out of _astro:i18n_ in an *.astro page file, like
  ```ts
  import { getRelativeLocaleUrl } from "astro:i18n";
  getRelativeLocaleUrl('en');
  ```
* run `npm run build`

## Additional info
Before running the build my IDE (IntelliJ) was already hinting me that `getRelativeLocaleUrl` couldn't be found.

Everything seems to work when using `npm run dev`. However, I get the same message as mentioned in issue #10558, so they might be related.

I edited `node_modules/astro/client.d.ts` replacing (adding _dist_)
```ts
declare module 'astro:i18n' {
	export * from 'astro/virtual-modules/i18n.js';
}
```
with
```ts
declare module 'astro:i18n' {
	export * from 'astro/dist/virtual-modules/i18n.js';
}
```
After that the IDE was happy, but the build still failed ...

### What's the expected result?

`npm run build` doesn't fail.

### Link to Minimal Reproducible Example

doesn't work in stackblitz, as npm run build is required

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by atennert** [comment]
Maybe this observation helps:

Checking the contents of `node_modules\astro\dist\virtual_modules`, what stands out with _i18n_ is that there is a ton of stuff in `i18n.d.ts` and `i18n.js`, while in all the other files there are only links into the different other folders of `dist`.

**Comment by ematipico** [comment]
cc @lilnasy 

You might want to look at this

**Comment by lilnasy** [comment]
Can you clarify the conditions required for the bug?

<img width="911" alt="image" src="https://github.com/withastro/astro/assets/69170106/a2c68800-85c9-4463-8060-bb4cf7207866">

**Comment by Because789** [comment]
Here is the [minimal reproduction](https://github.com/withastro/astro/issues/10558#issuecomment-2022069218)

**Comment by atennert** [comment]
@lilnasy Interesting ... the difference that I see between your build and my build is npm vs. pnpm

**Comment by Because789** [comment]
@atennert how does your tsconfig.json look like? I tried to reproduce it with different TS settings and wasn't able to get the build error. Then I changed it accidentally to:

```ts
{
  "extends": "astro/tsconfigs/relaxed"
}
```
And would you look at that, I got exactly your build error, including the hint that `getRelativeLocaleUrl` couldn't be found in index.astro:

![Screenshot (209)](https://github.com/withastro/astro/assets/867257/2beddb5a-3797-4ebf-b218-d23821755e3b)

**Comment by lilnasy** [comment]
That's a good pointer. "relaxed" doesn't exist, the project effectively behaves as if there was no tsconfig, but astro needs the rules contained within it for basic functionality.

**Comment by atennert** [comment]
It seems, there is a new version today (4.5.10 vs. 4.5.9 from above), including latest typescript(!), with which it's working. I just created a new project to reproduce the issue for the extends, which (now) is generated
```
{
  "extends": "astro/tsconfigs/strict"
}
```
but it works now ^^

Remark: `Sourcemap for "/home/andi/Desktop/density-doppler/node_modules/astro/dist/virtual-modules/i18n.js" points to missing source files` still exists.
