### ISSUE TITLE
When using the development server versus distributing static build artifacts, the behavior of redirects differs.

### ISSUE THREAD

**Issue by taiga533** [withastro/astro#10576]
### Astro Info

```block
Astro                    v4.5.10
Node                     v20.11.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

"When using the development server versus distributing static build artifacts, the behavior of redirects differs. 

With the following configuration, on the development server, the contents of old-page.astro (old-page/index.html) are displayed, but when a static build is performed and distributed on any server (or previewed using astro preview), old-page/index.html is displayed and then redirected to new-page.astro using the `<meta http-equiv=\"refresh\">` tag.

```
# file-system
pages
├ old-page
└ new-page
```

```js
// config
export default defineConfig({
  output: \"static\",
  redirects: {'/old-page': '/new-page'},
});
```

### What's the expected result?

I believe that even on the development server, old-page.astro should be displayed and then redirected to new-page.astro using the <meta http-equiv=\"refresh\"> tag.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yogmzg?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Sounds reasonable, but I would expect a status code redirect still if `output: 'server'`. Would you be willing to implement this?

**Comment by ematipico** [comment]
Closed by https://github.com/withastro/astro/pull/12169
