### ISSUE TITLE
Astro MDX fails to render framework components and components defined with MDX file, when explicit `null` or `undefined` prop passed in

### ISSUE THREAD

**Issue by duanwilliam** [withastro/astro#10575]
### Astro Info

(from stackblitz environment)

```block
Astro                    v4.5.10
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
```

### Describe the Bug

If a framework component is used within an MDX file, and one of its props gets passed in an explicit `undefined` or `null`, Astro crashes with an error trying to render the component.
This issue also occurs for components defined within the MDX file.

e.g.

```mdx
import A from 'foo.jsx'

export function B() { return <div /> }

{/* both of these cause an error */}
<A foo={undefined} />
<B bar={undefined} />
```

The problematic line is https://github.com/withastro/astro/blob/bb7707e1715fc3f496e4c3f07834221c8da62ff6/packages/astro/src/runtime/server/jsx.ts#L118-L119

in these cases,
- `vnode` is an object, so `renderJSX` delegates to `renderJSXNode` (this seems to be true of all the jsx inside an mdx file?)
- `vnode['astro:jsx']` is `true` (i.e. it is in fact a vnode)
- `vnode.type` is the component, i.e. a function
- `vnode.type` does _not_ have `isAstroComponentFactory` set
- there is no truthy `server:root` prop

which leads to aforementioned line being called, resulting in attempting to do a property access on `null`/`undefined` which results in an error.

### What's the expected result?

Component renders properly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mbbqqu?file=src%2Fpages%2Fa.mdx

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Yes, please do send a PR, thanks!
