### ISSUE TITLE
Error when starting a fresh project with Astro 4.5.11

### ISSUE THREAD

**Issue by amit13k** [withastro/astro#10594]
### Astro Info

```block
Astro                    v4.5.11
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When starting a project created with Astro 4.5.11, I am getting the following error,
`The requested module '../core/path.js' does not provide an export named 'removeBase'
  Stack trace:
`

### What's the expected result?

Project should start normally.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qoeoy2?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pabloimrik17** [comment]
I have the same problem. Im using Node 20.10.0, pnpm 8.15.5

**Comment by Princesseuh** [comment]
I'm on it, apologies for the issue. Should be fixed in a few minutes.

**Comment by DAVIDS2405** [comment]
I have the same problem I will be attentive when this is solved jejej

**Comment by DAVIDS2405** [comment]
@Princesseuh Thank you very much you are the best

**Comment by Princesseuh** [comment]
This is fixed now in the latest version, sorry again for the inconvenience.
