### ISSUE TITLE
Type Error when returning 404 response with dynamic route segments

### ISSUE THREAD

**Issue by amit13k** [withastro/astro#10590]
### Astro Info

```block
Astro                    v4.5.10
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

When returning a 404 Reponse from a dynamic route segment, I get a Type Error `Expected "x" to be a string`. This happens in a specific route configuration as demonstrated in the minimal reproducible example. In the example project, there are two dynamic route segments([x] and [z]). The url looks like this, `/[x]/y/[z]/`. The issue doesn't occur if i remove `pages/[x]/index.astro file`.

### What's the expected result?

A correct 404 response.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-xiu5we?file=src%2Fpages%2F%5Bx%5D%2Fy%2F%5Bz%5D.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I _think_ this could be an issue related to priority

**Comment by ematipico** [comment]
Closing, this is fixed in https://github.com/withastro/astro/pull/10582
