### ISSUE TITLE
View transitions do not work properly when there are images on the page

### ISSUE THREAD

**Issue by kamranahmedse** [withastro/astro#10595]
### Astro Info

```block
Astro                    v4.5.9
Node                     v19.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

View transitions do not work properly when there are images on the page

https://github.com/withastro/astro/assets/4921183/def75943-684f-47ca-9d0a-f886d4dfdc78

### What's the expected result?

Images on page should not impact the transitions.

### Link to Minimal Reproducible Example

https://github.com/kamranahmedse/astro-view-transitions-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Replacing 

&nbsp;\- `<ViewTransitions />`
\+ `<meta name="view-transition" content="same-origin" />`

and 

&nbsp;\- `<div transition:animate={myFade}>`
\+ `<div style="view-transition-name: main">` 

shows that the distortion also happens with Chromes multi page view transitions.
(Chrome 123.0.6312.86, experimental flag chrome://flags#view-transition)
That is without any participation of Astro.

**Comment by martrapp** [comment]
The effect is more likely to show up with dev tools open. 
Adding an artificial wait >=500ms in the update callback after swap fixes the issue of this example. 
The rational is that the images are completely loaded before the `::view-transition-new` image is set up. IMHO, it is no valid solution to wait for image loading during the DOM update as rendering is blocked in this state of view transitions and the browser feels frozen. 

Note also, that the distortion effect is reported to show for long pages, only.

**Comment by martrapp** [comment]
Currently, I do not see a general solution to this issue besides waiting for Chrome to fix it. 
Developers who encounter that issue, might think about using placeholder `<divs>` (to avoid layout shifts) and delaying the insertion of `<img>` elements until after the view transition animations completed. (Maybe with a nice enter animation ;-)
