### ISSUE TITLE
BUG: When a site has view transitions, and `scroll-behavior: smooth`, the back button has an annoying scroll animation.

### ISSUE THREAD

**Issue by godalming123** [withastro/astro#10615]
### Astro Info

```block
Astro                    v4.5.12
Node                     v20.10.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When on a page with `scroll-behavior: smooth` and view-transitions, if the user uses a link to navigate to another page, and then navigates back with the browsers back button, then an annoying animation is played where astro restores the scroll position.

### What's the expected result?

When astro restores the scroll position in it's view-transition code, it sets the behavior to instant so no annoying animation plays:
```js
window.scrollTo({
  top: 100,
  left: 100,
  behavior: "instant",
});
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nfiryw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @godalming123, the behavior you observed is to be expected with view transitions. It is not Astro-specific. When you use [Chrome's multi page view transitions](https://developer.chrome.com/blog/spa-view-transitions-land#transitions_across_documents) instead of using Astro's `<ViewTransitions />`, you will get the same effect. This is also in line with the [spec](https://drafts.csswg.org/css-overflow/#smooth-scrolling).

**Comment by aleclarson** [comment]
Is there a way to do instant scroll restoration for history navigation only?

**Comment by martrapp** [comment]
Hi @aleclarson 👋🏼

Assuming you set the scroll-behavior on your `<html>` tag:
```
:root {
  scroll-behavior: smooth;
}
```
You can set instant scroll ('auto') for history navigation (navigationType === 'traverse') like this:
```html
<script>
  document.addEventListener('astro:before-swap', (e) => {
    e.newDocument.documentElement.style.scrollBehavior =
      e.navigationType === 'traverse' ? 'auto' : 'smooth';
    e.viewTransition.updateCallbackDone.then(() => {
      document.documentElement.style.scrollBehavior = 'smooth';
    });
  });
</script>
```
Setting it before the swap is sufficient to control the scrolling of the client router.

You have to reset it to smooth after the scroll. 
You can do this in an `astro:after-swap` event 
or when the View Transition API signals that the swap is done (see code above).

**Comment by koji-1009** [comment]
Hi, I was looking at this file while working on #16025 and noticed that `scrollTo` calls in `router.ts` are inconsistent:

- Line 83: no `behavior` specified (defaults to `auto`)
- Line 215: uses `behavior: 'instant'`
- Line 220: no `behavior` specified (defaults to `auto`)

I confirmed locally that adding `behavior: 'instant'` to the remaining calls resolves the smooth scroll issue on back navigation, even with `scroll-behavior: smooth` set globally.

Would this be an acceptable fix? If so, I'm happy to open a PR.

https://github.com/withastro/astro/blob/astro%406.0.8/packages/astro/src/transitions/router.ts

**Comment by martrapp** [comment]
Hi @koji-1009 :wave:, this is by design. Scroll to top on the new page is instant, scroll restoration uses the current scroll-behavior.

**Comment by koji-1009** [comment]
I see, thanks for the explanation. Sorry for the noise!
