### ISSUE TITLE
db table autoimport intellisense does not show types

### ISSUE THREAD

**Issue by mayank99** [withastro/astro#10613]
### Astro Info

```block
Astro                    v4.5.12
Node                     v20.11.0
System                   macOS (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

This is a super minor issue, but I noticed that when autoimporting a table, the types are not shown in the popout.

Video below shows:
1. When typing `Count`, I can't even tell from the suggestion list that it's a table, because the text "`astro:db`" is so faint. And even if I could see the text, I wouldn't know whether it's a table or something else.
2. Later, after the Column has been imported, hovering it does show the types.

https://github.com/withastro/astro/assets/9084735/29af572e-5096-4fb1-a413-200f9a4f3920

### What's the expected result?

I should be able to see the types of the thing I'm about to import, without having to import it.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7mx9rf-vqepqn

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Does this have anything to do with Astro or is this just how vscode displays the type?

**Comment by mayank99** [comment]
Normally I can see the types without importing it. You can try importing a regular TS object to verify this.

My guess is that `astro:db` types have not been correctly set up.

**Comment by matthewp** [comment]
Having trouble recreating this myself. I do see the type before the import occurs. One thing that is different is that the types are generated for you. So if you open vscode without the `Count` schema being defined then vscode thinks the types for `astro:db` are different from what they actually are. Could you try Reload Window which should refresh the types and see if it still occurs?

**Comment by mayank99** [comment]
Okay I can't reproduce it anymore.

I did notice another weird issue though, where the imports are not grouped

https://github.com/withastro/astro/assets/9084735/8af4b259-cfe1-43e0-96fc-424b61cc9a39
