### ISSUE TITLE
BUG: Relative paths in links behave differently in prod and dev mode

### ISSUE THREAD

**Issue by godalming123** [withastro/astro#10614]
### Astro Info

```block
Astro                    v4.5.12
Node                     v20.10.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When you set the path of a link to something relative (say `../`), then it behaves differently in production and dev mode. With the example, in production mode it goes back one level (so `/somePage/otherPage/` becomes `/somePage/`), however in dev mode, the link goes back to levels (so `/somePage/otherPage/` becomes `/`).

### What's the expected result?

The link behaves the same in production and dev mode.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xqmajg (I could not get stackblitz to run the code, but if I downloaded it locally, I could reproduce the bug)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
- Clicking on a `"../"` anchor on `/subsection/subpage/` (with trailing slash) will take you to `/subsection/`.
- Clicking on a `"../"` anchor on `/subsection/subpage` (without trailing slash) will take you to `/`.

Is it possible your production server necessarily adds trailing slashes?
If so, does setting `trailingSlash` to `"always"` make the astro dev server behave the same as your production server?

**Comment by godalming123** [comment]
@lilnasy thanks, add a trailing slash to the link fixed the bug.
