### ISSUE TITLE
astro build to non-project directory adds TypeScript d.ts files

### ISSUE THREAD

**Issue by m-radzikowski** [withastro/astro#10610]
### Astro Info

```block
Astro                    v4.5.12
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/mdx
                         astro-icon
                         astro-meta-tags
```

### Describe the Bug

In astro project with TypeScript, running `astro build --outDir ../dist` writes `.d.ts` files to the output dir.

The files include `types.d.ts` from `.astro/` but also other types added by plugins, for example `icon.d.ts` from astro-icon.

This does not happen if we build to the dir `./dist` or any child like `./sub/dir`. But it always happen when we build to a dir outside the project, like `../dist`.

### What's the expected result?

The output dir should not contain `.d.ts` files.

### Link to Minimal Reproducible Example

not reproducible online

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Fryuni** [comment]
Can you make a minimal project where this happens? It could be a GH repo since you said this can't be reproduced online.

I tested with Astro 4.5.12 for the example projects and everything is being generated correctly, I got no `.d.ts` files. Maybe there is something in your Astro configuration or in your `tsconfig.json` that differs from the example projects and causes this.

**Comment by m-radzikowski** [comment]
Hey, sure, here is the repo with reproduction: https://github.com/m-radzikowski/astro-issue-10610

It's a fresh, clean project with all default options and only one file created in `src/content`.

**Comment by Fryuni** [comment]
Confirming the reproduction. Thanks @m-radzikowski

**Comment by ematipico** [comment]
If anyone wants to help, this should be an easy fix

**Comment by rishi-raj-jain** [comment]
@ematipico 

I am up for getting this done!
