### ISSUE TITLE
i18n dynamic routes: build log differs from build output

### ISSUE THREAD

**Issue by Because789** [withastro/astro#10621]
### Astro Info

```block
Astro                    v4.5.12
Node                     v20.11.1
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/tailwind
                         astro-icon
```

### Describe the Bug

I have the dynamic route src/pages/[...lang]/index.astro in my project (prefixDefaultLocale: false). It runs on dev server without any issues and builds correctly. But the build log shows that it generates the routes: /index.html, /en/index.html, /en/index.html and /en/en/index.html:

![Screenshot (211)](https://github.com/withastro/astro/assets/867257/6fdbee4c-e78a-4f52-8a50-5de602e3fdf5)

### What's the expected result?

Show correct build output in logs.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-quy3ic?file=src%2Fpages%2F%5B...lang%5D%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by 1574242600** [comment]
Can you tell me why this is necessary?
Astro I18n already adds an appropriate language prefix to each route, which results in duplicate language prefix.

```ts
export function staticPathsLangParams() {
    const urls = getRelativeLocaleUrlList();
    return urls.map((url) => ({
        params: { lang: url === "/" ? undefined : url },
    }));
}

export const getStaticPaths = staticPathsLangParams;
```

As for not generating `/en/en/index.html`, it's because `/en/index.html` is considered the same path and is skipped.

https://github.com/withastro/astro/blob/174ce25f619ea80f77e52f8d2ca864ecc63de938/packages/astro/src/core/build/generate.ts#L482-L493

**Comment by ematipico** [comment]
This use case seems to be a bit of a stretch to me.

This use case uses an API to retrieve all the configured locales and generate pages from it. However, the project is configured to not prefix the default locale. The use case creates tries to build an invalid page in purpose.

I'm not sure what's the correct way to go here and what needs to be fixed.
