### ISSUE TITLE
Worker scripts not output in correct assets directory

### ISSUE THREAD

**Issue by bayssmekanique** [withastro/astro#10626]
### Astro Info

```block
Astro                    v4.5.12
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

The Astro build is picking up the Worker script file and transforming it and placing it in the `dist` directory during builds, but it is always placed in `dist/assets` regardless of what the `build.assets` configuration is set to. 

### What's the expected result?

I would expect the worker script to be output to the same directory as other client scripts as specified by the `build.assets` property in the configuration.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-knx6rb?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
I'd love to work on this. May someone guide me the entrypoint where we bundle the workers in the core?

**Comment by bluwy** [comment]
Worker builds is handled by Vite and the output code is here: https://github.com/vitejs/vite/blob/e2658ad6fe81278069d75d0b3b9c260c3021b922/packages/vite/src/node/plugins/worker.ts#L89-L106

It doesn't seem like Astro sets the `vite.build.assetsDir` and is probably why `build.assets` has no effect. I'm not sure why Astro didn't set this for a long time and I'm not sure of the impact if we set it now though. (probably fine i hope)

**Comment by bayssmekanique** [comment]
It does look like it's hard coded to `assets` path here: https://github.com/vitejs/vite/blob/e2658ad6fe81278069d75d0b3b9c260c3021b922/packages/vite/src/node/plugins/worker.ts#L410-L417

**Comment by rishi-raj-jain** [comment]
Thank you @bluwy!
