### ISSUE TITLE
Build succeeds even when syntax is incorrect

### ISSUE THREAD

**Issue by ktym4a** [withastro/astro#10628]
### Astro Info

```block
Astro                    v4.5.12
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I noticed when fixing [this one](https://github.com/withastro/astro/pull/10627) that the build succeeds when the syntax is incorrect, but output is not correct.

But, in dev mode, the output is correctly placed inside `<head>`.

in the case of the following code:

```astro
<!doctype html>
<html lang="en">
<meta charset="UTF-8" />
  <head>
    <meta name="description" content="Astro description" />
  </head>
  <body>
    <slot />
  </body>
</html>
```

---

run dev:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="Astro description">
  </head>
  <body>
  </body>
</html>
```

run build:

```html
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<meta name="description" content="Astro description">
<body>
</body>
</html>
```

### What's the expected result?

The build will fail or the output should be the same as dev.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-qdiers

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Looks like you mistakenly put the charset tag between the `<html>` and `<head>` sections which is what is causing the head to be omitted. Moving it into the head gets the expected output.
