### ISSUE TITLE
2 Deprecated Subdependencies Found In @astrojs/cloudflare

### ISSUE THREAD

**Issue by Barzi-Ahmed** [withastro/astro#10639]
### Astro Info

Hi, 

There is two deprecated subdependencies found in @astrojs/cloudflare package.

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

![1](https://github.com/withastro/astro/assets/135956133/e922b2b6-f45a-4bc9-97ea-e8cff5d15fb2)

### What's the expected result?

Please upgrade them to the new versions.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Those packages are not within control of `@astrojs/cloudflare`. I'd suggest analyzing the dependency graph and contact the respective authors:

<img width="1786" alt="image" src="https://github.com/withastro/astro/assets/34116392/ecdd9a11-b8dc-4dc0-adff-b9fc139ac68c">

(from: https://npmgraph.js.org/?q=%40astrojs%2Fcloudflare)
