### ISSUE TITLE
Svelte integration with Svelte 5 is unusable since svelte@5.0.0-next.88

### ISSUE THREAD

**Issue by xiBread** [withastro/astro#10637]
### Astro Info

```block
Astro                    v4.5.12
Node                     v21.7.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
```

### Describe the Bug

Svelte 5 has removed the ability to directly import from the `internal` module, which the svelte integration relies on, and now throws:

<img width="1125" alt="Screenshot 2024-04-01 at 2 55 35 PM" src="https://github.com/withastro/astro/assets/60681223/7dfe1027-5849-4db1-b894-ea9752b6dc9b">

On `next.88` (https://github.com/sveltejs/svelte/pull/10968)

<img width="1146" alt="Screenshot 2024-04-01 at 2 56 17 PM" src="https://github.com/withastro/astro/assets/60681223/5d32b868-e6e6-4fbd-a68f-8db8ad227020">

On `next.90` (https://github.com/sveltejs/svelte/pull/10987)

The exports have moved to `internal/client` and `internal/server` in v5.

### What's the expected result?

No error

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Should be fixed upstream: https://github.com/sveltejs/svelte/issues/10979

**Comment by xiBread** [comment]
That was fixed but `next.90` introduced a new error because the specifier was only added to avoid Vite throwing on startup. Please see the second screenshot.

**Comment by bluwy** [comment]
Seems like we need to use the new entrypoints now:

https://github.com/withastro/astro/blob/260f4fa1912ba78299c587a7cad1101354ebbb48/packages/integrations/svelte/server-v5.js#L1

https://github.com/withastro/astro/blob/260f4fa1912ba78299c587a7cad1101354ebbb48/packages/integrations/svelte/client-v5.js#L2

and bump the peer dep to next.90
