### ISSUE TITLE
MDX cannot find relative image path without leading `./`

### ISSUE THREAD

**Issue by tisonkun** [withastro/astro#10641]
### Astro Info

```block
Astro                    v4.5.12
Node                     v21.6.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/mdx
```

### Describe the Bug

```
13:05:42 [ERROR] Cannot find module 'banner.png' imported from '/Users/tison/Brittani/nightsky-blog/src/content/posts/greptimedb-community-report/index.mdx'
  Stack trace:
    at /Users/tison/Brittani/nightsky-blog/src/content/posts/greptimedb-community-report/index.mdx?astroPropagatedAssets
    [...] See full stack trace in the browser, or rerun with --verbose.
```

```
![GitHub Banner](./banner.png) works
![GitHub Banner](banner.png) failed
```

### What's the expected result?

Both compiled

### Link to Minimal Reproducible Example

https://github.com/tisonkun/repro-astro-gldfcz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by OliverSpeir** [comment]
Thanks for bringing this up! Recently added this functionality to markdown but not mdx, definitely would like to see this work in mdx as well.

**Comment by rishi-raj-jain** [comment]
@OliverSpeir 

Possible to a link a PR to the markdown contribution enabling this? I'm happy to try it out for mdx.

**Comment by OliverSpeir** [comment]
@rishi-raj-jain 

[The md code](https://github.com/withastro/astro/blob/48f158215de64dcf78c4b1e8489aa965e703577d/packages/astro/src/vite-plugin-markdown/images.ts#L8)

[The mdx code](https://github.com/withastro/astro/blob/48f158215de64dcf78c4b1e8489aa965e703577d/packages/integrations/mdx/src/remark-images-to-component.ts#L38)

basically just adding the ./ if the path isn’t already relative

**Comment by rishi-raj-jain** [comment]
Thank you for the references, I've created the PR after testing the changes locally.
