### ISSUE TITLE
Error: Access is denied.

### ISSUE THREAD

**Issue by yisar** [withastro/astro#10658]
### Astro Info

```block
can not console log
```

### Describe the Bug

![18eb627d25ae572030f481c16d3b2e60](https://github.com/withastro/astro/assets/12951461/1daa5692-6404-42ab-80fb-a145cd6d81c7)

### What's the expected result?

run success

### Link to Minimal Reproducible Example

https://github.com/bmdavis419/astro-hono-example

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mingjunlu** [comment]
Hi @yisar,

After cloning your repo, I can successfully run the dev server without any error.

One thing I noticed is that you used `yarn dev` in your screenshot. Since the repo you provided uses pnpm, could you try the steps below? (It's equivalent to the instructions in README)

1. `pnpm install`
2. `pnpm run dev`

**Comment by yisar** [comment]
It's worth mentioning that I am a Windows computer.

**Comment by matthewp** [comment]
I tested on Windows with both pnpm and yarn and it worked. It seems likely to me that the install did not finish successfully as this is a common sort of error on windows when that happens. I would recommend running `pnpm install` again.

Also, the reproduction is not minimal. Given that dev doesn't start I think most of these dependencies are not needed to see the problem. If you can recreate using the __Empty Project__ template from here: https://astro.new/latest please file a new issues with the minimal things needed. Thanks!

**Comment by yisar** [comment]
I tested pnpm and it still reported an error. Any project using astro/db will report this error. This is a compatibility issue, not a code issue.

**Comment by yisar** [comment]
Please reopen this
