### ISSUE TITLE
SSL errors with hybird/prerendered 404 pages

### ISSUE THREAD

**Issue by lifeisfakenews** [withastro/astro#10664]
### Astro Info

```block
Astro                    v4.5.14
Node                     v20.11.1
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

Visiting a 404 page with output mode hybrid and no `prerender = false` gives the error
```
TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #renderError (file:///workspaces/astro-ssl-bug-of-annoyingess/dist/server/entry.mjs:881:27)
    at async file:///workspaces/astro-ssl-bug-of-annoyingess/dist/server/entry.mjs:1127:26 {
  cause: [Error: 00885EF8AF7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
```

make sure you follow the steps to reproduce in the repro README it wont happen if you arent using a https url

### What's the expected result?

Page loads correctly and doesnt throw an error
(ik this isnt exactly the most helpful but not really sure what else to put)

### Link to Minimal Reproducible Example

https://github.com/lifeisfakenews/astro-ssl-bug-of-annoyingess

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
The prerendered 404 page loads correctly. Is there something else about your setup that could be involved?

https://github.com/withastro/astro/assets/69170106/1c70037d-9cdc-4ece-87e9-d8f33ace87f2

**Comment by lilnasy** [comment]
I only see it with codespaces, not gitpod.

**Comment by lifeisfakenews** [comment]
"minor bug"

starlight doesnt work at all if your project has `hyrbid` output enabled (breaks my api docs completely)

**Comment by lilnasy** [comment]
Do you see it somewhere other than codespaces?

**Comment by lifeisfakenews** [comment]
yes - i see it when its hosted on my vps in 2 different projects, one without starlight and one with

Thats the only other place ive tested tho
