### ISSUE TITLE
resolve unprefixed routes when `prefixDefaultLocale: true`

### ISSUE THREAD

**Issue by stefanprobst** [withastro/astro#10660]
### Astro Info

```block
Astro                    v4.5.12
Node                     v20.12.0
System                   Linux (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/markdoc
                         keystatic
```

### Describe the Bug

in a project which uses `astro:i18n` with `prefixDefaultLocale: true`, i want to use the [keystatic cms astro integration](https://keystatic.com/docs/installation-astro), which [injects a `/keystatic` route](https://github.com/Thinkmill/keystatic/blob/main/packages/astro/src/index.ts#L44-L50) for the cms admin ui.

however, i cannot reach the `/keystatic` route but instead get a 404 page (it works correctly only when i set  `prefixDefaultLocale: false`).

it would be nice if astro could still resolve routes without locale prefix in `/src/pages/`, or any unprefixed routes injected by an integration, when `prefixDefaultLocale` is set to true.

issue repro with keystatic astro integration: https://github.com/stefanprobst/issue-keystatic-astro-i18n-prefix
issue repro with just a route file in pages folder: https://github.com/stefanprobst/issue-astro-i18n-prefix-default-locale

### What's the expected result?

be able to reach the injected `/keystatic` route, even when `prefixDefaultLocale: true` is set

### Link to Minimal Reproducible Example

https://github.com/stefanprobst/issue-keystatic-astro-i18n-prefix

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
It seems that Astro is working as expected, so I don't think this is a bug. 

Since you have particular needs, I would wait for `v4.6.0`, when we will land a new feature where you can create your own i18n routing: https://github.com/withastro/astro/pull/10193
