### ISSUE TITLE
Prod build collections cache can be modified

### ISSUE THREAD

**Issue by SStembridge** [withastro/astro#10700]
### Astro Info

```block
Astro                    v4.5.16
Node                     v20.9.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When building for production, the first time a collection is loaded it can be manipulated in a way that affects the cache and results in the manipulations carrying over to subsequent calls to getCollection. This doesn't happen when running or building dev.

### What's the expected result?

The cached collection should not be affected by operations performed after loading it.
I believe I found the cause is simply line 113 here returning the original array rather than a copy like it does when the cache is used on line 81:
https://github.com/withastro/astro/blob/8214bacfeaf478ec8ff57a92655963441f3f45e9/packages/astro/src/content/runtime.ts#L79-L114

### Link to Minimal Reproducible Example

https://github.com/SStembridge/astro-collections-cache-prod-build

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@ascorbic after thinking about it, I think you are probably right that freezing would be a breaking change for people. So it might be better for now that we just make a copy each time `getCollection` is called and in 5.0 we can switch to freezing.
