### ISSUE TITLE
Trailing Slash Should Be Added Automatically 

### ISSUE THREAD

**Issue by Barzi-Ahmed** [withastro/astro#10704]
### Astro Info

```block
Windows 11 64-bit

Astro 4.5.16
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

Hello,
In Next.js and SvelteKit, when trailingSlash is set to "always", and you go to `example.com/about`, the route changes to `example.com/about/` and it opens successfully, but in Astro when trailingSlash is always, `example.com/about` will result in 404, only if you explicitly type the trailing slash, liken`example.com/about/` then it will opened. 

### What's the expected result?

Please make trailing slash work same like the rest of frameworks, by adding the trailing slash automatically when not explicitly written, in "always" mode.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mingjunlu** [comment]
Hi @Barzi-Ahmed,

You can create a reproduction repo on StackBlitz without registering or logging in. Try this minimal template:
https://astro.new/minimal?on=stackblitz

Once you set up everything it needs to reproduce the problem, hit `Command + S` or `Control + S` to save the changes. It will then create a unique URL for the repo.

**Comment by ematipico** [comment]
@Barzi-Ahmed we ask you to open a discussion in the roadmap repository, that's where suggestions should go.

Astro, in this case, works as per design.
