### ISSUE TITLE
Show console output even set `--silent`.

### ISSUE THREAD

**Issue by ktym4a** [withastro/astro#10703]
### Astro Info

```block
Astro                    v4.5.16
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-robots-txt
```

### Describe the Bug

Show console output even set `--silent`.

This happens when the integration uses `console` for output instead of `AstroIntegrationLogger`.

### What's the expected result?

I don't know if it is correct to show `console`, but just the documentation says this:

> Enables silent logging, which will run the server without any console output.

https://docs.astro.build/en/reference/cli-reference/#--silent

So I expect that not show.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

If this is a bug, I would like to work on it. (I'm sure I will ask some questions.)

**Comment by rishi-raj-jain** [comment]
Hey @ktym4a,

May you share in which integration did you see this?

**Comment by ktym4a** [comment]
@rishi-raj-jain 
For example, `astro-robots-text`.
https://github.com/alextim/astro-lib/blob/a2562321a5b9421d630d825b80b265061f5a3515/packages/astro-robots-txt/src/index.ts#L69

but you can try to see like this one.
```ts
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  site: 'https://example.com',
  integrations: [{
		name: 'test',
		hooks:{
			"astro:build:done": ({logger}) => {
				logger.info("Logger: Build done")
				console.log("Console: Build done")
			}
		}
	}]
});
```

---

in console
```bash
[~/private/astro/examples/starlog] pnpm build --silent

> @example/starlog@0.0.1 build /private/astro/examples/starlog
> astro build "--silent"

Console: Build done
```

**Comment by rishi-raj-jain** [comment]
I think the docs meant it for the astro core, excluding the external integration ecosystem. 

Console logs become helpful in integration and package components to personalize as the creator seems fit I guess.

According to me, this falls outside the purview of core.

**Comment by ktym4a** [comment]
Yes, I understand that too.

> Enables silent logging, which will run the server without any console output.

I just feel in that case that the docs are a bit inaccurate.

**Comment by ematipico** [comment]
We can't silence the global object `console`, other integrations and libraries can use it.


Silenced logs are only the ones emitted by astro itself, and the ones emitted using the astro logger

**Comment by florian-lefebvre** [comment]
Yeah I think it only affects the logger for integrations, not console
