### ISSUE TITLE
The errorOverlay's themeSwitch does not work as expected.

### ISSUE THREAD

**Issue by liruifengv** [withastro/astro#10715]
### Astro Info

```block
Astro                    v4.5.12
Node                     v18.16.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

## Issue
The errorOverlay's themeSwitch does not work as expected.

### Prerequisites
- User's system use dark mode
- When the user first encounters the error page, open the errorOverlay.
- No localstorage `astroErrorOverlayTheme` now.

### Steps
1. open the errorOverlay
2. theme is detected as dark
3. Click the themeSwitch
4. themeSwitch's check status is wrong
5. theme toggle also does not work

## Video

https://github.com/withastro/astro/assets/25167721/932b9dea-ffcb-457f-a5c6-cc42c8007a97

## Reason
- When it is detected that the system is dark, it is not saved to localstorage.
- `isDark` should be `localStorage.astroErrorOverlayTheme === 'dark' || this?.classList.contains('astro-dark')`

### What's the expected result?

errorOverlay's themeSwitch works correctly

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xx2wzh

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
PR is here: https://github.com/withastro/astro/pull/10661
