### ISSUE TITLE
solid-js onCleanup is called on the server and it breaks the app

### ISSUE THREAD

**Issue by DrevaSergii** [withastro/astro#10710]
### Astro Info

```block
Astro                    v4.5.16
Node                     v18.19.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/solid-js
                         @astrojs/tailwind
```

### Describe the Bug

I want to subscribe to document clicks when the component is mounted and unsubscribe when the component is unmounted. Solid provides two functions to manage lifecycle - onMount and onCleanup.
However, my app crashes when I put document in onCleanup.
I observed that onCleanup is called when the app starts on the server, where there is no document.

I couldn't reproduce this issue with solid start
https://playground.solidjs.com/anonymous/dac2d20e-5f9e-4bbc-be95-73ff967c88d2

### What's the expected result?

Since onMount isn't invoked on the server, I believe onCleanup shouldn't be invoked on the server either.

<img width="1728" alt="Screenshot 2024-04-07 at 10 44 06" src="https://github.com/withastro/astro/assets/27158929/5716c778-15f4-4f0d-8578-332ccb1f6bbf">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-eq5yjh?file=src%2Fcomponents%2FDemo.tsx,src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Astro doesn't control how `onCleanup` is called. Solid [compiles and includes it](https://playground.solidjs.com/anonymous/dac2d20e-5f9e-4bbc-be95-73ff967c88d2) (SSR output) and the server module for `solid-js` doesn't make [`onCleanup` a noop](https://github.com/solidjs/solid/blob/dbdc27df2246ec05c0e32cf7b461ddbe4223915f/packages/solid/src/server/reactive.ts#L156-L162) (unlike the `onMount` above it).
