### ISSUE TITLE
When setting the prefixDefaultLocale = false, fallback to default is not working at homepage.

### ISSUE THREAD

**Issue by dande-sun** [withastro/astro#10724]
### Astro Info

```block
Astro                    v4.5.12
Node                     v20.8.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/vue
                         @astrojs/tailwind
                         @astrojs/mdx
                         @astrojs/partytown
                         client:eager
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

when setting below options, the fallback for SG homepage is not working, the `Location` in response is a null string.
`i18n: {
    defaultLocale: "default",
    locales: [
      "default",
      "fr",
    ],
    fallback: {
      "fr": 'default'
    },
    routing: {
      prefixDefaultLocale: false
    }
  },
  trailingSlash: "never"`

This is the response, 
`Request URL:
https://astro.avepoint.com/uk
Request Method:
GET
Status Code:
302 Found
Remote Address:
10.1.0.182:443
Referrer Policy:
strict-origin-when-cross-origin
Date:
Tue, 09 Apr 2024 07:31:48 GMT
Last-Modified:
Tuesday, 09-Apr-2024 07:31:48 UTC
Location:
Referrer-Policy:
no-referrer-when-downgrade
`

### What's the expected result?

It's should be fallback to default homepage.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xfj9kv?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Can you please create a valid reproduction? The reproduction uses the `fr` language, but then the `pages/` folder contains a `es/` folder instead.

Also, when running `astro build`, I can see the emitted files as expected.

**Comment by dande-sun** [comment]
@ematipico, the `fr` only an example, I set the fallback `fr` to default, but there not have the `fr` homepage, it should be fallback to default homepage, the bug does not need `astro build`, in the `dev` mod is same too.
Anyway I updated the reproduction, https://stackblitz.com/edit/github-xfj9kv

**Comment by ematipico** [comment]
@dande-sun: thank you
