### ISSUE TITLE
Quotes in YAML codeblocks can escape and leak onto the page

### ISSUE THREAD

**Issue by Noxsios** [withastro/astro#10726]
### What version of `starlight` are you using?

0.21.2

### What version of `astro` are you using?

4.5.12

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Brave (Chromium)

### Describe the Bug

Note sure if this is a bug in Starlight, Astro, Expressive Code or Shiki.

Seeing the following weird behavior for certain YAML codeblocks. I think something is not properly escaping `" >`, resulting in code getting leaked.

![Screenshot 2024-04-08 at 1 13 09 PM](https://github.com/withastro/starlight/assets/50058333/10d97477-f4f9-48e9-87b6-735b2eac9709)

![Screenshot 2024-04-08 at 1 12 59 PM](https://github.com/withastro/starlight/assets/50058333/42eb2390-5c28-4e38-a252-e947d0e63dc0)

markdown to replicate:

````md
broken:

```yaml
cmd: echo "foo" && echo "bar" > /tmp/hello.txt
```

working:

```yaml
# comment before causes it to work
cmd: echo "foo" && echo "bar" > /tmp/hello.txt
```

```yaml
- echo "foo" && echo "bar" > /tmp/hello.txt
```

```bash
echo "foo" && echo "bar" > /tmp/hello.txt
```
````

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sdjcwl-k7jz7g?file=src%2Fcontent%2Fdocs%2Findex.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
For context:

- Expressive Code uses a `data-code` attribute in its copy button to store the code to copy to the clipboard.
- In Astro 4.5.2 and lower this was correctly escaped, but in 4.5.3 and higher certain strings are not escaped properly, and end up getting rendered as HTML.

**Comment by Noxsios** [comment]
tyvm @ematipico !
