### ISSUE TITLE
TypeError: possibleFilePath?.replace is not a function

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#10741]
### Astro Info

```block
Astro                    v4.5.18
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/vue
                         astro-auth
                         @astrojs/react
                         @sentry/astro
```

### Describe the Bug

I get the following error when building on CI server:

```
12:39:27 [ERROR] [vite] x Build failed in 11.04s
TypeError: possibleFilePath?.replace is not a function
    at collectInfoFromStacktrace (file:///app/node_modules/astro/dist/core/errors/dev/utils.js:109:38)
    at file:///app/node_modules/astro/dist/core/errors/dev/utils.js:17:25
    at Array.forEach (<anonymous>)
    at collectErrorMetadata (file:///app/node_modules/astro/dist/core/errors/dev/utils.js:15:7)
    at throwAndExit (file:///app/node_modules/astro/dist/cli/throw-and-exit.js:16:29)
    at cli (file:///app/node_modules/astro/dist/cli/index.js:172:11)
```

Unfortunately, I can't reproduce it locally or on stackblitz. It actually masks another error I'm debugging. However, looking at the [code](https://github.com/withastro/astro/blob/ba3af206b53d8ea9aca78361c66e9806c660ad2a/packages/astro/src/core/errors/dev/utils.ts#L177), I see a potential mistake that the second `replace` is not called defensively:

```ts
const source = possibleFilePath?.replace(/^[^(]+\(([^)]+).*$/, '$1').replace(/^\s+at\s+/, '');
```

In any case, `collectInfoFromStacktrace` function is not robust against potentially missing data.

### What's the expected result?

Astro's error handling should be robust. Showing raw error is always better than masking the error with own failure.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
The change you've identified seems reasonable. Although, ideally we would be able to recreate the error before correcting it.

Could you share what CI server this occurs on alongside a small project? Is it running a non-Node runtime?

**Comment by lilnasy** [comment]
Could you run another build with `experimental--10745` as the astro version instead of `4.5.18`.

**Comment by HananoshikaYomaru** [comment]
I got this bug too, this lead to build fails on vercel. my astro version 4.5.16

**Comment by lilnasy** [comment]
@HananoshikaYomaru do you see the real error after deploying with `astro@experimental--10745`?

**Comment by shishkin** [comment]
@lilnasy thanks for the quick response. I can confirm that `astro@experimental--10745` displays the real error.
