### ISSUE TITLE
Bun no longer being detected in `astro/cli/install-package.ts`

### ISSUE THREAD

**Issue by jacobdalamb** [withastro/astro#10748]
### Astro Info

```block
Astro                    v4.5.18
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### Describe the Bug

Running `bun astro check` returns 
![CleanShot 2024-04-10 at 13 22 41](https://github.com/withastro/astro/assets/44789941/6533fbe3-e957-4f7d-a461-558571e53cd7)

### What's the expected result?

Should say `bun add @astrojs/check typescript`

### Link to Minimal Reproducible Example

https://astro.new/basics?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Bun is not a supported package manager. If it works, it works, but it will be a conversation before we make an official decision to add it.

**Comment by jacobdalamb** [comment]
> Bun is not a supported package manager. If it works, it works, but it will be a conversation before we make an official decision to add it.

No, but it should be properly detecting it. https://github.com/withastro/astro/blob/main/packages/astro/src/cli/install-package.ts

**Comment by lilnasy** [comment]
Is there something about your environment that could be preventing it?

**Comment by jacobdalamb** [comment]
> Is there something about your environment that could be preventing detection of bun?

I don't think so. I tried running it on a new astro project and I got the same result.

**Comment by lilnasy** [comment]
I notice that you added bun detection in https://github.com/withastro/astro/pull/8306. Did it stop working after a certain version?

**Comment by jacobdalamb** [comment]
> I notice that you added bun detection in #8306. Did it stop working after a certain version?

I guess it must have stopped working, or I didn't check a scenario when running a cli command for an integration that isn't installed. Because bun detection works for creating a new astro project, astro info, and adding integrations. 

I'm not sure if this issue takes place in [index.ts](https://github.com/withastro/astro/blob/main/packages/astro/src/cli/add/index.ts) or [install-package.ts](https://github.com/withastro/astro/blob/main/packages/astro/src/cli/install-package.ts)
