### ISSUE TITLE
How to output cjs files instead of esm with node ssr

### ISSUE THREAD

**Issue by harshil1507** [withastro/astro#10759]
### Astro Info

```block
Astro                    v4.5.18
Node                     v18.20.1
System                   macOS (x64)
Package Manager          yarn
Output                   server
Adapter                  @astrojs/node
```

### Describe the Bug

I have a backend and want to add astro for some SSR. When running `astro build` command, the generated files have a .mjs extension and are not compatible to be used with CJS files. Is there a way to generate CJS files instead? 

### What's the expected result?

`astro build` command should give an option to build CJS files.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/ssr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Our build flow only allows ESM output. CJS is not supported (and with no plans for it).
