### ISSUE TITLE
(sitemap) Root site URL in generated sitemap does not respect AstroConfig.trailingSlash

### ISSUE THREAD

**Issue by gislerro** [withastro/astro#10751]
### Astro Info

```block
Astro                    v4.5.18
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

### Describe the Bug

Using this Astro Config:
```js
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
	site: 'https://example.com',
	trailingSlash: 'never',
	integrations: [sitemap()],
});
```

results in the following `sitemap-0.xml` being generated after `astro build` on a basic setup two pages `index.astro` and `about.astro`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
   xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
   xmlns:xhtml="http://www.w3.org/1999/xhtml"
   xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
   xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
   <url>
      <loc>https://example.com/</loc>
   </url>
   <url>
      <loc>https://example.com/about</loc>
   </url>
</urlset>
```

### What's the expected result?

All urls in the generated sitemap conform to the `trailingSlash` config option:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
   xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
   xmlns:xhtml="http://www.w3.org/1999/xhtml"
   xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
   xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
   <url>
      <loc>https://example.com</loc>
   </url>
   <url>
      <loc>https://example.com/about</loc>
   </url>
</urlset>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-6n4cpf?file=dist%2Fsitemap-0.xml

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by gislerro** [comment]
After some investigating this seems to be an upstream issue in [sitemap.js](https://github.com/ekalinin/sitemap.js/issues/403). I could implement the workaround suggested if it's desired

**Comment by ematipico** [comment]
I believe we could attempt to apply the workaround. @gislerro, would you like to send a PR?

**Comment by tholyong** [comment]
Hi, is there a way to maintain a trailing slash for the root URL even when AstroConfig.trailingSlash is 'never'? The majority of the browsers will land/redirect the root URL with a trailing slash (although we can't see it, but when we copy the URL the trailing slash is included). So in the Sitemap and for a better SEO practice, it is probably a good idea to have the root URL with the trailing slash included even when AstroConfig.trailingSlash is 'never'.
