### ISSUE TITLE
img tag from <Image /> component isn't self-closing after building the project

### ISSUE THREAD

**Issue by Arom1a** [withastro/astro#10786]
### Astro Info

```block
$ pnpm astro info
Astro                    v4.6.1
Node                     v21.7.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I'm importing an image using the `<Image />` in `astro:assets`. 

The image is correctly rendered, but I got problem when parsing the page using `DOMParser()`. An error happened since the img tag is not enclosed. 

The resulted built page has: `<img src="/_astro/sample.Cp5117vv_ZAxtwn.webp" data-image-component="true" alt="sample" width="278" height="300" loading="lazy" decoding="async">`

Reproduce: 
in `src/page/index.astro`:
```astro
---
import {Image} from "astro:assets"
import sample from "../../public/sample.png"
---

<html lang="en">
    <head>
    </head>
    <body>
        <Image src={sample} alt="sample" />
    </body>
</html>
```
and I placed the `sample.png` at `public/sample.png`. 

After this, ran `pnpm run build` and got this in the built `index.html`
```
<!DOCTYPE html><html lang="en"> <head><meta charset="utf-8"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><meta name="viewport" content="width=device-width"><meta name="generator" content="Astro v4.6.1"><title>Astro</title></head> <body> <img src="/_astro/sample.Cp5117vv_ZAxtwn.webp" data-image-component="true" alt="sample" width="278" height="300" loading="lazy" decoding="async"> </body></html>
```

---

I'm interested in contributing to this project. However, I'm a newcomer. 

It seems that in `packages/astro/components/Image.astro`, the img tag is self-enclosing, but it is not true in the built page. Is this file the one used during the building process?

I would like to ask for a documentation talking about how astro build the pages. Tks!

### What's the expected result?

It is expected to self-close the tag. 

`<img src="/_astro/sample.Cp5117vv_ZAxtwn.webp" data-image-component="true" alt="sample" width="278" height="300" loading="lazy" decoding="async" />`

### Link to Minimal Reproducible Example

Sorry that I cannot upload an image to stackblitz...

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Arom1a** [comment]
Error msg from the parser is provided below:
```
XMkL Parsing Error: mismatched tag. Expected: </img>
```

**Comment by Princesseuh** [comment]
`img` is a void element and as such does not need to be closed. https://html.spec.whatwg.org/multipage/syntax.html#void-elements

You might find this article interesting too https://jakearchibald.com/2023/against-self-closing-tags-in-html/

**Comment by Arom1a** [comment]
Ty so much for providing me the solution and articles!
Specifying HTML does solve my problem.
