### ISSUE TITLE
Ran errors instead of warnings

### ISSUE THREAD

**Issue by jamesli2021** [withastro/astro#10794]
### Astro Info

```block
Astro                    v4.6.1
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations
```

### Describe the Bug

` npx astro check` in your project and found the summary indicate # errors instead of showing as # warning when those are appear to be warning. So I get 9 warning is an wrong indication.

### What's the expected result?

Issues with coding under warning should be counted as warning, not errors.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
We still need a repro.
