### ISSUE TITLE
--outDir changes env.d.ts

### ISSUE THREAD

**Issue by cdtut** [withastro/astro#10808]
### Astro Info

```block
Astro                    v4.5.16
```

### Describe the Bug

`astro build --outDir /tmp/project` adds `/// <reference path="../.astro/types.d.ts" />` to `env.d.ts` file. But `astro dev` or `astro build` don't add anything.

### What's the expected result?

It doesn't add anything like other commands.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jqwvp1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
> ### What's the expected result?
> 
> It doesn't add anything like other commands.

In this section, you should explain how it should be the **correct** use case, what you expected in case there wasn't a bug.

For example, if you run `astro build`, what should you expect in `env.d.ts`?

**Comment by Princesseuh** [comment]
The repro does not reproduce the problem, seems to be an empty project.
