### ISSUE TITLE
Importing "astro:db" in Vitest unit testing produces error

### ISSUE THREAD

**Issue by MatteoL-W** [withastro/astro#10804]
### Astro Info

```block
Astro                    v4.6.1
Node                     v20.12.0
System                   macOS (x64)
Package Manager          unknown
Output                   hybrid
Adapter                  none
Integrations             astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

Hello team ! I hope you're doing well

I have an Astro project, using **astro:db** and **Vitest**.
I would like to unit test my database handmade fetching functions, with the seed values.

As soon as I import {db} from "astro:db" into a test file, I have the following error:
`Error: Failed to load url astro:db (resolved id: astro:db) in [...]/test/basic.test.ts. Does the file exist?`

And so, my tests are failing: 
```
      Test Files  1 failed (1)
      Tests  no tests
```

Additionally, when I start the test, I receive these two pieces of information:
```
10:51:48 [astro:db] New local database created.
10:51:48 [ERROR] [astro:db] The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '\x00astro:db:seed'
```

### What's the expected result?

I would expect the test files to allow the import of anything located in "astro:db"

The Minimal Reproducible Example is really minimal, but it reproduces the issue of my main project.
I'm a beginner to unit testing integration, so I might do something wrong! 
Have a nice day!

### Link to Minimal Reproducible Example

https://github.com/MatteoL-W/astrodb_vitest_issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Fixed in https://github.com/withastro/astro/pull/10846
