### ISSUE TITLE
Astro build fails when the filename contains '#'.

### ISSUE THREAD

**Issue by Patrickill** [withastro/astro#10803]
### Astro Info

```block
Astro                    v3.6.1
Node                     v20.9.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
```

### Describe the Bug

I created an md file as my new blog content, and named the file "JavaScript基础#1——事件循环与Promise.md". Then, during the build process, the terminal reported an error: 
```
[vite]: Rollup failed to resolve import "/src/content/blog/JavaScript基础#1——事件循环与Promise.md?astroContentCollectionEntry=true" from "astro:content".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external. 
```
After I removed the # from the file name, I was able to build normally.

### What's the expected result?

build successfully :)

### Link to Minimal Reproducible Example

https://github.com/Patrickill/my-blog/actions/runs/8721085469

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
To which URL do you expect the blog map to?

**Comment by bluwy** [comment]
Vite doesn't handle well when `#` is in the file name. For example:

```
/src/content/blog/JavaScript基础#1——事件循环与Promise.md?astroContentCollectionEntry=true
```

The `#` makes everything pass it possibly removed, especially the `?astroContentCollectionEntry=true` part. It's probably best to avoid the `#`. Fixing this will be hard and will likely incur performance hit for all module resolving by default.
