### ISSUE TITLE
Inline script for component is added to the page even if component is absent on the page

### ISSUE THREAD

**Issue by Antonytm** [withastro/astro#10817]
### Astro Info

```block
(I was able to reproduce the same on Stackblitz, so I checked the `I am using the latest version of Astro and all plugins` checkbox)
Locally I have:

Astro                    v4.5.13
Node                     v20.12.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/vue
                         @analogjs/astro-angular
```

### If this issue only occurs in one browser, which browser is a problem?

It is server generated part

### Describe the Bug

**Steps to reproduce:**
I use Astro in a pair with CMS. I got some data from it. Based on that data, some components are added or removed to the page.

Oversimplified version:
```
---

import Component1 from "./Component1.astro"
import Component2 from "./Component2.astro"

export interface Props {
  component: string
}

---

{Astro.props.component === '1' && <Component1/>}
{Astro.props.component === '2' && <Component2/>}
```

Both components, `Component1` and `Component2` contain some script.  I got data that I should render `Component1`, but not the `Component2`.  (Astro.props.component = 1). 

**Actual behavior:**
Scripts for both Component1 and Component2 are added to the header.

**Expected behavior:**
Script ONLY for `Component1` should be present in the header. 

---
I understand that according to the documentation, it works as expected. https://docs.astro.build/en/guides/client-side-scripts/
> Any imports will be bundled, allowing you to import local files or Node modules.

But if a big part of the presentation is controlled by the CMS side, it becomes quite inefficient. A lot of unused scripts are present in the header. I consider the `<script is:inline>` option, but it also has limitations. If the component is used twice, scripts are duplicated.

If there is another way to achieve it, please let me know.

### What's the expected result?

I want to be able to exclude the script from the header if the component wasn't rendered. (Based on logic on the page)
I understand that it will probably make the logic more complex and increase the build time.
However, the build time is less important compared to browser runtime for the SSG approach.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-21lir2-uyvgki

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Does using https://docs.astro.build/en/reference/configuration-reference/#experimentaldirectrenderscript fixes this for you?

**Comment by Antonytm** [comment]
@Princesseuh 
Yes, it works!

https://stackblitz.com/edit/github-21lir2-fsgmgw?file=astro.config.mjs
