### ISSUE TITLE
Redoc react component not rendering

### ISSUE THREAD

**Issue by lamATnginx** [withastro/astro#10815]
### Astro Info

```block
Astro                    v4.6.3
Node                     v21.2.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/markdoc
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Safari, Firefox

### Describe the Bug

Using redoc react component leads to an error of `require is not defined` on a local build. Similar issue can be seen in this past MR https://github.com/withastro/astro/pull/6933.

### What's the expected result?

Component should render on the page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dubfdg?file=README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You're using an old version of `@astrojs/react` where redoc is not configured. Try upgrading to 3.3.0.

**Comment by lamATnginx** [comment]
Thanks for replying. Upgraded to 3.3.0. Cleared `node_module` and reinstalled. Still receiving same error. 

`react` and `react-dom` are both `18.2.0` as well.

**Comment by matthewp** [comment]
Can you update the Stackblitz example as well?

**Comment by lamATnginx** [comment]
Done: https://stackblitz.com/edit/github-dubfdg-3cszvw?file=package.json

**Comment by lamATnginx** [comment]
Thanks for reviewing. Still encountering the same issue when upgraded to astro 4.6.4 with the new changes. Could you verify again on your end @matthewp.
