### ISSUE TITLE
`noUnusedLocals` and `noUnusedParameters` Settings Not Applied in Astro Build

### ISSUE THREAD

**Issue by bkyerv** [withastro/astro#10812]
### Astro Info

```block
Astro                    v4.6.1
Node                     v20.12.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

We are experiencing an issue where the TypeScript compiler options noUnusedLocals and noUnusedParameters are set to false in our tsconfig.json, but the settings do not seem to be applied during the Astro build process. Despite these settings, we continue to receive warnings about unused variables and parameters, which suggests that these compiler options are being ignored.

### What's the expected result?

All warning related to variable declared but not used should be ignored

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/bkyerv/for-triaging-a-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Those parameters are for outputting errors when locals and params are unused, TypeScript (which is what `astro check` uses) will still output hints for those, much like you see in the editor.

**Comment by Princesseuh** [comment]
It does not, see the documentation here: https://www.typescriptlang.org/tsconfig#noUnusedLocals. This exclusively makes it so it's an error instead of a warning.

**Comment by Aqzhyi** [comment]
hello, i have encountered the same issue as well

several hints appeared in the console, leading me to mistakenly believe they were genuine compilation errors

at present, i am able to resolve this issue by configuring the flag --minimumSeverity warning

https://github.com/Aqzhyi/issue-for-astro-check
