### ISSUE TITLE
@astrojs/rss uses trailing slash in urls when it shouldn't

### ISSUE THREAD

**Issue by patrickreiner** [withastro/astro#10838]
### Astro Info

```block
Astro                    v4.5.16
Node                     v20.12.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             astro:db
                         @astrojs/db/file-url
                         @astrojs/sitemap
```

### Describe the Bug

Hi,

In my astro.config.mjs I set:

export default defineConfig({
  ...
  trailingSlash: 'never',
})

and in my vercel.json I set:

{
  "cleanUrls": true,
  ...
  "trailingSlash": false
}

If you go to my site, https://art.patrickreiner.com you can see that none of the urls have a trailing slash, and if you put a trailing slash, you a redirected to the page without the slash.

And yet, my RSS feed file has a trailing slash added to every domain, you can see the live file here:
https://art.patrickreiner.com/artwork-rss.xml

### What's the expected result?

The RSS feed file should honor the settings, and not include a trailing slash

### Link to Minimal Reproducible Example

None

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Hi @patrickreiner , you should use the `trailingSlash` option of the RSS integration: https://github.com/withastro/astro/blob/main/packages/astro-rss/README.md#trailingslash
