### ISSUE TITLE
Add a new `Astro.metadata` global object

### ISSUE THREAD

**Issue by ematipico** [withastro/astro#10844]
This is an opportunity to land a new feature in Astro, without knowing too much about the **internals**; however, you must be familiar with Astro itself because you will implement a test that would require familiarity as a user. You will have to take care of everything:
- code
- tests
- documentation
- code reviews and address comments from reviewers

> [!IMPORTANT]
> We want to land this feature for **Astro v4.8**, scheduled for the 9th of May. Please don't volunteer if you can't commit to this deadline.

## Feature

We want to add a new `Astro.metadata`. The `metadata` will be used to store read-only information that integrations and users can use to implement some logic.

For this feature/issue, you will add `Astro.metadata.route`.

## Technical changes

Here's a TODO list of the things that you will have to do in order to land the PR:
- Add `metadata` in the `AstroGlobal` interface 
  https://github.com/withastro/astro/blob/a2df344bff15647c2bfb3f49e3f7b66aa069d6f4/packages/astro/src/%40types/astro.ts#L172-L176
- Create a new `AstroGlobalMetadata` interface and add `route`. The `route` type must be `RouteData['route']`. Make sure to document the stuff that you add. Follow the in-code patterns.
- Populate the `Astro` global object with `metadata.route`. The `RenderContext` has a `RouteData` object, that's where `metadata.route` will come from. I don't think we need any caching:
	- https://github.com/withastro/astro/blob/a2df344bff15647c2bfb3f49e3f7b66aa069d6f4/packages/astro/src/core/render-context.ts#L150
	- https://github.com/withastro/astro/blob/a2df344bff15647c2bfb3f49e3f7b66aa069d6f4/packages/astro/src/core/render-context.ts#L309
- Create an integration test. We already have `astro-global.test.js`, we can update that test with new use cases. 
	- This feature must work in dev, ssg, ssr. The metadata must be accessible inside Astro components, middleware and endpoints, so let's create tests to cover those cases
- Create a changeset that shows a minimal example

## Coordination

GitHub and Discord are the best places for coordination. Use the `#contribute` channel for questions.

**Comment by matfire** [comment]
hey, it's the guy from discord

**Comment by matthewp** [comment]
I might have missed the context on this one. So it looks like this is just the route string, right? What's the use-case for adding this?

**Comment by matfire** [comment]
I'd started looking at the codebase and trying to get a feel of how it all comes together :)
No problem; if and when it comes up again, I'd get glad to help
