### ISSUE TITLE
`@astrojs/mdx`: “smart quotes” are broken in HTML headers

### ISSUE THREAD

**Issue by johnnydecimal** [withastro/astro#10859]
### Astro Info

```block
Astro                    v4.6.4
Node                     v21.7.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

When Astro renders an MDX page where a header contains `"quotes"`, the rendering of `”smart quotes”` in the output is broken: both quotes are rendered as the closing quote.

## To reproduce
1. Create a new project using the blog template, `npm create astro@latest`.
2. Edit `/src/content/blog/using-mdx.mdx`, line 10, to include double-straight-quotes: `## "Why MDX?"`.
3. `npm run build`.
4. The source of the built page contains incorrect quotes, `<h2 id="why-mdx">”Why MDX?”</h2>`.

This is much more apparent when one uses a font with highly-stylised quotes. See [my built page here](https://6627318766110c000899c0e0--jdcmal.netlify.app/10-19-concepts/11-core/11.05-the-index/#this-sounds-like-a-lot-of-work) for an example.

### What's the expected result?

The header currently looks like this:

# ”Incorrect quotes”

It should look like this:

# “Correct quotes”

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vngmzc?file=src%2Fcontent%2Fblog%2Fusing-mdx.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is configurable by disabling smartypants, see https://docs.astro.build/en/reference/configuration-reference/#markdownsmartypants

**Comment by johnnydecimal** [comment]
May I respectfully appeal a triage decision?

Disabling the feature will ‘fix’ the issue, sure. Like not driving my broken car will prevent oil from spilling on the road.

But surely this is a desirable feature that many use? It’s on by default. And SmartyPants isn’t at fault here: if I run the Perl script manually, it processes it just fine:

```txt
perl SmartyPants.pl
# "hi"
# &#8220;hi&#8221;
```

That’s a [left double quote](https://www.codetable.net/decimal/8220) and a [right double quote](https://www.codetable.net/decimal/8221), as expected. SmartyPants works just fine. Astro is munging this somehow.

This is a bug.

**Comment by lliding** [comment]
I have the same problem. Disabling 'smartpants' fixes it.

**Comment by danielzting** [comment]
```
Astro                    v5.16.6
Node                     v23.7.0
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

This happens on regular Markdown files, not only MDX.

https://stackblitz.com/edit/github-vngmzc-45x2eice?file=src%2Fcontent%2Fblog%2Ffirst-post.md 

Attaching a screenshot here because left and right quotes look almost identical on GitHub, so the OP's report doesn't do it justice to how weird it looks:

<img width="300" height="73" alt="Image" src="https://github.com/user-attachments/assets/ecdf8440-a00d-4736-81d3-9247dc113ebf" />
