### ISSUE TITLE
Rendering React component does not work

### ISSUE THREAD

**Issue by dirkjf** [withastro/astro#10857]
### Astro Info

```block
Astro                    v4.6.3
Node                     v20.12.2
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/mdx
```

### Describe the Bug

Transfering from a NextJS app to Astro, I ran into the issue with one of my components which does not render correctly. This is the component:
```
import React, { ReactNode, useState } from 'react';

type TabsProps = {
  children: React.ReactNode;
  initialTab?: number;
};

type TabProps = {
  title: string;
  children: ReactNode;
};

export const Tabs: React.FC<TabsProps> = ({ children, initialTab = 0 }) => {
  const [activeTab, setActiveTab] = useState<number>(initialTab);

  const handleTabClick = (index: number) => {
    setActiveTab(index);
  };

  return (
    <div>
      <div>
        {React.Children.map(children, (child, index) => {
          if (React.isValidElement<TabProps>(child)) {
            return (
              <button
                key={child.props.title}
                onClick={() => handleTabClick(index)}
              >
                {child.props.title}
              </button>
            );
          }
          return null;
        })}
      </div>
      <div>{React.Children.toArray(children)[activeTab]}</div>
    </div>
  );
};

export const Tab = ({ children }: TabProps) => {
  return <>{children}</>;
};
```

And this is how it is used:
```
<Tabs>
  <Tab title='First'>
    <p>First tab content</p>
  </Tab>
  <Tab title='Second'>
    <p>Second tab content</p>
  </Tab>
</Tabs>
``` 

You can see this component working here: https://playcode.io/1846409

### What's the expected result?

In this example, two buttons should be rendered, instead only one is and the content of both children is shown in one div. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-n8hkfj

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hi @dirkjf, the reason this happens is because components inside of an Astro component are not React component. Astro components compile to strings, so what you receive inside of your Tabs component is not multiple React components, but the compiled HTML of those components as a single React component. It's not a Tabs at all, just a wrapper for the HTML.

If you want to compose React components this way, it's better to put that inside of a single island and include that in your Astro instead, like `<TabsContent client:only />`.

**Comment by dirkjf** [comment]
Hi @matthewp, thanks for the quick reply. I am not sure I understand, both the <Tabs> and <Tab> component are React components. However, adding `client:only="react"` to them makes no difference. Would changing these components to Astro components make a difference?

**Comment by dirkjf** [comment]
I understand, but this makes things tricky. Currently I have mdx files that have this kind of content, so I will have to find a way of converting this data.

**Comment by matthewp** [comment]
Yeah, just move the content into it's own JSX or TSX file. MDX gets compiled to Astro so it has the same constraints.

**Comment by dirkjf** [comment]
I am afraid that for my use-case, Astro might not be the right tool. I have hundreds of MDX pages which contain components that may require client side rendering and they use the syntax like mentioned above. I was looking into creating a wrapper for all the MDX which defines what components should be rendered on the server vs the client, but even making that work requires me to transform all the above mentioned syntax into HTML first and then transform it back into the component I want to use. But this will create so much overhead. If there is anything I am missing I would love to hear it.
