### ISSUE TITLE
Relative paths in css url() references get double encoded

### ISSUE THREAD

**Issue by SibiAkkash** [withastro/astro#10868]
### Astro Info

```block
Astro                    v4.6.4
Node                     v20.10.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I've set base = `/blog/John%20Doe` in the astro config.

When building and deploying the site, the final path to the assets in css url() references are double encoded.

The output paths in css url() becomes `/blog/John%2520Doe/...`, when they should stay `/blog/John%20Doe/...`
<br />

The background image url becomes - `/blog/John%2520Doe/_astro/[name].[hash].svg`

The font url becomes - `/blog/John%2520Doe/_astro/[name].[hash].ttf`

### What's the expected result?

The url() references shouldn't get double encoded. The % character in config.base is getting encoded to %25

Expected asset path in css url() : `/blog/John%20Doe/[name].[hash].[ext]`
Actual asset path in css url():       `/blog/John%2520Doe/[name].[hash].[ext]`

### Link to Minimal Reproducible Example

https://github.com/SibiAkkash/astro-double-encoding-example

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Why don't you set base to `/blog/John Doe` in that case?

**Comment by SibiAkkash** [comment]
> Why don't you set base to `/blog/John Doe` in that case?

I had tried that too, the same issue occurs.

**Comment by matthewp** [comment]
Ok, this is an upstream bug that is being fixed here: https://github.com/vitejs/vite/pull/16412 @bluwy is going to work on getting that finalized which should then fix in Astro as well.

**Comment by SibiAkkash** [comment]
Thanks @matthewp !
