### ISSUE TITLE
A command field in astro:config:setup returns build value while running check command

### ISSUE THREAD

**Issue by moose96** [withastro/astro#10876]
### Astro Info

```block
Astro                    v4.7.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             test
```

### Describe the Bug

Let's assume an Astro config like below:
```js
export default defineConfig({
  integrations: [
    {
      name: 'test',
      hooks: {
        'astro:config:setup': ({ command }) => {
          console.log(command);
        },
      },
    },
  ],
});
```
While running `astro check` the console outputs `build` string. This can be confusing, especially when running the command in the default pipeline: `astro check & astro build`. In this case, the `astro:config:setup` hook is called twice with `command === 'build'`, unexpectedly triggering certain code twice during the build.
Also, this behavior isn't documented: [https://docs.astro.build/en/reference/integrations-reference/#command-option](https://docs.astro.build/en/reference/integrations-reference/#command-option)

It appears to be caused by a hardcoded 'build' value in the mentioned line:[https://github.com/withastro/astro/blob/main/packages/astro/src/core/sync/index.ts#L62](https://github.com/withastro/astro/blob/main/packages/astro/src/core/sync/index.ts#L62)
```ts
const settings = await runHookConfigSetup({
	settings: _settings,
	logger: logger,
	command: 'build', // <- here
});
```

### What's the expected result?

I suggest three possible solutions:

1. `command` while running `astro check` has `check` value
2. `astro check` command is integrated with `astro build` always, so `astro:config:setup` calls once only (I think it's the worst option)
3. Describe this behavior in documentation

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yfhwgr?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Seems reasonable, would love a PR for this!

**Comment by Princesseuh** [comment]
This is probably not `astro check`'s doing, but a side effect of `astro check` running `astro sync` implicitly

**Comment by moose96** [comment]
> This is probably not `astro check`'s doing, but a side effect of `astro check` running `astro sync` implicitly

You're right. Whether it's `astro build` or `astro check`, both commands call the `sync` function which triggers `runHookConfigSetup` with `command` set to `build`. I've noticed the `sync` function has an optional second argument of type `SyncOptions`. Perhaps enhancing this function to accept properties like `runByCommand` via `SyncOptions` could provide better information about executed command?
