### ISSUE TITLE
Astro DB: push with --force-reset doesn't seem to work.

### ISSUE THREAD

**Issue by pMay2021** [withastro/astro#10873]
### Astro Info

```block
Astro                    v4.6.4
Node                     v21.7.3
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/mdx
                         astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

I've defined my tables in `config.ts` and have made some changes to them (though they really aren't breaking changes, as I'm adding some new columns but for some reason, the push kept failing).  Since I'm in the early stages, I just want to reset and recreate the database.

The documentation says I should do `npm run astro db push --remote --force-reset`

but when I do that, I see the following messages:

```

> owdcom@0.0.1 astro
> astro db push

✔ Connected to remote database.
Database schema is out of date.
Pushing database schema updates...
https://db.services.astro.build/db/push failed: 400 Bad Request
{"success":false,"error":{"code":"SQL_QUERY_FAILED","details":"SQLITE_CONSTRAINT: SQLite error: FOREIGN KEY constraint failed"}}
/db/push fetch failed: 400 Bad Request

```

There are very few foreign keys, and they are all named and referenced correctly (and have not changed). With the generic error message, I cannot figure out where the issue lies.

I see the same whether I do --remote or --force-reset. It's as if the force-reset flag isn't being considered.

_PS - I do not know if this is related to some of the db issues I've been seeing today and raised a separate ticket._

### What's the expected result?

Create the tables per the new schema.

### Link to Minimal Reproducible Example

db related

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
It is definitely possible that our logic to reset the db has bugs in it, but we can't help without a reproduction.

**Comment by anwaracquaint** [comment]
Hello @pMay2021  if you try to reset the astro db, then the command to reset your db is: **npx astro db push --force-reset**

**Comment by sarmong** [comment]
@matthewp I have the same issue and I think the problem arises when there are foreign keys - you cannot call `DROP TABLE` if there are foreign keys pointing at the table. So tables need to be deleted in specific order, not in arbitrary.

I am not well-versed in sqlite, but it seems like another way is to call `PRAGMA foreign_keys = OFF;`
