### ISSUE TITLE
@astrojs/mdx>=2 unnecessarily removes whitespaces and line breaks from multiline strings in Astro components props supplied from Remark

### ISSUE THREAD

**Issue by YonicDev** [withastro/astro#10888]
### Astro Info

```block
Astro                    v4.7.0
Node                     v21.7.3
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

In Astro v3 (`@astrojs/mdx^1`), when props are supplied to Astro components from MDX (by using a Remark plugin to wrap a markdown into an MDX element and filling its attributes in), multi-line strings are preserved. In Astro v4 (`@astrojs/mdx>=2`), they are altered in such a way that whitespace and line breaks are removed.

### What's the expected result?

```
Multiline
    strings
        like
    these
```
should have their indentation and line breaks preserved, and be rendered unaltered. Instead, they may look like this:

```
Multiline strings
like
these
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-md1ter?file=src%2Fcontent%2Fblog%2Fusing-mdx.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
In `@astrojs/mdx`, one of the biggest change is updating `@mdx-js/mdx` from v2 to v3. I'm guessing its breaking change is affecting your usecase. If I install `vite-plugin-inspect` to check the output, I can see that it's generating invalid code:

```jsx
return ... <Test code="this
    is
a
text
with
    varying
		    levels
	of
indentation
and
some
with
  consecutive
	      levels" lang="plaintext" />
```

The string is spread out in multiple lines, and we use esbuild + babel to later transform that, which is probably forgiving and concatenates them together, stripping out the indents.

I think to fix this, you need to manually escape the new lines before adding them as attributes. You can verify its needed by manually writing `<Test code="Multiline\n    strings\n        like\n    these" />` in the MDX file and inspecting the hast:

```js
{
  type: 'mdxJsxFlowElement',
  name: 'Test',
  attributes: [
    {
      type: 'mdxJsxAttribute',
      name: 'code',
      value: 'Multiline\\n    strings\\n        like\\n    these',
      position: [Object]
    }
  ],
  children: [],
  position: {
    start: { line: 46, column: 1, offset: 793 },
    end: { line: 46, column: 69, offset: 861 }
  },
  data: { _mdxExplicitJsx: true }
}
```

There's double slashes to preserve the escaping. Hence I think this is working as expectd and MDX v3 probably wasn't clear about this breaking change (or I can't find it). Closing this for now as Astro is not affecting this change.
