### ISSUE TITLE
Warning: ReactDOMServer.renderToStaticNodeStream() is deprecated. 

### ISSUE THREAD

**Issue by tjx666** [withastro/astro#10899]
### Astro Info

```block
Astro                    v4.7.0
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

<img width="1440" alt="image" src="https://github.com/withastro/astro/assets/41773861/1bc3014a-2a8f-41d7-8fb4-cc2d2880bf89">

```node
Warning: ReactDOMServer.renderToStaticNodeStream() is deprecated. Use ReactDOMServer.renderToPipeableStream() and wait to `pipe` until the `onAllReady` callback has been called instead.
```

I find a discuss on reddit: https://www.reddit.com/r/astrojs/comments/1cdbito/libsupabase_error_v46_and_v47_warning/?onetap_auto=true&one_tap=true

### What's the expected result?

no this warning

### Link to Minimal Reproducible Example

https://github.com/tjx666/astro-blog

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by david10sing** [comment]
I am still getting this issue in my project.

**Comment by leonelhenriquez** [comment]
> I am still getting this issue in my project.

as actualizado a [@astrojs/react@3.3.2 ? ](https://github.com/withastro/astro/releases/tag/%40astrojs%2Freact%403.3.2)
