### ISSUE TITLE
Build fails when using <style>.

### ISSUE THREAD

**Issue by seraku-matsuoka** [withastro/astro#10909]
### Astro Info

```block
Astro                    v4.7.0
Node                     v20.10.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When using <style> in an .astro file, I get the following error message when building.

Sometimes I can build without error, but the css is not loaded in the generated html file.

```zsh
09:40:32 [ERROR] [vite] x Build failed in 1.05s
[astro:build] Could not load C:/Users/path/to/project/src/pages/index.astro?astro&type=style&index=0&lang.css (imported by src/pages/index.astro): No cached compile metadata found for "C:/Users/path/to/project/src/pages/index.astro?astro&type=style&index=0&lang.css". The main Astro module "C:/Users/path/to/project/src/pages/index.astro" should have compiled and filled the metadata first, before its virtual modules can be requested.
  Stack trace:
    at Object.load (file:///C:/Users/path/to/project/node_modules/.pnpm/astro@4.7.0_typescript@5.4.5/node_modules/astro/dist/vite-plugin-astro/index.js:71:15)
    at file:///C:/Users/path/to/project/node_modules/.pnpm/rollup@4.17.1/node_modules/rollup/dist/es/shared/node-entry.js:19775:40
    at async file:///C:/Users/path/to/project/node_modules/.pnpm/rollup@4.17.1/node_modules/roll ELIFECYCLE  Command failed with exit code 1.
```

This happens even when I just created a project with default settings.

### What's the expected result?

Could be due to Windows environment rather than Astro, but could not be identified.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wnqguo?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Is it because your `<style>` is below the html tag?

**Comment by seraku-matsuoka** [comment]
@matthewp 
Thank you.
But just putting it in the html tag didn't solve the problem.

When I do a build, it generates an html file with no css loaded.

**Comment by BryceRussell** [comment]
Do you have any more details that you can share about your environment? I tried reproducing this on Windows, but I am not getting any errors and I can see the styles in the output of the build.

**Comment by seraku-matsuoka** [comment]
Sorry,
I tried it on another PC and it was not reproducible, so I'm closing this issue.

**Comment by El-Rico** [comment]
I had the same issue while doing the Astro blog tutorial. I updated to node v20. I was on v18. That fixed it for me.

**Comment by posti85** [comment]
I was facing the same issue and it was my browser was storing old cached data. It was in Developer Tools > Sources > Overrides > localhost:4321. Removing it solved the problem.
