### ISSUE TITLE
npx astro add fails on Node 22

### ISSUE THREAD

**Issue by davidjbradshaw** [withastro/astro#10905]
### Astro Info

```block
Astro                    v4.7.0
Node                     v22.0.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

Bash Mac OS 12.7.4

### Describe the Bug

When I ran `npx astro add` under Node 22 it crashed.

```sh
 % npx astro add tailwind
(node:58304) Warning: require() of ES modules is not supported.
require() of /Users/dave/dev/iframe-resizer/docs/node_modules/astro/astro.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename astro.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/dave/dev/iframe-resizer/docs/node_modules/astro/package.json.
```

### What's the expected result?

I expected the installer to run, switching to Node 20 fixes the issue

### Link to Minimal Reproducible Example

CLI issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mingjunlu** [comment]
Hi @davidjbradshaw,

Here's what I tried using Node.js v22.0.0 on macOS:

```shell
npm create astro@latest
cd ./hello-astro-node-22
npm install
npx astro add tailwind
```

However there was neither error nor crash on my side. Would it be possible for you to provide a minimal reproduction and the steps to reproduce the problem?

**Comment by davidjbradshaw** [comment]
The only difference that I can think of was that I installed Astro a few months ago on an earlier version of Node. Then upgraded to 22. I had upgraded to the latest version of Astro and Starlight before tying this. Beyond that I’m at a bit of a loss.

**Comment by davidjbradshaw** [comment]
Your welcome to try it on http://github.com/iframe-resizer/docs

**Comment by mingjunlu** [comment]
I still couldn't reproduce it somehow 😵

> The only difference that I can think of was that I installed Astro a few months ago on an earlier version of Node. Then upgraded to 22.

This might be related. Could you try removing `node_modules` then running `npm install` using Node.js v22?

**Comment by davidjbradshaw** [comment]
Yep that fixed it.

Thanks
