### ISSUE TITLE
Astro glob throw unsupported files for svg

### ISSUE THREAD

**Issue by Its-Just-Nans** [withastro/astro#10913]
### Astro Info

```block
Astro                    v4.7.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Astro glob throw unsupported files for svg

```js
const svgs = await Astro.glob("../files/*.svg")
```

throws

`unsupported file type: undefined`

### What's the expected result?

Detect and import svgs

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-vexf1b

**Comment by Grohotun** [comment]
I have almost the same error, but I do get object. But it's siblings are not having props, so even simple url to file is not working.

`---
const logos = await Astro.glob("../assets/clients/*.svg");
---
{logos.map((logo) => (
    <img src={logo.url} alt="A" width="100"/>
))}`

in dev mode it shows no images.

**Comment by Its-Just-Nans** [comment]
@Grohotun 

In fact, it's when a svg doesn't have width or height specified ;)

The PR https://github.com/withastro/astro/pull/10924 add a clearer error message

**Comment by Grohotun** [comment]
> @Grohotun
> 
> In fact, it's when a svg doesn't have width or height specified ;)
> 
> The PR #10924 add a clearer error message

@Its-Just-Nans  setting width & height doesn't help at all.

**Comment by Its-Just-Nans** [comment]
> > @Grohotun
> > 
> > In fact, it's when a svg doesn't have width or height specified ;)
> > 
> > The PR #10924 add a clearer error message
> 
> @Its-Just-Nans  setting width & height doesn't help at all.

Can you provide the svg ?

**Comment by Grohotun** [comment]
> > > @Grohotun
> > > In fact, it's when a svg doesn't have width or height specified ;)
> > > The PR #10924 add a clearer error message
> > 
> > 
> > @Its-Just-Nans  setting width & height doesn't help at all.
> 
> Can you provide the svg ?

Sure I can but in fact is doesn't matter, which svg's to use.
If I use Image component for any one of them - it is loading properly.

**Comment by Princesseuh** [comment]
The SVG in the repro is quite wonky, many tools can't parse it correctly. For instance, trying to paste it in https://jakearchibald.github.io/svgomg/ results in an error about it being invalid.

`image-size` tries its best to detect that it's a SVG, but it's tough when the SVG is malformed / unusually formed

**Comment by matthewp** [comment]
Closing as this is an upstream issue.
