### ISSUE TITLE
Path aliases in Markdown front-matter are not respected

### ISSUE THREAD

**Issue by NicksPatties** [withastro/astro#10949]
### Astro Info

```block
Astro                    v4.7.1
Node                     v20.12.2
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

I have defined a path alias in my `tsconfig.json` file to my `src/assets` directory called `@assets`. I have used the path alias in the front-matter of a markdown file and in the body of the markdown file. The path alias is not processed in the same way as it is in the image link in the markdown file.

### What's the expected result?

[According to the documentation](https://docs.astro.build/en/guides/images/#images-in-content-collections), images are processed in frontmatter the same way as they are in Markdown files, meaning that I can either use a relative path or an import alias to find the correct file.

In the sample provided, in the "Markdown Style Guide" blog page, I assign this path to my `heroImage` property, and also use it in my blog post. I expect the photo to be visible in both locations on the page, but only the image in the article is visible.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-frac3r?file=src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your schema is not configured properly. https://docs.astro.build/en/guides/images/#images-in-content-collections
