### ISSUE TITLE
i18n and transition

### ISSUE THREAD

**Issue by TheElegantCoding** [withastro/astro#10948]
### Astro Info

```block
Astro                    v4.7.0
Node                     v20.10.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
                         @astrojs/partytown
```

### Describe the Bug

I don't know if this is a bug, but i have a footer that needs to have `transition:persist`, it is needed to maintain other code working and i set up the i18n, on the page

unfortunately, if i have an anchor like this, the Astro.url.pathname will only work the first time the page open if i switch from the "/" to "/about-us", the href will be "/en" and not "/en/about-us"

```jsx
<footer transition:persist>
     <a
        href={changeLanguage('en', Astro.url.pathname)}
        class='footer__dropdown-button'
     >Ingles</a>
</footer>
```

this is an idea, but it doesn't work and i don't see anyone think of that, but as i see `transition:persist={false}` is not possible to do, maybe could be a feature to can change the child elements inside a `transition:persist` to not persist some elements

```jsx
<footer transition:persist>
     <a
        href={changeLanguage('en', Astro.url.pathname)}
        class='footer__dropdown-button'
       transition:persist={false}
     >Ingles</a>
</footer>
```

otherwise, the only solution i see here is to use javascript and change the anchor to a button, and then dynamic change the redirect that made

### What's the expected result?

-

### Link to Minimal Reproducible Example

I will provide one if needed

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
This is more a request for help, than a report of a bug. I can't see the real bug, and the absence of expectations and reproduction doesn't help.

I suggest you to seek help on Discord

**Comment by TheElegantCoding** [comment]
Thanks, sorry for post as a bug, i will search in discord more information
