### ISSUE TITLE
Provide a way to prevent script tags from running on the server side

### ISSUE THREAD

**Issue by danielo515** [withastro/astro#10953]
### Astro Info

```block
Astro                    v4.4.6
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/svelte
                         @sentry/astro
                         astrojs-service-worker
```

### Describe the Bug

The code inside `<script>` tags is always executed. This mean, they are executed in the client, but also in the server.
While I understand this is something useful in case the server dom needs to be modified, it will be nice to have a way to be able to opt-out for some script tags.
Components do not exhibit the same behavior, where you can decide if they run on the client or the server and the client.

### What's the expected result?

I want to be able to exclude some script tags to run while SSR without having to check for the SSR env variable.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-a7qbew?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Script tags don't run on the server, what do you mean more precisely? Your repro even show this, as the console log doesn't appear in the terminal.

**Comment by matthewp** [comment]
Closing, please file a new issue if you can reproduce.
