### ISSUE TITLE
script with "data-astro-rerun" cant have external library, give error 

### ISSUE THREAD

**Issue by TheElegantCoding** [withastro/astro#10950]
### Astro Info

```block
Astro                    v4.7.1
Node                     v20.10.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
                         @astrojs/partytown
```

### Describe the Bug

![image](https://github.com/withastro/astro/assets/70770072/85360feb-b6b8-44e6-9a5b-6c6ec69ae013)

### What's the expected result?

```html
<script data-astro-rerun type='module'>
  import screenfull from "screenfull";
</script>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-a1zlce?file=src%2Fpages%2Findex.astro,package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Trombach** [comment]
That's expected behaviour. According to the [docs](https://docs.astro.build/en/guides/view-transitions/#data-astro-rerun) `data-astro-rerun` adds `is:inline` explicitly. This actually happens when you add any attribute to a `script` tag that is not `src`. `is:inline` [prevents the script from being processed, optimized or bundled](https://docs.astro.build/en/reference/directives-reference/#isinline), so you can't use a plain import statement.

**Comment by martrapp** [comment]
Hello @TheElegantCoding, I will close this issue as it was perfectly answered by @Trombach.   
Depending on you build environment, you might be able to use `import screenfull from "./node_modules/screenfull";`

**Comment by TheElegantCoding** [comment]
Hello @martrapp thanks, yes `./node_modules` works, but only in dev mode, not in production, it give me 404 when the site is deployed, what should i do to make it work ?
![image](https://github.com/withastro/astro/assets/70770072/41a43df8-63c9-45fb-a4db-84325c487567)

**Comment by martrapp** [comment]
Are you using view transitions?

**Comment by TheElegantCoding** [comment]
yes, that's why i need `data-astro-rerun` otherwise the script only work the first time

**Comment by Trombach** [comment]
@TheElegantCoding In my opinion it might be best to rethink your approach to this. It might be better to execute your code based on one of the [lifecycle events](https://docs.astro.build/en/guides/view-transitions/#lifecycle-events) Astro provides. For example

```astro
<script>
  import screenfull from "screenfull";

  function init() {
    /* use screenfull library */
  }

  // run on initial page load
  init();

  // rerun in every "after-swap" event
  document.addEventListener("astro:after-swap", init);
</script>
```
