### ISSUE TITLE
getRelativeLocaleUrl dont work with internal "#" link 

### ISSUE THREAD

**Issue by TheElegantCoding** [withastro/astro#10951]
### Astro Info

```block
Astro                    v4.7.1
Node                     v20.10.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
                         @astrojs/partytown
```

### Describe the Bug

with `trailingSlash: 'never'`, getRelativeLocaleUrl, redirect to another page instead of keep the actual page, also if is a redirect to another and make scroll, go to 404

to reproduce in stacktrace go to /es and then click the link app

### What's the expected result?

redirect to "/es#about"

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ppkgse?file=src%2Fpages%2Findex.astro,src%2Futil%2Flocale.ts,src%2Fpages%2Fen%2Findex.astro,src%2Fpages%2Fes%2Findex.astro,astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
`getRelativeLocaleUrl` takes a pathname, not arbitrary parts of a URL. You can achieve what you want with this:

```astro
{getRelativeLocaleUrl(language)+'#app'}
```
