### ISSUE TITLE
.astro created with --outDir

### ISSUE THREAD

**Issue by cdtut** [withastro/astro#10969]
### Astro Info

```block
Astro                    v4.7.1
```

### Describe the Bug

When `pnpm run build` fails the effect is different with `--outDir astrobuild`. It creates `.astro` under project with temporary files. If error in index.astro is fixed and run command again then `.astro` is deleted. But it is not created without `--outDir`.

### What's the expected result?

`--outDir` should build temporary files at same place like `pnpm run build` and not create `.astro`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-iqja2n

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
`--outDir` is where your built site is written to. It does not control `.astro` which is not currently configurable.

**Comment by cdtut** [comment]
@matthewp Why `.astro` is only used with `--outDir`?
