### ISSUE TITLE
global SCSS mixin can't be used

### ISSUE THREAD

**Issue by Grohotun** [withastro/astro#10961]
### Astro Info

```block
Astro                    v4.7.1
Node                     v18.20.2
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

### Describe the Bug

1)create component for global styles
```html
<style is:global lang="scss">
  body{
    margin: 0;
    word-spacing: normal;
    font-family: 'Gilroy';
    font-weight: 500;
  }
  
   @mixin h11{
    font-size: 44px;
    line-height: 48px;
    letter-spacing: -0.03em;
  }
  
</style>
```

2)include this component on Astro page
3)add styles into page
```html
<style lang="scss">
#example{
@include h11;
}
</style>
```

Got error
```bash
[sass] Undefined mixin.
  ╷
3 │ @include h11;
  │ ^^^^^^^^^^^^
  ╵
  src/pages/index.astro 3:1  root stylesheet
```
### What's the expected result?

element with **example** will have styles from mixin **h11**

may be related to [#2032 ](https://github.com/withastro/astro/issues/2032)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-pyg5gf
https://withastroastropyg5gf-n0hc--4321--34455753.local-credentialless.webcontainer.io/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You need to configure [`vite.css.preprocessorOptions['.scss'].additionalData`](https://vitejs.dev/config/shared-options.html#css-preprocessoroptions-extension-additionaldata) to properly reference `h11`, as each SCSS code is compiled itself and doesn't have information from other files.
