### ISSUE TITLE
Improper styles usage (nested?)

### ISSUE THREAD

**Issue by Grohotun** [withastro/astro#10968]
### Astro Info

```block
Astro                    v4.7.1
Node                     v18.20.2
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

### Describe the Bug

If image is loaded by external component you can't simply apply scoped styles, only global styles are working (or add styles directly into loaded component)

### What's the expected result?

styles to be applied from main.astro

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/Grohotun/withastro-astro-8gguzy?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You need to pass along the `data-astro-cid-*` prop in order for the scoped styles to work on the element. If you're using `scopeStyleStrategy: 'class'`, you need to rename `cl` as `class` for the scoped class to properly apply to the `class`.
