### ISSUE TITLE
Handle multiple slashes in url

### ISSUE THREAD

**Issue by DarthTicius** [withastro/astro#10989]
### Astro Info

```block
Astro                    v4.1.2
Node                     v20.12.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/preact
```

### Describe the Bug

We want to redirect user if url contains multiple slashes
`https://www.example.com/this//is/my/////directory` to `https://www.example.com/this/is/my/directory`

But on the middleware side we do not get raw url : `https://www.example.com/this//is/my/////directory`
instead we are getting already sanitized version `https://www.example.com/this/is/my/directory.`

### What's the expected result?

Expecting the url in client to be sanitized and not remaining `https://www.example.com/this//is/my/////directory`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tdbrwm?file=src%2Fmiddleware.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I believe this is a known limitation because we can't translate 
`this//is/my/////directory` into the file system.

**Comment by cauboy** [comment]
Is there no way to get the original request with raw initial URL somewhere in Astro? 

Would that mean that the only way to accomplish that is to put a reverse-proxy in front of Astro where the URL gets sanitized?

One reason for sanitizing URLs is for SEO. Google might think of '/path///other' and /path/other' as two separate things potentially leading to duplicate content.

**Comment by matthewp** [comment]
This is SSR so I wouldn't expect it to have that constraint. Did you debug to see where it gets stripped away?

**Comment by matthewp** [comment]
Looks like this was caused by this: https://github.com/withastro/astro/pull/7935

In retrospect I think this PR was a mistake. @DarthTicius would you be interested in submitting a PR to fix?
