### ISSUE TITLE
`@astrojs/react` is broken on `npm install` command

### ISSUE THREAD

**Issue by mika-f** [withastro/astro#10984]
### Astro Info

```block
Astro                    v4.8.0
Node                     v18.19.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Failed to install `@astrojs/react` of latest release.

```bash
npm run astro add react

> green-galaxy@0.0.1 astro
> astro add react

✔ Resolving packages...

  Astro will run the following command:
  If you skip this step, you can always run it yourself later

 ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
 │ npm install @astrojs/react@^3.3.3 @types/react@^null @types/react-dom@^null react@^18.3.1 react-dom@^18.3.1  │
 ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

√ Continue? ... yes
✖ Installing dependencies...

 Command failed with exit code 1: npm install @astrojs/react@^3.3.3 @types/react@^null @types/react-dom@^null react@^18.3.1 react-dom@^18.3.1
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^null" of package "@types/react@^null": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in: C:\Users\REDACTED\AppData\Local\npm-cache\_logs\2024-05-09T11_58_24_625Z-debug-0.log

Astro could not update your astro.config.js file safely.
Reason: Unable to install dependencies

You will need to add these integration(s) manually.
Documentation: https://docs.astro.build/en/guides/integrations-guide/
  Stack trace:
    at add (file:///C:/a/green-galaxy/node_modules/astro/dist/cli/add/index.js:218:31)
    at async runCommand (file:///C:/a/green-galaxy/node_modules/astro/dist/cli/index.js:117:7)
```

### What's the expected result?

Successfully install it without any errors.

### Link to Minimal Reproducible Example

https://github.com/mika-sandbox/astro-add-react-broken

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Reikon95** [comment]
Also just started getting this error whenever adding react.

**Comment by emish89** [comment]
> Likely due to
> 
> https://github.com/withastro/astro/blob/770b9f06c3d67f89de527d8b3a842555e596c01f/packages/integrations/react/package.json#L62-L64

Yeah, I confirm that removing these 2 `npm:types-` everything works again.

**Comment by emish89** [comment]
I created this https://github.com/withastro/astro/pull/10986/files

**Comment by Reikon95** [comment]
<img width="1120" alt="Screenshot 2024-05-09 at 15 35 01" src="https://github.com/withastro/astro/assets/38852603/6455c417-320d-4616-a6d1-a1f40b308242">

Anyone else still getting this after the merge?

**Comment by Reikon95** [comment]
<img width="912" alt="Screenshot 2024-05-09 at 15 36 10" src="https://github.com/withastro/astro/assets/38852603/1efad16b-ab7a-4daa-af8c-ea4122172f92">

This seems to have merged but I'm still getting this, even after updating astro

**Comment by emish89** [comment]
> <img alt="Screenshot 2024-05-09 at 15 36 10" width="912" src="https://private-user-images.githubusercontent.com/38852603/329281406-1efad16b-ab7a-4daa-af8c-ea4122172f92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjY3ODIsIm5iZiI6MTcxNTI2NjQ4MiwicGF0aCI6Ii8zODg1MjYwMy8zMjkyODE0MDYtMWVmYWQxNmItYWI3YS00ZGFhLWFmOGMtZWE0MTIyMTcyZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE0NTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZWY0Mjc3YjNmYTU0N2ExOTExZjY3NTRjOWY2OGMxNTg5NDFiYTM1MzczZTFiNmI3MzI3NGUxNWFkZDA0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uiCseHoPGRSQ1RJuuRFW2to7n2xtK8KiTOKln4HDI3g">
> This seems to have merged but I'm still getting this, even after updating astro

I think this is a different problem and, maybe, is better to manage in a different issue

**Comment by mika-f** [comment]
I confirmed that this problem has been resolved. Thank you for your quick response & release!
