### ISSUE TITLE
"Port is already in use" error on CI when jobs ran in parallel

### ISSUE THREAD

**Issue by tom751** [withastro/astro#11003]
### Astro Info

```block
Astro                    v4.6.3
Node                     v18.20.2
System                   Linux (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### Describe the Bug

I have a CI pipeline on GitLab where jobs can be ran in parallel (e.g a CI runner can be running jobs for multiple merge requests). This causes Vite to throw the following error if multiple `astro` commands are run at the same time, e.g. `astro check` or `astro sync`.

```
[ERROR] [vite] WebSocket server error: Port is already in use
```

This causes the pipelines to become flaky as Astro is creating Vite dev servers which are all competing for the same default port 24678. Changing the port in the astro config makes no difference.

I did some digging and the culprit seems to be in 2 places where we create a vite server, and set `hmr: false`:
- https://github.com/withastro/astro/blob/main/packages/astro/src/core/config/vite-load.ts#L10
- https://github.com/withastro/astro/blob/main/packages/astro/src/core/sync/index.ts#L121

From this Vite issue https://github.com/vitejs/vite/issues/13994, it sounds like setting `hmr` to false doesn't disable the WebSocket which is why I'm seeing the "Port is already in use" error.

I was able to get around this with patch-package and instead of using `hmr: false` in those places above, I set an object with a random port number, but obviously this isn't ideal. I was able to test this locally by running two commands simultaneously `npm run astro check & npm run astro check`

Is there a better way to deal with this? Apologies if this is more of a Vite issue than an Astro one!

### What's the expected result?

I should be able to run multiple jobs in parallel on CI that use `astro` CLI commands.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-g3vfoh?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by millette** [comment]
I'm getting that too recently, on localhost (dev). It happens with node and db integrations, but I wasn't able to track it down to any integration yet. Other projects don't have this problem. It says "vite error" but everything seems to work anyway.

**Comment by matthewp** [comment]
Would love a PR for this.

**Comment by bluwy** [comment]
https://github.com/vitejs/vite/pull/16219 could help with this once it lands.

**Comment by ResearchScientist** [comment]
I'm getting a similar build error here on github codespaces `[vite] Websocket server error: Port is already in use`.
CI/CD unable to deploy to Netlify.

**Comment by millette** [comment]
I noticed something else when I build twice in a row (no changes):

```
building client (vite)
12:38:41 [ERROR] [vite] WebSocket server error: Port is already in use
12:38:41 [vite] Re-optimizing dependencies because vite config has changed
12:38:41 [vite] ✓ 19 modules transformed.
```

`Re-optimizing dependencies because vite config has changed` but no, it hasn't changed.

Only one of my project is showing the websocket error although it seems to build properly in any case. I removed `.astro/`, `node_modules/` and `dist/` but the error remains.

**Comment by geshov** [comment]
I also got this error right after adding integration @astrojs/db to project. After removing the integration @astrojs/db, the error disappeared. 

For information - the project is empty, one test page and one integration @astrojs/react:

 "@astrojs/react": "^3.4.0",
 "@types/react": "^18.3.3",
 "@types/react-dom": "^18.3.0",
 "astro": "^4.9.2",
 "react": "^18.3.1",
 "react-dom": "^18.3.1"

**Comment by 0niSec** [comment]
I'm also receiving this error with @astrojs/db. Once I added it and tried merging dev to main, my build failed on Netlify.

https://i.imgur.com/lIFuwRM.png

**Comment by oscarnilsson98** [comment]
Same here, any solutions in sight or workarounds?

**Comment by oscarnilsson98** [comment]
So there is a bug with the current version of astro db, downgrading to 10.7 fixes it.

I haven't had time to look at what is causing it but should be a good place to start.

**Comment by millette** [comment]
I agree with @oscarnilsson98 , problem is between 0.10.7 and 0.11.0. I put on my detective hat but to no avail. Perhaps <https://github.com/vitejs/vite/pull/16219> will help to fix this.

One thing I noticed is `"astro:build:setup"` gets called twice.

**Comment by latinrev** [comment]
I'm not sure what the difference its between logs but I was able to get rid of at least one error by
```
const YourPlugin= () => {
  return {
    name: "YourPlugin",
    hooks: {
      "astro:config:setup": ({ updateConfig }) => {
        updateConfig({
          vite: {
           // Changing the port for me at any point during build step has not done anything
            server: { ws: false }, // this line gets rid of [ERROR] [vite] WebSocket server error: Port is already in use
          },
        });
      },
    },
  };
};
```

Before:
> WebSocket server error: Port is already in use
> 01:39:33 [ERROR] [vite] WebSocket server error: Port is already in use

After:
> WebSocket server error: Port is already in use

**Comment by adopted3** [comment]
These otherwise inconsequential errors have disappeared for me at astro v14.

**Comment by jgondev** [comment]
Still there for me in 4.14

![image](https://github.com/user-attachments/assets/5f6fad98-846b-477a-8e68-66992f5df962)

**Comment by NickHodges** [comment]
I'm getting this as well in 4.14.2

` ``
building client (vite) 
06:13:25 [ERROR] [vite] WebSocket server error: Port is already in use
06:13:25 [vite] Re-optimizing dependencies because vite config has changed
06:13:27 [vite] ✓ 42 modules transformed.
06:13:28 [vite] dist/client/_astro/NewsletterSignup.Di8ayWiw.js    2.17 kB │ gzip:  1.16 kB
06:13:28 [vite] dist/client/_astro/index.DhYZZe0J.js               6.72 kB │ gzip:  2.68 kB
06:13:28 [vite] dist/client/_astro/hoisted.D-2wbxhY.js            14.17 kB │ gzip:  4.84 kB
06:13:28 [vite] dist/client/_astro/client.BIGLHmRd.js            135.60 kB │ gzip: 43.81 kB
06:13:28 [vite] ✓ built in 3.12s
```

**Comment by millette** [comment]
@adopted3 @jgondev @NickHodges Could you share your package.json and astro.config files?

**Comment by adopted3** [comment]
package.json
```
{
  "name": "alds-astro",
  "type": "module",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/alpinejs": "^0.4.0",
    "@astrojs/check": "^0.9.2",
    "@astrojs/netlify": "^5.5.1",
    "@astrojs/react": "^3.6.2",
    "@astrojs/sitemap": "^3.1.6",
    "@astrojs/tailwind": "^5.1.0",
    "@iconify-json/fluent-emoji-high-contrast": "^1.1.15",
    "@iconify-json/simple-icons": "^1.1.107",
    "@portabletext/to-html": "^2.0.13",
    "@portabletext/types": "^2.0.13",
    "@sanity/astro": "^3.1.4",
    "@sanity/client": "^6.21.0",
    "@sanity/types": "^3.50.0",
    "@types/alpinejs": "^3.13.10",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "alpinejs": "^3.14.1",
    "astro": "^4.14.2",
    "astro-navbar": "^2.3.2",
    "glob": "^11.0.0",
    "netlify-cli": "^17.34.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-google-reviews": "^1.1.1",
    "sanity": "^3.50.0",
    "tailwindcss": "^3.4.3",
    "typescript": "^5.4.3"
  },
  "devDependencies": {
    "@iconify/tailwind": "^1.1.1",
    "accessible-astro-components": "^2.3.6"
  }
}
```

astro.config.mjs
```
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import sitemap from "@astrojs/sitemap";
import netlify from '@astrojs/netlify';
// import node from "@astrojs/node";

import sanity from "@sanity/astro";
import alpinejs from "@astrojs/alpinejs";
import react from "@astrojs/react";

// https://astro.build/config
export default defineConfig({
  trailingSlash: 'ignore',
  // prefetch: true,
  site: '...',
  integrations: [tailwind(), alpinejs(), sitemap({
    ...
  }), sanity({
    projectId: '...',
    dataset: 'staging',
    useCdn: true,
    apiVersion: "2024-07-13",
  }), react()],
  redirects: {
    ...
  },
  output: 'hybrid',
  base: '.',
  adapter: netlify()
});
```

**Comment by NickHodges** [comment]
Sure!

`package.json`:

```
{
  "name": "techbash2024",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && ASTRO_DATABASE_FILE=./src/data/TechBash2024.db   astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.9.2",
    "@astrojs/db": "^0.13.1",
    "@astrojs/node": "^8.3.3",
    "@astrojs/react": "^3.6.2",
    "@astrojs/sitemap": "^3.1.6",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "astro": "^4.14.2",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "typescript": "^5.5.4"
  }
}

```

and `astro.config.mjs`:

```
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import react from '@astrojs/react';
import node from "@astrojs/node";

import db from "@astrojs/db";

// https://astro.build/config
export default defineConfig({
  output: 'hybrid',
  site: 'http://localhost:4321',
  integrations: [sitemap(), db(), react()],
  experimental: {
    actions: true,
    serverIslands: true,
  },
  adapter: node({
    mode: "standalone"
  })
});
```
