### ISSUE TITLE
Styled Component is not applied when navigating with View Transition

### ISSUE THREAD

**Issue by nojaf** [withastro/astro#11000]
### Astro Info

```block
Astro                    v4.8.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

A styled component (via React client:only) will only render correctly if it is on the initial page load.
When navigating via a View Transition the style will not be applied.

### What's the expected result?

The style is always applied after each page transition.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wut9d2?file=src%2Fpages%2Fanother.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @nojaf, it looks like `@emotion/styled` is not working with `<ViewTransitions />`.

Obviously it works with full page loads but the lib's internal state will not automatically update on view transitions. I skimmed through `@emotion/*` but didn't find an obvious way to update script state after view transitions.

**Comment by matthewp** [comment]
This seems to do the job: https://stackblitz.com/edit/github-wut9d2-fnekpm?file=src%2Fcomponents%2FButton.jsx,src%2Flayouts%2FLayout.astro,src%2Fpages%2Fanother.astro

**Comment by nojaf** [comment]
Thanks a bunch for this solution!

**Comment by walmartwarlord** [comment]
Hi @matthewp, do you know of any way to do this when you dont have access to `withEmotionCache` and `cache` property in a project? Now that we can do [custom swap functions](https://docs.astro.build/en/guides/view-transitions/#building-a-custom-swap-function), Im pretty sure we only need to modify the `swapHeadElements` there but not sure how to go from there
