### ISSUE TITLE
Remote URLs throw an error using the `image()` content collection validator

### ISSUE THREAD

**Issue by bholmesdev** [withastro/astro#11010]
### Astro Info

```block
Astro                    v4.8.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I expected the `image()` validator for content collections to work on remote images. I set up the `image.domains` property in my astro config as instructed, and it _did_ work when using the `<Image />` component directly. However, I get the following error using the content collection validator:

> blog → example.md frontmatter does not match collection schema.
> Image https://dev-to-uploads.s3.amazonaws.com/i/8lu1lb4qy2l5kr1jq2nt.png does not exist. Is the path correct?

### What's the expected result?

`image()` should respect remote images like the `Image` component.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-csonwy?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
The image() schema is equivalent to an image import, not to the Image component. This is intentional, since depending on the image service, it's ambiguous if a string is supposed to be a local path, a remote path, a key for a CDN etc.
