### ISSUE TITLE
Check latest astro version fail cause astro render error page at first time visit.

### ISSUE THREAD

**Issue by QingXia-Ela** [withastro/astro#11012]
### Astro Info

```block
Astro                    v4.8.2
Node                     v18.18.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Astro cannot catch [fetchLatestAstroVersion](https://github.com/withastro/astro/blob/main/packages/astro/src/core/dev/dev.ts#L51) error when fetch failed, and it will create a error layout when first time fetch the page.

This bug may only appear in some country that cannot connect to npmjs.org normally.
It cannot reproduction in the stackblitz. I only can put some screenshots to show it.

The error will cause my test fail when I fetch the page first time.

Screenshots:
![图片](https://github.com/withastro/astro/assets/86217807/9dbb08f8-30c3-4e4d-8ca8-0a1de576d9b2)
![图片](https://github.com/withastro/astro/assets/86217807/1d564073-b73a-4c79-b191-47dd9b1479b2)

Stackblitz reproduction can follow this:
- Modify `node_modules/astro/dist/cli/install-package.js` and let `fetchPackageVersions` always return Error.
- Modify `node_modules/astro/dist/core/dev/dev.js#L31` and made shouldCheck to `true`.

![图片](https://github.com/withastro/astro/assets/86217807/08aad978-1c95-4cdb-bbdd-719c4c47f663)

### What's the expected result?

Expect cli do nothing, keep server run normally.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-82f59z

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bitsnaps** [comment]
I'm not sure if this issue is related to that one, but I'm still getting `fetch failed` with `astrodb` after following the steps in docs, here is a reproducible demo on [stackblitz](https://stackblitz.com/~/github.com/bitsnaps/astro-db-demo), here is the log for creating a new project:
```bash
❯ astro db link
✔ Link "~/bitsnaps/astro-db-demo" with Astro Studio? … yes
✔ Link with an existing project in Astro Studio? … no
✔ Create a new project in Astro Studio? … yes
fetch failed
```
Try to link an existing project:
```bash
❯ astro db link
✔ Link "~/bitsnaps/astro-db-demo" with Astro Studio? … yes
✔ Link with an existing project in Astro Studio? … yes
fetch failed
```
