### ISSUE TITLE
Module '"astro:actions"' has no exported member 'defineAction'

### ISSUE THREAD

**Issue by ahmad-ali14** [withastro/astro#11018]
### Astro Info

```block
Astro                    v4.8.2
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

Module '"astro:actions"' has no exported member 'defineAction'

### What's the expected result?

I expect both `z` and `defineActions` to be exported from `astro:actions`. 

I temporarily added this line to `.astro/actions.d.ts` and it seems to fix the issue

```ts
declare module 'astro:actions' {
  type Actions =
    typeof import('/Users/...project/src/actions')['server'];

  export const actions: Actions;

  // this line was added manually
  export { defineAction, z } from 'astro/dist/actions/runtime/virtual/server'; 
}
```

### Link to Minimal Reproducible Example

No need for this

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ahmad-ali14** [comment]
The `check` command is overwriting that file; so it is always failing.

**Comment by ematipico** [comment]
That's a code generated file, so you'd have to have the dev server running. Maybe you weren't running the dev server?

**Comment by matthewp** [comment]
A repro is always needed, please don't skip this section, thank you.

**Comment by ahmad-ali14** [comment]
I have created this minimal project: https://stackblitz.com/edit/github-smajyk?file=src%2Factions%2Findex.ts

It seems to be working; there must be some tsconfig issue on my end. Cause runtime is okay; just the types are confused.

**Comment by andrioid** [comment]
I changed module resolution from "node" to "Bundler" in tsconfig and the error went away.

**Comment by kasvith** [comment]
> I changed module resolution from "node" to "Bundler" in tsconfig and the error went away.

thanks, this resolved the issue

**Comment by TnTSpace** [comment]
My error was because the actions folder wasn't directly under my src folder, instead I put it in my libs folder

A - This is what is expected for the actions types to be generated: /src/actions/index.ts
B - This was what I did: /src/lib/actions/index.ts

So I had to move it from B to A and it worked
