### ISSUE TITLE
Run [object Promise] ... to update

### ISSUE THREAD

**Issue by zaaakher** [withastro/astro#11024]
### Astro Info

```block
Astro                    v4.7.0
Node                     v18.19.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

This is extremely minor. I think astro couldn't detect something and said `[object Promise]` instead of the actual message 

![image](https://github.com/withastro/astro/assets/46135573/273202d3-604f-4424-91e5-ad440f3a3a25)

### What's the expected result?

It should say `Run npx @astrojs/upgrade to update` or something around those lines.

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by zaaakher** [comment]
Upon further investigation I think it's coming from https://github.com/withastro/astro/blob/18b78ec881f35e74ba21b45abefe32b8beb0e8b3/packages/astro/src/cli/install-package.ts

**Comment by zaaakher** [comment]
For more details:
- I'm using `pnpm`
- I ran the command `pnpm dev:landing` from the root of my monorepo
Here are the scripts in the root `package.json` 👇
![image](https://github.com/withastro/astro/assets/46135573/a65fd49b-a82a-4d55-a56c-f0e30c433e12)

- My mono repo structure is 
```
- package.json (in the root)
- sites
    - landing (the astro app)
- backends
    - content (a strapi app)
```

**Comment by zaaakher** [comment]
@matthewp Sure no problem, but what exactly is the cause of the problem? and the possible solution?

**Comment by bluwy** [comment]
Sorry. This is fixed in https://github.com/withastro/astro/pull/10991

**Comment by zaaakher** [comment]
Ah, I was looking at the code and it already handles the promise using `await`, what a head-scratcher. Thanks @bluwy 

Ironically I just have to actually run the upgrade command in order for this issue to not appear again 😄
