### ISSUE TITLE
Partytown scripts break ViewTransition 

### ISSUE THREAD

**Issue by dsegovia90** [withastro/astro#11033]
### Astro Info

```block
Astro                    v4.8.3
Node                     v18.19.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/partytown
```

### Describe the Bug

Scripts with partytown break when transitioning between routes with ViewTransitions.

Console error (on multiple browsers):
```
Uncaught SyntaxError: redeclaration of const t
    <anonymous> index2 line 102 > injectedScript:1
    runScripts router.js:102
    transition router.js:335
    transition router.js:334
    navigate router.js:366
    <anonymous> ViewTransitions.astro:97
    EventListener.handleEvent* ViewTransitions.astro:59
[index2 line 102 > injectedScript:1:1](http://localhost:4321/index2%20line%20102%20%3E%20injectedScript)
```

This can be shown in the Minimal Reproducible Example attached.

### What's the expected result?

Partytown webworker should not break when transitioning routes with ViewTransition

### Link to Minimal Reproducible Example

https://astro-viewtransition-partytown-bug.vercel.app/

### Code

Repo: https://github.com/dsegovia90/astro-viewtransition-partytown-bug
Partytown script: https://github.com/dsegovia90/astro-viewtransition-partytown-bug/blob/57ac9a6a624284e57bd4163feb553d563a7772dd/src/layouts/Layout.astro#L22C3-L27C12

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by V3RON** [comment]
The Partytown snippet is supposed to be loaded only once, but when the View Transitions API gets activated, the <script> element containing this snippet is recreated on every transition.

https://github.com/withastro/astro/blob/6f948903fcd33c660641203507240a8b5e99e7ac/packages/integrations/partytown/src/index.ts#L28-L38

I decided to comment out the line adding SELF_DESTRUCT_ON_VIEW_TRANSITION to the script and see what happens. The outcome is:
a) No error while transitioning between pages.
b) Partytown scripts are not executed after the transition.

That's probably expected. We should let Partytown know there may be new scripts added by dispatching new CustomEvent('ptupdate'). I did so, and nothing happened.

Under certain conditions, Partytown may need an <iframe> element to be present on the page. It's true for my local environment, and when a view transition happens, this <iframe> is removed from the DOM. 

We should persist it somehow 🤔

**Comment by matthewp** [comment]
@V3RON thanks for doing the research! Would you mind sending a PR?

**Comment by dsegovia90** [comment]
Thank you @V3RON & @matthewp. Let me know if you need some help testing, or setting up another Minimal Reproducible Example.

**Comment by V3RON** [comment]
@matthewp
Just to confirm - it's expected for `<script type="text/partytown">` scripts to be restarted when transition happens, right?

If so, then [this commit](https://github.com/V3RON/astro/commit/9c159238612e0d571edee9b03940ec8492ebdda9) should be all we need. It moves the `<iframe>` element created by Partytown from the old document to the new one on transition.

Is there any edge-case I should be aware of? 🤔

**Comment by dsegovia90** [comment]
thanks @V3RON! tested this commit in my local machine, and can confirm that partytown is no longer crashing. I can also see that the service worker is re-initialized on route change. I'm not sure if that is the intended behavior for partytown.

the only thing I can think of is comparing it to nuxtjs or nextjs, would that be helpful?

**Comment by matthewp** [comment]
Sounds perfect to me.

**Comment by V3RON** [comment]
> I'm not sure if that is the intended behavior for partytown.

It's not, but there is no way to move `<iframe>` and maintain its state - it will always reload. 
I'll open a PR then 👌
