### ISSUE TITLE
Bug with resolving imports when using viteServer.ssrLoadModule in astro adapter

### ISSUE THREAD

**Issue by patheticGeek** [withastro/astro#11048]
### Astro Info

```block
Astro                    v4.8.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @patheticGeek/astro-express
Integrations             none
```

### Describe the Bug

I am migrating from nextjs to astro at work and need to run astro server under a express server as we have integrations on express level want to be using them.

I created a express adapter based on https://github.com/matthewp/astro-fastify but both of these have the same issue which is in the vite plugin's `configureServer` function. we get the vite server and have to load our server file with `server.ssrLoadModule`.

This `server.ssrLoadModule` function is not resolving relative imports correctly in astro projects, it works fine when used in a vanilla vite project ([Example](https://stackblitz.com/edit/vitejs-vite-owzm7e?file=src%2Fserver.js)).

Both projects have the same file structure for server folder
```
├── package.json
├── server
│   ├── index.js
│   └── utils
│       └── index.js
├── astro-express
│   ├── index.js // when using astro adapter, ssrloadmodule is called in this file
│   ├── response-iterator.js
│   └── server.js
└── src
    └── server.js // when using vite, ssrloadmodule is called in this file
```

The following error is thrown when trying to import `./utils/index.js` in `server/index.js`

```
Failed to load url ./utils (resolved id: ./utils). Does the file exist?
  Stack trace:
    at loadAndTransform (/home/projects/withastro-astro-kfswv5/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53933:21)

```

### Related
matthewp/astro-fastify#21

### What's the expected result?

The relative imports should work as expected

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-kfswv5?file=astro-express%2Findex.js

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
The bug is that as you're calling `server.ssrLoadModule` in `configureServer`, Vite's internal plugin that converts the `./utils` to something valid for itself, e.g. `/server/utils/index.js`, is not working because of [this line](https://github.com/vitejs/vite/blob/c3b3d3c617ba729814c599e14145499aeac4c9d3/packages/vite/src/node/plugins/importAnalysis.ts#L207-L216) where `transform` is should be converting the path, but its `configureServer` hook has not reached yet.

I'm not really sure how we can fix this on the Vite side, perhaps it's not safe to call `ssrLoadModule` before the server is finished configuring? You may need to workaround this by delay calling `ssrLoadModule`, e.g. returning a function from `configureServer`. Or maybe not rely on `ssrLoadModule` for importing the code.

**Comment by patheticGeek** [comment]
Also a question is, why does it happen only with astro and not in a vite project
and i have also found out that no aliases are being applied when using this function, some of the config is being ignored i think

**Comment by bluwy** [comment]
> Is there any place for discussion around better support for a dev server in adapter?

For this specific case, I don't think there's a discussion about this yet. For adapter influencing dev in general, there's the Vite 6 Environment API, but it wouldn't help this case with a custom express/fastify server. I've not seen the pattern you showed a lot in the wild, and it feels a bit hacky to me though.

> Also a question is, why does it happen only with astro and not in a vite project

It also happens with a Vite project if you do the `ssrLoadModule` in a `configureServer` hook. Vite also has a specific [middlewareMode](https://vitejs.dev/guide/ssr.html#setting-up-the-dev-server) to prevent creating two http servers.

**Comment by patheticGeek** [comment]
> It also happens with a Vite project if you do the ssrLoadModule in a configureServer hook. Vite also has a specific [middlewareMode](https://vitejs.dev/guide/ssr.html#setting-up-the-dev-server) to prevent creating two http servers.

Ah, understood what I was missing and why this worked in the vite example I gave above.

> I've not seen the pattern you showed a lot in the wild, and it feels a bit hacky to me though.

I admit this is a rare use case, but super important when you want APIs/business logic separated from your rendering framework. This has helped that we have APIs fully separated from next and can move to astro without rethinking our that whole layer.
Also, just super useful in general to have the same adapter serving things in dev & prod, not having different behaviours there.

Anyway, thanks for the help!
