### ISSUE TITLE
Inspect Popup exceeds window

### ISSUE THREAD

**Issue by zaaakher** [withastro/astro#11044]
### Astro Info

```block
Astro                    v4.8.3
Node                     v18.19.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
                         @astrojs/partytown
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

When I try the inspect feature the popup exceeds the current window. I'm not sure if this happens because my site is RTL or not
(notice the scrollbar at the bottom is due to the popup)
![image](https://github.com/withastro/astro/assets/46135573/75c6799b-9f11-4ef5-bf8e-ea4199e9bcc4)

### What's the expected result?

It should stay within the window and pop to the left/right depending on conditional awareness of it's position

![image](https://github.com/withastro/astro/assets/46135573/ee07fa74-7f7e-489f-9d98-9cd061e42644)

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by zaaakher** [comment]
My apologies @matthewp, here you go https://stackblitz.com/edit/github-5k1mkz?file=src%2Fpages%2Findex.astro

Here's a quick gif showing it:
![astro-rtl-inspector-popup](https://github.com/withastro/astro/assets/46135573/d8a29a96-cfb8-4a0f-95ca-b743472a4103)

**Comment by V3RON** [comment]
@bluwy There is a check for right-side overflow, but not for left-side overflow. I'll open a PR adding one shortly.
