### ISSUE TITLE
Slot passthrough breaks default slot content

### ISSUE THREAD

**Issue by innermatrix** [withastro/astro#11047]
### Astro Info

```block
Astro                    v4.8.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

If component A uses slot passthrough to a child component B, and component B uses slot default content, then default content is incorrectly not shown when empty slot is passed through A.

A:

```
---
  import B from './B.astro';
---
<div>
<div>A start</div>
<B>
<slot name="s" slot="s" />
</B>
<div>A end</div>
</div>
```

B:

```
<div>
<div>B start</div>
<slot name="s">
<div>Default content</div>
</slot>
<div>B end</div>
</div>
```

A is rendered as 

```
<div>
<div>A start</div>
<div>
<div>B start</div>
<div>B end</div>
</div>
<div>A end</div>
</div>
```

### What's the expected result?

A should be rendered as

```
<div>
<div>A start</div>
<div>
<div>B start</div>
<div>Default content</div>
<div>B end</div>
</div>
<div>A end</div>
</div>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mvb5lj

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ArmandPhilippot** [comment]
It is a known design limitation. See [natemoo-re answer](https://github.com/withastro/astro/issues/9654#issuecomment-1885362051) in #9654.

However, there is a workaround. You need to add an extra check before passing the slot. So, in component `A`:

```astro
---
  import B from './B.astro';
---
<div>
<div>A start</div>
<B>
<slot name="s" slot={Astro.slots.has("s") ? "s" : ""} />
</B>
<div>A end</div>
</div>
```

(You can also write `Astro.slots.has("s") && "s"`, but with the strictest preset for Typescript it might complain about this syntax...)

**Comment by matthewp** [comment]
Default content is rendered when a slot is not provided. Not when it is empty. Since A passes the slot, it's used, even if empty. If you want to check for emptyness use `slots.render()`: https://docs.astro.build/en/reference/api-reference/#astroslotsrender

I'll bring this up to docs as something worth adding to the docs as its a common pitfall.

**Comment by innermatrix** [comment]
@matthewp Thanks! I've seen other people discussing `slots.render` as a solution for this problem and also for the issue of false positives in `slots.has`, and I've also seen some noise about performance concerns about `slots.render`. Can you tell me whether code that does `slots.render("foo")` and then (depending on the outcome) maybe uses `<slot name="foo"/>` will end up paying the compute cost of the render twice, or if it's cached and the cost of repeat renders is negligible? (In the latter case, I am probably going to put the `render` in the frontmatter and then use `html` to directly include its output instead of rerendering.)
