### ISSUE TITLE
Experimental Rewrites - Including search params not matching index route for rewrites

### ISSUE THREAD

**Issue by SamHarrison-dev** [withastro/astro#11061]
### Astro Info

```block
Astro version: ^4.0.8 (application)
Astro version: ^4.8.0 (integration)
```

### Describe the Bug

I am using the experimental rewrite feature added in Astro 4.8.

Inside of my integration middleware (which runs before any application middleware) I am rewriting requests to include the locale to match a dynamic [locale] route where all additional pages and routes are nested

However I am running into an issue with keeping existing params from the request when creating a new signature only for the index page.

_example for request to /_

const url = `/${locale}${url.pathname}${url.search}` e.g => /en-gb/?foo=bar
const page = await next(url)
console.log(page.status)
return page

_Below are some further example routes:_

request: `/` **200**
request: `/?foo=bar` **404**
request: `/c/all/` **200**
request: `/c/all/?foo=bar` **200**

I have added a catch all route inside of the [locale] route as `[...all].astro` to debug this further. When query params are added on the index route the rewrite request falls inside of this catch all route, however when no query params are added it matches the `index.astro` route. The structure of the /c/ route is /c/[...slug]

I am able to reproduce the issue on local development. Adding the following resolves the issue locally but does not work using the cloudflare adapter, instead this 404's the index route regardless of query params present or not but the /c/[...slug] route is working as expected

const url = new URL(`/${locale}${url.pathname}${url.search}`)
const page = await next(url)

### What's the expected result?

Rewrites to the index page that include search params should match the index.astro route

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-wnb7je?file=package.json,astro.config.mjs,src%2Fmiddleware%2Findex.js,src%2Fpages%2F404.astro,src%2Fpages%2F[locale]%2Findex.astro&title=Astro%20Starter%20Kit:%20Basics

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SamHarrison-dev** [comment]
> Do you happen to see the same issue with `context.rewrite()` too?

I haven't tried with `context.rewrite()` as we don't intend to rerun the middleware again, from debugging I can see that the regex test runs against the payload where it treats the search params as part of the pathname

`else if (route.pattern.test(decodeURI(payload))) {
        foundRoute = route;
        break;
}`
        
I have tested this against named routes that don't have a dynamic route as part of the subfolder i.e /test/?foo=bar 404's as route.pattern.test(decodeURI(payload)) is testing against '/test/?foo=bar' which doesn't match a route in my folder whereas it should ignore the search params as part of this regex test and find `basket`.

This will also explain as to why /c/[...slug] works as it will match the rest route regardless of whether the query params are present or not

**Comment by ematipico** [comment]
> I haven't tried with context.rewrite() as we don't intend to rerun the middleware again

I am sure you do. I just asked so I can understand better where the issue lies.

**Comment by SamHarrison-dev** [comment]
> I am sure you do. I just asked so I can understand better where the issue lies.

The docs suggest that inside of middleware I should use next and pass the new signature in https://astro.build/blog/astro-480/#experimental-request-rewriting

As I'm only going to be using rewrites in the middleware, am I right in using `next` and not `context.rewrite` here?

The conclusion I've came to on what the issue is, is that `route.pattern.test` is including the search params as part of this lookup which is not matching any routes causing the 404, I believe this should run the test excluding the search params as part of the lookup

**Comment by ematipico** [comment]
I was just asking you to try using the other API and see if you have the same error. It was a request to help me triage the issue. Never mind that; I believe I know how to fix the issue.
