### ISSUE TITLE
Remove duplicate class name

### ISSUE THREAD

**Issue by azat-io** [withastro/astro#11066]
### Astro Info

```block
Astro                    v4.8.3
Node                     v22.1.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @playform/compress
                         @astrojs/sitemap
                         @astrojs/svelte
                         @astrojs/mdx
```

### Describe the Bug

My component has a classname. I import this component and use the same classname. Styles in both components are isolated using date-attributes.

The output I get is a component with duplicate class names.

Example:

```astro
---
// Icon.astro

let { props } = Astro
---

<div class:list={["icon", props.class]} {...props}>
  I
</div>

<style>
.icon {
  /* ... */
}
</style>
```

I import this component on my page:

```astro
---
// index.astro
import Icon from '../components/Icon.astro'
---

<Icon class="icon" />

<style>
.icon {
  /* ... */
}
</style>
```

**Current output:**

```html
<div
  class="icon icon"
  data-astro-cid-j7pv25f6
  data-astro-cid-patnjmll
>
I
</div>
```

### What's the expected result?

Isolation of styles is provided through the use of date-attributes. It makes sense to delete classes with the same names.

**Expected output:**

```html
<div
  class="icon"
  data-astro-cid-j7pv25f6
  data-astro-cid-patnjmll
>
I
</div>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-c3nvhe?file=src%2Fcomponents%2FIcon.astro,src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Deduplication is not a feature of `class:list`. You can likely achieve this using the object syntax though: `class:list={[ { icon: true, [props.class]: true } ]}

**Comment by azat-io** [comment]
Okay, I think that would be helpful.

Thank you for your answer!
