### ISSUE TITLE
NPM build misses a post

### ISSUE THREAD

**Issue by danielrosehill** [withastro/astro#11078]
### Astro Info

```block
Astro                    v4.8.4
Node                     v20.13.1
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
                         @astrojs/sitemap
                         @astrojs/mdx
```

### Describe the Bug

I've been trying to figure out a peculiar error:

I created a new blog as usual in `/src/content/blog`. It's a standard markdown (`.md`) filetype.

When I visit my local dev server the post shows up as it should:

![image](https://github.com/withastro/astro/assets/40233203/b7ae2664-4c70-49e2-8694-68a42b6491a4)

But after deploying to Netlify I see that it's missing:

![image](https://github.com/withastro/astro/assets/40233203/d1c7dba7-200a-443d-a7f6-12733efaa8d0)

I ran `npm run build` locally in order to try figure out what was going on.

Indeed looking at the output of `index.html` the post is missing (so ... the problem is with the build and Netlify is just recreating the issue on the remote).

I added a previous blog that showed up just fine and can't figure out why this one wont display.

### What's the expected result?

Blog should appear in the blog post listings. The pagination files of the theme I'm using (Astro Paper) all look okay. 

### Link to Minimal Reproducible Example

https://www.stackblitz.com

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Please use Discord for these kinds of issues.
