### ISSUE TITLE
Empty Content Collections with defined scema don't generate typescript types

### ISSUE THREAD

**Issue by murl-digital** [withastro/astro#11075]
### Astro Info

```block
Astro                    v4.8.4
Node                     v22.0.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

I want to publish a blank vesion of my website with no content. I already have a schema set up on config.ts, and doing a dev build complains but works no problem. However, running a full production builds throws many typescript errors (specifically that something's of a type unknown) because the type wasn't properly generated. The example I provided should be enough to get the bug to trigger, but I wasn't able to.

### What's the expected result?

In this scenario, I would expect a build with no pages, similar to how a dev build works

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2n2i41

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Are you saying that the reproduction doesn't show the issue you found?

**Comment by murl-digital** [comment]
Massive egg on my face, but yes. I tried to get it to break yesterday but just couldn't. I am however able to do it with the project I'm working on, I can make the repository public so you can poke around if you like.

**Comment by matthewp** [comment]
Unless it's relatively small would prefer that you reproduce in the example you provided. It's possible that through reducing you'll find out that it's not a bug at all.

**Comment by murl-digital** [comment]
I had to poke it a bit, but I reproduced the issue. Turns out, it's not a problem with the build like I thought, it's a problem with ``astro check``

Reproduction steps are load up the codespace, run ``astro check``, and observe it freak out when the collection's empty

**Comment by Princesseuh** [comment]
`astro check`'s behaviour is correct here - when the collection is empty the types are `unknown`, `never` etc so trying to do operations on them results in type errors.

**Comment by murl-digital** [comment]
> `astro check`'s behaviour is correct here - when the collection is empty the types are `unknown`, `never` etc so trying to do operations on them results in type errors.

That would make sense if a collection didn't have a schema defined, but since it does the type would be known in theory, I would think

**Comment by bholmesdev** [comment]
@murl-digital Ah interesting, I am able to replicate with your Stackblitz example by running `npm run astro check`. Confirmed the issue goes away if at least one entry is present. I agree we should defer to your config types when a directory is empty

**Comment by Fryuni** [comment]
> > `astro check`'s behaviour is correct here - when the collection is empty the types are `unknown`, `never` etc so trying to do operations on them results in type errors.
> 
> That would make sense if a collection didn't have a schema defined, but since it does the type would be known in theory, I would think

The schema defines the type for the `data` field in each collection entry.

The type _where that field is_ is inferred from your entries, so that type is unknown. Your type doesn't even get used.

I think changing it to a generalization of the inferred types would be great, in this case the `data` field could have the proper types always.

**Comment by vbartalis** [comment]
I just ran into the same issue. I believe this is related to #8336, although it seems to be closed.

**Comment by Princesseuh** [comment]
> I just ran into the same issue. I believe this is related to #8336, although it seems to be closed.

The issue you linked is about a previous behavior where Astro would error if a collection was empty. This issue is about the types being unknown when there's no content
