### ISSUE TITLE
build error [vite] websocket server error : port is already in use

### ISSUE THREAD

**Issue by ResearchScientist** [withastro/astro#11077]
### Astro Info

```block
Astro                    v4.8.5
Node                     v20.12.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

Updated schema and reset and force pushed to astro studio.
Build results in error:

- 0 errors
- 0 warnings
- 0 hints

✔ Connected to remote database.
01:36:11 [WARN] [config] The feature "assets" is experimental and subject to change (used by @astrojs/netlify).
01:36:11 [astro:db] database: remote
01:36:11 [build] output: "server"
01:36:11 [build] directory: /workspaces/Accountability-Bunnies/dist/
01:36:11 [build] adapter: @astrojs/netlify
01:36:11 [build] Collecting build info...
01:36:11 [build] ✓ Completed in 2.58s.
01:36:11 [build] Building server entrypoints...
01:36:12 [vite] ✓ built in 1.30s
01:36:12 [build] ✓ Completed in 1.37s.

 building client (vite) 
01:36:12 [ERROR] [vite] WebSocket server error: Port is already in use
01:36:12 [vite] Re-optimizing dependencies because vite config has changed
01:36:12 [vite] ✓ 7 modules transformed.
01:36:13 [vite] dist/_astro/hoisted.CayMMy3Q.js  7.19 kB │ gzip: 2.44 kB
01:36:13 [vite] ✓ built in 113ms
01:36:13 
 finalizing server assets 

01:36:13 [build] Rearranging server assets...
01:36:13 [@astrojs/netlify] Emitted _redirects
01:36:13 [@astrojs/netlify] Generated SSR Function
01:36:13 [build] Server built in 4.55s
01:36:13 [build] Complete!

The project then appears on netlify as a blank page.
It deployed correctly with astro v4.8.2.
Failed with v4.8.5.
Reverted back to v4.8.2 and now also fails.

### What's the expected result?

Build to succeed.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mingjunlu** [comment]
Hi @ResearchScientist,

Thanks for taking the time to report this issue. I noticed that it seems to be similar to an existing issue, #11003. To keep our issue tracker organized and make it easier for others to find relevant discussions, I'm going to close this one for now. If you believe that this issue is different, please feel free to let me know.
