### ISSUE TITLE
Experimental rewriting of POST request does not work

### ISSUE THREAD

**Issue by gersomvg** [withastro/astro#11127]
### Astro Info

```block
Astro                    v4.8.4
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          npm (this should be pnpm)
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Not specific to a browser

### Describe the Bug

Just trying out the new rewriting feature as this came just in time for a use case that I had. Question: is this supposed to work with a POST request?

Let's say you post an `email` field to `/page-a`, I want to rewrite to `/page-b` while keeping the FormData.

It currently does not work, as the rewrite results in a 404. Any ideas?

### What's the expected result?

I'd expect `/page-b` to render and receive the `email` field in FormData

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-oyssmw?file=src%2Fpages%2Fpage-a.astro

**Comment by ematipico** [comment]
Downgraded to P3, as it's not critical and it doesn't affect many users. Plus, it's experimental and bugs are expected.
