### ISSUE TITLE
`getStaticPaths` fails during `astro build` when it imports a module that uses `import.meta.dirname`

### ISSUE THREAD

**Issue by Nemikolh** [withastro/astro#11122]
### Astro Info

```block
Astro                    v4.8.7
Node                     v18.20.3
System                   Linux (wasm32)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

When a module imported by a `[...slug].astro` page uses `import.meta.dirname`, the value is undefined while doing a `astro build`.

It is defined and working as expected when using `astro dev`.

### What's the expected result?

I would either expect both mode to fail or to work. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-get-static-paths-bug

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by Nemikolh** [comment]
Oh the module is handled by node and node 18 does not support `import.meta.dirname`. I suppose it works in dev because the module is transformed/handled by vite?

This can be fixed by using node >= 20 or using a "polyfill":

```js
import { dirname } from 'path';
import { fileURLToPath } from 'url';
    
const __dirname = dirname(fileURLToPath(import.meta.url));
```

**Comment by Fryuni** [comment]
This is not specific to `dirname`; I think it is a deeper problem.

This code:
```ts
console.log({
  meta: import.meta,
});
```

Is being converted into this code during `astro dev` before being loaded:
```ts
console.log({
  meta: __vite_ssr_import_meta__
});
```

`__vite_ssr_import_meta__` is a constant defined by Vite that contains the appropriate fields and refers to the correct file in the file system. In this case, the fields are not controlled by Node.

The same code is left unchanged when building. So `import.meta` will have the fields available on the running Node version. Not only will it not have the same fields, but the values for the fields in common would also be different. For example, `import.meta.url` will refer to the source file when running the dev server, but the chunk file where the code ended up after the build.

So this is logged during dev:
```
{
  meta: {
    dirname: '<project path>/src',
    filename: '<project path>/src/module.ts',
    url: 'file://<project path>/src/module.ts'
  }
}
```

And this is logged running the build result (using Node 20 in this case):
```
{
  meta: [Object: null prototype] {
    dirname: '<project path>/dist/server/chunks/pages',
    filename: '<project path>/dist/server/chunks/pages/__Ylb_7DBG.mjs',
    resolve: [Function: resolve],
    url: 'file://<project path>/dist/server/chunks/pages/__Ylb_7DBG.mjs'
  }
}
```

There might be code relying on this behavior, but it seems to me that Vite should be inlining the value in both cases.
I'm not sure if this is a problem on Vite itself or how Astro is configuring Vite.

**Comment by matthewp** [comment]
Thanks for explaining @Fryuni! This is indeed a case where you shouldn't/can't depend on source locations from dev and build being the same. They change because of bundling.
