### ISSUE TITLE
Unexpected Token when importing CSS module or CSS file with preact

### ISSUE THREAD

**Issue by SyntheticBird45** [withastro/astro#11121]
### Astro Info

```block
Astro                    v4.8.7
Node                     v22.0.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/preact
```

### Describe the Bug

When importing a CSS file (or module) in a jsx file (Preact, with compat for React). Astro crashes with `[scrubbed]/styles.module.css: Unexpected token (1:0)`
```jsx
/* toast-bar.jsx */
import styles from "./styles.module.css";
```
```css
/* styles.module.css */
.toastbar {
	display: flex;
	align-items: center;
}
```
Result:
```
[scrubbed]/styles.module.css: Unexpected token (1:0)

> 1 | .toastbar {
    | ^
  2 | 	display: flex;
  3 | 	align-items: center;
  4 | }
```
This is apparently not common and solutions I've found is to add a plugin to babel. But it do not work. It is weird since Astro documentation explicitly says support for CSS modules import in Preact/React JSX files

### What's the expected result?

No crash and nice looking toast

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-itc6zz?file=src%2Fcomponents%2Fpreact%2Fcomponent.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SyntheticBird45** [comment]
Presumably, the issue is caused by the `include` field in `integrations: [ preact({` configuration in `astro.config.mjs`. Excluding CSS files out fix the issue

**Comment by bluwy** [comment]
Yeah the issue is with the `include`. You should only include `.tsx` files like `include: ['src/components/preact/**.tsx']`
