### ISSUE TITLE
Repo can't be opened on GitHub codespaces

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#11130]
### Astro Info

```block
-
```

### Describe the Bug

The dev container fails to build because the monorepo requires an outdated version of pnpm.

### What's the expected result?

The repo can be opened on GitHub codespaces.

### Link to Minimal Reproducible Example

https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=348060227&machine=standardLinux32gb

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, being worked on in https://github.com/withastro/astro/pull/11146
