### ISSUE TITLE
`<a>` as first element inside component breaks layout

### ISSUE THREAD

**Issue by gauel** [withastro/astro#11154]
### Astro Info

```block
Astro                    v4.9.2
Node                     v20.9.0
System                   Windows (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/react
                         pagefind
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

Component that starts with `<a>` weirdly reduplicates its children, better to see it in action:
[Preview demo](https://astroanchorbug-4ifv--4321--71ef666c.local-credentialless.webcontainer.io)
[Demo repository](https://stackblitz.com/~/github.com/gauel/astro-anchor-bug)

### Demo screenshot:
![Snímek obrazovky 2024-05-27 v 18 36 29](https://github.com/withastro/astro/assets/69206870/97f2cf23-e12d-4ddf-890e-f4540ae79a3e)

### Production screenshot:
Starts with `<div>`:
![Snímek obrazovky 2024-05-27 v 18 39 50](https://github.com/withastro/astro/assets/69206870/27f39f07-3a1a-4c6c-95a3-8b80e2a25b89)

Starts with `<a>`:
![Snímek obrazovky 2024-05-27 v 18 40 47](https://github.com/withastro/astro/assets/69206870/143cd290-cf36-4ccd-87ca-504b5313f0e5)

### What's the expected result?

In the link above is both the expected result as well as the current bug

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/gauel/astro-anchor-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Nesting a button inside of an `a` is not valid HTML. See here: https://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5

**Comment by gauel** [comment]
@matthewp 
That was just a quick example. It doesn't matter what's inside. It still breaks:

![image](https://github.com/withastro/astro/assets/69206870/2bf84a59-c094-484b-8846-847f343b8f4c)

**Comment by gauel** [comment]
@matthewp 
With more complexity, it even starts to duplicate the nodes of the parent element. I just wanted to break down the complexity for the issue, but this is something far more serious than just nonvalid HTML

https://github.com/withastro/astro/assets/69206870/37e4772f-6976-4ac8-bd10-bb429423c9ec
