### ISSUE TITLE
shikiConfig not applying to Code components outside markdown

### ISSUE THREAD

**Issue by ssalbdivad** [withastro/astro#11157]
### Astro Info

```block
Astro                    v4.9.1
Node                     v22.2.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
                         @astrojs/react
```

### Describe the Bug

I was able to get twoslash + shiki working with Starlight by adding the following settings to my astro config:

```ts
export default defineConfig({
    site: "https://arktype.io",
    // starlight config etc with expressiveCode: false.,
    markdown: {
        shikiConfig: {
            theme: arkdarkColors,
            langs: [arktypeTextmate],
            transformers: [twoslash]
        }
    }
})
```

This looks great when rendering from markdown, but it doesn't affect the way the `Code` component (imported from `"astro:components"`) is rendered despite [the docs](https://docs.astro.build/en/guides/markdown-content/#syntax-highlighting) implying it is handled centrally.

![image](https://github.com/withastro/astro/assets/10645823/0aafcad2-5db9-4cf9-b5b8-ea2bcc04cb77)

I realize it being in the "markdown" key is a little suspicious, but as far as I could tell that was the only config location for it.

### What's the expected result?

Either `markdown/shikiConfig` should apply to `Code` components, or there should be a root config option that applies to both.

### Link to Minimal Reproducible Example

https://github.com/arktypeio/arktype/tree/v2-docs/ark/docs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Can you provide a minimal reproduction? Thank you.

**Comment by matthewp** [comment]
Creating a minimal repro is not about proving the bug exists. I believe that it does. The minimal repro helps with debugging and finding the bug. It saves the developer from needing to create one themselves. Thanks.

**Comment by ssalbdivad** [comment]
Well I'm creating this bug as a courtesy to the project and community as I've already found a way to work around this issue locally.

As a maintainer myself, I don't think it's fair to expect users to do extra legwork just so I can avoid it, which would imply I value my own time above theirs.

Personally, I'd value the work that went into submitting something like this in the first place, but if you want to close the issue, that's your prerogative as a maintainer.

**Comment by matthewp** [comment]
Sounds good. 

Additionally, after talking with others we have never supported this config being applied outside of Markdown since the config is not serializable at runtime. That's why this config is under `markdown` and not something like `syntaxHighlighting`.

**Comment by ssalbdivad** [comment]
@matthewp Yeah that's what I wanted to know more about the expected behavior before creating a repro.

> I realize it being in the "markdown" key is a little suspicious, but as far as I could tell that was the only config location for it.

I do think it would be very convenient to have some built-in way to get consistent behavior but if it doesn't sound like a feature worth prioritizing I understand.
