### ISSUE TITLE
Base does not change href value in anchors.

### ISSUE THREAD

**Issue by nicogutz** [withastro/astro#11159]
### Astro Info

```block
Astro                    v4.9.2
Node                     v20.13.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When adding images, CSS, or JS, the routes all seem to be affected by the base variable. In the documentation it says:

> Astro uses standard HTML [<a> elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) to navigate between routes. There is no framework-specific <Link> component provided.

> The base path to deploy to. Astro will use this path as the root for your pages and assets both in development and in production build.

Yet when building with a base, none of the hrefs on anchor elements are changed.

### What's the expected result?

With:
```
export default defineConfig({
    base:"/test"
});
```
```
<a href="/">
	<h1>Astro</h1>
	<img src={image.src} /><img />
</a>
```
Should turn into:
```
<a href="/test/">
	<h1>Astro</h1>
	<img src=/test/img.png><img />
</a>
```

### Link to Minimal Reproducible Example
[codesandbox.io](https://codesandbox.io/p/devbox/cocky-bohr-3dftz9?file=%2Fsrc%2Fpages%2Findex.astro%3A14%2C13&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwqhhtcn00072v6jcwnumoah%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwqhhtcn00022v6js5px5gdx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwqhhtcn00042v6j9vvcbk8i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwqhhtcn00062v6jwy6fdont%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwqhhtcn00022v6js5px5gdx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqhhtcn00012v6jch4w43q0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwqhip9i003d2v6j3ca43aty%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fastro.config.mjs%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwqhjxc200022v6i5jmw8aqb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A13%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252Findex.astro%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwqhhtcn00022v6js5px5gdx%2522%252C%2522activeTabId%2522%253A%2522clwqhjxc200022v6i5jmw8aqb%2522%257D%252C%2522clwqhhtcn00062v6jwy6fdont%2522%253A%257B%2522id%2522%253A%2522clwqhhtcn00062v6jwy6fdont%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqhhtcn00052v6jvz0fttim%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A4321%252C%2522path%2522%253A%2522%252Ftest%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwqhhtcn00052v6jvz0fttim%2522%257D%252C%2522clwqhhtcn00042v6j9vvcbk8i%2522%253A%257B%2522id%2522%253A%2522clwqhhtcn00042v6j9vvcbk8i%2522%252C%2522activeTabId%2522%253A%2522clwqhhtcn00032v6jy66fvrd2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqhhtcn00032v6jy66fvrd2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clwqhwbws00gj2v6in51euoow%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwqhwbzu0014dahid2kw752g%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nicogutz** [comment]
My bad:
https://stackblitz.com/edit/withastro-astro-wt5lgb

**Comment by BryceRussell** [comment]
This is expected behavior, the `base` option has to be prepended to paths manually. The easiest way to do this is creating a `URL` object using `Astro.url`:

```tsx
<a href={new URL('/path/to/a/page', Astro.url).pathname}></a>
```

**Comment by nicogutz** [comment]
> This is expected behavior, the `base` option has to be prepended to paths manually. 

In that case the documentation has to be much more explicit about this. If I have some time this week I'll make a PR.

**Comment by matthewp** [comment]
Thanks! Closing as this is expected behavior.

**Comment by ccjmne** [comment]
Hey @BryceRussell,
Can you help me understand why nothing special needs to be done for the `img`'s `src` attribute to be prefixed with the correct base URL? Is that new-ish?
We can reproduce that behaviour in @nicogutz 's MVCE.

**Comment by nicogutz** [comment]
> Hey [@BryceRussell](https://github.com/BryceRussell), Can you help me understand why nothing special needs to be done for the `img`'s `src` attribute to be prefixed with the correct base URL? Is that new-ish? We can reproduce that behaviour in [@nicogutz](https://github.com/nicogutz) 's MVCE.

@ccjmne I don't think this was ever changed, my PR for the documentation was changed and has been incorrect for a while now:

https://github.com/withastro/docs/pull/8466#discussion_r1632046508
> > We only use caution very rarely, for things like security issues. In general, we prefer to document "how something works" properly in the first place, not add notes on like we forgot to say something. 😅
> 
> I will keep that in mind for next time 😃 , nevertheless, the example shows the opposite of what happens, see [withastro/astro#11159](https://github.com/withastro/astro/issues/11159). The `base` never changes the `href`.
> 
> This is why I thought it was important to explicitly indicate that the anchors are **not changed** with the base config parameter. A user coming from other frameworks might assume that since the assets are changed by the config, then the anchors must be automatically changed as well.
