### ISSUE TITLE
lit client-shim uses deprecated apis, throws page speed error

### ISSUE THREAD

**Issue by scottnath** [withastro/astro#11160]
### Astro Info

```block
Astro                    v4.9.2
Node                     v20.12.2
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/lit
                         @astrojs/mdx
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

chrome + pagespeed

### Describe the Bug

The lit plugin's client-shim is using a deprecated API, which is causing a big hit to page insights.

Chrome's deprecation info:
https://chromestatus.com/feature/5116094370283520

The fix:

```
Instead of:
  (new DOMParser()).parseFromString(html,'text/html',{includeShadowRoots: true});

this can be used instead:
  document.parseHTMLUnsafe(html);
```

The file: https://github.com/withastro/astro/blob/2d93902f4c51dcc62b077b0546ead688e6f32c63/packages/integrations/lit/client-shim.js#L11

The warning:

```
[Deprecation] The includeShadowRoots parameter to parseFromString has been deprecated, and will be removed very soon. Please use parseHTMLUnsafe() or setHTMLUnsafe() instead.
```

Example of page speed error:
https://pagespeed.web.dev/analysis/https-scottnath-com/d3d6jmz94w?form_factor=desktop

The difference:
If I remove the `@astrojs/lit` plugin from `astro.config` the warning goes away and Lighthouse/Best Practices goes from `81` to `100`

### What's the expected result?

Proposed fix:
Change client-shim to use the correct api

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-lit?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Would you be willing to submit a PR?

**Comment by scottnath** [comment]
hi @matthewp submitted here:
https://github.com/withastro/astro/pull/11164

Not sure what the rules are to fix it coming from a fork though?

cheers, scott

**Comment by matthewp** [comment]
No issue at all, thanks!
