### ISSUE TITLE
I try to add images in my project, but report error on MAC M1. The error is "illegal hardware instruction".

### ISSUE THREAD

**Issue by peipei818** [withastro/astro#11169]
### Astro Info

```block
Astro                    v4.9.2
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I try to **add images** in my project, but report error on **`MAC M1`**. The error is **`illegal hardware instruction`**..

No matter I use  `npm` or `pnpm` to install,  it awlays report this error when i add images.

such as 
```
---
import { Image } from 'astro:assets';
import logo from '../assets/logo.png';
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<title>Astro</title>
	</head>
	<body>
		<h1>Astro</h1>
		<Image src={logo} alt="logo" width="40" height="40" />
	</body>
</html>

```

### What's the expected result?

I want use images in my project and no errors.

### Link to Minimal Reproducible Example

0

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Could you try reinstalling your dependencies? Maybe your installation of Sharp is corrupted, not sure.

**Comment by peipei818** [comment]
> Could you try reinstalling your dependencies? Maybe your installation of Sharp is corrupted, not sure.

I tried to reinstall the dependencies,but it still report error. It think it is because of `Sharp`, but I can't use `Sharp` you use in astro.
I manually downgraded `Sharp` version to `0.31.3`,then i can use images in my project and no errors.

such as 
```
{
  "resolutions": {
    "sharp": "0.31.3"
  },
  "name": "astro",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "astro": "^4.9.2"
  }
}
```

**Comment by peipei818** [comment]
When I `brew install vips`, this error will not occur, and I do not need to downgrade `Sharp` version to use the images normally.

**Comment by Grohotun** [comment]
or you can move to different image service like squoosh

**Comment by matthewp** [comment]
Sharp does depend on `libvips` so I think this is expected. Closing: https://github.com/lovell/sharp
