### ISSUE TITLE
Rewriting - Rewrite in the middleware but get a 404

### ISSUE THREAD

**Issue by zhangchuachua** [withastro/astro#11179]
### Astro Info

```block
Astro                    v4.9.2
Node                     v20.13.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### Describe the Bug

`/pages/[lang]/index.astro`: 

```js
export const getStaticPaths = (() => {
  return [{ params: { lang: 'en' } }, { params: { lang: 'zh-tw' } }, { params: { lang: 'jp' } }]
}) satisfies GetStaticPaths
```

`middleware.ts`: 

```ts
import { defineMiddleware } from 'astro:middleware'

export const onRequest = defineMiddleware(async (context, next) => {
  if(context.url.pathname === '/') {
    return next('/en')
  }
  return next();
})
```

When I visit `/` I can get the content of `/en` correctly, but the status code is 404.

### What's the expected result?

Since `/en` exists, the status code should be 200 instead of 404 when I access `/`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9yvgfw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by zhangchuachua** [comment]
![CleanShot 2024-06-04 at 11 37 03@2x](https://github.com/withastro/astro/assets/57211927/27f18d97-3605-4b6f-b3d7-a20294f639c9)

The `payload` cannot match the route in `tryRewrite`, so 404 is caused.

**Comment by ematipico** [comment]
I mean, that's expected, don't you think? By default, an index page is required (https://docs.astro.build/en/guides/internationalization/#redirecttodefaultlocale).

Since you're intentionally breaking this constraint, it's normal to get a 404 for a page that doesn't exist.

Just change the status code of the response. You can do that in the middleware:

```js
const response = await next("/en");
response.status = 200;
```

**Comment by zhangchuachua** [comment]
> I mean, that's expected, don't you think? By default, an index page is required (https://docs.astro.build/en/guides/internationalization/#redirecttodefaultlocale).
> 
> Since you're intentionally breaking this constraint, it's normal to get a 404 for a page that doesn't exist.
> 
> Just change the status code of the response. You can do that in the middleware:
> 
> ```js
> const response = await next("/en");
> response.status = 200;
> ```

@ematipico  I'm sorry, I used the Next.js middleware approach to use Astro's middleware. 

```js
const response = await next('/en');
console.log(response.status); // 200
return response;// Returned a response with a status of 200, but got 404 in the browser. this confuses me
```
