### ISSUE TITLE
Table of Contents not generated automatically in Astro components

### ISSUE THREAD

**Issue by tsavpyn** [withastro/astro#11177]
### Astro Info

```block
Astro                    v4.9.2
Node                     v20.14.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
```

### Describe the Bug

**Table of Contents is not generated automatically in Astro components.** 

I have an Astro component which includes &lt;h2&gt;&lt;h3&gt;, etc. 
In Astro components it will not generate table of contents via &lt;h&gt; marks, 
even though there is id declared in it like `<h3 id="my-content">My Content</h3>`

### What's the expected result?

I wished to see it automatically generate table of contents on the sidebar, like it does in md/mdx files.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-f8cdkz?file=src%2Fcontent%2Fdocs%2Fguides%2FEg.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
This is an intended behaviour. Feel free to create a discussion to propose the change.
