### ISSUE TITLE
Possible bug: pages can update Astro.locals

### ISSUE THREAD

**Issue by gersomvg** [withastro/astro#11174]
### Astro Info

```block
Astro                    v4.9.2
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
```

### Describe the Bug

Currently it's possible to update `Astro.locals` from within a page script. This can be useful for example if you want to update `Astro.locals.user` after a POST request, so the new data will immediately show. But since the docs only mention that you should write to locals from middleware, I think it's unintended behaviour.

### What's the expected result?

We can go either way: allow this behaviour and mark it stable, or disallow it explicitly by updating the docs and applying `Object.freeze` on `Astro.locals` after all the middleware has finished running.

I personally wouldn't mind marking updating locals from within a page as stable, as it currently works fine and is quite convenient for the use case mentioned above. But I can also imagine this opens a can of worms.

### StackBlitz

https://stackblitz.com/edit/github-mxldb7?file=src%2Fmiddleware.ts

**Comment by adaliszk** [comment]
The danger I see is the page script and any astro components you may import. They all have access to the `Astro` global; thus, any of them could modify the locals when they get parsed.
For the page, I might even allow it to change the locals through a dedicated method, like `Astro.locals.set(name, value)`, but once the page starts to render, none of the components used should be able to modify data there.
One edge case is the Layouts and any Page imports, which should all behave as pages and not components, even though the template interface does expose them as components.

**Comment by gersomvg** [comment]
@adaliszk because of the design of Astro pages and layouts having to be imported into a page like a regular component instead of being some abstraction on top, it currently seems to be quite easy to reason about updating `Astro.locals` from the page at least. The only place after middleware where you would have non-updated `locals` would be any leading code above in the same page file as where you are doing the update. I would also be in favour of not recommending or even disabling updates from within components as that will be the point where you can't reason about execution order anymore.

**Comment by gersomvg** [comment]
Added reproduction: https://stackblitz.com/edit/github-mxldb7?file=src%2Fmiddleware.ts

**Comment by matthewp** [comment]
I think we might have allowed this on purpose, cc @ematipico to confirm. If middleware can mutate variables then I don't think we're gaining that much from banning pages/endpoints from doing so. The downside still exists. And making each middleware call cause a new object allocation would be expensive for little gain. In my mind, `Astro.locals` is a shared space and everyone needs to play well with each other.

**Comment by adaliszk** [comment]
It makes no sense not to freeze the object right away. With the current behavior, a random component can change locals mid-rendering, potentially breaking or hijacking the rest of the page. I am not worried about allocating memory or spending CPU time; I am just concerned about breaking the expectations of a deterministic code and the potential attack surface of a supply-chain attack.

**Comment by ematipico** [comment]
@adaliszk this is true for every library you install, every integration you install, every adapter and your/others code. If you're worried, you can inspect your dependencies and decide to fork or send a PR.

This isn't a valid argument in open source.

Other than that, I don't think freezing the whole object is a viable solution because users might still need to write in it. If you're worried about **your locals**, you can freeze them. Astro freezes the assignment to locals, so third party code can't wipe them.

**Comment by adaliszk** [comment]
Very well. I'm sorry that I raised the security aspect of it. There is no desire to block the vulnerability until someone posts a horror story of the exact attack that stole confidential information or perhaps even money.
While there is always a risk whenever you install a dependency, a framework should not make it easy to execute an attack.

/unsubscribe

**Comment by ematipico** [comment]
I take security seriously, and it's a soft subject, and I can feel it's the same for, I think. Astro project take it seriously too, in fact we have a CVE filing system in place that you can use.

Because of that, I need to understand **exactly** what are the security implications you're talking about, maybe backed by a reproduction. Happy to raise the issue to a p5.

**Comment by matthewp** [comment]
There's nothing special about `Astro.locals` vs. any other object that's available inside of components. `Astro.request` is itself mutable, just as are most JavaScript objects.

There are measures we can and probably should take to help though. We could probably make `locals.__proto__` non-writable, that way if someone assigns user-input onto it, it prevents prototype pollution from occurring.

Would love more specific recommendations outside of "every object must be immutable" which is not reasonable and not something any other framework does to my knowledge.

**Comment by gersomvg** [comment]
Thanks for all the comments. So back to the original question that caused me to explore this:

- Given that sometimes you want to update something in locals based on a post request that is handled in a page;
- Given that the frontmatter code on the page level seems to be ran before any other component code;
- Would you say its safe to update Astro.locals from the page and have the changes be reflected in all components?

**Comment by matthewp** [comment]
It is safe in that the frontmatter code does always run before those components, so you are not going to run into race conditions. I assume you probably are doing this to avoid needing to pass props through several layers of component props. It should work and not break to do this. Whether that's a good pattern or not, I guess that's a matter of opinion. I like the explicitness of prop passing, but you are free to do it another way.

Going to close as I don't think there's any bugs to fix from this issue. Thanks for the discussion though!

**Comment by Fryuni** [comment]
Just pointing out a little detail since that is where the Devil lies:

> It is safe in that the frontmatter code does always run before those components, so you are not going to run into race conditions.

It is safe to do that in the front matter of the page. If you change locals from the front matter of a component, it may race with changes from the front matter of sibling components.

Race here in the JS sense. A logical race, not a memory race.

**Comment by matthewp** [comment]
Yes, don't attempt to set variables that siblings need. Only direct children

**Comment by gersomvg** [comment]
Thanks for taking some time on this issue @matthewp!
