### ISSUE TITLE
Blending page layout scripts and post scripts

### ISSUE THREAD

**Issue by SolT31** [withastro/astro#11172]
### Astro Info

```block
Astro                    v4.1.2
Node                     v20.12.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

All

### Describe the Bug

When using different layouts for the list of posts and individual posts in "MD" format, the script sections from the individual post layout mixed up on the list of posts page. 

### What's the expected result?

The script from an individual post should not end up on the list page, as there is a possibility it could break the list page layout.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/unruffled-easley-944jv8?file=%2Fsrc%2Flayouts%2Flayout_main.astro%3A12%2C1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is a downside to how Astro.glob works. And it's one of the reasons we created Content Collections. I highly recommend you use that instead as we'll probably remove Astro.glob in 5.0

https://docs.astro.build/en/guides/content-collections/

**Comment by matthewp** [comment]
Going to close as we don't plan on changing Astro.glob behavior.
