### ISSUE TITLE
Passing functions from Astro into Svelte

### ISSUE THREAD

**Issue by zellwk** [withastro/astro#11180]
### Astro Info

```block
▶ npx astro info                 
Astro                    v4.9.2
Node                     v21.7.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             astro:db
                         @astrojs/db/file-url
                         @astrojs/mdx
                         @astrojs/svelte
                         @astrojs/tailwind
                         @astrojs/sitemap
```

### Describe the Bug

I tried to pass a function into a Svelte Component from an Astro file. 

In SSR, the function is able to execute fine. But in the browser, the function becomes `null`. Is this an expected behaviour? 

### What's the expected result?

Function should be executed in both SSR and client modes. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-srrouw-oh7hlx?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
It is expected behaviour and is documented at https://docs.astro.build/en/guides/framework-components/#passing-props-to-framework-components. It happens for any framework components.
