### ISSUE TITLE
CSS Sibling Selectors Affecting <astro-island> Tags

### ISSUE THREAD

**Issue by lstephensca** [withastro/astro#11185]
### Astro Info

```block
Astro                    v4.9.2
Node                     v21.7.1
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/preact
                         astro:db
                         @astrojs/db/file-url
                         astro-icon
```

### Describe the Bug

I've encountered an issue where applying certain CSS classes via tailwind, specifically those targeting siblings (e.g., .space-y-8 > :not([hidden]) ~ :not([hidden])), unexpectedly affects `<astro-island>` tags in Astro. This occurs because the `<astro-island>` tag, which is set to `display: contents`, doesn't visually render the applied margins or paddings from these sibling selectors.

### What's the expected result?

CSS sibling selectors should not affect the `<astro-island>` tag itself but rather the components contained within it.

Workaround: Wrapping the component in an additional `<div>` element resolves the issue by controlling the scope of the CSS.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4c6duy?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Yes, this is a trade-off we have to make as we need a root to render into. `display: contents` makes *most* CSS work as expected by sibling selectors is one place where it falls short. The fix is to use a wrapper, as you have.

We've had it this way for years now and aren't going to change it any time soon (not sure how we even could), so going to close.
