### ISSUE TITLE
SyntaxError: Unexpected number when running any Astro command with pnpm

### ISSUE THREAD

**Issue by DavidNazareno** [withastro/astro#11215]
### Astro Info

```block
pnpm astro info

> astro "info"

SyntaxError: Unexpected number
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:169:18)
    at callTranslator (node:internal/modules/esm/loader:272:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:30)
 ELIFECYCLE  Command failed with exit code 1.
```

### Describe the Bug

I encountered a SyntaxError: Unexpected number error when running any Astro command using pnpm. This issue occurs immediately after creating a new Astro project with pnpm. Below is the error message:

![Screenshot-17](https://github.com/withastro/astro/assets/20806165/f893d3ac-9375-4ea0-a155-70a9c7898f74)

``` bash
pnpm run dev
> astro "dev"

SyntaxError: Unexpected number
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:169:18)
    at callTranslator (node:internal/modules/esm/loader:272:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:30)
 ELIFECYCLE  Command failed with exit code 1.
```
Steps to reproduce:
Create a new Astro project using pnpm.
Run any Astro command, such as pnpm astro info.

**This error does not occur if I create the project with npm**

Environment:
OS : Pop!_OS 22.04 LTS
pnpm version: 9.1.4
Node.js version: v20.13.1

### What's the expected result?

The commands should execute without errors and provide the relevant information.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by V3RON** [comment]
@DavidNazareno Unfortunately, I cannot reproduce this issue using your steps. Could you please reinstall Node and PNPM to ensure they are not corrupted, or provide additional details about your environment?

**Comment by millette** [comment]
@DavidNazareno I basically have the same config with popos, pnpm 9.3.0 and node 20.14.0.

`pnpm astro info` works as expected, so does `pnpm dev`.

Note that I have in my scripts:
```json
{
  "scripts": {
    "astro": "astro"
  }
}
```

Otherwise, you'll need to use `pnpm dlx astro info`.

**Comment by ascorbic** [comment]
@DavidNazareno  Do either `./node_modules/.bin/astro info` or `node node_modules/astro/astro.js info` work?

**Comment by bluwy** [comment]
Closing due to lack of response. From around the web, looks like you may need to upgrade node and ensure its binary matches your OS.
