### ISSUE TITLE
Is there a date picker component in Astro, or is there a standard way to use third-party date picker component?

### ISSUE THREAD

**Issue by acche** [withastro/astro#11212]
### Astro Info

```block
Astro                    v4.10.0
Node                     v22.2.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/partytown
                         @astrojs/react
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Safari

### Describe the Bug

When I using Shadcn UI to integrate datePicker component, it shows an error to prevent running:

```
TypeError
An error occurred.
Cannot read properties of null (reading 'useState')
cjs/react.development.js:1622:21
```

When I using the NextUI for the datePicker, it can only display plain text on the page, no pop-up action can be trigger.

 **Is there a date picker component in Astro, or is there a standard way to use third-party date picker component?**

### What's the expected result?

It should be display datePicker normally and work with the interaction.

### Link to Minimal Reproducible Example

https://yourastro.new/hard/to/use

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
If you're seeking help or other opinions, please use our Discord

**Comment by acche** [comment]
> If you're seeking help or other opinions, please use our Discord 

@ematipico I try to find the answer from discord that someone ask the same question but no one resolved it yet. Almost one month!

**Comment by ematipico** [comment]
Sorry about that. We use GitHub for actual bugs

**Comment by acche** [comment]
> Sorry about that. We use GitHub for actual bugs

@ematipico Is an issue occurring with a third-party component considered a bug?

**Comment by ematipico** [comment]
It depends, that's why you should provide a reproduction

**Comment by acche** [comment]
Hey @ematipico  I just follow the instruction from shadcn UI - https://ui.shadcn.com/docs/installation/astro to add the Date Picker.

```
---
"use client"
 
import * as React from "react"
import { format } from "date-fns"
import { Calendar as CalendarIcon } from "lucide-react"
 
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Calendar } from "@/components/ui/calendar"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover"

const [date, setDate] = React.useState<Date>()
---
 
<Layout title="Astro">
    <main>
        <title>Astro</title>
	<div>
            <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant={"outline"}
                        className={cn(
                          "w-[280px] justify-start text-left font-normal",
                          !date && "text-muted-foreground"
                        )}
                      >
                        <CalendarIcon className="mr-2 h-4 w-4" />
                        {date ? format(date, "PPP") : <span>Pick a date</span>}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0">
                      <Calendar
                        mode="single"
                        selected={date}
                        onSelect={setDate}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
	</div>
        </main>
</html>
```
