### ISSUE TITLE
@astro/solid-js conflicts with vite@5

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#11217]
### Astro Info

```block
Astro                    v4.10.1
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Conflicting peer dependency with vite@5. solid-devtools depends on outdated solid-start, which requires vite@4 as peer dependency.

### What's the expected result?

[This](https://github.com/withastro/astro/pull/10937) should have been a major version increment or compatible change.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yttbgb?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
I don't understand what the repro is trying to show. I don't see any error anywhere, solid is not used nor the integration (although deps are added)... Can you give me more details and/or update the repro?

**Comment by florian-lefebvre** [comment]
Works with `npm install --legacy-peer-deps` but I'm going to open an issue upstream

**Comment by shishkin** [comment]
Thank you!

**Comment by kuringer** [comment]
I'm facing this issue too, and it's preventing me from using a date picker component in my Astro project with Solid.js. The --legacy-peer-deps workaround doesn't fully resolve the problem.

This is a critical issue blocking effective use of Solid.js with Astro. Are there any updates on a permanent fix?

As a workaround, would it be possible to make solid-devtools an optional dependency?

**Comment by florian-lefebvre** [comment]
The peer dependency is already optional (https://github.com/withastro/astro/blob/main/packages/integrations/solid/package.json#L50-L54). I can't look into it before Sept 30tg, but if you want a fix to land I think the fastest way is to submit a PR to the devtools directly. Can you also provide a reproduction showing the workaround does not work?

**Comment by florian-lefebvre** [comment]
This should be fixed next Monday when we merge the renovate PR
