### ISSUE TITLE
Emmet Abbreviation suggestion takes priority over Astro suggestions

### ISSUE THREAD

**Issue by IcyFoxe** [withastro/astro#11220]
### Astro Info

```block
Astro                    v4.10.1
Node                     v20.11.1
System                   Windows (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

I didn't find any post mentioning this problem and I don't remember having this issue last time I worked with Astro, but maybe there was an update from VSCode that could start causing this.

Basically whenever I type some variable in the template, the first suggestion comes from Emmet and then the actual suggestion from Astro. This makes suggestions very annoying to use, because you constantly have to select the second option (which is not a problem in other frameworks).

![image](https://github.com/withastro/astro/assets/48529386/9ed902c3-b594-4f4e-ba89-3411314d04c9)

I've done a lot of searching and can't find a solution to this problem. I see that the suggestion comes from the Emmet "Text" Abbreviation (https://docs.emmet.io/abbreviations/syntax/#text), but there's no way to disable this specific suggestion. Only solutions that I've found is either completely disable Emmet, which is not what I want, since it's useful in a lot of places, or move Emmet suggestions to the bottom of the list, which is also a bad solution.

### What's the expected result?

Astro suggestions should appear before Emmet suggestions.

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IcyFoxe** [comment]
Ah I'm sorry, thanks to the useless google, I didn't find that this problem was already being mentioned in the `withastro / language-tools` repo (which is probably more appropriate place for this issue). But that at least proves me, that it started happening recently and didn't happen before. Definitely something that should be resolved soon, if possible.

**Comment by Princesseuh** [comment]
It's been happening since 2.0 of the language server, so about a year+ ago.

It's a bit tough to fix because it's a side effect of allowing Emmet to work in more places and not really a bug per se (it's a valid Emmet completion!), though it's definitely unwanted behavior.

I'll close this issue in favor of the existing language-tools discussion
