### ISSUE TITLE
Virtual module ids with query parameters that end in `.astro` throw errors

### ISSUE THREAD

**Issue by BryceRussell** [withastro/astro#11230]
### Astro Info

```block
Astro                    v4.10.1
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             astro-test-invalid-transform
```

### Describe the Bug

The [`transform` hook](https://github.com/withastro/astro/blob/734b98fecf0212cd76be3c935a49f84a9a7dab34/packages/astro/src/vite-plugin-astro/index.ts#L205) inside the [vite plugin `astro:build`](https://github.com/withastro/astro/blob/734b98fecf0212cd76be3c935a49f84a9a7dab34/packages/astro/src/vite-plugin-astro/index.ts) matches module ids that are ***not*** Astro files but contain paths to Astro files inside query parameters, for example:

```
virtual:test?importer=%2Fhome%2Fprojects%2Fgithub-vdjlmf%2Fsrc%2Fpages%2Findex.astro
```

This issue occurs because Astro uses `.endsWith` to check for Astro files
https://github.com/withastro/astro/blob/734b98fecf0212cd76be3c935a49f84a9a7dab34/packages/astro/src/vite-plugin-astro/index.ts#L205

```diff
- if (!id.endsWith('.astro') || parsedId.query.astro) {
-   return
- } 
+ if (!parsedId.filename.endsWith('.astro')) {
+   return
+ }
+ if (parsedId.query.astro) {
+   return
+ }
```

One workaround for this is to add an empty query parameter as a suffix:
```
virtual:test?importer=%2Fhome%2Fprojects%2Fgithub-vdjlmf%2Fsrc%2Fpages%2Findex.astro&end
```

### What's the expected result?

Astro does not attempt to transform virtual module's that have `.astro` paths inside query parameters

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vdjlmf?file=astro.config.mjs,src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
We can do similar to what Vue does which it:

- creates a filter: https://github.com/vitejs/vite-plugin-vue/blob/727004bf67a976daed3e7d5975e90a340ae68a5b/packages/plugin-vue/src/index.ts#L135
- compares it against the filename, not the query: https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue/src/utils/query.ts#L13-L38

**Comment by BryceRussell** [comment]
If this fix uses [`createFilter`](https://github.com/rollup/plugins/tree/master/packages/pluginutils#createfilter), are the [`include` and `exclude` options](https://github.com/rollup/plugins/tree/master/packages/pluginutils#include-and-exclude) meant to be configurable from the Astro config? If not, it may be simpler and faster to skip the filter and check `filename` directly.
