### ISSUE TITLE
Prefetch not working properly

### ISSUE THREAD

**Issue by djmtype** [withastro/astro#11237]
### Astro Info

```block
Astro                    v4.10.1
Node                     v21.6.2
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Brave (with shields disabled or enabled)

### Describe the Bug

When using prefetch on my project, it fails to load and/or locate the page.*.js file when in production using a service like Netlify. 

First I tried adding `prefetch: true` in my config file in which I then assigned `data-astro-prefetch` to my links. 

After that failed, instead, I tried setting prefetch at the global level: 

```
prefetch: {
  prefetchAll: true
}
```
This also did not fix my issue.

This is a static site BTW. When I build and preview locally there are no issues with prefetching links.

On the other hand, when using Netlify, it results in an error for each link I hover. 
Example: `(failed) net::ERR_FAILED` `page.DFwqf4PB.js:1] (net::ERR_FAILED 301 (Moved Permanently))`

I tried adding a _headers file with the following, but it made no difference: 
```
/_astro/*
  Cache-Control: public, max-age=31536000
  Content-Type: application/javascript
```

Is this a bug or something I am doing wrong?

### What's the expected result?

I'd expect when I hover over a prefetch-assigned link, it would fetch that specific document.

### Link to Minimal Reproducible Example

https://astro-prefetch-test.netlify.app

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Trombach** [comment]
I've just tried it on your example link and I'm no seeing any errors 
![image](https://github.com/withastro/astro/assets/19306765/7038e54e-f411-4a28-a9bb-c93efcab0ed7)

Maybe try and clear the browser cache.

**Comment by djmtype** [comment]
@Trombach in Chrome it's fine, but Brave, it produces an error each time the prefetch link is hovered. I had cleared my browser's cache, too.

Screenshot below: 
![Screenshot 2024-06-12 at 6 42 50 AM](https://github.com/withastro/astro/assets/930713/586ba575-9832-4305-b1fc-9e977a8bd723)

**Comment by V3RON** [comment]
@Trombach @djmtype
Using Brave is a must-have to reproduce that. I searched for any reason why Brave doesn't want to follow redirects in `fetch` requests, but couldn't find anything useful. 

@djmtype 
Those requests are redirected from /blog to /blog/ (notice the trailing slash). Add trailing slashes to all your links and try again. It should work fine then. If you don't want to have those slashes at the end, then [this article](https://support.gatsbyjs.com/hc/en-us/articles/17278086709780-Remove-trailing-slash-in-Netlify-URLs) may help you.

**Comment by djmtype** [comment]
@V3RON Thanks, good point, I overlooked the trailing slashes bit.

I'll try it once Netlify is back online.

**Comment by ascorbic** [comment]
It sounds like is solved, so I'll close the issue
