### ISSUE TITLE
Markdown configuration for shiki doesn't accept `defaultColor: false` 

### ISSUE THREAD

**Issue by madcampos** [withastro/astro#11238]
### Astro Info

```block
Astro                    v4.9.2
Node                     v20.14.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @vite-pwa/astro-integration
                         @astrojs/sitemap
                         astro-icon
```

### Describe the Bug

The configuration for markdown doesn't do anything if we set `defaultColor` to `false`. According to [Shiki's docs](https://shiki.style/guide/dual-themes#without-default-color) it should remove the inline styling on code blocks.

### What's the expected result?

Code blocks to have no default style when the setting is set.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-shehh9?file=astro.config.mjs

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
The `shikiConfig` options don't accept every option supported by `codeToHtml`, because they're not passed through as-is. It could in theory support more of them. Currently this is implemented [here](https://github.com/withastro/astro/blob/plt-2183/packages/markdown/remark/src/shiki.ts#L41).

**Comment by madcampos** [comment]
Got some help with this issue, will submit a pull request with a fix :)

**Comment by ematipico** [comment]
FYI this won't be considered a fix but a **new feature**

**Comment by kzmiura** [comment]
It appears that this issue has resurfaced as of `astro@6.1.9`.
