### ISSUE TITLE
Rewriting to the root doesn't work with trailingSlash: never & rewrite to non-existed page/404 issues

### ISSUE THREAD

**Issue by vchirikov** [withastro/astro#11235]
### Astro Info

```block
astro 4.10.2
```

### Describe the Bug

1. rewriting to `/` doesn't work with `trailingSlash: 'never'` config setting
1. rewriting to `/404` doesn't work at all (with or without context (`next('/404')` and `ctx.rewrite('/404')`), might be the same behavior for 500 (?)
1. astro's pipeline throws the same error type for a non-existed page or rendering error (so we don't know which error page should show - 404 or e.g. 500, [it's bad for i18n](https://github.com/withastro/roadmap/discussions/950) )

![bug](https://github.com/withastro/astro/assets/40987940/e9527556-7fa5-416a-8e60-7d36ed0d8bc7)

### What's the expected result?

rewriting works fine with `/404` and `/` with or without trailingSlash setting

### Link to Minimal Reproducible Example

https://github.com/vchirikov/astro_issue_01

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Downgrading to a P3 because this is an experimental feature, and I doubt we have a lot of users using it

**Comment by vchirikov** [comment]
@ematipico also I found that rewriting doesn't change the status code of response, e.g. I want to rewrite from `/en/about` to `/pages/about.astro` I do something like this:

```ts
const response = await next('/about');
console.log('return response from rewrite handler', response)
return response;
```
see nodejs in logs:

```js
16:36:49 [watch] src/middleware.ts
return response from rewrite handler Response {
  status: 200,
  statusText: 'OK',
  headers: Headers {
    'content-type': 'text/html',
    'X-Astro-Route-Type': 'page',
    'X-Astro-Reroute': 'no'
  },
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
  bodyUsed: false,
  ok: true,
  redirected: false,
  type: 'default',
  url: ''
}
16:36:49 [404] /en/about 187ms
```

note the `response.status` is 200, but astro returns 404 to the browser:

![image](https://github.com/withastro/astro/assets/40987940/e69db9e3-4b67-4b7d-8c95-a3edc2701d13)

**Comment by vchirikov** [comment]
@ematipico I've tested 4.11 and [404 on rewriting is still the issue](https://github.com/withastro/astro/issues/11235#issuecomment-2163478342)

Again, the returned http status code is from `/original-url` not from `/rewritten-url`. Should I create a new issue or you will re-open this?

**Comment by ematipico** [comment]
Please create a new one. I haven't seen the issue posted in the comment
