### ISSUE TITLE
SSR behaviour different with `hybrid` mode and `node` adapter between Linux and MacOS (ARM)

### ISSUE THREAD

**Issue by LunaticMuch** [withastro/astro#11232]
### Astro Info

```block
Astro                    v4.10.1
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/starlight
                         @astrojs/tailwind
```

### Describe the Bug

I recently opened an issue with [Astro Starlight](https://github.com/withastro/starlight/issues/1989) because I was seeing a weird behaviour with SSR.
In building the test case, I've noticed that the issue can be reproduced on MacOS (ARM) but not on codesandbox (or stackblitz) with Linux. It pointed me out to further debug and potentially rule out Starlight, and consider that the issue is within the adapter or compiler somewhere 😕  

None of the pages included in starlight are pre-rendered when the build runs on MacOS. They should be prerendered. 
However, when the build runs on Linux, they all get pre-rendered.

I tried different version of nodes too, as the default one in Stackblitz is v18 and I was running on v20, but this has not change anything.

In trying to reproduce, I collected logs and committed into my repo. Look for the following
- [MacOS](https://github.com/LunaticMuch/fuzzy-giggle/tree/main/logs/macos)
- [Codesandbox](https://github.com/LunaticMuch/fuzzy-giggle/tree/main/logs/codesandbox)

### What's the expected result?

The result is that the pages in starlight plugin get pre-rendered too. There's no reason for not rendering then and, given the `hybrid` configuration, by default they should be rendered.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/LunaticMuch/fuzzy-giggle

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by V3RON** [comment]
That's weird. I cloned you repository, try building it myself and experienced no issues at all, no matter which Node version I used (v18, v20, v21).

```
Astro                    v4.10.1
Node                     v18.20.3
System                   macOS (arm64)
Package Manager          unknown
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/starlight
                         @astrojs/tailwind
```
[See full logs here](https://github.com/user-attachments/files/15792177/log.txt)

Is there anything special about your environment? Could you purge `node_modules`, reinstall and try again? 🤔

**Comment by LunaticMuch** [comment]
> Is there anything special about your environment? Could you purge `node_modules`, reinstall and try again? 🤔

Just tried on one of my laptop, fresh clone and `npm cache clean --force` before running `npm ci`, I get this

```
 prerendering static routes 
17:50:42 ▶ src/pages/schema/[...slug].astro
17:50:42   ├─ /schema/1/index.html (+10ms)
17:50:42   ├─ /schema/2/index.html (+3ms)
17:50:42   └─ /schema/3/index.html (+3ms)
17:50:42 ✓ Completed in 32ms.
```

So no change. I do not think I have anything weird on my env. I use `nvm` for managing my node versions, but other than that I do not have any `NODE_` variable set.

**Comment by V3RON** [comment]
@LunaticMuch 

Aha! I reproduced it 🚀 

I noticed the directory where Astro is running on your side includes "_GITHUB." I added the same directory on my side, and voilà, I observed the same behavior.

I'll investigate it further today and provide a detailed explanation.

**Comment by LunaticMuch** [comment]
> I noticed the directory where Astro is running on your side includes "_GITHUB." I added the same directory on my side, and voilà, I observed the same behavior.

I have my path as `/Users/stefano/_GITHUB` but initially I observed the behaviour in a different path.

**Comment by V3RON** [comment]
That's the culprit:

https://github.com/withastro/astro/blob/769f11f23f3dd32da912d0688008f9233ae13dd4/packages/astro/src/core/util.ts#L122-L129

Notice the condition in line 124. It checks for the presence of `_` in any part of the URL. The problem is that file is an absolute path, so `_GITHUB` is picked up by this condition, causing the page to be considered 'not public'.

We should limit paths to the repository root.

**Comment by LunaticMuch** [comment]
> We should limit paths to the repository root.
Yeah, it should the local path and not the file path... I was about to propose a fix, but thanks 😄
