### ISSUE TITLE
a11y warning using Tabs / TabList: interactive role on non-interactive element

### ISSUE THREAD

**Issue by sparecycles** [withastro/astro#11239]
### Astro Info

I think [`aria_non_interactive_roles`](https://github.com/withastro/astro/blob/769f11f23f3dd32da912d0688008f9233ae13dd4/packages/astro/src/runtime/client/dev-toolbar/apps/audit/rules/a11y.ts#L67-L108) is just missing [tabpanel](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tabpanel_role)?

### Describe the Bug

Seeing an a11y warning with a starlight Tabs/TabItems control.

### What's the expected result?

No a11y warnings?

### Link to Minimal Reproducible Example

stackblitz is failing to create a starlight project (in firefox?)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I believe you are right, wanna send a PR?

**Comment by mingjunlu** [comment]
@sparecycles Hi, are you still working on this issue?

**Comment by sparecycles** [comment]
@mingjunlu sorry, I'm not.  I hit some other errors after I applied that fix and now I've forgotten the context.

**Comment by mingjunlu** [comment]
No worries! I could take a look at it.
