### ISSUE TITLE
Cannot access 'default' before initialization

### ISSUE THREAD

**Issue by adesege** [withastro/astro#11246]
### Astro Info

```block
Astro                    v4.10.2
Node                     v20.13.1
System                   macOS (x64)
Package Manager          yarn
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
```

### Describe the Bug

When I build the app and upload it to cloudflare, I get the following error

```
(error) 19:49:34 [ERROR] ReferenceError: Cannot access 'default' before initialization
    at lastNext (renderers.mjs:3518:32)
    at async renderers.mjs:383:22
    at async callMiddleware (renderers.mjs:2963:10)
    at async RenderContext.render (renderers.mjs:3539:22)
    at async App.render (renderers.mjs:4371:18)
    at async Object.fetch (chunks/@astrojs_CbQyIiEc.mjs:89:22)
```

I've tried deleting node_modules, rerun yarn install several time but that didn't fix it. I was able to deploy to Cloudflare pages before now.

Sometimes, I get an empty `import.meta.env`. I've the experimental env feature but that didn't work either.

### What's the expected result?

The expected result is to be able to build an astro project and deploy to Cloudflare

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/blog?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
Hi,
Can you provide a reproduction as a repo that can be deployed. It's a lot harder for us to help you without it. The default example that you included doesn't include any of your config changes or adapters, so it's not something that can be used for this.
Thanks!

**Comment by saaymeen** [comment]
Hi @adesege, I'm running into the same issue and wondering what your solution was? Is this due to a wrong  setup, or indeed a bug?

**Comment by lukeojones** [comment]
I'm also experiencing this issue, I'm trying to track down the issue and will upload a minimal example if I get there.
