### ISSUE TITLE
Cannot find module '*/dist/renderers.mjs' when build project

### ISSUE THREAD

**Issue by Lodo4ka** [withastro/astro#11259]
### Astro Info

```block
Node was version 20.12.2
{
    "dependencies": {
    "@astrojs/rss": "4.0.6",
    "@astrojs/sitemap": "3.1.5",
    "@astrojs/tailwind": "5.1.0",
    "@builder.io/qwik": "^1.5.7",
    "@fontsource/golos-text": "^5.0.8",
    "@markdoc/markdoc": "^0.2.1",
    "@qwikdev/astro": "^0.5.15",
    "@tailwindcss/typography": "^0.5.9",
    "astro": "4.10.2",
    "astro-compress": "^2.2.10",
    "astro-compressor": "^0.4.1",
    "astro-icon": "^0.8.1",
    "astro-meta-tags": "^0.2.1",
    "astro-navbar": "^2.3.0",
    "flowbite": "^2.3.0",
    "moment": "^2.29.4",
    "qwik-slider": "^1.1.0",
    "sass": "^1.63.6",
    "scss": "^0.2.4",
    "sharp": "^0.33.4",
    "slugify": "^1.6.5",
    "tailwindcss-animated": "^1.0.1",
    "valibot": "^0.28.1"
  },
  "devDependencies": {
    "@astrojs/ts-plugin": "1.8.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "astro-seo-schema": "^4.0.0",
    "autoprefixer": "^10.4.17",
    "eslint": "^8.44.0",
    "eslint-plugin-astro": "^0.27.2",
    "eslint-plugin-vue": "^9.16.1",
    "postcss": "^8.4.35",
    "prettier": "^2.8.8",
    "prettier-plugin-astro": "^0.10.0",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.4.5",
    "vite": "^5.1.3",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-minify": "^1.5.2"
  },
  "packageManager": "yarn@4.3.0"
{
```

### Describe the Bug

I am using the latest version of Astro and all plugins but I have error when build project. `renderers.mjs` was contained qwik library. I don't know why it was. Please help me guys

Full error log

Cannot find module '*/dist/renderers.mjs' imported from */node_modules/astro/dist/core/build/generate.js
  Stack trace:
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:322:34)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:225:14)

### What's the expected result?

Expected build was successful

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/agitated-goldwasser-t88qlx?file=%2Fsrc%2Fcomponents%2Fqwik%2FQwikCounter.tsx%3A9%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxeokegd00053b6iqbhpr8wp%2522%252C%2522sizes%2522%253A%255B35.872156013001074%252C64.12784398699893%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxeokegd00023b6io2cuaxww%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxeokegd00033b6i6gijyorr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxeokegd00043b6ipgw0ur8e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxeokegd00023b6io2cuaxww%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxeokegd00013b6i1xi1dna8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxeokx2b002y3b6i26kmgru7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fastro.config.mjs%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxep0ucw00023b6jxx2hcjb3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252Fqwik%252FQwikCounter.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxeokegd00023b6io2cuaxww%2522%252C%2522activeTabId%2522%253A%2522clxep0ucw00023b6jxx2hcjb3%2522%257D%252C%2522clxeokegd00043b6ipgw0ur8e%2522%253A%257B%2522id%2522%253A%2522clxeokegd00043b6ipgw0ur8e%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4321%252C%2522id%2522%253A%2522clxep1eho00353b6jcnht05yz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxep1eho00353b6jcnht05yz%2522%257D%252C%2522clxeokegd00033b6i6gijyorr%2522%253A%257B%2522id%2522%253A%2522clxeokegd00033b6i6gijyorr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxeomiey00cd3b6ibd2x359p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxeomik3000kdjg7f10m9it8%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxeomiey00cd3b6ibd2x359p%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Looks like a bug in the `@qwikdev/astro` package. Looking at the code it seems to move some files around. It probably doesn't intend to move these server build files, although I'm not sure the reasons it has for doing this.

The result though is that the files are in the wrong place, breaking references. I recommend submitting an issue or PR to that project.

<img width="323" alt="Screen Shot 2024-06-14 at 4 25 27 PM" src="https://github.com/withastro/astro/assets/361671/bf79fc0f-8aed-4880-8eb3-1e7e16f9f36d">
