### ISSUE TITLE
Default 404.astro page is not shown for non-supported languages when prefixDefaultLocale: true

### ISSUE THREAD

**Issue by jaimefd** [withastro/astro#11260]
### Astro Info

```block
Astro                    v4.10.2
Node                     v20.11.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-icon
```

### Describe the Bug

When setting prefixDefaultLocale to true for the i18n routing config, the 404.astro page no longer renders if your url doesn't start by a supported language.

For example, if my app has `es` and `en` as supported languages, `/es/any-non-existent-path` and `/en/any-non-existent-path` will redirect to `src/pages/404.astro`. But if I were to type `/fr/any-non-existent-path` or simply `/any-non-existent-path`, the page will just remain white and return a 404 error in the console (but not render my `src/pages/404.astro`).

Furthermore, it seems like similar issues have been reported in https://github.com/withastro/astro/issues/11011 and labeled as fixed, but other people are reporting in the comments that it still doesn't work, just like my issue

### What's the expected result?

I should be redirected to my `src/pages/404.astro` no matter what, even if the language isn't supported.

### Link to Minimal Reproducible Example

I cannot work on it right now and discord isn't working in my laptop, this was my only way to ask for support. Please forgive me

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You might ask in Discord if someone else is willing to create a reproduction for you.
