### ISSUE TITLE
Duplicated brackets are generated in data collections.

### ISSUE THREAD

**Issue by syhily** [withastro/astro#11274]
### Astro Info

```block
Astro                    v4.10.3
Node                     v22.3.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/mdx
```

### Describe the Bug

The latest release astro doesn't generate the JSON schema correctly. A duplicated `};` is introduced for each yaml data file. I think this bug is introduced by the https://github.com/withastro/astro/pull/11249

<img width="812" alt="image" src="https://github.com/withastro/astro/assets/1761698/79f37eb7-3f48-4ade-a43e-eb865b7445b3">

### What's the expected result?

Valid schema json.

### Link to Minimal Reproducible Example

https://github.com/syhily/yufan.me

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by syhily** [comment]
IIUC, the line in the belowing PR shouldn't be moved into the for-loop. It should be kept in the original place.

https://github.com/withastro/astro/pull/11249/files#diff-7e9b96084af9c6f79604dd4aaba392dc11ebb3e64f5a47f2d5c1ce67cb8abb79R452

**Comment by markgaze** [comment]
Apologies, this was my fault! Like I said on the PR comment, I'll have a look to see if I can add some tests around this because I made an assumption that the tests passing meant everything was fine with the types but that wasn't the case, unfortunately!
