### ISSUE TITLE
import.meta.env.MODE and other related env variables don't get properly set in `astro build`

### ISSUE THREAD

**Issue by syhily** [withastro/astro#11282]
### Astro Info

```block
Astro                    v4.10.3
Node                     v22.3.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/mdx
```

### Describe the Bug

When I execute the `astro build` I found that the `import.meta.env.MODE` is always equal to the `development`. Even if I set the `NODE_ENV=production`.

I just add a console.log in `astro.config.ts` and you can easily check the different in the bellowing screenshots.

![image](https://github.com/withastro/astro/assets/1761698/91298781-1ba3-4e00-8c01-91426ba17147)
![image](https://github.com/withastro/astro/assets/1761698/fbe4e740-51b6-430d-8b5f-8495529f5303)

### What's the expected result?

The `import.meta.env.MODE` should be `production` when I execute the `astro build`.

### Link to Minimal Reproducible Example

https://github.com/syhily/yufan.me

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hi @syhily can you please create a reproduction using https://astro.new/latest . Debugging your personal website slows down our ability to discover and fix the problem. Thank you.

**Comment by syhily** [comment]
Sorry for the inconvenience. I only add two line of code on `astro.config.ts` and execute the `astro build`. I'm this could reproduce this issue 100%.

```
console.log(process.env.NODE_ENV);
console.log(import.meta.env.MODE);
```

**Comment by ericclemmons** [comment]
Still an issue:

https://idx.google.com/just-the-basics-58885807

![Image](https://github.com/user-attachments/assets/c09f7db2-b889-4b09-aaab-cd93fcfd8cc6)

**Comment by ericclemmons** [comment]
@syhily Please re-open – I can't.
