### ISSUE TITLE
`astro:env` public variables should not be checked during sync

### ISSUE THREAD

**Issue by Trombach** [withastro/astro#11281]
### Describe the Bug

I'm not sure if it's best to report here or if this is an issue with `astro:env`.

I've moved my environment setup to `astro:env` and noticed that my Github action running `astro-check` started failing. An example can be found [here](https://github.com/Trombach/astro-homepage/actions/runs/9532080758/job/26273787108). I would expect for `astro-check` to only infer the type of my defined variable, but not to require the variables to actually be set.

It's easy enough to work around by just setting the environment variables to something, but it would be nice if we didn't have to for simple CI checks like this.

![image](https://github.com/withastro/language-tools/assets/19306765/55b8ef46-b30c-42af-ad2f-bd21dc1cd547)

### Steps to Reproduce

1. `npm init astro`
2. add non optional `envField` to astro.config, e.g. 
```ts
schema: {
  PUBLIC_VARIABLE: envField.string({
   context: "server",
   access: "public",
  }),
},
```
3. run `npm run astro check`
4. Error! 
The following environment variables do not match the data type and/or properties defined in `experimental.env.schema`:

Variable PUBLIC_VARIABLE is not of type: string.

### Minimal reproduction

https://stackblitz.com/~/github.com/Trombach/astro-check-test

**Comment by florian-lefebvre** [comment]
I think this is because we check the variables during `buildStart`, and the vite plugin also runs during `astro sync`. I think we need a way to know when it's syncing and avoid throwing errors in this case? What do you think @bluwy?

**Comment by Trombach** [comment]
Thanks for looking into this @Princesseuh and @florian-lefebvre. Yes, I have noticed that `astro sync` shows the same behaviour and it makes sense it behaves this way. I will send a minimal repo later today

**Comment by Trombach** [comment]
@florian-lefebvre I've added a stackblitz to the description

**Comment by bluwy** [comment]
> I think this is because we check the variables during `buildStart`, and the vite plugin also runs during `astro sync`. I think we need a way to know when it's syncing and avoid throwing errors in this case? What do you think @bluwy?

Sounds ok to me, but I'm not sure how to get that info from a plugin. The way we usually handle types file generation though is directly in the sync command:

https://github.com/withastro/astro/blob/e67d7e66a9e9f09b316d87f27d0d9c861b7adca7/packages/astro/src/core/sync/index.ts#L82-L89

So perhaps we should move the env generation there? And the plugin shouldn't be generating any files.
