### ISSUE TITLE
Error type props ts for image component

### ISSUE THREAD

**Issue by SavinDevelop** [withastro/astro#11290]
### Astro Info

```block
Astro                    v4.10.3
Node                     v22.3.0
System                   Linux (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/vue
                         astro-icon
```

### Describe the Bug
Typescript throws an error on the props type for the image component, even though I'm doing everything as described in the documentation.

```javascript
---
import image1 from '@assets/1.jpg';
import { Image } from 'astro:assets';
---
 <Image src={image1.src} alt="image" />
```

```bash
Type '{ src: string; alt: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Type '{ src: string; alt: string; }' is not assignable to type 'IntrinsicAttributes & { [x: `data-${string}`]: any; title?: string | null | undefined; children?: unknown; class?: string | null | undefined; 'class:list'?: string | Record<string, boolean> | Record<...> | Iterable<...> | Iterable<...> | undefined; ... 203 more ...; inferSize?: false | undefined; }'.
```

### What's the expected result?

I want to solve this problem

### Link to Minimal Reproducible Example

None

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Remove `.src` from your code, you're using the syntax for `img` tags, not `Image`.

https://docs.astro.build/en/guides/images/#images-in-astro-files

**Comment by SavinDevelop** [comment]
I feel ashamed of my inattention

**Comment by mrcleanandfresh** [comment]
> I feel ashamed of my inattention

You're not alone. This helped me solve my issue.

**Comment by SavinDevelop** [comment]
> > I feel ashamed of my inattention
> 
> You're not alone. This helped me solve my issue.

I'm glad to be useful
