### ISSUE TITLE
setUpEnvTs writes file even if no changes are needed

### ISSUE THREAD

**Issue by NeoPhi** [withastro/astro#11303]
### Astro Info

```block
Astro                    v4.10.3
Node                     v20.13.1
System                   macOS (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @sentry/astro
```

### Describe the Bug

If `src/env.d.ts` is present but read-only by the user running a build, the build will fail. It seems `setUpEnvTs` will unconditionally rewrite this file even if there are no changes needed. This is problematic for CI/CD situations where the build user is not allowed to modify any files under the `src/` directory.

https://github.com/withastro/astro/blob/dbbd0a22e249bb62d406aed016ed626a651a332d/packages/astro/src/vite-plugin-inject-env-ts/index.ts#L99

### What's the expected result?

No files under `src` are modified if changes are not needed.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Do you have an example of a CI situation where `src` cannot be written?

**Comment by ematipico** [comment]
@NeoPhi is your `env.d.ts` file commit in your repository? 

@florian-lefebvre maybe we could add a check **only during the build**. If the file doesn't exist, we could throw a runtime error saying that the file should be committed. What do you think?

**Comment by florian-lefebvre** [comment]
That sounds reasonable to me, and easy to implement

**Comment by bluwy** [comment]
I suppose there's a risk breaking current setups where the `src/env.d.ts` is not committed, but I'm not sure how common is that. Maybe it would be simpler to not write the file if the file content is the same? Though I also agree with Erika that this is kinda a niche situation.

**Comment by ematipico** [comment]
True, definitely niche, but FS operations are always a big question mark and throw unexpected errors like in this case

**Comment by matthewp** [comment]
You should be able to create a new Astro project, run `astro build` having never run dev and it should work. It sounds like the suggestion here would break that. We don't have many required files in Astro and we shouldn't start adding them, imo. This is definitely a niche situation.

Could we add a `--no-env` or something? It's always been a little "controversial" to create files inside src as some people simply don't like such a thing. Could solve this.

**Comment by NeoPhi** [comment]
Our `env.d.ts` is committed since we added custom entries to support TypeScript as per https://docs.astro.build/en/guides/environment-variables/#intellisense-for-typescript

The `--no-env` suggestion seems like a nice solution, similar to yarn's `--frozen-lockfile`.

**Comment by bluwy** [comment]
@florian-lefebvre is this already fixed from https://github.com/withastro/astro/pull/11415 ? Particularly https://github.com/withastro/astro/blob/904f1e535aeb7a14ba7ce07c3130e25f3e708266/packages/astro/src/core/sync/setup-env-ts.ts#L75-L78

Astro db also has a copy of that, but also does a similar check before write: https://github.com/withastro/astro/blob/904f1e535aeb7a14ba7ce07c3130e25f3e708266/packages/db/src/core/integration/vite-plugin-inject-env-ts.ts#L44-L50

**Comment by florian-lefebvre** [comment]
Yes I believe it should be fixed by this check I added. Would prefer confirmation from the OP before closing

**Comment by bluwy** [comment]
Closing this for now due to lack of response.
