### ISSUE TITLE
transition:persist doesnt work for iframes.

### ISSUE THREAD

**Issue by laurencefass** [withastro/astro#11311]
### Astro Info

```block
Astro                    v4.11.0
Node                     v18.17.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/solid-js
                         @qwikdev/astro
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

chrome

### Describe the Bug

Im working through docs for ViewTransitions. transitions dont appear to work for iframes (at least not with videos in them!)

Ive supplied a github link to [this demo URL](https://astro.syntapse.co.uk) which renders html video element, a react counter, and a youtube iframe. The html video element and the react counter for the most part persist across transitions (not in all cases but Ill investigate separately) Howeve a youtube embed iframe reloads with every page nagvigation. Ive tried wrapping the iframe in a div but it too also reloads the iframe with each navigation.

Im wondering how can I play a youtube video or add embedded content and make good use of transition:persist? 

Is this beyond design scope? Is it not working intentionally? Or is this a bug?

layout

### What's the expected result?

dont know what the expected result is for iframes (bug or intentional?) but I would like to play a youtube video across page navigations.

### Link to Minimal Reproducible Example

https://github.com/laurencefass/syntapse-astro/blob/main/src/layouts/Layout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by laurencefass** [comment]
aha ive just seen this:

![image](https://github.com/withastro/astro/assets/3512857/6453684c-283f-4156-8e87-a558b039aa95)

though i wont close just yet in case there's some news on this being fixed in the future (if ever?)

**Comment by aleclarson** [comment]
Atomic moves via `Node#moveBefore` will fix this: https://developer.chrome.com/blog/movebefore-api

Are there plans to enable this feature in Astro? Alternatively, some kind of workaround when using Astro transitions, if you know of one, would be very appreciated!

**Comment by aleclarson** [comment]
Bumping this thread again as I didn't receive a reply.

*edit:* I created a proposal in the RFC repo: https://github.com/withastro/roadmap/discussions/1263
