### ISSUE TITLE
💡 RFC: Allow multiple public asset directories

### ISSUE THREAD

**Issue by Jeroen-Matthijssens** [withastro/astro#1134]
### Background & Motivation

While some assets are to be committed to version control, some static assets can be the result of a separate build step. Build artifacts are typically not committed to version control. Currently astro only supports a single assets directory. This means we don't have an easy way to differentiate between the different assets. So one would have to:

- Either generate the content in a folder which is under version control and try to ignore these generated files,
- or copy the checked in files into a separated directory and manually listen for files changes to sync the two.

Neither solution is particularly elegant.

### Proposed Solution

The easiest solution would be to allow multiple asset directories in the astro configuration file. The `public` configuration could be either a normal string, or an array of strings. All files in that directory would then be processed as public files, and be included in the build.

```
export default {
  /* ... */
  public: [ './public', './build/generated-assets' ]
};
```

It is possible that multiple directories contain a file with the same name or path, but a simple last one wins strategy could resolve those conflicts.

### Alternatives considered

It is possible to manage this outside of astro, as mentioned before, by either gaming the astro build into using a separate public folder, or gaming the scm system into not tracking the generated assets. There is a third option outside of astro: the different asset folders are combined after the build. 

If the paths match up, since these are all static assets, one could just copy everything into the same folder after the astro build and serve that as is.

### Risks, downsides, and/or tradeoffs

Personally I don't see much risk in this, but then I don't know the project well enough. Conceptually we can threat all the asset directories as slices of hte same logical directory which is the union of all of them. While there is a bit more logic introduced for handling this, the complexity seems very minimal.

There was a mention by @drwpow on a pull request I made suggesting this would be hard to implement with upcoming changes to the engine. But I don't know what those are, or how that would impact the general concept of 'merging' different directories into a single logical one. Someone else could possible expand on that?

### Open Questions

- What would be the impact for future changes to the engine.

### Detailed Design

There is not really much to the implementation or the design,an illustration of the idea at can be found at https://github.com/snowpackjs/astro/pull/1124.

The `AstroConfig.public` configuration option is already normalized to a `URL`, we now normalize it to a `URL[]`. 

- Given  a single string, it will be turned into an array with a single url.
- Given an array of strings, it will be turned into an array of urls.
- If the property is empty, it will be turned into an array with a single url pointing to `./public`.
- Given anything but a string or an array you'll get an error.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by drwpow** [comment]
> There was a mention by @drwpow on a pull request I made suggesting this would be hard to implement with upcoming changes to the engine. But I don't know what those are, or how that would impact the general concept of 'merging' different directories into a single logical one. Someone else could possible expand on that?

Yeah, sure! Apologies for being vague. Essentially in a future update we won’t be using Snowpack’s for serving static files anymore, in favor of an off-the-shelf solution that currently only supports one public folder. So the multiple mounted directories would go away. This would mean adding to Astro’s maintenance by having to build and maintain a static site server that combines multiple directories into one URL structure (or adds multiple instances of our internal static site server that may come with other issues). While there will be more file system lookups for every add’l public directory you add, for all we know that’s a moot performance concern; maintenance is mostly what I want to raise.

---

Also something to consider: with multiple public directories, you increase your chance of accidental collision. Should we throw an error in that case? Or should we only warn and prevent file overwrites (e.g. earlier in the array takes priority)?

**Comment by FredKSchott** [comment]
> maintenance is mostly what I want to raise.

@drwpow I think that's a super valuable point here. Basically, is the benefit of the feature > the cost of long-term maintenance? Number of users impacted is the biggest measure we have for "benefit of the feature", so I think one clear requirement to prioritizing this would be seeing if users (other than yourself) are also looking for this. If this issue gets many 👍 or comments, I think that would be a sign to revisit and consider implementing.

**Comment by FredKSchott** [comment]
Also @Jeroen-Matthijssens  f I remember correctly, it sounded like you may have found a solution by copying that build directory into public? or, was it maybe a symlink? can't remember entirely, but sounds like there might be a few workarounds here available as well

**Comment by Jeroen-Matthijssens** [comment]
@FredKSchott, yes there are a couple of workarounds, but to me they all felt 'hacky'. If astro was able ta handle multiple directories all those problems went away.

@drwpow, If there are collisions in the different directories, a last one wins strategy would be more then workable I'd think. I also don't expect such collisions to be intentional, so raising a warning might help to mitigate any possible inconvenience there.

I completely sympathise with the point amount maintenance.

If I understand correctly, implementing it right now would not be much of a problem, but if this was introduced than that would limit astro's future file servers choices which can be used during development. We don't want to limit options in the future if the feature is not worth it.

Wether it is worth it is not something is not something I can answer. Community consensus is. So I'm eagerly awaiting many thumbs up :+1: :smile:.

**Comment by jasikpark** [comment]
Would it not work to do:

```
public/
|
- normal-assets/
|
- generated-assets/
```

and then add 
```
public/generated-assets/
```
to your .gitignore? since that gets you a similar effect to having two public folders, and you can have version control ignore the important folders!

**Comment by Jeroen-Matthijssens** [comment]
@jasikpark That would put the generated content in the public directory, but it would also place that content under that path. That may not match with the path structure needed for the generated content.

It wolud also place all normal assets under `normal-asets`, though that would be easily fixed, you can still use public for normal assets and just ignore `./public/generated-assets`.

The major downside is that you would see urls like `http://example.com/generated-assets/som/path/to/file.ext`.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat

**Comment by azat-io** [comment]
This plugin works for me: https://github.com/sapphi-red/vite-plugin-static-copy
Thanks to @sapphi-red

**Comment by nguyenbatranvan** [comment]
check my lib!!
[vite-multiple-assets](https://www.npmjs.com/package/vite-multiple-assets?activeTab=readme)

```
import {AstroIntegration} from "vite-multiple-assets";
const assets = ["libs/assets", "repo1/assets", ...];
export default defineConfig({
    integrations: [
        AstroIntegration(assets)
    ],
});

```
- The above configuration will automatically add files in `public`, `libs/assets`, `repo1/assets` folders as static assets for your project, which can be understood as below:

```
export default defineConfig({
   // default is public folder
   publicDir:["public","libs/assets","repo1/assets",...]
 })
```
