### ISSUE TITLE
npm install @astrojs/check typescript ?

### ISSUE THREAD

**Issue by J-env** [withastro/astro#11344]
### Astro Info

```block
Astro                    v4.11.2
Node                     v18.18.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/vue
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

It's already installed, why is it still prompting?

<img width="867" alt="image" src="https://github.com/withastro/astro/assets/25259920/3ff5cf37-7c86-4cf3-96d0-5f4631324672">

<img width="475" alt="image" src="https://github.com/withastro/astro/assets/25259920/6176fefb-28e1-461f-9ff1-eded2170d483">

### What's the expected result?

Dependencies already installed.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Is this happening only on the latest version? I may have messed something up in https://github.com/withastro/astro/pull/11331 😬 I'll take a look at this later
