### ISSUE TITLE
Script handles problems

### ISSUE THREAD

**Issue by olcchi** [withastro/astro#11357]
### Astro Info

```block
no info in terminal .
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

When I follow the official Three.js documentation to include Three.js using the 
```js
<script type="importmap">
  {
    "imports": {
      "three": "https://cdn.jsdelivr.net/npm/three@<version>/build/three.module.js",
      "three/addons/": "https://cdn.jsdelivr.net/npm/three@<version>/examples/jsm/"
    }
  }
</script>
```
script CDN, I need to explicitly add <script type="module"> on the script tag when using Three.js in other Astro components. However, I noticed a section in the Astro documentation about script parsing, `"The processed script will be injected into your page’s <head> with [type="module"]"`, which confuses me. Is this a bug?

### What's the expected result?

I have never explicitly used `<script type="module">` in Astro components before, but in this particular issue, I can only avoid errors by doing so. Is this the right approach?

### Link to Minimal Reproducible Example

https://github.com/olcchi/3/blob/main/src/pages/index.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
This one is a bit tricky but is actually logic. By default, astro scripts are processed: you can use TS and import packages from npm. However in this case you don't want that since you use imports maps. What you want is an inline script (ie. that opts out of processing). I think you can do this (the type module may still be required idk, try without it first):

```diff
- <script type="module">
+ <script is:inline>
```

Let me know if it works for you!

**Comment by bluwy** [comment]
I think you'd still need the `type="module"` so that gets added in the output, which is needed because importmaps only work with ESM imports.

The better way I think is to still npm install threejs so its code could be treeshaken and doesn't rely on third party scripts.

**Comment by olcchi** [comment]
> This one is a bit tricky but is actually logic. By default, astro scripts are processed: you can use TS and import packages from npm. However in this case you don't want that since you use imports maps. What you want is an inline script (ie. that opts out of processing). I think you can do this (the type module may still be required idk, try without it first):
> 
> ```diff
> - <script type="module">
> + <script is:inline>
> ```
> 
> Let me know if it works for you!

hi！Florian

Actually, what I initially tried was using <script is:inline> to avoid Astro processing the script. While this did prevent the editor from reporting errors, the browser console would then report an error saying `"SyntaxError: Cannot use import statement outside a module"`. Another method I tried was` <script type='module' is:inline>`, and in this case, the program ran correctly. It seems the key is to add type='module' to the script tag.
In most cases, I add libraries by downloading npm packages. This error only occurred when I tried to use a CDN to import third-party libraries. It seems something is happening here that doesn't align with the official documentation, which has left me a bit confused. That's why I wanted to seek some knowledge. Once again, thank you for your response.

**Comment by olcchi** [comment]
> I think you'd still need the `type="module"` so that gets added in the output, which is needed because importmaps only work with ESM imports.
> 
> The better way I think is to still npm install threejs so its code could be treeshaken and doesn't rely on third party scripts.

Hi, Bluwy,
Actually, in most cases during development, I use npm packages to import third-party libraries. Many frameworks and tools also assume that developers will use this method to import third-party libraries.
This issue arose when I insisted on trying to use a CDN to import third-party libraries. In reality, it is a rare occurrence and does not affect the use of Astro. However, I believe I encountered a situation that does not align with the official documentation, which left me feeling confused. That's why I wanted to seek some knowledge. Thank you for your response.

**Comment by florian-lefebvre** [comment]
I think the banner at https://docs.astro.build/en/guides/client-side-scripts/#opting-out-of-processing addresses exactly your question. In general, we recommend you add is:inline even if it's inferred (eg. by type="module") for clarity

**Comment by bluwy** [comment]
I think we can close this. Florian's last comment explains the current behaviour
