### ISSUE TITLE
Using Astro Actions causes Build Error

### ISSUE THREAD

**Issue by hkbertoson** [withastro/astro#11354]
### Astro Info

```block
Astro                    v4.11.3
Node                     v20.15.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         astro-icon
                         @astrojs/react
```

### Describe the Bug

When actions are enabled. Project does not build

### What's the expected result?

Project should build

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-tpp1b5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
cc @bholmesdev

**Comment by bholmesdev** [comment]
Hi @hkbertoson, thanks for reporting! I see you're using the Cloudflare adapter. Did you try the following?

1. [Add the `nodejs_als` flag](https://developers.cloudflare.com/workers/runtime-apis/nodejs#enable-only-asynclocalstorage) to your wrangler config. This allows a Node-specific API that actions relies on

```toml
# wrangler.toml
compatibility_flags = [ "nodejs_als" ]
```

2. [Mark this Node API as external](https://docs.astro.build/en/guides/integrations-guide/cloudflare/#nodejs-compatibility) in your vite config:

```ts
import {defineConfig} from "astro/config";
import cloudflare from '@astrojs/cloudflare';

export default defineConfig({
  adapter: cloudflare({}),
  output: 'server',
  vite: {
    ssr: {
      external: ['node:async_hooks'],
    },
  },
})
```

I was also unable to reproduce this bug with the node adapter as @alexanderniebuhr noted above. If you can share a minimal reproduction with the node adapter that displays this issue, please share!

**Comment by alexanderniebuhr** [comment]
@bholmesdev I just took that assumption based on screenshots from here https://discord.com/channels/830184174198718474/1255555330646216785

**Comment by ematipico** [comment]
I am going to raise the priority of this issue, because the project doesn't even build with the Node.js adapter.

**Comment by dgurns** [comment]
Just confirming that I ran into the original error in this issue -- failed build when using Astro Actions, related to `node:async_hooks`, and @bholmesdev's fix [here](https://github.com/withastro/astro/issues/11354#issuecomment-2194365696) solved it for me.
