### ISSUE TITLE
Issue with FOUC when moving from home page to other pages and vice versa. 

### ISSUE THREAD

**Issue by Albertyhu** [withastro/astro#11368]
### Astro Info

```block
Astro                    v4.11.0
Node                     v18.17.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/tailwind
                         @astrojs/react
                         @astrojs/sitemap
                         astro-robots-txt
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

I've built a website using the Astro framework. 
url: https://www.mordecai-law.com/

Issues with FOUC appears when clicking from the home page to the inner pages and vice versa. 
This likely happens on Chrome. 

Check the video below to see what I am describing: 
[Library | Loom - 27 June 2024 - Watch Video](https://www.loom.com/share/49f048d22f3b46d5957ae5687b0896a1)

I did disable View Transitions, but that did not solve the problem. 

### What's the expected result?

A smooth navigation experience with no FOUC specifically on the Chrome browser. 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/Albertyhu/eli-mordecai?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Hi! This is not a minimal reproduction since it's your whole project. That being said, I understand the issue is probably caused by some specific aspects of your project. Either provide a minimal reproduction or seek support on our official Discord server https://astro.build/chat
