### ISSUE TITLE
If the -- open flag is used, any modifications to the packagist.json file will reopen the browser at this time

### ISSUE THREAD

**Issue by ajiho** [withastro/astro#11374]
### Astro Info

```block
unnecessary
```

### If this issue only occurs in one browser, which browser is a problem?

chrome

### Describe the Bug

If the -- open flag is used in the development script, every time the package.json file browser is modified, it will open a new tab
script:
```
"dev": "astro --config src/config/astro.config.mjs dev --open",
```

Here is a more detailed video demonstration：

https://github.com/withastro/astro/assets/107699138/5d8aa80e-4d94-4679-9aae-d38f32319941

Warehouse for reproducing examples：
https://github.com/ajiho/astro-build-boilerplate

### What's the expected result?

The correct behavior should be to modify package.json, which should not have any response，I don't know if it's an issue with Astro or Vite regarding the occurrence of this behavior，If there are no issues with both, please tell me what to do? I have ensured that my vscdoe editor does not have any extensions that may affect it，
![image](https://github.com/withastro/astro/assets/107699138/35beb7ae-60e0-40e4-8b9f-ac7b379f90b2)

### Link to Minimal Reproducible Example

https://github.com/ajiho/astro-build-boilerplate

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
I _think_ that's because we do a full restart of the vite dev server each time a config file changes, so we tell vite to open a browser tab each time. @bluwy what do you think we should do?

**Comment by ajiho** [comment]
@florian-lefebvre I have also provided feedback on this issue in vitepress based on vite, and they also have this issue, but they have already resolved it，[issues/4001](https://github.com/vuejs/vitepress/issues/4001) I think you can refer to how it was resolved

**Comment by ajiho** [comment]
Sorry, I can't be of much help. I just want to humbly ask the Astro team if this issue is difficult to handle? I'm just troubled by opening a new tab every time I modify packagejson.

**Comment by florian-lefebvre** [comment]
## Good first issue!
This is an opportunity for astro users to learn about how astro works by fixing a small but real bug. You can expect to get help setting up the dev environment, and understanding the project structure in `#contribute` channel of our discord server (https://astro.build/chat). 

### What's the bug?
In development when using `astro dev --open`, updating a config file reopens a new tab.

### What's going wrong here?
When a config file changes, a full restart happens and the Vite dev server is recreated. That means a new tab will reopen each time.

### Where do I start looking?
[This condition](https://github.com/withastro/astro/blob/main/packages/astro/src/core/dev/container.ts#L61) needs to be updated. You'll need to use the `isRestart` parameter and test manually

**Comment by RickyC0626** [comment]
I can take a look
