### ISSUE TITLE
astro:env does not generate .astro/env.d.ts in develoment mode

### ISSUE THREAD

**Issue by xino1010** [withastro/astro#11380]
### Astro Info

- astro: 4.11.3
- node: 18.18.2

Using last experimental type-safe environment variables features, types are not generated automatically in development mode.

```typescript
import { getSecret } from "astro:env/server";
```

Cannot find module 'astro:env/server' or its corresponding type declarations.ts(2307)

I have to execute

```bash
npm run build
````

to remove the ts error.

### Describe the Bug

Code works but intellisense show an error.

![Captura de pantalla 2024-06-30 a las 9 34 13](https://github.com/withastro/astro/assets/7092367/1a03a20d-f591-46db-8035-82a16c448606)

Looking the file `env.d.ts`

```typescript
/// <reference path="../.astro/env.d.ts" />
/// <reference types="astro/client" />
```

new line is added but the file is not generated under  `.astro` folder.

Same happens for backend vars.

![Captura de pantalla 2024-06-30 a las 9 45 17](https://github.com/withastro/astro/assets/7092367/d4561007-7bab-4412-972c-9613ca1be23d)

but if you execute `npm run build`, the error dissapears because typings file is generated.

### What's the expected result?

Generate automatically `env.d.ts` file on develoment mode.

```typescript
declare module "astro:env/client" {
  export const API_URL: string;
}

declare module "astro:env/server" {
  export const DB_HOST: string;
  export const DB_NAME: string;
  export const DB_PASS: string;
  export const DB_PORT: number;
  export const DB_USER: string;

  export const getSecret: (key: string) => string | undefined;
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ey4hsq?file=.env

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mogeko** [comment]
You should run `astro sync`.

**Comment by xino1010** [comment]
> You should run `pnpm astro sync`.

should it be the expected behaviour? or astro could be generated on dev mode?

**Comment by florian-lefebvre** [comment]
Yes dev should run sync under the hood so there may be a bug, I'll have a look

**Comment by florian-lefebvre** [comment]
I think the issue lies here https://github.com/withastro/astro/blob/main/packages/astro/src/core/sync/index.ts#L87. If there are no content collections, the env sync code may not be run. @xino1010 do you want to try fixing it?

**Comment by ematipico** [comment]
Ah yeah, that's because `sync` was originally meant for content collections. Now we are change its semantics, so we should remove that check at this point, or add an OR check for `astro:env`

**Comment by xino1010** [comment]
> I think the issue lies here https://github.com/withastro/astro/blob/main/packages/astro/src/core/sync/index.ts#L87. If there are no content collections, the env sync code may not be run. @xino1010 do you want to try fixing it?

No sorry, it exceed of my knowledge

**Comment by Trombach** [comment]
@florian-lefebvre I'm happy to submit a PR for this if that's ok?

**Comment by florian-lefebvre** [comment]
@Trombach sure do it! Feel free to reach out on Discord in `#contribute` if you need help

**Comment by nemanjam** [comment]
I get this too, they are simply undefined, I use `"astro": "^4.14.4"`.


![image](https://github.com/user-attachments/assets/4e7111b9-2a0d-45a7-89d8-a789c981fa40)

`yarn dev`, `yarn sync`, `yarn build` all of them fail.

```
username@computer3:~/Desktop/nemanjam.github.io$ yarn sync
yarn run v1.22.22
$ astro sync
8:47:02 AM [vite] Pre-transform error: Failed to load url astro:env/client (resolved id: astro:env/client) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
8:47:02 AM [vite] Pre-transform error: Failed to load url astro:env/server (resolved id: astro:env/server) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?



username@computer3:~/Desktop/nemanjam.github.io$ yarn build
yarn run v1.22.22
$ astro build
8:47:08 AM [vite] Pre-transform error: Failed to load url astro:env/client (resolved id: astro:env/client) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
8:47:08 AM [vite] Pre-transform error: Failed to load url astro:env/server (resolved id: astro:env/server) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
8:47:08 AM [vite] Pre-transform error: Failed to load url @/schemas/config (resolved id: @/schemas/config) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?


username@computer3:~/Desktop/nemanjam.github.io$ yarn dev
yarn run v1.22.22
$ astro dev
8:45:00 AM [vite] Pre-transform error: Failed to load url astro:env/client (resolved id: astro:env/client) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
8:45:00 AM [vite] Pre-transform error: Failed to load url astro:env/server (resolved id: astro:env/server) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
8:45:00 AM [vite] Pre-transform error: Failed to load url @/schemas/config (resolved id: @/schemas/config) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
8:45:00 AM [vite] Pre-transform error: Failed to load url @/utils/log (resolved id: @/utils/log) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
8:45:00 AM [vite] Pre-transform error: Failed to load url @/utils/validation (resolved id: @/utils/validation) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
8:45:00 AM [vite] Error when evaluating SSR module /src/config.ts: failed to import "astro:env/client"
|- Error: Cannot find module 'astro:env/client' imported from '/home/username/Desktop/nemanjam.github.io/src/config.ts'
    at nodeImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52945:19)
    at ssrImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:22)
    at eval (/home/username/Desktop/nemanjam.github.io/src/config.ts:3:50)
    at instantiateModule (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:11)

```

**Comment by florian-lefebvre** [comment]
@nemanjam 👋 Can you open a new issue? Thank you!

**Comment by Ellmon** [comment]
> ### Astro Info
> 
> 
> 
> - astro: 4.11.3
> 
> - node: 18.18.2
> 
> 
> 
> Using last experimental type-safe environment variables features, types are not generated automatically in development mode.
> 
> 
> 
> 
> 
> ```typescript
> 
> import { getSecret } from "astro:env/server";
> 
> ```
> 
> 
> 
> 
> 
> Cannot find module 'astro:env/server' or its corresponding type declarations.ts(2307)
> 
> 
> 
> I have to execute
> 
> 
> 
> ```bash
> 
> npm run build
> 
> ````
> 
> 
> 
> to remove the ts error.
> 
> 
> 
> ### If this issue only occurs in one browser, which browser is a problem?
> 
> 
> 
> _No response_
> 
> 
> 
> ### Describe the Bug
> 
> 
> 
> Code works but intellisense show an error.
> 
> 
> 
> ![Captura de pantalla 2024-06-30 a las 9 34 13](https://github.com/withastro/astro/assets/7092367/1a03a20d-f591-46db-8035-82a16c448606)
> 
> 
> 
> Looking the file `env.d.ts`
> 
> 
> 
> ```typescript
> 
> /// <reference path="../.astro/env.d.ts" />
> 
> /// <reference types="astro/client" />
> 
> ```
> 
> 
> 
> new line is added but the file is not generated under  `.astro` folder.
> 
> 
> 
> Same happens for backend vars.
> 
> 
> 
> ![Captura de pantalla 2024-06-30 a las 9 45 17](https://github.com/withastro/astro/assets/7092367/d4561007-7bab-4412-972c-9613ca1be23d)
> 
> 
> 
> but if you execute `npm run build`, the error dissapears because typings file is generated.
> 
> 
> 
> ### What's the expected result?
> 
> 
> 
> Generate automatically `env.d.ts` file on develoment mode.
> 
> 
> 
> ```typescript
> 
> declare module "astro:env/client" {
> 
>   export const API_URL: string;
> 
> }
> 
> 
> 
> declare module "astro:env/server" {
> 
>   export const DB_HOST: string;
> 
>   export const DB_NAME: string;
> 
>   export const DB_PASS: string;
> 
>   export const DB_PORT: number;
> 
>   export const DB_USER: string;
> 
> 
> 
>   export const getSecret: (key: string) => string | undefined;
> 
> }
> 
> ```
> 
> 
> 
> ### Link to Minimal Reproducible Example
> 
> 
> 
> https://stackblitz.com/edit/withastro-astro-ey4hsq?file=.env
> 
> 
> 
> ### Participation
> 
> 
> 
> - [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Hi @Ellmon this issue is very old, can you open a new one? Thank you
