### ISSUE TITLE
Drop node v21, add node v22? (minor)

### ISSUE THREAD

**Issue by mrienstra** [withastro/astro#11382]
The `engines` fields in the various* `package.json` files currently have:

```json
  "engines": {
    "node": "^18.17.1 || ^20.3.0 || >=21.0.0"
  },
```

As per https://nodejs.org/en/about/previous-releases#release-schedule, seems like it's about time to replace v21 with v22?

Oh, hmm, reading https://docs.astro.build/en/upgrade-astro/#support, kinda seems like v22 won't be added until it is the current LTS (scheduled for November-ish), is that right?

Very minor, not particularly high priority, just thought I'd call it out.

Related PR: https://github.com/withastro/astro/pull/10689 (bumped `v18.14.1` to `v18.20.1`)

---

*: There are 13 `package.json` files, they all have the same `"node"`  field, but `packages/astro/package.json` also adds ranges for `npm` & `pnpm`:

```json
  "engines": {
    "node": "^18.17.1 || ^20.3.0 || >=21.0.0",
    "npm": ">=9.6.5",
    "pnpm": ">=7.1.0"
  },
```

**Comment by ematipico** [comment]
As you said, we won't add v22 until it goes in LTS. What's the issue for?
