### ISSUE TITLE
Nested routing hijacks `href`

### ISSUE THREAD

**Issue by alvinometric** [withastro/astro#11389]
### Astro Info

```block
Astro                    v4.11.3
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When using nested routing, the value of the `href` attribute in links is different to what's provided.

Example: Given `/ev/tesla`, the actual value of the `href` attribute in the browser is `/ev/ev/tesla`.

I haven't found a way around it, I tried using relative paths to no avail.

### What's the expected result?

I expect the `href` attribute not to change.

Example: Given `/ev/tesla`, the actual value of the `href` attribute in the browser should be `/ev/tesla`.'

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-prspxr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@alvinometric can you please add some instruction to the reproduction? I opened it, and I really don't understand what I am supposed to do to trigger the error.

You mention `href`, but I don't understand where it comes from. Is there something about docs that I missed? Please provide better info for us, so we can help you

**Comment by alvinometric** [comment]
@ematipico Sorry I didn't realise that Stackblitz would default to the readme.
If you click on the first link then on any of the links after that, the `href` is wrong for all the links, despite the correct `href` getting logged to the console.

Here's a video: https://www.loom.com/share/c63819a9d3ef4a34ac1f2776d1487cd6
