### ISSUE TITLE
Improved astro:env errors

### ISSUE THREAD

**Issue by xino1010** [withastro/astro#11381]
### Astro Info

```block
- astro: 4.11.3
- node: 18.18.2
```

### Describe the Bug

- Use last experimental type-safe environment variables features and define an env var in `astro.config.mjs`.

```javascript
import { defineConfig, envField } from "astro/config";

import node from "@astrojs/node";

// https://astro.build/config
export default defineConfig({
  experimental: {
    env: {
      schema: {
        ...,
        DB_PASS: envField.string({
          context: "server",
          access: "secret",
        }),
        ...,
      },
    },
  },
  output: "server",
  adapter: node({
    mode: "standalone",
  }),
});
```

Use the env var, for example,`src/data-source.ts`.

```typescript
import { DB_HOST, DB_NAME, DB_PASS, DB_PORT, DB_USER } from "astro:env/server";
import { DataSource } from "typeorm";
import { Todo } from "./entities/todo";

const dataSource: DataSource = new DataSource({
  type: "mysql",
  host: DB_HOST,
  port: DB_PORT,
  username: DB_USER,
  password: DB_PASS,
  database: DB_NAME,
  entities: [Todo],
  synchronize: true,
  logging: false,
});

export const getDataSource = async (): Promise<DataSource> => {
  if (!dataSource.isInitialized) {
    try {
      await dataSource.initialize();
    } catch (e) {
      console.error("Failed to initialize data source", e);
      process.exit(1);
    }
  }
  return dataSource;
};
```

- Build the project.

```bash
npm run build
```

- Launch the project.

```bash
npm run preview
```

- Node throw an error

```bash
22:14:07 [ERROR] EnvInvalidVariable: The following environment variable does not match the data type and/or properties defined in `experimental.env.schema`: DB_NAME is not of type string
    at createInvalidVariableError (file:///Users/dani/git/astro-dummy/dist/server/chunks/astro/env-setup_K_VhW_hQ.mjs:134:10)
    at _internalGetSecret (file:///Users/dani/git/astro-dummy/dist/server/chunks/data-source_DM7eOVU6.mjs:66:8)
    at file:///Users/dani/git/astro-dummy/dist/server/chunks/data-source_DM7eOVU6.mjs:78:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Defining the var with access `public`, there is not error:

```javascript
import { defineConfig, envField } from "astro/config";

import node from "@astrojs/node";

// https://astro.build/config
export default defineConfig({
  experimental: {
    env: {
      schema: {
        ...,
        DB_PASS: envField.string({
          context: "server",
          access: "public",
        }),
        ...,
      },
    },
  },
  output: "server",
  adapter: node({
    mode: "standalone",
  }),
});
```

### What's the expected result?

Launch the application without any error.

### Link to Minimal Reproducible Example

https://github.com/xino1010/astro-env-example

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
The reproduction does not show this issue, please update it

**Comment by xino1010** [comment]
@florian-lefebvre [here](https://github.com/xino1010/astro-env-example) you'll find an example to reproduce the bug.

**Comment by florian-lefebvre** [comment]
I think this is because at https://github.com/withastro/astro/blob/main/packages/integrations/node/src/server.ts#L11 (and same for vercel and netlify), `process.env` is not loaded with `.env`. Maybe we should call `loadEnv`? @ematipico

**Comment by ematipico** [comment]
> I think this is because at [`main`/packages/integrations/node/src/server.ts#L11](https://github.com/withastro/astro/blob/main/packages/integrations/node/src/server.ts?rgh-link-date=2024-07-02T11%3A54%3A57Z#L11) (and same for vercel and netlify), `process.env` is not loaded with `.env`. Maybe we should call `loadEnv`? @ematipico

Should we? `astro preview` is meant to run a production-like server, and I doubt users will use `.env` to load their secrets in production. Those secrets should injected via `process.env`. In this particular case, the secret should be passed like this

```shell
CHAT_GPT_SECRET=123456 astro preview
```

**Comment by xino1010** [comment]
> > I think this is because at [`main`/packages/integrations/node/src/server.ts#L11](https://github.com/withastro/astro/blob/main/packages/integrations/node/src/server.ts?rgh-link-date=2024-07-02T11%3A54%3A57Z#L11) (and same for vercel and netlify), `process.env` is not loaded with `.env`. Maybe we should call `loadEnv`? @ematipico
> 
> Should we? `astro preview` is meant to run a production-like server, and I doubt users will use `.env` to load their secrets in production. Those secrets should injected via `process.env`. In this particular case, the secret should be passed like this
> 
> ```shell
> CHAT_GPT_SECRET=123456 astro preview
> ```

Maybe we're talking about two different things:
- if a variable is defined as a secret, this one should be available using types in the code.
```javascript
import { defineConfig, envField } from "astro/config";

import node from "@astrojs/node";

// https://astro.build/config
export default defineConfig({
  output: "server",
  adapter: node({
    mode: "standalone",
  }),
  experimental: {
    env: {
      schema: {
        CHAT_GPT_KEY: envField.string({
          context: "server",
          access: "secret",
        }),
      },
    },
  },
});

```

```typescript
---
import { CHAT_GPT_KEY } from "astro:env/server";
console.log(CHAT_GPT_KEY);
---
```


- as I understood `getSecret` function can be used to get the value of an env var not defined in `astro.config.mjs`.

so the issue here is, in preview and build mode, the secret var is not accessible.

```bash
11:18:15 [ERROR] EnvInvalidVariable: The following environment variable does not match the data type and/or properties defined in `experimental.env.schema`: CHAT_GPT_KEY is not of type string
```

**Comment by florian-lefebvre** [comment]
Yeah I agree errors need improvements, regarding what validation rule is failing exactly (eg. startsWith)
