### ISSUE TITLE
🐛 BUG: [ERROR] The build was canceled

### ISSUE THREAD

**Issue by simonwinter** [withastro/astro#11390]
### Describe the Bug

I've just encountered a similar error with astro `4.11.3` and astro-check `0.7.0` as the closed error withastro/language-tools#757 - namely I would get the following when running `astro check`:

```
➜ yarn build
22:55:33 [types] Added src/env.d.ts type declarations.
✘ [ERROR] The build was canceled

22:55:33 [types] Added src/env.d.ts type declarations.
22:55:33 Types generated 361ms
22:55:33 [check] Getting diagnostics for Astro files in /Users/simon/astro-website...
Result (2 files):
- 0 errors
- 0 warnings
- 0 hints
```

Note: for brevity, I've changed the build command to simply `astro check`, not `astro check && astro build`

**Solution?**

After much digging, I found that I had an empty `content` directory (i.e. a directory with no files inside). Removing it and running the command again solved this issue.

### Steps to Reproduce

Using yarn berry (4.3.1):

1. `yarn install`
2. `yarn build`
5. Error! The build says it's canceled, but carries on regardless.

**Comment by ematipico** [comment]
@simonwinter could you please create a reproduction for us?

**Comment by merlinschumacher** [comment]
I have the issue as well. The error disappears, when you clear out the content directory.
