### ISSUE TITLE
create-astro does not work

### ISSUE THREAD

**Issue by christianahvilla** [withastro/astro#11396]
### Astro Info

```block
Astro                    v4.11.3
Node                     v20.3.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When I run `npm create astro@latest` and follow the instructions, I get the following error and the installation fails:

```
astro   Launch sequence initiated.

╭─────╮  Houston:
│ ◠ ◡ ◠  I'll be your assistant today.

 astro   Launch sequence initiated.

   dir   Where should we create your new project?
         ./regular-resonance

  tmpl   How would you like to start your new project?
         Include sample files

    ts   Do you plan to write TypeScript?
         Yes

   use   How strict should TypeScript be?
         Strict

  deps   Install dependencies?
         Yes

   git   Initialize a new git repository?
         Yes

 ██████  Project initializing...
         ▶ Template copying...
         □ TypeScript
         □ Dependencies
         □ Git
      ▲  error fetch failed

```

### What's the expected result?

An Astro project was created correctly 

### Link to Minimal Reproducible Example

no avaiable 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lkzwc** [comment]
什么问题呀 感觉挂了么
![image](https://github.com/withastro/astro/assets/84896877/4f1adce2-5544-4e7a-b167-2c99ea75f8a0)

**Comment by christianahvilla** [comment]
> 什么问题呀 感觉挂了么 ![image](https://private-user-images.githubusercontent.com/84896877/345279760-4f1adce2-5544-4e7a-b167-2c99ea75f8a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODI0MjMsIm5iZiI6MTcxOTk4MjEyMywicGF0aCI6Ii84NDg5Njg3Ny8zNDUyNzk3NjAtNGYxYWRjZTItNTU0NC00ZTdhLWIxNjctMmM5OWVhNzVmOGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA0NDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZTVmOTEyZWJjMjdhNjJjZjIyNDIwMGI3MTA4NmI3YTE2NzNiMGY0MTU1NjBkY2RmNDc4YmVjYTM3MmJhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kCFxkdF67aw5rPJAxhg1a-Iz2GPJv1p9CDqgErRStjA)

I have the same issue, I tried on another WSL, on my local machine but they did not work, what processor do you have?

**Comment by florian-lefebvre** [comment]
Maybe linked to #11314

**Comment by Princesseuh** [comment]
It's hard to tell what the underlying issue is here, and probably that it's not really fixable (firewall things, connection issues etc), but we should surface the error better.

**Comment by Thiago2104** [comment]
I have the same issue, I tried with node v18.17.1, windows and it stays loading in the `template copying` with every option (use sample files, use blog template and empty). Also tried with `npm create astro@4` (it installed version 4.8) to check an older version, with the same result.
