### ISSUE TITLE
Image is not rendering from mobile devices on an astro-built Github Pages website

### ISSUE THREAD

**Issue by renardeinside** [withastro/astro#11397]
### Astro Info

```block
Astro                    v4.11.3
Node                     v20.11.1
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/mdx
                         @astrojs/svelte

Astro config:

import { defineConfig } from 'astro/config';
import tailwind from "@astrojs/tailwind";
import mdx from "@astrojs/mdx";

import svelte from "@astrojs/svelte";

// https://astro.build/config
export default defineConfig({
  integrations: [tailwind(), mdx(), svelte()],
  site: 'https://renardeinside.github.io',
});
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome and Safari on Iphone

### Describe the Bug

The image is not showing in mobile browsers (see screenshot below)

Code is [here](https://github.com/renardeinside/renardeinside.github.io), specifically:

https://github.com/renardeinside/renardeinside.github.io/blob/60fb9e4cce80d66a12fc4636bd85af975671d386/src/pages/index.astro#L13

![telegram-cloud-photo-size-2-5197370836225480934-y](https://github.com/withastro/astro/assets/4979594/d8fce58e-6f3f-449b-ad6e-08d853b5257e)

### What's the expected result?

Image is visible in mobile browsers exactly as it's visible in dev and desktop ones.

### Link to Minimal Reproducible Example

https://renardeinside.github.io/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I can't replicate the issue. I can the image from Firefox and Chrome (for Android).

**Comment by ematipico** [comment]
I'm not sure to be honest. Did you build and preview the site locally? Can you see the image? 

If so, it could be something related to the host. Did you check if you get some status code for that particular image?
