### ISSUE TITLE
dark mode shiki config in mdx

### ISSUE THREAD

**Issue by j-mendez** [withastro/astro#11406]
### Astro Info

```block
Astro                    v4.11.4
Node                     v22.1.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/react
                         @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/mdx
```

### Describe the Bug

Dark mode is not respected when using markdown or mdx to render code.

```js
const shikiConfig = {
	wrap: true,
	themes: {
		light: 'slack-ochin',
		dark: 'dracula-soft',
	},
	defaultColor: false,
};
```

### What's the expected result?

Astro respect the `.dark` class and shiki theme.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-x6rs8v?file=src%2Fpages%2Fapi%2Fmethods.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by zhuozhiyongde** [comment]
https://www.reddit.com/r/astrojs/comments/1cbz6ti/how_to_change_shiki_light_and_dark_themes/

**Comment by bluwy** [comment]
You're using `defaultColor: false`, which means there's no color rendered by default. You need to use CSS to enable it. See https://shiki.style/guide/dual-themes#without-default-color
