### ISSUE TITLE
Missing "./stream-node" specifier in "preact-render-to-string" package

### ISSUE THREAD

**Issue by jorgefranciscogil** [withastro/astro#11403]
### Astro Info

```block
Astro                    v4.11.3
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/preact
                         @astrojs/react
```

### Describe the Bug

Recurrent error when I try to configure both integrations, preact and react with compatibility.

```javascript
export default defineConfig({
  integrations: [
    preact({
      include: ['**/preact/*'],
      compat: true,
    }),
    react({
      include: ['**/react/*'],
    }),
  ],
});
```

I got it when configure only the _preact_ integration but not both.

IMPORTANT: there is A PREVIOUS ISSUE. Before this, when I trie to install dependencies with overrides like:

```
"overrides": {
  "react": "npm:@preact/compat@latest",
  "react-dom": "npm:@preact/compat@latest"
},

```
npm launch this error:

0 verbose cli /Users/jfgc/.nvm/versions/node/v20.12.2/bin/node /Users/jfgc/.nvm/versions/node/v20.12.2/bin/npm
1 info using npm@10.7.0
2 info using node@v20.12.2
3 silly config:load:file:/Users/jfgc/.nvm/versions/node/v20.12.2/lib/node_modules/npm/npmrc
4 silly config:load:file:/Users/jfgc/Documents/_pocs/astro/preact-react.astro/.npmrc
5 silly config:load:file:/Users/jfgc/.npmrc
6 silly config:load:file:/Users/jfgc/.nvm/versions/node/v20.12.2/etc/npmrc
7 verbose title npm i
8 verbose argv "i"
9 verbose logfile logs-max:10 dir:/Users/jfgc/.npm/_logs/2024-07-03T10_31_50_226Z-
10 verbose logfile /Users/jfgc/.npm/_logs/2024-07-03T10_31_50_226Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 verbose stack Error: Override for react@^18.3.1 conflicts with direct dependency
13 verbose stack     at Node.assertRootOverrides (/Users/jfgc/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1334:29)
13 verbose stack     at #loadActual (/Users/jfgc/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-actual.js:133:24)
13 verbose stack     at async Promise.all (index 0)
13 verbose stack     at async Arborist.reify (/Users/jfgc/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
13 verbose stack     at async Install.exec (/Users/jfgc/.nvm/versions/node/v20.12.2/lib/node_modules/npm/lib/commands/install.js:150:5)
13 verbose stack     at async module.exports (/Users/jfgc/.nvm/versions/node/v20.12.2/lib/node_modules/npm/lib/cli/entry.js:74:5)
14 verbose cwd /Users/jfgc/Documents/_pocs/astro/preact-react.astro
15 verbose Darwin 21.6.0
16 verbose node v20.12.2
17 verbose npm  v10.7.0
18 error code EOVERRIDE
19 error Override for react@^18.3.1 conflicts with direct dependency
20 verbose exit 1
21 verbose code 1
22 silly unfinished npm timer reify 1720002710421
23 silly unfinished npm timer reify:loadTrees 1720002710423
24 silly unfinished npm timer idealTree 1720002710423
25 silly unfinished npm timer idealTree:init 1720002710423
26 error A complete log of this run can be found in: /Users/jfgc/.npm/_logs/2024-07-03T10_31_50_226Z-debug-0.log

### Conclusion
It's so difficult config react and preact at same time.

### What's the expected result?

I expect the framework to differentiate between react and preact components according to location and to be compatible with each other or in one direction (react components compatible with preact).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hsjysn?file=package.json,astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Preact compat is all or nothing. If you attempt to use it, you will only use Preact and can't use React alongside of it. So that particular feature extends outside of your `include` path. See https://github.com/preactjs/preset-vite
