### ISSUE TITLE
Astro Actions: "Error: Unable to get API context." when is sended arguments to an action.

### ISSUE THREAD

**Issue by ynhhoJ** [withastro/astro#11423]
### Astro Info

```block
Astro                    v4.11.5
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/preact
```

### If this issue only occurs in one browser, which browser is a problem?

Firefox

### Describe the Bug

I followed example from [Actions Proposal](https://github.com/withastro/roadmap/blob/actions/proposals/0046-actions.md) and everytime when is called an action with arguments like:
```js
await actions.like({ postId })
```

Is returned error: ` Uncaught (in promise) Error: Unable to get API context.`  and `500` HTTP Status

But if we do:
```js
await actions.like()
```

We get `400` HTTP Status and validation input error.
![image](https://github.com/withastro/astro/assets/22500212/47347d56-3c1e-4b90-b39d-8dc5883c2cfd)

### What's the expected result?

There is no error when action:

```js
await actions.like({ postId })
```

is called

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-pdghi3?file=src%2Fcomponents%2FLike.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Yeah I think the 500 error should not occur here but be a 400 instead. @bholmesdev wdyt?

**Comment by bholmesdev** [comment]
Thanks for reporting @ynhhoJ! I just confirmed this a Stackblitz issue, but does not occur locally. Is that true for you as well? That 500 error is indeed unexpected

**Comment by ynhhoJ** [comment]
@bholmesdev , originally, on on my machine:
```
Astro                    v4.11.5
Node                     v20.15.0
System                   Linux (x64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/node
Integrations             i18n:custom
                         @astrojs/tailwind
                         @astrojs/preact
```
I got another error `Unexpected end of JSON input`, every time when `action` has a body payload. So this is the cause why I opened this issue.

It's very strange:

![image](https://github.com/withastro/astro/assets/22500212/7fce9205-5abd-4bbc-8642-957c43ce62b9)
![image](https://github.com/withastro/astro/assets/22500212/04a83252-ff62-4122-b3ca-1079d5cc3f0c)

UPD: This error happens only with `bun run --bun dev`, if I run project from `npm run dev`, everything is OK

![image](https://github.com/withastro/astro/assets/22500212/7e43cf41-420c-4838-b723-24460eb150b2)

**Comment by bholmesdev** [comment]
got it. So to clarify @ynhhoJ: do **all** of the 500 errors you reported go away when using npm? We don't officially support bun, so I'd like to table that dsicussion

**Comment by ynhhoJ** [comment]
> do all of the 500 errors you reported go away when using npm?

Yeah. I opened an issue to `bun` repo.

Thank you!

**Comment by ynhhoJ** [comment]
Sorry, maybe `500` error should be fixed by `Astro` team :D

But `Unexpected end of JSON input` will be on `Bun` side

**Comment by bholmesdev** [comment]
@ynhhoJ Alright got it, that's good info. I know we rely on the `node:async_hooks` import for API context. It seems Bun has implemented this, but it could be an issue with the combo of Node and Vite. Not sure which side that issue is on yet.

**Comment by florian-lefebvre** [comment]
Also stackblitz has issues with ALSs

**Comment by bholmesdev** [comment]
Using this issue to track errors with edge middleware on Netlify and Vercel. Bun issue has been raised in their repository, and Stackblitz will take cross communication

**Comment by bholmesdev** [comment]
Alright, we removed async local storage from the Actions implementation, which should help with support in Bun and other environments. That still left your JSON parse error, which I think I've gotten to the bottom of!

We use `request.clone().json()` to read your input from the Action handler function. For some reason, calling `.clone()` clears out the response body in Bun (but not other environments). The `.clone()` is unnecessary and easy to remove on our end. The issue is [being tracked in Bun](https://github.com/oven-sh/bun/issues/6348) but unfortunately has not seen a fix yet.

**Comment by bholmesdev** [comment]
@ynhhoJ Well, I'm glad our unit testing suite exists. I've discovered the `.clone()` _is_ necessary to support reading the `ctx.request` body directly from an action. I unfortunately needed to close that PR.

I'm hopeful Bun can get this issue resolved on their end! But for now, I suggest removing the `--bun` flag when using Astro Actions.
