### ISSUE TITLE
Query parameters lost and function inconsistently

### ISSUE THREAD

**Issue by MikeCarbone** [withastro/astro#11434]
### Astro Info

```block
Astro                    v4.10.3
Node                     v18.17.1
System                   macOS (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/react
```

### Describe the Bug

When using query parameters for navigation, in production we lose the query parameters. Take this simple page for example:
```
---
const page = Astro.url.searchParams.get("page");
const res = await fetch(`${API_URL}/links?page=${page}`);
const data = await res.json();
---
<!doctype html>
<html lang="en">
  <body>
     { data.map((p) => <div>{p.title}</div> }
     <a href={`/links?page=${page + 1}`}>Next page</a>
   </body>
</html>
```
**This works locally.** As expected, clicking the "Next page" button will navigate to the next page and new data will show.

However when deployed (with Vercel), the page will _navigate_ with the query parameters, but the query parameters are not sent to the API. I'm not sure if this is a Vercel problem, an Astro problem, or a me problem.

In the StackBlitz example, it's even simpler and doesn't function as I'd expect.

### What's the expected result?

I expect query parameters to consistently hold the state. In the StackBlitz, I expect the query parameter to increment. I expect this to work in production. What am I missing?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pdcl2d?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
> This works locally. As expected

This **isn't** expected: https://docs.astro.build/en/reference/api-reference/#astrorequest

> With the default output: 'static' option, Astro.request.url does not contain search parameters, like ?foo=bar, as it’s not possible to determine them ahead of time during static builds. However in output: 'server' mode, Astro.request.url does contain search parameters as it can be determined from a server request.

**Comment by bluwy** [comment]
I tested locally and you can't access the searchParams either, which is intended as the page is prerendered and can't read the search params ahead of time. I'll close this for now as further explained by Ema as why this works the way it is.
