### ISSUE TITLE
Cookies are not persistent when set on a page inside 'account' folder

### ISSUE THREAD

**Issue by loissascha** [withastro/astro#11446]
### Astro Info

```block
Astro                    v4.11.5
Node                     v22.4.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

I have a login.astro page which sets a cookie (named 'bearerToken') on successful login which then gets read by my middleware to verify the login status on every request. 

When I have my login.astro page (or any other page) inside the src/pages/account folder there are two weird things happening. 
1. When I use Astro.cookies.set without defining a path, the cookie is only available to all the pages within the /account path
2. When I use Astro.cookies.set with the path '/' defined, the cookie is available on all the other pages except them inside /account path

When I move my login.astro page to the root or to a different folder (for example I'm using /auth now) it works.

**This bug does not appear when I run the minimal reproducible example on stackblitz, but when I download the example to my local machine and run it from there it happens.**

### What's the expected result?

I'd expect a cookie with path '/' to also be available on /account/[x] pages

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zd5fj1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @loissascha, your example is setting the cookie inside `/account/login/`. When you set a cookie within a subpath route the browser by default only allows the cookie to be retrieved from that path and subpaths. If you want the entire site to have access you need to provide a third argument to cookies.set: `{ path: '/' }`. See https://stackblitz.com/edit/github-zd5fj1-hbpkkp?file=src%2Fpages%2Faccount%2Flogin.astro

**Comment by loissascha** [comment]
@matthewp yes and if I set a cookie with path '/', its available on all paths exept them starting with /account.
I'd expect a cookie to be available on all paths including those starting with /account when setting the path to '/'.

This does not happen on stackblitz btw, I had to download the sample and run it with npm run dev.

**Comment by matthewp** [comment]
It does work locally for me.

<img width="1266" alt="Screen Shot 2024-07-22 at 1 54 24 PM" src="https://github.com/user-attachments/assets/09b834a4-9472-448d-89aa-aefda4e3b5a5">

It doesn't show as logged in when you press the button because you read the cool from `Astro.locals`, but that is already populated by the time the cookie is set. If you leave and come back to that page it shows as being logged in.

**Comment by loissascha** [comment]
> It doesn't show as logged in when you press the button because you read the cool from Astro.locals, but that is already populated by the time the cookie is set. If you leave and come back to that page it shows as being logged in.

I know that, it was not perfectly prepared in the test project from me. But I can confirm that even after reload it doesn't show for me. I tried it in 3 different projects because I first encountered this by accident while setting up a new project for my company. 
Did you make sure you didn't have the old cookie with the path /account/login left in your session while testing? I had that one time when I thought I fixed it and next day I had the issue again because the cookie was gone. 
I'll see if I can test this on another device tomorrow, maybe there's something wrong on my side or with my browser or whatever.

**Comment by matthewp** [comment]
Ok. I'll reopen for now.

**Comment by loissascha** [comment]
Okay I got it to work on my laptop. Seems to be a me problem. Sorry for wasting your time with what seems to be not an actual astro issue but rather something wrong on my PC.

**Comment by matthewp** [comment]
No problem, glad to hear you got it resolved.
