### ISSUE TITLE
Refuse to apply style because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by JenuelDev** [withastro/astro#11457]
### Astro Info

```block
Astro                    v4.11.5
Node                     v20.15.0
System                   Windows (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/netlify
Integrations             unocss
```

### Describe the Bug

Hi! I am using  UnoCss for astro, its working properly on my local but then when I deploy it in netlify its showing this error.

### What's the expected result?

It should able to apply the css file generated by unocss.

### Link to Minimal Reproducible Example

https://believerssword.netlify.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Can you please share "this error"?

**Comment by JenuelDev** [comment]
> Can you please share "this error"?

If you open this website https://believerssword.netlify.app/ and you open console you will be able to see the error. The project is SSR. Its just a simple hello world to test it out if its working. Here is the repo: https://github.com/Bible-Projects/believers-sword-next/tree/main/web-next

**Comment by JenuelDev** [comment]
I was able to solve this It seems its an error on my side, for people having this issue. To fix this you have to specify the the dist for published directory specially if your project in a sub directory of your repo.
![image](https://github.com/user-attachments/assets/99c06495-464b-4dda-a5f1-6c9ff0eb354f)
