### ISSUE TITLE
`hast` element property names converted to `camelCase` when running in MDX mode

### ISSUE THREAD

**Issue by benrbray** [withastro/astro#11453]
### Astro Info

```block
Astro                    v4.11.5
Node                     v20.11.1
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/solid-js
```

## Context

I have custom `remark`/`rehype` plugins for adding support for citations to Markdown files:

* [`@benrbray/rehype-cite`](https://github.com/benrbray/remark-cite/tree/master/rehype-cite) 
* [`@benrbray/remark-cite`](https://github.com/benrbray/remark-cite/tree/master/remark-cite) 

The `remark` plugin replaces pandoc-style citation syntax with `hast` nodes that look like this:

```javascript
{
  type: 'element',
  tagName: 'span',
  properties: {
    className: [ 'cite-inline' ],
    'data-cite': '[{"key":"riehl2017:category"}]'
  },
  children: [ { type: 'text', value: '[@riehl2017:category]' } ],
  position: {
    start: { line: 5, column: 5, offset: 252 },
    end: { line: 5, column: 26, offset: 273 }
  }
},
```

The `rehype` plugin looks for `span.cite-inline` elements and reads their `data-cite` property and passes it to the citation renderer.

## Problem

The `rehype` plugin performs as expected in ordinary markdown files, but **fails to detect any citations in MDX files**.  After some investigation, I discovered that when used with an MDX file, my `rehype-cite` plugin receives `hast` nodes that look like this:

```typescript
{
  type: 'element',
  tagName: 'span',
  properties: {
    className: [ 'cite-inline' ],
    dataCite: '[{"key":"riehl2017:category"}]'
  },
  children: [ { type: 'text', value: '[@riehl2017:category]' } ],
  position: {
    start: { line: 17, column: 6, offset: 289 },
    end: { line: 17, column: 27, offset: 310 }
  }
}
```

Notice that the citation data belongs to `properties.dataCite` rather than the expected `properties.data-cite`.

### What's the expected result?

I would expect `astro` to preserve the names of properties attached to `hast` nodes, so that they can be read by `rehype` plugins which expect specific names.

## Questions

* is this expected behavior of `astro`?  if so, why does it happen only for MDX files and not for standard MD?
* are there any workarounds that would not require modifying the behavior of my `rehype-cite` plugin?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ovqfqy?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Rehype when parsing may turn it into camelCase, Astro doesn't explicitly change this and presumably it happen because there was another rehype pass in Astro (or the MDX pipeline) that raised this. The camelcase behaviour is documented in the [rehype spec](https://github.com/syntax-tree/hast?tab=readme-ov-file#propertyname), and you can verify the behaviour at https://github.com/wooorm/property-information/blob/c24a4674206b25af82841339237577d6aa4c4978/lib/find.js#L27-L32.

I'd suggest for the plugin to check for the camelcase version instead.
