### ISSUE TITLE
Markdown Pages - Links on new tab and additional attribute support

### ISSUE THREAD

**Issue by impondesk** [withastro/astro#11462]
### Astro Info

```block
Astro 4.10
```

### Describe the Bug

Looking for adding target="_blank" to md pages links

### What's the expected result?

Adding target attribute to links
- default value as target="_self" and
- support to override as required

### Link to Minimal Reproducible Example

https://www.impondesk.com/blog/microfrontends/

**Comment by bluwy** [comment]
You can use something like https://www.npmjs.com/package/rehype-external-links for it.
