### ISSUE TITLE
Nested links being rendered as siblings

### ISSUE THREAD

**Issue by Soviut** [withastro/astro#11474]
### Astro Info

```block
Astro                    v4.11.5
Node                     v22.4.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @storyblok/astro
                         @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/partytown
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

I have a Card component where the entire thing can be made into a clickable link. It also has a body slot that can be filled with rich text. When the rich text contains a link, the card renders incorrectly, not maintaining the nesting and actually duplicating the contents of the parent `<a>` tag to the child.

Here is the simplest example. Two nested tags.

```astro
---
---
<div>
  <a href="#" class="parent">
    <a href="#" class="child">Read more</a>
  </a>
</div>
```

When rendered become siblings.

```html
<div data-astro-source-file="/home/soviut/projects/myproject/src/components/Card.astro" data-astro-source-loc="30:6">
  <a href="#" class="parent" data-astro-source-file="/home/soviut/projects/myproject/src/components/Card.astro" data-astro-source-loc="31:30"></a>
  <a href="#" class="child" data-astro-source-file="/home/soviut/projects/myproject/src/components/Card.astro" data-astro-source-loc="32:31">Read more</a>
</div>
```

When I add some other elements (like in the original Card component)...

```astro
---
---

<div>
  <a href="#" class="parent">
    <div>
      <a href="#" class="child">Read more</a>
    </div>
  </a>
</div>
```

It seems to duplicate certain parts of the parent

```html
<div data-astro-source-file="/home/soviut/projects/myproject/src/components/Card.astro" data-astro-source-loc="30:6">
  <a href="#" class="parent" data-astro-source-file="/home/soviut/projects/myproject/src/components/Card.astro" data-astro-source-loc="31:30"></a>
  <div data-astro-source-file="/home/soviut/projects/myproject/src/components/Card.astro" data-astro-source-loc="31:4">
    <a href="#" class="parent" data-astro-source-file="/home/soviut/projects/myproject/src/components/Card.astro" data-astro-source-loc="32:10"></a>
    <a href="#" class="child" data-astro-source-file="/home/soviut/projects/myproject/src/components/Card.astro" data-astro-source-loc="33:33">Read more</a>
  </div>
</div>
```

### What's the expected result?

I should be able to render a link inside a link without any rendering issues.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-q5xoza?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is expected due to how HTML works: https://stackoverflow.com/questions/9882916/are-you-allowed-to-nest-a-link-inside-of-a-link

There is an argument to be made that Astro should not respect how HTML works and instead let the browser figure it out, that I'd agree with. For that, please create a discussion on our roadmap repo: https://github.com/withastro/roadmap/discussions with the suggestion

**Comment by Soviut** [comment]
The biggest issue I had is that it was unexpected behaviour. It would be handy if Astro reported these kinds of issues.
