### ISSUE TITLE
Build broken in Astro 4.11.6

### ISSUE THREAD

**Issue by wheresrhys** [withastro/astro#11480]
### Astro Info

```block
Astro                    v4.11.6
Node                     v18.20.4
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/starlight

I'm also seeing the issue in github actions, where I am unable to run `astro info`
```

### Describe the Bug

Some dependencies appear to be missing. See this build output https://github.com/wheresrhys/fetch-mock/actions/runs/9975537393/job/27565585726

### What's the expected result?

When pinning to 4.11.5 I get a successful build https://github.com/wheresrhys/fetch-mock/actions/runs/9975667348/job/27565992625

### Link to Minimal Reproducible Example

https://github.com/wheresrhys/fetch-mock/actions/runs/9975537393/job/27565585726

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I had a quick look at your action, and it seems that was triggered after you update the package manager. Is it possible that some lock file wasn't updated? Or that the action is buggy? https://github.com/wheresrhys/fetch-mock/commit/ffab4b6f5795de6179ad425bc9fc273ef457f9fd

I did update a repo of mine that relies on starlight with that latest of Astro and I didn't see any issue.

**Comment by Piotr-Aueternum** [comment]
> I had a quick look at your action, and it seems that was triggered after you updated the package manager. Is it possible that some lock file wasn't updated? Or that the action is buggy? [wheresrhys/fetch-mock@ffab4b6](https://github.com/wheresrhys/fetch-mock/commit/ffab4b6f5795de6179ad425bc9fc273ef457f9fd)
> 
> I did update a repo of mine that relies on starlight with that latest of Astro and I didn't see any issue.

I started new project and I'm having same issue with 4.11.6. In other hand 4.11.5 works fine.
windows 11
node 18/20
npm 9.6.7
```
{
  "name": "test",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.8.2",
    "@astrojs/mdx": "^3.1.2",
    "@astrojs/rss": "^4.0.7",
    "@astrojs/sitemap": "^3.1.6",
    "astro": "^4.11.5",
    "typescript": "^5.5.3"
  }
}

> astro dev

SyntaxError: Unexpected token 'with'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
```

**Comment by Princesseuh** [comment]
There is an an actual regression, this version of Astro introduces an import attribute somewhere (possibly in a dep?), which are not supported on low versions of Node 18 and 20.

Upgrading your Node version will fix this.

**Comment by nathanchere** [comment]
Just encountered this with Cloudflare Pages hosting, since their most current build configuration still uses Node 18.17

Setting an environment variable `NODE_VERSION` value `22.4` got builds working again.

**Comment by nakasyou** [comment]
Building also fails on Bun v1.1.20 on Cloudflare Pages.

**Comment by ematipico** [comment]
For anyone coming here, the next release (4.12.0) will fix it.

**Comment by fregante** [comment]
The fix is out, you no longer need to use a lower version

-  https://github.com/sindresorhus/boxen/pull/102
