### ISSUE TITLE
How to Exclude links from sitemap, i have tried but not working

### ISSUE THREAD

**Issue by tiktokios** [withastro/astro#11488]
### Astro Info

```block
i hav started a site on ASTRO, where as i need to exclude some links from sitemap, but unable to do so. please help on this.

i have add following string in astro.config.mjs 

 output: "server",
  integrations: [
    astroI18next(),
    react(),
    sitemap({
      filter: (page) =>
        page !== 'https://mysite.com/elements' &&
        page !== 'https://mysite.com/hashtag-generator/' &&
        page !== 'https://mysite.com/download' &&
        page !== 'https://mysite.com/categories' &&
        page !== 'https://mysite.com/authors' &&
        page !== 'https://mysite.com/tags/',
    }),
    tailwind({
      config: {
        applyBaseStyles: false,
      },
    }),
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Mozila, Opera

### Describe the Bug

sitemap isn't able to exclude unnecessary links.

### What's the expected result?

no result

### Link to Minimal Reproducible Example

https://saveinsta.li/sitemap-0.xml

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@tiktokios to me it seems to be working, but you're website is multiple language, so you need filter localised URLs too. e.g. `https://mysite.com/de/elements`

**Comment by tiktokios** [comment]
> localised i need to exclude some unnecessary links. please help on this

**Comment by ematipico** [comment]
@tiktokios please join us on Discord, we'll help you there https://astro.build/chat
