### ISSUE TITLE
Lit component hydration with 'client:*' directive fetches all the components exported in the index.js

### ISSUE THREAD

**Issue by RogierdeRuijter** [withastro/astro#11487]
### Astro Info

```block
Astro                    v4.11.6
Node                     v20.12.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/lit
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Safari

### Describe the Bug

When hydrating a component with a client directive (e.g. client:load). All the components that are present in the index file are fetched if the file is imported through an index file.  This behaviour doesn't happen when the component is imported directly.

For example:

Index import (issue):

```
import { MyLitComponent } from "../lit-components";
...
<MyLitComponent client:load />
```

Direct import (no issue):

```
import { MyLitComponent } from "../lit-components/my-lit-component";
...
<MyLitComponent client:load />
```

When running the reproduction and looking at the network tab you can see that 2 requests are made.
<img width="728" alt="Scherm­afbeelding 2024-07-18 om 11 11 57" src="https://github.com/user-attachments/assets/5deef79a-5932-4461-8b54-a62d4771645a">

### What's the expected result?

That only the `my-lit-component.js` is fetched by the browser and not `my-lit-component-2.js`

### Link to Minimal Reproducible Example

https://github.com/RogierdeRuijter/astro-index-lit-component

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
This is expected, and it's just plain JavaScript. You're importing a **barrel file** that imports other files, and the browser imports those. Astro isn't doing anything, it's just importing the component you passed.

**Comment by RogierdeRuijter** [comment]
@ematipico This is tricky to understand. If I have the following code.

```
---
import { MyAstroComponent } from './astro-barrel-file.ts';
import { MyLitComponent } from './lit-barrel-file.ts';
---

<!-- Not a performance issue -->
<MyAstroComponent />

<!-- A performance issue -->
<MyLitComponent client:load />

```

It is difficult to understand, by reading this code, that one has performance impact but the other has not. I don't have a solution for this, but it is not intuitive.

**Comment by ematipico** [comment]
I know, but it isn't an Astro issue.
