### ISSUE TITLE
Astro fails to install Node 22.5

### ISSUE THREAD

**Issue by PhearZero** [withastro/astro#11493]
### Astro Info

```block
@latest
```

### Describe the Bug

Install hangs when running `npm install -g astro` on Ubuntu 22.04.4 LTS and Node `22.5`

### What's the expected result?

Successful install of `astro`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-cfdthv

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by PhearZero** [comment]
https://x.com/nodejs/status/1814112932650701195

This is an issue upstream with Node

**Comment by ematipico** [comment]
For people coming here: 
- downgrade to 22.4.*
- wait for a 22.5.* fix
