### ISSUE TITLE
Astro component with `?raw` suffix should not be executed

### ISSUE THREAD

**Issue by erwinheldy** [withastro/astro#11502]
### Astro Info

```block
Astro                    v4.12.1
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Because Astro components with the suffix `?raw` are strings, the string should not be executed, even if there is a script tag within it.

For example I have `Hello.astro` component:
```html
<h1>Hello world</h1>
<script>alert("Hello world")</script>
```

Now I import it using `?raw`:
```astro
---
import { Code } from 'astro:components'
import Hello from '../components/Hello.astro?raw';
---

<Code code={Hello} lang="html" />
```

Results:
![image](https://github.com/user-attachments/assets/ffeb9b31-cf99-4665-9dd7-e529865ec30a)

### What's the expected result?

The string should not be executed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dznkn1?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Fryuni** [comment]
This one is related to https://github.com/withastro/astro/pull/11478 where we make it so the code doesn't get transformed when one of Vite's magic queries is present.

In those cases, the script and styles should not propagate to the parent.
