### ISSUE TITLE
astro:assets doesn't export ImageMetadata, making it hard to pass images as props.

### ISSUE THREAD

**Issue by jcayzac** [withastro/astro#11521]
### Astro Info

```block
Astro                    v4.12.2
Node                     v20.15.1
System                   macOS (arm64)
Package Manager          bun 1.1.17
Output                   static
Adapter                  none
Integrations             astro-icon
                         @astrojs/preact
                         auto-import
                         astro-embed
                         astro-expressive-code
                         @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Because it's not exposed, to properly type images when passing them as props one has to use:

```ts
import type { ImageFunction } from 'astro:content'
type ImageMetadata = ReturnType<ImageFunction>['_output']
```

(note: using `['_output']` here since Astro doesn't expose `z.infer` (#11520))

### What's the expected result?

`ImageMetadata` should be exported by `astro:assets`.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You can import it from `astro`, `import type { ImageMetadata } from "astro";`

**Comment by jcayzac** [comment]
@Princesseuh Thanks! Somehow I couldn't find it anywhere 😮
