### ISSUE TITLE
Astro doesn't expose z.infer.

### ISSUE THREAD

**Issue by jcayzac** [withastro/astro#11520]
### Astro Info

```block
Astro                    v4.12.2
Node                     v20.15.1
System                   macOS (arm64)
Package Manager          bun 1.1.17
Output                   static
Adapter                  none
Integrations             astro-icon
                         @astrojs/preact
                         auto-import
                         astro-embed
                         astro-expressive-code
                         @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Astro exposes Zod as `z` from the `astro:content` package. However, [`z.infer`](https://zod.dev/?id=type-inference) is not exported, so users have to use Zod's internal implementation-specific `MyType['_output']` rather than the regular `z.infer<MyType>`.

### What's the expected result?

`z.infer` should be exported by `astro:content`.

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/issues/11520

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
I can use `z.infer` just fine using the Zod imported from about anywhere:

<img width="424" alt="image" src="https://github.com/user-attachments/assets/1ba4fbca-568b-45ac-9def-8cf1b557f29d">
