### ISSUE TITLE
View transitions: `transitionEnabledOnThisPage` returns `true` when fallback is set to `none`

### ISSUE THREAD

**Issue by bholmesdev** [withastro/astro#11528]
### Astro Info

```block
Astro                    v4.11.5
Node                     v20.13.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/netlify
Integrations             @astrojs/markdoc
                         astro-icon
                         @astrojs/react
                         simple-stack-query
```

### If this issue only occurs in one browser, which browser is a problem?

Firefox, Safari

### Describe the Bug

I built a library that reruns a user's script whenever view transitions are enabled. I toggle this behavior using `transitionEnabledOnThisPage` from `astro:transitions/client`. However, I noticed this returns `true` even when fallback is set to `none` and my browser does not support view transitions. 

### What's the expected result?

I am using `transitionEnabledOnThisPage` to determine whether the `astro:page-load` event will fire. Since `astro:page-load` does not fire when the fallback is set to `none`, I would expect `transitionEnabledOnThisPage` to return `false`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gcu7qh?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @bholmesdev, yes, in retrospective one might expect that ;-)
I'm a bit reluctant to change the semantics of the API but on the other hand, 
a) I do not think that that this function is widely used and
b) one might argument that it is a bug 

Would be happy to see your PR on this!
Should we defer it to 5.0?

In the meanwhile you could extend your test with ` && ... getFallback() !== 'none')`

**Comment by martrapp** [comment]
Yes, please! Regarding the original intend you could talk to Matthew. 

Inside the client side router it is not used as "SPA-mode" but "The client-side router code is available on that page in case we need to reload". 

I skimmed our uses and it looks like adding `getFallback() !== "none"` wouldn't hurt, but you should check it thoroughly. I'm afraid we do not have e2e tests that check consequences in the behavior when `transitionEnabledOnThisPage` changes. 🙄 

Alternatively, you could add a new function along the lines of "SPA routing".

**Comment by martrapp** [comment]
Having a second look at the whole thing:

@bholmesdev, @matthewp: Even though I can understand when reading the name of the function raises expectations that it might do something else, I guess we should have better justification for an incompatible change to a published function. People might have used it in their own components to differentiate as the docs suggest.

**Comment by matthewp** [comment]
I think we can close.

**Comment by bholmesdev** [comment]
@matthewp agreed. I don't feel strongly enough to push this forward, and I no longer use the function in my own code
