### ISSUE TITLE
Build error with both a conditional ternary and a nullish coalescing operators

### ISSUE THREAD

**Issue by HiDeoo** [withastro/astro#11526]
### Astro Info

```block
Astro                    v4.12.2
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When running `astro build` with code including a conditional ternary operator and a nullish coalescing one, e.g. by adding the following simplified code to `src/pages/index.astro`

```js
const something = 4;
const result = (something ? 'a' : 'b') ?? 'c';
console.log('🚨 [index.astro:9] result:', result);
```

The following error is thrown:

```
11:47:05 [build] Building static entrypoints...
11:47:06 [ERROR] [vite] x Build failed in 1.14s
[vite:build-import-analysis] [plugin vite:build-import-analysis] pages/index.astro.mjs (1:1): Parse error @:1:1

1  |  import { c as createComponent, r as renderTemplate, a as addAttribute, b as renderHead, d as renderSlot, e as createAstro, m as maybeRenderHead, f as renderComponent } from '../chunks/astro/server_Csh4ctT6.mjs';
   |   ^
2  |  import 'kleur/colors';
3  |  import 'html-escaper';

  Stack trace:
    at parse$f (file:///home/projects/xoriwgxvly.github/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:20559:585)
    at eval (file:///home/projects/xoriwgxvly.github/node_modules/rollup/dist/es/shared/node-entry.js:19833:40)
```

A few notes:

- This works fine when running `astro dev`
- If `something` is a function call, e.g. `Math.random()`, the error is not thrown.
- If the nullish coalescing operator is removed and the code is only `const result = (something ? 'a' : 'b')`, the error is not thrown.
- The error reproduces if the code is located in a TS file imported and used in the Astro file as well.

### What's the expected result?

I would not expect an error in this case.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xa1qdj?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Looks like an upstream Rollup issue. I've opened an issue there: https://github.com/rollup/rollup/issues/5585. I'll close this here for now as there's not much we can fix here.
