### ISSUE TITLE
Can't consume web components directly in MDX

### ISSUE THREAD

**Issue by daniellwdb** [withastro/astro#11539]
### Astro Info

```block
Astro                    v4.11.0
Node                     v20.15.0
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
                         astro-robots-txt
                         @astrojs/preact
```

### Describe the Bug

Whenever I try to consume a library that uses Lit directly in mdx, it seems to not render correctly. Only the plain HTML tags are rendered (see example). It does work when consuming the library in a .ts(x) file and import that larger component inside mdx.

### What's the expected result?

The components should render correctly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cvquga?file=src%2Fcontent%2Fblog%2Ffirst-post.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@daniellwdb, do you have some documentation that explains how you can render lit/web components in a `.mdx` file?

**Comment by daniellwdb** [comment]
I will reopen in case I got some clarity
