### ISSUE TITLE
Deploy on Vercel with server mode not working since 4.11.6

### ISSUE THREAD

**Issue by bentouch-digital** [withastro/astro#11532]
### Astro Info

```block
Astro                    v4.11.5
Node                     v20.15.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @storyblok/astro
                         @astrojs/sitemap
                         @astrojs/vue
                         astro-icon
                         unocss
                         prebuild-tailwind-classes
                         redirections
                         robots-txt
                         astro-icon
                         ab-testing
```

### Describe the Bug

Hi,
I've updated the Astro version from 1.11.5 to 1.12.2. After deployment on Vercel each page returns a 500 error. 
I then downgraded the Astro version until I no longer had the problem and it worked again from 1.11.5, so the bug must have come from 1.11.6.
I use server mode to render my site.

This is what the errors in the Vercel logs look like: 
```
Invalid export found in module "/var/task/.vercel/output/_functions/chunks/_.._CjjaY_-n.mjs".
The default export must be a function or server.
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
Invalid export found in module "/var/task/.vercel/output/_functions/chunks/_.._CjjaY_-n.mjs".
The default export must be a function or server.
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
```

### What's the expected result?

Deployment works on Vercel.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bentouch-digital** [comment]
Reproduction link: 
https://stackblitz.com/edit/github-86xhmq?file=astro.config.mjs

**Comment by bluwy** [comment]
Hmm the error doesn't quite make a lot of sense. It implies that it tries to load nested chunk files as serverless entrypoints, but we do generate `.vercel/output/functions/_image.astro.func/.vc-config.json` with:

```json
{
	"runtime": "nodejs18.x",
	"handler": "pages/entry._image.astro.mjs",
	"launcherType": "Nodejs",
	"supportsResponseStreaming": true
}
```

So it should load `pages/entry._image.astro.mjs` only

**Comment by dylanalizon** [comment]
Got the same error. I tried to upgrade Astro to the last version and got the error after deploying on Vercel. Rollback to 4.11.5 solves the error. 

Does a workaround exist?

**Comment by bentouch-digital** [comment]
After some investigations this concerns only Astro pages. When i tried to fix this i duplicate my [...slug].astro to another folder like this testing/[...slug].astro and after some tests inside the deployment worked. I then deleted the duplicated file and I hadn't changed anything inside the original file and then the bug came back. I have the feeling that the problem occurs depending on the size of the chunks.

**Comment by bentouch-digital** [comment]
Set "functionPerRoute" to false seems to solve the problem.

**Comment by ematipico** [comment]
Hi @bentouch-digital, I strongly suggest **not using** `functionPerRoute`. 

We plan to deprecate the feature because we haven't noticed particular advantages compared to the classic bundling.
