### ISSUE TITLE
Server Island Missing Runtime Env

### ISSUE THREAD

**Issue by rawkode** [withastro/astro#11530]
### Astro Info

```block
Astro                    v4.12.2
Node                     v20.11.1
System                   Linux (x64)
Package Manager          bun
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/vue
                         @astrojs/react
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

I'm testing out server islands and deferred a LoginButton.

Locally, this runs fine and works. 

Unfortunately, I cannot build the site when trying to ship to production.

It appears that it tries to render the static pages, and the runtime environment is unavailable.

### What's the expected result?

`context.locals.runtime.env` should be available for server:deferred component.

```
 prerendering static routes
22:46:23 ▶ src/pages/about/index.astro
22:46:23   └─ /about/index.htmlCannot destructure property 'env' of 'context.locals.runtime' as it is undefined.
  Stack trace:
    at file:///home/rawkode/Code/src/gitlab.com/RawkodeAcademy/RawkodeAcademy/projects/rawkode-academy/web/dist/_worker.js/chunks/_astro-internal_middleware_3m49KJKK.mjs:1723:11
    at file:///home/rawkode/Code/src/gitlab.com/RawkodeAcademy/RawkodeAcademy/projects/rawkode-academy/web/dist/_worker.js/chunks/_astro-internal_middleware_3m49KJKK.mjs:481:12
    at file:///home/rawkode/Code/src/gitlab.com/RawkodeAcademy/RawkodeAcademy/projects/rawkode-academy/web/node_modules/astro/dist/core/middleware/sequence.js:35:18
    at applyHandle (file:///home/rawkode/Code/src/gitlab.com/RawkodeAcademy/RawkodeAcademy/projects/rawkode-academy/web/node_modules/astro/dist/core/middleware/sequence.js:16:22)
    at callMiddleware (file:///home/rawkode/Code/src/gitlab.com/RawkodeAcademy/RawkodeAcademy/projects/rawkode-academy/web/node_modules/astro/dist/core/middleware/callMiddleware.js:20:27)
```

### Link to Minimal Reproducible Example

https://gitlab.com/RawkodeAcademy/RawkodeAcademy/-/merge_requests/5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rawkode** [comment]
I was able to work around this in the interim with:

https://gitlab.com/RawkodeAcademy/RawkodeAcademy/-/merge_requests/5/diffs?commit_id=45062d9c7a6ef2093a80b4af7cdb4b546fd84b0d

Which I got from:

https://github.com/withastro/astro/issues/4416

**Comment by matthewp** [comment]
@alexanderniebuhr can you think of anything about server islands that would cause Cloudflare locals to not be set?

**Comment by alexanderniebuhr** [comment]
The issue @rawkode has here is that `context.locals.runtime` is not available during build time for prerendered pages. This is expected and the current behavior even without server islands. It looks like the issue occurs inside some middleware, which would make sense since middleware runs for prerendered and on-demand pages.

I can't quite follow the reproduction case, but I would like to understand the issue more and give a better answer to this.

**Comment by rawkode** [comment]
OK, so the problem is that I thought middleware was for on-demand only.

Is there a way to tell if it's prerendered or on-demand?

I should be able to handle this correctly now that I understand what's happening.

Thank you.
