### ISSUE TITLE
`astro-island,astro-slot,astro-static-slot{display:contents}` is injected in the body in both dev and production

### ISSUE THREAD

**Issue by arihantverma** [withastro/astro#11536]
### Astro Info

```block
Astro                    v4.12.2
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
                         @astrojs/mdx
```

### Describe the Bug

`astro-island,astro-slot,astro-static-slot{display:contents}` is injected in a style tag ( in this example inside the `header` tag )

Related closed, old issue for reference: #4298

### What's the expected result?

`astro-island,astro-slot,astro-static-slot{display:contents}` shouldn't be injected in a style tag in the body

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-kmy4p3

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
I'm not sure I understand, it's intended that this is in a style tag in the body, you would get worse performance if it was anywhere else.

As for the validity of it, there's.. long discussions on the subject (see https://github.com/whatwg/html/issues/1605 ), but it is intended in the context of Astro at this time and supported by every browser.

**Comment by arihantverma** [comment]
@Princesseuh you are right. I incorrectly understand the previous issue, the issue there was that the style tag was actually showing off on the page, which is different from what I said.

At first, in the least, I was confused as to why a style tag with astro custom elements' selectors were injected in the first place. It just hit me right now why those styles are needed – `display:contents` to let css work in a way it should without `astro-` custom elements wrappers getting the way.

Something that I didn't share in the issue description was that my exact issue was that on android chrome. In the screenshot below, you can see that the first paragraph has a visually different font size, even though both paragraphs have `font-size:16px`. I thought that it had something to do with the styles injected, since unchecked `astro-island {display: contents}` fixed it. 

<img width="406" alt="Screenshot 2024-07-24 at 11 42 57 AM" src="https://github.com/user-attachments/assets/13037192-e866-4b2c-99fd-567fb73b5a6f" >

But turns it out it isn't. It's because of the button html element in the paragraph ( shown with the vanilla reproduction ).

<img width="404" alt="Screenshot 2024-07-24 at 12 28 09 PM" src="https://github.com/user-attachments/assets/e94cc3cf-338c-48c1-af97-57f062265254">

Repro links (it is not an astro specific issue, I'm sharing an astro repro anyway, followed by a vanilla repro):

(open the following in android chrome:)

Astro: https://stackblitz.com/edit/withastro-astro-6wgofr
Vanilla: https://codepen.io/arihantverma/full/zYVKYYo

A possible chromium bug because of which this issue arises: https://issues.chromium.org/issues/40484405

Closing this issue, since it's not an astro issue.

Thank you for taking out time to explain, appreciate it.

**Comment by sudheer-salavadi** [comment]
Avoid putting hydrated components directly inside inline or restricted HTML elements like:
`<li>` `<span>` `<option>` `<title>` etc. 

Place react components outside above elements in .astro files, it should work fine.
