### ISSUE TITLE
When using a strict package manager like pnpm, you may need to manually install Sharp into your project even though it is an Astro dependency.

### ISSUE THREAD

**Issue by peipei818** [withastro/astro#11533]
### Astro Info

```block
Why i need to manually install Sharp when using `pnmp`?
```

### If this issue only occurs in one browser, which browser is a problem?

-

### Describe the Bug

-

### What's the expected result?

-

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Please use Discord for these kinds of questions.
