### ISSUE TITLE
Replacing Images Does Not Auto Update

### ISSUE THREAD

**Issue by KevinFocke** [withastro/astro#11547]
### Astro Info

```block
Astro                    v4.11.5
Node                     v20.12.2
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         astro-robots-txt
                         astro-critters
```

### Describe the Bug

Hello Astro,

I am updating my website and noticed images do not automatically update while running `npm run dev` . I have to click on an image for it to change. Even a refresh does not work on my browser (Chrome).

The theme is an old one by [Lexington Themes](https://lexingtonthemes.com/) that I made some changes to. Anyway.

### What's the expected result?

The images automatically update if you change them while running `npm run dev`.

### Link to Minimal Reproducible Example

nah

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I know you said "nah", but we really need a reproduction to understand what's the issue

**Comment by canxerian** [comment]
Probably browser caching, if anyone else comes across this issue - shift + refresh should do the trick
