### ISSUE TITLE
How to share states between Server Islands?

### ISSUE THREAD

**Issue by mogeko** [withastro/astro#11552]
### Astro Info

```block
Astro                    v4.12.2
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

I tried to use `Astro.url.searchParams.get` in server islands to get `SearchParam`, but it didn't work properly.

```astro
---
export const prerender = false;

const page = Astro.url.searchParams.get("page");
---

<div>Page: {page} </div>
```

<img width="444" alt="截屏2024-07-25 19 07 18" src="https://github.com/user-attachments/assets/0632d52d-d192-40f2-b630-bb5fd4d012d5">

### What's the expected result?

Allow the use of `SearchParam` in Server Islands, or any other mechanism to share the state between Server Islands.

I believe a syntax like React Hook would be a good idea:

```ts
const [page, setPage] = useState("page");
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hp28qt?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Pleas leave support questions in https://astro.build/chat
