### ISSUE TITLE
pages not loading when deployed to Firebase

### ISSUE THREAD

**Issue by jorgecoca** [withastro/astro#11556]
### Astro Info

```block
Astro                    v4.12.2
Node                     v20.16.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/starlight
                         @astrojs/tailwind
```

### Describe the Bug

I have a project that uses Firebase for hosting, and Firebase authentication to control users. The code is pretty much identical to the one found in this video: https://www.youtube.com/watch?v=Kjro6HzFCk0 and this repository: https://github.com/coding-in-public/firebase-astro-auth/tree/finished-code

I am deploying to firebase with the webframeworks experiment enabled, and it works. The deployment is successful.

Unfortunately, the routes are not longer protected by the middleware and the "new" page that should show the login form throws this message (https://github.com/coding-in-public/firebase-astro-auth/tree/finished-code/src/pages):

```
Error: Forbidden
Your client does not have permission to get URL /login from this server.
```

In localhost everything works without a problem.

### What's the expected result?

I can access the content inside `pages` served from Firebase Hosting without a problem

### Link to Minimal Reproducible Example

https://github.com/coding-in-public/firebase-astro-auth/tree/finished-code

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
Hi @jorgecoca 
Can you share the actual repo that you're trying to deploy. The one you linked isn't going to help, because presumably it is working because the author deployed it in the video. If you create a new repo that you actually try to deploy and then if it fails share that then it would be easier for us to see exactly what's happening. Thanks.

**Comment by ascorbic** [comment]
The main difference is that the demo is showing as being deployed to Vercel, and presumably you've needed to change the adapter to Node to deploy to Firebase, correct?
