### ISSUE TITLE
I used an Image component of astro, and set source to a url image link but its not working in netlify production.

### ISSUE THREAD

**Issue by JenuelDev** [withastro/astro#11563]
### Astro Info

```block
Astro                    v4.12.2
Node                     v20.15.0
System                   Windows (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/netlify
Integrations             unocss
                         astro-icon
```

### Describe the Bug

I used `import { Image } from "astro:assets";` for images on my website. But I use url:
example:
```jsx
             <Image
                    src={data.cover_img}
                    class="rounded-lg w-full mx-auto col-span-2"
                    width="300"
                    height="150"
                    loading="eager"
                    alt={data.title}
                />
```

the `data.cover_img` contains a url link like `https://example.com/path/image.png` from different domains or base domains.
But When I deployed it in netlify this is what I am getting. But image is not displaying.

This is what it rendered in html
![image](https://github.com/user-attachments/assets/f9bfe7bf-5a4f-41e8-9486-d8bcef97055b)

The image is not rendering
![image](https://github.com/user-attachments/assets/bf29ae7f-97ab-4744-a86a-9243c81d72a8)

### What's the expected result?

It should render the image.

here is the repo for this test: https://github.com/JenuelDev/github-rxm5dx-lr4njb
and I deployed it in netlify: https://boisterous-crostata-04e284.netlify.app/

### Link to Minimal Reproducible Example

https://github.com/JenuelDev/github-rxm5dx-lr4njb

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Trombach** [comment]
Have you configured the domain in you config as explained here: https://docs.astro.build/en/guides/images/#authorizing-remote-images?

**Comment by JenuelDev** [comment]
I moved by project to Vercel

**Comment by jdic** [comment]
I had this problem a while ago, but it came back and is persistent.

My solution: switch to **Vercel**.
