### ISSUE TITLE
Inaccurate JSdoc comment for `page.size` in astro/@types

### ISSUE THREAD

**Issue by ArmandPhilippot** [withastro/astro#11560]
### Astro Info

```block
Astro                    v4.12.2
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I was reading the [Routing guide](https://docs.astro.build/en/guides/routing/#complete-api-reference) and I noticed an error which leads me to `astro/@types` package.

The Page interface in [`astro/@types`](https://github.com/withastro/astro/blob/02c85b541241a07db45bf9e15717e111104898e5/packages/astro/src/%40types/astro.ts#L2707-L2708) indicates that the default for `page.size` is `25`. It seems to be wrong:
* see [paginate.ts#L19](https://github.com/withastro/astro/blob/02c85b541241a07db45bf9e15717e111104898e5/packages/astro/src/core/render/paginate.ts#L19) and [paginate.ts#L80](https://github.com/withastro/astro/blob/02c85b541241a07db45bf9e15717e111104898e5/packages/astro/src/core/render/paginate.ts#L80): `page.size` uses the given `pageSize` option in `paginate()` function or `10`.
* [Stackblitz reproduction](https://stackblitz.com/edit/astro-paginate-pagesize?file=src%2Fpages%2Fpokemon%2F[page].astro&on=stackblitz) (click on `Pokemon - Page 1` in the preview)

### What's the expected result?

```diff
/**
 * Represents a single page of data in a paginated collection
 *
 * [Astro reference](https://docs.astro.build/en/reference/api-reference/#the-pagination-page-prop)
 */
export interface Page<T = any> {
	/** result */
	data: T[];
	/** metadata */
	/** the count of the first item on the page, starting from 0 */
	start: number;
	/** the count of the last item on the page, starting from 0 */
	end: number;
	/** total number of results */
	total: number;
	/** the current page number, starting from 1 */
	currentPage: number;
-	/** number of items per page (default: 25) */
+	/** number of items per page (default: 10) */
	size: number;
	/** number of last page */
	lastPage: number;
	url: {
		/** url of the current page */
		current: string;
		/** url of the previous page (if there is one) */
		prev: string | undefined;
		/** url of the next page (if there is one) */
		next: string | undefined;
		/** url of the first page (if the current page is not the first page) */
		first: string | undefined;
		/** url of the next page (if the current page in not the last page) */
		last: string | undefined;
	};
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-paginate-pagesize?file=src%2Fpages%2Fpokemon%2F[page].astro&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You're right. Feel free to send a PR to fix that 👍

**Comment by ArmandPhilippot** [comment]
@bluwy Done! I just created the issue to keep a track (I don't know if this was needed...).

**Comment by bluwy** [comment]
For single line changes it may be easier (especially for you as there's less work) to create a PR directly in the future, as long as the PR explains the context too! But still it doesn't hurt if you prefer to open an issue first.

**Comment by ArmandPhilippot** [comment]
Ok @bluwy, thanks for you feedback! 😄
