### ISSUE TITLE
Build fails due to the "Export named 'removeBase' not found in module" error

### ISSUE THREAD

**Issue by brklntmhwk** [withastro/astro#11573]
### Astro Info

```block
Astro                    v4.12.2
Node                     v20.16.0
System                   Linux (x64)
Package Manager          bun
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/mdx
                         @astrojs/solid-js
                         astro-purgecss
                         @astrojs/sitemap
```

### Describe the Bug

At some point in time, it started throwing an error like below at build time.
Deployment succeeds despite the error somehow. (To Cloudflare Pages)

---
$ astro check && astro build
Export named 'removeBase' not found in module '/home/runner/work/website/website/node_modules/astro/dist/core/path.js'.
  Stack trace:
    at <parse> (:0)
    at link (:1:11)
    at linkAndEvaluateModule (:1:11)
error: script "build" exited with code 1
Error: Process completed with exit code 1.
---

### What's the expected result?

Build ends in success.

### Link to Minimal Reproducible Example

Extrapolating from the error message, it seems hard to create a minimal reproducible example project.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
I'd suggest nuking your node_modules, making sure everything is up to date and reinstalling.

I suspect somehow that one of the internal dependency of Astro got stuck at the wrong version

Without a reproduction, there's nothing we can do, as this evidently works on fresh setups, otherwise we'd get a billion reports.

**Comment by brklntmhwk** [comment]
@Princesseuh 

Thank you for your quick response.
I modified my Github Actions workflow for deployment commenting out some parts related to deps cache and then it solved the error. As you pointed out, the discrepancy of deps caused it.
Your advice helped me find the problem that I'd overlooked.
