### ISSUE TITLE
Actions: navigation to url with query string appended on submit

### ISSUE THREAD

**Issue by atej** [withastro/astro#11582]
### Astro Info

```block
Astro                    v4.12.3
Node                     v20.16.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/react
                         astro:db
                         @astrojs/db/file-url
                         astro-icon
```

---

UPDATE: The issue is not isolated to forms in UI components. Even in Astro components:

```astro
<!-- form.astro -->
<form method="POST" action={actions.subscribe}>
```

leads to a navigation to `<url>?_astroAction=subscribe`

I guess the navigation is to be expected as that's the default behaviour of HTML forms. But how do I now achieve the behaviour I got with `getActionProps`  (I have `<ViewTransitions />` enabled).

---

### Describe the Bug

Defining a React form component like so:

```tsx
// ReactForm.tsx
type FormProps = React.DetailedHTMLProps<
  React.FormHTMLAttributes<HTMLFormElement>,
  HTMLFormElement
>

export function ReactForm({ onSubmit, children, ...delegated }: FormProps) {
  return (
    <form
      onSubmit={(ev) => {
        console.log('submitted!');
        onSubmit && onSubmit(ev);
      }}
      {...delegated}
    >
      {children}
      <input type="email" name="email" />
      <button type="submit">Submit</button>
    </form>
  );
}
```

and then using it like so:

```astro
<!-- index.astro -->
<ReactForm method="POST" action={actions.subscribe.queryString} client:idle />
```

Appends the query string `?_astroAction=subscribe` to the url i.e. the `method="POST"` is ignored.

In another case, the following error is produced:

```
Action was called from a form using a GET request, but only POST requests are supported. This often occurs if method="POST" is missing on the form.
```

The now deprecated `getActionProps` works as expected:
```astro
<!-- index.astro -->
<ReactForm method="POST"  client:idle>
  <input {...getActionProps(actions.subscribe)} />
</ReactForm>
```

### What's the expected result?

Passing the query string via the form `action` attribute should work like `<input {...getActionProps(...)} />`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-actions-issue-1?file=src%2Fpages%2Findex.astro

**Comment by bholmesdev** [comment]
Hey @atej! Thanks for reporting this issue. We realized this URL appending wasn't ideal, so we removed this in the latest version in favor of auto-redirects. Install the latest and let me know how it works for you.
