### ISSUE TITLE
Override Astro config using Container API and Vitest

### ISSUE THREAD

**Issue by ArmandPhilippot** [withastro/astro#11585]
### Astro Info

```block
Astro                    v4.12.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

According to the documentation, it is possible to [override Astro's configuration using Vitest](https://docs.astro.build/en/guides/testing/#vitest):

```
As of Astro 4.8, if you need to customize the Astro configuration applied in your tests, pass a second argument to getViteConfig()
```

I haven't tested with other configuration options (although I think I tried in the past with `site` with the same result) but with i18n it doesn't work. For example:

**astro.config.mjs**

```mjs
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  i18n: {
    defaultLocale: 'fr',
    locales: ['en', 'fr'],
  },
});
```

**vitest.config.ts**

```ts
/// <reference types="vitest" />
import { getViteConfig } from 'astro/config';

export default getViteConfig(
  {
    test: {
      environment: 'node',
      globals: false,
      watch: false,
    },
  },
  {
    i18n: {
      defaultLocale: 'en',
      locales: ['en', 'fr'],
    },
  }
);
```

**To note:** In Astro config, the default locale is `fr` while in Vitest config, with overriding, the default locale should be `en`.

Then, I realized that I was using the experimental Container API which is `currently scoped to allow testing of .astro component output in vite environments such as vitest` (see [Container reference](https://docs.astro.build/en/reference/container-reference/)).

So I figured that was where the problem was and that I needed to use options when creating a container. The documentation and the Typescript signature seems to be in conflict. The documentation only cites `renderers` and `streaming` as options while, in VSCode, the auto-completion also suggests (among others) `astroConfig`. So I tried to use:

```ts
import { experimental_AstroContainer as AstroContainer } from 'astro/container';

const container = await AstroContainer.create({
    astroConfig: { i18n: { defaultLocale: 'en', locales: ['en', 'fr'] } },
});
```

But with or without overriding Astro configuration in Vitest config file, it does not work.

In all my tests, the default language remains the one configured in `astro.config.mjs`.

For example, using this component:

```astro
---
const message = Astro.currentLocale === "en" ? "English version" : "Version française";
---

<div>{message}</div>
```

With these tests:

```ts
import { experimental_AstroContainer as AstroContainer } from 'astro/container';
import { describe, expect, it } from 'vitest';
import MultilingualComponent from './multilingual-component.astro';

describe('MultilingualComponent', () => {
  it('renders the french version by default', async () => {
    const container = await AstroContainer.create();
    const result = await container.renderToString(MultilingualComponent);

    expect(result).toContain('Version française');
  });

  it('renders the english version using container config', async () => {
    const container = await AstroContainer.create({
      astroConfig: { i18n: { defaultLocale: 'en', locales: ['en', 'fr'] } },
    });
    const result = await container.renderToString(MultilingualComponent);

    expect(result).toContain('English version');
  });
});
```

The first test always passes while the second always fails (even when overriding the configuration in Vitest).

#### Context

~~I'm building a French website with, now or later, an English version. Either way, during development, I want the English version to be available. For testing purposes, I'd like to use the English version as default language to avoid breaking tests if I change the configuration later. So I would like to be able to override the default configuration either via the Vitest configuration file or via the container configuration when creating it (the latter seems to be the best option).~~

---

**Edit:**
Finally, the context is not really relevant. In any case, some tests might break if the configuration changes.
However, I still think there is an issue here:
* either the configuration should be overwriteable in Container API or the `astroConfig` option should be removed from the `create` method to avoid confusion
* in the latter case, a note in the documentation about this might be useful (i.e. "*Astro configuration cannot be replaced with Container API and overriding the configuration in Vitest will not work when using Container API in Vitest.*"). 

---

### What's the expected result?

Using the previous tests, I expect the second test to pass (`expect(result).toContain('English version');` should be `true`). So I expect the configuration to be overwritten either at Vitest level or at container level. (I know Container API is still experimental so this feature may not be implemented yet but I wanted to point it out.)

It seems that even though the `astroConfig` option is available, it is [not used at container creation time](https://github.com/withastro/astro/blob/6aaeec5034cabf6a83e1949ec1ca8f50e7978cc1/packages/astro/src/container/index.ts#L276-L287). So I think the problem comes from there.

#### Reproduction

I put a [Stackblitz link](https://stackblitz.com/edit/astro-vitest-i18n-container-api?file=src%2Fpages%2Fen%2Findex.astro,src%2Fcomponents%2Fmultilingual-component.test.ts&on=stackblitz) with a minimal reproduction using i18n option. To see the issue, you should exit the dev server and execute `npm run test`. The test (`multilingual-component.test.ts`) and the component (`multilingual-component.astro`) are located in `src/components`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-vitest-i18n-container-api?file=src%2Fpages%2Fen%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
cc @ematipico

**Comment by ematipico** [comment]
The `astroConfig` option was initially added as a prototype to determine whether there was a valid use case; however, it was never documented. 

We will probably remove it.
