### ISSUE TITLE
Not working with Ionic

### ISSUE THREAD

**Issue by mariusbolik** [withastro/astro#11607]
### Astro Info

```block
Astro                    v4.13.1
Node                     v20.16.0
System                   macOS (x64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @sentry/astro
```

### Describe the Bug

I installed Ionic inside an Astro project:
```html
<script>
  import { initialize, loadingController, menuController, modalController, type IonicConfig } from '@ionic/core';
  import { defineCustomElements } from '@ionic/core/loader';
  import * as icons from 'ionicons/icons';
  import { addIcons } from 'ionicons';

  initialize({
    mode: 'ios'
  });
  defineCustomElements();

  for (const iconName in icons) {
    addIcons({ [iconName]: (icons as any)[iconName] });
  }
</script>
```

Config:
```ts
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  vite: {
    optimizeDeps: {
      exclude: [`@ionic/core/loader`], // needed for stencil
    },
  },
});
```

Everything works well after running `npx run dev`.
BUT after deployment (or in preview mode: `npx run preview`), there are some errors in the browser console:

<img width="1000" alt="Bildschirmfoto 2024-08-03 um 13 24 16" src="https://github.com/user-attachments/assets/25409d5f-936f-4995-a0f5-f1aa2c69e2ef">

### What's the expected result?

The Ionic/Astro App should behave the same while dev server is running and on server.
If you think this error is releated to Astro instead if Ionic, please let me know. In this case I'll copy this issue to the Astro repo.

Do I need to add something more to my vite config or do I need to include Stencil Web Components in another way?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-svnle1?file=src%2Flayouts%2FLayout.astro,src%2Fpages%2Findex.astro,astro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
The issue here is that stencil expects to be able to lazy-load the component JS, but those source files aren't available because Vite doesn't know about them. I'm not an expert in Stencil, but I think you have a couple of options. One is to [load Ionic from a CDN](https://stenciljs.com/docs/javascript), rather than from a node module. The other is to use [the `enableImportInjection` option](https://stenciljs.com/docs/config-extras#enableimportinjection), which seems like it's designed specifically for Vite.

**Comment by mariusbolik** [comment]
@ascorbic Thank you for helping! I really appreciate it! Loading Ionic from a CDN works, but I would really like to have everything based on my own domain and also want to use the typescript types for some ionic features like modals.
I updated the stackblitz demo, but sadly, the error still appears. It seems like Vite is not copying the needed files to the correct location. Does it possibly have something to do with how the Ionic components are imported?

**Comment by ascorbic** [comment]
> Does it possibly have something to do with how the Ionic components are imported?
Yes, it is exactly that. They expect to be able to construct a URL to import them, but Vite knows nothing about those files. I'm going to close this because it's not an Astro bug - it's just an issue with Stencil and Vite with a couple of workarounds
