### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by lbianfa** [withastro/astro#11616]
### Astro Info

```block
Astro                    v4.13.1
Node                     v20.11.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### Describe the Bug

I am trying to implement @splidejs/react-splide in my Astro project, in the following component.
![image](https://github.com/user-attachments/assets/015babb8-84e1-450d-b0ef-42d57a976b92)

But I am getting the following error.
![image](https://github.com/user-attachments/assets/58bab632-a5c6-4f22-91f2-a0a73b6671b5)

### What's the expected result?

"The successful compilation of the dependency.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-38yfim?file=src%2Fcomponents%2FSplideTest.jsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
The package is wrongly made https://publint.dev/@splidejs/react-splide@0.7.12

The ESM exports are being treated as CJS. You may be able to get it working through some of the settings described here: https://vitejs.dev/guide/dep-pre-bundling.html#customizing-the-behavior

**Comment by PTBYSR** [comment]
Have you solved this issue? Because I'm getting the exact same problem

**Comment by HawtinZeng** [comment]
+1
![image](https://github.com/user-attachments/assets/e6d2875b-3412-4e67-a5f5-3bf3f152123d)
It's annoying, we can't use ES module in Vue Component???

**Comment by tsulatsitamim** [comment]
![image](https://github.com/user-attachments/assets/308a84f6-bd6e-4a3f-a4f3-1d4a1065bd81)

I also cannot import lucide-react icon in react component

**Comment by tsulatsitamim** [comment]
![image](https://github.com/user-attachments/assets/60daca77-6cdb-4bca-a6b6-229f834bf8e8)
cannot import lucide react icon in react component
