### ISSUE TITLE
Imported global stylesheet is injected into every page

### ISSUE THREAD

**Issue by farshed** [withastro/astro#11614]
### Astro Info

```block
Astro                    v4.13.1
Node                     v20.12.1
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/react
```

### Describe the Bug

I am importing my global Saas stylesheet file into a layout like this.

```js
import '../styles/global.scss';
```

The stylesheet's content is being injected into the head of every page that uses the layout.
```html
<head>
   <style>
       <--- global stylesheet's content --->
   </style>
<head>
```

### What's the expected result?

I want to have the global stylesheet linked inside the head instead so the browser can cache it. I've been through the docs and haven't found a way to achieve this.

```html
<head>
   <link rel="stylesheet" href="/compiled-global.css">
</head>
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
See https://docs.astro.build/en/reference/configuration-reference/#buildinlinestylesheets. It's not possible to tell what's wrong in your case as there's no repro.
