### ISSUE TITLE
Endpoint context.request is empty

### ISSUE THREAD

**Issue by drag0n-app** [withastro/astro#11629]
### Astro Info

```block
Astro                    v4.13.1
Node                     v22.3.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

test.astro
```html
<a href=`/endpoint`>test</a>
```

endpoint.ts
```ts
import type { APIRoute, APIContext } from 'astro';

export const GET: APIRoute = (context: APIContext) => {
    return new Response(JSON.stringify(context.request, null, 2));
}
```
run project and click the link "test", endpoint response "{}"

### What's the expected result?

It should contains url, headers, method

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-n9thac?file=src%2Fpages%2Ftest.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
The request **is there**. Try `console.log` and you'll see data. Simply, the `Request` object isn't serialisable via `JSON.stringify`
