### ISSUE TITLE
getRelativeLocaleUrl doesn't work correctly with `trailingSlash: 'never'`

### ISSUE THREAD

**Issue by Vipermaseg** [withastro/astro#11630]
### Astro Info

```block
Astro                    v4.13.1
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

My header has a logo that is supposed to go to my index: htt-p://mysite.com, and when I am in Portuguese I should get the link htt-p://mysite.com/pt

Using getRelativeLocaleUrl(locale, "/") will yield:
locale = en -> htt-p://mysite.com
locale = es -> htt-p://mysite.com/es/

Using getRelativeLocaleUrl(locale) will yield:
locale = en -> htt-p://mysite.com/example
locale = es -> htt-p://mysite.com/es

Where "example" could be any page I am currently at.

### What's the expected result?

Using getRelativeLocaleUrl(locale, "/") should yield:
locale = en -> htt-p://mysite.com
locale = es -> htt-p://mysite.com/es

Using getRelativeLocaleUrl(locale) should yield:
locale = en -> htt-p://mysite.com
locale = es -> htt-p://mysite.com/es

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-weczql?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
This is an incorrect usage of the API. Check the examples here: https://docs.astro.build/en/reference/api-reference/#getrelativelocaleurl

The second argument is **appended** to the locale. The utility is meant to make the construction of the paths easier, but it doesn't check if what you provide in the second argument follows the configuration.
