### ISSUE TITLE
Zod refine on Server Actions input causes undefined values

### ISSUE THREAD

**Issue by adamburmister** [withastro/astro#11641]
### Astro Info

```block
Astro                    v4.13.1
Node                     v22.5.1
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/sitemap
                         @astrojs/tailwind
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

ssr

### Describe the Bug

When using Zod `.refine` (et al) the Server Actions handlers appear to not parse the action inputs.
The action progresses past input validation and passes `undefined` into the handler.

### What's the expected result?

The `refine` should run in addition to the regular `zod.object` and block the handler execution.

This is the Zod behaviour expected as shown in the Zod Playground
https://zod-playground.vercel.app?appdata=N4IgzgxgFgpgtgQxALhALwDoDsAEf8B0A9gEYBWMEALgBTDb6M4AOCYYA7kQE4AmyOTLiaMCYKtwCWWAOZ0ccGOwQyYAgOQAFADYw2MFtyIA3SbwMIcEInGa6AHizacevdTgC%2BASgYjCcaRoADgAaHGAFJTAVNRwtZy4%2BBQBXcRwSCyocXTYsoKsoBG4EahhuMHdvXz8cAkR7GgBmACYwiMVlVQ1NBNcUtIzsqJwqQtwWgqKSqjKKzy8Q6qZrLAAzSW44HvZE-kExCWk5dqiY7pywAxX1zZwATyJk7icd10qFpbwq4VFuGHWsDAaJ98DRjAhtMklF4cABeAB84RBjD%2BVCeuHBkKUBFYrySsIJOExULABGuGy2vT4AG5kZ5Fj8mPRGSIOtEunFti4%2BGAcLwiDgsEQsogqNB1AyanhWKMBABtdTkzZc3bqAC6kr8HhBXhAIRAxKUKDlIGAuO5ewwIHNuwAjM1GlawkrKXjLdaqbx7Y6QB4QBqDbNJEQsCgQI0CA6CEFfUA

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fzlfgy?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bryanwood** [comment]
https://github.com/withastro/astro/blob/main/packages/astro/src/actions/runtime/virtual/server.ts#L86-L106

When there's some Zod schema object with a `.refine()` chained onto it the resulting schema object is not an instance of `z.ZodObject` anymore, it's `z.ZodEffects`. This causes the handler to receive unparsed input. 

Maybe this should inspect the schema object to see if it's z.ZodEffects and extract the inputSchema.innerType() if it is to do the FormData to object parsing then use the original inputSchema to do the validation?
