### ISSUE TITLE
Unknown file extension ".ts" when using @astrojs/svelte 

### ISSUE THREAD

**Issue by ocavue** [withastro/astro#11667]
### Astro Info

```block
Astro                    v4.13.3
Node                     v18.20.2
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/svelte
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

I created a minimal repo to describe this issue.

1. Open https://pr.new/github.com/issueset/astro-monorepo-svelte-ts-error (or clone https://github.com/issueset/astro-monorepo-svelte-ts-error locally)
2. `pnpm install`
3. `pnpm run dev`

You will see the following error in the browser:

```
Unknown file extension ".ts" for /home/issueset/astro-monorepo-svelte-ts-error/packages/is-even/src/index.ts
```

I found that if I remove `@astrojs/svelte` in `playground/astro.config.mjs`, this error doesn't occur anymore. Considering that `playground/` is not using Svelte at all (i.e. You can see that the svelte component is commented out in `playground/src/pages/index.astro`), I suspect that there is a bug in `@astrojs/svelte`.

### What's the expected result?

No error.

### Link to Minimal Reproducible Example

https://pr.new/github.com/issueset/astro-monorepo-svelte-ts-error

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
This isn't an Astro error, but how you set up the monorepo and how to load typescript (source) files from a monorepo. I don't have a solution for you, but maybe on Discord someone knows how to do it.

**Comment by ocavue** [comment]
Thanks for your reply. I believe both Vite and Astro support loading typescript from a monorepo directly, as you can see from my repo which works fine with only `@astrojs/react`. This strategy is widely used, for example it's included in Turborepo's docs ([link](https://turbo.build/repo/docs/core-concepts/internal-packages#just-in-time-packages)).

However, I'm not sure which plugin breaks the ability to import `.ts` files directly, `@astrojs/svelte` or underlay `@sveltejs/vite-plugin-svelte`.

**Comment by leekeh** [comment]
Did you figure this one out? Ran into the same issue.
