### ISSUE TITLE
Vite Config cspNonce

### ISSUE THREAD

**Issue by bnjmnrsh** [withastro/astro#11669]
### Astro Info

```block
Astro                    v4.13.1
Node                     v21.7.3
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-icon
                         @kindspells/astro-shield
                         astro-purgecss
```

### Describe the Bug

Passing the following config to Astro does not create the expected output as outlined in [Vite's docs](https://vitejs.dev/guide/features#content-security-policy-csp)

```JavaScript
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  vite: {
    html: {
      cspNonce: '1234',
    },
  },
});
``` 

### What's the expected result?

As per [Vite's docs](https://vitejs.dev/guide/features#content-security-policy-csp), a meta tag should be added to the head:

```html
<meta property="csp-nonce" nonce="PLACEHOLDER" />
```
and scripts and styles should be given `nonce="PLACEHOLDER"` attributes. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-vite-cspnonce

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
The Vite CSP config only applies to Vite-controlled HTML files only, which doesn't happen in Astro, so it doesn't work by default. If Astro were to support CSP configs, it'd probably be through its own Astro config, and I think it's more of a feature request in that case.

I think it would be better to create a discussion at https://github.com/withastro/roadmap if this is something you'd like to see. There's also https://github.com/withastro/roadmap/discussions/377 which seems somewhat related. 

Closing this for now as we keep feature requests in the roadmap repo, and this isn't quite a bug in Astro.

**Comment by bnjmnrsh** [comment]
@bluwy Thank you for the explanation. The [docs](https://docs.astro.build/en/reference/configuration-reference/#vite) don't provide any guidance as to what of Vite's config can be modified. I'll open a separate issue to clarify this to save others time if they come down this road. I'll contribute to the roadmap discussions where I can.
