### ISSUE TITLE
Custom lit converter not being called

### ISSUE THREAD

**Issue by lp247** [withastro/astro#11670]
### Astro Info

```block
Astro                    v4.13.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/lit
```

### Describe the Bug

File src/components/A.js is a lit component with a custom converter for the attribute 'text'. This converter should convert the attribute given as text to the length of the text. This converter is not called.

### What's the expected result?

The converter should be called and the rendered text should be "6" instead of "AAAAAA".

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kwbwgy?file=src%2Fcomponents%2FA.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JulianCataldo** [comment]
<img width="754" alt="Screenshot 2024-08-21 at 21 08 32" src="https://github.com/user-attachments/assets/f2fb76f2-7b01-46b5-95ac-488f1370e611">
<img width="944" alt="Screenshot 2024-08-21 at 21 10 31" src="https://github.com/user-attachments/assets/1857743f-4bc3-4c49-9a0e-ee02ae8ae16f">

Quick and dirty test. Sorry for the screenshots.

Some observations:

- Properties are not serialized at all, independently of the Lit converter thing. This is weird, I don't remember such a glaring issue.
- Loading `MyTest` once, and subsequently, `<my-test>` will me picked up and rendered as such.
- Removing MyTest import, restart server, Astro's Custom Element Registry implementation doesn't pick up `<my-test>` anymore.
- Import the component in a client script tag, and the client component is picked up again, this time with the serialized attributes. Wut?

This is not very scientific, just poking around. I don't understand what is going on.

**Comment by florian-lefebvre** [comment]
In 5.0, we [removed the Lit integration](https://5-0-0-beta.docs.astro.build/en/guides/upgrade-to/v5/#removed-the-lit-integration) so we don't plan to address this issue. If you’re interested in maintaining a Lit integration yourself, you may wish to use the [last published version of `@astrojs/lit`](https://github.com/withastro/astro/tree/astro%404.13.0/packages/integrations/lit) as a starting point and upgrade the relevant packages.
