### ISSUE TITLE
i18n and rewrites do not output the right files

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#11690]
### Astro Info

```block
Astro                    v4.13.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When using i18n and rewrites, rewriting a path does not create the right file:

1. Rewrite from `/fr/a-propos` to `/fr/about`
2. Return 404 on `/fr/about`
3. Once built, I get `/fr/about.html`

### What's the expected result?

Once built, I should get`/fr/a-propos.html` instead

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kckvir?on=stackblitz

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
I tried to workaround it but I don't think it's possible atm:
- Rewriting to `/404` causes `/fr/about` content to be the same as 404, so I can't just rename some files
- If instead of rewriting to `/404` I just return `new Response(null, { status: 404 })`, no file is emitted for `/fr/about`

**Comment by florian-lefebvre** [comment]
Can you confirm if those things are relevant if I want to look into the issue?
- https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/generate.ts#L446-L451
- pipeline.tryRewrite/#executeRewrite

**Comment by ematipico** [comment]
I looked at the issue, and this is a known limitation in SSG. The starting route `/fr/a-props` doesn't actually exist on disk, so when the build triggers, Astro doesn't know that the user wants to create `/fr/a-props`. 

The only way to achieve that is with a catch all route, in SSR. 

However, we do plan to lift this limitation somehow in the near future.
