### ISSUE TITLE
Dynamic import and rendering of Framework component throws Could not render `ComponentName`. No matching import has been found for `ComponentName`

### ISSUE THREAD

**Issue by JakubFaltyn** [withastro/astro#11701]
### Astro Info

```block
Astro                    v4.13.4
Node                     v22.3.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
                         astro-icon
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

In the company I'm working for, we mostly build static websites using Directus CMS. Our clients have the ability to change not only the content within the app but also which components should be displayed on the current page and in what order. The problem is that dynamically importing and rendering components works well only if it's an Astro component. Interestingly, UI Framework components work well only if they don't have any client directives (so when they're just static), otherwise, they throw the following error:
`NoMatchingImport: Could not render 'Component'. No matching import has been found for 'Component'`

Example code for varius cases:
1. Normal import
```
//Work well
import Component from "../components/Component.tsx"
<Component client:load>
```
2. Import with change of name
```
//Dont work and throws No matching import error
import Component from "../components/Component.tsx"
const ComponentCustomName = Component

<Component client:load>
```
3. Import with change of name and render it staticly
```
//Work well but its static
import Component from "../components/Component.tsx"
const ComponentCustomName = Component

<Component client:load>
```

So, when I need to map over items to get my component, it never works as expected:
```
const componentConfigs = await Promise.all(
  page.blocks.map(async (block) => {
    const componentName = block.item.component_name
    const config = componentMapping[componentName]
    
    let importedModule
    if (config.extension === 'astro') {
      importedModule = await import(`../components/${config.path}.astro`)
    } else {
      importedModule = await import(`../components/${config.path}.tsx`)
    }
    
    return {
      componentName,
      importedModule,
      clientDirective: config.clientDirective,
      isReact: config.extension !== 'astro'
    }
  })
)

// Create an object with component names as keys and imported components as values
const Components = Object.fromEntries(
  componentConfigs
    .filter(config => config !== null)
    .map(config => [config.componentName, config.isReact ? config.importedModule.default : config.importedModule.default])
)
```
```

 {componentConfigs.map((info, index) => {
      if (!info) return null
      const { componentName, clientDirective, isReact } = info
      const Component = Components[componentName]
      const props = page.blocks[index].item
      
      if (isReact) {
        if (clientDirective === 'load') {
          return <Component key={index} {...props} client:load />
        } else {
          return <Component key={index} {...props} />
        }
      } else {
        return <Component key={index} {...props} />
      }
    })}
```

### What's the expected result?

Be able to properly render component with client:load directive

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sdac4n?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sebgron** [comment]
I’m facing the same problem as described.

**Comment by dstudnicki** [comment]
I had the same problem a while ago!

**Comment by Princesseuh** [comment]
At this time, this is an intentional limitation. See this previous issue on the subject: https://github.com/withastro/astro/issues/5415

and documented here: https://docs.astro.build/en/basics/astro-syntax/#dynamic-tags

**Comment by evertonadame** [comment]
Is there any possibility of reopening this issue? I've tried using virtual imports with Vite plugins, and it works well as long as there are no client directives.

Is there no way to dynamically import framework components that have client directives?

**Comment by shjyh** [comment]
I created a small integration to handle this use case.

Package: [astro-dynamic-component](https://www.npmjs.com/package/astro-dynamic-component).

You can use like this:

```astro
// support any glob
import DynamicComp from "dc:load:./_types/*.vue";

---

<DynamicComp comp="comp_name" />

```
