### ISSUE TITLE
pnpm create astro skips installing deps and git 

### ISSUE THREAD

**Issue by hkbertoson** [withastro/astro#11738]
### Astro Info

```block
Using 

pnpm 9.7.1
Node 20.16.0
```

### Describe the Bug

![CleanShot 2024-08-15 at 13 55 37@2x](https://github.com/user-attachments/assets/0c430180-7b4a-46b3-803d-c7f1dcbd5a2e)
When running `pnpm create astro` it is skipping installing deps and git. 

### What's the expected result?

It should work just like `npm` and `yarn` do. 

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Fixed in https://github.com/withastro/astro/pull/11733

**Comment by hkbertoson** [comment]
@bluwy This issue is still happening

**Comment by bluwy** [comment]
I just reran it and it's still working fine. Is pnpm caching an older version somehow?

**Comment by hkbertoson** [comment]
What version of pnpm are you running?

**Comment by hkbertoson** [comment]
I did `pnpm store prune` and then tried again and still same issue.

**Comment by bluwy** [comment]
pnpm v8.15.6 and v9.6.0, which both works for me. Maybe try `npm create` to see if it's really an issue with the latest version, or some sort of pnpm cache issue?

**Comment by hkbertoson** [comment]
`npm create` works just fine for me. I ran it on a different machine with a fresh install of pnpm and it worked just fine as well. Im using v9.7.1

The other machine was a windows machine.
