### ISSUE TITLE
context.site is undefined when using the "--site https://foo.com" CLI argument

### ISSUE THREAD

**Issue by nlnw** [withastro/astro#11731]
### Astro Info

```block
Astro                    v4.14.1
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

all

### Describe the Bug

When using the "--site" option, the site should be available through the APIContext, but it now returns undefined. This was working correctly in `4.13.3`.

```
astro dev --site https://foo.com
```

```
import type { APIContext } from 'astro';

export async function GET(context: APIContext) {
  return new Response(
    JSON.stringify({
      site: context.site,
    })
  );
}
```

### What's the expected result?

The APIContext.site field should not be undefined.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nlnw** [comment]
Now that’s what I call good service! Thanks @bluwy !

**Comment by bluwy** [comment]
I did broke it first, but thanks 😅 (and sorry about that)
