### ISSUE TITLE
Error unterminated string literal when you have a string that contains `</script>`

### ISSUE THREAD

**Issue by afiiif** [withastro/astro#11752]
### Astro Info

```block
Astro                    v4.12.3
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

Error when you have code like this:

```js
const myInnocentString = "Lorem ipsum </string> dolor sit amet"
```

I know I can split the `</script>` part into something like `"</sc" + "ript"`,
but I consider this as a false alarm, and will be nice if this get fixed.

<img width="560" alt="Screen Shot 2024-08-17 at 06 11 10" src="https://github.com/user-attachments/assets/de4e0b0c-35c0-43a3-bf9f-bd1a8b4858d9">

### What's the expected result?

It should not throw any error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8seqds?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Astro parses the HTML like browsers, and in browsers, you also can't write the `</script>` that way as is. It'll assume that's the end tag and parses the rest as HTML. I don't think this is something we'll fix.
