### ISSUE TITLE
bunx @astrojs/upgrade fails

### ISSUE THREAD

**Issue by claughinghouse** [withastro/astro#11750]
### Astro Info

```block
$ astro info
Astro                    v4.14.2
Node                     v22.6.0
System                   macOS (x64)
Package Manager          bun
Output                   static
Adapter                  astro-sst
Integrations             @astrojs/starlight
                         @sentry/astro
```

### Describe the Bug

When running `@astrojs/upgrade` with bun, the command errors out attempting to run the yarn package manager instead of bun. 

```
# bunx @astrojs/upgrade                                                                                                                                                                          

 astro   Integration upgrade in progress.

      ◼  @astrojs/check is up to date on v0.9.2
      ●  astro will be updated to v4.14.2
      ●  @astrojs/starlight will be updated to v0.26.1

 ██████  Installing dependencies with yarn...

      ▲  error Dependencies failed to install, please run the following command manually:
yarn add @astrojs/starlight@0.26.1 astro@4.14.2
```

### What's the expected result?

Replacing `yarn` with `bun` results in a successful upgrade:

```
# bun add @astrojs/check@^0.9.2 @astrojs/starlight@^0.26.1 astro@^4.14.2                                                                                                                         
bun add v1.1.24 (85a32991)

installed @astrojs/check@0.9.2 with binaries:
 - astro-check
installed @astrojs/starlight@0.26.1
installed astro@4.14.2 with binaries:
 - astro

16 packages installed [2.18s]
```

### Link to Minimal Reproducible Example

I am not able to reproduce in stackblitz since the issue exists when upgrading using the bun package manager. 

~https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics~

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
We don't support bun. Bun is a drop in replacement for Node.js, so if something works with Node.js but not bun, you should file an issue with bun

**Comment by Jarred-Sumner** [comment]
> We don't support bun. 

It does seem to recognize bun

<img width="495" alt="image" src="https://github.com/user-attachments/assets/f16f436f-dd98-4fb6-8373-7ebe4dd5c6dd">
