### ISSUE TITLE
how to add xmlns in astro

### ISSUE THREAD

**Issue by e5h8** [withastro/astro#11757]
### Astro Info

```block
v20.3.0
```

### If this issue only occurs in one browser, which browser is a problem?

chrome

### Describe the Bug

```
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xmlns:th="http://www.thymeleaf.org">
	<head>
		<meta charset="UTF-8" />
		<meta name="description" content="Astro description" />
		<meta name="viewport" content="width=device-width" />
		<link rel="icon" href="/favicon.ico" />
		<meta name="generator" content={Astro.generator} />
		<title>{title}</title>
	</head>
	<body>
		<slot />
	</body>
</html>
```
show error :
Type '{ children: any[]; xmlns: string; lang: string; }' is not assignable to type 'HtmlHTMLAttributes'.
  Property 'xmlns' does not exist on type 'HtmlHTMLAttributes'.

### What's the expected result?

I need add thymeleaf namespace

### Link to Minimal Reproducible Example

no

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Astro assumes you're in the modern ages building a HTML5 website, not XHTML. Are you intentionally building a XHTML website?
