### ISSUE TITLE
Image loading issue in tabs

### ISSUE THREAD

**Issue by Bhargav-92** [withastro/astro#11755]
### Astro Info

```block
Astro                    v4.14.2
Node                     v20.13.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

I'm using React and Shadcn's Tabs component. There are 3 tabs, each containing images, and I have placed the images in the /public directory. The problem is that the images load when the tabs are changed.

[Github repo ](https://github.com/Bhargav-92/Astro-Image-Issue/tree/main)

[Hosted preview](https://main--astro-tabs-image-issue.netlify.app/)

### What's the expected result?

Images must load when the page is rendered not when tabs change.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/Bhargav-92/Astro-Image-Issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
That's how the web works. Typically you want to use either a preload of the image, or different CSS so that the browser still load the image (the common cause is using display: none instead of visibility: hidden)
