### ISSUE TITLE
`ActionAPIContext` not exported like `APIContext`

### ISSUE THREAD

**Issue by Fryuni** [withastro/astro#11764]
Currently, the context value type used on actions must be imported from `astro/actions/runtime/utils.js`. It should be exported from `astro` like `APIContext` or at least from `astro:actions`.

Without this, organizing the project's code for reusability depends on the internal organization of the actions runtime modules.

**Comment by ematipico** [comment]
Can you provide an example of where this type is needed?

**Comment by Fryuni** [comment]
Same as for `APIContext`, for code organization. For example, if I want to make something like this:

```ts
import type { APIContext } from 'astro';

function extractUser(ctx: APIContext) {
  // Can look at headers, URL, cookies, etc.
}

function setUser(ctx: APIContext) {
  // Set the cookies, but reads the URL and headers to determine the appropriate cookie options
}
```

Those can be used by any API route that shares those functionalities. If I want to do the same to share code between actions:

```ts
import type { ActionAPIContext } from 'astro/actions/runtime/utils.js';

function extractUser(ctx: ActionAPIContext) {}

function setUser(ctx: ActionAPIContext) {}
```

There are workarounds for this by wrapping all the API in an object and putting it in the `locals`, but that way too much to do for every common piece of code. Some code is shared only between a few actions and may be colocated with them, adding those functions to `locals` would make them accessible by every action, route and page.

**Comment by bholmesdev** [comment]
Sounds like a good suggestion! We've been exposing utility types from `astro:actions`, so I'd expect us to continue this pattern.
