### ISSUE TITLE
ViewTransitions break theme controller

### ISSUE THREAD

**Issue by BOTShaneZA** [withastro/astro#11781]
### Astro Info

```block
Astro                    v4.13.1
Node                     v18.17.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         astro-auth
                         @astrojs/react
```

### Describe the Bug

Enabling ViewTransitions clears theme value on html tag.

I am busy using DaisyUi with theme controller to do some theming with my astro site and I noticed that on page navigation after adding the ViewTransitions routing component the data-theme attribute on the html tag would get cleared.

### What's the expected result?

I guess don't clear additional attributes that have been added onto the html tag

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-aige1b?file=src%2Flayouts%2FLayout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You want to use events to restore state such as that. See https://docs.astro.build/en/guides/view-transitions/#astrobefore-swap
