### ISSUE TITLE
SolidJS's `attr:` syntax doesn't work in astro integration

### ISSUE THREAD

**Issue by gersomvg** [withastro/astro#11792]
### Astro Info

```block
Astro                    v4.14.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
```

### Describe the Bug

Solid's `attr:` syntax broken in astro:
https://stackblitz.com/edit/github-vunq7y?file=src%2Fcomponents%2FSolidComponent.tsx

The funny thing is that locally after triggering HMR by updating a file it **does work**. It just doesn't work on first render.

It works outside of astro:
https://playground.solidjs.com/anonymous/3fc352bc-7d8d-4031-b510-4ae5ceca35c0

### What's the expected result?

For example `attr:onclick` should be replaced by `onclick` on the resulting HTML element:
https://playground.solidjs.com/anonymous/3fc352bc-7d8d-4031-b510-4ae5ceca35c0

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vunq7y?file=src%2Fcomponents%2FSolidComponent.tsx
https://playground.solidjs.com/anonymous/3fc352bc-7d8d-4031-b510-4ae5ceca35c0

**Comment by gersomvg** [comment]
Ah, its a bug in solid https://discord.com/channels/722131463138705510/1275467267865444434/1275478781179596893

Keep this issue open until its fixed upstream, or close it?

**Comment by florian-lefebvre** [comment]
Ryan said it looks like a solid only bug. I'm going to close this issue but feel free to reopen/comment if it turns out to be an astro issue as we
