### ISSUE TITLE
Catch all page ([...slug].astro) catch all Server island requests

### ISSUE THREAD

**Issue by dylanalizon** [withastro/astro#11793]
### Astro Info

```block
Astro                    v4.14.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

All requests from the server islands (/_server-islands/*) are caught by the catchall page ([...slug].astro). This works locally but when you run `npm run build` and `npm run preview` or deploy (tested on Vercel) server island requests are caught by the route.

### What's the expected result?

All server island requests (/_server-islands/*) must not be caught by the [...slug].astro page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wmamgi?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
@Fryuni do you think it's fixed by the global route priority flag?

**Comment by dylanalizon** [comment]
> @Fryuni do you think it's fixed by the global route priority flag?

I've just tested it, but it doesn't fix the problem.

**Comment by Fryuni** [comment]
I think the server islands route is being appended after the routes get sorted

**Comment by pablopunk** [comment]
Not only catch-all routes but also 2-level routes like `/[team]/[user].astro` since that will match `/_server-islands/ComponentName`

**Comment by tedevra** [comment]
in the final build that is being deployed, there is no route file for _server-islands...

i think that this is the reasong behind this problem, the file is missing, so requests to urls that start with "*/_server-island*" will be caught by the custom catch all routes of the project. 
Could have something to do with the adapter that performs the build transformations for the specific environment (cloudflare, vercel, ...)?

For example: Astro adds a route file for Actions, if you are using that feature:
![image](https://github.com/user-attachments/assets/6a4e0b2e-ba31-45d6-878f-b99113e02b96)
but no "/pages/_server-islands/_---path_.astro.mjs"
