### ISSUE TITLE
The environment variables are not obtained that set in the dashboard for deployment on Cloudflare

### ISSUE THREAD

**Issue by sgalcheung** [withastro/astro#11830]
### Astro Info

```block
Astro                    v4.14.5
Node                     v18.20.3
System                   macOS (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         astro-icon
```

### If this issue only occurs in one browser, which browser is a problem?

No browser related

### Describe the Bug

Its origin from https://github.com/withastro/astro/issues/11246

I have also created a new topic in Cloudflare Comunity: [Difference deploy behavior from wrangler CLI and Cloudflare website](https://community.cloudflare.com/t/difference-deploy-behavior-from-wrangler-cli-and-cloudflare-website/702540)

### What's the expected result?

Get Cloudflare Dashboard env vars.

### Link to Minimal Reproducible Example

https://github.com/sgalcheung/balanced-chef

### Participation

- [ ] I am willing to submit a pull request for this issue.
```[tasklist]
### Tasks
```

**Comment by ascorbic** [comment]
Cloudflare does environment variables differently than other runtimes. See [this guide](https://docs.astro.build/en/guides/integrations-guide/cloudflare/#cloudflare-runtime) for details

**Comment by sgalcheung** [comment]
I have read this doc and Cloudflare doc, it seems that no on has mentioned how to obtain the parameters of the dashboard configuration.

**Comment by sgalcheung** [comment]
Astro 5.0 Beta introduction [Stable: astro:env](https://astro.build/blog/astro-5-beta/#stable-astroenv) solved this.
