### ISSUE TITLE
Image component generates the unused original image only when reading the image property.

### ISSUE THREAD

**Issue by tenpaMk2** [withastro/astro#11887]
### Astro Info

```block
Astro                    v4.15.1
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

`<Image>` generates unused original images only when reading its property (like `.width` ).

## Example

See the StackBlitz that is created from the empty project template.

Whether or not `<Image>` generates the original image depends on whether or not the `.width` property is read.

The following code generates the original image.

```astro
---
import myImage from "../sample.png";
import { Image } from "astro:assets";
---

...

<Image
  src={myImage}
  alt={`width is ${myImage.width}`}
  format="webp"
  widths={[240, 540]}
  sizes={`(max-width: 360px) 240px, 540px`}
/>
```

The following files are generated in the `dist/_astro` directory.

- `sample.DRk6a-UB.png` <- The original image that is unused!!
- `sample.DRk6a-UB_2wRPSH.webp`
- `sample.DRk6a-UB_AXNuM.webp`
- `sample.DRk6a-UB_ZbJNag.webp`

Strangely enough, if you delete `${myImage.width}` , the original image is not generated.

## Related issues?

- #8143
- #4961
- #8866

### What's the expected result?

The original image should not be generated in the `_astro` directory because it's never used in HTML.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jovs8y?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
At the moment this is kinda intended, to be on the safer side regarding keeping images that might be needed. I think it would be possible to just limit it to src though.

**Comment by tenpaMk2** [comment]
OK, thanks.
I will implement the following workarounds.
https://github.com/withastro/astro/issues/4961#issuecomment-2317515695
