### ISSUE TITLE
Vitest not able to render Astro components with React/Preact children.

### ISSUE THREAD

**Issue by dvelasquez** [withastro/astro#11882]
### Astro Info

```block
Astro                    v4.15.1
Node                     v20.15.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/preact
                         @astrojs/react
```

### Describe the Bug

Vitest container api don't work with astro components that have the directive `client:only="preact"` or `client:load` and load a react/preact children.

Here is the component test:
```ts
import { experimental_AstroContainer as AstroContainer } from 'astro/container';
import { getContainerRenderer } from '@astrojs/preact';
import { loadRenderers } from 'astro:container';
import { expect, test } from 'vitest';
import Index from './index.astro';

test('Header tests', async () => {
  const renderers = await loadRenderers([getContainerRenderer()]);
  const container = await AstroContainer.create({ renderers });
  const result = await container.renderToString(Index);

  expect(result).toContain(/This is a preact island/);
});
```
This throws the following error:
```NoClientEntrypoint: `Island` component has a `client:only` directive, but no client entrypoint was provided by `@astrojs/preact`.```

When adding the client entrypoint with `container.addClientRenderer` the code looks like this:
```ts
test('Header tests', async () => {
  const renderers = await loadRenderers([getContainerRenderer()]);
  const container = await AstroContainer.create({ renderers });

  container.addClientRenderer({
    name: '@astrojs/preact',
    entrypoint: '@astrojs/preact/client.js',
  });

  const result = await container.renderToString(Index);

  expect(result).toContain(/This is a preact island/);
});
```

And throws the following error
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
```

### What's the expected result?

Container API is able to render the Astro component and it framework children components.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-utorbc?file=src%2Fpages%2Findex.test.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Please add the server renderer manually: https://docs.astro.build/en/reference/container-reference/#adding-a-renderer-manually

**Comment by dvelasquez** [comment]
I changed the code to this:

```ts
import { experimental_AstroContainer as AstroContainer } from 'astro/container';
import preactRenderer from '@astrojs/preact/server.js';
import { expect, test } from 'vitest';
import Index from './index.astro';

test('Header tests', async () => {
  const container = await AstroContainer.create();

  container.addServerRenderer({
    name: '@astro/preact',
    renderer: preactRenderer,
  });

  container.addClientRenderer({
    name: '@astrojs/preact',
    entrypoint: '@astrojs/preact/client.js',
  });

  const result = await container.renderToString(Index);

  expect(result).toContain(/This is a preact island/);
});

But vitest is still throwing an unhandled error
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
```
```

**Comment by ematipico** [comment]
Thank you

**Comment by ematipico** [comment]
Actually the code for adding the server renderer is incorrect, check the docs please, and report back

**Comment by dvelasquez** [comment]
The documentation says the server renderer don't have a name, but typescript complains if a name is not given. Anyway, the same unhandled error persist when updating the code to how is in the documentation.

<img width="693" alt="Screenshot 2024-08-30 at 11 01 19" src="https://github.com/user-attachments/assets/d913c5d7-6336-4bd8-baa9-a6f457e65897">

**Comment by joshualouisjenson** [comment]
I am getting similar issues when trying to load a Vue component. SSR and bundling appears to work fine (I can see the component CSS and JS loaded into the browser) but the hydration step fails with the following errors in the console:
![image](https://github.com/user-attachments/assets/89d99b94-f217-4feb-8e0f-e581f93339ff)

**Comment by dvelasquez** [comment]
I've updated the astro versions and astro adapters and now is working.

Here is my updated info version

```bash
﻿Astro                    v4.15.6
Node                     v20.15.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/preact
﻿﻿﻿```
