### ISSUE TITLE
Vue useId cannot generate unique identifiers for islands

### ISSUE THREAD

**Issue by MRamonLeon** [withastro/astro#11881]
### Astro Info

```block
Astro                    v4.15.1
Node                     v20.5.1
System                   macOS (arm64)
Package Manager          unknown
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/vue

```

### If this issue only occurs in one browser, which browser is a problem?

All browsers.

### Describe the Bug

I would like to have unique ids when using new Vue 3.5 `useId` method in different Astro islands. Basically apply the same you did at https://github.com/withastro/astro/pull/6976. This issue would be the equivalent of https://github.com/withastro/astro/issues/6849 for Vue 3.5 release.

### Current _improvable_ result
<img width="1602" alt="Screenshot 2024-08-30 at 10 08 26" src="https://github.com/user-attachments/assets/1aa9a811-25f0-4f32-9082-06e6b6cfff32">

### What's the expected result?

We have a way to generate unique ids for each island using Vue's `useId` or the recommended Astro method.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/MRamonLeon/AstroAndVue35UseId?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Looking forward to your PR!

**Comment by MRamonLeon** [comment]
@ematipico Sorry I checked the _Participation_ check by mistake.

**Comment by ematipico** [comment]
PRs welcome, if someone has knowledge of Vue
