### ISSUE TITLE
ASTRO_DB_APP_TOKEN environment variable not being recognized for Astro DB libSQL

### ISSUE THREAD

**Issue by edburtnieks** [withastro/astro#11890]
### Astro Info

```block
Astro                    v4.15.1
Node                     v22.5.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

Hi, couldn't figure out why `ASTRO_DB_APP_TOKEN` environment variable as per [documentation](https://docs.astro.build/en/guides/astro-db/#libsql) wasn't being recognized, and everytime I used `astro build --remote`/`astro db push --remote` I was prompted to link my project to Astro Studio

However, replacing `ASTRO_DB_APP_TOKEN` with `ASTRO_STUDIO_APP_TOKEN` worked like a charm and as expected

So my `.env` file looks like this

```.env
ASTRO_DB_REMOTE_URL=libsql://...
ASTRO_STUDIO_APP_TOKEN=...
```

---

Related PR - https://github.com/withastro/astro/pull/11385

---

By the way, huge thanks for rolling out this feature, love this :pray: 

### What's the expected result?

The `ASTRO_DB_APP_TOKEN` environment variable is being recognized and doesn't prompt you to link your project in Astro Studio

```.env
ASTRO_DB_REMOTE_URL=libsql://...
ASTRO_DB_APP_TOKEN=...
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jm88qd

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by edburtnieks** [comment]
**Update:**

I needed the `ASTRO_STUDIO_APP_TOKEN` only locally

When tried to deploy on Vercel, the `ASTRO_DB_APP_TOKEN` was picking up fine and actually didn't work without it

**Comment by Fryuni** [comment]
Thanks for the report. Indeed my projects I used during development had the token on both env vars locally, initially this new feature used the existing `ASTRO_STUDIO_APP_TOKEN` variable.

I'll send a PR in a bit fixing it
