### ISSUE TITLE
integration with shadcn/ui drops error

### ISSUE THREAD

**Issue by amirhoseinsh** [withastro/astro#11892]
### Astro Info

```block
Astro                    v4.14.2
Node                     v20.11.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
                         @astrojs/sitemap
                         astro-robots-txt
```

### Describe the Bug

I follow up shadcn integration page with astro, but it gives me an error like below when I run 
`npx shadcn@latest init`

✔ Preflight checks.
✔ Verifying framework. Found Astro.
✖ Validating Tailwind CSS.
✔ Validating import alias.

No Tailwind CSS configuration found at C:\Users\USER\Desktop\code\open-matn\3f-commercial.
It is likely you do not have Tailwind CSS installed or have an invalid configuration.
Install Tailwind CSS then try again.
Visit https://tailwindcss.com/docs/guides/astro to get started.

my `tailwind.config.mjs` file is like below:

```
/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}',
		'./@/**/*.{ts,tsx}',
		],
	theme: {
		extend: {},
	},
	plugins: [],
}
```

also my `tsconfig.json` file is like this:
```
"compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    "jsx": "react-jsx",
    "jsxImportSource": "react"
  },
```
### What's the expected result?

I want to add shadcn to my project

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/with-tailwindcss?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
If the issue occurs using shadcn/ui's cli, then an issue should be opened there

**Comment by florian-lefebvre** [comment]
See https://github.com/shadcn-ui/ui/issues/4701
