### ISSUE TITLE
TS2305: Module "astro:actions" has no exported member actions

### ISSUE THREAD

**Issue by alfi-dim** [withastro/astro#11893]
### Astro Info

```block
Astro                    v4.15.1
Node                     v18.20.4
System                   Windows (x64)
Package Manager          unknown
Output                   hybrid
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/preact
```

### Describe the Bug

Got `TS2305: Module "astro:actions" has no exported member actions` when `import { actions } from 'astro:actions';`

full code:
my actions/index.ts
```ts
import { defineAction, ActionError } from 'astro:actions';
import { z } from "astro:content";

import {app} from '../firebase/server.ts';
import { getFirestore } from 'firebase-admin/firestore';

export const server = {
  getData: defineAction({
    input: z.object({
      docName: z.string().min(1),
    }),
    handler: async (input: { docName: string }) => {
      try {
        const db = getFirestore(app);
        const doc = await db.collection('test').doc(input.docName).get();
        console.log('doc.data()', doc.data());
        return doc.data();
      } catch (error) {
        return new ActionError({
          code: 'INTERNAL_SERVER_ERROR',
          message: `An error occurred while fetching data: ${error.message}`,
        });
      }
    }
  })
};
```
my preact component

```ts
import { actions } from 'astro:actions';
import {useEffect, useState} from "preact/hooks";

export default function TestFirebase() {
  const [data, setData] = useState([]);

  useEffect(() => {
    const f = async () => {
      const d = await actions.getData({docName: 'test'})
      setData(d)
    }
    f()
  }, [])
  return (
    <div>
      <h1>TestFirebase</h1>
      <ul>
        {
          data.map((d) => <li>d</li>)
        }
      </ul>
    </div>
  );
}
```

index.astro

```ts
import { defineAction, ActionError } from 'astro:actions';
import { z } from "astro:content";

import {app} from '../firebase/server.ts';
import { getFirestore } from 'firebase-admin/firestore';

export const server = {
  getData: defineAction({
    input: z.object({
      docName: z.string().min(1),
    }),
    handler: async (input: { docName: string }) => {
      try {
        const db = getFirestore(app);
        const doc = await db.collection('test').doc(input.docName).get();
        console.log('doc.data()', doc.data());
        return doc.data();
      } catch (error) {
        return new ActionError({
          code: 'INTERNAL_SERVER_ERROR',
          message: `An error occurred while fetching data: ${error.message}`,
        });
      }
    }
  })
};
```

### What's the expected result?

it should import actions correctly

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aretrace** [comment]
@alfi-dim did you run the dev server? 
apparently it's [code generated](https://github.com/withastro/astro/issues/11018#issuecomment-2107393109)

**Comment by groteck** [comment]
I found the same issue, migrating from:
- astro 4.11.5
+ astro 4.15.3
The error happens only on build time

**Comment by TnTSpace** [comment]
My error was because the actions folder wasn't directly under my src folder, instead I put it in my libs folder

A - This is what is expected for the actions types to be generated: /src/actions/index.ts
B - This was what I did: /src/lib/actions/index.ts

So I had to move it from B to A and it worked

**Comment by kevinricher** [comment]
Just experienced this on a fresh install of Astro v5.5.2. Adding `.astro/actions.d.ts` to my tsconfig includes removed the error for me.

My tsconfig now looks like:

```
{
  "extends": "astro/tsconfigs/strict",
  "include": [".astro/types.d.ts", ".astro/actions.d.ts", "**/*"],
  "exclude": ["dist"]
}
```

**Comment by devlopersabbir** [comment]
@kevinricher thanks it's works for me

**Comment by MichaelBelgium** [comment]
Having this too with astro 5.12.9. How is this issue still around for a year? Litteraly nobody uses actions? Cuz you can't create actions with that error

I don't have a `.astro/actions.d.ts` file so that wont work for me, there is a reference to it in types.d.ts but after snooping around there's indeed no "actions" thats getting exported, so why is it removed? 

This also makes the actions docs unusable

**Comment by ValentinKolb** [comment]
@kevinricher thanks! fixed it

**Comment by impcyber** [comment]
> Having this too with astro 5.12.9. How is this issue still around for a year? Litteraly nobody uses actions? Cuz you can't create actions with that error
> 
> I don't have a `.astro/actions.d.ts` file so that wont work for me, there is a reference to it in types.d.ts but after snooping around there's indeed no "actions" thats getting exported, so why is it removed?
> 
> This also makes the actions docs unusable

What is the content of the `actions/index.ts` file?

**Comment by serrg** [comment]
I'm also encountering this issue in Astro `5.16.0` and TypeScript `5.7.3`. 

I get the following error:
```
Module '"astro:actions"' has no exported member 'actions'.
```
when trying to import it like this:
```
import { actions } from 'astro:actions';
```

My TypeScript configuration includes:
```
  "include": [".", ".astro/types.d.ts"],
```

The `.astro/types.d.ts` file references `astro/client`, which in turn references `./types/actions.d.ts`, where the module `astro:actions` is declared as follows:
```
declare module 'astro:actions' {
	export * from 'astro/actions/runtime/server.js';

	export function getActionPath(
		action: import('astro/actions/runtime/server.js').ActionClient<any, any, any>,
	): string;
}
```

So it looks like it is missing:
```
export const actions: Actions;
```
