### ISSUE TITLE
Safari only: null is not an object (evaluating 'history.state.index') coming from "astro:transitions/client" navigate on scroll event

### ISSUE THREAD

**Issue by pawelgrzybek** [withastro/astro#11913]
### Astro Info

```block
Astro                    v4.15.2
Node                     v20.15.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/netlify
Integrations             @sentry/astro
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Safari

### Describe the Bug

Scroll event results in `TypeError: null is not an object (evaluating 'history.state.index')` on scroll event when client side `navigate` is in use. Safari only.

Example:
```
---
---

<h1>Home page</h1>
<button>go to test page</button>
<div style="height: 120vh">hi</div>

<script>
  import { navigate } from "astro:transitions/client";

  const button = document.querySelector('button')
  button.addEventListener('click', () => navigate('/test'))
</script>
```
The `div` with 120vh size added intentionally to be able to scroll.

### What's the expected result?

Scroll event shouldn't cause a TypeError.

I am going to add a StackBlizt demo, but StackBlitz does not play very well with Safari.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qyxzsr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pawelgrzybek** [comment]
Hi @martrapp 

In my example I followed [this guide](https://docs.astro.build/en/guides/actions/#handling-client-redirects). It is easy to miss the fact that navigate function relies on `ViewTransitions` being added to a page.

Thank you

**Comment by martrapp** [comment]
Yes, I'm sorry for that, we should definitively make this consistent!
cc: @bholmesdev

**Comment by bholmesdev** [comment]
@martrapp Oh no! I remember testing that `navigate()` could work without view transitions, hence the recommendation. If that isn't allowed, we'll need to update our docs.

**Comment by pawelgrzybek** [comment]
@bholmesdev it does work on Chrome and Firefox without it `<ViewTransitions />`. Only the use on Safari results in this error. Of course when I inject `<ViewTransitions />` to the scope of this page, error disappears on Safari.

PS. I am big fan of some of your YouTube explainers.
