### ISSUE TITLE
axobject-query/lib/index.js?v=c984d6da' does not provide an export named 'AXObjectRoles'

### ISSUE THREAD

**Issue by TheGuyInApt42** [withastro/astro#11912]
### Astro Info

```block
Astro                    v4.15.2
Node                     v20.9.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

the styles for my project are not loading and i get error message "The requested module '/@fs/C:/Users/tuc-dev/node_modules/axobject-query/lib/index.js?v=c984d6da' does not provide an export named 'AXObjectRoles'". They were working for a long time and I am not sure what the change was. I did a fresh install of astro and still got same error. I didnt make any changes to the fresh install at all. I did notice during the cli install process that it timed out during the dependencies installing and i had to manually run npm install. 
![Opera Snapshot_2024-09-03_100658_localhost](https://github.com/user-attachments/assets/b8fe9242-29d2-40f8-b5bd-22706c39cb4e)

### What's the expected result?

Styles to load

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by abednarz-selectron** [comment]
I am having the same exact issue but with Astro v4.15.3

**Comment by abednarz-selectron** [comment]
Reverting back to a version before 4.1.0 removes the error message but the CSS is still not rendering for me. I also tried Node versions 18.7.1 and 22.7.0 with the same results

**Comment by TheGuyInApt42** [comment]
I switch between vscode terminal and windows terminal

**Comment by insidert** [comment]
For users on windows. Use intergrated terminal in VS Code to run the app and render the styles. 
Do not use 'Terminal' app to run the app.

**Comment by WefNET** [comment]
Same strangeness here with:

> "astro": "^4.15.4",

I was using an elevated CMD to run the app with NVM to check a few node version variabilities. Running this way produced Astro site with no styles and the error message in the browser console. (Same with non-elevated).

The site works fine in the VS "node" terminal.

**Comment by TheGuyInApt42** [comment]
I was also using NVM with both windows terminal and vscode. As been mentioned, it does seem that just using vscode terminal works so i will just use that for now

**Comment by JaydenWN** [comment]
> The error message itself is unrelated to not having CSS. There was a similar CSS issue a long time ago, and it was related to the terminal that was being used, and only on Windows.
> 
> Which terminal and shells are you using?

I'm still having this issue, running in a powershell terminal within vscode on windows 10. I run it within a WSL and its fine, however doesn't have HMR. 

I've experienced this issue once before and disabled VSCode extensions and it worked.

I've also tried running it in a bash terminal within vscode, same result.

**Comment by ethancoote** [comment]
Had the same issue. For some reason if I open the terminal in a parent directory and cd into the project directory I get the error.

If I open the terminal in the project directory directly then it works fine.

No idea why this happens but hopefully that helps.

**Comment by JhustDuke** [comment]
this is what i did  it works but the error still persist in the console client side
import { defineConfig } from "astro/config";

export default defineConfig({
	// ... other astro config
	vite: {
		ssr: {
			noExternal: ["axobject-query"],
		},
	},
});
