### ISSUE TITLE
When the API returns the HTTP response for fetch, the API crashes

### ISSUE THREAD

**Issue by ccbikai** [withastro/astro#11921]
### Astro Info

```block
Astro                    v4.15.2
Node                     v18.18.2
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

https://github.com/ccbikai/astro-debug

How to reproduce:

`npm run dev`

Visit `http://localhost:4321/api/https://http.im/status/200`, no error reported

Access `http://localhost:4321/api/https://http.im/status/500`, and encounter an error `TypeError: immutable`.

### What's the expected result?

only return 500 http response

### Link to Minimal Reproducible Example

https://github.com/ccbikai/astro-debug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ccbikai** [comment]
@liruifengv Communication

**Comment by ascorbic** [comment]
The issue here is that the `Response` returned from a `fetch()` is immutable, but Astro expects to be able to add headers to it. You can fix it by returning a new Response with the response:

```ts
export async function GET({ request, params }) {
  const response = await fetch(params.url, request)
  return new Response(response.body, response)
}
```

It might be nice if Astro handled this itself, but I'm not sure how widespread this is likely to be.

**Comment by ccbikai** [comment]
@ascorbic Thank you for your help, your code works fine now

**Comment by ascorbic** [comment]
The original code should now work once astro 4.15.11 is released
