### ISSUE TITLE
Support dynamic routes (without getStaticPaths) in static output mode

### ISSUE THREAD

**Issue by erikdemarco** [withastro/astro#11928]
### Astro Info

```block
❯ astro info
Astro                    v4.15.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   hybrid
Adapter                  none
Integrations             none
```

### Describe the Bug

Right now, when we use the { output: 'static' } option to statically pre-generate the app to run in static site hosting, we hit a roadblock: dynamic routes like /post/[id].astro just can't be created because it always compalined "getStaticPaths()` function is required for dynamic routes". Yes, we can pre-generate specific pages such as /posts/1, /posts/2, /posts/3, and so on, but its very time consuming if we have very huge list of contents. And with current way of Astro workflow it will limit client side rendering ability bring us back to 1991 internet era. Even nextjs page router and gatsby can do this exact thing without any problem.

### What's the expected result?

We're looking to get dynamic routes with variable parameters up and running in static export mode. The vision is to have routes like /post/[id] operate without a hitch, avoiding the dreaded 404 error when the ID parameter changes, and allowing individual posts to be fetched client-side. This change would significantly broaden the scope and usefulness of static exports.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u8tndk?file=src%2Fpages%2Fauthors%2F%5Bauthor%5D.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
SSG mode generates .html files. We can't generate .html files if you don't tell us which ones to generate. If you want to support loading any `[id]` then you don't want static output, you want server output.

**Comment by erikdemarco** [comment]
@matthewp  if you use server output, you will need ssr. this thing can be deployed frontend without any ssr adapter. in our static hosting we just need to rewrite all request to authors/* to authors/[id].html, so all request will be handled by this single html
