### ISSUE TITLE
Load component module <script> only when needed in the page.

### ISSUE THREAD

**Issue by pijusz** [withastro/astro#11937]
### Astro Info

```block
Astro                    v4.15.3
Node                     v20.15.1
System                   Windows (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

Been using astro-portabletext with multiple custom components which are javascript heavy (charts).

I'm using <CustomPortableText /> on every page, but every page does not have charts item. But Astro still bundles chart javascript into every page that has <CustomPortableText />

### What's the expected result?

Chart javascript module should only be loaded when needed in the page.

Added Stackblitz for the lazy/dynamic load attempt. If value index.astro does not have _type: "alert" it should not load alert script module.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-p8kupg?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2FType.astro,src%2Fcomponents%2FAlert.astro,src%2Fcomponents%2FHello.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
https://docs.astro.build/en/reference/configuration-reference/#experimentaldirectrenderscript fixes this in your reproduction, and will be enabled by default in Astro 5
