### ISSUE TITLE
Inaccurate route collision error

### ISSUE THREAD

**Issue by delucis** [withastro/astro#11957]
### Astro Info

```block
Astro                    v4.15.4
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             test
```

### If this issue only occurs in one browser, which browser is a problem?

n/a

### Describe the Bug

In an Astro project with:
- More than one injected routes
- At least one injected route with a spread pattern (e.g. `[...slug]`)
- No `index.astro` or `index.ts` in `src/pages/`

Requests for `/` trigger a [`PrerenderDynamicEndpointPathCollide`](https://docs.astro.build/en/reference/errors/prerender-dynamic-endpoint-path-collide/) error even when there are no collisions.

### What's the expected result?

When there are no collisions, a collision error should not be raised.

---

Details about the reproduction:

- The inline integration in `astro.config.mjs` injects two routes
- One is available at `/page` the other at `/test` — these both load successfully
- Requesting `/` triggers the error (should be a 404)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dm88gb?file=entrypoint-page.ts,entrypoint-test.ts,astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
is the problem that it always expects an index route to exist and is sending that as a param?

**Comment by delucis** [comment]
> is the problem that it always expects an index route to exist and is sending that as a param?

The problem is that Astro throws a “conflict” error even when there is no conflict, i.e.

- `[...slug]` should handle `/`
- `page` should handle `/page`

But Astro errors saying these two routes conflict.

**Comment by delucis** [comment]
Sharing an updated repro for this error being thrown by the Node adapter even with the fixed version: https://stackblitz.com/edit/github-dm88gb-pd8nv5?file=astro.config.mjs,entrypoint-test.ts,entrypoint-page.astro

Chatting on Discord with @bluwy about this and will decide whether we reopen or if I should make a new issue.
