### ISSUE TITLE
Slot with default value doesn't work for `<head>`

### ISSUE THREAD

**Issue by openscript** [withastro/astro#11959]
### Astro Info

```block
Astro                    v4.15.4
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

All browsers

## Bug description

1. I have created a layout `DefaultLayout.astro` with the following markup:
  ```tsx
  ---
  import Head from "./Head.astro";
  ---
  
  <html lang="en">
    <slot name="head">
      <Head />
    </slot>
    <body>
      <slot name="header">
        <header>Default header</header>
      </slot>
      <slot />
    </body>
  </html>
  ```
2. I use this layout in a page `index.astro` with the following markup:
  ```tsx
  ---
  import DefaultLayout from '../layouts/DefaultLayout.astro'
  import Head from '../layouts/Head.astro'
  ---
  
  <DefaultLayout>
    <Head slot="head" title="Custom title" />
    <main>Body</main>
  </DefaultLayout>
```
3. Now the `<main>Body</main>` won't be rendered anymore.
4. I've verified, that it works in other situations. See the pages `more.astro` and `another.astro`.

### What's the expected result?

The expected result is, that I can have a slot with a default value for the `<head>` like it is described here: https://docs.astro.build/en/basics/astro-components/#fallback-content-for-slots

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-v3mu9b?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by openscript** [comment]
It seems like the error only happens if there is no `<head>` element in the layout.

**Comment by openscript** [comment]
This doesn't seem to work. When my `<Head />` doesn't include the normal html `<head>` but just emits what is inside the `<head>` it starts to work. I think this is a bug or limitation of Astro.

I do something like this in my layout now:

```html
  <head>
    <Head translations={translations}>
      <slot name="meta" slot="meta">
        <Meta />
      </slot>
    </Head>
  </head>
```

Inside the `<Head />` I have a slot:

```html
<slot name="meta" />
```

A page where I use the construct looks like:

```html
<DefaultLayout translations={page.translations}>
  <Meta slot="meta" title={page.data.title} />
  <Content />
</DefaultLayout>
```

My `<Meta />` component looks like:

```tsx
---
import { getLocaleFromUrl, useTranslations } from '../../utils/i18n';
import { author as packageAuthor } from "../../../package.json";

type Props = {
  title?: string;
  author?: string;
  description?: string;
  keywords?: string;
}

const locale = getLocaleFromUrl(Astro.url);
const props = Astro.props;
const t = useTranslations(locale);

const title = props.title ? `${props.title} - example.com` : t("title");
const author = props.author || packageAuthor;
const description = props.description || t("description");
const keywords = props.keywords;
---

<title>{title}</title>
<meta name="author" content={author} />
<meta name="description" content={description} />
{ keywords && <meta name="keywords" content={keywords} /> }
```

**Comment by openscript** [comment]
Is this somewhere mentioned in the docs?

**Comment by xamgore** [comment]
Bumped onto this today. Haven't seen it in the docs.

**Comment by openscript** [comment]
@xamgore There is an easy workaround. Just not make the whole `Head` component into a slot, but it's children:

1. In your layout you do something like:
    ```tsx
    <html lang={locale}>
      <Head>
        <slot name="meta" slot="meta">
          <Meta />
        </slot>
      </Head>
      <body>
        
      </body>
    </html>
     ```
1. Define your `<Head>` component:
    ```tsx
    <head>
      <meta charset="utf-8" />
      <slot name="meta" />
    </head>
    ```
1. In the pages you can define now the `meta` slot:
    ```tsx
    <DefaultLayout>
      <Meta slot="meta" title={title} />
    </DefaultLayout>
    ```
