### ISSUE TITLE
Server Islands fails when an object with circular dependencies passed as a prop.

### ISSUE THREAD

**Issue by Mouaz** [withastro/astro#11969]
### Astro Info

```block
Astro                    v4.15.4
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          bun
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         astro-icon
```

### Describe the Bug

Passing an object with circular references to a server Island causes since `safeJsonStringify` doesn't take circular references in consideration.
![image](https://github.com/user-attachments/assets/65b214bd-4f39-432f-b173-9d94b6a831c0)

### What's the expected result?

Circular objects to be delivered as they are to the client.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ldsng3?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
Maybe we should use devalue to serialise the data. That would allow Map and Set too.

**Comment by matthewp** [comment]
We went through all of these types of things with client islands and it causes more problems than it fixes I think. Also if we used something like `devalue` we need to both serialize and deserialize it. I personally think it's better just to document the limitation.

**Comment by bluwy** [comment]
There was an attempt to fix this in the past: https://github.com/withastro/astro/pull/8004

**Comment by ematipico** [comment]
I am up for documenting the limitation.

**Comment by ascorbic** [comment]
Closing this in favour of a docs issue: https://github.com/withastro/docs/issues/9557
