### ISSUE TITLE
getStaticPaths regression after v4.15.5

### ISSUE THREAD

**Issue by jwv** [withastro/astro#11990]
### Astro Info

```block
Astro                    v4.15.5
Node                     v22.2.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         astro-icon
                         @astrojs/sitemap
```

### Describe the Bug

After update to v4.15.5 getStaticPaths  stop work as usually.

For example:
pages/archive/[...slug]/[...page].astro

```JS
export async function getStaticPaths({ paginate }) {

  const paths = [
    {
      slug: 'news/july-2024',
      items: ['item 1', 'item 2', 'item 3', 'item 4', 'item 5', 'item 6'],
      contentType: 'news',
      monthYear: 'july-2024',
    }
  ];

  return paths.flatMap((path) => {
    return paginate(path.items, {
      params: { slug: path.slug },
      props: {
        contentType: path.contentType,
        monthYear: path.monthYear,
      },
      pageSize: 2,
    });
  });
}
```

With v4.15.5 returns a error:

> A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/archive/news/july-2024`.
> Possible dynamic routes being matched: src/pages/archive/[...slug]/[...page].astro.

With v4.15.4 runs without errors and route without any problem.

Don't know maybe something with #11983

### What's the expected result?

Routing without any errors.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vxjmv8?file=src%2Fpages%2Farchive%2F[...slug]%2F[...page].astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, i'll take a look and hopefully get a new patch out.
