### ISSUE TITLE
Visible <script> and <style> tags when using tailwinds *:grid and astro client directives

### ISSUE THREAD

**Issue by RealKendpr** [withastro/astro#12005]
### Astro Info

```block
> extinct-event@0.0.1 astro
> astro info

Astro                    v4.15.6
Node                     v20.9.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

when using tailwinds `*:grid` class in the parent element, and client directive `client:load` in one its children a `<script>` and `<style>` tag is visible in the DOM, but when using `grid` class in each of the child elements it does not happen.

### What's the expected result?

There should be no `<script>` and `<style>` tag is visible in the DOM.

### Link to Minimal Reproducible Example

https://github.com/RealKendpr/extinct-event

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is not an Astro issue, `*:grid` applies `display: grid;` to every children, including script and style tags, making them visible.

**Comment by RealKendpr** [comment]
> This is not an Astro issue, `*:grid` applies `display: grid;` to every children, including script and style tags, making them visible.

I see. So, there is a script and style tag since the react component has a client directive, and I didnt know you could apply styles in script and style tags. Thanks
