### ISSUE TITLE
astro build  doesn't  output right dist files when config i18n fallback

### ISSUE THREAD

**Issue by yuchenii** [withastro/astro#12013]
### Astro Info

```block
Astro                    v4.15.6
Node                     v18.20.3
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

1. Follow this page to [add i18n features](https://docs.astro.build/en/recipes/i18n/#use-collections-for-translated-content), and config i18n.fallback `en: "zh"`,  more detailed information is on [StackBlitz.](https://stackblitz.com/edit/github-1vx29t-fsktjn?file=astro.config.mjs)
2. After running pnpm build, the dist directory is as follows. There are also en and zh directories under the en directory, this is a bug or my problem

```text
dist
  ├─en
  │    ├─blog
  │    │    └─first-post
  │    │         └─index.html
  │    ├─en
  │    │    └─blog
  │    │         └─first-post
  │    │              └─index.html
  │    ├─index.html
  │    └─zh
  │         └─blog
  │              └─first-post
  │                   └─index.html
  ├─index.html
  └─zh
       └─blog
            └─first-post
                 └─index.html
```

3. if comment out the fallback configuration or add `prefixDefaultLocale: true` to i18n.routing，there will be no problem

### What's the expected result?

The dist directory should look like this

```text
dist
  ├─en
  │    └─blog
  │         └─first-post
  │              └─index.html
  ├─index.html
  └─zh
       └─blog
            └─first-post
                 └─index.html
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1vx29t-fsktjn?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I did triage the issue, and I believe you're using the feature incorrectly, or you provided an incorrect reproduction.

Your reproduction has two issues:
- it uses collections to dynamically generate content, which means **there's always content**
- you reproduction has content for both pages (first-post), so the fallback doesn't make sense
