### ISSUE TITLE
`selected` should be a boolean attribute

### ISSUE THREAD

**Issue by fviolette** [withastro/astro#12023]
### Astro Info

```block
Astro                    v5.0.0-beta.1
Node                     v22.8.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             auto-import
                         @astrojs/sitemap
                         @astrojs/preact
                         @astrojs/asides
                         astro-expressive-code
                         @astrojs/pagefind
                         @astrojs/mdx
```

### Describe the Bug

When dynamically adding the selected attribute on `<option>`, Astro preserves the full attribute with its value: `selected="true"` or `selected="false"`.

On v4.X, `selected="true"` was output when true and nothing was, when false.

I notice that selected is not part of the list of boolean attributes at: https://github.com/withastro/astro/blob/astro%405.0.0-beta.1/packages/astro/src/runtime/server/render/util.ts#L9

### What's the expected result?

As per https://5-0-0-beta.docs.astro.build/en/guides/upgrade-to/v5/#changed-non-boolean-html-attribute-values, I expect the output of `selected={true}` should be `selected`, `selected={false}` should not output anything. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ltqkre?file=src%2Fpages%2Findex.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Good catch! Looks like an easy fix. I think editing the regex without tests should be fine if you'd like to contribute.

**Comment by fviolette** [comment]
Here's my attempt at https://github.com/withastro/astro/pull/12027.
