### ISSUE TITLE
[Beta] Astro MDX renderer is not bundled

### ISSUE THREAD

**Issue by universse** [withastro/astro#12029]
### Astro Info

```block
Astro                    v5.0.0-beta.1
Node                     v22.6.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/react
                         @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Deployment to CF Pages failed due to non-existent '@astrojs/mdx/server.js'.

Here's the output of `dist\_worker.js\chunks\_@astro-renderers_[hash].mjs`.

```js
globalThis.process ??= {}; globalThis.process.env ??= {};
import { p as getDefaultExportFromCjs } from './astro/server_CH__8xxn.mjs';
import _renderer1 from '@astrojs/mdx/server.js'; // <--- here

const opts = {
  experimentalReactChildren: false
};

var react = {exports: {}};
...
```

### What's the expected result?

MDX renderer should be bundled.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jkjbbg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I can't reproduce the issue with the link given. I'm seeing that it's properly bundled. Perhaps you could double check that all Astro dependencies are upgraded?

**Comment by universse** [comment]
I figured out the issue. I'm using Astro Container API. To make it work on Cloudflare, I needed to mark container modules as external.
Here's the updated reproduction https://stackblitz.com/edit/github-jkjbbg-nhzsfm

```
  vite: {
    ssr: {
      // previously v4
      // external: ["astro/container", "@astrojs/mdx"],
      external: [
        'astro/container',
        'node:fs',
        'node:fs/promises',
        'fs',
        'node:url',
        'node:path',
        'path',
      ],
    },
  },
```

**Comment by ematipico** [comment]
In order to fix the issue, you need to load the render manually, otherwise it isn't bundled. The way you're loading the renderer is meant for cases like `vitest`. This is [mentioned in the docs](https://docs.astro.build/en/reference/container-reference/#adding-a-renderer-through-the-container-api):

> When using vite (vitest, Astro integrations, etc.), the renderers are loaded with the function loadRenderers() from the virtual module astro:container. Outside vite, you’ll have to load the renderers manually.

Here's how load the MDX renderers:

```js
import mdxRenderer from "@astrojs/mdx/server.js";

const astroContainer = await AstroContainer.create();
astroContainer.addServerRenderer({renderer: mdxRenderer});
```

**Comment by universse** [comment]
Not sure I understand correctly. The reason I'm loading it as such is because of Node.js built-in imports causing Vite to throw error during build. Loading the renderers manually does not help.

**Comment by ematipico** [comment]
> Not sure I understand correctly. The reason I'm loading it as such is because of Node.js built-in imports causing Vite to throw error when building for Cloudflare workers (via `@astrojs/cloudflare` integration). Loading the renderers manually does not help.

I did test it using your reproduction, and it built successfully.

**Comment by universse** [comment]
Yes, it built successfully because I added all Node.js built-ins to `vite.external.ssr` to Astro config. If you comment those out, the build will fail because Astro Container feature depends on Node built-ins..
