### ISSUE TITLE
Simple example doesn't work with cloudflare Pages

### ISSUE THREAD

**Issue by jolic** [withastro/astro#12020]
### Astro Info

```block
used  create astro@latest
```

### Describe the Bug

I tried the simple example from the docs (https://docs.astro.build/de/install-and-setup/) with ```npm create astro@latest```.
```npm run dev``` and ```npm run build``` worked fine.

But cloudflare shows an error:

`
15:21:04.206 | No wrangler.toml file found. Continuing.
-- | --
15:21:04.366 | Detected the following tools from environment: nodejs@20.11.0, npm@9.6.7
15:21:04.367 | Installing nodejs 20.11.0
15:21:05.202 | Trying to update node-build... ok
15:21:05.306 | To follow progress, use 'tail -f /tmp/node-build.20240918132105.489.log' or pass --verbose
15:21:05.411 | Downloading node-v20.11.0-linux-x64.tar.gz...
15:21:05.535 | -> https://nodejs.org/dist/v20.11.0/node-v20.11.0-linux-x64.tar.gz
15:21:07.205 | Installing node-v20.11.0-linux-x64...
15:21:07.617 | Installed node-v20.11.0-linux-x64 to /opt/buildhome/.asdf/installs/nodejs/20.11.0
15:21:07.617 |  
15:21:08.743 | Installing project dependencies: npm clean-install --progress=false
15:21:09.761 | npm ERR! code EUSAGE
15:21:09.763 | npm ERR!
15:21:09.763 | npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
15:21:09.763 | npm ERR!
15:21:09.763 | npm ERR! Invalid: lock file's prettier@2.8.7 does not satisfy prettier@3.3.3
15:21:09.763 | npm ERR! Missing: prettier@2.8.7 from lock file
15:21:09.764 | npm ERR!
15:21:09.764 | npm ERR! Clean install a project
15:21:09.764 | npm ERR!
15:21:09.764 | npm ERR! Usage:
15:21:09.764 | npm ERR! npm ci
15:21:09.764 | npm ERR!
15:21:09.764 | npm ERR! Options:
15:21:09.764 | npm ERR! [--install-strategy <hoisted\|nested\|shallow\|linked>] [--legacy-bundling]
15:21:09.764 | npm ERR! [--global-style] [--omit <dev\|optional\|peer> [--omit <dev\|optional\|peer> ...]]
15:21:09.765 | npm ERR! [--include <prod\|dev\|optional\|peer> [--include <prod\|dev\|optional\|peer> ...]]
15:21:09.765 | npm ERR! [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
15:21:09.765 | npm ERR! [--no-bin-links] [--no-fund] [--dry-run]
15:21:09.765 | npm ERR! [-w\|--workspace <workspace-name> [-w\|--workspace <workspace-name> ...]]
15:21:09.765 | npm ERR! [-ws\|--workspaces] [--include-workspace-root] [--install-links]
15:21:09.765 | npm ERR!
15:21:09.765 | npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
15:21:09.765 | npm ERR!
15:21:09.765 | npm ERR! Run "npm help ci" for more info
15:21:09.766 |  
15:21:09.766 | npm ERR! A complete log of this run can be found in: /opt/buildhome/.npm/_logs/2024-09-18T13_21_09_243Z-debug-0.log
15:21:09.776 | Error: Exit with error code: 1
`

Any hints on this?

### What's the expected result?

It works.

### Link to Minimal Reproducible Example

No url

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please create an example with https://astro.new/latest/, thank you.

**Comment by jolic** [comment]
Just resolved the issue and maybe this could help someone else: 

Remove ```package-lock.json``` from the repo and restart the build on Cloudflare. Best way is to add ```package-lock.json``` in the file ```.gitignore```.

Maybe it's an issue because I'm using a Mac and the VM on Cloudflare uses Linux...

**Comment by Princesseuh** [comment]
Closing since this is most likely not an actionable Astro issue.

**Comment by dralshehri** [comment]
I had the same issue and tried to specify the node version using `.nvmrc` to `20.x` since Cloudflare uses node v18 and also added `"prettier": "^3.3.3"` to `devDependencies` in `package.json, which solved the problem.
