### ISSUE TITLE
Image component doesn't recognize local images in the new Content Layer API

### ISSUE THREAD

**Issue by frenicohansen** [withastro/astro#12025]
### Astro Info

```block
Astro                    v5.0.0-beta.1
Node                     v20.9.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

After migrating to the new Content Layer API, the Image component is no longer able to recognize local images when the source is provided by a content collection. This is causing issues as the component now requires manual setting of image dimensions, which should not be necessary by default.

https://docs.astro.build/en/guides/images/#images-in-content-collections

### What's the expected result?

Image component shouldn't ask for dimensions of local images

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/z22xn5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by i-bsd** [comment]
Thanks for posting this issue. I wasted hours on this yesterday thinking I did something wrong.

**Comment by jurajkapsz** [comment]
I can confirm this.

The schema `image()` `ImageFunction` no longer returns an image object with `src`, `width` etc. propertiess but only a resolved string representing `src/` relative path to the image file.

```js
const myCollection = defineCollection({
  loader: glob({
    pattern: "**/*.mdx",
    base: "./src/data/collection",
  }),
  schema: ({ image }) =>
    z.object({
      title: z.string(),
      image: image(), // <-- this
    }),
});
```

**Comment by Princesseuh** [comment]
This seems to be caused by the path being absolute, modifying the reproduction to use a relative path makes it work

**Comment by i-bsd** [comment]
For me, it's dynamically importing images that doesn't work at all now after upgrading (using [this recipe](https://docs.astro.build/en/recipes/dynamically-importing-images/)). Never had an issue before.

**Comment by Princesseuh** [comment]
> For me, it's dynamically importing images that doesn't work at all now after upgrading (using [this recipe](https://docs.astro.build/en/recipes/dynamically-importing-images/)). Never had an issue before.

That seems unrelated, this issue is specifically about the `image()` schema.

**Comment by jurajkapsz** [comment]
> This seems to be caused by the path being absolute, modifying the reproduction to use a relative path makes it work

Yes, I use absolute paths for linked images eg `/src/assets/images/perex/image.jpg`.
I actually can't imagine to use relative paths. I'd like to say that switching to absolute paths resolved my project's maintainability.
