### ISSUE TITLE
Localized Sitemap Generation with @astrojs/sitemap Fails to Render Correct XML Structure on Vercel Deployment

### ISSUE THREAD

**Issue by isooosi** [withastro/astro#12049]
### Astro Info

```block
Astro                    v4.15.7
Node                     v22.8.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
                         @astrojs/mdx
                         pagefind
                         @astrojs/tailwind
                         astro-icon
                         @astrojs/partytown
```

### Describe the Bug

In my Astro multi-language project, I am using the official @astrojs/sitemap plugin to generate localized sitemap files. While the sitemap files (sitemap-0.xml, etc.) are correctly generated with proper XML structures in the local development environment, the deployed version on Vercel fails to display the correct XML structure. Instead, the sitemap files only show a list of URLs without the necessary XML tags, preventing search engines from properly parsing and indexing the website.

Sitemap URLs:

	•	https://verse-i18n.vercel.app/sitemap-index.xml
	•	https://verse-i18n.vercel.app/sitemap-0.xml

### What's the expected result?

In the production environment on Vercel, sitemap files (sitemap-index.xml, sitemap-0.xml, etc.) should be generated with the correct XML structure, including <urlset>, <url>, and other necessary XML tags. This structure is essential for search engines like Google to parse and index the website effectively.

### Link to Minimal Reproducible Example

https://github.com/isooosi/Astroverse-i18n

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Even if doesn't show properly the XML in the browser, it's absolutely fine. If you open the devtools, the structure is good

**Comment by moshicode** [comment]
Its not showing properly, there is issue with the structure or the headers

**Comment by florian-lefebvre** [comment]
What do you mean?

**Comment by erotondano** [comment]
Does this has any answer? The same issue is happening to me. Locally it builds pretty right, but once is online on cloudflare it just shows a list of urls without any xml format.

**Comment by florian-lefebvre** [comment]
Browsers may not display it pretty if it's long IIRC. It's not actually a problem, if you can see the proper structure in the devtools. If you there's a bug still, please open a new issue!
