### ISSUE TITLE
@astrojs/svelte server render default import doesn't work

### ISSUE THREAD

**Issue by JonathonRP** [withastro/astro#12056]
### Astro Info

```block
Astro                    v4.15.8
Node                     v20.11.1
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
```

### Describe the Bug

astro container fails to add server renderer - 'TypeError: Cannot read properties of undefined (reading 'check')'

### What's the expected result?

to be able to use server render

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rmjshr?file=src%2Fpages%2Fdownload%2F%5B...file%5D.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
It looks like your usage is wrong, which is understandable, because [the docs](https://docs.astro.build/en/reference/container-reference/#adding-a-renderer-manually) are also (differently) wrong! The renderer needs to be an object with `renderer` and `name` options. 
Change it to this and it works:

```ts
      container.addServerRenderer({ renderer: svelteRenderer, name: '@astrojs/svelte' });
      container.addClientRenderer({
        name: '@astrojs/svelte',
        entrypoint: '@astrojs/svelte/client.js',
      });
```
