### ISSUE TITLE
Astro 5 beta and Svelte npm install issue

### ISSUE THREAD

**Issue by bigandy** [withastro/astro#12059]
### Astro Info

```block
Astro                    v5.0.0-beta.1
Node                     v22.3.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I tried installing the svelte package using `npx astro add svelte` which resulted in a silent npm install error and a change to the `astro.config.mjs` file: 
```js
import svelte from '@astrojs/svelte';

// https://astro.build/config
export default defineConfig({
  integrations: [svelte()]
});
```
which causes a failure when running `npm run dev` due to absence of the @astrojs/svelte package (there is no package.json or package-lock.json changes).

I then tried a manual install of the required packages (running `npm install @astrojs/svelte@^5.7.1 svelte@^4.2.19 typescript@^5.6.2`) and this fails due to a  peerdependencies issue in @astrojs/svelte:

npm install @astrojs/svelte@^5.7.1 svelte@^4.2.19 typescript@^5.6.2
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: astro-5-beta@0.0.1
npm error Found: astro@5.0.0-beta.1
npm error node_modules/astro
npm error   astro@"^5.0.0-beta.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer astro@"^4.0.0" from @astrojs/svelte@5.7.1
npm error node_modules/@astrojs/svelte
npm error   @astrojs/svelte@"^5.7.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /<redacted>/.npm/_logs/2024-09-23T12_19_36_278Z-eresolve-report.txt
npm error A complete log of this run can be found in: /<redacted>/.npm/_logs/2024-09-23T12_19_36_278Z-debug-0.log

### What's the expected result?

To be able to add svelte when using the Astro 5 beta.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qkggru?file=package.json&view=editor

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
A beta of the svelte integration will soon be released, that will solve it. You can watch #12017

**Comment by bigandy** [comment]
I repeated the steps with 5.0.0-beta.2 and still it tries to install the wrong version of @astrojs/svelte when running `npx astro add svelte`. The text gives "npm install @astrojs/svelte@^5.7.1 svelte@^4.2.19 typescript@^5.6.2" instructions and also fails silently during the install process. 

If I manually change the install to @astrojs/svelte@^6.0.0 everything works successfully.

Will the `npx astro add svelte` script be updated, or is this still a bug?

**Comment by florian-lefebvre** [comment]
`astro add` always uses the stable latest version by default so it's expected
