### ISSUE TITLE
Astro v5 upgrade beta fails

### ISSUE THREAD

**Issue by apatel369** [withastro/astro#12064]
### Astro Info

```block
Astro                    v4.15.9
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

In the latest Astro 4.15.9 when I run `npx @astrojs/upgrade beta` command it fails with error "Version beta could not be found!"

```
❯ npx @astrojs/upgrade beta
Need to install the following packages:
@astrojs/upgrade@0.3.3
Ok to proceed? (y) 

 astro  Integration upgrade aborted.

      ▲  error
         Version beta could not be found!
      ◼  check
         https://github.com/withastro/astro/releases
```

### What's the expected result?

Astro should be upgraded to v5 Beta after running the upgrade beta command.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal?file=package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by apatel369** [comment]
I tried locally and this time it did not fail.
However, after it finished, I ran astro info and I still had my astro version v4.15.9 instead of v5 Beta.

```
➜  astro-beta git:(master) ✗ astro info  
Astro                    v4.15.9
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none

✔ Copy to clipboard? … yes
➜  astro-beta git:(master) ✗ npx @astrojs/upgrade beta
Need to install the following packages:
@astrojs/upgrade@0.3.3
Ok to proceed? (y) 

 astro   Integration upgrade in progress.

      ◼  astro is up to date on v5.0.0-beta.1
      ●  @astrojs/check will be updated to v0.9.3

 ██████  Installing dependencies with npm...

╭─────╮  Houston:
│ ◠ ◡ ◠  Good luck out there.
╰─────╯
➜  astro-beta git:(master) ✗ astro info               
Astro                    v4.15.9
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

**Comment by t0scale** [comment]
not sure if this is the right way to do this but I am also getting the same/similar error. I initiated a new project using:

`npm create astro@latest -- --ref next`

but this only ran create-astro@4.9.0

I then tried running the upgrade on this untouched new project using:

`npx @astrojs/upgrade beta
`

But I got this error:

`npm ERR! code E404

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@astro%2fupgrade - Not found

npm ERR! 404
npm ERR! 404  '@astro/upgrade@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
`

**Comment by Princesseuh** [comment]
That error make it seems like you ran `@astro/upgrade` and not `@astrojs/upgrade`.

**Comment by apatel369** [comment]
> That error make it seems like you ran `@astro/upgrade` and not `@astrojs/upgrade`.


@Princesseuh I ran npx @astrojs/upgrade beta

**Comment by Princesseuh** [comment]
I was answering to @t0scale

**Comment by TheOtterlord** [comment]
@apatel369 You've install `astro` globally and are calling `astro info` on the global version. You can uninstall the `astro` package globally with `npm uninstall astro -g`. You can run `astro info` on your project with `npm run astro info`.

Wasn't able to figure out why it's unable to verify that beta exists in stackblitz.

**Comment by apatel369** [comment]
@TheOtterlord Yes you are correct. Unintalling global `astro` worked. Closing this issue.
