### ISSUE TITLE
bug: onclick not working in svelte5

### ISSUE THREAD

**Issue by laciferin2024** [withastro/astro#12066]
### Astro Info

```block
Astro                    v4.15.9
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

<img width="459" alt="image" src="https://github.com/user-attachments/assets/bb8e6eff-42a3-412e-99a2-1d96c06c613e">

On loading : localhost:4173/svelte

Its expected to update count on every click. 

<img width="459" alt="image" src="https://github.com/user-attachments/assets/fef9f0e5-b0c5-46cc-b89b-8e06ad75056f">

Not only the count is not updated, but also the count is not logged.

### What's the expected result?

<img width="459" alt="image" src="https://github.com/user-attachments/assets/fef9f0e5-b0c5-46cc-b89b-8e06ad75056f">

Count updated in UI, and count logged in console

### Link to Minimal Reproducible Example

https://github.com/laciferin2024/astro101/blob/main/src/pages/svelte/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by laciferin2024** [comment]
The issue is now fixed: https://github.com/laciferin2024/astro101/commit/623efbc82277d4800e76716509e3622a2dc7f139

Apparently SSR support is yet to come for svelte components.

**Comment by bluwy** [comment]
You need `client:*` to make it interactive for any framework.

**Comment by laciferin2024** [comment]
Thank u

**Comment by laciferin2024** [comment]
@bluwy any reason why I should opt for `client:only ` over `client:load` ?

**Comment by bluwy** [comment]
Both should work, otherwise it may be a bug
