### ISSUE TITLE
[5.0.0-beta.2] Astro.request.headers warning when building app

### ISSUE THREAD

**Issue by GiyoMoon** [withastro/astro#12069]
### Astro Info

```block
Astro                    v5.0.0-beta.2
Node                     v22.8.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When building the page with `pnpm build`, every page prints this warning about astro headers:
```
 generating static routes 
10:22:48 ▶ src/pages/index.astro
10:22:48   └─ /index.html10:22:48 [WARN] `Astro.request.headers` is not available on prerendered pages. If you need access to request headers, make sure that the page is server rendered using `export const prerender = false;` or by setting `output` to `"server"` in your Astro config to make all your pages server rendered.
 (+3ms)
10:22:48 ✓ Completed in 6ms.
```

The warning doesn't appear when using `5.0.0-beta.1`.

### What's the expected result?

It shouldn't print this warning as I'm not accessing the headers in my code.

### Link to Minimal Reproducible Example

https://github.com/GiyoMoon/astro-header-warning-v5-beta-2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by stefanprobst** [comment]
seeing the same warning with v4.15.9 (but not with 4.15.8)

**Comment by ematipico** [comment]
@GiyoMoon please provide a valid reproduction, the repository you provided still relies on v4

**Comment by GiyoMoon** [comment]
@ematipico wait huh? The repo has `5.0.0-beta.2` as it's dependency 🤔 
<img width="912" alt="image" src="https://github.com/user-attachments/assets/91bbbf3c-6878-47f3-8dc4-291dc9fa4b93">

**Comment by ematipico** [comment]
Weird. Anyway, I could reproduce and I sent a PR to fix the issue :)

**Comment by ematipico** [comment]
Closed by https://github.com/withastro/astro/pull/12070

**Comment by stefanprobst** [comment]
> seeing the same warning with v4.15.9 (but not with 4.15.8)

this is when the following is set in `astro.config.js`:

```ts
security: {
	checkOrigin: true,
},
```

should i open a new issue?
