### ISSUE TITLE
The collection "blog" does not exist or is empty with `contentCollectionCache` enabled under astro 5 beta.

### ISSUE THREAD

**Issue by oxSaturn** [withastro/astro#12065]
### Astro Info

```block
Astro                    v5.0.0-beta.2
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When building the site with `npm run build`, I would run into this error:

> The collection "blog" does not exist or is empty with `contentCollectionCache` enabled.

### What's the expected result?

I would expect the build to proceed without the problem.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9pytya?file=src%2Fcontent%2Fconfig.ts,src%2Fdata%2Fblog%2Ftest.md,src%2Fpages%2Fblog%2F[...slug].astro,src%2Fpages%2Findex.astro,astro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Experimental Content Collections Cache will soon be removed (likely in the next 5.0 beta), in favor of Content Layer

**Comment by ascorbic** [comment]
CCC is no longer supported, so I'm closing this
