### ISSUE TITLE
ViewTransitions breaks Supabase OAuth

### ISSUE THREAD

**Issue by kevin-moechel** [withastro/astro#12080]
### Astro Info

```block
Astro                    v4.15.9
Node                     v20.17.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/solid-js
```

### Describe the Bug

Using ViewTransitions breaks the OAuth flow with supabase, and potentially others. The request to the OAuth provider (tested with Github and Google) is declined with a CORS error. Instead you land on a 404 page. Tested with Chrome Version 129.0.6668.59.

For the test setup clone https://github.com/kevinzunigacuellar/astro-supabase, get a free or local supabase instance, configure OAuth for any provider and run the app. Without ViewTransitions the login works as expected. With ViewTransitions you run into the error.

I tried a workaround that adds the ViewTransitions only conditionally to the `Base.astro` layout but that didn't work.
Then I tried to use a completely differnet layout for the `singin.astro` page but even that didn't solve the issue either.

### What's the expected result?

Login flow for OAuth is not affected by ViewTransitions

### Link to Minimal Reproducible Example

https://github.com/kevinzunigacuellar/astro-supabase

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @kevin-moechel, that is not a minimal reproduction. 
Do you have at least some deployment I can take a look at?

**Comment by martrapp** [comment]
@kevinzunigacuellar Hi Kevin, maybe you have some quick insights?

**Comment by kevinzunigacuellar** [comment]
@martrapp I wish I could but I am very new to view transitions. Let me take a look

**Comment by martrapp** [comment]
Hi @kevinzunigacuellar, thank you s o much!
I would be happy to help with the original issue but it would really be helpful to have a reproduction. I do not use Supabase and me setting up OAuth might or might not be successful ;-)

View Transitions only work with same origin, but they should gracefully fallback on cross-origin routes.

@kevin-moechel, I guess a in a first step some deployment of an app with the error would be good enough, no need for a stackblitz or github repo for first analysis.

**Comment by kevin-moechel** [comment]
@martrapp  @kevinzunigacuellar I have a running, minimal version of the issue [here](https://astro-supabase-oauth.vercel.app/).

On the page you have a Google login using Astro Endpoints. The Layout uses ViewTransitions. This yields in the CORS error.

There's an identical page [here](https://astro-supabase-oauth.vercel.app/without-view-transition), that doesn't use ViewTransitions. Login works as expected.

Login with Astro Actions and ViewTransitions is working though. It's just the combination of ViewTransitions and Endpoints that doesn't seem to work. See [here](https://astro-supabase-oauth.vercel.app/with-server-action).

[This](https://github.com/kevin-moechel/astro-supabase-oauth) is the repository for the page.

**Comment by kevinzunigacuellar** [comment]
Thanks for the reproduction. It seems that submitting the form is trying to do a client navigation to the endpoint. I am getting the following error

```
[WARN] [router] No API Route handler exists for the method "GET" for the route "/api/auth/signin".
Found handlers: "POST"
```

adding `data-astro-reload` to the form seems to fix the issue

```astro
---
import Layout from "../layouts/Layout.astro";

const accessToken = Astro.cookies.get("sb-access-token");
const refreshToken = Astro.cookies.get("sb-refresh-token");

if (accessToken && refreshToken) {
  return Astro.redirect("/dashboard");
}
---

<Layout title="Sign in">
  <h1>Sign in</h1>
  <p>New here? <a href="/register">Create an account</a></p>
  <form action="/api/auth/signin" method="post" data-astro-reload>
    <label for="email">Email</label>
    <input type="email" name="email" id="email" />
    <label for="password">Password</label>
    <input type="password" name="password" id="password" />
    <button type="submit">Login</button>
    <button value="github" name="provider" type="submit">Sign in with GitHub</button>
  </form>
</Layout>
```

Maybe Martin can explain better what is happening here as I am quite new to view transitions. Hope this helps!

**Comment by martrapp** [comment]
We are getting somewhere ;-)

Thank you Kevin! `data-astro-reload` allows you to opt out of view transitions for a link or a form submission. So that would be perfectly fine as a solution.

I will see whether I can find out why there was no graceful fallback in this particular case.
