### ISSUE TITLE
Astro Info shows incorrect astro version

### ISSUE THREAD

**Issue by apatel369** [withastro/astro#12082]
### Astro Info

```block
Astro                    v4.15.9
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I created a new Astro v5 beta project using `npm create astro@latest -- --ref next`.
It correctly installed Astro 5.0.0-beta.2.
But when I run `astro info` in that project's directory It shows Astro version 4.15.9 instead of 5.0.0.-beta.2

![Screenshot 2024-09-26 at 10 49 27 PM](https://github.com/user-attachments/assets/8401dfb7-388b-4280-8cac-39592d3b41ef)

      Here are the options I chose while creating project
      ```
       astro   Launch sequence initiated.
      
         dir   Where should we create your new project?
               ./molecular-mercury
      
        tmpl   How would you like to start your new project?
               Include sample files
      
          ts   Do you plan to write TypeScript?
               Yes
      
         use   How strict should TypeScript be?
               Strict
      
        deps   Install dependencies?
               Yes
      
         git   Initialize a new git repository?
               Yes
      
            ✔  Project initialized!.
               ■ Template copied
               ■ TypeScript customized
               ■ Dependencies installed
               ■ Git initialized
      
      ```

### What's the expected result?

Astro info should show version 5.0.0-beta.2.

### Link to Minimal Reproducible Example

create new project using command npm create astro@latest -- --ref next

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Are you sure you don't have a global version of Astro installed? Try running `npm run astro info` instead.

**Comment by apatel369** [comment]
> Are you sure you don't have a global version of Astro installed? Try running `npm run astro info` instead.

@Princesseuh ```npm run astro info`` shows the correct output so I am closing this issue.

```
Astro                    v5.0.0-beta.2
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none

```
