### ISSUE TITLE
Astro 5 Beta and Node Adapter

### ISSUE THREAD

**Issue by cball** [withastro/astro#12091]
### Astro Info

```block
Astro                    v5.0.0-beta.2
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         astro-icon
```

### Describe the Bug

Similar to #12059, I'm not able to install the node adapter when using a 5.0 beta.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @example/minimal@0.0.1
npm ERR! Found: astro@5.0.0-beta.2
npm ERR! node_modules/astro
npm ERR!   astro@"^5.0.0-beta.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer astro@"^4.2.0" from @astrojs/node@8.3.4
npm ERR! node_modules/@astrojs/node
npm ERR!   @astrojs/node@"^8.3.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### What's the expected result?

The adapter should install so the app can be deployed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-oqungq?file=package.json&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You need to install the beta version of the integration. `astro add` installs the latest stable version and as such, cannot be used for betas at this time.

**Comment by cball** [comment]
@Princesseuh I understand `add` only installing beta versions, I had just missed the beta release for the adapter since it was further down the releases page. Thanks!

**Comment by dansasser** [comment]
I installed the node npm package using the legacy flag but I am unable to use node as my output adapter in my Astro config. I get an error when I try but if I just leave output set to server with no adapter everything seems to build and work fine as SSR
