### ISSUE TITLE
Content Collections: restart needed to get latest content after `astro sync`

### ISSUE THREAD

**Issue by lgastler** [withastro/astro#12103]
### Astro Info

```block
Astro                    v5.0.0-beta.3
Node                     v18.20.4
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

When using the "new" content collections with f.e. a REST Endpoint in `output: "server"` mode. The content fetched using `astro sync` is not reflected in the data without a server restart. 

### What's the expected result?

I expected to be abel to use `astro sync` to manually or triggered by several triggers update the underlying data store for content collections, so pages rendered on demand could access that newly updated / synced content. 

### Link to Minimal Reproducible Example

https://github.com/lgastler/astro-cc-sync-ssr

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
Are you referring to the production server, or dev? If it's production then this is as expected, because production servers don't support hot reload.

**Comment by lgastler** [comment]
Talking about production, I am aware that this might be more of a feature request. Just wanted to know if this is expected and if it may be interesting to explore. Really love using "content layer" to gather multiple sources some of which are quite dynamic so if this would work it would be great.

**Comment by lgastler** [comment]
Great thanks for the quick response and explanation :) looking forward to it 👍🏼
