### ISSUE TITLE
Build cancelled when running pnpm astro sync

### ISSUE THREAD

**Issue by Serpentarius13** [withastro/astro#12138]
### Astro Info

```block
Astro                    v4.15.11
Node                     v20.16.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
```

### Describe the Bug

When running pnpm astro sync to sync up content collections, it outputs this:
![image](https://github.com/user-attachments/assets/09bcf2c4-f0ea-47db-8141-6fc9bccfbbe3)

And types for `data` property on collections are not generated (any). Also, when removing `content` folder, it works just fine

### What's the expected result?

Generate typings

### Link to Minimal Reproducible Example

https://github.com/Serpentarius13/astro-build-cancelled-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Serpentarius13** [comment]
It seems I just didn't add `config.ts` there =) Baka

**Comment by florian-lefebvre** [comment]
Yeah even though there's this log, it doesn't actually break anything. It would be nice to understand why it shows tho

**Comment by ascorbic** [comment]
This was fixed in #11976, so will be in the next beta release

**Comment by Serpentarius13** [comment]
> Yeah even though there's this log, it doesn't actually break anything. It would be nice to understand why it shows tho

The log was because I used `index.ts` file instead of `config.ts` in src/content directory. I spent an hour or two scrambling at dist source code to console.log the issue down and found out that it couldn't find my file. I think errors could be about what happened, and not that the "build was cancelled"? On every check where there's something missing and would proceed further (return void 0), wouldn't it be cool to add some logger.error("This thing not found")?

**Comment by florian-lefebvre** [comment]
As Matt said, it should be fixed in the last beta

**Comment by Serpentarius13** [comment]
> As Matt said, it should be fixed (and such case covered) in the last beta

Oh I see, have missed the line about logging. But I think as there are about 3 issues popped by this error, wouldn't it be add logging for other errors and not only missing content collections? It is just uninformative

**Comment by ascorbic** [comment]
It's allowed to have no `config.ts`, so we shouldn't be logging about that.

**Comment by Serpentarius13** [comment]
> It's allowed to have no `config.ts`, so we shouldn't be logging about that.

Yeah, I undestand, but wouldn't there be any other places where such an error would pop up without explanation? In the future or now maybe? If anyone did something wrong, CLI wouldn't point it out to them then
