### ISSUE TITLE
🐛 BUG: Cannot import TS types and interfaces

### ISSUE THREAD

**Issue by adamarutyunov** [withastro/astro#12144]
### Astro Info

```block
Astro                    v4.15.11
Node                     v21.7.3
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

I have encountered the same bug that was fixed three years ago: https://github.com/withastro/astro/issues/3787

In an astro component, it is not possible to import an interface or a type from a typescript file.

The behaviour is the same:
- It does not matter if `.ts` is included or not (`import x from "./x.ts"` vs `import x from "./x"`);
- It does not matter if the export is default or not;
- It does not work neither with `export type` nor `export interface;
- Imports and exports of any other JS native items (functions/objects/etc) work perfectly;

The only difference is that the “Weird workaround” (to add any other non-TS export in the file) does not work anymore.

### What's the expected result?

Interfaces and types should be able to be imported as it is convenient to use these repeatable items in different components.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dkmvrf?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
TypeScript types don't have runtime values, as such it's normal that they'll always be undefined when trying to console.log them.

In an editor with intellisense, you'll get a warning when trying to do so: 
<img width="598" alt="image" src="https://github.com/user-attachments/assets/db4f534f-29c0-49f9-aa4c-067c2bf404dc">

The actual type works fine: 
<img width="337" alt="image" src="https://github.com/user-attachments/assets/1777055f-8421-4494-9f7b-e8743ec749c6">
