### ISSUE TITLE
[sitemap] `xslURL` option not declared in `SitemapOptions` type

### ISSUE THREAD

**Issue by AverageHelper** [withastro/astro#12153]
### Astro Info

```block
﻿﻿Astro                    v4.15.12
Node                     v20.15.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

### Describe the Bug

Trying to define `xslURL` in the options for `@astrojs/sitemap` (see #11485), but `astro check` fails because "`Object literal may only specify known properties, and 'xslURL' does not exist`" in the `SitemapOptions` type.

### What's the expected result?

Should be able to define `xslURL` and run `astro check` without issue.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uxjrgn?file=astro.config.ts&view=editor

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Looks like we also need to add the types here: https://github.com/withastro/astro/blob/de35daa8517555c1b9c72bc7fe9cc955c4997a83/packages/integrations/sitemap/src/index.ts#L19-L39
