### ISSUE TITLE
Security vulnerability report

### ISSUE THREAD

**Issue by pwntester** [withastro/astro#12176]
### Astro Info

Hi, I reported a critical security vulnerability in July the 5th via GitHub private vulnerability reporting, but its being ignored so far. 

### Describe the Bug

Details in the PVR report.

### What's the expected result?

Report is acknowledged and vulnerability gets fixed

### Link to Minimal Reproducible Example

https://astro.new/latest/

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Thank you @pwntester 

Sorry if we overlooked your report, however we ask you to refrain from creating issues. 

You can check here our process: https://github.com/withastro/astro/blob/main/SECURITY.md
And contact the security team on Discord: https://github.com/withastro/astro/blob/main/SECURITY_CONTACTS
