### ISSUE TITLE
CLI failed to install new project

### ISSUE THREAD

**Issue by bumpyy** [withastro/astro#12183]
### Astro Info

```block
-
```

### Describe the Bug

The CLI failed to install new project.

cli always error on project init:
![image](https://github.com/user-attachments/assets/440eeefc-2e11-4c2c-8358-c67b6039cf48)

For context i'm using windows nvm via Laravel herd, idk if this is the problem because my other machine has no issue (not using Herd), but i've tried turn off nvm, herd, and install node manually, even clear cache folder, but no change.

the log are as follows:

![image](https://github.com/user-attachments/assets/c26a0882-fe44-496a-97ee-bafa8cda493c)

for the manually installed node are as follows:

![image](https://github.com/user-attachments/assets/9d2adcdd-ed21-4380-9afa-ba65596804ca)

### What's the expected result?

Astro CLI successfully generated new project. 

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Is this your first time running the CLI or has it worked in the past for you? We recently updated it with a new deoendency and I wonder if it caused a regression (it shouldn't have though as long as you're using node18, which your logs shown as 20 & 22). I tested locally with the latest CLI (on macos) and it seems to still work fine.

**Comment by bumpyy** [comment]
I've used it before, no issues
Though I haven't use herd yet. 

I've also tried using node 18 but still the same.

I'll try to uninstall herd first thing in the morning to see if it works.

**Comment by bumpyy** [comment]
> I've used it before, no issues Though I haven't use herd yet back then.
> 
> I've also tried using node 18 but still the same.
> 
> I'll try to uninstall herd first thing in the morning to see if it works.

Nope, not herd
I've also removed pnpm & bun but still error.

**Comment by bumpyy** [comment]
I think this is create-astro issue.

I tried to create Vite project, Nextjs, & Nuxt, and they are working perfectly.

I'm using windows 10 btw.

**Comment by bumpyy** [comment]
Hey @bluwy just an update,

I just updated to create-astro@4.10.0 and it's working now using herd (nvm) or regular node install.

![image](https://github.com/user-attachments/assets/a27978c4-bd9a-4819-8db4-056543ee1274)
