### ISSUE TITLE
`entryFileNames` behaves strangely

### ISSUE THREAD

**Issue by rik9228** [withastro/astro#12184]
### Astro Info

```block
Astro                    v4.15.7
Node                     vv20.14.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Integrations             sitemap, react
```

### Describe the Bug

No control over bundled files other than scripts that run on the page itself.

### What's the expected result?

Assume a situation where a page-specific script and a common script are executed respectively.

For example, if the script below is executed, after build,

```typescript
import { Common } from "@/scripts/common";

export function Top() {
	Common(); // common scripts
	console.log("huga");
	return 2;
}

```

The following file will be generated.

`common.hash.js`.

Is it possible to change this file name freely?
It would be nice to at least be able to remove the hash name.

This file seems to be completely excluded from options such as astro.config > `vite.build.entryFileName`, so it is not possible to extract the file name using chunkInfo.

The output destination is also not controlled by these options, and I can forcibly change the output destination by specifying the top-level build.assets, but it is a bit confusing.

Is there any way to resolve this?

![image](https://github.com/user-attachments/assets/5871b3c6-4498-4deb-88ae-115e69007a8c)

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/rik9228/astro_boiler_template

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Because you have two entries (Top and About) sharing the same code (`common.js`). That code will be located in a shared chunk, so you should use `chunkFileName` to customize the name instead.
