### ISSUE TITLE
Astro 4.16.0: Astro.currentLocale Not Updating on Route Change

### ISSUE THREAD

**Issue by TrySquadDF** [withastro/astro#12185]
### Astro Info

```block
Astro                    v4.16.0
Node                     v20.9.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

all

### Describe the Bug

I've encountered an issue with `Astro` version `4.16.0.` The `Astro.currentLocale` is behaving inconsistently: when I change routes, the language doesn't update as expected.

### What's the expected result?

When changing routes within the application, the Astro.currentLocale should update to reflect the language associated with the new route.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/nkkt4h

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by santhoo** [comment]
Same here. After 4.16 update, my currentLocale works inconsistently.

**Comment by thisisrexa** [comment]
Same here

**Comment by drimchansky** [comment]
Same regression noticed
