### ISSUE TITLE
Still getting deleted collection entries from getCollection function

### ISSUE THREAD

**Issue by jurajkapsz** [withastro/astro#12195]
### Astro Info

```block
Astro                    v4.16.0
Node                     v20.11.1
System                   Linux (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

1. I have a file-based [mdx] Content Layer collection, using the build-in glob loader.
2. While running Astro dev, when I delete a file from collection (ie remove a collection entry), I'm still getting all collection entries from `getCollection` function, including the deleted ones, and the deleted entries are still being used in output generation.
3. After restarting Astro dev, the `getCollection` function returns entries correctly, without the deleted ones, and they [the deleted ones] are also no longer being used in output.

### What's the expected result?

Not needing to restart Astro dev to have deleted collection entries discarded from returned collection list, if that's how it should be.

### Link to Minimal Reproducible Example

Repro needed on this one?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jurajkapsz** [comment]
Now I also noticed the following behavior:
- When I start Astro dev, and create a new collection entry, the collection entries list gets correctly updated, it gets added the new entry.
- When I delete the newly created entry, the collection gets also correctly updated, having one entry less.
- But when I delete an entry, that was created before the Astro dev was run (in a previous dev session), the collection does not get updated, as reported. So it doesn't work for "old" or already existing entries from previous dev sessions.

**Comment by apatel369** [comment]
@jurajkapsz I am not able to reproduce this. Please provide a reproducible example.

**Comment by jurajkapsz** [comment]
Thanks @apatel369 , will do in couple of days.

**Comment by jurajkapsz** [comment]
I couldn't reproduce it on [stackblitz](https://stackblitz.com/edit/github-5d3ggt ), but it happens on my local pc, where I've tried the same again.

![image](https://github.com/user-attachments/assets/9ddd83f3-4b84-403e-b739-083142c99f3e)

**Comment by jurajkapsz** [comment]
After I run `build`, the entries were correct in built `dist` files, ie showing `2`, but that's the same as restarting `dev` server, when the entries list [`getCollection`] also gets updated, ie shows `2` etc.

**Comment by jurajkapsz** [comment]
Maybe I could try to make a local clean install of Astro and try it there, as this was tried out in my existing project, but I don't think there is anything special used in the project.

**Comment by florian-lefebvre** [comment]
@ascorbic I wonder if this issue is the same I was encountering, about data store not refreshing

**Comment by jurajkapsz** [comment]
The fix works, thanks @florian-lefebvre !
