### ISSUE TITLE
Blank page on Cloudflare Pages

### ISSUE THREAD

**Issue by jamesli2021** [withastro/astro#12203]
### Astro Info

```block
Astro                    v4.16.1
Node                     v20.17.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
```

### Describe the Bug

I see blank page after followed this tutorial: deployed to GitHub and Cloudflare build success.

https://logsnag.com/blog/deploy-astro-cloudflare-pages-guide

### What's the expected result?

What is the issue if SSR should be straightforward?

### Link to Minimal Reproducible Example

https://github.com/jamesli2021/test5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I'm guessing it's related to a recent regression. Can you try Astro 4.16.0 instead? https://github.com/withastro/astro/issues/12201

**Comment by jamesli2021** [comment]
Can't test it since `npm create astro@4.16.0` command don't work?

**Comment by willtemperley** [comment]
I just came across this, but with slightly different setup, I'm using Cloudflare Frameworks beta.

I can confirm using 4.16.0 works, I was getting this error with 4.16.1

```
TypeError: Can't modify immutable headers.
    at setOriginHeader (_worker.js:14991:19)
....
```

@jamesli2021 Just set Astro to the exact version in your package.json:

```
  "dependencies": {
    "astro": "4.16.0",
  },
```

**Comment by jamesli2021** [comment]
@willtemperley I did tried to change the version number to 4.16.0 and reinstall packages, npx astro info shown 4.16.1.

**Comment by jamesli2021** [comment]
@willtemperley Great thanks! 4.16.0 works for me.

**Comment by bluwy** [comment]
Thanks for the update. I'll close this for now in favor of https://github.com/withastro/astro/issues/12201 then. We'll use that issue to track the bug.
