### ISSUE TITLE
TypeError: Can't modify immutable headers. in Cloudflare Pages after updating to 4.16.1

### ISSUE THREAD

**Issue by nicbovee** [withastro/astro#12201]
### Astro Info

```block
Astro                    v4.16.1
Node                     v20.16.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/react
                         @astrojs/svelte
                         @astrojs/tailwind
                         @sanity/astro
                         @sentry/astro
```

### Describe the Bug

After building with `4.16.1` my site running on Cloudflare Pages in `hybrid` mode 500's on all non-prerendered routes.

Looking at the realtime logs I see complaints about headers:
```
18:17:35 [ERROR] TypeError: Can't modify immutable headers.\n    at setOriginHeader (chunks/index_CUH8Sv5d.mjs:1356:19)\n    at RenderContext.create (chunks/index_CUH8Sv5d.mjs:1393:5)\n    at async App.render (chunks/_@astrojs-ssr-adapter_BtNH5sZC.mjs:824:29)\n    at async Object.fetch (chunks/_@astrojs-ssr-adapter_BtNH5sZC.mjs:1016:22)
```

In the build output there's also a bunch of warnings now that hadn't been there up to this point:
```
11:28:16.727	18:28:16   ├─ /daily-readings/it-must-be-small/index.html18:28:16 [WARN] `Astro.request.headers` is unavailable in "static" output mode, and in prerendered pages within "hybrid" and "server" output modes. If you need access to request headers, make sure that `output` is configured as either `"server"` or `output: "hybrid"` in your config file, and that the page accessing the headers is rendered on-demand.
11:28:16.731	 (+4ms)
```

Locking the version to `4.16.0` and re-deploying fixed it.

### What's the expected result?

I would expect these routes to work.

### Link to Minimal Reproducible Example

https://hotfix-hide-entire-countdown.wildatheart1.pages.dev/the-series

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nicbovee** [comment]
Possibly caused by this change:
https://github.com/withastro/astro/commit/2d10de5f212323e6e19c7ea379826dcc18fe739c#diff-153aea9d29dc6f65b7f594f4674159c48939a8402408a2e11742275c19c3dc94R86

**Comment by nicbovee** [comment]
Wondering if [this](https://github.com/withastro/astro/commit/2d10de5f212323e6e19c7ea379826dcc18fe739c#diff-153aea9d29dc6f65b7f594f4674159c48939a8402408a2e11742275c19c3dc94R86) should change to:
```
export function setOriginHeader(request: Request, pathname: string): void {
	request.headers.append(ASTRO_ORIGIN_HEADER, encodeURIComponent(pathname));
}
```

I'm missing context around this, but it looks like `X-Astro-Origin` is a new header when `setOriginHeader` is called, which makes me think `.append` is the right method to use based on [these docs](https://developers.cloudflare.com/workers/examples/alter-headers/) from cloudflare.

**Comment by flashblaze** [comment]
For some reason, if I build locally and then deploy using `wrangler pages deploy dist` this does not happen for me. However, if I push the code to GitHub and Cloudflare builds it automatically, I get the same error.

I'm on `astro` version `4.16.0`

**Comment by JusticeMatthew** [comment]
I feel like set should be fine here after doing a bit of digging

This might be a bit above my skill level but to me it seems the issue would be caused by not duplicating the request in that utility function first (so it’s mutable), modifying it, and returning the modified request

I could be way off base though

**Comment by ammi1378** [comment]
I had the same issue, downgrading to astro@4.16.0 fixed it.

**Comment by jahands** [comment]
> I feel like set should be fine here after doing a bit of digging
> 
> This might be a bit above my skill level but to me it seems the issue would be caused by not duplicating the request in that utility function first (so it’s mutable), modifying it, and returning the modified request
> 
> I could be way off base though

This is correct - in Cloudflare Pages / Workers, the request must be duplicated to make it mutable.

```ts
async fetch(request, env, ctx) {
	// Comment this line out to see that the duplciated request works:
	request.headers.set('x-foo', 'bar') // FAIL

	// Duplicate request to make it mutable
	const req = new Request(request)
	req.headers.set('x-foo', 'bar') // WORKS!

	return new Response('hello world')
},
```

[Here's a demo](https://workers.cloudflare.com/playground#LYVwNgLglgDghgJwgegGYHsHALQBM4RwDcABAEbogB2+CAngLzbPYDqApmQNJQQBimYACFKNRHQAqYAMIBGLgA8uAZwQA3BAAsJASTJQAXCxYduvAVhHVakmfKWqN2vVACwAKGnoqEdj+wAIlDKMOjKvFDeBiQYWHgExCRUcMDsDABE+IQAdABWyumkqFBgfilpmQl5BR5ePn4Q2BJ0MOzRcDAwYFAAxgSRVMi5cGpwyj0IsBAA1MDouODsHh7sCqFIJLjsqHDgECQA3u4AkMmp0ekAogopXewkAIIACjrpADQnhADmytEA2ulVrdSu8SOkOlBQekEOwQt5lOx0gBdD4AXyI7g8xmYph4-EEVjE9CkckUKnUWl0+lq3l8-iCcPC0CiMUE8UIpDOFSgNFW1UKMRKZVSGR5WwU-Jp9X8zVa7U63T6zMGw1G40mMBmcwWpWW7igwHW+wA7uwwD10KkYghLWDTebLexspoIMAwIV3O5kAAqb3uEjekgAAQgLXYW1QhwA8mRcuwehBUSRLlQ1P7vchPasjZttrtIIcTj6-ccA8H4AgUocAErsACOIFhiZIMIbTZOZaDFarBxTaiTfjTpcDXcQPeu8ZAyrqvgUzYTCg7I5hEBACCoykOTxtwGC7AAPLW4Rv2AA+VFLzPHMZ0Kg9GLsCA9TQAClbjeUEDeJEH34XAEpC2OY5kGQEgvGAVIfBICBNGCEhuioe5KH2CB0BIBF7lgggYM0e4Fi6HooAIcMW3rD8TUwABrX4TmOd8m2ddg4C2BBlGyBEIBfAByBRsAwdBuO-biyEQbjANAkg+AeHQABlPWAySAhALpehIsi20-GD0OAOAqPuXgSFAQgyFKOiLQ3fZWxIBgknYY0SFrTSuIYz9-zo1smJY9g2I4x8eL4gShJIESxIksDWCjasuAAZQAQgU+jHzXKg7Ico9QhPHi8LAMB0ONTAwFwcSTlRNEMSxbFcXMAlRBsEl7HJJwqTcTxaQaQJglCJkBmiWIcCyRIuQye0LVSZ1XXdIohWG9JRsdCa3XSKU6UaWU2hg1YUC6OAeT1fc4oCKNpAkABNJ5LhIF03VPdx92usAELgKgvgyPx0lu457uY3BPq+1JCBIZ9EE4jIAFUJD4bAAA50hIZA-v3AG4CuiAIBgbByKgNQMgADWwMGHmwCD4GgUzESB9qfAyHRLgYcMvgphG6KRx8UdmtQoHso04Ys1aRqgXBYIYLZOZ6dhsGNQXYO-HkIjgMBsHGBW0lkbIAAY4eZ4D92gCBSlPaQ8pAXBUDARB7lYaifM3J5zboL4bWsfdkD1g2WcQqi6KSsAMk-OhSmUPDH3Sb3NBhVAMhddHflAnaHadmhslFmAbVwbIemN03zZhZP2DUZB5tSJXQ1KDPlAKOjtZdvCWNuk59woXA6ER3BsaB82K4yM2LYKP6voNL4MIQHoo7RmBY+QePHbqvO1FT+YM6znvc9FtAc9hbIYBerXEeQNu1ER3SeX7-cD47sZlBG622OwPKvnQD6XYP0+YH744OAdVI4pIMGEVw+Cds4AJzqtpTaWlcCTDUPcFGVsED6QQH+GE6kUZbDmNpb2xwg4WxIN4RC7BvzPVwCQY0eFUrIObrmLo6A6CbCgDCBMYBaFoVwvcBm9wyC0M4tAF6JAVIkDgJgo2lBs44LgD0C01AIDZG9i7N+sjNCyFPKwTQOF4KwJvgAfhrko2R8jgLAQeOBZeG8SBwIQSQeCAApEYcAYoTCmJTLYJA6CUBIZMXwuEcKqJoIHFxlAEAkM4Jgpk7BuKbgABISAkE8GClZUDFHvG3Bh+taE8mMSIleYTNzsIQugJUAxNyIFAbBdgmCCoICKoQ3K6Apa8NcSAMBeUlT3AtM4zOYQsLoQaYEvwxCQAIjYpY1KmBWIYIMUlY8xCWGlOAEZTA9wGy9Cokw2RU9T6KNPBIeglj9g9IRGAVAOjX7vyjKlHpCFtj7HURhYElsb5eOuZuBA1AqA8iHt4ABm5QnZBIKdNxfQqCYPDIZQy3RoECJoBhdgWE8JkWUHsTceFc7JjbqhOFpNNACIoBClhyAITjIMZhK6tTWE-huIaUoZiHk+NwH4tuCSfINBbChTefyAXPQEWAZQ6EQUQEwaUpxXToX3FIQQcJJBurhHJpC4hZBJj1ICXZOclitgoxYd0VATo1n6K+sgY+VBPouybi3O6yAHq3UqsYaq+JLB1XEA1MkjhKQuBWh1Bk3UIgsn6uyIa5QMjI0GgKYopRZqmXQGQZabVpRrTDPKVSBTvBDB5VQPUBx0hjVJlAfQ3RQwAH0siIgMOkAATOrEtAAWbA6sADM1aADs7wM2WizTm3gdA809x+OkAwAIqDzHYPkPNmaCDIjeOkA1ebtSLB7ekMUfJ8jpFRFakwnA8QWGEPa4kdgnUUmcPoZgHggA)

**Comment by bluwy** [comment]
Sorry for the inconvenience everyone. For now I'd suggested pinning Astro to `4.16.0` to workaround this.

```json
// package.json
{
  "dependencies": {
      "astro": "4.16.0"
  }
}
```

We'll likely only able to get to fixing this next Monday, but I'll check with the team if we should revert https://github.com/withastro/astro/pull/12173 for now, which seems to be the cause here.
