### ISSUE TITLE
empty page returns `<!DOCTYPE html>`

### ISSUE THREAD

**Issue by Ahwxorg** [withastro/astro#12209]
### Astro Info

```block
yarn run v1.22.22
warning package.json: No license field
$ astro info
Astro                            v4.16.1
Node                              v20.17.0
System                          Linux (x64)
Package Manager       yarn
Output                          static
Adapter                        none
Integrations             @astrojs/tailwind
                                       @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

curl

### Describe the Bug

curl https://domain.tld/page returns `<!DOCTYPE html>text` (or the view page source button in Firefox does too)

### What's the expected result?

it should return just `text`, not the `<!DOCTYPE html>`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1jo8fr?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Ahwxorg** [comment]
You can see my page at i.e. https://liv.town/i/matrix.

**Comment by florian-lefebvre** [comment]
I believe this is wanted (cc @bluwy). I think if you don't want this, you should probably use [endpoints](https://docs.astro.build/en/guides/endpoints/) instead

**Comment by Ahwxorg** [comment]
Alright, I'll use endpoints!
