### ISSUE TITLE
Warning messages when creating a new project with empty template on 4.16.1

### ISSUE THREAD

**Issue by ayberktandogan** [withastro/astro#12202]
### Astro Info

```block
Astro                    v4.16.1
Node                     v20.17.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When creating a new project with default options except the template selected empty, I get the error:

```bash
[WARN] `Astro.request.headers` is unavailable in "static" output mode, and in prerendered pages within "hybrid" and "server" output modes. If you need access to request headers, make sure that `output` is configured as either `"server"` or `output: "hybrid"` in your config file, and that the page accessing the headers is rendered on-demand.
```

I haven't added, changed or removed anything. It just prints this on every refresh.

You can also see the same behaviour on the stackblitz example as well.

### What's the expected result?

It should give me no errors because I'm not trying to access "Astro.request.headers" anywhere in the code.

**This does not happen on 4.16.0**

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewmercuri** [comment]
I can corroborate this as well. Just tried a fresh install and also on my newly updated existing Astro repo.

**Comment by CaptainSwag101** [comment]
I am getting this problem after upgrading my site (created using the built-in blog template in 4.15.1) to 4.16.1 as well. I can't seem to find anywhere in my own code where `Astro.request.headers` is used, and the error message doesn't give me any useful information as to where or how I might correct this issue without changing to "server" or "hybrid" mode.
