### ISSUE TITLE
Dev server error: `ReferenceError: module is not defined` (`node_modules/cssesc/cssesc.js:73:1`)

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#12229]
### Astro Info

```block
Astro                    v4.16.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When `vite.ssr.noExternal = true` is set, no page can be accessed from the dev server. Production build is not impacted.

<img width="403" alt="{97E1B4C7-895B-49DE-985E-9622DE12020A}" src="https://github.com/user-attachments/assets/796a5ddb-08d3-4704-8c25-b2c6a762876c">

<img width="640" alt="{D430CCB9-5804-45A8-82D9-9A335BBDBABB}" src="https://github.com/user-attachments/assets/65384551-0548-433d-bb7c-5580237e0117">

### What's the expected result?

`vite.ssr` has no effect on the dev server. Alternatively, `cssesc`-related issues only arise when its code is needed (i.e., in projects using view transitions), or `cssesc` can be detected as a commonjs module and be transpiled appropriately.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jdp8df?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi Arsh! Good do hear from you again!

Let me take a look 👀

**Comment by martrapp** [comment]
Surely you know the remedy, but for others who may stumble across it in the meantime, it's a quick fix:
In the `astro.config` re-add `cssesc` after `noExternal: true`
```diff
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  vite: {
-   ssr: { noExternal: true },
+   ssr: { noExternal: true, external: ['cssesc'] },
  },
});
```

**Comment by bluwy** [comment]
We can add cssesc here https://github.com/withastro/astro/blob/6df5bba870001ccaf7eee5ad7707ba6c90f955c4/packages/astro/src/core/create-vite.ts#L66-L74

Though using `ssr.noExternal` in dev is kinda a rare case too since you're saying all your dependencies recursively export ESM, which isn't the case most of the time.
