### ISSUE TITLE
Regular view transitions using JS have are choppy

### ISSUE THREAD

**Issue by ericmikkelsen** [withastro/astro#12224]
### Astro Info

```block
Astro                    v4.16.2
Node                     v22.5.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

I've been working on an [animating details and summary with some js view transitions on codepen](https://cdpn.io/pen/debug/JjgWoMQ) and got it most of the way there, so I moved [the details and summary to Astro](https://accordion-reduced-test-case.netlify.app/) and the animation runs different, it's always choppy and consistent. The repo is a reduced test case where only the index.astro has been updated with an exact copy of the codepen work.

### What's the expected result?

The astro project should match the smooth animation of the codepen.

### Link to Minimal Reproducible Example

https://github.com/ericmikkelsen/accordion-reduced-test-case/tree/main

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @ericmikkelsen 👋🏼, you copied the codepen, but Astro does not generate the same HTML as it automatically scopes styles, which in your case makes some `::view-transition` rules unusable.

To opt-out of scoped styles **change `<style>` to `<style is:global>`**. Opting out is important for all selectors that address the `:root` element or its pseudo-elements like `::view-transition-old`. 

Please see the generated styles for examples, e.g. the selector `::view-transition-old(middle) [data-astro-cid-j7pv25f6]` targets the body, not the old image.

**Comment by martrapp** [comment]
@ericmikkelsen, did adding `is:global` to the `<style>` element remove the different behavior for you?
If not, feel free to reopen this issue  with additional information.

**Comment by ericmikkelsen** [comment]
> @ericmikkelsen, did adding `is:global` to the `<style>` element remove the different behavior for you? If not, feel free to reopen this issue with additional information.

Hey @martrapp ! It did, so did adding the html to my view transition like `html::view-transition-old()`. Thanks for the response!
