### ISSUE TITLE
Not working `vite.build.copyPublicDir` option

### ISSUE THREAD

**Issue by rktyt** [withastro/astro#12230]
### Astro Info

```block
Astro                    v4.16.4
Node                     v20.15.0
System                   Linux (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

```typescript
// build.ts
import { build } from 'astro'

process.env.NODE_ENV='production'

await build({
  root: process.cwd(),
  mode: 'production',
  vite: {
    build: {
      copyPublicDir: false,
      sourcemap: false,
    },
  },
})
```

```typescript
// astro.config.ts
import { defineConfig } from 'astro/config'
import node from '@astrojs/node'
import { tmpdir } from 'node:os'

export const outDir = 'astro.dist'

export const buildExcludePackages = []

export default defineConfig({
  trailingSlash: 'ignore',
  output: 'server',
  adapter: node({
    mode: 'middleware',
  }),
  outDir,
  cacheDir: `${tmpdir()}/.astro-cache`,
  vite: {
    cacheDir: `${tmpdir()}/.vite-cache`,
    resolve: {
      alias: {
        '~': `${import.meta.dirname}/src`,
      },
    },
    optimizeDeps: {
      exclude: buildExcludePackages,
    },
  },
  build: {
    assets: 'gen.assets',
    client: `${outDir}/client`,
    server: `${outDir}/server`,
  },
})
```

I am currently building with `npx tsx build.ts` using the above file, but the contents of the public directory are copied into the dist directory.

----

The astro's adapter and output options do not seem to matter.
A simpler form is described below.

1. `npm create astro@latest my-astro-project -- --template minimal --no-git --typescript strict --yes`
2. change astro.config.mjs
3. `npm run build`

### What's the expected result?

Do not perform copying of the public directory if the `vite.build.copyPublicDir` option is set to false.

I checked with `npm create vite@latest` just to be sure, and vite itself works fine, so I don't think it is a problem on the vite side.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rktyt** [comment]
I understand the reason.

> I don't think Astro has to allow every Vite options to work, and I personally incline that if you require this specific behaviour for your build flow, you should workaround it yourself.

I agree, but I would like the documentation to clearly state which vite options are unavailable.

**Comment by ascorbic** [comment]
I'm going to close this because it's working as expected. You might want to open a docs PR or issue if you want to have more details about supported Vite options.
