### ISSUE TITLE
npm create astro@latest doesn't work. Get sh: 1: astro: not found

### ISSUE THREAD

**Issue by technologyconsulting** [withastro/astro#12241]
### Astro Info

```block
astro info

Astro                    v4.16.3
Node                     v22.5.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

After `npm create astro@latest` i'm told to run `npm run dev`. This in tern returns `sh: 1: astro: not found`. To FIX, I need to run `npm install astro`?

### What's the expected result?

For the webserver to start in dev mode.

### Link to Minimal Reproducible Example

https://I-cant-reproduce-this-using-astro.new

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Did you install dependencies during the step where it asks if you want to install dependencies?

**Comment by technologyconsulting** [comment]
I did yes. Admittedly, I've only attempted the installation twice but it has happened both times.
