### ISSUE TITLE
Import a local stylesheet - Don't work as expected

### ISSUE THREAD

**Issue by technologyconsulting** [withastro/astro#12247]
### Astro Info

```block
astro info

Astro                    v4.16.3
Node                     v22.5.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I've had to rewrite this about 20 times as and when I 'thought' I had found the issue! 

I initially started writing my css in the `<style></style>` tags for each page but soon got tired of scrolling up and down the page. Yes, I know I could have opened up the file again and split right ;-)

So I decided to take advantage of the import a local stylesheet as described in [Astro Docs](https://docs.astro.build/en/guides/styling/#import-a-local-stylesheet).

But as soon as I did this all my styles stopped applying. Then by accident, after many hours of scratching my and trying all sorts of stuff. I realised that if I made a change in the local css file it would brake and I would have to perform a save on one of the .astro files even if nothing had change there and then save the local css file again before the styles would work???

What's that all about! This is on a fresh astro project without me changing any of the config files or internals of astro.

1. Create a new blank project (yes, the npm i bug is still here!?)
2. Add a local .css file and import it.
3. Add something basic like html {color: red;}
4. Test
5. Then add something extra like a basic reset * {box-sizing: border-box;}, save and boom the styles don't work.

And I also get this in the console: Unsupported file type /src/pages/global.css found. Prefix filename with an underscore (`_`) to ignore.

### What's the expected result?

I can use an imported css file without having to save multiple files before the styles work.

### Link to Minimal Reproducible Example

https://

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by technologyconsulting** [comment]
And now you're forcing me to create a github repo just to prove something out of the box isn't working. Poor support model if you ask me. Asking someone to reproduce an issue should only be done if you don't have the means to reproduce it yourself. And as i've described, i'm literally running `npm create astro@latest` and trying to import a .css file using the `import './global.css` method in the official docs.

**Comment by technologyconsulting** [comment]
https://github.com/technologyconsulting/testing-css-02

**Comment by ematipico** [comment]
> Asking someone to reproduce an issue should only be done if you don't have the means to reproduce it yourself

We see it differently here. We think that if a user doesn't want to create a reproduction, it means that the bug isn't important enough to them. 

The user spends energies to isolate the issue in a predictable manner, and we debug and fix the issue. It's a fair trade-off.

____

Thank you for providing a reproduction, we'll look into it.

**Comment by technologyconsulting** [comment]
I completely disagree, and I say that having 25 + year supporting global infrastructures.

Whilst I appreciate the effort in providing the product Astro for free. A simple out of the box issue shouldn't need a the user to reproduce the issue.

Since using Astro, first time over the last couple of days, I've experienced two issues out of the box preventing me from using the product without having to spend time researching, troubleshooting and WASTING time. Not a great first introduction to Astro.

1st issue, needing to run an extra npm install after npm create astri@latest.

2nd issue, basic import of a. css file.

These issues shouldn't be the experience out of the box and certainly aren't reflected in the official docs.

Imagine buying a car and filling it with the documented fuel only to find out it now won't start!

**Comment by matthewp** [comment]
@technologyconsulting This is not the place to state your disagreement to our policies. As you said, this is a free product, and as such you are not entitled to any support. We do appreciate bug reports to help improve the product. If you'd like to continue please answer @mingjunlu question. Keep in mind they are an unpaid volunteer and we'll enforce that they (and everyone who helps in these threads) are treated with kindness.

**Comment by technologyconsulting** [comment]
Wow, Matthew Phillips, your arrogance is outstanding. I've not been unkind in any fashion and how am I instantly supposed to know that someone is annoyed unpaid volunteer?

I'm clearly stateing that the product doesn't work out of the box. I've done nothing outside of the documention and the product falls over immediately.

I'm not entitled to support. Where is the pride, honour in not supporting your product on such a basic level. You clearly don't care enough.
