### ISSUE TITLE
Specifying `config.outDir` results in broken directory structure

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#12248]
### Astro Info

```block
Astro                    v4.16.6
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

<img width="470" alt="{21B6A5ED-A60B-4500-A2BD-4632FD5A3801}" src="https://github.com/user-attachments/assets/e08cd142-1b58-4e79-92d6-879dcd5a2cc9">

Build artifacts are written into a folder named "dist" within a folder named the same as the custom `outDir`, instead of directly into the `outDir`.

### What's the expected result?

Only one dist folder is created.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-etpyme?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Closing as it's fixed in `next`
