### ISSUE TITLE
`addIntegration` not working in Starlight Plugin

### ISSUE THREAD

**Issue by trueberryless** [withastro/astro#12253]
### Astro Info

```block
Astro                    v4.16.6
Node                     v20.8.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

only tested Arc

### Describe the Bug

When running `pnpm dev` in `/docs` folder, vite fails to resolve the dependency, which should be injected by the [`addIntegration`](https://starlight.astro.build/reference/plugins/#addintegration) hook from [Starlight](https://starlight.astro.build/). Try yourself with this [Stackblitz](https://stackblitz.com/github/trueberryless/starlight-plugin-add-integration-test) example.

![image](https://github.com/user-attachments/assets/ec0993a2-18d8-4bd1-8154-406f559aca75)

This leads to the Starlight page which uses the plugin can't find the `@astrojs/react/server.js` file.

![image](https://github.com/user-attachments/assets/a6c51361-1191-433f-a7fa-1145f66b1f3d)

### What's the expected result?

The `addIntegration` hook should inject the dependency to the consumer (the Starlight page using the plugin), so the user doesnt have to add it manually and the config is right.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/trueberryless/starlight-plugin-add-integration-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@trueberryless 

I believe you should mark the dependencies of `starlight-plugin-add-integration-test-docs` as `peerDependencies`. Then, `docs` project should **install** them as a direct `dependencies`.

I did that and your project works correctly.

You can use [`peerDependenciesMeta`](https://pnpm.io/package_json#peerdependenciesmeta) to mark them as optional. 

Further tip: you should load `@astrojs/react` dynamically: 

```js
        if (!isReactLoaded) {
          const react = await import('@astrojs/react');
          addIntegration(react.default());
        }
```

**Comment by trueberryless** [comment]
Okay, thank you very much. As I mentioned in the Discord #starlight channel, there is still the possibility that I'm just stupid. As it turns out, I was right 🤣🤣🤣

Pls keep the issue open nonetheless, until I try it out. I'll do that ASAP...

However, I'm in good spirits if you say it works correctly! 😊

One thing we could improve though, are the Starlight docs if you ask me cause maybe there are other people who don't know that they need to add it to the peerDependencies...

**Comment by trueberryless** [comment]
Imho I would

1. add a section for adding packages to peerDependencies 
2. change the code with your nice dynamic loading feature

https://starlight.astro.build/reference/plugins/#addintegration

**Comment by trueberryless** [comment]
One final question: What does the `.default()` function do?

**Comment by ematipico** [comment]
> One final question: What does the .default() function?

It's the parallel of the following code, which automatically imports the function that is exported using the grammar `export default`

```js
import react from "@astrojs/react"
```

However, the dynamic `import()` is a bit "dumber" and needs more babysitting, meaning that you have to call the `default` function that was exported.

**Comment by ematipico** [comment]
> One thing we could improve though, are the Starlight docs if you ask me cause maybe there are other people who don't know that they need to add it to the peerDependencies...

You could bring this up in the Starlight channel, I am sure they are more than welcome to review the docs based on your use case.

**Comment by trueberryless** [comment]
> I believe you should mark the dependencies of `starlight-plugin-add-integration-test-docs` as `peerDependencies`. Then, `docs` project should **install** them as a direct `dependencies`.
> 
> I did that and your project works correctly.

@ematipico 

Okay, I'm currently trying to get it to run but it doesnt work for me. Do I need to mark the dependencies of `starlight-plugin-add-integration-test-docs` as `peerDependencies` or the dependencies of starlight-plugin-add-integration-test` as `peerDependencies`. Because the second option makes more sense to me, but you described the first one...

Nonetheless it doesnt work with either option...

**Comment by ematipico** [comment]
Here's a fork of your initial stackblitz you can use as example: https://stackblitz.com/edit/github-gr9wpu?file=packages%2Fstarlight-plugin-add-integration-test%2Fpackage.json,docs%2Fpackage.json

I am going to close this issue now. If you require more support, I suggest to use our Discord server.
