### ISSUE TITLE
gifs converted to webp don't play well in Safari

### ISSUE THREAD

**Issue by xavdid** [withastro/astro#12257]
### Astro Info

```block
﻿﻿﻿Astro                    v4.16.0
Node                     v20.17.0
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/preact
                         @astrojs/sitemap
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

Safari

### Describe the Bug

I've got a gif on my static site. During build, it's turned into a .webp file. While it plays great on Firefox and Chrome, it chugs on Safari (both macOS and iOS). It's partway down on https://david.reviews/articles/beast-breaker-review/ 

The gif itself is at https://david.reviews/_astro/strike.nWL5HkJR_7MdGU.webp, though that url might change when the site redeploys.

It's a big gif (~12MB) and I'm having trouble uploading (including to stackblitz, which doesn't accept files that big). You can download the full thing here: https://www.dropbox.com/scl/fi/d69to3oz5fpd0oqhqp4vx/strike.gif?rlkey=j81ywu5cw84n5xw7w3khc7bza&st=g8z3uzg8&dl=0

It's also linked in my website's repo below.

### What's the expected result?

The gif plays smoothly on all platforms

### Link to Minimal Reproducible Example

https://github.com/xavdid/david.reviews/blob/main/src/content/articles/beast-breaker-review.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
I don't think this is an Astro issue. It sound like a bug in Safari's handling of animated webp. You will get better results if you convert it to a video instead. e.g. using ezgif to convert to mp4 cut the size by 80%: https://ezgif.com/webp-to-mp4?url=https://david.reviews/_astro/strike.nWL5HkJR_7MdGU.webp

I'm closing this as a third party issue.
