### ISSUE TITLE
No autorefresh from changes on node 23.0.0

### ISSUE THREAD

**Issue by danyadanch** [withastro/astro#12261]
### Astro Info

```block
Astro                    v4.16.6
Node                     v23.0.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I've installed empty template and tried to change any text inside default generated page. No autorefresh in browsers.

### What's the expected result?

When i change something it autoupdates in browser

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Is it only happening on node 23? I'd probably suggest reporting to node then since the version is still new and not always stable. Maybe it's related to chokidar since that's what's used for file watching.

**Comment by danyadanch** [comment]
@bluwy yeah, it's happening only on node 23

about bug - sure, i will investigate where it happens, issue for providing data about node support

**Comment by kitschpatrol** [comment]
I'm seeing this as well, refresh works in Node 22.9.0, breaks in 23.0.0.

No big deal since Node 23 is bleeding edge, but interesting nonetheless.

**Comment by ematipico** [comment]
We advise to **not** use Astro with Node.js v23, because we don't officially support it. You can check this page https://docs.astro.build/en/upgrade-astro/#nodejs-support-and-upgrade-policies
