### ISSUE TITLE
Assets in public failing to resolve during dev with Node 23

### ISSUE THREAD

**Issue by ssalbdivad** [withastro/astro#12260]
### Astro Info

```block
Astro                    v4.16.6
Node                     v23.0.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
                         @astrojs/react
```

### Describe the Bug

After a recent upgrade, my references to assets in public have been failing to resolve in dev:

```
15:49:10 [WARN] [router] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/copy.svg`.

Possible dynamic routes being matched: ../../node_modules/.pnpm/@astrojs+starlight@0.28.3_astro@4.16.5_@types+node@22.7.5_rollup@4.24.0_typescript@5.7.0-beta_/node_modules/@astrojs/starlight/routes/static/index.astro.
15:49:10 [404] /copy.svg 14ms
```

Those assets are also broken when rendered in the app itself.

I'm currently on the latest astro (4.16.5) and @astrojs/starlight (0.28.3).

When run from dist or in prod, the path resolves correctly.

A minimal repro from @kitschpatrol:

```bash
mkdir public-test
cd public-test

pnpm create astro@latest . --yes

pnpm run dev

curl -s -o /dev/null -w "%{http_code}" http://localhost:4321/favicon.svg
```

@kitschpatrol Found the following workaround:

```js
import { defineConfig } from "astro/config";

export default defineConfig({
  vite: {
    publicDir: "public",
  },
});
```

### What's the expected result?

Assets are rendered normally without a warning.

### Link to Minimal Reproducible Example

Didn't repro when I tried in StackBlitz, instructions above

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kitschpatrol** [comment]
Thanks ssalbdivad!

I think this might have something to do with the trailing slash Astro is using in the absolute path to the public folder...

Running `astro dev --verbose` (without any modifications to the Astro config file) shows that Astro is setting the following absolute path (obviously unique to my machine):

```
vite:config     publicDir: '/Users/mika/Desktop/astro-asset-test/public/',
```

With this config, `http://localhost:4321/favicon.svg` 404s.

If I drop the trailing slash in an Astro config Vite override:

```ts
import { defineConfig } from "astro/config";

export default defineConfig({
  vite: {
    publicDir: "/Users/mika/Desktop/astro-asset-test/public",
  },
});
```

Then `http://localhost:4321/favicon.svg` resolves correctly.

**Comment by kitschpatrol** [comment]
Quick update:

I failed to notice / mention that I was running on Node 23... (it auto-updated and I wasn't paying attention).

For me at least, non-resolution of `/public` assets in `astro preview` and `astro dev` with a default `astro.config` are **only** happening with Node 23. Rolling back and running against Node 22.9.0 works fine.

**Comment by ematipico** [comment]
We recommend not using a non-LTS version of Node.js with Astro. We don't officially support them: https://docs.astro.build/en/upgrade-astro/#support

**Comment by ssalbdivad** [comment]
@ematipico It seems like a lot of Astro's users have already locally upgraded to Node 23 and that one of two things is true:

- This is a bug in Node 23 that should be tracked and fixed in [their repo](https://github.com/nodejs/node)

- This is expected behavior in Node 23, and given that Astro will eventually have to support it anyways, resolving it without waiting for it to be published as LTS could save a lot of headaches

**Comment by demmm** [comment]
Just an FYI, I had the same issues as described in this bug report (with nodejs 23.0.0), released version today of 23.1.0 solved all problems here, so, imo, not an astro issue, but issues with first 23 release of nodejs.

**Comment by ssalbdivad** [comment]
@demmm Cool, safe to say this is addressed then.

Still probably worth keeping in mind for the Astro team when triaging issues related to the latest node versions, though.

**Comment by bluwy** [comment]
Astro doesn't necessarily guarantee to work with odd versions of node. We've documented it here: https://docs.astro.build/en/upgrade-astro/#nodejs-support-and-upgrade-policies

**Comment by ssalbdivad** [comment]
@bluwy I get that, I'm just pointing out that generally, if a new node release doesn't work, it should boil down to a bug in Node or a change that will eventually be reflected in an LTS release, so being somewhat proactive about trying to identify which is this case could be helpful for planning.
