### ISSUE TITLE
Chinese routing display error in 5.0.0-beta.5 version

### ISSUE THREAD

**Issue by JinMokai** [withastro/astro#12262]
### Astro Info

```block
Astro                    v5.0.0-beta.5
Node                     v20.15.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/tailwind
                         pagefind
                         @playform/compress
                         astro-robots-txt
                         @astrojs/sitemap
                         @astrojs/vue
                         astro-compressor
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

When I upgraded the version from 5.0.0-beta.2 to the latest 5.0.0-beta.5, I can't open the link to my blog in the development environment, but production can open the

### What's the expected result?

Ability to open blogs in the development environment

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jxnmpi?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JinMokai** [comment]
I'm sorry I didn't pay attention to update the change document, when I try to upgrade the version to 5.0.0-beta.4, the problem still occurs, it may be a decoding problem, but I've already added decodeURI to the local project as requested.
but it's still not parsing
https://github.com/withastro/astro/blob/refs/heads/next/packages/astro/CHANGELOG.md#changed-params-arent-decoded-anymore

**Comment by ematipico** [comment]
@JinMokai you said you already tried to use `decodeURI`. Can you please update the reproduction accordingly?

**Comment by JinMokai** [comment]
@ematipico hello I updated the example link
https://stackblitz.com/edit/github-jxnmpi?file=src%2Fpages%2Findex.astro

**Comment by Uninen** [comment]
I'm running into this same issue. Urls without special characters work fine, urls with them dont, decoded or not.
