### ISSUE TITLE
Incorrect index file copied when middleware used

### ISSUE THREAD

**Issue by Sporiff** [withastro/astro#12269]
### Astro Info

```block
Astro                    v4.16.6
Node                     v22.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             auto-import
                         @astrojs/react
                         astro-expressive-code
                         @astrojs/mdx
                         @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/markdoc
```

### Describe the Bug

I have the following i18n configuration set using SSG mode:

```js
  i18n: {
    defaultLocale: "en",
    locales: ["en", "ja", "ko", "zh"],
    routing: {
      prefixDefaultLocale: true,
      fallbackType: "rewrite",
      redirectToDefaultLocale: false,
    },
    fallback: {
      ja: "en",
      ko: "en",
      zh: "en"
    },
  },
```

To ensure people are directed to the correct locale, I have a small client-side script in my `pages/index.astro` that checks the user's preferred browser locale and pushes them to the right page accordingly.

Recently I made a change to my `middleware.ts` file. Since then, I noticed that instead of my custom `pages/index.astro` being copied to `dist`, the default `redirectToDefaultLocale: true` index file is appearing.

```html
<!doctype html><title>Redirecting to: https://dev.adjust.com/en</title><meta http-equiv="refresh" content="2;url=https://dev.adjust.com/en"><meta name="robots" content="noindex"><link rel="canonical" href="https://dev.adjust.com/en"><body>	<a href="https://dev.adjust.com/en">Redirecting from <code>/</code> to <code>https://dev.adjust.com/en</code></a></body>
```

### What's the expected result?

My custom `index.astro` should be copied to the `index.html` location in my `dist` folder during build when I have configured `redirectToDefaultLocale: false`. Under no circumstances should a different file be put there.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/index-copying-i18n?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by apatel369** [comment]
@Sporiff  The custom redirect file is being generated due to the following logic in your `noLocale` middleware:

```
  if (!languages.includes(pathLang)) {
       let newUrl = context.url.pathname.split('/');
     newUrl.splice(1, 1, 'en');
     return context.redirect(newUrl.join('/'));
  }
```

When I commented out the above code, it generated the index.html based on your custom `pages/index.astro`.

**Comment by apatel369** [comment]
@ematipico If any fix is needed in Astro, I am willing to submit PR. Please advise about expected behaviour in this case.

**Comment by ematipico** [comment]
Great analysis @apatel369 

This isn't a bug, since the i18n middleware isn't doing any redirect.
