### ISSUE TITLE
Warning about `astro:env` support is always logged if an adapter is added

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#12276]
### Astro Info

```block
Astro                    v4.16.6
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

Since all adapters mark the support as `experimental`, a warning is logged everytime an astro command is run. This does not take into account whether the feature is being used in the first place, in which case it is just adding noise to the terminal.

### What's the expected result?

The warning is only logged if the feature is used.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u1ggs8?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
This check is probably wrong https://github.com/withastro/astro/blob/main/packages/astro/src/integrations/features-validation.ts#L97
