### ISSUE TITLE
imported styles has added to page 5 times

### ISSUE THREAD

**Issue by AntonOshurek** [withastro/astro#12274]
### Astro Info

```block
➜  oshurek.dev git:(task-optimization) astro info
zsh: command not found: astro
```

### If this issue only occurs in one browser, which browser is a problem?

on all browsers

### Describe the Bug

when i import style as a import '../styles/variables/variables.scss'; this styles are imported to page 5 times. It happens with all styles that i imported to components. You will be able to find this problem in my blog page. oshurek.dev. just see how many times styles are imported :root variables.

repo for this project https://github.com/AntonOshurek/oshurek.dev

### What's the expected result?

all imported styles will added to style bundle 1 times

### Link to Minimal Reproducible Example

oshurek.dev

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Can you please narrow down the issue into a single reproduction? Debugging user projects come with a lot of issues, instead it's best to provide a clean, **minimal** way to reproduce the issue

**Comment by AntonOshurek** [comment]
Problem was resolved. I just import my variables.scss file into some amount of another .scss style files and this caused that variables :root was imported so many times.
