### ISSUE TITLE
image endpoint not called in production if there is a dynamic param in root pages

### ISSUE THREAD

**Issue by ayZagen** [withastro/astro#12284]
### Astro Info

```block
Astro                    v5.0.0-beta.5
Node                     v22.10.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             include-app-config-import
                         @astrojs/markdoc
                         @astrojs/mdx
                         @astrojs/tailwind
                         @astrojs/vue
```

### Describe the Bug

![{760C404D-72F4-41AC-8AAB-74AB1B0F6903}](https://github.com/user-attachments/assets/494b725d-7e28-4346-99e3-386f239afe15)
With the above structure with `SSR` mode the `_image` endpoint generated by astro is never called. Instead it tries to render `[...slug].astro` file. 

### What's the expected result?

The static endpoints should take precedence over the dynamic pages. So, the `_image` endpoint should be called.

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by apatel369** [comment]
Please add a reproducible example.
