### ISSUE TITLE
ActionAPIContext

### ISSUE THREAD

**Issue by ohrrkan** [withastro/astro#12281]
### Astro Info

```block
Astro                    v4.16.5
Node                     v20.18.0
```

### If this issue only occurs in one browser, which browser is a problem?

Server

### Describe the Bug

There are some omissions in the definition of ActionAPIContext, but they are available in the context : https://github.com/withastro/astro/blob/e9e8080a8139f898dcfa3c030f5ddaa98413c160/packages/astro/src/actions/runtime/utils.ts#L13

### What's the expected result?

Remove the omitted elements from the context, not just from the definition. OR remove the omit.
By the way, I found this issue because I was searching for a way to call the action from an action context.
I would prefer you to simply remove the omitted elements from the definition, but I assume you had a reason for this omit in the first place. what was it? 

### Link to Minimal Reproducible Example

[code](https://stackblitz.com/edit/github-8h6bt9?file=src%2Factions%2Findex.ts)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
> Remove the omitted elements from the context, not just from the definition.

I am not sure what you mean. The omitted element **aren't** added: 

https://github.com/withastro/astro/blob/52d1b58f89969551f881bc95107b5caf19d70586/packages/astro/src/core/render-context.ts#L282-L316

**Comment by ohrrkan** [comment]
> > Remove the omitted elements from the context, not just from the definition.
> 
> I am not sure what you mean. The omitted element **aren't** added:
> 
> https://github.com/withastro/astro/blob/52d1b58f89969551f881bc95107b5caf19d70586/packages/astro/src/core/render-context.ts#L282-L316

that right but you assign it after : https://github.com/withastro/astro/blob/52d1b58f89969551f881bc95107b5caf19d70586/packages/astro/src/core/render-context.ts#L238

**Comment by ematipico** [comment]
But that's not ActionAPIContext. Please provide *some code* to help us understanding *what issue* you have

**Comment by ematipico** [comment]
I see now, thank you. I believe the bug is that we are passing the incorrect context to the handler.

**Comment by ohrrkan** [comment]
Yes, I think so too. It’s not using ActionAPIContext, but APIContext. However, it’s amazing to be able to call an action within an action because of that,I would love to know why the decision was made to remove that possibility.

**Comment by ematipico** [comment]
I don't have all the details, maybe the original RFC has something about it
