### ISSUE TITLE
Regression: astro.currentLocale always returns default locale in v4.15.8

### ISSUE THREAD

**Issue by layout-ch** [withastro/astro#12291]
### Astro Info

```block
Astro                    v4.16.7
Node                     v22.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             astro-icon
                         @sanity/astro
                         @astrojs/react
```

### Describe the Bug

In Astro v4.15.8, Astro.currentLocale always returns the default locale regardless of the current route's language. This worked correctly in v4.8.7.

Steps to reproduce:

1. Set up an Astro project with i18n routing
2. Configure multiple locales with a default locale
3. Create routes for different languages
4. Try to access Astro.currentLocale on non-default language routes

Expected behavior:

- Astro.currentLocale should return the current route's locale

Actual behavior:

- Astro.currentLocale always returns the default locale

### What's the expected result?

Astro.currentLocale should return the current route's locale

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dpuscher** [comment]
I had the same problem in 4.16.0, but it seems like it was fixed in 4.16.4 in this PR: https://github.com/withastro/astro/pull/12199
