### ISSUE TITLE
Cannot find module `.../zod-to-json-schema/...`

### ISSUE THREAD

**Issue by Rushmore75** [withastro/astro#12296]
### Astro Info

```block
npm run astro info

> ad-channels@0.0.1 astro
> astro info

Cannot find module '/home/bob/code/ad-channels/node_modules/zod-to-json-schema/dist/esm/parsers/branded' imported from /home/bob/code/ad-channels/node_modules/zod-to-json-schema/dist/esm/parsers/record.js
  Stack trace:
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at defaultResolve (node:internal/modules/esm/resolve:1148:11)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
```

### If this issue only occurs in one browser, which browser is a problem?

n/a

### Describe the Bug

Running (most) `npm run astro ...` commands fail with the above output; `npm run astro dev` `npm run astro build`. `npm run astro` outputs fine.
Here's version of everything:
| Product | Version| 
|-|-|
| astro | v4.16.7 |
| node | v21.7.3 |
| @astrojs/check | 0.9.4 |
| typescript | 5.6.3 |

- [x] `npm update` has been run

### What's the expected result?

Default cli operation

### Link to Minimal Reproducible Example

doesn't break in their environment

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nnisarggada** [comment]
Same issue

**Comment by delucis** [comment]
Just hit this with pnpm too locally. Pretty sure it’s a buggy latest release of `zod-to-json-schema`: https://github.com/StefanTerdell/zod-to-json-schema/issues/151

**Comment by Rushmore75** [comment]
Looks like it will be solved in this pull https://github.com/StefanTerdell/zod-to-json-schema/pull/152

**Comment by OctupusPrime** [comment]
Fix mine with pnpm overrides

```
  "pnpm": {
    "overrides": {
      "zod-to-json-schema": "3.23.3"
    }
  }
```

**Comment by StefanTerdell** [comment]
Woops! Should be fixed in 3.23.5.

**Comment by jamesli2021** [comment]
4..3..2..1. It's fixed!

**Comment by delucis** [comment]
Thanks for the quick fix @StefanTerdell!
