### ISSUE TITLE
FOUC in dev mode on loaded page

### ISSUE THREAD

**Issue by Serpentarius13** [withastro/astro#12295]
### Astro Info

```block
Astro                    v4.15.12
Node                     v22.10.0
System                   Linux (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             astro-expressive-code
                         @astrojs/mdx
                         @astrojs/tailwind
                         @astrojs/vue
                         pagefind
                         @astrojs/preact
                         astro-robots-txt
```

### Describe the Bug

When reloading page with big amount of content in dev mode, it flickers with FOUC for a second. I don't know if its a bug of just a limitation of Vite? It seems there's nothing I've done incorrectly though. Would my project's repo be sufficient as repro? Just run one script: ./startup.sh

### What's the expected result?

It would not flicker

### Link to Minimal Reproducible Example

https://github.com/Serpentarius13/personal-blog

Video:

[screen-capture (1).webm](https://github.com/user-attachments/assets/632f0150-f111-42ad-a6bc-bdb7db945cf7)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
We require minimal reproduction, to identify what's causing the issue

**Comment by Serpentarius13** [comment]
/

> We require minimal reproduction, to identify what's causing the issue

I couldn't reproduce it on a new repo as there's a lot of conditions and I don't have much time now.. But I figured how to fix it: I removed rendering of a lot of opengraph `<meta>` tags in dev mode and it fixed itself!
```ts {import.meta.env.PROD && <OpenGraph {...props} />}```
Can you please take a look at my repo? Maybe have an idea why this would happen? I've tried bloating head in repro, but flashes didn't occur there. Removing anything else didn't help - I tried to remove my theme script which is quite chunky, but it still happens.

**Comment by ematipico** [comment]
Unfortunately, I don't have the bandwidth to look after big projects :( I suggest you to reach out to our support squad on Discord, maybe they'll help you
