### ISSUE TITLE
MDX variable interpolation not working in Markdown link syntax

### ISSUE THREAD

**Issue by iCCPM** [withastro/astro#12309]
### Astro Info

```block
not Neccessary
```

### Describe the Bug

Description:
I am encountering an issue with variable interpolation in Markdown link syntax within MDX files. When I try to use a variable as the URL in a Markdown link, the variable is not properly resolved.

Steps to reproduce:
1. Define a variable in the MDX file, for example:
   ```mdx
   export const pdfUrl = pdfPath;
   ```

2. Use the variable in a Markdown link syntax:
   ```mdx
    [Click to download]({pdfUrl}) or [Click to download](`{pdfUrl}`)
   ```

Expected behavior:
The `pdfUrl` variable should be interpolated as the URL of the link, resulting in the following generated HTML:
```html
<a href="/path/to/pdf">Click to download</a>
```

Actual behavior:
The link is generated with the literal string `{pdfUrl}` as the URL, instead of the variable's value:
```html
<a href="{pdfUrl}">Click to download</a>
```

 

Additional context:
- I have tried using JSX syntax `<a href={pdfUrl}>Click to download</a>` and it works as expected.
- I have also tried assigning the variable to a constant and using it in the Markdown link syntax, but it still does not interpolate the value correctly.

I would appreciate any guidance or solution to properly interpolate variables in Markdown link syntax within MDX files.

Thank you for your assistance!

### What's the expected result?

The `pdfUrl` variable should be interpolated as the URL of the link, resulting in the following generated HTML:
```html
<a href="/path/to/pdf">Click to download</a>
```

### Link to Minimal Reproducible Example

https://xoriwpnrmwgithub-ibeo--4321--34c588ed.local-credentialless.webcontainer.io

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
1. This isn't an Astro issue, but a MDX issue. We don't own it.
2. You can't do that, it isn't how MDX grammar works. The interpolation is meant to work only inside the JSX part of a MDX file.
3. If you still feel strongly about this grammar/feature, you should propose it in the MDX repository/organization.
