### ISSUE TITLE
Server islands do not respond to i18n language changes

### ISSUE THREAD

**Issue by Amirhlotfi** [withastro/astro#12307]
### Astro Info

```block
Server islands don’t respond to i18n language changes, and astro.currentLanguage consistently returns the default locale. This issue doesn’t seem to occur in Astro pages or components.
```

### Describe the Bug

astro.currentLanguage in a Server island consistently returns the default locale

### What's the expected result?

astro.currentLanguage to return the correct locale.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/Amirhlotfi/astro-i18n-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Server islands are created using a particular route naming, so they are exempt from i18n checks.

However, can't you pass the current locale as a prop to the server island?

**Comment by Amirhlotfi** [comment]
Thank you for the response.
You're right, the correct `currentLocale` can be sent to the server island. But I guess this makes an unexpected inconsistency with astro.currentLanguage. It also becomes more of a hassle since all nested Astro component in a server island would need to take in `currentLocale` as a prop.

**Comment by ematipico** [comment]
It's definitely a hassle and a limitation. I'll have to think if there's a way to get that information from a server island.

I'll keep the issue open

**Comment by Amirhlotfi** [comment]
How about using using the `referer`-header that comes with the request to decide?
`Astro.request.headers.get("referer")`
