### ISSUE TITLE
`onRequest` middleware should be executed before parsing

### ISSUE THREAD

**Issue by rktyt** [withastro/astro#12318]
### Astro Info

```block
Astro                    v4.16.7
Node                     v20.15.0
System                   Linux (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

pages/news/[category]/index.astro
pages/news/search/index.astro

There are the above two page files, and there are redirects as below.

```typescript
// middleware.ts
import { defineMiddleware } from 'astro:middleware'

export const onRequest = defineMiddleware(async ({ url, redirect }, next) => {
  // old url to new url
  if (
    /^\/news\/[^/]+$/.test(url.pathname) &&
    !/^\/news\/(search|category1|category2)\/?$/.test(url.pathname)
  ) {
    const text = url.pathname.split('/').at(-1)
    if (text) {
      return redirect(
        '/news/search?' +
          new URLSearchParams({ q: decodeURIComponent(text) }),
        301,
      )
    }
  }
  return await next()
})
```

`/news/keyword1%2Fkeyword2` is not redirected to `/news/search?q=keyword1%2Fkeyword2`.
I receive the error Missing parameter: category

 It is similar to https://github.com/withastro/astro/issues/7962, but this is an issue with the onRequest processing timing.

### What's the expected result?

That redirects work correctly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7nbdqa?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rktyt** [comment]
I made it
https://stackblitz.com/edit/github-7nbdqa?file=astro.config.mjs

But I seems stackblitz not supported middleware.
Therefore, it is not possible to confirm the phenomenon.

**Comment by ematipico** [comment]
@rktyt 

The middleware works on stackblitz, if you don't see anything it is probably because the regex doesn't work.

**Comment by rktyt** [comment]
Sorry, there was an error in the middleware file name.

I wrote three links on the root page.
It's bug that the third link causes an error.
