### ISSUE TITLE
astro:env can't find secrets in middleware

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#12324]
### Astro Info

```block
N/A
```

### Describe the Bug

When using a secret inside a middleware, it now fails

1. `npm run build`
2. `npm run preview`
3. visit root

### What's the expected result?

Should still work

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8b8hjn

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by JLarky** [comment]
seeing the same issue in astro 4.16.6-4.16.8

I even tried to remove middleware/index.ts and it didn't help me, still fails here:

<img width="654" alt="image" src="https://github.com/user-attachments/assets/071b5f93-89ca-4a73-bd24-6fea5473aca5">

<img width="990" alt="image" src="https://github.com/user-attachments/assets/fd284c00-c070-469e-8c89-3d4e57edd41d">

**Comment by florian-lefebvre** [comment]
I don't know for sure in what version it was introduced but in the meantime, downgrade a few patches until it works. We are working on a fix but it's not easy so I have no ETA atm

**Comment by JLarky** [comment]
it works in 4.16.5

BTWtested with `astro@experimental--env-middleware` and seeing exactly the same error like I saw when I removed middleware

**Comment by florian-lefebvre** [comment]
Yeah, I tried it as well and I was very disappointed to see my attempt did not work at all :/. @ematipico is probably going to pick it up. Thanks for confirming the version where it works!

**Comment by JLarky** [comment]
can confirm 4.16.9 works

**Comment by florian-lefebvre** [comment]
Yeah we reverted, we're going to do another attempt this/next week

**Comment by florian-lefebvre** [comment]
@JLarky what adapter were you using?

**Comment by hckhanh** [comment]
@JLarky Did you try it with Astro v5. I intend to upgrade the the latest version.

**Comment by hckhanh** [comment]
I confirm it can work with Astro v5.0.9
