### ISSUE TITLE
SyntaxError when using define:vars and import in the client script

### ISSUE THREAD

**Issue by kunxi** [withastro/astro#12343]
### Astro Info

```block
﻿﻿Astro                    v4.16.7
Node                     v22.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
                         astro-jupyter
```

### Describe the Bug

I try to pass the server-side variables to the client side, and according to the document, it may look like:

```
<script define:vars={{ message }}>
import * as d3 form "d3"
</script>
```
I received a syntax error: `Uncaught SyntaxError: import declarations may only appear at top level of a module`. It makes sense as `message` is injected as the outcome of an anonymous function to the global namespace. It was executed before the imports. I think the current implementation make imports and passing server-side variable mutual exclusive. 

### What's the expected result?

We should be able to import and define vars, and no syntax errors.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dwejhk-1zxka4?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @kunxi👋🏼, yes, you are right: `define:vars` and Astro's automatic handling of script that turns them into external module scripts [are mutual exclusive](https://docs.astro.build/en/reference/directives-reference/#definevars).

Please see the following section on [how to pass frontmatter variables to _module_ scripts](https://docs.astro.build/en/guides/client-side-scripts/#pass-frontmatter-variables-to-scripts).
