### ISSUE TITLE
Cannot find module 'astro:content' or its corresponding type declarations.

### ISSUE THREAD

**Issue by dschuessler** [withastro/astro#12357]
### Astro Info

```block
Astro                    v4.16.8
Node                     v22.6.0
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Importing from `astro:content` yields a type error in `src/content/config.ts`. It reads:

```
Cannot find module 'astro:content' or its corresponding type declarations.ts(2307)
```

I have tried:

* `bunx astro sync`
* `bunx --bun astro sync`
* `npx astro sync` (with node.js 20)
* Restarting the TypeScript Language Server
* Restarting the VSCode Extension Host
* Restarting VSCode

### What's the expected result?

There is no type error.

### Link to Minimal Reproducible Example

https://github.com/dschuessler/astro-content-type-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
You don't have a tsconfig.json file in the root of your project. Can you try adding one extending the strict preset?

**Comment by dschuessler** [comment]
Yes, that fixes it. I don't know how the `tsconfig.json` went missing.

Thank you!
