### ISSUE TITLE
Astro.currentLocale not working correctly in root 404.astro with i18n

### ISSUE THREAD

**Issue by otra-ch** [withastro/astro#12356]
### Astro Info

```block
Astro                    v4.16.8
Node                     v22.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             astro-icon
                         @sanity/astro
                         @astrojs/react
```

### Describe the Bug

When using a 404.astro page at the root level (pages/404.astro), Astro.currentLocale always returns the defaultLocale even when visiting a different locale URL path.

Example:
- URL: /de/nonexistent-page
- Astro.currentLocale returns 'fr' (defaultLocale) instead of 'de'

Console log shows:
{ currentLocale: 'fr', url: '/de/fasf', params: {} }

This works correctly in some projects but not others with similar configurations.

My config:
```astro.config.mjs
i18n: {
   defaultLocale: "fr",
   locales: ["fr", "de"],
   routing: {
      prefixDefaultLocale: true,
      redirectToDefaultLocale: false,
   }
}
```
### What's the expected result?

Astro.currentLocale should return 'de' when visiting /de/* paths 

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by apatel369** [comment]
@otra-ch Please add a reproducible example.

**Comment by otra-ch** [comment]
Sure here you go : https://stackblitz.com/edit/github-e8pwbg?file=src%2Fpages%2Ffr%2Fabout.astro

**Comment by ematipico** [comment]
I don't think your expectations are correct, or they are perhaps too broad.

First, I think the expectation should be only for pages that don't exist. The reason why I say so is that because there's also a fallback system involved, if opted in. And if so, the page that doesn't exist will use the fallback, and the current locale should be the locale if the rewritten route

**Comment by otra-ch** [comment]
Hey @ematipico, my use case is specifically about 404 pages without any fallback configuration. When a user visits /de/non-existent-page, I expect Astro.currentLocale to reflect the language in the URL ('de'), since that's what the user explicitly requested, even if the page doesn't exist.

**Comment by ematipico** [comment]
I'm talking about i18n fallback: https://docs.astro.build/en/guides/internationalization/#fallback

**Comment by stefanprobst** [comment]
this was working for me in 4.15.12 but broke with 4.16.0

**Comment by apatel369** [comment]
@ematipico My PR specifically handles 404 pages without any fallback configuration.
