### ISSUE TITLE
Could we dynamic load contents in need?

### ISSUE THREAD

**Issue by sgalcheung** [withastro/astro#12386]
### Astro Info

```block
Astro                    v5.0.0-beta.2
Node                     v18.20.3
System                   macOS (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/starlight
                         @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

I want to update in real-time when I use Content Load API, and I found the docs about the `Collection`.
> [When not to create a collection](https://5-0-0-beta.docs.astro.build/en/guides/content-collections/#when-not-to-create-a-collection)
> You are using APIs that need to be updated in real time. Content collections are only updated at build time, so if you need live data you should consider [on-demand rendering](https://5-0-0-beta.docs.astro.build/en/guides/on-demand-rendering/).

Could we implement it using on-demand rendering?

### What's the expected result?

When I use SSR render and Starlight on the render model, the collection still does not load in real-time.

### Link to Minimal Reproducible Example

https://github.com/sgalcheung/starlight-squidex/tree/sdk

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Please, use Discord for these kinds of questions.

**Comment by sgalcheung** [comment]
I moved to Discord, https://discord.com/channels/830184174198718474/1303620097335758868

**Comment by sgalcheung** [comment]
I read this, it supports dynamic through the webhook refresh content, read more [](https://github.com/withastro/roadmap/blob/content-layer/proposals/0050-content-layer.md#integration-support)
