### ISSUE TITLE
Status code in response set by middleware is not respected

### ISSUE THREAD

**Issue by Tobikblom** [withastro/astro#12391]
### Astro Info

```block
Astro                    v4.16.10
Node                     v20.10.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

Given the following middleware, every request should respond with a Status Code 200 OK:
```js
// middleware.ts
import { defineMiddleware, sequence } from "astro:middleware";

const ok = defineMiddleware(async (context, next) => {
  return new Response("OK", { status: 200 });
});


export const onRequest = sequence(ok);
```
However, sending a request to a pathname that is not matched by anything in the pages directory, will respond with a Status Code 404 Not Found, i.e., the response set by the middleware is not respected.

### What's the expected result?

The Status Code set in the response by the middleware should be respected.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-bzdjbw?file=src%2Fmiddleware.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by joshpensky** [comment]
We're having the same issue here — we use middleware to rewrite/forward requests from a path `/www` to our app

The request itself has a `200 OK` response, but middleware always returns a 404 no matter what
