### ISSUE TITLE
Astro.url resolve to `localhost:4321` or `127.0.0.1:4321` when building with vercel

### ISSUE THREAD

**Issue by bryanltobing** [withastro/astro#12399]
### Astro Info

```block
Astro                    v4.16.7
Node                     v22.8.0
System                   macOS (arm64)
Package Manager          npm
Integrations             @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

chrome

### Describe the Bug

I'm building a static API route that returns some JSON in `pages/spotify/top-artists.json.ts`.

When I try to fetch it in an Astro file, it throws an error during the Vercel deployment because it doesn't resolve to the actual URL but instead points to the localhost URL.

![image](https://github.com/user-attachments/assets/7a059d50-b905-4b68-a46e-8515295db48e)

There’s no issue in local development since it correctly uses `localhost:4321`.

```javascript
const url = new URL("/spotify/top-artists.json", Astro.url);
const response = await (await fetch(url)).json();
```

i'm following this doc https://docs.astro.build/en/guides/data-fetching/#fetch-in-astro

I tried using relative path

https://stackblitz.com/edit/github-ad4juv?file=src%2Fpages%2Findex.astro

but i got `failed to parse url` error instead

![image](https://github.com/user-attachments/assets/fdbd923a-288d-4d15-845e-7eae356a8b42)

### What's the expected result?

The expected result is for it to resolve to the actual URL where it's deployed, instead of `localhost`.

I tried logging it in my browser:

https://bryanprim-git-a34a5f-bryan-primus-exaudi-lumbantobings-projects.vercel.app/interest

but it still shows `localhost`.

### Link to Minimal Reproducible Example

https://github.com/bryanltobing/astro-static-api-routes-repro

specific commit causing the issue: [feat: add api routes and fetch data from api routes from astro file](https://github.com/bryanltobing/astro-static-api-routes-repro/commit/09d553759793ae65ffa85ec4fb4e841ede72901b)

How to reproduce:

- Clone repo
- Run or build locally -> this should be fine without no error -> turns out build was fine because dev server is running and build was pointing to localhost:4321, when i turned off dev server, local build `yarn build` is also error
- Try to deploy on vercel -> build error since astro.url resolve to localhost

### Participation

- [X] I am willing to submit a pull request for this issue.

i temporarily work around this by specifying 

`PUBLIC_ORIGIN=MY_DOMAIN_ORIGIN` in my `env`

but doesn't seem like an ideal approach since i'm deploying to more than one domain

**Comment by bryanltobing** [comment]
i temporarily work around this by specifying 

`PUBLIC_ORIGIN=MY_DOMAIN_ORIGIN` in my `env`

but doesn't seem like an ideal approach since i'm deploying to more than one domain

**Comment by ematipico** [comment]
That's not how you would solve the problem, at least not with this setup. Astro is behaving correctly in **this setup**, so you must adjust your setup. 

Looking at the minimal reproduction, it seems that you require the files **at compile time**, which means that during the build, **you don't need any server**, however you're trying to retrieve these files using *an endpoint*, and they require a server. 

If you require to retrieve the files via that endpoint, **for this particular case**, then import the endpoint itself:

```astro
---
import { GET } from "../data.json.ts";

const response = await GET();
const json = await response.json();
---
```

**Comment by bryanltobing** [comment]
In this case, I probably don’t need an endpoint at all. I was concerned about using an API key `CLIENT_SECRET` and didn’t want it exposed. However, since no client or island code requires that data, it should be safe just doing something like this in an astro file right?

```astro
---
// pages/interest.astro
const basic = Buffer.from(
  `${import.meta.env.SPOTIFY_CLIENT_ID}:${  // <- from .env
    import.meta.env.SPOTIFY_CLIENT_SECRET // <- from .env
  }`
).toString("base64");

const getAccessToken = async () => {
  const response = await fetch(API_TOKEN_URL, {
    method: "POST",
    headers: {
      Authorization: `Basic ${basic}`,
    },
    body: querystring.stringify({
      refresh_token: import.meta.env.SPOTIFY_REFRESH_TOKEN, // <- from .env
    }),
  });

  return response.json();
};

const getTopArtists = async () => {
  const { access_token } = await getAccessToken();

  const response = await fetch(TOP_ARTISTS_URL, {
    headers: {
      Authorization: `Bearer ${access_token}`,
    },
  });

  return response.json();
};

const topArtistsResponse: GetTopArtistsResponse = await getTopArtists()
---

<pre>{JSON.stringify(topArtistsResponse)}</pre>
```
