### ISSUE TITLE
Catch-all routes duplicates custom headers

### ISSUE THREAD

**Issue by zanettin** [withastro/astro#12419]
### Astro Info

```block
Astro                    v4.16.10
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

-

### Describe the Bug

Setting a custom header (`X-Debug` in the attached repro), the values are duplicated when returning a response on the catch-all (`[...slug].astro`) route.

**Reproduction**
- run `npm run build && npm run preview`
- open dev tools -> network
- go to any URI but not home
- checking `X-Debug` header which has the value `1234, 1234`

### What's the expected result?

`X-Debug` header should have value `1234` also on catch-all routes

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/focused-cartwright-hjrw7n?workspaceId=858df2c7-b16d-4601-b40c-e4a00d04da47

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I can't replicate, can you please at least tell us which browser you're using?

Here's what I get on firefox (raw headers)

```
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Origin: *
content-type: text/plain;charset=UTF-8
x-debug: 1234
Date: Mon, 18 Nov 2024 14:21:25 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```

**Comment by zanettin** [comment]
Thank you very much @ematipico for having a look at this issue and sorry if my description was not clear. i've recorded a short video to demonstrate the point i've tried to mention above. important is, that i am talking about the built version of the app and not the dev mode. since the headers are set on SSR it doesn't have an impact which browser is used. if i can give you further info, please let me know 🙏 

https://github.com/user-attachments/assets/47e44563-98b6-421c-a9ef-c75cc6301ccd
