### ISSUE TITLE
unable to do external rewrites

### ISSUE THREAD

**Issue by litcodeur** [withastro/astro#12413]
### Astro Info

```block
Astro                    v4.16.5
Node                     v20.18.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I'm trying to do a rewrite to an external url with astro but it seems to just return the index page. I tried doing `return Astro.rewrite("http://localhost:5173/login");` on login page, also tried to do it with middleware but when I visit `/login` it returns the index.astro page.

### What's the expected result?

it should rewrite the output correctly

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5cjane?file=src%2Fpages%2Flogin.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Astro rewrites aren't designed to rewrite external sources
