### ISSUE TITLE
Cannot use separate tsconfig.json in the src/content folder

### ISSUE THREAD

**Issue by NullVoxPopuli** [withastro/astro#12412]
### Astro Info

```block
❯ pnpm astro info

> warp-drive-tutorial@0.0.1 astro /home/nvp/Development/NullVoxPopuli/warp-drive-tutorial
> astro "info"

Astro                    v4.16.10
Node                     v22.10.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @tutorialkit/astro
```

### If this issue only occurs in one browser, which browser is a problem?

n/a

### Describe the Bug

Two issues, mainly
- I'm not sure how to have `astro check` ignore my src/content stuff
- astro build errors when a tsconfig.json is present in src/content

    Here is a link to a discussion in discord for added context and troubleshooting: 
    https://discord.com/channels/830184174198718474/1304493514532458597/1304493514532458597
    
    The Error text:
    ```
    12:07:23 [ERROR] [MixedContentDataCollectionError] tutorial contains a mix of content and data entries. All entries must be of the same type.
      Hint:
        Store data entries in a new collection separate from your content collection.
      Error reference:
        https://docs.astro.build/en/reference/errors/mixed-content-data-collection-error/
      Stack trace:
    ```

### What's the expected result?

I should be allowed to use nested tsconfig.jsons so that when writing tutorial content, I can have the appropriate intellisense to help me write content more effectively.

### Link to Minimal Reproducible Example

https://github.com/NullVoxPopuli/warp-drive-tutorial/pull/3

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
It's not possible to achieve what you're looking with the current setup.

The current content collections pull all data inside `src/content`, so having files that don't satisfy the schema of your content collections is an error. 

For your setup, it's best to turn to [content layer](https://docs.astro.build/en/reference/configuration-reference/#experimentalcontentlayer) and use the `glob` loader to select the files you want.

**Comment by spaceemotion** [comment]
@ematipico We are using the glob loader with the new content layer, but are still getting a similar error (mixed content). Is this the same issue or should I open a new one? We are looking only for `.mdoc` files, but since we also have a couple `.json` ones in there it seems to get confused about...
