### ISSUE TITLE
Server island not work when using preload library

### ISSUE THREAD

**Issue by futamiy** [withastro/astro#12421]
### Astro Info

```block
Astro                    v4.16.10
Node                     v22.11.0
System                   Windows (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

When in page with server island and open link with server island (and same name component too) where using preload library like [framethrower](https://github.com/fireship-io/flamethrower), component not loaded and show this error
![CopyQ eBdChL](https://github.com/user-attachments/assets/3ebff5fb-8ce1-48ed-8b46-d4736942a419)
![CopyQ bObKnR](https://github.com/user-attachments/assets/dc74df8f-5380-45e5-9b04-4a0ba76d7a27)

[Repo](https://github.com/futamiyarn/futami-landing/tree/c976615820fe0e647230daa86bfe32980b8cf7da)

### What's the expected result?

server island component load normally even use preload library

### Link to Minimal Reproducible Example

Web Preview: https://4885e27d.futami.pages.dev/
Stackblitz Link: https://stackblitz.com/edit/withastro-astro-tkdvnm?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by apatel369** [comment]
@futamiy Please provide a valid reproduction. Here is the [guide](https://docs.astro.build/en/guides/troubleshooting/#creating-minimal-reproductions) to create it.

**Comment by futamiy** [comment]
stackblitz link: https://stackblitz.com/edit/withastro-astro-tkdvnm?file=package.json

**Comment by ematipico** [comment]
What does `flamethrower` do? Without the library, the server island works, so @futamiy you would need to explain to us at least what's happening.

**Comment by futamiy** [comment]
https://github.com/user-attachments/assets/0700827a-e197-4bac-b9af-f98c73515609
![CopyQ HGUnfH](https://github.com/user-attachments/assets/498577d0-45ca-4639-b9bc-049102fe041c)


When click a link and using `flamethrower`, image can't show because replacing body
Explain `framethrower` video: https://youtu.be/SJeBRW1QQMA?t=311

**Comment by ematipico** [comment]
I don't think there's much we can do, if a library messes up with script tags, we can't prevent it.

I will send a PR to avoid that runtime error in the console, but maybe you should check if that library allows to prevent prefetching all script tags
