### ISSUE TITLE
`is:global` keywords within `<head>` are included in builds

### ISSUE THREAD

**Issue by YektaDev** [withastro/astro#12434]
### Astro Info

```block
> @example/minimal@0.0.1 astro
> astro info

Astro                    v4.16.12
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

The use of global styles (`<style is:global>`) in components placed inside the `<head>` is included as-is in the final bundle, causing this HTML validation error:

```
Attribute “is:global” not allowed on element “style” at this point.
```

### What's the expected result?

All `is:global` tokens to be stripped from the output of `npm run build`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wdcfns?file=dist%2Findex.html

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
This is a bug in my component, not in Astro itself. Thanks for taking the time to do it tho!

**Comment by YektaDev** [comment]
But isn't this what happens to every head components' `<style is:global>` tag?

**Comment by florian-lefebvre** [comment]
No I think in this case it's because I'm using `set:html`, which probably opts out of the behavior of `is:global`
