### ISSUE TITLE
defineCollection and other declarations missing from generated types for "astro:content" module

### ISSUE THREAD

**Issue by bsidhom** [withastro/astro#12439]
### Astro Info

```block
Astro                    v4.16.12
Node                     v23.2.0
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

No browser; this is a development issue

### Describe the Bug

With a minimal project using yarn 4.5.1, Astro 4.16.12 and the latest official VSCode Astro extension, I'm getting an error in my `src/content/config.ts` file when I try to do the following import:

```
import { defineCollection, z } from "astro:content";
```

This is the error I see:
```
Module '"astro:content"' has no exported member 'defineCollection'.ts(2305)
```

I can confirm that, indeed, the `defineCollection` and `z` declarations are _missing_ from the `.astro/astro/content.d.ts` typing file. (I can share the contents of that file if desired, but you should be able to reproduce with my sample.)

I've linked a minimal reproduction. To initialize the project, I just ran `yarn init -2`, added the relevant Astro dev dependencies, and pasted in a few filler content files. I see the same issue whether I put everything into `dependencies` or `devDependencies` in my `package.json`, so it does not appear to be a dev-vs-runtime dependency issue.

Note that I wasn't able to insert slashes (`/`) into the gist files, so I've replaced those with underscores (`_`).

I've also run `astro sync`, `astro check`, and `astro build`. All result in the same _VSCode type error_. I am able to successfully _build_ and view the website.

Finally, the closest previous issue I could find to this one was https://github.com/withastro/astro/issues/5711, which seems to be complaining that the module doesn't exist _at all_. This is _not_ what I'm seeing; instead, I'm seeing that not all of the module exports are getting into the declaration file.

### What's the expected result?

The `.astro/astro/content.d.ts` should contain all relevant typings and should allow type checking of collection schemas.

### Link to Minimal Reproducible Example

https://gist.github.com/bsidhom/88417490e8dc651a17f1608c5af3067c

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Mikescops** [comment]
Ah anyway, I figured out I forgot to include `"include": ["./src/**/*.astro"]` in my `tsconfig.json`. Now it works like a charm, sorry for the noise.

**Comment by ascorbic** [comment]
@bsidhom it looks like this is an issue with type resolution and Yarn PnP. It's failing to pick up the types from the Astro package. The `defineCollection` and `z` types are declared in the `astro` module, not in `.astro/content.d.ts`. If I install your repro with pnpm then it works.

**Comment by ascorbic** [comment]
I'm going to close this because we document the fact that you may need to disable PnP when using yarn: https://docs.astro.build/en/guides/troubleshooting/#using-astro-with-yarn-2-berry

**Comment by bsidhom** [comment]
Yes, this was my fear. And I can confirm that it works if I opt out of PnP with Yarn.

**Comment by bsidhom** [comment]
I'm just confused as to why type resolution works for _most_ but not _all_ components.
