### ISSUE TITLE
@astrojs/sitemap not included in the static output with SSR on Vercel adapter

### ISSUE THREAD

**Issue by Javiervinus** [withastro/astro#12437]
### Astro Info

```block
Astro                    v5.0.0-beta.8
Node                     v20.11.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/vercel
Integrations             @astrojs/sitemap
                         @astrojs/tailwind
                         @astrojs/react
                         astro-icon
                         @astrojs/partytown
```

### Describe the Bug

In an Astro project using the `@astrojs/sitemap` plugin and deploying with the Vercel adapter (`@astrojs/vercel` in SSR mode), the `sitemap.xml` file **does not appear in the final static output on Vercel**.

#### Issue Details
- The issue is not related to missing SSR dynamic routes in the sitemap. In fact, I am using the `customPages` option in `@astrojs/sitemap` to handle dynamic routes manually, and this part works as expected.
- The main problem is that the `@astrojs/sitemap` plugin generates the `sitemap.xml` **after Vercel has already finalized the static assets output**.
- During the local build, the sitemap file is created in the `dist/client` folder **only after Vercel finishes packaging** the static content, which causes the sitemap file to be excluded from the deployed static files.

#### Project Context
- The project contains a mix of **static** and **SSR pages**.
- The sitemap is intended to index both types of pages, but **even the static pages** do not appear in the final build on Vercel due to the timing of the sitemap generation.

### What's the expected result?

The `@astrojs/sitemap` plugin should generate the `sitemap.xml` and any other sitemap files **before the Vercel adapter finalizes the build**. This way, the sitemap files can be included in the output deployed to Vercel.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Javiervinus** [comment]
I've attached a series of images to illustrate the issue with the sitemap generation timing in relation to the Vercel build process:

1. **Intermediate `dist` Folder**: This first image shows the `dist` folder during the build process, where both the `client` and `server` folders are present. At this stage, the `sitemap.xml` is not yet generated in the `client` folder, which is where Vercel pulls its static assets for deployment.
![image](https://github.com/user-attachments/assets/9c05bc9a-80a6-445a-9bdf-177952867e08)

2. **Vercel Static Output**: The second image shows the final output generated by Vercel for deployment. As you can see, the `sitemap.xml` is missing from this output, indicating that it was not included in the packaging process.
![image](https://github.com/user-attachments/assets/5ed05cc2-74c6-4a83-b609-debd1dffdf56)

3. **Final `dist` Folder After Build Completes**: The third image shows the `dist` folder after the build process has fully completed, at which point the `sitemap.xml` finally appears in the `client` folder. However, by this time, Vercel has already completed the packaging of static assets, so the `sitemap.xml` is not included in the deployed output.
![image](https://github.com/user-attachments/assets/4c846e10-a865-4ca6-a216-4b265438d9f6)


These images provide evidence that the `sitemap.xml` is being generated after Vercel has already finalized the static output, leading to it being excluded from the deployed files.

**Comment by lilith** [comment]
I am also experiencing this bug.

**Comment by javiern8410** [comment]
> I am also experiencing this bug.

I am too! 

Vercel output does not generate sitemap but in my dist folder have a sitemap files

![image](https://github.com/user-attachments/assets/c3436eab-0f9b-44ca-8531-e6b964a4fa5a)
