### ISSUE TITLE
Can not import from astro:env/client and astro:env/server

### ISSUE THREAD

**Issue by sgalcheung** [withastro/astro#12448]
### Astro Info

```block
Astro                    v5.0.0-beta.2
Node                     v18.20.3
System                   macOS (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/starlight
                         @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

10:45:37 PM [vite] Pre-transform error: Failed to load url astro:env/server (resolved id: astro:env/server) in /Users/.../starlight-squidex/packages/starlight-ssr/index.ts. Does the file exist?
10:45:37 PM [vite] Error when evaluating SSR module /@fs/Users/.../starlight-squidex/packages/starlight-ssr/index.ts: failed to import "astro:env/server"
|- Error: Cannot find module 'astro:env/server' imported from '/Users/.../starlight-squidex/packages/starlight-ssr/index.ts'
    at nodeImport (file:///...o/starlight-squidex/node_modules/.pnpm/vite@5.4.8_@types+node@22.9.0/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52990:19)
    at ssrImport (file:///.../starlight-squidex/node_modules/.pnpm/vite@5.4.8_@types+node@22.9.0/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52857:22)
    at eval (eval at instantiateModule (file:///.../starlight-squidex/node_modules/.pnpm/vite@5.4.8_@types+node@22.9.0/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52906:24), <anonymous>:5:37)
    at async instantiateModule (file://.../starlight-squidex/node_modules/.pnpm/vite@5.4.8_@types+node@22.9.0/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52915:5)

### What's the expected result?

Loading custom env.

I noticed the limitations of the `astro:env` API:

> astro:env is a virtual module which means it can only be used inside the Astro context. For example, you can use it in:
> 
> - Middlewares
> - Astro routes and endpoints
> - Astro components
> - Framework components
> - Modules
> 
> You cannot use it in the following and will have to resort to process.env:
> 
> - astro.config.mjs
> - Scripts

I don't know how about integrations and how about the lifecycle.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-un5xht?file=example%2Fpackage.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Background & Motivation
- Some variable must be load from .env file or other files, as a startup run(like pass dashboard config variables).
- If we write this variables hardcode in `astro.config.mjs`, and you want to modify it, we must modify the code in production environment.

**Comment by sgalcheung** [comment]
> Tools for integrations authors to allow them using env variables inside integrations (ie. no access to virtual modules)
[quote from 0049-astro-env.md](https://github.com/withastro/roadmap/blob/main/proposals/0049-astro-env.md)

That means we can access virtual modules using env variables.

**Comment by sgalcheung** [comment]
For now, I used vite's `LoadEnv` as a temp method that load env variables in `astro.config.mjs`.
```
import { loadEnv } from 'vite';

const env = loadEnv('', process.cwd(), '');
```

**Comment by florian-lefebvre** [comment]
`loadEnv` is indeed the right API for this. An API around `astro:env` outside of Astro context has been requested several times, but no one created a roadmap discussion so we're not evaluating it for now. Feel free to create one!

**Comment by sgalcheung** [comment]
moved to https://github.com/withastro/roadmap/discussions/1057
