### ISSUE TITLE
Server islands does not support indirect components - "Could not find server component name"

### ISSUE THREAD

**Issue by moonlitknight** [withastro/astro#12458]
### Astro Info

```block
Astro                    v5.0.0-beta.8
Node                     v22.5.1
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/vercel
Integrations             @astrojs/tailwind
                         @astrojs/solid-js
```

### Describe the Bug

tl;dr adding "server:defer" to my component causes error 
```
13:52:48 [ERROR] Could not find server component name
  Stack trace:
    at /usr/app/sluroy/astrosb/node_modules/.pnpm/astro@5.0.0-beta.8_@types+node@22.7.4_jiti@1.21.6_rollup@4.27.2_typescript@5.6.2_yaml@2.5.1/node_modules/astro/dist/runtime/server/render/server-islands.js:35:15
    [...] See full stack trace in the browser, or rerun with --verbose.
```

My code is unusual insofar as, I do not render the component by name, but rather I instantiate an object that contains the component object and render that. This works fine without server islands, but fails if I add "server:defer". 

See the `index.astro` file in the attached Stackblitz to see the minimal code and some additional notes on why I am doing this.

### What's the expected result?

I expect my component to render.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-u2cja6?file=src%2Fpages%2Findex.astro&title=Astro%20Starter%20Kit:%20Basics

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
By default, Astro uses the name of the name to resolve it when rendering the island, but since you change the component to `ComponentToRender`, it's not able to find `Card.astro` anymore.

This is required by the Astro rendering engine.

**Comment by moonlitknight** [comment]
That's fine.
It might be worth including in the server islands documentation as it's
reasonable for developers to expect that adding "server:defer" to a working
component should not break it.

**Comment by ematipico** [comment]
What you might want to do is the following:

```
{
  ComponentToRender === 'Card' ? (
    <Card server:defer />
  ) : ComponentToRender === 'Other' ? (
    <Other server:defer />
  ) : ...
}
```

Astro relies on static analysis at the compiler level to determine the component to render. This is true for client directives.

**Comment by JuanDeve** [comment]
i found the solution 
![image](https://github.com/user-attachments/assets/58c5a2c7-a95d-46e4-9e4a-ea33453f8ee3)
You need the astro.config.mjs like this. The server island is experimental.
