### ISSUE TITLE
[5.0.0-beta.8] Astro.request.headers warning when build output server with prerender

### ISSUE THREAD

**Issue by drithh** [withastro/astro#12459]
### Astro Info

```block
Astro                    v5.0.0-beta.8
Node                     v23.1.0
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

```
[WARN] `Astro.request.headers` is not available on prerendered pages. If you need access to request headers, make sure that the page is server rendered using `export const prerender = false;` or by setting `output` to `"server"` in your Astro config to make all your pages server rendered.
```

that warning will be shown on output mode `server` and there page with `export const prerender = true;` 

### What's the expected result?

The warning shouldn’t appear because I’m not accessing the headers in my code. This issue seems similar to what’s described here: [withastro/astro#12069](https://github.com/withastro/astro/issues/12069). but this issue only fix when output mode `static`

### Link to Minimal Reproducible Example

https://github.com/drithh/astro-header-warning

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@drithh please provide a valid reproduction, you `astro info` says you're using the node adapter, but reproduction doesn't have any

**Comment by mayank99** [comment]
Here's a minimal repro: https://stackblitz.com/edit/github-rtcfqk?file=astro.config.mjs,src%2Fpages%2Findex.astro&on=stackblitz

```
20:52:45 [build] Building server entrypoints...
20:52:46 [vite] ✓ built in 1.07s
20:52:46 [build] ✓ Completed in 1.37s.

 prerendering static routes 
20:52:46 ▶ src/pages/index.astro
20:52:46   └─ /index.html20:52:46 [WARN] `Astro.request.headers` is unavailable in "static" output mode, and in prerendered pages within "hybrid" and "server" output modes. If you need access to request headers, make sure that `output` is configured as either `"server"` or `output: "hybrid"` in your config file, and that the page accessing the headers is rendered on-demand.
 (+27ms)
20:52:46 ✓ Completed in 189ms.
```

**Comment by spaceemotion** [comment]
Just stumbled across this as well - but it only started to happen after I added the experimental container API (we needed to render a Content component to HTML). Not sure if I need to configure something in the container to make the warning go away.

**Comment by ascorbic** [comment]
I've just checked using @mayank99's repro and can confirm that updating to beta.12 fixes this.
