### ISSUE TITLE
astrojs-svelte Unexpected tokens, unavailable stack traces, __vite_ssr_import_2__.TextLine is not a function

### ISSUE THREAD

**Issue by djkato** [withastro/astro#12454]
### Astro Info

```block
Astro                    v4.16.13
Node                     v23.1.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

1. [ERROR] __vite_ssr_import_2__.TextLine is not a function for unknown reason in many of my projects files
![image](https://github.com/user-attachments/assets/b2694cff-7e14-4481-91a2-86aea55f25d3)
2. Unexpected tokens instead of ledgible issues / stack traces
![image](https://github.com/user-attachments/assets/c6c97053-c97c-44a8-b19a-2ef7f85ea73c)
The minimal repo I gave tries to reproduce the issue with as little code as possible. I deleted stuff willy nilly, so the code actually might not be correct! But since the issue is astro not *reporting* the issues right, I think it's fine.

### What's the expected result?

To either give proper reasons why something is broken, or just work? I don't see what's wrong in my code.

### Link to Minimal Reproducible Example

https://github.com/djkato/astrojs-svelte-error

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
cc  @bluwy

**Comment by bluwy** [comment]
```diff
-    import { SelectInline } from "./universal/SelectInline.svelte"
+    import SelectInline from "./universal/SelectInline.svelte"
```

Svelte components are default exported. I'm not sure why Vite isn't giving nice errors here, I'd suggest reporting an issue to Vite to possibly improve this. Closing this as I don't think it's a bug Astro can fix.

**Comment by bluwy** [comment]
I'm not getting any errors after updating to default imports in the repro. The errors you show seem strange to me and implies some sort of JS parsing error. Maybe you can try re-installing dependencies or use a different package manager? Also, the `overrides` in your package.json can also be removed.

**Comment by djkato** [comment]
The package manager was the issue. After I switched from bun to pnpm it builds correctly.
I'll go report it there then
