### ISSUE TITLE
Continuous benchmark workflows runs on forked repositories

### ISSUE THREAD

**Issue by mandar1jn** [withastro/astro#12467]
### Astro Info

```block
Not applicable
```

### If this issue only occurs in one browser, which browser is a problem?

Not applicable

### Describe the Bug

The action as defined in [continuous_benchmark.yml](https://github.com/withastro/astro/blob/main/.github/workflows/continuous_benchmark.yml) should only run on repositories within the astro organisation since it contains `if: ${{ github.repository_owner == 'withastro' }}`. However, as can be seen in [the actions tab](https://github.com/withastro/astro/actions/workflows/continuous_benchmark.yml), this workflow is also ran on repositories outside of the organisation, causing them to fail and somehow clog up the actions tab.

### What's the expected result?

The workflow should not be ran on any repository outside of the withastro organisation.

### Link to Minimal Reproducible Example

Not applicable

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Closed by https://github.com/withastro/astro/pull/12466 ?

**Comment by mandar1jn** [comment]
it shouldn't be. The workflow shouldn't run at all regardless of whether the token is present

**Comment by ematipico** [comment]
Why? The objective is to find if PRs might add regressions

**Comment by mandar1jn** [comment]
Oh. Yeah. You're right. I was interpretting the original mistake as "this is being ran on other repositories when we push a commit". Didn't realise it was for PRs. This should fix it. My bad.
