### ISSUE TITLE
Non-critical error when running Astro 5 in dev mode: "[vite] cannot find entry point module 'astro:db'."

### ISSUE THREAD

**Issue by goosechaser** [withastro/astro#12474]
### Astro Info

```block
Astro                    v5.0.0-beta.8
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/svelte
                         @astrojs/tailwind
                         astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

Running `npm run dev` shows:

```
18:33:24 [types] Generated 1ms

 astro  v5.0.0-beta.8 ready in 1114 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

▶ This is a  beta  prerelease build!
  Report issues here: https://astro.build/issues

18:33:24 watching for file changes...
18:33:24 [astro:db] New local database created.
18:33:24 [ERROR] [astro:db] [vite] cannot find entry point module 'astro:db'.
18:33:56 [astro:db] Seeded database.
....
```

Everything works though. 

### What's the expected result?

No error should be displayed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-f2kqtd?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by apatel369** [comment]
I can reproduce this error:
```
17:06:28 watching for file changes...
17:06:28 [astro:db] New local database created.
17:06:28 [ERROR] [astro:db] [vite] cannot find entry point module 'astro:db'.
17:06:32 [astro:db] Seeded database.
17:06:33 [200] / 1407ms
```

**Comment by Dame-G** [comment]
Also getting same output. v. 5.0.0 beta 7

```
19:08:20 [types] Generated 2ms
19:08:20 [vite] Re-optimizing dependencies because lockfile has changed
19:08:21 [astro:db] New local database created.
19:08:21 [ERROR] [astro:db] [vite] cannot find entry point module 'astro:db'.
```

**Comment by jonaspm** [comment]
I am facing the same error:

```text
13:35:56 [astro:db] New local database created.
13:35:56 [ERROR] [astro:db] [vite] cannot find entry point module 'astro:db'.
```

**Comment by brunogarba** [comment]
I'm getting the same issue after upgrading to 5.0.1

**Comment by ochoa8al** [comment]
same error

**Comment by 0bkevin** [comment]
Same error here, just upgrade to astro v5

**Comment by 0bkevin** [comment]
For my, the error only happens when you have installed `@astro/mdx` when I uninstall it, it works normally.


``` package.json
{
  "name": "...",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.9.4",
    "@astrojs/svelte": "^7.0.1",
    "@astrojs/tailwind": "^5.1.3",
    "astro": "^5.0.1",
    "svelte": "^5.2.2",
    "swiper": "^11.1.15",
    "tailwindcss": "^3.4.15",
    "typescript": "^5.6.3"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.15",
    "@types/node": "^17.0.15"
  }
}

```

**Comment by ascorbic** [comment]
This seems to be coming from [here](https://github.com/withastro/astro/blob/uppercase-images/packages/db/src/core/integration/index.ts#L156), where we try to eagerly-load the virtual module. What the error message isn't showing is that the module it's trying to load is actually `\0astro:db`. The null-prefixed name is used internally by the Vite plugin. What is unclear is whether that is deliberate. I'll defer to @bholmesdev on that. What I do know is that changing it to instead import `"astro:db"` fixes the immediate issue.

**Comment by Uninen** [comment]
FWIW I get this error as a critical error (which prevents dev server to start) when I install `@astrojs/mdx` with 5.0.2:

```
03:41:59 [ERROR] [vite] cannot find entry point module '/[...]/node_modules/.pnpm/@astrojs+mdx@4.0.1_astro@5.0.2_@types+node@22.10.1_jiti@1.21.6_rollup@4.28.0_typescript@5.6.3_yaml@2.6.1_/node_modules/@astrojs/mdx/dist/server.js'.

```

**Comment by ascorbic** [comment]
@Uninen that won't be related to this

**Comment by cameronapak** [comment]
I am getting the same error:

```bash
15:17:05 [ERROR] [astro:db] [vite] cannot find entry point module 'astro:db'.
```

My package.json includes:

```json
"@astrojs/db": "^0.14.3",
"astro": "^5.0.3",
```

[Here's the codebase.](https://github.com/cameronapak/freedom-stack/pull/44)

**Comment by bholmesdev** [comment]
Hey @cameronapak! Thanks for reporting. Looks like we're on 5.0.4 right now. Can you confirm this still occurs on the latest? If so, it may be worth making a new issue with a link to your codebase

**Comment by cameronapak** [comment]
Will do, @bholmesdev!

**Comment by jonaspm** [comment]
I confirm it still happens in v5.0.4:
![imagen](https://github.com/user-attachments/assets/e15cd8a7-9350-4dfd-93f8-c862dcffc5fc)
