### ISSUE TITLE
Issue with Astro 5 and vercel adapter

### ISSUE THREAD

**Issue by javiern8410** [withastro/astro#12485]
### Astro Info

```block
When try to add vercel adapter on Astro 5 see this error in console.

[ERROR] [config] The adapter @astrojs/vercel/serverless does not currently support the feature "sharp". Your project may not build correctly.

This is when trying to install manualy because automatic install fail.

npx astro add vercel
√ Resolving packages...

  Astro will run the following command:
  If you skip this step, you can always run it yourself later

 ╭─────────────────────────────────────╮
 │ npm install @astrojs/vercel@^7.8.2  │
 ╰─────────────────────────────────────╯

√ Continue? ... yes
× Installing dependencies...

 The command `npm install @astrojs/vercel@^7.8.2` exited with code 1
```

### Describe the Bug

Error when add vercel adapter on Astro 5

### What's the expected result?

Build to Vercel with vercel adapter

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-soh3xs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
Hi. When you're working with the beta version you need to ensure you add beta versions of adapters. You can do this with `npx astro add vercel@beta`

**Comment by javiern8410** [comment]
> Hi. When you're working with the beta version you need to ensure you add beta versions of adapters. You can do this with `npx astro add vercel@beta`

Thanks @ascorbic, this work fine 👍
