### ISSUE TITLE
Middleware code is executed during build

### ISSUE THREAD

**Issue by rktyt** [withastro/astro#12495]
### Astro Info

```block
Astro                    v4.16.14
Node                     v20.15.0
System                   Linux (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### Describe the Bug

In v4.16.13, the build passed without any errors, but in v4.16.14 the build started to fail.
It looks like the build is "executing" the middleware code.

### What's the expected result?

There are no errors in the build.
The build is expected to only be transpiled.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-patrsd?file=src%2Fmiddleware%2Findex.ts

Please run `npm run build`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
It's possible you missed that part, but that's expected. We explain it right at the beginning of our docs: https://docs.astro.build/en/guides/middleware/#_top

**Comment by rktyt** [comment]
@ematipico 
Document says "all prerendered pages".
If the setting is `output: 'server'`, it is on-demand, so it shouldn't be executed, right?
