### ISSUE TITLE
In 4.16.14: middleware suddenly reads config.ts with `astro build`, it didn't since at least 4.10

### ISSUE THREAD

**Issue by corneliusroemer** [withastro/astro#12527]
### Astro Info

```block
Astro                    v4.16.14
Node                     v22.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/react
                         @astrojs/mdx
```

### Describe the Bug

When upgrading from 4.16.14 (via dependabot), `astro build` suddenly fails, it worked fine in 4.16.13.

We have a JSON config file that is read by config.ts at runtime. It's not present at build time. This was never an issue until 4.16.14 where we suddenly get build failures if the file is not present (no build failure if the file is present).

Repro:
1. Check out https://github.com/loculus-project/loculus/commit/7534e92c9d1ecdd56f5ae2df903d0a615455263f
2. `cd website && npm ci && npm run build`
3. Observe result

This previous commit with only difference being 4.16.13 builds fine: https://github.com/loculus-project/loculus/commit/94732cabfedf7727a80e50ba2e29a2d9c01a036c

Stacktrace:

```
23:33:17 [vite] ✓ built in 5.38s
ENOENT: no such file or directory, open 'tests/config/website_config2.json'
  Location:
    /Users/corneliusromer/code/loculus/website/node_modules/astro/dist/core/build/pipeline.js:105:57
  Stack trace:
    at Object.readFileSync (node:fs:441:20)
    at getWebsiteConfig (file:///Users/corneliusromer/code/loculus/website/dist/server/chunks/config_DyPyM6lX.mjs:407:15)
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async BuildPipeline.retrieveManifest (file:///Users/corneliusromer/code/loculus/website/node_modules/astro/dist/core/build/pipeline.js:105:57)
    at async staticBuild (file:///Users/corneliusromer/code/loculus/website/node_modules/astro/dist/core/build/static-build.js:109:5)
    at async AstroBuilder.run (file:///Users/corneliusromer/code/loculus/website/node_modules/astro/dist/core/build/index.js:182:7)
    at async build (file:///Users/corneliusromer/code/loculus/website/node_modules/astro/dist/cli/build/index.js:24:3)
    at async cli (file:///Users/corneliusromer/code/loculus/website/node_modules/astro/dist/cli/index.js:175:5)
```

### What's the expected result?

Build works without issue as it did until 4.16.13

### Link to Minimal Reproducible Example

https://github.com/loculus-project/loculus/commit/7534e92c9d1ecdd56f5ae2df903d0a615455263f

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
That file is read in the middleware, and the middleware is also executed during the build for prerendered pages. It's documented in documentation.

It's been like this since the very beginning. Can you please narrow down the issue and provide a reproduction?

**Comment by corneliusroemer** [comment]
I agree that the reproduction isn't minimal but it _is_ a precise reproduction occurring between to patch versions.

If the reason is that "the middleware is also executed during the build for prerendered pages. It's documented in documentation." this must mean that in a patch version, some new pages prerendered that didn't before. Is that possible?

**Comment by corneliusroemer** [comment]
Ok, it does seem to happen in the middleware and we had a code change there 6 days ago. So it's possible this should have always been an error and it just wasn't in the particular Astro version we were using at the time, likely 4.16.7

Does that sound like a plausible explanation?

**Comment by corneliusroemer** [comment]
Ok here's a stackblitz: it passes with 4.16.13 and fails with 4.16.14 when you run `npm run build`: https://stackblitz.com/edit/github-patrsd-2vc61n?file=src%2Fconfig.ts

**Comment by ematipico** [comment]
@corneliusroemer

The stackblitz you shared uses `4.16.13` anbd **it fails**. Also, why would you expect this to not fail? The example you shared shows that the code tries to read a file that doesn't exist, so it makes sense having the error.

In the latest patch, we fixed a minor bug around the middleware, so maybe, without knowing, you were leveraging the bug?

**Comment by rktyt** [comment]
Currently, it seems that all code must be defined within onRequest.
However, it is also true that SSR has a lot of code that only needs to run once before onRequest.

In my case I have something like connecting with an another system through a socket file.
Honestly, I don't want to prepare something that is not necessary just to pass the build.
Even if the current behavior is correct, I don't want to accept it.
So I decided to apply the patch manually.

I don't know if it will be helpful, but I will list the patch that I have applied at hand.
**I do not guarantee operation nor take any responsibility. (I have no idea how this part of the code is actually used)**
Works fine in my project.
Note: I am using it in middleware mode, not standalone mode. Also, the server program is bundled with esbuild after astro build.

This is for astro@4.16.15.
patches/astro+4.16.15.patch (used by `patch-package`)
```patch
diff --git a/node_modules/astro/dist/core/build/pipeline.js b/node_modules/astro/dist/core/build/pipeline.js
index a960ded..1accc2f 100644
--- a/node_modules/astro/dist/core/build/pipeline.js
+++ b/node_modules/astro/dist/core/build/pipeline.js
@@ -12,7 +12,7 @@ import { createDefaultRoutes } from "../routing/default.js";
 import { findRouteToRewrite } from "../routing/rewrite.js";
 import { isServerLikeOutput } from "../util.js";
 import { getOutDirWithinCwd } from "./common.js";
-import { cssOrder, getPageData, mergeInlineCss } from "./internal.js";
+import { cssOrder, getPageData, mergeInlineCss, hasPrerenderedPages } from "./internal.js";
 import { ASTRO_PAGE_MODULE_ID, ASTRO_PAGE_RESOLVED_MODULE_ID } from "./plugins/plugin-pages.js";
 import { RESOLVED_SPLIT_MODULE_ID } from "./plugins/plugin-ssr.js";
 import { getPagesFromVirtualModulePageName, getVirtualModulePageName } from "./plugins/util.js";
@@ -102,7 +102,8 @@ class BuildPipeline extends Pipeline {
     }
     const renderersEntryUrl = new URL(`renderers.mjs?time=${Date.now()}`, baseDirectory);
     const renderers = await import(renderersEntryUrl.toString());
-    const middleware = internals.middlewareEntryPoint ? await import(internals.middlewareEntryPoint.toString()).then((mod) => {
+    // Probably it would be OK to import internals.middlewareEntryPoint only if there are prerendered pages.
+    const middleware = hasPrerenderedPages(internals) && internals.middlewareEntryPoint ? await import(internals.middlewareEntryPoint.toString()).then((mod) => {
       return function() {
         return { onRequest: mod.onRequest };
       };
```

**Comment by corneliusroemer** [comment]
@ematipico apologies for the not-so-good stackblitz setup that didn't make it obvious what version was running. I've now fixed the setup so you should see that:
- 4.10.1 builds: https://stackblitz.com/edit/github-patrsd-qqxnpz?file=package.json
- 4.16.13 builds: https://stackblitz.com/edit/github-patrsd-kx4wvg?file=package.json
- 4.16.14 fails: https://stackblitz.com/edit/github-patrsd-q88fg5?file=package.json
- 4.16.16 fails: https://stackblitz.com/edit/github-patrsd-j3yb4o?file=package.json

> Also, why would you expect this to not fail? The example you shared shows that the code tries to read a file that doesn't exist, so it makes sense having the error.

In our project, we read a file in config.ts that's only available at _run time_ not at _build time_.

It's quite possible that you want to change behavior to _require_ config.ts to pass _at build time_, but such a behaviour change (requiring config.ts to run successfully at build time when it previously wasn't required to run) should come with a major version bump not a patch. Unless you think this should have always been required and it has been a bug for much or all of astro's life that config.ts wasn't required to run.

I don't have strong feelings about the ideal behavior here, I just had a dependabot upgrade fail between patch releases and wanted to report this.

**Comment by ematipico** [comment]
> It's quite possible that you want to change behavior to require config.ts to pass at build time, but such a behaviour change (requiring config.ts to run successfully at build time when it previously wasn't required to run) should come with a major version bump not a patch. Unless you think this should have always been required and it has been a bug for much or all of astro's life that config.ts wasn't required to run.

I am not sure I understand what you mean here, because, as far I understood, the only `config.ts` file known to Astro is the one that belongs to the content collections, which is not the case. 

As explained before, it's possible you were leveraging the bug without even knowing. The stackblitz examples also show that the middleware was working with incorrect assumptions. So, when we fixed the bug, it uncovered a small issue with the code. **It wasn't intentional**, so apologies if that broke your code. 

> In our project, we read a file in config.ts that's only available at run time not at build time.

[We've always documented](https://docs.astro.build/en/guides/middleware/) that the middleware runs at build time too:

> This rendering occurs at build time for all prerendered pages, but occurs when the route is requested for pages rendered on demand

So it's up to you to decide whether to import that file. From v5, the `ctx` now exposes a property called [`isPrerendererd`](https://docs.astro.build/en/reference/api-reference/#routepattern) and [`routePattern`](https://docs.astro.build/en/reference/api-reference/#routepattern), so you can use those to better detect when you're at runtime and import the config only when needed:

```
export const onRequest = async (ctx, next) => {
	if (!ctx.isPrerendered) {
		const config = await import("./config");
		// .. do something
	}
	return next();
}
```
