### ISSUE TITLE
Cannot find module 'astro:content' or its corresponding type declarations. 

### ISSUE THREAD

**Issue by sgalcheung** [withastro/astro#12531]
### Astro Info

```block
"astro": "^5.0.0-beta
```

### Describe the Bug

When I write an integration, it need to reference to "astro:content", but tsup couldn't handle this module, so how do you compile and publish this?

> ESM Build failed
> Error: Build failed with 1 error:
> src/loaders.ts:6:7: ERROR: Could not resolve "astro:content"

### What's the expected result?

compile correct the integration.

### Link to Minimal Reproducible Example

https://undefined

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sgalcheung** [comment]
I used this solution resolved for me.

Since `astro:content `is project-specific and requires a proper Astro environment, avoid bundling it directly. Instead:
Treat it as an external dependency in your tsup.config.ts:
```
export default defineConfig({
  external: ['astro:content'], // Exclude `astro:content` from the bundle
});
```

**Comment by ascorbic** [comment]
It sounds like you've found a solution so I'll close this.
