### ISSUE TITLE
 Issue with Trailing Slashes in URLs Preventing Middleware Execution in Astro

### ISSUE THREAD

**Issue by rajpatel2435** [withastro/astro#12537]
Hello @tordans @altano @madbook 

### Astro Info

```block
Astro                    v4.5.2
Node                     v20.9.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

All Browser

### Describe the Bug

When accessing URLs with multiple trailing slashes, such as:

https://vegasaces.com/games/slots/lucky-dama-muerta//////////
The URL is automatically normalized in the backend to:

/games/slots/lucky-dama-muerta/

However, this normalization seems to bypass middleware logic. As a result, middleware doesn't execute as expected for the raw incoming URL.

Steps to Reproduce:

Create an Astro project with a middleware to log requests or process specific slugs.
Access a URL with multiple trailing slashes (e.g., //////////).
Observe that the middleware does not execute correctly for the normalized path.

### What's the expected result?

Astro should identify and process URLs with multiple trailing slashes correctly, ensuring middleware functions execute as intended.

Current Behavior:
URLs with trailing slashes are normalized by Astro, but middleware logic does not handle the original raw URL, causing inconsistencies.

### Link to Minimal Reproducible Example

https://vegasaces.com/games/slots/lucky-dama-muerta//////////

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
Hi. It's not totally clear to me what you mean when you say the middleware is not ezecuted correctly. Is it not executed at all, or in the wrong way? If the latter, wrong in what way. Can you provide a reproduction that includes the source code, ideally via stackblitz. Thanks

**Comment by rajpatel2435** [comment]
Hi @ascorbic 

Issue is that when I type in browser with multiple trailing slashes 

https://vegasaces.com/games/slots/////////

in Astro logs terminal  I just got
https://vegasaces.com/games/slots/

how can I fix that so I only have one trailing slashes in the end of URL?

https://github.com/rajpatel2435/Slotsparadise_Astro

Thanks

**Comment by ascorbic** [comment]
That's not something we can use as a minimal reproduction. Please create a minimal reproduction, ideally using [astro.new](https://astro.new) and Stackblitz.

**Comment by rajpatel2435** [comment]
Hi @ascorbic 

![image](https://github.com/user-attachments/assets/723d26ee-d64d-41fe-9457-383da4eb18a2)

https://stackblitz.com/~/github.com/rajpatel2435/Slotsparadise_Astro?file=src/layouts/Layout.astro&initialPath=/casino/slots/////////////////////////


Thanks

**Comment by ascorbic** [comment]
That link shows a 404 page for me. Please see the instructions on creating a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Please don't just share your whole site: you need to narrow it to the smallest example that reproduces the problem. It's usually best to start from a starter site rather than from your own site.

**Comment by rajpatel2435** [comment]
Hi @ascorbic 

This is the minimal project structure

https://stackblitz.com/~/github.com/rajpatel2435/slots?file=.env&initialPath=/how-to-play///

Thanks

**Comment by ascorbic** [comment]
That project has no middleware, so I don't know how you can reproduce a bug. Can you please start from an empty project from https://astro.new and add just the parts needed to demonstrate the bug.

**Comment by rajpatel2435** [comment]
Hi @bluwy @ascorbic 

I updated the repo with middleware  but you did not get my point correctly. the issue is that in terminal we are not getting the actual url that we are writing in browsers so our middleware is not able to get the correct url from the frontend.

for example here in browser i am writing /how-to-play///////////// but i n terminal we are getting /how-to-play/ but in actual what we need is the backend will get the correct url what we are writing in the frontend

![image](https://github.com/user-attachments/assets/ac1ce3b0-2dd8-4b5b-9751-66d53c3d6dd1)
are u able to see difference here?

Thanks

**Comment by ematipico** [comment]
Sorry @rajpatel2435 , but your reproduction **isn't** minimal, please provide one

**Comment by rajpatel2435** [comment]
Solved from my side
