### ISSUE TITLE
Astro.request.headers is not available in "static" output mode.

### ISSUE THREAD

**Issue by hkbertoson** [withastro/astro#12544]
### Astro Info

```block
Astro                    v4.16.16
Node                     v20.18.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/solid-js
                         @sentry/astro
                         @astrojs/tailwind
                         astro-icon
                         @astrojs/alpinejs
                         @astrojs/sitemap
                         @astrojs/partytown
                         astro-turnstile
                         @playform/inline
                         @playform/compress
```

### Describe the Bug

![image](https://github.com/user-attachments/assets/2f853bb6-0494-456e-82dd-89d11a8eb4a0)

I can confirm im not using Headers anywhere

### What's the expected result?

Not to get this warning

### Link to Minimal Reproducible Example

https://stackblitz.com/see-above

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
We need a minimal reproduction, because it's very hard to isolate an issue if we're needing to build your whole site. If you can't reproduce it on Stackblitz it's fine to share a repo instead, but it needs to still be a minimal reproduction.

**Comment by hkbertoson** [comment]
Im wondering if it could be one of my Integrations?

**Comment by ascorbic** [comment]
Yes, there's a good chance it could be. This is why a minimal repro is vital.

**Comment by hkbertoson** [comment]
Upgrades to V5 and now the issue is fixed!
