### ISSUE TITLE
Print mode covers content with "On this page" section

### ISSUE THREAD

**Issue by virzak** [withastro/astro#12564]
### Astro Info

```block
Astro                    v4.16.16
Node                     v23.3.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Safari

### Describe the Bug

Print preview displays "On this page > Overview" section on every page, covering actual content.

Happens in both v4 and v5.

- Navigate to: https://docs.astro.build/en/guides/content-collections/
- Print and observe:
<img width="281" alt="image" src="https://github.com/user-attachments/assets/9d978e19-83e6-4890-a20a-e17e4e9d0517">

The actual content should be:

![image](https://github.com/user-attachments/assets/ac0c431d-7c6c-454e-bb1b-f28336cbc23a)

Same problem with v5.
 https://5-0-0-beta.docs.astro.build/en/guides/endpoints/

<img width="153" alt="image" src="https://github.com/user-attachments/assets/ffdb150a-17c1-4411-ac64-b661c8f79812">

### What's the expected result?

"On this page" should be hidden in print mode by default

### Link to Minimal Reproducible Example

https://docs.astro.build/en/guides/content-collections/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
We're using Starlight for the documentation, so the fix should be in https://github.com/withastro/starlight. However, print styles support is still a WIP at https://github.com/withastro/starlight/pull/157 and should be unblocked when Astro v5 releases soon. I'll close the issue for now but I'd suggest to follow progress on print mode support in that PR.
