### ISSUE TITLE
astro check command support import from CDN

### ISSUE THREAD

**Issue by daimalou** [withastro/astro#12569]
### Astro Info

```block
None
```

### Describe the Bug

```ts
import decode, {
  init as initDecoder,
} from "https://unpkg.com/@jsquash/webp@1.4.0/decode.js?module";
```

Vite support this syntax. But `astro check,` don't support. 

Only I change `"build": "astro check && astro build",` to `"build": "astro build",`, 

it works.

### What's the expected result?

astro check don't prompt this error.

### Link to Minimal Reproducible Example

None

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Until TypeScript supports this https://github.com/microsoft/TypeScript/issues/35749, it's not really possible for us to support. `astro check` is a wrapper around `tsc`.

I would suggest manually typing your module definitions until then, which is the common workaround
