### ISSUE TITLE
Missing styles since Astro 5

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#12616]
### Astro Info

```block
Astro                    v5.0.2
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Stylesheet generated by vite plugins is no longer added to the page.

![image](https://github.com/user-attachments/assets/68810c3c-3642-4e6c-b5b2-264c35f7ba47)

### What's the expected result?

Same result that astro 4 generates.

![image](https://github.com/user-attachments/assets/a08d9089-de7f-4cb7-991b-835270a14e13)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ojxby9

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
@bozdevs can you submit a separate issue with its own repro please

**Comment by ascorbic** [comment]
@lilnasy Even though this is a regression with Astro 5, it would be a good idea to submit this as an issue to ecsstatic too. It's hard to say if this is an issue with that plugin + Vite 6, or if it's Astro-specific, as the plugin hasn't been updated for Vite 6 yet.

**Comment by ascorbic** [comment]
This does only seem to be an issue in dev too: when I run a build, it works correctly.

**Comment by lilnasy** [comment]
The issue is astro specific. The styles added onto astro components are missing. They still load with framework components.

Although, the use with framework components changed in a more subtle way: the stylesheet is not added immediately in the initial html, rather it is added by vite client js dynamically. This affects vite 6 too but it does not block upgrading, the entirely missing styles in astro components do.

**Comment by lilnasy** [comment]
The issue is astro specific. The styles added onto astro components are missing. They still load with framework components.

Although, the use with framework components changed in a more subtle way: the stylesheet is not added immediately in the initial html, rather it is added by vite client js dynamically. This affects vite 6 too but it does not block upgrading, the entirely missing styles in astro components do.

That might mean vite no longer adds the css to the module graph (not immediately, at least), and that's why astro fails to retrieve them in `getStylesForURL()`:
https://github.com/withastro/astro/blob/24edead67a6a8a0e78f714ad53fb71792e0b9f1c/packages/astro/src/vite-plugin-astro-server/pipeline.ts#L122-L136
https://github.com/withastro/astro/blob/24edead67a6a8a0e78f714ad53fb71792e0b9f1c/packages/astro/src/vite-plugin-astro-server/css.ts#L14-L24

...and css for astro components is added only on initial page load, unlike for framework components, relying on full page refresh to update them, which seems to be another regression.

**Comment by bluwy** [comment]
I have not took a deeper look, but my hunch is that `@acab/ecsstatic` is not handling this [Vite breaking change](https://github.com/vitejs/vite/pull/17922) which indirectly affects how Astro searches for CSS>

**Comment by lilnasy** [comment]
It uses side effect imports, not css modules.

https://github.com/mayank99/ecsstatic/blob/3c75f63414e7a7ee88305ff3731f9a2109806fd5/package/vite.ts#L162

Would you expect a difference between astro and framework components with the breaking change you linked?

**Comment by bluwy** [comment]
Yes as framework components are rendered client side which Vite takes over and dynamically adds CSS by itself. The breaking change I linked affects all kinds of CSS, not only CSS modules.

**Comment by lilnasy** [comment]
If that is the relevant breaking change, how would the plugin migrate? Would it be by hooking the load of the css file with `export default ${JSON.stringify(css)}` for the server consumer?

**Comment by bluwy** [comment]
I've sent a fix downstream. The idea is for virtual module CSS to support the `?inline` query when Astro tries to add it to be able to get the processed CSS. I'll close this for now as it isn't a bug in Astro. https://github.com/mayank99/ecsstatic/pull/25
