### ISSUE TITLE
`astro^5.0+` should support `@astrojs/check` by default

### ISSUE THREAD

**Issue by JakiChen** [withastro/astro#12619]
### Astro Info

```block
Astro                    v5.0.1 || v5.0.2
Node                     v20.18.0
System                   macOS (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         astro-svgs
                         astro-robots
```

### Describe the Bug

There doesn't seem to be an option to choose whether to use `TypeScript` or not

<img width="625" alt="截屏2024-12-04 16 03 50" src="https://github.com/user-attachments/assets/344bc05d-b4fb-4844-bfe0-b998d021b84a">

So much so that all the preset templates don't seem to support the function of **`astro check`**, so why give up pre-installation? Manual installation is also available

```json
{
  "name": "astro-check",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "astro": "^5.0.2"
  }
}
```

### What's the expected result?

Astro Check should be supported by default

```json
{
  "name": "astro-check",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {},
  "devDependencies": {
    "@astrojs/check": "^0.9.4",
    "@astrojs/sitemap": "^3.2.1",
    "astro": "^5.0.1",
    "astro-robots": "^2.3.0",
    "astro-svgs": "^1.2.1"
  }
}
```

In this way, astro-svgs will be able to verify the SymbolId of a valid icon smoothly with the support of astro check. Not only that, but while I may be annoyed by this check on a daily basis, I always feel that with a check, the TS code will be more flawless (for a novice TypeScript developer)

### Link to Minimal Reproducible Example

null

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
There is no longer a TypeScript question in create-astro because it now always enables TypeScript. The previous behavior was misleading, because Astro still used TypeScript even when it wasn't enabled. 

The reason we no longer enable astro check by default is because it was often confusing. Errors were not reported in development and then would fail during build, and people would think it was a build error when it's actually a type error.

**Comment by JakiChen** [comment]
@ascorbic， Thanks for your feedback.

I'm curious if Astro Check will be deprecated in 5.0+ and beyond, or is there a possibility that we will be able to choose whether or not to enable Astro Check when creating a project through the wizard so that users can really enjoy the experience of each tool?
