### ISSUE TITLE
Content collections can't retrieve entries since Astro 5.0 during testing

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#12612]
### Astro Info

```block
Astro                    v5.0.1
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

When a project is built using the Astro API during testing, all content is missing.

### What's the expected result?

Content remains accessible.

### Link to Minimal Reproducible Example

Blog template with a vitest test added:
https://stackblitz.com/edit/github-ljhqod?file=content.test.ts
```
npm exec vitest --run content.test.ts
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I am not sure I understand what you mean with "content accessibile", can you help me? 

I ran the test you provided, but there were errors because there weren't any tests. I don't know what to test.

**Comment by lilnasy** [comment]
`getCollection()` returns an empty array, giving access to no content, which you can see if you preview the project.

Vitest is just there to create a testing environment for the build command.

**Comment by ematipico** [comment]
I can't reproduce the issue using the reproduction. I logged the blog collection in both places and I could see data

**Comment by ematipico** [comment]
I can reproduce the issue. I was running `npm run dev` before running the vitest command

**Comment by lilnasy** [comment]
@ascorbic It might help you to know that it comes down to this line:

https://github.com/withastro/astro/blob/350b3da9cf1ebf6fa165566deab53d19feadf8e8/packages/astro/src/content/vite-plugin-content-virtual-mod.ts#L59

Production and dev are not the only two states vite may be in.

**Comment by ascorbic** [comment]
It certainly does help, thanks!
