### ISSUE TITLE
@ts-check doubles in astro.config.js

### ISSUE THREAD

**Issue by mckoda09** [withastro/astro#12624]
### Astro Info

```block
Astro                    v5.0.2
Node                     v23.1.0
System                   Linux (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When you run `bun create astro`, it writes in astro.config.js this:
```js
// @ts-check
// @ts-check
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({});
```

### What's the expected result?

Expected to see `@ts-check` only once

### Link to Minimal Reproducible Example

cant produce

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I can't reproduce this. I don't see any double `ts-check` with `bun create astro`.

**Comment by mckoda09** [comment]
@bluwy can i reproduce it and push to github? ill provide all steps in readme.md

**Comment by bluwy** [comment]
Fine by me. But it looks like this relies on a specific output of the `bun create` command, so the steps to reproduce this would be crucial to trace the issue instead of a final repo output.

Also, does this happen with `npm create`? Could this be a bun-specific issue only?

**Comment by mckoda09** [comment]
ill try with npm create

**Comment by mckoda09** [comment]
it is fixed now wtf
i've just tried to create a new project, but the creation process was diffrent. now i see only one `@ts-check` in the config.
