### ISSUE TITLE
Copy to clipboard doesn't work

### ISSUE THREAD

**Issue by jamesli2021** [withastro/astro#12639]
### Astro Info

```block
Astro                    v5.0.2
Node                     v22.12.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
```

### Describe the Bug

When running npx astro info and pressing the Enter button without the Y key, it says 'yes,' but nothing is copied to the clipboard.

npx astro info
Astro                    v5.0.2
Node                     v22.12.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind

✔ Copy to clipboard? … yes

### What's the expected result?

Should be copied.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
Reproduced locally in iTerm, Terminal.app and VS Code

**Comment by jurajkapsz** [comment]
Yup, it actually never worked for me neither, also with Astro `v4.x`. I have:

```txt
Astro                    v5.0.2
Node                     v22.11.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/node
Integrations             @astrojs/mdx
                         build/images
                         build/cleanup
                         @astrojs/sitemap
```

In my case, it bails out with the [catch](https://github.com/withastro/astro/blob/main/packages/astro/src/cli/info/index.ts#L78-L81):

**Comment by jurajkapsz** [comment]
I've logged out the [command](https://github.com/withastro/astro/blob/main/packages/astro/src/cli/info/index.ts#L84) value:

```txt
xclip -sel clipboard -l 1
```

**Comment by ascorbic** [comment]
I think stdin isn't working with `execSync`. I have a PR that switches to `spawnSync` which works on Mac. I've also added tests, so I'm waiting for them to run to see if it works on other platforms.

**Comment by jurajkapsz** [comment]
Updated to `v5.0.3`, on choosing `yes`, the clipboard does not exit to prompt.

```txt
Astro                    v5.0.3
Node                     v22.11.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/node
Integrations             @astrojs/mdx
                         build/images
                         build/cleanup
                         @astrojs/sitemap
```

![image](https://github.com/user-attachments/assets/9bdc800b-774d-40c8-b6f1-8c1adcbeef0f)

Should I create a new issue?

**Comment by jurajkapsz** [comment]
Also, didn't get a copy in clipboard, but probably it doesn't work for linux.

**Comment by ascorbic** [comment]
Oh dear, that's not expected. It should work, but relies on having `x-clip` or `wp-copy` available. It should handle it gracefully if they're not available though.

**Comment by jurajkapsz** [comment]
I have `xclip`, not sure if I had to install it manually in the past though.

**Comment by jurajkapsz** [comment]
Actually, I could try to have a look at the code, as I have the problematic env.

**Comment by ascorbic** [comment]
That would be a great help if you could. I don't have access to a desktop Linux system at the moment.

**Comment by jurajkapsz** [comment]
Great, I am on it.

**Comment by jurajkapsz** [comment]
@ascorbic I made PR #12658 with found solution but I am not sure how it works with other OS-es/utils.
