### ISSUE TITLE
MD frontmatters requires new line prefix to work on Astro version 5

### ISSUE THREAD

**Issue by kyjovskym** [withastro/astro#12656]
### Astro Info

```block
Astro                    v5.0.3
Node                     v20.17.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When using MD files in Astro, each frontmatter must be prefixed by a newline (ignore the whitespace - it is being used just by demonstration purpose):

```astro
 
---
layout: ../../layouts/MarkdownPostLayout.astro
title: 'My First Blog Post'
pubDate: 2022-07-01
---
```
otherwise, the frontmatter is displayed on the website as a concatenated string:

![Screenshot 2024-12-05 at 21 32 36](https://github.com/user-attachments/assets/2f06fee4-39d2-44da-bb3d-436a2c538e49)

In the attached StackBlitz, I was not able to reproduce the issue, so I mocked it by removing the first line of the frontmatter. Nonetheless, we face this problem on Windows and Mac OS environments.

### What's the expected result?

The MD should be processed compatible with the previous version of Astro: The last working version `4.16.17`. I.e. no extra new line prefix is needed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ugal8e?file=src%2Fpages%2Fblog%2Fpost-1.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by artt** [comment]
In your example, it seems like you're missing the beginning `---` in the first line?
I tried adding that and it renders correctly. Or maybe I'm misunderstanding something.

<img width="1177" alt="image" src="https://github.com/user-attachments/assets/213c717b-bfba-4edd-880e-e88a6d2081dc">

**Comment by kyjovskym** [comment]
@artt, Yes, I have prepared that example on purpose with this syntactic error so that I can demonstrate what I see when the frontmatter is syntactically correct on my machine.

**Comment by artt** [comment]
Ah I see. Sorry. Didn't read it carefully.
Does this happen when you start a new project on your machine also? Or is it specific to this project?

**Comment by kyjovskym** [comment]
We discovered this issue yesterday when my colleague started to learn Astro. I copied his repo and reproduced the issue. When I decrease the Astro version to 4.16.17 and below, it works. This is the repository where we are facing the issue: https://github.com/andrejjurco/astro-tutorial

**Comment by bluwy** [comment]
The issue was that the file was encoded in utf8 with bom, which the bom character messes with the frontmatter extraction. I've sent a PR above to fix this.
