### ISSUE TITLE
🐛 BUG: Client-side hydration doesn't work with npm package components

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#1268]
### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

When I use a workspace linked component, it renders just fine on the page.

However, when I use any `client:`directive to hydrate the component, the script URL that gets loaded in the browser is off. Instead of a successful load, I see a 404 for something like: 

```
const [{ default: Component }, { default: hydrate }] = await Promise.all([import("/_astro/file:///Users/fks/Code/astro/packages/components/docs/src/components/ThemeToggleButton.js"), import("/_snowpack/link/packages/renderers/renderer-preact/client.js")]);
```

The issue seems to be that we are loading the component like a source file, instead of as a package. Since this is a workspace, it should be loaded as `/_snowpack/link/...` instead of `/_astro/,,,`.

This isa bit of a tricky Snowpack issue, since it treats these files differently :/

### Steps to Reproduce

1. Clone this repo
2. Checkout the `wip-docs-components` branch
3. `cd examples/docs`
4. `yarn start`
5. Load the site in your browser, notice the 404s.

**Comment by matthewp** [comment]
I believe that is happening because of this: https://github.com/snowpackjs/astro/blob/6c3416ef44c76afc75a89d735f8f39347be0e5a8/packages/astro/src/compiler/codegen/index.ts#L228

**Comment by natemoo-re** [comment]
Going to close this since we switched from Snowpack to Vite in v0.21!
