### ISSUE TITLE
Documented example of remarkPlugins does not work

### ISSUE THREAD

**Issue by jonahbeckford** [withastro/astro#12681]
### Astro Info

```block
Astro                    v5.0.3
Node                     v20.17.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

There is documentation on the Astro site for "Adding remark and rehype plugins" at https://docs.astro.build/en/guides/markdown-content/#adding-remark-and-rehype-plugins

However, I could get neither the remark nor the rehype plugin to affect the Markdown.

### What's the expected result?

I took the Markdown example from https://github.com/remarkjs/remark-toc?tab=readme-ov-file#use and added the `remarkToc` plugin as described in the Astro document.

With the remarkToc plugin I expect to see a table of contents. I don't.

### Link to Minimal Reproducible Example

https://idx.google.com/astro-markdown-bug-9384828

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jonahbeckford** [comment]
The minimal reproduction is linked at https://idx.google.com/astro-markdown-bug-9384828 and was present in the bug report. The minimal reproduction instructions were followed.

Can you not access it?

**Comment by jonahbeckford** [comment]
Separate issue:

I am concerned about how I ended up at Google's Project IDX rather than StackBlitz.

I looked at my browser history and it is clear that the Project IDX link came from Astro. Here are the successive links:

- `https://astro.new/latest/`
- `https://idx.google.com/new?utm_source=astro&utm_medium=astro&utm_campaign=astro&astroTemplate=blog&name=Astro:%20Blog&template=https:%2F%2Fgithub.com%2Fwithastro%2Fastro.new%2Ftree%2Fmain%2F.idx-templates%2Flatest`

And that first https://astro.new/latest/ link comes from the official Astro minimal reproduction page https://astro.new/repro/getting-started/. It sounds like I was subject to an A/B test (A=StackBlitz, B=Project IDX).

Feedback if it was an A/B test: I was auto-signed into a Google account (lucky it was an unimportant one) and apparently tracked in a campaign (see URL above) ... with a) no prompting, b) no consent and c) no warning from Astro that would happen. Please rectify the situation going forward.

**Comment by ascorbic** [comment]
No, we need a Stackblitz repro because IDX links are not sharable. Are you able to see where the link to IDX was on https://astro.new/repro/getting-started/ ? The examples on there are supposed to all use Stackblitz, because that's easiest for sharing reproductions. There don't appear to have been any changes to [the repo](https://github.com/withastro/astro.new) since your report. From what I can see, the only way to get from https://astro.new/repro/getting-started/ to https://astro.new/latest/ is by clicking the home link, which would take you to the root of astro.new. If you do navigate to https://astro.new/latest/ then you are given the option to choose between IDX, Stackblitz, Gotpod and Codesandbox.

**Comment by jonahbeckford** [comment]
> No, we need a Stackblitz repro because IDX links are not sharable. Are you able to see where the link to IDX was on https://astro.new/repro/getting-started/ ?

On that page, above the fold, there is

> Want more guidance? Read our guide to "Creating minimal reproductions"

Then, on that "Creating minimal reproductions" page there is the first link (the big blue link) "Create a StackBlitz via astro.new". It even repeats the link and says "You can use [link astro.new] to create a new Astro project *with a single click*." (emphasis added).

As of today I can see the default is "Open in IDX" (at least for me).

If the intention was that people would know to click on the drop-down and change it to StackBlitz, especially after a page dedicated to creating minimal reproductions talks about a single click, and if the assumption was that people would know minutiae that IDX and StackBlitz are alternative vendors for Astro (I had never heard of either of them until I filed this report) ... then there is misalignment or miscommunication. Easy to fix. I am glad this wasn't a hijack.

---

I'll recreate it in StackBlitz.
