### ISSUE TITLE
I18n fallbacks break path params in node adapter

### ISSUE THREAD

**Issue by mtwilliams-code** [withastro/astro#12701]
### Astro Info

```block
Astro                    v5.0.3
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When running the node server, all paths with a param and a url that is configured to fall back will fail to capture the param correctly. 

There are at least two issues - both can be fixed with one change I believe, but I need some direction to guide where it should be. 
First the failure is:
```
TypeError: Missing parameter: id
    at getParameter (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/manifest_8Y-hEi58.mjs:25:13)
    at file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/manifest_8Y-hEi58.mjs:32:45
    at Array.map (<anonymous>)
    at getSegment (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/manifest_8Y-hEi58.mjs:32:31)
    at file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/manifest_8Y-hEi58.mjs:42:44
    at Array.map (<anonymous>)
    at Object.generate (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/manifest_8Y-hEi58.mjs:42:27)
    at stringifyParams (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/chunks/_@astrojs-ssr-adapter_DAm4WuN6.mjs:739:16)
    at findPathItemByKey (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/chunks/_@astrojs-ssr-adapter_DAm4WuN6.mjs:879:21)
    at getProps (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/chunks/_@astrojs-ssr-adapter_DAm4WuN6.mjs:1176:29)
```

This can be fixed by only continuing in `getProps` through the 
```
const params = getParams(route, pathname);
const matchedStaticPath = findPathItemByKey(staticPaths, params, route, logger);
```
if there are any matching static paths - that is - adding `if (staticPaths.length === 0) return {}` right before it. ⚠️ I have not tested this with a static deployment, but my reading of the code indicates these are unused anyway unless there are matching static paths, so I think it should work ⚠️ 

I tested this solution and another error occurred I need additional direction for:

The differences between the dev server and the node server make it difficult for me to ascertain where it is expected for this to be solved, but `getParams` in `packages/astro/src/core/render/params-and-props.ts` is receiving the routeData for the route it is falling back to and the original, localized pathname. That is:
```
getParams(
    {
        "route": "/products/[id]",
        "isIndex": false,
        "type": "page",
        "pattern": "^\\/products\\/([^/]+?)\\/?$",
        "segments": [
          [
            {
              "content": "products",
              "dynamic": false,
              "spread": false
            }
          ],
          [
            {
              "content": "id",
              "dynamic": true,
              "spread": false
            }
          ]
        ],
        "params": [
          "id"
        ],
        "component": "src/pages/products/[id].astro",
        "prerender": false,
        "fallbackRoutes": [
          {
            "route": "/es/products/[id]",
            "isIndex": false,
            "type": "fallback",
            "pattern": "^\\/es\\/products\\/([^/]+?)\\/?$",
            "segments": [
              [
                {
                  "content": "es",
                  "dynamic": false,
                  "spread": false
                }
              ],
              [
                {
                  "content": "products",
                  "dynamic": false,
                  "spread": false
                }
              ],
              [
                {
                  "content": "id",
                  "dynamic": true,
                  "spread": false
                }
              ]
            ],
            "params": [
              "id"
            ],
            "component": "src/pages/products/[id].astro",
            "prerender": false,
            "fallbackRoutes": [],
            "distURL": [],
            "origin": "project",
            "_meta": {
              "trailingSlash": "ignore"
            }
          }
        ],
        "distURL": [],
        "origin": "project",
        "_meta": {
          "trailingSlash": "ignore"
        }
      }, "/es/products/1"
)
```

it tries to get the params with `const paramsMatch = route.pattern.exec(decodeURIComponent(pathname));`, but this is using the pattern from the 'falled-back' route with the pathname from the localized one, so doesnt work. Dev and server environments seem to handle i18n fallbacks totally differently - it seems dev returns a full 404 render to the Vite plugin, which then handles falling back by rendering again , whereas Node just calls the render once. 

I dont see The [rewrite in RenderContext.render's lastNext](https://github.com/mtwilliams-code/astro/blob/6f4793656e6c911525c95afa570ca4a19ba11a3c/packages/astro/src/core/render-context.ts#L149) getting called from my logs - perhaps the issue is related to that? Alternatively, do we need to change the pathname like dev does to the fallback pathname?

### What's the expected result?

It should not crash on loading the page and should correctly parse out the param

### Link to Minimal Reproducible Example

https://github.com/mtwilliams-code/astro-sir-i18n-params-repro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Can you please explain the bug/bugs? I couldn't understand them from the reproduction, which doesn't seem to be **minimal**

**Comment by mtwilliams-code** [comment]
Sorry about that - I forgot to copy paste the actual instructions. - the repro is just the SSR example modified to use the i18n routing with fallback, an adjustment to display the locale, and a button to switch the locale for ease of reproduction. The issue doesnt occur in dev, but does in the node adapter. Also changed default port cuz I had something else running. 
To repro:
1. `npm i && npm run build`
2. `npm run server`
3. open [http://localhost:4444](http://localhost:4444). Notice it is rendering correctly and you can see the locale in the title
4. click the "toggleLanguage" button to see path change and the locale change in the header to 'es' - i18n config is working.
5. Click on toggle language again to go back to english
6. click on any of the products, or navigate to http://localhost:4444/products/1. You should see the English version work correctly
7. click on the "toggle language" button, or navigate to http://localhost:4444/es/products/1. The request will fail and the node server will have a log `TypeError: Missing parameter: id`
