### ISSUE TITLE
Allow @types/react of version 19

### ISSUE THREAD

**Issue by IvanUkhov** [withastro/astro#12713]
### Astro Info

```block
Astro                    v4.16.12
Node                     v20.18.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### Describe the Bug

There is a new major version of `@types/react`, which `@astro/react` does not allow, making it difficult to combine with other packages.

### What's the expected result?

`@types/react@19` is allowed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-h1s6faky?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Closing because this has been fixed, and released shortly https://github.com/withastro/astro/pull/12678

**Comment by IvanUkhov** [comment]
Apologies. Thank you!
