### ISSUE TITLE
BUG: Search parameters with an .md extension break astro

### ISSUE THREAD

**Issue by alarbada** [withastro/astro#12711]
### Astro Info

```block
Astro                    v5.0.4
Node                     v21.1.0
System                   Linux (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When a page has a search parameter with a value that has a '.md' suffix, astro breaks:

![image](https://github.com/user-attachments/assets/4abf0375-bb21-407a-ac19-c69ea0eb40e4)

This doesn't happen with other file extensions (as far as I've tested), only with '.md' files.

To reproduce locally, go clone this repo:
https://github.com/alarbada/astro-bug

install dependencies and go to 'http://localhost:4321/my/page?page=hello.md'. It will fail.

### What's the expected result?

Astro showing the corresponding page.

### Link to Minimal Reproducible Example

https://github.com/alarbada/astro-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@alarbada can you update your reproduction? You can't have a on-demand page (`prerender = false`) without an adapter.

**Comment by ascorbic** [comment]
@ematipico I've reproduced it using dev

**Comment by alarbada** [comment]
Nice thank you very much!
