### ISSUE TITLE
Buffer not found when using msgpack-lite in production build

### ISSUE THREAD

**Issue by anonymous-0545** [withastro/astro#12717]
### Astro Info

```block
Astro                    v5.0.3
Node                     v23.1.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
                         astro-purgecss
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

## Description
The `msgpack-lite` library works correctly in development but fails in the production build with a "Cannot read properties of undefined (reading 'Buffer')" error.

## Error Message
```js
ViewersGrid.astro_astro_type_script_index_0_lang.BIjkZuiz.js:3832 Uncaught TypeError: Cannot read properties of undefined (reading 'Buffer')
    at E_ (ViewersGrid.astro_astro_type_script_index_0_lang.BIjkZuiz.js:3832:65274)
```

## Details
The error occurs in the minified production build where the code looks like:
```js
function E_() {
    if (sc)
        return bi;
    sc = 1,
    bi = i(typeof Buffer < "u" && Buffer) || i(bi.Buffer) || i(typeof window < "u" && window.Buffer) || bi.Buffer;
    function i(e) {
        return e && e.isBuffer && e
    }
    return bi
}
```

This corresponds to the following source code in development:
```js
// node_modules/msgpack-lite/lib/buffer-global.js
var require_buffer_global = __commonJS({
  "node_modules/msgpack-lite/lib/buffer-global.js"(exports, module) {
    module.exports = c("undefined" !== typeof Buffer && Buffer) || c(exports.Buffer) || c("undefined" !== typeof window && window.Buffer) || exports.Buffer;
    function c(B) {
      return B && B.isBuffer && B;
    }
  }
});
```

## Environment
- Development: ✅ Works
- Production Build: ❌ Fails

### What's the expected result?

It should be loaded as expected. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zm7nbaeo?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
I can't reproduce this. Your repro builds fine for me. Can you check and update the instructions so that we can reproduce it.

**Comment by anonymous-0545** [comment]
> I can't reproduce this. Your repro builds fine for me. Can you check and update the instructions so that we can reproduce it.

Hello, thank you so much for the prompt response. I think I was not clear enough, build and serve don't have an issue but if you open the console you can see the error on the repro. I'm not using any functionality of the library on repro, just importing it on the index page but it fails on the runtime of the build. Here is the error on the runtime of the repro code (visible on the console):

```
index.astro_astro_type_script_index_0_lang.BRafoyqh.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'Buffer')
    at me (index.astro_astro_type_script_index_0_lang.BRafoyqh.js:1:119)
    at index.astro_astro_type_script_index_0_lang.BRafoyqh.js:1:3792
    at H (index.astro_astro_type_script_index_0_lang.BRafoyqh.js:1:4784)
    at Sr (index.astro_astro_type_script_index_0_lang.BRafoyqh.js:1:4856)
    at Nr (index.astro_astro_type_script_index_0_lang.BRafoyqh.js:1:15473)
    at be (index.astro_astro_type_script_index_0_lang.BRafoyqh.js:1:18519)
    at Ae (index.astro_astro_type_script_index_0_lang.BRafoyqh.js:1:18872)
    at Ye (index.astro_astro_type_script_index_0_lang.BRafoyqh.js:22:2083)
    at index.astro_astro_type_script_index_0_lang.BRafoyqh.js:22:2215
```


Please let me know if I can make any further clarifications.

**Comment by ascorbic** [comment]
It looks like it's related to how the library is trying to load `Buffer`. It looks like Vite is getting in a mess when minifying this code: 
https://github.com/kawanet/msgpack-lite/blob/master/lib/buffer-global.js#L3-L7
It works in dev because it's not minified. There may be some Vite settings you could use to fix this but I'm not sure. I tried a couple of things without much luck. It comes down to the fact that this is a really old library that isn't playing nicely with a modern bundler.

**Comment by anonymous-0545** [comment]
I see, I didn't notice that is not actively maintained and migrated to tiny-msgpack same issue probably because it is a fork of it. I will create an issue in [tiny-msgpack](https://github.com/JoshuaWise/tiny-msgpack) to see if we can find a solution there.

**Comment by anonymous-0545** [comment]
I see, I didn't notice that is not actively maintained and migrated to tiny-msgpack, and the issue is resolved, thanks.
