### ISSUE TITLE
Site built with 5.0.0.beta12, but doesn't with 5.0.5

### ISSUE THREAD

**Issue by tarasis** [withastro/astro#12738]
### Astro Info

```block
So using Node 23.4.0, on macOS 15.2. The site I was previously building fine with 5.0.0.beta12 in now failing with Astro 5.0.5 and I don't know why. The error isn't helpful enough
```

### Describe the Bug

So using Node 23.4.0, on macOS 15.2. The site I was previously building fine with 5.0.0.beta12 in now failing with Astro 5.0.5 and I don't know why. The error isn't helpful enough

```
14:07:18 [content] Clearing content store
terminated
  Stack trace:
    at Fetch.onAborted (node:internal/deps/undici/undici:11106:53)
    at Fetch.terminate (node:internal/deps/undici/undici:10264:14)
    at Request.onError (node:internal/deps/undici/undici:2094:31)
    at TLSSocket.<anonymous> (node:internal/deps/undici/undici:6312:16)
    at node:net:351:12
  Caused by:
  other side closed
    at TLSSocket.<anonymous> (node:internal/deps/undici/undici:6287:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
```

### What's the expected result?

The site builds, or a more useful error message so I can debug

### Link to Minimal Reproducible Example

https://github.com/tarasis/tarasis.net/tree/v5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
We don't support Node.js v23, we discourage odd Node.js versions. More can be found here:

https://docs.astro.build/en/upgrade-astro/#nodejs-support-and-upgrade-policies

**Comment by tarasis** [comment]
Noted, thank you. Interestingly it is building again with 5.0.9
