### ISSUE TITLE
[Astro 5] invoking "await Astro.slots.render('default')" removes slotted script tags from rendered page 

### ISSUE THREAD

**Issue by david-hodgetts** [withastro/astro#12747]
### Astro Info

```block
Astro                    v5.0.6
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Invoking **await Astro.slots.render("default")** in an Astro component's frontmatter section, results in the removal of script tags present in the component's slot from the rendered page.

### What's the expected result?

Invoking **await Astro.slots.render("default")** should not provoke any side effect on the structure of the rendered page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nbcunqcz?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
You either render the slot with `<slot />` or render via `Astro.slots.render('default')`. 

In you use case, you render it via `Astro.slots.render('default')`, which means, you must render it, but you don't. In fact, `slotContent` is unused. 

Adding `<Fragment set:html={slotContent} />` works. 

More here: https://docs.astro.build/en/reference/astro-syntax/#astroslotsrender
