### ISSUE TITLE
Content-Type was not one of "multipart/form-data" or "application/x-www-form-urlencoded" for <Form> POST

### ISSUE THREAD

**Issue by jeffscottward** [withastro/astro#12741]
### Astro Info

```block
Astro                    v5.0.3
Node                     v20.17.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

Attempting to do a simple form post results in this error.

```sh
16:56:31 [ERROR] Content-Type was not one of "multipart/form-data" or "application/x-www-form-urlencoded".
  Stack trace:
    at node:internal/deps/undici/undici:5426:19
    at consumeBody (node:internal/deps/undici/undici:5460:9)
    at /Users/jeffscottward/Desktop/dump/astroblog-reference/src/pages/index.astro:11:40
    [...] See full stack trace in the browser, or rerun with --verbose.
16:56:32 [404] /service-worker.js 2ms
```

I followed this guide in an isolated brand new Astro project (the Blog template), and I used exactly these instructions.

https://docs.astro.build/en/guides/astro-db/#insert

I have the bare bones boilerplate with the error here.
(make sure to update to your own turso to test)

https://github.com/jeffscottward/astroblog-reference

### What's the expected result?

A successful POST request with no errors.

### Link to Minimal Reproducible Example

https://github.com/jeffscottward/astroblog-reference

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I can't access the repository. Please use stackblitz

**Comment by jeffscottward** [comment]
> I can't access the repository. Please use stackblitz

Apologies I didn’t realize that it was private. I’ve changed it to public now. I haven’t used stackblitz, but I would assume you can just clone a GitHub public repo into it. @ematipico

**Comment by jeffscottward** [comment]
I got it working finally. 
`export const prerender = false;` in the top route /page. Can't put it a child component. Which I suppose does make sense but then the colocation of logic is broken.
