### ISSUE TITLE
can not install astro

### ISSUE THREAD

**Issue by TeresaMini** [withastro/astro#12743]
### Astro Info

```block
node 18.20
mac m3
进行的操作有nvm use 18;npm create astro@latest;npm install astro失败
```

### If this issue only occurs in one browser, which browser is a problem?

暂无

### Describe the Bug

<img width="539" alt="image" src="https://github.com/user-attachments/assets/8b147d94-2f9e-4fbe-8791-a5bddd2d8c4c" />

### What's the expected result?

无法安装依赖以及运行项目

### Link to Minimal Reproducible Example

暂无

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
This looks like a network issue, related to your connection to npm. Are you able to install other npm packages? If you are in China, perhaps this is a GFW issue.

**Comment by TeresaMini** [comment]
> This looks like a network issue, related to your connection to npm. Are you able to install other npm packages? If you are in China, perhaps this is a GFW issue.

maybe because of GFW, i'll check on next Monday
