### ISSUE TITLE
Duplicate slugs does not throw error

### ISSUE THREAD

**Issue by mvsoom** [withastro/astro#12788]
### Astro Info

```block
Astro                    v5.0.0-beta.12
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/preact
```

### Describe the Bug

Using the Astro tutorial on the content collections branch.

If I set the `slug` in the frontmatter of `post-1.md` and `post-2.md` to identical values (`post-A` in the MRE), the second post disappears from the `/blog` index page.

### What's the expected result?

Loud error from Astro complaining about identical slugs.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bew6ny4w?file=src%2Fblog%2Fpost-2.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mvsoom** [comment]
There is an error page for this error: https://docs.astro.build/en/reference/errors/duplicate-content-entry-slug-error/

**Comment by ematipico** [comment]
@mvsoom, the slug isn't part of the new content layer. The unique identifier of each entry is now `id`, so you need to define `slug` it in your schema, and make it unique via zod.

**Comment by mvsoom** [comment]
OK, thank you. But as `slug` is a magic way to way to override `id`, and the latter must be unique, isn't it better to validate this automatically?

**Comment by ematipico** [comment]
No, `slug` isn't a way to override `id`. Maybe it was true for the **old content collections**, but it was a mistake in our design. In the content layer, there's just one unique field, which is `id`. 

If you need `slug` in your collection *via content layer*, you must define it and do the validation yourself.

**Comment by filipesmedeiros** [comment]
Hello @ematipico. I truly believe that @mvsoom is correct: es/content-collections/#defining-custom-ids

Astro does use the `slug` property to override the `id` property.
I, too, had the problem of multiple items having the same `slug` property (and, thus, the same `id`) and no error being thrown.

A content file with frontmatter

```
---
slug: a-beleza-da-palavra-escrital
---
```

Will produce the JSON `{id: 'a-beleza-da-palavra-escrital', ...` when doing a `getCollection`.
