### ISSUE TITLE
The collection does not exist or is empty, even it's already existed on the file system on Windows

### ISSUE THREAD

**Issue by EslaMx7** [withastro/astro#12784]
### Astro Info

```block
Astro                    v5.0.9
Node                     v20.12.2
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I tried two themes (portfolio, blog) both having the same empty collection warnings even if the filesystem already contains `.md` files inside a folder with the collection name.
also there is a `content.config.ts` file with the following contents:

```
import { glob } from 'astro/loaders';
import { defineCollection, z } from 'astro:content';

export const collections = {
	work: defineCollection({
		// Load Markdown files in the src/content/work directory.
		loader: glob({ base: './src/content/work', pattern: '**/*.md', }),
		schema: z.object({
			title: z.string(),
			description: z.string(),
			publishDate: z.coerce.date(),
			tags: z.array(z.string()),
			img: z.string(),
			img_alt: z.string().optional(),
		}),
	}),
};

```

Used Commands:

```
D:\Playground> cd .\astro-profile\
D:\Playground\astro-profile> npm create astro@latest -- --template=portfolio

 astro   Launch sequence initiated.

   dir   Where should we create your new project?
         .
      ◼  tmpl Using portfolio as project template

  deps   Install dependencies?
         Yes

   git   Initialize a new git repository?
         Yes

      ✔  Project initialized!
         ■ Template copied
         ■ Dependencies installed
         ■ Git initialized

  next   Liftoff confirmed. Explore your project!
         Run npm run dev to start the dev server. CTRL+C to stop.
         Add frameworks like react or tailwind using astro add.

         Stuck? Join us at https://astro.build/chat


D:\Playground\astro-profile [master +0 ~1 -0 !]> npm run dev

> dev
> astro dev

12:18:18 [types] Generated 1ms

 astro  v5.0.9 ready in 104 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

12:18:19 watching for file changes...
The collection "work" does not exist or is empty. Ensure a collection directory with this name exists.
12:18:20 [200] /work/ 29ms
The collection "work" does not exist or is empty. Ensure a collection directory with this name exists.
12:18:21 [200] /work/ 5ms
12:18:42 [200] /about/ 12ms
The collection "work" does not exist or is empty. Ensure a collection directory with this name exists.
12:18:43 [200] /work/ 10ms
```

### What's the expected result?

1. No empty collections warnings
2. View the collection contents on the parent page.

### Link to Minimal Reproducible Example

N/A

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by wxiaoyun** [comment]
Facing the same problem here

**Comment by sceee** [comment]
Upgrade to astro 5.1.1 (previously 5.0.9) / `@astrojs/mdx` 4.0.3 (previously 4.0.2) and deleting the `.astro` directory fixed it for me.

**Comment by mystica2000** [comment]
> Upgrade to astro 5.1.1 (previously 5.0.9) / `@astrojs/mdx` 4.0.3 (previously 4.0.2) and deleting the `.astro` directory fixed it for me.

it works for me on dev `npm run dev`, not on build `npm run build` on windows.

**Comment by jacob-armiger** [comment]
I seem to also be getting this issue on Mac

**Comment by TimWitzdam** [comment]
> Upgrade to astro 5.1.1 (previously 5.0.9) / `@astrojs/mdx` 4.0.3 (previously 4.0.2) and deleting the `.astro` directory fixed it for me.

Deleting the .astro directory also solved the issue for me.

**Comment by HawtinZeng** [comment]
> > Upgrade to astro 5.1.1 (previously 5.0.9) / `@astrojs/mdx` 4.0.3 (previously 4.0.2) and deleting the `.astro` directory fixed it for me.
> 
> it works for me on dev `npm run dev`, not on build `npm run build` on windows.

Me too
