### ISSUE TITLE
Esbuild 0.24.1 cause astro build to fail

### ISSUE THREAD

**Issue by leochiu-a** [withastro/astro#12797]
### Astro Info

```block
Astro                    v5.0.9
Node                     v23.3.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

The latest version of `esbuild@0.24.1` causes `astro build` to fail. After changing the `esbuild` version to 0.24.0, everything works fine.

```
Expected identifier but found "import"
  Location:
    (define name):1:0
  Stack trace:
    at failureErrorWithLog (/solar-singularity/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:1476:15)
    at responseCallbacks.<computed> (/solar-singularity/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:622:9)
    at Socket.readFromStdout (/solar-singularity/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:600:7)
    at addChunk (node:internal/streams/readable:559:12)
    at Readable.push (node:internal/streams/readable:390:5)
 ELIFECYCLE  Command failed with exit code 1.
```

### What's the expected result?

`astro build` successfully.

### Link to Minimal Reproducible Example

https://github.com/leochiu-a/astro-practice

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by utkarshkukreti** [comment]
https://github.com/evanw/esbuild/issues/4010

**Comment by SerkanSipahi** [comment]
@leochiu-a I can confirm this error. I have the same error message.

**Comment by rlarreasanchez** [comment]
I have the same error in a blank Astro 5.1 project, with no added dependencies, just creating the basic project and then running the build.

**Comment by prth** [comment]
Facing same issue ^

On astro project level, can address the problem temporarily by overriding the version. 

I couldn't override version of `esbuild` using `npm (10.9.0)`
I had to switch to using `pnpm (9.15.1)` package manager to override the `esbuild` dependency version to 0.24.0

```
"pnpm": {
    "overrides": {
      "esbuild": "0.24.0"
    }
  }
```
