### ISSUE TITLE
Using `Astro.rewrite` after a form action modifies the URL

### ISSUE THREAD

**Issue by romanstetsyk** [withastro/astro#12794]
### Astro Info

```block
Astro                    v5.1.0
Node                     v22.11.0
System                   macOS (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

Using `Astro.rewrite` after a form action modifies the URL and refreshing the page doesn't clear the action result, as shown on the screen recording.

https://github.com/user-attachments/assets/5e07be1b-d1b9-480b-a069-b383b9c58b29

### What's the expected result?

I expected it to work the same way as in Astro 4 as shown below

https://github.com/user-attachments/assets/32f9dbe8-5454-489f-b58e-7932aa691f6f

### Link to Minimal Reproducible Example

https://github.com/romanstetsyk/astro-form-action

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
Hi. This is expected. Astro Actions no longer include default middleware for redirects that remove the query param. See https://docs.astro.build/en/guides/upgrade-to/v5/#changed-actions-submitted-by-html-forms-no-longer-use-cookie-redirects
