### ISSUE TITLE
False empty collection error

### ISSUE THREAD

**Issue by jacob-armiger** [withastro/astro#12809]
### Astro Info

```block
Astro                    v5.1.1
Node                     v23.3.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/vercel
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

Calling `getCollection('projects')` for my "projects" collection returns 
```
The collection "projects" does not exist or is empty. Ensure a collection directory with this name exists.
```

This occurred some time after using `pnpm dlx @astrojs/upgrade` to upgrade from Astro 4 to 5. The error was occurring for both of my collections, but it seems one of them started working again once I used `pnpm run dev` instead of `pnpm dev`

### What's the expected result?

I expect to receive the collection since I have the scheme defined in `content.config.ts` and `md` files in my `projects` folder.

### Link to Minimal Reproducible Example

NA

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by SamuNatsu** [comment]
How do you solve that? I faced the same problem.
