### ISSUE TITLE
🐛 [Bug] v5.1.1 - Can't load the middleware.

### ISSUE THREAD

**Issue by JakiChen** [withastro/astro#12819]
### Astro Info

```block
Astro                    v5.1.1
Node                     v20.18.0
System                   macOS (x64)
Package Manager          yarn
Output                   server
Adapter                  @astrojs/vercel
Integrations             astro-favicons
                         @storyblok/astro
                         astro-robots
                         @astrojs/sitemap
```

### Describe the Bug

The issue occurs when `astro-favicons` are a development dependency, but as a dependency, everything works fine.

What causes this?
<img width="682" alt="截屏2024-12-23 22 53 31" src="https://github.com/user-attachments/assets/6c6bbf13-743f-4261-94d4-0e3ff1397a71" />

### What's the expected result?

**The middleware of `astro-favicons` should work fine regardless of whether it is a development dependency or a dependency** Because in "astro": "^4.16.14", complex projects (useful to middleware, restApi, storyblok, etc.) will work fine

### Link to Minimal Reproducible Example

See https://github.com/jakichen/boilerplates-vercel

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dreamstar-enterprises** [comment]
I have the same issue following this example:
https://docs.astro.build/en/guides/middleware/
Middleware just wont load in 5.1.1
