### ISSUE TITLE
SVG doesn't transform

### ISSUE THREAD

**Issue by dreamstar-enterprises** [withastro/astro#12842]
### Astro Info

```block
npm view astro version
5.1.1

The command 'astro info' does not work for me on a mac!
```

### Describe the Bug

 does not flip the direction of a chevron

```
import Chevron from "../assets/svgs/chevron.svg"; 
<Chevron class="h-4 w-4 -scale-y-1"/>
```

### What's the expected result?

should do tranform

### Link to Minimal Reproducible Example

https://stackexamplegivenabove

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wildfiremedia** [comment]
`npx astro info` we use `npx`.

**Comment by dreamstar-enterprises** [comment]
Ok, but the bug is still there. 
-scale-y-1 does not work. (but rotate-180 does!)

**Comment by lameuler** [comment]
`-scale-y-1` isn't a valid Tailwind utility class, have you tried with `-scale-y-100` instead?

https://tailwindcss.com/docs/scale

**Comment by dreamstar-enterprises** [comment]
My apologies. I was looking at the native CSS column on the right. The tailwind column on the left -scale-y-100 did work. 
Closing issue
