### ISSUE TITLE
Cross-site POST form submissions are forbidden

### ISSUE THREAD

**Issue by wildfiremedia** [withastro/astro#12851]
### Astro Info

```block
Astro                    v5.1.1
Node                     v22.12.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
```

### Describe the Bug

In transition from 4.x to 5.x, I found I could not submit the form when testing in `npx astro preview` after the build, on macOS. Is it something we need to disable CORS?

Submit a form to the same origin threw `Cross-site POST form submissions are forbidden` which is weird.

### What's the expected result?

Tested on `localhost:8080` should continue to work as expected in 5.x?

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Lippiece** [comment]
This is really painful. I needed a quick MVP and can't deploy it on Render because the app refuses to perform POST requests to itself. 

All I found is the exact same message in Svelte Kit. How can we disable this behaviour here?

**Comment by wildfiremedia** [comment]
Just discovered I need to disable this check when running `preview` and it work!


asstro.config.mjs
```
security: {
    checkOrigin: false
  }`
```

**Comment by wildfiremedia** [comment]
@Lippiece Worth reading :)
https://docs.astro.build/en/reference/configuration-reference/#security

**Comment by Daniel15** [comment]
If anyone still hits this error, you can fix it by setting `security.allowedDomains` in your astro config.
```
  security: {
    // Trust nginx's X-Forwarded-* headers when they resolve to our domains.
    allowedDomains: [
      {hostname: 'example.com', protocol: 'https'},
    ],
  },
```

I know this issue is old, but it's still in the first page of Google results for "Cross-site POST form submissions are forbidden"
