### ISSUE TITLE
View Transitions - Docs could be clearer about where to attach the transition directive

### ISSUE THREAD

**Issue by dreamstar-enterprises** [withastro/astro#12859]
### Astro Info

```block
5.1.1.
```

### Describe the Bug

I think the docs could be clearer about this. 
For example:

This works

```
<!--footer-->
<footer class="mt-auto bg-theme-selected-footer-background" transition:persist>
```

But if I take the transition:persist and put it in the Astro component (i.e. the wrapper), it does not work

`<Footer transistion:persist />`

Perhaps not a bug, but if not, docs could be a little bit clearer

### What's the expected result?

See above

### Link to Minimal Reproducible Example

seeabove

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @dreamstar-enterprises 👋🏼, yes! 

If the Footer component does not handle `transition:persist`, it will just be ignored.

Would you please open a PR on the docs repository to improve the docs?
