### ISSUE TITLE
🐛 BUG: Bad JSON passed to Markdown via content prop causes a confusing `astro build` compiler error

### ISSUE THREAD

**Issue by trevormunoz** [withastro/astro#1334]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I am hitting a bug when I try to run `astro build` (Throughout everything described `astro dev` works just fine so I was humming along building the site and only encountered this problem when I went to build/publish.) 

To be honest I'm not exactly sure where things are tripping up—it might have to do with dynamic routes (those are the pages where the build chokes and stops) but I'm also importing wads of JSON data to build pages with and that seems to make a difference in the code sandbox below (`people.json` vs. `people-full.json`).

### Steps to Reproduce

1. `npm init astro` using template minimal
2. Add just enough layouts, components, data to [recreate the failure](https://codesandbox.io/s/youthful-phoebe-6d10e)
2. `npm run build` | `astro build`
3. I expected Astro to build all the pages of the site … instead the build stops and fails partway through while processing dynamic route pages
```
[build] Unable to render src/pages/people/[person].astro

Error: __astro_slot encountered an unexpected child:
    at file:///sandbox/src/pages/people/[person].astro
undefined
    at __astro_slot (/_snowpack/pkg/astro.dist.internal.__astro_slot.v0.20.4.js:11:11)
    at Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.20.4.js:47:12)
    at async Promise.all (index 0)
    at async Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.20.4.js:45:20)
    at async Promise.all (index 0)
    at async Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.20.4.js:45:20)
    at async Promise.all (index 0)
    at async Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.20.4.js:45:20)

[build] ✕ building pages failed!
```

### Link to Minimal Reproducible Example (Optional)

https://codesandbox.io/s/youthful-phoebe-6d10e

**Comment by trevormunoz** [comment]
Nevermind. The root cause turned out to be my own silly error in the frontmatter script.

**Comment by trevormunoz** [comment]
So, this may not have been such a simple self-own as I thought. In trying to update the minimal reproduction above (and also get my local code fully working), I hit another roadblock.

Even with the issue of trying to access an undefined variable's attribute fixed, the use of the Astro Markdown component ([here](https://gist.github.com/trevormunoz/7ef206c1ab69f33b4a2e7b26d4537e18#file-person-astro-L37) in the original version of the component before debugging the undefined variable bit) seems to be causing problems now?

An [updated version of the reproduction](https://codesandbox.io/s/sharp-bash-9dr5j) above shows this in action: https://9dr5j.sse.codesandbox.io/people/mills-kelly

**Comment by jasikpark** [comment]
I tried to fix the Markdown problem with https://codesandbox.io/s/dreamy-feather-vs7jf?file=/src/pages/people/%5Bperson%5D.astro, via:

```astro
          {personData.bio ? <Fragment><Markdown content={personData.bio} /></Fragment> : ""}
```

but I got this error:

```sh
[access] /people/mills-kelly
[parse-error]

 /sandbox/src/pages/people/[person].astro:37:215

 𝘅 Expected ")" but found ":"

     35 |         </div>
     36 |         <div class="bio">
   > 37 |            {personData.bio ? <Fragment><Markdown content={personData.bio} /></Fragment> : ""}
        |                                      ^
     38 |         </div>
     39 |         <div>
     40 |

(node:65) UnhandledPromiseRejectionWarning: Error: Unable to compile expression
    at compileExpression (file:///sandbox/node_modules/astro/dist/compiler/codegen/index.js:223:11)
    at async Object.enter (file:///sandbox/node_modules/astro/dist/compiler/codegen/index.js:479:24)
    at async AsyncWalker.visit (file:///sandbox/node_modules/astro/node_modules/estree-walker/src/async.js:49:5)
    at async AsyncWalker.visit (file:///sandbox/node_modules/astro/node_modules/estree-walker/src/async.js:86:6)
    at async AsyncWalker.visit (file:///sandbox/node_modules/astro/node_modules/estree-walker/src/async.js:79:14)
    at async AsyncWalker.visit (file:///sandbox/node_modules/astro/node_modules/estree-walker/src/async.js:79:14)
    at async AsyncWalker.visit (file:///sandbox/node_modules/astro/node_modules/estree-walker/src/async.js:79:14)
    at async AsyncWalker.visit (file:///sandbox/node_modules/astro/node_modules/estree-walker/src/async.js:79:14)
    at async asyncWalk (file:///sandbox/node_modules/astro/node_modules/estree-walker/src/index.js:34:9)
(node:65) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23)
```

**Comment by trevormunoz** [comment]
Could this be related to #1259?

**Comment by jasikpark** [comment]
possibly? 🤔

**Comment by jasikpark** [comment]
Hopefully https://github.com/snowpackjs/astro/pull/1343 sorts it then!

**Comment by trevormunoz** [comment]
I was hopeful that the fixes in v0.20.6 might resolve this but no such luck 😞: https://9dr5j.sse.codesandbox.io/people/mills-kelly

**Comment by trevormunoz** [comment]
Reading the discussion on [another comment in the support channel in Discord](https://discord.com/channels/830184174198718474/845451724738265138/888337159554203678), I also suspected there were newline `\n` characters in the markdown I was receiving and trying to pass into the Markdown component via content prop.

[A new reproduction](https://codesandbox.io/s/shy-sea-cyw1q?file=/src/pages/people/%5Bperson%5D.astro) seems to confirm that the presence of `\n` characters is causing the Markdown component to error out with the not-so-helpful `__astro_slot encountered an unexpected child` error. Replacing `\n` with `<br>` in the incoming markdown as suggested by user pout resolves the build error.

Compare https://cyw1q.sse.codesandbox.io/people/mills-kelly with https://9dr5j.sse.codesandbox.io/people/mills-kelly

cc: @natemoo-re @jasikpark

**Comment by matthewp** [comment]
I think we can call this a confirmed bug, thanks!

**Comment by FredKSchott** [comment]
Closed as not reproducible.
