### ISSUE TITLE
🐛 BUG: pageUrlFormat: 'file' creates `.html` file

### ISSUE THREAD

**Issue by coelmay** [withastro/astro#1338]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Creating dynamic pages e.g `[user].astro` or `/user/[user].astro` when `pageUrlFormat` is set to `file` results in an `.html` file created inside the directory
```
   Pages                
 ┌ /1-bevon-westby/.html
 ├ ....
 ├ /index.html          
 ├ ....
 └ /user/10-zackariah-dallywater/.html
```
When I would have expected
```
   Pages                
 ┌ /1-bevon-westby.html
 ├ ....
 ├ /index.html          
 ├ ....
 └ /user/10-zackariah-dallywater.html
```
**Note:** When running `astro dev` logged URLs are correct e.g.
```
[access] /10-zackariah-dallywater
```
though I am unsure if this is really the case or not as the same is logged irregardless of URL format.

### Steps to Reproduce

1.  git clone https://github.com/coelmay/astro-pageurlformat-bug.git
2. cd astro-pageurlformat-bug
3. yarn
4. yarn build

### Link to Minimal Reproducible Example (Optional)

https://github.com/coelmay/astro-pageurlformat-bug

**Comment by coelmay** [comment]
After a little looking, and testing, I am thinking this is the offending piece of code
https://github.com/snowpackjs/astro/blob/6fc8202e60f666d6d81f69dd812cbdbe138f8f14/packages/astro/src/build/page.ts#L63

If I add `trailingSlash` to `devOptions` in `astro.config.mjs`, page output for build is as expected (see above.)
```javascript
devOptions: {
  trailingSlash: 'never'
},
```

The issue then is according to this, `devOptions` are meant only when running `astro dev`, not `astro build`.
https://github.com/snowpackjs/astro/blob/a923268da2f5ada2f0c02b5bf339daf4a41afa0a/packages/astro/src/%40types/config.ts#L66

**Comment by coelmay** [comment]
For consideration: https://github.com/coelmay/astro/commit/17a8cdce13df4e9aea6dac266363a529c0361db2

Unsure if current [astro-pageDirectoryUrl.test.js](https://github.com/snowpackjs/astro/blob/6fc8202e60f666d6d81f69dd812cbdbe138f8f14/packages/astro/test/astro-pageDirectoryUrl.test.js) should get modified or whether additional test.

Suggest the `preserveIndexes` feature may require input from others who use Astro to gauge viability and whether it should default to `true` or `false`.

**Comment by matthewp** [comment]
Makes sense! I think additional tests for dynamic routes would be helpful here.

**Comment by coelmay** [comment]
> Makes sense! I think additional tests for dynamic routes would be helpful here.

I have an issue in that with my test code (a hack job) everything works fine unless I have `trailingSlash` in `astro.config.mjs` to 'never' or 'always'
ie.
```
devOptions: {
  trailingSlash: 'never'
}
```
- OR -
```
devOptions: {
  trailingSlash: 'always'
}
```

building returns an error
```
[build] Unable to render src/pages/docs/index.astro
 
 Error: No matching route found.
```
But when `trailingSlash` is unset, or set to `'ignore'`, everything works as expected. I have tried looking through the codebase to figure out where/why something in `devOptions` is influencing the production build process, but cannot pinpoint anything. While I can (I believe) put tests together as @matthewp suggested I know there are at least two "real-world" cases where this functionality would still likely fail.
