### ISSUE TITLE
🐛 BUG: Trailing slash of `url.pathname` inconsistent between dev and build

### ISSUE THREAD

**Issue by stephanmax** [withastro/astro#1415]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When logging `Astro.request`’s url property I stumbled upon the behavior that `pathname` does not include a trailing slash, but the build does (which breaks a couple of things I am doing). I do not have set a `trailingSlash` config, mind you, and setting it to `always` makes the `pathname` consistent. Still, I am not sure whether that behavior (inconsistency between dev and build, regardless of the `trailingSlash` config) is intendes.

Also, when fetching Markdown files with `Astro.fetchContent` and paginating them, the returned objects’ `url` property does not include a trailing slash—so if I use that URL to create the link to blog posts on an overview page, it never matches the canonical URL which includes the trailing slash.

Not a show stopper by any means, but a bit of a puzzle to me and maybe the symptom a bigger bug. Thanks for this amazing tool!

### Steps to Reproduce

1. `npm init astro`
2. Create any kind of page
3. Compare `Astro.request`’s url property in dev and build

### Link to Minimal Reproducible Example (Optional)

https://github.com/stephanmax/stephanmax.is/tree/develop

**Comment by jasikpark** [comment]
I can confirm this is still the case as of `v0.21.12`: https://stackblitz.com/github/qgnivmooo?file=README.md

**Comment by jasikpark** [comment]
Looks like canonical url normalization might be related to this? 

https://github.com/withastro/astro/issues/1415

**Comment by IanVS** [comment]
So, I guess it should be this instead, maybe? (I just got bitten by this bug)

```
let pathname = url.replace(/\/index.html$/, '/'); // index.html is not canonical 
```

**Comment by jonathantneal** [comment]
We‘ve had folks reviewing older issues, and @RafidMuhymin was able to let us know this was resolved but never closed, and this was tested locally. `url.pathname` should be consistent with the `trailingSlash` flag.

If for some reason there are still issues, please let us know so we can look back into it.

**Comment by brycewray** [comment]
Is this still happening? Seeing inconsistency between dev and production if `trailingSlash = "always"` is set in `astro.config.mjs`. That's in Astro 1.0.0-beta.12.
