### ISSUE TITLE
🐛 BUG: Loading the HMR dev server port in a browser should redirect you to the correct port

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#1437]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I wish I could always successfully load `localhost:3000` on platforms like Codesandbox and Forestry, where the dev server port is selected based on the first port opened.

Maybe we could just wait to open the HMR port until the dev server is responding?

### Steps to Reproduce

1. https://githubbox.com/snowpackjs/astro/tree/main/examples/minimal
2. See if the dev server successfully gets selected as the correct port - it's a race between `3000` and `11512` 😆

### Link to Minimal Reproducible Example (Optional)

https://githubbox.com/snowpackjs/astro/tree/main/examples/minimal

**Comment by matthewp** [comment]
I don't quite understand, are you saying that if HMR port connects before the dev server then the codesandbox won't work (because its sending http requests to an hmr server)?

**Comment by matthewp** [comment]
Assuming I understand you correctly, I think making HMR wait on dev port does make a bit of sense, but this is also likely going to change with Vite. We should test against the `next` tag.

**Comment by jasikpark** [comment]
> I don't quite understand, are you saying that if HMR port connects before the dev server then the codesandbox won't work (because its sending http requests to an hmr server)?

yep! that's exactly what i'm saying - i don't have any evidence other than the fact that whether it chooses the right port is changes every time, and that's the only info they seem to have. I'm not sure why it serves "Upgrade Required" though

**Comment by natemoo-re** [comment]
Removing the `compiler-v2` tag and moving to a the [v0.22 milestone](https://github.com/snowpackjs/astro/milestone/2).

**Comment by jasikpark** [comment]
I'm not quite sure how we would implement this.. maybe just responding to HTTP requests with a  redirect to the dev server port + normally responding over websockets?

**Comment by jasikpark** [comment]
So basically the HMR server is responding with "I don't talk over https or HTTP, please use WSS or WS"

Maybe we could just setup an HTTP redirect on that port as well?

**Comment by natemoo-re** [comment]
Hmm, interesting thought, thanks for taking a look at this! That would be cool if we could do something like that, but no implementation ideas on my end.

**Comment by jonathantneal** [comment]
Without implementation ideas, we can’t really move forward with this request. I recommend re-opening this as an RFC discussion, and seeking out developers who could help with responding over the HMR port. I could see its usefulness!
