### ISSUE TITLE
📘 DOC: Add options for initializing project with TS, Sass, or SCSS

### ISSUE THREAD

**Issue by jawshoeadan** [withastro/astro#1460]
### Background & Motivation

It isn’t very well documented how to add these features to your project and each of the frameworks Astro renders has a different way of implementing them. It would probably be more convenient to just include that in the setup.

### Possible solutions
Add options to `npm unit astro` for options like TypeScript, Sass, or SCSS similar to asking which frameworks to use
### Alternatives considered
Add documentation to website showing how to do this for each framework
### Risks, downsides, and/or tradeoffs
None
### Detailed Design

Based on the user input, add the different dependencies, snowpack plugins, and template files for each framework to match the user’s preference.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [x] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by drwpow** [comment]
I think we can get on-board with this! I don’t think we need a discussion.

**Comment by jonathantneal** [comment]
We now have https://github.com/withastro/rfcs/discussions

I recommend we move this into a discussion, as those requests are not limited to core. :)

**Comment by jonathantneal** [comment]
I’ve requested this be moved into discussions. I’m closing this out for now, as it seemed to have gone stale.
