### ISSUE TITLE
🐛 BUG: could not find commit hash for HEAD

### ISSUE THREAD

**Issue by urffanfadillah** [withastro/astro#1499]
I'm new to Astro, and when I created a new Astro project, I encountered this problem:
![image](https://user-images.githubusercontent.com/54013237/136142174-3730625d-c327-45a2-957d-bf22a82ebf25.png)
I hope you guys know the solution so what should I do. thank you

**Comment by Mikkel-T** [comment]
Looks like this is a problem with degit. Do you have git installed? That is the only reason I can think of after looking through degits code.

**Comment by Mikkel-T** [comment]
@urffanfadillah can you confirm if you have git installed?

**Comment by jonathantneal** [comment]
Pinging @drwpow for review.

**Comment by jonathantneal** [comment]
Windows issues were resolved a while back, but we hadn’t tracked this one. I’m closing it for now, but I’m open to reviewing this if there is still a problem. Just let us know!
