### ISSUE TITLE
🐛 BUG: "No renderer found for" external Svelte components

### ISSUE THREAD

**Issue by thelucid** [withastro/astro#1514]
### What package manager are you using?

yarn

### What operating system are you using?

macOS

### Describe the Bug

Importing a Svelte component from a node module, that's structured like this: https://github.com/sveltejs/component-template. The error "No renderer found for MyComponent".

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. `yarn add my-component-package`
3. `import { MyComponent } from 'my-component-package'`
4. `yarn dev`
5. `No renderer found for MyComponent`

**Comment by matthewp** [comment]
Can you provide an example of this not working? Hard to debug given there's not an example component that's failing. Creating a reproduction here would be best: https://astro.new/minimal@next?on=stackblitz

**Comment by jack-y** [comment]
I got the same issue.
Using the `framework-svelte` template, I tried to reproduce here : https://stackblitz.com/edit/github-hfgram
Unfortunately this error is fired: 

```
500 Internal Error
Missing "./server.js" export in "@astrojs/renderer-svelte" package
```

**Comment by jack-y** [comment]
### Steps to reproduce on a desktop
 1. Download the svelte template
 
```
mkdir time-picker-astro
cd ./time-picker-astro
npm init astro -- --template framework-svelte
```

2. Add an external Svelte component

```
(in package.json)

"devDependencies": {
  "astro": "^0.20.12",
  "svelte-time-picker": "^1.0.8"
}

(in pages/index.astro)

import TimePicker from 'svelte-time-picker'

...

<main>
  <Counter client:visible>
    <h1>Hello Svelte!</h1>
  </Counter>
  <div style="margin-top: 8rem;"></div>
  <TimePicker />
</main>
```

3. Run the app

```
npm install
npm run dev
```

4. Go to the URL
http://localhost:3000/

Hope it helps.

**Comment by natemoo-re** [comment]
This should be working in the latest cut of `0.21.x`, but please reopen if you're still running into problems.
