### ISSUE TITLE
🐛 BUG: Inline code blocks from markdown pages aren't being stylized by Prism

### ISSUE THREAD

**Issue by henriquehbr** [withastro/astro#1532]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I'm working on a simple blog with markdown posts, most posts contain both fenced code blocks and inline code, the former works fine, but the latter is ignored by Prism, searched on the docs about this but couldn't find anything about how to solve this

Any clue of what i might be doing wrong? Thanks!

### Steps to Reproduce

1. `npm run dev`
2. _voilà_

### Link to Minimal Reproducible Example (Optional)

https://henriquehbr.xyz
https://github.com/henriquehbr/henriquehbr.github.io

**Comment by jasikpark** [comment]
I think only block style codeblocks are highlighted by most highlighting libraries, there's usually not support for inline code block highlighting

**Comment by matthewp** [comment]
I think with `next` we can change this. Prism highlighting is now done via a remark plugin, so presumably that plugin could do this.

**Comment by jasikpark** [comment]
In theory it should be possible to enable [`transformInlineCode`](https://github.com/sergioramos/remark-prism#transforminlinecode) in the remark-prism config.

**Comment by ShivamJoker** [comment]
Hello this is seems to be coming in latest version as well

**Comment by FredKSchott** [comment]
This should be resolved as of Astro v0.24.0. 

If you still can reproduce, please create a reproduction on stackblitz so that maintainers can help debug further!
