### ISSUE TITLE
🐛 BUG: JavaScript broken in Safari 12.1

### ISSUE THREAD

**Issue by ThomasHoadley** [withastro/astro#1535]
### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

I have tested my astro site in Safari 12.1 (Mojave, 2018) and there is a breaking JavaScript error.

The console output is

`Unhandled Promise Rejection: SyntaxError: Unexpected token '?'` - load.js

### Steps to Reproduce

1. Open an astro page which contains a component with client:load e.g. `<Component client:load />`
2. Run `npm run dev`.
3.  Open the page in Safari 12.1 (Mojave, 2018).
4. See console for the JS breaking error.

**Comment by ElianVanCutsem** [comment]
Hmm, maybe you're doing something else wrong. Works fine on my Mojave Install. Any repo that reproduces the issue?

**Comment by radiosilence** [comment]
This seems to be due to the nullish coalescing operator `??`. Changing `target` in `tsconfig.json` doesn't seem to fix, either :S

**Comment by radiosilence** [comment]
Ok, in further investigation this seems to be because esbuild isn't transforming anything or respecting the `target` in tsconfig.json, perhaps because it is an old version.

**Comment by xididri** [comment]
I have the same error despite using [plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) with `Safari >= 11` in the browserlist query.

I also tried to use the option `modernPolyfills: true` but I still get the error on prod (`Unhandled Promise Rejection: SyntaxError: Unexpected token '?'`)

Any idea on how to resolve this?
