### ISSUE TITLE
📘 DOC: Algolia Docsearch results don't discern language

### ISSUE THREAD

**Issue by tbeseda** [withastro/astro#1565]
Algolia search results include results for all languages even if the current user has specified a language from the dropdown. And from the default of "English", multiple languages are included.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/15697/137550085-bf2c0bea-9989-4cad-b712-dfa63793aa92.png">

I believe this can be solved with the "facet" options in Algolia. This includes a meta tag to specify the key ("lang") and value (example: "fr" for French). Then passing the facet filter when initializing algolia.

Meta tag config docs demonstrate the `lang` attribute https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags

Here's how Express inits Algolia https://github.com/expressjs/expressjs.com/blob/c2b8ecf5d9235780917f92995dec4cd9ca22f103/_includes/footer/_docsearch.html but I don't see the meta tag in their source, maybe lang is implicit 🤔 

I will continue to research, looking at how it is done in other doc sites that use docsearch.

**Comment by tbeseda** [comment]
Material-UI uses Algolia docsearch with a few languages with this approach:
[set docsearch:lang to current lang in meta tag](https://github.com/mui-org/material-ui/blob/24015d1e4bdf135ba6c6091141cab2299d824be5/docs/src/modules/components/Head.js#L44)
and set `facetFilters: ['lang:<current lang>']` [when initializing docsearch](https://github.com/mui-org/material-ui/blob/ecd8a7da5c427b90b1b3c29fef10005b1489ba11/docs/src/modules/components/AppSearch.js#L268)

**Comment by jasikpark** [comment]
As a later improvement of this, I really would like to replicate wikipedia’s ui for multi-language search, where they surface results from other languages in a noise-minimal way. https://techblog.wikimedia.org/2021/02/22/in-search-of-the-perfect-search-for-wikipedia/

**Comment by tbeseda** [comment]
Seems like the best approach will be to let Algolia index Astro docs with the new meta tag for lang. Then we can test searching with the [`facetFilters` set like this](https://github.com/snowpackjs/astro/pull/1568/commits/911646a3b842a6cfeaf46e30f5c0a58ea06fd328#diff-4c755b369f155105965f0e115dea967a7463c3775a5ce9e1952af84006be46b2R70) before deploying any change to how docsearch actually returns results

**Comment by FredKSchott** [comment]
Solved by #1568

**Comment by jasikpark** [comment]
> Seems like the best approach will be to let Algolia index Astro docs with the new meta tag for lang. Then we can test searching with the [`facetFilters` set like this](https://github.com/snowpackjs/astro/pull/1568/commits/911646a3b842a6cfeaf46e30f5c0a58ea06fd328#diff-4c755b369f155105965f0e115dea967a7463c3775a5ce9e1952af84006be46b2R70) before deploying any change to how docsearch actually returns results

Do we still need to turn on facetfilters?
