### ISSUE TITLE
🐛 BUG: [Next] Renderer order causes error

### ISSUE THREAD

**Issue by drwpow** [withastro/astro#1685]
### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

❌ This fails:

```
renderers: ['@astrojs/renderer-react', '@astrojs/renderer-preact']
```

✅ This passes:

```
renderers: ['@astrojs/renderer-preact', '@astrojs/renderer-react']
```

🤷‍♂️

### Steps to Reproduce

Use `framework-multiple` or `with-markdown` or any example with multiple JSX renderers. You’ll either see it working, or:

```
Cannot read properties of undefined (reading '__H')
```

**Comment by benzizoo** [comment]
this issue seems to happen as well while using react-hook-form
