### ISSUE TITLE
🐛 BUG: Default imports not imported properly

### ISSUE THREAD

**Issue by SimeonGriggs** [withastro/astro#1713]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Using 0.21 beta

Packages default imports don't seem to get imported correctly, failing with this error:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

### Steps to Reproduce

Import a default package like [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer) and its React component like this:

```
import Highlight, { defaultProps } from "prism-react-renderer";
```

The default import `Highlight` imports as the entire object. Not the `default` key in that Object. So importing the components like documented...

```
<Highlight {...defaultProps} code={code}>
```

...doesn't work, but calling the default key does!

```
<Highlight.default {...defaultProps} code={code}>
```

### Link to Minimal Reproducible Example (Optional)

https://github.com/SimeonGriggs/simeonGriggs/blob/main/astro/src/components/PortableText.jsx

**Comment by natemoo-re** [comment]
Thanks! This looks like an issue we'll need to fix upstream in Vite.

**Comment by IanVS** [comment]
I've found that this can happen in vite/rollup when dependencies mix default and named exports.  Rollup has a warning about it, even: https://rollupjs.org/guide/en/#outputexports.

**Comment by fi3ework** [comment]
Same issue, any workaround for now?

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:

The latest version of Vite landed in `astro@next` and will be making its way into a new `astro` release soon :+1:

**Comment by kasvith** [comment]
its still haunting me :)
