### ISSUE TITLE
Should `@astrojs/language-server` be in devDependencies instead of dependencies?

### ISSUE THREAD

**Issue by cktang88** [withastro/astro#1728]
### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

I'm seeing that in my yarn-lock and installed in prod builds in my astro project, wondering if there's a reason for this? Looks like it was included for https://github.com/snowpackjs/astro/pull/1410

That dep includes lots of vscode dependencies too which seems unnecessary to run Astro in production and just slows down installs of npm modules in production builds :/

### Steps to Reproduce

1. `npm init astro` using template `blog`

**Comment by jasikpark** [comment]
#1410 depends on the lsp, though maybe that can be made more optimized?

**Comment by matthewp** [comment]
Thanks for filing! Yes, the language server is used by `astro check` to provide type-checking in `.astro` files. We could possibly bundle it.

When you say production builds do you mean in your CI server?

**Comment by cktang88** [comment]
> When you say production builds do you mean in your CI server?

Yep! My current use case would be to do `astro check` in CI on the PRs before merging, but then after merging, the CI would ideally just build and deploy as fast as possible with no checks.

**Comment by natemoo-re** [comment]
Sounds like the reason Svelte went with a separate `svelte-check` CLI 👍🏻

**Comment by matthewp** [comment]
@cktang88 do you have data on how long npm install was taking before astro check and how much it takes after?

**Comment by cktang88** [comment]
Good point, I compared `0.20.10` and `0.20.09` in CI (Netlify) for different PRs:
env:
```
yarn: 1.22.10
node: 16.13.0
image: Ubuntu Focal 20.04 (default)
```

`0.20.10`: cold time = 20.90s, cold run 2 = 18.19s, cold run 3 = 17.76s, warm w/ Netlify default caching for node_modules + yarn cache = 11.50s
`0.20.09`: cold run 1 = 17.00s, cold run 2 = 26.80s, cold run 3 = 22.15s, warm = 13.31s

There is good amount of variance here even between the same versions but on average only a few seconds faster :sweat_smile:

**Comment by cktang88** [comment]
Good point, I compared `0.20.10` and `0.20.09` in CI (Netlify) for different PRs:
env:
```
yarn: 1.22.10
node: 16.13.0
image: Ubuntu Focal 20.04 (default)
```

`0.20.10`: cold time = 20.90s, cold run 2 = 26.80s, cold run 3 = 22.15s, warm w/ Netlify default caching for node_modules + yarn cache = 11.50s
`0.20.09`: cold run 1 = 17.00s, cold run 2 =18.19s, cold run 3 =17.76s , warm = 13.31s

There is good amount of variance here even between the same versions but on average only a few seconds faster :sweat_smile: 

The warm time for `20.09` is slightly slower but I assume that's within the variance so around the same.

**Comment by matthewp** [comment]
Thanks for the numbers! I think the solution here is probably going to be to bundle the language server. That will prevent installing all of its dependencies.
