### ISSUE TITLE
📘 DOC: Add section about Astro component tag order

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/astro#1740]
As changes expected in version 0.21 now the tags order in component syntax is important to avoid the compiler to get angry at you.

```astro
---
// Frontmatter first
---

<!-- html second -->
<html lang="en"></html>

<!-- style third -->
<style></style>

<!-- script last -->
<script></script>
```

From this change we should expect the compiler to also ask the user to enforce that order and refer to the section in the docs and add some test case for this behavior

**Comment by natemoo-re** [comment]
TBH I'm not sure what the behavior here _is_ versus what the behavior _should_ be.

We definitely don't want confusing implicit behavior that forces you to structure your file a certain way. Things should just work independently of the file format.

**Comment by aFuzzyBear** [comment]
You are right dude, the format is not implicit, I have spent ages playing about with the file format to try and verify this hypothesis, its safe to discard it, Im sorry for wasting your time with this. Given the issue that Alex was facing earlier it does seem to be specific to #1741 also just to put it out there HMR seems to not be playing nice with the online stack-editors, 
Thanks man, =)

**Comment by jonathantneal** [comment]
With credit to @sarah11918, we’ve been tidying our issues, and we noticed that the underlying issue leading to this request was resolved. I’m closing it for now, but definitely ping us if you feel it should be re-opened.
