### ISSUE TITLE
🐛 BUG: renderer-lit doesn't work with re-exported lit imports, snowpack crashes

### ISSUE THREAD

**Issue by jorenbroekema** [withastro/astro#1759]
### What package manager are you using?

npm

### What operating system are you using?

Ubuntu 20.04 LTS (through WSL2)

### Describe the Bug

@astrojs/renderer-lit works great with LitElement, but when I am importing Lit through another package by proxy, snowpack errors.

```js
import { LitElement, html } from "lit";

export const tagName = "foo-el";

class FooEl extends LitElement {
  static get properties() {
    return {
      count: { attribute: false },
    };
  }

  constructor() {
    super();
    this.count = 0;
  }

  connectedCallback() {
    super.connectedCallback();
    setInterval(() => {
      this.count++;
    }, 1000);
  }

  render() {
    return html`Hello, World! from lit ${this.count}`;
  }
}
customElements.define(tagName, FooEl);
```

```html
---
import '../components/foo-el.js';
---
<foo-el client:load></foo-el>
```

`astro.config.mjs`
```js
export default {
  renderers: ['@astrojs/renderer-lit'],
};
```

This component works great like this, but then I change the import to another package that re-exports Lit, and things go wrong:

```js
import { LitElement, html } from "@lion/core";
```

Error:
```
[executing astro] [Error: ENOENT: no such file or directory, open '/home/joren/code/astro-bug/node_modules/.cache/snowpack/build/@lit/reactive-element@1.0.1/@lit/reactive-element/decorators/custom-element.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/joren/code/astro-bug/node_modules/.cache/snowpack/build/@lit/reactive-element@1.0.1/@lit/reactive-element/decorators/custom-element.js'
}
```

For reference, `@lion/core` re-exports from lit --> https://unpkg.com/browse/@lion/core@0.18.4/index.js

I could just import straight from lit instead, but that's not really going to solve my problem because I am also importing some webcomponents from `@lion` that internally use `@lion/core` to import from Lit.

Now, I'm assuming this is snowpack related somehow, there's warnings in the terminal about unscannable package imports. Not really sure how to go about fixing this, especially since I have no experience with snowpack or astro's settings for snowpack.

Versions:
`nodejs`: 16.11.1
`npm`: 8.0.0
`astro`: 0.20.12
`@astrojs/renderer-lit`: 0.1.2
`@lion/core`: 0.18.4
`lit`: 2.0.2 (as transitive dep of `@lion/core`)

### Steps to Reproduce

1. `npm init astro` using template Starter Kit (Generic)
2. Add @astrojs/renderer-lit to config
3. Install `@lion/core`
4. Create a Lit Component by importing LitElement/html from `@lion/core` instead of `lit`
5. Use this component in your index.astro page
6. `npm run dev`
7.  Everything looks okay, go to browser where it's served
8. Suddenly snowpack starts scanning packages and complaining they are unscannable
9. Finally the error
![image](https://user-images.githubusercontent.com/36734656/140646813-ffb1b9ce-82e2-4503-861d-a5f19e795196.png)

### Link to Minimal Reproducible Example (Optional)

https://github.com/jorenbroekema/astro-lit-bug

**Comment by matthewp** [comment]
Would be good to test against `next` to see if Vite is helping here at all.

**Comment by natemoo-re** [comment]
This [StackBlitz reproduction](https://stackblitz.com/edit/jorenbroekema-astro-lit-bug-avbknt?file=src%2Fcomponents%2Ffoo-el.js) on `astro@next` narrows things down a bit! 

Looks like `LitElement` from `@lion/core` is assuming a browser environment rather than being SSR compatible. 

```
00:00:00 AM [vite] Error when evaluating SSR module /node_modules/@lion/core/src/browserDetection.js:
TypeError: Cannot read properties of undefined (reading 'userAgent')
    at /node_modules/@lion/core/src/browserDetection.js:34:43
    at instantiateModule (/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:66510:15)
```

**Comment by jorenbroekema** [comment]
I tried running my repro on astro@next locally but I get:

![image](https://user-images.githubusercontent.com/36734656/140810738-097e1edd-1dbc-48a6-a71b-74b01768b898.png)

For context, Lion is kind of all in on scoped elements registry, allowing multiple custom elements with the same name to be used on the same page (e.g. multiple major versions that cannot be deduped). It uses [`@open-wc/scoped-elements`](https://open-wc.org/docs/development/scoped-elements/#development-scoped-elements) which is now following the [Scoped Custom Element Registries Spec Proposal](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Scoped-Custom-Element-Registries.md) and automatically loads a polyfill [@webcomponents/scoped-custom-element-registry](https://github.com/webcomponents/polyfills/tree/master/packages/scoped-custom-element-registry)

**Comment by jorenbroekema** [comment]
https://stackblitz.com/edit/jorenbroekema-astro-lit-bug-7oxaif?file=src%2Fpages%2Findex.astro tried to create a reproduction with just lit and @open-wc/scoped-elements and without lion, but ran into issues immediately

**Comment by natemoo-re** [comment]
@jorenbroekema If these components only need to load on the client, you can just reference the components inside of a `<script>` tag like you normally would! The Astro renderer flow is only for SSR'ing components that _can be SSR'd_. https://stackblitz.com/edit/jorenbroekema-astro-lit-bug-uzvk9z?file=src%2Fpages%2Findex.astro

I think https://github.com/snowpackjs/astro/pull/1737 might be along the lines of what you're expecting to work, though.

**Comment by jorenbroekema** [comment]
Ahh good workaround for now thanks.

However, I do believe that what I am trying to do should probably be supported with the lit renderer right?

- Regular Lit component failing on latest next versions: https://stackblitz.com/edit/jorenbroekema-astro-lit-bug-7oxaif?file=src%2Fpages%2Findex.astro
- Regular Lit component that uses scoped elements spec polyfill, I would create a repro that doesn't involve `@lion` stuff so it's more isolated, but the bug above is blocking me there

**Comment by JosefJezek** [comment]
Lit components are ok now, here is example https://github.com/withastro/astro/tree/latest/examples/framework-lit
