### ISSUE TITLE
📘 DOC: Separate `feature` releases from `content` and `ui` releases

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#1779]
There are 3 types of `docs` updates I see:

- Updates related to Astro releases, features, etc.
- UI updates, for example improving the docs search
- Improving the content of the docs, adding additional i18n pages

Currently, the docs site is in lockstep with releases for `astro`, which is fine when we are releasing on a consistent schedule, but less helpful when we're paused like in preparation for `v0.21`.

I'd like to propose that we merge docs into both `latest` and `main` unless if they're associated with a feature or similar update to Astro

**Comment by FredKSchott** [comment]
Do you mean to cherry-pick docs commits from `main` onto `latest`? I'm not sure if there's a way to do that automatically, I'm definitely curious to hear more about how this would work!

**Comment by jasikpark** [comment]
It's not really clear to me either about how this would work 😅

**Comment by natemoo-re** [comment]
One obvious solution here would be to split `docs` into a separate repo! That way it would truly be decoupled from any work happening on `astro` and could be updated on an as-needed basis.

**Comment by FredKSchott** [comment]
Done in https://github.com/withastro/docs
