### ISSUE TITLE
🐛 BUG: getStaticPaths not working for markdown

### ISSUE THREAD

**Issue by schlichtanders** [withastro/astro#1793]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

It seems impossible to use Markdown in combination with dynamic routing, as there is no way to set the `getStaticPaths` function.

### Steps to Reproduce

Minimal astro setup plus the following two files

```astro
---
// src/layouts/test.astro
const { content } = Astro.props;
export async function getStaticPaths() {
  return ['en', 'de'].map(lang => ({ params: { lang: lang } }));
}
---
<html>
  <head>
    <title>{content.title}</title>
  </head>

  <body>
    <p>content.astro.content = {content.astro.content}</p>
    <p>content.url = {content.url}</p>
    <slot />
  </body>
</html>
```

```astro
---
// src/pages/[lang]/test.md
layout: ../../layouts/test.astro
title: Hi
---

# Hello

World
```
When serving it with `npm run dev` and going to `localhost:3000/en/test`, I get the following error printed on the webpage 
```
Error: [getStaticPaths] getStaticPaths() function is required. Make sure that you `export` the function from your component.
```
and on the terminal console I get
```
[access] /en/test
[executing astro] Error: [getStaticPaths] getStaticPaths() function is required. Make sure that you `export` the function from your component.
    at validateGetStaticPathsModule (file:///home/ssahm/Projects/JuliaPerformance/JuliaPerformance.gitlab.io/node_modules/astro/dist/util.js:14:11)
    at load (file:///home/ssahm/Projects/JuliaPerformance/JuliaPerformance.gitlab.io/node_modules/astro/dist/runtime.js:98:7)
    at async Server.<anonymous> (file:///home/ssahm/Projects/JuliaPerformance/JuliaPerformance.gitlab.io/node_modules/astro/dist/dev.js:21:20)
```

**Comment by natemoo-re** [comment]
Ah, interesting, we haven't run into this yet.

I'd be curious if there's a way we can support this with the new `setup` option in `astro@next`, but I'm also really curious if this is something we _want_ to support. 

The general assumption we've made is that `.md` files are typically static content. Would using a similar approach that we do in our [docs](https://github.com/snowpackjs/astro/tree/main/docs/src/pages) site work for your use case?

**Comment by schlichtanders** [comment]
I use dynamic routing for internationalization fallback.
- `src/pages/[lang]/fallback_language_pages/*`
- `src/pages/de/other_languages_pages/*`

With the current restriction I cannot use Markdown to implement the language fallback, a pity.

**Comment by schlichtanders** [comment]
Thank you for the pointer to `Astro.fetchContent`. I was not aware that it also parses the headers and front-matter. Good to know and looks like a full workaround. Thanks.
