### ISSUE TITLE
🐛 BUG: Scripts not hoisted out of components rendered for a markdown page

### ISSUE THREAD

**Issue by innermatrix** [withastro/astro#1805]
### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

If a markdown page uses a layout that includes a component, and that component uses a hoisted script, the hoisted script is not included in the rendered page. Works fine if the page is astro instead of markdown.

Seen in 0.20.12 and 0.21.0-next.2

### Steps to Reproduce

1. See attached stackblitz
2. Load main page → nothing happens
3. Click link on main page to load the other page → alert "test" appears

* Expected: both pages include the `Test` component whose hoisted script calls `alert()`; both pages should cause an alert to appear
* Seen: hoisted script only works in astro page. Removing `hoist` from the script makes it work in both

### Link to Minimal Reproducible Example (Optional)

https://stackblitz.com/edit/github-t3hheb-yojlyi

**Comment by jonathantneal** [comment]
Confirmed, a `<script hoist>` in either `Layout.astro` or `Test.astro` is nowhere to be found in the source, while a `<script>` is.
