### ISSUE TITLE
🐛 BUG: Important regression between 0.20.2 to 0.21.0-next.[1-3] for nested variables replacements

### ISSUE THREAD

**Issue by lakano** [withastro/astro#1807]
### What package manager are you using?

npm

### What operating system are you using?

Fedora Linux 35

### Describe the Bug

The variable replacement doesn't works in some parts of nested html code, the variable isn't replaced correctly.
Works in 0.20.2 and stopped to works since the 0.21.0-next1 ( still present in the last version, next3 ) 

I've made a very simple example in stackblitz:

```
---
const variable = "Hello World"
---
<html lang="en">

<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/x-icon" href="/favicon.ico" />
	<meta name="viewport" content="width=device-width" />
	<title>Welcome to Astro</title>
</head>

<body>
	<h1>{variable}</h1>
	<select>
		<option>{variable}</option>
	</select>
</body>

</html>

```
The H1 « {variable} » is correctly replaced, but not the one inside OPTION.

### Steps to Reproduce

1. Click on the stackblitz link
2. You'll see the OPTION with the name of the variable rather than the value of the variable
3. Try to change in package.json to 0.20.2, re-rerun and you'll see the OPTION correctly

### Link to Minimal Reproducible Example (Optional)

https://stackblitz.com/edit/github-rjzxsq?file=src/pages/index.astro

**Comment by jonathantneal** [comment]
Other reproductions:

```astro
---
const options = ""
---
<select>{options}</select>
```

```astro
---
const message = "I dream one day of"
---
<textarea>{message}</textarea>
```

**Comment by lakano** [comment]
Hello!
This bug is come back on 0.21.12
Here is a short example: https://stackblitz.com/edit/github-aerndc?file=src/pages/index.astro
The second SELECT tag is write, but the OPTION tags are outside of the SELECT.

```

---
const batchs = [ 'this option works', 'another one' ]

---
<html lang="en">

<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/x-icon" href="/favicon.ico" />
	<meta name="viewport" content="width=device-width" />
	<title>Welcome to Astro</title>
</head>

<body>

	<select id="first">
			{batchs.map(b => <option>{b}</option>	)}
	</select>

	<select id="second">
		<option>this option bug</option>
	</select>

</body>

</html>

```

**Comment by lakano** [comment]
Thank you @matthewp 
BTW, in my first SELECT I've tested with a map(), but if you just do a variable replacement, the bug appear too.

**Comment by natemoo-re** [comment]
For the record this was reintroduced in https://github.com/withastro/compiler/commit/75bd7303a063c3acba9539a96f3b402f4fade3ff while attempting to fix a somewhat related bug. We'll have to find another approach.

**Comment by tony-sull** [comment]
Including another reproduction here from #2559 

```astro
---
const langs = [
  'HTML',
  "CSS",
  "Javascript",
  "React.js",
  "Next.js"
]
---

<select>
  <!-- Default option -->
  <option value='all'>all</option>

  <!-- works fine if options are typed as hardcoded or adding an empty comment after this line -->
  {langs.map(lang => <option value={lang}>{lang}</option>)}
</select>

<!-- this elements transformed to text -->
<p>p tag for testing</p>
<p>Another p tag for testing</p>
```

Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-7wtvpz?file=src%2Fpages%2Findex.astro

**Comment by erdeme** [comment]
Hi @tony-sull 

It looks like this bug still exists on latest versions. I tried with 23.7, 24.0 and 25.0.

Reproducible example: [https://stackblitz.com/edit/github-rjzxsq-k9i9l2?file=package.json](https://stackblitz.com/edit/github-rjzxsq-k9i9l2?file=package.json)
