### ISSUE TITLE
🐛 BUG: next.3 styles and scripts injected into body instead of head

### ISSUE THREAD

**Issue by hans-d** [withastro/astro#1818]
### What version of `astro` are you using?

next.3

### What package manager are you using?

npm

### What operating system are you using?

linux

### Describe the Bug

In some cases astro injects style and script tags inside the body tag, instead of the head.

This seems to happen when a layout is using another component around it's slot, eg
```
---
import Layout from './body.astro'
---
<html><Layout>
<slot />
</Layout></html>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zxc9hq?file=src/pages/index.astro

**Comment by natemoo-re** [comment]
Yeah this makes sense based on our implementation—the fix here is to move `html` into your `Layout` component.

Our compiler automatically generates `html`, `head`, and `body` elements per the HTML spec. We have to use a heuristic to guess when a user _wants_ this behavior versus when this would be undesirable. For files in `src/pages` or `src/layouts`, we assume that if the root element is a component, that's a Layout component that already has `html`, `head`, and/or `body` in it.

**Comment by hans-d** [comment]
Hi @natemoo-re , the fragment shown is already in a layout component. The page is just simple text referring that fragment, which in turn uses another layout component

**Comment by hans-d** [comment]
Is there a way, eg in the frontmatter, to skip the generation of html/head/body ?

**Comment by natemoo-re** [comment]
Ah actually, this is a compiler bug! See the JS output from the [Astro Playground](https://astro.build/play#EQegDghg5gpgziACtGA6CcAuAnA9sALmABkBFAC1IFE4AxOAQQGMAJOAYSYYFcH2GAslFIB3AFIA2EQGkALLgDiAIwCeKgCoBJACIBrBgyiJS29gA8uAEyjSlAJk0AhAAwSGAL1y6IpAHIqocihcBm0RBmIAJTEDOwZEABttMV0RACtfNJV3AFYADllI5wBbEQBVBIA1UjgwYiYASwB1JgFsBrBnEOAAGlAmXGKwXAA7GBHMBHZB4bGJ9Cw8QhIKUgUBNm04BSZHLipndgVHJQZhqAA3TShIwWlIkIB5AQVnPJhcTRFcEMQGRwAmuwBAwAGb-TQAhh2ADMugaDCUAEYAMpQi5QETaZzYXz6YBAA). The `Layout` component is placed in the implicit `head`, but it's `<slot />` child is rendered to the `body`.

I'm not positive that fixing this bug will fix your issue, but it's worth a shot.

Currently, the only way to skip the `html/head/body` generation is to move this component outside of `src/pages` and `src/layouts`.

**Comment by hans-d** [comment]
I will have a look if moving it to another directory will solve my issue for now. Perhaps as to-be-build option in astro.config.mjs to have something like `bring-your-own-html-head-body: true`

**Comment by drwpow** [comment]
Closing this issue because we’ve improved script injection in the `0.21.0` build. But please re-open if you continue to experience this issue.
