### ISSUE TITLE
🐛 BUG: Add tests for nested custom elements

### ISSUE THREAD

**Issue by justinfagnani** [withastro/astro#1912]
### What version of `astro` are you using?

current

### What package manager are you using?

all

### What operating system are you using?

all

### Describe the Bug

The Lit renderer currently doesn't pass a RenderInfo object into `renderShadow()` or `renderLight()`. This means that there's no open element stack and so every element is rendered as if it's a top-level element. Parent/child elements won't have a chance to communicate (once lit-ssr implements support for that).

I'm not sure how Astro currently handles nested custom elements, but it'd be necessary to have some sort of context preserved that the parent renderer can write to and the child renderer can consume in order to pass the open element stack.

The type of tests to add will be of the form:

```html
<parent-element>
  <child-element></child-element>
</parent-element>
```

Where the child communicates with the parents via events (like a context).

### Link to Minimal Reproducible Example

https://github.com/snowpackjs/astro/blob/main/packages/renderers/renderer-lit/server.js#L38

**Comment by natemoo-re** [comment]
Thanks for opening an issue!

This is a general limitation of Astro's partial hydration approach, not limited to Lit. I'd be very interested in something that could enable context-sharing like this without losing our support for recursive partial hydration. 

We'll have to do some exploration to see how we could approach this.

**Comment by tony-sull** [comment]
@matthewp You merged a fix recently for nested components, would that unblock this use case with Lit?

**Comment by matthewp** [comment]
It doesn't relate to this, no. As @natemoo-re says, this is a limitation of partial hydration, each component is rendered in isolation. Closing as there is nothing we can do to fix this at the moment.
