### ISSUE TITLE
🐛 BUG: HMR not working with components created after dev server started

### ISSUE THREAD

**Issue by santicros** [withastro/astro#1943]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When creating a new component (tested with .astro or .jsx) HMR is not working and not updating the component, even when refreshing the whole page with CMD+R.

Only when updating another component that was already on the page when the dev server was created updates all the components on the page.

Creating the dev server, then creating a component, then restarting the dev server gives HMR to the component.

To reproduce:
- Start the dev server.
- Create a component
- Import it
- Make any update and see no HMR

Here's a small video demoing it:

https://user-images.githubusercontent.com/24988424/142727425-845d9f69-83dc-4508-8366-db64c01852c5.mp4

### Link to Minimal Reproducible Example

https://codesandbox.io/s/beautiful-fire-qq1vj?file=/src/pages/index.astro

Thanks!!

**Comment by tony-sull** [comment]
After a bit of [discord debugging](https://discord.com/channels/830184174198718474/911588740055592961/911598131152584724) it looks like this is specific to pages or components that were added after the `dev` server was started, HMR recognizes updates made to components/pages that existed when the dev server first started

**Comment by santicros** [comment]
Thanks for your message @tony-sull that's exactly the problem I'm seeing, HMR not updating components created after server started. It's not happening for pages though, only for components (.astro, .jsx...) :)

**Comment by tarpier** [comment]
I am seeing the same behaviour on pages using tailwind inside a .astro file

**Comment by santicros** [comment]
Hi all!

I've been debugging more this problem, and what I've found that this is happening only when using Tailwind and having a specific setting at tailwind.config.js:

Previously I had this
``` js
// tailwind.config.js
module.exports = {
  mode: 'jit',
  purge: ['./src/**/*.{vue,js,ts,jsx,tsx,astro}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

Removing all the other file extensions other than astro on purge solved the problem:
```js
module.exports = {
  // ...
  purge: ['./src/**/*.{astro}'],
  // ...
}
```

Any idea why might this be happening?

**Comment by santicros** [comment]
And another tests:

This is working:
```js
module.exports = {
  // ...
  purge: ['./src/components/*.{astro,jsx}'],
  // ...
}
```

This is working too
```js
module.exports = {
  // ...
  purge: ['./src/components/*.{astro,jsx}',  './src/pages/*.{astro}'],
  // ...
}
```

And this is failing:
```js
module.exports = {
  // ...
  purge: ['./src/components/*.{astro,jsx}', './src/pages/*.{astro,jsx}'],
  // ...
}
```

Seems the problem is when having the Purge setting targeting the pages/* with files other than .astro :O

**Comment by yamac-kurtulus** [comment]
This happens to me regardless of when a file was created or the tailwind config.

Actually, when I tried to change the tailwind config as @santicros suggested, HMR ran once after saving tailwind.config.js. After that, I couldn't get HMR to work again.

**Comment by jonathantneal** [comment]
Sticking with the original issue, I can verify that HMR updates are not present when editing an Astro file on CodeSandbox. However, I do see HMR updates working locally.

@santicros, is this your same experience? Also, if you re-check, would you use the latest version of Astro?

**Comment by santicros** [comment]
Hi @jonathantneal! I can confirm I still have the issue with the latest `astro@0.22.6`and `tailwindcss@3.0.11` locally. Adding any new component does not update it changes later

**Comment by zeshhaan** [comment]
> Hi @jonathantneal! I can confirm I still have the issue with the latest `astro@0.22.6`and `tailwindcss@3.0.11` locally. Adding any new component does not update it changes later

I am also having same issue. Each time i add a tailwind class, i need to restart the server. I cloned the astro starter template and followed the instructions from [here](https://docs.astro.build/en/guides/styling/#-tailwind) to setup tailwind.

**Comment by tony-sull** [comment]
Related issues: #2568 #2410

**Comment by tony-sull** [comment]
See the updated `with-tailwindcss` example for a fix :+1:  I updated the example to import the CSS in frontmatter and use `set:html` to inline it in the page's `<head>`.  The `@import "../styles/global.css"` syntax was actually causing an HMR issue that was preventing dev server from catching newly created files

[PR](https://github.com/withastro/astro/pull/2601) updating the Tailwind example

**Comment by santicros** [comment]
Hi all!
I'm having this problem again (on all browsers: Firefox, Chrome..) Here a video showing what's happening:

When a new component is created, it's not updated:

https://user-images.githubusercontent.com/24988424/172591783-bff0c5c0-d726-4251-8ed0-346fc98a96d1.mp4
