### ISSUE TITLE
📘 DOC: Theme Toggle doesn't work

### ISSUE THREAD

**Issue by altano** [withastro/astro#1963]
The Theme Toggle switch (light/dark) on docs.astro.build doesn't seem to do anything. I clicked the sun and moon emoji and nothing happens.

I tried both latest Firefox and Chrome.

**Comment by drwpow** [comment]
Can confirm! Will fix this.

**Comment by drwpow** [comment]
Turns out this was a bug with `client:visible` when you used it on a page where the same component appeared multiple times. So wasn’t just a bug with our docs!
