### ISSUE TITLE
🐛 BUG: `Astro.resolve()` not processing files & paths in `Astro@0.21`

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/astro#1968]
### What version of `astro` are you using?

0.21.1

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

when building, Astro leaves the static path of the user's machine where `Astro.resolve()` is called

I tested for `.scss` & `.ts` file, but i think it also affect all files using the resolve function

Ex: `<script src={Astro.resolve('../../scripts/service-register.ts')}></script>` become `<script src="/var/www/project/src/scripts/service-register.ts"></script>` after build

Same with scss: `<link rel="stylesheet preload" as="style" href={Astro.resolve('../../styles/global.scss')}>` become `<link rel="stylesheet preload" as="style" href="/var/www/project/src/styles/global.scss">`

scss files are being preprocess by astro and turning to `NAME-SLUG.css` but `.ts` file are simply not processed entirely

see below for exemple (build & see the result in the `dist/` directory)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kgxvhf?file=src/pages/index.astro

**Comment by frankstallone** [comment]
I am seeing a similar issue. On `0.20.x` everything is building correctly. You can [see this on my](https://github.com/frankstallone/frankstallone-portfolio) `master` branch. [I created a new branch](https://github.com/frankstallone/frankstallone-portfolio/tree/feature-upgrade-astro) to upgrade to `0.21.x` and what I am seeing is that the `build` step does not process my `.ts` files at all. They never land in the `dist/` folder and the reference to them in the compiled `HTML` is at some odd location. You can see the weird references in the `scripts` just about the closing `body` tag on [this deploy preview site](https://61994e98b35ad80007293542--confident-saha-449b9e.netlify.app/). 

• `src/pages/index.astro` has the `Astro.resolve()` calls. 
• `.ts` files are all in the `src/scripts` or `src/utils` folder

**Comment by jonathantneal** [comment]
Confirmed the file is not available in dev or build (which I tested locally).

**Comment by frankstallone** [comment]
> Thanks, I'm going to fix this. First going to see how non-hoisted scripts behaved in 0.20 and will apply similar logic.

Fun fact! I tried adding the `hoisted` tags to my two `script` files and saw an odd behavior. It would only include the _first_ `script`! So on my home page example, running `npm run start` would only include the the first `script` in dev mode. I tried swapping which came first and it didn't matter which script it was.

**Comment by Chrissdroid** [comment]
Reopening this issue because it keeps appening after update for `.scss` file

`.ts` file are now process correctly and it's fixed

but not for `.scss` files. See exemple below:
https://stackblitz.com/edit/github-sht6ym?file=src%2Fpages%2Findex.astro&on=stackblitz

`<link rel="stylesheet" href={Astro.resolve('../styles/global.scss')}>` becomes `<link rel="stylesheet" href="/var/www/project/src/styles/global.scss">` after building

**Comment by matthewp** [comment]
Ok, I thought we already had tests for that, but I'll check it out

**Comment by matthewp** [comment]
@Chrissdroid in that example project I get this after the build: `<link rel="stylesheet" href="assets/index.9bc8e468.css">`, and this file does exist and contains the correct CSS.

What operating system are you using? Could be os specific issue here.

**Comment by Chrissdroid** [comment]
i'm using ubuntu v20.04
