### ISSUE TITLE
🐛 BUG: Windicss, UnoCss etc... doesn't properly work in astro

### ISSUE THREAD

**Issue by Blinks44** [withastro/astro#1971]
### What version of `astro` are you using?

0.21.1

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Am i doing something wrong, or what is a proper way to install Windicss (vite plugin) on fresh v0.21? What i try:

astro.config.mjs
```js
import WindiCSS from "vite-plugin-windicss";

vite: {
  plugins: [WindiCSS()],
},
```
windi.config.js
```js
export default {
  ...
    extract: {
    include: ["./src/**/*.{vue,html,jsx,tsx,astro}"],
    exclude: ["node_modules", ".git"],
  },
}
```
src/layouts/BaseLayout.astro
```js
---
import "virtual:windi.css";
---
```
And when i run `npm run dev` classes that already exists in the project - work, but new added classes during dev - doesn't apply their css styles. Also `npm run build` shows an error `Rollup failed to resolve import "/@windicss/windi.css" from "@astro-page-all-styles/index.js".`

In reproduction you can try to add some Tailwind class that doesn't already exist in project and nothing will work, windicss can't insert tailwind classes on fly, when you add them to you project during dev server work.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yhknx2-co3mve?devtoolsheight=33&file=src/pages/index.astro

**Comment by natemoo-re** [comment]
Thanks! This is a known issue that @matthewp is working on a solution for. Assigning him.

**Comment by matthewp** [comment]
Thanks for filing the issue. We are collaborating with the uno.css maintainer on a solution. https://github.com/antfu/unocss/issues/105

**Comment by Miaourt** [comment]
Sorry to maybe bump this but is there some alternative to use those frameworks rn ?

**Comment by matthewp** [comment]
@Miaourt Not at the moment that I'm aware of. I am actively working on this as part of a larger effort to make improvements to the build (performance in particular). Due to the nature of how Astro works, which differs from SPA-oriented frameworks, we never build `.astro` pages, which is the reason why these types of plugins don't work, they expect to run through Vite's build pipeline.

The change I'm working on will make it work that way. I'll talk to the team and see if they're open to adding some experimental flag to get my work out sooner for those who want to test it.

**Comment by Blinks44** [comment]
@matthewp Hope to touch it soon

**Comment by hans-d** [comment]
@matthewp something experimental or some other workaround - eg being able to not fail on such assets - and perhaps something that we can pass the generated builds through vite in a second run (even if we have to add it to some npm script entry) would work for me.

**Comment by 7flash** [comment]
Can it work with React or any other framework inside of Astro?

**Comment by yellowsink** [comment]
Probably, as Vite would process those files.

**Comment by matthewp** [comment]
Happy to see that Windicss works with Astro now!

https://stackblitz.com/edit/github-yhknx2-f2kqam?devtoolsheight=33&file=src%2Fpages%2Findex.astro

**Comment by yellowsink** [comment]
Awesome! I will be using this ASAP now :p

**Comment by ay13** [comment]
In the Stackblitz demo, Windi works on the first load but any changes do not trigger the creation of the new styles.

**Comment by yellowsink** [comment]
In local testing, indeed this works perfectly with `vite build`, however `vite dev` will not find any new styles, only ones that existed at the time of command invoke.

So Astro still does not properly implement Vite development mode I would guess as the source of this.

**Comment by matthewp** [comment]
Thanks! If there is a specific dev HMR (it sounds like) related bug, please file a separate issue on that.

**Comment by Olyno** [comment]
Hi @yellowsink, can you fill the new issue about it please? I have this issue too, but don't have enough details to fill an issue

**Comment by yellowsink** [comment]
Okay, will do it later today!

**Comment by yellowsink** [comment]
#3291
