### ISSUE TITLE
🐛 BUG: Not allowed to load local resource (css modules from react component)

### ISSUE THREAD

**Issue by RinatValiullov** [withastro/astro#1973]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Describe the Bug

I have separate react component with scoped styles in css module.
But after building a project get warnings in chrome dev tools console tab:

![image](https://user-images.githubusercontent.com/9755333/142906234-34ff85e2-a03b-4e73-a354-2aa8038c80fd.png)

Astro compile the page and enter a path to these modules in `file:///` protocol:

![image](https://user-images.githubusercontent.com/9755333/142906482-5609dfd1-f13a-4b1a-8133-a49a25c12b74.png)

How to fix such behaviour? And I also have some flash styles (nearly 0.5sec no styles are applied) when route to another pages.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/css-modules-issue

**Comment by natemoo-re** [comment]
Pinging @drwpow who has dug into a lot of Vite × Windows bugs recently!

**Comment by drwpow** [comment]
This should be fixed in the upcoming `0.21.3` version. If you still experience issues after updating, please let us know!
