### ISSUE TITLE
🐛 BUG:  Classes are not combined when one is spread from Astro.props

### ISSUE THREAD

**Issue by IanVS** [withastro/astro#1978]
### What version of `astro` are you using?

0.21.1

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

 I found that the internal classes that astro uses to default-local scope styling are included in `Astro.props`, and spreading in props to an element that already has a `class` defined results in a 500 due to duplicate class declarations, rather than combining them.  See the reproduction for an example.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3nphsr?file=src/components/input.astro

**Comment by natemoo-re** [comment]
I agree that throwing a 500 error is a bug, but I'm not sure I agree with your suggestion that merging them is the correct behavior.

IMO, automatically passing the `class` attribute as a prop is the buggy behavior. It is meant to allow users to opt-in to styling component children, but perhaps we need a special prop for that, separate from the `class` attribute.

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:
