### ISSUE TITLE
🐛 BUG: head contents are moved into body

### ISSUE THREAD

**Issue by IanVS** [withastro/astro#1989]
### What version of `astro` are you using?

0.21.2

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

Upon upgrading to 0.21, I found that some things were breaking on my site, and I tracked it down to my `<head>` contents being placed into `<body>`.  See reproduction for an example.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8dhdku?file=src/pages/index.astro

**Comment by natemoo-re** [comment]
Thanks for opening this issue! This looks like a follow-up to https://github.com/snowpackjs/astro-compiler/pull/154 which we _thought_ fixed this issue. I'll add this example as a test case and diagnose what's breaking.

**Comment by matthewp** [comment]
@natemoo-re is there a reason why we can't just parse everything as a fragment? This is how it worked in the old compiler. Or is a head/body tag not allowed in a fragment?

**Comment by natemoo-re** [comment]
@matthewp Yep! I think that's a larger implementation discussion that I'd love to spin out in the new RFC repo.

This issue is a regression of behavior that _was_ working in 0.21.1. PR forthcoming.
