### ISSUE TITLE
🐛 BUG: Astro.resolve() full path URLs behave oddly, should be relative to root?

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#2002]
### What version of `astro` are you using?

main (0.21.4)

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

1. Currently, `Astro.resolve()` creates absolute URLs in development. (ex: `localhost:3000/Users/fks/Code/astro/examples/blog/src/styles/blog.css`)
2. When I visit these URLs, I get a 404. 
3. However, they do appear to load in the browser when requested via a `<link>` tag. This is confusing behavior: why do I get a 200 sometimes and a 404 other times?

As far as I understand it, Vite is meant to load these URLs from a root-relative URL (ex: `localhost:3000/src/styles/blog.css`). This URL always returns a 200, and I believe is documented as "correct" in Vite documentation. I wonder if the absolute URL support is something that we added as a workaround, or some undocumented behavior coming from Vite.

```
// Naive fix: unfortunately createAstro() doesn't have access to the config root value
resolve(segment: string) {
  return (new URL(segment, url)).pathname.replace(process.cwd(), '');
},
```

### Link to Minimal Reproducible Example

Oddly enough, I can't reproduce this on stackblitz. I'm guessing that the root dir is the same as absolute dir on Stackblitz.

**Comment by matthewp** [comment]
> However, they do appear to load in the browser when requested via a <link> tag. This is confusing behavior: why do I get a 200 sometimes and a 404 other times?

My guess is that Vite is serving these differently depending on the `accept` header. I know that it does use that header to decide whether to serve JavaScript or CSS for css file paths. Not sure why the 404 in this case.

>  I wonder if the absolute URL support is something that we added as a workaround

No, it comes from Vite.

> unfortunately createAstro() doesn't have access to the config root value

Yeah, that's why it works like this. Although we could probably pass this in via the compiler.

**Comment by brpaz** [comment]
Just updated a project to Astro 0.21 and start having this issue with SVG files.

Any workaround? I need to dynamically construct the URL from a variable. that´s why I am using `Astro.resolve`.

**Comment by matthewp** [comment]
@brpaz which issue exactly? Afaik this shouldn't break anything.

**Comment by matthewp** [comment]
This has come up enough on Discord that I'm going to go ahead and fix as it should be pretty small.
