### ISSUE TITLE
🐛 BUG: getting `roots[0] is undefined` after browser reload when doing client-side hydration

### ISSUE THREAD

**Issue by imballinst** [withastro/astro#2004]
### What version of `astro` are you using?

0.21.3

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

Hello! First of all, thank you for creating this thing! I want to report a bug -- or, at least at the time of writing, I think it is.

Client-side hydration stops working (?) after a browser reload, after starting `yarn start` for the first time.

## Reproduction in Codesandbox

As shown in the link below, https://codesandbox.io/s/unruffled-perlman-ggl0v?file=/src/pages/index.astro, the steps is to:

1. Open the Codesandbox
2. Wait until the counter starts ticking, or just save a random file, e.g. in `/src/pages/index.astro`. This will trigger the build and restart the Node server (or so, I believe). At the same time, the interval will start ticking.
3. Reload the browser page **inside** the Codesandbox
4. See the count returns back to 0, but it won't start ticking. I think it should keep working anyway? Not sure. Anyway, there is this error in the browser console (not the Codesandbox one):

```
Uncaught (in promise) TypeError: roots[0] is undefined
    onVisible visible.ts:10
    <anonymous> index.astro:2
```

## Alternative reproduction

I have prepared an alternative GitHub repository for this purpose: https://github.com/imballinst/astro-bug-repro/tree/client-hydration-react-1

1. Clone the repository
2. Install dependencies using `yarn`
3. `yarn start`
4. When the browser first opens, the interval will run properly
5. After the browser is reloaded, then the timer will stop ticking.

I tried to find the root cause, then I find that for the first time render, the `astro-root` element is this:

```
<astro-root uid="SrAbR">
```

I also placed a `console.log` in the `node_modules/astro/dist/runtime/client/visible.js` file to check the `astroId`. It outputs this in my browser:

```
[vite] connecting... client.ts:22:8
SrAbR visible.ts:9:8
[vite] connected. client.ts:52:14
```

However, after browser reload, the `astro-root` element became this:

```
<astro-root uid="2a6uG6">
```

While that happens, the `astroId` in the `onVisible` function stood the same:

```
[vite] connecting... client.ts:22:8
[vite] connected. client.ts:52:14
SrAbR visible.ts:9:8
```

Hence, probably that's the reason why `roots[0]` throws error, because `roots` is `undefined`. If there are more information that I need to give, please let me know. Thanks again!

**EDIT:** apparently this only happens when we are doing anything `Date` related in the `.astro` file... curious.
**EDIT2:** if I remove the `Date` stuff in the `.astro` file and use the `Date` only in the `.jsx` files, it also causes the same kind of errors.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/unruffled-perlman-ggl0v?file=/src/pages/index.astro

**Comment by matthewp** [comment]
So yeah, as you figured out using Date is the cause here. I think what is going on is that because the Date is changing the contents of the HTML is changing, which is what those ids are based on (it hashes the contents). Doesn't mean this *should* break, of course, still diagnosing.

**Comment by matthewp** [comment]
So this comes down to a Vite bug. What happens is the inline scripts we create to render components get cached by Vite. Checking on what is the appropriate way to bust the cache on these. Should be fixable though.

**Comment by imballinst** [comment]
Thank you for diagnosing this further!

Not sure if this helps, but I found another behavior: this only happens if we do `new Date()` (without any arguments). If we do `new Date(1)`, then it will work normally.

**Comment by matthewp** [comment]
Using `new Date(1)` gives you the same date every time. This bug is about the fact that a component's value might change after the dev server starts. Since Vite is caching scripts indefinitely, you can never change a value.

**Comment by imballinst** [comment]
Oh, yeah! That totally makes sense. Thanks for the explanation!

**Comment by imballinst** [comment]
Thanks @matthewp for working on this! It would seem that I can still replicate this issue in https://codesandbox.io/s/vibrant-water-9thhq?file=/src/pages/index.astro, could you confirm if it also happens in your machine? Thanks!

I am attaching the screenshot of the sandbox below -- notice the `roots[0]` error is still there despite the `astro` is bumped to `0.21.5` (confirmed in the `yarn.lock` file).

![image](https://user-images.githubusercontent.com/7077157/143988209-573acbb5-458d-4505-828e-716e5a5cd609.png)

**Comment by matthewp** [comment]
Yep, I can see that, I can see what the problem is as well, fix incoming.

**Comment by matthewp** [comment]
Ok, this will be coming in the next release.  Also fixed upstream: https://github.com/vitejs/vite/pull/5891

**Comment by imballinst** [comment]
Perfect. Thanks @matthewp! I'll test that out again after it is released.

**Comment by imballinst** [comment]
@matthewp is there something that I am doing wrong? https://codesandbox.io/s/unruffled-perlman-ggl0v?file=/package.json

The sandbox still has the same behavior as before. I also tried it in my local repro with these changes: https://github.com/imballinst/astro-bug-repro/commit/8fd0dd9f70e8fccf6bb2a18df1e0d5ce7d9550eb, but still, getting `roots[0] is undefined`. Same case like before, the `uid` changes for each refresh.

I also see the `astro-*` classes in `html` and `main` tag, are they supposed to do anything? On initial load, the `*` part always has the same ID as `uid`, but after first refresh, the `*` part stays the same while the `uid` changes.

**Comment by surajsharma** [comment]
I have this issue in production currently, effectively requiring a hard refresh on client for latest server rendered page. A fix would be welcome.
