### ISSUE TITLE
🐛 BUG: <img> tags display no image on productions sites when using `vite-imagetools`

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#2019]
### What version of `astro` are you using?

0.21.3

### What package manager are you using?

yarn

### What operating system are you using?

Ubuntu

### Describe the Bug

`<img>` tags display no image on productions sites when using `vite-imagetools`. Because there's no dev server running. And also the paths produced by `vite-imagetools` aren't any valid paths. The paths produced by `vite-imagetools` are something like this `/@imagetools/fa400dec5a9a532885014638aabc426b1794b160`. So, browsers don't recognize this as an image file.  And there's also no file present with this name in the `/dist` directory.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-e6cx7v

**Comment by RafidMuhymin** [comment]
Confirmed in `v0.21.4`

**Comment by matthewp** [comment]
This was previously reported in https://github.com/withastro/astro/issues/1718 . Going to consolidate around that report.
