### ISSUE TITLE
🐛 BUG: `Astro.new/starter@next` referencing `.scss` files when it's using `.css`

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/astro#2023]
### What version of `astro` are you using?

0.21.4

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

index.astro is resolving `global.scss` & `home.scss` but these files are `.css` files

### Link to Minimal Reproducible Example

https://astro.new/starter@next?on=stackblitz

**Comment by stephanbogner** [comment]
Can confirm, I made [a PR](https://github.com/withastro/astro/pull/2020) about this.

**Comment by drwpow** [comment]
Fixed! Thank you.
