### ISSUE TITLE
🐛 BUG: environment variables in build

### ISSUE THREAD

**Issue by diegoleme** [withastro/astro#2027]
### What version of `astro` are you using?

0.21.4

### What package manager are you using?

npm 8.1.0

### What operating system are you using?

Mac

### Describe the Bug

I have the following environment variable configured in the .env file.

```
PUBLIC_API="https://api.example.com/"
```

With the `npm run dev` command, everything works as expected.

However, when I use the `npm run build` command, The value I get in the client is `undefined`. The variable is available on the server, but not on the client.

But, if I change the variable name to `VITE_API`, this variable is available on the client.

## `npm run dev`
![image](https://user-images.githubusercontent.com/374857/143665667-398399d1-7754-45af-8725-31d36f90738d.png)

## `npm run build && npm run preview`
![image](https://user-images.githubusercontent.com/374857/143665682-383af229-2af4-4d7b-9daa-5f9361fd4117.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rpfxhk?file=src%2Fcomponents%2FClient.vue&on=stackblitz

**Comment by matthewp** [comment]
Thanks! I think this might be a quick fix in the build, will take a look.

**Comment by matthewp** [comment]
This was fixed in 0.21.5
