### ISSUE TITLE
🐛 BUG: presence of a body tag in a layout crashes Astro entirely

### ISSUE THREAD

**Issue by jlengstorf** [withastro/astro#2031]
### What version of `astro` are you using?

0.21.4

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

In 0.21.4 (and 0.21.3 as well), adding a layout with a `<body>` tag causes Astro to crash entirely.

1. `npm init astro` with the minimal starter
2. move the contents of `src/pages/index.astro` into `src/components/layout.astro` and add a slot
3. import the layout in `src/pages/index.astro` and use it

Trying to run the server fails:

```
Error: Uh oh, the Astro compiler encountered an unrecoverable error!
```

In the terminal:

```
❯ npm run dev

> @example/minimal@0.0.1 dev
> astro dev

04:45 PM [astro] Server started                               395ms
04:45 PM [astro] Local: http://localhost:3000/
panic: runtime error: index out of range
panic: runtime error: index out of range
4:45:44 PM [vite] Error when evaluating SSR module /Users/blitz/github/jlengstorf/astro-body-error/src/pages/index.astro:
    at /Users/blitz/github/jlengstorf/astro-body-error/src/components/layout.astro
```

I'm not sure when this was introduced, but it wasn't happening when I was on the pre-release branch for Vite (`0.21.0-next.3`).

### Link to Minimal Reproducible Example

https://github.com/jlengstorf/astro-body-error

**Comment by jlengstorf** [comment]
Digging a little bit deeper here, it actually looks like layouts don't work at all with Vite? The wrapped content is appended after the layout instead of in the slot and we end up with duplicate head/body tags.

I might be holding it wrong, but as far as I can tell I'm doing what the docs do.

**Comment by gabrielgrant** [comment]
direct stackblitz link: https://stackblitz.com/github/jlengstorf/astro-body-error/

**Comment by gabrielgrant** [comment]
playing with this a bit more, it does seem like a basic component that wraps content without <html>, <head>, or <body> is working to insert content in the slot as I'd expect:

![image](https://user-images.githubusercontent.com/493968/143796986-73e0c018-8c9d-478f-854a-93caa21c8238.png)

(although it doesn't seem to be applying the style tag from the wrapper component? https://stackblitz.com/edit/github-k3z2hw?file=src%2Fcomponents%2FMyLayout.astro )

**Comment by CM-IV** [comment]
I didn't get errors or crashes after updating from 0.21.0 to 0.21.4, only a blank page appeared, 

I removed the **html** and **body** tags inside of my wrapper layout and used them in each page instead. 

That seems to fix the blank page issue for me.

**Comment by matthewp** [comment]
There's a bug in 0.21 where, due to using a more strict html parser, we have trouble with components that contain body/head tags. The workaround at the moment is to put layouts into `src/layouts` where they will be treated like pages from the parser's perspective. We do want to fix this requirement urgently, however.

**Comment by natemoo-re** [comment]
Just wanted to share an update! Our compiler needed some updates to support this, but the 0.20.x behavior should return for components with https://github.com/withastro/astro-compiler/pull/177!

**Comment by jlengstorf** [comment]
just confirmed it's working as expected now with the upgrade to `0.21.5`!
