### ISSUE TITLE
🐛 BUG: Vite plugins not applied in production (only in dev)

### ISSUE THREAD

**Issue by tkon99** [withastro/astro#2039]
### What version of `astro` are you using?

0.21.4

### What package manager are you using?

npm

### What operating system are you using?

Windows (reproduced in Linux)

### Describe the Bug

When using a Vite plugin to transform page HTML the result is as expected when using the dev server (`astro dev`), but building the page (`astro build`) results in Vite plugins not being applied.

To reproduce: example below, after observing the automatically started dev server (correctly processing the HTML), stop the dev server, build the project, and inspect the generated HTML.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5hwrzj-w68pe3?devtoolsheight=33&file=astro.config.mjs

**Comment by matthewp** [comment]
The `transformIndexHtml` hook is specific to a SPA workflow within Vite where you have a literal `index.html` file. The fact that this hook runs in dev is because we use it internally in Astro to resolve module specifiers. This is an internal implementation detail and should not be relied upon.

It's very likely we'll stop using this transformation in the future as we move to SSR where we can't rely on Vite doing HTML preprocessing.

**Comment by jrencz** [comment]
In case some one, like me, finds this issue: If I'm correct there's no way to apply code injections with such ease as `transformIndexHtml` allows into statically built html files. At the same time what's generated is named `index.html` so one may be tempted to go that way (at least I was).

My use case: I tried to inject scripts at the bottom of the page. Astro allows injection as described by type

https://github.com/withastro/astro/blob/ae41f25e10a3fb1e5ad72c979ebe27fe55071de3/packages/astro/src/%40types/astro.ts#L935

but that's not fine for my use case, where I need to inject at the bottom, but opt-out of any transformations.

Right now it's like shown:

https://github.com/withastro/astro/blob/4b188132ef68f8d9951cec86418ef50bb4df4a96/packages/astro/src/core/build/generate.ts#L382-L393

and there's no api to alter generated html files

**Comment by findlay-best-wishes** [comment]
> The `transformIndexHtml` hook is specific to a SPA workflow within Vite where you have a literal `index.html` file. The fact that this hook runs in dev is because we use it internally in Astro to resolve module specifiers. This is an internal implementation detail and should not be relied upon.
> 
> It's very likely we'll stop using this transformation in the future as we move to SSR where we can't rely on Vite doing HTML preprocessing.

Does the `transformIndexHtml` hook has been stopped using?

**Comment by yoyo837** [comment]
If `transformIndexHtml` is not supported in `ssg`, then what should we do when we want to modify the html build?

**Comment by yoyo837** [comment]
`rollup`'s `generateBundle` was found to be unsupported as well.

**Comment by LINGyue-dot** [comment]
`generateBundle` doesn't include HTML files. I'm currently using astro:build:done with file I/O to modify them, but I don't think that's the best approach.
