### ISSUE TITLE
🐛 BUG:  Regex operation in getstaticpaths hangs and pins CPU

### ISSUE THREAD

**Issue by Tc-001** [withastro/astro#2043]
### What version of `astro` are you using?

0.21.4

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Some operations, if performed under `getstaticpaths()`, will cause astro to freeze and pin the CPU at 100%
From my limited testing regex is *at least* one of the main culprits. (there may be others, but could not reproduce)

Here is an example:

`/src/pages/[...foo].astro`
```astro
---
export async function getStaticPaths() {
	let pages = []

 	for (let i = 0; i < 20; i++) {
 		pages.push("foo"+i)
 	}

	//pages = pages.map(x => x.replace((new RegExp("foo", "g"), ""))	

	return pages.map(x => ({params: {foo: x}}))
}
---

<h1>{Astro.request.params.foo}</h1>
```

This will render out:
![image](https://user-images.githubusercontent.com/55956895/143907117-91c17b7d-ec01-4a59-91af-d916a9db0281.png)

...But if I uncomment `pages = pages.map(x => x.replace((new RegExp("foo", "g"), ""))`, it will never load the page and pin my CPU at 100%.
![image](https://user-images.githubusercontent.com/55956895/143907642-d10e1109-1aba-4682-b360-7e3796c01281.png)

I could reproduce in codesandbox as well, where the builtin browser stopped taking any route changes after an uncomment+reload.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/gifted-bhaskara-9wzgn?file=/src/pages/%5B...foo%5D.astro

**Comment by Tc-001** [comment]
Can confirm still happening on `0.21.6`

**Comment by natemoo-re** [comment]
:( Well this seems... bad. I'm really not sure if this is happening in the compiler or in the Astro runtime. Definitely worth more investigation.

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:
