### ISSUE TITLE
🐛 BUG: Vite inline script proxing broken on Windows

### ISSUE THREAD

**Issue by drwpow** [withastro/astro#2053]
### What version of `astro` are you using?

0.21.5

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Scripts don’t proxy correctly in dev on Windows:

![unknown-1](https://user-images.githubusercontent.com/1369770/143957621-f88fda3b-6cfc-4c06-8eaf-4dec7f3cff3a.png)

![unknown](https://user-images.githubusercontent.com/1369770/143957631-a20cbd87-ebbc-41b7-acff-87e3690afe2d.png)

### Link to Minimal Reproducible Example

(windows-only bug)

**Comment by agustinmulet** [comment]
This was working on Windows 10, Astro v0.21.4
