### ISSUE TITLE
🐛 BUG: Errors are not properly reported in markdown setup frontmatter.

### ISSUE THREAD

**Issue by nailuj29** [withastro/astro#2054]
### What version of `astro` are you using?

0.21.5

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

Errors are not properly reported in markdown `setup` frontmatter. The server simply hangs if any syntax errors occur.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5mtpk1?file=src/pages/posts/index.md

**Comment by jonathantneal** [comment]
Confirmed. I get an infinite load and no message.

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:
