### ISSUE TITLE
🐛 BUG: RuntimeError when using components to wrap children

### ISSUE THREAD

**Issue by jungaretti** [withastro/astro#2063]
### What version of `astro` are you using?

0.21.5

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Astro reports `RuntimeError: Error: Uh oh, the Astro compiler encountered an unrecoverable error!` when I use a base components to wrap child components. This prevents me from using a generic `Base` component for common HTML code.

### Steps to Reproduce

`Base.astro` is a component for with everything shared among my components:

```astro
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/x-icon" href="/favicon.ico" />
	<meta name="viewport" content="width=device-width" />
	<title>Welcome to Astro</title>
</head>
<body>
    <span />
</body>
</html>
```

`index.astro` uses `Base` to wrap its actual content:

```astro
---
import Base from "../components/Base.astro";
---
<Base>
    <h1>Welcome to <a href="https://astro.build/">Astro</a></h1>
</Base>
```

### Link to Minimal Reproducible Example

https://github.com/jungaretti/astro-component-syntaxerror

**Comment by jungaretti** [comment]
Probably related to #1757

**Comment by stephanbogner** [comment]
More so probably to #2022 

[Quote](https://github.com/withastro/astro/issues/2022#issuecomment-982081803):
> We’ve been noticing some weirdness when <head> or <body> are included in components. @natemoo-re is adding fixes in the compiler to prevent errors. I think we are still deciding on how best to handle this, but current workaround is to limit <head> and <body> tags to pages, and try to make a habit to always include them.
> 
> This may even become best practice, because if <head> can be specified within components, we’d likely need some sort of API or behavior to merge & combine those tags, which we don’t have currently.

**Comment by jonathantneal** [comment]
Confirmed. I’ve created another example that demonstrates the issue without also including malformed HTML.

https://stackblitz.com/edit/github-hbybtq?file=src%2Fpages%2Findex.astro
