### ISSUE TITLE
🐛 BUG: Compiler error when multiple `<tr>` are conditionally added (0.21.6)

### ISSUE THREAD

**Issue by stephanbogner** [withastro/astro#2069]
### What version of `astro` are you using?

0.21.6

### What package manager are you using?

npm

### What operating system are you using?

Mac (Catalina 10.15.7)

### Description
I wanted to make a table were two rows are included conditionally.
Weirdly, if I only have **1** that is conditionally added, it works.
When it's **2**, it doesn't work.

It shows `500: Internal Error – Error: Uh oh, the Astro compiler encountered an unrecoverable error! Please open a GitHub issue using the link below.` which is why I am here now 😬

### ❌ Doesn't work:
```
[...]
<table>
        <tbody>
            <tr>
                <td>Normal row 1</td>
                <td>Content</td>
            </tr>
            {
            true ? (
                <tr>
                    <td>Conditional row 1</td>
                    <td>Content</td>
                </tr>) : null
            }
            {
            true ? (
                <tr>
                    <td>Conditional row 2</td>
                    <td>Content</td>
                </tr>) : null
            }
        </tbody>
</table>
[...]
```

### ✅ Works (second conditional removed)
```
[...]
<table>
        <tbody>
            <tr>
                <td>Normal row 1</td>
                <td>Content</td>
            </tr>
            {
            true ? (
                <tr>
                    <td>Conditional row 1</td>
                    <td>Content</td>
                </tr>) : null
            }
        </tbody>
</table>
[...]
```

### ✅ Works also (first conditional removed)
```
[...]
<table>
        <tbody>
            <tr>
                <td>Normal row 1</td>
                <td>Content</td>
            </tr>
            {
            true ? (
                <tr>
                    <td>Conditional row 2</td>
                    <td>Content</td>
                </tr>) : null
            }
        </tbody>
</table>
[...]
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ykj1cj?file=src/pages/index.astro

**Comment by drwpow** [comment]
> which is why I am here now 😬

You have come to the right place, friend! 😄 Will look into this.

**Comment by drwpow** [comment]
PR opened! The reason for the error being present within `<table>` is because in the HTML spec there are somewhat-special rules for parsing markdown within that. And there was a minor bug with expressions within `<table>` context only.

**Comment by stephanbogner** [comment]
> PR opened! The reason for the error being present within `<table>` is because in the HTML spec there are somewhat-special rules for parsing markdown within that. And there was a minor bug with expressions within `<table>` context only.

Wow that was fast 🚀 – thanks! 🙏
