### ISSUE TITLE
🐛 BUG: support local markdown plugins (remark & rehype)

### ISSUE THREAD

**Issue by tkon99** [withastro/astro#2097]
### What version of `astro` are you using?

0.21.7

### What package manager are you using?

npm

### What operating system are you using?

Windows (reproduced in Linux)

### Describe the Bug

Unable to use rehype plugin when importing from local file (e.g. `import('./rehypePlugin.mjs')`)

Expected behavior: plugin runs the same as when imported by package name (i.e. installed plugins), consistent with what's expected from `import`.

Usecase: development of project-specific plugins

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ajreza?file=astro.config.mjs

**Comment by natemoo-re** [comment]
Good catch, this definitely seems like something we should support!

**Comment by jasikpark** [comment]
It looks like this is a case where the code expects to be passed a dynamic import value rather than a static import 

https://stackblitz.com/edit/github-ajreza-p7jkpa?file=astro.config.mjs

```js
// astro.config.mjs
// Full Astro Configuration API Documentation:
// https://docs.astro.build/reference/configuration-reference

// @type-check enabled!
// VSCode and other TypeScript-enabled text editors will provide auto-completion,
// helpful tooltips, and warnings if your exported object is invalid.
// You can disable this by removing "@ts-check" and `@type` comments below.
import astroRemark from '@astrojs/markdown-remark';

import rehypePlugin from './rehypePlugin.mjs';

console.debug(rehypeSlug);
console.debug(await import('rehype-slug'));

// @ts-check
export default /** @type {import('astro').AstroUserConfig} */ ({
  // Enable Custom Markdown options, plugins, etc.
  markdownOptions: {
    render: [
      astroRemark,
      {
        remarkPlugins: ['remark-code-titles'],
        rehypePlugins: [
          ['rehype-autolink-headings', { behavior: 'prepend' }],
          ['rehype-toc', { headings: ['h2', 'h3'] }],
          ['rehype-add-classes', { 'h1,h2,h3': 'title' }],
          { default: (await import('rehype-slug')).default },
          { default: rehypePlugin },
        ],
      },
    ],
  },
});

```

It works for me to import the default function and then

**Comment by jasikpark** [comment]
So @tkon99 a workaround for you today is `{ default: (await import('./rehypePlugin.mjs')).default }` - you need the object so that some asumptions hold true for it??

**Comment by tkon99** [comment]
@jasikpark thanks, I'll try this out when I have some more time on my hands, will report back here when I've done so.
To be clear, this is still going to be supported as a static import?

**Comment by jasikpark** [comment]
I agree that it makes sense to support statically importing plugins, I think there's just some logic in `load-plugins.ts` that needs to be changed if it hasn't already been sorted in the last 29 days
