### ISSUE TITLE
🐛 BUG: Several pages of Astro docs are missing header styles

### ISSUE THREAD

**Issue by IanVS** [withastro/astro#2099]
### What version of `astro` are you using?

0.21.6

### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

I noticed that a few pages of the Astro production docs site had broken styles, particularly in the header and the theme switcher.  I narrowed the broken pages down to those which have Spanish versions that are `.astro` files, (but it's the English pages that are broken).  Interestingly, the Spanish pages are fine.

Through `git blame`, I determined that the styles broke starting with https://github.com/withastro/astro/pull/2052.

This is only seen in production builds, not the dev server.

Removing the call to `Astro.fetchContent()` in the Spanish pages makes the issue disappear as well.

### Link to Minimal Reproducible Example

https://docs.astro.build/guides/markdown-content/

**Comment by IanVS** [comment]
cc @drwpow, since you might have an idea of what is going on here.

**Comment by FredKSchott** [comment]
Fixed in https://github.com/withastro/astro/pull/2112

**Comment by IanVS** [comment]
That was a strange one, glad y'all got it figured out!  Great sleuthing work, @drwpow! 🕵️
