### ISSUE TITLE
🐛 BUG: Prod built html file doesn't have any css styles

### ISSUE THREAD

**Issue by amithgeorge** [withastro/astro#2101]
### What version of `astro` are you using?

0.21.8

### What package manager are you using?

npm

### What operating system are you using?

stackblitz

### Describe the Bug

The page `page-1` uses two layouts. Both layouts import their own css file. 

In dev-server, the page has proper styling. When the app is prod built, `dist/page-1/index.html` has no link tags for any css. 

Additional observations
- The `dist/page-1/index.html` has unnecessary classes added to its markup. I haven't written any css in `<style>` tags, for Astro to use scoped css classes. 
- There is an empty js file `dist/assets/page-1.hash.js` . My repo has no js. Thankfully the js file is not linked-to from any html file. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qoihup?file=src/pages/page-1.astro

**Comment by ElianVanCutsem** [comment]
Having the same issue here!

**Comment by Princesseuh** [comment]
Here's another repro that exhibit this issue: https://stackblitz.com/edit/github-zmryon

index.html doesn't have any styles (even though it should) while index2.html will. The only difference between the two files being that index2 has an additional link tag to a second css file.

**Comment by tkon99** [comment]
FYI, this seems to have broken in 0.21.7, CSS works as expected in 0.21.6.

**Comment by amithgeorge** [comment]
Updated the repro link to use `v0.21.11`. The issue still exists. https://stackblitz.com/edit/github-qoihup?file=package.json (Visit `/page-1` in the browser panel).

**Comment by EmilioLucky** [comment]
package.json add postbuild

"build": "astro build && node postbuild.js",

Add file postbuild.js

```
import fs from 'fs';
import path from 'path';

const distDir = path.join(process.cwd(), 'dist');
const indexPath = path.join(distDir, 'index.html');

let indexContent = fs.readFileSync(indexPath, 'utf8');
indexContent = indexContent.replace(/href="\/_astro\//g, 'href="_astro/');


///_astro/index.52f4aa6a.css

fs.writeFileSync(indexPath, indexContent, 'utf8');
console.log('Emilio Lucky - well done slash / removed');
```
