### ISSUE TITLE
🐛 BUG: Astro build fails for the blog starter example

### ISSUE THREAD

**Issue by amithgeorge** [withastro/astro#2102]
### What version of `astro` are you using?

0.21.8

### What package manager are you using?

npm

### What operating system are you using?

WSL2 AlmaLinux

### Describe the Bug

Running `npm run build` fails with error message 

```shell
'pathToFileURL' is not exported by __vite-browser-external
```

Full output

```shell
❯ npm run build

> @example/blog@0.0.1 build
> astro build

11:11 AM [config] Set "buildOptions.site" to generate correct canonical URLs and sitemap
'pathToFileURL' is not exported by __vite-browser-external, imported by node_modules/astro/dist/runtime/server/index.js
file: <path>/astro-blog-build-error/node_modules/astro/dist/runtime/server/index.js:33:9
31: };
32: import shorthash from "shorthash";
33: import { pathToFileURL } from "url";
             ^
34: import { extractDirectives, generateHydrateScript } from "./hydration.js";
35: import { serializeListValue } from "./util.js";
Error: 'pathToFileURL' is not exported by __vite-browser-external, imported by node_modules/astro/dist/runtime/server/index.js
```

----

I am not able to repro this on Stackblitz, because whenever I run the build command, I get a `wasm out of memory error`. I have updated the `Open in Stackblitz` link, so you may try your luck using it. 

### Link to Minimal Reproducible Example

https://github.com/amithgeorge/astro-blog-build-error

**Comment by matthewp** [comment]
Sorry about that, fixing right now.
