### ISSUE TITLE
🐛 BUG: Regression between Astro 0.21.6 and 0.21.7

### ISSUE THREAD

**Issue by Princesseuh** [withastro/astro#2104]
### What version of `astro` are you using?

0.21.8

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

This is a weird one, if someone has a better idea for a title that'd be great. Doing a simple menu using a list with the following code:

```astro
---
  const menu = ["Menu Item 1", "Menu Item 2", "Menu Item 3"]
---

<header>
  <nav>
    {menu.map((item) => (
      <a href={`/${item.toLowerCase()}`}>
        {item}
      </a>
    ))}
  </nav>
</header>
```

Works in both 0.21.7/8 and 0.21.6. However, if I add another component to the same file (Hello.astro being just a div with Hello in it):

```astro
---
  import Hello from "./Hello.astro"
  const menu = ["Menu Item 1", "Menu Item 2", "Menu Item 3"]
---

<header>
  <nav>
    {menu.map((item) => (
      <a href={`/${item.toLowerCase()}`}>
        {item}
      </a>
    ))}
  </nav>

  <Hello/>
</header>
```

It works in 0.21.6 but fails in later version, complaining that `item`, from my map doesn't exist. This only happens if you use `item` twice however, removing the href for instance will make it works.

Here's a repo with the exemple: https://github.com/Princesseuh/astro-regression

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rhjlop

**Comment by RafidMuhymin** [comment]
I am confirming the bug. And actually, it's not related to any component. If you put *any* HTML tag or component *after* (not before) the `<nav>` (check the reproduction) the error is shown.
