### ISSUE TITLE
🐛 BUG: Container queries silently produce incorrect output

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#2113]
### What version of `astro` are you using?

latest (I think)

### What package manager are you using?

unknown

### What operating system are you using?

unknown

### Describe the Bug

<img width="621" alt="Screen Shot 2021-12-03 at 8 44 48 AM" src="https://user-images.githubusercontent.com/622227/144640136-16dc3042-34ae-443b-86b2-45364b8972e2.png">

### Link to Minimal Reproducible Example

https://twitter.com/DasSurma/status/146603496855195648

**Comment by natemoo-re** [comment]
Closing in favor of https://github.com/withastro/astro/issues/2131 which provides more detail and links to upstream issue.
