### ISSUE TITLE
🐛 BUG: JSX in frontmatter components

### ISSUE THREAD

**Issue by johnhenry** [withastro/astro#2119]
### What version of `astro` are you using?

0.21.10

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

In previous iterations (< 0.21) one could define simple components using JSX in front matter, like so:

```astro
---
const wrap = text=><div>{text}</div>;
---
<body>{wrap(<h1>Hello, world!</h1>)}</body>
```

This now appears to be broken. The particular example throws an error, `error: Syntax error "\x0A"`
when building, but I've seen other errors where I think this is the cause.

I've glanced through the documentations and it looks as though this behavior may have not been defined previously;
so perhaps this is a feature request?

### Link to Minimal Reproducible Example

https://codesandbox.io/s/relaxed-glitter-lim9i?file=/src/pages/working.astro

**Comment by tylergaw** [comment]
@johnhenry There's an update about it in the 0.21 migration guide https://docs.astro.build/migration/0.21.0/#components-in-markdown

> Previously, you could create mini Astro Components inside of the Astro Frontmatter, using JSX syntax instead of Astro’s component syntax. This was always a bit of a hack, but in the new compiler it became impossible to support. We hope to re-introduce this feature in a future release of Astro using a different, non-JSX API.

**Comment by johnhenry** [comment]
@tylergaw thanks!
