### ISSUE TITLE
🐛 BUG: messed html in layout

### ISSUE THREAD

**Issue by kuworking** [withastro/astro#2122]
### What version of `astro` are you using?

^0.21.9

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Describe the Bug

*Reproducible in https://github.com/kuworking/bug_astro

Starting with the markdown example Astro starter theme, adding to `layouts/main.astro` this line

```jsx
  <body>
        <div>{content.astro?.headers.filter(h => h.depth === 1).map(h => <a href="">{h.text}</a>)}</div>
    <slot/>
  </body>
```
Causes a mess with `<a>` elements

*I have tried this in stackblitz and there it doesn't happen (I would say), but it does happen in local (as seen in the screenshot)

![image](https://user-images.githubusercontent.com/4474004/144704030-ff67ac2c-6bdb-4ed8-9d48-0de138d3a490.png)

### Link to Minimal Reproducible Example

https://github.com/kuworking/bug_astro

### Workaround

If you rewrite the `<a>` line as an external component, the render works as expected

**Comment by natemoo-re** [comment]
This was fixed in the latest release of Astro. See [`withastro/compiler`](https://github.com/withastro/compiler/pull/206). 

Please upgrade `astro` to `0.21.10` or above and try again. [See working StackBlitz reproduction](https://stackblitz.com/edit/github-cddq4w?file=src%2Fpages%2Fother.md).
