### ISSUE TITLE
🐛 BUG: Theme portfolio-svelte do not load svelte css files

### ISSUE THREAD

**Issue by bluellyr** [withastro/astro#2140]
### What version of `astro` are you using?

0.21.10

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

While testing and previewing ("npm run build && npm run preview") the theme [`portfolio-svelte`](https://github.com/withastro/astro/tree/main/examples/portfolio-svelte) the following urls:
1. `/project/mars-rover`
2. `/project/nested/lunar-eclipse`

do not load the following css files of the following Svelte components:
- Nav.svelte (/assest/Nav.svelte_svelte_type_style_lang.d700a8a9.css)
- Button.svelte (/assets/Button.svelte_svelte_type_style_lang.a3798a23.css)
- Footer.svelte

1. The `/project/mars-rover` only loads:
```html
<link rel="stylesheet" type="text/css" href="../../assets/mars-rover.34c5f9a8.css">
<link rel="stylesheet" type="text/css" href="../../assets/global.58ebf414.css">
```

2. The `/project/nested/lunar-eclipse` only loads:
```html
<link rel="stylesheet" type="text/css" href="../../../assets/global.58ebf414.css">
<link rel="stylesheet" type="text/css" href="../../../assets/mars-rover.34c5f9a8.css">
```

The `index`, `/projects` and `/about` pages loads all the css files correctly.

Questions:

1. I can not figure out why the style tags of the css files for the `Nav.svelte`, `Button.svelte` and `Footer.svelte` are not present on the html of the pages `/project/mars-rover` and `/project/nested/lunar-eclipse`, is there something wrong?
2. I notice that the Nav.svelte css and the Footer.svelte css are bundle on the same file `/assets/Nav.svelte_svelte_type_style_lang.d700a8a9.css`, should not be in separate files?

Thank you and great project!

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/tree/main/examples/portfolio-svelte

**Comment by bluellyr** [comment]
Hi,
The link to the "Link to Minimal Reproducible Example" iswrong.

The site (dist folder) created using `npm run build` using the official theme portfolio-svelte (without any modifications) can be viewed at `[https://astro-portfolio-svelte-dist.vercel.app/](https://astro-portfolio-svelte-dist.vercel.app/)`

The following urls do not load the css files of the svelte components:
- https://astro-portfolio-svelte-dist.vercel.app/project/mars-rover
- https://astro-portfolio-svelte-dist.vercel.app/project/nested/lunar-eclipse

Thank you

**Comment by jonathantneal** [comment]
@natemoo-re, is that Vercel link from us? If so, that example is very out of date. In the current release, those pages appear as expected.

Feel free to close this, if the links are updated or someone else’s

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:

A couple recent bug fixes cleaned up how building to subpaths is handled and should have this taken care of :+1:
