### ISSUE TITLE
🐛 BUG: astro's --version option does not work

### ISSUE THREAD

**Issue by hmvp** [withastro/astro#2143]
### What version of `astro` are you using?

0.21.11

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

```sh
$ npx astro --version
[Error: ENOENT: no such file or directory, open '/test_project/node_modules/astro/dist/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/test_project/node_modules/astro/dist/package.json'
}
```

That file does not exist indeed. `/test_project/node_modules/astro/package.json` does...

### Link to Minimal Reproducible Example

nvt

**Comment by jonathantneal** [comment]
Confirmed, this is not working in Astro v0.21.12.
