### ISSUE TITLE
🐛 BUG: Image url is not replaced with prod asset image url in all places where the image url is referred

### ISSUE THREAD

**Issue by amithgeorge** [withastro/astro#2145]
### What version of `astro` are you using?

0.21.11

### What package manager are you using?

yarn

### What operating system are you using?

Codesandbox

### Describe the Bug

Image is imported in an Astro file. The imported variable is provided as value to an `img` tag's `src` and `data-src` attributes. 

During dev build, both attributes have the correct value -  `src/images/astronaut.jpg`. 

In prod build, the `src` attribute value is correct `/assets/astronaut.hash.jpg`. The `data-src` attribute value is still the dev url `/src/images/astronaut.jpg`. I expect the `data-src` attribute value to also be the prod asset url. 

More details in the repro link. 

### Link to Minimal Reproducible Example

https://codesandbox.io/s/sharp-water-e9zoy?file=/src/pages/index.astro

**Comment by bluellyr** [comment]
Hi,
The link to the "Link to Minimal Reproducible Example" is wrong.

The site (dist folder) created using `npm run build` using the official theme `portfolio-svelte` (without any modifications) can be viewed at [https://astro-portfolio-svelte-dist.vercel.app/](https://astro-portfolio-svelte-dist.vercel.app/).

The following urls do not load the svelte css:
- https://astro-portfolio-svelte-dist.vercel.app/project/mars-rover
- https://astro-portfolio-svelte-dist.vercel.app/project/nested/lunar-eclipse

Thank you

**Comment by amithgeorge** [comment]
Since version `0.22.6` fixed a bunch of compiler bugs, I updated the repro hoping this might have been fixed. The issue persists.

**Comment by benjaminbarbe** [comment]
Same problem here. Nobody found a workaround?

**Comment by amithgeorge** [comment]
The issue got fixed for me with one of the newer 0.23.x or 0.24.x releases. The linked repro is giving me CodeSandbox website related errors, so I am not able to demonstrate the same. I am closing the issue. @benjaminbarbe if it is not solved for you with the newer versions, please feel free to re-open or create a fresh issue.
