### ISSUE TITLE
🐛 BUG: no CSS in production for projects with >1 page.

### ISSUE THREAD

**Issue by tkon99** [withastro/astro#2151]
### What version of `astro` are you using?

0.21.11

### What package manager are you using?

npm

### What operating system are you using?

Windows (reproduced in Linux)

### Describe the Bug

Weirdest bug. There is still no CSS tag included in `<head>` (i.e. it disappears) when using a layout component that's referenced by more than one page.

To reproduce (example below):

1. The example comes with two pages (index.astro & about.astro), first run `npm run build` and `npm run preview`, and observe the breaking CSS.
2. Then remove `about.astro` and run `npm run build` and `npm run preview` again, CSS is included correctly now.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2qvskx-cdcoua?file=src%2Fpages%2Fabout.astro&on=stackblitz

**Comment by drwpow** [comment]
This might have to do with some behavior of `<head>` tags. When using `layouts` for `.md` files, the layouts correctly are able to control the `<head>` tag.

However, when using layouts as a component wrapper for another page, there are issues with resolving `<head>` elements properly so they are likely getting dropped.

What I’d recommend doing is moving `<head>` and `<body>` into `pages/*.astro`. You can dedupe your style & head tags into a `<MainHead>` component, like so:

```astro
---
import MainHead from '../components/MainHead.astro';
import BaseLayout from '../layouts/BaseLayout.astro';
---
<html>
<head>
  <MainHead />
</head>
<body>
  <BaseLayout>
    <h1>Page Content</h1>
  </BaseLayout>
</body>
</html>
```

Does this work as a workaround for now?
Of course this will likely mean

**Comment by tkon99** [comment]
Does not seem to work either.

**Comment by amithgeorge** [comment]
@tkon99 The newest Astro version `0.21.12` had fixed a similar issue I had reported. I [forked your repro](https://stackblitz.com/edit/github-2qvskx-evqajf?file=package.json) just to check, your issue seems to be solved with the newer version. Please update and check.

**Comment by jonathantneal** [comment]
Thank you, @amithgeorge!
