### ISSUE TITLE
🐛 BUG: Empty Named Slot Nested In Other Slot Is Not Recognized As Empty Slot

### ISSUE THREAD

**Issue by philipp-tailor** [withastro/astro#2153]
### What version of `astro` are you using?

0.21.11

### Describe the Bug

When a named slot is passed to a component's default slot, and that component checks whether the slot is set by checking `Boolean(Astro.slots.default)`, the expression evaluates to `true`, even though no content is passed to the default slot. This used to behave as expected in `v0.20.x`, and broke with `v0.21.x`.

```astro
<!-- components/Header.astro -->

<header>
{
	Astro.slots.default ?
		<h1>
			<slot />
		</h1> :
		<h2>This is the default header</h2>
}
</header>
```

```astro
---
// layouts/Layout.astro
import Header from '../components/Header.astro'
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
  </head>
	<body>
    <Header>
      <slot name='header'/>
    </Header>
		<slot/>
	</body>
</html>
```

```astro
---
// pages/index.astro
import { Markdown } from 'astro/components'
import Layout from '../layouts/Layout'
---

<Layout>
	<article>
		<Markdown>
			`<Layout/>` has a named slot `'header'`, which is not set in this example. The named slot `'header'` is nested in a `<Header/>` component's default slot. When not setting this named slot, it would be expected, that the default slot is considered empty. This used to be the case in astro 0.20.0, and broke with the new compiler. Now, the slot is considered not empty anymore (but should).
		</Markdown>
	</article>
</Layout>
```

**Expected**:

`Boolean(Astro.slots.default)` evaluates to `false` when only an unused slot is passed to `Header.astro`.

**Actual**:

`Boolean(Astro.slots.default)` evaluates to `true` when only an unused slot is passed to `Header.astro`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nkh4mv?file=src/pages/index.astro

**Comment by jonathantneal** [comment]
This might be intended; where Astro returns whether there was the presence of a slot. Pining @natemoo-re to confirm.

**Comment by tony-sull** [comment]
We've been discussing changes to the `slot` API to avoid conflicts with native template `<slot>` behavior, would be worth making sure this behavior is defined either way :+1:

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:

This is expected behavior, though not ideal, in the current `<slot>` API 👍
