### ISSUE TITLE
🐛 BUG: Can't use Markdown components outside of Markdown pages

### ISSUE THREAD

**Issue by Princesseuh** [withastro/astro#2158]
### What version of `astro` are you using?

0.21.11

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

## The problem
Markdown components only works when used through Markdown pages, despite [what the documentation say on this subject](https://docs.astro.build/guides/markdown-content/#markdown-pages)

> These files can contain frontmatter, but are otherwise processed as plain markdown files and do not support components. If you’re looking to embed rich components in your markdown, take a look at the Markdown Component section.

When used through the Markdown component or through `Astro.fetchContent` with `astro.html`, they generate something like:
`<component-name> </component-name>` with parameters unchanged from their input or when self-closing, they'll sometimes corrupt the content by wrapping the entire markdown content in them

## Reproduction instructions
In the reproduction, go to /markdowntest for various tests trying to embed the blog exemple Author component like the Markdown page does, you'll notice that it doesn't work in all three cases

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3nen9t?file=src%2Fpages%2Fmarkdowntest%2Findex.astro&on=stackblitz

**Comment by Princesseuh** [comment]
So it turns out you have to use the <Content> component you get from Astro.fetchContent to do this, so this is more of a documentation issue than a bug

**Comment by jonathantneal** [comment]
I’m seeing `Hello!` in all 3 cases of the `markdowntest` page from your reproduction. Is this working differently in v0.21.12+?

**Comment by Princesseuh** [comment]
"Hello!" is the content of the Markdown file, it's supposed to show that and the component in the file

**Comment by pyronaur** [comment]
Just to clarify if anyone is searching for this.

You have to use the `Content` component that's returned by `Astro.props["your-content-slug"]` (like `Astro.props.post` for me).

Here's an example:

```astro
---
export async function getStaticPaths({ rss }) {
	const markdownFiles = await Astro.fetchContent('../content/**/*.md');
	const posts = published( markdownFiles );

	return posts.map((post) => {
		return {
			params: { post: post.slug },
			props: { post }
		};
	})
}

const { post } = Astro.props;
const { Content } = post;
---

<div class="content container">
	<Content />
</div>
```


Related commit where the issue I had was caused by using a Fragment component: https://github.com/OnWritingCode/simple-blog-template/commit/56812d3828891a087f30fe1d2d28bb32ec6a4931

And a real-life demo: 
https://github.com/OnWritingCode/simple-blog-template/blob/b7b240921be644df0d16fa7c9fb19f0ba1e0c15a/src/pages/%5Bpost%5D.astro#L1-L33

**Comment by Princesseuh** [comment]
As this is a documentation issue, I'm closing in favor of an issue I created on the docs repo: https://github.com/withastro/docs/issues/358
