### ISSUE TITLE
🐛 BUG: Vite not bundling assets in hoisted `<script>` tags

### ISSUE THREAD

**Issue by aFuzzyBear** [withastro/astro#2160]
### What version of `astro` are you using?

v0.21.11

### What package manager are you using?

yarn || npm

### What operating system are you using?

wsl2; ubuntu 20.04, reproduced on stackblitz

### Describe the Bug

Hi Troops

This issue that Im facing is relatively new I am lead to believe. 

Currently if one was to do this to an `.astro` component

```jsx
// Library or utils file 
//src/scripts/x.{ js || mjs }
export default ......//anything!!!
```
```astro
<script type="module">
import * as something from '/scr/scripts/x.mjs'
console.log(something)
</script>
```

In this above situation, one would expect Vite to be able to locate the file and be able to bundle that when in `PROD` into `dist/assets`

Presently this is not the case, in `DEV` mode the file is easily accessed as their is reference to the `src` directory in the server,

The problem lies mainly when being the site is being built.

I dont know what the expected or correct behaviour for this is, any advice or guidance on this matter would be greatly appreciated,

If this is possible it would greatly enhance the DX using Astro and in a selfish sense really excel `XElement` and the range of use-cases it can provide

Kindest Regards

Peter

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-syzdma-tidpbn?file=src/pages/index.astro

**Comment by matthewp** [comment]
Hey @aFuzzyBear, we only bundle scripts that have the `hoist` attribute.

**Comment by aFuzzyBear** [comment]
Hey dude, I have just tried that and its not working am afraid, its not coming anywhere near the build. =(

**Comment by matthewp** [comment]
@aFuzzyBear thanks for checking. If you wouldn't mind updating the stackblitz i can take a look at what's wrong here.

**Comment by aFuzzyBear** [comment]
@matthewp  💚  thanks for looking into this for me dude, that is the stackblitz updated, still the same issue persists, and vite is kicking up a fuss 

```bash
[vite] Internal server error: Failed to resolve import "/scr/scripts/x.js" from "src/pages/index.astro?html-proxy&index=0.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/projects/github-syzdma-tidpbn/src/pages/index.astro?html-proxy&index=0.js
  1  |  import * as Obj from '/scr/scripts/x.js'
     |                        ^
  2  |  import {answer} from 'src/scripts/y.mjs'
  3  |  //OR
      at formatError (/home/projects/github-syzdma-tidpbn/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:42212:46)
      at TransformContext.error (/home/projects/github-syzdma-tidpbn/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:42208:19)
      at normalizeUrl (/home/projects/github-syzdma-tidpbn/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:67278:26)
      at async TransformContext.transform (/home/projects/github-syzdma-tidpbn/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:67418:57)
      at async Object.transform (/home/projects/github-syzdma-tidpbn/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:42419:30)
      at async doTransform (/home/projects/github-syzdma-tidpbn/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:56766:29) (x2)
03:14 PM [astro] 404 /src/pages/index.astro    
```

**Comment by danramteke** [comment]
@aFuzzyBear on line `1` there, did you mean to spell it `scr`? Perhaps you meant `src`?

I downloaded the project to make that change but still have issues

**Comment by danramteke** [comment]
just got it to work locally

try in `index.astro`
```
<script type='module' hoist>
import p from '/src/scripts/x.js'
console.log(p.a)
</script>
```

and in `src/scripts/x.js` try

```
export default {
  a: 1,
  b: 2,
  c: 3,
  d: 4,
  e: 5,
};

```

**Comment by aFuzzyBear** [comment]
> just got it to work locally
> 
> try in `index.astro`
> 
> ```
> <script type='module' hoist>
> import p from '/src/scripts/x.js'
> console.log(p.a)
> </script>
> ```
> 
> and in `src/scripts/x.js` try
> 
> ```
> export default {
>   a: 1,
>   b: 2,
>   c: 3,
>   d: 4,
>   e: 5,
> };
> ```

thats great, however should yu go to prodution and build the site, could you tell me if it still is there

**Comment by danramteke** [comment]
@aFuzzyBear yep, tested both `yarn dev` and `yarn build && yarn preview` 🥺

**Comment by matthewp** [comment]
Hey @aFuzzyBear, sorry for taking so long to get to this one. I checked it out and there are a couple of problems with the example. The inline script contains a path to `scr/scripts/y.mjs` (should be `src/`), and in one file it is `export default x = {...` which it should just be `export default {...`. Fixing those things made it work for me. Here's a fixed example: https://stackblitz.com/edit/github-syzdma-suwv57?file=src%2Fpages%2Findex.astro

**Comment by aFuzzyBear** [comment]
Hey @matthewp d'oh that was my mistake, I appreciate you taking a look however the issue still exists that they are not being respected during `PROD` however I do feel that this issue would be satisfied once `local:` comes into existence, Im happy to wait on this one
