### ISSUE TITLE
📘 DOC: "Language does not exist" message

### ISSUE THREAD

**Issue by kuworking** [withastro/astro#2161]
From a while I've started to see these messages in the console, they delay the rendering but doesn't appear to break anything (only tested in dev mode, haven't identified a specific cause even though before I didn't see them, so it's something I've added to the site)

What do they mean? (I ask it here since if it is not a bug this could be included in the docs)

```
Language does not exist: js/4
Unable to load the language: js/4
Language does not exist: js/9
Unable to load the language: js/9
```

astro 0.21.10
node 16.13.1 
npm 8.1.2
Windows10

**Comment by FredKSchott** [comment]
Not sure if this is still an issue, so closing out of caution. If it is still an issue, you can reopen here: https://github.com/withastro/docs

**Comment by myakura** [comment]
@kuworking I got the same message, except the language is `Markdown`.

> Language does not exist: Markdown
> Unable to load the language: Markdown

It seems to be coming from markdown files that have fenced code blocks with language. In my case, one of the markdown files contains multiple code blocks with `Markdown` set:

```
```Markdown
```

So you might want to check out your markdown files. I think there are code blocks with `js/4` and `js/9`.
