### ISSUE TITLE
🐛 BUG: Vue components do not use classes from global.css unless they are used before in somewhere else with tailwindcss

### ISSUE THREAD

**Issue by yamac-kurtulus** [withastro/astro#2165]
### What version of `astro` are you using?

0.21.11

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I am using Vue and Astro with tailwindcss. Html tags inside .vue template is not being styled, unless those classes are used in other .astro classes. I am guessing this has to do weither with how vite caches the css, or classes in vue files are skipped at somepoint while purging and bundling the css. 

This might not even be related to tailwindcss, I just encountered this one when I was using tailwind.

 ### Example:

Reproduction of the bug takes a few steps. 

1. To set up, I have started an astro project with `astro init` from scratch and chose vue. Then added tailwindcss as instructed. I will focus on a vue component and an astro page: `VueText.vue` and `index.astro`. A single div is of concern in both of them so i have given them 2 ids: vue-div and astro-div. 

**pages/index.astro**:
```
---
import VueText from '../components/VueText.vue';
---
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href={Astro.resolve('../styles/global.css')}>
</head>
<body>
    <main>
        <div id="astro-div" class="text-6xl">
            This is from index.astro page
        </div>
        <VueText client:visible />
    </main>
</body>
</html>
```

**components/VueText. vue**
```
<template>
  <div id="vue-div" class="text-6xl text-purple-700">
    <div>This is from vue component</div>
  </div>
</template>

<script>
</script>
```
Also **styles/global.css**:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

2. At this stage I started the server and, here is a screenshot of my output:
![image](https://user-images.githubusercontent.com/32689837/145316739-7ff6ee0c-ed3a-4779-b1b7-734f33321cca.png)
As you can see here, class `text-6xl` on both div works but not the `text-purple-700` on the vue-div. 

3. I add `text-red-500` to the astro-div it changes the color as you can see:
![image](https://user-images.githubusercontent.com/32689837/145317403-50be9d09-eff6-4649-8940-4a8f0a38b6d5.png)

4. And if I change `text-red-500` of astro-div to `text-purple-700` (which is already on vue-div) `index.astro`, then both change color. 
![image](https://user-images.githubusercontent.com/32689837/145319372-2b4c4ea4-b6ac-49ea-8a2b-f655cd5425b8.png)

5. Then I change vue-div to `text-red-500` and it works. Apparently the class should be used somewhere before vue can use it. I used colors here but Same goes for other classes too.
![image](https://user-images.githubusercontent.com/32689837/145319580-311966c1-ccbd-4df7-8dd1-27ef90d12eb2.png)

6. But still not finished, I used `text-red-500` and `text-purple-700` on both divs. Now I change astro-div to `text-green-500` (a new color) and save. 
![image](https://user-images.githubusercontent.com/32689837/145320503-b1666f52-3205-491c-a48e-17fd0971a53d.png)

7. Then I change vue-div back to `text-purple-700` and it works fine
![image](https://user-images.githubusercontent.com/32689837/145321039-c6ed855c-7aed-4db9-904f-d09b5fd03f5a.png)

8. Then I change vue-div to `text-green-500` and I save ONLY the `VueText.vue`. Do not save the `index.astro`. Nothing changes.
![image](https://user-images.githubusercontent.com/32689837/145321039-c6ed855c-7aed-4db9-904f-d09b5fd03f5a.png)

9. Finally, I save  `index.astro` and vue-div becomes green
![image](https://user-images.githubusercontent.com/32689837/145321468-e6bea41a-8141-4bef-b4b1-995a1f26f9b4.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nl4a2q?file=src/pages/index.astro

**Comment by yamac-kurtulus** [comment]
Adding style in the vue class works as expected, despite it is an apply directive for tailwind. 
```
<template>
  <div id="vue-div" class="text-6xl label-div">
    <div>This is from vue component</div>
  </div>
</template>

<style>
.label-div{
  @apply bg-blue-600 text-red-900;
}
</style>
```

But I need to save the astro page or component that the Vue component is used in (i.e. `index.astro`) for HMR to refresh in dev mode.

**Comment by yamac-kurtulus** [comment]
Apparently this might be a problem with tailwind and/or vue itself. Vue-cli tailwind plugin uses a version of tailwind compatible with postcss 7.

Downgrading to these dependencies fixes the problem. Though I think the issue is still worth exploring.
```
"dev-dependencies": {
    "@tailwindcss/postcss7-compat": "^2.2.17",
    "autoprefixer": "^9",
    "postcss": "^7",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.17",
  }
```

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:

I think a few recent changes in the `astro@next` branch related to updating Vite and switching to their dev server should have this all fixed up now :+1:
