### ISSUE TITLE
🐛 BUG: Astro CLI Config `devOptions.hostname` not displaying local network IP.

### ISSUE THREAD

**Issue by austinjherman** [withastro/astro#2177]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

After following the [quickstart](https://docs.astro.build/quick-start/) and setting `devOptions.hostname` to `0.0.0.0`, I see the following output in my terminal:

```bash
06:45 PM [astro] Server started                               71ms
06:45 PM [astro] Local: http://0.0.0.0:3000/
```
Shouldn't there be another line with the local network address?

Can't really do a minimal reproduction ... You can just follow the quickstart, change `devOptions.hostname` to `0.0.0.0`, and get the same output.

### Link to Minimal Reproducible Example

https://docs.astro.build/quick-start/

**Comment by jonathantneal** [comment]
> Shouldn't there be another line with the local network address?

That’s a nice suggestion, for when `0.0.0.0` is used. I think we should also use `0.0.0.0` as the default.

```
00:00 AM [astro] Local: http://0.0.0.0:3000/
00:00 AM [astro] Network: http://192.168.0.1:3000/
```

**Comment by natemoo-re** [comment]
Would be very nice to copy what Vite is doing here.

<img width="309" alt="Screen Shot 2022-03-07 at 3 49 28 PM" src="https://user-images.githubusercontent.com/7118177/157123780-494772b0-a8c7-44d8-836c-36588e9ad8bd.png">
