### ISSUE TITLE
🐛 BUG: named imports of *some* reactstrap components don't work

### ISSUE THREAD

**Issue by sgruenholz2** [withastro/astro#2182]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Using the reactstrap component library, I expected that I would be able to use their named exports like:
`import {Badge, Button} from "reactstrap"`

- Button worked. 
- Badge did not, failing with a "cannot read properties of undefined" error. 

To workaround this, I had to create and reference my own Badge.jsx component, and wrap the reactstrap version like:
`
import React from "react";
import {Badge as RSBadge} from "reactstrap";
const Badge = props => <RSBadge {...props} />;
export default Badge;
`
Not sure if this is something that you plan to fix so that it "just works" or if just the docs need to be updated to watch out for cases like this.

As for why it worked for the one and not the other, looking at their component definitions, their Button uses `class Button extends React.Component` whereas their Badge is just a functional component. Guessing that was the key difference?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lkbbtb-k7lzx9?file=src/pages/index.astro

**Comment by jonathantneal** [comment]
Confirmed. Thanks for the reproduction. And here’s a forked version with the failure in action.

https://stackblitz.com/edit/github-lkbbtb-b9xwwe?file=src%2Fpages%2Findex.astro

**Comment by matthewp** [comment]
Latest failure: https://stackblitz.com/edit/github-lkbbtb-kdfz9z?file=astro.config.mjs,package.json

**Comment by matthewp** [comment]
Ah, it looks like Badge requires a `tag` prop but they don't document this. This is a working version:

```jsx
<Badge className="foo" color="primary" tag="span">New</Badge>
```

https://stackblitz.com/edit/github-lkbbtb-kdfz9z?file=astro.config.mjs,package.json,src%2Fpages%2Findex.astro
