### ISSUE TITLE
🐛 BUG: CSS Modules don't get injected during build

### ISSUE THREAD

**Issue by tusharsadhwani** [withastro/astro#2183]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

This bug is reproducible in 0.21.0 as well, but not on 0.20

I unfortunately don't have a minimal reproducible example yet. But, I'm seeing this issue in my [blog site](https://github.com/tusharsadhwani/blog) which is based on the blog starter template. You should be able to reproduce it by cloning the repo and running it.

Here's the bug:

- When running `npm run build`, the css inside the [Newsletter](https://github.com/tusharsadhwani/blog/blob/master/src/components/Newsletter/Newsletter.module.css) and [ThemeSwitch](https://github.com/tusharsadhwani/blog/blob/master/src/components/ThemeSwitch/Switch.module.css) is not injected in the html's `<head>` tag.
- When running `npm start` (dev mode), the modules _might_ get rendered. Sometimes both of them render, sometimes just one, sometimes neither. They show up as 0, 1 or 2 `<link rel="text/css">` tags inside the `<head>` tag. It changes on each refresh, with each render taking 20 seconds.

### Link to Minimal Reproducible Example

https://github.com/tusharsadhwani/blog

**Comment by KenCorbettTruepic** [comment]
This was fixed for me with the 0.21.12 build.

**Comment by tusharsadhwani** [comment]
Doesn't work for me in 0.21.12 either :/

**Comment by jonathantneal** [comment]
Also seeing things working. However, I did update the `package-lock.json`, which is out of sync with the `package.json` file.
