### ISSUE TITLE
🐛 BUG: Failed to resolve import for local NPM packages (500 Internal Error)

### ISSUE THREAD

**Issue by markteekman** [withastro/astro#2186]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to locally develop components for an Astro NPM package ([accessible-astro-components](https://github.com/markteekman/accessible-astro-components)) using the following locally installed path:

```
{
  "name": "accessible-astro-starter",
  "version": "1.1.2",
  "private": true,
  "scripts": {
    "start": "astro dev",
    "build": "astro build"
  },
  "devDependencies": {
    "accessible-astro-components": "file:../accessible-astro-components",
    "astro": "^0.21.12",
    "autoprefixer": "^10.4.0",
    "stylelint": "^13.13.1",
    "stylelint-config-standard": "^22.0.0"
  }
}
```

Just like with the installed package from NPM I'm importing my components and using it like such:

```html
---
import { Accordion, AccordionItem } from 'accessible-astro-components'
---
<Accordion>
  <AccordionItem
    header="First Item"
  >
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quasi nobis optio? Qui in quo accusantium debitis sapiente obcaecati magnam incidunt sit. Molestiae exercitationem quibusdam quod veritatis laboriosam est tenetur. </p>
    <a href="#">Tab to me!</a>
  </AccordionItem>
  <AccordionItem
    header="Second Item"
  >
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quasi nobis optio? Qui in quo accusantium debitis sapiente obcaecati magnam incidunt sit. Molestiae exercitationem quibusdam quod veritatis laboriosam est tenetur. </p>
  </AccordionItem>

  <!-- ... -->

</Accordion>
```

Which results in the following error:

<img width="1472" alt="Schermafbeelding 2021-12-11 om 11 43 01" src="https://user-images.githubusercontent.com/3909046/145673786-81c12e46-43c7-419e-a3d5-6c899d8306fc.png">

I checked and the package is available in the `node_modules`:

<img width="195" alt="Schermafbeelding 2021-12-11 om 12 18 04" src="https://user-images.githubusercontent.com/3909046/145674542-f2f8922d-c5fe-457b-a337-db64fdfc6934.png">

There's no problem when using the package published on NPM but I'm trying to develop and test my components locally first, before publishing a version which I know works. My workaround now is developing the components in a separate project, then including them in the package, publishing a new version of that package and then test it again using the published version. Sometimes I still get a bug or two this way so it's not ideal to have to keep changing the versions due to that.

For some reason I was able to reproduce the error in the CodeSandbox example using the published version.

_**NOTE**: This **does** work when using the published NPM package and not when referencing the package locally (which is why I submitted this issue) or, for some reason, when installing the package in CodeSandbox :)_

### Link to Minimal Reproducible Example

https://codesandbox.io/s/headless-http-se04x?file=/package.json

**Comment by jonathantneal** [comment]
Confirmed this issue. Thanks for raising it. I would expect `file:` packages to work, as well.

As a workaround, tho, you can also develop components alongside a demo in a monorepo.

[StackBlitz Example](https://stackblitz.com/github/snowpackjs/astro/tree/jn.update-component-template/examples/component?on=stackblitz)

☝️ And this is being added to Astro, [soon](https://github.com/withastro/astro/pull/2203).

**Comment by markteekman** [comment]
Thanks for looking into it @jonathantneal! And thanks for sharing that workaround, that'll do just fine in the meantime 😊 Really looking forward to it being added to Astro, great work! 👍🏼

**Comment by Chris-Shivom** [comment]
What was the fix for this? Also have this issue and the StackBlitz example link isn't working :(

**Comment by surgeharb** [comment]
Hello, @jonathantneal @markteekman it seems that the above link for the workaround is broken. Can you please share what should be done in this thread, please? 🙏

**Comment by markteekman** [comment]
@surgeharb I never found a moment to use this workaround.. 🤔 Maybe @jonathantneal can update the StackBlitz example 🙂

**Comment by tony-sull** [comment]
@surgeharb There's now a [component example](https://github.com/withastro/astro/tree/main/examples/component) project setup to demo importing components from other packages in a monorepo :+1:

**Comment by markteekman** [comment]
Awesome, thanks @tony-sull!

**Comment by markteekman** [comment]
There's now also extended information about this in the documentation and I think it's a better approach to using `file:`, so I'm closing this issue in regard of that 😄 

https://docs.astro.build/en/guides/publish-to-npm/
