### ISSUE TITLE
🐛 BUG: Raw markdown page incorrectly encodes some characters, e.g. ' becoming â€™

### ISSUE THREAD

**Issue by Janne252** [withastro/astro#2187]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Viewing a raw markdown page, e.g. `/content` (`./src/pages/content.md`) results in incorrectly encoded characters, e.g. `'` becomes `â€™`.

Markdown rendered via `<Markdown content={...} />` doesn't have this issue.
See the Minimal Reproducible Example for a demonstration.

- The default page loads `./src/pages/content.md` to a `<Markdown />` component which correctly displays the character `'`.
- Click the "See the content on /content" link or change the browser preview's path to `/content`. For some reason the `'` character is now displayed as `â€™`. Additionally the unicode character `↩` rendered in footnotes is also incorrectly encoded.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/winter-lake-x65bm?file=/sandbox.config.json

**Comment by Janne252** [comment]
This likely isn't a bug at all. The raw markdown page doesn't have `<meta charset="utf-8" />`. Not sure if the default encoding should be part of the default / fallback layout when no layout is defined.

**Comment by jonathantneal** [comment]
That is correct, @Janne252. I think the default template for Markdown files should include `utf-8` by default.

**Comment by FredKSchott** [comment]
I believe that this has been fixed in #2654

**Comment by rudifa** [comment]
This is still (or again ?) a problem in astro v3.0.5:

To reproduce, follow the [tutorial](https://docs.astro.build/en/tutorial/0-introduction/) to [Write your first Markdown blog post](https://docs.astro.build/en/tutorial/2-pages/2/), create the file `post-1.md`, insert the text including `What's next` and connect it up as explained in the tutorial. 

The browser displays `Whatâ€™s next`.

**Comment by HurdyGutty** [comment]
Adding to @rudifa  comment, it seems that there are encoding problems while running in dev environment but not in production.

**Comment by rudifa** [comment]
Confirmed: the problem is present in the `dev` build, but absent from `build` + `preview`.

**Comment by Hime-Hina** [comment]
For those who encounter this problem while following the tutorial, please read [markdownmdx-layouts](https://docs.astro.build/en/core-concepts/layouts/#markdownmdx-layouts). Then, add `<meta charset="utf-8">` to the `<head>` section of your layout file.

**Comment by tohagan** [comment]
> For those who encounter this problem while following the tutorial, please read [markdownmdx-layouts](https://docs.astro.build/en/core-concepts/layouts/#markdownmdx-layouts). Then, add `<meta charset="utf-8">` to the `<head>` section of your layout file.

I'm sure that would makes *after* you've done the tutorial but not at the start!

**Comment by Kiailandi** [comment]
IMHO, given that this is encountered in the tutorial, a possible temporary patch could be to remove text that is using the ' character from the tutorial itself.

It could be daunting for people not used to markdown and escaping issues to face this problem without being able to fix it during the very first steps..

**Comment by tohagan** [comment]
> IMHO, given that this is encountered in the tutorial, a possible temporary patch could be to remove text that is using the ' character from the tutorial itself.

Yes agreed ... and when the tutorial covers **layouts**, add instructions to include `<meta charset="utf-8">` to the `<head>` section of the layout file with some explanation as to why.

**Comment by dillionmegida** [comment]
I encountered this bug and here's what I was doing wrong and what worked for me.

I had a `Layout` component:

```html
<Header />
<slot />
```

and a `BaseDocument` component:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <!-- others -->
  </head>

  <body>
    <slot />
  </body>
</html>
```

Then I used both for my page like this:

```html
<Layout>
  <BaseDocument>
    <!-- stuff -->
  </BaseDocument>
</Layout>
```

And this was the problem. Even though I had `<meta charset="utf-8" />`, it still didn't fix the encoding because `BaseDocument` is a child of `Layout`. It makes sense because `html` should be the root element (with the `head` tag) and not something else.

The fix for this was putting `Layout` as a child of `BaseDocument` instead:

```html
<BaseDocument>
  <Layout>
    <!-- stuff -->
  </Layout>
</BaseDocument>
```

**Comment by mohamed-elbermil** [comment]
I don't comment often, but I wanted to thank you immensely. You saved my life.
