### ISSUE TITLE
🐛 BUG: 4xx added to sitemap, built in directory

### ISSUE THREAD

**Issue by coelmay** [withastro/astro#2195]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm/yarn

### What operating system are you using?

Mac

### Describe the Bug

Similar to #1944 and #2129 other 4xx code pages (e.g. 403, 410) are also built to `dist/[code]/index.html` and are added to the sitemap.

I feel that all status codes that can/do return content should remain excluded from the sitemap, and build to `dist/[code].html` not `dist/[code]/index.html`.

GitHub repository including `dist` https://github.com/coelmay/status-code-pages-bug

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-q5pdpt

**Comment by natemoo-re** [comment]
Interesting! I originally made https://github.com/withastro/astro/pull/2137 to handle any `/[0-9]{3}/` but got feedback that it was too aggressive. I think this confirms that's what users expect, though! Maybe just `/[45][0-9]{2}/` should get this behavior?

**Comment by coelmay** [comment]
`/[45][0-9]{2}/` would also include [418 I'm a teapot](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418) 😄

**Comment by coelmay** [comment]
I do feel the regex method is a little overkill given there are 29 client responses codes (4xx) and 11 server error response (5xx) listed on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) and even less in [RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616) and [RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231). Add to this some of these responses may never see use with an Astro built site (other than 404 and 410, I'm not sure, for instance, how much customisation there is for a Netlify deployed site with 4xx, let alone 5xx, responses.)

Perhaps changing
https://github.com/withastro/astro/blob/fc5f4163826f5aaf7db95d630b306d5aec33516e/packages/astro/src/vite-plugin-build-html/index.ts#L24
to (assuming `name` below is **String**)
```javascript
const STATUS_CODES = [ '403', '404', '410', '429', /* and the rest */]
```
Then changing
https://github.com/withastro/astro/blob/fc5f4163826f5aaf7db95d630b306d5aec33516e/packages/astro/src/vite-plugin-build-html/index.ts#L432
to 
```javascript
if (STATUS_CODES.find(code =>  code === name))
```
might work just as well.
