### ISSUE TITLE
🐛 BUG: Using svelte npm component with vite and astro

### ISSUE THREAD

**Issue by ptrxyz** [withastro/astro#2199]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Today I ran into a weird problem: I wanted to use [svelte-carousel](https://www.npmjs.com/package/svelte-carousel) on my Astro page, yet it didn't really work.

I assembled a minimal example here: https://github.com/ptrxyz/astro-problem-demo (does not work with Stackblitz due to some dependencies not being resolved there)

See `src/pages/index.astro`:
- the simple Svelte button component works quite fine, no problems there.
- ATTEMPT1: Line 33-37: my first try. Just use the component, yet it raises an error in Astro
- ATTEMPT2: Line 39-45: 2nd try, loading the component with `client:only`. Throws errors in dev tools.
- ATTEMPT3: Line 48: Wrapped loading of the component into a `onMount`-handler. Component can't be loaded either.

I discussed the issue on [Discord with Muhymin](https://discord.com/channels/830184174198718474/920331135265931264), while he could reproduce the error, he could also not see a solution.

We tried to fix it, the closest to success was this: I modified my astro config and added the problematic libraries (non ES modules) to `vite.optimizedDeps.include` as well as to `vite.ssr.external`
```js
export default {
  vite: {
    optimizeDeps: {
      include: ["lodash.isequal", "lodash.clonedeep", "lodash.get"],
    },
    ssr: {
      external: ["lodash.isequal", "lodash.clonedeep", "lodash.get"],
    },
  },
};
```
I uncommented ATTEMPT2 + ATTEMPT3, this resulted in a half rendered component and a correctly rendered component.
Removing either ATTEMPT2 or ATTEMPT3 however made everything go to waste again with errors on the console log.

The bug is reproducible with the code in the repo, yet it does not work with Stackblitz.

### Link to Minimal Reproducible Example

https://github.com/ptrxyz/astro-problem-demo

**Comment by VodnikAngus** [comment]
I used [svelte-carousel](https://www.npmjs.com/package/svelte-carousel) too And I think that the problem you're facing is Astro trying to build the component at build time but it can't do that, solution I would suggest is using `client:only` for those cases. This might be a bug, so I am recommending this only until the core team responds

**Comment by tony-sull** [comment]
This is working in the 1.0 beta of Astro :party:

I still couldn't get this to work in Stackblitz, looks like `svelte-carousel` is may be trying to access the local git binary via the `$PATH` env variable, but this worked for me 👇 

> NOTE: I used `client:idle` here but `client:only` also works.  The example in `svelte-carousel` would need a bit of updating to handle finding connecting to the carousel's `<div>` children since they wouldn't be server rendered with `client:only`

### src/components/Carousel.svelte
```svelte
<script>
    import Carousel from 'svelte-carousel'
  
    let carousel; // for calling methods of the carousel instance
    const handleNextClick = () => {
      carousel.goToNext()
    }
  </script>
  
  <Carousel
    bind:this={carousel}
  >
    <div>1</div>
    <div>2</div>
    <div>3</div>
  </Carousel>
  
  <button on:click={handleNextClick}>Next</button>
```

### src/pages/index.astro (snippet)
```html
---
import Carousel from '../components/Carousel.svelte';
---

<Carousel client:idle></Carousel>
```
