### ISSUE TITLE
🐛 BUG: map with return fails on .astro files

### ISSUE THREAD

**Issue by kuworking** [withastro/astro#2201]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

node 16.13.1 npm 8.1.2

### What operating system are you using?

Windows 10

### Describe the Bug

Without knowing if this is something of my repo, something general (then I'd do a repo), or a feature, if I use something like

```
  <div class="list">
              {Object.values(nutrition_table)
              .sort((a, b) => {
                const nameA = a.name.toUpperCase()
                const nameB = b.name.toUpperCase()
                return nameA > nameB ? 1 : nameA < nameB ? -1 : 0
              })
              .map(ing => <div>{ing}</div>
              )}
  </div>
```

it goes well, but if I modify it into this

```
  <div class="list">
              {Object.values(nutrition_table)
              .sort((a, b) => {
                const nameA = a.name.toUpperCase()
                const nameB = b.name.toUpperCase()
                return nameA > nameB ? 1 : nameA < nameB ? -1 : 0
              })
              .map(ing => {
                return <div>{ing}</div>
              })}
  </div>
```

Then I get 
```
Unexpected "return"
...
Error: Transform failed with 1 error:
```

### Link to Minimal Reproducible Example

no repo

**Comment by jonathantneal** [comment]
@kuworking, would you put up a working example on StackBlitz?

**Comment by kuworking** [comment]
> @kuworking, would you put up a working example on StackBlitz?

I have tried to reproduce it on StackBlitz, but that specific part didn't cause any error, so it's something specific to my repo.
I would say I have found this same error 2 or 3 times, and I workaround this by doing the logic between the `---` parts to move on.

So, I close the issue until I can make a simplified version of my repo that causes the error (and then I'll reopen it)
