### ISSUE TITLE
🐛 BUG: Cannot change projectRoot

### ISSUE THREAD

**Issue by FlavioSantoro92** [withastro/astro#2205]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I've initialized a project and copied the astro.config.mjs into the root project. Into this file I've put:
`projectRoot: '/app'`
but when I start the project I get this output:
` [astro] Missing pages directory: o/src/pages/`
Changint the projectRoot will result in other, apparently, random pages directory path.
This leads to impossibility of building 'cause it watch always in a empty (unexistent) dir and the only page I see in the browser is 404 default page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-i5ujrx?file=astro.config.mjs&on=stackblitz

**Comment by jonathantneal** [comment]
Hmm. I would have expected the same thing, but the [documentation](https://github.com/withastro/astro/blob/astro%400.21.12/packages/astro/src/@types/astro.ts#L53-L57) has me wondering if `projectRoot` is different.

> Where to resolve all URLs relative to. Useful if you have a monorepo project.

Should `projectRoot` be working as they expect, @matthewp? If so, then I can confirm this issue.

**Comment by boehs** [comment]
While it's a bit different `./` is ignored as a project root.

**Comment by matthewp** [comment]
I think this might only be supported as a CLI flag. We can't find the Astro config without knowing the root already.

**Comment by tony-sull** [comment]
Closing this out as unsupported behavior as far as the Astro config goes, the [--root CLI flag](https://docs.astro.build/en/reference/cli-reference/#--root-path) is the right approach here to make sure Astro knows where to find the config file
