### ISSUE TITLE
🐛 BUG: Tailwind + Svelte Error (PostCSS not configured in the Svelte Renderer)

### ISSUE THREAD

**Issue by snelgrove** [withastro/astro#2211]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

**Problem**
I'm working on a project composed of Astro, Svelte and Tailwind CSS. After updating from Astro `0.20.x` to `0.21.12`, I have been chasing a build error relating to Tailwind: `Semicolon or block is expected`, which is reported wherever I use inline CSS variants (e.g. `button:hover`) or attempt to apply Tailwind specific variants (e.g. `@apply md:w-11/12`). Interestingly, basic Tailwind styles *do* work.

**Possible Solution**
The solution seems to be that the custom vite config in `@astrojs/renderer-svelte` needs to include the preprocessor option `postcss: true` in order for PostCSS, and therefore Tailwind, to run on `.svelte` components.  

I don't see how a consumer of Astro can adjust the *renderer's* configuration from `astro.config.js`, but that might also be a good solution.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wys7r3

**Comment by MicLeey** [comment]
Running into this as well after upgrading to Astro 0.21 with styles that used to work in 0.20.x

Happens with both Tailwind 2.x and 3. 
Used to get eslint errors but the build worked, now I get no eslint error and the build errors.
```
Semicolon or block is expected
ParseError: Semicolon or block is expected
```

**Comment by ptrxyz** [comment]
I also ran into this just now. I also fixed it by manually editing `node_modules/@astrojs/renderer-svelte/index.js` but this seems to be a super hacky solution.
I also tried to add the preprocessor to a separate `svelte.config.js` config file but it seems to not work.
