### ISSUE TITLE
🐛 BUG: New astro project with svelte

### ISSUE THREAD

**Issue by suraj0901** [withastro/astro#2213]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Today i initialise new astro project with svelte and i encountered this
![image](https://user-images.githubusercontent.com/66919989/146389879-27b2c89c-573c-4d5b-bf26-fa000fa2db8d.png)
but it was working fine before 

### Link to Minimal Reproducible Example

https://bnmiqzypo--github--3000.local.webcontainer.io

**Comment by austinjherman** [comment]
Yes! I'm having this same problem. Sometime yesterday my whole dev environment stopped working and I'm seeing similar error messages. Also using svelte with astro, but on a mac.

**Comment by boehs** [comment]
Me too! What's the last working versions?

**Comment by sarah11918** [comment]
Confirming that this is also happening with our Svelte starter example from astro.new in CodeSandbox.

See the Discord thread for the "temporary workaround" of setting Svelte components to "client:only" to at least get the dev environment to start: https://discord.com/channels/830184174198718474/921107451854614538

**Comment by natemoo-re** [comment]
Based on this timeline, I'm guessing that the new version of `@sveltejs/vite-plugin-svelte` that went out is why things are breaking? Does pinning `@sveltejs/vite-plugin-svelte` to `1.0.0-next.28` resolve the issue for anyone?

**Comment by austinjherman** [comment]
I tried pinning it as a dev dependency in `package.json` [here](https://stackblitz.com/edit/github-zt4qgd?file=package.json&on=stackblitz). Still doesn't work in the sandbox though :/

Looking at the package-lock in that stackblitz, there are a couple different versions of `@sveltejs/vite-plugin-svelte` being used ranging from `1.0.0-next.28` to `1.0.0-next.32`.

**Comment by natemoo-re** [comment]
That narrowed it down, thanks @austinjherman! PR here https://github.com/withastro/astro/pull/2216
