### ISSUE TITLE
🐛 BUG: Vue components styles are missing in the production build when `client:only`

### ISSUE THREAD

**Issue by jimmyhayek** [withastro/astro#2225]
### What version of `astro` are you using?

0.21.13

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Vue components styles are correct in `dev` mode but missing in the production build when `client:only`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fxqlpn

**Comment by matthewp** [comment]
https://github.com/withastro/astro/issues/2231 is another example of this happening.

**Comment by matthewp** [comment]
Sorry for the silence, I'm looking into this now. I can see that the client:only styles do get built but are not linked to the page correctly, investigating more..

**Comment by shingonoide** [comment]
I have the same issue with React components.
Is there any workaround?

**Comment by songololo** [comment]
This is still not working for me on `1.0.0-beta.12`...

**Comment by songololo** [comment]
Tried bumping to `1.0.0-beta.17` and CSS via `<style>` sections is still not coming through for me on `client:only` vue components.

Any pointers?
