### ISSUE TITLE
🐛 BUG: Unmatched routes with getStaticPaths not redirecting to 404.astro

### ISSUE THREAD

**Issue by jonathantneal** [withastro/astro#2226]
### What version of `astro` are you using?

0.21.13

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The `404.astro` pattern does not seem to work with the current `[id].astro` pattern. Consider the following structure:

```
/
└── src/
    ├── public/
    └── pages/
        └── 404.astro
        └── [slug].astro
```

I would expect Astro to match routes in `[slug].astro` using `getStaticPaths`, and I would expect `404.astro` to be used whenever a route is unmatched.

Instead, the route error page is hit. The same is true for sites delivered with `astro dev` and `astro preview`.

[This came up recently in discord](https://canary.discord.com/channels/830184174198718474/845451724738265138/921313331313266708).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-r6xsps-whuwce

**Comment by natemoo-re** [comment]
- Browser should show 404 page
- Terminal console should log a warning that was previously in the browser
