### ISSUE TITLE
🐛 BUG: Elements renderend after a `<slot>` tag not targeted by JavaScripts `document.querySelector`

### ISSUE THREAD

**Issue by markteekman** [withastro/astro#2227]
### What version of `astro` are you using?

0.21.13

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm executing this small script to hide all direct children of the body:

```js
<script>
  const pageElements = [...document.querySelectorAll('body > *')]
  pageElements.forEach(element => {
    element.style.display = 'none'
  })
</script>
```

The expected result is for all the direct children of the body receiving the `display: none` property. However, this is not the case and this is the result:

<img width="592" alt="Schermafbeelding 2021-12-18 om 12 01 17" src="https://user-images.githubusercontent.com/3909046/146638666-295775cf-0e8b-4c67-a739-f12f0f09f807.png">

Everything after `<main>` is ignored. My own conclusion is that it is because of the `<slot>` tag that is present within the `<main>` tag, removing that now does give the expected result:

<img width="565" alt="Schermafbeelding 2021-12-18 om 12 05 50" src="https://user-images.githubusercontent.com/3909046/146638765-0fb7a7cc-b070-4a43-b418-5085d7311b5a.png">

This is the structure in my own DefaultLayout.astro file:

```html
<body>

    <!-- header -->
    <Header />

    <div>Another element</div>

    <div>One more</div>

    <!-- main -->
    <main id="main-content">

      <slot />

    </main>

    <!-- footer -->
    <Footer />

    <div>Last element</div>

    <div>I'm here too</div>

  </body>
```

I've tried reproducing an example on CodeSandbox and for some reason I'm not getting this kind of behavior here and all elements are hidden, even when using the `<slot>` tag.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/gallant-benji-jue3s?file=/src/layout/DefaultLayout.astro

**Comment by markteekman** [comment]
Adding `type="module"` to the `<script>` tag solves this problem. Keeping the issue open just in case if someone wanted to take a look at his.

**Comment by matthewp** [comment]
Ah yes, good catch! I think Vite is treating this script as a module, so indeed using the type is necessary.
