### ISSUE TITLE
📘 DOC: Search should only search selected language

### ISSUE THREAD

**Issue by altano** [withastro/astro#2229]
When searching with "English" selected I get results in other languages, some of them above the English results:

![image](https://user-images.githubusercontent.com/1009/146656007-d28c7f70-79e2-4ff7-b638-f45e7102bb19.png)
![image](https://user-images.githubusercontent.com/1009/146656028-5892e046-2061-410a-a838-b381c2740c40.png)

**Comment by FredKSchott** [comment]
I believe @JuanM04 has a PR out for this! We're moving other docs issues into the new docs repo (https://github.com/withastro/docs) but I'll leave this once since it's tied to that PR.

**Comment by tony-sull** [comment]
Docs [PR](https://github.com/withastro/docs/pull/119) was merged and deployed 🥳
