### ISSUE TITLE
🐛 BUG: Page keeps refreshing in dev mode

### ISSUE THREAD

**Issue by altano** [withastro/astro#2230]
### What version of `astro` are you using?

0.21.13

### What package manager are you using?

npm

### What operating system are you using?

Linux/Windows

### Describe the Bug

When using `npm run dev` about every 5-8 seconds the page refreshes:
https://user-images.githubusercontent.com/1009/146656529-61df02fb-e785-4583-91a5-139a1fa36f55.mp4

I'm not sure if this is intended or not.

On stackblitz (https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal) I can't reproduce the issue. It looks like Vite says it connects in the console and nothing refreshes. For me, locally, Vite never connects and then the page refreshes.

I'm developing on an Ubuntu container and then connecting to it in VS Code (Remote Extension) so the Astro server is running on Ubuntu and my local web browser is running on Windows. Port 3000 is automatically forwarded by VS Code. Is there another port needed to make Vite connect that isn't being discovered automatically? Usually the VS Code remote stuff works perfectly.

### Link to Minimal Reproducible Example

cannot repro on stackblitz

**Comment by altano** [comment]
The issue was the web socket was failing to connect on port 24678. I configured VS Code to forward port 24678 as well and then enabled the VS Code setting for "Remote: Restore Forwarded Ports" (`"remote.restoreForwardedPorts": true`) to make it so that I only have to forward the port once.

Everything works now and the issue was not Astro related.

**Comment by crabmusket** [comment]
I had the same issue when running in a Docker container, and fixed it by adding `-p 24678:24678` to my `docker run` command.

**Comment by SaulR07** [comment]
I have a similar problem since it does not refresh in docker, can you help me?
