### ISSUE TITLE
🐛 BUG: `client:only` components don't include CSS Module

### ISSUE THREAD

**Issue by altano** [withastro/astro#2231]
### What version of `astro` are you using?

0.23.13

### What package manager are you using?

npm

### What operating system are you using?

Linux/Windows

### Describe the Bug

CSS Modules with `client:only` components work in `astro dev` but NOT `astro build && astro preview`

Repro: Go to https://stackblitz.com/edit/github-8u4uez-b2m9uc?file=src/pages/index.astro

Expected: 
* EITHER: `ClientComponent`'s CSS module (`ClientComponent.module.css`) will be downloaded on page load, just like all other components.
* OR: it is documented that you can't use CSS Modules with `client:only`

Actual: `ClientComponent.module.css` is never downloaded and the component is unstyled.

NOTE: styling works in `npm run dev` but NOT `npm run build && npm run preview` so I think this is just a bug.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8u4uez-b2m9uc?file=src/pages/index.astro

**Comment by altano** [comment]
Looks like https://github.com/withastro/astro/issues/2225 might be a general issue for all components. Feel free to close this as a duplicate?

**Comment by matthewp** [comment]
Yep, let's combine this with https://github.com/withastro/astro/issues/2231, as this seems to be a general client:only issue. I'll try and take a look myself
