### ISSUE TITLE
🐛 BUG: Emoji no longer renders correctly in markdown in dev mode

### ISSUE THREAD

**Issue by e111077** [withastro/astro#2241]
### What version of `astro` are you using?

0.21.13

### What package manager are you using?

npm

### What operating system are you using?

Chrome OS (linux) & Windows (WSL)

### Describe the Bug

Since 0.21.0 emoji stopped rendering correctly in markdown files in dev mode. Works just fine in `astro build && astro preview`.

The following:

```md
🌞🌉 San Francisco 🌉🌞
```

now renders to:

```html
<p>ðŸŒžðŸŒ‰ San Francisco ðŸŒ‰ðŸŒž</p>
```

which is very 🥲 Sad Francisco 🥲 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6udjnd?file=src%2Fpages%2Findex.md&on=stackblitz

**Comment by e111077** [comment]
Hmm also noticed that apostrophe is rendering incorrectly

from:

```
'
```

to

```
â€™
```

**Comment by matthewp** [comment]
You need to set `<meta charset="utf-8">` in your head. Here's an example: https://stackblitz.com/edit/github-6udjnd-tw72mf?file=src%2Flayouts%2FMain.astro&on=stackblitz

**Comment by matthewp** [comment]
Note that the dev server in 0.20 was setting the charset for you, but with the move to Vite it doesn't do that. That's probably more correct, since not every production server is going to do so, so might as well add the meta tag.

**Comment by miguelgargallo** [comment]
> You need to set `<meta charset="utf-8">` in your head. Here's an example: https://stackblitz.com/edit/github-6udjnd-tw72mf?file=src%2Flayouts%2FMain.astro&on=stackblitz

Thanks
