### ISSUE TITLE
🐛 BUG: Lit-renderer hydration support polyfill is being called too late in prod build

### ISSUE THREAD

**Issue by e111077** [withastro/astro#2242]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm

### What operating system are you using?

Chrome OS (linux) & Windows (WSL)

### Describe the Bug

In the prod build (not dev), the [hydration support polyfills](https://github.com/withastro/astro/blob/main/packages/renderers/renderer-lit/index.js#L13) in renderer-lit are being called after the definition / import of `lit` itself.

This means that `LitElement` cannot be patched with hydration logic and instead of upgrading the template, it simply calls render again, duplicating the content

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hv51r1?file=src%2Fcomponents%2FCounter.js&on=stackblitz

**Comment by jonathantneal** [comment]
I can verify in a production build that `litElementHydrateSupport` is added at the end of the bundled JS.

**Comment by e111077** [comment]
Would it be possible to split this section into something like hydrationPolyfills "Pre" & "Post"

**Comment by e111077** [comment]
Can confirm that experimental build fixes!

**Comment by tony-sull** [comment]
Nice!  Going to close this out since it's fixed in with the new `--experimental-static-build` flag, that will become the default build process soon and in the meantime the experimental flag is a good workaround 👍
