### ISSUE TITLE
🐛 BUG: Passing `prop{prop.value}` does break Astro

### ISSUE THREAD

**Issue by coelmay** [withastro/astro#2243]
### What version of `astro` are you using?

0.21.13 (happens on 0.21.10 too)

### What package manager are you using?

yarn (and npm)

### What operating system are you using?

Mac

### Describe the Bug

*Terrible title. Hopefully someone an come up with a better one 🙃*

Given the component with two required props
```astro
---
const { name, description } = Astro.props;
---
<section id="acomponent">
  <h2>A Component</h2>
  <p>name: "{ name }"</p>
  <p>description: "{ description }"</p>
</section>

```
I would expect the following usage to fail as the `=` is missing.
```astro
<AComponent
  name={data.acomponent.name}
  description{data.acomponent.description}
/>
```

I detected this after using the W3C validator on a live site.

### Link to Minimal Reproducible Example

https://github.com/coelmay/astro-component-props-bug

**Comment by matthewp** [comment]
Talked this over and this is actually not a bug! It's valid to have attribute names without values (boolean attributes), but the { character is not valid as a name, and therefore it gets ignored, leaving on the value. 

This is indeed odd but HTML allows for this to happen and .astro syntax follows HTML.

Thanks for filing anyways, this was fun to research!

**Comment by coelmay** [comment]
Thanks @matthewp. I guess you mean attributes like `disabled` or `hidden`, in which case I completely agree.

In the way I was using this
```astro
<AComponent
  name={data.acomponent.name}
  description{data.acomponent.description}
/>
```
in a dynamic page the description was used in the head meta
```html
<meta name="description" content={description}>
```
which results in having no `content` ie.
```HTML
<meta name="description">
```
This is then not valid as per the [HTML standard](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element) which states
> If either name, http-equiv, or itemprop is specified, then the content attribute must also be specified.

**Comment by matthewp** [comment]
Any attribute can be a boolean attribute. It's obviously a mistake, but `description{data.acomponent.description}` could be an attribute name! It's very odd. 

I would recommend in your AComponent to have some fallback for when `description` is not provided. You could even throw if you wanted, this would help you spot these sorts of mistakes.
