### ISSUE TITLE
🐛 BUG: process.env.XXX not accessible

### ISSUE THREAD

**Issue by gqio** [withastro/astro#2244]
### What version of `astro` are you using?

0.21.13

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Unable to access process.env.XXX directly.

`XXX=true astro build/dev`

```
---
console.log(process.env.XXX) // output undefined
console.log(process.env) // output correctly an object with a prop XXX and value 'true'
const {XXX}= process.env
console.log(XXX)// output  correctly 'true'
---
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-haaaff?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by matthewp** [comment]
That is very strange! I cleaned up the example a little bit: https://stackblitz.com/edit/github-haaaff-nxqfrw?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by gqio** [comment]
Yes, indeed it caused us some trouble because it was correctly processed before our migration from the 0.20.x to 0.21.x
And it was used to inject plugins and scripts only on certain conditions but with 0 errors during the build.

**Comment by natemoo-re** [comment]
I think this is a Vite limitation. Vite _does_ support `process.env` access but only in 2.7.x. Astro is still pinned to 2.6.x while we work on https://github.com/withastro/astro/pull/1866

**Comment by zyj1022** [comment]
process.env.NODE_ENV can be development, but NODE_DEBUG is undefinded

**Comment by natemoo-re** [comment]
Moved the Vite upgrade to https://github.com/withastro/astro/pull/2424. Once that lands this will be unblocked.

**Comment by tony-sull** [comment]
[#2424](https://github.com/withastro/astro/pull/2424) landed!

Closing this out since it should be supported now that we are using Vite 2.7 🥳

**Comment by natemoo-re** [comment]
Re-opening this! It looks like you _can_ access `process.env` now, but it doesn't expose the local environment variables defined in `.env` files.
