### ISSUE TITLE
🐛 BUG: many of the examples seem to have invalid tsconfig.json

### ISSUE THREAD

**Issue by SteveALee** [withastro/astro#2275]
### What version of `astro` are you using?

main branch

### What package manager are you using?

n/a

### What operating system are you using?

n/a

### Describe the Bug

I spotted many of the examples / templates seem to have invalid `tsconfig.json`

eg https://github.com/withastro/astro/blob/main/examples/starter/tsconfig.json

There should be a top level `compilerOptions` as per https://devtut.github.io/typescript/tsconfig-json.html#create-typescript-project-with-tsconfig-json

### Link to Minimal Reproducible Example

https://devtut.github.io/typescript/tsconfig-json.html#create-typescript-project-with-tsconfig-json

**Comment by manigandham** [comment]
Looks like this has been resolved in https://github.com/withastro/astro/pull/2278

**Comment by SteveALee** [comment]
I agree, you search foo is better than mine. Thanks.

I won't close yet though, hopefully PR merge will close.

**Comment by SteveALee** [comment]
Seems I can't close this issue.
