### ISSUE TITLE
🐛 BUG: The local font files referred via css/scss isn't processed well in built css.

### ISSUE THREAD

**Issue by vipindigiqt** [withastro/astro#2276]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

I'm trying to reference my local font files which are in `public/assets/fonts/` (.woff, .woff2) through scss and I'm using `/assets/fonts..` to refer them.

Its all fine on local server, but breaks on CSS build. the relative font url is not correct in css.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/cool-jepsen-s83m7?file=/src/pages/index.astro

**Comment by vipindigiqt** [comment]
Update: I tried [Fontsource](https://fontsource.org/) as well but It's not working as well.

Still getting this weird (to me) asset ref in built css:

`@font-face{font-family:"Inter";font-style:normal;font-display:swap;font-weight:400;src:url(__VITE_ASSET__444c3024__) format("woff2"),url(__VITE_ASSET__054f12d0__) format("woff");`

**Comment by ahsath** [comment]
x2

**Comment by obnoxiousnerd** [comment]
@ahsath @vipindigiqt Not sure if you still have the issue, but I made [this script](https://gist.github.com/obnoxiousnerd/9fe57bf44fdcbd9efa6e3eb3aab91943) to replace the `VITE_ASSET` references with the correct file names, which you can run post-build.

**Comment by tony-sull** [comment]
Looks like this may have been fixed in a later version of Astro as @jonathantneal mentioned above

The `VITE_ASSET` issue above is tracked by [#2146](https://github.com/withastro/astro/issues/2146) and is currently blocked by an upstream issue and [PR](https://github.com/vitejs/vite/issues/6625) in Vite :+1:
