### ISSUE TITLE
🐛 BUG: CSS Modules don't get injected during build

### ISSUE THREAD

**Issue by tusharsadhwani** [withastro/astro#2282]
### What version of `astro` are you using?

0.22.1

### What package manager are you using?

npm

### What operating system are you using?

Linux (Pop!_OS 21.10)

### Describe the Bug

This is a continuation of #2183. The bug still persists for me.

### The bug

[My project](https://github.com/tusharsadhwani/blog) is using preact with css modules.

When doing `npm run build`, the `<link rel="text/css>` tags that should get injected into the `<head>` tag of the static pages, don't get injected.

When doing `npm start`, the tags don't appear on the first load, but then they start appearing as I refresh the page more.

### Steps to reproduce

```bash
git clone https://github.com/tusharsadhwani/blog
cd blog
npm install
npm run build  # or npm start
```

---

Here's a video of the bug:

https://user-images.githubusercontent.com/43412083/147495675-0d0c240a-6fd8-4d6d-81bc-deffdb7c5030.mp4

Notice that at first, the purple switcher on the top right of the page doesn't get loaded in the video. On second refresh, it gets loaded but the "subscribe" form on the bottom doesn't get loaded. On the third reload, both of them (and their respective css modules) get loaded. Those two (the switcher and the subscribe form) are  preact components.

### Screenshots

- `npm run build` output (The html from preact components gets rendered, but CSS doesn't)

  ![image](https://user-images.githubusercontent.com/43412083/147496394-cc1cac00-eb1a-44a9-b15b-99e633eb522b.png)

- No `<style>` tags at the end of `<head>` in the static output of `npm run build`:

  ![image](https://user-images.githubusercontent.com/43412083/147495831-11f16a2e-1160-4363-9258-61bfa756beaa.png)

- Just one, random `<style>` tag during `npm start`:

  ![image](https://user-images.githubusercontent.com/43412083/147495339-0d0d3ad4-87c8-404e-9516-3f939d1d1a81.png)

- Expected output (two `<style>` tags):

  ![image](https://user-images.githubusercontent.com/43412083/147495129-99db5f53-7c50-4088-9927-e7631bd4ed49.png)

**Comment by jonathantneal** [comment]
Verified using https://stackblitz.com/github/tusharsadhwani/blog?file=src%2Fpages%2Findex.astro

**Comment by tusharsadhwani** [comment]
Problem still persists with astro 0.23.0, is there any issue/discussion I can follow for updates?

**Comment by yavko** [comment]
Same here, but with everything not just css modules, im using postcss and sass as well

**Comment by matthewp** [comment]
What about if you use `--experimental-static-build`.

**Comment by yavko** [comment]
> What about if you use `--experimental-static-build`.

Thanks for the quick reply I'm currently testing it out, its just telling me to fix something about smartypants!

**Comment by yavko** [comment]
> What about if you use `--experimental-static-build`.

It appears to work!

**Comment by matthewp** [comment]
Awesome. Smartypants doesn't work well in ESM. I suggest using this config: https://github.com/withastro/astro.build/blob/ff7e3106810d6b642542497317b0f66a7ff11c0f/astro.config.ts#L27

Going to close because that flag will be the default in 0.24 (coming up next week, hopefully).

**Comment by yavko** [comment]
> Awesome. Smartypants doesn't work well in ESM. I suggest using this config: [withastro/astro.build@`ff7e310`/astro.config.ts#L27](https://github.com/withastro/astro.build/blob/ff7e3106810d6b642542497317b0f66a7ff11c0f/astro.config.ts#L27)
> 
> Going to close because that flag will be the default in 0.24 (coming up next week, hopefully).

Yeah thats actually what I used to see how to fix it haha.

**Comment by tusharsadhwani** [comment]
@matthewp That doesn't work for me unfortunately. I get a "cannot find built path" error for every preact component that I have:

```
[build] Error rendering: Error: Cannot find the built path for /src/components/ThemeSwitch/Switch.jsx
    at Object.resolve (file:///home/tushar/code/blog/node_modules/astro/dist/core/build/static-build.js:260:17)
    at generateHydrateScript (file:///home/tushar/code/blog/dist/chunks/index.27d454df.mjs:93:155)
    at renderComponent (file:///home/tushar/code/blog/dist/chunks/index.27d454df.mjs:442:28)
```

Using astro 0.23.4
