### ISSUE TITLE
🐛 BUG: sitemap.xml appends /index.html

### ISSUE THREAD

**Issue by lhermann** [withastro/astro#2285]
### What version of `astro` are you using?

0.22.1

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Generated sitemap appends `/index.html` to all paths when `buildOptions.pageUrlFormat: 'directory'` is used.

### Actual result:

```html
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>https://example.com/blog/post-1/index.html</loc>
   </url>
   <url>
      <loc>https://example.com/blog/index.html</loc>
   </url>
   <url>
      <loc>https://example.com/index.html</loc>
   </url>
</urlset>
```

### Expected result:

```html
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>https://example.com/blog/post-1/</loc>
   </url>
   <url>
      <loc>https://example.com/blog/</loc>
   </url>
   <url>
      <loc>https://example.com/</loc>
   </url>
</urlset>
```

### Link to Minimal Reproducible Example

https://github.com/lhermann/astro-sitemap-bug

**Comment by 684efs3** [comment]
I'm getting the same bug.

**Comment by arlair** [comment]
I also came across this while trying out astro. A believe this would work as a temporary fix in your package.json scripts (if you have sed on your computer):

`"postbuild": "sed -i -e 's/index.html//g' ./dist/sitemap.xml",`

**Comment by jonathantneal** [comment]
Confirmed. The routes should not require the trailing `index.html`.

> This URL must begin with the protocol (such as http) and end with a trailing slash, if your web server requires it.
> — https://www.sitemaps.org/protocol.html#locdef

**Comment by jonathantneal** [comment]
Good news! This was fixed in https://github.com/withastro/astro/pull/2335 🎉
