### ISSUE TITLE
🐛 BUG: blog template does not offer rss nor sitemap

### ISSUE THREAD

**Issue by rburgst** [withastro/astro#2288]
### What version of `astro` are you using?

0.22.1

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

According to the docs (https://github.com/withastro/astro/blob/main/examples/blog/README.md) the blog template should contain rss and sitemap. However, none of the two are implemented.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/github/snowpackjs/astro/tree/latest/examples/blog

**Comment by jonathantneal** [comment]
Confirmed. To enable it, I had to add a value to `buildOptions.site`.

**Comment by WebDevSimplified** [comment]
I am curious where the RSS feed can be found once the the correct options are enabled. I am not sure what the default route for it is.

**Comment by rburgst** [comment]
you have to custom code the rss feed
https://github.com/withastro/astro/blob/main/examples/blog-multiple-authors/src/pages/posts/%5B...page%5D.astro#L14
