### ISSUE TITLE
🐛 BUG: Multiple jsx elements with different props end up getting the same props on hydration

### ISSUE THREAD

**Issue by Kilian** [withastro/astro#2294]
### What version of `astro` are you using?

0.22.2

### What package manager are you using?

npm, yarn

### What operating system are you using?

Linux

### Describe the Bug

When a JSX component is instantiated in different places with different props, they end up getting the same Astro uid and the same props.

This seems to be the same bug as #844 and #846. 

The example below is structured as follows:

* index page
  * GridBlock.astro
    * Tickercard.astro 1
      * Ticker.jsx
    * Tickercard.astro 2
      * Ticker.jsx
    
The props are set in GridBlock.astro and then sent down to Ticker.jsx

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fkwapp?file=src%2Fcomponents%2FGridBlock.astro

**Comment by WebDevSimplified** [comment]
I am also running into this exact same issue. It appears that the components are rendering exponentially. If I try to render 3 of the same component it will hydrate the component 9 times on the client when it should only be 3. I am guessing this is what is leading to the bug.

**Comment by jonathantneal** [comment]
Verified! Great example, @Kilian. You are correct about the IDs matching, as well. We’ll get this fixed.

**Comment by diegoleme** [comment]
This also happens to me. I'm using vue.js.

**Comment by Kilian** [comment]
@jonathantneal do you have any leads yet, or a workaround?

**Comment by yusufhilmi** [comment]
Any updates to this problem? It happens with Vue components as well.
