### ISSUE TITLE
CSS optimisation is reordering styles in unpredicted way

### ISSUE THREAD

**Issue by georges-gomes** [withastro/astro#230]
Hi!

I'm using 0.0.12 successfully but migrating to 0.10.0 introduced an issue only at build.
I think this is related to css bundling of the new release.

I'm using global reset css and utility classes that I load on all the pages.
I just do
```
<link href="/css/reset.css" rel="stylesheet"/>
<link href="/css/global.css" rel="stylesheet"/>
```
in my base layout `head`.

In astro build of the latest version, the bundling of the styles creates a single chunck with all `reset.css`, `global.css` and scoped css of astro components. (great!)

But, the `reset.css` and `global.css` are at the end of the new file. 

It's different in dev mode where the scoped css astro component are loaded at the end of the `head` so after `reset.css` and `global.css`.

It creates different behaviour from dev and build, and I don't know how to implement css reset because I don't see any other way to say to astro: "hey! please load this css before anything else".

Thanks

**Comment by nonsponsored** [comment]
Running 0.23.7 and it seems how you link to `global.scss` affects the compile order of page and component CSS, when page and component CSS is set to global.

A test repo is available at https://github.com/nonsponsored/astro-css-ordering


## Case 1:

Linking `global.scss` in `index.astro` via: `<link rel="stylesheet" href={Astro.resolve("../styles/global.scss")} />`

- In dev, `h1` styling comes from `Component1.astro`. [Expected result]
- In production, `h1` styling comes from `_base.scss.` [Not expected result]

- Production compiled CSS order: `index.astro` styles, `Component1.astro` styles, `global.scss` styles [Not expected result]


## Case 2:

Linking `global.scss` in `index.astro` via: `<style global>@import "../styles/global.scss";</style>`

- In dev and production, `h1` styling comes from `Component1.astro.` [Expected result]

- Production compiled CSS order: `index.astro` styles, `global.scss` styles, `Component1.astro` styles [Not expected result]

Note there's a side effect with this approach, and nested styles in `_base.scss` don't get compiled correctly. For example, the `h1` pseudo element compiles to `h1{color:#639;&:before{content:"Style from: _base.scss"}}` 


## Expected Result

1. Component styles would always be appended to `global.scss`, allowing allowing component styles to utilize the cascade.

2. Production compiled CSS order: `global.scss` styles, `index.astro` styles, `Component1.astro` styles
