### ISSUE TITLE
🐛 BUG: Markdown Component, weird egde case

### ISSUE THREAD

**Issue by aFuzzyBear** [withastro/astro#2312]
### What version of `astro` are you using?

0.22.5

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

Hi team, 

I am submitting this on behalf of @askrodney from the discord support thread
https://discord.com/channels/830184174198718474/845451724738265138/927907325795250256

The use has reported issues that are reproducible in regards to a specific use case of the Markdown component.

```astro

<Markdown >
```javascript
import Twitter from './Twitter.svelte';
```
</Markdown>

<Markdown>
  ```html
    <script>
      import Twitter from './Twitter.svelte';
    </script>
  ```
</Markdown>
```

In both these instances `vite:dep-scan`  appears to be wanting to directly import the `.svelte` files, which is a very strange and unexpected behaviour.

```bash
Error: Build failed with 1 error:
xxxx : Could not resolve "./twitter.svelte" (the plugin "vite:dep-scan" didnt set a resolve directory)
```

This definitely feels more of a bug than a feature,

### Link to Minimal Reproducible Example

https://github.com/rodneylab/astro-markdown-codeblock/blob/main/src/pages/index.astro

**Comment by FredKSchott** [comment]
Fixed in Astro v0.24.0: https://stackblitz.com/edit/github-zqhkh9?file=src%2Fpages%2Findex.astro&on=stackblitz
