### ISSUE TITLE
🐛 BUG: <table> broken inside dynamic html

### ISSUE THREAD

**Issue by maltedickson** [withastro/astro#2331]
### What version of `astro` are you using?

0.22.7

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

The HTML tag `<table>` can't be used in [dynamic HTML](https://docs.astro.build/en/core-concepts/astro-components/#dynamic-html).

If I replace the `<table>` related tags with regular `<div>` tags, the problem disappears.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vvi5ju?file=src/pages/index.astro

**Comment by soluml** [comment]
Having the same issue, spent way too long trying to figure out what I was doing wrong. In my case, I was trying to use Dynamic HTML within a `<table><thead><tr>`, trying to add dynamic `<th>`. I noticed that if I switched the `<th>` to an `<li>` it built successfully. So it's almost like a weird DOM issue... as `<li>`'s aren't valid descendants of `<tr>` and are therefore moved outside of the table as seen below.

Using `<div>` in place of `<li>` still blows up.

![image](https://user-images.githubusercontent.com/589571/148565481-f512847f-defa-4705-b618-ec4c8d658900.png)

**Comment by jonathantneal** [comment]
I think this will be fixed as part of https://github.com/withastro/astro/pull/2193

**Comment by FredKSchott** [comment]
Fixed in Astro v0.24.0
