### ISSUE TITLE
🐛 BUG: Markdown files fail to compile when using objects/arrays as props

### ISSUE THREAD

**Issue by WebDevSimplified** [withastro/astro#2332]
### What version of `astro` are you using?

0.22.7

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

If you try to pass an array/object as a prop to a component in Markdown it will fail to render the component and will also sometimes lead to a failure to compile the page depending on the content that comes after the component.

The components will sometimes render properly if there are no spaces and/or double quotes in the object/array as shown below.

#### Broken: 
```
<Component value={{ key: "Value" }} />
```

#### Works: 
```
<Component value={{key:1}} />
```

Also somewhat related to this is it is impossible to pass double quotes as a prop to a component in a markdown file.

#### Broken: 
```
<Component value='"Hi"' />
<Component value={'"Hi"'} />
<Component value={`"Hi"`} />
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pqhj9j?file=src/pages/index.md

### Related Discord Conversation

https://discord.com/channels/830184174198718474/845451724738265138/926139042951741470

**Comment by natemoo-re** [comment]
Going to close this to consolidate in https://github.com/withastro/astro/issues/2332. Thanks!
