### ISSUE TITLE
🐛 BUG: Can't nest Astro components with <slot/>

### ISSUE THREAD

**Issue by tony-sull** [withastro/astro#2346]
### What version of `astro` are you using?

0.22.8

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I am trying to use one Astro component as a child to another Astro component using slots.

I'm able to use plain old HTML in the parent component's slot, but when using an Astro component for the slot the child component is never rendered and is being thrown into the slot as a raw string

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3bqujt-lpwy6r

**Comment by tony-sull** [comment]
One fun note, this only reproduces when props are used on the parent component

In the Stackblitz repro, updating `FeatureBlock.astro` so that it doesn't need to pass the `data` prop to `UIBlock` and the slotted content is rendered just fine

**Comment by Morritz** [comment]
Have you tried to change the passed prop name to solve it?

**Comment by natemoo-re** [comment]
Hmm this is a weird one! I'll take a look.

**Comment by tony-sull** [comment]
Fixed in PR [245](https://github.com/withastro/compiler/pull/245) 🥳
