### ISSUE TITLE
🐛 BUG: client directive with Vue + Tailwind throws the following error after page refresh "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelector')"

### ISSUE THREAD

**Issue by WoetDev** [withastro/astro#2352]
### What version of `astro` are you using?

^0.22.9

### What package manager are you using?

yarn

### What operating system are you using?

Windows (WSL)

### Describe the Bug

When running in development using `astro dev`, the Vue component `<HeadlessUI client:visible />` works as expected initially. However when doing a hard page refresh, then the following error is thrown and the interactivity no longer works: 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelector')
    at onVisible (visible.ts:10:29)
    at index.astro?html-proxy&index=0.js:2:1
onVisible @ visible.ts:10
(anonymous) @ index.astro?html-proxy&index=0.js:2
```

![image](https://user-images.githubusercontent.com/76952619/148696866-a9982124-3e7a-409c-b233-4ec0ba745be4.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/cool-wood-j7wez?file=/src/pages/index.astro:1277-1291

**Comment by emmanuelsw** [comment]
You have to use `client:only` because Headless UI uses client-side APIs like `document` and `window` that aren't available in node.

https://docs.astro.build/en/core-concepts/component-hydration/#mycomponent-clientonly-

**Comment by WoetDev** [comment]
Thanks, that was indeed the problem. Error message could be more clear but I'll close this ticket.
