### ISSUE TITLE
🐛 BUG: JS and CSS bundles per component in production build

### ISSUE THREAD

**Issue by austinjherman** [withastro/astro#2360]
### What version of `astro` are you using?

0.22.9

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

After performing a production build of our Astro + Svelte site, we're seeing both JS and CSS bundles being created per component. That is, if I have a `CounterOne.svelte` and a `CounterTwo.svelte` component, then after a build there are JS and CSS files created for each component and put in the `dist` directory. I've created a minimal reproduction for both svelte and react.

React: https://stackblitz.com/edit/github-5rymes?file=src%2Fpages%2Findex.astro&on=stackblitz
Svelte: https://stackblitz.com/edit/github-bjccnz?file=src%2Fpages%2Findex.astro

I'm creating a bug report for this behavior because having both JS and CSS files _per component_ is making some of the lighthouse tests angry, including "Eliminate Render-Blocking Resources", "Avoid chaining critical requests", and "Inline critical CSS".

Additionally, about a month ago I had something like this in the document `<head>`:
```html
<head>
  <style lang="scss">
    @use '../style/framework.scss';
  </style>
</head>
```

That ^ inlined all of our critical CSS right in the document head, which was nice because it eliminated a request for our framework stylesheet. While I still have the above code in the document head, it's now being put in a stylesheet that's linked to the document rather than being inlined. 

As a side note, it would be nice to have the option to inline CSS if one was so inclined.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bjccnz?file=src%2Fpages%2Findex.astro

**Comment by jonathantneal** [comment]
Was this bundling differently in a prior version of Astro, @austinjherman? If so, that might help me narrow down the issue. If there isn’t a regression and this is a request, then this would serve as a good example for a proposal we’re working on to do exactly what you’ve mentioned.

**Comment by austinjherman** [comment]
Hi @jonathantneal, thanks for the quick response! Hopefully I'm not annoying you all, haha. For what it's worth we love Astro!

So, in answer to your question, yes, at one point it was bundling differently. More specifically, it looks like Astro was bundling CSS differently (combining CSS into a common file), but even then it looks like the JavaScript was still being split into component-based bundles. 

I've pinpointed the time frame of this difference to be sometime between Nov 30th 2021 and Dec 8th 2021. The last Netlify deploy preview we have with the old bundling was Nov 30th. The next deploy preview we had was Dec 8th, and that's the one where the new bundling took effect.

I inspected the PR attached to the Dec 8th deploy preview, and oddly there didn't appear to be any changes to `package-lock.json` or `package.json`. So I'm at a loss as to what could have introduced the change. 

Nov 30th deploy preview CSS requests (has common.css):
<img width="1024" alt="Screen Shot 2022-01-11 at 12 13 13 PM" src="https://user-images.githubusercontent.com/13291882/148989583-025c1c11-7581-4a48-bc71-b4ab46ad1d04.png">

Dec 8th deploy preview CSS requests (doesn't have common.css):
<img width="1233" alt="Screen Shot 2022-01-11 at 12 16 16 PM" src="https://user-images.githubusercontent.com/13291882/148990074-9ac2963d-0a7e-4bef-9f62-73c46ad10de6.png">

Let me know if I can provide any more information to help you out. 

For what it's worth, even with the current bundling we're still getting page speed scores of 99 and 100. However, once we introduce Google Tag Manager 🙄  (currently just an empty container without any tags), we're seeing a performance degradation of about 16 points. Lighthouse mentions some of the tests I mentioned above in my initial comment, so we're unsure if it's simply GTM that is killing our performance, or if it's a combination of the bundling style _and_ GTM. Just for some more context.

**Comment by austinjherman** [comment]
Oh and the Nov 30th - Dec 8th timeframe is also when Astro stopped inlining the framework CSS in the head and instead put it in a file linked to the document. 

e.g. This code no longer inlines but gets moved to another CSS file:
```html
<style lang="scss">
  @use '../style/framework.scss';
</style>
```

**Comment by jonathantneal** [comment]
Thanks for the these details. I’m not quite sure the cause of this, so I’m going to pull in some help from @matthewp.

**Comment by matthewp** [comment]
Thanks for filing the issue! Sorry for taking so long to respond. I agree that we should do a better job of inlining critical styles. Can you create an RFC for this (a discussion is fine too)?
