### ISSUE TITLE
🐛 BUG: docs template fails to render search ("Invalid hook call [...]")

### ISSUE THREAD

**Issue by happycollision** [withastro/astro#2390]
### What version of `astro` are you using?

0.22.11

### What package manager are you using?

npm

### What operating system are you using?

Mac

## Steps to reproduce:

1. ` npm init astro -- --template docs`
2. Install the deps (via npm, if it matters)
3. Start the app
4. Uncomment the lines in the `config.ts` file for the Algolia search and save

### Expected
The search component would appear

### Actual
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

https://user-images.githubusercontent.com/3663628/149541333-16207d15-b19b-4d97-80ea-78e8b0aaa561.mp4

## Attempts to remedy

I tried installing the `@astrojs/renderer-react` (since only preact was there to start), but I still got the same message.

I also tried to just switch to Preact for that component, but importing `createPortal` from `preact/compat` caused some other giant failure.

### Link to Minimal Reproducible Example

https://github.com/happycollision/astro-docs-template-search-failure

(Stackblitz also fails for me with the same edit, but 1. the package.json file is not actually the same to start, and 2. the failure is completely different... `__vite_ssr_import_2__.useDocSearchKeyboardEvents is not a function`)

**Comment by jonathantneal** [comment]
`__vite_ssr_import_2__`, this seems like an issue with a dependency not being exposed correctly.

**Comment by happycollision** [comment]
You are definitely more aware of what is going wrong here than I am, but I want to reiterate that the `__vite_ssr_import_2__` error that I quoted at the very end is not the main bug in this issue. Perhaps, under the covers it _is_ the same thing, but I wanted to be clear.

**Comment by matthewp** [comment]
Sorry for the slow response. This has been fixed since the issue was just filed. I just tested against `0.23.0-next.6` and it is working there. Going to close.
