### ISSUE TITLE
🐛 BUG: Astro.resolve('*.css') not working after upgrade

### ISSUE THREAD

**Issue by X7md** [withastro/astro#2398]
### What version of `astro` are you using?

0.22.6, 0.22.13

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

"
`href={Astro.resolve('../styles/global.css')}`
 not work after update form 0.22.6 to 0.22.13 and no error showing just page without css
"

[discord support thread](https://discord.com/channels/830184174198718474/931919789948022825)

to reproduction just upgrade from `0.22.6` to `0.22.13` by run `npm install astro@0.22.13` and build it 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/X7md/x7md.github.io?file=package.json

**Comment by X7md** [comment]
after trying different astro versions, the issues just happening on `0.22.11` or up

**Comment by Mravuri96** [comment]
@X7md maybe this is intended see #2393

**Comment by X7md** [comment]
solution:

```html 
<style global>@import "..."</style>
```
