### ISSUE TITLE
🐛 BUG: Components with array-like prop fail to render in Markdown

### ISSUE THREAD

**Issue by Destiner** [withastro/astro#2399]
### What version of `astro` are you using?

0.22.11

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a component that takes an array as a prop. I then use this component in a markdown file with `setup`. When that markdown is rendered, I get something along the lines of `<ComponentName propName=[[Object object][Object object]] />` rendered a string. Interestingly, passing empty array to them component seems to work (nothing gets rendered).

I tried to create a Vue component as well and got the same result.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fdsvay?file=src%2Fpages%2Findex.md

**Comment by toSayNothing** [comment]
according to the [document](https://docs.astro.build/en/guides/markdown-content/),
>### Markdown Pages
>Astro treats any .md files inside of the /src/pages directory as pages. These files can contain frontmatter, but are otherwise processed as plain markdown files and do not support components. If you’re looking to embed rich components in your markdown, take a look at the Markdown Component section.

 so you can use the `MarkDown` component in `.astro` file to render the customize component.
eg : https://stackblitz.com/edit/github-fdsvay-rqehaz?file=src/pages/index.astro

**Comment by jonathantneal** [comment]
I think there is an issue with how attributes are serialized. I’m going to track this as a bug. In the meantime, @toSayNothing, thank you for sharing that workaround.

**Comment by natemoo-re** [comment]
Confirming that this is still an issue in the latest version. https://stackblitz.com/edit/github-fdsvay-qeaaxz?file=src%2Fpages%2Findex.md,src%2Fcomponents%2FTodoList.astro
