### ISSUE TITLE
📘 DOC: fix "coiner" of the phrase "Island Architecture"

### ISSUE THREAD

**Issue by jorroll** [withastro/astro#2407]
Reading through the Partial Hydration section of the docs, I was interested in the section describing the Island Architecture concept. That section helpfully includes the following

> To quote Jason Miller, who [coined the phrase](https://jasonformat.com/islands-architecture/):
> 
> > In an “islands” model, server rendering is not a bolt-on optimization aimed at improving SEO or UX. Instead, it is a fundamental part of how pages are delivered to the browser. The HTML returned in response to navigation contains a meaningful and immediately renderable representation of the content the user requested.

I clicked on the link to read more about the term, only to be greeted with a blog post that begins with the following two sentences (emphasis mine):

> I’ve struggled to find references to this online, but heard the name used multiple times this year when describing the approach outlined here. ***To the best of my knowledge, the "Component Islands" pattern was coined by Etsy's frontend architect [Katie Sylor-Miller](https://twitter.com/ksylor) during a meeting we had in 2019.***

In any context, it would be a little awkward to discover that you're giving credit to the wrong person. But for the mistake to be explicitly called out in the second sentence of the linked source (and using the same phrasing of "coined by" no less!)...And for the mistake to be that of crediting a man with something a woman did (when that's such a common criticism in society already that it's the subject of [Vox articles](https://www.vox.com/2016/9/14/12914370/white-house-obama-women-gender-bias-amplification) and included in [Rick and Morty episodes](https://www.imdb.com/title/tt14898020/?ref_=ttep_ep4))...It just seems so...on the nose X.X

Anyway, I imagine this was just a regular old mistake and maybe the linked blog post was updated after the citation was made, but it'd be nice to get it fixed. 

Perhaps update that line in the docs to something like the following

> To quote Jason Miller, the first to write [a blog post](https://jasonformat.com/islands-architecture/) on the concept:

_**Note:** in this case I actually just removed reference to the person who "coined the phrase" since it seems tangential to the current point being made in the docs (and if someone wants to learn more about it, they can go read Jason's blog post). But if you are going to give credit to the person who "coined the phrase," it seems important to give credit to the correct person (apparently [Katie Sylor-Miller](https://twitter.com/ksylor))._

**Comment by sarah11918** [comment]
I agree with the idea of fixing this, and I'm putting it out there to everyone in the docs/i18n channel so we can check on this and be more accurate in all translations of the docs.

**Comment by FredKSchott** [comment]
100%! I believe I authored that because I had heard it first from Jason seperately, and clearly hadn't read the article closely enough. Apologies to Katie, let's get that updated! 

+1 for removing the line entirely which I actually think reads better. We could do this across all translations without needing to translate each one:

```diff
- To quote Jason Miller, who [coined the phrase](https://jasonformat.com/islands-architecture/):
-
 > In an "islands" model, server rendering is not a bolt-on optimization aimed at improving SEO or UX. Instead, it is a fundamental part of how pages are delivered to the browser. The HTML returned in response to navigation contains a meaningful and immediately renderable representation of the content the user requested.
+> -- [Jason Miller](https://jasonformat.com/islands-architecture/)
```

@jorroll any chance you'd be able to do this? You can do a big find-all for "Jason Miller" across the `docs/` sub-directory to find all versions of this line. It would be greatly appreciated if so!

**Comment by jorroll** [comment]
Pull request up #2411. Though if folks end up preferring a different phrasing, feel free to ignore.

And were it not for a silly mistake I made initially, I would have been able to submit the change entirely using [github.dev](https://github.dev/withastro/astro) which is pretty neat.

**Comment by FredKSchott** [comment]
merged! Thanks @jorroll!

**Comment by natemoo-re** [comment]
Just want to chime in that I really appreciate this issue and the correction! Thanks. ❤️
