### ISSUE TITLE
🐛 BUG: Using a function from Date throws an error

### ISSUE THREAD

**Issue by GrafZ3pp3lin** [withastro/astro#2415]
### What version of `astro` are you using?

0.22.14

### What package manager are you using?

npm

### What operating system are you using?

Linux (Windows WSL)

### Describe the Bug

An error is generated when a function of Date is used. 
```
TypeError: p2.date.getTime is not a function
```
But only if a for loop was used before. The map function works fine.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-loop-error?file=src/components/Error.astro

**Comment by boehs** [comment]
This is not astro's fault, this is just an issue in your javascript. Try running [this[

**Comment by GrafZ3pp3lin** [comment]
Ohh, I see. Maybe vscode should have shown me the type mismatch... But thanks 😅
