### ISSUE TITLE
📘 DOC: When switching from version 0.20 to 0.21 (or 0.22) imports need to be first in the astro frontmatter

### ISSUE THREAD

**Issue by schlichtanders** [withastro/astro#2441]
It took me three attempts to switch from astro 0.2 to a more recent version.
Finally I figured out the problem. It is due to `import` statemenents in the astro frontmatter.

* With astro 0.20 you could mix them arbitrarily with other javascript code 
* With astro 0.21 and up, you cannot anylonger, instead you get syntax error which at least for me was totally confusing. You need to have all the import statements first

This is breaking change which is not described in the migration guide https://docs.astro.build/en/migration/0.21.0/

It would be great if the documentation could be adapted respectively.
Thank you very much

**Comment by jonathantneal** [comment]
What you have described, I would consider a bug.

In Native JS, while imports can’t reference variables, they do not need to be the very first JS.
