### ISSUE TITLE
🐛 BUG: astro doesn't load Observable Plot

### ISSUE THREAD

**Issue by Fil** [withastro/astro#2451]
### What version of `astro` are you using?

0.22.17

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to import Observable Plot into an astro page to do SSR. However it seems that astro fails to import the module, and crashes on the use of imports in a function's default arguments.

~~~js
registry is not defined
ReferenceError: registry is not defined
    at ScaleQ (/node_modules/@observablehq/plot/src/scales/quantitative.js:55:13)
    at Module.ScaleLinear (/node_modules/@observablehq/plot/src/scales/quantitative.js:111:10)
    at Scale (/node_modules/@observablehq/plot/src/scales.js:176:73)
    at Module.Scales (/node_modules/@observablehq/plot/src/scales.js:27:21)
    at plot (/node_modules/@observablehq/plot/src/plot.js:54:33)
    at Dot.plot (/node_modules/@observablehq/plot/src/plot.js:177:12)
    at eval (/Users/fil/Sites/test-astro/src/pages/index.astro:19:50)
    at renderToString (file:///Users/fil/Sites/test-astro/node_modules/astro/dist/runtime/server/index.js:290:27)
    at renderPage (file:///Users/fil/Sites/test-astro/node_modules/astro/dist/runtime/server/index.js:300:26)
    at render (file:///Users/fil/Sites/test-astro/node_modules/astro/dist/core/ssr/index.js:170:20)
~~~

Observable Plot is developed with vite, so it doesn't seem that vite itself is incompatible with this. fwiw here's Plot's vite config: https://github.com/observablehq/plot/blob/main/vite.config.js

Minimal repro: https://github.com/Fil/temp-test-astro/commit/f26a828924eb945b302822a3fe40e263502c52ac

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ebkhph

**Comment by jonathantneal** [comment]
Aside; the StackBlitz needs to install `@observablehq/plot `.

https://stackblitz.com/edit/github-ebkhph-daswe7 (done here)

```shell
npm install --save-dev @observablehq/plot 
```

Now we can see the `registry` error.

If I log the value of `Plot.dot([1, 2, 3])`, I see the correct object, and it has the `plot()` method. The imports do not crash. The default arguments to not crash the function.

I can’t at this moment, but would you be able to setup a regular Node project with the same code? If the `registry` error does not exist there; I can use the two projects to investigate further. If it does, then the exists either in their documentation or source. It might not, but I can’t tell, yet.

**Comment by Fil** [comment]
Yes the same code "works" in node. https://github.com/Fil/test-node-for-astro

(I put "works" in quotes, because in actuality it does crash later on; however the latter crash is expected, since Plot calls d3.create which needs a DOM document. I want to add JSDOM to fix it, but for this I need to pass the first hurdle of the crash on _registry_.)

**Comment by Fil** [comment]
this is fixed with astro@0.23.0-next.6 ! (tested both with and without the `--experimental-static-build` modifier.)

Adding JSDOM allows Plot to create a SVG node server-side:

```js
import * as d3 from "d3";
import {JSDOM} from "jsdom";
import * as Plot from "@observablehq/plot";

export interface Props {
	title: string;
}

const jsdom = new JSDOM("");
global.window = jsdom.window;
global.document = jsdom.window.document;
global.Event = jsdom.window.Event;
global.Node = jsdom.window.Node;
global.NodeList = jsdom.window.NodeList;
global.HTMLCollection = jsdom.window.HTMLCollection;

const values = await d3.csv("./data/values.csv");
const chart = Plot.plot({
  marks: [Plot.dot(values, {x: "a", y: "b", fill: "green"})]
});

```

One last hurdle is how to cleanly pass that SVG node to the front-end. I can use `{chart.outerHTML}` but then I get a warning: `Unescaped HTML content found inside expression! The next minor version of Astro will automatically escape all expression content. Please use the `set:html` directive.`

**Comment by joakimnl** [comment]
@Fil Could you elaborate on how you implemented the above solution? Struggling to achieve the same thing.

**Comment by Fil** [comment]
this is the complete contents of my Nav.astro file:
[Nav.astro](https://github.com/withastro/astro/files/10031334/Nav.astro.txt)

I haven't tried since last February, so maybe things have changed again. Let me know if it works for you?

**Comment by joakimnl** [comment]
Thanks for the quick reply! Unfortunately it fails with the following error message:

> [plugin:vite:import-analysis] Failed to resolve entry for package "@observablehq/plot". The package may have incorrect main/module/exports specified in its package.json.

Also, there's a TypeScript error on global: Cannot fine name 'global'.

**Comment by joakimnl** [comment]
I got this working:

```
---
export interface Props {
	title: string;
    data: object;
    type?: string;
}

const { data, type, title } = Astro.props;
---

<div id={title}>
    <h1>{title}</h1>
</div>

<script type="module" define:vars={{data,title,type}}>
import * as Plot from "https://cdn.skypack.dev/@observablehq/plot@0.4";
let chart = document.querySelector('#' + title);
chart.appendChild(Plot.plot({
  marks: [
    Plot.barY(data, {x: "Aldersgruppe", y: "Antall respondenter", fill: "magenta"}),
    Plot.ruleY([0])
  ]
}));
</script>
```

Not optimal, as I would prefer to load Plot from disk, but at least it's working.

Thanks again @Fil!

**Comment by joakimnl** [comment]
Copying this in from Discord. Got Plot to load thanks to this script from @delucis  
```
---
const { data, type, title } = Astro.props;
---

<plot-chart data-data={JSON.stringify(data)} data-type={type}>
  <h1>{title}</h1>
</plot-chart>

<script>
import * as Plot from '@observablehq/plot';

class PlotChart extends HTMLElement {
  constructor() {
    super();
    const { type } = this.dataset;
    const data = JSON.parse(this.dataset.data);
    this.appendChild(Plot.plot({
      marks: [
        Plot.barY(data, {x: "something", y: "something", fill: "magenta"}),
        Plot.ruleY([0])
      ]
    }));
  }
}

customElements.define('plot-chart', PlotChart);
</script>
```
