### ISSUE TITLE
🐛 BUG: Relative assets break 404 pages

### ISSUE THREAD

**Issue by Tc-001** [withastro/astro#2452]
### What version of `astro` are you using?

0.22.14

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When building the site, auto-generated assets get referenced with relative urls (ex. `./assets/foo.hash.js` if in root, or `../assets/foo.hash.js` if a subdirectory) instead of absolute ones (`/assets/foo.hash.js`)
This means that any page that has server-side path overrides (like 404 pages) can have broken assets.

# In the wild

in https://docs.astro.build/ the assets for the `404` page are linked as follows: 
```html
<script type="module" src="../assets/404.cb69fe85.js"></script>
<link rel="stylesheet" href="../assets/404.59613581.css">
<link rel="stylesheet" href="../assets/LanguageSelect.68aa0211.css">
<link rel="stylesheet" href="../assets/Search.ca9f3b6c.css">
```

This means that the page `https://docs.astro.build/foo/bar/baz` will have every asset break
![image](https://user-images.githubusercontent.com/55956895/150695645-49edd59a-162d-4779-8527-df7889b6c75a.png)

As the browser tries to access 
`https://docs.astro.build/foo/assets/404.cb69fe85.js` 
instead of 
`https://docs.astro.build/assets/404.cb69fe85.js`

### Link to Minimal Reproducible Example

Any astro site that uses resolve or hoists html/js

**Comment by jonathantneal** [comment]
This is the intended behavior, as it guaruntees relative assets in HTML, CSS, and JS would all work regardless of the deployment directory. What are the _server-side overrides_ that you are encountering?

**Comment by Tc-001** [comment]
See the last section.
404 pages can happen on any path. be it `example.com/a` or `example.com/a/b/c`
Assets being relative means that 404 pages in subdirectories will have broken styles

See 
https://docs.astro.build/foo/bar/baz (broken)
https://docs.astro.build/foo/bar (working)

Or for a more extreme example:
https://ohkabots.ohkaspace.com/foo/bar/baz (broken)
https://ohkabots.ohkaspace.com/foo/bar (working)

**Comment by Tc-001** [comment]
Duplicate-ish of https://github.com/withastro/rfcs/discussions/79

## Workaround
Include `<base href="/404/">` in head
