### ISSUE TITLE
🐛 BUG: .astro to .html transformation is broken

### ISSUE THREAD

**Issue by schlichtanders** [withastro/astro#2461]
### What version of `astro` are you using?

0.22.17

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I tried to combine astro and reveal.js for fancy html slides, however it seems that I run into a bug when astro compiles .astro files to the final .html

I created a minimal working example. If you run `npm run build` (unfortunately stackblitz somehow allowed me doing this once, but now no longer...) you find that in the generated file the section `With animations` (just search for the words) is corrupted with newly appearing `<code>` segments which even destroy the nesting of `sections` so that everthing below this section gets inserted as subsections.

-----------------

The MRE is the official reveal.js example with the small change that all code blocks are wrapped into `script` environments to be compatible with astro's `{...}` syntax. The split into Layout and .ts and .css I've created myself.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-q5lc4h-dc3dsc?file=src/layouts/SlidesLayout.astro

**Comment by FredKSchott** [comment]
I believe that this has been resolved as of Astro v0.24.0!
