### ISSUE TITLE
🐛 BUG: Does not support hydration with destructured export object

### ISSUE THREAD

**Issue by delucis** [withastro/astro#2480]
### What version of `astro` are you using?

0.22.19

**Edit:** Also reproduced with v0.23.2

### What package manager are you using?

npm (8.1.2)

### What operating system are you using?

macOS 12.1

### Describe the Bug

Adding a `client:` directive to a component in a Markdown file causes the dev server and build task to error.

The reproduction link shows a very simple Preact component included in two Markdown files. The following renders fine:

```md
<RedP>Test component</RedP>
```

Adding a `client:load` directive (or other `client:` directive), throws an error:

```md
<RedP client:load>Test component</RedP>
```

I also tried a random attribute containing a `:` and that works fine.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vzflqt-fzwkf9?file=src/pages/load.md

**Comment by jonathantneal** [comment]
Confirmed. Not zesty. Here’s the error to help speed debug —

```
RedP is not defined
ReferenceError: RedP is not defined
    at /home/projects/github-vzflqt-fzwkf9/src/pages/load.md:12:163
    at async instantiateModule (/home/projects/github-vzflqt-fzwkf9/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:66516:9)
```

**Comment by pyronaur** [comment]
Seeing a similar issue to this with the following load order:

```js
// [post].astro
Astro.fetchContent("content/*.md")

// content/intro.md
import Robotcode from './examples/Robotcode.astro';

// content/examples/Robotcode.astro
import Robot from './Robot.svelte';
```

In other words, 
Astro page loads Markdown content using `Astro.fetchContent`
Markdown content file with imports an Astro component with frontmatter
Astro component imports a Svelte component
Svelte component works fine during development, but during `npm run build` produces error:

```
03:44:57 PM [build] Error rendering: Error: Cannot find the built path for @examples/Robot.svelte
    at Object.resolve (file:///path/to//node_modules/astro/dist/core/build/generate.js:136:17)
    at Module.generateHydrateScript (/node_modules/astro/dist/runtime/server/hydration.js:65:165)
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/index.js:233:50)
    ┃ /intro/ +2ms
Completed in 10ms
```

**Comment by IanVS** [comment]
I updated the reproduction to 1.0.0-beta.24 and this is still an issue. https://stackblitz.com/edit/github-vzflqt-y3zyb5?file=src/pages/index.md

**Comment by natemoo-re** [comment]
Thanks @IanVS that's super helpful!

This is an urgent bug to fix, I'll make sure we get this prioritized. Thanks for your patience, everyone.

**Comment by natemoo-re** [comment]
Here is the same reproduction with the export changed and the example working.
https://stackblitz.com/edit/github-vzflqt-g1vrd7?file=src%2Fpages%2Fload.md

@matthewp is going to investigate this and see how **if** we can support this destructured style for static analysis and **if not** how we can improve our error message.

**Comment by delucis** [comment]
I can also confirm that `export const RedP = ...` / `import { RedP } from '...'` also fixes this bug. So it’s only when exporting an object containing a reference to the component that this breaks — a `this` issue, maybe? Also, makes we wonder if it’s related to the re-exporting issue in #3053.

**Comment by matthewp** [comment]
@delucis It's not related in this case. It's because we must know which components are hydrated in the client without running the code, in order to bundle that code for production. However `import { RedP } from '..'` should work since that is static. Are you saying that case is current working? If so then this becomes a dev warning/error issue.

**Comment by delucis** [comment]
Yeah `import { RedP } from '..'` works for non-default exports. Reproduction: <https://stackblitz.com/edit/github-vzflqt-acpall?file=src/pages/load.md>
