### ISSUE TITLE
🐛 BUG: div class in one component applying to divs in other component & css being rendered into broken code.

### ISSUE THREAD

**Issue by wtpcg** [withastro/astro#2484]
### What version of `astro` are you using?

0.21

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

div class="sect-bk" in Wtpfg.astro width css is applying to div widths in the other component.
&
div class="sct" in Wtpfg.astro with margin-top: 7em is being rendered as margin-top.astro-JT6NNQYL: 7em; on local site.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/xenodochial-sinoussi-hxknm?file=/src/components/Wtpfg.astro

**Comment by wtpcg** [comment]
i just ran npm astro --version, it displays 8.3.1

sorry for confusion on which version of astro

**Comment by Princesseuh** [comment]
I think this is fixed on the latest versions? The generated CSS looked fine to me and I didn't notice any CSS being leaked between components

If this is still happening for you, please open another issue in the future :smile:
