### ISSUE TITLE
🐛 BUG: Empty config file isn't supported

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#2488]
### What version of `astro` are you using?

0.22.19

### What package manager are you using?

pnpm

### What operating system are you using?

Ubuntu

### Describe the Bug

Astro throws the following error if there's an empty `astro.config.js` file present or if the config file doesn't have a default export.
```bash
TypeError: Cannot convert object to primitive value
```
No error is thrown if there's no `astro.config.js` file present.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tz7qbv?file=astro.config.mjs&on=stackblitz

**Comment by jonathantneal** [comment]
Verified. I agree this _seems_ like a bug. However, I want to point out that if no astro configuration file is present, then the error does not persist.
