### ISSUE TITLE
🐛 BUG: define:vars breaking on hoisted scripts with `--experimental-static-build`

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/astro#2505]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Any defined variable in `define:vars` is scrapped from rendered page when `--experimental-static-build` is set to `true` and hoist is set also to `true`

Works if hoist is set to `false` or `--experimental-static-build` is set to `false`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xrbux4?file=src%2Fcomponents%2FTour.astro&on=stackblitz

**Comment by jonathantneal** [comment]
Verified. This may be a current limitation, but I’m not certain and I can see in your excellent example that there is no warning flag.

**Comment by Chrissdroid** [comment]
apart from "variable is undefined" the console is empty, i found this by checking files via the sources tab on devtools

**Comment by matthewp** [comment]
Thanks, I'm currently taking a look. This is true of styles as well, not hadn't implemented define:vars behind that flag yet.

**Comment by Chrissdroid** [comment]
May keep the issue stale for now and link the future PR later then ?

**Comment by matthewp** [comment]
Not sure I follow but we can keep this issue open if thats what you mean.

**Comment by Chrissdroid** [comment]
Sorry, I meant to leave the issue open for the moment while waiting for an implementation in order to avoid duplicates

**Comment by matthewp** [comment]
Fixed by #2511, should go out in the next (prerelease most likely)
