### ISSUE TITLE
🐛 BUG: Plain HTML template usage breaks Astro

### ISSUE THREAD

**Issue by jonathantneal** [withastro/astro#2509]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm

### What operating system are you using?

Mac, Windows, Linux

### Describe the Bug

Plain HTML throws in Astro when using `<template>`.

```html
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>Plain HTML</title>
	</head>
	<body>
		<h1>Plain HTML</h1>
    <div>
      <template shadowroot="true">
        <slot></slot>
        <style>
        ::slotted(button) {
          all: unset;
        }
        </style>
      </template>
      <button>click</button>
    </div>
	</body>
</html>
```

```
Cannot read properties of null (reading 'default')
```

#### Workarounds (1)

- Remove `<slot></slot>` and don’t use HTML. This unbreaks Astro.
- Create a JavaScript variable to represent the actual tag name.

<details><summary><strong>See Example</strong></summary>

```astro
---
const Slot = 'slot'
---
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>Plain HTML</title>
	</head>
	<body>
		<h1>Plain HTML</h1>
    <div>
      <template shadowroot="open">
        <style>
        ::slotted(button) {
          all: unset;
        }
        </style>
        <Slot></Slot>
      </template>
      <button>click</button>
    </div>
	</body>
</html>
```

Work **Workarounds (1)**, slotting will only work when slotted content is used. Without it, the content will be the text "undefined". Also, styling is broken.

#### Workarounds (2)

- Remove `<style></style>` and don’t use HTML or CSS.
- Use JavaScript to hack around Astro by creating a component that is actually a tag name.
- Use an Astro internal attribute to prevent the component from throwing.

<details><summary><strong>See Example</strong></summary>

```astro
---
const Slot = 'slot'
const Style = 'style'
---
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>Plain HTML</title>
	</head>
	<body>
		<h1>Plain HTML</h1>
    <div>
      <template shadowroot="open">
        <Style data-astro-raw>
        ::slotted(button) {
          all: unset;
        }
        </Style>
        <Slot></Slot>
      </template>
      <button>click</button>
    </div>
	</body>
</html>
```

</details>

This usage of JavaScript variables and the usage of Astro internals feels highly fragile and subject to future breakage.

---

_Please Note: This example does not use web components or custom elements._

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4bhpd2?file=src/pages/index.astro

**Comment by jonathantneal** [comment]
The example has been updated to use `astro@0.23.1` and the bug is still present.

**Comment by Princesseuh** [comment]
I can confirm that this issue still happens in the latest version of Astro, however it seems like a pretty specific issue

**Comment by natemoo-re** [comment]
Closing in favor of https://github.com/withastro/astro/issues/2933

**Comment by rienheuver** [comment]
Can you explain how #2933 solves this? That issue is closed but I still can't figure out how to get this to work
