### ISSUE TITLE
🐛 BUG: Static build with pnpm requires extra dependencies

### ISSUE THREAD

**Issue by zadeviggers** [withastro/astro#2520]
### What version of `astro` are you using?

0.23.0-next.0

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When using pnpm and building with the `--experimental-static-build` flag, it will complain about missing dependencies unless you install `estree-util-value-to-estree`, `shiki`, and `shorthash`.

### Link to Minimal Reproducible Example

Can't really create an example of this on stackblitz or codesandbox because it's to do with the package manager

**Comment by jonathantneal** [comment]
The `estree-util-value-to-estree` dependency is something I’ve seen during bundling. Handing this to @matthewp for further investigation.

**Comment by matthewp** [comment]
You have to use the `shamefully-hoist` option with pnpm at the moment.

**Comment by boehs** [comment]
Can this be closed? All examples already include it

**Comment by zadeviggers** [comment]
Yep!
