### ISSUE TITLE
🐛 BUG: client:only="lit" error: Failed to resolve module

### ISSUE THREAD

**Issue by ClintH** [withastro/astro#2526]
### What version of `astro` are you using?

0.22.0

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I'm trying to use a client-only Lit element.  Using the `client:only="lit"` attribute as in:

`<my-counter client:only="lit"></my-counter>`

Throws the error:

Uncaught (in promise) TypeError: Failed to resolve module specifier ''
    at index.astro?html-proxy&index=1.js:5:1
    at async onLoad (only.ts:9:18)

I also tried using `@astrojs/renderer-lit` with the same outcome.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bbch9k?file=src/pages/index.astro

**Comment by matthewp** [comment]
Thanks! We do not support `client:only` on base module imports at the moment. The logic for determining which import statement matches which component usage is based on seeing the imported name. Here's the code in the compiler: https://github.com/withastro/compiler/blob/f25131ceaf57e4b8b4eecba282209de2aacf6d26/internal/printer/printer.go#L348

I think this is something we probably just cannot possibly support. We don't know that `my-counter` matches up to `import '../components/Counter.js';`.

I think what we need here is a good error message when we encounter a `client:only` on a custom element.

**Comment by rodydavis** [comment]
How can we use a client only component that we do not have a SSR strategy for?

<model-viewer> for example i want/need threejs and there is not content i plan on rendering.

Also for the import even if the developer is responsible with including the is-inline script tag, that would be nice just ignore the custom tag and pass it through on the markup

**Comment by e111077** [comment]
Can this be worked around now that the `export const tagName` requirement is gone?

Alternatively, can we simply just define a map file somewhere that can one day be auto-generated by Web Component Analyzer?

**Comment by matthewp** [comment]
Yes, given that we no longer support `tagName` approach, you can import the element constructor and use `client:only` on it directly.

Going to close this issue given its age and the new approach, please open new issues as needed.

**Comment by e111077** [comment]
Do you mind re-opening this issue? There doesn't seem to be a workaround because `client:only="lit"` still doesn't exist 😢 

repro case based on the official templates:

https://stackblitz.com/edit/github-jrtzpq?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by e111077** [comment]
well it seems to load the definition, but does not include the tag name w/ attributes / properties set

**Comment by whs** [comment]
Running into this as well

**Comment by hrmcdonald** [comment]
Also seeing this issue.

**Comment by FredericHeem** [comment]
All my components are wrapped into a function for dependency injection:

```js
---
import counter from '../components/Counter';
const context = {
 // global data and function
};
const Counter = counter(context);
---
<html lang="en">
<body>
    <Counter client:only="react" />
  </body>
</html>
```

That results in the error: `Unable to find matching import statement for client:only component`

Is there a workaround ?
