### ISSUE TITLE
🐛 BUG: HMR not working in `astro@next`

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/astro#2528]
### What version of `astro` are you using?

0.23.0-next.1

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

HMR broke when updating to `v0.23` for both `next-0` and `next-1`

list of files which is affected by this:

- Files under the `/src/pages` directory (both `.astro` & `.md`)
- Files under the `public` directory

if they are imported works fine and reload page properly.

### Link to Minimal Reproducible Example

https://astro.new/starter@next?on=stackblitz

**Comment by jonathantneal** [comment]
As @Chrissdroid mentioned in Discord, this seems related to the switch to the Vite server (https://github.com/withastro/astro/pull/2494), where the new server may not be listening for changes on the files in `src/pages/`

**Comment by FredKSchott** [comment]
I have some time to take a look now!

**Comment by FredKSchott** [comment]
I can't reproduce in my refactor PR, instead I believe I've traced it back to this PR, which touches a lot of the same HMR code: #2522

@matthewp any chance you can take a look? I can reproduce in `examples/blog`, where a change to `src/pages/index.astro` does not trigger a browser reload. Could it be that we're not returning the actual file that changed (ex: `index.astro`) in `return Array.from(filtered);`?

**Comment by matthewp** [comment]
Oof, yes I can, it's possible I did this.

**Comment by matthewp** [comment]
Fix is here: https://github.com/withastro/astro/pull/2532
