### ISSUE TITLE
🐛 BUG: Asset URLs not resolved correctly with Astro.resolve() when used in CSS of Vue component

### ISSUE THREAD

**Issue by marianheinsen** [withastro/astro#2535]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

If you open the URL, there is an Astro file with two Vue Components. Both of them get an image URL from Astro.resolve as a property, however one of them uses it as source in an <img> tag and the other one as a background image using style binding.

On initial run, both images are visible in the preview. However if you cancel the process in the Terminal below and do a build + preview using `npm run build && npm run preview` we can see that only the first image is visible.

![screenshot](https://user-images.githubusercontent.com/43065575/152583375-87da5b2f-0db9-4463-8c2f-799da5d7845a.png)

In the build output, the resolved asset URL is inserted correctly for the <img> tag but the url of the background image is wrong

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dygz7x?devtoolsheight=33&file=src/pages/index.astro

**Comment by FredKSchott** [comment]
FYI Astro.resolve() is going away in future versions for reasons exactly like this. Sounds like we need to update the example instead!
