### ISSUE TITLE
🐛 BUG: Svelte components (client:only) render but are not interactive.

### ISSUE THREAD

**Issue by MikeChurvis** [withastro/astro#2542]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

# Svelte components in Astro render but are not interactive.

The browser DevTools console shows this error: 
`[HMR][Svelte] Unrecoverable error in <Wrapper>: next update will trigger a full reload`

Additionally, VSCode shows this error in the Astro component where the Svelte component is imported: 
`Cannot find module '../components/test.svelte' or its corresponding type declarations.js(2307)`

A minimal example is given in the StackBlitz link.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7uizka?file=src/pages/index.astro

**Comment by Princesseuh** [comment]
The VS Code part I assume is [this issue](https://github.com/withastro/language-tools/issues/142), which doesn't affect behavior

**Comment by MikeChurvis** [comment]
# Update

This bug is due to human error.

The non-interactivity is due to incorrect Svelte syntax. In Svelte, all event handlers *must* be functions; `on:click={count++}` should have been `on:click={()=>count++}`. This is a departure from my Vue background, where `v-on:click="count++"` is valid.

I am closing this issue.
