### ISSUE TITLE
🐛 BUG: RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by ejdrien** [withastro/astro#2566]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm

### What operating system are you using?

linux

### Describe the Bug

Using `rehype-katex` package crashes Astro with `RuntimeError: memory access out of bounds` on every page that either fetches or includes Markdown content.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/reverent-satoshi-1l422

**Comment by tony-sull** [comment]
Thanks for filing this issue @ejdrien!

I hadn't realized this when we were talking on Discord but it looks like this is probably the same underlying issue as [#2325](https://github.com/withastro/astro/issues/2325)

Closing this as a duplicate so we can track both `rehype-katex` issues in #2325 :+1:
