### ISSUE TITLE
🐛 BUG: duplicate attributes cause runtime error instead of taking precedence

### ISSUE THREAD

**Issue by Enteleform** [withastro/astro#2574]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

# Setup

### Foo.jsx
```ts
export default function Foo(props){
  return (
    <h1 class="Foo" {...props}>
      {"Foo"}
    </h1>
  )
}
```

### Foo.astro
```ts
---
import Foo from "./Foo.jsx"
---

<Foo class="Bar" client:visible/>
```

# Expected
Duplicate attributes will have their rightmost instance applied, as defined in the component to be rendered.

In the case of `Foo.jsx`, where `props` are spread to the right of `class="Foo"`, the usage of `class="Bar"` @ `Foo.astro` will take precedence, resulting in the following rendered HTML:
```html
<div class="Bar">Foo</div>
```

![image](https://user-images.githubusercontent.com/10906415/153734282-d9ea8748-fcf1-4026-a8f5-7d903989c4e5.png)

(*expected output via [CodeSandbox/VanillaSolidExample](https://codesandbox.io/s/vanillasolidexample-p7tmj?file=/src/App.tsx)*)

# Actual
A runtime error occurs, due to multiple `class` attributes on the rendered HTML element:
```bash
Unable to parse {"file":"/src/pages/index.astro","line":51,"column":57}
49 |      <main class="astro-ASBXE2DO">
50 |        
51 |  <astro-root uid="Z1ci0oJ"><h1 data-hk="0.0" class="Foo" class="Bar" >Foo</h1><script>window._$HY||(_$HY={events:[],completed:new WeakSet,r:{}})</script></astro-root>
   |                                                          ^
52 |  
53 |      </main>
```e/>
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/github/enteleform-codesandbox/0006--Astro--PropOverrides?file=/src/components/Foo.jsx

**Comment by jonathantneal** [comment]
Interesting. The React renderer should be collapsing these, since this is happening within a JSX file.
