### ISSUE TITLE
🐛 BUG: Markdown Plugins As Functions Throws Error

### ISSUE THREAD

**Issue by EmNudge** [withastro/astro#2576]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm

### What operating system are you using?

MacOS

### Describe the Bug

According to [Astro's Docs](https://docs.astro.build/en/guides/markdown-content/)
> You can provide names of the plugins as well as import them:

> ```js
> import autolinkHeadings from 'remark-autolink-headings';
> 
> // astro.config.mjs
> export default {
>   markdownOptions: {
>     render: [
>       '@astrojs/markdown-remark',
>       {
>         remarkPlugins: [[autolinkHeadings, { behavior: 'prepend' }]],
>       },
>     ],
>   },
> };
> ```

Although importing the function directly will not work. The plugin will be added as `undefined` and `unified` will then throw an error when adding. 

> TypeError: Cannot read properties of undefined (reading 'call')

# The Problem & Fix
This is because of `@astrojs/markdown-remark/src/load-plugins.ts`
```ts
export function loadPlugins(items: Plugin[]): Promise<[unified.Plugin] | [unified.Plugin, any]>[] {
  return items.map((p) => {
    return new Promise((resolve, reject) => {
      if (Array.isArray(p)) {
        const [plugin, opts] = p;
        return importPlugin(plugin)
          .then((m) => resolve([m.default, opts]))
          .catch((e) => reject(e));
      }

      return importPlugin(p)
        .then((m) => resolve([m.default]))
        .catch((e) => reject(e));
    });
  });
}
```

We resolve with `m.default` regardless of what `importPlugin` returns, however, the function won't wrap `p` in `{ default: p }` when returning if it's just a function.

```ts
async function importPlugin(p: string | UnifiedPluginImport): UnifiedPluginImport {
  if (typeof p === 'string') {
    return await import(p);
  }

  return await p;
}
```

According to this code, our input shouldn't be the plugin itself, but `{ default: pluginName }`. We get this behavior with `import('plugin-name')`, but during the config resolution process, the config object is deeply merged with other properties which calls `propertyIsEnumerable` on any non-primitive. This fails for module types since they don't extend `Object`.

The way forward is either to fix us calling `propertyIsEnumerable` on non-objects and then fix the documentation accordingly **or** we can change our types to accept a function instead of a module. We could then just return `{ default: await p }` from `importPlugin`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8hx11j

**Comment by amykapernick** [comment]
I'm having the same issue with my project

**Comment by jonathantneal** [comment]
Wonderful diagnosis. Are you open to submitting the fix? I’m still accepting the bug and assigning it, but if you have the solution in hand, everyone can probably enjoy the fix sooner. :)
