### ISSUE TITLE
🐛 BUG: CSS Import Regression

### ISSUE THREAD

**Issue by jonathantneal** [withastro/astro#2597]
### What version of `astro` are you using?

0.23.0-next.8

### What package manager are you using?

npm

### What operating system are you using?

Mac, Windows, Linux

### Describe the Bug

In Astro v0.22, writing `import cssURL from './about.css?url'` sets the value of `cssURL` as `"/src/pages/about.css"`, and writing `import css from './about.css?raw'` sets the value of `css` as `"export default \"body {\\n  background-color: green;\\n}\""`.

In Astro v0.23, the bug is present in `?raw` usage.

In Astro v0.23, writing `import cssURL from './about.css?url'` sets the value of `cssURL` as `"export default \"/src/pages/about.css\""`, and writing `import css from './about.css?raw'` sets the value of `css` as `"export default \"body {\\n  background-color: green;\\n}\""`.

In Astro v0.23, the bug is present in both `?raw` and `?url` usage.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bmk7qq?file=src/pages/index.astro

**Comment by jonathantneal** [comment]
This example has been updated to `astro@0.23.1` and the bug is still present, with or without the `--experimental-static-build` flag.

**Comment by bholmesdev** [comment]
This issue is fixed as of Astro v1! 🥳
