### ISSUE TITLE
🐛 BUG: Nested Markdown lists don't work in slot of Markdown Component

### ISSUE THREAD

**Issue by HoloPollock** [withastro/astro#2610]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using inline markdown list will not create sub lists. ex
```
<Markdown>
- list 
   - list
</Markdown>
```
will become 
- list
- list

this isnt true for self closing markdown ex
```
---
const content = `
- list
   - list 
`
---

<Markdown content={content}/>
```

will correctly produce 

- list
   - list

All above example hold true for ordered lists

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gsa18q?file=src/pages/index.astro

**Comment by sarah11918** [comment]
Just verifying that I reproduced the behaviour! The same thing happened for me in CodeSandbox in our most recent Astro starter template. Using the Markdown component imported into an .astro page in both ways described above produced those two different results.
