### ISSUE TITLE
🐛 BUG: pnpm missing peer babel core

### ISSUE THREAD

**Issue by KirdesMF** [withastro/astro#2632]
### What version of `astro` are you using?

0.23

### What package manager are you using?

pnpm

### What operating system are you using?

Windows WSL 2

### Describe the Bug

When using pnpm to create an astro project `pnpm create astro`  with a framework, pnpm warns the user that there is a missing peer dependency : `@babel/core`

It does not break the build AFAIK 

![image](https://user-images.githubusercontent.com/54989552/154845109-7f1d57a8-4b2b-47f1-9e06-01be013ad5dd.png)

### Link to Minimal Reproducible Example

create a new project with pnpm

**Comment by FredKSchott** [comment]
Ah! This could probably be fixed by adding `@babel/core` to the preact renderer!

https://github.com/withastro/astro/blob/1d9f8a57f5863948eceda99a72da3fcdda986073/packages/renderers/renderer-preact/package.json

```diff
  "dependencies": {
+   "@babel/core": "^7.15.8",
    "@babel/plugin-transform-react-jsx": "^7.16.7",
```
    
@KirdesMF would you able to create a PR to add?

**Comment by KirdesMF** [comment]
Sure. 
Same for the react renderer I guess ?

**Comment by FredKSchott** [comment]
That would be great, thank you!

**Comment by KirdesMF** [comment]
I took a look at others frameworks 


**Solid**

```Powershell
devDependencies:
+ @astrojs/renderer-solid 0.4.0
+ astro 0.23.0

 WARN  Issues with peer dependencies found
.
└─┬ @astrojs/renderer-solid
  └─┬ babel-preset-solid
    └─┬ babel-plugin-jsx-dom-expressions
      └─┬ @babel/plugin-syntax-jsx
        └── ✕ missing peer @babel/core@^7.0.0-0
Peer dependencies that should be installed:
  @babel/core@^7.0.0-0
```

**Vue**

```Powershell
devDependencies:
+ @astrojs/renderer-vue 0.4.0
+ astro 0.23.0

 WARN  Issues with peer dependencies found
.
└─┬ @astrojs/renderer-vue
  └─┬ @vitejs/plugin-vue
    └── ✕ missing peer vite@^2.5.10
Peer dependencies that should be installed:
  vite@^2.5.10
``` 

If I understand

- Solid , React , Preact => need to add `@babel/core` to `package.json`

- Vue, Svelte => need to add `vite@^2.5.10` to `package.json` ?

and also, if you don't mind, why this particular version of `@babel/core` ?

```markdown
  "dependencies": {
+   "@babel/core": "^7.15.8",
    "@babel/plugin-transform-react-jsx": "^7.16.7",
```

**Comment by FredKSchott** [comment]
Fixed by updating our own repo to pnpm! Note that you will still need `shamefully-hoist` if using pnpm in your own project, while we continue to improve this support

**Comment by kissu** [comment]
Why having
```js
"peerDependencies": {
	"vite": "^2.5.10"
}
```
is not a viable solution over `shamefully-hoist`? Defeats the purpose of PNPM so far.

**Comment by millette** [comment]
@kissu see https://github.com/withastro/astro/pull/2455#issuecomment-1021331065
