### ISSUE TITLE
🐛 BUG: Using Sass cause `Error: Preprocessor dependency "sass" not found. Did you install it?` in v0.23.0

### ISSUE THREAD

**Issue by myakura** [withastro/astro#2634]
### What version of `astro` are you using?

v0.23.0

### What package manager are you using?

npm v8.1.2

### What operating system are you using?

Windows (WSL2 Ubuntu)

### Describe the Bug

Using Sass (SCSS) inside an Astro component throws an error, both in dev and build.

I put the demo on https://github.com/myakura/test--astro-v0-23-0-scss . It only adds the following `<style lang="scss">` tag to `index.astro` from the minimal template.

```astro
<style lang="scss">
	h1 { color: salmon }
</style>
```

Here is the error log I got when I run the dev command on the stackblitz.

```
Preprocessor dependency "sass" not found. Did you install it?
Error: Preprocessor dependency "sass" not found. Did you install it?
    at loadPreprocessor (/home/projects/gqaiqayql.github/node_modules/vite/dist/node/chunks/dep-971d9e33.js:19109:19)
    at scss (/home/projects/gqaiqayql.github/node_modules/vite/dist/node/chunks/dep-971d9e33.js:19120:20)
    at compileCSS (/home/projects/gqaiqayql.github/node_modules/vite/dist/node/chunks/dep-971d9e33.js:18850:40)
    at async transform (/home/projects/gqaiqayql.github/node_modules/vite/dist/node/chunks/dep-971d9e33.js:18485:50)
```

I got the same error on my local machine.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/myakura/test--astro-v0-23-0-scss

**Comment by iozcelik** [comment]
Do you install sass from npm?

**Comment by myakura** [comment]
@iozcelik 

> Do you install sass from npm?

No I don't. I don't think it's necessary. The code works in v0.22.0.
Or does Astro now require installing sass separately?

**Comment by myakura** [comment]
Ooh I missed the migration guide.
https://docs.astro.build/en/migrate/#missing-sass-error

So I now have to install sass. Got that. Sorry for the noise~
