### ISSUE TITLE
🐛 BUG: Retype plugins are not working 

### ISSUE THREAD

**Issue by niksmac** [withastro/astro#2636]
### What version of `astro` are you using?

0.23.0

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Retype plugs are not generating links 

### Link to Minimal Reproducible Example

https://codesandbox.io/s/github/withastro/astro/tree/latest/examples/with-markdown-plugins?file=/package.json:372-382

**Comment by FredKSchott** [comment]
Fixed in v1.0.0-beta!
