### ISSUE TITLE
🐛 BUG: Unable to use dynamic imports in the static build

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#2647]
### What version of `astro` are you using?

0.23.0

### What package manager are you using?

pnpm

### What operating system are you using?

Ubuntu

### Describe the Bug

Getting `Unknown file extension ".ext" for "path/to/file.ext"` every time when trying to use dynamic imports in static build.

Error example:
```js
Error rendering: TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".jpg" for /media/mariamrafid/WEB DEVELOPMENT/ubuntu/astro-image-demo/src/images/elva-800w.jpg
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async Promise.all (index 0) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-metubz?file=src%2Fpages%2Findex.astro

**Comment by matthewp** [comment]
Hey @RafidMuhymin, I did some research and apparent Vite is using this rollup plugin for dynamic imports: https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#imports-must-end-with-a-file-extension

And notice from that link that it must end in an extension. I have a fork of your Stackblitz that works: https://stackblitz.com/edit/github-metubz-6ak3tn?file=src%2Fpages%2Findex.astro

Should we maybe add a link to that documentation from our own docs? I'm not sure where it would go...

**Comment by matthewp** [comment]
Actually it seems like we might be suppressing a warning that's already happening, let me investigate that.

**Comment by matthewp** [comment]
Looks like Vite doesn't do that warning in SSR: https://github.com/vitejs/vite/blob/596494948a6e2f697232371b200c2d7a51d386bc/packages/vite/src/node/plugins/importAnalysis.ts#L442

I guess they are figuring that it will work in SSR, which is true in dev, I guess.

**Comment by matthewp** [comment]
This is being fixed upstream and will come through in a future release, thanks!

**Comment by simonwiles** [comment]
Is there any work around for this?  I'm trying to dynamically import images and I have their names and paths in an array I'm looping through.  The extensions could be `.jpeg`, `.png`, `.webp`, and probably others in the future, so I can't hard-code them as in the working stackblitz above.  I'm unclear on the status of this; are we hoping for this to be fixed upstream in Vite such that this will be possible?  Do I need some other kind of approach?  Would appreciate any insight!  Thanks!
