### ISSUE TITLE
🐛 BUG: custom 404 page doesn't render

### ISSUE THREAD

**Issue by mmakrzem** [withastro/astro#2661]
### What version of `astro` are you using?

0.23.1

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Describe the Bug

I've created a src/pages/404.astro file.  When I run **astro dev** and try to hit a url that doesn't exist than I see my 404 page.  

However when I do **astro build** and **astro preview** then when I hit a url that doesn't exist I don't see my 404 page, instead I see this:  
![image](https://user-images.githubusercontent.com/1681264/155734519-e1104d6e-cec0-49a1-9a1d-f9be50c28e12.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/holy-grass-te4nxz?file=/src/pages/404.astro

**Comment by mmakrzem** [comment]
also noticed that once I published my astro site to a server, if I try to access a file that doesn't exist ie www.mysite.com/something.html then the 404 page displays.  However if I try to access a directory (ie www.mysite.com/someDir/) then the 404 page doesn't load properly

**Comment by mmakrzem** [comment]
with further investigation I see why my published 404 site doesn't render properly.  The 404.html file is trying to load "../assets/404.dd734ee4.css" however this css file is in a different location.  So the 404.html file that gets generated should instead do "/assets/404.dd734ee4.css" to get the correct path.

**Comment by tony-sull** [comment]
@mmakrzem Does adding a `<base>` tag to the 404 page's head do the trick?

```html
<head>
  <base href="/404" />
</head>
```

**Comment by FredKSchott** [comment]
@sarah11918 any chance that you could add a mention of this fix to our 404 page docs? I think the long-term fix will be to use absolute URL pathnames (`/assets/...`) instead of relative ones.

**Comment by mmakrzem** [comment]
@tony-sull added the <base> tag to the head doesn't seem to change any behaviour.

**Comment by neuro-bro** [comment]
Still not working in 1.0.0-beta.5. Page location: src/pages/404.astro. Tested with http://localhost:3000/x

Doubt it is related but Tailwind is not hot reloading properly either.

**Comment by delucis** [comment]
I think 72c2c86 fixed this in production (an issue where `404.astro` was building to `404/index.html` while most services look for `404.html`), but yes, looks like Astro doesn’t pick up a custom 404 in dev.

Here’s a minimal reproduction: https://stackblitz.com/edit/github-gp5hpy
