### ISSUE TITLE
🐛 BUG: Workers don't work in tsx files, it give an SSR error

### ISSUE THREAD

**Issue by okikio** [withastro/astro#2670]
### What version of `astro` are you using?

0.23.2

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

The error is this
![image](https://user-images.githubusercontent.com/17222836/155875964-c485827f-a28e-4469-a487-bf0eeb3909d8.png)

For some reason no matter what I do Astro won't let me create Workers and it seems like it's because of the SSR stuff.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bjemml?file=src%2Fcomponents%2FEditor.tsx

**Comment by FredKSchott** [comment]
This is a Vite feature but we don't document this as an Astro feature. If anyone is able to help debug further, that would be great! It would be fantastic if Vite gave us this for free.

**Comment by matthewp** [comment]
Given the age of this issue I'm going to close. Please reopen if this is something Astro related and still occurs in 1.4.x.
