### ISSUE TITLE
🐛 BUG: CSS not injected into HTML when importing it via ESM

### ISSUE THREAD

**Issue by jmartsch** [withastro/astro#2672]
### What version of `astro` are you using?

0.23.0

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

My global stylesheet is not included when I built the site. In dev everything is working fine.
I have a src/styles/site.css file (uses Tailwind CSS)  and reference it in my MainLayout.astro (which will be imported on all pages)  like described on https://docs.astro.build/en/guides/styling/#global-styles

@Muhymin told me to look here https://docs.astro.build/en/migrate/#deprecated-astroresolve and use  ESM Import instead of Astro.resolve, so the documentation seems to be outdated and should be updated.

After that I used an ESM import in the layouts/MainLayout.astro file, but the CSS is not reflected after running `npm run build` in the HTML. It should be there right before the closing HEAD tag.

![image](https://user-images.githubusercontent.com/551551/155899812-dd3faabd-a1fc-4e74-9cf3-07d54da9ec68.png)

Another user had a similar problem in the discord but he was using SCSS instead of plain CSS.

The build works fine and the CSS is added if I use `astro build --experimental-static-build`. But it renames my `index.css` file to Header.hash.css. Why is that?

You can find the repo here https://github.com/jmartsch/ammonito-astro and I cloned it on stackblitz.

Maybe you can take a look at my repo and find the bug why without the experimental-static-build the CSS is not included.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/ammonito

**Comment by jmartsch** [comment]
E.Erdem from Discord wrote me this:

> Hi @Jens Can you try adding an inline style to the head section of your layout file:
> 
> <style>
> i {
> color: black;
> }
> </style>
> 
> The rule doesn't matter, but there should be at least one rule.

My result:
When I add this, a css file is generated, but no link to it is injected into the HTML, instead only the inline style appears in the head. I used this without the --experimental-static-build flag

**Comment by matthewp** [comment]
Given that it works in `--experimental-static-build` I think it's unlikely we'll make a change to the legacy build. Is there any problem with using that flag? It will became the default in 0.24.

**Comment by jmartsch** [comment]
No not a problem at all. So I will close this issue now.
