### ISSUE TITLE
🐛 BUG: client onLoad called twice

### ISSUE THREAD

**Issue by millette** [withastro/astro#2673]
### What version of `astro` are you using?

0.23.2

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### Describe the Bug

onLoad (onVisible, etc.) are called twice. I'm using solid and the first time, no root is found (astroid doesn't match) but the second time astroid matches with the html and the root is found.

*Sorry, the example doesn't reflect the problem.*

### Link to Minimal Reproducible Example

https://stackblitz.com/github/gqaiqojag?file=package.json

**Comment by tony-sull** [comment]
Hey @millette!  The stackblitz link isn't working for me for some reason, any chance you can include another repro here so we can take a look?
