### ISSUE TITLE
🐛 BUG: scss anomalies

### ISSUE THREAD

**Issue by VodnikAngus** [withastro/astro#2680]
### What version of `astro` are you using?

0.23.2

### What package manager are you using?

npm

### What operating system are you using?

Fedora Linux 35

### Describe the Bug

Scss acts weird with astro. First of all on my machine I don't even have the ``sass`` dependency or any global npm package or standalone executable from any package manager, but I had to add it for stackblitz, all these issues are hard to replicate but I think they are connected.

If I use ``@import`` or ``@use`` in scss ``:global()`` selector gets completely ignored: ``:global(main)`` in ``src/layouts/Boilerplate.astro:54``

Some scss classes don't get scoped: ``.wrapper`` class in ``src/layouts/Boilerplate.astro:45``

I don't know should import aliases even work with scss, but those aren't working either

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-n66nua?file=src%2Fpages%2Flog-in.astro

**Comment by FredKSchott** [comment]
We defer most of this logic to Sass as a pre-processor, so there's not too much that we can do here. Based on some quick googling, you may need to escape the global selector in Sass?
https://stackoverflow.com/a/47279128
