### ISSUE TITLE
🐛 BUG: 404 page in the static build is built to `404/index.html` instead of `404.html`

### ISSUE THREAD

**Issue by tony-sull** [withastro/astro#2689]
### What version of `astro` are you using?

0.23.3

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using the `--experimental-static-build`, `src/pages/404.astro` is built to `dist/404/index.html` instead of `dist/404.html`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-t1gvmd

**Comment by dfghjkjhgr** [comment]
This might not be a bug: https://docs.astro.build/en/reference/configuration-reference/#pageurlformat

**Comment by matthewp** [comment]
This is fixed in `next`
