### ISSUE TITLE
🐛 BUG: `<script>` in component appears to resolve relative to the page using the component

### ISSUE THREAD

**Issue by delucis** [withastro/astro#2701]
### What version of `astro` are you using?

0.23.3

### What package manager are you using?

npm

### What operating system are you using?

macOS 12.2.1 / Stackblitz

### Describe the Bug

It looks like resources (scripts in this case) imported in a component are being resolved relative to the page that uses the component rather than the component itself.

`src/components/component.astro`

```astro
---
---
<script type="module" hoist>import '../scripts/script.js'</script>
```

`src/pages/index.astro`

```astro
---
import Component from '../components/component.astro';
---
<Component/>
```

^ This works because the page and component are at the same depth.

`src/pages/subdir/index.astro`

```astro
---
import Component from '../../components/component.astro';
---
<Component/>
```

^ This doesn’t work because the page is one level deeper than the component.

I have tried this with and without the `--experimental-static-builds` flag with the same result.

<details>
<summary>Error stack trace</summary>

```
[vite] Internal server error: Failed to resolve import "../js/script.js" from "src/pages/nested-page/index.astro?html-proxy&index=1.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/projects/github-ripnxh/src/pages/nested-page/index.astro?html-proxy&index=1.js
  1  |  import '../js/script.js';
     |          ^
      at formatError (/home/projects/github-ripnxh/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38098:46)
      at TransformContext.error (/home/projects/github-ripnxh/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38094:19)
      at normalizeUrl (/home/projects/github-ripnxh/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:69823:26)
      at async TransformContext.transform (/home/projects/github-ripnxh/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:69963:57)
      at async Object.transform (/home/projects/github-ripnxh/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38334:30)
```

</details>

I came across this while debugging this support thread, but that also features a different error message so may be unrelated: https://discord.com/channels/830184174198718474/948322821203984484

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ripnxh?file=src/pages/index.astro

**Comment by matthewp** [comment]
The flag is `--experimental-static-build` without an `s`. If I remove that your Stackblitz appears to work properly. Let me know if you have any issues.

**Comment by delucis** [comment]
Oof, well spotted, thank you! Hope it didn’t take too much of your time to figure that one out.
