### ISSUE TITLE
🐛 BUG: warning "getStaticPaths() called twice during the build"

### ISSUE THREAD

**Issue by gbizetdev** [withastro/astro#2723]
### What version of `astro` are you using?

0.23.6

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Warning message about **getStaticPaths()** keeps displaying in some pages:

**[routeCache] Internal Warning: getStaticPaths() called twice during the build. (src/pages/product/[slug].astro)**

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-thklzz?file=src/pages/product/[slug].astro

**Comment by songololo** [comment]
I'm also running into this. I've also noticed that `client:only` components load twice in the browser (from a built site). Don't know if this is related or not.
