### ISSUE TITLE
🐛 BUG: `client:only` is broken when component used more than once

### ISSUE THREAD

**Issue by LorenzoLeonardini** [withastro/astro#2725]
### What version of `astro` are you using?

0.23.7

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Note: this bug report uses Svelte components because that's the only framework I know, feel free to test with React and friends and compare the results.

**Bug description**
If I import a component and use it more than once in a page, specifying `client:only`, only the last instance of the component gets added to the page. Also, the site **refuses to build**

**The setup**
A simple `Test` component with a `content` prop, it renders "content" into an `<h1>`. You would expect to be able to do something like
```html
<Test content='Test 1' client:only />
<Test content='Test 2' client:only />
<Test content='Test 3' client:only />
```
and have all the titles show up in the page, but only the last one gets added.

If you don't specify `client:only` all three of them get added.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nejdnv?file=src/pages/index.astro

**Comment by yusufhilmi** [comment]
I had the same problem with Vue as well. Once we use a component more than once it doesn't show up. A similar issue [here](https://github.com/withastro/astro/issues/2294). I have a workaround solution until a fix has been pushed. Try implementing another component to encapsulating these 3.

**Comment by LorenzoLeonardini** [comment]
Unfortunately, for my use, it's not really possible to wrap stuff into other components. I'm just using `client:load` for now.
