### ISSUE TITLE
🐛 BUG: postcss custom media

### ISSUE THREAD

**Issue by 7flash** [withastro/astro#2731]
### What version of `astro` are you using?

^0.23.7

### What package manager are you using?

pnpm

### What operating system are you using?

Windows 11

### Describe the Bug

Installed PostCSS Plugin: 

```
npm install postcss-custom-media --save-dev
```

Added postcss.config.cjs

```
module.exports = {
  plugins: {
    autoprefixer: {},
    postcssCustomMedia: {}
  }
};
```

Getting the error in browser 

```
Loading PostCSS Plugin failed: Cannot find module 'postcssCustomMedia'
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6fuz8b?file=src/pages/index.astro

**Comment by JuanM04** [comment]
You need to write the exact name of the plugin you want to import. In your case, it will be like this:

```js
module.exports = {
  plugins: {
    autoprefixer: {},
    "postcss-custom-media": {}
  }
};
```

**Comment by 7flash** [comment]
This CSS I am using for testing

```
		.FeaturedImage {
			position: absolute;
			bottom: 0;
			right: 0;
			z-index: -1;

			@media (--portrait) {
				display: none;
			}

			@media (--landscape) {
				display: none;
			}
		}

```

I am expecting the page to never show, but it does show always

**Comment by 7flash** [comment]
This my postcss.config.cjs

```
module.exports = {
  plugins: [
    require('autoprefixer'),
    require('postcss-custom-media')
  ]
};
```

**Comment by 7flash** [comment]
Changed to this but still no effect @JuanM04 @natemoo-re 

```
module.exports = {
  plugins: {
    autoprefixer: {},
    "postcss-custom-media": {}
  }
};
```

**Comment by JuanM04** [comment]
What's the error now?

**Comment by 7flash** [comment]
> What's the error now?

Now there is no error, but my CSS example not working as expected

**Comment by JuanM04** [comment]
1. Did you declare `--portrait` and `--landscape`?
2. I've noticed you are nesting CSS but you have neither `postcss-nesting` nor `postcss-nested` installed. Try using the `@media` outside that block.
3. Where is that css? Is it in a file, or in a style tag? Could you share a more complete example?

**Comment by 7flash** [comment]
--portrait and --landscape are coming from openprops

https://open-props.style/#media-queries

**Comment by 7flash** [comment]
Fixed nesting but still no effect
```
		@media (--portrait) {
			.FeaturedImage {
				display: none;
			}
		}

		@media (--landscape) {
			.FeaturedImage {
				display: none;
			}
		}
```

**Comment by JuanM04** [comment]
> --portrait and --landscape are coming from openprops

Could you try to declare them yourself in the same file with those `@media`?

**Comment by mark-looptimize** [comment]
Just wanted to say that I ran into this same issue today in the context of using PostCSS with [Astro](https://github.com/withastro/astro) to build a single component file.

![Screenshot 2022-09-12 6 12 15 PM](https://user-images.githubusercontent.com/84925676/189715818-5e9c6347-cb65-466b-a787-7a34597f601f.png)

I can confirm that this don't transform correctly.

**Comment by brandon-pereira** [comment]
For me, the issue was that I had the `@custom-media --tablet (min-width: 720px);` (in my case) declared at the root of the all `Layout.astro` but it needs to be in the same component as the @media query, which for me isn't exactly what I was hoping, I wanted to define a global variable for the whole app to use the same media queries

**Comment by Mrowa96** [comment]
Yep, I was trying to follow instruction from official plugin docs [here](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-custom-media#modular-css-processing) but unfortunately it doesn't look to work with Astro.

**Comment by brandon-pereira** [comment]
@Mrowa96 I was able to get it to work the `postcssGlobalData` option!

**Comment by Mrowa96** [comment]
@brandon-pereira That's weird, I tried again and indeed it works!

For others struggling with it here is my code
```js
const postcssGlobalData = require('@csstools/postcss-global-data');
const postcssCustomMedia = require('postcss-custom-media');
const postcssNesting = require('postcss-nesting');

module.exports = {
  plugins: [
    postcssGlobalData({
      files: ['./src/styles/media.css'],
    }),
    postcssCustomMedia(),
    postcssNesting(),
  ],
};
```

**Comment by JoeMorgan** [comment]
> @brandon-pereira That's weird, I tried again and indeed it works!
> 
> For others struggling with it here is my code
> 
> ```js
> const postcssGlobalData = require('@csstools/postcss-global-data');
> const postcssCustomMedia = require('postcss-custom-media');
> const postcssNesting = require('postcss-nesting');
> 
> module.exports = {
>   plugins: [
>     postcssGlobalData({
>       files: ['./src/styles/media.css'],
>     }),
>     postcssCustomMedia(),
>     postcssNesting(),
>   ],
> };
> ```

Thank you, this helped me when I was just about to give up on using custom media in my app.
