### ISSUE TITLE
🐛 BUG: Some styles lost when using components in markdown

### ISSUE THREAD

**Issue by tony-sull** [withastro/astro#2764]
### What version of `astro` are you using?

0.23.7

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Styles are being lost for components used in markdown, only during `build` (`dev` has the styles as expected)

I just noticed this on [Astro's blog ](https://astro.build/blog/astro-021-release/) and haven't managed to reproduce it in a starter project yet

I narrowed it down to [this](https://github.com/withastro/astro.build/commit/d8fc6d796239e18d2f4b136179b31629cf3eba93) commit moving the site over to the static build.  [This code](https://github.com/withastro/astro.build/commit/d8fc6d796239e18d2f4b136179b31629cf3eba93#diff-ad765aceefcde2264545092cdf141aae68f851b0856e7b57090a40121cdcd469) seems like the most likely cause, we have a bit of a different setup for how posts content is loaded in and treated as an Astro component

### Link to Minimal Reproducible Example

https://github.com/withastro/astro.build

NOTE: This has been fixed in the latest astro.build release, sync to [this commit](https://github.com/withastro/astro.build/commit/0d3436c58da63ba8ad3c96e85d5c8aef9eaf09a2) to debug locally

**Comment by tony-sull** [comment]
I've tried a few different ways to reproduce this one in the blog starter and can't actually manage to get it to hit.  There's a corner case bug here somewhere, but it's not easy to hit at all so I wouldn't put too much priority on tracking this one down immediately :+1:

**Comment by matthewp** [comment]
Given that this is a legacy markdown feature that we are no longer supporting, I'm going to close this issue.
