### ISSUE TITLE
🐛 BUG: `<svelte:head>` content is not injected

### ISSUE THREAD

**Issue by natemoo-re** [withastro/astro#2769]
### What version of `astro` are you using?

0.24.0

### What package manager are you using?

all

### What operating system are you using?

Mac

### Describe the Bug

Followup to https://github.com/withastro/astro/issues/2128

Users expect `<svelte:head>` content to be projected into Astro's `head`, but this doesn't happen until client-side rendering occurs.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fkakju?file=src%2Fcomponents%2FCounter.svelte&on=stackblitz

**Comment by FredKSchott** [comment]
**Notes from core sync:**

- the ability to inject into `head` isn't supported in any framework, even Astro components
- current workaround: move it into an Astro head (may not work for all users, especially Svelte packages).
- concerns around making streaming harder (but not impossible)

**Comment by matthewp** [comment]
Given that we support streaming now we can't support this feature without some API level change (like turning streaming off perhaps). So closing as this would need an RFC to support.
