### ISSUE TITLE
🐛 BUG: Vite "define" aliases throwing errors on build and ignored in dev

### ISSUE THREAD

**Issue by BobToninho** [withastro/astro#2774]
### What version of `astro` are you using?

0.24.0

### What package manager are you using?

npm, yarn

### What operating system are you using?

Ubuntu (WSL), WebContainers

### Describe the Bug

When adding a global alias using vite's define option ([docs](https://vitejs.dev/config/#define)) this is not recognized.

While in `dev` it is simply ignored and when building it breaks the build.
It breaks with v0.24.0, in 0.23.0 it was working ([repro](https://stackblitz.com/edit/github-idvd6o?file=astro.config.mjs))

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-njhw7j?file=astro.config.mjs

**Comment by FredKSchott** [comment]
Thanks @BobToninho! I tracked a fix into a part of the codebase that I was already cleaning up in #2772, so I added the fix to that PR. 

I think this makes sense to fix as a regression from previous behavior. Most likely, we]'ll want to formalize these config options into either official Astro config, or some understanding of what Vite configs do/do not work (related: #2782)
