### ISSUE TITLE
🐛 BUG: Vue components in layout results in vendor bundle on all pages

### ISSUE THREAD

**Issue by preetamslot** [withastro/astro#2775]
### What version of `astro` are you using?

0.24

### What package manager are you using?

npm

### What operating system are you using?

windows

### Describe the Bug

steps:
1. Create a base layout with a Vue component inside
2. Create an intdex. astro with Vue components
3. Create a markdown page that makes use of an Astro layout extending the base layout

After the build, the markdown generated page will have a vendor js file with dependencies for the index page.

### Link to Minimal Reproducible Example

https://github.com/preetamslot/astro-bug-vue-component-in-layout

**Comment by FredKSchott** [comment]
I believe that this has been fixed in Astro v1.0.0 beta. If you can update your reproduction and still see a bug, please file a new issue and someone will take another look!
