### ISSUE TITLE
🐛 BUG: Error Failed to load module for SSR

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#2781]
### What version of `astro` are you using?

0.24.0

### What package manager are you using?

pnpm

### What operating system are you using?

Ubuntu

### Describe the Bug

After upgrading to `astro@0.24.0-next.1`, I'm getting `Failed to load module for SSR` error. I am able to reproduce the issue even in the `minimal` starter. All the versions are working fine till `astro@0.24.0-next.0`. So, some code changes between the [two versions](https://github.com/withastro/astro/compare/astro%400.24.0-next.0...astro@0.24.0-next.1) may have caused the issue.

`astro build`

![image](https://user-images.githubusercontent.com/63650415/158069838-69b4547b-3db6-4474-bf95-46303cad7878.png)

`astro dev`

![image](https://user-images.githubusercontent.com/63650415/158069847-bb329cbb-fe79-4e9d-9809-a4256cede1de.png)

But the main problem only a few users are experiencing this issue. Till now, three users have reported this issue. One of them is using Ubuntu, the other one Windows, and the other one Mac.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal

**Comment by manishshahi1** [comment]
Getting same issue with minimal and every other template based installation such as svelte.

**Comment by matthewp** [comment]
Thanks everyone. For those who are seeing this problem, is it happening sporadically or does it always occur?

**Comment by manishshahi1** [comment]
I installed Astro a few days ago it was working fine. But since today I am getting the error.

**Comment by RafidMuhymin** [comment]
@matthewp It's happening all the time.

**Comment by matthewp** [comment]
Here's the diff between the versions where the regression was noticed: https://github.com/withastro/astro/compare/astro@0.24.0-next.0...astro%400.24.0-next.1

**Comment by matthewp** [comment]
@manishshahi1 can you share your OS version and Node version?

**Comment by matthewp** [comment]
@manishshahi1 Are you using pnpm by chance?

**Comment by matthewp** [comment]
I'm able to recreate this now, it's related to the fact that there is a space in your filepath.

I think it's probably this bug: https://github.com/vitejs/vite/issues/7300

**Comment by colinthedev** [comment]
This error can also occur if the filepath for an import does not match what it should be.

**Comment by patrick91** [comment]
> This error can also occur if the filepath for an import does not match what it should be.

Yes! thanks! I forgot to add `.astro` in an import inside an MDX file

**Comment by marcelocra** [comment]
> This error can also occur if the filepath for an import does not match what it should be.

Wow.. I didn't even noticed that `.astro` imports were different than React ones:

```diff
-import { AstroComponent } from "../path/to/AstroComponent";
+import AstroComponent from "../path/to/AstroComponent.astro";
```

Solved for me, thanks!
