### ISSUE TITLE
🐛 BUG: unnecessarily generating js in ./dist

### ISSUE THREAD

**Issue by npup** [withastro/astro#2784]
### What version of `astro` are you using?

0.24

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

`astro build` generates an unnecessary (react related) js file even when there is no reason to ship javascript.

#shipless

The problem is not observable in `astro@0.23.7`.

Reproduction is here: https://github.com/npup/why-js

### Link to Minimal Reproducible Example

https://github.com/npup/why-js

**Comment by tony-sull** [comment]
Great catch!  Agreed that JS bundle shouldn't be built :+1:

Initially I was expecting to find a react component in the project that's just never `client:` hydrated.  It's really interesting that react is being bundled up even with any react or `renderer-react` reference, maybe it bled in from our internal JSX dependencies?

**Comment by npup** [comment]
> Initially I was expecting to find a react component in the project that's just never `client:` hydrated.

Me too ("what - I must have left a React component here somewhere!"), so  I double checked.  In fact, I was in the process of preparing a seminar on my beloved Astro, and wanted to showcase exactly the js-less-ness of it.  The irony! :D

**Comment by preetamslot** [comment]
Got the same with Vue files, and if you include Vue components in the layout, scripts are loaded on all pages:
https://github.com/withastro/astro/issues/2775

**Comment by FredKSchott** [comment]
Fixed in v1.0.0-beta, I can no longer reproduce in your repo
