### ISSUE TITLE
🐛 BUG: Custom Astro components not parsed in Markdown pages after Astro.fetchContent

### ISSUE THREAD

**Issue by andreg** [withastro/astro#2799]
### What version of `astro` are you using?

0.24.0

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Not entirely sure if I'm doing things correctly here, but I am trying to display paginated posts in a page, along with their respective content.

Posts are written in Markdown and use a custom Astro component in their content, along with regular Markdown text.

The individual post page is ok and the custom component is rendered correctly, but when I try to grab the page content in a pagination context (so, after `Astro.fetchContent( './blog/*.md' )` has been called), the custom element is not rendered, and its non-HTML tag is kept in the content instead.

**Original post content**

````
Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.

<Test />
````

**Rendered post content in the pagination cycle**

````
<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p>

<Test />
````

Is there a way to make use of custom components for Markdown pages also in the context of a `Astro.fetchContent` cycle?

### Link to Minimal Reproducible Example

n/a

**Comment by natemoo-re** [comment]
Yes, there's a way to do this! Instead of using the `content` string that is returned by `Astro.fetchContent`, you should use the `Content` component it returns. [See working example.](https://stackblitz.com/edit/github-re8pbx?file=src%2Fpages%2Findex.astro)
