### ISSUE TITLE
🐛 BUG: Sourcemap for XXXX points to missing source files

### ISSUE THREAD

**Issue by manishshahi1** [withastro/astro#2805]
### What version of `astro` are you using?

0.24.1

### What package manager are you using?

npm

### What operating system are you using?

Windows 8.1

### Describe the Bug

After installing minimal template and running the installation with npm start command. I get following errors:

Sourcemap for "C:/Users/Windows 8.1/Desktop/quest/node_modules/astro/dist/runtime/server/index.js" points to missing source files
Sourcemap for "C:/Users/Windows 8.1/Desktop/quest/node_modules/astro/dist/runtime/server/hydration.js" points to missing source files
Sourcemap for "C:/Users/Windows 8.1/Desktop/quest/node_modules/astro/dist/runtime/server/util.js" points to missing source files
Sourcemap for "C:/Users/Windows 8.1/Desktop/quest/node_modules/astro/dist/runtime/server/escape.js" points to missing source files
Sourcemap for "C:/Users/Windows 8.1/Desktop/quest/node_modules/astro/dist/runtime/server/metadata.js" points to missing source files
Sourcemap for "C:/Users/Windows 8.1/Desktop/quest/node_modules/astro/dist/runtime/client/hmr.js" points to missing source files

Are they serious?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jhuzfh?file=src/pages/index.astro

**Comment by manishshahi1** [comment]
Minimal reproducible example link is for example. please install the minimal template at your end. requesting.

**Comment by VodnikAngus** [comment]
Should be addressed with #2806 by @natemoo-re

**Comment by natemoo-re** [comment]
This has been fixed! Please upgrade to `astro@0.24.3`

**Comment by manishshahi1** [comment]
@natemoo-re thanks :)
