### ISSUE TITLE
🐛 BUG: v0.24.1 generate wrong pagination result

### ISSUE THREAD

**Issue by patrickdung** [withastro/astro#2813]
### What version of `astro` are you using?

0.24.1

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I have a JSON file to store the article metadata.
I used a [...page].astro for pagination, like:

```
export async function getStaticPaths({ paginate, rss }) {

  const articlesJSON = fs.readFileSync('content/posts.json')
  let articlesList = JSON.parse(articlesJSON)
  articlesList = articlesList.sort((a, b) =>
    new Date(b.date).valueOf() - new Date(a.date).valueOf())

  console.log ("DEBUG1 page.astro: ", articlesList)

  for (let i=0; i<articlesList.length; i++) {
    articlesList[i].url =
      "posts/" + articlesList[i].category + "/"
      + format (parseISO(articlesList[i].date), 'yyyy-MM-dd') + "/"
      + articlesList[i].slug + "/"
  }
  rss({
    title: `${import.meta.env.SITENAME}`,
    description: `${import.meta.env.SITENAME}`,
    customData: `
      <author>
        <name>${import.meta.env.AUTHOR}</name>
      </author>`,
    dest: '/rss.xml',
    items: articlesList.map (article => ({
      title: article.title,
      description: article.description,
      link: article.url,
      pubDate: article.date,
    })),
  })

  console.log ("DEBUG2 page.astro: ", articlesList)

  return paginate (articlesList, {pageSize: import.meta.env.PAGINATION_SIZE})
} // getStaticPaths
const { page } = Astro.props
let pageDescription = `Page ${page.currentPage} of ${page.lastPage}`;

console.log ("DEBUG3 page.astro: ", page.data)
```
Now if there are 6 entries in the JSON file, there are two pages and each page has 3 entries. (correct)

Now if there are 7 entries in the JSON file, there are three pages (total no of page is correct), but:

1) first page is correct (first 3 entries)
2) second page is incorrect. it has 4 entries. The first three entries is for the second page (correct). But it include an extra entry, it is from the last page.
3) last page is correct (have a single / the last entry)

Besides that, if you set the pagination size to 1 or 2, the result of some of the pages are wrong. It had included extra number of entries. From my observation, (usually) the first and the last page is correct.

### Link to Minimal Reproducible Example

N/A

**Comment by patrickdung** [comment]
Using this seems to produce the correct result for pagination size 2 or 3:

```
    <ul>
    {page.data.slice(0, import.meta.env.PAGINATION_SIZE).map (article => (
      <li>
        <a href={`/${article.url}`}>
          {article.title} - {article.category} - {article.date}
        </a>
      </li>
    ))}
    </ul>
```

**Comment by FredKSchott** [comment]
We can't reproduce or fix this issue without a Reproducible Example. Can you create one here: astro.new

The `blog-with-multiple-authors` template has a pagination example that you can borrow from.

**Comment by matthewp** [comment]
Closing as its been a month without a response. Please try against the 1.0 beta and produce an example, thanks!

**Comment by scottaw66** [comment]
@matthewp I have a repro for this, but it only seems to happen when a variable value is passed in for the value of pageSize to the paginate function.

Repro repo is here: https://github.com/scottaw66/astro-pagination-bug
