### ISSUE TITLE
🐛 BUG: `dist` cannot be a parent directory, symlink directory, etc. (Cannot find package shorthash)

### ISSUE THREAD

**Issue by kukac7** [withastro/astro#2817]
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

npm 8.3.0

### What operating system are you using?

Mac

### Describe the Bug

hi,

could the problem be that the project is in a subfolder?

```
npm run build
$ astro build
10:38:17 PM [config] Set "buildOptions.site" to generate correct canonical URLs and sitemap
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'shorthash' imported from /home/projects/github-bjdfp4/public/index.2b609de1.mjs
    at NodeError.get (https://github-bjdfp4.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:286334)
    at __node_internal_ (https://github-bjdfp4.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:1492)
    at new NodeError (https://github-bjdfp4.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:2995)
    at packageResolve (https://github-bjdfp4.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:365802)
    at https://github-bjdfp4.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:366908
    at Loader.defaultResolve [as _resolve] (https://github-bjdfp4.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:367507)
    at Loader.resolve (https://github-bjdfp4.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:1019940)
    at Loader.getModuleJob (https://github-bjdfp4.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:1021996)
    at https://github-bjdfp4.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:734578
    at _0x52ceac.link (https://github-bjdfp4.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:232691)
```

`astro.config.mjs`:

```
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  // Enable the Preact renderer to support Preact JSX components.
  renderers: ['@astrojs/renderer-preact'],
  projectRoot: '../frontend/',
  dist: '../public/',
});
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bjdfp4

**Comment by FredKSchott** [comment]
Yea, our build will output some JS files that are then run to generate the rest of your site, so my guess is that the npm dependency isn't loadable from your output folder (`public/`) because it was installed to the subfolder `frontend/node_modules/`.

**Comment by FredKSchott** [comment]
FYI this is a short-term limitation that I believe @matthewp is working to solve (by bundling your build into a single JS file, so there will be no dependencies to load). So for the short-term, you'll need to make sure that your output `dist` directory isn't a parent of your project root (or wherever your npm dependencies are installed).

**Comment by matthewp** [comment]
Bundling into a single file is pretty slow, I don't think it's a good choice for SSG if we can avoid it.

**Comment by matthewp** [comment]
We could have a single entrypoint and that might speed up some builds, but that's a different question from whether we should bundle node_modules deps. The latter involves all of your dependencies going through every Vite/Rollup plugin, then get all concatenated together. It's probably a necessary requirement for SSR but not so for SSG.

**Comment by FredKSchott** [comment]
Ah, I see what you mean now. If we separate those two issues, then I agree, what Nate called out is probably the correct issue here: `astro/*` files are getting bundled, but then their sub-dependencies are getting externalized through our `ssr.external` Vite settings. You can see `shorthash` in the `ALWAYS_EXTERNAL` array, probably causing this issue. We should either bundle all of Astro (and its subdeps) or none of astro (therefore fixing the pnpm case, at least).

But... if we need full bundling for SSR anyway... do we really want to maintain two different build/bundle configs? It would be really nice if we kept SSG & SSR as close as possible, vs. maintaining and debugging two different configurations and their outputs. If the cost is a couple of extra seconds of build time, I think that would be well-worth the reduced maintenance cost.

**Comment by FredKSchott** [comment]
Also because this topic always gets me curious, I did a quick test against the DDT codebase to output a single JS file (including deps bundled) vs. our current output, and saw a 10-20% speed up! 


```
Current:
10:46:27 AM [build] 781 pages built in 81.93s

1 Bundle /w external dependencies:
10:42:19 AM [build] 781 pages built in 78.35s

1 Bundle (only node built-ins external):
10:42:19 AM [build] 781 pages built in 65.73s  (run 1)
10:53:17 AM [build] 781 pages built in 73.81s  (run 2)
```

Bundling everything actually was faster than our current settings, which is curious and worth digging more into. Maybe it is faster, but at the very least I think it would have a trivial impact compared to all of the other build logic we do, and would also really help with consistency ("I moved from SSG to SSR, and all of my deps broke!").

**Comment by tony-sull** [comment]
This is an interesting one related to how our SSR builds are currently built - can we build to a single JS file?

Astro is using a temp folder during the build and there's likely cleanup we could do here to avoid writing to file during the build so dependencies can always be built to the final output directory rather than assuming it lives in the project root.

Marking this as a nice to have for 1.0 mainly due to the complexity and potential risk of the fix, but this would be a great one to see fixed to handle more complex build configurations 👍

**Comment by matthewp** [comment]
Thank you @rishi-raj-jain! Given that, I'm going to close. @kukac7 please open a new issue if you are still seeing this problem.
