### ISSUE TITLE
🐛 BUG: Hoisted Script Tags dont get updated when saving the file

### ISSUE THREAD

**Issue by muellercornelius** [withastro/astro#2834]
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

npm

### What operating system are you using?

WIndows (and I am pretty sure stackblitz is running linux)

### Describe the Bug

When adding `hoist` to a script tag (mentioned here: https://docs.astro.build/en/core-concepts/astro-components/) this script tag is processed by vite and changes in the script block after the dev server start dont get updated until the next restart of the dev server. Pretty annoying. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ptbzxn?file=src/pages/index.astro

**Comment by tony-sull** [comment]
Thanks for filing, great catch!  Looks like HMR must be missing the hoisted script for change tracking

As a work around for now, if you move the script out to it's own file and HMR will pick up changes in dev as expected

```
<script hoist type="module">
    // any changes in the .ts (or .js) files would be picked up by `astro dev`
    import "../scripts/nav.ts";
</script>
```

**Comment by FredKSchott** [comment]
Just ran into this one!

**Comment by natemoo-re** [comment]
Confirming that this was **NOT** fixed by https://github.com/withastro/astro/pull/3138. Going to dig into this one more.

**Comment by matthewp** [comment]
Will be fixed by https://github.com/withastro/astro/pull/3336
