### ISSUE TITLE
🐛 BUG: environment variables are not available in server-side code

### ISSUE THREAD

**Issue by destegabry** [withastro/astro#2846]
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I cannot access "private" env variables on server-side code, even the [official example](https://github.com/withastro/astro/tree/main/examples/env-vars) is broken.

[Here](https://stackblitz.com/edit/github-ubib9u?file=src%2Fpages%2Findex.astro&on=stackblitz) you should see the `DB_PASSWORD` env printed on page, but it's `undefined`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ubib9u?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by natemoo-re** [comment]
Thanks, this definitely looks like a regression!
