### ISSUE TITLE
🐛 BUG: Import document in path src

### ISSUE THREAD

**Issue by mandrilla34** [withastro/astro#2850]
### What version of `astro` are you using?

^0.24.3

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I'm getting this error in the browser console:  `Uncaught ReferenceError: enviarEmail is not defined
    at HTMLButtonElement.onclick`

But I'm importing my document (enviar-email.js), which is inside the src folder, as it says in the DOC: https://docs.astro.build/en/core-concepts/astro-components/#client-side-scripts

in page contato.astro:
```
<script type="module" hoist>
        import "jquery";
        import "bootstrap/dist/js/bootstrap.bundle.min.js";
        import "../js/enviar-email.js"
</script>
```

Exporting my function inside the file:
And I need to use jquery in this document
`export function enviarEmail() {`

On the page (contato.astro) where I'm importing send-email.js, I have the button element:

`<button class="btn btn-primary" onclick="enviarEmail()" type="button" id="button-enviar">Enviar</button>`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9htsqg-rydkwk?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by natemoo-re** [comment]
This is just a misunderstanding of how `type="module"` works. 

You're defining `export function enviarEmail()` in a module, but trying to reference an export via `onclick`. `onclick="enviarEmail()"` expects a global function named `enviarEmail` to be available, but there isn't one. You'd need to make sure `enviarEmail` is available on the `window` or `globalThis` object.

[Here's a working demo.](https://stackblitz.com/edit/github-9htsqg-wcdpcw?file=src%2Fpages%2Findex.astro&on=stackblitz)
