### ISSUE TITLE
🐛 BUG: Nested .astro pages not bundling JS imports on build

### ISSUE THREAD

**Issue by cpenned** [withastro/astro#2866]
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

## TLDR; Description
Nested .astro pages are not properly bundling JS files during build

## Expanded
- I have an .astro file in a nested dir (pages > projects > project-one > index.astro)
- I import a JS file `import './app.js'`
- During dev, everything works as expected
- Moving to preview or build, I get the following error when referencing the index.astro document in the app.js file: `ReferenceError: document is not defined`  when evaluating SSR module.

### Link to Minimal Reproducible Example

https://github.com/cpenned/sample

**Comment by tony-sull** [comment]
Hey @cpenned!  Any JS files in `src/pages` will attempt to build to an [API route](https://docs.astro.build/en/guides/server-side-rendering/#api-routes)

For any JS files that you need imported in the browser, they should still live inside of the `src` directory so the build finds it **but** outside pages.  I usually use something like `src/assets/app.js` to keep track of assets that I want built (CSS, JS, etc)
