### ISSUE TITLE
🐛 BUG: Lib import with CSS doesn't work in production

### ISSUE THREAD

**Issue by mandrilla34** [withastro/astro#2868]
### What version of `astro` are you using?

^0.24.3

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I'm using a library, which exports in css, flags in svg.
Lib: `"flag-icons": "^6.1.1"`

I'm getting these errors in the browser console when I build it and put it on hosting:

```
GET https://site-vallorx-astro.netlify.app/assets/__VITE_ASSET__fc872e71__ 404
```

But when I'm in the environment I'm in the development environment, with the command: `astro dev`  everything works normally.
I place the element in the HTML as informed in the Lib DOC:

```
<span class="fi fi-br"></span>
```

And I import Lib like importing any css and it works normally in Dev:

```
---
    import 'flag-icons/css/flag-icons.css';
---
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7uvf9a-dwn4w9?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by mandrilla34** [comment]
Any answer on this?

**Comment by davide93** [comment]
#2146
