### ISSUE TITLE
🐛 BUG: Conditional imports break scss

### ISSUE THREAD

**Issue by obj-obj** [withastro/astro#2883]
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

yarn (berry)

### What operating system are you using?

Linux

### Describe the Bug

Using conditional imports breaks scss generation.

Differences in generated css:

Without a conditional import:

```
html,body{width:100%;height:100%;background-color:#fff}
```

With a conditional import (invalid css):
```
@media (prefers-color-scheme:dark){$background.astro-ENRH6ACD: black.astro-ENRH6ACD{}}html,{}
```

A solution would be not bundling the css file with the conditional imports and generating two bundled css files instead, which might be possible with astro..?

I can't find anything about disabling bundling for a file.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wzme3a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ryanfitzer** [comment]
This is due to limitations in SCSS and not Astro. This would only be possible if:

1. SCSS was compiling the CSS in the browser at runtime (a big performance issue)
2. Or, SCSS supported replacing `$background: <color>;` with `--background: <color>;` at build-time, which it doesn't.

SCSS is a pre-processor and resolves all variables at build-time.

To support your needs, use CSS custom properties, which retain the declarations (variable definitions) and their usage in properties (`background-color: var(--background);`) so they can be evaluated in the browser at runtime.

**Comment by obj-obj** [comment]
@ryanfitzer two css files could be generated, with a 3rd that contains the original conditional imports (so for example `style.css` with the conditional imports, that links to `style-light.css` and `style-dark.css` if dark mode is enable). I've seen Jekyll set up like this so it *should* be possible

**Comment by ryanfitzer** [comment]
That may be the case, but your styles are preprocessed with SCSS. So the issue of the SCSS variables requiring resolution at build-time would remain.

**Comment by obj-obj** [comment]
Maybe just require "no-minify" styles to be regular css, but still resolve scss imports

**Comment by FredKSchott** [comment]
Traced to this issue: https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-astro/compile.ts#L80-L92 our regex isn't catching this type of `@import`, should be a quick fix to be a bit more flexible here.

**Comment by FredKSchott** [comment]
PRs welcome, if anyone knows Regex well enough to update!

**Comment by matthewp** [comment]
This is an upstream issue (not actually related to that regex): https://stackblitz.com/edit/vitejs-vite-d16cot?file=main.js,styles%2Fmain.scss,styles%2Fcommon.scss,styles%2Fdark.scss,styles%2Flight.scss,dist%2Fassets%2Findex.1a22d3e8.css&terminal=dev

Please feel free to file an issue upstream using that Stackblitz example.
