### ISSUE TITLE
🐛 BUG: Frontmatter variables in markdown are very inconsistent on whether they actually work or not

### ISSUE THREAD

**Issue by obj-obj** [withastro/astro#2886]
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

yarn (berry)

### What operating system are you using?

Linux

### Describe the Bug

Sometimes frontmatter variables will get inserted, and sometimes they won't, depending on what's surrounding them in the markdown

Markdown:

```md
---
notworking: working
---

{frontmatter.notworking}

{frontmatter.notworking} e

{frontmatter.notworking} {frontmatter.notworking}

- {frontmatter.notworking}

[foo]({frontmatter.notworking})

- [foo]({frontmatter.notworking})
```

HTML:
```html
<!DOCTYPE html>

frontmatter.notworking
frontmatter.notworking
<p>working e</p>
<p>working working</p>
<ul>
<li>
frontmatter.notworking
</li>
</ul>
<p><a href="%7Bfrontmatter.notworking%7D">foo</a></p>
<ul>
<li><a href="%7Bfrontmatter.notworking%7D">foo</a></li>
</ul>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9qfe1m

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
It seems to be an issue with lines that start with a `{`, this small change to the example works fine on my stackblitz:

```
---
notworking: working
---

hello, {frontmatter.notworking}.

{frontmatter.notworking} e

{frontmatter.notworking} {frontmatter.notworking}

- hello, {frontmatter.notworking}

[foo]({frontmatter.notworking})

- [foo]({frontmatter.notworking})
```

**Comment by obj-obj** [comment]
> It seems to be an issue with lines that start with a `{`, this small change to the example works fine on my stackblitz:
> 
> ```
> ---
> notworking: working
> ---
> 
> hello, {frontmatter.notworking}.
> 
> {frontmatter.notworking} e
> 
> {frontmatter.notworking} {frontmatter.notworking}
> 
> - hello, {frontmatter.notworking}
> 
> [foo]({frontmatter.notworking})
> 
> - [foo]({frontmatter.notworking})
> ```

They still don't work in links, and the line with an "e" after the variable also works, which is strange...

**Comment by obj-obj** [comment]
I added a few more examples, like for example creating a `<a>` manually and setting the href to a variable works, but if you use concatenation in that statement it messes up the entire element. Otherwise, concatenation works fine.
