### ISSUE TITLE
🐛 BUG: imported scripts are ignored in site build

### ISSUE THREAD

**Issue by 7flash** [withastro/astro#2897]
### What version of `astro` are you using?

^0.24.3

### What package manager are you using?

pnpm

### What operating system are you using?

WSL2

### Describe the Bug

Here is repository to reproduce error:

https://github.com/7flash/sleek-web-second/blob/master/src/components/SleekApp.jsx

Expected, when I run "npm run build" and serve index.html, it should render the same what renders using "npm run dev"

npm run dev:

![image](https://user-images.githubusercontent.com/4569866/159125007-34aeb216-ef2f-44e2-bcbd-abf1576157b0.png)

npm run build:

![image](https://user-images.githubusercontent.com/4569866/159125017-1b0b6eee-915c-4680-81b5-32f35a288d0e.png)

As seen on screenshot, in second case the component imported from package missing styling and functionality too

### Link to Minimal Reproducible Example

https://github.com/7flash/sleek-web-second/blob/master/src/components/SleekApp.jsx

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by 7flash** [comment]
Any ideas? That seems like urgent issue, I need to use external packages in my app @memarino92

**Comment by natemoo-re** [comment]
Going to close this in favor of consolidating issues of this nature in https://github.com/withastro/astro/issues/3217. A lot of folks have been hitting this, so it's definitely a huge priority for us.
