### ISSUE TITLE
🐛 BUG: astro build including `.debug` css when no <Debug> component present

### ISSUE THREAD

**Issue by stfullstack** [withastro/astro#2906]
### What version of `astro` are you using?

0.25.2

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

When inspecting the build output from `yarn build` there appears to be css classes for `.debug` present. It appears that they are present when using astro's `<Markdown>` component.

```css
.debug.astro-7HSJXGCA {
    background: #fff;
    font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Open Sans,Helvetica Neue,sans-serif;
    font-size: 14px;
    padding: 1rem 1.5rem
}

.debug-header.astro-7HSJXGCA,pre.astro-7HSJXGCA {
    margin: -1rem -1.5rem 1rem;
    padding: .25rem .75rem
}

.debug-header.astro-7HSJXGCA {
    background: #ff1639;
    border-radius: 4px 4px 0 0
}

.debug-title.astro-7HSJXGCA {
    color: #fff;
    font-size: 1em;
    margin: .5em 0
}

.debug-label.astro-7HSJXGCA {
    font-weight: 700;
    margin-right: .75em;
    text-transform: uppercase
}
```

### Link to Minimal Reproducible Example

na

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
Repro needed! I can't reproduce, so this was most likely fixed recently
