### ISSUE TITLE
🐛 BUG: Misleading logging when an integration sets `buildOptions.site`

### ISSUE THREAD

**Issue by delucis** [withastro/astro#2912]
### What version of `astro` are you using?

0.25.2

### What package manager are you using?

npm (8.1.2)

### What operating system are you using?

macOS 12.2.1 / Stackblitz

### Describe the Bug

In the experimental integrations API we can update the Astro config from the `astro:config:setup` hook:

```js
const integration = {
  'astro:config:setup': ({ updateConfig }) => {
    console.log('UPDATING CONFIG!');
    updateConfig({ buildOptions: { site: 'https://example.com' } });
  },
};
```

As far as I can see, this works as expected and `Astro.site`, canonical URLs and the sitemap all use the value of `buildOptions.site` provided by the integration.

However, on `astro build`, `buildOptions.site` is checked _before_ the integration has a chance to run and a user is told to set the value even though it is set by the time the build actually starts. Building using the above integration shows the execution order:

```
$ astro build --experimental-integrations
[config] Set "buildOptions.site" to generate correct canonical URLs and sitemap
[build] Initial setup...
UPDATING CONFIG!
...
```

This isn’t super serious, but it would probably best to move that config check to _after_ the `astro:config:setup` hook has run.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-muzm7x?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
This error message is no longer reported, so I believe that we can mark this as fixed. Thanks for filing!
