### ISSUE TITLE
🐛 BUG: Pages are showing `[object Object]` in legacy build

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#2916]
### What version of `astro` are you using?

0.25.2

### What package manager are you using?

pnpm

### What operating system are you using?

Zorin OS (Ubuntu)

### Describe the Bug

All the pages are being built successfully but showing `[object Object]` in the legacy build both in dev and build.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-h16pve?file=.stackblitzrc

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm not sure if we're going to be supporting any fixes for `legacyBuild` at this point. We'll have to chat as a team and decide.

**Comment by RafidMuhymin** [comment]
@natemoo-re Will `legacyBuild` be removed completely in `v1.0`?

**Comment by FredKSchott** [comment]
Legacy build has been removed in v0.26.0. If you still need legacy build, you should stay on `v0.25.x` until you are able to migrate. You can read our full migration guide here: https://docs.astro.build/en/migrate/
