### ISSUE TITLE
🐛 BUG: No hot reload with postcss-import

### ISSUE THREAD

**Issue by DaNiels89** [withastro/astro#2917]
### What version of `astro` are you using?

0.25.2

### What package manager are you using?

npm

### What operating system are you using?

Windows - WSL Ubuntu 20.04

### Describe the Bug

I've been setting up postcss-import. At the moment hot reloading isn't working. In the terminal it says it has reloaded and the global.css is updated. The CSS change only shows up after a hard refresh of the browser.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/DaNiels89/astro-starter

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by DaNiels89** [comment]
Locally:

- npm start
- Made a CSS change in typography.css (file is imported in src/styles/global.css, and then updated in public/styles/global.css)

Got these results locally:
04:43:28 PM [astro] reload /src/styles/base/typography.css
04:43:28 PM [astro] reload /public/styles/global.css

**Comment by FredKSchott** [comment]
Fixed in v1.0.0-beta!
