### ISSUE TITLE
🐛 BUG: JSX camel cased attributes do not map to kebab cased counter parts

### ISSUE THREAD

**Issue by clhenrick** [withastro/astro#2922]
### What version of `astro` are you using?

0.23.0-next.10

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When setting attributes on elements with Astro's component JSX I'm seeing that attributes that in vanilla HTML are written using a hyphen such as `aria-hidden` are not expanding correctly when passing them as their JSX camel-cased counter part e.g. `ariaHidden`. Instead I'm seeing that the result in the DOM is `ariahidden` which isn't a valid attribute. 

This happens when I create a props object and spread it on the element, for example:

```jsx
---
  const props = {
    ariaExpanded: true,
    ariaControls: true,
  };
---

<button {...props}>Hello Astro</button>
```

When inspecting the DOM using dev tools, the attributes on the `<button>` element are `ariaexpanded` and `ariacontrols`. They should be `aria-expanded` and `aria-controls`.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/vigilant-booth-tnhf4s?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ryanfitzer** [comment]
Astro uses `dash-case` attributes: https://docs.astro.build/en/comparing-astro-vs-other-tools/#astro-vs-jsx

**Comment by clhenrick** [comment]
@ryanfitzer thanks for clarifying, oversight on my part. 

Slightly confusing that this is different than JSX syntax in other frameworks.
