### ISSUE TITLE
🐛 BUG: TypeError in solid.js preset when using client:only="solid"

### ISSUE THREAD

**Issue by hangtwenty** [withastro/astro#2928]
### What version of `astro` are you using?

0.25.4

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

The error I'm seeing is similar to https://github.com/withastro/astro/issues/2336 [fixed] but from a slightly different cause. 

1. When using `npm init astro` and choosing solid, it initially works.
2. Changing `client:visible` to `client:only="solid"` results in this error:

```
dev.js:222 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'completed')
    at hydrate$1 (dev.js:222:44)
    at hydrate (dev.js:505:10)
    at client.js:13:2
    at (index):14:39
    at onLoad (only.js:19:5)
```

This is in contrast to [a working example of `client:only="svelte"`](https://github.com/driftcatcher/astro-svelte-localstorage-example).

<details><summary>For convenience, here is the generated code around dev.js:222</summary>

```
function hydrate$1(code, element, options = {}) {
  sharedConfig.completed = globalThis._$HY.completed;  // ← Line where it errors
  sharedConfig.events = globalThis._$HY.events;
  sharedConfig.load = globalThis._$HY.load;
  sharedConfig.gather = root => gatherHydratable(element, root);
  sharedConfig.registry = new Map();
  sharedConfig.context = {
    id: options.renderId || "",
    count: 0
  };
  gatherHydratable(element, options.renderId);
  const dispose = render(code, element, [...element.childNodes]);
  sharedConfig.context = null;
  return dispose;
}
```

</details>
  

<details><summary>Dependency versions</summary>

```json
  "devDependencies": {
    "@astrojs/solid-js": "^0.0.3",
    "astro": "^0.25.4"
  },
  "dependencies": {
    "solid-js": "^1.3.13"
  }
```

</details>

### Link to Minimal Reproducible Example

https://github.com/driftcatcher/astro-solid-bug

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You need to use `client:only="solid-js"` instead of `client:only="solid"`.
