### ISSUE TITLE
🐛 BUG: example-apline doesn't work in stackblitz on firefox due to a CORS error

### ISSUE THREAD

**Issue by remcodekker** [withastro/astro#2929]
### What version of `astro` are you using?

0.25.4

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When opening https://astro.new/framework-alpine in Firefox (98.0.2) a stackblitz environment is started loading/building the example project.

in Firefox the example doesn't work due to a CORS error while trying to load alpinejs

> The resource at “https://unpkg.com/alpinejs?t=1648548070446” was blocked due to its Cross-Origin-Resource-Policy header (or lack thereof). See https://developer.mozilla.org/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)#

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-y3ewc3-jmkflm?file=src%2Fpages%2Findex.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Ah. Simply adding `crossorigin` fixes this issue? Feel free to open a PR if so!
