### ISSUE TITLE
🐛 BUG: astro's compiler struggles when using `slot` attribute outside of custom components

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/astro#2933]
### What version of `astro` are you using?

0.25.4

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When using [slots](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot) outside of custom components compiler goes into ashes

The exemple below is getting `UnhandledPromiseRejectionWarning: Error: EBADF: bad file descriptor, write`
i also gotten `panic: Element with a slot='...' attribute must be a child of a component or a descendant of a custom element` on my machine

may causes issues when trying an implementation of many [OpenUI](https://open-ui.org/)'s components like [\<selectmenu\/\>](https://open-ui.org/components/select)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xow7rt?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Yep, this is a pain! This is something I've been hoping to fix for a while—I have a few ideas on how we could address this with minimal disruption.

**Comment by natemoo-re** [comment]
Update: we'll have to chat about the best way forward here as a team! But it's a high priority to have an officially documented way to do this.

My initial suggestion would be borrowing our existing `is:inline` syntax (which applies to `script` or `style`) for native `slot`. Not entirely ergonomic, but better than silently changing behavior. 

There's a workaround mentioned in https://github.com/withastro/astro/issues/2509, but I'll keep this as the issue to track this.

**Comment by natemoo-re** [comment]
This particular issue was fixed in https://github.com/withastro/compiler/pull/442 and works in the latest release candidate. https://stackblitz.com/edit/github-xow7rt-yogycs?file=src%2Fpages%2Findex.astro&on=stackblitz.

There are still cases where `slot` doesn't work like everyone expects, so I'll leave this open until those are addressed.

**Comment by matthewp** [comment]
No longer a problem in latest! https://stackblitz.com/edit/github-xow7rt-6mb2ic?file=package.json&on=stackblitz

Please open a new issue if you have further problems.
