### ISSUE TITLE
🐛 BUG: Adding a named slot in the <head /> removes any body class

### ISSUE THREAD

**Issue by grantholle** [withastro/astro#2951]
### What version of `astro` are you using?

0.25.4

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Inside of a layout, if I include a named slot in my `<head />`, any classes set on the body get removed in the resulting html. Removing the named slot will result in the classes being included.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6ktqjg?file=src/layouts/BaseLayout.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Likely related to #2904 as well
