### ISSUE TITLE
🐛 BUG: 0.26.0 needs `publicDir` declaration

### ISSUE THREAD

**Issue by brycewray** [withastro/astro#2972]
### What version of `astro` are you using?

0.26.0

### What package manager are you using?

npm

### What operating system are you using?

macOS 12.3.1

### Describe the Bug

If `publicDir` is not set in `astro.config.mjs`, Astro doesn’t use the default setting of `./publicDir` — and, as a result, produces 404 errors for any content in the `publicDir` directory. Only if `  publicDir: './publicDir',` is set will `./publicDir` be recognized as the static assets directory.

Repo where demonstrated:  https://github.com/brycewray/astro-site (URL for result is https://astro-site-vercel.vercel.app/). In the repo, I have commented out the `publicDir` line so you can see that many 404s appear in the browser Inspector.

### Link to Minimal Reproducible Example

https://astro-site-vercel.vercel.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Looks like this is actually a mismatch between the docs and `Astro` global type definition, `./public` is actually the default for the `publicDir` config

The [blog-multiple-authors](https://github.com/withastro/astro/tree/main/examples/blog-multiple-authors) example starter shows this working properly, blog post images are kept in `public/images` and the blog posts load them fine without the `publicDir` config included

For reference, [here's](https://github.com/withastro/astro/blob/1335797903a57716e9a02b0ffd8ca636b3883c62/packages/astro/src/core/config.ts#L72) where the `publicDir` config option is defaulted to `./public` (not the `./publicDir` shown in the docs and typescript definition)

**Comment by brycewray** [comment]
> Looks like this is actually a mismatch between the docs and `Astro` global type definition, `./public` is actually the default for the `publicDir` config

@tony-sull Interesting. I wonder if the same might be true for the `outDir` setting; because, after reading your reply, I realized I forgot to change that setting on the host, which means the host still built to, and then rendered from, a top-level `/dist` directory as usual.

**Comment by tony-sull** [comment]
Great catch!  I just fixed the doc for `outDir` in #2973 as well
