### ISSUE TITLE
🐛 BUG: `hoist` still needed for node_modules-imports

### ISSUE THREAD

**Issue by herteleo** [withastro/astro#2980]
### What version of `astro` are you using?

0.26.1

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Scripts with imports from node_modules still need the `hoist` attribute. Otherwise there will be the console error

```
Uncaught TypeError: Failed to resolve module specifier "xxxx". Relative references must start with either "/", "./", or "../".
```

If you add the `hoist` attribute to the reproducible example it will work as expected.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-j2wmnz-ijodmh?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
The `type` attribute must be omitted to get default hoist behavior.
