### ISSUE TITLE
🐛 BUG:  Integration Components (Vue, React) are breaking the build

### ISSUE THREAD

**Issue by SebasG22** [withastro/astro#2993]
### What version of `astro` are you using?

1.0.0-beta.1

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Previously, the components from multiple integrations were working when you loaded from a markdown file.

Currently, this is broken. Please check the demo and see the basic example.

The dev command works as expected, but when you try to generate a build : 

```bash
src/pages/index.astro
 error   Cannot find the built path for /src/components/Counter.vue
    at Object.resolve (file:///home/projects/github-vfva4n/node_modules/astro/dist/core/build/generate.js:149:15)
    at generateHydrateScript (file:///home/projects/github-vfva4n/dist/entry.mjs:163:165)
    at Module.renderComponent (file:///home/projects/github-vfva4n/dist/entry.mjs:513:28)
    at async _render (file:///home/projects/github-vfva4n/dist/entry.mjs:331:11)
    at async renderAstroComponent (file:///home/projects/github-vfva4n/dist/entry.mjs?time=1649123692518:649:20)
    at async renderToString (file:///home/projects/github-vfva4n/dist/entry.mjs?time=1649123692518:613:18)
    at async renderComponent (file:///home/projects/github-vfva4n/dist/entry.mjs?time=1649123692518:412:20)
    at async _render (file:///home/projects/github-vfva4n/dist/entry.mjs?time=1649123692518:331:11)
    at async renderAstroComponent (file:///home/projects/github-vfva4n/node_modules/astro/dist/runtime/server/index.js:428:20)
    at async Module.renderPage (file:///home/projects/github-vfva4n/node_modules/astro/dist/runtime/server/index.js:372:22)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vfva4n?file=src/data/demo.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SebasG22** [comment]
@FredKSchott I think this is related to the refactor under the Markdown API

**Comment by SlicedSilver** [comment]
This may fix the issue for you.

Within the `src/pages/index.astro` file, try changing the way that the markdown content is imported.
Replace this:
```javascript
const data = await Astro.glob('../data/demo.md');
const Content = data[0].Content;
```
with this:
```javascript
import Content from '../data/demo.md?content';
```

I don't think that the `?content` import implementation is on the Astro document site yet, I found it within this RFCS proposal: 
https://github.com/withastro/rfcs/blob/main/proposals/0017-markdown-content-redesign.md

Linked from the Migration guide:
https://docs.astro.build/en/migrate/#new-markdown-api

**Comment by songololo** [comment]
Is there a simple way to load the markdown file's content (without rendering to component) via the new API?

**Comment by SlicedSilver** [comment]
> Is there a simple way to load the file's raw content (without rendering to component) via the new API?

You can use the `?raw` query string at the end of the import statement. For example:
```javascript
import democontents from '../data/demo.md?raw'
```

That will give you the exact file contents as a string.

It's a feature of ViteJS:
https://vitejs.dev/guide/features.html#static-assets

**Comment by SebasG22** [comment]
> This may fix the issue for you.
> 
> Within the `src/pages/index.astro` file, try changing the way that the markdown content is imported. Replace this:
> 
> ```js
> const data = await Astro.glob('../data/demo.md');
> const Content = data[0].Content;
> ```
> 
> with this:
> 
> ```js
> import Content from '../data/demo.md?content';
> ```
> 
> I don't think that the `?content` import implementation is on the Astro document site yet, I found it within this RFCS proposal: https://github.com/withastro/rfcs/blob/main/proposals/0017-markdown-content-redesign.md
> 
> Linked from the Migration guide: https://docs.astro.build/en/migrate/#new-markdown-api

I confirm that this works but this does not solve the issue in reality.
For example, In scenarios like a blog post when you load all the posts in `md` using a regex expression:  `/data/**/*.md` this will not do the trick.

**Comment by WebDevSimplified** [comment]
Are there any updates on this issue? I am running into this same issue (using Preact components) on the latest beta version (v1.0.0-beta.18). If I have a markdown file that imports a Preact component that is set to run on the client with something like `client:load` it will fail when I try to build the site, but development will work perfectly fine. If I do not have the component set to run on the client by leaving off `client:load` it will work. Also, markdown files that contain Astro components still work fine. In an effort to pair down this error I removed all the dynamic code from my Preact component and even then with just static HTML being exported from the component it fails to build.

Here is a minimal demo example: https://stackblitz.com/edit/github-bgnlni?file=.stackblitzrc

Here is the error message
```
generating static routes 
▶ src/pages/index.astro
  └─ /index.html (+20ms)
▶ src/pages/[date]/[blog].astro
 error   Cannot find the built path for /src/blogComponents/useTransition/UseTransition.jsx
    at Object.resolve (file:///F:/Web-Dev-Simplified/business-code/blog/node_modules/astro/dist/core/build/generate.js:136:15)
    at Module.generateHydrateScript (/node_modules/astro/dist/runtime/server/hydration.js:61:165)
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/index.js:226:27)](https://stackblitz.com/edit/github-bgnlni?file=.stackblitzrc)
```

**Comment by matthewp** [comment]
Thanks everyone! Closing as a duplicate, don't worry, this is a very important issue that we are going to fix soon. #3134
