### ISSUE TITLE
🐛 BUG: Custom 404 not rendered

### ISSUE THREAD

**Issue by idrakimuhamad** [withastro/astro#2998]
### What version of `astro` are you using?

1.0.0-beta.2

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I've created a custom 404 page under `src/pages/404.astro`. When I visited some random link, it will show the default Astro's 404 page instead of my custom page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mmsbbb-puzicp?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
(likely related) it looks like the 404 and `src/pages/[slug].astro` aren't working properly together in dev

[Discord discussion](https://discord.com/channels/830184174198718474/961300009863766097)

**Comment by rnwolf** [comment]
The 404 pages work when I publish site to Cloudflare but not when I use `npm run dev` or `npm run preview` for local testing.

**Comment by FredKSchott** [comment]
Closed by #3331
