### ISSUE TITLE
🐛 BUG: Custom Syntax Highlighter crashes compiler

### ISSUE THREAD

**Issue by naiyerasif** [withastro/astro#3012]
### What version of `astro` are you using?

1.0.0-beta.4

### What package manager are you using?

npm

### What operating system are you using?

Linux, Windows

### Describe the Bug

I am trying to use a custom Shiki renderer through a Remark plugin as follows.

```js
import { defineConfig } from 'astro/config';
import preact from '@astrojs/preact';
import remarkShiki from './src/plugin/remark-shiki.mjs'

// https://astro.build/config
export default defineConfig({
	integrations: [preact()],
	markdown: {
		syntaxHighlight: false,
		remarkPlugins: [
			'remark-gfm',
			'remark-smartypants',
			remarkShiki
		],
		rehypePlugins: [
			'rehype-slug'
		]
	}
});
```

This mostly works but crashes the Astro compiler when it encounters String-interpolation like tokens in codefences (e.g., `${encoding}`) with an error printed as follows.

```log
encoding is not defined
ReferenceError: encoding is not defined
    at default (/home/projects/github-rkwfya/src/pages/posts/index.md:23:165)
    at _render (/node_modules/astro/dist/runtime/server/index.js:49:20)
    at async Module.renderSlot (/node_modules/astro/dist/runtime/server/index.js:89:12)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rkwfya?file=src%2Fpages%2Fposts%2Findex.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
@natemoo-re will probably need to dig into this.

**Comment by JuanM04** [comment]
This is intended behavior. To prevent Astro from using template directives, use [`is:raw`](https://docs.astro.build/en/reference/directives-reference/#israw):

```diff
- return shiki.renderToHtml(lines, htmlRendererOptions)
+ return shiki.renderToHtml(lines, htmlRendererOptions).replace('<pre class="shiki"', '<pre is:raw class="shiki"');
```
