### ISSUE TITLE
🐛 BUG: client:only is broken when component used more than once

### ISSUE THREAD

**Issue by LorenzoLeonardini** [withastro/astro#3017]
### What version of `astro` are you using?

0.26.1

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

This bug had already been fixed previously: #2725
However, since at least version `0.25.1` (haven't tested older versions) and with the current version `0.26.1` this came back.
Some new piece of information: `dev` is broken, `build` crashes and skips page generation

The original bug report is copied below:

> Note: this bug report uses Svelte components because that's the only framework I know, feel free to test with React and friends and compare the results.
> 
> **Bug description**
> If I import a component and use it more than once in a page, specifying `client:only`, only the last instance of the component gets added to the page. Also, the site **refuses to build**
> 
> **The setup**
> A simple `Test` component with a `content` prop, it renders "content" into an `<h1>`. You would expect to be able to do something like
> ```html
> <Test content='Test 1' client:only />
> <Test content='Test 2' client:only />
> <Test content='Test 3' client:only />
> ```
> and have all the titles show up in the page, but only the last one gets added.
> 
> If you don't specify `client:only` all three of them get added.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nejdnv-ujxmej?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by naiyerasif** [comment]
I can confirm that this happens with Vue as well. I have a `Tag` component which when used multiple times causes this issue.

**Comment by natemoo-re** [comment]
I'm looking into this now! Surprisingly, it seems to be an issue with our compiler.
