### ISSUE TITLE
🐛 BUG: `Astro.request.headers.get('cookie')` always null

### ISSUE THREAD

**Issue by thepassle** [withastro/astro#3018]
### What version of `astro` are you using?

1.0.0-beta.2

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

In my `index.astro` I have a google sign in button, that redirects to my `auth/success` POST handler. In that POST handler, I verify the JWT token, set it as a cookie, and redirect the user back, like so:

```js
export async function post(_, req) {
  // verify token etc, omitted for brevity
  const headers = new Headers();
  
  headers.append('Set-Cookie', `jwt=${token}; Path=/; HttpOnly`);
  headers.append('Location', '/');

  return new Response('', {
    status: 302,
    headers,
  });
}
```

In the browser I can see that the cookie is indeed set, and I also see it in the network tab in the request:

<img width="290" alt="Screenshot 2022-04-07 at 14 17 13" src="https://user-images.githubusercontent.com/17054057/162198013-180c4864-4b3f-4d7b-b563-b839a4a746b1.png">

<img width="778" alt="Screenshot 2022-04-07 at 14 18 12" src="https://user-images.githubusercontent.com/17054057/162198027-531c9d48-3b75-44bb-ad6a-36b150b4cb0f.png">

 In my `index.astro`, I want to check for the presence of the cookie, but the `Astro.request.headers.get('cookie');` is always null, and `Astro.request.headers` is always an empty object. Am I missing something? Shouldnt I be able to access the cookie here?

e.g.:
```astro
---
const cookie = Astro.request.headers.get('cookie');
console.log(cookie); // null
console.log(Astro.request.headers); // {}
---
<html lang="en">
<!-- etc -->
</html>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-s3uktf?file=src/pages/auth/success.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Tc-001** [comment]
Here is a smaller, distilled script with the same issue.
The response body should contain the header, but are instead null
```js
// any .js page
export async function get(_, req) {
  const headers = new Headers();
  headers.append('Set-Cookie', `jwt=test123; Path=*; HttpOnly`);
  return new Response(JSON.stringify(req.headers.entries()), {
    headers,
  });
}
```

**Comment by matthewp** [comment]
Very interesting, will take a look + fix!

**Comment by matthewp** [comment]
I'm able to recreate in a test, working on fix.

**Comment by matthewp** [comment]
Talked about this in Discord and the adapter wasn't set. We might want to give some warnings when an adapter is not set and headers are attempted to be accessed though.

**Comment by Tc-001** [comment]
I would still expect it to work in dev mode without any adapters, but not the end of the world if there is a warning instead.

**Comment by matthewp** [comment]
@Tc-001 The reason is to prevent dev/prod differences. It's still possible we could adjust this requirement if enough users run into it. We have seen a few.  But also wonder if better messaging will help with the problem, so going to try that route first.

**Comment by Tc-001** [comment]
Fair, so maybe a warning is the best.
Thanks for the quick response!
