### ISSUE TITLE
🐛 BUG: Problems with importing Astro Components from NPM

### ISSUE THREAD

**Issue by aFuzzyBear** [withastro/astro#3019]
### What version of `astro` are you using?

latest

### What package manager are you using?

npm

### What operating system are you using?

wsl2; ubuntu 20.04, reproduced on stackblitz

### Describe the Bug

Component authors, have been experiencing new problems importing their components from NPM registry since the recent launch of `1.0-beta` 

This seems to be an SSR related issue where we are receiving the following errors:

```bash
File URL host must be "localhost" or empty on linux
File URL host must be "localhost" or empty on linux
File URL host must be "localhost" or empty on linux
12:39:01 PM [vite] Error when evaluating SSR module /node_modules/astro-stylesheet/Manager.astro:
TypeError [ERR_INVALID_FILE_URL_HOST]: File URL host must be "localhost" or empty on linux
```

This can be recreated by importing `astro-stylesheet` or `astro-imagetools` from npm into the project and simply encounter the error by `import * from 'astro-**'`

The following commands engages this behaviour:

```
import Stylesheet from "astro-stylesheet"
import { Stylesheet } from "astro-stylesheet"
```
But this doesnt

```
import Stylesheet from "astro-stylesheet/stylesheet"
```

If the problem is within the package.json of these components please do advise of the correct way that `exports` should be defined, 

I hope that this issue can be expedited with a resolution, as its hampering the publication of components at the present moment.

Kindest Regards

Your favorite bear

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rxhc1h?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by littleninja** [comment]
Was seeing the same error, `File URL host must be "localhost" or empty on darwin`. I'm consistently reproducing it when I add `layout` to my Markdown front matter. I needed to restart the dev server between each change, adding and removing the layout.

```markdown
// src/pages/posts/hello-world.md
---
layout: ~/layouts/PostLayout.astro // also tried ../../layouts/PostLayout.astro
title: Hello World
date: 2021-12-29T22:04:07-08:00
draft: false
tags: ['hello', 'world']
---

For a long time...
```

**Comment by tony-sull** [comment]
@aFuzzyBear I _think_ this is taken care of now, but want to double check with you before closing!

I ran the reproduction locally and updated to the latest Astro beta, I also had to update the import statement in `index.astro` to the line below - "Openprops" needed to match the `package.json` so the astro component could be found

```js
import OpenProps from "astro-stylesheet/Openprops"
```

**Comment by aFuzzyBear** [comment]
hey Tony, thanks for taking a look at, I'll double check and get back to you about this dude, 😀 
hope your enjoying the bug bashing

**Comment by DaveOrDead** [comment]
> I can build locally, but when I'm running a build on Netlify I get this error [...] File URL host must be "localhost" or empty on linux
I came across this when deploying to AWS as well. It turned out to be a casing issue. I was developing on Mac which is more forgiving than Linux when it comes to casing.
I was trying to do:
```
import Icon from '../components/icon/Icon.astro';
```
which built on Mac even though the location was actually `/Icon/Icon.astro` not `icon/Icon.astro`. When deploying to a Linux environment it will break the build in this case.

In your case if you're doing
```
import Layout from '../components/layout.astro';
```
it might be that your component name starts with a capital and should be
```
import Layout from '../components/Layout.astro';
```
Might help someone else :)
