### ISSUE TITLE
🐛 BUG: Open in stackblitz button not working for blog-multiple-authors example

### ISSUE THREAD

**Issue by jcha0713** [withastro/astro#3027]
### What version of `astro` are you using?

1.0.0-beta.4

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Clicking on 'Open in StackBlitz' button on astro.new page gives me an error and does not open. I checked the other links and it works well with CodeSandbox and Gitpod. I've also tested on my local machine and it gives me no error. 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/blog-multiple-authors

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lostra01** [comment]
On MacOS Monterey @ 12.0.1 cannot reproduce.

M1 Mac Mini

Tested on:

FireFox @100
Vivaldi @5.1.2567.66
Safari @15.1

Each browser opens up the Blog (Complex) [blog-multiple-authors] fine from astro.new

**Comment by jcha0713** [comment]
I was using Brave and it seems like it works again now. Weird, but good that I can now use it. Thanks for checking!
