### ISSUE TITLE
🐛 BUG: Lit Hydration Failing to set property values.

### ISSUE THREAD

**Issue by woutervroege** [withastro/astro#3035]
### What version of `astro` are you using?

1.0.0-beta.5

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Been playing with Astro+Lit, blowing my mind guys!
One serious issue (bug?) though.
While hydration works fine up until the initial render (declaratie shadow root is parsed and stamped correctly), the (reactive) property values are not set. This leads to incorrect (incomplete) state in consecutive renders.

## my-element.js

```import { LitElement, html } from 'lit';

export const tagName = 'my-element';

class MyElement extends LitElement {

  static get properties() {
    return {
      name: {
        type: String,
      }
    }
  }

  render() {
    return html` <p>Hello ${this.name}</p> `;
  }
}

window.customElements.define(tagName, MyElement);
```

## index.astro

```
---
import '../../components/my-element.js';
const name = 'John';
---
<html>
	<body>
	<my-element
		name={name}
		client:load 
	></my-element>
	</body>
</html>
```

## Result
- `myElement.shadowRoot.querySelector('p').textContent` equals 'Hello John' ✅
- `myElement.name` equals `undefined` (should be John) 🐛

## Additional Notes
- Setting `reflect: true` on the lit `name` prop solves the issue (but is not a real fix as you don't want every prop to be reflected to the dom.
- Another workaround would be to be able to set the attribute rather than the property in the astro template, but I didn't find a way to achieve this.

### Link to Minimal Reproducible Example

https://we.tl/t-pWnDopPfHn

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by woutervroege** [comment]
@matthewp See a fork of the lit demo in stackblitz: https://stackblitz.com/edit/github-m9zemz?file=src%2Fpages%2Findex.astro&on=stackblitz

As you can see, the initial render is correct (count=1), but the `count` prop value of `<my-counter>` is still 0 (constructor default value).

Is this astro or an lit ssr issue?

**Comment by matthewp** [comment]
Hey @woutervroege, nope this is working as intended. If you want to reflect from the rendered attribute you can add `reflect: true` to the property defininition:

```js
      count: {
        reflect: true,
        type: Number,
      },
```

Tested in your example and this works!

**Comment by woutervroege** [comment]
@matthewp This is definitely a bug, not intended.
reflect=true means that the element sets the corresponding attribute when setting the property. This is unrelated to the fact that the property should be set.
Please see the lit docs for further info on this.

I strongly suggest reopening this issue. I am wiling to investigate this further.
