### ISSUE TITLE
🐛 BUG: `base` configuration option doesn't work

### ISSUE THREAD

**Issue by JLarky** [withastro/astro#3040]
### What version of `astro` are you using?

1.0.0-beta.5

### What package manager are you using?

yarn, npm

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to figure out what is the point of `base` configuration option :) My expectation is based on `basePath` from next.js.

My use case is that I want to host my blog on /blog using reverse proxy/rewrite rules. So my blog is hosted on `blog.com/blog` and is proxied into `web.site/blog` and all the assets/css/js resources need to be hosted in `/blog` otherwise my `web.site/blog` will try to include `web.site/entry.30c7b9c44.js` instead of `web.site/blog/entry.30c7b9c44.js`

So here's an example I created: https://stackblitz.com/edit/github-cmdjpm?file=astro.config.mjs It builds SSG folder and serves it with `serve`.
You can see that in `dist` everything is right in the root and if you look into `index.html` all the imports are done from `/styles`, `/entry[...].js` and so on. So understandably none of that stuff is going to actually work in my use case.
Now even if I move data from `dist` to `dist/path/to/stuff` with `outDir` it will still not fix the problem with absolute imports in HTML file itself.

Here's example of next.js: https://stackblitz.com/edit/nextjs-erxnn7?file=next.config.js if I use `basePath: '/path/to/stuff'` so it will serve everything from `/path/to/stuff/_next`

I tested this with both SSG and SSR using netlify adapter. The same deal :) apart from superficial `twitter` and `og` stuff I don't see this option doing much :)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cmdjpm?file=astro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Closing this to use the #2409 as the primary since it's the oldest issue related to `base` begin ignored in `astro build` :+1:
