### ISSUE TITLE
🐛 BUG: `this` being modified to `globalThis` within XElement code

### ISSUE THREAD

**Issue by aFuzzyBear** [withastro/astro#3052]
### What version of `astro` are you using?

1.0.0.beta.5

### What package manager are you using?

yarn

### What operating system are you using?

wsl2; ubuntu 20.04, reproduced on stackblitz

### Describe the Bug

I have noticed that with the recent beta releases (cant pin it down exactly) but I have noticed that Astro is somehow modifying the code that is generated by XElements, esbuild transform output, in such a way that is now rendering `XElement` obsolete. 

`this` is being replaced with `globalThis` whereas `this` is important to the function call of XElement, as it binds the function to the Element.

I have no Idea how this came about but can you please advise of a suitable fix to remedy this issue, 

The following is the `build` output that is being generated,

```jsx
(async function (e, s) {
  s = this,
  e = (await import (e.src)).default,
  ((i, t) =>{
    typeof t.theme_buttons > 'u' && (t.theme_buttons = [
    ]),
    t.theme_buttons.push(globalThis)
  }) (s, e),
  s.addEventListener('click', i=>{
    ((t, l) =>{
      l.theme_buttons.forEach(a=>{
        a.classList.remove('active')
      }),
      globalThis.classList.add('active'),
      [
        'dark',
        'light'
      ].forEach(a=>document.documentElement.classList.remove(`${ a }-theme`)),
      document.documentElement.classList.add(`${ globalThis.dataset.theme }-theme`),
      localStorage.setItem('theme', globalThis.dataset.theme)
    }) (i, e)
  }, {
    useCapture: !1
  })
}).call(this.previousSibling, this.remove() || this);
```

Note that all instances of `globalThis` within the scope of the method is a mutation of some sorts, as this is entirely new and unprecedented behaviour, 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rppmpv?file=src/comp/test.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
We should definitely chat about this one @aFuzzyBear! Not positive what's going on... possibly an `esbuild` issue?

**Comment by aFuzzyBear** [comment]
Id love that, thanks nate, im game whenever you are dude, 💚

**Comment by matthewp** [comment]
I don't think this is still doing that in beta.27. My guess is that it was an esbuild regression (or Vite). Code currently being transformed to:

```js
(async function(t,e){e=this,t=(await import(t.src)).default,console.log(e),((s,a)=>{console.log("EL!",s),typeof a.theme_buttons>"u"&&(a.theme_buttons=[]),a.theme_buttons.push(s)})(e,t),e.addEventListener("click",s=>{((a,c)=>{c.theme_buttons.forEach(o=>{o.classList.remove("active")}),e.classList.add("active"),["dark","light"].forEach(o=>document.documentElement.classList.remove(`${o}-theme`)),document.documentElement.classList.add(`${e.dataset.theme}-theme`),localStorage.setItem("theme",e.dataset.theme)})(s,t)},{useCapture:!1})}).call(this.previousSibling,this.remove()||this);
```

@aFuzzyBear can you retry and confirm?

**Comment by aFuzzyBear** [comment]
I will do dude,  I'll keep you posted,
