### ISSUE TITLE
🐛 BUG: Markdown-imported component styles do not get applied when `Astro.glob().Content` is used

### ISSUE THREAD

**Issue by Tc-001** [withastro/astro#3054]
### What version of `astro` are you using?

1.0.0-beta.5

### What package manager are you using?

yarn / pnpm

### What operating system are you using?

Linux

### Describe the Bug

1. Create a `src/markdowns/file.md` file with the following:
```md
---
setup: import Styled from "../components/StyledCompoent.astro"
---
<Styled></Styled>
```
2. Create a `src/components/StyledCompoent.astro` with the following
```astro
<h1> This should be red </h1>
<style>
  h1 {color:red;}
</style>
```
3. Replace `index.astro` with
```astro
---
	let pages = await Astro.glob("../markdowns/*.md")
---
<html lang="en">
	<head>
	</head>
	<body>
		{pages.map(page=> (
			<page.Content />
		))}
	</body>
</html>
```
4. `dev` or `build` the project

## Expected
There is a red `<h1>` component

## Actual
There is a black `<h1>` component

Adding the following line to the `index.astro` frontmatter
```js
import Styled from "../components/StyledCompoent.astro"
```
will side-effect import the styles, and I get the expected, red `<h1>`.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/pedantic-archimedes-p3k2n0?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Update: this affects styles loaded by _any_ components in `.md`, not just `.astro`. It also occurs for standard ESM imports like so:

```astro
---
import { Content } from '../markdowns/page.md'
---
```

☝️ We're planning to use this in our own starter example soon, so it's definitely worth fixing!
