### ISSUE TITLE
🐛 BUG: Werid behaviour with Astro.canonicalURL.pathname and Astro.canonicalURL.href with `/1` route?

### ISSUE THREAD

**Issue by Yofou** [withastro/astro#3058]
### What version of `astro` are you using?

^1.0.0-beta.5

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

# Video of display the bug
https://user-images.githubusercontent.com/39814328/162638244-1f845b8d-94ef-4f61-ae02-30f295c4c6b3.mp4

# TLDW
So when having numerical id routes like `/1`, `/2`, `/3` everything behaves as expected but `/1` which for some reason 
`Astro.canonicalURL.pathname` and `Astro.canonicalURL.href` as index page (`/`)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hadnau

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Thanks for including a simple reproduction here!

Looks like we have a couple bugs related to numeric route params, picking this up now to see if we can knock out this and [#3082](https://github.com/withastro/astro/issues/3082) at the same time :+1:

**Comment by tony-sull** [comment]
Confirmed this is still an issue in the latest beta release

I haven't tracked down where the routing inconsistency comes from yet, but we had an issue in non-SSR builds that was automatically removing `/1` for paginated routes, may be related to this as well
