### ISSUE TITLE
🐛 BUG: Svelte components aren't reloaded without `client` property

### ISSUE THREAD

**Issue by pyronaur** [withastro/astro#3069]
### What version of `astro` are you using?

1.0.0-beta.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When a Svelte component is added without `client` property, it loses hot-reloading behavior for both DOM changes, but more frustratingly - style changes.

It seems that the style changes don't take effect until a parent astro component is updated.

```astro
---
import Test from '../components/Test.svelte';
---

<Test />
``` 

## Reproducing

Go to the [Stackblitz example](https://stackblitz.com/edit/github-odctde?file=src/components/Test.svelte) and toggle font size on and off. Then go to `index.astro` turn on ` <Test client:load /> ` example. 

**Note** - To break or fix hot-reloading you'll need to restart astro dev server. So if you start out with `client:load` and then remove `client:load` - hot reloading is going to keep on working until the next restart.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-odctde?file=src/components/Test.svelte

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Looks like this is the same underlying issue as #3097, I should have a PR out today that makes sure the browser reloads when a server-only component is updated in `dev`

**Comment by natemoo-re** [comment]
This should be fixed in the most recent version! Please feel free to re-open if you're still having trouble with this.

**Comment by Kingkon963** [comment]
Hi, @natemoo-re 
Unfortunately, I'm facing this issue in the latest version. At `astro v1.9.1`

![image](https://user-images.githubusercontent.com/33956213/211032685-9581bed3-c871-4c9a-a93a-5c14b48dbddf.png)

The page reloads when I save the file but the latest change doesn't reflect on the browser until I restart the server again.
