### ISSUE TITLE
🐛 BUG: Shiki is highlighting the dynamic values of component props with white color

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#3075]
### What version of `astro` are you using?

1.0.0-beta.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Zorin OS

### Describe the Bug

Shiki is highlighting the dynamic values of component props with white color. They should be highlighted with the variant of blue that is used to highlight variables.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wnuztx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
Looks like this has been fixed!

<img width="793" alt="Screen Shot 2022-05-10 at 12 50 13 PM" src="https://user-images.githubusercontent.com/622227/167701124-97df1180-2fb0-498a-a3c6-28449958e290.png">
