### ISSUE TITLE
🐛 BUG: Official shiki theme not taken into account

### ISSUE THREAD

**Issue by kissu** [withastro/astro#3083]
### What version of `astro` are you using?

1.0.0-beta.5

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

tried all of 3

### What operating system are you using?

Linux + MacOS

### Describe the Bug

This question was initially asked [on Discord](https://discord.com/channels/830184174198718474/845451724738265138/961679446367174717).

I'll give the details here too:
- using this configuration in `astro.config.mjs` have no impact regarding the theme
```js
import { defineConfig } from 'astro/config';

export default defineConfig({
  markdown: {
    render: [
      {
        shikiConfig: {
          theme: 'monokai',
        },
      },
    ],
  },
})
```
- my goal is to be able to use any of the [official themes](https://github.com/shikijs/shiki/blob/main/docs/themes.md#all-themes) at first
- here is the code snippet I'm using for the highlight
<img width="599" alt="CleanShot 2022-04-11 at 02 05 47@2x" src="https://user-images.githubusercontent.com/5133074/162645777-e098e5a5-6ec7-4222-83d0-d15543847899.png">

This is supposed to be Monokai but it's not (I've tried a lot of them, none worked)
<img width="627" alt="CleanShot 2022-04-11 at 02 06 09@2x" src="https://user-images.githubusercontent.com/5133074/162645795-b4bcdc8f-dd58-4988-a2a1-a57c58974145.png">

I don't have any hints by inspecting the DOM (no `:root` CSS variables or alike).

I've followed [this documentation](https://docs.astro.build/en/guides/markdown-content/#shiki-configuration), I've [replaced `markdownOptions` by `markdown`](https://github.com/withastro/docs/pull/339) following the latest updates.

---
Here is [a codesandbox](https://codesandbox.io/s/github/kissu/astro-shiki-issue) and the [Github repo](https://github.com/kissu/astro-shiki-issue).

Am I missing something here or is it a bug?

### Link to Minimal Reproducible Example

https://codesandbox.io/s/github/kissu/astro-shiki-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
@kissu ah, our apologies! Our `markdown` config options have been simplified for the 1.0 beta launch, but our markdown docs haven't caught up yet. Here's the config you'll need:

```js
import { defineConfig } from 'astro/config';

export default defineConfig({
  markdown: {
    shikiConfig: {
      theme: 'monokai',
    },
  },
})
```

👆 You no longer need the `render: [...]` array for supplying these options. It looks like this resolves the issue in your sandbox, but lmk if you're still having trouble!

**Comment by bholmesdev** [comment]
Update: our docs actually _were_ updated! Find [the new syntax highlighting reference here](https://docs.astro.build/en/guides/markdown-content/#syntax-highlighting).

**Comment by kissu** [comment]
Yeah, the syntax was updated just after I was done looking at it. 😂
Thanks for the quick reply! ❤️ 

This works perfectly with `theme: 'monokai',`

![image](https://user-images.githubusercontent.com/5133074/164057943-9ec0ec9f-4b3e-4a63-86f7-953b5abf668d.png)
![image](https://user-images.githubusercontent.com/5133074/164058027-cfd97669-15c7-4c91-9dba-56c235fa7f88.png)
---
Meanwhile, when using the `<Code />` component, it tends to be a bit more tricky, for example this
![image](https://user-images.githubusercontent.com/5133074/164058155-0452045a-601e-4438-b362-664513971bf3.png)
Does render the following
![image](https://user-images.githubusercontent.com/5133074/164058229-ed34f32f-f9ac-4278-bc42-ca33442c8170.png)

Adding `theme="rose-pine-moon"` (or any other official theme) after `wrap` is working great but putting nothing fallback to some unkown theme (if any).

---
Also, setting up `theme: 'css-variables',` on top of some globally scoped variables like those
```css
:root {
  --shiki-color-text: #e1e000;
  --shiki-color-background: #3cc000;
  --shiki-token-constant: #40c0c0;
  --shiki-token-string: #e010e0;
  --shiki-token-comment: #4040c0;
  --shiki-token-keyword: #3030c0;
  --shiki-token-parameter: #a00000;
  --shiki-token-function: #1010c0;
  --shiki-token-string-expression: #5050a0;
  --shiki-token-punctuation: #900000;
  --shiki-token-link: #a03030;
}
```

Have no success into customizing the code with the 3 backticks (the `<Code />` is still stuck with it's default theme).

![image](https://user-images.githubusercontent.com/5133074/164059518-61459fd7-fd2d-4b0b-a286-27a1ecfa607a.png)

Should I suppose that customizing Shiki with variables is not possible yet?

**Comment by bholmesdev** [comment]
You'll need to use `--astro-code-token` instead of `--shiki-token` for your variable names! Noticed this from my personal debugging. Ik it's rather odd @kissu

**Comment by kissu** [comment]
Oh yeah right, works well like that! 🙏🏻
