### ISSUE TITLE
🐛 BUG: Astro.glob() only returns url for Markdown

### ISSUE THREAD

**Issue by leifniem** [withastro/astro#3084]
### What version of `astro` are you using?

1.0.0-beta.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

The switch from `fetchContent` to `glob` allows for `.astro` files to be loaded just the same as `.md`, yet only the latter includes a `url` property in it's results to link to.

I have not looked into the code for glob yet, but if i can figure it out i'd gladly open a PR myself.

Thanks in advance for all the great work you do with Astro :)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/upbeat-http-k8ifvm?file=/src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by leifniem** [comment]
Sounds good, because that was my only painpoint using Astro :)

**Comment by FredKSchott** [comment]
Talked with some core maintainers and @natemoo-re, and agreed that we could add the same handling to `.astro` pages that we have in the `.md` output:

```
export const file = ${JSON.stringify(fileId)};
export const url = ${JSON.stringify(fileUrl)};						
```

**Comment by fujohnwang** [comment]
When I glob with such pattern:

```astro
const posts = await Astro.glob("../**/*.md*");
```

only mdx file returned with `url` but md will not(which has only `file` attribute but no `url`), I am using starlight with astro:

```
    "@astrojs/starlight": "^0.21.0",
    "@astrojs/starlight-tailwind": "^2.0.1",
    "@astrojs/tailwind": "^5.1.0",
    "@zachleat/table-saw": "^1.0.6",
    "alpinejs": "^3.13.5",
    "astro": "^4.3.5",
```
