### ISSUE TITLE
🐛 BUG: React - Text content did not match. Server "test " Client: "test"

### ISSUE THREAD

**Issue by andreialecu** [withastro/astro#3086]
### What version of `astro` are you using?

1.0.0-beta.7

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When rendering any React component with Astro, I see this warning in dev mode in the Chrome console:

> Text content did not match. Server: "Unlock the game's full potential with our " Client: "Unlock the game's full potential with our"

The offending tsx looks like this:

```tsx
 <p>
Unlock the game's full potential with our{" "}
	  <a className="link" href="/#platform">
	    lorem ipsum
	  </a>
</p>
```

Notice the `{" "}`.

<img width="1110" alt="Screenshot 2022-04-12 at 10 10 22" src="https://user-images.githubusercontent.com/697707/162901732-0379c0d1-647a-40a0-a1fe-07a0ca2f3b11.png">

This seems to happen with other interpolations as well.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lk6zbc?file=src/components/Counter.jsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by andreialecu** [comment]
This is actually triggered in `react-dom` and this is a somewhat similar issue: https://github.com/facebook/react/issues/20697 but in that case it was an user error.

I believe astro is probably doing something wrong here as well, because I cannot reproduce it with react alone as per:

https://codesandbox.io/s/suspicious-brahmagupta-qx8shi?file=/src/index.js

**Comment by aFuzzyBear** [comment]
I would like to update for some further clarity, this appears to be an implementation issue with the `@astro/react` integration, with React 18 as the dep, 

See support thread for more information: https://discord.com/channels/830184174198718474/963057127260311572

**Comment by aFuzzyBear** [comment]
Thanks Ben
