### ISSUE TITLE
🐛 BUG: JSX components HMR not updating on save unless client:* directive is used.

### ISSUE THREAD

**Issue by davycoe** [withastro/astro#3097]
### What version of `astro` are you using?

1.0.0-beta.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

JSX components not updating on save unless client:* directive is used.

No HMR update:
```
<Heading />
```

HMR works:
```
<Heading client:load />
```

I assume when running dev this should work without using a client:* directive?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-bxkvt5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This _should_ have been fixed by https://github.com/withastro/astro/pull/3138, but please feel free to open a new issue if you're still running into HMR issues!
