### ISSUE TITLE
🐛 BUG: Static paths do not seem to work with src imports into Astro components. Relative paths do though.

### ISSUE THREAD

**Issue by JaymanMDev** [withastro/astro#3100]
### What version of `astro` are you using?

1.0.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

In development mode, static paths to javascript content do not seem to work. Relative paths work just fine.

### Link to Minimal Reproducible Example

https://github.com/JaymanMDev/astro-test-project

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
I opened your application and everything seems to be working correctly. Closing as most likely fixed in a recent release
