### ISSUE TITLE
🐛 BUG: Component used in Markdown errors on child content with brackets

### ISSUE THREAD

**Issue by kilbd** [withastro/astro#3112]
### What version of `astro` are you using?

1.0.0-beta.8

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

macOS Monterrey on an M1 Mac

### Describe the Bug

I'm trying to use a "wrapper" component in a Markdown page for code fences, where the code block is wrapped by the component and therefore should be inserted into the component's slot. It looks like this:

```md
    <Figure caption="Initializing a Variable">
    ```js
    let myVar = {test: true};
    ```
    </Figure>
```
Astro seems to be trying to render the code fence, and this causes an error if it contains curly braces. I'd like Astro to treat code fences as raw text or allow me to declare text as raw.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/wispy-mountain-4o0cgu?file=/src/pages/index.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
So according to the Commonmark spec, nesting Markdown _inside_ of HTML content requires an extra newline before the Markdown content.

The following should work. [See repro](https://stackblitz.com/edit/github-xsjakq?file=src%2Fcomponents%2FFigure.astro,src%2Fpages%2Findex.md).

```md
<Figure caption="Initializing a Variable">

```js
let myVar = {test: true};
```

</Figure>
```
