### ISSUE TITLE
🐛 BUG: Generated Assets do not consider base

### ISSUE THREAD

**Issue by Auroratide** [withastro/astro#3119]
### What version of `astro` are you using?

1.0.0-beta.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When `base` is provided in the configuration, Astro's build process does not use it when constructing `link`s for generated assets, such as extracted CSS. Instead, the URL is always root-relative starting with `/assets`:

```html
<link rel="stylesheet" href="/assets/asset.2cb5588a.css">
```

As an example, this affects deployment to Github Pages, where the site url is of the form `https://username.github.io/base-path`.

Looking around the codebase, I stumbled upon [createLinkStylesheetElement()](https://github.com/withastro/astro/blob/main/packages/astro/src/core/render/ssr-element.ts#L14), which takes as inputs the asset path and the site url, but not the base path. I believe this issue could be fixed by providing this information from the manifest, though I'm not 100% certain if this should apply to _all_ stylesheet files (my first time looking through the codebase 🙂).

### Link to Minimal Reproducible Example

https://github.com/Auroratide/astro-base-component-styles

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Auroratide** [comment]
Related: https://github.com/withastro/astro/issues/2751

**Comment by tony-sull** [comment]
Related to [#3040](https://github.com/withastro/astro/issues/3040) as well

**Comment by tony-sull** [comment]
Closing this to use the #2409 as the primary since it's the oldest issue related to `base` begin ignored in `astro build` :+1:

**Comment by johnchaffee** [comment]
I experienced this exact same problem. I have a base path (`base: "/foo",`)  in my config and when the static site is built, it includes the '/foo' path in the links to the posts (`href="/foo/posts/first-post"`) but the stylesheet references in the head do not include the '/foo' path (`href="/assets/asset.ede33789.css"`).
