### ISSUE TITLE
🐛 BUG: HMR broken for at least Solid and Lit

### ISSUE THREAD

**Issue by Jutanium** [withastro/astro#3124]
### What version of `astro` are you using?

1.0.0-beta.12

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

yarn

### What operating system are you using?

Mac, Linux

### Describe the Bug

([Support thread with @aFuzzyBear ](https://discord.com/channels/830184174198718474/964990885811093534))
When setting up a new project and adding Solid, the Vite dev server does not reflect changes to a Solid component unless the server is completely restarted.

Loading the project on Gitpod, it no longer worked at all, and I got this error:
```
Internal server error: Failed to resolve entry for package "/workspace/noteroll/". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "/workspace/noteroll/". The package may have incorrect main/module/exports specified in its package.json.
```

### Link to Minimal Reproducible Example

https://github.com/Jutanium/noteroll/commit/dd9dc00852b173bce52bc479aae3229cfc8e2241

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Jutanium** [comment]
Starting a new project using the "Starter Kit" template did work. This problem arose when using the Minimal template and `astro add solid`.

**Comment by Jutanium** [comment]
Update: I experience the issue with regular `.astro` components too - every so often the dev server goes haywire and refuses to update for changes made inside components (changes made inside pages still work) and I have to restart it.

**Comment by tony-sull** [comment]
I've been working on an [HMR fix](https://github.com/withastro/astro/pull/3118) related to the dev server ignoring framework component updates when `client:` directives aren't used (i.e. server-only components)

@Jutanium any chance you can share a reproduction for the issue you're hitting with Solid and Lit?

**Comment by natemoo-re** [comment]
We made a bunch of HMR fixes in https://github.com/withastro/astro/pull/3138, @Jutanium can you confirm if you're still hitting this?

**Comment by Jutanium** [comment]
@natemoo-re Fixed for me :) Thanks so much!
