### ISSUE TITLE
🐛 BUG: `Window` is not defined after using lit integration when deployed on netlify

### ISSUE THREAD

**Issue by thepassle** [withastro/astro#3126]
### What version of `astro` are you using?

1.0.0-beta.8

### Are you using an SSR adapter? If so, which one?

netlify

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

I added the `lit` integration to my project:
```diff
import { defineConfig } from 'astro/config';
+ import lit from '@astrojs/lit';
import netlify from '@astrojs/netlify';
import { vitePluginCommonjs } from 'vite-plugin-commonjs'

export default defineConfig({
  site: 'https://my-astro-course.netlify.app',
  adapter: netlify(),
+ integrations: [lit()],
  vite: {
    plugins: [
      vitePluginCommonjs()
    ]
  },
});
```

Which locally worked fine, but when deployed to netlify, gives me the following error:

<img width="775" alt="Screenshot 2022-04-17 at 09 37 13" src="https://user-images.githubusercontent.com/17054057/163705414-0cfdefbf-114c-4957-a5c2-5d44a4d16f29.png">

### Link to Minimal Reproducible Example

astro.new

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by thepassle** [comment]
Looks like the `@astrojs/netlify` adapter indeed excludes `window` and `document` from being polyfilled, but those are probably needed to SSR custom elements:

https://github.com/withastro/astro/blob/main/packages/integrations/netlify/src/netlify-functions.ts#L6-L8
```js
polyfill(globalThis, {
  exclude: 'window document',
});
```

Is there a particular reason `window` and `document` are excluded?

**Comment by thepassle** [comment]
Hrm thats weird, i was definitely getting that error after adding the lit integration. Ill try to update my dependencies and redeploy tomorrow to see if the problem is still there

**Comment by thepassle** [comment]
Yeah, this is definitely not working as expected

## Reproduction:

- `npm init astro@latest`
- `npm i -S lit @webcomponents/template-shadowroot @astrojs/lit @astrojs/netlify`
- Update `astro.config.mjs`:
```diff
import { defineConfig } from 'astro/config';
+ import netlify from '@astrojs/netlify';
+ import lit from '@astrojs/lit';

export default defineConfig({
+  integrations: [lit()],
+  adapter: netlify()
});
```

- Add a simple lit component to `src/pages/my-el.js`:
```js
import { LitElement, html } from 'lit';

export const tagName = 'my-element';

class MyElement extends LitElement {
  render() {
    return html` <p>Hello world! From my-element</p> `;
  }
}

customElements.define(tagName, MyElement);
```

- Import and use it in `index.astro`:
```diff
---
+ import './my-el.js';
---
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>Astro</title>
	</head>
	<body>
		<h1>Astro</h1>
+		<my-element></my-element>
	</body>
</html>
```

- Run `netlify deploy --prod`: https://astro-lit-netlify-repro.netlify.app/
<img width="824" alt="image" src="https://user-images.githubusercontent.com/17054057/164381788-eef089d0-2b97-48c4-ab7e-46fcd4adb73d.png">

Locally this does work:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/17054057/164381847-676a4512-3766-48ea-86be-fc82180ea655.png">

If I deploy it without the lit integration, it also works.

**Comment by thepassle** [comment]
Ok so I dug a little bit more and it seems like this is a problem in the build. E.g.: if I use a lit component, it imports litelement, which uses some browser apis (like for example some stuff on the window, document, etc). This gets shimmed by lit-ssr. My astro build output (with the netlify adapter) looks like:

![image](https://user-images.githubusercontent.com/17054057/164417674-fdc75f42-383e-41de-8c1c-cedde3127090.png)

However, the window shim only gets installed way later in the output bundle (see line nr):

![image](https://user-images.githubusercontent.com/17054057/164417773-e5bcc319-816e-4b45-b233-49a72b507974.png)

So when litelement gets imported at line 4, it'll try to use browser apis that have not been shimmed yet, because that only happens on line 877

You can reproduce this locally by cloning this repro, running the build, and looking at the `netlify/functions/entry.mjs`: https://github.com/thepassle/astro-lit-netlify-repro

A fix for this could be to somehow make sure the bundler loads the dom shim module first

**Comment by hippotastic** [comment]
Okay, so I've done a little testing myself as well, and the error seems to occur because the `netlify/functions/entry.mjs` file generated by `astro build` includes your import line coming from `src/pages/my-el.js`:
```js
import { LitElement, html } from 'lit';
```

As imports are processed before executing any other code in the `entry.mjs` file, the following happens:
1. `LitElement` from `lit` gets imported
2. As `LitElement` extends `ReactiveElement`, `@lit/reactive-element` gets imported
3. `@lit/reactive-element` imports the file `./css-tag.js` from its own package
4. `css-tag.js` attempts to access `window.ShadowRoot`, which causes the error you're seeing.

I believe that we could fix this error by exporting `server-shim.js` from the `@astrojs/lit` package and adding an `import '@astrojs/lit/server-shim.js'` statement to `netlify/functions/entry.mjs` during build BEFORE any of the imports contributed by components.

**Comment by thepassle** [comment]
I think the larger problem is that imports in your components (e.g. `src/components/my-element.js` get externalized in the final build. In the build output, this then leads to any imports you may use being placed as external imports at the top of the bundle, when the shim hasnt been applied yet. You can work around it by adding those imports to the `vite.ssr.noExternal` config, which then causes them to be bundled in the output, but maybe it would make more sense to bundle those imports by default as well?
