### ISSUE TITLE
🐛 BUG: changes to imported JavaScript are ignored

### ISSUE THREAD

**Issue by gustavopch** [withastro/astro#3131]
### What version of `astro` are you using?

1.0.0-beta.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

The reproducible example imports `import { x } from '../lib.js'` and renders`<h1>{x}</h1>`. Changing the value of `x` and saving should reload the page so the new value is rendered. Instead, the change is ignored.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-42qihx-gjkpau?file=src/lib.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Happy to report that this was fixed in https://github.com/withastro/astro/pull/3138 !

Take a look when using `astro@1.0.0-beta.16` https://stackblitz.com/edit/github-42qihx-c1dqr4?file=src%2Flib.js
