### ISSUE TITLE
🐛 BUG: Not work in browsers that do not support the Optional chaining operator.

### ISSUE THREAD

**Issue by diegoleme** [withastro/astro#3136]
### What version of `astro` are you using?

stro@1.0.0-beta.12 

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

The current version of astro does not work in [browsers that do not support the Optional chaining operator](https://caniuse.com/mdn-javascript_operators_optional_chaining). 

By default astro uses the `esnext` to target  vite configuration. https://github.com/withastro/astro/blob/0f071a9723961a9a53602744bf10207040d2daaf/packages/astro/src/core/build/static-build.ts#L218.

The value [default on vite](https://vitejs.dev/config/#build-target) is `modules`.

When target is `esnext`

```
a?.b
```

When target is `modules`

```
a==null?void 0:a.b
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-x8bff6

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
It works if you don't use optional chaining in your code 😀. Astro does not down-level your code, we just compile what you give us. Perhaps you think we *should* down-level your code and that's a valid want. If so, go through the RFC process: https://github.com/withastro/rfcs
