### ISSUE TITLE
🐛 BUG: Web Component `connectedCallback` updates cause issues when rendered with React

### ISSUE THREAD

**Issue by Enteleform** [withastro/astro#3155]
### What version of `astro` are you using?

1.0.0-beta.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

I'm running into these errors when programmatically updating Web Components that are rendered by React; and also have encountered the same issues with component libraries like MUI, which I assume are due to programmatic updates of some sort.

```
• Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
• Warning: An error occurred during hydration. The server HTML was replaced with client content in <astro-root>.
• Warning: Expected server HTML to contain a matching <some-component> in <astro-root>.
• Warning: Extra attributes from the server: someAttribute
```

Tried to troubleshoot via `client:only`, but was blocked by #3154.

Additional context @ [**Discord/#support-threads/enteleform(2022-04-20)**](https://discord.com/channels/830184174198718474/966277614056652831)

### Link to Minimal Reproducible Example

- [**index.astro:282-411**](https://codesandbox.io/s/astro-react-webcomponent-issue-37sw92?file=/src/pages/index.astro:282-411)
  - Some form of error occurs with all `client:*` variants.
- [**WebComponent_Wrapper.jsx:88-295**](https://codesandbox.io/s/astro-react-webcomponent-issue-37sw92?file=/src/components/WebComponent_Wrapper.jsx:88-295)
  - Issue occurs when with immediate updates.
  - Issue does not occur when updates are delayed.
### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I don't understand, this doesn't seem like a bug to me. React expects what is rendered by the component to match the initial DOM, and it doesn't because this element is mutating itself.

Here's the same thing happen with just normal React: https://stackblitz.com/edit/react-ts-6dbqsh?file=index.tsx

There are a couple of options:

1. Don't mutate yourself in connectedCallback.
2. Render this element using dangerouslySetInnerHTML which I believe will prevent diffing.

Either way, this is not an Astro issue, so closing.

**Comment by Enteleform** [comment]
@matthewp

Ok, I've never used `hydrateRoot` with React so I was unsure of how that was getting handled between Astro and React.

My next thought was that `client:only` might work for this, but then I ran into #3154. Am I correct in thinking that that should work for the reproduction scenario, given that the issue wasn't present?
