### ISSUE TITLE
🐛 BUG: External JS is overwritten/unloaded from page if component has client:load

### ISSUE THREAD

**Issue by varungupta3009** [withastro/astro#3184]
### What version of `astro` are you using?

1.0.0-beta.17

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Windows 11

### Describe the Bug

Styles and Logic applied by a script loaded using a script tag will unload or be overridden by styles or scripts in a component.
For ex: I'm using the GitHub `buttons.js` script to add GitHub buttons on by page that reside in a component. This component has `client:load` on it. The script correctly loads and styles the buttons for a quick fraction of a second before losing all the styles.

Tried various tags on `buttons.js`, even tried loading it both externally, internally, and inline. Nothing works.

PFA reproducible example.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-y4f6tm-hjx2sr?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I think this is expected? The Github Button script is applying styles and behavior to the buttons, but then Svelte is hydrating all children and wiping out any changes the Github Button script made.

If these buttons were rendered outside of a Svelte component, in a normal `.astro` file it should work just fine!
