### ISSUE TITLE
🐛 BUG:  Cannot find module AppData\Local\Temp\dlx-17728\5\node_modules\create-astro\create-astro.mjs

### ISSUE THREAD

**Issue by Rolanddoda** [withastro/astro#3193]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm, pnpm, nvm

### What operating system are you using?

Windows 11

### Describe the Bug

I just tried creating a new project running the command `npm create astro@latest`

![image](https://user-images.githubusercontent.com/18482346/164894610-aaa41826-cc49-4c78-8af9-01c0ebd07e0d.png)

Node and npm versions:

![image](https://user-images.githubusercontent.com/18482346/164894642-7f177af2-7b20-47b6-a2f4-3fcbb684f7b9.png)

### Link to Minimal Reproducible Example

no-link

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Rolanddoda** [comment]
`npm init astro` fails too

![image](https://user-images.githubusercontent.com/18482346/164894869-07f79d69-a7d6-41fa-bd63-0d65b30e6aa0.png)

**Comment by Rolanddoda** [comment]
I know that it might be hard to investigate what is going on without a "Minimal Reproducible Example" but just wanted to open the issue if others are facing this too.

**Personally I solved it by opening `Git bash` instead of the command line.**

If no one else faces the same, then I don't have any problem if it gets closed.

**Comment by FredKSchott** [comment]
Thanks @Rolanddoda! We'll keep an eye out for this, but this seems like an npm issue / our code hasn't even been run yet when you're seeing this issue. Hopefully `npm` can fix this!
