### ISSUE TITLE
🐛 BUG: `define:vars` not receiving variable

### ISSUE THREAD

**Issue by brycewray** [withastro/astro#3194]
### What version of `astro` are you using?

1.0.0-beta.17

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

I have followed the [instructions regarding using CSS variables with `define:vars`](https://docs.astro.build/en/guides/styling/#css-variables), but the variables’ values aren’t making it into the `style` — yet, I can add text within the HTML referencing the same variable and it appears. The following should work but, for now, doesn't.

In the code fence (and I have confirmed with the above procedure that `LQIP_b64` is defined):
```js
let imgBkgd = `url(data:image/jpeg;base64,${LQIP_b64})`
```

In the template section:
```html
<style define:vars={{ imgBkgd }}>
  .bkgdHandler {
    background: var(--imgBkgd);
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
  }
</style>
<div class={bkgdHandler}>
<!-- continues from here -->
```

. . . but, in the browser, this shows `imgBkgd` is undefined. I have tested a less complex variable by defining `noRepeat` and then using it in the `background-repeat` line of this `style`, and that one also didn't get to the `style`.

**Note**: in the minimal reproducible example, see the base `index.astro` file.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tapra2/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aFuzzyBear** [comment]
Hey @tony-navillus , could you take a wee look over this if you have a spare second, it appears `define:vars` is breaking the `styles` and is not being sent across.... I wish I could diagnose this better for you dude, but all I can tell is she is breathing but very erratically,

**Comment by i-bsd** [comment]
This is also broken for me trying to pass variables to JSON schema (`<script type="application/ld+json">`).

Just outputs the variable names.

**Comment by tony-sull** [comment]
I'm actually out this week and won't be around reliable internet, @natemoo-re in case this is related to the latest compiler release

**Comment by aFuzzyBear** [comment]
Ah sorry dude, I hope you have a great week @tony-sull, enjoy the fresh air bud, 👊

**Comment by natemoo-re** [comment]
Thanks for the ping! I'll take a look at this today.

**Comment by 1deadpixl** [comment]
I ran into this same issue today. Thought I was doing some wrong.

In diagnosing, I added the implied `is:inline` directive to the `<style>` tag and got a new result:
`TypeError: Cannot convert undefined or null to object`

Seems that `defineStyleVars` isn't seeing the variables declared in the frontmatter?

Hope that extra info helps with the bugfix.
Thanks for the hard work!

**Comment by zadeviggers** [comment]
I'm running into this too, running on beta 18.

**Comment by aFuzzyBear** [comment]
And Tony is back ladies and gentle bears, 
Thanks for getting to this dude, really appreciate it, 💚
Hope you enjoyed the wee break 😃

**Comment by brycewray** [comment]
> And Tony is back ladies and gentle bears, Thanks for getting to this dude, really appreciate it, 💚 Hope you enjoyed the wee break 😃

Yes, once I saw Nate was outta here for a few days, figured this was on hold. Thanks for the advisory @aFuzzyBear!
