### ISSUE TITLE
🐛 BUG: <head> delegated to component does not inject hydration scripts

### ISSUE THREAD

**Issue by pmochine** [withastro/astro#3195]
### What version of `astro` are you using?

1.0.0-beta.17

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

Super hard to describe but I tried to make a minimal reproducible example.

The error is that an astro-root tag that is either empty or even if it is filled up with content, it's just not displayed.

I'm using a normal base layout but within the default-layout I'm using a head-layout. This is somehow the bug.

Have a look at this example: 

https://stackblitz.com/edit/github-2e3za6?file=src%2Fpages%2Findex.astro&on=stackblitz (It's not working because of the default layout).

And have a look at where this example works:

https://stackblitz.com/edit/github-2e3za6-9yzpnu?file=src%2Flayouts%2FDefaultLayout.astro&on=stackblitz

This time I only merged the head-layout with the default-layout.

And unfortunately, I have to use client:only="vue" because I'm trying to use "swiper" with vue components.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2e3za6?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Interesting! It looks like the hydration script is not being included in the head as expected. Pretty critical bug, we'll try to take a look as soon as possible.

**Comment by FredKSchott** [comment]
Related to #3917

**Comment by natemoo-re** [comment]
Related to https://github.com/withastro/astro/issues/3197
