### ISSUE TITLE
🐛 BUG: Astro dev server should restart when relevant config files are changed (ex: `astro.config.js`, `tsconfig.json`, etc)

### ISSUE THREAD

**Issue by Jutanium** [withastro/astro#3196]
### What version of `astro` are you using?

1.0.0-beta.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

Yarn

### What operating system are you using?

Mac

### Describe the Bug

After running `astro add` (in my case `yarn astro add vue`), the `astro.config.mjs` and `yarn.lock` files were updated, but the dev server didn't restart. This caused the dev server to display an error when using a Vue component, as it wasn't running with the new plugin:

`Error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.`

After restarting the dev server, the problem went away, but this is a frustrating DX for beginners. 

(In the minimal reproducable example below, run `yarn astro add vue` to see this behavior.)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/vigilant-frost-q4hb19?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
This has both short term and long term resolutions!
- Short term: improve CLI logs to explain when restarts are necessary. We currently say "updated `astro.config.js`," which is very misleading (implies config changes have taken effect)
- Longer term: update dev server to full-restart dev server on astro config changes. If done correctly, this should trigger a "restarted dev server" info log to clarify

**Comment by bholmesdev** [comment]
@Jutanium Update: I'm going to break out a separate bug to scope this down. I also ask that **we make an RFC discussion for longer-term DX improvements here!** Improving dev server restarts seems like a feature rather than a bug in my opinion.

Closing this issue assuming a discussion RFC is created. Feel free to re-open if you disagree here!

**Comment by bholmesdev** [comment]
Bug report: #3326
