### ISSUE TITLE
🐛 BUG: Errors when using spaces in project pathname

### ISSUE THREAD

**Issue by Elwood-P** [withastro/astro#3202]
### What version of `astro` are you using?

1.0.0-beta.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac OS 12.1

### Describe the Bug

I was getting an error whenever trying to use a route to .md file. Tested by trying fresh install of Blog template and I get error loading homepage. Removing BlogPostPreview component clears the error and the page loads.

On advice from Discord I tried same projects with a pathname containing no spaces. No errors occur.

Example error below:

```
[vite] Error when evaluating SSR module /Users/paullittlewood/My Files/Work/Web Dev/Astro Sites/AstroDemoBlog/src/pages/posts/index.md:
Error: failed to load module for ssr: /Users/paullittlewood/My%20Files/Work/Web%20Dev/Astro%20Sites/AstroDemoBlog/node_modules/astro/dist/runtime/server/index.js
    at instantiateModule (/Users/paullittlewood/My Files/Work/Web Dev/Astro Sites/AstroDemoBlog/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:58445:15)
 error   failed to load module for ssr: /Users/paullittlewood/My%20Files/Work/Web%20Dev/Astro%20Sites/AstroDemoBlog/node_modules/astro/dist/runtime/server/index.js
    at instantiateModule (/Users/paullittlewood/My Files/Work/Web Dev/Astro Sites/AstroDemoBlog/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:58445:15)
```

### Link to Minimal Reproducible Example

/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matchboxhero** [comment]
I just ran into the same issue

**Comment by matchboxhero** [comment]
I managed to get rid of the error by removing a space in a folder name.

I'm sure I saw the spaces in folder names issue in another bug which was marked as fixed but that's what solved it for me.

**Comment by natemoo-re** [comment]
This looks like a Markdown-specific issue now? There were other general issues with this but I think we fixed them for most cases.

Will have to take a closer look at this!
