### ISSUE TITLE
🐛 BUG: Asset URLs not working when used inside of getStaticPaths

### ISSUE THREAD

**Issue by benjaminbarbe** [withastro/astro#3218]
### What version of `astro` are you using?

1.0.0-beta.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Related to: https://github.com/withastro/astro/issues/2145

Everything works fine in development but not for the production build.

index.astro
```
---
import Home from '../../components/Home.astro';

export async function getStaticPaths() {
    return [
      { params: { static: undefined }, props: { Klass: Home } },
    ];
};

const { Klass } = Astro.props;

---

<Klass />
```

Home.astro
```
---
import FullLogoLight from '../assets/full-logo-light.png';
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<link rel="icon" type="image/x-icon" href="/favicon.ico" />
	</head>
	<body>
		<main>
            <img src={FullLogoLight} width="100%" />
		</main>
	</body>
</html>
```

<img width="935" alt="image" src="https://user-images.githubusercontent.com/630365/165481768-caae743e-191c-4401-8865-17c3dbcb87af.png">

### Link to Minimal Reproducible Example

https://withastro-astro-2vobz1xr5z0.ws-eu42.gitpod.io/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I can't see the gitpod, what is it being replaced with?

**Comment by benjaminbarbe** [comment]
Here is a working link: https://codesandbox.io/s/sweet-mendeleev-0ebsr6

Everything works well in development, but the build does not put the asset in the pipeline for optimization, its path remains unchanged.

Thanks

**Comment by FredKSchott** [comment]
The issue seems to be with its usage inside of `getStaticPaths()`. When I make this change, the code works:

```diff
---
import Home from '../../components/Home.astro';

export async function getStaticPaths() {
    return [
      { params: { static: undefined }, props: { Klass: Home } },
    ];
};

const { Klass } = Astro.props;

---

- <Klass />
+ <Home />
```

This sounds like a valid, reproducible issue. Triaging and prioritizing now. In the meantime, you'll need to avoid using assets like this.

**Comment by benjaminbarbe** [comment]
@FredKSchott 

Thank you for your reply.

I know, but I can't use it that way. I generate pages based on external sources. This example is based only on one Astro component, but I have dozens of them. I pass them conditionally.

The only workaround I found to go forward is to use the public directory for now.

🤞

**Comment by matthewp** [comment]
This is working now in latest: https://codesandbox.io/s/jolly-shape-ghuecx?file=/src/components/Home.astro
