### ISSUE TITLE
🐛 BUG: HTML doesn't work in markdown

### ISSUE THREAD

**Issue by daviatkea** [withastro/astro#3220]
### What version of `astro` are you using?

1.0.0-beta.18

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I’m using the built-in <Content /> component to render HTML from a markdown file. It’s working just fine, but when I put HTML inside the markdown file, it duplicates some of the text content and produces weird spacing. For instance, if I put in <code class="some-class">content</code>, I get extra spacing around the word “content”, and my other plain text preceding the code-tag is duplicated. It worked when I was able to use {content.astro.html} in an earlier version of Astro.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ut8fqd

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This seems to be an issue with our Markdown integration, likely coming from the way components are handled in `remark`. We should take a look at making sure the behavior is consistent between paragraphs with HTML embedded in them and paragraphs with only Markdown.

**Comment by rwwagner90** [comment]
@natemoo-re I am still getting a broken build when I try to use HTML in markdown. I get this error 
```
Unexpected character `=` (U+003D) before name, expected a character that can start a name, such as a letter, `$`, or `_`
```

**Comment by natemoo-re** [comment]
> @natemoo-re I am still getting a broken build when I try to use HTML in markdown. I get this error 
> 
> ```
> 
> Unexpected character `=` (U+003D) before name, expected a character that can start a name, such as a letter, `$`, or `_`
> 
> ```

We are tracking a handful of regressions that were introduced by the PR that closed this issue. You can look at the `markdown` tag to see them. If you don't see any related to your specific problem, please feel free to open a new issue.

I'm going to keep this particular issue closed since the original problem in the PR description has been fixed.
