### ISSUE TITLE
🐛 BUG: Base config item does not work correctly with a url

### ISSUE THREAD

**Issue by Alshie** [withastro/astro#3222]
### What version of `astro` are you using?

v1.0.0-beta.18

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

5pm

### What operating system are you using?

Mac

### Describe the Bug

When building the site there no way to have my stylesheet in the final built output have a full url e.g. https://domain.com/css/styles.css whilst retaining the astro build optimisations.

I expected passing a url to the `base` config option to allow this but the output is incorrect when using a url

`base: 'https://domain.com/'`

in astro config leads to the following output

` <link rel="stylesheet" href="/https:/domain.com/assets/asset.028d37aa.css"></link>`

a preceding slash is added to the start of the url and the double slash `//` after `https` is changed to a single slash

expected behaviour would be for the stylesheet link to be rewritten with valid url

**use case for this**

I realise this ties the css to a particular domain but I need this as its for some landing pages that will be deployed to netlify and called from another site using rewrite proxies - without full url it looks for the assets on the original calling domain.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vgqkb3?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
[`base`](https://docs.astro.build/en/reference/configuration-reference/#base) is actually only meant for publishing to subpaths, i.e. `example.com/blog`

The simplest solution would probably be to drop the `.css` files in `public` so they never get bundled and hashed.  If it's really one project being built and published to multiple domains you could also use Vite's `?url` imports to get the same `href` that is built into `<link>`s by default

```html
---
import styles from '../styles/blog.css?url';

const url = new URL(styles, "https://example.com");
---

<link href={url.toString()} rel="stylesheet">
```

**Comment by theduke** [comment]
I have the same requirements, or more specifically: I would like to only have a custom URL for static assets, since I want to serve them from a different domain.

Manually prefixing the base in front of all `import` ed assets is not a viable solution.

**Comment by KNighD** [comment]
> [`base`](https://docs.astro.build/en/reference/configuration-reference/#base) is actually only meant for publishing to subpaths, i.e. `example.com/blog`
> 
> The simplest solution would probably be to drop the `.css` files in `public` so they never get bundled and hashed. If it's really one project being built and published to multiple domains you could also use Vite's `?url` imports to get the same `href` that is built into `<link>`s by default
> 
> ```
> ---
> import styles from '../styles/blog.css?url';
> 
> const url = new URL(styles, "https://example.com");
> ---
> 
> <link href={url.toString()} rel="stylesheet">
> ```

Is there any reason why `base` just not doing the same thing just like vite, or is there something alternative? I'd like deploy my bunled static assests to cdn, while html on my own server, but now I just can not do this

**Comment by LeonDWong** [comment]
I meet same problem, my case is that uploading assets to storage service which using different domain, but i can't change assets domain anyway.
And i checkout generated source code (using standalone mode). Find out that Astro always add splash before assets path when first character is not a splash. Is it a better solution that add a condition if path is beginning with schema?
<img width="376" alt="image" src="https://user-images.githubusercontent.com/17465046/202671020-0b604282-aa2f-4e4e-a7e0-addc31578fed.png">

**Comment by dan-newscorp** [comment]
+1 same issue here. Loving Astro and think it'd be perfect for what we want to achieve, but being unable to to specify a base domain for assets is a dealbreak, as we need to serve those assets from an Akamai CDN.

**Comment by ob6160** [comment]
Vite seems to have an experimental option to allow you to control this: https://vitejs.dev/guide/build.html#advanced-base-options called `renderBuildUrl` but I imagine that this isn't called as part of the Astro build process.

This would also be a useful feature for us as we have a similar story where we need to serve assets from a CDN.

Not sure if there's another good escape hatch I'm missing here, but I suppose post-processing the built files to find/replace the values might be an option, albeit a fragile one.

**Comment by dan-newscorp** [comment]
Yeah i was also trying to use `renderBuildUrl`, but ur right, it doesnt seem to be called in the astro build process.
I wonder if that is a deliberate decision or a defect, seeing Astro is shipped supporting Vite 3

**Comment by ConsoleTVs** [comment]
Just adding a better solution in the mean time:

```astro
---
import something from '../assets/something.png?url'

const url = new URL(something, Astro.site)
---
```

At least this seems to make a good enough trade off for cases where you need a fully qualified URL, such as `og:image` meta tag.

**Comment by matafokka** [comment]
Hello, everyone! A bit late to the party. I'm using Astro for building email messages, and I really need to use full URL to our website.

For assets in `src`, this issue can be solved by this config:

```js
{
  site: BASE_URL,
  build: {
    assetsPrefix: BASE_URL,
  }
}
```

However, fonts can't be imported from `src` because they're not resolved by Vite for some reason. You'd see this in a terminal if you'll try to build the project:

```
[file name] referenced in [file path] didn't resolve at build time, it will remain unchanged to be resolved at runtime
```

The simplest and fastest solution an Astro user can do is to put all files in a directory with a unique name (for example, `/public/put-files-here-this-fixes-astro`) and replace it after the build.

Project's directory structure will look like this:

```
public
 |- put-files-here-this-fixes-astro
    |- fonts
       |- Noto.ttf
       |- ComicSansLol.ttf
    |- images
       |- favicon.ico
       |- logo.svg
```

Then add a script that'll move your files to the build root (so URLs will look nice) and replace unique directory with the full website URL

```js
import { DEFAULT_BASE_URL } from "./build-const.mjs";
import fs from "fs";
import fse from "fs-extra";
import path from "path";

console.log("Fixing public assets...");

const PUBLIC_DIR = "put-files-here-this-fixes-astro";
let BASE_URL = process.env.ENV_BASE_URL || DEFAULT_BASE_URL; // You website/CDN URL here

if (!BASE_URL.endsWith("/")) {
  BASE_URL += "/";
}

const distDir = path.join(import.meta.dirname, "dist");
const tempAssetsDir = path.join(distDir, PUBLIC_DIR);
const tempAssetsEntries = fs.readdirSync(tempAssetsDir);

const movePromises = [];

for (const entry of tempAssetsEntries) {
  movePromises.push(fse.move(path.join(tempAssetsDir, entry), path.join(distDir, entry)));
}

await Promise.all(movePromises);

function transformFiles(filePath) {
  if (fs.lstatSync(filePath).isDirectory()) {
    const entries = fs.readdirSync(filePath);

    for (const entry of entries) {
      transformFiles(path.join(filePath, entry));
    }

    return;
  }

  let didReplace = false;

  const content = fs
    .readFileSync(filePath)
    .toString()
    .replaceAll(`/${PUBLIC_DIR}/`, () => {
      didReplace = true;
      return BASE_URL;
    });

  if (didReplace) {
    fse.writeFile(filePath, content);
  }
}

transformFiles(distDir);
```

And then update `build` script in `package.json` like so:

```
"build": "astro check && astro build && node postbuild.mjs"
```

If you, like I, want to use external template engine on top of generated files, you can safely put something like `{{ host }}` instead of an actual URL, it should work.

____

P.S. My suggestion to Astro team is to honor Vite's `base` and `experimental.renderBuiltUrl` options as an opt-in behavior to preserve backward compatibility.
