### ISSUE TITLE
🐛 BUG: Dynamic JSX elements do not update without manually restarting the dev server

### ISSUE THREAD

**Issue by Jutanium** [withastro/astro#3228]
### What version of `astro` are you using?

1.0.0-beta.19

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac, Linux

### Describe the Bug

Rendering a dynamic element (taking an element string as a prop and then rendering that in JSX) works, but only the first time - changing what I pass as that prop triggers the dev server to HMR but does not actually propagate the change. The only way to propagate the change is to trigger a different fundamental change to the component, or to manually restart the dev server.

In the following example, try changing the value passed to `DynEl`. 

### Link to Minimal Reproducible Example

https://codesandbox.io/s/rough-field-3q46gu?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pkb-pmj** [comment]
I've encountered a similar problem (1.0.0-beta.20, npm, macOS Catalina).
I have a script tag inside an `.astro` layout. When I change the JS in the script, it triggers a reload but doesn't actually change anything.

**Comment by CalebKester** [comment]
Same. Anytime I edit a `<script>` inside of an .astro component i have to restart the server to see it change.

**Comment by markteekman** [comment]
Also have been experiencing the exact same problem, changing things inside my `<script>` need a reload of the dev server to reflect the changes.

**Comment by tnraro** [comment]
This problem is also found in 1.0.0-beta.31, npm, WSL2 in Windows 11. I need to reload the dev server when I change my code in the script tag.
