### ISSUE TITLE
🐛 BUG: Access to SSR Manifest in plugins/adapters/integratrions

### ISSUE THREAD

**Issue by thepassle** [withastro/astro#3251]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

Im creating an integration that creates a Service Worker build of your Astro app, so you can render your astro pages when offline/on the client.

The problem I'm running into, is that I don't have access to the SSR Manifest thats being created in [`vite-plugin-ssr`](https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/vite-plugin-ssr.ts#L75)

Essentially, what I'm trying to do is something like:
![image](https://user-images.githubusercontent.com/17054057/166152762-8d743efe-7f11-432a-bb75-c9b49ccda51c.png)

Where I need to be able to pass the `_manifest` to the adapter's `start` function. However, I dont have access to the manifest via any lifecycle hooks, and the `'@@ASTRO_MANIFEST_REPLACE@@'` or `manifestReplace` is guarded by an [if clause](https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/vite-plugin-ssr.ts#L81-L85): 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/17054057/166152856-689fe9ac-027f-4ae1-a848-99a8c20eed35.png">

Could this if clause be loosened up a little bit, so that other plugins could also gain access to the manifest? If this is agreeable, I've created a PR [here](https://github.com/withastro/astro/pull/3252). But I'm also happy to hear any other thoughts/ideas 🙂

Or maybe the ssr manifest can be passed to `astro:build:done|start` ?
 

<details>
  <summary>full code for clarity</summary>

```js
import { defineConfig } from 'astro/config';
import netlify from '@astrojs/netlify';

const virtualModuleId = "astro-swsr-virtual-module";
const resolvedVirtualModuleId = "\0" + virtualModuleId;
const manifestReplace = "@@ASTRO_MANIFEST_REPLACE@@";
const pagesVirtualModuleId = "@astrojs-pages-virtual-entry";

function getAdapter({networkOnly = []} = {}) {
  return {
    name: "astro-service-worker",
    serverEntrypoint: `${process.cwd()}/service-worker-integration/server.js`,
    exports: [],
    args: { networkOnly }
  };
}

function SWSR(options) {
  return {
    name: 'astro-plugin-swsr',
    options(opts) {
      return {
        ...opts,
        input: [...(opts.input ?? []), virtualModuleId],
      };
    },
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }
    },
    load(id) {
      const adapter = options.adapter;

      if (id === resolvedVirtualModuleId) {
        return `import * as adapter from '${adapter.serverEntrypoint}';
  import * as _main from '${pagesVirtualModuleId}';

  import { deserializeManifest as _deserializeManifest } from 'astro/app';
  const _manifest = Object.assign(_deserializeManifest('${manifestReplace}'), {
    pageMap: _main.pageMap,
    renderers: _main.renderers
  });

  const _args = ${adapter.args ? JSON.stringify(adapter.args) : "undefined"};
  
  ${adapter.exports ? `const _exports = adapter.createExports(_manifest, _args);
  ${adapter.exports.map((name) => {
            if (name === "default") {
              return `const _default = _exports['default'];
  export { _default as default };`;
            } else {
              return `export const ${name} = _exports['${name}'];`;
            }
          }).join("\n")}
  ` : ""}

  const _start = 'start';
  if(_start in adapter) {
    adapter[_start](_manifest, _args);
  }`
      }
    }
  }
}

// https://astro.build/config
export default defineConfig({
  adapter: netlify(),
  vite: {
    plugins: [
      SWSR({
        adapter: getAdapter()
      })
    ]
  }
});

```
</details>

### Link to Minimal Reproducible Example

astro.new

### Participation

- [x] I am willing to submit a [pull request](https://github.com/withastro/astro/pull/3252) for this issue.

**Comment by matthewp** [comment]
Let's keep the discussion here for now: https://github.com/withastro/rfcs/discussions/188. I think we can probably do this without needing a full RFC, especially if you're willing to implement.
