### ISSUE TITLE
🐛 BUG: Issue creation link in terminal does not work

### ISSUE THREAD

**Issue by IanVS** [withastro/astro#3257]
### What version of `astro` are you using?

0.26.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

I'm trying to upgrade to 0.26, and I get an error.  But, the point of this issue isn't the error itself, but rather the link that is provided in the terminal.  It seems like it's intended to fill out some information in the issue, to get the user started, with query params for labels, title, body, etc, but instead it just opens the standard https://github.com/withastro/astro/issues/new/choose page.  

### Link to Minimal Reproducible Example

None

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
I think these issue links were updated a couple times on the way to the beta release, any chance you could try upgrading to the latest beta to see if this issue still hits?

**Comment by IanVS** [comment]
I'm going to upgrade to 1.0.0 beta next, and I'm sure I'll have a chance to test out an error link or two.  😆

**Comment by IanVS** [comment]
Yes, I updated to the latest beta, and triggered an error of the following:

```
Error: Uh oh, the Astro compiler encountered an unrecoverable error!

    Please open
    a GitHub issue using the link below:
```

https://github.com/withastro/astro/issues/new?labels=compiler&title=%F0%9F%90%9B+BUG%3A+%60%40astrojs%2Fcompiler%60+panic&body=%23%23%23+Describe+the+Bug%0A++++%0A++++%60%40astrojs%2Fcompiler%60+encountered+an+unrecoverable+error+when+compiling+the+following+file.%0A++++%0A++++**src%2Fcomponents%2Fatoms%2FConfigOption.astro**%0A++++%60%60%60astro%0A++++---%0Aimport+%7B+Code%2C+Markdown+%7D+from+%22astro%2Fcomponents%22%3B%0A%0Aconst+%7B+isRequired%2C+description%2C+example+%7D+%3D+Astro.props%3B%0A%2F%2F+Remove+the+styles+below+once+https%3A%2F%2Fgithub.com%2Fwithastro%2Fcompiler%2Fissues%2F379+is+fixed%0A---%0A%0A%3Cstyle%3E%0A++.badge+%7B%0A++++margin-bottom%3A+1.5rem%3B%0A++%7D%0A++.container+%3Aglobal%28.p%29%3Alast-child+%7B%0A++++margin-bottom%3A+1.5rem%3B%0A++%7D%0A%3C%2Fstyle%3E%0A%0A%3Cslot%3E%3C%2Fslot%3E%0A%7BisRequired+%26%26+%3Cp+class%3D%22mt-16+badge+badge-info%22%3ERequired%3C%2Fp%3E%7D%0A%7Bdescription%3F.trim%28%29+%26%26+%3CMarkdown+content%3D%7Bdescription%7D+%2F%3E%7D%0A%7Bexample+%26%26+%3CCode+code%3D%7Bexample%7D+lang%3D%22yaml%22+%2F%3E%7D%0A%0A++++%60%60%60%0A++++

**Comment by IanVS** [comment]
@Princesseuh when I click the link above, this is what I see:

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/4616705/167702017-a88ed923-60e4-42e7-8894-60815aa41d4b.png">

I wonder if it works differently for you because you're in the astro org?  What happens if you try clicking that link in an incognito window?
