### ISSUE TITLE
🐛 BUG: post.content.rendered

### ISSUE THREAD

**Issue by jonseo** [withastro/astro#3260]
### What version of `astro` are you using?

1.0.0

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm 17

### What operating system are you using?

Windows 11

### Describe the Bug

Created dynamic page [slug].astro.
Where its supposed to display the content with this:
<div>
   {post.content.rendered}
    </div>
Its only displaying one long html string, like this: <h4><span style="color: #c64305;"><strong><i>Improving your Skills</i></strong></span></h4> <p>Do you want to...................
Would like to see the "content" as if for the frontend users.

### Link to Minimal Reproducible Example

https://stackblitz.com/1234

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Can you share a link to a minimal repro?

**Comment by jonseo** [comment]
Thnx, someone had already found the answer and referenced it.
Its just the directives I had to play with. - ie.  set:html={string}

Thank you!

Jon Hines
Digital Strategies/Web Dev Director
Media Inc. Publishing
941 Powell Ave S Suite 120
Renton, WA 98057
1-800-332-1736
(206) 382-9220 xt107
americanshootingjournal.com
nwsportsmanmag.com
aksportingjournal.com
https://www.facebook.com/AmericanShootingJournal
https://twitter.com/AmShootingJourn

**Comment by tony-sull** [comment]
Excellent, glad the `set:html` did the trick!
