### ISSUE TITLE
🐛 BUG: Remark plugin transformer file.path returns undefined

### ISSUE THREAD

**Issue by stephanbogner** [withastro/astro#3264]
### What version of `astro` are you using?

1.0.0-beta.20

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Whatever StackBlitz uses

### Intention:
I am trying to create a remark-plugin that allows having image-files right next to .md files.

### Approach:
1. I struggled to obtain the absolute file paths of the .md (or the images) so I opened [a thread](https://github.com/orgs/remarkjs/discussions/990) in the remarkjs discussions
2. The [maintainer wooorm mentioned](https://github.com/orgs/remarkjs/discussions/990#discussioncomment-2679117) that `file.path` should return well the file path. But it seems in Astro it doesn't (see StackBlitz)
3. Woorm [also replied](https://github.com/orgs/remarkjs/discussions/990#discussioncomment-2679507) that the root cause might be [this bit of code](https://github.com/withastro/astro/blob/de123b28b3ff398b800cb598f20326ca85a0fb60/packages/markdown/remark/src/index.ts#L90) in the Astro source code

### Relevant bit of code:
```
export default function (pluginOptions) {
  const transformer = (tree, file) => {
    console.log('Transformer data:');
    console.log(file.path); // -> returns undefined
  };

  return transformer;
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3cnfvx-nsf5xw?file=custom-remark-plugin/index.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Yep, looks like we could improve the way we're calling `process` here. I'll try to get this prioritized!

**Comment by stephanbogner** [comment]
No worries, you're welcome! And thanks for trying to solve this quickly 😊

**Comment by stephanbogner** [comment]
I never replied. Thanks a lot! Works great now! @natemoo-re
