### ISSUE TITLE
🐛 BUG: Vue SFC styles/JS not loading properly

### ISSUE THREAD

**Issue by andy-stewart-design** [withastro/astro#3265]
### What version of `astro` are you using?

1.0.0-beta.20

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm having an issue with loading the styles/javascript from single-file Vue components. The problem is different in dev and prod environments.

In Dev, I'm having an issue in Brave and Firefox, but not Chrome or Safari, where, when I navigate the site using the browsers back/forward buttons, I get the following errors:

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.`
`Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:3000/@fs/Users/andy/Documents/Dev/astro-vue/src/components/HomeHero.vue`

The result is that the JS from the Vue component is not loaded and the interactive elements do not work. When I remove the style tags, the JS loads as expected, though obviously that's not an ideal solution. If I refresh the page, the problem is resolved. When I navigate the site using internal links, everything works as expected.

In production, which you can see at the attached link/Github repo, the problem is different. I don't get any errors, and the JS is loaded successfully when navigating between the pages of the site, but that seems to be because the styles from the Vue component are not being loaded (in the attached example, clicking the button is supposed to toggle the `isActive` boolean and change the background color of the button. You can see the isActive boolean being toggled, but the button background color is not changing, which suggests that the styles are not being toggled). As far as I can tell, this issue happens in all browsers.

To be thorough, I've attached a Code Sandbox link, although I don't think you'll be able to reproduce it there. Instead, try these links:

Github: https://github.com/andy-stewart-design/astro-vue
Netlify: https://neon-meerkat-f23f4f.netlify.app/

### Link to Minimal Reproducible Example

https://codesandbox.io/s/twilight-worker-2qp6su?file=/src/pages/about.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
I'm sorry, but I can't reproduce. Can you either share a video walkthrough or some numbered steps that someone could follow to see the same error that you're seeing?

**Comment by natemoo-re** [comment]
Possibly related? https://github.com/withastro/astro/issues/3219

**Comment by andy-stewart-design** [comment]
@FredKSchott @natemoo-re Thanks for the response. The problem I mentioned in the production build seems to have actually been caused by a weird discrepancy in specificity between dev and prod. Anyway, I think you can safely disregard it.

I'm attaching a video of the dev issue. I think Nate could be right — it seems like a similar problem.

https://user-images.githubusercontent.com/47165383/167754855-a2d7c34b-129c-4a55-860b-d487c6215138.mp4

.
