### ISSUE TITLE
🐛 BUG: Ctrl-C doesn’t stop 1.0.0-beta.21 dev server

### ISSUE THREAD

**Issue by brycewray** [withastro/astro#3269]
### What version of `astro` are you using?

1.0.0-beta.21

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

When I run `astro dev`, the terminal will not accept Ctrl-C as a stop command but, rather, just echoes `^C` in the display. I tried it also with `astro dev --experimental-static-build --experimental-integrations` and got the same result. (Could only suspend the job with Ctrl-Z, and then separately kill the suspended job.)

Downgrading to 1.0.0-beta.20 solves the problem.

**Note**: I tried to create a minimal reproducible example but was unable to load 1.0.0-beta.21 successfully. The URL below is **NOT** usable, but simply something to allow me to submit the issue.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/kkvinmbxo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by brycewray** [comment]
I will add that @Jutanium reports on Discord that he can't reproduce the issue on his Mac. He suggested that I try the other test environments on astro.new, which I did but, again, couldn't load 1.0.0-beta.21 to test them (each was still on 1.0.0-bet.20).

**Comment by hayley** [comment]
I just upgraded one of my projects from .20 to .21 and am seeing this same behaviour with ctrl C not working. Downgrading back to .20 also fixed.

Mine is Void Linux, but I can also test this on Mac and Arch Linux if helpful.

**Comment by brycewray** [comment]
@hayley on the Discord, @Jutanium advises his Mac has Apple Silicon. Mine is an Intel Mac. Am assuming your Linux box is using an x86 CPU. Can you test on an Intel Mac?

**Comment by brycewray** [comment]
Being fixed in https://github.com/withastro/astro/pull/3276.

**Comment by matthewp** [comment]
Thanks for reporting!

**Comment by brycewray** [comment]
> Thanks for reporting!

@matthewp @FredKSchott Thank you folks for the quick fix incoming!

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/3276, release will be coming in a few minutes.
