### ISSUE TITLE
🐛 BUG: Duplicate <title> meta in Astro's Blog (Complex) template

### ISSUE THREAD

**Issue by djmtype** [withastro/astro#3270]
### What version of `astro` are you using?

1-beta 19

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

In Astro's Blog (Complex) template, the meta info for `<title>` is being displayed twice – once as a prop within MainHead.astro, and the other instance is directly on the index page.  https://github.com/withastro/astro/blob/latest/examples/blog-multiple-authors/src/pages/index.astro#L27

### Link to Minimal Reproducible Example

https://astro.new/blog-multiple-authors?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, mind sending a PR?

**Comment by kevinzunigacuellar** [comment]
This issue can be closed 😁
