### ISSUE TITLE
🐛 BUG: Windi, Uno, and other Vite plugins that need to read the page content do not correctly hot reload

### ISSUE THREAD

**Issue by yellowsink** [withastro/astro#3291]
### What version of `astro` are you using?

1.0.0-beta.24

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Recently, Vite plugins became capable of reading the contents of `.astro` pages.

This allowed atomic CSS frameworks like WindiCSS and UnoCSS to flourish, however with one drawback.

These build fine, and when you run `astro dev`, the styles will apply fine, however any changes to your `.astro` page will not reflect in the styles.

I suspect that, for whatever reason, Vite plugins do not get to see HMR'd `.astro` pages.

Cannot reproduce *consistently* in stackblitz. Can reproduce locally and in GitPod (linked).

Additional videos showing both Gitpod and local env displaying the issue:

https://user-images.githubusercontent.com/19270622/166800184-f6babb53-8c39-4c9c-97d9-0aa46ec74543.mp4

https://user-images.githubusercontent.com/19270622/166800195-860155a4-029d-48dd-b1c7-67c1617a18ad.mp4

### Link to Minimal Reproducible Example

https://gitpod.io#snapshot/229ff5b6-51af-4e32-8c14-ff119e07298c

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by yellowsink** [comment]
I suspect this *could* have a relation to #3228?

**Comment by AllanChain** [comment]
After playing around with a normal vite project and an astro project, I find that the CSS HMR problem is caused by astro injecting `__uno.css` into HTML:

```html
<link rel="stylesheet" href="/__uno.css" data-astro-injected>
```

This makes the browser send a normal CSS request which has the header:

```yaml
Accept: text/css,*/*
```

instead of

```yaml
Accept: */*
```

in normal vite application. This makes vite returning normal CSS instead of a HMR JS module:

```js
// https://github.com/vitejs/vite/blob/1ffc0107e81d9196284a42dd450b8ff9d038b245/packages/vite/src/node/server/middlewares/transform.ts#L152-L158
        // for CSS, we need to differentiate between normal CSS requests and
        // imports
        if (
          isCSSRequest(url) &&
          !isDirectRequest(url) &&
          req.headers.accept?.includes('text/css')
        ) {
          url = injectQuery(url, 'direct')
        }
```

**Comment by yellowsink** [comment]
I see.

**Comment by matthewp** [comment]
Thanks for all of the research @AllanChain! I think this probably needs to be an integration, in that case. Integrations can call `injectScript()` to inject a script into the page, in which allows you to append this JS script. Astro is not able to know that it needs to inject a JS script for this CSS module.

This is a case where the uno.css Vite plugin is intended for a normal Vite application that is a SPA and everything is done in the client, which is not the way Astro works. Happy to help someone who wants to build a Uno Astro integration!

**Comment by high1** [comment]
@matthewp I would be willing to work on unocss integration, if you can provide me with guidance - sorry for reopening this.

**Comment by AllanChain** [comment]
@high1 I actually tried out a little bit but found it hard to make it work properly without the ability to preserve injected element between .astro hmr.

One potential solution would be let unocss properly invalidate the css module (I did this by modifyig  node_modules), and send css-update event (or update css url timestamp via injectScript). But this still have flashes. In fact the css hmr of .astro file seems also flash between updates. Ideally I'd wait Astro to fix the css hmr problem before further experiments.

If you want the code, I'll create a repo and upload my experiments.

**Comment by high1** [comment]
That would be great. We could continue the discussion there. Is there an official bug report for css flashing with hmr?

**Comment by AllanChain** [comment]
I have created a bug report at #3370 for the flashing problem.

The experimental integration code is uploaded at https://github.com/AllanChain/astro-uno

**Comment by AllanChain** [comment]
With the updates in `astro@1.0.0-beta.42`, now we can use UnoCSS just as usual :tada:

**Comment by Nauxscript** [comment]
@AllanChain thx for your integration! when i got unocss hmr problem yesterday, i found this issue and use astro-uno, and its seem working well at that time, but this morning i start my project I get a error:

```
Error: Cannot find module 'uno.css-hmr-fix' imported from 'astro:scripts/page-ssr.js'
```

i am sorry I can't repoduce this error in online example,  if you  know what happend to this, plz let me know.

thank you so much!
