### ISSUE TITLE
🐛 BUG: In Dev, /help.html doesn't work but /help does

### ISSUE THREAD

**Issue by hsnyc** [withastro/astro#3294]
### What version of `astro` are you using?

v1.0.0-beta.18

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Hi all, trying to use Astro as my main static site gen.. really digging it so far. 
I am trying to convert an existing static site which has a nav menu referencing html files, like this:
```
<li><a href="help.html">Help</a></li>
...
```

In Astro, I have the build format set to 'file' because I want the output files to keep their name and be placed in the root when the site is built. I need the dir structure to stay this way in order for it to work in our environment, not placed in directories like `/help/index.html`. 

In Astro this file is `help.astro` and after build, it is `help.html`. If I build and Preview I have not issues navigating. But, while in Dev the nav wont work because of course that file does not exist (`help.html`) until the site is built. 

My question is how do I tell Astro to look for `help.html `while in dev.. ?

My temporary solution/workaround is to use the default env variable `import.meta.env.MODE` to conditionally set the Nav's href to the appropriate file
```
// help.astro
const mode = import.meta.env.MODE;
...
<li>
  <a href={mode === "development" ? '/help' : 'help.html'}>Help</a>
</li> 
```
submitting the Issue in case this can be addressed in a more elegant way. 

Thanks!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cz4cyw?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Fixed with PR #3401  🎉
