### ISSUE TITLE
🐛 BUG: `injectScript` only works during dev or SSG mode, not SSR (build only)

### ISSUE THREAD

**Issue by thepassle** [withastro/astro#3298]
### What version of `astro` are you using?

1.0.0-beta.24

### Are you using an SSR adapter? If so, which one?

netlify

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

> Note: during dev it works fine, this only regards the SSR build output

Im trying to add a script to the head of my pages using the `injectScript` callback in the `astro:config:setup` hook like so:

```js
      'astro:config:setup': ({ command, injectScript }) => {
        if(command === 'build') {
          injectScript('head-inline', options?.swScript ?? SW_SCRIPT);
        }
      },
```

But it seems like during the build, scripts on `astroConfig._ctx.scripts` only get added if `staticMode` is true, which only seems to be the case for SSG mode.

`head-inline` scripts seem to get added in `generatePath` in `generatePage` in `generatePages` in `static-build.ts`, 
![image](https://user-images.githubusercontent.com/17054057/166878168-8a5103e1-78e9-40b6-8bbc-9b20c2d6f132.png)

but that never gets called when not in SSG mode:
![image](https://user-images.githubusercontent.com/17054057/166878540-f3bd9eb1-457a-4081-98fc-e98248001af1.png)

I can reproduce it by creating a new minimal template astro project, and the following config:
```
mkdir scripts-repro && cd scripts-repro && npm init astro@latest -- template=minimal && npm i -S @astrojs/netlify
```

```js
import { defineConfig } from 'astro/config';
import netlify from '@astrojs/netlify';

// https://astro.build/config
export default defineConfig({
  adapter: netlify(),
  integrations: [{
    name: 'foo',
    hooks: {
      'astro:config:setup': ({ command, injectScript }) => {
        if(command === 'build') {
          injectScript('head-inline', 'window.a = "fooadsfasdf";console.log(window.a);');
        }
      },
    }
  }]
});
```

### Link to Minimal Reproducible Example

astro.new

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by thepassle** [comment]
Looking more into this, I think in `vite-plugin-ssr`, in the `buildManifest` function, the scripts on `astroConfig._ctx.scripts` need to be added to the manifest:

```diff
function buildManifest(opts, internals, staticFiles) {
  const { astroConfig } = opts;
  const routes = [];

  for (const pageData of eachPageData(internals)) {
    const scripts = Array.from(pageData.scripts);
    if (pageData.hoistedScript) {
      scripts.unshift(pageData.hoistedScript);
    }
    routes.push({
      file: "",
      links: Array.from(pageData.css),
-       scripts,
+      scripts: [...scripts, ...astroConfig._ctx.scripts],
      routeData: serializeRouteData(pageData.route)
    });
  }
  const entryModules = Object.fromEntries(internals.entrySpecifierToBundleMap.entries());
  entryModules[BEFORE_HYDRATION_SCRIPT_ID] = "data:text/javascript;charset=utf-8,//[no before-hydration script]";
  const ssrManifest = {
    routes,
    site: astroConfig.site,
    markdown: astroConfig.markdown,
    pageMap: null,
    renderers: [],
    entryModules,
    assets: staticFiles.map((s) => "/" + s)
  };
  return ssrManifest;
}
```

**Comment by tony-sull** [comment]
@thepassle thanks for the deep investigation here!  Would you actually be interested in opening a PR with the fix?

**Comment by thepassle** [comment]
The fix I suggest does lead to a lot of duplication in the build, I was hoping to hear some thoughts on how to go about that to avoid the bundles being larger than they need to be

**Comment by matthewp** [comment]
I think this sounds ok. The point of injectScript is to inject it into every page.

**Comment by thepassle** [comment]
Made a PR here: https://github.com/withastro/astro/pull/3339

Would love some pointers if the TS can be improved
