### ISSUE TITLE
🐛 BUG: Unable to load CSS from React-Spectrum

### ISSUE THREAD

**Issue by Morialkar** [withastro/astro#3306]
### What version of `astro` are you using?

1.0.0-beta.20

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Trying to import a UI library, getting strange error about . being an unexpected token. 

The UI library documentation mentions requiring css-loader for webpack but no matter how hard I looked, I couldn't find any information in the documentation on how I could solve this kind of situations.

All help would be appreciated, thank you.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zgagsv?file=src/components/Counter.jsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

I might, but I have no idea where to start

**Comment by matthewp** [comment]
Thanks for filing. It seems like there's a deeper issue here and even importing this module fails in SSR: https://stackblitz.com/edit/github-zgagsv-rgrbiy?file=src%2Fpages%2Findex.astro
