### ISSUE TITLE
🐛 BUG: RangeError: Incorrect locale information provided

### ISSUE THREAD

**Issue by UpperCod** [withastro/astro#3309]
### What version of `astro` are you using?

1.0.0-beta.24

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Running Astro generates the following error:

```bash
RangeError: Incorrect locale information provided
    at new DateTimeFormat (<anonymous>)
    at file:///C:/git/atomico/plugin-astro/node_modules/astro/dist/core/logger/core.js:15:24
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
```
This error occurs because node generates the process.en.LANG with the following code `es_419.UTF-8`, which is incompatible with the result of `getLoggerLocale` when instantiating Intl.DateTimeFormat in:

```bash
const dateTimeFormat = new Intl.DateTimeFormat(getLoggerLocale(), {
  hour: "2-digit",
  minute: "2-digit",
  second: "2-digit"
});
```

**Reproduction is complex since this is a Node variable depending on the region of the installation, in my case country Chile**

### Link to Minimal Reproducible Example

https://github.com/UpperCod/atomico-astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by UpperCod** [comment]
The bug can be patched as follows:
1. Open time settings in windows
2. Time and language > Region and language
3. Change regional format to `Español (International)`

**Comment by natemoo-re** [comment]
Sorry for the frustration! This is a pretty critical issue but should be pretty small to fix. We should definitely take a look at this soon.

**Comment by UpperCod** [comment]
Hi, the solution that I have attached is not valid, this affects Windows 11 users with international Spanish (or that is my case).

I am attentive to the solution and to what you need

**Comment by tanepiper** [comment]
I've just had this affect a colleague, her machine was in Colombian Spanish while I'm in UK English.

**Comment by natemoo-re** [comment]
Thanks for opening an issue—this is fixed in the next release of Astro!

We've also added some regression tests to ensure this doesn't happen in the future.
