### ISSUE TITLE
🐛 BUG: vite-plugin-webfont-dl is not working

### ISSUE THREAD

**Issue by irrvrsl** [withastro/astro#3310]
### What version of `astro` are you using?

1.0.0-beta.25

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Hi there! I tried to add the [vite plugin](https://github.com/feat-agency/vite-plugin-webfont-dl), it fetches google fonts with required css, puts them in the `assets` folder and transforms `<link href="[YOUR-CSS-URL]" rel="stylesheet" />` tags in html. It doesn't work. Example attached. 

The expected result should look like this:

```html
<link rel="preload" as="style" href="/assets/webfonts.b904bd45.css">
<link rel="stylesheet" media="print" onload="this.onload=null;this.removeAttribute('media');" href="/assets/webfonts.b904bd45.css">
```

The actual result:
```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap" rel="stylesheet">
```

However no errors in terminal or other useful information. Thanks in advance!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-m6xrum?file=dist/index.html

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks for filing! Unfortunately this plugin depends on a Vite hook that only works if you are using Vite's SPA workflow. Since Astro produces its own HTML, this hook never gets called. https://github.com/feat-agency/vite-plugin-webfont-dl/blob/00425ebde833f73587607232105bfbe4b548b2dd/src/index.ts#L162
