### ISSUE TITLE
🐛 BUG: Can't overwrite vite's MODE environment variable

### ISSUE THREAD

**Issue by caioferrarezi** [withastro/astro#3311]
### What version of `astro` are you using?

v1.0.0-beta.27

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

I wanna open this issue saying that I wasn't able to find out if this really a bug or it's designed like that, but since the docs mentions this:

> Astro uses Vite for environment variables, and allows you to [use any of its methods](https://vitejs.dev/guide/env-and-mode.html) to get and set environment variables.

I'm struggling to find a way to overwrite the `MODE` environment variable to any value other than `production` or `development` (in my case, I need `staging`). What I was able to find is that the `build` script already expects this option [as seen here](https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/index.ts#L35) but the [CLI never provides it](https://github.com/withastro/astro/blob/main/packages/astro/src/cli/index.ts#L167).

It seems that a `--mode` flag to the build command [like vite's](https://vitejs.dev/guide/env-and-mode.html#modes) already solves the problem, but I came to ask because as I said, I don't know if this is a bug or if it is desired.

Thanks! 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ueaw7y?file=package.json,src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I think this is a case where we are not providing the `mode` you passed in. https://github.com/withastro/astro/blob/1acbcaba9e05ef376ba8f2e550a0ab5bbad35efe/packages/astro/src/core/build/static-build.ts#L125

**Comment by caioferrarezi** [comment]
Thanks, @matthewp! I didn't see this step! 

If you don't mind I would like to give it a try :)

**Comment by bholmesdev** [comment]
Yep! Just discovered some added utility from custom Vite modes beyond the `import.meta.env.MODE` too. Namely, allowing custom environment variable extensions like `.env.staging`. Would like to support [everything documented on the Vite 3 page](https://vitejs.dev/guide/env-and-mode.html#modes)!
