### ISSUE TITLE
🐛 BUG: Frontmatter variables in Markdown

### ISSUE THREAD

**Issue by ClintH** [withastro/astro#3318]
### What version of `astro` are you using?

1.0.0-beta.27

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Seems the same issue as #2886 ?

```
---
notworking: working

---

![foo]({frontmatter.notworking})
```

Yields HTML:

```html
<img src="%7Bfrontmatter.notworking%7D" alt="foo">
```

Expected HTML:

```html
<img src="working" alt="foo"> 
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9qfe1m-wef4od?file=src%2Fpages%2Findex.md,package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ClintH** [comment]
I suppose I expected variables to work consistently as per the [variables in Markdown](https://docs.astro.build/en/guides/markdown-content/#using-variables-in-markdown) documentation. 

One might argue that the syntax is the MD equivalent for the `IMG` tag example you give. Having to use HTML or fancy components would be a shame as it diminishes the point of using Markdown.

**Comment by RichardJECooke** [comment]
Could someone from Astro please explain how frontmatter variables are supposed to work please?

None of the examples render the variable value for me in the output:

```md
A link - [{frontmatter.url}]({frontmatter.url})

In backquotes - 

In codeblocks -  `{frontmatter.technology`

'''
git clone {frontmatter.url}.git
cd fusionauth-quickstart-wordpress-web
'''

```

What syntax do I use to get these to render?  Otherwise I have to copy and paste their values dozens of times throughout my document, and update every one manually whenever I change them.

**Comment by RichardJECooke** [comment]
I thought maybe using HTML would work, but this doesn't render either:

`<a href="{frontmatter.url}">{frontmatter.url}</a>`

**Comment by tambuildsthings** [comment]
In case others find this thread as I did - my mistake was using `.md` files and not `.mdx` files. 
With .mdx files and the [MDX extension installed](https://docs.astro.build/en/guides/integrations-guide/mdx/) I can now use frontmatter variables directly in the markdown using `{frontmatter.variable_name}`.
