### ISSUE TITLE
🐛 BUG: Manifest replace takes place when not all assets are present

### ISSUE THREAD

**Issue by thepassle** [withastro/astro#3324]
### What version of `astro` are you using?

1.0.0-beta.24

### Are you using an SSR adapter? If so, which one?

netlify

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

This code in the netlify-edge adapter does not work as expected (however, it seems to accidentally work):
https://github.com/withastro/astro/blob/main/packages/integrations/netlify/src/netlify-edge-functions.ts#L11-L15

```js
if (manifest.assets.has(url.pathname)) {
  return;
}
```

For example for asset: `’/assets/asset.c2c341cd.css’`, `manifest.assets.has(url.pathname)` is always `false`

The reason for this is that during the build, the assets initially get output in the `opts.buildConfig.server` directory. Then after the build is done, these files get moved to the `opts.buildConfig.client` directory in the `ssrMoveAssets` function. 

The SSR manifest replace takes place during the `generateBundle` of the `vite-plugin-ssr` hook. At this point in time, the assets have not been moved yet by `ssrMoveAssets`, and so the manifest that gets output is not complete (it misses css files, for example)

Here you can see the manifest that gets output to `netlify/edge-functions/entry.js`, it only includes the favicon, and not the css file in `assets/`:
![Screenshot 2022-05-10 at 17 33 45](https://user-images.githubusercontent.com/17054057/167673287-c6a37d23-1896-489a-adc7-bbd0534116a3.png)
 
And here you can see that the `manifest.assets.has(url.pathname)` never seems to run at all:
<img width="1282" alt="Screenshot 2022-05-10 at 17 56 21" src="https://user-images.githubusercontent.com/17054057/167673534-251b70a9-df46-4281-8a3c-27efabf42080.png">

You can reproduce this by creating a new astro project, installing the `@astrojs/netlify` adapter, adding the edge adapter to the `astro.config.mjs`, adding a `<style is:global>` to the `index.astro`, and running a build. In the `netlify/` folder you'll see an `assets/` directory with some CSS, but if you search for the `manifest` in the `netlify/edge-functions/entry.js` file, you'll see the css assets are missing.

### Link to Minimal Reproducible Example

https://github.com/thepassle/assets-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, going to fix this now.

**Comment by matthewp** [comment]
Am I misunderstanding what the bug is here? Below screenshot, I see that the asset is listed.

<img width="1409" alt="Screen Shot 2022-05-17 at 4 27 28 PM" src="https://user-images.githubusercontent.com/361671/168904301-9dfd064e-daf4-40e6-b330-1b4fee622d7f.png">

**Comment by matthewp** [comment]
Ah, yes, I think I understand what is expected here now, thanks!
