### ISSUE TITLE
🐛 BUG:Turbolink integration with Doc template

### ISSUE THREAD

**Issue by anoopsinghbayes** [withastro/astro#3328]
### What version of `astro` are you using?

^1.0.0-beta.20

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Turbolink integration does not work for me
I also tried it with the base Docs template and it doesnt work 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yavbsq?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm having trouble reproducing this, but it seems to work fine on Stackblitz. Could you provide more detail as to what is not working?

**Comment by anoopsinghbayes** [comment]
The turbo links integration should allow client side routing but if you navigate to other pages you see a full page load

**Comment by anoopsinghbayes** [comment]
Try downloading the stackblitz example mentioned up here, the turbolink integration does not work as there is a full page reload on clicking any links in the app

**Comment by natemoo-re** [comment]
Thank you! This definitely looks broken. We'll look into what's going on here.

**Comment by FredKSchott** [comment]
This integration is really tough to maintain, and turbolinks is deprecated. @tony-sull to experiment with `swup` as an alternative, and we can potentially discuss prioritizing a first-class Astro "turbo"/"spa" mode.

**Comment by tony-sull** [comment]
Closed by #3383

[Turbolinks](https://github.com/turbolinks/turbolinks) is no longer under active development. The `@astrojs/turbolinks` integration has been deprecated.

## Looking for an alternative?

Check out [swup](https://swup.js.org/)! If you are using any `client:*` script for partial hydration, make sure to install the `@swup/scripts-plugin` to ensure components are rehydrated after a page navigation.
