### ISSUE TITLE
🐛 BUG: @builder.io/sdk-solid not working with Astro

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#3338]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

Hey Fred! I'm Sami, an engineer at Builder.io who's focused on our SDKs. I'm helping Steve out with our SolidJS + Astro example and trying to get it to the finish line!

I have a bit of an odd issue that I'm hoping you can provide guidance on 🙏🏽. Trying to import our SolidJS SDK causes an error regarding .jsx extensions (see screenshot). 

- This error does not occur with the exact same code in a Solid starter. 
- Both examples use the same vite config.
- I believe we've fixed our SDK to be a proper ESM package now.

Here is the reproduction: https://github.com/samijaber/builder/tree/fix/solidjs-sdk/examples/astro-solidjs

(You can reproduce by installing @builder.io/sdk-solid@0.0.8-3 and trying to import it in the App.jsx of an Astro project, as in the reproduction repo linked above)

Any idea why Astro would have difficulty with this? :thinkdrops:

![unknown](https://user-images.githubusercontent.com/622227/167737908-dcc8c216-f443-49ce-98be-96627fc3005f.png)

### Link to Minimal Reproducible Example

https://github.com/samijaber/builder/tree/fix/solidjs-sdk/examples/astro-solidjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
Fred probably okay to close, but revisit #3350 to make sure no remaining issues

**Comment by samijaber** [comment]
To add more context from Discord:

In the current version of the `@builder.io/sdk-solid` (`0.0.8-6`), the code gets imported just fine by Astro. However, if we attempt to `npm link` that same version of the SDK into an Astro project, then we hit the `.jsx` unknown extension issues. It seems to be tied/caused by npm linking for some reason...

**Comment by FredKSchott** [comment]
Closed by #3350
