### ISSUE TITLE
🐛 BUG: Rendering option inside select breaks the page

### ISSUE THREAD

**Issue by gkesh** [withastro/astro#3351]
### What version of `astro` are you using?

0.21

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

When you fetch an array from the server and use the array to render &lt;option&gt; tags inside &lt;select&gt;, the whole page crashes all of a sudden. The error brings the content of the style tag inside the astro (page) component in a seemingly random manner, which results in the page loosing all styling and functionality.

The issue only occurs with the &lt;select&gt; tag and using it with any other tag seems to work perfectly, for ex. &lt;ul&gt;, &lt;p&gt;, etc.

#### Source of the page rendered by Astro
![](https://user-images.githubusercontent.com/27612533/168050502-eb69ef36-5b5e-4266-8af7-ef87cafe39d9.png)

#### Screenshot of the page rendered
![](https://user-images.githubusercontent.com/27612533/168050439-d9b2a949-0e64-474a-ac4a-1a6a06500f69.png)

#### Original look of the page
![](https://user-images.githubusercontent.com/27612533/168050682-3c5520f7-aa49-45ba-b9fa-24834e31f638.png)

#### Highlighted code is where the bug occurs
![](https://user-images.githubusercontent.com/27612533/168051114-a7d826f8-db81-4c50-94d6-77dcbe013522.png)

#### Console output for the array used
![](https://user-images.githubusercontent.com/27612533/168051173-10182ef5-f190-4d99-9f88-b2dcf0ab42e5.png)

#### Replacing &lt;option&gt; with &lt;p&gt; in code
![](https://user-images.githubusercontent.com/27612533/168051352-d902b2f1-56cf-4777-875d-f409d1c742d7.png)

#### Successfully rendered in browser
![](https://user-images.githubusercontent.com/27612533/168051428-9ce76456-9090-4b44-8d87-d940e087b3c8.png)

***I have linked the minimal reproduction but I cannot replicate this issue in the sandox***

### Link to Minimal Reproducible Example

https://codesandbox.io/s/dazzling-lalande-119nig?file=/src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I see that you're on `0.21.0`, but this bug has been fixed in the latest version of `1.0.0-beta.27` (or sooner). Please upgrade to the latest and reopen if you're still running into this problem.
