### ISSUE TITLE
🐛 BUG: Styles don't compile unless touching a file

### ISSUE THREAD

**Issue by amykapernick** [withastro/astro#3359]
### What version of `astro` are you using?

v1.0.0-beta.28

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux (running in WSL)

### Describe the Bug

When starting the site it has no styles:
![image](https://user-images.githubusercontent.com/15953185/168205659-057d5d34-c4d7-4b4c-af7a-b7b6c83fbc10.png)

When saving one of the components, it pulls in any styles there, but only for that components (eg. saving src/components/partials/Layout`)
![image](https://user-images.githubusercontent.com/15953185/168205753-375e3466-fb57-4e76-bd02-29dfb7c2eeb8.png)

Have to go through and save each individual component to get their styles (eg. saving `src/components/partials/Header`
![image](https://user-images.githubusercontent.com/15953185/168205791-5de872dc-b7c6-478b-b789-447ea9136377.png)

Have stripped back and confirmed still happens and have replicated in Stackblitz

Is only an issue since updating from `beta.27` to `beta.28`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-riwbe1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Fixed by #3388, will be released shortly.
