### ISSUE TITLE
🐛 BUG: Unable to render blog post

### ISSUE THREAD

**Issue by mattgeowild** [withastro/astro#3367]
### What version of `astro` are you using?

v1.0.0-beta.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

```
 error   Unable to render Article!
  
  This component likely uses @astrojs/react, @astrojs/preact, @astrojs/vue or @astrojs/svelte,
  but Astro encountered an error during server-side rendering.
  
  Please ensure that Article:
  1. Does not unconditionally access browser-specific globals like `window` or `document`.
     If this is unavoidable, use the `client:only` hydration directive.
  2. Does not conditionally return `null` or `undefined` when rendered on the server.
  
  If you're still stuck, please open an issue on GitHub or join us at https://astro.build/chat.
    at renderComponent (file:///Users/Cain/project/dist/entry.mjs?time=1652491616037:469:15)
```

I've linked a stackblitz but I'm not sure how helpful it's going to be, as I couldn't get it to run on there. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-y4eqmn

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mattgeowild** [comment]
It may also be worth noting that before this error started popping up, it was this:
```
There are no \`integrations\` set in your \`astro.config.mjs\` file.
--
2 | Did you mean to add ${formatList(probableRendererNames.map((r) => "`" + r + "`"))}?`;
3 | throw new Error(message);
```

**Comment by mattgeowild** [comment]
Unfortunately I don't think this is the cause, my astro config file was `.mjs`. Though somehow it has magically resolved itself AND the StackBlitz has somehow disappeared, so unless someone else can replicate the error, not sure how to move forward. :(

**Comment by natemoo-re** [comment]
Hey @mattgeowild! Sorry to hear the reproduction has disappeared. Can you at least share your `astro.config.mjs` file? I'm also curious if you're able to upgrade to the latest (`1.0.0-beta.31`) and if the problem persists.

**Comment by matthewp** [comment]
This issue is quite state and we didn't get a response, so closing. Please reopen if you are still having an issue in 1.0.

**Comment by Funasitien** [comment]
Hi! I came across the same error while working with MDX. Here is the config file, the mdx file which cause the error and the error itself :

```js
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import icon from "astro-icon";

import mdx from "@astrojs/mdx";

// https://astro.build/config
export default defineConfig({
  integrations: [tailwind(), icon(), mdx()],
  site: 'https://f.dreamclouds.fr',
  base: '/AstroClouds'
});
```

```mdx
---
title: Test
description: re
logo: https://f.dreamclouds.fr/cdn/archive/title/demov1.png

layout: /src/layouts/archive.astro
---

import { ArchiveCard } from '../../components/ArchiveCard.astro'

<ArchiveCard
  title="Bannière pour le lancement de DEMOCRAFT"
  description="Avec notre lobby en arrière plan, qui est toujours présent aujourd'hui :)"
  image="https://f.dreamclouds.fr/cdn/archive/demo-bann-1.png"
  base="col-span-2"
/>
```

```logs
[ERROR] Unable to render /projects/demo because it contains an undefined Component!
Did you forget to import the component or is it possible there is a typo?
```

**Comment by MelleNi** [comment]
> ```
> [ERROR] Unable to render /projects/demo because it contains an undefined Component!
> Did you forget to import the component or is it possible there is a typo?
> ```

Getting this error too, with latest Astro. Fresh install, only added mdx support.

**Comment by Funasitien** [comment]
> > ```
> > [ERROR] Unable to render /projects/demo because it contains an undefined Component!
> > Did you forget to import the component or is it possible there is a typo?
> > ```
> 
> Getting this error too, with latest Astro. Fresh install, only added mdx support.

Remove the {} in your importe state, it should work then
