### ISSUE TITLE
🐛 BUG: Tailwind changes only appear on refresh in Firefox

### ISSUE THREAD

**Issue by inwardmovement** [withastro/astro#3369]
### What version of `astro` are you using?

1.0.0-beta.28

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Tailwind changes only appear on refresh.
This may be related to other Tailwind/Vite issues, I don't think it's a duplicate but sorry if it is.

Steps to reproduce with _Completely empty_ template after a fresh install (see log below):

1. `astro dev`
```
warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
```
2. add Tailwind classes (change A) (save) > nothing happens
3. refresh page > changes (change A) appear
4. change Tailwind classes (change B) (save) > styles reset to before change A (i.e. no styling at all)
5. refresh page > changes (change B) appear

![astro-bug](https://user-images.githubusercontent.com/9438102/169454623-48853d9c-672b-4121-836f-a6510b052534.gif)

Here is the full setup log:

```
> node --version
v16.15.0
> npm create astro@latest
Need to install the following packages:
  create-astro@latest
Ok to proceed? (y)

Welcome to Astro! (create-astro v0.12.1)
√ Where would you like to create your app? ... .
√ Which app template would you like to use? » Completely empty
✔ Template copied!
√ Would you like us to run "npm install?" ... yes
✔ Packages installed!
√ Run "astro add --yes?" This lets you optionally add component frameworks (ex. React), CSS frameworks (ex. Tailwind), and more. ... yes
√ What frameworks would you like to enable? »
√ What additional integrations would you like to enable? » Tailwind
✔ Resolving integrations...

  Astro will make the following changes to your config file:

 ╭ astro.config.mjs ─────────────────────────────╮
 │ import { defineConfig } from 'astro/config';  │
 │                                               │
 │ import tailwind from "@astrojs/tailwind";     │
 │                                               │
 │ // https://astro.build/config                 │
 │ export default defineConfig({                 │
 │   integrations: [tailwind()]                  │
 │ });                                           │
 ╰───────────────────────────────────────────────╯


  Astro will run the following command:
  If you skip this step, you can always run it yourself later

 ╭───────────────────────────────────────────╮
 │ npm install --save-dev @astrojs/tailwind  │
 ╰───────────────────────────────────────────╯

✔ Installing dependencies...

  Astro will generate a minimal ./tailwind.config.cjs file.


   success  Added the following integration to your project:
  - @astrojs/tailwind
√ Initialize a git repository? ... no
✔ Done. Ready for liftoff!

 Next steps 

You can now cd into the  project directory.
Run npm run dev to start the Astro dev server. CTRL-C to close.

Stuck? Come join us at https://astro.build/chat
```

### Link to Minimal Reproducible Example

https://github.com/inwardmovement/astro-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue @inwardmovement! A screen recording would be very helpful if you're still running into this—I know HMR + Tailwind has given us some trouble in the past, but we're working on improving our E2E tests to give us a lot more coverage here.

**Comment by inwardmovement** [comment]
@natemoo-re I added a screen recording

**Comment by inwardmovement** [comment]
Indeed it's not broken in Chrome.

**Comment by gomespereira** [comment]
I'm having the same issue on Chrome (102.0.5005.61 - arm64).

Any changes made on components on the "component" folder are only reflected if I make a change on the "index.astro" page and then save. Refreshing the page won't work.

I tested both Svelte and Alpine components.

**Comment by santicros** [comment]
Hi! I'm having the same problem in Chrome, Firefox,... I left a comment here with a video https://github.com/withastro/astro/issues/1943#issuecomment-1149727712

It happens in components created after the HMR server started, that updates on the component are not recognized.

**Comment by natemoo-re** [comment]
We recently overhauled our HMR handling for the `astro-1.0.0-rc`! From my testing this appears to be fixed, but please feel free to reopen this issue if you're still running into problems with the latest release.

**Comment by NotAgentBilly** [comment]
I still have this issue with svelte & tailwind when using client:load for svelte components.

**Comment by natemoo-re** [comment]
Sorry to hear that @NotAgentBilly! Would you mind opening a new issue? This one seemed specific to both Firefox and using Tailwind with Astro components, but yours sounds like a more general problem with Svelte + Tailwind.
