### ISSUE TITLE
🐛 BUG: Cannot reference `import.meta.env` in a Markdown file

### ISSUE THREAD

**Issue by natemoo-re** [withastro/astro#3412]
### What version of `astro` are you using?

1.0.0-beta.31

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

Any

### What operating system are you using?

Any

### Describe the Bug

See https://github.com/withastro/docs/issues/612

In the Astro docs, we reference `import.meta.env` as text but it is replaced by Astro (or Vite?) regexp, leading to an error in the file that contains it.

As a workaround, the docs team has moved any reference to `import.meta.env` into a component that looks like:

```astro
<code><Fragment set:html="i" />mport.meta.url</code>
```

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by hippotastic** [comment]
@natemoo-re Should be fixed by my PR. PTAL :)
