### ISSUE TITLE
🐛 BUG: Importing TS/TSX files using JS/JSX extensions doesn't work

### ISSUE THREAD

**Issue by Princesseuh** [withastro/astro#3415]
### What version of `astro` are you using?

astro@1.0.0-beta.31

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

(See https://github.com/withastro/rfcs/discussions/191 for more info on this problem)

Currently, importing `.ts`/`.tsx` files using `.js`/`.jsx` extensions does not work, only `.ts` (which is not recommended by TypeScript) and no extension will work. 

To be more compatible with TypeScript, we should support importing TS using JS extensions, especially considering that in the future, [TypeScript will require them](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#type-in-package-json-and-new-extensions) when using `moduleResolution: "node16"` which many users are likely to use for ESM support

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hn7v8a?file=src%2Fpages%2Findex.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Note: importing with the `.js` or `.jsx` extension works for TS files in plain Vite! [Here's a playground demo](https://stackblitz.com/edit/vitejs-vite-tpw1zs?file=src%2Fmain.tsx,index.html,src%2FbadIdea.ts&terminal=dev).

**Comment by RafidMuhymin** [comment]
@bholmesdev I never came across it but why is it even a feature? Isn't it weird?

**Comment by Princesseuh** [comment]
> @bholmesdev I never came across it but why is it even a feature? Isn't it weird?

This is how TypeScript imports work, they do it this way so you have the proper import part in your code already after transpilation
