### ISSUE TITLE
🐛 BUG: Partytown's Integration does not respect Astro's base config option

### ISSUE THREAD

**Issue by caioferrarezi** [withastro/astro#3432]
### What version of `astro` are you using?

v1.0.0-beta.31

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

With this astro configuration: 

```js
export default defineConfig({
  site: 'https://www.example.com',
  base: '/test',
  outDir: './dist/test',
  integrations: [partytown()],
});
```

Partytown's integration build its files under the `dist/test/~partytown/` directory, but the js snippet that it generates does not contain the correct path to load the service worker script.

To reproduce this, just `npm run build` and `npm run preview` on the following stackblitz project and you must see this error:
![image](https://user-images.githubusercontent.com/14830190/170084093-3c3f8aed-8189-4462-8c8c-930e34b049e3.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5ufy4j-st5s17

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! Looks like this should be a pretty simple fix for Astro's integration to automatically modify the [`lib`](https://partytown.builder.io/configuration) option to include the configured `base`.

If you'd be interested in opening a PR to make that happen, that would be greatly appreciated!
