### ISSUE TITLE
🐛 BUG: svelte styles are not loaded on HMR

### ISSUE THREAD

**Issue by suamai** [withastro/astro#3445]
### What version of `astro` are you using?

1.0.0-beta.33

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

#### To Reproduce
- Create a new project a project using the `npm create astro@1.0.0-beta.33`
- Choose the "Just the basics" template
- Choose to add the Svelte integration only
- Create a simple svelte component with styles, add it to index page
- Trigger HRM

#### Description
  When HRM is triggered - even if the styles did not change, or if the change is not in a svelte file - all styles from svelte components stop showing. After a page refresh it loads normally, but vanishes as soon as the next HMR hits.
  
  Other styles, like the ones written on `.astro` files, behave normally.
  
  The issue stated on #3219 is also happening here, but it doesn't seem to be the same thing - this issue is also happening on Chrome.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nxhq4u?file=src/components/Counter.svelte

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by retronav** [comment]
Hi, it looks like your link to the reproduction seems to be broken. Can you update it?

**Comment by suamai** [comment]
Sorry about that, I changed the url and forgot to update here. [New link](https://stackblitz.com/edit/github-nxhq4u?file=src/components/Counter.svelte) edited in. 

Also did a few more tests, and it seems like the issue starts happening only after a change has been made to an `.astro` file.

On the blitz linked, if you first change the `Counter.svelte` styles everything works fine. But, after changing and saving the `index.astro` file, any changes that triggers a HMR will cause the styles to go haywire. 

![issue3445](https://user-images.githubusercontent.com/21014034/170506698-7089c8a1-abd5-4104-860b-d50e89a2a748.gif)
