### ISSUE TITLE
🐛 BUG: line must be greater than 0 (lines start at line 1)

### ISSUE THREAD

**Issue by artiely** [withastro/astro#3447]
### What version of `astro` are you using?

1.0.0-beta.33

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

`line` must be greater than 0 (lines start at line 1)

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/docs?file=README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aFuzzyBear** [comment]
Hey @artiely  sorry but could you provide some more information about this error.
I have little go to on, can I ask are you using the `astro-icon` package by any chance?
This Error is known, and can come up sometimes when there should be a package declared to be `vite.ssr.external` within the Astro config.

```js
export default function defineConfig(){
  vite: {
    ssr: {
      external: ['package']
      }
   }
 }
```
More information can be found here:
https://docs.astro.build/en/reference/configuration-reference/#vite
And the Vite resources here:
https://vitejs.dev/guide/ssr.html#ssr-externals
https://vitejs.dev/config/#ssr-external

**Comment by IanVS** [comment]
Hi, I also got this issue, but I'm not using `astro-icon`.  I upgraded from beta.38 to beta.69, and get this error:

```
5:22:56 PM [vite] Error when evaluating SSR module /node_modules/github-slugger/index.js?v=87eab6f7:
ReferenceError: require is not defined
    at /node_modules/github-slugger/index.js?v=87eab6f7:1:15
    at instantiateModule (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50311:15)
 error   `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:16780:19)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50162:25
    at String.replace (<anonymous>)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50152:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50151:10)
    at instantiateModule (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50316:32)
/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:16780
            throw new Error(LINE_GTR_ZERO);
                  ^
```

Adding this to my vite config resolved the error:

```
vite: {
    ssr: {
      external: ["github-slugger"],
    },
  },
```

**Comment by garfieldnate** [comment]
I encountered this issue today while following the documentation on introducing an RSS feed to my site. The fix was to restart the dev server (generally speaking the dev server has to be restarted every time you install new dependencies).
