### ISSUE TITLE
🐛 BUG: Not getting Astro to work using Yarn v3 (Berry)

### ISSUE THREAD

**Issue by MartijnHarmenzon** [withastro/astro#3450]
### What version of `astro` are you using?

astro@1.0.0-beta.34

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

Yarn v3 Berry

### What operating system are you using?

Windows

### Describe the Bug

Hello. I am reporting you this issue after talking to @aFuzzyBear on Discord. [link-to-thread](https://discord.com/channels/830184174198718474/979293146531897404)

I would love to get Astro working with Yarn v3 (Berry). But when using the following steps:
- yarn set version berry
- yarn create astro

This wil resolve in the following error:
> Error: chalk tried to access #ansi-styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Any ideas?

### Link to Minimal Reproducible Example

https://martijnharm-astrotailwi-dq52nanes0o.ws-eu46.gitpod.io/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You need to use `shamfully-hoist` with yarn: https://github.com/withastro/docs/blob/edea9edff2119a0ac11365e99432b4cd205effaa/.npmrc

**Comment by MartijnHarmenzon** [comment]
> You need to use `shamfully-hoist` with yarn: https://github.com/withastro/docs/blob/edea9edff2119a0ac11365e99432b4cd205effaa/.npmr

Thanks, but tried before I created the issue. It doesn't make a difference. But maybe I am placing the file in the wrong location. What should I do with the file exactly?

**Comment by matthewp** [comment]
@MartijnHarmenzon put it in the root of your project before calling `yarn install`. You probably want to remove your node_modules folder.

**Comment by MartijnHarmenzon** [comment]
@matthewp Unfortunately it did not work. I did the following steps:
- created a folder
- added the .npmrc file
- yarn init -2
- yarn install
- yarn create astro

The above results in the same errors.

**Comment by MartijnHarmenzon** [comment]
Update..
If I add the follwing to the .yarnrc.yml file:
```
nodeLinker: pnp
pnpMode: loose
```
Astro is able to run `astro create`.

But when trying to run `yarn dev`, I get the following error. 

> The project in E:\dev\playground\astro-tailwind-alpine-v2\frontend12\package.json doesn't seem to have been installed - running an install there might help

Running the yarn install doesn't help. Any ideas?

**Comment by matthewp** [comment]
I'm not sure I can help any more, unfortunately. If you figure it out let us know and we'll update the documentation.

fwiw I would recommend not using Yarn any more. pnpm provides similar features but is more compatible with the ecosystem.

**Comment by retronav** [comment]
Hi @MartijnHarmenzon , right now the most suitable solution for getting Astro to work for Berry is to use node_modules for linking:

```yaml
nodeLinker: node-modules
```

Since we need `shamefully-hoist` in `.npmrc`, that indicated something might be using other node modules directly from `node_modules/` directory, hence why Yarn PnP is not working (just a wild guess).

**Comment by matthewp** [comment]
We've turned this into a docs issue, thanks for the suggestion @retronav! Going to track this further there: https://github.com/withastro/docs/issues/700

**Comment by njfamirm** [comment]
Hi,
Is any plan exists to support yarn pnp?

![Image](https://github.com/user-attachments/assets/1ee3706b-4008-4bc8-b82f-e1697ce41989)

**Comment by matthewp** [comment]
@njfamirm There are no plans, no.

**Comment by arcanis** [comment]
Are there specific issues with Astro & PnP? I just tried creating a new project and all seems well. I'll see later this week to add an E2E to the Yarn testsuite to make sure of it in a reproducible way, but as far as I can tell there's no need to use the node-modules linker.
