### ISSUE TITLE
🐛 BUG: Static route does not take precedence over the dynamic route

### ISSUE THREAD

**Issue by fgeierst** [withastro/astro#3451]
### What version of `astro` are you using?

1.0.0-beta.31

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Routes priority: Looking at https://docs.astro.build/en/core-concepts/routing/#route-priority-order, I think the static route should take precedence - but in my case it's the other way round (see screenshot). The dev server serves the correct file (static route) where as running the build command `pnpm run build` both locally or on Vercel overwrites the static file with the contents from the dynamic route.

![image](https://user-images.githubusercontent.com/22551442/170496791-98bf6736-2bce-4237-9ae9-8061a24f6622.png)

I can not re-create Minimal Reproducible Example with Stackblitz because it has issues with the fetch request in the dynamic route. So here is where the issue occurred originally:

- Dynamic Route: https://github.com/fgeierst/florian-geierstanger-org/blob/master/src/pages/%5B...id%5D.astro
- Static Route: https://github.com/fgeierst/florian-geierstanger-org/blob/master/src/pages/kontakt.astro
- Deployment: https://florian-geierstanger-oi5uum3t0-fgeierst.vercel.app/kontakt

### Link to Minimal Reproducible Example

https://github.com/fgeierst/florian-geierstanger-org

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aFuzzyBear** [comment]
Im Triaging this as !Important as the user has demonstrated that the defined Astro behaviour for routing isnt really being followed here.

**Comment by felixsanz** [comment]
> Im Triaging this as !Important as the user has demonstrated that the defined Astro behaviour for routing isnt really being followed here.

@tony-sull I think you already fixed this inside #2560, with PR #3407 . So maybe this issue can be closed? (check it please, I just found this issue randomly. Or maybe there is a regression).

**Comment by tony-sull** [comment]
<img width="877" alt="Screen Shot 2022-07-20 at 10 14 51 AM" src="https://user-images.githubusercontent.com/15836226/180018919-860967e3-9daf-4fe7-b283-a09adf517d51.png">

Confirmed, this doesn't reproduce in the latest `astro` beta 🎉
