### ISSUE TITLE
🐛 BUG: Braces are displayed when using HTML comments in Markdown code fences.

### ISSUE THREAD

**Issue by ota-meshi** [withastro/astro#3460]
### What version of `astro` are you using?

1.0.0-beta.35

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When you see the following markdown code fence:

````md
```astro
---
// Component Script (JavaScript)
---
<!-- Component Template (HTML + JS Expressions) -->
```
````

Unwanted curly braces are displayed, as shown below:

```astro
---
// Component Script (JavaScript)
---
{/*<!-- Component Template (HTML + JS Expressions) -->*/}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-j2bchk?file=src%2Fpages%2Fen%2Fintroduction.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! I know exactly where this was introduced, but fixing it might be a bit of a chore. I'll try to come up with a quick solution.
