### ISSUE TITLE
🐛 BUG: 404 'not found' when using SSR adapter, building then visiting site via `astro preview`

### ISSUE THREAD

**Issue by seenickcode** [withastro/astro#3472]
### What version of `astro` are you using?

^1.0.0-beta.31

### Are you using an SSR adapter? If so, which one?

netlify

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I have an astro site generated using the out of box 'blog' template. 
1. I have an `/src/pages/index.astro` page that works fine normally as well as deploying to Netlify. 
2. I then activate SSR via the instructions [here](https://github.com/withastro/astro/tree/main/packages/integrations/netlify)
3. I can successfully deploy my new SSR enabled site to Netlify (via provided example, devjourney.io)
4. The issue I'm having is that when I try to `pnpm astro build` then `pnpm astro --host localhost preview`, I get a astro 404 error when visiting my site.

### Link to Minimal Reproducible Example

https://github.com/seenickcode/devjourney

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
`astro preview` is only for SSG apps at the moment. Since every host has a different SSR API we can't make `astro preview` work that way. Instead since you are using Netlify you can use netlify's own local preview via the Netlify CLI.

**Comment by seenickcode** [comment]
Thank you.
