### ISSUE TITLE
🐛 BUG: Using any CSS styles in an .astro component causes the entire entry.mjs to be minified

### ISSUE THREAD

**Issue by hippotastic** [withastro/astro#3500]
### What version of `astro` are you using?

1.0.0-beta.38

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

With a very recent PR (https://github.com/withastro/astro/pull/3439), an error was introduced into the build process. Our `vite-plugin-build-css` is inadvertently enabling minification for the entire entrypoint build. This is caused by the following line:
https://github.com/withastro/astro/blob/d588bc4a9cc6baccf4d63ac74f2242735494391a/packages/astro/src/vite-plugin-build-css/index.ts#L91

Note that this change happens to a globally shared object `resolvedConfig` in an async function. There may be other code running in parallel that picks up the new minification setting, and as the reproduction example shows, this happens reproducibly and causes the entire `entry.mjs` to be minified.

This unwanted minification causes bad build performance and makes build errors harder to debug.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/loving-joliot-2ij52q?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by hippotastic** [comment]
CC'ing @matthewp as the bug seems to be related to your PR

**Comment by hippotastic** [comment]
Another note: I already tried moving the "reset code" performed in line 99 (`resolvedConfig.build.minify = minifyOption;`) before the block in line 94 to ensure the reset cannot be skipped by the return statement, but that didn't solve the issue. There must be more to the puzzle.

https://github.com/withastro/astro/blob/d588bc4a9cc6baccf4d63ac74f2242735494391a/packages/astro/src/vite-plugin-build-css/index.ts#L88-L101

**Comment by matthewp** [comment]
Thanks. My guess is that rollup is calling these in parallel perhaps, meaning that other renderChunk hooks are seeing the new minify option.

I wonder if switching it synchronously would avoid the problem. For ex.

```js
const minifyOption = resolvedConfig.build.minify; 
 	if (minifyOption === false) { 
 		resolvedConfig.build.minify = 'esbuild'; 
 	} 
 	const resultPromise = renderChunk.apply(this, args); 
        resolvedConfig.build.minify = minifyOption;
        const result = await resultPromise;
 	if (typeof result === 'string') { 
 		return { 
 			code: result, 
 		}; 
 	} 
 	 
 	return result || null; 
```

**Comment by matthewp** [comment]
Another solution is to create another Vite plugin that runs `post` that minifies just CSS in `generateBundle`. This would mean not needing to monkey patch that plugin.
