### ISSUE TITLE
🐛 BUG: Astro gives different CLI output with no --host flag and --host flag

### ISSUE THREAD

**Issue by isaac-mcfadyen** [withastro/astro#3523]
### What version of `astro` are you using?

v1.0.0-beta.40

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

macOS

### Describe the Bug

When running `dev` with no `--host` flag (localhost only) the Astro CLI gives this output:
```
  🚀  astro  v1.0.0-beta.40 started in 122ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
  ▶ This is a  beta  prerelease build
    Feedback? https://astro.build/issues
```

However, when run with a `--host` flag the output looks like this:
```
  🚀  astro  v1.0.0-beta.40 started in 122ms
  
  ▶ This is a  beta  prerelease build
    Feedback? https://astro.build/issues
```

Notice on the second one, there's no message about `Local` or `Network`. This led me to believe that Astro had hung and was not running at all, when in fact it was running just fine.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5q7luq?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! I know @bholmesdev did a lot of work here, so he might be able to resolve this quickly when he's able to look at it.

**Comment by bholmesdev** [comment]
@isaac-mcfadyen  Hm, I'm unable to replicate this issue in the "Link to Minimal Reproducible Example" you sent. It doesn't show up locally on my machine using `yarn` either... I'm wondering if we fail to find a network port to expose on and bomb out silently in the dev server logs 🤔 

Do you mind trying again on the latest beta?

**Comment by bholmesdev** [comment]
@isaac-mcfadyen Mmm okay, that could be messing with things. I'm unable to replicate running `astro dev --host 0.0.0.0 --port 3001 --experimental-integrations` on its own, so I'm curious if `nodemon` is breaking our request for network interfaces. Have you tried running without the nodemon shell?

**Comment by isaac-mcfadyen** [comment]
> Also as an aside: I'm not sure why you need nodemon here?

Main reason is WindiCSS's HMR (or rather, lack of it haha). For some reason WindiCSS doesn't pick up new classes without restarting the server. There was an Issue open but the suggestion was just to move to a native Astro integration, which hasn't happened yet. My workaround was `nodemon`.

A quick test shows that it's not `nodemon` though 🤔 

Output without `nodemon`, running the same command (notice the missing Local/Network part):
```
  🚀  astro  v1.0.0-beta.41 started in 141ms
  
  
  ▶ This is a  beta  prerelease build
    Feedback? https://astro.build/issues
```

**Comment by bholmesdev** [comment]
@isaac-mcfadyen Gotcha, thanks for confirming! I'm working on a PR to keep displaying the local URL when we can't detect your network devices. There's a number of reasons why Node might fail to find a network IP, but they're all beyond my pay grade 🙃

We also used Vite's internal logic for generating these logs. I'm curious if you see the same empty log [spinning up a Vite app](https://vitejs.dev/guide/#trying-vite-online) and running `vite dev --host` 🤔 

 I'm also _hopeful_ the HMR fixes in beta 41 can help with your WindiCSS issues. That sounds like a separate issue worth investigating for sure!
