### ISSUE TITLE
Website breaks after running build command

### ISSUE THREAD

**Issue by david-gagne** [withastro/astro#3524]
### Description
Running ```npm run build``` or ```npm run preview``` causes my Astro site to break in appearance and function from the development view. 

##### Website after running ```npm run dev```:
![Website screenshot](https://workflowy.com/file-proxy/file/gAAAAABim4k6yZyYCcchDiqJF6Pw6FfSeKllY5gM4tA0qJOqpC2eOZwZdAFdE_okOdyT6TSLWvz8jPORAK7B5FF_Ed4B0K_2VHk3AX7M92OrQ2DauO7KYG07oK5jkDkGVk4YVNuvIB6nZ4rMOYppI7q9wu-olz6zq8CSFhPkdm_E-8MNl1yEmBhY-FXjHpfsQZgNjr50BaJoxF-dYSraVdagtqpqugi83TuR6hTNw-gv_GbmfusvEPC-wkdhioMbSZ4-vMOqajFU_a1yzDf_9yEJjZfJKpIX9B0U21aF43bWgXmLmtWonqmDhokTeU883DRHyQORatr3nYpU3u3X7S8bfQZOTyHSFDq72NIqBW5vfYVdGITeXcgq91dYzOyCbR9qlwM1GewnCKZeLcHhZFCqbLMGZ1DVadFhrcTCZaBi2iEuGFxPot4sYKnYYnEUNMfwIdtvRY94PXnIRrwvDcE3oVh_i9Tk_pGqGt-eEGTqyefBMMJ4b6_0ACYjuUY-3nFaPd7U5-zkYu4HyDilO-rnYrdJgiXhLQ==/)

##### Website after running ```npm run build```:
![Website screenshot](https://workflowy.com/file-proxy/file/gAAAAABim4q5h8Nj97QElit7K1KopfXUCxQlMJ6L_CTM5bm069CHkqNP7JvnyEUs-t1l-VAaS3qP5_KvB10KdeuWlDzRSi4cyo0nlxn5rbhb_4uQ5ktLDBo_XRFTStnuPTy3kX_RYriB0J6hfcZk_YBbdgzCS5oYZbnNv6CB0AEJwQ_gUEJE_Bycc9i8TVN-PY86jvT6BdZxl_QiUCbJ-kRcJg2O5MRvXowIrK9C57ZdaYUOfxH9onybrUJQWqN1DBWN0Z7KRVoKOk49Q1gXoUfImg71zY2GY3-24RVJdUb9hKyAlX-PIQonUyX2CYB8xycDKGA57w3JlYBrsxH-o0NB91WQHNJKUrOL5QAHOKV8qtw4aDhp3ktj6vDqPoJ0N1bFwp7oKW-8zXK5AzB5mEZFNwy3dW4YYhQC8tQcm0xBKhx3FUgEOYq6Ad4ws8Ywj8bsw8N5qt6Plfe965akTtnTTAiBCRVf15uuEKISDoY9eKcNt5KqSfXHuNzFSYhoJpCLE3jsvDSo/)

#### Setup
My Astro project is set up using the "Just the basics" template with 1.0.0-beta.33". I'm working on a MacBook Air (M1, 2020) running macOS Monterey.

#### To Reproduce
- Install Astro "Just the basics" template
- Run ```npm run build```
- Open index.html in the browser

**Comment by delucis** [comment]
OK, done!

Could you try updating your project to the latest Astro beta version to see if that fixes your issue? I believe we’re on 1.0.0-beta.40 now.

**Comment by david-gagne** [comment]
Hey @delucis, thanks for responding so quickly. Hang tight.

**Comment by david-gagne** [comment]
@delucis, I updated to the latest version but still no luck. I've tried this same process with one of the Astro starter templates, and the results are the same. It seems like everything from files to links don't map correctly during the build step.

**Comment by delucis** [comment]
Ohhh, hang on! I think I missed your very last bullet point:

> - Open index.html in the browser

Are you double clicking or otherwise opening the HTML file directly in the browser? Often that won’t pick up local assets like CSS etc. (browsers treat things differently when they’re loaded using the `file://` protocol instead of `https://`)

You can run `npm run preview` after `npm run build` to spin up a local server that will serve the built files like you would when hosting them. Does that fix things for you?

**Comment by david-gagne** [comment]
@delucis, no I'm using the Live Server extension in VS Code. But I've also tried deploying my site on Netlify with the same result.

**Comment by david-gagne** [comment]
Hey @delucis, everything appears to be running just fine now. I did the last thing you suggested and that seemed to do the trick. From now on. I'll use the ```npm run preview``` after ```npm run build``` to ensure things work as intended. Thanks for helping me through it!

**Comment by Achour** [comment]
rm -rf .astro .vercel and then commit & push fixed the issue for me
