### ISSUE TITLE
🐛 BUG: can't use the YAML pipe for a multiline `setup` in markdown frontmatter...

### ISSUE THREAD

**Issue by nuotsu** [withastro/astro#3527]
### What version of `astro` are you using?

1.0.0-beta.40

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Using the pipe for multiline values in `setup` in markdown frontmatter:
```
---
setup: |
  import Test from '../Test.svelte'
---
```

causes the following error:
```
can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 1:
```

Works in the repro but not in a bare-minimum local environment (just an .md file and a basic Svelte component)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wxeaud?file=src%2Fpages%2Ftest.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hey @nuotsu! I actually ran into a similar error and realized that my YAML had a parsing error. As a fix, I've opened https://github.com/withastro/astro/pull/3557 to improve how we surface YAML errors.

The actual fix here https://stackblitz.com/edit/github-wxeaud-k8hihj?file=src%2Fpages%2Findex.astro,src%2Fpages%2Ftest.md is to wrap "Test" in quotes. 

Looks like we have a bit of an unrelated issue with URL, which I'll track separately.
