### ISSUE TITLE
🐛 BUG: `<a href="URL">URL</a>` tags in Markdown files generate double links

### ISSUE THREAD

**Issue by andygrunwald** [withastro/astro#3529]
### What version of `astro` are you using?

v1.0.0-beta.40

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When you clone the **Astro Starter Kit: Blog with Multiple Authors** example and have block posts where raw HTML is part of the content like:

```html
<ul>
    <li>Pieter Levels <a href="https://levels.io/async/">https://levels.io/async/</a></li>
</ul>
```

Astro generates content like

```html
<ul>
<li>Pieter Levels
<a href="https://levels.io/async/"></a><a href="https://levels.io/async/">https://levels.io/async/</a>
</li>
</ul>
```

It seems that if the content of the `<a>`-tag is also a URL, the markdown parser automatically generates an additional (empty) `<a>` tag.

See screenshot:
![Screenshot from 2022-06-06 12-20-00](https://user-images.githubusercontent.com/320064/172143499-30e9fd32-c07f-4f1f-b29b-c6974e4d4feb.png)

### Expected result

Output generation like

```html
<ul>
<li>Pieter Levels
<a href="https://levels.io/async/">https://levels.io/async/</a>
</li>
</ul>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tulupu?file=src/pages/post/chapter-i.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This definitely looks like a regression with our Markdown handling! We're still trying to track down a few remaining issues like this. It's a high priority to fix!

**Comment by andygrunwald** [comment]
@natemoo-re In v1.0.0-beta.31, it is working as expected. In v1.0.0-beta.36 it is broken (like described here).

I assume https://github.com/withastro/astro/commit/cfae9760b252052b6189e96398b819a4337634a8 might be a good start (part of [astro@1.0.0-beta.33](https://github.com/withastro/astro/releases/tag/astro%401.0.0-beta.33)).
