### ISSUE TITLE
🐛 BUG: `?raw` doesn't work with import.meta.glob() and import.meta.globEager()

### ISSUE THREAD

**Issue by felixsanz** [withastro/astro#3531]
### What version of `astro` are you using?

v1.0.0-beta.40

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

`import.meta.glob` works fine, but when using `import.meta.globEager` i get this error:

```
error   `line` must be greater than 0 (lines start at line 1)
```

I created this test case but it doesn't work on codesandbox because `import.meta` doesn't work there, but it's a reproducible minimal example.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/priceless-mayer-rhmb7c?file=/src/i18n.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by felixsanz** [comment]
Reopening because passing `?raw` to `import.meta.glob` or `import.meta.globEager` doesn't work, it returns an empty object.

```js
const imports = import.meta.glob('../components/**/*.ftl')
console.log(imports)

/*
{
  '../components/ui/About/en.ftl': [Function: ../components/ui/About/en.ftl],
  '../components/ui/About/es.ftl': [Function: ../components/ui/About/es.ftl]
}
*/
```

```js
const imports = import.meta.glob('../components/**/*.ftl?raw')
console.log(imports)

/*
{}
*/
```

So.. if using `?raw`, nothing is returned. If not using it,... obviously it crash.

**Comment by natemoo-re** [comment]
Hmm interesting, I wonder if there's still a Vite transformation happening here. Definitely a suspicious edge case in one of our Vite plugins.

**Comment by sibbng** [comment]
This is intentional. Check https://github.com/vitejs/vite/issues/7017 for more info.

Provide the `raw` query like this:
```ts
const modules = import.meta.glob('./dir/*.js', { as: 'raw' })
```

Docs: https://vitejs.dev/guide/features.html#glob-import

**Comment by felixsanz** [comment]
it works! thanks
