### ISSUE TITLE
🐛 BUG: Ignore hidden files/folders with create-astro

### ISSUE THREAD

**Issue by tony-sull** [withastro/astro#3538]
### What version of `astro` are you using?

1.0.0-beta.41

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When running `create-astro` inside an cloned empty git repo, I get a CLI error that `.` is not empty (it sees the .git folder)
<img width="751" alt="Screen Shot 2022-06-06 at 3 11 38 PM" src="https://user-images.githubusercontent.com/15836226/172240548-f02f5eff-ee60-4de2-8909-d22548b06923.png">

### Link to Minimal Reproducible Example

na

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nickisnoble** [comment]
... so what is the preferred method of switching an existing project to Astro (eg, want to migrate on a `dev` branch of an existing repo).

Do I need to (annoyingly) start a whole separate project and manually pick through things?

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/4805
