### ISSUE TITLE
🐛 BUG: No static build output when using`@astrojs/rss`

### ISSUE THREAD

**Issue by philipp-tailor** [withastro/astro#3550]
### What version of `astro` are you using?

1.0.0-beta.42

### Are you using an SSR adapter? If so, which one?

None (but also does not work with SSR adapter)

### What package manager are you using?

npm, yarn

### What operating system are you using?

Mac

### Describe the Bug

When adding `pages/rss.xml.ts` (or `pages/rss.xml.js`), `yarn build` no longer generates static routes.

This can be verified by downloading the linked stackblitz, and running `yarn build`:
- as is --> no static HTML output ❌,
- and after deleting `pages/rss.xml.js` --> static HTML output ✅

The docs on https://docs.astro.build/en/guides/rss/#using-astrojsrss-recommended suggest that using `@astrojs/rss` should work with and without SSR adapter. I also tried adding the Netlify adapter, with a similar result: Not even the `netlify/functions/` folder was created.

The build command output also reflects this: "generating static routes" does not show any outputs when `pages/rss.xml.js` is present:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/47689073/172463875-1c58b226-0376-444d-b6d4-ad314ee3d53c.png">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ebz6gf-jkeapy?file=src/pages/rss.xml.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Marking this as a `p2-nice-to-have` - it isn't technically a broken feature, but there's opportunity for a much better developer experience here as we're getting everything buttoned up for 1.0!

**Comment by philipp-tailor** [comment]
Thank you for the blazing-fast response, and sorry for having reported a bug in my code as Astro bug. I did not mean to misuse bug report for personal support.

**Comment by matthewp** [comment]
The pattern in this bug no longer works post-1.0 because calling `module.default()` doesn't give you the content of the .md file now. Instead you pass `items` to the RSS integration. Closing as I don't think there's anything to be done about this now.
