### ISSUE TITLE
🐛 BUG:  "failed to load module for ssr" even when the component exists

### ISSUE THREAD

**Issue by shubhamjain** [withastro/astro#3555]
### What version of `astro` are you using?

1.0.0-beta.42

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

Yarn

### What operating system are you using?

Mac

### Describe the Bug

I have markdown file, which is like this:

```
---

title: "Accepting Technical Debt As Important As Fighting It"
date: "2019-09-15 10:46:34 +0530"
permalink: "/2019/09/15/accepting-technical-debt/"
category: "post"
setup: |
    import Tweet from "../components/Tweet";

---        

I was sixteen when I first read ...
```

Tweet is a custom component in the "components" folder. I get the following error after multiple restarts:

```
21:16:50 [vite] Error when evaluating SSR module /Users/shubhamjain/Projects/personal-blog/src/posts/2019-09-15-i174-accepting-technical-debt-as-im.md:
Error: failed to load module for ssr: ../components/Tweet
    at instantiateModule (/Users/shubhamjain/Projects/personal-blog/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:50199:15)
 error   failed to load module for ssr: ../components/Tweet
    at instantiateModule (/Users/shubhamjain/Projects/personal-blog/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:50199:15)
21:17:08 [astro] reload /src/posts/2019-09-15-i174-accepting-technical-debt-as-im.md
21:17:08 [vite] Error when evaluating SSR module /Users/shubhamjain/Projects/personal-blog/src/posts/2019-09-15-i174-accepting-technical-debt-as-im.md:
Error: failed to load module for ssr: ../components/Tweet
    at instantiateModule (/Users/shubhamjain/Projects/personal-blog/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:50199:15)
 error   failed to load module for ssr: ../components/Tweet
    at instantiateModule (/Users/shubhamjain/Projects/personal-blog/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:50199:15)

 ```

It's not an issue with component because, it throws an error even with empty component. It's not an issue with path. I have triple checked it, and also tried variations but none of them work. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-g8tmux

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm not sure if the linked reproduction is the same issue as what you're describing? 

Looks like you're referencing a monorepo package, but by relative path (`../../../../packages/my-component/Button`) rather than by the module specifier (`@examples/my-component/Button`). I wouldn't expect that to work because Vite doesn't know about any files outside of your project root.

Also you need to reference files by the full extension (include `.astro`) for them to be resolved. In this case, you have an `export` map but the relative path specifier won't read from the export map.

**Comment by shubhamjain** [comment]
My bad! Specifying ".astro" fixes the issue. I don't know why I assumed extension is not needed. Maybe from my experience using require and import that doesn't need ".js" to be specified. 

Feel free to close.

Minor Suggestion: Maybe we can add a little warning/suggestion in the message: "Did you mean Button.astro?"
