### ISSUE TITLE
🐛 BUG: HMR destroy scripts (and changes made) because they don't re-run on HMR update

### ISSUE THREAD

**Issue by felixsanz** [withastro/astro#3556]
### What version of `astro` are you using?

v1.0.0-beta.42

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Inserting scripts that make changes to the page (DOM), like this...

```js
    <script is:inline>
      const link = document.createElement('link')
      link.rel = 'stylesheet'
      link.href = `/themes/default.css`

      document.head.insertAdjacentElement('afterbegin', link)
    </script>
```
...are lost on HMR because HMR reloads the entire page and scripts are not re-run because they hasn't changed.

As discussed on discord,  a solution could be a new directive like <script is:fixed> that re-runs the script on HMR and is stripped off on building. HMR algorithm should just re-run those scripts like if they were changed

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rqmsac-zbs3uf

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Chatted about this on Discord. We probably need some way for authors to specify that they want certain scripts to rerun when HMR happens, unless we can find a way scope HMR updates to component boundaries.

Will need to discuss this with the team.

**Comment by natemoo-re** [comment]
Marking this as closed by https://github.com/withastro/astro/pull/3932. We'll now perform a full reload if scripts are present.
