### ISSUE TITLE
🐛 BUG: Dev server doesn't return UTF-8 compatible responses on non-html-pages

### ISSUE THREAD

**Issue by felixsanz** [withastro/astro#3573]
### What version of `astro` are you using?

v1.0.0-beta.42

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

According to [Non-HTML Pages](https://docs.astro.build/en/core-concepts/astro-pages/#non-html-pages) docs you can create an endpoint like this:

```js
export async function get() {
  const body = { test: 'Código' }

  return {
    body: JSON.stringify(body),
  }
}
```

Problem is... when using thing like `ó` (which is essential in Spanish), the dev server doesn't respond with UTF-8 compatible characters. So this piece of code returns `{"test":"CÃ³digo"}`

I tried passing a `headers` object with `Content-type` but doesn't help, seems like its ignored. This affects almost all languages and symbols.

Example output: https://01nfzn.sse.codesandbox.io/whatever.json

When building, the file is created with this content: `{"test":"Código"}` so at least it doesn't affect production code, but the dev server should replicate this, and **not only output UTF-8, but also accept a headers** object because for example i want my `src/pages/manifest.webmanifest.ts` file to return `application/manifest+json` as `Content-type`.

### Link to Minimal Reproducible Example

Test case: https://codesandbox.io/s/nostalgic-haibt-01nfzn

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by retronav** [comment]
Hi @felixsanz, the type definition of `get` function exported for non-HTML pages is:
https://github.com/withastro/astro/blob/c54b024803b3ae43826a48c11f7c744b866501a5/packages/astro/src/%40types/astro.ts#L892-L894

Which expects a partial `Response` object, in which you can set headers. You were almost there, however, headers in a `Response` object are provided using the [`Headers` class](https://developer.mozilla.org/en-US/docs/Web/API/Headers), and not using a object.

To provide a quick example of all this, I wrote the exact JSON page with the headers:
```ts
export async function get() {
  const body = { test: 'Código' };
  const headers = new Headers({
    'Content-Type': 'application/json; charset=utf-8',
  });

  return {
    body: JSON.stringify(body),
    headers,
  };
}
```

Which then is rendered in the intended manner. 
![JSON file opened in Firefox which reads《 {"test":"Código"} 》](https://user-images.githubusercontent.com/52596591/173181414-744420c6-d432-4cec-ad9e-e64383f9a840.png)

That said, this can be documented better IMO, including making the `APIRoute` type public.

**Comment by felixsanz** [comment]
Thank you for helping. I can't get it to work :/

https://codesandbox.io/s/elastic-meninsky-v8n8pn?file=/src/pages/whatever.json.ts

![1654947258](https://user-images.githubusercontent.com/6182099/173186171-cd279898-c146-408c-83a5-98e40ed3dbaa.png)

https://v8n8pn.sse.codesandbox.io/whatever.json

![1654947271](https://user-images.githubusercontent.com/6182099/173186173-2a7061ea-ab79-4885-9d63-2d0b58eb4f41.png)

What i'm doing wrong? I copied your code

**Comment by retronav** [comment]
Looks like it isn't setting the headers 😕 
But I am still getting the correct text from the same sandbox

![image](https://user-images.githubusercontent.com/52596591/173186309-4f204e24-2aed-4718-a754-f6e0bf9b9b33.png)

Which browser are you using? I am using Firefox Developer Edition 102.0b6 on Windows 11.

**Comment by felixsanz** [comment]
I'm using Linux. In Firefox this is correct, but in Brave and chrome is not. Can you try Chrome please?

**Comment by felixsanz** [comment]
There are 2 possible output types: `EndpointOutput` and `Response`.

`EndpointOutput` doesn't contain `headers`:

https://github.com/withastro/astro/blob/c54b024803b3ae43826a48c11f7c744b866501a5/packages/astro/src/%40types/astro.ts#L888-890

And `Response` doesn't contain `body`:

https://github.com/withastro/astro/blob/c54b024803b3ae43826a48c11f7c744b866501a5/packages/astro/src/%40types/astro.ts#L143-145

```
Type '{ body: string; headers: Headers; }' is not assignable to type 'ResponseInit & { readonly headers: Headers; }'.
Object literal may only specify known properties, and 'body' does not exist in type 'ResponseInit & { readonly headers: Headers; }'.ts(2322)
```

So this is never going to work :/

**Comment by retronav** [comment]
> I'm using Linux. In Firefox this is correct, but in Brave and Chrome is not. Can you try Chrome please?
> 
> Anyway the problem is... that the headers thing is not working. You could probably remove it and in Firefox will still work.

Can confirm, but like you said, that was going to happen because headers were never set.

**Comment by retronav** [comment]
OK, I missed the fact that `Response` can be used as a constructor too. Updated code:
```ts
export async function get() {
	const body = { test: 'Código' };
	const headers = new Headers({
		'Content-Type': 'application/json; charset=utf-8',
	});

	const resp = new Response(JSON.stringify(body), { headers });

	return resp;
}
```

Result in Edge:
![image](https://user-images.githubusercontent.com/52596591/173192216-407ae46b-1809-41b9-abfd-522d7e40a440.png)

This time, the `Content-Type` header is correctly set:
```http
Access-Control-Allow-Origin: *
content-type: application/json; charset=utf-8
Date: Sat, 11 Jun 2022 14:33:13 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```

So using `Response` makes the non-HTML page work as intended, as opposed to using the `body` method.

**Comment by felixsanz** [comment]
> ```ts
> new Response(JSON.stringify(body), { headers });
> ```

That works perfect!  Thanks so much for helping me debug the issue. I'll submit a PR to docs

**Comment by natemoo-re** [comment]
I agree that `new Response()` makes the most sense to document, but I'm guessing this is not the case because SSG doesn't maintain any of the headers or other data, whereas for SSR we do.

I'm going to tag this issue to be discussed with the core team.

**Comment by felixsanz** [comment]
> I agree that `new Response()` makes the most sense to document, but I'm guessing this is not the case because SSG doesn't maintain any of the headers or other data, whereas for SSR we do.
> 
> I'm going to tag this issue to be discussed with the core team.

The dev server needs it or we are going to develop a different version that the expected to serve in production

**Comment by natemoo-re** [comment]
**Notes from Triage Call**

- This has a workaround, but we probably need better docs on this
- For SSR mode, we should default endpoints using the `body` object to `utf-8`.
- If you are creating a `Response` manually, you must set the `charset` yourself.
