### ISSUE TITLE
🐛 BUG: Client side <script/> tags in Astro components break when using named imports. 

### ISSUE THREAD

**Issue by shaunchander** [withastro/astro#3576]
### What version of `astro` are you using?

1.0.0-beta.44

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

MacOS

### Describe the Bug

🐛 Client-side `<script />` tags present in Astro components are not bundled when importing said component using named imports, ie:

```
import { ComponentName } from "@components/ComponentName"
```

The expected behavior is that any, non-inlined `<script />` tag in a named Astro component should be bundled just as it is normally when using a default exported Astro component.

⚠️ This bug does not affect inlined-scripts, they work as expected whether you are using a default exported Astro component or a named one.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cbpkqr?file=src/pages/index.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I would love for @matthewp or @bholmesdev to weigh in on this, I think we're aware that there are problem here but maybe not aware of this particular one.

**Comment by matthewp** [comment]
I think this will likely be fixed when we fix https://github.com/withastro/astro/issues/3217. It's the same core issue, that our discovering of what to build in the client can't pass through non-astro files.
