### ISSUE TITLE
🐛 BUG: error: Expected a closing tag for `<测试>`  before the end of `paragraph`

### ISSUE THREAD

**Issue by xcsnowcity** [withastro/astro#3577]
### What version of `astro` are you using?

1.0.0-beta.40

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

when a .md file contains some chinese characters(maybe?) and they are wrapped with `<` and `>`, then run `npm run build`, there will be an error：

> Failed to parse Markdown file
> Expected a closing tag for `<测试>` before the end of `paragraph`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qmxszv-z3etkl?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This occurs with any characters wrapped in `<` and `>`, because we aren't able to determine that they are NOT a component. The solution is to use the HTML entities `&lt;` and `&gt;` instead of the raw `<` and `>`.

https://stackblitz.com/edit/github-qmxszv-6dxqrm?file=src%2Fpages%2Fbook%2Ftest.md

**Comment by xcsnowcity** [comment]
> This occurs with any characters wrapped in `<` and `>`, because we aren't able to determine that they are NOT a component. The solution is to use the HTML entities `&lt;` and `&gt;` instead of the raw `<` and `>`.
> 
> https://stackblitz.com/edit/github-qmxszv-6dxqrm?file=src%2Fpages%2Fbook%2Ftest.md

But I have test some other situation, where I don't change `<` and `>` to `&lt;` and `&gt;`, but it still works and no error show up.

https://stackblitz.com/edit/github-qmxszv-hxydrz?file=src/pages/book/test.md
