### ISSUE TITLE
🐛 BUG: Unexpected token ',' when running Astro build

### ISSUE THREAD

**Issue by DRD161** [withastro/astro#3580]
### What version of `astro` are you using?

1.0.0-beta.44

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Node version?

v16.13.1

### Describe the Bug

When running `astro build` I am getting the following error:

` 
error   Unexpected token ','
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run build" terminated with exit code: 1.
`

![image](https://user-images.githubusercontent.com/29187448/173241996-8a267065-ef5c-4d4c-a2f0-e115d6237d6c.png)

Here is a [StackBlitz](https://stackblitz.com/edit/github-wg7pgx-zpirw9?file=src/pages/index.astro) link as well. The error that appears is slightly different which I'm assuming is due to being in the StackBlitz container but I figured I'd add it in case it's helpful.

### Link to Minimal Reproducible Example

https://github.com/DRD161/astro-portfolio.git

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arimgibson** [comment]
Having the same issue myself, looking into it right now

**Comment by arimgibson** [comment]
Looks like this issue is occuring when the `dist/chunks` files are being created. This is the invalid JS that was generated on my side, showing those invalid commas after the `const` definition semicolons.

```js
/* Pure CSS chunk chunks/chunk.bb64a152.mjs */ export const $ = {};,export const a = {};,export const b = {};,export const c = {};,export const d = {};,export const e = {};
```

**Comment by natemoo-re** [comment]
Thanks for filing an issue and for digging into this! I suspect this is an edge case in our build logic. Pinging @matthewp for his insights.

**Comment by DRD161** [comment]
> Not sure if @DRD161 had the same experience, but I encountered no issues running the astro dev script

@arimgibson yep same here, running `astro dev` gave me no issues.

**Comment by tony-sull** [comment]
@matthewp [here](https://stackblitz.com/edit/github-agxelg) is a simplified reproduction

The bug is specific to importing styles from `swiper` - importing only one of `swiper`'s CSS files works fine, but the build breaks when a second or third CSS file is imported from the package

**Comment by matthewp** [comment]
Figured this one out, PR will be coming soon.

**Comment by matthewp** [comment]
Fix in https://github.com/withastro/astro/pull/3595

**Comment by DRD161** [comment]
Awesome! Thanks for the quick turn around on this!

**Comment by arimgibson** [comment]
Fixed for me as well @matthewp , thank you!
