### ISSUE TITLE
🐛 BUG: Path aliases don't work inside <style> blocks

### ISSUE THREAD

**Issue by SachaG** [withastro/astro#3581]
### What version of `astro` are you using?

1.0.0-beta.44

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac OS

### Describe the Bug

Path aliases defined inside `tsconfig.json` don't work inside an Astro `<style>` block. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3n5sn9?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is a limitation of Vite's CSS compilation which does not do aliasing. Going to close as there's nothing actionable to be done on our side. I recommend filing an issue with them.
