### ISSUE TITLE
🐛 BUG: api route request body is empty with node adapter SSR

### ISSUE THREAD

**Issue by Scalamando** [withastro/astro#3619]
### What version of `astro` are you using?

1.0.0-beta.40, 1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

Node (v1.2.0)

### What package manager are you using?

npm, yarn classic

### What operating system are you using?

WSL Debian / Windows

### Describe the Bug

Received POST requests that should contain a json body (and a `Content-Type: application/json` header) have an empty body in SSR mode using the node adapter.

Example request:
```js
const response = await fetch("/test", {
  method: "post",
  body: JSON.stringify({ 
    test: "Baby don't hurt me, no more"
  }),
  headers: { "Content-Type": "application/json" }
});
```

The api endpoint receives the following:
```js
export const post : APIRoute = async ({ request }) => {
  console.log(request.body); // Logs: null
  const { test } = await request.json(); // SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

  ...
}
```

Run the following in the StackBlitz console:
- `npm run build`
- Ignore the premium warning
- `node server.mjs`

Just to be sure I checked the response using the `express.json()` middleware and the body is available there

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1qng5x?file=src/pages/test.ts

### GitHub Repo with MRE

https://github.com/Scalamando/astro-ssr-node-issue-repro

Simply run `yarn && yarn start-ssr`

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Scalamando** [comment]
Just did some more testing and it looks like no form of body is received at all.

I did tests for
- Multipart Form Data
- Form URL Encoded
- Plain Text

with Insomnia and none of them ever showed up in `request.body`.

I also tried a raw `http` server:
```js
http.createServer(function(req, res) {
  ssrHandler(req, res, err => {
    if(err) {
      res.writeHead(500);
      res.end(err.toString());
    } else {
      // Serve your static assets here maybe?
      // 404?
      res.writeHead(404);
      res.end();
    }
  });
}).listen(8080);
```

but that didn't change anything.

Did really nobody notice this yet? I'm getting the feeling that I did something wrong.

**Comment by Scalamando** [comment]
After looking a bit more into it I've found the reason for this.

https://github.com/withastro/astro/blob/main/packages/astro/src/core/app/node.ts#L8
```js
function createRequestFromNodeRequest(req: IncomingMessage): Request {
	let url = `http://${req.headers.host}${req.url}`;
	const entries = Object.entries(req.headers as Record<string, any>);
	let request = new Request(url, {
		method: req.method || 'GET',
		headers: new Headers(entries),
        body: new ReadableStream(req)
	});
	return request;
}
```

If the request is a node request (http.IncomingMessage), the body is omitted in the conversion to a fetch api request. After looking into this issue even more, the solution seems to be non-trivial and/or I lack the knowledge to tackle this problem.

**Comment by Scalamando** [comment]
Sounds good, no worries!

For anybody else that is facing this problem: While suboptimal I solved this temporarily by sending the stringified json data in a query string and parsing it in the endpoint:

Client
```ts
await fetch(
    `/register?data=${encodeURIComponent(JSON.stringify(dataObj))}`,
    { method: "post" }
);
```

API Endpoint
```ts
const { data } = Object.fromEntries(new URL(request.url).searchParams);
```

**Comment by 314ga** [comment]
I am having a similar issue, using node adapter SSR with a hybrid output target. I am using an example of Firebase authentication ([Astro Firebase](https://docs.astro.build/en/guides/backend/google-firebase/#adding-authentication-with-firebase)). It works perfectly with "npm run dev", hovewer when I run "npm run build" and "node ./dist/server/entry.mjs", I am able to access only plain URL. I tried the workaround provided by [Scalamando](https://github.com/Scalamando) but the query string disappears too. Any idea what am I doing wrong?

CLIENT:
` const response = await fetch(`/api/auth/login?token=${idToken}`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${idToken}`,
        },

      });`

SERVER:
`export const get: APIRoute = async ({ request, cookies, redirect }) => {

 if(!request.headers.get("authorization"))
  {
    return new Response(
        JSON.stringify({
        error: request.url,
        author: request.headers.get("authorization"),
        referer: request.headers.get("referer"),
        cookie: request.headers.get("cookie")
        }),
      { status: 401 }
    );
  }`

RESPONSE:  {"error":"http://localhost:3000/api/auth/login","author":null,"referer":null,"cookie":null}

**Comment by tayhimself** [comment]
@314ga Did you find a fix for the issue? I'm also seeing this issue. Works with the dev server, but on prod there is no body in the form request. node adapter, server output and can't get the body.

**Comment by tayhimself** [comment]
I'd like to quickly followup in case @matthewp is listening so that my misunderstanding can be cleared up.

Request.formdata() and request.json() don't work while request.text() and request.arraybuffer() are fine. 

When I use the formData library, I couldn't get it to work because of request.on() which reminded me that the request object isn't a node request but a fetch request. Anyway, I think I am just confused as to why formData works in dev and not in prod and what the correct way to go about it is. I have a workaround but I'd rather do it the right way without brittle/dangerous parsing.

**Comment by rimzzlabs** [comment]
Closed the issue and never give the solution, oh what A great community, I just tried Astro for the first time, but then discovered the same problem just like this issue, everytime I hit the api, it always shows me dis error:
![image](https://github.com/withastro/astro/assets/62492410/1af27d39-4f59-4360-84c0-be9cdffbad07)

// SERVER 
```ts
export async function POST({ request }) {
  try {
    const body = await request.json();
    return new Response(JSON.stringify(body), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response(
      JSON.stringify({
        text: "Error,",
        message: "Unknown error",
      }),
      { status: 500, headers: { "Content-Type": "application/json" } },
    );
  }
}
```

// CLIENT
```tsx

type Props =  Readonly<{
    reactionKey: string;
    alt: string;
    emoji: string;
}>

async function onClick(){
 await fetch(`/api/reaction`, {
      headers: { "Content-Type": "application/json" },
      method: "POST",
      body: JSON.stringify(props),
    });
}
```

**Comment by bholmesdev** [comment]
Hey @tayhimself and @rimzzlabs, thanks for reporting! Do you mind seeing if you can reproduce in a minimal example using an astro.new template? That should help us find whether it's a general issue, or something more unique to your setups.

**Comment by rimzzlabs** [comment]
> Hey @tayhimself and @rimzzlabs, thanks for reporting! Do you mind seeing if you can reproduce in a minimal example using an astro.new template? That should help us find whether it's a general issue, or something more unique to your setups.

Hey, thanks for the update, I will be back with a codesandbox this evening

**Comment by rimzzlabs** [comment]
> Hey @tayhimself and @rimzzlabs, thanks for reporting! Do you mind seeing if you can reproduce in a minimal example using an astro.new template? That should help us find whether it's a general issue, or something more unique to your setups.

Here you go sir https://stackblitz.com/edit/withastro-astro-njgj6d?file=src%2Fpages%2Findex.astro,src%2Flayouts%2FLayout.astro,package.json,src%2Fcomponents%2FReactionButton.tsx,astro.config.mjs,src%2Fpages%2Fapi%2Freaction.ts&title=Astro%20Starter%20Kit:%20Basics

**Comment by bholmesdev** [comment]
@rimzzlabs Hm, I downloaded this sample you sent and I was unable to replicate. Here is what I did:
1. I updated the configuration to use the Node adapter with `output: 'server'`
2. I ran `npm run build` followed by `npm run preview`
3. I tried POSTing to `api/reaction` by running `curl http://localhost:4321/api/reaction -X POST -d '{"hello": "world"}'`

This seemed to parse my JSON input correctly. Is it possible you're using `output: 'hybrid'` for your application? If so, you'll need to add `export const prerender = false` to your `api/reaction` file.

**Comment by rimzzlabs** [comment]
> @rimzzlabs Hm, I downloaded this sample you sent and I was unable to replicate. Here is what I did:
> 
> 1. I updated the configuration to use the Node adapter with `output: 'server'`
> 2. I ran `npm run build` followed by `npm run preview`
> 3. I tried POSTing to `api/reaction` by running `curl http://localhost:4321/api/reaction -X POST -d '{"hello": "world"}'`
> 
> This seemed to parse my JSON input correctly. Is it possible you're using `output: 'hybrid'` for your application? If so, you'll need to add `export const prerender = false` to your `api/reaction` file.

I didn't read the docs carefully, turns out I can export the `prerender` variable from a `.ts` file (endpoints)?
Thanks for your help @bholmesdev , it works well now
