### ISSUE TITLE
🐛 BUG: Frontmatter variables inside markdown don't work on specific cases

### ISSUE THREAD

**Issue by felixsanz** [withastro/astro#3622]
### What version of `astro` are you using?

v1.0.0-beta.42

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

A markdown file with variables inside frontmatter, sometimes those variables don't work. On text they do fine, but at least on anchors they don't.

```md
this is text showing variable {frontmatter.url}.

this is text having a [link to contact page]({frontmatter.url}/contact)
```

This piece of markdown renders:

```html
<p>this is text showing variable http://localhost.</p>
<p>this is text having a <a href="%7Bfrontmatter.url%7D/contact">link to contact page</a></p>
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/festive-haze-ssjf38?file=/src/test.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Thanks for filing this @felixsanz!  I'd expect that to work as well, looks like we probably need to prevent the `{}` from being escaped 🤔

**Comment by matthewp** [comment]
Closing as this is an issue with legacy markdown that we'll likely not get around to working on. PR still would be accepted.
