### ISSUE TITLE
🐛 BUG: Astro components insert a space after text because POSIX incompatibility

### ISSUE THREAD

**Issue by felixsanz** [withastro/astro#3623]
### What version of `astro` are you using?

v1.0.0-beta.42

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

If a component contains this text:

```
<>foo</>(\n, new line)
(EOF, empty line)
```

![1655469540](https://user-images.githubusercontent.com/6182099/174299884-42467c7c-8bff-43bd-8071-44089e96e22d.png)

And the component is then called like `<p><Foo /></p>`, the result is `<p>foo </p>` (with a space after foo).

POSIX define a line as:

> 3.206 Line
> A sequence of zero or more non- < newline > characters **plus a terminating < newline > character**.

But here the terminating new line char is converted to a space, and shouldn't because it alters the HTML.

![1655469715](https://user-images.githubusercontent.com/6182099/174300330-237e40fe-85d2-4469-a116-ba8ce5878f28.png)

![1655469722](https://user-images.githubusercontent.com/6182099/174300349-10caca2e-e861-45ca-9a6d-9424c94eda0b.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/quiet-tdd-ys9mu6?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by felixsanz** [comment]
Just a thought... a solution could involve using `trim()` ?

**Comment by tony-sull** [comment]
I'm not sure if this would actually be in core or in our compiler, @natemoo-re does this one jump out to you as a likely compiler fix?

**Comment by matthewp** [comment]
I'm not sure what's changed, but this no longer occurs on latest: 
<img width="148" alt="Screen Shot 2022-10-07 at 9 12 26 AM" src="https://user-images.githubusercontent.com/361671/194562022-317e537c-26d2-4023-86f9-c6d31d691930.png">

https://codesandbox.io/s/condescending-tesla-iygbc1?file=/src/Test.astro
