### ISSUE TITLE
🐛 BUG: Astro config base not applied to paths in Astro component HTML and MD

### ISSUE THREAD

**Issue by cpetrov** [withastro/astro#3626]
### What version of `astro` are you using?

1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Demo: https://github.com/cpetrov/astro-base-issue-demo

Paths in the HTML part of Astro components and in Markdown components do not get adapted according to the `base` configuration of `astro.config.mjs`.

See:

`astro.config.mjs`
```ts
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  site: 'http://localhost:3000',
  base: '/base-path'
});
```

`src/pages/index.astro`
```html
...
# Paths to pages in the HTML part of Astro components:
<a href='/foo'>Visit foo</a> <!-- Points to http://localhost:3000/foo instead of http://localhost:3000/base-path/foo-->
...
# Paths to resources in the HTML part of Astro components:
<img src='/teide.jpg' width={500} /> <!-- Points to http://localhost:3000/teide.jpg instead of http://localhost:3000/base-path/teide.jpg -->
...
```

`src/pages/foo.md`
```md
...
# Paths to pages in Markdown components:
Go [home](/). <!-- Points to http://localhost:3000 instead of http://localhost:3000/base-path -->
...
# Paths to resources in Markdown components:
![Img](/teide.jpg) <!-- Points to http://localhost:3000/teide.jpg instead of http://localhost:3000/base-path/teide.jpg -->
```

When running a production build (`npm run build && npm run preview`), none of those paths are adapted to the configured base path. I would expect any absolute URLs  to be rewritten to the configured base path, similarly to how paths in CSS resources are handled by the build.

---
Note that when running `npm start`, the vulcano images will be shown as it seems the development build (`astro dev`) disrespects `base` when serving the `public` directory,  serving it on `http://localhost:3000/`, which corresponds to the paths that also do not respect `base`. The production build (`npm run build && npm run preview`) serves `public` on `http://localhost:3000/base-path/` as expected.

### Link to Minimal Reproducible Example

https://github.com/cpetrov/astro-base-issue-demo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Astro does not manipulate your `<a>` tags for you. `base` is used for injected scripts and links, but you'll have to set your `<a>` tags yourself.

**Comment by matthewp** [comment]
Going to close, happy to continue the discussion here.
