### ISSUE TITLE
🐛 BUG: Adding a backward slash silently causes Astro to hang without any feedback

### ISSUE THREAD

**Issue by ThatGuySam** [withastro/astro#3629]
### What version of `astro` are you using?

1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I just spent 6 hours trying to track down why I couldn't `astro build` or `astro dev` without indefinite hanging. 

`astro dev` would just load indefinitely with no response and no feedback from command line.  

Turns out I accidentally added a backward slash to the end of the layout property: 
```
layout: ../../layouts/MainLayout.astro\
```

This stuck me so bad I hope publishing this at least helps someone else who's stuck

Here's demo using the Minimal Reproducible Example attached: 
<video src="https://user-images.githubusercontent.com/2830379/174396119-c01f9f3a-ad07-407d-8fc5-e3c59ebc96b0.mov" />

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2dabec?file=src%2Fpages%2Fen%2Fintroduction.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ThatGuySam** [comment]
@tony-sull Yeah at the very least this issue and my solution will show up when searching for `astro silent hanging` and they don't have to waste hours of their life on a single typo

**Comment by Princesseuh** [comment]
Hello! This seems to have been fixed in one of the latest versions. It now shows 

> failed to load module for ssr: ../../layouts/MainLayout.astro\

Instead of hanging. The error message could be better, but that's a separate upstream issue (see https://github.com/vitejs/vite/issues/10002)

Thank you for reporting this!

**Comment by ThatGuySam** [comment]
Thanks @Princesseuh !!
