### ISSUE TITLE
Fix Netlify Edge Functions test suite and re-enable in CI

### ISSUE THREAD

**Issue by tony-sull** [withastro/astro#3632]
### What version of `astro` are you using?

1.0.0-beta.46

### Are you using an SSR adapter? If so, which one?

Netlify Edge

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Netlify Edge Functions were disabled in [#3631](https://github.com/withastro/astro/pull/3631), it looks like they'll need a little love to run reliably in the CI test runner

### Link to Minimal Reproducible Example

na

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
We use the bug tracker for issues, and not chore/TODOs like this!
