### ISSUE TITLE
🐛 BUG: Build fails because Vue Component cannot access the value set in vite define

### ISSUE THREAD

**Issue by hyakt** [withastro/astro#3636]
### What version of `astro` are you using?

1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

Build fails because Vue Component cannot access the value set in vite define.

Works OK for `astro dev`.
It is also OK if the vite define value is accessed from an Astro component.

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/3012887/174445254-398f1873-3fe7-42ff-bc9b-3642d65b50d6.png">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-njhw7j-328yrx?file=astro.config.mjs&file=src%2Fcomponents%2FSample.vue&file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by hyakt** [comment]
To add to this, as there may be a difference in perception, you can refer to the value of Vite's define if it is within the Astro Component.
The problem is that you cannot access it from the Vue Component.

**Comment by rishi-raj-jain** [comment]
@matthewp 

I see this working with the latest astro.

Here's the repro that doesn't repro the issue: https://github.com/rishi-raj-jain/issue-astro-config-define-vue
