### ISSUE TITLE
🐛 BUG: Cannot convert undefined or null to object in beta 47

### ISSUE THREAD

**Issue by jackmerrill** [withastro/astro#3641]
### What version of `astro` are you using?

1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

Node/Deno, however it may not matter in this instance

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

The https://github.com/withastro/astro/commit/fc52321a888920beebb6b84f56d2f41791666e13 commit seems to have broken something, I'm not exactly sure what and I don't know how to replicate it.

Running an earlier version of Astro (I downgraded to beta 44, was using it earlier) seems to work fine.

### Link to Minimal Reproducible Example

I have no idea how to reproduce this sadly. From what I can see on the Discord, others may be having trouble with this same (or a similar) issue.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by iiome** [comment]
I am experiencing the same error message on React components when I pass more than one property to the React component from an Astro page.

When I remove on property the React component is rendering with no error message.

### What version of astro are you using?
1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?
dev or preview mode

### What package manager are you using?
yarn

### What operating system are you using?
macOS
