### ISSUE TITLE
🐛 BUG: `<p>`-tags spread over multiple lines in Markdown generate multiple `<p>`-tags

### ISSUE THREAD

**Issue by andygrunwald** [withastro/astro#3642]
### What version of `astro` are you using?

1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When you clone the **Astro Starter Kit: Blog with Multiple Authors** example and add the following content to a blog post (like `pages/post/chapter-i.md`):

```html
<p>
  THIS IS HELLO
  <a href="https://google.com">
    Link
  </a>
</p>
```

Astro generates content like

```html
<p>THIS IS HELLO</p><a href="https://google.com/"><p>Link</p></a>
```

See screenshot:
![Screenshot from 2022-06-19 13-20-05](https://user-images.githubusercontent.com/320064/174478368-d88f7eda-158b-468a-add9-e3989a1383ad.png)

### Expected result

Output generation like

```html
<p>THIS IS HELLO <a href="https://google.com/">Link</a></p>
```

This bug might be very similar to https://github.com/withastro/astro/issues/3529

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ldex7c?file=src/pages/post/chapter-i.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by andygrunwald** [comment]
Writing the HTML like

```
<p>THIS IS HELLO<a href="https://google.com">Link</a></p>
```

produces the expected output.

**Comment by X7md** [comment]
I think by default the markdown parser will parse any text intro `<p>` tag.

Try use
 
```markdown
THIS IS HELLO [Hello](https://google.com)
```
preview:
 [Hello](https://google.com)

as workaround.

Also I think you can configure remake parser manually to avoid this behavior.

**Comment by andygrunwald** [comment]
@X7md Any hint where or how I can configure this?

**Comment by matthewp** [comment]
Can you try again with latest? If you are still seeing the same behavior please open a new issue. The markdown handling has changed a lot since we went stable.
