### ISSUE TITLE
🐛 BUG: define:vars - Identifier 'xxx' has already been declared 

### ISSUE THREAD

**Issue by laurieherault** [withastro/astro#3643]
### What version of `astro` are you using?

1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Windows, Linux

### Describe the Bug

When you create an Astro component with an inline script with define:vars and use this component multiple times you have a bug because the variable created by Astro is used multiple times.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hgd3l7

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Interesting bug @laurieherault! Seems we define variables without de-duping props passed to a component. Worth investigating 👍

**Comment by FredKSchott** [comment]
Thanks for filing! I believe that this has been fixed in RC! If you can still reproduce, please comment and we can reopen to debug more.
