### ISSUE TITLE
🐛 BUG: Vue components can't be nested

### ISSUE THREAD

**Issue by prototowb** [withastro/astro#3644]
### What version of `astro` are you using?

1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The BaseLayout component in the Example should hold other Vue components. What's unusual here, is, that using other components in that BaseLayout Vue component only is possible when adding the `setup` attribute tho the script block. which is only syntactic sugar for the Vue3 composition API, and should work totally fine without. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pfa8kk?file=src/layouts/BaseLayout.vue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for reporting @prototowb! [Looking at the Vue 3 docs](https://vuejs.org/guide/essentials/component-basics.html#using-a-component) as a sanity check, it seems you should export a `components` object when using the options API. Just tested that adding the following export and dropping `setup` will work:

```js
import Header from './Header.vue'
export default {
  components: { Header },
}
```

Is there a Vue nuance you were expecting to work that didn't here?

**Comment by prototowb** [comment]
> Thanks for reporting @prototowb! [Looking at the Vue 3 docs](https://vuejs.org/guide/essentials/component-basics.html#using-a-component) as a sanity check, it seems you should export a `components` object when using the options API. Just tested that adding the following export and dropping `setup` will work:
> 
> ```js
> import Header from './Header.vue'
> export default {
>   components: { Header },
> }
> ```
> 
> Is there a Vue nuance you were expecting to work that didn't here?

oof. yes. that's the way. seems it has been often quite late the last couple days 😄 sorry for the noise

**Comment by bholmesdev** [comment]
No problem! Glad we got it working 👍
