### ISSUE TITLE
🐛 BUG: Astro 1-beta42 re-introduces a PostCSS Preset Env's Custom Media Queries bug

### ISSUE THREAD

**Issue by djmtype** [withastro/astro#3648]
### What version of `astro` are you using?

1.0.0-beta.46

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

I'm using Open-Props library which relies heavily on the [PostCSS Import](https://www.npmjs.com/package/postcss-import) plugin and the [PostCSS Preset Env](https://preset-env.cssdb.org/) plugin. This bug is not exclusive to Open-Props BTW.

It utilizes [media query ranges](https://preset-env.cssdb.org/features/#media-query-ranges) and [custom media queries](https://preset-env.cssdb.org/features/#custom-properties). Those properties can be seen here: https://github.com/argyleink/open-props/blob/main/src/props.media.css

The following example no longer works in Astro 1-beta 42 and later, but works as expected in Astro 1-beta 41.
```
body {
  @media (--sm-n-above) {
    background-image: var(--gradient-3);
  }
}
```

The workaround would be to include the custom media query definition(s) ([This file](https://github.com/argyleink/open-props/blob/main/src/props.media.css)) in every single Astro component wherever custom media queries are used. However, that would be entirely tedious, redundant and bloated because the bug only persists during development, and not at build. 

In the Stackblitz example, expand the viewport beyond 480px wide, and there should be a gradient background, however, the background remains white. This is the bug. 

Uncomment `@custom-media --sm-n-above (width >= 480px)` as a workaround to see that PostCSS Env's custom media queries do work.

This bug is tricky because if you comment out `@custom-media --sm-n-above (width >= 480px)` once again, everything will continue working. 

However, kill and restart the server and you'll see the issue again.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3pb6hh?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for the thorough issue @djmtype! I see [two changes from `beta.42`](https://github.com/withastro/astro/pull/3534) that could be to blame here:
- #3537 cc @matthewp 
- #3492 cc @natemoo-re 

Can confirm this issue occurs in CSS files imported via frontmatter as well ([reproduction](https://stackblitz.com/edit/github-3pb6hh-mkuu3v?file=src/pages/index.astro))

**Comment by djmtype** [comment]
Honestly, just found it more reliable to add this configuration to postcss.config.js.
```js
const postcssPresetEnv = require("postcss-preset-env")

module.exports = {
	plugins: [
		postcssPresetEnv({
			stage: 0,
			features: {
				"custom-media-queries": {
					importFrom: ["./node_modules/open-props/src/props.media.css"],
				},
			},
		}),
	],
}
```

**Comment by matthewp** [comment]
Appears to be an underlying Vite issue. Here's a recreation here: https://stackblitz.com/edit/vitejs-vite-rhhiwt?file=index.html,package.json,style.css,postcss.config.js&terminal=dev

Should we document the workaround somewhere? Going to close this issue as it doesn't appear we can fix it.

**Comment by samducker** [comment]
Import from has been deprecated according to the PostCSS console logs I'm getting. 

My most reliable workaround now is to import the variables into all scoped styles, not sure why it doesn't just work importing it into my layout.

  @import "../../styles/variables.css";

I'm just using custom media queries but not open props.

**Comment by SFToro** [comment]
Is importing the stylesheet in every component the only workaround? Has someone found any other solution?
Indeed it is very tedious.

Thanks in advance.

**Comment by davidsandoz** [comment]
I'm facing the same problem. Should this issue be re-opened or another one created?

**Comment by samducker** [comment]
Would be awesome if we didn’t have to do this, yes I am having to import into each and every component.

**Comment by SalahAdDin** [comment]
> Honestly, just found it more reliable to add this configuration to postcss.config.js.
> 
> ```js
> const postcssPresetEnv = require("postcss-preset-env")
> 
> module.exports = {
> 	plugins: [
> 		postcssPresetEnv({
> 			stage: 0,
> 			features: {
> 				"custom-media-queries": {
> 					importFrom: ["./node_modules/open-props/src/props.media.css"],
> 				},
> 			},
> 		}),
> 	],
> }
> ```

It does not work with NextJs.
