### ISSUE TITLE
🐛 BUG: Partytown integration does not work with some SSR adaptors

### ISSUE THREAD

**Issue by nrgnrg** [withastro/astro#3668]
### What version of `astro` are you using?

^1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

netlify, cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Both the Netlify and Cloudflare adaptors serve static assets by deferring the request to the platform, they do this by first checking if the request is for something that exists in the manifest from the `createExports` args.

```
// netlify adaptor
if (manifest.assets.has(url.pathname)) {
  return;
}

// cloudflare adaptor
if (manifest.assets.has(pathname)) {
  const assetRequest = new Request(`${origin}/static${pathname}`, request);
  return env.ASSETS.fetch(assetRequest);
}
```

the `manifest.assets.has(pathname)` fails for partytown assets because the partytown static assets do not exist in the manifest and thus they 404.

I'm not sure wether this is a bug in the partytown integration or wether the adaptors should handle this better.

Partytown could be special cased in the adaptors or the check could be more forgiving with a regex like so: `/\.\w+$/.test(pathname)`. Although both are a workaround.

### Link to Minimal Reproducible Example

I tried to set this up in a repro but was having difficulties, I can give it another go if this isn't clear enough.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for the thorough explanation @nrgnrg! I agree this should be handled better on the integration side. Personally, I think adding partytown assets to the manifest is worth investigating over the workaround you mentioned. We'd need to investigate how possible this is though.

**Comment by matthewp** [comment]
It's possible that type of integration does not currently work in SSR. I'll look into it.

**Comment by nrgnrg** [comment]
I think the issue is here

https://github.com/withastro/astro/blob/b9f891b8a65652e5ef167829c19b0a3f39501bb4/packages/integrations/partytown/src/index.ts#L49-L51

it copies over the files into to the build folder on `astro:build:done` so there not included in the manifest and thus the SSR adaptors don't know how to route requests for them

**Comment by matthewp** [comment]
@nrgnrg do they get added to the page though? And 404 from there?

**Comment by nrgnrg** [comment]
it looks like a script tag gets added to the head which I think is initiating the request

**Comment by matthewp** [comment]
PR: https://github.com/withastro/astro/pull/3686
