### ISSUE TITLE
🐛 BUG: <style> in .md files makes compliation fail

### ISSUE THREAD

**Issue by NotWoods** [withastro/astro#3687]
### What version of `astro` are you using?

1.0.0-beta.52

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Trying to use `<style>` inside markdown files makes rendering fail. The new markdown parser seems to fail when it encounters CSS, even though its within a style element.

This is working in version 1.0.0-beta.31 but breaks in later versions.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/epic-black-ecj5tr?file=/src/pages/styles.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for reporting @NotWoods! That _is_ pretty confusing... we've been hard at work on fixing our markdown parser after some recent changes, and I know we haven't been checking for this use case. In the meantime, I'd suggest styling via an Astro `layout` [using the `:global()` keyword](https://docs.astro.build/en/guides/styling/#global-styles) to style headings, images, etc.

**Comment by matthewp** [comment]
Looks like this problem no longer exists: https://stackblitz.com/edit/github-n2pdxa?file=src%2Fpages%2Findex.astro,src%2Fpages%2Fstyles.md&on=stackblitz
