### ISSUE TITLE
🐛 BUG: `import.meta.env.SSR` not defined depending on environment doing the build

### ISSUE THREAD

**Issue by nrgnrg** [withastro/astro#3688]
### What version of `astro` are you using?

1.0.0-beta.52

### Are you using an SSR adapter? If so, which one?

cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Slightly odd one, I noticed a few days ago that `import.meta.env.SSR` was `undefined` in the SSR build but it looked like this was resolved around `beta.48`/`beta.49`.

However it appears to only be somewhat fixed and that depends on the platform which does the build.

- Building on my mac the behaviour is as expected, `import.meta.env.SSR` is a boolean.
- Building in either the Github Actions CI or Cloudflare pages `import.meta.env.SSR` is `undefined`.

[This repro](https://github.com/nrgnrg/astro-ssr-repro) has been deployed to Cloudflare Pages in 2 different ways

- built locally and uploaded via dashboard GUI: https://74b1f4d5.astro-test-bio.pages.dev/
- build on Cloudflare Pages via GitHub integration: https://268c2da3.astro-ssr-repro.pages.dev/

you can see the `typeof` in the second deployment is `undefined`

### Link to Minimal Reproducible Example

https://github.com/nrgnrg/astro-ssr-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JReinhold** [comment]
I'm seeing the same issue with the deno adapter.

Building on my Mac works fine, but building in GitHub Actions and deploying to Deno Deploy sets `import.meta.env.SSR` to `undefined`

**Comment by delucis** [comment]
Thanks! In that case I’ll leave this for someone more expert to triage — I’d just been editing docs updates about that flag so it’s about the extent of my knowledge here, sorry 🙌
