### ISSUE TITLE
🐛 BUG: Hydration with Solid without a wrapper DOM element

### ISSUE THREAD

**Issue by SebastianM** [withastro/astro#3690]
### What version of `astro` are you using?

beta 51

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I'm not 100% sure if it's an Astro bug or a Solid bug.

I created a simple Solid component that is a counter - nothing special:

```tsx
import { Component, createSignal } from "solid-js";

const Counter: Component = function () {
  const [count, setCount] = createSignal(0);
  return (
    <>
      {count()}
      <button type="button" onClick={() => setCount(count() + 1)}>
        add
      </button>
    </>
  );
};

export default Counter;
```

I hydrate the component on load. When I click the button, the count is shown in another text node. The intial count 0 of the SSG run is still on the page. 

**When the `{count()` get's wrapped in a div, it works fine.**

```astro
---
import Counter from '../components/Counter';
---
<Counter client:load></Counter>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hwirgy?file=src/components/Counter.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SebastianM** [comment]
I'm closing this as it seems that it is a solid bug.
See https://github.com/solidjs/solid/issues/1079

**Comment by chlbri** [comment]
You need to await, maybe 200 milliseconds before rehydratation.

<img width="570" alt="Capture d'écran 2022-10-14 à 20 04 47 PM" src="https://user-images.githubusercontent.com/51156116/195933266-58a5db78-e3a6-4ec5-b9d0-cf45a83ad5f4.png">

This is a project where I use xstate as state manager, and rehydrate data with localStorage
