### ISSUE TITLE
🐛 BUG: `adapter` not fully documented in Configuration Reference

### ISSUE THREAD

**Issue by sarah11918** [withastro/astro#3691]
### What version of `astro` are you using?

1.0.0.-beta.50

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

ChromeOS

### Describe the Bug

There seems to be a placeholder for `adapters` in https://github.com/withastro/astro/blob/main/packages/astro/src/%40types/astro.ts to generate a description for docs, but needs to be written so that it will appear in our Configuration Reference page in docs.

![Screenshot 2022-06-23 12 05 00](https://user-images.githubusercontent.com/5098874/175331930-3b44b97a-5d37-444d-9e47-5f892c5b3025.png)
![Screenshot 2022-06-23 12 10 49](https://user-images.githubusercontent.com/5098874/175332683-5d6fbcdf-8fb3-4c62-b943-6e0a9ba25c64.png)

### Link to Minimal Reproducible Example

https://docs.astro.build/en/reference/configuration-reference/#integrations

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Good call-out Sarah! Should be an easy fix 👍
