### ISSUE TITLE
🐛 BUG: Possible hydration issue

### ISSUE THREAD

**Issue by ddrake** [withastro/astro#3698]
### What version of `astro` are you using?

0.26.1

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

A component which makes an XHR POST request to fauna.com works with @astrojs/preact v0.1.2 fails with @astrojs/preact v0.1.3

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jdz7wg?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ddrake** [comment]
No, but I can do that today.

Sent from my iPad

On Jun 24, 2022, at 6:28 AM, Matthew Phillips ***@***.***> wrote:

﻿

Have you tried with the 1.0 beta?

**Comment by ddrake** [comment]
Thanks @matthewp -- with astro 1.0.0-beta.53, the issue with @astrojs/preact v 0.1.3 is no longer present.  I will upgrade astro to the 1.0 beta version at my sites

**Comment by matthewp** [comment]
Great to hear!
