### ISSUE TITLE
🐛 BUG: Importing an Astro component through an `index.{js,ts}` facade, via `package.json` breaks client side bundled JS

### ISSUE THREAD

**Issue by JulianCataldo** [withastro/astro#3703]
### What version of `astro` are you using?

55

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Example of facade index.js :
```ts
export { default as Image } from './src/Image.astro';
```
```ts
import TransitionOverlay from './Overlay/TransitionOverlay.astro';

export default TransitionOverlay;
```

Works good, but client side bundled JS (non-inline) is not loading at all.
Tested with 1.0.0-beta.47 and 55

[Discord message](https://discord.com/channels/830184174198718474/878341752799494154/989978686495277066)

### Link to Minimal Reproducible Example

https://github.com/JulianCataldo/astro/tree/master/app/Base

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
This is definitely a bit of a rough edge that we're actively working on, the [currently supported](https://docs.astro.build/en/guides/publish-to-npm/#packagejson) way to publish `.astro` component is to use the `exports` map in `package.json` to point to the `.astro` file

The basic exporting with a facade file currently comes down to exactly how imports are resolved during build time, but this one is definitely on a radar as a future improvement, and one that Matthew may have actually already been working on to see if it could make it into the 1.0 Relase Candidate :+1:

**Comment by ashishlotake** [comment]
```
src/components
└── Button
    ├── Button.astro
    └── index.ts
```

in `index.ts`
```ts
export { default as Button } from "./Button.astro"
```

Then in index.astro 
```
import { Button } from "src/component/Button"
```
