### ISSUE TITLE
🐛 BUG: incorrect import.meta.env.BASE_URL at development

### ISSUE THREAD

**Issue by AllanChain** [withastro/astro#3711]
### What version of `astro` are you using?

1.0.0-beta.56

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Even though setting `base: '/blog'` in Astro config, `import.meta.env.BASE_URL` is always `'/'` in development. But it's correct in build.

Possible cause: `base` option is not passed to Vite in development.

https://github.com/withastro/astro/blob/72587eccc51e7468aba7839daa471d0de5e17abf/packages/astro/src/core/dev/index.ts#L43-L59

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-srxxa3?file=src%2Fpages%2Findex.astro,astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by JulianCataldo** [comment]
I've seen this bug too
