### ISSUE TITLE
🐛 BUG: Could not parse expression with acorn: Expecting Unicode escape sequence \uXXXX

### ISSUE THREAD

**Issue by victor0x16** [withastro/astro#3714]
### What version of `astro` are you using?

1.0.0-beta.56

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Rendering mathematical expressions in Markdown works/worked `1.0.0-beta.31`, but it is not working anymore.

My code:
```js
// file.md
<Fragment is:raw>
   $$f(x) = \pm A \sin\left(\frac{2\pi}{4} + \theta\right)$$
</Fragment>
```

The output should be:
$$f(x) = \pm A \sin\left(\frac{2\pi}{4} + \theta\right)$$

But I get an Error:
```
Could not parse expression with acorn: Expecting Unicode escape sequence \uXXXX
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/affectionate-flower-rc6f81?file=/src/pages/posts/MathMath.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sylvinus** [comment]
Hello! I just wanted to link this issue with https://github.com/withastro/compiler/issues/436, which was also created between betas 31 and 33

**Comment by natemoo-re** [comment]
Hey @victor0x16 and @sylvinus! Astro 1.0 has been released and we no longer run `.md` files through the Astro compiler!

This should make things like this much easier, and I can confirm that this issue is now fixed. See [working repro](https://stackblitz.com/edit/github-ync4n4?file=src%2Fpages%2Fposts%2FMath.md).

**Comment by sylvinus** [comment]
@natemoo-re awesome, thanks!

**Comment by sylvinus** [comment]
@natemoo-re I've tried to integrate katex in mdx, either with astro-katex or the remark/rehype plugins and I'm getting errors in both cases. Can you have a look?

https://stackblitz.com/edit/github-ync4n4-tjaxjr?file=src%2Fpages%2Fposts%2FMath2.mdx,astro.config.mjs,src%2Fpages%2Fposts%2FMathless.mdx,src%2Fpages%2Findex.astro,src%2Fpages%2Fposts%2FMath.md

https://stackblitz.com/edit/github-ync4n4-ytz3cu?file=src%2Fpages%2Findex.astro,package.json,astro.config.mjs,src%2Fpages%2Fposts%2FMath.mdx

thanks!
