### ISSUE TITLE
🐛 BUG: import.meta doesn't works with the vue sfc

### ISSUE THREAD

**Issue by CDHon** [withastro/astro#3720]
### What version of `astro` are you using?

1.0.0-beta.53

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

windows

### Describe the Bug

I want to use the vitest's in-source tesing, but the tsconfig doesn't work for vue's sfc.
I tried using official vue initial project and import.meta can work there.
https://vitest.dev/guide/in-source.html
![image](https://user-images.githubusercontent.com/79888915/175835706-a82ad77f-0ef4-401d-9dae-b85911da5351.png)
```
//tsconfig.json
{
  "compilerOptions": {
    "strict": true,
    // Enable top-level await, and other modern ESM features.
    "target": "ESNext",
    "module": "ESNext",
    // Enable node-style module resolution, for things like npm package imports.
    "moduleResolution": "node",
    // Enable JSON imports.
    "resolveJsonModule": true,
    // Enable stricter transpilation for better output.
    "isolatedModules": true,
    // Add type definitions for our Vite runtime.
    "types": ["vite/client", "vitest/importMeta"],
    "jsx": "preserve"
  }
}
//vitest.config.ts
import { defineConfig } from "vitest/config";

export default defineConfig({
  define: {
    "import.meta.vitest": "undefined",
  },
  test: {
    includeSource: ["src/**/*.{js,ts,jsx,tsx,vue}"],
  },
});


```

### Link to Minimal Reproducible Example

astro  vue  vitest

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Thanks for opening this issue!  We haven't had a chance to dive deep into how Vitest integrates with Astro but this is a perfect chance to get that rolling

Can you provide a link to an example project based on one of the [astro.new](https://astro.new) starters that we can use a starting point for our investigation?

**Comment by CDHon** [comment]
> Thanks for opening this issue! We haven't had a chance to dive deep into how Vitest integrates with Astro but this is a perfect chance to get that rolling
> 
> Can you provide a link to an example project based on one of the [astro.new](https://astro.new) starters that we can use a starting point for our investigation?

I make a mistake about the location of config, sorry, thanks for comment, I will be careful next time.
