### ISSUE TITLE
🐛 BUG: `define:vars` not working with CSS / Styles

### ISSUE THREAD

**Issue by marcosmartini** [withastro/astro#3721]
### What version of `astro` are you using?

1.0.0-beta.56

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using `define:vars` with styles, css variables are not being passed down/initiated.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uxs5zp?file=src/components/Title.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I think this is related to a change to head injection, will take this.

**Comment by Jutanium** [comment]
I'm having the [same problem](https://stackblitz.com/edit/github-eutsb3-fbczth?file=src%2Fcomponents%2FBox.svelte,src%2Fcomponents%2FBox.vue,src%2Fcomponents%2FBox.jsx,src%2Fcomponents%2FBox.astro,src%2Fpages%2Findex.astro).

**Comment by matthewp** [comment]
Just merged, release will go out shortly.

**Comment by marcosmartini** [comment]
Amazing guys!
