### ISSUE TITLE
🐛 BUG: vue's tsx dose not work with vue intergration

### ISSUE THREAD

**Issue by CDHon** [withastro/astro#3722]
### What version of `astro` are you using?

1.0.0-beta.53

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

windows

### Describe the Bug

```
//App.tsx
import { defineComponent } from "vue";

export default defineComponent({
  setup() {
    return <h1>hi</h1>;
  },
});

//index.astro
import App from '../components/App';
---
<App></App>

//Terminal
[Vue warn]: Component App is missing template or render function.

// stackblitz's Terminal
Unable to resolve a JSX renderer! Did you forget to include one? Add a JSX integration like `@astrojs/react` to your `astro.config.mjs` file.
```

### Link to Minimal Reproducible Example

[astro with vue intergration](https://stackblitz.com/edit/github-6bdjbe?file=src/components/HelloWorld.jsx)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Thanks for filing!  There were a few updates recently to improve how astro handles `.ts` and `.js` file extensions to better align with TypeScript conventions, this may be a new regression

Can you provide an example project based on one of the [astro.new](https://astro.new) starter templates that we can use as the starting point for investigating the issue?

**Comment by CDHon** [comment]
> Thanks for filing! There were a few updates recently to improve how astro handles `.ts` and `.js` file extensions to better align with TypeScript conventions, this may be a new regression
> 
> Can you provide an example project based on one of the [astro.new](https://astro.new) starter templates that we can use as the starting point for investigating the issue?

sorry, I have now updated the example.

**Comment by CDHon** [comment]
> Thanks for filing! There were a few updates recently to improve how astro handles `.ts` and `.js` file extensions to better align with TypeScript conventions, this may be a new regression
> 
> Can you provide an example project based on one of the [astro.new](https://astro.new) starter templates that we can use as the starting point for investigating the issue?

Maybe I made a mistake again, I will close the issue and find how to configure by myself.
 I apologize for my rudeness, see you next time.

**Comment by X-Jagger** [comment]
> 
@CDHon same error here，how do u configure it right?
