### ISSUE TITLE
🐛 BUG: SSR - dynamic routes are triggered by static files

### ISSUE THREAD

**Issue by yassinedoghri** [withastro/astro#3728]
### What version of `astro` are you using?

1.0.0-beta.57

### Are you using an SSR adapter? If so, which one?

Node.js

### What package manager are you using?

npm

### What operating system are you using?

Linux (Ubuntu 22.04)

### Describe the Bug

When using SSR, dynamic routes get unexpectedly triggered by static files.

This issue was initially found when using the `astro-i18next` component with SSR: https://github.com/yassinedoghri/astro-i18next/issues/12

I've mentioned this issue on discord https://discord.com/channels/830184174198718474/872579324446928896/990992832317759558

I guess this is not intended and may create side-effects.

To see the issue in the linked minimal reproduction:
1. run `npm run server`
2. open the preview in a new window
![image](https://user-images.githubusercontent.com/11021441/175991697-30fa5037-25b2-4d4c-b923-8bb96bc42c72.png)
3. follow the instructions on the page

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ewjnzr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Yep, that's definitely a bug!  It looks like Astro's internal server is ignoring `public` files and jumps right to matching the route to `src/pages`

In the reproduction, if you add a `favicon.ico` file to `public` it will actually work as expected in `dev` but `build` still ignores public.  We'll get this cleaned up soon!
