### ISSUE TITLE
🐛 BUG: Integration looking for a js map throwing a warning in the console

### ISSUE THREAD

**Issue by moritzlaube** [withastro/astro#3731]
### What version of `astro` are you using?

1.0.0-beta.56

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When working with Svelte, the astro-svelte-integration throws a warning in the console that it can't find a js source map:

```
DevTools failed to load source map: Could not load content for http://localhost:3000/@id/@astrojs/svelte/@astrojs_svelte_client_js.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
Check DevTools in the console of the attached Stackblitz

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4o8rsa?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Yep, Ben has been hitting this one quite a bit working with Svelte as well!  [PR #3744](https://github.com/withastro/astro/pull/3744) actually just got merged in with a fix so these warning should disappear in the next beta release 🎉

**Comment by c-ehrlich** [comment]
Still having this issue in ^1.0.0-beta.73, with Preact

`[serve]    404 /@id/@astrojs/preact/@astrojs_preact_client_js.js.map (x2)`

**Comment by silveltman** [comment]
> Still having this issue in ^1.0.0-beta.73, with Preact
> 
> `[serve] 404 /@id/@astrojs/preact/@astrojs_preact_client_js.js.map (x2)`

me too

**Comment by ntnhan30dh** [comment]
Same here "^1.0.0-beta.73" with React

**Comment by noga-dev** [comment]
1.0.0-beta.73 both Solid and Svelte

**Comment by sandervspl** [comment]
Still happening for me in `v1.0.0-rc.3` with Preact

```
05:12:37 PM [getStaticPaths] Route pattern matched, but no matching static path found. (/@id/@astrojs/preact/@astrojs_preact_client__js.js.map)
05:12:37 PM [serve]    404 /@id/@astrojs/preact/@astrojs_preact_client__js.js.map
```

**Comment by cAttte** [comment]
fixed this by disabling the React DevTools extension. related? facebook/react#32339
