### ISSUE TITLE
🐛 BUG: client:only component not visible in development

### ISSUE THREAD

**Issue by saravanapriyanm** [withastro/astro#3739]
### What version of `astro` are you using?

1.0.0-beta.42

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac, Windows

### Describe the Bug

When running the project with `astro dev`, client:only component is not visible. After build, in `astro preview` the component is visible.

Console throws an error: 
`Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://github-jhuzfh-ehssvd--3000.local.webcontainer.io/@fs/home/projects/github-jhuzfh-ehssvd/src/components/accordion`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jhuzfh-ehssvd

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by saravanapriyanm** [comment]
In stackblitz, change something `index.html` to reproduce the bug.

Page refresh seems to work in stackblitz, but not working in local.

**Comment by saravanapriyanm** [comment]
Any update on this?

**Comment by natemoo-re** [comment]
Sorry for the delay @saravanapriyanm! I am looking at this as we speak.

**Comment by natemoo-re** [comment]
I can confirm that this is no longer happening with our latest changes in the `astro@1.0.0-rc` release candidate!

See that updating both the `pages/index.astro` file and the `components/accordion.jsx` file refresh the page as expected. https://stackblitz.com/edit/github-jhuzfh-xp4vv6?file=src%2Fpages%2Findex.astro

If you run into any further issues, please don't hesitate to open another issue!

**Comment by CommanderGL** [comment]
This is happening to me in newer version.

I was trying to make an Iframe that will set src based on id in URL Search Params I moved my JS code to SolidJS component and got this error.
