### ISSUE TITLE
🐛 BUG: Can't pass Map to hydrated Svelte component

### ISSUE THREAD

**Issue by pinhead84** [withastro/astro#3752]
### What version of `astro` are you using?

1.0.0-beta.57

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Starting with Version 1.0.0-beta47 it seems not to be possible anymore, to pass a `Map` object as a property to a Svelte component (in combination with `client:load`). I guess, it's not properly hydrated. Browser console shows the following Javascript error:

```
VM210:1 Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at 4 ((index):14:236)
    at Object.o ((index):14:389)
    at JSON.parse (<anonymous>)
    at hydrate ((index):14:1026)
    at (index):14:131
```

Converting the `Map` to a `Record` before passing it to the Svelte component solved the problem for me.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-g8d1n6

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by leader22** [comment]
I had a same issue and tried some debugging.

> this is just a bug in how Map is serialized

Yes.

https://github.com/withastro/astro/blob/38f2fd7723407a80fbece621be2d4aa95713df7f/packages/astro/src/runtime/server/astro-island.ts#L20-L35

It throws here and using `Set` also fails to deserialize.

And I found another possible bug that `undefined` value converted to `null` while serializing. 🙈
