### ISSUE TITLE
Add test coverage for the `injectRoute` API

### ISSUE THREAD

**Issue by tony-sull** [withastro/astro#3762]
### What version of `astro` are you using?

1.0.0-beta.58

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

`injectRoute` doesn't have any test coverage yet!

**Coverage needed**
- `astro dev`
- `astro build` for SSR builds
- injecting basic pages, `/_admin`
- injected API endpoints
- injecting dynamic routes, `/_admin/[userid]`
- injecting dynamic routes with rest params, `/_admin/[...params]`

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
We use the bug tracker for issues, and not chore/TODOs like this!
