### ISSUE TITLE
🐛 BUG: Streaming (1.0.0-beta.55) breaks Cloudflare Pages

### ISSUE THREAD

**Issue by nrgnrg** [withastro/astro#3764]
### What version of `astro` are you using?

1.0.0-beta.55

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

I'm super excited that streaming has landed in Astro, such a great feature!

Unfortunately Cloudflare Pages are currently stuck on a fairly old version of the workers runtime that doesn't support streams. There is as of right now no way to set the compatibility date or the flag to enable streams. I've asked about this again on the Cloudflare discord but the last update was "it's coming soon", which isn't a concrete timeframe.

What this means is that the Cloudflare adaptor, for now anyway, will only work with versions of Astro pre `1.0.0-beta.55`.

I've tried the `web-streams polyfill` and buffering the response to a string in the Cloudflare adaptor but I think the issue lies in the fact that the Response constructor doesn't know what to do when passed a stream and just outputs `[object ReadableStream]`.

I don't think this is a bug or an issue with Astro, more Cloudflare Pages itself, but I've raised the issue here because I think it should be documented on the Cloudflare adaptor which I'm happy to raise a PR to do, since it's now somewhat broken. Or on the off chance there is a way to workaround the streams changes that went into Astro core?

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
**Notes from Triage Call**

- Cloudflare adapter might need to use the `@astrojs/webapi` polyfill. If that works, we're good!
- If not, we might need to make our streaming support detection is properly working.
- As a final option, we may need to build-in a flag for core to toggle streaming on/off.

**Comment by matthewp** [comment]
Can the adapter not just buffer the response and create a new one with the final HTML?
