### ISSUE TITLE
🐛 BUG: Astro request url with ssr can't retrieve url hash

### ISSUE THREAD

**Issue by ariomoklo** [withastro/astro#3775]
### What version of `astro` are you using?

1.0.0-beta.59

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm, pnpm

### What operating system are you using?

windows

### Describe the Bug

I'm using supabase that required to using url hash for reseting user password.

I tried doing this:
```js
// try with url:
// http://localhost:3000/#token=abcd&q=1234&s=test

const url = new URL(Astro.request.url)
const hash = JSON.stringify(url.hash)
```

hash will return nothing.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-url-hash-test?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! This seems like it should be pretty small to fix, hoping to get to it as soon as we can!

**Comment by matthewp** [comment]
URL hashes are only available client-side and aren't sent as part of the HTTP request. You can use them in your client components but not in a Astro component (or a client component in SSR).

What you probably want to do is use a query/search param instead; ie change the `#` to `?`.

See https://stackoverflow.com/questions/14462218/is-the-url-fragment-identifier-sent-to-the-server#:~:text=Fragment%20identifiers%20are%20not%20sent,elements%20within%20the%20same%20page.
