### ISSUE TITLE
🐛 BUG: cannot export types from astro components

### ISSUE THREAD

**Issue by ggrandi** [withastro/astro#3787]
### What version of `astro` are you using?

1.0.0-beta.61

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Whenever I try to export a type from the frontmatter that either is an interface that extends another interface or is a defined with the type keyword, astro errors with an unclear `ERROR: Unexpected "export"`.

This is an issue because it makes exporting Props that extend intrinsic elements difficult as shown in `components/MyParagraph2.ts`. The only workaround is to put the interface that it extends from in a different file.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jxm7wb?file=src/components/Bug.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
This is actually a slightly different issue, `MyParagraph1.astro` has an export after a non-exported type - updating it to`export type ParagraphProps` does fix the build issue

I'll track down the tracking bug, this has been a high priority on our list to get rid of the limitation that all imports/exports need to be at the top of the `.astro` frontmatter

**Comment by ggrandi** [comment]
Thank you very much

This fixed the issue
