### ISSUE TITLE
🐛 BUG: Astro MDX doesn't allow comments

### ISSUE THREAD

**Issue by okikio** [withastro/astro#3792]
### What version of `astro` are you using?

^1.0.0-beta.61

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Using this comment syntax causes bugs,
```astro
{/* comment */} 
```

![image](https://user-images.githubusercontent.com/17222836/176940779-8887ba04-79e5-46b6-99e9-e60895d41b1e.png)

> **Note**: the MDX vscode extension by default uses `<!-- comments -->` 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5mawuq?file=src/pages/index.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by okikio** [comment]
cc @natemoo-re

**Comment by natemoo-re** [comment]
So I did look into this a bit. Looks like `esbuild` is stripping out comments but leaving the `{}` intact which is invalid JSX. Still thinking through a fix... `esbuild` doesn't allow comment preservation AFAICT.

**Comment by okikio** [comment]
Can't we support HTML comments?

**Comment by natemoo-re** [comment]
Just picked this back up and it seems to be working, not sure what was going on in the older version.

https://stackblitz.com/edit/github-qfawez?file=src%2Fpages%2Findex.mdx
