### ISSUE TITLE
🐛 BUG: False 404 logged for public files when `base` is set

### ISSUE THREAD

**Issue by AllanChain** [withastro/astro#3808]
### What version of `astro` are you using?

1.0.0-beta.63

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When a `base` is configured to `/blog` and the page requests an image from the `public/` folder via `src="/blog/full-logo-light.png"`, although the request succeeds and the image is correctly displayed, there is a false 404 message logged in the console:

```
[serve]    404                /blog/full-logo-light.png
```

The expected behavior is that the above message is never logged.

**Edit:** And if a `404.astro` file is added to `src/pages/`, the image will not load. The expected behavior is that the image will load anyway. 

### Link to Minimal Reproducible Example

https://github.com/AllanChain/astro-base-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue @AllanChain!

Since the bug is just an erroneous `console.log` but other behavior is working properly, I'm going to mark this as a relatively low priority for now. Hopefully we can circle back and tackle this soon, otherwise contributions are welcome!

**Comment by natemoo-re** [comment]
Thank you! I didn't realize there was more problematic behavior here than the `console.log` or I would bumped the priority. Really appreciate the fix.

Going to mark this as closed since your PR was merged in https://github.com/withastro/astro/pull/3942.
