### ISSUE TITLE
🐛 BUG: `injectRoute` path intercepted by dynamic route during dev

### ISSUE THREAD

**Issue by delucis** [withastro/astro#3809]
### What version of `astro` are you using?

v1.0.0-beta.73
v1.0.0-beta.63

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

npm

### What operating system are you using?

macOS / Stackblitz

### Describe the Bug

Routes added using `injectRoute` are intercepted by matching dynamic routes in a project in dev mode (maybe also in SSR? I haven’t tested that).

For example, say an integration injects a page at `/injected`. If the project also has a `src/pages/[slug].astro` route, the dynamic `[slug].astro` route will try to handle the request to `/injected` and (assuming `getStaticPaths` doesn’t include `slug: 'injected'`) print an error: `Route pattern matched, but no matching static path found`.

The same even applies when you have a `src/pages/[slug]/index.astro` (see second reproduction below), so I’m guessing _any_ root-level dynamic segment would trigger this.

This is an issue with the new image integration, because its `/_image` route breaks in projects using a dynamic route as described above.

Two possibilities:

1. On Discord, Fred suggested this could be a priority issue: we should treat injected routes as higher priority than local ones.

    I don’t know if this is true — what about the scenario where an integration injects a catch-all `[...path]` pattern but a local project can override it? Plausible for some of our speculative “no code, content-first” integration ideas.
    
    We don’t currently mention `injectRoute` in our [route priority docs](https://docs.astro.build/en/core-concepts/routing/#route-priority-order), but my instinct would be that injected routes have a lower priority than a project’s file routes.

2. Similar to #3621, we could treat dynamic routes as a stack where if the first route doesn’t provide a matching static path, the next is evaluated and so on. I personally feel this would be closer to the behaviour I expect.

Potentially related: #3451

#### `src/pages/[slug].astro` intercepts the injected route

https://stackblitz.com/edit/github-zmcb8k?file=astro.config.mjs

#### `src/pages/[slug]/index.astro` intercepts the injected route

https://stackblitz.com/edit/github-zmcb8k-rfjobw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue @delucis! I agree that this is a problem we need to fix!

I'm tagging this as a minor bug because I think the number of folks using `injectRoute` is quite low at the moment, so the surface area for this bug is somewhat low. 

Your two proposed solutions are great, but either one will be a larger task to think through our routing logic a bit more to account for this.

**Comment by delucis** [comment]
@tony-sull Do you think there's a workaround `@astrojs/image` could use while we wait for a fix? I'm wondering if injecting the route at `_astro/image` instead of `_image` might make clashes with a local `[path].astro` less likely? Wouldn't help if someone had a `...path` route but would be better than nothing.

**Comment by franzwilding** [comment]
@natemoo-re as I don't think this is a minor bug, because using `@astrojs/image` in combination with a `[path].astro` page is the most common usecase when you want to connect astro with a headless cms. It would be great, if there is a way that _image has higher priority than the dynamic page url.

**Comment by tony-sull** [comment]
Agreed, this really is a p4 bug now that `@astrojs/image` is heavily using the `injectRoute` API (was a fairly niche API not too long ago)

I'm finishing up a couple updates to markdown and MDX support but I may be able to pick this one up today :+1:
