### ISSUE TITLE
🐛 BUG: Astro does not respect `vite.build.manifest` option

### ISSUE THREAD

**Issue by chenxsan** [withastro/astro#3810]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I want to generate a `manifest.json` file for my server side use case, and I notice that vite provides this `manifest` option:

```
export default defineConfig({
  vite: {
    build: {
      manifest: true,
    },
  },
});
```
But astro doesn't seem to respect it.

You can run `npm run build` from the example link and there's no manifest file under `dist`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yqg5jq?file=astro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hey @chenxsan! It looks like we are hard-coding `manifest` to `false` but I'm not sure if there's a particular reason we're doing this. @matthewp might know...

https://github.com/withastro/astro/blob/b11e3b38ebb59ceec3479cbf580276d3b3bd657c/packages/astro/src/core/build/static-build.ts#L113

**Comment by natemoo-re** [comment]
Hi @chenxsan! I checked with @matthewp and the reason we disable Vite's option is because we actually run two Vite builds in parallel, so we have our own manifest format!

You can create an integration that uses the [`astro:build:ssr`](https://docs.astro.build/en/reference/integrations-reference/#astrobuildssr) hook to read our manifest and write it to wherever you need.

Feel free to reopen if you're still running into trouble!

**Comment by chenxsan** [comment]
@natemoo-re Thanks for the clarification.

I think I did run into trouble with the `astro:build:ssr` hook, here's the hook I tested:

```
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  integrations: [
    {
      name: 'manifest',
      hooks: {
        'astro:build:ssr': async ({ manifest }) => {
          console.log(manifest);
        },
      },
    },
  ],
});
```

I expect `npm run build -- --experimental-integrations` to output `manifest` data but unfortunately there's none in console. From the API document I can see all hooks are optional, so I have no idea what i might be missing.

Again, you can test the repository here https://stackblitz.com/edit/github-yqg5jq?file=astro.config.mjs&on=stackblitz

**Comment by matthewp** [comment]
@chenxsan The manifest is only created when deploying to SSR. You have to use one of the SSR adapters (or create your own). Are you attempting to create an adapter?

**Comment by chenxsan** [comment]
> 

Ah, I see. No, I'm not using any official SSR adapters listed here https://docs.astro.build/en/guides/server-side-rendering/ or creating one my self.

Here's my use case,

1. create pages with astro
2. build static pages
3. use those built static pages as templates in php - our server side is in php, not Node or Deno

Note that I won't use any features that would require client side hydration. Basically what I need is the SSG + `manifest.json`.

**Comment by matthewp** [comment]
If you need to know what pages are built you can use the `astro:build:done` hook. See this example: https://github.com/withastro/astro/blob/main/packages/integrations/sitemap/src/index.ts#L62

**Comment by chenxsan** [comment]
> If you need to know what pages are built you can use the `astro:build:done` hook. See this example: https://github.com/withastro/astro/blob/main/packages/integrations/sitemap/src/index.ts#L62

Not sure if I explained my use case clearly above.

Take this html code Astro generates for example:

```html
<!DOCTYPE html>
<!DOCTYPE html><html lang="en" class="astro-MGHQNGUJ">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
  <link rel="icon" type="image/x-icon" href="/favicon.ico">
	<title>Welcome to Astro.</title>
<link rel="stylesheet" href="/assets/f91153f8.6a904a26.css" /></head>
```
There's this `/assets/f91153f8.6a904a26.css` path, I would like to generate it in php with the manifest data, e.g.:

```php
<link rel="stylesheet" href="/assets/<?php echo manifest['main.js']->css; ?>" />
```

Otherwise I would have to update the path in php templates every time I build the static pages, E.g.:

```diff
- <link rel="stylesheet" href="/assets/f91153f8.6a904a26.css" /></head>
+ <link rel="stylesheet" href="/assets/f6773f8.6a904else.css" /></head>
```
