### ISSUE TITLE
🐛 BUG: Moving <head></head> into its own component produces bugs.

### ISSUE THREAD

**Issue by Elwood-P** [withastro/astro#3819]
### What version of `astro` are you using?

1.0.0-beta.63

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Take "Just the basics" template and move `<head></head>` and its contents into its own component:

```
---
// Layout.astro
import Head from "../components/Head.astro";
export interface Props {
    title: string;
}
const { title } = Astro.props as Props;
---

<!DOCTYPE html>
<html lang="en">
<Head title="title"/>
<!-- etc -->
```

```
---
// Head.astro
const { title } = Astro.props;
---

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <title>{title}</title>
</head>
```

Now when running dev, hmr.js is added twice. When running build any scripts and stylesheets are added twice.

/dist/index.html:
```
<!DOCTYPE html>
<!DOCTYPE html><html lang="en" class="astro-M64WE4MG">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">
  <link rel="icon" type="image/x-icon" href="/favicon.ico">
  <title>title</title>
<link rel="stylesheet" href="/assets/b98c4ddc.6d41d091.css" /></head>
<link rel="stylesheet" href="/assets/b98c4ddc.6d41d091.css" /><body>
<!-- etc -->
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tepoy4?file=src%2Flayouts%2FLayout.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Elwood-P** [comment]
`npm run build` from stackblitz example above:

![CleanShot 2022-07-05 at 07 37 41](https://user-images.githubusercontent.com/8029011/177265829-5b7f8e0d-051b-4edd-905d-948735cb083a.png)

**Comment by matthewp** [comment]
Thanks!
