### ISSUE TITLE
🐛 BUG: Unexpected React 18 warning during dev

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#3827]
### What version of `astro` are you using?

1.0.0-beta.63

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

When I run the https://github.com/withastro/docs site in development, I see a React warning in my console logs all of the time.

### Link to Minimal Reproducible Example

https://github.com/withastro/docs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Could you make sure you’ve run `pnpm i` recently? This was patched by @hippotastic in #3769 and we’ve updated the docs to a recent enough version that I don’t see that anymore.

**Comment by hippotastic** [comment]
Also, if the warning persists even after a `pnpm i --force`, could you post the warning here please?

**Comment by FredKSchott** [comment]
@matthewp I'm seeing this on an old branch of docs, so if its already been fixed then this is safe to close!
