### ISSUE TITLE
🐛 BUG: .astro <script> doesn't get updated

### ISSUE THREAD

**Issue by silveltman** [withastro/astro#3832]
### What version of `astro` are you using?

1.0.0-beta.63

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

windows

### Describe the Bug

JS written in a <script> tag on a .astro page doesn't get updated. When I add it initally it uses the code, but after that no updates, When I restart the dev-server the updates are applied. 

Howver, I do see the following in my vscode terminal: `00:40:44 [astro] reload C:/Users/silve/Documents/Web dev/astro/astro-reproduction/src/pages/debug.astro`

For a reproduction I did:
- npm create astro@latest
- npm i gsap
- make new page file (debug.astro, see reproduction)
- thats it.. 

### Link to Minimal Reproducible Example

https://github.com/silveltman/astro-reproduction

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arimgibson** [comment]
Not able to open the link to your minimal reproducable example @silveltman

**Comment by silveltman** [comment]
I'm not sure what's the problem there. However, it was basically the starter template. Via Discord I heard that it seems to be a windows problem. Should be fixen when vite 3 gets implemented. 

Also, for me the problem suddenly disappeared without a reason.

**Comment by natemoo-re** [comment]
Sounds like this problem has gone away? 

Other recent developments are:
- #3570 has been merged, so we'll be on Vite 3 very soon!
- #3932 overhauls our HMR handling, and I am unable reproduce this issue with the new implementation
