### ISSUE TITLE
🐛 BUG: Tailwind CSS Base layer overwritten when used via imported local stylesheet

### ISSUE THREAD

**Issue by kleemeo** [withastro/astro#3844]
### What version of `astro` are you using?

1.0.0-beta.63

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using `@layer base` directive in an **imported stylesheet** (e.g. global.css), the styles get overwritten by[ Tailwind's base layer](https://tailwindcss.com/docs/preflight) again after build/compile. Sometimes HMR or reload during dev server shows the style changes, but once you recompile via `npm run dev / build / preview` the custom styles appears to be overwritten by Tailwind base layer's properties again.

```css
/* ✅ this works to confirm stylesheet is connected*/
h1 {
  color: red;
} 

/* 
❌ this doesn't work because tailwind's base layer seems to overwrite again during build/recompile? 
It works when I add a !important tag at the end of the line because that's more specific than the tailwind base layer
*/
@layer base {
  h1 {
    @apply text-4xl text-green-500 font-bold;
  }
}
```

Current workaround is adding `!important` tag at the end of the tailwind @apply directive to make it more specific than the tailwind base layer. 

This also works when used directly in `index.astro` in a <style> tag

Seems like a resolve bug during compile/build time?

Looking at inspector, you can see it registered the @apply custom styles, but is filtered by the base layer's inherit properties.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/22482764/177683718-12778383-fd2d-4e75-98d7-e11bacfa23e9.png">

### Link to Minimal Reproducible Example

https://stackblitz.com/github-hch4sc
- Imported stylesheet using Tailwind
- Pertains to Tailwind's [Base layer properties](https://tailwindcss.com/docs/preflight)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kleemeo** [comment]
Looking at the compiled html, I see that Tailwind's base preflight properties are injected twice.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/22482764/177786852-60a53c46-477a-4057-9965-08452f4db8fa.png">

#### First "data-astro-injected" block
```html

/*👇 Tailwind Preflight Code*/

<style data-astro-injected="">/*
! tailwindcss v3.1.4 | MIT License | https://tailwindcss.com
*//*
1. Prevent padding and border from affecting element width. (https://github.com/mozdevs/cssremedy/issues/4)
2. Allow adding a border to an element by just adding a border-width. (https://github.com/tailwindcss/tailwindcss/pull/116)
*/

*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: #e5e7eb; /* 2 */
}

...

/*
Remove the default font size and weight for headings.
*/

h1,
h2,
h3,
h4,
h5,
h6 {
  font-size: inherit;
  font-weight: inherit;
}

...

/* 👇 my custom styles here*/

  h1 {
  font-size: 2.25rem;
  line-height: 2.5rem;
  font-weight: 700;
}

...

</style>
```

#### Second "data-astro-injected" block, whole block of Tailwind Base Preflight code without my custom H1, causing the overwriting

```html

/*👇 Tailwind Preflight Code 2nd time*/

<style data-astro-injected="">/*
! tailwindcss v3.1.4 | MIT License | https://tailwindcss.com
*//*
1. Prevent padding and border from affecting element width. (https://github.com/mozdevs/cssremedy/issues/4)
2. Allow adding a border to an element by just adding a border-width. (https://github.com/tailwindcss/tailwindcss/pull/116)
*/

*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: #e5e7eb; /* 2 */
}

[...]

h1,
h2,
h3,
h4,
h5,
h6 {
  font-size: inherit;
  font-weight: inherit;
}

[...]
</style>
```

**Comment by kavalerov** [comment]
@kleemeo Thank you so much... I've just spent days trying to understand what is happening and missed this part of Astro-Tailwind docs - and now it is all working. Thanks

**Comment by molavec** [comment]
> After digging the [Astro-Tailwind config docs](https://github.com/withastro/astro/tree/main/packages/integrations/tailwind), I found the Astro-specific reason:
> 
> > By default, the integration imports a basic base.css file on every page of your project. This basic CSS file includes the three main @tailwind directives `@tailwind base; @tailwind components; @tailwind utilities;`
> > To disable this default behavior, set config.applyBaseStyles to false. This can be useful if you need to define your own base.css file (to include a [@layer directive](https://tailwindcss.com/docs/functions-and-directives#layer), for example). This can also be useful if you do not want base.css to be imported on every page of your project.
> 
> ```js
> // astro.config.mjs
> export default {
>   integrations: [tailwind({
>     // Disable injecting a basic `base.css` import on every page.
>     config: { applyBaseStyles: false },
>   })],
> }
> ```

Thanks @kleemeo!

I will add something. Maybe this could be useful for someone:
if `injecting base.css` is desable but you want still get base styles append imports to your global:

global.css

```css
/* Inject manually as applyBaseStyle is set as false */ 
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by anasouardini** [comment]
I removed the base styles, since it seems to be fix the issue of overriding as mentioned above by `kleemeo`:
```js
    tailwind({
          config:{applyBaseStyles: false}
      }),
```
But now tailwind stopped working!!

Then I created `index.css`, as suggested by `molavec`, and linked it to the `head` of my website.
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

p{margin-bottom: 1rem}
```
But only the last line in my `index.css` has an effect.

How do I just do it the normal way, like when you use it in a react app?

**Comment by brandondeweese-reify** [comment]
@anasouardini is right. This isn't working.

**Comment by brandondeweese-reify** [comment]
Remove 'config:{}' and it works. Use:

```
tailwind({
     applyBaseStyles: false
}),
```

**Comment by kleemeo** [comment]
Yes, please read the new docs, they have updated the config object:
https://github.com/withastro/astro/tree/main/packages/integrations/tailwind#applybasestyles

From the new docs:
```js
// astro.config.mjs
import { defineConfig } from 'astro/config';

export default defineConfig({
  integrations: [
    tailwind({
      // Example: Disable injecting a basic `base.css` import on every page.
      // Useful if you need to define and/or import your own custom `base.css`.
      applyBaseStyles: false,
    }),
  ],
});
```

**Comment by Alvarordev** [comment]
I removed basestyles to implement css variables theming. Everything is working fine, except for the hot reload.

```
export default defineConfig({
  integrations: [tailwind({
    applyBaseStyles: false,
  }), react()]
});
```

```
// Layout.astro
<style is:global>
  @tailwind base;
  @tailwind components;
  @tailwind utilities;

  @layer base {
    :root {
      --background: 0 0% 100%;
      ....
      }
</ style>
```

This is mainly what I changed, and a script to check the localstorage so it adds the theme class to the html. Anyone else, had a problem with hotreload?
