### ISSUE TITLE
🐛 BUG: RSS "Cannot read properties of undefined (reading 'replace')"

### ISSUE THREAD

**Issue by zellwk** [withastro/astro#3846]
### What version of `astro` are you using?

1.0.0-beta.64

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The RSS plugin throws an error that says "Cannot read properties of undefined (reading 'replace')" even when all necessary parameters are included. 

![CleanShot 2022-07-07 at 18 46 58](https://user-images.githubusercontent.com/3607637/177756395-ead207ab-c38f-4de2-9d55-83f6633495ee.png)

I traced the error to `/rss/dist/index.js`. It looks like `createCanonicalURL` was called either without `url` or `base`. 

![CleanShot 2022-07-07 at 18 49 08](https://user-images.githubusercontent.com/3607637/177756459-921ec2e1-4d09-409d-9942-bb85e4d4aa01.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-f6teq2?file=package.json

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@zellwk For your RSS issue, a `link` is required for each item. I'll update this to provide a better error message.

**Comment by matthewp** [comment]
@zellwk if you're still having the `env.SITE` issue can you open a separate bug. I confirmed that we do have a test for this, so there must be something different about your setup. Thanks!
