### ISSUE TITLE
🐛 BUG: Rendering an array of data with map() fails inside an HTML table

### ISSUE THREAD

**Issue by ownchoice** [withastro/astro#3849]
### What version of `astro` are you using?

1.0.0-beta.64

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Note: it seems to be the same bug as [#1939](https://github.com/withastro/astro/issues/1939), which was fixed already, so maybe it got reintroduced.

I'm having a problem mapping an array to TD elements inside an HTML Table with Astro's JSX, an error that doesn't occur with React's JSX.

It fails in Astro's JSX but works on React's JSX (and Preact's)

```astro
---
// file.astro
const names = ['Knocky', 'Flor', 'Ella', 'Juan'];
---
<table>
  <tr>
    {names.map((name) => (
      <td>{name}</td>
    ))}
  </tr>
</table>
```

But when not using the variable inside the map function, it works:

```astro
---
// file.astro
const names = ['Knocky', 'Flor', 'Ella', 'Juan'];
---
<table>
  <tr>
    <!-- Works but it's not using the variable -->
    {names.map((name) => (
      <td>name</td>
    ))}
  </tr>
</table>
```

Error message:

```
500: Internal Error
Transform failed with 1 error:
/home/projects/github-j85rmj/src/pages/withoutReact.astro:53:14: ERROR: Expected "}" but found "$$render"
Error: Transform failed with 1 error:
/home/projects/github-j85rmj/src/pages/withoutReact.astro:53:14: ERROR: Expected "}" but found "$$render"
    at failureErrorWithLog (/home/projects/github-j85rmj/node_modules/esbuild/lib/main.js:1605:15)
    at eval (/home/projects/github-j85rmj/node_modules/esbuild/lib/main.js:1394:29)
    at eval (/home/projects/github-j85rmj/node_modules/esbuild/lib/main.js:666:9)
    at handleIncomingPacket (/home/projects/github-j85rmj/node_modules/esbuild/lib/main.js:&#8230;
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-j85rmj

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Yep, this is a known compiler issue. Hoping to fix this (and a number of other `table` related bugs) as soon as I can!

**Comment by natemoo-re** [comment]
Closing as fixed in the latest release! https://stackblitz.com/edit/github-j85rmj?file=src%2Fpages%2Findex.astro
