### ISSUE TITLE
🐛 BUG: Installing vitest and writing test.ts files causes errors

### ISSUE THREAD

**Issue by kungpaogao** [withastro/astro#3856]
### What version of `astro` are you using?

1.0.0-beta.64

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

## Context
I wrote a script (`.ts` file) to fetch and parse some data from Notion during build time. I wanted to test my parser, so I installed `vitest` and made a `.test.ts` file. However, this creates a bunch of errors when I run `yarn dev`. This doesn't seem to prevent the dev server from starting/running, nor does it affect the build.

## Questions
- Is it possible to ignore files (like `**/*.test.ts`) during Astro builds?
- Do these scripts get shipped to the user?
- Is it related to this issue: https://github.com/vitest-dev/vitest/issues/1118?
- Is there official guidance on writing tests in Astro projects?

## Error output
```
[vite] error while updating dependencies:
Error: Build failed with 10 errors:
node_modules/local-pkg/dist/shared.mjs:54:9: ERROR: No matching export in "browser-external:fs" for import "existsSync"
node_modules/local-pkg/dist/shared.mjs:54:21: ERROR: No matching export in "browser-external:fs" for import "promises"
node_modules/local-pkg/dist/shared.mjs:62:13: ERROR: No matching export in "browser-external:node:fs" for import "promises"
node_modules/local-pkg/dist/shared.mjs:235:14: ERROR: No matching export in "browser-external:node:fs" for import "promises"
node_modules/local-pkg/index.mjs:1:9: ERROR: No matching export in "browser-external:path" for import "join"
...
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rpxbwm?file=src/lib/something.test.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for the report! I think this is a really small fix, I'm going to take a look at it now.

**Comment by natemoo-re** [comment]
OK this was not as small as I'd hoped! Something fishy going on with Astro + Vitest. Hoping we can look into this more soon.

**Comment by natemoo-re** [comment]
That's what I tried! I went through pretty much every configuration of `vite.ssr.external` and `vite.optimizeDeps.exclude` I could think of, but the errors on `vitest` dependencies were persistent.

I wonder if it has something to do with Astro projects not having a `vite.config.*` file? Astro creates a pre-configured Vite config that `vitest` might need to also use, but I think it only supports `vite.config.*` files.

**Comment by natemoo-re** [comment]
Just to close the loop on this, I think closing this issue is totally fair! The `getViteConfig` helper will allow you to run `vitest` inside an Astro project.

What we **don't** have yet is an easy way to test the output of Astro pages/components. That will require some new features, but we'll hopefully be looking into this for v1.1.0. Getting Vitest + Astro working together is something I'm really excited about!
