### ISSUE TITLE
🐛 BUG: Importing node modules throws error in svelte

### ISSUE THREAD

**Issue by Levminer** [withastro/astro#3872]
### What version of `astro` are you using?

1.0.0-beta.64

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

* Import the crypto module
* Create a hash
* The hash gets created and logged to the console
* Svelte throws `[HMR][Svelte] Unrecoverable HMR error in <Counter>: next update will trigger a full reload`

![image](https://user-images.githubusercontent.com/33373714/178068752-7f01a4b2-ad3f-47a3-828e-76b14dd0e8fc.png)

* I tried to import the module in index.astro, works fine

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6etaxx?file=src%2Fcomponents%2FCounter.svelte&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This works if you remove the `client:visible`. That's because `node:crypto` doesn't work in the browser. See https://github.com/vitejs/vite/discussions/3126#discussioncomment-2875824
