### ISSUE TITLE
🐛 BUG: Markdown does not wrap certain tags with <p>

### ISSUE THREAD

**Issue by martpie** [withastro/astro#3875]
### What version of `astro` are you using?

beta-65

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I am porting a website to Astro, and I noticed markdown is not behaving the same as `frontmatter-markdown-loader` and remark by default in general.

Remark demo: https://codesandbox.io/s/ppq2i?file=/src/index.js -> change the markdown file with the following

```md
This will render a p

<small>This will only render small, but not wrapped in p in astro, but wrapped in p in remark</small>
```

Is this an intentional behavior? forcing to manually wrap top-level `<small>` in `<p>` is a little bit cumbersome.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cefvtb?file=src/pages/index.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by hippotastic** [comment]
This is intentional as per the MDX specification. If you want to render block-level Markdown content (like paragraphs, headings, lists) inside a JSX element, the opening and closing tags of that element must be on their own separate lines.

**Comment by martpie** [comment]
Thanks for looking into this, I actually did not realize it was using mdx under the hood, but it makes a lot of sense. Doing as you said unfortunately render `<small><p>something</p></small>`, which is not valid HTML.

I'll check the MDX repo to see if anyone else faced the same issue before, and what should be the right solution.

**Comment by martpie** [comment]
Playing with the MDX playground, I can reproduce it, so I will open an issue upstream.

**Comment by hippotastic** [comment]
Good luck! They will probably close it, as I've seen issues like that in the past being responded to in a similar fashion:

Yes, you can create invalid HTML by nesting tags in Markdown manually like you did, and the solution is not to do something like this. 😄

**Comment by martpie** [comment]
fyi, this issue does not happen in rc1 as mdx is not enabled by default 🚀
