### ISSUE TITLE
🐛 BUG: Svelte hydrated component is being duplicated in Safari

### ISSUE THREAD

**Issue by acrusella** [withastro/astro#3890]
### What version of `astro` are you using?

^1.0.0-beta.65

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When working on a Svelte component with `client:load` hydration, the component gets duplicated after the second reload only in Safari browser.

I could reproduce the problem when building a new astro+svelte project and serving it on a local http-server, because running astro preview does not reproduce the problem. Same problem behaviour when deploying my static pages into an Amazon S3 bucket.
No console errors are seen.

Problem being reproduced in a new astro test project:

https://user-images.githubusercontent.com/103419048/178304816-3aa0201b-8e7a-411b-bc8f-22a48fbb8d6e.mov

Stackblitz shared, but it's not possible to reproduce in safari as it is not a supported browser.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-acrusella?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @acrusella, the other Safari issue you submitted was fixed in beta.66. I'm curious if this one was also fixed? Having some trouble recreating at the moment.

**Comment by matthewp** [comment]
Awesome! Saves me some more work 😅
