### ISSUE TITLE
🐛 BUG: Update broke `astro dev`/SSR

### ISSUE THREAD

**Issue by SKFrozenCloud** [withastro/astro#3910]
### What version of `astro` are you using?

1.0.0-beta.69

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn/npm

### What operating system are you using?

Linux

### Describe the Bug

Updated the astro package from version `1.0.0-beta.44` to `1.0.0-beta.69` and it broke.

You can explicitly set the version in the `package.json` of the astro package in the link below to see the effects.

`astro build && astro preview` works as usual though.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8x99bh-bud4qs

This is from https://github.com/withastro/astro/issues/3494

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please provide a clearer description of what broke, not just that something broke.

**Comment by SKFrozenCloud** [comment]
If you open the link to the example you can see that `astro dev` return 500 Internal Error in the new versions of `1.0.0-beta.69` but if you explicitly set the version to `1.0.0-beta.44` it works.
