### ISSUE TITLE
🐛 BUG: Unable to escape `<` as `&lt;` and `{` as `&#123;` in Markdown

### ISSUE THREAD

**Issue by hippotastic** [withastro/astro#3916]
### What version of `astro` are you using?

1.0.0-beta.70

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When rendering Markdown pages, we seem to decode HTML entities used in the Markdown content before processing JSX elements and JS expressions.

It is therefore not possible to escape the `<` character as `&lt;`, and also not possible to prevent treating an opening curly brace as the beginning of a JS expression by using its HTML entity `&#123;` instead.

This leads to Markdown content like `&lt;i&gt;This should NOT be italic&lt;/i&gt;` being rendered as an italic line, and `&#123;some content&#125;` resulting in an error 500.

These issues turned up as we were about to document the correct way to escape control characters in Markdown [here](https://github.com/withastro/docs/issues/987). The only alternative we currently have to escape characters is to wrap them inside a JS expression (e.g. using `{'\u007B'}` to represent a single opening curly brace), but this looks like a hack rather than a proper solution, so we would prefer to prevent the unwanted decoding instead.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-upjkdu?file=src%2Fpages%2Findex.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garfieldnate** [comment]
Not sure if it's off-topic here, but it would be much nicer to be able to just use a slash to escape brackets. If I have to use the HTML escape code, then generally I have to stop what I'm doing and search the internet for the correct code, which interrupts the writing workflow.

**Comment by andersk** [comment]
`\<` and `\{` are as much a part of the MDX standard as `&lt;` and `&#123;`, since MDX is [based on CommonMark](https://mdxjs.com/docs/what-is-mdx/#markdown), which [allows](https://spec.commonmark.org/0.30/#backslash-escapes) any ASCII punctuation character to be backslash-escaped. `remark-mdx`, `@mdx-js/mdx`, and `micromark-extension-mdx` correctly support all four.

```js
> (await import('remark')).remark().use(await import('remark-mdx')).parse("escape testing: \\< &lt; \\{ &#123;").children[0].children
[
  {
    type: 'text',
    value: 'escape testing: < < { {',
    position: { start: [Object], end: [Object] }
  }
]
> (await import("@mdx-js/mdx")).compileSync("escape testing: \\< &lt; \\{ &#123;").value
…
  '  return _jsx(_components.p, {\n' +
  '    children: "escape testing: < < { {"\n' +
  '  });\n' +
…
> (await import("micromark")).micromark("escape testing: \\< &lt; \\{ &#123;", {extensions: [(await import("micromark-extension-mdx")).mdx()]})
'<p>escape testing: &lt; &lt; { {</p>'
```

**Comment by matthewp** [comment]
@andersk is that relevant to this issue?

**Comment by matthewp** [comment]
I'm still working on this. I've got enough information to know that it's a compiler bug related to `set:html`. Still working on a fix.

**Comment by matthewp** [comment]
This should fix it: https://github.com/withastro/compiler/pull/481

**Comment by matthewp** [comment]
Adding a test to within astro as well.
