### ISSUE TITLE
🐛 BUG: Unable to group :global styles with Sass

### ISSUE THREAD

**Issue by mayank99** [withastro/astro#3929]
### What version of `astro` are you using?

1.0.0-beta.71

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Astro's scoped styles are usually great! But sometimes I need to nest some global styles under a scoped selector, like so:
```css
.parent { ... }
.parent :global(.child) { ... }
.parent :global(.child .grandchild) { ... }
```

This gets repetitive/tedious really quickly. In CSS modules this is easy to solve with a preprocessor like Sass. Their [docs](https://github.com/css-modules/css-modules#usage-with-preprocessors) even recommend using preprocessors for grouping global styles under `:global`.
```scss
.parent {
  // ...

  :global {
    .child {
      // ...

      .grandchild {
        // ...
      }
  }
}
```

This does not work in Astro. When `:global` is used without a selector inside the parentheses, it gets treated as `global` (without colons). e.g. The above snippet results in the following:
```css
.parent { ... }
.parent global .child { ... }
.parent global .child .grandchild { ... }
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-id8wcn?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for the suggestion @mayank99! This does sound like a great feature, but I'm not sure when we'll have have the bandwidth to implement it.

This seems like a great feature request to discuss in our [`RFC`](https://github.com/withastro/rfcs/discussions) repo!
