### ISSUE TITLE
🐛 BUG: Type 'astroHTML.JSX.Element' is not assignable to type 'import(".../solid-js/types/jsx").JSX.Element'.

### ISSUE THREAD

**Issue by thetarnav** [withastro/astro#3945]
### What version of `astro` are you using?

1.0.0-beta.72

### Are you using an SSR adapter? If so, which one?

doesn't apply

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

The last version seems to have changed the expected return types of islands. In the types, Solid components can return HTML elements too, which of course doesn't happen on the server, but the types remain.

```
Type 'astroHTML.JSX.Element' is not assignable to type 'import(".../solid-js/types/jsx").JSX.Element'.
```

![image](https://user-images.githubusercontent.com/24491503/179370789-5a2cf060-ac1f-4b3f-af6f-6d1c0cff5e41.png)

### Link to Minimal Reproducible Example

sorry, no repro :P

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is a bit hard to debug with no reproduction, could you at least share the code of your Astro and Solid components?

**Comment by mthlemos** [comment]
It also happens to me when using React with Typescript.

Here's my `tsconfig.json`:

```json
{
  "compilerOptions": {
    // Enable top-level await, and other modern ESM features.
    "target": "ESNext",
    "module": "ESNext",
    // Enable node-style module resolution, for things like npm package imports.
    "moduleResolution": "node",
    // Enable JSON imports.
    "resolveJsonModule": true,
    // Enable stricter transpilation for better output.
    "isolatedModules": true,
    // Add type definitions for our Astro runtime.
    "types": [
      "astro/client",
      "@types/react",
      "@types/react-dom"
    ]
  }
}
```

**Comment by thetarnav** [comment]
Example component: https://github.com/thetarnav/renkidzielo/blob/main/renkidzielo/src/islands/ui/socials/Socials.tsx
tsconfig: https://github.com/thetarnav/renkidzielo/blob/main/renkidzielo/tsconfig.json

**Comment by Princesseuh** [comment]
Thank you both, seems to be some sort of regression. I'll take a look this week
