### ISSUE TITLE
🐛 BUG: Typescript error while using Astro.glob() to import components

### ISSUE THREAD

**Issue by space-otter** [withastro/astro#3953]
### What version of `astro` are you using?

v1.0.0-beta.72

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

While using the result of `Astro.glob(path)` to import and render `.astro` components,
an Typescript error occurs after I try to access `.default`.

```
'comp.default' cannot be used as a JSX component.
  Its return type 'Promise<AstroComponent> | Response' is not a valid JSX element.
    Type 'Promise<AstroComponent>' is not assignable to type 'Element'.ts(2786)
```

The following code shows the Minimal Reproducible Example:

```astro
---
const components = await Astro.glob('./../components/*.astro');
---

<!--- ... --->
    {components.map((comp) => <comp.default />)}
<!--- ... --->
```

Even more strange I can reproduce the error on 3 different machines (2 macbooks and 1 linux laptop),
but @delucis don't on his macbook. Also the example on Stackblitz does not throw an error.

[Github local example](https://github.com/space-otter/Astro-Glob-TS-Bug)
[Stackblitz remote example](https://stackblitz.com/edit/github-ffcvsd-daauk6?file=README.md)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ffcvsd-daauk6?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello, thanks for creating this issue. This is a regression in `beta.72`, same issue as https://github.com/withastro/astro/issues/3945 so I'll be closing as a duplicate!
