### ISSUE TITLE
🐛 BUG: Console output while building a js file with dynamic routes parameter in pages is wrong

### ISSUE THREAD

**Issue by pointout** [withastro/astro#3954]
### What version of `astro` are you using?

1.0.0-beta.72

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

The console output while building a file ``[parameter].json.js`` in the ``pages``-directory is saying, that this is created to ``parameter.json/index.html``, but the files are build correctly to ``parameter.json`` 

Output stackblitz example:
```
src/pages/[orderno].json.js
  └─ /2012.json/index.html (+4ms)
  ``` 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6mexhr?file=src%2Fpages%2F[orderno].json.js&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Yep, that should definitely be cleaned up!  Thanks for opening this issue, we're focusing heavily on cleanup and polish in preparation for a 1.0 release, looks like this should be an easy win to clean up the logging there :+1:
