### ISSUE TITLE
🐛 BUG: vite.build.sourcemap does not generate sourcemaps for client-side components on build

### ISSUE THREAD

**Issue by Tc-001** [withastro/astro#3970]
### What version of `astro` are you using?

1.0.0-beta.72

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Sourcemaps are useful for debugging components while developing an application. But there are also tools (Ex. Sentry), that can use the sourcemaps in production to get a similar experience with in-the-wild bugs.

This functionality is currently unavailable however, as astro fails to generate soucemaps on build

## The bug
1. Clone and set up https://github.com/withastro/astro/tree/latest/examples/framework-svelte
2. Set `vite.build.sourcemap` in `astro.config.mjs` to true
3. Build the site

**Expected:** A sourcemap file (`*.js.map`) for each client-side script in `./dist`, as well as the script itself referencing the sourcemap as per [vite](https://vitejs.dev/config/build-options.html#build-sourcemap)

**Actual:** an almost empty `entry.mjs.map` with no modifications to other files

```
{"version":3,"file":"entry.mjs","sources":[],"sourcesContent":[],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"}
```

This was also in the build logs:
```
Sourcemap is likely to be incorrect: a plugin (astro:build) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (astro:vite-plugin-env) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
...
```

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/tree/latest/examples/framework-svelte

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Tc-001** [comment]
On a closer look there do seem to be some sourcemaps in `./dist/chunks`, but they have the same issue as `entry` and are not referenced anywhere as far as I can see 

(also maybe only for markdown pages? Unsure)

**Comment by natemoo-re** [comment]
Ooh very strange! Thanks for opening an issue, I know digging into sourcemaps is definitely on our list.

This would be great to fix.

**Comment by pikeas** [comment]
Happening in dev as well in 1.0rc3:

```
[serve]    404 /@id/@astrojs/vue/@astrojs_vue_client__js.js.map
```

**Comment by matthewp** [comment]
@natemoo-re I'm going to hand this one over to @bluwy.

**Comment by bluwy** [comment]
Gimme

**Comment by matthewp** [comment]
This would be a good one to create a test for.

**Comment by pikeas** [comment]
Still happening with 1.0.0.


```
$ npm run dev

> project@0.0.1 dev
> astro dev

  🚀  astro  v1.0.0 started in 59ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

03:21:13 PM [serve]    404 /@id/astro/runtime/client/astro_runtime_client_hmr__js.js.map
03:21:13 PM [serve]    404 /@id/@astrojs/vue/@astrojs_vue_client__js.js.map
```

**Comment by bluwy** [comment]
@pikeas I believe that's related to #4219 in dev mode.

**Comment by villanuevadani** [comment]
I do not see sourcemaps on build (astro version: 2.6.6). I am adding `sourcemap: true` in `vite` section of the Astro Config; what am I doing wrong?
