### ISSUE TITLE
🐛 BUG: Astro is built fine but crash at runtime when using Netlify ssr adapter

### ISSUE THREAD

**Issue by eagrwx** [withastro/astro#3984]
### What version of `astro` are you using?

1.0.0-beta.73

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

The basic starter Astro project using Netlify SSR adapter works just fine. However, when you build this, netlify build logs say:
 
```
The following Node.js modules use dynamic expressions to include files: 
- astro

Because files included with dynamic expressions aren't bundled with your serverless functions by default, this may result in an error when invoking a function. To resolve this error, you can mark these Node.js modules as external in the [functions] section of your `netlify.toml` configuration file:

[functions]
external_node_modules = ["astro"]
```

After adding this to the netlify.toml file and deploying again, still the build is fine but I get this error in runtime:

```
An unhandled error in the function code triggered the following message:

Error - require() of ES Module /var/task/node_modules/astro/dist/core/app/index.js from /var/task/.netlify/functions-internal/entry.js not supported. Instead change the require of index.js in /var/task/.netlify/functions-internal/entry.js to a dynamic import() which is available in all CommonJS modules.

Stack trace
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/node_modules/astro/dist/core/app/index.js from /var/task/.netlify/functions-internal/entry.js not supported.
Instead change the require of index.js in /var/task/.netlify/functions-internal/entry.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/var/task/.netlify/functions-internal/entry.js:12164:18)
    at Object.<anonymous> (/var/task/entry.js:1:18)
    at _tryRequireFile (file:///var/runtime/index.mjs:654:37)
    at _tryRequire (file:///var/runtime/index.mjs:704:25)
    at _loadUserApp (file:///var/runtime/index.mjs:721:22)
    at Object.module.exports.load (file:///var/runtime/index.mjs:741:27)
    at file:///var/runtime/index.mjs:781:34
    at file:///var/runtime/index.mjs:783:3
    at async Promise.all (index 0)
```

The public repo to reproduce the issue:

https://gitlab.com/eagrwx/astro-netlify-with-problem

If you deploy the `main` branch on Netlify, there will be no problem.
If you deploy the `bug` branch on Netlify, you'll see the bug as described above.

### Link to Minimal Reproducible Example

with bug:
https://deploy-preview-1--tourmaline-kringle-4c0f3f.netlify.app/

working fine:
https://62d7a14a230c1277c6716f21--tourmaline-kringle-4c0f3f.netlify.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by eagrwx** [comment]
the repo to reproduce the issue:

https://gitlab.com/eagrwx/astro-netlify-with-problem

**Comment by natemoo-re** [comment]
Thank you for the repro links! Definitely some fun CJS/ESM compat issues happening here. We'll take a look as soon as we can.

**Comment by matthewp** [comment]
Taking a look as this doesn't appear to be related to a dependency.

**Comment by matthewp** [comment]
@eagrwx What version of Astro was this working ok on?

**Comment by eagrwx** [comment]
Hi Matthew, I'm pretty new to Astro, so I don't know if it was working on previous versions of Astro or not.

**Comment by eagrwx** [comment]
The thing I noticed is that, it breaks when you add 
```
[functions]
external_node_modules = ["astro"]
```
to the netlify.toml and gets back to working if you remove that line.

**Comment by matthewp** [comment]
@eagrwx So I think the warning you're seeing telling you to add that to your toml file can be ignored. It doesn't seem to have any effect on the ability to render in Netlify.

Going to close as I don't think there's anything actionable that can be done here, and deploying to Netlify does work in SSR. Let me know if anything I'm saying here is incorrect and I'll reopen.

**Comment by jackvhall** [comment]
This is currently an issue for me. I can confirm that adding the line:
```toml
[functions]
  external_node_modules = ["astro"]
```

to `netlify.toml` causes this error, but without it, I end up with `Invocation failed` error when loading the page.

**Comment by nickmickley** [comment]
@jackvhall did you ever figure this out? I'm having the same issue.

**Comment by gigig987** [comment]
same issue here too @jackvhall

**Comment by briankgarland** [comment]
I am having this problem as of Jan 3rd 2022. Anyone found a fix?

**Comment by Ohhhh** [comment]
Same issue here.
Works fine when delete
`[functions]
  external_node_modules = ["astro"]`
from `netlify.toml`

**Comment by HialeahLiam** [comment]
> This is currently an issue for me. I can confirm that adding the line:
> 
> ```toml
> [functions]
>   external_node_modules = ["astro"]
> ```
> 
> to `netlify.toml` causes this error, but without it, I end up with `Invocation failed` error when loading the page:
> 
> ```
> [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) - The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
> ```

I'm having the same issue. I get those same error either including "astro" as external_node_module or excluding it.
