### ISSUE TITLE
🐛 BUG:  Transform failed - Expected "}" but found "{"

### ISSUE THREAD

**Issue by rnwolf** [withastro/astro#3985]
### What version of `astro` are you using?

1.0.0-beta.73

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

After upgrading from .63 to .73 I get the following error

[astro:build] Transform failed with 1 error:
C:/Users/rnwol/workspace/astro-throughputfocus-com/src/components/authors.astro:51:71: ERROR: Expected "}" but found "{"
file: C:/Users/rnwol/workspace/astro-throughputfocus-com/src/components/authors.astro
 error   Transform failed with 1 error:
  C:/Users/rnwol/workspace/astro-throughputfocus-com/src/components/authors.astro:51:71: ERROR: Expected "}" but found "{"
  File:
    C:/Users/rnwol/workspace/astro-throughputfocus-com/src/components/authors.astro
  

### Link to Minimal Reproducible Example

https://github.com/rnwolf/astro-throughputfocus-com

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@natemoo-re I can take this one if you don't think you'll have time to tackle it soon.

**Comment by natemoo-re** [comment]
Hey @rnwolf! I haven't tracked down exactly what changed in the compiler yet, but I noticed that your code is as follows:

```astro
{authors &&
  <h2 class="mt-4" >Authors</h2>
  {authors.map((author) => <AUTHOR author={getAuthorByKey(authorData,author)} level={level}/>)}
}
```

The compiler seems to be getting tripped up because the elements inside the expression don't share a root node. This _should_ work, but it seems to be an edge case.

As a workaround, updating to wrap the expression content in a Fragment (`<>`) seems to do the trick.

```astro
{authors && <>
    <h2 class="mt-4" >Authors</h2>
    {authors.map((author) => <AUTHOR author={getAuthorByKey(authorData,author)} level={level}/>)}
  </>
}
```

**Comment by rnwolf** [comment]
@natemoo-re got that working again. Thank you. 
Now onward to the upgrading to the 1.0 release candidate.
