### ISSUE TITLE
📘 Docs: Improve `@astrojs/image` README docs

### ISSUE THREAD

**Issue by tony-sull** [withastro/astro#3999]
### What version of `astro` are you using?

1.0.0-beta.73

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

Notes from the image bug bash on 7/20 -

- Usage section should really have API details for the `<Image>` and `<Picture>` components
- document how to create a custom loader/service
- document `getImage` and `getPicture` APIs
- add an example of custom styling with `<Image class="..."/ >` and `<Picture class="..." />`

### Link to Minimal Reproducible Example

https://npmjs.com/@astrojs/image

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dkotik** [comment]
This issue needs to be reopened. getImage documentation is wrong. Here is a snippet I ended up using instead of passing a string path:

```
import { getImage } from "@astrojs/image";
const { src: cardImage } = await getImage({
    src: import("./share.png"),
    width: 20,
    aspectRatio: 16/9,
    format: "jpg"
});
```
