### ISSUE TITLE
🐛 BUG: class:list directive adding class attribute when undefined

### ISSUE THREAD

**Issue by BryceRussell** [withastro/astro#4001]
### What version of `astro` are you using?

v1.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

```
---
const {
  tag: Tag,
  ...attrs
} = Astro.props
---
<Tag class:list={attrs.class}>
  <slot />
</Tag>
```
When creating an element dynamically using a prop, if class:list directive is undefined it still adds the 'class' attribute to the element like so: `<div class></div>`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cqnqlh

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by BryceRussell** [comment]
Found a bug in my package that was using an older version of astro-json-element that uses the class:list directive which applies the class attribute if undefined

Although it is not the bug I submited it would be nice if the class:list directive did not apply the class attribute if it is undefined

**Comment by FredKSchott** [comment]
Fixed in RC! If you're still seeing this behavior, please let us know and we'll reopen

**Comment by BryceRussell** [comment]
@FredKSchott I updated my minimal reproduction example to the new 1.0.4 version and I am still seeing this behavior

**Comment by FredKSchott** [comment]
Interesting! I know a PR came through to fix this, but if you can still reproduce it may not have covered 100% of cases. Reopening to take a look

**Comment by rishi-raj-jain** [comment]
Thanks for the great minimal reproduction @BryceRussell, I've solved the issue in the PR linked above.
