### ISSUE TITLE
🐛 BUG: Solid JSXElement type mismatch against Astro Element

### ISSUE THREAD

**Issue by space-otter** [withastro/astro#4005]
### What version of `astro` are you using?

v1.0.0-beta.73

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Importing any Solid component into a `.astro` component results in following error:

```astro
---
import Example from "./Example";

const slogans = [
  ["Hello", "Bonjour", "Guten Tag"]
]
---
<!--- ... --->
  <article>
    <Example slogans={slogans} client:idle />
  </article>
<!--- ... --->
```

```
'Example' cannot be used as a JSX component.
  Its return type 'import("project/node_modules/.pnpm/solid-js@1.4.7/node_modules/solid-js/types/jsx").JSX.Element' is not a valid JSX element.
    Type 'number' is not assignable to type 'Element'.
```

`Example` is the imported `.jsx` module.
It seems that the definition of `Element` do not allow nodless return types like `number | string `. 
@Princesseuh I had in mind that somebody already reported some similar issue, but I couldn't find it.
Maybe this is also a regression in beta.73.

**I cannot reproduce the error via Stackblitz. Same situation as #3953, but #3953 got fixed.**

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-solid?file=src/components/Counter.jsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by space-otter** [comment]
Found the related issue #3945, which was closed.

**Comment by Princesseuh** [comment]
I cannot reproduce this locally. The current definition of `Element` (in `beta.73`) is `type Element = HTMLElement | any;`, which should allow everything and is the same as it was before the regression in `beta.72`

StackBlitz does not run our language server, so types errors don't show inside Astro files, hence why you cannot see the errors 😄

**Comment by space-otter** [comment]
Hm, odd. Created a new instance via `pnpm create astro@latest` and the error don't show up.

The screenshot below is from the old instance. Could be some wired behaviour of vscode. 

<img width="583" alt="Screenshot 2022-07-21 at 14 57 25" src="https://user-images.githubusercontent.com/27896533/180218985-bbb2df2a-20e1-4a10-977a-afb581c0380f.png">

**Comment by Princesseuh** [comment]
If you upgraded while running VS Code, it's possible that it still has the old types cached 😃

**Comment by space-otter** [comment]
Restart VS Code a few times, no changes. I deleted my `tsconfig.json` and reinstalled my `node_modules`. Guess what, the error disappeared! **Thank you for the hint :)** Sometimes a simple "Delete all!" is all you need :D
