### ISSUE TITLE
🐛 BUG: config.base prepends "/" to full URLs

### ISSUE THREAD

**Issue by bjrn** [withastro/astro#4007]
### What version of `astro` are you using?

1.0.0-beta.73

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Setting `config.base` to a full URL, e.g. `base: 'https://www.test.com/blog'`, prepends the URL with a `/` and turns the built paths to `/https://www.test.com/blog`. I've also tried setting `config.vite.base`, but that config setting is ignored.

Expected output of the stylesheet after `npm run build`:
```html
<link rel="stylesheet" href="https:/www.test.com/blog/assets/15cdaa0d.592172ca.css" />
```

Actual output:
```html
<link rel="stylesheet" href="/https:/www.test.com/blog/assets/15cdaa0d.592172ca.css" />
```

The [Astro docs](https://docs.astro.build/en/reference/configuration-reference/#base) do not say anything about full URLs being accepted, like the [Vite docs](https://vitejs.dev/config/shared-options.html#base) specify, but IMHO it would make sense if `base` worked the same way as in Vite, especially since `config.vite.base` is ignored.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hgfg1s?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is documented to be a pathname: https://docs.astro.build/en/reference/configuration-reference/#base. The intended use-case is to control your base for the dev server, so providing a URL doesn't make sense. It's just just a configuration for controlling how Link tags are built.

**Comment by bjrn** [comment]
Ok, but how do I specify that I would like my paths as absolute URLs for the built output? the Vite config property `base` is ignored, and the Astro config property `site` is not applied to the bundled css + js assets.

**Comment by wangxiao95** [comment]
I also encountered the same problem. How did you solve it?
