### ISSUE TITLE
🐛 BUG: Style is not included at all when running `yarn run build` 

### ISSUE THREAD

**Issue by luciodale** [withastro/astro#4025]
### What version of `astro` are you using?

1.0.0-beta.72

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I've got `Footer.astro` and `Navbar.astro` components.

- I am requiring both files in `layouts/Layout.astro`
- Both Navbar and Footer use `Astro.glob("../pages/**/*.astro")`
- The fact that they're both fetching files from the `pages` dir breaks the style.

If both files look into say `/layouts/*.astro` there's no bug. But if they both point to any path under `/pages` then the style is not included in the final build.

The issue happens only when BOTH files look into the `pages` dir.

### Link to Minimal Reproducible Example

https://github.com/luciodale/astro-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Have you confirmed that this bug only occurs when using Yarn?

**Comment by luciodale** [comment]
Nope I’m just developing with yarn and don’t know about the rest

**Comment by michaeltoohig** [comment]
I upgraded to the latest rc from an earlier beta version than the one reported above and this issue just happened to me. All fine in dev but build loses style on pages built from the new `.mdx` files that use a layout. Not sure if mdx is related but I had to upgrade to that with the upgrade to the latest Astro version so I thought I should include that info.

I would guess right now that the fact that these pages built with a `layout` wrap the markdown content in an element `<Layout>` must be the issue as that is a dramatically different change with the upgrade to .mdx files.

Also using Yarn but I don't believe that should be related.

**Comment by michaeltoohig** [comment]
Here's a bit of my project structure.

```MainHead.astro
---
import '@styles/global.scss';
const { title } = Astro.props;
---

<title>{title}</title>
```

```home.astro
---
import MainHead from '@components/MainHead.astro';
---

<html lang="en">
	<head>
		<MainHead title="Welcome to..." />
	</head>
</html>
```

The above file builds correctly with the css style from `MainHead.astro` included in the final html file.

Below does not work when built but does work during dev.

```post.mdx
---
title: Migrating to Astro
---
import Layout from '@layouts/Layout.astro';

<Layout content={frontmatter}>

# Markdown content

</Layout>
```

```Layout.astro
---
import MainHead from '@components/MainHead.astro';

const { content } = Astro.props;
---

<html>
	<head>
		<MainHead title={content.title} />
	</head>
	<body>
                 <slot />
        </body>
</html>
```


All I can tell is something happening in `MainHead.astro` with the `import '@styles/global.scss';`. Hope this helps narrow down the issue.

**Comment by michaeltoohig** [comment]
I just updated Astro to rc.3 from rc.2 but the issue persists.

In my home page `index.astro` the built `index.html` has the following lines just before the end head tag.

```
<link rel="stylesheet" href="/assets/afe0e435.aa923301.css" />
<link rel="stylesheet" href="/assets/7da8e18c.08e614dc.css" />
<link rel="stylesheet" href="/assets/6c7ec730.712d5b2e.css" />
```

But in the blog post that uses a layout there is no stylesheets added in the head.

**Comment by eliasbrange** [comment]
Also seeing the same issue. 

I have multiple pages that uses the same glob such as `/posts/*.mdx`. These `.mdx` files use a Layout that imports CSS, but that CSS is not properly inserted on said pages.

**Comment by michaeltoohig** [comment]
@eliasbrange that last sentence is an odd observation.

I upgraded to latest rc.4 and @astrojs/mdx@0.5.0 and the issue persists. So I put together a hack added it to my deploy script after building the project. It takes the lines at the end of the `</head>` where I know astro injects the stylesheets of my index page which I know has the stylesheets. Then for each html page in my post and project directories which are built with a layout I paste those same stylesheets from index.html. It seems to work for me as a stopgap and it may not work for others depending on other stylesheet issues I may not have experienced yet.

```python
from pathlib import Path

# known good file that contains stylesheets in head
indexFile = Path("./dist/index.html")
with indexFile.open("r") as f:
    html = f.read()

# copy style sheets from index page
scriptTagClosedIndex = html.index("</script>")
headTagClosedIndex = html.index("</head>")
cssLinks = html[scriptTagClosedIndex:headTagClosedIndex]

for file in Path("./dist/post/").glob("**/*.html"):
    with file.open("r") as f:
        html = f.read()
        scriptTagClosedIndex = html.index("</script>")
        head, body = html[:scriptTagClosedIndex], html[scriptTagClosedIndex+9:]
        html = head + cssLinks + body
    # overwrite html with injected style sheets
    with file.open("w") as f:
        f.write(html)
```

**Comment by djmtype** [comment]
Using Astro RC 4 and having the same if not similar issue. All is fine in development, but in production no links to css files in the `<head>` for just my single post pages. If I change my `.mdx` files back to `.md`, this will be reflected in the `Astro.glob`, and everything will build properly in production.

**Comment by matthewp** [comment]
Thanks, I'm looking into this issue now.

**Comment by matthewp** [comment]
I have a breaking test for this now.

**Comment by michaeltoohig** [comment]
Can confirm, upgraded to rc-7 and the stylesheets are now included in built files.

Thank you.
