### ISSUE TITLE
🐛 BUG: "Unterminated string literal" when breaking class to multiple lines

### ISSUE THREAD

**Issue by thetarnav** [withastro/astro#4029]
### What version of `astro` are you using?

1.0.0-beta.73

### Are you using an SSR adapter? If so, which one?

doesn't apply

### What package manager are you using?

pnpm

### What operating system are you using?

Windows 10

### Describe the Bug

I'm using tailwind, so I'll ofter break the value of `class` attribute into multiple lines for readability.
This works fine when the `class` is applied to an HTML Element. But the compiler breakes with components.

```tsx
// works:
<div class="some-tailwind-class another-tailwind-class more-tw-madness
   once-again-tailwind-class more-tailwind-class absolute inset-0
   etc-tailwind-class foo baz bar"
/>

// doesn't work:
<MyComponent class="some-tailwind-class another-tailwind-class more-tw-madness
   once-again-tailwind-class more-tailwind-class absolute inset-0
   etc-tailwind-class foo baz bar"
/>
```
Repro: https://stackblitz.com/edit/astro-multiline-class-bug?file=src%2Fpages%2Findex.astro

Error message:

![image](https://user-images.githubusercontent.com/24491503/180613900-68af8d30-7482-450a-97af-32286d1581a8.png)

----

It seems that `.tsx` files suffer from the same thing...
I guess this should work as a workaround:

```tsx
<MyComponent class={`some-tailwind-class another-tailwind-class more-tw-madness
   once-again-tailwind-class more-tailwind-class absolute inset-0
   etc-tailwind-class foo baz bar`}
/>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-multiline-class-bug?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by soongsta** [comment]
i had a similar issue. I just put everything on 1 line which seems to fix the issue for me

**Comment by daviddecorso** [comment]
Getting this issue with meta tags. Kinda insane tbh

**Comment by joeng03** [comment]
Still having this bug. Why is this issue closed"?

**Comment by thetarnav** [comment]
I don’t remember why I closed it tbh, I can reopen if that’s still an issue.
Maybe someone from the team can say if that is expected or not.

**Comment by bluwy** [comment]
I can still reproduce the issue, but I'd suggest opening a new one over at https://github.com/withastro/compiler instead of re-opening this old one. It can be reproed by pasting the multiline values at https://live-astro-compiler.vercel.app

**Comment by marijoo** [comment]
For anyone interested, you can simply use template literals, so this should work:

```astro
<MyComponent class={`some-tailwind-class another-tailwind-class more-tw-madness
   once-again-tailwind-class more-tailwind-class absolute inset-0
   etc-tailwind-class foo baz bar`}
/>
```

**Comment by akhoury** [comment]
@marijoo thanks but this won't work for non-strings, say, ... an array 

```
        b-form-select(
            v-model='form.relationship'
            :options='[
                { value: "SPOUSE", text: "Spouse" },
                { value: "PARENT", text: "Parent" },
                { value: "CHILD", text: "Child" },
                { value: "FRIEND", text: "Friend" },
                { value: "OTHER", text: "Other" }
            ]'
        )
```
