### ISSUE TITLE
🐛 BUG: Sending binary body is broken with node adapter SSR

### ISSUE THREAD

**Issue by tkamenoko** [withastro/astro#4053]
### What version of `astro` are you using?

0.0.0-rc-20220726043527

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Sending a binary content is broken on api route.

Example request:
```js
const requestBody = Uint8Array.from([0,1,33,233])

const response = await fetch("/api/echo", {
  method: "post",
  body: requestBody,
  headers: { "Content-Type": "application/octet-stream" }
});

const responseBody = new Uint8Array(await response.arrayBuffer())
console.log(requestBody)
console.log(responseBody)
```

Stdout:
```
Uint8Array(4) [ 0, 1, 33, 233 ]
Uint8Array(6) [ 0, 1, 33, 239, 191, 189 ]
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xdurhs-q4pmtc

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by tkamenoko** [comment]
I found PR #4023 that fixes empty body bug, but it seems to allow only UTF-8 contents.

https://github.com/withastro/astro/blob/adf8cde10fc86705935ba9ec4644fc9ecc1657b1/packages/astro/src/core/app/node.ts#L25-L57

It always decodes a request body as UTF-8 string.

**Comment by matthewp** [comment]
Ah yeah, it should be building up a Buffer I guess.
