### ISSUE TITLE
🐛 BUG: @fontsource breaks with new RC release

### ISSUE THREAD

**Issue by lostra01** [withastro/astro#4064]
### What version of `astro` are you using?

v1.0.0-rc.1

### Are you using an SSR adapter? If so, which one?

Vercel - Serverless (^0.3.0)

### What package manager are you using?

npm

### What operating system are you using?

MacOS Ventura

### Describe the Bug

Using the `@fontsource` package breaks with the new RC release when using SSR, with the following error:

```
[plugin:astro] Unknown file extension ".css" for /Volumes/Data/GIT/hackurity/frontend/node_modules/@fontsource/roboto/index.css

You likely need to add this package to `vite.ssr.noExternal` in your astro config file.

```

### Workaround:

Adding vite and the required parameters to the `astro.config.mjs` file removes the error, and the page loads as expected in a local dev environment. I have yet to push to Vercel to see what's happening there. I'll update this issue if there are problems on Vercel.

### Code for workaround:

```mjs
export default defineConfig(
/** @type {import('astro').AstroUserConfig} */
{
  adapter: vercel(),
  vite:{
    ssr:{
      noExternal: ['@fontsource/*']
    }
  }
});
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kb96u9?file=src/layouts/Layout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/4073
