### ISSUE TITLE
🐛 BUG: Build gets failed when we have space in between of the entire path

### ISSUE THREAD

**Issue by vidhyeshpatil** [withastro/astro#4065]
### What version of `astro` are you using?

1.0.0-beta.73

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When we try to generate the build, and the respective project is present at some desired path in the system. Build gets failed if there is space in between of any word into that path.

eg: Personal/Astro Project/my-astro-site (this might fail, during build process)

### Link to Minimal Reproducible Example

https

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please provide a sample. We have tests specifically for this. It's likely there are cases our tests aren't covering, so I do believe the bug, but I cannot fix it without knowing the condition that causes it. Happy to reopen when there is an example.
