### ISSUE TITLE
🐛 BUG: getStaticPath does not work with MDX glob (.url and .file)

### ISSUE THREAD

**Issue by dkotik** [withastro/astro#4074]
### What version of `astro` are you using?

v1.0.0-rc.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Astro.glob("content/*.mdx") returned ".url" page property is always undefined when path is above `./pages` folder. I had to work around this by passing a slug through the frontmatter.

`.file` is not set in any condition, even though it goes with regular Markdown files.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9dg5ka?file=src/pages/[slug].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dkotik** [comment]
If you are an Astro pro, can you please post your getStatisRoutes with MDX as an example? I am having a terrible with with it. Right now, my "npm dev" responds to globbed routes, but "npm build" outputs nothing. I did not have any issues with regular Markdown.

**Comment by matthewp** [comment]
Thanks for the repro, looking to get this fixed.

**Comment by matthewp** [comment]
One issue with the example is that your `content/` folder is outside of `src/`. It needs to be inside of src. But I think there's still a bug here.

**Comment by dkotik** [comment]
@matthewp Thank you so much for fast fix! Made my day. I am recommending Astro to my CEO tomorrow.
