### ISSUE TITLE
🐛 BUG: Inability to use MUI with a React app

### ISSUE THREAD

**Issue by andrewdavidcostello** [withastro/astro#4079]
### What version of `astro` are you using?

1.0.0-rc.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

This is a new fresh create astro with react and material-ui added to test library compatibility.

Running dev is fine but running build results in the below error before adding material ui to noExternal:

<img width="977" alt="Screenshot 2022-07-28 at 14 02 47" src="https://user-images.githubusercontent.com/443964/181512229-a3f2beba-7eff-4ceb-a5e8-f7f92bc2e823.png">

After adding mui to noExternal:

<img width="974" alt="Screenshot 2022-07-28 at 14 06 34" src="https://user-images.githubusercontent.com/443964/181512445-76bb1d28-daab-4ac8-96a1-83d662f00f43.png">

This may simply be an issue with material ui, apologies if so.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mggo3n?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You probably want to add `@mui/material` to `vite.ssr.noExternals`.

**Comment by andrewdavidcostello** [comment]
> You probably want to add `@mui/material` to `vite.ssr.noExternals`.

Thanks for the reply but as per above that is exactly what I tried, the before and after error. Final example on stackblitz shows it in noExtenal.

**Comment by codingfunwoody** [comment]
swithc to client-only for workaround
[https://github.com/withastro/astro/issues/4107#issuecomment-1215069951](url)

**Comment by matthewp** [comment]
Going to add a warning for this one.
