### ISSUE TITLE
🐛 BUG: browserslist is not respected on CSS build

### ISSUE THREAD

**Issue by kagankan** [withastro/astro#4092]
### What version of `astro` are you using?

1.0.0-rc.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Describe the Bug

# Problem

Astro transfroms css like this.

```css
.class {
  top: 0;
  right: 0;
  bottom: 0;
  right: 0;
}
```

↓ astro build

```css
.class{inset: 0;}
```

However, `inset` property is not supported in Safari 14.0 or before,
https://caniuse.com/?search=inset
so my styles are broken in Safari 14.0.
I added `safari 14.0` in .browserslistrc, but I got same result.

# Expected Behavior

in `vite-plugin-build-css`, css code is minified by esbuild.

https://github.com/withastro/astro/blob/c15cb36636320012c7d0c9d6ac8620029da70b0b/packages/astro/src/vite-plugin-build-css/index.ts#L121

I hope that `.browserslist` config is set to esbuild's`target` option.

# Possible Solution

Set  `.browserslist` config to esbuild on CSS build process.
I'll submit a PR.

# Other Solutions

- Add something astro option, enables to pass esbuild config on build  (like `build.css.esbuildConfig`) 
- Use Vite instead of esbuild (in order to pass `vite.build` config)

---

I love Astro project! Thanks to contributors and maintainers!

### Link to Minimal Reproducible Example

https://github.com/kagankan/astro-sample

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks for the PR!

**Comment by natemoo-re** [comment]
Appreciate the PR! We won't be able to add this feature until v1.1.0, but in the meantime the [`vite.build.cssTarget`](https://vitejs.dev/config/build-options.html#build-csstarget) might help?

**Comment by kagankan** [comment]
@natemoo-re 

Thank you for replying!
I understand that it won't be added soon.
(I'm looking forward to Astro 1.0.0 production release!)

> vite.build.cssTarget

It seems that `vite.build.cssTarget` is also ignored by Astro's CSS minification process.
If I send a PR that is to support cssTarget, that will be merged soon?
I'll send a PR just in case.
(but even if it is difficult to add this feature until 1.1.0 too, I don't mind!)
