### ISSUE TITLE
🐛 BUG: Using `preact/compat` with `solid-js` leads to "Cannot read properties of null (reading 'useRef')"

### ISSUE THREAD

**Issue by mayank99** [withastro/astro#4093]
### What version of `astro` are you using?

1.0.0-rc.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

See linked stackblitz. Using `client:load` causes the solid-js adapter to mess with preact components. Using `client:only` makes the error go away.

I've also seen other variations of this issue, e.g. the react adapter sometimes messes with solid-js components. Will update this issue with more links (or create a new one) if I bump into that again.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bltmyz?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I think this isn't directly related to Solid and is an issue with preact/compat and the `downshift`. Will report back after I investigate more.

**Comment by matthewp** [comment]
Made a little bit of progress here: https://github.com/withastro/astro/tree/preact-compat-issue

Going to chat with @bluwy about this. The issues I'm running into are:

- SSR seems to transform `node_modules/preact/compat/dist/compat.module.js` incorrectly, I think because it contains an import statement and an `export from` statement about the same module.
- This module exports a bunch of things off of the `default` that `downshift` expects to be named exports. I'm not sure if this is the fault of Vite or preact (probably preact).

It might be that `downshift` isn't compatible with preact/compat.

**Comment by mayank99** [comment]
Oh that's super interesting. I think I got confused by the original error message because it says `@astrojs/solid-js`.

Does `preact/compat` not have full compatibility with all `react` (<18) packages?

Also, if `solid-js` is eliminated, does that make this issue a duplicate of https://github.com/withastro/astro/issues/4107? Different package there, similar problem.

**Comment by matthewp** [comment]
I'm sure that preact/compat is not compatible with all React packages, that's an impossible ask. But I don't yet know if its compatible with this one or not, there's an underlying bug we have to fix first.

#4107 could be the same issue, assigning it to myself until we figure this one out.

**Comment by bluwy** [comment]
I managed to trim down the issue to Vite's SSR transform, which incorrectly transforms:
```js
export * from 'vue'
import {createApp} from 'vue'
export {createApp as bar}
```
to
```js
const __vite_ssr_import_1__ = await __vite_ssr_import__("vue");
__vite_ssr_exportAll__(__vite_ssr_import_1__);
Object.defineProperty(__vite_ssr_exports__, "bar", { enumerable: true, configurable: true, get(){ return __vite_ssr_import_0__.createApp }});
```

Note the `__vite_ssr_import_0__` does not exists. I'll try to send a fix in Vite.
