### ISSUE TITLE
🐛 BUG: CSS is duplicated in dev server.

### ISSUE THREAD

**Issue by RobertAKARobin** [withastro/astro#4102]
### What version of `astro` are you using?

1.0.0-rc.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac OS X 12.5

#### Expected result:

When I access my website via the dev server, each stylesheet will be applied once.

#### Actual result:

Each stylesheet is applied twice — both component stylesheets, and global stylesheets imported via ESM — via duplicate `<style>` tags in the `<head>`:

![Screen Shot 2022-07-30 at 12 13 29 PM](https://user-images.githubusercontent.com/6268177/181945480-6a076c69-4e20-4822-ab2a-5c7ef75d2014.jpg)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-dupe-css?file=src%2Flayouts%2Fhome.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by RobertAKARobin** [comment]
Note that this started occurring within the maybe last 1 - 3 weeks, during which time I've been frequently updating to Astro's latest beta release. So it must have been introduced by a version released within the last couple of weeks.

**Comment by Fahari** [comment]
The bug is quite annoying so to say.

**Comment by natemoo-re** [comment]
I just opened #4157 and this should be fixed in the next `rc` release!
