### ISSUE TITLE
@astrojs/image SSR support for non-Node runtimes

### ISSUE THREAD

**Issue by sandervspl** [withastro/astro#4109]
### What version of `astro` are you using?

1.0.0-rc.3

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

pnpm (same happens on yarn and npm)

### What operating system are you using?

Mac

### Describe the Bug

When you combine the `@astrojs/image` integration with `output: 'server'` the build fails. It's failing to build the project because the image component is using multiple Node.js modules (fs, crypto, path, URL)

The error:
```
[commonjs--resolver] Cannot bundle Node.js built-in "node:fs/promises" imported from "node_modules/@astrojs/image/dist/utils/images.js". Consider disabling ssr.noExternal or remove the built-in dependency.
 error   Cannot bundle Node.js built-in "node:fs/promises" imported from "node_modules/@astrojs/image/dist/utils/images.js". Consider disabling ssr.noExternal or remove the built-in dependency.
```

### Link to Minimal Reproducible Example

This example below does not run on Stackblitz. You will need to download the project, install it and then run `npm run build`. You will get the error above.

https://stackblitz.com/edit/github-i5zqrv?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This only happens for the Cloudflare integration as we set `vite.ssr.target: 'webworker'` for it. Checking `@astro/images` which injects route endpoints for serving images, I'm not sure if this can work without a significant refactor. Perhaps this is out of scope for the Cloudflare integration?

**Comment by tony-sull** [comment]
We'll need to investigate this a bit more.  The `@astrojs/image` integration only supports Node environments right now, but we do want to add support for deno soon.  I'm not sure exactly what the differences are in Cloudflare's `webworker` support, hopefully we can add support there as well

**Comment by bluwy** [comment]
Thanks for the update @tony-sull. With `webworker`, you can imagine an SSR build but without all the nodejs modules available. Cloudflare uses V8 instead of node but implements a browser web worker-like API instead. I'll unassign myself as I don't have a good overview of how this would work for the image integration.

**Comment by jcayzac** [comment]
Seeing this too. Default project + `cloudflare` & `image`.

```
> astro build

01:34:00 PM [build] output target: server
01:34:00 PM [build] deploy adapter: @astrojs/cloudflare
01:34:00 PM [build] Collecting build info...
01:34:00 PM [build] Completed in 437ms.
01:34:00 PM [build] Building server entrypoints...
[commonjs--resolver] Cannot bundle Node.js built-in "util" imported from "node_modules/.pnpm/sharp@0.30.7/node_modules/sharp/lib/constructor.js". Consider disabling ssr.noExternal or remove the built-in dependency.
```

https://discord.com/channels/830184174198718474/830184175176122389/1020553683072729148

**Comment by matthewp** [comment]
@tony-sull is this fixed by https://github.com/withastro/astro/pull/4738 ?

**Comment by matthewp** [comment]
Started implementing in this branch: https://github.com/withastro/astro/compare/image-non-node?expand=1 Current blocker is whether the vendored squoosh code can be edited or not, as it heavily relies on Node at the moment.

**Comment by matthewp** [comment]
@Princesseuh This is something you could possibly work on in the future. For now I think it's blocked because the Squoosh library, the only one that uses wasm, has been deprecated. So I'm not sure we can take on this issue yet.

There probably needs to be some research as to what our options are. Do other similar projects like next/image work outside of Node.js? If so what are they using for image optimizations?

**Comment by elevatebart** [comment]
Hello Y'all

Cool stuff toward a wasm sharp is being done [here](https://github.com/lovell/sharp/pull/3522) hopefully this will solve a thing or two.

Hehe

**Comment by Princesseuh** [comment]
Hello, just a status update about this: We're currently waiting for Sharp to add WASM support, since `libsquoosh` is deprecated.

We won't fix this in `@astrojs/image`, as it is heading towards maintenance mode in favour of the new `astro:assets` feature, but we are looking into fixing this for `astro:assets`. The later has a much better warning for this being unsupported, which should at least clear confusion for users.

**Comment by schummar** [comment]
I use hybrid mode and need `astro:assets` only at build time. I have a few SSR components and endpoints but they do not use it, but with the Cloudflare adapter the build still fails as soon as `experimental: { assets: true }` is enabled.

Until proper non-Node support is ready, here is my little hack to allow this.

Create a custom image service at "src/image-service.ts":
```ts
import type { LocalImageService } from 'astro';
import { baseService } from 'astro/assets';

const service: LocalImageService = {
    ...baseService,

    async transform(inputBuffer, transform, serviceConfig) {
        // Purposefully obfuscate the import to prevent bundling => will only work at build time!
        const imageService = (
            await new Function(
                `return import('astro/assets/services/squoosh')`
            )()
        ).default;

        return await imageService.transform(
            inputBuffer,
            transform,
            serviceConfig
        );
    },
};

export default service;
```

and add it to the config. E.g.:
```ts
import cloudflare from '@astrojs/cloudflare';
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
    output: 'hybrid',
    adapter: cloudflare({
        mode: 'directory',
    }),
    experimental: {
        assets: true,
    },
    image: {
        service: {
            entrypoint: './src/image-service.ts',
        },
    },
});
```

**Just keep in mind that this will throw runtime errors, if you try to use `astro:assets` in any server rendered component!**

**Comment by matthewp** [comment]
Closing as we have removed `@astrojs/image` from the repo an won't be fixing bugs for it going forward. In the future the solution for non-Node runtimes with `astro:assets` will be to use a wasm version of Sharp (when that is released).

**Comment by Princesseuh** [comment]
Just for info, we're aware this also affects astro:assets, however we consider this to be closer to a feature request than an issue. So we'd like for discussion to continue on our roadmap repo instead.

As Matthew said, the ultimate solution for this is for Sharp, the upstream dependency, to support both WASM and non-Node environments.

**Comment by dfbaskin** [comment]
While we wait for a non-Node (Cloudflare) option, temporarily maybe we can just do a pass-through image (`passThroughImageService.ts`):

```ts
import type { LocalImageService } from "astro";
import { baseService } from "astro/assets";

// Image service ("sharp") not supported by Cloudflare pages
// https://github.com/withastro/astro/issues/4109
const service: LocalImageService = {
  ...baseService,
  getURL({ src }) {
    const path = typeof src === "string" ? src : src.src;
    return path;
  },
  async transform(buffer, transform) {
    return {
      data: buffer,
      format: transform.format,
    };
  },
};

export default service;
```

and registration (`astro.config.mjs`):

```ts
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import cloudflare from "@astrojs/cloudflare";

// https://astro.build/config
export default defineConfig({
  site: "https://...",
  integrations: [mdx(), sitemap()],
  output: "server",
  adapter: cloudflare(),
  image: {
    service: {
      entrypoint: "./src/services/passThroughImageService",
    },
  },
});
```

**Comment by Princesseuh** [comment]
That already exists:

```ts
import { defineConfig, passthroughImageService } from "astro/config";

export default defineConfig({
 image: {
   service: passthroughImageService(),
 },
});
```

It's also automatically configured for you when using an adapter that doesn't support Sharp and Squoosh.

**Comment by dfbaskin** [comment]
Missed that, Thanks!

**Comment by cptchloroplast** [comment]
> That already exists:
> 
> ```ts
> import { defineConfig, passthroughImageService } from "astro/config";
> 
> export default defineConfig({
>  image: {
>    service: passthroughImageService(),
>  },
> });
> ```
> 
> It's also automatically configured for you when using an adapter that doesn't support Sharp and Squoosh.

FYI - This does not automatically configure when using the Cloudflare adapter. You have to explicitly tell it to use the pass through service. The docs are not very helpful in this regard either

**Comment by Princesseuh** [comment]
> > That already exists:
> > 
> > ```ts
> > import { defineConfig, passthroughImageService } from "astro/config";
> > 
> > export default defineConfig({
> >  image: {
> >    service: passthroughImageService(),
> >  },
> > });
> > ```
> > 
> > It's also automatically configured for you when using an adapter that doesn't support Sharp and Squoosh.
> 
> FYI - This does not automatically configure when using the Cloudflare adapter. You have to explicitly tell it to use the pass through service. The docs are not very helpful in this regard either

Your CloudFlare integration might be outdated, the latest version should do it for you
