### ISSUE TITLE
🐛 BUG: Ordering of CSS outputs differ between `dev` & `build`

### ISSUE THREAD

**Issue by aFuzzyBear** [withastro/astro#4110]
### What version of `astro` are you using?

rc-0

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

pnpm 

### What operating system are you using?

linux production environments like Container images, Netlify Deployment, 

### Describe the Bug

This bug was reported by another user.

The ordering pattern of the css outputs appear to change during `build` to be different to what was provided in `development`
```js
[
  'entry.mjs',
  'assets/0afaed2b.378d12e2.css',
  'assets/3699556f.dd6093dd.css',
  'assets/5728253d.48cd12e9.css',
  'assets/7da89e5b.378d12e2.css',
  'assets/c0cfc463.a0a88ab6.css',
  'assets/d23a3325.93c09b2b.css',
  'assets/e7323b69.a6d911fd.css'
]
```
Server order:
```js
[
  'entry.mjs',
  'assets/0a79d35e.93c09b2b.css',
  'assets/121c21c7.378d12e2.css',
  'assets/1a4fd730.a0a88ab6.css',
  'assets/4f496975.378d12e2.css',
  'assets/cdc44a93.48cd12e9.css',
  'assets/e0547ee7.dd6093dd.css',
  'assets/e1a82085.a6d911fd.css'
]
```

If you notice, the secondary hashes do not match up in the same order, this then effects the cascade ordering of the stylesheets

The user has provided a further update to suggest that the deviation maybe occurring somewhere within the `vite-plugin-internals`

I do believe this is breaking expected behavior and have seen this occur when trying to debug alongside the user.

Unfortunately this is a commercial project and the user couldnt share their project as a reproduction.

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@aFuzzyBear these two code snippets appear to both be for the build, not for development. Where are you getting these snippets from?

Is it possible that you mean that one of them is what is output in static mode and the other is what is output for an SSR build?

**Comment by aFuzzyBear** [comment]
Sorry, Matt my apologies wasn't clear in the issue, the first snippet is the localhost provided by dev and the second is the build output, it was an SSG project,

**Comment by matthewp** [comment]
Thanks, but I still don't follow. Where do you get those snippets? Did you find those in the code and do a console.log? Is there maybe a discord thread that can help me understand better?

The reason I add is because the first snippet looks like files that are created during the build. They aren't created during dev at all.

**Comment by matthewp** [comment]
Talked to @aFuzzyBear on discord and this bug report came from a private DM so we can't get more details.

My suspicion is that they may be reporting a static build / ssr build difference. So I'm going to create a test for this and fix it, if that indeed is a problem.
