### ISSUE TITLE
🐛 BUG: Astro doesn't work too well with react-simple-typewriter

### ISSUE THREAD

**Issue by reqyo** [withastro/astro#4121]
### What version of `astro` are you using?

1.0.0-rc.3

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Using a react package (react-simple-typewriter) in a react component and importing that component into a .astro file, and using any of the client settings, (client:load, client:idle, client:visible etc) the expected outcome does not work.

Instead of looping through the array of strings that are passed into a prop with react-simple-typewriter and displaying them on the screen, it only loops through one, and then just continues to blink, when trying this exact same component in normal react, or Gatsby, I don't have any issues. I understand how astro ships with as little js as possible but this seems like an issue if you are trying to explicitly state you want it on the client.

react-simple-typewriter@3.0.1

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-l82kez?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
This appears to be a Vite bug, unrelated to Astro. I can reproduce it in Vite without Astro being involved: https://stackblitz.com/edit/vitejs-vite-ygfgpn?file=package.json&terminal=dev

Most likely, this package is incompatible with esbuild and Vite's internal esbuild bundler. You can file this issue with Vite, but your best bet would be to get `react-simple-typewriter` to publish their package as ESM which is a JS format that often does much better in esbuild and modern dev tools.

Sorry that we can't do anything here to help!

**Comment by reqyo** [comment]
Just want to say @FredKSchott thank you so much this drove me up the wall, first time with Astro and I was thinking non of the npm packages worked, no worries, will move on to doing that typewriter thing myself! Legend
