### ISSUE TITLE
🐛 BUG: set:text misinterpretation using quotation marks (' and ") in template literals 

### ISSUE THREAD

**Issue by space-otter** [withastro/astro#4122]
### What version of `astro` are you using?

v1.0.0-rc.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Quotation marks in template literals that are passed into `set:text={}` aren't escaped. 

```astro
<h1 set:text={`Husten we have a problem' `} />
```

renders to:
```
Husten we have a problem' /> }
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6kdkmr?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by space-otter** [comment]
Same behaviour occurs also in `set:html`.

**Comment by natemoo-re** [comment]
Thanks for opening an issue @space-otter! I'm taking a look right now.
