### ISSUE TITLE
🐛 BUG: Params not passed in api routes SSR

### ISSUE THREAD

**Issue by isakkeyten** [withastro/astro#4132]
### What version of `astro` are you using?

1.0.0-rc.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Params is always an empty object even when query params are added to the api url.

To reproduce:

Open this repro on stackblitz
https://stackblitz.com/edit/github-gshanh?file=src/pages/api/products.ts
Let it run
go to url/api/products?test=value
console.log from the api/products.ts file always shows an empty object.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gshanh?file=src/pages/api/products.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I think you are confusing route params and query/search params. The `params` object passed into an API route is for when you are using dynamic routes.

Search params are the part after `?` in the URL. You can get those from the request object. Here's an example that does what I think you want: https://stackblitz.com/edit/github-gshanh-zqkcph?file=src%2Fpages%2Fapi%2Fproducts.ts

**Comment by nestorbfgo** [comment]
thanks but if you watch documentation this part same to be unclear!
