### ISSUE TITLE
🐛 BUG: New MDX release breaks if you disable the collect-headings plugin.

### ISSUE THREAD

**Issue by eliasbrange** [withastro/astro#4150]
### What version of `astro` are you using?

v1.0.0-rc.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows (WSL 2)

### Describe the Bug

The added functionality in MDX that adds headings and frontmatter to layout props (https://github.com/withastro/astro/pull/4134) does not work if you disable the custom plugin `collect-headings` as specified here: https://docs.astro.build/ar/guides/integrations-guide/mdx/#configuration

If that plugin is disabled, the function `getHeadings()` does not exist.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6nege1?file=astro.config.mjs,src%2Fpages%2Findex.mdx,package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for reporting! Agreed that `getHeadings` should always be applied. We decided to make our `collect-headings` plugin non-overridable for now. If you have a reason we should _allow_ users to remove this plugin, we can re-open!
