### ISSUE TITLE
🐛 BUG: UpperCase Folder name issue

### ISSUE THREAD

**Issue by Hopelezz** [withastro/astro#4163]
### What version of `astro` are you using?

1.0.0-rc.6

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Windows

## 🐛Bug:
I was uploading my modified Blog Template to Vercel
an error :
![img](https://media.discordapp.net/attachments/1004448301044740126/1004924015778996316/unknown.png?width=1470&height=897)

After migrating my site codebase to 1.0.0-rc.6 the issue still persisted...
It was suggested by @mayank99 to change letter case of the folders as this has caused him issues.

I had previously decided to Uppercase all component folders to match their contents since components are Uppercase since creating the original blog.

## 🧾The Issue:
Everything matched on my local machine, but didn't match on Github.
When `git push`ing to a repo the folder casing wasn't being updated. Because the files were  referencing Uppercase folders and the repo had lowercase and the files referencing had Uppercase. This was causing the deploy to vercel to break.

Local Repo:
```
src/components/Blog/post.astro
import BlogPost from ../components/Blog/post.astro
```

Remote Repo:
```
src/components/blog/post.astro
import BlogPost from '../components/Blog/post.astro
```

## 🛠️The Fix:

- remove the components folder out of the project file. 
- `git push` to change the Github repo.
- add files back to project
- `git push`

Confirmed the folder casing has been fixed and Vercel deployed.

People Helping on my issue in Discord:
https://discord.com/channels/830184174198718474/1004448301044740126
@FredKSchott , @aFuzzyBear, @bholmesdev, @mayank99 ~Thank you all for your time!

Note:
- _(Stackblitz just shows a generic `failed to load ssr` as I was getting and not the GitHub problem. Not sure how to replicate)_
![image](https://user-images.githubusercontent.com/72772558/183004657-33726013-cfc6-44c4-a94f-38cf57c17f13.png)

- Not sure what all is involved with submitting a PR for this, but I'd like to be involved if I can be!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2kknbu?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hey @Hopelezz! I have a very strong suspicion that this is a common gotcha with `git` and not an Astro-specific problem. Have you investigated if changing the [`core.ignorecase`](https://git-scm.com/docs/git-config/2.14.6#Documentation/git-config.txt-coreignoreCase) setting fixes the problem?

```
git config core.ignorecase false
```

Here's some more info about this setting. https://www.hanselman.com/blog/git-is-casesensitive-and-your-filesystem-may-not-be-weird-folder-merging-on-windows

**Comment by Hopelezz** [comment]
@natemoo-re I think this might be a gotcha, I ran the git command. Hopefully I wont run into this again, but I'll def be aware of this issue for future cases. Thanks!
