### ISSUE TITLE
🐛 BUG: 404 does not work with Vercel

### ISSUE THREAD

**Issue by jablonski** [withastro/astro#4164]
### What version of `astro` are you using?

1.0.0-rc.6

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Adding a 404.astro to src/pages works fine in Netlify, but in Vercel the 404 is not displayad. It displays the start page with a 200 status code.

### Link to Minimal Reproducible Example

Problem is only visible in Vercel

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by intagaming** [comment]
Actually deeply willing to watch this being resolved, because since I switch from Next.js to Astro, by old blog links is not being shown the 404 page, resulting in Google believing that the URL is still up and not removing them from search results (or at least in the Google Search Console thingy).

**Comment by matthewp** [comment]
Are you using Vercel Serverless, Edge, or Static? For serverless it should be getting the 404.astro page already: `https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/serverless/entrypoint.ts#L25`

**Comment by intagaming** [comment]
> Are you using Vercel Serverless, Edge, or Static? For serverless it should be getting the 404.astro page already: `https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/serverless/entrypoint.ts#L25`

I know the OP might just have different setup than me, but I'm also having the same issue and had sent support ticket to Vercel, to which they're "elevating to the team", so here you go.

My Astro website's source code is publicly available at [https://github.com/intagaming/hxann.com](https://github.com/intagaming/hxann.com). Here's a random url which don't exist, you might try anything after the slash: [https://hxann.com/asdCompletelyRandom123aazz](https://hxann.com/asdCompletelyRandom123aazz). It's completely static, or shall you say Vercel Static.

**Comment by matthewp** [comment]
@intagaming i cloned your repo and it is producing a 404.html which according to here: https://vercel.com/guides/custom-404-page#static-site-generator-(ssg) that should work.

**Comment by intagaming** [comment]
> @intagaming i cloned your repo and it is producing a 404.html which according to here: https://vercel.com/guides/custom-404-page#static-site-generator-(ssg) that should work.

Yes, it is, but only locally for me. Have you tried deploying to Vercel?

**Comment by matthewp** [comment]
If you have a link you can send me I can take a quick look.

**Comment by intagaming** [comment]
I included the Build log and the Output thing to the comments of this commit, don't know if it helps or not: [https://github.com/intagaming/hxann.com/commit/c77886ec239c437aab452709cf4932ea6450be9e](https://github.com/intagaming/hxann.com/commit/c77886ec239c437aab452709cf4932ea6450be9e)

**Comment by intagaming** [comment]
I'm gonna make a wild guess that it *might* have something to do with the Vercel router. But again, it should not act like this at all for a Next.js static site, based on my experience with it.

**Comment by matthewp** [comment]
@intagaming from your screenshot I see a few files named `blog`, `contact`, and `about`. I'm talking about the files, not the folders. What are those files?

**Comment by intagaming** [comment]
> @intagaming from your screenshot I see a few files named `blog`, `contact`, and `about`. I'm talking about the files, not the folders. What are those files?

That's just an HTML page disguised as a Vercel "file". They're generated with Astro's `[...slug]` thing, which I don't know the exact term but it's like a dynamic route. Here's the content of one: 
![image](https://user-images.githubusercontent.com/16471365/183141955-c559736c-eb78-4ca6-a61e-f0471f2a3469.png)

**Comment by matthewp** [comment]
Ok, that's a bit unusual. I would expect the folders with index.html in them but not those files (with no file extension). I don't think Astro is producing those files. It's probably unrelated to your 404 problem though.

The 404.html file exists which according to their docs is all that's needed, so I'm not sure how to further help here.

**Comment by intagaming** [comment]
I just tried to `npm create astro@latest` and use the "Just the basic" template to spin up a fresh Astro site, and it's the same problem. Info dump: [GitHub Repo](https://github.com/intagaming/test-astro-404) [https://test-astro-404.vercel.app/asd](https://test-astro-404.vercel.app/asd)

So... That should make it a bit more interesting to work with.

**Comment by jablonski** [comment]
Very strange... even if I set the Framework to "other" and provide "dist" as output (where a 404.html sits at root), it doesn't work. Seems to be a problem with Vercel...

**Comment by jablonski** [comment]
I've created a support ticket at Vercel. Let's see what they will say.

**Comment by intagaming** [comment]
> I've created a support ticket at Vercel. Let's see what they will say.

Just so you know, it's been awhile for my ticket to sit without much update. Maybe you'd get better luck with the Vercel Pro. Worth another stab though.

![Screenshot_2022-08-06-08-11-28-38_e307a3f9df9f380ebaf106e1dc980bb6.jpg](https://user-images.githubusercontent.com/16471365/183227822-aeb7aabf-deb6-4af3-9226-8b5ea12ac6ac.jpg)

**Comment by matthewp** [comment]
Thanks @jablonski, please let us know what you find. Will keep the issue open for a little bit in case its a bug on our end.

**Comment by jablonski** [comment]
Maybe relevant: I'm using Astro with an /api-folder for Vercel functions.

**Comment by matthewp** [comment]
Thanks @jablonski, so it sounds like maybe there is something wrong with our SSR output, I'll play around with it.

**Comment by matthewp** [comment]
I can confirm that `404.html` is not working in my own basic static project. cc @okikio.

Going to dig into the SSR issue as that is likely Astro's bug.

**Comment by okikio** [comment]
Awesome

**Comment by matthewp** [comment]
I'm getting the 404.astro page: https://vercel-404-matthew6.vercel.app/testing

However we are getting the wrong status code, so let me try and fix that.

**Comment by intagaming** [comment]
@matthewp Hi. I don't think the problem is resolved yet. So the Astro Docs' guide to deploy to Vercel literally says that you can skip the Vercel configuration in Astro completely if you don't use SSR. The "Just the basics" template of Astro doesn't use SSR. Indeed it is not fixed as of `astro@1.0.2`, which has the fix included. Here's the deployment of "Just the basics", upgraded to `astro@1.0.2`: [GitHub commit](https://github.com/intagaming/test-astro-404/commit/f8f16406fea712f2bbe43614b9e0632ba3457ce4). Here a link for convenience: [https://test-astro-404.vercel.app/zxc111](https://test-astro-404.vercel.app/zxc111)

**Comment by matthewp** [comment]
Yep, @intagaming, I'm aware that the 404.html is not working on Vercel. This issue is about the SSR adapter case, and that has been fixed by the linked PR.

As you noted you have a support ticket in with Vercel on their 404.html support, there's nothing we can do on our end to fix that problem.

**Comment by jablonski** [comment]
My interpretation of the problem: when Vercel detects an Astro project (regardless if there's a Vercel adapter installed or not), it runs it in some kind of SSR mode. This works fine with the Vercel adapter, but leads to the 404 problem without the adapter. This problem occurs even if one selects "Other" as framework. So the bug is on the Vercel side (at least for framework = "other" Vercel should just deliver the dist folder).

Contacting the Vercel support didn't help.

**Comment by prototypa** [comment]
Reviewing some [Vercel 404 documentation](https://vercel.com/guides/custom-404-page#what-if-i-need-to-name-my-404-file-something-different) and applying a little logic I was able to temporarily fix the Vercel problem with the 404 in Astro in SSG (Static Side Generator) by uploading a *vercel.json* file with these settings::

```json
{
    "routes": [
      { "handle": "filesystem" },
      { "src": "/(.*)", "status": 404, "dest": "/404.html" }
    ]
}
```

<br />

Demo:
- Good url: https://astrowind.vercel.app/
- Some random url: https://astrowind.vercel.app/somebadurl

**Comment by jablonski** [comment]
routes didn't work for me because I need rewrite rules and routes and rewrites are not allowed to mix. So I've tested and found this combination (with an example rewrite). And it works!!!!

```
{
  "cleanUrls": true,
  "trailingSlash": false,
  "rewrites": [
    {
      "source": "/api/(.*)",
      "destination": "/api/fastify"
    }
  ]
}

```

**Comment by jablonski** [comment]
I've added a PR for the docs, so others won't run into this issue:

https://github.com/withastro/astro/pull/4299

**Comment by shishkin** [comment]
There is still an issue with custom 404 pages on Vercel with dynamic routes: https://github.com/withastro/astro/issues/4635

**Comment by jtomek** [comment]
Hello, how to get a 404 on Vercel?

This issue is reproducible in the official demo: https://vercel.com/templates/astro/astro-edge-functions
Example: https://astro-template.vercel.app/djaklfjaklsjdlfasdfjaklsdf

**Comment by cerpow** [comment]
Hey guys, this worked for me using Astro and Vercel edge adapter in vercel.json at root:

```json
{
  "cleanUrls": false,
    "rewrites": [
      {
        "source": "(.*)",
        "destination": "404.html"
      }
  ]
}
```

**Comment by colinmcdermott** [comment]
So is this still an issue? I have been trying to get a working 404 page in Astro with no joy so far...

**Comment by cerpow** [comment]
Yes @colinmcdermott , I get blank page in Safari and 404 message in Chrome, but no html page.
Happens using @vercel edge adapter.

I manage to fix it by creating "[...any].astro" in Pages folder replacing 404.astro.

// [...any].astro 
```
---
import Layout from '../layouts/layout.astro';
const { any } = Astro.params;
---

<Layout center>
	<h1>Not found</h1>
	<p class="medium">The page you wanted isn't here. Browse our site for something else that might catch your interest.</p>
	<p><a href="/">Back to Homepage</a></p>
</Layout>

```

**Comment by benadam11** [comment]
@cerpow that seems like a better workaround than the routes config ...

**Comment by jtomek** [comment]
Does it return 404? Without a valid 404 status, it could have consequences on SEO.

**Comment by colinmcdermott** [comment]
Thank you kindly for the response @cerpow and all. Would also be very interested to know if your work around responds with a 404 status, as it looks great otherwise. A catch 22... ugly 404, or pretty 200... would have to go with the ugly 404 I guess.

**Comment by ElyseGiroux** [comment]
If like me you are using hybrid rendering and have your configs like this:  output: "server", adapter: vercel()
and building pages with: export const prerender = true;

You need to remove the export const prerender = true; from your 404 page.

I render all my pages statically but still use an API and the 404 page need to be server rendered too.

**Comment by benjamin-guibert** [comment]
I just ran into the same issue using hybrid mode in Astro 3 using Vercel Adapter: the custom 404 page was not being generated.

I got it fixed by rendering the 404 page, thanks for the tip!

```typescript
export const prerender = false;
```
