### ISSUE TITLE
🐛 BUG: Language from code chunks showing up with `mdx`

### ISSUE THREAD

**Issue by kylebutts** [withastro/astro#4170]
### What version of `astro` are you using?

1.0.0-rc.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The language from the code block is being treated as code and is displayed in the resulting html. Here's an example from astro.new:

![CleanShot 2022-08-05 at 12 02 38@2x](https://user-images.githubusercontent.com/19961439/183134713-f747cf5b-c567-4e88-9997-59a3dbc57805.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/with-mdx?file=README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'll let @bholmesdev weigh in on this, but I believe this is because we switched from a custom Shiki implementation to using [`shiki-twoslash`](https://github.com/shikijs/twoslash) and this is their default behavior.

**Comment by bholmesdev** [comment]
That's correct! This is inserted by [`shiki-twoslash`](https://github.com/shikijs/twoslash) by default so you can either style or hide that element yourself. Closing since this is intentional, but let us know if you'd prefer a different behavior! Feedback welcome

**Comment by kylebutts** [comment]
Yeah, I can see why it's helpful (e.g. absolute positioning the language to the top right corner or something). Thanks for the quick response!
