### ISSUE TITLE
🐛 BUG: `astro dev` Components used in MDX-Layout do not update on save

### ISSUE THREAD

**Issue by ChristianK43** [withastro/astro#4178]
### What version of `astro` are you using?

1.0.0-rc.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When using the MDX-Integration and import an Astro-Component in the MDX-Layout file, the values in the Component-Script of that Component do not get updated on save while running `astro dev`

Example: `const test` was changed from `"a"` to `"b"`, but it's still outputting `"a"`
 ![example screenshot](https://media.cleanshot.cloud/media/18919/xsd1zuWysFj1tKyNXgjClTREnJOGFXzzZxDtVkoB.jpeg?Expires=1659734912&Signature=OqysQZsUFcX7co90tuBgt7s6QkpXIS3zMIVvSGkwAiKTEuR3bj3nf57DhtIs9QNPe-jOthkrh0t5xpEjGOFzZZrOM2dfr5e4oEMZwfzfZVc4IN1ZFv1QzPnPfQKUMPBPukJ8ZjgL-MynltPXPGJcLy0F0rht~~FQyCWGdq2VJ7yMrT~LLZYz-dIba0vjeK1We1hmWWIWbiKn4ebG9238Ln5wtmPv4qERdEqjDf4wLGkcDFlwtRavht96-LkdNHe2L38xg11FKjvCe9482ebJlQxQSvAfkAPe9wqslPIyNo2CwSrNQedLqs0KwHMgZv3IJcujQsw3OceLHRUWjBXcnw__&Key-Pair-Id=K269JMAT9ZF4GZ)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1trqzs?file=README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I investigated this a little bit and am totally stumped. There might be a race condition in the module graph not populating `importers` properly **or** we might not be crawling all the way up the importer graph to invalidate the correct modules.

**Comment by ChristianK43** [comment]
@natemoo-re you've probably already found out yourself, but this is not limited to the component-script, but affects the whole component.

**Comment by djmtype** [comment]
I'm probably not being helpful by saying this, but I'm experiencing this too, using Astro 1.0.0. If I change my .mdx files back to .md everything works. Meaning, my changes are reflected in the browser upon save.

**Comment by bholmesdev** [comment]
@ChristianK43  @djmtype Looks like this _may_ be resolved in the latest version of Astro (`1.0.9`) and MDX (`0.10.1`)! I have a working demo over here with that `Dummy` component you provided. Let me know if this works as expected for you when editing on the dev server.

https://stackblitz.com/edit/github-u9y6mb?file=src/components/Title.astro

**Comment by Bobakanoosh** [comment]
> @ChristianK43 @djmtype Looks like this _may_ be resolved in the latest version of Astro (`1.0.9`) and MDX (`0.10.1`)! I have a working demo over here with that `Dummy` component you provided. Let me know if this works as expected for you when editing on the dev server.
> 
> https://stackblitz.com/edit/github-u9y6mb?file=src/components/Title.astro

Just spent a frustrating hour trying to figure out why my pages weren't hotreloading, finally find this.

Works fine on the following version:
```
		"@astrojs/mdx": "^0.10.2",
		"astro": "^1.1.1",
```

**Comment by bholmesdev** [comment]
@Bobakanoosh glad to hear it! I'll close this thread first thing tomorrow if I don't see any follow-ups.

**Comment by bholmesdev** [comment]
Closing! I'll reopen if anything is discovered. Thanks y'all 🙏
