### ISSUE TITLE
Client directive not working on namespaced JSX inside MDX

### ISSUE THREAD

**Issue by pomber** [withastro/astro#4209]
### What version of `astro` are you using?

1.0.0-rc.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm, yarn

### What operating system are you using?

Linux

### Describe the Bug

This is hydrated

```jsx
import { Counter } from '../components/Counter.jsx';

<Counter client:load />
```

but this isn't

```jsx
import { Foo } from '../components/Foo.jsx';

<Foo.Counter client:load />
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-stiwfz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks, I think we forgot to handle this case in our JSX transform!

**Comment by pomber** [comment]
Thanks @natemoo-re

I updated the dependencies in the example and it still doesn't work: https://stackblitz.com/edit/github-stiwfz-adqbjh?file=package.json

Am I missing something?
