### ISSUE TITLE
🐛 BUG: Incorrect value replacement inside of Markdown

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#421]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.
- [x] I am on an ESM Node.js version (`v12.20.0+, v14.13.1+, or v16.0.0+`)
- [x] I use package manager: npm
- [x] I run Astro on OS: Mac

### Describe the bug

Looks like `import.meta.env` is being replaced inside of Markdown (and maybe HTML) even though that's only a JS thing. 

Wanting to output `import.meta.env` to the page is definitely a Snowpack-specific thing so this isn't a high-priority for others. But currently, a docs page is broken: https://www.snowpack.dev/reference/environment-variables

As long as this isn't a larger issue about how static HTML is being generated/transformed, then we could get away with a quick fix for snowpack.dev for now.

### Steps to reproduce

1. Build the https://github.com/snowpackjs/snowpack www/ project
2. Visit "/reference/environment-variables" 
3. Notice the references to `SNOWPACK_ENV`, it should say `import.meta.env` instead.

**Comment by matthewp** [comment]
If you do:

```astro
<div>import.meta.env</div>
```

Rendering should output exactly that. Same if in a markdown file you did:

```md
## Heading

Here I am talking about import.meta.env.
```

**Comment by natemoo-re** [comment]
This seems to be working in 0.21!
