### ISSUE TITLE
Could not resolve ... url-parser.js during Build

### ISSUE THREAD

**Issue by st1ng7ay** [withastro/astro#4231]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

✅I am using the latest version of Astro and all plugins.
✅ I am using a 16.16.0 version of Node

Yarn run Dev - all perfect, but during Build have this message:

 finalizing server assets 

17:44:31 [build] Rearranging server assets...
✘ [ERROR] Could not resolve "./Users/ray/Code/intelmed/astro/node_modules/same-origin/url-parser.js"

    dist/_worker.js:1:64:
      1 │ ...uire$$0 from './Users/ray/Code/intelmed/astro/node_modules/same-origin/url-pa...
        ╵                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 error   Build failed with 1 error:
  dist/_worker.js:1:64: ERROR: Could not resolve "./Users/astro/node_modules/same-origin/url-parser.js"
  File:
    dist/_worker.js
  Code:
    > 1 | /* empty css                           */import require$$0 from './Users/ray/Code/intelmed/astro/node_modules/same-origin/url-parser.js';
        |                                                                ^
      3 | globalThis.process = {
      4 |   argv: [],

**Same code with netlify adaptor - all perfect, without problems**

### Link to Minimal Reproducible Example

https://codesandbox.io/s/suspicious-voice-x0m6ty?file=/astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by st1ng7ay** [comment]
same code deploying to netlify - all perfect, without problems

**Comment by matthewp** [comment]
It should be:

```js
import cloudflare from '@astrojs/cloudflare';
```

Closing for now, let me know if you still have an issue and we can reopen.

**Comment by zeshhaan** [comment]
I still face the same issue (trying to deploy on cloudflare)

Repro at https://github.com/zeshhaan/accessads-astro-sanity/tree/main/my-astro-site

<img width="1116" alt="Screenshot 2022-09-04 at 2 23 13 PM" src="https://user-images.githubusercontent.com/34814964/188305572-4a280503-e8f4-4d05-b8b3-6eaaf47e569a.png">

**Comment by st1ng7ay** [comment]
Yes,  Cloudflare adaptor         still broke with   "import sanityClient"   at build process.
Dev work fine, without errors. Netlify adaptor also work fine, without errors.


<img width="985" alt="Снимок экрана 2022-09-15 в 17 20 43" src="https://user-images.githubusercontent.com/79450231/190379941-96cebd5a-5544-4624-bd3e-4c21a4935d2d.png">

**Comment by zeshhaan** [comment]
Thanks to Support Squad. I got the issue solved. Here is the link if in case that helps. @st1ng7ay 
https://discord.com/channels/830184174198718474/1015611023971061782

**Comment by st1ng7ay** [comment]
I don't see any message at this channel:
<img width="716" alt="Снимок экрана 2022-09-16 в 13 37 48" src="https://user-images.githubusercontent.com/79450231/190572824-51c42d6c-38cb-42d8-aae9-08b0dac1195c.png">
