### ISSUE TITLE
CSS which is imported by JS(TS) is not loaded after build

### ISSUE THREAD

**Issue by kagankan** [withastro/astro#4242]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Problem

When JS file imports scss file, css file will not load after build.

```typescript
// src\components\LoadingScreen\LoadingScreen.ts
import './LoadingScreen.scss';
```

During `astro dev` :
LoadingScreen.scss is loaded (added to head tag)

After `astro build`:
LoadingScreen.scss is **NOT** loaded 
(`LoadingScreen.[hash].css` is generated correctly)

### Expected Results

Adds `<link rel="stylesheet" href="/LoadingScreen.[hash].css">` to the head tag of the `index.html`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-a2vwzj-5vbsjj?file=src/components/LoadingScreen/LoadingScreen.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thank you for posting. The key thing here is that the CSS is imported by hoisted script, and not inside of the server. I think this *should* still work though, so looking into it.
