### ISSUE TITLE
Typescript files added by create-astro when opting out of Typescript

### ISSUE THREAD

**Issue by smth** [withastro/astro#4243]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I just ran the `create-astro` wizard, chose to not use Typescript then found there were a couple of TS config files in the project. Not sure if this is intentional (apologies if so), but it felt a little confusing. Files were:
- env.d.ts
- tsconfig.json

### Link to Minimal Reproducible Example

https://codesandbox.io/s/github/withastro/astro/tree/latest/examples/basics

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! `.astro` files are currently TypeScript only, as such those files are required even if you don't plan on writing TypeScript necessarily. 

You should have gotten this message after choosing the option that should make this more clear: 
![image](https://user-images.githubusercontent.com/3019731/183986492-ea64c8f6-d9e6-4428-b2ce-77b00ef2e74d.png)

This particular prompt option was added hastily before 1.0 and we're currently evaluating removing it or at least wording it better, we pretty much all agree that it's very confusing and frustating

**Comment by smth** [comment]
Sounds like you're way ahead of me on this :) I'd say it's very likely I did get that message (which directly answers my question), and just didn't read it. Thanks for repeating the explanation here.

**Comment by FredKSchott** [comment]
Closing since this is technically answered by the message, but agreed the message could be better! We have a ticket on our core tracker to improve this to be less skippable
