### ISSUE TITLE
First line of Prism component output is indented

### ISSUE THREAD

**Issue by IanVS** [withastro/astro#4246]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

I've upgraded from beta.70 to 1.0.1, and found that my `Prism` components have an indent on the first line.

I've upgraded `@astrojs/prism` to `1.0.0` as well.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xfjsam?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue, @IanVS! Not sure what's going on here, we'll take a look.

As a very quick workaround, it looks like setting `white-space: normal` on the `pre` element and `white-space: pre` on the `pre > code` element fixes it. But we'll get a proper fix out as soon as we can!

**Comment by IanVS** [comment]
Thanks @natemoo-re for the quick 👀 .  Unfortunately, it seems that workaround removes all line breaks, so it won't work for my yaml examples.

**Comment by natemoo-re** [comment]
Oh no! Alright, I'll be sure to prioritize this, in that case!
