### ISSUE TITLE
Astro.url.pathname is different for dev and preview when using getStaticPaths()

### ISSUE THREAD

**Issue by jablonski** [withastro/astro#4252]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When generating dynamic routes, `Astro.url.pathname` has a trailing slash in build mode, but is fine in dev mode (no trailing slash).

The following example results in `/rover` in dev-mode and `/rover/` in build-mode.

This makes proper handling of pathnames in code very hard (worked in dev, but breaks in prod).

```
---
export function getStaticPaths() {
  return [
    {params: {slug: 'clifford'}},
    {params: {slug: 'rover'}},
    {params: {slug: 'spot'}},
  ];
}

const pathname = Astro.url.pathname
---

Pathname: {pathname}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-znyzfh?file=src%2Fpages%2F[...slug].astro,package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by djmtype** [comment]
Experiencing the same issue. On single a routing page, everything seems fine, but on a collection landing page, using something like `[...page]`, a trailing slash is appended to the end in production. To clarify, in development it works as expected: `/blog`, but in production or running preview, results in `/blog/`.

**Comment by FredKSchott** [comment]
This one feels urgent! Assigning @matthewp to take a look

**Comment by matthewp** [comment]
My intuition is that the dev mode version is wrong and that it should end with `/`. But [these docs](https://docs.astro.build/en/reference/api-reference/#data-passing-with-props) show examples that do not end with forward slash, so I guess it is preview that is wrong here.

**Comment by storialp** [comment]
I'm having this same issue. However, I'm not using getStaticPaths only regular routing and conditional styling. In dev-mode the pathname passed down via props to my react component doesn't have the trailing slash but it does on build.

**Comment by PanJohnny** [comment]
This is still an issue, however in this example this is component logic. I have an component for navigation and this is my logic for it.

```typescript
let pathName = Astro.url.pathname;

let paths: Record<string, string> = {
    "/": "Domů",
    "/polevky": "Polévky",
    "/hlavni-jidla": "Hlavní jídla",
};

if (!paths[pathName]) {
    paths[pathName] = title;
}
``` 

In development mode this works well - there are no trailing spaces in `Astro.url.pathname`. In production as you can see in my build logs when I logged the paths record:

```
├─ /polevky/index.html
{
  '/': 'Domů',
  '/polevky': 'Polévky',
  '/hlavni-jidla': 'Hlavní jídla',
  '/polevky/': 'Polévky'
}
``` 

there is a trailing slash in the path, that leads to path duplication in my project.

**Comment by anmpog** [comment]
Just spent a while debugging some conditional styling I had dependent on `new URL(Astro.request.url).pathname`. I'm curious about the decision to append the trailing slash to regular page routes in production but not in development. Am mostly curious for my own edification, as this seems to be an intentional decision given the length of time this thread has been open!
