### ISSUE TITLE
Astro build command doesn't properly recognise image paths

### ISSUE THREAD

**Issue by westernwontons** [withastro/astro#4254]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When I use the image component like so:

```ts
---
// @ts-nocheck
import { Image } from '@astrojs/image/components'
import me from '@/public/images/me.webp'
console.log(me);

---

<div class="flex justify-center ml-16 md:ml-32">
  <div class="mt-14 mb-16 relative">
    <div class="bg-[#00FFFF] absolute w-52 rounded-3xl left-2 -top-2 h-full" />
    <div class="relative w-52 overflow-hidden rounded-3xl">
      <Image src={me} width={1200} aspectRatio='3:4' />
    </div>
  </div>
</div>
```

the object printed to the console looks like this:
```ts
{
  src: '/Users/username/dev/astro/project/public/images/me.webp',
  width: 3000,
  height: 4000,
  format: 'webp'
}
```

which is the correct path to the file. But when I `pnpm build` the following is the output (with sensitive information swapped):

```bash

> @example/basics@0.0.1 build /Users/username/dev/astro/project
> astro build

01:02:41 [build] output target: static
01:02:41 [build] Collecting build info...
01:02:41 [build] Completed in 20ms.
01:02:41 [build] Building static entrypoints...
01:02:41 [build] Completed in 433ms.

 generating static routes
▶ src/pages/index.astro
/Users/username/dev/astro/project/public/images/me.webp
  └─ /index.html (+13ms)
Completed in 17ms.

"/Users/username/dev/astro/project/public/images/me.webp" image could not be fetched
 error   ENOENT: no such file or directory, copyfile '/Users/username/dev/astro/project/src/Users/username/dev/astro/project/public/images/me.webp' -> '/Users/username/dev/astro/project/dist/Users/username/dev/astro/project/public/images/me.webp'
 ELIFECYCLE  Command failed with exit code 1.
```

To reproduce, run:

`pnpm build`

### Link to Minimal Reproducible Example

https://github.com/westernwontons/astro-project

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue @westernwontons!

A few things could be happening here, but I suspect the problem is that the image you import _must_ be in the `src/` directory rather than the `public/` directory. This is a departure from the pattern Next.js uses, so we probably need to clarify this in our docs.

Would you mind moving your image into `src/` and reporting back? I also notice that the reproduction link is using an `.ico` file but I'm not sure if we support those (at the moment, at least).

**Comment by westernwontons** [comment]
Hi! I never would have thought of that! I tried and now it works. The reason why I used an `.ico` is because it was very late at night, I just wanted to check out the new update. I was really hyped about the new image component. Thanks for the help!
