### ISSUE TITLE
Unable to set up new Astro project

### ISSUE THREAD

**Issue by wmgweb** [withastro/astro#4259]
### What version of `astro` are you using?

1.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

 ■■▶ Copying project files...
could not find commit hash for latest
This seems to be an issue with degit. Please check if you have 'git' installed on your system, and install it if you don't have (https://git-scm.com).
If you do have 'git' installed, please run this command with the --verbose flag and file a new issue with the command output here: https://github.com/withastro/astro/issues

### Link to Minimal Reproducible Example

Generic error message? 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Alone1206** [comment]
I am having the same issue.

**Comment by natemoo-re** [comment]
Sorry about this, our `latest` branch was out of sync with `main`. Please give this another try!

**Comment by wmgweb** [comment]
It's still throwing me the same error unfortunately!

**Comment by lexmin0412** [comment]
same issue.

**Comment by bluwy** [comment]
I tried `npm create astro@latest` and it works for me.

**Comment by luisherreralg** [comment]
Same problem here:
![image](https://user-images.githubusercontent.com/105667470/214551236-e94674f1-d1c8-448e-b229-c69827d4e26d.png)
