### ISSUE TITLE
SolidJS component working locally but not on prod

### ISSUE THREAD

**Issue by codejet** [withastro/astro#4260]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I'm using Astro 1.0.1 and have created a site which has one component that is using SolidJS.
I installed all necessary dependencies (@astrojs/solid-js, solid-js, latest versions), added `integrations: [solid()]`, to the config, and `<MySolidComponent client:idle />` (also tried client:load) inside the Astro component which loads the SolidJS one.
Locally, SolidJS is being loaded and thus the component works. But on prod the page does not include any JS. Hope I'm not missing something obvious...

### Link to Minimal Reproducible Example

https://keen-alfajores-df789a.netlify.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hey @codejet, thanks for opening an issue! Do you have a link to the code so we can take a closer look and try to track this down?

**Comment by codejet** [comment]
Sorry, added the url of the site instead of the one of the repo: https://gitlab.com/codejet/oliverschmidt-astro/

**Comment by matthewp** [comment]
@codejet Your CSP policy doesn't allow inline scripts, you can see that in your console:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'
```

Astro uses an inline script to avoid adding JavaScript unless a page actually *uses* the client component, and to make it run faster since the script is small. 

You will need to change your CSP policy to allow this. Happy to reopen if you still have issues after that.

**Comment by codejet** [comment]
Thanks a lot @matthewp! And sorry, but somehow I totally didn't see this error 🙈 Works now 🎉

**Comment by matthewp** [comment]
Great to hear!
