### ISSUE TITLE
Custom 404 with Astro SSR not working on Netlify

### ISSUE THREAD

**Issue by maxcell** [withastro/astro#4269]
### What version of `astro` are you using?

1.0.2

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

MacOS

### Describe the Bug

When a user applies the `netlify` adapter (and turns the output to 'server') to produce a SSR build, it appears as though a custom 404 page doesn't get picked up for the redirect rules anymore. Even if a user also tries to use the `netlify.toml` to manually conduct the 404 redirect, it doesn't pick up the custom page.

It was a user reported bug within the [Discord](https://discord.com/channels/830184174198718474/961342596918177853/1007200825447305276).

---

You can see this live in these two experiences:
- The production build with only a static output: https://prince-test-astro.netlify.app/beef
- The deploy preview build with the server output and the netlify adapter: https://deploy-preview-1--prince-test-astro.netlify.app/beef

### Link to Minimal Reproducible Example

https://github.com/maxcell/test-astro-ssr/pull/1

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by irg1008** [comment]
Thank you for openning this issue. Has been driving me crazy for the past 2 days.

We talked about it on the discord channel and I have come with the next temporary solution using `_redirects` file in static folder. (It won't work using netlify config file).

We need to add the next redirect:

`/* /.netlify/functions/entry 404`

That way the 404 responses will be redirected and handled by the function like it does with the rest of pages.
I don't think it's the ultimate solution but It works for the moment

**Comment by irg1008** [comment]
Okay so It turns out it after few attemps the function has crashed and the invocation has failed. 😕

**Comment by irg1008** [comment]
I retract from my previous message. **It does work.**

The displayed error is non-related about a react component used within the 404 page. For that I am sorry

With the redirect as stated [above](https://github.com/withastro/astro/issues/4269#issuecomment-1212196991) it works perfectly on production!

**Comment by natemoo-re** [comment]
I'm curious if this has anything to do with https://github.com/withastro/astro/pull/4247, which was merged but has not been released yet?

cc @matthewp

**Comment by matthewp** [comment]
Thanks for the info @irg1008! Going to add that to our integration.

**Comment by matthewp** [comment]
@irg1008 does that entry need to be the last one in the redirects file?

**Comment by yogthesharma** [comment]
Do we have the same functionality for vercel.com also ?

**Comment by Anurodhydv** [comment]
> Thank you for openning this issue. Has been driving me crazy for the past 2 days.
> 
> We talked about it on the discord channel and I have come with the next temporary solution using `_redirects` file in static folder. (It won't work using netlify config file).
> 
> We need to add the next redirect:
> 
> `/* /.netlify/functions/entry 404`
> 
> That way the 404 responses will be redirected and handled by the function like it does with the rest of pages. I don't think it's the ultimate solution but It works for the moment



> Thank you for openning this issue. Has been driving me crazy for the past 2 days.
> 
> We talked about it on the discord channel and I have come with the next temporary solution using `_redirects` file in static folder. (It won't work using netlify config file).
> 
> We need to add the next redirect:
> 
> `/* /.netlify/functions/entry 404`
> 
> That way the 404 responses will be redirected and handled by the function like it does with the rest of pages. I don't think it's the ultimate solution but It works for the moment

I don't see a _redirect file in static folder. It is only in dict folder and the last two line are these
/404                             /.netlify/edge-functions/entry    200
/*                               /.netlify/edge-functions/entry    404
When ever i update this file it goes back to original state when i run yarn run build. Please help me with this @irg1008

**Comment by SStan-prog** [comment]
Unfortunately this solution is not working for my site. 
Is there a way to replicate this with built in Astro redirects?
