### ISSUE TITLE
Passing an an absolute path (such as `foo.html`) into `getStaticPaths` nests an index.html at the path

### ISSUE THREAD

**Issue by obj-obj** [withastro/astro#4275]
### What version of `astro` are you using?

1.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

![image](https://user-images.githubusercontent.com/57120300/184228149-99fb7e6e-8777-4583-ac70-6eec87f776ab.png)
Passing the above to `getStaticPaths`, instead of generating `foo.html`, generates this:
![image](https://user-images.githubusercontent.com/57120300/184228233-9eb5f09c-cfcc-4bd4-bd06-cccf51ed8cd1.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wgkxey

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This is the intended behavior, `params` do not set the output filename, they set the matching portion of the pathname. Is there a better error message we could provide here?

You might be looking for the [`build.format`](https://docs.astro.build/en/reference/configuration-reference/#buildformat) option?

**Comment by obj-obj** [comment]
> 

The `build.format` option affects the entire site, however. Maybe this should be a feature request for a way to change `build.format` for a specific file?

**Comment by natemoo-re** [comment]
@obj-obj Yes I think that's a fair feature request! Those usually go to [our RFCs repo](https://github.com/withastro/rfcs/discussions)!
