### ISSUE TITLE
When adding an astro file tailwindCSS classes are not HMR into the dev bundle

### ISSUE THREAD

**Issue by drewtownchi** [withastro/astro#4278]
### What version of `astro` are you using?

1.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 11

### Describe the Bug

1. Start Astro dev server
2. Create a new .astro page
3. Add HTML with styles you've never used anywhere else in the project
4. Notice that the styles are not applied
5. Restart dev server
6. See that styles are now applied
7. Any styles you've never used before in the project **will** now work on the page via HMR

The reproduction works with the default stackblitz Tailwind template.  Just add the file and navigate to the new page and attempt to view the styles which won't appear until you refresh the page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-51uqnk?file=src%2Fpages%2Fnew.astro,src%2Fpages%2Ftest.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Hey @drewtownchi! I just bumped your stackblitz to the latest Astro version (`npm i astro@latest`) and wasn't able to replicate. Mind double checking if the latest version fixes the issue for you?

**Comment by bholmesdev** [comment]
Hey, checking in that this issue persists! Let me know if the latest Astro release fixes the issue for you.

**Comment by drewtownchi** [comment]
I agree this issue seems to be resolved now. Thank you!
