### ISSUE TITLE
`@astrojs/image` should throw an error if `alt` text is missing

### ISSUE THREAD

**Issue by delucis** [withastro/astro#4291]
### What version of `astro` are you using?

v1.0.3

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

pnpm

### What operating system are you using?

macOS / Stackblitz

### Describe the Bug

Following up on some [Discord discussion](https://discord.com/channels/830184174198718474/857704189723541514/1007746334847152159): there seemed to be consensus that the image integration should throw an error if `alt` text is missing. For context this is what [eleventy-img does](https://www.11ty.dev/docs/plugins/image/#asynchronous-shortcode):

> You bet we throw an error on missing alt in `imageAttributes` (alt="" works okay)

This would be a breaking change, but seems do-able as a minor bump before the integration reaches v1.

### Link to Minimal Reproducible Example

Not provided but can make a repro where missing `alt` does not throw an error if needed!

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm totally on board with this!

**Comment by jasikpark** [comment]
Should it throw or should it warn/error?

Good start could be requiring `alt` in the types of Image and Picture at least

**Comment by delucis** [comment]
eleventy-img _throws_ and I think it’s a good default. (The error message should be helpful, e.g. “The `<Image>` component requires you provide `alt` text. If this image does not require an accessible label, set `alt=""`.”) If there’s really pushback we could add an `inaccessibleAltText` flag in the integration you have to enable, I guess?

**Comment by jasikpark** [comment]
I say just go the whole mile 😄

**Comment by DerYeger** [comment]
Is there any progress on this? If not, I'd like to work on this.

**Comment by DerYeger** [comment]
I had some spare time, so I created PRs for both the change and Astro's docs.
Let me know if anything is missing!
