### ISSUE TITLE
Duplicate CSS tags on build (not dev server)

### ISSUE THREAD

**Issue by obj-obj** [withastro/astro#4293]
### What version of `astro` are you using?

1.0.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Layout:
![image](https://user-images.githubusercontent.com/57120300/184449761-6467651a-5508-4ad7-8bd1-18d82c5a7bf3.png)
Build output:
![image](https://user-images.githubusercontent.com/57120300/184449589-8cc1e6e3-d999-4812-89f7-2ae3353a4fb2.png)

Seems to only happen when the layout is used by markdown files.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3ukg6x

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Just found the same issue in https://github.com/withastro/astro/issues/4328

**Comment by matthewp** [comment]
Testing a fix here, not read for merging though: https://github.com/withastro/astro/pull/4334

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/4334, should go out soonish. Thanks for filing!
