### ISSUE TITLE
TailwindCSS arbitrary classes don't work with template strings and class:list

### ISSUE THREAD

**Issue by florian-richter** [withastro/astro#4300]
### What version of `astro` are you using?

1.0.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

If I create a template string variable (``const foo = `${bar}`;``) and assign this via `<div class:list={[foo]}></div>` it is correctly rendered in HTML but the CSS file contains the string before interpolation and therefore the class has no effect.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8zxgch?file=src/components/Button.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by drewtownchi** [comment]
I'm not sure this in an Astro problem.  Tailwind requires all class named to be "complete unbroken strings" and do not "construct class names dynamically"

https://tailwindcss.com/docs/content-configuration#dynamic-class-names

**Comment by natemoo-re** [comment]
Yep, I think this unfortunately an upstream limitation!

**Comment by florian-richter** [comment]
Understood. I was hoping this could be resolved by generating the static HTML before running tailwind. 

If anyone has a similar issue, I worked around the issue by using `<style>` in my component (so not using tailwind but plain CSS).

**Comment by chaegumi** [comment]
You can do it like this

https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values
![image](https://github.com/user-attachments/assets/8f8cd582-2447-4851-8a39-48c8271dfb19)

```
<style is:global define:vars={{themeColor: render_value(siteinfo, 'theme_color')}}>
</style>

<div class="bg-[--themeColor]">
  <!-- ... -->
</div>
```
