### ISSUE TITLE
Lit integration in `examples/frameworks-multiple` causing demo to fail

### ISSUE THREAD

**Issue by aFuzzyBear** [withastro/astro#4304]
### What version of `astro` are you using?

Latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Testing out the Kitchen sink for a different issue, found the execution of the demo to fail `npm start` 
Its calling in the `@astrojs/lit` within the `astro.config.mjs` when its not installed within the `package.json`. 

![image](https://user-images.githubusercontent.com/28299972/184502940-b6d31c62-b92c-458f-9b67-eec5dc0769fe.png)

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/tree/latest/examples/framework-multiple

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks @aFuzzyBear! Closed in https://github.com/withastro/astro/pull/4305
