### ISSUE TITLE
Slow DX with @astrojs/mdx 0.9.0 (not 0.8.1)

### ISSUE THREAD

**Issue by brycewray** [withastro/astro#4307]
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

macOS 12.5

### Describe the Bug

With v.0.9.0 of the `@astrojs/mdx` package installed, each change of an MDX file requires 10–12 seconds before the screen updates, much as was the case with regular Markdown. This is regarding a site with a few hundred MDX files. Reverting to `@astrojs/mdx` v.0.8.1 seems to resolve the problem.

**Note**: the minimal reproducible example has only one MDX file, and it works just fine. I think many more MDX files are required before the bug appears — again, as was the case with regular Markdown. My own repo has over 300 MDX files and thus shows the problem: https://github.com/brycewray/astro-site.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zfypkq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Gah, thanks for the heads up @brycewray! I will look at this as soon as I can.

**Comment by brycewray** [comment]
> Gah, thanks for the heads up @brycewray! I will look at this as soon as I can.

@natemoo-re Just FYI, am still seeing this behavior with @astrojs/mdx 0.10.0 and Astro 1.0.6. It seems to vary according to the level of the content — i.e., `src/pages/about/index.mdx` updates quickly with 0.10.0, but `src/pages/posts/2022/test006/index.mdx` has the same slow-update behavior. Don't know whether that will help you but, again, just FYI.

**Comment by bholmesdev** [comment]
@brycewray Hm, I'm willing to bet `Astro.glob` is slowing things down. I know you're globbing `posts` but _not_ the `about` page in your example. We'll investigate the `0.9.0` changes to see what's cauisng this!

**Comment by brycewray** [comment]
> @brycewray Hm, I'm willing to bet `Astro.glob` is slowing things down. I know you're globbing `posts` but _not_ the `about` page in your example. We'll investigate the `0.9.0` changes to see what's cauisng this!

Yes, sir, I thought of that, too, but that whole “correlation != causation” meme kept me from suggesting it. :-) Anyway, thanks as always!

**Comment by brycewray** [comment]
FWIW, this issue has apparently resurfaced. Seeing in `@astrojs/mdx` 0.11.4. Edits to MDX-based pages with **no** `Astro.glob` usage appear almost instantly, but edits to MDX-based pages **with** `Astro.glob` take 10–20 seconds before refresh occurs.

**Comment by luciodale** [comment]
I am having this issue and I stripped out everything from the project. I've only got an `index.astro` file that looks like this:

```astro
const pages = await Astro.glob('./{*.mdx,*.md}')
console.log('this shouldnt take 7 seconds.')
---

<div>index of blog</div>

```

Within the folder I've got about 70 md and 70 mdx docs.. the mdx ones are reloaded veeeery slowly any time you save whatever page. Even pinning `v0.8.1` doesn't fix the problem.. any help?

**Comment by brycewray** [comment]
> I had this issue too, because I was using `Astro.glob` in a component to render links to next/previous blog posts. I refactored my code to get the next/previous blog posts in `getStaticPaths` and pass them as props instead, which helped significantly with hot reload time.

@phelipetls Same here re `Astro.glob`. Is your `getStaticPaths`-refactored code publicly viewable?

**Comment by bholmesdev** [comment]
@phelipetls Understood! Just curious, have you tried using [Vite's `import.meta.glob`](https://vitejs.dev/guide/features.html#glob-import) instead? This will fetch a map of lazy imports, so you can pick and choose which documents to import by file name. `Astro.glob` uses "eager" fetching under-the-hood, so you'll potentially import thousands of documents when you only need a few.

I'll also call out [content collections](https://docs.astro.build/en/guides/content-collections/) for this use case. It's now available as an experimental release, and will use lazy imports for the same DX improvements (with some nice fetch APIs on top).

**Comment by phelipetls** [comment]
> @phelipetls Same here re `Astro.glob`. Is your `getStaticPaths`-refactored code publicly viewable?

Yes, here's the commit with the refactor: https://github.com/phelipetls/blog/pull/15/commits/103b2cc12ccd81304656e42919adfc1e37b4393a

The initial load of all posts in dev mode still takes a considerable amount of time (say, when I go to `/posts`), but the reload time after editing has improved massively!

**Comment by brycewray** [comment]
@phelipetls Thanks! Interesting.

**Comment by phelipetls** [comment]
> Understood! Just curious, have you tried using [Vite's import.meta.glob](https://vitejs.dev/guide/features.html#glob-import) instead?

I haven't, but after looking at it I'm not sure how lazy loading would help me -- I would still need to read all markdown frontmatter to sort them by date, for instance. Maybe I'm missing something.

> I'll also call out [content collections](https://docs.astro.build/en/guides/content-collections/) for this use case.

@bholmesdev Yes, I've seen this only recently, but it definitely looks like the way to go. I was only put off by this:

> Files other than your .md/.mdx content are not permitted inside src/content/.

This is a big difference from Hugo, the SSG I'm migrating from, which allows collocating any file type alongside markdown (see [Leaf Bundles](https://gohugo.io/content-management/page-bundles/#leaf-bundles)). But anyway! I'm very happy that I managed to overcome this performance issue. I can live with the initial load time.

**Comment by bholmesdev** [comment]
@phelipetls Ah yes, if you need access to dates and other frontmatter properties then `import.meta.glob` won't help much. Only if you can retrieve the next and previous by file name somehow (which is understandably a no-go).

> Files other than your .md/.mdx content are not permitted inside src/content/.

And ah, we lifted that restriction recently! You can now colocate files (including files _outside_ collections) if you prefix with an underscore `_`. So for images and styles:

```bash
src/content/
  blog/
  // prefix files
  _styles.css
  _thumbnail.png
  // or directories
  _assets/
    stuff.css
  post.mdx
```
This admittedly won't allow relative image paths via standard Markdown syntax though; it'll only work with the Astro `Image` component in MDX. _But_ this should make colocating styles and other assets a bit nicer.
