### ISSUE TITLE
Multiple route matches in SSR does not work

### ISSUE THREAD

**Issue by LopezNoah** [withastro/astro#4310]
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Multiple route matches in SSR produces an error. The documentation shows that multiple routes will match based on priority, but this line [here](https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-astro-server/index.ts#L254) in the vite-plugin-astro-server directory prevents that.

![image](https://user-images.githubusercontent.com/22570798/184512443-4872016e-eccd-4730-957b-0fe12d56c3cd.png)

![image](https://user-images.githubusercontent.com/22570798/184514123-b135605b-3b25-4d29-b1da-244676fd9b1a.png)

Commenting out those few lines enables SSR with multiple route matches again. The package astro@1.0.0-rc.2 does not contain this change. This is similar to this issue here [🐛 BUG: Can't have 2+ dynamic routes in the same folder. Only one works](https://github.com/withastro/astro/issues/3621)

I am also curious about whether this change is permanent and needs to be written in the docs.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4dd3np?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
@tony-sull to confirm that this error catching code is okay to remove, I think it should be. @LopezNoah if you're willing to submit a PR to fix this, that would be great!
