### ISSUE TITLE
Astro runs on `:3000` port even though another app is running on the same port

### ISSUE THREAD

**Issue by yxshv** [withastro/astro#4315]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I had a React app running on port `3000` and ran an astro app thinking that it will automatically use a different port. Bu, it didn't

### Link to Minimal Reproducible Example

just run an different app on localhot:3000 and then run an astro app

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Astro's dev server uses Vite. Does this happen on a Vite app too? Also, is your React app running on http://172.0.0.1:3000 or http://[::1]:3000. The port detection depends on which hostname your React app is running vs Vite's

**Comment by FredKSchott** [comment]
I can't reproduce. When I have something running on `:3000`, `astro dev` starts on `:3001` instead.

**Comment by FredKSchott** [comment]
@yxshv can you go into your node_modules folder and add some logging to this file? I'm curious if `onError` isn't being hit here on Windows.

https://github.com/withastro/astro/blob/485742dc0dd18b6b6bef6be969b900265cac7eaa/packages/astro/src/core/preview/index.ts#L135-L148

**Comment by yxshv** [comment]
@FredKSchott Nope it does not. 

![](https://us-east-1.tixte.net/uploads/img.yashverma.me/WindowsTerminal_hQGs7ojCmz.png)

```js
        httpServer == null ? void 0 : httpServer.on("error", onError);
      };
      const onError = (err) => {
        console.log(err)    // +++++++++++
        if (err.code && err.code === "EADDRINUSE") {
          if (!showedPortTakenMsg) {
            console.log("port not taken")    // +++++++++++
            info(logging, "astro", msg.portInUse({ port }));
            showedPortTakenMsg = true;
          }
          port++;
          return listen();
```
```js
       listen();
    });
  }
  console.log("starting server");    // +++++++++
  await startServer(startServerTime);
  function closed() {
    return new Promise((resolve, reject) => {
      httpServer.addListener("close", resolve);
      httpServer.addListener("error", reject);
    });
  }
 ```

**Comment by yxshv** [comment]
I thought. Lets just use a different `PORT` and added `PORT=3001` in environment variables

and to my surprise it still ran on `:3000` 

![](https://us-east-1.tixte.net/uploads/img.yashverma.me/WindowsTerminal_GbP5U56XzT.png)

**Comment by bluwy** [comment]
> and to my surprise it still ran on `:3000`

I don't think we support reading from `PORT`.

Is this issue related to `astro dev` or `astro preview` or both? And how are you starting your other app

**Comment by yxshv** [comment]
> > and to my surprise it still ran on `:3000`
> 
> I don't think we support reading from `PORT`.
> 
> Is this issue related to `astro dev` or `astro preview` or both? And how are you starting your other app

oh. It does not work on both `dev` and `preview`

I am starting the other react (`nextjs) app with `pnpm dev`

**Comment by SachaG** [comment]
Same issue here:

<img width="570" alt="Screen Shot 2022-08-22 at 20 22 47" src="https://user-images.githubusercontent.com/358832/185909715-478a6b9f-17d3-4cdd-a219-8ea9ae2ddeec.png">
