### ISSUE TITLE
astrojs/image does not remove URL variables from remote image URLs

### ISSUE THREAD

**Issue by wilkomanger** [withastro/astro#4317]
### What version of `astro` are you using?

1.0.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Currently in `@astrojs/image`, when using a remote image with URL variables (e.g. `https://example.com/123?access_token=abc`) gets resolved to the following local URL: `/_image/123?access_token=abc`.

This should be `/_image/123`, so that the access token is not leaked, and also just to save some space. The image is reachable by `/_image/123` already, the URL variables are not used in any way.

Slightly related: It seems that (in my experience) all generated URLs end with `.undefined`. Also something to look at?

Note regarding the linked example: It seems that `@astrojs/image` does not work in Stackblitz, so you'll have to run the example locally. Also note that you have to run `npm run build` to see the final generated URL (not `npm run dev`).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qse61x?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
The access token should probably be encoded with the URL. We should clarify query string behavior and then add some tests to make this behavior explicit.

**Comment by wilkomanger** [comment]
> The access token should probably be encoded with the URL.

Could that maybe an option? Whether to encode query strings or not?
