### ISSUE TITLE
Bug on serializing circular referenced object (just hanging with no error in production)

### ISSUE THREAD

**Issue by outerlook** [withastro/astro#4332]
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

Self lambda adapter

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Why would I use a circular referenced object, you might ask. Well, while using [gqty](https://gqty.dev/) with an grapqhl query like:
```gql
{
	user {
		orders {
			user
		}
	}
}
```

which may generate an infinite loop object if it tries to serialize each one.

I don't know which would be the nicest, deal with it somehow or a clear error.

At the repro it luckily throws "Maximum stack" error. But at lambda now it just hangs. I think it is important because I had no clue why my lambda requests were just timing out, with no output after trying to render. It didn't happen before new hidration scripts

### Link to Minimal Reproducible Example

https://codesandbox.io/s/mystifying-bouman-zpbnzh?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hey @outerlook! It'd be great to _allow_ this, but for now I've made a PR to give a more helpful error as a quick patch to avoid the indefinite hanging.

**Comment by outerlook** [comment]
> Hey @outerlook! It'd be great to _allow_ this, but for now I've made a PR to give a more helpful error as a quick patch to avoid the indefinite hanging.

That is good enough, in my opinion. It isn't a requirement to be able to keep this objects, just to know what is going wrong.  Thanks @natemoo-re !

**Comment by natemoo-re** [comment]
I'm picking up the PR again which got closed as stale
