### ISSUE TITLE
Relative paths of inline script tags in nested folders get mangled by `astro dev` and `astro preview`

### ISSUE THREAD

**Issue by swift502** [withastro/astro#4337]
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I'm bringing this up because this behavior seems to differ from the standard web browser behavior and other dev servers such as [webpack-dev-server](https://github.com/webpack/webpack-dev-server) or [http-server](https://github.com/http-party/http-server).

Given this folder setup:

![image](https://user-images.githubusercontent.com/24359130/184697428-101f27d7-c8f8-466f-b3bb-5805d7410bb6.png)

In /index.astro, we're importing script.js relatively as such:
```html
<script is:inline src="./nested_folder/script/script.js"/>
```

And in /nested_folder/index.astro, we're importing the same script in the same way:
```html
<script is:inline src="./script/script.js"/>
```

First one correctly imports and runs the script.

But second one throws a 404, because the paths get mangled, converting them to root-relative paths:
```
./script/script.js -> /script/script.js
script/script.js   -> /script/script.js
```

The issue affects both `astro dev` and `astro preview` commands.

Is this intentional or a bug?
Thanks.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yhv4gs?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by swift502** [comment]
I guess my main point is that even if it was intended for the `dev` command, for `preview` it makes no sense.
The sole purpose of `preview` is to see how the website behaves in the browser right?
But this behavior is different from the browser, so it kinda seems like a bug.

**Comment by natemoo-re** [comment]
Sorry, this definitely sounds like a bug! Astro should definitely not be transforming any `is:inline` scripts.

**Comment by swift502** [comment]
Could this be related? https://github.com/vitejs/vite/issues/9358
Might be a vite issue? I understand Astro is just using the Vite dev server and preview commands?

**Comment by swift502** [comment]
@matthewp Thanks a lot! I'll definitely use `trailingSlash: 'always'` to prevent this.

**Comment by swift502** [comment]
The only idea I have to prevent this in the future is to set trailingSlash to 'always' by default to match the default 'directory' build.format.
