### ISSUE TITLE
Bug: Shiki doesn’t style <pre> tag consistently for both .md and .mdx

### ISSUE THREAD

**Issue by scottaw66** [withastro/astro#4345]
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Shiki wrap does not work by default in the same way in mdx as it does in md. Upon inspection, astro inserts the following styles into <pre/> in compiled md file content, but not compiled mdx file content:

overflow-x: auto; white-space: pre-wrap; word-wrap: break-word;

The result is that shiki syntax code blocks compiled from md files wrap neatly while shiki syntax code blocks compiled from mdx files don’t wrap and don’t shrink responsively, but instead extend outside the code block div.

### Link to Minimal Reproducible Example

https://github.com/scottaw66/astro-mdx-md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by scottaw66** [comment]
Looks like Ben already has this one fixed - I thought the change from shiki twoslash to shiki for mdx had already been published to the world.

**Comment by Einenlum** [comment]
I still encounter this issue in Astro 1.6.6 and @astrojs/mdx 0.11.6.

Can you guide me to where which update is supposed to have fixed this bug? @scottaw66
