### ISSUE TITLE
`vite.assetsInclude` is not working on `astro build`

### ISSUE THREAD

**Issue by kagankan** [withastro/astro#4346]
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Background
I want to use `.glb` (3D model data) in Three.js

### Bug
1.  add `vite.assetsInclude` config to astro.config to use .glb as assets file.
```
vite: {
    assetsInclude: ['**/*.glb'],
}
```
2. import .glb file from TS (`import cameraMove from '@/assets/models/camera_move.glb';`)
3. it works on `astro dev`
4. it doesn't work on `astro build`. I got errors (.glb is binary file, so there are garbled characters)

```
vite v3.0.5 building for production...
✓ 3 modules transformed.
[vite:build-import-analysis] Parse error @:5:37
file: C:/Users/Owner/Documents/astro-sample/src/assets/models/camera_move.glb:5:36
3: ?UU? ?��*?UU5?@?��J?UUU?`?��j?UUu?�?UU�?���?�?UU�?���?�?UU�?���?�?UU�?���?�?UU�?
// ...
transforming (5) node_modules\three\build\three.module.js error   Parse error @:5:37
  File:
    C:/Users/Owner/Documents/astro-sample/src/assets/models/camera_move.glb
  Code:
    3: ?UU? ?��*?UU5?@?��J?UUU?`?��j?UUu?�?UU�?���?�?UU�?���?�?UU�?���?�?UU�?���?�?UU�?
// ...
  Stacktrace:
    at parse$b (file:///C:/Users/Owner/Documents/astro-sample/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:33579:355)
    at Object.transform (file:///C:/Users/Owner/Documents/astro-sample/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:40749:27)
```

### Link to Minimal Reproducible Example

https://github.com/kagankan/astro-sample/tree/f62581354ae153089c810ce35c90841da7283078

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue @kagankan! I suspect we're not passing this option through to the build as we should be.

Any interest in submitting a PR? This option needs to be passed through in two places:
https://github.com/withastro/astro/blob/cd679af4e74c3155806c4643d170820636d7184c/packages/astro/src/core/build/static-build.ts#L118 and https://github.com/withastro/astro/blob/cd679af4e74c3155806c4643d170820636d7184c/packages/astro/src/core/build/static-build.ts#L197

**Comment by bluwy** [comment]
I actually submitted some refactors to the code today at https://github.com/withastro/astro/pull/4344 which should fix this too.

**Comment by kagankan** [comment]
@bluwy 
That's great! 🙌 Thank you.
