### ISSUE TITLE
no such file with astro/image on build

### ISSUE THREAD

**Issue by mundry** [withastro/astro#4349]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm, pnpm

### What operating system are you using?

Linux

### Describe the Bug

I'm using the astro/image integration with the `Picture` component. Using imported images as the value for the `src` prop creates an error when running `npm run build`. The exact same code works in dev mode.

When specifying the image path as a string value to `src` the image gets interpreted as a remote image and I'm required to pass a value for `aspectRatio`; both on build and dev. Going the route of the string path works on build and dev, though.

I've tested the exact same project setup with `npm` and `pnpm`, both under `Node 16.17.0` and `Node 18.7.0`.

# How to reproduce

```bash
/tmp/astro-path$ npm create astro@latest

Welcome to Astro! (create-astro v1.0.0)
Lets walk through setting up your new Astro project.

✔ Where would you like to create your new project? … ./my-astro-site
✔ Which template would you like to use? › Just the basics (recommended)
✔ Template copied!
✔ Would you like to install npm dependencies? (recommended) … yes
✔ Packages installed!
✔ Would you like to initialize a new git repository? (optional) … no
ℹ Sounds good! You can come back and run git init later.
✔ How would you like to setup TypeScript? › Strict (recommended)
✔ TypeScript settings applied!
✔ Setup complete.
✔ Ready for liftoff!

/tmp/astro-path$$ cd my-astro-site
/tmp/astro-path$/my-astro-site$ npx astro add image
...
 success  Added the following integration to your project:
  - @astrojs/image

/tmp/astro-path$/my-astro-site$ mkdir public/img
/tmp/astro-path$/my-astro-site$ rm -r src/components src/layouts
/tmp/astro-path$/my-astro-site$ npm run build

> @example/basics@0.0.1 build
> astro build

18:02:37 [build] output target: static
18:02:37 [build] Collecting build info...
18:02:37 [build] Completed in 7ms.
18:02:37 [build] Building static entrypoints...
18:02:38 [build] Completed in 572ms.

 generating static routes
▶ src/pages/index.astro
  └─ /index.html (+8ms)
Completed in 12ms.

"/tmp/astro-path/my-astro-site/public/img/hero.jpg" image could not be fetched
 error   ENOENT: no such file or directory, copyfile '/tmp/astro-path/my-astro-site/src/tmp/astro-path/my-astro-site/public/img/hero.jpg' -> '/tmp/astro-path/my-astro-site/dist/tmp/astro-path/my-astro-site/public/img/hero.jpg'
```
Same result running it anywhere else than under `/tmp`.

Do you have an idea what could be going wrong here?

### Link to Minimal Reproducible Example

https://github.com/mundry/astro-image-issue-demo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by michaeltoohig** [comment]
I have the same issue but the build completes I just get 404 to the image file.

I am using the `Image` component and not the `Picture` component. My mdx file may look like the following.

```
---
layout: '@layouts/project.astro'
title: Something
img: '/assets/project/something.png'
---
import { Image } from '@astrojs/image/components';
import Template from './assets/template.png';

<Image src={Template} />
```

In dev the images in `Image` components load properly but then when built the images are at the correct location in the `dist` directory but it returns 404. My images are in an `assets` directory alongside the markdown file. So in production the path to the image looks like `www.example.com/_image/pages/project/something/assets/template_1920x1080.png`. When visiting this address I actually hit the Astro 404 and not the image.

But the image I use in the frontmatter is located in the `public/assets/` directory and that does load correctly in production when built. So maybe I'm not using images correctly and they all should be in the `public` directory?

**Comment by tony-sull** [comment]
@mundry The image files need to be imported from '/src' rather than `/public`.  Public is meant for files that aren't touched at all by Astro during the build, they're just copied over as-is into `dist`

Bumping this down to a `p2` while I track down how we can add a better error message here.  The build really should catch this and warn or error with a clear note that images should always be imported from `src` :+1:

**Comment by mundry** [comment]
Thanks @tony-sull for clearing up my mistake. It works like a charm putting the images under 'src', both with `Picture` and `Image` components.

I consider my issue resolved.

**Comment by tony-sull** [comment]
Glad that did the trick!  I'm looking into whether we can support using `/public` in the image components as well so hopefully this limitation will be gone soon! 🤞

**Comment by panwauu** [comment]
In the [documentation](https://docs.astro.build/en/guides/integrations-guide/image/#installation) it is stated: `For images in your project’s repository, use the src relative to the public directory.`

It would be good to change this if this issue is still open.
