### ISSUE TITLE
Global styles from Markdown pages persist when imported to another page

### ISSUE THREAD

**Issue by skra-pa-pa** [withastro/astro#4359]
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Say there are two layouts, `MainLayout.astro` and `BlogPostLayout.astro`. BlogPostLayout uses a global `<style is:global>` to style elements within its markdown children. There are markdown blog posts in `src/pages/blog/*.md` that use `BlogPostLayout`.

There is a page `src/pages/blog/index.astro` using `MainLayout` that imports markdown blog post files via `Astro.glob("./*.md")`.  This page *should* only have styles from itself and `MainLayout`, *but instead* also has the global styles from `BlogPostLayout`.

Sorry if my explanation is unclear, just look at the minimal example.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kq1tg9?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I can reproduce this too. My hunch is that because CSS are side-effectful in markdown that it's included when globbing as well.

**Comment by matthewp** [comment]
That is correct, Astro.glob turns into an import statement. We're going to fix this with a new feature that doesn't do that.
