### ISSUE TITLE
Response body is available in SSG but query is not

### ISSUE THREAD

**Issue by reggi** [withastro/astro#4361]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

Local

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I wanted to point out that I'm able to use `const value = await Astro.request.text()` with my astro site configured default (ssg), but unable to get the request query? This doesn't seem to make any sense, seems a bit like a contradiction. If I can dynamically render the page with custom data from the request, why don't I have access to the query? 

1. I'd like access to the query / docs on how to access it.
2. We may want to flag access to the request body 
3. Make it so that if the code accesses dynamic pieces of code within the Astro context the site switches to SSR?

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hey @reggi! Thanks for opening an issue. This definitely seems like an oversight—the reason query params are not available is because `output: 'static'` will not have any requests at build time. It seems reasonable that the request body should not be available either.

**Comment by matthewp** [comment]
Agreed, the body should not be available in static mode.

**Comment by reggi** [comment]
Thanks! I also think there's another potential bug I don't think `output: 'server',` allows access to the query and theoretically it should right?

**Comment by matthewp** [comment]
Yep! It should.

**Comment by cj** [comment]
Just ran into this :)

**Comment by cj** [comment]
Quick work around for right now:

```javascript
 import url from 'url'
 import querystring from 'querystring'

  const query = querystring.decode(url.parse(request.url).query)
```

**Comment by bluwy** [comment]
@reggi @cj I can't seem to find any bug when testing locally. In SSG, `Astro.request.body` and `Astro.url.searchParams` are `undefined` and `""` by default. In SSR, both are populated, which is the expected behaviour. Should this information be updated in the docs instead? Or maybe I'm missing something.

**Comment by cj** [comment]
@bluwy https://github.com/cj/eslint-plugin-astro-script-parsing-error/blob/main/src/pages/api/trpc/%5Btrpc%5D.ts#L14 `request.url` is a string.

**Comment by reggi** [comment]
I should have provided an example. I agree I tried it as well and couldn't see the issue again and everything worked with and without `output: "server"` as expected. Clarity in the docs would be great, thanks!

**Comment by bluwy** [comment]
> @bluwy https://github.com/cj/eslint-plugin-astro-script-parsing-error/blob/main/src/pages/api/trpc/%5Btrpc%5D.ts#L14 `request.url` is a string.

That's from the standard `Response` object so a string is expected. Astro does provide `Astro.url` which is the same as `new URL(Astro.request.url)` but that's for Astro components only. I tested the repo and it looks like the search params are properly passed so it seems to be working fine.

I'll update the docs regarding this for now.

**Comment by reggi** [comment]
🙏
