### ISSUE TITLE
Spelling mistake in the docs example template

### ISSUE THREAD

**Issue by vincent-uden** [withastro/astro#4367]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

In src/components/LeftSideBar/LeftSidebar.astro what I'm assuming should be called `pseudoSection` is currently spelled `pesudoSection`. If this isn't intended, I'd happily fix it

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/docs?file=src/components/LeftSidebar/LeftSidebar.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Looks like a typo to me, feel free to send a PR!
