### ISSUE TITLE
Layout flash

### ISSUE THREAD

**Issue by adebiyial** [withastro/astro#4368]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Layout isn't preserved with route changes. If I have a dark background set for the `body` in the shared layout, there will be flashes when I switch routes

https://user-images.githubusercontent.com/18689106/185141863-77508ed4-8b19-4c8f-8a83-31a27d928edd.mov

### Link to Minimal Reproducible Example

https://github.com/adebiyial/astro-getting-started

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hey @adebiyial! This is expected as Astro does not come with SPA routing out of the box. You can refer to our [MPA vs SPA](https://docs.astro.build/en/concepts/mpa-vs-spa/) guide for more information.

For this particular use case, I'd highly recommend checking out Josh Comeau's [Dark Mode Guide](https://www.joshwcomeau.com/react/dark-mode) for how to implement this behavior in a blocking manner. If you have any more questions, feel free to join us in [our Discord](https://astro.build/chat) and create a support thread in `#support-threads`.
