### ISSUE TITLE
Access to a `astro.renderToString` method?

### ISSUE THREAD

**Issue by reggi** [withastro/astro#4372]
I've dug into the code but I couldn't find any mention / Astro api that would allow me to pass in a `.astro` file and spit out HTML. Something like `react.renderToString`. Does this exist?

Not sure if this would live within the Astro global, or just within the package something like:

```ts
import astro from 'astro'
import Example from './example.astro'

astro.renderToString(Example, { prop: true })
```

or

```ts
import astro from 'astro'
astro.renderToString('./example.astro', { prop: true })
```

**Comment by reggi** [comment]
For context on why I'm trying to do this. I'd like to be able to have an API endpoint that returns an astro component HTML. That's pretty much it. I think it would be cool.

**Comment by bluwy** [comment]
Recently used the [Astro compiler](https://github.com/withastro/compiler#transform-astro-to-valid-typescript) which might be similar to what you're looking for, though it's still a bit internal-ish to use AFAIA.

Anyways, the issues here are usually for bug reports. For feature requests, please open at https://github.com/withastro/rfcs/discussions! You might get better awareness there.

**Comment by reggi** [comment]
Ok closing out opened discussion here: https://github.com/withastro/rfcs/discussions/254
