### ISSUE TITLE
Astro.glob crashes if filename contains apostrophe

### ISSUE THREAD

**Issue by alvinometric** [withastro/astro#4373]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If the filename of one of the files read by `Astro.glob` contains an apostrophe `'`, everything crashes.

```
---
const posts = await Astro.glob('../content/**/*.md')
console.log(posts);
---

<main>

</main>
```

You can see the error in the reproducible example. 

The biggest issue is, it _just crashes_. There wasn't any clear error message telling me it was a filename issue. It took trial and error to figure out.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mjfepe-lwngmi?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is a bug upstream in Vite. I submitted https://github.com/vitejs/vite/pull/9729 which should fix this. Will close the PR when we update the Vite version used.

**Comment by alvinometric** [comment]
Fantastic, thank you for the quick turnaround

**Comment by FredKSchott** [comment]
Fixed upstream!
