### ISSUE TITLE
Netlify Edge Functions route pattern validation error

### ISSUE THREAD

**Issue by jackiewmacharia** [withastro/astro#4376]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

We set up [validation](https://github.com/netlify/build/commit/f3942eac3e6c020fa52f60661f5300a0a0f45d27) for Edge Functions manifest.json recently and came across some build failures from some astro route patterns. This happens if a route pattern is set up at this point: [astro/blob/main/packages/integrations/netlify/src/integration-edge-functions.ts](https://github.com/withastro/astro/blob/main/packages/integrations/netlify/src/integration-edge-functions.ts#L56). This error is triggered during `netlify build`.

We currently handle this by serializing it in this way in [netlify/build](https://github.com/netlify/edge-bundler/blob/main/src/manifest.ts#L34). I have minimal repro [code here](https://github.com/jackiewmacharia/astro-cattos) and fix on my fork [branch here](https://github.com/jackiewmacharia/astro/commit/100cce705d04d1627d2aff401a71c09e402a150e) ready for a PR if that's okay. Instructions to test the fix available [here](https://github.com/jackiewmacharia/astro-cattos#testing-fix-instructions).

Error screenshot:
<img width="1515" alt="ntl build err" src="https://user-images.githubusercontent.com/16131515/185388679-ba118cf4-9607-4557-9f2c-a18f208b13ea.png">

### Link to Minimal Reproducible Example

https://github.com/jackiewmacharia/astro-cattos

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kingroho** [comment]
I'm getting this error too. Vercel and Cloudflare adapters seem to be working fine.

**Comment by bholmesdev** [comment]
@jackiewmacharia Ah, thanks for the thorough investigation and fix! Such a joy reading issues like this 😄 
I confirmed this issue exists on Netlify CLI 10.18 and later, and can also confirm your fix solves the issue. I'll make a PR for expediency here but I'll tag your profile as a co-author.
