### ISSUE TITLE
Vite plugin works differently for CSS files in `astro dev` vs. `astro build` 

### ISSUE THREAD

**Issue by soluml** [withastro/astro#4377]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows (WSL)

### Describe the Bug

I've written a plugin that works with Vite in a similar vein to [postcss-modules](https://github.com/madyankin/postcss-modules). The stylesheet is processed and JSON is returned to the component in place of the CSS file.  However, `astro build` does not run the plugin for CSS/SCSS files as expected during the build process. 

I've attached a couple of images and a very small reproducible demo using a very scaled back plugin that simply replaces `.example.css` files with a string for component consumption. 

### `astro.config.mjs`
![image](https://user-images.githubusercontent.com/589571/185404083-209b0a9e-6bd2-41db-98a6-57720bc05b65.png)

### `astro dev`
![image](https://user-images.githubusercontent.com/589571/185402785-0633b7cc-9bef-494c-a1e8-46f54ec08cb1.png)

### `astro build`
![image](https://user-images.githubusercontent.com/589571/185402978-7136b06f-fbe4-4df8-9c45-cccfedaa760a.png)

### Link to Minimal Reproducible Example

https://github.com/soluml/astro-bug-css-plugin

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
That's odd. This makes me think that this is technically a Vite issue, since you're seeing the difference inside the Vite plugin `transform()` method. Assigning to @matthewp to take a quick look, in case it's actually on our end.

**Comment by soluml** [comment]
Thanks for taking a look! I've been experimenting with the CSS build side of things off an on since the 1.0 release and in my attempts to work around the above issue I found that disabling the `vite.build.cssCodeSplit` option also breaks all CSS in the production build for Astro (#4413).

I'm not sure if the issues are related, though it should be noted that disabling `cssCodeSplitting` does fix the text issue above, just breaks all CSS in production builds.

**Comment by matthewp** [comment]
Vite internal plugin injects `?used` during the build, so your plugin needs to account for that in your regex checking. See https://github.com/vitejs/vite/blob/21515f167b2adf3a1574a13fd1f9e5dbae06c314/packages/vite/src/node/plugins/importAnalysisBuild.ts#L308-L324
