### ISSUE TITLE
Tailwind classes with arbitrary values don't get applied when in a template literal

### ISSUE THREAD

**Issue by femtozer** [withastro/astro#4379]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I'm using @astrojs/tailwind v1.0.0.
I use tailwind classes with [arbitrary values](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values).
It doesn't work when the value is set in a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).
Look at the index.astro file in the stackblitz example for a better understanding.
Do you see a workaround that would allow to use an astro variable as an arbitrary value?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ccjahy?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by davidhellmann** [comment]
I think that's more a Tailwind thing: https://tailwindcss.com/docs/content-configuration#dynamic-class-names
Tailwind didn't know you dynamic class.

**Comment by faizananwerali** [comment]
+1
I also experienced this while developing. I don't think I've seen this type of error with any other framework.

**Comment by femtozer** [comment]
I confirm that this is a tailwind thing.
The only workaround I found is to directly use the style attribute:
```<div style={`background: ${bgColor}`}><div>```

**Comment by jonaspm** [comment]
Is this fixed in the new lit 3.1.x ?
