### ISSUE TITLE
Client directive not working on namespaced JSX

### ISSUE THREAD

**Issue by pomber** [withastro/astro#4389]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm, yarn

### What operating system are you using?

Linux

### Describe the Bug

This is hydrated

```jsx
import { Counter } from '../components/Counter.jsx';

<Counter client:load />
```

but this isn't

```jsx
import { Foo } from '../components/Foo.jsx';

<Foo.Counter client:load />
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-stiwfz-adqbjh?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pomber** [comment]
Hey @natemoo-re, sorry to reopen issue #4209, but looks like it is still happening.

**Comment by pomber** [comment]
To add more context, I think this is the only issue blocking the integration of Astro with [Code Hike](https://codehike.org/).

**Comment by peterkrieg** [comment]
Thanks @pomber   for your excellent work with code hike, it looks amazing!  I'm looking forward to trying it on astro, it feels like a really good fit for a content-focused framework like astro.

**Comment by JohnDaly** [comment]
This issue should be fixed by: https://github.com/withastro/astro/pull/4403

The latest version of Astro should support this use case

**Comment by pomber** [comment]
@JohnDaly do you know what's wrong with this example?

> ### Link to Minimal Reproducible Example
> https://stackblitz.com/edit/github-stiwfz-adqbjh?file=package.json

**Comment by JohnDaly** [comment]
> @JohnDaly do you know what's wrong with this example?
> 
> > ### Link to Minimal Reproducible Example
> > https://stackblitz.com/edit/github-stiwfz-adqbjh?file=package.json

Updating that example to use `"astro": "^1.2.6"` should fix the problem

**Comment by rishi-raj-jain** [comment]
@matthewp this can be closed per comment above ig.

**Comment by matthewp** [comment]
Great, thank you everyone!
