### ISSUE TITLE
Vercel Edge Adapter fails to deploy if react integration is enabled

### ISSUE THREAD

**Issue by janus-reith** [withastro/astro#4391]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Using the following astro config:
```
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import vercel from "@astrojs/vercel/edge";

export default defineConfig({
  integrations: [react()],
  output: "server",
  adapter: vercel(),
});
```

Deployment on Vercel fails with:
`commonjs--resolver] Cannot bundle Node.js built-in "stream" imported from "node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js". Consider disabling ssr.noExternal or remove the built-in dependency.`

Deployment succeeds when I disable the React integration or switch to `@astrojs/vercel/serverless`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-napk2o

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
I'm not sure why https://unpkg.com/browse/react-dom@18.2.0/cjs/react-dom-server-legacy.node.production.min.js is being loaded, https://unpkg.com/browse/react-dom@18.2.0/cjs/react-dom-server.node.production.min.js doesn't have this dependency on `stream` and should work fine. I don't know how this package works internally though, so more investigation needed to find out why the `legacy` file is being used. I can reproduce on stackblitz.

**Comment by janus-reith** [comment]
@bholmesdev I tried the @astrojs/vercel v1.0.1 and while the build succeeds now,  pages that use a react component are rendered with an empty body.
I have added a second page similar to the other one, except that the React component has been omitted, that one renders fine.

**Comment by bholmesdev** [comment]
Ah, fair enough! I'll re-open this issue so we don't have to refile a separate one. Will investigate 👍
