### ISSUE TITLE
Scss imported with `?url` is processed on dev server, but not when site is built

### ISSUE THREAD

**Issue by obj-obj** [withastro/astro#4395]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Could possibly be a vite issue, but I'm reporting the bug here in case it isn't. Importing a scss file with `?url` like this works fine on the dev server.
![image](https://user-images.githubusercontent.com/57120300/185712624-f5678839-1892-4cf8-91c3-6ff8868500db.png)
However, the build output looks like this:
![image](https://user-images.githubusercontent.com/57120300/185712678-a6db048e-f457-4a1d-a864-f21d21dad494.png)
![image](https://user-images.githubusercontent.com/57120300/185712695-f4023c11-d47c-4027-8471-2c27ac1226fb.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nzkhmd

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by obj-obj** [comment]
If I'm debugging this myself where would I start? I can't find the code that handles `?url` stuff...

**Comment by matthewp** [comment]
If you use `?url` or `?raw` those things are not going to be built. Vite's CSS builds and bundles all CSS together into bundles and using `?url` for an import that gets bundled with other stuff isn't what you really want. `?url` is for things that aren't built/bundled.

**Comment by matthewp** [comment]
Woops, accidentally closed. We might be able to add a warning for this.

**Comment by matthewp** [comment]
Here's the upstream discussion on this in Vite, so let's track this there: https://github.com/vitejs/vite/issues/2522
