### ISSUE TITLE
Imported CSS on mdx files not applying unless a component is included

### ISSUE THREAD

**Issue by darusk** [withastro/astro#4397]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

A css stylesheet imported in an mdx file does not have the classes applied to the output unless there is also an additional component imported and rendered on the page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zaud2k?file=src/pages/index.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Confirmed I can reproduce! Submitted a fix PR above 👍
