### ISSUE TITLE
💡 RFC: `draft` support for Markdown posts

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#440]
## What is Missing from Astro Today?

- `draft` as a top-level primitive for Markdown posts/files 
- `buildOptions.drafts` as an option to ignore posts/files with `draft: true`
- borrowed from: https://jekyllrb.com/docs/configuration/options/ 

## Proposed Solution

Implement this to match Jekyll.

As a stretch goal, we could also add the `published: true/false` syntax instead. This is similar, but `draft=true` can still be built if `--drafts` is used when you build. `published=false` will never make it into your build, no matter what.

## Help Make it Happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by ewatch** [comment]
### Analysis

- This would mean markdown need to respect the format YEAR-MONTH-DAY-title.md to be not treated as drafts
- adding a command-line parameter `--drafts` where drafts would be used in dev and build mode
  - in that case modification time of the file would be used as publish date

If there's no pressure behind this I'd like to give this a try.

**Comment by FredKSchott** [comment]
@ewatch would love your help on this! 

> This would mean markdown need to respect the format YEAR-MONTH-DAY-title.md to be not treated as drafts

Not sure I follow, why wouldn't this work with a `title.md` file?

**Comment by ewatch** [comment]
@FredKSchott 
From what I've read in Jekyll there is no `published: true / false` frontmatter attribute.
So by default every file that has not a date in the filename through this convention mentioned above the file is treated as a draft. That's my understanding.
So then it the logic could be:

- date in a file => will be published
- `published: true` in frontmatter => will be published
- rest of the files would be treated as drafts

Additionally Jekyll has a hard convention that only markdown files in the `_drafts` folder a previewable.

**Comment by ewatch** [comment]
*As a note:*
The file / directory (pattern: `YEAR-MONTH-DAY-title.md` / directory `_drafts`) based approach has the benefit that within astro we could earlier decide about those files to filter them out, while when using the `published: true / false` the the filtering has to be done late after parsing the file and at least the frontmatter part.

**Comment by FredKSchott** [comment]
> From what I've read in Jekyll there is no published: true / false frontmatter attribute.

See here: https://jekyllrb.com/docs/front-matter/

> every file that has not a date

I don't think we're ready to change the filename format just yet. Because we're following file-path routing, the file path matches the final URL so we couldn't force every URL to have a date.

**Comment by ewatch** [comment]
Okay thanks. 👍 
I will start implementing it with publish and draft attribute and create a PR.
Didn't think of the routing regarding the file pattern.

**Comment by ewatch** [comment]
@FredKSchott 
I implemented a first version and will add tests now.
Are you sure that `buildOptions.draft: true` should make astro ignoring the files instead of `false` ? 😓 
Or should we name it `ignoreDrafts` ?

**Comment by tony-navillus** [comment]
For what it's worth, many CMS's I've used stick with calling it `preview` when draft updates are used.

What about `buildOptions.preview: true` to include draft files?

**Comment by FredKSchott** [comment]
- @ewatch `buildOptions.draft: true` can't this include drafts, and then have it default to false / default to ignoring drafts in the final build?
- `Astro.fetchContent()` - I think that this should respect the config value, and not return drafts unless `buildOptions.draft` is true
- @tony-navillus I have a slight preference for `draft` over `preview` since it's more explicit. I always thought that "preview" referred to letting a headless CMS frontend update for live preview while you're editing content

**Comment by jonathantneal** [comment]
Hey everyone! **This RFC is still accepted**, and it has been moved to https://github.com/withastro/rfcs/blob/main/active-rfcs/support-draft-markdown-posts.md

In an effort to improve our RFC process, we made some changes to better organize things, which include a [dedicated RFC repository](https://github.com/withastro/rfcs#readme).

**Comment by myakura** [comment]
> Hey everyone! **This RFC is still accepted**, and it has been moved to https://github.com/withastro/rfcs/blob/main/active-rfcs/support-draft-markdown-posts.md

FYI: it's moved to https://github.com/withastro/rfcs/blob/main/active-rfcs/0004-support-draft-markdown-posts.md
