### ISSUE TITLE
`define:vars` on styles don't work with dynamic tag names

### ISSUE THREAD

**Issue by aFuzzyBear** [withastro/astro#4400]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

npm

### What operating system are you using?

linux

### Describe the Bug

User had reported a strange bug with `<style define:vars />`  values are being not defined, but it is not fully applicable, it works in some places and not in others, this is a very bizarre issue that has appeared. 

For further information please view the [discord thread](https://discord.com/channels/830184174198718474/1008977537432555610)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u8rcsu?file=src/components/Another.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I think the issue here is that the styles are not defined on the element if is a variable. This is probably an issue in the runtime.

**Comment by MoustaphaDev** [comment]
I think the issue comes from the compiler. Since a dynamic tag needs to be capitalized, the parser thinks it is a normal component according to the [isComponent](https://github.com/withastro/compiler/blob/02add77888cb2748de58e52f538b0e3d892615d3/internal/parser.go#L398-L403) function definition

**Comment by natemoo-re** [comment]
This is a limitation of the way we transform `define:vars` right now. It won't work if there isn't any static HTML in the file.

The fix would be to include a wrapper element, but I also opened https://github.com/withastro/compiler/pull/612 to emit a warning from the compiler when we detect this issue.
