### ISSUE TITLE
define:vars not accessible in Safari

### ISSUE THREAD

**Issue by carstenjaksch** [withastro/astro#4401]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I set `define:vars` on a `script` tag and want to get the value inside a function. That works fine with Chrome, but not Safari.

Error in console: `ReferenceError: Can't find variable: id`

Instructions for the reproducible example:
1. Open in Gitpod
1. `cd examples/framework-svelte`
2. npm run dev
3. Make port public and click on any "Move up" button both in Chrome and Safari.
4. Developer console should return an element in Chrome and an error in Safari.

Another observation: Chrome returns the same element regardless of the clicked button. But the variables should be scoped to the respective script tag? Maybe thats the issue with Safari.

### Link to Minimal Reproducible Example

https://github.com/carstenjaksch/astro-examples

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by carstenjaksch** [comment]
Well, I fixed some JS-Code and now the correct elements will be returned in the console of Chrome. But Safari still refuses to display _something_. Now, there is no error. But instead, nothing is returned.

If you want, you could compare the latest two commits.

**Comment by carstenjaksch** [comment]
Well, forgot to clear console filters in Safari. Now all is working fine, but the console errors in commit [Add some components](https://github.com/carstenjaksch/astro-examples/commit/740a39d7d111ad020f4d156963bec9c0992dce62) still concern me.

These variables should be accessible even inside functions and the fact that it is working differently in Chrome and Safari is strange, I think.

**Comment by carstenjaksch** [comment]
Never mind, the issue fixed itself after creating this issue. 🤦‍♂️

**Comment by mikkelwf** [comment]
This is still an issue

**Comment by rhizodigital** [comment]
I can confirm this is still issue

**Comment by carstenjaksch** [comment]
I don't know if that helps you @mikkelwf @rhizodigital, but here is the commit that fixed my issue:

https://github.com/carstenjaksch/astro-examples/commit/cdf6c8102f515e9a01d690adb5a75aef6fb6a21f
