### ISSUE TITLE
Problem: Reading the configuration file data, the return will be more '/' ?

### ISSUE THREAD

**Issue by WuChenDi** [withastro/astro#4404]
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

MAC

### Describe the Bug

Hi guys, Why does environment variable fetching return more '/'?
For example, in the example I provided, I set `/astro-page-template`, but the actual return is `/astro-page-template/`

![image](https://user-images.githubusercontent.com/31385662/185771456-1b9e20e9-c4e2-4bdb-9ae9-e2a3c6cc019e.png)

### Link to Minimal Reproducible Example

https://hjfront.github.io/astro-page-template/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
This should be the configuration that you are looking for: https://docs.astro.build/en/reference/configuration-reference/#trailingslash

FYI there is a bug related to a dev & build mismatch that @matthewp is tracking down #4190 that may be related to this issue.

**Comment by WuChenDi** [comment]
@FredKSchott Thanks for your reply, I tried this configuration, but I didn't get the results I wanted.

My current problem is that when reading the `astro.config.mjs` file, the jump in the link component gives an extra `/` result, but not this.

![image](https://user-images.githubusercontent.com/31385662/185823561-51c8537a-5914-4b4d-a0ad-e5a8dc4fbe94.png)
![image](https://user-images.githubusercontent.com/31385662/185823590-b7ca078d-46d6-4cfc-9758-4caff3b6b99e.png)
![image](https://user-images.githubusercontent.com/31385662/185823703-d7de908a-b6e9-4df4-bd9b-e47837e90004.png)
![image](https://user-images.githubusercontent.com/31385662/185823628-2448bb31-6b82-409a-b53f-481c35bb52dc.png)
