### ISSUE TITLE
Image integration does not run on Stackblitz, non-node environments

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#4412]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

We've gotten many reports of the image component failing to run on `astro.new`. This prevents us from being able to add the Image component to any of our official templates where it would make sense, like the blog template.

### Link to Minimal Reproducible Example

astro.new

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
`@astrojs/image@0.8.0` added a built-in WASM-based image service, StackBlitz is now supported out of the box 🎉
