### ISSUE TITLE
Case mismatched .astro components do not hot reload when running dev server

### ISSUE THREAD

**Issue by SchmiddyFolkwang** [withastro/astro#4419]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Hey there!
Just wanted to test out Astro and found a minor bug/inconvenience.

The stackblitz link doesn't really convey the problem because it behaves a little differently than my machine.

So I started with the basic template and added tailwindcss.
Deleted pretty much all of the content from index, Layout, and threw the existing Card component out of the window.

index.astro
```
---
import Layout from '../layouts/Layout.astro';
import Card from '../components/Card.astro';
---

<Layout title="Welcome to Astro.">
	<main class="my-32 max-w-prose mx-auto">
		<h1 class="text-6xl font-bold text-center">Hello, <span class="bg-gradient-to-r from-emerald-600 to-teal-500 bg-clip-text text-transparent">Github!</span></h1>
		<Card title="Hello"/>
	</main>
</Layout>
```

I made a new card.astro component and linked it like you see in the code snippet.

Now here's the bug:
`npm run dev` starts the dev server and loads everything as it should.
But now when I make a change to card.astro, it won't get refreshed. I have to start the dev server manually again for it to work.
Notice the names: I have imported "Card.astro" but the file is called "card.astro". It doesn't hot-reload when it's lowercase, a manual reload works fine.

This problem drove me crazy until I found out that simply changing the name solves the problem.

So why raise this issue? The issue is, that there was no warning on my end (there is one in the stackblitz when you rename the card component). The console doesn't show anything, the network tab doesn't show anything, the site doesn't show anything.
It would be nice to have the cli give a warning that there is a name mismatch and that reloading might not work

That's all, thank you so much! I'm very excited to see where Astro.js is going in the future.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-m9axad?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Dmarcotrigiano** [comment]
This bug was driving me nuts, thanks for providing a solution.

**Comment by surjithctly** [comment]
I'm having the same issue, but not because of casing. I'm using tailwindcss. I have same project cloned. In one project new tailwind classes defined won't hot reload. In other it only reloads one time and no updates until we reload ourselves. 

This is some kind of wierd bug. Tried on node 18 and 17 (mac, m1). same issue.

**Comment by bluwy** [comment]
I think this needs to be fixed upstream in Vite. Closing in favour of https://github.com/vitejs/vite/issues/964

**Comment by JeffMusgrave** [comment]
For me its just flat out not hot reloading on a new install of astro + tailwind.

**Comment by Josh-Karp** [comment]
Same here. Astro + Tailwind hot releading is not working. Manually restart the dev server each time.

**Comment by sajarin** [comment]
Is there a workaround for this? This currently makes the dev experience quite annoying.

**Comment by caroguerrerosilvera** [comment]
I temporarily modified a start script in `my package.json` since the Hot Reload does not work :(

` ` ` 
 "scripts": {
    ...,
    "start": "TAILWIND_MODE=watch astro dev"
  }
` ` `

**Comment by FDiskas** [comment]
Astro does only Hot Reload - no HMR as it says in the documentation.

**Comment by Agslz** [comment]
"dev": "astro dev --port 4321" Adding the port helped me

**Comment by adonyssantos** [comment]
For me, adding the following to the `astro.config.mjs` works:

```
vite: {
    server: {
        watch: {
            usePolling: true,
        }
    }
},
```

And the `vite.config.mjs` look like this:

```js
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
    vite: {
        server: {
            watch: {
                usePolling: true,
            }
        }
    },
    integrations: [],
});
```

**Comment by piotrwydmuch** [comment]
> For me, adding the following to the `astro.config.mjs` works:
> 
> ```
> vite: {
>     server: {
>         watch: {
>             usePolling: true,
>         }
>     }
> },
> ```
> 
> And the `vite.config.mjs` look like this:
> 
> ```js
> import { defineConfig } from 'astro/config';
> 
> // https://astro.build/config
> export default defineConfig({
>     vite: {
>         server: {
>             watch: {
>                 usePolling: true,
>             }
>         }
>     },
>     integrations: [],
> });
> ```

That helped me too, thanks 👌🏼 

For me it's not the first time that HMR in Vite doesn't work for me, I found out that it's a fault of using WSL2 https://vite.dev/config/server-options.html#server-watch 

[UsePolling leads to high CPU utilization](https://github.com/paulmillr/chokidar/tree/3.6.0#performance).
