### ISSUE TITLE
Functions and objects can be passed to HTML attributes in `.astro` (and are unhelpfully stringified)

### ISSUE THREAD

**Issue by Jutanium** [withastro/astro#4424]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

In a `.astro` file, you can pass functions and objects as HTML attributes: 

```.astro
---
function myFunction() {
  return "called";
}

const myObj = { test: "hi" }
---
<button onClick={within} data-test={myObj}>Button</button>
```
But these don't get serialized properly; they get stringified. Thus, there is no use case where this would be desired.

Output:
```html
<button onclick="function myFunction() {
    return &quot;called&quot;;
  }" data-test="[object Object]">Button</button>
```

[See this Stackblitz for a more detailed demo](https://stackblitz.com/edit/github-khqxp5-7bbtv6?file=src/components/TestFuncProp.astro).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-khqxp5-7bbtv6?file=src/components/TestFuncProp.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
What is it you are expecting to happen here?

**Comment by Jutanium** [comment]
If there’s no reason for this to be supported, I’d expect the compiler to reject this or warn against it.

**Comment by matthewp** [comment]
You want this to be supported in general. JavaScript treats the `toString()` method on objects special, giving you a way to serialize objects to strings. For example:

```js
const vector = {
  points: [1, 2],
  toString() {
      return this.points.join(',')
  }
};

'' + vector; // 1,2
```

That we want to continue to support. Maybe functions are different though and we should warn there. Although you can modify a function's toString method to make it correctly serialize, so maybe even that's something we should allow.

**Comment by Jutanium** [comment]
I'll just advocate then for warning against passing functions as HTML attributes:
- Passing functions as HTML attributes happens often when learning Astro, because they try to add event handlers in their `.astro` file like they would in JSX. A warning will help put them on the right track.
- Any use case for overriding a function's `toString` method is sufficiently advanced that they can work around a warning

**Comment by tronicboy1** [comment]
I ran into the same issue of assuming that you _can_ add Event Listeners in .astro, until reading this issue!

I agree with @Jutanium I think because `.astro` syntax is very similar to React like JSX frameworks, we assume that you can add Event Listeners.

Maybe it may be nice to add this (that all objects are stringified) to the Documents for `.astro` components? Excuse me if it's already in there and I missed it.

**Comment by Princesseuh** [comment]
Nowadays, this results in a warning in both the editor and `astro check` telling you that the event expects a `string`. As Matthew said, there's real patterns where you want to support this, so any further warnings would probably results in false positives once in a while. As such, I'll be closing this issue!
