### ISSUE TITLE
@astrojs/image not processing the image from frontmatter correctly

### ISSUE THREAD

**Issue by djmtype** [withastro/astro#4440]
### What version of `astro` are you using?

1.0.7

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When referencing images from markdown's frontmatter that have been placed within `public` or `src`, the `<Image />` or `<Picture />` component doesn't render the image. However, it does process the image's `alt` info correctly. 

I would've liked to provide a Stackblitz or CodeSandBox example, but neither worked with `@astro/image` for different reasons. 

### Link to Minimal Reproducible Example

https://github.com/djmtype/Broken-Astro-Img

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@tony-sull I'm assuming we expect this to work?

**Comment by darusk** [comment]
The example repo linked to is trying to get the images from the `public` folder, which I believe is still not possible.  If the images are moved to `src/images` and the frontmatter changed accordingly, the example does seem to work—at least the main index.  I did query this in a support thread created by the OP, but did not get a response on it.

**Comment by djmtype** [comment]
For kicks tried nesting the `<Picture />` component within another Astro component. So long as the images are within `src` everything works. This issue can be closed since it's probably related to https://github.com/withastro/astro/issues/4411

**Comment by matthewp** [comment]
Thanks for the explanation, closing this now.
