### ISSUE TITLE
Upgrading @astrojs/mdx from 0.9.0 to 0.10.x breaks custom syntax highlighter that uses title metadata

### ISSUE THREAD

**Issue by eliasbrange** [withastro/astro#4447]
### What version of `astro` are you using?

1.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows (WSL 2)

### Describe the Bug

Upgrading `@astrojs/mdx` from `0.9.0` to `0.10.x` breaks the line highlighter in `rehype-pretty-code`. It uses metadata in the title such as 

```
```typescript {1, 5-6}
```

Since I do not use the built-in astro highlighter, my guess is that `rehypeRaw`, which was added as default with the same PR (https://github.com/withastro/astro/pull/4292) is causing some problems for me.

Working example (with `@astrojs/mdx 0.9.0`: https://stackblitz.com/edit/github-iyfzcn-zhr6ov

Non-working example (with `@astrojs/mdx 0.10.1`: https://stackblitz.com/edit/github-iyfzcn

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-iyfzcn

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Can you try again in `@astrojs/mdx` 0.11.x and create a new issue if it's still happening?
