### ISSUE TITLE
Bug: not supporting vue tsx 

### ISSUE THREAD

**Issue by X-Jagger** [withastro/astro#4450]
### What version of `astro` are you using?

^1.0.8

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

error： Cannot read properties of undefined (reading '0')

please check the reproducible example

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-v6q6m9?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2FCounter.tsx&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@bluwy this might be a big one so let's chat about it before you begin.

**Comment by bluwy** [comment]
Yeah this seems like a big feature request, but I can see if a `vue-jsx` integration is possible.

**Comment by bluwy** [comment]
Added support for JSX in the next minor release of `@astrojs/vue` with the `jsx: true` option. Note the supported syntax (also recommended in the Vue docs) is something like:

```jsx
export default defineComponent({
   props: {
     start: {
       type: String,
       required: true
     }
   },
   setup(props) {
     const count = ref(parseInt(props.start))
     return () => (
       <div>{count.value}</div>
     )
   },
 })
```
