### ISSUE TITLE
Lit component - using connectedCallback breaks updates

### ISSUE THREAD

**Issue by trentvb** [withastro/astro#4460]
### What version of `astro` are you using?

1.0.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I added a connectedCallback function to to the my-counter.js example:

` connectedCallback() {
    this.count = 42;
  }`

The counter failed to show the update of 42. It also broke the increment functionality moving forward.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dzjdsh-dy8mys

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You need to call `super.connectedCallback();` if you override connectedCallback.

**Comment by trentvb** [comment]
You are correct. I'm new to Lit. However, even after adding the `super.connectedCallback();`, the count isn't updated until another increment event. It appears any state change in `connectedCallback()` isn't applying.

**Comment by matthewp** [comment]
Is that the correct way to change state in a Lit component?

**Comment by trentvb** [comment]
"correct" is a loaded word for someone just trying to learn the library. I'll put it this way, when I change state there using my other build tools (Vite + Lit) it does what I expect it to.
