### ISSUE TITLE
@astrojs/vercel v1.0.1 fails to build

### ISSUE THREAD

**Issue by OllieJT** [withastro/astro#4464]
### What version of `astro` are you using?

^1.0.8

### Are you using an SSR adapter? If so, which one?

@astrojs/vercel

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Development works fine, running astro build results in an error.

Downgrading to `@astrojs/vercel@1.0.0` resolves this. Upgrading back to `@astrojs/vercel1.0.1` breaks it again.

Apologies for not adding a repro, it's 3:22 am and I will do my best to add one in the morning.

**Error**
```sh
[vite]: Rollup failed to resolve import "undefined" from "@astrojs-ssr-virtual-entry".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Full log**
```sh
❯ yarn build
yarn run v1.22.19
$ astro build
03:12:45 [build] output target: server
03:12:45 [build] deploy adapter: @astrojs/vercel/static
03:12:45 [build] Collecting build info...
03:12:45 [build] Completed in 21ms.
03:12:45 [build] Building server entrypoints...
[vite]: Rollup failed to resolve import "undefined" from "@astrojs-ssr-virtual-entry".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
 error   [vite]: Rollup failed to resolve import "undefined" from "@astrojs-ssr-virtual-entry".
  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "undefined" from "@astrojs-ssr-virtual-entry".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///Users/olliejt/Developer/+client/craft-coop/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:43721:19)
    at onwarn (file:///Users/olliejt/Developer/+client/craft-coop/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:43520:13)
    at Object.onwarn (file:///Users/olliejt/Developer/+client/craft-coop/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23178:13)
    at ModuleLoader.handleResolveId (file:///Users/olliejt/Developer/+client/craft-coop/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22335:26)
    at file:///Users/olliejt/Developer/+client/craft-coop/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22296:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Link to Minimal Reproducible Example

#

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, I'm going to take a look at this now.

**Comment by MoustaphaDev** [comment]
Looks like it's related to this commit https://github.com/withastro/astro/commit/4ac271888346c307dd361801337eade918387e89

**Comment by matthewp** [comment]
Ah, very odd, thanks @MoustaphaDev, I will revert that.

**Comment by MoustaphaDev** [comment]
No I don't think it should be reverted since it corrects a bug which was that `@astrojs/vercel/static` was importing `@astrojs/vercel/serveless`'s adapter

**Comment by matthewp** [comment]
Happy to go with another solution if there is one, but I'd rather revert something that's completely breaking the adapter vs. leaving this as is.

**Comment by MoustaphaDev** [comment]
@OllieJT should've used `@astrojs/vercel/serveless` in the first place because he's doing SSR, but the bug allowed him to do SSR with `@astrojs/vercel/static`. He should just use `@astrojs/vercel/serverless` (as the docs stated)[https://docs.astro.build/en/guides/integrations-guide/vercel/]

**Comment by matthewp** [comment]
Oh I see, this is a usage problem. Probably we should be warning about using static as an adapter.

**Comment by matthewp** [comment]
Ok, closing, @OllieJT please use `@astrojs/vercel/serverless` instead.

**Comment by OllieJT** [comment]
Thank you, we resolved this on Discord a couple of hours ago and I forgot to return here - thank you for the support!
