### ISSUE TITLE
`base` config is ignored on build

### ISSUE THREAD

**Issue by kagankan** [withastro/astro#4468]
### What version of `astro` are you using?

1.0.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Describe the Bug

after `astro build` with `base` config, fail loading image from script.
image path in the script should be `/(base)/assets/images/image.png` but it's `/assets/images/image.png`.
`base` config is ignored.

in this PR, `base: astroConfig.base,` was deleted, but this is NOT from `viteConfig`, so this line is needed
https://github.com/withastro/astro/pull/4344/files

### Link to Minimal Reproducible Example

https://github.com/kagankan/astro-sample/tree/sample/base-config-bug

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thank you!
