### ISSUE TITLE
Astro Markdown doesn't render empty alt attribute properly

### ISSUE THREAD

**Issue by marcosmartini** [withastro/astro#4470]
### What version of `astro` are you using?

1.0.8

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using the astro flavoured markdown, if you add an image and add an empty alt attribute to it, instead of rendering `<img alt="" />`, it will render with extra quotes like `<img alt="""" />`. This can be problematic for accessibility since the recommendation when rendering an image that should be ignored by screenreaders is to add `alt=""`.

Cheers,
Marcos.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uvm4y1?file=src/layouts/Layout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JuanM04** [comment]
Correct me if I'm wrong, but I think the way you write empty alt attributes is by writing nothing inside the brackets. Instead of `[""](source.png)`, it should be `[](source.png)`. I did a quick search through the Markdown spec and I didn't find any mention of `[""]` but yes about `[]` (which results in `alt=""`).

**Comment by marcosmartini** [comment]
Hey @JuanM04 thanks for the reply! If I write `[](source.png)` it returns only `alt` without the `""` – Apparently, when using a decorative image, we should be outputting [`alt=""`](https://www.w3.org/WAI/tutorials/images/decorative/)

**Comment by JuanM04** [comment]
@marcosmartini when I built the example it was there 🤔. Beware that Chrome and other browsers modify the looks of the HTML in their dev tools. Could check out the output generated by `astro build`?

**Comment by marcosmartini** [comment]
Hey @JuanM04 - thank you very much! Yes, I can confirm the output in the build file is what it should be if we use `[](source.png)`. 

Closing this one now, thank you again!
