### ISSUE TITLE
CSS for Svelte components is generated twice

### ISSUE THREAD

**Issue by Jelenkee** [withastro/astro#4476]
### What version of `astro` are you using?

1.0.9

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When i build my website the CSS for my svelte component is generated as part of the index.css and as a file for the svelte component.
I added a rollup plugin to log the bundles during build.
```
Accessing "isAsset" on files in the bundle is deprecated, please use "type === 'asset'" instead
{
  fileName: 'assets/index.4f504e74.css',
  isAsset: [Getter],
  name: 'index.css',
  source: 'div.svelte-179aisq{font-style:italic}div:where(.astro-W7ZR56CG){color:plum}',
  type: 'asset'
}
18:30:11 [build] Completed in 1.90s.

 building client 
rendering chunks (3)...Accessing "isAsset" on files in the bundle is deprecated, please use "type === 'asset'" instead
{
  fileName: 'assets/A.e0c50dda.css',
  isAsset: [Getter],
  name: 'A.css',
  source: 'div.svelte-179aisq{font-style:italic}\n',
  type: 'asset'
}
```
You can see that both assets contain CSS for `div.svelte-179aisq`. This causes a problem with [UnoCSS](https://github.com/unocss/unocss) because the latter css asset does not contain the placeholder which causes the build to fail

[Repo](https://github.com/Jelenkee/svelte-astro-bug)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-zcsve1?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
It does seem like the styles are duplicated, currently investigating this down. But my hunch fix is that we should  selectively remove css during the static build.

> This causes a problem with UnoCSS because the latter css asset does not contain the placeholder which causes the build to fail

Can you elaborate on what "placeholder" means here? It looks like `index.[hash].css` will take higher precedence over `A.[hash].css`, so it should still render fine.

**Comment by Jelenkee** [comment]
> Can you elaborate on what "placeholder" means here? It looks like `index.[hash].css` will take higher precedence over `A.[hash].css`, so it should still render fine.

[Here](https://github.com/unocss/unocss/blob/c2cdbd2fa75fb2bc21734b99805229eb7d52abb0/packages/vite/src/modes/global/build.ts#L185) you can see that some placeholders are replaced. When the placeholders are missing, the build fails (Line 197). And for this example the placholders are added to `index.123123.css` only. Not for `A.123123.css`.

I created an issue for UnoCSS too.
https://github.com/unocss/unocss/issues/1402

**Comment by bluwy** [comment]
Thanks! I've chatted with Matthew and discussed some ways to circumvent this. It also feels like the unocss one is a slightly different issue, does it happen if you use `client:only="svelte"` too? (`client:only` doesn't have duplicated css, but it has two css files). If so it'd be great if you can extend the repro to showcase it too, in case it's an astro bug.
