### ISSUE TITLE
Component hydration breaks when using `client:load="react"`

### ISSUE THREAD

**Issue by fandy** [withastro/astro#4491]
### What version of `astro` are you using?

^1.0.7

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

The TopBar component uses `window.location` to determine the active path, but that requires a check for `window` that returns `null`. This breaks HMR because the server and initial client HTML don't match.

When trying `client:load="react"` on the component, it causes a layout shift.

When using `client:load`, it breaks HMR due to unmatching HTML between client and server.

When using `client:visible`, the component doesn't display.

Live example:
https://boringordinary-astro-8yykry7z3-boringordinary.vercel.app/

### Link to Minimal Reproducible Example

https://github.com/boringordinary/boringordinary-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
What about [Astro.url](https://docs.astro.build/en/reference/api-reference/#astrourl)? You can pass this from the Astro file into the React component. `Astro.url` exists for client and server for usecases like this.

**Comment by DerYeger** [comment]
`client:load="react"` is not valid, as seen in [the docs](https://docs.astro.build/en/reference/directives-reference/#clientload).

As mentioned by @bluwy, you may use `Astro.url.pathname` to access the current path.

**Comment by cj** [comment]
@fandy I think you're looking for `client:only="react"` https://docs.astro.build/en/reference/directives-reference/#clientonly

**Comment by fandy** [comment]
Ah sorry I made a typo I am actually using `client:only="react"` and got that error.

Using @bluwy's solution of using `Astro.url` did fix the hydration issue, but then breaks on `astro build` (development works though!)

I get this error:

``` generating static routes 
▶ src/pages/index.astro
 error   Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
  Code:
      71 | b.treeContext=ib(c,1,0);try{W(a,b,d)}finally{b.treeContext=c}}else W(a,b,d);return;case Sa:c=c.type;d=Hb(c,d);Ib(a,b,c,d,f);return;case Na:f=d.children;c=c._context;d=d.value;e=c._currentValue2;c._currentValue2=d;g=D;D=d={parent:g,depth:null===g?0:g.depth+1,context:c,parentValue:e,value:d};b.context=d;W(a,b,f);a=D;if(null===a)throw Error("Tried to pop a Context at the root of the app. This is a bug in React.");d=a.parentValue;a.context._currentValue2=d===Xa?a.context._defaultValue:d;a=D=a.parent;
    > 72 | b.context=a;return;case Oa:d=d.children;d=d(c._currentValue2);W(a,b,d);return;case Ta:f=c._init;c=f(c._payload);d=Hb(c,d);Ib(a,b,c,d,void 0);return}throw Error("Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: "+((null==c?c:typeof c)+"."));}}
         |                                                                                                                                                           ^
      73 | function W(a,b,c){b.node=c;if("object"===typeof c&&null!==c){switch(c.$$typeof){case Ia:Ib(a,b,c.type,c.props,c.ref);return;case Ja:throw Error("Portals are not currently supported by the server renderer. Render them conditionally so that they only appear on the client render.");case Ta:var d=c._init;c=d(c._payload);W(a,b,c);return}if(ra(c)){Kb(a,b,c);return}null===c||"object"!==typeof c?d=null:(d=Ya&&c[Ya]||c["@@iterator"],d="function"===typeof d?d:null);if(d&&(d=d.call(c))){c=d.next();if(!c.done){var f=
      74 | [];do f.push(c.value),c=d.next();while(!c.done);Kb(a,b,f)}return}a=Object.prototype.toString.call(c);throw Error("Objects are not valid as a React child (found: "+("[object Object]"===a?"object with keys {"+Object.keys(c).join(", ")+"}":a)+"). If you meant to render a collection of children, use an array instead.");}"string"===typeof c?(d=b.blockedSegment,d.lastPushedText=Ha(b.blockedSegment.chunks,c,a.responseState,d.lastPushedText)):"number"===typeof c&&(d=b.blockedSegment,d.lastPushedText=Ha(b.blockedSegment.chunks,
      75 | ""+c,a.responseState,d.lastPushedText))}function Kb(a,b,c){for(var d=c.length,f=0;f<d;f++){var e=b.treeContext;b.treeContext=ib(e,d,f);try{Jb(a,b,c[f])}finally{b.treeContext=e}}}
    
  Stacktrace:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
    at Ib (/Users/fang/Projects/boringordinary-astro/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:72:155)
    at W (/Users/fang/Projects/boringordinary-astro/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
    at Jb (/Users/fang/Projects/boringordinary-astro/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:76:98)
    at Kb (/Users/fang/Projects/boringordinary-astro/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:75:140)
    at W (/Users/fang/Projects/boringordinary-astro/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:345)
    at Jb (/Users/fang/Projects/boringordinary-astro/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:76:98)
    at Kb (/Users/fang/Projects/boringordinary-astro/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:75:140)
    at W (/Users/fang/Projects/boringordinary-astro/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:345)
    at Jb (/Users/fang/Projects/boringordinary-astro/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:76:98)
    at Ib (/Users/fang/Projects/boringordinary-astro/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:68:145)

```

I can fix the build (but break hydration) with an SSR escape in the component:

```
  if (typeof window === "undefined") {
    return null;
  }
  ```

**Comment by bluwy** [comment]
@fandy would you be able to give a minimal repro for that error? Googling it gave me https://stackoverflow.com/questions/34130539/uncaught-error-invariant-violation-element-type-is-invalid-expected-a-string, perhaps something similar is happening on your end. Otherwise It think the original issue is resolved by using `Astro.url` to prevent hydration mismatches.

**Comment by matthewp** [comment]
@fandy Are you able to give a reproduction?

**Comment by fandy** [comment]
> @fandy would you be able to give a minimal repro for that error? Googling it gave me https://stackoverflow.com/questions/34130539/uncaught-error-invariant-violation-element-type-is-invalid-expected-a-string, perhaps something similar is happening on your end. Otherwise It think the original issue is resolved by using `Astro.url` to prevent hydration mismatches.

Yeah you're right, I tried creating a reproduction but it looks like it's an issue with Radix UI's menu component. Using Astro.url fixes the hydration issue :)
