### ISSUE TITLE
`@types/react` not included in devDependencies when doing `astro add react`

### ISSUE THREAD

**Issue by sunneydev** [withastro/astro#4506]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

wat

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Not much to say, it did not install `@types/react` and I had type errors when writing `.tsx` code.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by sunneydev** [comment]
@Princesseuh Yeah I see that, tell me if I'm wrong, but I don't believe it would be hard/problematic to implement? 
We need to check if the project is using TypeScript or not and add dependencies based on that.

I dived in the source code and couldn't figure out how the `astro add` command works entirely. The code says it just resolves from the `npmjs` and adds `peerDependencies` if it has any, but how is it figuring out to install `react-dom` then?

Anyways, I'd be happy to make a PR for this if you can point me to the right direction.

**Comment by Princesseuh** [comment]
@sunneydev For React it's pretty easy, just need to add dependencies. `astro add`'s uses the `peerDependencies` field of the integration to determine what packages to add.

The issue becomes a bit larger because for other frameworks, it's not packages you need to add but settings to `tsconfig.json`. 

Adding settings there is easy enough using a package like `comment-json`, but what do you do when someone types `astro add solid preact`? Do you add Solid's or Preact's settings? 😅

https://docs.astro.build/en/guides/typescript/#errors-typing-multiple-jsx-frameworks-at-the-same-time

**Comment by sunneydev** [comment]
> @sunneydev For React it's pretty easy, just need to add dependencies. `astro add`'s uses the `peerDependencies` field of the integration to determine what packages to add.
> 
> The issue becomes a bit larger because for other frameworks, it's not packages you need to add but settings to `tsconfig.json`.
> 
> Adding settings there is easy enough using a package like `comment-json`, but what do you do when someone types `astro add solid preact`? Do you add Solid's or Preact's settings? sweat_smile
> 
> https://docs.astro.build/en/guides/typescript/#errors-typing-multiple-jsx-frameworks-at-the-same-time

I see. I guess the problem you're trying to solve complicates getting `TypeScript` working properly for eveything, but are there really a lot of frameworks that need specific `tsconfig.json` settings? 

My point is that implementing the feature of resolving `@types` should definitely be considered, it may not work for everything, but it should work for the majority of packages? I just think it will save a lot of users from getting confused.

**Comment by Princesseuh** [comment]
> > @sunneydev For React it's pretty easy, just need to add dependencies. `astro add`'s uses the `peerDependencies` field of the integration to determine what packages to add.
> > 
> > The issue becomes a bit larger because for other frameworks, it's not packages you need to add but settings to `tsconfig.json`.
> > 
> > Adding settings there is easy enough using a package like `comment-json`, but what do you do when someone types `astro add solid preact`? Do you add Solid's or Preact's settings? sweat_smile
> > 
> > https://docs.astro.build/en/guides/typescript/#errors-typing-multiple-jsx-frameworks-at-the-same-time
> 
> I see. I guess the problem you're trying to solve complicates getting `TypeScript` working properly for eveything, but are there really a lot of frameworks that need specific `tsconfig.json` settings? 
> 
> My point is that implementing the feature of resolving `@types` should definitely be considered, it may not work for everything, but it should work for the majority of packages? I just think it will save a lot of users from getting confused.
> 
> 

`@types` works for React and Alpine. Everything else (apart from Svelte and Lit) needs `tsconfig.json` changes
