### ISSUE TITLE
@astrojs/image does not load local images in dev

### ISSUE THREAD

**Issue by panwauu** [withastro/astro#4513]
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When using build+preview the images located in src/images are loaded successfully. When using dev the images are not found.

I use the element like this:
```
<Image src={`/images/${image}`} class="banner-image" width="1024" aspectRatio="5:1" />
```

The images are located in the folder `src/images` as the `public` is not working.

It works fine for images from a remote source.

(I reproduced it in codesandbox. To test it with build/preview you can run build in a new terminal and afterwards replace `astro dev` with `astro preview` in the package.json dev entry. Then restart the codesandbox to start the preview. I was new to codesandbox, so I docuement this so I will be able to reproduce it 😉)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/magical-violet-4155dq?file=/src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by DerYeger** [comment]
You cannot load images using the `<Image>` component like this.
As seen in [the docs](https://docs.astro.build/en/guides/integrations-guide/image/#local-images), you need to `import` images using **relative** paths:

```tsx
<Image src={import('../assets/hero.png')} />
```
