### ISSUE TITLE
Importing a react-lottie component in astro gives "Error: Element type is invalid"

### ISSUE THREAD

**Issue by sellingsolutions** [withastro/astro#4516]
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If you open up my stackblitz link and run `npm run build` you should get a build error with the mesage `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

I'm using a named export like so: `export const LottieAnimation = (props: LottieAnimationProps) => { ... `. I would expect a named export function to not be interpreted as an object. Any ideas as to what I'm doing wrong here?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-f2m6up?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by DerYeger** [comment]
Hi, if you add `console.log(LottieAnimation)` to your `index.astro`, you will see that the component function is imported as expected.

Does lottie-react support SSR?

I noticed that you used `client.load` (which should be `client:load`), so the animation component is rendered at build time.
If lottie-react does not support SSR, you can get it to work by using `client:only="react"` instead, which actually works with the StackBlitz you provided.

**Comment by DerYeger** [comment]
Interestingly, using lottie-react's `useLottie` hook works fine even with `client:load`.
However, it's still affected by https://github.com/withastro/astro/issues/4220, unless you're using `export default function`.

**Comment by sellingsolutions** [comment]
> Interestingly, using lottie-react's `useLottie` hook works fine even with `client:load`. However, it's still affected by #4220, unless you're using `export default function`.

@DerYeger Thank you!! I added your changes to my stackblitz link and it works like a charm
