### ISSUE TITLE
Typescript does not build

### ISSUE THREAD

**Issue by sidvenu** [withastro/astro#4518]
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

`tsc --noEmit`, as suggested by https://docs.astro.build/en/guides/typescript/#type-checking to be used, throws the following error:

    ❯ npm run build
    $ astro check && tsc --noEmit && astro build
    astro check
    ✔  Getting diagnostics for Astro files in /home/projects/github-gmjytu/…
    Result (3 files): 
    - 0 errors
    - 0 warnings
    - 0 hints
    
    node_modules/astro/config.d.ts:2:31 - error TS2307: Cannot find module './dist/types/@types/astro' or its corresponding type declarations.
    
    2 type AstroUserConfig = import('./dist/types/@types/astro').AstroUserConfig;
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    
    Found 1 error in node_modules/astro/config.d.ts:2

I found that this is because the `dist` folder directly has `@types` folder, so the fix should be:
`type AstroUserConfig = import('./dist/@types/astro').AstroUserConfig;`
or to investigate if the expected `dist` structure was to have a `types` subfolder within which we should have `@types` folder.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gmjytu

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Fixed in https://github.com/withastro/astro/pull/4524
