### ISSUE TITLE
Unable to import built CSS as a file reference

### ISSUE THREAD

**Issue by JamesAlexanderHill** [withastro/astro#4521]
### What version of `astro` are you using?

1.0.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I want to lazy import a css file and need a reference to the built CSS. (I am using the tailwind integration but this isnt specific to tailwind)

Currently I can get the css as text, base64 or an unbuilt file (so it only contains the tailwind directives not the built code).

I need a reference to the build file so that I can import it via html myself.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lrl1vc?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hi @JamesAlexanderHill, this is not currently possible. All CSS that gets built and bundled by Astro is also inserted by Astro. There's not an ability to customize how it is inserted.

If you'd like to see such a feature I recommend starting an RFC discussion where we can talk about the problem and figure out a solution together: https://github.com/withastro/rfcs/discussions

In the meantime, if you really need this, you can create a Vite plugin to give yourself more control. Such a plugin might use a special query param like the one you showed in your example, but then build + bundle the file. This would be a bit advanced but it's possible.
