### ISSUE TITLE
CORS Error When Adding A Paperform Script

### ISSUE THREAD

**Issue by WallaceSociety** [withastro/astro#4532]
### What version of `astro` are you using?

1.01

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows  - WSL

### Describe the Bug

Probably not the best title, but as I'm not really sure what's happening under the hood I figured I'll start with the output and then can rename it to the specific problem later. 

**Desired Outcome:**
Display an embedded paperform on an HTML page

**Current Results:**
CORS error from embed script

**Steps to Reproduce:**
npm create astro@latest paperformIssue
( install empty project )
Add following code to body of index.astro and run dev or build
```
<div data-paperform-id="ztxmmoot"></div>
<script src="https://paperform.co/__embed.min.js"></script>
```

**My Notes**
As I mentioned I'm not quite sure what is happening, but it looks like the script is somehow getting repackaged as a hoisted.js and something is being changed in the request headers. 

**Workaround**
Omit the `<script src="https://paperform.co/__embed.min.js"></script>` tag and add it just before the body of the compiled HTML.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cmn6bo?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @WallaceSociety, regular scripts get compiled into modules and that's why you're seeing a CORS error here. You want to use `<script is:inline src="https://paperform.co/__embed.min.js"></script>` instead.

See https://docs.astro.build/en/reference/directives-reference/#isinline

**Comment by WallaceSociety** [comment]
That makes sense. Thank you.
