### ISSUE TITLE
Accented characters in markdown frontmatter get mangled when imported

### ISSUE THREAD

**Issue by velvetkevorkian** [withastro/astro#4538]
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Ubuntu 16.04 in WSL2

### Describe the Bug

Accented characters in Markdown frontmatter get mangled in some cases. For example, this markdown file renders correctly as `àáâäå`
```
// pages/example.md
---
title: àáâäå
---
àáâäå
```
 but when we import it into an `.astro` template 
```
// pages/index.astro
---
import * as example from './example.md'

const {title} = example.frontmatter
---

{title}
```
`title` renders as `Ã Ã¡Ã¢Ã¤Ã¥`.

Doing this in the layout seems to work correctly:
```
// layouts/Layout.astro
---
const { title } = Astro.props.frontmatter || Astro.props;
---
[snip]
<h1>{title}</h1>
[snip]
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jrzskb-zha5gx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
This seems like an issue with `gray-matter`, I'm gonna investigate if someone isn't faster than me

**Comment by MoustaphaDev** [comment]
You need to set the encoding of your html document with `<meta charset="UTF-8" />` on the head of the index page
Learn more on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset)

**Comment by velvetkevorkian** [comment]
Oh good spot, that does seem to correct the issue. I feel like there is still something funny going on, as if you take out the charset tag the encoding is not consistent between pages, but shouldn't really be a problem in most cases. Thanks.

**Comment by matthewp** [comment]
See that this has been resolved, closing!
