### ISSUE TITLE
Sitemap integration missing trailing slashes

### ISSUE THREAD

**Issue by moritzlaube** [withastro/astro#4539]
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Not sure, if it is a bug or a config issue: When using the sitemap integration, up until now the URL-paths were exported with a trailing slash like `https://my-domain.com/page/`. But when I just rebuilt my page with updated Astro and sitemap integration, the sitemaps are missing the trailing slash (`https://my-domain.com/page`).

Is this intended? If it is, is there a possibility to add a config option to add or remove trailing slashes? 

I've added an example on Stackblitz. Just have a look into the dist folder. 

Thanks!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kqyvbr?file=dist/sitemap-0.xml

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kevinzunigacuellar** [comment]
a config option `trailingSlash?: boolean` would be awesome!

**Comment by matthewp** [comment]
Thanks!
