### ISSUE TITLE
canonicalUrl doesn't match in dev and prod

### ISSUE THREAD

**Issue by kevinzunigacuellar** [withastro/astro#4547]
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When making a canonical URL:
```js
const canonicalURL = new URL(Astro.url.pathname, Astro.site);
```

**dev server** will output a URL without a trailing slash
```html
<link rel="canonical" href="https://example.com/blog">
```

while **build** will generate a URL with trailing slash
```html
<link rel="canonical" href="https://example.com/blog/">
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-s2tqe2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
This is expected. In dev mode the url trailing slash handling is forgiving [by default](https://docs.astro.build/en/reference/configuration-reference/#trailingslash). However, at build time trailing slashes are added [by default](https://docs.astro.build/en/reference/configuration-reference/#buildformat)

**Comment by kevinzunigacuellar** [comment]
I see I was expecting both dev and prod to match. Also, I just realized that the Astro.url already contains the pathname and the site so the canonical URL can be written as

```js
const canonicalUrl = new URL(Astro.url).href
```

or even just

```html
<link rel="canonical" href={Astro.url} />
```

Thank you I am not quite sure if this is an issue now 😅 but I think it would be a better DX to match outputs both in dev and prod. Feel free to close this issue.

**Comment by bluwy** [comment]
I think this is expected at the meantime as showed by @MoustaphaDev. For context, this change was made in https://github.com/withastro/astro/pull/4352, and the reason it's not made consistent in dev is to prevent a breaking change. It's certainly something we can align in the future, but for now it's something to keep in mind. Closing the issue for now.
