### ISSUE TITLE
ApolloClient cant fetch data

### ISSUE THREAD

**Issue by odwrotnie** [withastro/astro#4550]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have followed simple steps from https://www.apollographql.com/docs/react/get-started:

```js
import {
	ApolloClient,
	ApolloProvider,
	gql,
	InMemoryCache,
	useQuery
} from "@apollo/client";

const client = new ApolloClient({
	uri: 'https://flyby-gateway.herokuapp.com/',
	cache: new InMemoryCache(),
});

const GET_LOCATIONS = gql`
	query GetLocations {
	  locations {
		id
		name
		description
		photo
	  }
	}
  `;


function DisplayLocations() {
	const { loading, error, data } = useQuery(GET_LOCATIONS);

	if (loading) return <p>Loading...</p>;
	if (error) return <p>Error :(</p>;

	return data.locations.map(({ id, name, description, photo }) => (
		<div key={id}>
			<h3>{name}</h3>
			<img width="400" height="250" alt="location-reference" src={`${photo}`} />
			<br />
			<b>About this location:</b>
			<p>{description}</p>
			<br />
		</div>
	));
}

function Locations() {
	return <ApolloProvider client={client}>
		<div>
			<h2>My first Apollo app 🚀</h2>
			<br />
			<DisplayLocations />
		</div>
	</ApolloProvider>
}

export default Locations;
```

and after running I got `Loading...` while on raw React project the behaviour is as expected - it shows the result.

### Link to Minimal Reproducible Example

https://github.com/instap-app/astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Astro doesn't ship javascript by default, so you need to use `client:*` directives to make your components interactive
You can learn more here  https://docs.astro.build/en/reference/directives-reference/#client-directives

**Comment by odwrotnie** [comment]
It works!
