### ISSUE TITLE
server error on unhandled routes with no way to actually handle them

### ISSUE THREAD

**Issue by jazoom** [withastro/astro#4561]
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

I'm setting up an API in `/pages/api`

I have a catch-all route at `/pages/api/[...404].ts` with content:

```
import type { APIRoute } from "astro";

export const get: APIRoute = ({ params, request }) => {
  return {
    body: "get404",
  };
};

export const post: APIRoute = ({ params, request }) => {
  return {
    body: "post404",
  };
};
```

As far as I can tell, there's no way to have an `any` route, for example:

```
import type { APIRoute } from "astro";

export const any: APIRoute = ({ params, request }) => {
  return {
    body: "404",
  };
};
```

This is a minor annoyance (since I have to make an export for every possible HTTP method) but the real problem is I have to do the same thing for each and every other route, and if I don't it ends up as an internal server error if someone/something calls an unsupported method.

Here's what I mean. Suppose there's the following route at `/pages/api/healthCheck.js`
```
import type { APIRoute } from "astro";

export const get: APIRoute = ({ params, request }) => {
  return {
    body: "ok",
  };
};
```

Now if you make a POST request to `/api/healthCheck` you will cause a server error, but if you make a POST request to some garbage URL, for example `/api/thisdoesntexist` you will get a nice 404 response.

Maybe I'm missing something, but I think I've read all of your documentation and have seen no way to handle this properly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jhuzfh-vlbzls

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jazoom** [comment]
Possibly the best way to handle this is making unimplemented methods fall through to the catch-all route since there was no handler defined in the file with the higher specificity filename?

**Comment by matthewp** [comment]
I think I understand what you mean. You are expecting `POST /api/healthCheck` to be picked up by the 404 handler. That does make sense to me. I'll look into this.

**Comment by jazoom** [comment]
> I think I understand what you mean. You are expecting `POST /api/healthCheck` to be picked up by the 404 handler. That does make sense to me. I'll look into this.

Yep pretty much. I'd expect a 404 handler that can handle ALL requests that don't match another route.

**Comment by jazoom** [comment]
As I noted in my comment in #4594, I think serving a full 404 HTML page is not the appropriate way to handle this (imagine calling the incorrect URL in the terminal, or doing some console debug logging and printing the response). I'd like a simple way to, for example, return a text response such as "API route not implemented".

**Comment by matthewp** [comment]
@jazoom Since you control the 404 page you are able to respond with a simpler response if you want:

```astro
---
if(Astro.url.pathname === '/api/healthCheck') {
  return new Response('Wrong http method: ' + Astro.request.method, {
    status: 404
  });
}
---
```

**Comment by jazoom** [comment]
But then we're back to the problem of having to add a special handler for every single route.

**Comment by jazoom** [comment]
@matthewp I tried doing this as a catch-all for API calls as you suggested:
```
if (Astro.url.pathname.startsWith("/api/")) {
  return new Response("route not found", {
    status: 404,
  });
}
```
But that didn't work for unsupported methods of routes that exist because it seems you're changing the pathname to "/404". For example, in the case of GET "/api/healthCheck" (which exists), calling POST "/api/healthCheck" will fall through to the full 404 page because Astro rewrites the URL in that case to "/404", but Astro does not do the same thing for a route that does not exist for any method. For example, both GET "/api/h" and POST "/api/h" keep their pathname and the correct 404 response is returned. It's inconsistent.

For now I'm working around the issue like this:
```
if (Astro.url.pathname.startsWith("/api/") || Astro.url.pathname === "/404") {
  return new Response("route not found", {
    status: 404,
  });
}
```
