### ISSUE TITLE
CSS fallback not working

### ISSUE THREAD

**Issue by wattanakorn495** [withastro/astro#4563]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I try to set height of the div with css class below
```
<div class="app app-webkit app-moz">
	<Live client:load /> //solid app
</div>
```
these classes do not work, it seem like astro ignore app-webkit and app-moz
```
.app {
	height: calc(100vh - 42px);
}
.app-webkit {
	height: -webkit-calc(100vh - 42px);
}
.app-moz {
	height: -moz-calc(100vh - 42px);
}
```

i also try this class but it does not work
```
.app {
        height: calc(100vh - 42px);
        height: -webkit-calc(100vh - 42px);
        height: -moz-calc(100vh - 42px);
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bbt4mb?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Seems to look right to me, what am I missing?

__Firefox__

<img width="989" alt="Firefox" src="https://user-images.githubusercontent.com/361671/187964343-8fdeae1e-3c2d-4c9e-b9ac-2551213c303e.png">

__Safari__

<img width="977" alt="Safari" src="https://user-images.githubusercontent.com/361671/187964425-a93679af-ef70-498a-8e18-3fe3b784e323.png">

**Comment by matthewp** [comment]
Closing as I don't see an issue. Let me know if I've missed something.
