### ISSUE TITLE
Client-side JS in unused Astro components

### ISSUE THREAD

**Issue by smth** [withastro/astro#4564]
### What version of `astro` are you using?

1.1.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If you import an Astro component, but due to some logic in the template, do not use it, the client-side JS from that component is still included. For example you have a template building pages from a CMS, this page may or may not contain images, if it does contain images you want to include a gallery component. If the gallery HTML is not added to the page the JS still is.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qjwkgn?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is how hoisted scripts work, they get hoisted to the `<head>`. If we waited until we knew they were going to be used then they would not be in the head and would be somewhere in the body. So this is a known limitation, you can use `<script is:inline>` for truly dynamic scripts.
