### ISSUE TITLE
@astro/image errors "require is not defined" in local development

### ISSUE THREAD

**Issue by joe-bell** [withastro/astro#4568]
### What version of `astro` are you using?

1.1.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Hey friends! Appreciate the work you're doing at Astro – I've been having a blast using it for the last few days

I've been recently building an Astro example for plaiceholder, but stumbled across an issue when trying to use `@astro/image`:
https://github.com/joe-bell/plaiceholder/pull/218

When visiting any of these newly added pages locally in `astro dev`, I see:

```sh
 error   require is not defined
ReferenceError: require is not defined
    at /.../plaiceholder/node_modules/.pnpm/tiny-glob@0.2.9/node_modules/tiny-glob/index.js:1:25
    at instantiateModule (file:///.../plaiceholder/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:50548:15)
```

This issue only seems to happen within my local environment, **not** in Vercel. 

Some other details that might help to diagnose:
- Node version: `16.15.1`
- `.npmrc` contents (I don't want to hoist all within my monorepo)
    ```
    public-hoist-pattern[]='astro'
    public-hoist-pattern[]='@astrojs/*'
    ```

I'd love to have this example as a "gold standard" Astro site, so I'd really appreciate any help to investigate :pra

### Link to Minimal Reproducible Example

https://github.com/joe-bell/plaiceholder/pull/218

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks! I'll take a look at this.

**Comment by matthewp** [comment]
@tony-sull, setting `image-size` and `tiny-glob` to `external` fixes this problem. Should the integration be configuring this?

**Comment by matthewp** [comment]
@joe-bell in the meantime you can set these as external in your own config which seemed to resolve it in my testing:

```js
export default defineConfig({
  vite: {
    ssr: {
      external: ['image-size', 'tiny-glob']
    }
  }
});
```

**Comment by joe-bell** [comment]
@matthewp that works a charm in the meantime, thank you!

**Comment by matthewp** [comment]
Ah, yes, anything that is external needs to be hoisted. I don't know if your monorepo setup allows hoisted all of that example project or not, if so that would avoid needing to individually hoist external packages.

**Comment by matthewp** [comment]
Can confirm that this is because of hoisting. Due to how Vite works when compiling code, it winds up `import()`ing it for you. Which means it has to be a dependency of the thing doing the import, or a parent. Hoisting works around this issue.

Other Vite-based frameworks have the same problem, see for example: https://github.com/nuxt/vite/issues/91

So closing as there's not really anything we can do here until the underlying problem is resolved in Vite.

**Comment by joe-bell** [comment]
Thanks @matthewp!

**Comment by Adam-Collier** [comment]
Just ran into this problem myself! Any chance we could get a note added to the documentation about this? Save people having to search the issues
