### ISSUE TITLE
Lit component loses it's property state

### ISSUE THREAD

**Issue by vlyamzin** [withastro/astro#4569]
### What version of `astro` are you using?

1.1.2

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Lit component loses a property state when provided from the outside. The initial state is being rendered correctly though.

Compare pure Lit solution on [stackblitz](https://stackblitz.com/edit/typescript-litelement-example-duayw2) with Astro framework Lit example [here](https://stackblitz.com/edit/github-gar9g1)

In the first example, the counter is incremented. The second example returns `NaN`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gar9g1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I'm not able to recreate after a bunch of testing. It seems that `@property` is a problem and doesn't jive with class properties. This docs talks about that: https://lit.dev/docs/components/properties/#avoiding-issues-with-class-fields

I did notice that using the `static properties` and setting `reflect: true` it does work.
