### ISSUE TITLE
Dynamic components break with client:* directive

### ISSUE THREAD

**Issue by dolbex** [withastro/astro#4573]
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When referencing dynamic components the application bombs when trying to use client:* directives.

This works fine:

```
---
import TestComponentOne from "src/slices/PiniaTest.vue";
import TestComponentTwo from "src/slices/CircleSlideshow.vue";
import BlueLayout from "../layouts/BlueLayout.astro";

const components = [TestComponentOne, TestComponentTwo];
---

<BlueLayout>
  {components.map((Component) => <Component />)}
</BlueLayout>
```
but this does not:
```
---
import TestComponentOne from "src/slices/PiniaTest.vue";
import TestComponentTwo from "src/slices/CircleSlideshow.vue";
import BlueLayout from "../layouts/BlueLayout.astro";

const components = [TestComponentOne, TestComponentTwo];
---

<BlueLayout>
  {components.map((Component) => <Component client:visible />)}
</BlueLayout>
```

Notice the ```client:visible``` on the component. It generates the following error: ```Component is not defined```

**Update**: Simple reproduction

```
---
import TestComponentOne from "src/slices/PiniaTest.vue";
const TestAlias = TestComponentOne;
---
<TestAlias client:load />
```

Fails the same way

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rj87rn?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
We discussed this on Discord, it's a technical limitation of how Astro works. See https://discord.com/channels/830184174198718474/983479293319450624/1014575218024534147
