### ISSUE TITLE
Custom scoped CSS namespace ignores CSS in older browsers

### ISSUE THREAD

**Issue by markpinero** [withastro/astro#4580]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Regarding the [scoped CSS proposal](https://github.com/withastro/rfcs/blob/main/proposals/0012-scoped-css-with-preserved-specificity.md), it's described that the drawbacks are "legacy browsers" but doesn't take into account that `:where` has only been available on browsers for only 2 years.

> Chrome: 2021-01-18
> Edge: 2021-01-22
> Safari: 2020-09-15
> Firefox: 2020-06-29

Source: https://caniuse.com/mdn-css_selectors_where

Compared to the previous implementation, there were obvious side effects with specificity but with the `:where` implementation, the scoped CSS is **completely ignored** on these unsupported browsers and not sure if this can be considered a worthwhile tradeoff.

## Unsupported
![Screen Shot 2022-08-31 at 2 06 58 PM](https://user-images.githubusercontent.com/1432193/187782792-80761116-ebc0-4927-ac0a-a90037a199c6.png)

## Supported
![Screen Shot 2022-08-31 at 2 07 08 PM](https://user-images.githubusercontent.com/1432193/187782841-f44cc07b-55c2-49b5-892d-fced9cb72e7d.png)

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks for bringing our attention to this. We made the decision to switch to using `:where` in an [RFC](https://github.com/withastro/rfcs/blob/main/proposals/0012-scoped-css-with-preserved-specificity.md) several months ago and switching before 1.0. Switching again would be a major breaking change and could not happen before 2.0.

If we're going to make such a large change it's going to have to go through the RFC process, so I would direct you towards [our RFC discussions](https://github.com/withastro/rfcs/discussions) if this is a change you feel strongly about. 

Going to close as there's no actionable change we can make for this at this time.

**Comment by andersk** [comment]
RFC discussion:

- https://github.com/withastro/rfcs/discussions/371
