### ISSUE TITLE
Console warning when using `<script>` with an expression in the `src` attribute

### ISSUE THREAD

**Issue by jon301** [withastro/astro#4583]
### What version of `astro` are you using?

1.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Given the following `.astro` file:

```
---
const myApiKey = 'my_api_key';
---
<html lang="en">
	<body>
		<script src={`https://maps.googleapis.com/maps/api/js?key=${myApiKey}&v=weekly`}></script>
	</body>
</html>
```

I get the following warning in the console:

```
src/pages/index.astro: <script> uses the expression {`https://maps.googleapis.com/maps/api/js?key=${myApiKey}&v=weekly`} on the src attribute and will be ignored. Use a string literal on the src attribute instead.
```

Note: This warning does not appear in the stackblitz repro below ... It only appears locally, not sure why >_<

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zz8fkr-pepcpw?file=src%2Fpages%2Findex.astro

**Comment by matthewp** [comment]
Hey @jon301, you want to use `<script is:inline src={...}>` which creates a regular script tag. Without the `is:inline` we try to bundle everything and can't do so for dynamic expressions (that's why you get the warning).
