### ISSUE TITLE
Solid components using an HTML table won't hydrate

### ISSUE THREAD

**Issue by kollinmurphy** [withastro/astro#4602]
### What version of `astro` are you using?

1.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When a Solid component is rendered inside of an HTML table tag, or when a Solid component renders an HTML table tag, that component won't hydrate at all.

### Link to Minimal Reproducible Example

https://github.com/kollinmurphy/astro-table-hydrating-bug-report

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JohnDaly** [comment]
For the case of the `Table.tsx` component, you get the following error:

```
(index):13 Uncaught (in promise) The browser resolved template HTML does not match JSX input:
<table><tbody><tr><td>I render but I don't hydrate</td></tr></tbody></table>

<table><tr><td>I render but I don't hydrate</td></tr></table>. Is your HTML properly formed?
```

Updating the `Table.tsx` component like this will fix the problem:
```tsx
/* @jsxImportSource solid-js */

import { createEffect } from 'solid-js';

const TableRow = () => {
  createEffect(() => {
    console.alert("I'm hydrated now");
  });

  return (
    <table>
      <tbody>
        <tr>
          <td>I render and hydrate now</td>
        </tr>
      </tbody>
    </table>
  );
};

export default TableRow;
```

**Comment by matthewp** [comment]
A table row not hydrating is kind of expected, it's a limitation of how islands work as we have to create a wrapping element to do hydration.

The full table is a bit unexpected though. Can you create a Stackblitz that shows the problem?

**Comment by kollinmurphy** [comment]
I didn't get that same error saying "The browser resolved template HTML does not match JSX input". But when I added the tbody tag it did work. Thanks!

Here's a Stackblitz with two tables, one with a tbody and and the other without one.

https://stackblitz.com/edit/withastro-astro-bbsjwn?file=src/pages/withTbody.astro

**Comment by matthewp** [comment]
Yep, tbody is required as well. Thanks for the sample but since this is a known limitation there's nothing we can do.
