### ISSUE TITLE
Dynamically imported CSS fails in production build (React, CSS Modules)

### ISSUE THREAD

**Issue by agundermann** [withastro/astro#4613]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

In the example I used React lazy + Suspense for code splitting, and CSS modules for styles, but I think this could also affect other UI libraries + CSS generators.

In build/preview mode the browser shows the error

```
Unable to preload CSS for ...
```

No issues in development mode.

Seems to be a regression from https://github.com/withastro/astro/commit/9ad307a9fca064dcd9b2f27c3243d09d9154a5dc , since it works with earlier versions, but with duplicated CSS.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kjcsh4

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Think I have a fix for this.

**Comment by agundermann** [comment]
Thanks @matthewp !
