### ISSUE TITLE
Preserving `meta` field of Astro MDX code block

### ISSUE THREAD

**Issue by pinanek23** [withastro/astro#4616]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I try to use a custom syntax highlighter with `markdown.syntaxHighlight = false`. The official MDX documentation suggests that [markdown supports a meta string for code](https://mdxjs.com/guides/syntax-highlighting/#syntax-highlighting-with-the-meta-field). However, it seems like Astro doesn't preserve the `meta` field. 

````md
```astro title="hello"
---
const weSupportAstro = true;
---

<h1>Hey, what theme is that? Looks nice!</h1>
```
````

```js
function rehypeMeta() {
  return function transformer(tree) {
    visit(tree, 'element', (node) => {
      if (node.tagName === 'code') {
        console.log(node.data.meta);
      }
    });
  };
}
```

The `meta` field is undefined.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-benngb?file=rehype-meta.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
@pinanek23 @matthewp  I just realized that this is not a bug. While implementing the plugin in the PR, I had the meta field already. Then I saw that @pinanek23 is using rehype instead of actually using remark for custom syntax highlighting. @pinanek23 Here's the code that shall work as expected: https://github.com/rishi-raj-jain/issue-meta-field-mdx.

**Comment by matthewp** [comment]
Thank you @rishi-raj-jain!

**Comment by pinanek23** [comment]
Thank you @rishi-raj-jain, I switched to remark. But I think someone (like me 😄) will go though the MDX docs and try rehype instead of remark (as MDX docs suggests writing a rehype plugin for custom syntax highlighting)
