### ISSUE TITLE
failed to load module for ssr

### ISSUE THREAD

**Issue by lppoi** [withastro/astro#4624]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

windows

### Describe the Bug

![image](https://user-images.githubusercontent.com/64509267/188405442-21a1c25d-bb3a-4a29-a305-bec8ad3f59f7.png)

When a new project(blog template) is running, pnpm run dev reports an error.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I think this is Vite bug, if you can provide a repro it would be appreciated to report this at https://github.com/vitejs/vite ! I saw some reports of this vague error before but can't reproduce it. Closing this one for now.
