### ISSUE TITLE
@astrojs/solid-js style object undefined keys reach DOM style attribute

### ISSUE THREAD

**Issue by toonddd** [withastro/astro#4627]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Solid components, rendered through Astro with `@astrojs/solid-js`, result in style properties that are explicitly set to undefined to propagate to the DOM.

This deviates from the expected behavior when using plain Vite to build a SPA with the same components.
There they do not show up as a literal `"undefined"` in the DOM's style attribute string.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cwxcij?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Is this a bug in Astro or in Solid itself? It feels like the latter.

**Comment by toonddd** [comment]
Will investigate this further. Will get back to you asap. I agree it does look like a Solid SSR issue at first glance.

**Comment by toonddd** [comment]
I have created a different bug report on the relevant repository.
