### ISSUE TITLE
Odd error message during development:"Internal Warning: route cache overwritten"

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#4633]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

As I was developing on astro.build, I saw this warning message every time I changed and saved an MDX blog file:

<img width="895" alt="Screen Shot 2022-09-05 at 10 15 39 PM" src="https://user-images.githubusercontent.com/622227/188557310-68404ae0-2244-4270-8564-394924d6d372.png">

### Link to Minimal Reproducible Example

https://github.com/withastro/www-2

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by soongsta** [comment]
same

**Comment by deeprobin** [comment]
I can confirm.

```
14:15:22 [routeCache] Internal Warning: route cache overwritten. (src/pages/[language]/index.astro)
```
