### ISSUE TITLE
Misleading "Unable to render Content" warning on MDX error

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#4634]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

If I went into an MDX file and removed an import accidentally, I saw this error message. This message made no sense since there was no `Content` component or variable defined, and it didn't tell me the file name either.

If I started the dev server with this missing import, the dev server crashed and failed to startup.

<img width="915" alt="Screen Shot 2022-09-05 at 11 17 05 AM" src="https://user-images.githubusercontent.com/622227/188557516-e5b48292-89cf-43c7-8faf-86dee7420d91.png">

```
 error   Unable to render Content!
  
  There is 1 renderer configured in your `astro.config.mjs` file,
  but it was not able to server-side render Content.
  
  Did you mean to enable `@astrojs/react`, `@astrojs/preact`, `@astrojs/vue` or `@astrojs/svelte`?
```

### Link to Minimal Reproducible Example

https://github.com/withastro/www-2 (start up the dev server, then remove any import from a blog mdx file)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lasfito** [comment]
Encountered the same Issue while deploying to CloudFlare
