### ISSUE TITLE
 Inconsistency between dev and build with trailing slash 

### ISSUE THREAD

**Issue by AidanNichol** [withastro/astro#4638]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

working with astro 1.1.5
```
let pathname = new URL(Astro.request.url).pathname;
```
with _astro dev_ this doesn't return a trailing '/' whereas _astro build_ does.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rc3xnz?file=src%2Fpages%2Findex.astro,src%2Fpages%2Fbug.astro,package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You want to use `trailingSlash: never` in order to control trailing slash behavior. By default it is set to `ignore` which means it will accept both in dev mode. In the build it can obviously only be one of the two and it defaults to including the trailing slash when using `build.format = 'directory'`.

**Comment by fabien** [comment]
@matthewp I ran into this issue as well. Adding `trailingSlash: never` to my config did not help, the trailing slash was still there.

**Comment by underblob** [comment]
I think this is not obvious to the uninitiated. I spent longer than I would have liked trying to figure it out. When trying to identify the current page from the `Astro.glob` collection, I thought it was an `Astro.glob` behavior issue for a long time until I printed `Astro.url.pathname` to the render in both development and production and saw the trailing slash. It would be friendlier if the default behaviors across dev/build were consistent.

**Comment by tylerwray** [comment]
I would love to re-open this issue and work on it.

The issue I'm having is that for a production build there is no way to have `Astro.url` remove the trailing slash.

I'm doing this regex workaround now to conditionally remove a trailing slash

```js
const pathname = Astro.url.pathname.replace(/\/$/, "")
```

It would be great if there was a way to make production builds not include trailing slashes if that's someone's preference.
