### ISSUE TITLE
Passing React children from Astro component doesn't work with client:load

### ISSUE THREAD

**Issue by jkjustjoshing** [withastro/astro#4640]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Stackblitz

### Describe the Bug

I'm able to pass children into a React component from an Astro component:
```jsx
<MyReactComponent>
  <div>From Astro</div>
</MyReactComponent>
```

When I set `client:load` on the React component, the component SSG renders correctly, but in the browser the `children` prop is empty/undefined:
```jsx
<MyReactComponent client:load>
  <div>From Astro</div>
</MyReactComponent>
```
<img width="641" alt="image" src="https://user-images.githubusercontent.com/813192/188660292-ea20b32e-7ada-4aa0-8207-3b302e8e9607.png">

## Expected behavior
The same value passed to the React component when rendering in Node should be passed to the React component in the browser.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mwmoww-fx99q4

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You can't put a div inside of a p. That's what's causing your server/client mismatch. Working version removing the p and using div instead: https://stackblitz.com/edit/github-mwmoww-nxfbqj?file=src%2Fpages%2Findex.astro
