### ISSUE TITLE
I can use imported static files in HTML but I can't use them in the client-side script tags

### ISSUE THREAD

**Issue by hsensh** [withastro/astro#4650]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I really don't know if it's a bug or if this is a way things are intended, but suppose I am using Alpine, and I want to fetch data X and pass it on to script tag so it can process them. It just says that X is not defined. How would I replicate this behavior while sticking to Alpine, because I have the flexibility to pass it on as a component prop when using Vue or React but not Alpine.

Note: I have Alpine installed manually and not through the adapter as I need to extend Alpine behavior.

### Link to Minimal Reproducible Example

Don't believe it needs reproduction

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You can pass data into script tags using `define:vars`: https://docs.astro.build/en/reference/directives-reference/#definevars

For support questions the best place to go is our discord: https://discord.com/channels/830184174198718474/845451724738265138
