### ISSUE TITLE
BUG: TailwindCSS + Svelte: Hot Reload shows erratic behavior

### ISSUE THREAD

**Issue by SMEETT** [withastro/astro#4651]
### What version of `astro` are you using?

v1.1.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Win 11 Enterprise (10.0.22000 Build 22000)

### Tailwind Classes added to HTML-Elements are being ignored or are applied erratically (once Svelte is integrated)

Here are a few things I observed (I used an `H1` with the class `text-*xl` in both, a Svelte component and `.astro` page):

1. When changing `text-*xl` and going up in sizes, it often works for `text-2xl`, `text-3xl` etc. and up to `text-5xl`, then it stops working and jumps back to no styling (even though we now have something like `text-6xl` applied.)
2. Problem seems to be related to the Svelte integration. When Svelte is integrated `.astro` files show an erratic behavior too.
3. Restarting the dev-server "fixes" the problem (e.g classes are applied as they should).
4. When a class was added successfully once (by restarting the dev-server) it seems to work after that. 

Thanks for reading!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xtuihr?file=src%2Fpages%2Findex.astro,src%2FTest.svelte&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SMEETT** [comment]
I automated the process of restarting the dev-server after changes to `.svelte` files.
**Far** from being optimal but I can work at least. Here's what I did:
1. Installed the following VSC-Extension: [Save and Run](https://marketplace.visualstudio.com/items?itemName=wk-j.save-and-run)
2. Added the following to `settings.json`
```json
	"saveAndRun": {
		"commands": [
			{
				"match": "\\.svelte$",
				"cmd": "\u0003",
				"useShortcut": false,
				"silent": false
			},
			{
				"match": "\\.svelte$",
				"cmd": "yarn run dev -- --host",
				"useShortcut": false,
				"silent": false
			}
		]
	},
```

Only one command can be run per entry, so I used two. The first `\u0003` basically acts as `Ctrl-C` and kills the running process, the second one restarts the server. It takes around 3-5 seconds.

**Comment by aFuzzyBear** [comment]
It both pains me to see this as a workaround, but amazed with the solution provided. Didnt know about the 'Save and Run' extension. Thank you for raising this issue with us @SMEETT

**Comment by aFuzzyBear** [comment]
Further information can be obtained from the corresponding support thread, https://discord.com/channels/830184174198718474/1016851598808453191

**Comment by rainerbird** [comment]
I am also getting this issue too, on a fresh installation of astro + svelte

**Comment by 1CAMOU** [comment]
same issue for me

**Comment by matthewp** [comment]
Pattern I am seeing:

1. Modify svelte component.
1. HMR works.
1. Modify astro component.
1. HMR does not work.

It works on refresh. It seems like going from svelte to astro cause it to break.

**Comment by matthewp** [comment]
PR open, thanks a lot for your patience on this one, I think this will improve .astro file HMR quite a bit.
