### ISSUE TITLE
Docs Site - Table of contents highlight not working

### ISSUE THREAD

**Issue by luwes** [withastro/astro#4658]
### What version of `astro` are you using?

1.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

We started using Astro for our [Media Chrome docs (PR)](https://github.com/muxinc/media-chrome/pull/292) and really like it so far!

One thing we noticed is that the table of contents doesn't seem to highlight the current title of the section you're in when you scroll. Is this expected? 

Thanks!

### Link to Minimal Reproducible Example

https://media-chrome-docs-git-fork-luwes-docs-site-mux.vercel.app/en/get-started

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Jutanium** [comment]
If this is an issue with our docs site, please [make an issue there!](https://github.com/withastro/docs/issues) That said, I don't see this issue on our current docs site.

**Comment by luwes** [comment]
I should have been clearer, it's about the Astro docs starter kit https://github.com/withastro/astro/tree/main/examples/docs

Thanks for looking into it.

**Comment by Jutanium** [comment]
My bad! Seems like a good update for us to make to that template!

**Comment by sarah11918** [comment]
Hi @luwes!

Just to let you know that the Docs template is due for some updates as that starter is really pretty far behind our own Docs site. We do plan to add some features that are currently in Astro Docs, but I'm not sure we have a timetable for that yet. I do agree that this is something we like having in our own docs site that is probably one of the features that we will add to our starter template.

If you'd like to see some extra features in action in the meantime, you can take a look at the Astro Docs code, or come chat in our Discord and our main contributors to the site are there and happy to chat about what they've added!

**Comment by rishi-raj-jain** [comment]
This issue was taken care of in https://github.com/withastro/astro/commit/d8e796e9604231a58dfa84abe163c5dd488d57e3 ig.

**Comment by luwes** [comment]
@rishi-raj-jain thanks for fixing the left side bar bug but this ticket is about the right sidebar highlighting while scrolling.
please do not close yet as it is not fixed afaik.
