### ISSUE TITLE
HMR Bug as discussed on discord

### ISSUE THREAD

**Issue by WallaceSociety** [withastro/astro#4660]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Windows  - WSL

### Describe the Bug

HMR Bug as discussed on discord with tony-sull

I've create a repo that reproduces it and he confirmed it is an issue. 

### Link to Minimal Reproducible Example

https://github.com/WallaceSociety/Astro-HMR-Issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HosfordDotMe** [comment]
Is this issue failing to hot reload on any change while using WSL in Windows?

**Comment by matthewp** [comment]
Discord thread: https://discord.com/channels/830184174198718474/1014759140456923137/1015158873033805834

**Comment by matthewp** [comment]
Relevant section:

> Adding or removing pretty much anything in lib/toc/Toc.astro will reproduce. For example removing line 14 does not remove the header unless you quit and recompile.

**Comment by matthewp** [comment]
This is already fixed by https://github.com/vitejs/vite/commit/01857afbbdac40f950564a3be435a85282c3a159 thanks @bluwy !

**Comment by WallaceSociety** [comment]
Sorry I wasn't much help with this, I've been in the middle of a very large move, but thank you for addressing it. I'll check it out as soon as I can.
