### ISSUE TITLE
Getting ERROR: Expected ")" but found "s" when simply trying to run the example 

### ISSUE THREAD

**Issue by Jimmyelvis** [withastro/astro#4665]
### What version of `astro` are you using?

1.1.6

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Describe the Bug

I was simply trying the example on the Astro website. I followed the directions and ran npm create astro@latest, I went with the recommended settings, cd to my project folder run npm run dev, and I keep getting this error:

`/my-astro-site/src/pages/index.astro:27:186: ERROR: Expected ")" but found "s"`

I'm not sure why I am getting this error, I meet the min requirements for Node.js v16.13.2

### Link to Minimal Reproducible Example

I'm simply running the latest from astro@latest, with no changes

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Can you provide an example?

**Comment by swift502** [comment]
I just ran `npm create astro@latest`, then `cd my-astro-site` and finally `npm run dev` and everything went ok. Can't reproduce. 😕

**Comment by Jimmyelvis** [comment]
Here's a quick git repository I just put together. It's basically all the steps swift502 just did except for me I keep getting the error I mentioned above.

https://github.com/Jimmyelvis/astrotest

**Comment by matthewp** [comment]
@Jimmyelvis can you let me know what Node version and operating system you are using?

**Comment by Jimmyelvis** [comment]
Sure, I'm using Node v16.13.2, Npm 8.13.2, and my OS is Windows 10 64 bit

**Comment by matthewp** [comment]
Hi @Jimmyelvis, can you try this again and let me know? I've been struggling to recreate so I just want to make sure we're doing the same thing.

```shell
npm init astro@latest
```

Walk  through all  of the steps choosing the default options. cd into the new project and:

```shell
npm run dev
```

Also, which terminal are you using. `cmd`?

**Comment by matthewp** [comment]
Hey @Jimmyelvis, I've been having trouble reproducing. I'm going to close as I think there might not be an issue here, but if you're able to answer the above I'd be happy to reopen.

**Comment by Jimmyelvis** [comment]
Sorry, I'm just now getting to your response. I tried it again. These are the options I used:

√ Where would you like to create your new project? ... ./my-astro-site
√ Which template would you like to use? » Just the basics (recommended)
✔ Template copied!
√ Would you like to install npm dependencies? (recommended) ... yes
√ Would you like to initialize a new git repository? (optional) ... yes
✔ Git repository created!
√ How would you like to setup TypeScript? » Relaxed
✔ TypeScript settings applied!
✔ Setup complete.
✔ Ready for liftoff!

I tried with powershell, and git bash and still  the same results when I go localhost:3000.

This is the full error message inside the browser:

[plugin:astro:build] Transform failed with 1 error:
D:/Jinjoe's stuff/Learning/WEB DEVELOPMENT/JAVASCRIPT/Frameworks/Astro/2/src/pages/index.astro:27:156: ERROR: Expected ")" but found "s"
D:/Jinjoe's stuff/Learning/WEB DEVELOPMENT/JAVASCRIPT/Frameworks/Astro/2/src/pages/index.astro:27:156
Error: Transform failed with 1 error:
D:/Jinjoe's stuff/Learning/WEB DEVELOPMENT/JAVASCRIPT/Frameworks/Astro/2/src/pages/index.astro:27:156: ERROR: Expected ")" but found "s"
    at failureErrorWithLog (D:\Jinjoe's stuff\Learning\WEB DEVELOPMENT\JAVASCRIPT\Frameworks\Astro\2\node_modules\esbuild\lib\main.js:1624:15)
    at D:\Jinjoe's stuff\Learning\WEB DEVELOPMENT\JAVASCRIPT\Frameworks\Astro\2\node_modules\esbuild\lib\main.js:1413:29
    at D:\Jinjoe's stuff\Learning\WEB DEVELOPMENT\JAVASCRIPT\Frameworks\Astro\2\node_modules\esbuild\lib\main.js:678:9
    at handleIncomingPacket (D:\Jinjoe's stuff\Learning\WEB DEVELOPMENT\JAVASCRIPT\Frameworks\Astro\2\node_modules\esbuild\lib\main.js:775:9)
    at Socket.readFromStdout (D:\Jinjoe's stuff\Learning\WEB DEVELOPMENT\JAVASCRIPT\Frameworks\Astro\2\node_modules\esbuild\lib\main.js:644:7)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10

**Comment by matthewp** [comment]
Great, thanks for the new information, this will help a lot! Reopening.

**Comment by mischah** [comment]
Hej @Jimmyelvis, rename your directory from `Jinjoe's stuff` to `Jinjoes stuff` and you are good to go 🚀 

cc/ @matthewp

**Comment by Jimmyelvis** [comment]
> Hej @Jimmyelvis, rename your directory from `Jinjoe's stuff` to `Jinjoes stuff` and you are good to go 🚀
> 
> cc/ @matthewp

Yes, that solved it. Thanks a lot.

**Comment by matthewp** [comment]
Awesome, good to hear
