### ISSUE TITLE
BUG: Vercel Edge Adapter Related Issue With Using Node Modules (e.g. Crypto)

### ISSUE THREAD

**Issue by jaymanmatthewsdev** [withastro/astro#4670]
### What version of `astro` are you using?

1.1.7

### Are you using an SSR adapter? If so, which one?

Vercel Edge

### What package manager are you using?

pnpm

### What operating system are you using?

Windows (WSL 2)

### Describe the Bug

When utilising the Vercel edge adapter, a simple build of the application is unsuccessful. It seems to fail bundling Node.js native modules, such as 'crypto' in this specific case. However, if I switch to the serverless adapter, it builds and deploys fine.

The error message displayed upon building the application is as follows:
![image](https://user-images.githubusercontent.com/108161206/189055299-673400a9-ff89-4819-b6a1-10821db0d505.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gxbfu8?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
That's because Vercel Edge does not use Node.js and packages such as `crypto` are internal Node packages. If you need Node support use Vercel Serverless instead.
