### ISSUE TITLE
Svelte component styles are not included in built HTML document

### ISSUE THREAD

**Issue by beeb** [withastro/astro#4671]
### What version of `astro` are you using?

1.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows WSL2

### Describe the Bug

When using a svelte component ([`svelte-video-player`](https://github.com/meigo/svelte-video-player)), the styles are bundled into a CSS file found in the `assets` directory, but this CSS is not linked in the final HTML document.

### Link to Minimal Reproducible Example

https://github.com/beeb/astro-svelte-styles-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Looks like this is a problem when using `client:only`, is that right?

**Comment by matthewp** [comment]
PR: https://github.com/withastro/astro/pull/4699
