### ISSUE TITLE
Weird generated asset name

### ISSUE THREAD

**Issue by gasatrya** [withastro/astro#4672]
### What version of `astro` are you using?

1.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

WSL2 on Windows

### Describe the Bug

I am not sure if this is an issue, or I miss configured Astro, when I ran `build`, asset generated file name is so weird, it is named based on existing pages I have. Here's the dummy pages https://github.com/gasatrya/hidupberdua.id/tree/master/dist/assets and the asset name is `hallo-dunia-index-sandwich-generation.6342a09a.css`. My original css file is `global.css`.

Any help would be appreciated.

### Link to Minimal Reproducible Example

https://github.com/gasatrya/hidupberdua.id/tree/master/dist/assets

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hi @gasatrya, we generate these names based on the page they belong to, to avoid interfering with other pages. A page's CSS is made up of more than 1 css file usually so we can't just name it after that. Perhaps we could do better and make it shorter, but it's always going to be based on the page it belongs to. 

The name of the file hopefully doesn't cause any actual issues, does it? Going to close assuming it does not, happy to reopen if so.

**Comment by pierredewilde** [comment]
I come back with Astro weird generated names. 

Those names may become ridiculous long if used in several places:

`about-astro-about-index-about-unocss-index.71a83050.css`

The generated number should suffice to make it unique:

`71a83050.css` or `about.71a83050.css`

**Comment by matthewp** [comment]
Yeah true, probably what we should do is just grab the last segment from the first page we find, for example `src/pages/about.astro` -> `about` and then just create the hash for *all* of the pages. That would still be unique, as you said, and give us shorter names.

**Comment by matthewp** [comment]
Re-opening as there might be an easy win here.

**Comment by matthewp** [comment]
A change here should go out today

**Comment by pierredewilde** [comment]
Thank you for your prompt fix.

**Comment by gasatrya** [comment]
Thank you.
