### ISSUE TITLE
client:* directives are loading Vue components server-side

### ISSUE THREAD

**Issue by alexbruno** [withastro/astro#4686]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows and Linux

### Describe the Bug

Reference: https://docs.astro.build/en/reference/directives-reference/#client-directives

The `client:*` directive is loading Vue components server-side.
It only works as expected, loading the component JS client-side, when used with `client:only`. And, also, it is not necessary to pass the framework name to the directive, as we can see on the docs page: `client:only="vue"`.
By using any of these: `client:load`, `client:visible`, or `client:idle` ... If the component JS code contains any reference to browser APIs outside the lifecycle hooks (ex: `onMounted`), the build crashes.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-vue-client-bug?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
That's as intended, Astro server renders components by default. If you want a component to not be server rendered because it uses browser code, `client:only` is the thing to use.

**Comment by alexbruno** [comment]
So, I think this could be clearer!
The documentation is not clear about that and also the directive name is not really clear about that.
What mean when I use the `client:load` directive?
It is supposed to **load** the component on the **client**.
If I want the component to be loaded client-side, why should it be rendered server-side?
If I have everything ok in the component to be rendered server-side, why would I want to load it server-side?
I disagree with that pattern and also about closing this issue. It is still an issue for me.
At least a concept issue!
