### ISSUE TITLE
Can't run build or dev when project path contains non-English characters on Windows

### ISSUE THREAD

**Issue by Lifeni** [withastro/astro#4689]
### What version of `astro` are you using?

1.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

1. Open Terminal on Windows.
2. Run the following command to create the project.

    ```shell
    mkdir 测试
    cd 测试
    pnpm create astro@latest
    ```

3. Error after running command.

    ```shell
    cd my-astro-site
    npm run build
    ```

The error message is as follows, the `\` in the path was parsed incorrectly.

```powershell
PS C:\Codes\测试\my-astro-site> npm run build

> @example/basics@0.0.1 build
> astro build

15:03:55 [build] output target: static
15:03:55 [build] Collecting build info...
15:03:55 [build] Completed in 17ms.
15:03:55 [build] Building static entrypoints...
[vite:load-fallback] Could not load C:Codes测试my-astro-site
untimeserverindex.js (imported by src/pages/index.astro): ENOENT: no such file or directory, open 'C:\Codes\测试\my-astro-site\Codes测试my-astro-site
untimeserverindex.js'
 error   Could not load C:Codes测试my-astro-site
untimeserverindex.js (imported by src/pages/index.astro): ENOENT: no such file or directory, open 'C:\Codes\测试\my-astro-site\Codes测试my-astro-site
untimeserverindex.js't
Error: Could not load C:Codes测试my-astro-site
ode_modulesastrodist
untimeserverindex.js (imported by src/pages/index.astro): ENOENT: no such file or directory, open 'C:\Codes\测试\my-astro-site\Codes测试my-astro-site
ode_modulesastrodist
untimeserverindex.js'

```

I also tested with WSL and StackBlitz and it works fine. It seems that this problem occurs only on Windows.

Related Issues: https://github.com/withastro/astro/issues/4624#issue-1361597248 

I tried using Vite + Vue.js and it works fine. So this might be an Astro bug.

<details>
<summary>Path resolution is normal when using `vite build`.</summary>

```powershell
PS C:\Codes\测试\my-astro-site>  .\node_modules\.bin\vite build
vite v3.0.9 building for production...
✓ 0 modules transformed.
Could not resolve entry module (index.html).
error during build:
Error: Could not resolve entry module (index.html).
    at error (file:///C:/Codes/%E6%B5%8B%E8%AF%95/my-astro-site/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.loadEntryModule (file:///C:/Codes/%E6%B5%8B%E8%AF%95/my-astro-site/node_modules/rollup/dist/es/shared/rollup.js:22352:20)
    at async Promise.all (index 0)

```

</details>

### Link to Minimal Reproducible Example

None

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please add a stackblitz example and resubmit, thanks.

**Comment by Lifeni** [comment]
StackBlitz doesn't have a Windows environment, so it can't be reproduced with StackBlitz.

Here is a working link: [stackblitz](https://stackblitz.com/edit/github-i4hde8?file=%E6%B5%8B%E8%AF%95%2Ftest%2F.stackblitzrc,%E6%B5%8B%E8%AF%95%2Ftest%2FREADME.md), the error cannot be reproduced.

**Comment by kasvith** [comment]
Wow im having this issue also with Finnish letters
