### ISSUE TITLE
Hoisted client javascript libraries not woking

### ISSUE THREAD

**Issue by marceloverdijk** [withastro/astro#4691]
### What version of `astro` are you using?

1.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I cannot use client javascript served from a NPM dependency.

In `Layout.astro` the client javascript library is included like:

```
<body>
    <slot />
    <script>
      import 'aos/dist/aos.js'

      (function() {
        AOS.init({
          duration: 650,
          once: true
        })
      })()
    </script>
</body>
```

But in the browser it fails with:

`Uncaught ReferenceError: AOS is not defined`

Looking at the hoisted code referenced in the generated HTML as:

`<script type="module" src="/Users/marceloverdijk/workspace/astro-npm-js/src/layouts/Layout.astro?astro&type=script&index=0&lang.ts"></script>`

I can see the orginal imported `aos.js` has been "transformed" 
and it exports something like:

```
var aos_dist_aos_js_default = require_aos();
export {
  aos_dist_aos_js_default as default
};
```

but not AOS anymore, hence the `AOS is not defined` error.

See full example here: https://github.com/marceloverdijk/astro-npm-js

### Link to Minimal Reproducible Example

https://github.com/marceloverdijk/astro-npm-js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
It appears this works:

```js
import AOS from 'aos/dist/aos.js'
```

**Comment by marceloverdijk** [comment]
ok thx, so that is the supposed way to include a "full" library?
In some cases I want to include such libraries - similar as jquery plugins in the past - , but don't do a further config myself, how would I import it then? 
Simply `import 'aos/dist/aos.js'` and all would work?

I'm just missing the knowledge how to import npm libraries best.

**Comment by marceloverdijk** [comment]
@matthewp Additionally I found that some js client libs I need to include on the page do not export a default.

E.g. just doing:

```
const HSBsValidation = { .. }
```

and then when doing `import HSBsValidation from '@js/hs.bs-validation.js'` in my `Layout.astro` that will result in the following error in the browser:

```
Uncaught SyntaxError: The requested module '/src/js/hs.bs-validation.js' does not provide an export named 'default' (at Layout.astro:47:14)
```

Is there something I can do such a case? Thx for your help, much appreciated 👍

**Comment by matthewp** [comment]
You really just need to read the docs on each package and they should tell you what they export. There's nothing that Astro does that has any control over this.

**Comment by marceloverdijk** [comment]
OK I understand, I have so js libraries that don't export anything but just define a const.

When just using such a file using a <script> tag that works (even if  nothing is exported)

But I just cannot include such a js file in a script tag when such a js file is in node_modules using npm unfortunately..
