### ISSUE TITLE
ESM dependencies are not resolved correctly during build

### ISSUE THREAD

**Issue by Enteleform** [withastro/astro#4692]
### What version of `astro` are you using?

1.1.7

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

This error occurs during `build` when multi-distribution (*CJS, ESM*) packages are imported.

```shell
> astro build

06:04:41 AM [build] output target: static
06:04:41 AM [build] Collecting build info...
06:04:41 AM [build] Completed in 18ms.
06:04:41 AM [build] Building static entrypoints...
06:04:42 AM [build] Completed in 700ms.

 building client 
Completed in 202ms.


 generating static routes 
 error   Named export 'atom' not found. The requested module 'solid-use' is a CommonJS module, which may not support all module.exports as named exports. 
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'solid-use';
  const { atom } = pkg;
  
file:///D:/DemoProject/dist/entry.mjs?time=1662717882730:3
/* empty css                        */import { atom } from 'solid-use';
                                               ^^^^
SyntaxError: Named export 'atom' not found. The requested module 'solid-use' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'solid-use';
const { atom } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:528:24)
    at async generatePages (file:///D:/DemoProject/node_modules/astro/dist/core/build/generate.js:70:20)
    at async staticBuild (file:///D:/DemoProject/node_modules/astro/dist/core/build/static-build.js:67:5)
    at async AstroBuilder.build (file:///D:/DemoProject/node_modules/astro/dist/core/build/index.js:82:5)
    at async AstroBuilder.run (file:///D:/DemoProject/node_modules/astro/dist/core/build/index.js:123:7)
    at async build (file:///D:/DemoProject/node_modules/astro/dist/core/build/index.js:22:3)
    at async runCommand (file:///D:/DemoProject/node_modules/astro/dist/cli/index.js:138:14)
```

I included two demos in the reproduction repo, one using `astro` and one using `solid-start`. Both demos are minimally modified starter projects, they were updated to implement `atom` from  `solid-use` instead of `createSignal` from `solid-js`.

The `solid-start` demo builds without issue. (*they also use `vite` in their [build process](https://github.com/solidjs/solid-start/blob/c06313ffc247cd4eb106d92d05b719884e708562/packages/start/bin.cjs#L141-L142)*)

The `astro` demo throws the above error.

`solid-use` has both CJS & ESM distributions, with a properly configured [package.json](https://github.com/lxsmnsyc/solid-use/blob/87ae59bfb2e2c5ff4e2a992f3732ffeef3e20ec4/packages/solid-use/package.json#L12-L13) that should allow usage in either environment.

### Link to Minimal Reproducible Example

https://github.com/enteleform-codesandbox/0015--Astro--ESM-Imports

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Is this fixed using `vite: { ssr: { noExternal: [ 'solid-use' ] } }` ?

**Comment by Enteleform** [comment]
@matthewp 

> Is this fixed using `vite: { ssr: { noExternal: [ 'solid-use' ] } }` ?

This seems to work 👍. Do you know why it's required for `astro` but not other `vite` projects? I just added another demo to the repro, `vite`'s `vanilla-ts` starter. It also builds fine with `solid-use` without any explicit configuration.

Also, once I got past that error I ran into another one which seems to be caused by improper hoisting in the `entry.mjs` bundle. This one might be harder to make a repro for since it's the result of bundling multiple nested local dependencies, but I have built other `vite`/`webpack` projects using those same libraries without issue.

```log
> dotenv  -v ExecutionContext=Production   astro build

(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.
ts-toolbelt doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
05:16:48 AM [build] output target: static   
05:16:48 AM [build] Collecting build info...
05:16:48 AM [build] Completed in 25ms.      
05:16:48 AM [build] Building static entrypoints...
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
05:16:51 AM [build] Completed in 2.98s.

 building client 

PWA v0.12.6
mode      generateSW
precache  16 entries (94.31 KiB)
files generated
  dist\sw.js
  dist\workbox-4d7aac67.js      
Completed in 5.36s.       


 generating static routes 
 error   Cannot access 'File' before initialization
ReferenceError: Cannot access 'File' before initialization
    at file:///D:/DemoProject/dist/entry.mjs?time=1662801417180:3288:28
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:528:24)
    at async generatePages (file:///D:/DemoProject/node_modules/astro/dist/core/build/generate.js:70:20) 
    at async staticBuild (file:///D:/DemoProject/node_modules/astro/dist/core/build/static-build.js:67:5)
    at async AstroBuilder.build (file:///D:/DemoProject/node_modules/astro/dist/core/build/index.js:82:5)
    at async AstroBuilder.run (file:///D:/DemoProject/node_modules/astro/dist/core/build/index.js:123:7) 
    at async build (file:///D:/DemoProject/node_modules/astro/dist/core/build/index.js:22:3)
    at async runCommand (file:///D:/DemoProject/node_modules/astro/dist/cli/index.js:138:14)
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: demo-project@1.0.0 
npm ERR!   at location: D:\DemoProject 

 *  The terminal process "C:\WINDOWS\System32\cmd.exe /d /c npm run build" terminated with exit code: 1. 
 ```

**Comment by matthewp** [comment]
If I had to guess, this line is probably causing it: https://github.com/withastro/astro/blob/main/packages/integrations/solid/src/index.ts#L42

can you try commenting that out in your local node_modules and see if it fixes any of those issues?

**Comment by Enteleform** [comment]
> can you try commenting that out in your local node_modules and see if it fixes any of those issues?

Just tried it, still ran into the original issue.

**Comment by ruhollahh** [comment]
I ran into this problem with the @codesandbox/sandpack-react package.
and this didn't help:
> Is this fixed using vite: { ssr: { noExternal: [ 'solid-use' ] } } ?

**Comment by matthewp** [comment]
@ruhollahh that's likely unrelated.

**Comment by ruhollahh** [comment]
> @ruhollahh that's likely unrelated.

I'm getting this error:
` error   Named export 'SandpackCodeEditor' not found. The requested module '@codesandbox/sandpack-react' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from '@codesandbox/sandpack-react';
  const { SandpackProvider, SandpackLayout, SandpackCodeEditor, SandpackPreview } = pkg;
  
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)`

how is this unrelated?

**Comment by ruhollahh** [comment]
> @ruhollahh that's likely unrelated.

I downgraded the astro version from 1.1.7 to 1.0.0-beta.73 and the problem was solved, I guess it had something to do with vite 3.

**Comment by Enteleform** [comment]
Just tried `1.0.0-beta.73` for the repro & still ran into the same issue.

**Comment by ruhollahh** [comment]
okay I finally fixed it by finding the the package in error in node_modules folder and adding this to it's package.json file:
`"type": "module"`
also edit this:
"main": "dist/cjs/production/index.js"
to this:
`"main": "dist/esm/production/index.js"`
I also tested this method in your Minimal Reproducible repo and it works, I was able to build without any error.
I hope this helps.

**Comment by Enteleform** [comment]
> "main": "dist/esm/production/index.js"

There are two current workarounds that don't require altering affected packages:

Matthew's suggestion of:
```js
{
  vite: {
    ssr: { 
      noExternal: ["solid-use"]
    }
  }
}
```
and also one that I had posted on the Discord server when I opened the issue:
```js
{
  vite: {
    resolve: {
      alias: {"solid-use": "D:/DemoProject/node_modules/solid-use/dist/esm/production/index.js"}
    }
  }
}
```

**Comment by matthewp** [comment]
Is this a problem only in build but not in development mode?

**Comment by Enteleform** [comment]
> Is this a problem only in build but not in development mode?

Yes, that's correct.

**Comment by Enteleform** [comment]
@matthewp

Seems like this might have something to do with monorepos/workspaces.

Just tried out the latest `Completely Empty` template from [astro.new](https://astro.new/). It works fine if I use it on its own, but I get the following error when I tried running `astro dev` in my Yarn workspace:

```shell
> astro dev

file:///D:/DemoProject/node_modules/@astrojs/markdown-remark/dist/rehype-collect-headings.js:2  
import { toHtml } from "hast-util-to-html";
         ^^^^^^
SyntaxError: Named export 'toHtml' not found. The requested module 'hast-util-to-html' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'hast-util-to-html';
const { toHtml } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:528:24)

npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @enteleform/habit-tracker--document@1.0.0 
npm ERR!   at location: D:/DemoProject 

*  The terminal process "C:/WINDOWS/System32/cmd.exe /d /c npm run dev" terminated with exit code: 1. 
```

**Comment by Enteleform** [comment]
Actually, just noticed that that same issue broke one of my previously working projects.

I haven't changed anything in the project other than running `yarn install` on the workspace to install deps for other projects in the same workspace... Looking into it now...

**Comment by matthewp** [comment]
Are you using `shamefully-hoist=true` in your `.npmrc`? That's the first thing I look for in monorepo issues.

**Comment by Enteleform** [comment]
> Are you using `shamefully-hoist=true` in your `.npmrc`? That's the first thing I look for in monorepo issues.

I think `shamefully-hoist` is just for `pnpm`. Good call though, got it working with this @ the `yarn` workspace root `package.json`:

```json
"nohoist": [
  "**/astro",             "**/astro/**"
  "**/@vivliostyle/cli",  "**/@vivliostyle/cli/**",
]
```

Before that I was trying to go about it more granularly by targeting the clashing packages via `yarn` + `resolutions`, and `npm` + `overrides`, but neither of those seemed to work... 😑

**Comment by rishi-raj-jain** [comment]
I think this is more of a rollup error.

**Comment by rishi-raj-jain** [comment]
https://www.npmjs.com/package/@rollup/plugin-commonjs something like this shall help?

**Comment by Enteleform** [comment]
> [npmjs.com/package/@rollup/plugin-commonjs](https://www.npmjs.com/package/@rollup/plugin-commonjs) something like this shall help?

I tried that and a couple of Vite-specific ones without any luck.

The issue doesn't occur in other Vite projects though, even a plain Vite starter - so it seems like the issue might have something to do with Astro's particular usage of Vite.

**Comment by bluwy** [comment]
`solid-use` is incorrectly packaged (https://publint.bjornlu.com/solid-use@0.5.0), hence it doesn't work in node when Astro builds. I'd suggest opening an issue in their repo to fix it.
