### ISSUE TITLE
`npx astro add` throws "fetch is not defined" in v1.2.0

### ISSUE THREAD

**Issue by greypants** [withastro/astro#4704]
### What version of `astro` are you using?

1.2.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm, yarn

### What operating system are you using?

Mac

### Describe the Bug

`npx astro add` throws "fetch is not defined" in v1.2.0
version 1.2.0 appears to have broken `npx astro add`.

```shell
npx astro add react
✖ fetch is not defined
```

Reverting to `"astro": "1.1.8"` works fine.

### Link to Minimal Reproducible Example

 https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Thank you for the report! This is fixed in 1.2.1😄
