### ISSUE TITLE
Exporting and importing the output of `Astro.glob` causes a compiler error

### ISSUE THREAD

**Issue by Beefers** [withastro/astro#4714]
### What version of `astro` are you using?

1.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When exporting the output of `await Astro.glob("./*.md");`, then importing it in another file, Astro will attempt to reference a variable that is not yet defined, thus erroring when trying to build.

This only happens on build, not in `astro dev`, so in the reproduction, you will need to stop the dev server and `pnpm build`. You should see an error:

```
Error: Cannot access '_page1' before initialization
```

In my project, I have temporarily solved this by doing a second glob in the file I wish to import my globbed output in. This is probably not an ideal solution, so I am making this bug report in the hopes it can be resolved.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nplvfd

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Exporting values from Astro components is not supported.
