### ISSUE TITLE
@vitejs/plugin-legacy doesn't work

### ISSUE THREAD

**Issue by aminya** [withastro/astro#4716]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I am trying to use `@vitejs/plugin-legacy` to generate a bundle for the older browsers, but nomodule is not inserted into my built HTML files. Does Astro support this?

https://www.npmjs.com/package/@vitejs/plugin-legacy

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5e3bfx

Run `npm run build` and see `dist/index.html`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Astro does not support browsers without support for modules.

**Comment by aminya** [comment]
Since Astro mostly uses HTML, supporting old browsers should not be very hard. I wonder what causes this official Vite plugin not to work.
