### ISSUE TITLE
Component creation error due to Vite V3

### ISSUE THREAD

**Issue by rohaanuv** [withastro/astro#4719]
### What version of `astro` are you using?

1.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

windows

### Component creation error due to Vite V3
 I am getting the following error.  for creating the component in Astro. 
Terminal Error:
![image](https://user-images.githubusercontent.com/40298253/189537330-b3fc1c55-446c-4ca7-829e-ab31fa99fcd7.png)

On Browser
![image](https://user-images.githubusercontent.com/40298253/189537359-eef2645e-403b-48e6-a011-6f35c3785103.png)

This error not showing for the default template of Astro.  When we start creating customer component then error popup
if we used version2 we may not get the error Because of the Lates **Vite version 3 update** many people get the same error. 

### Link to Minimal Reproducible Example

http://localhost:3000/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
I suspect this might be happening because your component has a capitalized A in the file extension.

**Comment by matthewp** [comment]
I think @Princesseuh is right here. If you can create an example in Stackblitz we'll be happy to take a look, otherwise I suggest just renaming the extension to use a lower case `a`.

**Comment by rohaanuv** [comment]
Thank you for your help
