### ISSUE TITLE
Hydration issue when using local storage

### ISSUE THREAD

**Issue by kestvir** [withastro/astro#4726]
### What version of `astro` are you using?

1.0.0-beta.44

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Hello, I'm trying to make a new personal site with Astro. Wanted to implement dark theme switcher that looked similar to the one in astro docs. When the page is refreshed only the icon color seems to rerender instead of the whole component which is  the goal. However, in my case, I get warning: `className did not match. Server: "" Client: "checked"`.

I was wondering if this is also happening in the astro docs website and if not, how is this avoided?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mmowge?on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Can you try with the stable 1.0 release? We are no longer supporting the beta.

**Comment by kestvir** [comment]
> Can you try with the stable 1.0 release? We are no longer supporting the beta.

Thanks for pointing this out. However, looks like the stackblitz example is using astro 1.2.1 and if you look at the `console ` the warning still gets shown.

**Comment by matthewp** [comment]
This seems to work fine: https://stackblitz.com/edit/github-mmowge-7ea89s?file=src%2Fcomponents%2FThemeToggle.jsx&on=stackblitz

What is this not doing that you expect?

**Comment by matthewp** [comment]
Going to close, let me know if you have an answer to the above and we can reopen, thank you!
