### ISSUE TITLE
Using css selector where() is not good for many browsers

### ISSUE THREAD

**Issue by niboac** [withastro/astro#4732]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I suggest do not use css selector where(), cause It is too new for many old browser, even bellow Chrome 88.

### Link to Minimal Reproducible Example

do not need demo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks @niboac. I understand the concern here. Since we use this issue tracker for bugs can you make this point here instead: https://github.com/withastro/rfcs/discussions

We can discuss there and come up with a solution. A few people have suggested this.
