### ISSUE TITLE
Invalid hook call react

### ISSUE THREAD

**Issue by kestvir** [withastro/astro#4734]
### What version of `astro` are you using?

1.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I'm using react for one of my components but get the invalid hook call even though the code looks ok.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mmowge?file=src%2Fcomponents%2FThemeToggle.jsx&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Is this the same as https://github.com/withastro/astro/issues/4220 ?

**Comment by kestvirb** [comment]
> Is this the same as #4220 ?

Sorry and thanks!
