### ISSUE TITLE
Multipart/form-data file encoding issue

### ISSUE THREAD

**Issue by Simptechtic-Nicholas118** [withastro/astro#4737]
### What version of `astro` are you using?

1.2.2

### Are you using an SSR adapter? If so, which one?

Nodejs

### What package manager are you using?

yarn

### What operating system are you using?

Windows 10

### Describe the Bug

I tried to upload using PNG and JPEG but none of it works

/src/pages/index.astro
```
<form action="/api/upload" enctype="multipart/form-data" method="post">
    <label for="file">Upload File</label>
    <input type="file" id="file" name="file" />
    <button type="submit">Submit</button>
</form>
```

/src/pages/api/upload.ts
```
import type { APIContext } from "astro";

export async function post({ request }: APIContext) {
    const data = await request.formData();
    const file = data.get("file") as File;

    if (file) {
        const buffer = await file.arrayBuffer();
        console.log(buffer);
    }

    return new Response(JSON.stringify("Ok"), { status: 200 });
}
```

server console log buffer
```
ArrayBuffer {
  [Uint8Contents]: <ef bf bd 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 32 00 00 00 64 08 03 00 00 00 ef bf bd 36 ef bf bd 69 00 00 01 ef bf bd 50 4c 54 45 00 00 00 2c ef bf bd ef bf bd ef bf bd ef bf bd ef bf bd 2c ef bf bd ef bf bd 2c ef bf bd ef bf bd 2c ef bf bd ef bf bd 2c ef bf bd ef bf bd 00 00 00 2c ... 2378 more bytes>,   
  byteLength: 2478
}
```

However, everything runs smoothly in build

after built server console log buffer (this is the correct buffer)
```
ArrayBuffer {
  [Uint8Contents]: <89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 32 00 00 00 64 08 03 00 00 00 f3 36 93 69 00 00 01 83 50 4c 54 45 00 00 00 2c aa e1 ff ff ff 2c aa e1 2c aa e1 2c aa e1 2c aa e1 00 00 00 2c aa e1 07 1b 23 2c aa e1 0c 2f 3e 2c aa e1 13 49 60 2c aa e1 00 00 00 2c aa e1 17 5a 77 04 0f 13 06 17 ... 1413 more bytes>,
  byteLength: 1513
}
```

I suspect byteLength difference in binary vs utf-8 encoding.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kkavvp

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Problem is probably here: https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-astro-server/index.ts#L217-L225
