### ISSUE TITLE
cloneElement with props defined does not render correctly

### ISSUE THREAD

**Issue by craigjennings11** [withastro/astro#4753]
### What version of `astro` are you using?

1.2.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When using `cloneElement` in a React component, passing anything to the optional `props` parameter causes the children of the cloned element to not render.

Here's a screenshot of the DOM rendered in the linked StackBlitz example. Notice that the `div` of the `ClonedWithProps` component is rendered but not it's children, while the `ClonedWithoutProps` children are rendered correctly.

![image](https://user-images.githubusercontent.com/1683368/190204323-d394035c-be08-4ac3-8137-c4992be2b81b.png)

The only difference between the two components is that one calls `cloneElement(element, props)` while the other only calls `cloneElement(element)`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wysfgw?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Looks like React doesn't like passing `null` or `undefined` as the children prop is the reason.
