### ISSUE TITLE
Stylesheet is duplicated on the Index page

### ISSUE THREAD

**Issue by phenomen** [withastro/astro#4757]
### What version of `astro` are you using?

1.2.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows, Linux

### Describe the Bug

After build, stylesheet is placed in the `head` and in the middle of the `body`.

![image](https://user-images.githubusercontent.com/138311/190233598-ab5a64f8-09e6-4e1b-b1db-280944a5dc34.png)

On Stackblitz it's reproducible on the index page (`/`) with 
```
npm build
npm preview
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xkmtka?file=src/pages/index.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
This seems like a bigger issue. I was trying this and found that the output generated doesn't even have a html, body and head tags unless inserted in layouts or pages. Shouldn't we be creating those if not found?

**Comment by matthewp** [comment]
This was a fun one, cc @rishi-raj-jain see https://github.com/withastro/astro/pull/4892
