### ISSUE TITLE
Astro component doesn't render anything when it only contains a <script>

### ISSUE THREAD

**Issue by pReya** [withastro/astro#4770]
### What version of `astro` are you using?

1.2.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When I create a `index.astro` component, that ONLY includes a `<script>` tag, the script won't render/be included in the output at all.

This will not work:

```
<script>
  console.log("HELLO");
</script>
```

However, as soon as I put anything else into the component (e.g. a div or h1) it will render and run the script.

This will work:
```
<script>
  console.log("HELLO");
</script>
<h1></h1>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qaafby?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Really curious about this one. My guess is that the compiler returns early when there is no content so it doesn't pick up on the scripts correctly.

**Comment by jasikpark** [comment]
there might be a similar issue for global styles then?

**Comment by matthewp** [comment]
Could be. This only occurs if a script is literally the only thing on your page though, so a super corner case.

**Comment by matthewp** [comment]
Styles with nothing else on the page wouldn't do anything, so arguably they shouldn't be added!

**Comment by jasikpark** [comment]
Scoped styles shouldn't be added, but global astro styles or imported styles should, right?

```
<!-- my-global-astro-file-style.astro -->
<style is:global>
body{background:red;}
</style>
```

and

```
---
import "my-global-style.css";
import "my-global-astro-file-style.astro";
---
```

should both return the unscoped styles as their body if imported, right?

**Comment by matthewp** [comment]
The scenario is a completely empty page; no elements in the template at all (except the script). So for style this would mean that you could style the body but there is no content. So maybe technically a bug, but not a real use-case.
