### ISSUE TITLE
Svelte styles not included in build for client:only components

### ISSUE THREAD

**Issue by rob0rt** [withastro/astro#4777]
### What version of `astro` are you using?

1.2.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm/ npm

### What operating system are you using?

Linux/ Mac

### Describe the Bug

When using a Svelte component that's rendered with `client:only="svelte"`, any styles included in that component are not applied in built versions. In the repo below, the issue is not present when using `npm start` but is when running `npm build && npm preview`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5cghqe?file=src/components/Example.svelte

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rob0rt** [comment]
I'm pretty sure this is also happening in astro `1.2.4`, which was the version when I first noticed this issue (for which I attempted to fix by upgrading)

**Comment by zachlankton** [comment]
I too am having this same problem.  `client:load` works and renders styles, but `client:only="svelte"` does not.

I am using Node SSR adapter.
NPM
Windows (Linux DevContainer in VSCode)
