### ISSUE TITLE
"can't access property "children", node is undefined" when adding rehype plugin

### ISSUE THREAD

**Issue by charlesvdv** [withastro/astro#4789]
### What version of `astro` are you using?

1.2.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

By simply adding the rehype plugin `rehype-shift-heading` to the astro configuration, I get an error: 

`[plugin:@mdx-js/rollup] can't access property "children", node is undefined`

I also tried with the plugin `rehype-autolink-headings` and there is a similar error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3qccek?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Does this work in regular mdx outside of astro?

**Comment by matthewp** [comment]
I think this is a limitation of mdx and not of astro/mdx. Let me know if I'm reading this wrong and we can continue discussing.

**Comment by charlesvdv** [comment]
I just did some investigation. astro nor mdx are the source of the issue. The issue is coming from how I configured the rehype plugin. I initially passed the plugin like this: 

```js
    rehypePlugins: [rehypeShiftHeading({ shift: 1})],
```

but actually, plugins should be passed like this: 

```js
    rehypePlugins: [[rehypeShiftHeading, { shift: 1}]],
```

**Comment by matthewp** [comment]
Ah! Ok great, glad you figured it out!
