### ISSUE TITLE
Picture element generating width and height on the img element

### ISSUE THREAD

**Issue by smeevil** [withastro/astro#4793]
### What version of `astro` are you using?

1.2.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

nom

### What operating system are you using?

MacOS 12.4

### Describe the Bug

I'm having a bit of trouble with the Picture element. It seems it generates an img tag with a set width and height, which causes the image to stop being responsive. I've compared the generated code from the Picture tag to the one described by MDN. The MDN one does not have a width/height on the img tag and works as expected. 

Am I doing something wrong, or is this a bug maybe?

I've added two screenshots where you can find the original code in the template and the generated HTML
The first picture tag is generated by the Picture component, the second by hand (which works properly)

If I remove the width and height van the img tag generated by the Picture element, it works as intended.
I did maybe find a related message to this here: https://discord.com/channels/830184174198718474/1018629133951045703/1019002736584429679

Source code
![CleanShot_2022-09-18_at_10 26 54](https://user-images.githubusercontent.com/13874/190912443-c8de7d2e-ca11-4480-b998-0a5e6a91429c.png)

Generated code
![CleanShot_2022-09-18_at_10 25 13](https://user-images.githubusercontent.com/13874/190912439-c0256ecd-e198-4369-a29d-c070abb0e3f5.png)

I tried to make a stackblitz for this, but that gives an error trying to install `sharp` module :/

Gerard.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-q4vakz?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

well... I'll give it a shot at #4797 :)

**Comment by smeevil** [comment]
I copied the Picture.astro from @astrojs/image/components/Picture.astro to my own components so I could adjust it and test some things. It turns out that, indeed, just adding `delete image.width; delete image.height;` after the `await getPicture` call fixes the problem.

**Comment by matthewp** [comment]
@smeevil can you sub a PR for this?

**Comment by smeevil** [comment]
It is already linked in the top post :) but here again #4797

**Comment by smeevil** [comment]
And it has been merged :)
