### ISSUE TITLE
Astro Image component does not work on Netlify using SSR

### ISSUE THREAD

**Issue by lgastler** [withastro/astro#4794]
### What version of `astro` are you using?

1.2.6

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The image component does not render images correctly in Production on Netlify using the `@astrojs/netlify` adapter. Everything works fine in dev mode but once deployed to Netlify the image endpoint fails to generate and return images, instead it throws the following error:

`The image "URL" cannot be displayed because it contains errors.` 

A deployed site using the minimal Reproducible Example can be found here: 
https://astro-image-ssr-reproduction.netlify.app/

### Link to Minimal Reproducible Example

https://github.com/lgastler/astro-image-ssr-reproduction

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nicatspark** [comment]
This seems to not work again, opening a new issue.

**Comment by ezriharmusial** [comment]
Having the Same issues also. Works in development, not in production.

**Comment by gregorysirtoli** [comment]
Same issue here, work in dev. not in prod.

**Comment by Leiloukou** [comment]
It doesn't work for me either! I created an Astro 3 app, excited for the new features, but it doesn't even work on Netlify, the best serverless provider!

And yes, I am using the Netlify adapter.

Here is a bit of my config:
```javascript
export default defineConfig({
	site: // ...
	integrations: [
		mdx(),
		sitemap(),
		prefetch({
			intentSelector: '[data-prefetch]',
			throttle: 10,
		}),
		tailwind(),
		react(),
	],
	adapter: netlify(), // This doesn't make images work!
});
```
