### ISSUE TITLE
getStaticPaths() with `undefined` slug creates actual "/undefined" route

### ISSUE THREAD

**Issue by ttntm** [withastro/astro#4796]
### What version of `astro` are you using?

1.2.4, 1.2.6

### Are you using an SSR adapter? If so, which one?

none yet

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Following the docs (https://docs.astro.build/en/core-concepts/routing/#example-dynamically-create-a-top-level-root-page) and #3990 (https://github.com/withastro/astro/issues/3990#issuecomment-1211216446) to create a top level root page via `undefined` slug renders an actual "/undefined" route.

Happens on localhost, just the same way as in the linked repro at https://withastro-astro-zoqwkc--3000.local-corp.webcontainer.io/undefined

The /undefined route can certainly be worked around using HTTP redirects in production, but generating it is probably not what should be happening in the first place.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-zoqwkc?file=src/pages/[...slug].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
I don't see this happening with the latest astro version.

**Comment by rishi-raj-jain** [comment]
<img width="1439" alt="Screenshot 2022-09-22 at 8 38 33 PM" src="https://user-images.githubusercontent.com/46300090/191784282-199d9abf-41bf-49c4-b239-08d236beca65.png">

Here's what I've in package.json:
  "dependencies": {
    "astro": "^1.2.8"
  }

**Comment by rishi-raj-jain** [comment]
I think we can close this

**Comment by rishi-raj-jain** [comment]
Even in the stackblitz attached, I don't see the undefined being created

**Comment by bluwy** [comment]
@rishi-raj-jain It looks like `/undefined` only happens in dev when you navigate to it. I've send #4873 to fix it.
