### ISSUE TITLE
bug: rendering components with `id` multiple times doesn't give error

### ISSUE THREAD

**Issue by juliusmarminge** [withastro/astro#4798]
### What version of `astro` are you using?

1.1.2

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

Rendering a component twice which contains elements with `id` doesn't cause an error (or whatever warning the devtools usually throws)

I created a Card component that renders a div with an `id` on it, and despite rendering multiple Card's i don't get an error in the dev tools.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/floral-meadow-xr7gsy?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I'm pretty sure this isn't an Astro bug. We don't prevent you from rendering the same id multiple times. You usually probably don't want to do so, although I don't think browsers try and stop you.

https://codepen.io/matthewp/pen/YzLQzaw
