### ISSUE TITLE
Tailwind custom colors don't apply

### ISSUE THREAD

**Issue by nicolas-deyros** [withastro/astro#4799]
### What version of `astro` are you using?

1.2.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

Yarn

### What operating system are you using?

Linux

### Describe the Bug

Try adding custom color to Tailwind config file and they are not loading. Try to make the colors load base on dynamic parameter of the Pokeapi
Try solution of BUG https://github.com/withastro/astro/issues/3043 but is not resolving my problem

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-r89q1e

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
https://stackblitz.com/edit/github-r89q1e-zerjbs?file=tailwind.config.cjs
