### ISSUE TITLE
Code blocks in MDX render environmental variables

### ISSUE THREAD

**Issue by ymcheung** [withastro/astro#4801]
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

Deno Deploy

### What package manager are you using?

pnpm

### What operating system are you using?

macOS 12

### Describe the Bug

I have some `import.meta.env` in MDX's code blocks and don't want them to be converted. (Just display import.meta.env.XXXXX)

In dev environment, the output is doing well.

However, `import.meta.env.SITE` becomes `undefined` (or the url I defined in `astro.config.mjs`);
`import.meta.env.PUBLIC_HOSTNAME` becomes `(Object.assign(import.meta.env,{HOSTNAME:process.env.HOSTNAME,})).PUBLIC_HOSTNAME` in production. 

### Link to Minimal Reproducible Example

https://codesandbox.io/s/vibrant-chandrasekhar-gbicwd?file=/src/pages/article1.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for reporting @ymcheung! Looks like we're missing our environment variable handling in MDX that we use for standard Markdown. Will PR that fix 👍
