### ISSUE TITLE
`astro add` with a custom package adds `/` to the import

### ISSUE THREAD

**Issue by mayank99** [withastro/astro#4808]
### What version of `astro` are you using?

1.2.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Running `npx astro add @tokencss/astro` leads to this config (notice the slashes):
```js
import { defineConfig } from 'astro/config';

import tokencss/ from "@tokencss/astro";

export default defineConfig({
  integrations: [tokencss/()]
});
```

Related issue: https://github.com/tokencss/tokencss/issues/11

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Yep, mind submitting a PR @mohammed-elhaouari or @mayank99 ?
