### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token '?' 

### ISSUE THREAD

**Issue by henryhu712** [withastro/astro#4812]
### What version of `astro` are you using?

1.2.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I built and deployed [my site](http://dalanshu.com/en/introduction/). But my old Chrome did not show correctly and reported errors when displaying it:

> Uncaught (in promise) SyntaxError: Unexpected token '?' 
> Uncaught (in promise) SyntaxError: Unexpected token '.'

My chrome version is 78.0.3904.108.

### Link to Minimal Reproducible Example

http://dalanshu.com/en/introduction/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
The error is due to optional chaining not supported.

Similar to https://github.com/withastro/astro/issues/4716, Astro doesn't support older browsers. Features like `:where` also isn't supported in Chrome 78 so css scoping wouldn't work properly. Closing as this for now.
