### ISSUE TITLE
Image: Local images from public need size attributes

### ISSUE THREAD

**Issue by panwauu** [withastro/astro#4814]
### What version of `astro` are you using?

1.2.6

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

In the [docs](https://docs.astro.build/de/guides/integrations-guide/image/) under width we can read:
> Dimensions are optional for local images, the original image size will be used if not provided.
>
> For remote images, the integration needs to be able to calculate dimensions for the optimized image. This can be done by providing width and height or by providing one dimension and an aspectRatio.

But since local images from public are loaded like remote images this is not the case anymore for local images in public. I think this feature would be really nice to be added again. I personally would like to use it.
Ideally we could specify nothing (-> keep size) or either width or height (-> keep aspectRatio of original)).

### Link to Minimal Reproducible Example

.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Hey @panwauu, this is actually expected bevhavior ([docs here](https://www.npmjs.com/package/@astrojs/image#user-content-images-in-public))

Images in `/public` are treated aren't part of the build at all, they're treated like a remote image that just happens to be hosted on the same domain.  This one's a bit confusing for sure, we tried to cover it in the docs but let us know if there's a better way we can call this out in the docs 👍

**Comment by panwauu** [comment]
Seems absolutely reasonable. Thanks for the clarification
