### ISSUE TITLE
No assets folder when outDir outside cwd

### ISSUE THREAD

**Issue by rob-gordon** [withastro/astro#4825]
### What version of `astro` are you using?

1.2.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I have a pnpm monorepo containing an astro app in one folder and a create-react-app in another.
My goal is to build the create-react-app, then build the astro app into a subfolder of the built create-react-app.

For the most part, this works fine. The only problem is that the `public` folder isn't copied into the `outDir` destination, so images and css 404 on the deployed site.

### Link to Minimal Reproducible Example

https://github.com/rob-gordon/nested-astro-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
does changing it to join(process.cwd(), 'build') get it done?

**Comment by rishi-raj-jain** [comment]
Taking this up!

**Comment by rob-gordon** [comment]
@rishi-raj-jain thanks for the fast fix! 🙏🏻

**Comment by rishi-raj-jain** [comment]
@rob-gordon My pleasure!
