### ISSUE TITLE
Can I use getStaticPaths with  output: 'server', ?

### ISSUE THREAD

**Issue by akirawinz** [withastro/astro#4827]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

Verlce

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I'm currently looking in this theme https://hellotham.github.io/hello-astro/ 

the problem is when I try to setup deploy by using Vercel which I add these in astro.config

```
  output: 'server',
  adapter: vercel(),
```

after that I run `yarn dev`

and enter into /blog page

the error show up 

`Cannot read properties of undefined (reading 'size')`

Here is an blog page code

https://github.com/hellotham/hello-astro/blob/main/src/pages/blog/%5B...page%5D.astro

I'm not sure, Does output: 'server', allow to deployed with getStaticpath? 

### Link to Minimal Reproducible Example

https://github.com/hellotham/hello-astro/blob/main/src/pages/blog/%5B...page%5D.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hi, you don't need to use getStaticPaths because all paths are dynamic in SSR. Just read directly from `Astro.props` to get the value.

**Comment by akirawinz** [comment]
thank you @matthewp
