### ISSUE TITLE
Adding `define:vars` to script tag will break imported client scripts

### ISSUE THREAD

**Issue by markpinero** [withastro/astro#4835]
### What version of `astro` are you using?

1.2.8

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Adding variables to a script tag will add a block scope to the script and break all imports.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hmu6p8

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is intended, see the Caution tip on this page: https://docs.astro.build/en/reference/directives-reference/#definevars
