### ISSUE TITLE
Radix React component in MDX file does not render properly

### ISSUE THREAD

**Issue by callumflack** [withastro/astro#4838]
### What version of `astro` are you using?

^1.2.6

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Adding the [Radix UI Hover Card](https://www.radix-ui.com/docs/primitives/components/hover-card) component to an `.mdx` file does not render the children of `HoverCard` correctly. It renders the default "toString" representation (ie. `[Object object]`).

The context is important here: I am attempting to show this card on an inline string within a paragraph. You'll notice to use of `p` and `span` tags to create this.

When I tested locally, it looked like the children being passed to `HoverCard` was an array of Astro stuff, not just the child value on the page. (I can't screenshot that right now).

In the Stackblitz terminal, it gives console errors for unclosed tags, although they are none and the page renders. 

<img width="894" alt="image" src="https://user-images.githubusercontent.com/749885/191688190-b3b5ec08-0408-40c6-8dd1-4b50807f7667.png">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xnawl8-ryclcm?file=src%2Fpages%2Ftest.mdx,src%2Flib%2FHoverCard.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by callumflack** [comment]
Possibly related: https://github.com/withastro/astro/issues/4826

**Comment by bholmesdev** [comment]
Hey @callumflack! Looks like it was just a versioning issue. I noticed you're using early versions of the React and Preact integrations. You can bump them with:

```shell
npm i @astro/react@latest @astro/preact@latest
```

[See my fork](https://stackblitz.com/edit/github-xnawl8-uhck5r?file=src/pages/index.mdx) for a working example. Let me know if that works for you and I'll close the issue! Also, say hi to Joseph C for me 😉

**Comment by callumflack** [comment]
Ah nice, thanks @bholmesdev !

I manually updated the package version. If I install `@astro/react@latest` with either `pnpm` or `npm`, it fails? What is the correct syntax for running `@latest` updates?

Shall pass on your regards to Mr C 🫡

**Comment by bholmesdev** [comment]
@callumflack Ah, sorry for the typo! Should be `@astrojs/react@latest` 👍

**Comment by callumflack** [comment]
Thanks heaps @bholmesdev! Keep doing those videos. Decided to use Astro for my site revision — it's kinda too easy ⚡️
