### ISSUE TITLE
Build issue deletes everything when config is set to `outDir: './'`

### ISSUE THREAD

**Issue by j3rech0** [withastro/astro#4844]
### What version of `astro` are you using?

1.2.8

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

windows 11

### Describe the Bug

If you set `outDir: './'` on `astro.config.mjs` and then run `npm run build` all the files inside your project will be deleted. 😲

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-enk8fb?file=package-lock.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Oops, we should almost definitely abort in that situation shouldn't we.
