### ISSUE TITLE
`@preact/signals` not supported out of the box

### ISSUE THREAD

**Issue by natemoo-re** [withastro/astro#4856]
### What version of `astro` are you using?

16+

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

After installing `@preact/signals`, I needed to manually update my config to ensure `@preact/signals` is not externalized by Vite.

```js
export default defineConfig({
  vite: {
    ssr: {
      noExternal: ['@preact/signals', 'preact', 'preact-render-to-string']
    }
  }
})
```

Repro works in StackBlitz but not locally

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-a863zh?file=src%2Fcomponents%2FCounter.tsx,astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
You know what... I tried this yesterday and it didn't work. I tried it today and it worked. Maybe the new release of `@preact/signals` fixed this?

**Comment by matthewp** [comment]
We're going to revert https://github.com/withastro/astro/pull/4843 and update the preact/signals version there. It should be working once we do that.
