### ISSUE TITLE
Script with innerHTML not working on Safari

### ISSUE THREAD

**Issue by aleksastojsic** [withastro/astro#4859]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows, but the issue is on iOS mobile

### Describe the Bug

Trying to get a simple message displayed in the footer saying "Have a great {currentDay}" in my Footer astro component.

In doing so, I first tried writing the function for getting the current day in the Component Script part (---)  and that didn't work, it would only get the day when the site was built and deployed, which is as I understand the expected outcome.

Then I realized I should probably run that script on the client side because I need the current day to be updated daily, so I used the `<script>` tag with the same function and injected the text with `.innerHtml` .  That got the desired outcome and the days were updating as expected, everything was working on Desktop browsers. But when I opened the site on my iPhone, both Safari and Chrome (everything is Safari on iPhone) the message wasn't there.

edit: I've tried `.innerText` instead of `.innerHtml`, still not working on Safari.

The reproduction of the problem below now uses `set:html` but my guess is it won't update the current day tomorrow, as with using the Component Script part. I left the client-side script that was not working on Safari commented out.

### Link to Minimal Reproducible Example

https://github.com/aleksastojsic/astro-portfolio/blob/main/src/components/Footer.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
Does it work in other browsers well? Would it be possible to share a deployed URL?

**Comment by aleksastojsic** [comment]
On desktop yes, I've tested it on all the browsers. I changed the code from using the `set:html` to the `<script>` with `.innerHtml` now, so it should be available on https://aleksa.codes at the bottom. Do you know if `set:html` with the function would also run only on build time as using the Component Script part (---) ?

**Comment by rishi-raj-jain** [comment]
@aleksastojsic Hey I just tried it and on desktop it fails to load on Safari

**Comment by rishi-raj-jain** [comment]
Looks more like a Safari issue

**Comment by rishi-raj-jain** [comment]
<img width="1440" alt="Screenshot 2022-09-24 at 4 41 56 PM" src="https://user-images.githubusercontent.com/46300090/192094720-bf94fa2b-fd32-4e2c-8176-3e4d0fccf80e.png">

the error

**Comment by rishi-raj-jain** [comment]
So what's happening is that define:vars produces the variable with `let variable` which is not supported with Safari: https://stackoverflow.com/questions/29194024/cant-use-let-keyword-in-safari-javascript

**Comment by rishi-raj-jain** [comment]
Okay attempting a fix

**Comment by aleksastojsic** [comment]
Great find. Not sure if related but TypeScript did throw me this:

![Untitled](https://user-images.githubusercontent.com/64015178/192095187-9c46236a-3ccd-41f8-b52d-47efcbde3c14.png)

**Comment by aleksastojsic** [comment]
Upgraded to `astro@1.3.1` and the message is still not there on Safari, and getting the "Could not find 'days'." as in the image above.

**Comment by rishi-raj-jain** [comment]
@aleksastojsic So I get why this issue issue still exists. Now this is occuring because of the extra { } sent while using define:vars. Doing a quick PR for it.

**Comment by rishi-raj-jain** [comment]
Though addition of those extra {} results in the error only in safari, and not on other browsers.

Simple reproduction:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      {
        const days = ["1"];
        function getDay() {
          return days[0];
        }
        console.log(getDay());
      }
    </script>
  </body>
</html>
```

Would throw console error in safari while work in chrome

**Comment by aleksastojsic** [comment]
@rishi-raj-jain Should I open another issue? I feel like this is important to fix.
