### ISSUE TITLE
Nested anchor tags break element flow

### ISSUE THREAD

**Issue by EthanStandel** [withastro/astro#4864]
### What version of `astro` are you using?

1.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

MacOS

### Describe the Bug

If you nest an anchor tag inside another anchor tag, the outer tag takes it's children out and renders them as if they are its sibling.

An example use-case of this, would be on a blog post link-card. The card itself is an anchor (so the whole thing is clickable), but then you may have category links in the card that will lead to a page that lists all posts under that category. The styling and accessibility of this can be tricky... but this rendering behavior makes it quite litterally impossible using Astro components.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vhnc6s?file=src%2Fcomponents%2FCard.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
@EthanStandel I don't think that's the case. If you remove the .link > a style in the basics template, you're good to go there.
https://stackblitz.com/edit/github-vhnc6s-c2zwef?file=src/components/Card.astro

**Comment by rishi-raj-jain** [comment]
<img width="1438" alt="Screenshot 2022-09-24 at 10 48 55 PM" src="https://user-images.githubusercontent.com/46300090/192110700-c3d320a5-3baa-4f14-9000-c11b2c448816.png">

Attached is the build output that shows it's rendered as children only.

**Comment by EthanStandel** [comment]
@rishi-raj-jain 

![image](https://user-images.githubusercontent.com/16840301/192113727-2785d2fe-3c98-4b30-b691-234e8e5b8dab.png)

If you look at the DOM output, the anchor tags are adjacent, when the code chows that they should be side-by-side.

**Comment by rishi-raj-jain** [comment]
@EthanStandel hey can you try this on local? Even with my Stackblitz, I'm seeing what you said above, but locally, I'm able to see the dom nodes as expected.

**Comment by X7md** [comment]
Nested `<a>` break HTML rules.

https://stackoverflow.com/a/18667146

Technically you can't have nested `<a>` tags.

**Comment by X7md** [comment]
For this use case, in my opinion you need to use a `<button data-url={post.link}>`

![Screenshot_20220924-224717_Chrome](https://user-images.githubusercontent.com/54203033/192115895-72c1b154-aa8d-42e3-a3a9-73b59115be54.jpg)

Do something like this:

https://github.com/X7md/x7md.github.io/blob/main/src/components/Tag.astro

and:

https://github.com/X7md/x7md.github.io/blob/main/src/components/Card.astro

Like you see

`@click` in my code is just inline JavaScript with petite-vue, but you can use normal JavaScript to do the same workaround.

**Comment by X7md** [comment]
You can preview the click behavior here:

x7md.github.io/posts/

**Comment by EthanStandel** [comment]
@rishi-raj-jain Yeah, it was happening initially on my local

@X7md thank you! I guess I won't do this in my application, but I still think it's worth keeping this bug open because I think it's a hint to some other problematic behavior. If Astro were to give me an error here, I would be fine with that behavior, but because it resorts the nodes, I think it's still worth being addressed.

**Comment by EthanStandel** [comment]
@X7md Oh dang! This isn't an Astro problem in any way! The browser just does this!

@rishi-raj-jain You may not have seen this behavior if you checked the SSR/SSG output from Astro, but the browser actually ejects the internal anchor. This is entirely my bad, closing!

**Comment by rishi-raj-jain** [comment]
Learning for me as well, @EthanStandel!
