### ISSUE TITLE
Lookbehind regex crashing on Safari

### ISSUE THREAD

**Issue by marcoseiza** [withastro/astro#4865]
### What version of `astro` are you using?

1.3.0

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

File [`src/runtime/server/render/util.ts`](https://github.com/withastro/astro/blob/f8c2d828bd6fd15fabac334a489d1c3ab7e2d209/packages/astro/src/runtime/server/render/util.ts) uses the following regex with lookbehind `/(?:(?<!^)\b\w|\s+|[^\w]+)/g`, which is [not supported](https://caniuse.com/js-regexp-lookbehind) on Safari.

My code [https://github.com/marcoseiza/PersonalWebsite#personal-website](https://github.com/marcoseiza/PersonalWebsite#personal-website).

Live Website With problem (Not permanent) [https://meizayaga.com/blog](https://meizayaga.com/blog)

### Link to Minimal Reproducible Example

https://meizayaga.com/blog

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
@marcoseiza That as says, runs on the server but not the browser.

**Comment by marcoseiza** [comment]
How do I fix this in safari then? The live site with netlify SSR is not working.

**Comment by rishi-raj-jain** [comment]
@marcoseiza What's the problem you're facing?

**Comment by rishi-raj-jain** [comment]
Ah, you're right, it occurs on the client side with Safari.

**Comment by rishi-raj-jain** [comment]
@bluwy @matthewp @marcoseiza 

Re-opened the PR.

Steps to reproduce:
- Open https://meizayaga.com/blog in Chrome
- Open https://meizayaga.com/blog in Safari
- The blogs don't load and the JS points to the error as the issue created for
