### ISSUE TITLE
Error while building using cloudflare adapter

### ISSUE THREAD

**Issue by nirus** [withastro/astro#4869]
### What version of `astro` are you using?

^1.1.3

### Are you using an SSR adapter? If so, which one?

cloudflare

### What package manager are you using?

yaran

### What operating system are you using?

Mac

### Cloudflare adapter build error if import node deps in the astro code.

Followed the [documentation](https://docs.astro.build/en/guides/integrations-guide/cloudflare/)

But i am getting the error during build command astro build as shown in the error screenshot.

<img width="531" alt="Screenshot 2022-09-25 at 10 47 20 PM" src="https://user-images.githubusercontent.com/2213751/192168080-8ecc0a91-2b79-45e3-85bf-65bfa81c6656.png">

After going through the terminal window log bubbling from /node_modules/esbuild/lib/main.js

and searching web on the error i guess i have to build the webapp using --platform=node flag. But i am not sure how and where to pass it to the vite config.

Can you please point me in the right direction!

### One possible solution:

Adding `platform: "node"` on this [line](https://github.com/withastro/astro/blob/32f489b13689929ce115d07e56136abc549e98b6/packages/integrations/cloudflare/src/index.ts#L80) fixed the errors. 

But couldn't preview with `wrangler pages dev --node-compat=true --local=true ./dist `

** Attached the stackblitz example with this bug report.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-z3z4j7

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by AirBorne04** [comment]
Hi @nirus , 
there was an update to this package, can you try `@astro/cloudflare: 2.0.0`, since this was addressing a similar issue?

**Comment by bluwy** [comment]
This is expected as the Cloudflare worker environment doesn't support modules like `fs`, `path`, etc. You have to avoid importing those modules or deps that import those modules when deploying to Cloudflare.

**Comment by gz-ns** [comment]
@AirBorne04 is there a strong reason to have the platform property set to `neutral` [here](https://github.com/withastro/astro/commit/ce0b92ba73072c0f0143829a53f870155ad4c7ff#diff-2039ec525c2c4d3855197c5d569ef62e843bfb2fe2bc614b206bf541a3d9a46cL80)? I'm getting probably similar issue with react ssr, as it attempts to load the `node` variant instead of `browser`. Setting it back to browser fixes it and worker is created as expected.

<img width="821" alt="Screenshot 2022-09-26 at 12 52 37" src="https://user-images.githubusercontent.com/92586825/192258997-600763e5-a535-4e0c-9e38-bdd65dddef8b.png">

**Comment by germanz** [comment]
@AirBorne04 is there a strong reason to have the platform property set to `neutral` [here](https://github.com/withastro/astro/commit/ce0b92ba73072c0f0143829a53f870155ad4c7ff#diff-2039ec525c2c4d3855197c5d569ef62e843bfb2fe2bc614b206bf541a3d9a46cL80)? I'm getting probably similar issue with react ssr, as it attempts to load the `node` variant instead of `browser`. Setting it back to browser fixes it and worker is created as expected.

<img width="780" alt="Screenshot 2022-09-26 at 12 58 17" src="https://user-images.githubusercontent.com/2526045/192259927-08cd18fd-8821-4c6a-b73e-c42072a4e640.png">

**Comment by nirus** [comment]
so `node-fetch` for any kind of reverse proxy usecase doesn't work?. _Like for example - hide api keys to certain 3rd party api calls and make reverse connection through the SSR.._

In my **stackblitz** example `/api` under `pages/api.ts` makes an API call to fetch a simple data. 

Implementing [this](https://docs.astro.build/en/guides/server-side-rendering/#ssr-and-routes) (**recaptcha example**) using cloudflare adapter is not possible?

**Comment by AirBorne04** [comment]
@gz-ns the reason to go with neutral here was to avoid a misleading config as `browser` seems as incorrect as `node` because it should be `worker`. Instead I added the following props
```
mainFields: ['main', 'module'],
conditions: ['worker', 'node'],
```
where conditions are the key part for which files should be imported. Running through the docs of `esbuild` again it seems there is one more effect of the platform, preferring the `browser` mappings.

**Comment by AirBorne04** [comment]
> so `node-fetch` for any kind of reverse proxy usecase doesn't work?. _Like for example - hide api keys to certain 3rd party api calls and make reverse connection through the SSR.._
> 
> In my **stackblitz** example `/api` under `pages/api.ts` makes an API call to fetch a simple data.
> 
> Implementing [this](https://docs.astro.build/en/guides/server-side-rendering/#ssr-and-routes) (**recaptcha example**) using cloudflare adapter is not possible?

In cloudflare workers you are using `fetch` directly, no need for `node-fetch`.

**Comment by AirBorne04** [comment]
@nirus I am not a guru on that particularly but it seems isomorphic is the way to go, or [workers compatible page](https://workers.cloudflare.com/works) is a place to check additional supported libraries.

**Comment by germanz** [comment]
> @germanz the reason to go with neutral here was to avoid a misleading config as `browser` seems as incorrect as `node` because it should be `worker`. Instead I added the following props
> 
> ```
> mainFields: ['main', 'module'],
> conditions: ['worker', 'node'],
> ```
> 
> where conditions are the key part for which files should be imported. Running through the docs of `esbuild` again it seems there is one more effect of the platform, preferring the `browser` mappings.

@AirBorne04 without setting `browser` my app is screwed :( as it tries to bundle the node deps from `react-dom`. Any suggestions how to override it from the outside? 

I understand your point, but according to esbuild docs, there is no `worker` platform, so the closest we have is browser... I could create a PR and switch it back to `browser` if that's fine and won't break another use case.

**Comment by nirus** [comment]
> workers compatible page

Perfect. Thats helpful if its mentioned on the documentation page.

Also i guess some kind of prop exposed to overside the esmbuild option would be a good option too!

**Comment by AirBorne04** [comment]
> @AirBorne04 without setting `browser` my app is screwed :( as it tries to bundle the node deps from `react-dom`. Any suggestions how to override it from the outside?

reverting it back actually breaks my stack. did you try to adjust the settings like so

```
platform: "neutral",
mainFields: ["browser", "module", "main"],
```

**Comment by germanz** [comment]
Didn't help :(

**Comment by matthewp** [comment]
Thanks for all of the research! We could also make `platform` an option for the adapter, that way people can customize this.

**Comment by AirBorne04** [comment]
> Didn't help :(. What's your stack Astro + Solid in SSR?
> 
> _Update._ Removing the platform altogether and letting esbuild to figure out also seems to help. Is it an option for you?

Yes I am running solid in ssr mode. The default value of platform is `browser` , therefore it is still broken with solid js. Can you make a stackblitz for your config, I just want to play around a little.

@matthewp I would have liked to get a setting together, without the need to document different behaviors, but maybe a warning for those configs that we know is useful.

**Comment by AirBorne04** [comment]
I did some more digging around. The platform field should definitely be `browser` for the `esbuild`. In addition I would make a little adjustment to the `vite settings` to respect the user config for the ssr settings.

 This way the adapter is building 2 steps.

1. vite ssr build which is building the framework
    - target (default: `webworker`), but for solid it can be overridden by `node`
    - noExternal, can be used to bundle packages for the `node` build
    - external, can be used to move a package to the second build step
2. esbuild bundle which is bundling the rest
    - bundles the rest of the external files for the `browser` platform

prepared a PR #4888

**Comment by germanz** [comment]
Here is the Stackblitz setup. Try executing `npm run build`, you'll see errors:
```
  node_modules/react-dom/cjs/react-dom-server.node.development.js:18:21: ERROR: Could not resolve "stream"
  node_modules/react-dom/cjs/react-dom-server.node.production.min.js:9:74: ERROR: Could not resolve "stream"
```

https://stackblitz.com/edit/github-z3z4j7-hramha?file=astro.config.mjs

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/4888
