### ISSUE TITLE
Using `npm run dev --host` doesn't expose to network

### ISSUE THREAD

**Issue by caincodes** [withastro/astro#4870]
### What version of `astro` are you using?

1.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Running `npm run dev --host` doesn't expose the site to the network. Note that `astro dev --host` works, but I don't have astro installed **globally** on my machine -- and that shouldn't be a requirement, right? This should be reproducible on any site with astro@1.3.0 installed. Reproducible example is a link to a new minimal astro project on stackblitz. 

### Link to Minimal Reproducible Example

https://astro.new/minimal?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You need to run `npm run dev -- --host` instead as that's npm's way of passing CLI args to the underlying binary.
