### ISSUE TITLE
Cannot access dev server on iOS via ip

### ISSUE THREAD

**Issue by nemdo** [withastro/astro#4882]
### What version of `astro` are you using?

1.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows, iOS

### Describe the Bug

I cannot access the dev server on iOS via http://my-ip-address:3000.

It does not work with --host or --host [custom-address], in both cases it always gives me the following result, no matter what:
```
   astro  v1.3.0 started in 138ms  
  
  ┃ Local    http://127.0.0.1:3001/
  ┃ Network  use --host to expose 
```

I tested with both home wifi and iOS hotspot, all popular iOS browsers and followed many different tutorials, but nothing works. Note that I can still access the dev server on iOS of any Next.js app in any of those situations.

**Comment by nemdo** [comment]
It finally worked after deleting node_modules and package-lock.json and adding --host directly in the script command in package.json. For some reason, it worked this time even though I repeated that exact same process many many times.

**Comment by bluwy** [comment]
Make sure you use `npm run dev -- --host` too instead of `npm run dev --host`
