### ISSUE TITLE
@astrojs/image outputs the source file to /dist folder on astro build instead of just the transformed image.

### ISSUE THREAD

**Issue by supermoos** [withastro/astro#4896]
### What version of `astro` are you using?

1.3.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

https://docs.astro.build/en/guides/integrations-guide/image/ - the package works great for transforming images, however it also copies the source image into the /dist folder which at the very least should probably be optional, if not off by default. Is there a way to do this? The examples here will all copy the source image in addition to the transformed versions of the image to the /dist folder: https://docs.astro.build/en/guides/integrations-guide/image/#local-images

Try and run 'npm run build' in the provided minimal repo locally, and you'll see this output which wrongly contains the source file too.
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/2298345/192751602-220a5766-9ac6-4561-857d-9f76d3929eaf.png">

### Link to Minimal Reproducible Example

https://codesandbox.io/s/throbbing-butterfly-2is8ef?file=/sandbox.config.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by panwauu** [comment]
Possible duplicate #4961
