### ISSUE TITLE
Hydration mismatch since 1.3.0

### ISSUE THREAD

**Issue by ElMatella** [withastro/astro#4900]
### What version of `astro` are you using?

1.3.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Hi, since 1.3.0, I'm having a bug with SSR and VueJS. It only happens on rather long pages.

Take this Astro component:
```astro
---
import Layout from '../layouts/Layout.astro';
import SomeComponent from '../components/SomeComponent.vue'
---

<Layout title="Welcome to Astro.">
  <main>
    <SomeComponent client:load></SomeComponent>
  </main>
</Layout>
```
And this Vue component:
```vue
<template>
  <div>
    <div v-for="i in 10000">
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    </div>
    <div v-for="i in 5">
      Hello World!
    </div>
  </div>
</template>
```

From 1.3.0, the page takes a really longer time to generate, and results in a hydration mismatch on the client:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/7662722/192776331-ccd72bd1-086d-430c-a488-c24d38ce6d6f.png">
<img width="729" alt="image" src="https://user-images.githubusercontent.com/7662722/192776427-c10c3044-1419-4ac0-9854-1c1cdf19d519.png">

When switching back to `1.2.8` with `npm install astro@1.2.8 --save-exact`, the mismatch error disappear and the page takes significantly less time to generate:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/7662722/192776799-035e9c87-cc08-430e-8e60-bfdb04820871.png">

Because I use rather long HTML pages, I can't upgrade to `1.3.*` and I'm stuck to `1.2.8`. 

To reproduce, please clone the repo, and run:
```
npm install
npm run build
node server.mjs
```
Then to see how it worked before, type:
```
npm install astro@1.2.8 --save-exact
npm run build
node server.mjs
```

Thank you very much for your time, and thank you for your amazing work :)

Reproduction: https://github.com/ElMatella/astro-ssr-bug

### Link to Minimal Reproducible Example

https://github.com/ElMatella/astro-ssr-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by AirBorne04** [comment]
I have a similar issue and i hunted it down to this [line](https://github.com/withastro/astro/blob/778dce8c0529f6562f332d546ce5ab87702dcbe4/packages/astro/src/runtime/server/render/common.ts#L72) where the comparison is checking for string, but if it is HTMLString (what it is in my case) it is just jumping over it and the array buffer stays empty for the hydration script.

**Comment by AirBorne04** [comment]
i would recommend a change to something like this.
```
if (ArrayBuffer.isView(part)) {
    this.parts[i] = part;
  }
  else {
    this.parts[i] = encoder.encode(String(part));
  }
```

this mirrors (invert) the behavior of the `.toString` method of the same object.

**Comment by matthewp** [comment]
Thanks @AirBorne04 for doing the research!

**Comment by ElMatella** [comment]
Hey, thank you for handling this issue but unfortunately the initial problem does not seem to be fixed. I think I identified an even smaller reproduction, I'll try to update this or I'll just create an other issue, as you wish.
Thank you again and have a nice week-end

**Comment by ElMatella** [comment]
Also, note on my reproduction repository, that with the same code:

- Astro 1.2.8: Renders a 934kB document
- Astro 1.3.0: Renders a 5.6MB document

Do you know what could cause such a thing?

**Comment by matthewp** [comment]
Oh wow, no but that's very interesting. 1.3.0 introduced the ability to stream responses in the template. I'm guessing this is the culprit (and also the perf regressions reported)

**Comment by matthewp** [comment]
I think I've tracked down the problem here, working on a fix.

**Comment by matthewp** [comment]
Have a preview release for this:

```
npm installl astro@ next--perf-2
```

Will test in your repo.

**Comment by matthewp** [comment]
No more mismatch from my testing.

**Comment by ElMatella** [comment]
Houray! Looks perfect, thank you very much! I'll look at the pull request, would love to contribute some day. Have a very nice day or night.
Cheers

**Comment by carlos00027** [comment]
I've that problem but I use Vue 3

```
// my-page.astro
 <Carrito client:load />
```

```
const getItemsSelected = readonly(computed(() =>  itemsSelected.value))
```

```
<BtnPrimary
        :disabled="getItemsSelected.length === 0"
        @click="onClickContinuar"
        >
          Continuar la compra
        </BtnPrimary>
```

**Comment by enavarrocu** [comment]
> [@carlos00027](https://github.com/carlos00027) replace
> 
> `<Carrito client:load />` ↓ `<Carrito client:only="vue" />`

This worked for me, thanks :)
