### ISSUE TITLE
import of files with capitalized filename extension fails (.JPG, .PNG instead of .jpg or .png)

### ISSUE THREAD

**Issue by supermoos** [withastro/astro#4901]
### What version of `astro` are you using?

1.3.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Perhaps the image asset filename extensions should be case insensitive?

Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .JPG file format, or if it's an asset, add "**/*.JPG" to `assetsInclude` in your configuration.
  File:
    /src/assets/media/400/IMG_0042.JPG

### Link to Minimal Reproducible Example

https://codesandbox.io/s/prod-currying-xl9uql?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Seems like this is a Vite issue. Please file an issue there. In the meantime you can use the `assetsInclude` config.
