### ISSUE TITLE
Unexpected blank line before text using embedding expression

### ISSUE THREAD

**Issue by arthur-fontaine** [withastro/astro#4908]
### What version of `astro` are you using?

1.3.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

If a blank line is added before an embedding expression, the HTML output will include an unexpected blank line before the text.

```jsx
<p>
    {text.split('').map((char) => (
        <span>{char}</span>
    ))}
</p>
```
The blank line between the opening `<p>` tag and the `{text.split('')...` line is automatically added by some formatters.

Using React ([stackblitz example](https://stackblitz.com/edit/unexpected-blank-line-before-the-text-react-example?file=App.tsx)), the blank line is not added.
For both examples (React and Astro), I logged the `textContent` of the `p` element.

 - React:
    ```
    "Bonjour everybody tout le monde !"
    ```

 - Astro:
    ```
    "\n        Bonjour everybody tout le monde !\n      "
    ```
    
With `white-space: pre-line` on the `p` tag, it causes an unexpected rendering.

<img width="1512" alt="Capture d’écran 2022-09-28 à 22 46 15" src="https://user-images.githubusercontent.com/57626613/192885349-e2263df3-24f0-45e9-a52d-021a2e1cc0f3.png">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/unexpected-blank-line-before-the-text?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @arthur-fontaine, Astro is different here from JSX and preserves whitespace, like HTML does. That's why if you look at the raw output all of your indentation remains.

This is intentional.
