### ISSUE TITLE
Can't create project with yarn [modern] dlx

### ISSUE THREAD

**Issue by nickmccurdy** [withastro/astro#4923]
### What version of `astro` are you using?

1.4.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Using yarn dlx (the yarn modern version of yarn/create) leads to a package installation error:
```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 1s 365ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 1s 539ms

/private/var/folders/2t/t4byzhn576n41yk4yqzx3tsw0000gn/T/xfs-6b77a3cd/dlx-26562/.pnp.cjs:9004
  return Object.defineProperties(new Error(message), {
                                 ^

Error: chalk tried to access #ansi-styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: #ansi-styles (via "#ansi-styles/package.json")
Required by: chalk@npm:5.0.1 (via /Users/nick/.yarn/berry/cache/chalk-npm-5.0.1-6afcb94227-8.zip/node_modules/chalk/source/index.js)

    at makeError (/private/var/folders/2t/t4byzhn576n41yk4yqzx3tsw0000gn/T/xfs-6b77a3cd/dlx-26562/.pnp.cjs:9004:34)
    at resolveToUnqualified (/private/var/folders/2t/t4byzhn576n41yk4yqzx3tsw0000gn/T/xfs-6b77a3cd/dlx-26562/.pnp.cjs:9923:21)
    at Object.resolveToUnqualified (/private/var/folders/2t/t4byzhn576n41yk4yqzx3tsw0000gn/T/xfs-6b77a3cd/dlx-26562/.pnp.cjs:10067:26)
    at resolve$1 (file:///private/var/folders/2t/t4byzhn576n41yk4yqzx3tsw0000gn/T/xfs-6b77a3cd/dlx-26562/.pnp.loader.mjs:224:31)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.10.0
```

### Link to Minimal Reproducible Example

```
yarn dlx create-astro
```

### Participation

- [x] I am willing to submit a pull request for this issue.

### Workaround

Create the project with `yarn create` and then upgrade to yarn modern with `yarn set version stable`.

**Comment by mandar1jn** [comment]
This is actually an issue with yarn/chalk/both and not an issue with Astro itself https://github.com/chalk/chalk/issues/531 https://github.com/yarnpkg/berry/issues/3879

**Comment by nickmccurdy** [comment]
@matthewp I'm aware that yarn resolutions can be used as a workaround, but as far as I'm aware there isn't a way to use this with `yarn dlx` globally. If you have a workaround can you please explain?

@mandar1jn It seems like `chalk` isn't ideal for projects using ESM in `package.json`. Could we `picocolors` instead? It's used by Vite, it's smaller, it's faster, and it supports PNP.

**Comment by mandar1jn** [comment]
Replacing chalk with an alternative that supports pnp would indeed work. Also, you’d indeed need to replace ora if it uses chalk

**Comment by nickmccurdy** [comment]
Do you have any receommendations for progress libraries?

**Comment by mandar1jn** [comment]
no I don't sadly

**Comment by mrienstra** [comment]
You can try yarn v4, [`yarn set version canary`](https://yarnpkg.com/cli/set/version), more details here:
https://github.com/chalk/chalk/issues/553#issuecomment-1262833300
... though huh, `yarn set version canary` isn't global, so... Oh yeah, corepack:
`corepack prepare yarn@canary --activate`
as per https://nodejs.org/docs/latest-v18.x/api/corepack.html#upgrading-the-global-versions
(gotta open a PR to add that to the [yarn install docs](https://yarnpkg.com/getting-started/install))

**Comment by matthewp** [comment]
Closing per https://github.com/withastro/astro/issues/4923#issuecomment-1264353444, not an issue with Astro.

**Comment by mrienstra** [comment]
Work around, as per [Corepack docs](https://github.com/nodejs/corepack#corepack-binary-nameversion--args):

```sh
corepack yarn@3.2.4 dlx create-astro
```
