### ISSUE TITLE
React Children are always passed as a single object

### ISSUE THREAD

**Issue by pReya** [withastro/astro#4926]
### What version of `astro` are you using?

1.30.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Inside an .astro file, whenever passing child elements to a React component, they will always be bundled inside of a single object instead of separate objects per child.

```
---
import Wrapper from '../components/Wrapper';
---

<html lang="en">
	<body>
		<Wrapper client:load>
			<p>Child 1</p>
			<p>Child 2</p>
			<p>Child 3</p>
		</Wrapper>
	</body>
</html>

```

This is the parent wrapper component:

```tsx
import React, { Children } from 'react';

export default function Wrapper({ children }: { children: React.ReactNode }) {
  console.log('Children', children);
  return <div>I have {Children.count(children)} children</div>;
}
```

In theory, the `Wrapper` should receive an array of 3 children. Instead, it only ever receives one child. I'd love to know if this is wanted behavior/unavoidable or if this is actually a bug?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fedzey?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is unavoidable. Astro isn't JSX, so all of your `<p>` children are not separate "instances", it's just one chunk of HTML in a string.

**Comment by matthewp** [comment]
Since this is not something we can change, closing, happen to continue discussing however.

**Comment by CreaDisc** [comment]
@matthewp Is there a way to work around this?
