### ISSUE TITLE
getStaticPaths() incorrectly marked as not found

### ISSUE THREAD

**Issue by mandar1jn** [withastro/astro#4929]
### What version of `astro` are you using?

1.4.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

I was creating a posts page based on [this](https://github.com/ixartz/Astro-boilerplate) example.

Weirdly, I kept getting the error that getstaticPaths() was not exported while it clearly was. So, I copied the code over and adapted it to my project. Weirdly enough, it now worked. I used an online website to compare and the only differences were whitespaces and using " instead of ' for the includes. 

I created a stack blitz project from the basic example and pasted an adapted version of my code. I still got the same error. So, I forked it and pasted it in the known working code and there were no issues. Here is a screenshot of the diff between those files. The left is broken right is working.
![image](https://user-images.githubusercontent.com/49076509/193295704-0d8a6b44-2eae-40dc-8fe0-aa656fd3c6b1.png)

As stated, no differences except whitespace and quotes. To rule it out, I also checked the broken code for hidden characters to no avail.
![image](https://user-images.githubusercontent.com/49076509/193296071-a32c36f2-175f-4e4f-b6d1-4f274a340475.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/@mandar1jn/collections/astro-getstaticpaths-not-found

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by mandar1jn** [comment]
A repository with the issue in context can be found [here](https://github.com/mandar1jn/portfolio/tree/c682ac5bc9fc38020e235a338e0a77608ef46ed4) I'm linking to a specific commit because I'll of course be applying my no-idea-why fix so I can continue working on it

**Comment by mandar1jn** [comment]
More conversation about this issue can also be found [in the discord support thread](https://discord.com/channels/830184174198718474/1025314465203363860)

**Comment by matthewp** [comment]
This looks similar to https://github.com/withastro/astro/issues/4685

**Comment by mandar1jn** [comment]
Yes. I can confirm. I read the issue and placed the opening bracket on a new line. Then I got the error

**Comment by mandar1jn** [comment]
Interesting. I am on the latest version which should have the updated compiler(?)

**Comment by mandar1jn** [comment]
Well, turns out I'm on compiler version 0.24 for some reason

**Comment by mandar1jn** [comment]
After running `yarn upgrade` the compiler is now on the latest version. Sadly, the issue still persists

**Comment by natemoo-re** [comment]
Might be the TypeScript types throwing off the compiler? I'll look at this again

**Comment by QQCif** [comment]
Hi, any update on this issue? I tried to type `paginate` funtion today and after prettier's fomatting, compiler told me `GetStaticPathsRequired`. I was so confused.
Reproduction
[https://stackblitz.com/edit/github-huahga?file=src%2Fpages%2Fblog%2F[page].astro&on=stackblitz](https://stackblitz.com/edit/github-huahga?file=src%2Fpages%2Fblog%2F[page].astro&on=stackblitz)

**Comment by natemoo-re** [comment]
This will be fixed by https://github.com/withastro/compiler/pull/750
