### ISSUE TITLE
Returning a `Response` from an API Route in SSG mode does not warn during development

### ISSUE THREAD

**Issue by Jutanium** [withastro/astro#4930]
### What version of `astro` are you using?

1.4.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If you return a Response from an API route in `static` mode, it fails during build.

> error: Returning a Response from an endpoint is not supported in SSG mode.

But during development, you don't get a warning.

Returning a Response _is_ allowed in `.astro` files in SSG mode, making it especially important to warn here.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sr6jeq?file=src%2Fpages%2Fpage-response.astro,src%2Fpages%2Fendpoint.json.ts&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
https://docs.astro.build/en/core-concepts/endpoints/#static-file-endpoints

I think it shall not warn during build rather build fine.
