### ISSUE TITLE
`astro build --help` should print a help message about the `astro build` command

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#4935]
### What version of `astro` are you using?

1.4.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If you run `npx astro build -h` it will just build and ignore the flag
If you run `npx astro build --help` it will print the global help message

I would expect that both commands print help details for the `build` command.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rq9ofs?file=example&view=editor

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@jasikpark are you able to submit a PR for this?

**Comment by jasikpark** [comment]
what would be required to make this happen?

**Comment by matthewp** [comment]
Help is printed here: https://github.com/withastro/astro/blob/main/packages/astro/src/cli/index.ts so updating that to account for it being for a subcommand.

**Comment by jasikpark** [comment]
okay thx -- I guess this issue is two things:

A that `-h` is ignored as a help flag for subcommands

B that it'd be great to have more in-depth help output for particular subcommands more than the single-line that's printed for global help

**Comment by ematipico** [comment]
I will be working on this. I will take the opportunity to add the `--help` flag to ALL commands.
