### ISSUE TITLE
Website loads/requests the wrong style sheets at random

### ISSUE THREAD

**Issue by lasfito** [withastro/astro#4941]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I got SSR Astro site hosted on Netlify. 

When I open a page no styling is shown because the wrong style sheets were requested. By "wrong" I mean random hashed values that do not correspond to the styling files of that page/template. 

This only occurs randomly (raw estimate of 1 out 7 pages) and seems to disappear when reloading multiple times. 

No asset optimization is enabled in Netlify and all styling is correctly added to the head while also avoiding Astro style directives. 

This situation has been discussed in Discord and there seems to be a consensus that this could be related to Netlify caching.

Find here the conversation:
https://discord.com/channels/830184174198718474/1025066250273042443

### Link to Minimal Reproducible Example

https://discord.com/channels/830184174198718474/1025066250273042443

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Going to close, please file another issue if you can create a reproduction.
