### ISSUE TITLE
Custom Elements not rendering since v1.4

### ISSUE THREAD

**Issue by Coretteket** [withastro/astro#4942]
### What version of `astro` are you using?

1.4.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows/StackBlitz

### Describe the Bug

Since v1.4.0, Custom Elements do not render into the HTML output. In the StackBlitz example linked below using v1.3.1, you should see the text 'test', and be alerted on clicking it. Changing Astro to v1.4.0 (or 1.4.1) however, removes the `custom-button` from the output.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-n3zm7f?file=src/components/Button.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tforssander** [comment]
Moving the `<script>` tag below the `<custom-button>` element seems to fix the issue. I'm not sure why this is happening, but I'm guessing it has something to do with the way the script is being loaded.
