### ISSUE TITLE
Access to <slot> content

### ISSUE THREAD

**Issue by f3oall** [withastro/astro#4955]
### What version of `astro` are you using?

1.4.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

WSL

### Describe the Bug

Currently Astro provide `Astro.slots.render()` function which returns a raw string. It would be neat to have access to the initial content of the slot, so we can be able to control what will be rendered and how it will be rendered.

For example, Vue uses VNodes, so when you access the slot you can manipulate these VNodes before they get rendered.

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I think we would need an RFC about this. I would recommend starting a discussion here: https://github.com/withastro/rfcs/discussions

fwiw, Astro does not have VNodes, HTML is just raw strings, so we'd be unlikely to provide you something like this. However it's worth talking about, maybe there's another solution to your needs.
