### ISSUE TITLE
Extremely slow text processing/rendering in components

### ISSUE THREAD

**Issue by janreges** [withastro/astro#4958]
### What version of `astro` are you using?

1.4.2

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Windows 11

### Describe the Bug

Hi,

we are big lovers and fans of Astro. Due to the fact that the website we are developing contains a mix of static and dynamically generated pages (e.g. with different content or personalization filters), we decided to use Astro in the mode with SSR and the "node" adapter. We use GraphQL and Apollo client with its cache to connect to our headless CMS. Everything works excellently and very fast.

Everything works flawlessly even in SSR mode, except for one major performance issue. We found a very significant slowdown on some pages - instead of the normal generation of HTML in 30-50ms, some pages are generated for us in around 1 second. These pages, unlike others, also only contain several paragraphs of text from variables. Also, when generating this page, the node process is loaded to 100% CPU, so there is no IO waiting.

In the end, we discovered that the problem is that Astro in SSR mode processes the text before rendering in some extremely inefficient way. I assume it will be caused by some regular expressions used to sanitize text.

I am attaching a very simple Example.astro for simulation.

If the given component contains only one paragraph of text, SSR renders the entire page in **30-40 ms**.

But if there are 60 paragraphs (as in example below), the page in SSR is generated around **400 ms**, which means that processing one such Lorem ipsum text in one paragraph requires 6 ms with full CPU load. These measurements are from an idle Intel Core i7-8700K processor, 32GB of RAM and NVME SSD. We use latest LTS NodeJS 16.17.1. We tested it with Windows 11 and also with Ubuntu, the results are the same.

Btw, I tested it also with latest Astro 1.4.3 (it contains some performance fix in SSR), but the results are the same.

Do you have any tips on how to solve this performance problem? We will of course use the HTML cache in the reverse proxy in selected places, however, even in SSR mode without cache the pages should be very fast. We use a lot of templating languages on other projects that also need to sanitize text/HTML based on context, but even with a lot of text there aren't these issues. I assume this is just a temporary weakness of Astro. In another case, it is a big problem of scaling, because even with very powerful multi-core processors and the use of clustering, one server could handle only tens or low hundreds of requests per second in SSR mode, which is very bad.

Thanks for the review and also for all the work you do with Astro 👍 

**Example.astro**
```javascript
---
const content: string = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";
---

<div>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
  <p>{content}</p>
</div>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yvb3ty?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks for the reproduction. 1.4.3 was intended as a partial fix as we saw that it helped in some apps. Still some work to do tracking down what caused the slowdown. I'll take a look at your example and see what's going on.

It's interesting to see that expressions are the root of the problem, that will help track things down.

In the mean time you might try 1.2.8 which was the last known version without the regression.

**Comment by matthewp** [comment]
I think I know (at least one of) the causes here.

**Comment by janreges** [comment]
Thank you @matthewp. I tested it with version 1.2.8 and SSR is ultrafast ❤️ Pages that previously took 500-800ms to generate now take an impressive 10-20ms. I know that you will be able to find and remove the issue. Fingers crossed and thanks :-)

**Comment by janreges** [comment]
@matthewp - I confirm that the slowdown occurred between versions 1.2.8 and 1.3.0.

I will mention that during the load testing using apache benchmark (`ab -n 1000 -c 50 http://localhost:3000/`) I noticed that with the very fast version 1.2.8, the `node` process allocates a maximum of 150-200 MB of RAM in peaks.

In the case of the slow version 1.3.0, the `node` process allocates more than 1 GB of RAM for the same requests, so the problem is related to the change, which at the same time basically increased the memory requirements.

**Comment by matthewp** [comment]
@janreges can you try with this preview release?

```
npm installl astro@ next--perf-2
```

**Comment by janreges** [comment]
@matthewp - i tried `astro@next--perf-2` version and is also superfast like in 1.2.8 version! You fixed it man. Thank you! 💪

**Comment by getflourish** [comment]
So glad I found this by searching for issues containing “slow”. I was on 1.4.2. and ```astro@next--perf-2``` fixes the slow dev server! :)

**Comment by matthewp** [comment]
@getflourish this has since been released and latest has these fixes

**Comment by getflourish** [comment]
You're moving fast :)
