### ISSUE TITLE
@astrojs/image: Don't include original image in output bundle

### ISSUE THREAD

**Issue by jkjustjoshing** [withastro/astro#4961]
### What version of `astro` are you using?

1.2.5

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm not sure if this is a bug or a feature request - my apologies if I should have submitted this to github.com/withastro/rfcs

When using `@astrojs/image` with the `<Picture>` component and `widths={}` prop, multiple different sizes of images end up in my `./dist/assets` folder corresponding to the values I pass `widths`. However, there is also a copy of the original full-sized image. 

This full-sized image is not referenced in the HTML at all, and is never downloaded by the site user, so I have no concerns for user-experience with an oversized image. However, including this full-size image in the bundle makes deploys slower and can increase hosting costs.

### Suggested change
Remove full-size image from output directory

### Alternatative
Setting in integration config options for removing the full-size image.

### Link to Minimal Reproducible Example

Not applicable (but I can provide one if anyone disagrees)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
I think this was added at the request of people who did need the full size image as well (to reference as an open graph image or use as a download link or something). So I guess a config option that lets you opt out might make sense (or opt in, not sure what makes most sense)

**Comment by jkjustjoshing** [comment]
That's what I figured. However, the original image has a hashed filename - how would someone write code to actually expose the URL of the full-sized image to the user? 

If it is possible to get the path to the full-sized image, then I agree that it's good to keep in the output folder (with an option to exclude it). However, if it's not possible then I would say either a) there's no value in having it or b) there should be a way to expose the original file's path to the developer.

**Comment by panwauu** [comment]
Possible duplicate of #4896

**Comment by tony-sull** [comment]
The original image actually does need to be included here in case an image is imported and the `src` is used directly.

Astro won't actually know what image variants are used until every page is built, and it won't actually know at all in SSR since the pages are built at run time.

It's a bit of an implementation detail and a little annoying to see extra files included here, but there's not a way to safely avoid it either unfortunately

```ts
---
import hero from '../hero.jpg'
---

<!-- this src can be used as-is, but it will fail if the original file isn't included in dist -->
<img src={hero.src} />
```

**Comment by jkjustjoshing** [comment]
Ah that makes sense. I wasn't thinking about using the image in a raw/native `<img>` element without using `<Image>` or `<Picture>`. Thanks for the context!

**Comment by supermoos** [comment]
@tony-sull could a work around be to have some sort of import parameter that would exclude it from the output? something like: 
```
---
import hero from '../hero.jpg!discard'
---
```
It's a big issue as it defeats the purpose for a lot of image generation scenarios to output the original source also.

**Comment by supermoos** [comment]
Or perhaps some sort of post build way to delete those files again?

**Comment by jkjustjoshing** [comment]
@supermoos the naming convention of the files is regular, so you probably could write a script post-build that looks for the original file. It would be pretty fragile, but could do something like the following:

Look for files matching the regex `/^([^.]+)\.([0-9a-f]+)\.([a-z]+)$/` - that is, "xxxx.abc123.jpg". This is an original (all non-original files have an underscore in the segment before the file extension). `$1` is the first part of the path, `$2` is the unique content hash, and `$3` is the file extension. Before deleting it would be smart to make sure there exist optimized versions of this file - files that follow the pattern `$1.$2_[anything alphanumeric].[any extension]`.

**Comment by supermoos** [comment]
Thanks for this. Seems a bit error prone though. What if I actually wanna keep some of the source files for some reason? The import suggestion would solve that issue.

**Comment by simonwiles** [comment]
Fwiw, this causes me a problem on a very image-heavy site, as my originals are large and when they're copied into the output folder I end up with something that's too big to upload to my hosting environment.

**Comment by rikur** [comment]
I get a lot of noise on aHrefs site audit, because the crawler will download the original images that are way too big.

**Comment by robinwatts96** [comment]
Hi, this is a really useful thread. I'm having a somewhat unrelated issue, but this thread seems like the best place I could find help.

I want to get the final path to the images in the  _astro folder dynamically in my head element. I need to do this _before_ the build process, not on the client. It would be easy enough if I could do this on the client...

I want to set the [og:image](https://ogp.me/#:~:text=og%3Aimage%20%2D%20An%20image%20URL%20which%20should%20represent%20your%20object%20within%20the%20graph.) property in the head, but the value I set won't function as intended if set it on the client with JS, as Google scrapes your page pre any JS you add on the client. 

So if there was a way for me to guess the abc123 part of the file path: "xxxx.**abc123**.jpg" then I think i'd be able to work the rest out.

Any help with this would be greatly appreciated!

> @supermoos the naming convention of the files is regular, so you probably could write a script post-build that looks for the original file. It would be pretty fragile, but could do something like the following:
> 
> Look for files matching the regex `/^([^.]+)\.([0-9a-f]+)\.([a-z]+)$/` - that is, "xxxx.abc123.jpg". This is an original (all non-original files have an underscore in the segment before the file extension). `$1` is the first part of the path, `$2` is the unique content hash, and `$3` is the file extension. Before deleting it would be smart to make sure there exist optimized versions of this file - files that follow the pattern `$1.$2_[anything alphanumeric].[any extension]`.
> 
> <img alt="image" width="304" src="https://user-images.githubusercontent.com/813192/196691226-2f831a83-016d-4400-86e6-5e080fb2d8ef.png">

**Comment by robinwatts96** [comment]
@delucis This is **exactly** what I needed - thank you so much, I appreciate your help.

**Comment by wtchnm** [comment]
> @supermoos the naming convention of the files is regular, so you probably could write a script post-build that looks for the original file. It would be pretty fragile, but could do something like the following:
> 
> Look for files matching the regex `/^([^.]+)\.([0-9a-f]+)\.([a-z]+)$/` - that is, "xxxx.abc123.jpg". This is an original (all non-original files have an underscore in the segment before the file extension). `$1` is the first part of the path, `$2` is the unique content hash, and `$3` is the file extension. Before deleting it would be smart to make sure there exist optimized versions of this file - files that follow the pattern `$1.$2_[anything alphanumeric].[any extension]`.
> 
> <img alt="image" width="304" src="https://user-images.githubusercontent.com/813192/196691226-2f831a83-016d-4400-86e6-5e080fb2d8ef.png">

For those who don't use imported images directly in plain `<img />` tags, here's an Astro integration that removes the original images from the build:

```typescript
// In Astro 4, images that are not used are remove from the build, but some original images still exist in the _astro folder.
const removeOriginalImages: AstroIntegration = {
	name: 'remove-original-images',
	hooks: {
		'astro:build:done': async ({ dir }) => {
			const path = dir.pathname + '_astro/'
			const files = await fs.readdir(path)
			for (const file of files) {
				const parts = file.split('.')
				const ext = parts.pop()
				if (ext && ['jpg', 'png'].includes(ext)) {
					const hash = parts.pop()
					if (hash && !hash.includes('_')) {
						await fs.unlink(path + file)
					}
				}
			}
		}
	}
}
```

**Comment by tenpaMk2** [comment]
Thank you for sample codes.
I made improved version.

- Add supports for `jpeg` and `webp` .
- Detect `_` only in hash strings.

```ts
import fs from "node:fs/promises";
import path from "node:path";

...

    {
      name: "remove-original-images",
      hooks: {
        "astro:build:done": async ({ dir }) => {
          const astroDir = path.join(dir.pathname, `_astro/`);
          const files = await fs.readdir(astroDir);

          for (const file of files) {
            const { name, ext } = path.parse(file);
            const { ext: hashStr } = path.parse(name);

            if (!ext) continue;
            if (!hashStr) continue;
            if (![`.jpg`, `.jpeg`, `.png`, `.webp`].includes(ext)) continue;
            if (hashStr.includes(`_`)) continue;

            console.log(`Removing original image: ${file}`);
            await fs.unlink(path.join(astroDir, file));
          }
        },
      },
    },
```

Optimized image seems to have `{name}.{original hash}_{additinal hash}.{ext}` .
However, sadly, some `{original hash}` contain `_` .
Therefore, the above scripts wrongly detect these images as optimized and will not remove it.

**Comment by jurajkapsz** [comment]
Thanks guys for sharing the original image removal code. Probably you got it further improved by now, in any case here is my version as of now. I modified the matching algorithm to overcome the mentioned `_` limitation and added support for reflecting the Astro `_assets` folder setting from `AstroConfig` itself because I myself have it customized.

I also added some logging so I know about interventions on the official build process. I went for a shorter integration name `ROI` just because of that; not sure about it, but the logs are more compact that way. Can be easily changed. Otherwise I tried to have my code human readable.

Finally, I narrowed the checked original image file formats for my use case as I don't expect to deliver web image formats (`webp`, `avif`, ...?) myself, but to have them generated for me. This can be changed in the formats array, as anything else.

```ts
import { readdir, unlink } from "node:fs/promises";
import path from "node:path";
import type { AstroIntegration, AstroConfig } from "astro";

// Inspired by https://github.com/withastro/astro/issues/4961#issuecomment-2322936873
function removeOriginalImages() {
  let astroConfig: AstroConfig;

  // Used to identify original image files
  const ORIGINAL_IMAGE_FORMATS = ["jpg", "jpeg", "png"] as const;
  const ORIGINAL_IMAGE_HASH_PATTERN_DOT_8_HASH_CHARS_DOT = ".*\\.[a-zA-Z0-9_\\-]{8}\\.";

  const integration: AstroIntegration = {
    name: "ROI",
    hooks: {
      "astro:config:done": ({ config }) => {
        astroConfig = config;
      },
      "astro:build:done": async ({ dir, logger }) => {
        const astroAssetsDir = path.join(dir.pathname, astroConfig.build.assets);
        const files = await readdir(astroAssetsDir);

        let foundFilesCount = 0;
        let removedFilesCount = 0;

        for (const file of files) {
          const { ext } = path.parse(file);
          // Strip `ext` of dot also for use in upcoming regex match, as dots have special meaning
          const fileFormat = ext.slice(1);

          if (!(ORIGINAL_IMAGE_FORMATS as ReadonlyArray<string>).includes(fileFormat)) continue;

          // Match original image files by ending with single hash and extension
          const reOriginalImage = new RegExp(`${ORIGINAL_IMAGE_HASH_PATTERN_DOT_8_HASH_CHARS_DOT}${fileFormat}$`);
          if (!reOriginalImage.test(file)) continue;

          foundFilesCount++;
          logger.warn(`Removing ${file}`);

          const result = await unlink(path.join(astroAssetsDir, file));

          if (isUnlinkSuccessful(result)) {
            removedFilesCount++;
          } else {
            logger.error(`Couldn't remove file ${file}`);
          }
        }

        if (foundFilesCount > 0) {
          logger.warn(`Removed ${removedFilesCount}/${foundFilesCount} files.`);
        }

        /** Helper function */
        function isUnlinkSuccessful(result: unknown): boolean {
          return typeof result === "undefined";
        }
      },
    },
  };

  return integration;
}

export default removeOriginalImages;
```

**Comment by petdomaa100** [comment]
Since there's no reliable way for Astro to know it in advance, it would be nice to have a config option to specify which images to exclude/include.

In the meantime, here is what I came up with (heavily) inspired by the solutions above:
```ts
import path from 'node:path'
import fs from 'node:fs/promises'
import type { AstroIntegration, AstroConfig } from 'astro'

/**
 * Astro keeps a copy of the original, unprocessed image in the build output
 * alongside any processed variants, even when the original itself is never
 * referenced in the final HTML. This integration deletes those unused originals
 * after build. See: https://github.com/withastro/astro/issues/4961
 */
function imageCleanup() {
  let astroConfig: AstroConfig

  return <AstroIntegration> {
    name: 'image-cleanup',
    hooks: {
      'astro:config:done': ({ config }) => {
        astroConfig = config
      },
      'astro:build:done': async ({ dir, logger }) => {
        const srcDir = astroConfig.srcDir.pathname
        const regexes: RegExp[] = []

        for await (const file of fs.glob('**/*.{png,jpg,jpeg}', { cwd: srcDir })) {
          const { name, ext } = path.parse(file)

          // In the build output, assets that were processed appear as `name.HASH_HASH2.ext`,
          // while unprocessed originals appear as `name.HASH.ext`. This regex matches only the latter.
          // Example: `image.CSgEFFUW.png` & `image.CSgEFFUW_Z19EHYn.png`
          regexes.push(new RegExp(`^${name}\\.[a-zA-Z0-9_\\-]{8}${ext}\$`))
        }

        // =====

        const builtAssetsDir = path.join(dir.pathname, astroConfig.build.assets)
        const files = await fs.readdir(builtAssetsDir)

        for (const file of files) {
          if (!regexes.some(r => r.test(file))) {
            continue
          }

          await fs.unlink(path.join(builtAssetsDir, file))
            .catch(e => logger.error(`Failed to delete ${file}: ${e}`))
            .then(() => logger.info(`Deleted ${file}`))
        }
      },
    },
  }
}
```

**Comment by kitschpatrol** [comment]
Sharing one more clean-up integration implementation in case it's useful to anyone:

https://github.com/kitschpatrol/astro-media-kit/blob/main/src/integration/remove-originals.ts

Also available on NPM as part of [astro-media-kit](https://www.npmjs.com/package/astro-media-kit).
