### ISSUE TITLE
[@astrojs/prefetch] Prevent prefetching current page

### ISSUE THREAD

**Issue by Coretteket** [withastro/astro#4963]
### What version of `astro` are you using?

1.4.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

In `@astrojs/prefetch`, there is currently no check to prevent prefetching the current page. This is, at least in my use-cases, quite a common occurrence when a navigation component is used on a group of pages. So, when a `/` path has a `<a href="/" rel="prefetch" />` tag, it will re-request the page, as can be seen in the screenshot of the network tab. 

Looking at the integration source code, it seems that the [`shouldPreload`](https://github.com/withastro/astro/blob/main/packages/integrations/prefetch/src/client.ts) function just needs a check like `window.location.pathname !== url.pathname`. (PS: What is the `url.hash` check doing here? AFAIK this will never equal the location's pathname.)

**Screenshot:**
![image](https://user-images.githubusercontent.com/33397397/193669596-f024f9d7-59d0-4f05-9198-0fc78b15a2e8.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dsebcz?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by panwauu** [comment]
I also tested it and you are right it works after the change. I would guess that the `url.hash` is a typo and was actually supposed to be `url.pathname`.

**Comment by mdkq** [comment]
Hey I'm just wondering is this really desirable? I have a use case where I have a pagination component comprised of links with the same pathname and differing `page` search params. This check prevents all of them from being prefetched. Would comparing pathname + search be better?
