### ISSUE TITLE
Deep (slots) Vue island not hydrating since v1.4

### ISSUE THREAD

**Issue by leomp12** [withastro/astro#4970]
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

> May be related to https://github.com/withastro/astro/issues/4942 👀 

The example below works as expected until v1.3.1, since v1.4.0 my `LoginOffcanvas` Vue component is not interactive anymore:

```astro
<slot name="header">
  <TheHeader {...globalThis.TheHeaderProps}>
    <Fragment slot="buttons">
      <LoginOffcanvas client:idle {...globalThis.LoginOffcanvasProps} />
    </Fragment>
  </TheHeader>
</slot>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vzvsg1?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This was indeed the same issue as #4942  Now working in 1.4.5. See https://stackblitz.com/edit/github-vzvsg1-vbhy1j?file=package.json
