### ISSUE TITLE
astro-slot no closed tag and Client Directives Don't work

### ISSUE THREAD

**Issue by J-env** [withastro/astro#4971]
### What version of `astro` are you using?

v1.4.2+, v1.4.4

### Are you using an SSR adapter? If so, which one?

None, @astrojs/solid-js^1.1.0, solid-js^1.5.7

### What package manager are you using?

npm, node14.20.0, node16.14.2

### What operating system are you using?

Mac

### Describe the Bug

🐛🐛: Client Directives Don't work
🐛🐛 astro-slot no closed tag： 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/25259920/193744640-b5af9f8c-7336-4dc2-b02f-c6df17bb7be8.png">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sdeict-4fhgo1?file=src%2Flayouts%2FActivity%2FLayout.astro,src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thank you, to your knowledge was this previously working in another version?

**Comment by J-env** [comment]
@matthewp 
I am using Astro in project since Astro1.4.2.
Client Directives Don't work 🐛 I figured out the reason.

in the link example: 
```
// src/layouts/Container.astro
---
const Component: string = Astro.props.tag || 'div';
---

// remove <Component><slot /></Component>

// new
// Client directives work
<div><slot /></div>
```

**Comment by matthewp** [comment]
I don't see client directives there, can you explain more?

**Comment by J-env** [comment]
When there are dynamic tags, Client Directives Don't work

I have simplified the code:
[link example](https://stackblitz.com/edit/github-sdeict-4fhgo1?file=src%2Fpages%2Findex.astro)

**Comment by matthewp** [comment]
Right, thanks! It looks like the closing slot is being escaped, will investigate.

**Comment by matthewp** [comment]
Ok, so the problem here is that the hydration script is not being appended, looking into why that is.

**Comment by J-env** [comment]
OK, thanks! I am migrating projects to Astro. It seems that both bugs are because of dynamic tags
