### ISSUE TITLE
Yarn: node adapter builds with error in entry script

### ISSUE THREAD

**Issue by Jutanium** [withastro/astro#4974]
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

After installing the node adapter and running `yarn build`, the output `entry.mjs` script contains this line: 
```js
import { compile } from 'path-to-regexp';
```
This results in an error when script is run:
> import { compile } from 'path-to-regexp';
         ^^^^^^^
SyntaxError: Named export 'compile' not found. The requested module 'path-to-regexp' is a CommonJS module, which may not support all module.exports as named exports.

This is fixed by adding `path-to-regexp` to `noExternal` before building.

This error does not happen when using `npm` or `pnpm`. Yarn seems to build an entirely different entry script, which is shorter but has these additional dependencies.

Yarn:
```js
// entry.mjs
import * as adapter from '@astrojs/node/server.js';
import { escape } from 'html-escaper';
import 'mime';
import 'cookie';
import 'kleur/colors';
import 'string-width';
import 'path-browserify';
import { compile } from 'path-to-regexp';

const ASTRO_VERSION = "1.4.4";
...
```

pnpm:
```js
// entry.mjs
import * as adapter from '@astrojs/node/server.js';

const ASTRO_VERSION = "1.4.4";
```

### Link to Minimal Reproducible Example

https://github.com/Jutanium/repro-node-yarn

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Closed by https://github.com/withastro/astro/pull/4978
