### ISSUE TITLE
[@astrojs/image]: Picture component does not resize with scrollbar

### ISSUE THREAD

**Issue by panwauu** [withastro/astro#4985]
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I want to use the Picture component, but I am not really familiar with it, so correct me if I do anything wrong.

I use the component like this (copying from the docs) and adding the `width: 100%`.
```html
<Picture 
   src={imageUrl} 
   widths={[200, 400, 800]} 
   aspectRatio="2109:684" 
   sizes="(max-width: 800px) 100vw, 800px" 
   alt="descriptive text"
   style="width: 100%;"
/>
```

The width works until the content gets too large for the page and a scrollbar appears. Now the picture has the correct size but the img tag inside still has 100vw width (which is defined in sizes). This makes it hard for me to style the picture component. I can "fix" the behaviour to my expected behaviour by applying (but it seems hacky and I need to add global styles):

```html
<style is:global>
/* Fix by adding width: 100% to img */
picture > img {
   width: 100%;
} 
</style>
```

Is this usual? Am I doing something wrong?
(Why dont we add width and height attributes (Removed in #4797) to avoid layout shifts and apply width: 100% to the img to keep responsiveness?)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qnk2xr?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by carlcs** [comment]
Related to https://github.com/withastro/astro/issues/3909
