### ISSUE TITLE
SSR example not working

### ISSUE THREAD

**Issue by developer2346** [withastro/astro#4991]
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Running the ssr example and getting this error when opening in the browser:
`Only instance of Response can be returned from an Astro file`

Commands run:
```
npm run build
npm run server
```
same error for `npm run dev`

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/tree/main/examples/ssr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Oh right, I meant to fix this.
