### ISSUE TITLE
[@astrojs/image]: ReferenceError: module is not defined

### ISSUE THREAD

**Issue by Merciful12** [withastro/astro#4995]
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac, Linux

### Describe the Bug

I'm trying to use Image component but it's not working. I got errors like
```js
 error   module is not defined
ReferenceError: module is not defined
    at /node_modules/.pnpm/http-cache-semantics@4.1.0/node_modules/http-cache-semantics/index.js:101:1
    at instantiateModule (file:///Users/stanislav/Projects/my-astro-site/node_modules/.pnpm/vite@3.1.5/node_modules/vite/dist/node/chunks/dep-49b3b5ea.js:53436:15) 
```

It does work with npm

### Link to Minimal Reproducible Example

https://github.com/Merciful12/astro-reproduce

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by unalgo** [comment]
@Merciful12 Removing node_modules folder and switching to npm resolved my issue.
