### ISSUE TITLE
[@astrojs/image]: Picture not working with query parameter

### ISSUE THREAD

**Issue by panwauu** [withastro/astro#4996]
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When running `build` with a picture and a query parameter in src I get the following error:
`Error: Expected one of: heic, heif, avif, jpeg, jpg, jpe, tile, dz, png, raw, tiff, tif, webp, gif, jp2, jpx, j2k, j2c for format but received jpg?test=test of type string`

To determine the file extension the query parameter should be ignore. It works in dev.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qnk2xr-4dvsmq?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by akyag** [comment]
Same error when importing svg image.
```
 optimizing 4 images in batches of 4 
 error   Expected one of: heic, heif, avif, jpeg, jpg, jpe, tile, dz, png, raw, tiff, tif, webp, gif, jp2, jpx, j2k, j2c for format but received svg of type string
  Code:
      123 | const invalidParameterError = function (name, expected, actual) {
    > 124 |   return new Error(
          |          ^
      125 |     `Expected ${expected} for ${name} but received ${actual} of type ${typeof actual}`
      126 |   );
      127 | };
```
