### ISSUE TITLE
Using npm create, could not find commit hash for latest

### ISSUE THREAD

**Issue by BGOPC** [withastro/astro#5004]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux, Ubuntu 22.04

### Describe the Bug

I just heard of Astro and when wanted to create a project using `npm create astro@latest`, I got the `could not find commit hash for latest` Error.
I'm living in Iran just in case.
this is the Error Text:
```
Welcome to Astro! (create-astro v1.1.0)
Lets walk through setting up your new Astro project.

✔ Where would you like to create your new project? … ./my-astro-site
✔ Which template would you like to use? › Just the basics (recommended)
✖ ■■▶ Copying project files...
could not find commit hash for latest
This seems to be an issue with degit. Please check if you have 'git' installed on your system, and install it if you don't have (https://git-scm.com).
If you do have 'git' installed, please run this command with the --verbose flag and file a new issue with the command output here: https://github.com/withastro/astro/issues
npm ERR! code 1
npm ERR! path /home/bgopc/Documents/projects/astro/P1
npm ERR! command failed
npm ERR! command sh -c -- create-astro

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bgopc/.npm/_logs/2022-10-06T17_52_55_124Z-debug-0.log
```
## Nodejs Version: 18.9.1

Older Version and npm default version didn't work too

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Can you try again? Is this still happening? Could have been an internet connection issue.
