### ISSUE TITLE
Type for TSX with solid integration

### ISSUE THREAD

**Issue by chlbri** [withastro/astro#5017]
### What version of `astro` are you using?

16.16.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

For tsx files for solidjs Components, I need to configure tsconfig in order to correct typescript check errors for JSX.IntrinsicElements. 
```json
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "solid-js"
  }
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/github/chlbri/astro-site-solig-jsx-bug?file=tsconfig.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
We have a PR due to go out next week that should fix this for new projects: https://github.com/withastro/astro/pull/4959

**Comment by chlbri** [comment]
Alternatively, you can use a per-file pragma to set this option, like:

```typescript
/** @jsxImportSource solid-js */

import type { Component } from 'solid-js';
```

**Comment by chlbri** [comment]
Cool
