### ISSUE TITLE
Vercel deployments broken with pnpm

### ISSUE THREAD

**Issue by sammccord** [withastro/astro#5020]
### What version of `astro` are you using?

1.4.6

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When deploying an Astro site inside a pnpm monorepo to Vercel with the `@astrojs/vercel/serverless` adapter, the deployment succeeds, but all requests fail with 500 errors. See this deployed example - [https://pnpm-astro.vercel.app/](https://pnpm-astro.vercel.app/)

The only error being thrown in the logs is:

```
ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@astrojs/vercel' imported from /var/task/entry.js    at new NodeError (node:internal/errors:372:5)
```

This is essentially a duplicate of [https://github.com/withastro/astro/issues/4567](https://github.com/withastro/astro/issues/4567), but I'm re-opening this specifically for pnpm / Vercel functionality.

I'll also note that `shamefully-hoist=true` in the root `.npmrc` doesn't seem to have any effect, [even though it was fixed](https://github.com/withastro/astro/issues/4567#issuecomment-1270586418) in `>1.4.0`

### Link to Minimal Reproducible Example

https://github.com/sammccord/pnpm-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Do you need to move that package into a regular (non dev) dependencies?

**Comment by sammccord** [comment]
> Do you need to move that package into a regular (non dev) dependencies?

Both `astro` and `@astrojs/vercel` are listed in the package's production dependencies in the attached reproduction - [https://github.com/sammccord/pnpm-astro/blob/main/packages/astro/package.json](https://github.com/sammccord/pnpm-astro/blob/main/packages/astro/package.json)

**Comment by JuanM04** [comment]
@sammccord I've made a fix. Could you try it and tell me if it works?

```bash
$ pnpm add @astrojs/vercel@next--monorepos
```

**Comment by sammccord** [comment]
> I've made a fix. Could you try it and tell me if it works?

Looks good to me! Thanks! <3

**Comment by BrightonMboya** [comment]
idk if it was removed in the latter releases and I have the same exact issue as this one. Followed the above instructions but still doesnt work. I have opened a  [new Issue](https://github.com/withastro/astro/issues/5657)

**Comment by jon-xo** [comment]
I opened #9382 with my Vercel output and a screenshot
