### ISSUE TITLE
[@astrojs/image] gif formats are not supported

### ISSUE THREAD

**Issue by DJRHails** [withastro/astro#5028]
### What version of `astro` are you using?

1.4.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

Remote `.gif` files are unsupported.

Local `.gif` files a semi-supported using Sharp, but break in `<Picture/>` components due to avif formatting.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lmp1qc?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by panwauu** [comment]
Related to #4936

You could always set a custom formats option in picture: `formats={['webp']}` than you dont have the problem with `<Picture />` and sharp

From my experience it does always works with GIF if you use sharp and not avif. It does not work with squoosh and avif

**Comment by DJRHails** [comment]
Yes - that's my work around at the moment:

```ts
let formats = [meta.format, "webp"];

if (meta.format !== "gif") {
  formats.push("avif");
}
``` 

But at the very least it could do with throwing an error / meaningful error message rather that a subtle break.

**Comment by panwauu** [comment]
Or maybe the default formats should depend on the input format like you do already 🤔

I totally agree on the error messages! 

avif should support animated content correct?

**Comment by DJRHails** [comment]
Yes - via `.avifs` I believe

**Comment by matthewp** [comment]
Thanks, is anyone willing to submit a PR for this?

**Comment by panwauu** [comment]
I am willing, but not sure if I am capable. I will look into it.

**Comment by wulinsheng123** [comment]
mark,
I will contribute

**Comment by wulinsheng123** [comment]
![image](https://user-images.githubusercontent.com/27261522/201592831-68d74bbe-e74d-4db5-9230-ca4e7c7eb9a0.png)

**Comment by matthewp** [comment]
@bluwy assigning to you since you are reviewing the PR

**Comment by wulinsheng123** [comment]
> it does always works with GIF if you use sharp and not avif.

The GIF setup `formats={['avif']}` then can't work with `sharp`?

**Comment by wulinsheng123** [comment]
> 

hello 
Could your offered `code` run without set `image({ serviceEntryPoint: '@astrojs/image/sharp' })`?

**Comment by wulinsheng123** [comment]
@bluwy I did both methods.
