### ISSUE TITLE
[@astrojs/tailwind] Cannot use custom animations defined by extending tailwind.config.cjs

### ISSUE THREAD

**Issue by jChapman** [withastro/astro#5030]
### What version of `astro` are you using?

v1.4.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When adding a new animation by extending the theme in tailwind.config.cjs as described in the [tailwind documentation ](https://tailwindcss.com/docs/animation#customizing-your-theme) I am unable to get the example shown in the docs (wiggle) to work at all. Using the built in animations works just fine and the tailwind vs code plugin seems to find the new keyword and associated keyframes just fine. Copy pasting the same tailwind.config.cjs into the [Tailwind Playground](https://play.tailwindcss.com/) (and applying animate-wiggle to some element) shows it working just fine. 

Recreated with the tailwind starter in gitpod before I read the issue template, I can recreate it in stackblitz if needed. 

### Link to Minimal Reproducible Example

https://gitpod.io#snapshot/41df471a-0ddf-4b48-b255-8d080df2aef5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jChapman** [comment]
Only happens in preview, in the deployed site it works

**Comment by adrifer** [comment]
I have the same issue. Restarting `npm run dev` seems to do the trick

**Comment by matthewp** [comment]
That's right, currently you have to restart the server on Tailwind config changes. https://github.com/withastro/astro/pull/4947 will fix that.

**Comment by bluwy** [comment]
Closing as #4947 is merged.
