### ISSUE TITLE
Config's site option not change <astro-island> component-url

### ISSUE THREAD

**Issue by vivipure** [withastro/astro#5043]
### What version of `astro` are you using?

1.4.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I use the github page to deploy my astro application. So I set the `site` option. All static resources are loaded properly, except js.
```js
//astro.config.mjs
{
  site: 'https://vivipure.github.io/code_playground/',
}
```

I noticed that it might be a problem with the `<astro-island>` component.

Now ：
```
<astro-island uid="1efXz4" component-url="/PlayGround.fd49d14d.js" component-export="default"
```
It Should be：
```
<astro-island uid="1efXz4" component-url="/code_playground/PlayGround.fd49d14d.js" component-export="default"
```

But when I set the base option, it works fine.
```diff
- site: 'https://vivipure.github.io/code_playground/',
+ base: '/code_playground',
```

What is the difference between them?

**Comment by matthewp** [comment]
`site` is used for generating the sitemap (which requires the domain) and can be used in your components via `Astro.site` to create canonical URLs. It's not used for setting astro-island, link, or script urls. https://docs.astro.build/en/reference/configuration-reference/#site
