### ISSUE TITLE
Astro.glob() wildcard import returns only the first file type if spaces are included in the prop string

### ISSUE THREAD

**Issue by flbn** [withastro/astro#5048]
### What version of `astro` are you using?

1.2.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Astro.glob() wildcard import only works for multiple file types if no spaces are provided. The following will only return `.txt` files.
```typescript
const files = (await Astro.glob<ImgType>('./120mm/*{txt, jpg, jpeg, png, webp, gif}'))
```

Whereas removing the spaces inbetween each extension will return the expected files:
```typescript
const files = (await Astro.glob<ImgType>('./120mm/*{txt,jpg,jpeg,png,webp,gif}'))
```

*_Minimal repro link is not viable, it seems overkill for an easily reproducible bug +++ it's late and i have work in the morning. I can add later if need be._*

### Link to Minimal Reproducible Example

https://github.com/flbn/astro-dir

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by flbn** [comment]
some of the comments in the [testing code](https://github.com/withastro/astro/blob/67fbdc338427fc47e28bf18c335929f50a50d4d3/packages/astro/src/vite-plugin-astro-postprocess/index.ts) seem to anticipate this as a potential issue but it doesn't seem to be working correctly 🤔 🤔

It's late, so I can't dig into the code too much but perhaps this is actually a Vite issue? Willing to contribute a patch if it isn't in the works already, just lmk if I can help out. The obvious fix is to warn people that whitespace is important in the docs, but seems like it should be addressed for DX purposes :)

**Comment by matthewp** [comment]
First thing to do is try `import.meta.glob` and see if you get a difference, since Astro.glob is a wrapper around that.

**Comment by flbn** [comment]
Fails to behave correctly with import.meta.glob, I suppose it is a Vite thing!

**Comment by flbn** [comment]
I guess a potential solution could be to remove whitespace while parsing?

**Comment by flbn** [comment]
The following regex will remove all whitespaces in a sting: `str.replace(/\s+/g, '')`, i.e. spaces, tabs, new lines, etc. I can dive into the code and add this if it's deemed permissible.

**Comment by matthewp** [comment]
Thanks, can you raise this issue with Vite directly?
