### ISSUE TITLE
SolidJS / Vite 3.1.0 issues

### ISSUE THREAD

**Issue by Ehesp** [withastro/astro#5058]
### What version of `astro` are you using?

1.4.7

### Are you using an SSR adapter? If so, which one?

N/A

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When Vite 3.1.0 released, it caused issues with some packages in the solid ecosystem. The issue I'm running into is:

https://github.com/thisbeyond/solid-dnd/issues/53

That issue has a bit of a chain of what the problem is, however ultimately a PR landed to [vite-plugin-solid](https://github.com/solidjs/vite-plugin-solid) which fixed it.

I'm trying to figure out how to incorporate the latest commits to that plugin into the astro adapter however I'm not having much luck. I've added a repro below to demonstrate this error in astro.

When running the repo, when vite starts you'll get this error below, which is the same as the one linked in the above issue:

```
[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: /home/projects/github-gjh4c2/node_modules/@thisbeyond/solid-dnd/dist/source/sortable-context.jsx?v=6a9840e1
  39 |      return <Context.Provider value={context}>{props.children}</Context.Provider>;
  40 |  };
  41 |  const useSortableContext = () => {
     |                                    ^
  42 |      return useContext(Context) || null;
  43 |  };
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gjh4c2?file=src/Foo.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
We've talked about using `vite-plugin-solid` in our adapter. cc @bluwy who brought up this idea.

**Comment by chlbri** [comment]
https://github.com/thisbeyond/solid-dnd/issues/66#issue-1436030446

**Comment by Ehesp** [comment]
Awesome, thanks for the work!
