### ISSUE TITLE
map() index not available for slot

### ISSUE THREAD

**Issue by nelhop** [withastro/astro#5066]
### What version of `astro` are you using?

1.4.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I am trying to put a dynamic number of slots into a component. But for some reason the index of the .map() function is not  available inside of slot={} (ReferenceError: index is not defined), but everywhere else.

```jsx
---
import Component from '../components/Component.astro'
const content = ['ZERO', 'ONE', 'TWO', 'THREE', 'FOUR']
---

<Component>
    {
      content.map((contentBlock, index) => (
        <div
          test={index} // available here
          slot={"slot" + index}  // NOT available here. Works with a hard typed slot, like slot="slot2"
         >
            {contentBlock}
            {"slot" + index}  // available here
        </div>
      ))
    }
</Component>
```

May be related to https://github.com/withastro/compiler/issues/566?

### Link to Minimal Reproducible Example

https://codesandbox.io/s/boring-morning-5hgjr0?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I looked into this and we cannot support dynamic slot names. The compiler creates render functions for each slot and it can't do so when the names are dynamically generated like this. So this comes down to a limitation of the Astro syntax.

**Comment by nelhop** [comment]
Thanks for clarification!

**Comment by enavarrocu** [comment]
Any workaround or suggestion for this issue? I also have it.

**Comment by Alex-S-Davies** [comment]
I have just filed a pr to add a note for this in the astro docs as I lost a few hours wondering why my dynamic slots would not work.
May I request that the compiler spits out an error when a developer tries to generate a slot that the compiler cannot handle? Currently it just silently fails.

It would be amazing if this feature is possible in the future, as dynamically named slots is an extremely powerful feature and it is shame that astro has limited support for them.

> Any workaround or suggestion for this issue? I also have it.

I am not sure what your case was, but I was trying to use an astro component in a dynamically named slot for a vue component. As a workaround I was able to utilize the [GetImage ](https://docs.astro.build/en/guides/images/#generating-images-with-getimage) function to generate everything I needed to then build the dynamic slot in vue instead. I suppose this solution works with the other UI frameworks but if you aren't using any, you might be a bit stuck....

**Comment by lukasborawski** [comment]
I encountered a similar issue and discovered a solution that involves setting up multiple `if` statements. However, this approach is not very flexible and can be quite unsightly, especially if you have a large number of items in your array. It may work well only if you have a limited number of items in your array.

```astro
array.map(
   (item, index) => (
        <div class={item.class}>
           {index === 0 && <slot name="item-1" />}
           {index === 1 && <slot name="item-2" />}
        </div>
    ),
 )
```

**Comment by jhedstrom** [comment]
I'm attempting to pull slide show cards from an API, and am encountering this limitation. Are there proposed dynamic workarounds?

```
<Carousel>
  {slides.map((slide: HeroType, index: number) => {
    return (
       <Hero slot={`slide-${index + 1}`} title={slide.title} subtitle={slide.subTitle} blurb={slide.blurb} ctaText={slide.ctaText} ctaUrl={slide.ctaUrl} imageUrl={slide.imageUrl} />
    )
  })}
</Carousel>
```

**Comment by Alex-S-Davies** [comment]
> I'm attempting to pull slide show cards from an API, and am encountering this limitation. Are there proposed dynamic workarounds?
> 
> ```
> <Carousel>
>   {slides.map((slide: HeroType, index: number) => {
>     return (
>        <Hero slot={`slide-${index + 1}`} title={slide.title} subtitle={slide.subTitle} blurb={slide.blurb} ctaText={slide.ctaText} ctaUrl={slide.ctaUrl} imageUrl={slide.imageUrl} />
>     )
>   })}
> </Carousel>
> ```

It looks almost exactly like the issue I faced.

Are you using any UI framework on the client side? If so, I would move the Carousel component into the UI framework if possible.

**Comment by jhedstrom** [comment]
Yeah, I'm using React, so will probably end up doing that. In the meantime I made this mess that works :)

```
<Carousel>
  {typeof slides[0] !== 'undefined' && (
    <Hero slot="slide-1" title={slides[0].title} subtitle={slides[0].subTitle} blurb={slides[0].blurb} ctaText={slides[0].ctaText} ctaUrl={slides[0].ctaUrl} imageUrl="https://picsum.photos/3000/2000" />
  )}
  {typeof slides[1] !== 'undefined' && (
  <Hero slot="slide-2" title={slides[1].title} subtitle={slides[1].subTitle} blurb={slides[1].blurb} ctaText={slides[1].ctaText} ctaUrl={slides[1].ctaUrl} imageUrl="https://picsum.photos/3000/2000" />
  )}
  {typeof slides[2] !== 'undefined' && (
  <Hero slot="slide-3" title={slides[2].title} subtitle={slides[2].subTitle} blurb={slides[2].blurb} ctaText={slides[2].ctaText} ctaUrl={slides[2].ctaUrl} imageUrl="https://picsum.photos/3000/2000" />
  )}
  {typeof slides[3] !== 'undefined' && (
  <Hero slot="slide-4" title={slides[3].title} subtitle={slides[3].subTitle} blurb={slides[3].blurb} ctaText={slides[3].ctaText} ctaUrl={slides[3].ctaUrl} imageUrl="https://picsum.photos/3000/2000" />
  )}
</Carousel>
```
