### ISSUE TITLE
Routing with catch-all in folder name

### ISSUE THREAD

**Issue by jbanety** [withastro/astro#5068]
### What version of `astro` are you using?

1.4.7

### Are you using an SSR adapter? If so, which one?

@matthewp/astro-fastify

### What package manager are you using?

yarn

### What operating system are you using?

Linux / Gitpod

### Describe the Bug

I'm trying to create routes with a catch-all in the path not in file : 
```
|- pages
   |- index.astro
   |- [...breadcrumbs]
      |- [collectionSlug].astro
      |- [productSlug].html.astro
```

Note the `.html` at the end of the second file. I used that to distinguish my category page and my product page.
With this setup, the suffix is ignored and all request goes to `[collectionSlug].astro`
This works without catch-all in folder name.
The goal is to have a SEO friendly url with collection breadcrumbs (`/my/parent/category` => category, `/my/parent/category/my-product.html` => product)
And if I change the suffix with `.dhtml` by example this works 🤨 
Any idea ?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-prkeiw

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Not sure, sounds like our routing perhaps is special-treating .html somehow...

**Comment by jbanety** [comment]
Yes. I don't known how routes are processed/generated?
Tell me and I'll give a look to this issue 😉

**Comment by bluwy** [comment]
Looks like this is caused by

https://github.com/withastro/astro/blob/a79a37cad549b21f91599ff86899e456d9dcc7df/packages/astro/src/vite-plugin-astro-server/request.ts#L26-L29

And it doesn't look like we can remove this. I'm also not sure if we want to support this? It's mixing both file and directory convention, which makes accessing the endpoints inconsistent. Perhaps we should warn when a user names something `*.html.astro` instead?

**Comment by matthewp** [comment]
@bluwy I feel like if we allow .html to match routes without an extension then that logic should be in the router and not in the dev server. The dev server shouldn't be manipulating the URL, imo.

**Comment by bluwy** [comment]
We could move the logic to the router, but the supporting `.html.astro` still feels confusing though. If I do a static build of the repro with `getStaticPaths()`, we get:

```
▶ src/pages/index.astro
  └─ /index.html (+4ms)
▶ src/pages/[...breadcrumbs]/[productSlug].html.astro
  └─ /my-product.html/index.html (+2ms)
▶ src/pages/[...breadcrumbs]/[collectionSlug].astro
  └─ /my-collection/index.html (+2ms)
```

We have to make the second output `/my-product.html`, which means a special route that's served as a file.

With `build.format: 'file'`:

```
▶ src/pages/index.astro
  └─ /index.html (+4ms)
▶ src/pages/[...breadcrumbs]/[productSlug].html.astro
  └─ /my-product.html.html (+2ms)
▶ src/pages/[...breadcrumbs]/[collectionSlug].astro
  └─ /my-collection.html (+2ms)
```

It's simpler to fix, but the general idea sounds like it could bring a footgun when the user starts writing anchor links. I'm thinking it would be better practice to enforce one way of file output.

**Comment by matthewp** [comment]
`/my-product.html/index.html` is indeed weird but the user they'll only see `/my-product.html`. It doesn't matter that this is not actually file, but a folder.

From my perspective Astro should not be opinionated about how you choose to display URLs. You should be able to do weird things. But indeed, we should not special case them. So you get `/my-product.html/index.html`.
