### ISSUE TITLE
injectRoute doesn't generate build pages

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [withastro/astro#5096]
### What version of `astro` are you using?

1.5.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Astro doesn't generate `injectRoute` routes from integrations, even if the pages are different depending on the url.

### Link to Minimal Reproducible Example

https://github.com/Alexandre-Fernandez/astro-injectRoute
`pnpm install`
`pnpm build`
=> The injectedRoute (`/secret`) is not generated in `/dist`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JulianCataldo** [comment]
I do use generated routes from injectRoute, for this integration and it works correctly:

- https://github.com/JulianCataldo/astro- content/blob/2d44a4eebb569202652e2d655e8ebca7d2440a13/packages/integration/config-setup.ts#L94
- https://github.com/JulianCataldo/astro-content/blob/2d44a4eebb569202652e2d655e8ebca7d2440a13/packages/gui/ssr-entrypoint.astro#L51

Maybe you're looking for the  `[...catchAll]` pattern ?

**Comment by matthewp** [comment]
Given that I'm going to close. `injectRoute` is not intended for creating duplicate routes. You can fix this pretty easily just by creating a component and pointing to that instead.

**Comment by francoromanol** [comment]
Hey Mathew, I have an issue here:

### Describe the Bug
`injectRoute` stop working when I call it more than once, if i comment one of the `injectRoute` calls, both works.

```
import { AstroIntegration } from 'astro';

export default (): AstroIntegration => {
  return {
    name: 'astro-i18next',
    hooks: {
      'astro:config:setup': async ({ injectRoute }) => {
        injectRoute({
          pattern: '/test',
          entryPoint: 'src/app/about-us.astro',
        });
        injectRoute({
          pattern: '/test2',
          entryPoint: '/src/pages/login/index.astro',
        });
      },
    },
  };
};
```

```
error   Cannot find module 'src/pages/login/index.astro'
  Require stack:
  - /Users/francopabloromanolosada/Franco/Work/covered-astro/node_modules/astro/dist/core/routing/manifest/create.js
Error: Cannot find module 'src/pages/login/index.astro'
Require stack:
...
```

**Comment by francoromanol** [comment]
Hey Matthew, I know it was not conceived to create duplicate routes but, is there any technical explanation on why it is not possible to do it? It could unlock nice possibilities such as custom routers (without file-based routing) and ccTLDs (Country Code Top-Level Domains) management (e.g `domain.com/houses` - `domain.es/casas`).
