### ISSUE TITLE
Using `generateScopedName` with `vite.css.modules` breaks CSS, even if classes are correctly outputted

### ISSUE THREAD

**Issue by JulianCataldo** [withastro/astro#5097]
### What version of `astro` are you using?

latest (stackblitz starter)

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

Adding this to the stackblitz starter:

```js
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  vite: {
    css: {
      modules: {
        generateScopedName: 'custom__[hash:base64:5]',
      },
    },
  },
});

```

We get the new classes:

```html
<h1 class="custom__TuMzL astro-JCQVOAF3">
	HELLO, this should be red

...
</h1>
```

But CSS isn't correctly associated anymore, it looks like it is just not inserted in the `<head/>` at all.

remove `generateScopedName`, and everything get back to normal, the text is red.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wdlcyk-khanxf?file=src/components/Card.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
https://github.com/vitejs/vite/pull/10514 should fix this. It's an inconsistency between client and server transformations of the CSS module, since `[hash:base64:5]` uses the filename to hash too.

**Comment by bluwy** [comment]
Closing as https://github.com/vitejs/vite/pull/10514 is merged. The fix should be brought upstream when we update to Vite 3.2
