### ISSUE TITLE
Dynamically creating a top level root page does not work with build format 'file'

### ISSUE THREAD

**Issue by christian-hackyourshack** [withastro/astro#5121]
### What version of `astro` are you using?

1.5.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I am trying to create a top-level root page dynamically according to the docs (https://docs.astro.build/en/core-concepts/routing/#example-dynamically-create-a-top-level-root-page) it works fine for the default build format directory, but when switching to build format 'file', the index.html is generated into the top-level project-directory instead of dist.

If someone points me to the place, where the file path is derived from the URL, then I could submit a pull request for this.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9r4avl?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Sorry about that, I'll check it out.
