### ISSUE TITLE
examples/ssr is not working

### ISSUE THREAD

**Issue by BeanWei** [withastro/astro#5124]
### What version of `astro` are you using?

1.5.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

https://github.com/withastro/astro/blob/9d4716f5ad4327196c33e28643a5b01c5584a68b/packages/integrations/node/src/http-server.ts#L27

stream.on('error') cannot handle index page, so when request `localhost:3000`, no logic to handle.

may be should do as that:
```js
stream.on("directory", () => {
  handler(req, res);
});
```

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/tree/main/examples/ssr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I can't reproduce this, are there comamnds/steps required to trigger the error?

**Comment by BeanWei** [comment]
@bluwy no special command/steps, just `pnpm i -> npm run build -> npm run server` .
i think this code logic is missing handle index page https://github.com/withastro/astro/blob/9d4716f5ad4327196c33e28643a5b01c5584a68b/packages/integrations/node/src/http-server.ts#L27

when request index page, if not setting base url that the file path will be a directory ->  `/xxx/xxx/dist/client/ `, is a valid pathname. so will not do `stream.on('error')` & `stream.on('file')` logic.

so i think could to do that:

```js
stream.on("directory", () => {
  handler(req, res);
});
```
to handle index page, if the filepath name is a directory, just do the handle logic

**Comment by bluwy** [comment]
Ah so I think I understand the issue now, so this is an issue that could theoretically happen only? Do you mean we should add:

```js
stream.on("directory", () => {
  forwardError = true;
});
```

instead? Feel free to send a PR if so! I think it's a nice to have.

**Comment by BeanWei** [comment]
@bluwy  @matthewp 
This actually only happens on windows, 
this code may be wrong:
https://github.com/withastro/astro/blob/e86723d931237b90c6bd919969fbfe7ea0e288e3/packages/integrations/node/src/http-server.ts#L21
from https://github.com/pillarjs/send readme:
```
send(req, path, [options])
Create a new SendStream for the given path to send to a res. The req is the Node.js HTTP request and the path is a urlencoded path to send (urlencoded, not the actual file-system path).
```
`the path is a urlencoded path to send (urlencoded, not the actual file-system path).`

after i test and see express source code at
https://github.com/expressjs/express/blob/8368dc178af16b91b576c4c1d135f701a0007e5d/lib/response.js#L419

maybe , i found the solution~

```diff
- const fileURL = new URL("." + req.url, client);
- const stream = send(req, fileURLToPath(fileURL), {
+ const stream = send(req, encodeURI(req.url), {
+   root: fileURLToPath(client),
    dotfiles: "deny"
  });
```
