### ISSUE TITLE
unable to get local issuer certificate when call api 

### ISSUE THREAD

**Issue by ziat1988** [withastro/astro#5128]
### What version of `astro` are you using?

1.5.1

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I have an API in localhost which is in SSL: https://localhost/api.
When I call this API from Astro component I have this error : "unable to get local issuer certificate".
Is there a way for Astro to deal this problem? 
I'm searching a way to integrate a key, pem in Astro without success. There's not a lot of docs for astro.
Thanks

### Link to Minimal Reproducible Example

nolink

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Not enough information to help, sorry. Please try the Discord channel for support.
