### ISSUE TITLE
Slots in layouts of layouts not replaced

### ISSUE THREAD

**Issue by AliveDevil** [withastro/astro#5129]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Applying regular old dependencies and hierarchies to layouts should work just fine.
E.g
- Create a layout, which defines some slots.
- Create a layout, which extends that layout, without tampering with any of the slots available
- Create a page which uses the layout, which extends the layout, where slots are defined, and inject a fragment into that slot

This should result in the fragment of that page to replace the default content, not displaying the default content discarding the page fragment content.

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/files/9824804/my-astro-site.tar.gz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jasikpark** [comment]
you probably want 

```astro
---
// Head.astro
---
<title>my astro site</title>
<slot name="head"/>
```

```astro
---
// Layout.astro
import Head from "./Head.astro";
---
<html>
  <head>
    <Head>
      <slot name="head" slot="head"/>
    </Head>
  </head>
  <p>hallo</p>
</html>
```

**Comment by bluwy** [comment]
Yep similarly in `layout.astro`, you need to forward the slots to achieve it:

```astro
---
// layout.astro
import Layout from './base.astro'
---

<Layout>
	<slot name="content" slot="content" />
	<slot />
</Layout>
```

Astro seems to be working fine here.
