### ISSUE TITLE
Issue deploying to Vercel: could not resolve chunk

### ISSUE THREAD

**Issue by thomasledoux1** [withastro/astro#5138]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When deploying to Vercel, I get the following error:
vc-file-system:entry.mjs:280:267: ERROR: Could not resolve "./chunks/BlogLayout.821cbd02.mjs"
When I have a look in the output from the build process (with npm run build locally), I can see only 1 chunk is created.
<img width="466" alt="Screenshot 2022-10-21 at 11 49 15" src="https://user-images.githubusercontent.com/10978632/197167394-ffa67b07-39c6-434c-93cf-ebae0d0586c3.png">
I added my Github repo here, not sure if I should create a Stackblitz instead since it seems to be closely related to the adapter?

Astro config:
```javascript
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import mdx from '@astrojs/mdx';
import { remarkReadingTime } from './src/utils/calculate-reading-time.mjs';
import vercel from '@astrojs/vercel/edge';

// https://astro.build/config
export default defineConfig({
  integrations: [
    tailwind({
      config: {
        applyBaseStyles: false,
      },
    }),
    mdx(),
  ],
  output: 'server',
  adapter: vercel(),
  markdown: {
    remarkPlugins: [remarkReadingTime],
    extendDefaultPlugins: true,
  },
});
```

When changing to @astrojs/vercel/serverless, I do get the BlogLayout chunk generated, so might be "edge" only.

### Link to Minimal Reproducible Example

https://github.com/thomasledoux1/website-thomas-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
What does your `functions` folder look like? I think it should be in there.

**Comment by thomasledoux1** [comment]
Hi @matthewp , thanks for the quick reply!
It doesn't appear in the functions folder either.
I clicked open all the folders so you can see the output here:
<img width="556" alt="Screenshot 2022-10-21 at 16 02 40" src="https://user-images.githubusercontent.com/10978632/197214683-d99ac9ea-1427-4aee-b5b9-d578684033ef.png">

**Comment by matthewp** [comment]
Hm, `static` is your frontend code. So it's not happening there. Are there no other folders created when you do the build?

**Comment by thomasledoux1** [comment]
No, no other folders created…

**Comment by thomasledoux1** [comment]
Btw it worked before on Astro@1.4.2 and @astro/vercel@2.0.1, see diff: 
![4D7D0FD4-0658-4651-8A62-1A9DC2A04E58](https://user-images.githubusercontent.com/10978632/197295431-195f117a-1b6b-485a-919f-70308f5a98f4.png)

**Comment by thomasledoux1** [comment]
Maybe @JuanM04 has an idea about this? I see you worked on most of the changes of the adapter?
