### ISSUE TITLE
CustomElementRegistry broken with Lit and Node SSR

### ISSUE THREAD

**Issue by ba55ie** [withastro/astro#5140]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

After building the node server crashes on the `customElements.define` call. It doesn't matter if you choose the `standalone` or `middleware`  (using `Express`) mode.

The dev server works without any problems.

```
TypeError: Cannot read properties of undefined (reading 'set') at CustomElementRegistry.define (/node_modules/@lit-labs/ssr/lib/dom-shim.js:100:32)
```

I have linked a Stackblitz project. Just run `npm start` (`astro build && npm run server`) to see the server crash.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kcxbgs

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by ba55ie** [comment]
I stumbled upon this bug after upgrading from Astro `1.4.7`. and `@astrojs/node 1.1.0`.

**Comment by matthewp** [comment]
Not sure what's up here. Seems like the server-shim.js is not running first. Any help here would be appreciated.

**Comment by ba55ie** [comment]
The problem is that the `CustomElementRegistry` shim provided by `Lit` gets overwritten by the `'@astrojs/webapi'` polyfill: 

https://github.com/withastro/astro/blob/b23f6b159694d1fc269f0d4ba110a545195aea4e/packages/webapi/src/lib/CustomElementRegistry.ts#L84
