### ISSUE TITLE
Unclear error with typo in import path

### ISSUE THREAD

**Issue by matthewp** [withastro/astro#5149]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Would be ideal of:

1. Error message was more descriptive / better written.
2. Told you which file was doing the importing.
3. Included a codeframe of where the error occurs.

<img width="948" alt="Screen Shot 2022-10-19 at 1 35 30 PM" src="https://user-images.githubusercontent.com/361671/197276265-30566cfb-bafb-4711-9ee1-94ca57aee4d3.png">

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Related vite issue https://github.com/vitejs/vite/issues/10002

**Comment by matthewp** [comment]
Hopefully @bluwy can help us out. Can Vite surface where this error originates from (which file)?

**Comment by bluwy** [comment]
The way Vite transforms for SSR makes it hard to know the importer. I've been trying to take a look at this error though but I can't find a way to repro it.

**Comment by bluwy** [comment]
Nevermind I found a repro while working on some stuff today 😄 https://stackblitz.com/edit/github-ad1c93?file=test.js. Will take a look this week.
