### ISSUE TITLE
HMR: Creating a file after @import does not refresh the browser

### ISSUE THREAD

**Issue by matthewp** [withastro/astro#5155]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

1. Add an `@import` to a file that does not exist in your Astro CSS.
2. Create that file.
3. It should refresh the browser but does not.
4. Works after manual refresh.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by zihan-ch** [comment]
It works. HMR just does not work when you delete everything in the file. If you added something, HMR will work.
