### ISSUE TITLE
tailwind plugin severely slows down hot-reloading with `Astro.glob(./*.mdx)`

### ISSUE THREAD

**Issue by luciodale** [withastro/astro#5166]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac M1 11.6

### Describe the Bug

Hot reloading becomes severely slowed when a `.astro` file uses the `Astro.glob` fn to import `.mdx` files. Reproducing the issue is easy.

deps:

```
"@astrojs/tailwind": "^2.1.1",
"@astrojs/mdx": "^0.11.4"
```

File: `index.astro`

Code:
```
---
const pages = await Astro.glob('./*.mdx')

console.log(
  'suuuper slow on change or when any other src file changes',
  pages.length
)
---

<div>index</div>
```

I am testing with about 70 `.mdx` files and hot-reloading takes about 7 seconds. 

Also, adding `mode: "jit"` in the tailwind configs doesn't solve the issue.

### Link to Minimal Reproducible Example

The above snippet in any astro project

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Does this happen if you remove Tailwind? I'm thinking this is not a tailwind issue but just the fact that recompiling 70 mdx files takes a while.

**Comment by luciodale** [comment]
When removing tailwind, the hot reloading is almost instant. I stripped out everything from my example to make sure it wasn’t something else interfering.

**Comment by matthewp** [comment]
Ah interesting, so I wonder what Tailwind is doing on file changes.

**Comment by luciodale** [comment]
I kinda need this to be fixed.. any pointers to where I should starting looking at if I wanna help?

**Comment by matthewp** [comment]
@luciodale Yeah that would be great. I'd be curious to know if these were `.md` files and not `.mdx` if it had the same slowdown. 

This is the mdx integration: https://github.com/withastro/astro/blob/main/packages/integrations/mdx/src/index.ts

I would probably add some `console.time()` in here to see if it's any one thing that's slow.

Otherwise, if this is purely Tailwind related then I would do the same within the Tailwind integration: https://github.com/withastro/astro/blob/main/packages/integrations/tailwind/src/index.ts

Perhaps Tailwind is recompiling for each of your mdx files and not once for all? I'm not really sure, this is going to take some research into what the underlying problem is.

**Comment by raffazizzi** [comment]
I am experiencing the same issue with 200+ `.md` (not `.mdx`) files. My site includes an index page that uses `Astro.glob()` to get frontmatter data and removing it solves the issue. The frustrating part is that hot reload is affected _everywhere_, including when modifying pages that do not involve the component with `Astro.glob()` or the MD files.

**Comment by luciodale** [comment]
I haven’t had time to try and debug this myself  :/.. Though, what helped a bit in my case was to get rid of the tailwind extension and just call it through the cli as a separate step.. it’s not integrated into Astro this way but it’s easy enough to setup from the tailwind docs. 

Also, it’s worth to mention that this fixed the problem temporarily because after the project kept growing the hot reloading slowness got worse by a lot.. but maybe that’s a different issue so idk

**Comment by raffazizzi** [comment]
Thanks @luciodale, that's a good tip. I'm going to experiment with that. My main issue is with DX, especially when I'm working on a components styling or debugging. I may also look into writing a script to move md files out under certain development conditions and move them back in when I'm done.

**Comment by jacobthesheep** [comment]
Is there any update on this?

**Comment by matthewp** [comment]
@jacobdalamb as far as I can tell, no one has done the investigation work to find out. Would you like to? See https://github.com/withastro/astro/issues/5166#issuecomment-1295409859

**Comment by raffazizzi** [comment]
FWIW this is no longer an issue for my project since updating to Astro 4.0.5

**Comment by lilnasy** [comment]
Thanks for the tip @raffazizzi! 

@luciodale Can you check if the recent versions make a difference?

**Comment by matthewp** [comment]
No response, and with Astro.glob being deprecated it seems unlikely this will be improved unless a contributor submits a PR. I suggest doing that if anyone is still having this problem.
