### ISSUE TITLE
`Astro.glob` results in invalid `src` with `@astrojs/image`

### ISSUE THREAD

**Issue by DerYeger** [withastro/astro#5171]
### What version of `astro` are you using?

1.4.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac/Linux

### Describe the Bug

Using `const assets = await Astro.glob('../assets/**/*')` to get all assets seems to include generated hashes for the `src` of images at build time.

This is caused by updating `@astrojs/image` from v0.3.7 to any later version.

I did not observe this behavior previously (before upgrading). My existing usages are now failing because the expected paths no longer match. 

My use case is having an image path in the frontmatter of MDX files.
In a page linking to all MDX files/pages, I'd like to show include each file's image.
This is no longer possible, since the filename is randomized (by the hash) at build time.

### Link to Minimal Reproducible Example

https://github.com/DerYeger/astrojs-image-asset-reproduction

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
What version was this working?

**Comment by matthewp** [comment]
So the bug here is that some of the paths are wrong, right? `/assets/apollo.9c6399b5.png` should be `/assets/projects/apollo.9c6399b5.png`

**Comment by DerYeger** [comment]
> So the bug here is that some of the paths are wrong, right? `/assets/apollo.9c6399b5.png` should be `/assets/projects/apollo.9c6399b5.png`

Yes 😄

**Comment by bholmesdev** [comment]
Hey @DerYeger! Could you provide a more minimal example? I tried this with a simplified `assets` folder of nested PNGs and could not replicate the issue. I've tried versions both with and without the Astro Image plugin: https://stackblitz.com/edit/github-8ffdl4?file=src/pages/index.astro

I also noticed your example's `src` does not include the `@astroimage` prefix as you'll see in the demo above. Have you tried installing `@astrojs/image@latest`?

**Comment by DerYeger** [comment]
Sorry, I haven't managed to create another example yet.

But I also noticed my initial finding was wrong.
Actually, `@astrojs/image` v0.4.0 and later are causing the issue.

**Comment by DerYeger** [comment]
After further investigation, it seems `@astrojs/image` v0.4.0 made it impossible to get the `src` of an image based on the file name defined in an MDX frontmatter.

I tried using both regular `import` statements and the included `getImage` helper like this:

```ts
const posts = await Promise.all((await Astro.glob('./blog/*.{md,mdx}'))
  .sort(
    (a, b) =>
      new Date(b.frontmatter.pubDate).valueOf() -
      new Date(a.frontmatter.pubDate).valueOf()
  )
  .filter((post) => !post.frontmatter.draft)
  .map(async (post) => {
    const image = await getImage({ src: `..${post.frontmatter.heroImage}`, height: 200, width: 1200, quality: 100 })
    return { data: post, image }
  }))
  ```
  
  But none of the images actually resolve.

**Comment by wulinsheng123** [comment]
> 

Does this bug still exist?

**Comment by wulinsheng123** [comment]
> > Does this bug still exist in the latest version?
> 
> Yes, though it seems to be a feature regression rather than a #bug.

https://github.com/DerYeger/jan-mueller/tree/renovate/all-minor-patch
this link can’t access 
Can you offer repo

**Comment by DerYeger** [comment]
> > > Does this bug still exist in the latest version?
> > 
> > 
> > Yes, though it seems to be a feature regression rather than a #bug.
> 
> https://github.com/DerYeger/jan-mueller/tree/renovate/all-minor-patch this link can’t access Can you offer repo

Sorry, the updated link is https://github.com/DerYeger/jan-mueller. The old `@astrojs/image` version is installed. Updating breaks the build as detailed.

**Comment by wulinsheng123** [comment]
> > > > Does this bug still exist in the latest version?
> > > 
> > > 
> > > Yes, though it seems to be a feature regression rather than a #bug.
> > 
> > 
> > https://github.com/DerYeger/jan-mueller/tree/renovate/all-minor-patch this link can’t access Can you offer repo
> 
> Sorry, the updated link is https://github.com/DerYeger/jan-mueller. The old `@astrojs/image` version is installed. Updating breaks the build as detailed.

Could you offer minimal demo ！
I tried to replicate this bug ,but it can’t replicate this bug

**Comment by DerYeger** [comment]
> > > > > Does this bug still exist in the latest version?
> > > > 
> > > > 
> > > > Yes, though it seems to be a feature regression rather than a #bug.
> > > 
> > > 
> > > https://github.com/DerYeger/jan-mueller/tree/renovate/all-minor-patch this link can’t access Can you offer repo
> > 
> > 
> > Sorry, the updated link is https://github.com/DerYeger/jan-mueller. The old `@astrojs/image` version is installed. Updating breaks the build as detailed.
> 
> Could you offer minimal demo ！ I tried to replicate this bug ,but it can’t replicate this bug

v0.11.1: https://stackblitz.com/edit/github-b4qvgh?file=sandbox.config.json

The reproduction in `index.astro` prints

```json
[
  {
    default: '/src/assets/favicon.svg',
    [Symbol(Symbol.toStringTag)]: 'Module'
  }
]
```

in dev and

```json
[
  {
    default: '/src/assets/favicon.svg',
    [Symbol(Symbol.toStringTag)]: 'Module'
  }
]
```

when building.

**Comment by DerYeger** [comment]
I created a much better (automated) reproduction: https://github.com/DerYeger/astrojs-image-asset-reproduction

**Comment by wulinsheng123** [comment]
> I created a much better (automated) reproduction: https://github.com/DerYeger/astrojs-image-asset-reproduction

`run dev` every thing was right.but only happened  on `run build` right？

**Comment by wulinsheng123** [comment]
> > I created a much better (automated) reproduction: https://github.com/DerYeger/astrojs-image-asset-reproduction
> 
> `run dev` Everything was right, but only happened on `run build` right？

**Comment by wulinsheng123** [comment]
> > > > > > Does this bug still exist in the latest version?
> > > > > 
> > > > > 
> > > > > Yes, though it seems to be a feature regression rather than a #bug.
> > > > 
> > > > 
> > > > https://github.com/DerYeger/jan-mueller/tree/renovate/all-minor-patch this link can’t access Can you offer repo
> > > 
> > > 
> > > Sorry, the updated link is https://github.com/DerYeger/jan-mueller. The old `@astrojs/image` version is installed. Updating breaks the build as detailed.
> > 
> > 
> > Could you offer minimal demo ！ I tried to replicate this bug ,but it can’t replicate this bug
> 
> v0.11.1: https://stackblitz.com/edit/github-b4qvgh?file=sandbox.config.json
> 
> The reproduction in `index.astro` prints
> 
> ```json
> [
>   {
>     default: '/src/assets/favicon.svg',
>     [Symbol(Symbol.toStringTag)]: 'Module'
>   }
> ]
> ```
> 
> in dev and
> 
> ```json
> [
>   [Module: null prototype] { default: '/assets/favicon.dddac387.svg' }
> ]
> ```
> 
> when building.

I think that this Description does not match #5171, I think if the extension had a problem, you should create a new issue.

**Comment by DerYeger** [comment]
> > I created a much better (automated) reproduction: https://github.com/DerYeger/astrojs-image-asset-reproduction
> 
> `run dev` Everything was right, but only happened on `run build` right？

Yes, the reproductions's README describes the issue.



> > > > > > > Does this bug still exist in the latest version?
> > > > > > 
> > > > > > 
> > > > > > Yes, though it seems to be a feature regression rather than a #bug.
> > > > > 
> > > > > 
> > > > > https://github.com/DerYeger/jan-mueller/tree/renovate/all-minor-patch this link can’t access Can you offer repo
> > > > 
> > > > 
> > > > Sorry, the updated link is https://github.com/DerYeger/jan-mueller. The old `@astrojs/image` version is installed. Updating breaks the build as detailed.
> > > 
> > > 
> > > Could you offer minimal demo ！ I tried to replicate this bug ,but it can’t replicate this bug
> > 
> > 
> > v0.11.1: https://stackblitz.com/edit/github-b4qvgh?file=sandbox.config.json
> > The reproduction in `index.astro` prints
> > ```json
> > [
> >   {
> >     default: '/src/assets/favicon.svg',
> >     [Symbol(Symbol.toStringTag)]: 'Module'
> >   }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in dev and
> > ```json
> > [
> >   [Module: null prototype] { default: '/assets/favicon.dddac387.svg' }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > when building.
> 
> I think that this Description does not match #5171, I think if the extension had a problem, you should create a new issue.

This first reproduction wasn't good. That's why I hid the comment and linked the repository.

**Comment by wulinsheng123** [comment]
@matthewp I think it's not Astro's bug. 
<img width="840" alt="image" src="https://user-images.githubusercontent.com/27261522/200837555-f1db35d7-dd37-4fcc-8b35-cb93946ea895.png">
Vite tool has deleted `a` folder, So in Astro also

**Comment by tony-sull** [comment]
@DerYeger That use case did get a little tricker after `@astrojs/image` started leaning on Vite to hash built asset filenames, sorry!

This can actually still be done with `import.meta.glob()`, the main trick is that you need to lazy load the globbed files and `Astro.glob()` will always eagerly load the files

```astro
---
const lazyImages = await import.meta.glob('../assets/**/*')

// lazyImages will look like `{ '../assets/social.png': [Function: ../assets/social.png] }`

const socialLoader = Object.entries(lazyImages)
    .find(([filename, loader]) => filename.endsWith('social.png'))

cons socialImage = await socialLoader()
---

<Image src={socialImage} alt='' />
```

When I've had to do this before I like moving it out a `.ts` helper file so my pages and components can call something like `loadImage(content.frontmatter.hero)`

**Comment by tony-sull** [comment]
Closing this out as expected **with a workaround** of using `import.meta.glob()`.  In case I'm mistaken and it's still a bug please reopen the issue and we'll take another look!

**Comment by DerYeger** [comment]
> Closing this out as expected **with a workaround** of using `import.meta.glob()`.  In case I'm mistaken and it's still a bug please reopen the issue and we'll take another look!

Thank you very much for the workaround! I wasn't aware of using lazy/eager globs as a solution.
