### ISSUE TITLE
Indentation format exceptions (`.astro`, `.md`)

### ISSUE THREAD

**Issue by mrienstra** [withastro/astro#5178]
Continuation of https://github.com/withastro/astro/pull/5168

As per [.prettierrc.js#L8](https://github.com/withastro/astro/blob/bf5ad72/.prettierrc.js#L8):
```js
useTabs: true,
```
And [.prettierrc.js#L20-L23](https://github.com/withastro/astro/blob/bf5ad72/.prettierrc.js#L20-L23):
```js
files: ['.*', '*.json', '*.md', '*.toml', '*.yml'],
options: {
  useTabs: false,
},
```
... `.md` files should be indented with spaces, and `.astro` files should be indented with tabs, but currently there are exceptions (roughly 37% of `.astro` files & 11% of `.md` files). I'm happy to open two PRs, one to remove tabs from `.md` files, and one to remove spaces from `.astro` files, thought I should get a thumbs up beforehand to make sure this is wanted.

dot files, `.json` files, `.toml` files, & `.yml` are already as they should be (indented with spaces only, no tabs)
(searched for `^\t` with "files to include" set to `**/.**,.json,.toml,.yml`)

|  | with both | spaces only | tabs only | neither | total |
|--|-----------|-------------|-----------|---------|-------|
| `.astro` 🚀 | 60 (10%) | 161 (27%) | 259 (43%) | 117 (20%) | 597 |
| `.md` ⬇️ | 9 (5%) | 50 (29%) | 11 (6%) | 105 (60%) | 175 |
| `examples` `.astro` 🚀 | 4 (6%) | | 62 (94%) | | 66 |
| `examples` `.md` ⬇️ | 1 (3%) | 5 (13%) | | 32 (84%) | 38 |
| `packages/markdown` (fixtures) `.astro` 🚀 | 1 (3%) | 11 (34%) | 18 (56%) | 2 (6%) | 32 |
| `packages/markdown` `.astro` 🚀 | | | 1 (100%) | | 1 |
| `packages/markdown` `.md` ⬇️ | | 5 (28%) | 4 (22%) | 9 (50%) | 18 |
| `packages/integrations` (fixtures) `.astro` 🚀 | 9 (20%) | 5 (11%) | 25 (54%) | 7 (15%) | 46 |
| `packages/integrations` `.astro` 🚀 | | | 2 (100%) | | 2 |
| `packages/integrations` `.md` ⬇️ | 1 (5%) | 18 (86%) | | 2 (10%) | 21 |
| `packages/astro` `.astro` 🚀 | | | 4 (100%) | | 4 |
| `packages/astro` `.md` ⬇️ | 6 (7%) | 19 (21%) | 6 (7%) | 58 (65%) | 89 |
| `packages/astro` (fixtures) `.astro` 🚀 | 46 (10%) | 145 (33%) | 146 (33%) | 108 (24%) | 445 |
| `packages/astro-prism` `.astro` 🚀 | | | 1 (100%) | | 1 |
| `packages/astro-prism` `.md` ⬇️ | | 1 (100%) | | | 1 |
| `packages/create-astro` `.md` ⬇️ | | | | 1 (100%) | 1 |
| `packages/astro-rss` `.md` ⬇️ | 1 (100%) | | | | 1 |
| `packages/telemetry` `.md` ⬇️ | | | | 1 (100%) | 1 |
| `packages/webapi` `.md` ⬇️ | | | 1 (100%) | | 1 |

(disclaimer: the numbers in the table above are based off of regex searches, I know there are a few case in which e.g. `^ {2}` appears in `.astro` files inside string literals, so take them with a grain of salt)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Closed by https://github.com/withastro/astro/pull/5241

**Comment by mrienstra** [comment]
@matthewp, is `#5241` related to this issue? Looks like `#5172` is the issues that corresponds to `#5241`.
