### ISSUE TITLE
Error is thrown when using CSS in `<style>` tag if `srcDir == root`

### ISSUE THREAD

**Issue by MrFoxPro** [withastro/astro#5183]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

static

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

```
Failed to load module for ssr: /home/projects/github-hqskis/pages/index.astro?astro&type=style&index=0&lang.css
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hqskis?file=pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
let me mark.

**Comment by wulinsheng123** [comment]
Will happen on your local？

**Comment by wulinsheng123** [comment]
https://stackblitz.com/edit/github-efreff?file=src%2Fpages%2Findex.astro,tsconfig.json&on=stackblitz
it's not happen in the last version。

**Comment by MrFoxPro** [comment]
> Will happen on your local？

it was. Ill try with latest.

**Comment by matthewp** [comment]
Please file a new issue if you see it happening again, thanks!

**Comment by wulinsheng123** [comment]
> Please file a new issue if you see it happening again, thanks!
I found that set object  `{output: 'static',
  srcDir: '.',
  root: '.',}` in `astro.config.mjs` and Moving the `src/page` folder to the root directory. then putting CSS <style> tag in index.astro.
emerge this error `Could not import "/workspace/astro/examples/minimal/pages/index.astro?astro&type=style&index=0&lang.css"`

so I want to ask you 
can I move `page` this folder?

**Comment by MrFoxPro** [comment]
Error is happening even in 1.6.1
