### ISSUE TITLE
[@astrojs/image] Original format not inferred from headers on remote images

### ISSUE THREAD

**Issue by itsmatteomanf** [withastro/astro#5186]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When leaving the `formats` array to the default choices, which should be AVIF+WebP+OriginalFormat, when the file doesn't have an extension, which is the case for the vast majority of API driven third party sources, makes the only formats generated AVIF+WebP.

The format can be easily inferred from the headers on the image response from the service.

These two options, will generate different code, while technically being the same API and same file. The second is the correct one.

```html
<Picture
  src="https://picsum.photos/id/982/600/600"
  widths={[600]}
  aspectRatio={1}
/>
<Picture
  src="https://i.picsum.photos/id/982/600/600.jpg?hmac=etUnxUawipNL4Pg6f0xivch-EcOY1T0erLJog8QDGw0"
  widths={[600]}
  aspectRatio={1}
/>
```

```html
<picture class="astro-EI35XRNH">
  <source type="image/avif" srcset="/assets/600_2k5Rer.avif 600w" class="astro-EI35XRNH">
  <source type="image/webp" srcset="/assets/600_2tcCD7.webp 600w" class="astro-EI35XRNH">
  <img src="/assets/600_1deUIz.webp" class="astro-EI35XRNH" loading="lazy" decoding="async">
</picture>


<picture class="astro-EI35XRNH">
  <source type="image/avif" srcset="/assets/600_2qQOan.avif 600w" class="astro-EI35XRNH">
  <source type="image/webp" srcset="/assets/600_Z2udyeS.webp 600w" class="astro-EI35XRNH">
  <source type="image/jpeg" srcset="/assets/600_Td8wy.jpg 600w" class="astro-EI35XRNH">
  <img src="/assets/600_19ecgO.jpg" class="astro-EI35XRNH" loading="lazy" decoding="async">
</picture>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-issue-5186?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! We're slowly entering maintenance mode for `@astrojs/image` and won't be adding new features. As such, I'll be closing this issue.

fwiw, it is possible to integrate this in a custom service using the new `astro:assets` API.

**Comment by itsmatteomanf** [comment]
Hello @Princesseuh, happy to see it being integrated, but there are a ton of missing features from this package in the new integrated assets features, including remote image optimization.

Good docs and more features are really needed.
