### ISSUE TITLE
@astrojs/node ignores port specified in user config

### ISSUE THREAD

**Issue by sramam** [withastro/astro#5189]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

With an astro config:
```
export default defineConfig({
  output: "server",
  adapter: node({
    mode: 'standalone',
    port: 4000,
  }),
})
```

`node dist/server/entry.mjs` sets the port to 3000.

I think this is because the user config is being explicitly [overwritten by the defaults](https://github.com/withastro/astro/blob/main/packages/integrations/node/src/index.ts#L40)

Shouldn't this block read the following?
```
_options = {
  host: config.server.host,
  port: config.server.port,
  ...userOptions,
  client: config.build.client?.toString(),
  server: config.build.server?.toString(),
};
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ovfs8n?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You don't pass a port through the adapter options like that. `mode` is the only option you pass. You set the port in your astro.config.mjs with:

```js
export default {
  server: {
    port: 4000
  }
};
```

**Comment by sramam** [comment]
ah - thank you.  
Was a bit confusing since the port is meant for the adaptor. Wasn't obvious from a casual perusal of the code. 

Also, thanks for the great work and quick turn around. Much appreciated.
