### ISSUE TITLE
@astro/sitemap does not generate robots.txt

### ISSUE THREAD

**Issue by ansidev** [withastro/astro#5219]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

@astro/sitemap does not generate robots.txt automatically.

Why it should be?

- A simple robots.txt looks like this:

```
# I, for one, welcome our new robotic overlords

User-agent: *
Allow: /

Sitemap: https://astro.build/sitemap-index.xml
```

The last line contains the site URL.

Currently, we must add `robots.txt` manually (the site URL is a hard code value).

Site URL can be a dynamic value and we can read it from the environment variable. It helps us deploy one source code to multiple servers, just need to change the site URL via the environment variable.

### Link to Minimal Reproducible Example

https://github.com/withastro/astro.build/blob/main/public/robots.txt

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
`robots.txt` has many uses beyond the sitemap so it seems out of scope for the sitemap integration to take care of generating it.

Regarding generating a `robots.txt` file: this is a good fit for a file endpoint. Add a `src/pages/robots.txt.js` file and use it to generate the file contents based on environment variables etc. You can read more about endpoints here: https://docs.astro.build/en/core-concepts/endpoints/#static-file-endpoints
