### ISSUE TITLE
[@astrojs/image] Removal of Class from <Picture> Element

### ISSUE THREAD

**Issue by SaintSin** [withastro/astro#5223]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

ppm

### What operating system are you using?

Mac

### Describe the Bug

Removing the class from the `<picture>` element renders it unusable in many css grid layouts, as row and column styles need to apply to the picture, not its children.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please provide a reproduction.
