### ISSUE TITLE
No builtin Astro approach to move files to the root of the `dist` folder.

### ISSUE THREAD

**Issue by awwong1** [withastro/astro#5245]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

See also Discord support thread: https://discord.com/channels/830184174198718474/1032513921153761330

> Can  a file (e.g. `_redirects` ) be moved into the dist folder on `npx astro build`?
> 
> If I have this file within public, it gets put into dist/static.
> 
> If I create this file manually, it is overwritten on each build.
> 
> This is necessary for Cloudflare Pages redirects.
> https://developers.cloudflare.com/pages/platform/redirects
> 
> Thanks!

### Link to Minimal Reproducible Example

https://github.com/udiaca/u0.vc

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
So I guess this is happening because the Cloudflare adapter sets up the `dist/static` folder here: https://github.com/withastro/astro/blob/main/packages/integrations/cloudflare/src/index.ts#L48

If `_redirects` is a special Cloudflare thing maybe it should support that file directly?

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/5347
