### ISSUE TITLE
injectRoute dose not work with dynamic route

### ISSUE THREAD

**Issue by BeanWei** [withastro/astro#5247]
### What version of `astro` are you using?

1.6.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

`pattern: '/test-[slug]',` => NG, can't request `http://localhost:3000/test-123`, just `http://localhost:3000/test-[slug]` 

`pattern: '/[slug]',` => OK

### Link to Minimal Reproducible Example

https://github.com/BeanWei/astro-bug/tree/main/astro-inject-route-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by BeanWei** [comment]
https://github.com/withastro/astro/blob/7d678c9ed05a33380a2153df54abdf87d374f970/packages/astro/src/core/routing/manifest/create.ts#L343

only support `[slug]` ?

**Comment by bholmesdev** [comment]
Thanks @BeanWei! Just confirmed this in a stackblitz as well. Linking for reference: https://stackblitz.com/edit/github-ozzoxi?file=src%2Fpages%2Ftest-[slug].astro,astro.config.mjs,endpoint.ts

Also looks like `test-[slug]` will work as a standard page when _not_ injected. Worth fixing this one 👍

**Comment by matthewp** [comment]
https://stackblitz.com/edit/github-ozzoxi-qurph4?file=src%2Fpages%2Findex.astro,astro.config.mjs,src%2Fcomponents%2Ftest.astro
