### ISSUE TITLE
template: navbar `isActive` doesn't work on home page in the personal site template

### ISSUE THREAD

**Issue by nexxeln** [withastro/astro#5248]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

pnpm

### What operating system are you using?

WSL Ubuntu

### Describe the Bug

![demo](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/brave_xjXfn86vhy.gif)

There's no indication for current route in home, it only works in routes other than the index route.

The current implementation is this: 
```ts
const { href, class: className, ...props } = Astro.props;
const isActive = href === Astro.url.pathname.replace(/\/$/, '');
```

This works for all routes except the index route, because `Astro.url.pathname` returns `/` and that gets removed by the `.replace` and becomes and empty string.

The most straightforward fix would be to use just `Astro.url.pathname`, the problem with this is that in production (at least on Vercel), `Astro.url.pathname` returns the path with a trailing slash, for example, `/blog` would be `/blog/`. So we definitely need to replace on all paths except the index route.

This is the fix I have come up with
```ts
const { href, class: className, ...props } = Astro.props;
let pathnameWithoutTrailingSlash = Astro.url.pathname.replace(/\/$/, "");
if (href === "/" && pathnameWithoutTrailingSlash === "") {
  pathnameWithoutTrailingSlash = "/";
}
const isActive = href === pathnameWithoutTrailingSlash;
```
However this feels really hacky and I'm unable to think of ways to simplify this. Would love some input on this.

I have linked a github repo below, the `main` branch has the current way of doing this where you can see the bug. There is also a `possible-fix` branch which has the solution which works in production. I will link the deployed versions  here too for convenience:

Deployed version with bug:  https://astro-blog-template-navbar-issue-repro-7l8iwxya2-nexxeln.vercel.app/
Deployed version with proposed fix: https://astro-blog-template-navbar-issue-repro-4iofgo5dp-nexxeln.vercel.app/

### **Edit**: 
With the help of @Yevhenii-Bakhmat, we came up with a simplified solution:
```ts
const { href, class: className, ...props } = Astro.props;

const pathname = Astro.url.pathname;
const path = pathname.match(/^\/$/) ? pathname : pathname.slice(0, -1);

const isActive = href === path;
```

Deployed version with the new and simplified fix: https://astro-blog-template-navbar-issue-repro-putckyo19-nexxeln.vercel.app

### Link to Minimal Reproducible Example

https://github.com/nexxeln/astro-blog-template-navbar-issue-repro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Yevhenii-Bakhmat** [comment]
> pathname = '/test'
> const path = pathname.match(/^\/$/) ? pathname : pathname.slice(0, -1);
> // yields: '/tes' which is an unexpected behavior

pathname always has / in the end

**Comment by nexxeln** [comment]
> I don't believe your simplified solution generalizes well:
> 
> ```js
> pathname = '/test'
> const path = pathname.match(/^\/$/) ? pathname : pathname.slice(0, -1);
> // yields: '/tes' which is an unexpected behavior
> ```
> 
> 
> Catching the the null case may be simpler:
> 
> ```js
> const isActive = href === (Astro.url.pathname.replace(/\/$/, '') || '/')
> // but href = '' will fail, possible unexpected
> 
> const isActive = href === (Astro.url.pathname.replace(/\/$/, '') || href==='' ? '' : '/' )
> // may be worth considering
> ```
> 
> Otherwise, perform equal operations:
> 
> ```js
> const isActive = href.replace(/\/$/, '') === Astro.url.pathname.replace(/\/$/, '')
> ```

Yeah this might be worth adding.

At least on Vercel there's always the trailing slash, not sure how this works elsewhere.

**Comment by nexxeln** [comment]
> Thats sort of beside the point. If you want to build robust code/software, you want your code to have expected behavior regardless of any guarantees you may think you have.

This makes sense, I'll be sure to add a null check if I do make a PR. Thank you for the feedback.

**Comment by gronagatan** [comment]
@Yevhenii-Bakhmat 
> pathname always has / in the end

Unfortunately it doesn't. Only in dev, not when running build. Not for me at least.

**Comment by bholmesdev** [comment]
Love the conversation here! If I could weigh in, I'd probably refactor your check to this:

```ts
const { pathname } = Astro.url;
const isActive = href === pathname || href === pathname.replace(/\/$/, '');
```
This way, it'll keep working whether an `href` has trailing slashes or not, and will handle the homepage use case. Let me know if you prefer this @nexxeln!

**Comment by bholmesdev** [comment]
Also, feel free to open a PR with your change and tag me for review! Most of the fixes I've seen here would be welcome, no need to feel pressured by my thoughts :)

**Comment by nexxeln** [comment]
> Also, feel free to open a PR with your change and tag me for review! Most of the fixes I've seen here would be welcome, no need to feel pressured by my thoughts :)

I prefer your fix! I'll make a PR soon.
