### ISSUE TITLE
Astro CLI is slow

### ISSUE THREAD

**Issue by Princesseuh** [withastro/astro#5255]
### What version of `astro` are you using?

1.6.1

### Are you using an SSR adapter? If so, which one?

N/A

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

The Astro CLI seems to have a considerable overhead on the functions ran, the best example is the `astro docs` command, on my system it takes around a second to execute while running the original command being wrapped (`open` on macOS) takes only 75ms

![image](https://user-images.githubusercontent.com/3019731/199012470-d1233229-75ca-4009-8f5e-ba5676ee05f2.png)

![image](https://user-images.githubusercontent.com/3019731/199012506-d4b38236-e9f0-4be2-939a-d04553138fc8.png)

I'm never expecting `astro docs` to be as fast the original command (not exactly a zero cost abstraction), but I do believe we can make it much much faster

Please note that this is not exclusive to the `docs` command, this affects the entire CLI: 
![image](https://user-images.githubusercontent.com/3019731/199015576-aad4790b-1bf2-4ba3-84bc-ae9850c43ccc.png)

This is most likely related to [all the imports in this file](https://github.com/withastro/astro/blob/25a6360a60d5029b861725a58541f7fad93ab434/packages/astro/src/cli/index.ts), as removing them manually seems to increase the performance - perhaps some of them could be moved to dynamic imports?

### Link to Minimal Reproducible Example

any https://astro.new/ project

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Probably `docs` is the most dissimilar of the CLI commands and doesn't need any of that stuff. We could likely move most of that code to another module and load it when it is used by the other commands.
