### ISSUE TITLE
`create-astro` doesn't respect system proxy config or environment variables

### ISSUE THREAD

**Issue by yonkeltron** [withastro/astro#5256]
### What version of `astro` are you using?

1.6.1

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

yarn

### What operating system are you using?

macOS

### Describe the Bug

I am unable to initialize a new project with `astro-create` due to it not following the system proxy settings or respecting the proxy environment variables I have in place.

The following variables are set:

```
HTTP_PROXY
HTTPS_PROXY
http_proxy
https_proxy
ALL_PROXY
all_proxy
 ```

```
$ create-astro

╭─────╮  Houston:
│ ◠ ◡ ◠  I'll be your assistant today.
╰─────╯

 astro   v1.6.1 Launch sequence initiated.

? Where would you like to create your new project? › potato
✔ Where would you like to create your new project? … potato
✔ How would you like to setup your new project? › a few best practices (recommended)
          ■■▶ Copying project files...(node:5863) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
          ■■▶ Copying project files...Failed to download https://github.com/withastro/astro/archive/latest.tar.gz: 401 authenticationrequired
```

Eager to help understand what's wrong, unfortunately I can't create a minimal example due to it being isolated to the corporate network I'm currently on. Sorry!

How else can I test or provide more info?

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for reporting @yonkeltron! Dang, this is indeed a tricky one to replicate. I'll say we use [giget](https://github.com/unjs/giget) under-the-hood to fetch project templates, so that project would likely need tweaks to respect environment variables for network proxies. May be worth:
- writing a small-scale script that uses `giget`'s JS API to replicate
- if it still fails, file an issue on their repo with that minimal reproduction

Hope that helps!

**Comment by natemoo-re** [comment]
There's actually an upstream issue to unblock this, as well!

https://github.com/unjs/giget/issues/23

**Comment by danielroe** [comment]
This has been merged and released in `giget@1.0.0`.

**Comment by yonkeltron** [comment]
Just a bit more info here:

```

╭─────╮  Houston:
│ ◠ ◡ ◠  Time to build a sweet new website.
╰─────╯

 astro   v1.9.2 Launch sequence initiated.

✔ Where would you like to create your new project? … panda
✔ How would you like to setup your new project? › a few best practices (recommended)
          ■■▶ Copying project files...Failed to download https://github.com/withastro/astro/archive/latest.tar.gz: 401 authenticationrequired
```

**Comment by yonkeltron** [comment]
FYI I can reproduce this error still in the 2.0 release.

`create-astro@2.0.2`

`astro   v2.0.4 Launch sequence initiated.`

**Comment by yonkeltron** [comment]
Just an update that this still fails with `create-astro@3.0.0`:

```
╭─────╮  Houston:
│ ◠ ◡ ◠  Let's claim your corner of the internet.
╰─────╯

 astro   v2.0.9 Launch sequence initiated.

   dir   Where should we create your new project?
         ./panda

  tmpl   How would you like to start your new project?
         Include sample files
Failed to download https://github.com/withastro/astro/archive/latest.tar.gz: 401 authenticationrequired
```

**Comment by calebdwilliams** [comment]
I can confirm this issue still exists on the latest version (2.5.7 as of this post). This issue should be re-opened.

**Comment by calebdwilliams** [comment]
Specifically this is failing with `create-astro@3.1.5`

**Comment by yonkeltron** [comment]
Can confirm this is still an issue with `create-astro@3.1.6`:

```console
$ create-astro

╭─────╮  Houston:
│ ◠ ◡ ◠  Initiating launch sequence...
╰─────╯

 astro   v2.6.0 Launch sequence initiated.

   dir   Where should we create your new project?
         ./panda

  tmpl   How would you like to start your new project?
         Include sample files
      ▲  error Failed to download https://github.com/withastro/astro/archive/latest.tar.gz: 401 authenticationrequired
```

**Comment by teehemkay** [comment]
I can confirm this is still an issue with create-astsro@4.3.2

```sh
npm create astro@latest -- --template starlight


 astro  Launch sequence aborted.

      ▲  error Unable to connect to the internet.
```

**Comment by indefinitelee** [comment]
this is an issue for me with npm create astro@latest I am behind a corporate firewall and using an internal registry which is set in the .npmrc

**Comment by rafaelpirolla** [comment]
I can confirm this is still an issue with create-astsro@4.11.0

**Comment by PaznerA** [comment]
Same issue here on Ubuntu behind proxy with _yarn create astro@latest_.
Both npm, and yarn can download deps without issue(e.g. create react app work fine), but Astro fails on create command.
```

yarn create v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-astro@4.11.0" with binaries:
      - create-astro
[###############################] 31/31

 astro  Launch sequence aborted.

      ▲  error Unable to connect to the internet.
error Command failed.
Exit code: 1
```
