### ISSUE TITLE
`eager` flag in `import.meta.glob(..., { eager: true })` causes astro build to fail

### ISSUE THREAD

**Issue by manunamz** [withastro/astro#5265]
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

macos

### Describe the Bug

When calling `import.meta.glob(route,{eager:true})` inside of `astro.config.mjs`, I get the following (vite?) error:

```
Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .md file format, or if it's an asset, add "**/*.md" to `assetsInclude` in your configuration.

Parse failure: Assigning to rvalue (1:2)
Contents of line 1: ---
Parse failure: Assigning to rvalue (1:2)
Contents of line 1: ---
Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .md file format, or if it's an asset, add "**/*.md" to `assetsInclude` in your configuration.
Parse failure: Assigning to rvalue (1:2)
Contents of line 1: ---
12:03:46 PM [astro] Unable to load /Users/astro-project/astro.config.mjs

 error   Parse failure: Assigning to rvalue (1:2)
  Contents of line 1: ---
Error: Parse failure: Assigning to rvalue (1:2)
Contents of line 1: ---
    at ssrTransformScript (file:///Users/astro-project/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:52872:15)
    at ssrTransform (file:///Users/astro-project/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:52847:12)
    at Object.ssrTransform (file:///Users/astro-project/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:62123:20)
    at loadAndTransform (file:///Users/astro-project/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:37396:24)
```

The error says to look at [`assetsInclude`](https://vitejs.dev/config/shared-options.html#assetsinclude), which is a Vite config.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xxw2lw?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
@MoustaphaDev Ah, right you are! Vite features like `import.meta.glob` and `import.meta.env` are _not_ accessible from your config file. Closing this as expected behavior, but I recommend trying [packages like `fast-glob`](https://github.com/mrmlnc/fast-glob) for use in config files.
