### ISSUE TITLE
Error is thrown when using CSS in `<style>` if `srcDir == root`

### ISSUE THREAD

**Issue by MrFoxPro** [withastro/astro#5267]
### What version of `astro` are you using?

1.6.1

### Are you using an SSR adapter? If so, which one?

static

### What package manager are you using?

turbo

### What operating system are you using?

Linux / Stackblitz

### Describe the Bug

Failed to load module for ssr: /home/projects/github-hqskis/pages/index.astro?astro&type=style&index=0&lang.css

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hqskis?file=pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
I’m looking for this

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/5298
