### ISSUE TITLE
css build background-image error

### ISSUE THREAD

**Issue by J-env** [withastro/astro#5268]
### What version of `astro` are you using?

1.6.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

css: 
<img width="780" alt="image" src="https://user-images.githubusercontent.com/25259920/199177732-803fce7a-8228-48ab-9d2b-8084e5f731eb.png">

npm run build:
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/25259920/199178031-a1070913-5a1e-40db-ab04-ad971d2688e7.png">

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for filing @J-env! Since I'm not sure what your project config is (I assume you're using import aliases?), I can't replicate this issue on my end. Can you create a minimal reproduction using a template on [astro.new](https://astro.new) and attach a link in your issue description?

**Comment by J-env** [comment]
@bholmesdev 
[This should be the vite prompt](https://github.com/vitejs/vite/blob/c53ffec3465d2d28d08d29ca61313469e03f5dd6/packages/vite/src/node/plugins/css.ts#L224)
```js
const resolved = await resolveUrl(url, importer)
if (resolved) {
  return fileToUrl(resolved, config, this)
}
if (config.command === 'build') {
  // #9800 If we cannot resolve the css url, leave a warning.
  config.logger.warnOnce(
    `\n${url} referenced in ${id} didn't resolve at build time, it will remain unchanged to be resolved at runtime`
  )
}
return url
```

**Comment by bholmesdev** [comment]
@J-env I understand that, but I'm unsure how to replicate this. Please provide an example from an https://astro.new template and share a link here, thanks!

**Comment by J-env** [comment]
@bholmesdev  https://codesandbox.io/s/priceless-neumann-7t1yt5?file=/src/pages/index.astro
<img width="743" alt="image" src="https://user-images.githubusercontent.com/25259920/199652427-81cf27c1-99e2-4e1b-b1a2-d3d7d8d44c90.png">

**Comment by wulinsheng123** [comment]
> @bholmesdev https://codesandbox.io/s/priceless-neumann-7t1yt5?file=/src/pages/index.astro <img alt="image" width="743" src="https://user-images.githubusercontent.com/25259920/199652427-81cf27c1-99e2-4e1b-b1a2-d3d7d8d44c90.png">

![image](https://user-images.githubusercontent.com/27261522/202348211-8e98d8ad-8765-4d1a-a5da-a6e3e5fd0f53.png)

I tried , but nothing

**Comment by matthewp** [comment]
I'm also unable to create @wulinsheng123 

Going to close, if you can provide more information on how to recreate I'd be happy to reopen the issue.

**Comment by riolly** [comment]
I have the same issue working with background-image using URL with tailwind.
Do you figure out the solution @J-env ?

**Comment by riolly** [comment]
Oh, I just don't import the URL correctly.

wrong
`images/picture.svg`
correct
`/images/picture.svg`

**Comment by abegehr** [comment]
Ran into the same issue. The reason was that Astro bundles the css into `_astro/indexXYZ.css`. When the browser then tries to access `url(images/picture.svg)` (relative path) from the css file, it fetches `your.domain.com/_astro/images/picture.svg` (404). Using `url(/images/picture.svg)` (absolute path) correctly resolves to `your.domain.com/images/picture.svg`. Took me a few thought, since the relative path does with in dev mode.

**Comment by danielo515** [comment]
> Ran into the same issue. The reason was that Astro bundles the css into `_astro/indexXYZ.css`. When the browser then tries to access `url(images/picture.svg)` (relative path) from the css file, it fetches `your.domain.com/_astro/images/picture.svg` (404). Using `url(/images/picture.svg)` (absolute path) correctly resolves to `your.domain.com/images/picture.svg`. Took me a few thought, since the relative path does work in dev mode.

Is there any way to enforce this failing in dev mode so we are not fooled with stupid errors like this?
Thanks

**Comment by daqm3d** [comment]
Hello, I have had this same problem when using **'background-image: url(./city.png);'** in CSS, I need it this way to be able to animate it with **'background-position-x' **, The only solution I have found for now is the following:

We create an alias for dynamic routes in tsconfig.json
```javaScript
{
  "extends": "astro/tsconfigs/base",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
      "#/*": ["./public/*"]
    }
  }
}
```

Then in the template I assign a variable for the path, and we pass it to the html with inline css:
```javaScript
---
import imgBody from '#/city.png'; 
---
<html lang="es">
    <div
          class="print bg"
          style={{
            backgroundImage: `url(${imgBody.src})`,
          }}
        >
    </div>
</html>
```

If you do not need to use the background-image, you can use the html img tag and this problem will not be generated
```html
<html lang="es">
  <img src="./DAQM3D.jpg"  />
</html>
```

**Comment by daqm3d** [comment]
Another solution I found is the following:
we import the image that we want to use with **javascript**
```
  ---
  import plantillaFondoPrint from '#/plantillaFondoPrint.webp';
  ---
```
Then in the **CSS** part we do the following assignment:
```
<style define:vars={{ plantillaFondoPrint: `url(${plantillaFondoPrint.src})` }}>
 dir{
      background-image: var(--plantillaFondoPrint);
 }
<style/>
```
This allows us to use the routes that are created in both **DEV** and **BUILD** within the same file,
Finally, if we wanted to pass the information to a child component so that it can use it alone 
We would have to pass it as a **PROPS** and repeat the above.
```
<html lang="es">
  <Header backgroundUrl={`url(${backgroundUrl.src})`} />
</html>
```
