### ISSUE TITLE
Error when using @motionone/vue

### ISSUE THREAD

**Issue by taoguangc** [withastro/astro#5275]
### What version of `astro` are you using?

1.6.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Now I installed astro and integrated vue, then installed motion according to https://motion.dev/vue/quick-start, and wrote a sample into the vue component and referenced it on the home page, but an error occurred.
**The screen prompt information is:**
Failed to resolve entry for package "@motionone/vue". The package may have incorrect main/module/exports specified in its package.json.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hz67ks?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
`@motionone/vue` `package.json` `main` is missing https://publint.bjornlu.com/@motionone/vue@10.14.3. I'd suggest reporting this upstream.
