### ISSUE TITLE
Inconsistent handling of default imports (exports) in `astro dev` and `astro build`

### ISSUE THREAD

**Issue by jsve** [withastro/astro#5277]
### What version of `astro` are you using?

1.6.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When importing an external library (private npm package) i get inconsistencies between running `dev` and `build`.

When running `dev` imports work as expected, meaning I'm able to import both the default and named exports successfully. However, when running `build` I get the notorious:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### Example

```javascript
import Module from '@external/component';
```

In `dev`, importing Module gives me the expected React.FC:
```javascript
[Function: Module] { propOne: '', propTwo: '' }
```

In `build` Module evaluates to:
```javascript
{
  default: [Function: Module] { defaultProps: { propOne: '', propTwo: '' } }
}
```

Note that any named imports from the same package works both in `dev` and `build`:
```javascript
import Module, { NamedModule } from '@external/component';
```

Where NamedModule works in both commands, but Module works only in `dev`.

### Fixes

Based on #4692 I was able to `noExternal` the external libraries, which means that default imports work as expected.

I also tried adding logic in the code to set Module to Module.default after importing it as suggested here (https://github.com/withastro/astro/issues/3174#issuecomment-1138958697).

### Suggestion

Even if I was able to solve the issue as described in "Fixes", it seems weird that `dev` and `build` behave fundamentally differently for default imports. My suggestion is to align the configurations between these commands. If that's not possible, this should at least be documented in depth outside of the closed issues in the repo.

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is an inconsistency bug in Vite (https://github.com/vitejs/vite/issues/9061), there's also a workaround like https://github.com/vitejs/vite/issues/9061#issuecomment-1203035009 you can try. Closing as it's an upstream issue.

**Comment by jsve** [comment]
NP! Please consider adding it to the documentation though. Don't want to scare people away from this awesome tool because of something like this!
