### ISSUE TITLE
HTMLAttributes Type is missing class:list

### ISSUE THREAD

**Issue by herteleo** [withastro/astro#5279]
### What version of `astro` are you using?

1.6.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The new HTMLAttributes type (#5147) is super helpful but I think it's missing the `class:list` prop. The prop gets omitted in the definition but is actually accessible via
```ts
export type Props = HTMLAttributes<"div">;
const { "class:list": classList } = Astro.props as Props; // Property 'class:list' does not exist on type 'Props'
console.log(classList); // outputs the classes
```
or is this intended?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-o5vqgz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Can you submit a PR?

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/5284
