### ISSUE TITLE
Processed script always runs when component is conditionally rendered

### ISSUE THREAD

**Issue by zadeviggers** [withastro/astro#5283]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Processed scripts always run if a component is included in the template of an Astro page, even if it's excluded by conditional rendering (e.g. `{showThing && <MyComponent />}`). This doesn't affect scripts with `is:inline` applied - they work fine.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ceknm8?file=src/pages/dont-run.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Regular `<script>` are bundled and attached to the head. We wouldn't be able to bundle them if we didn't know if they were going to be used or not. This is a known limitation. `is:inline` is what you should use if you really do want to conditionally render a script.
