### ISSUE TITLE
Image is 90 degrees rotated

### ISSUE THREAD

**Issue by Taekema** [withastro/astro#5286]
### What version of `astro` are you using?

1.6.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

windows

### Describe the Bug

Image src='/src/images/img4.jpg' width={300} aspectRatio="3/4" format="png" alt='testing'

Using @astrojs/image as shown above the image gets rotated 90 degrees.

img  tag works OK.

If I remove the EXIF information from the image it works fine.

![img4](https://user-images.githubusercontent.com/32708250/199665936-1430d305-3dd3-4ac4-9dd5-c2ebc8c2a3fc.jpg)

### Link to Minimal Reproducible Example

https:/www.taekema.eu

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
What’s the EXIF information ？

**Comment by Taekema** [comment]
https://nl.wikipedia.org/wiki/Exchangeable_image_file_format

**Comment by wulinsheng123** [comment]
> format

Can you offer a replication?

**Comment by Taekema** [comment]
https:/www.taekema.eu  and

See the image uploaded is this log

**Comment by wulinsheng123** [comment]
> https:/www.taekema.eu and
> 
> See the image uploaded is this log

I can't see any code in this link.

**Comment by wulinsheng123** [comment]
I copy your code into my IDE, but I can't replicate your said bug

**Comment by Taekema** [comment]
Is this of any help?

https://github.com/Taekema/01-image-bug

It is stil rotated with the latest and greatest

**Comment by Taekema** [comment]
I just looked at the the docs and saw the advise to install sharp as well for static sites. This fixed the problem for me.
