### ISSUE TITLE
Dep on old language-server leads to multiple versions of the compiler being installed

### ISSUE THREAD

**Issue by mayank99** [withastro/astro#5289]
### What version of `astro` are you using?

1.6.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm / yarn

### What operating system are you using?

All

### Describe the Bug

`astro@1.6.3` has a dependency on an older version of the language-server.

https://github.com/withastro/astro/blob/89f335b5399bf9511baa08841086c7afb05d8208/packages/astro/package.json#L104

this in turn has a dependency on an older version of prettier-plugin-astro which has a dependency on an older version of `@astrojs/compiler`, which in addition to the direct dependency results in multiple versions of the compiler included in lockfile

https://github.com/withastro/astro/blob/89f335b5399bf9511baa08841086c7afb05d8208/packages/astro/package.json#L103

additionally, installing the latest version of the prettier plugin leads to even more duplicate dependencies being installed. this is because `^` on a pre-1.0 package does not include future minor versions.

Potential solutions:
- use peer deps
- use `>=` or `0.X` instead of `^`.

### Link to Minimal Reproducible Example

https://astro.new/minimal?on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Does this lead to any actual bugs or just a slower install time?

**Comment by mayank99** [comment]
> Does this lead to any actual bugs or just a slower install time?

No bug by default, but I noticed this when I was trying to update the prettier plugin. Since there are multiple versions, I can't tell which one is actually being used.
