### ISSUE TITLE
Cannot preload images with getImage and astro/image 

### ISSUE THREAD

**Issue by surjithctly** [withastro/astro#5302]
### What version of `astro` are you using?

1.6.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I cannot properly set to preload images generated from `@astro/image`. The document suggest to use `getImage` helper, but the result is different. 

layout.astro

```jsx

---
import { getImage } from "@astrojs/image"; 
const { src } = await getImage({
  src: "../../assets/hero.png",
  width: 800,
  height: 742,
  format: "avif",
}); 
---

<html lang="en">
  <head>
    <link rel="preload" as="image" href={src} alt="Hero" />
  </head>
  <body>
```

hero.astro

```jsx
---
import { Image } from "@astrojs/image/components";
import heroImage from "assets/hero.png";
---

<Image  src={heroImage} alt="hero" loading="eager" format="avif" />

```

Result

```html
<head>
<link rel="preload" as="image" href="/assets/hero_2ltYko.avif" alt="Hero"> // returns 404
</head>

<img alt="Hero" width="800" height="742" src="/assets/hero.386919e0_1ifD2N.avif" loading="eager" decoding="async">
```

As you can see both of the hash after the filename are different, thus it defeats the purpose. 

### Proposed Solution
There should be an option called `priority=true` so Astro can automatically include that image for preloading. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-edxsa5?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
For something small like this we would probably accept a PR, I recommend doing that if you have the chance. If not please create an RFC discussion where someone else might be willing to champion such a feature. https://github.com/withastro/rfcs/discussions

Thanks!
