### ISSUE TITLE
@astrojs/image works locally but not on Netlify Edge

### ISSUE THREAD

**Issue by toddmorey** [withastro/astro#5307]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

astrojs/netlify 1.2.0 (targeting edge functions)

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Similar issue to #5253. Astro projects that include astro/image seem to fail on deploy, at least when targeting Netlify Edge Functions.

Right after building server entrypoints, it errors out with `Cannot bundle Node.js built-in "node:fs/promises" imported from "node_modules/@astrojs/image/dist/utils/metadata.js". Consider disabling ssr.noExternal or remove the built-in dependency.`

Here are the build logs from Netlify:

```
11:40:27 PM: $ astro build
11:40:28 PM: 04:40:28 AM [build] output target: server
11:40:28 PM: 04:40:28 AM [build] deploy adapter: @astrojs/netlify/edge-functions
11:40:28 PM: 04:40:28 AM [build] Collecting build info...
11:40:28 PM: 04:40:28 AM [build] Completed in 36ms.
11:40:28 PM: 04:40:28 AM [build] Building server entrypoints...
11:40:29 PM: [commonjs--resolver] Cannot bundle Node.js built-in "node:fs/promises" imported from "node_modules/@astrojs/image/dist/utils/metadata.js". Consider disabling ssr.noExternal or remove the built-in dependency.
11:40:29 PM:  error   Cannot bundle Node.js built-in "node:fs/promises" imported from "node_modules/@astrojs/image/dist/utils/metadata.js". Consider disabling ssr.noExternal or remove the built-in dependency.
11:40:29 PM:   File:
11:40:29 PM:     Error
11:40:29 PM:   Stacktrace:
11:40:29 PM: Error: Cannot bundle Node.js built-in "node:fs/promises" imported from "node_modules/@astrojs/image/dist/utils/metadata.js". Consider disabling ssr.noExternal or remove the built-in dependency.
11:40:29 PM:     at error (file:///opt/build/repo/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
11:40:29 PM:     at throwPluginError (file:///opt/build/repo/node_modules/rollup/dist/es/shared/rollup.js:21587:12)
11:40:29 PM:     at Object.error (file:///opt/build/repo/node_modules/rollup/dist/es/shared/rollup.js:22541:20)
11:40:29 PM:     at Object.resolveId (file:///opt/build/repo/node_modules/vite/dist/node/chunks/dep-c842e491.js:34805:34)
11:40:29 PM:     at Object.handler (file:///opt/build/repo/node_modules/vite/dist/node/chunks/dep-c842e491.js:46785:19)
11:40:29 PM:     at file:///opt/build/repo/node_modules/rollup/dist/es/shared/rollup.js:22748:40
11:40:30 PM: ​
11:40:30 PM: ────────────────────────────────────────────────────────────────
11:40:30 PM:   "build.command" failed                                        
11:40:30 PM: ────────────────────────────────────────────────────────────────
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6xnc83?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
I believe this is a known limitation due to reliance on Node.js APIs. The [integration docs](https://docs.astro.build/en/guides/integrations-guide/image/#installation) say:

> Note that `@astrojs/image` is not currently supported on
> 
> Cloudflare SSR
> `@astrojs/deno`
> `@astrojs/netlify/edge-functions`
> `@astrojs/vercel/edge`

**Comment by matthewp** [comment]
We should add an explicit error message when trying to use with known, non-supported adapters.

**Comment by toddmorey** [comment]
I definitely saw the note in the docs, though the explicit error message would help, too. I submitted this as a bug after talking to @FredKSchott who thought it **_may_** be working in Deno environments and the docs just may be out of date. Totally understand that adding Deno support for image processing like this is no small task.
