### ISSUE TITLE
Stylesheets included twice when using define:vars

### ISSUE THREAD

**Issue by gjdev** [withastro/astro#5308]
### What version of `astro` are you using?

1.6.3

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When using SCSS stylesheets with define:vars in astro pages, astro renders a page where the stylesheet is included twice. It first renders a link element to reference the stylesheet as an exernal file, and directly afterwards renders the same stylesheet inline in a style element, e.g.:

```
<link rel="stylesheet" href="/assets/_...path_.f2be9d86.css" /><style>body{background-color:var(--bgColor)}</style>
```

See the linked reproduction example. Run `npm run build` and then inspect `dist/index.html`.

### Link to Minimal Reproducible Example

https://github.com/gjdev/github-zjbcmw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
`define:vars` should not be bundled, because it cannot be. My guess is that the compiler is incorrectly thinking that this is both a regular bundle-able stylesheet and a non-bundleable define:vars inline sheet (probably because of the lang usage).

**Comment by gjdev** [comment]
> `define:vars` should not be bundled, because it cannot be.

I don't see why it can not be bundled. A `define:vars` on a stylesheet doesn't change the stylesheet, the defined variable is still left as a variable reference in the sheet. Astro puts a style attribute on the root element of the component, that assigns the variable. It keeps the stylesheet as is.

**Comment by matthewp** [comment]
I should have said *isn't*, because I believe we were intentionally not bundling them. I created a simplified example without `lang` and there is the double problem there too: https://stackblitz.com/edit/github-dxnmqh?file=src%2Fpages%2Findex.astro,dist%2Findex.html&on=stackblitz

@natemoo-re what is the state of `define:vars` on `<style>` is it intended to be bundled or not?

**Comment by wulinsheng123** [comment]
> 

is this problem in the compiler library?

**Comment by natemoo-re** [comment]
> @natemoo-re what is the state of `define:vars` on `<style>` is it intended to be bundled or not?

The `<style>` block is intended to be bundled and the `define:vars` values are intended to be inlined into the markup. I bet this is an issue in the compiler, I'll take a look.
