### ISSUE TITLE
Astro.site returns undefined in dev environment

### ISSUE THREAD

**Issue by rhyses-pieces** [withastro/astro#5310]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

#### Expected Behavior
`Astro.site` returns a URL made from `site` in Astro config. If undefined, this will return a URL generated from `localhost`. ([Reference - Astro Docs](https://docs.astro.build/en/reference/api-reference/#astrosite))

#### Actual Behavior
`Astro.site` returns `undefined` instead of the URL generated from `localhost`.

#### Steps to Reproduce
1. Initialize new Astro project with `pnpm create astro@latest`
2. Print the output of `Astro.site` via `console.log()`
3. Start the dev environment with `pnpm start`

#### Comments
Hi! I'm a little new to Astro, but I've been running into issues with constructing metadata because of the issue highlighted above. Are there any workarounds for this in the meantime?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8vjmar-xkyu7t?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
I checked this code, returned `undefined ` surely

**Comment by matthewp** [comment]
Astro.site is your production URL. It is meant to be exactly what you put in your config and nothing more. If you want to get the actual current URL use `Astro.url` instead.
