### ISSUE TITLE
Server can't restart with TailwindCSS config file edition

### ISSUE THREAD

**Issue by g-beier** [withastro/astro#5313]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When editing the `tailwind.config.js` file, the server is restarted, but never goes up again.
The Astro.new with-tailwindcss also has the same issue on Stackblitz.

Also, it gerenates many temporary files, don't know if it matters.

### Link to Minimal Reproducible Example

https://astro.new/with-tailwindcss?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Got similar reports about `astro.config.mjs`, think it's a regression, looking into it now.

**Comment by matthewp** [comment]
This should be fixed in `astro@1.6.4`, thank you so much for reporting.
