### ISSUE TITLE
Vercel build yields 404 pages only despite config file

### ISSUE THREAD

**Issue by FlipFloop** [withastro/astro#5320]
### What version of `astro` are you using?

1.6.4

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When serving locally, everything works fine, however once deployed to Vercel, the site 404s. The commit that introduced such behavior is the following (but has been fixed/reverted since then):

![Image 11-7-22 at 21 31](https://user-images.githubusercontent.com/19635051/200486145-1c0fa94d-1012-4759-bb8b-329ae2d33e66.jpg)

Now my `vercel.json` is like so:

```
{
  "cleanUrls": true
}
```

and my `astro.config.mjs`: 

```
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import tailwind from "@astrojs/tailwind";
import compress from "astro-compress";
import vercel from "@astrojs/vercel/serverless";
import image from "@astrojs/image";
import sitemap from "@astrojs/sitemap";
import path from "path";
import { fileURLToPath } from "url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// https://astro.build/config
export default defineConfig({
  site: "https://victorguyard.com/",
  base: "./",
  publicDir: "/public",
  build: {
    format: "file",
  },
  vite: {
    ssr: {
      external: ["svgo"],
    },
    resolve: {
      alias: {
        "~": path.resolve(__dirname, "./src"),
      },
    },
  },
  integrations: [
    mdx(),
    tailwind({
      config: {
        path: "./tailwind.config.cjs",
      },
    }),
    compress(),
    sitemap(),
    image({
      serviceEntryPoint: "@astrojs/image/sharp",
    }),
  ],
  output: "server",
  adapter: vercel(),
});

```

### Link to Minimal Reproducible Example

https://victorguyard-ky3m1yb1t-flipfloop.vercel.app/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by FlipFloop** [comment]
I redeployed too manny times to count without cache, and even promoting the last working build to the current production build results in the 404.

**Comment by matthewp** [comment]
@FlipFloop is it the `base: './'`? What are you expecting that to do?

**Comment by FlipFloop** [comment]
@matthewp That was there since forever, and worked before. Let me delete it and see. I added it early on when I was testing things out.

**Comment by FlipFloop** [comment]
Here is the build from that commit: https://victorguyard-f8twwtq14-flipfloop.vercel.app/

Seems to work!

**Comment by FlipFloop** [comment]
Well, the build works now. Any idea why it suddenly stopped working?
