### ISSUE TITLE
Raise exception for conflicting routes

### ISSUE THREAD

**Issue by veesahni** [withastro/astro#5340]
### What version of `astro` are you using?

1.6.5

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

**Current Behavior**: If a dynamic route (i.e. getStaticPaths) results in a conflicting path (eg: dynamic route matches a filesystem based route), astro does not raise any error.  It appears the static file system route takes precedence.

**Expected Behavior**: astro should raise an error if there are conflicting routes.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-azmt2w

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks! There are likely other ways that routes can conflict with each other. One that comes to mind is using `injectRoute` in an integration.

It might actually be better to take this to an RFC as it might be contentious. 

It's normal for routers to allow conflicts and to simply pick one based on a priority. I am a bit conflicted about this myself.

Given that I would suggest an RFC where this can be discussed and debated. https://github.com/withastro/rfcs/discussions
