### ISSUE TITLE
Base path without a trailing slash

### ISSUE THREAD

**Issue by Adrianjs42** [withastro/astro#5349]
### What version of `astro` are you using?

1.6.5

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to implement a search page that has a base path on /search.
The idea is that the page is accessible on the base `/search` and a query string can be read.
e.g.
`http://localhost:3000/search?q=test`

The problem is that I always have a trailing slash, like the following example:
`http://localhost:3000/search/?q=test`

Without entering the trailing slash I can't find the page and I get a 404 error.

I already add in the config the trailingSlash: 'never' option but it is ignored. 

Maybe related https://github.com/withastro/astro/issues/5288

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tnktw6

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/5358

**Comment by Adrianjs42** [comment]
> Fixed by #5358

thx @matthewp for looking into the bug. 
I just checked the [example](https://stackblitz.com/edit/github-tnktw6) given and still a trailing slash is always added to the url

As it looks right now:
`http://localhost:3000/search/?q=test`

What it should look like
`http://localhost:3000/search?q=test`

or am I missing something here?
