### ISSUE TITLE
🐛 BUG: Warn if non-serializable props are passed to a client-side component

### ISSUE THREAD

**Issue by natemoo-re** [withastro/astro#535]
### Motivation

_Originally posted by @FredKSchott in https://github.com/snowpackjs/astro/issues/522#issuecomment-867142208_

You can't pass a function as a prop to a client-side rendered component. We currently don't have any validation that props are serializable when you use `:load` / `:idle` / `:visible`, but we should!

### Possible solutions

- Add a warning if a prop is not serializable

### Alternatives considered

- Find a way to support JS props? Probably a terrible idea!

### Risks, downsides, and/or tradeoffs

- None!

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jonathantneal** [comment]
Reproduction @ https://stackblitz.com/edit/github-q35ih2?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by tony-sull** [comment]
Grabbed a couple screenshots of the warnings and errors we show currently.  It looks like hydration directives are handled pretty well now, I could see adding a bit more context around the un-serializable props but `estree-util-value-to-estree` does a pretty good job of pointing to what caused the error

Warning from the Stackblitz reproduction above

![image](https://user-images.githubusercontent.com/15836226/152990278-60ac9bce-940a-4096-acdb-48faf0079492.png)


Warning with invalid `client:media` values (ignored for the other directives that don't use a variable)

![image](https://user-images.githubusercontent.com/15836226/152990125-6e0cf8d7-7a7a-4f7d-9535-41501fdbcea7.png)

**Comment by tony-sull** [comment]
Closing this one out now since it looks like we have pretty good error messages and type checking :+1:
