### ISSUE TITLE
Typescript settings on create

### ISSUE THREAD

**Issue by Astisme** [withastro/astro#5352]
### What version of `astro` are you using?

1.6.5

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm 8.19.2

### What operating system are you using?

Pop!_OS 22.04 LTS

### Describe the Bug

Using `npm create astro@latest`.

When choosing which TypeScript setting to use if the user selects `Help me choose`, the program `default(s) to the most relaxed settings for you.` Without actually helping to choose between the other settings.
![image](https://user-images.githubusercontent.com/96465880/201161801-86ba2450-5da7-4e1b-873d-451be5a9fed2.png)

IMHO there are two ways to solve this:
- Swap the `Help me choose` text with `Use defaults`
- Actually show the user what would happen with each option (or throw a link in the terminal and ask again to choose)

PS: the link to the reproducible example is fake because the bug happens when creating a new astro project.

### Link to Minimal Reproducible Example

https://stackblitz.com/abcd1234

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by nsudhakaran679** [comment]
I agree this way definitely a bit confusing when I tried it out. I think the old way of displaying the three options in a list (see below) was really nice!

- Strict
- Strictest
- Relaxed (Default)

If you wanted more of an explanation, I'd also maybe include [a link to the docs](https://docs.astro.build/en/guides/typescript/) / explain why there's not a "No TypeScript" option—I think that would be helpful to people coming to Astro who have never used TypeScript before and don't necessarily plan to.

**Comment by neelsudhakaran** [comment]
**PS:** If there's an interest in making this change, I'm more than happy to do so!

**Comment by matthewp** [comment]
Thank you @neelsudhakaran! I think the change to `Use defaults` is a safe change to make. A lengthier explanation might go against the desire to keep these prompts brief.

**Comment by matthewp** [comment]
Thank you for filing this issue! Talked this over with the maintainers and we don't quite have consensus on way to fix this. Some people prefer different warning. We are the closest on agreeing to just remove the question, as it is confusing, and use `relaxed` as the default.

Going to close as there's nothing actionable on this at the moment.
