### ISSUE TITLE
unrendered conditional slot still causes slot's default content to not be rendered

### ISSUE THREAD

**Issue by gabrielgrant** [withastro/astro#5363]
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Ubuntu Linux

### Describe the Bug

This is particularly relevant when you want to plumb a slot through a hierarchy of components and only want to override the wrapper component's slot's default content if the slot is used by a user of the component

See example for a better explanation

#### Workaround

conditionally change the slot's name, instead of/in addition to conditionally rendering it

```
const slotName =  Astro.slots.has('myslot') ? 'image' : 'unused';
---
<Outer>
  {Astro.slots.has('myslot') && (
  <Fragment slot={slotName}>
    <slot name="myslot" />
  </Fragment>
  )}
</Outer>
```

### Link to Minimal Reproducible Example (and workaround)

https://stackblitz.com/edit/github-saodt6?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2FInner.astro,src%2Fcomponents%2FOuter.astro&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
cc @natemoo-re compiler related?

**Comment by natemoo-re** [comment]
This is a really interesting one, and I'm still trying to wrap my head around it.

Did some poking around here https://stackblitz.com/edit/github-saodt6-5k9but?file=src%2Fcomponents%2FOuter.astro&on=stackblitz, and it looks like `Astro.slots.has('myslot')` is `true`, but if you do `Astro.slots.render('myslot')`, you'll see that the result is an empty string.

I _think_ this is a limitation of the way we compile slots within expressions right now—if we detect any slots inside of an expression, that slot is always defined (even if it renders nothing). I think there might be a way to compile this differently, but I'll have to think through it.

**Comment by matthewp** [comment]
Ah yes, I am aware of that limitation and didn't realize that was happening here. I don't think fixing this is a priority, in that case. This is just a limitation of slots; `slots.has()` just says if a slot exists, not if it is being used.

**Comment by matthewp** [comment]
Thanks @gabrielgrant. As stated above, the `slots.has()` API only returns if a slot exists, not if it winds up being rendered. Because of that, you need to use `slots.render()` to get the result if you want to conditionally add slot content only if provided.
