### ISSUE TITLE
System limit for number of file watchers reached.

### ISSUE THREAD

**Issue by fabriziogiordano** [withastro/astro#5376]
### What version of `astro` are you using?

1.6.3

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

The file watcher is running out.
Is there a way to tell Astro to only watch a specific folder or set of files?
It is currently watching the /dist folder which has more than 2000 files.
I know I can increase the watch limit.. but I'd prefer not to.
If I could add a config and tell Astro to just watch a subset of file would be great and better for perfomance.

```
  🚀  astro  v1.6.3 started in 959ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '****/dist/****.html'
```

### Link to Minimal Reproducible Example

https://whodoyouhaveasitetoreprocli.com

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Yep, with vite config, see here: https://vitejs.dev/config/server-options.html#server-watch

**Comment by fabriziogiordano** [comment]
thank you @matthewp I forgot that behind the hood there is Vite!
