### ISSUE TITLE
body tag missing

### ISSUE THREAD

**Issue by J-env** [withastro/astro#5379]
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The body tag is missing when there are components in the head tag.

index.astro
```astro
---
import TestHead from '../components/TestHead.astro';
---

<!DOCTYPE html>
<html lang="en">
  <head>
    <TestHead />
    <title>document</title>
  </head>
  <body>
    <main>
       <h1>Welcome to <span class="text-gradient">Astro</span></h1>
    </main>
  </body>
</html>
```
output:
```html
<!DOCTYPE html>
<html lang="en" class="astro-PTZTROG7">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">

  <title>document</title>
  <link rel="stylesheet" href="/assets/index.dc9f3dd3.css" />
</head>

<main class="astro-PTZTROG7">
  <h1 class="astro-PTZTROG7">Welcome to <span class="text-gradient astro-PTZTROG7">Astro</span></h1>
</main>
</html>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zkwgaq?file=src%2Fcomponents%2FTestHead.astro,src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dayvster** [comment]
The link you have provided, does indeed contain a body tag within the iframe.

**Comment by mzaien** [comment]
Hi @J-env, I've dowloaded the reproduction and built the project, you are right it does not return the body tag

but if i `run npm run preview` (production build) it shows the body 
<img width="1224" alt="CleanShot 2022-11-12 at 11 54 45@2x" src="https://user-images.githubusercontent.com/43112535/201466770-b87e7375-2ee2-4137-bb5d-1f90e1bbbbd7.png">



<img width="1258" alt="CleanShot 2022-11-12 at 11 52 18@2x" src="https://user-images.githubusercontent.com/43112535/201466711-0d965137-6ce7-44a9-a829-1de38689432e.png">

**Comment by J-env** [comment]
@dayvster @mzaien 

The browser will fix it automatically. But there is no body tag in the source code

```
npm run build
```
<img width="935" alt="image" src="https://user-images.githubusercontent.com/25259920/201468183-ea9060d7-2b7a-4aa4-bd59-090b48caec30.png">

**Comment by MoustaphaDev** [comment]
This is a compiler bug.
I checked the compiler's parser output for this code but it looked correct, so my guess is that it's at the printer level.

**Comment by adaptive** [comment]
I am seeing the same issue, locally find, but on Cloudflare Pages omits the body tag.

**Comment by adaptive** [comment]
This bug appears on Astro 1.6.2 (Upgrade @astrojs/compiler to 0.29.x). Although the browser tries to fix it automatically, it messes up your CSS if applied to the body tag.

**Comment by LakeeSiv** [comment]
This messes up quite a few tailwind websites which rely on settings the classes on the body

**Comment by devidw** [comment]
Just a note on verifying this behavior in the browser: 
- It can be checked by opening DevTools Network Tab and seeing the HTML page response and searching for `<body`
- or by prefixing the URL with `view-source:`, right click "View Page Source", page search

Both methods show the unmodified version of the page as served by the server. In contrast to what for example the elements tab in DevTools auto-fixes as mentioned by @adaptive.

---

(Beside the bug: Having multiple single nodes as children of the non-written body tag caused issues for me, while wrapping everything into a single div-node: things seem to work.)

**Comment by adaptive** [comment]
Further digging into this, I notice that when removing the component `components/TestHead.astro` and manually adding the content in `pages/index.astro` the `<body>` returns to the build.

After reviewing several projects, it looks like it is the same problem. Every time you have a component that touches the `<head>` the bug surfaces. As mentioned @MoustaphaDev it is compiler related.

**Comment by ahkhanjani** [comment]
Same problem here. Tailwind classes in the body tag don't apply since there is no body tag in the page source.

**Comment by MoustaphaDev** [comment]
One more detail for the maintainers: it was introduced exactly in [0.29.12, #617](https://github.com/withastro/compiler/pull/617)

**Comment by matthewp** [comment]
Thanks for letting us know. cc @natemoo-re

**Comment by natemoo-re** [comment]
Thanks for your patience on this, everyone! A fix will be out in the next patch release.

In case anyone is curious, our parser was updated to handle components more literally to fix a different edge case with components inside of the `head` tag. Unfortunately, this regression was caused by the parser not properly exiting the "literal" parsing mode after encountering a component inside of `head`. This is now handled properly and regression tests have been added!

**Comment by cgpro** [comment]
Is this with 1.6.11 fixed?

**Comment by polioan** [comment]
saaame...

**Comment by cgpro** [comment]
Happens in 1.6.14 too 😔

**Comment by cgpro** [comment]
Unfortunately, not solved with version 1.7.0. 😢

**Comment by cgpro** [comment]
With 1.9.2 it's fixed, thanks! 😊

**Comment by ejoebstl** [comment]
Faced this very issue - creating a minimal reproduction it turned out I forgot to close the tag of my head component, which caused astro to silently stop rendering anything after.

**Comment by MoustaphaDev** [comment]
I recommend opening a new issue in the compiler repo @ejoebstl 
https://github.com/withastro/compiler

**Comment by ejoebstl** [comment]
> I recommend opening a new issue in the compiler repo @ejoebstl 
> https://github.com/withastro/compiler

Hey, not flagging an issue (as it's not a bug) - just hoping my comment helps others who land on this thread when googling.
