### ISSUE TITLE
cannot import a hoisted script with baseUrl

### ISSUE THREAD

**Issue by wassfila** [withastro/astro#5381]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

windows

### Describe the Bug

None of the documented ways allows to import a script when using a baseUrl

all failing attempts, the hardcoded option 0) is not a solution and is not wanted

```javascript
  //0) works fine in dev and build but hardcoded
  import '/astro-big-doc/panzoom.js';
  //1) does not work when component used from another one e.g. from Markdown on another path resolves to relative markdown path
  import "./panzoom.js";
  //2) works in dev mode only, not deployed
  import '../../node_modules/panzoom/dist/panzoom';
  //3) unexpected template string
  import `${baseUrl}/panzoom.min`; 
  //4)
  import "import.meta.env.BASE_URL/panzoom.min";
  //5) warning : files in the public directory are served at the root path.  Instead of /public/panzoom, use /panzoom.
	import '../../public/panzoom';
```

### Link to Minimal Reproducible Example

https://github.com/MicroWebStacks/astro-big-doc/blob/f24fecb2f83f29651846af738e28b021a333736a/src/components/panzoommodal.astro#L115

### Participation

- [ ] I am willing to submit a pull request for this issue.

# Discord
I submitted this on Discord to check if this is a known issue or if I did something wrong but no one could answer so far

https://discord.com/channels/830184174198718474/1019713903481081876/threads/1038767599527403600

**Comment by matthewp** [comment]
Hey @wassfila, thanks for filing. The reason this is not working the way that you'd like is because `define:vars` scripts are just normal script tags. We do not build them out, so the URLs you import will only work if they exist in prod. The best way to make this work is to use scripts that are in the `public/` directory. Those will be copied to your production output and be available.

**Comment by wassfila** [comment]
> Hey @wassfila, thanks for filing. The reason this is not working the way that you'd like is because `define:vars` scripts are just normal script tags. We do not build them out, so the URLs you import will only work if they exist in prod. The best way to make this work is to use scripts that are in the `public/` directory. Those will be copied to your production output and be available.

But as you can see here the script I'm trying to import is already in the public directory
https://github.com/MicroWebStacks/astro-big-doc/tree/f24fecb2f83f29651846af738e28b021a333736a/public

The answer sounds like a bug acknowledgement but a won't fix for static imports, it's pity that black magic concepts brought by frameworks break basic things developers usually rely upon, anyway I hope this gets revisited once the platform strives for a higher maturity level.

As a workaround, which I consider even a better way out is to use dynamic imports, this way I even improve page load times and defer scripts imports that can become conditional

# This works and fixes teh problem but with dynamic imports
```javascript
<script define:vars={{url,uid,isSvg,baseUrl}} type="module">
  await import(`${baseUrl}/panzoom.js`)

```
