### ISSUE TITLE
Astro with tailwind for MPA needs multiple css files

### ISSUE THREAD

**Issue by srini-leanfolks** [withastro/astro#5390]
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When using tailwindcss with astro for multiple pages, all the css are converted into one file of ~70kB. Any other ways to split the css for each page separately?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-csbhoi

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mandar1jn** [comment]
Addition to this: using @apply doesn’t strip the classes from the tailwind files but just makes it so you have duplicate styling. inline doesn’t work at all with tailwindcss since no transformation is done

**Comment by bluwy** [comment]
I think that's how tailwindcss works. It scans the files for classes and generates them under a single css file with:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Vite can only code-split when CSS is define in several modules. It's a caveat of tailwindcss unless you use `@apply` in different style tags across pages and components.

**Comment by srini-leanfolks** [comment]
Using ```@apply``` means by having a class name for required elements and having a separate css files for each page and writing styles in it?

**Comment by mandar1jn** [comment]
> Yeah. It's not the greatest and probably not tailwind-ish, but that's the only way to code-split CSS files that I can think of. Otherwise it would need to analyze the CSS, perform selector matching on each HTML files, and try to split it out, but I'm not sure how possible is that.

Actually, using @apply still generates the same tailwind file too. Causing even more code duplication

**Comment by bluwy** [comment]
Oh maybe tailwind's scanner extracts the classes from `@apply` too 😦 That's.. a problem. I guess the only way now is to deal with a single css file. If CSS analysis & code-splitting were to be implemented, it would be in Vite. I'll close this for now as there's not much we can do here.
