### ISSUE TITLE
Astro generates empty `.-index.bundle.js` (after update to 1.6.8)

### ISSUE THREAD

**Issue by impcyber** [withastro/astro#5400]
### What version of `astro` are you using?

1.6.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Using configuration
```ts
vite.build.rollupOptions:
        output: {
          inlineDynamicImports: false,
          chunkFileNames: 'assets/chunks/[name].[hash].js',
          entryFileNames: 'assets/[name].bundle.js',
          assetFileNames: 'assets/[name].bundle.[ext]',
        },
```
When import css file via js `import`, a js file with a strange name is generated `.-index.bundle.js`

without customizing `vite.build.rollupOptions.output` patterns, the empty .-index.123456.js file is generated.

![image](https://user-images.githubusercontent.com/1425691/201787084-3fa2e226-78f3-4edd-87fc-e1b69f21dd53.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xfum8x-ppta8q?file=dist/assets/chunks/.-index.3d9a295b.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by impcyber** [comment]
After digging through the code, I found the place where the problem occurred:
https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/css-asset-name.ts#L36
```ts
const firstParentId = parents[0]?.[0].id || 'index';

// Use the last two segments, for ex /docs/index
let dir = firstParentId;
```
if page is not nested, `firstParent` becomes `'index'`

https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/css-asset-name.ts#L43

```ts
while (i < 2) {
	if (dir === pagesDir) {
		break;
	}
```
to compare against `pagesDir`, `dir` must be an **absolute** path

this code solves the problem:
```ts
const firstParentId = parents[0]?.[0].id || viteID(new URL('./pages/index", settings.config.srcDir));
```

**Comment by matthewp** [comment]
Thanks @impcyber, can you submit a PR?

**Comment by impcyber** [comment]
No problem, submitted
