### ISSUE TITLE
Build fails with the following error:  Cannot read properties of null (reading 'default')

### ISSUE THREAD

**Issue by bkyerv** [withastro/astro#5408]
### What version of `astro` are you using?

1.6.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When running the build command following error is thrown in the console:

` error   Cannot read properties of null (reading 'default')`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-acc8kh

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by impcyber** [comment]
This is because astro tries to build all `*.astro` files in the `pages` folder as pages.
You need to move `layouts` folder upper in one level with `pages` folder.

**Comment by bkyerv** [comment]
Thank you. If I were to resolve it myself what would be the best hint in the error stacktrace that would lead me to find out the cause of the error?
