### ISSUE TITLE
Hydrating dynamic framework components throws "Unable to resolve a valid export" error

### ISSUE THREAD

**Issue by paulwag** [withastro/astro#5415]
### What version of `astro` are you using?

1.6.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux Ubuntu

### Describe the Bug

Using dynamic framework components brakes with hydration (see minimal reproduction). 

What works:
- import and then hydrate framework components
- assign components to variable and render (no hydration)

What fails:
- assigning a component to a variable and then hydrating it

_Use case for reference:_
Looping over a list of content parts and render components dynamically based on the type of the part.
This works great without hydration, but fails with error `Unable to resolve a valid export for "Component"!` on hydration.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sewhq2?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2FVueComponent.vue,src%2Fcomponents%2FSvelteComponent.svelte,package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is a known limitation. The way that Astro knows which code to load in the browser is by matching up the component being used to which import statement it comes from. Reassigning breaks that connection so we don't know what to do.

**Comment by paulwag** [comment]
Alright thanks for the quick info :)

**Comment by SarcevicAntonio** [comment]
> This is a known limitation.

ahh bummer, i was working on something were this would be very handy.
any plans to support this in the future?
