### ISSUE TITLE
Regression: Error [@astrojs/node] Setting the 'mode' option is required.

### ISSUE THREAD

**Issue by the-dijkstra** [withastro/astro#5422]
### What version of `astro` are you using?

v1.6.9

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

```txt
@astrojs/node/dist/index.js:12:11
@astro-app:build:   Code:
@astro-app:build:       11 |   if (!(userOptions == null ? void 0 : userOptions.mode)) {
@astro-app:build:     > 12 |     throw new Error(`[@astrojs/node] Setting the 'mode' option is required.`);
@astro-app:build:          |           ^
@astro-app:build:       13 |   }
@astro-app:build:       14 |   let needsBuildConfig = false;
@astro-app:build:       15 |   let _options;
```

### Link to Minimal Reproducible Example

https://github.com/codiume/orbit/actions/runs/3483931326/jobs/5827944357

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hi @the-dijkstra, this became a required field in `@astrojs/node` version 2.0.0, a major version changed, so this is not a regression. See this release PR: https://github.com/withastro/astro/pull/5046

**Comment by matthewp** [comment]
That's the version of Astro. Astro did not have a breaking change, the Node adapter did, it's a separate package.
