### ISSUE TITLE
setting config param 'base' to './' is not working

### ISSUE THREAD

**Issue by Nauxscript** [withastro/astro#5435]
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

set the `astro.config.mjs` content like:

```
export default defineConfig({
  ...
  base: './',
  ...
})
```
and run build script; the asset in output html files are still linked by  absolute path; but in vite, it will be changed to relative path when set `base` to `./` ;

[vite example](https://stackblitz.com/edit/vitejs-vite-vgqzuj)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hffxux

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Astro doesn't support fully relative paths at the moment. See https://github.com/withastro/rfcs/pull/381 where we are discussing how to fix this.

**Comment by delucis** [comment]
Hi @Nauxscript! Thanks for opening this issue. This is a known issue and we're currently discussing an approach for supporting this here: https://github.com/withastro/rfcs/pull/381

I'll close this and we can use that linked RFC to track progress.
