### ISSUE TITLE
Astro.params.foo is typed as string|number|undefined, but it can only be string|undefined, which forces extra TypeScript typing 

### ISSUE THREAD

**Issue by jyasskin** [withastro/astro#5442]
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

Linux (WSL)

### Describe the Bug

https://github.com/withastro/astro/blob/4b188132ef68f8d9951cec86418ef50bb4df4a96/packages/astro/src/%40types/astro.ts#L1149 says that `Astro.params` can contain numbers, which https://docs.astro.build/en/reference/api-reference/#params says doesn't actually happen. This forces TypeScript programs to either handle a `number` type that never actually happens or to cast it away.

I believe #3087 introduced this in order to loosen typing in `getStaticPaths()`, which produces `Params` instances, but it broke consumption of the types. You probably need two different types for inbound vs outbound.

Run `astro check` in https://stackblitz.com/edit/github-fht7tc?file=src/pages/products/[name].astro to see the error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fht7tc?file=src/pages/products/[name].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This makes sense to me. We should have `getStaticPaths` accept `numbers`, but anywhere else should be `string | undefined` only as it's extracted from the URL and we can't tell if it's a number or a string.
