### ISSUE TITLE
@astrojs/vercel API routes support?

### ISSUE THREAD

**Issue by thomasledoux1** [withastro/astro#5451]
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I added an `/api` folder in my Astro app, expecting the functions inside to be deployed as an Edge/Serverless functions.
However, when I try to call the API route, I get a 404.
Is this the expected behaviour? 
Any plans on adding support for this if not present?

### Link to Minimal Reproducible Example

https://github.com/thomasledoux1/website-thomas-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by panwauu** [comment]
If you are using SSR you can add endpoints inside the pages folder as displayed in https://docs.astro.build/de/core-concepts/endpoints/.

**Comment by panwauu** [comment]
You also get great support for these kind of questions on discord!
There you will mostly get faster help✌️

**Comment by matthewp** [comment]
I believe the api folder is a feature of the `vercel` CLI. So you should be able to still have that ability when you run `vercel build`.  Closing as I don't think this is related to Astro.

**Comment by ZeldOcarina** [comment]
To be honest it is, there's currently no way of adding POST endpoints in static mode but vercel serverless offers that but I can only test it in production as in vercel dev it 404s..
