### ISSUE TITLE
Partytown TypeError: Failed to fetch 

### ISSUE THREAD

**Issue by stefanrows** [withastro/astro#5454]
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Trying to implement Google Analytics using Partytown on a project. Implementation is done using [this guide](https://www.kevinzunigacuellar.com/blog/google-analytics-in-astro/).

After implementation of the script in the <head> tag, following error message is received:

```
TypeError: Failed to fetch
    at partytown-ww-sw.js?v=0.7.2:1676:41
    at receiveMessageFromSandboxToWorker (partytown-ww-sw.js?v=0.7.2:1703:19)
(anonymous) @ partytown-ww-sw.js?v=0.7.2:1694
await in (anonymous) (async)
receiveMessageFromSandboxToWorker @ partytown-ww-sw.js?v=0.7.2:1703
```

My config is the same as in the tutorial (with my own GA ID).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7ha9qg?file=astro.config.mjs,src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MHB2011** [comment]
Same here

**Comment by eranbetzalel** [comment]
Same here, got the console error on my website, https://www.getmailpass.com/.

**Comment by GeoBrodas** [comment]
Any solutions for this?

**Comment by damonmarkjones** [comment]
Also having same issue

**Comment by GeoBrodas** [comment]
Hey yo guys, so i discussed this issue in the discord and here's what I found!

So I tried it without party town and it wasn't working still, when I realized I was using Brave. So any third-party scripts that tracks your location gets blocked immediately. Make sure it works on some other browser like Chrome.

Yet to try it with Party Town, but I guess this should be the problem.

**Comment by damonmarkjones** [comment]
Hey @GeoBrodas thanks for clarifying. I have just confirmed analytics are working as expected when using a chrome ans safari browser **with** **PartyTown** so looks like a Brave browser specific issue.

**Comment by damonmarkjones** [comment]
> Hey yo guys, so i discussed this issue in the discord and here's what I found!
> 
> So I tried it without party town and it wasn't working still, when I realized I was using Brave. So any third-party scripts that tracks your location gets blocked immediately. Make sure it works on some other browser like Chrome.
> 
> Yet to try it with Party Town, but I guess this should be the problem.

May be worth adding the browser to the issue reporting template

**Comment by GeoBrodas** [comment]
Yeah so this problem is browser specific and considering our audience will not be much privacy concerned, thiss issue can be closed?😂👍🏻

**Comment by damonmarkjones** [comment]
> 

Yeah agree and for what its worth if you take down the shield in Brave analytics work as expected too. For others you need to turn shields off by clicking this button

<img width="776" alt="Screenshot 2022-12-29 at 11 25 50" src="https://user-images.githubusercontent.com/16006664/209944668-b2b6cc1c-899c-4615-a553-f1e443667d5f.png">

**Comment by stefanrows** [comment]
Can't confirm. I experience this issue using chrome.

**Comment by GeoBrodas** [comment]
Share your script

**Comment by stefanrows** [comment]
> 
`
<script
  type='text/partytown'
  async
  src='https://www.googletagmanager.com/gtag/js?id=G-ID'
></script>
<script type='text/partytown'>
  window.dataLayer = window.dataLayer || []
  function gtag() {
    dataLayer.push(arguments)
  }
  gtag("js", new Date())

  gtag("config", "G-ID")
</script>`
