### ISSUE TITLE
Astro Lit integration breaks SCSS imports

### ISSUE THREAD

**Issue by riccardolardi** [withastro/astro#5456]
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Reproduction:

- `yarn create astro`
- `yarn add -D sass`
- create file `/src/_index.scss`, add `<style lang="scss">` and `@import '../_index.scss';` to `/src/pages/index.astro`
- `yarn dev`, visit `localhost:3000`, all fine
- `yarn astro add lit`
- `yarn dev`, visit `localhost:3000`, error: `Sass: Can't find stylesheet to import.`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2hn57u?file=src/pages/index.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is quite similar to https://github.com/withastro/astro/issues/5441 but I can confirm this bug happening before 1.6.3 too so maybe there's a different cause to it.

**Comment by riccardolardi** [comment]
@bluwy let me know if there's any way I can help. Would be glad to contribute!

**Comment by bluwy** [comment]
Made a fix at https://github.com/vitejs/vite/pull/11079. Was a pain to debug but it's over now 😄
