### ISSUE TITLE
@astrojs/image not working on Vercel

### ISSUE THREAD

**Issue by wutangpaul** [withastro/astro#5457]
### What version of `astro` are you using?

1.16.10

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

Followed the instructions (including installing sharp module) for installing @astro/image: https://docs.astro.build/en/guides/integrations-guide/image/

Implementation: https://github.com/wutangpaul/astrojs-image-vercel-error/blob/main/src/pages/index.astro

Everything works fine locally in dev mode. 

**Using @astro/image version 0.11.6** 

When I deploy to Vercel, the image does not display and I see the following error in the function log:

> 2022-11-22T18:25:13.969Z	3a92dcb0-918d-44b9-8fc1-79665c3222cb	ERROR	(node:8) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time(Use `node --trace-warnings ...` to show where the warning was created)2022-11-22T18:25:14.184Z	3a92dcb0-918d-44b9-8fc1-79665c3222cb	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of ArrayBuffer","reason":{"errorType":"TypeError","errorMessage":"The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of ArrayBuffer","code":"ERR_INVALID_ARG_TYPE","stack":["TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of ArrayBuffer","    at new NodeError (node:internal/errors:393:5)","    at write_ (node:_http_outgoing:843:11)","    at ServerResponse.write (node:_http_outgoing:808:15)","    at setResponse (file:///var/task/node_modules/@astrojs/vercel/dist/serverless/request-transform.js:74:11)","    at async Server.handler (file:///var/task/node_modules/@astrojs/vercel/dist/serverless/entrypoint.js:22:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of ArrayBuffer","    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)","    at process.emit (node:events:525:35)","    at process.emit (node:domain:489:12)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}Unknown application error occurredRuntime.Unknown

Edit: should I be raising this with Vercel and not here? If so, let me know. 

### Link to Minimal Reproducible Example

https://github.com/wutangpaul/astrojs-image-vercel-error

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This seems to be the same as https://github.com/withastro/astro/issues/5463, but I'll close this one for now as it's a generic problem (not only astro image) that #5463 highlights.
