### ISSUE TITLE
Docs are out of sync with npm release

### ISSUE THREAD

**Issue by AirBorne04** [withastro/astro#5466]
### What version of `astro` are you using?

1.6.11

### Are you using an SSR adapter? If so, which one?

on the example of Cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Currently the Docs already include the new functionality for `@astrojs/cloudflare`, as described in the #5432. But the those updated versions have not yet been released to npm and the #5432 is also not merged yet.

In other words, the [docs](https://docs.astro.build/en/guides/integrations-guide/cloudflare/#headers-redirects-and-function-invocation-routes) for `@astrojs/cloudflare` are already on release `4.1.0` while the [npm](https://www.npmjs.com/package/@astrojs/cloudflare) version is still on `4.0.1`.

### Link to Minimal Reproducible Example

https://docs.astro.build/en/guides/integrations-guide/cloudflare/#headers-redirects-and-function-invocation-routes

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Unfortunately most of the team will be out during Thanksgiving so this might only get resolved when we get back. I'll ping the others though since the next release looks quite safe.

**Comment by aFuzzyBear** [comment]
@AirBorne04 Thank you for your amazing work 
💚

**Comment by bluwy** [comment]
Got the green light to merge! https://github.com/withastro/astro/pull/5432 is merged now so this should be resolved.
