### ISSUE TITLE
Issue with very slow install in WSL2 terminal and even broken in command prompt

### ISSUE THREAD

**Issue by tfarhan00** [withastro/astro#5472]
### What version of `astro` are you using?

1.6.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When trying to install Astro with CLI in Windows command prompt the process just stuck on the project name input, then when using WSL2 Ubuntu terminal with npm it's works but really slow, and no hope with pnpm

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/web-platform-efircq?file=example.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Soviut** [comment]
In WSL2, if you're using a volume that's shared with Windows, the file system will run very slowly because it is CPU-bound. I strongly recommend cloning your code in the linux-only part of the file system (eg: a `~/projects` directory) to make it run more quickly.

**Comment by Lofty-Brambles** [comment]
Are you sure this isn't related to #5227 by any chance? Can you try with a `--skip-houston` flag?
