### ISSUE TITLE
Fragments inside brackets remove body

### ISSUE THREAD

**Issue by Jelenkee** [withastro/astro#5483]
### What version of `astro` are you using?

1.6.11

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When a Fragment inside brackets is used in the `<head>` the `<body>` tag is gone.

`{<Fragment set:html={'<title>Hello world</title>'}/>}`

![image](https://user-images.githubusercontent.com/59470612/204130078-b9470c2f-cf82-40f7-acd2-44d2d44cc1e3.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zuyc2y?file=src%2Flayouts%2FLayout.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
It's not missing for me in stackblitz and locally. Perhaps it's a rendering error with the browser?

<img width="725" alt="image" src="https://user-images.githubusercontent.com/34116392/204237533-81087b3e-32c5-45d6-95d3-3740a78f5e0e.png">

**Comment by bluwy** [comment]
Actually it seems like that's added by the browser. It's indeed gone when checking the network request.

**Comment by wulinsheng123** [comment]
Is this problem with the `compiler`?

**Comment by Jelenkee** [comment]
> Actually it seems like that's added by the browser. It's indeed gone when checking the network request.

Sure it is added. But when you have classes on your body, they are gone.

**Comment by Princesseuh** [comment]
I'm not sure in which version, but this has been fixed and now works properly on the latest version of Astro.
