### ISSUE TITLE
Astro/sitemap i18n error

### ISSUE THREAD

**Issue by manuelernestog** [withastro/astro#5487]
### What version of `astro` are you using?

1.6.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When you generate a sitemap using i18n config, the format of the `sitemap-0.xml` file is incorrect and tools like Google Search Console can't find any pages in it.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-de1e3v

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @manuelernestog! Could you provide some more information about what is wrong with the format?

**Comment by manuelernestog** [comment]
Hi @delucis, sure!

When you generate a Sitemap with Astro Sitemap Integration, it creates two files, the `sitemap-index` and the `sitemap-0.xml` 

If you take a look at some `sitemap-0.xml` without the i18n config, it's look like this in the web browser

![Screenshot from 2022-11-29 00-56-36](https://user-images.githubusercontent.com/53962116/204450334-f7f19260-b5bc-462e-aba1-c814f94f3547.png)

Now if you take a look at one generated with the i18n config, it's look like this

![image](https://user-images.githubusercontent.com/53962116/204450483-3bcd6e33-af3e-4c1b-83f2-7eeb49e10133.png)

And it should look like this

![image](https://user-images.githubusercontent.com/53962116/204451509-25d5bda8-5eb0-45ad-8bd5-1f5fd24cd927.png)

As you can see, the web browser is not recognizing this as a xml valid file and Google Search Console is also unable to recognize URLs in the file

![image](https://user-images.githubusercontent.com/53962116/204450702-9679b7e9-4bc3-4d47-bfbd-947795bb5b72.png)

The minimal example have a website with just two index files (one for English and one for French). When you build the page and preview it you will find the same problem in the generated XML file.

**Comment by matthewp** [comment]
Is this a bug with Astro or with `astro-i18next`? It's unclear to me. Can you create an example that takes `astro-i18next` out of the equation?

**Comment by matthewp** [comment]
@manuelernestog can you let us know what is wrong with the actual XML (and not how it's rendered by the browser)?

**Comment by manuelernestog** [comment]
Sure @matthewp. First as you suggested before let me create an example without  `astro-i18next` Although it should not be interfering, it could be the reason for the problem.

> Our docs site doesn’t use i18next but does use the `i18n` sitemap config and the sitemap renders without browser styles like OP’s example: https://docs.astro.build/sitemap-0.xml
> 
> (Worth noting though that’s a browser rendering quirk: if you “View source” or download the XML file, you’ll see the XML markup is still there.)
> 
> But we don’t have the same search console error: <img alt="image" width="745" src="https://user-images.githubusercontent.com/357379/205979476-ad6a66b8-888d-4b2e-b796-9e8b1cc1252f.png">

Thanks for the information @delucis, seeing this then maybe it could be some incompatibility problem with the plugin

I'm going to create another Minimal Reproducible Example to check if it's a compatibility issue with the plugin `i18n` or is it something else. I'll get back to you as soon as I have it.

**Comment by matthewp** [comment]
Closing as stale, please reopen if you still see. an issue. Thanks!
