### ISSUE TITLE
New idea about how to refactor @astrojs/deno

### ISSUE THREAD

**Issue by CGQAQ** [withastro/astro#5491]
I don't know you guys will watch discord or not.

here is what I said:
> hey guys, I have tried a new way to refactor @astrojs/deno integration, and I think I need help
if im not wrong the original idea is build using browser target and add SHIM on top
What im trying to do is build WITH node target, and take full adventage of Deno's node shims layer
first use esbuild to bundle the code to node target, then

```js
const content = fs.readFileSync(pth, 'utf-8');
fs.writeFileSync(
    pth,
    content
    .replace(
        /import(.*?)from.*?"node:(.*?)"/g,
        'import$1from "https://deno.land/std/node/$2.ts"'
    )
    .replace(
    // replace other node builtins but didn't start with node:
    // also ignore deno modules start with http(s)://
    /import(.*?)from.*?"((?!(http|https):\/\/)(.*?))"/g,
    'import$1from "https://deno.land/std/node/$2.ts"'
    ),
    'utf-8'
);
```
> **I wanna know what you guys' thought on this**
and I have a PR for this, the SSR without @astrojs/image is working fine
but with it, the page is
![image](https://user-images.githubusercontent.com/15936231/204433760-db4a85b1-413d-43a6-a455-d6f0ac61ed31.png)
**BTW, the PR is at: https://github.com/withastro/astro/pull/5471**

> so I figured out what causes this problem, it's web-streams-polyfill, Deno cant use it, so Deno just call .toString() on it
https://github.com/denoland/deno/blob/433f38084bba9f18bdb5de22422cbbd5b0c01ff7/ext/http/01_http.js#L203
this check will not be valid

**And I really want to know what you guys opinions on this, and if possible take that and implement it OR give me some help**

**Comment by matthewp** [comment]
@CGQAQ I did see your PR. I think we can accept it when it's ready. Thanks!
