### ISSUE TITLE
Function 'runHookServerSetup' will run two times when start with 'dev'

### ISSUE THREAD

**Issue by CharlexChen** [withastro/astro#5492]
### What version of `astro` are you using?

1.6.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Function 'runHookServerSetup' will run two times when start with 'dev'

![企业微信截图_6d637501-e0f8-40c4-9bfa-5e6bee177ada](https://user-images.githubusercontent.com/96185017/204490394-057988c6-40e4-48c1-8f16-76df23173856.png)

![企业微信截图_22ea14d5-5ff1-46dc-b65c-dad2dda5e139](https://user-images.githubusercontent.com/96185017/204490423-affa75e0-41f1-4620-8728-1835074884d6.png)

So when i define a integration which include the hook(astro:server:setup) in ‘astro.config.mjs', the callback function will run two times.

![image](https://user-images.githubusercontent.com/96185017/204490729-47a3f43a-878e-4fb6-9b22-a776ea518026.png)

### Link to Minimal Reproducible Example

https://github.com/CharlexChen/astro-demo

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Seems like we should probably keep the one in `astroIntegrationsContainerPlugin` as it's called earlier, and it injects server middlewares in an [earlier position](https://github.com/vitejs/vite/blob/cff4f66cd7dfb28bdf30300ddee6dedc1c873a50/packages/vite/src/node/server/index.ts#L535-L539) before some Vite core middlewares. cc @matthewp who added both code 😬

**Comment by TheApeMachine** [comment]
Running `npm run dev` actually caused the output below:
```
❯ npx astro dev
  🚀  astro  v2.0.5 started in 34ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

Running with `npm run preview` works fine.

**Comment by bluwy** [comment]
This seems to be fixed in `main` now. There's only one call to `runHookServerSetup`
