### ISSUE TITLE
Passing `children` as props to a react component breaks in production.

### ISSUE THREAD

**Issue by miklschmidt** [withastro/astro#5493]
### What version of `astro` are you using?

1.6.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

linux

### Describe the Bug

If you're passing `children` as a prop to a react component from a `.astro` file, instead of doing it via markup, eg:
```
<MyComponent children="test" />
```

The component will receive `{children: null}` when building. It works fine in `astro dev`, but breaks in `astro build` when the island is loaded. Since this is perfectly viable React code, i'd regard this as a bug.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-l4gigd

### Participation

- [x] I am willing to submit a pull request for this issue. As long as someone can point me in the right direction.

**Comment by wulinsheng123** [comment]
mark

**Comment by wulinsheng123** [comment]
Hello Dude,
Perhaps you need to recheck the doc. 
https://docs.astro.build/en/core-concepts/framework-components/#passing-children-to-framework-components

**Comment by wulinsheng123** [comment]
> 

`< MyComponent >
  Breaks in production
</MyComponent >`
try again which use this

**Comment by wulinsheng123** [comment]
![image](https://user-images.githubusercontent.com/27261522/205534141-3e6cbc5e-c110-4196-bf34-89ec79af36ea.png)

**Comment by miklschmidt** [comment]
> < MyComponent > Breaks in production </MyComponent >
try again which use this

I'm perfectly aware that this works. I'm saying <MyComponent children="break in production"/> fail silently *only in production*. This is a bug.

**Comment by wulinsheng123** [comment]
> 
Ok, 
On my side, which seems to happen whatever the development or the production.
![image](https://user-images.githubusercontent.com/27261522/205535477-ddf1fecd-2690-4693-8900-c7ceb7301177.png)
this was your offers project

**Comment by miklschmidt** [comment]
Yup, you get this because of the bug in astro (rendered HTML is inconsistent with client rendered HTML), react then switches to client rendering and rerenders the component. In production it doesn’t, so the component is blank (gets serialized to children=null).

**Comment by miklschmidt** [comment]
> What happens in regular client-side (non-Astro) React when you pass it a prop named `children` with a string value?

`props.children` is then a string, as you'd expect.

```
import React, { useRef } from "https://esm.sh/react@18";
import ReactDOM from "https://esm.sh/react-dom@18";

const Test = (props) => {
  return (
    <div>{props.children}</div>
  )
}

const App = () => {
  return(
    <>
      <div className="box">
        <h1>Passing string children as prop</h1>
        <Test children="prop" />
      </div>
      <div className="box">
        <h1>Passing string children both as prop and children</h1>
        <Test children="prop">children</Test>
      </div>
    </>
  );
}

ReactDOM.render(<App />,
document.getElementById("root"))
```

![Screenshot_17](https://user-images.githubusercontent.com/751171/206173171-9bf14de4-1b8d-4e50-aca4-d0401b9c67aa.png)
