### ISSUE TITLE
Astro + Sanity Portable Text - Render Astro component to string?

### ISSUE THREAD

**Issue by waspeer** [withastro/astro#5494]
### What version of `astro` are you using?

1.6.11

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Hi! 👋

First of all; big fan of Astro! Been using it since it's first announcement and loving all the progress and new features.

In a project I'm currently working on I'm using Sanity as the CMS. Sanity has a custom format for richt text called [Portable Text](https://github.com/portabletext/portabletext). To render this they provide [a couple of packages](https://www.npmjs.com/search?q=%40portabletext), of which I'm using [`@portabletext/to-html`](https://github.com/portabletext/to-html).

The gist of Portable Text is that it's an array of `blocks`  that render differently based on their properties. It's also possible to define custom blocks, which you can render like this:

```astro
---
import {toHTML} from '@portabletext/to-html';

const { somePtValue } = Astro.props;
---

<Fragment set:html={
  toHTML(somePtValue, {
    components: {
      types: {
        image: ({value}) => `<img src="${value.imageUrl}" />`,
        callToAction: ({value, isInline}) =>
          isInline
            ? `<a href="${value.url}">${value.text}</a>`
            : `<div class="callToAction">${value.text}</div>`,
      },
    }
  });
} />
```

This brings me to my issue. For simple custom blocks this works fine (like the ones in the example above), but in my current project I need to render an Astro component here. I did not expect it to work, but I've tried this anyway and got the following error:

```
Error: Transform failed with 1 error:
/Users/.../[slug].astro:46:2: ERROR: Top-level return cannot be used inside an ECMAScript module
```

Is what I'm trying possible in any way? If not would it be an option to expose an API that renders an Astro component to a string?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-drkk5p?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
There's not currently a way to render an Astro component to a string, no. We have some internal APIs for that but not one that we've yet exposed. We would definitely like to add one! I would suggest going over to the RFCs repo and see if there is an existing discussion; if not create one.

Thanks!

**Comment by waspeer** [comment]
I opened a discussion for this here: https://github.com/withastro/rfcs/discussions/409
