### ISSUE TITLE
Hashed build assets end up in multiple places in build output

### ISSUE THREAD

**Issue by delucis** [withastro/astro#5502]
### What version of `astro` are you using?

1.6.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

macOS / Stackblitz

### Describe the Bug

Astro outputs various assets from its build and adds a hash to the file names to help with immutable caching. Currently these end up in various places making it less simple than it could be to set up cache headers for static builds:

- `dist/assets/<name>.<hash>.css`
  - styles in `<style>` tags or imported as ES modules

- `dist/chunks/<name>.<hash>.js`
  - scripts from UI integrations (Preact in this reproduction)
  - code-split modules (dynamically imported `canvas-confetti` in this repro)

- `dist/hoisted.<hash>.js` (also `dist/client.<hash>.js`?)
  - hoisted scripts from Astro components (if they’re bigger than Vite’s size limit for inlining — forced in the reproduction using `vite.build.assetsInlineLimit`)

- `dist/<ComponentName>.<hash>.js`
  - code for hydrated framework components

Proposal here is to move these all under `assets/` so that caching is simpler to set up. Vercel automatically sets `immutable` cache headers for the `assets/` folder of static Astro sites, so this would also ensure their default set-up covers everything.

Alternative would be to make PRs to Vercel and other providers for a more complex immutable caching set-up.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-p5qbcj?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
Could I move all these files to the folder `assets `?
like this 
![image](https://user-images.githubusercontent.com/27261522/206135069-17bbbb1f-f49c-412f-886d-ac4905267264.png)

**Comment by wulinsheng123** [comment]
I want to try fix this bug

**Comment by delucis** [comment]
I think that’s one option, sure — or just move the _contents_ of `chunks/` into `assets/`. And we’d also need to make sure generated links to CSS, etc. end up pointing to the new location too.

**Comment by wulinsheng123** [comment]
> I think that’s one option, sure — or just move the _contents_ of `chunks/` into `assets/`. And we’d also need to make sure generated links to CSS, etc. end up pointing to the new location too.

let me try to move all to the `assets` folder

**Comment by wulinsheng123** [comment]
> I think that’s one option, sure — or just move the _contents_ of `chunks/` into `assets/`. And we’d also need to make sure generated links to CSS, etc. end up pointing to the new location too.


I have tried these files moving But following your said method that doesn't move the CSS bundle file. 
So, When do I need to pay attention to the CSS link?

**Comment by Princesseuh** [comment]
Fixed in 2.0 with the `_astro` folder!
