### ISSUE TITLE
Can not change the response from a component

### ISSUE THREAD

**Issue by ido-pluto** [withastro/astro#5509]
### What version of `astro` are you using?

1.6.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Trying to change the response from a component is ignored.

`Astro.response.headers.set('x-name', 'astro');`

### Link to Minimal Reproducible Example

https://codesandbox.io/s/sharp-meadow-t8lcog?file=/src/components/Card.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hey, `Astro.response` is a SSR-only property. 

In static generation mode, Astro generates HTML files so it is not possible to change the response there!

**Comment by ido-pluto** [comment]
Sorry, I forgot to update some of the example settings (I did update now).

My intention is to use it with the SSR mode. For some reason, I can only change the `Astro.response` from the page but not from the page components.

In the example, the header `x-index-page` is going through but `x-component-card` is not.

**Comment by matthewp** [comment]
Right, this is because of streaming. You an only modify headers in the page component.
