### ISSUE TITLE
url.searchParams is always an empty object

### ISSUE THREAD

**Issue by youssef-ahamid** [withastro/astro#5515]
### What version of `astro` are you using?

1.4.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

i am trying to read a search string from the search params:
```js
// http://localhost:3000?search=123
const search = Astro.url.searchParams.get('search');
console.log(search); // always null
```

Moreover, Astro doesn't seem to recognize search params at all. Anything after a question mark is ignored. Visiting http://localhost:3000?search=123 yields the following `Astro.url` object:

```
URL {
    href: 'http://localhost:3000',
    origin: 'http://localhost:3000',
    protocol: 'http:',
    username: '',
    password: '',
    host: 'localhost:3000',
    hostname: 'localhost',
    port: '3000',
    pathname: '',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
 }
```

Is there another way to access the search params on the server?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6eyvhx?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! As said in our docs, `searchParams` are always empty in static mode. See the following page: https://docs.astro.build/en/reference/api-reference/#astrorequest

**Comment by matthewp** [comment]
Correct, set `output: 'server'` to use search params.
