### ISSUE TITLE
Astro Content not working

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#5520]
### What version of `astro` are you using?

0.0.0-content-schemas-20221130135236

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

The `astro:content` module does not exist yet at all. I only see astro/zod . I don't know what's going on but I ready to try things out dude I'm living on the edge.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/rxjs-gu34u8

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Hey @louiss0! Yes, this is a draft preview, so be patient with us as we near an `--experimental` release 😁 

After installing, you'll need to run `astro dev` or `astro build` for the `astro:content` module to be generated in the `src/content/types.generated.ts` file. Have you tried this?

**Comment by louiss0** [comment]
> Hey @louiss0! Yes, this is a draft preview, so be patient with us as we near an `--experimental` release 😁
> 
> After installing, you'll need to run `astro dev` or `astro build` for the `astro:content` module to be generated in the `src/content/types.generated.ts` file. Have you tried this?

I did nothing happened I created the types generated.ts file It doesn't work. I hope you are not too busy to fix this. All it does is say watching. Are you sure you published the right version

**Comment by louiss0** [comment]
I tried this again but I got this error. I guess I have to wait for experimental 

```
Error: ENOENT: no such file or directory, mkdir 'C:/C:/Users/louis/Desktop/web-projects/ui/test-content/.vite/deps_temp'
    at Object.mkdirSync (node:fs:1395:3)       
    at runOptimizeDeps (file:///C:/Users/louis/Desktop/web-projects/ui/test-content/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:41726:14)
    at Timeout._onTimeout (file:///C:/Users/louis/Desktop/web-projects/ui/test-content/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:41135:54) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'C:/C:/Users/louis/Desktop/web-projects/ui/test-content/.vite/deps_temp'
}

Node.js v18.12.1
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by louiss0** [comment]
It's not the installation that went wrong It's the dev server and build
command

**Comment by bholmesdev** [comment]
@louiss0 I'm aware! Just making sure all dependencies are up-to-date before running the dev server. Again, will work on windows CI tests to see if we can catch this

**Comment by louiss0** [comment]
Sounds good, thanks!  Please notify me when things change.

**Comment by louiss0** [comment]
> @louiss0 I'm aware! Just making sure all dependencies are up-to-date before running the dev server. Again, will work on windows CI tests to see if we can catch this

Well, I hope you can fix this I'm hyped for this RFC. I think it will change my life.
