### ISSUE TITLE
Generate runtime sitemap in SSR mode still call /favicon.io 😅

### ISSUE THREAD

**Issue by harrytran998** [withastro/astro#5524]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

Node 18, SSR mode standalone

### What package manager are you using?

yarn 3

### What operating system are you using?

Mac

### Describe the Bug

![image](https://user-images.githubusercontent.com/24296018/205447605-b71913cd-132c-46bc-9afd-860fca2b9cf3.png)

Here is the overview of this problem. In XML mode view, this still calls `/favicon.ico` although I don't use it. --> Bcs not found the assets --> Redirect to 404 page(but still work) 😆.

### Link to Minimal Reproducible Example
Prefer https://github.com/harrytran998/rep-astro-runtime-sitemap to Stackblitz in this case.
Stackbilzt did not work well with XML + base path https://stackblitz.com/edit/github-a1xjuo?file=src/pages/sitemap.xml.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Pimm** [comment]
I don't think this is an issue, especially not an Astro one.

When one visits a page, their browser is going to look for an icon to put in the tab. Some browsers ‒ yours included ‒ make an educated guess that it is located at `/favicon.ico`. This is normal behaviour, and not problematic.

Or am I misunderstanding your explanation?

**Comment by bluwy** [comment]
Yup @Pimm is correct as it's default browser behaviour that it tries to find a favicon regardless if you have one or not. Closing as it's out of our control.

**Comment by harrytran998** [comment]
@bluwy  @Pimm 

Thanks for the quick response 🍻. And yeah, I agree about the `/favicon` --> But Astro will redirect in here, and I don't know why 🧐

https://www.dnse.com.vn/hoc/kien-thuc/sitemap.xml --> You can go here to see this product of our team using NextJs to generate runtime Sitemap, this doesn't have any problem with redirect here 😆.

**Comment by bluwy** [comment]
I tried to access the link but it doesn't seem to be responding. I think the redirect happens because the server detects a 404 and tries to redirect and render a fallback page. Does your server has that set up?

I tried to run the repro locally but I don't see the redirect happening. I use `node ./dist/server/entry.mjs` to start the server locally.
