### ISSUE TITLE
Prevent cache with 'Astro.slots.render'

### ISSUE THREAD

**Issue by ido-pluto** [withastro/astro#5525]
### What version of `astro` are you using?

1.6.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The only way to prevent cache when rendering the children is to pass args to `Astro.slots.render`

But this is meant to be used when there is a single-child function

```jsx
<Component>
{(text) => <p>{text}</p>}
</Component>
```

I need a way to disable the cache for some uses different from the original use.

Right now if there is only one child it will throw an error.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/cranky-benji-k1r7pl?file=/src/components/ManyNumbers.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
What is your reason for needing the cache to be disabled?

**Comment by natemoo-re** [comment]
Yeah agreed, I think the cache was just premature optimization. Definitely not something we need to keep.

**Comment by matthewp** [comment]
Closed by https://github.com/withastro/astro/pull/5548
