### ISSUE TITLE
Weird SSR bug. Missing "./dist/runtime/server/render/astro" export in "astro" package. Sorry if simple.

### ISSUE THREAD

**Issue by jazzypants1989** [withastro/astro#5527]
### What version of `astro` are you using?

1.6.12

### Are you using an SSR adapter? If so, which one?

Node, but I tried switching and it did nothing.

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Working in dev and most things have been fine. I did a build to test how things were actually working and I was happy. However, when I go back to trying to work in my dev environment, I am getting this error:

```
Missing "./dist/runtime/server/render/astro" export in "astro" package
```

This only occurs in my auth redirect that sends the user to Github OAuth.

I decided to tweak a few things, and then I wanted to build again. Guess what? Every build cancels out with that exact same error.

I eventually got this slightly better error: 

```
[commonjs--resolver] Missing "./dist/runtime/server/render/astro" export in "astro" package
 error   Missing "./dist/runtime/server/render/astro" export in "astro" package
  File:
    C:\Users\user\OneDrive\Documents\GitHub\pale-parsec\node_modules\vite\dist\node\chunks\dep-67e7f8ab.js:32675:8
  Code:
      32674 | function bail(name, entry, condition) {
32675 |   throw new Error(
            |        ^
      32676 |     condition
      32677 |     ? No known conditions for "${entry}" entry in "${name}" package
      32678 |     : Missing "${entry}" export in "${name}" package
      
}
```

    And, this call stack:
    
   
    
```
(file:///C:/Users/user/OneDrive/Documents/GitHub/pale-parsec/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:32739:3)
    at resolveExports (file:///C:/Users/user/OneDrive/Documents/GitHub/pale-parsec/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34115:12)
    at resolveDeepImport (file:///C:/Users/user/OneDrive/Documents/GitHub/pale-parsec/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34133:31)
    at tryNodeResolve (file:///C:/Users/user/OneDrive/Documents/GitHub/pale-parsec/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33825:20)
    at Object.resolveId (file:///C:/Users/user/OneDrive/Documents/GitHub/pale-parsec/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33585:28)
    at Object.handler (file:///C:/Users/user/OneDrive/Documents/GitHub/pale-parsec/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45593:19)
    at file:///C:/Users/user/OneDrive/Documents/GitHub/pale-parsec/node_modules/rollup/dist/es/shared/rollup.js:22748:40
```
    
   
    
   Just let me know if you need any more information.
   
   I'm sorry if this is something simple that I'm missing. I've been debugging for two hours and nothing seems to help.
    

### Link to Minimal Reproducible Example

https://github.com/jazzypants1989/astro-solid-blog

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jazzypants1989** [comment]
I'm an idiot. I haven't gotten it fixed, but this is definitely a **ME** problem and not an Astro problem.

**Comment by stephanbogner** [comment]
I just had the same issue:
I wanted to access Astro globals in a React-JSX component which obviously doesn't work ... but made VS-Code automatically add `import { AstroComponentInstance } from "astro/dist/runtime/server"` at the top of my script.
I now removed it and it works again.

**Comment by LucianoCanziani** [comment]
@stephanbogner You are awesome dude. Doing that just solved my problem
