### ISSUE TITLE
Astro not default loading the .env.production when run serve: `node dist/server/entry.mjs`

### ISSUE THREAD

**Issue by harrytran998** [withastro/astro#5536]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

NodeJs SSR standalone

### What package manager are you using?

yarn 3

### What operating system are you using?

Mac

### Describe the Bug

When building the Astro project, Astro will transform `import.meta.env.PRIVATE_ENV` to `process.env.PRIVATE_ENV`. This will work well in CI/CD or Docker env(mask and inject `PRIVATE_ENV`). But locally, BCS Astro does not load `.env.production` like NextJs, so we cannot serve it in the local environment.

### Link to Minimal Reproducible Example

This is well informative enough to know the issue 😆. But if your team needs that, I will do <3

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Loading dot env sounds like a reasonable feature request. Maybe we should do it, but likely won't without an RFC, so closing and asking that you post an RFC discussion / proposal instead.

**Comment by harrytran998** [comment]
> ```shell
> DOTENV_CONFIG_PATH=.env.production node -r dotenv/config
> ```

Thanks for your suggestion to do this 🥰. It worked! 

But in a good condition, like Vite or Nextjs, their load env before todo something. @matthewp I will do that <3
