### ISSUE TITLE
Astro params not work correctly with `basePath` config in production mode.

### ISSUE THREAD

**Issue by harrytran998** [withastro/astro#5537]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

Node 18 Standalone - SSR

### What package manager are you using?

yarn 3

### What operating system are you using?

Mac

### Describe the Bug

When I config Astro project with base path `/ok` --> In dev mode, it works correctly, but in production mode, the params return nothing. Here is the payload of Astro.

```js
params: {},
props: {},
 url: URL {
    href: 'http://localhost:3000/ok/hello-astro',
    origin: 'http://localhost:3000',
    protocol: 'http:',
    username: '',
    password: '',
    host: 'localhost:3000',
    hostname: 'localhost',
    port: '3000',
    pathname: '/ok/hello-astro',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  ```
  
  Hope your team can fix this 😆 <3.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7gh2ow?file=astro.config.mjs | Can pull local to run to easy debug --> https://github.com/harrytran998/rep-astro-base-path-params

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
mark
