### ISSUE TITLE
Redirect in imported pages throws an error

### ISSUE THREAD

**Issue by sjorsjes** [withastro/astro#5551]
### What version of `astro` are you using?

1.6.13

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When adding `Astro.redirect('/')` to a (imported) hidden page the application throws an error.
You can see the example in StackBlitz when navigating to `/en/search`

```
Returning a Response is only supported inside of page components. Consider refactoring this logic into something like a function that can be used in the page.
 error   {"size":0}
  File:
    /home/projects/qgniooaqx.github/file:/file:/home/projects/qgniooaqx.github/node_modules/astro/dist/core/errors/utils.js:68:73
  Stacktrace:
Error: {"size":0}
    at Module.createSafeError (file://file:///home/projects/qgniooaqx.github/node_modules/astro/dist/core/errors/utils.js:68:73)
    at onError (file://file:///home/projects/qgniooaqx.github/node_modules/astro/dist/vite-plugin-astro-server/request.js:75:41)
    at Module.runWithErrorHandling (file://file:///home/projects/qgniooaqx.github/node_modules/astro/dist/vite-plugin-astro-server/controller.js:86:19)
    at async Module.handleRequest (file://file:///home/projects/qgniooaqx.github/node_modules/astro/dist/vite-plugin-astro-server/request.js:56:3)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kmhexi

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sjorsjes** [comment]
@delucis Good point, I've adjusted the stackblitz to represent a more "real" situation. In this case we've got 2 directories representing languages and I want to re-use the `_search.astro` page for both languages.

**Comment by delucis** [comment]
Thanks! I don’t seem to be able toc access your reproduction link. I get this screen:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/357379/206277498-f22e2e06-721e-452c-a32f-82ef415025a9.png">

And following “Open project” gives me

<img width="835" alt="image" src="https://user-images.githubusercontent.com/357379/206277574-4f7fff99-adb2-44b9-a7e1-c34d8afe4e55.png">

Maybe it’s private or something?

**Comment by sjorsjes** [comment]
@delucis Not sure whats happend to stackblitz, here is the repo: https://github.com/sjorsjes/astro-redirect-issue

**Comment by delucis** [comment]
Thanks! I’ll leave it to someone else to say if we can fix something on our end as it’s not really my expertise, but in this scenario I’d probably suggest using a dynamic route for example at `src/pages/[lang]/search.astro`:

```astro
---
const { lang } = Astro.params;

if (!['en', 'nl'].includes(lang)) {
  return new Response(null, {
    status: 404,
    statusText: 'Language not found'
  });
}

// Redirect for your search queries as suggested in your Stackblitz
Astro.redirect('/');
---

```

**Comment by matthewp** [comment]
You can only redirect from the top-level page. So in your case that would be in `src/pages/en/search.astro` or `src/pages/nl/zoeken.astro`. It's not a matter of where the component is located, if it's not used as a top-level page then it can't redirect (or return a response).
