### ISSUE TITLE
Error `fn is not a function` when Astro.glob in a TS file

### ISSUE THREAD

**Issue by goulvenclech** [withastro/astro#5552]
### What version of `astro` are you using?

1.6.13

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

NPM

### What operating system are you using?

Tested on Linux, Mac & Windows

### Describe the Bug

Hi guys !

I tried to use `await Astro.glob` inside a TS file by passing Astro as an argument. Throw the error "FN is not a function", looks like a Vite-related problem. 

The same function works like a charm when in an Astro file. 

### Error log

```
fn is not a function

/home/projects/github-xlqiz4/globHandler/<@file:/file:/home/projects/github-xlqiz4/node_modules/astro/dist/runtime/server/astro-global.js:28:47

globHandler/<@file://file:///home/projects/github-xlqiz4/node_modules/astro/dist/runtime/server/astro-global.js:28:47
globHandler@file://file:///home/projects/github-xlqiz4/node_modules/astro/dist/runtime/server/astro-global.js:28:35
getStaticPathFromContentType@/src/utils.ts:4:32
getStaticPaths@/home/projects/github-xlqiz4/src/pages/blog/[article].astro:10:32
callGetStaticPaths@file://file:///home/projects/github-xlqiz4/node_modules/astro/dist/core/render/route-cache.js:38:27
getParamsAndProps@file://file:///home/projects/github-xlqiz4/node_modules/astro/dist/core/render/core.js:41:47
matchRoute@file://file:///home/projects/github-xlqiz4/node_modules/astro/dist/vite-plugin-astro-server/route.js:43:59
````

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xlqiz4?file=src/utils.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Tried to debug this on my end and it seems like [importMetaGlobResult](https://github.com/withastro/astro/blob/4f7f20616ed2b63f94ebf43bc5fdc1be55062a94/packages/astro/src/runtime/server/astro-global.ts#L13) here is somehow an array of strings instead of being an array of imports. I'm not too familar with how Vite's `import.meta.glob` works, but I guess it comes from there?

**Comment by bluwy** [comment]
I think this is expected as documented at https://docs.astro.build/en/reference/api-reference/#astroglob. Closing this for now.
