### ISSUE TITLE
There are `presetWebFonts` and `presetIcons` in `unocss.config.ts` can't work 

### ISSUE THREAD

**Issue by wulinsheng123** [withastro/astro#5556]
### What version of `astro` are you using?

last

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

There are presetWebFonts and presetIcons in unocss.config.ts can't work, 
it's only works with the `@iconify/icons-carbon`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-d4rp6r-zdr9hy?file=tsconfig.json,src%2Fcomponents%2Findex.vue,src%2Fpages%2Findex.astro,astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
How is this a bug in Astro?

**Comment by sibbng** [comment]
UnoCSS maintainer here!

@wulinsheng123 You need to install `@iconify-json/carbon` for icons. To use web fonts you need to include either `font-sans`, `font-mono` or `font-serif` classes in your app.

**Comment by wulinsheng123** [comment]
> UnoCSS maintainer here!
> 
> @wulinsheng123 You need to install `@iconify-json/carbon` for icons. To use web fonts you need to include either `font-sans`, `font-mono` or `font-serif` classes in your app.
l

![image](https://user-images.githubusercontent.com/27261522/206602307-7b7f3adc-52e2-4fe1-a4ea-6a6239179d24.png)

Here is an example in the `@unocss/preset-icons` doc.

in the duplicate of the link, I settled `presetIcons({scale: 10,warn: true,})` also didn't  work 

![image](https://user-images.githubusercontent.com/27261522/206602470-99d65916-ff62-4fcd-a9d2-195af65d4eb5.png)

**Comment by sibbng** [comment]
You need to install corresponding packages for each icon set or the complete set. Please read the Install section in docs: https://github.com/unocss/unocss/tree/main/packages/preset-icons#install

**Comment by wulinsheng123** [comment]
> You should install the corresponding package for each icon set or the complete set. Please read the Install section in docs: https://github.com/unocss/unocss/tree/main/packages/preset-icons#install

![image](https://user-images.githubusercontent.com/27261522/206649278-4be7e43a-066d-40cb-a542-e07672d6579c.png)
I use a config file, and same this repo `https://github.com/antfu/vitesse-lite`

**Comment by wulinsheng123** [comment]
it's my bad.
`"@iconify-json/carbon": "^1.1.11",
    "@iconify/icons-carbon": "^1.2.12",`
there two dependencies so similar 
sorry
