### ISSUE TITLE
Body tags are missing when conditionally rendering Astro components in HTML head

### ISSUE THREAD

**Issue by nimajneb** [withastro/astro#5557]
### What version of `astro` are you using?

1.6.13

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When conditionally rendering an Astro slot or component in the HTML `head`, the opening and closing `body` tags provided by the template are completely stripped from the document.

I'm using said condition to differentiate between a production or development build, and it appears to not make a difference whether the condition evaluates to true or false. Only commenting out the code does lead to the body tags being correctly rendered.

There is no difference in behaviour between a production build or running the development server.

It is hardly noticeable when using an empty body tag, because browsers seem to be fault-tolerant and implicitly insert one (as one can see in the dev console), but I am putting CSS class names on the body element which I need for styling. In this example I used an inline style so it's visible more easily.

Both slot content and Astro component, as well as the rest of the document seem to be rendered correctly.

I can kind of work around the issue by wrapping everything inside body in an extra div and apply my classes there, but this might not apply to everyone, so this is totally unexpected to me.

```astro
---
const isProd = process.env.NODE_ENV === 'production'
---
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Astro</title>
		{isProd && <slot name="test" />}
	</head>
	<body style="background-color: red;">
		<slot />
	</body>
</html>
```

A minimal reproducible example that is also rendering an Astro component is provided below.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uwb7te?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I believe this is a compilation problem.

**Comment by cgpro** [comment]
https://github.com/withastro/astro/issues/5379
