### ISSUE TITLE
Astro build crashes when using `react-syntax-highlighter` library

### ISSUE THREAD

**Issue by VojtaStruhar** [withastro/astro#5562]
### What version of `astro` are you using?

1.6.14

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When I include React in my Astro project, everything works fine, unitil I install and use library for syntax highlighting component [`react-syntax-highlighter`](https://www.npmjs.com/package/react-syntax-highlighter).

The weird part is, that it works fine in dev mode, but **crashes on build**. 

It almost seems like an error in the library (?), but once again - in dev mode, it works just fine.

I've created a fresh new project here on Github that contains nothing else. You have to run `yarn build` to get the error, that's why I didn't use StackBlitz or others like that.

### Link to Minimal Reproducible Example

https://github.com/VojtaStruhar/astro-react-syntax-highlighter-buildcrash

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by VojtaStruhar** [comment]
**Just tested:** The build error does NOT occur when I opt into SSR with vercel adapter.

**Comment by bluwy** [comment]
The `react-syntax-highlighter` [isn't properly packaged](https://publint.bjornlu.com/react-syntax-highlighter@15.5.0). Please report upstream to fix it.

**Comment by VojtaStruhar** [comment]
Thanks! I'll try to find something that is properly packaged then...

**Comment by onyoo** [comment]
@VojtaStruhar did you find a suitable work-around?

**Comment by onyoo** [comment]
solution: use the  `client:only` directive on the component in your astro file. This side steps the packaging issues in react-syntax-highlighter.

**Comment by VojtaStruhar** [comment]
I think I gave up and just used [hljs](https://highlightjs.org/). That one is framework agnostic.

Thanks for the reply!
