### ISSUE TITLE
Vue library "primevue" needs configuration

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#5563]
### What version of `astro` are you using?

1.6.1

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I tried using prime vue in my vue app but i ran into a problem that I had to solve with this setting 

```
ssr: {
      noExternal: ["primevue"],
  },
```

Why did I have to deal with this problem if you take this setting off then the prime Vue file will be bundled into the server entry. which is what I don't want apparently. I hope I don't have to deal with this again. I don't like configuring at all. 

 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nqn7zc?file=src%2Fbootstrap.ts,astro.config.mjs,dist%2Fentry.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@louiss0 Not all libraries work without configuration, that's why the configuration exists in the first place. Please be kinder in your bug reports.

It looks like this is a popular library so I'll make it so that we have this setting as part of the Vue integration.

**Comment by francoromanol** [comment]
FYI, this makes configuration neccesary in SSR (at least on Vercel). Now we need to specify the opposite:

```
ssr: {
      external: ["primevue"],
  },
```

**Comment by matthewp** [comment]
@francoromanol Oh, that's really unfortunate. Do you have any idea why you need to make it be external?

**Comment by carlos00027** [comment]
I don't understand how I can add primevue
