### ISSUE TITLE
Is a directory (os error 21) - Internal Server Error

### ISSUE THREAD

**Issue by Astisme** [withastro/astro#5565]
### What version of `astro` are you using?

v.1.6.14

### Are you using an SSR adapter? If so, which one?

Deno

### What package manager are you using?

npm 8.19.2

### What operating system are you using?

Linux

### Describe the Bug

Please read [the issue on deno](https://github.com/denoland/deploy_feedback/issues/318).

tldr:

- `npm run dev` works perfectly,
- `npx astro build` has no problem,
- `npm run preview` shows an empty page
- when deploying to deno via [GH Actions](https://docs.astro.build/en/guides/deploy/deno/#github-actions-deployment), there's an `Internal Server Error`

Is Astro with GH Actions using this line?
```javascript
import { serve } from "https://deno.land/std@0.167.0/http/server.ts";
```

Is @astrojs/deno up to date or is it using this other line?
```javascript
import { serve } from "https://deno.land/std@0.132.0/http/server.ts";
```

### Link to Minimal Reproducible Example

https://stackblitz.com/abcd1234

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Feel free to submit a PR updating the dependency.

**Comment by lino-levan** [comment]
ref: https://github.com/withastro/astro/pull/5573

**Comment by Astisme** [comment]
Ok so basically this is why this error was coming up:

I created a websiteConfig.json file which contained the website name and the favicon name.
I put this file inside the public folder and was then importing it from the files in the src directory.

While I was using `npx astro dev`, everything was working as expected (I suspect because I was in localhost) but when I then pushed to Deno, the file configuration obviously changes and everything broke.

# Fix
The fix here is to use the `src/config.ts` file for any configuration.

My problem was that I didn't find this file until I created a new Astro project from scratch (not the basic one).
