### ISSUE TITLE
@astrojs/vercel: 2.3.5 breaks API endpoints

### ISSUE THREAD

**Issue by Ehesp** [withastro/astro#5568]
### What version of `astro` are you using?

1.6.14

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The `@astrojs/vercel` adapter is breaking API endpoints on vercel when using `2.3.5`. On `2.3.4` they work as expected.

I've got a deployment running in the reproduction link below on Vercel, as you can see if you look at network, any requests to `/api` are failing with the same error:

```
ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: response.body.getReader is not a function","reason":{"errorType":"TypeError","errorMessage":"response.body.getReader is not a function","stack":["TypeError: response.body.getReader is not a function","    at setResponse (file:///var/task/node_modules/@astrojs/vercel/dist/serverless/request-transform.js:109:32)","    at Server.handler (file:///var/task/node_modules/@astrojs/vercel/dist/serverless/entrypoint.js:22:11)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: response.body.getReader is not a function","    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)","    at process.emit (node:events:539:35)","    at process.emit (node:domain:475:12)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
Runtime.Unknown
```

Looks like [this commit](https://github.com/withastro/astro/commit/a1885ea2f59f26cbdae10c298e1e0d1063d9dca1) from @JuanM04 is the issue.

For clarity, the endpoint failing does a basic response:

```ts
export const post: APIRoute = async ({ request }) => {
  const { idToken } = (await request.json()) as { idToken: string };

  if (!idToken) {
    return new Response(null, {
      status: 200,
      headers: new Headers({
        'Set-Cookie': cookie.serialize('session', '', {
          expires: new Date(0), // Deletes the cookie
        }),
      }),
    });
  }

  const expiryDys = 5; // Expires in 5 days
  const expires = 60 * 60 * 24 * expiryDys * 1000;
  const session = await createSessionToken(idToken, expires);

  return new Response(null, {
    status: 200,
    headers: new Headers({
      'Set-Cookie': cookie.serialize('session', session, {
        maxAge: expires,
        path: '/',
        httpOnly: false, // Allows the cookie to be read by the client and sent via fetch
      }),
    }),
  });
};
```

### Link to Minimal Reproducible Example

https://zapp-r4q76tpec-invertase.vercel.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
So sorry to hear this, paging @JuanM04 in case he knows what's going on. I'll take a look myself too.

This is the only change in 2.3.5: https://github.com/withastro/astro/pull/5514

**Comment by JuanM04** [comment]
Ohhhh, I think I know what's happening. `getReader` is only supported in Node v16. @Ehesp, are you using Node v16 or above? Is the Vercel project set to use Node v16 or v18?

**Comment by matthewp** [comment]
Can we do a fallback for those on Node 14?

**Comment by Ehesp** [comment]
![image](https://user-images.githubusercontent.com/842078/206730560-0149f5e6-43cf-405a-9b34-31ecb58f3b9a.png)

Hmm, version is set to Node 16 on Vercel.

**Comment by pilcrowOnPaper** [comment]
Should this issue be prioritized over #5489?

**Comment by matthewp** [comment]
Yes, regressions are prioritized.

**Comment by pilcrowOnPaper** [comment]
@matthewp No, I mean like aren't these the same issue? So, should I close #5489 over this issue?

**Comment by matthewp** [comment]
They might be the same issue! Let's leave them open for now and after we have this fixed if you wouldn't mind checking to see if it fixes yours as well.

**Comment by pilcrowOnPaper** [comment]
Oh, the error message is ever slightly so different, my bad!

**Comment by JuanM04** [comment]
Sorry for the late response, I wasn't available. I've identified the issue and I'm solving it. Meanwhile, @Ehesp, upgrading to Node v18 solves it.

**Comment by JuanM04** [comment]
@Ehesp could you try with `@astrojs/vercel@next--set-cookie`?

**Comment by savicaleksa** [comment]
> @Ehesp I've made a PR. Could you try with `@astrojs/vercel@next--set-cookie`?

I can confirm that this also fixes the issue with `@astrojs/image` and sharp not working on vercel ssr.
Thank you!
