### ISSUE TITLE
Styles and scripts not loading on Chrome browser in Android

### ISSUE THREAD

**Issue by ruben00001** [withastro/astro#5574]
### What version of `astro` are you using?

1.6.13

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

For the website I'm developing, styles and scripts aren't loading on my android phone. It works on desktop. It works responsively (within the desktop).

**Edit**: the browser it's not working on is Google Chrome and device is moto g4. It's working on the Firefox browser.

Having inspected my android phone using chrome://inspect, I can see the style sheet and script seem to be loaded in fine, but the styles aren't applied and scripts aren't working.

I've made some attempt to reproduce the issue on the site.

An example is the home page: [here](https://joshua-gordon.netlify.app/).
I've made a simple page on: [here](https://joshua-gordon.netlify.app/test).

The git repository is at: [here](https://github.com/ruben00001/joshua-gordon-portfolio).

### Link to Minimal Reproducible Example

None.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please provide a minimal reproduction.

**Comment by delucis** [comment]
Hey @ruben00001! My guess here is that this is a problem with an older version of Chrome. Your site loads fine on my Chrome + Android set-up. To provide its scoped styles, Astro relies on the [`:where()` pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:where), which is not supported in some older versions of browsers.

If you need to support such devices, you could try adding the [`is:global` directive](https://docs.astro.build/en/reference/directives-reference/#isglobal) to your `<style>` tags. This will turn off scoping so you need to be careful to use unique class names to ensure styles don’t conflict between components, but will avoid the use of `:where()` so has better backwards compatibility with older browsers.

**Comment by ruben00001** [comment]
Thank you @delucis! You're right - I updated Chrome and it's working fine.
