### ISSUE TITLE
Astro not serving local font files

### ISSUE THREAD

**Issue by michecode** [withastro/astro#5578]
### What version of `astro` are you using?

1.6.14

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I'm building a Svelte/Tailwind app with Astro and was confused when the fonts are not being served once I pushed a live build. I followed the [Astro docs guide for fonts](https://docs.astro.build/en/guides/fonts/) almost exactly. I thought everything was working fine but it turned out Chrome and Firefox just used the installed font to display it. Safari doesn't do this so that's how I found the issue.   
Tailwind applies the css class correctly but the fonts are never delivered as seen in the network tab below.
![image](https://user-images.githubusercontent.com/44727187/206879503-824f1683-1e25-4108-a6fe-66ffc826e22c.png)

edit: forgot to show examples of the font!!
Top is the safari version not using the installed fonts on my computer and bottom is firefox using installed fonts
![image](https://user-images.githubusercontent.com/44727187/206879754-5183ae01-e4d7-4917-a4ce-d1623e1787e3.png)
![image](https://user-images.githubusercontent.com/44727187/206879764-44d969bb-93aa-4c51-a7c7-175672e1ae40.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/confident-sound-s7vhrm?file=/src/globals.css

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by michecode** [comment]
This is embarrassing 😅 my global css file which imported the fonts was not included in my astro files. Importing it fixed it right away

**Comment by parisosuch-dev** [comment]
I might have the same issue as you. What do you mean by "global css file not included with astro files." Where do you include the imports in what astro files?
