### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by bastianhilton** [withastro/astro#5580]
### What version of `astro` are you using?

1.6.14

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When starting up the application i'm having issues with the following error message:
```
reflect-metadata doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix. (x3)
 error   WebAssembly.instantiate(): expected 3426596 bytes, fell off end @+7785
  File:
    C:/Users/Basti/OneDrive/Documents/My Websites/Handmade Sites/Javascript-Projects/Nuxt-Projects/Applications/AlternateCMS-Framework/AlternateCMS-Astro/src/pages/index.astro
  Stacktrace:
CompileError: WebAssembly.instantiate(): expected 3426596 bytes, fell off end @+7785

10:31:11 PM [serve]    404                                   /sw.js (x2)
```
and this is what shows up on the homepage (index.astro page)
```
[plugin:astro:build] WebAssembly.instantiate(): expected 3426596 bytes, fell off end @+7785

C:\Users\Basti\OneDrive\Documents\My Websites\Handmade Sites\Javascript-Projects\Nuxt-Projects\Applications\AlternateCMS-Framework\AlternateCMS-Astro\C:\Users\Basti\OneDrive\Documents\My Websites\Handmade Sites\Javascript-Projects\Nuxt-Projects\Applications\AlternateCMS-Framework\AlternateCMS-Astro\src\pages\index.astro:0:0
```

### Link to Minimal Reproducible Example

https://github.com/meeovi/alternatecms-astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
`reflect-metadata` doesn't work in Vite and esbuild. See https://stackoverflow.com/questions/68570519/why-cant-reflect-metadata-be-used-in-vite
