### ISSUE TITLE
[astro-rss] Stylesheets no longer work in 1.1.0

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#5581]
### What version of `astro` are you using?

1.6.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

RSS Stylesheets are not rendered in astro-rss v1.1.0 due to missing `type="text/xsl"`-attribute removed in https://github.com/withastro/astro/pull/5550.

```
# 1.0.* working
<?xml-stylesheet href="/pretty-feed-v3.xsl" type="text/xsl"?>

# 1.1.0 broken
<?xml-stylesheet href="/pretty-feed-v3.xsl" encoding="UTF-8"?>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dsatf5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fflaten** [comment]
In repro, visit /rss.xml in the preview. Downgrade `@astrojs/rss` to 1.0.0 to see working stylesheet

**Comment by matthewp** [comment]
@fflaten can you submit a PR to fix this?

**Comment by fflaten** [comment]
Unfortunately not this time.

Build fails in the included devcontainer and I don't currently have time to troubleshoot. Not sure if it's user error or a new issue, but getting this:
![image](https://user-images.githubusercontent.com/3436158/207105201-45573348-1428-4277-ae4d-0f4d6badac62.png)

**Comment by le0pard** [comment]
Had same issue. Downgrade helps. In previous version generated:

```xml
<?xml-stylesheet href="/rss/styles.xsl" type="text/xsl"?>
```

In version 1.1.0 generated (no attribute "type" and not needed attribute "encoding"):

```xml
<?xml-stylesheet href="/rss/styles.xsl" encoding="UTF-8"?>
```

Also 1.1.0 break usage of CDATA in title/description tags and encode everything inside it. No option back CDATA usage.

**Comment by matthewp** [comment]
@le0pard sorry about this, if you're familiar with these features would you mind seeing a PR to fix?

**Comment by fflaten** [comment]
> Unfortunately not this time.
> 
> Build fails in the included devcontainer and I don't currently have time to troubleshoot. Not sure if it's user error or a new issue, but getting this: ![image](https://user-images.githubusercontent.com/3436158/207105201-45573348-1428-4277-ae4d-0f4d6badac62.png)

Might have been a resource-issue using github codespace. Worked fine in devcontainer locally, so will submit a PR as soon as I get familiar with chai.

> Also 1.1.0 break usage of CDATA in title/description tags and encode everything inside it. No option back CDATA usage.

@le0pard Do you mind posting this a new issue so it's not forgotten? 🙂

**Comment by le0pard** [comment]
Thanks, issue created - https://github.com/withastro/astro/issues/5677
