### ISSUE TITLE
Node SSR with Express JSON middleware fails on POST

### ISSUE THREAD

**Issue by erg208** [withastro/astro#5602]
### What version of `astro` are you using?

1.6.15

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

In the Node/Express SSR app we need to use the Express JSON middleware like so.
```
  app.use(express.json()) // for parsing application/json
```

We need this for other Express middleware to work, like for Azure AD SSO. When we do any call to a POST end-point, it does not complete with a response.
Found if we change in https://github.com/withastro/astro/blob/main/packages/astro/src/core/app/node.ts The following code in the class NodeApp render function from:
```
			let body = Buffer.from([]);
			let reqBodyComplete = new Promise((resolve, reject) => {
				req.on('data', (d) => {
					body = Buffer.concat([body, d]);
				});
				req.on('end', () => {
					resolve(body);
				});
				req.on('error', (err) => {
					reject(err);
				});
			});
```
To:
```
			let body = Buffer.from([]);
                        let reqBodyComplete = null;
                        if (req.body) {
                          reqBodyComplete = new Promise((resolve, reject) => {
                            body = Buffer.from(JSON.stringify(req.body));
                            resolve(body);
                          });
                        } else {
                          reqBodyComplete = new Promise((resolve, reject) => {
                            req.on("data", (d) => {
                              body = Buffer.concat([body, d]);
                            });
                            req.on("end", () => {
                              resolve(body);
                            });
                            req.on("error", (err) => {
                              reject(err);
                            });
                          });
                        }
```
Doing this allowed us to utilize the Express JSON middleware and the also allows the Astro end-points have access to the request data. We hope this is a feasible change and would not break anything else.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/erg208-node-astro-ssr

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by erg208** [comment]
Also it would be nice to add a reference in the Request Object to the original Node request in the same function. Like so.
```
  let request = new Request(url, {
    method,
    headers: new Headers(entries),
    body: ["HEAD", "GET"].includes(method) ? null : body
  });
  request.req = req;
```

**Comment by erg208** [comment]
Created a work-around with a SSR adapter called express based on the node adapter. The source can be found in the "expressapp" folder of this stackblitz project [https://stackblitz.com/edit/erg208-node-astro-ssr-n16lzu](https://stackblitz.com/edit/erg208-node-astro-ssr-n16lzu). With this we where able to move forward with implementing Azure AD SSO and in memory session data with our prototype of utilizing Astro.build SSR.

**Comment by matthewp** [comment]
Can anyone submit a PR with a fix?

**Comment by erg208** [comment]
I have never made a PR for a project like this, but will try to do today. I did the fix yesterday locally for the newest version of Astro, so have a good idea where to make the fix.

**Comment by petertjmills** [comment]
@erg208 Would have been happy to myself but didn't want to steal your thunder ;)

**Comment by erg208** [comment]
@petertjmills Thanks, the PR is now available for review.
