### ISSUE TITLE
Astro config were read twice on starting app while using vite loadEnv

### ISSUE THREAD

**Issue by ansidev** [withastro/astro#5606]
### What version of `astro` are you using?

^1.6.15

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

pnpm

### What operating system are you using?

macOS 12.6.1

### Describe the Bug

Astro config was read twice on starting Astro app while using `vite` `loadEnv`.

Please check out the repository for more information.

### Link to Minimal Reproducible Example

https://github.com/ansidev/astro-loadenv-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I'm not exactly sure why this is happening, but what would the problem be?

**Comment by ansidev** [comment]
@matthewp 

> I'm not exactly sure why this is happening, but what would the problem be?

I remember this issue didn't happen in the older version I used. I'm not sure which version is.

By the way, some changes were not expected. I guess that.

**Comment by bluwy** [comment]
This seems to be fixed in the latest Astro version (2.5.5)
