### ISSUE TITLE
Duplicated stylesheets causing duplicated font calls

### ISSUE THREAD

**Issue by santicros** [withastro/astro#5610]
### What version of `astro` are you using?

1.6.15

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

MacOS Monterey 12.5.1

### Describe the Bug

Hi! I've found the stylesheets are always duplicated in the head tag, in two formats:
```
<script type="module" src="..."></script>
```
 and 
```
<style>...</style>
```
Like this:
<img width="1511" alt="Captura de Pantalla 2022-12-15 a las 16 56 30" src="https://user-images.githubusercontent.com/24988424/207909905-52958910-adee-4d8e-b9c5-1aa4407ad753.png">

The problem is that this is making Firefox to do two calls for every font, like so:
<img width="1511" alt="Captura de Pantalla 2022-12-15 a las 16 56 40" src="https://user-images.githubusercontent.com/24988424/207910136-d80586cb-d3a2-4af7-bab0-43ea5ab52541.png">

Our project has quite a lot more kb of fonts, and so this is making the size always de double.

Is the duplication in purpose? Can we do anything to not have Firefox request two times the same fonts? Thanks!

### Link to Minimal Reproducible Example

https://github.com/santicros/astro-bug-stylesheets

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @santicros does this bug happen after running `astro build` or `astro dev`?

**Comment by santicros** [comment]
Hi @delucis this is happening both in `astro dev` and `astro build`. Thanks!

**Comment by delucis** [comment]
For anyone looking at this, you can open @santicros’s reproduction on StackBlitz quickly with this link: https://stackblitz.com/github/santicros/astro-bug-stylesheets

First thing to note is that in dev it may _look_ like CSS is duplicated but this is a little misleading. You see:

<img width="440" alt="Two DOM nodes, one script type module, the other script type text/css" src="https://user-images.githubusercontent.com/357379/208070548-2560e91b-21d2-418f-a20f-c0c16baa16a6.png">

The first `type="module"` is not in fact a CSS file — it’s the small JavaScript module Vite injects during dev to enable HMR. The second `type="text/css"` is the actual CSS, so I only see it once.

When I run `astro build`, in the reproduction this is the full output of the `dist/index.html` that would be served to users:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  <link rel="stylesheet" href="/assets/index.ec7bbf7d.css" /></head>
  <body> Look at the styles. They are duplicated :(</body></html>
```

As far as I can tell, there’s still only one CSS file.

Could you double check that this is really happening on build?

**Comment by santicros** [comment]
Thanks for your response @delucis. I did the build test wrongly and when doing the build it only loads once as you are saying.

I wrongly thought `npm run start` was showing me the result of `npm run build` but it's the same as `npm run dev`. Doing `npm run preview` is properly showing only one stylesheet as you said.

So this bug is only happening on development, I think it's not that important anymore, I'll be closing it.

Thank you!
