### ISSUE TITLE
Can't use RSS with content folder

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#5619]
### What version of `astro` are you using?

1.7.0

### Are you using an SSR adapter? If so, which one?

NONE

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I can't use RSS with Astro when I try to use the content folder to render the rss stuff it will not work. 

This is the error that I get when running the code.

```

 Cannot read properties of undefined (reading 'replace')
  File:
    C:\Users\louis\Desktop\web-projects\ui\test-windows\node_modules\@astrojs\rss\dist\util.js:2:22
  Code:
    1 | function createCanonicalURL(url, base) {
    > 2 |   let pathname = url.replace(/\/index.html$/, "");
        |                      ^
      3 |   pathname = pathname.replace(/\/1\/?$/, "");
      4 |   if (!getUrlExtension(url))
      5 |     pathname = pathname.replace(/(\/+)?$/, "/");
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'replace')
    at createCanonicalURL (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/@astrojs/rss/dist/util.js:2:22)
    at file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/@astrojs/rss/dist/index.js:82:62
    at Array.map (<anonymous>)
    at generateRSS (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/@astrojs/rss/dist/index.js:80:33)
    at getRSS (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/@astrojs/rss/dist/index.js:38:17)    
    at Module.get (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/dist/entry.mjs?time=1671239724287:2315:3)     
    at renderEndpoint (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/runtime/server/endpoint.js:60:18)
    at call (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/core/endpoint/index.js:70:26)
    at async generatePath (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/core/build/generate.js:271:20)
    at async generatePage (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/core/build/generate.js:110:5)
    at async generatePages (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/core/build/generate.js:69:7)
    at async staticBuild (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/core/build/static-build.js:68:7)
    at async AstroBuilder.build (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/core/build/index.js:86:5)
    at async AstroBuilder.run (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/core/build/index.js:127:7)
    at async build (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/core/build/index.js:21:3)
    at async runCommand (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/cli/index.js:150:14)
    at async cli (file:///C:/Users/louis/Desktop/web-projects/ui/test-windows/node_modules/astro/dist/cli/index.js:168:5)    

 ELIFECYCLE  Command failed with exit code 1.

```

This is what my config looks like 

![rss-config](https://user-images.githubusercontent.com/29028601/208215974-b1962ee9-22d0-412c-8a90-cd4ec51d25e1.png)

### Link to Minimal Reproducible Example

https://github.com/louiss0/test-windows

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fflaten** [comment]
Ideally we'd be able to use `getCollection()` API directly as this is the type of scenario it's really useful for.

Ugly workaround:
```js
const slugRegex = /^src\/content\/blog\/(.*?)\.mdx?$/i
...

link: new URL(`/posts/${post.url.replace(slugRegex, '$1/')}`, import.meta.env.SITE).toString(),
```

**Comment by andersk** [comment]
You can use the `getCollection()` API directly.

```js
import rss from '@astrojs/rss';
import { getCollection } from 'astro:content';
import { SITE_TITLE, SITE_DESCRIPTION } from '../config';

const posts = await getCollection('blog');

export const get = () =>
  rss({
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    site: import.meta.env.SITE,
    items: posts.map((post) => ({
      title: post.data.title,
      description: post.data.description,
      pubDate: post.data.pubDate,
      link: post.slug,
    })),
  });
```

**Comment by louiss0** [comment]
> You can use the `getCollection()` API directly.
> 
> ```js
> import rss from '@astrojs/rss';
> import { getCollection } from 'astro:content';
> import { SITE_TITLE, SITE_DESCRIPTION } from '../config';
> 
> const posts = await getCollection('blog');
> 
> export const get = () =>
>   rss({
>     title: SITE_TITLE,
>     description: SITE_DESCRIPTION,
>     site: import.meta.env.SITE,
>     items: posts.map((post) => ({
>       title: post.data.title,
>       description: post.data.description,
>       pubDate: post.data.pubDate,
>       link: post.slug,
>     })),
>   });
> ```

I can't seem to get a good build from doing that.

**Comment by andersk** [comment]
I did verify that it works: louiss0/test-windows#1 ([open in StackBlitz](https://stackblitz.com/github/louiss0/test-windows/tree/0038c1be12ad19cb187e7ec6af33c13828ad458c?file=src%2Fpages%2Frss.xml.js)).

**Comment by louiss0** [comment]
> I did verify that it works: [louiss0/test-windows#1](https://github.com/louiss0/test-windows/pull/1) ([open in StackBlitz](https://stackblitz.com/github/louiss0/test-windows/tree/0038c1be12ad19cb187e7ec6af33c13828ad458c?file=src%2Fpages%2Frss.xml.js)).

I tried out the example but I did not get a good build out of it.  This is what I get when I try to build the site. 

![image](https://user-images.githubusercontent.com/29028601/208269997-432c09fd-6b95-4264-8cbb-e221ffb2b347.png)

Using get collection does not allow you to get the build you want. I don't know what is happening but the files i need refuse to come out. Do I need to build while the server is running or something?

**Comment by andersk** [comment]
It looks like you are running `astro preview`, which does not build anything; it only serves the build that was previously generated with `astro build`. Review the [CLI reference](https://docs.astro.build/en/reference/cli-reference/).

**Comment by louiss0** [comment]
> It looks like you are running `astro preview`, which does not build anything; it only serves the build that was previously generated with `astro build`. Review the [CLI reference](https://docs.astro.build/en/reference/cli-reference/).

I did that after the build the files that are generated from the build on the left. It's not about the command It's about the files. As you can see no html files are generated at all.

**Comment by louiss0** [comment]
I just noticed that I don't get the url from the post when I  use `import.meta.glob()` this is what I get from it 

![image](https://user-images.githubusercontent.com/29028601/208270912-de611dab-a3f3-4028-ad83-338433dad940.png)

**Comment by louiss0** [comment]
> 👍 Ideally we'd be able to use `getCollection()` API directly as this is the type of scenario it's really useful for.
> 
> Ugly workaround:
> 
> ```js
> const slugRegex = /^src\/content\/blog\/(.*?)\.mdx?$/i
> ...
> 
> link: new URL(`/posts/${post.url.replace(slugRegex, '$1/')}`, import.meta.env.SITE).toString(),
> ```

How am I supposed to write the url. I see no url out put any more

**Comment by andersk** [comment]
> As you can see no html files are generated at all.

You seem to have run into a separate `async`-related bug that caused `astro build` to exit early without an error message. Try again with this (also updated at louiss0/test-windows#1).

```js
import rss from "@astrojs/rss";
import { getCollection } from "astro:content";
import { SITE_TITLE, SITE_DESCRIPTION } from "../config";

export const get = async () => {
  const posts = await getCollection("blog");

  return rss({
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    site: import.meta.env.SITE,
    items: posts.map((post) => ({
      title: post.data.title,
      description: post.data.description,
      pubDate: post.data.pubDate,
      link: post.slug,
    })),
  });
};
```

**Comment by louiss0** [comment]
> > As you can see no html files are generated at all.
> 
> You seem to have run into a separate `async`-related bug that caused `astro build` to exit early without an error message. Try again with this (also updated at [louiss0/test-windows#1](https://github.com/louiss0/test-windows/pull/1)).
> 
> ```js
> import rss from "@astrojs/rss";
> import { getCollection } from "astro:content";
> import { SITE_TITLE, SITE_DESCRIPTION } from "../config";
> 
> export const get = async () => {
>   const posts = await getCollection("blog");
> 
>   return rss({
>     title: SITE_TITLE,
>     description: SITE_DESCRIPTION,
>     site: import.meta.env.SITE,
>     items: posts.map((post) => ({
>       title: post.data.title,
>       description: post.data.description,
>       pubDate: post.data.pubDate,
>       link: post.slug,
>     })),
>   });
> };
> ```

You got it the astro team needs to be told that this is how to use `getCollection()` from now on. We have a new problem now. 

I'll have to write lots of boilerplate code to be able to get multiple collections from multiple files. I want the content folder just to be the base. 
![image](https://user-images.githubusercontent.com/29028601/208271856-f204386a-6222-4032-a9cd-f1f1990365db.png)

**Comment by louiss0** [comment]
This is how you use astro with content collections. This is fantastic

![image](https://user-images.githubusercontent.com/29028601/208272217-039f9f0f-c14d-4f12-a619-27b282c73334.png)

**Comment by fflaten** [comment]
> > As you can see no html files are generated at all.
> 
> You seem to have run into a separate `async`-related bug that caused `astro build` to exit early without an error message. I’ve filed that as #5628. Try again with this (also updated at [louiss0/test-windows#1](https://github.com/louiss0/test-windows/pull/1)).
> 
> ```js
> import rss from "@astrojs/rss";
> import { getCollection } from "astro:content";
> import { SITE_TITLE, SITE_DESCRIPTION } from "../config";
> 
> export const get = async () => {
>   const posts = await getCollection("blog");
> 
>   return rss({
>     title: SITE_TITLE,
>     description: SITE_DESCRIPTION,
>     site: import.meta.env.SITE,
>     items: posts.map((post) => ({
>       title: post.data.title,
>       description: post.data.description,
>       pubDate: post.data.pubDate,
>       link: post.slug,
>     })),
>   });
> };
> ```

Thanks! 🚀 I got the early exit issue using `astro build` multiple in my attempts, so though this was limited to `*.astro` files.
