### ISSUE TITLE
TypeScript files in <script> don't run on Vercel

### ISSUE THREAD

**Issue by aleksa-codes** [withastro/astro#5621]
### What version of `astro` are you using?

1.7.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

After upgrading the `mdx`, `rss` integrations and `astro` the website works on the local machine but doesn't show up when deployed to Vercel.

I upgraded my other website which is deployed with GitHub pages and it works just fine.

I tried rolling back to the previous dependencies which worked before and now they don't even work, kinda strange, I am probably missing something.

Here is the latest commit, upgrading dependencies:
https://github.com/aleksa-codes/astro-portfolio/commit/b568d7913cdf8d7ced615c8f381f68e7b7b292df

Website when everything was working, state to which I tried reverting back with old dependencies versions but failed:
https://aleksacodes-e7dmuw6l9-aleksacodes.vercel.app/

Here is what the console returns:

![Capture](https://user-images.githubusercontent.com/64015178/208241117-c0244382-8ee6-4776-92f8-1fe9ea5d1dd7.PNG)

Also Vercel dashboard usually displayed my favicon, now I got this:

![astro](https://user-images.githubusercontent.com/64015178/208240545-58ecb80e-4e10-4fd5-a2fc-1a8e06b76a45.png)

Edit:
Just tried upgrading Node version from 16 to 18.12.1 LTS on Vercel and locally and the build fails, that's maybe even more concerning than my current problem. But I rolled it back to 16, so this could get solved first.

Error message with Node 18:

![error-astro](https://user-images.githubusercontent.com/64015178/208242337-e12d72f6-08a1-4726-9cc2-5708f13f9e44.png)

### Link to Minimal Reproducible Example

https://aleksa.codes

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aleksa-codes** [comment]
After some testing looks like none of my scripts using TypeScript are working anymore when deployed to Vercel.

One of the scripts I have is a FOUC fix that applies `document.body.style.visibility = 'visible';` after the DOM is ready, before that I have style='visibility: hidden;' applied to `body` and that removes FOUC in most of the cases. That is why there is no content seen on my website because the script is never run.

I tried commenting out everything about the FOUC fix and leaving the rest, content shows now, but then the .ts script for snow, copyToClipboard and typewriter don't run as well.

**Comment by aleksa-codes** [comment]
Loos like this is a similar issue: https://github.com/withastro/astro/issues/5632

**Comment by natemoo-re** [comment]
Thanks for the detailed info! Looks like we have a build regression related to our production output in `1.7.x`. We're looking into a fix right away!
