### ISSUE TITLE
OnClick event rendered in map() in child component does not fires

### ISSUE THREAD

**Issue by AL3X1** [withastro/astro#5622]
### What version of `astro` are you using?

1.7.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I trying to render list from `UserList` component that returns `map` of `UserItem` components. 
Each `UserItem` component has `OnClick` event that does not fires if I render in map, but fires separately. 

**UsersList.tsx**
```
import React from "react";
import { useStore } from "@nanostores/preact";
import { users } from "../stores/users.store";
import { UserItem } from "./UserItem/UserItem";

const UsersList = () => {
  const stateUsers = useStore(users);
  return (
    <>
      <UserItem user={{ name: "Test" }} /> // That way it fires alert
      {stateUser.map((x, index) => ( // that way it's not fires alert
        <UserItem user={x} />
      ))}
    </>
  );
};

export default UsersList;
```

**UserItem.tsx**
```
import "./UserItem.scss";

export const UserItem = ({ user }) => {
  return (
    <div className="user" onClick={(_) => alert("user to user")}>
      <span className="name">{user.name}</span>
    </div>
  );
};

```

What I am doing wrong?
**UPD:** I also noticed that children rendered from `map` inside AstroIsland element in html has no `click` event listeners.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/react-ts-3urtt7?file=src/components/UsersList.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @AL3X1! Where do you add the React component to an Astro file?

In Astro, React components are shipped without JavaScript by default (so no client-side interactivity like click handlers is shipped). You need to opt in to sending that JS to users using a `client:*` directive.

You can read more about this in ["Hydrating Interactive Components" in the docs](https://docs.astro.build/en/core-concepts/framework-components/#hydrating-interactive-components).

**Comment by AL3X1** [comment]
Sorry I haven't mentioned that. I did client:load there. 
I adding ReactComponent in astro page (it's a bit different than in example but pretty much same)

```
     <div class="users">
            <UsersList client:load />
        </div>
```

**Comment by AL3X1** [comment]
Well, not an astro issue. I have used nanostores as dependency and issue was because I haven't initialized initial state properly. New items worked well, but initial ones not. Closing the issue as it's not astro.

**Comment by Ibeenoch** [comment]
Facing the same issue, with React island in Astro, i added the client:load directive, it works well during development, but after running npm run build, and served the build it stopped working. I really need a fix, I am using SSR for my project

**Comment by delucis** [comment]
@Ibeenoch For support, please visit https://astro.build/chat
