### ISSUE TITLE
`astro build` exits early without an error message with collections + MDX + top-level await

### ISSUE THREAD

**Issue by andersk** [withastro/astro#5628]
### What version of `astro` are you using?

1.7.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

In this project (minimized from #5619), `astro build` exits early without an error message.

**`astro.config.mjs`**

```js
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";

export default defineConfig({
  experimental: {
    contentCollections: true,
  },
  integrations: [mdx()],
});
```

**`src/content/blog/foo.mdx`**

```md
foo
```

**`src/pages/test.txt.js`**

```js
import { getCollection } from "astro:content";

await getCollection("blog");

export const get = () => ({ body: "test" });
```

### Output

```console
$ astro build
05:20:27 PM [build] output target: static
05:20:27 PM [build] Collecting build info...
05:20:27 PM [build] Completed in 365ms.
05:20:27 PM [build] Building static entrypoints...
05:20:27 PM [content] Types generated
05:20:28 PM [build] Completed in 0.78s.

 generating static routes 
$
```

There is no error message and no “Complete!” message. The expected output `dist/test.txt` is missing:

```console
$ ls dist/
chunks  entry.mjs
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6jktqr

Run `astro build`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Perhaps it's the same issue as https://github.com/withastro/astro/issues/5318

**Comment by pilcrowOnPaper** [comment]
Seems to be an issue with `import.meta.glob()` and/or `Astro.glob()` #5629

**Comment by Princesseuh** [comment]
For context, this still seems to happens despite #5629 being fixed!

**Comment by surjithctly** [comment]
Same issue here. It works when I remove `*.mdx` file out of the content folder.

**Comment by andersk** [comment]
Seems to be working for me.
