### ISSUE TITLE
`Astro.url.pathname` includes trailing dash when building for SSG but not on dev mode

### ISSUE THREAD

**Issue by pilcrowOnPaper** [withastro/astro#5630]
### What version of `astro` are you using?

1.7.1

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

`Astro.url.pathname` returns a different value on dev mode (`dev` command) and build command. 

```ts
// src/pages/hello-word.astro
Astro.url.pathname === "/hello-world"; // dev mode
Astro.url.pathname === "/hello-world/"; // build
```

### Link to Minimal Reproducible Example

https://github.com/pilcrowOnPaper/astro-trailling-dash

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I believe this was intentional depending on the [build.format](https://docs.astro.build/en/reference/configuration-reference/#buildformat) config (since that option was added), but I had find this confusing too, and ideally would be nice if it's consistent.

**Comment by williamhzo** [comment]
been facing the same bug, if i'm not mistaken there was a discussion about this in #4190, and the TL;DR was:
> Ok, we do have consensus now. We will make the build follow build.format so that if it is set to directory (the default), your url will be /page/ and if it is set to file it will be page.html. This should make relative URLs created using Astro.url work as you would want/expect.

but i don't think it solves the inconsistency in the default behaviour between `dev` and `build`.

**Comment by teleclimber** [comment]
I am experiencing this too. This doesn't seem like a "minor bug". All my links work in dev and preview, but are broken in prod because of this. A relative link defined in `/page.md` like this:

```
[blah](destination)
```

...goes to `/destination` in dev and preview, and it goes to `/page/destination/` in prod. The result is I have 404s all over my deployed site  and I'm not sure how to fix it apart from changing every link to be absolute.

I just upgraded all packages and verified it's still happening. Astro 2.3.0 used for pure SSG.

**Comment by bluwy** [comment]
Similar issue: https://github.com/withastro/astro/issues/6623. It would be a breaking change if we fix this, so will also mark it as so if we get around it in the next major.

**Comment by matthewp** [comment]
I don't think this is a bug. If you are using `trailingSlash: 'ignore'` then you are saying that you'll accept either with or without a trailing slash. But it sounds like you want it to *not* have the trailing slash, in which case you should be using `trailingSlash: 'never'`. Am I missing something?
