### ISSUE TITLE
`create-astro` is incompatible with Yarn Berry

### ISSUE THREAD

**Issue by ansidev** [withastro/astro#5637]
### What version of `astro` are you using?

1.7.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn berry

### What operating system are you using?

Mac

### Describe the Bug

1. Run `yarn create astro@latest -- --template with-tailwindcss` (`yarn -v` = `3.3.0`)

Problem:
- Dependency module was not installed.

Workaround:
- cd into project root folder.
- Create an empty `yarn.lock`.
- Run `yarn install`.

2. Run `yarn dev` and go to `http://localhost:3000/markdown-page`.

Problem:
- Page displayed an error.

Workaround:
- Add this line: `nodeLinker: node-modules` into `.yarnrc.yml`.
- Run `yarn install`.
- Run `yarn dev`.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This works for me.

> * Create an empty `yarn.lock`.

Are you getting this error if not?

```
Usage Error: The nearest package directory (/Users/bjorn/Work/repros/astro-yarn-berry/test-yarn) doesn't seem to be part of the project declared in /Users/bjorn/Work/repros/astro-yarn-berry.

- If /Users/bjorn/Work/repros/astro-yarn-berry isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /Users/bjorn/Work/repros/astro-yarn-berry is intended to be a project, it might be that you forgot to list test-yarn in its workspace configuration.
- Finally, if /Users/bjorn/Work/repros/astro-yarn-berry is fine and you intend test-yarn to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.
```

I find `create-astro` seem to swallow it too when auto-installing it so might be good to fix this.

**Comment by levic** [comment]
Can confirm that creating an empty `yarn.lock` fixes this, however the `nodeLinker: node-modules` step is no longer required thanks to #4842

```
$ yarn --version
1.22.19
$ yarn set version berry
$ yarn create astro@latest

astro   v2.0.2 ...

# use defaults for everything except project name:
# - project name: myproject
# - a few best practices
# - install yarn dependencies: yes
# - initialize a new git repository: yes
# - typescript: strict

$ cd myproject
$ yarn dev

Usage Error: The nearest package directory ... doesn't seem to be part of the project declared in ...
```

Workaround:
```
$ touch yarn.lock
```

This now works as expected:
```
$ yarn install
$ yarn dev
```
