### ISSUE TITLE
Content Collections break when file names have spaces

### ISSUE THREAD

**Issue by ispringle** [withastro/astro#5640]
### What version of `astro` are you using?

1.7.1

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When a file in a content collection has spaces in the file name the collection can be fetched, but it will not `render()`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hbxxvt

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by narduin** [comment]
I thought I was going crazy, thank you!
Turns out the old `Macintosh HD` is breaking everything 🥲
