### ISSUE TITLE
Vercel Serveless Adapter not working

### ISSUE THREAD

**Issue by BrightonMboya** [withastro/astro#5657]
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Linux - Ubuntu

### Describe the Bug

I got an Astro App with some react components. When configuring the ```astrojs/vercel/serverless``` it throws an error in the vercel logs even though it works well on the dev server.

Here is my astro.config.mjs
```
import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import react from "@astrojs/react";
import image from "@astrojs/image";

// https://astro.build/config
import vercel from "@astrojs/vercel/serverless";

export default defineConfig({
  integrations: [
    tailwind(),
    react(),
    image({
      serviceEntryPoint: "@astrojs/image/sharp",
    }),
  ],
  output: "server",
  adapter: vercel(),
});
```
Here is my package.json
```
{
  "name": "@example/basics",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev --host --experimental-integrations",
    "start": "astro dev --experimental-integrations",
    "build": "astro build --experimental-integrations",
    "preview": "astro preview --experimental-integrations"
  },
  "dependencies": {
    "@astrojs/image": "^0.12.1",
    "@astrojs/react": "^1.2.2",
    "@astrojs/tailwind": "^2.1.2",
    "@astrojs/vercel": "^2.1.1",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "astro": "^1.6.10",
    "react": "^18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.7.1",
    "sharp": "^0.31.2",
    "tailwindcss": "^3.0.24"
  }
}
```

The CodeSandbox works fine, the issue is the vercel logs
![Screenshot from 2022-12-21 12-31-02](https://user-images.githubusercontent.com/88210399/208884385-ad8087ae-0cd5-4013-ad18-88ac160f7d7f.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/hardcore-panka-zfv6ox?file=/package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ignacio-fm** [comment]
I have the exact same problem 😭

**Comment by dospolov** [comment]
@BrightonMboya @ignacio-fm 

this did the trick for me
![image](https://user-images.githubusercontent.com/670682/211098800-0049a0e2-e55d-4052-b807-fee824a80a44.png)

**Comment by ignacio-fm** [comment]
> @BrightonMboya @ignacio-fm
> 
> this did the trick for me ![image](https://user-images.githubusercontent.com/670682/211098800-0049a0e2-e55d-4052-b807-fee824a80a44.png)

The point is that I don't use react-icons, do you have any idea what the error is specifically due to?

I don't know how to link your solution with [my repository](https://github.com/ignacio-fm/ignacio.info)

Thanks for sharing your experience. A cordial greeting!

**Comment by dospolov** [comment]
@ignacio-fm you can try alternative import
![image](https://user-images.githubusercontent.com/670682/211166047-7e1e91e5-2a3a-4528-b725-1afd4fc10270.png)

**Comment by ignacio-fm** [comment]
@dospolov 
I'm very sorry but I don't understand these images, does this error have to do with the "import"? Besides, what "import" are you referring to specifically? I don't use any of those packages you show.
All the best!

**Comment by BrightonMboya** [comment]
@dospolov The tricked fixed the issue well.

**Comment by ignacio-fm** [comment]
@BrightonMboya how you fix that? Thanks in advance

**Comment by BrightonMboya** [comment]
@ignacio-fm you add "/index" at the end of the import statement.
e.g `import { FaBars, FaTimes } from "react-icons/fa/index";`
