### ISSUE TITLE
MDX file with draft prevents successful build

### ISSUE THREAD

**Issue by LoyalPotato** [withastro/astro#5658]
### What version of `astro` are you using?

1.6.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

The [docs](https://docs.astro.build/en/guides/markdown-content/#draft-pages) mention that we can use `draft: true` in both .md and .mdx files
I have a page with an empty mdx file with this:

```
---
draft: true
---
```

When I go to build the project I get the following error:

```
[astro:jsx] Transform failed with 1 error:
/Users/foo/Documents/Personal/loyalpotato.dev/src/pages/posts/empty.mdx:2:5: ERROR: Expected ";" but found ":"
file: /Users/foo/Documents/Personal/loyalpotato.dev/src/pages/posts/empty.mdx
 error   Expected ";" but found ":"
  File:
    /Users/foo/Documents/Personal/loyalpotato.dev/src/pages/posts/empty.mdx:2:5
  Code:
      1 | ---
    > 2 | draft: true
        |     ^
      3 | ---
    
  Stacktrace:
Error: Transform failed with 1 error:
/Users/foo/Documents/Personal/loyalpotato.dev/src/pages/posts/empty.mdx:2:5: ERROR: Expected ";" but found ":"
    at failureErrorWithLog (/Users/foo/Documents/Personal/loyalpotato.dev/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/foo/Documents/Personal/loyalpotato.dev/node_modules/esbuild/lib/main.js:1413:29
    at /Users/foo/Documents/Personal/loyalpotato.dev/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/foo/Documents/Personal/loyalpotato.dev/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/foo/Documents/Personal/loyalpotato.dev/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/silly-shannon-iuzder?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Hey @LoyalPotato! Looks like you need to install the MDX integration first:

```ts
npx astro add mdx
```

Let me know if this fixes your issue!

**Comment by LoyalPotato** [comment]
@bholmesdev The sandbox that I linked already has the integration as a dependency and it's still throwing the same error. Is it not showing for you?

**Comment by LoyalPotato** [comment]
Ok, it was just missing the `mdx()` in the config. Sorry about that.

**Comment by tordans** [comment]
Thanks for documenting and solving this. I ran into the same problem. I opened https://github.com/withastro/rfcs/discussions/420 to suggest to make the console output more helpful in this / such a situation.
