### ISSUE TITLE
shift style in layout on top of html moves style link from head to body

### ISSUE THREAD

**Issue by wassfila** [withastro/astro#5659]
### What version of `astro` are you using?

1.7.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

simply moving the <style is:global> above the html in Layout, the generation shifts the style from the head to the body

in the minimal reproduction example, I even can show this within the same generation when using two pages

* `index_good.astro` => importing `Layout_good.astro`
* `index_bad.astro` => importing `Layout_bad.astro`

in https://github.com/MicroWebStacks/astro_examples-style-head-body/tree/main/src/pages

I commited the generation with 1.7.2 in dist
https://github.com/MicroWebStacks/astro_examples-style-head-body/tree/main/dist

Note same shift with astro 1.5.2 and 1.0.0

# Preview
* good Layout vs bad layout
<img width="973" alt="image" src="https://user-images.githubusercontent.com/1510763/208928389-4ae81282-5d17-4fa6-9777-62638abab8c8.png">

* good generated layout vs bad generated layout

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/1510763/208928481-05c228fe-9697-4eda-a222-1cdb777f758a.png">

### Link to Minimal Reproducible Example

https://github.com/MicroWebStacks/astro_examples-style-head-body

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
mark

**Comment by wulinsheng123** [comment]
I will take a look; this bug is interesting

**Comment by wulinsheng123** [comment]
`shift style in layout on top of html moves style link from head to body`
because of the compiler happens error.
![image](https://user-images.githubusercontent.com/27261522/212289643-6319ae2c-32ca-487a-863c-a50a1e42ffe8.png)
.
@bluwy 
and could I use a format tool to fix the code format?
Or could I make the compiler fix the format issues?

**Comment by matthewp** [comment]
These types of bugs have since been fixed. Please file a new issue if you still see a problem.
