### ISSUE TITLE
Returning png with hex or base64 in APIRoute doesn't work in dev

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#5660]
### What version of `astro` are you using?

1.7.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Returning a png-image using `base64` or `hex` encoding works in build, but not in dev. In dev the client gets base64/hex-string directly, which obviously doesn't render in the browser.

Code in repro is similar to https://docs.astro.build/en/core-concepts/endpoints/#static-file-endpoints but the example uses `binary`-encoding which seems to be deprecated in Node, so I'm trying to replace it.

Related https://github.com/withastro/docs/issues/2202

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dcmdb9

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by haasal** [comment]
Any news on this? `encoding: "binary"` doesn't work anymore on vercel and netlify (ssr). I would like to help fixing this.

**Comment by haasal** [comment]
Wait, is the encoding even checked by the dev server? I haven't seen anything that would suggest that the encoding matters at all in [Resonse.ts](https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-astro-server/response.ts)

**Comment by HiDeoo** [comment]
I've just hit this issue too. It looks like a workaround might be to convert back the body to a buffer in the [`vite-plugin-astro-server`](https://github.com/withastro/astro/blob/a717c5c76df130b511397de64400bede78e67786/packages/astro/src/vite-plugin-astro-server/route.ts#L203-L208) when handling the route with a `hex` or `base64` encoding:

```diff
+ const response = new Response(result.body, {
+ 	status: 200,
+ 	headers: {
+ 		'Content-Type': `${contentType};charset=utf-8`,
+ 	},
+ });
- const response = new Response(
-   result.encoding === 'hex' || result.encoding === 'base64'
-     ? Buffer.from(result.body, result.encoding)
-     : result.body,
-   {
-     status: 200,
-     headers: {
-       'Content-Type': `${contentType};charset=utf-8`,
-     },
-   }
- );
```

I have yet to find the time to investigate more and see if there is a better fix and also to find a proper way to add tests for this.
