### ISSUE TITLE
Astro build - HTML formatting is slightly screwed up after build (in dist folder)

### ISSUE THREAD

**Issue by HummingMind** [withastro/astro#5662]
### What version of `astro` are you using?

1.7.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Hello,
After building, the output for my index.html formatting is slightly messed up:

This is the source in the .astro file:

![image](https://user-images.githubusercontent.com/87399963/209013945-ad273bfe-978b-44b5-91ef-de42f90edd74.png)

And this is the compiled index.html in the dist folder:

![image](https://user-images.githubusercontent.com/87399963/209013861-6ec1de27-1067-4cf4-921e-ca8c94f073cf.png)

Makes it difficult to look at the produced HTML (outside the browser dev tools). And it bugs my OCD. 😢 😄 

Thank you!

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
@Princesseuh 

Do we include something like html-minifier with safe options to make all the pre-rendered output look either cool or minified?

**Comment by rishi-raj-jain** [comment]
@Princesseuh I think there's already a plugin for this named astro-compress (https://github.com/astro-community/astro-compress/blob/main/src/options/html.ts)

**Comment by rishi-raj-jain** [comment]
@HummingMind Does that plugin solve your use case?

**Comment by Princesseuh** [comment]
Closing since we don't be fixing this. We recommend running a formatter, or other tools to change the output. We'll soon be including partial HTML minification to Astro itself, which should at least make the output more consistent.

**Comment by padaliyajay** [comment]
i am also looking same feature if possible to beautify generated html in dist/ folder

**Comment by laukstein** [comment]
I haven't find any working workaround to beautify HTML output of `astro dev`.
astro.config.mjs allows to define `compressHTML: false`, and to run [astro-html-beautifier](https://github.com/bangkitdev/astro-html-beautifier) or [js-beautify](https://github.com/beautifier/js-beautify), but still `astro dev` will continue to ignore it.

@Princesseuh can this task be reopen to uprise priority of clean beautified HTML output, maybe to have it by default?
