### ISSUE TITLE
Error inside `astro.config.mjs` hangs dev server start on Stackblitz

### ISSUE THREAD

**Issue by Princesseuh** [withastro/astro#5664]
### What version of `astro` are you using?

1.7.2

### Are you using an SSR adapter? If so, which one?

N/A

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

On Stackblitz, if there's an error inside the config file the dev server starts hangs indefinitely and the user needs to do `CTRL+C` to quit. I'm using Arc Browser 0.81.0, which uses Chromium 108.0.5359.125

This seems to work fine in local

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-obbbo4?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Upgrading to Astro 2.0 seems to fix the issue. Stackblitz would show the error message and exit.
