### ISSUE TITLE
modularized CSS gets pushed to all pages.

### ISSUE THREAD

**Issue by FlipFloop** [withastro/astro#5671]
### What version of `astro` are you using?

1.7.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I have several pages that link to `pageName.module.scss`. However every single page references 2 .scss/css (in build) files: `about.css` and a certain page by the name of `GaTechCourseChecker.css`.

You can verify this in the network tab for any page on https://victorguyard.com/.

Willing to share more code.

![p1](https://user-images.githubusercontent.com/19635051/209400254-88009d81-1581-4d0b-b7ad-230e0da6c835.png)
![p2](https://user-images.githubusercontent.com/19635051/209400258-bd8b9c3a-5ab9-4342-95a8-402b2d105280.png)
![p3](https://user-images.githubusercontent.com/19635051/209400492-36d44206-2e83-4f21-a881-dc33139c0e17.png)

### Link to Minimal Reproducible Example

 https://victorguyard.com/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
We'd need a minimal reproducible project including the source code to be able to debug why the CSS works this way.

**Comment by FlipFloop** [comment]
Where do you recommend I set this up @bluwy ?

**Comment by delucis** [comment]
We usually recommend doing this on StackBlitz. This link will kick off a new basic Astro project on StackBlitz and then you can add just the bare essentials in order to trigger the bug: https://astro.new/minimal?on=stackblitz

**Comment by matthewp** [comment]
Going to close since it's been a while. Please open a new issue if you can create a reproduction. We do have similar issues that are being tackled soon, so please try in 2.0.
