### ISSUE TITLE
astro with tailwind incorrect style css order in subpath

### ISSUE THREAD

**Issue by herve-ch** [withastro/astro#5676]
### What version of `astro` are you using?

1.7.2

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

css files (with tailwind)  in subpath (like http://website/subfolder) are imported in the wrong order and custom styles get overridden

it only happen when building for production, local dev is correct, I tried with deno and netlify

it works correctly with astro 1.6.14

i set up a sample in netlify:

Compare: 
https://verdant-kashata-5415d3.netlify.app/test/
https://verdant-kashata-5415d3.netlify.app/

=> TEST H1 in https://verdant-kashata-5415d3.netlify.app/test/
 is not styled with global css, it is overridden, it should be like in https://verdant-kashata-5415d3.netlify.app/

source code : https://github.com/herve-ch/astro-tw

### Link to Minimal Reproducible Example

https://github.com/herve-ch/astro-tw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by herve-ch** [comment]
updated to astro 1.9.1 and still the same problem, am I missing something?

**Comment by matthewp** [comment]
Sorry for not responding earlier, we were busy with 2.0 issues. I'm taking a look at this now.

**Comment by matthewp** [comment]
I would think that this issue shouldn't require an SSR adapter, right? Does this not happen with SSG mode @herve-ch ?

**Comment by herve-ch** [comment]
Hello @matthewp I just updated to latest astro 2.0.2 and netlify adapter and now it happen on both local and netlify deployment.
It happens on both SSG and SSR mode

https://verdant-kashata-5415d3.netlify.app/test/ <-- Tailwind global css are overriden
https://verdant-kashata-5415d3.netlify.app/

Thanks for your awesome work

**Comment by wulinsheng123** [comment]
> Hello @matthewp I just updated to latest astro 2.0.2 and netlify adapter and now it happen on both local and netlify deployment. It happens on both SSG and SSR mode
> 
> https://verdant-kashata-5415d3.netlify.app/test/ <-- Tailwind global css are overriden https://verdant-kashata-5415d3.netlify.app/
> 
> Thanks for your awesome work

You meant that the below code didn't run in the test folder. Right?
```css
<style lang="postcss">

		:global(h1) {
			@apply text-5xl font-semibold w-full mb-4;
		}
</style>
```
I only have seen different CSS.

**Comment by herve-ch** [comment]
> > Hello @matthewp I just updated to latest astro 2.0.2 and netlify adapter and now it happen on both local and netlify deployment. It happens on both SSG and SSR mode
> > https://verdant-kashata-5415d3.netlify.app/test/ <-- Tailwind global css are overriden https://verdant-kashata-5415d3.netlify.app/
> > Thanks for your awesome work
> 
> You meant that the below code didn't run in the test folder. Right?
> 
> ```css
> <style lang="postcss">
> 
> 		:global(h1) {
> 			@apply text-5xl font-semibold w-full mb-4;
> 		}
> </style>
> ```
> 
> I only have seen different CSS.

I'm sorry my sample was not correct. I corrected it and I'm using a Global Layout.

https://verdant-kashata-5415d3.netlify.app/ --> H1 appear correctly

https://verdant-kashata-5415d3.netlify.app/test/  -->H1 doesn't get styled

The 2 pages use same layout.

I noticed the bug happen when I'm fetching posts in /pages/test/index.astro:
 `const allPosts = await Astro.glob("../posts/*.md");` 
if I remove this line, H1 is displayed correctly.

Thanks

**Comment by wulinsheng123** [comment]
I got it.
the same problem that is the CSS order.
![image](https://user-images.githubusercontent.com/27261522/215965483-daa7896e-e662-40df-bb5a-d998769f43b5.png)

**Comment by matthewp** [comment]
Thanks! Taking a look tomorrow.

**Comment by matthewp** [comment]
Got a fix, just need to figure out how to test this scenario.

**Comment by matthewp** [comment]
Fix is in https://github.com/withastro/astro/pull/6176
