### ISSUE TITLE
`.md` included in href for markdown links

### ISSUE THREAD

**Issue by lorenzolewis** [withastro/astro#5682]
### What version of `astro` are you using?

1.7.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

For links within a markdown file, when linking to another markdown file and you include the `.md` extension it does not get stripped from the resulting href. This leads to a 404. 

If you don't include the `.md` extension in the source link then it works as expected. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-y6ntrw-pgakey?file=src%2Fpages%2Fsource.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, as discussed in #5680 this is a result of the fact that Astro does not modify your HTML (or markdown-produced HTML) to do thinks like URL resolution. So closing and we can continue the discussion in that issue.

**Comment by lorenzolewis** [comment]
Relevant RFC discussion opened in https://github.com/withastro/rfcs/discussions/424

**Comment by vernak2539** [comment]
Until this gets into Astro proper, I ended up writing a rehype plugin called [rehype-astro-relative-markdown-links](https://github.com/vernak2539/rehype-astro-relative-markdown-links) specifically for astro to do something like this in `md` and `mdx` files.

It's still a work in progress (only supports `md` and `mdx` relative paths and doesn't support custom slugs [all file based])
