### ISSUE TITLE
[@astrojs/image] Unnecessary `.wasm` output 

### ISSUE THREAD

**Issue by kagankan** [withastro/astro#5689]
### What version of `astro` are you using?

1.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Describe the Bug

Thank you for always developing Astro!
`@astrojs/image` integration is very useful to get image width and height. 😍 

## Problem

1. Clone reproduction repo.
2. Run `npm install` and `npx astro build`
3. There are `.wasm` files in `dist/chunks` folder after build.

To my understanding, wasm files are needed for **image optimization**, and not needed for getting image sizes.
I would like to disable this output, since I'm not using image optimization.

## Want

Disable this output automatically when image optimization is not used,
or allow to turn off this manually.

Thank you.

### Link to Minimal Reproducible Example

https://github.com/kagankan/astro-sample/tree/sample/image-integration

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by danielberndt** [comment]
fyi this issue is also present when activating 

```
  experimental: {
    assets: true,
  }
```

for astro `2.1.2`.

Adding this to the config results in 5.3MB of .wasm files in `dist/chunks`

Note that this also happens when 

```
  image: {
    service: "astro/assets/services/sharp",
  }
```

is set.

**Comment by danielberndt** [comment]
Is it maybe enough to extend this expression to also include `.wasm` files?

https://github.com/withastro/astro/blob/f208b5f897189d67b6a83c1643fab31decacb8fc/packages/astro/src/core/build/static-build.ts#L328

**Comment by sujaykumarh** [comment]
Hello, Here's what i found, 

this is the line of code that copies `.wasm` files which was added in [PR#4738](https://github.com/withastro/astro/pull/4738)
https://github.com/withastro/astro/blob/c341bd07ac84e51aeb97fab581e9730a540c5c72/packages/astro/src/assets/vite-plugin-assets.ts#L192


the `.wasm` vendor files are present at https://github.com/withastro/astro/tree/main/packages/astro/src/assets/services/vendor/squoosh

<br>

i do not understand the need for wasm files to be present for a SSG site, having tested on `astro v2.1.3` and with experimental feature `astro:assets` this seems unnecessary as images are optimized on build and no wasm file is  loaded on any request on a SSG site after build


<br>
<br>

**Possible solution**

**an option to disable export of `.wasm` files in `astro.config.mjs` would be helpful** if  wasm files are required to be present for some reason by default


```js
// example config of astro.config.mjs
export default defineConfig({
  ....
  vite: {
    build: {
      assets: {
         export_wasm: false, // or export_vendor: false,
      },
    },
  },
});
```

**Comment by Princesseuh** [comment]
The WASM files are required during the build, they just aren't cleaned up properly.
