### ISSUE TITLE
 Relative pathing breaks in pages that are 2 routes deep

### ISSUE THREAD

**Issue by sydist** [withastro/astro#5704]
### What version of `astro` are you using?

1.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 11

### Describe the Bug

`<a href="image.png">` works when both the document and image are in the same directory, but stops working when they're both in a directory 2 routes deep from the root document.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wakc19?file=src/pages/sub/sub2/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nandito** [comment]
I'm new to Astro, but I haven't seen any reference in the docs that say the `public` folder structure should match the `pages` folder structure.

I confirm that it works weird now, as having `<a href="image.png">` in an `index.astro` file:
* looks for `public/sub/image.png` if the `index.astro` file is in the `pages/sub` folder
* and also looks for `public/sub/image.png` if the `index.astro` file is in the `pages/sub/sub2` folder

I was wondering what if I want to put the image to a `public/images` folder and I found that adding `/` to the beginning of the href path can refer to the `public` folder.

So if I have a `public/images/image.png` file then the `index.astro` file with `<a href="/images/image.png">` navigates to the correct image, even if `index.astro` file is 2 routes deep from the root.

In your StackBlitz example you can use `href="/sub/sub2/favicon.png"` to make it work.

**Comment by sydist** [comment]
> In your StackBlitz example you can use href="/sub/sub2/favicon.png" to make it work.

Yes, I am aware of that, in fact, that's what I currently do in one of my projects.

When building, if the folder structure for `pages/` matches the one in `public/`, it will put the assets alongside the `index.html` file in `dist/`

For example:

If you have `pages/sub1/sub2/index.astro` and `public/sub1/sub2/image.png`, when you build the project they end up in the same dist folder `dist/sub1/sub2/index.html` and `dist/sub1/sub2/image.png`, so accessing the image with `<a href="image.png">` or `<img>` should link to the image correctly, but it doesn't when using `astro dev` or `astro preview`.

It works however when I just drag and drop the `index.html` in my browser.

**Comment by sydist** [comment]
So I did some testing, it seems the problem might be related to Vite instead of Astro, the same exact problem persists when using Vite.

**Comment by sydist** [comment]
After even more testing, it appears my previous comment was incorrect, this is a problem with Astro, and I figured out why too.

I found out this only happens in Astro because `localhost:300/sub` is equivelent to `localhost:300/sub/`.

For example:
If you have a page in `pages/sub/index.astro` you can access it from BOTH `localhost:300/sub` and `localhost:3000/sub/`, that last slash matters, because when you click the link in the former situation, the browser thinks it's in the root and looks for the image there, not inside the `sub/` directory.

This behaviour doesn't happen in Vite, therefore this must be an Astro bug.

**Comment by sydist** [comment]
Note that this issue still happens in the most recent version (1.9.1)

**Comment by sydist** [comment]
Though I'm not sure if this is truly a bug or intended behaviour anymore.

**Comment by sydist** [comment]
Looks like there is a config option, `trailingSlash`, you can just set that to "always" instead of manually having to fix it when it happens.
