### ISSUE TITLE
getting git hub errors

### ISSUE THREAD

**Issue by osde8info** [withastro/astro#5708]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

web

### Describe the Bug

goto 
https://github.com/withastro/astro

click 
https://github.com/withastro/astro/blob/main/packages/astro/tsconfigs/base.json
or
https://github.com/withastro/astro/blob/main/packages/astro/tsconfigs/strict.json
or 
https://github.com/withastro/astro/blob/main/packages/astro/tsconfigs/strictest.json

screen flashes then you get
```
There was an error parsing the JSON document. The document may not be well-formed.
Unexpected token '*', "* Add tsco"... is not valid JSON
* Add tsconfig templates to extend from

* Add changeset

* Right order for assign parameters

* Add tsconfigs to export map
* 
```

### Link to Minimal Reproducible Example

https://astro-vercel-astro.vercel.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! I'm not quite sure I get what you mean, those links work fine for me. Where are you seeing those errors?

**Comment by osde8info** [comment]
using windows 10 + edge + nav to https://github.com/withastro/astro/blob/main/packages/astro/tsconfigs/base.json

you will see the following error

![image](https://user-images.githubusercontent.com/51541/210132555-90a30806-0a4c-43a8-b249-72c5dafa93c5.png)

btw it might be a ms/github error not yours

**Comment by delucis** [comment]
Thanks for the extra information! I don't think this is an Astro issue but a browser issue/GitHub bug, so we can probably close this.
