### ISSUE TITLE
Missing TailwindCSS rules of CSS in inline styles

### ISSUE THREAD

**Issue by oscard0m** [withastro/astro#5710]
### What version of `astro` are you using?

1.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm (and yarn in CodeSandbox)

### What operating system are you using?

MacOS Ventura 13.0.1 (22A400)

### Describe the Bug

When using TailwindCSS with Astro, some CSS styles from Tailwind are not being served. I'm not sure why.

Here's an example where I'm adding `rehypeAutolinkHeadings` plugin to a project (https://codesandbox.io/s/practical-astro-tailwind-missing-classes-qhbsyz). Even I'm adding the expected Tailwind CSS classes to elements, they don't appear when inspecting with DevTools (missing `.flex-row`, `.items-baseline`...).

With Tailwind Playground (no Astro in the middle), the CSS classes work: https://play.tailwindcss.com/GRcoxf3pJl

With a bit of guidance o what's the issue I would be happy to work on a PR if necessary.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/practical-astro-tailwind-missing-classes-qhbsyz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by mandar1jn** [comment]
Hi. I’m currently on mobile so I can’t really look at your code but your issue title mentions inline. Tailwind css doesn’t work when using Astro inline css.

**Comment by oscard0m** [comment]
> Hi. I’m currently on mobile so I can’t really look at your code but your issue title mentions inline. Tailwind css doesn’t work when using Astro inline css. 

Thanks for the reply. Maybe the Issue title is misleading.

When building Astro with Tailwind, there's a resulting `<style>` tag with Tailwind's CSS rules if I'm not wrong. 

I'm guessing the build step is reducing the amout of CSS rules served to the minimum ones necessary given the classnamss used in HTML and markdown markup. Is this assumption correct?

If you inspect in the example I shared you will see some Tailwind classes missing when using Astro.

I hope I have explained myself better now.

**Comment by velialiev** [comment]
> > Hi. I’m currently on mobile so I can’t really look at your code but your issue title mentions inline. Tailwind css doesn’t work when using Astro inline css.
> 
> Thanks for the reply. Maybe the Issue title is misleading.
> 
> When building Astro with Tailwind, there's a resulting `<style>` tag with Tailwind's CSS rules if I'm not wrong.
> 
> I'm guessing the build step is reducing the amout of CSS rules served to the minimum ones necessary given the classnamss used in HTML and markdown markup. Is this assumption correct?
> 
> If you inspect in the example I shared you will see some Tailwind classes missing when using Astro.
> 
> I hope I have explained myself better now.

That is how tailwindcss works itself

**Comment by oscard0m** [comment]
> That is how tailwindcss works itself, this behavior has nothing to do with astro or integration

Thanks for the answer. I'm probably missing some details on how Astro works with Tailwind integration.

Do you know why my example in Tailwind Playground works and why my example with Astro+Tailwind doesn't?

Thank you!

**Comment by matthewp** [comment]
Closing for no response, please reopen if you can still see the problem.

**Comment by oscard0m** [comment]
> It's a bit hard to navigate through your reproduction since it's fairly large, but your `content` array in your Tailwind config does not includes files in the root directory, only files inside `src`, so the classes used in your config files are not included by Tailwind. This is purely a Tailwind thing, not related to Astro
> 
> Let me know if it works after updating it!

That was exactly the issue @Princesseuh, I didn't know Tailwind to get content from [JS files adding classes to HTML](https://tailwindcss.com/docs/content-configuration):

> If you have any JavaScript files that manipulate your HTML to add classes, make sure you include those as well

---

Sorry for the delay in the response and for the noise this could cause to Astro's backlog
