### ISSUE TITLE
HMR: style not updating with my folder configuration

### ISSUE THREAD

**Issue by Vap0r1ze** [withastro/astro#5713]
### What version of `astro` are you using?

1.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows 10

### Describe the Bug

Style updates do not apply with this astro config:
```js
{
    publicDir: "./docs/public",
    srcDir: "./docs",
    outDir: "./dist/docs/",
    root: "./docs",
    integrations: []
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-hmr-style-bug?file=docs/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Vap0r1ze** [comment]
I'm unfamiliar with Vite hmr and I think I need help identifying the issue

**Comment by matthewp** [comment]
The issue is that your root and the `srcDir` are the same. You want the root to be `.`. It should be the folder that your Astro config is in. Just removing the `root` config fixes this.
