### ISSUE TITLE
`globalThis[Symbol.for("import.meta")]` is undefined

### ISSUE THREAD

**Issue by shadichy** [withastro/astro#5722]
### What version of `astro` are you using?

1.8.0

### Are you using an SSR adapter? If so, which one?

yes, im using Node (as a placeholder)

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

when I ran `astro dev`, everything seemed no problem. but as soon as I opened it on my web browser (localhost:3000), I got this error 
```
(4) Uncaught TypeError: Cannot set properties of undefined (setting 'fileHref')
    at env.mjs:1:335
```
turns out it was because of this in `entry.mjs`
```
let s=Symbol.for("import.meta"),m=globalThis[s]
// ...
m.fileHref="/some/file.js";
m.siteHref="http://localhost:3000/";
m.requestHref=(m.siteHref+m.pageHref.slice(48,-6)).replace(/\/index$/i, '/')
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fdmsn9

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This looks like a bug related to a library. It could be a bug in Astro but is very likely a bug in the library. Please investigate this more and if you can recreate the bug without the library please resubmit it here.

**Comment by shadichy** [comment]
@matthewp i do have link to minimal reproducible example
so what do you mean by "a bug in the library"? which "library"?

**Comment by shadichy** [comment]
turn out it was because of [@astropub/imports](https://github.com/astro-community/import-meta)
will try [@astropub/assert](https://github.com/astro-community/assert) and find out if it has the same problem
thanks for your reply
