### ISSUE TITLE
Incorrect binary files are generated by static file endpoints

### ISSUE THREAD

**Issue by bmdelacruz** [withastro/astro#5725]
### What version of `astro` are you using?

1.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When `Response` is returned from a static file endpoint handler and the response's body is not a utf-8 encodable binary data, e.g. images, Astro generates incorrect binary files.

Check out https://github.com/withastro/astro/pull/5258#discussion_r1060315590 to see the code that causes the bug.

The code below is a simple static file endpoint handler that reproduces the bug. When the generated file is inspected, you'll see that it contains `<ef bf bd>` not `<ff>`. Check out the stackblitz link below to see it in action.
```ts
import type { APIRoute } from 'astro';

export const get: APIRoute = async function () {
  return new Response(new Uint8Array([0xff]));
};
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-y1allf?file=README.md&view=editor

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Updated reproduction: https://stackblitz.com/edit/github-y1allf-u1s3qo?file=package.json&view=editor
