### ISSUE TITLE
Astro does not work on x64/x68 processors that don’t support AVX/AVX2

### ISSUE THREAD

**Issue by mandar1jn** [withastro/astro#5729]
### What version of `astro` are you using?

1.8.0 (I think. Not my project)

### Are you using an SSR adapter? If so, which one?

Unknown

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

On processors that don’t support the optional AVX/AVX2 instructions, ‘Astro dev’ crashes with the output: ‘CODE illegal hardware instruction (core dumped)  COMMAND’. An executable (maybe the compiler wasm file?) utilises the optional AVX/AVX2 instruction. This causes the program to crash on processors not supporting these instructions. 

### Link to Minimal Reproducible Example

Impossible

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mandar1jn** [comment]
It is worth noting that 95.14% of processors support AVX and 88.97% support AVX2. This should be considered when deciding to build these files without these instructions as these can cause quite significant speed improvements in some cases

**Comment by mandar1jn** [comment]
The original report for this issue can be found here: https://discord.com/channels/830184174198718474/1059684152766640158/1059684152766640158

**Comment by matthewp** [comment]
Interesting, any ideas what in our code is depending on that?

**Comment by mandar1jn** [comment]
No clue. But to narrow it down, it crashes before anything is logged when using Astro dev

**Comment by Princesseuh** [comment]
In Node, I'd wager that the few things using AVX are related to SSL or possibly SHA and other hashes calculations

**Comment by Princesseuh** [comment]
Closing since we won't be fixing this. Ever since Astro's creation, we've only gotten a single report about this and since we don't really know where we use AVX/AVX2 ourselves, it's highly likely that it's in a required dependency (maybe some wasm stuff, maybe esbuild etc) that we cannot do much about. Sorry for the inconvenience
