### ISSUE TITLE
Empty "chunks" directory in build output

### ISSUE THREAD

**Issue by kasperaamodt** [withastro/astro#5735]
#4435 This bug appears to be back, and it messes with Vercel deployments.

![Screenshot 2023-01-03 at 23 58 15](https://user-images.githubusercontent.com/44305520/210455184-6d1b44eb-c478-4cda-bed8-8610ad927722.png)

![Screenshot 2023-01-03 at 23 33 36](https://user-images.githubusercontent.com/44305520/210455129-aace99f5-2af8-4580-8003-1dbfe6e11f3b.png)

**Comment by Eldemarkki** [comment]
Yep, I'm getting this on version 1.8.0 too

**Comment by Eldemarkki** [comment]
This was probably a problem with Vercel, because I just tried redeploying and it worked without problems. @kasperaamodt could you try redeploying to see if it was fixed for you as well?

**Comment by wulinsheng123** [comment]
mark

**Comment by wulinsheng123** [comment]
I did meet this problem 
![image](https://user-images.githubusercontent.com/27261522/211759923-2bdb8562-49b4-43f1-a61f-e47f49ab686c.png)

**Comment by natemoo-re** [comment]
@kasperaamodt please use our provided issue template! Triaging issues is a lot harder when they don't include all the necessary information.

Is this on a specific version of Astro? We have made some changes to our bundling in 2.0.0-beta.1 and this definitely isn't a problem on the latest.

**Comment by natemoo-re** [comment]
Specifically, keep an eye out for this release https://github.com/withastro/astro/pull/5792

**Comment by matthewp** [comment]
Does this still occur?

**Comment by bholmesdev** [comment]
@kasperaamodt Checking if this is still an issue for you with Astro 2.0. Try installing `astro@latest` and let us know if that resolves your issue. If not, we'll close this as "could not reproduce."

**Comment by kasperaamodt** [comment]
@bholmesdev sorry for not answering, this was probably a Vercel issue, and was resolved quite fast. Sorry again for keeping it open.

**Comment by bholmesdev** [comment]
Ah no problem, thanks for checking! Glad we found a fix
