### ISSUE TITLE
Astro capable of rendering / outputting invalid HTML documents

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/astro#5738]
### What version of `astro` are you using?

v1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

## What? 
- Consider an astro page whose content is a valid HTML document. 

```html 
// src/pages/index.astro
<!DOCTYPE html>
<html lang="en-GB">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>HTML 101</title>

    <style>
      p {
        color: red;
      }
    </style>

    <script>
      console.log('Hello world');
    </script>
  </head>
  <body>
    <p>Hello World</p>
  </body>
</html>
```

- If the said astro page imports another complete valid HTML document, astro behaves funny 

```jsx
// update src/pages/index.astro

---
import AnotherIndex from '../AnotherIndex.astro'
---

// ... same content as earlier but change the content of the body

<body> 
   <p>Hello world </p>
   // where AnotherIndex has the same full HTML content i.e., HTML, body, head, and meta tags
   <AnotherIndex />
</body>
```
-  You can view the page e.g., by running `astro dev`. The initial bundling seems correct, but the other HTML is attempted to be rendered in the page's body 
![CleanShot 2023-01-04 at 09 21 50](https://user-images.githubusercontent.com/10930234/210513106-5c1ae655-63f6-4a6b-9b8e-14460c608645.png)

This produces invalid HTML. The browser still attempts to render this of course. 

![CleanShot 2023-01-04 at 09 23 16](https://user-images.githubusercontent.com/10930234/210513241-8afd8df0-467b-406f-915f-c9609f4f5a81.png)

## Expected behaviour 
I realise this is tricky, however, isn't is more consistent to either throw an error or spit out a warning e.g., in dev or upon building `astro build` about the HTML output being potentially wrong? i.e., adding static HTML validation to the dev / build step? 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ngf8z6?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I believe this is intentional. Astro allows you to template HTML, even invalid ones, and browsers are quite lenient to invalid HTML that it could work sometimes too. There doesn't seem to be a robust html validator package too if we want to do so. Closing as this is working as expected.
