### ISSUE TITLE
Cannot access 'SITE_TITLE' before initialization during build in 2.0.0-beta.0

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#5754]
### What version of `astro` are you using?

2.0.0-beta.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Getting the following error when building (not dev) using 2.0.0-beta.0. Works fine in 1.9.0.

```console
generating static routes 
 error   Cannot access 'SITE_TITLE' before initialization
  File:
    file://file:///home/projects/github-zea7ll/node_modules/astro/dist/core/build/generate.js:81:20
  Stacktrace:
Error: Cannot access 'SITE_TITLE' before initialization
    at async Module.generatePages (file://file:///home/projects/github-zea7ll/node_modules/astro/dist/core/build/generate.js:81:20)
    at async Module.staticBuild (file://file:///home/projects/github-zea7ll/node_modules/astro/dist/core/build/static-build.js:85:7)
    at async AstroBuilder.build (file://file:///home/projects/github-zea7ll/node_modules/astro/dist/core/build/index.js:103:5)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zea7ll

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Does this happen in 1.x?

**Comment by fflaten** [comment]
No, works fine in 1.9.0.

**Comment by natemoo-re** [comment]
Just FYI @matthewp this looks like something related to the way our intermediate (server) bundle is generated before the pages are statically rendered. You can see this in the reproduction by inspecting the files in the `dist/` directory before the error occurs. The constants are re-exported from the `index` page chunk, which seems to be the source of the problem.

**Comment by fflaten** [comment]
> I suspect this would happen on `1.x` with the `--experimental-prerender` flag passed

Can confirm 1.9.0 breaks with `astro build --experimental-prerender` in the new simplified repro: https://stackblitz.com/edit/github-zea7ll-jop67q  (which is currently set to 2.0.0-beta.0)

**Comment by natemoo-re** [comment]
Thanks for your patience, I'm looking into this one again today. Will be sure to share progress updates.

**Comment by natemoo-re** [comment]
I was able to determine _what_ bundling change causes this, but I'm still unsure of the _correct_ way to split each page into a chunk without hitting this issue. 

That being said, per-page splitting is purely cosmetic. If we emit a single chunk, this is no longer an issue.
