### ISSUE TITLE
Installing Image component with Netlify adaptor crashes site in prod.

### ISSUE THREAD

**Issue by nicatspark** [withastro/astro#5774]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Works in development mode but crashes in prod with Netlify. No need to use the Image component, it crashes in as soon you have it installed. Site always works in development.

To reproduce:
- Create a minimal Astro app `npm create astro@latest`.
- Add the Netlify adaptor `npm astro add netlify`
- Add the image component `npm astro add image`
- Prod crashes.
- Netlify deploy log will tell you, you need to create a `netlify.toml` file (shouldn't this come with the adaptor? Anyway...) containing 
```
[functions]
  external_node_modules = ["astro"]
```
- Install the netlify.toml file.
- Site still crashes in prod (new error message though)
- Remove Image component and it works again.

### Link to Minimal Reproducible Example

https://profound-elf-d15d29.netlify.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by eostrom** [comment]
Can confirm. A little more info:

- Here's a [repo.](https://github.com/eostrom/astro-image-netlify-ssr)
  - I took slightly different steps to get there but it crashes the same way.
  - This is the version without `external_node_modules`, but it's there to uncomment out if you want.
- I can reproduce it locally with the Netlify CLI.
  - `yarn add netlify-cli` or use `npm install -g` or `npx` or whatever you're into.
  - `netlify build && netlify dev`
- Here's the "before" error:

```
TypeError: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at createRequire (node:internal/modules/cjs/loader:1218:11)
    at .netlify/functions-internal/chunks/image-pool.abfa6f7b.mjs (/Users/eostrom/workspace/swagleft/astro-image-netlify-ssr/.netlify/functions-internal/chunks/image-pool.abfa6f7b.mjs:135:20)
    at __init (/Users/eostrom/workspace/swagleft/astro-image-netlify-ssr/.netlify/functions-serve/entry/src/.netlify/functions-internal/entry.js:37:56)
    at /Users/eostrom/workspace/swagleft/astro-image-netlify-ssr/.netlify/functions-internal/entry.mjs:1898:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_VALUE'
```
