### ISSUE TITLE
Lit Element loses prop state for subsequent renders when rendered as island

### ISSUE THREAD

**Issue by woutervroege** [withastro/astro#5777]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Hi,

I've come across an issue that doesn't render lit elements correctly when rendering as an island.
The inital render is just fine, though subsequent renders fail to remember the current value / state of props that do not have default values defined in the lit constructor function. This just works fine when using lit elements in other environments than Astro.

We've put together a codesandbox that demo's the undesired behavior. It consists of 3 similar lit elements that are rendered as islands. One of them has a constructor value, a second one doesn't and a third one also doesn't but reflects the attribute (which also seems to fix the issue at hand).

When the button is pressed you can see that 1 of the elements loses its correct state.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/astro-lit-update-bug-h1imu8?file=%2Fsrc%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Would love someone more familiar with Lit and why this might happen (and why Astro might be causing this) to work on this if possible.

**Comment by woutervroege** [comment]
I can look into this issue. The assumed workaround is not realistic as devs will bring external component libraries instead of building UI components in the astro repo. Assuming these components will add `reflect: true` to all their props for just this use case would break the separation of concerns and affect performance.

**Comment by matthewp** [comment]
Components that don't have `reflect: true` probably weren't created with SSR in mind. Whether or not we can make these types of components work in an SSR world is an open question, happy to receive a PR if you figure it out!

**Comment by woutervroege** [comment]
@matthewp To rule out the possibility that it's the underyling `@lit-labs/ssr` lib that causes the issue I've just created a sandbox that directly renders using lit-ssr, and hydrate a lit element. Here you can see (although it renders shadow dom twice, whut?) that the rendered element keeps its correct state when updating.

**Comment by matthewp** [comment]
@woutervroege that's actually working differently than how it works in Astro. In Astro you don't render a string template, you render the Element itself. We have to take the constructor function and create an instance of it. To do this we have to infer what should be an attribute and what should be a prop. In your example you are explicitly using an attribute.

The code that is causing this is likely here: https://github.com/withastro/astro/blob/main/packages/integrations/lit/server.js#L41-L46

You might want to look at the `blame` history to see why we do it like this. It's possible the reasons are no longer relevant or just wrong. In which case maybe we can or should change it.

**Comment by woutervroege** [comment]
Getting rid of the conditional at L41-L46 and simply rendering everything as attributes seems to resolve the issue.
Since lit props have an attribute by default would be an ok solution.

However, `ssr-lit.test.js` fails. @matthewp is there a quick way to run just this file to see what's going on there?

**Comment by matthewp** [comment]
@woutervroege 

```
node packages/astro/node_modules/mocha/bin/_mocha --timeout=30000 packages/astro/test/ssr-lit.test.js
```
