### ISSUE TITLE
[astro-rss] Forced closing tags in customData

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#5794]
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Empty elements set in `customData` are converted to use closing tag.

Ex:
`customData: '<atom:link href="${import.meta.env.SITE}rss.xml" rel="self" type="application/rss+xml" />'`
becomes:
`<atom:link href="https://domain.com/rss.xml" rel="self" type="application/rss+xml"></atom:link>`

**Possible solution**
Including `suppressEmptyNode: true` in the `xmlOptions` used with `XMLParser` and `XMLBuilder` fixes this. Any downsides?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9mkavk

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fflaten** [comment]
Bonus: Should we include `atom:link` in channel by default per best practice?

See https://www.rssboard.org/rss-profile#namespace-elements-atom-link and https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html

**Comment by igorskyflyer** [comment]
> customData: '<atom:link href="${import.meta.env.SITE}rss.xml" rel="self" type="application/rss+xml" />'

I am aware that this is a closed issue but I am currently working on adding an RSS feed to my Astro site and this issue came up and I tried to add the tag but unfortunately it can only be added to each feed entry as customData which is not how it should work. The `atom:link` tag should be in the `<channel>` tag as @fflaten mentioned and only be included once.

Is there a workaround for this issue?

**Comment by fflaten** [comment]
This already works. You probably set `customData` inside the `items`-array (entry values). Set it at the same level as `items`. Ex I use:

```ts
return await rss({
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    site: context.site!,
    xmlns: {
      'atom': 'http://www.w3.org/2005/Atom'
    },
    items: posts.map((post) => ({
      link: '/posts/' + post.slug,
      title: post.data.title,
      pubDate: post.data.publishDate,
      description: post.data.description,
      categories: post.data.tags
    })),
    customData: [
      '<language>en-us</language>',
      `<atom:link href="${new URL('rss.xml', context.site)}" rel="self" type="application/rss+xml" />`
    ].join(''),
    stylesheet: '/pretty-feed-v3.xsl',
  });
```
