### ISSUE TITLE
`--host` is missing after restart

### ISSUE THREAD

**Issue by chenxsan** [withastro/astro#5799]
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

So I was running `npm run dev -- --host` to start the devServer:

```
> astro dev --host

06:34:02 PM [content] Types generated
06:34:03 PM [content] Watching src/content/ for changes
  🚀  astro  v1.9.1 started in 839ms
  
  ┃ Local    http://localhost:3001/
  ┃ Network  http://192.168.2.66:3001/
             http://10.147.19.74:3001/
             http://169.254.164.104:3001/
```

And I was able to access url like `http://192.168.2.66:3001/`.

Then I made a change to my `tailwind.config.cjs` file, saved the file and I can saw the terminal updated with logs:

```
06:35:17 PM [astro] update /tailwind.config.cjs
06:35:17 PM [astro] Configuration updated. Restarting...

06:35:17 PM [content] Types generated
06:35:18 PM [content] Watching src/content/ for changes
06:35:18 PM [astro] update /src/content/types.generated.d.ts
```
Now I can no longer access `http://192.168.2.66:3001/` while I was still able to open `http://localhost:3001/`.

I can see `config.server.host` set to `true` in the beginning,

<img width="475" alt="" src="https://user-images.githubusercontent.com/1091472/211191618-87689543-78ce-4fb4-91c2-14a1e177f45f.png">

But It was reset to `false` after restart:

![](https://user-images.githubusercontent.com/1091472/211191704-3ca6cb9b-ed9f-4f67-94ff-83dafc391a81.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nvmtqq?file=tailwind.config.cjs&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! Definitely seems like a bug in our restart logic, but it does look like we're passing CLI arguments through correctly.

https://github.com/withastro/astro/blob/main/packages/astro/src/core/dev/restart.ts#L153

I wonder if this is just an issue with how we're displaying the message? Happy to review a PR if you want to look into this more!

**Comment by chenxsan** [comment]
> 

I believe that `flags` comes from https://github.com/withastro/astro/blob/main/packages/astro/src/core/dev/dev.ts#L38 which is always an empty `{}`.
