### ISSUE TITLE
Astro slot takes priority over vue named slots

### ISSUE THREAD

**Issue by DaniFoldi** [withastro/astro#5801]
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

macOS Ventura 13.1

### Describe the Bug

When a component has more than one slot in a vue component, named slots are used with the following syntax: `<slot name="example" />`.

The component is then used with an interesting syntax:

```vue
<MyComponent>
  <template #example>
    <h1>Hi</h1>
  </template>
  <template>
    <h2>Hello again</h2>
  </h2>
</MyComponent>
```

Unfortunately, I believe that astro's slots take priority over this syntax, and render into a string like (prettified)
```html
<div class="counter-message">
  <astro-slot>
    <template #title="" class="astro-NZOEPMJF">
	  <h1 class="astro-NZOEPMJF">Hello, Vue!</h1>
    </template>
    <template class="astro-NZOEPMJF">
	  <p class="astro-NZOEPMJF">Message</p>
	</template>
  </astro-slot>
</div>
```

This occurs whenever any non-default slot of a vue component is used; all slots of the component are left empty and instead astro slots are generated.

---

Changes in stackblitz from the example:
- Add named slot title to Counter.vue
- Use title and default slots of Counter in index.astro

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rp5kxs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Do we document named slot support in framework components? I'm not sure that we do, but I might be wrong. cc @delucis

**Comment by delucis** [comment]
Not extensively but we do say:

![image](https://user-images.githubusercontent.com/357379/211339663-8646c050-566e-4672-844d-27641cb6aebf.png) ([Source](https://docs.astro.build/en/core-concepts/astro-components/#named-slots))

And in the UI framework docs we also mention them while explaining slots: https://docs.astro.build/en/core-concepts/framework-components/#passing-children-to-framework-components

**Comment by natemoo-re** [comment]
Is the following in a `.vue` file or an `.astro` file?

```html
<MyComponent>
  <template #example>
    <h1>Hi</h1>
  </template>
  <template>
    <h2>Hello again</h2>
  </h2>
</MyComponent>
```

We don't support the `#example` syntax in `.astro` files, that is a Vue feature.

**Comment by DaniFoldi** [comment]
Indeed, I was using the shorthand syntax, however I wasn't able to render the component successfully with the regular vue syntax (`v-slot:example`), or the astro syntax (`slot="example"`).

**Comment by matthewp** [comment]
@DaniFoldi can you provide a reproduction that uses Astro slot syntax? Only Astro syntax works in Astro files.

**Comment by kissu** [comment]
Thanks for this one, works well!
I guess that scoped slots are a stretch tho. 🤔

**Comment by yoyo837** [comment]
I'm also looking for information on support for vue scoped slots in astro files

**Comment by ahsath** [comment]
i know this is closed but if you do something like this inside an astro component:

```HTML
<VueHeaderComponent client:load slot="header">
  <VueComponent client:load slot="trailing" />
</VueHeaderComponent>
```

it will cause a hydration mismatch because astro will render it with the `slot="trailing"` attr (i think that's what is going on), the trick is to set `defineOptions({ inheritAttrs: false });` inside those server rendered components so the generated HTML does not contain this attr
