### ISSUE TITLE
Automate: bump `astro` version in `examples` with every release 

### ISSUE THREAD

**Issue by redwerkz** [withastro/astro#5809]
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

-

### What package manager are you using?

-

### What operating system are you using?

-

### Describe the Bug

This is not about a particular bug, but a more general issue with the release process.

In general the examples should represented the latest features & ux and exspecially when bugs get fixed there is a potential gap. And I noticed this because they are prominently linked in the docs for reference(!) 

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is already the case! Are you seeing an outdated version anywhere?

**Comment by redwerkz** [comment]
browser -> github.com/withastro/astro  --> releases       -> tag: latest       -> astro 1.9.1     😊
                                     \ \_ /examples/basic -> def: brnch: main  -> astro 2.0.0beta 🤔
                                      \__ #readme -> astr.new ->  brnch: latest-> astro 1.9.0     😯   


1. is like the baseline: you come to the repo and find some latest number of a release version
2. looking at the examples I get a newer unstable version?! -> you would not exspect this do you?
3. and a little bit more off it is when `astro.new`(!) doesnt serve what's promise to you

**Comment by Princesseuh** [comment]
The `main` branch is by definition unstable, it's where development happens (and where actual releases are cut from). So no, I wouldn't expect things to be stable there 😅

The examples on the `latest` branch are on `^1.9.0`, which will give the latest version automatically. `create-astro` and other tools also use the `latest` branch or the `latest` tag on npm, which also points to the stable version.

**Comment by natemoo-re** [comment]
I think the way we're doing it now makes sense, but maybe renaming `main` to `canary` might be a bit more clear? That's what Vercel uses on [`vercel/next.js`](https://github.com/vercel/next.js).

**Comment by redwerkz** [comment]
> The `main` branch is by definition unstable, it's where development happens (and where actual releases are cut from). So no, I wouldn't expect things to be stable there 😅

Yeah, you are totally right and it feels natural as long as I don't start thinking about it 😅 in the end it's an agreement which branching to use.

> I think the way we're doing it now makes sense, but maybe renaming `main` to `canary` might be a bit more clear? 

I guess this will create more confusion in comparison to all other astro related repos. Maybe just the CONTRIBUTING.md should have a sentence or two about this topic



The question that remains: Why are the examples via astro.new are outdated, e.g. "just the basics" is on astro 1.9.0, but 1.9.2 is already available

**Comment by natemoo-re** [comment]
I will update CONTRIBUTING.md to mention this, though. That's a good idea!
