### ISSUE TITLE
@astrojs/partytown cause "`Event.path` is deprecated and will be removed. Please use `Event.composedPath()` instead."

### ISSUE THREAD

**Issue by excelsior091224** [withastro/astro#5810]
### What version of `astro` are you using?

1.8.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I created a website with Astro and use Google Analytics with "@astrojs/partytown":"^1.0.2".
However, when I check with PageSpeed Insights, I get the following warning.
``Event.path` is deprecated and will be removed. Please use `Event.composedPath()` instead.`
<img width="721" alt="image" src="https://user-images.githubusercontent.com/44745901/211481953-28991abd-a8fc-43fc-b62b-8f45e2c20d0b.png">
From what I have found, on the Partytown side, this problem has been resolved in version 0.7.4.
https://github.com/BuilderIO/partytown/pull/328
However, when I checked the html in question (`/~partytown/partytown-sandbox-sw.html?1673332988582`), the Partytown loaded was 0.7.3.
<img width="412" alt="image" src="https://user-images.githubusercontent.com/44745901/211482406-e4c5edb5-a8b5-4508-9205-2ef2673c454c.png">
It is obvious that Partytown loaded by @astrojs/partytown is out of date.
Please improve it ASAP.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ee3up5?file=package.json,astro.config.mjs,src%2Fcomponents%2FBaseHead.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is an upstream issue at https://github.com/BuilderIO/partytown/issues/284 that's recently fixed but not released yet. Once it is, the integration should pick it up and not caused the warning.

**Comment by bluwy** [comment]
Uh wait I didn't read the issue description right as you've also mentioned that too. Since our deps declare `^0.7.1`, I think this isn't an issue nonetheless. You can run `npm update @builder.io/partytown` to bump the nested dependency.

**Comment by excelsior091224** [comment]
> You can run `npm update @builder.io/partytown` to bump the nested dependency.

It didn't works.
I run `npm update @builder.io/partytown` and `"node_modules/@builder.io/partytown"` in `package-lock.json` updated to "0.7.4".
https://github.com/excelsior091224/new_blog/commit/6fd58d8a147c3411a8c66b1af2a040511e928dbf
But PageSpeed Insights still warning, and partytown in `partytown-sandbox-sw.html` is "0.7.3".
<img width="718" alt="image" src="https://user-images.githubusercontent.com/44745901/211497178-6bcfcfd0-9cab-4907-8fea-dd6e3e39bed7.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/44745901/211497522-3481a42c-2ed7-4b5e-9899-8e5dbb4f0cd8.png">

**Comment by excelsior091224** [comment]
After `npm update`, partytown is updated to "0.7.4".
Thanks!
<img width="417" alt="image" src="https://user-images.githubusercontent.com/44745901/211508214-e955dd54-5f95-4262-b1cd-8eb719c43b87.png">
