### ISSUE TITLE
CSS Sourcemap Duplication of References in Dev

### ISSUE THREAD

**Issue by djmtype** [withastro/astro#5817]
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

This is part of an old closed issue that needs addressing since Astro 1.0.0-beta42. 
Original issue: https://github.com/withastro/astro/issues/3647

I thought it might work itself out with future Astro versions. Even with Astro 2 beta which utilizes Vite v4, the issue persists.

With CSS sourcemaps enabled, there is duplicate CSS being referenced from both the css file and page file. This can make debugging css extremely tedious. I thought maybe it was a Vite bug. After using Vite as standalone compiler and Sveltekit 1.0, that doesn't seem to be the case as there is no CSS sourcemap duplication with these libraries. 

```js
// astro.config.mjs
vite: {
    css: {
      devSourcemap: true,
    },
  },
```
![Screenshot 2023-01-10 at 11 45 47 AM](https://user-images.githubusercontent.com/930713/211612464-94c9785a-6869-432d-b15a-dfedbb3aceca.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-g7v2dq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by djmtype** [comment]
@natemoo-re I think you had an issue open for this already? Sorry, I couldn't find it at the time. Feel free to close then. I've experienced no other issues otherwise.

**Comment by gvkhna** [comment]
Can this be configured at the very least. I wouldn't care as much about a FOUC during dev, but not having source maps is a non-starter for anything greater than toys. All I'm seeing is `<style>` for every css entry in a largish project it's completely unworkable.

**Comment by gvkhna** [comment]
I've diagnosed the issue at least:

With this in my astro.config.mjs:
```
vite: {
    css: {
      devSourcemap: true,
    },
    server: {
      hmr: { overlay: false }
    }
  }
```

There's an issue with the matching of `el.innerHTML.trim()` between the `injectedStyles` Map and the Observer.

https://github.com/withastro/astro/blob/5fd9208d447f5ab8909a2188b6c2491a0debd49d/packages/astro/src/runtime/client/hmr.ts#L12

And here:

https://github.com/withastro/astro/blob/5fd9208d447f5ab8909a2188b6c2491a0debd49d/packages/astro/src/runtime/client/hmr.ts#L35

I did a diff between the values, and there are some odd differences between what should be the same files. It's possible extensions or something else is calling the values to be different.

A simple fix is to replace `el.innerHTML.trim()` with `el.innerHTML.substr(0,50)` which for obvious reasons isn't a great solution but has solved the problem for me. 

Looks like this would be have to be pushed upstream to the point where the style elements are injected (by Vite?) to add an `id` attribute that can be targeted better.

**Comment by natemoo-re** [comment]
Thanks for the investigation @gvkhna! With your help, I was able to track down what was going on here—looks like there were situations where the exact content didn't match and the duplicate styles weren't being handled properly.

I've opened https://github.com/withastro/astro/pull/5917 which should fix this!
