### ISSUE TITLE
Astro dev/build hangs when component exports arrow function type

### ISSUE THREAD

**Issue by duncanwerner** [withastro/astro#5818]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

WSL2/Ubuntu-20.04

### Describe the Bug

When I export an arrow function type from an astro component, both `astro dev` and `astro build` hang forever (node is running at 100%, so it seems like some sort of loop).

Component.astro:
```
---
// this is fine
export type NumberType = number;

// astro hangs because of this typedef. 
// comment it out and astro will work.
export type FuncType = (x: number) => number;

---
{new Date()}
```

I think this is new, because I hit it when I upgraded an old project. It worked without problems in (at least) Astro 1.5.2. 

### Link to Minimal Reproducible Example

https://github.com/duncanwerner/demo-astro-0123

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Marking this as a p3 since exporting types from Astro files is not something we recommend in general, but weird issue! I think @natemoo-re would be the one with the most context here

**Comment by natemoo-re** [comment]
Thanks! I'm looking into this now and will report back!
