### ISSUE TITLE
Astro ignores vite.envPrefix only during production build

### ISSUE THREAD

**Issue by JLarky** [withastro/astro#5827]
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

change your configuration to add `vite.envPrefix`:
```
export default defineConfig({vite: {
    envPrefix: 'VITE_',
}});
```

For both scripts `PUBLIC_P=1 VITE_P=2` was set in environment, both those values are accessible during SSR, but only one of them is going to be ignored on client (depending on the way you run it).

Running `npm run dev`:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/7026/211692156-3501f340-c65c-4457-9948-62d891003cd9.png">
Running `npm run build && npm run preview`:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/7026/211692186-077c512c-184c-4f0a-868d-3125572247b0.png">

My explanation is that it seems like Astro is ignoring `astro.vite` configuration during builds, but uses it during dev

### Link to Minimal Reproducible Example

https://github.com/JLarky/astro-env-prefix-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks!
