### ISSUE TITLE
got some errors when I used node 18

### ISSUE THREAD

**Issue by wulinsheng123** [withastro/astro#5830]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

I Got some errors when I used node 18

step1: 
cd `/workspace/astro/packages/integrations/node`
step2: pnpm run test
1) API routes
       Can get the request body:
     TypeError: Cannot read properties of undefined (reading 'toString')
      at Context.<anonymous> (file:///workspace/astro/packages/integrations/node/test/api-route.test.js:30:32)

  2) API routes
       Can get binary data:
     TypeError: Cannot read properties of undefined (reading 'buffer')
      at Context.<anonymous> (file:///workspace/astro/packages/integrations/node/test/api-route.test.js:47:43)

### Link to Minimal Reproducible Example

https://github.com/withastro/astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This works for me in local, make sure you have the latest changes of `main` and you ran a build before running the tests.

If it doesn't work, could you share more information about which version of Node 18 you're using?

**Comment by wulinsheng123** [comment]
it's bizarre.
I close first
