### ISSUE TITLE
Astro Build fail to build all component styles while using vuetify ?

### ISSUE THREAD

**Issue by geminigeek** [withastro/astro#5848]
### What version of `astro` are you using?

1.9.2

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

linux

### Describe the Bug

while using vuetify the dev mode works perfectly all styles works , but as i build the app the component styles are not working properly , i have a reproduction url.

https://stackblitz.com/edit/github-vjbdds-gf34pr?file=src/pages/_app.ts

just run npm run dev the buttons looks fine work fine

after building and running npm run preview the button looks messed up they function fine though?

any help on how to properly build ?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vjbdds-gf34pr?file=src/pages/_app.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by do-web** [comment]
I have the same issue, any workaround? I am using ssr with node and the styles are gone in the build.

**Comment by bluwy** [comment]
It looks like you need to use [vite-plugin-vuetify](https://www.npmjs.com/package/vite-plugin-vuetify) when using in Vite: https://stackblitz.com/edit/github-vjbdds-qmeixb?file=package.json,astro.config.mjs. You have to use the plugin like this though: https://stackoverflow.com/a/73515954/13265944

Closing as this is a Vuetify setup issue.

**Comment by jscottsf** [comment]
Same issue. Tried `vite-plugin-vuetify` but it states that the vue plugin must be loaded first? Will keep trying.

**Comment by RicardoDev1999** [comment]
it is not working for me, I am having the following error: 
![image](https://github.com/withastro/astro/assets/25202366/63459abc-34bb-4187-9164-56204d50a158)

**Comment by omerman** [comment]
Im getting - [Vuetify] Could not find injected layout
as if the v-layout is not set before the app-bar is used.. which is weird..


I did everything described above. can someone help?

@bluwy By any chance Do you have any idea what Im doing wrong here?




```
// astro.config.mjs

import { defineConfig } from 'astro/config';
import vue from '@astrojs/vue';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';
import partytown from '@astrojs/partytown';
import vuetifyPlugin from 'vite-plugin-vuetify';
import { fileURLToPath } from 'node:url';

// https://astro.build/config
export default defineConfig({
  outDir: '../../dist/apps/astro-test',
  integrations: [
    vue({
      appEntrypoint: '/src/pages/_app',
    }),
    vuetify(),
    tailwind({
      configFile: fileURLToPath(
        new URL('./tailwind.config.cjs', import.meta.url)
      ),
    }),
    sitemap(),
    partytown(),
  ],
});

/**
 * Vuetify integration for Astro
 * @param {import('astro/config').Options} options
 * @returns {import('astro/config').AstroIntegration}
 */
function vuetify(options) {
  return {
    name: 'my-astro-vuetify-integration',
    hooks: {
      'astro:config:setup': ({ updateConfig }) => {
        updateConfig({
          vite: {
            ssr: {
              noExternal: ['vuetify'],
            },
            plugins: [vuetifyPlugin()],
          },
        });
      },
    },
  };
}

```


```
//Layout.astro


---
import VueLayout from '../components/Layout.vue';
import AppBar from '../components/AppBar.vue';

interface Props {
  title: string;
}

const { title } = Astro.props;
---

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Astro description" />
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="generator" content={Astro.generator} />
    <title>{title}</title>
  </head>

  <body>
    <VueLayout>
      <AppBar />
      <slot />
    </VueLayout>
  </body>
</html>

```

```
//components/AppBar.vue

<template>
  <v-app-bar title="Application bar" />
</template>


```

```
// components/Layout.vue
<template>
  <v-layout>
    <slot></slot>
  </v-layout>
</template>
```

<img width="412" alt="image" src="https://github.com/withastro/astro/assets/6780529/dfa16820-61f5-498b-9ba7-f74d286ad6c3">
