### ISSUE TITLE
Cannot read properties of undefined (reading 'postcss')

### ISSUE THREAD

**Issue by jamestoot** [withastro/astro#5850]
### What version of `astro` are you using?

2.0.0-beta.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac/Linux

### Describe the Bug

When using tailwind on a new astro install (2.0.0-beta.2) you get the following error:

![image](https://user-images.githubusercontent.com/13592472/212351841-a5dbbb4c-d602-47f8-a3bb-dc6305f8e9ec.png)

 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mt8tbl?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! To use Tailwind with the beta version, you also need to install the beta version of the integration: `"@astrojs/tailwind": "^3.0.0-beta.1"`

In the future, we plan to make `astro add` recognize this situation better so it automatically installs the beta version of the integration if available. Sorry for the inconvenience in the meantime!
