### ISSUE TITLE
Missing `noImplicitAny` rule in "strict" tsconfig

### ISSUE THREAD

**Issue by ClementNerma** [withastro/astro#5861]
This is not a real bug as it doesn't affect runtime, but I feel like the strictest TypeScript configuration should enable a few rules by default: `noImplicitAny`, `noImplicitThis`, `noPropertyAccessFromIndexSignature`, `useUnknownInCatchVariables` and `strictPropertyInitialization`.

Affects latest version.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! All of those are part of `strict: true`, which the strictest preset has through its extend of the strict preset.

**Comment by ClementNerma** [comment]
Indeed! Apart from `noPropertyAccessFromIndexSignature`, these are all registered in `strict`. Thanks for pointing it out :)

**Comment by Princesseuh** [comment]
> Indeed! Apart from `noPropertyAccessFromIndexSignature`, these are all registered in `strict`. Thanks for pointing it out :)

Ah, yep! We could definitely add that one to the strictest preset. If you're interested in doing the PR for it, go ahead! Otherwise, I'll get to it on Monday

**Comment by ClementNerma** [comment]
I opened a PR at #5864
