### ISSUE TITLE
@astrojs/rss Filtering out draft posts not working with RSSFeedItem[] item type

### ISSUE THREAD

**Issue by satnaing** [withastro/astro#5865]
### What version of `astro` are you using?

1.9.2

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Excluding draft posts in RSS feed feature not working as expected when `items` is `RSSFeedItem[]` type. I think it is only working fine with `GlobResult` type.

I've been excluding draft posts by manually filtering like this.
```js
export const get = () =>
  rss({
    title: SITE.title,
    description: SITE.desc,
    site: SITE.website,
    items: posts
      .filter(({ frontmatter }) => !frontmatter.draft) // exclude draft posts
      .map(({ frontmatter }) => ({
        link: `posts/${slugify(frontmatter)}`,
        title: frontmatter.title,
        description: frontmatter.description,
        pubDate: new Date(frontmatter.datetime),
      })),
  });
```

After bumping `@astrojs/rss` to 2.0.0, the following code should filter out draft posts, but it doesn't.
```js
// astrojs/rss 2.0.0
export const get = () =>
  rss({
    title: SITE.title,
    description: SITE.desc,
    site: SITE.website,
    items: posts
      .map(({ frontmatter }) => ({
        link: `posts/${slugify(frontmatter)}`,
        title: frontmatter.title,
        description: frontmatter.description,
        pubDate: new Date(frontmatter.datetime),
        draft: frontmatter.draft,
      })),
  });
```

To reproduce the problem, you can clone [AstroPaper](https://github.com/satnaing/astro-paper) and test it.

### Link to Minimal Reproducible Example

https://github.com/satnaing/astro-paper/blob/main/src/pages/rss.xml.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
This should be resolved in Astro 2.0 with #5851! Give it a try by installing `astro@latest` and `@astrojs/rss@latest`.
