### ISSUE TITLE
Build fails when non-module JS-file is present in /pages

### ISSUE THREAD

**Issue by stephanbogner** [withastro/astro#5873]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Issue:
If I add a JS-file that is not a module (e.g. the [p5 JS library](https://p5js.org/download/)) somewhere in `/pages`, the build fails due to `Browser APIs are not available on the server.` (it fails even if the file is not used anywhere).

#### Example file `/src/pages/this-will-fail-the-build.js`:
Content: `console.log("Window width:", window.innerWidth)`

#### Error log:

```
> @example/blog@0.0.1 build
> astro build

10:40:52 PM [build] output target: static
10:40:52 PM [build] Collecting build info...
10:40:52 PM [build] Completed in 285ms.
10:40:52 PM [build] Building static entrypoints...
10:40:52 PM [build] Completed in 0.83s.

 generating static routes 
 error   window is not defined
  Hint:
    Browser APIs are not available on the server.
    
    If the code is in a framework component, try to access these objects after rendering using lifecycle methods or use a `client:only` directive to make the component exclusively run on the client.
    
    See https://docs.astro.build/en/guides/troubleshooting/#document-or-window-is-not-defined for more information.
    		
  Stacktrace:
ReferenceError: window is not defined
    at file:///home/stephan/Desktop/test/useful-group/dist/entry.mjs?time=1673883652966:2525:30
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

## Context:
[As I posted in Discord](https://discord.com/channels/830184174198718474/1064222276683321394/1064222276683321394) I have smaller experiments (written in plain HTML + JS + CSS) that I'd like to publicize.
I want to keep the files in `/src` because otherwise project files will be spread across `/public` and `/src` which would be hard to maintain.

## Ideal workflow:
I assumed files that are never imported are not part of the build process.

I intended to use [`is:inline`](https://docs.astro.build/en/reference/directives-reference/#isinline) to prevent them from affecting the build process, but their presence itself makes the build fail.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xhttxl?file=src%2Fpages%2Fthis-will-fail-the-build.js&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @stephanbogner!

Astro treats all files in `src/pages/` as a potential route/page, so even if not imported, Astro is trying to load `/src/pages/this-will-fail-the-build.js` and render it as an endpoint (more [about Endpoints in the docs](https://docs.astro.build/en/core-concepts/endpoints/)).

You can have Astro ignore files in `src/pages/` if you rename them (or the directory they’re in) to start with an underscore: `_`. (See [docs on excluding pages](https://docs.astro.build/en/core-concepts/routing/#excluding-pages).) However, if you’re not importing these files, they won’t be copied to your build output so for your case I’m afraid you would still need to use `src/public/` for these files that aren’t processed.

**Comment by stephanbogner** [comment]
@delucis Thanks for the quick clarification!

Technologically this makes sense. I hope that this approach changes in the future as it's much easier to structure projects if everything relevant is in one folder. (But honestly not sure what the best approach would be as it's a complicated topic).

For my project now I have to think of a workaround. Maybe I'll use _gulp_ to copy the stuff into `/public/something` (which I already do for images for a different but related reason).

**But just in general:** What I love about Astro (and also about HeadlessUI and TailwindCSS) is that it makes the annoying/complicated bits easy (e.g. build process/RSS/etc.), yet allows me to structure my project how I like. It has the right kind of abstraction / low-levelness :+1:
