### ISSUE TITLE
defineConfig don't allow async fns

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#5878]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

doesn't matter

### What operating system are you using?

doesn't matter

### Describe the Bug

in Vite, the `defineConfig` function allows either a config object, or a function or async function returning an object. this is extremely useful when dealing with async plugins, loading of X and Y files/assets. It'd be nice if Astro could follow the same convention/feature if the config function uses the same name.

Thank you

### Link to Minimal Reproducible Example

.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You can also use top-level await.

```js
const something = await foo()

export default defineConfig({
  site: something
})
```

So I'm not sure if we need this feature.

**Comment by y-nk** [comment]
@bluwy is astro running only on node versions supporting top-level await?

**Comment by bluwy** [comment]
Yes, `^14.18.0 || >=16.12.0` in the `package.json`. Top-level await is supported since Node.js 14.8

**Comment by y-nk** [comment]
thank you
