### ISSUE TITLE
Assets doesn't load 

### ISSUE THREAD

**Issue by Daniere-Mathieu** [withastro/astro#5881]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I make a portfolio with astro and after i build (no problem for build ) , my page cannot get the assets and i get lot of 404 in the console (for each file in assets) , but the file exist on dist/assets , so i try to make github page deployement to see if it's a problem from my computer and get the same errors do you know how to fix it ? (if you need to check the code the repo is here https://github.com/Daniere-Mathieu/Portfolio )

### Link to Minimal Reproducible Example

https://daniere-mathieu.github.io/Portfolio/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
In the linked example, an asset path defined like [`"/assets/svg/js.svg"`](https://github.com/Daniere-Mathieu/Portfolio/blob/befbcfa7b9e934b04482c4b6c3c8b92b9be5b560/src/const.ts#L10) is trying to load the image from the URL `https://daniere-mathieu.github.io/assets/svg/js.svg`, altho, the image is actually located at `https://daniere-mathieu.github.io/Portfolio/assets/svg/js.svg`.

If your `base` option in your `astro.config.mjs` is properly configured as described in the [GitHub Pages deployment guide](https://docs.astro.build/en/guides/deploy/github/#how-to-deploy), e.g. `base: '/Portfolio'`, you can then use the base to prefix static asset imports and URLs using [`import.meta.env.BASE_URL`](https://docs.astro.build/en/reference/configuration-reference/#base):

```ts
{ name: "Javascript", path: `${import.meta.env.BASE_URL}/assets/svg/js.svg` }
```

**Comment by Daniere-Mathieu** [comment]
Thanks for the help !
