### ISSUE TITLE
Astro.url.protocol returning http event when in https

### ISSUE THREAD

**Issue by GaspardCulis** [withastro/astro#5890]
### What version of `astro` are you using?

8.19.3

### Are you using an SSR adapter? If so, which one?

Node adapter, standalone

### What package manager are you using?

npm

### What operating system are you using?

Arch Linux btw

### Describe the Bug

In the --- ... --- zone (how do you call it ?) of an Astro page, I'm trying to access the current URL origin of my page using Astro.url.origin. It returns the good domain name, but prefixed with http, not https (I started my preview server with SERVER_KEY_PATH & SERVER_CERT_PATH env variables, https works fine in the browser). Same issue for Astro.url.protocol.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8d8wxa?file=src%2Fpages%2Findex.astro,package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
I believe you need to use the node adapter and have SSR enabled in your astro config

**Comment by MoustaphaDev** [comment]
@GaspardCulis I believe you need to use the node adapter and have SSR enabled in your astro config

**Comment by GaspardCulis** [comment]
I said in the issue I was using the node adapter, here is my config :

export default defineConfig({
	output: 'server',
	adapter: node({
		mode: 'standalone',
	}),
	vite: {
		optimizeDeps: {
			exclude: ['postgres'],
		},
	},
});

**Comment by MoustaphaDev** [comment]
> I said in the issue I was using the node adapter, here is my config :
> 
> export default defineConfig({ output: 'server', adapter: node({ mode: 'standalone', }), vite: { optimizeDeps: { exclude: ['postgres'], }, }, });

Ah I completely skipped it, I saw the repro didn't have it.

**Comment by MoustaphaDev** [comment]
Maybe try setting the vite config's `server.https` to `true`?

**Comment by GaspardCulis** [comment]
Haven't configured that on codeblitz sorry did it quick and dirty.
I changed my config:

export default defineConfig({
	output: 'server',
	adapter: node({
		mode: 'standalone',
	}),
	vite: {
		optimizeDeps: {
			exclude: ['postgres'],
		},
		server: {
			https: true,
		},
	},
});

I was sure this would solve my issue, but it didn't sadly. So might be a bug.

**Comment by rishi-raj-jain** [comment]
Yeah, I'm experiencing the same, hence switched to https://github.com/rishi-raj-jain/rishi.app/blob/master/src/pages/api/search.js#L4 checks.

**Comment by rishi-raj-jain** [comment]
Maybe we can do a config variable to set the protocol and hostname.

**Comment by GaspardCulis** [comment]
Yeah, I mean I found an alternative to know which protocol my website is using, I just reported this issue because it seems like a bug that could be fixed
