### ISSUE TITLE
Node builtins example doesn't work. Is there any way to read repo files at build time?

### ISSUE THREAD

**Issue by hurrymaplelad** [withastro/astro#5895]
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The [Node builtins API example](https://docs.astro.build/en/guides/imports/#node-builtins) does not work with `astro build` on Node due to the change in `import.meta.url` as reported in #5438.

In the repo example, using code copied from `docs.astro.build`, `astro dev` works as expected, showing the version from `package.json` while `astro build` fails with error `ENOENT: no such file or directory, open '/home/projects/package.json'`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jexi9q?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
You could have different paths for dev and production
```astro
---
...
const pkgJsonPath = import.meta.env.MODE === "development" ? '../../package.json' : '../package.json';

const url = new URL(pkgJsonPath, import.meta.url);
...
```

**Comment by MoustaphaDev** [comment]
@hurrymaplelad You could have different paths for dev and production
```jsx
---
const pkgJsonPath = import.meta.env.MODE === "development" ? '../../package.json' : '../package.json';

const url = new URL(pkgJsonPath, import.meta.url);
```

**Comment by matthewp** [comment]
The problem is it's not build-time if you are using SSR. The source files don't exist in that scenario. We probably do need to provide some safe-way to read files though, yes.

**Comment by hurrymaplelad** [comment]
Um should we maybe remove the broken example?
