### ISSUE TITLE
Imports are duplicated if script tag is placed above layout

### ISSUE THREAD

**Issue by IanVS** [withastro/astro#5907]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

I noticed in the `<head>` of our page during dev, that the astro-generated imports of modules were duplicated.  I've traced this down to only happening when the page includes a `<script>` tag _above_ the layout markup.  If I move it below, it is not duplicated.  

@matthewp helped to troubleshoot this in Discord.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-eshbkk?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is because the compiler is inserting a `maybeRenderHead()` for hoisted scripts when it should not be.
