### ISSUE TITLE
Code component breaks build when using PNPM

### ISSUE THREAD

**Issue by sean-au** [withastro/astro#5912]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm v7.2.0 node.js 19.2.0

### What operating system are you using?

Windows

### Describe the Bug

After running pnpm astro create@latest

adding 

`import { Code } from 'astro/components';`

and 

<Code code={`const foo = 'bar';`} lang="js" />  (both lines taken from the docs)

to pages/index.astro

On running `pnpm astro build` (or `npm astro build`) i get the following error

```
PS C:\github\astro-bootstrap\build-test> pnpm astro build

> @example/basics@0.0.1 astro C:\github\astro-bootstrap\build-test
> astro "build"

10:25:09 pm [build] output target: static
10:25:09 pm [build] Collecting build info...
10:25:09 pm [build] Completed in 13ms.
10:25:09 pm [build] Building static entrypoints...
10:25:15 pm [build] Completed in 5.80s.

 generating static routes 
 error   Cannot find package 'shiki' imported from C:\github\astro-bootstrap\build-test\dist\entry.mjs
  Did you mean to import shiki@0.11.1/node_modules/shiki/dist/index.js?
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'shiki' imported from C:\github\astro-bootstrap\build-test\dist\entry.mjs
Did you mean to import shiki@0.11.1/node_modules/shiki/dist/index.js?
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:823:9)
    at moduleResolve (node:internal/modules/esm/resolve:872:20)
    at defaultResolve (node:internal/modules/esm/resolve:1087:11)
    at nextResolve (node:internal/modules/esm/loader:161:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:831:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:413:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
 ELIFECYCLE  Command failed with exit code 1.
```

Stackblitz link below works as I assume its using npm.

Here is a link to the same minimal example with PNPM 
https://github.com/powerfulweb-dev/build-test

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nolt4t?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by findlay-best-wishes** [comment]
Probably, [non-flat node_moduels](https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory) cause the problem

**Comment by sean-au** [comment]
Thanks for the help.
Is there a way that astro can be modified so that everything works out of the box?

**Comment by sean-au** [comment]
I have tried adding either of the two options into a .npmrc file in the root of the project, and neither solve the dependency issue :(

**Comment by findlay-best-wishes** [comment]
> I have tried adding either of the two options into a .npmrc file in the root of the project, and neither solve the dependency issue :(

I m ok.

1.add the config
2.rm `node_modules`
3.run `pnpm install`
4.run `pnpm build`

**Comment by bluwy** [comment]
The issue likely comes from 

https://github.com/withastro/astro/blob/f27bb3d79f9774f01037e60e656b1f9d8e03367d/packages/astro/src/core/build/vite-plugin-internals.ts#L14

I tried to remove it, which successfully bundles `shiki`, but it then has runtime issues with `require is not defined` error. Using https://github.com/unjs/shiki-es might fix this issue but I haven't got that fully working from a quick change.

**Comment by matthewp** [comment]
This sounds like something we can't fix at the moment, so closing the issue.

**Comment by 0xJem** [comment]
As an FYI, I encountered this issue using PNPM and the Code component, but receive this error message:
>  No grammar provided for <text.html.markdown.jsx>

(Partially posting it here so that anyone with the same error message can find it!)

The fix to the docs noted in this PR enabled a workaround: https://github.com/withastro/docs/pull/2503
