### ISSUE TITLE
build/dev fail to run if user had a ' at the end of his name

### ISSUE THREAD

**Issue by pewpewded** [withastro/astro#5913]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

My build/dev failed to run on my windows desktop and the error was "Unterminated string literal index.astro" but worked fine on my Mac/Linux (gh-pages), it took me a good time of investigating till I suspected my user name, and right I was. User name was (Khalil') and changing users fixed it. I did reproduce the issue with another name ending with a ' before opening the issue.

### Link to Minimal Reproducible Example

/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! If you have the time, it'd be great if you could try on both the latest version of Astro (1.9.2) and the latest beta (2.0.0-beta.3) to see if this still happens as we've recently merged a fix for a similar issue.

**Comment by pewpewded** [comment]
just tried with Astro (1.9.2), issue still persists.

A user ending with an apostrophe

![1](https://user-images.githubusercontent.com/118110192/213673200-6f719f85-b4de-4405-9b4b-76067a29d6af.png)

Moved the project to public user and re-ran

![2](https://user-images.githubusercontent.com/118110192/213673220-7ea452cd-53b8-43da-8b45-10869dc074f6.png)

**Comment by Princesseuh** [comment]
And what about using the latest beta? 😄

**Comment by pewpewded** [comment]
issue seems to be fixed on the latest beta version 👍🏻

![sc](https://user-images.githubusercontent.com/118110192/213676081-503bf092-6fdf-4f10-890c-c78fa2335e83.png)

**Comment by pewpewded** [comment]
> And what about using the latest beta? 😄

I was on it, I just wanted to give a quick update 😅

**Comment by Princesseuh** [comment]
> issue seems to be fixed on the latest beta version 👍🏻

Sweet, thank you! I'll close this issue, the beta should be out soon enough. Sorry for the inconvenience in the meantime!

**Comment by pewpewded** [comment]
> > issue seems to be fixed on the latest beta version 👍🏻
> 
> Sweet, thank you! I'll close this issue, the beta should be out soon enough. Sorry for the inconvenience in the meantime!

no worries, keep up the good work y'all ^^
