### ISSUE TITLE
"Top-level return cannot be used inside an ECMAScript module"

### ISSUE THREAD

**Issue by jyasskin** [withastro/astro#5922]
### What version of `astro` are you using?

1.9.2

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I'm getting a "Top-level return cannot be used inside an ECMAScript module" error. When trying to reduce the error, it appears to go away once I simplify the surrounding code enough, so I suspect it's caused by the presence of another error. However, that means the real error is replaced by this incorrect one, which makes it hard to fix the other error. See the stackblitz below for the complex reproduction.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hz21xe?file=src/pages/[...crawl_date].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jyasskin** [comment]
And, in fact, this one was caused by an underlying error on the `await` inside the page template. So the bug isn't that the page should work, but that it should show the right error.

**Comment by mathiasmagnusson** [comment]
I get this error from the following code:

```
return new Response(null, {
    status = 401,
});
```

When running node, I get this error (which should probably be the same in this case):

```
Uncaught SyntaxError: Invalid shorthand property initializer
```
