### ISSUE TITLE
Image Integration does not work

### ISSUE THREAD

**Issue by Yoha485** [withastro/astro#5928]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm 

### What operating system are you using?

Windows

### Describe the Bug

I'm trying to use Astro Image Integration the same way as written in docs but it do not seems to work.
![image](https://user-images.githubusercontent.com/51025357/213886100-b22e3d00-aa64-47ed-9850-ec21584ba9cf.png)
![image](https://user-images.githubusercontent.com/51025357/213886120-78cbe953-004a-4942-aebd-10fb5b8fd597.png)

And if I import it another way: 
![image](https://user-images.githubusercontent.com/51025357/213886180-77102a2b-1443-4b09-a905-20fc8483f2a1.png)
![image](https://user-images.githubusercontent.com/51025357/213886186-bde527a9-83c0-4976-8c5b-1f6552a255dc.png)

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
I believe you need to specify the entire url of the image (i.e `http://localhost:PORT/social.png`)

**Comment by Yoha485** [comment]
Unfortunately, that did not help

**Comment by rishi-raj-jain** [comment]
Hey, I think that'd require a relative path for it to work.

**Comment by MoustaphaDev** [comment]
> Unfortunately, that did not help

I can take a look if you have a reproduction

**Comment by robpc** [comment]
I noticed this problem too. For me, adding the `/public` to the front solved it, so in your case that would be `import socialImage from "/public/social.png"`. If you use a string instead it works as you expect it to `<Image src="/social.png" ... />`, which is confusing. Before I imported the `@astrojs/image` package, the import you have would work for me (ie without `/public`) and afterward it did not.

**Comment by Xyrai** [comment]
Like @robpc mentioned, your path is incorrect. You have multiple options of using the Image component.

One is by using the src directly, like how you normally would e.g.
`<Image src="/astronaut.jpg" width={1280} aspectRatio="16:9" alt="descriptive text" />`

You could also put the image into an assets folder outside of public and import it from there instead, however I would recommend only doing this if you want to transform the image beforehand. If not, feel free to put them into the public folder.

The format prop mentioned above is **not** a requirement.

Feel free to have a look into the defined types:
```ts
export interface ImageComponentRemoteImageProps extends TransformOptions, ImgHTMLAttributes {
	src: string;
	/** Defines an alternative text description of the image. Set to an empty string (alt="") if the image is not a key part of the content (it's decoration or a tracking pixel). */
	alt: string;
	format?: OutputFormat;
	width: number;
	height: number;
}
```

```ts
export declare type OutputFormatSupportsAlpha = 'avif' | 'png' | 'webp';
export declare type OutputFormat = OutputFormatSupportsAlpha | 'jpeg' | 'jpg';
```

**Comment by robpc** [comment]
I think the part that makes this unexpected is that it changes the way images are imported. Even ignoring the `<Image />` component. 

If you create a `empty project` in Astro without the image integration, you can use a file at `/public/assets/cat.jpg` like the below or in [this test repo](https://github.com/robpc/astrojs-image-test/tree/6fb9207a92dcbe2d3dbf5dbb5243e5a69740fbd4).

```astro
---
import cat from '/assets/cat.jpg';
---

<html lang="en">
	<head><!--...--></head>
	<body>
		<h1>Astro</h1>
		<img src={cat} width={200} />
		<img src="/assets/cat.jpg" width={200} />
	</body>
</html>
```

Having run through the tutorial, and reading through the documentation my impression was you needed to drop the `/public`. It was only in testing this that it became apparent that either path works normally for both imports or strings.

<img width="762" alt="astro-image-test-01" src="https://user-images.githubusercontent.com/3671561/214758974-2026007d-a639-4488-b6cd-0cb003fd0bef.png">

But if you add the `@astrojs/image` integration using `npx add image` and the other documented changes in [this commit](https://github.com/robpc/astrojs-image-test/commit/8c3a3383dc0a2200ac83a4bc2ee4eba5ea0d5159), you get the error below. So one needs to update the import url to `/public/assets/cat.png`, but only in the one case and not the other. 

<img width="765" alt="astro-image-test-02" src="https://user-images.githubusercontent.com/3671561/214760435-ee0c9e60-a801-48f0-b2d0-d6ccd0b5e0cf.png">


The "head" of this repo has the [fixed changes](https://github.com/robpc/astrojs-image-test/commit/3ae083f502e33697b93fe7f0294b6b6af2d5d381).
```astro
---
import cat from '/public/assets/cat.jpg';
---

<html lang="en">
	<head><!--...--></head>
	<body>
		<h1>Astro</h1>
		<img src={cat.src} width={200} />
		<img src="/assets/cat.jpg" width={200} />
	</body>
</html>
```

To an outsider it is not even apparent we are interacting with the integration at all and there is no note in the documentation I can find. I think ideally it would act the same as without the integration, but if it is a necessary change, a note in the documentation would be nice. Right now [the documentation](https://docs.astro.build/en/guides/integrations-guide/image/#src) only gives an example for the string src case.

>For images located in your public directory: use the URL path relative to the public directory. (e.g. src="/images/public-image.jpg")

**Comment by HundredPercentCoverage** [comment]
I'm having this problem too. My images are in `/public/images`. I reference them in the frontmatter of my markdown files as e.g. `/images/placeholder-hero.jpg`, [as per the docs](https://docs.astro.build/en/guides/integrations-guide/image/#src), which is then fed into the image component in a `BlogPost.astro` layout file. When I use the component without a `format` attribute, which I shouldn't need to [according to the docs](https://docs.astro.build/en/guides/integrations-guide/image/#format) as it's not a 'remote' image, I get the error:

```
Unknown image output: "undefined" used for /images/placeholder-hero.jpg
```

If I add a `format` attribute, it's fine. Either the implementation could do with being tweaked, or the docs.

**Comment by Princesseuh** [comment]
> I'm having this problem too. My images are in `/public/images`. I reference them in the frontmatter of my markdown files as e.g. `/images/placeholder-hero.jpg`, [as per the docs](https://docs.astro.build/en/guides/integrations-guide/image/#src), which is then fed into the image component in a `BlogPost.astro` layout file. When I use the component without a `format` attribute, which I shouldn't need to [according to the docs](https://docs.astro.build/en/guides/integrations-guide/image/#format) as it's not a 'remote' image, I get the error:
> 
> ```
> Unknown image output: "undefined" used for /images/placeholder-hero.jpg
> ```
> 
> If I add a `format` attribute, it's fine. Either the implementation could do with being tweaked, or the docs. 

Hello, I admit that it's super confusing right now, this is definitely something we're working to fix, but an image in public is actually considered to be a remote image. A local image refers to images that are imported through an ESM import.

Next week we're hoping to publish our plan for the core integration of the image component, which will explain the steps we're taking to make using images easier and should fix this issue.

I'm sorry for the inconvenience in the meantime 😅

**Comment by Princesseuh** [comment]
Hello! The requirement of `format` has been added to the docs. I've additionally created an issue on the docs repo asking for the ESM shape being different to be documented: https://github.com/withastro/docs/issues/2586

The previously mentioned proposal has been also posted: https://github.com/withastro/roadmap/discussions/468. We'll be taking multiple steps making this clearer, from better types, better error messages and better documentation to generally more intuitive behaviour. 

Thank you everyone for commenting on this issue, we definitely appreciate your feedback!

**Comment by BertoRamosM** [comment]
This problem its still persisting for me a year later

**Comment by Rebooting-Me** [comment]
I had the same problem but once I relocated the images to a folder(_I named it "assets"_) present in the root directory and then referenced it _(relatively of course)_, the issue with png images was resolved.

**Comment by Julibe** [comment]
I suggest you check your Node.js version and use the LTS version, as the newer releases have compatibility issues with Astro.

**Comment by tjklemz** [comment]
Can confirm that switching to the LTS version of Node fixes this issue. (Bizarre.) Running the default blog template of Astro, no changes.

**Comment by reecenward** [comment]
maybe if its in a folder inside the public folder than use a slash if it can't find it like "/filename/image.png"
