### ISSUE TITLE
throwing errors in dev kills dev-server

### ISSUE THREAD

**Issue by juliusmarminge** [withastro/astro#5931]
### What version of `astro` are you using?

1.9.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When throwing errors in dev, the server kills itself making it almost impossible to develop with a good experience:

![image](https://user-images.githubusercontent.com/51714798/213895049-4b92d2b6-ba56-49c8-83aa-d6976f76a559.png)

To put some context to this, the error is coming from this snippet - a fetch request which comes back with unauthorized: ([See source here](https://github.com/t3-oss/create-t3-app/blob/2c09e6323ed23ed93b1fe005952f12113981c634/www/src/components/landingPage/tweets/tweets.astro#L25))

```ts
  return await fetch(url, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })
    .then((res) => {
      if (res.ok) {
        return res.json();
      } else {
        console.error(res);
        throw new Error("Failed to fetch tweets"); // <-- error here
      }
    })
    .then((res) => {
```

However, I can't seem to reproduce this on [a minimal setup](https://github.com/juliusmarminge/error-dev) - I tried a bunch of stuff in order to get the error, including placing the Astro project in a monorepo as is the case for the site where the original error is from.

To reproduce the error:

1. clone [create-t3-app](https://github.com/t3-oss/create-t3-app) and install deps using `pnpm i` **NOTE: We're not on 1.9.2 but error happens no matter what Astro version. My local branch is using 1.9.2 which you can see from the error message below too**
3. create a file `www/.env` and add the token `TWITTER_BEARER_TOKEN=some-unauthed-token`
4. start the dev-server using `pnpm dev:www` or `pnpm --filter www dev` ti run with and without turbo respectively (error happens on both)
5. open the site and your app should crash, including the server.

The same steps on the [more minimal setup](https://github.com/juliusmarminge/error-dev) doesn't kill the server, but instead the error shows in the browser (which is a LOOOOT better and how it should be). For reference, this is how it looks side by side in the terminal:

![image](https://user-images.githubusercontent.com/51714798/213895200-15f5c669-916b-4613-b0b6-a038cdd0c9e3.png)

Not sure why this is, might try adding more stuff and seeing when / if I can make the minimal example break too...

### Link to Minimal Reproducible Example

https://github.com/t3-oss/create-t3-app (sorry, not minimal)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Do you have a `catch`? This might just be the default Node.js behavior where uncaught exceptions crash the process.

**Comment by juliusmarminge** [comment]
> Do you have a `catch`? This might just be the default Node.js behavior where uncaught exceptions crash the process.

Do you mean like `try-catch`? No - I want the error to error out in prod but in dev i expect there to just be an overlay in the browser. This is the line throwing the error: https://github.com/t3-oss/create-t3-app/blob/81a08b3a3ef957abb7cfbbd20cadf7aa6f1e19fa/www/src/components/landingPage/tweets/tweets.astro#L25

**Comment by wulinsheng123** [comment]
I downloaded your project and checked it.
But it's challenging to find out why it will kill the server.
There are many other factors to affect it.
Could you please duplicate it again? Thanks a lot

**Comment by wulinsheng123** [comment]
![image](https://user-images.githubusercontent.com/27261522/216760931-37624b7f-a158-4395-9503-f0722abbc919.png)
![image](https://user-images.githubusercontent.com/27261522/216760935-6c256a97-3e36-4503-af73-e0e64c691201.png)

I did but nothing happen

**Comment by matthewp** [comment]
I spent some time here but also could not recreate. If you're still having the issue please create a stackblitz with https://astro.new/ and file a new issue. THanks!
