### ISSUE TITLE
img tag src with @astrojs/image doesn't work in certain circumstances

### ISSUE THREAD

**Issue by gvkhna** [withastro/astro#5934]
### What version of `astro` are you using?

1.9.2

### Are you using an SSR adapter? If so, which one?

Deno? Or SSG? I believe it's not affected by adapter.

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Simply adding astrojs/image to a project doesn't correctly render <img tags in certain circumstances.

For example:

```
import {MyImage} from '@images/myimage.png'

<img src={MyImage} alt="" />
```

In output for dev/build is turned into 

```
<img src="[object Object]" alt="">
```

It does seem like static img paths are not affected (`<img src="myimage.jpg` ..), this has something to do with resolving the import url and the astrojs/image plugin possibly in vite-plugin-astro-image.js

After extensive tracing I was able to narrow down the scenario in more detail that may help with a fix.

https://github.com/withastro/astro/blob/02ba7c2250a950593961d833201e46adb3e0873c/packages/astro/src/vite-plugin-astro/compile.ts#L37

Here you can add `console.log(esbuildResult)` and you'll see the following:

```
addAttribute as $$addAttribute

<img${$$addAttribute(MyImage, "src")} alt="img
```

Tracing this through to here:

https://github.com/withastro/astro/blob/37cb2fc02a03754d454b243579bc55e55cf72904/packages/astro/src/runtime/server/render/util.ts#L52

Where `key` is `src` and `value` is:

```
{
  src: '/assets/img-02.9ece27da.png',
  width: 95,
  height: 100,
  format: 'png'
}
```

I believe the issue here is that `value` is an object, through my tracing most other values are strings. `value` is generated from the `metadata` function in astrojs/image. As for how it gets there I'm not sure.

This Object is being sent from somewhere as part of astrojs/image I believe. But it's unclear exactly where at this point.

Here's a sample stack trace:

```
  at addAttribute (file:///home/~/dist/entry.mjs?time=1674364337555:1470:13)
    at AstroComponentInstance.factory (file:///~/dist/entry.mjs?time=1674364337555:3530:23)
    at AstroComponentInstance.init (file:///~dist/entry.mjs?time=1674364337555:994:29)
    at AstroComponentInstance.render (file:///~dist/entry.mjs?time=1674364337555:999:18)
    at render.next (<anonymous>)
    at renderChild (file:///~dist/entry.mjs?time=1674364337555:1058:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async [Symbol.asyncIterator] (file:///~/subhunt/dist/entry.mjs?time=1674364337555:428:7)
    at async renderAstroTemplateResult (file:///~/dist/entry.mjs?time=1674364337555:436:20)
    at async renderChild (file:///~/dist/entry.mjs?time=1674364337555:1055:5)
    at async renderSlot (file:///~/dist/entry.mjs?time=1674364337555:1084:22)
    at async renderChild (file:///~/dist/entry.mjs?time=1674364337555:1038:11)
    at async [Symbol.asyncIterator] (file:///~/dist/entry.mjs?time=1674364337555:428:7)
    at async renderAstroTemplateResult (file:///~/dist/entry.mjs?time=1674364337555:436:20)
    at async renderChild (file:///~dist/entry.mjs?time=1674364337555:1055:5)
    at async AstroComponentInstance.render (file:///~/dist/entry.mjs?time=1674364337555:1008:7)
    at async renderChild (file:///~/dist/entry.mjs?time=1674364337555:1058:5)
    at async [Symbol.asyncIterator] (file:///~/dist/entry.mjs?time=1674364337555:428:7)
    at async renderAstroTemplateResult (file:///~node_modules/.pnpm/astro@1.9.2/node_modules/astro/dist/runtime/server/render/astro/render-template.js:40:20)
    at async read (file:///~/node_modules/.pnpm/astro@1.9.2/node_modules/astro/dist/runtime/server/render/page.js:104:32)
```

Hopefully this is an easy fix!

I apologize but my repro is not correct, I am not able to upload an image to repro this correctly on stackblitz. 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
This is how the image integration transforms image imports from [this file]

**Comment by MoustaphaDev** [comment]
This is how the image integration transforms imported images, it's done by [this vite plugin](https://github.com/withastro/astro/blob/20e60c6e0857f7b6938494df6027e8c1ad74cdc1/packages/integrations/image/src/vite-plugin-astro-image.ts#L20) and this is the 9resulting interface of the image module](https://github.com/withastro/astro/blob/20e60c6e0857f7b6938494df6027e8c1ad74cdc1/packages/integrations/image/src/vite-plugin-astro-image.ts#L13)

**Comment by gvkhna** [comment]
> I believe this is expected, that's is how the image integration transforms imported images, it's done by [this vite plugin](https://github.com/withastro/astro/blob/20e60c6e0857f7b6938494df6027e8c1ad74cdc1/packages/integrations/image/src/vite-plugin-astro-image.ts#L20) and this is the [resulting interface of the image module](https://github.com/withastro/astro/blob/20e60c6e0857f7b6938494df6027e8c1ad74cdc1/packages/integrations/image/src/vite-plugin-astro-image.ts#L13) To get the `src` of you image I think you'd need to access the `.src` of the imported image
> 
> ```js
> ---
> import {MyImage} from '@images/myimage.png'
> ---
> <img src={MyImage.src} alt="" />
> ```

This makes sense but it’s definitely a bit of a pain. I guess we could add a note in the docs. 

But I’m wondering if there’s a better way to do it, I believe the renderer should detect it’s an object and unwrap/handle it instead of simply printing out “[object Object]”. 

I’ll maybe look into it more but seems low priority if there’s such an easy workaround. An error versus current state would also be very nice.

**Comment by gvkhna** [comment]
Can confirm `MyImage.src` works but with typescript gives the following error too `Property 'src' does not exist on type 'string'`. So this is clearly doing something incorrect. I could propose a fix but I'm hoping a maintainer of astro/image can weigh in on how that should be done.

I want to look into this more anyway because astro/image isn't supported by deno yet which doesn't make a lot of sense to me and it's something I'll look into fixing as well.

**Comment by Princesseuh** [comment]
The TypeScript error happens because you didn't update the type reference in your env.d
ts: https://docs.astro.build/en/guides/integrations-guide/image/#update-envdts

In the future, we're hoping to add the image integration as a core feature, so that step wouldn't be needed

**Comment by gvkhna** [comment]
I guess that's a reasonable solution in which case this could possibly be closed. Moving it into core could help with the missing types. 

Incidentally it's still not working for me in vscode after restarts with the added compilerOptions but that's probably something else.

**Comment by gvkhna** [comment]
May I suggest the following strategy that is valid ECMA, should be able to handle either situation without having to specify `src` on specific imports, and is more conducive to passing metadata.

Using query params in imports is valid ECMA. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta

https://github.com/withastro/astro/commit/7e66c74d7df4a79b3144d1946233af3b4f9cd6a4

https://github.com/withastro/astro/commit/aaf70f400c4283ce1ba182bbe08ccaebf2f64b61

**Comment by gvkhna** [comment]
Here's a cleaned up/working/minimal PR. Hopefully a good starting point.

https://github.com/withastro/astro/pull/5950

**Comment by Princesseuh** [comment]
Created an issue on the docs asking for this to be documented better: <https://github.com/withastro/docs/issues/2586>

We're currently in the process of investigating the core integration for images, which will make the situation clearer by not needing manual interventions for types, see the proposal here: https://github.com/withastro/roadmap/discussions/468
