### ISSUE TITLE
"base" option in combination with "trailingSlash: 'never'" leads to wrong URI for partytown

### ISSUE THREAD

**Issue by AleVul** [withastro/astro#5935]
### What version of `astro` are you using?

1.9.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

linux

### Describe the Bug

when configuring astro with `base: '/blog'` and `trailingSlash: 'never'` - generated url for partytown script is "/blog~partytown".

The build step also logs the following: (!) `"base" option should end with a slash.`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-npvowd?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
@AleVul I think this was fixed in https://github.com/withastro/astro/commit/4266869f4fef37fadb2e0c4c0b703decde11037a

**Comment by rishi-raj-jain** [comment]
Ah but that's an old one now
