### ISSUE TITLE
`Astro.headers.set()` method not saving/setting cookie.

### ISSUE THREAD

**Issue by jareer12** [withastro/astro#5938]
### What version of `astro` are you using?

^1.9.0

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

The `Astro.cookies.set()` method is not saving its value.

```js
Astro.cookies.set(
  "auth_token",
 "Ms52B9FQaxtY2t8mO1odIPWjo39cEW035FTSDaUITjmdehjf0AADkmvkGbvnvtO0mP54rBZtir3OZ6oKTWiJYaZLfdmBO2KSUbE8MR6h24JKtHUwFQZQlD2Jb6F68WLVo1A5tvQ8MbPEEksfPeQ1ZHxwZ2S3ABJdza233JfS84wXEBe4i7Y0h64dLlhMhibmQfJfWm2WY5OnUPkeuAHPl5I7SzYzwpkiVDZQH7ESsGzLVs8BY2KJKopMROSwfc55"
);

const auth_token = Astro.cookies.get("auth_token").value; // Null if I don't use the .set() method above.
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-s8inzd?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
What do you mean by not saving it's value?

**Comment by jareer12** [comment]
> What do you mean by not saving it's value?

The cookie is not being saved.

**Comment by rishi-raj-jain** [comment]
if running it inside a server, you could probably maintain a global variable for the all ops.

**Comment by MoustaphaDev** [comment]
@jareer12 Make sure you have the [node adapter](https://docs.astro.build/en/guides/integrations-guide/node/) and have the [output target](https://docs.astro.build/en/reference/configuration-reference/#output) to `server`.

Also letting you know that `Astro.cookies` only works in astro pages (i.e astro files inside the `/pages` directory)
See the [warning below the linked heading](https://docs.astro.build/en/guides/server-side-rendering/#astrorequestheaders)

**Comment by jareer12** [comment]
> @jareer12 Make sure you have the [node adapter](https://docs.astro.build/en/guides/integrations-guide/node/) and have the [output target](https://docs.astro.build/en/reference/configuration-reference/#output) to `server`.
> 
> Also letting you know that `Astro.cookies` only works in astro pages (i.e astro files inside the `/pages` directory) See the [warning below the linked heading](https://docs.astro.build/en/guides/server-side-rendering/#astrorequestheaders)

Yes, I'm calling the set cookie method in a .astro file. 

My config file:
```js
import { defineConfig } from "astro/config";

// https://astro.build/config
import tailwind from "@astrojs/tailwind";

// https://astro.build/config
import compress from "astro-compress";

// https://github.com/RafidMuhymin/astro-imagetools#readme
import { astroImageTools } from "astro-imagetools";

// import astroI18next from "astro-i18next";
import astroI18next from "astro-i18next";

// Astro Node.js adapter
import node from "@astrojs/node";

// https://astro.build/config
import react from "@astrojs/react";

// Import vue bitch
import vue from "@astrojs/vue";

// https://astro.build/config

// https://astro.build/config
export default defineConfig({
  output: "server",
  adapter: node({
    mode: "middleware",
  }),
  integrations: [
    vue({ jsx: true }),
    react(),
    tailwind(),
    compress(),
    astroI18next(),
    astroImageTools,
  ],
});
```

**Comment by MoustaphaDev** [comment]
Sorry if I'm repeating myself, but is the astro file you're calling the `cookies.set` method in an astro component or layout? This shouldn't work in both cases, it only works in astro pages.

Just trying to narrow down the cause of the issue.

**Comment by jareer12** [comment]
> 

I get it now, it's a component file and is not in the `pages` dir.
