### ISSUE TITLE
When run `npm run buid` with @astrojs/image or astro-imagetools the dist/server/entry.mjs not working

### ISSUE THREAD

**Issue by newathnow** [withastro/astro#5940]
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

SSR NODE

### What package manager are you using?

NPM

### What operating system are you using?

Mac

### Describe the Bug

Hey guys will appreciate if someone faced with this problem or i am doing something wrong. 

So i have tested the astro-imagetools and @astrojs/image 

And seems like in the docs is written i need to use Img 
```astro
---
import { Img } from "astro-imagetools/components";
---

<Img src="https://picsum.photos/1024/768" alt="A random image" />
```

i am taking my src from aws from url also this below working perfectly : 
```js
 {all.map((post) => (
                <Img src={link+post.cover+"?quality=80"}  alt={post.title}/>
      ))}
```
Problem comes when i run npm run build and try to run ╰─○ node dist/server/entry.mjs
server not showing me the content in the body tag(its empty), but if i dont use image libs its working perfect. 

Any suggestions or what i am doing wrong ?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-j8s3qs?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
I don't know about astro-image-tools but with the official image integration, the `src`, `alt`, `format`, `width` and `height` (or one of the last two and `aspectRatio`) props are required
[See](https://docs.astro.build/en/guides/integrations-guide/image/#image-)

**Comment by newathnow** [comment]
is lazy load can be used as attribute and work ? 

cause i am checking blurha.sh integration cause the website will be heavily filled with images  and need optimal solution for this

**Comment by newathnow** [comment]
> I don't know about astro-image-tools but with the official image integration, the `src`, `alt`, `format`, `width` and `height` (or one of the last two and `aspectRatio`) props are required for remote images [See](https://docs.astro.build/en/guides/integrations-guide/image/#image-)

is lazy load can be used as attribute and work ?

cause i am checking blurha.sh integration cause the website will be heavily filled with images and need optimal solution for this

**Comment by newathnow** [comment]
> > I don't know about astro-image-tools but with the official image integration, the `src`, `alt`, `format`, `width` and `height` (or one of the last two and `aspectRatio`) props are required for remote images [See](https://docs.astro.build/en/guides/integrations-guide/image/#image-)
> 
> is lazy load can be used as attribute and work ?
> 
> cause i am checking blurha.sh integration cause the website will be heavily filled with images and need optimal solution for this



When i try use picture it return me this: 
<picture>
	<source type="image/avif" srcset="/_image?f=avif&amp;w=400&amp;h=400&amp;ar=1&amp;href=https%3A%2F%2Fdev.domain.com%2Fassets%2Fd8a28ca4-6c74-4386-9d23-f1706ba564a4 400w,/_image?f=avif&amp;w=800&amp;h=800&amp;ar=1&amp;href=https%3A%2F%2Fdev.domain.com%2Fassets%2Fd8a28ca4-6c74-4386-9d23-f1706ba564a4 800w,/_image?f=avif&amp;w=1200&amp;h=1200&amp;ar=1&amp;href=https%3A%2F%2Fdev.domain.com%2Fassets%2Fd8a28ca4-6c74-4386-9d23-f1706ba564a4 1200w"><source type="image/webp" srcset="/_image?f=webp&amp;w=400&amp;h=400&amp;ar=1&amp;href=https%3A%2F%2Fdev.domain.com%2Fassets%2Fd8a28ca4-6c74-4386-9d23-f1706ba564a4 400w,/_image?f=webp&amp;w=800&amp;h=800&amp;ar=1&amp;href=https%3A%2F%2Fdev.domain.com%2Fassets%2Fd8a28ca4-6c74-4386-9d23-f1706ba564a4 800w,/_image?f=webp&amp;w=1200&amp;h=1200&amp;ar=1&amp;href=https%3A%2F%2Fdev.domain.com%2Fassets%2Fd8a28ca4-6c74-4386-9d23-f1706ba564a4 1200w">
	<img src="/_image?f=webp&amp;w=1200&amp;h=1200&amp;ar=1&amp;href=https%3A%2F%2Fdev.domain.com%2Fassets%2Fd8a28ca4-6c74-4386-9d23-f1706ba564a4" loading="lazy" decoding="async" alt="My Title ">
</picture>

no idea why it mixing the src like that

**Comment by newathnow** [comment]
ok i found the issue ;)
