### ISSUE TITLE
tsconfg undefined

### ISSUE THREAD

**Issue by felipe300** [withastro/astro#5960]
### What version of `astro` are you using?

2.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### Describe the Bug

I just create an Astro project with the new release 2.0 and it create a `tsconfig.json` file with this: 
`{ "extends": "astro/tsconfigs/undefined", }`, when i use `pnpm dev` or `pnpm run dev` i got this error: `TSConfckParseError
An error occurred.` `failed to resolve "extends":"astro/tsconfigs/undefined" in .../ASTRO/astro-2.0-content-collection/tsconfig.json`. But when i reload the page the page error goes away, but it doesn't change my file

I'm using pnpm 7.25.0

### Link to Minimal Reproducible Example

https://stackblitz.com/github/felipe300/astro-2.0?file=tsconfig.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @felipe300! Thanks for reporting. This should be fixed in 2.0.1 could you try re-running the `create astro` command?

Or just to fix up the `tsconfig` you can update this manually:

```json
{
  "extends": "astro/tsconfigs/base"
}
```

**Comment by matthewp** [comment]
Thank you! You were quick to find this. Luckily we found it around the same time and fixed it here: https://github.com/withastro/astro/pull/5958

**Comment by felipe300** [comment]
> Hi @felipe300! Thanks for reporting. This should be fixed in 2.0.1 could you try re-running the `create astro` command?
> 
> Or just to fix up the `tsconfig` you can update this manually:
> 
> ```json
> {
>   "extends": "astro/tsconfigs/base"
> }
> ```

I just did that! Thanks

**Comment by thomas-callahan-collibra** [comment]
Thanks for the quick fix! I had just started trying Astro for the first time this morning and ran into this.
