### ISSUE TITLE
Content Collections can't load `config.ts` file when there are spaces in the folder tree

### ISSUE THREAD

**Issue by MoustaphaDev** [withastro/astro#5961]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Ubuntu 22.04

### Describe the Bug

When there are spaces in the folder tree leading to the config file loaded by the content collections API, loading the config file fails

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-moeeyn?file=package.json&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
PR in flight: https://github.com/withastro/astro/pull/5962
