### ISSUE TITLE
Astro 2.0 + TailwindCSS error after update to Astro 2.0

### ISSUE THREAD

**Issue by linuxmobile** [withastro/astro#5964]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I already update to the new version and try to run `pnpm run dev`
![image](https://user-images.githubusercontent.com/10554636/214401497-91aad619-bc34-429f-9f46-8da3218c0fd1.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/github/linuxmobile/linews/tree/dev/?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! It seems like your Tailwind integration is out of date. The 3.0.0 version of it is required to use Astro 2.0.0.

Let me know if updating fix the issue for you!

**Comment by linuxmobile** [comment]
Fixed installing  @astro/tailwindcss manually.

**Comment by linuxmobile** [comment]
> Hello! It seems like your Tailwind integration is out of date. The 3.0.0 version of it is required to use Astro 2.0.0.
> 
> Let me know if updating fix the issue for you!

Yeah. Thats right. It's fixed now. Sorry for open an issue

**Comment by stefanrows** [comment]
Same here. After updating to Astro 2.0 I go the same exact error. 

I went ahead and run `npx astro add tailwind` after upgrading to Astro 2.0 and recognized that I now have two different versions of Tailwind present in the `package.json`:

```
{
  "name": "@example/minimal",
  "type": "module",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/netlify": "^1.3.0",
    "@astrojs/prism": "^1.0.2",
    "@astrojs/sitemap": "^1.0.0",
    "@astrojs/tailwind": "^2.1.3",
    "astro": "^2.0.2",
    "netlify-cli": "^12.7.2",
    "tailwindcss": "^3.2.4"
  }
}
```

Would be good to somehow address this because I am sure that this issue will come up for many people.

**Comment by linuxmobile** [comment]
> Same here. After updating to Astro 2.0 I go the same exact error.
> 
> I went ahead and run `npx astro add tailwind` after upgrading to Astro 2.0 and recognized that I now have two different versions of Tailwind present in the `package.json`:
> 
> ```
> {
>   "name": "@example/minimal",
>   "type": "module",
>   "version": "0.0.1",
>   "private": true,
>   "scripts": {
>     "dev": "astro dev",
>     "start": "astro dev",
>     "build": "astro build",
>     "preview": "astro preview",
>     "astro": "astro"
>   },
>   "dependencies": {
>     "@astrojs/netlify": "^1.3.0",
>     "@astrojs/prism": "^1.0.2",
>     "@astrojs/sitemap": "^1.0.0",
>     "@astrojs/tailwind": "^2.1.3",
>     "astro": "^2.0.2",
>     "netlify-cli": "^12.7.2",
>     "tailwindcss": "^3.2.4"
>   }
> }
> ```
> 
> Would be good to somehow address this because I am sure that this issue will come up for many people.

Try installing manually `@astrojs/tailwind@latest`
