### ISSUE TITLE
@astrojs/image: wrong type definition 

### ISSUE THREAD

**Issue by fabon-f** [withastro/astro#5979]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

In the [document](https://github.com/withastro/docs/blob/27d7c272a79d10af07f365b177f3610182513c8d/src/pages/en/guides/integrations-guide/image.mdx), `background` option is optional. But in the type definition, `background` prop is described as required.

https://github.com/withastro/astro/blob/03e374f6bcbe7dc51f0cbcf4cfd15f00bac799be/packages/integrations/image/components/index.ts#L50

Because of this, running `astro check` emits type error: `Property 'background' is missing in type '...' but required in type 'PictureComponentRemoteImageProps'`.

I think this is not the problem of doc, but the problem of type definition. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9fxoes?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jaular** [comment]
Same error with astro@2.0.1 and astrojs/image@0.13.0

**Comment by wulinsheng123** [comment]
mark
