### ISSUE TITLE
💡 RFC: Give better feedback when you try to interact with a static rendered component

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#598]
### Motivation

- Sometimes, when I click a button/component on my page it doesn't work
- Sometimes, this is because I didn't add a `:load` handler to the component
- This almost always feels like Astro is broken, but Astro is actually doing the right thing
- Even more importantly, "opt-in" JS is a core idea in Astro.

/cc @matthewp @natemoo-re 

### Proposed Solution

1. During dev: add a click event handler to every non-Astro UI component, warning that the component is not hydrated and isn't expected to work. Would need to handle inputs/buttons/form elements.
2. During dev: add a "inspector mode" / "xray mode" that adds CSS bprders around your islands, grey for static and green for hydrated.

I'm a little more in favor of 2. but we could honestly do both! Curious to hear other solutions as well.

### Detailed Design

TODO.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by MatsDahlin** [comment]
I would also favor something in the lines of proposed solution no 2. It feels more direct, and there's also a possibility that a component that needs hydration is not dependant on user input to work, and in those cases solution no 1 wouldn't be as discoverable. 

I started playing around with a naive solution to this just to poke around the code a bit, but i'm not sure how to check if dev server is being used or if Astro is building production build.
Looking forward to see how you implement this so I can learn :)

Also, solution no 2 got me started thinking about Astro having built-in dev tools for this kind of thing. I really like how projects like react-query have their dev tools integrated in the library instead of being a browser add-on. Not sure what else would fit in there right now for Astro though.

**Comment by FredKSchott** [comment]
Excited to try out that branch! I'm a bit worried that "x-ray mode" would be too hidden, but we could combine some of the same idea as 1. to have a grey border kind of flash for a second when you click a static Astro component. Or something like that

**Comment by jasikpark** [comment]
The only problem would be elements that aren't meant to be made interactive by astro, but another means, like a form that `POST`s to `/submit`

**Comment by MatsDahlin** [comment]
Hackig around with some of these ideas in https://github.com/snowpackjs/astro/pull/801

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
