### ISSUE TITLE
[Build prod]  js assets outside of assets

### ISSUE THREAD

**Issue by ampmonteiro** [withastro/astro#5982]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux (Ubuntu 20.04.1)

### Describe the Bug

I am using vue for client side js.

When build to prod i notice that js files are outside of assets, when should be inside of assets folder.

in version 2.0, i notice an  _astro folder is created but either way like css files js files also should be inside an assets folder.

Even if public > assets folder doesnt exist, in build for prod should be created an assets folder by default and by default any css and js files should be inside of this folder.

standalone Vite js project has the behavior, where all css and js file were inside of assets folder when build for prod.

Note: the link to minimal reproduction example,   it is not from the project i am building. But just build any project with client side js would be enough to do a reproduction of the issue.

![image](https://user-images.githubusercontent.com/31895754/214658078-7e116b54-deb9-41e2-9607-044dace8d5cd.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-vue?file=README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I notice that you put `1.6.0` as the Astro version you're using, but this behavior has changed in `2.0.0` as you mentioned. 

In `2.0.0`, `_astro` _is_ the assets folder. Are you wanting it to be named `assets` or suggesting something else? The exact name of the directory is customizable using the [`assets`](https://docs.astro.build/en/reference/configuration-reference/#buildassets) config option, but many hosts will automatically cache files inside of `_astro`.

**Comment by ampmonteiro** [comment]
@natemoo-re 

yes, that is right, the version i am using is prior 2.x.

I mention the version 2, because only today see the release and try it with one of yours templates with vue.

here print of json file:

![image](https://user-images.githubusercontent.com/31895754/214670078-34cc867d-c2f5-4d2b-9011-3d589f1d37f7.png)

**Comment by natemoo-re** [comment]
Assets in `public/` are copied to the root `dist/` directory, not the `_astro/` directory.

Since this issue is about the behavior in Astro 1.6.0, there's not much we can do. The behavior has changed in Astro 2.0.0. If you run into issues with the new Astro 2.0.0 behavior, feel free to open another issue.
