### ISSUE TITLE
script in Astro component not run in mdx loaded with content collection with dev command

### ISSUE THREAD

**Issue by malcolm-kee** [withastro/astro#5987]
### What version of `astro` are you using?

2.0.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Code in `<script>` tag inside Astro component is not run when running `astro dev` when the Astro component is embedded in mdx loaded via content collection.

The code runs when I run `astro build` then `astro preview`.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/malcolm-kee/astro-content-script-bug

1. Run `pnpm run dev`
2. Go to `/my-post` path. Verify that the h1 content is "Example Comp with script", which means the code in `script` tag which overwrite the text is not running.
3. Run `pnpm run build && pnpm run preview`
4. Go to `my-post` path. Verify that the h1 content is now "Script is run!", which means the code in `script` tag runs.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jessegood** [comment]
I believe this is the same as https://github.com/withastro/astro/issues/5991

**Comment by matthewp** [comment]
It is, closing this one as Ben is already working on https://github.com/withastro/astro/issues/5991 .
