### ISSUE TITLE
Cannot resolve aliased module from `src/content/config.ts`

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#5990]
### What version of `astro` are you using?

2.0.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a module `src/data.ts` and `tsconfig.json` configured to resolve aliased names:

```json
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": ["src/*"]
  }
}
```

I'm able to import `~/data` just fine from pages and other files, but not from `src/content/config.ts`. I get the error `Cannot find module '~/data' imported from '.../src/content/config.ts'`.

It all works however if I use relative import `../data` instead of the path alias.

### Link to Minimal Reproducible Example

no yet

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@bholmesdev I'm pretty sure this is because the config is loaded with its own fresh Vite dev server. We could just add the alias plugin to that server which would fix this case, but I'm thinking people will just find other missing features.

What was the reason for this needing to load in its own server and not use the existing Vite dev server?

**Comment by bholmesdev** [comment]
@matthewp Good question! We load your config so we can parse frontmatter with Zod at build-time, rather than shipping Zod and parse logic to your server runtime. This naturally has consequences like broken aliases though. I'm curious if we can parse your config with our complete `create-vite` config, or if this could be a perf bottleneck?

**Comment by matthewp** [comment]
What I'm thinking is that in dev mode there's already a `viteServer` that's configured with `create-vite`. So we can just use that. During the build and in sync we could create one.

**Comment by wulinsheng123** [comment]
> @bholmesdev I'm pretty sure this is because the config is loaded with its own fresh Vite dev server. We could just add the alias plugin to that server which would fix this case, but I'm thinking people will just find other missing features.
> 
> What was the reason for this needing to load in its own server and not use the existing Vite dev server?

Can I fix it by modifying `vite-plugin-config-alias` because I don't need to add the alias plugin to that server?
I'm afraid I will have some trouble if I have done, which will find other missing features

**Comment by wulinsheng123** [comment]
I tried the last version of the Astro, and everything is fine 😂

**Comment by wulinsheng123** [comment]
> @wulinsheng123 Yeah, I don't think that modification would do it. I'm leaning towards @matthewp's suggestion to use our complete vite config loading our content config in dev, and replicate it in production. Planning to work on a fix with core there!

![image](https://user-images.githubusercontent.com/27261522/215944009-4c214dd1-32a9-46e4-9a39-27a48de1ab8f.png)
![image](https://user-images.githubusercontent.com/27261522/215944061-0ddd5aaa-390e-4866-8544-7e04eb21ae25.png)


I tried with the last version of the Astro and everything was fine suddenly.

**Comment by shishkin** [comment]
In `2.0.4` typescript indeed seems fine with the aliased import. However, `astro check` fails in presence of the aliased import:

```
astro check
 error   `astro sync` command failed to generate content collection types.
  Hint:
    Check your `src/content/config.*` file for typos.
  File:
    /.../node_modules/astro/dist/cli/sync/index.js:27:11
  Code:
    26 |   } catch (e) {
    > 27 |     throw new AstroError(AstroErrorData.GenerateContentTypesError);
         |           ^
      28 |   }
      29 |   info(logging, "content", `Types generated ${dim(getTimeStat(timerStart, performance.now()))}`);
      30 |   await setUpEnvTs({ settings, logging, fs });
  Stacktrace:
GenerateContentTypesError: `astro sync` command failed to generate content collection types.
    at sync (file:///.../node_modules/astro/dist/cli/sync/index.js:27:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async check (file:///.../node_modules/astro/dist/cli/check/index.js:12:19)
    at async runCommand (file:///.../node_modules/astro/dist/cli/index.js:160:19)
    at async cli (file:///.../node_modules/astro/dist/cli/index.js:180:5)
```
