### ISSUE TITLE
[Build prod] files in public folder not into _astro folder

### ISSUE THREAD

**Issue by ampmonteiro** [withastro/astro#5994]
### What version of `astro` are you using?

2.0.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux (Ubuntu 20.04.1)

### Describe the Bug

In sequence of https://github.com/withastro/astro/issues/5982 issue,  The files the are in public should be also inside of _astro folder.

All assets related should be centralized into _astro folder, even if they are not optimized by astro.

This can be tested with any of yours templates.

![214675158-4229cf4a-a966-4de5-86c3-1fbdbf911254](https://user-images.githubusercontent.com/31895754/214918631-c9191c38-34df-4b83-b651-efb99165b65f.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
The `_astro` file is only for files that Astro builds, like component styles and scripts. Putting `public/` files in `_astro` would make them not accessible from the expected path in the browser.

**Comment by ampmonteiro** [comment]
I find out a solution,  that was similar to what i did when using vite only.

In this case in public folder create also an _astro folder and at build prod time all will be merge.
