### ISSUE TITLE
Upgrading astro, astro-storyblok, and netlify adapter results in build error in Netlify (SSR)

### ISSUE THREAD

**Issue by SandraRodgers** [withastro/astro#5996]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I updated my project to Astro 2.0. I'm using the netlify adapter for SSR. The dependencies have also been updated:

```
"dependencies": {
    "@astrojs/netlify": "^2.0.0",
    "@astrojs/tailwind": "^3.0.0",
    "@storyblok/astro": "^2.0.5",
    "astro": "^2.0.1",
    "tailwindcss": "^3.2.4"
  }
```
For netlify builds, Netlify is running Node v16.19.0. 

When I run it locally, the site builds fine. In storyblok I can edit and publish and see the updates, both the visual editor and on my localhost. 

Previously, it would build fine when I pushed to main (before I upgraded to Astro 2.0)

Now, when I push my updated project to main, the netlify deployment happens. It builds the site, but results in an error. 

Attaching screenshot of error and build logs where related warning happens

<img width="853" alt="Screen Shot 2023-01-26 at 12 33 06 PM" src="https://user-images.githubusercontent.com/45321563/214935963-a703270e-2073-45bf-8f78-a370e7ba366b.png">

<img width="1195" alt="Screen Shot 2023-01-26 at 1 52 07 PM" src="https://user-images.githubusercontent.com/45321563/214936360-53d7e6a3-e283-4b67-9fc9-444aef6cd874.png">

### Link to Minimal Reproducible Example

https://github.com/SandraRodgers/astro-storyblok-example

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@Princesseuh when we removed Node 14 support did was stop shimming `fetch` and `Headers` globals? We might need to bring that back if so, since we document using things like `new Headers()` in code.

**Comment by Princesseuh** [comment]
> @Princesseuh when we removed Node 14 support did was stop shimming `fetch` and `Headers` globals? We might need to bring that back if so, since we document using things like `new Headers()` in code.

No, we still provide those through undici. https://github.com/withastro/astro/blob/main/packages/webapi/src/ponyfill.ts#L74-L78

**Comment by natemoo-re** [comment]
Yeah I looked into this a bit and nothing obvious jumped out, `webapi` was the first place I looked and it all looked OK to me.

**Comment by matthewp** [comment]
The polyfill is applied here: https://github.com/withastro/astro/blob/main/packages/integrations/netlify/src/netlify-functions.ts#L6

I could be a bundling issue where the code using `Headers` happens at the module scope and it higher in the bundled file than the shimming happens. If that's the case then we need to massage the bundling order so that the shimming happens first.

But it could also be caused by something else.

**Comment by philr35** [comment]
Also having this issue, same setup as @SandraRodgers
