### ISSUE TITLE
@astrojs/image Picture duplicates alt attribute

### ISSUE THREAD

**Issue by jordisala1991** [withastro/astro#6003]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When using Astro image with Picture element the alt attribute gets duplicated on the output html:

```
import { Picture } from '@astrojs/image/components';
```

```
        <Picture
            src={import(`../assets/blog/${post.data.image.path}.png`)}
            widths={[400]}
            width={362}
            height={204}
            sizes="100vw"
            alt={post.data.image.alt}
        />
```

It doesn't happen with the `<Image>` tag tho.

### Link to Minimal Reproducible Example

Will provide soon

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Fixed by https://github.com/withastro/astro/commit/460f9e7329482429172883e99dcee95a3a9fb1a5
