### ISSUE TITLE
Using prerender on Dynamic Route with SSR

### ISSUE THREAD

**Issue by thomasledoux1** [withastro/astro#6007]
### What version of `astro` are you using?

2.0.1

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm currently using an SSR adapter (Vercel) for my website, but I want to prerender some parts now for even better performance(?). 
This works fine when I added the `export const prerender = true` on a "normal" `.astro` file.
But when I try to add this to a dynamic route (/blog/[...slug].astro in my case), I get the following error:

```
 error   `getStaticPaths()` function is required for dynamic routes. Make sure that you `export` a `getStaticPaths` function from your dynamic route.
  Hint:
    See https://docs.astro.build/en/core-concepts/routing/#dynamic-routes for more information on dynamic routes.
    
    Alternatively, set `output: "server"` in your Astro config file to switch to a non-static server build. This error can also occur if using `export const prerender = true;`.
    See https://docs.astro.build/en/guides/server-side-rendering/ for more information on non-static rendering.
  File:
    src/pages/blog/[...slug].astro
```

Is this the expected behaviour? Shouldn't it be possible to opt in to prerendering dynamic routes too while using SSR?
Sorry for not providing a StackBlitz/CSB example, they're both now working along today..

### Link to Minimal Reproducible Example

https://github.com/thomasledoux1/website-thomas-astro/tree/feature/use-prerender

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by AirBorne04** [comment]
You can pretender dynamic routes but therefore you need to define the possible routes, that is what the mentioned 'getStaticPaths' function is for.

**Comment by rishi-raj-jain** [comment]
https://github.com/thomasledoux1/website-thomas-astro/blob/feature/use-prerender/src/pages/blog/%5B...slug%5D.astro needs to have a getStaticPaths. More on this error:
https://docs.astro.build/en/reference/errors/get-static-paths-required/

**Comment by thomasledoux1** [comment]
Hi, I got it working by adding `getStaticPaths` indeed. I tried this before the 2.x version, and didn't seem to work then. Thanks for the clarification!

**Comment by dsomel21** [comment]
If you have added an `export function getStaticPaths() {}` and **it's still failing** make sure that you don't have an extra `[id].astro` file lying around in your folders.
