### ISSUE TITLE
Astro/Images integration breaks: pnpm run build

### ISSUE THREAD

**Issue by felipe300** [withastro/astro#6009]
### What version of `astro` are you using?

2.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### Describe the Bug

I set this project with astro1.9 but when i update to astro2.0 its breaks when i use `pnpm run build` it breaks. This is the error:

` error   Cannot destructure property 'buildConfig' of 'undefined' as it is undefined.
  File:
    /home/pipo/astro2/node_modules/.pnpm/@astrojs+image@0.12.1_sharp@0.31.3/node_modules/@astrojs/image/dist/index.js:66:31
  Code:
    65 |       },
    > 66 |       "astro:build:start": ({ buildConfig }) => {
         |                               ^
      67 |         var _a;
      68 |         const adapterName = (_a = _config.adapter) == null ? void 0 : _a.name;
      69 |         if (adapterName && UNSUPPORTED_ADAPTERS.has(adapterName)) {
`

An this are my dependencies: 
`  "dependencies": {
    "@astrojs/image": "^0.12.2-beta.0",
    "@astrojs/rss": "^2.0.0",
    "@astrojs/sitemap": "^1.0.0",
    "astro": "^2.0.0-beta.3",
    "astro-icon": "^0.8.0",
    "postcss": "^8.4.21",
    "postcss-preset-env": "^7.8.3",
    "sharp": "^0.31.3"
  }`

in order to make it work, i had to remove the astro integration with Images

### Link to Minimal Reproducible Example

https://stackblitz.com/github/felipe300/astro-codingInPublic?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your `@astrojs/image` integration is outdated. Please upgrade to `0.13.0`

**Comment by felipe300** [comment]
Thanks

**Comment by eosfelipe** [comment]
Gracias!!

**Comment by eosfelipe** [comment]
> Your `@astrojs/image` integration is outdated. Please upgrade to `0.13.0`

Gracias!!

**Comment by ReyWins** [comment]
I am actually having this issue again. I am using the latest @astro/image 12.1 version.
