### ISSUE TITLE
`@astro/vercel` causes error with render function

### ISSUE THREAD

**Issue by jacobthesheep** [withastro/astro#6012]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

After updating my site to Astro 2.0 and implementing the new Content Collections API by following the docs and the [blog template](https://astro.new/blog?on=stackblitz), I ran into an error message saying `post.render is not a function`, and after some digging, I discovered that if I removed the vercel integration, the error would go away. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-oe3kkp?file=README.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jmn** [comment]
Setting "output" to "server" in `astro.config.mjs` also causes the error with the blog demo

![bild](https://user-images.githubusercontent.com/35616/215265372-7fb9b5cf-9a19-4365-b0bf-26366354f67f.png)

**Comment by jmn** [comment]
I found this in the documentation: https://docs.astro.build/en/core-concepts/routing/#modifying-the-slug-example-for-ssr

And modified `[...slug.astro]` to look like this:
```astro
---
import { CollectionEntry, getCollection } from 'astro:content';
import BlogPost from '../../layouts/BlogPost.astro';

const posts = await getCollection('blog');
type Props = CollectionEntry<'blog'>;

const { slug } = Astro.params;
const post = posts.find((page) => page.slug === slug);
if (!post) return Astro.redirect("/404");
const { Content } = await post.render();
---

<BlogPost {...post.data}>
	<h1>{post.data.title}</h1>
	<Content />
</BlogPost>
```

Which solved the problem.

**Comment by jacobthesheep** [comment]
Thanks @jmn that fixed it for me.

**Comment by Ibinola** [comment]
Thanks @jmn this fixed it for me

**Comment by leodeslf** [comment]
For me it was enough to just change the adapter to SSG as I don't need the "dynamic" part of SSR to build a blog-like site. (Not sure if this fits your needs).

```js
// astro.config.mjs:

import { defineConfig } from 'astro/config';
// import vercel from '@astrojs/vercel/serverless'; // --
import vercel from '@astrojs/vercel/static';        // ++
 
export default defineConfig({
  // output: 'server', // --
  output: 'static',    // ++
  adapter: vercel(),
});
```

Notice `@astro/vercel` did not cause the error itself. See more at (Astro docs) [@astrojs/vercel - Targets](https://docs.astro.build/en/guides/integrations-guide/vercel/#targets) or (Vercel docs) [Astro on Vercel - Edit your config](https://vercel.com/docs/frameworks/astro#edit-your-config).

**Comment by BharatCoder9** [comment]
Thanks @jmn 
Just to add, if you are using typescript, you should do the following imports instead:

```
import type { CollectionEntry } from 'astro:content'
import { getCollection } from 'astro:content';
```

**Comment by jweboy** [comment]
Thanks @jmn this fixed it for me
