### ISSUE TITLE
Circular imports evaluated twice client-side?

### ISSUE THREAD

**Issue by benoitv-code** [withastro/astro#6014]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

Node Standalone

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I wanted to use a SolidJS context provider for a component also rendered client-side (with `client:load`).

I noticed that my first approach was failing to get the proper context value, apparently due to a circular import in my component, resulting the in context initialization code [^1] being run twice client-side, hence resolving into different symbols when used in my `ContextProvider` and `SimpleDiv` components (instead of resolving into the same symbol as I was expecting).

The behavior is correct during SSR, but incorrect during CSR.

Moving the context initialization code [^1] to a separate file (imported by both the `ContextProvider` and `SimpleDiv` components solves the issue.

See the console output (by opening the dev tools) from this [reproduction example on Stackblitz](https://stackblitz.com/edit/github-cbhyay-u2rz7y):

```
// Output for ./src/components/without-bug/
[SSR][Good] createContext() call
[SSR][Good] Language: fr

[CSR][Good] createContext() call
[CSR][Good] Language: fr

// Output for ./src/components/with-bug/
[SSR][Bad] createContext() call
[SSR][Bad] Language: fr

[CSR][Bad] createContext() call
[CSR][Bad] createContext() call
[CSR][Bad] Language: en
```

It shows:
- The `createContext()` call (incorrectly?) being done twice client-side when using the `./src/components/with-bug/` components, resulting in the incorrect context being used.
- The `createContext()` call (correctly?) being done once client-side when using the `./src/components/without-bug/` components, resulting in the correct context being used.

I am not sure if it's an expected behavior from the ESM module imports resolution (in this case, sorry for the bug report), or a Vite limitation, or an Astro/SolidJS limitation.

[^1]: Context initialization code: `export const ApplicationContext = createContext([{ lng: 'en' }, {}]);`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cbhyay-u2rz7y

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Here's an updated reproduction: https://stackblitz.com/edit/github-cbhyay-ckd5ko?file=src%2Fpages%2Findex.astro

The problem seems to be related to us loading the island as a `/@fs/...` module. What happens is:

- ContextProvider is loaded with `/@fs/...`
- SimpleDiv loaded as `/src/...`
- ContextProvider loaded as `/src/...`

I think loading the island with the `/src/...` prefix would fix this. ccing @bluwy as he's worked in this area before.
