### ISSUE TITLE
Reading .env using `dotenv` in astro config causes private envs to be `undefined` in API endpoints

### ISSUE THREAD

**Issue by ni554n** [withastro/astro#6025]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I stumbled upon this issue when one of my API endpoint broke out of nowhere due to missing env values.
I traced it back to the change I did on _astro.config.mjs_ where I had started reading an env variable using `dotenv`.
After that change, private envs are nowhere to be found in `.dist/_worker.js` after an `astro build`.

I observed **_all_** envs will be there as expected if
- endpoints are running on `astro dev`, and
- envs are prefixed using `PUBLIC_`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-pqrurd?file=astro.config.mjs,.env,src%2Fpages%2Fapi.ts,src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
As a workaround you can use the [`loadEnv`](https://vitejs.dev/guide/api-javascript.html#loadenv) function from vite to use environment variables in your config file

**Comment by matthewp** [comment]
Thanks for the explanation @MoustaphaDev. I agree, this is expected behavior and `loadEnv` is a good choice inside of Astro config.

**Comment by ni554n** [comment]
Then we should replace the `dotenv` recommendation with `loadEnv` in the [doc](https://docs.astro.build/en/guides/configuring-astro/#referencing-relative-files:~:text=We%20recommend%20alternatives%20like%20dotenv%20or%20fast%2Dglob%20for%20these%20respective%20use%20cases.).

**Comment by matthewp** [comment]
Yes, I think that sounds reasonable.
