### ISSUE TITLE
rehype-autolink-headings not working

### ISSUE THREAD

**Issue by kkettinger** [withastro/astro#6026]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Adding `rehype-autolink-headings` does not create clickable anchor heading links:
![grafik](https://user-images.githubusercontent.com/83078716/215355672-490432b9-e31d-4dc7-8792-e5d4a313b94f.png)

Steps to reproduce issue:
```
npm create astro@latest
npm install rehype-autolink-headings
```

`astro.config.mjs`:
```
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';

import sitemap from '@astrojs/sitemap';

import rehypeAutolinkHeadings from 'rehype-autolink-headings';

// https://astro.build/config
export default defineConfig({
	site: 'https://example.com',
	integrations: [mdx(), sitemap()],
	markdown: {
		rehypePlugins: [
			rehypeAutolinkHeadings
		]
	}
});

```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rns4dd-sqvx9n

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
`rehype-autolink-headings` only work for headings with an `id` attribute. Since in markdown they don't have an `id` by default, you need to use the `rehype-slug` plugin too to get it to work.

```js
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import rehypeSlug from 'rehype-slug'
import rehypeAutolinkHeadings from 'rehype-autolink-headings';

// https://astro.build/config
export default defineConfig({
	site: 'https://example.com',
	integrations: [mdx(), sitemap()],
	markdown: {
		rehypePlugins: [
			rehypeSlug,
			rehypeAutolinkHeadings
		]
	}
});
```

**Comment by kkettinger** [comment]
> 

Doesn't seem to work: https://stackblitz.com/edit/github-rns4dd-yauoou

**Comment by bluwy** [comment]
It's working for me. It doesn't work for some h1 because it is rendered like:

```html
<!-- src/pages/blog/[..slug].astro -->

<BlogPost {...post.data}>
	<h1>{post.data.title}</h1>
	<Content />
</BlogPost>
```

<img width="388" alt="image" src="https://user-images.githubusercontent.com/34116392/215431840-dbc3b471-2402-4375-b483-d8dcc0304975.png">

**Comment by kkettinger** [comment]
Ah sorry, you were right, i have looked at the wrong headings. Thank you for your help!
