### ISSUE TITLE
Astro Starter Kit: Blog - About Page Broken

### ISSUE THREAD

**Issue by JS-GitRepo** [withastro/astro#6030]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

yarn

### What operating system are you using?

Windows 10

### Describe the Bug

I am new to Astro, but I noticed that the "About" page on the official blog example is not displaying images or other information from the markdown file's frontmatter.

The raw text is displayed, but the title, description, updated date, and heroImage are not appearing. It's as if any javascript in the BlogPost layout is being ignored for about.md? 

I started Astro with v2.0 but I'm assuming this broke recently? I noticed the BlogPost layout that "about.md" uses is setup fo the "blog" collection (which to my understanding are new in 2.0) and I'm wondering if this broke the linking to .md pages (that aren't in a collection / the collection listed in BlogPost)?

An example is attached but here is another as well:
https://astro-test-js.netlify.app/

### Link to Minimal Reproducible Example

https://codesandbox.io/s/github/withastro/astro/tree/latest/examples/blog

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Looks like we need to refactor the `BlogPost.astro` component a bit to fix the about page.

**Comment by bholmesdev** [comment]
Good catch @JS-GitRepo! Yes, we refactored the Blog Layout to play nicely with content collections, but forgot to check that pages using the `layout` property (`about.md`) still correctly handles props. We'll update this 👍
