### ISSUE TITLE
Unsupported file types found - .DS_Store

### ISSUE THREAD

**Issue by marcellocurto** [withastro/astro#6031]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

macOS 13.2

### Describe the Bug

```
02:53:23 PM [content] Unsupported file types found. Prefix with an underscore (`_`) to ignore:
- .DS_Store
```

I keep getting the above error and I think it should be ignored by Astro and not shown at all.
The is no way to comply with it as it is a hidden system file. Even if I were to prefix it with `_` macOS would just create a new .DS_Store file.

I created an example on Stackblitz, however it keeps deleting the .DS_Store file on every new run. So to reproduce the error, you have have to create the file manually inside the src/content folder to mimic macOS behavior.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kgua4m-vzkzg6?file=src/content/config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for reporting @marcellocurto! Yes, that should be ignored by Astro since it's a common file type. I'm wondering if we can respect your `.gitignore` as well for a more holistic fix.
