### ISSUE TITLE
Error Assigning Custom Components to HTML elements

### ISSUE THREAD

**Issue by marcellocurto** [withastro/astro#6032]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

macOS 13.2

### Describe the Bug

I tried to assign a custom component to an HTML element in a MDX file as described in the [documentation](https://docs.astro.build/en/guides/markdown-content/#assigning-custom-components-to-html-elements).

The problem is, that no matter which component I try to assign, it is always ignored in the actual HTML output.
Maybe there is an extra setting that needs to be configured, but there is no mention of it in the documentation.

This is the example I used from the documentation:

`src/pages/about.mdx`
```
import Blockquote from '../components/Blockquote.astro';
export const components = {blockquote: Blockquote}

> This quote will be a custom Blockquote
```

`src/components/Blockquote.astro`
```
---
const props = Astro.props;
---
<blockquote {...props} class="bg-blue-50 p-4">
  <span class="text-4xl text-blue-600 mb-2">“</span>
  <slot /> <!-- Be sure to add a `<slot/>` for child content! -->
</blockquote>
```

I also tried this and the output was still the default HTML:
```
<blockquote></blockquote>
```

In the [stackblitz example](https://stackblitz.com/edit/github-19em5z?file=src%2Fcontent%2Fblog%2Fusing-mdx.mdx,src%2Fcomponents%2FBlockquote.astro&on=stackblitz), navigate to Blog->Using MDX to see the example in action.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-19em5z?file=src%2Fcontent%2Fblog%2Fusing-mdx.mdx,src%2Fcomponents%2FBlockquote.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
It looks like this is only an issue when using MDX through a Content Collection.

From a quick investigation, it seems that the `astroDelayedAssetPlugin` (or `astroContentAssetPropagationPlugin` when #6035 is merged) is [not re-exporting `components`](https://github.com/withastro/astro/blob/9bb0bfab13c18ebc49cce1559f33d04c5f5f654f/packages/astro/src/content/vite-plugin-content-assets.ts#L37):

```ts
export { Content, getHeadings, frontmatter } from ${JSON.stringify(basePath)};
```

If exported, it would be possible to use it in the Content Collection [`render function`](https://github.com/withastro/astro/blob/9bb0bfab13c18ebc49cce1559f33d04c5f5f654f/packages/astro/src/content/internal.ts#L146) and pass it as a props so it can be [used by the MDX integration](https://github.com/withastro/astro/blob/9bb0bfab13c18ebc49cce1559f33d04c5f5f654f/packages/integrations/mdx/src/index.ts#L125):

```diff
- renderTemplate`${renderComponent(result, 'Content', mod.Content, props, slots)}`
+ renderTemplate`${renderComponent(result, 'Content', mod.Content, { ...props, components: mod.components }, slots)}`
```

Altho, it is not possible to simply add it to the list of exports as most MDX files won't export it and we would get a `"components" is not exported by "…"` error.

I tested locally using the following syntax:

```ts
import * as asset from ${JSON.stringify(basePath)};
export { Content, getHeadings, components } from ${JSON.stringify(basePath)};
export const components = asset.components;
```

This fixes the issue but I'm not sure if it's the best way to do it. I guess @bholmesdev might have a better idea.

**Comment by bholmesdev** [comment]
Ah ha, I see what's happening. There is a funky requirement in Astro today when dealing with MDX in `pages/` vs. _imported_ MDX outside of pages:
- In `pages`: `components` are wired up for you
- As an import: `components`, are _not_ wired up, and you need to manually reapply the components export as a prop when rendering the imported file: Example below.

[Stackblitz](https://stackblitz.com/edit/github-nh5fyv?file=src/pages/with-imported-mdx.astro,src/components/Title.astro,src/components/Entry.mdx)

```astro
---
import Entry, {components} from '../components/Entry.mdx'
---
<Entry components={components} />
```

Since content collections uses imports, the latter behavior occurs today (but without the components export exposed as @HiDeoo shared). I think this is something content collections can solve, but imported MDX would need some more thinking.
