### ISSUE TITLE
client directives don't work with spread syntax

### ISSUE THREAD

**Issue by schelmo** [withastro/astro#6033]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

when trying to spread client directives,
all the client attributes needed for hydration (`client:component-path`, `client:component-export`, `client:component-hydration`, `client:display-name`) are missing

```astro
---
import Counter from '../components/Counter.vue';
const dynamicAttrs = {'client:visible': true}
---
<Counter {...dynamicAttrs}>
  <h1>Hello, Vue!</h1>
</Counter>
```
`Unable to resolve a valid export for "Counter"!`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qakuvl?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You can't add client directives dynamically. This is because Astro needs to know about them in order to build the right components for production. In your example, without the directive Astro doesn't know that `Counter` is a client component and treats it like an SSR-only component.

**Comment by lschierer** [comment]
Thanks for the help
