### ISSUE TITLE
withastro/action@v0 GitHub action has a command that is going to be deprecated

### ISSUE THREAD

**Issue by ajurry** [withastro/astro#6044]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Recently followed the Astro docs for setting up a website on GitHub and it seems that the GitHub action called ```withastro/action@v0``` is currently causing a warning since it contains the "::set-output" function.

The output from my GitHub action can be seen below

```
Run len=`echo $INPUT_PM | wc -c`
  len=`echo $INPUT_PM | wc -c`
  if [ $len -gt 1 ]; then
      echo "::set-output name=PACKAGE_MANAGER::$INPUT_PM"
      echo "node_pm=$INPUT_PM" >> $GITHUB_ENV
  elif [ $(find "." -name "pnpm-lock.yaml") ]; then
      echo "::set-output name=PACKAGE_MANAGER::pnpm"
      echo "node_pm=pnpm" >> $GITHUB_ENV
  elif [ $(find "." -name "yarn.lock") ]; then 
      echo "::set-output name=PACKAGE_MANAGER::yarn"
      echo "node_pm=yarn" >> $GITHUB_ENV
  elif [ $(find "." -name "package-lock.json") ]; then 
      echo "::set-output name=PACKAGE_MANAGER::npm"
      echo "node_pm=npm" >> $GITHUB_ENV
  else
      echo "No lockfile found.
  Please specify your preferred \"package-manager\" in the action configuration."
      exit 1
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_PM: 
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Link for more information
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I don't believe I can make a stackblitz as it is deployment related, so have inserted the public git-repo where the git action displays the warning, apologies if that is not the done thing but I had to insert something!

If you have anymore questions, feel free to reply to the ticket.

### Link to Minimal Reproducible Example

https://github.com/ajurry/astro-tutorial/actions/runs/4046652580/jobs/6959763985

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Is this a documentation issue?

**Comment by ajurry** [comment]
I don't believe so, as the documentation page just states the following

https://docs.astro.build/en/guides/deploy/github/#how-to-deploy
```
Astro maintains the official withastro/action to deploy your project with very little configuration.
```

It looks like I might have raised this in the wrong repository. It seems like this code is maintained in the following
https://github.com/withastro/action

Do you want me to close the issue and raise it there?

**Comment by HiDeoo** [comment]
This should be fixed by https://github.com/withastro/action/pull/15 or https://github.com/withastro/action/pull/19.

**Comment by matthewp** [comment]
@natemoo-re can you take a look at https://github.com/withastro/action/pull/15?

**Comment by swift502** [comment]
Changes to [withastro/action](https://github.com/withastro/action) have been merged and the warnings no longer appear. https://github.com/swift502/Web/actions/runs/4080174319

Probably can close this. 👌
