### ISSUE TITLE
--- in code in astro file breaks typechecker

### ISSUE THREAD

**Issue by calebeby** [withastro/astro#6054]
Hi friends, I found another bug!

### What version of `astro` are you using?

2.0.4

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When I run `astro check`, there is a parsing error:

<img width="365" alt="Screenshot 2023-01-30 at 5 31 05 PM" src="https://user-images.githubusercontent.com/13206945/215636298-d3f4b7ca-9424-4255-a8dd-04877c779897.png">

This is when I have this code in my astro file:

```astro
---
console.log('---')
---

<!DOCTYPE html>
<html lang="en">
	<body>
		<h1>Hi</h1>
	</body>
</html>
```

It trips on the presence of the `---` within the code block. The same issue happens if the `---` is in a JS comment in the code block. If I remove the triple dashes, it works fine.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ucvq5b?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by calebeby** [comment]
I wonder if this issue belongs in https://github.com/withastro/language-tools... feel free to move it or I can close this and make a new one there if that would be better.

**Comment by calebeby** [comment]
This seems like it might be the problematic code... https://github.com/withastro/language-tools/blob/main/packages/language-server/src/core/documents/parseAstro.ts#L28-L58

**Comment by Princesseuh** [comment]
Thank you for reporting this! It's unfortunately already been reported here: https://github.com/withastro/language-tools/issues/248

You're right that it's the code you pointed out that's offending, I've been wanting to rework it but haven't had the time yet
