### ISSUE TITLE
The link to public fails if you put the parameter "base" and then remove it

### ISSUE THREAD

**Issue by afandos-bbm** [withastro/astro#6067]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

Tested with npm and pnpm

### What operating system are you using?

Windows

### Describe the Bug

The problem is that once you put the "base" parameter in the astro.config.mjs file, if you later remove it, it still keeps the base prefix.

Steps to reproduce:
1. Clone Minimal reproducible example or Create a basic app with astro.
`npm create astro@latest`
2. If you have created a new app add any svg or any other file in the "public" folder
![step2](https://i.ibb.co/VQ07hgv/Captura.png)
3. Use the file in any astro file.
![step3](https://i.ibb.co/HD8vLSY/Captura2.png)
4. You run astro with "npm run dev" and everything works.
5. In the file "astro.config.mjs" you add the base parameter with any value.
6. It will warn you that you must change the url adding the value that you have entered in "base" so that it works in production. But it still works.
7. Remove the base parameter from the "astro.config.mjs" file
and it stops working as it still requires the "base". It shows a 404 code in the console.
![step7](https://i.ibb.co/44Hdr1C/Captura3.png)
*Click on image to better view*

### Link to Minimal Reproducible Example

https://github.com/alejandrofan2/astro-bug-base

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
So this is an HMR related issue, right?

**Comment by wulinsheng123** [comment]
I would be met the same.
If I modified the TSconfig files when they already ran.

**Comment by alejandrofan2** [comment]
@matthewp It's very possible but I'm not entirely sure.

**Comment by wulinsheng123** [comment]
> @matthewp It's very possible but I'm not entirely sure.

Is that still the case?

**Comment by natemoo-re** [comment]
Unfortunately I can confirm that this is still an issue. seems like our middleware for handling `public` assets isn't regenerated when the config triggers a restart.
