### ISSUE TITLE
Astro image attempting to load images from Vue components

### ISSUE THREAD

**Issue by drewtownchi** [withastro/astro#6071]
### What version of `astro` are you using?

2.0.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I have a Vue component that is using some standard `<img src="/images/blah.jpg" />`  and when I try to run build on my machine or Netlify I get...

[@astrojs/image] Could not load /images/old-ute-valley-park-photos/old-ute-1.jpg (imported by src/components/OldPhotos.vue?vue&type=script&setup=true&lang.ts): ENOENT: no such file or directory, open 'D:\images\old-ute-valley-park-photos\old-ute-1.jpg'
 error   Could not load /images/old-ute-valley-park-photos/old-ute-1.jpg (imported by src/components/OldPhotos.vue?vue&type=script&setup=true&lang.ts): ENOENT: no such file or directory, open 'D:\images\old-ute-valley-park-photos\old-ute-1.jpg'
Error: Could not load /images/old-ute-valley-park-photos/old-ute-1.jpg (imported by src/components/OldPhotos.vue?vue&type=script&setup=true&lang.ts): ENOENT: no such file or directory, open 'D:\images\old-ute-valley-park-photos\old-ute-1.jpg'

Not sure why Astro image is trying to get involved here.  I'm not importing it anywhere in the minimal repro. The Vue component is just using standard HTML img tags that are pointing to an image in the /public/images directory.

### Link to Minimal Reproducible Example

https://github.com/drewtownchi/image-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
If I understand correctly [vue should not compile `src` attributes to imports](https://github.com/vuejs/core/blob/main/packages/compiler-sfc/src/templateTransformAssetUrl.ts#L111), which is what seems to be happening here.
Disabling that asset optimization should fix the issue
```js
import { defineConfig } from 'astro/config';
import vue from '@astrojs/vue';
import image from '@astrojs/image';

export default defineConfig({
  integrations: [
    vue({
      template: {
        transformAssetUrls: false,
      },
    }),
    image(),
  ],
});
```

**Comment by MoustaphaDev** [comment]
See another workaround https://github.com/withastro/astro/issues/5924#issuecomment-1410744335

**Comment by natemoo-re** [comment]
I haven't been able to reproduce this using the latest versions of `astro`, `@astrojs/image`, and `@astrojs/vue`. Please update your dependencies! I'd also suggest switching from `@astrojs/image` to the [`astro:assets`](https://docs.astro.build/en/guides/assets/) feature which will become the default in 3.0.
