### ISSUE TITLE
Change of Remark plugins order for MDX integration after Astro 2.0 upgrade

### ISSUE THREAD

**Issue by njakob** [withastro/astro#6079]
### What version of `astro` are you using?

2.0.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

While migrating to Astro 2.0 the "reading time" feature for my articles based on the Astro documentation (https://docs.astro.build/en/guides/markdown-content/#example-calculate-reading-time), I'm getting different reading times.

This happens as the Remark plugin is getting already "preprocessed" nodes by the built-in highlighter (Shiki in my case). In other words, `toString(tree)`  already includes some HTML which therefore adds a lot more plain text to the `reading-time` function call.

While digging into MDX, I realized that the merging of Markdown plugins got changed by https://github.com/withastro/astro/pull/5684 (especially [here](https://github.com/withastro/astro/pull/5684/files#diff-401e5b711062a443e079902c7451b00033368f375fee6a0ba9f6457065b77ce2L158)). Before, Markdown plugins were added before any MDX or built-in syntax highlighters and extensions.

Since it seems pretty common to add plugins and their order is quite relevant, we should most likely only inject highlighters as the last plugins. Unless this is due to another reason?

Besides, in the PR mentions that we could eject from the highlighters and define the order on the consumer side. However, since [`remark-shiki`](https://github.com/withastro/astro/blob/474ecc7be625a0ff2e9bc145af948e75826de025/packages/markdown/remark/src/remark-shiki.ts) is not directly exposed and cannot be directly imported, the code would need to be copy-pasted. Therefore, we could also export these "internal" plugins.
 
You can observe the change in behavior through the [following reproducible setup](https://stackblitz.com/edit/github-vcjigg) and change back to the following `package.json` dependencies:

```json
"dependencies": {
  "@astrojs/mdx": "^0.14.0",
  "astro": "^1.9.2",
  "mdast-util-to-string": "^3.1.1",
  "reading-time": "^1.5.0"
}
```

Happy to hear your thoughts here!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vcjigg?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
@njakob Good catch! Yes, this was definitely a regression. We caught a similar issue migrating docs.astro.build to 2.0 as well. Merging a fix shortly!

**Comment by njakob** [comment]
That's amazing, thank you for picking this up @bholmesdev!

Looking at the extra plugins used in the documentation, having the same issue make sense...

I would definitely test this as soon as the fix gets released :raised_hands:
