### ISSUE TITLE
Cloudflare SSR integration deployment showing empty screen

### ISSUE THREAD

**Issue by NachoVazquez** [withastro/astro#6081]
### What version of `astro` are you using?

2.0.4

### Are you using an SSR adapter? If so, which one?

Cloudflare, 6.1.1

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Creating a fresh Astro project using Cloudflare as the SSR provider doesn't work.

When deploying to Cloudflare using git integration I only get a blank screen.

https://astro-ssr-dca.pages.dev/

The following are the Cloudflare logs.

```
0:50:39.039 | Executing user command: npm run build
-- | --
20:50:39.565 | npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
20:50:39.566 | npm WARN config location in the cache, and they are managed by
20:50:39.567 | npm WARN config     [`cacache`](http://npm.im/cacache).
20:50:39.582 |  
20:50:39.582 | > @example/basics@0.0.1 build
20:50:39.583 | > astro build
20:50:39.583 |  
20:50:41.782 | 11:50:41 PM [build] output target: server
20:50:41.782 | 11:50:41 PM [build] deploy adapter: @astrojs/cloudflare
20:50:41.782 | 11:50:41 PM [build] Collecting build info...
20:50:41.783 | 11:50:41 PM [build] Completed in 27ms.
20:50:41.784 | 11:50:41 PM [build] Building server entrypoints...
20:50:44.022 | 11:50:44 PM [build] Completed in 2.24s.
20:50:44.037 |  
20:50:44.038 | finalizing server assets
20:50:44.038 |  
20:50:44.038 | 11:50:44 PM [build] Rearranging server assets...
20:50:44.099 | ▲ [WARNING] Ignoring this import because "node_modules/path-to-regexp/dist.es2015/index.js" was marked as having no side effects [ignored-bare-import]
20:50:44.100 |  
20:50:44.100 | dist/$server_build/_worker.mjs:4:7:
20:50:44.100 | 4 │ import 'path-to-regexp';
20:50:44.100 | ╵        ~~~~~~~~~~~~~~~~
20:50:44.100 |  
20:50:44.100 | "sideEffects" is false in the enclosing "package.json" file
20:50:44.101 |  
20:50:44.101 | node_modules/path-to-regexp/package.json:45:2:
20:50:44.101 | 45 │   "sideEffects": false,
20:50:44.101 | ╵   ~~~~~~~~~~~~~
20:50:44.101 |  
20:50:44.117 | 11:50:44 PM [build] Server built in 2.36s
20:50:44.118 | 11:50:44 PM [build] Complete!
20:50:44.141 | Finished
20:50:44.142 | Found _worker.js in output directory. Uploading.
20:50:44.172 | Found _routes.json in output directory. Uploading.
20:50:44.194 | Validating asset output directory
20:50:44.915 | Deploying your site to Cloudflare's global network...
20:50:47.746 | Uploading... (0/2)
20:50:47.747 |  
20:50:48.473 | AAG Uploading... (1/2)
20:50:48.473 |  
20:50:48.658 | AAG Uploading... (2/2)
20:50:48.659 |  
20:50:48.661 | ✨ Success! Uploaded 2 files (1.60 sec)
20:50:48.662 |  
20:50:49.132 | ✨ Upload complete!
20:50:50.610 | Success: Assets published!
20:50:51.488 | Success: Your site was deployed!
```

When trying it locally, I get a different error.

Running 

```bash
yarn build && yarn preview
```

Where `yarn preview` is `wrangler pages dev ./dist`

Results in the following error

```
[ssr] Error: To use the new ReadableStream() constructor, enable the streams_enable_constructors feature flag.
    at Object.construct (/Users/nachovazquez/work/experiments/astro-ssr/node_modules/@miniflare/core/src/plugins/core.ts:97:13)
    at Ti (/Users/nachovazquez/work/experiments/astro-ssr/dist/_worker.js:59:767)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Qi (/Users/nachovazquez/work/experiments/astro-ssr/dist/_worker.js:61:2849)
    at $e.dt (/Users/nachovazquez/work/experiments/astro-ssr/dist/_worker.js:61:8890)
    at $e.render (/Users/nachovazquez/work/experiments/astro-ssr/dist/_worker.js:61:8061)
    at Object.fetch (/Users/nachovazquez/work/experiments/astro-ssr/dist/_worker.js:93:1126)
    at EventTarget.[kDispatchFetch] (/Users/nachovazquez/work/experiments/astro-ssr/node_modules/@miniflare/core/src/standards/event.ts:385:13)
    at Server.<anonymous> (/Users/nachovazquez/work/experiments/astro-ssr/node_modules/@miniflare/http-server/src/index.ts:298:20)
GET / 500 Internal Server Error (41.49ms)
GET /service-worker.js 404 Not Found (5.33ms)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/js-zbcxfx?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Pelps12** [comment]
I have the issue as well. 
I'm trying to see if there is a way I can enable the feature flag from a "pages dev" command.
Also, if you turn off local mode, it looks the same as in deployment

**Comment by Pelps12** [comment]
Where would you place the wrangler.toml file directory-wise?

**Comment by vampaz** [comment]
https://developers.cloudflare.com/workers/wrangler/configuration/

**Comment by Pelps12** [comment]
I mean should it be in the root folder on the ./dist folder.

**Comment by vampaz** [comment]
> I mean should it be in the root folder on the ./dist folder.

Root

**Comment by Pelps12** [comment]
Thanks. It worked

**Comment by vampaz** [comment]
In prod:
"outcome": "exception",
  "scriptName": "pages-worker--696915-preview",
  "exceptions": [
    {
      "name": "TypeError",
      "message": "Failed to execute 'encode' on 'TextEncoder': parameter 1 is not of type 'String'.",
      "timestamp": 1675173793258
    }
  ],

**Comment by Pelps12** [comment]
Yeah. Same thing. I think there is a PR made for that #6070

**Comment by wolves** [comment]
I am now seeing this same issue again as of recently:

```json
"exceptions": [
    {
      "name": "TypeError",
      "message": "Failed to execute 'encode' on 'TextEncoder': parameter 1 is not of type 'String'.",
      "timestamp": 1690036683358
    }
  ],
  ```

These are the following project dependencies:
```json
  "dependencies": {
    "@astrojs/cloudflare": "^6.6.2",
    "@astrojs/svelte": "^3.1.0",
    "@astrojs/tailwind": "^4.0.0",
    "astro": "^2.9.1",
    "svelte": "^4.1.1",
    "tailwindcss": "^3.3.3"
  },
```

And the astro config:
```mjs
import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import cloudflare from "@astrojs/cloudflare";

import svelte from "@astrojs/svelte";

// https://astro.build/config
export default defineConfig({
  integrations: [tailwind(), svelte()],
  output: "server",
  adapter: cloudflare()
});
```

Any help anyone could offer would be much appreciated and if there is any more info needed or anything I can help with to resolve this please let me know.

**Comment by reneklacan** [comment]
I'm also running into this issue with 2.9.1

@wolves Downgrading to 2.8.5 resolved it.

**Comment by dokozero** [comment]
Same here, with cloudflare 6.6.2 and astro 2.9.1.
I have this error, "Error: To use the new ReadableStream() constructor, enable the streams_enable_constructors feature flag."
I added the mentioned flag in worker's config (in admin not wrangler.toml).

And now I have this error too "Failed to execute 'encode' on 'TextEncoder': parameter 1 is not of type 'String'."

Tried to use astro 1.8.5 but with no luck 🤷‍♂️.

**Comment by wolves** [comment]
> I'm also running into this issue with 2.9.1
> 
> @wolves Downgrading to 2.8.5 resolved it.

I attempted to downgrade, but it did not resolve the issue for me

**Comment by bluwy** [comment]
Sorry for the regression! I've made a fix at https://github.com/withastro/astro/pull/7777.

**Comment by genesem** [comment]
> > I'm also running into this issue with 2.9.1
> > @wolves Downgrading to 2.8.5 resolved it.
> 
> I attempted to downgrade, but it did not resolve the issue for me

Happend to me with long time ago created pages project (old compat date in production)
How it could be fixed:
In the pages project go to 'settings' then 'functions' ,
find and set 'Compatibility date'  newer than '2022-11-30'
and redeploy the project.
