### ISSUE TITLE
Any query parameter breaks pre-rendered routes completely

### ISSUE THREAD

**Issue by Paratron** [withastro/astro#6093]
### What version of `astro` are you using?

2.0.5

### Are you using an SSR adapter? If so, which one?

node 5.0.2

### What package manager are you using?

npm

### What operating system are you using?

windows, linux

### Describe the Bug

If you add any query parameter to a request URL, the routing breaks completely, responding with status 404 and a simple text content "Not found". Not even a pre-defined 404 page is returned.

# Steps to reproduce
- Add @astrojs/node as adapter to astro
- Make a prerendered route with `export const prerender = true;`
- Make a production build
- Start the build result
- Add any query parameter to a otherwise functional URL

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kewixk?file=src/pages/test.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Does the Node adapter correctly serve the prerendered route without the query param?

**Comment by Paratron** [comment]
Yes, works fine without the query param. Or if I remove the prerender flag, it works with query params again 🙈

**Comment by bholmesdev** [comment]
Hm, this seems like expected behavior if I understand this right. `prerender` ensures a route outputs a _static HTML file,_ rather than a server endpoint. Included query parameters would no longer point to that static file. You can try adding query params to an SSG site to see similar behavior. cc @matthewp

**Comment by matthewp** [comment]
The Node.js adapter is able to serve the prerendered HTML (I think). So I think this is a case where it is not finding the .html file because it is not omitting the query params when checking, is my guess.

**Comment by matthewp** [comment]
Going to take a look.
