### ISSUE TITLE
`undefined` params within getStaticPaths cause Vercel build to fail

### ISSUE THREAD

**Issue by joe-bell** [withastro/astro#6095]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

#### Expectation

When using `params` in a `getStaticPaths` function, I would expect `undefined` to result in the creation of an index route.

#### Actual Behaviour

The build fails in Vercel

##### Success: Without `undefined` `params`

- Deployment: https://vercel.com/joebell/astro-bug-params-undefined/4G9AqahtnJTsvXzCP6Z97H55ze73

```sh
19:36:18.324	▶ src/pages/example/[...slug].astro
19:36:18.345	  ├─ /example/one/index.html (+21ms)
19:36:18.347	  ├─ /example/two/index.html (+23ms)
19:36:18.348	  └─ /example/three/index.html (+25ms)
19:36:18.349	λ src/pages/api/example/[...slug].ts
19:36:18.350	  ├─ /api/example/one (+1ms)
19:36:18.351	  ├─ /api/example/two (+2ms)
19:36:18.351	  └─ /api/example/three (+3ms)
19:36:18.351	Completed in 59ms.
```

##### Error: With `undefined` `params`

- Deployment: https://vercel.com/joebell/astro-bug-params-undefined/Fj1im5wqsKA6XdVn2VhGkWrkSFja

```sh
▶ src/pages/example/[...slug].astro
19:39:10.815	  ├─ /example/one/index.html (+18ms)
19:39:10.817	  ├─ /example/two/index.html (+19ms)
19:39:10.818	  ├─ /example/three/index.html (+21ms)
19:39:10.820	  └─ /example/index.html (+22ms)
19:39:10.820	λ src/pages/api/example/[...slug].ts
19:39:10.821	  ├─ /api/example/one (+1ms)
19:39:10.822	  ├─ /api/example/two (+2ms)
19:39:10.822	  ├─ /api/example/three (+3ms)
19:39:10.911	 error   EISDIR: illegal operation on a directory, open '/vercel/path0/.vercel/output/static/api/example'
19:39:10.911	Error: EISDIR: illegal operation on a directory, open '/vercel/path0/.vercel/output/static/api/example'
19:39:10.926	 ELIFECYCLE  Command failed with exit code 1.
```

### Link to Minimal Reproducible Example

https://github.com/joe-bell/astro-bug-params-undefined

> **Note**
>
> More details have been provided in the reproduction

### Participation

- [ ] I am willing to submit a pull request for this issue.

---

Not part of the template, but just want to say a huge thanks to the Astro team – I love using this product and I appreciate you all!

**Comment by AirBorne04** [comment]
Ok there seems to be an inconsistency with the behaviour between API routes and Pages where for Pages `undefined` is translated into index, for the API routes undefined is throwing an error and not falling back to index.
The easy work around would be to add `index` for the API route directly.

**Comment by joe-bell** [comment]
Cheers! That’s the tactic I’ve opted for now; with a `_handler.ts` that’s used across both `index.ts` and `[…slug].ts`

It’s fine in the meantime, but of course would be nice to have matching behaviour across all routes

**Comment by joe-bell** [comment]
Following up: It seems like the same issue occurs for nested (spread) params (i.e. `/a/b`)

```sh
Error: ENOTDIR: not a directory, mkdir '/vercel/path0/.vercel/output/static/a/b/'
--
17:16:28.830 | ELIFECYCLE  Command failed with exit code 1.
17:16:28.851 | Error: Command "pnpm build" exited with 1
```

**Comment by AirBorne04** [comment]
Sorry I might not have been clear on what I meant exactly, you do not need to create a separate `index.ts`.

My suggestion was to replace [this line](https://github.com/joe-bell/astro-bug-params-undefined/blob/945f210eb145cf5c344ab3d6b9b0b8fea6d35b45/src/pages/api/example/%5B...slug%5D.ts#L3):
```
const slugs = ["one", "two", "three", undefined];
```
with the following
```
const slugs = ["one", "two", "three", "index"];
```

**Comment by joe-bell** [comment]
Thanks @AirBorne04!

That seems to work for endpoints, but not for regular pages

https://github.com/joe-bell/astro-bug-params-undefined/pull/1

- https://astro-bug-params-undefined-cspzja1z6-joebell.vercel.app/example/index
- https://astro-bug-params-undefined-cspzja1z6-joebell.vercel.app/example
- https://astro-bug-params-undefined-cspzja1z6-joebell.vercel.app/api/example
- https://astro-bug-params-undefined-cspzja1z6-joebell.vercel.app/api/example/index

**Comment by AirBorne04** [comment]
Hi joe-bell,
it seems that `example/`works just `example` not. I would like to dig deeper on this one, but I do not have time at the moment.
@matthewp can you check this out?

**Comment by wulinsheng123** [comment]
> Thanks @AirBorne04!
> 
> That seems to work for endpoints, but not for regular pages
> 
> [joe-bell/astro-bug-params-undefined#1](https://github.com/joe-bell/astro-bug-params-undefined/pull/1)
> 
> * https://astro-bug-params-undefined-cspzja1z6-joebell.vercel.app/example/index
> * https://astro-bug-params-undefined-cspzja1z6-joebell.vercel.app/example (this one doesn't exist)
> * https://astro-bug-params-undefined-cspzja1z6-joebell.vercel.app/api/example
> * https://astro-bug-params-undefined-cspzja1z6-joebell.vercel.app/api/example/index

this link of code all from  this `https://github.com/joe-bell/astro-bug-params-undefined` repository？

**Comment by wulinsheng123** [comment]
> Sorry I might not have been clear on what I meant exactly, you do not need to create a separate `index.ts`.
> 
> My suggestion was to replace [this line](https://github.com/joe-bell/astro-bug-params-undefined/blob/945f210eb145cf5c344ab3d6b9b0b8fea6d35b45/src/pages/api/example/%5B...slug%5D.ts#L3):
> 
> ```
> const slugs = ["one", "two", "three", undefined];
> ```
> 
> with the following
> 
> ```
> const slugs = ["one", "two", "three", "index"];
> ```

I'm curious, you said that only happen in production ?
I tried out and also at dev environment ?
![image](https://user-images.githubusercontent.com/27261522/220514737-2cb280ba-1610-412e-8a5c-b441960a0d6b.png)
