### ISSUE TITLE
Cannot use in old browsers

### ISSUE THREAD

**Issue by axelthat** [withastro/astro#6096]
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

As suggested by @matthewp here: https://github.com/withastro/astro/issues/5870#issuecomment-1405609124, I did the following to target Astro to run on legacy browsers:

```
import pluginLegacy from '@vitejs/plugin-legacy';
import { defineConfig } from 'astro/config';

export default defineConfig({
  integrations: [
    {
      name: 'my-integration',
      hooks: {
        'astro:build:setup': ({ vite, target }) => {
          if(target === 'client') {
            vite.plugins.push(pluginLegacy());
          }
        }
      }
    }
  ]
});
```

This does render legacy chunks but Astro doesn't inject them in HTML files: https://github.com/withastro/astro/issues/5870#issuecomment-1407368142.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/typescript-9hhrzt?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I'm not familiar with this plugin. What does it do? What does Astro need to do with the chunks it creates?

**Comment by axelthat** [comment]
From https://github.com/vitejs/vite/tree/main/packages/plugin-legacy,

> By default, this plugin will:
> 
> Generate a corresponding legacy chunk for every chunk in the final bundle, transformed with [@babel/preset-env](https://babeljs.io/docs/en/babel-preset-env) and emitted as [SystemJS modules](https://github.com/systemjs/systemjs) (code splitting is still supported!).
> 
> Generate a polyfill chunk including SystemJS runtime, and any necessary polyfills determined by specified browser targets and actual usage in the bundle.
> 
> Inject <script nomodule> tags into generated HTML to conditionally load the polyfills and legacy bundle only in browsers without widely-available features support.
> 
> Inject the import.meta.env.LEGACY env variable, which will only be true in the legacy production build, and false in all other cases.

**Comment by matthewp** [comment]
Ok, the desire here is to support IE11, is that right?

**Comment by axelthat** [comment]
@matthewp Not really. I want to support chrome 55+. I don’t want to support IE11.

**Comment by matthewp** [comment]
Ah ok. Fully supporting `nomodule` is not something we are going to be able to do. Astro uses modules pretty deeply; all component loading is done with the assumption that they are modules. It would be quite an engineering feat to take that on.

It _might_ be possible to implement that in an integration. But it would be non-trivial, all island loading is done by importing modules.

Going to close because we unfortunately aren't going to be able to take this on.

**Comment by totalhack** [comment]
Just curious, do you guys know if an approach like this suffers from the same limitation where astro won't end up using the "legacy" result. It's not using the plugin, just setting the vite build target to es6:

```javascript
    {
      name: 'vite-es6',
      hooks: {
        'astro:build:setup': ({ vite, target }) => {
          if (target === 'client') {
            vite.build.target = "es6";
          }
        }
      }
    },
```

**Comment by mb21** [comment]
Here's a proposal to allow us to at least print a fallback message: [Roadmap discussion: Fallback for framework components that fail to hydrate or crash in the client ](https://github.com/withastro/roadmap/discussions/724)
