### ISSUE TITLE
Errors in the console from other route components in the dev

### ISSUE THREAD

**Issue by sauravexodus** [withastro/astro#6099]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

scripts are executed which are outside the scope of the the current component. This only happens when I am running the dev server for local development. When I generate pages using the static adapter, then scope resolution works fine.

In the [example](https://stackblitz.com/edit/withastro-astro-huhcsw?file=src/pages/index.astro). I have a separate component called called errors.astro which has it's separate script block. The problem arises when I load the index.astro file, since errors.astro is out of scope, it should not show errors from the other page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-huhcsw?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I just pulled down your project, started dev and went to the index page and saw no errors. Should I have?

**Comment by matthewp** [comment]
Closing, let me know if I missed something and I'll reopen.
