### ISSUE TITLE
@astrojs/image: support for SVG files missing

### ISSUE THREAD

**Issue by ggounot** [withastro/astro#6101]
### What version of `astro` are you using?

2.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

SVG files can be used through `<img />` but the `@astrojs/image` integration doesn't permit it through `<Image />`.

A `*.svg` module declaration should be added in `@astrojs/image/client.d.ts` (as it exists in `astro/client.d.ts`) and metadata extraction support for SVG files should be added so that `<Image />` can generate an `<img />` tag with `width` and `height` attributes. The SVG file itself doesn't have to be converted.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rgnkk6?file=src/pages/index.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by ggounot** [comment]
Fixed in @astrojs/image@0.15.0

**Comment by gkatsanos** [comment]
@ggounot can we actually use the image integration and INLINE svg's instead if having them as <img />'s?

**Comment by gkatsanos** [comment]
@ggounot I dont think so.. what would be the example code for this?

**Comment by gkatsanos** [comment]
sorry, I think I may not have been clear:
import and svg and INLINE it in the html:

<html>
... <svg> <path> whatever </path> </svg>

**Comment by ggounot** [comment]
@gkatsanos I don't think you need the image integration to do that. But I don't have much experience with Astro so I invite you to ask on the Discord directly.

**Comment by gkatsanos** [comment]
Indeed, using Fragment and set:html it's done! Thank you
