### ISSUE TITLE
Vite config cause Error on Build

### ISSUE THREAD

**Issue by stabas** [withastro/astro#6103]
### What version of `astro` are you using?

2.0.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Updated to v2 on astro project. I already had some vite building options in the config for naming script and styling files in "clear text". 
Running build gets completed but also causes this error, caused by line: chunkFileNames: 'assets/[name].js'

![image](https://user-images.githubusercontent.com/58772524/216340745-c3abdb1b-1374-4bb6-87d1-3e1740ce660d.png)

### Link to Minimal Reproducible Example

(WebContainer doesnt work on my browsers - don't know why. double checked with multiple browser, incognito modes, adblockers, etc)

https://stackblitz.com/edit/github-dwxnyr?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
If you change the output files to `.js` instead of `.mjs` (which is what Astro does by default), you need to set `"type": "module"` in your Astro config, or Node.js will not recognize them to be modules.
