### ISSUE TITLE
<Component> was created with unknown prop 'class'

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [withastro/astro#6106]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

windows

### Describe the Bug

![2](https://user-images.githubusercontent.com/67856304/216391636-04f779b7-4724-4f58-8527-8e067a3a391e.PNG)
![`1](https://user-images.githubusercontent.com/67856304/216391642-5ced2d00-4866-48dc-bb0f-27b9ddc0f280.PNG)
![3](https://user-images.githubusercontent.com/67856304/216394941-b3e2956f-28ae-4e4a-927a-0e1552156865.PNG)

- Problem
1. when i use svelte components in astro file, above warn message occurs every re-loaded.
2. previous version(1.x), i believe i didnt see any issues like this.
3. i didnt any props to component as you see, but i cant still understand what does mean of 'class' prop.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by moritzlaube** [comment]
You closed this issue yourself. How did you solve your issue? I am experiencing the same with Astro 2

**Comment by JUNGHUNKIM-7** [comment]
@moritzlaube oh, i forgot remaining solution for this. sorry for that.
i believe that was very silly mistakes & issues which is not hard to solve.
i'm looking back my code, but that seems setting or config issue, because my code is still same.

**Comment by gerardo-rodriguez** [comment]
I am also experiencing this same issue. It's not clear to me how to fix it.

**Comment by JUNGHUNKIM-7** [comment]
@gerardo-rodriguez so painful that, i should've leave the solution. did you check your slot names? bind astro's slot name to fragment's, svelte slot should bind only svelte files. and check both kinds of slot please.

**Comment by JUNGHUNKIM-7** [comment]
i think when im using astro wrapper(.astro) with slot and svelte componet is also in astro wrapper with client:something, Err happends.

so i modified code like this
```
--ASTROWRAPPER
<div>
  <slot name='a'/>
  <slot/>
  <slot name='b'/>
</div>

--ComponentA(.astro)
<Fragment slot='a'>
  <YOUR SVELTE client:idle/>
</Fragment>
```

--ComponentB(.astro)
<Fragment slot='b'>
  <YOUR SVELTE client:idle/>
</Fragment>
```

--Wrapper(.astro)
<ASTROWRAPPER>
   <div> ...
   <ComponentA />
   <div2> ...
   <ComponentB />
</ASTROWRAPPER>
```
that is what i solved. if someone find another solution, please leave comments!
