### ISSUE TITLE
 .jsx is not  a  module

### ISSUE THREAD

**Issue by guzily** [withastro/astro#6127]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

I follow the steps of astro doc to use react components . however, vscode editor says that

> github-nocpho/src/components/MyReactComponent.jsx is not a module

<img width="982" alt="image" src="https://user-images.githubusercontent.com/74231693/216756042-1eacfa6c-9815-471d-be1e-d331cc0bd2af.png">

What is the reason, is there any solution? Thank you very much for the answer!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nocpho

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your React component is empty, it won't be considered a module until it exports something.

**Comment by Fuutarou-Uesugi** [comment]
this helps me https://docs.astro.build/es/guides/integrations-guide/react/
