### ISSUE TITLE
Deno SSR with prerender=true complains about invalid URL scheme

### ISSUE THREAD

**Issue by andrioid** [withastro/astro#6131]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

Deno

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Adding `export const prerender = true` to `index.astro` in the Deno example is enough to cause the error:

Steps:
1. Check out the example repo
2. Run: `pnpm run build`
3. Observe the following...

```
 prerendering static routes 
 error   Only URLs with a scheme in: file, data are supported by the default ESM loader. Received protocol 'https:'
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. Received protocol 'https:'
    at new NodeError (node:internal/errors:372:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
    at defaultResolve (node:internal/modules/esm/resolve:1200:3)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36)
 ELIFECYCLE  Command failed with exit code 1.
```

I was attempting to migrate my Astro site to SSR. I have several things that I'd like to pre-render, such as my PDF CV and social-cards.

### Link to Minimal Reproducible Example

https://github.com/andrioid/astro-deno-ssr-prerender-bug

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
mark

**Comment by natemoo-re** [comment]
A fix for this was added, then reverted. The new fix is https://github.com/withastro/astro/pull/6284 which should have some performance gains as well.

Going out in [`@astrojs/deno@4.0.2`](https://github.com/withastro/astro/pull/6279)
