### ISSUE TITLE
@astrojs/image working, but not copying image file to dist-folder

### ISSUE THREAD

**Issue by oschade** [withastro/astro#6132]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

When using @astrojs/image to process image files, the image processing works correctly and the URL to the image is correctly pointing to the image in the dist/.astro folder, but the image file is not present in that folder.

### Link to Minimal Reproducible Example

https://github.com/oschade/steadfast-sphere

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello, the reproduction you shared is a link to the basic example. Please include a proper reproduction

**Comment by oschade** [comment]
Updated it. Just run run `yarn build`.

**Comment by matthewp** [comment]
Import the image rather than passing the path as string.

```js
import src from "../assets/photo-1525310072745-f49212b5ac6d.jpg"
```

This fixes it.
