### ISSUE TITLE
Generated assets do not respect base config property when using content collections

### ISSUE THREAD

**Issue by ChristineTham** [withastro/astro#6133]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Generated assets are referenced without the `base` prefix in content collections under some circumstances.

In the minimum reproducible example, do a `yarn build`, then view the generated file `dist/blog/test/index.html` it references assets without the `base` prefix:

```html
<link rel="stylesheet" href="/_astro/Card.astro_astro_type_style_index_0_lang.9142d561.css" />
<link rel="stylesheet" href="/_astro/Card.astro_astro_type_style_index_1_lang.c2da61e5.css" />
<link rel="stylesheet" href="/_astro/Layout.astro_astro_type_style_index_0_lang.12c5fa68.css" />
<link rel="stylesheet" href="/_astro/photoswipe-dynamic-caption-plugin.1f3fc3bb.css" />
<link rel="stylesheet" href="/_astro/photoswipe.b0eaaae0.css" />
<script src="/test/_astro/Card.astro_astro_type_script_index_0_lang.4d86517e.js" type="module"></script>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hgxunk

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by seeplusplus** [comment]
Hi! Could you give some more details on what you're trying to do? I looked at your minimal reproducible example but didn't see the `base` property set in the Astro config or any `<script>`s in the components.

**Comment by ChristineTham** [comment]
> Hi! Could you give some more details on what you're trying to do? I looked at your minimal reproducible example but didn't see the `base` property set in the Astro config or any `<script>`s in the components.

Oh, it didn't show? I must have forgotten to save the stackblitz. I have saved it now.

Anyway, all I did was take the Astro Basics started on stackblitz, made the following two changes.

In `src/pages/index.astro` added the following lines

```html
<p id="demo">A Paragraph.</p>
<button type="button" onclick="myFunction()">Try it</button>

<script>
function myFunction() {
  document.getElementById("demo").innerHTML = "Paragraph changed.";
}
</script>
```

In `astro.config.mjs` added the following:

```javascript
export default defineConfig({ base: 'test'});
```

**Comment by claudealdric** [comment]
Hey @ChristineTham!I'm not too familiar with Astro projects yet, but from looking at the documentation, it looks like `.astro` files require a different syntax for an `onClick` handler, which is not like the syntax we would normally see in React. [Here's the relevant documentation](https://docs.astro.build/en/guides/client-side-scripts/#handle-onclick-and-other-events) for reference. Using this, I was able to attach an `onClick` handler for the button. I'm away from my desk at the moment, but I can show you some code if it'll be helpful.

**Comment by seeplusplus** [comment]
> > Hi! Could you give some more details on what you're trying to do? I looked at your minimal reproducible example but didn't see the `base` property set in the Astro config or any `<script>`s in the components.
> 
> Oh, it didn't show? I must have forgotten to save the stackblitz. I have saved it now.
> 
> Anyway, all I did was take the Astro Basics started on stackblitz, made the following two changes.
> 
> In `src/pages/index.astro` added the following lines
> 
> ```
> <p id="demo">A Paragraph.</p>
> <button type="button" onclick="myFunction()">Try it</button>
> 
> <script>
> function myFunction() {
>   document.getElementById("demo").innerHTML = "Paragraph changed.";
> }
> </script>
> ```
> 
> In `astro.config.mjs` added the following:
> 
> ```js
> export default defineConfig({ base: 'test'});
> ```

I am a little bit rusty on the preferred syntax here, but the issue here is that `<script>` tags are imported as ES modules. If you module your JS to 
```js
export function myFunction() {
  console.log('test');
  const demo = document.getElementById('demo');
  
  if (demo) {
	  demo.innerHTML = 'Paragraph changed';
  }
}
window.myFunction = myFunction;
```

then the desired outcome works.

Obviously, binding to `window` is not preferable, but it does get the desired effect.

**Comment by MoustaphaDev** [comment]
Hi, you need to use the `is:inline` directive to use a function like this
```diff
-<script>
+<script is:inline>
function myFunction() {
  document.getElementById("demo").innerHTML = "Paragraph changed.";
}
</script>
```

**Comment by ChristineTham** [comment]
> Hi! You just need to use the [`is:inline`](https://docs.astro.build/en/reference/directives-reference/#isinline) directive if you want to reference a function like this in your markup

Yes, but it doesn't work generally, including for <script src='...'> - I merely created a minimal example. The processed script does not include base so does not get loaded.

**Comment by claudealdric** [comment]
> You just need to use the [`is:inline`](https://docs.astro.build/en/reference/directives-reference/#isinline) directive

Huh. TIL.

**Comment by MoustaphaDev** [comment]
@ChristineTham I see that you have updated your reproduction but it doesn't show anything unexpected, the script is loaded in dev and in build. Mind updating it to show your issue?

**Comment by ChristineTham** [comment]
> @ChristineTham I see that your reproduction has been updated but it doesn't show anything unexpected, the script is loaded in dev and in build. Mind updating it to show the issue?

Thanks Moustapha unfortunately the problem is not as reproducible as I thought, and it's quite difficult to replicate. It seems under certain circumstances the current version of astro generates css and js assets that are not prefixed by base but I can't find an easy way to replicate it. I've managed to work around the issue. Would you like me to spend more time trying to create a reproducible example? The issue is in the following repository but my latest commit has avoided the issue:

https://github.com/hellotham/hello-astro/

**Comment by ChristineTham** [comment]
I suspect my issue is related to https://github.com/withastro/astro/issues/5968

**Comment by ChristineTham** [comment]
OK, I have successfully created a minimal reproducible example. If you view the stackblitz project, do a `yarn build`, then view the generated file `dist/blog/test/index.html` it references assets without the base prefix:

```html
<link rel="stylesheet" href="/_astro/Card.astro_astro_type_style_index_0_lang.9142d561.css" /><link rel="stylesheet" href="/_astro/Card.astro_astro_type_style_index_1_lang.c2da61e5.css" /><link rel="stylesheet" href="/_astro/Layout.astro_astro_type_style_index_0_lang.12c5fa68.css" /><link rel="stylesheet" href="/_astro/photoswipe-dynamic-caption-plugin.1f3fc3bb.css" /><link rel="stylesheet" href="/_astro/photoswipe.b0eaaae0.css" /><script src="/test/_astro/Card.astro_astro_type_script_index_0_lang.4d86517e.js" type="module"></script>
```

**Comment by matthewp** [comment]
Thanks, here's the code where that happens: https://github.com/withastro/astro/blob/main/packages/astro/src/content/vite-plugin-content-assets.ts

Looks like base is not being taken into account for links.

**Comment by matthewp** [comment]
PR up: https://github.com/withastro/astro/pull/6182
