### ISSUE TITLE
When i config vite in astro with a function 

### ISSUE THREAD

**Issue by 19Qingfeng** [withastro/astro#6136]
### What version of `astro` are you using?

2.0.5

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

when i config vite in astro with a function , such as:
```js
export default defineConfig({
  output: 'server',
  integrations: [react(), svelte()],
  vite: (env) => {
    return {
      plugins: [
        visualizer(),
        analyzer(),
        createImportPlugin([
          {
            libraryName: 'antd',
          },
        ]),
      ],
    };
  },
  adapter: node({
    mode: 'standalone',
  }),
});
```

He doesn't work, but I want to get environmental variables to distinguish between ssrBuild to configure different plug-ins.

I find that the functional approach does not work. I'm not sure there's any other way I can configure it.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Use the `astro:build:setup` integration hook. You can then inject Vite plugins there based on the `target`. https://docs.astro.build/en/reference/integrations-reference/#astrobuildsetup
