### ISSUE TITLE
<slot /> between texts is adding a new empty character

### ISSUE THREAD

**Issue by noghartt** [withastro/astro#6141]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I have a simple component called `Link` following this structure:

```astro
<a>
  <slot />
</a>
<style>
  a {
    color: inherit;
    cursor: pointer;
    text-decoration: underline dotted;
  }

  a:hover {
    text-decoration: underline solid;
  }
</style>
```

When we add it following this structure in a component like this:

```astro
---
import Link from '../components/Link.astro';
---

<p>Just a test using <Link>link</Link>, ok?</p>
```

The `<slot />` adds a new empty character between the last character from `Link` and the rest of the paragraph text with a blank space.

<details>
<summary>See the example to understand it</summary>

![image](https://user-images.githubusercontent.com/47952043/216851253-5eea251d-b39a-4cde-8e16-46e33e76e57e.png)
</details>

A way to fix it is restructuring the `Link` component to follow this:
```astro
<a><slot /></a>
<style>
  a {
    color: inherit;
    cursor: pointer;
    text-decoration: underline dotted;
  }

  a:hover {
    text-decoration: underline solid;
  }
</style>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-d7bqks?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
`a` is an inline element, so line breaks inside it will appear in the result. You can see the same behaviour [in vanilla HTML in this CodePen](https://codepen.io/princesseuh/pen/gOjyKwQ)

This page on mdn gives more details as to how whitespace is handled in HTML: <https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace>
