### ISSUE TITLE
[ssr] Error: Expected an exported Astro component but received typeof undefined  when visit dinamic route

### ISSUE THREAD

**Issue by newathnow** [withastro/astro#6146]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

SSR NODE

### What package manager are you using?

NPM

### What operating system are you using?

Mac

### Describe the Bug

[ssr] Error: Expected an exported Astro component but received typeof undefined

when visit dinamic route (aka fetching from api information) getting this error

"dependencies": {
    "@astrojs/image": "^0.14.0",
    "@astrojs/node": "^5.0.3",
    "@astrojs/partytown": "^1.0.2",
    "astro": "^2.0.6",
    "axios": "^1.2.2",
    "calculate-readtime": "^0.0.3",
    "cookie": "^0.5.0",
    "date-fns": "^2.29.3",
    "fs-extra": "^11.1.0",
    "http-cookie-agent": "^5.0.2",
    "javascript-time-ago": "^2.5.9",
    "jquery": "^3.6.3",
    "reading-time-estimator": "^1.7.2",
    "sharp": "^0.31.3",
    "swiper": "^8.4.6",
    "tough-cookie": "^4.1.2",
    "undici": "^5.15.0"
  }

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-j8s3qs?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please provide a reduce example. This has a lot of integrations and configuration that likely has nothing to do with the problem. For example you should not be setting `noExternal` for astro and astro/image. That's likely your problem.

**Comment by newathnow** [comment]
no it wasnt this ser :D but will try debug more

**Comment by newathnow** [comment]
thing is i am using [slug].astro and make fetch req to api to fetch a post and its inside page folder
