### ISSUE TITLE
Older browsers support

### ISSUE THREAD

**Issue by 19Qingfeng** [withastro/astro#6158]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Hello, I checked the official website and didn't find the corresponding browser support description.

I see that the compiled HTML uses Web Component，At the same time, I hope to support IE 11. Please ask whether Astro supports IE 11. Or what other polyfill methods can be supported.

I want to render normally in IE 11 and Chrome 50

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Hi @19Qingfeng! Unfortunately no, Astro is not built to support IE 11. This is an intentional decision to keep the scope of our testing secure. We are focused on Chrome, Firefox, and Safari today. Closing this issue since this is expected!

**Comment by yanni4night** [comment]
Does Astro support Safari <13(which not support BigInt)?

**Comment by mb21** [comment]
Here's a proposal to allow us to at least print a fallback message: [Roadmap discussion: Fallback for framework components that fail to hydrate or crash in the client ](https://github.com/withastro/roadmap/discussions/724)
