### ISSUE TITLE
Style loading will fail

### ISSUE THREAD

**Issue by qiuqfang** [withastro/astro#6172]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When using the styled components in the React integration, the style of the generated components is modified; the style loading fails

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-bc4tvc

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
related to #4432

**Comment by matthewp** [comment]
Astro does not integrate with these libraries and so you don't get SSR support for their styles. I'm planning on working on head propagation as a future feature for Astro and think we can likely create some hooks that might allow this.

**Comment by matthewp** [comment]
But yes, let's keep #4432 as the issue about CSS-in-JS. I'm going to consider this use-case in my head propagation proposal.

**Comment by qiuqfang** [comment]
Thank you for your help

**Comment by qiuqfang** [comment]
> But yes, let's keep #4432 as the issue about CSS-in-JS. I'm going to consider this use-case in my head propagation proposal.

Thank you for your help
