### ISSUE TITLE
astro dev slow or unresponsive when using content collections

### ISSUE THREAD

**Issue by ChristineTham** [withastro/astro#6173]
### What version of `astro` are you using?

2.0.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Minimal example is a simple site with content collections.

astro check shows no errors

astro build and astro preview works

astro dev hangs - does not render a page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-qcexpn

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ChristineTham** [comment]
Looking more closely at the code, I think the issue may be caused by the index page calling `getCollection('doc')` but the layout page for the content is also calling `getCollection('doc')`

**Comment by matthewp** [comment]
is `getCollection('doc')` slow? Did you dig into why?

**Comment by ChristineTham** [comment]
> is `getCollection('doc')` slow? Did you dig into why?

I don't think it's slow, but not handling reentrant calls in dev. Basically, index.astro is calling `await getCollection('doc')`, but the collection itself has pages referencing a layout that also does `await getCollection('doc')` and this causes a hang. I'll try and create another, even smaller example that illustrates this.

**Comment by matthewp** [comment]
Oh! I can see how we might run into this issue. cc @bholmesdev possible circular dep issue here. A smaller reproduction would be helpful, thanks!

**Comment by ChristineTham** [comment]
> Oh! I can see how we might run into this issue. cc @bholmesdev possible circular dep issue here. A smaller reproduction would be helpful, thanks!

Here is an even smaller example, based on the Astro Basics starter. Basically the problem reared itself as soon as I added a getCollections in the Blog.layout file.

https://stackblitz.com/edit/github-3pq5xf

**Comment by wulinsheng123** [comment]
mark

**Comment by bholmesdev** [comment]
@matthewp This is interesting, because Vite handles circular dependencies with `Astro.glob` pretty well. My guess is our internal async imports aren't handled properly 🤔 

In the meantime @ChristineTham, I'll suggest replacing your `layout` prop with an explicit layout wherever you're using these blog posts. This is the best practice we're trying to encourage anyways, and should remove the circular dependency issue!
