### ISSUE TITLE
Custom 404 doesn't load on Cloudflare Pages

### ISSUE THREAD

**Issue by JG-devo** [withastro/astro#6177]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Cloudflare Pages is looking for a 404.html file to handle 404 responses, however, the production build of the final files includes a 404 folder with index.html inside. This seems to happen with SSG mode and dynamic routing.

I've tested this by going to domain.com/404/ and the page loads up on Cloudflare pages. Going to domain.com/404 goes back to the home page. I've also checked the build folder (/dist) and verified this result.

<img width="307" alt="Screenshot 2023-02-08 at 17 13 52" src="https://user-images.githubusercontent.com/67287800/217554203-18f12eb2-c236-443e-adaf-9ff9870df42d.png">

I've created a version of this bug with stackblitz linked below. Simply add /404/ to the end and try without i.e. /404

Thanks!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-daj2vt?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is a non-standard feature that some hosts like Netlify support. It is not necessarily supported by all hosts. You can likely configure Cloudflare to use that page for your 404. I couldn't tell you how to do that, however. But it's not something Astro controls.

**Comment by JG-devo** [comment]
> This is a non-standard feature that some hosts like Netlify support. It is not necessarily supported by all hosts. You can likely configure Cloudflare to use that page for your 404. I couldn't tell you how to do that, however. But it's not something Astro controls.

The bug isn't necessarily with Cloudflare or any host. If I create a 404.astro file directly, it automatically resolves to a 404.html file. Dynamic routing seems to put it in a folder.

**Comment by fcanmekikoglu** [comment]
setting assets.not_found_handling to "404-page" on wrangler.jsonc fixed the issue for me.

```json
{
    "$schema": "node_modules/wrangler/config-schema.json",
    "name": "mysitedotcom",
    "compatibility_date": "2025-04-06",
    "assets": {
        "directory": "./dist",
        "not_found_handling": "404-page", 
    }
}
```

**Comment by rogervera** [comment]
> "assets": {
>         "directory": "./dist",
>         "not_found_handling": "404-page", 
>     }

Thank you! For those who are interested here's a link to the docs about this: https://developers.cloudflare.com/workers/static-assets/#routing-behavior
