### ISSUE TITLE
Unsupported config.js file type for content collection schema

### ISSUE THREAD

**Issue by tschaub** [withastro/astro#6179]
### What version of `astro` are you using?

2.0.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Stackblitz

### Describe the Bug

When adding a `content/config.js` file to [define a schema](https://docs.astro.build/en/guides/content-collections/#defining-a-collection-schema) for a content collection, I see the following output:

```shell
09:16:39 AM [content] Unsupported file types found. Prefix with an underscore (`_`) to ignore:
- config.js
```

I am able to use the content collection, but it is not clear to me that the schema in the `content/config.js` file is being used.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fba5em?file=README.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks! We originally decided to not support anything other than `config.ts` while we worked through that more common use-case. I think it's probably safe to limit that restriction at this time though.

Of course, if you use a .js file here you are either going to need to configure a tsconfig with `allowJs: true`, *or* you will not get autocomplete when using `getCollection`, etc.

**Comment by matthewp** [comment]
Here's where it's documented that it should be supported: https://docs.astro.build/en/guides/content-collections/#defining-a-collection-schema

**Comment by mfrachet** [comment]
Sorry if I lack context here, but it seems that `config.js` is well working (I did not need to tweak my ts config in order to get the collection retrieved 🤔 )

Is this issue about removing the warning itself? Or am I missing something?

**Comment by MoustaphaDev** [comment]
@mfrachet I believe the issue is that currently only a `config.ts` file in the `src/content` directory is used by content collections to validate the frontmatter and generate types. Your `config.js` file is just ignored here.
