### ISSUE TITLE
Styles are rendered inside the body, instead of the header in certain combinations using slots

### ISSUE THREAD

**Issue by prototypa** [withastro/astro#6185]
### What version of `astro` are you using?

2.0.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Since **Astro** version **2.0.4** something changed that causes for certain uses of slots (https://docs.astro.build/en/reference/api-reference/#astroslotsrender), the main styles (link) are rendered inside tags in the body instead of in the header. This causes page speeds problems with CLS (cumulative shift).

You can check the problem in the following repository: https://github.com/prototypa/astro-styles-in-body-with-slots

Once the build is done, the result of the html page is the following:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  <body>
    <main>
      <section class="bg-slate-50">
        <div class="mx-auto text-center max-w-3xl px-4 py-8 md:py-16">
          <h1 class="text-4xl md:text-5xl font-bold leading-tighter tracking-tighter">Lorem ipsum lorem</h1>
          <p class="mt-4 text-xl text-gray-500">
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti
          </p>
          <div class="mt-4">
            <link rel="stylesheet" href="/_astro/good.857198b4.css" />
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
              ea commodo consequat.
            </p>
            <p class="mt-4">
              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
              laborum.
            </p>
          </div>
        </div>
      </section>
      <div class="text-center p-4">
        <a class="text-blue-500 underline" href="good">To good example »</a>
      </div>
    </main>
  </body>
</html>
```

In that example repository you can see how [`index.astro`](https://github.com/prototypa/astro-styles-in-body-with-slots/blob/main/src/pages/index.astro) is generated with styles incorrectly, however the page [`good.astro`](https://github.com/prototypa/astro-styles-in-body-with-slots/blob/main/src/pages/good.astro) resolves the styles ok, but doesn't use slots the way we used it in that demo's component: [_Widget.astro_](https://github.com/prototypa/astro-styles-in-body-with-slots/blob/main/src/components/Widget.astro)

We have done many tests and combinations before submitting this issue. We have not been able to resolve the issue. If you can help us please. Thank you.

---
PD: This problem has caused us to have the version of Astro fixed at **2.0.2**. in [**AstroWind** ](https://github.com/onwidget/astrowind)

### Link to Minimal Reproducible Example

https://github.com/prototypa/astro-styles-in-body-with-slots

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, there has been some changes here to prevent styles from rendering in the body. It sounds like it must have broke some other cases. Will prioritize getting this fixed.

**Comment by drumsta** [comment]
Hello,

I have encountered exactly the same issue and was about to open the issue.

I've prepared very minimal example to localize the issue, hope that will help you.

https://github.com/drumsta/astro-slot-render

Regards,

**Comment by matthewp** [comment]
@drumsta Yep, the user of `slots.render()` is the issue here. Working on a solution now. Thanks for the extra repro!

**Comment by matthewp** [comment]
PR up: https://github.com/withastro/astro/pull/6196

**Comment by drumsta** [comment]
Hi @matthewp !

Thank you for addressing the issue.

Unfortunately, the issue still exist in a more complicated scenario, which is the real case in my own project.

I've update the repo that you would be able reproduce the issue.

https://github.com/drumsta/astro-slot-render

Regards,
