### ISSUE TITLE
"Uncaught ReferenceError: globalThis is not defined" on older browsers (ie Chrome 68)

### ISSUE THREAD

**Issue by xo-vision** [withastro/astro#6186]
### What version of `astro` are you using?

2.09

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

WebOS 5.0, Windows 11 with Chrome 68

### Describe the Bug

Even when installing the default ASTRO cards example with no code modifications I get thi s error: Uncaught ReferenceError: globalThis is not defined at overlay.ts:140
	
It seems to be Vite related. I cannot use newer browsers as my app needs to be running on WebOS and Tizen, using older browsers (latest: Chrome 68).

Please note that the stackblitz link does not work, as stackblitz will not run on older browsers.

### Link to Minimal Reproducible Example

https://Stackblitz.com

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello, Vite requires minimum Chrome 87, as documented here: https://vitejs.dev/guide/build.html#browser-compatibility

This is not something we can really control from Astro. You may be able to circumvent this problem by using certain Vite plugins, but this falls outside of our scope. Sorry for the inconvenience
