### ISSUE TITLE
@astrojs/image turns an imported image into an object, but React still infers it as string

### ISSUE THREAD

**Issue by bytrangle** [withastro/astro#6187]
### What version of `astro` are you using?

2.0.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

In React, importing an image gives you a string value as documented [here](https://create-react-app.dev/docs/adding-images-fonts-and-files/).

However, when I added @astrojs/image integration, the imported value turns into an object which contains the following properties:
- src
- width
- height
- format

This is helpful, but the problem is that React still infers the type of this imported image as string. 

![typescript-identify-image-as-string](https://user-images.githubusercontent.com/28924121/217768874-5fcd9221-f3a0-4409-ab69-8886f58ae2ef.png)

If I use Typescript and I try to access the properties of this image, I'll get a Typescript error:

> Property `src` does not exist on type string

![property src does not exist on type string](https://user-images.githubusercontent.com/28924121/217768961-e503f294-97f2-4329-a7df-5ba3ec52fa23.png)

I wonder if there is a way to make React, or whatever tooling responsible recognize that the imported image is an object. Some users may not be aware of this and miss out on some helpful things they can do with the image.

## Reproduction

In the codesandbox below, I imported an image in the `Counter` component and `console.log` the value.

You can open the `dev` log and see its value.

Then comment out the image integration in `astro.config.mjs`. The value returns to a string.

Apologize if this is out of scope of this image integration.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/astro-react-image-70grz4

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello, you need to update your `env.d.ts`: https://docs.astro.build/en/guides/integrations-guide/image/#update-envdts

**Comment by bytrangle** [comment]
@Princesseuh Thank you for your help.

**Comment by klib19** [comment]
@Princesseuh I am still getting this error in .astro files after trying both methods in the link that you provided. Is it working for you in the latest version of Astro?
