### ISSUE TITLE
After installing Astro 2.0.8 vite issues

### ISSUE THREAD

**Issue by tifsolus** [withastro/astro#6193]
### What version of `astro` are you using?

2.0.8

### Are you using an SSR adapter? If so, which one?

custom Fastify Adapter

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

After installing astro@2.0.8, when I run astro build it fails with the following error:
Works properly with 2.0.7
I am using a cusom fastify adapter
astro:config:setup
 error   Cannot read properties of undefined (reading 'default')
  File:
    node_modules\vite\dist\node\chunks\dep-5e7f419b.js:61085:30
 for (const hook of config.getSortedPluginHooks('configureServer')) {    > 61085 |         postHooks.push(await hook(server));

### Link to Minimal Reproducible Example

https://stackbliz.com

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please provide a reproduction.

**Comment by tifsolus** [comment]
My bad, sure thing I will create a reproducible sample.
