### ISSUE TITLE
@astrojs: Import image via absolute path throws directory error

### ISSUE THREAD

**Issue by bytrangle** [withastro/astro#6194]
### What version of `astro` are you using?

2.0.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

## Problem

I have an Astro + React project. When I imported an image via the absolute path, it works fine.

```js
import image from "/astropaper-og.jpg"
```
Tis image is stored in `public/` directory. The `image` value here is exactly the absolute path: `astropaper-og.jpg`.

As soon as I added the @astrojs/image integration, without changing anything else, I got an error:

> Error: ENOENT: no such file or directory, open '/astropaper-og.jpg'

## Workaround

The only way to avoid the error is to import the image using the relative path to the current file.

```
import image from "../../public/astropaper-og.jpg";
```

It makes sense that `@astrojs/image` is unable to find the image, but I think having the site crashing down is somewhat confusing.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/astro-react-image-absolute-path-erhe7d?file=%2Fsrc%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
We don't recommend importing images from `public`, if you need to import an image it should be from `src`. Referring to images inside `public` should only be done through strings, ex: `<Image src="/thing.png" />`.

Nonetheless, this should work, as Vite (for some reason) allows it, which I admittedly find surprising...

**Comment by bytrangle** [comment]
@Princesseuh In the Astro docs for images, there's a recommendation:

> We recommend that you keep your images in [public/](https://docs.astro.build/en/guides/images/#public) or store them [remotely](https://docs.astro.build/en/guides/images/#using-images-from-a-cms-or-cdn) if you must use Markdown files.

I think storing images in `public/` does have a downside when the number of Markdown files increase and it takes time which image goes with which file. Plus you can't take advantage of path suggestion. And they are are served as-is without transformation.

But thanks for the response.
