### ISSUE TITLE
Missing triple slash typescript reference for "../.astro/types.d.ts" in basic example

### ISSUE THREAD

**Issue by ralacerda** [withastro/astro#6201]
### What version of `astro` are you using?

2.0.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Hello,

I created a new astro project using `create astro@latest`, and tried using the Content Collections.
I copied the example code from the docs, but I got the following typescript error:

```
Cannot find module 'astro:content' or its corresponding type declarations.
```

I noticed that the triple slash directive for the `"../.astro/types.d.ts"` path was missing, but was present in the other examples.

```
/// <reference path="../.astro/types.d.ts" />
```

So I believe either the triple slash is missing from the basic example (and other examples), or there should be something on the docs about it.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-z6rdsl?file=src%2Fcontent%2Fconfig.ts&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by BryceRussell** [comment]
The docs mention this here: https://docs.astro.build/en/guides/content-collections/#the-astro-directory

It should fix itself after running `astro dev` or `astro build`

**Comment by Princesseuh** [comment]
This is intended, those types are only generated when using content collections, which some projects might not be using

**Comment by jungaretti** [comment]
Astro's docs do not seem to mention `types.d.ts`:

- https://docs.astro.build/en/guides/typescript/#setup
- https://docs.astro.build/en/guides/content-collections/#setting-up-typescript

`astro build` ensures that `src/env.d.ts` contains the `types.d.ts` directive. If the line is missing, then `astro build` adds it. Is that intended?

If so, I think the docs should mention this behavior.

**Comment by aloon** [comment]
I solved it by modifying my package.json file adding 
` --remote`
after `astro build`
