### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by J-env** [withastro/astro#6204]
### What version of `astro` are you using?

2.0.8+

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/25259920/218060913-efe1e982-9742-416a-9c12-c64f39b0a0b4.png">

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mfrachet** [comment]
Hey there 👋🏻 .

Could you please provide a bit of context of what is going wrong for you? In the screenshot above, we only see the error, which is good, but we don't know what command you ran, or what your codebase looks like.

It s a bit hard to understand how to get in this specific state without steps to reproduce 😊 

Thanks 🙏🏻

**Comment by matthewp** [comment]
Yeah going to close, please open a new issue if you have steps and/or a reproduction.
