### ISSUE TITLE
Cloudflare mode directory outputs [[path]] to root instead of ./function

### ISSUE THREAD

**Issue by vampaz** [withastro/astro#6206]
### What version of `astro` are you using?

2.0.10

### Are you using an SSR adapter? If so, which one?

Cloudflare 6.1.2

### What package manager are you using?

npm 

### What operating system are you using?

mac/Linux

### Describe the Bug

Expected:
After build the file [[path]].js is saved at ./functions

Result:
After the build the file [[path]].js is saved at the root instead of the expected destination ./functions

When it started:
This was introduced when updating both astro and the cf adaptor(6.1.2) to the latest

How to reproduce:
`npm run build` in the provided stackblitz

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-qbsvtj?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mfrachet** [comment]
I think I m able to reproduce locally, but I don't know if it s a bug or not. Seems related to this LOC: https://github.com/withastro/astro/blob/main/packages/integrations/cloudflare/src/index.ts#L208

Also, adding the following assertion:

```js
	it.only('generates functions folder inside the project root', async () => {
		expect(await fixture.pathExists('../functions')).to.be.true;
		expect(await fixture.pathExists('../functions/[[path]].js')).to.be.true; // this one
	});
```

In https://github.com/withastro/astro/blob/main/packages/integrations/cloudflare/test/directory.test.js#L19 could safe guard this behaviour.

Also, on a side note, running `npm run build && npm test` in cloudflare folder end up generating the `[[path]].js` file as a sibling of `functions` (probably the behaviour you mention).

I should be able to fix it (let me know if someone else wants to try fixing this one)
