### ISSUE TITLE
postcss-preset-env plugin not working with tailwindcss

### ISSUE THREAD

**Issue by Ivluengo** [withastro/astro#6212]
### What version of `astro` are you using?

2.0.10

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Hi! I have a project with tailwind integrated (v 3.0.1) and I'm trying to add the `postcss-preset-env` plugin, but I can't find how to make it work. 

### I created a `postcss.config.js` file with this code:

```javascript
module.exports = {
  plugins: [
    require('postcss-preset-env')({ stage: 0 })
  ]
}
```

Then I have checked an error I'm having using nesting css (which you can do with preset-env) 

```error
[vite:css] Nested CSS was detected, but CSS nesting has not been configured correctly.
Please enable a CSS nesting plugin *before* Tailwind in your configuration.
See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting
```

### And then I tried to do as they tell:

```javascript
module.exports = {
  plugins: {
    'postcss-preset-env': { stage: 0, features: { 'nesting-rules': false } },
    'tailwindcss/nesting': {},
    tailwindcss: {}
  },
}
```

But nothing seems to work. I would love to have the `preset-env` plugin installed, so I can write new CSS code without a problem. I tried using it in a regular project without astro, and it works with the second piece of code. The nesting part I assume that tailwindcss/nesting plugins does it and with `postcss-preset-env` I tried to use for example `@custom-media` queries and it worked. But it does not in my astro project. It keeps yelling at me the same error that I need to enable a “nesting plugin” before tailwindcss. I asked before in the discord support channel, and @MoustaphaDev told me it's probably a bug. So here I am.

Thanks a lot for your help!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-igpmlu?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
The `postcss-preset-env` pacakge wasn't in the package.json. I installed it and it works now! Let me know if it works for you.

Got to that conclusion after installing tailwind manually, it threw a comprehensive error.

We should definitely consider not silencing errors here

**Comment by MoustaphaDev** [comment]
The `postcss-preset-env` package wasn't in the package.json. I installed it, changed the extension of the postcss config to `.cjs` (because of `type="module"` in package.json) and it worked!

If the issue persists, feel free to reopen.

**Comment by Ivluengo** [comment]
Hey!! It was only of that `.js` extension?? So sorry then. Thanks a lot for your help!
