### ISSUE TITLE
Misplacement of head content in nested .astro components rendered from content collection MDX.

### ISSUE THREAD

**Issue by angelokeirsebilck** [withastro/astro#6214]
### What version of `astro` are you using?

2.0.10

### Are you using an SSR adapter? If so, which one?

Vercel adapter but same problem in Node adapter

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

This repo uses vercel adapter but the same bug occurs when using node adapter.

Rendering nested .astro components misplaces the head links inside the body (right after where you import the nested component)

<img width="641" alt="image" src="https://user-images.githubusercontent.com/42614667/218161999-e0c9c466-f321-4b5d-8896-2853b3445a99.png">

First component in .mdx: https://github.com/angelokeirsebilck/mdx-collection-vercel-head-misplacement/blob/main/src/content/blog/bug.mdx?plain=1#L10

nested astro component: https://github.com/angelokeirsebilck/mdx-collection-vercel-head-misplacement/blob/main/src/components/blocks/home/HomeBanner.astro#L14

Live example: https://mdx-collection-vercel-head-misplacement.vercel.app/blog/bug/

### Link to Minimal Reproducible Example

https://github.com/angelokeirsebilck/mdx-collection-vercel-head-misplacement

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Fixed in https://github.com/withastro/astro/issues/6214

**Comment by matthewp** [comment]
You can try this out with:

```
npm install astro@next--headbody
```

**Comment by angelokeirsebilck** [comment]
Can confirm that this works
