### ISSUE TITLE
Cannot render the same slot twice

### ISSUE THREAD

**Issue by RealOrangeOne** [withastro/astro#6220]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When writing a layout and wanting to render the same `slot` twice, it's unable to. The first render works fine, but subsequent don't render at all.

Example:

```astro
---
import BaseLayout from "./BaseLayout.astro";
---
<BaseLayout>
  <slot />
  <slot />
</BaseLayout>
```

Passing the `name` prop explicitly doesn't change the effect.

### Link to Minimal Reproducible Example

See example above

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Closing as this is a little dated, please reopen with a reproduction.
