### ISSUE TITLE
When build, Could not resolve entry module

### ISSUE THREAD

**Issue by crownclownwl** [withastro/astro#6223]
### What version of `astro` are you using?

2.0.10

### Are you using an SSR adapter? If so, which one?

netlify

### What package manager are you using?

npm, yarn

### What operating system are you using?

Linux

### Describe the Bug

I added the alias configuration using the Astro website

in tsconfig.json 
`json
 {
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "jsx": "preserve",
    "skipLibCheck": true,
    "strictNullChecks": true,
    "baseUrl": ".",
    "paths": {
      "@components/*": ["src/components/*"],
      "@assets/*": ["src/assets/*"]
    }
  }
}
`
`yarn dev` noproblem，but `yarn build` is Error
Could not resolve entry module "@components/react/SelfIntroduction/index.jsx".

![image](https://user-images.githubusercontent.com/11539526/218301653-d8f58ef6-6398-4343-94b5-3777fbc013c4.png)

### Link to Minimal Reproducible Example

https://app.netlify.com/sites/incandescent-sprite-a55195/deploys/63e899edabe0154fa76b52f5

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by crownclownwl** [comment]
![image](https://user-images.githubusercontent.com/11539526/218301754-19edcaaa-e135-4e17-ae40-26969e18bc6c.png)

**Comment by crownclownwl** [comment]
this is my ts config
![image](https://user-images.githubusercontent.com/11539526/218301801-0f30044e-5742-46fa-b552-f596ebf087ad.png)

**Comment by crownclownwl** [comment]
I'll just change it to a relative path
eg:
![image](https://user-images.githubusercontent.com/11539526/218301954-a80f39e1-ea47-4869-991d-d03c0441cf55.png)
![image](https://user-images.githubusercontent.com/11539526/218301964-3e4a2abf-cd68-4afe-a497-11e962d96b59.png)

**Comment by MoustaphaDev** [comment]
I tried to reproduce this but I couldn't. Can you create a reproduction @crownclownwl

**Comment by crownclownwl** [comment]
> I tried to reproduce this but I couldn't. Can you create a reproduction @crownclownwl ?
Please look at it for me, This is My blog demo address:
https://github.com/crownclownwl/testAstroDemo

**Comment by matthewp** [comment]
@ematipico this one is complicated and probably related to our aliasing which is in `src/vite-plugin-config-alias/` and maybe how our build is consuming those in `src/core/build/static-build.ts`. Happy to chat about it.

**Comment by crownclownwl** [comment]
> @ematipico this one is complicated and probably related to our aliasing which is in `src/vite-plugin-config-alias/` and maybe how our build is consuming those in `src/core/build/static-build.ts`. Happy to chat about it.
yeah, I'd be honored， so:
Is the problem easy to solve? Is it a bug in the framework configuration? Or is there a problem with my project configuration?
Feel free to test it out in my demo: https://github.com/crownclownwl/testAstroDemo

**Comment by ematipico** [comment]
@matthewp This is a weird one:

> **Note**: the component has a `.tsx` extension but it gets imported using a `jsx`extension, I don't know if that's correct,

The component gets correctly aliased and resolved **when building the static content**, but it fails to be resolved during the building of the client code. Weirdly, the arguments passed to `this.resolve` function have the same values in both cases.

**Comment by crownclownwl** [comment]
I'm terribly sorry，This is my problem. Please forgive my newbie behavior！！！Thank you very much

**Comment by crownclownwl** [comment]
> @matthewp This is a weird one:
> 
> > Note: the component has a `.tsx` extension but it gets imported using a `jsx`extension, I don't know if that's correct,
> 
> The component gets correctly aliased and resolved **when building the static content**, but it fails to be resolved during the building of the client code. Weirdly, the arguments passed to `this.resolve` function have the same values in both cases.
> 
> @crownclownwl If you change
> 
> ```diff
> - import SelfIntroduction from '@components/react/SelfIntroduction/index.jsx'
> + import SelfIntroduction from '@components/react/SelfIntroduction/index.tsx'
> ```
> 
> It should work

I'm terribly sorry，This is my problem. Please forgive my newbie behavior！！！Thank you very much

**Comment by crownclownwl** [comment]
> @matthewp This is a weird one:
> 
> > Note: the component has a `.tsx` extension but it gets imported using a `jsx`extension, I don't know if that's correct,
> 
> The component gets correctly aliased and resolved **when building the static content**, but it fails to be resolved during the building of the client code. Weirdly, the arguments passed to `this.resolve` function have the same values in both cases.
> 
> @crownclownwl If you change
> 
> ```diff
> - import SelfIntroduction from '@components/react/SelfIntroduction/index.jsx'
> + import SelfIntroduction from '@components/react/SelfIntroduction/index.tsx'
> ```
> 
> It should work

10/5000

I forgot to change the file suffix
