### ISSUE TITLE
Raw text content produces TypeScript error ts(2304) in Visual Studio Code

### ISSUE THREAD

**Issue by ScriptRaccoon** [withastro/astro#6228]
### What version of `astro` are you using?

2.0.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows / macOS

### Describe the Bug

In Astro components I would like to be able to write paragraphs with curly braces. So that Astro does not treat this as dynamic content, we can pass the [is:raw](https://docs.astro.build/en/reference/directives-reference/#israw) directive to the container. This makes the Astro compiler happy, and the build looks as expected.

However, the TypeScript compiler in Visual Studio Code is not happy. When I write, say, { working }, it says `Cannot find name 'working'.ts(2304)`.

![not-working](https://user-images.githubusercontent.com/54458975/218338905-78c0bc1c-3249-41b3-92ce-4fb8d2883b48.jpg)
 
I have tried to adjust `tsconfig.json` to `"extends": "astro/tsconfigs/base"`, but this did not solve the issue.

One can put `// @ts-nocheck` in the frontmatter of the Astro component. But this is a bad workaround, as it disables TS in the whole component.

The issue cannot be reproduced on Stackblitz, since there apparently no type checking is happening.

Related question: can I configure Astro so that only **double curly braces** are used for dynamic content? This would probably also solve my problem.

### Visual Studio Code Version

1.75.1

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jbqp6y

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
This issue was [fixed a while ago](https://github.com/withastro/language-tools/issues/285) though the fixes haven't landed in the release version, yet. In the meanwhile, you can switch to the pre-release version.
