### ISSUE TITLE
Mode is 'development' in config file when running astro build

### ISSUE THREAD

**Issue by kvsm** [withastro/astro#6241]
### What version of `astro` are you using?

2.0.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Running `astro build` and attempting to use `import.meta.env.MODE` in `astro.config.mjs` per the documentation at https://docs.astro.build/en/guides/configuring-astro/#environment-variables does not work as expected.

Expected: Mode is set to 'production'

Actual: Mode is set to 'development'

### Link to Minimal Reproducible Example

https://github.com/kvsm/config-mode-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ElianCodes** [comment]
have you used `MODE=production pnpm run build`?

**Comment by kvsm** [comment]
> have you used `MODE=production pnpm run build`?

Just tested, `import.meta.env.MODE` is still development.  Currently working around it by using `process.env.NODE_ENV`, which gives the expected result.

**Comment by iShelar** [comment]
> > have you used `MODE=production pnpm run build`?
> 
> Just tested, `import.meta.env.MODE` is still development. Currently working around it by using `process.env.NODE_ENV`, which gives the expected result.

Are you trying to use `import.meta.env.MODE` in astro.config.ts?

**Comment by rishi-raj-jain** [comment]
@kvsm I think astro's config isn't the right place to test this or is it? I think per the current logic that's set in while building the app after digesting the config so shall be available in the pages. Validating my hypothesis

**Comment by rishi-raj-jain** [comment]
<img width="1512" alt="Screenshot 2023-03-13 at 3 24 07 PM" src="https://user-images.githubusercontent.com/46300090/224667388-255926f5-a691-4ce8-b732-d0ab91d2d1a5.png">

Yeah so in your current setup, if you use the value inside but not in the config, it'll reflect the right values.

**Comment by elevatebart** [comment]
I have a blocking issue with this: 
The `site` config "has" to be different between staging and prod. If not:
- the canonical will be broken links
- sitemaps will probably be wrong

How do you set up 2 different site urls? 
2 config files?

**Comment by kvsm** [comment]
> @kvsm I think astro's config isn't the right place to test this or is it? I think per the current logic that's set in while building the app after digesting the config so shall be available in the project but not in the config. Validating my hypothesis, just a sec.

That may be the case, but that's not what the documentation I linked to suggests.

**Comment by bluwy** [comment]
Bumping this down to a p2 since I don't think `import.meta.env.*` should generally work in config files. The documentation does recommend so, but it relies on a Vite feature whereas the goal is to only use Vite to transpile TS to JS.

Using `process.env.NODE_ENV`, or if Astro supports a config function syntax one day that passes `mode` would be more predictable.

**Comment by elevatebart** [comment]
One could also have 2 separate config files since the build process is called from the server. 

instead of running 

```
astro build
```

run this command

```
astro build --config astro.config.build.ts
```

and import one config in the other updating what you would like to import.
