### ISSUE TITLE
Astro project encoding issue (PageSpeed/Lighthouse)

### ISSUE THREAD

**Issue by JesseKoldewijn** [withastro/astro#6242]
### What version of `astro` are you using?

2.0.11

### Are you using an SSR adapter? If so, which one?

None (static deployment to Vercel)

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

PageSpeed test throws encoding error while either a charset or content-type meta tag is present.

Github repo is linked below and you can check the pagespeed check with the link below (points to my vercel project url with this test)
[Pagespeed link](https://pagespeed.web.dev/report?url=https%3A%2F%2Fshiftcode-eu.vercel.app%2F)

### Link to Minimal Reproducible Example

https://github.com/ShiftCodeEU/shiftcode.eu

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
What is the bug you are reporting?

**Comment by JesseKoldewijn** [comment]
According to pagespeed (and like-sorts) scans the encoding of a build page seems to be incorrect in the sense that it cant be metered by a performance scan like pagespeed.

My previous description: "PageSpeed test throws encoding error while either a charset or content-type meta tag is present."
Browser compatibility response from PageSpeed: "Properly defines charset Error!
A character encoding declaration is required. It can be done with a <meta> tag in the first 1024 bytes of the HTML or in the Content-Type HTTP response header."

The issue in my case is that I do have the correct meta tag at the right top of my document head so I dont understand what the issue would be.

**Comment by matthewp** [comment]
I don't know what would cause this either, but it doesn't sound like an Astro bug. Astro does not add meta tags to your page or set HTTP headers in your static site.

This might be of some help: https://stackoverflow.com/questions/12661919/google-page-speed-says-avoid-meta-tag-for-char-set-but-i-havent-used-a-meta-ta

**Comment by JesseKoldewijn** [comment]
I've seen that thread as well but that issue mentioned in there is not the same as what I run into. It seems like there is an encoding issue during the build process which does involve astro.

**Comment by JesseKoldewijn** [comment]
I have both tested with and without the encoding meta tag(s) and bots still break when inspecting the page. Since this is quite bad SEO wise I don't see how you can close this as completed like this to be honest.

**Comment by JesseKoldewijn** [comment]
When I run a check over the raw html that the astro compiler spits out I get the following html markup validation errors:
- Element “style” not allowed as child of element “body” in this context.
- Malformed byte sequence: “a9”. At line 60, column 533 Code Extract:

**Comment by JesseKoldewijn** [comment]
It seems to have the malformed byte sequence on the following snippet (which is compiled down by astro from a client loaded react component):
```html
<footer class="footer footer-center mb-2 rounded-xl bg-base-100 p-10 text-base-content"><div class="grid grid-flow-col gap-4"><a href="[#](https://shiftcode-eu.vercel.app/#)" class="link-hover link">About us</a><a href="[#](https://shiftcode-eu.vercel.app/#)" class="link-hover link">Projects</a><a href="[#](https://shiftcode-eu.vercel.app/#)" class="link-hover link">Contact</a><a href="[#](https://shiftcode-eu.vercel.app/#)" class="link-hover link">Open-Source</a></div><div><div class="grid grid-flow-col gap-4"><a href="[#](https://shiftcode-eu.vercel.app/#)"><span>socialLink 1</span></a><a href="[#](https://shiftcode-eu.vercel.app/#)"><span>socialLink 2</span></a><a href="[#](https://shiftcode-eu.vercel.app/#)"><span>socialLink 3</span></a></div></div><div><p>Copyright © <!-- -->2023<!-- --> | All right reserved by ShiftCode Developments</p></div></footer>
```

**Comment by JesseKoldewijn** [comment]
I also don't really understand why the copyright icon get compiled from an html symbol to the actual tag itself. As far as I know this shouldn't happen because saw icons like those can behave off on different browsers compared to the build in html symbols.

**Comment by matthewp** [comment]
What HTML validator are you using? Note that a lot of those are very dated and wrong. The browser doesn't actually care about a lot of the things it warns against.

I would reduce this down until you see PageSpeed not give you that warning. Go for a barebones HTML page with just `<html><head><meta charset="utf-8"></head><body></body></html>` and then gradually add back more stuff until the error happens again. Then you'll know the root cause.

**Comment by JesseKoldewijn** [comment]
Aight, good idea! Will do that. Thanks for the suggestion.👍

**Comment by JesseKoldewijn** [comment]
nice, every metrics bot still keeps having issues with reading the right file encoding. Even though the http encoding type and html char set are specified correctly...

**Comment by matthewp** [comment]
did you reduce it all the way down? I would also try completely removing Astro from the equation. Just literally create an HTML file that looks like this: `<html><head><meta charset="utf-8"></head><body></body></html>`

**Comment by JesseKoldewijn** [comment]
I've throw the generated html, css & js with basic html + react (using vite) with the same react components I use in my astro project without issues. So its either an issue within the compile step astro goes through or within my astro page and/or layout. But since this project is quite bare and the astro bits about the project are basically snippets from you guys's docs I dont think the issue would lie within that.
