### ISSUE TITLE
Pages do not update when making changes to remark or rehype plugins

### ISSUE THREAD

**Issue by johnzanussi** [withastro/astro#6245]
### What version of `astro` are you using?

2.0.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The dev server does not automatically pick up and apply changes to Markdown/MDX output when working on local remark or rehype plugins.

The dev server sees that a change has been made to the remark plugin, but no changes are reflected in the browser. This isn't a problem with HMR, as not even a page refresh triggers the change.

A shutdown and restart of `astro dev` is needed to see the changes. 

```js
// astro.config.mjs
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';

import sitemap from '@astrojs/sitemap';

import remarkTest from './src/utils/remark/remark-test';

// https://astro.build/config
export default defineConfig({
	site: 'https://example.com',
	integrations: [mdx(), sitemap()],
	markdown: {
		remarkPlugins: [
			remarkTest,
		]
	}
});
```

```js
// src/utils/remark/remark-test.js
const customPropValue = "foo";

export default function remarkTest() {
  return function (_, file) {
    file.data.astro.frontmatter.customProp = customPropValue;
  };
}
```

Changes made to `remark-test.js` are recognized by the dev server as seen in the terminal output but the changes aren't reflected in the output.

```sh
[astro] update /src/utils/remark/remark-test.js
```

## Reproduce
The linked [CodeSandbox](https://codesandbox.io/p/sandbox/friendly-roman-tgeeh5?on=codesandbox&file=%2Fsrc%2Futils%2Fremark%2Fremark-test.js&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A1%7D%5D) can be used to reproduce the issue.
1. Start the dev server if it isn't already started
2. Open `src/utils/remark/remark-test.js`
3. Change the value of the `customPropValue` on line 1.
4. Save the file.

### Actual Result
`astro dev` recognizes the changes to `remark-test.js` but the preview displays the value of `customPropValue` before the file was saved.

### Expected Result
`astro dev` recognizes changes to `remark-test.js` and the preview displays the new value of `customPropValue`.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/friendly-roman-tgeeh5?on=codesandbox&file=%2Fsrc%2Futils%2Fremark%2Fremark-test.js&selection=%5B%7B%22endColumn%22%3A29%2C%22endLineNumber%22%3A1%2C%22startColumn%22%3A26%2C%22startLineNumber%22%3A1%7D%5D

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
+1 I know this is an issue from my own work on custom remark plugins. Integrations have the ability to add watch files — https://docs.astro.build/en/reference/integrations-reference/#addwatchfile-option — so users can manually add things that should restart the dev server. Wonder if we can improve this automatically though?

**Comment by johnzanussi** [comment]
> +1 I know this is an issue from my own work on custom remark plugins. Integrations have the ability to add watch files — https://docs.astro.build/en/reference/integrations-reference/#addwatchfile-option — so users can manually add things that should restart the dev server. Wonder if we can improve this automatically though?

I tried using a simple inline integration that called `addWatchFile` with my remark plugin. This got me some of the way there as the dev server restarted but I still needed to manually refresh the entire page. 

I also dug into the HMR code. This is going to be a tricky one to solve because the remark plug-ins aren’t in the import tree of the mdx file. And this isn’t a limitation of something Astro is or isn’t doing. 

That’s where I stopped digging and opened this ticket.

**Comment by Adam-Collier** [comment]
+1 to this! I ran into this today and it would make a huge difference having this updating the page automatically instead of having to reload the whole page

**Comment by bluwy** [comment]
I don't think this is a bug. When we load the Astro config file, we only get its return value. We don't know which files this config file depends on to trigger a restart, except if the edit actually happen on the config file itself.

The `[astro] update /src/utils/remark/remark-test.js` shows that Astro sees the file being updated, but since we don't know the dependencies the config file rely on, we don't know if it's safe to trigger a restart.

I think this will be a separate feature request to have loading config files also track its dependencies so we can correctly trigger a restart. Vite was able to achieve this by manually loading the config file with esbuild (which esbuild returns a list of deps), it would be hard to port that to Astro without replicating it though.

Closing this one for now.
