### ISSUE TITLE
Support aliases in frontmatter (for layouts)

### ISSUE THREAD

**Issue by millette** [withastro/astro#6255]
### What version of `astro` are you using?

2.0.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

GNU Linux

### Describe the Bug

I'm using mdx pages (not content) with aliases configured in tsconfig.json. I tried to use an alias for the layout as seen here <https://github.com/withastro/astro/issues/397#issuecomment-1193245056> but it doesn't work.

### Link to Minimal Reproducible Example

https://0wkiec-3000.preview.csb.app/p2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please provide a code example (such as a Stackblitz), not just your site.

**Comment by millette** [comment]
@matthewp Oups, I provided the wrong link, here's the proper codesandbox:

<https://codesandbox.io/p/sandbox/lingering-water-0wkiec?on=codesandbox&file=%2Fsrc%2Fpages%2Fp2.md&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A1%7D%5D>

Hmm, actually this might be a better link: <https://codesandbox.io/s/lingering-water-0wkiec> - I'm not really used to working with _csb_.

**Comment by millette** [comment]
Hello again @matthewp 

Compare p2 and p3 for example:
https://codesandbox.io/p/sandbox/lingering-water-0wkiec?file=%2Fsrc%2Fpages%2Fp2.md

Hope this issue can be reopened since there's a full example available.

**Comment by olivierdelomez** [comment]
@millette you need to wrap the path in quotes :)

`
---
layout: "@layouts/my-layout.astro"
---
`
