### ISSUE TITLE
Cannot create project

### ISSUE THREAD

**Issue by pandasoli** [withastro/astro#6256]
### What version of `astro` are you using?

0.0.0

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm, yarn, pnpm

### What operating system are you using?

Linux - Ubuntu 22.04.1 LTS

### Describe the Bug

I cannot initialize a project with any package manager.

My versions are:
- Node: `v18.14.0`
- NPM: `9.3.1`
- Yarn: `1.22.19`
- PNPM: `7.27.0`

**NPM**
![image](https://user-images.githubusercontent.com/76575902/219173187-606504b4-cdab-4d93-992b-b7b382e13e7b.png)

**Yarn**
![image](https://user-images.githubusercontent.com/76575902/219173274-05c632f0-fdd7-4dcc-b897-f891b5c027e4.png)

**PNPM**
![image](https://user-images.githubusercontent.com/76575902/219173833-3b2fbcb4-f9c3-45c2-b5bf-35d8f8dfde47.png)

### Link to Minimal Reproducible Example

.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sajarin** [comment]
@pandasoli I ran into this error but was able to create the project after using astro@3.0.0 and node version v16.19.0

**Comment by pandasoli** [comment]
Ah yeah, I fixed the problem.

I was having problems with the internet connection.  
It was working normally, but strangely some things didn't work.

Among them:
- Translator of a Samsung cell phone; and
- HBO application.

And by coincidence I had to reconnect the wi-fi router and so everything went back to work.  
Thank you @sajarin for trying to help <3
