### ISSUE TITLE
markdown translate to html failed

### ISSUE THREAD

**Issue by JonasCaptain** [withastro/astro#6260]
### What version of `astro` are you using?

2.0.12

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

window

### Describe the Bug

This text fails to be parsed
`
![alt text](/src/images/random.jpeg 'Logo Title Text 1')
`
From Markdown document sixth.md on 'https://astro.build/themes/details/astro-boilerplate/'

### Link to Minimal Reproducible Example

https://astro.build/themes/details/astro-boilerplate/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I'd suggest reporting this to https://github.com/ixartz/Astro-boilerplate, the template is still using Astro 1.0 beta, which needs to be updated.
