### ISSUE TITLE
If you nest two Solid islands into each other, the nested one is mounted twice

### ISSUE THREAD

**Issue by alexander-lozovsky** [withastro/astro#6263]
### What version of `astro` are you using?

2.0.12

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When you render two Solid islands nested into each other, the nested one is mounted twice.

So in case you have something like this:
```
<Wrapper client:idle>
  <NestedComponent client:idle>
    <p>Hello world</p>
  </NestedComponent>
</Wrapper>
```

`NestedComponent` runs twice in the browser, which means that if you run some logic inside `onMount`, it runs twice.

See the attached stackblitz: click "Open in New Tab" and observe "NestedComponent" logged twice in the console

Same composition with React components works as expected https://stackblitz.com/edit/github-tgt7ck?file=src/pages/index.astro

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gcp42c?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by idiglove** [comment]
![image](https://user-images.githubusercontent.com/29911508/220032330-b2a5eada-b4af-4677-b720-0d6f51d55d20.png)
I don't see "Nested Component" being logged twice

**Comment by alexander-lozovsky** [comment]
@idiglove you're looking at the dev server logs, please check the browser logs

![image](https://user-images.githubusercontent.com/20779617/220038327-7303ebde-8f8d-4ba2-a4e8-178e09db397f.png)
![image](https://user-images.githubusercontent.com/20779617/220038111-349baf96-290d-4d70-b535-cc213bbc651c.png)

**Comment by SerekKiri** [comment]
Problem might be with a fallback to `load` event from `requestIdleCallback` as that what astro does -> https://docs.astro.build/en/reference/directives-reference/#clientidle

`window.requestIdleCallback` is not supported on safari
<img width="300" alt="image" src="https://user-images.githubusercontent.com/29735836/221299048-15ffe9be-aa1b-4215-8135-576fff44925c.png">

Question though as there is no `load` being used but a `setTimeout` instead if I'm looking into proper places. 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/29735836/221300003-bfb621d2-cbad-433d-a7de-0c655bd1bc1e.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/29735836/221299534-bfb62087-b0ef-4eca-a361-8d357429eb3d.png">

I might dig a bit 🤔

**Comment by SerekKiri** [comment]
Also docs update for `client:idle` was 10 months ago and 8 months ago for `requestIdleCallback` so probably docs should be updated as well 👍🏼 
<img width="319" alt="image" src="https://user-images.githubusercontent.com/29735836/221303780-57bb7a96-0b09-4e63-9dc6-ebd689fcf761.png">

**Comment by SerekKiri** [comment]
@alexander-lozovsky did you test that in a production mode?

**Comment by alexander-lozovsky** [comment]
@SerekKiri yes, it happens in both SSR and SSG builds

**Comment by SerekKiri** [comment]
@alexander-lozovsky could you check if your project will work properly with changes added by @matthewp in the PR mentioned above?

**Comment by bluwy** [comment]
I haven't tested yet, but https://github.com/withastro/astro/pull/7370 might also help with this.

**Comment by bluwy** [comment]
I ran the repro and updated Astro to latest and it seems to be fixed now.
