### ISSUE TITLE
`create astro -- --template`  passing non-existent folder arg.

### ISSUE THREAD

**Issue by liruifengv** [withastro/astro#6275]
### What version of `astro` are you using?

0.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Use `npm create astro@latest test-project -- --template empty` passing non-existent folder arg.

Show template copied but the project is empty.

Expectation： Throw a 404 error.

This appears to be the result of an upstream repository https://github.com/unjs/giget

### Link to Minimal Reproducible Example

None

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Not sure what I'm getting wrong, but running the same exact command give me a 404
![image](https://user-images.githubusercontent.com/81974850/219647414-f3b88f6e-7ce2-48b1-980e-be52ba498af3.png)

**Comment by MoustaphaDev** [comment]
Ah I can't read now, so it's related to #6276

**Comment by liruifengv** [comment]
Yes. I can still reproduce the question.

I read the source code of the upstream repository and it seems to be based on the HTTP code 404 returned by GitHub.

But GitHub doesn't return 404 for non-existent directories of the repository.

I don't know~

**Comment by natemoo-re** [comment]
This has already been fixed in a more recent version of `create-astro`!
