### ISSUE TITLE
[Netlify] setting external_node_modules crashes app

### ISSUE THREAD

**Issue by jamesarosen** [withastro/astro#6292]
### What version of `astro` are you using?

2.0.12

### Are you using an SSR adapter? If so, which one?

@astrojs/netlify@2.1.2

### What package manager are you using?

pnpm@7.27.0

### What operating system are you using?

MacOS

### Describe the Bug

My app has been running fine on Netlify. Recently, I noticed the following warning in their build log:

> ❯ The following Node.js modules use dynamic expressions to include files:
>    - astro
> ​
>   Because files included with dynamic expressions aren't bundled with your serverless functions by default,
  this may result in an error when invoking a function. To resolve this error, you can mark these Node.js
>   modules as external in the [functions] section of your `netlify.toml` configuration file:
> ​
>   [functions]
>     external_node_modules = ["astro"]
> ​
>   Visit https://ntl.fyi/dynamic-imports for more information.

I tried setting that in my app. Netlify built the branch without warning, but visiting the preview results in

### This function has crashed

An unhandled error in the function code triggered the following message:

```
Runtime.ImportModuleError - Error: Cannot find module 'astro/app' Require stack: - /var/task/apps/www/.netlify/functions-internal/entry.js - /var/task/entry.js - /var/runtime/index.mjs
```

#### Stack trace

```
Runtime.ImportModuleError: Error: Cannot find module 'astro/app'
Require stack:
- /var/task/apps/www/.netlify/functions-internal/entry.js
- /var/task/entry.js
- /var/runtime/index.mjs
    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)
    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)
    at async start (file:///var/runtime/index.mjs:1200:23)
    at async file:///var/runtime/index.mjs:1206:1
```

See also https://discord.com/channels/830184174198718474/1063063360964415519

### Link to Minimal Reproducible Example

https://github.com/eostrom/astro-image-netlify-ssr/blob/main/netlify.toml

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Yeah I'm not sure why this warning is present when deploying to Netlify since it is incorrect. You _do_ need to bundle `astro` with your deployment.

**Comment by matthewp** [comment]
Sorry you ran into this issue! Can you try again after upgrading your dependencies? I was able to get it working with:

```json
  "dependencies": {
    "@astrojs/image": "^0.16.2",
    "@astrojs/netlify": "^2.2.0",
    "astro": "^2.1.7"
  }
```

**Comment by jamesarosen** [comment]
I still get "This function has crashed" when viewing the app. You can see the preview app [here](https://641f323d7ce587000888b8dd--thunderous-bubblegum-8bc069.netlify.app/).

My dependencies:
```
"dependencies": {
	"@astrojs/netlify": "^2.2.0",
	"@astrojs/tailwind": "^3.1.1",
	"@sentry/browser": "^7.45.0",
	"@sentry/tracing": "^7.45.0",
	"astro": "^2.1.7",
	"content-security-policy-builder": "^2.1.1",
	"tailwindcss": "^3.2.7"
}
```

**Comment by jamesarosen** [comment]
I'm debugging this in [this demo repo](https://github.com/jamesarosen/netlify-astro-external-demo)

The [first commit](https://github.com/jamesarosen/netlify-astro-external-demo/commit/a79064105634b910d36d7633f96445b2d47232b2) (which doesn't have an `astro.config.cjs` file) [works fine](https://645e742c045969126285247f--quiet-babka-445d2b.netlify.app/).

But when I [add this](https://github.com/jamesarosen/netlify-astro-external-demo/commit/77401163fdf1bf79362e9cee30f1967ce19cc5fb):

```js
import { defineConfig } from 'astro/config'
import netlify from '@astrojs/netlify/functions'

// https://astro.build/config
export default defineConfig({
  output: 'server',
  adapter: netlify(),
})
```

the [app crashes](https://645e755ca1884a0008e3063b--quiet-babka-445d2b.netlify.app/).

**Comment by matthewp** [comment]
`@astrojs/image` has been removed from Astro. You should begin migrating over to `astro:assets` instead which is our Image component going forward. I'm not sure if your issue is related to using this package or not. If you can reproduce using `astro:assets` then please file a new issue. Thank you!

**Comment by teddybee** [comment]
@jamesarosen I have the same problem with output: "static". There is no extra @astrojs/image for astro.
