### ISSUE TITLE
TailwindCSS in mdx component is ignored if parent component never uses TailwindCSS classes.

### ISSUE THREAD

**Issue by yukukotani** [withastro/astro#6302]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

For example, think about `MdxComponent.mdx` with the code below.

```mdx
<span class="text-red-500">use tailwind class in **mdx** component</span>
```

When the parent component is an Astro component which never uses TailwindCSS classes, the style won't be applied.

```astro
---
import MdxComponent from "../components/MdxComponent.mdx"
---

<MdxComponent /> in Astro page. No directly usage in this page.
```

Other cases below are working well.

### 1. The parent component is an Astro component and it uses TailwindCSS classes.

```astro
---
import MdxComponent from "../components/MdxComponent.mdx"
---

<div class="text-red-500">directly use tailwind class in Astro page</div>

<div>
  <MdxComponent /> in Astro page
</div>
```

### 2. The parent component is a MDX component and it never uses TailwindCSS classes.

```mdx
import MdxComponent from '../components/MdxComponent.mdx';

<div>
  <MdxComponent /> in mdx page
</div>
```

### 3. The parent component is a MDX component and it uses TailwindCSS classes.

```mdx
import MdxComponent from '../components/MdxComponent.mdx';

<div class="text-red-500">directly use tailwind class in mdx page</div>

<div>
  <MdxComponent /> in mdx page
</div>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-j64f3s?file=src/pages/astro-indirect.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ElianCodes** [comment]
What does your Tailwind config look like?

You'll probably have to add and include the .mdx extension in the content section of the config

**Comment by ElianCodes** [comment]
Oops, nevermind above, I see your config is valid in the example 🤦‍♂️

**Comment by MoustaphaDev** [comment]
This is probably related to https://github.com/withastro/astro/issues/6225, when you have another element in the page, things works as expected.

**Comment by jacobdalamb** [comment]
Can this issue be closed?

**Comment by bluwy** [comment]
Yeah I'll close this in favour of https://github.com/withastro/astro/issues/6225. Further improvements can be tracked at https://github.com/withastro/roadmap/discussions/541

**Comment by mleister97** [comment]
@bluwy I don't quite understand why this issue was closed. Is there any workaround or how can one ensure that even classes used in a .mdx file or even classes used conditionally in an astro file are included?

**Comment by antick** [comment]
This is still not fixed. I am also facing the same issue. Not sure why they keep closing this and other issues talking about this particular problem.
