### ISSUE TITLE
importing images from src assets to use as html image source no longer works - sets src=[object Object]

### ISSUE THREAD

**Issue by scottaw66** [withastro/astro#6315]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The following code results in a 404 instead of an image because the src becomes [object Object] instead of the actual url for the final image asset location.

```
---
import logo from "../images/site-header.svg";
---

<a href="/"><img class="header-image" src={logo} alt="logo" /></a>
```

Result is this:

```
<img class="header-image astro-3EF6KSR2" src="[object Object]" alt="logo">
```

![CleanShot 2023-02-20 at 00 37 43@2x](https://user-images.githubusercontent.com/7348442/220054549-6e2d79ea-ce96-4b0e-89f3-5eded7102f42.png)

### Link to Minimal Reproducible Example

https://github.com/scottaw66/sierraalfawhiskey

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bloycey** [comment]
It looks like this has to do with the `sharp` library you're using. If I comment out the sharp image integration in `astro.config.mjs` everything seems to work fine. 

When using `sharp` you just need to do `logo.src` instead of `logo` and I think that solves your issue.

**Comment by scottaw66** [comment]
Disregard, I just need to reference the object property "src". I started to try this when I saw it was returning an object but didn't see that property in autocomplete so I stopped before actually testing it... 🤦‍♂️

**Comment by klib19** [comment]
@scottaw66 When using typescript, I get the following error. Is there something I can do about this?

Property 'src' does not exist on type 'string'. ts(2339)
Property 'height' does not exist on type 'string'. ts(2339)
Property 'width' does not exist on type 'string'. ts(2339)

**Comment by scottaw66** [comment]
> @scottaw66 When using typescript, I get the following error. Is there something I can do about this?
> 
> Property 'src' does not exist on type 'string'. ts(2339) Property 'height' does not exist on type 'string'. ts(2339) Property 'width' does not exist on type 'string'. ts(2339)

Might want to post in the Astro discord support forum. Not sure without seeing what you're doing, but I'm pretty ignorant about Typescript still

**Comment by sebdybowski** [comment]
I am still experiencing that issue
