### ISSUE TITLE
Astro.slots.render() makes the link tag be inserted in the body at build time

### ISSUE THREAD

**Issue by tetracalibers** [withastro/astro#6318]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm, yarn

### What operating system are you using?

Mac

## Summary

If I use `Astro.slots.render('default')` to extract the slots and `set:html` to display them, the CSS `link` tags extracted at build time will be inserted within the `body` tag.

```astro
---
const content = await Astro.slots.render('default')
---

<Fragment set:html={content} />
```

When displayed using the `slot` tag, the CSS is inserted within the `head` tag.

```astro
<slot />
```

This problem occurs when an `astro build` is performed.
（When `astro dev` is executed, both cases are normal.）

## Demo

After viewing it in a browser, open the developer tools and see if the `link` tag is in the `body` tag or in the `head` tag.

### use `Astro.slots.render('default')`

- https://tetracalibers.github.io/astro-slot-bug-test/slots-render/

The `link` tag is inserted within the `body` tag.

<img width="563" alt="use-astro-slots-render" src="https://user-images.githubusercontent.com/92695929/220084763-b02e66a4-e1ba-4c32-b500-2535a0ef22b0.png">

### use `<slot />`

- https://tetracalibers.github.io/astro-slot-bug-test/slot-tag/

The `link` tag is inserted within the `head` tag.

<img width="563" alt="use-slot-tag" src="https://user-images.githubusercontent.com/92695929/220084934-736dcb0d-e2b3-497a-b2c9-b237a0913dcf.png">

## Expected Results

The `link` tag that loads the CSS file should be placed within the `head` tag.

### Problems with initial site display

The placement of the `link` tag within the `body` tag delays the loading of the CSS file and disrupts the initial display of the site.

### Problems with `astro-icon` package's `Sprite` feature

The internal implementation of `Sprite.Provider` in [astro-icon](https://github.com/natemoo-re/astro-icon) uses `Astro.slots.render('default')`.

- https://github.com/natemoo-re/astro-icon/blob/main/packages/core/lib/SpriteProvider.astro

Users of astro-icon's sprite functionality will have problems with initial display turbulence.

- https://github.com/natemoo-re/astro-icon/issues/83

### Link to Minimal Reproducible Example

https://github.com/tetracalibers/astro-slot-bug-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, sorry about this. We've encountered a few of these types of bugs and have fixed them, there must still be some edge cases that are missing.

I now have an idea for a better fix that *should* work more universally.

**Comment by wulinsheng123** [comment]
> Thanks, sorry about this. We've encountered a few of these types of bugs and have fixed them, there must still be some edge cases that are missing.
> 
> I now have an idea for a better fix that _should_ work more universally.

Could you share your idea? Because I want to fix it if that is in my field.

**Comment by matthewp** [comment]
@wulinsheng123 I actually realized that the idea I had *wouldn't* fix it. Layouts and head propagation are the problem here. I'm working on this issue now, though.

**Comment by matthewp** [comment]
Pretty sure I know what the problem is here. Should be an easy fix once I get a test set up.

**Comment by matthewp** [comment]
@tetracalibers I just want to shout you out for doing a fantastic job at providing a reduced example.
