### ISSUE TITLE
Kodemo integration breaking Astro

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#6321]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm@8

### What operating system are you using?

macOS@latest

### Describe the Bug

I'm trying to use [Kodemo](kodemo.com/docs/player) like a normal React component, but it seems not working.

I'm pretty sure it's on Kodemo's side since i've already [reported some weird behavior](https://github.com/kodemoapp/player/issues/1) but at least, even tho not optimal it works on CRA, so i guess it should work here too.

My knowledge of the react integration is very poor, so I can't investigate further on my own. Happy to receive pointers and continue the digging if necessary.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4fly4m?file=src/components/ReactComponent.jsx,src/pages/index.astro&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by y-nk** [comment]
**Small update:** 

I've noticed this: `(node:6) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.` in the console, and surely when patching node_modules by adding the type, the warning disappears. I was thinking to try [vite-plugins-commonjs](https://github.com/originjs/vite-plugins/tree/main/packages/vite-plugin-commonjs) but there's no `plugins` options exposed in Astro's config.

I've added a couple of cases in the stackblitz to try to investigate further and _it seems_ to be on Astro side as the module is undefined when it should not be.

**Comment by bluwy** [comment]
The `"type": "module"` error is because it's not published right: https://publint.dev/@kodemo/player@0.3.2

But also after fixing that as you mentioned, the error still persists. When running this purely in node.js,

```js
// test.mjs
import { KodemoPlayer } from "@kodemo/player";
console.log(KodemoPlayer);
```

It fails with:

```
file:///Users/bjorn/Work/repros/astro-kodemo/node_modules/.pnpm/@kodemo+player@0.3.2_du7yz5f23cngwv65h7jru7qe7y/node_modules/@kodemo/player/dist/kodemo-player.es.js:3360
`, ik = YP, rk = MP, ok = Z(DP)`
                          ^

TypeError: Z is not a function
    at file:///Users/bjorn/Work/repros/astro-kodemo/node_modules/.pnpm/@kodemo+player@0.3.2_du7yz5f23cngwv65h7jru7qe7y/node_modules/@kodemo/player/dist/kodemo-player.es.js:3360:27
```

So it seems like the package isn't meant to be used in node.js / SSR? Which is required by Astro as it renders the templates in the server.

**Comment by matthewp** [comment]
It seems likely this component is not meant to be run in the server. You can use the `client:only` directive to force a component to load only in the browser.
