### ISSUE TITLE
Link JavaScript is not build as bundle?

### ISSUE THREAD

**Issue by joyjoyworld** [withastro/astro#6324]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

In the component countdown.astro, I have link cd.js is use to count down timer.
```<script src="../cd.js"></script>```

`npm run build` will inline entire JavaScript into `<head>` which is not actually as I have expected based on the documentation I understand?

How do you bundle your app in a global.js?

### Link to Minimal Reproducible Example

No

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by joyjoyworld** [comment]
This page I read at:
https://docs.astro.build/en/guides/client-side-scripts/

Can be confusing.

**Comment by matthewp** [comment]
Please use the #support channel in Discord for help. In this case don't use `src` but rather write it like this:


```astro
<script>
  import '../cd.js';
</script>
```
