### ISSUE TITLE
Astro + React: Build failed because of react-slick Slider though in dev it works fine

### ISSUE THREAD

**Issue by ZorikovPasha** [withastro/astro#6334]
### What version of `astro` are you using?

1.6.13

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 11

### Describe the Bug

So, I have this error, using `react-slick` and `rc-slider`, say I have Slider component in TopSlider, and then TopSlider is imported and used in `index.astro`: `<TopSlider client:load />`. In dev mode it works fine but build fails every time till I remove all react components with sliders in them. Same with rc-slider. Specifically what I am getting is `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`. Reproduction is attached down below

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/js-d39yan

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Marking the package as `noExternal` would normally fix issues like this
This comments explains why need to do that https://github.com/withastro/astro/issues/3076#issuecomment-1099605904.

Let me know if it does work for you

**Comment by matthewp** [comment]
Can confirm that `client:only="react"` works here. This package relies on access to the `window` which is not available in Astro SSR.

**Comment by y-nk** [comment]
@matthewp thanks to this error i found why my build was broken. it would be nice if we could have a more meaningful explanation of why this breaks.

for example, mocking `window` with every prop/func throwing an error would help catching expected error to bubble up the info that a react renderer tries to use a browser api at build.
