### ISSUE TITLE
Node middleware adapter doesn't match routes when base is set

### ISSUE THREAD

**Issue by mdixon4** [withastro/astro#6335]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Windows/WSL/Ubuntu

### Describe the Bug

Enable SSR using `output: server` and using the node adapter with `mode: 'middleware'`, and set a base in astro.config:

```js
import { defineConfig } from 'astro/config'

// https://astro.build/config
import node from '@astrojs/node'

// https://astro.build/config
export default defineConfig({
  output: 'server',
  adapter: node({
    mode: 'middleware',
  }),
  base: '/mybasepath',
})
```

Create a `server.js` file that creates an express app and hosts the built middleware at `/mybasepath`:

```js
import express from 'express'
import { handler } from './dist/server/entry.mjs'

const app = express()

app.use('/mybasepath', express.static('./dist/client'))
app.use('/mybasepath', handler)

app.listen(3000, () => {
  console.log('Listening on http://localhost:3000')
})
```

Build the site, and run the server using `npm run build && node server.js`

A 404 status is returned when requesting `http://localhost:3000/mybasepath/`. When running in dev or preview modes, the site is displayed appropriately.

Inspecting the running code, it looks like match is prepending an additional '/' before matching, so it is trying to find `//` rather than `/`.

### Link to Minimal Reproducible Example

https://github.com/mdixon4/intergalactic-ice

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
mark

**Comment by wulinsheng123** [comment]
You needn't add a `/mybasepath`  in the server file.

**Comment by wulinsheng123** [comment]
```js
import express from 'express'
import { handler } from './dist/server/entry.mjs'

const app = express()

app.use('/mybasepath', express.static('./dist/client'))
app.use(handler)

app.listen(3000, () => {
  console.log('Listening on http://localhost:3000')
})
```

**Comment by wulinsheng123** [comment]
Because the `handle` function will handle `baseUrl`,  and the ` express.static` not 
 
I think we can add more descriptions of the middleWare in the doc.
@matthewp 
@bluwy 
cc

**Comment by mdixon4** [comment]
Thank you @wulinsheng123 I can confirm that your solution works. Thanks for investigating.

**Comment by wulinsheng123** [comment]
I think we also need to update this in the doc.

**Comment by matthewp** [comment]
Yeah, I suppose mentioning this in the readme could be helpful to people.

**Comment by ematipico** [comment]
I'll take this one
