### ISSUE TITLE
Tailwind is not loaded for layout of markdown pages

### ISSUE THREAD

**Issue by hieudo-dev** [withastro/astro#6336]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm facing an issue where TailwindCSS is not available in the Markdown pages of my app.

I created some `.md` pages that has my content and I specified a layout component through the property `layout` like below:
```astrojs
---
layout: ../layouts/Base.astro
---
```
the **Base.astro** component uses TailwindCSS but I when access my pages in the browser none of the TailwindCSS classes work.

I'm note sure if this is a bug or a misusage on my part. As of now im using content collections and the `astro:content` to work around this. A reproducible version is provided below.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xkptsr-yprlfg

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by rafael-pinheiro** [comment]
Also struggling with that.
It's worse that it only happens on build and not on dev. Found out after deploy =/

**Comment by matthewp** [comment]
I think this may be the same issue as https://github.com/withastro/astro/issues/6318 Will add a test for both
