### ISSUE TITLE
[create-astro] `--help` does not print all possible flags

### ISSUE THREAD

**Issue by ansidev** [withastro/astro#6339]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

Steps to reproduce:
1. Run `pnpm create astro@latest --help`.

`--help` does not print all possible flags. These flags should be generated automatically.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Hi @ansidev , what are the flags you expect to see?

**Comment by ansidev** [comment]
> Hi @ansidev , what are the flags you expect to see?

You can see possible flags here:

https://github.com/withastro/astro/blob/main/packages/create-astro/src/actions/context.ts#L30-L51

**Comment by natemoo-re** [comment]
Thanks for catching this—PRs welcome! Not sure if we'll have time to update ourselves but this seems like a great first issue for someone.

**Comment by SerekKiri** [comment]
Hello 👋🏼 , if @ematipico wants to work on it then go on, if not I would love to pick it up 👍🏼

**Comment by ansidev** [comment]
> Hello 👋🏼 , if @ematipico wants to work on it then go on, if not I would love to pick it up 👍🏼

@SerekKiri At least this solution might resolve this issue, however, your solution does not solve it.

If flags were added, however, the developer forgets to update the help command, which will cause this issue again.

I expect a solution that automatically generates output for `--help` from given arguments and flags, ...

**Comment by SerekKiri** [comment]
Ok, sounds good 👍🏼 I missed that part in the description 😅

**Comment by SerekKiri** [comment]
@ansidev one question tho, do you expect for the ones that would be automatically added to have description?

**Comment by rishi-raj-jain** [comment]
@ansidev 

I think each flag's description can be added whenever a new one is added (which won't be that frequent ig), but something to be made sure of so would defer to @matthewp (to introduce a process for this maybe?)

**Comment by matthewp** [comment]
Perfect is the enemy of good :) Flags are not added often enough to justify some big effort to attempt to automate them. So we should just add the ones that are missing imo :)

**Comment by rishi-raj-jain** [comment]
Yup, totally agreed!

Maybe can be just as small as a checkbox on the PR template

**Comment by SerekKiri** [comment]
@rishi-raj-jain hmm a checkbox is not a bad idea but does it make sens to add it to a template? I think it's a good thing to focus on during a code review and for a developer to remember.

**Comment by ansidev** [comment]
I like this library: https://github.com/urfave/cli
