### ISSUE TITLE
Lit and multiple slotted elements not all rendering

### ISSUE THREAD

**Issue by boyatbeebee** [withastro/astro#6340]
### What version of `astro` are you using?

2.0.11

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Using a Lit element and multiple slotted elements causes not all of them to render.

One is a named slot, the other doesn't have a name.

**Expected behaviour:**
Both slotted elements render.

**Actual behaviour:**
Only 1 slotted elements gets rendered.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/serene-feistel-bs1n9w?file=%2Fsrc%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Use `slot:raw="body"`. The `slot` attribute means something different in .astro files than in normal HTML.

**Comment by boyatbeebee** [comment]
Thanks for the clarification @matthewp 

`raw` is only mentioned here in the docs.
[is:raw](https://docs.astro.build/en/reference/directives-reference/#israw)
Not anywhere near slotted components.
Also the syntax is a bit different with `is:raw `and in this case `:raw`.
Would it be an idea to add some information about this to the docs?

**Comment by matthewp** [comment]
yep for sure, i don't know if we have docs for the `slot:raw` case.
