### ISSUE TITLE
Prerendering from Content Collections still adds content to SSR server code

### ISSUE THREAD

**Issue by jimjimovich** [withastro/astro#6350]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

Deno

### What package manager are you using?

npm

### What operating system are you using?

Linux, Ubuntu 22.04

### Describe the Bug

When prerendering content from content collections using the method described in the documentation and used in the blog example, the content of each item/page is still added to the entry.mjs file. Standard pages are prerendered to html and then not added to entry.mjs.

Duplicating the already prerendered content inside entry.mjs leads to very large server files and is in general not efficient. 

See the example provided and you can see how the output from blog posts in the content folder are in entry.mjs but the content of the about.astro page is no longer included there when using prerendering.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8mbuj5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jimjimovich** [comment]
Any chance that this is fixable? I took a look at the code and couldn't figure out what needed changed.

**Comment by natemoo-re** [comment]
Ah I'm sorry it took so long for us to get to this issue!

You're correct that hybrid rendering does not suffer from this issue, but it also looks like this `/blog/[...slug].astro` file includes a `getStaticPaths()` function but not an `export const prerender = true` statement. Setting the page to be prerendered should avoid the Content Collection code from ever being bundled on the server.

Astro should have a better warning is `getStaticPaths` is used but `prerender` is not!

**Comment by natemoo-re** [comment]
I'm asking the rest of the team how we want to handle `getStaticPaths` with for `output: 'server'` if a `prerender` export doesn't exist...

As this issue shows, it's unintuitive that the `getStaticPaths` is silently ignored. It should probably warn, throw, or just imply that the page should be prerendered.
