### ISSUE TITLE
Usage of `:where` in CSS should be optional for compatibility reasons

### ISSUE THREAD

**Issue by Razunter** [withastro/astro#6354]
### What version of `astro` are you using?

2.0.15

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Astro uses `:where` for scoped styles, but support for `:where` isn't global: https://caniuse.com/mdn-css_selectors_where
Safari on iOS is the main problem, as it doesn't auto-update.

---
Unrelated to this issue, and I haven't really investigated this, but styles from the component were added before global styles that were imported into the layout...

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-asoega?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
We had similar issues of this in the past and converge them to https://github.com/withastro/roadmap/discussions/371 now, so closing this.
