### ISSUE TITLE
Running Vite server during build breaks plugin assumptions

### ISSUE THREAD

**Issue by natemoo-re** [withastro/astro#6364]
### What version of `astro` are you using?

2.0.12+

### Are you using an SSR adapter? If so, which one?

N/A

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

In https://github.com/withastro/astro/pull/6238, we broke [`vite-plugin-pwa`](https://github.com/vite-pwa/vite-plugin-pwa/) (and possibly others) because we started running a temporary Vite server during the build to load Content Collections. `vite-plugin-pwa` uses [`apply: 'serve'`](https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/plugins/dev.ts#L32) as a heuristic for running the dev server, which no longer works when we start a temporary server _and pass all plugins_ to that server.

cc @userquin 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kyecnu?file=integration.js,astro.config.mjs,package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by userquin** [comment]
https://vitejs.dev/guide/api-plugin.html#conditional-application

**Comment by userquin** [comment]
Maybe I can include a protection using command on configResolved hook in main plugin

**Comment by matthewp** [comment]
I believe @bholmesdev plans to get rid of the special temporary Vite server and just load through the normal one.
