### ISSUE TITLE
Package use-immer crashes astro

### ISSUE THREAD

**Issue by RadoslavMarinov** [withastro/astro#6365]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Importing `use-immer` into react (tsx) file causes error in the terminal:
```

import { useImmerReducer } from "use-immer";

const initState = {}
const reducer = (draft, action) => {
  switch(action.type) {      
    default:
      break;
  }
}
const [data, dataDispatch] = useImmerReducer(reducer, initState);
```

The terminal shows:

```
12:09:46 AM [astro] reload C:/Users/rojer/code/node/web/astro/rico-12:11:49 AM [astro] reload C:/Users/rojer/code/node/web/astro/rico-astro-website/src/components/xp/immer/immer-reducer.tsx (x9)       
 error   Cannot read properties of undefined (reading 'useImmerReducer')
  File:
    C:\Users\rojer\code\node\web\astro\rico-astro-website\C:\Users\rojer\code\node\web\astro\rico-astro-website\src\components\xp\immer\immer-reducer.tsx:12:29
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'useImmerReducer')
    at C:/Users/rojer/code/node/web/astro/rico-astro-website/src/components/xp/immer/immer-reducer.tsx:12:29
    at async instantiateModule (file:///C:/Users/rojer/code/node/web/astro/rico-astro-website/node_modules/vite/dist/node/chunks/dep-3007b26d.js:52400:9)
```

Steps to reproduce 
1) Install use immer `npm install immer use-immer`
2) Create react component and add it to a page (make sure it is client side component (client:visible)
And the server crashes with the above mentioned error

### Link to Minimal Reproducible Example

?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
> Link to Minimal Reproducible Example
> ?

Can you add a link to stackblitz?

**Comment by rishi-raj-jain** [comment]
@RadoslavMarinov Here's how you want to run it: https://stackblitz.com/edit/withastro-astro-sfd8r7?file=astro.config.mjs

Basically you need to set the following in astro config:

```
vite: {
    ssr: {
      noExternal: 'use-immer',
    },
}
```

cc @MoustaphaDev
