### ISSUE TITLE
Astro.cookies.set is broken while using the dev server via npm run dev on localhost

### ISSUE THREAD

**Issue by martinemmert** [withastro/astro#6367]
### What version of `astro` are you using?

2.0.15

### Are you using an SSR adapter? If so, which one?

netlify

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

While using the dev server, started via `npm run dev`, the functionality behind `Astro.cookies.set()` does not result in a cookie being sent with the response.

Even though the cookie's content can be read via `Astro.cookies.get()` after it was set with `Astro.cookies.set()`. Therefore, the bug must be located in the functionality that creates the cookie headers for the response.

Setting the headers directly works.

`Astro.response.headers.set('Set-Cookie', 'a=b; Path=/;');` this will set a cookie `a` with content `b`

### Link to Minimal Reproducible Example

https://github.com/martinemmert/github-w5uqxj

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martinemmert** [comment]
Further discussion: https://discord.com/channels/830184174198718474/1078818327260057681

**Comment by Princesseuh** [comment]
Fixed in 2.0.16: 
<img width="206" alt="image" src="https://user-images.githubusercontent.com/3019731/221590982-584df288-a669-4ef8-95ab-86a5bd771e24.png">
