### ISSUE TITLE
Node standalone adapter doesn't match routes without trailing slash when base is set

### ISSUE THREAD

**Issue by sasoria** [withastro/astro#6371]
### What version of `astro` are you using?

2.0.15

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Somewhat similar to #6335, when running the Node adapter in standalone mode and a base path is set, going to the url of the application without a trailing slash returns 404. This is my Astro config:
```javascript
export default defineConfig({
  base: "/base-path",
  trailingSlash: "ignore",
  integrations: [react()],
  output: "server",
  adapter: node({
    mode: "standalone",
  }),
});
```
The only working version of the app both in dev and preview is with a trailing slash, even when trailingSlash is set to `ignore`. That is, http://localhost:3000/basepath returns 404 and http://localhost:3000/basepath/ does not.

### Link to Minimal Reproducible Example

https://github.com/sasoria/astro-trailing-slash-exmaple

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sasoria** [comment]
It looks like a trailing slash is added during build under `const _manifest` in dist/server/entry.mjs: `... "_meta":{"trailingSlash":"ignore"}}}],"base":"/base-path/`

**Comment by teinett** [comment]
Related: https://github.com/withastro/astro/pull/4352

**Comment by matthewp** [comment]
Yes, this is now fixed by https://github.com/withastro/astro/pull/4352
