### ISSUE TITLE
Incorrect syntax highlighting font style due to outdated shiki version

### ISSUE THREAD

**Issue by yklcs** [withastro/astro#6383]
### What version of `astro` are you using?

2.0.16

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

Astro's shiki version (`shiki^0.11.1`) has a bug causing improper rendering of `fontStyle` (bold, underline, italic) options: shikijs/shiki#343. This affects Astro syntax highlighting.

This can be fixed by bumping the version of shiki. I had a go at creating a PR, but had a hard time figuring out the test case color values.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-iy1dyb?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
If upgrading shiki doesn't cause any regressions, then I think it's fine to upgrade without any test (if that's what you're referring to the color values?)

**Comment by bluwy** [comment]
I've upgraded shiki to latest at https://github.com/withastro/astro/pull/6932, which is release in Astro 2.4
