### ISSUE TITLE
[prerender=true] hybrid approach getStaticPaths not working /[id]/[slug]

### ISSUE THREAD

**Issue by alexandregiordanelli** [withastro/astro#6385]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

<img width="749" alt="Captura de Tela 2023-02-28 às 13 50 03" src="https://user-images.githubusercontent.com/1518223/221922361-f88e08cc-94bc-4fb8-a61e-a7714e00a04a.png">
<img width="678" alt="Captura de Tela 2023-02-28 às 13 49 53" src="https://user-images.githubusercontent.com/1518223/221922380-f80a8550-603d-4044-99c0-835e90115c5e.png">
<img width="871" alt="Captura de Tela 2023-02-28 às 13 49 46" src="https://user-images.githubusercontent.com/1518223/221922386-f7393d7f-116c-4ae5-8a91-4b9796a780fc.png">
<img width="389" alt="Captura de Tela 2023-02-28 às 13 53 38" src="https://user-images.githubusercontent.com/1518223/221922476-2ab7e045-f273-4ed1-a7d1-121d4ce55071.png">

Build but no .html files in dist folder. 404 error when astro preview

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexandregiordanelli** [comment]
<img width="408" alt="Captura de Tela 2023-02-28 às 13 55 57" src="https://user-images.githubusercontent.com/1518223/221923050-6c9fe491-12f3-4777-8e47-7c9748e316de.png">
<img width="410" alt="Captura de Tela 2023-02-28 às 13 55 50" src="https://user-images.githubusercontent.com/1518223/221923054-2c930407-7723-403e-8965-6a8237a1f175.png">

**Comment by alexandregiordanelli** [comment]
<img width="781" alt="Captura de Tela 2023-02-28 às 13 56 47" src="https://user-images.githubusercontent.com/1518223/221923290-930cc3e6-8100-41a0-8c2d-b540fdcc0c47.png">

**Comment by rishi-raj-jain** [comment]
@alexandregiordanelli 

We'd need a reproduction link to see what's breaking, can you use stackblitz / or share a GitHub repo to your example?

**Comment by natemoo-re** [comment]
Based on the information you have shared, the problem is likely the way you're defining `getStaticPaths`. The `GenerateStaticPaths()` function will not be available since `getStaticPaths` is hoisted out of the module at compile time.

Please provide a reproduction if that's not the case.

**Comment by matthewp** [comment]
Issue is stale, going to close, please create a new issue if you have a reproduction.
