### ISSUE TITLE
Importing MDX from MDX

### ISSUE THREAD

**Issue by zellwk** [withastro/astro#6389]
### What version of `astro` are you using?

2.0.9

### Are you using an SSR adapter? If so, which one?

Nope

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to import an `mdx` file from another `mdx` file but I ran into a `Component.render is not a function` error. 

Details below. 

**Here's the basic idea of what I'm trying to do:** I'm trying to use mdx as partials. 

I have an `index.astro` file that contains many `mdx` partials. For each partial, I pass in the components. 

```astro
---
import Base from '/src/layouts/Base.astro'
import { components } from '/src/utils.js'

import Intro from '/src/partials/intro.mdx'
// Import other partials here
---

<Base>
  <Intro {components} />
  <Mechanism {components} />
  <Product {components} />
  <About {components} />
  <Close {components} />
  <CTA {components} />
  <Guarantee {components} />
  <FAQ {components} />
  <CTA {components} />
  <Footer {components} />
</Base>
```

Next, I tried importing another partial from the `Intro` partial. 

```mdx
import NestedPartial from './anotherPartial.mdx'
```

What I discovered: 

- If `NestedPartial` contains any Astro to Svelte components, I'll get the `Component.render is not a function` error. 
- If `NestedPartial` doesn't contain Astro or Svelte components, it would work

**This is where I need help**

- Is there any way to include nested partials in Astro using MDX files? 
- Before this, I would use the legacy MarkdownComponent, but as I shift to MDX I have no idea how to include nested partials anymore. 
- Is there any way to make this work? 

Thank you so much. 

### Link to Minimal Reproducible Example

I tried creating a reproducible example but I got a syntax error even on my first `mdx` file... I'm not sure why at this point. 

https://stackblitz.com/edit/github-gpe8ap?file=src%2Fpartials.mdx,src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by y-nk** [comment]
The stackblitz example lacks of the [@astrojs/mdx](https://docs.astro.build/en/guides/integrations-guide/mdx/) package installed. Did you miss that part in your repro?

**Comment by zellwk** [comment]
Doh! I completely forgot about the mdx integration! 

I'll work on the demo and get back soon.
