### ISSUE TITLE
@astrojs/image sharp integration: dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by theurgi** [withastro/astro#6390]
### What version of `astro` are you using?

2.0.16

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

After installing `@astrojs/image` with the sharp integration, my project won't build. Without the sharp integration it builds fine.

I tried running `pnpm rebuild sharp` to no avail.

Below are steps for a manual reproduction. The [stackblitz repro](https://stackblitz.com/edit/github-q3m5h1) fails as well but with a different stack trace: `Something went wrong installing the "sharp" module...`

**EDIT:** I see now that StackBlitz doesn't support `sharp`:

> The @astrojs/image default image transformer is based on [Squoosh](https://github.com/GoogleChromeLabs/squoosh) and uses WebAssembly libraries to support most deployment environments, **including those that do not support sharp, such as StackBlitz**

## Steps taken

Installed with `image` and `sharp`

```sh
pnpm astro add image
pnpm install sharp
```
Configured `astro.config.mjs`

```js
import image from '@astrojs/image'
import { defineConfig } from 'astro/config'

export default defineConfig({
  integrations: [
    image({
      serviceEntryPoint: '@astrojs/image/sharp',
    }),
  ],
})
```
Configured `src/env.d.ts`

```ts
/// <reference types="@astrojs/image/client" />
```
Stack trace on `pnpm dev`

```
❯ pnpm dev

> <package>@0.0.1 dev <project_root>
> astro dev

dyld: lazy symbol binding failed: Symbol not found: _pthread_jit_write_protect_supported_np
  Referenced from: <project_root>/node_modules/.pnpm/sharp@0.31.3/node_modules/sharp/build/Release/../.././vendor/8.13.3/darwin-x64/lib/libvips-cpp.42.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _pthread_jit_write_protect_supported_np
  Referenced from: <project_root>/node_modules/.pnpm/sharp@0.31.3/node_modules/sharp/build/Release/../.././vendor/8.13.3/darwin-x64/lib/libvips-cpp.42.dylib
  Expected in: /usr/lib/libSystem.B.dylib

 ELIFECYCLE  Command failed.
zsh: abort      pnpm dev
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-q3m5h1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by theurgi** [comment]
Turns out this looks like a sharp/macOS issue ( https://github.com/lovell/sharp/issues/3438 ) that should be fixed in the next sharp release.

If anyone runs into this in the mean time, this is what fixed it for me: https://github.com/lovell/sharp/issues/3438#issuecomment-1343755452

```sh
pnpm uninstall sharp
# then
pnpm install sharp@0.31.1
```

**Comment by Princesseuh** [comment]
Thank you for investigating, this seems like it only affects a minority of users and will be fixed soon upstream, so I'll close this issue!
