### ISSUE TITLE
css duplicate after build

### ISSUE THREAD

**Issue by J-env** [withastro/astro#6395]
### What version of `astro` are you using?

2.0.16

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm,pnpm

### What operating system are you using?

Mac

### Describe the Bug

1. open link
[example](https://stackblitz.com/edit/github-sdeict-ymlg1a?file=src%2Fpages%2Findex.astro)

2. `npm run build`

3. View dist/index.html
<img width="971" alt="image" src="https://user-images.githubusercontent.com/25259920/222159191-112c56d5-2ebd-4d29-bcfb-77cd71e11bf6.png">

4. css content
<img width="1566" alt="image" src="https://user-images.githubusercontent.com/25259920/222160368-cb8da945-5059-4cfc-8ed1-4f349d006c41.png">

I haven't found the reason yet.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sdeict-ymlg1a?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
mark。
this bug looks fun

**Comment by bluwy** [comment]
This seems to be similar https://github.com/withastro/astro/issues/6524. What happens is that the CSS is imported in an Astro component and a framework component. When Astro does an SSR and client build, both builds would generate their own set of CSS artifacts which causes this duplication.

We do have code in place to remove the duplication though by matching CSS chunks from both builds and discarding one of them. I _think_ https://github.com/withastro/astro/pull/6582 might fix this too.
