### ISSUE TITLE
got Invalid request body when using astro endpoint on vercel

### ISSUE THREAD

**Issue by Kalo0m** [withastro/astro#6399]
### What version of `astro` are you using?

2.0.15

### Are you using an SSR adapter? If so, which one?

Vercel - serverless

### What package manager are you using?

pnpm's monorepo

### What operating system are you using?

Windows

### Describe the Bug

I created a post endpoint which parse the body to extract an email from.
```ts
export const post: APIRoute = async ({ request, url }) => {
  const body = await body.json()
  await prisma.user.create({
    data: {
      email: body.email,
    },
  });
  return {
    status: 200,
    headers: {
      'content-type': 'application/json',
    },
    body: JSON.stringify({ email }),
  };
};
```
and fetch it in a react client loaded component : 
```ts
  const onSubmit = (email: string) => {
    fetch('/signin?email=${email}', {
      method: 'post',
      body: JSON.stringify({ email }),
    });
  };
  ```
It works perfectly locally but when deployed to vercel, when I call the endpoint I get Invalid request body before running the function. Is it a bug or do I misunderstand something ?

ps : here is my astro.config
```ts
import vercel from '@astrojs/vercel/serverless';

// https://astro.build/config
export default defineConfig({
  output: 'server',
  integrations: [react(), vercel()],
});
```

thanks for your help and your amazing work !

I've created a minimal reproduction which I've deployed to vercel and I got the same error (that's the link of the deployed project [astro-vc4bqx.vercel.app](https://astro-vc4bqx.vercel.app/)). If you send a post request with a body to https://astro-vc4bqx.vercel.app/signin you will get the error

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-vc4bqx?file=src/pages/signin.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by w3bdesign** [comment]
@Kalo0m 

I checked your code, and it looks like you are missing this line in the Astro config file:

`adapter: vercel(),`

**Comment by Kalo0m** [comment]
@w3bdesign Yes sorry, I fixed the config and still get the error. Will the next release solve my issue and will I get an error message?

**Comment by w3bdesign** [comment]
> @w3bdesign Yes sorry, I fixed the config and still get the error. Will the next release solve my issue and will I get an error message?
> 
> and can I use the next release with a version tag right now?

@Kalo0m 

I can't give a good answer to that yet, but apparently the Astro team is aware of the bug and has commited a fix. 

I would check https://www.npmjs.com/package/@astrojs/vercel and wait until they get a new release published before trying to use it again.

**Comment by Kalo0m** [comment]
It works perfectly with astro@2.0.17 thank you all !

**Comment by lirantal** [comment]
Note, this requires `@astrojs/vercel` to be updated too to at least `3.1.4`

**Comment by MoustaphaDev** [comment]
Closing as completed in https://github.com/withastro/astro/pull/6380
As stated by the comments above, you need to update `astrojs/vercel` and `astro`

**Comment by lirantal** [comment]
> Closing as completed in #6380 As stated by the comments above, you need to update `astrojs/vercel` and `astro`

@MoustaphaDev you should update your reply to not confuse folks to install a typosquatted package. it should be `@astrojs/vercel` and not `astrojs/vercel` (note the leading `@` that denotes the official namespace)

**Comment by MoustaphaDev** [comment]
Thanks @lirantal, updated!
