### ISSUE TITLE
Using a Content Security Policy with Astro

### ISSUE THREAD

**Issue by rossPatton** [withastro/astro#6407]
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I am trying to add a nonce to enable use of google fonts with a strict CSP. 

I'm wondering what the Content Security Policy experience is supposed to be with Astro, because currently it looks like any use of `client:load` will break script-src/style-src set to anything but 'unsafe-inline', due to how astro-islands appear to work.

What I want to know is - is there a way to dynamically add a nonce to these inlined style/script tags or get the computed hash(s)? I can do this for my own scripts/styles, but I don't see a way to do this with bundles auto-generated by astro.

Thanks

Link provided just goes to one of our staging urls. See the screenshot below. There is an application form that an astro-island loaded via client:load. The corresponding css/js is inlined with no nonce or hash set. 

<img width="1124" alt="Screenshot 2023-03-02 at 9 43 26 AM" src="https://user-images.githubusercontent.com/2379901/222460765-67770a33-b907-47ce-871f-c4d82266b9fa.png">

My CSP:

```
        default-src 'self';
        connect-src 'self' *.joinfreeworld.local *.joinfreeworld.com;
        font-src fonts.gstatic.com;
        form-action 'self';
        frame-src 'self' https://airtable.com;
        img-src 'self' https://fwpublic.nyc3.cdn.digitaloceanspaces.com https://images.ctfassets.net;
        manifest-src 'self';
        media-src 'self' https://fwpublic.nyc3.cdn.digitaloceanspaces.com https://videos.ctfassets.net;
        object-src 'none';
        script-src 'self' https://vercel.live 'nonce-${NONCE}';
        style-src 'self' fonts.googleapis.com;
        style-src-elem 'self' fonts.googleapis.com;
        upgrade-insecure-requests;
```

### Link to Minimal Reproducible Example

https://marketing-site-git-ross-qualitypass-fw-test-team.vercel.app/application

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
There's not a way at the moment. See https://docs.astro.build/en/guides/troubleshooting/#refused-to-execute-inline-script

We are discussing solutions to allow stricter policies here: https://github.com/withastro/roadmap/discussions/377

closing as the discussion for CSP should be in the above thread.
