### ISSUE TITLE
Importing components through a js file

### ISSUE THREAD

**Issue by zellwk** [withastro/astro#6411]
### What version of `astro` are you using?

^2.0.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Hi! I'm trying to write a script in a js file that allows me to avoid importing components one by one. 

So imagine being able to write this: 

```js
const comps = await import.meta.glob('/src/components/*')
export const components = await componentMap(comps)
```

Instead of this: 

```js
import Accordion from '/src/components/Accordion.svelte'
import Button from '/src/components/Button.svelte'
import Highlight from '/src/components/Highlight.svelte'
import Image from '/src/components/Image.svelte'
import List from '/src/components/List.astro'
import PaymentOption from '/src/components/PaymentOption.svelte'
import ProductInfo from '/src/components/ProductInfo.astro'
import SVG from '/src/components/SVG.svelte'
import Showcase from '/src/components/Showcase.astro'
import Testimonial from '/src/components/Testimonial.astro'
import TextImage from '/src/components/TextImage.astro'
import TextImageInsert from '/src/components/TextImageInsert.astro'
import Video from '/src/components/Video.svelte'

export const components = {
  Accordion,
  Testimonial,
  List,
  SVG,
  Highlight,
  Showcase,
  Image,
  ProductInfo,
  TextImageInsert,
  TextImage,
  PaymentOption,
  Button,
  Video,
}
```

I've managed to write a script that works successfully in Astro's dev mode. 

```js
export async function componentMap(files) {
  const obj = {}

  const entriesPromises = Object.entries(files).map(async entry => {
    let [key, value] = entry
    const basename = path.basename(key)
    const ext = path.extname(key)
    const filename = basename.replace(ext, '')

    const { default: component } = await value() // We'll get an error here in the built step
    return [filename, component]
  })

  const entries = await Promise.all(entriesPromises)

  for (const entry of entries) {
    const [key, value] = await entry
    obj[key] = value
  }

  return obj
}
```

But I run into an error in Astro's build step.

![CleanShot_2023-03-03_at_16 21 02](https://user-images.githubusercontent.com/3607637/222673365-23662879-3cd5-40cc-94cd-f116980ddd3b.png)

Does anyone have any ideas how to make this work in the build step please? 

Help is super duper appreciated! Thank you!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ljahqu?file=src/pages/index.astro

Interestingly, the error in the minimal reproducible example is different in Stackblitz — it seems like `import.meta.glob` returns undefined so I'm unable to even reproduce the actual error. 

![CleanShot 2023-03-03 at 16 43 44](https://user-images.githubusercontent.com/3607637/222673685-600b831f-6447-410c-b074-44300e12b50f.png)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
I didn't find what caused your script to fail but it's most likely unrelated to Astro.

This script should work though
```ts
/* src/components/index.ts */
const componentEntries = Object.entries(
  import.meta.glob('./**/*.astro', { eager: true })
);
const components = {};

for (let [modulePath, { default: Component }] of componentEntries) {
  // name of the export based on the filename
  const exportName = modulePath
    .split('/')
    .at(-1)
    .replace(/\.(astro|svelte)$/, '');
  components[exportName] = Component;
}

export { components };
```

Note that when doing this (or any other script that regroups imports) you won't benefit from threeshaking and importing the `components` variable will import ALL css and js of ALL components, even if you only use one component from the object. Because of that, it's not recommended to do this

A more compact way to manually export your components is something like this:
```ts
export { default as Accordion } from './src/components/Accordion.svelte'
export { default as Button } from './src/components/Button.svelte'
export { default as Highlight } from './src/components/Highlight.svelte'
...
```

Closing this as it's not an Astro issue
