### ISSUE TITLE
@astrojs/sitemap doesn't provide setup of links

### ISSUE THREAD

**Issue by Tc-001** [withastro/astro#6416]
### What version of `astro` are you using?

2.0.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Currently the `@astrojs/sitemap` integration generates a `sitemap-index.xml` file that is used to hint search engines where to look. But for search engines to find it there needs to be a link to it in either `robots.txt` or a meta tag.

The issue is that the integration doesn't add either of them, or warn if they are not added. It is also not documented in [it's readme](https://github.com/withastro/astro/blob/main/packages/integrations/sitemap/README.md) if/how to add them manually.

Astro sites seem to add the link manually:
https://github.com/withastro/astro.build/blob/165ae1706857aee6589b8339dc276ba7b540b7a4/public/robots.txt#L6
https://github.com/withastro/astro.build/blob/165ae1706857aee6589b8339dc276ba7b540b7a4/src/components/BaseHead.astro#L34

... so it's probably just the case of missing documentation.

Although an opt-out option to inject the meta tag would also be nice (but that could break older sites that already have a manual one, if a crawler gets confused) 
Or have it be a step of `astro add` if that is possible

### Link to Minimal Reproducible Example

none

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for flagging this @Tc-001!

I think we need a docs fix for this one as we don't currently have an API for integrations to add tags to output (think an `injectElement` a bit like our current `injectScript` hook). We should probably show an example of the required HTML to add to your layout. Fancy making a PR?
