### ISSUE TITLE
Nesting anchor tags breaks DOM structure

### ISSUE THREAD

**Issue by ShivamJoker** [withastro/astro#6417]
### What version of `astro` are you using?

^2.0.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Nesting anchor `<a>` tags breaks the DOM.

![image](https://user-images.githubusercontent.com/23727670/222829727-9e5985d9-415b-4cb1-8d8b-5a919d3f6c8f.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rknpgy-6mbysn?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
That's invalid HTML.

**Comment by ShivamJoker** [comment]
@matthewp I know it's invalid HTML but Astro should tell us, instead of changing the DOM tree which breaks the whole structure.

I spoke with @natemoo-re, he said Astro should give error.

**Comment by carlos-dubon** [comment]
@matthewp Then how can one achieve this structure for Blog Post items:

```html
<a href="/blog-post-item">
    <div class="title">My blog post</div>
    <div class="tags">
        <a href="/tags/life>Life</a>
        <a href="/tags/family>Family</a>
    </div>
    <div class="description">My blog post item description</div>
</a>
```

even if it's not valid HTML it's a common pattern accross the web and should not break the DOM structure...
