### ISSUE TITLE
adding deno and lit integration does not work

### ISSUE THREAD

**Issue by zenwork** [withastro/astro#6418]
### What version of `astro` are you using?

2.0.17

### Are you using an SSR adapter? If so, which one?

deno

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Combining the lit integration with the deno adapter and running build fails with the following 

Note: running `npm run dev` OR `npm run start` works!

error output:
``` text
? npm run build

> planetary-plasma@0.0.1 build
> astro build

12:45:50 AM [content] No content directory found. Skipping type generation.
12:45:50 AM [build] output target: server
12:45:50 AM [build] deploy adapter: @astrojs/deno
12:45:50 AM [build] Collecting build info...
12:45:50 AM [build] Completed in 46ms.
12:45:50 AM [build] Building server entrypoints...
[commonjs--resolver] Cannot bundle Node.js built-in "node:http" imported from "node_modules/node-fetch/src/index.js". Consider disabling ssr.noExternal or remove the built-in dependency.
 error   Cannot bundle Node.js built-in "node:http" imported from "node_modules/node-fetch/src/index.js". Consider disabling ssr.noExternal or remove the built-in dependency.
RollupError: Cannot bundle Node.js built-in "node:http" imported from "node_modules/node-fetch/src/index.js". Consider disabling ssr.noExternal or remove the built-in dependency.
    at error (file:///Users/flo/dev/explore/planetary-plasma/node_modules/rollup/dist/es/shared/node-entry.js:2105:30)
    at Object.error (file:///Users/flo/dev/explore/planetary-plasma/node_modules/rollup/dist/es/shared/node-entry.js:23997:20)
    at Object.resolveId (file:///Users/flo/dev/explore/planetary-plasma/node_modules/vite/dist/node/chunks/dep-ca21228b.js:21501:34)
    at Object.handler (file:///Users/flo/dev/explore/planetary-plasma/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44872:19)
    at file:///Users/flo/dev/explore/planetary-plasma/node_modules/rollup/dist/es/shared/node-entry.js:24196:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/flo/dev/explore/planetary-plasma/node_modules/rollup/dist/es/shared/node-entry.js:24096:28)
    at async resolveId (file:///Users/flo/dev/explore/planetary-plasma/node_modules/rollup/dist/es/shared/node-entry.js:23040:26)
    at async ModuleLoader.resolveId (file:///Users/flo/dev/explore/planetary-plasma/node_modules/rollup/dist/es/shared/node-entry.js:23304:15)
    at async Object.resolveId (file:///Users/flo/dev/explore/planetary-plasma/node_modules/vite/dist/node/chunks/dep-ca21228b.js:7972:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/flo/dev/explore/planetary-plasma/node_modules/rollup/dist/es/shared/node-entry.js:24096:28)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-98m33j

Note: the issue only happens with `npm run build`

here is the actual project I have just started: https://github.com/zenwork/privatus

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by zenwork** [comment]
> It seems like `@lit-labs/ssr`, which we use to render the lit elements into the html, doesn't support Deno by default: [lit/lit#3272](https://github.com/lit/lit/issues/3272). I don't think we can do much until that issue is solved, so closing for now.

I don't quite agree with this assessment. Astro supports lit on it's own (as I stated) and with `client:only="lit"` mode no SSR should be used/needed. This is how I would like to use lit and deno at the moment.

**Comment by zenwork** [comment]
further more... `client:only="lit"` islands, which does not use ssr by definition, only works when I use the lit plugin.

**Comment by bluwy** [comment]
Yeah maybe we can investigate not inlining Lit's SSR renderer if `client:only="lit"` is only used.

**Comment by bluwy** [comment]
I've checked this, and it's not easy to not include Lit's renderer if `client:only="lit"` is used, since when we bundle for SSR and check for `client:only="lit"` usage at the same time, there's no reliable way to know if we've finished scanning all Astro, MDX files before we can decide whether to bundle Lit's renderer or not.

Since this is a unique case, you can use a Vite plugin to workaround it for now like so:

```js
function removeLitSsrRenderer() {
  return {
    name: 'remove-lit-ssr',
    enforce: 'pre',
    load(id) {
      if (id.includes('@astrojs/lit/server.js')) {
        return 'export default {}';
      }
    },
  };
}
```

[Stackblitz](https://stackblitz.com/edit/github-gfsuvd-eyepfd?file=astro.config.mjs) example.

Closing this for now as it's not something we can solve at the moment, but if there's more reports of this being a common usecase, we could reconsider re-architecting our internals to support this.

**Comment by zenwork** [comment]
Thanks for looking into this. I tested the above and it did in a simple setup. In the end I eventually hit other problems which required more extra steps requiring Vercel and so I dropped this approach. It probably would have worked,I want to learn astro and the benefits of an island-based design with a reasonably stable use-case.

**Comment by adoublef** [comment]
just wanted to note that with Deno, it's possible to use the unstable `deno_emit` package which is goilg to make it client only, similar to Astro's `client:only` attribute. 

I have only tested the `simple-greeting` example, but I am looking at seeing if the `lit-lab/context` works. Maybe  with declaritive shadowroot we can a way to define the markup in html then wait for the client script to kick in?
