### ISSUE TITLE
Node and Rollup assetFileNames output to wrong path

### ISSUE THREAD

**Issue by jamesli2021** [withastro/astro#6420]
### What version of `astro` are you using?

2.0.17

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

Ran `npm run build`, Astro generate CSS appear in `server` which is incorrect, the correct should be in `client` folder.
Note: path's `dir` variable returns is an empty string in astro.config.mjs, so by default `assetFileNames` is pointed to `server` folder:

```
import { defineConfig } from 'astro/config';
import path from "path";

// https://astro.build/config
import node from "@astrojs/node";

// https://astro.build/config
export default defineConfig({
  vite: {
    build: {
      cssCodeSplit: false,
      assetsInlineLimit: 0,
      rollupOptions: {
        output: {
          entryFileNames: 'assets/script/a.[hash].js',
          assetFileNames: ({
            name
          }) => {
            const { ext, dir, base } = path.parse(name);
            if (ext == ".css") return path.join(dir, "assets/css", 'a.[hash].css');
            return "assets/img/[name].[ext]";
          }
        }
      }
    }
  },
  output: "server",
  adapter: node({
    mode: "standalone"
  })
});

```

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
Hello,
Could you provide a duplicate?
That can let us find a problem more quickly.

**Comment by bluwy** [comment]
@jamesli2021 creating a repro means that everyone who's helping doesn't need to manually replicate the template to check. It increases the chances someone fixes the issue too. Anyway here's one: https://stackblitz.com/edit/github-upsdcx?file=astro.config.mjs

**Comment by jamesli2021** [comment]
Yes, it's still an error with that. I'm glad you spot it.

**Comment by wulinsheng123** [comment]
I'm going to check this bug right now
