### ISSUE TITLE
Style tag outside of <html> makes styles not apply to markdown files

### ISSUE THREAD

**Issue by BalintCsala** [withastro/astro#6428]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When placing a style tag outside the html element it won't cause any issues with pages created using .astro files, but posts won't get any form of styling. I'm not sure whether the correct behaviour here would be it causing an error or making posts work like they should.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nf66re?file=src/layouts/MainLayout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by zihan-ch** [comment]
I'm not pretty sure what you mean, but I guess you mean that styles elements have to be wrapped in the html element. Astro doesn't just put the style element directly into your HTML. Astro transforms the style content and then bundle it with Vite. In the end, the style is probably a CSS file outside the HTML and the HTML will have a link to that CSS file.

**Comment by BalintCsala** [comment]
@zihan-ch You can just open the MRE I linked, if you put a style element outside the html tags (doesn't need to do anything, just be there) then posts lose _all_ styling, not just from the one outside of the html tag.

**Comment by matthewp** [comment]
We're very unlikely to fix this. Just put it inside of the html tag.

**Comment by jamesli2021** [comment]
I tried it out and apply background to blue and is:global which works.

To ascertain why it doesn't apply even on a HTML, it is CSS complexity
https://blog.shimin.io/understanding-css-complexity/

The `Astro` is still red!

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
<style type="text/css">
.this-is-filler {
	color: blue !important;
}
.this-red {
    color: red;
}
</style>
</head>
<body class="this-is-filler">
	<h1 class="this-red">Astro</h1>
	<a href="/posts/test" class="">Link to example post</a>
</body>
</html>
```

**Comment by BalintCsala** [comment]
@matthewp I spent a good 2 hours debugging this, my issue isn't it not having a workaround, but how it doesn't give you an error and the documentation doesn't say anything about putting style tags outside the html tag.

@jamesli2021 Think you misunderstood the issue, this is not about the CSS since astro should put all of them into a single css file, the "Astro" text on the main page should be red and it is, but if you go to the example post the text should be green, but it isn't. It works on pages but doesn't work on posts.

**Comment by jamesli2021** [comment]
@BalintCsala `is:global` directive which will put all the styling in one CSS file. Let try to extract that and work on a HTML version?

**Comment by jamesli2021** [comment]
The nested layout issue you're referring is missing `<head>` tag when viewing in `http://localhost:3000/posts/test`.

**Comment by matthewp** [comment]
Getting back to this, we're not going to be able to fix this due to how the compiler works.
