### ISSUE TITLE
Build process fails with file copy when outDir is in upper directory

### ISSUE THREAD

**Issue by impcyber** [withastro/astro#6431]
### What version of `astro` are you using?

2.0.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

```ts
export default defineConfig({
  outDir: '../build/retail',
});
```

If i set `outDir` in upper folder of project folder, then build process fails with `copyfile`  error:
![image](https://user-images.githubusercontent.com/1425691/223169191-b5816049-6389-43d0-ba59-7df12496e539.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/misty-silence-y7xnw7

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@bluwy I believe you looked into this issue in the past. Did we conclude that we couldn't support it?

**Comment by bluwy** [comment]
This looks eerily familiar but I can't quite remember what was the problem. @impcyber I can't seem to get codesandbox working, there's some sort of yarn install error, but it might be me not familiar with codesandbox. Can you provide a GitHub repo or stackblitz instead?

I also tried replicating this locally and it's working fine for me.

**Comment by impcyber** [comment]
@bluwy Something strange happens, but the example a've provided works well now...
But anyway here is an repo (part of my real project): https://github.com/impcyber/astro-test-outdir
I've tested it now, error present:

![image](https://user-images.githubusercontent.com/1425691/223509234-e61d89d6-6410-4ecb-a204-e286d27ceb75.png)

**Comment by wulinsheng123** [comment]
@bluwy. 

let me dig into the build module again.
