### ISSUE TITLE
Initial scaffolded project with @astrojs/lit erroring: module is not defined

### ISSUE THREAD

**Issue by cbarratt** [withastro/astro#6444]
### What version of `astro` are you using?

^2.0.18

### Are you using an SSR adapter? If so, which one?

Netlify, but happens with no SSR

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### NOTE:

This appears to be ok when using yarn, but not pnpm

If I do `pnpm install --force --shamefully-flatten`, it works

I've just gone to setup a brand new astro project using the astro cli to scaffold it so, i then proceeded to add the lit integration using `pnpm astro add lit`.

Once the lit() integration was added, the site will error:

```
ReferenceError: module is not defined
    at eval (/Users/callumbarratt/projects/checkout-web/node_modules/.pnpm/node-domexception@1.0.0/node_modules/node-domexception/index.js:18:1)
    at instantiateModule (file:///Users/callumbarratt/projects/checkout-web/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52420:15)
```

### Link to Minimal Reproducible Example

https://github.com/dankochetov/astro-test-2

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
`lit` requires this `.npmrc` to work with pnpm: https://github.com/withastro/astro/blob/e1858e633484d0e1eca0e3ad72af679fc12271e0/examples/framework-lit/.npmrc#L1

Maybe `astro add` needs to be tweaked to add that if it doesn't exist, for pnpm.
