### ISSUE TITLE
Cache-Control headers not set when deployed using @astrojs/vercel/serverless adapter

### ISSUE THREAD

**Issue by williamli** [withastro/astro#6445]
### What version of `astro` are you using?

2.0.18

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Using the default template with `Astro.response.headers.set` added to index page (https://github.com/vercel-support/122247-astro-trpc-example/blob/main/src/pages/index.astro), the deployed site (https://122247-astro-trpc-example.vercel-support.app/) does not have the required custom header set for 'Cache-Control'.

```
---
import Layout from '../layouts/Layout.astro';
import Card from '../components/Card.astro';

Astro.response.headers.set('Cache-Control', 'public, max-age=0, s-maxage=3600, stale-while-revalidate=5400');

---
```

### Link to Minimal Reproducible Example

https://github.com/vercel-support/122247-astro-trpc-example/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, that's interesting. trpc is unrelated to this, i think, right?

**Comment by williamli** [comment]
Yeah. it's unrelated.

**Comment by matthewp** [comment]
Played around with this a bit and it seems to depend on what you set `Cache-Control` to. Other headers do work fine. And `Cache-Control` can work, but they seem to do some validation on it and default to `public, max-age=0` if they don't like what you give them. This string works for stale-while-revalidate: `s-maxage=1, stale-while-revalidate`.

Closing as this is not a bug on our end. I found these docs helpful: https://vercel.com/docs/concepts/functions/serverless-functions/edge-caching You might reach out to their support if your values are not being honored.
