### ISSUE TITLE
postcss-import-ext-glob plugin not working as expected

### ISSUE THREAD

**Issue by jacklenox** [withastro/astro#6447]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I have installed the `postcss-import` and `postcss-import-ext-glob` plugins following the instructions outlined in the documentation [here](https://docs.astro.build/en/guides/styling/#postcss), but the latter plugin doesn't seem to be functioning at all. Anywhere I place `@import-glob` in my CSS, it isn't interpreted as an import at all and therefore doesn't work.

The console also reports the following issue, which to me shows the plugin hasn't been loaded properly:

```
[vite:css] @import must precede all other statements (besides @charset or empty @layer)
9  |  @import 'global/global-styles.css';
10 |  
11 |  @import-glob 'utilities/*.css';
   |   ^
12 |  
13 |  @import 'tailwindcss/utilities'; (x2)
```

My `postcss.config.cjs` looks like this:

```js
module.exports = {
  plugins: [
    require('postcss-import-ext-glob'),
    require('postcss-import')
  ]
};
```

My `astro.config.mjs` looks like this:

```js
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

// https://astro.build/config
export default defineConfig({
	integrations: [tailwind({
		config: { applyBaseStyles: false },
	})],
});
```

I've reproduced a slimmed down version of my site in Stackblitz, so you can hopefully see the problem. If `global.css` contains nothing but `@import-glob`, it seems to work. But it can't be used alongside other regular imports, which is obviously kind of the whole point.

Am I missing something?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-drb48a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This looks a bit similar to https://github.com/vitejs/vite/issues/12257. Vite supports `postcss-import` by default, but no glob imports.

**Comment by bluwy** [comment]
I don't think this can be fixed in Astro as Vite is handling CSS preprocessing. I've created https://github.com/vitejs/vite/issues/12336 to discuss it. Closing in favour of it.

**Comment by jacklenox** [comment]
Thank you for looking into it @bluwy. It's frustrating, but I understand!
