### ISSUE TITLE
Astro.clientAddress is not available for Node integration

### ISSUE THREAD

**Issue by jcdogo** [withastro/astro#6451]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

@astrojs/node: 5.1.0

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When attempting to access `Astro.clientAddress`, I get this error:

```
ClientAddressNotAvailable: `Astro.clientAddress` is not available in the `@astrojs/node` adapter. File an issue with the adapter to add support.
```

It looks like #3973 added support for this to most of the backends, but Node was missing from the list.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-q7ujbk?file=package.json,astro.config.mjs,tsconfig.json&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
The adapter itself shouldn't need to add support, because it should be getting it for free because it uses this: https://github.com/withastro/astro/blob/main/packages/astro/src/core/app/node.ts#L26-L28

I'll write a test and try it out.

**Comment by matthewp** [comment]
This is working on my end. I pulled down your example and it works locally. Are you behind a proxy perhaps?

**Comment by jcdogo** [comment]
@matthewp Thanks for looking into this. What happens when you click the Stackblitz link from above:
https://stackblitz.com/edit/github-q7ujbk?file=package.json,astro.config.mjs,tsconfig.json&on=stackblitz

Because I'm seeing that error when running on the Stackblitz website directly.

<img width="1440" alt="Screen Shot 2023-03-09 at 3 14 30 PM" src="https://user-images.githubusercontent.com/70533701/224182026-d58ad8c1-a972-47b2-8bce-e793b482f5df.png">

If it's working for you, maybe we can figure out what the delta is between your environment and the Stackblitz example.

But even if behind a proxy, it shouldn't throw an error right?

**Comment by matthewp** [comment]
@jcdogo does that Stackblitz work for you when running locally? It does for me. I think the issue is that Stackblitz doesn't support `request.socket.remoteAddress` which is what we use in dev.
