### ISSUE TITLE
Support for SVG images is missing in the new Assets (Experimental) feature

### ISSUE THREAD

**Issue by TechAurelian** [withastro/astro#6452]
### What version of `astro` are you using?

2.1.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I'm trying to use the new `<Image />` component from `astro:assets` following the [official docs](https://docs.astro.build/en/guides/assets/):

`import headerLogo from '../assets/images/branding/logo/logo-header.svg';`

`<Image src={headerLogo} alt="Logo" />`

But I get this error:
```
MissingImageDimension
Missing image dimensions
For remote images, width and height are required.
```

With a `console.dir(headerLogo);` a get the path to the SVG image, instead of the expected `ImageAsset` object.

Trying to load the same logo in PNG format works, as it can also be seen in the attached StackBlitz.

Note: In the [VALID_INPUT_FORMATS](https://github.com/withastro/astro/blob/main/packages/astro/src/assets/consts.ts#L3) definition, `svg` is missing.

Possible SVG related issue: https://github.com/withastro/astro/issues/6101

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-svg-asset-image-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by TechAurelian** [comment]
The Astro [Assets guide](https://docs.astro.build/en/guides/assets/) hints to SVG support in this example:

![image](https://user-images.githubusercontent.com/108275944/223656298-d10e9969-78a9-40da-85a5-bd35bcc0dfb3.png)

**Comment by Princesseuh** [comment]
Arf, of course we had to let one mistake slip through, ha!

Not supporting SVGs is intended at this time, so this is exclusively a docs issue, will fix that, thanks!

**Comment by TechAurelian** [comment]
@Princesseuh When do you expect SVG to be supported? It's not necessarily about optimizing (because it can be done with tools like [SVGOMG](https://jakearchibald.github.io/svgomg/), but about automatically selecting the correct `width` and `height` for SVG images, that could be very useful to avoid Content Layout Shift (CLS).

I'm using quite a few SVG files on each site with the `<img />` tag, so I created my own solution using the `image-size` Node package, but a built-in solution would be great!

```ts
export function getLocalImageSize(src) {
  const computedSrc = src.replace(LOCAL_PREFIX, './public/assets/images/');
  const dimensions = sizeOf(computedSrc);
  if (!dimensions || !dimensions.width || !dimensions.height) {
    throw new Error(`Failed to get dimensions for local image: ${computedSrc}`);
  }
  return {
    width: dimensions.width,
    height: dimensions.height,
  };
}
```

**Comment by Princesseuh** [comment]
For just the ESM shape, I'll see about adding it today. That part can be in scope for sure!

**Comment by vinhphm** [comment]
> For just the ESM shape, I'll see about adding it today. That part can be in scope for sure! Just need some error handling for the Image component to reject SVGs at this time.

Yup, I was stuck yesterday because Astro keep telling 'remote images need width and height' while I didn't have any. Later, I found out it was because of SVGs.

**Comment by TechAurelian** [comment]
@Princesseuh Thank you, it works now... for importing static (hardcoded?) SVG files, like in the documentation:

`import rocket from '../assets/images/rocket.svg'`

The larger issue is about dynamic imports. 

For example if I have an `.astro` component, and I want to send an asset image src / url as prop, if I try

`const svgImage = await import(srcProp);`

I get the `The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.` warning.

I could static import the image and send the `ImageAsset` to the component, but what if the image src / url is a front matter property of a content collection entry?

I know this is a larger issue. Where do you think would be the best place to discuss this?

Note: I found this somehow related comment: https://github.com/withastro/astro/issues/6061#issuecomment-1410447757

**Comment by Princesseuh** [comment]
> @Princesseuh Thank you, it works now... for importing static (hardcoded?) SVG files, like in the documentation:
> 
> `import rocket from '../assets/images/rocket.svg'`
> 
> The larger issue is about dynamic imports.
> 
> For example if I have an `.astro` component, and I want to send an asset image src / url as prop, if I try
> 
> `const svgImage = await import(srcProp);`
> 
> I get the `The above dynamic import cannot be analyzed by Vite. See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.` warning.
> 
> I could static import the image and send the `ImageAsset` to the component, but what if the image src / url is a front matter property of a content collection entry?
> 
> I know this is a larger issue. Where do you think would be the best place to discuss this?
> 
> Note: I found this somehow related comment: [#6061 (comment)](https://github.com/withastro/astro/issues/6061#issuecomment-1410447757)

For the frontmatter use case, our official recommendation would be to use the new `image()` schema: https://docs.astro.build/en/guides/assets/#update-content-collections-schemas

Apart from that, yeah, there's no real ways to work around the dynamic import issue. Vite (and Astro) are just not made that way.

**Comment by ankushg** [comment]
> Not supporting SVGs is intended at this time, so this is exclusively a docs issue, will fix that, thanks!

Is there a ticket we can follow for adding support for SVGs, even if it's an explicit [`unoptimized` flag a la `next/image`](https://nextjs.org/docs/api-reference/next/image#unoptimized)? 

Having to keep track of the format of my images so I know when to use `img` instead of `Image` is making things feel very clunky.
