### ISSUE TITLE
assets: relative paths in markdown files work in dev, but not in SSG build

### ISSUE THREAD

**Issue by mashehu** [withastro/astro#6462]
### What version of `astro` are you using?

2.1.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Hi,

I am trying to use the new assets feature and I have markdown files (which I fetch from a different local repo using `Astro.glob`) with relative image paths there. These work fine during dev mode, but when I try to make a static build, I get
```
Error [RollupError]: Failed to parse Markdown file "/Users/matho180/MultiQC/docs/core/development/plots.md":
The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../MultiQC/docs/images/cbrewer_scales.png".
    at error (file:///Users/matho180/MultiQC_website/node_modules/rollup/dist/es/shared/node-entry.js:2105:30)
    at FileEmitter.emitFile (file:///Users/matho180/MultiQC_website/node_modules/rollup/dist/es/shared/node-entry.js:23804:24)
    at Object.resolveImage (file:///Users/matho180/MultiQC_website/node_modules/astro/dist/vite-plugin-markdown/index.js:55:23)
    at async file:///Users/matho180/MultiQC_website/node_modules/@astrojs/markdown-remark/dist/remark-collect-images.js:16:20 {
  code: 'VALIDATION_ERROR'
}
```
The relative paths in this error messages are already resolved from `../../images` and correct from the perspective of the website repo.

I linked the respective repo branch below.

### Link to Minimal Reproducible Example

https://github.com/mashehu/MultiQC_website/tree/switch-to-assets

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I'm finding a dev bug, but not the build bug you are reporting. What is different here? https://stackblitz.com/edit/github-mnzpmy-p1csgv?file=astro.config.mjs,src%2Fpages%2Findex.md&on=stackblitz

**Comment by mashehu** [comment]
found a way to reproduce the error. works in dev, but not on build: https://stackblitz.com/edit/github-mnzpmy-gckpwj?file=astro/src/pages/[slug].astro

**Comment by mashehu** [comment]
okay, 2.1.2 made it also stop working in dev mode 😞

**Comment by matthewp** [comment]
Thanks for the repro! Will look into it tomorrow. This is an experimental feature. Thanks for your patience.
