### ISSUE TITLE
assets: images can't be opened on windows. An extra C: is appended at the start of the file

### ISSUE THREAD

**Issue by mandar1jn** [withastro/astro#6464]
### What version of `astro` are you using?

2.1.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Given the following import: `import heroImage from "@assets/images/foto.jpg"` and the following component: `<Image width={600} height={800} src={heroImage} format="avif" alt="A picture of me" loading={"eager"} />` the development server crashes with a file not found:
```cmd
C:\Users\Marijn\source\repos\mandar1jn\portfolio>yarn dev
yarn run v1.22.19
$ astro dev
   astro  v2.1.0 started in 168ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

05:47:58 PM [content] Watching src/content/ for changes
05:47:58 PM [astro] update C:/Users/Marijn/source/repos/mandar1jn/portfolio/.astro/types.d.ts
05:47:58 PM [content] Types generated
05:48:51 PM [astro] reload C:/Users/Marijn/source/repos/mandar1jn/portfolio/src/pages/index.astro
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open 'C:\C:\Users\Marijn\source\repos\mandar1jn\portfolio\src\assets\images\foto.jpg'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\C:\\Users\\Marijn\\source\\repos\\mandar1jn\\portfolio\\src\\assets\\images\\foto.jpg'
}

Node.js v18.14.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

this error doesn't give much info, but the page does load before the server crashes so I did some research. Decoding the source url for the affected image, I get the following url: `/_image?href=file:///C:/Users/Marijn/source/repos/mandar1jn/portfolio/src/assets/images/foto.jpg?origWidth=763&origHeight=764&origFormat=jpg&w=600&h=800&f=avif`

I'm guessing that the issue lies in the three forward slashes before the file path. Therefore, my guess is that the issue lies in [this](https://github.com/withastro/astro/blob/9d48328287348a2d00103807352d66c405c7bc7e/packages/astro/src/assets/vite-plugin-assets.ts#L121-L153) function or a function called by that function/

### Link to Minimal Reproducible Example

None. Just try importing a image on a windows machine I guess

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by phenomen** [comment]
Same here, in my case it's double `D:\`
```
[Error: ENOENT: no such file or directory, open 'D:\D:\Github\my-company\src\assets\people\john-smith.png'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\D:\Github\my-company\src\assets\people\john-smith.png'
}
```
Windows 11, Node v19.7.0

**Comment by jaycedotbin** [comment]
My case is a full repository path:

![image](https://user-images.githubusercontent.com/64476715/223907426-8517d363-df4f-442c-949e-738f4444a1a2.png)

**Comment by matthewp** [comment]
This was fixed by https://github.com/withastro/astro/pull/6466

**Comment by jaycedotbin** [comment]
@matthewp please reopen this issue as this is still not resolved in Windows, the error still happens, and I use Astro 2.1.2. I tested it both in the content directory and in the pages directory.

The same error still appears:
![image](https://user-images.githubusercontent.com/64476715/224489561-3f4db310-2936-400c-bf78-9c494f089dac.png)
