### ISSUE TITLE
assets: Vercel's serverless function crashes

### ISSUE THREAD

**Issue by vinhphm** [withastro/astro#6470]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

After migrated to assets folder and ran dev in localhost, everything went well.
Then I deployed to Vercel, with the latest integration package (3.2.0), the build succeeded but then when I accessed the site, the serverless function failed with error as below in the logs:
```
Cannot find module 'image-size'
Require stack:
- /var/task/dist/chunks/astro.0e1c7d6a.mjs
Did you forget to add it to "dependencies" in `package.json`?
RequestId: 2feb46af-d7d4-4854-9e51-0c4cd3b61b89 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```
Here is the link to the preview deployment: https://vinh-dev-git-assets-vinhphm.vercel.app/

### Link to Minimal Reproducible Example

None. I don't think I can reproduce it in Stackblitz since it related to Vercel

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hmm, seems like one of our dependency is getting externalized by mistake, will take a look thank you!

Sorry for the inconvenience

**Comment by vinhphm** [comment]
I just updated to version 2.1.3, and it seems to have a new issue in the serverless function. Here is what on the log:
```
Invoke Error 	{"errorType":"Error","errorMessage":"socket hang up","code":"ECONNRESET","stack":["Error: socket hang up","    at connResetException (node:internal/errors:718:14)","    at Socket.socketOnEnd (node:_http_client:520:23)","    at Socket.emit (node:events:525:35)","    at endReadableNT (node:internal/streams/readable:1359:12)","    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"]}
```

**Comment by JayBox325** [comment]
I'm getting this error too. I've stripped out everything (it did have Sanity integrated) but it's now just two blank HTML templates and I'm still getting this with my config being:

```
import { defineConfig } from 'astro/config';
import vercelServerless from '@astrojs/vercel/serverless';

export default defineConfig({
  // Vercel
  output: "server",
  adapter: vercelServerless()
});
```
