### ISSUE TITLE
Type error on mdx integration

### ISSUE THREAD

**Issue by christian-hackyourshack** [withastro/astro#6475]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

WSL2/Debian

### Describe the Bug

In my astro.config.ts TypeScript (with the recommended strict settings) complains about incompatible types for the mdx integration:

```
Type 'IntegrationWithPrivateHooks' is not assignable to type 'AstroIntegration'.
    The types of 'hooks['astro:config:setup']' are incompatible between these types.
```

Nevertheless it builds ~~and the same error is not showing up in Stackblitz~~.

Versions:
astro: 2.1.2
@astrojs/mdx: 0.18.0
node: 18.12.1
TypeScript: 4.9.4

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pktrxh?file=astro.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by selrond** [comment]
Here’s the full error:

```sh
Type 'IntegrationWithPrivateHooks' is not assignable to type 'false | AstroIntegration | (false | AstroIntegration | null | undefined)[] | null | undefined'.
  Type 'IntegrationWithPrivateHooks' is not assignable to type 'AstroIntegration'.
    The types of 'hooks['astro:config:setup']' are incompatible between these types.
      Type '(params: { config: AstroConfig; command: "dev" | "build" | "preview"; isRestart: boolean; updateConfig: (newConfig: Record<string, any>) => void; addRenderer: (renderer: AstroRenderer) => void; addWatchFile: (path: string | URL) => void; injectScript: (stage: InjectedScriptStage, content: string) => void; injectRout...' is not assignable to type '(options: { config: AstroConfig; command: "dev" | "build" | "preview"; isRestart: boolean; updateConfig: (newConfig: Record<string, any>) => void; addRenderer: (renderer: AstroRenderer) => void; addWatchFile: (path: string | URL) => void; injectScript: (stage: InjectedScriptStage, content: string) => void; injectRou...'.
        Types of parameters 'params' and 'options' are incompatible.
          Type '{ config: import("/Users/USER/Projects/blog/node_modules/astro/dist/@types/astro").AstroConfig; command: "dev" | "build" | "preview"; isRestart: boolean; updateConfig: (newConfig: Record<...>) => void; addRenderer: (renderer: import("/Users/USER/Projects/blog/node_modules/astro/dist/@types/astro").AstroRendere...' is not assignable to type '{ config: import("/Users/USER/Projects/blog/node_modules/astro/dist/@types/astro").AstroConfig; command: "dev" | "build" | "preview"; isRestart: boolean; updateConfig: (newConfig: Record<...>) => void; addRenderer: (renderer: import("/Users/USER/Projects/blog/node_modules/astro/dist/@types/astro").AstroRendere...'. Two different types with this name exist, but they are unrelated.
            Type '{ config: AstroConfig; command: "dev" | "build" | "preview"; isRestart: boolean; updateConfig: (newConfig: Record<string, any>) => void; addRenderer: (renderer: AstroRenderer) => void; addWatchFile: (path: string | URL) => void; injectScript: (stage: InjectedScriptStage, content: string) => void; injectRoute: (injec...' is missing the following properties from type '{ addPageExtension: (extension: string) => void; addContentEntryType: (contentEntryType: ContentEntryType) => void; }': addPageExtension, addContentEntryType
```

**Comment by ematipico** [comment]
Hi @christian-hackyourshack , I just opened your minimal example, but I can't see any error. How can we trigger the issue?

**Comment by HiDeoo** [comment]
> the same error is not showing up in Stackblitz

> I just opened your minimal example, but I can't see any error.

You can get the error to show up in StackBlitz  by switching the tsconfig extended configuration from `base` to `strict`.

Here is a [direct link](https://stackblitz.com/edit/github-pktrxh-gjzrre?file=astro.config.ts) to the same sandbox forked with the error visible.

I personally get this error when combining the MDX integration into [a preset](https://docs.astro.build/en/reference/integrations-reference/#combine-integrations-into-presets).

**Comment by christian-hackyourshack** [comment]
I updated the original repro according to @HiDeoo 's comment (Thanks for the hint 👍)

**Comment by valxntine** [comment]
Hey, sorry to drag this up, I recently added the MDX integration and ran into the same error, but for some reason adding `skipLibCheck` to my `tsconfig.json` doesn't work. Anyone have any ideas?

**Comment by valxntine** [comment]
Okay so for anyone else reading this - I came back to an old project and ran into this issue. Updating to `v2.9.1` of astro seems to have fixed the issue!
