### ISSUE TITLE
<Picture /> not creating images on Vercel SSR

### ISSUE THREAD

**Issue by pijusz** [withastro/astro#6479]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

Vercel SSR

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

When using static output, Picture generates all of the images. But with Vercel SSR (with and without prerender) Picture images are not generated

Blitz is for example purposes, but does not reproduce error. It has to be done with Vercel SSR adapter

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5okmvb?file=package.json,src%2Fpages%2Findex.astro,astro.config.mjs,tsconfig.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pijusz** [comment]
Update:
It seems that in production website (with `prerender=true`), generates image in 30seconds+ and then it is saved. Since production website also uses CMS, it becomes not that useful.

Side topic: I understand its fair that generation takes long (I added all of the formats and 5 image sizes). It just has to initially generate image on buildtime.

**Comment by Princesseuh** [comment]
Hello! We are entering maintenance mode on `@astrojs/image` in favor of the new `astro:assets` feature. The new feature has better support for `prerender` pages and the images should now be properly built at build time for those pages. I would also check out the `sharp`-based image service for much better performance. <https://docs.astro.build/en/guides/assets/#using-sharp>

**Comment by pijusz** [comment]
I've been using Sharp from very beginning, will you add Picture to astro:assets also?
