### ISSUE TITLE
Astro.clientAddress is not available in the @astrojs/vercel/serverless adapter

### ISSUE THREAD

**Issue by isobecci** [withastro/astro#6481]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

@astrojs/vervel@3.1.3 is works well. but @astrojs/vervel@3.1.4 and @astrojs/vervel@3.2.0 are not work because clientAddressNotAvailable: `Astro.clientAddress` is not available in the `@astrojs/vercel/serverless` adapter. File an issue with the adapter to add support.

### Link to Minimal Reproducible Example

https://github.com/isobecci/welcome-to-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Looks like it was removed here, I'm sure by mistake. Will take a look at adding it back. https://github.com/withastro/astro/commit/0e378c3b87627ca2764872a426dfba0a1606f991

**Comment by doganalper** [comment]
This is currently happening to me on builds. My Astro version is `3.6.4` and my `@astrojs/vercel` is `4.0.5`.
