### ISSUE TITLE
`astro build` shows duplicate lines in the log

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/astro#6489]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows and Linux

### Describe the Bug

I just build [my site](https://github.com/torn4dom4n/torn4dom4n.github.io) with Astro v2.1.2 and I see [this log](https://github.com/torn4dom4n/torn4dom4n.github.io/actions/runs/4377119434/jobs/7660172919):

```log
 generating optimized images 
  ▶ /_astro/me.ff60ed41_1g8my4.jpg (before: 51kb, after: 13kb) (+666ms)
  ▶ /_astro/logo.759d98d5_Z1SJ5Wi.png (before: 3kb, after: 1kb) (+152ms)
  ▶ /_astro/logo.759d98d5_Z1SJ5Wi.png (before: 3kb, after: 1kb) (+112ms)
```

It shows 2 lines `/_astro/logo.759d98d5_Z1SJ5Wi.png (before: 3kb, after: 1kb) (+152ms)` at the end.
BTW, in the `_astro` folder, I see both optimized images and unoptimized images. I think we just need optimized images because it'll reduce the project's size.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/torn4dom4n/torn4dom4n.github.io

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
> I see both optimized images and unoptimized images. I think we just need optimized images because it'll reduce the project's size.

This is currently intended, ESM importing an image into the project includes it (so a file gets created), and then using the Image component / getImage creates another asset.
