### ISSUE TITLE
Assets does not respect `~/assets/*` alias in markdown files

### ISSUE THREAD

**Issue by leuke-naam** [withastro/astro#6490]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

[Documentation](https://github.com/withastro/roadmap/blob/feat/core-image-story/proposals/0030-core-image-story.md) suggests that an asset referenced in markdown files using the alias `~/assets/file.jpg` will be found. The result is that an asset will be undefined. If an assets is referenced as `./file.jpg` it will be found but yields errors when running the `dev` and `build` command.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7mkcho

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
When using images in content collections, every asset in the frontmatter is already relative to the assets folder, as such, the proper format is the following for an image at `src/assets/image.png`

```
cover: image.png
```

As for the error, this is currently being worked on, sorry for the inconvenience. We're hoping to release a fix soon!

**Comment by leuke-naam** [comment]
Thanks for the quick reply! Will aliases work in the future or should I wait until fix and use the relative path?

**Comment by Princesseuh** [comment]
I'd recommend using a relative path, we are still not sure of the featureset we want there and it might take a while before aliases are supported (if they ever are)

**Comment by Princesseuh** [comment]
Closing this issue since the fix has been merged, we'll do a release with it shortly.

Sorry again for the inconvenience!

**Comment by patriciatiffany** [comment]
New to Astro here. Reading the docs, it still seems to suggest that aliases specified in `tsconfig.json` would work for content collections:

> Images in content collections will be processed the same way they are in [Markdown](https://docs.astro.build/en/guides/images/#images-in-markdown-files) and [MDX](https://docs.astro.build/en/guides/images/#images-in-mdx-files) depending on which file type you are using.
