### ISSUE TITLE
Astro cookies not works

### ISSUE THREAD

**Issue by dmitryuck** [withastro/astro#6499]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Windows 11

### What browser are you using?

Chrome

### Describe the Bug

in this case `hasCookie` is always false, but cookie is set

```
const hasCookie = Astro.cookies.has("lang");
if (!hasCookie) {
    // This executes every time when page refresh, but cookie is set and I see it in the dev tools
    Astro.cookies.set("lang", "en" , { maxAge: 604800 });
}
```

### Link to Minimal Reproducible Example

no

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@dmitryuck It would be great if you could share a minimal example (stackblitz or github), so we know what kind of use case you're running.

**Comment by dmitryuck** [comment]
https://stackblitz.com/edit/withastro-astro-yodjbw?file=src/pages/index.astro

**Comment by ematipico** [comment]
Astro shows a warning:

```shell
17:33:54 [ssg] Headers are not exposed in static (SSG) output mode. To enable headers: set `output: "server"` in your config file.
```

**Comment by dmitryuck** [comment]
yes, I see, I can't use cookies in SSG mode, only on the client side
thank you for clarifying.

**Comment by ZeldOcarina** [comment]
So how would you access cookies in ssg? Through a middleware?

**Comment by rustinwelter** [comment]
@ZeldOcarina 

[This](https://docs.astro.build/en/guides/server-side-rendering/#astrorequestheaders) probably answers your question.

**Comment by ZeldOcarina** [comment]
Yeah I read those but afaiu cookies cannot work in ssg as there's no server runtime going on, did I get it completely wrong?
Sorry for asking a stupid question in case..

**Comment by rustinwelter** [comment]
@ZeldOcarina 

Sorry, I took it as ssr instead of ssg. You are right. As you have mentioned earlier, you can probably only use middleware.

**Comment by rustinwelter** [comment]
@ZeldOcarina 

Hey, I'm sorry for saying this afterwards, as I should've it beforehand... but seems like you can set cookies with middleware. Though, I haven't checked it thoroughly.

This is the code I used in middleware.ts

```typescript

import { defineMiddleware } from "astro/middleware";

export const onRequest = defineMiddleware(
  (context, next) => {
    context.cookies.set("hello", "hello");
    console.log(context.cookies.get("hello"));
    return next();
  }
```

It returns this in the console `AstroCookie { value: 'hello' }`

**Comment by ZeldOcarina** [comment]
Hey amazing thanks a lot I'll give it a try!
