### ISSUE TITLE
I want to use VITE's base option to prefix static resource prefix with "https://my.cdn.com", but it does not take effect

### ISSUE THREAD

**Issue by wangxiao95** [withastro/astro#6500]
### What version of `astro` are you using?

2.0.18

### Are you using an SSR adapter? If so, which one?

ssr

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I want to use VITE's base option to prefix static resource prefix with "https://my.cdn.com", but it does not take effect
【vite base】
Type: string
Default: /
Base public path when served in development or production. Valid values include:

Absolute URL pathname, e.g. /foo/
Full URL, e.g. https://foo.com/
Empty string or ./ (for embedded deployment)
See [Public Base Path](https://vitejs.dev/guide/build.html#public-base-path) for more details.

How to achieve the effect of “full url”

### Link to Minimal Reproducible Example

any

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
@wangxiao95 can you link a reproduction example using Stackblitz so that we can validate and isolate the issue?

**Comment by rishi-raj-jain** [comment]
Should be as simple as using BASE_URL: https://docs.astro.build/en/guides/environment-variables/#:~:text=import.meta.env.BASE_URL%3A%20The%20base%20url%20your%20site%20is%20being%20served%20from.%20This%20is%20determined%20by%20the%20base%20config%20option.

**Comment by bluwy** [comment]
I don't think Astro supports this at the moment. The feature is tracked at https://github.com/withastro/roadmap/discussions/456
