### ISSUE TITLE
Image assets paths not correctly resolved if using URL base in site config

### ISSUE THREAD

**Issue by songololo** [withastro/astro#6504]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I'm trying the new experimental assets optimisation for images.

During development everything works as intended.

When building the site, everything works as intended when using a base path prefix of `/`.

However, the build breaks if using a base path other than `/`, e.g. if using `test` as a basepath, then it tries to use the following style of path:
`error   ENOENT: no such file or directory, open '/path/to/repo/astro-minimal/dist/test/_astro/ginger_cat.509f05b4.jpeg'`

Note that `test` has been inserted between `dist` and `_astro`.

### Link to Minimal Reproducible Example

https://github.com/songololo/astro-minimal

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Thank you for submitting this issue! I just renamed the issue to clear up any possible confusion with the old `@astrojs/image` integration.
