### ISSUE TITLE
page prop is type never with InferGetStaticPropsType as it has no signature matching the paginate function

### ISSUE THREAD

**Issue by david-abell** [withastro/astro#6507]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

windows

### What browser are you using?

chrome

## InferGetStaticPropsType does not work with ` getStaticPaths({ paginate } {...}`

The new helper type `type Props = InferGetStaticPropsType<typeof getStaticPaths>` does not work when used with `getStaticPaths()` and the paginate option such as the basic docs pagination example [found here](https://docs.astro.build/en/core-concepts/routing/#pagination).

See below codesandbox run script `check`

The signature  infers types from a function with no arguments `T extends () =>...`
```typescript
export type InferGetStaticPropsType<T> = T extends () => Promise<infer R> ? R extends Array<infer U> ? U extends {
    props: infer P;
```
I tried modifying the signature to accept parameters:
```typescript
 export type InferGetStaticPropsType<T> = T extends (...args: any[]) => Promise<infer R> ...
```

I was specifically trying to use this with collections:

```typescript
export const getStaticPaths: GetStaticPaths = async ({ paginate }) => {
  const collection = (await getCollection('projects')).sort((a, b) => a.data.pubDate.valueOf() - b.data.pubDate.valueOf());
  return paginate(collection, { pageSize: 6 });
};
```

The paginate function appears not to return the collection type of `CollectionEntry<"projects">[]`  but instead returns only `type GetStaticPathsResult`. It would be nice if this were a generic so that inferGetStaticPropsType could infer the collectionEntry as Props.

The old way still of course works as expected:

```typescript
interface Props {
  page: Page<CollectionEntry<'projects'>>;
}

const { page } = Astro.props;
```

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/github/withastro/astro/tree/latest/examples/blog?on=codesandbox&file=%2FREADME.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
The problem isn't that it doesn't work with `paginate`, it's that it doesn't work when `getStaticPaths` is typed because then it does not infer the return value

This is a bit challenging to fix, I'll investigate more..

**Comment by Princesseuh** [comment]
Since this is not possible to fix, I instead updated the documentation to point towards `satisfies`: <https://github.com/withastro/docs/pull/2963>

Additionally, the investigation here led to find an unrelated issue with it, fixed it here: <https://github.com/withastro/astro/pull/6711> (this PR also updates the comments to show the proper way to do it)
