### ISSUE TITLE
@astrojs/vercel not bundling undiscoverable required dependencies

### ISSUE THREAD

**Issue by cb1kenobi** [withastro/astro#6509]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm and pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When deploying a vanilla Astro site with markdown to Vercel using the `@astrojs/vercel` serverless adapter, not all dependencies are being discovered. `@astrojs/vercel` uses `@vercel/nft` to discover imported dependencies, however the `@astrojs/markdown-remark` import is explicitly obfuscated to prevent this module from being discovered: https://github.com/withastro/astro/blob/f6eddffa0414d54767e9f9e1ee5a936b8a20146b/packages/astro/src/core/render/result.ts#L229-L234

As a possible solution, `@astrojs/vercel`'s nft wrapper library (https://github.com/withastro/astro/blob/f6eddffa0414d54767e9f9e1ee5a936b8a20146b/packages/integrations/vercel/src/lib/nft.ts) could whitelist `@astrojs/markdown-remark` and likely others (possibly including `image-size`, `inherits`, and `queue`) so that they will properly be bundled.

As a hacky workaround, users can explicitly glob those dependencies and include them like this:

```
import { defineConfig } from 'astro/config'

import vercel from '@astrojs/vercel/serverless'
import glob from 'glob'

// https://astro.build/config
export default defineConfig({
  output: 'server',
  adapter: vercel({
    includeFiles: [
      ...glob.sync('./node_modules/@astrojs/markdown-remark/**'),
      ...glob.sync('./node_modules/image-size/**'),
      ...glob.sync('./node_modules/inherits/**'),
      ...glob.sync('./node_modules/queue/**'),
    ],
  }),
})
```

### Link to Minimal Reproducible Example

https://github.com/rechenberger/astro-vercel

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Why do you need `@astrojs/markdown-remark` at runtime? Is this for the `<Markdown>` component?

**Comment by cb1kenobi** [comment]
I think the intention is we don't need `@astrojs/markdown-remark` at runtime because it will have been bundled into the generated serverless function, however the `@astrojs/vercel` adapter uses `nft` to bundle dependencies and it doesn't see that `@astrojs/markdown-remark` is being used, so it doesn't bundle it.

I have no idea if this is for the `<Markdown>` component. The issue was reported to Vercel, but I believe the problem is in Astro's code. I linked to the reproducible example in the description.

**Comment by matthewp** [comment]
Ok thanks! We've deprecated the `<Markdown>` component which I think is the likely culprit here as it was previously dynamically importing that module. Closing as nothing to fix here any more.
