### ISSUE TITLE
Build breaks with @sentry/vite-plugin

### ISSUE THREAD

**Issue by WesSouza** [withastro/astro#6513]
### What version of `astro` are you using?

2.1.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm or pnpm

### What operating system are you using?

Mac and Linux

### What browser are you using?

Chrome or Safari

### Describe the Bug

Running astro with Vercel and `@sentry/vite-plugin` used to work on 1.x, but stopped once 2.0 was released.

When building, `astro.config.mjs` fails:

```
07:47:23 AM [astro] Unable to load /home/projects/github-ftsaxu-yjuz4p/astro.config.mjs

 error   __vite_ssr_import_2__.default is not a function
  File:
    file://file:///home/projects/github-ftsaxu-yjuz4p/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52468:9
  Stacktrace:
TypeError: __vite_ssr_import_2__.default is not a function
    at eval (/home/projects/github-ftsaxu-yjuz4p/astro.config.mjs:17:34)
    at async instantiateModule (file://file:///home/projects/github-ftsaxu-yjuz4p/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52468:9)
```

It seems the issue is not related to the Vercel adapter or React integration.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ftsaxu-yjuz4p?file=astro.config.mjs,package.json&on=stackblitz

**Comment by bluwy** [comment]
According to its docs, you need to import it like this:

```js
import { sentryVitePlugin } from '@sentry/vite-plugin';
```

Even with that fixed, the repro has another cryptic error. It's improved in the next Vite minor though, which I get a clearer message:

```
6:11:29 PM [vite] Error when evaluating SSR module /Users/bjorn/Work/repros/astro-sentry/astro.config.mjs: failed to import "@astrojs/react"

06:11:29 PM [astro] Unable to load /Users/bjorn/Work/repros/astro-sentry/astro.config.mjs

 error   Cannot find package 'react-dom' imported from /Users/bjorn/Work/repros/astro-sentry/node_modules/.pnpm/@astrojs+react@2.1.0/node_modules/@astrojs/react/dist/index.js
```

After installing `react` and `react-dom`, it works for me.
