### ISSUE TITLE
The ImageAsset interface from the Assets guide is not defined

### ISSUE THREAD

**Issue by TechAurelian** [withastro/astro#6514]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

The `ImageAsset` interface from the [Assets guide](https://docs.astro.build/en/guides/assets/#update-content-collections-schemas) is not defined anywhere in Astro, only in the docs.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/108275944/224485035-a33fd7d1-e1f3-4e8a-b2ff-0ee3e941abba.png">

Are we supposed to define it ourselves if needed? Shouldn't it be importable from `astro:assets`?

I want to create an Astro component that receives an ImageAsset prop. (I can't send the image src / url because then I would have to do a dynamic import, and [that's not ok](https://github.com/withastro/astro/issues/6452#issuecomment-1461658423).)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-svg-asset-image-bug?file=src/pages/index-png.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tomafro** [comment]
Is this meant to be the same interface as `ImageMetadata`, defined in `client-image.d.ts`? Only difference seems to be that the format is restricted in `ImageMetadata` to one of `'avif' | 'gif' | 'heic' | 'heif' | 'jpeg' | 'jpg' | 'png' | 'tiff' | 'webp'` (so doesn't look like `svg` is supported).

**Comment by Princesseuh** [comment]
This interface actually already exists, but it's not exported. I'll fix this among some other small types issues I've noticed. Fix should be out today!
