### ISSUE TITLE
Cannot find module 'astro:assets' imported from "examplepath"

### ISSUE THREAD

**Issue by Hinterberger-Thomas** [withastro/astro#6515]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

chrome

### Describe the Bug

I just tried to import the experimental image component but it showed me an error that it could not find the image component. I looked into my node_modules and the image component exists, so, I do not really know what the problem is.

### Link to Minimal Reproducible Example

https://github.com/Hinterberger-Thomas/astro-testinger

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by leuke-naam** [comment]
You must set `experimental.assets` to `true` or use the flag `--experimental-assets` in order to use `astro:assets`. You can update your `astro.config.mjs` to be something like this: 

```js
import { defineConfig } from "astro/config";

import tailwind from "@astrojs/tailwind";

// https://astro.build/config
export default defineConfig({
  integrations: [tailwind()],

  // 👇
  experimental: { assets: true },
});
```

**Comment by Hinterberger-Thomas** [comment]
oh sry my fault did forget that step, thanks very much!
