### ISSUE TITLE
Very large `exclude` attribute on  `_routes.json` file, crashing deployments on Cloudflare Pages

### ISSUE THREAD

**Issue by Odas0R** [withastro/astro#6516]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

Cloudflare @6.2.0

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

I have my fonts locally and there are at most 500 files. These files get bundled onto `_astro` and added to `_routes.json` to the `excluded` param, producing then the following error:

```text
Error: Failed to publish your Function. Got error: Error 8000057: Rules in `_routes.json` are over the 100 rule limit. Refer to https://cfl.re/3FsE4aF.
```

I'm a bit confused about what is actually required to be on the `_routes.json`...

On the https://stackblitz.com/edit/github-jllrss?file=dist/_routes.json I show that the woff is excluded (even though it is a fake file). Imagine having 500+ files? Throws the error above

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jllrss?file=dist/_routes.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Looks like our `_routes.json` handler can be made smarter to use globs if there's a directory in `/public`. In this case, the repro could generate:

```json
{
  "version": 1,
  "include": [
    "/*"
  ],
  "exclude": [
    "/_worker.js",
    "/favicon.svg",
    "/fonts/*"
  ]
}
```

instead. There's a risk that the SSR handler might need to handle some endpoints in `/fonts/*` though, but I think it's an edgecase that we can ignore for now.

**Comment by AirBorne04** [comment]
hey @Odas0R,

the issue is that we need to exclude all files from the routes, otherwise cloudflare will hit the worker instead of just loading the file directly. (That works but comes with the cost of worker invocation) To not create an issue by trying to be smart the compiler just renders a full list of items into the `_routes.json` this might create a problem likes yours, but for that case you are able to create a custom `_routes.json` which will be respected.

cc: @bluwy

**Comment by bluwy** [comment]
I think it's worth looking into making it smarter so the users don't have to author the `_routes.json` manually, especially if it's only a problem they'll encounter after they deploy. The page manifest provided in the integration hook could help with this.

**Comment by jankocian** [comment]
Hey all, I came to similar problem due to the _redirects.

My site is fully static with just one preview route, like this: https://logicworks.pages.dev/preview/644b74758c0e6c251a0b9f06?draft=true

So I obviously wanted to take the opposite approach and whitelist only that one particular path...
```
{
  "version": 1,
  "include": [
    "/preview/*"
  ],
  "exclude": [
    "/*"
  ]
}
```

Yet I cannot get it to work - only getting 404s... Any help would be much appreciated.

Thanks a lot!

**Comment by jankocian** [comment]
Let me answer for myself...

Exclude always takes precedence over include! Getting rid of the "/*" from exclude array did the trick :)

**Comment by AkashRajpurohit** [comment]
Bumping this up, for now it may be possible to unblock it by using custom `_routes.json` in public directory. However, as @bluwy mentioned, it would be if the build system is smarter enough to use wildcards for generating excludes instead of dumping all static generated pages.

Also, if no-one is working on this, then would be happy to chime in on it with some help 😄

**Comment by bluwy** [comment]
I don't think anyone is working on this yet, so feel free to take it!

**Comment by Odas0R** [comment]
> hey @Odas0R,
> 
> the issue is that we need to exclude all files from the routes, otherwise cloudflare will hit the worker instead of just loading the file directly. (That works but comes with the cost of worker invocation) To not create an issue by trying to be smart the compiler just renders a full list of items into the `_routes.json` this might create a problem likes yours, but for that case you are able to create a custom `_routes.json` which will be respected.
> 
> cc: @bluwy

Thanks!

I just do some `sed` magic after the build process and it does the job :)

Still sounds weird! The fact that injects all assets on the exclude.

![image](https://github.com/withastro/astro/assets/32167770/c25bc4eb-9ec4-4c40-84c0-568bb0f03606)

This was from the Cloudflare discord a while back when I had this error. Why is every asset being added to the exclude? Seems like if a project gets big enough it will only rise problems.s

**Comment by wassim** [comment]
It's not just about static files like fonts but also static pages. I have like thousands of pages and 1 API endpoint. 

My _routes.json in hybrid mode looks like this, which breaks deployments

```json
{
  "version": 1,
  "include": [
    "/*"
  ],
  "exclude": [
    ...thousands of static pages routes
  ]
}
```

**Comment by Daniel-Freese** [comment]
@wassim in your case it is super easy to write the routes file yourself just add the one dynamic api path into the include.

**Comment by wassim** [comment]
@Daniel-Freese I have an api folder inside pages directory.

I tried this **_routes.json** but doesn't work, any ideas why?
```json
{
    "version": 1,
    "include": ["/api/*"],
    "exclude": []
}
```

**Comment by AkashRajpurohit** [comment]
> @Daniel-Freese I have an api folder inside pages directory.
> 
> I tried this **_routes.json** but doesn't work, any ideas why?
> 
> ```json
> {
>     "version": 1,
>     "include": ["/api/*"],
>     "exclude": []
> }
> ```

I would've expected this to work, what is going wrong with it, can you go into a bit detail?
This seems similar to the [sample example](https://developers.cloudflare.com/pages/platform/functions/routing/#example-configuration) provided by CF as well just that instead of `/*` you are adding `/api/*`

**Comment by isaquedev** [comment]
Any news here? I'm starting to use Astro and faced that problem, with a few icons and some hybrid JS my _routes.json get more than 100 items in exclude.

Is there any way to solve this?

**Comment by AkashRajpurohit** [comment]
> > @Daniel-Freese I have an api folder inside pages directory.
> > I tried this **_routes.json** but doesn't work, any ideas why?
> > ```json
> > {
> >     "version": 1,
> >     "include": ["/api/*"],
> >     "exclude": []
> > }
> > ```
> 
> I would've expected this to work, what is going wrong with it, can you go into a bit detail? This seems similar to the [sample example](https://developers.cloudflare.com/pages/platform/functions/routing/#example-configuration) provided by CF as well just that instead of `/*` you are adding `/api/*`

@isaquedev I have verified that this setup works for now, you can explicitly add a _routes.json file to unblock yourself.

**Comment by schummar** [comment]
I have a pull request open with a possible solution and am looking forward to your feedback. #7846

**Comment by vvashisht** [comment]
> I have a pull request open with a possible solution and am looking forward to your feedback. #7846

Can you please check https://github.com/withastro/astro/pull/7846#issuecomment-1693870028

**Comment by aqueenan** [comment]
The `include` array needs to include all of the pages and server api, and the `exclude` array needs to include the list of static assets in `public`.

The easiest way of doing that is to exclude everything in `public`, plus the generated code in `_astro`. My `public` folder has a bunch of icon files (matching `*.*`) and subfolders for `images` and `plugins`, so I exclude them all with:

```
  adapter: cloudflare({
    routes: {
      "exclude": [
        "/*.*",
        "/_astro/*",
        "/images/*",
        "/plugins/*",
      ],
    }
```
