### ISSUE TITLE
CLI command to automatically open localhost in your browser 

### ISSUE THREAD

**Issue by danny007in** [withastro/astro#6522]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Need feature like https://github.com/vitejs/vite/discussions/8467

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pvsfei?file=README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
I'm on it

**Comment by rishi-raj-jain** [comment]
@matthewp the greater decision could be to expose the flags from cmd passed to createVite function. How does that sound?

https://github.com/vitejs/vite/discussions/8467#:~:text=Jun%204%2C%202022-,You%20can%20do%20that%20with%20server.open%20in%20config%20or%20vite%20%2D%2Dopen%20from%20CLI.,-View%20full%20answer requires detection of the `open` flag. Can you guide me how to access flags in the createVite function https://github.com/withastro/astro/blob/main/packages/astro/src/core/create-vite.ts#L63-L66? Happy to do a PR!

**Comment by bluwy** [comment]
Not Matthew, but you could probably pass the flag [here](https://github.com/withastro/astro/blob/887fae4a1ec768be85dc29867ce77cf0a7817244/packages/astro/src/core/dev/dev.ts#L66-L71) which when you follow down the chain, you can then pass it [here](https://github.com/withastro/astro/blob/887fae4a1ec768be85dc29867ce77cf0a7817244/packages/astro/src/core/dev/container.ts#L82-L96).

**Comment by wulinsheng123** [comment]
I'll try it out then.
I can touch the command module.

**Comment by wulinsheng123** [comment]
> Not Matthew, but you could probably pass the flag [here](https://github.com/withastro/astro/blob/887fae4a1ec768be85dc29867ce77cf0a7817244/packages/astro/src/core/dev/dev.ts#L66-L71) which when you follow down the chain, you can then pass it [here](https://github.com/withastro/astro/blob/887fae4a1ec768be85dc29867ce77cf0a7817244/packages/astro/src/core/dev/container.ts#L82-L96).

Maybe the preview mode needs to support this flag?

**Comment by Princesseuh** [comment]
Closing since this was implemented
