### ISSUE TITLE
Can't set multiple cookies in response on v2

### ISSUE THREAD

**Issue by michael-land** [withastro/astro#6525]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

tried on vercel and node 

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

```ts
    Astro.cookies.set(`is_auth`, '1', {
      httpOnly: true,
      secure: true,
      sameSite: 'strict',
      expires: addMinutes(new Date(), 5),
      path: '/',
    });
    Astro.cookies.set(`authorization`, accessToken, {
      httpOnly: true,
      secure: true,
      sameSite: 'strict',
      expires: addMinutes(new Date(), 5),
      path: '/',
    });
```

<img width="812" alt="image" src="https://user-images.githubusercontent.com/33362998/224557706-b6913071-b267-4eb8-9742-5278f6ffd27c.png">
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/33362998/224557748-7de4c5cf-a1f4-4bd8-8482-82a166ab3499.png">

### Link to Minimal Reproducible Example

todo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! What version of Node are you using? We've recently had a whole dilemma around cookie handling where specific versions of Node behaved differently and stuff, so it would be helpful to know!

**Comment by jeffdrumgod** [comment]
I'm using 18.12 and have the same problem here

**Comment by romanzy313** [comment]
Please reopen the issue, I am having the same problem as @jeffdrumgod. Setting multiple cookies works in build but not in dev. Really makes it impossible to use cookies while developing.

Running `node 18.14.0`, `astro 2.3.3`, `@astrojs/node 5.1.2`

**Comment by matthewp** [comment]
Ok, will recheck.

**Comment by matthewp** [comment]
Think a regression happened here. https://github.com/withastro/astro/pull/6355/files

**Comment by alex-sherwin** [comment]
I'm seeing multiple set-cookie's work in dev and not in prod (nodejs adapter) using current Node LTS v18.16.0 and latest Astro 2.5.5

I'm not even using Astro.cookies at all, this is me directly setting up a Response with a Headers object with multiple set-cookie headers, e.g.

```typescript
const h = new Headers();
h.append("set-cookie", "cookie1=abc");
h.append("set-cookie", "cookie2=abc");
return new Response("abc", { headers });
```

Works in dev, but in prod (using Astro's nodejs adapter) only the first set-cookie is used. 

Feels like a bug with some naive code grabbing only the first occurrence of a key (e.g. "set-cookie" header name), still digging through Astro code to see if I can find the culprit

**Comment by alex-sherwin** [comment]
And there it is https://github.com/withastro/astro/blob/main/packages/integrations/node/src/nodeMiddleware.ts#L52

```typescript
res.writeHead(status, Object.fromEntries(headers.entries()));
```

The line `Object.fromEntries(headers.entries())` is too naive and not accounting for the fact that `Headers` is a special purpose multi-value map (i.e. can contain > 1 value per key), it cannot be converted to a simple object in this manner.

In reading the node spec for `response.writeHead` https://nodejs.org/docs/latest-v18.x/api/http.html#responsewriteheadstatuscode-statusmessage-headers interestingly it does not explicitly state that the object form of supplying headers can accept an array of values (but the docs for `response.setHeader` do say this, so I would assume the behavior is the same)

So this needs to be smarter about building a multi-value object of header key/value pairs

**Comment by matthewp** [comment]
Multiple set-cookie headers is not supported by the Headers API. If you Google you'll see lots of discussion on this.

**Comment by alex-sherwin** [comment]
@matthewp, historically that's correct, however, it is now addressed in the official Fetch spec and now supported in undici since 5.19.0 via `Headers.getSetCookie()`

I opened #7226 and I'm wrapping up a PR now that's based on the built-in `Headers.getSetCookie()` that I think is a pretty clean solution
