### ISSUE TITLE
Top-level `await` in Vue component causes event handling to break

### ISSUE THREAD

**Issue by ffxsam** [withastro/astro#6549]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### What browser are you using?

Chrome

### Describe the Bug

With the Vue integration, using a top-level `await` in a component seems to break event handling.

```vue
<script setup lang="ts">
/** The top-level await causes event handling to not work (button click) */
await new Promise((resolve) => setTimeout(resolve, 1000));

function wow() {
  console.log("wow!!");
}
</script>

<template>
  <div>
    Hello!
    <button @click="wow">Go go go</button>
  </div>
</template>
```

Side-effect bug (maybe a separate issue): I noticed whenever I update the code in the script block, I get an error:
```
runtime-core.esm-bundler.js:6263 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'shapeFlag')
    at getNextHostNode (runtime-core.esm-bundler.js:6263:19)
    at getNextHostNode (runtime-core.esm-bundler.js:6264:20)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5733:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:36)
    at flushJobs (runtime-core.esm-bundler.js:406:17)
```

And if I update the template block:
```
TypeError: instance.update is not a function
    at runtime-core.esm-bundler.js:501:18
    at Array.forEach (<anonymous>)
    at rerender (runtime-core.esm-bundler.js:493:27)
    at Object.rerender (runtime-core.esm-bundler.js:570:20)
    at MyTest.vue:30:25
    at client.ts:614:1
    at client.ts:614:1
    at client.ts:614:1
    at Array.forEach (<anonymous>)
    at queueUpdate (client.ts:614:1)
```

### Link to Minimal Reproducible Example

https://github.com/ffxsam/repro-astro-await-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ffxsam** [comment]
Possibly related:

`<MyComponent client:only="vue" />` will also not render its contents if there's a top-level `await`.

**Comment by ffxsam** [comment]
I'm finding this works better if the `.astro` component does the fetch, then passes the data into the Vue component.

**Comment by natemoo-re** [comment]
> I'm finding this works better if the .astro component does the fetch, then passes the data into the Vue component.

This is generally what we'd recommend, but if top-level await is something Vue components actually support, we should support that as well! I can take a look.

**Comment by MoustaphaDev** [comment]
If I understand correctly [the docs](https://vuejs.org/api/sfc-script-setup.html#top-level-await), Vue components using top-level await must be used in combination with [`Suspense`](https://vuejs.org/guide/built-ins/suspense.html#suspense).

**Comment by ffxsam** [comment]
@MoustaphaDev Thing is, there is no Vue component above this one. The Astro component is the next level up.

@natemoo-re Moustapha is right, typically in a Vue 3 environment, you need to wrap the component that uses top level await in `<Suspense>`. However, Nuxt doesn't require this as they automatically wrap your whole app with `<NuxtPage>` which has suspense built into it.

**Comment by wulinsheng123** [comment]
> > I'm finding this works better if the .astro component does the fetch, then passes the data into the Vue component.
> 
> This is generally what we'd recommend, but if top-level await is something Vue components actually support, we should support that as well! I can take a look.

I want to fix this bug.
COuld you share your idea if you have any ideas ?

**Comment by ffxsam** [comment]
@lioumens No, I went ahead and took the route of not using a top-level await in our Vue components. All the data fetching is handled at the very top by Astro component(s), then passed down into Vue components.

**Comment by JerryWu1234** [comment]
> @ffxsam I'm still getting the `runtime-core.esm-bundler.js` error when updating the script block, when using a top level await. Did that issue go away for you? It seems I still need to create a parent Vue component and manually wrap it with `<Suspense>` for it to update properly.

let me check it
