### ISSUE TITLE
Questions about style import of scss+svelte+astro

### ISSUE THREAD

**Issue by mydracula** [withastro/astro#6551]
### What version of `astro` are you using?

latest 

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

1.How to import `base.scss` globally，I want to use ` @include` or `@extend`
```
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import svelte from '@astrojs/svelte';

saving
export default defineConfig({
  integrations: [mdx(), sitemap(), svelte()],
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "src/styles/base.scss" as *;',
        },
      },
    },
  },
});
```
2.if the import is displayed，I use`@import '$styles/variables.scss';` 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-v55sfg?file=src/components/Test.svelte

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I don't think aliases from tsconfig work in css/scss at the moment, is that the issue you're facing?

**Comment by mydracula** [comment]
> 

yes I want to know how to use the path with astro and scss
