### ISSUE TITLE
Create astro failed in windows with: zlib: unexpected end of file

### ISSUE THREAD

**Issue by lvqq** [withastro/astro#6557]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

pnpm/npm

### What operating system are you using?

Windows

### What browser are you using?

No

### Describe the Bug

Create astro failed in windows cmd and git bash, using both pnpm and npm return the same error:
```
zlib: unexpected end of file
```

Node: v18.15.0/v16.16.0 all failed

![image](https://user-images.githubusercontent.com/29809148/225340920-cf15a851-8b81-46ea-9db3-dc6720ee9922.png)

### Link to Minimal Reproducible Example

Run pnpm/npm create astro@latest in windows

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This usually means the tar file for the template failed to unpack, perhaps of network issues (?). It's usually hard to debug this case, can you reproduce this reliably?

**Comment by lvqq** [comment]
I guess it's not network issue, I can reproduce it reliably on my windows. But on my macbook, it works fine. They are under the same network.

**Comment by bluwy** [comment]
Interesting. I don't have a windows laptop, so I can't reproduce this. I've never seen this error before with `create-astro` though.

**Comment by matthewp** [comment]
Can you provide specific versions of Windows? I tried on Windows 11 and did not see this. Also what specific shell are you using (I was using Powershell).

**Comment by lvqq** [comment]
I'm using Windows 10 and the error occurs both in cmd and git bash
