### ISSUE TITLE
Layout convention prevents HTML streaming

### ISSUE THREAD

**Issue by tropperstyle** [withastro/astro#6561]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

Node.js

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Curl

### Describe the Bug

HTML streaming pauses immediately after the opening `<body>` tag, even if the async component is deep in the document.

In this example, the server should output `<h1>` before pausing for the `<Async>` component.

The `<h1>` tag _is_ output first if the layout component is not used.

It is not clear from the documentation if this is a bug or an inherent limitation of Astro components

----

layout.astro
```
---
const { title } = Astro.props;
---

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>{title}</title>
    </head>

    <body>
        <slot />
    </body>
</html>
```

async.astro
```
---
await new Promise((resolve) => setTimeout(resolve, 5000));
---

<p>Async</p>
```

page.astro
```
---
import Layout from "./layout.astro";
import Async from "./async.astro";
---

<Layout title="Layout Blocks Streaming">
    <h1>Page</h1>
    <Async />
</Layout>
```

$ curl -v http://localhost:3000/page
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Layout Blocks Streaming</title>
    </head>

    <body>

        <!-- Pauses here for 5s -->

        <h1>Page</h1>
        <p>Async</p>
    </body>
</html>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rduhhb-u6t9nb?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, I'll be looking into this next week.

**Comment by bholmesdev** [comment]
I ran into this during a tech demo at a meetup the other day. Wasn't sure if this was intended behavior; sounds like not?

**Comment by matthewp** [comment]
@bholmesdev layouts are weird because we render them to a string. I think that's likely what's going on here, we are rendering it to a string before injecting it. I am going to look into whether anything can be done about this. IIRC the primary reason why we render them to a string is for the Astro.slots APIs.
