### ISSUE TITLE
Using Prisma with static generation

### ISSUE THREAD

**Issue by andresobral** [withastro/astro#6571]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Hi I am trying to use Astro and Prisma and I have a dynamic route like `/[slug].astro` with the following code:

```
---
import { PrismaClient } from '@prisma/client'
import Layout from '../../layouts/Layout.astro'

const prisma = new PrismaClient();

export async function getStaticPaths() {
  const countries = await prisma?.country.findMany({select: {slug: true}});
  return countries.map((country) => ({params: {slug: country.slug}}));
}

const { slug } = Astro.params
---
```

But I get an error `prisma is not defined`.  Any script using node works with this code. Does Astro support such thing? I can do this with Next.js for example.

### Link to Minimal Reproducible Example

not possible

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
The `getStaticPaths` function executes in a different scope, so the variables inside the frontmatter are unavailable to it. You could either declare the prisma client in the function itself or create a separate file where you create and export the prisma client that you'll import in the `[slug].astro` file

**Comment by andresobral** [comment]
Yes, thank you. It works! Summarizing for other, what I did was:

Created a Prisma client in another file

```
import { PrismaClient } from '@prisma/client'

export const prisma = new PrismaClient();
```

And on the `[slug].astro`, I used like this:

```
---
import { prisma } from '../../prisma'
import Layout from '../../layouts/Layout.astro'

export async function getStaticPaths() {
  const countries = await prisma?.country.findMany({select: {slug: true}});
  return countries.map((country) => ({params: {slug: country.slug}}));
}

const { slug } = Astro.params
---
```
