### ISSUE TITLE
Scoped CSS does not apply to Picture

### ISSUE THREAD

**Issue by ZebraFlesh** [withastro/astro#6574]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When using the `<Picture>` element from the `@astrojs/image` integration, the generated `<picture>` tag lacks a scope CSS class (e.g., `class="astro-AUKH742L"`). This prevents authors from targeting these tags with any CSS. The included example is generated from the Portfolio template replaces the main `<img>` tag with a `<Picture>` component and then adds some text before it. It includes the CSS:

```css
.hero > :nth-last-child(-n+2) {
	border: 1px solid hotpink;
}
```

So the last 2 children of the `.hero` container should have a hotpink border. However, only the text above the `<picture>` element renders a border. This is because the `<picture>` is rendered as:

```html
<div class="astro-J7PV25F6">Some text</div>
<picture>
	<source type="image/avif" srcset="/_image?f=avif&amp;w=200&amp;h=258&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 200w,/_image?f=avif&amp;w=400&amp;h=517&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 400w" sizes="(max-width: 375px) 50vw, 75vw"><source type="image/webp" srcset="/_image?f=webp&amp;w=200&amp;h=258&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 200w,/_image?f=webp&amp;w=400&amp;h=517&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 400w" sizes="(max-width: 375px) 50vw, 75vw"><source type="image/jpeg" srcset="/_image?f=jpg&amp;w=200&amp;h=258&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 200w,/_image?f=jpg&amp;w=400&amp;h=517&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 400w" sizes="(max-width: 375px) 50vw, 75vw">
	<img src="/_image?f=jpg&amp;w=400&amp;h=517&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg" loading="lazy" decoding="async" class="astro-J7PV25F6">
</picture>
```

Lack of a scoped CSS class on the `<picture>` tag prevents styling it. It is tempting to say "just style the `img` tag", however, that doesn't work for layout concerns. For example, if the `<picture>` element participates in a CSS grid layout, you can't do something like `justify-self: center;` on it -- such a rule must be applied to the containing `<picture>`, not the child `<img>`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kyjn1r?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by seansmyth** [comment]
Yeah, saw this too.

An easy enough fix is to wrap  the Picture component in a div but yeah, not ideal.

**Comment by ZebraFlesh** [comment]
You work around it still get some scoped CSS with something like`div > :global(picture) { ... }`. The `div` still carries the CSS scoping in this case. (If that winds up being the resolution to this issue, then it really needs to be better documented.)

**Comment by maddsua** [comment]
By the way, does everybody know the reason for choosing the `:where` selector over simple class stacking?
Seems not very durable to me, because this stuff was added like 2 years ago, and it might not work for 100% of users.
For now, I completely disabled scoped styles in my project. Hope this won't go down in flames when I merge into production 😅

**Comment by bluwy** [comment]
It is documented that the additional attributes (including scoped css via the `class` attribute) are passed to the inner `img` only: https://docs.astro.build/en/guides/integrations-guide/image/#picture-

> In addition to the component-specific properties, any valid HTML attribute for the `<img />` included in the `<Picture />` component will be included in the built `<img />.`

Closing this for now.

**Comment by ZebraFlesh** [comment]
@bluwy Just because it's document doesn't mean it's not a bug. Given the current functionality, it is not possible to have a `<Picture>` element participate in individual item rules for CSS grid or even just `nth-child` selectors without using `:global` CSS. That seems unintended.

**Comment by bluwy** [comment]
We can't put both classes in `picture` and `img`. That would cause more unintended effects and future bug reports. Even if it's only making the scoped class on the `picture` tag so it works, that isn't future proof if the scoping behaviour changes in the future (https://github.com/withastro/roadmap/discussions/243). Working around with `.hero > :global(:nth-last-child(-n+2))` would be the best middle ground for now.
