### ISSUE TITLE
Custom Env Variables are invalid in version 2.1

### ISSUE THREAD

**Issue by yisense** [withastro/astro#6575]
### What version of `astro` are you using?

2.1.0

### Are you using an SSR adapter? If so, which one?

node standalone

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Custom .env.test are invalid in vCustom environment variables are invalid in version 2.1, such as .env.test
execute `cross-env NODE_ENV=test astro build --mode test`. But the variables in the .env.production file are still used

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ueaw7y-s1mlqj?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
check right now

**Comment by wulinsheng123** [comment]
Please check your demo.
your demo will get an error

**Comment by wulinsheng123** [comment]
![image](https://user-images.githubusercontent.com/27261522/227158592-17d75175-f26f-4bd8-a554-8dc6db3b5e57.png)

**Comment by songwuk** [comment]
I think this bug in `v2.1.0` - `2.1.6`   
Link: [https://stackblitz.com/edit/github-ueaw7y-83zmbv?file=src%2Fpages%2Findex.astro,package.json](url)

**Comment by wulinsheng123** [comment]
> songwuk

I make sure with a core team member.
this is a bug. I will fix it later

**Comment by wulinsheng123** [comment]
I want to extend to add a new flag `--mode`. 
Also, the user can input the property `mode` in Astro.config.js, the `mode` default is `development`
Because we support the flag `--mode`, But we can't find it in the `Global Flags` array.
@bluwy

**Comment by matthewp** [comment]
@yisense Did Astro have a `--mode` flag in the past? I can't recall it.

**Comment by zoxon** [comment]
Any updates or workarounds?

**Comment by bluwy** [comment]
As the PR was closed due to the scope, we'd need an RFC (https://github.com/withastro/roadmap) for supporting `--mode` to go forward. Closing this for now.

**Comment by JerryWu1234** [comment]
https://github.com/withastro/roadmap/issues
why is here no about this RPC?

**Comment by bluwy** [comment]
I was suggesting to create an RFC (stage 1) there. It doesn't exist yet AFAIA
