### ISSUE TITLE
Duplicated frontmatter field causes the dev server to crash

### ISSUE THREAD

**Issue by MoustaphaDev** [withastro/astro#6587]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Ubuntu 22.04

### What browser are you using?

Irrelevant

### Describe the Bug

Having duplicated frontmatter keys in a markdown or mdx file causes the dev server to crash.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pbwi2s?file=src%2Fcontent%2Fblog%2Ffirst-post.md,src%2Fpages%2Findex.astro,package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
It shouldn't crash for sure, but nonetheless duplicated keys are not supported in YAML, so they shouldn't work

**Comment by MoustaphaDev** [comment]
Right, the crashing behavior is the actual issue
