### ISSUE TITLE
Experiencing hydration errors when passing strings as children to nested client React components

### ISSUE THREAD

**Issue by lokkeestudios** [withastro/astro#6597]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I recently encountered some hydration error messages (server / client mismatch).
It seems like you cannot pass string children to a React component nested in another React component, which has any client directive but `client:load` (e.g. `<Container><Button>This is text</Button></Container>`).
Since this looks like quite the edge case it seems more like a bug than anything else to me, so I decided to create an issue on this.
Passing in the text as a prop or without the React component being the child of another React component, I don't experience these issues.
Furthermore, you can also pass strings as children to components, if they are not React, but Astro components.

Thank you in advance! 😊 

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/mystifying-mayer-6ozvmp?file=%2FREADME.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lokkeestudios** [comment]
After doing some further testing on this it seems like this issue applies to any children which are being passed from an Astro component into a React component (which is nested in another React component).

**Comment by lokkeestudios** [comment]
@matthewp hmm.. weird. Let me know if I can help you in any way to get this issue resolved 🙂
I mean you technically just have to have two nested client React components in an Astro component, where the nested Component has children as well and you should experience the same hydration error.

**Comment by matthewp** [comment]
I don't think framer is required to show this bug. I think this is happening here too: https://stackblitz.com/edit/github-jr2n4y?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by lokkeestudios** [comment]
@matthewp yes you are right. It does not have anything to do with framer-motion. Just wanted to stress that the Component is hydrated on the client-side.

**Comment by matthewp** [comment]
So this is one is really tough given the way we currently do slotting. An astro-slot is injected so that we can find the inner HTML to rehydrate in the client. However a server-rendered framework component has its astro-slots stripped. When this happens it's also stripping the slots of a child island, which is causing this bug.

I'm thinking we can avoid adding the `astro-slot` for server rendered components, and then we won't need to remove them after. @natemoo-re worked on this part of the code so I'm going to wait until he gets back (he's on vacation this week) to talk to him about it.

**Comment by lokkeestudios** [comment]
All right, thanks for working on a fix, it's a pretty nasty bug if you don't know about it. Oh, and don't worry, I know how busy and stressful life as a programmer can sometimes be. Probably not the highest priority at the moment either ^^.
Just hit me up in case you need anything further from my side!

**Comment by matthewp** [comment]
PR is up!
