### ISSUE TITLE
Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Use 'verbatimModuleSyntax' instead.

### ISSUE THREAD

**Issue by artursopelnik** [withastro/astro#6599]
### What version of `astro` are you using?

16.12.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

any

### What operating system are you using?

any

### What browser are you using?

any

### Describe the Bug

Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Use 'verbatimModuleSyntax' instead.

See here:
https://github.com/withastro/astro/blob/main/packages/astro/tsconfigs/strict.json

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/blob/main/packages/astro/tsconfigs/strict.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
We can't change this until a majority of our users are on TypeScript 5.0, since we don't control the TypeScript version used. Even VS Code does not have TypeScript 5.0 at the moment.

We'll add `ignoreDeprecations: "5.0"` to our templates in the meantime

**Comment by Princesseuh** [comment]
I'm thinking of waiting a bit more, because changing it to `verbatimModuleSyntax` is breaking unfortunately. For what it's worth, you can still use the option yourself, we just can't include it in our templates.

**Comment by Princesseuh** [comment]
Optimally, we should unfortunately be waiting on either Astro's 3.0 or TS's 5.5 to make sure we don't break people, which might be months away still 😔 Nonetheless, we'll consider it after 5.1, hopefully most people wouldn't be too affected by then.

It's a bit of a frustrating situation, just having `verbatimModuleSyntax` in your `tsconfig.json` prevent compilation when using 4.9 TS or lower. I wish it would've been possible to just add it and for TS to ignore `importsNotUsedAsValues` when `verbatimModuleSyntax` is present, alas.
