### ISSUE TITLE
`paginate` create broken `page.url.prev` link for second page (added trailing slash)

### ISSUE THREAD

**Issue by le0pard** [withastro/astro#6603]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

Github Pages

### What package manager are you using?

yarn

### What operating system are you using?

Mac, Linux

### What browser are you using?

Any

### Describe the Bug

`paginate` create broken `page.url.prev` link for second page (added trailing slash)

How to reproduce:

add in astro config:

```
build: {
    format: 'file',
  },
```

Next create `[...page].astro` in `posts` subfolder and add pagination links:

```
{page.url.prev ? <a href={page.url.prev}>Previous</a> : null}
{page.url.next ? <a href={page.url.next}>Next</a> : null}
```

On page `/posts/2` link "Previous" will contain in `href=/posts/` (with trailing slash), all other links works as expected `/posts/number` (no trailing slash). This will work in dev mode, but after build you website will contain broken link (because static hosting often don't have mode `trailingSlash: 'ignore'`)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gfz7vj-kbpqqf?file=src/pages/posts/[...page].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by le0pard** [comment]
@ematipico why it is [p2-nice-to-have](https://github.com/withastro/astro/labels/p2-nice-to-have) ? It is clearly break navigation for builded website and developer need to write wrapper function to fix invalid links from `paginate` functionality

**Comment by ematipico** [comment]
> @ematipico why it is [p2-nice-to-have](https://github.com/withastro/astro/issues?q=is%3Aopen+label%3Ap2-nice-to-have+sort%3Aupdated-desc) ? It is clearly break navigation for builded website and developer need to write wrapper function to fix invalid links from `paginate` functionality

I launched the stackblitz link in dev and preview modes, but the links still work. They have an incorrect trailing slash, but the link is still reachable. Did I misunderstand the issue? Or did I miss something during the build step? I haven't managed to reproduce a 404 page.

**Comment by le0pard** [comment]
@ematipico link will work, because dev server ignore trailing slashes by default ( https://docs.astro.build/en/reference/configuration-reference/#trailingslash - default is 'ignore'). 

But if you will build site - you will have broken link. Or you can set `trailingSlash: 'never'` and get broke link in dev mode too

**Comment by le0pard** [comment]
@ematipico here also video

https://user-images.githubusercontent.com/98444/226715051-c39a081c-d40b-4ab6-a614-896be4b977ee.mov

**Comment by ematipico** [comment]
> @ematipico link will work, because dev server ignore trailing slashes by default ( [docs.astro.build/en/reference/configuration-reference/#trailingslash](https://docs.astro.build/en/reference/configuration-reference/#trailingslash) - default is 'ignore').
> 
> But if you will build site - you will have broken link. Or you can set `trailingSlash: 'never'` and get broke link in dev mode too

The stackblitz link didn't have `trailingSlash` set up to `never`. Pasting here a link that will break https://stackblitz.com/edit/github-gfz7vj-prehcg?file=astro.config.mjs

**Comment by le0pard** [comment]
> The stackblitz link didn't have `trailingSlash` set up to `never`

@ematipico it is fine for dev, but in the end you find out about issue on hosting providers after deploy :)

Thanks for changed label
