### ISSUE TITLE
Incorrect image format returned (via experimental astro:assets)

### ISSUE THREAD

**Issue by tpiros** [withastro/astro#6610]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

As per the [docs](https://docs.astro.build/en/guides/assets/):

> You can optionally state the image file type to be used. The default file format used is webp.

However, given this code:

```
---
import spain from '~/assets/spain.jpeg';
import { Image } from 'astro:assets';
---
<Image src={spain} width={600} alt="Some Text" />
```

I always end up receiving `jpg` not `webp` so I'm slightly confused.

As a side note it doesn't matter if I have squoosh explicitly specified in `astro.config.mjs` or not.

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This was fixed in https://github.com/withastro/astro/pull/6555. Just hasn't been released yet, we'll do a release shortly. Sorry for the inconvenience!

Fwiw, the file format is correct, it's just the file extension that's wrong

**Comment by tpiros** [comment]
Thanks for the update. I checked the headers and the images also come back as `image/jpeg` - not sure if that's driven by the extension or not by the browser though.
