### ISSUE TITLE
Add option to disable `loading=lazy` attribute on the `Image` component

### ISSUE THREAD

**Issue by tpiros** [withastro/astro#6611]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Today the `<Image>` component renders and `<img>` element that has the `loading=lazy` attribute added to it. The problem is that if an image is used to calculate the site's LCP score (which, in most occurrences would be the case), lazy loading is going to increase the LCP value. (lazy loading an LCP image is bad practice).

There should be a prop added to the `<Image>` component that controls if an image should be lazy loaded or not.

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hi, you can use `loading="eager"` on the component. As said here: https://docs.astro.build/en/guides/assets/#additional-properties, the component accepts all the same props as `img`

**Comment by tpiros** [comment]
I see. I'd make this more obvious somewhere in the docs because if someone doesn't know CWV and LCP and how `loading=lazy` may actually run into problems.

**Comment by m-emelchenkov** [comment]
How to specify loading="eager" for automatically parsed Markdown images?

**Comment by Princesseuh** [comment]
Unfortunately in Markdown there's currently no way to do so outside of creating your own image service.

**Comment by rowe-morehouse** [comment]
> I see. I'd make this more obvious somewhere in the docs because if someone doesn't know CWV and LCP and how `loading=lazy` works and what it does (in conjunction with LCP) may actually run into problems.

In the `assets` docs you could also show this in the interface pattern / signature:

`interface ImageMetadata {
  src: string;
  width: number;
  height: number;
  format: string;
  decoding: sync | async | auto
  loading: eager | lazy

}`

And let us know that loading defaults to lazy, decoding to async.

:)

**Comment by xexiu** [comment]
@m-emelchenkov 

In my case, I'm using [Astro Remote](https://github.com/natemoo-re/astro-remote) to parse markdown (.md) files.

As @tpiros said, the lighthouse is complaining about LCP from Markdown and other images.
I made a nasty hack to remove the `loading` attr from the images in the port view cause using `loading: eager` was making all images use it, so I prefer most of the images to have `loading: lazy`.

You can check the function here:

[IsInPortView](https://github.com/xexiu/web_astro_blog/blob/67f402f769c19142ad462c6fd3060e2ca32c4ced/src/js/utils.ts#L86)

And how to use it in the markdown component with [Astro Remote](https://github.com/natemoo-re/astro-remote):

[Markdown Renderer](https://github.com/xexiu/web_astro_blog/blob/67f402f769c19142ad462c6fd3060e2ca32c4ced/src/pages/blog/%5Bslug%5D.astro#L81)

Treated MarkdownImages:

[MarkdownImage Img](https://github.com/xexiu/web_astro_blog/blob/master/src/components/markdown/MarkdownImages.astro)

This will solve the LCP complaints.

**Comment by protyposis** [comment]
> Unfortunately in Markdown there's currently no way to do so outside of creating your own image service.

@Princesseuh Does that no longer apply to Astro 4? I created and configured my own image service (extending `sharpService`), but for Markdown images, only `parseURL` and `transform` get called. Others like `getURL` and `validateOptions` (which I'd like to use to set defaults) aren't called. Is there any other way to customize processing of Markdown images?

For the use case of the OP (modifying options of explicitly used `<Image/>` tags) I can confirm that this approach works nicely.

**Comment by Princesseuh** [comment]
> > Unfortunately in Markdown there's currently no way to do so outside of creating your own image service.
> 
> @Princesseuh Does that no longer apply to Astro 4? I created and configured my own image service (extending `sharpService`), but for Markdown images, only `parseURL` and `transform` get called. Others like `getURL` and `validateOptions` (which I'd like to use to set defaults) aren't called. Is there any other way to customize processing of Markdown images?
> 
> For the use case of the OP (modifying options of explicitly used `<Image/>` tags) I can confirm that this approach works nicely.

Markdown images calls `getImage`, which calls all of the hooks.

**Comment by protyposis** [comment]
Thanks, I got confused by some hooks only being called once when the Markdown is transformed to HTML, while others are called on every request (using the dev server). Works as expected :)

Here's a full example of a custom image service to set defaults:

```ts
import type { LocalImageService } from "astro";
import sharpService from "astro/assets/services/sharp";

const service: LocalImageService = {
  async validateOptions(validateOptions, imageConfig) {
    if (!sharpService.validateOptions) {
      throw new Error("Image service validation hook is unexpectedly missing");
    }

    // Set defaults here as suggested in docs:
    // https://docs.astro.build/en/reference/image-service-reference/#validateoptions

    return sharpService.validateOptions(validateOptions, imageConfig);
  },
  getSrcSet: sharpService.getSrcSet,
  getURL: sharpService.getURL,
  parseURL: sharpService.parseURL,
  transform: sharpService.transform,
  getHTMLAttributes: sharpService.getHTMLAttributes,
};

export default service;

```
