### ISSUE TITLE
Internal server error: Failed to resolve import "lib/getClient" from...

### ISSUE THREAD

**Issue by e-jigsaw** [withastro/astro#6613]
### What version of `astro` are you using?

2.1.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I'm using astro with TypeScript. I set `compilerOptions.baseUrl` and `import some from 'lib/thing'`. 2.1.3 works fine, but 2.1.4 broken below error

```
Internal server error: Failed to resolve import "lib/getClient" from...
```

thanks

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u39yd1?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
This regression was probably introduced in #6566

**Comment by e-jigsaw** [comment]
I was suspicious of that Pull Request after looking at the changelog

**Comment by e-jigsaw** [comment]
nice work folks! I confirmed 2.1.5 works fine.

**Comment by filiptammergard** [comment]
@MoustaphaDev @e-jigsaw I'm still experiencing the same issue in 2.1.5, as can be seen here: https://github.com/filiptammergard/recept/pull/161

Is that expected?

**Comment by bluwy** [comment]
@filiptammergard we've reverted the change that caused the urgent bug in the first place. Can you try 2.1.6?

**Comment by filiptammergard** [comment]
> @filiptammergard we've reverted the change that caused the urgent bug in the first place. Can you try 2.1.6?

Yep that works. Thanks!
