### ISSUE TITLE
Image can't load in client 

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#6615]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

The get image component does not work with client components. Vite does not allow the use of node promises file system. 

**This error is the one that wil be seen in the browser dev tools** 

`Uncaught (in promise) Error: Module "node:url" has been externalized for browser compatibility. Cannot access "node:url.fileURLToPath" in client code.  See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
    at Object.get (__vite-browser-external:node:url:3:11)
    at metadata.js?v=4630eb1d:2:131
`

**This link should show you what's going on**
https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-9rvycr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello, it is intended at this time that client side components are not supported. We'll document this better, sorry for the inconvenience!

**Comment by matthewp** [comment]
Closing, the docs team is working on documenting this (might already have finished doing so).

**Comment by louiss0** [comment]
> Closing, the docs team is working on documenting this (might already have finished doing so).

Is there an alternative you'd recommend in the meantime.
