### ISSUE TITLE
Unknown compiler option 'ignoreDeprecations'

### ISSUE THREAD

**Issue by mameaw14** [withastro/astro#6616]
### What version of `astro` are you using?

2.1.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Firefox, Chrome

### Describe the Bug

When I run my jest test on astro 2.1.4
```
  ● Test suite failed to run

    node_modules/astro/tsconfigs/base.json:28:5 - error TS5023: Unknown compiler option 'ignoreDeprecations'.

    28     "ignoreDeprecations": "5.0"
           ~~~~~~~~~~~~~~~~~~~~
```
will found this error

in the package `node_modules/astro/tsconfigs/base.json` have this line
```
    // TypeScript 5.0 changed how `isolatedModules` and `importsNotUsedAsValues` works, deprecating the later
    // Until the majority of users are on TypeScript 5.0, we'll have to supress those deprecation errors
    "ignoreDeprecations": "5.0"
```

I think I suppose to use typescript v5 in order to make it works. I know it's build in by astro. So, I check my typescript version and it's 4.9.4.
```
npm list typescript
├─┬ astro@2.1.4
│ └── typescript@4.9.4
└─┬ ts-jest@29.0.5
  └── typescript@4.9.4 deduped
```

Not sure astro should update typescript to be 5? or I need to do something with my jest setup. Beside jest test, the application can build and run normally. Sorry if it's not a bug. 

This is my code https://github.com/mameaw14/mameaw14.github.io

### Link to Minimal Reproducible Example

https://github.com/mameaw14/mameaw14.github.io/actions/runs/4481801471/jobs/7879010494#step:6:16

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello, please update to TypeScript 4.9.5, which added `ignoreDeprecations`.

**Comment by LefanTan** [comment]
I'm still encountering this error when running `tsc --noEmit`. 

```
 npm list typescript
├─┬ @typescript-eslint/eslint-plugin@5.58.0
│ └─┬ tsutils@3.21.0
│   └── typescript@5.0.4 deduped
├─┬ astro@2.2.2
│ └── typescript@5.0.4 deduped
└── typescript@5.0.4
```

```
node_modules/astro/tsconfigs/base.json:28:5 - error TS5023: Unknown compiler option 'ignoreDeprecations'.

28     "ignoreDeprecations": "5.0"
```

**Comment by timmywil** [comment]
For anyone coming here later like me, if you see this error in VS code, also change the typescript version used to the workspace version. The one that comes with VS code is older than 4.9.5.
