### ISSUE TITLE
Problem generating a sitemap

### ISSUE THREAD

**Issue by ljrodriguez1** [withastro/astro#6618]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Linux, WSL2

### What browser are you using?

Chrome

### Describe the Bug

The bug i Am experiencing is with this minimal astro config

```js
export default defineConfig({
  site: "https://example.com",
  base: "/blog",
  output: "static",
  adapter: vercel(),
  integrations: [
    sitemap(),
  ],
  trailingSlash: "never",
});
```

This produce 2 sitemap files, the first one is sitemap-index.xml

```xml
<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>https://example.com/sitemap-0.xml</loc></sitemap></sitemapindex>
```

Here we should have `https://example.com/blog/sitemap-0.xml`

then in the second file: sitemap-0.xml i have this:
```xml
<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"><url><loc>https://sundes.com/blogpost/1</loc></url></urlset>
```

where i should have a url like `https://sundes.com/blog/post/1`

I think this is a bug in the plugin, i will try to fix this, but i am not sure if i could create a working PR for this

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-47cfzy?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dev-cyprium** [comment]
I have the same issue. Also, I don't see an option for generating a sitemap is the `output` is `server` like in my case:
```ts
export default defineConfig({
  output: "server",
  adapter: vercel(),
  site: "https://defacto.co.rs",
  integrations: [
    tailwind(),
    image({
      serviceEntryPoint: "@astrojs/image/sharp",
    }),
    mdx(),
    sitemap(),
    storyblok({
      accessToken: env.STORYBLOK_TOKEN,
      components: {
        news: "storyblok/News",
      },
    }),
  ],
});
```

anything that can be done in this case?

**Comment by 43081j** [comment]
if i run the repro locally it seems to work fine.

we get a `sitemap-index.xml` which has one entry: `[...]/blog/sitemap-0.xml`

that then has several `/blog/blog/[...]` entries (`/blog/` twice in each one but that seems different to your problem)

maybe its just me though? could you try the repro again?

**Comment by andremralves** [comment]
> if i run the repro locally it seems to work fine.

I think it's because the 'trailingSlash: "never"' option is missing in the repro.

I tested locally and this error seems to occur when both ``base: "/something"`` and ``trailingSlash: "never"`` options are set. So the sitemap plugin generates a URL without the trailing slash for the base path.

I think I can solve this issue. If nobody is currently working to solve it, I would like to work on this issue.

**Comment by 43081j** [comment]
@andremralves go for it, doesn't sound like anyone's on it

im gonna guess its some buggy concatenation in the sitemap integration, probably a good place to start. joining paths without a trailing slash to separate them
