### ISSUE TITLE
can't run astro build when use vite-pwa tailwind and set ts import alias

### ISSUE THREAD

**Issue by deemsang** [withastro/astro#6620]
### What version of `astro` are you using?

2.1.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

got this error when run astro build
```
[vite-plugin-pwa:build] Could not load /home/projects/github-nyhn6u/src/astrojs/tailwind/base.css (imported by astro:scripts/page-ssr.js): ENOENT: no such file or directory, open '/home/projects/github-nyhn6u/src/astrojs/tailwind/base.css'
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nyhn6u?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
Let me dig into this bug.

**Comment by deemsang** [comment]
change prefix path in tsconfig to anything else except `@` to fix the issue. but maybe its still a bug

**Comment by wulinsheng123** [comment]
> change prefix path in tsconfig to anything else except `@` to fix the issue. but maybe its still a bug

Why do you need to code such as ` "@*": ["src/*"]`?
Why not `"@": ["src/*"]`?

**Comment by deemsang** [comment]
`"@": ["src/*"]` cant import like this `import Layout from "@layouts/Layout.astro";`

**Comment by wulinsheng123** [comment]
> `"@": ["src/*"]` cant import like this `import Layout from "@layouts/Layout.astro";`

Do you have any success with the example in another builder tool?

**Comment by wulinsheng123** [comment]
> Looks like this is a regression for a usecase I didn't expect. We need to pass a custom resolver to `vite.resolve.alias` to optional resolve the path if it fails.

Let me try it out?

**Comment by bluwy** [comment]
Fixed in https://github.com/withastro/astro/pull/6633
