### ISSUE TITLE
Imports from `src` root broken with 2.1.4 update

### ISSUE THREAD

**Issue by Brian-McBride** [withastro/astro#6621]
### What version of `astro` are you using?

2.1.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Updating astro  ^2.1.3  →  ^2.1.4

After update:

```shell
  🚀  astro  v2.1.4 started in 73ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
01:30:39 PM [content] Watching src/content/ for changes
The following dependencies are imported but could not be resolved:

  src/settings (imported by /Users/me/projects/documentation/src/utils/menu-tree.ts)

Are they installed?
01:30:39 PM [content] Types generated
01:30:39 PM [astro] update /.astro/types.d.ts
```

After updating, the pathing seems to be amiss with imports as per the new release.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9xfzri?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Brian-McBride** [comment]
If I were to make a guess, it would be something involved in this "fix"

https://github.com/withastro/astro/commit/ea9b3dd72b98b3f5a542ca24a275f673faa6c7c5

**Comment by e-jigsaw** [comment]
https://github.com/withastro/astro/issues/6613

**Comment by bluwy** [comment]
Yeah this is the same as #6613. Let's converge on a single issue to track it.
