### ISSUE TITLE
import.meta.env.BASE_URL is including a trailing slash

### ISSUE THREAD

**Issue by sugarmaplemedia** [withastro/astro#6623]
### What version of `astro` are you using?

2.1.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Firefox

### Describe the Bug

When I call `import.meta.env.BASE_URL` in my `src` files, it includes a trailing slash that renders incorrectly as `http://localhost/foo//bar`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wccs8f?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sugarmaplemedia** [comment]
Update: setting `trailingSlash` in the config from the default `ignore` to `never` fixed the issue. Either way, its still a bug.

**Comment by bluwy** [comment]
Makes sense to me. Looks like the behaviour was from https://github.com/withastro/astro/pull/5358, even though before it we had always prepend a slash. But I agree that if the default is `ignore`, it should probably leave the `base` as is.

There's a good chance someone might be relying on the old behaviour though so "fixing" this could be a breaking change.

**Comment by natemoo-re** [comment]
Closing this since https://github.com/withastro/astro/pull/7878 has been merged to `next`. This will be fixed in Astro 3.0!
