### ISSUE TITLE
Imported CSS file name applies numeric page file name

### ISSUE THREAD

**Issue by kimulaco** [withastro/astro#6624]
### What version of `astro` are you using?

2.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When there is a page whose file name is only numeric, the file name of imported CSS becomes the numeric value.
For example, if `src/pages/404.astro` exists, the imported CSS will be named `404.hash.css".

Not just `src/pages/404.astro`.
Lower numbers take precedence if `src/pages/200.astro` exist.

'dist/index.html' is loading '404.9a459717.css' in the following example so I feel strange.
https://stackblitz.com/edit/github-wfqtjs?file=dist/index.html

Sorry if there is already the same issue.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wfqtjs?file=dist/index.html

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kimulaco** [comment]
@bluwy Thanks for confirming.
I hope it will improve in the future!

**Comment by HiImJulien** [comment]
To expand on this:

The property `vite.build.rollupOptions.output.assetFileNames` also accepts a function with the signature `(info: PreRenderedAsset) => string`.

In order to rename a specific output, you could create function, which returns the preferred name for this specific asset. Note, that in my case, Astro decided to pickup the name `datenschutz.css` as the chunk name. With the following function I can rename it to `style.[hash].css`.

```js
function chunkNamer(info) {
    if(info.name === "datenschutz.css") {
        return "assets/style.[hash].css";
    }

    return "assets/[name].[hash][extname]";
}
```

**Comment by Plinpod** [comment]
@bluwy 
> Yes this is intentional as a bundled CSS chunk name is based on the pages that use it, so if a list of pages uses a CSS chunk, then the first page name is used, in this case "404" as it's sorted alphanumerically. Unfortunately this can't be changed for now without fiddling with with `vite.rollupOptions.assetFileNames` (not sure if that works reliably), but this name should be harmless when used in production.
> 
> I'll close this for now as it's not a bug, but maybe we could revisit changing how we name CSS chunks in the future.

This isn't entirely harmless when dealing with Google, GoogleBot occasionally ignores filenames with "404" in them. This can be an issue when the bot attempts to render your pages internally.

**Comment by bluwy** [comment]
Does GoogleBot need the CSS to crawl the content? If it needs it, it shouldn't ignore any sort of CSS file names, so I'm not sure that's a reason we should sway away from this naming pattern now.

**Comment by HiImJulien** [comment]
> Does GoogleBot need the CSS to crawl the content? If it needs it, it shouldn't ignore any sort of CSS file names, so I'm not sure that's a reason we should sway away from this naming pattern now.

Google evolved from purely crawling static HTML. At this point, they're completely rendering websites and executing JS (although you MUST NOT rely on this happening!) for their metrics. 

One metrics, that is important for your Google rank is, among others, mobile usability. If your website is not responsive and unusable on mobile (i.e. text too small, etc.) then you'll be punished.
