### ISSUE TITLE
@astrojs/markdoc: `render: null` on document node removes child nodes too

### ISSUE THREAD

**Issue by paulrudy** [withastro/astro#6628]
### What version of `astro` are you using?

2.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

As I mentioned [on Discord](https://discord.com/channels/830184174198718474/830184175176122389/1088170954959618169), Markdoc devs [suggest](https://github.com/markdoc/markdoc/discussions/347#discussioncomment-5393103) the following to remove the `<article>`...`</article>` tags that Markdoc wraps content with by default:

```js
import Markdoc from '@markdoc/markdoc';

const config = {
  nodes: {
    document: {...Markdoc.nodes.document, render: null}
  }
};

const doc = Markdoc.parse(example);
const output = Markdoc.transform(doc, config);
```

In a [Next.js example using Markdoc](https://stackblitz.com/edit/github-vcq4hg-aargkf?file=markdoc/config.js), the suggested code prevents rendering of the wrapping `<article>`...`</article>` tags, but the child nodes are still rendered.

In Astro, I adapted the suggested code in `astro.config.mjs` like this:

```js
import markdoc from '@astrojs/markdoc';
import Markdoc from '@markdoc/markdoc';

export default defineConfig({
  integrations: [
    markdoc({
      nodes: {
        document: { ...Markdoc.nodes.document, render: null },
      },
    }),
  ],
});
```

Result is that the wrapping `<article>`...`</article>` tags are not rendered, but none of the child nodes are rendered either. See the link for minimal reproduction on Stackblitz.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tfbhvr?file=markdoc.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by paulrudy** [comment]
updated minimal reproducible example to account for changes in @astrojs/markdoc v 1.0

**Comment by bholmesdev** [comment]
@paulrudy Appreciate that! I'll be taking a look tomorrow 👍

**Comment by paulrudy** [comment]
> @paulrudy Appreciate that! I'll be taking a look tomorrow 👍 

Cool, no rush, I know there are higher priority issues. I tried to discover the source myself, but typescript and Astro deep workings are beyond me 😀
