### ISSUE TITLE
Astro Check Errors - Only when using React

### ISSUE THREAD

**Issue by GrantBirki** [withastro/astro#6631]
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows, Linux, and MacOS - All the same error

### What browser are you using?

Chrome and Brave

### Describe the Bug

When running `astro check`, I am seeing errors displayed in my terminal ever since adding React components into my project. I added React functionality by closely following the official Astro docs.

What is really strange, is that these errors are also shown in `build` command with Astro but the build still successfully completes and my sites are all deployed. In fact, I didn't even know these errors were happening until I checked my GitHub Actions build logs and saw them in there. All the sites I am deploying and using Astro have these "error" messages (that are using React) but they are deployed fine and have no visible issues.

Here are the errors I'm seeing and how to recreate them

1. Clone this [template repository](https://github.com/grantbirki/astrowind)
2. Install npm packages

    ```bash
    npm install
    ```

3. Run a build and view the error:

```console
$ npm run build

> <name>@0.0.0 build
> astro build

X [ERROR] The build was canceled

10:19:30 PM [content] Types generated 1.89s
10:19:30 PM [build] output target: static  
10:19:30 PM [build] Collecting build info...
10:19:30 PM [build] Completed in 2.21s.     
10:19:30 PM [build] Building static entrypoints...
10:19:33 PM [build] Completed in 2.47s.

 building client 
Completed in 1.89s.       

...
 generating static routes 
▶ src/pages/index.astro
...
10:19:48 PM [build] 19 page(s) built in 19.51s
10:19:48 PM [build] Complete!
```

As you can see in the logs above, the build completes successfully, but there is an odd line in the output -> `X [ERROR] The build was canceled`.

Running `astro check` shows some additional info

```console
$ npm run astro check
> <project-name-here>@0.0.0 astro
> astro "check"

10:22:33 PM [check] Checking files
X [ERROR] The build was canceled

10:22:35 PM [content] Types generated 1.80s
X [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]

    node_modules/esbuild/lib/main.js:728:12:
      728 │       throw new Error(`Invalid command: ` + request.command);
          ╵             ^

    at handleRequest (<project-path-here>\node_modules\esbuild\lib\main.js:728:13)       
    at handleIncomingPacket (<project-path-here>\node_modules\esbuild\lib\main.js:745:7) 
    at Socket.readFromStdout (<project-path-here>\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

  The plugin "JavaScript plugins" was triggered by this import

    node_modules/@mui/material/ButtonBase/Ripple.js:3:17:
      3 │ import clsx from 'clsx';
        ╵                  ~~~~~~

⠋  Getting diagnostics for Astro files in <project-path-here>\…X [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]

    node_modules/esbuild/lib/main.js:728:12:
      728 │       throw new Error(`Invalid command: ` + request.command);
          ╵             ^

    at handleRequest (<project-path-here>\node_modules\esbuild\lib\main.js:728:13)
    at handleIncomingPacket (<project-path-here>\node_modules\esbuild\lib\main.js:745:7)
    at Socket.readFromStdout (<project-path-here>\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

  The plugin "JavaScript plugins" was triggered by this import

    node_modules/@mui/material/ButtonBase/Ripple.js:8:28:
      8 │ import { jsx as _jsx } from "react/jsx-runtime";
        ╵                             ~~~~~~~~~~~~~~~~~~~

✔  Getting diagnostics for Astro files in <project-path-here>\…
10:22:40 PM [diagnostics] Result (48 files): 
- 0 errors
- 0 warnings
- 0 hints
```

---

## Additional Details

The [pull request that added React components](https://github.com/GrantBirki/astrowind/pull/4/files) to my repository when things broke

Actions [logs](https://github.com/GrantBirki/astrowind/actions/runs/4451518854/jobs/7818269689#step:8:9) showing the error. This is where I traced things back to the Actions workflow when things first started acting _weird_

### Link to Minimal Reproducible Example

https://github.com/grantbirki/astrowind

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Can you provide a minimal reproduction? The provided example is a full app it seems.

**Comment by GrantBirki** [comment]
Yeah something definitely seems up with React in Astro projects. cc @matthewp

**Comment by GrantBirki** [comment]
@matthewp or @ematipico - If it helps at all, I would be happy to hop in a Discord/zoom/call to troubleshoot and show you what I'm experiencing. I would then be happy to write up our findings in this issue so they are documented publicly and others can follow along with our results.

**Comment by kodumbeats** [comment]
@ematipico Thanks for reviewing! I found a more relevant ticket ([6306](https://github.com/withastro/astro/issues/6306)) that I missed on my first pass through open issues 🙈 so I'll move my report there.

**Comment by GrantBirki** [comment]
> the error log `X [ERROR] The build was canceled` is harmless; it comes from `vite`. It was fixed upstream and I was confirmed that it wouldn't break anything in your code;

@ematipico Do you have any reference to this or links?

It would be nice if there was a way to suppress this error if it is indeed "harmless" because I don't like the color "red" in my production pipeline unless there is something actually going wrong 😄

**Comment by ematipico** [comment]
> > the error log `X [ERROR] The build was canceled` is harmless; it comes from `vite`. It was fixed upstream and I was confirmed that it wouldn't break anything in your code;
> 
> @ematipico Do you have any reference to this or links?
> 
> It would be nice if there was a way to suppress this error if it is indeed "harmless" because I don't like the color "red" in my production pipeline unless there is something actually going wrong 😄 

@bluwy would you mind chiming in?

**Comment by bluwy** [comment]
@GrantBirki it was fixed in https://github.com/vitejs/vite/pull/12358 and should be gone when you upgrade Astro's internal Vite dep to v4.2. You can run `npm update vite` in your project to bump it.

**Comment by GrantBirki** [comment]
@bluwy Thank you for the suggestion! I checked out the PR you linked and it looks like that is _exactly_ what I need to suppress the error.

It looks like `vite` is set to [`^4.1.2`](https://github.com/search?q=repo%3Awithastro%2Fastro+language%3AJSON+%22vite%22%3A+%22%5E4.1.2%22&type=code&l=JSON) all throughout the Astro repo. Once this gets updated, I would imagine that these wonky errors will disappear for all users on the latest version of Astro

**Comment by bluwy** [comment]
Yep! Usually we bump the internal Vite version when we rely on a certain features on that version. I _think_ npm/pnpm would pull the latest version of Vite by default, as long as it respects the semver range.

**Comment by GrantBirki** [comment]
`npm` is not pulling the new version down so I'm guessing it has to be bumped in Astro as that is where the dependency is coming from 🤷

**Comment by onyoo** [comment]
This issue doesn't happen on `npm run astro check` but has similar output. Maybe it's related? https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/519

**Comment by GrantBirki** [comment]
FWIW this error doesn't appear for me any more on the latest version of `astro` so at least for me this is resolved.
