### ISSUE TITLE
Response cookies can't be set when page is .astro

### ISSUE THREAD

**Issue by sausir1** [withastro/astro#6632]
### What version of `astro` are you using?

2.1.4

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Linux, Ubuntu 20.04

### What browser are you using?

Firefox, Chrome

### Describe the Bug

I think the title says it all. But to be more clear - I have a `Layout.astro` component in my `/layouts` directory, where a cookie is set based on given props/params (eg. `Astro.cookies.set('layout', 'test')`. Everything works fine when requesting a page that is not another `.astro` file - Cookie is being sent back and can be seen in response.  But, if I navigate to `index.astro` (does not matter if it set's any cookies or not), the response does not include the cookie that is being  set in `Layout.astro` file anymore. Don't really know if it has to work like this, but the behavior is quite unexpected I think.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7j549u?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You can only set cookies inside of page components due to streaming. By the time the Layout runs the stream has already started, headers are sent. We should probably give you an error when you attempt to set them lower in the page.

**Comment by sausir1** [comment]
Well, if I would get an error when setting cookies in a layout component, how do I set them from `.vue`, `.md` and other page files? Maybe a warning is better indication, rather then just stopping execution?

**Comment by matthewp** [comment]
You can't set cookies from framework components.

**Comment by Skn0tt** [comment]
I spent a couple hours debugging why my cookies set in a component didn't work, until I've stumbled across this issue. It worked fine in local dev, so I was expecting it to work fine in prod as well! I'm assuming there's some underlying race condition here.

Would it be possible to add some kind of runtime detection to this? A console warning would've been enough for me to catch this a lot earlier. If you can give me some pointers as to how to implement it, i'm happy to open a PR :D
