### ISSUE TITLE
image asset: ENOENT error for remote markdown files with relative paths

### ISSUE THREAD

**Issue by mashehu** [withastro/astro#6635]
### What version of `astro` are you using?

2.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

MacOS

### What browser are you using?

Chrome

### Describe the Bug

With the new image assets, relative links to images in a remote markdown are not resolved well and generate a ENOENT error which stops the server. See example below

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mnzpmy-qdvhnk?file=astro/package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
It's unfortunately unlikely that we can support this. Importing files from outside the Astro project is not a supported use case we have at the moment, and is unfortunately unlikely to happen to be due to technical restrictions regarding where files can live.
