### ISSUE TITLE
[astro:build] Transform failed  ERROR: Unexpected "default"

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [withastro/astro#6636]
### What version of `astro` are you using?

2.1.5

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

LINUX

### What browser are you using?

VIVALDI

### Describe the Bug

`
 building client 
[astro:build] Transform failed with 1 error:
astro-entry:@components/home/List_Cards_v2.astro:25:26: ERROR: Unexpected "default"
file: astro-entry:@components/home/List_Cards_v2.astro:25:26

Unexpected "default"
23 |  Astro.self = $$ListCardsV2;
24 |  
25 |  return $$render`export ${ default } from "@components/home/List_Cards_v2.astro"`;
   |                            ^
26 |  }, 'astro-entry:@components/home/List_Cards_v2.astro');
27 |  export default $$ListCardsV2;

 error   Unexpected "default"
  File:
    astro-entry:@components/home/List_Cards_v2.astro:25:26
❌ [build] Failed with exit status 1`

### Link to Minimal Reproducible Example

https://pastebin.com/kJEjG1Rq

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jojojojojoj5564656465465** [comment]
my tsconfig.json

`{
	"extends": "astro/tsconfigs/strict",
	"compilerOptions": {
		"strictNullChecks": true,
		"allowJs": true,
		"allowImportingTsExtensions": true,
		"baseUrl": "./src",
		"paths": {
			"@components/*": ["components/*"],
			"@assets/*": ["assets/*"],
			"@style/*": ["Style/*"],
			"@content/*": ["content/*"],
			"@img/*": ["/public/assets/*"]
		}
	}
}`

**Comment by jojojojojoj5564656465465** [comment]
import "@unocss/reset/tailwind.css";
import { astroImageTools } from "astro-imagetools";
import { defineConfig } from "astro/config";
import UnoCSS from "unocss/astro";

import sitemap from "@astrojs/sitemap";
import critters from "astro-critters";
import robotsTxt from "astro-robots-txt";

// https://astro.build/config
import compress from "astro-compress";

// https://astro.build/config

// https://astro.build/config
import mdx from "@astrojs/mdx";

// https://astro.build/config
export default defineConfig({
  vite: {
    resolve: {
      alias: {
        "@": "/src"
      }
    },
    build: {
      rollupOptions: {
        output: {
          exclude: ["@style/dev.css", "/src/Style/dev.css"]
        }
      }
    }
  },
  server: {
    host: "0.0.0.0"
  },
  site: "https://massage-kobido-lifting.com/",
  integrations: [astroImageTools, UnoCSS(), critters(), sitemap(), compress(), robotsTxt(), mdx()]
});

**Comment by matthewp** [comment]
Can you provide a full reproduction with a stackblitz? I created one with your pastebin and didn't get an error, but I suspect there is more involved: https://stackblitz.com/edit/github-avntfs?file=src%2Fpages%2Findex.astro&on=stackblitz

Please open a new issue if you can create a repro.

**Comment by spokospace** [comment]
Hello, did you resolve this issue? I try to build a page with astro, dev is okay, buy prod is always with 'Unexpected "default"' error :(

**Comment by jojojojojoj5564656465465** [comment]
Yes it's solve. it was because i used the astro client:visible  instead of <component client:visible/> use plain <component> this way
