### ISSUE TITLE
Passing a var to a script tag disables the bundling

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#6642]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

mac

### What browser are you using?

chromium

### Describe the Bug

# Problem

We can't use variables defined in the frontmatter part of an Astro element in a script tag, because using `define:vars` will shut down the bundling behavior (as per the docs)

<img width="697" alt="image" src="https://user-images.githubusercontent.com/411625/227468963-4a4f12b5-4d8c-4598-880f-2de8fd412289.png">

# Usecase

I found few examples on how to bind some script (from a script tag) to a button, but all of them always refer to hardcoded selectors which tend not to scale well.

I'd like to have, instead, the capacity to generate random ids and use them after in a querySelector call in order to target my html elements.

# Steps to reproduce

1. Create an astro component with a `<button />`

2. Add a script tag to add some behavior to the button such as:
    ```html
    <script>
    import confetti from 'canvas-confetti'
    document
      .querySelectorAll('button')
      .forEach(btn => btn.onclick = confetti)
    </script>
    ```

**→ WORKS**

3. Generate a uuid in the frontmatter part of the component such as:
    ```mdx
    ---
    const uuid = Math.random().toString(16).slice(2, 10)
    ---
    ```

4. Inject that uuid as a data attribute in the button such as:
    ```html
    <button data-id={uuid} />
    ```

5. Modify the script in 2. to leverage the uuid as a selector
    ```html
    <script define:vars={{ uuid }}>
    import confetti from 'canvas-confetti'
    document
      .querySelectorAll(`[data-id="${uuid}"]`)
      .forEach(btn => btn.onclick = confetti)
    </script>
    ```

**→ BREAKS**

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-txerhu?file=src/pages/index.astro,src/components/Button.astro&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Hi. Currently this is not possible because for a script to be bundled, it needs to take over the whole script to be bundled and chunked right. The alternative you mentioned is the way of dealing with this. If you believe this is possible with a trick internally, we're happy to re-investigate this again as an RFC at https://github.com/withastro/roadmap. Closing for now.

**Comment by Fryuni** [comment]
A suggestion for this is to have the logic in a module script (without the vars) and a separate script that calls the function.

```astro
<script>
  declare global {
    interface Window {
      doSomethingWithValue(value: string): void;
    }
  }

  window.doSomethingWithValue = value => {
    // Do the thing
  }
</script>
<script define:vars={{value: valueFromFrontmatter}}>
  document.addEventListener('DOMContentLoaded', () => {
    doSomethingWithValue(value);
  });
</script>
```

Bundled scripts are executed just once per page, regardless of how many times the component is included in the page.

Non-bundled scripts are executed once per instantiation of the component.

This could be automated internally by Astro when only define:vars is used, wrap the entire thing in a function, which can be bundled and add a call for every time the component is instantiated passing the correct vars. Probably not in the global window object, but on some variable for that using the hash of the script.

If there is some discussion about this on the roadmap that I didn't find I can share this idea there as well. This is how I solved for my use case.

**Comment by y-nk** [comment]
> Bundled scripts are executed just once per page, regardless of how many times the component is included in the page.
> 
> Non-bundled scripts are executed once per instantiation of the component.

this is very useful knowledge i didn't remember. thanks for pointing this out.
