### ISSUE TITLE
assets: Vercel serverless function throws ECONNRESET Error: socket hang up

### ISSUE THREAD

**Issue by vinhphm** [withastro/astro#6648]
### What version of `astro` are you using?

2.1.6

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

nom

### What operating system are you using?

Mac

### What browser are you using?

Safari, Chrome

### Describe the Bug

Everything was normal when I ran `npm run dev`. The deployment build to Vercel also succeeded. But when I try to access the site, the serverless function crashed and threw this error on the logs:
```
Invoke Error 	{"errorType":"Error","errorMessage":"socket hang up","code":"ECONNRESET","stack":["Error: socket hang up","    at connResetException (node:internal/errors:718:14)","    at Socket.socketOnEnd (node:_http_client:520:23)","    at Socket.emit (node:events:525:35)","    at endReadableNT (node:internal/streams/readable:1359:12)","    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"]}
```
This has happened since version 2.1.3

### Link to Minimal Reproducible Example

None. I think it's related to Vercel adapter.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
We're going to need more information to help here. Preferably a reproduction as well.

**Comment by vinhphm** [comment]
> We're going to need more information to help here. Preferably a reproduction as well.

@matthewp Here is a reproduction:
Source: https://github.com/vinhphm/vinh-dev-paper
Web: https://vinh-dev-paper.vercel.app

**Comment by kymppi** [comment]
Why was this closed? Still happening to me with adapter version `3.2.1` and Astro `2.1.8`

**Comment by matthewp** [comment]
@kymppi The lack of a minimal reproduction.

**Comment by matthewp** [comment]
@kymppi Yes for sure, or you can just open a new issue since that might be easier.

**Comment by kymppi** [comment]
Seems like after downgrading `@astrojs/vercel` from `3.2.1` to `3.2.0` it started to work :thinking:

**Comment by matthewp** [comment]
There's actually this related issue: https://github.com/withastro/astro/issues/6685
