### ISSUE TITLE
Add TTL support for Netlify adapter for On Demand Builders

### ISSUE THREAD

**Issue by cassidoo** [withastro/astro#6654]
### What version of `astro` are you using?

2.1.5

### Are you using an SSR adapter? If so, which one?

Netlify

### Describe the Feature

The Netlify On Demand Builders adapter should support Time To Live (TTL):

https://docs.netlify.com/configure-builds/on-demand-builders/#time-to-live-ttl

Relevant PR: #5874 

### Participation

- [X] I am willing to submit a pull request for this issue (but I won't be hurt if someone beats me to it)

**Comment by natemoo-re** [comment]
Uh oh... rogue bot!

**Comment by natemoo-re** [comment]
Apologies for the notifications @cassidoo! Trying the label action again...
