### ISSUE TITLE
Astro Build Failing trying to .map a passed property

### ISSUE THREAD

**Issue by CyberPunkMetalHead** [withastro/astro#6655]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

This is a build error that happens when attempting to call .map() on a passed property of type list in a child component. The issue is not present when running in dev mode.

**A bit of context -**
The index file imports some data from a .ts file that looks like this
```
export const accordions: SingleAccordion[] = [
  {
    title: "title here",
    description:
      "description here",
  },
  {
    title: "another title",
    description: "another description"
  }]
```

And then passes this data to a component:

`<Accordion accordions={accordions} />`

Inside the Accordion component, I defined and mapped this property to render any number of accordions:

```
---
import type { SingleAccordion } from "../../types/Accordion";

interface Props {
  accordions: SingleAccordion[];
}

const { accordions } = Astro.props;
---

{
  accordions.map((accordion) => (
    <>
      <div class="tailwind-stuff">
        {accordion.title}
      </div>
      <div class="tailwind-stuff">
        <p>{accordion.description}</p>
      </div>
    </>
  ))
}
```

**The build error I'm getting is the following:**
`TypeError: Cannot read properties of undefined (reading 'map')
`
I have troubleshoot and logged the value of the accordions to the console. The local dev environment renders everything as expected, this error only happens when trying to run `npm run build`

In some of the build chunks, it appears that the property is never passed the value, though I'm not sure.
```
const accordions = [
  {
    title: "stuff",
    description: "other stuff"
  },
  {
    title: "more stuff",
    description: "other stuff."
  }];

const _page1 = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
  __proto__: null,
  accordions
}, Symbol.toStringTag, { value: 'Module' }));

const $$Astro$a = createAstro();
const $$Accordion = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$a, $$props, $$slots);
  Astro2.self = $$Accordion;
  const { accordions } = Astro2.props;
  return renderTemplate`${accordions.map((accordion) => renderTemplate`${renderComponent($$result, "Fragment", Fragment, { "class": "astro-PFMOAHWC" }, { "default": ($$result2) => renderTemplate`${maybeRenderHead($$result2)}<div class="just-tailwind astro-PFMOAHWC">
        ${accordion.title}
      </div><div class="more-tailwind astro-PFMOAHWC">
        <p class="astro-PFMOAHWC">${accordion.description}</p>
      </div>` })}`)}`;
}, "path/to/src/pages/IndexComponents/Accordion.astro");
```

The only way I managed to get it to work is if I drop the actual data inside the child component I'm planning to use .map in. But this is not ideal and creates other problems when trying to build components with list elements and props.
Any help would be appreciated, thanks!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yoimhe?file=src/pages/index.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by matthewmercuri** [comment]
I don't have a great explanation, but I think I can offer a fix. If you assume the `accordions` prop is potentially undefined, it seems to build. So you would make the prop optional and then simply add conditional chaining in `Accordion.astro`

```typescript
{
  accordions?.map((x) => (
    <>
      <div class="accordion">
        {x.title}
      </div>
      <div class="panel">
        <p>{x.description}</p>
      </div>
    </>
  ))
}
```

I suspect this has to do with how values are passed between components at build time. Perhaps a core member or someone much smarter than me can offer an explanation.

**Comment by CyberPunkMetalHead** [comment]
Thank you @matthewmercuri! That does seem to work and the build output looks fine.

**Comment by CyberPunkMetalHead** [comment]
That's just for the minimum reproductible example. 
I do  store most of my components in src/components. 

However, I also user deeper nesting for components specific to a certain layout so that it's all neatly organised.
