### ISSUE TITLE
host: true with Node adapter

### ISSUE THREAD

**Issue by millette** [withastro/astro#6661]
### What version of `astro` are you using?

2.1.7

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

firefox

### Describe the Bug

Using the following configuration:

```json
{
  server: {
    host: true // "0.0.0.0",
  },
  integrations: [tailwind()],
  output: 'server',
  adapter: node({
    mode: 'standalone',
  }),
}
```

Instead of listening on all addresses, it says "http://undefined:3000" with "astro preview".

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/thirsty-ride-r3726r?on=codesandbox&file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A15%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A15%7D%5D

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
@millette https://github.com/withastro/roadmap/discussions/493
help to push it if you feel free.
This discussion is the same as well as this bug.

**Comment by natemoo-re** [comment]
Cleaned up the PR @JerryWu1234 started in https://github.com/withastro/astro/pull/6928! We'll try to get this merged.
