### ISSUE TITLE
Error with exit code 137 ("Killed") while optimizing images

### ISSUE THREAD

**Issue by nolanlawson** [withastro/astro#6664]
### What version of `astro` are you using?

2.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

N/A

### Describe the Bug

**TL;DR**: if you're hitting a 137 "Killed" error while optimizing images, try [installing `sharp`](https://docs.astro.build/en/guides/integrations-guide/image/#installing-sharp-optional).

While running `npm run build` on Ubuntu 22.04 (64-bit, Intel chip), I kept running into the cryptic message "Killed" immediately after optimizing images:

```
optimizing 229 images in batches of 8
[build] Waiting for the @astrojs/image integration...
Killed     
```

Doing `echo $?` showed that it was killed with a 137 error code, which means it was killed by the OS, [typically due to an OOM (Out-Of-Memory) error](https://www.containiq.com/post/exit-code-137) (although I can't say for sure that that was the issue).

In any case, after some trial-and-error, including trying the ["experimental" assets](https://docs.astro.build/en/guides/assets/) (which didn't help), as well as manually reducing the number of batches from the core count to 1 (which also didn't help), I realized that [setting up `sharp`](https://docs.astro.build/en/guides/integrations-guide/image/#installing-sharp-optional) fixed the issue.

I'm mostly opening this issue so that anyone googling the same error will land on this page. I don't expect Astro devs to do anything, unless you want to update the documentation or something. "137 Killed" is pretty cryptic, but I'm not sure you can actually catch the error and provide a more friendly error message.

### Link to Minimal Reproducible Example

N/A, my project is closed-source, but basically I have a ton of very large JPEG images if that helps.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by simplast** [comment]
how to solved it?

**Comment by nolanlawson** [comment]
> I realized that [setting up sharp](https://docs.astro.build/en/guides/integrations-guide/image/#installing-sharp-optional) fixed the issue.

**Comment by nolanlawson** [comment]
Well, I upgraded to Astro 3.1.2 and have upgraded to the new `astro:assets` system, and this issue has come back. Switching from sharp (default) to squoosh didn't resolve it. I might have to debug to see where all the memory usage is coming from.

In case it helps, I'm on desktop Ubuntu 22.04. My whole system actually visually freezes while running `astro build`, and then the process is killed with a 137 error.
