### ISSUE TITLE
Dev/Build error on Arm-64 Macbook

### ISSUE THREAD

**Issue by tilemoon** [withastro/astro#6668]
### What version of `astro` are you using?

2.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

<img width="870" alt="image" src="https://user-images.githubusercontent.com/37775224/227850092-30d38d50-3e7a-4144-bb2d-9a184a97e2dd.png">
when i run `pnpm run dev` command, i get error on the image

### Link to Minimal Reproducible Example

None(it works fine on remove server)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This isn't a bug in Astro. Have you tried the suggestions in the error message?

**Comment by tilemoon** [comment]
> This isn't a bug in Astro. Have you tried the suggestions in the error message?

yeah, i installed `esbuild/darwin-arm64` package and then worked fine.but this is a new package just created from `pnpm create astro@latest`, i didn't change any code.

**Comment by bluwy** [comment]
Maybe you can try `npm install esbuild` in an empty project and see what esbuild brings in? There could be a bug with esbuild detecting your system to install the right binaries. [esbuild detects it here](https://github.com/evanw/esbuild/blob/b2b897870564a6b8e8bc802a140c55bf602de31b/lib/npm/node-platform.ts#L28-L46).

But this also seems like Rosetta 2 intefering like the error message mentioned. Just a guess, did you let the Astro CLI install the dependencies? Maybe you can try installing manually to see if it works instead.

**Comment by tilemoon** [comment]
> Maybe you can try `npm install esbuild` in an empty project and see what esbuild brings in? There could be a bug with esbuild detecting your system to install the right binaries. [esbuild detects it here](https://github.com/evanw/esbuild/blob/b2b897870564a6b8e8bc802a140c55bf602de31b/lib/npm/node-platform.ts#L28-L46).
> 
> But this also seems like Rosetta 2 intefering like the error message mentioned. Just a guess, did you let the Astro CLI install the dependencies? Maybe you can try installing manually to see if it works instead.

i tried `npm install esbuild` in an empty folder. 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/37775224/227903008-4273e6b8-3d5e-4458-957a-e8af137be3e5.png">
As shown, it installed correct esbuild version.

but when i use `pnpm install esbuild`
<img width="583" alt="image" src="https://user-images.githubusercontent.com/37775224/227904025-b7a5c894-954c-4c06-b570-12dae128b745.png">
it didn't install esbuild/darwin-arm64.

**Comment by bluwy** [comment]
For pnpm you have to check `node_modules/.pnpm` to see all installed packages.

**Comment by tilemoon** [comment]
> For pnpm you have to check `node_modules/.pnpm` to see all installed packages.

yeah,i will check that.Thanks for response.
