### ISSUE TITLE
Override chunkFileNames and astro build generate strange extra JS files

### ISSUE THREAD

**Issue by krossmusic** [withastro/astro#6674]
### What version of `astro` are you using?

2.0.17

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

NA

### Describe the Bug

Aplogy, I'm struggle to get CodeSpace which I can't find a way to add astro config which is missing and my vision isn't doing well, will need going for eye checkup tomorrow.

Have not add anything to this build, but you can find a completed astro config at the button of this issue.
https://krossmusic-cuddly-space-bassoon-9p6qqggrr45fppwv.github.dev/

Without chunkFileNames set in astro config.
The build generated `NotificationBanner.astro_astro_type_script_index_0_lang.b9638bfa.js`.
```
NotificationBanner.astro_astro_type_script_index_0_lang.b9638bfa.js
scripts
├── a.55d6129b.js
└── a.ed83f321.js
```

With chunkFileNames set in astro config.
Chunk produces additional chunk files which I have only 1 NotificationBanner component, should produce 1 chunk JS file.
```
scripts
├── a.e4eaedc7.js
├── a.f635012b.js
├── chunk.163a9289.js
├── chunk.29c34b4b.js
├── chunk.4da842d7.js
├── chunk.829a2d7a.js
├── chunk.b9638bfa.js
├── chunk.bb120c77.js
└── chunk.c6b89100.js
``

Completed astro config.
```
import { defineConfig } from 'astro/config';
import path from "path";
import tailwind from '@astrojs/tailwind';

// https://astro.build/config
import image from "@astrojs/image";

// https://astro.build/config
import node from "@astrojs/node";

// https://astro.build/config
export default defineConfig({
  build: {
    assets: "resc"
  },
  vite: {
    build: {
      assets: 'resc',
      cssCodeSplit: false,
      assetsInlineLimit: 0,
      rollupOptions: {
        output: {
          entryFileNames: 'resc/script/a.[hash].js',
          chunkFileNames: 'resc/script/chunk.[hash].js',
          assetFileNames: ({ name }) => {
            const { ext, dir, base } = path.parse(name);
            if (ext == ".css") return path.join(dir, "resc/css", 'a.[hash].css');
            return "resc/img/[name].[ext]";
          }
        }
      }
    }
  },
});
```


### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by thedtvn** [comment]
> @matthewp Can Astro or Rollup shorten `NotificationBanner.astro_astro_type_script_index_0_lang.b9638bfa.js` to `NotificationBanner.b9638bfa.js` or `randomname.b9638bfa.js`?

same

**Comment by matthewp** [comment]
Possibly, is anyone willing to look into why the names are long and possibly fix it?

**Comment by thedtvn** [comment]
> Possibly, is anyone willing to look into why the names are long and possibly fix it?

@matthewp  can set `vite.rollupOptions.chunkFileNames` can use to rename those file but it will break server file  :\
![image](https://github.com/withastro/astro/assets/80153297/09f0c2f3-baa0-4521-a104-4b586878f6c8)
![image](https://github.com/withastro/astro/assets/80153297/142b932b-5e65-417b-a49a-180c539de22f)
![image](https://github.com/withastro/astro/assets/80153297/16a336e5-c36c-48ed-a48b-d8b69e65a3dc)

**Comment by thedtvn** [comment]
> Possibly, is anyone willing to look into why the names are long and possibly fix it?

@matthewp it make when you put script on components then import it and can I ask that what file process components script ( for easyer to track whe it come from ) ?
