### ISSUE TITLE
Astro.slot.render() with arguments does not work with Fragment

### ISSUE THREAD

**Issue by BryceRussell** [withastro/astro#6683]
### What version of `astro` are you using?

2.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Firefox

### Describe the Bug

When `Astro.slots.render()` is called with arguments it does not handle `<Fragment>`s correctly and throws an error.

```jsx
// Slot.astro
<Fragment set:html={Astro.slots.render('name', ['arg'])}>
```
**Does NOT Work:**
```jsx
<Slot>
  <Fragment slot="name">
    {arg => <span>{arg}</span>}
  </Fragment>
</Slot>
```
**Works**:
```jsx
<Slot>
  <frag slot="name">
    {arg => <span>{arg}</span>}
  </frag>
</Slot>
```
This is the line that throws the error: https://github.com/withastro/astro/blob/main/packages/astro/src/core/render/result.ts#L106

It looks like the `<Fragment>` is being rendered into HTML before it can be rendered with the arguments from `Astro.slots.render()`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ucqonn?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks!

**Comment by wulinsheng123** [comment]
I will be looking this bug.

**Comment by JerryWu1234** [comment]
this bug should be closed

**Comment by BryceRussell** [comment]
@JerryWu1234 The bug has only been partially fixed, PR #6832 fixed this case:

```jsx
<Fragment slot="name">
    Text
</Fragment>
```

But, it did not fix this case:

```jsx
<Fragment slot="name">
  {arg => <span>{arg}</span>}
</Fragment>
```

**Comment by JerryWu1234** [comment]
```js
${renderComponent($$result, "Slot", $$Slot, {}, { "name": ($$result2) => renderTemplate`${renderComponent($$result2, "Fragment", Fragment, { "slot": "name" }, { "default": ($$result3) => renderTemplate`${(arg) => renderTemplate`<p>${arg}</p>`}` })}` })}
```
Because of the nested element, there is a workaround that uses the original tags (‘div’, ‘span’).

such as 

```js
<div slot="name">
  {arg => <span>{arg}</span>}
</div>
```

**Comment by JerryWu1234** [comment]
I think that it requires a lot of work if we want to fix this bug. Perhaps my idea is not a good one. So please share your idea if you have any idea to fix this bug.

this bug is derived from this line https://github.com/withastro/astro/blob/7ae6e892921fd47c630b289a28d8100414f861e2/packages/astro/src/runtime/server/render/any.ts#L28

**Comment by natemoo-re** [comment]
Thanks for looking into this one @JerryWu1234! I agree that this would be awesome to fix but it will take quite a bit of work.

One possible idea is to adjust our compiler output so that we generate an optimized statement for cases like this. That's probably the cleanest approach I can think of, since we'd need to deal with scope tracking across async boundaries otherwise.

**Comment by natemoo-re** [comment]
For my own future reference, investigating this was Linear ticket `PLT-556`. Considering the "investigation" part done, but hoping we can circle back with a proper fix soon.

**Comment by lilnasy** [comment]
@BryceRussell What is the use case for `<Fragment slot="name">` vs `<frag slot="name">`?

**Comment by BryceRussell** [comment]
@lilnasy For me, `<Fragment>` feels more intuitive and semantically correct vs `<frag>` feeling more like a hack. I think most people trying to pass a function to a named slot would try to use `<Fragment>` first and when that doesn't work they would have to do some trial and error to discover that `<frag>` also works.

**Comment by lilnasy** [comment]
Yeah, that's fair. To clarify, the tag name "frag" is not special, any plain HTML tag works and they are documented with named slots. We don't document `Fragment` with it.

**Comment by BryceRussell** [comment]
Ya I was just using `frag` to standardize my examples, but the fact that it can be any HTML tag is what feels unintuitive/hacky to me. When using an HTML tag to pass a function it is implied that the tag will be included in the markup of the slot like it is when passing HTML, but it is not and it instead acts more like a `<Fragment>`. If you were able to use a `<Fragment>` to pass a function it would be more implicit that your passing the function itself and not the tag too.

**Comment by lilnasy** [comment]
> But, this case has not been fixed:
> ```tsx
> <Fragment slot="name">
>   {arg => <span>{arg}</span>}
> </Fragment>
> ```

In this case, the function is the default slot of the `Fragment` component. If astro's rendering was architected differently, it would be simple for the `Fragment` to "passthrough" the function to whatever the `Fragment` itself is slotted into, but it currently isn't.

Related: https://github.com/withastro/astro/issues/7610#issuecomment-1962072650

Closing as a `wontfix`.

**Comment by BryceRussell** [comment]
@lilnasy 

This used to work in previous versions of Astro, is there a reason this is not supported anymore? I built a library of components that uses this principal of passing template functions to named slot to customize the rendering of a component https://github.com/BryceRussell/astro-headless-ui/wiki#named-slot-functions would this be considered a regression?

**Comment by lilnasy** [comment]
I'm still looking through to see if `<Fragment slot="name">` behavior changed in recent versions, but the pseudo-rendering you mention does still work - instead of the `Fragment` component, the function could be placed within any plain html element that has a `slot` attribute.

**Comment by lilnasy** [comment]
I'm re-opening until we know whether/when the behavior changed.

**Comment by BryceRussell** [comment]
@lilnasy I was doing some testing on this and I figured out that it was breaking on my end because I was using tags with dashes `-`:
- <tag slot="named">{() => ...}: tag is NOT included in the markup, arguments ARE passed to slot function
- <tag-with-dashes slot="named">{() => ...}: tag IS included in the markup, arguments are NOT passed to slot function

I think it is safe to close this issue
