### ISSUE TITLE
assets: Vercel's serverless function throws ECONNRESET Error: socket hang up

### ISSUE THREAD

**Issue by vinhphm** [withastro/astro#6685]
### What version of `astro` are you using?

2.1.7

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac, Windows, Linux

### What browser are you using?

Chrome, Safari

### Describe the Bug

Everything was normal when I ran npm run dev. The deployment build to Vercel also succeeded. But when I try to access the site, the serverless function crashed and threw this error on the logs:
```
Invoke Error 	{"errorType":"Error","errorMessage":"socket hang up","code":"ECONNRESET","stack":["Error: socket hang up","    at connResetException (node:internal/errors:718:14)","    at Socket.socketOnEnd (node:_http_client:520:23)","    at Socket.emit (node:events:525:35)","    at endReadableNT (node:internal/streams/readable:1359:12)","    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"]}
```
This has happened since version 2.1.3. I have submitted this one before but that was closed as completed because lack of reproduction. So I submitted this again with reproduction this time.

### Link to Minimal Reproducible Example

https://github.com/vinhphm/vinh-dev-paper

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your example is not public.

**Comment by vinhphm** [comment]
> @vinhphm your logs are not public. Can you paste the relevant section here?

@matthewp I have disabled the logs and source protection on Vercel, so you should have no problem check it when you visit [https://vinh-dev-paper.vercel.app](https://vinh-dev-paper.vercel.app)

<img width="931" alt="Screenshot 2023-03-28 at 10 16 47 PM" src="https://user-images.githubusercontent.com/75784849/228286080-6013a374-c1f6-4b3d-8472-c58a0db26ccb.png">

But in case you still can't see it, the error is still the same as above
```
2023-03-28T15:19:37.846Z	9e45fc3e-eda2-4b72-a7ef-5f62fc8b6be4	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"socket hang up","code":"ECONNRESET","stack":["Error: socket hang up","    at connResetException (node:internal/errors:718:14)","    at Socket.socketOnEnd (node:_http_client:520:23)","    at Socket.emit (node:events:525:35)","    at endReadableNT (node:internal/streams/readable:1359:12)","    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"]}
```

**Comment by matthewp** [comment]
Thanks for providing that but it's still not enough info. An `ECONNRESET` can happen for a number of reasons that aren't necessarily bugs in the Vercel adapter (or Astro). If you can provide a reproduction via `astro.new` that when deployed to Vercel gives this error, that gives us something to work off of.

**Comment by vinhphm** [comment]
@matthewp Thank you for your suggestion, here is another one from astro.new with the same error
Source: https://github.com/vinhphm/astro-assets
Site: astro-assets.vercel.app
I hope you would response to this because I would hate to create another issue.

**Comment by matthewp** [comment]
Thanks.

**Comment by tonyski** [comment]
The same error happens to me, usually after an hour after deploy.

**Comment by matthewp** [comment]
@tonyski are you using the image integration with squoosh?

**Comment by tonyski** [comment]
> @tonyski are you using the image integration with squoosh?

No, I integrated mongodb, I solved this problem by setting the connection pool options, I guess the problem should be caused by vercel serverless function execution timeout.

**Comment by Princesseuh** [comment]
I am not able to reproduce this specific error, nonetheless this made me discover a bug when using Squoosh on Vercel. With Sharp however, everything work and even while hammering the website with requests for some time, the function didn't crash

**Comment by Princesseuh** [comment]
Investigated this a bit more and still don't really understand why this happens. However, upgrading to latest of Astro and Vercel on your reproduction fixes the issue. Weird, but at least it seems to work!

**Comment by kymppi** [comment]
Hey! I have had this error for some time by now. Just upgraded to latest astro and still not working :(
