### ISSUE TITLE
Integration entrypoint 'astro:server:setup' is executed during 'astro build' 

### ISSUE THREAD

**Issue by edoardofelici** [withastro/astro#6687]
### What version of `astro` are you using?

2.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

'astro:server:setup' now gets executed not only during 'dev' mode - as mentioned in the [docs](https://docs.astro.build/en/reference/integrations-reference/#astroserversetup) - but also during 'build' mode. If it's now intended, the docs should be updated. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-nspsjy?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
When is this executed during the build? It shouldn't be. @bholmesdev is this related to CC maybe?

**Comment by bholmesdev** [comment]
@matthewp Hm, I'm not sure how but I could take a look. Depends when the regression was introduced?

**Comment by edoardofelici** [comment]
I'm updating the stackblitz issue example for easier testing, as some plugins don't work in astro < 2. 

I tried setting astro to version 1.9 and the 'astro:server:setup' is not called during build. Let me see if I can narrow down the version a bit more.

**Comment by edoardofelici** [comment]
@matthewp @bholmesdev  Found the regression version. 

astro@2.0.6 -> all good
astro@2.0.7 -> bugged.
