### ISSUE TITLE
Two different exports for "./dist/jsx/*" path in package.json of the astro package

### ISSUE THREAD

**Issue by dhirajgagrai** [withastro/astro#6708]
### What version of `astro` are you using?

2.1.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

There are two different exports for the same module path "./dist/jsx/*" in the package.json of the astro package inside node_modules.

<img width="684" alt="Screenshot 2023-03-30 at 9 59 08 AM" src="https://user-images.githubusercontent.com/22605432/228733550-0a0ac0be-f81c-4d82-8af9-89141ba4c63d.png">

When importing using the first path, the following error is thrown: Cannot find module 'astro/jsx/renderer' or its corresponding type declarations.
The second path works fine.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xawqgm?file=src/index.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dhirajgagrai** [comment]
After changing the moduleResolution in tsconfig to "nodenext", both the imports work. Should I leave this issue open as there are two exports for the same path?

**Comment by natemoo-re** [comment]
This has been merged into `next` and will go out in `astro@3.0.0`, so I'm going to close this issue!
