### ISSUE TITLE
Astro loads two copies of SolidJS

### ISSUE THREAD

**Issue by lxsmnsyc** [withastro/astro#6709]
### What version of `astro` are you using?

2.1.8

### Are you using an SSR adapter? If so, which one?

None (if @astrojs/node doesn't count)

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

![image](https://user-images.githubusercontent.com/4783372/228759116-9c35efe9-c3b1-4d00-867d-95559cda1b84.png)

As you see in the image, Astro loads two copies of SolidJS, one through the `file:///` URL (see `createResource`), the other with the  POSIX path (see `createMemo`).

Based on what I know with Vite's module resolution, since this is close to the browser behavior, two copies are loaded because they come from different URLs, despite pointing to the same file locally. This behavior breaks SolidJS packages that uses SolidJS APIs that relies on the existence of a root (e.g. `createUniqueId`, `createResource`). The code basically thinks that the APIs are called "outside a root".

I do think this same issue might be prevalent to other integrations that rely on the same mechanism (e.g. React), but I don't have any evidence for that yet. 

Another potential issue is how `@astrojs/solid-js` has [SolidJS as both a peer dependency and a dependency](https://github.com/withastro/astro/blob/main/packages/integrations/solid/package.json#L41-L45), I do think it should be both a peer and a dev dependency?

### Link to Minimal Reproducible Example

https://github.com/lxsmnsyc/astro-solid-spa-nested

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This fixes it:

```js
    ssr: {
      noExternal: ['solid-swr-store']
    }
```

Since this is an ecosystem package I'll add this to the Solid integration.
