### ISSUE TITLE
without PUBLIC_ prefix environment variables not working with react + @astrojs/vercel/edge

### ISSUE THREAD

**Issue by liuw5367** [withastro/astro#6713]
### What version of `astro` are you using?

2.1.8

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Without `PUBLIC_` prefix，`react + @astrojs/vercel/edge` cannot get environment variables in edge functions。
Local running is normal, the problem only occurs when deploying on Vercel.
Deploying `solidjs + @astrojs/vercel/edge` 、 `react + @astrojs/vercel/serverless` on Vercel is also normal.

### Link to Minimal Reproducible Example

https://github.com/liuw5367/astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by liuw5367** [comment]
[astro.vercel.app](https://astro-kappa-weld.vercel.app/)

This is the result of the sample code running on Vercel. If you check the console on the browser side, you will find that only the values that are public are returned.

**Comment by larryhudson** [comment]
I've just run into the same issue. Created a repo here to recreate the issue, if that's useful:
https://github.com/larryhudson/astro-vercel-edge-env-testing

**Comment by matthewp** [comment]
Thanks for narrowing it down! I'm going to take a look.
