### ISSUE TITLE
Fresh Astro project fails with `ERR_REQUIRE_ESM`

### ISSUE THREAD

**Issue by DjebbZ** [withastro/astro#6715]
### What version of `astro` are you using?

2.1.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

The CLI

### Describe the Bug

Starting a fresh install of Astro, I can't get it to run at all. I get this error after `npm start`:

```shell
Error [ERR_REQUIRE_ESM]: require() of ES Module /path/to/project/node_modules/emmet/dist/emmet.cjs.js from /path/to/project/node_modules/@vscode/emmet-helper/lib/cjs/emmetHelper.js not supported.
emmet.cjs.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename emmet.cjs.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /path/to/project/node_modules/emmet/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/path/to/project/node_modules/@vscode/emmet-helper/lib/cjs/emmetHelper.js:43:30)
    at Object.<anonymous> (/path/to/project/node_modules/@astrojs/language-server/dist/plugins/css/CSSPlugin.js:4:24)
    at Object.<anonymous> (/path/to/project/node_modules/@astrojs/language-server/dist/plugins/index.js:18:14)
    at Object.<anonymous> (/path/to/project/node_modules/@astrojs/language-server/dist/check.js:6:19)
    at Object.<anonymous> (/path/to/project/node_modules/@astrojs/language-server/dist/index.js:4:15) {
  code: 'ERR_REQUIRE_ESM'
}
```

Steps to reproduce:

```shell
npm create astro@latest
# answer questions : Include sample file, install dependencies.
# cd into directory 
npm start
```

I also tried deleting the `package-lock.json` and `node_modules` then reinstalling + running it with pnpm and yarn, same thing. I also tried various node.js versions with nvm: 16.20.0, 18.15.0, 19.8.1. Same result.

package.json:

```json
{
  "name": "blog",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "astro": "^2.1.8"
  }
}
```

I followed the suggestion in the error message and manually changed `/path/to/project/node_modules/emmet/package.json`'s `type` field from `module` to `commonjs` => Problem solved.

So the problem seems to come from the `emmet` package. Here's the dependency tree from `astro` to `emmet`:

```shell
$ npm ls emmet
└─┬ astro@2.1.8
  └─┬ @astrojs/language-server@0.28.3
    └─┬ @vscode/emmet-helper@2.8.6
      └── emmet@2.4.0
```

What's strange is that in CodeSandbox the same template with the same `package.json` works just fine.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/github/withastro/astro/tree/latest/examples/basics?on=codesandbox&file=%2Fpackage.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by 7flash** [comment]
Same! Tried create astro with npm, pnpm, yarn

**Comment by Princesseuh** [comment]
This is fixed already, running `npm upgrade` should fix the issue!

**Comment by DjebbZ** [comment]
Wow, so fast! Thanks a lot 🫡
