### ISSUE TITLE
VSCODE: VSCode/LSP support for highlighting Astro embedded in Markdown

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#672]
### Motivation

I want the VSCode extension + language server to support parsing in embedded language blocks, like in markdown files:

```md

# Hello World

```astro
  ---
  const props = Astro.props;
 \```
 ```

<img width="556" alt="image" src="https://user-images.githubusercontent.com/10626596/125388279-dbdf2080-e364-11eb-8068-d0cd533d4ce0.png">

### Possible solutions
I'm not sure what features or integrations this actually requires.
### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by natemoo-re** [comment]
There's no way for extension to extend the built-in Markdown highlighting, so this would need to be an upstream contribution to https://github.com/microsoft/vscode-markdown-tm-grammar and then https://github.com/microsoft/vscode/tree/main/extensions/markdown-basics.

**Comment by jasikpark** [comment]
@matthewp how can I move this to the new repo? I don't see it in "Transfer Issue"

**Comment by natemoo-re** [comment]
I believe this has been fixed!
