### ISSUE TITLE
Types being defined in Astro component are not recognised in the <script> tag of the component itself

### ISSUE THREAD

**Issue by marceloverdijk** [withastro/astro#6727]
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Types being defined in the Astro component are not recognised in the <script> tag of the component itself.
That way I cannot use type safety nor code completion.

E.g.

```
---
type Repo = {
	name: string
	stars: number
	forks: number
	description: string
}

...
---

<html>
  ...
</html>

<script>
  window.nameFormatter = (_value: any, row: Repo) => {
    return `${row.name}`
  }
</script>
```

See a full minimal example here: https://stackblitz.com/edit/github-e3ehug?file=src/pages/index.astro

Alternative is to define this type in a separate file and import in the <script> tag.
But for me this type is really scoped to the page, no use anywhere else so I would like to define that type in the Astro component file itself if possible.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-e3ehug?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is intended, scripts operate in a totally separate context. You'll need to either define the type inside the script tag, or in another file that you import in the script tag.

**Comment by marceloverdijk** [comment]
What is the rationale @Princesseuh 
Would it be an idea to explicitly export it so it can be used in the script tag?
As it is a really page scoped type , it feels cumbersome to move the type to a separate file.

**Comment by marceloverdijk** [comment]
Although the example is simplified , I use Prisma.io to query data in various Astro components . These query results are different across components as components ise different data. E.g 1 components only needs Books with isbn and title, but other components also include the Author, or even a break up in chapters. So there is not 1 Book type in this case which works very well with Prisma. So in fact I will have multiple Book types.
Would you create a dedicated ts file per Astro component or page? Is it eg. possible to include an index.ts in the same dir as src/pages/books/index.astro and then also [isbn].ts to accompany [isbn].astro or how would you do this?

**Comment by Princesseuh** [comment]
It's mostly a technical thing, since they operate in separate runtimes, they cannot share the same TypeScript context. You can think of every script tag as a separate, module, file.
