### ISSUE TITLE
Error using Astro and Partytown plugin: 404 Not Found for partytown-sandbox-sw.js and partytown-sw.js

### ISSUE THREAD

**Issue by alexsedeke** [withastro/astro#6729]
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

MacOS

### What browser are you using?

Chrome, Safari, Firefox

### Describe the Bug

I am encountering an error when using the Astro framework version 2.1.9 and the Partytown plugin. The error message is:

```bash
09:41:25 PM [serve]    404 /~partytown/debug/partytown-sandbox-sw.js
09:41:26 PM [serve]    404        /~partytown/debug/partytown-sw.js
```
I have tested this issue with Partytown versions 1.1.1 and 1.2.0. However, when using Astro version 2.1.7, both versions of Partytown work without any issues.

I am unsure whether this is a problem with Astro or the Partytown plugin.

### Link to Minimal Reproducible Example

https://github.com/alexsedeke/astropartytown.git

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fahminlb33** [comment]
I'm also experiencing the same issue today after updating from astro 2.1.8 to 2.1.9

**Comment by alexsedeke** [comment]
> I'm also experiencing the same issue today after updating from astro 2.1.8 to 2.1.9.
> 
> EDIT:
> 
> This issue only happens when using `astro dev`. When using the build version of the website, the service worker is correctly installed.

This happens to me even in build version using `npm preview`.

**Comment by Princesseuh** [comment]
cc @bholmesdev Could this be related to your changes in 2.1.9 related to `astro:server:setup`? I notice that the Partytown integration uses this hook to serve its files.

**Comment by bholmesdev** [comment]
@Princesseuh Hm, that's a good point. We _should_ always apply `astro:server:setup` but I can look into it 👍

**Comment by shishkin** [comment]
This is not only specific to the partytown plugin, but is a general issue of dev server middlewares not working. I see the same issue in https://github.com/shishkin/astro-pagefind/issues/8. The [basic server middleware example from the docs](https://docs.astro.build/en/reference/integrations-reference/#server-option) doesn't work anymore.

**Comment by A13k2** [comment]
fuck fuck fuck

had the same problem, if someone else runs into this problem: Check if "Bypass for network" is disabled in dev tools under Application -> Service Worker. It should not be enabled...

Hope I save someone a long time of googling 🙃

**Comment by jjdbrrr** [comment]
@A13k2 this comment deserves more praise, with the checkbox set all requests to the service worker are skipped, which also renders the debugging not fire. Took me a while to figure out. Thanks!

**Comment by suhaylmv** [comment]
Getting a similar (I think) 404 error with partytown, but from the Google Search Console

**Comment by Yutsuro** [comment]
"Bypass for network" is disabled, but the problem is still going.
