### ISSUE TITLE
failed resizing assets (experimental)

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [withastro/astro#6730]
### What version of `astro` are you using?

lastest

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Firefox

### Describe the Bug

I'm moving images for applying & using assets(experimental) features
but i failed to resizing my images in md/mdx file.

# structure
src/assets/*.png
contents/body/*.md(mdx)

# .astro
```
<div class="prose">
  <Content/>
</div>
```
# .md
```
import { Image } from 'astro:assets'
...
<Image src="../../assets/astro.png" width={100} height={45} alt="astro" class="my-class" /> // failed
![A starry night sky.](../../assets/astro.png) // <ONLY WORKS>
<img src="/_astro/astro.hash.png" alt="A starry night sky."/> //failed
```
# .mdx
```
import { Image } from 'astro:assets'
...
<Image src="../../assets/astro.png" width={100} height={45} alt="astro" class="my-class" /> // failed
![A starry night sky.](../../assets/astro.png) // failed
<img src="/_astro/astro.hash.png" alt="A starry night sky."/> //failed
```

i don't know what i'm missing from document.
btw, i wanna resize my image, but failed.
if i cant resize images in markdown, should i split code Content parts and images?

### Link to Minimal Reproducible Example

0

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello, you cannot use components in Markdown. There's currently no ways to resize images in Markdown when using Markdown syntax. You would need a remark / rehype plugin.

For MDX, you need to import the images, like you'd do in .astro files. The Markdown syntax (`![]()`) is currently not supported in MDX, but would also not allow you to resize the images.

**Comment by JUNGHUNKIM-7** [comment]
@Princesseuh Thanks! i have already seperated text contents & photoes and assemble these in .astro file again. Onething im curious is if i cant resize image in md file, is it meaningful using md or mdx files rather than using just pure astro file?

**Comment by vadimkantorov** [comment]
Are there any news on native image resizing from Markdown / MDX in Astro in 2025?
