### ISSUE TITLE
Assets in markdown - external URL throws error

### ISSUE THREAD

**Issue by marcinjahn** [withastro/astro#6731]
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

I'm using the experimental Assets feature in Astro.
I included an image in Markdown with:

```md
![](https://marcinjahn.com/assets/img/puff-help.af8a2784.png)
```

There's an error:

> Cannot find module 'https://marcinjahn.com/assets/img/puff-help.af8a2784.png' imported from '/home/projects/github-lrqjbq/src/pages/test.md'

> Error: Cannot find module 'https://marcinjahn.com/assets/img/puff-help.af8a2784.png' imported from '/home/projects/github-lrqjbq/src/pages/test.md'
    at nodeImport (file:///home/projects/github-lrqjbq/node_modules/vite/dist/node/chunks/dep-79892de8.js:54078:25)
    at ssrImport (file:///home/projects/github-lrqjbq/node_modules/vite/dist/node/chunks/dep-79892de8.js:53999:20)
    at ssrDynamicImport (file:///home/projects/github-lrqjbq/node_modules/vite/dist/node/chunks/dep-79892de8.js:54026:16)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lrqjbq?file=src/pages/test.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by marcinjahn** [comment]
@Princesseuh How do I track when these changes are released?

**Comment by Princesseuh** [comment]
When this PR gets merged: <https://github.com/withastro/astro/pull/6720>
It'll probably be today in a few hours when more of the team is online.
