### ISSUE TITLE
Assets in markdown - image ratio is not retained

### ISSUE THREAD

**Issue by marcinjahn** [withastro/astro#6732]
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

When using the Assets feature of Astro, the local images included in the markdown files are stretched, ratio is not kept.

markdown example:

```md
![](../../../assets/puff-help.png)
```

Result:
![image](https://user-images.githubusercontent.com/10273406/229367756-57e7a05c-fefc-4779-85bd-dfd439c520a0.png)

### Link to Minimal Reproducible Example

Can't upload images into Stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by marcinjahn** [comment]
I guess the `height: auto` CSS is missing in addition to the existing `max-width: 100%`. If someone points me at where that CSS could be added, I can prepare a PR.

**Comment by Princesseuh** [comment]
The CSS you're using is up to you, Astro does not generate any CSS for images by default. 

Could you provide more details?

**Comment by marcinjahn** [comment]
To give you a bit of a background, I come from VeuPress which comes with a good set of defaults. It might be that Astro does not aim to provide that kind of experience, and maybe it's actually a good thing since you as a developer are supposed to control the whole thing.

**Comment by Princesseuh** [comment]
Ah yeah, in Astro this is up to the theme you're using. The assets feature itself has no opinions regarding CSS (exactly so themes are free to do what they want)

Closing this issue since we're not planning on changing this.
