### ISSUE TITLE
Astro global somehow re declared by lit 

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#6734]
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

It seems like global is declared I have nothing installed but the lit integration yet I get this error I don't know what is going on I'm sure that astrojs/lit is the only extension that does this.  

```
Identifier 'global' has already been declared
  File:
    C:\Users\louis\Desktop\web-projects\templates\astro\minimal\node_modules\.pnpm\vite@4.2.1\node_modules\vite\dist\node\chunks\dep-79892de8.js:53995:28
  Code:
    53994 |         const AsyncFunction = async function () { }.constructor;
    > 53995 |         const initModule = new AsyncFunction(`global`, ssrModuleExportsKey, ssrImportMetaKey, ssrImportKey, ssrDynamicImportKey, ssrExportAllKey, '"use strict";' + result.code + `\n//# sourceURL=${mod.url}`);
            |                            ^
      53996 |         await initModule(context.global, ssrModule, ssrImportMeta, ssrImport, ssrDynamicImport, ssrExportAll);   
      53997 |     }
      53998 |     catch (e) {
  Stacktrace:
SyntaxError: Identifier 'global' has already been declared
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///C:/Users/louis/Desktop/web-projects/templates/astro/minimal/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:53995:28)
(x2)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-q1ng8g?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your Minimal Reproducible Example is not public

**Comment by louiss0** [comment]
> Your Minimal Reproducible Example is not public

Well I forgot I'm going to now give you something to work with this is the error that I see now.

![image](https://user-images.githubusercontent.com/29028601/229839177-77e4e87a-5c62-4676-a6e1-1ef6e8295bd0.png)

**Comment by louiss0** [comment]
> Your Minimal Reproducible Example is not public

I forgot to tell you that I changed the file.

**Comment by louiss0** [comment]
I changed the file I think you can use mine or the one you see here

**Comment by lschierer** [comment]
I get this as soon as I run ```pnpm astro add lit``` accepting all defaults in a fresh install of ```pnpm create astro``` where I told it to use the sample files.

**Comment by liidtke** [comment]
same issue here

**Comment by RogierdeRuijter** [comment]
Same issue. Running `rpm run build && npm run preview` instead of `rpm run dev` can be used as a workaround

**Comment by lschierer** [comment]
unfortunately the preview command isn't compatible with astro-sst/lambda

**Comment by augustjk** [comment]
Updating the dependency `@lit-labs/ssr-dom-shim` to 1.1.1 will warn instead of throwing on repeat custom element registrations.

**Comment by kemptone** [comment]
> I get this as soon as I run `pnpm astro add lit` accepting all defaults in a fresh install of `pnpm create astro` where I told it to use the sample files.

Same here.

**Comment by kemptone** [comment]
> Updating the dependency `@lit-labs/ssr-dom-shim` to 1.1.1 will warn instead of throwing on repeat custom element registrations.

I checked my pnpm-lock file, and it says ssr-dom-shim is 1.1.1. 

However, I am getting this error:

```
 error   Identifier 'global' has already been declared
  File:
    /Users/justinkempton/Developer/AstroLit/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54402:28
  Code:
    54401 |     try {
    > 54402 |         const initModule = new AsyncFunction(`global`, ssrModuleExportsKey, ssrImportMetaKey, ssrImportKey, ssrDynamicImportKey, ssrExportAllKey, '"use strict";' +
            |                            ^
      54403 |             result.code +
      54404 |             `\n//# sourceURL=${mod.id}${sourceMapSuffix}`);
      54405 |         await initModule(context.global, ssrModule, ssrImportMeta, ssrImport, ssrDynamicImport, ssrExportAll);
```

**Comment by kemptone** [comment]
I tried running the install of Astro without install, and without Demo files.
Starting it does not immediately error.

When I add a demo template, it errors on the decorators, which should be a different bug.

**Comment by pyrossh** [comment]
I guess this an issue when using `pnpm`. I've seen issues in nextjs as well when using `pnpm`. Had to delete `node_modules` and do `npm i` and run it again and it worked.

**Comment by louiss0** [comment]
> Can someone provide a reproduction? The one provided in the OP doesn't show the issue.

It works now I put up this issue seven majors ago. I'm surprised that not team member has said anything until now. I updated all the packages and now all I see is a message telling me that it tried to redo it but it was ignored.
