### ISSUE TITLE
Markdoc unable to create linked images

### ISSUE THREAD

**Issue by zacksiri** [withastro/astro#6738]
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

When I write regular markdown creating a linked image

[![alt text](/path/to/image)](/path/to/link)

I get an error 

```
 docs → getting-started.mdoc failed to validate:
child-invalid
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jgvtlq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ancaemcken** [comment]
I think it starts with the Markdoc schema. The `link` node accepts the children ` ['strong', 'em', 's', 'code', 'text', 'tag', 'inline']`.

I was able to display this linked image: 

```
[![Rick Astley dancing](https://media.tenor.com/x8v1oNUOmg4AAAAM/rickroll-roll.gif)](https://google.com)
```

with a custom link tag.  Below, my solution. 

**custom `link` tag:**

```
import AppLink from './src/components/AppLink.astro'
import markdoc from '@markdoc/markdoc'
const { Tag } = markdoc

export const link = {
  render: AppLink,
  children: ['strong', 'em', 's', 'code', 'text', 'tag', 'inline', 'image'],
  attributes: {
    href: { type: String, required: true },
    target: { type: String },
    rel: { type: String },
    title: { type: String },
  },
}
```

**`AppLink` component:**

```
---
const props = Astro.props;
---
<a href={props.href}>
  <slot />
</a>

```

 **`markdoc.config.mjs`:**

``` 
import { link } from './schema/Link.markdoc';

import { defineMarkdocConfig } from '@astrojs/markdoc/config';

export default defineMarkdocConfig({
  nodes: {
    // see @markdoc/markdoc/schema.ts  for default nodes
    link,
  }
});
```

**Result**
![image](https://user-images.githubusercontent.com/1617798/229562071-08158336-9518-4103-8d0c-4d5ebd3fc0be.png)

NOTE: This example is part of an app under development, so I haven't tried building for prod. Also, in your linked Stackblitz, all whitespace was removed on save, generating additional errors (invalid tag placement), so the formatting must be with the whitespace.

Hope this helps.

**Comment by matthewp** [comment]
Seems to be a downstream Markdoc issue, perhaps take this to them if it seems unnecessarily cumbersome.
