### ISSUE TITLE
Failure to import layout using dynamic location

### ISSUE THREAD

**Issue by yahavatar** [withastro/astro#6757]
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

Yes, Astro

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Firefox Dev

### Describe the Bug

I'm trying to import a layout with a dynamic location. I've tried two different ways to create the path to the layout:

import My_Layout from '../layouts/' + type + '_layout.astro';

Fails with a message like:        Expected ";" but found "+"

or

import my_layout from `../layouts/${furniture}_layout.astro`;

Fails with a message like:      Expected string but found "`@layouts${"

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mnfabi?on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hello, you are not allowed to do substitutions like that in a static import statements. You will need to use a dynamic import statement instead. Here's an example that does what you are attempting to do: https://stackblitz.com/edit/github-mnfabi-ppnibq?file=src%2Flayouts%2Fchair_layout.astro,src%2Flayouts%2Fdesk_layout.astro,src%2Fpages%2Fget-[furniture].astro&on=stackblitz

**Comment by yahavatar** [comment]
matthewp,
THANK YOU! My suspicion was that it could be done, but I am overly-suspicious at times... This helps me out a bunch!
