### ISSUE TITLE
RSS Feed generator

### ISSUE THREAD

**Issue by zellwk** [withastro/astro#6767]
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

nom

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Hi! I'm reading up the specs for a RSS file, and I can't help but notice this: 

- `@astro/rss` creates a `<content:encoded>`XML tag when we include contents
- But RSS specifications did not include a `<content>` XML tag at all. 

Here's an image from the [RSS Specifications](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt). 

![CleanShot 2023-04-06 at 17 32 03](https://user-images.githubusercontent.com/3607637/230336552-1fcafa16-b8c3-4e2f-976e-3f6f9bc26196.png)

And here's an example of my feed that I generated when I include contents

![CleanShot 2023-04-06 at 17 33 12](https://user-images.githubusercontent.com/3607637/230336720-88569afe-df65-4c18-827d-a6f611b7b2fe.png)

Can anyone tell me where to find out more about this `<contents>` tag, and whether this is intentional or a bugl? Thank you. 

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
`content:encoded` is indeed not part of the specification, but it is a [pseudo-standard](https://www.rssboard.org/rss-profile#namespace-elements-content-encoded) that is widely supported. See https://www.w3.org/wiki/RssContent for other possible patterns.

I can look into why/where this was added, but I might have to pull in our resident RSS experts.

**Comment by zellwk** [comment]
Thank you, this is very helpful.
