### ISSUE TITLE
server: AM [getStaticPaths] getStaticPaths() is ignored when "output: server" is set

### ISSUE THREAD

**Issue by systemctls** [withastro/astro#6768]
### What version of `astro` are you using?

2.2.0

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

 I created a blog using astro, using `npm create astro@latest -- --template blog`.  The docker used for the build.  The basic configuration is as follows: 
 ```
import { defineConfig } from 'astro/config';
import node from '@astrojs/node';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
  output: 'server',
  adapter: node({
    mode: 'standalone'
  }),
	site: 'http://xxx.xxx.xx.xxx:3000',
	integrations: [mdx(), sitemap()],
});

```
dockerfile
```
FROM node:lts-alpine as runtime
WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000
CMD node ./dist/server/entry.mjs
```
 , after Linux deployment, the home page can be accessed, and the following error is received when visiting the blog subpage 
error: 
```
Server listening on http://0.0.0.0:3000
09:49:53 AM [getStaticPaths] getStaticPaths() is ignored when "output: server" is set.
09:49:53 AM [ssr] TypeError: post.render is not a function
    at file:///app/dist/server/chunks/pages/all.d2fa7fe8.mjs:330:34
    at [...slug] (file:///app/dist/server/chunks/astro.afe21561.mjs:1209:12)
    at renderPage$1 (file:///app/dist/server/chunks/astro.afe21561.mjs:2893:36)
    at renderPage (file:///app/dist/server/chunks/astro.afe21561.mjs:3567:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #renderPage (file:///app/dist/server/chunks/astro.afe21561.mjs:3948:24)
    at async NodeApp.render (file:///app/dist/server/chunks/astro.afe21561.mjs:3892:22)
    at async file:///app/dist/server/entry.mjs:2586:28

```
 Normal access: http://xxx.xxx.xxx.xxx:3000/blog, http://xxx.xxx.xxx:3000/about 

 Error visit: http://xxx.xxx.xx.xxx:3000/blog/markdown-style-guide/ 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fv6tiq/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
The warning is correct. The `blog` example is a SSG example, not SSR. 

It cannot be used in SSR (and there's no purpose to do so, since it's all static)
