### ISSUE TITLE
The error with public image on Windows 10

### ISSUE THREAD

**Issue by cihad** [withastro/astro#6784]
### What version of `astro` are you using?

2.2.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows 10

### What browser are you using?

Chrome

### Describe the Bug

```astro
---
import { Image } from "@astrojs/image/components"
import publicCat from "/cat.png"
import assetsCat from "../assets/cat.png"
const remoteCat = "https://upload.wikimedia.org/wikipedia/commons/e/e9/Felis_silvestris_silvestris_small_gradual_decrease_of_quality.png"
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<title>Astro</title>
	</head>
	<body>
		<h1>/public</h1>
		<!-- <img src={publicCat} alt=""> -->

		<h1>src/assets</h1>
		<img src={assetsCat} alt="">

		<h1>remote</h1>
		<img src={remoteCat} alt="">

		<h1>/public with @astrojs/image</h1>
		<Image src={publicCat} alt="" width={160} aspectRatio="16:9" />
	</body>
</html>

```

This gives an error:

```
ENOENT: no such file or directory, open 'C:\cat.png'
```

It's resolving the image url incorrectly.

### Link to Minimal Reproducible Example

https://github.com/cihad/astro-public-image-bug-demo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by cihad** [comment]
Now I have encountered this problem exists in images under src/assets directory.

**Comment by cihad** [comment]
The samething is valid for `Ubuntu 22.04.1 LTS`

**Comment by Princesseuh** [comment]
Importing files from public is a not a supported pattern. You can refer to files from there directly using a string referring to the final path. (So for an image at `public/image.png`, you would do `<img src="/image.png" />`)
