### ISSUE TITLE
Astro + Tailwind + Svelte integrations - Errors parsing <style> sections with "@apply ..."

### ISSUE THREAD

**Issue by alf5** [withastro/astro#6787]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

This error can be duplicated simply by  generating a fresh astro project and adding the integrations:
- `npm init astro my-app` - I used Typescript
- then add svelte and tailwind
    - `npx astro add tailwind`
    - `npx astro add svelte`
- in a svelte file use a `<script>` section
    - add tailwind @apply styles in there that use a selector with a ":" e.g. `hover:`
- run `npm run dev`
- open a browser on the page and an error is shown (e.g.  "Semicolon or block is expected")

### Link to Minimal Reproducible Example

https://github.com/alf5/astro-tailwind-svelte

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alf5** [comment]
When I explored this further I found that adding the attribute `lang="css"` to the `<style>` tag in the svelte file it made it work.
This still generated an error within VS Code (Svelte language server I imagine).

I created a postcss config file `postcss.config.js` with:
```
export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```
This made VS Code happy.

I created a branch with those changes in the example project:
https://github.com/alf5/astro-tailwind-svelte/tree/workaround

**Comment by bluwy** [comment]
Yes, you need `<style lang="postcss">` since you're relying on postcss syntax. This is currently how `vite-plugin-svelte`'s `vitePreprocess` API works. https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md

**Comment by alf5** [comment]
I would of thought `lang="css"` would be the default sent to vite by the @astro/svelte plugin?
Coz if it did then it would work out of the box.

I added vue to the project (`npx asrto add vue`) and converted that Card file to Vue and `@apply` works without having to specify any `lang=...`
It be good if the svelte story was the same.
