### ISSUE TITLE
Slot fallback is showing even when passing in a slot prop.

### ISSUE THREAD

**Issue by edoardofelici** [withastro/astro#6788]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

The slot fallback is now showing even when a slot prop is provided to the 'slottable' component. This bug will break a lot of UIs. 

The regression version is '2.2.1'. Version '2.2.0' is working fine. 

See provided stackblitz example, where installing astro@2.2.0 fixes the problem. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ombtg4?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lukeshiru** [comment]
The same thing is happening to me. Here's a simple code example:

```astro
<!-- Child.astro -->
<strong>
  <slot name="foo">Default value</slot>
</strong>

<!-- Parent.astro -->
<Child>
  <span slot="foo">Hi</span>
</Child>
```

Results in:

```html
<strong>
  <span>Hi</span>Default value
</strong>
```

Expected (and previous behavior):

```html
<strong>
  <span>Hi</span>
</strong>
```

I'll roll back to `2.2.0` in the meantime. Thanks for reporting @edoardofelici!

**Comment by kamranahmedse** [comment]
I can confirm the same behavior. Rolling back to `2.2.0` fixed the issue.
