### ISSUE TITLE
Error when running `pnpm --filter @astrojs/netlify test-edge`

### ISSUE THREAD

**Issue by andremralves** [withastro/astro#6794]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

n/a

### Describe the Bug

I ran `pnpm --filter @astrojs/netlify test-edge` when I was trying to solve a bug with the edge functions and got this error: 

```
error: TS2578 [ERROR]: Unused '@ts-expect-error' directive.
```

This error occurs because the typescript compiler is expecting to find a bug in the next line using the `@ts-expect-error` directive and the error doesn't happen.

With `@ts-ignore` it works fine and removing the `@ts-expect-error` directives that are causing the issue, it works too, but in my ide the lines become underlined pointing some errors. Probably because it's not recognizing Deno's specific code.

### Link to Minimal Reproducible Example

https://github.com/withastro/astro 

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks! We don't use issues to track internal things like this, so please submit a PR to fix if you haven't already. Thanks again!
