### ISSUE TITLE
Redirect from the page gives empty page and response 200

### ISSUE THREAD

**Issue by teinett** [withastro/astro#6795]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

firefox, chrome

### Describe the Bug

I migrate old Tumblr blog to AstroJS. 
I have old links domain.com/post/123, which I would like to save.
At the end I will have pages:
- domain.com/post/123 - one post page
- domain.com/post - empty route
- domain.com/archive - list of all post with pagination

**I want to have 301 redirect** from domain.com/post to domain.com/archive.

**What I did**:

The code of `src/pages/post.astro`:
```
---
Astro.redirect('/archive');
---
```

In the browser I have 2 options:
- domain.com/post/ (with trailing slash) - page of error 404;
- domain.com/post (without trailing slash) - empty page, no errors in console. 

My config `astro.config.mjs`:
```
import { defineConfig } from 'astro/config';
import mdx from "@astrojs/mdx";
import node from "@astrojs/node";


export default defineConfig({
  trailingSlash: 'never',
  integrations: [mdx()],
  output: 'server',
  adapter: node({
    mode: "standalone"
  })
});
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-e5p1e6

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You need to return your redirect.

```astro
---
return Astro.redirect('/archive');
---
```

**Comment by teinett** [comment]
@matthewp Thanks a lot! It works now!
