### ISSUE TITLE
pageSize not included in Page type

### ISSUE THREAD

**Issue by stormwild** [withastro/astro#6796]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

The type for Page may need to be updated to use `pageSize` instead of size. The documentation may also need to be updated to refer to `pageSize` instead of just `size` as shown in the docs, https://docs.astro.build/en/core-concepts/routing/#complete-api-reference

If I try to use the `size` property, the number of items in the page is not the number specified. It only works if `pageSize` is used.

Modifying the `paginate` function to recognize only the `size` property may be a breaking change.

![image](https://user-images.githubusercontent.com/657249/230752851-122f6e20-3197-4dbd-a1ef-bfef8381fbdd.png)

[Routing 🚀 Astro Documentation](https://docs.astro.build/en/core-concepts/routing/#complete-api-reference)

```ts
interface Page<T = any> {
  /** number of items per page (default: 25) */
  size: number;
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/stormwild/stormwild.github.io

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
`size` is the number of items in a paginated route set by the `pageSize` option of the options argument of the [`paginateFunction`](https://github.com/withastro/astro/blob/c04ea0d43cc2aa8ebe520a1def19dd89828cf662/packages/astro/src/@types/astro.ts#L1332).
Here's the type you want to use for the [`options argument`](https://github.com/withastro/astro/blob/c04ea0d43cc2aa8ebe520a1def19dd89828cf662/packages/astro/src/@types/astro.ts#L1292) `paginate` function

**Comment by stormwild** [comment]
> `size` is the number of items in a paginated route set by the `pageSize` option of the options argument of the [`paginateFunction`](https://github.com/withastro/astro/blob/c04ea0d43cc2aa8ebe520a1def19dd89828cf662/packages/astro/src/@types/astro.ts#L1332). Here's the type you want to use for the [`options argument`](https://github.com/withastro/astro/blob/c04ea0d43cc2aa8ebe520a1def19dd89828cf662/packages/astro/src/@types/astro.ts#L1292) `paginate` function

That worked, thanks. @MoustaphaDev :)

**Comment by stormwild** [comment]
My mistake sorry.
