### ISSUE TITLE
sitemap-index.xml does not produced in dev

### ISSUE THREAD

**Issue by kant2002** [withastro/astro#6797]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Edge

### Describe the Bug

I have plugin `sitemap()` in the project and it builds sitemap fine. I would like to run pa11y as part of my dev loop.
Currently I'm using this command `pa11y-ci --sitemap https://open-ui.org/sitemap-index.xml --sitemap-find https://open-ui.org --sitemap-replace http://localhost:3000` so I take sitemap from remote location and perform substitution.

But I encounter situation where I would like to exclude some page from sitemap and only way to to that is build website locally and  serve static content. This is not very productive. Is it possible somehow give ability to have `sitemap-index.xml` when run using `astro dev`?

I possible willing to submit PR, unless that would be complicated. Just want to know opinion first.

### Link to Minimal Reproducible Example

1

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @kant2002 we would definitely be interested in dev support. If you look at the code it's entirely geared towards build at the moment. But I don't see why dev mode couldn't be added.

**Comment by nathanchere** [comment]
Does this need any special config to make work in dev? I can't get it working in 4.7.0

astro build:

```
19:19:37 [@astrojs/sitemap] `sitemap-index.xml` created at `dist`
```

astro dev:

```
$ astro dev
 astro  v4.7.0 ready in 210 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

19:21:57 watching for file changes...
19:22:00 [astro-icon] Loaded icons from src/assets/icons, fa-brands, fa-solid, heroicons
19:22:00 [404] /sitemap-index.xml 33ms
```

**Comment by nikolailehbrink** [comment]
Hi @matthewp, I’m a bit confused about why this issue was closed. Is it more of a proposal, and that’s why you closed it? I’d really love to see this feature implemented. Right now, I have to validate changes by rebuilding my project each time, which is quite cumbersome.
