### ISSUE TITLE
Image seems not be rendered in netlify

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [withastro/astro#6800]
### What version of `astro` are you using?

2.2.0

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Firefox

### Describe the Bug

- Problem
1. Rendering image is fine in localhost
2. it is not rendered on netlify
3. i'm not sure which side's problem between astrojs and netlify.

Did i missing something in my code or set wrong config?

```js
export default defineConfig({
    integrations: [svelte(), tailwind()],
    output: 'server',
    adapter: netlify(),
    experimental: {
        assets: true,
    },
    image: {
        service: "astro/assets/services/sharp",
    },
});
```

```js
import { Image } from 'astro:assets';
import imgPath from '../assets/img.jpg';

<Image
      class="rounded-md"
      src={imgPath}
      width={600}
      quality="max"
      alt="alt-img"
  />
```

```
1:51:23 PM: 04:51:23 AM [build] output target: server
1:51:23 PM: 04:51:23 AM [build] deploy adapter: @astrojs/netlify/functions
...
1:51:32 PM:  generating optimized images 
1:51:32 PM: Completed in 181ms.
1:51:32 PM: 
1:51:32 PM: 
1:51:32 PM:  finalizing server assets 
1:51:32 PM: 04:51:32 AM [build] Rearranging server assets...
1:51:32 PM: 04:51:32 AM [build] Server built in 10.11s
1:51:32 PM: 04:51:32 AM [build] Complete!
```
### Link to Minimal Reproducible Example

.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Please include a reproduction

**Comment by JUNGHUNKIM-7** [comment]
> Could you add logs from Netlify?

There wasn't any errors in whole log, and as you see, that is only clue that i found in build log.
running in local server was fine, i think that is more likely problems of netlify.

1:51:32 PM: generating optimized images 
1:51:32 PM: Completed in 181ms.

**Comment by Princesseuh** [comment]
Without a reproduction this is still impossible to debug, please include one. If you can't include a minimal one, your full repo can still be useful.

**Comment by matthewp** [comment]
Closing. Please open a new issue if you can create a reproduction.
