### ISSUE TITLE
Environment variables are undefined when using @astrojs/vercel/edge

### ISSUE THREAD

**Issue by markmals** [withastro/astro#6801]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

Vercel edge

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When deploying an Astro project using environment variables from `import.meta.env` to Vercel using the Vercel edge adapter (`@astrojs/vercel/edge`), any [user-set environment variables](https://vercel.com/docs/concepts/projects/environment-variables#declare-an-environment-variable) are undefined. If you switch to the serverless adapter (`@astrojs/vercel/serverless`) without changing the environment variables or their configuration, then the environment variables are defined again.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kdhkd8?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by larryhudson** [comment]
I've found that environment variables only work inside edge functions when they are prefixed with `PUBLIC_`. I found a similar issue here:
https://github.com/withastro/astro/issues/6713

I created a repo to recreate the issue here:
https://github.com/larryhudson/astro-vercel-edge-env-testing

**Comment by markmals** [comment]
@larryhudson that isn't something I'm seeing. There are several Vercel environment variables (I assume, set by the service themselves) which are prefixed with `PUBLIC_`, but the environment variables I set myself have unchanged names. It's just that their values are undefined: 
<img width="297" alt="Screenshot 2023-04-09 at 11 05 27 PM" src="https://user-images.githubusercontent.com/39869007/230823632-19b0a13e-bb05-4b24-bf87-0a6086b362c5.png">

**Comment by matthewp** [comment]
Yes, let's use https://github.com/withastro/astro/issues/6713 to track this issue. I'm debugging this now.
