### ISSUE TITLE
Importing .yaml file incorrectly shows up as an error after installing @rollup/plugin-yaml

### ISSUE THREAD

**Issue by kamoshi** [withastro/astro#6802]
### What version of `astro` are you using?

2.2.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

1. Follow an example shown here:
https://docs.astro.build/en/recipes/add-yaml-support/
2. Try importing a yaml file:
`import example from './example.yml';`
3. Use the `astro check` command

As a result we get an error reported to us:
```
08:10:06 PM [diagnostics] 
 /home/projects/github-xcqkkx/src/pages/index.astro:2:18 Error: Cannot find module './example.yml' or its corresponding type declarations.
01  ---
02  import yaml from './example.yml';
                     ~~~~~~~~~~~~~~~
03  import json from './example.json';

08:10:06 PM [diagnostics] Result (1 file): 
- 1 error
- 0 warnings
- 0 hints
```

However the `.yaml` file is correctly imported in the `.astro` file.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xcqkkx?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Vite plugins only applies to your build. To make it work in your editor (or `astro check`, which also uses the same process), you need to either use a TypeScript plugin for JavaScript files or create a module definition. This is not specific to Astro

**Comment by kamoshi** [comment]
I feel like adding this information in the docs page would be very useful in the future for anyone coming across the recipe and getting confused 😀

**Comment by Princesseuh** [comment]
I agree! I sent a message to our docs people about this
