### ISSUE TITLE
Wildcard exports are inconsistently resolved

### ISSUE THREAD

**Issue by lynshi** [withastro/astro#6814]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Edge

### Describe the Bug

I used [openapi-generator](https://github.com/OpenAPITools/openapi-generator) to generate some client code, and everything generated is exported using wildcards. This seemed to work fine until today, where I noticed a couple things:
1. On certain browsers (Edge and Firefox, but not Chrome), I see errors like `Uncaught (in promise) SyntaxError: The requested module '/src/.../index.ts' does not provide an export named '$NameOfExport'` in the console after my page loads.
2. When I run `astro build`, I see warnings like `"HelloRequest" is not exported by "src/client/index.ts", imported by "src/components/Hello.svelte"`.

I noticed a similar issue was raised recently in https://github.com/vitejs/vite/issues/12284 (though not yet released), so this may be a symptom of that? Not sure why it was working yesterday though!

Note that I attached a stackblitz; when you run `npm run dev`, you _might_ see a similar error the first time you run it, but it works fine afterwards. The warning consistently shows up for `npm run build`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pa2cr2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
It seems to be caused by `Hello.svelte` being compiled and still preserving:

```js
// compiled output
import { HelloRequest } from "/src/client/index.ts";
```

In Svelte, TS is compiled with `importsNotUsedAsValues: 'preserve'` so you need to use `import type` instead to elide the import. You can set `"importsNotUsedAsValues": "error"` or `"verbatimModuleSyntax": "true"` in your `tsconfig.json` `compilerOptions` if you want to get stricter messages from TypeScript. Or simpler with `"extends": "astro/tsconfigs/strict"`.

I think we can document this in the svelte integration docs.

**Comment by lynshi** [comment]
Thanks! 

I did have `tsconfig.json` with the `extends` setting locally, but there were no errors. In the linked stackblitz, nothing happens on `tsc --noEmit` when I have the following in `tsconfig.json`.
```json
{
  "extends": "astro/tsconfigs/strict"
}
```

I had to use the explicit settings for there to be errors displayed:
```json
{
  "compilerOptions": {
    "importsNotUsedAsValues": "error",
    "ignoreDeprecations": "5.0"
  }
}
```
