### ISSUE TITLE
Unable to run `npm run dev` on astro project because of miss matched node version

### ISSUE THREAD

**Issue by michalzard** [withastro/astro#6820]
### What version of `astro` are you using?

2.2.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm,pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome,Firefox

### Describe the Bug

![image](https://user-images.githubusercontent.com/58849789/231311310-73e5df95-dac9-4a7c-a730-033a55bfc92e.png)

![image](https://user-images.githubusercontent.com/58849789/231311419-a3065f1e-e85d-4286-82c4-6d29729796a6.png)

im only able to get it running by installing node as devDependency which i didnt need to do in last project that was written in 2.1.9 version and im getting this error on vercel aswell 
![image](https://user-images.githubusercontent.com/58849789/231311553-cd0e640b-6968-439a-8af8-bac7c0e658ce.png)

### Link to Minimal Reproducible Example

.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
We get the version using a simple `process.versions.node`, which is the standard way to get the current version of node.

Is it possible that npm is running the wrong version? You definitely should not need to add node as a devDep.

**Comment by Princesseuh** [comment]
Happy to hear you found a solution! I doubt there's anything we can do on our end here, so I'll close this issue. Thank you for reporting back

**Comment by michalzard** [comment]
Thank you again for quick response. <3
