### ISSUE TITLE
create astro stuck at "Template copying..." step 

### ISSUE THREAD

**Issue by NaserAlqimlas** [withastro/astro#6828]
### What version of `astro` are you using?

2.2.3

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm, yarn, pnpm

### What operating system are you using?

MacOS 13.2.1 M1 hardware

### What browser are you using?

Arc, Firefox

### Describe the Bug

I've tried using create astro multiple times and it keeps getting stuck at the "Template copying..." step. I've tried using 
- yarn v1.22.19
- npm v9.5.0
- pnpm v8.2.0

As well as nodes v18.12.1 and v18.15.0.

I've attempted to run create astro with versions 3.0.5 and 3.1.0 as well as the current latest version (3.1.2) along with the next--refactor version.

Not sure if this is helpful but here is a screenshot
<img width="908" alt="Screenshot 2023-04-13 at 12 09 18 AM" src="https://user-images.githubusercontent.com/32109934/231586312-3c14a171-0e43-4086-bc35-60d1f756885d.png">

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by miguel-rodrigo** [comment]
I had the same issue. It was a network problem in my case. I was using the University network and it didn't work (tried multiple times with different versions of everything), I have no idea why because I have never had this problem before. I used my phone network and it worked like a charm.

I suggest that you try a different network as well, just to rule that out.

**Comment by matthewp** [comment]
Closing as there isn't anything we can do about network issues.

**Comment by naourass** [comment]
I have the same issue, my network is working fine for other requests/connections though.

**Comment by miguel-rodrigo** [comment]
Yeah, mine was working fine too for anything else. It might have been a
false positive from the firewall or something. Just try with your phone or
somewhere else.

**Comment by lidongtony** [comment]
Check your npm/yarn/pnpm registry config
I have set the registry address with https://registry.npmmirror.com/
and it will be fine when I removed it

**Comment by otabekoff** [comment]
I've the same issue on first try.
