### ISSUE TITLE
Issues with Markdoc

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#6829]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm 

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

There are a few problems with Mardoc. I decided to test it and see if things were going to be ok. But I have found a few problems with it 
- Functions can't be used I get an error called invalid child when I attempt to use a function
- Syntax highlighting is not automatically enabled 
- Code Comments are added to each page.

To see the first two problems go to the `markdown-style-guide.mdoc` page. 
I created the Code component with the fence so that it could just be implemented later on. Other than that I will write a discussion soon.   

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-zdtvav

### Participation

- [] I am willing to submit a pull request for this issue.

**Comment by louiss0** [comment]
I have recently discovered that markdoc wraps each page in an article tag I hope this is not the way this integration will work in the near future. This is where I discovered it from [here](https://github.com/withastro/docs/issues/2904). This is another problem.

**Comment by louiss0** [comment]
I recently found out that Markdoc Errors are not displayed because of the Astro Markdoc Implementatiion. I tried to talk to them about error messages but instead I was told this. 

> Can you tell me how you are performing the validation? It seems like you are just seeing the error id, but Markdoc itself provides very explicit messages. For example, an invalid type shows the [message](https://github.com/markdoc/markdoc/blob/main/src/validator.ts#L209) "Attribute '${key}' must be type of '${t}" and an error on a matches rule shows the [message](https://github.com/markdoc/markdoc/blob/main/src/validator.ts#L223) "Attribute '${key}' must match one of ${matches}".
> Ryan Paul Maintainer of Stripe 

I think there is a way of transferring errors from one catcher to another. I think you decided to override the Markdoc errors with your own one.

**Comment by paulrudy** [comment]
> I have recently discovered that markdoc wraps each page in an article tag I hope this is not the way this integration will work in the near future. This is where I discovered it from [here](https://github.com/withastro/docs/issues/2904). This is another problem.

The solution to this issue is included in [this comment](https://github.com/withastro/docs/issues/2904#issuecomment-1479985063) in the issue that you linked. Markdoc by default wraps content in `<article>...</article>`. On markdoc's github, they [suggested](https://github.com/markdoc/markdoc/discussions/347#discussioncomment-5393103) an undocumented method of avoiding that wrapping. I made an [issue](https://github.com/withastro/astro/issues/6628) that has since been closed, and now that method works fine in Astro.

**Comment by matthewp** [comment]
Can you create 1 issue per bug report? It's hard to investigate many things at once. Scanning this issue, for example, I can't tell what is a bug in Astro's Markdoc integration and what is just how Markdoc works. I suspect the error catching is probably a bug on our end, for example. Please create an issue just about that.

Closing to keep the repo to actionable issues.
