### ISSUE TITLE
"Invalid YAML front matter in" - error with Github Pages build process

### ISSUE THREAD

**Issue by matt765** [withastro/astro#6830]
### What version of `astro` are you using?

2.2.3

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

All of them

### Describe the Bug

I have AstroJS project uploaded on Github as open source repository. I don't use Github Pages for hosting, but when it was enabled there was an error in build process. I didn't find working solution to fix it yet. I compared Layout.astro and Index.astro files to current Astro starter but I didn't find any bugs. VSCode with Eslint don't show any errors too.

Log file with an error: https://github.com/matt765/Tailcast/actions/runs/4639085395/jobs/8209553067
Repository: https://github.com/matt765/Tailcast

![image](https://user-images.githubusercontent.com/63603595/231594864-8a687404-6d81-4390-8352-71826285072c.png)

### Link to Minimal Reproducible Example

https://github.com/matt765/Tailcast/actions/runs/4639085395/jobs/8209553067

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
That happens when your action is misconfigured and Jekyll is trying to build an Astro project. You can add a .nojekyll file to your project's root to fix this.

We have an official guide and action you can use to set up GitHub Pages correctly: https://docs.astro.build/en/guides/deploy/github/

Closing since this is not a bug in Astro, it's just how GitHub Pages work

**Comment by aramfe** [comment]
This is not the correct answer. I've copied the workflow file one by one.

**Comment by isaackwok** [comment]
I have the same issue too and I solved it by adding a file named `.nojekyll` to the root of my project.

**Comment by donokuda** [comment]
> I have the same issue too and I solved it by adding a file named `.nojekyll` to the root of my project.

This solved my issue as well. Would it make sense to add this as a note to the documentation?

**Comment by rioovs** [comment]
> I have the same issue too and I solved it by adding a file named `.nojekyll` to the root of my project.

this solved my problem

**Comment by gelembungsahabat** [comment]
this is still a thing now, and add .nojekyll fixed my issue

**Comment by ssgalib** [comment]
> I have the same issue too and I solved it by adding a file named .nojekyll to the root of my project.

solved my issue as well
