### ISSUE TITLE
[astro:build] Transform failed with 1 error:

### ISSUE THREAD

**Issue by toMatthew** [withastro/astro#6843]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

building client 
[astro:build] Transform failed with 1 error:
astro-entry:D:/t-project/t-n-astro/src/components/Nav.astro:25:26: ERROR: Unexpected "default"
file: astro-entry:D:/t-project/t-n-astro/src/components/Nav.astro:25:26

Unexpected "default"
23 |  Astro.self = $$Nav;
24 |
25 |  return $$render`export ${ default } from "D:/t-project/t-n-astro/src/components/Nav.astro"`;
   |                            ^
26 |  }, 'astro-entry:D:/t-project/t-n-astro/src/components/Nav.astro');
27 |  export default $$Nav;

 error   Unexpected "default"
  File:
    astro-entry:D:/t-project/t-n-astro/src/components/Nav.astro:25:26

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5iebyb?file=src/components/Nav.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by josipslavic** [comment]
You are getting this error because you are trying to hydrate an Astro component with a `client:` modifier. To fix it change `<Nav client:load />` into just `<Nav />` in your game.astro page.

For further explanation check: https://docs.astro.build/en/core-concepts/framework-components/#can-i-hydrate-astro-components

**Comment by toMatthew** [comment]
Thanks, `client:` just can use UI Framework components, before I thought using `client：` would generate client code
