### ISSUE TITLE
Getting headings from a markdoc file using the render() method returns an empty object.

### ISSUE THREAD

**Issue by hammadmajid** [withastro/astro#6855]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Edge

### Describe the Bug

When I try to get the headings from a markdoc file using the `render()` method, it returns an empty object.

```ts
import { getEntryBySlug } from 'astro:content';

const entry = await getEntryBySlug('blog', 'post-1');
const { Content, headings } = await entry.render();

console.log(headings) // []
console.log(typeof headings) // object
```

`post-1` at `src/content/blog/post-1.mdoc` contains a few different level of headings and they rendered as expected by `Content`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vwtxh9

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
This is expected at the moment! headings and ID calculation are being tackled in the next patch release 👍

**Comment by paulrudy** [comment]
Thanks for adding markdoc heading render @bholmesdev! Now I don't have to roll my own :)
