### ISSUE TITLE
Cannot re-export astro component in .ts file

### ISSUE THREAD

**Issue by recallwei** [withastro/astro#6858]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

![image](https://user-images.githubusercontent.com/62941121/232266238-1296cdba-ca0f-4529-80dc-2e51ecade58f.png)
![image](https://user-images.githubusercontent.com/62941121/232266241-7d002a99-1951-4814-b450-75b2106f11db.png)

I want to re-export Astro components in a .ts file, but TypeScript cannot recognize the .astro module.
Actually, it does work in dev mode. But, cannot pass the TypeScript check.

![image](https://user-images.githubusercontent.com/62941121/232266655-cc125507-25b9-4084-ad91-09a3f8b089ff.png)

I use VSCode and follow the contents of the doc below.
![image](https://user-images.githubusercontent.com/62941121/232266322-942c1855-f318-41c8-a3c5-b967dfd07f58.png)

How to reproduce: run the `build` command.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/upbeat-breeze-pcepco

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You cannot pass a file that imports an Astro component through `tsc`, it'll never work since TypeScript does not know about .astro files. In the future, we plan on making it so `astro check` also checks .ts files to support this use-case.

As for the editor part, the pre-release version of the extension, it should fix the issue! Though it is a bit brittle at times due to TypeScript's API not being too amazing for plugins.

**Comment by recallwei** [comment]
@Princesseuh 
Thanks, I removed the `tsc` check. 

And I'm using the pre-release version, only if I open the `index.ts` file where I try to re-export the `.astro` file, TypeScript will throw the error. 

Maybe my TypeScript version is too high, which is `5.0.4`. After I switched the TS version to `4.9.5`, the error disappeared.

**Comment by matthewp** [comment]
Closing as this can be solved without code changes. Thanks

**Comment by vighnesh153** [comment]
> You cannot pass a file that imports an Astro component through tsc, it'll never work since TypeScript does not know about .astro files.

@Princesseuh In the [docs](https://docs.astro.build/en/guides/typescript/#type-checking), it is mentioned that we can add `tsc --noEmit` to the npm script to check for errors in `ts` files. Does that not apply to files which are re-exporting astro components?

**Comment by Princesseuh** [comment]
It does, you'll get errors in those files unless you use a TypeScript comment to ignore the errors / exclude those files from your TypeScript project. In the future, we hope to make `astro check` also check TypeScript files in order to avoid this issue.
