### ISSUE TITLE
Astro.config.ts generate temp file automatically

### ISSUE THREAD

**Issue by recallwei** [withastro/astro#6861]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I switch `astro.config.mjs` to `astro.config.ts`. Sometimes after I save the .ts files, the temp .ts file
generated automatically. And it will also disappear automatically.

Is this an expected behavior?

![image](https://user-images.githubusercontent.com/62941121/232329508-2001e939-31ab-490d-a23b-fd17d640777b.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/upbeat-breeze-pcepco

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
@recallwei It is expected, it's sort of what makes the config file reload on change
