### ISSUE TITLE
`crypto` global is only partially polyfilled

### ISSUE THREAD

**Issue by pilcrowOnPaper** [withastro/astro#6870]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

(none)

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

(none)

### Describe the Bug

Global `crypto` seems to be polyfilled by Astro but only `crypto.getRandomValues()` exists. `crypto.subtle` and `crypto.randomUUID()` is undefined. 

### Link to Minimal Reproducible Example

https://github.com/pilcrowOnPaper/astro-crypto

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Thanks for reporting @pilcrowOnPaper!

Do you want to submit a PR?

**Comment by andremralves** [comment]
I would like to take this issue, if nobody is working on it.

**Comment by pilcrowOnPaper** [comment]
@MoustaphaDev 

I tried to see what the root cause was but I couldn't even find where `crypto.getRandomValues()` was getting polyfilled. @andremralves , if you don't mind that would be super appreciated!

**Comment by andremralves** [comment]
@pilcrowOnPaper I also was trying to find where polyfill was occurring and getting crazy about it haha.

But then I realized that maybe some library was polyfilling it with a top level code when being imported.

And I found this piece of code in `@astrojs/compiler` library:

https://github.com/withastro/compiler/blob/bedced877522e3a14ec9416b592a2c185b8fd0d5/packages/compiler/node/wasm_exec.ts#L25-L33

```js
if (!globalThis.crypto) {
  Object.defineProperty(globalThis, 'crypto', {
    value: {
      getRandomValues(b) {
        return crypto.randomFillSync(b);
      },
    },
  });
}
```

**Comment by pilcrowOnPaper** [comment]
> For Astro to run on your system, you will also need to have [Node.js](https://nodejs.org/en/) installed, version v16.12.0 or later.

Since Astro's minimum requirement is Node 16, something like this should be fine?

```ts
if (!globalThis.crypto) {
  Object.defineProperty(globalThis, 'crypto', {
    value: crypto.webcrypto as any 
    },
  });
}
```

Type override since Node's `getRandomValues()` is mis-typed https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1194

**Comment by andremralves** [comment]
I thought about adding the `crypto` object to be polyfilled in the `@astrojs/webapi` package. The problem is that `crypto` is already in the `globalThis` when the polyfill function is called because `@astrojs/compiler` created it first. So the polyfill is skipped for this property.

My workaround was to check for missing properties in the `crypto` object and add them. But I think the ideal solution would be to call the polyfill function from the library in an earlier stage, so that `@astrojs/compiler` don't polyfill it with before.

I'm creating a PR with more details.
