### ISSUE TITLE
import vuerouter init with vue.use(router), throw :  can't find window

### ISSUE THREAD

**Issue by NaCoLiu** [withastro/astro#6878]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

macos

### What browser are you using?

Chrome

### vue _app.ts:

import vuerouter init with vue.use(router), throw :  can't find window

### Link to Minimal Reproducible Example

https://none

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Thanks for reporting this @NaCoLiu!

Can you please include a reproduction?

Thanks!

**Comment by NaCoLiu** [comment]
no reproduction , sry.
just install @astro/vue & vue-router.

### astro.config.ts
```javascript
...
{
 integrations: [
    vue({
      jsx: true,
      appEntrypoint: "src/pages/_app"
    }),
]}
```
### _app.ts
```javascript
import {createRouter,createWebHashHistory} from 'vue-router'
import type { App } from 'vue';
const Home = { template: '<div>Home</div>' }
const About = { template: '<div>About</div>' }

const routes = [
  { path: '/', component: Home },
  { path: '/about', component: About },
]

const router = createRouter({
  history: createWebHashHistory(),
  routes, // `routes: routes` 
})

export default (app: App) => {
  app.use(router);
}

```

then astro throw "can't find window"

**Comment by MoustaphaDev** [comment]
That's because this file runs on the server, so you can't use `createWebHashHistory` which is expected to run on the client
This example in the vue-router docs explains how you should [use this api with ssr](https://router.vuejs.org/guide/migration/#new-history-option-to-replace-mod)
These modifications should be enough to make your code not break ()
```diff
- import {createRouter,createWebHashHistory} from 'vue-router'
+ import {createRouter,createWebHashHistory, createMemoryHistory} from 'vue-router'
import type { App } from 'vue';
const Home = { template: '<div>Home</div>' }
const About = { template: '<div>About</div>' }

let history = import.meta.env.SSR ? createMemoryHistory() : createWebHashHistory()


const routes = [
  { path: '/', component: Home },
  { path: '/about', component: About },
]

const router = createRouter({
  history: history,
  history: createWebHashHistory(),
  routes, // `routes: routes` 
})

export default (app: App) => {
  app.use(router);
}
```

**Comment by MoustaphaDev** [comment]
Let me know if that solves your issue @NaCoLiu

**Comment by NaCoLiu** [comment]
nice solution, thx
