### ISSUE TITLE
custom outDir write to "mydir/dist" instead of mydir

### ISSUE THREAD

**Issue by millette** [withastro/astro#6879]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

firefox

### Describe the Bug

Configuring `outDir` (to "mydir" or "./mydir" for example) in astro.config builds into `mydir/dist` instead of `mydir`.

### Link to Minimal Reproducible Example

https://github.com/millette/microattestations-icea

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by millette** [comment]
I added the following to my astro config:

```js
{
 build: {
    server: `./${outDir()}/server`,
    client: `./${outDir()}/client`,
  }
}
```

Say outDir() returns `mydist`.

After that, entry.mjs is written to `mydist/` instead of `mydist/server/`

**Comment by MoustaphaDev** [comment]
Looks like your repo isn't public @millette

**Comment by matthewp** [comment]
`build.server` and `build.client` do not take outDir into account. They are relative to the project root. I would expect whatever you set them to to be where the files are written. You might need a forward slash at the end, as these are converted to URLs.

Please provide a reproduction if you still have a problem, and file it in a new issue.

**Comment by nestoremgi** [comment]
maybe it's not related but i facing an issue similar, output: '../../dis/packages/my-app' is not generating anything instead it´s generate a folder called .vercel/output
