### ISSUE TITLE
Tailwind integration : applyBaseStyles false does not work during run dev

### ISSUE THREAD

**Issue by snimavat** [withastro/astro#6881]
### What version of `astro` are you using?

^2.3.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

firefox

### Describe the Bug

As per the tailwind integration docs [here](https://docs.astro.build/en/guides/integrations-guide/tailwind/)

I have set 

```
  integrations: [tailwind({
    config: { applyBaseStyles: false },
  })]
```

However during `npm run dev`

**I can see that the base.css from npm module is still imported**
And now there's duplicate imports for base.css

<img width="899" alt="Screenshot 2023-04-21 at 9 32 55 AM" src="https://user-images.githubusercontent.com/623295/233538173-63f8272d-9b75-42b8-aa93-4f00aa4d8be0.png">

Notice

`<script type="module" src="/node_modules/@astrojs/tailwind/base.css"></script>`
and `/Users/sudhir/work/sudhir/sites/XXXX/node_modules/@astrojs/tailwind/base.css`

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
I couldn't reproduce this bug, can you link a reproduction?

**Comment by snimavat** [comment]
Sure, i will do it in some time and update here

**Comment by snimavat** [comment]
@MoustaphaDev Sorry, this was some issue with my code tht i found out while i was setting up codesandbox.
It works - can i close the issue ?

**Comment by thorlucas** [comment]
I am having this issue and I don't see the solution here. Can you tell me what was wrong?

**Comment by MoustaphaDev** [comment]
Can you submit a new issue with its own repo @thorlucas?
