### ISSUE TITLE
vue not work

### ISSUE THREAD

**Issue by quantstu** [withastro/astro#6884]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Open ssr through vercel and use vue to develop web pages. There was no problem with local development, but an error occurred when deploying to vercel. The relevant web page content of vue cannot be loaded. There is such an error in the browser console. How should I solve it?
![image](https://user-images.githubusercontent.com/100741190/233672900-cafbd986-f67d-40a8-8be0-f2c38f4974c0.png)
![image](https://user-images.githubusercontent.com/100741190/233673110-1fc1312b-7c53-4492-92ae-1488c252cc4f.png)

### Link to Minimal Reproducible Example

None

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Can you add a reproduction @quantstu ?
It will help a lot for debugging the exact issue you're having.

Thanks!

**Comment by quantstu** [comment]
I found the reason. Using vite-plugin-top-level-await in my project will cause this error, and if I remove it, the error will disappear.

**Comment by gkatsanos** [comment]
@quantstu good to close this issue then?
