### ISSUE TITLE
Confusing imported CSS filenames in production build

### ISSUE THREAD

**Issue by thdoan** [withastro/astro#6889]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I'm importing a global CSS file like this:

**src/layouts/Layout.astro**
```
import '../global.css';
```

How come when I run `astro build` the global.css file is renamed to **about._hash_.css**? It looks like it's taking the first file in the `src/pages` directory and using that as the base for the filename, which is confusing. IMHO it would be more intuitive to name imported files after the original filename, e.g., **global._hash_.css**.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-y5t9cq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
That's how we decided CSS file name should be derived from - the first page name that the CSS is used in. Since CSS chunking can work very differently in some case, this was one of the reliable way to name it so we're sticking with it for now.
