### ISSUE TITLE
Input OnChange Firing

### ISSUE THREAD

**Issue by jpvarbed** [withastro/astro#6890]
### What version of `astro` are you using?

1.14.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

input tag's onChange event handler doesn't seem to fire.
Here's the code in react https://codesandbox.io/s/sweet-antonelli-wfe9tp?file=/src/App.tsx:335-664
Here's with astro https://codesandbox.io/p/sandbox/wizardly-ishizaka-vnsshf?file=%2Fsrc%2Fcomponents%2FSearchBar.tsx
When typing in the input bar there should be an update to the console

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/wizardly-ishizaka-vnsshf?file=%2Fsrc%2Fcomponents%2FSearchBar.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You're not hydrating your component. See https://docs.astro.build/en/core-concepts/framework-components/#hydrating-interactive-components

**Comment by jpvarbed** [comment]
That's right thanks
