### ISSUE TITLE
Astro Executing Function Multiple times !!

### ISSUE THREAD

**Issue by geminigeek** [withastro/astro#6894]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

yarn

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

it seems Astro is executing the function multiple times , or just not clearing the memory on page reload , i have a reproduction to show the issue, i am using marked and front-matter for loading md files from db.  in reproduction i am just using an inline md string. check the stackblitz url just see in the terminal multiple console.log for token.type  reload page and they keep increasing , i also tested the same function without astro and it works fine  here is my standalone code without astro

https://stackblitz.com/edit/github-7owtqd?file=README.md,src%2Fpages%2Findex.astro&on=stackblitz

```
import frontmatter from "front-matter"
import { marked } from "marked"
const dataMd = `
---
title: "About Us"
description: "Sample"
author: "dee"
---

# H1 Heading

## H2 Heading

### H3 Heading

sample paragraph

Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum quas iusto commodi natus eum voluptates accusamus. Laboriosam modi, nobis inventore, asperiores architecto voluptates odit ratione ipsam velit rerum eius quidem eum nostrum tempore magni quibusdam alias perspiciatis molestiae a illum maxime odio? Voluptatem praesentium doloremque commodi, odit assumenda doloribus delectus!

<gallery data="fzr 2000" />

Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum quas iusto commodi natus eum voluptates accusamus. Laboriosam modi, nobis inventore, asperiores architecto voluptates odit ratione ipsam velit rerum eius quidem eum nostrum tempore magni quibusdam alias perspiciatis molestiae a illum maxime odio? Voluptatem praesentium doloremque commodi, odit assumenda doloribus delectus!
`

const markdownContent = frontmatter(dataMd.trim())

const walkTokens = (token) => {
  if (token.type === "html") {
    console.log("token.type :>> ", token)
  }
}
marked.use({ walkTokens })
marked.parse(markdownContent.body)

```

 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7owtqd?file=README.md,src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
I believe what's happening here is that when `marked.use` is called, it adds a new `walkTokens` function to the `marked` options and the previous one isn't replaced of cleaned up.

I suggest setting up `marked` in a different file so that it gets setup once.

**Comment by MoustaphaDev** [comment]
Let me know if this solve your issue @geminigeek

**Comment by geminigeek** [comment]
> 

Hi [MoustaphaDev](https://github.com/MoustaphaDev)

thanks for helping me, your suggestion worked , its working as it should now
