### ISSUE TITLE
script block in astro component getting added t header

### ISSUE THREAD

**Issue by vikramsoni2** [withastro/astro#6895]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

The script block from my astro component is getting added to the header of my page. which is causing longer time to content. How do I configure is so that it includes the script at the end of body tag instead of header.

Attached the git repo I am trying to build. The code which appears in the header section is included in ThemeToggleButton.astro component

### Link to Minimal Reproducible Example

https://github.com/vikramsoni2/astro-blog

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nlxdodge** [comment]
@vikramsoni2 what is the solution? I found that this bug is also applicable to https://github.com/Destiner/astro-analytics/issues/25 which I am trying to research.

**Comment by nlxdodge** [comment]
Nevermind I found the issue, the code snippet from Amplitude is always loading whenever I use some Astro library, but it's in their implementation. Not in Astro.
