### ISSUE TITLE
how to import image in preact ?

### ISSUE THREAD

**Issue by vaynevayne** [withastro/astro#6898]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

    
not work

```jsx

 <img src={import("@assets/grassland_swiper.png")} alt="" />`


import grassland_swiper from "@assets/grassland_swiper.png"
import {vw} from "@utils/index"
import {useEffect, useRef} from "preact/compat"
 <img src={grassland_swiper} alt="" />
```
 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/124666577/233910752-23c2e9af-483c-4169-885c-ee2910c1f640.png">

### Link to Minimal Reproducible Example

no

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I noticed you also asked for support in Discord, which is the right place for questions like this. But here are some links that might help anyways:

https://docs.astro.build/en/guides/images/#using-img-with-the-image-integration

https://docs.astro.build/en/guides/assets/#update-existing-img-tags

If you have any follow up questions, please ask in the support thread on Discord. Thanks!
