### ISSUE TITLE
Certain Shiki themes unsupported by the Astro Code component 

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/astro#6899]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

The `<Code />` component does not seem to support all Shiki themes as documented. 

![CleanShot 2023-04-24 at 08 05 22](https://user-images.githubusercontent.com/10930234/233913761-955cfea3-bd91-4264-a0b3-c3875921214e.png)

![CleanShot 2023-04-24 at 08 07 35](https://user-images.githubusercontent.com/10930234/233913828-8e6059d5-9c8d-401a-8f61-26056c6fbbfd.png)

From the Shiki [theme list](https://github.com/shikijs/shiki/blob/main/docs/themes.md#all-themes),  the following themes aren't supported: 

-  'material-theme-darker'
  -  'material-theme-lighter'
  - 'material-theme-ocean'
  -  'material-theme-palenight'
  -  'material-theme'

Please see the reproduction link below

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rakqbl?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ohansemmanuel** [comment]
Took a look at the source, and seems the theme names are wrong. Perhaps this was updated on Shiki's end. See https://github.com/withastro/astro/blob/main/packages/astro/components/shiki-themes.js#L12

![CleanShot 2023-04-24 at 08 20 55](https://user-images.githubusercontent.com/10930234/233915127-db529251-c8b9-4553-a57f-26c3a37535d1.png)

**Comment by ohansemmanuel** [comment]
Shiki change: https://github.com/shikijs/shiki/commit/391713be6dec7b9484b06da0bc5bf27c33e5fee6

**Comment by ematipico** [comment]
Yeah, I tried to upgrade shiki some time ago, and there few breaking changes in the typescript types.
