### ISSUE TITLE
Errors not caught in imported components / streaming broken chunks

### ISSUE THREAD

**Issue by povilas-juodzevicius** [withastro/astro#6900]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Currently Astro doesn't handle errors that are thrown in imported components. The node adapter tries rendering the component, but throws out only an error: `net::ERR_INVALID_CHUNKED_ENCODING 200 (OK)`. So the server response is 200, though the runtime error is not caught. 

The problem seems to be in streaming chunks where one of them is broken. The node adapter's `asyncIterator` [function](https://github.com/withastro/astro/blob/main/packages/integrations/node/src/response-iterator.ts#L196) can be extended to catch these errors. It ends up in the `dist/server/entry.mjs`.

It would be best if we could either disable streaming or have some error catching in the adapter code so not to render a blank screen.  

### Link to Minimal Reproducible Example

https://github.com/povilas-juodzevicius/astro-runtime-error-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Yes, this is a problem with the Node adapter I believe.
