### ISSUE TITLE
Lit slotted selector when a lit component with hydration is used

### ISSUE THREAD

**Issue by RogierdeRuijter** [withastro/astro#6903]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

In Lit the slotted selector can be used to style incoming html elements. The slotted selector can only be used to style direct children in the slot. When a lit component is passed with a client directive to hydrate, an astro island is wrapped around the component. This creates a state where the slotted selector styled are not applied to the element passed. 
<img width="409" alt="Scherm­afbeelding 2023-04-24 om 16 08 04" src="https://user-images.githubusercontent.com/10298837/234021821-8cdcab32-dd4d-41f7-a834-14d5f910f7b8.png">
_This is an example of an astro island that makes the slotted selector unusable._

It is similar to the issue reported [here](https://github.com/withastro/astro/issues/5475) (which is now resolved) when using an astro-slot. 

The astro island feels like an essential architectural element to make the island architecture work, so it feels difficult to think of a way around it.

@astrojs/lit versie is: 2.0.1

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-mydd9h?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
It seems to work if I use `::slotted` (two colons), I think you were missing one. https://lit.dev/docs/components/styles/#slotted

**Comment by matthewp** [comment]
Ah ok, thanks @bluwy. Since this is a mistake, closing.
