### ISSUE TITLE
outDir config property create infinite loop of folders

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [withastro/astro#6904]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

nodejs, same with none

### What package manager are you using?

pnpm

### What operating system are you using?

Alpine (docker)

### What browser are you using?

Brave

### Describe the Bug

When you specify the outDir property in the astro config and try to run `pnpm run build` it fails and create an infinite loop of folder.
It is the case with and without specifying a trailing slash in the config.

The error returned : 
```sh
 error   ELOOP: too many symbolic links encountered, stat '/home/projects/withastro-astro-aiarqf/public/dist/core/views/dist/core/views/dist/core/views/dist/core/views/dist/core/views/dist/core/views/dist/core/views/dist/core/views/dist/core/views/dist/core/views/dist/core/views/dist/core/views/dist'
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-aiarqf?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
This happens because `outDir` is inside the `public` folder, which after build get copied to the `outDir` folder. This causes a recursive copy that leads to this error.
I think we could make more readable error messages to warn about this though

**Comment by natemoo-re** [comment]
If anyone would like to help out with this, we'd love a PR that checks if `outDir` is inside of `public` and throws an error if that's the case!
