### ISSUE TITLE
Script in JSX get stripped out

### ISSUE THREAD

**Issue by JetLi2K** [withastro/astro#6905]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

No

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

Work fine.
```
{
    <input id="name">
    <script>
    alert('Hello Astro!');
    </script>
}
```

Not fine. The whole script get stripped off, not found in the build too.
```
{
    <input id="name">
    <script>
    alert('Hello Astro!');
    const name = document.getElementById('name') as HTMLInputElement;
    </script>
}
```

It work fine when the client side script is place outside JSX scoped.
Perhaps, we need random testing on client side JavaScript for reliability testing.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qkjtay?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by AmarTrebinjac** [comment]
You've posted the same code twice, with an included getElementById in the second one

**Comment by bluwy** [comment]
I'm not sure what do you mean by stripping out. The issue seems to be that the `script` contains TypeScript, and Astro doesn't transpile it because it's dynamic, so I'm not sure if there's a way to fix this.

**Comment by MoustaphaDev** [comment]
Yeah that's just a limitation on the [compiler side](https://live-astro-compiler.vercel.app/?editor-state=WzMxLDEzOSw4LDAsNCw3Myw3NCwxMDAsMiwzLDY5LDE0NCw2NSwxMDcsMiw0OSwxNiwxMzMsMjU1LDIwMiw1MiwxNTEsNDAsMTg0LDE4NywxMTksMTcxLDY2LDkxLDEwLDEwLDI0Niw4NiwyNDAsMTQ2LDc1LDIxNiwyMDQsMTUwLDY0LDE0Niw5LDIwMSw3MiwxNywyNDEsMTkxLDE1NSwxNzIsNjUsMTE1LDIwMiwyMDQsMjUxLDIzMCwxODksMTAwLDE3NCw5OCwzNiwxMzEsOTgsNDUsMTg2LDE3NCw4MywxOTMsMjUwLDcyLDEzNywyMjUsMTY4LDQ3LDExNiwxMDIsMTUyLDE4LDEyMSwxNDQsMTI1LDYzLDE4NCwxODUsMjA2LDE5NSwxNjMsMjIzLDIzNSwyMDQsMTM3LDIyOCwyNTEsMTksMjU1LDIxMCwyMDEsMTg4LDIyNCwxNDUsNzQsNTUsOTYsNDAsMTI0LDIxLDk0LDI0NCwxNTYsMTYwLDE5NCwxNjYsMTg1LDE3OSwxMDEsMTM1LDkxLDM3LDc4LDIzMiwyMDIsOCwyLDE5LDEyNCw4NCwxODAsODcsOTgsMTY3LDE5NCw4NSw1LDQwLDEwMyw5OSw2Nyw0NCwxNzIsNTMsNSwxMiwyMTgsMjI3LDE3MiwyMDUsNjYsMzAsMTQ3LDE0MSwyMjAsNDIsMjM3LDQ4LDI0MSw2NiwyMzgsMjA5LDE4NSwyMzAsMjQyLDM4LDE1MSwzNywxOCwxMzQsMTYxLDE2OCwzNSwxMzMsMjA0LDgwLDE5OSw5NywxMSwxMzQsMTk4LDE3OSw0NywxNzUsMjM1LDI1NSwxNDQsMTkxLDI5LDIxNCwyMzUsMjMxLDIyOSw5NiwyMiwxNzgsMjM0LDExNCw5LDU4LDE5NSwyNTQsMjQ3LDIzMSwxMjAsMTY4LDE4NSw3NywxNzUsNzAsNTMsMTE0LDEyMCwxMDIsMjIyLDIwMiw1NSwyMTgsNTQsMTE4LDk4LDM3LDI1NCw0MSwxNTMsODMsMjEwLDQ5LDE2MiwxNywyMzUsNzMsMTg3LDE0MCw0MywyMjUsMzEsMTA3LDIyOSwxNjQsNjcsMTU4LDQwLDEyMSwxMTMsMTg3LDMsMjUxLDI1NSw2MiwxODAsMTA3LDEsMCwwXQ%3D%3D) I think it would be good to document that though, as people would expect script tags to always be optimized unless there is an attribute.

**Comment by JetLi2K** [comment]
@MoustaphaDev I see, in this use case for form submission to the same URL GET and POST, could have been working. But this could be accidentally run in production without knowing what happen.

**Comment by JetLi2K** [comment]
@bluwy `Astro doesn't transpile it`

You mean it doesn't transpile TypeScript inside JSX scoped?

**Comment by JetLi2K** [comment]
@AmarTrebinjac Yes, the 2nd code with the "additional code" in JSX scoped will cause Astro to strip out the entire <script> portion.

**Comment by matthewp** [comment]
Closing a there's a docs issue. We do not compile dynamic scripts (can't, actually).
