### ISSUE TITLE
Scripts from astro files are always inserted even when they shouldn't (bug in build script)

### ISSUE THREAD

**Issue by goldTpython** [withastro/astro#6906]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

When an astro file imports another **astro file that has a client-side script**, but the astro component **is not** inserted because of a falsy expression, the script is still inserted by the build process.
 
If the script contains DOM stuff like querySelector etc, it errors outs because obviously it shouldn't be there in the first place.
 
An example is pretty self-explanatory:
 
```astro
---
import SomeComponent from "../components/SomeComponent.astro";
 
const nullVar = null
---
{(nullVar) && <SomeComponent>foo</SomeComponent>}
```
 
If SomeComponent has this code:
 
```astro
---
---
<slot />
<script>
console.log('this shouldnt print on errorpage.astro')
</script>
```
 
The slot is not included (`foo` text is missing) but the script is ALWAYS included. No matter if the expression returned true or false.
 
The result is this:
 
```html
<meta name="generator" content="Astro v2.3.0">
<title>Astro</title>
<script type="module">console.log("this shouldnt print on errorpage.astro");
```
 
The reproduction example shows this happening with minimal code. (execute `npm run build` and check `dist/errorpage/index.html`)
 
NOTE: It ONLY happens when building static. On dev server it doesn't happen

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rxeqw7?file=src%2Fpages%2Findex.astro,dist%2Ferrorpage%2Findex.html&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
let me take a look

**Comment by lilnasy** [comment]
This is an architectural limitation. Astro could wait until every component is rendered before deciding which styles and scripts to send, but that would mean giving up on streaming. The way things are right now, Astro lets the browser download the required resources while the server is waiting on a CMS/DB request that decides which components will be used.

matthewp provides more context in a duplicate issue: #6563.

**Comment by leifmarcus** [comment]
@matthewp, I think, there should be a solution for this. As many project will have kind of module/component libraries they include but not use on every page. Isn’t there a way to deal with this problem?
