### ISSUE TITLE
how to calculate value in preact file on build time？

### ISSUE THREAD

**Issue by vaynevayne** [withastro/astro#6908]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

```jsx
const  vw =（px）=> 100/1920 *px +'vw'

// preact.jsx
import  {vw} from '../util'
import imgSrc from '../a.png'

const  ReactCard  = ()=>｛
return (<div style ={{
width ：vw(200)
height:imgSrc.height
}}></div>)
｝
```

i want  calcute vw(200) at build time instead of runtime ,  just like imgSrc.height  this value  is generate  in build time ，how to calculate in preact file on build time？

### Link to Minimal Reproducible Example

no

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
If you want to generate the markup at build-time, you could use your preact component within an Astro component without using [`client directives`](https://docs.astro.build/en/reference/directives-reference/#client-directives).

Using client directives other than the `client:only` one will do just that too.

**Comment by MoustaphaDev** [comment]
Also, reminder that GitHub issues are not the best place for support questions. You can go to [our discord server](astro.build/chat) and our amazing support community might be able to answer your future questions 🙂

**Comment by vaynevayne** [comment]
Judging from the current build results, vw is passed to the browser as a function and executed in the browser. What I hope is that the vw function executes vw during the construction phase, and then gives the value of return to preact. Is there any way to do that?

```jsx
// index.astro
 <RegisterButton client:load text={t("home.pre-register")} />

// @utils/index
export const vw = (px: number): string => {
  console.log("vw", px)
  return (100 / 1920) * px + "vw"
}

// RegisterButton.js
import {vw} from "@utils/index"

 <img
            src={gift.src}
            alt="预注册奖励"
            style={{
              width: vw(gift.width),
              height: vw(gift.height),
            }}
          ></img>

          <span
            class="text-gradient"
            data-text={numeral(registeredNumber).format("0,0")}
            style={{
              color: "transparent",
              position: "absolute",
              left: vw(700),
              top: vw(144),
              "z-index": 2,
              fontSize: vw(88),
            }}
          ></span>
```

after build
<img width="709" alt="image" src="https://user-images.githubusercontent.com/124666577/234451583-561f7057-b465-4288-8a1b-62017c1aa24c.png">
<img width="569" alt="image" src="https://user-images.githubusercontent.com/124666577/234451680-458fde02-30c5-4251-a5da-7fa0c5b7bc00.png">
<img width="533" alt="image" src="https://user-images.githubusercontent.com/124666577/234451852-2df498c2-89b4-4f0e-895a-7c7bc9f6d278.png">
<img width="742" alt="image" src="https://user-images.githubusercontent.com/124666577/234451911-9c3f4f3a-084a-4832-a830-76f8792cbe27.png">
