### ISSUE TITLE
my country not support discard ，can use github instead of discard？

### ISSUE THREAD

**Issue by vaynevayne** [withastro/astro#6909]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

safari

### Describe the Bug

search  resolve  way  in github  is easy on discard  and  our country not  support  discard 

### Link to Minimal Reproducible Example

no

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Ah, I didn't see this at first before answering in #6908.
Bear in mind that it might take time before getting answers for your questions here, as it's less spontaneous by nature.
Closing this as your question is in #6908.
