### ISSUE TITLE
`injectScript` cannot access `Astro`

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [withastro/astro#6913]
### What version of `astro` are you using?

last

### Are you using an SSR adapter? If so, which one?

doesn't matter

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

chrome & firefox

### Describe the Bug

The `injectScript` option cannot access the `Astro` global (https://docs.astro.build/en/reference/integrations-reference/#injectscript-option).

This limits what you can do. For example my library [astro-i18n](https://github.com/Alexandre-Fernandez/astro-i18n) cannot access the current route and because of this it forces every user to add `astroI18n.init(Astro)` at the start of every page when that could be done automatically with the `injectScript` option.

### Link to Minimal Reproducible Example

not needed

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Similarly that you can't access the `Astro` global in a `<script>` in an `.astro` file, you can't do it in `injectScript` too. If you think this should be supported, please open a discussion at https://github.com/withastro/roadmap. Thanks!
