### ISSUE TITLE
Markdoc Errors dont propagate into Astro Errors

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#6938]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

Nne

### What package manager are you using?

pnpm

### What operating system are you using?

Windowx

### What browser are you using?

Chrome

### Describe the Bug

I recently found out that Markdoc Errors are not displayed because of the Astro Markdoc implementation. I tried to talk to them about error messages but instead, I was told this.

Can you tell me how you are performing the validation? It seems like you are just seeing the error id, but Markdoc itself provides very explicit messages. For example, an invalid type shows the [message](https://github.com/markdoc/markdoc/blob/main/src/validator.ts#L209) "Attribute '${key}' must be type of '${t}" and an error on a matches rule shows the [message](https://github.com/markdoc/markdoc/blob/main/src/validator.ts#L223) "Attribute '${key}' must match one of ${matches}".
Ryan Paul Maintainer of Stripe

I think there is a way of transferring errors from one catcher to another. I think you decided to override the Markdoc errors with your own one.

### Link to Minimal Reproducible Example

https://github.com/louiss0/markdoc-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
We now show full validation error messages as part of #7045! A ci release is going out shortly. Let me know if the latest patch fixes this once it goes out.

**Comment by louiss0** [comment]
> We now show full validation error messages as part of #7045! A ci release is going out shortly. Let me know if the latest patch fixes this once it goes out.

I'll test things out today but please don't forget about #6936. If that issue is not fixed then Mardoc will barely be useable.

**Comment by louiss0** [comment]
This issue was solved for me I need to also remove another issue from your hands.  Please look at this [Markdocs Future](https://github.com/withastro/roadmap/discussions/554)
