### ISSUE TITLE
💡 RFC: Memoization helpers

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#694]
### Motivation

- Spun out from this RFC: 💡 RFC: Finalize component script scope/behavior #619
- The component script is scoped to each individual component
- This means that any code will run on every render
- Sometimes, expensive code should only be run once, and shared across all components. This is currently impossible today.

### Proposed Solution

```js
// Only runs once, cached and reused across all future instances
const result = Astro.defineOnce(async () => await fetch(...));
```

### Open Questions

- During dev, do we cache the value forever or just across a single page render?
- naming: this functions very similar to React's `useMemo()`, do we want to call this `Astro.useMemo()` instead?

**Comment by okikio** [comment]
I think a global state system would be useful. While testing I realized there was no way to create svg icons, and reuse them using the `<use href="#...">` tag, I think a means of storing state temporarily during build time would be useful.

**Comment by jasikpark** [comment]
This feels like something that would be very useful to solve in a general sense, I'd imagine doing something like `import data from "./expensive-memoized-function.js"` that allows for the memoization in both regular JS/TS & Astro.

**Comment by okikio** [comment]
> This feels like something that would be very useful to solve in a general sense, I'd imagine doing something like `import data from "./expensive-memoized-function.js"` that allows for the memoization in both regular JS/TS & Astro.

🤔🤔

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
