### ISSUE TITLE
Windows: create astro `command failed`

### ISSUE THREAD

**Issue by LadyBluenotes** [withastro/astro#6941]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm, pnpm

### What operating system are you using?

Windows 10

### What browser are you using?

n/a

### Describe the Bug

When running the command I get the following error:

```
npm ERR! code 1
npm ERR! path C:\Users\gerra\Documents\GitHub\docs-2.0
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-astro

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gerra\AppData\Local\npm-cache\_logs\2023-04-28T23_53_48_548Z-debug-0.log
```

### Link to Minimal Reproducible Example

n/a, local

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Need more info, we have numerous Windows users using Astro. I don't doubt that there might be some cases we are missing. If you have the time to dig deeper and figure out what exactly causes this problem we'd love to fix it. Otherwise there's nothing we can do with this given error message.
