### ISSUE TITLE
Yarn 3.5 doesn't work with dynamic routes

### ISSUE THREAD

**Issue by RodrigoTomeES** [withastro/astro#6942]
### What version of `astro` are you using?

2.3.2

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn@3.5.0

### What operating system are you using?

Windows 11

### What browser are you using?

Firefox Desktop 112.0.2 (64-bit)

### Describe the Bug

Hi,

After upgrade from npm to yarn 3.5.0 dynamic routes always thros this error.

```bash
$ yarn dev
   astro  v2.3.2 started in 130ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose


warn - You have enabled experimental features: optimizeUniversalDefaults
warn - Experimental features in Tailwind CSS are not covered by semver, may introduce breaking changes, and can change at any time.
 error   Unexpected "const"
  File:
    E:/Datos/Sites/Proyects/alienware-arena-marketplace/src/pages/[category]/[page].astro
  Code:
    44 | <Layout
    > 45 |   title={`${category}, page ${page.currentPage} of ${page.lastPage}.`}
         | ^
      46 |   description={`List of all items in the category ${category}, page ${page.currentPage} of ${page.lastPage}`}
      47 | >
      48 |   <Grid items={page.data} class="mb-4" />
```

You can reproduce it with the repo changing between this commits:
 - NPM: 47f037a0d5fcf53b58399d80dfc47a90a8626a76
 - YARN: d2579e57fbe800e532c49cfdf96e8aaa2bbf080c

Thanks

### Link to Minimal Reproducible Example

https://github.com/RodrigoTomeES/awa-db

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please provide a reduced example, thanks.
