### ISSUE TITLE
Astro.cookies.delete sets cookie to deleted/null instead of clearing cookie

### ISSUE THREAD

**Issue by btakita** [withastro/astro#6945]
### What version of `astro` are you using?

2.3.2

### Are you using an SSR adapter? If so, which one?

Vite/dev environment

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

Calling `Astro.cookies.delete('foobar')` does not clear the cookie in the header.

Clearing the cookie can be achieved by:

```js
headers.append('set-cookie', 'foobar=; path=/; Max-Age=0')
```

In the stackblitz example, calling `Astro.cookies.delete` sets the cookie to deleted. In a vite dev environment, `Astro.cookies.delete` sets the cookie to null. When `headers.append('set-cookie', 'foobar=; path=/; Max-Age=0')` is called, the cookie is entirely removed.

The issue with setting the cookie to null is that if there is are cookies on a page path & on the root path:

```js
headers.append('set-cookie', 'foobar=null; Max-Age=3600000; path=/companies')
headers.append('set-cookie', 'foobar=my-value; Max-Age=3600000; path=/')
```

The /companies cookie of null will be read by `Astro.cookies.get('foobar')`. Since `Astro.cookies.get` does not have a path option, getting the foobar cookie on the root path is not possible using `Astro.cookies.get` while on the /companies route.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You definitely seem to know more about cookies than me :) Would love a PR on this, the code and tests for Astro.cookies are straight forward.

**Comment by natemoo-re** [comment]
I wasn't able to reproduce this and couldn't find any place in our codebase where `Astro.cookies.delete` sets a cookie value to `null`. You can see our implementation of [the `delete()` method](https://github.com/withastro/astro/blob/2fea174303ca60f4765c6294d99ebc7a19e73403/packages/astro/src/core/cookies/cookies.ts#L73-L91) here.

This definitely sounds like a rough edge though. If @btakita can provide a repro or PR we'd be happy to take another look at this!

**Comment by Pedro-unixodbc** [comment]
@github-actions https://mantra-divine5.github.io/BBYlice4Mxqij2iaEDVxHoCDXsUvHwoy0pWfm1PpLIuPg1n/
