### ISSUE TITLE
Form with hidden bug

### ISSUE THREAD

**Issue by JetLi2K** [withastro/astro#6949]
### What version of `astro` are you using?

2.3.x

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

NPM

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

In this test.astro, the form containing one or multiple hidden inputs.
```
<form method="post">
    <input type="hidden" name="test1" value={value1}>
    <input type="hidden" name="test2" value={value1}>
    <input type="hidden" name="test3" value={value1}>
    <input type="hidden" name="test4" value={value1}>
    <input type="hidden" name="test5" value={value1}>
    <input type="hidden" name="test6" value={value1}>
</form>
```

Some time, you might found additional input that should have been deleted.
```
const valid = ['name'];
    try {
        let fd = await Astro.request.formData();
        for (const k of fd.keys()) {
            !valid.includes(k) && fd.delete(k);
        }
       console.log(fd)  // Check for form data before submit
    } ...

    
}
```

The terminal appear to delete only some but not all that is not part of the valid field I have specific.
```
Form FormData {
  [Symbol(state)]: [
    { name: 'test2', value: '' },
    { name: 'test4', value: '' },
    { name: 'test6', value: '' }
  ]
}
```

This could mean malicious code could inject into the form if devs have written improper SQL queries or endpoint with unintended parameters.

Included a problem code, installed node in Stackblitz.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qkjtay-gvvagr?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I think deleting inside of the iterator causes its internal index to be off so some are skipped.

This works:

```js
let keys = Array.from(fd.keys())
for (const k of keys) {
// ...
```
