### ISSUE TITLE
Cannot return JSX from function

### ISSUE THREAD

**Issue by VxMxPx** [withastro/astro#6955]
### What version of `astro` are you using?

2.3.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chromium

### Describe the Bug

Seems that returning JSX from function is not possible. Maybe the error could be more descriptive in cases developer try to do that, and documentation could be more clear on this topic.

Are there plans for this feature to be supported at some point?

_This is quite common feature, for anyone coming from React world._

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cvxuhq?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by cwilso03** [comment]
There is a workaround that, instead of JSX, uses JS strings and Astro's [`<Fragment>`](https://docs.astro.build/en/reference/astro-syntax/#fragments) component:

```astro
---
const myFuncReturningHTML = () => {
  const theUrl = 'https://example.com';
  // do whatever here...
 
  // return HTML string:
  return `
    <div>
      <a href='${theUrl}'>
        Click here
      </a>
    </div>
  `;
---
<div>
  Here is the dynamically generated link:
  <Fragment set:html={ myFuncReturningHTML() } />
</div
```

Generated HTML:
```html
<div>
  Here is the dynamically generated link:
  <div>
    <a href='https://example.com'>
      Click here
    </a>
  </div>
</div>
```
