### ISSUE TITLE
mdx not detected when file on sub directory

### ISSUE THREAD

**Issue by budiyono-dev** [withastro/astro#6963]
### What version of `astro` are you using?

2.2.2

### Are you using an SSR adapter? If so, which one?

stackblitz

### What package manager are you using?

npm

### What operating system are you using?

stackblitz

### What browser are you using?

chrome

### Describe the Bug

.md work fine in sub folder
mdx file not detected when i placed in subdirectory (blog/en/..), but work fine when i placed in blog

![image](https://user-images.githubusercontent.com/84400013/235680508-3999f45f-7ee0-4131-b358-a5f05a94fb49.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zqsmrp?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Please re-submit with a proper reproduction. It does not seem to include the relevant code.
