### ISSUE TITLE
Dynamic routes with multiple parameters and including dashes lead to error during static matching

### ISSUE THREAD

**Issue by davidsandoz** [withastro/astro#6968]
### What version of `astro` are you using?

2.3.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

With a dynamic routes setup with multiple parameters, if a parameter includes a dash, we get the following error during build:

```
A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/example-hell-no-world2`.
Hint:
    Possible dynamic routes being matched: src/pages/example-[foo]-[bar].astro.
```

In frontmatter of `example-[foo]-[bar].astro`:
```javascript
export function getStaticPaths() {
  return [
    {params: {foo: 'hello', bar: 'world'}},
    {params: {foo: 'hell-no', bar: 'world2'}}
  ];
}
```

This example comes from the minimal reproducible example linked below.

_(This was initially brought up in [this Discord thread](https://discord.com/channels/830184174198718474/1037826287814844427/1037826287814844427))_

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-z71beg?file=src/pages/example-[foo]-[bar].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JerryWu1234** [comment]
let me looking

**Comment by natemoo-re** [comment]
Confirming that this was fixed in https://github.com/withastro/astro/pull/7694 and should be available when upgrading to the latest version of Astro! Updating your linked reproduction seems to work.

**Comment by davidsandoz** [comment]
Awesome, thank you!
