### ISSUE TITLE
React cannot use externally imported functions

### ISSUE THREAD

**Issue by recallwei** [withastro/astro#6972]
### What version of `astro` are you using?

2.3.3

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Error Msg
![image](https://user-images.githubusercontent.com/62941121/235736529-8ffd7f67-aa53-4c2a-9cc5-49d663a210bf.png)

![image](https://user-images.githubusercontent.com/62941121/235736663-7755f416-00ed-4335-b2e6-9fb26fc419a0.png)

In the client-side React component, the outer function `navigateTo` does not work. Modified to comment worked.

### Link to Minimal Reproducible Example

https://github.com/recallwei/recallwei/blob/main/src/components/Motto/index.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I'm not what bug you are reporting here. Not all code works in the browser. Code using `process` will not. I would suggest using a package that is intended for use in the browser.

**Comment by recallwei** [comment]
@matthewp I found the problem, I created a `utils` directory to store public functions, and re-exported all methods in `utils/index.ts`, including methods that run on node. I can only solve the problem by isolating now, create a `utils/server.ts` to re-export all server-side methods
