### ISSUE TITLE
Getting an Unexpected "default" on build but not on dev

### ISSUE THREAD

**Issue by lschierer** [withastro/astro#6984]
### What version of `astro` are you using?

2.3.4

### Are you using an SSR adapter? If so, which one?

Yes, the aws adapter from SST, but verified with the node adapter as well

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

when I run the 
```
npm run build
```
script, I get the following error:
```
building client 
[astro:build] Transform failed with 1 error:
astro-entry:/home/projects/github-kes7ww/src/components/Lorem.astro:25:26: ERROR: Unexpected "default"
file: astro-entry:/home/projects/github-kes7ww/src/components/Lorem.astro:25:26

Unexpected "default"
23 |  Astro.self = $$Lorem;
24 |  
25 |  return $$render`export ${ default } from "/home/projects/github-kes7ww/src/components/Lorem.astro"`;
   |                            ^
26 |  }, 'astro-entry:/home/projects/github-kes7ww/src/components/Lorem.astro');
27 |  export default $$Lorem;

 error   Unexpected "default"
  File:
    astro-entry:/home/projects/github-kes7ww/src/components/Lorem.astro:25:26

~/projects/github-kes7ww 3s
```

Note this is copy/pasted from the reproduction in StackBlitz, but the error is identical in my actual repository except for the component name, the project file system path, and the package manager.  
```
npm run dev
```
works fine locally, but I want to be able to deploy and not just run locally.   

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kes7ww

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
That's because you have `<Lorem client:idle />` in `MarkdownPostLayout.astro`, as you can't hydrate an Astro component. I guess we could provide better errors though

**Comment by lschierer** [comment]
thanks for the help!
