### ISSUE TITLE
@astrojs/markdown-remark: pnpm package install has no dist directory

### ISSUE THREAD

**Issue by btakita** [withastro/astro#6992]
### What version of `astro` are you using?

2.3.2

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

I cloned the astro repo & ran `pnpm install`

The @astrojs/markdown-remark installation does not contain a `dist` directory & it's `package.json` contains:

https://github.com/withastro/astro/blob/main/packages/markdown/remark/package.json#L14-L18

![image](https://user-images.githubusercontent.com/3664/236276853-97a18c43-9595-477f-be7b-e3bedff34ae4.png)

![image](https://user-images.githubusercontent.com/3664/236277148-648492ee-13ee-4d07-8f82-93e77e7c2cd1.png)

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You need to run either `pnpm run dev` or `pnpm run build` to get a `dist` folder.
