### ISSUE TITLE
Middleware can affect css bundling?

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/astro#7007]
### What version of `astro` are you using?

2.4.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

It appears middleware can cause a bug with CSS bundling. When using middleware with the tailwind integration (or as I also found later with style tags in the page) there is a split second of no CSS in development, and in a production build no CSS is present.

As I write this, I've noticed than in the build, the CSS is present is the bundle, but isn't included in the head of the HTML source.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8rjwkk?on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
That is definitely unexpected. Is this just with Tailwind or have you noticed anything with component CSS?

If it's Tailwind, that happens via `injectScript` API. I still can't think of how the middleware change would effect this at the moment.

**Comment by TheOtterlord** [comment]
Normal style tags also fail. I've updated the stackblitz with an example

**Comment by ematipico** [comment]
For now, you can fix the issue by writing `return next()` instead. I will look at why just calling `next()` doesn't work.

**Comment by matthewp** [comment]
It's a requirement that a middleware returns either a `Response` or the return value of `next()` (which is a Response). Do we have a warning in place already about not returning anything from the middleware?

**Comment by ematipico** [comment]
We don't. I am going to add it and make sure that we handle this case. Eventually we should adhere to one single way to do things, I think.
