### ISSUE TITLE
String concatenation in JSX

### ISSUE THREAD

**Issue by thdoan** [withastro/astro#7016]
### What version of `astro` are you using?

2.3.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Hi, I don't know whether I've come up on the limitations of JSX or whether it's a real bug -- I cannot render an array of tags when string concatenation is involved. Let me demonstrate...

**This works, so so far so good:**
```
{
  entry.data.tags.length > 0
  ? entry.data.tags.map((tag: string) => <a rel="prefetch" href={`/tags/${tag}/`}>{tag}</a>)
  : ''
}
```
![image](https://user-images.githubusercontent.com/4110567/236605976-0f8683eb-ff2f-4f5f-a716-bb3efc829f07.png)

However, when I try to prepend the links with the text node "Tags: " and also separate the links with ", " things start to break down:

```
{
  entry.data.tags.length > 0
  ? 'Tags: ' + entry.data.tags.map((tag: string) => <a rel="prefetch" href={`/tags/${tag}/`}>{tag}</a>).join(', ')
  : ''
}
```
![image](https://user-images.githubusercontent.com/4110567/236606145-8fc58963-74f5-4db0-a309-d5345444d190.png)

I've also tried this:

```
{
  entry.data.tags.length > 0
  ? 'Tags: ' + entry.data.tags.map((tag: string) => `<a rel="prefetch" href="/tags/${tag}/">${tag}</a>`).join(', ')
  : ''
}
```
![image](https://user-images.githubusercontent.com/4110567/236606245-d8fb0aaa-2ddd-472d-b3dd-9306707a0261.png)

I thought this pattern might work, but it also failed:

```
{
  entry.data.tags.length > 0
  ? `Tags: ${entry.data.tags.map((tag: string) => <a rel="prefetch" href={`/tags/${tag}/`}>{tag}</a>).join(', ')}`
  : ''
}
```
![image](https://user-images.githubusercontent.com/4110567/236608502-6a79b0f0-fdef-44d5-bf0d-4f456de3e2a9.png)

Is this a current limitation of JSX, or is there a bug preventing us from doing string concatenation inside a JSX block?

The only solution I was able to find for this was using `set:html` which I would prefer _not_ to use unless it's a last resort:

```
<nav set:html={
  entry.data.tags.length > 0
  ? 'Tags: ' + entry.data.tags.map((tag: string) => `<a rel="prefetch" href="/tags/${tag}/">${tag}</a>`).join(', ')
  : ''
} />
```
![image](https://user-images.githubusercontent.com/4110567/236608730-c2af46ed-f528-4339-bfd7-af1198cc23b4.png)

To make development more predictable, I wish whatever we use inside `<nav set:html={ ... } />` would also work inside a standard JSX `<nav>{ ... }</nav>` block.

Note that the none of the code samples above produced errors in the VS Code console with Astro extension enabled, so I assume they are valid JSX code.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fttfkq?file=src/pages/blog/[...slug].astro

Click on Blog / Using MDX and scroll to the bottom to see the tags.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by johannesspohr** [comment]
The issue is that JSX tags are usually not transpiled to strings, but to objects that can also represent non-serializable data structures like event handlers etc. - but using `join` forces a string conversion, which yields the `[object Object]`.

You could however write a join function to join JSX elements:
```
function joinElements(elements, separator) {
  const joinedElements = [];

  for (let i = 0; i < elements.length; i++) {
    if (i > 0) {
      joinedElements.push(<>{separator}</>);
    }
    joinedElements.push(elements[i]);
  }

  return joinedElements;
}
```

**Comment by thdoan** [comment]
Thank you for the sample function. I also needed to concatenate "Tags: " at the start, so eventually I went with a solution based on this answer:

https://stackoverflow.com/a/40788571/452587

You can see it on the test site now (go to Blog / Using MDX to see tags)...

https://stackblitz.com/edit/github-fttfkq?file=src/pages/blog/%5B...slug%5D.astro

**TagList.astro**
```
---
const { tags = [] } = Astro.props;
---
<nav>
  Tags:
  {
    tags
      .map((tag) => <a href={`/tags/${tag}`}>{tag}</a>)
      .reduce((prev, curr) => [prev, ', ', curr])
  }
</nav>
```

**[...slug].astro**
```
{
  post.data.tags.length > 0
  ? <TagList tags={post.data.tags} />
  : ''
}
```
