### ISSUE TITLE
CSS files not routing correctly and TW not generated in `dist` build output

### ISSUE THREAD

**Issue by tommy-holmes** [withastro/astro#7021]
### What version of `astro` are you using?

2.4.2

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari, chrome

### Describe the Bug

I have installed Tailwind into my Astro project as described in the docs and all is well when I run on my dev server and build preview, [repo here](https://github.com/tommy-holmes/Athena-Site) However, when I build and go to the `index.html` of the build output (in the `dist` folder) none of my CSS works, neither Tailwind or Astro's scoped CSS (under `_astro`), [dist repo here](https://github.com/tommy-holmes/athena-test), with GH page [here](https://tommy-holmes.github.io/athena-test/). 

Please can anyone help, I have no idea why this would not be automatic as I would have thought Astro would handle all this in the build. I can't tell if I am missing a config AFAICT I have everything I would need. 

### Link to Minimal Reproducible Example

https://tommy-holmes.github.io/athena-test/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jamesli2021** [comment]
Did your config included "athena-test/"?

**Comment by bluwy** [comment]
Yeah it looks like the [base](https://docs.astro.build/en/reference/configuration-reference/#base) isn't set in the [astro config](https://github.com/tommy-holmes/Athena-Site/blob/main/app/astro.config.mjs)

**Comment by BlakeMScurr** [comment]
For posterity, this was my problem too because I misread the docs. I thought I shouldn't set the base parameter because my site was built from the root folder, but you're actually supposed to leave it unset if the site is *served* from the root folder.
