### ISSUE TITLE
Astro 2.4.2 requires `shamefully-hoist` when using pnpm, markdown pages, and assets

### ISSUE THREAD

**Issue by paulrudy** [withastro/astro#7022]
### What version of `astro` are you using?

2.4.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Safari, Chrome

### Describe the Bug

Very minor issue here involving pnpm and a particular node module, `eastasianwidth`, that vite complains about when markdown files and the experimental assets support are being used.

**Steps to reproduce:**

1. Set up basic install
2. Enable experimental assets support (no need to add assets)
3. Create markdown page and slot it into a base layout.
4. Update to Astro v 2.4.2 (if not yet updated)

**Result:** multiple errors like the one below. All the errors involve the same node module: `eastasianwidth`:

```
[vite] Error when evaluating SSR module /node_modules/.pnpm/eastasianwidth@0.2.0/node_modules/eastasianwidth/eastasianwidth.js:
|- ReferenceError: window is not defined
    at eval (/node_modules/.pnpm/eastasianwidth@0.2.0/node_modules/eastasianwidth/eastasianwidth.js:6:3)
    at instantiateModule (file:///Users/paul/astro-pnpm-error-test/node_modules/.pnpm/vite@4.3.5/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Even though the error mentions `evaluating SSR module`, the test case I'm linking to is not in SSR mode.

**Workaround/solution:**
1. Add an `.npmrc` file with `shamefully-hoist=true`
2. Delete `pnpm-lock.yaml` and `node_modules`
3. `pnpm i`

### Link to Minimal Reproducible Example

https://github.com/paulrudy/astro-2.4.2-pnpm-error-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jairusjoer** [comment]
Thanks for the solution. I've also been able to reproduce the described issue with the new 2.4.2 update.

**Comment by bluwy** [comment]
Looks like this is also causing our CI to fail currently.

**Comment by bluwy** [comment]
Seems to be caused by https://github.com/withastro/astro/pull/7009, which `astro:assets` imports `astro/dist/core/logger/core.js` -> `string-width` -> `eastasianwidth`
