### ISSUE TITLE
Build with netlify adapter fail

### ISSUE THREAD

**Issue by Ladvace** [withastro/astro#7024]
### What version of `astro` are you using?

2.4.2

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When I try building the project I get the following error:

```
 error  ENOENT: no such file or directory, rename '/Users/name/Documents/Gitrepos/astro-portfolio/.netlify/functions-internal/_astro/404.4dbde142.css' -> '/Users/name/Documents/Gitrepos/astro-portfolio/dist/_astro/404.4dbde142.css'
```

my Astro config:

```
import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import sitemap from "@astrojs/sitemap";
import solidJs from "@astrojs/solid-js";
import netlify from "@astrojs/netlify/functions";

// https://astro.build/config
export default defineConfig({
  integrations: [tailwind(), sitemap(), solidJs()],
  site: 'https://websitename.com',
  output: 'server',
  adapter: netlify(),
});


```

### Link to Minimal Reproducible Example

https://github.com/Ladvace/Astro-portfolio

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Ladvace** [comment]
this seems to happening only if there is the `404.astro` file, if I delete it, it built successfully

**Comment by matthewp** [comment]
Sorry for taking so long to get back. Can you resubmit with a minimal reproduction? I don't think all of those integrations are necessary to see this problem. Going to close since the issue is stale, but happy to accept a new one with a reproduction.
