### ISSUE TITLE
Error 500 using Astro.glob in hybrid mode with adapter-node

### ISSUE THREAD

**Issue by mef** [withastro/astro#7033]
### What version of `astro` are you using?

2.4.2

### Are you using an SSR adapter? If so, which one?

Node@5.1.2

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

`Adapter-node` and `npm run preview` crash whenever `Astro.glob('./**/*.astro')` is used and hybrid rendering is enabled.

### Use case

Building a site map, or dynamically generating a list of links to certain pages of the website.

### How to reproduce

(c.f. linked repo with a reproducible example)

* Create an SSR Astro app with adapter-node
* Have at least one SSR page and one SSG page (`export const prerender = true`)

### Expected behaviour

* No error occurs neither in dev mode, preview mode nor production.

### Expected behaviour

* No error occurs in dev mode
* `npm run preview` or `node dist/server/entry.mjs` crash with the following error message:

```
[ssr] TypeError: Cannot read properties of undefined (reading 'title')
    at file:///home/me/forks/astro/examples/minimal/dist/server/chunks/pages/all.992c83dc.mjs:17:26
    at Array.forEach (<anonymous>)
    at file:///home/me/forks/astro/examples/minimal/dist/server/chunks/pages/all.992c83dc.mjs:15:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async renderPage$1 (file:///home/me/forks/astro/examples/minimal/dist/server/chunks/astro.21412e4b.mjs:2928:30)
    at async renderPage (file:///home/me/forks/astro/examples/minimal/dist/server/chunks/astro.21412e4b.mjs:3596:18)
    at async NodeApp.#renderPage (file:///home/me/forks/astro/examples/minimal/dist/server/chunks/astro.21412e4b.mjs:4074:20)
    at async NodeApp.render (file:///home/me/forks/astro/examples/minimal/dist/server/chunks/astro.21412e4b.mjs:3995:22)
    at async file:///home/me/forks/astro/examples/minimal/dist/server/entry.mjs:2586:28
```

### Link to Minimal Reproducible Example

* [bug reproduction on github](https://github.com/mef/astro/tree/error-500-adapter-node-repro/examples/minimal) (based on `astro/examples/minimal`)
* [bug reproduction on stackblitz](https://stackblitz.com/edit/github-hasl5u?file=src/pages/index.astro)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by mef** [comment]
Update: a reproduction of the bug in stackblitz has been added, c.f. link in issue description. 

The code runs fine by default (dev), but fails when running `npm run build; npm run preview`

> �[0m�[2m22:41:30 �[22m�[1m�[31m[ssr]�[39m�[22m �[0m$$Index</<@file://file:///home/projects/github-hasl5u/dist/server/chunks/pages/all.7da6aed1.mjs:33:5
$$Index<@file://file:///home/projects/github-hasl5u/dist/server/chunks/pages/all.7da6aed1.mjs:31:15

**Comment by matthewp** [comment]
Thanks. Just a heads up that we will most likely not fix this given it requires both the use of Astro.glob and prerendering. Astro.glob is deprecated in favor of Content collections. If you're able to figure out the problem and send a PR we'd happily accept though. Thanks!

**Comment by natemoo-re** [comment]
I don't think that it will be possible to support this, unfortunately. `Astro.glob` is referencing modules that no longer exist, because the prerendered routes are only created to be pre-rendered, then they are destroyed.
