### ISSUE TITLE
HMR doesn't handle scss file changes with @use

### ISSUE THREAD

**Issue by RolginRoman** [withastro/astro#7035]
### What version of `astro` are you using?

v2.4.2

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

https://github.com/RolginRoman/astro-scss-changes-miss-hmr-repro

I'm using Sass with Astro. In serve mode scss changes don't reflect on pages with `@use` sass syntax.
Repro contains one `index` page and one style file in `styles` folder.
Seems like it works with `@import` syntax (I've found this issue https://github.com/withastro/astro/issues/3382 and `@import` got covered)

However, I'm not sure is it a bug or just misconfiguration cause no additional config was introduced from my side (https://docs.astro.build/en/guides/styling/)

### Link to Minimal Reproducible Example

https://github.com/RolginRoman/astro-scss-changes-miss-hmr-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I investigated this a bit. It's related to a small upstream issue (https://github.com/vitejs/vite/pull/13344), but even with that HMR for it still doesn't work, so leaving it open.

**Comment by natemoo-re** [comment]
Confirming that this is still an issue, even with the upstream issue merged!
