### ISSUE TITLE
Vitest doesn't work with Content Collection APIs

### ISSUE THREAD

**Issue by schietegal** [withastro/astro#7051]
### What version of `astro` are you using?

2.4.1

### Are you using an SSR adapter? If so, which one?

-

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

-

### Describe the Bug

Writing unit tests with vitest and trying to access the [Content Collection APIs](https://docs.astro.build/en/reference/api-reference/#content-collections) will result in an error.

`bholmesdev` already pointed out that [`getViteConfig`](https://github.com/withastro/astro/blob/latest/examples/with-vitest/vitest.config.ts) might help, but it doesn't.

Just run `npm run test`on the reproduction and look at the console.

Error:
```bash
Error: Content config failed to load.
  ❯ _0x46a642@https:/github3bgwtf-dgzh.w-corp.staticblitz.com/blitz.9c984a48.js:44:536697
  ❯ AstroError@file:/file:/home/projects/github-3bgwtf/node_modules/astro/dist/core/errors/errors.js:26:5
  ❯ getContentConfigFromGlobal@file:/file:/home/projects/github-3bgwtf/node_modules/astro/dist/content/vite-plugin-content-imports.js:208:11
  ❯ setContentEntryModuleCache@file:/file:/home/projects/github-3bgwtf/node_modules/astro/dist/content/vite-plugin-content-imports.js:144:33
  ❯ transform@file:/file:/home/projects/github-3bgwtf/node_modules/astro/dist/content/vite-plugin-content-imports.js:65:73
  ❯ transform@file:/file:/home/projects/github-3bgwtf/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42935:44
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3bgwtf

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mattwagl** [comment]
Hey Astro-Team 👋😀! Thanks for building this wonderful piece of software.

I am also experiencing this problem. While I was in the process of creating a bug report myself, this issue was opened. So I thought I'd add my reproducible example here.

**Are you using an SSR adapter? If so, which one?**
None

**What package manager are you using?**
npm

**What operating system are you using?**
Mac

**What browser are you using?**
Chrome

**Which Integrations are you using?**

```json
  "@astrojs/mdx": "0.19.1",
  "@astrojs/react": "2.1.3", // not included in the sandbox
  "@astrojs/rss": "2.4.1", // not included in the sandbox
  "@astrojs/tailwind": "3.1.2", // not included in the sandbox
 ```

**Link to Minimal Reproducible Example**
https://codesandbox.io/p/sandbox/empty-smoke-690kn0

**Logs**

<img width="600" alt="Screenshot-2023-05-10 at 14 14 38@2x" src="https://github.com/withastro/astro/assets/1268387/c8be5641-b0e0-4281-b315-f6effbc08551">


````js
FAIL  src/utils/getBlogPosts.test.ts [ src/utils/getBlogPosts.test.ts ]
Error: Content config failed to load.
 ❯ getContentConfigFromGlobal node_modules/astro/dist/content/vite-plugin-content-imports.js:191:11
 ❯ setContentEntryModuleCache node_modules/astro/dist/content/vite-plugin-content-imports.js:127:33
 ❯ TransformContext.transform node_modules/astro/dist/content/vite-plugin-content-imports.js:48:73
 ❯ Object.transform node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42883:44
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-934dbc7c.js:53349:29

````

---

I think it would be great to be able to write tests that load and filter Content Collections! If there is anything one can do to help solve the problem, let me know. 🙏

**Comment by chrskerr** [comment]
My understanding from a quick read of the code is that the collections depend on a running dev server which creates the types, reads in files from the content folders, etc. Without this running (probably in the same node instance) then there is no data available to test within vitest.

I'd be happy to be wrong about this, but it looks like it'd be pretty hard to make this data available without concurrently running up a dev server as step 1 of the test. 

Instead I'm going to look at manually reading the markdown files and pulling the front matter out of them that way, as an initial solution. Probably using `fs.readdir` it should be pretty simple to recursively find all the `.md` files and their full path names, and read them into memory one by one... will post if I find anything interesting :)

**Comment by chrskerr** [comment]
This is pretty raw & fragile, but it may be of some inspiration to anyone looking to do this properly. I'm just doing a small personal site, so hit my 80:20 point 😂


```ts
import { readdirSync, readFileSync } from "node:fs";
import matter from "gray-matter";

type Datum = {
  slug: string;
  data: {
    links: string;
  };
};

function recursivelyReadFiles(
  path: string,
  baseUrl: string
): { slug: string; content: string }[] {
  return readdirSync(baseUrl + path).flatMap(content => {
    if (content.endsWith(".md")) {
      return {
        slug: (path + "/" + content.replace(".md", "")).replace(/^\//, ""),
        content: readFileSync(baseUrl + path + "/" + content, "utf-8"),
      };
    } else {
      return recursivelyReadFiles(path + "/" + content, baseUrl);
    }
  });
}

function getAllCollections(path: string): Datum[] {
  const baseUrl = import.meta.url
    .replace("/__tests__/data.unit.test.ts", `/${path}`) 
    // my file is located within .../content/__tests__ and I only have the one so I hardcoded it
    .replace("file://", "");
  if (!baseUrl.endsWith(`/content/${path}`)) {
    throw new Error(`Invalid baseUrl ${baseUrl}`);
  }

  const allFiles = recursivelyReadFiles("", baseUrl);

  return allFiles.map(file => ({
    slug: file.slug,
    data: matter(file.content).data as Datum["data"],
  }));
}
```

**Comment by bholmesdev** [comment]
@chrskerr The type generator shouldn't need to run for APIs like `getCollection()` to run! This seems to be an issue with our config loader, which relies on spinning up a vite server where there _might_ not be one. Would have to test to be sure.

**Comment by mattwagl** [comment]
Finally found the time to try out the results of #7233 using the latest version of Astro. Testing data collections with Vitest now works flawlessly! 🎉

Many thanks to @bluwy and @bholmesdev for your work on astro and for listening to such suggestions!
