### ISSUE TITLE
Splashing Navigation Menu in portfolio template (example/portfolio)

### ISSUE THREAD

**Issue by krishna-santosh** [withastro/astro#7056]
### What version of `astro` are you using?

2.4.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

On mobile devices the expanded menu is visible by default for browsers that don't support JavaScript (or when the JavaScript is blocked), but is hidden for browsers that do support it. This is causing a brief **splash** effect when the page is initially loaded or refreshed, as the menu will be visible before JavaScript hides it.

![Screen_Recording_20230510-201437_Chrome (1)](https://github.com/withastro/astro/assets/75202541/7c544820-34d1-411f-b268-fb41e2c53371)

Also when JS is blocked the hero section's text is being hidden by overlapping menu, rendering it invisible.

![localhost_3000_(iPhone XR) (1)](https://github.com/withastro/astro/assets/75202541/654a253a-ab32-4caa-a05c-f2deea0ba5b9)

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/portfolio

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by imNel** [comment]
Hey! I've given this a go at #7078. Not sure if what I've done is good but better solutions/suggestions welcome as always :)

**Comment by krishna-santosh** [comment]
Hey @imNel, Thanks you for submitting the PR for my issue! I really appreciate your work on this.

There are two small issues though

1) When JS is disabled in desktop view

![image](https://github.com/withastro/astro/assets/75202541/8e2b966f-70be-4fd7-a1f9-cbe20ce59557)

2) Social Icons when JS is disabled in Mobile view (maybe some margin and gap would look good, what do you think?)

![localhost_3000_(iPhone XR)](https://github.com/withastro/astro/assets/75202541/a3fde192-3811-4903-9907-6d527a9a68ad)

**Comment by ArgR4N** [comment]
Hey! Is this issue just waiting to the pr to merge for being closed?

**Comment by krishna-santosh** [comment]
@ArgR4N https://github.com/withastro/astro/pull/7078#issuecomment-1640400552 
This is how it looks, I clone the repo and tested it.
