### ISSUE TITLE
`@astrojs/vercel/edge` not compatible with `imageService`

### ISSUE THREAD

**Issue by alexvuka1** [withastro/astro#7057]
### What version of `astro` are you using?

2.4.4

### Are you using an SSR adapter? If so, which one?

@astrojs/vercel/edge

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

Hi, I am trying to enable vercel's imageService, which is said to be supported on the edge in the `@astrojs/vercel` docs ([link](https://docs.astro.build/en/guides/integrations-guide/vercel/#imageservice)). To do that, I am required to enable `experimental: { assets: true }`, however by doing that I think that some node packages get imported into the build and that causes it to fail because of the edge runtime.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/verce-edge-image-service?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Looks like it's caused by https://github.com/withastro/astro/blob/a44e755cc666cfbcff22eb80872265cd4298e5e5/packages/astro/src/assets/internal.ts#L1-L2

**Comment by alexvuka1** [comment]
Is that necessary when using `@astrojs/vercel/edge imageService` and if not, could it be omitted? If it is, then is there no way to use `@astrojs/vercel/edge imageService`?
