### ISSUE TITLE
Comments are not enabled by Markdoc

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#7061]
### What version of `astro` are you using?

2.4.4

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Markdoc ignores comments by default.  I found this out when I was editing a post called third post. I forgot about it then remembered. I decided to test it out on a post called first post and found out that it's true. This behavior comes from `Markdoc`
[here](https://markdoc.dev/docs/syntax#comments). 

**Steps to reproduce**

 Remember the link will lead you to the page you need to see     

1. Wait for the server to load
2. Click on blog 
3. Click on first blog
4. Look at the first-post page and you'll see a comment.  

On your left you should see a comment on your right you should see an evaluated tag `Jul 8 2022` 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-fvk3qt?file=src/content/blog/first-post.mdoc

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by louiss0** [comment]
@bholmesdev I'm happy that Code comments are working but  This issue has not been solved.  What is going on? Here is the link to the repo again. https://stackblitz.com/edit/withastro-astro-fvk3qt?file=src%2Fcontent%2Fblog%2Ffirst-post.mdoc. All you have to do is go to the `first-post.mdoc` file then find it in the blog page then click on first-post. You'll see that the comment is not ignored by Markdoc

**Comment by louiss0** [comment]
> Ah, looks like this isn't available on the Markdoc config. Would an `allowComments` option on `markdoc.config.mjs` work?

It should be the default. **People should not have to decide whether comment's should be ignored**.

**Comment by bholmesdev** [comment]
@louiss0 Fair! Just noticed the note in the Markdoc docs (hehe doc doc) that this will be the default. Easy addition

**Comment by louiss0** [comment]
> @louiss0 Fair! Just noticed the note in the Markdoc docs (hehe doc doc) that this will be the default. Easy addition

I hope you can fix the `.mdoc` problem. I managed to get language support in Stackblits for `.mdoc` files but this will cause too many problems as layed out by This pull Request [here](https://github.com/withastro/astro/pull/6847)
