### ISSUE TITLE
Middleware does not work with API Endpoints

### ISSUE THREAD

**Issue by alex-sherwin** [withastro/astro#7070]
### What version of `astro` are you using?

2.4.4

### Are you using an SSR adapter? If so, which one?

NodeJS

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

If you have an API Endpoint which returns a `Response` with **ANY** non-null body, middleware is skipped entirely and prints warning:

> Middleware doesn't work for endpoints that return a simple body. The middleware will be disabled for this page.

This is caused by this line of code: https://github.com/withastro/astro/blob/a44e755cc666cfbcff22eb80872265cd4298e5e5/packages/astro/src/core/endpoint/index.ts#L113

I can't think of why there's a conditional block around whether to run middleware or not for API Endpoints, but I'm pretty confident that this is not the intended behavior.

Maybe this conditional was trying to naively determine if `response` was of the optional `EndpointOutput` object instead of a `Response`?  But that doesn't seem likely since in the code path which does call the middleware types the middleware generics to expect the union type of `Response | EndpointOutput`.

It feels to me like the conditional around running middleware for API Endpoints should probably be removed entirely and just always run if middleware is defined.

However, if there is some legitimate some reason why middleware *should* be skipped, I don't think it should be based on whether `Response.body` is set or not, I don't think middleware should care about this for any particular reason

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-avaykm-qoanvo?file=src/pages/api-notok.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Thank you for opening an issue! Yes, this is a valid bug and instead of checking against `null`, we should do this check

```js
if (response instanceof Response)
```

Since you're willing to open a PR, I am going to assign the issue to you! Thank you :) 
Let me know if you have further questions

**Comment by alex-sherwin** [comment]
Hi @ematipico 

I was in the process of putting together this PR and unit test coverage, and realized that I think maybe there's more broken about middleware + endpoint's than I first thought.

Making the simple change to `response instanceof Response` will make middleware run the way it's currently coded, however.. this doesn't really seem right.

Middleware in Astro, from what I can tell, is [properly] designed to be chainable in the sense that the middleware chooses when the actual requested route is executed by calling `next()` (allowing middleware wrap a request and run logic before and after the **actual** request is executed (e.g. endpoint or page))

However the current endpoint code does this:

```typescript
let response = await renderEndpoint(mod, context, env.ssr);
if (middleware && middleware.onRequest) {
	// .. run middleware
}
```

The obvious problem here is that `renderEndpoint` is always run directly here, and, before any middleware, instead of delegating the execution of it to the middleware.  This means that, as-is, middleware can't be used for important features like auth/session filtering before API code is executed.

I'll look at this a bit more to see if I can understand how the lazy evaluation of the actual endpoint/page is supposed to happen when middleware calls `next()`, but this might be above my paygrade inside this code base to fix

**Comment by ematipico** [comment]
That's a fair assessment, and I can see that this could be a problem inside standard endpoints that use `Response`. Maybe we should do a check inside the `sequence` function and the `callMiddleware` function. The downside is that we need to call the chain o middleware before telling the user that they can't use "simple" endpoints with the middleware.

**Comment by alex-sherwin** [comment]
@ematipico What is the underlying rationale for not allowing "simple" endpoints to be usable with middleware?

**Comment by alex-sherwin** [comment]
PR https://github.com/withastro/astro/pull/7079

**Comment by alex-sherwin** [comment]
@ematipico I think my solution in the PR is pretty decent, but the GitHub CI actions/tests won't run properly... check the PR for the failure info, but I'm not sure why it's failing on GitHub CI for that particular reason (I didn't change anything related to the `fs` import in util.ts), and they pass for me when run locally

If you have time to take a look I would appreciate it

**Comment by natemoo-re** [comment]
What's left from https://github.com/withastro/astro/pull/7106 to close this issue out, @ematipico?
