### ISSUE TITLE
Astro can't import from posthog-js/react package when used from React components

### ISSUE THREAD

**Issue by JLarky** [withastro/astro#7072]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

None, Vercel

### What package manager are you using?

npm, yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I was trying to use `posthog-js/react` in Astro, but noticed that I can't build my app anymore. During build no matter the way I would tyr to use the module it would crash with errors like these:

`error   Named export 'PostHogProvider' not found. The requested module 'posthog-js/react/dist/esm/index.js' is a CommonJS module, which may not support all module.exports as named exports.`

`error   Cannot use import statement outside a module`

I created this https://stackblitz.com/edit/github-xnztd8?file=src/pages/index.astro

As you can see you can actually import the module fine if you do it in a script tag. So I thought maybe I can use it with "client:only" but that also didn't work :) In that stackblitz I provide tons of different ways I tried to use it and they all failed to build. It does build in next.js.

```
// pages/_app.js
import { PostHogProvider } from "posthog-js/react";

const MyApp = ({ Component, pageProps }) => {
  return (
    <PostHogProvider>
      <Component {...pageProps} />
    </PostHogProvider>
  );
};

export default MyApp;
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xnztd8?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
As the Node.js error showed (and [publint](https://publint.dev/posthog-js@1.56.0)), the package isn't correctly bundled to be loaded by Node.js, which is what happens when you're using the component without `client:only` as the code needs to be SSR-ed.

It would be best to track this issue upstream, so closing this here.

**Comment by onyoo** [comment]
This seems to be working for me atm:

astro.config.ts
```
  vite: {
    ssr: {
      noExternal: [
        "posthog-js",
        "posthog-js/react",
      ],
    },
  },
```
