### ISSUE TITLE
💡 RFC: "redirect from" support

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#708]
### Background & Motivation

Consider the use-case:
1. I have a site with page "/api-reference" for forever
2. I move "/api-reference" to "/references/api"
3. all old links to "/api-reference" are now dead

In an ideal world, you would add a redirect at the host layer to do this. However, it's also possible to do a redirect as a page, in a way that Google will still respect for SEO. It's not as fast as the server redirect, but it works!

```
<meta http-equiv="refresh" content="time; URL=new_url" />
```

From: https://www.bitdegree.org/learn/html-redirect#what-is-an-html-redirect

### Proposed Solution

Add some user-facing API to support this. It could be either a mapping of old URL redirect in `astro.config.js`, or something in your page:

```jsx
---
// Example: /pages/references/api.astro (Astro component)
export const redirectFrom = [
  '/api-reference'
];
---
<html>
...
```

```markdown
---
# Example: /pages/references/api.md (Markdown)
redirectFrom:
    - '/api-reference'
---
# My page
```

- This would create a dummy page at that URL, that only includes the `<meta>`  tag outlined above.
- In the future, if we ever have a hosted/server element, we can implement this with a real `Redirect` response code without a breaking change for the user.

**Comment by matthewp** [comment]
I like the config based approach personally. If you're doing it in the page itself you might as well just add the meta tag instead.

**Comment by JuanM04** [comment]
Something like what [next.js does](https://nextjs.org/docs/api-reference/next.config.js/redirects) seems ideal

**Comment by jasikpark** [comment]
I do think I like the config redirect better, but for prior art there's the `alias` markdown frontmatter key in Hugo that allows you to invoke this behavior of an html-level redirect.

**Comment by drwpow** [comment]
I might be lame but I kinda just like the idea of writing the `<meta>` redirect tags yourself in Astro pages 🤷🏻. And with the new file-based routing you could even generate these tags for your entire blog in one `.astro` file!

I understand that this utility is useful if you’re constantly renaming things, but I also think there aren’t many people that care deeply about SEO and are constantly renaming files on their site.

**Comment by FredKSchott** [comment]
Ooohhhh interesting... you're saying have a single catch-all `src/pages/[...redirect].astro` route? That's really clever!

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
