### ISSUE TITLE
@astrojs/sitemap 1.3.1 adds endpoints with trailing slash

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#7080]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Edge

### Describe the Bug

Starting with astrojs/sitemap 1.3.0, endpoints like `rss.xml` are included in `sitemap-0.xml`.
Should sitemap include endpoints (data, images, rss etc.) at all?

If so, the trailing slash needs to be trimmed as the URLs are invalid.
`<url><loc>https://example.com/rss.xml/</loc></url>`

Repro: Run build in stackblitz sample and inspect `sitemap-0.xml`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xfdxg4

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fflaten** [comment]
Bonus: it doesn't add dynamic endpoints, only static. Still in 1.3.3
Ex.
- `rss.xml.ts` -> included as `rss.xml`. Ok, but users really have to filter it?
- `social.png.ts` -> included as `social.png`. Ok, but should it be there?
- `[...slug].png.ts` -> missing. Good imo, but still inconsistent with above

**Comment by Oceaneyes123** [comment]
Hey, there's now a way to configure this not to include the trailing slash. You can configure your ```astro.config.mjs```:

```
import { defineConfig } from 'astro/config'

export default defineConfig({
    trailingSlash: 'never'
})
```

For more information: https://docs.astro.build/en/reference/configuration-reference/#trailingslash

**Comment by fflaten** [comment]
Unfortunately that's not the answer. `trailingSlash` is an meant to match the dev-server's behavior to match your production host to catch errors in links etc. It does affect the URL style used in sitemap, but it's all-or-nothing and trailing slash is always wrong for file-endpoints like `rss.xml`.

In my case I'd have to use `trailingSlash: 'always'` to match my host's behavior while using `build.format = 'directory'`, but the sitemap will then also generate `../rss.xml/` (this issue). A request to that URL will look for `.../rss.xml/index.html` instead of the `.../rss.xml` file and return 404.

**Comment by natemoo-re** [comment]
Hey sorry it's taken us a while to get to this one! I'm working on this now.
