### ISSUE TITLE
Astro themes return 404 when running npm run preview

### ISSUE THREAD

**Issue by braincomb** [withastro/astro#7083]
### What version of `astro` are you using?

2.3.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

WSL2

### What browser are you using?

Firefox

### Describe the Bug

Themes built by Astro (example: https://github.com/withastro/astro/tree/main/examples/minimal) returns "404 Not Found" when running `npm run preview`.

This can be reproduced in Stackblitz as well:
https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I can't reproduce this. I'm guessing you didn't run `npm run build` before `npm run preview`?
