### ISSUE TITLE
Sitemaps include filtered pages and drafts

### ISSUE THREAD

**Issue by neulandherzer-dev** [withastro/astro#7087]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

any

### Describe the Bug

The filter does not work. Filtered pages are included in the sitemap!

Also, draft pages are included in the sitemap.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-sitemap-bug-fxfr?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by timozander** [comment]
Caused by https://github.com/withastro/astro/commit/1b90a7a5d5f16e3e1fa0329b509c6c6e76248181
The filtering is only applied to `pages` and not to `routes`.

Should be resolved by moving https://github.com/withastro/astro/blob/main/packages/integrations/sitemap/src/index.ts#L129 to line 119
