### ISSUE TITLE
Typescript Deprecation Error

### ISSUE THREAD

**Issue by Nightvision53** [withastro/astro#7100]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows Subsystem For Linux (Linux)

### What browser are you using?

Chrome

### Describe the Bug

Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.ts

This issue appears in Vscode while using latest version of Typescript.

![image](https://github.com/withastro/astro/assets/62076627/f1336942-327b-4643-8135-1be16bcb9d86)

### Link to Minimal Reproducible Example

I'm unable to reproduce the bug because its an editor issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Newer versions of Astro includes `ignoreDeprecations`, please upgrade, or manually add it to your `tsconfig.json`. We can't move to `verbatimModuleSyntax` at the moment, unfortunately due to breaking changes.
