### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by ghost** [withastro/astro#7115]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

To make Kysely database query works with Astro in production build.

When this `npm run dev` work but failed with `npm run build`? Kind of inconsistency DX, only to find it doesn't work later. How do 

Code example can be found in
https://kysely-org.github.io/kysely/#minimal-example
```
 Named export 'Pool' not found. The requested module 'pg' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'pg';
  const { Pool } = pkg;
  
import { Pool } from 'pg';
         ^^^^
SyntaxError: Named export 'Pool' not found. The requested module 'pg' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'pg';
const { Pool } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qdd7jz?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I am not sure if Astro can do something here, it seems to be an issue of the `pg` module

**Comment by bluwy** [comment]
Yeah unfortunately there's not something Astro can do here. In dev, which is powered by Vite, for HMR to work it'll convert `import { Pool } from 'pg'` to something like `const _pg = await import('pg'); const { Pool } = _pg;`, so it works there.

This issue isn't easily detectable because Node.js is trying its best effort to use `import` on a CJS file. Ideally if `pg` exports ESM code, it would also fix the issue, but that's a bigger feat. To workaround the issue for now, you should import the `pg` package as shown by the error message.

Closing this for now.

**Comment by RobbieTheWagner** [comment]
> Yeah unfortunately there's not something Astro can do here. In dev, which is powered by Vite, for HMR to work it'll convert `import { Pool } from 'pg'` to something like `const _pg = await import('pg'); const { Pool } = _pg;`, so it works there.
> 
> This issue isn't easily detectable because Node.js is trying its best effort to use `import` on a CJS file. Ideally if `pg` exports ESM code, it would also fix the issue, but that's a bigger feat. To workaround the issue for now, you should import the `pg` package as shown by the error message.
> 
> Closing this for now.

The problem with the suggestion is that it will break running in dev mode then. This feels like something Astro should be able to work around. Also, if it's going to fail the real build, it should fail dev too. It's frustrating to think everything is fine, then deploy and it blows up.

**Comment by bluwy** [comment]
> The problem with the suggestion is that it will break running in dev mode then. This feels like something Astro should be able to work around.

Can you open a new issue and provide a repro for that? I tested it with this issue's repro and it works.

> Also, if it's going to fail the real build, it should fail dev too. It's frustrating to think everything is fine, then deploy and it blows up.

Yes I'm planning to fix this in Vite 5 soon.
