### ISSUE TITLE
Astro's SSR build fails on Node adapter when using Ubuntu 20.04

### ISSUE THREAD

**Issue by IgStefano** [withastro/astro#7120]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Not relevant

### Describe the Bug

Hello, all. I am not sure why, but on SSR using Node as an adapter, the build on my Astro project is failing with the following message:

```
[commonjs--resolver] Failed to resolve entry for package "fs". The package may have incorrect main/module/exports specified in its package.json.
error   Failed to resolve entry for package "fs". The package may have incorrect main/module/exports specified in its package.json.
```
I created a minimal project (with a clone linked in Stackblitz) to test it out. It is an empty template with only `npx astro add node` ran with all y's. It crashes on build and gives me the same error as above, so I don't think it has anything to do with my dependencies. I also tried following [this troubleshooting guide in the docs](https://docs.astro.build/en/guides/integrations-guide/node/#syntaxerror-named-export-compile-not-found), didn't work.

If I comment out `output: "server"`, the build runs. I also got it to work alright using Deno as an adapter later on. So this leads me to believe that there's a problem with Node and Ubuntu.

However, on Stackblitz, it works perfectly. As I talked with a member of the community on [Discord](https://discord.com/channels/830184174198718474/1108374310416027648), it might be a platform issue. Don't know how useful the info is, but, in my machine I am running Ubuntu 20.04 and Node 18.16.0. Does anyone have any ideas on what might be happening? 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I wasn't able to recreate on Ubuntu 20.04. If you could, please provide a stackblitz example. I know you said it doesn't fail in Stackblitz, but even providing one helps a lot.

My guess is that there is a configuration issue with one of your dependencies. Some times these things don't show up until production. I would guess that you have a dep that needs `fs` but is be configured as `noExternal` some how. 

Closing because of the inability to recreate.
