### ISSUE TITLE
I can't define custom slug for a content

### ISSUE THREAD

**Issue by margani** [withastro/astro#7121]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Edge

### Describe the Bug

`astro build` complains about setting a slug for a content as said in [here](https://docs.astro.build/en/guides/content-collections/#defining-custom-slugs).

Steps to reproduce (you can find the prepared one in [here](https://stackblitz.com/edit/astro-custom-slugs)):
1. Initialise a project with `npm create astro@latest` with Typescript
2. Modify tsconfig.json as follows:
```json
{
  "extends": "astro/tsconfigs/base",
  "compilerOptions": {
    "strictNullChecks": true,
    "allowJs": true
  }
}
```
3. Create `src/content/posts/my-first-post.md` file with the following content:
```markdown
---
title: 'My First Blog Post'
slug: something/somewhere/my-first-post
---
This is my first post
```
4. Create `src/content/config.ts` file with the following content:
```ts
import { z, defineCollection } from 'astro:content'

export const collections = {
  posts: defineCollection({
    schema: z.object({
      title: z.string()
    })
  })
}
```
I didn't add `slug` field in this schema because `npm run build` shows an error:
`A content collection schema should not contain slug since it is reserved for slug generation. Remove this from your posts collection schema.`

5. Modify `pages/index.astro` with the following content:
```astro
---
import { getCollection } from "astro:content";
import Layout from '../layouts/Layout.astro';
const allPosts = (await getCollection("posts")) as any[];
---
<Layout title="Blog">
  <h1>Posts</h1>
  <ul>
    {
      allPosts.map((post: any) => (
        <li>
          <a href={`/${post.slug}`}>{post.data.title}</a>
        </li>
      ))
    }
  </ul>
</Layout>
```
6. Add `pages/[slug].astro` with the following content:
```astro
---
import { getCollection } from "astro:content";
import Layout from "../layouts/Layout.astro";

export async function getStaticPaths() {
  const posts = await getCollection("posts");
  return posts.map((post) => ({
    params: { slug: post.slug },
    props: { post },
  }));
}

const { post } = Astro.props;
const { Content } = await post.render();
---
<Layout title={post.data.title}>
  <h1>{post.data.title}</h1>
  <Content />
</Layout>
```
7. Now when you run `npm run build`, it will show the following error:

`Expected "slug" to match "[^\/#\?]+?", but got "something/somewhere/my-first-post"`

```
> npm run build


> astro-bug-repro-slug@0.0.1 build
> astro build

17:38:49 [content] Types generated 190ms
17:38:49 [build] output target: static
17:38:49 [build] Collecting build info...
17:38:49 [build] Completed in 202ms.
17:38:49 [build] Building static entrypoints...
17:38:50 [build] Completed in 608ms.

 generating static routes 
▶ src/pages/index.astro
  └─ /index.html (+7ms)
▶ src/pages/[slug].astro
 error   Expected "slug" to match "[^\/#\?]+?", but got "something/somewhere/my-first-post"
  File:
    /home/me/projects/astro-bug-repro-slug/node_modules/path-to-regexp/dist/index.js:229:27
  Code:
    228 |                 if (validate && !matches[i].test(segment)) {
    > 229 |                     throw new TypeError("Expected \"".concat(token.name, "\" to match \"").concat(token.pattern, "\", but got \"").concat(segment, "\""));
          |                           ^
      230 |                 }
      231 |                 path += token.prefix + segment + token.suffix;
      232 |                 continue;
  Stacktrace:
TypeError: Expected "slug" to match "[^\/#\?]+?", but got "something/somewhere/my-first-post"
    at Object.generate (/home/me/projects/astro-bug-repro-slug/node_modules/path-to-regexp/dist/index.js:229:27)
    at file:///home/me/projects/astro-bug-repro-slug/node_modules/astro/dist/core/build/generate.js:182:79
    at Array.map (<anonymous>)
    at getPathsForRoute (file:///home/me/projects/astro-bug-repro-slug/node_modules/astro/dist/core/build/generate.js:182:32)
    at async generatePage (file:///home/me/projects/astro-bug-repro-slug/node_modules/astro/dist/core/build/generate.js:143:17)
    at async generatePages (file:///home/me/projects/astro-bug-repro-slug/node_modules/astro/dist/core/build/generate.js:82:7)
    at async staticBuild (file:///home/me/projects/astro-bug-repro-slug/node_modules/astro/dist/core/build/static-build.js:79:7)
    at async AstroBuilder.build (file:///home/me/projects/astro-bug-repro-slug/node_modules/astro/dist/core/build/index.js:124:5)
    at async AstroBuilder.run (file:///home/me/projects/astro-bug-repro-slug/node_modules/astro/dist/core/build/index.js:156:7)
    at async build (file:///home/me/projects/astro-bug-repro-slug/node_modules/astro/dist/core/build/index.js:37:3)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-custom-slugs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by johannesspohr** [comment]
If I see that correctly it's because slashes are not supported in slugs - the RegExp indicated the letters that are not allowed here (/, # and ?).

**Comment by margani** [comment]
@johannesspohr Are you saying the guide [here](https://docs.astro.build/en/guides/content-collections/#defining-custom-slugs) should be changed to show an example of slug without slashes?

**Comment by Amin-Partovi** [comment]
@margani  If you want to create pages at dynamic levels, you can use rest parameters. In your case, you can change the name of your Astro file from [slug] to [...slug].

**Comment by ematipico** [comment]
@margani mind closing this PR and opening one in the documentation repo? Does that sound reasonable?

**Comment by bholmesdev** [comment]
@ematipico I also think we can greatly improve the build error message! I've seen that strange regex error many times in support. Overdue for an `AstroError`

**Comment by margani** [comment]
@ematipico sure, I will do that.
