### ISSUE TITLE
Parallel rendering does not respect arrays

### ISSUE THREAD

**Issue by smnbbrv** [withastro/astro#7127]
### What version of `astro` are you using?

2.5.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I tested the version 2.5.0 with parallel component rendering with the setup where I have originally discovered the parallel rendering issue and it does not seem to be fully fixed yet. It does not work properly with `array.map` async fragments.

Here is the rendering diagram:

<img width="1922" alt="image" src="https://github.com/withastro/astro/assets/13453858/8ee3b20b-f15d-42f8-a99f-872a2e571143">

I could easily reproduce this in a generic astro application.

```astro
// AsyncComponent.astro

---
export interface Props {
  delay: number;
}

const {delay} = Astro.props as Props;

await new Promise(resolve => setTimeout(resolve, delay));
---
<div>{delay}</div>
```

```astro
// index.astro

---
import Layout from '../layouts/Layout.astro';
import Card from '../components/Card.astro';
import AsyncComponent from '../components/AsyncComponent.astro';

const asyncComponentDelays = [500, 1000, 1000, 2000, 1000];
---

<Layout title="Welcome to Astro.">
	<main>
		<h1>Welcome to <span class="text-gradient">Astro</span></h1>
		<p class="instructions">
			To get started, open the directory <code>src/pages</code> in your project.<br />
			<strong>Code Challenge:</strong> Tweak the "Welcome to Astro" message above.
		</p>
		
		{asyncComponentDelays.map((delay) => <AsyncComponent delay={delay} />)}

// ...
```

The result is 5.5s rendering (expected 2s):

<img width="779" alt="image" src="https://github.com/withastro/astro/assets/13453858/ce1d5f6b-7ebe-4d0f-926f-5b774fa60480">

If I add the following components

```astro
// index.astro
// ...
		<AsyncComponent delay={1000} />
		<AsyncComponent delay={1000} />
		<AsyncComponent delay={1000} />

		{asyncComponentDelays.map((delay) => <AsyncComponent delay={delay} />)}
// ...
```

Then it results in 6.5s rendering time, which also should not be the case (should remain 5.5s, of course if 5.5s were the right time):

<img width="812" alt="image" src="https://github.com/withastro/astro/assets/13453858/08ad9661-2382-4499-b064-2a177b1233b7">

Is there something to work this around?

### Link to Minimal Reproducible Example

https://github.com/smnbbrv/astro-parallel-rendering-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
The code for this is here (i think): https://github.com/withastro/astro/blob/3257dd28901c785a6a661211b98c5ef2cb3b9aa4/packages/astro/src/runtime/server/render/any.ts#L19-L21 for anyone looking to work on it.
