### ISSUE TITLE
Vercel Edge adapter: "process.env.NODE_ENV" in markdown files breaks build

### ISSUE THREAD

**Issue by pilcrowOnPaper** [withastro/astro#7149]
### What version of `astro` are you using?

2.5.0

### Are you using an SSR adapter? If so, which one?

Vercel (Edge)

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

N/A

### Describe the Bug

Astros + Vercel Edge adapter fails to build when a markdown includes "process.env.NODE_ENV", but only if it's mid-string. It's specific to "process.env.NODE_ENV"; "process.env" or "process.env.ANY_OTHER_STRING" doesn't have any issues. No issues with the severless adapter as well.

#### Breaks:

```
// process.env.NODE_ENV
fn(process.env.NODE_ENV)
`process.env.NODE_ENV`
```

#### Doesn't break: 

```
process.env.NODE_ENV
process.env.FOO
```

### Link to Minimal Reproducible Example

https://github.com/pilcrowOnPaper/astro-markdown-edge

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by thiti-y** [comment]
I'm facing this issue.
