### ISSUE TITLE
Error when importing Image from astro:assets since 2.4

### ISSUE THREAD

**Issue by matt88120** [withastro/astro#7165]
### What version of `astro` are you using?

2.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When try to run dev / build, i've got this error :
`Cannot find module 'astro:assets' imported from ...`

Same code works great with astro 2.2 for example. 
Yes i'm using experimental in astro.config.js
`experimental: {
		assets: true,
	},`

### Link to Minimal Reproducible Example

https://zzmikgwkggithub-ldgi--3000--9c8944bc.local-credentialless.webcontainer.io

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your reproduction is the wrong link, it points to the preview instead of the editor.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! Unfortunately, without a proper reproduction, we're unable to help get this fixed. In an effort to keep all issues in this repository actionable, we've decided to close this issue for now.

If you're still having trouble and are able to provide a reproduction in the future, please let us know.
