### ISSUE TITLE
client:media doesn't work and create an error on build

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [withastro/astro#7168]
### What version of `astro` are you using?

2.5.1

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

manjaro linux

### What browser are you using?

chrome

### Describe the Bug

```
<Video FileName={'video0'} client:media="(min-width: 640px)" />
<Video FileName={'video1'} client:media="(max-width: 640px)" />
```

i get this error

[astro:build] Transform failed with 1 error:
astro-entry:src/components/miniComoponents/Video.astro:25:26: ERROR: Unexpected "default"
file: astro-entry:src/components/miniComoponents/Video.astro:25:26

Unexpected "default"
23 |  Astro.self = $$Video;
24 |  
25 |  return $$render`export ${ default } from "src/components/miniComoponents/Video.astro"`;
   |                            ^
26 |  }, 'astro-entry:src/components/miniComoponents/Video.astro');
27 |  export default $$Video;

 error   Unexpected "default"
  File:
    astro-entry:src/components/miniComoponents/Video.astro:25:26
❌ [build] Failed with exit status 1

### Link to Minimal Reproducible Example

ww.a.com

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
`client:*` directives doesn't work on Astro files, they only work on framework components as they can be rendered on the client.

**Comment by jojojojojoj5564656465465** [comment]
Do you mind to add it in the documentation

**Comment by bluwy** [comment]
We do document it at https://docs.astro.build/en/reference/directives-reference/#client-directives but not explicitly, perhaps you can open a PR to https://github.com/withastro/docs to update that part though.

On the core side, we had this issue before and the error message could definitely be better too to make it clear what's wrong.
