### ISSUE TITLE
@astrojs/markdoc v0.2.2: Markdoc tag rendering Astro component breaks when component uses getEntryBySlug()

### ISSUE THREAD

**Issue by paulrudy** [withastro/astro#7170]
### What version of `astro` are you using?

2.5.3

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Safari

### Describe the Bug

This is a very particular bug that showed up with @astrojs/markdoc v0.2.2 , when all of the following are true:

1. @astrojs/markdoc is v0.2.2
2. Pages are served from a content collection of _at least two_ .mdoc files.
3. `markdoc.config.mjs` imports an Astro component (for the purpose of defining a tag, although no tag actually needs to be defined—or used in any .mdoc file)
4. The Astro component uses `getEntryBySlug()` to access data from another content collection (the new `getEntry()` also produces the error)

The error looks like:
```
 error   Unexpected error while rendering pages → index.mdoc.
  File:
    /home/projects/github-pq3pgo/node_modules/astro/dist/content/runtime.js:186:33
  Code:
    185 |   renderEntryImport
    > 186 | }) {
          |                                 ^
      187 |   var _a, _b;
      188 |   const UnexpectedRenderError = new AstroError({
      189 |     ...AstroErrorData.UnknownContentCollectionError,
```

Pages render as expected after downgrading to v0.2.1, or when any of the other items above are false!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pq3pgo?file=markdoc.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by paulrudy** [comment]
@bholmesdev I hate to say it but unfortunately this issue has popped up again with v0.3.1. Should I create a new issue?

[Here's a fork](https://stackblitz.com/edit/github-pq3pgo-xieer6?file=package.json) of the original repro, but with updated astro 2.6.0 and @astrojs/markdoc 0.3.1

**Comment by bholmesdev** [comment]
Hey @paulrudy! That... hurts me deeply 😓 Is it present in 0.3.0 as well?

**Comment by bholmesdev** [comment]
No prob! Really appreciate it, just bummed the un-revert reintroduced this bug. I'll track that, thanks 👍
