### ISSUE TITLE
404 Response -> 404 page doesn’t work in dev server

### ISSUE THREAD

**Issue by arty-name** [withastro/astro#7179]
### What version of `astro` are you using?

2.5.4

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

The newly added feature [Render 404 page content for existing pages with 404 Response](https://github.com/withastro/astro/pull/7143) does not seem to work in dev mode, and only works in the built application.

You can see in the Stackblitz that the index page renders nothing when `astro dev` is running. If you stop it and run `astro build && astro preview`, only then the 404 page will be rendered for the index page returning status 404.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nszazr?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by paulrudy** [comment]
Just to add: In SSR mode, this also occurs when running `astro dev`, along with an added weirdness: after deploying (in my case to Vercel), navigating to a non-existent page `/foo` _downloads_ a file named `foo` (Safari on Mac).

**Comment by predaytor** [comment]
> 

experienced this too

**Comment by natemoo-re** [comment]
This was fixed in https://github.com/withastro/astro/pull/7693 and should be released soon.

**Comment by jdbruxelles** [comment]
I use astro v2.10.4 and my 404 page is served as a plain text in dev.
