### ISSUE TITLE
Open and close component different tags issue

### ISSUE THREAD

**Issue by proyb6** [withastro/astro#7183]
### What version of `astro` are you using?

2.5.x

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

I notice the tags are different and still work, they don't triggers any warning or errors in VS Code with Astro extension and it seems work fine? When both are different tags, it should be a bug?

```
<NewLayout>
    <p>This still work?</p>
</Layout>
```

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Our compiler, much like browsers, attempt to correct the HTML so it "always" work. It's part of the HTML spec: https://html.spec.whatwg.org/multipage/parsing.html#parsing

You can observe the same behaviour if you open a "invalid" HTML file in your browser and inspect the code using the dev tools: The browser magically correct the HTML.
