### ISSUE TITLE
Improve Cloudflare Integration in Hybrid Mode to Optimize Invocations

### ISSUE THREAD

**Issue by tonyaellie** [withastro/astro#7188]
### What version of `astro` are you using?

2.5.4

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

Currently, in the hybrid mode of our application, the Cloudflare integration utilizes an exclusion-based approach to determine which pages should be excluded from Cloudflare's function invocation. This means that by default, 404s will result in a function invocation, by switching to only including the opted in pages invocations will be decreased.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hb99m1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Related: https://github.com/withastro/astro/issues/6516

**Comment by natemoo-re** [comment]
I believe this was fixed in https://github.com/withastro/astro/pull/7846, but if that's not the case, please feel free to reopen!
