### ISSUE TITLE
Middleware redirect only works in dev mode (preview fails) for pre-rendered pages

### ISSUE THREAD

**Issue by gustafj** [withastro/astro#7194]
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

All

### Describe the Bug

When setting `export const prerender = true;` in a page and also using redirects within the middleware the functionality of the middleware is ignored / static when in `astro preview` while being dynamic in `astro dev`.

In the example the behaviour is different:
* In `astro dev` Astro redirects to `/` when visiting `/redirect` as expected
* In `astro preview` Astro does not redirect but instead shows the "redirect" page.

I would expect the middleware to be left out of the pre-rendering at build time and only applied during runtime. At the very least the `dev` mode and `preview` mode should behave identically.

_I can help fixing this but I would need guidance on where this functionality is located within Astro_

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bp83al?file=src%2Fmiddleware%2Findex.js,src%2Fpages%2Fredirect.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
That's an interesting case. I am not even sure if we would able to fix the case. 

@matthewp what do you think?

**Comment by matthewp** [comment]
Redirects currently do not work in SSG mode (or on a prerendered page). With this change: https://github.com/withastro/astro/pull/7067 I would expect it to work, however. I will add a test case for middleware.

**Comment by natemoo-re** [comment]
Can confirm that this issue has been fixed in Astro `2.6.x` via #7067!

[See reproduction](https://stackblitz.com/edit/github-bp83al-zhsrup).

**Comment by eitelkrauss** [comment]
I'm currently having this exact issue in Astro 4.0.3

**Comment by ematipico** [comment]
> I'm currently having this exact issue in Astro 4.0.3

Please open a new issue
