### ISSUE TITLE
Built code has no access to the run-time environment variables

### ISSUE THREAD

**Issue by arty-name** [withastro/astro#7195]
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

I use environment variables in my code according to the documentation like this: `import.meta.env.TEST`. They work fine in the development mode: `TEST=Pass astro dev`. After I build the code with `astro build` and start the server as `TEST=Pass astro preview`, the running application has no access to the runtime variables. In the generated code, I see that `import.meta.env.TEST` has been replaced with `({}).TEST`. To reproduce, open the linked example, stop the development server in the console, run `turbo build && turbo preview` and reload the view.

What made debugging complicated was the presence of `.env` file (and the inability of Stackblitz to persist it). If the `.env` file exists when `astro build` is run, then `import.meta.env.TEST` is replaced with the value of this variable from the .env file. This makes the built code ignore the environment variables configured during run-time.

Yet another quirk appears when there is no `.env` file however the environment variable is provided at build time: `TEST=Nevermind astro build`. This results in the expected outcome: `import.meta.env.TEST` is replaced with `process.env.TEST` in the generated code. To reproduce, open the linked example, stop the development server in the console, run `turbo working-build && turbo preview` and reload the view.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uegcud?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
The variable needs to be present during the build. If it is present then it will be fetched at runtime. For example just do: `TEST=whatever astro build` and it will be taken from the ENV at runtime.

**Comment by arty-name** [comment]
@matthewp it will not be fetched at runtime, this is what my demo showcases

**Comment by AxelLoupias** [comment]
Hello, sorry for commenting here, but if I want the env variable to be public?
I have tried to do what you said but if I add the "PUBLIC_" it will keep the value that was as placeholder and not the one I add in runtime.

**Comment by arty-name** [comment]
The public variable can only be present in scripts, right?

The scripts are only generated during the build, and then are served as static files. Looks like the public variables can only be configured during build, and not during the runtime.

**Comment by nemanjam** [comment]
Is it possible to prevent inlineing env vars at build time and load it in runtime in static builds, similarly like you can with `NEXT_PUBLIC_` prefix in Next.js?

**Comment by arty-name** [comment]
[I’ve documented it here](https://docs.astro.build/en/guides/integrations-guide/node/#runtime-environment-variables)

**Comment by nemanjam** [comment]
Very interesting, thank you.

```bash
VARIABLE_1=placeholder astro build
```

I understood runtime env vars at build time must be set to `placeholder` magic word to prevent inlining. Can you confirm?
