### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by batuhanyilmazer** [withastro/astro#7201]
### What version of `astro` are you using?

9.5.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

MacOS

### What browser are you using?

Safari

### Describe the Bug

When I want to use a style from another .astro/.css/any file, compiled file gives "Not allowed to load local resource" on console. Live Preview is fine, error occurs in compiled file only

In Minimal Reproducible Example, all elements given font-family: "Times New Roman", even the preview is shown correctly, compiled version won't.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You need to use the preview server to view the built files. See https://stackoverflow.com/questions/39007243/cannot-open-local-file-chrome-not-allowed-to-load-local-resource

**Comment by batuhanyilmazer** [comment]
Thanks for your fast response. I have one problem more, I could not solve how we suppose to run preview on github pages. When I deploy, github pages uses index.html and error continues.
I use withastro gh action script.

**Comment by bluwy** [comment]
Following https://docs.astro.build/en/guides/deploy/github/ should help with deploying to GH pages.

**Comment by batuhanyilmazer** [comment]
My bad! Thank you for sparing time to help.
