### ISSUE TITLE
Astro fails with GTM

### ISSUE THREAD

**Issue by alec-c4** [withastro/astro#7202]
### What version of `astro` are you using?

2.5.1

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

all

### Describe the Bug

Hi!
I've added GTM code to my layout file 

```
    <!-- Google Tag Manager -->
    <script>
      (function (w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({ "gtm.start": new Date().getTime(), event: "gtm.js" });
        var f = d.getElementsByTagName(s)[0],
          j = d.createElement(s),
          dl = l != "dataLayer" ? "&l=" + l : "";
        j.async = true;
        j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl;
        f.parentNode.insertBefore(j, f);
      })(window, document, "script", "dataLayer", "GTM-111");
    </script>
    <!-- End Google Tag Manager -->
```

and got following errors

<img width="1649" alt="image" src="https://github.com/withastro/astro/assets/25312/596731f8-f0f4-4dde-ac7a-eafceb3fad4b">

but when I replace `<script>` with `<script type="text/partytown">` errors went away, but GTM doesn't work :(

### Link to Minimal Reproducible Example

impossible, because google site verification is required

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You should use `is:inline` as it's an inline script
