### ISSUE TITLE
URL to /404 cannot load?

### ISSUE THREAD

**Issue by proyb6** [withastro/astro#7207]
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

In `npm run dev` is working fine, but it's a blank page on `npm run build && npm run preview`?

http://localhost/404

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Hey @proyb6! Can you check if issue #7301 is a duplicate? Happy to close and track there if so

**Comment by proyb6** [comment]
@bholmesdev Yes, closed here.
