### ISSUE TITLE
Spreading possibly undefined attributes on HTML element throws an Exception

### ISSUE THREAD

**Issue by Edo-San** [withastro/astro#7222]
### What version of `astro` are you using?

2.4.1

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Brave/Chrome

### Describe the Bug

Hi everyone 👋 

I created a [stripped-down example](https://stackblitz.com/edit/withastro-astro-stjnvx?file=src%2Fpages%2Findex.astro) of this issue I've been facing lately.

Basically, if I try to spread a possibly `undefined` object on an HTMLElement, Typescript does not complain since the object may also be defined (take a look at [this quick playground](https://www.typescriptlang.org/play?target=99#code/PTAEFEA8AcBsEsDG8AuoCuA7AJgUwGbya7YBQiA9pgM5oCGoAvBjgUSeVbaAEZOgBvAHQi6AX1KkQoALJ0Anr1ws8hYmUo00ifnJQALIQCc6OCgFsAFAEpQAHlAAGIQFZOW0Nn46A-IND6RgQAXKAARPgUFGFioKFYquwaXGjKzMIi2BLu1BSwuEKwFADmlgI8ADSguGLWkqQo8tDKAArw-ABKuJRG2Ha0RkTFVQNDAHwNTcoAiuj8AqAA2gDWuPKho5jFALobKINboGJAA) for reference), but at runtime, if the object is `undefined`, the [spreadAttribute](https://github.com/withastro/astro/blob/6c7df28ab34b756b8426443bf6976e24d4611a62/packages/astro/src/runtime/server/index.ts#L71) function throws an Error because `Object.entries` is called on `undefined`.

AFAIK this code would be valid in JSX, for instance, and Typescript does not complain about it, so I think that function should be able to handle `undefined` values as well, but I was wondering if the current implementation was indeed intended as it is or not 🤔 

If so, I'll close this issue, otherwise, I'd be more than happy to contribute!

Keep rocking! 🙌 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-stjnvx?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Makes sense to me! A simple `= {}` on this line should fix it:
https://github.com/withastro/astro/blob/af9ac3360be6e2426aa5eb93eeea5df73f5e727c/packages/astro/src/runtime/server/index.ts#L72

**Comment by Edo-San** [comment]
> Makes sense to me! A simple `= {}` on this line should fix it:
> 
> https://github.com/withastro/astro/blob/af9ac3360be6e2426aa5eb93eeea5df73f5e727c/packages/astro/src/runtime/server/index.ts#L72

TYVM @bluwy 
I was thinking about changing the function TS signature as well, but it wasn't necessary 😄 
I filed a PR here #7310
