### ISSUE TITLE
`img` MDX component override is not used in Astro collections

### ISSUE THREAD

**Issue by LexSwed** [withastro/astro#7223]
### What version of `astro` are you using?

the issue comes from `@astrojs/mdx@0.19+`

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When providing [custom components](https://docs.astro.build/en/guides/markdown-content/#assigning-custom-components-to-html-elements) for MDX file in content collections, `![alt](image.jpg)` will always be replaced by `astro:assets` `Image` component, hence not allowing to style it or customise the behaviour (for example, rendering the caption). The regression seems to come in some of [`@astrojs/mdx` updates](https://github.com/withastro/astro/pull/6824), reverting to `0.18` helps to mitigate the issue.

```js
export const components = {
  p: (props) => <p  {...props} class="custom-p" />
  img: (props) => <img {...props} class="custom-style" />
}
```

In `.mdx`:

```mdx
---
title: New post
---

export { components } from '../components';

![alt for image](assets/image.jpg)
```

`p` will be correctly picked up from `components`, but `img` will be ignored and `astro` image used instead.
Ideally, `![alt](image)` would be parsed as a local image, so `props` include `src`, `alt`, `width`, `height`, etc. So that they can be passed to `astro:assets/Image`

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/eager-pascal-b30gwz?file=%2Fsrc%2Fpages%2Findex.astro%3A14%2C1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by LexSwed** [comment]
Found a way to style it (jsx + Tailwind is only for example, can be Astro component with CSS)

```mdx
export const components = {
  p: (props) => <p class="[&:has(>img:only-child)]:mb-10 [&:has(>img:only-child)]:mt-6 [&>img]:mx-auto [&>img]:rounded-lg [&>img]:shadow-md" />
}
```

Obviously, this is suboptimal, and still doesn't allow for customised rendering (like captions)

**Comment by joe-bell** [comment]
Just ran into this trying to upgrade to `astro@3.0` — is it still possible to use the older version of `@astrojs/mdx` alongside Astro 3.0?
