### ISSUE TITLE
Writing content before the html element breakes the markup output

### ISSUE THREAD

**Issue by kireerik** [withastro/astro#7232]
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

See the title and the example.

&nbsp;
related workaround:
- https://github.com/withastro/roadmap/discussions/266#discussioncomment-6026957

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-z6jvzs-x36vyg?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Do you mean the `<html>` tag is gone when you add something before the `html` tag? Looks like it still renders fine, and the compiler is stripping it off ([compiler output](https://live-astro-compiler.vercel.app/?editor-state=WzMxLDEzOSw4LDAsMTIwLDE1MiwxMjUsMTAwLDIsMyw0NSwxNDIsNTksMTQsMTk0LDQ4LDE2LDY4LDE3NSwxNzgsMTA4LDE1Nyw0MCwxMjUsMTAwLDkyLDExNCw1LDE1NCw1MiwxOTgsMjIyLDM2LDIyLDI1NCw2OCwyMzUsMTgxLDM0LDEzMiwxODQsNTksMTQsMTY0LDI2LDE0MSwyNDQsMjMwLDEwNSwyMjIsMTA0LDE3OSwzNSwyOCw4MSwxNjgsMTM2LDE4NiwyNDQsMTI1LDEwMiwyMTYsOSwxMDgsMTc0LDE5MywxOTMsMjA2LDk0LDgsMjEyLDE0MSwyMDUsMTgsNDEsOSwyMCwxNDYsMTEzLDE0OSwyNCwxNzQsMTksNzgsNTYsMTA0LDQ4LDE2NSwxNzcsMzMsMjQ0LDE4OSw2MiwxNTAsNTQsMTk5LDEzMSwyNDIsMTA1LDEyOSw5Miw1LDEwMCwyNDUsNSwxMzAsNzksNCw3NiwxNjUsNiw0MSwyMjQsODMsMjQzLDUwLDE0NywyMSwxMzYsMTM0LDE1OSwxMTcsMTA3LDE5NSw0MSwxNjksMTk1LDE2OCwyMTMsNzQsMTk4LDEwNSw1MywyNTIsMjI3LDE0NSwyMjEsMTcxLDE0OSw1MSwxMjYsMCwxMTgsMTg0LDEwMywxMTgsMTE5LDU0LDIxOSw3MCwxNCwxOTksMjE3LDEzMiw2NiwyOSwxOTgsMjQzLDYxLDE1NSw4NCwyMzAsMjA0LDE3LDYzLDk1LDIwOCwyMDcsMjIwLDE3NywyMTAsMCwwLDBd))
