### ISSUE TITLE
special characters are becoming different in the output source code in `development` mode

### ISSUE THREAD

**Issue by kireerik** [withastro/astro#7234]
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

See the title and the example.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-z6jvzs-jfaa5i?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You need to set the `charset` of your page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#charset

**Comment by kireerik** [comment]
I do set it, but this issue exists regardless.

**Comment by kireerik** [comment]
I have a page part (Astro page) which is not visited directly because it is (lazy) loaded by a page (Astro page) on the client side (when to user scrolls close to that area). So this issue exists in the source code of the page (part) (Astro page) which is (lazy) loaded by the client.

**Comment by kireerik** [comment]
If I set it (in the page part (Astro page)) as you suggested that resolves the issue. However that page part has no `head` element. So this way the `HTML` output itself is not valid.

How should I set it properly?

**Comment by kireerik** [comment]
Also as I am checking now. This issue only happens in `development` mode. The source code of the final build output is correct. So this is definitely a bug which happens in `development` mode.

**Comment by kireerik** [comment]
This is the `build` output of the example:
```
<!DOCTYPE html>
example characters:
—
·
🃏
’
```

**Comment by kireerik** [comment]
But in `development` mode it is this:
```
<!DOCTYPE html>
<script src="/.localservice@runtime.272d3407.js"></script>example characters:
â
Âˇ
đ
â
```

**Comment by bluwy** [comment]
I'm not able to reproduce it:
<img width="840" alt="image" src="https://github.com/withastro/astro/assets/34116392/921a28e8-e7c8-4215-af46-ffcde8c84ec6">

**Comment by kireerik** [comment]
What environment do you use?

The issue is clearly happening (consistently (and reproducibly)) on the example (already added to this issue on creation):
- https://stackblitz.com/edit/github-z6jvzs-jfaa5i?file=src%2Fpages%2Findex.astro

**Comment by bluwy** [comment]
macos 13.4, Safari 16.5. Getting the same in Chrome. But I'm not sure if that matters here, Astro is serving the file as-is. You need `<meta charset="utf-8">` in your HTML file if it contains utf-8. Or the server needs to serve with that charset (usually it's more robust with the `meta` tag).

**Comment by kireerik** [comment]
But it works correctly in production mode regardless if the charset is set, but it does not work in development mode.

**Comment by bluwy** [comment]
It could be that your prod server serves HTML files with the [`charset=utf-8` `ContentType` header.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#syntax) Not all prod servers does that so we can't do that by default in dev too.

**Comment by kireerik** [comment]
I just manually check the output file (without any server) and that is correct.

**Comment by anttituomola** [comment]
Hello everyone,

I had this issue on an Astro project. The problem was not with file encoding (UTF-8), but with the lack of a charset declaration on a particular page.

My pages are usually wrapped with a Layout component that includes the head tags and charset declaration. However, one page was missing this layout wrapping.

After including the Layout component with the charset declaration on this page, the issue was resolved.

So, make sure all your pages have a charset declaration to handle special characters.

Hope this helps someone!

Happy coding!
