### ISSUE TITLE
different result in astro dev and astro build with sass

### ISSUE THREAD

**Issue by Qusic** [withastro/astro#7240]
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

linux

### What browser are you using?

chrome

### Describe the Bug

I am new to Astro and trying to set up a new project with picocss. However this global style in index.astro is not working properly.

```
<html>
  <body>
    <h1>Hello, World!</h1>
    <p><button data-tooltip='Tooltip'>Tooltip on a button</button></p>
  </body>
</html>
<style lang='scss' is:global>
  $primary-hue: 1;
  $grey-hue: 1;

  @import '@picocss/pico/scss/pico.fluid.classless';
</style>
```

I want to override the two hue variables defined [here](https://github.com/picocss/pico/blob/master/scss/themes/default/_colors.scss) to use a new set of colors.

when running with `astro dev`, the button is blue, which is not correct.
when running with `astro build` and then preview, the button is red and the variables overriding works.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-qwjrsq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Imports in style tags in Astro are intentionally treated as external. You can do what you want to do by moving this to a separate file and importing the sass instead.
