### ISSUE TITLE
Project built with node standalone adapter tied to `node_modules`

### ISSUE THREAD

**Issue by drocha87** [withastro/astro#7247]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Edge

### Describe the Bug

The process of building a node standalone project currently has a dependency on the specific machine used for building it. This is my `astro.config.mjs`

```js
 // https://astro.build/config
export default defineConfig({
  integrations: [tailwind()],
  output: "server",
  server: {
    host: "127.0.0.1",
    port: 3000,
  },
  adapter: node({
    mode: "standalone",
  }),
  vite: {
    esbuild: { minifyIdentifiers: false },
    ssr: { noExternal: ["jsonwebtoken"] },
  },
});
```

This limitation is not allowing me to run the built project on different machines. For example I have this error when trying to run it on another machine:

```txt
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'undici' imported from /home/user/dist/server/entry.mjs
```

**Update**: If I move the `node_modules` along with the `dist` it seems to fix the problem. 

To reproduce the problem just build the project and move the dist folder to outside of the project root and then try to run it.

### Link to Minimal Reproducible Example

https://github.com/drocha87/lonely-light

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by proyb6** [comment]
Closed. I assume this might be solve, without the need for node_module for deployment in the future Astro release, assume 3.0.

**Comment by bluwy** [comment]
This is intentional with the `node` integration. The typical flow when deploying a node app on a prod server is to copy the `dist/` and `package.json`, then run `npm install -P`, and you can start the prod server. If you'd like to bundle everything, you can set `vite.ssr.noExternal: true`.

**Comment by Whyjsee** [comment]
> This is intentional with the `node` integration. The typical flow when deploying a node app on a prod server is to copy the `dist/` and `package.json`, then run `npm install -P`, and you can start the prod server. If you'd like to bundle everything, you can set `vite.ssr.noExternal: true`.

thx bro ~! you saved me today !

**Comment by shelchin2023** [comment]
> > This is intentional with the `node` integration. The typical flow when deploying a node app on a prod server is to copy the `dist/` and `package.json`, then run `npm install -P`, and you can start the prod server. If you'd like to bundle everything, you can set `vite.ssr.noExternal: true`.
> 
> thx bro ~! you saved me today !

When I introduce react, the build product has a dependency on node_modules/react-dom. have you guys come across this?
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/342b11a8-9216-4a74-a9cf-8fc3ba3e50a3">

Reproducible： https://github.com/shelchin2023/test-astro-ssr
