### ISSUE TITLE
After adding tailwindcss project, start the project has been prompt can not find .temp.1685503781435.tailwind.config.cjs

### ISSUE THREAD

**Issue by quguoliang** [withastro/astro#7250]
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

vercel

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

11:29:34 [astro] Unable to load /Users/bytedance/Desktop/bytedance/personal-gpt/astro.config.mjs

 error   ENOENT: no such file or directory, unlink '/Users/bytedance/Desktop/bytedance/personal-gpt/.temp.1685503774949.tailwind.config.cjs'

### Link to Minimal Reproducible Example

no

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by proyb6** [comment]
How do you add tailwind? I have a macOS Ventura.

**Comment by bluwy** [comment]
We've recently refactored the tailwind integration which should fix this. Try `@astrojs/tailwind` v4.
