### ISSUE TITLE
Custom Fonts with @font-face are ignored

### ISSUE THREAD

**Issue by tisign** [withastro/astro#7251]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Firefox, Safari

### Describe the Bug

I have tried to add custom fonts to my project following the docs. However, the fonts are not loaded (no error in the console, no missing files).

I have the fonts in a folder under public/fonts/**.ttf and public/fonts/**.woff2

I tried all variations of paths and places to define the font-faces (main.scss, font.css, global style tag, local style tag)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cf68hv?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tisign** [comment]
After some investigation it seems to affect only (some?) ttf files.

**Comment by diakonovm** [comment]
Yeah, this was a huge headache, was not able to use ttf or otf file formats. I am using version 2.6.5, so the issue still persists.

**Comment by tisign** [comment]
For me it seems the conversion of my font files had an error. After cconerting them again, the fo ts got loaded correctly.
