### ISSUE TITLE
getImage() does not work for remote images

### ISSUE THREAD

**Issue by DCLangX** [withastro/astro#7252]
### What version of `astro` are you using?

2.5.6

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

I try to generate an optimized remote image by use getImage(),but it doesn't work,the image is still the original address😥
```
---
import { getImage, Image } from 'astro:assets'
const optimizedLogoImg = await getImage({
  src: 'https://avatars.githubusercontent.com/u/19513657?v=4',
  width: 500,
  height: 500,
  quality: 'low',
  format: 'jpg'
})
---

    <img src={optimizedLogoImg.src} alt="test" />
    <Image
      src={optimizedLogoImg.src}
      width="500"
      height="500"
      format="jpg"
      quality="low"
      alt="A description of my image."
    />
    <Image
      src="https://avatars.githubusercontent.com/u/19513657?v=4"
      width="500"
      height="500"
      format="jpg"
      quality="low"
      alt="A description of my image."
    />
```
![image](https://github.com/withastro/astro/assets/19513657/c52cf586-e21c-4dda-b805-a84542cb11b1)

### Link to Minimal Reproducible Example

https://github.com/DCLangX/test-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
> @Princesseuh this wasn't immediately apparent to me in the docs, either; I dug through the code to find a comment that made it clear remote images aren't optimized by either local image service.
> 
> Am I missing some obvious reason why I should _not_ submit a PR for adding remote image support?

We purposely left it out from a first version of `astro:assets` for multiple reasons:
- Wanted to keep the scope small for now (remote images support kinda has to go with other features such as remote patterns to avoid security issues)
- Wanted to push users towards self-hosting their images as much as possible, for performance reasons
- Wanted users to rely more on their chosen platforms of hosting for optimizing, several CMSes supports optimizing images directly nowadays.

If you're interested in pushing forward a proposal for this, feel free to create a thread over at https://github.com/withastro/roadmap

**Comment by AndreCox** [comment]
Hello,
I also ran into this problem as the documentation is very lacking in this area.
Is there any way of getting remote image optimization to work. Or any other options in the meantime?

**Comment by AndreCox** [comment]
> > Hello,
> > I also ran into this problem as the documentation is very lacking in this area.
> > Is there any way of getting remote image optimization to work. Or any other options in the meantime? 
> 
> The latest version supports remote images. Just make sure the domains are allowed in your config https://docs.astro.build/en/guides/assets/#allowed-domains-and-remote-patterns-for-remote-images

Thanks for the response, does this optimize the remote images because in my testing no optimization was done? I tried local images and those worked perfectly.

**Comment by Princesseuh** [comment]
> > > Hello,
> > > I also ran into this problem as the documentation is very lacking in this area.
> > > Is there any way of getting remote image optimization to work. Or any other options in the meantime? 
> > 
> > The latest version supports remote images. Just make sure the domains are allowed in your config https://docs.astro.build/en/guides/assets/#allowed-domains-and-remote-patterns-for-remote-images
> 
> Thanks for the response, does this optimize the remote images because in my testing no optimization was done? I tried local images and those worked perfectly.

Yes, remote images do get optimized with this.

**Comment by AndreCox** [comment]
Actually just updated to the latest version that was released a couple hours ago and it started working

**Comment by monaye** [comment]
seems like if I have a svg remote file, it doesn't create a local copy, jpg/png work fine. it this the case?
