### ISSUE TITLE
Script order execution is wrong

### ISSUE THREAD

**Issue by gkatsanos** [withastro/astro#7266]
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I would expect the order of execution to match the order of script declaration. As we see in the repro, it does not.

<img width="391" alt="image" src="https://github.com/withastro/astro/assets/1768834/fbad6ee2-c2d0-40df-bff6-86e15d036fa8">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-execution-order-wrong

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
`<script>` is bundled and treated as a module. So it's going to come last. See https://docs.astro.build/en/guides/client-side-scripts/ for how this works. You want to use `is:inline` to control ordering.

**Comment by gkatsanos** [comment]
@matthewp I tried changing it to is:inline, got the same order. The documentation is lacking a bit on examples and order execution. But feel free to modify the reproduction I posted above you will see the order is still not the one anticipated.

**Comment by gkatsanos** [comment]
My solution was a bit different ; I explicitely imported the module I want to use inside the <script> ... 

```js

<script>
  import { googleAnalytics } from "@helpers/tracking";

  googleAnalytics.trackPageView({
    virtualPageTitle: "connect_landingpage",
    trafficSource: "internal",
  });
</script>
```

**Comment by petegleeson** [comment]
Hey I love Astro. I found the ordering of scripts unintuitive as well.

My usecase is setting up analytics similar to @gkatsanos. I wanted to setup posthog in my shared Layout component. Then capture events in different page components. 

```Layout.astro
<!doctype html>
<html lang="en">
	<head>
               <!-- various meta tags -->
		<script>
			import posthog from 'posthog-js';
                         posthog.init();
		</script>
	</head>
	<body>
		<slot />
	</body>
</html>
```

```index.astro
<Layout title="Welcome to Astro.">
	<main>
		<script>
			import posthog from 'posthog-js';
			posthog.capture("user defined event");
		</script>
	</main>
</Layout>
```

This logs the error "[PostHog.js] You must initialize PostHog before calling posthog.capture".

I've put together a minimal example: https://stackblitz.com/edit/withastro-astro-rtylii?file=src%2Fpages%2Findex.astro

It's difficult to reason about the order of execution if that's decided by the bundler.

I can make this work with inline scripts and globals.

It would be cool if the execution order matched the order of components in the astro tree.

Thanks for the great work on Astro!
