### ISSUE TITLE
Processing images in CMYK colour space fails (stalls) without helpful feedback ("Unsupported color conversion request")

### ISSUE THREAD

**Issue by housser** [withastro/astro#7270]
### What version of `astro` are you using?

2.5.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

MacOS 13.3.1(a)

### What browser are you using?

Safari

### Describe the Bug

When trying to process an image that is in the CMYK colour space, the error message `Unsupported color conversion request` is printed to the console. This only occurs though when the image it rendered (in _dev_ that requires you to load the page that renders the image, or during the `astro build` process).

In my case I didn't notice this issue during development because I didn't browse to the specific catalog page that happened to have an image in CMYK colour space, so didn't notice until build time. During build, this error doesn't fail the build, but it does stop processing subsequent images.

Re-saving the image in RGB colour space seems to resolve the issue. I'm assuming this might be an issue with Squoosh, but there is an opportunity to add some defensive safeguards here for improved developer experience.

It would be helpful if the build process failed as a result of this error, as it was otherwise failing silently and allowing my builds to succeed with incomplete assets. I was able to diagnose by adding some trace outputs to `core/build/generate.js` so that I could determine the actual file it was trying to process (since the file name is not printed to the console until _after_ processing). It might also be helpful to have more output when using the `--verbose` flag, such as showing the file that Astro is _attempting_ to process, in case there is a subsequent failure that doesn't provide more helpful feedback.

In StackBlitz you might need to reload the preview window in order to see the error printed to the console.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qqjfe4?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Thank you for submitting this issue! I'm assuming this issue is specific to Squoosh, so switching to the Sharp image service may fix your issue in the meantime: https://docs.astro.build/en/guides/assets/#using-sharp

I'm a bit surprised that it doesn't crash the build... But Squoosh doesn't have the best error handling in general, so, also not too surprised.

Sorry for the inconvenience!

**Comment by housser** [comment]
I can try switching, but was able to resolve my issue in the short term by just converting the colour space of the image that was causing issues, once I was able to determine which one it was (helped by the additional console logging).

I will try to put together a PR with the logging change I made, as that would help others at least identify where the process was failing, and that verbose logging might also help with other potential issues that arise in the generation process due to unrelated issues.

**Comment by jacobthesheep** [comment]
I'm not sure when this bug was fixed but the image processing no longer fails and displays image on the lastest version

**Comment by Princesseuh** [comment]
> I'm not sure when this bug was fixed but the image processing no longer fails and displays the image on the latest version

Sharp is the default image processor now, this issue only affects Squoosh.

**Comment by Princesseuh** [comment]
Looking at our stats, less than 5% of Astro users are using a custom image service, the vast majority of which are using other services than Squoosh (ex: Vercel, Cloudflare etc.).

Considering this low usage and the fact that libsquoosh is unmaintained, it's quite likely that we'll be removing the squoosh service as a built-in service in the future and won't be fixing this issue unless someone send a PR. As such, I'll close this issue. Thank you for reporting it nonetheless!
