### ISSUE TITLE
Maximum call stack size exceeded on large page

### ISSUE THREAD

**Issue by hrmcdonald** [withastro/astro#7283]
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

Lit

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

On one of our largest pages with a lot of instances of custom elements, we get the following error:

```
Uncaught RangeError: Maximum call stack size exceeded.
    at hydrate ({{page-name-here}})
    at hydrate ({{page-name-here}})
    at hydrate ({{page-name-here}})
    at hydrate ({{page-name-here}})
```

This seems to happen in the logic for the `astro-island` web component, specifically this hydrate method:
<img width="795" alt="image" src="https://github.com/withastro/astro/assets/39349270/4ee4d622-6702-4146-8a45-6fc93a4c2f7d">

Nothing seems to be wrong with the page, but I think that might be because it's loading in and registering custom elements before it exceeds the call stack. Could something just be looping through too many instances of the same elements used across the page?

### Link to Minimal Reproducible Example

I don't know how to recreate this. I tried.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by proyb6** [comment]
Tried to create with Empty Project then fork/share?
https://astro.new/latest/

**Comment by bluwy** [comment]
I don't see how Astro's hydrate code could be called recursively. A repro would help a ton, but if it's not possible, maybe you can show the full stacktrace instead, or use something like https://replay.io

**Comment by hrmcdonald** [comment]
Thanks, I should have some time in the next week or two to dive deeper into trying to recreate this. I'll circle back and post more info then.

**Comment by hrmcdonald** [comment]
I was able to track this down to a single client:load/client:idle (it would happen with either) directive on web component that was rendered quite a bit within a few loops. Since this is a web component it only ever needs to be "loaded" once to register the element with the page. Hosting the load directive outside of the loops to single hidden instance of the component is enough to register the component without calling the client directive `load()` hundreds of times.

Is there a better pattern for dealing with this?

**Comment by bluwy** [comment]
I think I know what's going on, this hydrate code here could be called many times on startup if many islands are hydrated at once.

https://github.com/withastro/astro/blob/64b2b654109cda3dfdefec5104682eb96aaaead3/packages/astro/src/runtime/server/astro-island.ts#L98

For each island that finish hydrating, it removes its own `astro:hydrate` listener, but also trigger a global `astro:hydrate` event:
https://github.com/withastro/astro/blob/64b2b654109cda3dfdefec5104682eb96aaaead3/packages/astro/src/runtime/server/astro-island.ts#L128-L129

So for the other islands that are still hydrating but haven't reached that code yet (to remove the listener), the global event triggers their hydration again.

I actually made a refactor that should fix that while working on https://github.com/withastro/astro/pull/7197 (that PR doesn't include the fix, but I was investigating hydration code then). When that PR gets merged, I can try a fix and cut a preview release to test out.

**Comment by bluwy** [comment]
@hrmcdonald I've made a preview release at #7370, which you can try with `npm install astro@next--simple-nested-hydration`. Appreciate if you can test it out!

**Comment by hrmcdonald** [comment]
Awesome thanks, I'll find time to test this out soon.

**Comment by bluwy** [comment]
@hrmcdonald checking again if you're able to test this? Hoping to not let the PR hanging too long.

**Comment by hrmcdonald** [comment]
Sorry, we had a big release last week and I forgot to come back to this. I'll test this out today.

**Comment by hrmcdonald** [comment]
Confirmed @bluwy!

I re-configured a page to create the call-stack exceeded error from this issue and then tested the build again with `astro@next--simple-nested-hydration` and was no longer getting those errors.

**Comment by bluwy** [comment]
Awesome! Thanks for testing it. Will get that PR merged.
