### ISSUE TITLE
Mardoc Tags print out strange characters

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#7286]
### What version of `astro` are you using?

2.5.6

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

When I use Markdoc tags in Astro I get a `[object AsyncGenerator]` when I use a tag. 

To see what I mean all you have to do is follow these steps.

1. Click on blog you'll be lead to the blog posts page
2. Click on first post you'll be lead page with the error
 
The page is called `first-page` 

### Link to Minimal Reproducible Example

https://github.com/louiss0/astro-dummy-markdoc

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lgastler** [comment]
Exact same issue here :) 

### What version of `astro` are you using?
astro: 2.5.6
@astrojs/markdoc: 0.3.1

### Are you using an SSR adapter? If so, which one?
none

### What package manager are you using?
pnpm

### What operating system are you using?
macOS

**Comment by louiss0** [comment]
> Exact same issue here :)
> 
> ### What version of `astro` are you using?
> astro: 2.5.7 @astrojs/markdoc: 0.3.1
> 
> ### Are you using an SSR adapter? If so, which one?
> none
> 
> ### What package manager are you using?
> pnpm
> 
> ### What operating system are you using?
> macOS

In the meantime you can go back to 0.3.0

**Comment by bholmesdev** [comment]
@louiss0 @lgastler thanks! To confirm, this is a 0.3.1 specific issue?
