### ISSUE TITLE
glob() imported component with client:load throws error

### ISSUE THREAD

**Issue by Jan-Eckerlein** [withastro/astro#7287]
### What version of `astro` are you using?

2.5.7

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

firefox, safari

### Describe the Bug

Hey everyone :wave: 

Im getting and error when trying to hydrate components that ive imported via the `astro.glob()` function.
Im working on a lightweight foss cms and want to move to Astro as it would fairly easy allow me to make it framework agnostic.

In my `index.astro` im importing my svelte components using 
```
const svelteComponents = await Astro.glob('../components/*.svelte');
```
and rendering as explained in the docs like: 
```
{svelteComponents.map((comp) => <comp.default/>)}
```

this works fine, but Im not able to hydrate them using `client:load` without getting an Exception.

I coudnt find anything on the docs or forums regarding this Issue.
I would be very happy if someone could forward me any posts, docs, etc to me or directly giving me a solution to this here.

The Exception:
```
 error   Unable to resolve a valid export for "comp.default"! Please open an issue at https://astro.build/issues!
  File:
    /Users/janeckerlein/development/web/glob-import-client-load-issue/node_modules/astro/dist/runtime/server/hydration.js:79:11
  Code:
    78 |     children: "",
    > 79 |     props: {
         |           ^
      80 |       // This is for HMR, probably can avoid it in prod
      81 |       uid: astroId
      82 |     }
```

Thanks in advance

### Link to Minimal Reproducible Example

 https://stackblitz.com/edit/stackblitz-starters-amlrvz?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Jan-Eckerlein** [comment]
Other component props work.
A workaround that also makes sense in my project is to wrap the svelte/vue/etc components in a astro component wrapper where `client:load` is used and use the wrapper components instead.

**Comment by Jan-Eckerlein** [comment]
Although, it would be very nice to know if there is a direct way to define hydration for components imported using glob() function.

**Comment by bluwy** [comment]
It's not possible to make it work with a glob since we need to map a `<Component />` to the module it's from. For example, we can analyze that if you write:

```astro
---
import Component from './Component.svelte'
---

<Component client:load />
```

But it's not possible with:

```astro
---
import Component from './Component.svelte'

const allComponents = [Component] // simplified compiled example of Astro.glob

// you could be doing many things with `allComponents`, it's not safe to analyze this naively
---

{allComponents.map((comp) => <comp client:load />)}
```

Maybe it's possible to fix this someday by attaching the information on the imported module, but for now it's a limitation.

**Comment by Jan-Eckerlein** [comment]
Thanks @bluwy 
I see what you mean.
