### ISSUE TITLE
Waiting for tag value blocks processing of other elements in Astro components

### ISSUE THREAD

**Issue by kireerik** [withastro/astro#7289]
### What version of `astro` are you using?

2.5.7

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

and for example in the example the `content` is never loaded and displayed on the page. (Locally the page never loads.)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-z6jvzs-hjkozf?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This wouldn't work because Astro renders the HTML sequentially top-down for streaming. If you'd first encounter a promise, that can only be resolve after rendering the elements after it, it'll never resolve because the former depends on the latter, the latter depends on the former.

**Comment by kireerik** [comment]
I see. I wouldn't expect the HTML evaluation itself to be sequential (and the response can still be streamed as parts are getting resolved).

**Comment by kireerik** [comment]
There is no reason for the evaluation of elements at the same level to be blocking for eachother.

**Comment by kireerik** [comment]
Elements on the same level can be evaluated in parallel and streamed in sequence as the appropriate parts are resolved.

**Comment by kireerik** [comment]
This is an Astro component. I am not using JSX at all.
