### ISSUE TITLE
Cannot render the same slot twice

### ISSUE THREAD

**Issue by joshdcuneo** [withastro/astro#7290]
### What version of `astro` are you using?

2.5.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

This issue has been raised before [here](https://github.com/withastro/astro/issues/6220) I think but no reproduction was provided.

I've forked the [Stackblitz](https://stackblitz.com/edit/github-zze9lp?file=src%2Flayouts%2FDoubleLayout.astro,src%2Fpages%2Findex.astro) from @bluwy in that issue to reproduce the issue.

It appears that astro components will render correctly in the second slot but at least Svelte components don't. I haven't tested with any other UI framework.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zze9lp-aqk6st?file=package.json,src%2Fpages%2Findex.astro,src%2Fcomponents%2FCard.svelte

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
`<slot>` is single use. To do something like you are wanting to do, use the dynamic `Astro.slots.render()` API instead, like so: https://stackblitz.com/edit/github-zze9lp-x47o5y?file=package.json,src%2Fpages%2Findex.astro,src%2Flayouts%2FDoubleLayout.astro
