### ISSUE TITLE
Waiting for tag value causes imported module issue in Astro components

### ISSUE THREAD

**Issue by kireerik** [withastro/astro#7292]
### What version of `astro` are you using?

2.5.7

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

In this case I get a syntax related exception for the Astro component related to the result (content) returned from my module.

example with issue:
```Astro
---
import getContent from './module'
---

<Fragment set:html={await (async () =>
	<Fragment set:html={await getContent()}/>
)()}/>
```

workaround example:
```Astro
---
import getContent from './module'
const content = await getContent()
---

<div set:html={content}/>
```

### Link to Minimal Reproducible Example

⠀

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I wouldn't expect this to work. A `<Fragment>` is not a string value. It's a component instance. So you're passing a component instance into something that expects a string. The Promise part is not relevant.

**Comment by bluwy** [comment]
I agree with Matthew too. About the promise part, I guess we can take it to #7293
