### ISSUE TITLE
Typescript included even when no Typescript is selected

### ISSUE THREAD

**Issue by MrAmericanMike** [withastro/astro#7299]
### What version of `astro` are you using?

2.5.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

Run
```sh
pnpm create astro@latest
```

Select the directory for the project. Select "Include sample files"

Install Dependencies > No

Do you plan to write Typescript > No

Initialize Git > No

Then go into the `layouts` folder inside `src` folder. Layout.astro contains this code
```js
export interface Props {
	title: string;
}
```

Also file `env.d.ts` exists on the project, together with `tscofig.json`

I believe the Typescript question should be asked first and then Astro Create handle what template it copies, in order to use one that doesn't include Typescript at all.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=src%2Flayouts%2FLayout.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is expected, Astro is TypeScript only. The question only makes it so the configuration is more relaxed for users not used to TypeScript
