### ISSUE TITLE
404.astro not rendering 404.html when there are dynamic routes in the root directory

### ISSUE THREAD

**Issue by hongfanmeng** [withastro/astro#7301]
### What version of `astro` are you using?

2.5.0

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

404.astro not rendering 404.html when there are dynamic routes in the root directory

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nhc9gb?file=src%2Fpages%2F404.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arpadgabor** [comment]
Experiencing this too.

**Comment by proyb6** [comment]
Finally! I hit 404 page not found error.

**Comment by proyb6** [comment]
Finally! Found 404 page not found after the fixed.
