### ISSUE TITLE
`[@mdx-js/rollup]` null bytes in `path`

### ISSUE THREAD

**Issue by DerYeger** [withastro/astro#7302]
### What version of `astro` are you using?

2.5.6+

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

ppm

### What operating system are you using?

Mac, Linux (CI)

### What browser are you using?

Chrome, Safari

### Describe the Bug

Since Astro v2.5.6 I can no longer build my website.
The release changed the build logic with the following line:
https://github.com/withastro/astro/blob/d72cfa7cad758192163712ceb269405659fd14bc/packages/astro/src/core/build/plugins/plugin-pages.ts#L12

This results in the following error:

```
[@mdx-js/rollup] The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00@astro-page:src/pages/datenschutzerklaerung@_@mdx'
```

### Link to Minimal Reproducible Example

https://github.com/DerYeger/jan-mueller/tree/renovate/all-minor-patch

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
It looks like you're using the wrong version of the MDX integration (and the image integration).

https://github.com/DerYeger/jan-mueller/blob/60da8e7e67074ba55598a726621ee61e993d6a4d/package.json#L34-L35

For MDX in particular, you should use v0.19.6 (https://www.npmjs.com/package/@astrojs/mdx). I think we had accidentally published the beta version of those packages.

**Comment by DerYeger** [comment]
Thanks, I missed that and got hung on 2.5.5 working.
It's fixed now!

**Comment by xldrkp** [comment]
Thanks @bluwy, you saved my Feierabend.
