### ISSUE TITLE
Images are in wrong orientation

### ISSUE THREAD

**Issue by Akxe** [withastro/astro#7304]
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

Github pages

### What package manager are you using?

npm

### What operating system are you using?

Windows & Ubuntu (for build)

### What browser are you using?

Chrome

### Describe the Bug

I was pulling images from `.md` as a list, so I had to process them in `/projects/[...slug].astro` file

I used the snippet code below:

```typescript
const photos = (await Promise.all(data.photos.map(photo => getImage({
  src: photo.img,
  alt: photo.alt || `Vizualizace projektu "${data.title}"`,
})))).map(photo => {
  if (typeof photo.options.src == 'string') {
    throw new Error('Image not loaded');
  }

  return {
    src: photo.src,
    alt: photo.attributes.alt as string,
    style: {
      aspectRatio: `${photo.options.src.width}/${photo.options.src.height}`, 
      objectFit: 'cover',
    },
  };
});
```

I was the optimizing the code to run more in parallel and fixed it. To my surprise, the fix is when you switch from `getImage` options object to a string.

```typescript
const photos = await Promise.all(data.photos.map(photo => getImage(photo.img).then(result => {
  return {
    src: result.src,
    alt: photo.alt || `Vizualizace projektu "${data.title}"`,
    style: {
      aspectRatio: `${result.options.width}/${result.options.height}`,
      objectFit: 'cover',
    },
  };
})));
```

The bug is present regardless if you use Squoosh or Sharp.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jfzz89?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by millette** [comment]
For comparison, see:

<https://github.com/withastro/astro/blob/main/packages/integrations/image/src/loaders/sharp.ts#L18-L19>
