### ISSUE TITLE
@astrojs/markdoc v0.3.1 (reprise of issue #7170): Markdoc tag rendering Astro component breaks when component uses getEntryBySlug()

### ISSUE THREAD

**Issue by paulrudy** [withastro/astro#7317]
### What version of `astro` are you using?

2.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Safari

### Describe the Bug

This is a reprise of issue #7170, which shows up again with @astrojs/markdoc v0.3.1. Details basically identical to the previous issue, except that this time around, local Astro in dev mode doesn't seem to throw an error. In Stackblitz, it does.

This is a very particular bug that showed up with @astrojs/markdoc v0.3.1 , when all of the following are true:

1. @astrojs/markdoc is v0.3.1
2. Pages are served from a content collection of _at least two_ .mdoc files.
3. `markdoc.config.mjs` imports an Astro component (for the purpose of defining a tag, although no tag actually needs to be defined—or used in any .mdoc file)
4. The Astro component uses `getEntryBySlug()` to access data from another content collection (the new `getEntry()` also produces the error)

In local dev mode, I'm not seeing an error, the page just doesn't render. In Stackblitz looks like:

```
  error   Unexpected error while rendering pages → index.mdoc.
Error
    at AstroError (<anonymous>)
    at <anonymous> (<anonymous>)
    at render (<anonymous>)
```

Pages render as expected after downgrading to v0.3.0, or when any of the other items above are false!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pq3pgo-xieer6?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Hm, this is proving a _very_ weird nut to crack. It looks like the circular dependency of `astro:content` -> `.mdoc` file -> component -> `astro:content` is causing a memory issue in Vite. If you just have _one_ content collection entry, the Markdoc module looks fine:

```ts
{
  getHeadings: [function],
  Content: [function],
  [Symbol(Symbol.toStringTag)]: 'Module' }
}
```

But as soon as there's two or more files _in that collection,_ it becomes this:
```ts
{ [Symbol(Symbol.toStringTag)]: 'Module' }
```
Like Vite is throwing away the keys in the module 😕 Paging @bluwy if he has any ideas

**Comment by bholmesdev** [comment]
As a workaround, I'd try passing `getEntry` as a Markdoc variable to "inject" into your content. This breaks the circular dependency issue:

```ts
// markdoc.config.mjs
import { defineMarkdocConfig } from '@astrojs/markdoc/config';
import Aside from './src/components/Aside.astro';

export default defineMarkdocConfig({
	tags: {
		aside: {
			render: Aside,
			attributes: {
				name: String,
				getAside: Object,
			},
		},
	},
});
```

```astro
// src/content/[...slug].astro
---
import BaseLayout from '../layouts/Layout.astro';
import { getEntry, getEntryBySlug } from 'astro:content';
const { slug } = Astro.params;
const page = await getEntryBySlug('pages', slug === undefined ? 'index' : slug);
const { Content } = await page!.render();
---

<BaseLayout title={page!.data.title}>
	<Content getAside={(name: string) => getEntry('asides', name)} />
</BaseLayout>
```

```md
<!--src/content/pages/index.mdoc-->
{% aside name="1" getAside=$getAside /%}
```

```astro
// src/components/Aside.astro
---
const { getAside, name } = Astro.props;
const aside = await getAside(name);
const asideTitle = aside.data.title;
---

<div>{asideTitle}</div>
```

**Comment by paulrudy** [comment]
Apologies, I am actually able to use the workaround with Astro files, but it requires passing `getEntry()` as a variable through multiple components (in my case, from `[...slug].astro` to `BaseLayout.astro` to `Sidebar.astro`), which is makes this workaround a bit precarious when trying to replicate normal functioning of `getEntry()`

**Comment by bholmesdev** [comment]
Hey @paulrudy! The new `render` API is up on a preview release. Just verified it fixes your minimal repro locally. When you have time, do you mind:

1. Installing these versions in your test project

```
npm i astro@latest @astrojs/markdoc@markdoc-config-changes
```

2. Updating your Markdoc config [as described by the changeset here](https://github.com/withastro/astro/pull/7468/files#diff-41c694ad29a01e3186971cafb3d42dc20099fbda1b8c0436dac6c22ddce91d90)?

**Comment by bholmesdev** [comment]
@paulrudy Woooo! Just merged. You'll see it once Markdoc v0.4.0 is live 🥳
