### ISSUE TITLE
Astro redirects not working

### ISSUE THREAD

**Issue by Erlandas** [withastro/astro#7322]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Tried out new experimental redirects. 
```javascript
experimental: {
    redirects: true
  },
redirects: {
    '/a': '/b'
  }
 ```
Went trough all paths possible (for both new page and old page with slash and without) Yet visiting page "/a" no redirects being made (both in dev and production).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-njit3y

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jlarmstrongiv** [comment]
The types and validation for `redirects` are also incorrect

**Comment by matthewp** [comment]
I can recreate the dev problem. Fixing now.

**Comment by pijusz** [comment]
Would like to reopen this @matthewp
In astro docs, redirect with non-301 status doesn't work.

Goal is to be able to redirect with parameters status 308 (f.e. `/b?type=b`, `/a?type=b`)
```javascript
  output: "hybrid",
  adapter: vercel(),
  experimental: {
    redirects: true,
  },
  redirects: {
    "/b": {
      destination: "/a",
      status: 308,
    },
  },
```

received error:
```
[config] Astro found issue(s) with your configuration:
  ! redirects./b  Expected string, received object.
```

**Comment by bluwy** [comment]
Can confirm this is still happening. I'm refactoring some tests that now validates the config, and it fails with the error too. We need to fix the validation here: https://github.com/withastro/astro/blob/ed20154a5c89f07e87784c5fe80a028ceef741fa/packages/astro/src/core/config/schema.ts
