### ISSUE TITLE
createResource from solidjs integration does not react to states 

### ISSUE THREAD

**Issue by AkashRajpurohit** [withastro/astro#7323]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

`createResouce` from solid-js behaves weirdly with astro integrations, it does not react to error, loading etc states like it does with standalone solid application.

For example: If you check this [solid-js playground](https://playground.solidjs.com/anonymous/ab2a2201-3ade-4f8f-8538-f7f52b9b521c) the output would be `loading...` for 2 seconds and `errored...` after that since the fetcher throwed the error.

However the behavior changes when applied in Astro and it never moves away from loading to error state.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cqlpxq?file=src%2Fcomponents%2FResourceTesting.tsx&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by AkashRajpurohit** [comment]
Hey @natemoo-re is there any update on this?

**Comment by Guergeiro** [comment]
@AkashRajpurohit I also have this issue. Until it is solved, I'm forcing client-side render with `client:only="solid-js"`.

**Comment by natemoo-re** [comment]
Hey, sorry for the delay! I'm planning to look into this on Monday.

**Comment by nienow** [comment]
If I load the stackblitz example and click on a different file right away, it works fine (goes to error state). Also, if hit the refresh button it works well too. Very odd.

**Comment by nienow** [comment]
There is now a `state` property on a resource that was introduced in solid v1.5. It appears that using this state property works great in my Astro project, where I was also having trouble with the legacy properties (loading, error, etc).

An example:
```
const [data] = createResource(async () => {
    return new Promise((resolve) => {
	setTimeout(() => {
		resolve();
	}, 1000);
    });
  });
return <div>
  {data.state === 'pending' && <p>loading</p>}
  {data.state === 'ready' && <p>ready</p>}
  {data.state === 'errored' && <p>errored</p>}
</div>
```

https://docs.solidjs.com/references/api-reference/basic-reactivity/createResource#v150

**Comment by bluwy** [comment]
I can't seem to reproduce this in stackblitz, locally, and locally + Astro 3.0. Cleaning up some of our long-standing issues and will close this for now, but if it happens again feel free to let us know!
