### ISSUE TITLE
Define css variables, do not add to the style attribute of each tag

### ISSUE THREAD

**Issue by J-env** [withastro/astro#7328]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm,pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

// css-test.astro
```astro
---
const color = 'red';
---

<div>
  1111
  <button type="button">button</button>
</div>

<style define:vars={{ color }}>
  button {
    color: var(--color);
  }
</style>
```

<img width="810" alt="image" src="https://github.com/withastro/astro/assets/25259920/c319fac1-7364-4f74-a955-64ee876fef49">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sdeict-dc8tm6?file=src%2Fcomponents%2FDefineVars.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by J-env** [comment]
Duplicate style attribute

project:

<img width="1136" alt="image" src="https://github.com/withastro/astro/assets/25259920/a0e79a4f-d6f7-4570-8d09-706c6bc4b500">

**Comment by matthewp** [comment]
I assume we are doing it this way because this avoids `--color` from bleeding into child components. I'm not really sure though. Anyways, if you wanted to submit a PR that changed how this work we could discuss there. We like to keep the issue tracker to bugs, and this is an intentional design decision, so going to close. Happy to continue discussing here though!

**Comment by J-env** [comment]
```astro
---
const color = 'red';
---

<div>
  1111
  <button type="button">button</button>
</div>

<style define:vars={{ color }}>
  button {
    color: var(--color);
  }
</style>
```

build:
```
<style>
button.astro-hash {
  color: var(--color-hash);
}
<style>
```

**Comment by matthewp** [comment]
@J-env Where is it defined to `red` in this example?

**Comment by J-env** [comment]
@matthewp  The outermost element of the component

buid: 
```html
<div style="--color-hash: red;">
  1111
  <button type="button">button</button>
</div>

<style>
button.astro-hash {
  color: var(--color-hash);
}
<style>
```

**Comment by clockworkroger** [comment]
It's an ongoing issue, one that definitely needs reconsideration.

I think only setting `--color` on the outermost HTML element is a perfectly acceptable and expected use of CSS custom properties. I don't even think it needs to be hashed, because it's already scoped to that specific element, going into the inline style tag like that.

Arguably, you're doing _more_ work by outputting that style attribute on `<div>` _and_ `<button>` inside it the way Astro is now.

Let me throw another use-case out there...

I have a component for a section to which I'm adding a background image (three, actually, for responsive lazy loading). If I use `define:vars` to create a custom property so that my background image URL from `getImage()` can be used for that component, I get a `style=` attribute on my outermost `<section>` tag.... and every `<div>`, `<h3>`, `<p>`, and `<a>` tag inside it. None of those tags need the custom property, because CSS already handles that if for some reason they _do,_ but it's now defined for every single one of them, and my HTML is that much longer. Because of that, I'm adding my own `style=` attribute on my outermost tag.... it's just not as clean as if I were following the example laid out in the docs.

More generically, if I make a Card component with a `customColor` property and in its CSS, I have a button background color, text color, and border color all using the same `var(--custom-color)`, I'd expect that my outermost Card `<li>` or `<div>` (whatever it is) has a `style="--custom-color: red"` attribute on it, and that's it. A little like how you might have to explicitly pass properties or content down through multiple components if you want to set something on the deepest one.

And I understand that it's almost antithetical to the whole idea of Astro, but it feels like it simplifies things in an intuitive way.

(Full disclosure, I'm still somewhat new to Astro, so maybe I'm just doing things entirely wrong. Only really started using it a couple weeks ago for a project here at work. But I gotta say, I _really_ like it so far.)

**Comment by idalmus** [comment]
My site is cluttered with scoped style attributes with variables in each tag. It's really very odd. Must have something to do with this. The most important thing is that my site made with Astro works perfectly. But this really isn't very pretty. Here an example:


<section id="header-menu" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
   <div id="logo" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
      <a id="terugnaarinleiding" href="/nl/inleiding/" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">©<br data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">2023</a> 
      <div id="jessemusson" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
         <p data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">Jesse <strong data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">M*******n</strong></p>
      </div>
   </div>
   <div id="menu-container" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
      <div id="desktop-menu" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
         <a id="inleiding" class="menu-tekstopmaak kleine-padding selecteren" href="/nl/inleiding/" title="Inleiding tot deze website" aria-label="inleiding" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">inleiding</a> 
         <div id="mijn-verhaal" class="menu-tekstopmaak" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
            <a href="javascript:;" id="desktop-knop" class="menu-tekstopmaak kleine-padding selecteren" aria-label="mijn verhaal" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">mijn verhaal <i class="fa-solid fa-chevron-down" style="margin-left: 10px; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2></i></a> 
            <div id="submenu" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
               <a href="/nl/deel-1/" title="Deel 1: 1984—2017" aria-label="Deel 1: 1984—2017" class="selecteren submenu-marges" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                  <div data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                     <p data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"><strong style="font-size: 19px;; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2>Deel 1&nbsp;</strong>&nbsp;1984—2017</p>
                  </div>
               </a>
               <a href="/nl/deel-2/" title="Deel 2: 2018—2023" aria-label="Deel 2: 2018—2023" class="selecteren submenu-marges" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                  <div data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                     <p data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"><strong style="font-size: 19px;; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2>Deel 2&nbsp;</strong>&nbsp;2018—2023</p>
                  </div>
               </a>
               <a href="/nl/deel-3/" title="Deel 3: andere info" aria-label="Deel 3: andere info" class="selecteren submenu-marges" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                  <div data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                     <p data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"><strong style="font-size: 19px;; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2>Deel 3&nbsp;</strong>&nbsp;andere info</p>
                  </div>
               </a>
            </div>
         </div>
         <a class="menu-tekstopmaak kleine-padding selecteren" href="/nl/artikelen/" title="Lees mijn artikelen" aria-label="artikelen" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">artikelen</a> <a class="menu-tekstopmaak kleine-padding selecteren" href="/nl/contact/" title="Neem contact met mij op" aria-label="contact" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">contact</a> 
      </div>
      <div id="mobile-menu-container" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
         <div id="mobile-menu" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
            <div id="menu-icoon" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
               <div class="bar1" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"></div>
               <div class="bar2" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"></div>
               <div class="bar3" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"></div>
            </div>
            <div id="menu-tekst" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">menu</div>
            <div id="mobile-menu-links" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
               <div id="mobile-menu-div" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                  <div id="linkerkolom" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                     <a class="menu-marges menu-tekstopmaak mobmenu-select" href="/nl/inleiding/" title="Inleiding tot deze website" aria-label="inleiding" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">inleiding</a> <a href="/nl/inleiding/#keuze-section" class="menu-marges menu-tekstopmaak" aria-label="mijn verhaal" style="margin-bottom: -10px;; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2>mijn verhaal <i class="fa-solid fa-chevron-down" style="margin-left: 10px;; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2></i></a> 
                     <a href="/nl/deel-1/" title="Deel 1: 1984—2017" aria-label="Deel 1: 1984—2017" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                        <div class="mob-submenu-marges mobmenu-select mobmenu-sub" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                           <p data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"><strong style="font-size: 19px;; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2>Deel 1&nbsp;</strong>&nbsp;1984—2017</p>
                        </div>
                     </a>
                     <a href="/nl/deel-2/" title="Deel 2: 2018—2023" aria-label="Deel 2: 2018—2023" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                        <div class="mob-submenu-marges mobmenu-select mobmenu-sub" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                           <p data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"><strong style="font-size: 19px;; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2>Deel 2&nbsp;</strong>&nbsp;2018—2023</p>
                        </div>
                     </a>
                     <a href="/nl/deel-3/" title="Deel 3: andere info" aria-label="Deel 3: andere info" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                        <div class="mob-submenu-marges mobmenu-select mobmenu-sub" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">
                           <p data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"><strong style="font-size: 19px;; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2>Deel 3&nbsp;</strong>&nbsp;andere info</p>
                        </div>
                     </a>
                  </div>
                  <div id="rechterkolom" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"> <a class="mobmenu-select menu-marges menu-tekstopmaak" href="/nl/artikelen/" title="Lees mijn artikelen" aria-label="artikelen" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">artikelen</a> <a class="mobmenu-select menu-marges menu-tekstopmaak" href="/nl/contact/" title="Neem contact met mij op" aria-label="contact" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;">contact</a> </div>
               </div>
            </div>
         </div>
         <div id="taalswitch" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"> <a href="/en/behold-the-shadow/" data-astro-cid-3ef6ksr2 style="--cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;"><img src="/afbeeldingen/US-flag.png" alt="" style="position: relative; width: 25px; height: 25px; top: 3px;; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2><span class="selecteren" style="margin-left:8px; position: relative; bottom: 2px;; --cssLinkNaarJesseJpg: url('/afbeeldingen/Jesse.jpg');--cssLinkNaarJesseWebp: url('/afbeeldingen/Jesse.webp');--submenubreedte: 210px;" data-astro-cid-3ef6ksr2>English</span></a> </div>
      </div>
   </div>
</section>
