### ISSUE TITLE
Middleware is not being executed before the page 

### ISSUE THREAD

**Issue by e3stpavel** [withastro/astro#7332]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Edge

### Describe the Bug

When I use `next()` in middleware it does work as expected, see the logs
![image](https://github.com/withastro/astro/assets/70956582/6b34bba9-f373-44a4-996d-aeb1aef2819e)

but once I use `await next()` to get `response` and then return it (as it was mentioned in [example here](https://docs.astro.build/en/guides/middleware/#chaining-middleware)) I got the following output
![image](https://github.com/withastro/astro/assets/70956582/f73a5cad-6f49-4885-b24d-a377bbf36a4e)

The code for middleware:
```typescript
import { defineMiddleware } from 'astro/middleware'

export const onRequest = defineMiddleware(async (_, next) => {
  const response = await next()
  console.log('Middleware')

  return response
})
``` 

Code on the page:
```typescript
---
console.log('Astro page')
---
<p>Hello</p>
```

__NOTICE!__ The behaviour is the same for both dev and build

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bhphv9?file=src%2Fmiddleware.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Calling next calls the next middleware. If there is no middleware it calls the page. Put a console log before the `await next()` and it will be flipped.

This is intentional and how you are able to modify the response of the page. If you need to do something before the page is called, do it before calling next.
