### ISSUE TITLE
HTML Minification

### ISSUE THREAD

**Issue by proyb6** [withastro/astro#7333]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

In 2.6.0 update which has been patched with 
https://github.com/withastro/astro/pull/7242

I found the `<doctype>`  still contains newline while other part are minified, did the patch solved the issue?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wjgoff?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by proyb6** [comment]
`<doctype>` is minify when presender is set to true, `export const prerender = true;`

`<doctype>` is not minify when prerender is set to false.

**Comment by matthewp** [comment]
Can you add a reproduction please?
