### ISSUE TITLE
[regression] Markdown component generates console error in 2.6

### ISSUE THREAD

**Issue by birtles** [withastro/astro#7335]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

When using the `<Markdown>` component from `@astrojs/markdown-component` and running `astro build` now generates a console error:

```
The <Markdown> component is not available in SSR. See https://github.com/withastro/rfcs/discussions/179 for more info.
```

This is despite the fact that it is being used in SSG mode.

It didn't use to do with this before 2.6.

I'm guessing this is due to the redirects work in #7067 since that made us stop using `onlyAvailableInSSR` (which, it seems like we probably could have deleted at that point).

You can reproduce this in the linked-to StackBlitz container by running `npx astro build` from the command line.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ch7wk5?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, fix should be released today.
