### ISSUE TITLE
Vue async setup

### ISSUE THREAD

**Issue by vinhui** [withastro/astro#7336]
### What version of `astro` are you using?

2.6.1 / 2.4.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I have a vue component which needs an `async setup`. But when I do this, the whole vue reactivity doesn't work anymore. If I remove the `async` (and the `await` in the body) it works like expected.

You can also see in the console logs that the `mounted` of the `nestedText.vue` never gets called. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-za2t4b-xwbuwf?file=src%2Fcomponents%2FnestedTest.vue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by munkeawtoast** [comment]
Async component needs to be wrapped in [`<Suspense>`](https://vuejs.org/guide/built-ins/suspense.html)

```vue
// test.vue
<Suspense>
  <NestedTest :test="number" />
</Suspense>
```

**Comment by bluwy** [comment]
Yup, the browser also warns:

```
[Vue warn]: Component <NestedTest>: setup function returned a promise, but no <Suspense> boundary was found in the parent component tree. A component with async setup() must be nested in a <Suspense> in order to be rendered.
```

Astro does support async components when used in an `.astro` file by default, but when used in a `.vue` file, you'd have to follow it's usage pattern.

**Comment by vinhui** [comment]
I totally missed that warning. Thanks both!
