### ISSUE TITLE
Does react integration work with deno?

### ISSUE THREAD

**Issue by braco** [withastro/astro#7344]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

deno

### What package manager are you using?

yarn

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

Does the react integration work with deno?

As in 
`astro.config.mjs`
```
  output: "server",
  integrations: [react()],
  adapter: deno()
```

The first error I got was `process` undefined, which I fixed with this in `astro.config.mjs`:
```
if (typeof globalThis !== 'undefined' && typeof Deno !== 'undefined') {
  globalThis.process ||= {
    env: Deno.env.toObject()
  }
}
```

now I'm getting `module` is undefined, due to this:

`node_modules/.deno/react@18.2.0/node_modules/react/index.js`
```
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Is this is in dev mode?

**Comment by braco** [comment]
Yes, I was having another issue with build:

https://github.com/withastro/astro/issues/7330

but I removed that library and it looks like build is successful now. dev is still giving the errors as above

**Comment by bluwy** [comment]
Astro doesn't officially support Deno in dev, though it works with Vite. Do you have a repro? I think the fix here would be in `astro.config.mjs` to import as `import react from 'npm:@astrojs/react@2.2.1'`.

**Comment by matthewp** [comment]
Closing as we don't officially support Deno dev mode at the moment.
