### ISSUE TITLE
slot fallback removed with empty content

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [withastro/astro#7346]
### What version of `astro` are you using?

2.6.2

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Hi,

Is it possible to display the fallback slot when the content is empty?
I take an example, I have a component
```
<List>
  {contents?.map(item => <item value={item} />) }
</List>
```

definition of List:
```
<ul>
<slot>Empty</slot>
</ul>
```

I would like if contents is null, the fallback of List is displayed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bi9q8b?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is how it's supposed to work. Fallback occurs when there is no slot provided. In this case you are passing an expression as the child. So even though it winds up producing no HTML, there is a slot usage there.

To do what you are trying to do, use `Astro.slots.render('default')` and check that the string is empty or not.
