### ISSUE TITLE
Update image tags in examples 

### ISSUE THREAD

**Issue by dotarjun** [withastro/astro#7357]
### What version of `astro` are you using?

^2.5.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Edge

### Describe the Bug

![image](https://github.com/withastro/astro/assets/71163609/78b84e37-876a-4939-8b4d-a258781c4ac6)
https://github.com/withastro/astro/blob/main/examples/portfolio/src/pages/index.astro

The img tags should be replaced with ``<Image />`` for better performance as explained here https://docs.astro.build/en/guides/integrations-guide/image/

I would like to be assigned to this issue

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/blob/main/examples/portfolio/src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This looks like a good change, but I guess the reason it wasn't added initially was because it's still experimental 🤔

**Comment by matthewp** [comment]
Going to close, happy to receive a PR, but don't want to keep an issue open for a suggestion.
