### ISSUE TITLE
Create Astro project is not working when tailwind is added

### ISSUE THREAD

**Issue by geongeorge** [withastro/astro#7358]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

When create a new astro project and add tailwind I see this error when I run `yarn dev`

```sh
warning package.json: No license field
$ astro dev
 error   Cannot find module '/Users/geon/Work/headstart/xyz/node_modules/yaml/dist/index.js'
Error: Cannot find module '/Users/geon/Work/headstart/xyz/node_modules/yaml/dist/index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1075:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1068:15)
    at resolveExports (node:internal/modules/cjs/loader:551:14)
    at Module._findPath (node:internal/modules/cjs/loader:620:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:27)
    at Module._load (node:internal/modules/cjs/loader:898:27)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/geon/Work/headstart/xyz/node_modules/postcss-load-config/src/index.js:7:14)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I also tried creating with template using 
```
yarn create astro --template with-tailwindcss
```

I get the same error.

Looks like `/yaml/dist/` does not contain any index.js file

### Link to Minimal Reproducible Example

https://github.com/geongeorge/astro-tailwind-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by geongeorge** [comment]
I installed with npm and it works fine but yarn does not work

```sh

astro-tailwind-issue (master) [!?] ❯ npm i      

added 505 packages, and audited 506 packages in 5s

213 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

astro-tailwind-issue (master) [!?] ❯ npm run dev

> astro-tailwind-issue@0.0.1 dev
> astro dev

  🚀  astro  v2.6.2 started in 207ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
  ```

**Comment by geongeorge** [comment]
When I did this it worked. For some reason the default install does not work, this might not be an issue with astro. But still very frustrating.
```
yarn install --check-files
```

**Comment by bluwy** [comment]
I can't reproduce this either. Looks like you had a broken `node_modules` installation that causes the issue. There's not much we can do here.
