### ISSUE TITLE
Node version check?

### ISSUE THREAD

**Issue by yao-charlie** [withastro/astro#7359]
### What version of `astro` are you using?

9.7.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

N/A

### Describe the Bug

```
PS C:\Users\user\github\new_website> npm run dev

> dev
> astro dev

Node.js v16.5.0 is not supported by Astro!
Please upgrade Node.js to a supported version: ">=16.12.0"

PS C:\Users\user\github\new_website> npm config list
; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.20.0
; npm local prefix = C:\Users\user\github\new_website
; npm version = 9.7.1
; cwd = C:\Users\user\github\new_website
; HOME = C:\Users\user
```

It's on a fresh install of astro.

Err, not sure if this is an error with astro but if you'll see above, using npm with astro throws the Node.js version error, whereas npm reports a version which should be compatible. Also happens with changing to v17 or v18. Using nvm FWIW.

Reset node cache, re-installed, etc but same error. Can't find anything else that addresses this issue. Swapped to yarn and it seemed to work fine so not exactly urgent for me anymore.

N.B. Minimal reproducible example isn't one but seems like a requirement so it's just generic.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
The Astro CLI (and other CLIs) are actually using node v16.5.0 somehow. There might be lingering nodejs installation in your machine. Perhaps this [StackOverflow thread](https://stackoverflow.com/questions/24670235/cli-references-wrong-npm-version) may help.
