### ISSUE TITLE
Average number of files in build / Github actions fails to deploy to Deno Deploy, possibly due to large build size?

### ISSUE THREAD

**Issue by braco** [withastro/astro#7360]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

deno

### What package manager are you using?

yarn

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

Trying to sense check if this seems correct.

I can't seem to get astro to work with deno deploy.

Deno requires the user add a Github action to their repo, which does a build and upload.

After some work, it reaches the upload stage, and has this many files:

Uploading 14635 file(s) (total 220085755 bytes

Then it starts dumping out the (very slow) upload progress:
```
Uploading 14635 asset(s) (24.1%)
```

which I think is eventually killed or timed out by Github's process supervisor:

```
Uploading 14635 asset(s) (43.2%)
Error: TypeError: terminated
```

Does this number of files seem correct for a typical astro build? Here's my config:

```
export default defineConfig({
  output: 'server',
  integrations: [react()],
  build: {
    inlineStylesheets: 'auto',
  },
  adapter: deno(),
});
```

my local dist folder only has about 15 files in it, and my node_modules has over 35k, so I'm not sure what files it's counting there.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Did you set the `root` parameter for the action? https://docs.astro.build/en/guides/deploy/deno/#github-actions-deployment

**Comment by natemoo-re** [comment]
Hey @braco since we haven't gotten a response on this, I'm going to close the issue in an effort to keep our issues relevant and actionable! Please feel free to re-open if you're still running into this problem after trying to suggested fix.
