### ISSUE TITLE
`@tailwind base;` causes Astro to include script tags from other files

### ISSUE THREAD

**Issue by szmarczak** [withastro/astro#7363]
### What version of `astro` are you using?

2.6.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

If you include

```astro
    <style>
      @tailwind base;
    </style>
```

in `index.astro` then if you visit the webpage it will load all scripts from other Astro files. If you open the console you will see `Welcome, browser console!` even though this should be only visible on `/a`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ntewbh

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jgh713** [comment]
Just ran into this issue in the current Astro version (v3.4.3). Really incredibly confusing and a nightmare to track down the underlying issue. Further obscured by the fact that the `@tailwind base` directive was included as part of an external file with something along the lines of `<style lang="scss">@use 'path/file.css'</style>`.

Using the directive outside of a raw `import` statement in server-code seems to blindly load every component's javascript tags, wreaking havoc on testing on dev servers and potentially leading to some really dangerous cross-page functionality.

**Comment by bluwy** [comment]
I'm not sure why I tagged this a p3. This is due to Tailwind marking every Astro files as the importer of this file, so when we try to include the scripts of the imported Astro components, we're not correctly checking the actually imported files. This is a limitation of Tailwind and Vite so there's not much we can fix here.

Using `@astrojs/tailwind` is the safer way to avoid issues like this.

**Comment by szmarczak** [comment]
> Using @astrojs/tailwind is the safer way to avoid issues like this.

I'm not sure if you've noticed @bluwy but the repro is already using `@astrojs/tailwind`

**Comment by bluwy** [comment]
Sorry yeah I missed that while triaging this. There's now a new issue where you can track this progress: https://github.com/withastro/astro/issues/9370

The workaround is to put the tailwind CSS into its own CSS file instead, and import it from an Astro file.

**Comment by abolajibisiriyu** [comment]
You can also try changing the `astro` version, using `^3.5.6` at the moment. I guess `3.x.x`
