### ISSUE TITLE
Broken types for experimental redirects

### ISSUE THREAD

**Issue by bholmesdev** [withastro/astro#7375]
### What version of `astro` are you using?

2.6.3

### Are you using an SSR adapter? If so, which one?

Tried none and Vercel serverless

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Type definitions seem to be broken when using an `astro.config.ts` file with experimental redirects. Instead of expecting a _record_ of `RedirectConfig`s, it expects a single redirect config:

<img width="777" alt="image" src="https://github.com/withastro/astro/assets/51384119/917af074-c0b3-46a4-bc0f-fc6bbed639cf">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-b138wi?file=astro.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I think this is fixed in https://github.com/withastro/astro/pull/7366

**Comment by bholmesdev** [comment]
Looks like it! Missed the PR. Thanks Blu ❤️
