### ISSUE TITLE
deply Netfily  Error

### ISSUE THREAD

**Issue by chenxi24** [withastro/astro#7389]
### What version of `astro` are you using?

2.5.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

There are no errors in the local build. but when i deply Netfily The error message is as follows

4:12:48 PM: -  Getting diagnostics for Astro files in /opt/build/repo/…
4:12:51 PM: ✔  Getting diagnostics for Astro files in /opt/build/repo/…
4:12:51 PM: 08:12:51 AM [diagnostics] 
4:12:51 PM:  /opt/build/repo/src/pages/index.astro:2:24 Error: Cannot find module '@/layouts/BaseLayout.astro' or its corresponding type declarations.
4:12:51 PM: 01  ---
4:12:51 PM: 02  import BaseLayout from '@/layouts/BaseLayout.astro'
4:12:51 PM:                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4:12:51 PM: 03  import Hero from '@/components/Hero.astro'
4:12:51 PM: 08:12:51 AM [diagnostics] 
4:12:51 PM:  /opt/build/repo/src/pages/posts/[...page].astro:4:24 Error: Cannot find module '@/layouts/BaseLayout.astro' or its corresponding type declarations.
4:12:51 PM: 04  import BaseLayout from '@/layouts/BaseLayout.astro'
4:12:51 PM:                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4:12:51 PM: 05  import { Icon } from 'astro-icon'
4:12:51 PM: 08:12:51 AM [diagnostics] 
4:12:51 PM:  /opt/build/repo/src/pages/posts/[...slug].astro:4:24 Error: Cannot find module '@/layouts/BaseLayout.astro' or its corresponding type declarations.
4:12:51 PM: 04  import BaseLayout from '@/layouts/BaseLayout.astro'
4:12:51 PM:                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4:12:51 PM: 08:12:51 AM [diagnostics] Result (7 files): 
4:12:51 PM: - 3 errors
4:12:51 PM: - 0 warnings
4:12:51 PM: - 0 hints
4:12:51 PM: 
4:12:51 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
4:12:51 PM: ​
4:12:51 PM: "build.command" failed                                        
4:12:51 PM: ────────────────────────────────────────────────────────────────
4:12:51 PM: ​
4:12:51 PM:   Error message
4:12:51 PM:   Command failed with exit code 1: pnpm build (https://ntl.fyi/exit-code-1)
4:12:51 PM: ​
4:12:51 PM:   Error location
4:12:51 PM:   In build.command from netlify.toml:
4:12:51 PM:   pnpm build
4:12:51 PM: ​
4:12:51 PM:   Resolved config
4:12:51 PM:   build:
4:12:51 PM:     command: pnpm build
4:12:51 PM:     commandOrigin: config
4:12:51 PM:     publish: /opt/build/repo/dist
4:12:51 PM:     publishOrigin: config
4:12:52 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
4:12:52 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
4:12:52 PM: Failing build: Failed to build site
4:12:53 PM: Finished processing build request in 23.264s

### Link to Minimal Reproducible Example

https://github.com/chenxi24/chenxi.me/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Your file name casing is incorrect: https://github.com/chenxi24/chenxi.me/blob/dev/src/layouts/baseLayout.astro. It should be `BaseLayout.astro`. It works for you locally because Windows has a case-insensitive file system, whereas most CI pipelines using Linux is case-sensitive.
