### ISSUE TITLE
Astro.locals type errors not cleared from VSCode with proper env.d.ts

### ISSUE THREAD

**Issue by gkatsanos** [withastro/astro#7394]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

![image](https://github.com/withastro/astro/assets/1768834/30c1949a-14de-4fff-ba9f-54936d2f7e0e)

```ts
/// <reference types="astro/client" />
declare interface User {
  products_admin: boolean
  agency: boolean
  email: string
  firstname: string
  lastname: string
  salutation: string
  remember_me: boolean
  roles: string[]
  user_id: string
  company_ids: string
  session_id: string
}

declare global {
  namespace App {
    interface Locals {
      brand: string
      userAuth: User
      referrer: string
      url: string
    }
  }
}
```

```js
// middleware
import { getUserAuth } from "@store/auth"
import { USER_INFO_COOKIE_KEY } from "@constants/auth"

export function onRequest(context, next) {
  const forwardedHost = context?.request?.headers.get("x-forwarded-host")
  const url = new URL(context.request.url)

  if (forwardedHost?.includes("europages")) {
    context.locals.brand = "ep"
  } else {
    context.locals.brand = "wlw"
  }
  context.locals.url = url.pathname
  context.locals.referrer = url.origin

  if (context.cookies.has(USER_INFO_COOKIE_KEY)) {
    const cookie = context.cookies.get(USER_INFO_COOKIE_KEY)
    context.locals.userAuth = getUserAuth(cookie)
  }

  return next()
}
```

```
// tsconfig.json
{
  "extends": "astro/tsconfigs/base",
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": ".",
    "paths": {
      "@assets/*": ["src/assets/*"],
      "@components/*": ["src/components/*"],
      "@pages/*": ["src/pages/*"],
      "@helpers/*": ["src/helpers/*"],
      "@layouts/*": ["src/layouts/*"],
      "@constants/*": ["src/constants/*"],
      "@store/*": ["src/store/*"],
      "@i18n/*": ["src/i18n/*"]
    },
    "types": ["@astrojs/image/client"],
    "jsx": "preserve",
    "plugins": [
      {
        "name": "@astrojs/ts-plugin"
      }
    ]
  }
}

```
### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
The documentation is old, that's on us.

That's how you should type the `Locals`

```ts
declare namespace App {
	interface Locals {
		user: {
			name: string;
			surname: string;
		};
	}
}
```

**Comment by gkatsanos** [comment]
I am willing to make a PR to update it but I assume you guys have bundled a ton of updates with docs already?

(would be cool if docs would be updated together)

**Comment by whoiscarlo** [comment]
I'm still running into this issue in **Astro 3.5.7** in Typescript. Anytime I try to set a new property on `locals`, I get an error from VS Code saying: `Property '[insert_name]' does not exist on type 'Locals'.ts(2339)`

**Comment by Jaszkowic** [comment]
I am experiencing the same issue, even after updating `.env.d.ts` as recommended here: https://github.com/withastro/astro/issues/7394#issuecomment-1592728591

> Property '...' does not exist on type 'Locals'.ts(2339)

**Astro 3.6.0**

**Comment by san4d** [comment]
I'm also experiencing this issue on Astro 3.6.4. I restarted VS code as well.

**Comment by DnzzL** [comment]
Still the issue with astro 4.1.3.
Any news ?

**Comment by ematipico** [comment]
Our examples/ folder has an example where locals are typed, and we run TypeScript to make sure it's ok.

If you have errors, is it possible that you changed some TypeScript configuration?

**Comment by san4d** [comment]
This ended up being more about how TypeScript types behave within a namespace. This is noticeable when you're trying to import a custom type. Here's the solution:

Suppose you have a type called `SessionData` exported from `@session` (a path alias, but this also holds for relative paths). You can get the types to behave as expected with a dynamic import:
```typescript
// in env.d.ts
declare namespace App {
	interface Locals {
            sessionData: import('@session').SessionData;
	}
}
```

**Comment by DnzzL** [comment]
> This ended up being more about how TypeScript types behave within a namespace. This is noticeable when you're trying to import a custom type. Here's the solution:
> 
> Suppose you have a type called `SessionData` exported from `@session` (a path alias, but this also holds for relative paths). You can get the types to behave as expected with a dynamic import:
> 
> ```ts
> // in env.d.ts
> declare namespace App {
> 	interface Locals {
>             sessionData: import('@session').SessionData;
> 	}
> }
> ```

Thank you that was it :pray: 

Crazy I lost time on this :joy:

**Comment by svaraborut** [comment]
Im working with `@cloudflare`  (ide Webstorm 2023.2.1)

Versions:

```txt
"astro": "^4.2.6",
 "@astrojs/cloudflare": "^9.0.0",
```

The only way it works is using global and avoiding the `Env` name used in the documentation

```ts
/// <reference types="astro/client" />
import type { AdvancedRuntime } from '@astrojs/cloudflare'
import type { D1Database, R2Bucket } from '@cloudflare/workers-types'

// Calling it Env clashes with the @cloudflare type
type AppEnv = {
    // Bindings
    DB: D1Database
    R2_CDN: R2Bucket
    // Secrets
    AUTH_SECRET: string
}

declare global {
    namespace App {
        interface Locals extends AdvancedRuntime<AppEnv> {
        }
    }
}
```

**Comment by johnmw** [comment]
Thank you @san4d , that solved my problem. An additional note in case it helps anyone new to Typescript: *none* of my Locals types worked in VS Code until I removed *all* my "import X from Y" lines in env.d.ts file and replaced them with @san4d 's solution.

For example, something like this didn't work for me (including the testTypeScript function):

```TS
import { SupabaseClient } from '@supabase/supabase-js';

declare namespace App {
  interface Locals {    
      testTypeScript: () => string;
      supabase: SupabaseClient;
  }
}
```

However this did work: 

```TS
declare namespace App {
  interface Locals { 
      testTypeScript: () => string;
      supabase: import('@supabase/supabase-js').SupabaseClient;
  }
}
```

**Comment by ben-xD** [comment]
This seems broken again. Following the examples above don't work.

> Our examples/ folder has an example where locals are typed, and we run TypeScript to make sure it's ok.
> 
> If you have errors, is it possible that you changed some TypeScript configuration?

@ematipico, you referred to examples, but I cannot find any examples in this repo. I see 2 instances of `interface Locals {}` (they're empty). Is there another repo or something I don't know about?

**Comment by fearandesire** [comment]
Here's what worked for me:
```
/// <reference types="astro/client" />
declare global {
  namespace App {
    interface Locals extends Record<string, any> {
      discordId: string | null;
      discordUsername: string | null;
      userIsLoggedIn: boolean;
      userData: DbServiceResponse | null;
      userDetails: DbServiceResponse | null;
    }
  }
}

```
I'm using Astro 4.10.8

@ben-xD

**Comment by frudman** [comment]
just as FYI, had similar issue as per above for Astro v4.15.4 (sep 13, 2024)

What worked for me was as per prev response: go back to using `declare global { namespace App {...} }`
- note `declare global` (supposedly not needed but was failing for me without)
- also note `namespace App` (not `declare namespace App`)

**Comment by james-pre** [comment]
I'm still getting this issue with `astro@4.15.9` and `@astrojs/cloudflare@11.1.0`, regardless of dynamic/static imports.

**Comment by adworacz** [comment]
> just as FYI, had similar issue as per above for Astro v4.15.4 (sept 12, 2024)
> 
> What worked for me was as per prev response: go back to using `declare global { namespace App {...} }`
> 
>     * note `declare global` (supposedly not needed but was failing for me without)
> 
>     * also note `namespace App` (not `declare namespace App`)
> 
> 
> Also needed to re-add `declare global` for global vars, unlike current docs (as of sept 12):
> 
>     * [ref to modifying globalThis](https://docs.astro.build/en/guides/typescript/#extending-window-and-globalthis)
> 
>     * [ref to enhancing Locals](https://docs.astro.build/en/guides/middleware/#middleware-types)
> 
> 
> Are docs going to be updated or is prior behavior going to be re-implemented?

I'm experiencing this exact same thing, and only got it working after going with the the `declare global { namespace App { ... }} ` approach.

Either the docs need updating or something is actually broken in Astro right now.

**Comment by JacobNWolf** [comment]
Tried all the fixes from above, but here's what worked for me, personally using Lucia Auth.

```
// in env.d.ts

/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />

import type { AstroGlobal } from 'astro';

declare module 'astro' {
    interface AstroGlobal {
        locals: App.Locals;
    }
}

declare global {
    namespace App {
        interface Locals {
            user: {
                id: string;
            } | null;
            session: {
                id: string;
                userId: string;
            } | null;
        }
    }
}
```

**Comment by daniel-locatelli** [comment]
My project in Astro 4.16.13 (23 Nov 2024) was working fine as per middleware docs, until I renamed a variable using VS Code F2
Rename Symbol command. After this I tried adding another local and it was not working anymore.
Not sure if it is related though.

**Comment by datner** [comment]
can we finally add this to the docs? 🙏🏻

**Comment by HelloooLucas** [comment]
Hey, thanks for all the answers and solutions!

I ran into the same issue and what fixed it for me was wrapping the `App` namespace inside a `global` declaration:
```typescript
import type { User } from "@supabase/supabase-js";

declare global {
  namespace App {
    interface Locals {
      user: User | null;
    }
  }
}
```

Would be nice to add it to the docs! 😃
