### ISSUE TITLE
All files are served in development mode

### ISSUE THREAD

**Issue by kireerik** [withastro/astro#7400]
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

some examples:

`https://githubz6jvzsvmbpaf-q4sx-1vxuby5t--3000--a12d8c69.local-credentialless.webcontainer.io/`
- [**package.json**](https://githubz6jvzsvmbpaf-q4sx-1vxuby5t--3000--a12d8c69.local-credentialless.webcontainer.io/package.json)

- [**src/pages/index.astro**](https://githubz6jvzsvmbpaf-q4sx-1vxuby5t--3000--a12d8c69.local-credentialless.webcontainer.io/src/pages/index.astro)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-z6jvzs-vmbpaf?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is an intentional behaviour from Vite.

**Comment by kireerik** [comment]
I see and is this also an intentional Astro behavior?

**Comment by bluwy** [comment]
Yeah
