### ISSUE TITLE
Setting the compressHTML option has no effect

### ISSUE THREAD

**Issue by J-env** [withastro/astro#7401]
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm,pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

development:
<img width="1543" alt="image" src="https://github.com/withastro/astro/assets/25259920/2a71108e-2db4-4d92-b6fe-04581e7ccbb0">

build:
<img width="1323" alt="image" src="https://github.com/withastro/astro/assets/25259920/ef17d7ea-a099-4af4-bce2-6bdff96249a7">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sdeict-rftist?file=astro.config.mjs&file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I think this is intended, to compress the HTML only during the build step.

**Comment by matthewp** [comment]
No, it should be happening in dev as well.

**Comment by proyb6** [comment]
Can consolidate the fix with
https://github.com/withastro/astro/issues/7333

**Comment by natemoo-re** [comment]
OK, I was able to track this down! Fix incoming from the compiler side.

For context, our compiler is pretty defensive about preserving whitespace, even when `compressHTML` is enabled. In this case, we were (incorrectly) preserving the newlines here, but if there is both a _leading_ and _trailing_ newline, we should strip them.

**Comment by wackbyte** [comment]
The original behavior is actually correct, as
```html
<span>foo</span>
bar
<span>baz</span>
```
![image](https://github.com/withastro/astro/assets/29505620/5c62411b-4352-4358-9819-f2a899e39892)
is **not** the same as
```html
<span>foo</span>bar<span>baz</span>
```
![image](https://github.com/withastro/astro/assets/29505620/468b49a9-6aaa-4a9b-828d-9b5fb5c68398)
because the latter lacks any whitespace between each element.

If you really want no space between consecutive text elements, you must remove the whitespace in your source code.

**Comment by proyb6** [comment]
As this issue is close, you can open new issue if you encounter possible bugs.
