### ISSUE TITLE
Svelte with Unocss - returned here is merged into Astro Config

### ISSUE THREAD

**Issue by Scouterdev** [withastro/astro#7403]
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

firefox

### Describe the Bug

I'm using **@astrojs/svelte** along with **unocss/astro** in my projects. I would like you to include **unocss/astro** in your **@astrojs/svelte** module because I'm currently getting an error when running both models together.

```
error   Cannot read properties of undefined (reading 'postcss')
/@astrojs+svelte@1.0.2_@babel+core@7.22.5_postcss@8.4.24_svelte@3.55.1_typescript@4.9.5_vite@3.2.5/node_modules/@astrojs/svelte/dist/index.js:66:41
```

```
isDev: command === "dev",
postcssConfig: config.style.postcss
TypeError: Cannot read properties of undefined (reading 'postcss')
```

**Comment by bluwy** [comment]
I'm guessing you need to upgrade `@astrojs/svelte`, it shows you're using v1.0.2. It's currently v3.
