### ISSUE TITLE
dev and prod servers are crashing if Astro component that is passed as a slot inside Solid component throws an error 

### ISSUE THREAD

**Issue by alexander-lozovsky** [withastro/astro#7405]
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

There's a case when Astro doesn't handle errors properly, which causes dev and prod servers crashing:

```
---
import Layout from "../layouts/Layout.astro";
import Card from "../components/Card.astro";

import { Wrapper } from "../components/Wrapper";
---

<Layout title="Welcome to Astro.">
  <Wrapper>
    <Card
      href="https://docs.astro.build/"
      title="Documentation"
      body="Learn how Astro works and explore the official API docs."
    />
  </Wrapper>
</Layout>

```

- `Layout` has some async call under the hood
- `Wrapper` is a Solid component
- `Card` component it throwing an error inside the frontmatter

With the given composition, both dev and prod servers are crashing, instead of catching the error and keep running

### Link to Minimal Reproducible Example

https://github.com/alexander-lozovsky/astro-solid-server-crash-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jacobdalamb** [comment]
dev and prod no longer crash as of latest versions.
