### ISSUE TITLE
`CollectionDoesNotExistError` on fresh install of "Astro Starter Kit: Blog"

### ISSUE THREAD

**Issue by hirasso** [withastro/astro#7406]
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I installed the "Starter Kit: Blog" from https://github.com/withastro/astro/tree/main/examples/blog

When I run `npm run dev`, the dev server starts and I can visit the site on `localhost:3000`. The home (`/`) and `/about/` pages work as expected, but on the `/blog/` page, I am getting a `CollectionDoesNotExistError`:

![image](https://github.com/withastro/astro/assets/869813/1c6be975-535a-4ea5-8cc6-11b4a90bdd92)

Any idea what's happening here? I haven't changed anything, just `npm create astro@latest -- --template blog` and said "yes" to all questions. The weird thing is that the [demo on stackblitz](https://stackblitz.com/github/withastro/astro/tree/latest/examples/blog?file=README.md) works just fine...

### Link to Minimal Reproducible Example

https://github.com/hirasso/astro-starter-kit-blog

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by hirasso** [comment]
I have found the issue, and it's a weird one 👽 

This is the path I had put my astro install in:

```
/Users/<me>/Documents/__test/my-astro-install
``` 

Notice the folder `/__test/` there? The leading underscores seem to break something in astro! When I remove them, like so:

```
/Users/<me>/Documents/test/my-astro-install
``` 

...the content collections are starting to work.

Out of curiosity I also tested it with only one underscore (`/_test/`), that also breaks the content collections.

**Comment by alexzub** [comment]
@hirasso wow, thank you for posting the solution.

I've been fighting with this error for the last 2 days. Sure enough, a folder named "_Projects" was the culprit! 
Renamed to "-Projects" instead (which broke a number of other things for me, but it is what it is), and it's now working.

Definitely a bug, and one that would be an incredibly difficult one to trouble shoot for most people.

**Comment by bluwy** [comment]
I'm guessing the bug is here:

https://github.com/withastro/astro/blob/d2020c29cf285e699f92143a70ffa30a85122bb4/packages/astro/src/content/utils.ts#L288-L297

We do only check for the underscore within the project root (`.replace` handling), but maybe the `pathname` didn't match.

**Comment by hilmanski** [comment]
happen to me as well.
I have a normal named folder. (no underscore or - )

this error shows up
![Screen Shot 2023-06-23 at 08 01 20](https://github.com/withastro/astro/assets/4522467/d99c4afc-03fe-4f6c-b839-7b4ce24ca71d)

I already have that folder

![Screen Shot 2023-06-23 at 08 01 14](https://github.com/withastro/astro/assets/4522467/23eeb5f1-c545-4180-a84b-e0efc75dbd02)

**Comment by hirasso** [comment]
> I'm guessing the bug is here:
> 
> https://github.com/withastro/astro/blob/d2020c29cf285e699f92143a70ffa30a85122bb4/packages/astro/src/content/utils.ts#L288-L297
> 
> We do only check for the underscore within the project root (`.replace` handling), but maybe the `pathname` didn't match.

I just deactivated this function and ran the test again – turns out it's not related to the described bug. This is what I did:

- removed the first `if` clause in `getEntryType()` entirely
- ran `pnpm --filter astro run build`
- ran `pnpm --filter @example/blog run dev`
- Visited http://localhost:3000/blog

Got the same error

**Comment by hirasso** [comment]
It seems to be related to this `globWithUnderscoresIgnored`: 

https://github.com/withastro/astro/blob/main/packages/astro/src/content/vite-plugin-content-virtual-mod.ts#L210-L213

**Comment by hirasso** [comment]
Ran a test. This is the current output from `globWithUnderscoresIgnored`:

```js
[
  '/src/content//**/*{.md,.mdx}',
  '!**/_*/**{.md,.mdx}',
  '!**/_*{.md,.mdx}'
]
```

The problem is that the negation patterns are being matched on the full path. Changed the function to this:

```diff
function globWithUnderscoresIgnored(relContentDir: string, exts: string[]): string[] {
	const extGlob = getExtGlob(exts);
-       return [`${relContentDir}/**/*${extGlob}`, `!**/_*/**${extGlob}`, `!**/_*${extGlob}`]; 
+	return [`${relContentDir}**/*${extGlob}`, `!${relContentDir}_*/**${extGlob}`, `!${relContentDir}_*${extGlob}`];
}
```

Should I create a PR?
