### ISSUE TITLE
Regression: @astrojs/vercel/edge not compatible with imageService

### ISSUE THREAD

**Issue by alexanderniebuhr** [withastro/astro#7407]
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

> Hi, I am trying to enable vercel's imageService, which is said to be supported on the edge in the @astrojs/vercel docs ([link](https://docs.astro.build/en/guides/integrations-guide/vercel/#imageservice)). To do that, I am required to enable experimental: { assets: true }, however by doing that I think that some node packages get imported into the build and that causes it to fail because of the edge runtime

Regression. https://github.com/withastro/astro/issues/7057 seems to be back.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/verce-edge-image-service-2xuprn?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Tried to figure out where the nodejs modules are imported, and it's surprisingly hard. I can't seem to find where in the import chain it's being used. I made this Vite plugin to identify what files are included in a chunk, but it's still as hard:

```js
{
  name: 'track',
  renderChunk(code, chunk) {
    console.log(chunk)
  }
}
```

Adding this in the `astro:build:setup` hook of the vercel integration didn't help either:

```js
vite.build ||= {};
vite.build.rollupOptions ||= {};
vite.build.rollupOptions.output ||= {};
// Disable optimization as the output is bundled by esbuild, which nullifies the benefit
if (Array.isArray(vite.build.rollupOptions.output)) {
	vite.build.rollupOptions.output.forEach((output) => {
		output.hoistTransitiveImports = false;
	});
} else {
	vite.build.rollupOptions.output.hoistTransitiveImports = false;
}
```
