### ISSUE TITLE
Images (astro:assets) are not rendered (got 404) on SSR pages on hybrid build with node adapter

### ISSUE THREAD

**Issue by bmenant** [withastro/astro#7415]
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

Using Node adapter, Experimental astro:assets api does not work as expected with server-side-rendered pages on all build/running mode:

On dev mode, images are properly being rendered and served. :ok: 
On server mode, images are properly being rendered and served . :ok: 
On hybrid mode, images are not served (requests ends up with a 404 Not Found code) when imported from explicit ssr pages (not prerendered). 💥
On hybrid mode, images imported from prerendered pages are prerendered and served. :ok:

~~It looks like the `_image` endpoint is not included or not properly included in hybrid builds, so images requested to be rendered dynamically ends up with a 404 Not Found page.~~

Here is an example of such page: https://github.com/bmenant/hybrid-astro-assets-issue/blob/main/src/pages/ssr.astro

Notes:
- How images are imported does not matter (top-level import, dynamic import, collection image reference).
- The node adapter mode does not matter (Middleware or Standalone)
- The image service in use does not matter (Sharp or Squoosh)

### Link to Minimal Reproducible Example

https://github.com/bmenant/hybrid-astro-assets-issue/tree/main

### Participation

- [x] I am willing to submit a pull request for this issue. Done!

~~... but I have very little idea where I should have a look to debug this.~~

**Comment by bmenant** [comment]
After some REPL on a single image URL, I could find out why SSR image requests got shortcut. 
As a matter of fact, when the app looks for a route match, in astro/core/app, the `match()` function returns `undefined` (as it was a prerendered page or asset while it isn’t).

It happens [over here](https://github.com/withastro/astro/blob/main/packages/astro/src/core/app/index.ts#LL100C1-L103C4) at first:
```typescript
		// ignore requests matching public assets
		if (this.#manifest.assets.has(url.pathname)) {
			return undefined;
		}
```
For `this.#manifest.assets` includes `"/_image"`, which happens to be the pathname of images to be server-side-rendered. In a server mode build, this entry is not appended to the manifest’s assets set; the above shortcut condition is not met and the route-matching proceeds.

Then, if we comment the above shortcut statement, it happens again [over there](https://github.com/withastro/astro/blob/main/packages/astro/src/core/app/index.ts#L108):
```typescript
			if (routeData.prerender) return undefined;
```
For `routeData.prerender` is set to `true` on images to be server-side-rendered, where it should be `false` IMHO. 

If we comment the two above shortcut statements, the image is properly rendered and streamed to the browser.

Now, I’ll try to find out why the manifest ends up with `/_image` in its assets list and why the `/_image` route is defined as prerendered.

**Comment by bmenant** [comment]
Work in progress here: https://github.com/bmenant/astro/tree/fix/astro-assets-hybrid-ssr

**Comment by do-web** [comment]
I have the same error on SSR page got 404 with the latest version.

**Comment by doidor** [comment]
This issue is still reproducing in Astro v3.1.1 with Node v18

**Comment by xxxcodeingxxx** [comment]
Astro v4.0.3 doing same thing! I've never experienced this until now but all images are getting 404.

**Comment by agrattan0820** [comment]
Experiencing this error with Astro 4.5.3 on Vercel with the Vercel adapter.

**Comment by flaviort** [comment]
Same here with Vercel adapter

**Comment by mark-mybaggage** [comment]
I'm having the same issue using astro 4.11.5 with the cloudflare serverless adapter (11.0.1).  My node version is 21.5

**Comment by mark-mybaggage** [comment]
For me this was due to a change in defaults for the cloudflare serverless adapter.  The documentation has now been updated and setting the imageService to passthrough resolves the issue for me.

**Comment by glenatformat** [comment]
Enabling the imageService in the Vercel adapter works (Astro 4.6.1, Vercel Apdater: 7.5.4)
```
 adapter: vercel({
    imageService: true,
  }),
  ```
