### ISSUE TITLE
Pass a process.env var from server to client

### ISSUE THREAD

**Issue by gkatsanos** [withastro/astro#7416]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I find it increasingly problematic to pass server side variables to the client side scripts - beyond the simple use case. Example: 
Implement a Google Analytics pageView event that needs a `process.env` variable to initialize the main GA class wrapper:

```js
// tracking.js
// this guy needs to be client-side, but he has no idea about `process.env`
import { GoogleAnalytics } from "@visable-dev/tracking"

export const googleAnalytics = new GoogleAnalytics({
  trackingEnv: process.env.TRACKING_ENV || "development",
})
``` 

```js
// pageView.js
import { googleAnalytics } from "@helpers/tracking"

googleAnalytics.trackPageView({
  virtualPageTitle: "requestForQuote",
  trafficSource: trafficSourceType,
  wlwUserId: userId,
  wlwUserRoles: userRoles,
  originalUrl: originalUrl,
  referrer: document.referrer,
})
```

```html
---
import AtGlance from "@components/AtGlance.astro"
import FAQSection from "@components/FAQSection.astro"
import Hero from "@components/Hero.astro"
import HowItWorks from "@components/HowItWorks.astro"
import Testimonials from "@components/Testimonials.astro"
import Layout from "@layouts/Layout.astro"
---

<Layout>
  stuff
</Layout>

<script src="@scripts/pageview.js"></script>
```

I am thinking of an RFC where there's a file which can make variables available to the entire application.. 
the limitation of `.env` is one can't use dynamic variables. So we need something a bit more powerful.

Just as an idea, Nuxt handles this by providing an object of vars called: 

```js
  publicRuntimeConfig: {
    branchName: process.env.REPO_BRANCH,
    stage: process.env.STAGE || 'development',
      process.env.API_EXPLORE_BACKEND_URL ||
      'https://explore-backend.internal.wlw-1.staging.xxxxx.com/explore_backend',
    apiExplorePublicUrl: process.env.PUBLIC_API_URL
      ? `${process.env.PUBLIC_API_URL}/explore`
      : 'https://api.staging.xxx.io/explore',
    trackingEnv: process.env.TRACKING_ENV || 'development',
  },
```

I would be also OK to use `globalThis` for this but where would one put this?
### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Since this isn't a real issue (things seem to be working as expected), I suggest opening a **discussion** instead. From there, things can be discussed and eventually become a feature.

**Comment by gkatsanos** [comment]
Would it be possible for you @ematipico to move it ?
