### ISSUE TITLE
📘 DOC: Section "Component Publishing" needs improvements

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#743]
I feel like we should 
- specify a recommended way to scaffold testing for the components
- how to specify `astro` as a peer dependency for the component
- and maybe there could be a `npm init create-astro-component`?
- maybe also a link to the npm publishing guide + a recommendation on how to name the packages / namespace them
- show the source of the `Bold.astro` or `Capitalize.astro` as well?
- how do you access `<slot/>` as a prop so you can do processing like `<Markdown/>`?

**Comment by FredKSchott** [comment]
@natemoo-re this would be great for you to tackle as a part of your theme work
