### ISSUE TITLE
FailedToLoadModuleSSR

### ISSUE THREAD

**Issue by wanghaisheng** [withastro/astro#7437]
### What version of `astro` are you using?

2.6.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

windows

### What browser are you using?

edge

### Describe the Bug

![image](https://github.com/withastro/astro/assets/2363295/4b01edf8-fe85-47a3-9995-f8c097adb457)

as you can see ,use ls  we can see the file in this folder,but when I run npm run dev, it tells not found 
```
FailedToLoadModuleSSR
Could not import file.
Could not import ./LandingSectionText.astro.jsx.
[See Docs Reference](https://docs.astro.build/en/reference/errors/failed-to-load-module-ssr/)
This is often caused by a typo in the import path. Please make sure the file exists.
Stack Trace
Error: Failed to load url ./LandingSectionText.astro.jsx (resolved id: ./LandingSectionText.astro.jsx) in D:/Download/audio-visual/saas/tiktoka/idea-to-action-cycle/src/pages/_components/SellingPoints.astro. Does the file exist?
    at loadAndTransform (file:///D:/Download/audio-visual/saas/tiktoka/idea-to-action-cycle/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:533
```

### What's the expected result?

should work

### Link to Minimal Reproducible Example

https://github.com/wanghaisheng/idea-to-action-cycle

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
As the error eluded to, [this import](https://github.com/wanghaisheng/idea-to-action-cycle/blob/f5fd74bbc74e8722d70aa246fab049b122728bd6/src/pages/_components/SellingPoints.astro#L3) doesn't exist.
