### ISSUE TITLE
Can't pass in generic Arguments

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#7441]
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I have recently found out that when you try to pass in a generic Argument in Astro. It gives me an error.

```jsx
<GenericCmp<string> x="ok" />
```
 
```shell
 string is not defined
  File:
    /home/projects/withastro-astro-jfnmrp/src/pages/index.astro:26:106
  Stacktrace:
ReferenceError: string is not defined
```

### What's the expected result?

I expected to pass in a generic argument into the component then it would work. 

```jsx
<CMP<number> prop={2}  />
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-jfnmrp?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by louiss0** [comment]
When I tried to do this in VSCode  it seemed to work but it did this.

```jsx
<Generic<string>>
</Generic<string>>

```

 I think the vs code Astro extension is what did this.
I think you should use VSCode without Using the AutoComplete Tag or the Auto Close Tag extension.

**Comment by natemoo-re** [comment]
```jsx
<GenericCmp<string> x="ok" />
```

This seems to be a TypeScript feature introduced in [TS 2.9](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#generic-type-arguments-in-jsx-elements).

Astro syntax is similar to JSX, but it does diverge in certain areas. I don't think we are planning to support this syntax, so I'm going to close this issue. Feel free to open a discussion for this feature request in our [Roadmap repo](https://github.com/withastro/roadmap/discussions).
