### ISSUE TITLE
Internal server error (ExpectedImage) with astro:assets and node adapter when a same image is imported on a prerendered page and a ssr page

### ISSUE THREAD

**Issue by bmenant** [withastro/astro#7443]
### What version of `astro` are you using?

2.6.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

I’ve got the following internal server error on a ssr page on a recent build:

> ExpectedImage: Expected `src` property to be either an ESM imported image or a string with the path of a remote image. Received `undefined`.

That page had not been changed prior to the build, and used to work just fine before. Assets were not changed either.
They were imported using Vite’s  `import.meta.glob('~/assets/images/*.jpg')`.

The change introduced in the build was the addition of a new prerendered page. In that page, one asset was imported, possibly conflicting other imports (since this asset is included in the above glob):

```typescript
import image from '~/assets/images/img1.jpg'; // causes troubles on the other page
```

Removing that import solved the server error on the other page. A workaround I found is to import the asset using a dynamic import:

```typescript
const image = (await import('~/assets/images/img1.jpg')).default; // does not crash the other page
```

**Note:** the issue does **not** occur when running astro in dev mode (`npm run dev`).

### What's the expected result?

No internal server error: we should be able to import assets normally in both prerendered and ssr pages and combine the different options to import assets with Vite. 

### Link to Minimal Reproducible Example

https://github.com/bmenant/hybrid-astro-assets-issue/tree/issue-7443

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bmenant** [comment]
@bluwy I have created a minimal reproduction repo here: https://github.com/bmenant/hybrid-astro-assets-issue/tree/issue-7443

Additional note: Trying different cases, I found that if the exact same asset is being imported statically on another SSR page, then, the SSR page with dynamic import will run fine.

**Comment by bmenant** [comment]
IMHO, if it’s not easily fixable, the workarounds (i.e. to align static/dynamic imports on SSR and Prerendered pages) are just fine if documented as a known limitation. Especially because the error goes unseen while running in dev mode, and there ain’t no warning while running build. One is likely to push failing code live in production.

I’m not willing to submit a pull request over here since I’m moving all out of rendering assets on SSR pages (slow and high server cpu/memory load).

**Comment by JerryWu1234** [comment]
let me take a look

**Comment by Princesseuh** [comment]
Tried the reproduction on the latest version of Astro (after updating a few outdated things, like the aliases and the config) and everything worked just fine in both dev and prod. 

We've updated how the endpoints work a few times, so I assume we fixed this issue by accident!
