### ISSUE TITLE
`trailingSlash: "always"` break on Vercel

### ISSUE THREAD

**Issue by anasrar** [withastro/astro#7444]
### What version of `astro` are you using?

2.6.6

### Are you using an SSR adapter? If so, which one?

@astrojs/vercel@3.5.0

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

when `trailingSlash: "always"` is presented in config, access `/` will continuously redirect to `/`. Resulting infinite redirect when deployed on Vercel.

### What's the expected result?

See basics template on `/`.

### Link to Minimal Reproducible Example

https://github.com/anasrar/astro-vercel-trailingslash

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
Are you sure about this?
https://github.com/rishi-raj-jain/rishi.app/blob/main/src/routes/%2Blayout.ts doesn't break on rishi.app.

**Comment by rishi-raj-jain** [comment]
That was SvelteKit, hence deleted. I love both the frameworks.

**Comment by artt** [comment]
@bluwy seems like this is still an issue? What do you use for your setup now?
https://github.com/withastro/adapters/issues/418
