### ISSUE TITLE
💡 RFC: Provide a way to test Astro components, perhaps by publishing the `astro` test setup

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#745]
### Background & Motivation

I want to be able to setup tests for https://github.com/jasikpark/astro-katex to make sure it works correctly, but I have not clue how to do that without either adding it to `astro/packages/astro/components/KaTeX.astro` and using the current monorepo testing rig, or by manually testing it.

### Possible solutions
- Publish the helpers and whatnot as an astro package 🤔 or allow copying of the setup for the moment 
### Risks, downsides, and/or tradeoffs
- Seems like a lot of support to add, but testing astro components seems like a worthy goal.
### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by L1lith** [comment]
I'd suggest you take a look at my library [here](https://github.com/L1lith/Sandhands). You need to implement a `.npmignore` file to specify what not to upload to NPM.

**Comment by tony-sull** [comment]
I've been meaning to try using [uvu + puppeteer](https://github.com/lukeed/uvu/tree/master/examples/puppeteer) to test an Astro project

I'd be a happy camper if it can quickly testing the rendered DOM output and unit testing compiled framework components, bonus points if I could test interacting with the components after they are hydrated in the DOM for integration (or E2E?) tests

**Comment by FredKSchott** [comment]
@jasikpark added `rfc-discuss` label to make sure we discuss next week! But I can say that overall the team is aligned on having better testing support and better component development support in general, and would be interested in a proposal for what that could look like.

**Comment by jonathantneal** [comment]
Hey everyone! **This RFC is still accepted**, and it has been moved to https://github.com/withastro/rfcs/blob/main/active-rfcs/add-test-tool-for-astro-components.md

In an effort to improve our RFC process, we made some changes to better organize things, which include a [dedicated RFC repository](https://github.com/withastro/rfcs#readme).

**Comment by jasikpark** [comment]
updated rfc link: https://github.com/withastro/rfcs/blob/main/active-rfcs/0002-add-test-tool-for-astro-components.md
