### ISSUE TITLE
@astro/image

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [withastro/astro#7453]
### What version of `astro` are you using?

0.17.1

### Are you using an SSR adapter? If so, which one?

no 

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

edge

### Describe the Bug

When i update this paquage to 0.17.1 i get this error to my images

```js
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/home/manjaro/DEV/uno%20test/marina%20copie/public/assets/images/slider-1.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/manjaro/DEV/uno%20test/marina%20copie/public/assets/images/slider-1.jpg'
}

Node.js v19.3.0
❌ [start] Failed with exit status 1
```

### What's the expected result?

show images on dev mode

### Link to Minimal Reproducible Example

ww.a.com

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Please ask for support at https://astro.build/chat. If you think this is a bug, please provide a repro
