### ISSUE TITLE
'Assets / client-image' hijacks all images, prevents 'normal' importing for use in node scripts.

### ISSUE THREAD

**Issue by xriter** [withastro/astro#7455]
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

When having
```
experimental: {
  assets: true,
},
```
all image imports seem to be hijacked by this module. This prevents business logic in nodejs to import images the 'normal way', and have Vite bundle them in the build.

So, when I do this:
```
import myAsset from "./somefancystuff/images/myAsset.png";
```
`myAsset` will be transformed into this `ImageMetadata` object (containing the `src` to the optimised version and all), making it unusable for some logic that depends on the 'default behaviour'.

Is there a way to disable the Assets module for certain folders?
In the end, all I need is to be able to import the file like this, and then have Vite bundle it in the final build.

### What's the expected result?

To be able to also import images the 'default way'.

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
No there isn't a way to disable in some folders, the Vite/Rollup plugin doesn't allow that as a file/identifier can only be transformed to a single shape. When enabling `experimental.assets`, it will mean Astro taking over how assets are loaded in general.
