### ISSUE TITLE
astro/rss should allow setting `language` for channel

### ISSUE THREAD

**Issue by stefanprobst** [withastro/astro#7461]
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

firefox

### Describe the Bug

`@astro/rss` currently does not allow setting the `language` of a channel. see https://www.rssboard.org/rss-specification#optionalChannelElements

### What's the expected result?

`@astro/rss` allows setting a channel's language

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You can with the `customData` option: https://docs.astro.build/en/guides/rss/

```js
export function get(context) {
  return rss({
    // (optional) inject custom xml
    customData: `<language>en-us</language>`,
  });
}
```
