### ISSUE TITLE
Strange naming of css files

### ISSUE THREAD

**Issue by niklasgrewe** [withastro/astro#7469]
### What version of `astro` are you using?

2.6.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

i use a `global.css` file in my layout `base.astro` like this:

```html
---
import '../styles/global.css'
---

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <slot></slot>
</body>
</html>
```
i use this `base` layout in my two pages `index.astro` and `about.astro` like this:

```html
---
import Base from '../layouts/Base.astro'
---

<Base>
  <h1>Home page</h1>
</Base>

<style>
  h1 {
    color: red;
  }
</style>
```
```html
---
import Base from '../layouts/Base.astro'
---

<Base>
  <h1>About page</h1>
</Base>

<style>
  h1 {
    color: black;
  }
</style>
```
when i build my simple site, i get the following css files:

- `index.[hash].css` - homepage styles
- `about.[hash].css` - styles from `global.css` file, imported in `base.astro`
- `about.[hash].css` - about page styles

it is a bit strange that i have two `about.[hash].css` files.

### What's the expected result?

i like that the css files are named according to the pages, but why are imported css files, like my `global.css` file not named according to their file name or the layout file name?

i wan to get the following css files:
- `index.[hash].css` - homepage styles
- `global.[hash].css` or `base.[hash].css` - styles from `global.css` file, imported in `base.astro`
- `about.[hash].css` - about page styles 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wgxcan?file=src%2Fpages%2Fabout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is currently expected. We derive the CSS file name by the first name of a list of pages that uses it, e.g. if both `index` and `about` uses it, the first (sorted alphabetically) page - `about` - would be the name.

I think it's somewhat possible to use the original file name, e.g. `global.css`, as the main name though, so will leave this open for now for investigation.

**Comment by andywwright** [comment]
For now this is the only thing that feels wrong about Astro. This naming is very misleading and took me a while to investigate.

Why would anyone want to call `xxx` something that describes `yyy`? If it is used in most pages - just call it global. If you don't like to call it global - ​it is better to give it no name (a random string) rather than giving a misleading one forcing us to guess from a crystal ball that `about.css` actually means `global.css`

**Comment by jljorgenson18** [comment]
I agree. I thought something was broken since my css file was named after some random page despite being a global css file. It seems like it should ideally just be called the same name as the original file name (with a hash) or else it could confuse people.

**Comment by lilnasy** [comment]
I agree the naming could be made better. However, it can't be the original file name because a chunk is often made by combining multiple files and sources.

**Comment by do-web** [comment]
Please fix it, cause it feels so wrong and broken.

**Comment by Michael0520** [comment]
Has this issue been fixed correctly?
Because I still have the same problem

**Comment by karesztrk** [comment]
> Has this issue been fixed correctly? Because I still have the same problem

Same. So far, I'm aware of [Rollup assetfilenames](https://rollupjs.org/configuration-options/#output-assetfilenames). But its cumbersome.

**Comment by Kirshach** [comment]
Just encountered the same issue, if I may call it so, in Astro 4.5.2, was thinking I was doing something wrong. Would be good to somehow name the output file more appropriately by default

**Comment by faizananwerali** [comment]
same thing happend to me, it shouldn't merge them into one, keep them seperate chunks for each page to avoid _Eliminate render-blocking resources_ issue.

**Comment by cmnstmntmn** [comment]
same issue after so long time. any updates?

**Comment by olliefwilliams** [comment]
I just got confused by this issue. Would appreciate any of the suggestions made above.

**Comment by pippaine** [comment]
The current naming scheme is quite confusing when debugging style issues - I was chasing down a rabbit hole for a full day because of this. PR #8754 addressed some confusion (like "404" names), but the core issue of misnamed layout styles remains. Reproduction case of the current behavior in #13132.

Thanks to @mschoeffmann - your integration improves the confusing names, but I also see from #334 that it should prevent deployment headaches on cloudflare. Might have saved me from running into that wall later.

Since this naming problem continues to confuse new developers, it might be worth reconsidering closing issues when core problems remain unresolved.

**Comment by niconiahi** [comment]
I agree with the naming. It's totally unexpected behaviour in my opinion. The production files should just fingerprint the `.css` files while maintaining the name. 

it's the only weird thing about astro for now

https://discord.com/channels/830184174198718474/1337533512391331982

**Comment by bfcns** [comment]
Why is this closed?

**Comment by nlambert** [comment]
I agree the filename for shared styles is surprising.  
I thought something was wrong when I saw `about*.css` on every page.

This comes from **Vite’s CSS extraction**, not Astro. Vite decides which CSS is *shared* (referenced by multiple pages) and picks the filename from the **first referencing entry**. Rollup then applies your `assetFileNames` template and the content hash.

If you just want a stable name for all CSS, you can override it in `astro.config.mjs`:

```js
// astro.config.mjs
import { defineConfig } from 'astro/config';

export default defineConfig({
  vite: {
    build: {
      rollupOptions: {
        output: {
          assetFileNames: asset => asset.name.endsWith('.css')
            ? `_astro/styles.[hash][extname]`
            : `_astro/[name].[hash][extname]`
          },
        },
      },
    },
  },
});
```

> `[hash]` is content-based; change the CSS and the hash changes.

**Trade-offs:**
- **Shared CSS**: the filename will now be `styles.[hash].css` 
- **Page-specific CSS**: you lose the page-based filename

If you want to **rename only the shared CSS** and keep page-specific filenames, you’ll need a tiny Rollup plugin. I am happy with the generic names, so I stopped there.

**Comment by f7zorn** [comment]
Just a heads up, asset.name is nowadays deprecated but you can use asset.names like this:

```js
// astro.config.mjs
import { defineConfig } from 'astro/config';

export default defineConfig({
  vite: {
    build: {
      rollupOptions: {
        output: {
          assetFileNames: (asset) =>
            asset.names.some((name) => name.endsWith(".css"))
              ? `_astro/styles.[hash][extname]`
              : `_astro/[name].[hash][extname]`,
        },
      },
    },
  },
});
```
