### ISSUE TITLE
tsconfig: `compilerOptions.baseUrl` should probably be "./" ?

### ISSUE THREAD

**Issue by hirasso** [withastro/astro#7470]
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Irrelevant

### Describe the Bug

This is not necessary a bug, but maybe it is one. I need to use `compilerOptions.paths` for my project. This is what I want:

```json
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "strictNullChecks": true,
    "noImplicitAny": false,
    "paths": {
      "@packages/*": ["packages/*"],
    },
  }
}
```

When I try to import one of my packages, vscode complains:

```js
import MyPackage from "@packages/my-package/src/index.js";
```

![Screenshot 2023-06-24 at 16 03 19](https://github.com/withastro/astro/assets/869813/a1a24672-ae1d-4771-92a9-bcdee7a61f4e)

It seems like this is caused by the `baseUrl` being set to `.` in [astro/tsconfigs/base.json](https://github.com/withastro/astro/blob/main/packages/astro/tsconfigs/base.json#L22).

### What's the expected result?

When I change `compilerOptions.baseUrl` to `./` like so:

```json
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "strictNullChecks": true,
    "noImplicitAny": false,
    "baseUrl": "./",
    "paths": {
      "@packages/*": ["packages/*"],
    },
  }
}
```

...it starts to work as expected:

![Screenshot 2023-06-24 at 16 03 01](https://github.com/withastro/astro/assets/869813/85f10fce-d212-40f6-a3cc-58fe3218a8cb)

### Link to Minimal Reproducible Example

none needed

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I think it's because the `baseUrl` in `base.json` refers to that directory itself, e.g. `/node_modules/astro/tsconfig/`. It was added for the `~/assets/` alias but I'm not sure if it ever worked in that case 🤔 Maybe we should remove it and the preconfigured `paths` directly.

**Comment by natemoo-re** [comment]
Would love @Princesseuh to weigh in on this. Notably the `~/assets` alias was part of our [RFC for `astro:assets`](https://github.com/withastro/roadmap/blob/main/proposals/0030-core-image-story.md#srcassets)

**Comment by Princesseuh** [comment]
It's (unfortunately) not possible for a tsconfig from node_modules to properly set up aliases, because the base path is somewhat relative to itself and not to the final `tsconfig.json`, which honestly, feels like a bug in TypeScript in some ways, but I don't know.

The usual way to work around this is to have a `tsconfig.json` in the user's repo in an hidden folder that you extend from (a la nuxt), but it's a lot of work and would require rethinking completely how we do our presets, at least until we add support for `tsconfig.json` with array of extends.

Honestly, personally, I'd say we remove them and teach people in the docs how to set it up if they need it. Its main purpose is for Markdown, but a lot of people seem to prefer colocation anyway.

**Comment by kanashimia** [comment]
> generally pointing users towards package.json#imports as the "source of truth" for aliases now that TypeScript 5.0 supports them. Vite also automatically resolves them, so I don't even think there's anything special that needs to be done on our end.

Doesn't seem to work with Astro, requires module / exports / main fields which shouldn't be required, seems like a bug somewhere.

**Comment by Princesseuh** [comment]
Fixed by https://github.com/withastro/astro/pull/8113

**Comment by elliottmejia** [comment]
Getting mixed signals here, would love a hard answer for this-
Is there any way at all to use @components , @layouts as an alias?
I understand typescript may be causing issues, I just don't want to manually go through and change several hundred alias imports by hand
