### ISSUE TITLE
create-astro won't work with Bun due to `config` command

### ISSUE THREAD

**Issue by tylergannon** [withastro/astro#7471]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

bun

### What operating system are you using?

macOS

### What browser are you using?

Arc

### Describe the Bug

`bunx create-astro@latest my_app` fails to complete.  The `getRegistry()` function inside of `create-astro@latest` attempts to call `bun config get registry`.  Bun does not support the `config` command.

### What's the expected result?

Bun's registry management takes place only inside the `bunfig.toml` configuration file.

https://bun.sh/docs/install/registries

Since custom or private registries are a minority use case, the trivial fix of simply continuing to the default value on error would solve the problem for most users.

The "correct" solution would need to parse the TOML file.

I'd like to know if the trivial solution would be acceptable, for the time being.

### Link to Minimal Reproducible Example

Not possible.  Just run the `bunx create-astro@latest` command to manifest the bug.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Rhal95** [comment]
`create-astro@latest` is currently `3.1.8`.

As a workaround you can use the previous version `3.1.7`.

`bunx create-astro@3.1.7 my_app`
