### ISSUE TITLE
npm create astro@latest doesn't work

### ISSUE THREAD

**Issue by nadjib-boum** [withastro/astro#7480]
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

when I try installing Astro using this command: `npm create astro@latest`
this error appears:
`TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at new NodeError (node:internal/errors:372:5)
    at new ClientRequest (node:_http_client:164:11)
    at request (node:https:353:10)
    at get (node:https:387:15)
    at file:///C:/Users/username/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/create-astro/dist/index.js:259:3
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_PROTOCOL'
}`

### What's the expected result?

Astro should start installing

### Link to Minimal Reproducible Example

no link

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Moeyua** [comment]
Utilizing the "https://registry.npmjs.org/" instead of an alternative registry mirror proves efficacious in my case.
