### ISSUE TITLE
Cookies are being lost after redirect using middleware

### ISSUE THREAD

**Issue by i7N3** [withastro/astro#7484]
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

@astrojs/node: 5.2.0

### What package manager are you using?

npm or pnpm

### What operating system are you using?

Monterey m1

### What browser are you using?

Any

### Describe the Bug

I am faced with the fact that the cookie is lost after redirecting.

**How to reproduce?**
```
const middleware = defineMiddleware(async (context, next) => {
        // ...
	if (isAuthSuccess) {
		context.cookies.set('jid', '<TOKEN>')
		return context.redirect(`/dashboard`)
	}
	return next()
})
export const onRequest = sequence(middleware)
```

When I log cookie value on /dashboard page with Astro.cookies.get(...).value it's empty.
If I remove the redirect statement, then it works.

Tested both: dev and preview

### What's the expected result?

Cookies should be present after redirect.

### Link to Minimal Reproducible Example

https://github.com/i7N3/astro-middleware-bug-reproduction/tree/54281b3bf6e42bc5becb041c9db83aeb368d5b16

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This was previously fixed here: https://github.com/withastro/astro/pull/7294

It shouldn't matter which adapter it is. Possible regression?

**Comment by matthewp** [comment]
I would guess that the bug is specifically because of the redirect. https://github.com/i7N3/astro-middleware-bug-reproduction/blob/master/src/middleware.ts

**Comment by i7N3** [comment]
> I would guess that the bug is specifically because of the redirect. https://github.com/i7N3/astro-middleware-bug-reproduction/blob/master/src/middleware.ts

I tested it as described and yes, it's because of redirect.

**Comment by medeirosjoaquim** [comment]
I think I'm facing the same thing, but I'm using the API, and it also seems to be the `redirect`. I'm setting cookies before redirect. After the redirect I should be able to get the cookie, once the redirected page loads, with` Astro.cookies.get("/myroute")`, right? But it's undefined. Don't know if it's a bug or I am missing something from the docs on how cookies and redirect should work.

**Comment by asleepace** [comment]
@medeirosjoaquim I was able to get it working by using `context.request.headers.get('cookie')`

```ts
import { defineMiddleware } from "astro/middleware";

// server-side rendering
export const prerender = false;

// check if user is authenticated
const handleAuthentication = defineMiddleware((context, next) => {
  const astroCookies = context.cookies
  const requestCookies = context.request.headers.get('cookie')
  console.log("[middleware] astroCookies:", astroCookies)         // {} (bad)
  console.log("[middleware] requestCookies:", requestCookies)     // { someCookie: 'someValue' } (good)
  return next()
})
```

**Comment by i7N3** [comment]
I found a way to make a redirect using Response. Using this method Cookies are not lost.

`
import { defineMiddleware, sequence } from 'astro/middleware';

export const middleware = defineMiddleware(async (context, next) => {
    console.log('pathname: ', context.url.pathname);

    if (context.url.pathname.includes('/login')) {
        return new Response(null, {
            status: 301,
            headers: {
                Location: '/dashboard',
                'Set-Cookie': 'jid=HelloWorld; Path=/;',
            },
        });
    }

    return next();
});

export const onRequest = sequence(middleware);
`

**Comment by i7N3** [comment]
Fixed by https://github.com/withastro/astro/pull/8612
[Working demo](https://github.com/i7N3/astro-middleware-bug-reproduction)
