### ISSUE TITLE
"Astro builds a static site by default your build does not have access to search params." 

### ISSUE THREAD

**Issue by vic-cekvenich** [withastro/astro#7489]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

linux

### What browser are you using?

firefox

### Describe the Bug

"Astro builds a static site by default your build does not have access to search params." This is a bug.
That is not how http server(Apache, NGNIX) work, nor other static generators (eg 11ty). Search params are a browser command, so Astro removing it when it is client side is bug. I should not have to use server side just for querystring.

From: https://github.com/withastro/astro/issues/4399

### What's the expected result?

search params work client side.

### Link to Minimal Reproducible Example

"Astro builds a static site by default your build does not have access to search params." 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
If you get the search params on the client side, so inside a script tag or hydrated component, it'll work like you expect. For static websites, the Astro frontmatter runs at build time, where search params don't exist.
