### ISSUE TITLE
@astrojs/image with Sharp return bad content-type in response.

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [withastro/astro#7493]
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

All

### Describe the Bug

When you use the `@astrojs/image@0.17.0` integration with `sharp` service, the _image endpoint returns `image/heif` instead of `image/avif` when returning an avif image.

(sharp doesn't seem to work in stackblitz)

### What's the expected result?

When sharp returns an avif image, the content-type headers must be set to `image/avif`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tw8gmj

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nicholasray** [comment]
I'm getting this as well

**Comment by bluwy** [comment]
This is an expected behaviour from Sharp: https://github.com/lovell/sharp/issues/3053. From what I understand, the image is actually encoded as heif instead, so the Content-Type is correct. I personally also find this confusing, but there's not much we can do as it's upstream behaviour.
