### ISSUE TITLE
Default 404 page looking for `favicon.ico` not `favicon.svg`

### ISSUE THREAD

**Issue by rogadev** [withastro/astro#7506]
### What version of `astro` are you using?

2.6.6

### Are you using an SSR adapter? If so, which one?

vercel from @astrojs/vercel/serverless

### What package manager are you using?

9.7.1

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

In your dev environment, if I spin up my fresh, new Astro site (used the Blog template in this instance) and navigate to a page that I have not built yet, I get a 404 when attempting to retrieve the `favicon.ico`. This is because there is no `favicon.ico`, but rather a `favicon.svg` in the `public` folder.

```bash
08:34:30 p.m. [serve]    404                                /projects
08:34:30 p.m. [serve]    404                             /favicon.ico
```

This is extremely minor, but something I noted.

This can be replicated by simply going to [astro.new](https://astro.new) and loading a base project, then navigating to a `/some-route` that does not exist in the project.

### What's the expected result?

Favicon should load as intended.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/blog?file=README.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This can't be fixed as it's a default browser behaviour. When you get a 404, there isn't a way for the server/page/request to tell which favicon to load. Browsers (I believe mainly Chrome) will auto fetch `favicon.ico` in that case.

**Comment by rogadev** [comment]
@bluwy Is there a way to compile a fallback `facicon.ico` for this instance? It seems very unpolished to have this behavior exist out of the box. Users would have to know that this was going to happen. If they don't develop for this eventuality then their product looks bad. I'm not aware of this happening with SvelteKit, for example, and they also use a `favicon.svg` by default. End users will inevitably hit bad page requests sooner or later, so it feels like something small, but important on the principal of how basic/essential the behavior is expected to be.
