### ISSUE TITLE
Gitpod config for astro.new projects seems wrong

### ISSUE THREAD

**Issue by essential-randomness** [withastro/astro#7507]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

default (on GitPod)

### What package manager are you using?

default (on GitPod)

### What operating system are you using?

default (on GitPod)

### What browser are you using?

default (on GitPod)

### Describe the Bug

Starting a Astro project from [astro.new](https://astro.new/) seems to pull the entire withastro/astro repo. The screenshot shows gitpod after I selected the "minimal" option. It was very confusing and it took me a while to understand what was going on.

![image](https://github.com/withastro/astro/assets/47095486/0956b609-55ac-4b43-acc2-b1de5b7b1e84)

### What's the expected result?

Only the files in the minimal configuration are shown on the GitPod workspace, like in the other online editors.

### Link to Minimal Reproducible Example

https://withastro-astro-9dkyskt9cw1.ws-us101.gitpod.io/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Sorry for the confusion! Unfortunately, I don't believe GitPod supports pulling in a repo subpath like our `examples/*` setup expects.

I don't think we're planning on splitting our `examples` into separate repos anytime soon. If you're interesting in working with us to improve this workflow, please feel free to reopen this issue or join us on our Discord (https://astro.build/chat)
