### ISSUE TITLE
Error Rendering Javascript Value in Jsx

### ISSUE THREAD

**Issue by Favourz1** [withastro/astro#7515]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 

### What browser are you using?

Chrome

### Describe the Bug

I fetched a data from an AP (an array of objects) in an inline script tag, but i wasn't able to access this data from my html even after referencing it to a global variable.

I recreated the error here

[https://stackblitz.com/edit/error-rendering-js-in-jsx?file=src%2Fpages%2Findex.astro](url)

### What's the expected result?

I want to be able to map through an array gotten from the inline script and render some HTML table on my page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/error-rendering-js-in-jsx?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You can't render `customersList` that way. It needs to exist in build-time, but the value is only available runtime with the script tag. Since you're using alpine, you should use that to render in the client instead.
