### ISSUE TITLE
Custom 404 page has status code 200 OK

### ISSUE THREAD

**Issue by xriter** [withastro/astro#7516]
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

I created a custom 404 page (following the docs: https://docs.astro.build/en/core-concepts/astro-pages/#custom-404-error-page).

But when hitting this page, the status code of the document is still 200 OK!? 
404 Not Found is expected. 

(Use the web inspector to see this.) 

Note that the logs of Astro ARE logging 404 though. Is the status code of the page even set by Astro?

### What's the expected result?

Status code 404

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xjlmoy?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Will look into it

**Comment by ematipico** [comment]
The 200 status code is returned only in development, but I can see the 404 status code when building with the node adapter. Is your issue related only to the development mode?

**Comment by ematipico** [comment]
Yeah it's a bug, we'll have to look into it.

**Comment by bondarenkovladislav** [comment]
Hi, the issue is still here.
If I go to the 404 page directly it returns a 200 status, like the page exists and route too.

In Dev mode, it returns a 404, but after the build it's 200.

**Comment by alexschcom** [comment]
Yup, same here. In prod the `/404` route returns `HTTP 200`
