### ISSUE TITLE
Performance bug when uploading large amounts of data

### ISSUE THREAD

**Issue by hbgl** [withastro/astro#7525]
### What version of `astro` are you using?

2.7.2

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

There exists a performance bug when Astro has to handle large request bodies. The problem is caused by this piece of code:

https://github.com/withastro/astro/blob/5df4853bd19cab85cd33cc006662669db815e7f8/packages/astro/src/core/app/node.ts#L64-L75

On line 67, `Buffer.concat` is called for every chunk of the request body. The [concat](https://nodejs.org/api/buffer.html#static-method-bufferconcatlist-totallength) function returns a newly allocated buffer on each call. This puts a lot of pressure on the GC and spikes memory usage. With small payloads this effect is not noticeable. However, with larger payloads in the megabytes, this adds significant overhead. The chunk size on my machine is 64k, so a lot of buffers are created and destroyed when uploading anything large.

I want my Astro app to handle file uploads so this is a real problem for me.

### What's the expected result?

For me at least, the expected result would be to not buffer the body into memory at all. The [Request constructor](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request) also accepts a [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) for the body. That would be my preferred solution because for file uploads that will be saved on disk, there is no reason to load them into memory first.

Alternatively, instead of allocating a new Buffer for every chunk, use a "growing" buffer, e.g. double in size when full.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mx5ncy-g1ui5u

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! Since you've already identified the culprit, any interest in submitting a PR to fix this? Switching to a `ReadableStream` seems like a great solution.

**Comment by hbgl** [comment]
I'm not sure if I can find the time to do a proper implementation for this central infrastructure feature. It's sadly not that straight foward to convert a node [Readable](https://nodejs.org/api/stream.html#class-streamreadable) to a [ReadableStream](https://nodejs.org/api/webstreams.html#class-readablestream). A [suitable function](https://nodejs.org/api/stream.html#streamreadabletowebstreamreadable-options) is avaiable since Node V17 as an experimental feature. Astro does support Node V16 so that would need to get polyfilled ([node source](https://github.com/nodejs/node/blob/951da5282c7b00eb86a989336d628218fb2df057/lib/internal/webstreams/adapters.js#L388)).

**Comment by natemoo-re** [comment]
Totally understandable, I appreciate the links and context! We'll try to get working on this as soon as we can.

**Comment by hbgl** [comment]
> It's sadly not that straight foward to convert a node [Readable](https://nodejs.org/api/stream.html#class-streamreadable) to a [ReadableStream](https://nodejs.org/api/webstreams.html#class-readablestream). A [suitable function](https://nodejs.org/api/stream.html#streamreadabletowebstreamreadable-options) is avaiable since Node V17 as an experimental feature. Astro does support Node V16 so that would need to get polyfilled ([node source](https://github.com/nodejs/node/blob/951da5282c7b00eb86a989336d628218fb2df057/lib/internal/webstreams/adapters.js#L388)).

@natemoo-re  I want to make a correction here. Node uses the [undici](https://github.com/nodejs/undici) library for the implementation of the Request class (see [node source](https://github.com/nodejs/node/blob/08638b74eca2b296b2f3fbbcfc7f38038003e626/lib/internal/process/pre_execution.js#L236)). Undici's Request body also accepts async iterables, even though this is non-standard ([see remark](https://github.com/nodejs/undici#requestbody)).

So in practice, you do not need an adapter to convert from a [http.IncomingMessage](https://nodejs.org/api/http.html#class-httpincomingmessage) to a [ReadableStream](https://nodejs.org/api/webstreams.html#class-readablestream) since [http.IncomingMessage](https://nodejs.org/api/http.html#class-httpincomingmessage) is also a [Readable](https://nodejs.org/api/stream.html#class-streamreadable) which is also an [aync iterable](https://nodejs.org/api/stream.html#streams-compatibility-with-async-generators-and-async-iterators).

This should just work:

```ts
import { IncomingMessage } from 'node:http';

function makeRequest(req: IncomingMessage) {
    return new Request('http://example.com', {
        method: 'post',
        body: req,
        duplex: 'half',
    });
}
```

**Comment by hbgl** [comment]
I was trying to write a fix ([see commit](https://github.com/hbgl/astro/commit/5dc0de10367fc215dfe7dbab34a768cb893f1cd5)) but in order to make it PR-ready, it would also involve refactoring the tests. The [tests](https://github.com/withastro/astro/blob/8df6a423c5088a68cc409b5415b09aff0c10a0f1/packages/integrations/node/test/api-route.test.js#L20) currently use [node-mocks-http](https://github.com/eugef/node-mocks-http) to create mock requests. However, the mocked request does not support the async iterable interface that the real request has.
