### ISSUE TITLE
CSS HMR is broken on 2.7.2

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [withastro/astro#7529]
### What version of `astro` are you using?

2.7.2

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

edge, vivaldi

### Describe the Bug

When i am in dev mode, the hot reload is not working for css. It's works for html but not on css even if it's tailwind class or css in file.

### What's the expected result?

i want to be abble to use dev mode and have css compile along the html

### Link to Minimal Reproducible Example

https://stackblitz.com/github.com/jojojojojoj5564656465465/astro-bug2

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Dunqing** [comment]
There is the same problem in `UnoCSS`, a related issue in #2812.

I did some research and guessed that it was broken in https://github.com/withastro/astro/pull/7381. Hope it helps `astro` to fix this.

**Comment by delucis** [comment]
Noting that we’ve also seen reports of this with Astro v2.7.1 so may have been introduced before 2.7.2.

**Comment by jojojojojoj5564656465465** [comment]
I used my unocss config on qwik and didn't get those bugs so I don't blame unocss

**Comment by delucis** [comment]
I’ve definitely seen similar reports for a range of set-ups with/without UnoCSS, so yeah, don’t think that’s the issue here. I’d recommend anyone who’s hitting this downgrades to astro v2.7.0 for now:

```
npm i astro@2.7.0
```

**Comment by jojojojojoj5564656465465** [comment]
> I’ve definitely seen similar reports for a range of set-ups with/without UnoCSS, so yeah, don’t think that’s the issue here. I’d recommend anyone who’s hitting this downgrades to astro v2.7.0 for now:
> 
> ```shell
> npm i astro@2.7.0
> ```

I used 2.7.0 and it 's working perfectly

**Comment by gjaynes-squiz** [comment]
FYI, I'm getting this too with Tailwind CSS, I'm not using UnoCSS. 

It's particularly bad when saving `.mdx` file inside a content collection. 

I downgraded to 2.7.0 and it seems to fix the issue.

**Comment by florivdg** [comment]
> It's particularly bad when saving `.mdx` file inside a content collection.

I can definitely replicate that! I'm using Tailwind CSS and .mdx files, but this combination is proving to be not working as well.
