### ISSUE TITLE
Importing astro.config.mjs into component throws error when building

### ISSUE THREAD

**Issue by ferranJS** [withastro/astro#7551]
### What version of `astro` are you using?

2.7.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows, Linux

### What browser are you using?

Chrome

### Describe the Bug

When importing _astro.config_ into a component to add the base URL to an _img src_ like this:

```
---
import config from "../../astro.config.mjs"
---
<img src={config.base + "/image.svg"} />
```
it throws an error that can be seen [in this workflow](https://github.com/ferranJS/astro-tailwind-landing-0/actions/runs/5444110754/jobs/9901497337) from line 80 approx.

The import from above can be found [here](https://github.com/ferranJS/astro-tailwind-landing-0/blob/main/src/components/Socials.astro).

In the _stackblitz example_, cancel the `npm run dev` and run `npm run astro build`.

### What's the expected result?

It should build as usual and deploy with all the "socials" image URLs being `config.base+"/XXX.svg"` as you can see when running `npm run dev` in the _stackblitz_ example.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/ferranJS/astro-tailwind-landing-0

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Closing, this is an unsafe use of the configuration.
It's possible to read `import.meta.env.BASE_URL`.

**Comment by ferranJS** [comment]
> Closing, this is an unsafe use of the configuration. It's possible to read `import.meta.env.BASE_URL`.

Yes, I saw your recommendation in Discord, thank you for your reply!
