### ISSUE TITLE
📘 DOC: Add Accessibility Testing

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#756]
- All documents should have a title, ex: http://astro-docs.laura-melo.com/installation/ does not
- <html> element must have a lang attribute....

There's a couple more, but I think I'll just list them in context in a PR.

You can see for yourself what needs help by using https://www.deque.com/axe/browser-extensions/ in the devtools to check for basic accessibility problems

**Comment by jasikpark** [comment]
Partially implemented by #804, though automated testing via Github Action might be good.

**Comment by jonathantneal** [comment]
@jasikpark, would you be willing to submit such an action as a PR? I’m willing to help, and I’m sure others would, too. Like, if you can get the action put together, maybe we could help make sure it only runs when files are changed in docs.

**Comment by jonathantneal** [comment]
Since I hadn't heard back, I’m resolving this in https://github.com/withastro/astro/pull/2362

**Comment by jasikpark** [comment]
Oops didn't see this - thanks for working to fix the lint script and set up the Github Actions for linting on pa11y-ci & html-validate
