### ISSUE TITLE
Injected route error in pnpm workspace packages more than one directory deep

### ISSUE THREAD

**Issue by delucis** [withastro/astro#7561]
### What version of `astro` are you using?

2.7.0, 2.7.1, 2.7.2, 2.7.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

macOS / Stackblitz

### What browser are you using?

Firefox/Chrome/Safari

### Describe the Bug

In versions of Astro 2.7.0, 2.7.1, 2.7.2 and 2.7.3 (latest), we’re seeing the [starter template](https://github.com/withastro/starlight/tree/main/examples/basics) failing to build inside the Starlight monorepo (usage via `create astro` works fine as does `astro dev`). This seems to be a wider bug with pnpm workspaces.

Minimal reproduction:

1. Load the [StackBlitz repro](https://stackblitz.com/edit/github-kwocty-hrptj2)
2. It will install dependencies for you
3. `cd sites/docs` to move to the package using Starlight
4. `pnpm build` to try building the site

This will trigger an error during the generating static routes phase:

> Cannot find module `'/home/projects/github-kwocty-hrptj2/sites/renderers.mjs'` imported from `/home/projects/github-kwocty-hrptj2/sites/docs/dist/node_modules/.pnpm/@astrojs+starlight@0.4.1_astro@2.7.0/node_modules/@astrojs/starlight/404.astro.mjs`

For context: `404.astro.mjs` is being generated from Starlight’s [injected 404 route](https://github.com/withastro/starlight/blob/eec46b40f4d35fdfb63c1ae2f2b148c83a448faf/packages/starlight/index.ts#L38-L45).

If you move the site up a level to `docs/` (instead of `sites/docs/`) and update `pnpm-workspace.yaml` accordingly, the project builds fine, so seems to be related to folder depth? Or perhaps something accidentally works for packages one level deep but not for more nested packages?

Also reported here: https://github.com/withastro/starlight/issues/305

### What's the expected result?

`astro build` is able to successfully build the site.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kwocty-hrptj2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
I managed to make the build work by patching the [`makeAstroPageEntryPointFileName()`](https://github.com/withastro/astro/blob/47b756e3e11703387407692e189f34c31f8565d6/packages/astro/src/core/build/static-build.ts#L444-L465) function. 

Just posting what I could find here in case it might help:

- The `routes.find` won't return a route for the `pageModuleId` equals to `../../packages/starlight/404.astro` as `routeData.route` is equal to `/404`. Only `routeData.component` seems to be equal to the `pageModuleId`.
- This means the function will return `pages../../packages/starlight/404.astro.mjs`.
- To build properly, this function needs to return `pages/404.astro.mjs` instead.

The quick and dirty patch I used to make the build pass is the following, altho it is surely not the best way to fix this as I do not know this part of the codebase well enough and may break other things:

```diff
export function makeAstroPageEntryPointFileName(
	prefix: string,
	facadeModuleId: string,
	routes: RouteData[]
) {
	const pageModuleId = facadeModuleId
		.replace(prefix, '')
		.replace(ASTRO_PAGE_EXTENSION_POST_PATTERN, '.');
	let route = routes.find((routeData) => {
-		return routeData.route === pageModuleId;
+		return routeData.route === pageModuleId || routeData.component === pageModuleId;
	});
	let name = pageModuleId;
	if (route) {
		name = route.route;
	}
	if (name.endsWith('/')) name += 'index';
	const fileName = `${name.replaceAll('[', '_').replaceAll(']', '_').replaceAll('...', '---')}.mjs`;
-	if (name.startsWith('..')) {
+	if (pageModuleId.startsWith('..')) {
		return `pages${fileName}`;
	}
	return fileName;
}
```
