### ISSUE TITLE
Cloudflare Pages deployment throws 500

### ISSUE THREAD

**Issue by brandonpittman** [withastro/astro#7566]
### What version of `astro` are you using?

2.7.3

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

My homepage, `https://brandonpittman.com`, triggers a 500 error. When I run `wrangler pages deployment tail`, I get this error message:

```
(error) 02:27:47 AM [ssr] Error: To use the new ReadableStream() constructor, enable the streams_enable_constructors compatibility flag. Refer to the docs for more information: https://developers.cloudflare.com/workers/platform/compatibility-dates/#compatibility-flags
    at Ag (functionsWorker-0.4562300587147523.js:1322:20)
    at async as (functionsWorker-0.4562300587147523.js:1679:11)
    at async Zt.So (functionsWorker-0.4562300587147523.js:2348:137)
    at async Zt.render (functionsWorker-0.4562300587147523.js:2310:17)
    at async Object.fetch (functionsWorker-0.4562300587147523.js:7275:15) (x4)
```

I added a compatibility flag in `wrangler.toml`, but still getting a 500. Anyone else run into this?

### What's the expected result?

The page should display the same as it does local.

### Link to Minimal Reproducible Example

https://github.com/brandonpittman/site

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by derricksimpson** [comment]
@brandonpittman - Do you remember how you got past this error? Thanks!
