### ISSUE TITLE
Markdoc rendering does not support HTML tags

### ISSUE THREAD

**Issue by alex-sherwin** [withastro/astro#7576]
### What version of `astro` are you using?

2.7.4

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

pnpm

### What operating system are you using?

Mac, Windows & Linux

### What browser are you using?

Chrome, Firefox & Safari

### Describe the Bug

Right now, the default Markdoc renderer does not properly process HTML tags, however, HTML tags are allowed in the Mark **_down_** spec

This is a known issue in the Markdoc project, and currently there are no plans for that behavior to change.  I previously worked with a few people from the Stripe team on this issue and they helped me come up with a token transform approach (this approach be applied on the markdown-it tokens or the Markdoc AST).

This is discussed [here https://github.com/markdoc/markdoc/issues/10](https://github.com/markdoc/markdoc/issues/10) and [here https://github.com/markdoc/markdoc/pull/344#issuecomment-1470381718](https://github.com/markdoc/markdoc/pull/344#issuecomment-1470381718)

A high-level summary of this accepted solution to this problem is:

1. Parse the Markdoc markup into tokens
2. Apply an opt-in HTML transform on the tokens, which uses the [htmlparser2](npmjs.com/package/htmlparser2) NPM package (a lazy/incremental HTML parser) to...
    1. Traverse the token graph
    2. If raw HTML is encountered, parse the tags with **htmlparser2**, tracking the currently open stack of HTML nodes
    3. Create a token per HTML tag
    4. If Markdoc tags are encountered, move them under any currently open HTML node stack
3. Render

The end result is that any arbitrary nesting of block and inline HTML tags can be mixed and interleaved with any combination of Markdoc block and inline tags.

The proposed solution is entirely opt-in and applies as a pure transform function on the existing parsed tokens (technically these are [markdown-it](npmjs.com/package/markdown-it) tokens, which Markdoc uses under the covers).

I propose that Astro could do one or all of the following:

* Have a simple boolean option like **enableHTML** which will enable parsing of HTML tokens are proposed above
* Expose a hook allowing the registration of custom, pure token transform functions 

I think adding **both** of these would be the best solution, allowing a simple boolean opt-in for the most likely common token transform requirement (enabling HTML tokens) while also allowing advanced users/use-cases to transform the tokens in the future for any other purpose.

### What's the expected result?

Allow HTML in Markdoc to work as expected

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-burrs2?file=src%2Fcontent%2Fdocs%2Fintro.mdoc

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Hi, thanks for the proposal here. Usually we keep feature request at https://github.com/withastro/roadmap and only keep bug reports here. It would be best if you open a discussion there instead so we can keep track and discuss it there. Thanks!

**Comment by alex-sherwin** [comment]
> Hi, thanks for the proposal here. Usually we keep feature request at https://github.com/withastro/roadmap and only keep bug reports here. It would be best if you open a discussion there instead so we can keep track and discuss it there. Thanks!

Sure, I will do that.  

Just FYI I opened this in collaboration with @bholmesdev via Discord discussions so he could do an early review on my approach before putting together a real PR

**Comment by alex-sherwin** [comment]
For reference the discussion is here: https://github.com/withastro/roadmap/discussions/613
