### ISSUE TITLE
why outDir is not being generating  dist folder when we use adapter:vercel() and output:'server' on a NX monorepo

### ISSUE THREAD

**Issue by nestoremgi** [withastro/astro#7579]
### What version of `astro` are you using?

^2.6.1

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I don´t know why when I use adapter:vercel() and output:'server' on astro.config.mjs is not building dist folder 

import { defineConfig } from 'astro/config';
import vercel from "@astrojs/vercel/serverless";

export default defineConfig({
  outDir: '../../dist/packages/my-app',
  output:'server',
  adapter: vercel(),
});

Note: This happens only when I use vercel adapter

### What's the expected result?

generated a dist folder to be able to deploy on vercel 

### Link to Minimal Reproducible Example

https://github.com/nestoremgi/experimental-monorepo/tree/main/packages/my-app

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Because the Vercel adapter creates a Vercel function under the `.vercel` directory, and Vercel uses that instead of `dist`.

**Comment by nestoremgi** [comment]
@bluwy hi, that´s true altough this folder is being generated when i run   **npx nx run my-app:build**  locally how you can see
![image](https://github.com/withastro/astro/assets/105574612/a320f3c7-fe7f-4a91-9c02-b345b8a49f
The problem here  is when I deploy on vercel with a set up like that 
![image](https://github.com/withastro/astro/assets/105574612/be6a3876-99f9-4483-80dc-afab93349a28)

**Comment by nestoremgi** [comment]
@ematipico Yes,  it seems, but I don´t understand why  when I set up .vercel/output like output directory function is deployed but crashing.  When I don't use adapter all works (static site) perfectly but using  vercel adapter crash deployment. It´s really frustrating and I didnt found  any that really help me. :C

**Comment by binzcodes** [comment]
Also seeing this, installing the Vercel adapter is breaking builds in an https://github.com/vercel/turborepo monorepo. 

Build failure is inconsistent but building locally always builds to `apps/astro-site/.vercel/static/`
This overrides previous settings even with `outDir` in astro config as well as tsconfig, turbo and Vercel config.

At the very least this appears to be undocumented functionality.
It's also not yet clear to me if it's necessary for my case as I'm building to static, using the adapter only for https://github.com/kindspells/astro-shield

Dropping a comment here as I'm planning to dig into this and update docs or code if it can help others.

This issue may also need moving to https://github.com/withastro/adapters

**Comment by voidserf** [comment]
Also having this issue with vercel/turbo/astro. I changed the output directory in vercel settings to `.vercel/output/static` which seems to have resolved it

**Comment by ematipico** [comment]
The adapter sets a fixed output directory because that's what Vercel requires: https://vercel.com/docs/build-output-api/v3/primitives#static-files

**Comment by voidserf** [comment]
> Also having this issue with vercel/turbo/astro. I changed the output directory in vercel settings to `.vercel/output/static` which seems to have resolved it

Actually this didn't resolve the issue. I've now changed my output settings to use framework "other" without any overrides.

**Comment by voidserf** [comment]
> > Also having this issue with vercel/turbo/astro. I changed the output directory in vercel settings to `.vercel/output/static` which seems to have resolved it
> 
> Actually this didn't resolve the issue. I've now changed my output settings to use framework "other" without any overrides.

Just to note that i'm still getting this issue intermittently. Not clear to me how to fix it.
