### ISSUE TITLE
Tag name can't contain hyphens in @astrojs/markdoc v0.4.1

### ISSUE THREAD

**Issue by cometship** [withastro/astro#7595]
### What version of `astro` are you using?

2.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

Using tag names with hyphens is not possible in `@astrojs/markdoc` `v0.4.1`.

I get the following error (when running with `pnpm dev`):
```
Parse failure: Unexpected token (7:15)
At file: /path/to/index.en.mdoc
Contents of line 7: import Tagfloat-img from "/src/components/FloatImg.astro";
```

`markdoc.config.ts`:
```ts
import { component, defineMarkdocConfig, nodes } from "@astrojs/markdoc/config";

export default defineMarkdocConfig({
  nodes: {
    document: {
      ...nodes.document,
      render: undefined,
    },
  },
  tags: {
    "float-img": { render: component("./src/components/FloatImg.astro") },
  },
});
```

Seems like it's about the generated default import name as it can't contain hyphens. It worked in `v0.3.3`.

Building (with `pnpm build`) gives just a `Unexpected token (Note that you need plugins to import files that are not JavaScript)` error in the frontmatter for a markdoc containing the tag.

### What's the expected result?

It should work with tags that contain hyphens (like in `v0.3.3`).

According to the [docs](https://markdoc.dev/docs/attributes#create-a-custom-attribute)  hyphens are allowed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7zrydw-n8uwg1?file=markdoc.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This definitely seems like a regression! We'll look into this as soon as we can.

In the meantime, you are certainly welcome to pin your dependency to `v0.3.3`.
