### ISSUE TITLE
Configure Vercel Adapter on NX monorepo is not working or at least is not deploying like it´s expected 

### ISSUE THREAD

**Issue by nestoremgi** [withastro/astro#7600]
### What version of `astro` are you using?

^2.6.1

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I few days I wrote a bug related with how is generated build  output, when we are using vercel like adapter and  working with  NX monorep.  Issue  was closed and it was  answered in some way but now that I know where is being build  genereted  (.vercel folder) when I try to deploy  it , function is crashing. This is my astro.config.mjs

```
import { defineConfig } from 'astro/config';
import vercel from "@astrojs/vercel/serverless";

export default defineConfig({
  outDir: '../../dist/packages/my-app',
  output:'server',
  adapter: vercel(),
});

```
And here is my vercel config deploying of astro app on nx mono repo 
![image](https://github.com/withastro/astro/assets/105574612/384b8136-052f-411d-9b28-744c71d80c70)

At least if it is not a bug there is not information about to do it  to work 

### What's the expected result?

Deploy function on vercel https://experimental-monorepo-fke3.vercel.app/

### Link to Minimal Reproducible Example

https://github.com/nestoremgi/experimental-monorepo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Please share a reproduction.

**Comment by nestoremgi** [comment]
@Princesseuh Hi, sorry I  share repo https://github.com/nestoremgi/experimental-monorepo

**Comment by ematipico** [comment]
@nestoremgi you said that the app is crashing, are you able to copy here the stack trace of the error?

**Comment by ematipico** [comment]
Reading the documentation of the [output directory](https://vercel.com/docs/concepts/deployments/configure-a-build#output-directory).

Since you opt-out from the framework defaults, you have to make sure that you point to a directory that meets vercel criteria.

**Comment by nestoremgi** [comment]
hi, deploying is "working"  <html>
<body>


unning build in San Francisco, USA (West) – sfo1
--
08:06:15.880 | Cloning github.com/nestoremgi/experimental-monorepo (Branch: main, Commit: d8269a1)
08:06:15.888 | Skipping build cache, deployment was triggered without cache.
08:06:16.679 | Cloning completed: 794.716ms
08:06:16.905 | Running "vercel build"
08:06:17.581 | Vercel CLI 31.0.1
08:06:18.290 | Running "install" command: `npm install`...
08:07:10.611 |  
08:07:10.612 | > @myproyect-lates/source@0.0.0 postinstall
08:07:10.612 | > node ./tools/scripts/patch-nx-cli.js
08:07:10.612 |  
08:07:10.681 | The Nx CLI was patched to allow importing ESM modules in the "@nxtensions/astro" project graph plugin.
08:07:10.724 |  
08:07:10.724 | added 1450 packages, and audited 1451 packages in 52s
08:07:10.724 |  
08:07:10.725 | 329 packages are looking for funding
08:07:10.725 | run `npm fund` for details
08:07:10.958 |  
08:07:10.958 | 49 moderate severity vulnerabilities
08:07:10.958 |  
08:07:10.959 | To address issues that do not require attention, run:
08:07:10.959 | npm audit fix
08:07:10.959 |  
08:07:10.959 | To address all issues possible (including breaking changes), run:
08:07:10.959 | npm audit fix --force
08:07:10.959 |  
08:07:10.959 | Some issues need review, and may require choosing
08:07:10.960 | a different dependency.
08:07:10.960 |  
08:07:10.960 | Run `npm audit` for details.
08:07:12.719 |  
08:07:12.719 | >  NX   --skip-nx-cache disables the connection to Nx Cloud for the current run.
08:07:12.719 |  
08:07:12.719 | The remote cache will not be read from or written to during this run.
08:07:12.720 |  
08:07:12.728 |  
08:07:12.728 | > nx run my-app:build
08:07:12.728 |  
08:07:14.813 | 02:07:14 PM [content] No content directory found. Skipping type generation.
08:07:14.815 | 02:07:14 PM [build] output target: server
08:07:14.815 | 02:07:14 PM [build] deploy adapter: @astrojs/vercel/serverless
08:07:14.816 | 02:07:14 PM [build] Collecting build info...
08:07:14.816 | 02:07:14 PM [build] Completed in 97ms.
08:07:14.820 | 02:07:14 PM [build] Building server entrypoints...
08:07:16.638 | 02:07:16 PM [build] Completed in 1.82s.
08:07:16.663 |  
08:07:16.663 | finalizing server assets
08:07:16.663 |  
08:07:16.663 | 02:07:16 PM [build] Rearranging server assets...
08:07:17.745 | 02:07:17 PM [build] Server built in 3.03s
08:07:17.745 | 02:07:17 PM [build] Complete!
08:07:17.768 |  
08:07:17.768 |  
08:07:17.768 |  
08:07:17.768 | >  NX   Successfully ran target build for project my-app
08:07:17.769 |  
08:07:17.769 |  
08:07:17.866 | Build Completed in /vercel/output [60s]
08:07:17.948 | Deploying outputs...
08:07:20.009 | Deployment completed
08:07:40.878 | Uploading build cache [116.61 MB]...
08:07:43.487 | Build cache uploaded: 2.608s


</body>
</html>

**Comment by nestoremgi** [comment]
@ematipico Hi, then what will be the right output directory? Because when I'm using nx monorepo, I didn't find any other folder besides the .vercel/output directory, and it's that directory that I used.

**Comment by ematipico** [comment]
> @ematipico Hi, then what will be the right output directory? Because when I'm using nx monorepo, I didn't find any other folder besides the .vercel/output directory, and it's that directory that I used.

I don't know Vercel and how it works. It _seems_ you pointed to the correct directory but maybe it's not enough. You have to make sure that the files in that directory are correct. For example, is there an `index.html` after `.vercel/output` directory? What I'm trying to say is that **you** have to make sure that the files generated are in the correct order and folders for Vercel. Again, I don't know how Vercel reads and serves static files.

**Comment by nestoremgi** [comment]
Hi folks, I recommend you two things here first build with astro build and dev commands, also create symbolic links of node modules and it works! If someone is on troubles i can help!
