### ISSUE TITLE
Astro shows warning `Error: The following dependencies are imported but could not be resolved`

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/astro#7603]
### What version of `astro` are you using?

v2.8.0

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

pmpm

### What operating system are you using?

Windows

### What browser are you using?

Microsoft Edge

### Describe the Bug

I imported `javascript` files from the `public` folder and when I run `pnpm dev`, I get the error (follow https://github.com/AREA44/astro-multiverse/issues/94)

### What's the expected result?

I am not sure this is a bug but I hope the error doesn't show up.

### Link to Minimal Reproducible Example

https://github.com/AREA44/astro-multiverse

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Importing from the `public` folder is not a supported pattern, please move your files to `src` or if they're meant to be in `public` refer to them through a normal `<link>` or `<script>` reference
