### ISSUE TITLE
Astro.cookies error with length

### ISSUE THREAD

**Issue by jameslei2020** [withastro/astro#7604]
### What version of `astro` are you using?

2.8.0

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

Of sudden, I got a weird error with `Astro.cookies` when it tried to read a length? Prior to this issue, it has been working fine.

```
 error   Cannot read properties of undefined (reading 'length')
  File:
    /Users/v/Downloads/astro/project1/src/pages/post.astro:3:14
  Code:
    2 | try {
    > 3 |     if (!Astro.cookies.get('session').value) return Astro.redirect('/signout');
        |              ^

```

### What's the expected result?

Error

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Might be a regression during some internal refactors recently. Can you provide a repro and the full error log of the issue?
