### ISSUE TITLE
Cannot exclude pages with underscore prefix in folder name in content collections

### ISSUE THREAD

**Issue by OverflowCat** [withastro/astro#7606]
### What version of `astro` are you using?

2.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

WIndows

### What browser are you using?

Chrome

### Describe the Bug

Files with the _ prefix won’t be excluded and appear in the result of `getCollection`.
However, accessing them will cause an error.

Create a _folder in a collection with markdown files. The docs say "Files with the _ prefix won’t be recognized by the router and won’t be placed into the dist/ directory". If folders are expected to not exclude files, then accessing both of them raises an error. If folders are expected to work with underscores, then the two posts show up in the result of `getCollection`.

![demo](https://github.com/withastro/astro/assets/20166026/2423822b-34fb-4a6a-aa52-ea4624403a29)

### What's the expected result?

The two posts should either be excluded or can be rendered without throwing an error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lhq8uj

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This was fixed in 2.8.1 🥳
