### ISSUE TITLE
Markdown tables generate deprecated HTML attributes

### ISSUE THREAD

**Issue by thdoan** [withastro/astro#7609]
### What version of `astro` are you using?

2.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

The HTML code for tables generated from MD files use deprecated `align` attributes.

Source:
https://developer.mozilla.org/docs/Web/API/HTMLTableElement/align

Markdown
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

HTML output
```
<table>
  <thead>
    <tr>
      <th>Tables</th>
      <th align="center">Are</th>
      <th align="right">Cool</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>col 3 is</td>
      <td align="center">right-aligned</td>
      <td align="right">$1600</td>
    </tr>
    <tr>
      <td>col 2 is</td>
      <td align="center">centered</td>
      <td align="right">$12</td>
    </tr>
    <tr>
      <td>zebra stripes</td>
      <td align="center">are neat</td>
      <td align="right">$1</td>
    </tr>
  </tbody>
</table>
```

### What's the expected result?

`align="center"` should be replaced with `style="text-align: center;"`

`align="right"` should be replaced with `style="text-align: right;"`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-y5t9cq-6gywju?file=src%2Fpages%2Findex.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Astro uses Github-flavoured markdown by default, and it uses `align=""`. There's more discussion here: https://github.com/syntax-tree/mdast-util-to-hast/issues/43, so this is a wont fix on our side. If you'd like to convert that to `style`, you can use https://github.com/mapbox/hast-util-table-cell-style
