### ISSUE TITLE
Props not being passed to some slots 

### ISSUE THREAD

**Issue by salami-art** [withastro/astro#7610]
### What version of `astro` are you using?

2.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I am attaching a stripped-down example of what I am experiencing.

Basically, at least one of the slots I'm trying to render does not receive props ( hence the error ), usually the one named after. I found out about this when trying to build a component that receives multiple slots, all were passed props, except the one named after (or anything starting with A, weirdly enough) .
If I remove the props destructuring from the slotted function the slot is rendered.

By debugging the code into node_modules/astro/dist/core/render/result.js, I found out that that slot's expressions sometimes has an Object [Generator] {} as its first member (therefore the getFunctionExpression returns undefined because the expressions length is greater than 1) and I don't know where it comes from. However, sometimes, by changing the slot's name from after to something else the  Object [Generator] {} disappears

### What's the expected result?

I would like the props to be passed to all slots. It seems like the issue has something to do with my example not having a <head> tag and the `after` slot being the first in alphabetical order ( but I have seen it happening even if the <head> tag is included in other examples )

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-927mjd?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by salami-art** [comment]
That does fix that example, but there are also cases where the problem persists when adding a <head> tag.

see this: https://stackblitz.com/edit/github-32w1iv?file=README.md

**Comment by lilnasy** [comment]
Relevant proposal:
- https://github.com/withastro/roadmap/discussions/541

**Comment by matthewp** [comment]
Names slots can't be function. In these examples the `div` is the slot. The functions are just regular expressions. It would be the same as passing a function as an expression anywhere else, the template calls them without arguments.

This should work for default slots (the only valid way to define a function as a slot).

**Comment by BryceRussell** [comment]
@matthewp

This use to work in previous versions of Astro, is there a reason this is not supported anymore? I built a library of components that uses this principal of passing template functions to named slot to customize the rendering of a component https://github.com/BryceRussell/astro-headless-ui/wiki#named-slot-functions would this be considered a regression?

**Comment by BryceRussell** [comment]
I am not too sure I will do some testing and see which version it got changed

**Comment by BryceRussell** [comment]
@matthewp I tested this a bunch, passing a function to a named slot does still work but there is a caveat with the name of the tag, if the tag includes a dash `-` it breaks:

- `<tag slot="named">{() => ...}`: tag is NOT included in the markup, arguments ARE passed to slot function
- `<tag-with-dashes slot="named">{() => ...}`: tag IS included in the markup, arguments are NOT passed to slot function

But this is unrelated to the original issue

I made a minimal reproduction for the original issue here: https://stackblitz.com/edit/github-s9fusc?file=src%2Fpages%2Findex.astro,src%2FTest.astro,.gitignore

I have a limited knowledge of how the rendering works but the way I understand it is:
- If a component is the very first the first expression/element/tag on the page, the first slot alphabetically of the component will receive a `maybeRenderHead()` expression. When the component is rendered the `maybeRenderHead()` expression receives or "eats" the arguments meant for the the slot function's expression
