### ISSUE TITLE
Third party stylesheet overrides local stylesheet

### ISSUE THREAD

**Issue by waspeer** [withastro/astro#7614]
### What version of `astro` are you using?

2.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When using a third party css reset stylesheet, it somehow always overrides my local stylesheet.

### What's the expected result?

[As the documentation suggests](https://docs.astro.build/en/guides/styling/#import-order), I'd expect the rules to be evaluated in the order that they are imported and scoped rules to override imported css rules.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gigfsc?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by 516310460** [comment]
Adjust CSS order

**Comment by waspeer** [comment]
> Adjust CSS order

If you mean changing the import order by that, that does not work for me. Hence the bug report

**Comment by bluwy** [comment]
I don't see the issue in the repro. It looks like this to me in both dev and prod.

<img width="92" alt="image" src="https://github.com/withastro/astro/assets/34116392/d4de6737-b8df-458d-9a2f-abade45a4eea">

Which seems to be that the styles are correctly overridden.

**Comment by bluwy** [comment]
Oh yeah I was using Safari so that worked for me (finally it got something right). Thanks I'll leave this open then

**Comment by dannymcgee** [comment]
So I made the mistake of building out my entire blog in dev mode and not really testing the build until I was ready to deploy it. I relied on stylesheet ordering for overrides, like, a lot. I would really like to deploy this today, so I wrote a quick-and-dirty script that "fixes" the issue as a post-build step. Copying it here in case anyone finds it useful, but it is _not fast_, so tread carefully.

`tools/scripts/reverse-stylesheet-ordering.mjs`
```javascript
import { promises as fs } from "node:fs"
import path from "node:path"
import url from "node:url"
import jsdom from "jsdom"

main()

async function main() {
  const __dirname = url.fileURLToPath(new URL(".", import.meta.url))
  const dist = path.resolve(__dirname, "../../dist")
  const htmlFiles = await findFiles(dist, file => file.name.endsWith(".html"))

  await Promise.all(htmlFiles.map(async pathname => {
    const html = await fs.readFile(pathname, "utf-8")
    const dom = new jsdom.JSDOM(html)
    const { window: { document: doc }} = dom

    /** @type {HTMLLinkElement[]} */
    const cssLinks = []
    for (let link of doc.head.querySelectorAll(`link[rel="stylesheet"][href^="/_astro/"]`))
      cssLinks.push(doc.head.removeChild(link))

    const firstScript = doc.head.querySelector("script")

    while (cssLinks.length)
      doc.head.insertBefore(cssLinks.pop(), firstScript)

    const updated = dom.serialize()
    await fs.writeFile(pathname, updated, "utf-8")
  }))
}

/**
 * @param {string} root The root directory to search
 * @param {(file: import("fs").Dirent) => boolean} pred The predicate
 * @param {string[]} accum Accumulated results for recursive calls
 *
 * @returns {string[]} the full paths of all files under the provided directory
 * (including subdirectories) that match the provided predicate.
 */
async function findFiles(root, pred, accum = []) {
  const ls = await fs.readdir(root, {
    encoding: "utf-8",
    withFileTypes: true,
  })

  const subDirs = ls
    .filter(it => it.isDirectory())
    .map(dir => path.join(root, dir.name))

  accum.push(
    ...ls.filter(it => it.isFile() && pred(it))
      .map(file => path.join(root, file.name))
  )

  if (!subDirs.length)
    return accum

  const results = await Promise.all(
    subDirs.map(subDir => findFiles(subDir, pred, accum))
  )

  return results.flat()
}
```

`package.json`
```json
{
  ...
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build && npm run reverse-stylesheet-ordering",
    "preview": "astro preview",
    "astro": "astro",
    "reverse-stylesheet-ordering": "node ./tools/scripts/reverse-stylesheet-ordering.mjs"
  },
  ...
}
```

@bluwy (or anyone else with knowledge): If you'd be able to point me in the general direction of where the error might be occurring I can try to take a look at submitting a PR, but I can't make any promises.

**Comment by matthewp** [comment]
You want to use `scopedStyleStrategy: 'class'`. We cannot ensure stylesheet order, which is why we are going to change the default for this in 3.0.

**Comment by waspeer** [comment]
@matthewp Thanks for taking a look at this! Your solution does work for the scoped component styles. Happy to hear this will be the default.

However, this does not solve the fact that the styles in `global.css` are overridden in dev . I think this is a bug, because [the documentation suggests otherwise](https://docs.astro.build/en/guides/styling/#import-order) and this [does not match with the behavior after a build](https://github.com/withastro/astro/issues/7614#issuecomment-1632199709).

Here's an updated Stackblitz: https://stackblitz.com/edit/github-gigfsc-lvp8s9?file=src%2Fpages%2Findex.astro
