### ISSUE TITLE
Unable to find custom 404 page with trailing slash

### ISSUE THREAD

**Issue by 516310460** [withastro/astro#7616]
### What version of `astro` are you using?

v2.8.0

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When output: "hybrid", accessing a non-existent page, the custom 404 page cannot be found.
Automatically add '/' after the URL
Step:
1.npm run build
2.HOST=0.0.0.0 PORT=3000 node dist/server/entry.mjs
3.localhost:3000/en/test/asd
4.Custom 404 page not found

### What's the expected result?

1. Find the custom 404 page
2. Remove the trailing slash

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nhc9gb-malcwc?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by 516310460** [comment]
I have a question, I don't know how to implement it.
[lang]/page/[id].astro
Expect:
1. url: /en/page/10
2. url: /page/10
I don't know how to achieve it

About another question
Use `output: "hybrid"`
The route will prioritize matching SSG before matching SSR.
Can I set it to match SSR first and then match SSG, because in actual website visits, I need a dynamic route. If the SSR application crashes, I can use SSG

**Comment by natemoo-re** [comment]
I am looking into this and can see that we aren't handling 404 pages properly in hybrid mode. Working on a fix.

- Trailing slash behavior can be configured with the [`trailingSlash`](https://docs.astro.build/en/reference/configuration-reference/#trailingslash) option
- Please open new issues for other bugs and visit [our Discord](https://astro.build/chat) for support questions.

**Comment by 516310460** [comment]
> I am looking into this and can see that we aren't handling 404 pages properly in hybrid mode. Working on a fix.
> 
> * Trailing slash behavior can be configured with the [`trailingSlash`](https://docs.astro.build/en/reference/configuration-reference/#trailingslash) option
> * Please open new issues for other bugs and visit [our Discord](https://astro.build/chat) for support questions.

`TrailingSlash 'can only be used in development. In output: "hybrid" and SSG mode, it will automatically add at the end`/`

**Comment by lilnasy** [comment]
Fixed in #8070 (astro v2.10.10+)
<img width="423" alt="image" src="https://github.com/withastro/astro/assets/69170106/e1c5c841-9d9d-4908-80a5-1a1f748a75de">
