### ISSUE TITLE
Astro is fine when development including SSR but it crash after deploy with netlify adapter

### ISSUE THREAD

**Issue by rahXephonz** [withastro/astro#7638]
### What version of `astro` are you using?

latest 2.8.0

### Are you using an SSR adapter? If so, which one?

netlify

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Brave

### Describe the Bug

In development local, the api routes working fine without error and when build also using node adapter

but when deploying to netlify using netlify adapter and my output is "server", the page going crash as the screenshot bellow

![image](https://github.com/withastro/astro/assets/77242429/3ab57127-a00a-4333-b9b5-546601f87df6)

Anyone please help me.

### What's the expected result?

Expected the netlify adapter should be fine when using ```api``` routes.

### Link to Minimal Reproducible Example

https://github.com/rahXephonz/rizkyy.dev

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ioofy** [comment]
i try using that in my local development

and it going fine not error and anything. But should i use ``@astrojs/node``` in netlify?

**Comment by ioofy** [comment]
i try...

**Comment by Bartunek** [comment]
I have exactly the same problem, except I'm using `output: 'hybrid'`. Everything build fine in Netlify, but when api route is called I'm getting the following error:

```
{
  "errorType": "Error",
  "errorMessage": "require() of ES Module /var/task/node_modules/astro/dist/core/app/index.js from /var/task/.netlify/functions-internal/entry.js not supported.\nInstead change the require of index.js in /var/task/.netlify/functions-internal/entry.js to a dynamic import() which is available in all CommonJS modules.",
  "trace": [
    "Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/node_modules/astro/dist/core/app/index.js from /var/task/.netlify/functions-internal/entry.js not supported.",
    "Instead change the require of index.js in /var/task/.netlify/functions-internal/entry.js to a dynamic import() which is available in all CommonJS modules.",
    "    at Object.<anonymous> (/var/task/.netlify/functions-internal/entry.js:33436:18)",
    "    at Object.<anonymous> (/var/task/entry.js:1:18)",
    "    at _tryRequireFile (file:///var/runtime/index.mjs:912:37)",
    "    at _tryRequire (file:///var/runtime/index.mjs:962:25)",
    "    at _loadUserApp (file:///var/runtime/index.mjs:991:22)",
    "    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1032:27)",
    "    at start (file:///var/runtime/index.mjs:1195:42)",
    "    at file:///var/runtime/index.mjs:1201:7"
  ]
}
```

I'm guessing it might be a problem with [this import](https://github.com/withastro/astro/blob/main/packages/integrations/netlify/src/netlify-functions.ts#L4) in Netlify environment?

**Comment by rahXephonz** [comment]
Hello i'm sorry but i've updated a minimal repro into my github repository in here
https://github.com/rahXephonz/rizkyy.dev

Thanks before :)

**Comment by ematipico** [comment]
@Bartunek the split feature is only supported when output is `server`

**Comment by ematipico** [comment]
> Hello i'm sorry for now i've updated a minimal repro into my github repository in here
> https://github.com/rahXephonz/rizkyy.dev
> 
> Thanks before :) 

Your repository is not using the adapter though. :(

**Comment by ematipico** [comment]
Whatever you it's best. Without a reproduction (a minimal one would be best), we can't pin point the real issue.

**Comment by rahXephonz** [comment]
https://stackblitz.com/edit/node-nrueyj

link repro for now i'm using node adapter

**Comment by matthewp** [comment]
Sorry you're having this problem, but we can't consider this a bug with so much code required to get the bug. Our support channels on Discord might be a better place to get help. If you're able to create a minimal reproduction we'd take a look. Thanks!

**Comment by personable** [comment]
I'm not a developer - just a designer who codes a bit; so take this "fix" with a grain of salt. But I had the same issue, and I think the reason was that in my `package.json`, I had `type: module` AND I was on node v16+. Once I removed `type: module`, that `Instead change the require of index.js in /var/task/.netlify/functions-internal/entry.js...` error went away.

**Comment by rahXephonz** [comment]
> I'm not a developer - just a designer who codes a bit; so take this "fix" with a grain of salt. But I had the same issue, and I think the reason was that in my `package.json`, I had `type: module` AND I was on node v16+. Once I removed `type: module`, that `Instead change the require of index.js in /var/task/.netlify/functions-internal/entry.js...` error went away.

interesting maybe i will check this later and try with this solutions. Thanks :)
