### ISSUE TITLE
Almost empty layout does not import local stylesheets

### ISSUE THREAD

**Issue by nmattia** [withastro/astro#7641]
### What version of `astro` are you using?

2.8.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Safari

### Describe the Bug

When using an almost empty layout like so:

```
---
import "../styles/red.css"
---

<html>
  <slot/>
</html>
```

the stylesheets are not actually imported in the resulting page. If the `<slot/>` is wrapped in e.g. a `<div>` _then_ the stylesheet is imported/applied.

### What's the expected result?

The pages using that layout should import the stylesheet.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-k4aq4j?file=src%2Flayouts%2FEmpty.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ditto-vlad** [comment]
To add to this -> I ran into the same issue as well with the only solution being to wrap a dev around my component.
Was about to create an issue but came across this. 

Here is another [Reproducible Example](https://stackblitz.com/edit/github-8c12uz?file=src%2Fpages%2Findex.astro)

Hope this helps

**Comment by jacobthesheep** [comment]
Empty.astro is never used in another astro file so unless I'm getting this wrong this issue can be closed.

**Comment by lilnasy** [comment]
Scripts and styles are usually added as the last children of the `<head>` element. When it isn't there, we try to find the next appropriate place. This is a corner case where we don't find any.

Relevant proposal:
- https://github.com/withastro/roadmap/discussions/541

**Comment by lilnasy** [comment]
Workaround - add an empty `<head>` element:
```diff
---
import "../styles/red.css"
---

<html>
+   <head/></head>
    <slot/>
</html>
```
or wrap the slot in a `<body>` instead:
```diff
---
import "../styles/red.css"
---

-<html>
+<body>
    <slot/>
-</html>
+</body>
```
