### ISSUE TITLE
.astro entryPoints not resolved in injectRoute

### ISSUE THREAD

**Issue by salami-art** [withastro/astro#7642]
### What version of `astro` are you using?

2.8.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

What do I check if the `.astro` entryPoint of an `injectRoute`is not resolved? I have another .ts entryPoint that resolves just fine

```
injectRoute({
  pattern: "/api/endpoints/[endpoint]",
  entryPoint: "src/endpoints/endpoint.ts",
});
injectRoute({
  pattern: "/test/endpoints/[endpoint]",
  entryPoint: "src/endpoints/Loader.astro",
});

```
=>  error   Cannot find module 'src/endpoints/Loader.astro'

### What's the expected result?

The dev server shound start and use the Loader.astro entrypoint to handle requests to /test/endpoints/[endpoint]

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-d4i7hd?file=integration.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
I don’t think this is related to those issues, the reproduction works when updating the local `entryPoint` paths to use a Node-style relative-path format: https://stackblitz.com/edit/github-d4i7hd-9q5ovs?file=integration.ts

```js
injectRoute({
  pattern: "/api/endpoints/[endpoint]",
  entryPoint: "./src/endpoints/endpoint.ts",
});
injectRoute({
  pattern: "/test/endpoints/[endpoint]",
  entryPoint: "./src/endpoints/Loader.astro",
});
```

I think this is probably a documentation issue — the [integration API docs show bare paths](https://docs.astro.build/en/reference/integrations-reference/#injectroute-option) like in the reproduction, but those will be resolved as npm module names not as local paths.
