### ISSUE TITLE
Build warning with `@astrojs/vercel/serverless` due to Dependency Resolution and Eval Issues

### ISSUE THREAD

**Issue by jacobthesheep** [withastro/astro#7654]
### What version of `astro` are you using?

2.8.3

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When using the `@astrojs/vercel/serverless` integration and running `pnpm build`, the build completes successfully but multiple warnings appear regarding dependency resolution and use of `eval` in `binary-locators.js`.

### What's the expected result?

The build completes successfully without any warnings with the `@astrojs/vercel/serverless` integration.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jq9nj3?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Yikes, thank you for the report! I'm not sure where these dependencies are coming from, to be honest... they may have slipped into our `@astrojs/vercel/serverless` code in a recent update? These definitely don't look like things that should be bundled with our runtime at all.

cc @ematipico

**Comment by natemoo-re** [comment]
Given that Ema is off for the weekend but this is a P5, I'm going to look into this now.

**Comment by jacobthesheep** [comment]
> Yikes, thank you for the report! I'm not sure where these dependencies are coming from, to be honest... they may have slipped into our `@astrojs/vercel/serverless` code in a recent update? These definitely don't look like things that should be bundled with our runtime at all.
> 
> cc @ematipico

Sorry, the build doesn't fail but when I tried doing a preview deployment, it took a long time to build so I canceled it. This error showed up after updating to 3.6.0 of the integration.

**Comment by natemoo-re** [comment]
No problem, I was able to get a quick fix. It was attempting to bundle an internal dependency that it shouldn't!

Hoping to get #7659 out quickly.
