### ISSUE TITLE
Issue deploying to cloudflare with astrojs/react 2.2.1

### ISSUE THREAD

**Issue by thejackshelton** [withastro/astro#7662]
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Firefox

### Describe the Bug

Whenever using the @astrojs/react 2.2.1 integration, I get the following error:

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@astrojs/react/-/react-2.2.1.tgz - Not found
```

It will run fine locally, but doesn't build deploying to cloudflare. 

This was my package.json for further reference.
```tsx
{
  "name": "ramedia-us",
  "type": "module",
  "version": "0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/react": "^2.2.1",
    "@astrojs/sitemap": "^1.3.3",
    "@dotlottie/player-component": "1.3",
    "@fontsource-variable/montserrat": "^5.0.4",
    "@radix-ui/react-accordion": "^1.1.2",
    "@radix-ui/react-icons": "^1.3.0",
    "@types/react": "^18.2.12",
    "@types/react-dom": "^18.2.5",
    "animate.css": "^4.1.1",
    "astro": "2.7",
    "astro-icon": "^0.8.0",
    "autoprefixer": "^10.4.14",
    "cssnano": "^5.1.15",
    "postcss": "^8.4.24",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.9.0",
    "swiper": "^9.2.2"
  }
}
```

I reverted to version 2.1 and it deployed properly.

### What's the expected result?

My website to deploy.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
It seems to be fine now, might've just been a npm weirdness at the time you deployed.
