### ISSUE TITLE
In production, mongoose's error was not shown in the log

### ISSUE THREAD

**Issue by sanmmm** [withastro/astro#7665]
### What version of `astro` are you using?

2.8.3

### Are you using an SSR adapter? If so, which one?

Nodejs

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

In the production environment, the mongoose error in the endpoint interface was captured by the astro framework, but it was not shown in the log. It seems strange.

### What's the expected result?

mongoose's error should be treated like any other caught error

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qzg18y?file=src%2Fpages%2Ftest.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Astro is not special-casing Mongoose errors to not display them. If you can figure out what specifically Astro is doing to cause this problem, please let us know.
