### ISSUE TITLE
Hoisted scripts break when components are re-exported from a typescript file

### ISSUE THREAD

**Issue by ottomated** [withastro/astro#7673]
### What version of `astro` are you using?

2.8.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

When components are re-exported, like so:
```ts
import Component from './Component.astro';
import Layout from './Layout.astro';

export { Component, Layout };
```

Astro loses track of which components are included on which pages, leading to hoisted scripts being included on a page where the component does not exist.

This is impactful on a monorepo that includes a library of Astro components, as there is no easy way to avoid re-exporting them.

### What's the expected result?

Re-exporting components should function identically to importing them directly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-15jfdd?file=src%2Fpages%2Findex.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by ottomated** [comment]
Contents of `internals.hoistedScriptIdToHoistedMap` is identical in both cases:
```ts
Map(1) {
  '/astro/hoisted.js?q=0' => Set(1) {
    '/app/src/components/Component.astro?astro&type=script&index=0&lang.ts'
  }
}
```

**Comment by ottomated** [comment]
In `plugin-analyzer.ts`, the `walkParentInfos` function is the source of the bug:

Good case:
```
/app/src/components/Component.astro
/app/src/pages/index.astro
@astro-page:src/pages/index@_@astro
```

Bad case:
```
/app/src/components/Component.astro
/app/src/components/index.ts
/app/src/pages/index.astro 
@astro-page:src/pages/index@_@astro
/app/src/pages/page2.astro 
@astro-page:src/pages/page2@_@astro
```

It seems that hoisted scripts are determined by whether `page2` is a parent of `Component`, regardless of whether or not `page2` is actually importing `Component`.

**Comment by matthewp** [comment]
Do we have the necessary information to change this in the plugin? If so I guess we could check the bindings.

**Comment by ottomated** [comment]
> Do we have the necessary information to change this in the plugin? If so I guess we could check the bindings.

From what I've found, rollup's ModuleInfo objects don't contain the necessary info to fix this bug – they tell you which modules are importing the current module, but not what they are importing. This might require looking at the AST.

**Comment by matthewp** [comment]
@bluwy suggested we might be able to use `importedBindings`: https://rollupjs.org/plugin-development/#generatebundle

**Comment by ottomated** [comment]
`importedBindings` is a field on ChunkInfo, where the plugin is using ModuleInfo right now - I'm not seeing a way to get chunk info from the rollup [PluginContext](https://rollupjs.org/plugin-development/#plugin-context) but that would be great if possible

**Comment by ottomated** [comment]
Ah, it's accessible in the arguments passed to generateBundle

**Comment by ottomated** [comment]
It looks like `importedBindings` isn't a silver bullet here. Here's what the generated chunks look like for the bad case (page2 in the repro):

`src/pages/page2.astro.mjs`
```ts
// ...

const page = () => import('../../chunks/pages/page2.astro.160e38f8.mjs').then(n => n.p);

export { page };
```

`chunks/pages/page2.astro.160e38f8.mjs`
```ts
// ...

// This is the component that isn't included in the page:
const $$Component = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$2, $$props, $$slots);
  Astro2.self = $$Component;
  return renderTemplate`${maybeRenderHead()}<button id=\"button\">Component</button>`;
}, "/app/src/components/Component.astro");

// compiled code for Layout

// Page code
const $$Page2 = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Page2;
  return renderTemplate`${renderComponent($$result, \"Layout\", $$Layout, {}, { \"default\": ($$result2) => renderTemplate`
	${maybeRenderHead()}<p>
		This is page 2, which does not have the component html loaded. However, the
		script is still loaded, as you can see by the alert.
	</p>
	<a href=\"/\">back to page 1</a>
` })}`;
}, "/app/src/pages/page2.astro");

const $$file = "/app/src/pages/page2.astro";
const $$url = "/page2";

const page2 = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
  __proto__: null,
  default: $$Page2,
  file: $$file,
  url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

export { $$Component as $, $$Layout as a, page2 as p };
```

As you can see, it's actually including the component in the chunk to be re-exported, but the re-export is unused. This might be because it's a dynamic import and rollup therefore is having trouble optimizing it?

Anyway, it seems like a combination of the `ChunkInfo` and something else to remove unused imports is necessary here.

**Comment by ottomated** [comment]
If we can access the full `Module` objects in rollup (rather than the `ModuleInfo`s), `importDescriptions` should contain the neccessary information (it's a Map of imported variable name => the module that they're imported from)
