### ISSUE TITLE
Cyclic references cannot be safely serialized for client-side usage. Please remove the cyclic reference

### ISSUE THREAD

**Issue by jamesli2021** [withastro/astro#7676]
### What version of `astro` are you using?

2.8.2

### Are you using an SSR adapter? If so, which one?

SSR

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

Some extra info are leak including Astro license in `hoisted.xxxx.js` when building with `npm run build && npm run preview` and outputs has no error.

index.astro:
```
---
export function Data() {
  return {
    name: 'John Doe',
    isOkay: true,
    mood: null
  }
}
---
<script>
import {Data} from './index.astro';
console.log(">", Data())
</script>


```

### What's the expected result?

Should either throw an error or warning message on cyclic reference and not into hoisted js file which end with much large file size.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-iypkhz?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jamesli2021** [comment]
Thanks to one of the folk share his works in Astro discord showcase and I was exploring new technique.

**Comment by Princesseuh** [comment]
This is honestly a pattern we kinda don't support and I doubt we intend on supporting. We don't officially support exporting from Astro components and we don't officially support importing Astro components inside client-side script tags either.
