### ISSUE TITLE
About Routing Matching Priority. use output: "hybrid"

### ISSUE THREAD

**Issue by 516310460** [withastro/astro#7678]
### What version of `astro` are you using?

v2.8.0

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

The route will prioritize matching SSG before matching SSR.
Can I set it to match SSR first and then match SSG, because in actual website visits, I need a dynamic route. If the SSR application crashes, I can use SSG

### What's the expected result?

I want to prioritize using SSR routing. When the SSR service crashes, I am using SSG routing

### Link to Minimal Reproducible Example

null

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
For new features please add a discussion here: https://github.com/withastro/roadmap/discussions

Note that our route prioritization is modeled on how hosts typically work. I don't think making this configurable is worth the maintenance cost personally. It would be better to just not have routes that conflict with each other, or handle it in code.
