### ISSUE TITLE
astrojs/image won't build, even after proper installation

### ISSUE THREAD

**Issue by tylerjohnlavoie** [withastro/astro#7685]
### What version of `astro` are you using?

2.0.0-beta.4

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome, Firefox

### Describe the Bug

When generating static routes, vercel can't resolve "getImage".

Astro image is installed in my astro.config.mjs file - both imported at the beginning of the file and exported in defineConfig.

`
--
12:23:58.981 | ▶ src/pages/index.astro
12:23:59.082 | error   getImage is not defined
12:23:59.083 | ReferenceError: getImage is not defined
12:23:59.083 | at file:///vercel/path0/dist/chunks/pages/404.astro.2ab29237.mjs:179:45
12:23:59.083 | at AstroComponentInstance.MetaTags [as factory] (file:///vercel/path0/dist/chunks/astro.449c64b7.mjs:1120:12)
12:23:59.083 | at AstroComponentInstance.init (file:///vercel/path0/dist/chunks/astro.449c64b7.mjs:1653:29)
12:23:59.083 | at AstroComponentInstance.render (file:///vercel/path0/dist/chunks/astro.449c64b7.mjs:1658:18)
12:23:59.083 | at render.next (<anonymous>)
12:23:59.084 | at renderChild (file:///vercel/path0/dist/chunks/astro.449c64b7.mjs:1716:18)
12:23:59.084 | at async EagerAsyncIterableIterator.next (file:///vercel/path0/dist/chunks/astro.449c64b7.mjs:1475:14)
12:23:59.084 | at async [Symbol.asyncIterator] (file:///vercel/path0/dist/chunks/astro.449c64b7.mjs:1584:9)
12:23:59.084 | at async renderAstroTemplateResult (file:///vercel/path0/dist/chunks/astro.449c64b7.mjs:1593:20)
12:23:59.084 | at async renderChild (file:///vercel/path0/dist/chunks/astro.449c64b7.mjs:1714:5)
12:23:59.120 | error Command failed with exit code 1.
12:23:59.121 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:23:59.192 | Error: Command "yarn run build" exited with 1

`

### What's the expected result?

Build is able to resolve getImage from the Astro Image plugin

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-cnip9b?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Just a heads up that `@astrojs/image` will soon be deprecated in favour of [`astro:assets`](https://docs.astro.build/en/guides/assets/), as [mentioned at the top of the integration's page](https://docs.astro.build/en/guides/integrations-guide/image/)

**Comment by tylerjohnlavoie** [comment]
Noted - I'll try switching.

Also, I managed to deploy successfully with Netlify, but the Images and Tailwind plugins don't quite work - broken image links, broken styling, etc. Will update after trying Assets.

**Comment by tylerjohnlavoie** [comment]
Successfully migrated to Assets and Netlify.
