### ISSUE TITLE
React Component Hydration Error: "An error occurred during hydration. The server HTML was replaced with client content in <astro-island>"

### ISSUE THREAD

**Issue by lucaswalter** [withastro/astro#7709]
### What version of `astro` are you using?

2.8.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Hello, I'm having a bit of trouble tracing down the root of this so forgive me if this is not the correct spot to note this but I wanted to raise an issue to see if anyone else has encountered this or has a path forward.

I am using shadcn inside an Astro project and am attempting to display data in a `DataTable` component as documented on the shadcn documentation site. When I attempt to run the website locally, I get this hydration error when trying to apply custom formatting or JSX to the `header` or `cell` items on my `ColumnDef`.  **_An error occurred during hydration. The server HTML was replaced with client content in 'astro-island'_**

I've been able to reproduce this exact same issue on a fresh repro project after following these exact steps:
* Astro setup - https://ui.shadcn.com/docs/installation/astro
* DataTable setup - https://ui.shadcn.com/docs/components/data-table

Here is the repro link which uses exact same component as in the docs: https://github.com/lucaswalter/astro-shadcn-tanstack-repro/blob/main/src/pages/index.astro

In short, I am attempting to render and hydrate the `DataTable` like in the snippet below. Is it currently possible to use the DataTable component in an Astro project?
```
<Layout title="Welcome to Astro.">
	<main>
		<h1 class="mb-2">
			Welcome to <span class="text-gradient">Astro</span>
		</h1>

                 <!-- Data Table Usage -->
		<DataTable client:load columns={columns} data={data} />
	</main>
</Layout>
```

**Full Strack Trace**
```
react-dom.development.js:86 Warning: Did not expect server HTML to contain a <div> in <th>.
    at th
    at http://localhost:3000/src/components/ui/table.tsx:53:3
    at tr
    at http://localhost:3000/src/components/ui/table.tsx:44:3
    at thead
    at http://localhost:3000/src/components/ui/table.tsx:17:3
    at table
    at div
    at http://localhost:3000/src/components/ui/table.tsx:5:3
    at div
    at DataTable (http://localhost:3000/src/components/data-table.tsx:6:3)
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
warnForDeletedHydratableElement @ react-dom.development.js:10477
didNotHydrateInstance @ react-dom.development.js:11424
warnUnhydratedInstance @ react-dom.development.js:12313
warnIfUnhydratedTailNodes @ react-dom.development.js:12707
popHydrationState @ react-dom.development.js:12677
completeWork @ react-dom.development.js:22176
completeUnitOfWork @ react-dom.development.js:26593
performUnitOfWork @ react-dom.development.js:26568
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:86 Warning: An error occurred during hydration. The server HTML was replaced with client content in <astro-island>.
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
errorHydratingContainer @ react-dom.development.js:11473
recoverFromConcurrentError @ react-dom.development.js:25846
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at popHydrationState (react-dom.development.js:12678:9)
    at completeWork (react-dom.development.js:22176:30)
    at completeUnitOfWork (react-dom.development.js:26593:16)
    at performUnitOfWork (react-dom.development.js:26568:5)
    at workLoopConcurrent (react-dom.development.js:26543:5)
    at renderRootConcurrent (react-dom.development.js:26505:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:38)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
throwOnHydrationMismatch @ react-dom.development.js:12507
popHydrationState @ react-dom.development.js:12678
completeWork @ react-dom.development.js:22176
completeUnitOfWork @ react-dom.development.js:26593
performUnitOfWork @ react-dom.development.js:26568
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12535:7)
    at updateHostComponent (react-dom.development.js:19902:5)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26560:12)
    at workLoopConcurrent (react-dom.development.js:26543:5)
    at renderRootConcurrent (react-dom.development.js:26505:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:38)
    at workLoop (scheduler.development.js:266:34)
throwOnHydrationMismatch @ react-dom.development.js:12507
tryToClaimNextHydratableInstance @ react-dom.development.js:12535
updateHostComponent @ react-dom.development.js:19902
beginWork @ react-dom.development.js:21618
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26560
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:19849 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js:19849:57)
    at beginWork (react-dom.development.js:21615:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26560:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
updateHostRoot @ react-dom.development.js:19849
beginWork @ react-dom.development.js:21615
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

### Your minimal, reproducible example

https://stackblitz.com/github/lucaswalter/astro-shadcn-tanstack-repro

### Steps to reproduce

See the repro project here: https://github.com/lucaswalter/astro-shadcn-tanstack-repro/blob/main/src/pages/index.astro#L41 or [StackBlitz](https://stackblitz.com/github/lucaswalter/astro-shadcn-tanstack-repro?file=src%2Fpages%2Findex.astro%3AL43)

1. Clone repro project
2. Install dependencies
3. Run `npm run dev`
4. Open in browser and see error in console

### Expected behavior

As a user, I expect to be able to provide custom `cell` and `header` JSX which will render and hydrate on my website.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="466" alt="image" src="https://github.com/TanStack/table/assets/5252764/bcc3a21f-e6c2-4821-ac85-962a39198085">

### What's the expected result?

I would expect the component to be hydrated after initial render without errors.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/lucaswalter/astro-shadcn-tanstack-repro?file=src%2Fpages%2Findex.astro%3AL43

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hmm, I don't see anything immediately problematic in this code. This does seems like a hydration error rather than an Astro bug, though! Might be worth asking in the `#support` channel on [our Discord](https://astro.build/chat)?

I can see that the Amount column is rendered on the server, but causes a mismatch on the client. One possible workaround is to use `client:only="react"` so that the table is only rendered on the client, which assumes that you don't need a server rendered placeholder. Another possible reason for this is some invalid HTML being generated on the server and "corrected" by the browser before hydration (`table` elements in particular have funky rules).

**Comment by natemoo-re** [comment]
I'm going to direct you to share this in our [`#support` channel on Discord](https://astro.build/chat). Astro's behavior appears to be correct.

**Comment by natemoo-re** [comment]
I did look into your repro a bit and it seems like the problem is here. https://stackblitz.com/github/lucaswalter/astro-shadcn-tanstack-repro?file=src%2Fcomponents%2Fcolumns.tsx%3AL25

Something about the `header` and `cell` custom rendering functions isn't working on the client.

**Comment by lucaswalter** [comment]
That's what I noticed as well @natemoo-re, however this issue only reproduces for me when I try to render this component in Astro. When I use the same component in a simple react app, I don't have an issue which is what let me to post here in under the Astro issues.

Is it possible the `@astrojs/react` could be the source of this? I'm just at a loss here for a path forward.

**Comment by lucaswalter** [comment]
Thanks @natemoo-re, I'll take the conversation over to discord. I did also want to share here that using `client:only="react"` still did not end up working for me as a workaround.

When using that directive, the HTML inside a table cell ended up being completely empty even when trying to render static content in the rendering function like this:

```
  {
    accessorKey: "amount",
    header: "Amount",
    cell: () => <div>Test</div> // HTML is completely empty
  },
```

Would you expect that to still be handled by Astro?

**Comment by natemoo-re** [comment]
Hmm, if `client:only` isn't working then it's definitely something about the component. If this is only happening in Astro it might be something about our JSX transformation. Let me check on that quickly.

**Comment by lucaswalter** [comment]
Discord Support Thread in-case anyone else comes across something similar: https://discord.com/channels/830184174198718474/1130952479555735612
