### ISSUE TITLE
MDX pages that import components with scripts end up being included in the wrong context

### ISSUE THREAD

**Issue by TheConner** [withastro/astro#7710]
### What version of `astro` are you using?

2.8.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

I am using the MDX integration (0.19.7) with Astro. I have noticed that if I import astro components in MDX pages which have client-side script tags, and I then render frontmatter from those pages in a different pages, the scripts will execute.

For example ([**MWE link**](https://github.com/TheConner/astro-mdx-script-mwe)):

`HelloWorld.astro`
```astro
---
---
<script>
console.log("Hello, world!");
</script>
```

`testpage.mdx`
```mdx
---
slug: "/content/testpage"
title: "Testing Page"
---
import HelloWorld from "../../components/HelloWorld.astro";

<HelloWorld></HelloWorld>
```

`index.astro`
```
---
const mdxPages = await Astro.glob('./*.mdx');
---
<p>On this page, the script from HelloWorld.astro will be executed, but it does not need to be included / executed here</p>
<ul>
	{mdxPages.map((page) => {
		const frontmatter = page.frontmatter;
		return (
			<li>
				<a href={frontmatter.slug} >{frontmatter.title}</a>
			</li>
		)
	})}
</ul>
```

In this example I have a index page that simply lists all of the MDX pages I currently have. What happens is the script from the HelloWorld component gets included, but in this context it shouldn't be included as I am not rendering the body of this page. "hello world' gets printed to the console in both index and the testpage, but it should only be printed on the testpage.

The culprit here seems to be Astro.glob, I am globbing for mdx pages which inherently returns the page content and the frontmatter in the same object. Thus, if I choose to render the page content then Astro will need to include the script associated with that page. In this context however, I just have a simple listing of all MDX pages, so I only need the frontmatter from the MDX pages, the scripts need not be executed or ran.

In my eyes, there are two potential solutions (speculating as I don't know too much about how Astro works internally):
- Use the same Astro.glob mechanism but somehow determine where and how the page content is being rendered. If the page content gets rendered, include the scripts from that page's content so it displays properly. If not, do not bother including the script. I am speculating as I am not too familiar with Astro's internals, but this may be incredibly tricky to implement.
- A new API (or maybe there's an existing API that I missed whilst reading documentation) that only globs frontmatter, thus internally Astro does not have to include scripts from all the globbed MDX pages.

### What's the expected result?

In reference to the [MWE](https://github.com/TheConner/astro-mdx-script-mwe), "hello world" should not be printed to the browser console on the /index page. It should only be printed on pages that render the content of a MDX page -- or in other words, the script should only be imported and ran if absolutely needed. In this example where /index uses only the frontmatter, the scripts from all globbed mdx pages should not be included / ran.

### Link to Minimal Reproducible Example

https://github.com/TheConner/astro-mdx-script-mwe

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Unfortunately, this is a design limitation of the underlying [`import.meta.glob`](https://vitejs.dev/guide/features.html#glob-import) macro as implemented by Vite. `Astro.glob` is just a convenience wrapper around that.

There is a long history to this if you look through our issues. Most of the discussion is in https://github.com/withastro/astro/issues/3816, but searching for [`Astro.glob`](https://github.com/withastro/astro/issues?q=is%3Aissue+Astro.glob+is%3Aclosed) brings up a lot of others.

Since we aren't able to fix this design limitation, we introduced [Content Collections](https://docs.astro.build/en/guides/content-collections/) as a replacement for this API. Script/style bleed is properly addressed by the Content Collections feature. We understand that they're not exactly the same, but that is our recommended approach for dealing with dynamically imported `.mdx` files.

**Comment by TheConner** [comment]
I see, thank you for the quick response! I will look into content collections :+1:
