### ISSUE TITLE
Could not delete cookie when in function scope

### ISSUE THREAD

**Issue by proyb6** [withastro/astro#7715]
### What version of `astro` are you using?

2.8.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

Cookies can delete on non-SSR, after adding Node adapter, I found deleting a cookies in a function scope has no effect. See code example in the link provided.

In Node, it does not seem to delete the cookie permanently?

### What's the expected result?

Assume, the bug is found in Node.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nf1tnk-ca3kww?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by proyb6** [comment]
To add on, it work as expected when set and delete are called on the page-level, not on the page-level and component-level.

**Comment by natemoo-re** [comment]
I believe this is expected, since `Astro.cookies` actually sets the [`Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie) header behind the scenes. 

Astro responses begin streaming to the browser as soon as the page begins rendering. Because of that, `Astro.cookies` can only set headers before beginning to write to the body. This is the same limitation of `Astro.redirect`. I don't see this in the docs, though, so we'll need to update that.

**Comment by proyb6** [comment]
Prefer a warning or error when it's used in Astro components during run or build.

**Comment by olach** [comment]
I can confirm this. A cookie cannot be deleted if the delete operation is made inside a function scope.

For example inside a middleware:
```js
// This does not work:
if (SOME_DYNAMIC_VALUE) {
    cookies.delete('example_cookie');
}

// This works:
cookies.delete('example_cookie');
```

Example inside a page front matter:
```js
// This does not work:
if (SOME_DYNAMIC_VALUE) {
    Astro.cookies.delete('example_cookie');
}

// This works:
cookies.delete('example_cookie');
```

My solution for a workaround, was to create a separate route (`/logout`) where the cookie is deleted. But I would rather be able to delete the cookie directly inside the middleware.

Astro version: 3.5.5
