### ISSUE TITLE
Cannot deploy Vercel serverless function when using Node 20

### ISSUE THREAD

**Issue by Princesseuh** [withastro/astro#7717]
### What version of `astro` are you using?

2.9.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### What browser are you using?

N/A

### Describe the Bug

[The function here](https://github.com/withastro/astro/blob/4eba967d2b7e0593ed49f191b70dfea7a43e9829/packages/integrations/vercel/src/serverless/adapter.ts#L193) does [not take into account the versions of Node that Vercel actually supports](https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js#node.js-version)

### What's the expected result?

Perhaps show a warning if the current version of Node is unsupported, or fallback to the nearest version

### Link to Minimal Reproducible Example

N/A

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Closed by #7718
