### ISSUE TITLE
Astro.cookies different context?

### ISSUE THREAD

**Issue by proyb6** [withastro/astro#7719]
### What version of `astro` are you using?

2.8.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOs

### What browser are you using?

Firefox

### Describe the Bug

Cookies seem to have two different context: Cookies that set by other app, Cookies that set by Astro.

Cookie set by other app: `alert` has a value of `red`

Cookie read in Astro: `Astro.cookies.get('alert').value` return `red`
Cookies in Astro could retrieve the correct value set by the other app.

`Astro.cookies.set('alert', 'overwrites-cookie-value')`

When Cookie in Astro overwrites `alert` cookie with random values, the next page request/reload to other app which tried to set the new value to `alert` cookie will failed to reflect the correct value `red`, as the cookies is always retrieve value from Astro's context/control:

`Astro.cookies.get('alert')` returns
overwrites-cookie-value

Update:
To add on, upon checking on the browser, I ended up having 2 duplicate `alert` cookies with the same value `red`, the issue is due to duplicated cookies and could not even delete the existing cookie from Astro.

### What's the expected result?

Should not create duplicate cookies.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm unsure if this is a design limitation or if we can fix this, but I agree that deduplication would be desirable. 

Please include a minimal reproduction so that we can work on verifying and fixing this issue. Without a reproduction, it is significantly harder for our maintainers to work on issues like this.

**Comment by proyb6** [comment]
Further narrowing to cookie path issue, don't seem the path can be set in Astro.cookies? This was the problem that causing duplicate cookie if there are different path.

```
Astro.cookies.set({
        name: 'alert', 
        value: 'astro',
        path; '/',
    })
```
