### ISSUE TITLE
Astro redirects should not generate HTML stubs when using an adapter

### ISSUE THREAD

**Issue by mashehu** [withastro/astro#7731]
### What version of `astro` are you using?

2.8.5

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

MacOS

### What browser are you using?

Chrome, Firefox

### Describe the Bug

When using configured redirects on netlify I see the placeholder HTML with "Redirecting to: " for a moment, before the browser is redirected to the correct site. 

### What's the expected result?

Based on the wording in the documentation:
> When running astro build, Astro will output HTML files with the [meta refresh](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#examples) tag by default. Supported adapters will instead write out the host’s configuration file with the redirects.

 I assumed that the netlify adapter, would only write to the `_redirects` file, without generating these placeholder files, which give a quick flash of an unstyled page between pages.

See my minimal example deployment: https://main--thriving-dusk-04bc5b.netlify.app/

### Link to Minimal Reproducible Example

https://github.com/mashehu/astro-quickstart/tree/main

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jdozierezell** [comment]
I just dropped by to create the same issue. This began appearing after a recent update of the adapter and was not present prior to that.

**Comment by natemoo-re** [comment]
Ah yep, this behavior became more noticable when https://github.com/withastro/astro/pull/7644 was merged, but I suspect this has never worked properly in `hybrid` mode.

We should be bypassing these files in `hybrid` mode as well and only generate the `_redirects` file so Netlify can handle it.

**Comment by natemoo-re** [comment]
This is also relevant for the Vercel and Node adapters

**Comment by fprl** [comment]
Before creating a new issue:

I am trying to implement redirects but its not working in prod (in dev all good):
```javascript
redirects: {
  '/my-account/my-bookings/[hash]': '/nl/my-account/bookings/[hash]',
  '/my-account/my-profile': '/nl/my-account/profile',
  '/en/my-account/my-bookings/[hash]': '/my-account/bookings/[hash]',
  '/en/my-account/my-profile': '/my-account/profile',
  },
```
Everything gets redirected to `/`. Maybe this feature is for static builds? I'm using node adapter (I also see the placeholder).

Is this related to this PR? Thanks

**Comment by matthewp** [comment]
You can disable the stubs with `build.redirects = false` while still getting the `_redirects` config update. I think I agree that Netlify should be setting this for you. I'll look into it.

**Comment by paulrudy** [comment]
> This is also relevant for the Vercel and Node adapters in hybrid mode

I'm still seeing the "Redirecting to..." placeholders in Vercel. astro v 2.9.6, @astrojs/vercel v 3.7.4.

**Comment by disrae** [comment]
> You can disable the stubs with `build.redirects = false` while still getting the `_redirects` config update. I think I agree that Netlify should be setting this for you. I'll look into it.

When I set build.redirects = false, the redirects stop working.

**Comment by Seokhyeon315** [comment]
@disrae where did you put `build.redirects = false` in astro?

**Comment by zellwk** [comment]
This seems to happen on the latest Astro version. I'm using a Node adaptor and I still see the stub.
