### ISSUE TITLE
Client component causes unwanted inline style

### ISSUE THREAD

**Issue by osiegmar** [withastro/astro#7732]
### What version of `astro` are you using?

2.8.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

When using a component with the `client:*` directive, astro creates this inline style:

```html
<style>
  astro-island, astro-slot {
    display: contents
  }
</style>
```

This comes a bit unexpected as the config option `build.inlineStylesheets` is set to `never` (the default) which should cause "all styles are sent in external stylesheets" as the [documentation](https://docs.astro.build/en/reference/configuration-reference/#buildinlinestylesheets) says.

### What's the expected result?

Have external stylesheets exclusively.

### Link to Minimal Reproducible Example

https://astro.build

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This is expected. Island-related code is injected as inline scripts and styles for performance reasons, regardless of the `build.inlineStylesheets` configuration. We can clarify this in the documentation.

**Comment by natemoo-re** [comment]
Moved to docs issue https://github.com/withastro/docs/issues/3769
