### ISSUE TITLE
Building with @astrojs/vercel adapter outputs warnings.

### ISSUE THREAD

**Issue by susickypavel** [withastro/astro#7736]
### What version of `astro` are you using?

2.9.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Windows, Mac

### What browser are you using?

Chrome, Firefox

### Describe the Bug

Running `npm run build` on an empty project with Vercel adapter (edge function target) shows warnings below.

I should note that in one of my projects that is also deployed on Vercel there are similar warnings but they point to  different packages rather than `path-to-regexp` for example `solid-js/web`.

```
▲ [WARNING] Ignoring this import because "node_modules/path-to-regexp/dist.es2015/index.js" was marked as having no side effects [ignored-bare-import]

    dist/entry.mjs:7:7:
      7 │ import 'path-to-regexp';
        ╵        ~~~~~~~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json" file:

    node_modules/path-to-regexp/package.json:45:2:
      45 │   "sideEffects": false,
         ╵   ~~~~~~~~~~~~~

▲ [WARNING] Ignoring this import because "node_modules/path-to-regexp/dist.es2015/index.js" was marked as having no side effects [ignored-bare-import]

    dist/renderers.mjs:5:7:
      5 │ import 'path-to-regexp';
        ╵        ~~~~~~~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json" file:

    node_modules/path-to-regexp/package.json:45:2:
      45 │   "sideEffects": false,
         ╵   ~~~~~~~~~~~~~

▲ [WARNING] Ignoring this import because "node_modules/path-to-regexp/dist.es2015/index.js" was marked as having no side effects [ignored-bare-import]

    dist/chunks/index@_@astro.4cb2eba3.mjs:7:7:
      7 │ import 'path-to-regexp';
        ╵        ~~~~~~~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json" file:

    node_modules/path-to-regexp/package.json:45:2:
      45 │   "sideEffects": false,
         ╵   ~~~~~~~~~~~~~

▲ [WARNING] Ignoring this import because "node_modules/path-to-regexp/dist.es2015/index.js" was marked as having no side effects [ignored-bare-import]

    dist/chunks/404@_@astro.01afc1cf.mjs:7:7:
      7 │ import 'path-to-regexp';
        ╵        ~~~~~~~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json" file:

    node_modules/path-to-regexp/package.json:45:2:
      45 │   "sideEffects": false,
         ╵   ~~~~~~~~~~~~~

▲ [WARNING] Ignoring this import because "node_modules/path-to-regexp/dist.es2015/index.js" was marked as having no side effects [ignored-bare-import]

    dist/chunks/prerender.ba73c177.mjs:5:7:
      5 │ import 'path-to-regexp';
        ╵        ~~~~~~~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json" file:

    node_modules/path-to-regexp/package.json:45:2:
      45 │   "sideEffects": false,
         ╵   ~~~~~~~~~~~~~

▲ [WARNING] Ignoring this import because "node_modules/path-to-regexp/dist.es2015/index.js" was marked as having no side effects [ignored-bare-import]

    dist/chunks/pages/404.astro.313c1b21.mjs:5:7:
      5 │ import 'path-to-regexp';
        ╵        ~~~~~~~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json" file:

    node_modules/path-to-regexp/package.json:45:2:
      45 │   "sideEffects": false,
```

### What's the expected result?

No warnings

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-z7x12r?file=src%2Fpages%2F404.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sahilsuman933** [comment]
@Princesseuh, Could you please assign this issue to me?

**Comment by Princesseuh** [comment]
Sure, there you go. We typically don't really use assignments, but I figure doing it prevents someone from taking the issue without noticing.

**Comment by eligundry** [comment]
I would like to point out that this is also happening with the Netlify adapter as well.

**Comment by matthewp** [comment]
We have deprecated the Vercel Edge and Netlify Edge adapters due to compatibility issues and are encouraging people to instead use the serverless versions of these adapters, along with Edge Middleware, which we feel gives you the best of both worlds. Our adapter migration plan is laid out in this [roadmap issue](https://github.com/withastro/roadmap/discussions/631).

If you're still interested in deploying to these edge platforms I'd encourage you to build an adapter for it. You can use the edge adapter code as a starting point.

Closing as we are not planning on fixing edge adapter bugs (but will continue to support edge middleware).
