### ISSUE TITLE
Enabling view transitions breaks back functionality

### ISSUE THREAD

**Issue by MikeCarbone** [withastro/astro#7739]
### What version of `astro` are you using?

2.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Firefox

### Describe the Bug

Enabled the new view transitions and the back arrow no longer functions. The URL changes, but the view does not. Tested in latest chrome and firefox (view transition doesn't work in firefox, but back functionality still broken).

Details:
On my homepage `/`, I followed the steps [outlined here](https://docs.astro.build/en/guides/view-transitions/#built-in-animation-directives). On another page, I did not add any of the view configuration setup. One with the transition, one without. When I navigate from the page with the transitions enabled to the non-enabled page, the transition will fire and take me to the next page. When I try to use the browser back arrow, either by clicking it or swiping, the URL will change but the view will not.

### What's the expected result?

The back and forward arrows should function as expected.

The linked stackblitz isn't rendering anything and I don't have the patience to debug. But it's a simple implementation.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-b79kq3?file=src%2Fpages%2Fblog%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks. So if I got this right, it's

A - VT
B - No VT

A -> B (back) -> A that causes the bug?
