### ISSUE TITLE
The component js is lost after packaging.

### ISSUE THREAD

**Issue by J-env** [withastro/astro#7744]
### What version of `astro` are you using?

2.9.0+

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm,pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Since there is so much code in the project, it is difficult to find out what is causing it.
The following is the details page after construction as an example.

/dist/detail/v5.html:

<img width="1127" alt="image" src="https://github.com/withastro/astro/assets/25259920/7dd679b3-1807-44df-b16a-0a921558260c">

The <Modal /> component is used in the details page, but the <Modal /> component js is not imported in this js file.
There is no such problem in the development environment.
/dist/static-dev/hoisted.470aeb3d.js:

<img width="974" alt="image" src="https://github.com/withastro/astro/assets/25259920/9864f668-2607-4f93-8c94-ff8f093b38dc">

### What's the expected result?

It was good before version 2.9.0

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Hmm It might be caused by https://github.com/withastro/astro/pull/7707, which changes hoisted scripts detection across Astro files.

**Comment by natemoo-re** [comment]
A minimal reproduction would be extremely helpful if you're able to provide one.

**Comment by tillprochaska** [comment]
I’ve been seeing the same issue. We have multiple documentation sites built using Astro and share a few common components between them.

While I haven’t had the time yet to set up a minimal reproduction example, the site is open source. Maybe that’s already helpful.

* This is one of the Astro sites: https://github.com/alephdata/aleph/tree/develop/docs
* All pages include the `AlgoliaSearch` component (via a layout component) from [this package](https://github.com/alephdata/astro-theme-docs/blob/main/src/components/page/AlgoliaSearch.astro).
* When running `astro dev`, the JS for the `AlgoliaSearch` component is included on all pages as expected.
* When running `astro build`, the JS is *not* included.

I have temporarily locked the Astro version to 2.8.5 which *does not* have this problem.

**Comment by sermagnus** [comment]
Same issue

**Comment by ottomated** [comment]
The root issue here is #7857
