### ISSUE TITLE
context.url trim anything after #

### ISSUE THREAD

**Issue by Mahmoudgalalz** [withastro/astro#7749]
### What version of `astro` are you using?

Latest

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

Mac,

### What browser are you using?

Chrome

### Describe the Bug

the request URL, or context.url doesn't get me the whole url

### What's the expected result?

it should act like window.location.href

https://example.com/test#anything

anything after # get trimmed and I have no way to get them 

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I don't think this is possible. `window.location.href` is the client-side URL, so it has access to the full URL. The [`hash`](https://developer.mozilla.org/en-US/docs/Web/API/URL/hash) property of the URL is intentionally never sent to the server, it is for client-side behavior only.
