### ISSUE TITLE
Gsap scroll trigger and lenis scroll not compatible 

### ISSUE THREAD

**Issue by klevert-ope** [withastro/astro#7758]
### What version of `astro` are you using?

2.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

Npm

### What operating system are you using?

Windows 

### What browser are you using?

Chrome 

### Describe the Bug

1. When I click a link to the next page the scroll position of the page does not begin from the top.  (Lenis scroll)
 2. When navigating the pages back and forth; the gsap scroll trigger breaks and does not work as intended. (Gsap)   
 N/B: I have been experiencing the same issue on barba.js and swup.
Kindly help.

### What's the expected result?

I expected my scroll trigger to work as I intended in my case it was to pin a  section and this then enable the section to scroll the contents horizontally with a vertical movement and on complete it proceeds to the next section.
For the next page scroll position I expected it to proceed to the next page and start from the top and not the center.

### Link to Minimal Reproducible Example

Klevertopee.com

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Is this is a bug introduced by astro?

**Comment by klevert-ope** [comment]
Not astro, its the view transitions; it seems to be having the same issue
similar to barba.js and swup.js

**Comment by lilnasy** [comment]
Thank you for linking your website, but to fix this issue that isn't sufficient unfortunately. Could you create a reproduction from the basic template?
