### ISSUE TITLE
SSR: Defining other methods alongside page GET

### ISSUE THREAD

**Issue by romanzy313** [withastro/astro#7762]
### What version of `astro` are you using?

2.8.3

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

I am unable to define a HEAD or OPTIONS route at the same url as the page using SSR.

Here is my routes rolder structure
```
/someurl/index.ts
/someurl/index.astro
```

index.astro serves the needed page
contents of index.ts are the following:
```ts
import type { APIRoute } from "astro";

export const head: APIRoute = async (ctx) => {
  return new Response("", {
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "*",
    },
  });
};
```

### What's the expected result?

Without index.ts the page is accessible normally via a GET request.

When index.ts is added alongside index.astro, GET request returns 404 while HEAD returns correct headers.

I would expect that GET to an astro page still works, while non-GET requests are handled by index.ts

I can confirm the same behavior exists when defining POST, HEAD, or OPTIONS routes.

### Link to Minimal Reproducible Example

not needed

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You can actually handle any HTTP method in a .astro file.

```astro
---
if Astro.request.method === 'HEAD') {
  return new Response("", {
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "*",
    },
  });
}
---
<div>Normal stuff here</div>
```

Our router doesn't allow 2 files for the same route, so doing it the way you're suggesting isn't possible. If you'd like to explore other ways to do this sort of thing, I'd suggest bring it up for discussion here: https://github.com/withastro/roadmap/discussions
