### ISSUE TITLE
Customizing view translation doesn't work

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#7767]
### What version of `astro` are you using?

2.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Edge

### Describe the Bug

Using experimental view translation feature, when providing a expression to `transition:animate` like `transition:animate={slide({ duration: '0.4s' })}` it still fades. Expression values are ignored regardless of fade vs slide. Using string-values for default animation works for both.

### What's the expected result?

Using a expression as value for `transition:animate` should work to enable customizing ex. duration of `slide`. See https://docs.astro.build/en/guides/view-transitions/#customizing-animations

In repro, heading slides as expected using default slide-animation.
Body should slide out/in with 2.4s duration.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-stfdbe

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
That is very bizarre, checking it out.
