### ISSUE TITLE
client:only - Missing framework hint not throwing

### ISSUE THREAD

**Issue by birkskyum** [withastro/astro#7771]
### What version of `astro` are you using?

2.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

None

### Describe the Bug

When running the Astro unit tests and E2E tests, I've found 4 cases of client:only that doesn't have a framework hint. The [docs state](https://docs.astro.build/en/reference/directives-reference/#clientonly):

> **You must pass the component’s correct framework as a value!** Because Astro doesn’t run the component during your build / on the server, Astro doesn’t know what framework your component uses unless you tell it explicitly.

These tests appear to pass anyway, without throwing a "[Missing hint on client:only directive](https://docs.astro.build/en/reference/errors/no-client-only-hint/)".

The four cases are:

https://github.com/withastro/astro/blob/a3d36a88942823fad5bd7ccfe9d850a11b7df244/packages/astro/test/fixtures/0-css/src/pages/client-only-and-ssr/only.astro#L6

https://github.com/withastro/astro/blob/a3d36a88942823fad5bd7ccfe9d850a11b7df244/packages/astro/test/fixtures/astro-client-only/src/pages/index.astro#L8

https://github.com/withastro/astro/blob/a3d36a88942823fad5bd7ccfe9d850a11b7df244/packages/astro/test/fixtures/astro-client-only/src/pages/persistent-counter-standalone.astro#L13

https://github.com/withastro/astro/blob/a3d36a88942823fad5bd7ccfe9d850a11b7df244/packages/astro/e2e/fixtures/solid-circular/src/pages/index.astro#L12

### What's the expected result?

I expected these cases to throw a "[Missing hint on client:only directive](https://docs.astro.build/en/reference/errors/no-client-only-hint/)", due to the wording in the docs "You must pass".

### Link to Minimal Reproducible Example

Reproduced by `pnpm run test` or `pnpm run test:e2e` in astro, where these tests are passing

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I believe the docs say _must_ because there are _some_ cases where it is required, like if both React and Solid are enabled in your project. So to reduce unexpected errors, the docs recommend to always include it.

For Svelte files, we can use static analysis to determine that the component is a Svelte file because the import ends with `.svelte`. If the component comes from a package and the imported path does not end with `.svelte`, a hint would again be required.
