### ISSUE TITLE
Redirects uses base inconsistently

### ISSUE THREAD

**Issue by sasoria** [withastro/astro#7774]
### What version of `astro` are you using?

2.9.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

This is not a serious issue, but I noticed that the base path is used inconsistently when setting  configured redirects. The code below redirects from `/base/old-path` to `/base/new-path`

``` ts
export default defineConfig({
  base: "/base",
  redirects : {
    "/old-path": "/base/new-path"
  },
  output: "server",
  adapter: node({
    mode: "standalone",
  }),
});
```

### What's the expected result?

I expected this to work, i.e omitting the base entirely in redirects.
``` ts
export default defineConfig({
  base: "/base",
  redirects : {
    "/old-path": "/new-path"
  },
  output: "server",
  adapter: node({
    mode: "standalone",
  }),
});
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jhuzfh-rcjfax?file=src%2Fpages%2Findex.astro,astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, the redirects RFC did not mention base. The right hand side is interpreted as the final destination. Since we force usage of base in dev mode already I think it makes sense to also force you to use it in your redirects config. Going to close as I don't think we want to update this.
