### ISSUE TITLE
Minimal example fails with @astrojs/cloudflare

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/astro#7775]
### What version of `astro` are you using?

2.9.1

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

A minimal Astro project with the Cloudflare adapter installed, fails in production with this error:
```json
  "exceptions": [
    {
      "name": "TypeError",
      "message": "Failed to execute 'encode' on 'TextEncoder': parameter 1 is not of type 'String'.",
      "timestamp": 1690145312706
    }
  ],
```

Steps to reproduce:
1. Start a new Astro project. 
2. Add the Cloudflare adapter.
3. Deploy to CF Pages.

### What's the expected result?

Renders the minimal template page as expected.

### Link to Minimal Reproducible Example

https://github.com/TheOtterlord/astro-cf-repro/tree/9b9f172858f3c967d914a26b42bd8350d4eb947f

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wolves** [comment]
I am experiencing this as well and commented on an older related(closed) issue with my details as well.
https://github.com/withastro/astro/issues/6081#issuecomment-1646600176
