### ISSUE TITLE
AlpineJS syntax highlighting issue within loop

### ISSUE THREAD

**Issue by msfleischer** [withastro/astro#7779]
### What version of `astro` are you using?

2.9.2

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Syntax highlighting breaks when chaining modifiers using AlpineJS dot notation within an Astro loop.

### What's the expected result?

The syntax highlighting seems to work properly for the dot chained modifiers outside a loop, so having it work inside as well would be ideal.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-eejmra

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is unfortunately an issue out of our reach, we don't own the syntax highlighting used inside expressions, Microsoft does. As you've noticed, putting the same code outside an expression, where we do control the syntax highlighting, works just fine.
