### ISSUE TITLE
Vercel SSR Crashes When Trying To Use Fetch In a React Component

### ISSUE THREAD

**Issue by LorenzoBloedow** [withastro/astro#7789]
### What version of `astro` are you using?

2.9.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

The "render" serverless function for the Vercel adapter throws an ECONNRESET error when I use ``fetch`` inside a ``useEffect`` inside a React component.
My workaround was to use ``client:only``, this way it bypasses SSR and the fetch happens on the client, where no error is thrown.
Obviously, this is not the best solution as I'd still like to SSR some part of the React component before running ``useEffect`` on the client.

I guess my question is: Is this even possible? I'll admit this is my first time using Astro and I skimmed through the docs so I might've missed something about having to use ``client:only`` in React components that use hooks.
If so, I'd suggest for Astro to automatically set ``client:only`` when it detects a hook in a React component and log a warning or info, that'd be a pretty nice convenience!

In case this is not the intended behavior, here's the regression testing I've already tried so far (in order), so I can speed up things for you guys:

PACKAGE | VERSION
astro: 2.9.2
@astrojs/vercel: 3.7.4
@astrojs/react: 2.2.1
-------------------------
astro: 2.9.2
@astrojs/vercel: 3.7.4
@astrojs/react: 2.0.0
-------------------------
astro: 2.9.2
@astrojs/vercel: 3.7.4
@astrojs/react: 1.2.2
-------------------------
astro: 2.9.2
@astrojs/vercel: 3.7.4
@astrojs/react: 1.0.0
-------------------------
astro: 2.9.2
@astrojs/vercel: 3.0.0
@astrojs/react: 2.2.1
-------------------------
astro: 2.9.2
@astrojs/vercel: 2.0.0
@astrojs/react: 2.2.1
-------------------------
astro: 2.9.2
@astrojs/vercel: 2.3.4
@astrojs/react: 2.2.1

### What's the expected result?

As much as possible of the React component should be rendered on the server and then the rest on the client, instead of ``useEffect`` being executed on the server.

Note: When using the repo I linked for the minimal reproducible example, you should change the ``client:only`` directive to any other "client" directive in the ``<Libraries />`` component inside of ``Homepage.astro``, since that's how the ``<LibraryPreview />`` component throws the error.

### Link to Minimal Reproducible Example

https://github.com/LorenzoBloedow/portfolio

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I haven't used react for a bit, but as much as I remember, effects are not run on the server. They are client-side thing.

**Comment by LorenzoBloedow** [comment]
> I haven't used react for a bit, but as much as I remember, effects are not run on the server. They are client-side thing.

That's what I was expecting too but they seem to be running on the server in this case

**Comment by ematipico** [comment]
I fail to see how Astro can address an issue generated by a UI library, especially after I read your expectations from the issue template.  

Any input you can share to help you?

**Comment by natemoo-re** [comment]
I can assure you that Astro is not somehow bypassing React to run `useEffect` on the server for our own purposes. There must be something else going on here. Since it's only happening when deployed, I'm guessing there might be a bundling issue going on.

Unfortunately, it looks like your minimal reproduction has been updated and no longer includes the problematic code. Would you mind creating a **minimal** example on StackBlitz so that we can take a closer look?

**Comment by LorenzoBloedow** [comment]
> I can assure you that Astro is not somehow bypassing React to run `useEffect` on the server for our own purposes. There must be something else going on here. Since it's only happening when deployed, I'm guessing there might be a bundling issue going on.
> 
> Unfortunately, it looks like your minimal reproduction has been updated and no longer includes the problematic code. Would you mind creating a **minimal** example on StackBlitz so that we can take a closer look?

Sorry, I couldn't use StackBlitz so I made a branch on the same repository, I named it astro-bug-repro.
All you have to do is upload it to Vercel using Node version 18.16.1 (the version might not be relevant but it's how I did it)
Then you access the preview link and you'll (hopefully) see an error screen from Vercel.

**Comment by LorenzoBloedow** [comment]
@natemoo-re Why was this closed? I provided a minimal repro.
Sorry if I misunderstood something.

**Comment by matthewp** [comment]
Hey @LorenzoBloedow please provide a minimal reproduction; one that only contains the code needed to show the bug. I'm doubtful that Tailwind is required, or is so many files. Likely this bug should be able to reproduced using just 1 page and 1 React component using useEffect with a `client:load` on it.

**Comment by LorenzoBloedow** [comment]
> Hey @LorenzoBloedow please provide a minimal reproduction; one that only contains the code needed to show the bug. I'm doubtful that Tailwind is required, or is so many files. Likely this bug should be able to reproduced using just 1 page and 1 React component using useEffect with a `client:load` on it.

Sorry, here you go: https://github.com/LorenzoBloedow/astro-bug-minimal-repro
(I've discovered the bug actually stems from the use of a component from `react-spinners`)
