### ISSUE TITLE
Markdoc: Random p tags appear out of no where

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#7790]
### What version of `astro` are you using?

2.9.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I expected to write markdoc tags in a way that would produce no problems but. When I look at the out put HTML. I see the following things. I was using my library called `markdoc-html-tag-schemas` so I was using 

When I write a p tag it seems to create a p above and below it.

Whenever I render a block tag It seems to have a child of p automatically. When I do this

```md
{% a href="/" %}
  Back Home
{% /a %}
``` 

I get this

```html
<a>
<p>Back Home</p>
</a>
```

When I write a dl block  then put content inside of it like this.

```md
{% dl %}
  {% dt "Hyper Text Markup Language" /%}{% dd "The language that is used to render content on the web" /%}
  {% dt "Cascading Style Sheets" /%}{% dd "The language that is used to style content on the web" /%}
  {% dt "JavaScript" /%}{% dd "The language that is used to make content on the web interactive" /%}
{% /dl %}
```

I get 

```html
<dl>
<p></p>
  <dt>Hyper Text Markup Language</dt><dd>The language that is used to render content on the web</dd>
  <dt>Cascading Style Sheets</dt><dd>The language that is used to style content on the web</dd>
  <dt>JavaScript</dt><dd>The language that is used to make content on the web interactive</dd>
<p></p>
</dl>
```
 
 

### What's the expected result?

When I do this

```md
{% a href="/" %}
  Back Home
{% /a %}
``` 

I expect this

```html
<a>
<p>Back Home</p>
</a>
```

When I write a dl block then put content inside of it like this.

```md
{% dl %}
  {% dt "Hyper Text Markup Language" /%}{% dd "The language that is used to render content on the web" /%}
  {% dt "Cascading Style Sheets" /%}{% dd "The language that is used to style content on the web" /%}
  {% dt "JavaScript" /%}{% dd "The language that is used to make content on the web interactive" /%}
{% /dl %}
```

I expect this

```html
<dl>
  <dt>Hyper Text Markup Language</dt><dd>The language that is used to render content on the web</dd>
  <dt>Cascading Style Sheets</dt><dd>The language that is used to style content on the web</dd>
  <dt>JavaScript</dt><dd>The language that is used to make content on the web interactive</dd>
</dl>
```
 
 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-9vjszg?file=src%2Fcontent%2Fblog%2Ffirst-post.mdoc

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by louiss0** [comment]
By the way I'm using `@astrojs/markdoc` 0.4.3

**Comment by natemoo-re** [comment]
Have you verified that this issue only appears when using Astro's markdoc package, and that it's not an issue with your `markdoc-html-tag-schemas` package?

**Comment by louiss0** [comment]
> Have you verified that this issue only appears when using Astro's markdoc package, and that it's not an issue with your `markdoc-html-tag-schemas` package?

I'm not sure about what is happening but I'm sure that it's not about the package I realised that if I don't wrap tags in a way that it's close to the content the a "p"  will appear. I think this a markdoc issue I'll have to talk to them.

**Comment by louiss0** [comment]
When I posted this issue I thought the behavior was abnormal. Now I think this is expected behavior. I'll maybe talk to the markdoc people.

**Comment by louiss0** [comment]
When I posted this issue I thought the behavior was abnormal. Now I think this is expected behavior. I'll maybe talk to the markdoc people.
