### ISSUE TITLE
Astro Markdoc throws errors aggressively when frontmatter is invalid YAML

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#7801]
### What version of `astro` are you using?

2.9.1

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Stackblitz

### What browser are you using?

Chromium

### Describe the Bug

While editing the markdoc starter, I was able to crash the dev server, with an esbuild stacktrace. It seems to be triggered by saving a markdoc document with invalid frontmatter?

![image](https://github.com/withastro/astro/assets/10626596/33ee7d24-cd09-4f7f-80d0-d1d4f87d8555)

discord support thread ref: https://discord.com/channels/830184174198718474/1132700888734113902

### What's the expected result?

The markdoc integration should never crash, and should print an error / return an error in the dev server ui to indicate that the YAML frontmatter is invalid

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8sp5fi?file=src%2Fcontent%2Fdocs%2Fintro.mdoc

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
While dev servers crashes are typically p5, since this happens only in Markdoc, I figured P4 was more appropriate

**Comment by Thodor12** [comment]
I'm facing the same issue in my dev environment

**Comment by Princesseuh** [comment]
I cannot reproduce this using the latest version of Astro and the Markdoc integration, neither on Stackblitz or in local. It shows the error properly as I would expect: 

<img width="1207" alt="image" src="https://github.com/withastro/astro/assets/3019731/2c1dad58-b38b-4589-9d9c-a0137b54945c">

If this still happens, please tell me and I'll reopen the issue!
