### ISSUE TITLE
Experimental view transitions breaks navigation on the same page

### ISSUE THREAD

**Issue by NinoMaj** [withastro/astro#7803]
### What version of `astro` are you using?

2.9.3

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Hi Astro team,

Thanks for shipping experimental view transitions API, huge win for the web.
I've just tested it and it breaks navigation on the same page.

```astro
// index.astro
<a href="/blog">blog</a>
<a href="#test">test</a>

<div id="test">test</a>
```

1. navigate to another route - `/blog`
2. go back to original route -`/`
3. navigate to an `id` on the same page - `#test`
4. nothing happens

### What's the expected result?

`div` is scrolled into a view.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-a9ccjq-n4vkah?file=src%2Fpages%2Findex.astro,astro.config.mjs,src%2Flayouts%2FLayout.astro,src%2Fpages%2Fblog.astro,package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks! Will take a look.

**Comment by Alecyrus** [comment]
Are you guys notice this error in devtools? 
<img width="829" alt="CleanShot 2023-07-29 at 20 24 45@2x" src="https://github.com/withastro/astro/assets/13865581/0c86fe1d-6276-44a7-a148-1078d0f7ae1e">
Be more specifically, this error is related to View Transition feature.
<img width="718" alt="CleanShot 2023-07-29 at 20 26 04@2x" src="https://github.com/withastro/astro/assets/13865581/0bf05427-54ed-48a4-8e9a-ee27c3c73517">
