### ISSUE TITLE
Bare paths redirect to paths with a trailing slash in production

### ISSUE THREAD

**Issue by merrickclay** [withastro/astro#7808]
### What version of `astro` are you using?

9.8.0

### Are you using an SSR adapter? If so, which one?

Yes, Node.js

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Steps to Reproduce:
1. Create astro project
2. Run `npm astro add node`
3. Set `output: 'hybrid'` in astro config
4. Add `about.astro` to `pages` dir
5. Run `npm run build`
6. Run `node dist/server/entry.mjs`
7. In browser, navigate to `http://localhost:3000/about`
8. Notice redirect to `http://localhost:3000/about/`

### Notes:
- This seems to be at least related to https://github.com/pillarjs/send treating `/about/` as a file and `/about` as a directory
- Does not seem to be reproducible in stackblitz. Stackblitz's request handling may be masking the issue.

### What's the expected result?

We should be able to decide (maybe with some config) to allow both URLs with and without trailing slashes, or to redirect one to the other (3 options -- both, trailing redirects to bare, bare redirects to trailing).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xzttgu?file=sandbox.config.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by merrickclay** [comment]
- `trailingSlash` only applies to dev server.
- `build.format = 'directory'` would make the page `example.com/about/` (has trailing slash)
- `build.format = 'file'` would make the page `example.com/about.html`

This issue is a request to add a config option or update an existing option to allow a page to reside at `example.com/about` (no trailing slash), even when using hybrid SSR.

**Comment by matthewp** [comment]
`trailingSlash` doesn't only apply to the dev server. That's why it's. top-level option. `trailingSlash: 'never'` should be what you want. But maybe the Node adapter is not checking for the file in this case.

**Comment by natemoo-re** [comment]
@gvkhna The amount of issues we have with this particular config option definitely agrees with your assessment. I don't know that adding yet another option will make things any less confusing, though. We'll have to talk about this as a team.

**Comment by natemoo-re** [comment]
@bluwy did investigate https://github.com/withastro/astro/issues/5630 but we eventually just made a documentation change in https://github.com/withastro/astro/pull/8068

**Comment by natemoo-re** [comment]
Confirming, per @matthewp's comment, that the Node adapter doesn't seem to respect `trailingSlash: 'never'`

**Comment by gvkhna** [comment]
FWIW. I do think your assessment is right but if no other alternative is found a 4th option is still a reasonable solution as you really only have 4 possible situations related to this api. The node adapter not respecting trailingSlash: 'never' is probably a bug. 

1. Trailing Slash Only ('only')
2. Trailing Slash Never ('never')
3. Trailing Slash Priority (canonical) with redirect for non-trailing-slash ('priority')
4. Non Trailing Slash (canonical) with redirect for trailing slash. ('redirect')

Perhaps also 'always/ignore' is not well titled. Just my .02 for alternative naming that may be clearer. Cheers.
