### ISSUE TITLE
Environmental variables caused build error in Markdoc

### ISSUE THREAD

**Issue by ymcheung** [withastro/astro#7818]
### What version of `astro` are you using?

2.8.3 ~ 2.9.2

### Are you using an SSR adapter? If so, which one?

Deno Deploy

### What package manager are you using?

pnpm

### What operating system are you using?

macos 12

### What browser are you using?

Arc, Safari

### Describe the Bug

Hello! I switched to markdoc and content collection from markdown with Astro `2.8.3`.

I found environmental variables in markdoc content like this caused build error:

```
\`\`\`astro
// BaseHead.astro
---
const schema = JSON.stringify({
  '@context': 'https://schema.org',
  '@graph': [{
    '@type': 'WebPage',
    url: `${import.meta.env.PUBLIC_HOSTNAME}`,
    name: title,
    datePublished: published,
    dateModified: modified
  }]
});
---
\`\`\`
```

![CleanShot 2023-07-26 at 21 59 11@2x](https://github.com/withastro/astro/assets/4409977/a7f1cd56-1156-4c4a-b2d5-325fcd75952c)

In dev environment, the output is doing well (like that in the minimal reproduction example).

If I removed `import.meta.env.PUBLIC_HOSTNAME`, then the build was successful.

I upgraded Astro to `2.9.1` and still got this message. Will there be a possible fix or workaround for this?

Thank you!

### What's the expected result?

Build and deployment are successful

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-d25afu?file=src%2Fcontent%2Fposts%2Ffirst.mdoc

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue, seems like this may have been a regression.

It's very odd that this happens when running `astro build` only...

**Comment by matthewp** [comment]
Looks like it is building now. Not sure if there was a dependency updated that caused this or what. If you're still experiencing the issue and can update the example please file a new issue, thank you!
