### ISSUE TITLE
Can I customize the rendering priority when using the 'hybrid' mode

### ISSUE THREAD

**Issue by 516310460** [withastro/astro#7831]
### What version of `astro` are you using?

v2.8.0

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When I use 'hybrid', if 'SSG' exists, it will take priority over 'SSG'`

### What's the expected result?

When using 'hybrid', if you want to customize the priority, use 'ssr' or 'ssg'`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nhc9gb-malcwc?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I don't quite understand the description of the bug or how it's related to the minimal reproducible example you've linked. Choosing which pages are prerendered (SSG) vs SSR can be done using a [`prerender`](https://docs.astro.build/en/guides/server-side-rendering/#opting-out-of-pre-rendering) statement.

If you're asking for a way to prerender _and_ server-render the same route, that's not a feature we support at the moment but we welcome you to [open a discussion on our Roadmap](https://github.com/withastro/roadmap/discussions)
