### ISSUE TITLE
Vite manifest option doesn't include CSS files.

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [withastro/astro#7842]
### What version of `astro` are you using?

2.9.3

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

all

### Describe the Bug

When I build my app, using vite build manifest option sets to true, Astro only includes JS files and skip CSS ones in the manifest. (I can't even get it be generated in stackblitz, but as it work in local, I guess it's a problem on their side ?)

This is a problem because when you are using tailwind, astro build produce 2 different stylesheets, one for tailwinds and one for the CSS built from the `<style>` tags. 

In some use cases, we want to get the non-tailwind stylesheet path.

### What's the expected result?

The generated manifest.json should provide a way to get every stylesheets, like vite does by default, with something like that : 

```json
{
  "index.css": {
    "file": "index-526e452b.css",
    "src": "astro:tailwind/index.css"
  },
 "astro:style/style.css": {
    "file": "index-527e482b.css",
    "src": "astro:style/style.css"
  },
}
```

Something like that would allow us to read the manifest dynamically to fetch the stylesheets path.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yacdhd?file=dist%2Fclient%2F_astro%2Findex.3a65fd24.css

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Astro really doesn't have anything to do with the Vite manifest. We do use Vite's CSS plugin so I would think it would just work. @bluwy do you have any knowledge of how this manifest is produced and why ours would omit this?

If there's something we need to do to support this I don't think we should. We have our own manifest but it is not (currently) written to disc. That seems like a feature request.

**Comment by bluwy** [comment]
I don't quite see the manifest locally or on stackblitz, I think we're probably omitting it when we clean up the SSR static outputs? But even if we do emit it, I don't think it will be accurate as the Astro build step consists of two Vite builds.

The manifest is also usually used by frameworks only, and not for end-users. I'm not sure if we should commit to maintaining one.

Can you explain your overall goal for needing the manifest?

**Comment by Tanguy-Magnaudet** [comment]
> Can you explain your overall goal for needing the manifest?

I'm using Astro with wordpress. Tailwind is used for the overall frontend.
But, I'm rendering Gutenberg Blocks using Astro Components. It work well but tailwind might conflict in the admin area since every plugins can import anything in here, so I make sure I only use Astro in-component styling system.

At build time, it creates 2 stylesheets, one for tailwind, and one for the rest, it's perfect.

The problem is, I can't distinguish between the two sheets and it makes it not trivial to import only the one I want in Wordpress admin area.

I thought manifest could help me there,
I added this to my Astro config :
```js
export default defineConfig({
  // ...
  vite: {
    build: {
      manifest: true
    }
  } 
})
```

And, it worked, Astro outputed this manifest.json in the dist folder :
```json
{
  "_solid.7b9c65a7.js": {
    "file": "_astro/solid.7b9c65a7.js"
  },
  "astro-entry:@mylib/solidjs": {
    "file": "_astro/solidjs.a0464d8f.js",
    "imports": [
      "_solid.7b9c65a7.js"
    ],
    "isEntry": true,
    "src": "astro-entry:@mylib/solidjs"
  },
  "astro:scripts/page.js": {
    "file": "_astro/page.f7ec53a3.js",
    "isEntry": true,
    "src": "astro:scripts/page.js"
  },
  "node_modules/.pnpm/@astrojs+solid-js@2.2.0_@babel+core@7.22.9_solid-js@1.7.8_vite@4.4.7/node_modules/@astrojs/solid-js/dist/client.js": {
    "file": "_astro/client.ebcb7561.js",
    "imports": [
      "_solid.7b9c65a7.js"
    ],
    "isEntry": true,
    "src": "node_modules/.pnpm/@astrojs+solid-js@2.2.0_@babel+core@7.22.9_solid-js@1.7.8_vite@4.4.7/node_modules/@astrojs/solid-js/dist/client.js"
  }
}
```

But I was not able to reproduce it in Stackblitz.

Is there a way with an integration to create the manifest if Astro doesn't manage it ?

**Comment by bluwy** [comment]
Do you need the information to find which JS chunk imports which CSS chunk? Or only to differentiate if a CSS file is from tailwind and the rest (scoped CSS)?

If it's the latter, I'm not sure a manifest would help here. It might be easier to walk through the generated CSS files, read the contents and find hints that imply it's the main generated tailwind CSS.

**Comment by Tanguy-Magnaudet** [comment]
> Do you need the information to find which JS chunk imports which CSS chunk? Or only to differentiate if a CSS file is from tailwind and the rest (scoped CSS)?

Only if a CSS file is from tailwind or the rest in my use case. 

>  It might be easier to walk through the generated CSS files, read the contents and find hints that imply it's the main generated tailwind CSS.

Yes this is my current workaround. But it doesn't look super safe compared to a manifest, that's why I tried it in my astro config and opened this issue when I saw the generated code above.

**Comment by bluwy** [comment]
I don't think a manifest would help here. It only tells which chunks imports which other chunks, or CSS. It doesn't tell if that CSS is from tailwind or the rest. For now I think the workaround is the way to this issue.

**Comment by matthewp** [comment]
Going to close as this is not a feature we currently support. Please go to https://github.com/withastro/roadmap/discussions and provide your use-cases and maybe we can come up with some solution.
