### ISSUE TITLE
Scoped styled are not specific enought

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [withastro/astro#7855]
### What version of `astro` are you using?

2.9.4

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

all

### Describe the Bug

Not really a "bug".

Astro compile scoped style from this : 

```html
<style>
  h2 {
    color: red;
  }
</style>
```

To this : 

```html
<style>
h2:where(.astro-2HOU47ZN){color:red}
</style>
```

The problem is, using `h2:where()` results in a less specific selector compared to simply using `.astro-blablab{}`. When we utilize tools like `@tailwindcss/typography`, the prose class overrides some CSS rules, thereby compelling us to use named classes.

Unfortunately, this seems to undermine the strength of the scoped styles feature.

### What's the expected result?

A style tag directive like `is:specific` that would tell astro to compile more specific css for the current component.

### Link to Minimal Reproducible Example

None /

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Use `scopedStyleStrategy: 'class'`. This will be the new default in 3.0. https://docs.astro.build/en/reference/configuration-reference/#scopedstylestrategy
