### ISSUE TITLE
Build split: true, does not work with Hybrid

### ISSUE THREAD

**Issue by pijusz** [withastro/astro#7873]
### What version of `astro` are you using?

2.9.6

### Are you using an SSR adapter? If so, which one?

Vercel Serverless

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Firefox

### Describe the Bug

Quite simple, Hybrid split output throws an error:
```javascript
error   The option `build.split` can only be used when `output` is set to `"server"`.
  File:
    ...\PROJECT\node_modules\.pnpm\astro@2.9.6_@types+node@20.4.5_sass@1.64.1_sharp@0.32.4\node_modules\astro\dist\core\build\index.js:186:15
  Code:
    185 |       if (config.output !== "server") {
    > 186 |         throw new Error(
          |               ^
      187 |           'The option `build.split` can only be used when `output` is set to `"server"`.'
      188 |         );
      189 |       }
```
### What's the expected result?

Hybrid is exactly the same as server, just with prerender flipped. It should work.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wjcodz?file=sandbox.config.json,package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
That's not an issue, the error is intentional.

This was a design decision because not all the adapters are able to support static rendering (see Cloudflare). We might able to support it for `hybrid` for Astro 3.0, but this requires more work in the adapters.
