### ISSUE TITLE
SSR Streaming broken since version 2.9.3

### ISSUE THREAD

**Issue by LeanderG** [withastro/astro#7886]
### What version of `astro` are you using?

2.9.6

### Are you using an SSR adapter? If so, which one?

I tested Cloudflare and Node

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Firefox, Chrome

### Describe the Bug

Since version 2.9.3 (https://github.com/withastro/astro/releases/tag/astro%402.9.3) SSR streaming is not working.

In the minimal reproducible example, I added `await new Promise((resolve) => setTimeout(resolve, 3000));` to `Card.astro` which delays sending the entire document.

Switching back to 2.9.2 fixes the issue.

### What's the expected result?

Streaming should work. In the minimal reproducible example only rendering of `Card.astro` should be delayed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-31829z?file=src%2Fcomponents%2FCard.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mutheusalmeida** [comment]
I'm facing the same problem with the Netlify adapter. The fetch is not called at run time.

I downgraded to 2.9.2 and still doesn't work.

**Comment by eitelkrauss** [comment]
Streaming not working for me in production mode only in dev with `npx astro dev`
I'm on v4.15.6 and @astrojs/node: "^8.3.3"

reproduction: https://github.com/eitelkrauss/astro-repro
