### ISSUE TITLE
Ensure color contrast requirements are met in the CLI interface. 

### ISSUE THREAD

**Issue by mgifford** [withastro/astro#7905]
### What version of `astro` are you using?

v2.9.7

### Are you using an SSR adapter? If so, which one?

No idea

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Edge

### Describe the Bug

<img width="421" alt="Screenshot of the CLI" src="https://github.com/withastro/astro/assets/116832/0cdeaad1-76c1-4a79-90ed-2c5d3fa96215">

[white on #B05ED7](https://coolors.co/contrast-checker/ffffff-b05ed7)

[#5AC650 on white](https://coolors.co/contrast-checker/5ac650-ffffff)

[#34BBC7 on white](https://coolors.co/contrast-checker/34bbc7-ffffff)

[#00A700 on white](https://coolors.co/contrast-checker/00a700-ffffff)

### What's the expected result?

There should be more contrast between them. For suggestions, see https://contrast-finder.tanaguru.com/

### Link to Minimal Reproducible Example

CLI

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
So the terminal background color is determined entirely by the user's local settings, and there's no way (that I know of, please correct me if I'm wrong) to query the exact color of the user's background. There may be a few terminals that expose whether the user has a light or dark theme, though.

I can ask the team to take a look at this and adjust the colors so they work on both light and dark backgrounds. Maybe the best option is to just not use custom colors.

**Comment by natemoo-re** [comment]
Ah, I was going to close this as not actionable, but it looks like `NO_COLOR=true` doesn't actually work for us at the moment. We should fix that.
