### ISSUE TITLE
404 page missing CSS when 404 server Response redirects to static custom 404 page

### ISSUE THREAD

**Issue by paulrudy** [withastro/astro#7910]
### What version of `astro` are you using?

2.9.7

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Safari

### Describe the Bug

Perhaps a bit of an edge case, but with the following setup:
* server mode
* dynamic route (alphabetically first priority) `[...ssrPath].astro` redirects non-existing pages to 404 using `new Response` but does no page rendering
* dynamic route (alphabetically second priority) `[...staticPath].astro` renders pages statically (includes `export const prerender = true`)
*  custom `/pages/404.md`

The issue is: When deployed on Vercel, navigating to a non-existent page renders the custom 404 page, but without CSS.

Additional notes:
* Going directly to the 404 page _does_ successfully include CSS
* If the `Response` is changed to an Astro redirect (`return Astro.redirect('/404')`), CSS is included in the 404 page after the redirect
* This issue does not occur locally. With `vercel dev` or `astro dev`, CSS is included after the 404 Response.

### What's the expected result?

CSS should be included in the custom 404 page rendered after a 404 `Response`

### Link to Minimal Reproducible Example

[repo](https://github.com/paulrudy/astro-404-test.git)
[demo](https://astro-404-test.vercel.app)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! Looks like this was partially introduced by https://github.com/withastro/astro/pull/7754 which fixed the 404 behavior. In this case, the `404.md` page is server-rendered but when we rewrite the request, we're not including the correct CSS before rendering.

**Comment by paulrudy** [comment]
> Thanks for opening an issue! Looks like this was partially introduced by #7754 which fixed the 404 behavior. In this case, the `404.md` page is server-rendered but when we rewrite the request, we're not including the correct CSS before rendering.

I'm not sure how #7754 affected it, but in case it's helpful to know, I was encountering the issue before that was merged!
