### ISSUE TITLE
@astrojs/mdx causing CollectionDoesNotExistError error

### ISSUE THREAD

**Issue by liamkogan** [withastro/astro#7914]
### What version of `astro` are you using?

2.9.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Adding the @astrojs/mdx integration is causing a CollectionDoesNotExistError error when trying to access any collections from the content directory. 

### What's the expected result?

.md content should be accessible and render normally, as it does when the integration is removed. 

### Link to Minimal Reproducible Example

https://github.com/liamkogan/astro-CollectionDoesNotExistError-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I don't see any error in the repro. Also, the `config.ts` should be in `src/content/` not `src/content/hello-world/`

**Comment by liamkogan** [comment]
Thank you @bluwy seemed to be an issue with the location of the project on my machine.
