### ISSUE TITLE
Make social media articles consistent with for accessibility

### ISSUE THREAD

**Issue by mgifford** [withastro/astro#7927]
### What version of `astro` are you using?

git

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

None

### What operating system are you using?

Mac

### What browser are you using?

Edge

### Describe the Bug

The social media icons in the header file looks accessible:
https://github.com/withastro/astro/blob/main/examples/blog/src/components/Header.astro

But the ones in the footer don't:
https://github.com/withastro/astro/blob/main/examples/blog/src/components/Footer.astro

I am unsure why they are different. 

### What's the expected result?

I'd expect SVG images to be accessible, or be clearly marked as decorative. 

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/blob/main/examples/blog/src/components/Footer.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Probably just an oversight. Thank you for catching this! PRs welcome ♥️

**Comment by eniolajayi** [comment]
@natemoo-re Hello 👋, Is there a PR for this? Seems the solution is to add appropriate text content for screen readers.  We use a `<span>` element with the  `sr-only` class like in the Header component.

**Comment by jbrr** [comment]
Hope I didn't step on anyone's toes, but I just put up a quick PR to address this.
