### ISSUE TITLE
SyntaxError: The requested module svgo-node does not provide an export named 'optimize'

### ISSUE THREAD

**Issue by Albertyhu** [withastro/astro#7929]
### What version of `astro` are you using?

2.8.4

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome, Firefox

### Describe the Bug

I created a blog page with a search bar. The rest of the page is server rendered while search bar is a client component that gets hydrated. 
```
<form
    id="SearchBar"
    class = "grid whitespace-nowrap userselect-none border-none mt-10"
>
    <SearchInput client:load/>
</form>
```
However, the SearchInput component would cause the following error: 
SyntaxError: The requested module '/node_modules/svgo/lib/svgo-node.js?v=ef50a51e' does not provide an export named 'optimize' 

Also, the useEffect hook from either the preact and react library does not work. 

Here is the file for SearchInput component:
https://github.com/Albertyhu/Astro-Template/blob/main/src/components/search/client/searchInput.tsx

Here is the Github repository for the rest of the project: 
https://github.com/Albertyhu/Astro-Template/tree/main

### What's the expected result?

The error message shouldn't appear and the useEffect hook should work. 

### Link to Minimal Reproducible Example

https://snazzy-syrniki-043d2b.netlify.app/blog/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This is an issue with `astro-icon`, not your SearchInput component.

You need to add the following to your `astro.config.mjs` file because `svgo` doesn't ship a proper ESM version.


```js
defineConfig({
  vite: {
    ssr: {
      external: ['svgo']
    }
  }
}
```

See https://github.com/natemoo-re/astro-icon/issues/35 and https://github.com/natemoo-re/astro-icon/pull/111

**Comment by Albertyhu** [comment]
Thanks, @natemoo-re.
I added the code to the configuration, but the error still appeared, but I figured that the icon is being used in a React component, which I realize is the cause of the issue.
