### ISSUE TITLE
Children.map not working in astro component

### ISSUE THREAD

**Issue by david10sing** [withastro/astro#7930]
### What version of `astro` are you using?

2.9.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

We have a component from a design system which uses `Children.map` and then clones the children using `cloneElement`.

It appears that when using the component inside an Astro component, the component does not work properly as the cloned elements are missing some aria attributes which we append to the children.

### What's the expected result?

I would expect the `Children` map API to not affect the rendering of the children

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/astro-children-map-issue-jkz7v4

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
It looks like you are expecting the children to be React components, but they are not. They are Astro components. At the point they reach React they are strings. Astro gets rendered to strings, not to framework component instances.

This is as designed and not something we are able to change.

**Comment by david10sing** [comment]
Righto. Makes sense now. Thank you for the explanation @matthewp.

Does it make sense to state that using the `NavItem` component inside another React component (Nav), and then importing that react component in astro page would make the `NavItem` behave like a React component?
