### ISSUE TITLE
Nesting named slots does not work

### ISSUE THREAD

**Issue by KubaSzopa** [withastro/astro#7932]
### What version of `astro` are you using?

2.7.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When using named slots in one component and passing it to the other the slots do not pass through to the end component.

### What's the expected result?

Named slots should be passable or at least there should be a way around to do this.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-minimal-example-custom-tags-m2zmnu?file=src%2Fcomponents%2FComponentWithNamedSlot.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by qijizh** [comment]
In `ComponentWithSlot`, you should pass its recieved default slot to `ComponentWithNamedSlot`'s named slot, or it will be pass to `ComponentWithNamedSlot`'s default slot, and `ComponentWithNamedSlot` didn't define to recieve default. 
```astro
---
import ComponentWithNamedSlot from './ComponentWithNamedSlot.astro'
---

<div>
  <ComponentWithNamedSlot>
    <slot slot='some-content'/>
  </ComponentWithNamedSlot>
</div>
```

**Comment by KubaSzopa** [comment]
> 

Didn't come up with this solution. Works great, thanks @qijizh !
