### ISSUE TITLE
PDF attachment not rendering right when ViewTransition is enabled.

### ISSUE THREAD

**Issue by chenxsan** [withastro/astro#7947]
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Say I have a pdf file containing Chinese texts under `public` folder, and I have a link to that pdf file in one of my pages:

```
<a href="/chinese.pdf">A PDF containing Chinese.</a>
```

With ViewTransition enabled, clicking that link would return something like this:
<img width="1073" alt="CleanShot-a46EcksI@2x" src="https://github.com/withastro/astro/assets/1091472/063a8cfd-5e16-4016-8efe-2beb7299fc9d">

### What's the expected result?

I would expect the browser to show the pdf content.

### Link to Minimal Reproducible Example

https://github.com/chenxsan/astro-view-transition-pdf

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Could you add the `download` attribute here? We could support that as a way to signal the router not to treat it as page navigation.

We might also want a `data-astro-no-follow` (bikeshed) or something so you can prevent router navigation. cc @natemoo-re for ideas.

**Comment by chenxsan** [comment]
> Could you add the `download` attribute here? We could support that as a way to signal the router not to treat it as page navigation.
> 
> We might also want a `data-astro-no-follow` (bikeshed) or something so you can prevent router navigation. cc @natemoo-re for ideas.

but I don't want to download it, I just want to view the file in browser. Fyi, it's not just pdf file, all images would show the similar result:

<img width="705" alt="CleanShot-Zi8sJ6N1@2x" src="https://github.com/withastro/astro/assets/1091472/f70b2fad-5d23-40d6-871e-7eaf152ac14c">

**Comment by natemoo-re** [comment]
> We might also want a `data-astro-no-follow` (bikeshed) or something so you can prevent router navigation. cc @natemoo-re for ideas.

`data-astro-reload` or `rel="nofollow"` would work. SvelteKit supports the former.

**Comment by chenxsan** [comment]
> > We might also want a `data-astro-no-follow` (bikeshed) or something so you can prevent router navigation. cc @natemoo-re for ideas.
> 
> `data-astro-reload` or `rel="nofollow"` would work. SvelteKit supports the former.

Users don't have to add the attribute manually right? The compiler would handle them automatically?

**Comment by matthewp** [comment]
Yeah users would need to add it. By default we have to assume that same-site navigation is to another page and not to a file.

**Comment by martrapp** [comment]
I will go with `data-astro-reload`, which close to the names of this feature in other client-side routers like react router or the sveltekit router.

**Comment by matthewp** [comment]
@martrapp can you link to docs on those other routers?

**Comment by martrapp** [comment]
https://kit.svelte.dev/docs/link-options#data-sveltekit-reload
https://reactrouter.com/en/main/components/link#reloaddocument

**Comment by martrapp** [comment]
Do we need a mapping in the compiler for this? (e.g. transition:reload)?

**Comment by martrapp** [comment]
@chenxsan I changed the link in your example to 
```
	<a href="/chinese.pdf" data-astro-reload>A PDF containing Chinese.</a>
```
with the new Astro version (not yet released) the PDF is shows in the browser when the user clicks the link.
![image](https://github.com/withastro/astro/assets/94928215/d435014d-99d3-43f1-b8a1-f8e54cc38ce6)

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/8217. Will do a new RC tomorrow with these changes.
