### ISSUE TITLE
[astrojs/cloudflare] port build.split deprecation to cloudflare

### ISSUE THREAD

**Issue by alexanderniebuhr** [withastro/astro#7948]
I will work on this, 
we need to port https://github.com/withastro/astro/pull/7839 for the Cloudflare adapter in the next branch too.

**Comment by natemoo-re** [comment]
Thanks @alexanderniebuhr, that would be awesome! Keeping this open, but let us know when you're able to make a PR.

**Comment by alexanderniebuhr** [comment]
@natemoo-re in the coming two weeks should be feasible for me.

**Comment by natemoo-re** [comment]
https://github.com/withastro/astro/pull/8078 has been merged, so I'm going to close this. This should be released in https://github.com/withastro/astro/pull/8073!
