### ISSUE TITLE
RSS: wrong site type

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#7951]
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

When using `@astrojs/rss`, the `rss` function has a parameter `site` of type string. However, it expects a `URL` (from `context.site`) so we currently have to put `@ts-ignore` above.

### What's the expected result?

Fix the type from `string` to `URL`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-b8xj5x?file=package.json,src%2Frss.xml.ts&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I think it can accept both URL and string. We probably need to loosen it.

https://github.com/withastro/astro/blob/9b1de490753f67c9c24fad5d262642c879a1ca44/packages/astro-rss/src/index.ts#L72

**Comment by DerTimonius** [comment]
@bluwy Could you assign this to me? I'd love to help with this project!
