### ISSUE TITLE
A full-width space or `&emsp;` after a line break is replaced with a half-width space

### ISSUE THREAD

**Issue by k1350** [withastro/astro#7968]
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

When I insert a full-width space or `&emsp;` after a line break (2 spaces or `\`) , it seems to be replaced with a half-width space.

For example, 

```md
　Full-width space is inserted at the beginning of the paragraph.  
　Full-width space is inserted at the beginning of the new line.

 Half-width is inserted at the beginning of the paragraph.  
 Half-width space is inserted at the beginning of the new line.

&emsp;`&emsp;`   at the beginning of the paragraph.  
&emsp;`&emsp;` at the beginning of the new line.

&nbsp;`&nbsp;` at the beginning of the paragraph.  
&nbsp;`&nbsp;` at the beginning of the new line.
```

is rendered 

![capture](https://github.com/withastro/astro/assets/40417367/390bd8ae-b16b-4259-bcc4-207c0c7013cf)

### What's the expected result?

```md
　Full-width space is inserted at the beginning of the paragraph.  
　Full-width space is inserted at the beginning of the new line.

 Half-width is inserted at the beginning of the paragraph.  
 Half-width space is inserted at the beginning of the new line.

&emsp;`&emsp;`   at the beginning of the paragraph.  
&emsp;`&emsp;` at the beginning of the new line.

&nbsp;`&nbsp;` at the beginning of the paragraph.  
&nbsp;`&nbsp;` at the beginning of the new line.
```

is rendered

![スクリーンショット 2023-08-05 125019](https://github.com/withastro/astro/assets/40417367/ba278036-019b-4a82-80e2-eb41339c664d)

### Link to Minimal Reproducible Example

https://github.com/k1350/astro_fullwidth_space_sample

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm inclined to think this is a behavior of the CommonMark spec since [`remark`](https://github.com/remarkjs/remark) claims to be 100% compliant with CommonMark? I don't think [our `@astrojs/markdown-remark`](https://github.com/withastro/astro/blob/main/packages/markdown/remark/src/index.ts) logic has any specific handling for this case.

**Comment by natemoo-re** [comment]
Awesome, thanks for digging into it! Going to close this as it's an upstream issue.
