### ISSUE TITLE
netlify.toml

### ISSUE THREAD

**Issue by Malik-Shan** [withastro/astro#7970]
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

OperaGx, Chrome

### Describe the Bug

The netlify.toml to redirect and restrict pages not not working. According to Mr. Chris (core team member) that there is a chance it's broken due to the new redirect feature. I think so too. It works without astro SSR. Which I've set output: 'hybrid' & adapter: 'netlify()'. 
And also I dont know how to recreate the issue. The blitz wont' be able to use the netlify.toml. I'm hosting on it that's why it's working. It might be possible but I'm not that knowledgeable yet to configure those things. 

### What's the expected result?

I think if you use the netlfy.toml for redirect and restriction with astro SSR it wont work. Without SSR it works.

*netlify.toml
[[redirects]]
  from = "/cms/"
  to = "/cms/#/"
  force = true
  status = 200
  conditions = {Role = ['admin','editor']}
 // this only works without astro SSR.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pfezgk-nm8wbm?file=netlify.toml,src%2Fpages%2Fdocs%2Findex.astro,src%2Fpages%2Findex.astro,astro.config.mjs&on=stackblitz  (This is to be deployed on netlify tho for getting the bug & I dont know how to do that to the stackblitz repo here. )

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
You can create a minimal repository that reproduces the issue.

**Comment by maxstoyanov** [comment]
This is an issue that is quite common among frameworks that use a Netlify function to render on request. I found this to be an issue with Nuxt as well.

The `_redirects` file takes precedence over `netlify.toml` ([Source](https://www.youtube.com/watch?v=IWPDI01DsAo&t=2217s)). The first matching rule is used.

Astro uses the `_redirects` file to add one function that takes over the rendering of all routes that are not statically pre-rendered. By default, Netlify only serves rewritten routes if there are no matching files and folders.

The solution is to add all redirects through the `Astro.redirect` API. (I never used this API and can't elaborate if the precedence is correct.) User-added redirects must come before Astro defined ones.

**Comment by Malik-Shan** [comment]
https://stackblitz.com/edit/github-pfezgk-nm8wbm?file=netlify.toml,src%2Fpages%2Fdocs%2Findex.astro,src%2Fpages%2Findex.astro,astro.config.mjs&on=stackblitz (This is to be deployed on netlify tho for getting the bug & I dont know how to do that to the stackblitz repo here. )

**Comment by natemoo-re** [comment]
> This is an issue that is quite common among frameworks that use a Netlify function to render on request. I found this to be an issue with Nuxt as well.
> 
> The `_redirects` file takes precedence over `netlify.toml` ([Source](https://www.youtube.com/watch?v=IWPDI01DsAo&t=2217s)). The first matching rule is used.
> 
> Astro uses the `_redirects` file to add one function that takes over the rendering of all routes that are not statically pre-rendered. By default, Netlify only serves rewritten routes if there are no matching files and folders.
> 
> The solution is to add all redirects through the `Astro.redirect` API. (I never used this API and can't elaborate if the precedence is correct.) User-added redirects must come before Astro defined ones.

Thanks for the context! Seems like a valid (but annoying) workaround. I'm not sure if there's a way to use `_redirects` and also support user-defined redirects in the `netlify.toml` file? We might need to ask someone from Netlify.

**Comment by Malik-Shan** [comment]
For me if you me tho I dont have a _redirects file. It's just the netlify.toml. When I talked to someone on astro's discord they said there is a chance that when they added the astro's redirect  they forgot about netlify.toml and broke it.

**Comment by matthewp** [comment]
You'll want to put your redirects in a `_redirects` file instead for it to work with Astro SSR. When SSR is built we have to create a `_redirects` file to support its routing. And as others have said, Netlify takes this file over your netlify.toml config.

Closing as there's nothing for us to do here.
