### ISSUE TITLE
Using middleware with Netlify creates both edge and non-edge function calls

### ISSUE THREAD

**Issue by reaganchisholm** [withastro/astro#7971]
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Windows (WSL)

### What browser are you using?

Chrome

### Describe the Bug

When using middleware with the Netlify adapter (non edge functions), during build both a [Netlify Function](https://docs.netlify.com/functions/overview/) and [Netlify Edge Function](https://docs.netlify.com/edge-functions/overview/) are created to handle middleware, seeming to create and run 2 separate functions on Netlify.

![image](https://github.com/withastro/astro/assets/19511364/8f5d03b8-2149-45c3-89b3-08cf1710f736)

![chrome_zM9q911mpn](https://github.com/withastro/astro/assets/19511364/2ab0835c-4d87-4391-b304-f394bf94c8c3)

### What's the expected result?

My expectation and interpretation from [the docs](https://docs.astro.build/en/guides/integrations-guide/netlify/#run-middleware-in-edge-functions), is that having middleware run on edge with the Netlify adapter is intended to be an opt-in thing. 

I haven't opted in or enabled them via the `import netlify from '@astrojs/netlify/edge-functions'` or `excludeMiddleware: true` API but edge functions are still being created, deployed and ran. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-t6lvzv?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@ematipico any idea here? With regular Netlify functions they are getting edge functions created.

**Comment by ematipico** [comment]
I'll have to investigate
