### ISSUE TITLE
"Modifying frontmatter programmatically" example doesn't work

### ISSUE THREAD

**Issue by bobaekang** [withastro/astro#7972]
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

N/A

### Describe the Bug

["Modifying frontmatter programmatically"](https://docs.astro.build/en/guides/markdown-content/#modifying-frontmatter-programmatically) example in docs doesn't work.

The original use case I had in mind was to programmatically derive frontmatter `pubDate` value from markdown filename.

### What's the expected result?

The expected result is for each blog entry's `data.astro.frontmatter` to have a programmatically appended `customProperty` property  when following the example.

In the reproducible example I've provided, each blog page should display the `customProperty` value (`'Generated property'`) under the title. See the image below:

![image](https://github.com/withastro/astro/assets/22449454/a07d27c2-efde-4cfb-afb0-a4f9e33010ef)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-iactdj-mvggak?file=src%2Flayouts%2FBlogPost.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by reaganchisholm** [comment]
hey @bobaekang, it seems like you're using "Content Collections" based on your reproducible repo which behaves differently for frontmatter and remark plugins. Here is a link to the [details about that in the docs](https://docs.astro.build/en/guides/content-collections/#modifying-frontmatter-with-remark)

To get what you're looking for you could modify `pages/blog/[...slug].astro` to pass along that data

```jsx
// pages/blog/[...slug].astro

---
// [...] other code

const post = Astro.props;
const { Content, remarkPluginFrontmatter } = await post.render(); // customProperty is in "remarkPluginFrontmatter"
---

<BlogPost {...post.data} customProperty={remarkPluginFrontmatter.customProperty}>
	<Content />
</BlogPost>
```

![image](https://github.com/withastro/astro/assets/19511364/a3adbebd-3b56-4f9d-a9f2-ec533c0a2c01)

There is a note in the docs under the heading you linked that points to the new content collections section but maybe its not clear enough in the docs currently, either way, hope that helps!

**Comment by bobaekang** [comment]
Thanks @reaganchisholm! Looks like I'm the one that's broken here. I need to read the docs more carefully... 😂
