### ISSUE TITLE
Vercel adapter + prerender + build split leads to an error

### ISSUE THREAD

**Issue by raulfdm** [withastro/astro#7973]
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Doesn't matter

### Describe the Bug

While trying to use Vercel adapter and `build.split = true`, pages with `export const prerender = true` throws the following error:

```
 prerendering static routes 
 error   Unable to find the manifest for the module file:///path/to/project/astro-vercel-build-split-prerender-error/apps/website/dist/src/pages/_lang_/entry.index.astro.mjs?time=1691298936496. This is unexpected and likely a bug in Astro, please report.
Error: Unable to find the manifest for the module file:///path/to/project/astro-vercel-build-split-prerender-error/apps/website/dist/src/pages/_lang_/entry.index.astro.mjs?time=1691298936496. This is unexpected and likely a bug in Astro, please report.
```

### What's the expected result?

Build without error or have instructions about pre-rendered pages.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qfges3

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by raulfdm** [comment]
Related https://github.com/withastro/astro/issues/7753

**Comment by AkashRajpurohit** [comment]
FYI this is not specific to Vercel adapter. Happening for Cloudflare adapter as well.

**Comment by ematipico** [comment]
@raulfdm can you check if 2.10.10 fixes your issue?

**Comment by raulfdm** [comment]
@ematipico I've updated my stackblitz repo to latest version of astro and astro vercel:

```json
  "dependencies": {
    "@astrojs/vercel": "3.8.2",
    "astro": "2.10.14"
  }
```

The error remains:
![CleanShot 2023-08-28 at 15 53 25](https://github.com/withastro/astro/assets/12464600/7e8b1651-b4cb-4ec5-8969-6406038fdd56)

**Comment by raulfdm** [comment]
Well... the release will happen around the next days, right? As soon as it lands I'll check this out... thanks for getting back with this.

**Comment by jacobthesheep** [comment]
Just checked. No errors.

**Comment by ematipico** [comment]
Thank you! Closing as resolved
