### ISSUE TITLE
addEventListener lost after ViewTransition enabled

### ISSUE THREAD

**Issue by dehbini** [withastro/astro#7982]
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I added some click eventListener to navigation bar. After enabling ViewTransition, the click listener works only on first page load, after navigating to another page, I lost the click event on those elements.

### What's the expected result?

If I add el.addEventListener('click', someFunc) to some elements, and those elements are in DOM even after navigating to other pages, the event should still work.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-stfdbe-97paz7?file=src%2Fpages%2Findex.astro,src%2Fpages%2Ftwo.astro,src%2Fcomponents%2FLayout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This is by design. You can use the [`transition:persist`](https://docs.astro.build/en/guides/view-transitions/#maintaining-state) directive or listen for the [`astro:load`](https://docs.astro.build/en/guides/view-transitions/#astroload) event to handle behavior across page navigations.
