### ISSUE TITLE
Custom 500 page content-type is text/plain;charset=UTF-8

### ISSUE THREAD

**Issue by minht11** [withastro/astro#7992]
### What version of `astro` are you using?

2.10.3

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Firefox, Safari

### Describe the Bug

Have a page which returns 500 response.
Here is how behaviors differ:
- in dev mode it will show body of the 500 response.
- in build mode it will display actual custom 500 page, but its content-type header will be text/plain;charset=UTF-8

<img width="446" alt="Screenshot 2023-08-08 at 12 04 19" src="https://github.com/withastro/astro/assets/8914032/f25acdac-9662-4a64-8915-54a196634ab5">

### What's the expected result?

Behavior of 500 response is consistent between modes, and content-type is returned correcly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pt4enm-mla9j5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I think the difference here is because you're using `new Response('Response text', { status: 500 })` rather than `new Response(null, { status: 500 })`. We try to merge the responses, so the first one gets the original `content-type` while the second has no body and therefore the `text/html` `content-type` is automatically inferred.

An edge case we should fix, but that should unblock you for now.

**Comment by SudoCat** [comment]
Encountered the same issue today in Astro 2.10.6 - in our case, we return JSON responses as the body in all the templates that can error, as historically this gave a better debugging experience in development environments on older versions of Astro with node adapter (when 404/500 error states did not display the error page).

For now I've just created a simple middleware to enforce text/html on 4xx and 5xx pages - should we instead be replacing all of our response bodies with `null`?

**Comment by lilnasy** [comment]
> For now I've just created a simple middleware to enforce text/html on 4xx and 5xx pages - should we instead be replacing all of our response bodies with null?

I think so, the body gets replaced anyway.

If we were to address this behavior, implementation-wise it's not difficult to overwrite the Content-Type.

But if we are actively making a decision, I think it should be to warn that the body you provide is ignored.

**Comment by ematipico** [comment]
@lilnasy is this something that will be solved by your `Astro.reroute` proposal?

**Comment by lilnasy** [comment]
Yes - by deprecating implicit rerouting.

[Link to the proposal](https://github.com/withastro/roadmap/discussions/681#discussioncomment-6926305).
