### ISSUE TITLE
Prerended custom 500 page does not include imported stylesheets

### ISSUE THREAD

**Issue by minht11** [withastro/astro#8005]
### What version of `astro` are you using?

2.10.3

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Firefox, Safari

### Describe the Bug

Prerended custom 500 page does not include imported stylesheets in production mode. Changing prerender to false, fixes it. 

### What's the expected result?

Stylesheets are imported correctly inside custom 500 page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pt4enm-cr35nf

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hmm, this is surprising because it should be passing through the `500` page directly. Will take a look at this!

**Comment by lilnasy** [comment]
Seems to have been introduced with #7946.

Last good version 2.10.1.

**Comment by lilnasy** [comment]
Spot on!

500.astro is prerendered with the appropriate styles in <head> but the matched 500 route gets generated just-in-time

And because it's supposed to be prerendered, styles and scripts are empty arrays in the manifest.

**Comment by lilnasy** [comment]
> Seems to have been introduced with https://github.com/withastro/astro/pull/7946. (edit: confirmed)
>
> Last good version 2.10.1.

Correction: this issue was **not** introduced by that PR. It only made it so that 500 fallback routes does **not** inherit styles/scripts from the original route that failed.
