### ISSUE TITLE
Example with-markdoc: uses deprecated getEntryBySlug

### ISSUE THREAD

**Issue by teinett** [withastro/astro#8008]
### What version of `astro` are you using?

example docs

### Are you using an SSR adapter? If so, which one?

example docs

### What package manager are you using?

example docs

### What operating system are you using?

example docs

### What browser are you using?

example docs

### Describe the Bug

https://github.com/withastro/astro/blob/16161afb2b3a04ca7605fcd16de06efe3fabdef2/examples/with-markdoc/src/pages/index.astro#L2:
`import { getEntryBySlug } from 'astro:content';`

Docs https://docs.astro.build/en/reference/api-reference/#getentrybyslug:
"DEPRECATED
Use the [getEntry() function](https://docs.astro.build/en/reference/api-reference/#getentry) to query content entries. This accepts the same arguments as getEntryBySlug(), and supports querying by id for JSON or YAML collections."

### What's the expected result?

Example doesn't use deprecated code.

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/blob/main/examples/with-markdoc/src/pages/index.astro#L2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Yep, we probably just missed this when deprecating `getEntryBySlug`! 

PRs welcome, should be a quick fix 😄

**Comment by snitin315** [comment]
I'll send a fix for this.
