### ISSUE TITLE
Assets & Middleware crash when using Vercel serverless

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/astro#8014]
### What version of `astro` are you using?

2.10.3

### Are you using an SSR adapter? If so, which one?

Vercel (Serverless)

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

Builds crash in a project containing a middleware file, with assets enabled, that uses the Vercel serverless adapter.

### What's the expected result?

Project builds successfully.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u5dbiv?file=astro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Does adding `build: { split: true }` to your config change anything? We should be setting that automatically but maybe we're not.

**Comment by TheOtterlord** [comment]
Nope. Adding that to the repro doesn't fix it. It also doesn't work in `hybrid` mode.

**Comment by jacobdalamb** [comment]
Does the build crash on that reproducible example or on when vercel builds it on deployment? Because build doesn't crash for me.

**Comment by ematipico** [comment]
@TheOtterlord can this issue be closed? we made many changes, and I believe everything should be fine now

**Comment by TheOtterlord** [comment]
Yep! Confirmed this works fine in the latest versions
