### ISSUE TITLE
TS error for "id" attribute on dynamic HTML tag/component

### ISSUE THREAD

**Issue by basher** [withastro/astro#8024]
### What version of `astro` are you using?

2.8.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### What browser are you using?

Firefox

### Describe the Bug

I get the following TS error when adding an "**id**" attribute to a custom HTML component:

![TS-error](https://github.com/withastro/astro/assets/452809/85d6a473-d4ca-4516-9366-8922a14d2d7a)

I've even extended "**HTMLAttributes**" to no avail.

```
import type { HTMLAttributes } from 'astro/types'
interface Props extends HTMLAttributes<'h1'> {
    headingLevel: string;
    headingText: string;
    id?: string;
}

const { headingLevel, headingText, id } = Astro.props;
const HeadingElement = `h${headingLevel}`;
---

<HeadingElement class:list={['title']} id={id}>
    <img src="images/star.webp" alt="" width="135" height="138" loading="lazy" />
    <span>{headingText}</span>
</HeadingElement>
```

### What's the expected result?

No TS error for HTML attribute.

### Link to Minimal Reproducible Example

https://github.com/basher/basher-website/blob/master/src/components/Title.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Ah I see what's happening here! So `id` does exist for elements typed as `HTMLTag` (an alias for `keyof astroHTML.JSX.DefinedIntrinsicElements`), but not for elements that are generically `string`. Seems like this doesn't have anything to do with the `Props` interface or `HTMLAttributes`.

Updating your code to use the following makes the error go away!

```astro
---
import type { HTMLTag } from 'astro/types';

const HeadingElement = `h${headingLevel}` as HTMLTag;
---
<HeadingElement id={id} />
```

**Comment by basher** [comment]
Thanks @natemoo-re for your quick response... works a treat!

Might it be worth updating the [TS / HTML attribute docs](https://docs.astro.build/en/guides/typescript/#built-in-html-attributes)?

**Comment by natemoo-re** [comment]
Great call, I will open an issue on the docs repo!
