### ISSUE TITLE
`astro add` causes dev dependencies to be removed from node_modules

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/astro#8037]
### What version of `astro` are you using?

2.10.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

Using `astro add` causes a weird issue, where any existing installed dev dependencies will be removed from `node_modules`.

Stackblitz has repro instructions, but here's some you can also use locally.

1. new project (`npm create astro@latest`)
2. install a dev dependency (e.g. `npm i daisyui -D`)
3. check it exists in node_modules
4. use astro add (e.g. `npx astro add react -y`)
5. check to find the dev dependency missing from node_modules, but still in the package.json

### What's the expected result?

Dev dependencies to still be present, after using `astro add`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3sk8rq?file=md!README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thank you for the lovely reproduction, as usual! This is a weird one. I wonder if we're accidentally running `npm install` in production mode? That's probably the case.

**Comment by jacobthesheep** [comment]
> Thank you for the lovely reproduction, as usual! This is a weird one. I wonder if we're accidentally running `npm install` in production mode? That's probably the case.

I want to create a PR for this issue and based on what you said, I can't seem to find where this might be happening in the  [index.ts file](https://github.com/withastro/astro/blob/main/packages/astro/src/cli/index.ts) of `astro add` or in [install-package.ts file](https://github.com/withastro/astro/blob/main/packages/astro/src/cli/install-package.ts)
