### ISSUE TITLE
middleware / endpoint discrepancy

### ISSUE THREAD

**Issue by altano** [withastro/astro#8045]
### What version of `astro` are you using?

2.10.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

Middleware expects everything in its pipeline to return a proper `Response` object, but endpoints (`APIRoute`) don't require that `Response` objects be returned. This creates a situation where if you have perfectly valid API endpoints in your request pipeline, middleware breaks.

In the attached stackblitz repro I have added the official astro RSS plugin and a barebones middleware that just passes content through:

```ts
export const onRequest = defineMiddleware(async (context, next) => {
  return await next();
});
```

When building I get this error:

```
 generating static routes 
▶ src/pages/index.astro
  └─ /index.html (+10ms)
λ src/pages/rss.xml.js
11:46:21 PM [middleware] Using simple endpoints can cause unexpected issues in the chain of middleware functions.
It's strongly suggested to use full Response objects.
 error   Any data returned from middleware must be a valid `Response` object.
  File:
    /home/projects/github-b6qvcs-ibu1iq/node_modules/astro/dist/core/errors/errors.js:30:5
  Code:
    29 |     this.hint = hint;
    > 30 |   }
         |     ^
      31 |   setFrame(source, location) {
      32 |     this.frame = codeFrame(source, location);
      33 |   }
  Stacktrace:
MiddlewareNotAResponse: Any data returned from middleware must be a valid `Response` object.
    at new AstroError (/home/projects/github-b6qvcs-ibu1iq/node_modules/astro/dist/core/errors/errors.js:30:5)
```

To work around this I had to add this code to my middleware:

```ts
    if (isEndpointOutput(response)) {
      return new Response(response.body, {
        status: 200,
        headers: response.headers,
      });
    }
```

With an implementation of:

```ts
function isEndpointOutput(endpointResult: unknown): boolean {
  return (
    endpointResult != null &&
    !(endpointResult instanceof Response) &&
    typeof endpointResult === "object" &&
    "body" in endpointResult &&
    typeof endpointResult.body === "string"
  );
}
```

### What's the expected result?

Builds cleanly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-b6qvcs-ibu1iq?file=src%2Fmiddleware.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
This is a design decision, as you might have guessed from the log in your console. It's not a bug.

In Astro 3.0 we will deprecate simple objects being returned from endpoints and provide some APIs to bridge the gap.
