### ISSUE TITLE
New astro assets images pipeline should deduplicate images with identical props

### ISSUE THREAD

**Issue by mastfissh** [withastro/astro#8047]
### What version of `astro` are you using?

2.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

N/A

### Describe the Bug

I have two components that display the same image on different pages.

One of them uses GetImage, and one of them uses the Image component. They both have width=700

When I run build, I get two identical images generated of width 700. 

Note that if I tweak them both to use GetImage, they deduplicate correctly, so worth noting this as a workaround.

See https://github.com/mastfissh/safety_matrix/commit/50c3d244b3950301c4e9893a87cc16577d3a8a2f which is a commit that implements this workaround

### What's the expected result?

I would hope for the generated image result to be deduplicated - ideally the name would be related to the properties somehow, so the image could be cached in between pages.

### Link to Minimal Reproducible Example

https://github.com/mastfissh/safety_matrix/commit/50c3d244b3950301c4e9893a87cc16577d3a8a2f

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
The names are based on the transform content and they are deduplicated, so not quite sure why it's generating two images in your case 🤔

**Comment by chromakode** [comment]
This is happening for me as well. If I remove the `transition:name` directive from my `<Image>` components, I see a single image emitted. It appears that values other than image transform properties are being included in the hash.
