### ISSUE TITLE
Rendering issues with superscript & special characters in simple astro component (cloudflare ssr adapter)

### ISSUE THREAD

**Issue by lucaswalter** [withastro/astro#8057]
### What version of `astro` are you using?

2.10.7

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I just recently uplifted to Astro version **v2.10.7** and **6.8.0** of the cloudflare adapter but have hit this issue on the past few Astro versions.

On my site, I am fetching json for a game which includes superscript characters **"Apex Legends™"** in its name. After the json is fetched, I display in a simple Astro component without making any modifications.

On the rendered webpage, strange characters are rendered instead of the expected superscript. Has anyone else seen similar behavior or been able to work around it?

**API Endpoint:** `https://api.steambase.io/games/apex-legends`
**Live Page:** `https://steambase.io/games/apex-legends`

**Deployed Cloudflare Page (With Weird Characters on "Apex Legends" H1 and '—' does not render properly on reviews card)**
<img width="978" alt="image" src="https://github.com/withastro/astro/assets/5252764/7a9787d9-4c16-4b7b-828f-7ef0213a5d21">

**Local Development Page (Super script characters and '—' render properly)**
<img width="971" alt="image" src="https://github.com/withastro/astro/assets/5252764/25905f40-fd33-445e-9570-787084bd05cf">

### What's the expected result?

I would expect the superscript and special characters like `—` to render as expected

### Link to Minimal Reproducible Example

https://steambase.io/games/apex-legends

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Usually this happens when `<meta charset="UTF-8">` is missing, but I do see it on your page. I think this might be because some of your `script` elements (initializing GTag, etc) come before the `<meta charset>` declaration.

> In order for all browsers to recognize a <meta charset> declaration, it must be
> 
> - Within the `<head>` element,
> - Before any elements that contain text, such as the `<title>` element, AND
> - Within the first 512 bytes of your document, including DOCTYPE and whitespace

https://code.google.com/archive/p/doctype-mirror/wikis/MetaCharsetAttribute.wiki

**Comment by lucaswalter** [comment]
@natemoo-re — you were spot on with your hunch around the analytics scripts. As a test I removed them on my deployed Cloudflare site and that resolved the issue.

In-case anyone else hits this issue, I was able to resolve this by moving analytics scripts such as GA4 and FB Pixel to the final code right before closing `</head>` .
