### ISSUE TITLE
Env vriables with Vite and Cloudflare, the new replace of getRuntime()

### ISSUE THREAD

**Issue by Mahmoudgalalz** [withastro/astro#8060]
### What version of `astro` are you using?

Latest

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Mac,

### What browser are you using?

Chrome

### Describe the Bug

I have no access to environment variables via cloudflare, and I do override the connection string an a ts file and import it in a route

### What's the expected result?

I should be able to access the old getRuntime() out of the new usage Astro.Locals.runtime

as I cannot access this in the .ts files 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wj2hw8?file=src%2Fdb.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Ah, I think this consideration was overlooked when switching to `Astro.locals.runtime`. Ideally `import.meta.env` should still work, though. IMO you shouldn't need to use `getRuntime` for this.

**Comment by alexanderniebuhr** [comment]
@Mahmoudgalalz `getRuntime()` should still be available as for now. We wanted to get feedback for potential issues, before removing it.

**Comment by kelvinz** [comment]
I have a similar question, how can I access my cloudflare env variables at my API endpoint on the server?

Docs say,
```
import type { APIContext } from "astro";
import { getRuntime } from "@astrojs/cloudflare/runtime";

export async function get({request}: APIContext) => {
  const runtime = getRuntime(request);
  // the type KVNamespace comes from the @cloudflare/workers-types package
  const { MY_KV } = (runtime.env as { MY_KV: KVNamespace }));

  return {
    // ...
  };
};
```
But since getRuntime is gone, how do I access the env?

**Comment by ematipico** [comment]
Probably we should write a better documentation. 

**Inside an `.astro` file**:

```astro
const runtime = Astro.locals.runtime;
```

**Inside an endpoint**

```js
export function get(context) {
	const runtime = context.locals.getRuntime();
}
```

**Comment by kelvinz** [comment]
@ematipico this is the error I'm getting from ts, `Property 'getRuntime' does not exist on type 'Locals'`

**Comment by ematipico** [comment]
> @ematipico this is the error I'm getting from ts, `Property 'getRuntime' does not exist on type 'Locals'`
> when I try running `const runtime = context.locals.getRuntime()`
> 
> Also, I'm planning to do this, is this correct? `const API_KEY = import.meta.env.DEV ? import.meta.env.API_KEY : runtime.env.API_KEY`
> So getting the api key from astro dev vs getting it from cloudflare env variables on server.

My bad, it should be just `runtime`.

**Comment by alexanderniebuhr** [comment]
> There doesn't seem to be anything in runtime

Could you provide a Minimal Reproducible Example?
The CF Runtime is only available after the Requests are made.

**Comment by alexanderniebuhr** [comment]
It does work for me (https://github.com/alexanderniebuhr/smoggy-spiral), maybe you can either provide a Minimal Reproducible Example or compare the difference to your code. **Also note, if you try to get it working with `astro dev`, that will not work. But that limitation is also existence for `getRuntime()`**

- https://smoggy-spiral.pages.dev/
- https://smoggy-spiral.pages.dev/api/someFile

**Comment by ematipico** [comment]
> There doesn't seem to be anything in runtime

Is it possible you checked that while running the **Dev server**? If so, that's expected.

You should see the info only if you build the project and deploy it to CF.

**Comment by kelvin-zhao** [comment]
So does this
`const API_KEY = import.meta.env.DEV ? import.meta.env.API_KEY : context.env.API_KEY`
make sense to test and run on dev to make sure everything works before pushing it to test on server?
Or is there a better way to do development for such endpoints?

I'm also wondering if there is way to use CORS or someway to ensure that this API endpoint can only be run by my project and its domain?

Really thanks for the help thus far!

**Comment by kelvinz** [comment]
I'm getting `Property 'runtime' does not exist on type 'APIContext<Record<string, any>>'.`
when I tried `context.runtime.env.API_KEY`.

**Comment by kelvinz** [comment]
But how do you get rid of the typescript error?

**Comment by ematipico** [comment]
We are going to fix it in this PR: https://github.com/withastro/astro/pull/8190/files#diff-a74615b421da488d5e2bcf3e14c80732c192a374f51901a2064b3e2caef9d529
