### ISSUE TITLE
ViewTransition: link to self reloads

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#8069]
### What version of `astro` are you using?

2.10.7

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

Following #7849

When on a page (ie. `/`), clicking on a link that points to itself (`/`) reloads the page.

### Additional info

Open stackblitz in a new tab to see the page reload

### What's the expected result?

I think it shouldn't reload but scroll to the top with triggering the animation. This is what Nuxt does for instance.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-d5ubcr-bbzc7c

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue. PRs welcome! Otherwise, I'm sure we'll get fix this one before the feature stabilizes.

**Comment by martrapp** [comment]
I would like to help. But I think we have to consciously decide on a goal first. 

The last request was:

>  Tried with latest (2.10.1) and it now scrolls to top as well, but feels a bit weird. I think that, when on the same page, it should scroll up **without triggering the animation**
Originally posted by @florian-lefebvre in https://github.com/withastro/astro/issues/7849#issuecomment-1665623809_

The options:
a) Browser default navigation without animation (currently implemented). 
    Simple rule: same page navigation in not intercepted at all.
b) Clientside navigation and starting an animation 
c) Clientside navigation and not starting an animation. (Seems to go a bit against the original design)

Personally I think b) feels most naturally.  
It also seems worth mentioning that b) can already be enforced by linking to`/#` instead of `#`, i.e. by adding a hash. 

What is the planned way for Astro?

**Comment by martrapp** [comment]
Currently, we also have to find an answer for links that [start a view transition and should not:] (https://github.com/withastro/astro/issues/7947).
I would prefer to go with clear default rules and some simple mechanism to override the default behaviour when necessary (e.g. html attribut in link)

**Comment by matthewp** [comment]
Just curious, why do you have links to the same page? What is the use-case? I'm not used to doing this so I'm having a slightly difficult time thinking about what it should do.

I don't disagree with your rules @florian-lefebvre. Would accept a PR for that! I also agree with @martrapp and want to avoid a bunch of boolean flags to define how you want the behavior to be. Instead I think having an attribute like @martrapp mentioned and possibly some events to control the behavior is a better way.

**Comment by florian-lefebvre** [comment]
Common usecase is having a link in the header. When you click on it, you navigate to the concerned page so it becomes a link to the current page. Therefore I think it's likely to happen for many people

**Comment by florian-lefebvre** [comment]
We discussed with @martrapp on discord and here is the outcome of our discussion (correct me if I forgot stuff):

### Definition of "same page"

1. Same pathname
2. Same origin
3. Same searchString

Hash doesn't matter.

### Current implementation

- The current implementation of ViewTransitions starts some animation (fade-out, slide-out,...), copies the content of the new page into the old page, does some more animations (fade-in, slide-in...)
- for _[same page: just scroll]_, the implementation does nothing of that but let the browser handle it.
- The browser scrolls to hash links and it reloads links without hashes.
- If you want for the self page link without hashes to scroll to the top without visual reload, your only alternative currently is: "starts some animation (fade-out, slide-out,...), copies the content of the new page into the old page, does some more animations (fade-in, slide-in...)"

### All possible cases

We only cover "internal" pages, ie. same domain

1. Same page with hash
2. Same page without hash
3. Other page

### Pseudo-code

```ts
if (isSamePage) {
  if (hasHash) {
    // do nothing = let browser handle it
  } else {
    window.scrollTo(0)
  }
} else {
  // transition stuff
}
```

### Other

For people searching where this code leaves: https://github.com/withastro/astro/blob/main/packages/astro/components/ViewTransitions.astro

**Comment by matthewp** [comment]
@florian-lefebvre I think that makes sense and that works for me! Thanks! I understand the header link use-case. I can imagine if you have persistent DOM you would of course want that to be preserved.

**Comment by matthewp** [comment]
@martrapp is this fixed by https://github.com/withastro/astro/pull/8182?

**Comment by matthewp** [comment]
Oh yeah it is, weird that GH didn't close this one itself.
