### ISSUE TITLE
HMR doesn't work on Vue components

### ISSUE THREAD

**Issue by TechAkayy** [withastro/astro#8071]
### What version of `astro` are you using?

2.10.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When updating Vue component (client:load applied), HMR doesn't apply. 

Here is the github repo - https://github.com/TechAkayy/pg-astro

In the stackblitz version of the github repo, in HeroSection, uncomment the console.log statement. The whole component vanishes from the page on HMR update. 

Again, refresh the page, and now change the count variable from 0 to 1. HMR again breaks. Same issue, the whole component vanishes from the page. 

![image](https://github.com/withastro/astro/assets/73772701/537d2859-8b84-4248-94ca-98cb0abb209b)

### What's the expected result?

HMR should apply correctly. 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/TechAkayy/pg-astro?file=src%2Fcomponents%2FHeroSection.vue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks, we'll take a look at this as soon as we can!

**Comment by natemoo-re** [comment]
I noticed that you're using both of these in the same component... is that supported? I don't think I've ever seen it before.

```vue
<script lang="ts">
  export default {
    data() {
      return {
        count: 0,
      }
    },
    mounted() {
      /* uncomment the below line */
      // console.log(this.count)
    },
  }
</script>

<script setup lang="ts">
  defineProps({
    name: {
      type: String,
      default: 'HeroSection',
    },
  })
</script>
```

**Comment by TechAkayy** [comment]
I just removed the second `script` section from the reproduction. The HMR issue still exists, and it doesn't seem to be related to the 2 script tags. 

Try opening the above stackblitz link, and uncomment the console.log line. 

Though very uncommon, for certain scenarios, the `script setup` can be used alongside normal `script` tag in a Vue SFC - https://vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script.

The above double script tags example in the [SFC playground](https://play.vuejs.org/#eNrtVktu3EYQvUp5Nv5ghoxtIIsBo9hWbMhBPoZtJAgwmx6yZthSs5vpj0cTQYAvkEW22XiZe+UEPkJeNz9DOZLiAwSQBmRXd9V7rz7si9nTts3eBZ4tZ4UrrWw9KaG3X61m3q1mRytNxOetsZ4q3oigPF3ENaJKeHHv/vBGZNkHqw/vRKUJ2i/pi/mwdNk9XPYLTbRzNXWSP6CgS9M0rD35mmnNyuxISc30IB935fCtnVGcKbO952vpshTs/jQAohV5Rwk08NLTcwDa/osk2CHIK2tad6+Ho0XDywM2v2/x+sZbqbcjpV6UJd09YWvecOml0Xd7c48DqCZACs9Nq4TnFLZohNTpCc+uFfro4iIFpstLQvCLTkW8wUU091vrh+T8XnGkwOd+IZTc6iWV0I0tKH388Ncff7///eOHP9/TCStl5vTUeWu0CP5OkdcPB0dt/0D0Mysoz+RNUt5sNrKUQlEhqLa8QaTa+9Yt81xET9k6SFXliJUcF7k4ojXSMbhzXlhgoYFuRm+Rp/EVabDv2JHAH/K7rf2O4++cGqllI5TaLxLD6opDaE+tkVBkYywJvTeoDGXMWTQAeQIFjy1bB7KKdrx20vM8YZuTsYO7WNMbo6ShnfR1p07Wi5IPqvwvz+fKcxV9VMp1JwVteEeAxFsrYneAkbIsqn1s4o3cBssV7LQ3YYxelKbio07IblfWnLoiT8u0keh8+sUEKoWmMjhvGvkbJw99e8fQo7NbMzRFNmSLXk4WU+qgnahGrb0xyiEtZ0xvhVQ7qas5vWZRIj/Q/aeQyiTBaa05xVS4TjpMDCYR/zuJKka2jaYaEw/Ht4xZlaqk6pSMZTcovJx4CmrMQqHk0fNKxtmJdLRiy1HZTk1nyzyuOFCu+DxLIvSSFjkOTp0cpnjvDhWJOqEaiUPV4rFxV10j5S2qTXuXn6RNVwKMvm8O9LSqOsnS+OvbbGNM7JKbIr1I5s+LdFxzeUYmdGykLlWoIG0sfFS785/w6aSK1vy/RToeazB9tAaXXQaUAC0P78n54RBRCtSZXf4Mp17h0JTNYfN1vIp8TP2kE0/EO+gW9B16uYmC9oUUyrM5PtINN+s4dszN3VGZ0nUgDkMsNmziFo0IjJY4zIrbG6yshYeHU4wlCqnAv5GuNLYaG8udDZ5+DexS0902ar7r51kacZ3Y4+DpR84aNdsYtNYw6KTff01jBdwMfIvzYY2Z0+THtbCl6KgsYpTFEGU1m+TlOvuYKjGCXu+vieYBN9bvIRyE+l6cS3rB1rK0Irr4RIsi7+8MRT5eJWbzmURTWL9oRJudgjLuc+nmsuoNmG3jXWY1w4Uvvh+QBN2ebROOJ7DlFncO2fCiMs2Tx9mj7NGXeSWdn65n7JrF2podvlSI2GmCO9clsHjkNw3tq0hi42J02x/bftpOEOGLZnbfpjVvA/c3KJyJObtm/dSddwxeWU7fytVstGFoouY78/M3P+B+NDE2pgqqZ3+D8TXjbhkixm7bs6ArwJ7sS2hfJmFRiW/d83PP2g2kItCkRtqf1D6+hfoB7uPs8aji5T9BJc5+)

**Comment by natemoo-re** [comment]
Thanks for clarifying, definitely still valid then! Will continue to investigate.

**Comment by louiss0** [comment]
I decided to just ignore it but yes the component disappears in SSR. Oh I'd like to add that it takes a long time to load

**Comment by McSmog** [comment]
Need fix this too

**Comment by TechAkayy** [comment]
Hi @natemoo-re, just checking if there are any workaround for now until this HMR issue is fixed? 

Could it be related to applying client directives directly on Vue components? Wondering if wrapping the Vue components in an .astro intermediary will help, though I haven't tried that. 

Thanks for looking into this!

**Comment by louiss0** [comment]
> Hi @natemoo-re, just checking if there are any workaround for now until this HMR issue is fixed?
> 
> Could it be related to applying client directives directly on Vue components? Wondering if wrapping the Vue components in an .astro intermediary will help, though I haven't tried that.
> 
> Thanks for looking into this!

He has not said anything in a long time. Did switching to 3.0.0 change anything?
