### ISSUE TITLE
create-vite code path does not wait for "astro:server:setup" hooks

### ISSUE THREAD

**Issue by eigood** [withastro/astro#8097]
### What version of `astro` are you using?

2.10.7

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

linux

### What browser are you using?

chrome

### Describe the Bug

```diff
--- node_modules/astro/dist/vite-plugin-integrations-container/index.js 2023-08-15 19:10:11.965464887 -0500
+++ fixed.js 2023-08-15 19:10:04.233526608 -0500
@@ -6,10 +6,10 @@
 }) {
   return {
     name: "astro:integration-container",
-    configureServer(server) {
+    async configureServer(server) {
       if (server.config.isProduction)
         return;
-      runHookServerSetup({ config: settings.config, server, logging });
+      await runHookServerSetup({ config: settings.config, server, logging });
     },
     async buildStart() {
       if (settings.injectedRoutes.length === settings.resolvedInjectedRoutes.length)

```

Sorry for the inline patch, but I modified my node_modules file directly to see if this worked.

Basically, all integration hooks can return a Promise<void>, so I added a astro:server:setup hook, and added passport-js+oidc-client middleware.  The later requires an internal await(), to talk to the external server to auto-discover the endpoint urls.  I track down the bug to a missing async/await pair in the vite-plugin-integrations-container file.

### What's the expected result?

I expect that if I have an async astro:server:setup hook, that `astro run dev` will wait for it to finish, before continuing on with the startup.

### Link to Minimal Reproducible Example

inline patch

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Yep, not sure how that happened! If you'd like to submit a PR with this patch, please do!

**Comment by eigood** [comment]
Ok, I'll see if I can do that; I was able to rework my hook, but it's ugly as it looks, and would be much simpler just using normal async/await.  Might take a day tho.
