### ISSUE TITLE
Error including ChildPart with Lit integration 

### ISSUE THREAD

**Issue by lschierer** [withastro/astro#8106]
### What version of `astro` are you using?

2.10.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I created a lit element that uses a custom directive, in this directive I need a ChildPart.  The include for this causes an error in the console:

```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/lit_async-directive_js.js...' does not provide an export named 'ChildPart' { at MyElement.ts:3:26}
```

This does not happen in stackblitz using the same element at https://stackblitz.com/edit/vitejs-vite-ywbuun

so I do not believe this is a vite/lit but or it should happen there as well.    I could not get a typescript element to work in stackblitz, but checking out the repo locally let me reproduce the bug. as a minimal repo.  

### What's the expected result?

the element should do something

### Link to Minimal Reproducible Example

https://github.com/lschierer/withastro-astro-lvzauv.git

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Can confirm with [this repro](https://stackblitz.com/edit/github-wjdcyd?file=astro.config.ts). I tried adding Lit to `vite.ssr.external` and `vite.ssr.noExternal` but no luck. Might have an outdated dependency on our end.

**Comment by JosefJezek** [comment]
@lschierer pls reply

**Comment by lschierer** [comment]
I'm unsure what the question is.  The last comment I see is that @natemoo-re stated that there may be an outdated dependency on the astro side.

**Comment by lschierer** [comment]
Let me know what further information I can provide and I'm happy to do so.

**Comment by florian-lefebvre** [comment]
In 5.0, we [removed the Lit integration](https://5-0-0-beta.docs.astro.build/en/guides/upgrade-to/v5/#removed-the-lit-integration) so we don't plan to address this issue. If you’re interested in maintaining a Lit integration yourself, you may wish to use the [last published version of `@astrojs/lit`](https://github.com/withastro/astro/tree/astro%404.13.0/packages/integrations/lit) as a starting point and upgrade the relevant packages.
