### ISSUE TITLE
The build command generates different variants of files

### ISSUE THREAD

**Issue by drtvader** [withastro/astro#8110]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac/Win/Linux

### What browser are you using?

Chrome

### Describe the Bug

The essence of the error is that after each change in the files (js/css) the build command rebuilds the template with a different set of files (js/css) And this is a problem for the CMS with which I work, every time I have to go change these files in the <head>
My settings:
`
export default defineConfig({
    build: {
        format: 'file'
    },
   vite: {
        build: {
            rollupOptions: {
                output: {
                  entryFileNames: '_astro/entry.js',
                  chunkFileNames: '_astro/chunks/chunk.[name].js',
                  assetFileNames: '_astro/assets/asset.[hash][extname]',
                },
            },
        },
    },
}); 
`
Example in index.html: 
```
<head>
  <link rel="stylesheet" href="/_astro/assets/asset.71de4177.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.7e560ba4.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.ee964aa1.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.f555b2fc.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.b4ef1718.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.43a1691e.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.e39329a1.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.eedad98e.css" />
  ** <link rel="stylesheet" href="/_astro/assets/asset.f6de2017.css" /> **
  <link rel="stylesheet" href="/_astro/assets/asset.648dd383.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.7f4b1616.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.2660b43f.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.c7af2618.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.6a484c97.css" />
  <link rel="stylesheet" href="/_astro/assets/asset.7379c019.css" />
</head>
```
After build it shows:
```
<head>
<link rel="stylesheet" href="/_astro/assets/asset.71de4177.css" />
<link rel="stylesheet" href="/_astro/assets/asset.7e560ba4.css" />
<link rel="stylesheet" href="/_astro/assets/asset.ee964aa1.css" />
<link rel="stylesheet" href="/_astro/assets/asset.f555b2fc.css" />
<link rel="stylesheet" href="/_astro/assets/asset.b4ef1718.css" />
<link rel="stylesheet" href="/_astro/assets/asset.43a1691e.css" />
<link rel="stylesheet" href="/_astro/assets/asset.e39329a1.css" />
<link rel="stylesheet" href="/_astro/assets/asset.eedad98e.css" />
** <link rel="stylesheet" href="/_astro/assets/asset.de4691c0.css" /> **
<link rel="stylesheet" href="/_astro/assets/asset.648dd383.css" />
<link rel="stylesheet" href="/_astro/assets/asset.7f4b1616.css" />
<link rel="stylesheet" href="/_astro/assets/asset.2660b43f.css" />
<link rel="stylesheet" href="/_astro/assets/asset.c7af2618.css" />
<link rel="stylesheet" href="/_astro/assets/asset.6a484c97.css" />
<link rel="stylesheet" href="/_astro/assets/asset.7379c019.css" />
</head>
```
** Files that are different

### What's the expected result?

It is necessary that after each build command the set of connected files does not change, but it would be even more interesting if each page had its own file, perhaps even one (js/css)

### Link to Minimal Reproducible Example

https://docs.astro.build/en/reference/configuration-reference/#build-options

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! We agree that the hashes of unchanged files need to be stable in our build output. However, a link to our own documentation is not a minimal reproducible example and we can't figure out what's happening here without one.
