### ISSUE TITLE
Inconsistent route priority with rest parameters and configured redirects

### ISSUE THREAD

**Issue by Hoolean** [withastro/astro#8129]
### What version of `astro` are you using?

2.10.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

*

### Describe the Bug

Hello!

When a project has both rest parameters and configured redirects, the route priority is inconsistent across paths of different depths.

More specifically, single-layer paths will prioritise configured redirects, whereas multi-layer paths will prioritise rest parameters.

> e.g. With pages:
> * `src/`
>   * `pages/`
>     * `[...path].astro`
>     * `redirected.astro`
>
> ...and configured redirects:
> * `/abc` → `/redirected`
> * `/abc/def` → `/redirected`
>
> ...then `/abc` will be serve `[...path].astro` and `/abc/def` will serve `redirected.astro`.

### What's the expected result?

The rest parameter would be prioritised in both cases or the configured redirect would be prioritised in both cases.

> e.g.
> Either:
> * Both `/abc` and `/abc/def` will serve `[...path.astro]`; or
> * Both `/abc` and `/abc/def` will serve `redirected.astro`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-inconsistent-route-priority

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
I'd like to attempt this.

@natemoo-re How's this a redirect issue? The pages at redirect generate a redirect to the slug mentioned with the destination URL. I think route priority in general needs to be fixed?

**Comment by rishi-raj-jain** [comment]
Okay, so I played with it a little bit. It only seems to occur in mode: 'server' and whenever there's a redirect. @ematipico Any good point of reference for me to start at to contribute to this?

**Comment by florian-lefebvre** [comment]
I believe this will be fixed by #9439

**Comment by ematipico** [comment]
Going to close, I'm pretty sure this is fixed
