### ISSUE TITLE
Can't build after @astrojs/react@2.3.0: Could not resolve "./vnode-children.js"

### ISSUE THREAD

**Issue by xriter** [withastro/astro#8135]
### What version of `astro` are you using?

2.10.10

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

When trying to `npm run build` the error `Could not resolve "./vnode-children.js" from "node_modules/@astrojs/react/server.js"` gets thrown.

<img width="1194" alt="Scherm­afbeelding 2023-08-18 om 16 53 19" src="https://github.com/withastro/astro/assets/70454441/3aaec6fd-5e47-4f59-a5cd-48a7790addd8">

When using:
```
// astro.config.mjs
import { defineConfig } from 'astro/config';
import node from '@astrojs/node';
import react from '@astrojs/react';

export default defineConfig({
  output: 'server',
  adapter: node({
    mode: 'standalone',
  }),
  integrations: [react()],
});
```
```
// package.json
...
"dependencies": {
    "@astrojs/node": "^5.3.4",
    "@astrojs/react": "^2.3.0",
    "astro": "^2.10.10"
  }
...
```

The problem seems to be in the upgrade from `@astrojs/react@2.2.2` to `@astrojs/react@2.3.0`.
When building with `astro@2.10.10` with `@astrojs/react@2.2.2`, it works.

### What's the expected result?

A successful build.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tncfye?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Still happens on 2.3.1

<img width="666" alt="image" src="https://github.com/withastro/astro/assets/69170106/21db3ffd-4920-49ab-bf0d-a4754fd7ef56">

**Comment by olibos** [comment]
Hello,
The file is still missing on 3.0.0-rc.4

https://github.com/withastro/astro/blob/%40astrojs/react%403.0.0-rc.4/packages/integrations/react/package.json#L22-L30
NPM: https://www.npmjs.com/package/@astrojs/react/v/3.0.0-rc.4?activeTab=code
