### ISSUE TITLE
Missing file on npm

### ISSUE THREAD

**Issue by Speaka** [withastro/astro#8146]
### What version of `astro` are you using?

2.10.11

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

win

### What browser are you using?

chrome

### Describe the Bug

The node_modules\@astrojs\react\server.js file is referring to the file "./vnode-children.js" which is missing when installed via npm.
Resulting in error Could not resolve "./vnode-children.js" from "node_modules/@astrojs/react/server.js"
file: C:/xxx/node_modules/@astrojs/react/server.js 
when  building.
npm code here: https://www.npmjs.com/package/@astrojs/react?activeTab=code

### What's the expected result?

npm mirror should include the neccesary files.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
This was fixed in #8317 and released as @astrojs/react v2.3.1.  You just have to update.

**Comment by Speaka** [comment]
It might be but it's not correctly mirrored to npm. Version 2.3.1, no such file but referring to it in server.js. Consequently not installed with npm i.
![image](https://github.com/withastro/astro/assets/48431623/b9ef8f50-10a4-43c1-af31-8e483b4aa4ea)

**Comment by lilnasy** [comment]
You're right! Thanks for bringing this up. I'm re-opening the original issue #8135.
