### ISSUE TITLE
Astro Image component @astrojs/image does not work on Netlify using SSR

### ISSUE THREAD

**Issue by gregorysirtoli** [withastro/astro#8157]
### What version of `astro` are you using?

2.10.12

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome 

### Describe the Bug

The image component does not render images correctly in Production on Netlify using the @astrojs/netlify adapter. Everything works fine in dev mode but once deployed to Netlify the image endpoint fails to generate and return images, instead it throws the following error:

`The image "URL" cannot be displayed because it contains errors.`

Same error https://github.com/withastro/astro/issues/4794 

### What's the expected result?

It simply should render the images useing @astro/image 

### Link to Minimal Reproducible Example

https://github.com/lgastler/astro-image-ssr-reproduction

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ajinvarghesechandy1** [comment]
maybe

**Comment by natemoo-re** [comment]
I can confirm that I'm getting 500 / 502 errors with the original `@astrojs/image` repro.

[Here's a working repro](https://main--darling-bombolone-a9d1af.netlify.app/) using [`astro:assets`](https://docs.astro.build/en/guides/assets/) which has replaced the deprecated `@astrojs/image`. I unfortunately don't think that we'll be able to backport any fixes to `@astrojs/image` given that the recommended solution (`astro:assets`) is working as expected and [`@astrojs/image` is about to be officially sunset](https://github.com/withastro/astro/pull/7922) once https://github.com/withastro/astro/pull/8188 is merged.
