### ISSUE TITLE
Broken Portfolio Template

### ISSUE THREAD

**Issue by krishna-santosh** [withastro/astro#8161]
### What version of `astro` are you using?

2.10.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

![image](https://github.com/withastro/astro/assets/75202541/8682ef81-1bd8-40c2-8e04-b3956687ef25)

Due to the recent merge #7078. 
I've also mentioned it before the merge in the Issue and PR's comment section https://github.com/withastro/astro/issues/7056#issuecomment-1640405566

### What's the expected result?

Website(Template) to look normal.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/portfolio?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kasutu** [comment]
After removing the loop Where the social links are located the issue has been reduced.
![image](https://github.com/withastro/astro/assets/64959978/386b27fe-442c-4576-8acf-13d5713d3006)

![image](https://github.com/withastro/astro/assets/64959978/a9015446-62dc-4dd6-855f-e88cc7ca4355)


I am running in `dev` mode and browsing in `edge`
