### ISSUE TITLE
UI Bug: Code Snippet Displayed Instead of Rendered Element in <noscript>

### ISSUE THREAD

**Issue by OshriAsulin** [withastro/astro#8162]
### What version of `astro` are you using?

2.10.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

When using the <noscript> element with the display: contents; style to conditionally render content when JavaScript is disabled, the rendered UI displays a code snippet instead of the expected content.

This bug is present in the 'portfolio' template in the 'Nav.astro' component located at- https://github.com/withastro/astro/blob/latest/examples/portfolio/src/components/Nav.astro

![צילום מסך 2023-08-20 112622](https://github.com/withastro/astro/assets/114335827/3eaab156-53a2-46ba-a647-64a5e9865bb5)
![צילום מסך 2023-08-20 112633](https://github.com/withastro/astro/assets/114335827/abf83724-d04c-43ec-8293-521211cbcbce)

### What's the expected result?

The <noscript> element should render its content as specified in the HTML when JavaScript is disabled.

Actual Behavior:
Instead of rendering the content inside the <noscript> element, the UI displays a code snippet with various <div> and <a> elements containing SVG icons and links.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/portfolio?file=README.md&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Thanks for creating this issue! It seems to be the same one as #8161, closing as duplicate.
