### ISSUE TITLE
SolidJS component inside p tags is not executing js

### ISSUE THREAD

**Issue by LJonn** [withastro/astro#8167]
### What version of `astro` are you using?

2.9.6

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

`<Layout>
    <Redirect client:load />
    <div class="mx-auto p-8">
        <p><Name client:load />Hello</p>
    </div>
</Layout>`

if p tag is changed to probably any other tag then the code inside Name is executing its javascript.

### What's the expected result?

JS in Name component should execute if it's surrounded by p tags

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-c1hcrv?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by 3210jr** [comment]
Same issue here with Svelte and Preact components. No need for the `p` tag. Just init a new project, add svelte or preact and not intractability from the components (even with hydration set to client:load).

Literally copy pasting from the examples folder but still not working. Let me know if you figure something out. There might be some docs we havent seen

**Comment by 3210jr** [comment]
@LJonn I removed my node modules and reinstalled everything from scratch and everything works really well now. That might help you out

**Comment by LJonn** [comment]
added a reproduction example in stackblitz: https://stackblitz.com/edit/astro-c1hcrv?file=src%2Fpages%2Findex.astro
