### ISSUE TITLE
🐛 BUG: Directory imports (`components/MyComponent/index.js`) do not throw

### ISSUE THREAD

**Issue by natemoo-re** [withastro/astro#817]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

[PR 813](https://github.com/snowpackjs/astro/pull/813) was opened to fix Astro's handling of directory index files.

> It turned out that Astro can't correctly work with components that are imported from directory's index file.
> For example, we have this structure:
>
> ```
> src/
> ├── components/
>        └── Header/
>                ├── Header.tsx
>                └── index.js
> ```
> // index.js
> export {Header} from './Header'

This actually shouldn't work, according to [the spec](https://nodejs.org/api/esm.html#esm_import_specifiers). But for some reason it does.

> If we import Header in .astro file it will be rendered just fine but if we want to make it interactive then we will > get an error 404
> /_astro/src/components/Header not found

### Steps to Reproduce

1. `npm init astro` using any template
2. create `src/components/MyComponent/index.jsx` file
3. `import MyComponent from "../components/MyComponent"` in `src/pages/index.astro` 
5. No Error! This works but it should throw a helpful error that you probably meant `import MyComponent from "../component/MyComponent/index.js"`

**Comment by jasikpark** [comment]
Should the error message be `... from "../component/MyComponent/index.jsx"` not `.js`?

**Comment by jasikpark** [comment]
https://github.com/almostxyz/astro/blob/9af0d85e9e9a4cfb3fc9c92822f67655e9f00628/packages/astro/src/compiler/codegen/index.ts#L167-L173

could be where this occurs - is it appending `.js` to bare imports? And then allowing that to work?

maybe it should just test for whether there's *any* extension - and error on extension-less imports..

**Comment by natemoo-re** [comment]
I'm going to close this since v0.21 & Vite handle this just fine!
