### ISSUE TITLE
Astro:assets remote image with vercel ImageService does not use astro domains and remotepatterns

### ISSUE THREAD

**Issue by pijusz** [withastro/astro#8173]
### What version of `astro` are you using?

2.10.12

### Are you using an SSR adapter? If so, which one?

Vercel Serverless Hybrid

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

When I deployed to production with vercel settings:
```javascript
  adapter: vercel({
    imageService: true,
    imagesConfig: {
      sizes: [80, 200, 320, 768, 1000, 1280, 1920],
      formats: ["image/avif", "image/webp"],
    },
  }),
```
Image on website does not load.
Created vercel deployment with example: https://terrestrial-transit.vercel.app/

### What's the expected result?

Images should be created/loaded on the website

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-4x6y6e

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pijusz** [comment]
[Github example](https://github.com/pijusz/terrestrial-transit)
Adding the repo, so anyone can fork and check themselves in prod enviroment.
#https://github.com/withastro/astro/pull/7778

**Comment by Princesseuh** [comment]
For Vercel, you need to set the `domains` and `remotePatterns` in the Vercel's adapter config, since the format is slightly different from ours domains and remotePatterns, following the format in Vercel's documentation: https://vercel.com/docs/build-output-api/v3/configuration#images
