### ISSUE TITLE
Duplicate scripts/styles. Unexpected console errors. Scripts executing in the wrong pages.

### ISSUE THREAD

**Issue by KhalilOuali** [withastro/astro#8183]
### What version of `astro` are you using?

2.10.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I recently encountered all of the issues in the title while working on my site and I finally figured it out.
**The issue** in my case was using the `@tailwind` directives in a `<style>` tag.
**The solution** was to remove the `@tailwind`s and use tailwind's plugin system instead (see first link).

Specifically I was using them to create reusable css classes. For some reason this caused every Astro component which had the `<style>` tag to load all of the `<script>`s from all other scripts, as well as load duplicate tailwind classes. I'm guessing it had to do with what is mentioned in both links.

Also for some reason the issue only shows up when running in development mode. When I tried build and preview, everything seemed fine.

* https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css
* https://docs.astro.build/en/guides/troubleshooting/#an-unexpected-script-or-style-is-included

I have attached a minimal reproduction. If you open the site in a new tab and check the console, you'll find logs from all three Astro pages, which obviously shouldn't happen.

### What's the expected result?

`@tailwind` directives in the `<style>` tags should not load assets from other pages.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fssprj?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
> The issue in my case was using the `@tailwind` directives in a `<style>` tag.

Since `<style>` blocks in Astro files are scoped by default, we generally recommend against using `@tailwind` directives in the `<style>` tag and instead keeping them in a base `.css` file that is imported in your page.

The `@astrojs/tailwind` plugin also injects a standard `base.css` automatically, so your usage of `@tailwind` directives was likely duplicating the CSS. See [`@astrojs/tailwind#applyBaseStyle`](https://docs.astro.build/en/guides/integrations-guide/tailwind/#applybasestyles) for more info.

**Comment by natemoo-re** [comment]
Appreciate you opening an issue with the solutions you found! Hopefully this helps anybody that runs into similar problems in the future.

Feel free to open a new issue if you hit anything else. There's also tons of folks willing to help out and answer any questions [on our official Discord](https://astro.build/chat).
