### ISSUE TITLE
SSR page has query params attached on all anchor tags

### ISSUE THREAD

**Issue by badalsaibo** [withastro/astro#8194]
### What version of `astro` are you using?

2.6.0

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Suppose I'm on the root page, `localhost:3000`
I have a Navbar and a Footer component layout too wrapping this page. They all contain anchor tags in it.

Snippet of an anchor tag present in `Footer.astro`

```html
 <li>
   <a
      onclick="handleClickEvent('Virtual Homework'); "
      class="link-item"
      href="/virtual-study-club">
   Virtual Homework Club
   </a>
</li>
```

When I'm on `localhost:3000` All anchor tags works fine.

Rendered html output at `localhost:3000`

```html
<li class="astro-AK3UPACL">
   <a onclick="handleClickEvent('Virtual Homework'); " class="link-item astro-AK3UPACL" href="http://localhost:3000/virtual-study-club">
   Virtual Homework Club
   </a>
</li>
```

When I add a query param say `localhost:3000?page=2` and refresh the page. It works fine.
But the rendered html when inspecting gets this query params attached too`

Rendered html output at `localhost:3000?page=2`

```html
<li class="astro-AK3UPACL">
   <a onclick="handleClickEvent('Virtual Homework'); " class="link-item astro-AK3UPACL" href="http://localhost:3000/virtual-study-club?page=2">
   Virtual Homework Club
   </a>
</li>
```

As we saw on the original `Footer.astro` file, there isn't any query params attached. So I do not know why it behaves in this way.

I would not like the anchor tags to get the query params appended on them. Is there any way to overcome it. It affects other pages where this query params is needed for working.

`astro.config.mjs`

```js
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import vue from '@astrojs/vue';
import sitemap from '@astrojs/sitemap';

import netlify from '@astrojs/netlify/edge-functions';

export default defineConfig({
  experimental: {
    redirects: true,
  },
  output: 'server',
  site: 'https://xyz.com,
  integrations: [
    tailwind({
      applyBaseStyles: false,
      configFile: './tailwind.config.cjs',
    }),
    vue(),
    sitemap({
      serialize(item) {
        if (item.url.endsWith('/')) {
          item.url = item.url.substring(0, item.url.length - 1);
        }
        return item;
      },
    }),
  ],
  vite: {
    ssr: {
      noExternal: ['floating-vue', 'vueperslides'],
    },
  },
  adapter: netlify(),
});
```

### What's the expected result?

I expect the html anchor tags to be not affected by whatever query params I have on the url.

### Link to Minimal Reproducible Example

I tried creating a workable demo but it's not happening. Meanwhile can anyone figure it out why it's happening.

https://stackblitz.com/edit/github-pwkyz4?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm guessing that you're rendering the `href` attribute using `Astro.url` which will include `searchParams` when rendering on the server. Astro doesn't ever automatically rewrite the `<a href>` markup that is generated.

You can use `Astro.url.pathname` to just get the path of the current URL. Check the [MDN `URL` Docs](https://developer.mozilla.org/en-US/docs/Web/API/URL) for more information.

Feel free to reopen if you can add a reproduction!

**Comment by badalsaibo** [comment]
@natemoo-re Footer.astro contains hard-coded links as I shown above.

```html
<li>
   <a
      onclick="handleClickEvent('Virtual Homework'); "
      class="link-item"
      href="/virtual-study-club">
   Virtual Homework Club
   </a>
</li>
```

Even I'm confused how is the original href tags being overwritten.

**Comment by natemoo-re** [comment]
Hmm, hard to debug further without a reproduction. This definitely isn't happening in the one linked. Can you share a link to your full repo? Maybe there's something else going on.

**Comment by badalsaibo** [comment]
@natemoo-re There was a script tag hidden somewhere that was targetting all a tags and overwriting the href. 🥲

My bad. Closing the issue.
