### ISSUE TITLE
Netlify edge function adapter generated route interfering with SSG in hybrid mode (SSG/edge-SSR)

### ISSUE THREAD

**Issue by mb21** [withastro/astro#8211]
### What version of `astro` are you using?

2.10.13

### Are you using an SSR adapter? If so, which one?

@astrojs/netlify/edge-functions

### What package manager are you using?

npm

### What operating system are you using?

Mac (but build is in the cloud)

### What browser are you using?

Firefox

### Describe the Bug

With the following astro config:

```js
import { defineConfig } from 'astro/config';
import netlify from "@astrojs/netlify/edge-functions";

export default defineConfig({
  output: "hybrid",
  adapter: netlify()
});
```

And a pages/index.astro file (which is to be statically generated) and a dynamic api route with `export const prerender = false` (from which an edge function should be generated), `npm run build` produces the following:

```
cat .netlify/edge-functions/manifest.json
{
  "functions": [
    {
      "function": "entry",
      "path": "/"
    },
    {
      "function": "entry",
      "path": "/api.json"
    }
  ],
  "version": 1
}
```

The `path: /` route interferes with the `dist/index.html` file so that on the deployed site on netlify, only `myproject.netlify.app/index.html`  works but `myproject.netlify.app` doesn't.

Note that the same project works when using the netlify serverless functions adapter instead of the edge one.

### What's the expected result?

Expected result:

```
cat .netlify/edge-functions/manifest.json
{
  "functions": [
    {
      "function": "entry",
      "path": "/api.json"
    }
  ],
  "version": 1
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9jnpdy?file=src%2Fpages%2Fapi.json.ts

Click on the terminal in StackBlitz and hit Ctrl-C. Then run `npm run build`, followed by `cat .netlify/edge-functions/manifest.json`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Edge functions is deprecated and we won't be fixing any more issues with it. If you'd like to continue using it, I suggest forking the code and creating a new adapter for yourself. Happy to help point you to where that is. Thanks!

**Comment by mb21** [comment]
Thanks for the reply!

> Edge functions is deprecated

Oh, this isn't indicated in https://docs.astro.build/en/guides/deploy/netlify/#adapter-for-ssredge (and not even on main here yet: https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/deploy/netlify.mdx#L19)...

Any github issue or other place I could read up on what the reasoning is and whether there are similar plans for other adapters... e.g. will there be a Vercel Edge adapter?

**Comment by ematipico** [comment]
@mb21 It's possible that the docs team still needs to catch up on this part of the documentation. 

We deprecated support for **all** edge environments (https://github.com/withastro/astro/pull/8015, https://github.com/withastro/astro/pull/8029) for all adapters, Vercel included. If you still need to compute information from an edge function, you can use the [Edge middleware](https://github.com/withastro/astro/blob/main/packages/integrations/netlify/README.md#run-middleware-in-edge-functions) feature. Instead, if you want to run all your functions on the edge, you'd need to follow Matthew's advice.

**Comment by mb21** [comment]
Okay, I also found [this roadmap item](https://github.com/withastro/roadmap/discussions/631), which says:

>  Core will keep the Node adapter, because it is the most widely used, and the Vercel adapter since they are the project's official host sponsor.

Is that no longer accurate? Or is the remaning Vercel adapter deploying to [Vercel Node.js "serverless"](https://vercel.com/docs/infrastructure/runtime-comparison)?

I understand maintenance resources for core are limited, but I also think a big appeal for Astro is it's opinionated best-practices... what would you do when building a new site that cannot be static? I was under the impression that edge would be cheaper/faster if you could live with its limitations?
Would be great to have some guidance by the project how to deploy when you need SSR. Maybe a list of community-maintained adapters along with how mature they are (similar to what the [solid community does with its primitives](https://primitives.solidjs.community/)...

**Comment by alexvuka1** [comment]
+1 I think this change introduces a significant limitation, so it would be great to have a workaround even if it is a community-maintained package.
