### ISSUE TITLE
Lit + SSR: unable to resolve a valid export

### ISSUE THREAD

**Issue by JosefJezek** [withastro/astro#8216]
### Astro info

```block
Astro version            v2.10.14
Package manager          npm
Platform                 linux
Architecture             x64
Adapter                  Couldn't determine.
Integrations             @astrojs/lit
```

### What browser are you using?

Chrome

### Describe the Bug

```
error   Unable to resolve a valid export for "md-outlined-button"! Please open an issue at https://astro.build/issues!
  File:
    /home/projects/github-uiraud/node_modules/astro/dist/runtime/server/hydration.js:83:11
  Code:
    82 |     children: "",
    > 83 |     props: {
         |           ^
      84 |       // This is for HMR, probably can avoid it in prod
      85 |       uid: astroId
      86 |     }
  Stacktrace:
Error: Unable to resolve a valid export for "md-outlined-button"! Please open an issue at https://astro.build/issues!
    at Module.generateHydrateScript (/home/projects/github-uiraud/node_modules/astro/dist/runtime/server/hydration.js:83:11)
    at renderFrameworkComponent (/home/projects/github-uiraud/node_modules/astro/dist/runtime/server/render/component.js:267:46)
    at async Module.renderComponent (/home/projects/github-uiraud/node_modules/astro/dist/runtime/server/render/component.js:351:10)
    at async Module.renderChild (/home/projects/github-uiraud/node_modules/astro/dist/runtime/server/render/any.js:14:11)
```

### What's the expected result?

MD components are working with Next.js SSR, see https://github.com/material-components/material-web/issues/4245#issuecomment-1601574226

Please improve support for Lit.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uiraud?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by marcmalerei** [comment]
I have the same issue. Using lit 2.8.0. 

`07:17:45 PM [build] Building static entrypoints...
Ambiguous external namespace resolution: "node_modules/lit/index.js" re-exports "LitElement" from one of the external modules "lit-element/lit-element.js" and "lit-html/is-server.js", guessing "lit-element/lit-element.js".
Ambiguous external namespace resolution: "node_modules/lit/index.js" re-exports "html" from one of the external modules "lit-element/lit-element.js" and "lit-html/is-server.js", guessing "lit-element/lit-element.js".
Ambiguous external namespace resolution: "node_modules/lit/index.js" re-exports "unsafeCSS" from one of the external modules "lit-element/lit-element.js" and "lit-html/is-server.js", guessing "lit-element/lit-element.js".
"LitElement", "html" and "unsafeCSS" are imported from external module "lit-html/is-server.js" but never used in "node_modules/lit/index.js".`

**Comment by bluwy** [comment]
Astro's island component detection works through [direct imports of the framework component](https://docs.astro.build/en/reference/directives-reference/#client-directives):

> A client directive can only be used on a UI framework component that is directly imported into a .astro component.

In this case, you're importing `import '@material/web/button/outlined-button';` and then using it `<md-outlined-button client:load>Hello World</md-outlined-button>`. Astro can't know those are related in order to server-side render and hydrate it.

You can fix it by writing it this way:

```astro
---
import { MdOutlinedButton } from '@material/web/button/outlined-button';
---

<MdOutlinedButton client:load>Hello World</MdOutlinedButton>
```
