### ISSUE TITLE
@astrojs/deno - "start" option is not typed as part of the adapter Options type.

### ISSUE THREAD

**Issue by jaymanmdev** [withastro/astro#8221]
### Astro info

```block
N/A
```

### What browser are you using?

N/A

### Describe the Bug

When using the adapter, I get a typescript error stating that the property does not exist on the Options type for the adapter.

![image](https://github.com/withastro/astro/assets/122149396/cd189fc7-0985-40dd-b604-eccd07ef529a)

However, when I look further at the type declarations, the Option type only has the port and hostname options defined. The start option still works perfectly so it hasn't been taken out of the adapter (thankfully!), but it must have been overlooked when adjusting the adapter's type declaration.

![image](https://github.com/withastro/astro/assets/122149396/2f02ccf8-7ef9-4e14-a40c-bf047409e298)

### What's the expected result?

N/A

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
@lilnasy can you assign me? I'd like to handle this over the week-end
