### ISSUE TITLE
Internal Redirect or rewrite url

### ISSUE THREAD

**Issue by debasispanigrahi** [withastro/astro#8236]
### Astro info

```block
Astro version            v2.10.12
Package manager          npm
Platform                 win32
Architecture             x64
Adapter                  Couldn't determine.
Integrations             @astrojs/mdx, @astrojs/sitemap, @astrojs/react, @astrojs/svelte, @astrojs/vue
```

### What browser are you using?

Chrome

### Describe the Bug

Like express after changing req.url  in middleware data comes from newly matched path. but after changing request and url in context , target url does not change. Need dynamic rewrite rule instead of redirect. 

### What's the expected result?

After modifying request or url  in context with different detail, target page executed must be change. similar to nextjs rewrite or reverse proxy but dynamic. can be configured at middleware.

### Link to Minimal Reproducible Example

No Example available

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@debasispanigrahi is this a feature request?

**Comment by debasispanigrahi** [comment]
@matthewp i think it is bug.

issue 1: Currently Astro middle ware does not allow to modify to URL parameter. Even if we force modify it by using spread operator or force assign using below code
    context.request=new Request(url,{param}) and context.url=new URL(url)
context inside middle ware changes. but target page does not change. We receive previous Astro request without alternation. ideally new page route must be called with modified Astro request. Alternatively new rewrite function can be made available inside context.

**Comment by lilnasy** [comment]
Closing as this ability is being discussed in https://github.com/withastro/roadmap/discussions/665.
