### ISSUE TITLE
`astro check` not working in astro.build repo

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#8246]
### Astro info

```block
Astro version            v3.0.0-rc.7
Package manager          pnpm
Platform                 darwin
Architecture             arm64
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind, @astrojs/solid-js, @astrojs/mdx, @astrojs/sitemap, @astrojs/prefetch
```

### What browser are you using?

Chrome

#### Issue 1 

1. In the https://github.com/withastro/astro.build repo
2. Run `pnpm astro check`
3. See the following output: 

<img width="1001" alt="Screen Shot 2023-08-27 at 9 59 26 AM" src="https://github.com/withastro/astro/assets/622227/284a2f47-3b66-4a66-a42c-3861589d6207">

#### Issue 2

1. Install @astrojs/check manually
2. Run `pnpm astro check`
3. See the same output as above, even though @astrojs/check is installed:

<img width="564" alt="Screen Shot 2023-08-27 at 10 03 54 AM" src="https://github.com/withastro/astro/assets/622227/7809f17e-c7d1-4bbb-a376-8f17470b54a8">

### What's the expected result?

I didn't have `@astrojs/check` installed, so I expected to see that first message. However, it re-asked me to install `typescript` in that second prompt and then failed. 

This may be a pnpm issue, and not a Astro 3.0 issue. I'll test this on Astro 2.0 now to confirm.

### Link to Minimal Reproducible Example

https://github.com/withastro/astro.build

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
Update: this seems to be an issue in Astro 2.x as well, I just reproduced this Astro 2.0. 

I also tried reproducing this in a smaller repo and could not reproduce, so it may be something specific to the astro.build codebase that is causing it.

<img width="644" alt="Screen Shot 2023-08-27 at 10 18 37 AM" src="https://github.com/withastro/astro/assets/622227/3323ea96-73fb-404d-bcee-b2d49c82c2f4">

**Comment by Princesseuh** [comment]
This is fixed already, but the fix isn't released yet https://github.com/withastro/astro/pull/8237

**Comment by Princesseuh** [comment]
https://github.com/withastro/astro/pull/8237 fixed this and checking out the astro.build repo myself, everything works. Please open another issue if you encounter anything new, but I think the errors in your screenshot might just be RC versions being weird or your setup
