### ISSUE TITLE
slot content disappears upon hydration when using polymorphic tags

### ISSUE THREAD

**Issue by mayank99** [withastro/astro#8247]
### Astro info

```block
v2.10.14
```

### What browser are you using?

Chrome, Firefox

### Describe the Bug

WHEN using polymorphic components (or even just assigning a tag name to a variable), AND
WHEN this polymorphic Astro component has a slot, AND
WHEN that slot is filled with a framework (Svelte) component which also has a slot, AND
WHEN the framework component has a client hydration directive:

The slot content doesn't appear.

If you refresh the page, you might be able to see the slot appear in prerendering and then disappear upon hydration.

### What's the expected result?

Slot content should stay in the DOM after hydration.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-stsn4j?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2FStuff.svelte,src%2Fcomponents%2FPoly.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Valid! Thanks for the nice reproduction and clear description.

**Comment by ematipico** [comment]
@natemoo-re do you have any hints on where the bug might be?
