### ISSUE TITLE
`fetch failed` on `npx astro add vue`

### ISSUE THREAD

**Issue by bahmanworld** [withastro/astro#8249]
### Astro info

```block
╭─~/Projects/astro1
╰─ npx astro add vue                                                                       

-> ✖ fetch failed
```

### What browser are you using?

Chrome

### Describe the Bug

I run into problem during install vuejs for my astro project many times: 

CLI : `npx astro add vue`

Screenshot:
<img width="788" alt="Screenshot 2023-08-27 at 9 23 21 PM" src="https://github.com/withastro/astro/assets/5371898/3541bf77-a2c1-4a89-af1f-62e59b43a345">

### What's the expected result?

Install `vue` through cli

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jacobthesheep** [comment]
This needs more information. Testing both on stackblitz and local machine, adding vue works. https://stackblitz.com/edit/withastro-astro-yuhcwn?file=package.json
