### ISSUE TITLE
Jitter while scrolling a website built with Astro SPA 2.10 on iPad with iOS 16.6

### ISSUE THREAD

**Issue by mrdc** [withastro/astro#8250]
### Astro info

```block
Astro SPA 2.10
```

### What browser are you using?

Safari (iPadOS 16.6)

### Describe the Bug

Jitter while scrolling a website built with Astro SPA 2.10 on iPad with iOS 16.6.

### What's the expected result?

Scrolling should be smooth without any jitter.

### Link to Minimal Reproducible Example

https://astro-records.pages.dev/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please provide a minimal reproduction if you can. This was likely build before we added throttling to the scroll listener. Please open a new issue if you can provide a reproduction.
