### ISSUE TITLE
React with create:only gives strange error on client-side

### ISSUE THREAD

**Issue by zubialevich** [withastro/astro#8259]
### Astro info

```block
Astro version            v2.10.12
Package manager          npm
Platform                 win32
Architecture             x64
Adapter                  Couldn't determine.
Integrations             @astrojs/react
```

### What browser are you using?

Vivaldi

### Describe the Bug

Hi,

I am having a strange error on client-side when I am trying to enable `client:only="react"`

```
Uncaught (in promise) SyntaxError: The requested module '/node_modules/vscode-textmate/release/main.js?v=f42e9d87' does not provide an export named 'INITIAL' (at index.esm.js?v=f42e9d87:2:10)
```

I've tried to use empty react component but still the same error. Without `client:only="react"` component works

### What's the expected result?

No error on client and rendered frontend

### Link to Minimal Reproducible Example

don't have

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by zubialevich** [comment]
Seems I've found the reason. Problem was astro component `<Debug />`. Once I've removed it, the client-side error disappeared.

**Comment by matthewp** [comment]
Thanks, closing in that case.
