### ISSUE TITLE
please change the deafult PORT to :3000

### ISSUE THREAD

**Issue by bis0072** [withastro/astro#8284]
### Astro info

```block
Astro version            v3.0.0
Package manager          pnpm
Platform                 win32
Architecture             x64
Adapter                  @astrojs/netlify
Integrations             @astrojs/tailwind, @astrojs/sitemap, @astrojs/react
```

### What browser are you using?

Chorme

### Describe the Bug

Please change the default port to 3000 instead of 4321

### What's the expected result?

http://localhost:3000

### Link to Minimal Reproducible Example

na

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
why

**Comment by mdawar** [comment]
You can change the port using `--port` flag:

```sh
npx astro dev --port 3000
```

Or edit your `package.json` and add `--port 3000` to the `dev` and `start` scripts:

```json
{
  "scripts": {
    "dev": "astro dev --port 3000",
    "start": "astro dev --port 3000",
  }
}
```

**Comment by natemoo-re** [comment]
For background on this change, please see [the original roadmap discussion](https://github.com/withastro/roadmap/discussions/451) where this was suggested.

Picking a default port is hard, but 3000 is so common across projects that it caused some obscure, hard to debug problems. Having a unique port that is only used by Astro projects is helpful for new users and, honestly, just more fun.

As mentioned above, this behavior is entirely configurable if it doesn't suit your preferences.
