### ISSUE TITLE
Missing type declarations in Astro v3.0.0

### ISSUE THREAD

**Issue by mdawar** [withastro/astro#8291]
### Astro info

```block
Astro version            v3.0.0
Package manager          npm
Platform                 linux
Architecture             x64
Adapter                  Couldn't determine.
Integrations             None or couldn't determine.
```

### What browser are you using?

Chrome

### Describe the Bug

Running `npx tsc --noEmit` causes these TS errors:

```
node_modules/astro/components/index.ts:1:33 - error TS2307: Cannot find module './Code.astro' or its corresponding type declarations.

1 export { default as Code } from './Code.astro';
                                  ~~~~~~~~~~~~~~

node_modules/astro/components/index.ts:2:34 - error TS2307: Cannot find module './Debug.astro' or its corresponding type declarations.

2 export { default as Debug } from './Debug.astro';
                                   ~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/astro/components/index.ts:1
```

To reproduce the issue, create a new Astro project with TypeScript:
1. npm create astro@latest
2. Run `npx tsc --noEmit`

### What's the expected result?

No TS errors expected.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lecov5?file=package.json&startScript=check

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdawar** [comment]
The use of `tsc --noEmit` is suggested in the [docs](https://docs.astro.build/en/guides/typescript/#type-checking).

I filed it as bug, because I was updating a project using `v2.10.14` without any issues and I encountered this error after the update.

What do you suggest?

**Comment by Princesseuh** [comment]
Unfortunately, right now. I don't know. I'll see if we can just add some `@ts-expect-error` comments maybe just for `tsc` 🤔
