### ISSUE TITLE
SyntaxError: Named export 'compile' not found.

### ISSUE THREAD

**Issue by IamRaynah** [withastro/astro#8297]
### Astro info

```block
Astro version            v2.8.3
Package manager          yarn
Platform                 win32
Architecture             x64
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### What browser are you using?

Edge

### Describe the Bug

I'm getting the below error after building my astro project.

file:///C:/Users/User-Dir/Learning/astro/one/dist/server/chunks/astro.31debec6.mjs:1
import { compile } from 'path-to-regexp';
         ^^^^^^^
SyntaxError: Named export 'compile' not found. The requested module 'path-to-regexp' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'path-to-regexp';
const { compile } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

![image](https://github.com/withastro/astro/assets/17871148/199c68ed-83c2-4a0d-aee3-318da1c013d6)

### What's the expected result?

I expected the app to run and display in the browser

### Link to Minimal Reproducible Example

Private Repository

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by OsamaHaikal** [comment]
Hello, I faced the same issue with deno and node adapters with astro 3.0.3 and vue client v3

![image](https://github.com/withastro/astro/assets/72370395/7f7f59a3-46a7-4dcf-a3a9-eea9e7534711)

![image](https://github.com/withastro/astro/assets/72370395/1d5c4559-3814-40b6-8ae2-e13414bcebc5)

**Comment by OsamaHaikal** [comment]
Hello, this issue is vite issue and not related to astro,

you can fix the issue by adding
  vite: {
    ssr: {
      noExternal: ['path-to-regexp'],
    },
  },
  
  **Reference:** https://docs.astro.build/en/guides/integrations-guide/node/#syntaxerror-named-export-compile-not-found

**Comment by ImBIOS** [comment]
In Starlight I'm using this to solve this problem:

```astro.config.mjs
  vite: {
    ssr: {
      noExternal: ['execa', 'is-stream', 'npm-run-path'],
    },
  },
```

**Comment by ZeldOcarina** [comment]
The workaround works but I think a long-term solution should be though of? No?

**Comment by MagsMagnoli** [comment]
Just created a blank astro project with netlify adapter and saw this error
