### ISSUE TITLE
ViewTransitions fallback doesn't work in Safari 16.6

### ISSUE THREAD

**Issue by noClaps** [withastro/astro#8301]
### Astro info

```block
Astro version            v3.0.1
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  Couldn't determine.
Integrations             @astrojs/mdx, @astrojs/sitemap
```

### What browser are you using?

Safari, Firefox

### Describe the Bug

The ViewTransitions fallback doesn't work on Safari and Firefox.

### What's the expected result?

Although the ViewTransitions API isn't supported on Safari and Firefox, the fallback script should work, but it doesn't. There's no animation during page navigations.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-azssaz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks @noClaps, looking at the example, there is no use of `transition:animate`. We currently do not support the browser builtin default animations in the fallback. Mimicking those is difficult. We might support them in the future.

For now though, any animations you add via the `transition:animate` API should occur within the fallback as well.

**Comment by noClaps** [comment]
I think this should be mentioned in the docs somewhere, because right now it seems like simply adding the `<ViewTransitions />` component will enable page transitions, including the fallback.
