### ISSUE TITLE
Astro 3 throwing "invalid SVG" error when importing a SVG Sprite

### ISSUE THREAD

**Issue by moritzlaube** [withastro/astro#8305]
### Astro info

```block
Astro version            v3.0.2
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  Couldn't determine.
Integrations             @astrojs/sitemap, @astrojs/svelte, legacy
```

### What browser are you using?

Chrome

### Describe the Bug

Just upgraded from 2.10.1 to 3.0.2 and followed the migration guide. "npm run dev" as well as "npm run build" are failing because a problem with an SVG that I am importing in several components. The error when running `npm run dev` is: 

`[vite] Error when evaluating SSR module /src/components/CartIcon.svelte: failed to import "/src/assets/images/icons.svg"
|- TypeError: Invalid SVG`

When building the project, the error is coming from `[astro:assets:esm]` if that matters. 

The SVG in question is a SVG Sprite (`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">`) with symbols in it. In the components, I am importing the svg sprite as `Sprite` and use it in the template like so: `<svg><use xlink:href={Sprite + '#cart'} /></svg>` (this is importing the cart icon).

It's been working through all versions of Astro but stopped in version 3. 

### What's the expected result?

It should load the Sprite without Error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3zr73u?file=src%2Fassets%2Flogo.svg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Does using `?raw` work here? Or maybe you want `?url`?

**Comment by moritzlaube** [comment]
You nailed it. Appending `?url` did the trick. Thanks a lot!
