### ISSUE TITLE
Conflicting peer dependency: astro@3.0.3 from @astrojs/tailwind@5.0.0

### ISSUE THREAD

**Issue by elisapetcare** [withastro/astro#8307]
### Astro info

```block
Conflicting peer dependency: astro@3.0.3
npm ERR! node_modules/astro
npm ERR!   peer astro@"^3.0.0" from @astrojs/tailwind@5.0.0
npm ERR!   node_modules/@astrojs/tailwind
npm ERR!     @astrojs/tailwind@"*" from the root project
```

### What browser are you using?

in terminal

### Describe the Bug

Update pakages remove npm_packages folder and npm install

### What's the expected result?

install all packages

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@elisapetcare The reproduction doesn't show the warning you mentioned. Could you please provide a repository?

**Comment by maddsua** [comment]
@elisapetcare @ematipico here you go:

https://stackblitz.com/edit/github-rjadxb?file=package.json

If stackblitz does not work for some reason (it died on me, maybe my package is too big), here's a zip with both package and package-lock:

[astro-v2-upgrade-issue.zip](https://github.com/withastro/astro/files/12499017/astro-v2-upgrade-issue.zip)

What's in example:

package-lock contains deps versions for Astro 2.x
package contains versions for Astro 3

The result - failure to update deps

Just run `npm i` to see it in action. Deleting package-lock fixes the issue (but adds another one, but it's related to Rollup and I'll create a separate issue for it)

Here's also a screenshot of the error:

![image](https://github.com/withastro/astro/assets/102395937/3af1e3b7-96d6-43ff-8fe2-fea068fedc02)

Let me know if npm log files will be of any use

**Comment by dobbbri** [comment]
fixed

**Comment by dobbbri** [comment]
fixed

**Comment by elisapetcare** [comment]
upgrade packages and works.
