### ISSUE TITLE
Missing styles for element when class is passed as prop

### ISSUE THREAD

**Issue by nomorejalapenos** [withastro/astro#8309]
### Astro info

```block
Astro version            v3.0.3
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  Couldn't determine.
Integrations             None or couldn't determine.
```

### What browser are you using?

Chrome, Safari

### Describe the Bug

When I use a component as a wrapper for another component and pass a class to it as a prop, the styles that I wrote for this class are missing.

### What's the expected result?

Styles should not be lost.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-qwmbat?file=src%2Fcomponents%2FIntro.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by newtoallofthis123** [comment]
As of Astro 3.0,class list feature has been fully removed and can no longer be used 
[As per migration guide](https://docs.astro.build/en/guides/upgrade-to/v3/#removed-passing-classlist-as-a-prop).

## Remove Class list as prop

You are trying to pass in the class list as a prop.
This feature too has been [deprecated](https://docs.astro.build/en/guides/upgrade-to/v3/#removed-passing-classlist-as-a-prop) as well

Hence, something like this will fix your problem

```
---
;
const { class: className } = Astro.props;
---
<div
  class:list={[className]}
/>
```

Ps. If you are looking to pass in classes as props, i recommend using CSS variables instead

**Comment by nomorejalapenos** [comment]
> As of Astro 3.0,class list as a prop feature has been fully removed and can no longer be used [As per migration guide](https://docs.astro.build/en/guides/upgrade-to/v3/#removed-passing-classlist-as-a-prop).
> 
> ## Remove Class list as prop
> You are trying to pass in the class list as a prop. This feature too has been [deprecated](https://docs.astro.build/en/guides/upgrade-to/v3/#removed-passing-classlist-as-a-prop) as well
> 
> Hence, something like this will fix your problem
> 
> ```astro
> ---
> const { class: className } = Astro.props;
> ---
> <div
>   class:list={[className]}
> />
> ```
> 
> Ps. If you are looking to pass in classes as props, i recommend using CSS variables instead

In my example, I literally did what is written in the migration

**Comment by nomorejalapenos** [comment]
Сlasses are passed to the component, but the styles for these classes are lost somewhere. It doesn't make any sense and completely breaks all my sites.

**Comment by newtoallofthis123** [comment]
It seems that you are doing it correctly...sorry for not noticing 😅

**Comment by jochemkeller** [comment]
Hi, I ran into this same issue and found out that the required data-attribute for binding the styles is added to `Astro.props`. However this is not automatically added to the child component, we would have to bind it ourselves:

```astro
---
export interface Props {
  class?:string
}

const { class: className } = Astro.props

const attributes = Object.fromEntries(
  Object.entries(Astro.props)
  .filter(([key]) => key.startsWith('data-astro'))
  .map(([key]) => [key, true])
);
---

<div class:list={["section", className]} {...attributes}><slot/></div>
```

Working fork of your example → 🔗 https://stackblitz.com/edit/withastro-astro-lf8ted?file=src%2Fcomponents%2FSection.astro

Hope this helps 👍

**Comment by ragivi** [comment]
Hi! I have the same issue and with the solution provided by @jochemkeller it works, but it's a bit annoying to have to add this into every component with custom class name.

Another solution is change the **scopedStyleStrategy** to **'where'** but I would like to use the new default strategy **''attribute''**.

**Comment by nomorejalapenos** [comment]
> Hi, I ran into this same issue and found out that the required data-attribute for binding the styles is added to `Astro.props`. However this is not automatically added to the child component, we would have to bind it ourselves:
> 
> ```astro
> ---
> export interface Props {
>   class?:string
> }
> 
> const { class: className } = Astro.props
> 
> // filter the data-astro-cid-xxxxxxxx entries, and re-map so we can bind it as a spread object
> const attributes = Object.fromEntries(
>   Object.entries(Astro.props)
>   .filter(([key]) => key.startsWith('data-astro’))
>   .map(([key]) => [key, true])
> );
> ---
> 
> <div class:list={["section", className]} {...attributes}><slot/></div>
> ```
> 
> Working fork of your example → 🔗 https://stackblitz.com/edit/withastro-astro-lf8ted?file=src%2Fcomponents%2FSection.astro
> 
> Hope this helps 👍

It works but i don't think new users will do it. Same thing with **scopedStyleStrategy**. I think passing a class is such a common way and the fact that it does not work without additional settings looks at least strange

**Comment by natemoo-re** [comment]
Since the default `scopedStyleStrategy` was changed to `attribute` in 3.0, this behavior works slightly differently now.

This is how you would pierce the component scope from a parent with the new `attribute` behavior. No need to filter out the scope yourself, you can just pass any unhandled props down to the root element as attributes.

```astro
---
export interface Props {
  class?: string;
}

const { class: className, ...attributes } = Astro.props
---

<div class:list={["section", className]} {...attributes}><slot/></div>
```

Of course, you can also set `scopedStyleStrategy: 'where'` to keep the old behavior. It's not being removed, it's just no longer the default.

For context, while this _is_ a common use case, the drawback was that users had to manually filter the `class` prop in order to remove the parent's scoped class. This was actually one of the main motivations for changing this behavior. Users were unintentionally passing styles down to child components. Now, in order to allow styles to pierce from the parent scope into a child component, you must explicit allow it by passing the parent's scope attribute down.
