### ISSUE TITLE
Unable to import morph transition.

### ISSUE THREAD

**Issue by IndexZeroZzz** [withastro/astro#8316]
### Astro info

```block
Astro version            v3.0.3
Package manager          npm
Platform                 win32
Architecture             x64
Adapter                  Couldn't determine.
Integrations             @astrojs/tailwind
```

### What browser are you using?

Chrome

### Describe the Bug

It's impossible to import morph from astro:transitions. You can import fade, slide, but cannot import morph.

![изображение](https://github.com/withastro/astro/assets/83467432/bbd452fb-7ba6-4d26-9785-537fbbdd4a77)
![изображение](https://github.com/withastro/astro/assets/83467432/823a971d-0115-48c2-b5f2-024fc21dde95)

### What's the expected result?

You can import morph and change its duration

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/helloworld12?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This was renamed to `initial`, see here: https://docs.astro.build/en/guides/view-transitions/#update-transitionanimate-directives

**Comment by idoob** [comment]
@IndexZeroZzz are you trying to import `initial` animation to customize it ?

**Comment by IndexZeroZzz** [comment]
@idoob yes
