### ISSUE TITLE
Vercel serverless adapter logs too much

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#8321]
### Astro info

```block
Astro version            v3.0.3
Package manager          pnpm
Platform                 linux
Architecture             x64
Adapter                  @astrojs/vercel/serverless
Integrations             None or couldn't determine.
```

### What browser are you using?

N/A

### Describe the Bug

For the `functionPerRoute` setting, message about node.js compatibility is logged once per route.

![image](https://github.com/withastro/astro/assets/69170106/b53e8b95-d48d-4ee8-929a-8192c7eae1a5)

### What's the expected result?

The compatibility message should run once per build.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gmnscw?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Notes if you want to take this up:
- [`getRuntime()`](https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/serverless/adapter.ts#L229) is the function doing the logging
- It is called by [`createFunctionFolder()`](https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/serverless/adapter.ts#L101) which may run several times.
- Since 3.0, every integration hook has access to a `logger`, replacing console with it will make inserting `PACKAGE_NAME` in every message unnecessary.

**Comment by rafael-almeida** [comment]
Hey @lilnasy,
 
I would like to give this a shot as a first contribution to the project.

**Comment by lilnasy** [comment]
Hi, @rafael-almeida, thanks for the help!

I'll note that the vercel adapter was updated today, but I haven't checked if the issue was fixed. I think the compatibility data may still be outdated.

Please confirm and if the issue is still there, I encourage you to open a PR that mentions this issue. 🙏

**Comment by rafael-almeida** [comment]
Hi @lilnasy,

Thanks for the update. 

I am having trouble reproducing the issue using the stackblitz link you provided. Could you provide more detailed steps or context to help replicate it?

As this is my first open source contribution, I might need some extra guidance. I hope that is not too much trouble 🙏

<details>
  <summary>Here are the logs I got</summary>

```
~/projects/github-gmnscw
❯ pnpm install && pnpm run dev
Lockfile is up to date, resolution step is skipped
Packages: +444
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 444, reused 0, downloaded 444, added 444, done

dependencies:
+ @astrojs/vercel 4.0.0
+ astro 3.0.3

Done in 2.3s

> @example/basics@0.0.1 dev /home/projects/github-gmnscw
> astro dev

  🚀  astro  v3.0.3 started in 51ms
  
  ┃ Local    http://localhost:4321/
  ┃ Network  use --host to expose
``` 
</detail>

**Comment by lilnasy** [comment]
Of course, I'm happy to help.

So stackblitz runs the dev command `npm run dev` automatically. The vercel integration would only run with the build command `npm run build`.

**Comment by rafael-almeida** [comment]
Thank you for the clarification. I've updated `astro` to `3.0.10` and `@astrojs/vercel` to `4.0.4`, and the issue seems to persist. I'll work on a PR this weekend.

<details>
<summary>Logs</summary>

```
~/projects/github-gmnscw-8pc87w
❯ pnpm install && pnpm run dev
Lockfile is up to date, resolution step is skipped
Packages: +444
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 444, reused 0, downloaded 444, added 444, done
 
dependencies:
+ @astrojs/vercel 4.0.4
+ astro 3.0.10

Done in 2.9s

> @example/basics@0.0.1 dev /home/projects/github-gmnscw-8pc87w
> astro dev

08:13:28 PM [@astrojs/vercel/serverless] Vercel's hosting plans might have limits to the number of functions you can create.
Make sure to check your plan carefully to avoid incurring additional costs.
You can set functionPerRoute: false to prevent surpassing the limit.
  🚀  astro  v3.0.10 started in 52ms
  
  ┃ Local    http://localhost:4321/
  ┃ Network  use --host to expose
  
^C

~/projects/github-gmnscw-8pc87w 6s
❯ pnpm run build

> @example/basics@0.0.1 build /home/projects/github-gmnscw-8pc87w
> astro build

08:13:43 PM [@astrojs/vercel/serverless] Vercel's hosting plans might have limits to the number of functions you can create.
Make sure to check your plan carefully to avoid incurring additional costs.
You can set functionPerRoute: false to prevent surpassing the limit.
08:13:43 PM [content] No content directory found. Skipping type generation.
08:13:43 PM [build] output target: hybrid
08:13:43 PM [build] deploy adapter: @astrojs/vercel/serverless
08:13:43 PM [build] Collecting build info...
08:13:43 PM [build] Completed in 39ms.
08:13:43 PM [build] Building hybrid entrypoints...
08:13:44 PM [build] Completed in 1.64s.

 prerendering static routes 
▶ src/pages/index.astro
  └─ /index.html (+95ms)
Completed in 313ms.


 finalizing server assets 

08:13:45 PM [build] Rearranging server assets...
08:13:45 PM [@astrojs/vercel/serverless] Bundling function ../../../../dist/pages/entry._image.astro.mjs
[@astrojs/vercel/serverless] Your project is being built for Node.js 16 as the runtime.
[@astrojs/vercel/serverless] This version is deprecated by Vercel Serverless Functions, and scheduled to be disabled on February 6, 2024.
[@astrojs/vercel/serverless] Consider upgrading your local version to 18.
08:13:45 PM [@astrojs/vercel/serverless] Bundling function ../../../../dist/pages/entry.index.astro.mjs
[@astrojs/vercel/serverless] Your project is being built for Node.js 16 as the runtime.
[@astrojs/vercel/serverless] This version is deprecated by Vercel Serverless Functions, and scheduled to be disabled on February 6, 2024.
[@astrojs/vercel/serverless] Consider upgrading your local version to 18.
08:13:45 PM [build] Server built in 2.59s
08:13:45 PM [build] Complete!

~/projects/github-gmnscw-8pc87w 4s
❯ 
```

</details>
