### ISSUE TITLE
Vercel image service breaks svg when used with `astro:assets`

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#8322]
### Astro info

```block
Astro version            v3.0.3
Package manager          npm
Platform                 linux
Architecture             x64
Adapter                  @astrojs/vercel
Integrations             None or couldn't determine.
```

### What browser are you using?

Brave

### Describe the Bug

When using the Vercel static adapter and enabling the imageService locally, svg assets passed to the `Image` component are broken. Their link points to an error 500 with message `Server Error: Buffer has an unsupported format`.

### What's the expected result?

Be able to pass svgs to the Image component

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-aprtsf

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Can confirm that SVGs break when using

```js
vercel({ imageService: true })
```

I'm not too sure what the fix here will be. We might need a way for image services to configure which formats they support. cc @Princesseuh

**Comment by Princesseuh** [comment]
> Can confirm that SVGs break when using
> 
> ```js
> vercel({ imageService: true })
> ```
> 
> I'm not too sure what the fix here will be. We might need a way for image services to configure which formats they support. cc @Princesseuh 

Is this in dev or production? In dev we don't use Vercel's service, we use Squoosh. I believe the error message comes from Squoosh too.

**Comment by florian-lefebvre** [comment]
Broken in dev, haven't tried on vercel but I will do so

**Comment by florian-lefebvre** [comment]
Can confirm it works on vercel so it must come from squoosh
