### ISSUE TITLE
Astro 3 breaks Prettier

### ISSUE THREAD

**Issue by xriter** [withastro/astro#8325]
### Astro info
```
Astro version            v3.0.3
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  Couldn't determine.
Integrations             None or couldn't determine.
```

### Describe the Bug

I am not sure what is causing this, but after upgrading to Astro 3.0, Prettier doesn't seem to be working anymore in VS Code.

The error logs show:
```
["WARN" - 15:35:55] Parser not inferred, trying VS Code language.
["ERROR" - 15:35:55] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

I am using VS Code with the latest Astro extension (`v2.3.1`).
Next to this, the official Prettier extension (`v10.1.0`) is installed.

When running the VS Code command **Format document with... > Astro** it does work though. But when selecting **Prettier** it doesn't. Before Astro 3, this worked just fine.

I now downgraded back to `2.10.15` and everything instantly started working again.

Are there undocumented changes that I have to make in some config files or the way VS Code is set up? Or could this be an issue with the Astro Language Server?

### Repro
1. Clone this project: https://github.com/xriter/repro-astro-3-prettier (This is basically just the 'Empty Project' template from `www.astro.new`).
2. Open it in VS Code (with the Astro and Prettier extensions installed).
3. Run `npm install` to install the dependencies.
4. Then open `/src/pages/index.astro`.
5. Then try formatting the file using prettier (Run command > Format document with... > Prettier)
The line
```
const {
	a } = Astro.props;
```
should be formatted by Prettier to:
```
const { a } = Astro.props;
```
but Prettier will throw the error mentioned earlier.

**Comment by nomorejalapenos** [comment]
same issue

**Comment by Princesseuh** [comment]
In 2.x, the Astro language server included an old version of Prettier and the Prettier plugin by accident as transitive deps, we never intended for anyone to depend on this (and in most cases, it didn't work to depend on it anyway) and it was fully removed in 3.0.

To make things work again in your setup, you can install the Prettier plugin in your setup and configure your project accordingly: https://github.com/withastro/prettier-plugin-astro
