### ISSUE TITLE
Allow for empty content collections

### ISSUE THREAD

**Issue by pReya** [withastro/astro#8336]
### Astro Info

```block
Astro version            v2.9.6
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  Couldn't determine.
Integrations             @astrojs/react, @astrojs/tailwind, auto-import, @astrojs/mdx
```

### Describe the Bug

I'm well aware some might see this as a new feature, but I have to disagree. Content collections should be able to handle a "empty state" – meaning you should be able to use a content collection which has no items. Currently, this will always throw an error, so the page basically breaks. But there are plenty valid use cases for empty collections and it should be possible to still use the site (e.g. throw a warning instead of an error).

Also the error is technically not correct. This is what it says:
```
 error   The collection examples does not exist. Ensure a collection directory with this name exists.
 ```

Yet, this is also the error, when the folder exists, but there's just no file in it.

Am I missing something or is this really an oversight in the concept of content collections?

### What's the expected result?

Page should still render

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-agpp3a?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'd consider this mostly to be a bad error message, but we also should probably just warn instead of throw. Seems fair to me.

**Comment by DerTimonius** [comment]
I would like to take a look into this!

**Comment by DerTimonius** [comment]
@natemoo-re I have a quick question regarding the warning instead of throwing an error: in #8382 I removed the `AstroError` and changed it to a zodIssue, but I'm not sure if this would be the correct way. Was wondering, if there is a way to use something like `logger.warn`?

**Comment by pReya** [comment]
@natemoo-re Push! Can you help @DerTimonius ?
