### ISSUE TITLE
`client:only` causes component contents to be deleted in output (v3)

### ISSUE THREAD

**Issue by xiBread** [withastro/astro#8337]
### Astro Info

```block
Astro                    v3.0.5
Node                     v20.5.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/vue
                         @astrojs/mdx
```

### Describe the Bug

Building a project with components using the `client:only` directive results in its contents disappearing, e.g., building this:

```html
<!-- Component.vue -->
<template>
	<div class="hello">
		Lorem ipsum.
	</div>
</template>

<!-- index.astro -->
<Component client:only="vue">
```

↓↓↓

```html
<!-- dist/index.html -->
<astro-island ...></astro-island>
```

If I add a `<slot />` to the component, the slotted content is placed, but all other elements are ignored:

```html
<!-- Slotted.vue -->
<template>
	<div class="a">
		<slot />
	</div>

	<div class="b"></div>
</template>

<!-- index.astro -->
<Slotted client:only="vue">
	<p>Lorem ipsum</p>
</Slotted>
```

↓↓↓

```html
<!-- dist/index.html -->
<astro-island ...>
	<template data-astro-template>
		<p>Lorem ipsum</p>
	</template>
</astro-island>
```

Screenshots from my project:

[v2.10.14](https://imgur.com/5plL015.jpg)
[v3.0.5](https://i.imgur.com/Rp2oxfC.jpg)
[Console output](https://imgur.com/QLZHz9L.jpg)

### What's the expected result?

The contents are preserved.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4wkbtj?file=dist%2Findex.html

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This one may have been my fault! I refactored the Vue renderer in https://github.com/withastro/astro/pull/8264 and may have caused a regression for `client:only`.

I'm pretty sure you can pin to [`@astrojs/vue@2.2.1`](https://www.npmjs.com/package/@astrojs/vue/v/2.2.1) until we get this fixed!

**Comment by pijusz** [comment]
I have somewhat similar error with react:
Qouting from other (symlink issue):

I'm using React components with shadcn's navigation (Mobile and Desktop modals) with:
client:load and Mobile Nav also has: client:media="(max-width: 1024px)"
In preview I get 2 console errors (in dev mode it works):
"SES_UNHANDLED_REJECTION: TypeError: error loading dynamically imported module: URL"
And then "Loading module from “URL” was blocked because of a disallowed MIME type (“text/html”)."
React Components dont work.

**Comment by xiBread** [comment]
Upon further testing, I was able to get the above reproduction working using `@astrojs/node`, so this could be an issue with the Vercel integration.

**Comment by BlankParticle** [comment]
I can confirm this issue is also in `client:load`, `client:idle` and `client:only` while working with `hybrid` rendering in `@astrojs/node`, I have found the potential problem and reported it in #8379

**Comment by blazeshomida** [comment]
I'm having what I believe is a similar issue using solid-js, although not sure if maybe its just me doing something wrong.

**Comment by xiBread** [comment]
This seems to have been fixed in one of the lastest releases.
