### ISSUE TITLE
Access env. in production

### ISSUE THREAD

**Issue by GiovaneRobertiTafine** [withastro/astro#8338]
### Astro Info

```block
Not information
```

### Describe the Bug

I created an .env file in the root folder of the project, at the same level as package.json, and in developer mode, I can access the PUBLIC_TODOS variable, but in production mode I cannot access the PASSWORD_SECRETA variable, it stays as undefined

```
.env:
SENHA_SECRETA='sdenha123'
PUBLIC_TODOS='aqui'

gestao.js:
const isProd = import.meta.env.SENHA_SECRETA;
const isDev = import.meta.env.PUBLIC_TODOS;

package.json:
"devDependencies": {
        "@astrojs/react": "^2.0.2",
        "astro": "^2.0.6",
        "sass": "^1.49.9"
}
```

### What's the expected result?

Access environment variable in prod.

### Link to Minimal Reproducible Example

http

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Is `gestao.js` loaded in the browser or only the server? If it is loaded on the client, your environment variables **must** be prefixed with `PUBLIC_`.

Additionally, please be sure to fill out all the information in the issue template. It's required for a reason! We can't debug issues without all the requested information and a proper reproduction.

**Comment by GiovaneRobertiTafine** [comment]
I'm loading gestao-email.js in a static page as follows:

```
 <script>
         import * as gestaoEmail from "../js/gestao-email.js";
            globalThis.gestaoEmail = gestaoEmail;
</script>
```
And after generating the build, I insert an .env file at the same level as the index.html file

```
export default defineConfig({
  
    integrations: [
        react(),
    ],
});
```

**Comment by natemoo-re** [comment]
So yes, this is working as intended. 

Any environment variable that loads in the browser (inside of a `<script>` tag) needs to be named with a `PUBLIC_` prefix. This is for security, so that you don't accidentally leak a server-side secret in your client code where anyone can access it. The `PUBLIC_` prefix is how you opt-in to allowing a secret on the client.
