### ISSUE TITLE
Cannot access to the KV binding with Cloudflare Pages

### ISSUE THREAD

**Issue by shahin-hq** [withastro/astro#8347]
### Astro Info

```block
Astro version            v3.0.5
Package manager          pnpm
Platform                 linux
Architecture             x64
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind, @astrojs/react
```

### Describe the Bug

I have an endpoint which tries to access bindings but it constantly fails with an error. I tried two examples from Astro and Cloudflare docs:

```JS
export function get(context) {
  const runtime = context.locals.runtime;

  return new Response('Some body');
}
```

Error:      error   Cannot read properties of undefined (reading 'env')

```JS
import type { APIContext } from "astro";
import { getRuntime } from "@astrojs/cloudflare/runtime";

export async function get({request}: APIContext) => {
  const runtime = getRuntime(request);
  // the type KVNamespace comes from the @cloudflare/workers-types package
  const { MY_KV } = (runtime.env as { MY_KV: KVNamespace }));

  return {
    // ...
  };
};
``` 

Error: Cannot find module '@astrojs/cloudflare/runtime' imported from 

How can I access to the CF runtime?

### What's the expected result?

Get access to the Cloudflare runtime

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-k5f65r?file=src%2Fpages%2Fapi%2Fstats.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
@shahin-hq the following works. But please keep in mind that CF runtime is not available with `astro dev`. You need either to use `wrangler pages dev dist` or publish your site.

```ts
export async function GET(context) {
  const runtime = context.locals.runtime;

  return new Response(JSON.stringify(runtime), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
```

**Comment by shahin-hq** [comment]
@alexanderniebuhr Thank you for the response, the solution you suggested indeed works, however, now I get a different error.

```JS
❯ npx wrangler pages dev dist --compatibility-date=2023-08-14 --log-level=debug
No functions. Shimming...
 ⛅️ wrangler 3.6.0
------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":true}}.
Using vars defined in .dev.vars
Your worker has access to the following bindings:
- KV Namespaces:
  - DASHBRD_LANDING: ID_REDACTED
- Vars:
  - ENVIRONMENT: "(hidden)"
⎔ Starting local server...
[mf:dbg] Updated `Request.cf` object cache!
workerd/server/server.c++:2620: info: Inspector is listening
✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.

```

here is my `wrangler.toml`:

```toml
name = "dashbrd-landing"
compatibility_date = "2023-08-14"

kv_namespaces = [
  { binding = "DASHBRD_LANDING", id = "ID_REDACTED", preview_id = "PREVIEW_ID_REDACTED" }
]

```

It doesn't log anything else to debug, why do you think this is happening? 


It doesn't work when I publish it too, I get this error in browser console: 

```
Refused to apply style from 'https://xxx.pages.dev/_astro/cookie-policy.d1873d42.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by alexanderniebuhr** [comment]
Not sure. Can you add the css to the stackblitz example?
It could be a misconfigured base path. But can't tell without seeing it.

**Comment by shahin-hq** [comment]
@alexanderniebuhr Thanks for looking into that. Since it is hard to replicate the all components I granted access to the private repo, please check your email. However, I used a different account of mine with ID: @shahinsafaraliyev.
The latest changes are in the first PR.

**Comment by alexanderniebuhr** [comment]
Ok I **can not** reproduce it. The project works for me. However I had a lot of other build issues with the project, I don't think this is a issue with the CF adapter or the new way the runtime is exposed, and I would say you would need a minimal reproduction, to get down to the cause.

But this is what I changed, maybe that helps you:

```diff
diff --git i/astro.config.mjs w/astro.config.mjs
index 9d2eccf..3d33e6e 100644
--- i/astro.config.mjs
+++ w/astro.config.mjs
@@ -7,10 +7,15 @@ import cloudflare from "@astrojs/cloudflare";
 
 // https://astro.build/config
 export default defineConfig({
+  image: {
+    service: {
+      entrypoint: "astro/assets/services/noop",
+    },
+  },
   integrations: [tailwind(), react()],
   vite: {
-    plugins: [svgr()]
+    plugins: [svgr()],
   },
-  output: "hybrid",
-  adapter: cloudflare({mode: "advanced"}),
+  output: "server",
+  adapter: cloudflare({ mode: "advanced" }),
 });
 ```
 
 ```diff
 diff --git i/src/env.d.ts w/src/env.d.ts
index f964fe0..be839e7 100644
--- i/src/env.d.ts
+++ w/src/env.d.ts
@@ -1 +1,9 @@
 /// <reference types="astro/client" />
+type AdvancedRuntime = import("@astrojs/cloudflare").AdvancedRuntime;
+type KVNamespace = import("@cloudflare/workers-types").KVNamespace;
+
+declare namespace App {
+  interface Locals extends AdvancedRuntime {
+    runtime: AdvancedRuntime & { env: { DASHBRD_LANDING: KVNamespace } };
+  }
+}
```

**Comment by alexanderniebuhr** [comment]
Ok I **can not** reproduce it. The project works for me. However I see a lot of other issues with the project, I don't think this is a issue with the CF adapter or the new way the runtime is exposed, and I would say you would need a minimal reproduction, to get down to the cause.

But this is what I would at least change, maybe that helps you:

```diff
diff --git i/astro.config.mjs w/astro.config.mjs
index 9d2eccf..3d33e6e 100644
--- i/astro.config.mjs
+++ w/astro.config.mjs
@@ -7,10 +7,15 @@ import cloudflare from "@astrojs/cloudflare";
 
 // https://astro.build/config
 export default defineConfig({
+  image: {
+    service: {
+      entrypoint: "astro/assets/services/noop",
+    },
+  },
   integrations: [tailwind(), react()],
   vite: {
-    plugins: [svgr()]
+    plugins: [svgr()],
   },
-  output: "hybrid",
-  adapter: cloudflare({mode: "advanced"}),
+  output: "server",
+  adapter: cloudflare({ mode: "advanced" }),
 });
 ```
 
 ```diff
 diff --git i/src/env.d.ts w/src/env.d.ts
index f964fe0..be839e7 100644
--- i/src/env.d.ts
+++ w/src/env.d.ts
@@ -1 +1,9 @@
 /// <reference types="astro/client" />
+type AdvancedRuntime = import("@astrojs/cloudflare").AdvancedRuntime;
+type KVNamespace = import("@cloudflare/workers-types").KVNamespace;
+
+declare namespace App {
+  interface Locals extends AdvancedRuntime {
+    runtime: AdvancedRuntime & { env: { DASHBRD_LANDING: KVNamespace } };
+  }
+}
```

**Comment by lilnasy** [comment]
@shahin-hq You might be running into this bug, which already has a fix waiting to be reviewed. "output: hybrid" and the react integration in your config suggests you are.
https://github.com/withastro/astro/issues/8323#issuecomment-1701398141

**Comment by alexanderniebuhr** [comment]
You need to rebuild it every time you change something, because you can't use dev server. I'm pretty sure you are having the issue, which was linked [here](https://github.com/withastro/astro/issues/8323#issuecomment-1701398141). So the command should be:
```
npm install &&  npm run build && npx wrangler pages dev dist --compatibility-date=2023-08-14 --log-level=debug
```

**Comment by shahin-hq** [comment]
@alexanderniebuhr It indeed works now! Thank you very much for the help! :tada: 
I have one more question: is there a way to setup HMR loading for it? I'd love to have the thing reloaded when I make changes.

**Comment by alexanderniebuhr** [comment]
There is `--live-reload` for wrangler, but that means you would need to setup nodemon for the `npm run build`. [More references.](https://github.com/withastro/roadmap/discussions/273)

There is also `proxy` mode of wrangler, you can find run `astro dev` and run wrangler with proxy flag pointing to the astro port. However I'd personally issues with proxy not exposing all bindings, but maybe that is fixed.

**Comment by shahinsafarali** [comment]
That would very nice. Thank you very much @alexanderniebuhr, I appreciate your help!

**Comment by nefeleai** [comment]
try for live reloading
```
    "pages:dev": "wrangler pages dev --compatibility-date=2023-11-21 -- astro dev"
```
