### ISSUE TITLE
[Astro 3] Island is not being loaded in SSR (node or vercel)

### ISSUE THREAD

**Issue by raulfdm** [withastro/astro#8355]
### Astro Info

```block
Astro                    v3.0.5
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/partytown
                         @astrojs/tailwind
                         @astrojs/react
                         astro-robots-txt
                         @astrojs/prefetch
                         @astrojs/svelte
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome: 116.0.5845.140

### Describe the Bug

I noticed the loading of an island (my side menu) is not working when we build for both serverless (vercel) and SSR (with node).

- Astro v2 working: https://www.raulmelo.me/en
- Astro v3 URL preview: https://raulmelo-igejlcuvx-raulmelo-studio.vercel.app/en
- Branch: https://github.com/raulfdm/raulmelo-studio/pull/2499

Console errors:

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://raulmelo-igejlcuvx-raulmelo-studio.vercel.app/
```

It's important to note that running the `dev` command it works just fine.

### What's the expected result?

Loads correctly the island.

### Link to Minimal Reproducible Example

https://github.com/devraul/astro-3-island-load-error-ssr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by raulfdm** [comment]
I tried to upload the video here but it has 13mb and the limit is 10mb 😒

Here's a demo: https://drive.google.com/file/d/1wvAIfSHAUQWuF8mdNz_OenzpOBQmFi6u/view?usp=sharing

**Comment by xiBread** [comment]
related #8337
