### ISSUE TITLE
Astro 3.0 not respecting Vercel export config runtime edge

### ISSUE THREAD

**Issue by j-mendez** [withastro/astro#8362]
### Astro Info

```block
Astro                    v3.0.6
Node                     v20.0.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/edge
Integrations             @astrojs/react
                         @astrojs/tailwind
                         @astrojs/sitemap
```

### Describe the Bug

When upgrading to astro 3.0 and vercel 4.0.0 the `export const config = { runtime: 'edge' }` in the API route is no longer respected.

### What's the expected result?

Expected an edge route in vercel instead of node.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-x6rs8v?file=src%2Fpages%2Fapi%2Fmethods.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Unfortunately, configuring the vercel adapter to decide the runtime per-page was never supported.

The reason for your issue might be that the edge adapter was removed and some of its functionality was moved into the serverless adapter. You might want to update @astrojs/vercel as well.

You can read about it here:  https://docs.astro.build/en/guides/upgrade-to/v3/#what-should-i-do-13
