### ISSUE TITLE
Astro listens to file changes outside the root directory in a monorepo

### ISSUE THREAD

**Issue by mooxl** [withastro/astro#8369]
### Astro Info

```block
Astro                    v3.0.5
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
```

### Describe the Bug

I have a monorepo using pnpm, and one of the packages in the repo is Astro. Although everything is functioning correctly, it appears that Astro is monitoring file changes across the entire monorepo. I attempted to explicitly set the root in astro.config.mjs, but it did not resolve the issue.

Here is an example of the output I'm receiving:
`12:36 PM [astro] update /pathtoastroad/astroad/docker-compose.yml (x2)`

### What's the expected result?

Astro should only listen to file changes in its directory.

### Link to Minimal Reproducible Example

https://github.com/mooxl/astroad/tree/reproduction-file-changes

1. `pnpm install`
2. `pnpm dev` starts only the astro package, since i have removed the others from the workspace 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Is this happening because of this Vite setting? I think Vite might be treating it as if the `envDir` is the root of the project.

https://github.com/mooxl/astroad/blob/b9089ca1ac9442838f1f695235edf5f379bd01eb/astro/astro.config.mjs#L6C1-L7C1

**Comment by bluwy** [comment]
Yup, Vite also adds the `envDir` as a path to watch at https://github.com/vitejs/vite/blob/aae3a83b5fb49bbd9f174cfeac66f00483829da4/packages/vite/src/node/server/index.ts#L362

In this case, it should be fine for Astro/Vite to watch this folder, however, the dev server probably shouldn't react to it. That behaviour is tracked at https://github.com/withastro/astro/issues/8224, so closing this in favour of that for now.
