### ISSUE TITLE
Unable to escape apostrophe in front matter

### ISSUE THREAD

**Issue by third774** [withastro/astro#8374]
### Astro Info

```block
Astro                    v3.0.7
Node                     v20.5.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Trying to add an escaped apostrophe in the front matter doesn't seem to work.

![image](https://github.com/withastro/astro/assets/8732191/62533be5-ba10-4ba2-99dd-9e59f756fe28)

### What's the expected result?

I guess I expected to be able to escape the apostrophe?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tmqkgt?file=src/content/blog/first-post.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by andremralves** [comment]
Astro uses the YAML syntax in the [frontmatter](https://docs.astro.build/en/guides/markdown-content/) and I believe you can't use this kind of escaping in YAML. Removing the surrounding single quotes worked fine for me.

**Comment by lilnasy** [comment]
Thanks @andremralves, closing this issue as a quirk in yaml.

**Comment by third774** [comment]
I've got a follow-up question — assuming it isn't already, should JSON as frontmatter be supported?

**Comment by third774** [comment]
Aha — just tried it and it seems like it works! 🎉 Maybe this would be good to add to the docs?

**Comment by lilnasy** [comment]
It works because YAML is a superset of JSON. Valid JSON is valid YAML.
