### ISSUE TITLE
Astro 3 breaks support on `android-arm64v8`

### ISSUE THREAD

**Issue by vedxp** [withastro/astro#8375]
### Astro Info

```block
Astro version            v3.0.6
Package manager          pnpm
Platform                 android
Architecture             arm64
Adapter                  Couldn't determine.
Integrations             unocss
```

### Describe the Bug

I've encountered an issue with Astro v3 where support for the `android-arm64v8` platform seems to have been broken due to recent breaking changes.

Starting from Astro v3, the default image service is set to Sharp. Unfortunately, prebuilt binaries for Sharp is not available for the `android-arm64v8` platform, leading to this problem. When trying to initiate an Astro project on this platform, the following error is encountered:
```sh
pnpm create astro@latest
```
```sh
node_modules/.pnpm/sharp@0.32.5/node_modules/sharp: Running install script, failed in 2.1s
.../sharp@0.32.5/node_modules/sharp install$ (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-comp…
│ sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.4/libvips-8.14.4-android-arm64v8.tar.br
│ sharp: Installation error: Prebuilt libvips 8.14.4 binaries are not yet available for android-arm64v8
│ sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
└─ Failed in 2.1s at /data/data/com.termux/files/home/gst/node_modules/.pnpm/sharp@0.32.5/node_modules/sharp
 ELIFECYCLE  Command failed with exit code 1.
```

This issue prevents Astro projects from being properly initialized on the `android-arm64v8` platform. It would be greatly appreciated if this incompatibility could be addressed or if any guidance could be provided on potential workarounds or solutions.

### What's the expected result?

Astro v3 should seamlessly run on the `android-arm64v8` platform and enable project initiation without any hindrance, just as it did in previous versions.

### Link to Minimal Reproducible Example

Couldn't reproduce on web IDEs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jacobthesheep** [comment]
The issue is due to the [sharp](https://sharp.pixelplumbing.com/install)  library not supporting android-arm64v8. A possible solution could be to modify Astro to use its "noop" service for platforms that don't support Squoosh or Sharp.

**Comment by Princesseuh** [comment]
You might be able to work around the issue by doing `npm install --platform=linux sharp` though I don't know if this will make it actually work. Alternatively, overriding the dependency and using the Squoosh service instead would work.

Sharp is currently working towards having a WASM version, which would also help with this for platforms that don't have binaries available.

**Comment by vedxp** [comment]
> The issue is due to the [sharp](https://sharp.pixelplumbing.com/install) library not supporting android-arm64v8. A possible solution could be to modify Astro to use its "[noop](https://github.com/withastro/astro/blob/main/packages/astro/src/assets/services/noop.ts)" service for platforms that don't support Squoosh or Sharp.


Thank you for the suggestion. I've already configured Astro to use the "noop" service as the image service in my `astro.config.mjs` file as follows:
```mjs
export default ({
  image: {
    service: {
      entrypoint: 'astro/assets/services/noop'
    },
  },
})
```

However, I'm still encountering the same error related to the Sharp library not supporting the `android-arm64v8` platform. It seems that the configuration change didn't resolve the issue.

Is there anything else I might need to do or configure to ensure that Astro uses the "noop" service correctly on platforms where Sharp is not supported?

Any further guidance or assistance would be greatly appreciated. Thank you for your help.

**Comment by vedxp** [comment]
> You might be able to work around the issue by doing `npm install --platform=linux sharp` though I don't know if this will make it actually work. Alternatively, overriding the dependency and using the Squoosh service instead would work.
> 
> Sharp is currently working towards having a WASM version, which would also help with this for platforms that don't have binaries available. You might be able to override the sharp dependency with `@webassembly/sharp` in the meantime

- `npm install --platform=linux sharp` didn't seem to work as expected.
- I've also attempted this approach using Astro's configuration to set the default image service to `squooshImageService` as follows:
```js
import { defineConfig, squooshImageService } from 'astro/config';

export default defineConfig({
  image: {
    service: squooshImageService(),
  },
});
```
- Despite configuring the default image service to use `squooshImageService`, I've observed that Astro still attempts to install the Sharp package when installing packages with pnpm install. This persistence of Sharp installation results in the same error:
```sh
node_modules/.pnpm/sharp@0.32.5/node_modules/sharp: Running install script, failed in 2.1s
.../sharp@0.32.5/node_modules/sharp install$ (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-comp…
│ sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.4/libvips-8.14.4-android-arm64v8.tar.br
│ sharp: Installation error: Prebuilt libvips 8.14.4 binaries are not yet available for android-arm64v8
│ sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
└─ Failed in 2.1s at /data/data/com.termux/files/home/gst/node_modules/.pnpm/sharp@0.32.5/node_modules/sharp
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Princesseuh** [comment]
Sharp is a dep of Astro, so you'll need to override the dep: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

**Comment by budchirp** [comment]
> Sharp is a dep of Astro, so you'll need to override the dep: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
> 
> I'm thinking something we could do is make it an optional dep instead...

Next.js uses squoosh for Image tag in dev but recommends using sharp ın production. Astro can have the same thing too.
![Screenshot_20230903_210531_Termux](https://github.com/withastro/astro/assets/80613396/9aca313e-a6bf-47fc-8be6-3623eb9b72c8)

**Comment by budchirp** [comment]
> > Sharp is a dep of Astro, so you'll need to override the dep: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
> > I'm thinking something we could do is make it an optional dep instead...
> 
> Next.js uses squoosh for Image tag in dev but recommends using sharp ın production. Astro can have the same thing too. ![Screenshot_20230903_210531_Termux](https://user-images.githubusercontent.com/80613396/265281190-9aca313e-a6bf-47fc-8be6-3623eb9b72c8.jpg)

After a litte bit of dependency inspecting, I found a *temporary* fix. Installing `xorgproto` and `libvips` fixes sharp.

complete code:
```sh
pkg i x11-repo && pkg i build-essential clang make libvips xorgproto glib
```

after that, go to your astro project and run `yarn` or `npm i`

**Comment by vedxp** [comment]
Though [#8416](https://github.com/withastro/astro/pull/8416) had fixed the issue for `pnpm run dev`, I'm still getting errors when running `pnpm run build`. 

## Astro Info
```
Astro@3.6.0
```

## Errors:
```

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-android-arm64v8.node'
Require stack:
- /data/data/com.termux/files/home/cr/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/sharp.js
- /data/data/com.termux/files/home/cr/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/constructor.js
- /data/data/com.termux/files/home/cr/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/index.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current android-arm64v8 runtime: "npm install --platform=android --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/data/data/com.termux/files/home/cr/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/cr/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)

Node.js v20.2.0
```
