### ISSUE TITLE
<form> navigations aren't handled by the View Transitions router

### ISSUE THREAD

**Issue by markmals** [withastro/astro#8381]
### Astro Info

```block
Astro                    v3.0.7
Node                     v20.4.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  astro-vercel-edge
Integrations             @astrojs/solid-js
                         unocss
```

### Describe the Bug

When submitting a `<form>` or `<form action="get">`, the browser sends a request for the document at the form's `action` attribute, serializing the form's data as URLSearchParams, for example:

```html
<h3>Filter by Stars</h3>
<form>
    <button name="stars" value="1">1 Star</button>
    <button name="stars" value="2">2 Stars</button>
    <button name="stars" value="3">3 Stars</button>
</form>
```

Clicking on the "1 Star" button in this form should request the document at the URL `/?stars=1`. This is equivalent to using an anchor link to navigate to `/?stars=1`, but is more idiomatic. However, when submitting this form with the new view transitions single-page router, it performs a full page reload.

(**Note:** StackBlitz doesn't seem to be able to handle navigations that just append query parameters to the current URL, neither via `<a>` nor `<form>`. The linked minimal reproducible example doesn't work in StackBlitz but does work in a local dev environment)

### What's the expected result?

The page should retrieve the new page from the get request and replace the content with animations and while persisting `transition:persist` elements, just like it does when navigating via `<a>` tags.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mxrq8z?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks! Going to move to the roadmap as this is a new feature. It is something we are definitely going to have in an upcoming beta.

**Comment by lilnasy** [comment]
Manually posted here because there is no transfer option.
https://github.com/withastro/roadmap/discussions/682
