### ISSUE TITLE
Intellisense: Property 'name' does not exist on type 'AnchorHTMLAttributes'.

### ISSUE THREAD

**Issue by dr-vortex** [withastro/astro#8386]
### Astro Info

```block
Astro version            v2.10.7
Package manager          npm
Platform                 win32
Architecture             x64
Adapter                  Couldn't determine.
Integrations             None or couldn't determine.
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

Setting `name` of an `a` element gives an error.

### What's the expected result?

It should work.

Note this does not work with Stackblitz since it does not have intellisense.

### Link to Minimal Reproducible Example

\<a name={a_name}\>\</a\>

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
I don't mind adding this to our types, but this attribute was deprecated a very very long time ago, is there a specific reason you need it?

**Comment by dr-vortex** [comment]
I was using it for linking like this:

`<a name={release.name}></a>`

Using `id` could also work so I should probably use that.
