### ISSUE TITLE
functionPerRoute fails on Netlify

### ISSUE THREAD

**Issue by kingbiscit** [withastro/astro#8394]
### Astro Info

```block
Astro                    v3.0.7
Node                     v18.17.1
System                   macOS (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @storyblok/astro
                         @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

Enabling functionPerRoute on Netlify causes all requests to 404.

netlify({ functionPerRoute: true })

Example config

```js
import { defineConfig } from 'astro/config';
import netlify from '@astrojs/netlify/functions';

export default defineConfig({
  output: 'server',
  adapter: netlify({
    functionPerRoute: true,
  }
)}
```

### What's the expected result?

Functions should be created for each route but the site should render pages not 404.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u77xna?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Your reproduction repository doesn't build. Could you please fix it?

**Comment by stormynight9** [comment]
having the same issue here, SSR pages get redirected to 404.
