### ISSUE TITLE
deploy on netlify

### ISSUE THREAD

**Issue by gnani1226** [withastro/astro#8396]
### 📋 Explain your issue

i have a astro project and SSR enabled, now i want to deploy it using netlify but it is throwing an error i'm posting the error below you can find it

`he following serverless functions failed to deploy: manifest.2a3eab85
4:45:35 PM: To deploy these functions successfully, change the function names to contain only alphanumeric characters, hyphens or underscores
4:45:34 PM: Deploy site                                                   
4:45:34 PM: ────────────────────────────────────────────────────────────────
4:45:34 PM: ​
4:45:34 PM: Starting to deploy site from 'dist'
4:45:34 PM: Calculating files to upload
4:45:35 PM: Section completed: deploying
4:45:35 PM: ​
4:45:35 PM: Configuration error                                           
4:45:35 PM: ────────────────────────────────────────────────────────────────
4:45:35 PM: ​
4:45:35 PM:   Error message
4:45:35 PM:   Deploy did not succeed: [PUT /sites/{site_id}/deploys/{deploy_id}][422] updateSiteDeploy default  &{Code:422 Message:Incorrect function names. Name should consist of only alphanumeric characters, hyphen & underscores}
4:45:35 PM: ​`

**Comment by ematipico** [comment]
@gnani1226 We fixed in the issue, you should try the latest: `3.0.8`
