### ISSUE TITLE
Upgrading to v3 broke my localStorage reading ts file

### ISSUE THREAD

**Issue by kelvinz** [withastro/astro#8400]
### Astro Info

```block
Astro                    v3.0.8
Node                     v20.5.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

In my static paths, I have a store.ts file which I use to read/write localStorage, but after upgrading my astro and it's adaptors, I'm getting this error,

```
[vite] Error when evaluating SSR module /src/assets/store.ts:
|- ReferenceError: localStorage is not defined
    at persistentStore (/mfs/src/assets/store.ts:6:23)
    at eval (/mfs/src/assets/store.ts:12:19)
    at async instantiateModule (file:////mfs/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)
```

### What's the expected result?

Previously it was working and reads/writes my localStorage as per normal.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jsgbgb?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
In v3 we have removed the global `localStorage` shim, so the error is expected. `localStorage` doesn't exist in node in the first place. If you're intending to use this for the browser, you can wrap it in a script tag instead.

**Comment by kelvinz** [comment]
Eh? You mean in v3, we can no longer import script files to work with if they contain stuff like localStorage? This doesn't seem to be right... Instead I need to duplicate all my functions and use them inside each page's script tag? Feels like a step backwards no?

**Comment by bluwy** [comment]
In your case as you're importing the script from a Svelte file (I initially thought it was an Astro file), you can update `store.ts` to anticipate if `localStorage` doesn't exist instead. For example:

```js
const storedValue = typeof localStorage !== 'undefined' && localStorage.getItem('hello');
export const initialValue =
  storedValue === null ? 'hi' : JSON.parse(storedValue);
```
