### ISSUE TITLE
Vercel `includeFiles` is Ignored for Hybrid API Routes with `prerender = false`

### ISSUE THREAD

**Issue by joe-bell** [withastro/astro#8402]
### Astro Info

```block
Astro                    v3.0.8
Node                     v18.14.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### Describe the Bug

> **Note**
> This issue was discovered when trying to migrate to `astro@3.0` – this worked as expected in earlier versions

When referencing files - that have been disclosed via `includeFiles`- in a non-prerendered API route, Vercel returns a "This Serverless Function has crashed." warning.

In Vercel, the logs output the following message:
```
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Input file is missing: /var/task/src/assets/images/hello-there.jpg","reason":{"errorType":"Error","errorMessage":"Input file is missing: /var/task/src/assets/images/hello-there.jpg","stack":["Error: Input file is missing: /var/task/src/assets/images/hello-there.jpg"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Input file is missing: /var/task/src/assets/images/hello-there.jpg","    at process.<anonymous> (file:///var/runtime/index.mjs:1250:17)","    at process.emit (node:events:526:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```

When `prerender = false` is removed from the file, the route works as expected.

> **Note**
> I tried to determine if this was just an image-related issue, but the error still occurs for fonts when the image is removed

### What's the expected result?

I would expect for this API route to operate in the same manner as `prerender = true`

### Link to Minimal Reproducible Example

Code: https://github.com/joe-bell/astro-bug-vercel-includefiles
Preview: https://astro-bug-vercel-includefiles.vercel.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by joe-bell** [comment]
@matthewp hiya, thanks for responding 🙏🏼 

This is a relatively trivial example, but in my real-world use-case I need a separate file because it’s a `.tsx` extension (using JSX with `satori`)

AFAIA `.tsx` API routes aren’t supported but I can certainly try (or by moving the handler outside of `/api` directory)

**Comment by matthewp** [comment]
In this example is it the `hello-there.jpg` that's missing?

**Comment by matthewp** [comment]
The file *is* in the function. Maybe it's not relative to the `cwd` like expected? 

<img width="266" alt="Screen Shot 2023-09-06 at 9 48 19 AM" src="https://github.com/withastro/astro/assets/361671/81e27873-dc2b-4430-947a-705063e15c08">

**Comment by matthewp** [comment]
Same error occurs with `output: 'server'`.

**Comment by matthewp** [comment]
Using relative paths from the page seems to work:

```
const imgUrl = new URL('../../../src/images/hello-there.jpg', import.meta.url);
```

Our build preserves the structure of the built functions (tries to). Can you try this with your own project?

**Comment by joe-bell** [comment]
Can confirm that using `new URL(<relative-path-to-file>, import.meta.url);` works a treat, thank you! Happy to close this based on that knowledge.

Think it would be super valuable to encourage use of `URL` instead of `path` in the docs, especially in the goal of supporting different runtimes.

In a similar topic, what would you recommend in place of `fs.readFile` (alongside `URL`) to extract a `Buffer`?

**Comment by matthewp** [comment]
Great to hear! Actually I'm not sure what the advice should be for reading files in a serverless environment. I think fs.readFile is fine in this case, but each runtime has different considerations. It's actually the combination of bundling + serverless filesystem access that makes the topic so fraught. Glad you found a solution here and agree about documenting URL as the thing to use more.

**Comment by joe-bell** [comment]
Unfortunately this workaround no longer works 😢 
https://github.com/withastro/astro/issues/10380
