### ISSUE TITLE
View Transitions

### ISSUE THREAD

**Issue by bis0072** [withastro/astro#8403]
### Astro Info

```block
Astro                    v3.0.8
Node                     v18.17.1
System                   Windows (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

VM250:1 Uncaught TypeError: Cannot redefine property: userAgent
    at Function.defineProperty (<anonymous>)
    at <anonymous>:1:8
    at runScripts (ViewTransitions.astro:96:11)
    at navigate (ViewTransitions.astro:269:10)

### What's the expected result?

Showing TypeError while navigating from one layout to another layout. I don't know from where the error coming, Please help.

### Link to Minimal Reproducible Example

na

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hey @bis0072, `runScripts (ViewTransitions.astro:96:11)` runs the scripts in your pages. 
The error you see most likely happens because your script is executed more than once, see https://docs.astro.build/en/guides/view-transitions/#script-behavior-during-page-navigation for details and recipes how to resolve this.

**Comment by matthewp** [comment]
@bis0072 if you could, please create a project using https://astro.new/latest/ and give us a link to it. That is how we are able to debug and diagnose issues. Thank you.
