### ISSUE TITLE
`slot` prop in `<style />` tag ignored

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#8413]
### Astro Info

```block
Astro                    v3.0.8
Node                     v16.20.0
System                   Linux (x64) (Stackblitz)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

i have a Html component for basic layout, in which i wrote:

```tsx
...
<head>
  {Astro.slots.has('noscript') && (<noscript><slot name="noscript" /></noscript>)}
...
```

and i'm passing some global override to allow disabling "onload" transitions on image, such as:

```html
<img src="" style="opacity: 0" onload="this.style.opacity = 1" />
```

```html
<Html>
  <style slot="noscript" is:global>img { opacity: 1 !important }</style>
</Html>
```

when doing so, the `<style>` tag is not placed inside of the `<noscript>` tag

### What's the expected result?

the slot placement should be respected

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-zyb346?file=src%2Fpages%2Fbroken.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You want to use `is:inline` to prevent Astro from pulling out the styles and bundling them. Checked and this fixes your issue.

**Comment by y-nk** [comment]
@matthewp but having `is:inline` would prevent minification and tailwind related `@apply` things right?
