### ISSUE TITLE
an error tip when i create the astro project

### ISSUE THREAD

**Issue by aswind7** [withastro/astro#8425]
### Astro Info

```block
There is information in the picture below,  astro   v3.0.8 Launch sequence initiated.
```

### Describe the Bug

<img width="602" alt="image" src="https://github.com/withastro/astro/assets/12571054/e93429d3-f9c0-4a78-8ea9-6dfb5245cd03">

Whether I own the folder or not, it always displays an error tooltip;

### What's the expected result?

do not show the error 

### Link to Minimal Reproducible Example

--

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aswind7** [comment]
but now i cant reproduction that... i dont know why.

**Comment by natemoo-re** [comment]
Based on that error, it seems like `./astro-process` exists and has some files in it. Is it possible that's the case? That's why this error would appear.

Unfortunately without a reproducible example of the issue, there's not much more we can do.

**Comment by aswind7** [comment]
> Based on that error, it seems like `./astro-process` exists and has some files in it. Is it possible that's the case? That's why this error would appear.
> 
> Unfortunately without a reproducible(重现) example of the issue, there's not much more we can do.

😄Wow you are  so nice for relplying to me. The situation should be as  you said. Thank you! I'll close the issue soon because I can't provide a reproducible example.
