### ISSUE TITLE
I updated from v2 to V3  and now I get error when i do npm run dev

### ISSUE THREAD

**Issue by Thebuilderekes** [withastro/astro#8434]
### Astro Info

```block
Astro                    v3.0.9
Node                     v18.17.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

chrome

### Describe the Bug

I updated from v2 to V3 and now I get this error when I use npm run dev. Now using node v18.17.1 (npm v10.0.0) Deleted and node modules folder and package-lock.json and used npm install while switching between versions 20.5.1, 18.14.1, 18.17.1 and still got the same error.
![astro2](https://github.com/withastro/astro/assets/68848865/d19f730e-6cfd-494f-8e1c-b765f57ae455)

### What's the expected result?

I expect that the website shows up on localhost:4321

### Link to Minimal Reproducible Example

--

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I'd say it's likely you have some dependencies that are not updated. We will need some more information to help further, however.

**Comment by teinett** [comment]
I have the same issue. I updated from 3.0.7 today to 3.0.9 and got this:

<img width="659" alt="Снимок экрана 2023-09-06 в 12 36 22" src="https://github.com/withastro/astro/assets/1038168/43db12f8-8197-444d-a133-ee0cfa44438b">

**Comment by natemoo-re** [comment]
If anyone is able to attach a reproduction using https://astro.new/minimal that would significantly speed up our debugging process!

**Comment by teinett** [comment]
My repo with the small project: https://github.com/teinett/learn-astro-images

**Comment by natemoo-re** [comment]
Looks like this is the code that is throwing.

https://github.com/withastro/astro/blob/273335cb01615c3c06d46c02464f4496a81f8d0b/packages/astro/src/runtime/server/render/any.ts#L14

**Comment by natemoo-re** [comment]
Thanks @teinett! I'm taking a look right now.
