### ISSUE TITLE
Potential ViewTransitions memory leak with Svelte components

### ISSUE THREAD

**Issue by jerzakm** [withastro/astro#8435]
### Astro Info

```
Astro                    v3.0.9
Node                     v19.7.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             auto-import
                         @astrojs/tailwind
                         @astrojs/svelte
                         @astrojs/mdx
                         @astrojs/preact
```

### Describe the Bug

We're having issues with a potential memory leak - if you navigate in the docs several times (especially on an intensive route like /extras examples) - the amount of DOM nodes and JS listeners jumps up drastically.

It seems that Svelte components and listeners aren't destroyed on navigation. I thought it'd get fixed by this PR but I doesn't help our case
https://github.com/withastro/astro/pull/8264

Let me know if it's maybe something that we're doing wrong or if I can help in any way to pinpoint it better.

![image](https://github.com/threlte/threlte/assets/16734228/0223f4a9-f3d1-4691-8a47-1534d8cd946c)

I created this [PR](https://github.com/threlte/threlte/pull/601) to anchor the docs in time as a reproduction. The fastest way to cause the leak is to click through the sidebar of [Extras](https://threlte-fs391o5z6-threlte.vercel.app/docs/reference/extras/getting-started) 

### What's the expected result?

Dom/listener numbers closer to this

![image](https://github.com/withastro/astro/assets/16734228/596456db-3e0b-44bf-b902-b53fa1663ee9)

### Link to Minimal Reproducible Example

https://github.com/threlte/threlte/pull/601

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks for the heads up. Will create a demo project and see what happens.

**Comment by matthewp** [comment]
Good catch, @natemoo-re should this be the `target` variable instead?
