### ISSUE TITLE
Component in MDX content collection item doesn't have styles in production only

### ISSUE THREAD

**Issue by trafnar** [withastro/astro#8436]
### Astro Info

```block
Astro                    v3.0.9
Node                     v18.15.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
```

### Describe the Bug

I'm trying to include web components created with the [Imba](https://imba.io/) programming language, which has a Vite plugin. (I realize this issue could be related to my choice of an obscure programming language, but the issue seems likely related to Astro itself, I apologize if that is not the case).

I included my imba code successfully, and wrapped it in an Astro component, so that I could include that into .mdx files.

Everything works as expected if I include that astro component in a `.mdx` page

The component works in _development only_ if I use a `.mdx` file that is part of a content collection. If I build the site for production, the styles for the imba-created web component don't work, however Javascript functionality defined by the component does work.

I initially thought this was an instance of #7761 but I guess it is not because JS does work, and the issue is limited to production.

### What's the expected result?

I expected the same result between development and production, and between mdx pages and mdx content collection items - that styles would appear in all cases.

### Link to Minimal Reproducible Example

code sandbox: https://codesandbox.io/p/github/trafnar/astro-imba-issue/main
github repo: https://github.com/trafnar/astro-imba-issue

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I tested the github repo locally and it seems to work fine for me now, even after upgrading all dependencies to latest. I'll close this for now with the assumption that it's fixed, but feel free to let me know if it's not and we can re-open it.
