### ISSUE TITLE
Error ViewTransitions in Docker container with Traefik

### ISSUE THREAD

**Issue by magiceupho** [withastro/astro#8444]
### Astro Info

```block
Astro                    v3.0.7
Node                     v18.17.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/alpinejs
                         astro-robots-txt
```

### Describe the Bug

My site built with Astro is static and I use Docker, Apache2 and Traefik to display it.
When I activate ViewTransitions and I try to navigate, I got this error:
Mixed Content: The page at 'https://dev3.jmmagicnas.fr/' was loaded over HTTPS, but requested an insecure prefetch resource 'http://dev3.jmmagicnas.fr/a-propos/'. This request has been blocked; the content must be served over HTTPS.

Is there any specific configuration to avoid this ? Or a Traefik configuration for this ?

### What's the expected result?

The expected result is that the new page when navigating can be fetched correctly.

### Link to Minimal Reproducible Example

https://dev3.jmmagicnas.fr/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
It's because your server is responding to the prefetch with a redirect to an http URL.

It's possible your server is not configured to understand prefetch, or defaults to http. I'm not sure, please consult your server documentation to fix this.

<img width="399" alt="Screen Shot 2023-09-07 at 10 55 24 AM" 
src="https://github.com/withastro/astro/assets/361671/f594b0f4-9a3f-4ef1-a765-fe3b2b2873e6">

**Comment by mooxl** [comment]
Hey @magiceupho ,

I have the same setup as you (using nginx instead of apache) and encountered the same issue. I resolved it by adding the following line to the head of my layout file:

```html
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
```

Hope this helps!

**Comment by magiceupho** [comment]
Hi @mooxl ,
Thank you ! It work for me !
Cool !

**Comment by danielo515** [comment]
> Hey @magiceupho ,
> 
> I have the same setup as you (but using nginx instead of apache) and encountered the same issue. I resolved it by adding the following line to the head of my layout file:
> 
> ```
> <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
> ```
> 
> Hope this helps!

That solved also my problem. In my case, it was on github pages rather than any docker container, but it solved the problem
