### ISSUE TITLE
Missing component styles after transition with ViewTransitions

### ISSUE THREAD

**Issue by chrisaugustsson** [withastro/astro#8447]
### Astro Info

```block
Astro v3.0.10
Node v18.17.1
System Windows (x64)
Package Manager  npm
Output server
Adapter @astrojs/cloudflare
Integrations @astrojs/vue 
             @astrojs/tailwind"
```

### Describe the Bug

When using a Vue component on a page with client:only, the styles that are inside the component, does not get applied after a navigation with ViewTransitions.

### What's the expected result?

The styles should be applied after navigating to a new page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-hcwrzy?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Might have similarities with #8114

**Comment by matthewp** [comment]
Yeah this is a duplicate, closing, working on this one now. https://github.com/withastro/astro/issues/8114

**Comment by chrisaugustsson** [comment]
This is not resolved with the latest updates.

Example: 
https://stackblitz.com/edit/withastro-astro-ejr3bu?file=package.json,src%2Flayouts%2FLayout.astro

**Comment by matthewp** [comment]
@chrisaugustsson I saw your new bug, thanks for the repro!
