### ISSUE TITLE
Typescript error for Content Collection: post with reference("tags") gives "No overload matches this call"

### ISSUE THREAD

**Issue by teinett** [withastro/astro#8450]
### Astro Info

```block
Astro                    v3.0.10
Node                     v18.17.0
System                   macOS (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             astro-compress
```

### Describe the Bug

I have a page of one post and want to show all tags from this post: `src/pages/posts/[slug].astro`

```

---
export const prerender = true;

import type { CollectionEntry } from "astro:content";
import { getEntry, getEntries } from "astro:content";
import { getCollection } from "astro:content";

interface Props {
    post: CollectionEntry<"posts">;
}

const { post } = Astro.props;

export async function getStaticPaths() {
    const allPosts = await getCollection("posts");
    return allPosts.map((post) => ({
        params: { slug: post.slug },
        props: { post },
    }));
}

const { Content } = await post.render();

// get tags data from current post
const tags = await getEntries(post.data.tags);
...

---
...
```

I receive an error in VS Code:

```
No overload matches this call.
  Overload 1 of 2, '(entries: { collection: "tags"; slug: "black" | "red" | "white"; }[]): Promise<(({ id: "black.md"; slug: "black"; body: string; collection: "tags"; data: { cover?: { src: string; width: number; height: number; format: "png" | ... 5 more ... | "svg"; } | undefined; title: string; }; } & { ...; }) | ({ ...; } & { ...; }) | ({ ...; } & { ...; }))[]>', gave the following error.
  Overload 2 of 2, '(entries: { collection: never; id: string | number | symbol; }[]): Promise<never[]>', gave the following error.ts(2769)
```
Screenshot:

<img width="977" alt="Снимок экрана 2023-09-07 в 08 51 30" src="https://github.com/withastro/astro/assets/1038168/a3316108-b98c-447e-8dd5-e2b4af10fc12">

### What's the expected result?

I follow official docs: https://docs.astro.build/en/guides/content-collections/#accessing-referenced-data
I expect to have no errors.

### Link to Minimal Reproducible Example

https://github.com/teinett/learn-astro-images

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm guessing that `post.data.tags` is not being strictly typed? It looks like there is an `| undefined` in the type definition, which is probably what's causing this TypeScript error.

Not sure if we should widen our `getEntries` type to allow this loose behavior or if there's a way we can fix the `post.data.tags` typing.

**Comment by DerTimonius** [comment]
@natemoo-re I was looking into this and I'm not sure if there is a way to fix the typing of `post.data.tags`. It looks to me as if `data` is typed as `Record<string, any>` and I don't know if this could be changed safely.
I would open a PR where I add `undefined` to getEntries with error handling if undefined is actually passed

**Comment by ascorbic** [comment]
Hi @teinett,
I'm taking a look at this, but your reproduction repo no longer exists. If this is still a problem, could you create a new, minimal reproduction and I'll take a look. Thanks!

**Comment by teinett** [comment]
> Hi @teinett, I'm taking a look at this, but your reproduction repo no longer exists. If this is still a problem, could you create a new, minimal reproduction and I'll take a look. Thanks!

Reproduction repo is public again: https://github.com/teinett/learn-astro-images

**Comment by ascorbic** [comment]
It looks like the issue is that [`tags` is optional in the config](https://github.com/teinett/learn-astro-images/blob/master/src/content/config.ts#L9), which means the type is nullable. If I remove `optional()` then the error goes away and the type is inferred correctly. I suppose `getEntries` could be expanded to allow undefined to be passed (and return undefined for that), but I think iot's probably better to keep the null check on the property itself when it's explicitly optional. 

![image](https://github.com/withastro/astro/assets/213306/82b5750b-b10e-440d-8983-da7588c59883)

**Comment by ascorbic** [comment]
I think this is behaving as expected

**Comment by mpstaton** [comment]
I'm in a neverending loop trying to solve for the same error. It's giving it to me in my helper utility, which supposed to just process whatever comes at it:

```javascript

import { unified } from 'unified'
import { rehypeAstro } from '@nasa-gcn/remark-rehype-astro'
import remarkParse from 'remark-parse'
import remarkRehype from 'remark-rehype'
import type { Root } from 'mdast'
import { toMarkdown } from 'mdast-util-to-markdown'

interface RemarkAsfOptions {
  markdownFile: string;
}

/**
 * Plugin to process Astro Special Format content
 * Converts markdown content to HTML with enhanced Astro features
 */
export default function remarkAsf(options?: RemarkAsfOptions) {
  if (!options?.markdownFile) {
    throw new Error('markdownFile is required for remarkAsf plugin');
  }

  return async function transformer(tree: Root) {
    console.log('\n🚀 Remark ASF Plugin: Starting transformation...\n');
    console.log('Processing markdown file:', options.markdownFile);
    
    try {
      // Convert tree to markdown string
      const markdown = toMarkdown(tree);
      
      // Process the content through the unified pipeline
      const result = await unified()
        .use(remarkParse)
        .use(remarkRehype)
        .use(rehypeAstro, { markdownFile: options.markdownFile })
        .process(markdown);
      
      if (!result) {
        throw new Error('Failed to process content');
      }
      
      return result.value;
    } catch (error) {
      console.error('Error in remarkAsf transformation:', error);
      return tree; // Return original tree if transformation fails
    }
  }
}
```

**Comment by mpstaton** [comment]
> import { unified } from 'unified'
> import { rehypeAstro } from '@nasa-gcn/remark-rehype-astro'
> import remarkParse from 'remark-parse'
> import remarkRehype from 'remark-rehype'
> import type { Root } from 'mdast'
> import { toMarkdown } from 'mdast-util-to-markdown'
> 
> interface RemarkAsfOptions {
>   markdownFile: string;
> }
> 
> /**
>  * Plugin to process Astro Special Format content
>  * Converts markdown content to HTML with enhanced Astro features
>  */
> export default function remarkAsf(options?: RemarkAsfOptions) {
>   if (!options?.markdownFile) {
>     throw new Error('markdownFile is required for remarkAsf plugin');
>   }
> 
>   return async function transformer(tree: Root) {
>     console.log('\n🚀 Remark ASF Plugin: Starting transformation...\n');
>     console.log('Processing markdown file:', options.markdownFile);
>     
>     try {
>       // Convert tree to markdown string
>       const markdown = toMarkdown(tree);
>       
>       // Process the content through the unified pipeline
>       const result = await unified()
>         .use(remarkParse)
>         .use(remarkRehype)
>         .use(rehypeAstro, { markdownFile: options.markdownFile })
>         .process(markdown);
>       
>       if (!result) {
>         throw new Error('Failed to process content');
>       }
>       
>       return result.value;
>     } catch (error) {
>       console.error('Error in remarkAsf transformation:', error);
>       return tree; // Return original tree if transformation fails
>     }
>   }
> }

Managed to stumble on a workaround after some frustration: 

```typescript
import { unified } from 'unified'
import remarkParse from 'remark-parse'
import remarkRehype from 'remark-rehype'
import type { Root } from 'mdast'
import type { Plugin } from 'unified'
import { toMarkdown } from 'mdast-util-to-markdown'


const rehypeAstro: (options: { markdownFile: string }) => (tree: Root) => Root = (options) => (tree) => {
  return rehypeAstro({ markdownFile: options.markdownFile })(tree);
};

interface RemarkAsfOptions {
  markdownFile: string;
}

/**
 * Plugin to process Astro Special Format content
 * Converts markdown content to HTML with enhanced Astro features
 */
export default function remarkAsf(options?: RemarkAsfOptions): Plugin<[], Root, Root> {
  if (!options?.markdownFile) {
    throw new Error('markdownFile is required for remarkAsf plugin');
  }

  return function () {
    return async function (tree: Root): Promise<Root> {
      console.log('\n🚀 Remark ASF Plugin: Starting transformation...\n');
      console.log('Processing markdown file:', options.markdownFile);
      
      try {
        // Convert tree to markdown string
        const markdown = toMarkdown(tree);
        
        // Process the content through the unified pipeline
        const result = await unified()
          .use(remarkParse)
          .use(remarkRehype)
          .use(rehypeAstro, { markdownFile: options.markdownFile })
          .process(markdown);
        
        if (!result) {
          throw new Error('Failed to process content');
        }
        
        // Create a new Root node with the processed content
        return {
          type: 'root',
          children: [{
            type: 'text',
            value: result.value.toString()
          }]
        } as Root;
      } catch (error) {
        console.error('Error in remarkAsf transformation:', error);
        return tree; // Return original tree if transformation fails
      }
    }
  }
}
```
