### ISSUE TITLE
Curly quotes not rendered properly using `.md`

### ISSUE THREAD

**Issue by gsong** [withastro/astro#8457]
### Astro Info

```block
Astro                    v3.0.10
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Happens in Chrome and Firefox, but not in Safari

### Describe the Bug

Original `.md`:

```md
# My First Blog Post “”‘’
```

What's rendered in Chrome:

```
My First Blog Post â€œâ€â€˜â€™
```

### What's the expected result?

For this header to be rendered:

```
My First Blog Post “”‘’
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gnydz2?file=src/pages/test.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You need to wrap the page in a layout with `<meta charset="utf-8" />` for the encoding to be properly set. This is not an Astro bug, just how HTML works 😄

**Comment by gsong** [comment]
@Princesseuh Thank you for the quick response.

What you said makes sense. I would say it might be worth calling out in the tutorial that the issued is addressed later in the nested layout section. It was a puzzling experience for me, as I didn't know how to supply `.md` routes with a layout at that stage of the tutorial.

**Comment by Princesseuh** [comment]
Thanks, I've forwarded this feedback to our docs team 😄
