### ISSUE TITLE
Cannot find module 'astro/types'

### ISSUE THREAD

**Issue by karlosos** [withastro/astro#8471]
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.17.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

After a fresh install with the default blog template, there is a problem with TypeScript in `src/components/HeaderLink.astro` 

> Cannot find module 'astro/types'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

![image](https://github.com/withastro/astro/assets/3882385/b190e039-1dc4-4484-ac7d-90bb9efbc6d6)

I have started astro project with those options:

```
  npm create astro@latest

╭─────╮  Houston:
│ ◠ ◡ ◠  Time to build a sweet new website.
╰─────╯

 astro   v3.0.12 Launch sequence initiated.

   dir   Where should we create your new project?
         ./former-filament

  tmpl   How would you like to start your new project?
         Use blog template
      ✔  Template copied

  deps   Install dependencies?
         Yes
      ✔  Dependencies installed

    ts   Do you plan to write TypeScript?
         Yes

   use   How strict should TypeScript be?
         Relaxed
      ✔  TypeScript customized

   git   Initialize a new git repository?
         Yes
      ✔  Git initialized

  next   Liftoff confirmed. Explore your project!

         Enter your project directory using cd ./former-filament 
         Run npm run dev to start the dev server. CTRL+C to stop.
         Add frameworks like react or tailwind using astro add.

         Stuck? Join us at https://astro.build/chat

╭─────╮  Houston:
│ ◠ ◡ ◠  Good luck out there, astronaut! 🚀
╰─────╯
```

I am wondering if this is a problem on my side. Tried restarting the VSCode. It looks like VSCode is not recognizing TypeScript.

![image](https://github.com/withastro/astro/assets/3882385/5418a7ef-0d71-461c-8e4a-2543c6e8d65a)

### What's the expected result?

I'd expect no problems in VSCode on fresh installation. 

### Link to Minimal Reproducible Example

https://astro.new/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your version of TypeScript is outdated. Astro 3 requires TypeScript 5. See https://docs.astro.build/en/guides/upgrade-to/v3/#removed-support-for-typescript-4 for more information.
