### ISSUE TITLE
Error when evaluating SSR module

### ISSUE THREAD

**Issue by NikolaRHristov** [withastro/astro#8473]
### Astro Info

```block
Astro                    v3.0.10
Node                     v20.6.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
                         @astrojs/sitemap
                         astro-critters
                         @astrojs/prefetch
                         astro-rome
                         astro-compress
```

### Describe the Bug

Recently emerged:

[vite] Error when evaluating SSR module Website\astro.config.ts: failed to import "@astrojs/sitemap"
|- TypeError: Cannot set property SitemapItemStream of #<Object> which has only a getter
    at Object.<anonymous> (node_modules\.pnpm\sitemap@7.1.1\node_modules\sitemap\dist\index.js:13:537)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (node_modules\.pnpm\sitemap@7.1.1\node_modules\sitemap\dist\lib\sitemap-simple.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

[astro] Unable to load your Astro config

### What's the expected result?

Run `npm run start`

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by stereobooster** [comment]
Do you see something like this

```
[content] index.md must be nested in a collection directory. Skipping.
```

In my case `index.md` was inside `src/content/` all fixed when I moved it in subfolder (`src/content/docs` in my case)

**Comment by NikolaRHristov** [comment]
No, I don't have content collections. I'll provide a minimal example shortly.

**Comment by castarco** [comment]
I'm having a similar problem, it appears also when running astro build for static sites.

It doesn't seem to have any relation to SSR, but to the sitemap code; when I disable the sitemap plugin, it works flawlessly.

More interestingly, I thought that it was because I updated some dependency... but I reverted back to what I had in my outdated main branch... and somehow it got broken too (without package updates), even when that worked a couple of months ago.

**Comment by NikolaRHristov** [comment]
When I disable `@astrojs/sitemap` it works.

**Comment by Herover** [comment]
I have the same problem, it appears to be a problem when running NodeJS v20, downgrading NodeJS from version 20 to version 19 seems to fix this.

**Comment by castarco** [comment]
@Herover You are right, partially. I just checked, and it works well with Node 20.3.1, but not with Node 20.6.0 .

**Comment by NikolaRHristov** [comment]
Can confirm this happened after an upgrade to Node v20.6.0

**Comment by castarco** [comment]
I just checked, and there is a new release (v20.6.1: https://github.com/nodejs/node/releases/tag/v20.6.1) that fixes the problem 🎉

**Comment by NikolaRHristov** [comment]
Can confirm.

> I just checked, and there is a new release (v20.6.1: https://github.com/nodejs/node/releases/tag/v20.6.1) that fixes the problem 🎉
