### ISSUE TITLE
Astro is unable to use the `bun:sqlite` package.

### ISSUE THREAD

**Issue by homelyseven250** [withastro/astro#8476]
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.17.0
System                   macOS (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Astro is unable to use the `bun:sqlite` package.
Error:
```
george@Georges-MacBook-Pro words % bun run dev
$ astro dev
  🚀  astro  v3.0.12 started in 97ms
  
  ┃ Local    http://localhost:4321/
  ┃ Network  use --host to expose
  
Error: The following dependencies are imported but could not be resolved:

  bun:sqlite (imported by /Users/george/Desktop/code/cabbage/words/src/util/db.ts)

Are they installed?
    at file:///Users/george/Desktop/code/cabbage/words/node_modules/vite/dist/node/chunks/dep-df561101.js:45705:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/george/Desktop/code/cabbage/words/node_modules/vite/dist/node/chunks/dep-df561101.js:45114:38
^C
```

### What's the expected result?

The `bun:sqlite` can be imported and used.

### Link to Minimal Reproducible Example

https://github.com/homelyseven250/astro-bun-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Astro is a Node framework. If something specific to another runtime doesn't work, not only I don't know what we could do about it, but also, it's unrelated to us.

**Comment by Jarred-Sumner** [comment]
I hate saying this but

This appears to be a bug in Astro. 

Astro's module resolution prevents bun internal modules from being used. Astro resolves modules before Bun's module resolution runs. Bun cannot fix this without overriding Astro's module resolution altogether, which would break Astro on Bun in other ways and is generally not something you want.

**Comment by andrioid** [comment]
I just tried @Jarred-Sumner's suggestion, without luck. And yes @Princesseuh, I would assume this affects any Vite SSR app.

I couldn't even get the dev-server running without adding "bun:sqlite" to the `vite.optimizeDeps.exclude` configuration option. Nothing seems to help with accessing the `bun:sqlite` in SSR though. I've tried "external", disabling "optimizeDeps", etc.

Will tinker further...

**Comment by fabriziogiordano** [comment]
It appears the Vite use case is handled by Bun.

By adding `--bun`: The --bun flag tells Bun to run Vite's CLI using bun instead of node.

```
bun --bun run astro build
```

Here the info from the doc: https://bun.sh/guides/ecosystem/vite

**Comment by bluwy** [comment]
Feel free to open an issue in Vite regarding this. I think that line should indeed fix it, but Vite probably needs a more standardized flow internally for handling different runtime builtin protocols.
