### ISSUE TITLE
Modifying response via middleware breaks built-in 'Image' component on dev server

### ISSUE THREAD

**Issue by noelforte** [withastro/astro#8477]
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Not browser related

### Describe the Bug

When running `astro dev` with active middleware via a `middleware/index.js`/`middleware.js` file, the dev server does not properly render the image when using the `<Image />` component. This behavior is not exhibited when building for production.

In my minimally reproducible example, I'm using the same `onRequest` function [as shown in the documentation](https://docs.astro.build/en/guides/middleware/#example-redacting-sensitive-information). I'm returning an unmodified response to eliminate the possibility of their being glitches in the transformation of the response:

```js
export const onRequest = async (context, next) => {
  const response = await next();
  const html = await response.text();

  // Verify the middleware is being executed
  console.log('Request Recieved!');

  return new Response(html, {
    status: 200,
    headers: response.headers,
  });
};
```

Note that this issue persists across browsers:

<img width="400" alt="Screenshot 2023-09-09 at 2 07 49 PM" src="https://github.com/withastro/astro/assets/2560683/6d46fe7e-f7e8-4bb4-99c5-e38a3589828d">

<img width="400" alt="Screenshot 2023-09-09 at 2 08 39 PM" src="https://github.com/withastro/astro/assets/2560683/b08e9b5c-a890-4124-8c07-738c9c435ebe">

Disabling the middleware by either commenting out the `onRequest` function, moving the `middleware.js` file outside of the `src` folder, or renaming the `onRequest` function to something other than `onRequest` restores the expected functionality.

<img width="400" alt="Screenshot 2023-09-09 at 2 07 27 PM" src="https://github.com/withastro/astro/assets/2560683/1cfeb893-36f2-4e29-83f6-8900734f5f67">
<img width="400" alt="Screenshot 2023-09-09 at 2 09 02 PM" src="https://github.com/withastro/astro/assets/2560683/50f669f4-5592-4c85-9ee9-157a94810daf">

### What's the expected result?

Using middleware when running `astro dev` should not have an impact on the rendering of the `Image` component, since ideally the response being modified is only affecting the HTML and not anything related to image processing, unless of course the dev server is passing the image requests through the middleware and something is being mangled.

### Link to Minimal Reproducible Example

https://github.com/noelforte/astro-middleware-rtc

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
> The dev server is passing the image requests through the middleware and something is being mangled.

This is in fact, what it does 😄 The optimized images in dev and SSR are passed through an endpoint, so middleware affects it. You can check for the url not being `_image` before modifying the request.
