### ISSUE TITLE
Using getImage and glob import doesn't look to work

### ISSUE THREAD

**Issue by Adam-Collier** [withastro/astro#8478]
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             unocss
                         @astrojs/svelte
                         @astrojs/react
                         @astrojs/partytown
```

### Describe the Bug

Hey guys, I was just updating to Astro 3 and thought I'd do some image optimisations whilst I'm at it. Unfortunately, it looks like when I glob import some images files, loop through them and try and optimise them using the `getImage` function no optimisation occurs!

I wanted to create a repro on Stackblitz but it wasn't allowing me to upload some images, hopefully the below code will suffice to show how I was approaching it:

```
const imagesGlob = import.meta.glob('../../assets/photos/03-2023-Europe/*', {
  as: 'url',
  eager: true,
})

const imagesArr: string[] = Object.values(imagesGlob)

// loop through the imagesArr and create an array of Image components
const images = await Promise.all(
  imagesArr.map(
    async (image) => await getImage({ src: image, width: 200, height: 200 }),
  ),
)
```

### What's the expected result?

I expect that the globbed images would be optimised and then I can render them to the page

### Link to Minimal Reproducible Example

I couldn't upload images :'(

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
The `as: 'url'` is causing you to import strings instead of the proper value.
