### ISSUE TITLE
minio-js constructor causes astro to throw 500

### ISSUE THREAD

**Issue by DrDrei** [withastro/astro#8479]
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.17.1
System                   macOS (x64)
Package Manager          yarn
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

While using [minio-js](https://github.com/minio/minio-js) library, Astro unexpectedly fails to serve the page when running in `preview` mode or via `node ./dist/server/entry.mjs`. 
`astro dev` works as you'd expect.

Console error: `Failed to load resource: the server responded with a status of 500 ()`
Network Tab doesn't provide any useful information about the failure. 
Nothing is logged to the server.

Steps to reproduce: 
- `yarn create astro` > Empty project
- `yarn astro add node`
- `yarn add minio`
- add the [basic example](https://github.com/minio/minio-js#initialize-minio-client) to the Component Script of `index.astro`:
```javascript
import Minio from 'minio'

var minioClient = new Minio.Client({
  endPoint: 'play.min.io',
  port: 9000,
  useSSL: true,
  accessKey: 'Q3AM3UQ867SPQQA43P2F',
  secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
})
```
- `build`
- `preview`
- Astro fails to load the page with above error.

### What's the expected result?

Expectation is for Astro to work just like the `dev` command.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hl7ssy?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This package is not compatible with Node ESM as written, this works:

```js
import * as Minio from 'minio'
```

**Comment by DrDrei** [comment]
Thanks @matthewp! That helps a lot.
