### ISSUE TITLE
Build gets stuck when using Bun

### ISSUE THREAD

**Issue by marcinjahn** [withastro/astro#8483]
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.17.0
System                   Linux (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             auto-import
                         @astrojs/asides
                         @astrojs/code-snippets
                         @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/partytown


+ Bun 1.0
```

### Describe the Bug

Building my Astro app ([repo link](https://github.com/marcinjahn/technology-notebook)) with Bun gets stuck on non-recognized "log" script:

```sh
❯ bun run build
$ astro build
10:11:04 AM [content] Types generated 425ms
10:11:04 AM [build] output target: static
10:11:04 AM [build] Collecting build info...
10:11:04 AM [build] Completed in 442ms.
10:11:04 AM [build] Building static entrypoints...
The language "cshtml" doesn't exist, falling back to plaintext.
The language "log" doesn't exist, falling back to plaintext.
The language "protobuf" doesn't exist, falling back to plaintext.
The language "protobuf" doesn't exist, falling back to plaintext.
The language "sol" doesn't exist, falling back to plaintext.
The language "log" doesn't exist, falling back to plaintext.
```

I gave it a few minutes or so, it never progresses.

Running `npm run build` builds the whole website in less than a minute.

`bun run dev` runs well.

### What's the expected result?

Bun should be able to build the project, just like npm does.

I wasn't sure if this issue should be reported here, or at Bun's repo, but the [docs](https://docs.astro.build/en/recipes/bun/) link here, so here I am.

### Link to Minimal Reproducible Example

https://github.com/marcinjahn/technology-notebook

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
I would suggest raising this issue with the Bun team. Astro is a Node framework and we do not officially advertise any kind of Bun support.

**Comment by marcinjahn** [comment]
Then, the documentation is a bit misleading right now. Here's my take at fixing it https://github.com/withastro/docs/pull/4625
