### ISSUE TITLE
Sharp error

### ISSUE THREAD

**Issue by kacperwyczawski** [withastro/astro#8489]
### Astro Info

```block
Astro                    v3.0.12
Node                     v20.6.0
System                   Linux (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/prefetch
```

### Describe the Bug

I get `Server Error: MissingSharp: Could not find Sharp. Please install Sharp ('sharp') manually into your project or migrate to another image service.`, despite having sharp installed.

Here is the output from `bun pm ls`:
```sh
$ bun pm ls
<projectPath> node_modules (834)
├── @astrojs/prefetch@0.4.0
├── @astrojs/tailwind@5.0.0
├── @fontsource-variable/fira-code@5.0.8
├── @fontsource-variable/inter@5.0.8
├── @fontsource-variable/sora@5.0.8
├── astro@3.0.12
├── sharp@0.32.5
└── tailwindcss@3.3.3
```

And here is the request that fails:
```http
GET http://localhost:4321/_image?href=/@fs/<projectPath>/src/images/<imageName>.png?origWidth=1920&origHeight=1080&origFormat=png&f=webp
```

I am using `<Image />` component from `astro:assets`.

### What's the expected result?

Images should just work.

### Link to Minimal Reproducible Example

I don't know if it's possible to create bun project in stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is a Bun issue unrelated to Astro. It seems like Sharp doesn't support Bun really well yet, or the reverse. Not sure. Either way, it's unrelated to us specifically (we use Sharp normally, case in point being that it works on npm, yarn and pnpm). I'd recommend checking the Bun and Sharp repos for issues related to this, there seems to be a few already.
