### ISSUE TITLE
generated redirect pages are not compressed when `compressHTML=true`

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#8493]
### Astro Info

```block
Astro version            v2.10.15
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  astro-sst/edge
Integrations             @y_nk/cached-fetch, @astrojs/tailwind, @astrojs/react, @astrojs/sitemap
```

### Describe the Bug

When building static pages, the pages are properly compressed but not the static redirected pages.

<img width="559" alt="image" src="https://github.com/withastro/astro/assets/411625/fd219988-1b8f-40ff-9f22-76adbdd44a6e">

### What's the expected result?

html should be compressed

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-aebx5j

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
It would be great to split this list into four different issues, here's why:
- we can triage them singularly;
- we can close them singularly and progressively release the patches;
- we can assign the bugs to different people at the same time;

**Comment by y-nk** [comment]
@ematipico i understand what you mean. i grouped them because it made sense since they're all the same chunk of feature and relatively small things to fix.

but nevermind, i splitted them with this one and #8498 #8499 #8500

**Comment by ematipico** [comment]
Thank you @y-nk , that's really appreciated! ❤️

**Comment by y-nk** [comment]
@ematipico in the meantime since i _really_ need this fast, i'm probably gonna end up with an integration. if you feel like an integration could be a better path for this feature (rather than in core), i'm happy to release it afterwards and relieve the core from this feat.

**Comment by Princesseuh** [comment]
The compiler doesn't run on those pages at all, the template is just a random string: https://github.com/withastro/astro/blob/435b10549878281ad2bb60207cb86f312a4a809f/packages/astro/src/core/build/generate.ts#L579

**Comment by y-nk** [comment]
i'm thinking the whole feature could be handled in userland with a single `[...redirect].astro` + `getStaticPaths` and `prerender = true`. it would follow the same pipeline as the compiler and let user to handle canonical and other features i listed as bug.

i've tested that a `[...redirect].astro` can live next to another dynamic path route as long as generated paths don't collide. it looks better this way imho.
