### ISSUE TITLE
APIRoute POST not working

### ISSUE THREAD

**Issue by Liliandev** [withastro/astro#8495]
### Astro Info

```block
✅ I am using the latest version of Astro and all plugins.
✅ I am using a version of Node that Astro supports (>=18.14.1)
```

### Describe the Bug

I have the following directory tree : 

![image](https://github.com/withastro/astro/assets/4364899/9edb0612-0ec0-47bc-ae9a-0153f4d4dfa4)

contact.ts is implemented as followed : 

![image](https://github.com/withastro/astro/assets/4364899/41207374-16b0-43b4-96d9-5ac7a3cf0d90)

When i try to send a POST request, the json returned is for the GET and not for the POST method.

### What's the expected result?

POST response shoud be returned.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Liliandev** [comment]
Minimal reproduction Link : https://stackblitz.com/edit/github-lkrn6f?file=src%2Fpages%2Fapi%2Fcontact.ts

**Comment by ematipico** [comment]
@Liliandev I tried your reproduction, but the submit button doesn't work... I don't see any log unfortuantely

**Comment by Liliandev** [comment]
It seems export const prerender = false missing and was source of trouble

Thanks for your help

**Comment by Liliandev** [comment]
It seems export const prerender = false missing and was source of trouble

Thanks for your help
