### ISSUE TITLE
redirect page type icon not properly displayed

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#8498]
### Astro Info

```block
Astro version            v2.10.15
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  astro-sst/edge
Integrations             @y_nk/cached-fetch, @astrojs/tailwind, @astrojs/react, @astrojs/sitemap
```

### Describe the Bug

redirected page build shown as lambda (even tho it's not)

<img width="199" alt="image" src="https://github.com/withastro/astro/assets/411625/72781a6b-109d-491d-bd53-ba03eb501733">

### What's the expected result?

it should be shown as a static built page

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-aebx5j

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Good first issue!

[This line](https://github.com/withastro/astro/blob/astro@3.1.0/packages/astro/src/core/build/generate.ts#L300) was written when we only had pages and endpoints, but `pageData.route.type` can now also be "redirect".
