### ISSUE TITLE
server code contains useless code (bad treeshake)

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#8503]
### Astro Info

```block
❯ npx astro info
Astro                    v3.0.12
Node                     v16.20.0
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### Describe the Bug

installing react integration will force inject react rendering code on the server side even if it's not used (either all react is ssg'ed or client-only is strictly used).

this increases the bundle size of the server, which can be critical when deploying on aws lambda@edge.

<img width="848" alt="image" src="https://github.com/withastro/astro/assets/411625/28935925-4381-469d-b1a3-7dc6bb14d7f6">

### What's the expected result?

server side code should only contain what's necessary according to usage.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-hygumw?file=src/pages/index.astro,src/pages/foo.js,astro.config.mjs,src/pages/_Foo.jsx,dist/server/renderers.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Yeah ideally it would be removed in certain scenarios but architecturally it cannot be. Astro builds the code only once before pages are generated, so at build time it is not away that you only use it for client components or that you only use it on prerendered pages.

So going to close as there's nothing we can do to change this.
