### ISSUE TITLE
Prerendered endpoints are returning undefined in SSR prod mode

### ISSUE THREAD

**Issue by minht11** [withastro/astro#8513]
### Astro Info

```block
Astro                    v3.0.12
Node                     v16.20.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

Calling prerendered Astro endpoints during SSR is not working in production. The whole example can be found in Astro [call-endpoints recipe](https://docs.astro.build/en/recipes/call-endpoints/)

In given reproduction link run:
```bash
npm run build
npm run preview
```
Observe error, which is not present in dev mode

### What's the expected result?

Using prerendered API endpoint works as expected.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-huqjmk?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
The intent of `prerender` is to prevent the route from being included in the build, which is what happens here. If you want to share logic between an endpoint and a page I recommend moving that code to somewhere outside of the pages folder and calling them each from there.

**Comment by minht11** [comment]
My use case specifically for trying this was fetching data in my Layout, but because of node fetch [socket bug](https://github.com/nodejs/node/issues/47130) it fails a lot of the time. I can't just prerender or migrate fetching to top level because I have a lot of pages, so I just basically wanted to prerender endpoint and always use static data from there.

Steping back this working in DEV and failing in production without  a warning is confusing.

Second what is the deference in principle between prerendered API endpoint and SSR endpoint conceptually? They both do work from the outside, however using  prerendered endpoint inside SSRed Astro page breaks as described here in this issue. If both, endpoint and page are prerendered it works. These inconsistencies do complicate things, because now you have to know what type is target page is it SSR is it prerendered, what type is your endpoint. Now sometimes it doesn't work, so you have to dublicate code, change your structure and so on.

I am dissapointed to hear this is not valid use case, but then at very least different behaviors between prerender/SSR should be noted in the documentation,  even better would be to be consistent behavior in DEV/PROD modes. Thank you in anycase.
