### ISSUE TITLE
Type error when passing Astro object to APIRoute 

### ISSUE THREAD

**Issue by minht11** [withastro/astro#8514]
### Astro Info

```block
Astro                    v3.0.12
Node                     v16.20.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

Calling endpoint in the server and passing Astro object to APIRoute produces error
```ts
Argument of type 'Readonly<AstroGlobal<Record<string, any>, AstroComponentFactory, Record<string, string | undefined>>>' is not assignable to parameter of type 'APIContext<Record<string, any>, Record<string, string | undefined>>'.
  Property 'ResponseWithEncoding' is missing in type 'Readonly<AstroGlobal<Record<string, any>, AstroComponentFactory, Record<string, string | undefined>>>' but required in type 'APIContext<Record<string, any>, Record<string, string | undefined>>'.
```
whole example can be found in Astro [call-endpoints recipe](https://docs.astro.build/en/recipes/call-endpoints/

This is regression with Astro 3.0, 2.10 did not have this issue.
<img width="826" alt="image" src="https://github.com/withastro/astro/assets/8914032/bc1e94fc-5066-4e72-96ba-24bba8413d78">

### What's the expected result?

No type error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-huqjmk?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Is there a problem that's missing or not expected? That TS error isn't the greatest to read.

**Comment by Princesseuh** [comment]
The type is hard to read because of the many generics that are unfortunately needed for editor tooling, but I think the error is simply that APIContext has a ResponseWithEncoding property that the Astro global doesn't have

**Comment by matthewp** [comment]
Ah ok, we can probably add that.

**Comment by ematipico** [comment]
Is it a correct usage of the route endpoints?

**Comment by matthewp** [comment]
Yeah, after discussing this with some others, I'm not sure that we want to make it a breaking change if the API endpoint context types are unaligned with the Astro global. We do want to make them aligned when possible, but it shouldn't be a breaking change when they are not.

**Comment by zelenovsky** [comment]
I have the same issue. How to fix it?

**Comment by antheath** [comment]
@matthewp Is there a workaround to this issue? Do we need to downgrade to use API endpoints? This appears to be a breaking change.

**Comment by EddyVinck** [comment]
I "fixed" it by doing this:

```ts
let response = await GET({
  ...Astro,
  ResponseWithEncoding: Response,
  params: {
    id: post.data.id,
  },
});
```

But I am still getting an error when trying to do `response.json()` like the docs show:

```
Property 'json' does not exist on type 'EndpointOutput | Response'.
  Property 'json' does not exist on type '{ body: string; encoding?: BufferEncoding; }'
```

<img width="1090" alt="image" src="https://github.com/withastro/astro/assets/23434753/4ed27580-2113-4fe1-89bf-5a06851637b1">

**Comment by luiguild** [comment]
Still having this type problem.

The error message:
```
src/pages/[placeLang].astro:17:47 - error ts(2345): Argument of type 'Readonly<AstroGlobal<never, (_props: never) => any, Params>>' is not assignable to parameter of type 'APIContext<Record<string, any>, Record<string, string | undefined>>'.
  Types of property 'params' are incompatible.
```

The code:
```
const place: Place = await GET(Astro);
```

package.json
```
"dependencies": {
    "@astrojs/check": "^0.3.1",
    "@astrojs/vue": "^4.0.2",
    "astro": "^4.0.3",
    "typescript": "^5.3.2",
    "vue": "^3.2.30",
    "vue-i18n": "9"
  },
```
