### ISSUE TITLE
url encoded dynamic params not properly handled

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#8516]
### Astro Info

```block
~/projects/withastro-astro-vzlytn
❯ npx astro info
Astro                    v3.0.12
Node                     v16.20.0
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

i've a url such as `/%5Bpage%5D` coming from a 3rd party place, but handling this valid url in `getStaticPaths` breaks the build.

```tsx
---
export function getStaticPaths() {
  return [{
    params: { path: undefined },
    props: {}
  }, {
    params: { path: '%5Bpage%5D' }, // ← minimal repro
    props: {}
  }]
}
---

<ul>
  <li>hello world</li>
  <li>
    <a href="/%5Bpage%5D">url encoded (should work)</a>
  </li>
  <li>
    <a href="/[page]">url decoded (should not work)</a>
  </li>
</ul>
```

Error log:
```
 prerendering static routes 
▶ src/pages/[...path].astro
  ├─ index.html (+7ms)
 error   A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/%5Bpage%5D`.
  Hint:
    Possible dynamic routes being matched: src/pages/[...path].astro.
  Error reference:
    https://docs.astro.build/en/reference/errors/no-matching-static-path-found/
  File:
    /home/projects/withastro-astro-vzlytn/node_modules/astro/dist/core/errors/errors.js:36:5
  Code:
    35 |   setFrame(source, location) {
    > 36 |     this.frame = codeFrame(source, location);
         |     ^
      37 |   }
      38 |   static is(err) {
      39 |     return err.type === "AstroError";
```

### What's the expected result?

it should not matter what chars are in a dynamic param as long as it computes to a valid url, and this one seems to be valid according to `new URL('https://example.com/%5Bpage%5D')`.

<img width="299" alt="image" src="https://github.com/withastro/astro/assets/411625/f535aa9c-a1ca-4a38-ad92-fd51c5fcb205">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-vzlytn?file=src/pages/%5B...path%5D.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by rsk700** [comment]
Have similar issue, maybe related: was trying to upgrade to Astro v3 from v2, I'm generating pages with `getStaticPaths`.

In Astro v3 the issue I have is it works in production build, on start it works in dev instance, it works on reloads, but if I start navigating website with urls I've got `not found` for dynamic routes, and error in console says:

```
02:17:13 PM [getStaticPaths] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/en/download`.

Possible dynamic routes being matched: src/pages/[lang]/download.astro.
02:17:13 PM [serve]    404                             /en/download

```

**Comment by spokospace** [comment]
i have the same issue with static page after upgrade to Astro 3. Now I have files like category/subcategory.html instead of category/subcategory/index.html

**Comment by yaronovsky** [comment]
Similar issue with ssr in middleware mode, urls with special characters and dynamic url blog/{special characters},
I have an astro middleware and the request is skipped directly to 404

**Comment by y-nk** [comment]
🤞

**Comment by castarco** [comment]
I might be suffering from this same problem. I left a question in the Discord server... but I'm fearing that my problem is due to a bug and not because of anything wrong I did:

https://discord.com/channels/830184174198718474/1210365120832737310

**Comment by brokeboiflex** [comment]
![8j5nlz](https://github.com/withastro/astro/assets/50945071/69f2ac5e-e8bd-40dd-a158-bb852948879d)

**Comment by ematipico** [comment]
I am not really sure there's a fix for that. We do decode params because we run them against our route pattern. The route pattern expects a decoded path (the one you're providing via `params`) because the path could contain non-English characters. 

If we decided to **NOT** decode params, we could break other users's code.

**Comment by matthewp** [comment]
| example  | param                                | filename            | works in dev | built in ssg |
|----------|--------------------------------------|---------------------|--------------|--------------|
| のツール | %E3%81%AE%E3%83%84%E3%83%BC%E3%83%AB | のツール/index.html | yes          | yes          |
| のツール | のツール                             | ?                   | ?            | no           |
| [page]   | %5Bpage%5D                           | ?                   | ?            | ?            |
| [page]   | [page]                               | ?                   | ?            | ?            |

**Comment by ematipico** [comment]
https://stackblitz.com/edit/withastro-astro-21gk4v?file=src%2Fpages%2F[...path].astro

**Comment by brokeboiflex** [comment]
> I am not really sure there's a fix for that. We do decode params because we run them against our route pattern. The route pattern expects a decoded path (the one you're providing via `params`) because the path could contain non-English characters.
> 
> If we decided to **NOT** decode params, we could break other users's code.

Can't you just make it optional from config?

**Comment by ematipico** [comment]
@brokeboiflex 
I'm not sure what kind of options you're suggesting, but as you can see from https://github.com/withastro/astro/issues/8516#issuecomment-1999712725, we don't even get right possible non-english URLs.

We have to fix the correct expectations first.

**Comment by brokeboiflex** [comment]
@ematipico 
I dunno, like an option to not decode params or to support a custom route pattern.
I'm not saying I know your code better than you, I'm just saying that inability to use non english URLs may be a deal breaker for a lot of non english web devs, it certainly almost was for me but I've just worked around it by ditching the non english characters

It's dumb af but it gets the job done.
Maybe it'll help somebody

```javascript
export async function getStaticPaths() {
  const products = menuSections.flatMap((category) =>
    category.products.map((product) => ({
      categoryName: category.categoryName,
      productName: product.productName,
      productImg: product.productImg,
      productPrice: product.productPrice,
      productDescription: product.productDescription || '',
      variants: product.variants || [],
      sizes: product.sizes || [],
    }))
  )

  return products.map((item) => ({
      params: {
        item: 
          item.productName
            .toLowerCase()
            .replaceAll(' ', '-')
            .replaceAll('ą', 'a')
            .replaceAll('ć', 'c')
            .replaceAll('ę', 'e')
            .replaceAll('ł', 'l')
            .replaceAll('ń', 'n')
            .replaceAll('ó', 'o')
            .replaceAll('ż', 'z')
            .replaceAll('ź', 'z')
      },
      props: { item }, 
  }))
}
```

**Comment by y-nk** [comment]
@ematipico

> We do decode params because we run them against our route pattern. The route pattern expects a decoded path (the one you're providing via params) because the path could contain non-English characters.
> 
> If we decided to NOT decode params, we could break other users's code.

but then the decoded param won't match input given at `getStaticPaths` which isn't url encoded. i'm thinking maybe the right move (for this bug and non-english urls) should be not to decode the param _for path matching only_, so that internal routing would work fine. i guess that providing url decoded params _after_ makes sense as the framework could claim making a pass of sanitization.

**Comment by ascorbic** [comment]
I think the fix would be to change `decodeURIComponent` [here](https://github.com/withastro/astro/blob/devalue/packages/astro/src/core/render/params-and-props.ts#L74) to `decodeURI`. This would be a breaking change though, so will need to wait til Astro 5. In the meantime a workaround would be to double-encode the params.

**Comment by ematipico** [comment]
We are going to tackle this in Astro v5.0. It's possible there are going to be some breaking changes, but we want to make sure that we have a predictable encoding/decoding strategy.

We will follow up with some documentation too.

**Comment by y-nk** [comment]
@ematipico it's greatly appreciated that this issue is not left in the limbos of the great backlog. thanks a lot for the update.

**Comment by ematipico** [comment]
Fixed in https://github.com/withastro/astro/pull/12079
