### ISSUE TITLE
Setting "nodejs_compat" for Cloudflare SSR API?

### ISSUE THREAD

**Issue by kelvinz** [withastro/astro#8520]
### Astro Info

```block
Astro                    v3.0.10
Node                     v20.5.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

Hi guys, I'm running an API endpoint using the Cloudflare adaptor.
But I require the use of Buffer and hit the Buffer is not defined error.
I found that in Cloudflare documentation that I can run `compatibility_flags = [ "nodejs_compat" ]` and import Buffer this way `import { Buffer } from 'node:buffer'`, but I am unable to use this and build properly using Astro.
What am I missing or need to get this to work?

### What's the expected result?

To be able to build and push to Cloudflare.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5nhtag?file=src%2Fpages%2Fapi%2Fgenerate.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
That is a wrangler flag, so it should work regardless. I'll check your example.

**Comment by kelvinz** [comment]
When I tried building it says `Could not resolve "node:buffer"`, I think because I am simply using the Cloudflare adaptor to run my api page, instead of building a functions folder, the `compatibility_flags = [ "nodejs_compat" ]` is not used?
If I npm install a buffer package it packs it up, but when pushed and tested live, there's issues with the buffer function.

**Comment by alexanderniebuhr** [comment]
`compatibility_flags = [ "nodejs_compat" ]` should be a runtime flag & not used while building. Can you update your example, so the api endpoint has actual code, using the Buffer. Can be dummy data.. I need to clone it and try myself.

**Comment by kelvinz** [comment]
I can't seem to find a free api that returns base64 for me to add into the example. =(
[Cloudflare Docs](https://developers.cloudflare.com/workers/runtime-apis/nodejs/)
But this is the docs from Cloudflare that says Buffer is not support by default, and compat and `import { Buffer } from 'node:buffer'` is the way to activate it. But I think right now there is no way to activate that in Astro?

**Comment by alexanderniebuhr** [comment]
I'm pretty sure there is, but we need to have an example. Can you just use dummy data + buffer.

**Comment by kelvinz** [comment]
Okay! Give me awhile, let me try to update the example~ Thank you in advance for checking this out. =)

**Comment by alexanderniebuhr** [comment]
No problem, I can deploy it to my own cf acc

**Comment by lilnasy** [comment]
@kelvinz Your reproduction project is set to hybrid, which means "node:buffer" gets used during build time. Cloudflare's node compat does not get involved.

**Comment by lilnasy** [comment]
I would recommend opening a support thread on our discord if you want help confirming the issue.

https://astro.build/chat

**Comment by kelvinz** [comment]
Doesn't `export const prerender = false` tag in my api file make it run on server code? But yea, I've also got a thread on the discord server, should I close this here and continue there?

**Comment by alexanderniebuhr** [comment]
I would continue in Discord for now, but keep this open for a short time. If we find out it is an issue, we can continue here, but if we find out this is an upstream problem with Cloudflare, we would close this issue.

**Comment by alexanderniebuhr** [comment]
@lilnasy was able to reproduce...

**Comment by alexanderniebuhr** [comment]
fixed by https://github.com/withastro/astro/pull/8595
