### ISSUE TITLE
Vercel AI SDK does not stream response in production

### ISSUE THREAD

**Issue by brentreilly** [withastro/astro#8521]
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          yarn
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/vue
```

### Describe the Bug

Streaming using [Vercel's AI SDK](https://sdk.vercel.ai/docs) works in dev but not when deployed to a Vercel project in production.

### What's the expected result?

API streams chat completions in real time as expected.

### Link to Minimal Reproducible Example

https://github.com/reillybuilt/vercel-ai-stream

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
It's very unlikely this has anything to do with Astro, but is probably an environmental issue. We can't debug this issue for you, but if you're able to do so and find that there is a more specific problem with Astro, that can be demostrated without using a specific library, please file a new issue about that. Thanks.
