### ISSUE TITLE
Astro 3 - Using View Transitions gives random errors 

### ISSUE THREAD

**Issue by ThePrimeDev** [withastro/astro#8524]
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.16.1
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
```

### Describe the Bug

If I use viewtransitions, it it gives me errors, literally nonsense errors, like

`Transform failed with 1 error:
C:/Users/Jerryyy/Documents/Antlify/HallerMedical/src/pages/szakember/[...uri].astro?astro&type=script&index=0&lang.ts:2:0: ERROR: Unexpected "export"`

in a file where I have multiple pages, so I definitly need the "export async function getStaticPaths()" thing

If I go to other page, where I have no getStaticPaths, it gives me other random error:

`Transform failed with 1 error:
C:/Users/Jerryyy/Documents/Antlify/HallerMedical/src/pages/szakembereink.astro?astro&type=script&index=1&lang.ts:2:7: ERROR: Expected "(" but found "Navbar"`

![image](https://github.com/withastro/astro/assets/81071854/c23f24c7-78cd-45b7-a9d2-7857028e1c42)

If I refresh the page the error disappears, but no viewtransitions.

Same thing happens in ssr and static mode.

### What's the expected result?

ViewTransitions to work without this strange thing?

### Link to Minimal Reproducible Example

Somewhy I could not get a reproduction

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ThePrimeDev** [comment]
Told you that I cant get a reproduction 💀💀💀

**Comment by bluwy** [comment]
If there's no reproduction, we can't fix it either. How would we start debugging this?

**Comment by ThePrimeDev** [comment]
> If there's no reproduction, we can't fix it either. How would we start debugging this?

I tried to reproduce it, there the view transitions simply doesn't work. As a software dev, I know that some bugs are easily reproducable, others can be very hard to reproduce. I think this case is the second one. 

I can upload my workspace to a git repo, and share it to you, hoping that same bug will appear on your device

**Comment by bluwy** [comment]
If you're able to share your project (ideally publicly on github), then that would be great as at least there is a starting point for us. I can remove the "needs repro" tag once there's one.

**Comment by ThePrimeDev** [comment]
> If you're able to share your project (ideally publicly on github), then that would be great as at least there is a starting point for us. I can remove the "needs repro" tag once there's one.

https://github.com/ThePrimeDev/hallermedical

**Comment by ThePrimeDev** [comment]
In the readme you can find the required .env variables

**Comment by lilnasy** [comment]
Does this issue only happen with WordPress and WPGraphQL. Could they be removed for the reproduction?

**Comment by ThePrimeDev** [comment]
> Does this issue only happen with WordPress and WPGraphQL. Could they be removed for the reproduction?

There is a GraphQL endpoint in my project, but everything uses the rest api.

GraphQL is unused for now.

**Comment by lilnasy** [comment]
Your project builds fine.
<img width="275" alt="image" src="https://github.com/withastro/astro/assets/69170106/5d11f145-321b-42cc-baa1-f4fc97a99298">

I recommend deleting the node_modules folder, updating versions and reinstalling. You were using old integrations that are not supported on Astro v3.

> some bugs are easily reproducable, others can be very hard to reproduce.

Unfortunately, Astro maintainers only have so much time. Minimal reproductions are valuable because it would be better spent fixing bugs instead of chasing them.

**Comment by ThePrimeDev** [comment]
> Your project builds fine.
> <img width="275" alt="image" src="https://github.com/withastro/astro/assets/69170106/5d11f145-321b-42cc-baa1-f4fc97a99298">
> 
> I recommend deleting the node_modules folder, updating versions and reinstalling. You were using old integrations that are not supported on Astro v3.
> 
> > some bugs are easily reproducable, others can be very hard to reproduce.
> 
> Unfortunately, Astro maintainers only have so much time. Minimal reproductions are valuable because it would be better spent fixing bugs instead of chasing them.

I didnt told for a second it's not building. Look again what I said. 


Run npm run dev
Access the website, go to the szakembereink page, and u will get an error.

**Comment by lilnasy** [comment]
<img width="500" alt="image" src="https://github.com/withastro/astro/assets/69170106/69a2731c-01ca-486b-a96c-a5198d244db2">

Works fine in dev mode as well.

You can open a support thread on our discord if you want help confirming the issue.
https://astro.build/chat
