### ISSUE TITLE
Astro attributes in components dont work with Tailwind

### ISSUE THREAD

**Issue by marcosvzqz** [withastro/astro#8528]
### Astro Info

```block
Astro                    v3.0.13
Node                     v20.3.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Brave

### Describe the Bug

I'm trying to create classes from attributes within an Astro component, but Tailwind isn't detecting the class and isn't loading it. I'll write a quick example

_Button.astro_
_============_
---
```
// Components
interface Props {
    palette: "action" | "primary" | "secondary" | "accent" | "ambient";
    background?: string;
}

const {
    palette,
    background,
} = Astro.props;

const buttonDefault =
    "cursor-pointer text-center";

let classList = `
${buttonDefault}
${background ? `bg-${background}` : `bg-white`};
}
---

<button class={classList}>
    <slot />
</button>
```
_============_

If you try to put a component with the attribute, something like:
`<Buttons palette="accent">This is a button</Buttons>
`
Astro will load the class, but Tailwind won't detect it (unless it has been used before).
<button class="cursor-pointer text-center **bg-action**">FUNCIONA</button>

***
It seems that when trying to pass a prop by combining part of the Tailwind class with a variable 
`bg-${background}`
Tailwind doesn't detect it. 
However, if you write the full Tailwind class, Astro detects the class:
`<Buttons palette="bg-accent">This is a button</Buttons>
`

### What's the expected result?

Tailwind can detect classes in component attributes even if they don't have the complete class.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lzh5px?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by xiBread** [comment]
This isn't an Astro issue. https://tailwindcss.com/docs/content-configuration#dynamic-class-names
