### ISSUE TITLE
Impossible to use both Vue Tsconfig & astro TSConfig in the same project?

### ISSUE THREAD

**Issue by gkatsanos** [withastro/astro#8531]
### Astro Info

I have setup TS for Astro as described in the documentation:

```json

{
  "extends": "astro/tsconfigs/base",
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": ".",
    "paths": {
      "@assets/*": ["src/assets/*"],
      "@components/*": ["src/components/*"],
      "@pages/*": ["src/pages/*"],
      "@helpers/*": ["src/helpers/*"],
      "@layouts/*": ["src/layouts/*"],
      "@constants/*": ["src/constants/*"],
      "@experiments/*": ["src/experiments/*"],
      "@store/*": ["src/store/*"],
      "@i18n/*": ["src/i18n/*"],
      "@scripts/*": ["src/scripts/*"]
    },
    "types": ["@astrojs/image/client"],
    "jsx": "preserve",
    "plugins": [
      {
        "name": "@astrojs/ts-plugin"
      }
    ]
  }
}
```

Now I am adding a Vue Component in my project, and I want to enable TS annotations for it. 

```js
<script setup lang="ts">
import type { ShortlistItem } from "@store/shortlist.ts"
import { onMounted } from "vue"
import VerifiedIcon from "@assets/Verified.svg?inline"
import FastResponderIcon from "@assets/FastResponder.svg?inline"
import BinIcon from "@assets/BinIcon.svg?inline"
import { useStore } from "@nanostores/vue"
import {
  $shortlist,
  loadItemsFromLocalStorage,
  removeItem,
} from "@store/shortlist.ts"

const data: ShortlistItem[] = useStore($shortlist)

const getImage = (item) => {
  if (item.productImage) return item.productImage
  return item.companyLogo
}

const remove = (id: string) => {
  removeItem(id)
}

onMounted(() => {
  loadItemsFromLocalStorage()
})
</script>
```

### Describe the Bug

Getting a bunch of errors which make no sense:
<img width="1026" alt="image" src="https://github.com/withastro/astro/assets/1768834/3d112928-cf98-4446-94de-045dc4113df5">

any idea whats missing for the svg imports to be evaluated correctly? or what the issue with nanostores is?

### What's the expected result?

no errors?

### Link to Minimal Reproducible Example

tricky

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Does this happen without the `"extends": "astro/tsconfigs/base"` part? It could be a Volar bug as that's handling intellisense for `.vue` files. https://github.com/vuejs/language-tools

**Comment by gkatsanos** [comment]
This solved the `.svg` imports, and I also solved another issue by adding `    "allowImportingTsExtensions": true,` to my tsconfig.

But did I just remove a bunch of config by removing `"astro/tsconfigs/base"` that's related to checking types for Astro.locals and stuff? anyway to specify a different config for .vue and a different config for the rest of the files?

**Comment by bluwy** [comment]
`astro/tsconfigs/base` refers to [this file](https://github.com/withastro/astro/blob/main/packages/astro/tsconfigs/base.json), so you can try copying it and perhaps remove/change some options if it affects the Vue file intellisense.



> anyway to specify a different config for .vue and a different config for the rest of the files?

You can but it's quite tricky to setup, usually you can share the same tsconfig for `.vue`, `.ts`, and `.astro` files though. 

From the errors you showed in the issue description, it looks like the Vue vscode extensions fail to pick up the `"paths"` configuration.

**Comment by Princesseuh** [comment]
Closing since this seems unrelated to us.
