### ISSUE TITLE
`windows.onload()` doesn't always fire when using `<ViewTransistions/>` router

### ISSUE THREAD

**Issue by walter9388** [withastro/astro#8534]
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.16.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome (haven't tested others)

### Describe the Bug

In my previous Astro project I have a component which uses an event listener tied to the page load as it is needed for certain functionality:
```astro
---
---

<div>
   <!-- some html here -->
</div>

<script>
window.addEventListener("load", function () {
  console.log("event listener triggered")
  // do work
})
</script>
```

This had previously worked fine (as I guess Astro 2 was a true MPA and page loads were always enforced), but when using the new Astro 3 `<ViewTransitions/>` router (which looks awesome in theory!) the above onload event listener is no longer always triggered (e.g. when navigating to a different page/route, then pressing the back button to come back to the page with this component on).

I'm not sure if this a bug or intentional SPA functionality which the view transitions api needs to enforce, but I don't really want to massively refactor and retest the whole website.

Any thoughts on how to fix this?

### What's the expected result?

Open the console when using the stackblitz example below, and see the effect of navigating back and forth between the two pages with `<ViewTransistions/>` commented out and uncommented.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hwqhvy?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by igor-ht** [comment]
It worked fine here with the Reproducible Example you gave. The event is being fired whenever the index page is loaded (both with and without the ```<ViewTransition />```, also using the links and the navigator back button).

Maybe I didn't understand the issue?

Also, have you tried using ```astro:page-load``` or ```astro:after-swap```?  They are event that are triggered when navigating through routes with ```<ViewTransition />``` You can find more information about them [here](https://docs.astro.build/en/guides/view-transitions/#astropage-load).

**Comment by matthewp** [comment]
You want to use `astro:page-load` to listen for when the page loads. It works both for the initial load and any navigations. See here: https://docs.astro.build/en/guides/view-transitions/#astropage-load

**Comment by walter9388** [comment]
Ah I think you are right, `astro:page-load` is likely what I'm after! Basically RTFD. Thanks!
