### ISSUE TITLE
Header anomaly and content hidden when change from mobile size to desktop size and nav menu is opened

### ISSUE THREAD

**Issue by joseantanaper** [withastro/astro#8535]
### Astro Info

```block
Astro                    v3.0.13
Node                     v20.3.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/mdx
                         astro-icon
                         AstroWind:tasks
                         astro-compress
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Edge

### Describe the Bug

1. Change browser size to a mobile size (then the "Header Navigation Menu" is collapsed).
2. Click on the "Navigation Menu Button" to open navigation links (and DON'T select any link to remain it opened).
3. Change browser size to a desktop size.
4. Then, "Header Navigation Menu" is shown **vertically middle centered**, and **no content** is shown. It seems that mobile opened menu remains some garbage here.
5. If click on body (BUT not on original header top position), everything returns to normal ("Header Navigation Menu" is on top and content is shown).

![2023-09-13_121427](https://github.com/withastro/astro/assets/56954559/aa96db25-098a-486b-a57d-9086eda4f37a)

### What's the expected result?

When change to Desktop Size the "Header Navigation Menu" should be at top position and the content should be shown as normal.

### Link to Minimal Reproducible Example

https://astrowind.vercel.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
We are not the maintainers of AstroWind. You might want to bring up this issue here: https://github.com/onwidget/astrowind
