### ISSUE TITLE
TypeError: Cannot destructure property 'value' of 'Astro2.cookies.get(...)' as it is undefined.

### ISSUE THREAD

**Issue by AdrianKnapp** [withastro/astro#8539]
### Astro Info

```block
Astro                    v3.0.13
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/tailwind
                         @astrojs/partytown
                         proxy
```

### Describe the Bug

Updating Astro version from 2 to 3, I'm getting an error related to cookies. Like Astro didn't update the cookies API. Does someone know or ever already have this problem and know how to solve it?

```
TypeError: Cannot destructure property 'value' of 'Astro2.cookies.get(...)' as it is undefined.
    at file:///Users/.../dist/server/chunks/chunk.931067d9.js:540:18
```

### What's the expected result?

I expect that cookies API from Astro works well.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-a6qkyu?file=src/pages/index.astro&on=stackblitz
### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
In Astro v2.x, [`Astro.cookies.get(key)`](https://docs.astro.build/en/reference/api-reference/#astrocookies) would always return an [`AstroCookie` object](https://docs.astro.build/en/reference/api-reference/#astrocookie), even if the cookie did not exist. To check for its existence, you needed to use `Astro.cookies.has(key)`.

Astro v3.0 returns `undefined` for `Astro.cookies.get(key)` if the cookie does not exist.

Specific migration instructions for this are included in our [Upgrade to Astro v3](https://docs.astro.build/en/guides/upgrade-to/v3/#changed-astrocookiesgetkey-can-return-undefined) guide!
