### ISSUE TITLE
404 on <Image /> after update to 3.0.13

### ISSUE THREAD

**Issue by gregorysirtoli** [withastro/astro#8544]
### Astro Info

```block
Astro                    v3.0.13
Node                     v20.5.1
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

All

### Describe the Bug

I have problems with the use of the new <Image /> functionality introduced in v3.

 I have a file called file.md composed like this

```
---
title: "What is Big Data?"
meta_title: ""
description: "Read more."
image: "../../assets/images/wiki/bigdata.png".
draft: false
---
Content....
```

the file is contained in the folder /src/content/wiki/file.md

The image, on the other hand, is contained in the folder /src/assets/images/wiki/bigdata.png

Reading the documentation, it is expressly requested that a relative path be used, and so I did. 

https://docs.astro.build/en/guides/images/#images-in-markdown-files

The problem is that at DEV everything is fine, at build time ALL images result with a 404.

I want to continue to use the images within the /src/ folder for optimisation purposes, but I do not understand why the images are not found during buil.

this is my astro config 
```
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";

export default defineConfig({
  site: "https://mario.it",
  trailingSlash: "always",
  compressHTML: true,
});
```

### What's the expected result?

The visualisation of images

### Link to Minimal Reproducible Example

https://gregorysirtoli.it/wiki/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by blueboxes** [comment]
I have the same issue

**Comment by tristengrant** [comment]
I'm also having this issue.
