### ISSUE TITLE
Type hints don't work

### ISSUE THREAD

**Issue by J-env** [withastro/astro#8552]
### Astro Info

```block
Astro                    v3.0.13
Node                     v18.17.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/preact

typescript             ^5.1.6
```

### Describe the Bug

astro@v3.0.13

`import.meta.glob` The prompt and return value types are both any.
<img width="710" alt="image" src="https://github.com/withastro/astro/assets/25259920/db9c03f4-4191-496f-943c-52fd4fcb4d4e">

`astro@v2.10.15`, `astro@v3.0.13` Type hints don't work.
<img width="1155" alt="image" src="https://github.com/withastro/astro/assets/25259920/eefa728f-2017-4253-9e87-89bf4641b44f">

### What's the expected result?

astro@v2.10.15

`import.meta.glob` 
![image](https://github.com/withastro/astro/assets/25259920/53b94558-4e27-4673-a4b0-46f682862573)

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pratik-codes** [comment]
@matthewp Can i pick it up?

**Comment by bluwy** [comment]
It seems to be working for me. Please provide a repro for us to test out if not. And for autocompletion issues, they should be submitted to https://github.com/withastro/language-tools instead.
