### ISSUE TITLE
Animations for React components that are rendered with Array.map() don't work. 

### ISSUE THREAD

**Issue by Albertyhu** [withastro/astro#8553]
### Describe the Bug

CSS animations for React components that are rendered with Array.map() don't work. 
They only work if the React components are not rendered with the map method. 

Here is the directory where the React component renders a list of components using Array.map() method:
https://github.com/Albertyhu/uthan-template/tree/main2/src/components/accordion_component

### What's the expected result?

I expect that animation to work. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-5vjx3y

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Albertyhu** [comment]
Hi @matthewp, 
Thanks for replying.

I don't know why my earlier Stackblitz link didn't work, but here is a working minimal production:
https://stackblitz.com/edit/github-pizwfx-cfwjkf?file=src%2Fpages%2Findex.astro

**Comment by kashaudhan** [comment]
The `uuid()` is causing rerender the elements rendered with `Array`, so you need to either use `index` to some other variable as `key`.

**Comment by Albertyhu** [comment]
@kashaudhan 
 Got it. It works. Thanks for the suggestion.

**Comment by florian-lefebvre** [comment]
@Albertyhu can the issue be closed?

**Comment by Albertyhu** [comment]
Yes, @florian-lefebvre. This issue can be closed and is has been solved.
