### ISSUE TITLE
How to import external WebComponent from NPM

### ISSUE THREAD

**Issue by ivoba** [withastro/astro#8555]
### Astro Info

```block
Astro                    v3.0.13
Node                     v19.9.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

### Describe the Bug

I am trying to use a web-component (https://github.com/ivoba/obfuscate-wc) on a page.
<obfuscate-link email="aGVsbG..."></obfuscate-link>

It works in dev when i use an import statement:
```
<script>
 import('./node_modules/obfuscate-link-web-component/dist/obfuscate-link/obfuscate-link.esm.js');
</script>
```

However in prod mode resp. after build the node_modules is stripped out and the path does not resolve anymore.

When i use an ESM import it does not resolve.
>Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/obfuscate-link-web-component.js?v=4ad74b39' does not provide an export named 'default' (at impressum.astro:19:8)
```
<script>
import ObfuscateLink from 'obfuscate-link-web-component';
</script>
```
How should the web-component from NPM be imported?

### What's the expected result?

I can import a web-component in a script tag, both in dev and after build.

Note that stackblitz does not work currently due to old node version 16.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bdrksj?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Import it like usual instead `import('obfuscate-link-web-component')`, not the `node_modules` path. For further questions, please visit https://astro.build/chat for support. Thanks!
