### ISSUE TITLE
CSS Modules inject order

### ISSUE THREAD

**Issue by ymatuhin** [withastro/astro#8558]
### Astro Info

```block
Astro                    v3.0.13
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/preact
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

When I import CSS modules from Preact component, is goes first in order of all styles. Even before global styles. That messes up specificity for components.

### What's the expected result?

They should be treated as scoped css and be applied after globals.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-k1nega-mj5wcr?file=src%2Fcomponents%2FCounter.module.css

### Participation

- [ ] I am willing to submit a pull request for this issue.

<img width="595" alt="Screenshot 2023-09-14 at 17 05 02" src="https://github.com/withastro/astro/assets/3757971/9e0422d7-4164-4337-9694-06c8a50f36b6">

**Comment by natemoo-re** [comment]
Just to confirm, does the issue only occur in dev mode? Is the `astro build` output different?

**Comment by ymatuhin** [comment]
> Just to confirm, does the issue only occur in dev mode? Is the `astro build` output different?

Nope, build output has the same issue.

**Comment by lilnasy** [comment]
Could not reproduce the issue. The text renders green as expected.

<img width="350" alt="image" src="https://github.com/withastro/astro/assets/69170106/ebfc9d25-31c6-459c-ab44-0c082cc18fcf">

I find it really odd that in your screenshot global.css is a script. This is the result I'm getting from building your project.
<img width="350" alt="image" src="https://github.com/withastro/astro/assets/69170106/829e957d-51c2-447a-893e-ce70fef47318">

You might want to open a support thread on our discord: https://astro.build/chat.

**Comment by duncannah** [comment]
I'm having this same problem, only occurs on production build

**Comment by lilnasy** [comment]
@duncannah I can reproduce this issue only in dev mode. Could you open another issue with a minimal reproduction?

**Comment by ymatuhin** [comment]
@lilnasy yeah, looks like it happens only in dev mode. Sorry for misguidance.
