### ISSUE TITLE
Script in component included even when component is not

### ISSUE THREAD

**Issue by danielclausmeyer** [withastro/astro#8569]
### Astro Info

```block
Astro                    v3.1.0
Node                     v16.20.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```
(The stackblitz template needs to be updated to Node 18. But i tested it locally with 18 and it does not make a difference.)

### Describe the Bug

The script tag inside a component is included in the code even though the component is not.

Example:

`ScriptComponent.astro`:
```astro
<script>console.log('will execute')</script>
<p>Will not be included</p>
```

`index.astro`:
```astro
---
import ScriptComponent from "./ScriptComponent.astro"

const includeScript = false
---

{includeScript && <ScriptComponent />}
```

Even though the variable `includeScript` is false and the `<p>` will not be rendered, the script will still be included and executed.

### What's the expected result?

Nothing of the `ScriptComponent.astro` file should be included if the condition is false.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-q5yxtq?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is a known design constraint at the moment, see the following discussion: https://github.com/withastro/roadmap/discussions/664
