### ISSUE TITLE
Cannot access any header in .astro page files

### ISSUE THREAD

**Issue by alex-eliot** [withastro/astro#8572]
### Astro Info

```block
Astro                    v3.0.8
Node                     v20.5.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Firefox, Safari

### Describe the Bug

Accessing `Astro.request.headers.get(...)'` always returns null.

I am following the documentation as described here: https://docs.astro.build/en/core-concepts/routing/#dynamic-redirects

Am I doing something wrong?

### What's the expected result?

It should return the request's header values.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/crazy-grass-5r8439?file=/src/pages/index.astro:73,14

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You can only access headers when using server side rendering: https://docs.astro.build/en/guides/server-side-rendering/
