### ISSUE TITLE
astro:assets not working with docker

### ISSUE THREAD

**Issue by do-web** [withastro/astro#8573]
### Astro Info

```block
Astro                    v3.1.0
Node                     v20.5.0
System                   macOS (arm64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

Dockerfile
```
FROM node:lts AS runtime

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

EXPOSE 80

ENV HOST=0.0.0.0
ENV PORT=80

CMD node ./dist/server/entry.mjs
```

astro.config.mjs
```
import { defineConfig } from 'astro/config';
import node from "@astrojs/node";

// https://astro.build/config
export default defineConfig({
    output: "server",
    adapter: node({
        mode: "standalone"
    }),
});
```

Index.astro
```
---
import Layout from '../layouts/Layout.astro';
import { Image } from "astro:assets";
import hero from "../assets/img/hero.jpg";
---

<Layout title="Welcome to Astro.">
	<main>
		<Image src={hero} alt="test" width="200" />
	</main>
</Layout>
```

### What's the expected result?

The image ist not rendered 
http://localhost:1337/_image?href=%2F_astro%2Fhero.81f5191f.jpg&w=200&f=webp 

got "Not Found"

### Link to Minimal Reproducible Example

https://github.com/withastro/astro/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
If there's something Astro is doing wrong specifically with Docker then please submit a pull request. Unfortunately we do not have the bandwidth to debug issues that require Docker. Most likely it's related to Docker configuration and not Astro itself; all applications should work with Docker.

Closing the issue since we won't be able to help.
