### ISSUE TITLE
Image won't load while running preview locally with vercel adapter on static  mode

### ISSUE THREAD

**Issue by brahimABD98** [withastro/astro#8575]
### Astro Info

```block
Astro                    v3.1.0
Node                     v20.6.1
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/vercel
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
```

### Describe the Bug

after adding vercel adapter with this config
```javascript
import vercel from '@astrojs/vercel/static';
export default defineConfig({
  integrations: [mdx(), sitemap(), tailwind()],
  output: "static",
  adapter: vercel({
    webAnalytics:{
      enabled: true,
    },
    speedInsights:{
      enabled: true,
    },
    imageService:true,
  })
});
```
all images aren't loading and getting 404 on network request tabs
![image](https://github.com/withastro/astro/assets/47871510/0c40dca8-56d1-4b7c-8f6d-be53e0698770)
the deployed version seems to be working fine the issue is only when you run it locally with astro preview command 

### What's the expected result?

images should load while running astro preview command instead of getting 404  

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-tcabtn?file=src%2Flayouts%2FBlogPost.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is kinda not possible to make work I think... Vercel Image Optimization only works when hosted.

**Comment by rishi-raj-jain** [comment]
Yeah, the static build does have the URL that'll be available upon hosting the same on Vercel, but not locally.

**Comment by matthewp** [comment]
Closing for the reasons given above, this is not possible to make work.
