### ISSUE TITLE
Sharing State between Astro Component and SolidJS component

### ISSUE THREAD

**Issue by whoiscarlo** [withastro/astro#8577]
### Astro Info

```block
Astro                    v3.0.13
Node                     v20.5.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/solid-js
                         @astrojs/sitemap
                         @astrojs/prefetch
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

I'm currently trying to figure out how to share state from my **SolidJS component** to my **Astro component**. I found the `nanostore` library which seems to work great for the SolidJS component but isn't working with the Astro.

I found this in the FAQ on this page: [link](https://docs.astro.build/en/core-concepts/sharing-state/)

> You cannot subscribe to store changes from a .astro file, since Astro components do not re-render.

Which is seems weird because in the example used in the docs, it does exactly that: [link](https://docs.astro.build/en/recipes/sharing-state/)

```
<script>
  import { isOpen } from '../store.js';

  // Listen to changes in the store, and show/hide the dialog accordingly
  **isOpen.subscribe**(open => {
    if (open) {
      document.getElementById('dialog').style.display = 'block';
    } else {
      document.getElementById('dialog').style.display = 'none';
    }
  })

  document.getElementById('openDialog').addEventListener('click', openDialog);
</script>
```

Is there something wrong in the docs or am I just misunderstanding?

### What's the expected result?

Trying to figure out how to pass data between Astro components and SolidJS/ other component types.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ysaujj?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
@whoiscarlo 

What you've linked in

> Which is seems weird because in the example used in the docs, it does exactly that: [link](https://docs.astro.build/en/recipes/sharing-state/)

is referring to the Astro Components which are only limited to .astro components (as you can see on that link as you scroll down). If you're using frameworks such as SolidJS, you'd want to have a look at https://docs.astro.build/en/core-concepts/sharing-state/

**Comment by whoiscarlo** [comment]
Hey @rishi-raj-jain , Appreciate the link!

I'm already using nanostores/solid and passing state between SolidJS components seems to work fine, but passing state from Solid to Astro currently isn't working. If you check out my stackblitz example you'll see what I mean.

**Comment by rishi-raj-jain** [comment]
Hey @whoiscarlo,

So to make it more crisp, you're trying to use nanostores in both astro and solid, correct?

To create a minimal reproduction of the issue you're facing, I should try doing something in the solid component and see if that gets reflected in Astro, correct?

**Comment by whoiscarlo** [comment]
@rishi-raj-jain yup that's correct!

The exact thing I'm doing is having a user login through a form built in SolidJS and when the form submits, get the user info from `fetch`, place the user info into the `nanostore`, redirect the page, and on the new page (Astro component) show the user info.

Is my stackblitz link not working? Because it's all right there.

**Comment by whoiscarlo** [comment]
Got help from the discord and the issue is the fact that I'm launching a new page after storing the data in the nano store which means the data no longer exist. The solution is to use [nanostores/persistent](https://github.com/nanostores/persistent). The persistent library saves the data in local storage in the browser so that i can be used later.
