### ISSUE TITLE
Server Endpoint Returns 500 When Deployed to Google Cloud Run

### ISSUE THREAD

**Issue by akarpov91** [withastro/astro#8582]
### Astro Info

```block
Astro                    v3.0.13
Node                     v20.4.0
System                   macOS (arm64)
Package Manager          bun
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/lit
```

### Describe the Bug

I've built and deployed my hybrid SSR site to Google Cloud Run. 

The front end renders fine, but when front end form makes a call to the SSR /api/newsletter-signup.ts endpoint it returns 500 on Google Cloud Run, but 200 locally.

### What's the expected result?

SSR /api/newsletter-signup.ts endpoint should return user object. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-c4uyg5?file=tsconfig.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by akarpov91** [comment]
I deployed the same repo to Vercel, only changing the adapter from node to vercel, and it worked as expected. 

Could the Google Cloud Run issue be with the node adapter?

**Comment by matthewp** [comment]
We don't directly support Google Cloud Run. If it runs locally that's the best we can do to help you. As someone who's seen similar issues in my own projects in the past, it's possible Google Cloud Run has some sort of firewall that is preventing POST requests to hit your server. Or if not that, perhaps something similar.

Closing as there's nothing we can do to help here.

**Comment by fityannugroho** [comment]
@matthewp I have the similar issue. I create `/pages/api/wisely.ts` server endpoint with the project output set to **hybrid** and using **Vercel serverless** adapter. Of course, I use `export const prerender = false` for that file.

The endpoint `GET /pages/api/wisely?q=sometext` works as expected in local, but in Vercel preview deployment (see the last deployment in https://github.com/fityannugroho/wisely-web/pull/1), it doesn't. It throws error 500 in browser console. What have I missed?

For reproduction, please take a look at this branch: https://github.com/fityannugroho/wisely-web/tree/feat/playground
