### ISSUE TITLE
No renderer installed for react

### ISSUE THREAD

**Issue by GrantBirki** [withastro/astro#8584]
### Astro Info

```console
$ npm run astro info

> astrowind@0.0.0 astro
> astro info


Astro version            v2.10.15
Package manager          npm
Platform                 linux
Architecture             x64
Adapter                  Couldn't determine.
Integrations             astro-icon, @astrojs/tailwind, @astrojs/sitemap, @astrojs/image, @astrojs/mdx, @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

It is not browser specific

### Describe the Bug

I have a `/gallery` page on my Astro template site. It is a React component that loads a few images in a nicely formatted gallery.

I start up the Astro project by running `npm start`. All the pages load fine, including the `/gallery` page, but when I look at my local dev console output, I see the following error message:

```console
$ npm start

> astrowind@0.0.0 start
> astro dev

  🚀  astro  v2.10.15 started in 765ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

09:28:49 PM [content] Watching src/content/ for changes
09:28:49 PM [content] Types generated
09:28:49 PM [astro] update /.astro/types.d.ts
09:28:51 PM [astro] update /.astro/icon.d.ts
09:28:52 PM [renderer] /home/grantbirki/code/astrowind/src/components/widgets/Gallery.jsx No renderer installed for react. Try adding `@astrojs/react` to your project.
```

This is quite bizarre as I certainly have the `@astrojs/react` package installed, and the `/gallery` page loads totally fine.

## Reproduction Steps

1. Clone the following repo -> https://github.com/GrantBirki/astrowind
2. Run `npm install`
3. Run `npm start`
4. Navigate to the `/gallery` page
5. Look at your dev console to see the error

### What's the expected result?

I would expect to not see this error in my dev console as everything seems to be working fine 🤷 

### Link to Minimal Reproducible Example

https://github.com/GrantBirki/astrowind

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You're using the latest version of `@astrojs/react` (v3), which is not compatible with your installed Astro version (v2). You need to either upgrade `astro` to v3 or downgrade `@astrojs/react` to v2.

**Comment by jsjoeio** [comment]
Ah I am facing this same issue. Following the docs helped: https://docs.astro.build/en/guides/upgrade-to/v3/#upgrade-astro
