### ISSUE TITLE
Images loading when using Bun

### ISSUE THREAD

**Issue by GioPat** [withastro/astro#8587]
### Astro Info

```block
Astro                    v3.1.0
Node                     v19.8.1
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Creating a simple Image using the `<Image />` component results in error (500) of the following endpoint `http://localhost:4321/_image?href=%2F%40fs%2FUsers%2Fgiovannipatruno%2Frepos%2Fmisc%2Fmy-astro-project-using-bun%2Fsrc%2Fassets%2Flogo_dark.png%3ForigWidth%3D319%26origHeight%3D319%26origFormat%3Dpng&w=30&h=30&f=webp` and not displaying the image.

### What's the expected result?

Display the image as per NodeJS behavior

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-7rx5zs?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Please report Bun errors to Bun. Astro is a node framework.

In this case the problem is most likely the Sharp installation not working correctly. See https://github.com/oven-sh/bun/issues/4549

**Comment by Princesseuh** [comment]
Bun intends to be Node compatible, so the docs page is relevant for it, it's a valid use case to be trying to use a Node-compatible runtime. What's not relevant are issues however, as they're 100% of the time not issues in Astro, but issues in the runtime trying to be Node compatible.
