### ISSUE TITLE
"_" in _astro folder inside /dist makes it impossible to create browser extensions with Astro.

### ISSUE THREAD

**Issue by ivanjeremic** [withastro/astro#8594]
### Astro Info

```block
Astro                    v3.1.0
Node                     v18.17.1
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/solid-js
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

"_" in _astro folder makes it impossible to create browser extensions with Astro.

```
Cannot load extension with file or directory name _astro. Filenames starting with "_" are reserved for use by the system.
Could not load manifest.
```

### What's the expected result?

Being able to build and run Browser Extension with Astro, the underscore in `_astro` works not with the system.

### Link to Minimal Reproducible Example

https//nothing

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You can specify the name of this folder in your config, see https://docs.astro.build/en/reference/configuration-reference/#buildassets
