### ISSUE TITLE
Certain characters are garbled in Markdown using Pages.

### ISSUE THREAD

**Issue by KoutaKawase** [withastro/astro#8606]
### Astro Info

```block
Astro                    v3.1.1
Node                     v18.17.1
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When Markdown files are placed in the Pages directory according to the following [documentation](https://docs.astro.build/en/guides/markdown-content/#file-based-routing), certain characters are garbled in the browser.

[Markdown & MDX 🚀 Astro Documentation](https://docs.astro.build/en/guides/markdown-content/#file-based-routing)

This mainly occurs when apostrophes, double quotation marks and Japanese characters are used. (I am a Japanese speaker).

A minimal StackBlitz project that replicates this can be found here.

https://stackblitz.com/edit/github-uae268?file=src%2Fpages%2Fexample.md

After building, access /example from preview.

In my environment, the text is garbled like this.

![FireShot Capture 021 - Astro Minimal Example - StackBlitz - stackblitz com](https://github.com/withastro/astro/assets/37544784/91bd907a-4059-4b7e-ba5a-870cfc5711bd)

However, the garbled characters did not occur in Markdown under the content directory using the blog template by astro.new.
A minimal StackBlitz project that replicates this can be found here.

https://stackblitz.com/edit/github-cawxj8?file=src%2Fcontent%2Fblog%2Ffirst-post.md

After building, access /blog/first-post from preview.
This is a screenshot of it when it is rendered correctly

![FireShot Capture 022 - Astro Blog Example - StackBlitz - stackblitz com](https://github.com/withastro/astro/assets/37544784/811aee20-dc8b-46c0-846a-8e28da582edc)

The problem also occurred when I was trying out the tutorials in the Astro documentation.
This is because that tutorial has a section on placing Markdown under Pages.

### What's the expected result?

No garbled characters

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uae268?file=src%2Fpages%2Fexample.md)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by KoutaKawase** [comment]
Is this a problem that only occurs in my environment?

**Comment by Princesseuh** [comment]
You need a `charset` on your page. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#charset

**Comment by KoutaKawase** [comment]
@Princesseuh
Thank you!
It was an elementary mistake on my part.

thank you
