### ISSUE TITLE
📘 DOC: Add documentation specific to renderers like solid or svelte or react

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#861]
I think maybe there should be a page that has these sections:
- An initial section that explains that you can add renderers to your project and lists all of the currently existing renderers
- A section for each renderer used for any specifics, idiosyncrasies, or notes to make

for example: 
![image](https://user-images.githubusercontent.com/10626596/127025066-b2e7a172-b495-4937-819a-3e1d44ca38ab.png)

partially suggested by @Maestro#6355 on Discord while trying to find out what all of the possible renderers are.

A counterpoint would be that this might belong in https://github.com/one-aalam/awesome-astro instead, since it is eventually going to also include community-made renderers I assume, but I also don't see a problem with duplicating information for this.. 

The pages per section don't need to describe everything about them, but just small extra bits of information maybe.

**Comment by jonathantneal** [comment]
This was done! ✨ <sup>[ref](https://docs.astro.build/en/reference/renderer-reference/)</sup>

We didn’t track it in this issue, so it’s only getting closed now. Thanks for originally getting this on the board, @jasikpark. :)
