### ISSUE TITLE
Regression: Using @astrojs/mdx@1.0.3+ and @analogjs/astro-angular together throws an error

### ISSUE THREAD

**Issue by rlmestre** [withastro/astro#8611]
### Astro Info

```block
Astro                    v3.1.1
Node                     v20.5.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @analogjs/astro-angular
```

### Describe the Bug

When the following conditions are true:
- Add `@astrojs/mdx` (1.0.3 and above) and `@analogjs/astro-angular` (any version) to an Astro project
- Create and navigate to an MDX file

This error is thrown:
```bash
Unhandled Promise rejection: mdast-util-definitions expected node ; Zone: <root> ; Task: null ; Value: Error: mdast-util-definitions expected node
    at definitions (file:///Users/rafael/dev/astro-angular-mdx-zone-bug-repro/node_modules/mdast-util-to-hast/node_modules/mdast-util-definitions/lib/index.js:38:11)
```
The problem was introduced in f3f62a5a due to `remarkShiki` being refactored to return an `async` function ([here](https://github.com/withastro/astro/commit/f3f62a5a20f4881bb04f65f192df8e1ccf7fb601#diff-cdd82999ad7bf0f6baff5bdd1ddce14de6360eac70c886ebf73d8e311fc827b0R42)), which conflicts with `zone.js`.

I was able to fix it locally by refactoring this function to return a non-async function and moving the logic to the Promise's `then` callback instead.

### What's the expected result?

The integrations should continue to work seamlessly as before.

### Link to Minimal Reproducible Example

https://github.com/rlmestre/astro-angular-mdx-zone-bug-repro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This sounds like `@analogjs/astro-angular` is changing promise behavior _on the server_ with `zone.js`? Is that intentional? I can't imagine another reason why our internal refactoring to use a promise would be a problem.

**Comment by rlmestre** [comment]
Yeah, `zone.js` does need to run in the server as well, and it patches Promise APIs. The problem isn't happening with regular promises though, just this async function, which is why I suggested rewriting to use `Promise.then`.

**Comment by matthewp** [comment]
Yes, this is a limitation of zones. I wrote a [zones library](https://github.com/canjs/can-zone) and am very familiar with this problem. Unfortunately in 2023 using async/await is very common. We're not going to rewrite all of our code to use Promise.then and you're likely going to run into many other libraries where this library stops working as a result. I would recommend moving away from libraries that depend on being able to track async behavior in JS, because it's not possible.
