### ISSUE TITLE
Stutter scrolling on iOS Safari 17

### ISSUE THREAD

**Issue by evertjr** [withastro/astro#8625]
### Astro Info

```block
Astro                    v3.1.2
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Safari

### Describe the Bug

I used the blog template to start with.
I'm using SPA mode by importing` <ViewTransitions />` component in the common `<head> `

It works fine in all browsers, except on iOS Safari on my iPhone 14 Pro Max, the scroll is extremely stuttery and it's likely using a lot of CPU as the phone gets warm. This doesn't happen in other SPAs using other frameworks.

Setting the fallback to none fixes the problem but disables the SPA behavior, the problem persists even with fallback swap.

Weirdly enough on my old iPad 9 it works fine, maybe it's something related to the ProMotion display? I'm not sure how Astro implementation works but this demo https://live-transitions.pages.dev/ doesn't cause any issues.

### What's the expected result?

The scroll should be smooth and a simple static webpage should not cause high cpu usage.  

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rywjxp?file=src%2Fcomponents%2FBaseHead.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by judahsullivan** [comment]
If I may suggest try the fallback option in your ViewTransitions as the view transition api only works in chromium browsers currently, word is their team is still developing browser support

**Comment by evertjr** [comment]
That's what I did, but setting fallback to none also disables Astro's SPA behavior, which I think are two separated things in the same feature.  I was relying on the astro:page-load event listener which as result doesn't fire on Safari with fallback none, so I had to do some extra work to make interactive components behave correctly in SPA and MPA modes. Ideally it should just work since that's what advertised... When enabled it does present a fade animation in Safari but I guess there's some unthrottled function running at 120hz and causing performance issues.

**Comment by evertjr** [comment]
the last few updates haven't addressed this issue. Theres something I can do to help?

To quickly reproduce the issue all it takes is to start a Astro project with blog template, import the <ViewTransitions /> into the BaseHead.astro and open the website on a iPhone with ProMotion Display (mine is 14 pro max), theres heavy stuttering while scrolling.

**Comment by matthewp** [comment]
@evertjr you could try tweaking the value here: https://github.com/withastro/astro/blob/main/packages/astro/src/transitions/router.ts#L520-L521 The `300` controls how often the scroll handler is called. Maybe try increasing that value? You'll need to delete `node_modules/.vite` if you change that file.

**Comment by fredericoo** [comment]
Also having this issue. Also perceptible by trying to over-scroll the container on desktop devices.

Linke you mentioned @matthewp is no longer there, and there's no `300` anymore. I wonder if it's now being called on a loop?

**Comment by matthewp** [comment]
@fredericoo The number is here: https://github.com/withastro/astro/blob/d2340058aab30c91be4161e24bd3a1d70e58a205/packages/astro/src/transitions/router.ts#L599 it's now `350`

**Comment by QasimArif** [comment]
Glad I'm not seeing things. Thought it was just me. I've added the fallback to none and it's all good for me now. 

I did some general testing and found it's iOS Safari & iOS Chrome where I'm seeing issues. Firefox is smooth. Using iPhone 14 pro. 

Astro 4.3.1
