### ISSUE TITLE
Vite posthtml plugin does not work to support better HTML compression using htmlnano

### ISSUE THREAD

**Issue by aminya** [withastro/astro#8626]
### Astro Info

```block
Astro                    v3.0.12
Node                     v20.7.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             astro-imagetools
                         @astrojs/solid-js
                         @astrojs/sitemap
                         @astrojs/mdx
```

### Describe the Bug

The astro compiler's `compressHTML` isn't enough:
- It doesn't remove comments from the output
- The inline CSS is not minified (e.g. when inserted by Astro plugins)

Also, using `posthtml` and `htmlnano` through the vite plugins doesn't work. 

```js
// https://astro.build/config

import posthtml from "@vituum/vite-plugin-posthtml"
import { defineConfig } from "astro/config"
import htmlNano from "htmlnano"

const browserlist = ["chrome71"]

export default defineConfig({
  site: "https://test.com",
  base: "/",
  trailingSlash: "always",
  vite: {
    target: browserlist,
    plugins: [
      posthtml({
        include: false,
        extend: false,
        plugins: [htmlNano()],  // doesn't do anything
      }),
    ],
  },
})

```

### What's the expected result?

- Support `htmlnano` through `post-html` through `vite`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rv9gm4?file=src%2Flayouts%2FLayout.astro

Run `astro build` and see the big comment in `index.html` via `cat ./dist/index.html`

<img width="1026" alt="image" src="https://github.com/withastro/astro/assets/16418197/1d8da3ac-9480-4b00-a82f-d0da09a6f3f7">

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You can use [middlewares](https://docs.astro.build/en/guides/middleware/) to compress it yourself. Vite plugins don't work as that's applied during build-time. The html files Astro creates are only after the build output.

**Comment by aminya** [comment]
@bluwy 
This issue still looks relevant to me, and there are multiple action items:

- The documentation doesn't specify anything regarding the limitation of the plugins:
https://docs.astro.build/en/recipes/add-yaml-support/
- The Astro compiler should remove comments form the output
- The posthtml middleware could be supported natively by astro.

**Comment by marvincaspar** [comment]
Hi,
I had the same issue and created a simple middleware.ts file. Maybe this helps you for now

```
import type { APIContext, MiddlewareNext } from "astro";

export const onRequest = async (
  context: APIContext,
  next: MiddlewareNext<Response>
) => {
  const response = await next();
  const html = await response.text();

  // remove html comments
  const redactedHtml = html.replaceAll(/<!--(.|\n)*?-->/g, "");

  return new Response(redactedHtml, {
    status: 200,
    headers: response.headers,
  });
};
```

**Comment by aminya** [comment]
I published an astro-plugin to fix this issue. Now, `htmlnano` and `posthtml` are both supported for Astro!

https://www.npmjs.com/package/astro-htmlnano
https://www.npmjs.com/package/astro-posthtml
