### ISSUE TITLE
API routes return 404 when deployed to Vercel

### ISSUE THREAD

**Issue by vadimdemedes** [withastro/astro#8631]
### Astro Info

```block
Astro                    v3.1.2
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### Describe the Bug

API route works in dev server, but when deployed to Vercel it returns 404 status code.

I made a minimal reproduction at https://github.com/vadimdemedes/astro-api-route-404-repro and deployed it to https://astro-api-route-404-repro.vercel.app.

1. Open the URL.
2. Click "Submit form".
3. Locally, API route is executed and it redirects back to the root page. But on Vercel, that same API route is 404.

### What's the expected result?

API route works the same way locally and on Vercel.

### Link to Minimal Reproducible Example

https://github.com/vadimdemedes/astro-api-route-404-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Which version of the adapter are you using?

**Comment by vadimdemedes** [comment]
Latest one, 5.0.1.

**Comment by alvar-additio** [comment]
Hi! Try to add an `export const prerender = false;` on top of the file that has to be server-rendered.  

Here's the documentation for reference: https://docs.astro.build/en/guides/server-side-rendering/#opting-out-of-pre-rendering

**Comment by vadimdemedes** [comment]
Hey @alvar-additio, yep, it works with `prerender = false` now. I guess I didn't expect API routes would need to opt out, because I thought they can't be prerendered anyway. Now that I think of it, I realize `get` routes can?

Thanks!
