### ISSUE TITLE
Dynamic routes in Astro `redirects` error

### ISSUE THREAD

**Issue by delucis** [withastro/astro#8639]
### Astro Info

```block
(run on StackBlitz)

Astro                    v3.1.2
Node                     v16.20.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

n/a

### Describe the Bug

Astro supports a [`redirects`](https://docs.astro.build/en/core-concepts/routing/#redirects) field in `astro.config`. According to our docs this should be able to support dynamic routes:

> Dynamic routes are allowed as long as both the new and old routes contain the same parameters

I’m seeing errors for each of the following cases:
```js
  redirects: {
    '/old/[...spread]': '/new/[...spread]',
    '/old/[dynamic]': '/[dynamic]',
    '/old/[dynamic]/[route]': '/[dynamic]/[route]',
  }
```

In each case, attempting to load a route from one of the `/old/` paths, throws:

> `getStaticPaths()` function is required for dynamic routes. Make sure that you `export` a `getStaticPaths` function from your dynamic route.

The dynamic routes at the new location each contain `getStaticPaths()`.

### What's the expected result?

Dynamic redirects containing the same parameters redirect to the new location as expected.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gjbu5b?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Just to confirm, this is a dev-mode only issue?
