### ISSUE TITLE
Astro.params don't get proper types based on getStaticPaths

### ISSUE THREAD

**Issue by vorant94** [withastro/astro#8643]
### Astro Info

```block
Astro                    v3.1.1
Node                     v18.18.0
System                   macOS (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

I have the following component for displaying one post

```typescript
import { getCollection, getEntry } from 'astro:content';

export async function getStaticPaths() {
  const posts = await getCollection('posts');

  return posts.map(post => ({
    params: {slug: post.slug}
  }));
}

const { slug } = Astro.params;

const post = await getEntry('posts', slug);
const { Content } = await post.render();
```

This setup results in `No overload matches this call.` error during `astro check` for `getEntry` call, which is kinda what is expected since `Astro.params.slug` is just a `string`. But it isn't just a string, those slugs were generated earlier by `getStaticPaths`, so in reality they are `ValidContentEntrySlug`

I tried to add custom `Params` interface the way it works with `Props` and `Astro.props` to tell what is the type of params I expect for the page, but it had no effect e.g. `Props` are propagated to `Astro.props`, but `Params` are not propagated to `Astro.params` and I get `'Params' is declared but never used` warning instead

I'm using Astro for a new project, so I assume my repo can be considered minimal reproducible example, see `[slug].astro` file there.

regarding contribution, I'll be glad to dive into the code by myself in case the bug is confirmed, but i'd like to get some sort of starting direction where to look and so on

### What's the expected result?

types are property assigned, so there is no errors during `astro check`

### Link to Minimal Reproducible Example

https://github.com/vorant94/vorant94.github.io

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You want to use [getEntryBySlug](https://docs.astro.build/en/reference/api-reference/#getentrybyslug).

**Comment by vorant94** [comment]
yeah, `getEntryBySlug` definitely helps. also this issue can be avoided at all by setting post to `props` via `getStaticPaths` as I found out later yesterday. But what i wanted to point is that `params` actually don't reflect the type they actually have nevertheless there are another approaches that allow to avoid the issue in this particular case

**Comment by vorant94** [comment]
> You want to use [getEntryBySlug](https://docs.astro.build/en/reference/api-reference/#getentrybyslug).

yeah, `getEntryBySlug` definitely helps. also this issue can be avoided at all by setting post to `props` via `getStaticPaths` as I found out later yesterday. But what i wanted to point is that `params` actually don't reflect the type they actually have nevertheless there are another approaches that allow to avoid the issue in this particular case
