### ISSUE TITLE
Importing multiple images inside a markdown with ![alt](src)

### ISSUE THREAD

**Issue by ailequal** [withastro/astro#8649]
### Astro Info

```block
Astro                    v3.1.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Starting from a brand new Astro project created with `npm create astro@latest -- --template blog` I cannot add more than a single image to a markdown file, altough I can do it inside a mdx file. The images are stored under `/src/assets` (but it seems to not work even under `/public`).

This is the [only commit](https://github.com/ailequal/tremendous-tower/commit/57e3d41fb7a700058ebffc60b18143591ab5b37a) that I pushed for simulating the problem from a fresh installation.

The error from StackBlitz is the following (which is the same from my computer):
```
 error   Parse failure: Unexpected token (7:54)
  At file: /home/projects/github-rzgqu4/src/content/blog/test-md.md
  Contents of line 7:                           import Astro__ZmkHF3 from "/src/assets/puppy.jpg";,import Astro__1NHksg from "/src/assets/parrot.jpg";
  File:
    /home/projects/github-rzgqu4/src/content/blog/test-md.md?astroPropagatedAssets
  Stacktrace:
Error: Parse failure: Unexpected token (7:54)
At file: /home/projects/github-rzgqu4/src/content/blog/test-md.md
Contents of line 7:                             import Astro__ZmkHF3 from "/src/assets/puppy.jpg";,import Astro__1NHksg from "/src/assets/parrot.jpg";
    at ssrTransformScript (/home/projects/github-rzgqu4/node_modules/vite/dist/node/chunks/dep-df561101.js:55395:15)
    at ssrTransform (/home/projects/github-rzgqu4/node_modules/vite/dist/node/chunks/dep-df561101.js:55370:12)
    at Object.ssrTransform (/home/projects/github-rzgqu4/node_modules/vite/dist/node/chunks/dep-df561101.js:65044:20)
    at loadAndTransform (/home/projects/github-rzgqu4/node_modules/vite/dist/node/chunks/dep-df561101.js:55041:24)
    at async instantiateModule (/home/projects/github-rzgqu4/node_modules/vite/dist/node/chunks/dep-df561101.js:55927:10)
```

### What's the expected result?

All the images added inside a single markdown file with the sintax `![alt](src)` should be correctly displayed and optimized automatically.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rzgqu4?file=src%2Fcontent%2Fblog%2Ftest-md.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Fixed by https://github.com/withastro/astro/pull/8633, just not released yet

**Comment by ailequal** [comment]
That's good to know! My apologize for opening a duplicated issue.

**Comment by Princesseuh** [comment]
> That's good to know! My apologize for opening a duplicated issue.

No worries, you couldn't know!
