### ISSUE TITLE
`remark-math` throws an error on multiline math

### ISSUE THREAD

**Issue by OverflowCat** [withastro/astro#8650]
### Astro Info

```block
Astro                    v3.1.2
Node                     v18.15.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
                         @astrojs/mdx
```

### Describe the Bug

`astro.config.mjs`

```js
import { defineConfig } from 'astro/config';

import remarkMath from 'remark-math';
import rehypeMathJax from 'rehype-mathjax';

// https://astro.build/config
export default defineConfig({
  markdown: {
    smartypants: false,
    gfm: false,
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeMathJax],
  },
});

```

`multiline.md`

```markdown
$$
c = \dfrac 1
{\sqrt{\epsilon_0\mu_0}}
$$
```

Got error

```sh
Cannot read properties of undefined (reading 'mathFlowInside')
    at Object.exitMathFlowFence (file:///home/projects/github-jdbvgm/node_modules/mdast-util-math/lib/index.js:112:19)
...
```

But the code below works:

```ts
import rehypeKatex from 'rehype-katex';
import rehypeStringify from 'rehype-stringify';
import remarkMath from 'remark-math';
import remarkParse from 'remark-parse';
import remarkRehype from 'remark-rehype';
import { read } from 'to-vfile';
import { unified } from 'unified';

const file = await unified()
  .use(remarkParse)
  .use(remarkMath)
  .use(remarkRehype)
  .use(rehypeKatex)
  .use(rehypeStringify)
  .process(await read('example.md'));

console.log(String(file));
```

with

```json
  "dependencies": {
    "rehype-katex": "^7.0.0",
    "rehype-stringify": "^10.0.0",
    "remark-math": "^6.0.0",
    "remark-parse": "^11.0.0",
    "remark-rehype": "^11.0.0",
    "to-vfile": "^8.0.0",
    "unified": "^11.0.3"
  }
```

Noticed [this two plugins](https://github.com/withastro/astro/blob/1d4f91b033b70f6d863698acea8722d7ad8e50b9/packages/markdown/remark/src/index.ts#L75). Having tried disabling `gfm` and `smartypants` but error persisted.

Maybe due to astro using lower versions of `remark-*`, `rehype-*`, `*mdast*` in deps. Having tried using the same version of `remark-math` and `rehype-mathjax` that `integrations/mdx` uses but error persisted.

### What's the expected result?

The equation should render correctly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jdbvgm?file=src%2Fpages%2Findex.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Using `remark-math` v5 and `remark-mathjax` v4 worked for me. Unfortunately we can't bump our remark/rehype plugins yet as it's a breaking change. There were also some remark/rehype plugins we used that weren't up to the major change that prevented us from doing so before.

Closing this for now as there's not much we can do, but feel free to ask away of any questions!

**Comment by jcf** [comment]
I'm using KaTeX rather than Mathjax; same error as @OverflowCat.

The following versions are working for me:

``` json
{
  "rehype-katex": "^6.0.3",
  "remark-math": "^5.1.1"
}
```

**Comment by OverflowCat** [comment]
> Using `remark-math` v5 and `remark-mathjax` v4 worked for me. Unfortunately we can't bump our remark/rehype plugins yet as it's a breaking change. There were also some remark/rehype plugins we used that weren't up to the major change that prevented us from doing so before.
> 
> Closing this for now as there's not much we can do, but feel free to ask away of any questions!

@bluwy

I have tried updating these dependencies in the Astro source code and running the tests. `markdown` seems to function correctly, but `mdx` depends on older versions of `remark-rehype`, etc., making it hard to simply bump the version numbers to resolve the issue. Given this, could we consider the following solutions:

1. Add a section offering guidance on math to the documentation;
2. Introducing built-in config options for math rendering, similar to how we currently allow users to toggle between Prism and Shiki for syntax highlighting;
3. As a fallback, use `peerDependencies` to specify which versions of dependencies are required.

Would any of these options be feasible?

**Comment by gyunseo** [comment]
> I'm using KaTeX rather than Mathjax; same error as @OverflowCat.
> 
> The following versions are working for me:
> 
> ```json
> {
>   "rehype-katex": "^6.0.3",
>   "remark-math": "^5.1.1"
> }
> ```

@jcf it worked for me. thanks!!!!
