### ISSUE TITLE
Error with exit code 137 ("Killed") when having too many images

### ISSUE THREAD

**Issue by nolanlawson** [withastro/astro#8653]
### Astro Info

```block
Astro                    v3.1.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

This is Ubuntu 22.04.

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

When having lots of image assets (in my project, I had ~6000), Astro fails to build using `astro build`. Instead, it says `Building static entrypoints...` and then eventually crashes with a 137 (Out-of-Memory) error.

On my system, I see this output:

```
09:42:05 PM [build] Building static entrypoints...
Killed
root@9dc224615f36:/mnt# echo $?
137
```

I've put together a minimal repro to demonstrate: https://github.com/nolanlawson/astro-oom-137-repro. The repro copies an image file 10,000 times in a `postinstall` script (so you don't have to download 10,000 images).

To repro:

```shell
git clone https://github.com/nolanlawson/astro-oom-137-repro repro
cd repro
npm i
npm run build
```

### What's the expected result?

Even if there are a lot of image assets, I would expect Astro to build successfully rather than run out of memory. I'm porting a site over from Wordpress, and Wordpress is able to handle this number of large photo files.

Note that I previously opened an issue for this, but I'm opening a new one to keep things clean: https://github.com/withastro/astro/issues/6664

### Link to Minimal Reproducible Example

https://github.com/nolanlawson/astro-oom-137-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
Spent last 2 hours debugging this, and removing everything from your code and just having this just works:

```
const meta = await import.meta.glob("../assets/**/*", { import: 'default', eager: true });
const imagesToDisplay = Object.values(meta)
```

**Comment by rishi-raj-jain** [comment]
Or we could have something in Astro that supports dynamic import of assets.

**Comment by nolanlawson** [comment]
@rishi-raj-jain Thanks for the feedback! Unfortunately, the solution you propose did not work for me ([here's what I did](https://github.com/nolanlawson/astro-oom-137-repro/commit/79819e412827fff627797912535c1d06b394f40f)). I'm still getting 137 "Killed" error messages while running `astro build`.

**Comment by nolanlawson** [comment]
I will admit, though, that it got further this time before being killed:

```
03:35:05 PM [build] Building static entrypoints...
03:38:08 PM [build] Completed in 182.19s.

 generating static routes
▶ src/pages/index.astro
  └─ /index.html (+0.96s)

 generating optimized images
  ▶ /_astro/kitty.80902fef_Z19M0lr.webp (reused cache entry) (+4ms) (1/10001)
  ▶ /_astro/kitty_copy_0.35e10dfd_1oYGe4.webp (reused cache entry) (+2ms) (2/10001)
  ▶ /_astro/kitty_copy_1.76929db0_Z1YeyVR.webp (reused cache entry) (+2ms) (3/10001)
  ▶ /_astro/kitty_copy_10.8f49512e_2jB7ju.webp (reused cache entry) (+2ms) (4/10001)
  ▶ /_astro/kitty_copy_100.34b544e9_ZSs3wB.webp (reused cache entry) (+4ms) (5/10001)
Killed
```

I imagine this might be dependent on how much memory you have available and how exactly you're running the process. My machine has 16GB and I'm running inside a [Podman](https://podman.io/) container. (I've also tried it outside of Podman; it crashes in both cases.)

Perhaps with 50k or 100k images, in your case, it would still crash?

**Comment by rishi-raj-jain** [comment]
Ah right, makes sense. I think Astro is just re-exporting what vite does for the imports. Is there a way we can paginate the imports to process all of them but not at once (to not bloat the RAM) cc @bluwy

**Comment by rishi-raj-jain** [comment]
> const meta = await import.meta.glob("../assets/**/*", { import: 'default', eager: true });

so basically I think the variable 'meta' is the one occupying too much RAM.

**Comment by nolanlawson** [comment]
Thanks! If there's another workaround, I'm happy to try that out too.

FWIW `eager: true` causes it to crash on `astro dev` for me – whereas with non-`eager` mode, I can at least get `astro dev` to work, even if `astro build` does not.

In my actual project, it seems even 1,000 images are enough to cause a crash. Some of these images are huge – up to ~60MB. I'm guessing that all the images are read into memory at once?

**Comment by nolanlawson** [comment]
For anyone stumbling across this issue, I've self-solved with the following techniques:

1. Removing unused images from the `assets` directory, so I'm down from ~6k to ~1k images.
2. Running [mozjpeg](https://github.com/mozilla/mozjpeg/releases) over every JPG to reduce the size before running it through Astro.

It's a bit disappointing since I'd rather have Astro own the entire image optimization pipeline, but this is working for me for now.

**Comment by bluwy** [comment]
I'm not too familiar with Astro's image pipeline. Regarding `import.meta.glob` eager approach, they should work similarly as both are eagerly fetching the image urls before rendering the Astro html. This isn't something Vite controls, but how Node.js would schedule and fetches imports itself. Both approach runs well for me though.

For build, the images is currently optimized sequentially, so the exit is unlikely due to memory pressure, but maybe there's a memory leak somewhere.

https://github.com/withastro/astro/blob/2365c124645d5067a12987f205cee23a45d1d13d/packages/astro/src/core/build/generate.ts#L204-L213

**Comment by nolanlawson** [comment]
@bluwy Based on my debugging, it doesn't even reach the `generateImage` line of code before crashing. The crash happens during the `Building static entrypoints...` step.

**Comment by Princesseuh** [comment]
As far as I can tell, this is unrelated to how images are processed in Astro, it's just a lot of modules (every image ends up being a module) for Rollup to process, hence why it crashes before even reaching Astro's optimization step. 

I'm not quite sure why a lot of it stays in memory even after the `generating static routes` step though, I feel like by then things Rollup's part should've been cleared 🤔

fwiw, in a real project I would suspect that you wouldn't have exactly this pattern, where one module imports 10k modules, additionally, you could very easily make the imports lazy (using `import.meta.glob` without the `eager` flag), that way you can spread out the imports a bit).

Fwiw, I'm actually able to build your repro on my local computer, but it definitely does use a massive amount of RAM. May Rolldown save us.

**Comment by Princesseuh** [comment]
> @Princesseuh Maybe that's the case in my reduced repro (might not be the best repro then), but in my case, I didn't need to reduce the number of modules – I just needed to run the images through `mozjpeg` before handing them off to Astro. The smaller JPEG file sizes did the trick.

Hmm, that's very weird, as we definitely should not be holding in memory the image's data 🤔 I'll investigate more this week and hopefully have a (real) solution!

**Comment by Princesseuh** [comment]
We've made significant improvements to this in recent updates, trying to build the repro now we see a noticeable decrease in memory usage after the `Building static entrypoints` step

From a local build, we can really see the spike down:
<img width="144" alt="image" src="https://github.com/withastro/astro/assets/3019731/23c92f7f-76a7-4406-a0bb-79b99a2152ac">

Unfortunately, there's not much to do regarding how much memory it takes during the step however. I'm sure there are many improvements we can do in Astro, but ultimately Rollup just takes a lot of memory when there's a lot of modules, as is the case here. 

I will close this issue in the meantime, as "Lower memory usage" is generally a bit of a blurry goal and is, of course, something we're always working on.
