### ISSUE TITLE
Rendering Chunks Left Behind when building

### ISSUE THREAD

**Issue by helloimalastair** [withastro/astro#8659]
### Astro Info

```block
Astro                    v3.1.2
Node                     v18.15.0(bun 1.0.3)
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
                         sitemap-cleanup
```

### Describe the Bug

When using `vite.build.rollupOptions.output.chunkFileNames` to set a custom name for JS chunks, some build-related chunks are retained in the output directory, even if they aren't needed for rendering the page.

### What's the expected result?

All build-related chunks should be purged from the output directory, leaving only the scripts necessary for rendering/running the webpage.

### Link to Minimal Reproducible Example

[Stackblitz](https://stackblitz.com/edit/wnw17n)
To reproduce, stop dev process, and run `npm run build`, then check `dist/static` for JS chunks.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Workaround:
```diff
vite: {
  build: {
    rollupOptions: {
      output: {
-       chunkFileNames: "static/[hash].js",
+       chunkFileNames: "static/[hash].mjs",
        assetFileNames: "static/[hash][extname]",
      },
    },
  },
},
```

**Comment by bluwy** [comment]
We're cleaning up the files at https://github.com/withastro/astro/blob/2365c124645d5067a12987f205cee23a45d1d13d/packages/astro/src/core/build/static-build.ts#L374-L378, which is unfortunately `.mjs` only. It's probably not safe to clear everything because the SSR build also emit assets too.

Maybe we can track the `ssrBuild` output and only clear out the chunks (not assets), but I'm not sure if it'll work reliably.

**Comment by matthewp** [comment]
You can use the `astro:build:setup` hook to target only the client build, which is what I suspect you are wanting to do here, https://docs.astro.build/en/reference/integrations-reference/#astrobuildsetup

Closing as there is nothing actionable to be done here, our build system depends on static build assets being saved as `.mjs`.
