### ISSUE TITLE
[Build Error] The requested module 'x' does not provide an export named 'default'

### ISSUE THREAD

**Issue by raulfdm** [withastro/astro#8660]
### Astro Info

```block
Astro                    v3.1.2
Node                     v18.15.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Not relevant

### Describe the Bug

I'm trying to create an Astro project that uses three.js and its ecosystem, and when I tried to import a lib called [`lil-gui`](https://lil-gui.georgealways.com), while in `dev`, it works fine, it gets broken running a `build`:

```
 error   The requested module 'lil-gui' does not provide an export named 'default'
file:///Users/raulmelo/development/sandbox/test-lil-gui/dist/chunks/pages/script_d5fa1c97.mjs:1
import GUI from 'lil-gui';
       ^^^
SyntaxError: The requested module 'lil-gui' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

I noticed that if I edit the dependency package.json adding a "exports" property, it works fine:

```json
  "exports":{
    ".":{
      "import": "./dist/lil-gui.esm.js",
      "require": "./dist/lil-gui.umd.js"
    }
  }
```

My question here is: is there anything we need to do on Astro's/Vite's config to fix that?

### What's the expected result?

To build without error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-geagbm?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by raulfdm** [comment]
https://github.com/georgealways/lil-gui/assets/12464600/b4b4aa40-9790-469a-a36b-e87cfda3b424

**Comment by bluwy** [comment]
Sorry you're hitting this. Unfortunately it's a Vite bug, see https://github.com/vitejs/vite/issues/10712 and https://github.com/vitejs/vite/issues/14332 (and probably more). I'm planning to fix this in Vite 5, but for now there's not much Astro can do.

As a workaround, you can import it like this:

```js
import * as _GUI from 'lil-gui'
const GUI = GUI.default
// or (not sure if the above is enough)
const GUI = GUI.default || GUI
```

**Comment by raulfdm** [comment]
Oh.. nice @bluwy ... thanks getting me back and for the workaround 🙏

**Comment by raulfdm** [comment]
I noticed that in one if the open issues, a guy posted this: https://vite-plugin-ssr.com/broken-npm-package

I tried the following vite-config:

```ts
import { defineConfig } from "astro/config";

// https://astro.build/config
export default defineConfig({
  vite: {
    ssr: {
      // Add npm packages containing invalid code here
      noExternal: ["lil-gui"],
    },
  },
});
```

and the build succeeded: 

![CleanShot 2023-09-26 at 10 44 05](https://github.com/withastro/astro/assets/12464600/b33f3297-b569-4d46-ad1b-0c99c21e9fc7)

Also running a live server on `dist`, it worked fine.

**Comment by kitschpatrol** [comment]
Thanks for this tip. For some reason I just ran into this error in for the first time after upgrading from Astro 4.6.3 → 4.8.3. 

It's happening in production builds only, with complaints about a missing a default export on `nanoid`, which I'm only importing in Svelte components.

Here's the stack trace from the failed build:

```sh
15:48:11 [vite] ✓ built in 2.31s

 generating static routes 
2024-05-13T19:48:11.245Z astro:telemetry {
  context: {
    isGit: true,
    anonymousProjectId: '75d034b7c4fdc0dd0c1a22fcc8e69f50a50246f53fd192f5439f041340098812',
    packageManager: 'pnpm',
    packageManagerVersion: '9.1.1',
    anonymousId: 'a027c6f6f986bd6de11997d886abe7d1516be0d79855f6aa6df802f6fe46a496',
    anonymousSessionId: 'aaa25d967446653ca4eeab4994b492146a9b3d0c60d9dc0c777008fb12890b2d'
  },
  meta: {
    nodeVersion: '20.13.1',
    viteVersion: '5.2.11',
    astroVersion: '4.8.3',
    systemPlatform: 'darwin',
    systemRelease: '23.4.0',
    systemArchitecture: 'arm64',
    cpuCount: 14,
    cpuModel: 'Apple M3 Max',
    cpuSpeed: 2400,
    memoryInMb: 36864,
    isDocker: false,
    isTTY: undefined,
    isWSL: false,
    isCI: false,
    ciName: null
  }
}
2024-05-13T19:48:11.245Z astro:telemetry [
  {
    "eventName": "ASTRO_CLI_ERROR",
    "payload": {
      "name": "SyntaxError",
      "cliCommand": "build",
      "isFatal": true,
      "anonymousMessageHint": "The requested module"
    }
  }
]
The requested module 'nanoid/non-secure' does not provide an export named 'default'
  Stack trace:
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async generatePages (file:///Users/mika/Code/svelte-tweakpane-ui/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.5.0-beta/node_modules/astro/dist/core/build/generate.js:120:7)
    at async AstroBuilder.build (file:///Users/mika/Code/svelte-tweakpane-ui/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.5.0-beta/node_modules/astro/dist/core/build/index.js:133:5)
    at async build (file:///Users/mika/Code/svelte-tweakpane-ui/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.5.0-beta/node_modules/astro/dist/core/build/index.js:45:3)
    at async runCommand (file:///Users/mika/Code/svelte-tweakpane-ui/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.5.0-beta/node_modules/astro/dist/cli/index.js:140:7)
 ELIFECYCLE  Command failed with exit code 1.
```
<br />
<br />
Adding the following to my Astro config fixed it:
<br />

```ts
vite: {
  ssr: {
    noExternal: ['nanoid']
  }
}
```

**Comment by scarletczen** [comment]
Anyone getting this issue again? Build is failing only on CI, and the astro config workaround is not working. 
![image](https://github.com/user-attachments/assets/5ac8b22e-05ba-4ea9-8323-82d7e6d966de)

**Comment by rrscodes** [comment]
@scarletczen Yes the same is happening for me since yesterday evening and the workaround is not helpful.

**Comment by gilbertoxdev** [comment]
> Anyone getting this issue again? Build is failing only on CI, and the astro config workaround is not working. ![image](https://private-user-images.githubusercontent.com/84438186/356788415-5ac8b22e-05ba-4ea9-8323-82d7e6d966de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTg5ODcsIm5iZiI6MTcyMzM1ODY4NywicGF0aCI6Ii84NDQzODE4Ni8zNTY3ODg0MTUtNWFjOGIyMmUtMDViYS00ZWE5LTgzMjMtODJkN2U2ZDk2NmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA2NDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMmJjNzdhZWJkZjQ0ZGIwY2UyNmJiYzQ2YTk5ZDQ4NjFlY2RiYTI3ZTkyMjc5OGUzMTE2ZTQ4OTBiZDIxODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QEH3eW3a7hvhctgeAERk7mX1KSkBliiRYgfxZEjuTCY)

I have the same error and have not found a solution.

**Comment by gilbertoxdev** [comment]
The solution is installing npm install @iconify/tools --save

**Comment by scarletczen** [comment]
> The solution is installing npm install @iconify/tools --save

Tried, but did not help

**Comment by maximgx** [comment]
> > The solution is installing npm install @iconify/tools --save
> 
> Tried, but did not help

didn't, because when you install as per his suggestion you end up with two versions of @iconify/tools --save

and astro continues to pick the old one, you must remove the old one – for me it worked

in production unfortunately, the workaround is `rm -rdf node_modules/.pnpm/@iconify+tools@3.0.7 && npm run build`

**Comment by scarletczen** [comment]
> > > The solution is installing npm install @iconify/tools --save
> > 
> > 
> > Tried, but did not help
> 
> didn't, because when you install as per his suggestion you end up with two versions of @iconify/tools --save
> 
> and astro continues to pick the old one, you must remove the old one – for me it worked
> 
> in production unfortunately, the workaround is `rm -rdf node_modules/.pnpm/@iconify+tools@3.0.7 && npm run build`

Thank you, this workaround did help in production, however I'm not sure why this error would pop up all of a sudden on a fine weekend,
