### ISSUE TITLE
TypeError: FormData parse error missing final boundary with bun.sh

### ISSUE THREAD

**Issue by Liliandev** [withastro/astro#8662]
### Astro Info

```block
I'm using latest astro version with Bun.sh
```

### Describe the Bug

When using in production with **Bun.sh**, when a form is posted, i have the following error :

TypeError: FormData parse error missing final boundary

### What's the expected result?

No error and post submission must be decoded

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Astro is a Node framework, please post Bun issues over at their repo.
