### ISSUE TITLE
CSS media queries do not work on a child component

### ISSUE THREAD

**Issue by Dzelix** [withastro/astro#8667]
### Astro Info

```block
Astro                    v3.1.2
Node                     v18.15.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

CSS styles written within media queries in Parent component do not work on Child component. 

Layout is here
```
<div class="header__btn-wrap">
    <!-- parsed as <button class="transparent" id="try" data-astro-cid-35s5zxad="">Click</button> -->
   <Button type={'transparent'} id={'try'}>Click</Button>
    <a class="header__link" href="#" target="_blank">link</a>
</div>
```

With this CSS tag `<a>` is hidden, and `<button>` is not when media query applied. 

```
  @media (max-width: 767px){
    .header__btn-wrap > * {
      display: none!important;
    }
  }
```

The following CSS does not work on `<button>`.
```
  @media (max-width: 767px){
    #id {
      display: none!important;
    }
  }
```

```
  @media (max-width: 767px){
    .header__btn-wrap > button {
      display: none!important;
    }
  }
```
```
  @media (max-width: 767px){
    .transparent {
      display: none!important;
    }
  }
```

### What's the expected result?

Child component has `display: none;` when such stated in Parent component. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-kmqkay?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You need to use `.header__btn-wrap > :global(*)`. See https://docs.astro.build/en/guides/styling/#global-styles
