### ISSUE TITLE
Page styles not being removed when view transitions enabled in >= 3.0.13

### ISSUE THREAD

**Issue by adrianosmond** [withastro/astro#8674]
### Astro Info

```block
Astro                    v3.1.4
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

Using the minimal reproducible example: https://stackblitz.com/edit/github-xrfje7

Steps to reproduce
- Open the index page, notice that the background is black
- Click the link to go to the white page
- Notice that the background is now white (this is expected)
- Click the link on the white page to go back to the first page with the black background
- Notice that the background is still white (this is not expected)

The issue is that the page which should have the black background now has the white background of the page it just visited. It seems like styles from the page with the white background are not being removed when leaving that page.

This only happens if you include ViewTransitions in the page Layout. 

It seems to have been introduced in v3.0.13 - v3.0.12 doesn't have this issue as far as I can tell.

### What's the expected result?

Styles that are specific to a single page shouldn't hang around after leaving that page

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xrfje7

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by resource11** [comment]
I have this same issue @matthewp. I can send you a repo for testing if you need.

**Comment by matthewp** [comment]
Thanks, taking a look now.

**Comment by matthewp** [comment]
Probably caused by this: https://github.com/withastro/astro/pull/8472
