### ISSUE TITLE
View Transitions: CSS rule with transition-name not generated when building app

### ISSUE THREAD

**Issue by thomasledoux1** [withastro/astro#8675]
### Astro Info

```block
Astro                    v3.1.4
Node                     v18.17.1
System                   macOS (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/react
                         auto-import
                         @astrojs/code-snippets
                         @astrojs/prefetch
                         @astrojs/partytown
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

In development, everything works fine.
When I build and deploy my website, my view transitions don't work.
I noticed that on the overview page where I have a list of blog posts (https://website-thomas-astro-git-feature-vt-thomasledoux1.vercel.app/blog), the <h2> titles do get a data-astro-transition-scope attribute added to them, but no CSS rule is applied to this data attribute. (there doesn't even seem to be a <style> tag generated at all)
When I go and check the title on the detail page (https://website-thomas-astro-git-feature-vt-thomasledoux1.vercel.app/blog/tailwind-setting-using-css-variables-react), I see the data attribute is applied AND there is a CSS rule which applies to that data attribute.

### What's the expected result?

I would expect the CSS to be generated for all the titles on the overview page, just like on the detail page.

### Link to Minimal Reproducible Example

https://github.com/thomasledoux1/website-thomas-astro/tree/feature/vt

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @thomasledoux1, sorry for not getting back to you on this sooner. I checked out your project but was not able to debug it without deploying to Vercel. Can you remove that requirement from your site?

**Comment by ref-thomasledoux1** [comment]
Hi @matthewp , I can do that! Would you like me to deploy it to another host? Or what do you mean specifically?

**Comment by matthewp** [comment]
I'd like to be able to run it locally, so if it could be made to work with SSG that would be ideal. Otherwise with the Node adapter might be ok.

**Comment by ref-thomasledoux1** [comment]
Hi @matthewp , the branch https://github.com/thomasledoux1/website-thomas-astro/tree/feature/vt now uses SSG

**Comment by matthewp** [comment]
Thanks! This is the same underlying bug as https://github.com/withastro/astro/issues/7761 so going to close this in favor of that. Hoping to work on that one soon.

**Comment by noboomu** [comment]
I'm seeing a similar issue but I'm not using mdx. Should I file a separate issue?
