### ISSUE TITLE
Astro image transformation doesn't work when msw/node mocks are running

### ISSUE THREAD

**Issue by susickypavel** [withastro/astro#8681]
### Astro Info

```block
Astro                    v3.1.1
Node                     v18.16.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/vercel
Integrations             @astrojs/mdx
                         @astrojs/tailwind
                         @frontendista/astro-minify
```

### Describe the Bug

I'm running [msw/node](https://mswjs.io)  interception layer for mocking certain API calls during development.

The problem is that when I start the mock server from `astro.config` then endpoints for image transformation don't work and the endpoints return 404.

This happens only in development, if I build the website everything is ok (even with mocks enabled).

### What's the expected result?

Images should be generated.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mjk9gb?file=package.json,astro.config.mjs,src%2Fpages%2Findex.astro,src%2Fassets%2Fcat.jpg&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @susickypavel, we don't directly support this usage. If there's something we're doing that results in this that we can change, we would be happy to do so. But we cannot take the time to debug why this particular library does not work with Astro. Happy to continue the conversation in the closed issue.
