### ISSUE TITLE
Changes to files not picked up when disabling HMR

### ISSUE THREAD

**Issue by isaac-mcfadyen** [withastro/astro#8683]
### Astro Info

```block
Astro                    v3.1.4
Node                     v20.5.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### If this issue only occurs in one browser, which browser is a problem?

All browsers

### Describe the Bug

- When HMR is disabled by setting the flag `vite.server.hmr` to `false` in `astro.config.mjs`, changing and saving a file is not picked up at all by the dev server.
- Only completely restarting the dev server (Control+C and re-running `astro dev`) causes file changes to appear.
- Disabling HMR has a number of use-cases - for example, in one Astro project I don't want my page to make a new WebRTC connection every time I save, only when I explicitly refresh the page.

### What's the expected result?

- HMR is disabled, meaning that the page does not automatically apply changes on save.
- However, I expect to be able to see changes when manually refreshing the page, which is not the case.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mz3dgs?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
That's correct, HMR affects both module replacement for your server-side code and your client-side code. There isn't an HMR config for each part separately.

**Comment by isaac-mcfadyen** [comment]
@matthewp interesting - in other frameworks (SvelteKit mainly) pages update on save with HMR being disabled. Is that just because they implement things differently?

**Comment by matthewp** [comment]
Could be, I'm not sure.
