### ISSUE TITLE
vite.config.js gets used by astro... intentional?

### ISSUE THREAD

**Issue by AimForNaN** [withastro/astro#8702]
### Astro Info

```block
Astro                    v3.1.4
Node                     v20.7.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Not sure if it is intentional, but the astro docs gives the impression that this probably shouldn't be the case. From a practical point of view, it would be nice if these two things were kept separate anyway. `vite.config.js` can store conflicting configuration that could cause astro to fail to start a dev server and even fail to generate static content.

### What's the expected result?

Having two separate vite configurations (e.g. `astro.config.mjs` and `vite.config.js`) that aren't aware of each other's existence.

### Link to Minimal Reproducible Example

https://github.com/AimForNaN/astro-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Yeah I think it's unintentional. We should add a `configFile: false` inline Vite config to prevent this. I hope this isn't relied upon by others to be a breaking change though, especially that we already have the `vite` config option.
