### ISSUE TITLE
Portal Into Head when SSR / SSG

### ISSUE THREAD

**Issue by wakaztahir** [withastro/astro#8703]
### Describe

I have a library for Solid JS which is a CSS in JS library, I can't access the document so Every styled call renders two components

```
const X = styled("div")`
   color : red;
`
```

calling <X /> will render to

```
<>
   <style>.aclass{ color : red; }</style>
   <div class="aclass" />
</>
```

This works, its simple, nothing complicated. The `className` is determined by generating a unique hash for the CSS contents

Issue No 1
- When there are multiple invocations of a single component, It still outputs a style tag with same class, So I thought I would use a Map so to keep track and not generate style components multiple times, which would contain which classes have been generated, So I set each class to true in the Map before outputting a style tag but this didn't work and everything became invisible because maybe the whole map became true after the initial render
I think this happens because there are multiple renders when in development mode so I am going to test this in production mode to see if it works.

If this works I would deliver zero JavaScript to the browser and when generating the component will evaluate if it has rendered that CSS before and if it has, It won't render. Otherwise I could render a script that that will inject a style tag into document using a function I generated before but this script tag will run on client giving runtime overhead and possibly FOUC

Issue No 2
- To access the head and append styles to the head, I would need a `<Portal>` but that's not possible without JavaScript, which requires that all of my components use `client:only` which I don't want to do
When all style elements go to `head` It would make it easier for me to remove duplicate style tags

I didn't want to post this to discussions where it would be lost forever and wouldn't get a response !

### My question is : 

How can I inject style tags into head using a portal but not requiring the users to say client:only

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Not sure I completely understand, you want to run some JavaScript, but without `client:only`? Integrations can use [injectScript](https://docs.astro.build/en/reference/integrations-reference/#injectscript-option). Astro components can have a `<script>` element. That and client components are your only options. Did I misunderstand the problem?

**Comment by wakaztahir** [comment]
@lilnasy Yes its kind of related to CSS in JS, But I already have a working CSS In JS library with Astro + Solid, The reason I created this issue, is because There are two small issues going on with my library and Astro may or may not have an API to fix my issues, 

@matthewp No, I don't want to inject a script element, I want to inject a style element with styles in it, into the document's head element and I want to do it from a framework component

For Example MyFrameworkComponent (jsx)
```
export default function MyFrameworkComponent() {
   injectStyleInHeadSomehowWithoutRunningJavascriptOnBrowser(() => {
        return (<style> // My Styles Here </style>)
   });
}
```

Assume MyFrameworkComponent is deeply nested and can be referenced in Astro / Solid components, Astro needs to provide the function `injectStyleInHeadSomehowWithoutRunningJavascriptOnBrowser`

**Comment by wakaztahir** [comment]
here's my site, https://qinetik.github.io/anique If you read the console logs on the site, You'll see that the javascript is not being loaded, I wanted to deploy to Github without Github actions. Website is built at development mode and works perfectly in the development mode but somehow _astro folder is not ending up on the server

**Comment by wakaztahir** [comment]
The second problem I have is that I can't keep track of which styles have been generated and which haven't

for example this code, does not work, When I run the server, there are no styles, I do not understand why

```tsx

const renderedStyles = new Map<string, boolean>()

export function StyleRenderingComponent(props : { styles : string }) {
     const styleId = // my style id here
     if(renderedStyles.contains(styleId)){
          // render nothing, since style has been rendered before
          return <></> // or null
     } else {
         renderedStyles.setKey(styleId)
         return <style>{props.styles}</style>
     }
}

```

I believe that on the first render renderedStyles becomes true for all keys and for the second render there's nothing to render (assuming there are multiple renders in development mode so production should work, haven't tested)

**Comment by wakaztahir** [comment]
Please checkout my UI library for Solid that uses CSS in JS with Astro at https://qinetik.github.io/anique

**Comment by lilnasy** [comment]
Since you are asking for a new feature, I think [roadmap/discussions](https://github.com/withastro/roadmap/discussions) would be a better place. New issues on this repo are expected to be actionable.

**Comment by eric-burel** [comment]
Hi, I've just opened a relevant discussion on the roadmap: https://github.com/withastro/roadmap/discussions/1032
