### ISSUE TITLE
Console Errors Due to ViewTransitions on Hover in Brave

### ISSUE THREAD

**Issue by krishna-santosh** [withastro/astro#8705]
### Astro Info

```block
Astro                    v3.2.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Brave

### Describe the Bug

Issue title could've been better, but I will try to do my best to describe the bug here.

When using ViewTransitions, if I hover over an `a` tag, it attempts to prefetch data, which results in a link being added to the document's head. However, the browser console displays the following error message:

```js
net::ERR_FAILED
```

This issue only arises when using the **Brave** browser. I  tested with Firefox and Chromium, and they did not generate any error logs. Interestingly, this problem does not occur in development mode when using `pnpm run dev` or `pnpm run preview`. 

Nevertheless, when I build the project using `pnpm run build` and serve the contents of the `dist/` folder using Caddy or any other static file server, this error occurs. The same error also occurs when hosting the website on Cloudflare Pages.

https://astro-brave-bug.pages.dev/

https://github.com/withastro/astro/assets/75202541/e473bac2-7a34-470c-a9b6-fd7f424809ef

### What's the expected result?

No console errors in Brave Browser 

### Link to Minimal Reproducible Example

https://github.com/krishna-santosh/astro-brave-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Looks like Brave shows this when there's a redirect in a prefetch. Does this cause any problems outside of the logging?

**Comment by krishna-santosh** [comment]
No problems except for logging

**Comment by matthewp** [comment]
We've updated our implementation and you can now disable prefetch on certain links: https://docs.astro.build/en/guides/prefetch/#prefetch-all-links-by-default

Closing as that's the only solution to this problem. We don't know if a link has a redirect or not, and therefore cannot prevent these console errors. But you can now disable prefetch on these links which should resolve the problem.
