### ISSUE TITLE
Flicker issue with ViewTransition, darkMode, and CSS Transition effects

### ISSUE THREAD

**Issue by IHIutch** [withastro/astro#8711]
### Astro Info

```block
Astro                    v3.2.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Chromium

### Describe the Bug

When using `ViewTransitions`, `darkMode`, and elements that use a transition effect, elements briefly flicker when the transition is activated.

### What's the expected result?

Elements do not flicker.

In the reproduction, I've added a potential solution (uncomment `disableAnimation`), borrowing some logic from [`next-themes`](https://github.com/pacocoursey/next-themes/blob/main/packages/next-themes/src/index.tsx#L285-L303). This way, transition effects are temporarily disabled. I suspect many folks may want to leverage similar logic anyway, in order to prevent different elements from transitioning at different rates when toggling color modes.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-btmufr?file=src%2Flayouts%2FBlogPost.astro,src%2Fpages%2Findex.astro,src%2Fpages%2Fother.astro

Toggle to dark mode and navigate between pages. You should see the buttons briefly flicker/fade as they transition from their "initial" state.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Thank you, @ninetynize, for nudging me to the recent code changes!
Would not otherwise have been able to see what is causing this.

**Comment by martrapp** [comment]
After removing the call to `disableAnimation()`:
![image](https://github.com/withastro/astro/assets/94928215/5e9345d3-d23b-4a95-9b10-3581fc55360c)
The four upper lines are the flicker of the buttons. In 3.1.4 they do not show.

**Comment by martrapp** [comment]
Thanks for the Minimal Reproducible Example. Should work with the upcoming fix without `disableAnimation`.
