### ISSUE TITLE
Node adapter error handling in http stream: throwing async iterable shouldn't result in last HTTP/1.1 chunk being zero-length

### ISSUE THREAD

**Issue by mb21** [withastro/astro#8714]
### Astro Info

```block
Astro                    v3.2.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

It's great that Astro handles [JS iterables](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol) in its templates and converts them to an HTTP stream, as mentioned in the [docs](https://docs.astro.build/en/guides/server-side-rendering/#streaming).

However, async iterables can throw/reject, and that case isn't handled very gracefully. (Of course, the 200 status-headers have already been sent, so that's not an option.) The Astro Node adapter only supports HTTP/1.1 (if I understand correctly), so there it's actually [fairly clear what to do](https://stackoverflow.com/a/77207289/214446): simply not terminate with the zero-length end chunk. Because (from https://github.com/marko-js/community/pull/1/):

> If a chunked response doesn’t terminate with the zero-length end chunk, the client must assume that the response was incomplete — which at the very least, [means a cache should double-check with the server before reusing the stored incomplete response](https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#rfc.section.3.1).

But Astro currently returns a zero-length chunk.

To reproduce:

```
---
function * generator () {
  yield 1
  throw Error('ohnoes')
}
---
<body>
  {generator()}
</body>
```

and run `npm run build && npm run preview`, then in another terminal `curl --raw -i http://localhost:4321`. This prints.

```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
[...]
<body>
1
1
15
Internal server error
0

```

### What's the expected result?

```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
[...]
<body>
1
1
15
Internal server error
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-v33sgm?file=src%2Fpages%2Findex.astro

(Note that the `curl` built into stackblitz somehow doesn't have a `--raw` option, so you need to download the example.)

**Comment by matthewp** [comment]
Thanks @mb21, sounds like you understand the topic quite well and we would very much appreciate a PR to resolve this.

**Comment by mb21** [comment]
I mostly collected info from that linked marko issue ;-) Maybe I'll have time to take a stab at it later, but I haven't dug much in the astro code-base yet... would also be important to know whether the node server is planned to have HTTP/2 and/or HTTP/3 support anytime soon or not...

We currently catch the throwing async iterator in our code base, put an error message at that place in the HTML, and continue to render the rest of the HTML. For that case, optimally we would have a way to signal CDNs and other caches about that, i.e. again end with a non-zero-lenght HTTP/1.1 chunk. Possible interface would be a `Astro.response.markStreamError()` function or similar...

**Comment by mb21** [comment]
> Node servers are typically run behind reverse proxies which would handle HTTPS, HTTP/2, and even HTTP/3. Would there be value to directly supporting HTTP/2?

I think you're right that there is little benefit. [This SO answer](https://stackoverflow.com/questions/41637076/http2-with-node-js-behind-nginx-proxy) mentions "HTTP/2 server push" and some security benefits though... 🤷

**Comment by lilnasy** [comment]
Do you know if http/2 would mean better behavior for mid-stream failures?

**Comment by mb21** [comment]
@lilnasy no, the way to signal a mid-stream failure is just different.

**Comment by lilnasy** [comment]
Server push is deprecated. If there is a good use-case for native http/2, feel free to open an issue - I'm pretty sure it can be added very easily.

**Comment by mb21** [comment]
Nice work @lilnasy !
