### ISSUE TITLE
Transition name is ignored in `.mdx` files

### ISSUE THREAD

**Issue by aminya** [withastro/astro#8718]
### Astro Info

```block
Astro                    v3.2.0
Node                     v20.7.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
                         @astrojs/sitemap
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

Any

### Describe the Bug

`transition:name` is ignored when used in `.mdx` files. In the output, the `transition:name` attribute remains as is. So, when going between pages, the transition for this element is ignored.

```mdx
---
---
import Image from "astro:assets"
import SomeImage from "/images/some_image.jpeg"

<Image
  alt="test"
  transition:name="test"
  src={SomeImage}
/>
```

### What's the expected result?

Do not ignore the transition name in Mdx like in the Astro files

### Link to Minimal Reproducible Example

TODO

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
From https://docs.astro.build/en/reference/directives-reference/

> Template directives are a special kind of HTML attribute available inside of any Astro component template (.astro files), and some can also be used in .mdx files.

Apparently, the `transition:*` directives are not yet available in .mdx files.

I am in the process of checking if we can extend this.

**Comment by martrapp** [comment]
It turned out that processing `transition:*` in .mdx files is quite complex after all. 
I will therefore put this on hold for the time being.

However, there is a workaround for the issue:

You could define an Astro component `/src/components/Transition.astro` that does the processing:
``` astro
---
interface Props {name: string}
const { name } = Astro.props;
---
<span transition:name={name}><slot /></span>
```

and use it to add transition attributes to elements in your `myfile.mdx` file

``` mdx
---
layout: /src/components/Layout.astro
---
import Image from "astro:assets"
import SomeImage from "/images/some_image.jpeg"
import Transition from '/src/components/Transition.astro';

<Transition name="test">
  <Image
    alt="test"
    src={SomeImage}
  />
</Transition>
```

Note that you also need a `/src/components/Layout.astro` component in which you at least enable ViewTransition:

``` astro
---
import { ViewTransitions } from "astro:transitions";
---
<html><head><ViewTransitions /></head><body><slot /></body></html>
```

**Comment by martrapp** [comment]
I will reopen the issue  when I (or someone else who wants to work on it) finds time to expand the set of template directives that can be used in .mdx files.
