### ISSUE TITLE
Not allowed to load local ressource with npm run dev

### ISSUE THREAD

**Issue by falco467** [withastro/astro#8720]
### Astro Info

```block
Astro                    v3.2.1
Node                     v20.8.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

**Possible Regression: This error only occurs with Astro 3.2.1 and not with 3.2.0**

When running `npm run dev` and previewing the local page in a browser (Chrome, Edge, ...) the console reports a lot of errors:

```
Not allowed to load local resource: file:///C:/Workspace/myPage/src/components/myComponent.svelte?svelte&type=style&lang.css
Not allowed to load local resource: file:///C:/Workspace/myPage/src/components/components.svelte?svelte&type=style&lang.css
Not allowed to load local resource: file:///C:/Workspace/myPage/node_modules/@astrojs/tailwind/base.css
```

This error occurs for all CSS Styles.

This bug cannot easily be reproduced in the StackBlitz environment, since this will not generate local file urls, like on a local windows machine.

### What's the expected result?

I would expect the page to work without problems exactly the way it does in astro 3.2.0. Current workaround is a downgrade to astro 3.2.0

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cyjuhk-wuuptl?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
@falco467 can you show what the `<head>` HTML look like completely? It’s likely due to a change I made and I don’t have a windows machine at hand. That would help debugging this easier.

**Comment by bis0072** [comment]
Getting same messages 
Astro                    v3.2.1
Node                     v18.17.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/react
                   
                  Not allowed to load local resource: file:///D:/1%20Projects/A%20Latu%20Solutions/LATU%20SOLUTIONS/ASTRO%20SITES/astro-licway/node_modules/.pnpm/astro@3.2.1_@types+node@20.8.0/node_modules/astro/components/viewtransitions.css
localhost/:1 Not allowed to load local resource: file:///D:/1%20Projects/A%20Latu%20Solutions/LATU%20SOLUTIONS/ASTRO%20SITES/astro-licway/src/layouts/Layout.astro?astro&type=style&index=0&lang.css
localhost/:1 Not allowed to load local resource: file:///D:/1%20Projects/A%20Latu%20Solutions/LATU%20SOLUTIONS/ASTRO%20SITES/astro-licway/node_modules/.pnpm/@astrojs+tailwind@5.0.0_astro@3.2.1_tailwindcss@3.3.3/node_modules/@astrojs/tailwind/base.css
