### ISSUE TITLE
Types in @astrojs/partytown not exported from package

### ISSUE THREAD

**Issue by jerry84** [withastro/astro#8723]
### Astro Info

```block
Astro                    v3.1.0
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          pnpm/npm
Output                   static
Adapter                  none
Integrations             @astrojs/partytown
                         @astrojs/vue
```

### Describe the Bug

When using `@astrojs/partytown` as `preset` It would be great to provide the `Partytown` config options in the same way as using it as an `integration` directly. it is currently not able to import the types `PartyrownOptions` and/or `PartytownConfig` that are used in the package.

This is currently not possible.
``` ts
import type { PartytownOptions } from '@astrojs/partytown';

type PresetConfig = {
  partytownOptions?: PartytownOptions;
}
```

### What's the expected result?

It should be possible to import types for `PartytownOptions` and/or `PartytownConfig` from `@astrojs/partytown`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-humest?file=src%2Fastro-presets.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
If this issue is confirmed, I'd like to handle it

**Comment by bluwy** [comment]
Sounds fine to me to export `PartytownOptions`.
