### ISSUE TITLE
Fragments (#) not shown in Astro.url

### ISSUE THREAD

**Issue by sjorsjes** [withastro/astro#8742]
### Astro Info

```block
Astro                    v3.2.2
Node                     v20.4.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             i18n-client
                         @astrojs/lit
                         @astrojs/mdx
```

### Describe the Bug

In a toplevel page, i'm trying to retrieve a url fragment (hash) but it does not show up in the Astro.url object.

It shows the following
```
URL {
  href: 'http://localhost:4321/page',
  origin: 'http://localhost:4321',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:4321',
  hostname: 'localhost',
  port: '4321',
  pathname: '/page',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

### What's the expected result?

What i expect is that when I visit "http://localhost:4321/page#hash-id" the Astro.url object looks like this

```
URL {
  href: 'http://localhost:4321/page#hash-id',
  origin: 'http://localhost:4321',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:4321',
  hostname: 'localhost',
  port: '4321',
  pathname: '/page',
  search: '',
  searchParams: URLSearchParams {},
  hash: '#hash-id'
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-f8slmm?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
`Astro.url` originates form the server request, which doesn't have access to `#`. You should use `location.hash` in the client side instead.

**Comment by sjorsjes** [comment]
wow. I should have thought of that. Sorry for the report 😅

**Comment by kolosseo** [comment]
@sjorsjes thanx for asking. I had the very same problem 'cause reading the "hash" property inside the URL object made me think it was managed by the server as well.
I hashes really can't be read by the server, I guess it should be removed the "hash" property to avoid useless misunderstandings.

**Comment by ADTC** [comment]
@bluwy but shouldn't SSR have the hash on server side? It's a dynamic request so the hash is known.
