### ISSUE TITLE
Console error "adl_Load is not defined" when page loads

### ISSUE THREAD

**Issue by PabloChavez03** [withastro/astro#8744]
### Astro Info

```block
Astro                    v3.2.2
Node                     v18.17.1
System                   Fedora Workstation 38
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

n/a

### Describe the Bug

When you enter the page it throws this error

![image](https://github.com/withastro/astro/assets/89558154/a5cbbe4b-fd76-4655-9652-3b884b4dcf0d)

### What's the expected result?

Let it be solved simply, I thank you for reading me

### Link to Minimal Reproducible Example

https://github.com/PabloChavez03/portafolio-3.0

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Could not reproduce the issue. Both dev and build work fine.
<img width="500" alt="image" src="https://github-production-user-asset-6210df.s3.amazonaws.com/69170106/272634896-dcc08927-5ba4-44ed-8fe5-cedfefcdcfb6.png">

Could you try on another system, maybe a gitpod or github codespaces?

**Comment by PabloChavez03** [comment]
Thank you for responding 🤗, this only happens in the Brave browser (v1.58.135), it doesn't happen in other browsers.
