### ISSUE TITLE
🐛 BUG: React fails to update a client-side component if the client-side hydration is different than SSR HTML

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#875]
### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

On the docs site, I'm seeing React fail to update a client-side component if the client-side hydration is meant to render differently vs. the SSR HTML. The use-case is for the docs theme selector:

<img width="340" alt="Screen Shot 2021-07-26 at 1 09 26 PM" src="https://user-images.githubusercontent.com/622227/127052431-e45a9019-542f-4fa3-8605-e098bb6d1dc8.png">

### Steps to Reproduce

1. on SSR, the component is always in its default state
2. on hydration, the component re-renders, now with access to localStorage, user system preference, etc.
3. we expect the client to re-render, and select the user's default state
3. according to debugger, the component actually does run on the client, but the UI doesn't update
4. on click, a real render is triggered.

**Comment by matthewp** [comment]
Seems like a definite bug, moving to accepted.

**Comment by jonathantneal** [comment]
A few of us are going thru older issues, and a few of us were not clear what this issue is about.

@matthewp, @FredKSchott, is this still an issue? Could you provide more details, or assign the task with some priority if it is still an active issue?

**Comment by FredKSchott** [comment]
I'm fine to close this for now, if it hasn't been touched in almost a year. Most likely fixed, but if not someone else can create a new issue with a reproduction that we can test.
