### ISSUE TITLE
`npm create astro@latest` sets wrong version

### ISSUE THREAD

**Issue by pvvrzv** [withastro/astro#8751]
### Astro Info

```block
-
```

### Describe the Bug

When installed via `npm create astro@latest` version `^3.2.3`  is listed inside package.json file. When the latest npm version is `3.2.2`. So when you run `npm install` you get `no matching version` error. 

### What's the expected result?

The latest version to be listed inside `package.json` file.

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
We're on it, sorry for the inconvenience!

**Comment by Princesseuh** [comment]
Should be fixed now, sorry for the inconvenience!
