### ISSUE TITLE
BUG: Partytown's Integration does not respect `lib` option

### ISSUE THREAD

**Issue by LefanTan** [withastro/astro#8760]
### Astro Info

```block
Astro                    v3.0.8
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/vue
                         astro-icon
                         post:build
                         @astrojs/partytown
```

### Describe the Bug

I've noticed that the source code doesn't respect the `lib` option provided through `astro.config.mjs`. Our application requires that we host our assets from a different folder path, is it possible for us to override the default config for `lib`? Much appreciated.

![image](https://github.com/withastro/astro/assets/12474777/7deef386-9ed5-4e68-a5ed-12f24d977994)
![image](https://github.com/withastro/astro/assets/12474777/2e15d297-1242-4189-bc35-41750a9b8d86)

### What's the expected result?

Provide custom `lib` path to Astro's Partytown integration.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-skk9gg?file=dist%2Ffavicon.svg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I suppose we can have `lib` take lower precedence here: https://github.com/withastro/astro/blob/eaed844ea8f2f52e0c9caa40bb3ec7377e10595f/packages/integrations/partytown/src/index.ts#L30-L31

It doesn't look intentional to me.

**Comment by florian-lefebvre** [comment]
I'd like to handle that
