### ISSUE TITLE
ViewTransitions API affecting other page animations after scolling/navigation

### ISSUE THREAD

**Issue by ehowey** [withastro/astro#8764]
### Astro Info

```block
Astro                    v3.2.3
Node                     v20.7.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Verified it is happening in Chrome and Safari.

### Describe the Bug

I created some custom animations (using motion one) for the header on my website which you can view here:

- https://erichowey.dev/ (without ViewTransitions)
- https://github.com/ehowey/erichoweydev
- https://github.com/ehowey/erichoweydev/pull/39 (PR with View Transitions added)
- https://deploy-preview-39--erichoweydev.netlify.app/ (Preview with the the bug present)

I tested out the ViewTransitions API and added it to my `<head>` in a root layout component I have. Nice work on this by the way!

The ViewTransitions API appears to affect the other animations on the page after scrolling or navigating. The animations work correctly at first and then they seem to "freeze" an no longer work. To reproduce the bug scroll or move around the page a bit and notice how the fade/scale animations in the header stop working after navigating between pages and it overlaps the text. I believe this is probably some kind of interaction between the ViewTransitions API and my own animations. 

### What's the expected result?

All other page animations continue to work as intended.

### Link to Minimal Reproducible Example

https://github.com/ehowey/erichoweydev/pull/39

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ehowey** [comment]
Wow that was fast work! Thank-you!

**Comment by martrapp** [comment]
As you can see from #8767, your issue had quite a history. Glad if I could help quickly :)
