### ISSUE TITLE
Server Renderer's check(tag) doesn't work against elements rendered via `set:html`

### ISSUE THREAD

**Issue by LefanTan** [withastro/astro#8769]
### Astro Info

```block
Astro                    v3.0.8
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/vue
                         astro-icon
                         custom-elements-ssr
                         post:build
```

### Describe the Bug

I have a custom integration that renders custom elements during SSR
```
async function check(tag) {
  return !!customElements?.get?.(tag);
}
```

`<custom-img />` Component
```
export class CustomImg extends HTMLElement {
  constructor() {
    super();
  }

  connectedCallback() {
    this.innerHTML = `
    <picture >
      <img />
    </picture>
  `;
  }
}
```
----------

With the above component as an example, the following code will be rendered correctly into `<picture ><img /></picture>` during SSR

`<custom-img src="https://fastly.picsum.photos/id/476/200/300.jpg?hmac=_vE--dw3keZ1r73AbtN9I362ItgpZJkRbRrJsB688Kw"/>`

but not via the following example
`<div set:html={"<custom-img src='https://fastly.picsum.photos/id/476/200/300.jpg?hmac=_vE--dw3keZ1r73AbtN9I362ItgpZJkRbRrJsB688Kw'/>" }/>`

Because I'm using marked JS to render html during SSR, `set:html` is required for some cases and I'm guessing that markups in `set:html` didn't get picked up by `check(tag)` because it happens after the server render step? How can i correctly trigger `check(tag)` for elements that's created via `set:html`?

### What's the expected result?

Elements set via `set:html` should be picked up by the renderer.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-phgfus?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
I'm not sure if this a bug. set:html is supposed to not process the input in any way. https://docs.astro.build/en/reference/directives-reference/#sethtml

If you think there should be a new API for your integration, you are welcome to start a discussion on [withastro/roadmaps](https://github.com/withastro/roadmap/discussions).
