### ISSUE TITLE
ViewTransition overrides html attributes when attributes are dynamically added during client-side

### ISSUE THREAD

**Issue by sor4chi** [withastro/astro#8770]
### Astro Info

```block
Astro                    v3.2.3
Node                     v18.16.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

`<html>` attributes are overridden by `data-astro-transition` when page transition execute

### What's the expected result?

attributes of `<html>`  should not be overridden with `data-astro-transition` whether attributes are dynamically added client-side or static one

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mfkf3c

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @sor4chi, thanks for your minimal reproducible example.
After view transitions, the attributes of the `html` element are set to the values provided by the target page html file + data-astro-* attributes required for the transition animation. You cant opt out from the latter. 
If your page sets those attributes dynamically, it must set them again after the transition.
Use the `astro:after-swap` event to hook in: https://docs.astro.build/en/guides/view-transitions/#astroafter-swap
