### ISSUE TITLE
bunx --bun astro add tailwind block terminal

### ISSUE THREAD

**Issue by RodrigoTomeES** [withastro/astro#8780]
### Astro Info

```block
Astro                    v3.2.3
Node                     v20.8.0
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When run `bunx --bun astro add tailwind` and you arrive to the step "Astro will generate a minimal ./tailwind.config.cjs file." the shell crashes and you can't interact with it. You can only force close.

I couldn't make a minimal reproducible example because I don't know how to change to bun in stackblitz but this are the steps:

```bash
bunx create-astro@latest my-astro-project-using-bun
bun install
bunx --bun astro add tailwind
```

### What's the expected result?

The shell not crashes.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Please report Bun issues on their repo. Astro is a Node framework.
