### ISSUE TITLE
Cannot set response status in nested components in SSR mode

### ISSUE THREAD

**Issue by darioguarascio** [withastro/astro#8789]
### Astro Info

```block
Astro                    v3.2.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

Hi, I think I found a edge case of an unexpected behavior

Case 1: you have a `Component` thatn sets `Astro.response.status = 500` , using such component directly in one page:  HTTP response status gets sent correctly 
See example at  https://stackblitz.com/edit/github-taw4vz?file=src%2Fpages%2Findex.astro
Loading the result page gives a HTTP 500 status code

Case 2: you have a `Wrapper` component that envelops the  same`Component` : in this case, the `Astro.response.status` setting gets ignored.
See example at https://stackblitz.com/edit/github-taw4vz-9zgqpj?file=src%2Fpages%2Findex.astro 
Pages returns a HTTP 200 despite `Component` setting the Astro response code

This behavior was discovered while exploring ways to handle Component errors that wouldn't invalidate the whole page rendering

### What's the expected result?

I would expect to have a HTTP 500 on request level

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-taw4vz-9zgqpj?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
This is intended behavior. See the caution above this docs section: https://docs.astro.build/en/guides/server-side-rendering/#astrocookies.

**Comment by darioguarascio** [comment]
@lilnasy thanks for pointing me to the right direction, the doc makes sense, but then I can't understand why in the first example (non-nested component) it is possible to set the response code.

My report is about inconsistency: either all components can set the status code, or none can

**Comment by lilnasy** [comment]
The inconsistency exists because there's needs to be a way to set status codes. At the same time, astro shouldn't have to wait for every component to run before sending the status code.
