### ISSUE TITLE
Throwing errors in component abruptly interrupts page rendering

### ISSUE THREAD

**Issue by darioguarascio** [withastro/astro#8790]
### Astro Info

```block
Astro                    v3.2.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

If a SSR Component thorws an error, the page stops rendering with a `Internal server error` in place of the component, resulting in a partially rendered page.
This happens after build

Try out at https://stackblitz.com/edit/github-taw4vz?file=src%2FComponent.astro

run a `npm run build` followed by `npm run preview`
then, in preview tabl, access the `/?t=x` url to trigger the error throwing: 

 

### What's the expected result?

a whole page fault, a HTTP error code, not a partially rendered page with a HTTP 200 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-taw4vz?file=src%2FComponent.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Thanks for opening this issue. Given streaming, it's not clear what should happen when half the body is already sent to the browser.

- https://github.com/withastro/astro/issues/6900

**Comment by lilnasy** [comment]
One idea proposed by matthewp after working on that issue is this:
```astro
---
---
<Catch fallback={error => (
  <div>Oops, got this error: { error }</div>
)}>
  <SomeComponentThatMaybeThrows />
</Catch>
```

**Comment by darioguarascio** [comment]
@lilnasy a `<Catch>` component would make a lot of sense, but before thinking on how to manually handle errors, maybe giving the option to let the whole request end up in a non-200 HTTP response.

From a SEO perspective, it would be exceptionally bad to let a page be half-rendered, containing an error and having a HTTP 200 status code, something that might happen now

**Comment by lilnasy** [comment]
The status code is already sent by the time the error is thrown.

**Comment by ahmad-ali14** [comment]
I used to put all front matter in try/catch block inside the page and redirect to , and keep components down the road dumb

```
---
// page.astro
let props
try {
  // business code
  props = computeProps();
} catch(e){
     return new Response(null, {status: 500})
     // or redirect
     return new Response(null, {status: 302, Location:'/error'})
}
---

<DubmComponents {...props} />

```

I even had abstractions around that, but I moved to middlewares after astro 3.

**Comment by darioguarascio** [comment]
@ahmad-ali14 i guess is the only solution here

**Comment by lilnasy** [comment]
Since this is a feature request, roadmap discussions is a more appropriate place to discuss solutions.

Someone already started the thread very recently: https://github.com/withastro/roadmap/discussions/724.

**Comment by darioguarascio** [comment]
I found a workaround for this: switching from streaming response to buffered response by changing the output `entry.mjs` file (the `writeWebResponse` does it all)

It might be useful to have an Astro configuration option to let the user decide if to use one or the other approach. 

Leaving here my small hack

```
sed -i 's/res.writeHead(status, nodeHeaders);/let buffer = [];/' dist/server/entry.mjs
sed -i 's/res.write(chunk);/buffer.push(chunk);/' dist/server/entry.mjs
sed -i '/^  res/s/  res.end();/res.writeHead(status, nodeHeaders);res.end(Buffer.concat(buffer));/' dist/server/entry.mjs

```
