### ISSUE TITLE
Vue dynamic component is=input and slot causes hydration error.

### ISSUE THREAD

**Issue by minht11** [withastro/astro#8792]
### Astro Info

```block
Astro                    v3.2.3
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/vue
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Firefox, Safari

### Describe the Bug

Vue dynamic component with is=input causes astro hydration error, even if slot itself is empty.
```vue
<template>
  <component :is="'input'">
    <slot />
  </component>
</template>
```

### What's the expected result?

No hydration error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vc8reo?file=src%2Fcomponents%2FComp.vue,src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This seems to be a general Vue issue. We're passing the slots here: https://github.com/withastro/astro/blob/11f45b9a3216f60317e1c54bb3e6c4e9e0add342/packages/integrations/vue/client.js#L17

If I set `slots` as `undefined`, or avoid passing it completely, Vue still has the hydration mismatch. It seems like it doesn't play nice with `input` hydration in general. I'll close this for now as there isn't a way to fix it, ideally you can try to avoid putting `<slot/>` inside void elements.
