### ISSUE TITLE
Node adapter: assigning to locals in middleware causes blank 404 page in production build

### ISSUE THREAD

**Issue by mb21** [withastro/astro#8793]
### Astro Info

```block
Astro                    v3.2.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

In production build, the node server returns an empty HTML page if you assign anything at all to `context.locals` in a middleware.

Minimal example is the following `middleware.ts`:

```ts
export const onRequest = defineMiddleware((context, next) => {
  (context.locals as any).foo = undefined;
  return next();
});
```

Deleting the file `middleware.ts` fixes it.

1. Open [the stackblitz](https://stackblitz.com/edit/github-hacr1q?file=src%2Fmiddleware.ts)
2. Open your browser's network dev tools
3. hit ctrl-c in the terminal at the bottom and enter `npm install && npm run build && npm run preview`
4. wait until the page in the browser-like window is loaded, which will be blank
5. Find the 404 in your browser's network dev tools and observe that it has an empty response body

### What's the expected result?

The 404 page's body contains the HTML from `404.astro`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hacr1q?file=src%2Fmiddleware.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
The current intended usage is to assign an object to `context.locals` first.

I am going to keep this open because I think this should be reconsidered. There are big additions to middleware planned, and I imagine it would become awkward for an individual middleware. It would have to check that it is the first one trying to add to locals and assign accordingly.

**Comment by mb21** [comment]
Thanks! that actually fixes the issue!

But I would definitely consider this a bug, as it's very unexpected that things generally work, except the 404 page.

Also, this example is pretty much verbatim the example from https://docs.astro.build/en/guides/middleware/#basic-usage

**Comment by lilnasy** [comment]
Thanks for that pointer! After looking at the code, I can say that I was mistaken.

It works fine in dev mode, but there is a slight oversight for SSR as you suggest.
