### ISSUE TITLE
ERR MODULE NOT FOUND

### ISSUE THREAD

**Issue by konstantine6** [withastro/astro#8801]
### Astro Info

```block
Astro                    v3.2.4
Node                     v20.5.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

["[ERR_MODULE_NOT_FOUND]" when trying to build Astro Site. I run `npm run build`, and it gives me an error about how a module isn't found. The project fails to build. Additional error on windows

### What's the expected result?

I expected my website to be built.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ktubfm?file=src%2Flayouts%2Flayout.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your reproduction isn't public, or the link is invalid.
