### ISSUE TITLE
Astro.url.pathname does not change in UI with View Transitions

### ISSUE THREAD

**Issue by bis0072** [withastro/astro#8806]
### Astro Info

```block
Astro                    v3.2.4
Node                     v18.17.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

Astro.url.pathname does not change in UI with View Transitions. It should change the link color according to the path name. but it keeps showing the previous value until reloaded.

### What's the expected result?

---
import classNames from "classnames";
export interface Props {
  href: string;
  text: string;
}
const { href, text } = Astro.props;
---

<li>
  <a
    href={href}
    class={classNames({
      "text-indigo-700 bg-indigo-100 px-1 py-1 rounded-md":
        href === Astro.url.pathname,
      "duration-300 font-medium ease-linear hover:text-primary py-3": true,
    })}
    data-nav-link
  >
    {text}
  </a>
</li>

### Link to Minimal Reproducible Example

nil

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @bis0072 could you please provide a Minimal Reproducible Example on Github or StackBlitz so we can investigate the issue?

**Comment by bis0072** [comment]
https://stackblitz.com/edit/github-b69ue8?file=src%2Fpages%2Fforms.astro

**Comment by bis0072** [comment]
without view transitions it works fine-
https://stackblitz.com/edit/github-b69ue8?file=src%2Flayouts%2FLayout.astro

**Comment by martrapp** [comment]
Thank you very much, I will look into it.

**Comment by martrapp** [comment]
Please delete `transition:persist` from `<header class="absolute inset-x-0 top-0 z-50 py-6">` in `/src/components/NavBar.astro` and see if this meets your expectations.

**Comment by bis0072** [comment]
Yes, It is working now. Thank You. "transition:persist" is causing the issue.

**Comment by martrapp** [comment]
With `transition:persist` the NavBar from the first page was copied over to the next page, still showing the same content.

**Comment by bis0072** [comment]
But without  transition:persist now toggle buttons not working

**Comment by martrapp** [comment]
Instead of a Github issue, I would like to recommend the `#support` channel on Astro's Discord server:
https://discord.gg/astro-lounge-830184174198718474
