### ISSUE TITLE
Astro is not allowing me to import a submodule that I'm using in the @forastro/utilities package. 

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#8811]
### Astro Info

```block
Astro                    v3.2.4
Node                     v20.7.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
```

### Describe the Bug

Typescript does not infer the types for `@forastro/utilities/components`. It gives me an error 

![Screenshot forastro_utils-error](https://github.com/withastro/astro/assets/29028601/b6289a9d-5b72-48f9-b9a7-a8af695daec3)

### What's the expected result?

I was using a package called `@forastro/utilities`. The package had it's component exports set to this.

```json
"./components": {
      "import":"./dist/components/index.ts"
    }
``` 

Using `@forastro/utilities/components` was supposed to work but it doesn't 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-xrmxa9?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by louiss0** [comment]
> This works just fine for me: <img alt="image" width="685" src="https://user-images.githubusercontent.com/3019731/274515105-ebb41ef6-d4cd-475e-9c1e-f9bb8637e5cd.png">
> 
> Do you have more details you could share?

I now think it had something to do with Astro 2.9.3. It did not work on one of my projects. 
Do you know how this is affected?

**Comment by Princesseuh** [comment]
Astro 2.0 had `moduleResolution: 'node'` by default, which doesn't take `exports` into account. Astro 3 has `moduleResolution: 'bundler'` instead.

**Comment by louiss0** [comment]
> Astro 2.0 had `moduleResolution: 'node'` by default in the tsconfig presets, which doesn't take `exports` into account. Astro 3 has `moduleResolution: 'bundler'` instead.

I think this has something to do with the fact that I'm in a monorepo. I'm using a mono-repo that only installs Astro at the root of my project. The other project then share the Astro that is in the root.

**Comment by louiss0** [comment]
I just changed my "moduleResolution" to bundler it it seemed to work Why?

**Comment by Princesseuh** [comment]
Well, as I said, `moduleResolution: 'node'`, the default in Astro 2.x doesn't take into account the `exports` field in `package.json` at all.
