### ISSUE TITLE
Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by peng** [withastro/astro#8815]
### Astro Info

```block
astro: 3.2.4
node: 18.18.1
pnpm: 8.9.0
```

### If this issue only occurs in one browser, which browser is a problem?

cli

### Describe the Bug

When run `pnpm astro add react`, will error  `Unexpected token < in JSON at position 1`
I found in `dist/cli/add/index.js` file `fetchPackageJson` function, when res.status is 400, res body is ReadableStream, `res.json()` will error.

I use my company registry, It is not standard.

### What's the expected result?

Have a right message, eg: Get registry network wrong or cli have registry option

### Link to Minimal Reproducible Example

cli no link

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Thanks! As you've noticed, it seems like we need better error handling there whenever we don't get a normal 200 response.
