### ISSUE TITLE
Vercel Serverless Function Timeout

### ISSUE THREAD

**Issue by jln13x** [withastro/astro#8829]
### Astro Info

```block
Astro                    v3.3.0
Node                     v18.17.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/sitemap
                         @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

Vercel changed the default timeout to 15 seconds at the beginning of October. 
Now some of my functions are timing out.

I cant seem to find a way to actually set the `maxDuration` of my Astro Routes. 
My functions are just Astro `APIRoutes` living under `/pages/api/..`

### What's the expected result?

Being able to set the maxDuration

### Link to Minimal Reproducible Example

https://stackblitz.cm/abcd1234

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
What causes the responses to take so long?

**Comment by jln13x** [comment]
> What causes the responses to take so long?

Does it really matter? I could think of multiple use cases where I would to be able to define a longer  `maxDuration`

**Comment by lilnasy** [comment]
I think so. If it is because of some user code, then it might be better handled by user code as well.

**Comment by jln13x** [comment]
> I think so. If it is because of some user code, then it might be better handled by user code as well.

How would this need a repro?

**Comment by lilnasy** [comment]
If it is not a bug with a repro, it might be a feature request, which could benefit from an explanation of a use case, and how Astro could help.

Do you want to show a custom 504 page when the function times out?

**Comment by lilnasy** [comment]
After looking at Vercel docs, I see what you mean: [`maxDuration` is a vercel option](https://vercel.com/docs/functions/serverless-functions/runtimes#maxduration).

We do not have a way to set platform-specific configurations yet, but it is being tracked as a feature request here:
- https://github.com/withastro/roadmap/discussions/656

**Comment by lilnasy** [comment]
Since being "granular" is not necessary for `maxDuration`, it can be implemented right away!
