### ISSUE TITLE
CLI paths take the PC Root, not the project's path root.

### ISSUE THREAD

**Issue by muchisx** [withastro/astro#8831]
### Astro Info

```block
"Astro                    v3.2.2\nNode                     v18.16.0\nSystem                   Windows (x64)\nPackage Manager          npm\nOutput                   server\nAdapter                  @astrojs/vercel/serverless\nIntegrations             @custom/update-webflow-js\n                         @astrojs/tailwind\n                         @astrojs/preact\n                         @astrojs/prefetch\n                         astro-robots-txt"
```

### Describe the Bug

The Astro CLI during npm run dev is using my entire pc path for outputs, can this be modified to instead use the project's root path?

![image](https://github.com/withastro/astro/assets/34131801/87fcf6dc-b431-4303-8b5d-2626606025d6)

### What's the expected result?

I would think the project's root path is better! instead of the entire PC path !

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-n2mknz?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Seems to be the full path only on windows.

<img width="500" alt="image" src="https://github.com/withastro/astro/assets/69170106/af2301c8-fa8d-4ac6-8968-acc7729f5eee">

**Comment by lilnasy** [comment]
Thanks for looking into it!

I think either `ctx.file` or `config.root.pathname` needs URI decoding ("%20" into the space character.)

If that is the case, I would expect the full path to appear when there are special characters in the path on any OS.

**Comment by florian-lefebvre** [comment]
I have also the same thing right now with no space nor special character in the path, not sure to understand what you mean 🤔

**Comment by lilnasy** [comment]
Nevermind, it's not that. When pathname is read from a URL object (config.root in this case), it starts with a forwards slash, which prevents replace's pattern from matching.

<img width="500" alt="image" src="https://github.com/withastro/astro/assets/69170106/2c4e196b-2be5-4dc6-8d6c-30fb2ec460c7">

**Comment by lilnasy** [comment]
...in addition to the undecoded URI.
<img width="500" alt="image" src="https://github.com/withastro/astro/assets/69170106/828f5b7e-0393-4224-a8c4-31dacfde4c7c">

**Comment by florian-lefebvre** [comment]
Not sure where to look then 🤔, I'm not familiar enough with the codebase

**Comment by lilnasy** [comment]
@florian-lefebvre You already got it actually. The `hmr.ts` line you linked is the appropriate place. You might find `fileUrlToPath` function from `"node:url"` helpful.
