### ISSUE TITLE
shadcn/ui library causes errors

### ISSUE THREAD

**Issue by jacobthesheep** [withastro/astro#8835]
### Astro Info

```block
Astro                    v3.3.0
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

When setting `experimentalReactChildren` to `true` it causes this error and ends the dev session.
![error](https://github.com/withastro/astro/assets/44789941/f23f963b-c6d4-435b-8104-ae647f60011b)
Without `experimentalReactChildren` and trying to use the `Accordian` component is causes this error.
![accordian](https://github.com/withastro/astro/assets/44789941/eee0a79b-8115-4d69-9a95-04964f4fff10)

### What's the expected result?

No error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-q2hjvn?file=package-lock.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by xstevenyung** [comment]
I think for multiple-part components from `shadcn/ui` (or any UI library), you need to put the code into an island. behind the scene, radix / shadcn/ui rely on React Context which cannot work directly inside Astro files.

working example: https://stackblitz.com/edit/github-q2hjvn-2ow4sj?file=src%2Fpages%2Findex.astro

**Comment by jacobthesheep** [comment]
> I think for multiple-part components from `shadcn/ui` (or any UI library), you need to put the code into an island. behind the scene, radix / shadcn/ui rely on React Context which cannot work directly inside Astro files.
> 
> working example: https://stackblitz.com/edit/github-q2hjvn-2ow4sj?file=src%2Fpages%2Findex.astro

Thanks!
