### ISSUE TITLE
Rollup assetFileNames

### ISSUE THREAD

**Issue by proyb6** [withastro/astro#8837]
### Astro Info

```block
`assetFileNames` caused CSS not generate when I ran the build process as follow on this guide.

https://docs.astro.build/en/guides/configuring-astro/#customising-output-filenames

You can replicate the test in your local machine with the code example from Astro doc.
```

### Describe the Bug

CSS is again appear under `/server/mycss.css` instead of `/client`, previously it happened once and was fixed.

### What's the expected result?

Should be residing in `/client` folder.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by proyb6** [comment]
And `entryFileNames is storing all .mjs in `client` folder, In any relative URL such as `/faq/`, `/
/page2/`, etc. `.mjs` will load from relative path (file not found) instead of absolute path.

`entryFileNames: 'entry.[hash].mjs',`

This seem, there is a need to rework on rollup customisation.

**Comment by lilnasy** [comment]
Thanks for reporting. Unfortunately, a reproduction is necessary to find out what the issue is.
