### ISSUE TITLE
Generated srcset attribute puts the largest image on the top of the list

### ISSUE THREAD

**Issue by bbbbaum** [withastro/astro#8839]
### Astro Info

```block
Astro                    v3.3.0
Node                     v18.15.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Srcset attribute gets the largest image's source on the top of the list, causing the largest image to load all the time, regardless of the specified parameters.

Example:

for the following Picture component:

```
<Picture
  src={entry.data.image}
  alt={entry.data.imageAlt}
  loading="eager" 
  sizes="(max-width: 448px) 400px, (max-width: 810px) 750px, 1050px"
  **widths={[150, 450, 750, 1050, 1350]}**
  formats={['avif', 'webp']}
  fallbackFormat="jpg"
/>
```

Astro generated the following srcset attribute:

srcset="
  **_/pics/benhamin-labatut-kada-prestanemo-da-razumemo-svet.d1f84f2b_ZneUiD.avif ,_** 
  /pics/benhamin-labatut-kada-prestanemo-da-razumemo-svet.d1f84f2b_2rz9Rf.avif 150w, 
  /pics/benhamin-labatut-kada-prestanemo-da-razumemo-svet.d1f84f2b_15nu5x.avif 450w, 
  /pics/benhamin-labatut-kada-prestanemo-da-razumemo-svet.d1f84f2b_ZgNaGa.avif 750w, 
  /pics/benhamin-labatut-kada-prestanemo-da-razumemo-svet.d1f84f2b_d9vyo.avif 1050w, 
  /pics/benhamin-labatut-kada-prestanemo-da-razumemo-svet.d1f84f2b_ZxJo9o.avif 1350w"

This causes the image on top of the source list (which happens to be the largest one) to be loaded every time in every screen width, defeating the purpose of srcset.

### What's the expected result?

I guess that having this kind of entry at the top is an error unless there is some other use case or I'm misunderstanding the feature?

In the minimal reproducible example link I compared Astro's Picture component output with a "manually" created picture element so that the desired outcome can be observed.

### Link to Minimal Reproducible Example

https://flourishing-souffle-008245.netlify.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Ah yes, probably a change I made for densities (where having no descriptors causes it to be considered 1x) that crept in `widths`. Sorry for the inconvenience, I'll get this fixed on Monday.
