### ISSUE TITLE
Cannot pass imported types to Vue macros

### ISSUE THREAD

**Issue by MellKam** [withastro/astro#8845]
### Astro Info

```block
Astro                    v3.3.0
Node                     v20.5.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/vue
 error   Command failed: which xclip
  File:
    /workspaces/workspace/node_modules/astro/dist/cli/info/index.js:38:20
  Code:
    37 |   } else {
    > 38 |     const output = execSync("which xclip", { encoding: "utf8" });
         |                    ^
      39 |     if (output[0] !== "/") {
      40 |       return;
      41 |     }
```

### Describe the Bug

As from version 3.3 Vue supports imported types in macros 
https://blog.vuejs.org/posts/vue-3-3#imported-and-complex-types-support-in-macros

```ts
// props.ts
export type Props = { foo: string };
```

```vue
// Component.vue
<scirpt setup lang="ts">
import type { Props } from "./props"

defineProps<Props>()
</script>

<template>
  {{ $props.foo }}
</template>
```

But when I run this in Astro I get: `TypeError: Cannot read properties of undefined (reading 'sys')`

### What's the expected result?

The result should be the same as when declaring a type directly in generic

```vue
// Component.vue
<scirpt setup lang="ts">
defineProps<{ foo: string }>()
</script>

<template>
  {{ $props.foo }}
</template>
```

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/elated-shape-vjxqpg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
This is an unhelpful error message from `@vitejs/plugin-vue`. The issue is that typescript is expected to be installed, but it isn't.
- https://github.com/vitejs/vite-plugin-vue/issues/181

Fix:
```diff
"dependencies": {
    "astro": "latest",
    "@astrojs/vue": "latest",
    "vue": "latest",
+   "typescript": "latest"
},
```

**Comment by MellKam** [comment]
Wow, I wouldn't have even thought of that. Thanks for reply!
