### ISSUE TITLE
Can't access the window object in client:visible components

### ISSUE THREAD

**Issue by sasoria** [withastro/astro#8849]
### Astro Info

```block
Astro                    v3.3.0
Node                     v18.15.0
System                   macOS (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### Describe the Bug

I can't seem to access the window object in `client:visible` components. Unlike in `client:only` components, it throws this error:

```
error   window is not defined
Hint: Browser APIs are not available on the server.

If the code is in a framework component, try to access these objects after rendering using lifecycle methods or use a `client:only` directive to make the component exclusively run on the client.

See https://docs.astro.build/en/guides/troubleshooting/#document-or-window-is-not-defined for more information.
```

A workaround is to either use import.meta.env.SSR or something like useEffect (see the stackblitz link for examples).  

### What's the expected result?

I'm not sure if this is working as intended, but I would expect it to be possible to use the `window` object in client components (like I can in `client:only` components).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wsphny-ve5wre?file=src%2Fcomponents%2FReactComponent.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is working as intended. `client:visible` components run on the server where there is no `window`. So you need to make sure that any code that uses the window runs only in the client. Your example shows how to do that, but checking `import.meta.env.SSR`.
