### ISSUE TITLE
react: context + hmr bug (`context is undefined` while being a sibling of a `context.Provider`)

### ISSUE THREAD

**Issue by bigmistqke** [withastro/astro#8851]
### Astro Info

```block
Astro                    v3.3.1
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### Describe the Bug

https://github.com/withastro/astro/assets/10504064/8d19069b-e07b-4925-bec7-1e435452ee3b

steps to reproduce:
1. npm create astro
2. npx astro add react
3. create simple react-component with 1 root-element with a context-provider and 2 simple components, 1 inside the same file and another imported from another file:
```tsx
// components/test

export const rootContext = createContext<{hello: string} | undefined>(undefined);

export default () => {    
  return <rootContext.Provider value={{hello: 'world'}}>
    <DoesGetContext/>
    <DoesNotGetContext/>
  </rootContext.Provider>
}

const DoesGetContext = () => {
  const ctx = useContext(rootContext);
  console.log('ctx in DoesGetContext: ', ctx);
  return <></>
}

// components/DoesNotGetContext
export const DoesNotGetContext = () => {
  const ctx = useContext(rootContext);
  console.log('ctx in DoesNotGetContext: ', ctx);
  return <></>
}
```
4. start dev-server and open localhost
5. look at console:
- `ctx in DoesGetContext: {hello: world}` 
- `ctx in DoesNotGetContext: {hello: world}` 
6. do something to cause hmr, p.ex add `console.log('hallo')` in the root-component
7. look at console:
- `ctx in DoesGetContext: undefined` 
- `ctx in DoesNotGetContext: undefined`  
9. refresh page
10. look at console:
- `ctx in DoesGetContext: {hello: world}` 
- `ctx in DoesNotGetContext: undefined`  
11. refresh page
12. look at console:
- `ctx in DoesGetContext: {hello: world}` 
- `ctx in DoesNotGetContext: undefined` 

temporary fix: 
I was unable to reproduce the bug if I declare the context in its separate file, p.ex `components/context`, and then import it in both `components/test` and `components/DoesNotGetContext`.

### What's the expected result?

the expected result is that context is always defined as long as the components are siblings of a context.Provider

### Link to Minimal Reproducible Example

https://github.com/bigmistqke/astro-react-context

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
It seems like a limitation of hot module reloading. The module gets reloaded, including the context created within it, resulting in multiple contexts.

<img width="700" alt="image" src="https://github.com/withastro/astro/assets/69170106/6832b253-1b7c-48aa-99dc-2f2189bd5814">

Either way, I don't think this is related to Astro. I would expect the same behavior in a Vite project with this arrangement of modules. If that is not the case, feel free to reopen this issue.
