### ISSUE TITLE
Global CSS Variables declared with is:global inside components are not working

### ISSUE THREAD

**Issue by ZeldOcarina** [withastro/astro#8855]
### Astro Info

```block
Astro                    v3.3.1
Node                     v18.15.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When I try to add global css variables from inside a component using `is:global` and `define:vars`, these fail, while if I do the same in the `<Layout> ` component, it works correctly.

To achieve the same result I need to use a `Fragment` with `set:html`, which is a little strange.

I've created a reproduction repo that showcases the bug by using both approaches inside `GlobalStyles.astro` and `Layout.astro` and how the styles are applied or not both in `global.css`and inside the `Square`component.

As you can see both the `Fragment` `set:html` and the `Layout` styles are applied but the `is:global` styles inside `GlobalStyles.astro` are failing.

I need this behavior to work to be able to share the same css variables setup across a big monorepo with many different themes.

### What's the expected result?

All three approaches should work.

### Link to Minimal Reproducible Example

https://github.com/ZeldOcarina/astro-css-vars-bug

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ZeldOcarina** [comment]
![image](https://github.com/withastro/astro/assets/42982095/a83a66e1-d03c-4a0a-b9d1-d4ee9a770bc2)
Behavior confirmed in production built version too.

**Comment by lilnasy** [comment]
The issue might be that define:vars is unintuitive.

```astro
---
const x = "2rem"
---
<style define:vars={{ x }}>
    div { width: var(--x) }
</style>
<div></div>
```
... is syntax sugar for ...
```astro
---
const x = "2rem"
---
<style>
    div { width: var(--x) }
</style>
<div style={`--x: ${x}`}></div>
```
Notice that the stylesheet remains verbatim. The variable goes to the topmost html element. It works in your layout because the topmost element there is `<html>`. In your component, it has no element to which it can attach the variables.

I would recommend adding the inline style attribute manually. It often ends up less work in addition to involving no magic at all!

**Comment by ZeldOcarina** [comment]
I see the css variables are just lost then if the component does not include any HTML element but the style tag only.
May attaching the variables to the parent be an option if this is the case?

> I would recommend adding the inline style attribute manually. It often ends up less work in addition to involving no magic at all!

So here you are suggesting to use the Fragment approach with `set:html` that I used in the repro?

**Comment by lilnasy** [comment]
If it works, it works. But a simpler approach might be writing out the style attribute like the lower code block from my previous comment shows. Depending on your use case, it might be even simpler to create a `globals.css` with all your design tokens.

**Comment by lilnasy** [comment]
You are welcome to start a roadmap discussion if you think define:vars could work in a better way.

https://github.com/withastro/roadmap/discussions
