### ISSUE TITLE
CSS removed during View Transitions in React Components

### ISSUE THREAD

**Issue by bitzky** [withastro/astro#8856]
### Astro Info

```block
Astro                    v3.3.1
Node                     v18.17.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### Describe the Bug

When using ViewTransitions with React components, the CSS is removed after transition.

If you reload the page, the css get's applied again.

### What's the expected result?

The CSS should be still applied after transition.

I my example there should be still a big red div after clicking "Go to next page".

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pcyjcb

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JerryWski** [comment]
This problem is also on chrome browsers

**Comment by matthewp** [comment]
Fixed by https://github.com/withastro/astro/pull/8840
