### ISSUE TITLE
Custom env var not available in MDX

### ISSUE THREAD

**Issue by alexandremottet** [withastro/astro#8857]
### Astro Info

```block
Astro                    v3.3.1
Node                     v20.5.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

I try to use custom env var define in the file `.env` in both `.astro`, `md` and `.mdx`.
The custom environment variable is accessible in `.astro` file but not in the `.mdx` file.

I think it should be accessible as I have access to the other variables provided by Astro and Vite.

### What's the expected result?

I should be able to access custom environment variable in any extension.
I don't know about `md` if there is a templating replace system in place but it should work at least on `mdx`.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/white-thunder-n56g9p

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I tested with Astro 4 and it seems to work now. I'm guessing it's related to the Vite 5 update. It not working in Markdown is expected for now as `import.meta.env.*` is a JS specifier, and Markdown only contain plain string/html. I'll close this as fixed for now.
