### ISSUE TITLE
Partytown breaks VT fallback

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#8862]
### Astro Info

```block
Astro                    v3.3.2
Node                     v18.14.1
System                   Windows (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/partytown
```

### Describe the Bug

When creating a partytown script and navigating to a new page in an unsupported browser (like firefox), VT breaks: url is not updated, event listeners are not triggered etc but page swaps. See video.

![image](https://github.com/withastro/astro/assets/69633530/4bc66997-3318-4ecb-b285-ccb64bfcc4a1)

https://github.com/withastro/astro/assets/69633530/1fdfd8c6-fc04-447b-bb69-755d8bce3b31

### What's the expected result?

Shouldn't break

### Link to Minimal Reproducible Example

https://github.com/florian-lefebvre/astro-vt-fallback-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Help wanted! Obviously the minimal example does not work for @florian-lefebvre, but I was not able to reproduce the error with Firefox. Who can help to identify the source of this behavior?

**Comment by lilnasy** [comment]
I can reproduce the issue. I could take a closer look later this week.


https://github.com/withastro/astro/assets/69170106/fb16a206-39e0-4a0b-9e9f-5af91f76f45a

**Comment by lilnasy** [comment]
Affects firefox only, not Safari.

**Comment by alan-barzilay** [comment]
I also got the same issue, firefox + partytown + VT

**Comment by lilnasy** [comment]
This one might be hard to debug. The Firefox-specific error does not provide a stacktrace. I'm pretty sure it has to do with Partytown's usage of low-level APIs (Atomics, SharedArrayBuffer) that exposes a memory-management bug in Firefox, but there is no straightforward way to confirm.

**Comment by lilnasy** [comment]
Workaround: turn off minification.
```diff
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';

import partytown from "@astrojs/partytown";

// https://astro.build/config
export default defineConfig({
  site: 'https://example.com',
  integrations: [mdx(), sitemap(), partytown()],
+ vite: {
+   build: {
+     minify: false
+    }
+  }
});
```

**Comment by florian-lefebvre** [comment]
Do you think it's worth opening an issue usptream or is it really caused by Astro?

**Comment by lilnasy** [comment]
> Do you think it's worth opening an issue usptream or is it really caused by Astro?

I'm not sure yet. Since, view transitions are necessary for it to break on Firefox, there might be a fix possible on Astro's side. Just as long as it's not too drastic.

**Comment by lilnasy** [comment]
Using a build of partytown with minification turned off pointed me to a single line. It runs whenever the History API is used. It seems like an issue for Firefox to fix, although Partytown may be able to find a workaround. Astro's usage of history API is necessary and proper. 
<img width="600" alt="image" src="https://github-production-user-asset-6210df.s3.amazonaws.com/69170106/277794924-03cd7409-381e-40f8-928c-1f92e859167a.png">

**Comment by lilnasy** [comment]
Reducing priority only because it is a signal astro maintainers use to pick up issues. This is not something for them to fix.

**Comment by emish89** [comment]
I created the bug here, maybe this can help: 
https://github.com/BuilderIO/partytown/issues/505

**Comment by lilnasy** [comment]
- An issue has already been open for a month: https://github.com/BuilderIO/partytown/issues/486

**Comment by matthewp** [comment]
Might be able to prevent it by stopping Partytown from highjacking pushState, going to give that a try.

**Comment by matthewp** [comment]
Looks like that will work.

**Comment by emish89** [comment]
@matthewp can you post a code snippet? 
in this way we are losing GA events, correct?

**Comment by matthewp** [comment]
@emish89 I can create a preview release for you to try. You might lose events, I'm not sure. Hopefully not.

**Comment by matthewp** [comment]
@emish89 could you try out `astro@experimental--vt-partytown` and let me know?

**Comment by emish89** [comment]
ok tomorrow I'm going to try.
I also created a PR in partytown that should solve :/
https://github.com/BuilderIO/partytown/pull/511

**Comment by matthewp** [comment]
@emish89 have you confirmed that removing the setTimeout does fix it?

**Comment by lilnasy** [comment]
It was not sufficient to prevent the failure when I tried it. It has been a while though, it's possible I missed something.

**Comment by emish89** [comment]
in my local worked, but for sure I'm not an expert of the package. If they put it, is because there was some reason...

@lilnasy do you remember what can I test to be sure if is working or not?

**Comment by lilnasy** [comment]
If firefox does not error anymore then disregard what I said. The only tests to worry about would be the ones in partytown repo.

**Comment by matthewp** [comment]
@emish89 did you get a chance to try out `astro@experimental--vt-partytown`?

**Comment by emish89** [comment]
I would say that is working, for sure is not breaking, but I'm not 100% sure if is sending data to GA.
I cannot install extensions to check that on firefox

**Comment by matthewp** [comment]
Ok, I'm going to suggest that we go with this then. The most important thing is that page navigation is not broken. If Partytown is causing it to be so, then the priority should be for us to avoid that.

**Comment by emish89** [comment]
> Ok, I'm going to suggest that we go with this then. The most important thing is that page navigation is not broken. If Partytown is causing it to be so, then the priority should be for us to avoid that.

totally understandable and I agree. I confirm that in my case is now not breaking with this version.
