### ISSUE TITLE
RSS file not generated on static build

### ISSUE THREAD

**Issue by xypnox** [withastro/astro#8864]
### Astro Info

```block
Astro                    v3.2.2
Node                     v18.15.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
                         @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

After placing a basic `src/pages/rss.xml.js` with minimal content and building the astro project with `npm run build`, there is no rss file present in `dist` that should be generated.

### What's the expected result?

The rss file should be generated in the `dist` directory.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-j76eva

Here, run `npm run build` in terminal. 
Then check the `dist` folder.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
It looks like no integrations were added to the config file/

**Comment by xypnox** [comment]
Provided in the issue

**Comment by ematipico** [comment]
@xypnox your reproduction doesn't include the integration in the `astro.config.mjs`. Can you please update it?

**Comment by ematipico** [comment]
Also, your `astro info`shows that you haven't installed the integration at all. Install it and add it to your `astro.config.mjs`

**Comment by xypnox** [comment]
Hi, I am sorry for not providing the info that I was following the doc: [[Add an RSS feed 🚀 Astro Documentation](https://docs.astro.build/en/guides/rss/)](https://docs.astro.build/en/guides/rss/)

And it has no step of configuring it in `astro.config.mjs`. Moreover `rss` that is exported from the package cannot be configured in the `astro.config.mjs`.

```js
import { defineConfig } from 'astro/config';
import rss from '@astrojs/rss';

// https://astro.build/config
export default defineConfig({
  site: 'https://xypnox.com',
  integrations: [rss()], // throws error
});
```

**Comment by xypnox** [comment]
Also the associated package readme provides no such instruction on configuring the plugin in `astro.config.mjs`, https://github.com/withastro/astro/tree/main/packages/astro-rss.

**Comment by xypnox** [comment]
Bumping this again as IMO the issue is still unresolved. I couldn't get the RSS feed to work.

**Comment by lilnasy** [comment]
`@astrojs/rss` is a normal library, `@astrojs/sitemap` is the integration. You probably want the second one. You would add it to your project by running `astro add sitemap` as described here: https://docs.astro.build/en/guides/integrations-guide/sitemap/. Hopefully, that helps you with your project or with creating a reproduction. If not, feel free to seek help in our discord: https://docs.astro.build/en/guides/troubleshooting/#need-more.

**Comment by xypnox** [comment]
I do know and use the sitemap feature, but it doesn't generate the RSS feed. I wanted to generate the RSS feed. Also why does `@astrojs/rss` not work?

**Comment by lilnasy** [comment]
I am sorry, it was a misunderstanding on my part. I was incorrectly expecting the sitemap integration to be involved in the issue. When I noticed it wasn'tin the config file, I jumped to the conclusion that the repro was incomplete. I guess I got lost because both deal with XML, but you were right every step of the way!

Regard the real issue, it is because the endpoint handler function is called `get` (lowercase) but since 3.0, Astro expects `GET` (uppercase). So, Astro basically sees and endpoint with no handler functions in it.

https://docs.astro.build/en/guides/upgrade-to/v3/#changed-http-request-methods-case

**Comment by xypnox** [comment]
I tried `GET` instead of `get` but could not generate the rss file in `dist` after `astro build`. 

Ref: [Stakblitz](https://stackblitz.com/edit/github-j76eva?file=src%2Fpages%2Frss.xml.js)

**Comment by lilnasy** [comment]
It changed from `get` to `default`, not `GET`.

**Comment by xypnox** [comment]
Thanks the rss.xml.js that finally worked was:

```js
import rss from "@astrojs/rss"
//import { getCollection } from 'astro:content';

export async function GET(context) {
  const blog = await getCollection('blog');
  return rss({
    title: "Blag",
    description: "To muse over the words unmusable.",
    site: context.site,
    items: [],
  })
}

```

**Comment by lilnasy** [comment]
Glad it worked out. If you run into an issue again, you would likely get faster responses on discord.

Good luck!
