### ISSUE TITLE
Content collections doesn't allow `.strict()`

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#8871]
### Astro Info

```block
❯ pnpm astro info

Astro version            v2.10.15
Package manager          pnpm
Platform                 darwin
Architecture             arm64
Adapter                  Couldn't determine.
Integrations             @astrojs/react, @astrojs/image, @astrojs/mdx, my-global-css, @astrojs/sitemap
```

### Describe the Bug

Discord context: https://discordapp.com/channels/830184174198718474/872579324446928896/1162124756213059594

@delucis describes the problem well:

> `z.object({ foo: z.string() }).strict()` will throw if it finds a slug in frontmatter.
> But `z.object({ foo: z.string(), slug: z.string().optional() }).strict()` will also throw, because Astro doesn’t led you add slug to your own schema

I would suggest adding an additional custom schema provided by the `defineCollection` callback, similar to the `image` schema: `({ image, slug }) => {`

It would default to `slug: z.string().optional()`, but would allow the end user to then append `.refine()` and other steps to the schema to ensure a stricter shape of their slugs, like `/YYYY-MM-DD/lowecase_title_with_underscores` as a pattern.

Then loosening the astro requirement of "no slug schemas" to "only the astro built slug schema w/ refinements is allowed" which would enable setting `.strict()` on the collection schema

### What's the expected result?

I would expect that I can set `.strict()` on my content collection schemas, and that they will not error with "unexpected key `slug` found", since Astro currently prevents me from setting a `slug` property key in my content collection.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wtddxv?file=src%2Fcontent%2Fposts%2Ftest.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by aripalo** [comment]
Having access to the slug through `ctx: SchemaContext` would be useful for other use cases as well. For example, I have files (for example images) stored next to the actual blog post (i.e. in the same folder as the `.mdx` files): Having access to the slug in content collection schema definitions would mean that I could process these files "centrally" on the content collection and transform them (in whatever way) into the front matter.

**Comment by bholmesdev** [comment]
Well, I've sat on this issue for a while haven't I... investigating now!

**Comment by bholmesdev** [comment]
That was fast... We were passing the `slug` to the user schema by accident due to bad variable naming 🤦
