### ISSUE TITLE
Integration API: no way to directly inject server-side function within frontmatter

### ISSUE THREAD

**Issue by jkhaui** [withastro/astro#8874]
### Astro Info

```block
Astro                    v3.3.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  none
Integrations             test-plugin
```

### Describe the Bug

I'm building a basic Astro plugin which integrates a 3rd-party library (`react-navigation`). This is an isomorphic package which does some dodgy things with global vars, thus as part of this integration I want to run a function which resets the global Node context.

This function should exist—and be executed—from within the frontmatter of every page (i.e. on the initial page load + any subsequent page loads, the function should run within the scope of the Node server environment).

Below is a snippet to demonstrate what I mean and I've also included a minimal repro on Stackblitz.

```
---
// given the file [...slug].astro
// imports & other frontmatter code
// ...

// IIFE which successfully executes if manually added to frontmatter
(() => {
    global["__react_navigation__elements_contexts"] = new Map();
})();
// when the above function is present, terminal logs confirm that global context has been successfully reset
console.log(global["__react_navigation__elements_contexts"], "__SERVER__")
---
```

I've been following the guide from the [official docs](https://docs.astro.build/en/reference/integrations-reference/#injectscript-option) but the `page-ssr` doesn't work. Neither does adding the function as an inline script within the document's head.

Just to reiterate once more: the script **does** work as expected if I manually add it to the frontmatter, but for this purpose, I want the functionality to come from an Astro plugin.
My guess is maybe the script's module scope prevents it from accessing/modifying Node's globals.

### What's the expected result?

Astro's integrations API should expose an option to inject and execute server-side code directly within a page's frontmatter (i.e. not _only_ from an imported file/module).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yxnawg?file=src%2Ftest-plugin.ts,src%2Fpages%2F[...slug].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

edit: realised this code doesn't even need to be scoped within its own function (i.e. can just set `global["__react_navigation__elements_contexts"] = new Map();` directly), but regardless, this still doesn't do anything when injected from a plugin.

**Comment by lilnasy** [comment]
It works as you say it should.
<img width="500" alt="image" src="https://github-production-user-asset-6210df.s3.amazonaws.com/69170106/277824219-e7302e0d-13e6-4ffe-befa-1e13371c95f4.png">

Feel free to reopen if you still think there is an issue.
