### ISSUE TITLE
@astrojs/vue Can't find vite module with use latest yarn

### ISSUE THREAD

**Issue by kogeletey** [withastro/astro#8882]
### Astro Info

```block
Astro                    v3.3.2
Node                     v20.5.1
System                   Linux (x64)
Package Manager          yarn@3.6.3
```

### Describe the Bug

  When using the latest yarn package manager,  and pnpm settings for modules resolutions  the following error appear
```
Error when evaluating SSR module /workspaces/workspace/astro.config.mjs: failed to import "@astrojs/vue"
|- Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /workspaces/workspace/node_modules/.store/@vitejs-plugin-vue-virtual-57f61a4b96/node_modules/@vitejs/plugin-vue/dist/index.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:782:9)
    at moduleResolve (node:internal/modules/esm/resolve:831:20)
    at defaultResolve (node:internal/modules/esm/resolve:1036:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:251:12)
```
  
 I haven’t tested it with other modules except Vue. When using the `node-modules` setting, everything works fine.

### What's the expected result?

I hope that the error can be fixed somehow

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/goofy-tree-yx5r5k

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Removing the `.codesandox` folder from the repro gets the project to run. Not sure which step causes the issue, but evidently it is not related to Astro.

**Comment by kogeletey** [comment]
Please look into the problem carefully. It's not about `.codesandbox` folder, it just automatically start the server. The problem is that yarn does not find the vitejs plugin in pnpm mode.

**Comment by lilnasy** [comment]
Yes, removing `.codesandbox` folder and restarting allows vite to work properly.

**Comment by kogeletey** [comment]
You can build the same thing on your local machine and try to run the dev server.
 Of course, if you delete the codesandbox folder, the error will disappear.But the dev server won’t work.

**Comment by lilnasy** [comment]
Seems like I accidentally deleted the codesandbox I linked earlier. This one shows dev and build working fine and the difference is the removed codesandbox folder.

https://codesandbox.io/p/sandbox/cocky-sanne-gc4tq8

It might be an issue for yarn to fix, but there is nothing to be done from Astro's side.

**Comment by kogeletey** [comment]
Yes, I’ll contact yarn, but the link uses yarn v1, which does not correspond to the originally specified version of yarn - and you probably know that they are radically different.
