### ISSUE TITLE
Alllow setting limitInputPixels with Sharp

### ISSUE THREAD

**Issue by orf** [withastro/astro#8886]
### Astro Info

```block
Astro                    v3.3.2
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/preact
                         @astrojs/tailwind
```

### Describe the Bug

I have a large image that I would like to embed in one of my pages.

Locally this fails with:

```
Server Error: Error: Input image exceeds pixel limit
```

Which is related to https://github.com/lovell/sharp/issues/2373

In the sharp image service here https://github.com/withastro/astro/blob/d5dc5ce04acd19d9c9b7a29c2519408f6bdc3b83/packages/astro/src/assets/services/sharp.ts#L46 there is not  away to add `limitInputPixels: false` to the sharp constructor.

### What's the expected result?

I should be able to add `limitInputPixels: false` to the sharp constructor

Note: I can't upload the gif to the stackblitz editor, so the example below has the image link embedded directly in it. This does not work - you need to copy it locally.

The full gif can be found here: https://tomforb.es/visualizing-how-s3-deletes-1-billion-objects-with-athena-and-rust/animation_5.gif

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-arpawb?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
I'd be okay with adding this to `image.service.config` somehow (maybe `sharpImageService` from `astro/config` could take a param to set a config), this is an easy enough

**Comment by DerTimonius** [comment]
I would like to work on this, please 🙂

**Comment by lilnasy** [comment]
I am getting a different error.
![image](https://github.com/withastro/astro/assets/69170106/0bbbdc57-caa7-4ced-996b-33454271c6ee)

Fixed by adding `jsx: preseve` to `tsconfig.json`.

**Comment by lilnasy** [comment]
What do you think the API would look like?
