### ISSUE TITLE
Base npm run dev is broken

### ISSUE THREAD

**Issue by Christopher-Law** [withastro/astro#8891]
### Astro Info

```block
Astro                    v3.3.2
Node                     v20.6.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Terminal

### Describe the Bug

After installing a fresh Astro project and attempting `npm run dev`
```
Object.defineProperty(exports, "File", {
       ^

TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
```

### What's the expected result?

The dev server to spin up and function. 

### Link to Minimal Reproducible Example

.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
The Node version you're using had a regression that broke many packages. Upgrading (or downgrading) should fix it.

**Comment by Christopher-Law** [comment]
Thank you.
