### ISSUE TITLE
Remote Images are not resized when using relative path in `src`

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [withastro/astro#8894]
### Astro Info

```block
Astro                    v3.3.3
Node                     v21.0.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/solid-js
                         @astrojs/tailwind
                         @astrojs/prefetch
 error   Command failed: which xclip
  File:
    /var/www/public_html/node_modules/.pnpm/astro@3.3.3/node_modules/astro/dist/cli/info/index.js:38:20
  Code:
    37 |   } else {
    > 38 |     const output = execSync("which xclip", { encoding: "utf8" });
         |                    ^
      39 |     if (output[0] !== "/") {
      40 |       return;
      41 |     }
  Stacktrace:
Error: Command failed: which xclip
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at copyToClipboard (file:///var/www/public_html/node_modules/.pnpm/astro@3.3.3/node_modules/astro/dist/cli/info/index.js:38:20)
    at printInfo (file:///var/www/public_html/node_modules/.pnpm/astro@3.3.3/node_modules/astro/dist/cli/info/index.js:28:9)
    at async runCommand (file:///var/www/public_html/node_modules/.pnpm/astro@3.3.3/node_modules/astro/dist/cli/index.js:69:7)
    at async cli (file:///var/www/public_html/node_modules/.pnpm/astro@3.3.3/node_modules/astro/dist/cli/index.js:144:5)
```

### Describe the Bug

Images are not resized when you use a local image using an URL instead of an import statement, it is considered as a remote image, but since the domain is the same, Astro doesn't optimize it.

Here is an exemple Astro config : 

```js
import { defineConfig } from 'astro/config';
import node from '@astrojs/node';

// https://astro.build/config
export default defineConfig({
  site: 'https://example.com/',
  output: 'server',
  image: {
    domains: ['www.example.com', 'example.com'],
    protocol: 'https',
  },
  adapter: node({ mode: 'standalone' }),
  integrations: [],
});
```

Now if you run in production using this domain and try to load an image this way : 

```js
---
import { Picture } from 'astro:assets'
---
<Picture 
        src="https://www.exemple.com/image.jpg"
        alt="super image"
        widths={[256, 128]}
        sizes="(max-width: 550px) 126w, 256w"
        width={240}
        height={430}
        formats={['avif', 'webp']}
        decoding="async"
        loading="lazy"
/>
```

The image is not transform as it should.

### What's the expected result?

The image should be transformed, even if it comes from the same domain in the URL.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-xqjwat?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Tanguy-Magnaudet** [comment]
I've been mistaken by a wrong debugging process. I found what the problem was.
Absolute URL coming from the same domain works fine, something was transforming absolute URLs to relative URLs in my backend and I missed it.

I renamed the issue to match this.

However, I think relative URLs should be transformed when set as string in the `src` prop.

**Comment by matthewp** [comment]
I don't understand what you mean, where is there a relative URL? I don't see one. If you mean `src="./rel.png"`, Astro cannot resolve that, it doesn't have context of where that is coming from. Is that what you meant?

**Comment by bluwy** [comment]
Closing this for now due to lack of response.
