### ISSUE TITLE
The dynamically set tailwindcss style class name does not generate css styles

### ISSUE THREAD

**Issue by LuHugo** [withastro/astro#8905]
### Astro Info

```block
Astro                    v3.3.3
Node                     v21.0.0
System                   macOS (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

When tailwindcss is used in the project, some style names of the components will be set according to parameters, but such settings will not generate styles. For example:
```html
<!--working-->
<div class="w-96">working</div> 

<!--not working-->
<div class=`w-${80}`>not working</div>
<div class=`w-${width}`>not working</div>
```

Will work if there is a style class name that has been used before
```html
<div class="w-96">working</div> 
<!--working-->
<div class=`w-${96}`>working</div> 


<!--not working-->
<div class=`w-${80}`>not working</div>
<div class=`w-${80}`>not working</div>
```

**According to the information obtained by debugging, the dynamically set style class name has been correctly generated in the class attribute, but the corresponding style is not generated in the css file.**

### What's the expected result?

Dynamically set style class names should correctly generate css styles

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ab9min?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Tailwind does not support dynamic class names. https://tailwindcss.com/docs/content-configuration#dynamic-class-names

**Comment by LuHugo** [comment]
> Tailwind does not support dynamic class names. https://tailwindcss.com/docs/content-configuration#dynamic-class-names

Oh, this is my fault, I didn't check the tailwind documentation carefully.
