### ISSUE TITLE
Configured Redirects with more than two params don't expand properly

### ISSUE THREAD

**Issue by FredericLatour** [withastro/astro#8914]
### Astro Info

```block
Astro                    v3.3.2
Node                     v18.17.1
System                   Linux (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/mdx
                         @astrojs/react
```

#### Context
Redirects configuration in `astro.config.mjs`

Tested usint the following configuration (however certainly not limited to this configuration):
- SSR mode 
- Node adapter

#### Bug
Redirects entries with more than one param (ie: '/ov/[page]/[...user]': '/tests/ov/[page]/[...user]') don't  work.
The expansion does not take place.

#### Example:

Given the following configuration:

```javascript
export default defineConfig({
  redirects: {
    '/ov/[page]/[...user]': '/tests/ov/[page]/[...user]', // does not work
    '/ot/[...user]': '/tests/ot/[...user]',               // works
  },
  integrations: [tailwind(), mdx(), react()],
  output: "server",
  adapter: node({
    mode: "standalone",
  }),
})
```

- http://localhost:4321/ot/some-page/some-user/test 
will redirect properly to
- http://localhost:4321/tests/ot/some-page/some-user/test

**While**
- http://localhost:4321/ov/some-page/some-user/test
will redirect without expanding the params to
- http://localhost:4321/tests/ov/[page]/[...user]

### What's the expected result?

Given the configuration above,

- http://localhost:4321/ov/some-page/some-user/test
Should redirect to 
- http://localhost:4321/tests/ov/some-page/some-user/test
Instead of
- http://localhost:4321/tests/ov/[page]/[...user]

### Link to Minimal Reproducible Example
https://github.com/lilnasy/redirect-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredericLatour** [comment]
While trying to find a workaround (basically, using a single rest route), I realized that the problem was somewhat more complex than the issue would make it think.

For instance, even when a single param 'route'/'redirect config' (a rest one though) is concerned, the redirection may not work.

For instance with the following redirects configuraiton
```javascript
'/ot/old-page/[...pageuser]': '/play/ot/new-page/[...pageuser]',
```

- http://localhost:4321/ot/old-page/user/test
will redirect to
- http://localhost:4321/play/ot/new-page/[...pageuser]

Not sure how to complete, modify the issue to somewhat extend the scope of the problem.

**Comment by rishi-raj-jain** [comment]
@lilnasy 

> [http://localhost:4321/play/ot/new-page/[...pageuser]](http://localhost:4321/play/ot/new-page/%5B...pageuser%5D)
Is this a known issue with redirection? From the description it seems like there are two issues:

- redirects do not take place with both single level dynamic and nested routes
- even when redirects do take place, they fail to pass on the dynamic slug to the redirected path

**Comment by lilnasy** [comment]
Yeah, seems like it. Although the two issues may have the same cause: "..." being included in some match and replace maybe.

**Comment by lilnasy** [comment]
> While trying to find a workaround (basically, using a single rest route), I realized that the problem was somewhat more complex than the issue would make it think.

I don't think that is the case.

I think what you may be missing is the fact that the target route needs to exist for the expansion to work.

For example, for this redirect rule to expand properly...
```js
'/ot/old-page/[...pageuser]': '/play/ot/new-page/[...pageuser]',
```
...the target route named `src/pages/play/ot/new-page/[...pageuser].astro` or `.ts` needs to exist.

**Comment by nastiazhyrnova** [comment]
I think I may have similar issue (using storyblok CMS + i18n)

`'/de-de/services': '/de/services'` doesn't work, as well as `'/de-de/[...slug]': '/de/[...slug]' `, which is what I actually need
but
`'/de-de': '/de'` works
`'/': '/de'` works

**Comment by lilnasy** [comment]
@nastiazhyrnova Can you share what adapter you are using, and what your `src/pages` folder looks like? I'm specifically interested in whether a file called `src/pages/de/[...slug].astro` exists.

**Comment by nastiazhyrnova** [comment]
@lilnasy adapter is 

`  adapter:
    env.SSR === 'true'
      ? node({
          mode: 'standalone',
        })
      : undefined,`

env.SSR I tried both false and true, it doesn't change anything in this case...


Regarding the folder structure, it is actually `src/pages/[...slug].astro`, it works for both english and german versions. 
There is `src/pages/en/[...id].astro` and `src/pages/de/[...id].astro` but it is a different component for another functionality

**Comment by lilnasy** [comment]
Thanks, this really helps.
I think the workaround would be to create empty files whose name matches the redirect targets. `src/pages/de/[...slug].astro` in your case.

**Comment by nastiazhyrnova** [comment]
Hi @lilnasy I've tried it, but unfortunately it doesn't work :( Moreover, if I also remove [...slug].astro from `src/pages`, nothing works, which probably means that another [...slug].astro files are not being considered :(

**Comment by rishi-raj-jain** [comment]
@lilnasy

How about we:
- let the server handle the redirect instead of looking for files redirect to
- if available, wherever redirect resolves to, send the file else a 404

**Comment by nastiazhyrnova** [comment]
@rishi-raj-jain so far I see it as an only solution, in my case it is some middleware in Vercel, have to have a look at it

**Comment by lilnasy** [comment]
That is the plan. The logic would go here: https://github.com/withastro/astro/pull/9089#discussion_r1391508241.
To clarify, I only made the PR to help discuss the best way to refactor. Feel free to open a new one, and maybe copy the tests.

The information we have is `data = { slug: "x/y/z" }`, and `route =  "/de/[...slug]"`. The result we need is `generate(route, data) === "/de/x/y/z"`.

Normally, this generate function is already there but it comes from the target route. In this case, the target route is named differently so it is not available.

Ideally, we would refactor `routeData.generate` so that this function is not duplicated, but if there's no easy way, a simple RegExp replace in the link would get the job done too.
