### ISSUE TITLE
Slot name is being rendered as an attribute on Vue component

### ISSUE THREAD

**Issue by spacedawwwg** [withastro/astro#8921]
### Astro Info

```block
Astro                    v3.3.4
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          yarn
Output                   server
Adapter                  none
Integrations             @astrojs/vue
                         astro-purgecss
                         astro-compress
```

### Describe the Bug

When using a slot name on a Vue component, the slot name is being rendered as an attribute

something like:
```VUE
<Parent>
  <Child slot="footer" />
</Parent>
```
renders like:
```HTML
<div class="parent"> 
  <div class="parent-footer">
    <div class="child" slot="footer">I am the child</div>
  </div>
</div>
```
<img width="495" alt="image" src="https://github.com/withastro/astro/assets/1691867/e5b3c55e-8146-41fc-936c-86556b02ca0c">

### What's the expected result?

No slot attribute rendered on component

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1jemj8

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Ah, good catch, probably a quick fix, let me take a look.
