### ISSUE TITLE
A way to disable prefetch with ViewTransitions

### ISSUE THREAD

**Issue by fuwaneko** [withastro/astro#8926]
### Astro Info

```block
Astro                    v3.4.0
Node                     v20.8.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/solid-js
```

### Describe the Bug

I have an app with cookie-based authentication and a sign-out link. When ViewTransitions are enabled, hovering over the sign-out link causes the sign-out per se. There should be a way to tell Astro to disable prefetch on some links, adding "data-astro-reload" to a link doesn't prevent prefetching.

### What's the expected result?

A data attribute to disable prefetch, perhaps?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hmcjqs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
We are in the process of updating prefetch usage in general and plan to have a solution for this as part of it.

**Comment by matthewp** [comment]
An alternative is to use a `<form>` with a `POST` request. Usually you don't do mutations inside of a GET.

**Comment by bis0072** [comment]
I'm having the same issue
