### ISSUE TITLE
📘 DOC: Explain how to uses aliases in your Snowpack config like `"~": "src"`

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#893]
An example is in the docs site source:

```js
alias: {
  components: './src/components',
  '~': './src',
},
```

**Comment by brycewray** [comment]
Any reason why this doesn't work in `snowpack.config.mjs`? (Sorry if this is the wrong issue for this.)

```js
export default {
  alias: {
    public: './public',
  }
}
```

Can get other aliases to work, but not `public`; it still requires relative references. (Also tried `publicDir` in case `public` was "special"; same result.)

**Comment by sacarvy** [comment]
This issue can be closed now as we shifted to vite.js now So, we have to add docs about 

How to add aliases in vite ?

Possible answer I found on [Vue School Blog post](https://vueschool.io/articles/vuejs-tutorials/import-aliases-in-vite/) 
```js
// vite.config.js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
const path = require('path')

// https://vitejs.dev/config/
export default defineConfig({
  resolve:{
    alias:{
      '@' : path.resolve(__dirname, './src')
    },
  },
  plugins: [vue()]
})
```

**Comment by jonathantneal** [comment]
The documentation for this feature is being tracked in #1751, and the feature itself is tracked in #1749.
