### ISSUE TITLE
Property with nullish value in inline style should be omitted

### ISSUE THREAD

**Issue by MarvinXu** [withastro/astro#8933]
### Astro Info

```block
Astro                    v3.4.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

In JSX, `<div style={{ backgroundColor: condition ? '#d6f9dd' : undefined }} />` will not produce any style. But is astro template, this will produce `style="background-color:undefined"`

### What's the expected result?

behave as convention in JSX

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-47zegu?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is probably a pretty simple thing to fix once you find the code where this happens (I don't remember off-hand).

**Comment by MarvinXu** [comment]
I'll fix this by the end of the week. It would be great if anyone remember where the code is and inform me 😄
