### ISSUE TITLE
Query params trigger the `trailingSlash` error in preview mode

### ISSUE THREAD

**Issue by kamoshi** [withastro/astro#8942]
### Astro Info

```block
Astro                    v3.4.0
Node                     v20.9.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/solid-js
                         pagefind
```

### If this issue only occurs in one browser, which browser is a problem?

n/a

### Describe the Bug

When navigating to for example `http://localhost:4321/search/?q=hask` while running `astro preview` an error is shown:

![image](https://github.com/withastro/astro/assets/18511281/ac19a4a2-4257-4454-8863-4a5d55fd8418)

### What's the expected result?

The page should be shown normally

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rj7etb?file=src%2Flayouts%2FLayout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Is this for a static site?

**Comment by kamoshi** [comment]
Yes, it is static, however using query parameters in the URL allows me to save the search history that was inputted by the user on the search page. I use `window.history.pushState` browser API with a debounce to add URLs when user types a query client side.

I can't think of a better way to implement client-side site-wide search that can be preserved between tab reloads and shared with others

**Comment by rishi-raj-jain** [comment]
@kamoshi 

- I just tried your reproduction, and it doesn't seem to have a /search page (as it said in your issue description.
- I clicked on `Click Me` in your reproduction, and it works with the preview server.

**Comment by lilnasy** [comment]
You're right, the search page really does not exist. The issue is still visible though - the dev server thinks search params should end with a slash. Going to an arbitrary url with arbitrary search params should surface that.

**Comment by kamoshi** [comment]
> - I just tried your reproduction, and it doesn't seem to have a /search page (as it said in your issue description.

The search page exists on my website, but this bug doesn't depend on any page's existence, it can be root path ("/") too.

> - I clicked on `Click Me` in your reproduction, and it works with the preview server.

Make sure to kill the initial dev server with `ctrl-c`, run `npm run build && npm run preview`, and refresh the page afterwards. Then this should appear:
![Screenshot_2023-11-10-09-07-50-896-edit_org.mozilla.firefox.jpg](https://github.com/withastro/astro/assets/18511281/7da817ed-0659-4639-bbec-7d98f76e1956)

**Comment by rishi-raj-jain** [comment]
Yeah, I did this:

- npm run build && npm run preview
- Go to homepage
- Click on `CLICK ME`

Oh wait do you mean directly go to homepage/?test=10 instead of clicking it?

**Comment by kamoshi** [comment]
> Oh wait do you mean directly go to homepage/?test=10 instead of clicking it?

No, that screen should appear immediately after clicking on the button. That's strange I just did it minutes ago and it appeared for me

**Comment by rishi-raj-jain** [comment]
Can you re-try that? I tried that when I commented 3 hours ago and your code just worked fine.

**Comment by rishi-raj-jain** [comment]
Wait, let me do it again and record it

**Comment by rishi-raj-jain** [comment]
Purely, my bad. I was trying different combinations and I left the configuration set to trailingSlash: 'never' where this worked.
