### ISSUE TITLE
React components with client:only directive will have the style reloaded during View Transition

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [withastro/astro#8946]
### Astro Info

```block
Astro                    v3.4.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### Describe the Bug

React components with client:only directive will have the style reloaded during View Transition. React components' style has will remove and add again when transitioned. It causes flick view on component's styles.

### What's the expected result?

Style should not reload during the view transition.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rzjvb9

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
@ahmet-cetinkaya, thank you for you stackblitz example! The styles will stay now when #8964 is out.
