### ISSUE TITLE
Astro does not support Vue exports other than from setup.

### ISSUE THREAD

**Issue by minht11** [withastro/astro#8947]
### Astro Info

```block
Astro                    v3.0.12
Node                     v20.6.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/vue
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Firefox, Safari

### Describe the Bug

Astro does not support exports from regular non setup Vue scripts like this `<script lang="ts">`, type exports (the only thing supported from suchs blcoks) from `<script lang="ts" setup>` work fine.

Have a vue component
```vue
<script lang="ts">
export const someFunction = (param: 1 | 2) => boolean;

export interface PropsMultiple {
  value: 1;
}
</script>

<script lang="ts" setup>
defineProps<PropsMultiple>();
</script>

<template>
  <div>Multipe script blocks Component</div>
</template>
```
and try to import it inside astro page
```astro
---
// Neither types nor values exported from separate script block work here.
import MultipleBlocks, { type PropsMultiple, someFunction } from "../components/CompWithMultipleBlocks.vue";

---
<MultipleBlocks value={1} />

<!-- This breaks -->
{someFunction(1)}
```

### What's the expected result?

Importing from regular Vue script blocks work as expected.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vc8reo-kzwimz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Is this about editor support or is this something that breaks at runtime?

**Comment by minht11** [comment]
I double checked and I made mistake in my original reproduction (fixed it). On runtime it is working, so only editor/types support is lacking, as in exports not being recognized as existing. I guess I should open issue in [language-tools](https://github.com/withastro/language-tools) repo?
