### ISSUE TITLE
ViewTransitions Router not maintaining `theme-dark` on Astro Docs

### ISSUE THREAD

**Issue by afonsojramos** [withastro/astro#8948]
### Astro Info

```block
Astro                    v3.0.8
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             auto-import
                         @astrojs/preact
                         @astrojs/sitemap
                         @astrojs/asides
                         astro-expressive-code
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

Maybe the title isn't the true issue, but ViewTransitions does not take into account root element classnames for dark/light theme, making us do a check for the theme. Somewhere in the middle of all this an unnecessary flash shows when switching pages that I'm not 100% what is causing it.

### What's the expected result?

The flash does not occur, but another question might be why does it not happen without ViewTransitions.

### Link to Minimal Reproducible Example

https://github.com/withastro/docs/pull/5233

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by sarah11918** [comment]
Hey @afonsojramos ! I haven't looked into this closely for the docs repo itself as we're not considering adding View Transitions to the docs, but this might give some guidance (see Step 6) as to how we're suggesting to target `astro:after-swap` for things like checking for a theme.

I will let the core dev team decide whether there is a futher issue to look into not related to the docs repo itself, but re: theme flashing in general.

As I mentioned in your PR to docs, we are not adding View Transitions to the docs right now, so getting it to work in that repo is not an issue for us.

**Comment by lilnasy** [comment]
Do you know if the inline scripts in `CommonHead.astro` run after swap?

**Comment by afonsojramos** [comment]
@lilnasy they indeed do not! I was not aware of the existence of that component, but replacing `page-load` with `after-swap` actually ended up fixing the issue, and the code within `HeadCommon.astro` is now deletable. 

Either way, as @sarah11918 mentioned in https://github.com/withastro/docs/pull/5233, the goal is not to have ViewTransitions in the main docs site (which I find personally weird, but all good here 😅), and since the issue described here was out of a misunderstanding on my part of the difference between `page-load` and `after-swap` , I'll be closing the ticket. Thanks!!
