### ISSUE TITLE
unexpected static build step is present outputing a folder including a file introduced in version `3.x`

### ISSUE THREAD

**Issue by kireerik** [withastro/astro#8957]
### Astro Info

```block
Astro                    v3.4.0
Node                     v21.1.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
```

### Describe the Bug

unexpected build step: `building client`
potentially unexpected transformations: `✓ 3 modules transformed.`
unexpected output folder and file: `_astro` / `client.<hash>.js`

### What's the expected result?

There is no extra build step with no extra outputs. Just like in version 2.x.

### Link to Minimal Reproducible Example

https://github.com/kireerik/refo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Sorry, but we cannot do anything with such a reproduction, it's too big to diagnose properly.

This logging wasn't enabled in Astro 2, is it possible it always existed and you didn't notice?

**Comment by kireerik** [comment]
No, I checked it and this was introduced in version 3.x.

**Comment by kireerik** [comment]
The issue is that since version 3.x Astro generates this `client` `js` file even when it is not needed and not used at all.

**Comment by kireerik** [comment]
Okay this was an existing issue with the Astro SolidJS integration.

So far (with 2.x) I have used this workaround:
- https://github.com/kireerik/refo/blob/fdf5b81e167e8f5d2fdb6be21ef0c84cb4053378/example/package.json#L27C1-L28
- https://github.com/kireerik/refo/blob/fdf5b81e167e8f5d2fdb6be21ef0c84cb4053378/example/index/index/index.js#L12
- https://github.com/kireerik/refo/blob/fdf5b81e167e8f5d2fdb6be21ef0c84cb4053378/example/index/index/index.js#L32-L44

After 3.x the above workaround no longer works.

So this is an existing issue and I would expect the Astro SolidJS integration to not produce a client when SolidJS is not used on the client side.

> I am only using [Astro](https://docs.astro.build/en/reference/cli-reference/#astro-dev) [Dynamic](https://docs.astro.build/en/core-concepts/routing/#static-ssg-mode) [Static file (server) endpoint](https://docs.astro.build/en/core-concepts/endpoints/#static-file-endpoints) based [page](https://github.com/kireerik/refo/blob/main/example/index/index/page.js) routing.
