### ISSUE TITLE
Enhance Testing for Internal Packages

### ISSUE THREAD

**Issue by alexanderniebuhr** [withastro/astro#8960]
As maintainers, we want to have more sophisticated tests for our internal packages (e.g., @astrojs/underscore_redirects) so that we can ensure their reliability and robustness.

Currently, we are evaluating the kind of infrastructure required to best test these packages. While using search or regex pattern matching on the result might be a quick solution, I personally feel there could be better methods to achieve comprehensive testing. However, I haven't had the chance to explore alternatives yet.

**Comment by bluwy** [comment]
@alexanderniebuhr is there a plan yet to resolve this issue? or is the issue still relevant?
