### ISSUE TITLE
Cannot use vite config's define to set env vars

### ISSUE THREAD

**Issue by abegehr** [withastro/astro#8967]
### Astro Info

```block
Astro                    v3.4.0
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

Using `vite.define` in Astro's defineConfig() has no effect.

Sample `astro.config.mjs`:

```
import { defineConfig } from "astro/config";
import vercel from "@astrojs/vercel/serverless";
import tailwind from "@astrojs/tailwind";
import svelte from "@astrojs/svelte";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";

// read package.json
const file = fileURLToPath(new URL("package.json", import.meta.url));
const json = readFileSync(file, "utf8");
const pkg = JSON.parse(json);
console.log("DEBUG pkg:", pkg);

// https://astro.build/config
export default defineConfig({
  site: "https://my.site",
  output: "server",
  adapter: vercel(),
  integrations: [tailwind(), svelte()],
  vite: {
    define: {
      PKG_VERSION: pkg.version,
    },
  },
});
```

### What's the expected result?

Reading the package.json version from `import.meta.env.PKG_VERSION` to show it in the Astro app. PKG is properly read from file and parsed but doesn't appear in `import.meta.env`. It seems that Astro does not support `vite.define` in Astro's `defineConfig()`. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-p7iocq?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jacobthesheep** [comment]
Why don't you use do this instead?

import pkg from '../../package.json';

**Comment by lilnasy** [comment]
That would be...
```ts
    define: {
      `import.meta.env.PKG_VERSION`: pkg.version,
    },
```

**Comment by abegehr** [comment]
Thank you, @lilnasy! Got it working like so: `"import.meta.env.PKG_VERSION": JSON.stringify(pkg.version)`
