### ISSUE TITLE
the styles not loaded

### ISSUE THREAD

**Issue by sternelee** [withastro/astro#8971]
### Astro Info

```block
what? I have no `astro info` command
```

### Describe the Bug

when i used the naive-ui or radix-vue by @astrojs/vue, the component has been rendered, but styles were not loaded

### What's the expected result?

ui style is normal

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xdfl7e

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jacobthesheep** [comment]
You need to run `npx astro info` or `pnpm astro info`

**Comment by jacobthesheep** [comment]
Not sure what's going on but the styles are being rendered when I opened the link

**Comment by sternelee** [comment]
Ok, I found the same question, Astro not support `css in js`

https://www.reddit.com/r/webdev/comments/16r8sti/whats_the_most_compatible_component_library_for/

**Comment by anth0ni3** [comment]
I'm having similar issues. I run a monorepo with shadcn as a UI package. The UI styles don't load in even though it's tailwindcss. when I add styles...it works, but the styles from the package don't work.

**Comment by samiUllah1526** [comment]
The same issue is happening with HeroUI — the component loads, but its styles aren’t being applied. Other Tailwind classes are working fine, though.

**Comment by samiUllah1526** [comment]
Astro                    v5.15.9
Vite                     v6.4.1
Node                     v22.15.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react (v4.4.2)
