### ISSUE TITLE
Cannot access 'getCollection' before initialization when running `build`

### ISSUE THREAD

**Issue by MrAlex94** [withastro/astro#8972]
### Astro Info

```block
Astro                    v3.4.0
Node                     v20.7.0
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             starlight-blog
                         @astrojs/starlight
                         @astrojs/svelte
                         @astrojs/tailwind
```

### Describe the Bug

I am generating a open graph image with `src/pages/open-graph/[...path].ts`:

```TypeScript
import { OGImageRoute } from 'astro-og-canvas'
import { getCollection } from 'astro:content'

const allPages = await getCollection('docs')

/** Paths for all of our Markdown content we want to generate OG images for. */
const paths = process.env.SKIP_OG ? [] : allPages

/** An object mapping file paths to file metadata. */
const pages = Object.fromEntries(paths.map(({ id, slug, data }) => [id, { data, slug }]))

export const { getStaticPaths, GET } = OGImageRoute({
	param: 'path',

	pages,

	getImageOptions: async (_, { data, slug }: (typeof pages)[string]) => {
		return {
			title: data.title,
			description: data.description,
			dir: slug,
			logo: {
				path: './src/assets/waterfox-logo.png',
				size: [400]
			},
			border: { color: [5, 51, 97], width: 20, side: 'inline-start' },
			bgGradient: [
				[182, 156, 254],
				[123, 165, 255]
			],
			font: {
				title: {
					size: 80,
					families: ['Montserrat'],
					weight: 'Bold'
				},
				description: {
					size: 40,
					lineHeight: 1.25,
					families: ['Montserrat Thin'],
					weight: 'Light'
				}
			},
			fonts: [
				'https://github.com/JulietaUla/Montserrat/raw/master/fonts/webfonts/Montserrat-Light.woff2',
				'https://github.com/JulietaUla/Montserrat/raw/master/fonts/webfonts/Montserrat-Bold.woff2'
			]
		}
	}
})
```

When running `bun run build`, I get the following output:

```shell
 generating static routes 
 error   Cannot access 'getCollection' before initialization
  File:
    /Users/akontos/Work/waterfox-rework/node_modules/astro/dist/core/build/generate.js:193:22
  Code:
    192 |   }
    > 193 |   const pageModule = await pageModulePromise();
          |                      ^
      194 |   if (shouldSkipDraft(pageModule, pipeline.getSettings())) {
      195 |     logger.info(null, `${magenta("\u26A0\uFE0F")}  Skipping draft ${pageData.route.component}`);
      196 |     logger.warn(
  Stacktrace:
ReferenceError: Cannot access 'getCollection' before initialization
    at file:///Users/akontos/Work/waterfox-rework/dist/chunks/pages/__2d08d290.mjs:279:18
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
    at async generatePage (file:///Users/akontos/Work/waterfox-rework/node_modules/astro/dist/core/build/generate.js:193:22)
    at async generatePages (file:///Users/akontos/Work/waterfox-rework/node_modules/astro/dist/core/build/generate.js:147:9)
    at async staticBuild (file:///Users/akontos/Work/waterfox-rework/node_modules/astro/dist/core/build/static-build.js:85:7)
    at async AstroBuilder.build (file:///Users/akontos/Work/waterfox-rework/node_modules/astro/dist/core/build/index.js:127:5)
    at async AstroBuilder.run (file:///Users/akontos/Work/waterfox-rework/node_modules/astro/dist/core/build/index.js:158:7)
    at async build (file:///Users/akontos/Work/waterfox-rework/node_modules/astro/dist/core/build/index.js:37:3)
    at async build (file:///Users/akontos/Work/waterfox-rework/node_modules/astro/dist/cli/build/index.js:21:3)
    at async runCommand (file:///Users/akontos/Work/waterfox-rework/node_modules/astro/dist/cli/index.js:116:7)
    at async cli (file:///Users/akontos/Work/waterfox-rework/node_modules/astro/dist/cli/index.js:144:5)

error: script "build" exited with code 1 (SIGHUP)
```

### What's the expected result?

`bun run astro dev` generates the images correctly. `bun run build` should also, I am unsure why `getCollection` would not be available/uninitialized at build time?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2zqutw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by vasfvitor** [comment]
I'm having the same issue, works on dev but can't build.

Tried to reproduce without Starlight but couldn't. And this work perfectly on official Astro docs, as it is from I ~copied~ got inspiration for the implementation.

I went as far as adding editing Starlight source code (instead of override) but no difference, I guess any override will give the same result, I've tried with head and banner:

Steps on a new Starlight Project:
1) Override on`astro.config.mjs`
```ts
components: {
  Footer: './src/components/overrides/test.astro',
  },

````

2) Component:  `src/components/overrides/test.astro`
```ts 
---
import { sum } from 'pages/thisFile';
sum();
---
```


3)  `src/pages/thisFile.ts`. Needs to be in /pages because the goals to utilize a `[...docs].ts`). Either way will fail. 
Note: placing `thisFile.ts` outside /pages works, but I haven't tried to use it as workaround.
```ts
import { getCollection } from 'astro:content';
const pages= await getCollection('docs');
console.log(pages);

export function sum() {
  1 - 1
}
```
4) ```pnpm build```
5) Fail
![image](https://github.com/withastro/astro/assets/61759797/8417b589-93e8-4dc0-a197-e3c087cca073)

The very same function works when called from a file outside `/pages`, instead of an override, I haven't tried calling it from components.

example:
 `src/pages/test.astro`
```
---
import { sum } from 'pages/thisFile';
sum();
---
```

Hope this helps.

**Comment by matthewp** [comment]
Hello, unfortunately this is a limitation of how Astro components work. The `getStaticPaths` function is lifted out and does not have access to the scope values. So you must perform all of your logic inside of `getStaticPaths`. This is explained here: https://docs.astro.build/en/reference/api-reference/#getstaticpaths

**Comment by barrenechea** [comment]
I wonder how [withastro/docs](https://github.com/withastro/docs) is doing it, the code seems to have a very similar implementation for OpenGraph, just importing it from `~/content`.

When I attempt to do the same on my project, it fails for the same reason as this issue.

**Comment by vasfvitor** [comment]
for context, this is a PR from Astro Docs migration to Starlight, it's in active development as of now and in the future this hack may not be needed anymore. 

00 hack: https://github.com/withastro/docs/pull/4266/commits/030073f32d6dfe586c6e1da8d48d6b5485541ba2
This helped to solve the current issue, well, at least solved there and I've test and now it builds yaaay! for reference I'm using a simplified version of the current Astro Docs setup, so ymmv
