### ISSUE TITLE
transition:name not work in astro-island (client side components)

### ISSUE THREAD

**Issue by kratess** [withastro/astro#8983]
### Astro Info

```block
Astro                    v3.3.0
Node                     v18.16.0
System                   Windows (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### Describe the Bug

It is not possible to do a transition animation between ssr and client component.
I have ViewTransitions in both layouts and transition:name={cover-${id}} on both components image elements.
ssr: data-astro-transition-scope="astro-b7hvcfre-1"
client: transition:name="cover-6"

So basically they have different name of animation.
Even using import { navigate } from 'astro:transitions/client'; not work. Maybe just help a bit more but doesn't do the hero image transition because obviously doesn't follow the transition name that is incorrect.

### What's the expected result?

make the transition work from ssr to client and vice-versa

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8c6vse?file=src%2Fpages%2Fpage.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
The `transition:` directives (and all directives, such as `client:`) only work inside of `.astro` files. If you want to have a transition name that is shared between elements where one is inside of `.astro` and another inside of `.jsx` you can do this pretty easily with CSS via a shared class name:

```css
.my-image {
  view-transition-name: noenemies2;
}
```

Hope this helps.

**Comment by jorgejhms** [comment]
This should be included in the Astro Documentation. It would be very useful as many sites combine framework components with astro files.

**Comment by jsonMartin** [comment]
> The `transition:` directives (and all directives, such as `client:`) only work inside of `.astro` files. If you want to have a transition name that is shared between elements where one is inside of `.astro` and another inside of `.jsx` you can do this pretty easily with CSS via a shared class name:
> 
> ```css
> .my-image {
>   view-transition-name: noenemies2;
> }
> ```
> 
> Hope this helps.

I definitely found this helpful, but sometimes the `view-transition-name` needs to be dynamic (such as for multiple images on the page) which is not supported via shared CSS classes. In this case, a dynamic `view-transition-name` can be added via an inline style property, to ensure unique transition name keys:

```
<img
  {src}
  {width}
  style={`view-transition-name: ${src.replace(/[^a-z0-9]/gi, '')}`}
/>
```

This is also valid for adding transition effects to DOM elements completely encapsulated inside UI components, without being used in any `.astro` file at all.

**Comment by jsonMartin** [comment]
> This should be included in the Astro Documentation. It would be very useful as many sites combine framework components with astro files.

I agree. I did not realize that it was possible to add transitions within UI framework component DOM elements such as Svelte until I came across this page.
