### ISSUE TITLE
Vuetify components FOUC issue with Astro

### ISSUE THREAD

**Issue by TechAkayy** [withastro/astro#8987]
### Astro Info

```block
Astro                    v3.4.0
Node                     v21.1.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/vue
                         @astrojs/preact
                         @astrojs/react
                         @astrojs/solid-js
                         @astrojs/svelte
                         unocss
                         @astrojs/mdx
                         @astrojs/sitemap
                         unplugin-auto-import
                         @pinegrow/astro-module
```

### If this issue only occurs in one browser, which browser is a problem?

Testing only in Chrome

### Describe the Bug

FOUC issue with Vuetify components with Astro. In the reproduction, try refreshing the page, and notice the buttons. Here is a gif. 

Noticing this issue with Astro - https://pg-astro-vuetify.netlify.app/ (https://github.com/TechAkayy/my-astro-vuetify-ssr-issue)

Same component works fine with other frameworks
- Iles - https://pg-iles-vuetify.netlify.app/ (https://github.com/pinegrow/pg-iles-vuetify)
- Nuxt - https://pg-nuxt-vuetify.netlify.app/ (https://github.com/Pinegrow/pg-nuxt-vuetify)

![2023-11-02 23 52 51](https://github.com/withastro/astro/assets/73772701/37689fe7-a977-453b-8c94-7ce3ff964130)

### What's the expected result?

The components should work without any styling issue. 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/TechAkayy/my-astro-vuetify-ssr-issue?file=src%2Fcomponents%2FVuetifyIsland.vue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by TechAkayy** [comment]
Just an fyi - Vuetify relies on global inject, hence adding vuetify to the specific island. Related thread with Iles, but the concept is the same - https://github.com/ElMassimo/iles/issues/259.

**Comment by matthewp** [comment]
Hey @TechAkayy, sorry for the slow response. Can you trim down the reproduction to only what is absolutely necessary. I think just a single page, and a single usage of this component should be enough to show the problem.

Most of the time this sort of thing is a configuration issue.

**Comment by TechAkayy** [comment]
Reproduction on both github & stackblitz are already included

**Comment by TechAkayy** [comment]
Hi @matthewp I have removed all linting, formatting kinda features, and removed a lot of content to have only one index page that client:load the VuetifyIsland.vue that displays the SampleCard. Same issue. Thanks for looking into this. 

[Screencast from 18-11-23 15:39:48.webm](https://github.com/withastro/astro/assets/73772701/0248c20d-2b1d-4e9b-87e9-d55380e7757e)

**Comment by TechAkayy** [comment]
I have updated the original repo to make it minimal. 

Can you re-open this issue @matthewp. Thanks!
