### ISSUE TITLE
Rendering bug in Astro templates following a loop

### ISSUE THREAD

**Issue by rjvdw** [withastro/astro#8991]
### Astro Info

```block
Astro                    v3.4.3
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When writing the following piece of JSX:

```jsx
<div class="wrapper">
  <table>
    <tr>
      <th>text</th>
    </tr>

    {
      data.map((row) => (
        <tr>
          <td>{row.text}</td>
        </tr>
      ))
    }
  </table>
</div>

<p>I live outside the wrapper.</p>
```

the paragraph is incorrectly rendered inside the `div.wrapper`.

### What's the expected result?

The paragraph should be rendered outside of the div, but instead it gets rendered inside the div.

### Link to Minimal Reproducible Example

https://github.com/rjvdw/astro-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This looks like another instance of https://github.com/withastro/compiler/issues/870. Closing in favour of it instead.
