### ISSUE TITLE
getCollection types are wrong and should never return underfined

### ISSUE THREAD

**Issue by CapitaineToinon** [withastro/astro#8999]
### Astro Info

```block
Astro                    v3.4.3
Node                     v18.18.0
System                   macOS (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

I think there are still some problems when it comes to typescript and the returned types.

Given the following `src/content/config.ts`:

```ts
import { z, defineCollection } from "astro:content";

const blog = defineCollection({
  type: "content",
  schema: z.object({
    title: z.string(),
  }),
});

export const collections = { blog };
```

And the following structure (no blog folder):

```
- src/
  - content/
    - config.ts
```

I do indeed get the following warning in the console:

```
[content] The "blog" collection does not have an associated folder in your `content` directory. Make sure the folder exists, or check your content config for typos.
```

However the generated types in `.astro/types.d.ts` don't include the blog collection at all.

```ts
	type ContentEntryMap = {
		
	};

	type DataEntryMap = {
		
	};

	type AnyEntryMap = ContentEntryMap & DataEntryMap;

	type ContentConfig = typeof import("../src/content/config");
```

This means I get type errors when running this code:

![image](https://github.com/withastro/astro/assets/15376923/b83614ec-bbc8-4a8c-9841-0ea5bc70ef43)

I'm expecting the blog collection type to be there and to be inferred from my blog schema. Basically return me an empty array of blogs.

I can fix this by creating an empty blog content folder:

```
- src/
  - content/
    - blog/
      - .gitkeep 
    - config.ts
```

But now `getCollection` return type is `unknown[]` and even worse, at runtime it actually returns `underfined`.

![image](https://github.com/withastro/astro/assets/15376923/fff1b647-6cf6-4724-858e-7f48870b0979)

![image](https://github.com/withastro/astro/assets/15376923/95039a2a-e6b4-424c-bebc-94bf0fb6fdd6)

### What's the expected result?

This is very strange behavior. Basically, as long as collections are exported in `config.ts`, I'm expecting astro:content to fully be aware of it, regardless of my actual file structure.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vzypw2?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by CapitaineToinon** [comment]
For context, my issue is that I'm using astro and decap CMS at the same time. I intend my content to be created using decap so it's expected that collections could be empty. However, since I'm using astro to run decap, I cannot access the admin panel because my code crashes with the bug described above, but I need to access my panel to create content in the first place.

**Comment by CapitaineToinon** [comment]
For reference, my fix for now is to disable typescript for that file, do some optional checking to always return an array.

```ts
// @ts-nocheck
// ☝️not great
import { getCollection } from "astro:content";
import BaseLayout from "../layouts/base-layout.astro";

export async function getStaticPaths() {
  const pages = await getCollection("pages");

  return (
    pages?.map((entry) => ({
      params: { slug: entry.slug },
      props: { entry },
    })) ?? [] // 👈 always return an array
  );
}

const { entry } = Astro.props;
const { Content } = await entry.render();
---

<BaseLayout>
  <Content />
</BaseLayout>
```

**Comment by Princesseuh** [comment]
Ah yeah, the behaviour there changed a few times mostly because of unrelated issues. I agreed that having the collection defined should be enough, and I believe it was previously the case.

In the meantime, instead of disabling TypeScript in the file completely, you could just do `(pages ?? []).map`


P.S. Awesome work on the Dark Souls speedruns, I remember watching your runs a few years ago 😄

**Comment by CapitaineToinon** [comment]
Thanks, appreciate it! 

Unfortunately `(pages ?? []).map` doesn't help with the types. It seems like the issue is that the values are literal, since a generated based on the actual files:

```ts
  type ContentEntryMap = {
    pages: {
      "index.md": {
        id: "index.md";
        slug: "index";
        body: string;
        collection: "pages";
        data: InferEntrySchema<"pages">;
      } & { render(): Render[".md"] };
    };
  };
```

I get that this can be very useful for getEntry to catch 404 are compile times:

![image](https://github.com/withastro/astro/assets/15376923/e3de84d5-b87f-4450-98db-32e7e34a330c)

But I feel like this approach is not reconcilable with the bug here. The types are just too specific, I would need something wider.

For now, to keep using typescript, I'm gonna mimic the return type of `getCollection`:

```ts
const pagesSchema = z.object({
  title: z.string(),
});

const pages = defineCollection({
  type: "content",
  schema: pagesSchema,
});

export type Page = {
  id: string;
  slug: string;
  body: string;
  collection: "pages";
  data: z.infer<typeof pagesSchema>;
} & { render(): Render[".md"] };
```

And overwrite the return type in my function call:

```
import type { Page } from "@/content/config";

export async function getStaticPaths() {
  const pages = (await getCollection("pages")) as Page[] | undefined;

  if (!pages) {
    return [];
  }

  return pages.map((entry) => ({
    params: { slug: entry.slug },
    props: {
      pages,
      entry,
    },
  }));
}
``` 

And that seems to work fine. Would love a fix though.

**Comment by travisby** [comment]
I also hit this issue.  After noticing types were off, I looked at .astro/types.d.ts and my new type was empty, not the schema I built. 

-- your "directory was empty" was a hint to me.

Once I created an item in the collection then the type was correctly populated in .astro/types.d.ts

**Comment by NicoRio42** [comment]
> For context, my issue is that I'm using astro and decap CMS at the same time. I intend my content to be created using decap so it's expected that collections could be empty. However, since I'm using astro to run decap, I cannot access the admin panel because my code crashes with the bug described above, but I need to access my panel to create content in the first place.

@CapitaineToinon I am also using Astro and Decap CMS, and I found a hack to solve the problem without disabling Typescript:
- Create a dummy entry in a [subdirectory of the collection's directory](https://docs.astro.build/en/guides/content-collections/#organizing-with-subdirectories).
- In the Astro component querying the collection, filter the collection entries to remove the dummy entry.

This way you still have Typescript support for this collection, and the dummy entry should not appear in Decap CMS as it is in a different directory. However I agree this should not be necessary.
