### ISSUE TITLE
tsconfig.json  compilerOptions>paths has lower priority than node_modules folder

### ISSUE THREAD

**Issue by Antonytm** [withastro/astro#9015]
### Astro Info

```block
Astro                    v3.4.3
Node                     v18.16.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/vue
```

### Describe the Bug

I want to unpdate astro from 2.10.15 to 3.4.3
List of changes here: https://github.com/exdst/jss-astro-public/pull/7

The problem:
Project contains from 2 parts:
1) Library: distributed as NPM package
2) Site: sample of usage

This 2 parts are connected using  compilerOptions>paths attribute in the tsconfig.json:
```
    "paths": {
      "@astro-sitecore-jss/astro-sitecore-jss": [
        "packages/astro-sitecore-jss/index.ts"
      ]
    }
```

And I have usage of library like this: 
```
import { Image } from '@astro-sitecore-jss/astro-sitecore-jss';
```

It should call `packages/astro-sitecore-jss/index.ts` based on tsconfig.json
And that worked fine on 2+ version.

But it stopped to work with 3+ version.
Instead of using local @astro-sitecore-jss/astro-sitecore-jss, it takes from node_modules.

### What's the expected result?

tsconfig.json paths attribute should have priority over the packages in node_modules. (That is how it worked in Astro 2.+)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-3rgcjs?file=src%2Fcomponents%2FBaseHead.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
The Astro `paths` resolution had always took lower priority if the specifier, e.g. `@astro-sitecore-jss/astro-sitecore-jss` already resolves to something, e.g. the node_modules package. There was a regression in a few minor versions of v2 that caused it to have a higher priority which might be why you're seeing this.

If you want to have a higher priority instead, you should use `vite.resolve.alias` in `astro.config.js` to configure how it's resolved. We could perhaps revisit this behaviour in the future, but at the moment this is expected behaviour.

**Comment by Antonytm** [comment]
Ok, thank you for the clarification. 
Funny that I worked on a few Astro versions 2+ and it worked with tsconfig. That is why I was sure that it is expected behavior.
Alias fix the problem.

@bluwy Do you know if this Vite NPM plugin works with Astro? (It should do what I need from description, but it seems doesn't work) https://www.npmjs.com/package/vite-tsconfig-paths

**Comment by bluwy** [comment]
I'm not sure, but we do have an internal Vite plugin that does the same thing as it today.
