### ISSUE TITLE
error img is a self-closing tag and must neither have `children` nor use `dangerouslySetInnerHTML`.

### ISSUE THREAD

**Issue by dande-sun** [withastro/astro#9020]
### Astro Info

```block
> astro info

Astro                    v3.4.3
Node                     v20.8.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/tailwind
                         @astrojs/sitemap
 error   Command failed: which xclip
```

### Describe the Bug

When I pass img tag as props to react component, I got an error: 'img is a self-closing tag and must neither have children nor use dangerouslySetInnerHTML.'.
but if the img tag coding in the react component, it's working.
the astro code：
![image](https://github.com/withastro/astro/assets/93630861/ec5a6825-392c-4a20-9cae-7261ec099c3c)
the react code:
![image](https://github.com/withastro/astro/assets/93630861/0adf794c-f019-412e-adb1-ed0441651418)

### What's the expected result?

I hope can pass the img tag to React component, because astro components is deficient, and most of it is development phase.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/angry-sun-xpzhps?file=%2Fsrc%2Fcomponents%2FCarousel.tsx%3A16%2C19

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by milcaunicorn** [comment]
Try the adding client instructions which strategy for hydration.

```
<ReactComp client:load client:only="react">
   children
</ReactComp>
```

**Comment by lilnasy** [comment]
Thanks for looking into it, @milcaunicorn! This really helps. Summarizing the issue:
- Affects both dev and build
- Affects server hydration, "client:only" works.
- Appears only when `experimentalReactChildren` is enabled.
- React expects self-closing elements to _not_ have `children`, but the react integration's experimental feature always creates an array.
<img width="529" alt="image" src="https://github.com/withastro/astro/assets/69170106/f94b9cf8-283e-4d60-af3f-6017c29e9668">
