### ISSUE TITLE
Changing MDX Frontmatter of imported pages

### ISSUE THREAD

**Issue by prawin12345** [withastro/astro#9022]
### Astro Info

```block
Astro                    v3.4.3
Node                     v20.6.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/vue
                         @astrojs/tailwind
```

### Describe the Bug

I am trying to build a blog with "subarticles", i.e. there are the individual pages for each chapter and a page in a parent directory containing the combined contents. For the individual pages I'm using MDX and using a .astro layout. That layout changes the content conditionally depending on a frontmatter property (I want to prevent displaying the top navbar repetedly). In the parent page, I'm using `astro.glob` to import these mdx components and I'm changing the frontmatter with

```ts
---
...
const pages = await Astro.glob(`...`);
pages.forEach(page => page.frontmatter.contentOnly = "true");
---
```

and then displaying them in the `.astro` parent page with

```tsx
...
{ pages.map((page) => <page.default />) }
...
```

In dev-mode everything works fine, but the problem occurs when building the html pages. The parent page is ok, but then all the individual pages are rendered incorrectly (i.e. with the navbar). I'm suspecting astro is using some kind of caching for mdx components. Is this intentional and, if yes, are there other ways to achieve this aim?

I have tried passing props to the component

```tsx
{pages.map((page) => <page.default contentOnly={true} />)}
```

But that didn't work (`Astro.props.contentOnly` was undefined in the mdx layout), I also tried using `import.meta.glob` but that gave the same result.

PS: After creating the minimal example for stackblitz, I found out that there the problem will occur on the dev server too, when first loading the parent page and then the chapter page without editing the source files.

### What's the expected result?

The HTML pages should contain the navbar.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-eusdcg-ls3qnv?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I couldn't reproduce the issue in the stackblitz link. In dev and builds, the chapter-1 and chapter-2 pages don't have the navbar for me.

In general, `frontmatter` data tend to be read-only so I wouldn't mutate it like so. It might be better if you check against `Astro.url`, `Astro.props.url` or `Astro.props.content` in `chapter.astro` the layout to dynamically apply the navbar if needed.

**Comment by prawin12345** [comment]
Yes, if you load the parent page first, the individual chapter pages won't have a navbar. However, if you go to the individual page first, make a change in the mdx file and then reload the page, there will be a navbar. So, the individual page is displayed differently when the parent page is loaded first.

**Comment by prawin12345** [comment]
I reorganized my code and am using content collections; the code is now working as expected.
