### ISSUE TITLE
ERR_REQUIRE_ESM error on latest update

### ISSUE THREAD

**Issue by GibzClt** [withastro/astro#9024]
### Astro Info

```block
Trying to install astro
```

### Describe the Bug

On installing the latest version of astro (v3.4.4), it throws the following error
npm create astro@latest
```
internal/modules/cjs/loader.js:1007
  throw new ERR_REQUIRE_ESM(filename);
  ^

```

### What's the expected result?

Should install astro

### Link to Minimal Reproducible Example

Since this is in installing, not able to show an example

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I don't see any errors when running `npm install astro` in an empty project
