### ISSUE TITLE
Stylelint processes styles transformed with Postcss, no guide how to configure

### ISSUE THREAD

**Issue by T3sT3ro** [withastro/astro#9026]
### Astro Info

```block
Astro                    v3.4.4
Node                     v20.8.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/prefetch
```

### Describe the Bug

Stylelint seems to be running on files already processed by postcss in astro, and I can't find a way to make it work properly. I tried following the guides for stylelint and postcss, but it doesn't want to work. What's more, the stylelint seems to ignore the configuration.

The documentation on how to properly configure stylelint and postcss in astro could be better, the docs on stylelint 

### What's the expected result?

Stylelint shouldn't be processing files processed by astro, files inside node_modules and it should only work before processing with other postcss plugins (like autoprefixer — on my local, more complex project it detects additional errors like "no vendor prefixes" which are added probably by autoprefixer, as they are not present in my source code; I didn't yet manage to reproduce this one case in stackblitz)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-gmwxtc

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional info

It is possible that this may be a configuration problem, but there are no helpful materials or examples that describe how to configure stylelint + postcss in astro. The related discord post: https://discord.com/channels/830184174198718474/1171856464277684264

**Comment by bluwy** [comment]
Compatibility or guide with how to integrate certain libraries is out of scope of Astro's docs. This should be contributed externally, e.g. blog posts. For stylelint, you can look into https://github.com/ModyQyW/vite-plugin-stylelint instead.

**Comment by T3sT3ro** [comment]
If you haven't, take a look at the stackblitz and decide for yourself if it's misconfiguration or bug in astro. I couldn't determine which is it. To me it looks like astro ("which comes with postcss by default as a part of vite") runs postcss on plugins on css files it already processed (classes with astro id suffixes etc are displayed in stylelint) and it somehow breaks the configuration that is recommended by the official guides of stylelint.

**Comment by bluwy** [comment]
The Astro compiler has to output CSS with those astro id suffixes, that's the starting point of the CSS with no postcss applied yet. You can't apply postcss or stylelint before that, which means yes we don't support these kind of configurations. But the need for applying postcss before Astro even compiles it with id suffixes is niche IMO that it doesn't need to be documented.
