### ISSUE TITLE
Infinite 404 loop in prod on Vercel

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#9028]
### Astro Info

```block
Astro                    v3.4.4
Node                     v21.1.0
System                   Windows (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### Describe the Bug

When vercel's "cleanUrls" config is enabled and `404.astro` is prerendered - either explicitly or because of hybrid mode - visiting any path not routed would lead to an infinite loop which gets intervened by Vercel's infrastructure.

### What's the expected result?

`404.html` gets served.

### Link to Minimal Reproducible Example
https://infinite-rerouting.vercel.app/afsfasbj
https://github.com/lilnasy/vercel-infinite-loop/commit/087871b115227025b76cc3faef2d183d7daf55c6

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dreyfus92** [comment]
As discussed previously with @lilnasy, there is a workaround on how to fix this, just by adding to your `vercel.json` the `route` key with the following:

```json
{
  ...
  "routes": [
    { "handle": "filesystem" },
    { "src": "/(.*)", "status": 404, "dest": "/pages/your-custom-404.html" }
  ]
}
```

Or by just removing `cleanUrls` from it should the work.

**Comment by rishi-raj-jain** [comment]
@lilnasy can you update the reproduction? Can't seem to have the access to the repo.

**Comment by lilnasy** [comment]
Missed that, thanks!

I would start looking here:
https://github.com/withastro/astro/blob/a888e985384918798e7c2f203e0dee48a4a21225/packages/astro/src/core/app/index.ts#L284

I know this because it's me (hi).

I plan to remove the need for the code linked as part of [the reroute API proposal](https://github.com/withastro/roadmap/discussions/681). For now, I don't see a way around without special casing vercel. If you find one, please open a PR.
