### ISSUE TITLE
⚠️ Issue: Confusion with the minimum Node.js version needed to run astro.

### ISSUE THREAD

**Issue by atapas** [withastro/astro#9031]
Here (https://docs.astro.build/en/tutorial/1-setup/1/),

The doc says the minimum node version needed is version v18.14.1 or later.

For me `node-v` gives v18.18.2 but when I try installing astro using the command `yarn create astro@latest` I am getting the following error

<img width="1486" alt="image" src="https://github.com/withastro/docs/assets/3633137/65797d1a-b2d0-4407-a2c8-d4504391240f">

**Comment by atapas** [comment]
Just FYI... it works well with npm and pnpm along with Node 18.x. Yes it fails with yarn alone.

**Comment by Princesseuh** [comment]
`create-strapi-app` is not a dependency of Astro. You may have it installed globally on your system?
