### ISSUE TITLE
set:html renders anchors outside of parent anchor

### ISSUE THREAD

**Issue by rohannelson** [withastro/astro#9033]
### Astro Info

```block
Astro                    v3.4.4
Node                     v18.14.2
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When passing an anchor via set:html e.g. `set:html={'<a>Hello</a>'}`, if it is a descendant of an anchor it will be rendered outside of the parent anchor.

### What's the expected result?

The anchor passed to set:html renders outside of its parent anchor.

### Link to Minimal Reproducible Example

https://github.com/rohannelson/testingSetHtml

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
If you take a closer look at your build output, the `a` is correctly nested inside of the `a` in the generated HTML.

```html
<a href="https://astro.build/chat/" data-astro-cid-dohjnao5><h2 data-astro-cid-dohjnao5>Community<span data-astro-cid-dohjnao5>&rarr;</span></h2><p data-astro-cid-dohjnao5>Come say hi to our amazing Discord community. ❤️</p><a>Hello</a></a>
```

The behavior you're seeing is how a browser "corrects" invalid markup. Per the HTML spec, `a` cannot be rendered inside of another `a` tag.

**Comment by rohannelson** [comment]
Ah, right. Okay, thanks for that.
