### ISSUE TITLE
Use `yarn astro add react` command error

### ISSUE THREAD

**Issue by peng** [withastro/astro#9046]
### Astro Info

```block
warning package.json: No license field
$ astro add react
⚠ react is not an official Astro package. Use at your own risk!
✔ Continue? … yes
✖ react doesn't appear to be an integration or an adapter. Find our official integrations at https://astro.build/integrations
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### If this issue only occurs in one browser, which browser is a problem?

cli

### Describe the Bug

I found fetch package `400` error in `fetchPackageJson` function. This function in astro/dist/cli/add/index.js file.  But error show `react is not an official Astro package`. It perplexes me.

I use my company registry, It is not standard.

### What's the expected result?

Show more error info.
Support like this:
<img width="906" alt="image" src="https://github.com/withastro/astro/assets/26745086/b3645c7c-d608-433e-9baf-01682255dfff">
<img width="1194" alt="image" src="https://github.com/withastro/astro/assets/26745086/048433dc-6358-4d32-a354-71fadbda8b4b">

### Link to Minimal Reproducible Example

cli no link

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Looks like the error intends to catch 404 for packages that don't exist. Maybe we should check for 404 explicitly and throw an Error if not. The warning should only be showed for 404s.

**Comment by peng** [comment]
> Looks like the error intends to catch 404 for packages that don't exist. Maybe we should check for 404 explicitly and throw an Error if not. The warning should only be showed for 404s.

In fact it catch 400 code. Can I change like above image red box show ?

**Comment by bluwy** [comment]
Yeah that also works for me. Make sure you're logging `firstPartyPkgCheck.message` though to print the string only.
