### ISSUE TITLE
Can't add middleware with integrations

### ISSUE THREAD

**Issue by pilcrowOnPaper** [withastro/astro#9047]
### Astro Info

```block
Astro                    v3.5.0
Node                     v20.2.0
System                   macOS (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             middleware-test
```

### Describe the Bug

Running a basic project with the following config:

```ts
// astro.config.mjs
export default defineConfig({
  integrations: [
    {
      name: "middleware-test",
      hooks: {
        "astro:config:setup": ({ addMiddleware }) => {
          addMiddleware({
            order: "pre",
            entrypoint: "./middleware.js",
          });
        },
      },
    },
  ],
});
```
```ts
// middleware.js
export const onRequest = async (_, next) => {
  console.log("middleware running...");
  return await next();
};
```

leads to an error:

```
[vite] Error when evaluating SSR module @astro-middleware: failed to import "undefined"
|- Error: Cannot find module 'undefined' imported from '@astro-middleware'
    at nodeImport (file:///Users/root/code/astro-integration-middleware/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56088:25)
    at ssrImport (file:///Users/root/code/astro-integration-middleware/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55990:30)
    at eval (@astro-middleware:3:50)
    at instantiateModule (file:///Users/root/code/astro-integration-middleware/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)

Failed to load url undefined (resolved id: undefined) in @astro-middleware. Does the file exist?
```

### What's the expected result?

No errors

### Link to Minimal Reproducible Example

https://github.com/pilcrowOnPaper/astro-integration-middleware

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pilcrowOnPaper** [comment]
Same issue when using `@astrojs/node`

**Comment by pilcrowOnPaper** [comment]
I'm not sure if it's helpful, but the logs are different when defining files that exist compared to those that don't

File that exists:

```
Failed to load url undefined (resolved id: undefined) in @astro-middleware. Does the file exist?
```

File that doesn't exist:

```
Failed to load url undefined (resolved id: undefined) in @astro-middleware. Does the file exist?
Failed to load url random-file.js (resolved id: random-file.js) in @astro-middleware. Does the file exist?
```

**Comment by pilcrowOnPaper** [comment]
It's likely not related but `addMiddleware()` uses `entrypoint`, while every other API uses `entryPoint`

**Comment by matthewp** [comment]
Thanks! Will take a look and fix today.

**Comment by matthewp** [comment]
@bluwy is that a separate issue? I think not handling relative *is* the issue here?

I wonder if we should even support that. Given that integrations are shared as packages, using relative is going to resolve from the `pwd` (if we fix it) which isn't what you want. Maybe we should error and suggest using `fileURLToPath` pattern (or the package name)?

**Comment by pilcrowOnPaper** [comment]
@matthewp Doesn't work both absolute and relative paths

**Comment by MoustaphaDev** [comment]
The issue here is that we're trying to load the main middleware (in `src/middleware`) even when it doesn't exist. The line that bluwy showed should be conditional.
Mind if I make a PR @matthewp?

**Comment by bluwy** [comment]
> @bluwy is that a separate issue? I think not handling relative _is_ the issue here?

Yeah the relative path thing is another issue. `addClientDirective` is currently resolving from `process.cwd()` so maybe we can align on that. But I also generally agree that an absolute path is safer if we want to enforce it.

Looks like the comment above covered the `undefined` issue, where it's because `src/middleware` doesn't exist.

**Comment by matthewp** [comment]
@lilnasy is working on fix 🙏

**Comment by lilnasy** [comment]
The fix is done and tested but @ematipico is working on a proper one.
