### ISSUE TITLE
View transition forms do not work for same-page `action`

### ISSUE THREAD

**Issue by bholmesdev** [withastro/astro#9056]
### Astro Info

```block
Astro                    v3.5.1
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  none
Integrations             none
```

### Describe the Bug

I created a form with the current page as the `action` target. When using `<ViewTransitions handleForms />`, nothing happens when I click submit. Confirmed there are no server-side or client-side errors, and no request is sent on the network tab. I also noticed using a different action target (ex. `/request`), view transitions work as expected.

### What's the expected result?

I expect the form request to go to the current page and satisfy the `Astro.method === 'POST'` check.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tkfcdo?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Closed by https://github.com/withastro/astro/pull/9055
