### ISSUE TITLE
object label during build with verbose logging

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#9060]
### Astro Info

```block
Astro                    v3.5.2
Node                     v18.16.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             config-watcher
                         auto-import
                         @astrojs/sitemap
                         @astrojs/asides
                         astro-expressive-code
                         @astrojs/mdx
```

### Describe the Bug

Running build with vebose logging shows wrong label during page generation.
**Repro:** Create new project and run `npm run build -- --verbose` or `pnpm build --verbose`

```shell
 generating static routes 
▶ src/pages/index.astro
  astro:[object Object] build Generating: / [] +909ms
  └─ /index.html (+22ms)
Completed in 32ms.

  astro:[object Object] build Additional assets copied   1699642039.4s [] +10ms
07:47:22 PM [build] 1 page(s) built in 0.96s
07:47:22 PM [build] Complete!
```

### What's the expected result?

Correct label

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dxd52u?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
@matthewp might have more context on this... I'm not sure why the signature of our `debug` function is different than all our other logging methods. https://github.com/withastro/astro/blob/13ca6d989b91c4575517495647fc10ba8306cf88/packages/astro/src/core/logger/core.ts#L86-L90

It seems like modifying https://github.com/withastro/astro/blob/13ca6d989b91c4575517495647fc10ba8306cf88/packages/astro/src/core/logger/node.ts#L110 to match the following fixes the problem, but it's a bit of a hack.

```diff
export function debug(type: string, ...messages: Array<any>) {
+	if (typeof type !== 'string') {
+		type = messages[0];
+		messages = messages.slice(1);
+	}
	const namespace = `astro:${type}`;
	debuggers[namespace] = debuggers[namespace] || debugPackage(namespace);
	return debuggers[namespace](...messages);
}
```
