### ISSUE TITLE
Content Collection cache not invalidated on content changes

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#9061]
### Astro Info

```block
Astro                    v3.5.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Using the experimental content collection cache generates pages with outdated content.
Ex. changing a word in a blog post MDX still generates page with the old text. See README in repro.

### What's the expected result?

Changes to MDX content source should invalidate cached entry and render page again.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-i7afd2?file=README.md,src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fflaten** [comment]
Using `--force` fixes this obviously, but I assume this should have triggered a checksum error and invalidated the entry. 🙂 

Side note: Changing styles like switching shiki-theme is also not reflected in a cached build. Same issue? Separate issue? Or by design that should always require the users to clear cache?

**Comment by natemoo-re** [comment]
You're correct, these changes should be picked up and invalidated automatically. Working on a fix!

**Comment by distinctperspective** [comment]
Any update on this fix?

**Comment by Princesseuh** [comment]
Confirming that this still happens despite the recent fixes to CCC
