### ISSUE TITLE
Persisted navigation component state not being preserved on page transition 

### ISSUE THREAD

**Issue by moaali** [withastro/astro#9065]
### Astro Info

```block
Astro                    v3.5.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

I forked the 3d Viewer app demo from Astro's Pinned Tweet.

What I was trying to achieve with the demo is very simple, in theory, which is adding a small activity indicator under links and make that indicator animate left and right smoothly from the previous link center point to the center of the link that's currently active.

Provided a Stackblitz demo forked from the main demo with all the deps updated to the latest versions

Currently if you viewed that demo you will see that the indicator always shows at the correct position immediately but with no animation like if the navigation component is re-rendered on each route navigation. Also if you tried to click the nav links, quickly enough, you will notice that the navigation link doesn't work until the page transition completes.

Any quick thoughts about a fix or a workaround?

### What's the expected result?

1. The activity indicator should be moving smoothly from previous link center to current link center
2. Links should be immediately clickable even during page transitions?

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/moaali/astro-3d-view-transitions

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
In the `style` tag of the element you're animating, you can add `viewTransitionName": "line"` (any unique value works) and the browser will animate it. I'm not sure about the link navigation delays though so leaving this open for now.

**Comment by matthewp** [comment]
During a transition the page is screenshotted, so that's why you can't click on the links until it's complete. This is a known limitation of view transitions.
