### ISSUE TITLE
Scoped styles not being applied

### ISSUE THREAD

**Issue by hoqn** [withastro/astro#9066]
### Astro Info

```block
Astro                    v3.5.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Firstly, please forgive my lack of English as it is not my first language :)

After updating to version 3.5.2, the stylesheet is not being applied on some pages.

After taking a closer look at the problem, I realised that **if there is any code that fetches content, such as `getCollection`, the style is not applied on that page.** (I don't know if this is related, but it appears as `<style>undefined</style>` in the rendered html).

This issue appears to be the same in 3.5.1, and doesn't seem to be present in versions prior to 3.4.4.

I've reproduced the same situation in the stackblitz below.
Thanks :)

### What's the expected result?

Scoped styles must be applied

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-giqnfl?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Thanks for the detailed investigation!
This seems to be a regression caused by content collections cache in 3.5.

**Comment by lilnasy** [comment]
I see what the issue is:
https://github.com/withastro/astro/blob/1eb5d7fa7e8c0b046b794aedcb505c251ce2e9f9/packages/astro/src/content/vite-plugin-content-assets.ts#L147

Workaround:
```ts
export default defineConfig({
  experimental: {
    contentCollectionCache: true
  }
})
```

**Comment by lilnasy** [comment]
I think I see what the issue is:
https://github.com/withastro/astro/blob/1eb5d7fa7e8c0b046b794aedcb505c251ce2e9f9/packages/astro/src/content/vite-plugin-content-assets.ts#L147

Workaround:
```ts
export default defineConfig({
  experimental: {
    contentCollectionCache: true
  }
})
```

**Comment by natemoo-re** [comment]
Sorry about this! I just opened a PR with a fix. https://github.com/withastro/astro/pull/9069

Just waiting on a review so we can merge and release this.
