### ISSUE TITLE
`ReadableStream` in response body not canceled when client closes connection

### ISSUE THREAD

**Issue by pilcrowOnPaper** [withastro/astro#9068]
### Astro Info

```block
Astro                    v3.5.2
Node                     v20.2.0
System                   macOS (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
```

### Describe the Bug

When implementing server-sent events, `cancel()` is not called when client closes the connection (e.g. closes the tab).

```ts
export async function GET() {
  const stream = new ReadableStream({
    start(controller) {
      // do stuff
    },
    cancel() {
      console.log("cancelled");
    },
  });
  return new Response(stream, {
    headers: {
      "X-Content-Type-Options": "nosniff",
      "Content-Type": "text/event-stream; charset=utf-8",
      "Transfer-Encoding": "chunked",
    },
  });
}
```

### What's the expected result?

`cancelled` is logged to the console

### Link to Minimal Reproducible Example

https://github.com/pilcrowOnPaper/astro-readable-stream-bug

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by pilcrowOnPaper** [comment]
I don't think I know enough about the code base to make a PR, but fix would look something like this:

```ts
const reader = await webResponse.body.getReader();
res.on("close", () => {
   reader.cancel();
})
let result = await reader.read();
while (!result.done) {
   res.write(result.value);
   result = await reader.read();
}
```

**Comment by tarekwiz** [comment]
@lilnasy This doesn't work on dev. Only after build.

**Comment by ruohki** [comment]
> @lilnasy This doesn't work on dev. Only after build.

THIS IS SUCH A BANGER INFO ... I've been pulling my hair out about this.

**Comment by asleepace** [comment]
> > [@lilnasy](https://github.com/lilnasy) This doesn't work on dev. Only after build.
> 
> THIS IS SUCH A BANGER INFO ... I've been pulling my hair out about this.

lmao damn same... 😄
