### ISSUE TITLE
`import filename from "file?url"` not working

### ISSUE THREAD

**Issue by junaga** [withastro/astro#9073]
### Astro Info

```block
Astro                    v3.5.2
Node                     v18.17.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

## Heads up

not reproducible in https://stackblitz.com/

---

I have several SSR `.astro` pages that depend on binary files. When i import them with `?url` they are included in `dist/client/` not in `dist/server/`, as if they were part of the `public` directory.

With the setup below, `astro dev` does work as intended, but `astro build` does not.

### `src/pages/index.astro`

```astro
---
import binary = "../lib/binary-x86_64-linux?url" // the file is executable
import { exec } from "node:child_process"
import { promisify } from "node:util"

const str = (await promisify(exec)("./" + binary)).stdout
const lsStr = (await promisify(exec)("ls")).stdout
---

<!doctype html>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width" />

<pre>{str}</pre>
<pre>{lsStr}</pre>
```

### `astro.config.js`

```js
import nodejs from "@astrojs/node"
import react from "@astrojs/react"

export default {
	output: "server",
	adapter: nodejs({ mode: "middleware" }),

	integrations: [react()],
	publicDir: "src/public/"
}
```

### What's the expected result?

I need these assets on server-side only, they should not be accessible by the user.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-t95zzz?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by junaga** [comment]
on discord someone had the same issue https://discord.com/channels/830184174198718474/1149765290637398107

**Comment by matthewp** [comment]
Aside from being in the wrong folder, you can't rely on a file being relative in build the same way that they are in development. The JavaScript is bundled and put in another location, so even if the file where in `dist/server/` it would still not be relative to your component's code.

Probably what I would recommend here is keeping the binaries outside of `src/`, then create an [integration](https://docs.astro.build/en/reference/integrations-reference/) that copies it into `dist/server/` in the build. Even in this scenario you're going to have to write some code to find the binary as it's not going to be in a relative position. So this is just a use-case that Astro doesn't help you a ton with, aside from having the integration API.

Going to close as this isn't something Astro guarantees, happy to continue helping with a solution here though.

Btw, if you did create an integration, this would be a great kind of thing to have as an OS project as I'm sure other people have this sort of need. If it can be done in a generic way.

**Comment by junaga** [comment]
@matthewp I would like to try making an extension. Could you then give it a look and tell me what i could do better?
