### ISSUE TITLE
htmx script lost using `ViewTransition`

### ISSUE THREAD

**Issue by brunocascio** [withastro/astro#9074]
### Astro Info

```block
Astro                    v3.5.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When use `ViewTransition` and the page get transitioned to a new one, the htmx script is lost. Doing a full reload it works without any problem.

A way to reproduce it using the stackblitz provided:

1. Open it, it will show a blank page with a "Page" link
2. Click on "Page" link, it will open the page which contains the htmx attributes
3. Press the button and nothing happen
4. Perform a full reload, the button now works

Both pages are using the same Layout, which includes the htmx script

### What's the expected result?

The htmx script should be loaded and available on every page

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jubmf5?file=src%2Flayouts%2FLayout.astro,src%2Fpages%2Findex.astro,src%2Fpages%2Fpage-with-htmx.astro,src%2Fpages%2Fpartials%2Ftest.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
You should use htmx' [process](https://htmx.org/api/#process) function to attach listeners to the new html content. I tried that in your reproduction and that fixed it!
