### ISSUE TITLE
Rss can't generate after add i18 support in astro.config.mjs

### ISSUE THREAD

**Issue by fatbobman** [withastro/astro#9081]
### Astro Info

```block
Astro                    v3.5.3
Node                     v18.18.2
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Safari, Chrome

### Describe the Bug

I add i18 support in astro.config.mjs. After that, I can't generate rss file in dist folder.
when I comment the i18 configuration , rss generator works.
```mjs
   experimental: {
     i18n: {
      defaultLocale: 'zh',
      locales: ['en', 'zh'],
      routingStrategy: 'prefix-always',
    }
  },
```

### What's the expected result?

rss generate after add i18 support in astro.config.mjs

### Link to Minimal Reproducible Example

https://github.com/fatbobman/AstroRSSIssue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by itsmatteomanf** [comment]
Unfortunately the current implementation, with `prefix-always`, makes it so basically no files can be generated in the root, without any locale prefix.

Here is the RFC for the experimental i18n support, which mentioned this issue...
https://github.com/withastro/roadmap/pull/734#issuecomment-1806568884
