### ISSUE TITLE
Starlight is broken with Content Collections Build Cache

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/astro#9086]
### What version of `starlight` are you using?

v0.12.0

### What version of `astro` are you using?

v3.5.3

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

MS Edge

### Describe the Bug

When I init my project, I add the new experimental **Content Collections Build Cache** in `astro.config.mjs`. The homepage is broken like this image:

![image](https://github.com/withastro/starlight/assets/27698189/84f9fce1-e3d3-439e-9a2c-19e519d88a5b)

### Link to Minimal Reproducible Example

https://github.com/AREA44/starlight-tailwind-template

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for the report! For now I’d recommend disabling the flag while we work on a fix! I am in the process of refactoring how the build works.

**Comment by Princesseuh** [comment]
Testing it on the latest version, everything seems to work now.
