### ISSUE TITLE
<tr> in {} broke the build process

### ISSUE THREAD

**Issue by jamesli2021** [withastro/astro#9104]
### Astro Info

```block
Expected "}" but found "$$render" I have narrowed down that <tr> in {} scope cause the error while it works fine before the update.
```

### If this issue only occurs in one browser, which browser is a problem?

NA

### Describe the Bug

Update to latest version today and it broke during build process.

`Expected "}" but found "$$render"`

### What's the expected result?

Should not broke with <tr>...<tr> element in JSX scope. Need urgent update.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Fixed in https://github.com/withastro/compiler/pull/889. You can run `npm update @astrojs/compiler` to fix it.
