### ISSUE TITLE
Assets Cache-Control should be more aggressive

### ISSUE THREAD

**Issue by belluzj** [withastro/astro#9106]
### Astro Info

```block
Astro                    v3.5.4
Node                     v18.16.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/vue
```

### Describe the Bug

With the node adapter, it looks like static assets, with a hash in their filenames, get by default a max-age=0 cache control policy, which doesn't take advantage of hashing the names in the first place (from what I understand?).

Steps to reproduce:
- Run `astro build` then `node dist/server/entry.mjs`
- Look at assets in the Network Tab (filter by _astro/)
- The Cache-Control says `max-age=0`

![image](https://github.com/withastro/astro/assets/3616772/1370585b-ceb6-4c9a-b523-16b50e230b8f)

### What's the expected result?

The default max-age could be 1 year (or any very high value) because assets have a hash of their contents in the file name.

I tried following the JS code inside the node adapter to find out where the max-age=0 is coming from, but couldn't figure it out, so unfortunately I can't contribute a fix.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zhox1r?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by belluzj** [comment]
This also prevents us from having a longer cache-control on the HTML, because just after deploying a new version of the site, we get in a situation where the HTML is from the previous version (cached), but the assets that go with it have disappeared (because they're not cached), so we get unstyled HTML.

It's also not possible to work around this ourselves easily while using the node adapter because the Astro middleware (were we could set some caching policy) doesn't seem to run around static assets (which is OK because apart from caching there's not much use for middleware on static assets).

**Comment by matthewp** [comment]
Yeah I agree. I believe anything in the `_astro` folder can be given immutable cache headers. Would gladly accept a PR if you wanted to add this to the Node adapter!

**Comment by belluzj** [comment]
Unfortunately I didn't manage to follow the code of the adapter, I tried but couldn't figure out where the max-age=0 comes from. I could have a second look later if no-one else is available to look into it.

**Comment by matthewp** [comment]
I'm taking a look now to see if its a small change.

**Comment by matthewp** [comment]
PR in https://github.com/withastro/astro/pull/9125

**Comment by belluzj** [comment]
Thanks a lot @matthewp!

**Comment by rishi-raj-jain** [comment]
This is great!

**Comment by peterhirn** [comment]
For anyone deploying to Cloudflare, just add this file to your project:

`/public/_headers`
```
/_astro/*
  Cache-Control: public, max-age=31536000, immutable
```
