### ISSUE TITLE
Setting a i18n.fallback option that maps to the defaultLocale leads to client-side js been removed.

### ISSUE THREAD

**Issue by kossidts** [withastro/astro#9108]
### Astro Info

```block
Astro                    v3.5.4
Node                     v20.8.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/preact
                         @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/mdx
                         @astrojs/solid-js
```

### Describe the Bug

Setting the **i18n.fallback** option to match the **defaultLocale** in the configuration results in the removal of client-side JavaScript during the build process.

 At least client-side scripts are not sent to the browser and hence no client-side interaction possible.

```experimental: {
        i18n: {
            defaultLocale: "en",
            fallback: {
                de: "en", // <-- Issue: Client-side JS is removed
                // de: "fr", // Works
                // fr: "de", // Works
            },
            locales: ["en", "de", "fr"],
        },
    },
```

### What's the expected result?

The configuration should allow setting **i18n.fallback** to match **defaultLocale** without causing the removal of client-side JavaScript during the build. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-chtnz4?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@kossidts thank you for reporting. I opened your reproduction but I am at a loss because I don't know how to replicate the issue and what I should expect. Could you please add some instructions that tells me how to replicate the issue in the reproduction, and what's the expected result **in the reproduction**?

**Comment by kossidts** [comment]
Thank you, @ematipico, for your prompt response. Apologies for the oversight in my initial report. I've updated the reproduction code and the readme file to include some instructions for replicating the issue.

So please refer to the readme file for detailed instructions. But basically 
- Stop the the mode and run `npm run build && npm run preview`
- Observe that the button with a client-side click event functions correctly, changing the background color as expected.
- Stop the process and modify the astro.config.mjs by setting up the fallback to match the defaultLocale value i.e.
```js
i18n: {
    defaultLocale: 'en',
    fallback: {
      de: 'en', // issue removes client js
      // de: 'fr',
      // fr: 'de',
    },
    locales: ['en', 'de', 'fr'],
  },
```
- Now re-run `npm run build && npm run preview` and notice that the button ceases to function.

Here a record of reproduction.

![Astro-isssue](https://github.com/withastro/astro/assets/5726972/98ad94b0-60e4-4bc2-aea2-73cec29a3adb)
