### ISSUE TITLE
Script in Astro component doesn't work after going to another route

### ISSUE THREAD

**Issue by SantosAlarcon** [withastro/astro#9113]
### Astro Info

```block
Astro                    v3.5.4
Node                     v21.2.0
System                   Linux (x64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/netlify
Integrations             none
```

### Describe the Bug

Good morning. I am using Astro for a side project, and I have a mobile navbar **Astro component** with a `<script>` tag. When the page loads, the code that's inside script loads. But when I navigate to other route, the script doesn't load. 

IDK if there is a way to reload the script thing of the Astro component when I navigate to other route.

### What's the expected result?

Script still executes after you navigate to other route.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/github/SantosAlarcon/astro-anime/master?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp134a9e00072v6e9jzwt6cx%2522%252C%2522sizes%2522%253A%255B65.06953223767383%252C34.930467762326174%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp134a9d00032v6e1bv4okuj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp134a9d00052v6e1giqfhev%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp134a9d00062v6eq732m00q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp134a9d00032v6e1bv4okuj%2522%253A%257B%2522id%2522%253A%2522clp134a9d00032v6e1bv4okuj%2522%252C%2522activeTabId%2522%253A%2522clp134rjp00af2v6enosj6epy%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp134a9c00022v6eqjv6h2p6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252Ffragments%252FAnimeDetails%252Findex.astro%2522%252C%2522id%2522%253A%2522clp134rjp00af2v6enosj6epy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clp134a9d00062v6eq732m00q%2522%253A%257B%2522id%2522%253A%2522clp134a9d00062v6eq732m00q%2522%252C%2522activeTabId%2522%253A%2522clp13691v00jc2v6e0wdpv6fv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522id%2522%253A%2522clp13691v00jc2v6e0wdpv6fv%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clp134a9d00052v6e1giqfhev%2522%253A%257B%2522id%2522%253A%2522clp134a9d00052v6e1giqfhev%2522%252C%2522activeTabId%2522%253A%2522clp134bsl006w2v6e1k0rxtcc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp134a9d00042v6e5rxtdgn7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp134akr002zefdn69860dbw%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clp134bsl006w2v6e1k0rxtcc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clp13686400fa2v6e8rs0a6v6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
When using view transitions, you need to rerun the scripts on page changes. See https://docs.astro.build/en/guides/view-transitions/#script-behavior-during-page-navigation for more information.

**Comment by SantosAlarcon** [comment]
Thank you very much!

**Comment by Chebaleomkar** [comment]
its bcz viewTransition  . remove it from code and it will fix the error
