### ISSUE TITLE
Building form and POST request to API doesn't work

### ISSUE THREAD

**Issue by teinett** [withastro/astro#9117]
### Astro Info

```block
Astro                    v3.5.5
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

any

### Describe the Bug

I created form, using recipe https://docs.astro.build/en/recipes/build-forms-api/.
The code doesn't work. 
I don't receive any result from the form, and also it acts as GET request, not the POST.

**Example**: https://stackblitz.com/edit/github-59rrer

### What's the expected result?

1. It's POST request, so I don't see the text from any field in the URL.
What I see is the text from each field, as it would be with GET request: 
https://github59rrer-1baw--4321--420f2654.local-corp.webcontainer.io/?name=ana&email=a%40test.ro&message=fff - 

2. I will see the responseMessage in the form after request.
I don't see this responseMessage in the form. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-59rrer

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexgipi** [comment]
It doesn't seem to be an Astro issue in this case. When you use a component from Svelte, React, Vue, etc., you need to specify when the scripts will be loaded. In this case, you would need to add **client:load.**

`<FeedbackForm client:load/>`

Now you should receive the fields at your endpoint.

```
export const POST: APIRoute = async ({ request }) => {
    const data = await request.formData();
    const name = data.get('name');
    const email = data.get('email');
    const message = data.get('message');

    console.log({name, email, message});

    ...

}
```

**Comment by matthewp** [comment]
Thanks for the assist @alexgipi! @teinett can you try the suggest and see if it clears up your issue?

**Comment by teinett** [comment]
https://stackblitz.com/edit/github-59rrer?file=src%2Fpages%2Findex.astro - I added `client:load`, and it works now.
