### ISSUE TITLE
`clientAddress` not working

### ISSUE THREAD

**Issue by junaga** [withastro/astro#9124]
### Astro Info

```block
Astro                    v3.5.5
Node                     v18.17.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### Describe the Bug

Both `Astro.clientAddress` in pages and `context.clientAddress` in endpoints return a Link-local IP address.

### What's the expected result?

Both should return the HTTP request client address.

### Link to Minimal Reproducible Example

repro is breaks in stackblitz. I have

```js
export default defineConfig({
  output: 'server',
  adapter: nodejs({ mode: 'middleware' }),
});
```

yet it errors

```sh
Astro.clientAddress` is only available when using `output: 'server'` or `output: 'hybrid'`. Update your Astro config if you need SSR features.
```

https://stackblitz.com/edit/github-jagk5g?file=src%2Fpages%2Findex.astro,src%2Fpages%2Fendpoint.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by junaga** [comment]
`::ffff:169.254.1.1` is the address i got back

**Comment by matthewp** [comment]
Here's the code for this: https://github.com/withastro/astro/blob/main/packages/integrations/node/src/get-network-address.ts

Unclear to me if this is a case of a bug in the code or if the address is not available. Have you tried debugging this?

**Comment by junaga** [comment]
no, i did not try anything, this one is way above my experience. I am using Firebase Hosting with experimental webframework detection to deploy.

**Comment by rishi-raj-jain** [comment]
@junaga

How can I reproduce this? Which platform are you deploying to? I can see this working fine on localhost.

**Comment by rishi-raj-jain** [comment]
![image](https://github.com/withastro/astro/assets/46300090/147f2997-af83-40b2-9e2a-37eff287dccc)

**Comment by junaga** [comment]
@rishi-raj-jain Hi I am using **"Firebase Hosting with experimental webframework detection"**. you can checkout this [demo](https://github.com/withastro/astro/issues/9124#issuecomment-1817570014)

**Comment by rishi-raj-jain** [comment]
Thanks for providing that.


So, per https://github.com/arvidn/libtorrent/issues/6063 and quick IP search of the IP displayed in your demo (see the same IP appears even when the URL is viewed in different regions)

- ![Screenshot 2023-11-18 at 11 16 36 PM](https://github.com/withastro/astro/assets/46300090/28a98c30-736e-4f29-92fe-396d155ba1ec)

- ![Screenshot 2023-11-18 at 11 17 10 PM](https://github.com/withastro/astro/assets/46300090/defddfe0-c7c5-4503-b64d-a6b8342053f6)

indicate that this is picking up local-link address https://datatracker.ietf.org/doc/html/rfc3927

![Screenshot 2023-11-18 at 11 18 14 PM](https://github.com/withastro/astro/assets/46300090/a4ea7726-388f-449f-96d2-a97a3fa74583)

**Comment by rishi-raj-jain** [comment]
@junaga 

While I've never tried Firebase Hosting, can you help me with the following change in your `astro.config.mjs` to accurately debug:

```
  server: {
    port: 3000,
    host: '0.0.0.0',
  },
```

**Comment by rishi-raj-jain** [comment]
I think this should solve it exposing it to the public address which will be broadcasted by Firebase Hosting?

**Comment by lilnasy** [comment]
Firebase functions are likely behind multiple reverse proxies, the address you see might belong to one of them.

In cases like this, the real visitor's address is usually provided in a header, `X-Forwarded-For` for example. You could log all headers to find out if firebase forwards them.

**Comment by lilnasy** [comment]
Closing as the Astro API is behaving as expected. The "client" simply does not happen to be the human visitor in this case, but an intermediate server instead.
