### ISSUE TITLE
Node adapter does not support `build.format: "file"` for prerendered pages

### ISSUE THREAD

**Issue by cdtut** [withastro/astro#9128]
### Astro Info

```block
Output                   hybrid
Adapter                  @astrojs/node
```

### Describe the Bug

In dev server /file shows `file.astro` content and all other paths use `[param].js`.

After building project /file uses `[param].js` not `file.astro`.

### What's the expected result?

Build mode should do same thing as dev mode. First return SSG routes then SSR static routes then SSR dynamic routes last.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1o5lsw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
@cdtut 

I just had a look at your repro.

The steps I followed:

```bash
npm i
npm run build
npm run preview
```

Go to localhost:4321/file I see the file's content
Go to localhost:4321/whatif I see the not found response
Go to localhost:4321/example I see the page getting redirected to /redirect

I think this is working as expected.

**Comment by cdtut** [comment]
Add `build: { format: "file" }}` to astro config. `npm run preview` and `node dist/server/entry.mjs` should work with this.

**Comment by lilnasy** [comment]
`build.`format` is intended for static file servers that expect the html files to be named differently. Node is not one of these servers. It seems reasonable to me for it to expect only the default file naming. What is the use case?

**Comment by cdtut** [comment]
build.format sets the structure of output files but it shouldn't change what page appears for a path. If you go to /file it should use it first if /file exists in all cases. Should be consistent between build.format `file` or `directory`. And should be consistent between `standalone` and `middleware` mode.

**Comment by lilnasy** [comment]
Yeah, that sounds like a nice enhancement. Thanks for opening this issue!

I know you unchecked the participation checkbox but this would be a simple fix!

We use an npm library called `send` to handle static files in the node adapter. That part is here: https://github.com/withastro/astro/blob/306781795d5f4b755bbdf650a937f1f3c00030bd/packages/integrations/node/src/http-server.ts#L40-L43

The library apparently has an [`extensions`](https://www.npmjs.com/package/send#extensions) option that can match `/file` to `client/file.html` on disk.

If you want more context about how astro, integrations, and the node adapter work, I'd be happy to guide you in the `#dev` channel of our discord: https://astro.build/chat/.

**Comment by cdtut** [comment]
I don't understand this code. Can you explain? In 4.0 the bug is being fixed for index.astro location so it will make a difference in next version.

**Comment by lilnasy** [comment]
Which code do you mean?

The change in 4.0 will make `src/pages/x/index.astro` output to `dist/client/x/index.html`. Whereas  it currently goes to `dist/client/x.html`, overwriting the output of `src/pages/x.astro` which writes to the same location. The node adapter in its current state will serve only the files named "index.html".

I should point out again though, the configuration is intended for when your static file server doesn't work with the default format. What is the use case for using build.format with node?

**Comment by cdtut** [comment]
> I should point out again though, the configuration is intended for when your static file server doesn't work with the default format. What is the use case for using build.format with node?

I don't understand what you're saying about node and static file servers but does it change anything? There are cases to want files generated as name.html not name/index.html. `npm run preview` and `node dist/server/entry.mjs` should work normally in all cases but they don't.

Can this be P1 bug? The site is impossible to even preview the built version and impossible to deploy to server.

**Comment by kamranahmedse** [comment]
This looks same as https://github.com/withastro/astro/issues/9128 and should be fixed by PR https://github.com/withastro/astro/pull/9080
