### ISSUE TITLE
Port conflict

### ISSUE THREAD

**Issue by cdtut** [withastro/astro#9133]
### Astro Info

```block
Node                     v20.8.0
System                   Linux (x64)
```

### Describe the Bug

Start `astro dev` and it start on 4321. Start `astro dev` again and it start on next available port 4322.

Run `astro preview` and there is error `EADDRINUSE: address already in use ::1:4321`.

Run `node dist/server/entry.mjs` and it say `[@astrojs/node] Server listening on http://127.0.0.1:4321` even though process already running on 4321.

### What's the expected result?

1. `astro preview` should open on next available port 4322.
2. `node dist/server/entry.mjs` should have error `EADDRINUSE: address already in use ::1:4321`.
3. `astro preview` should have command line option `--port` and astro config file option to change port to try first.
4. node adapter should have host and port options that are used as default if environment variable not given. Not every build process can provide environment variables (https://docs.astro.build/en/guides/integrations-guide/node/#runtime-environment-variables).

```
adapter: node({
    host: "0.0.0.0",
    port: "4321"
})
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1o5lsw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by cdtut** [comment]
There is `server.host` and `server.port` which is used by dev server and node adapter. `host` and `port` should be possible to pass to node adapter to be different from dev which is needed if running dev and build together.

Another problem is passing `host: "0.0.0.0"` prints `[@astrojs/node] Server listening on http://localhost:4321` but should print `0.0.0.0` instead of `localhost`. To be consistent with how it's printed in other places `Error: listen EADDRINUSE: address already in use 0.0.0.0:4321`.

**Comment by matthewp** [comment]
@bluwy surprising to me, we are fully using Vite for preview server now, right?

**Comment by bluwy** [comment]
We use Vite's preview server for `astro preview` only (mostly for static sites). The nodejs adapter's preview server is rather simple and doesn't handle it specially, but maybe we're swallowing the `EADDRINUSE` error somewhere.

**Comment by bluwy** [comment]
> 1. `astro preview` should open on next available port 4322.

When using an adapter, `astro preview` would route to their implementation, and it's not always possible to expect them to auto-increment the port if it's already occupied. So I don't think this behaviour should be expected by default.

> 2. `node dist/server/entry.mjs` should have error `EADDRINUSE: address already in use ::1:4321`.

I submitted a PR to fix that https://github.com/withastro/astro/pull/9545. Technically it's not a port conflict behaviour as both servers are served under ipv4 and ipv6 respectively, but it is indeed inconsistent so I updated it.

> 3. `astro preview` should have command line option `--port` and astro config file option to change port to try first.

`--port` seems to work for me when I use it.

> 4. node adapter should have host and port options that are used as default if environment variable not given. Not every build process can provide environment variables ([docs.astro.build/en/guides/integrations-guide/node/#runtime-environment-variables](https://docs.astro.build/en/guides/integrations-guide/node/#runtime-environment-variables)).

I don't think we need new options for those unless you can show an environment where you can't pass env vars today. But I believe most enviroments should allow that in some form. I've skipped this in the PR for now as I think it's also out-of-scope.

**Comment by cdtut** [comment]
> When using an adapter, astro preview would route to their implementation, and it's not always possible to expect them to auto-increment the port if it's already occupied. So I don't think this behaviour should be expected by default.

New option to auto increment is possible? It is for previewing in development without stopping the dev server.

> --port seems to work for me when I use it.

I did not know that can it be included to command help menu?

> I don't think we need new options for those unless you can show an environment where you can't pass env vars today. But I believe most enviroments should allow that in some form. I've skipped this in the PR for now as I think it's also out-of-scope.

Some companies environment don't let developers customize env vars. It's a limitation they add that makes difficulty.

`host` and `port` can already be passed in https://github.com/withastro/astro/blob/main/packages/integrations/node/src/index.ts#L47. Can you move `...userOptions` to the end so it can be override?

**Comment by bluwy** [comment]
> New option to auto increment is possible? It is for previewing in development without stopping the dev server.

As mentioned, the problem is that different preview implementations are not expected to auto-increment today. Even if we add a new option, it doesn't make auto-increment work. They still need to implement themselves.

> I did not know that can it be included to command help menu?

We can definitely add them. Looks like it's missed out in the list.

**Comment by cdtut** [comment]
@ematipico host and port can already be passed in https://github.com/withastro/astro/blob/main/packages/integrations/node/src/index.ts#L47. Can you move ...userOptions to the end so it can be override?
