### ISSUE TITLE
Cannot use Tailwind with LightningCSS

### ISSUE THREAD

**Issue by azat-io** [withastro/astro#9134]
### Astro Info

```block
Astro                    v3.5.5
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

TailwindCSS styles are not applied if the project on the Astro uses LightningCSS.

### What's the expected result?

Everything is working correctly.

Please try using the demo:

1. Clone repo `git@github.com:azat-io/astro-tailwind-lightningcss-bug.git`
2. Install deps `pnpm install`
3. Start project `pnpm start` (There is a problem with styles 😢)
4. [Remove LightningCSS](https://github.com/azat-io/astro-tailwind-lightningcss-bug/blob/main/astro.config.ts#L5-L9) from Astro config (Everything works fine 🤷‍♂️)

### Link to Minimal Reproducible Example

https://github.com/azat-io/astro-tailwind-lightningcss-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Tailwind requires postcss to work. There's nothing we can do if postcss is removed for lightningcss instead.
