### ISSUE TITLE
Images in RSS give [object Object] 

### ISSUE THREAD

**Issue by teinett** [withastro/astro#9136]
### Astro Info

```block
Astro                    v3.5.5
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

any

### Describe the Bug

I created blog with Content Collections.

I use Image and RSS from AstroJS.

There is page http://localhost:4321/rss.xml and I see `https://untitled.urbansheep.com[object Object]` instead of image url.

<img width="1039" alt="Screenshot 2023-11-19 at 19 02 38" src="https://github.com/withastro/astro/assets/1038168/a7d15061-abc6-40c6-b8e9-434ce9ceb163">

Used code: `src/pages/rss.xml.ts`

```
return rss({
        stylesheet: "/rss/styles.xsl",
        xmlns: { h: "http://www.w3.org/TR/html4/" },
        title: SITE.title,
        description: SITE.description,
        site: context.site?.toString() || SITE.url,
        customData: "<language>ru</language>",
        items: posts.map((post) => ({
            title: post.data.title || `Пост ${post.data.id}`,
            pubDate: post.data.date,
            description: post.data.photo
                ? `${SITE.url}${post.data.photo} ${post.body}`
                : post.body,
            link: `/post/${post.data.id}`,
            guid: post.data.id,
            customData: `
                <h:img src="${SITE.url}${post.data.photo}" />
                <enclosure url="${SITE.url}${post.data.photo}" />
            `,
        })),
    });
```

### What's the expected result?

I extected to see generated URL of image after all transformations.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wnucdn?file=src%2Fpages%2Frss.xml.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
In Astro, image imports return an object with numerous properties about the image (its dimensions, format, orientation etc) in addition to its path. The image() schema that you're using also results in that same import shape.

As such, you'll need to do `post.data.photo.src` to get the file path. You can see the type here: https://docs.astro.build/en/guides/images/#local-images-in-src
