### ISSUE TITLE
Dynamic pages makes vercel serverless function crashes when deploying.

### ISSUE THREAD

**Issue by steve-ref** [withastro/astro#9153]
### Astro Info

```block
Astro                    v3.5.5
Node                     v18.14.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

When building a headless cms ( wordpress ) + Astro SSR project using vercel adapter, there is a bug and the vercel serverless function crashes.

So dynamic pages are not working ( FYI works fine with netlify ).

### What's the expected result?

When deploying the project on vercel, pages should be dynamically loaded by [slug].astro. But it's not working and vercel is displaying an error screen

### Link to Minimal Reproducible Example

https://github.com/steve-ref/dinos

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
It works fine. https://preview-fwl8m4sxs-lilnasy.vercel.app/dinos/anthracosaurus/

It is possible that the existence of the `.vercel` folder is confusing vercel CD somehow. Can you check if removing it from your repo changes anything?

**Comment by florian-lefebvre** [comment]
We tried to debug this with other contributors (eg @dreyfus92) and couldn't find a way to make it work, I'll try to link the discord thread later

**Comment by dreyfus92** [comment]
This is the discord [thread](https://discord.com/channels/830184174198718474/1176077459842670652) 🫡

**Comment by steve-ref** [comment]
> It works fine. https://preview-lilnasy.vercel.app/?_vercel_share=bgOYQx76PGryUryKP1Z6QYyzVxqzp9IR
> 
> It is possible that the existence of the `.vercel` folder is confusing vercel CD somehow. Can you check if removing it from your repo changes anything?

I don't need .vercel just to build and deploy on vercel?

**Comment by lilnasy** [comment]
> I don't need .vercel just to build and deploy on vercel?

That is correct. It is generated automatically on every build.

**Comment by steve-ref** [comment]
> > I don't need .vercel just to build and deploy on vercel?
> 
> That is correct. It is generated automatically on every build.

Yeah ok. The .vercel folder on github is the generated folder after the build.
But if I remove the folder, Vercel will not understand the import from git right ?

**Comment by lilnasy** [comment]
@steve-ref Did that help?

**Comment by steve-ref** [comment]
> @steve-ref Did that help?

Working fine with Dinos example; but not with my personal project :/
But i switched to Netlify and no problem since the switch.

**Comment by lilnasy** [comment]
Closing until there are reproduction steps.
