### ISSUE TITLE
Works in Dev, but styles break in Prod build

### ISSUE THREAD

**Issue by NagariaHussain** [withastro/astro#9156]
### What version of `starlight` are you using?

0.13.0

### What version of `astro` are you using?

3.5.6

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Arc

### Describe the Bug

Properly works in dev:

<img width="1721" alt="CleanShot 2023-11-21 at 22 55 47@2x" src="https://github.com/withastro/starlight/assets/34810212/656f7cae-fbcd-486a-8f4d-f4fa21151cb3">

But (styles) breaks in final build (even in yarn build/preview):

<img width="1657" alt="CleanShot 2023-11-21 at 22 56 05@2x" src="https://github.com/withastro/starlight/assets/34810212/d83a4d38-2695-417a-a2d7-8adcb714dc60">

No error in browser console.

### Link to Minimal Reproducible Example

https://tmfm.buildwithhussain.dev/ (https://github.com/NagariaHussain/the-missing-frappe-manual)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Liliandev** [comment]
Broken when prerendering is enabled, works well without prerendering
