### ISSUE TITLE
Svelte errors are not forwarded to user

### ISSUE THREAD

**Issue by Its-Just-Nans** [withastro/astro#9158]
### Astro Info

```block
All astro versions
```

### Describe the Bug

Hello,

Here is the reproduction https://stackblitz.com/edit/github-asymdn

The example show that with a svelte component using `client:only`, if there are errors (even an "obvious" one like `ee is not defined`, we don't have clear instructions.

We just have

```txt
[HMR][Svelte] Unrecoverable HMR error in <Test>: next update will trigger a full reload
```

Or sometimes (in a personal project for example) :
- the page crash
- the error is displayed
- but if I reload the page, it crashes again but with `[HMR][Svelte] Unrecoverable HMR error in <Test>: next update will trigger a full reload` with **only** error

But with client:visible we have a Error Boundary

### What's the expected result?

Have a Error boundary each time OR at least have the error in the console

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-asymdn

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Its-Just-Nans** [comment]
Note that I though it would be svelte-hmr but it's not

https://github.com/sveltejs/svelte-hmr/pull/86

**Comment by lilnasy** [comment]
I see a helpful error from your reproduction.

<img width="914" alt="image" src="https://github.com/withastro/astro/assets/69170106/ad4a60c2-125e-43ac-8c69-dbafb6ce64d2">

**Comment by lilnasy** [comment]
I notice that the error is being eaten up here:
https://github.com/withastro/astro/blob/4d1274c47987bf3c247f0ad02309f3c2b9968d6e/packages/integrations/svelte/client.js#L29-L30
