### ISSUE TITLE
styled-components styles are not always applied when using SSR & build fails when using SSR (React)

### ISSUE THREAD

**Issue by rbrishabh** [withastro/astro#9162]
### Astro Info

```block
Astro                    v3.5.7
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  none
Integrations             @astrojs/react

(see stackblitz link)
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

When using the React integration with Styled-Components, and loading a component with "client:load" option:

```
<ReactComponent client:load />
```
ReactComponent:
```
import styled from 'styled-components';

const Hello = styled.div`
background: green;
`;

const HelloHeadline = styled.h3`
  color: yellow;
`;

const ReactComponent = () => {
  return (
    <Hello>
      <HelloHeadline>Only works with client:only</HelloHeadline>

      <HelloHeadline>Does not work wit client Load</HelloHeadline>
    </Hello>
  );
};

export default ReactComponent;
```
<img width="1704" alt="image" src="https://github.com/withastro/astro/assets/22501334/04b75314-a396-407e-b2f1-d0c39ae67bc4">

The styles are not applied when styling a div "styled.div", but they are applied if I change styled.div to "styled.h6"

<img width="1704" alt="image" src="https://github.com/withastro/astro/assets/22501334/9c32ceb4-431d-48f8-bdb6-db23908cf219">

The styles always work correctly with "client:only"

### What's the expected result?

I expect that the styles should work for SSR for "styled.div" component too.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-8mqv8d?file=adorable-astronaut%2Fsrc%2Fcomponents%2FReactComponent.tsx

Also, the build doesn't work with using styled components with SSR. The build succeeds but when doing a yarn preview, the error is: TypeError: styled.div is not a function

<img width="1187" alt="image" src="https://github.com/withastro/astro/assets/22501334/1f308d4d-edae-4a07-8565-8735f1598b03">

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rbrishabh** [comment]
Similar bug reported here: https://github.com/withastro/astro/issues/2196#issuecomment-1243270895

**Comment by lilnasy** [comment]
Most CSS-in-JS solutions rely on creating stylesheets at render-time, which is incompatible with streaming. Tailwind works by creating all stylesheets at build-time.
- https://github.com/withastro/roadmap/discussions/778
