### ISSUE TITLE
Unable to render custom page types since Astro 3.0

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#9163]
### Astro Info

```block
Astro                    v3.6.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             integration
```

### Describe the Bug

Since 3.0 my asciidoc extension is [unable to render](https://github.com/shishkin/astro-asciidoc/issues/21) pages written in AsciiDoc. The error is that Astro is missing a renderer:

```
 error   Unable to render `Content`.

  No valid renderer was found for this file extension.
```

I don't know how to tell Astro which renderer to use. I tried to adapt some examples from Markdown and Mdx Astro code, but without any progress.

### What's the expected result?

I expect Astro to render custom `.adoc` page with necessary extensions.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-avtnzh?file=src%2Fintegration.ts
~https://github.com/shishkin/astro-asciidoc/tree/renovate/major-astro~

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
That integration is incredible!

The hooks you are using are internal so they won't be as well-documented but you are probably missing that `addContentEntryType` has to called as well. https://github.com/withastro/astro/blob/4d1274c47987bf3c247f0ad02309f3c2b9968d6e/packages/integrations/mdx/src/index.ts#L54-L72

**Comment by shishkin** [comment]
Thanks @lilnasy. I've tried to condense the integration [here](https://stackblitz.com/edit/github-avtnzh?file=src%2Fintegration.ts) and added a call to `addContentEntryType` as you suggested. Still the same error `NoMatchingRenderer: Unable to render Content.`
