### ISSUE TITLE
[@astro/rss] Error thrown when missing required property is unclear.

### ISSUE THREAD

**Issue by cdvillard** [withastro/astro#9171]
### Astro Info

```block
Astro                    v3.6.0
Node                     v20.9.0
System                   Linux (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/preact
                         @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Updating my RSS feed using `@astro/rss`, I kept receiving the following error when editing the `items` property.

![image](https://github.com/withastro/astro/assets/6250214/b3343531-6360-4786-80fa-0b4c9dba7764)

This error provided no obvious solution to what the problem was. It wasn't until I added a `link` property that it began working.

### What's the expected result?

I expected the error to be a little more clear about what might be missing. I do see the documentation makes note of this, but in the event of a quick fix, it wasn't made apparent that I was missing a critical parameter. I think there would be a benefit to making it clear what property is missing if possible.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vazm4h

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Thanks for the reproduction!

Looks like the zod runtime errors aren't as helpful as rss' typescript errors.
<img width="433" alt="image" src="https://github.com/withastro/astro/assets/69170106/014d8cc3-3235-4be0-ba2c-0ecbf68177de">

The logic for creating an error from zod's validation failure is here:
https://github.com/withastro/astro/blob/cfa0c454b5ac6732c538399ea944022fb031d460/packages/astro-rss/src/index.ts#L104-L118

**Comment by lilnasy** [comment]
## Good first issue!
This is an opportunity for astro users to learn about how astro works by fixing a small but real bug. You can expect to get help setting up the dev environment, and understanding the project structure in this channel. **If you have already been contributing for a while, consider guiding an enthusiastic newcomer.**

### What's the bug?
The main function `@astrojs/rss` throws an unhelpful error when things go wrong. cdvillard has provided a very clear minimal here linked in the issue description.

### What's going wrong here?
The `@astro/rss` library performs validation on the input using zod. If the validation fails, the details are gathered to create and throw an error. However, the error (which should still be thrown) has very little helpful information.

### Where do I start looking?
The part where `@astrojs/rss` converts the validation failure to the unhelpful error is here:  [withastro/astro/packages/astro-rss/src/index.ts](https://github.com/withastro/astro/blob/cfa0c454b5ac6732c538399ea944022fb031d460/packages/astro-rss/src/index.ts#L104-L118).

**Comment by cdvillard** [comment]
Took the lead on that suggestion and created a PR against `main` (#9299). Will likely miss tomorrow's release, but thought it'd be fun to do it regardless!

**Comment by florian-lefebvre** [comment]
I think this issue is resolved then! Feel free to reopen if I missed something
