### ISSUE TITLE
Astro.redirect doesn't work in a layout

### ISSUE THREAD

**Issue by EskelCz** [withastro/astro#9188]
### Astro Info

```block
Astro                    v3.5.3
Node                     v20.7.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/svelte
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

When trying to redirect in a front-matter of layout it always throw `The response has already been sent to the browser and cannot be altered.`

I was trying to run a certain logic in all pages and redirect based on the output. Seems like the layout is not the place for that, but I don't know what alternatives I have. I'm missing something like an app.astro or index.astro entry point.

Btw thanks for Astro, it's great :)

### What's the expected result?

Redirect, or have another place which can run logic for all pages, without cluttering their code.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mwg25p?file=src%2Flayouts%2FLayout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by EskelCz** [comment]
If it's by design, it should probably be mentioned in the documentation.

**Comment by lilnasy** [comment]
It is by design and mentioned in the docs here. We could make it more prominent, however. Open to suggestions :)
https://docs.astro.build/en/guides/server-side-rendering/#html-streaming

**Comment by EskelCz** [comment]
@lilnasy I see. Sorry I missed that, I was searching for the redirect keyword, so my suggestion would be to put a note/warning here: [https://docs.astro.build/en/core-concepts/routing/#dynamic-redirects](https://docs.astro.build/en/core-concepts/routing/#dynamic-redirects)

However now I feel kind of stuck, because I can't figure out how to reuse data between pages on the server side. I thought I'm going to do it in the layout. I'm missing some kind of glue above all pages.

**Comment by bngmnn** [comment]
@EskelCz May I know how you end up doing this? Since I'm facing the same issue right now

**Comment by EskelCz** [comment]
@bngmnn I found out middleware, which solved most of my problems. You can pass data through `locals` into all pages and also redirect without any issues.

**Comment by bngmnn** [comment]
@EskelCz wow, nice! Helped me a lot, thank you
