### ISSUE TITLE
`prettier-plugin-astro` ignorting HTML plugins

### ISSUE THREAD

**Issue by junaga** [withastro/astro#9191]
### Astro Info

```block
Astro                    v3.6.0
Node                     v18.17.1
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

When formatting `.astro` with [npm:@awmottaz/prettier-plugin-void-html](https://github.com/awmottaz/prettier-plugin-void-html) set in `plugins`, to fix [self closing tags](https://jakearchibald.com/2023/against-self-closing-tags-in-html/), it's ignored.

### in

```html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width">
<meta name="color-scheme" content="light dark">
```

### out

```html
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width" />
<meta name="color-scheme" content="light dark" />
```

### in

```html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width">
<meta name="color-scheme" content="light dark">
```

### out

```html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width">
<meta name="color-scheme" content="light dark">
```

### Link to Minimal Reproducible Example

https://example.com

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is unfortunately not possible to support on our end. Prettier plugins have pretty strict restrictions regarding how they can interact with other plugins.

The plugin in question needs to explicitly extend our plugin, much like the Tailwind plugin does, instead of just the HTML one.

**Comment by junaga** [comment]
Wow, this is no-go. I have the Astro VS Code extension installed. @Princesseuh self-closing tags are an abomination.

HTML is not JSX. HTML is not XHTML. HTML is HTML. Astro is an HTML-first framework if i understand correctly. This needs to be fixed.

**Comment by junaga** [comment]
For now I am just formatting my `dist/`. I like to pretend googlebot and others are senior devs that code review.

**Comment by Princesseuh** [comment]
Feel free to make a PR to the Prettier plugin you linked to add support for Astro. I'm just saying we can't do anything on our side to support said plugin.

We generally just match Prettier's formatting result (as is usually done in Prettier plugins for extra languages embedding other languages, ex: Svelte), so any complaints regarding that behavior should be brought up to them.

**Comment by junaga** [comment]
I did my upvotes for this across the prettier repo.

About contributing: I am banned from the Astro Discord (forum) for no reason. so no, thank you very much.
