### ISSUE TITLE
Importing Modules into a Web Components with Custom Element blocks the event actions

### ISSUE THREAD

**Issue by jolo-dev** [withastro/astro#9194]
### Astro Info

```block
Astro                    v3.2.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  none
Integrations             none
```

### Describe the Bug

I have created a [Web Component with Custom Element](https://docs.astro.build/en/guides/client-side-scripts/#web-components-with-custom-elements).
Now, I want to load a local Typescript file. 
However, it seems that the module cannot be imported.
I imported the local file as described here: https://docs.astro.build/en/guides/client-side-scripts/#import-local-scripts

### What's the expected result?

I can use the function that I outsourced into a Typescript file.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-w3xtbh?file=src%2Fcomponents%2FButton.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @jolo-dev, please try again after removing `type="module"` from the script tag. 
For an explanation, see the [first note in the `<script>` section](https://docs.astro.build/en/guides/client-side-scripts/#opting-out-of-processing) and [the description of `is:inline`]( https://docs.astro.build/en/reference/directives-reference/#isinline)

**Comment by jolo-dev** [comment]
Hey @martrapp ,
Oh yeah it seems to work.
It does not work on my project. I will do another Stackblitz later.
I guess it has something to do with SSR.

**Comment by martrapp** [comment]
You may be able to get faster and more direct help in the #Support channel at https://discord.gg/astrodotbuild.

**Comment by jolo-dev** [comment]
I know. I tried. It didn't work
https://discord.com/channels/830184174198718474/1176166136367284305/1176166136367284305

**Comment by martrapp** [comment]
> Oh yeah it seems to work.
Yes.
