### ISSUE TITLE
Theme Toggle doesn't work after the route is changed when use ViewTransititons

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/astro#9198]
### Astro Info

```block
Astro                    v3.6.0
Node                     v20.10.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

MS Edge

### Describe the Bug

First, I think this is a bug in ViewTransition. Step by step:

1. Go to https://astro-shadcn-ui-template.vercel.app
2. Direct to https://astro-shadcn-ui-template.vercel.app/404
3. Click "Go back home"
4. Click the `Theme Toggle` icon and it doesn't work.

This is [my repo](https://github.com/AREA44/astro-shadcn-ui-template). I added ViewTransition in [HeadSEO.astro](https://github.com/AREA44/astro-shadcn-ui-template/blob/main/src/components/HeadSEO.astro). Everything is fine if I remove ViewTransition. 

### What's the expected result?

The `Theme Toggle` still works.

### Link to Minimal Reproducible Example

https://github.com/AREA44/astro-shadcn-ui-template

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You need to handle the page changes manually, see https://docs.astro.build/en/guides/view-transitions/#script-behavior-during-page-navigation for more information
