### ISSUE TITLE
HTML in MDX validation wrong for nested lists

### ISSUE THREAD

**Issue by stephanbogner** [withastro/astro#9201]
### Astro Info

```block
Astro                    v3.6.1
Node                     v18.18.2
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
```

#### ❌ Does not work (notice the `<ol>` in the same line as the link)
```
---
title: "Lorem ipsum"
---
<ol>
    <li>
        <a href="#">1.</a>
    </li>
    <li>
        <a href="#">2.</a><ol>
            <li><a href="#">2.1</a></li>
        </ol>
    </li>
</ol>
```

Throws error `Expected a closing tag for </li> (6:27-6:31) before the end of paragraph`

#### ✅ Does work (`<ol>` in new line)
```
---
title: "Lorem ipsum"
---
<ol>
    <li>
        <a href="#">1.</a>
    </li>
    <li>
        <a href="#">2.</a>
        <ol>
            <li><a href="#">2.1</a></li>
        </ol>
    </li>
</ol>
```

### What's the expected result?

Line breaks should not affect the validity check.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2m2wzj?file=src%2Fcontent%2Fblog%2Ffirst-post.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Seems like an intentional design from MDX: https://github.com/mdx-js/mdx/issues/2212. There's also a few related issues if you search at https://github.com/search?q=repo%3Amdx-js%2Fmdx+expected+a+closing+tag&type=issues. Since this is out of our control, I'll close this.
