### ISSUE TITLE
Duplicate `data-astro-transition-scope` values with page partials

### ISSUE THREAD

**Issue by jtag05** [withastro/astro#9203]
### Astro Info

```block
Astro                    v3.6.0
Node                     v20.10.0
System                   Linux (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
```

### Describe the Bug

I have been trying out astro + htmx for the last few days and ran into an issue where subsequent elements of a paginated list, populated via a page partial have the same `data-astro-transition-scope` value as the existing items in the list. This breaks view transitions by throwing an `Unexpected duplicate view-transition-name` error. [Here is a minimal repro](https://stackblitz.com/edit/github-lhxfa8?file=src%2Fpages%2Fpartial.astro). 

Repro Steps:
- Click any link prior to clicking the `Load More` button
- Observe View Transition applying successfully
- Click back button to return to index page.
- Click `Load More` button
- Observe that View Transition is not applied on navigation
- Observe `Unexpected duplicate view-transition-name` error in console

### What's the expected result?

View Transitions continue to function after additional elements are loaded.

It seems that the `data-astro-transition-scope` id is being incremented per page load. Based on the fact that the naming is consistent across page loads and rebuilds, my assumption is that the unique string is some hash of the component name, but the iterator seems to cause duplicates between page loads.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lhxfa8?file=src%2Fpages%2F%5Bid%5D.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @jtag05, I'm afraid you are trying to achieve something that partials are not intended for. The [documentation](https://docs.astro.build/en/core-concepts/astro-pages/#page-partials) says, partial should not be used if they contain scoped styles and technically, the transition-scope is not different from a scoped style.  `/partial` uses transition-scopes, but it doesn't define them. Maybe that is more obvious when you replace the `<ComponentList>` in `index.astro` with the `<button>` from the component as in https://stackblitz.com/edit/github-lhxfa8-ooanoz?file=src%2Fpages%2Findex.astro.

**Comment by martrapp** [comment]
What would work in your example is not to have static scopes in the partial, but to create the names of the transitions dynamically as well. Delete the scoped CSS ``transition:name={`test-${id}``` and change the style attribute to ``style={`display:block; view-transition-name: test-${id.toString().replace('.', '_')}```. (Replacement of '.' with '_' matches the name sanitization of `transition:name`)

**Comment by jtag05** [comment]
Ok I see the issue. Thank you! that does work.

Let me recap:
The root issue is that the `astro:transition-name` directive generates a scoped style which is not supported by partials. 
This symptom I encountered is being surfaced due to  the naming code [here](https://github.com/withastro/astro/blob/d90714fc3dd7c3eab0a6b29319b0b666bb04b678/packages/astro/src/runtime/server/transition.ts#L21-L24) creating a duplicate reference to the same `view-transition-name` because the `data-astro-transition-scope` is duplicated on the subsequent load. 
By manually overriding the `view-transition-name` in the `style` attribute, we're able to circumvent the scoped style of the partial being ripped out and the duplicate reference from happening. 

Hacky solution, but it works. Is there anything on the roadmap to potentially support at least scoped styles inside partials that could make this work for view transitions out of the box? 
It seems like using the  `is:inline` directive on a `style` does generate it within the partial. Maybe identifying if a page is a partial and appending that during the view transition logic could work?

**Comment by jtag05** [comment]
Closing for now as my issue is resolved, but I'd enjoy continuing to work towards a more dev-x friendly solution :)

**Comment by RogierdeRuijter** [comment]
For anyone else who finds this issue. What worked for me, was removing the `export const partial = true` and using https://htmx.org/extensions/head-support/. This appends any stylesheet and script tag to the head. This way you can declare styles and components in the html file that you request with htmx. Following the guide in the link and adding the scripts in the following manner to an astro page worked for me.

```
<head>
  <script is:inline src="https://unpkg.com/htmx.org@1.9.9"></script>
  <script src="https://unpkg.com/htmx.org/dist/ext/head-support.js"></script>
</head>
```

`is:inline` is needed so vite doesn't process the htmx script and htmx is attached to the window so that head-support.js can find it.
