### ISSUE TITLE
getEntry returns undefined for newly created entry

### ISSUE THREAD

**Issue by reggi** [withastro/astro#9204]
### Astro Info

```block
Astro                    v3.6.1
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

chrome

### Describe the Bug

On the first run of this code both `check` and `checkAgain` are undefined.

On the second run of this code i'd expect both to be defined.

```astro
---
import { getEntry } from "astro:content";
import fs from 'node:fs/promises';
const check = await getEntry('blog', 'meow')
console.log({ check }) // undefined on first visit
const frontMatter = `
title: 'meow post'
description: 'meow'
pubDate: 'Jul 08 2022'
heroImage: '/blog-placeholder-3.jpg'
`
await fs.writeFile('./src/content/blog/meow.md', [`---`, frontMatter, `---`, 'meow'].join('\n'))
const checkAgain = await getEntry('blog', 'meow')
console.log({ checkAgain })
---
{checkAgain && checkAgain.body}
```

### What's the expected result?

On the first run of this code I'd expect check to be `undefined` and checkAgain to be defined. 

On the second run of this code i'd expect both to be defined.

Locally I see this on first run:

```
{ check: undefined }
{ checkAgain: undefined }
12:26:03 AM [astro] update /src/content/blog/meow.md
12:26:03 AM [astro] update /.astro/types.d.ts
```

On stackblitz i'm not seeing checkAgain fire undefined. 

Could this all be because of watching `content` and hot-reloading? Is there a safer way to do content-writes?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wasafp?file=src%2Fpages%2Fabout.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by reggi** [comment]
the main issue is that you this is unexpected: for the first run, all of these logs return undefined.

---
import { getEntry } from "astro:content";
import fs from 'node:fs/promises';

export async function example () {
  const check = await getEntry('blog', 'meow')
  console.log({ check }) // undefined on first visit

  const frontMatter = `
  title: 'meow post'
  description: 'meow'
  pubDate: 'Jul 08 2022'
  heroImage: '/blog-placeholder-3.jpg'
  `

  await fs.writeFile('./src/content/blog/meow.md', [`---`, frontMatter, `---`, 'meow'].join('\n'))

  const checkAgain = await getEntry('blog', 'meow')
  console.log({ checkAgain })
}

await example()
await example()
await example()
await example()
await example()

---

hi

**Comment by florian-lefebvre** [comment]
I think this is because CC rely on codegen si between writeFile and getEntry, Astro has no way to know an entry was added. But let's wait for a core member confirmation

**Comment by bluwy** [comment]
Yeah I don't think this is something we can fix. After you call `writeFile`, Astro's file watcher will be signalled to re-build the content collection entries. During that time, it isn't ready yet so if you call `getEntry` again, you would still get the previous value.

I'd suggest refactoring your code to work differently. Maybe the manual `writeFile` could be a custom script that's called externally.
