### ISSUE TITLE
Astro 4.0 beta Project Setup Instructions install Astro 3.6.1

### ISSUE THREAD

**Issue by Lms24** [withastro/astro#9205]
### Astro Info

```block
Astro                    v3.6.1
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

I wanted to create a new Astro 4.0.0-beta.0 project and followed the instructions from the [blog post](https://astro.build/blog/astro-4-beta/):

```sh
npm init astro@beta
```

However, the setup flow installed `astro@^3.6.1`. 
The same issue seems to happen with `npm create astro@beta` by the way.

### What's the expected result?

`astro@4.0.0-beta.0` (along with matching dependencies) is installed

### Link to Minimal Reproducible Example

State of the newly created project after running the setup wizard:

https://github.com/Lms24/astro-4.0.0-beta.o-installs-3.6.1-bug-repo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Lms24** [comment]
It's not a big deal obviously, as running `npm install astro@beta` afterwards upgrades to 4.0 but I thought I'd let you know anyway.

**Comment by bluwy** [comment]
Looks like you can workaround this with `npm init astro@beta --ref beta`. The issue is that the templates are still pulling from the `latest` branch here, which is synced from the `main` branch (v3), but not the `next` branch (v4).

Thanks for flagging this, I'll check with the others to see how we usually handle this in the past.
