### ISSUE TITLE
Bug when trying to convert string to URL in export function

### ISSUE THREAD

**Issue by jamesli2021** [withastro/astro#9208]
### Astro Info

Similar issue with export function that should have been caught.

In .ts file, I passed Astro.url.href to u parameter.

```
export function hellp(u: string = '') {
    let newurl = new URL(u);
}
```

### Describe the Bug

I get type error

```
TypeError [ERR_INVALID_URL]: Invalid URL
```

if I use the code below, it can convert:

```
new URL('https://localhost');
```

### What's the expected result?

Abolbe to correctly resolve the URL.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Could you share an example from `[astro.new](https://astro.new/minimal?on=stackblitz)` to explain what you mean?
