### ISSUE TITLE
 When migrating from 2.x to 3.x, `export * from` is invalid in mdx

### ISSUE THREAD

**Issue by nanarino** [withastro/astro#9253]
### Astro Info

No error is reported in the terminal
All dependencies are up to date

```block
"@astrojs/mdx": "^1.1.5",
"astro": "^3.6.4",
Node 18.16.0
pnpm 8.6.0
win11 Edge 119.0.2151.72
```

### If this issue only occurs in one browser, which browser is a problem?

all

### Describe the Bug

I introduced [this file](https://github.com/nanarino/nanarinostyl/blob/main/src/components/markdown/index.mdx) in every mdx file. It works fine in 2.x

### What's the expected result?

I hope it works fine in the new version too

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1uj5sn?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nanarino** [comment]
sorry I may be mistaken. I casually upgraded the version of @astrojs/mdx during the migration
🤔😂 After upgrading astro version its version no longer matches 
`"@astrojs/mdx": "^0.19.7"` -> "@astrojs/mdx": "^1.1.5"

**Comment by lilnasy** [comment]
I am not sure how it worked before 1.0, but currently it expects to be able to see that there is a variable called components in the file. For example, this works.
<img width="367" alt="image" src="https://github.com/withastro/astro/assets/69170106/87ac48e8-83f2-48b2-ab4c-7c3b6f1f0d3b">

**Comment by nanarino** [comment]
> I am not sure how it worked before 1.0, but currently it expects to be able to see that there is a variable called components in the file. For example, this works. <img alt="image" width="367" src="https://private-user-images.githubusercontent.com/69170106/287055365-87ac48e8-83f2-48b2-ab4c-7c3b6f1f0d3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTc5MzgsIm5iZiI6MTcwMTUxNzYzOCwicGF0aCI6Ii82OTE3MDEwNi8yODcwNTUzNjUtODdhYzQ4ZTgtODNmMi00OGIyLWFiNGMtN2MzYjZmMWYwZDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDExNDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNTdhNTA1MTFkOGY0N2ZmNzdkY2ZiMTE5NDg4MDcxMGM5NDA4ZjU5N2FmODZlODE3NDFlMzk2ODcyZTA2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Q1ommQee4LBVPreDDm8QpSo-Mevm2QPxIYU5gnh-dw">

```js
// @astrojs/mdx/dist/index.js
export const Content = (props = {}) => MDXContent({...props,components: { Fragment, ...props.components },});
export default Content;
```
The component is in the `props.components` when 0.x 
and no longer there after upgrading to >1.0
 now it only supports explicit export
