### ISSUE TITLE
import.meta.glob with path aliases won't work

### ISSUE THREAD

**Issue by cdtut** [withastro/astro#9258]
### Astro Info

```block
Astro                    v3.6.0
```

### Describe the Bug

https://github.com/withastro/astro/issues/3835 was fixed for Astro.glob but not for import.meta.glob. Error is `Error: Invalid glob: "@dir/*.png" (resolved: "@dir/*.png"). It must start with '/' or './'`

### What's the expected result?

Should not throw error and the output of import.meta.glob should be object like this

```
'@dir/1.png': [Function: /src/resolved/dir/1.png],
'@dir/2.png': [Function: /src/resolved/dir/2.png],
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/flamboyant-parm-hmhud7

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
In your repro, the Astro version specified is `astro@^1.0.0-beta.63` which in the lockfile resolved to v1.9.2. Is this correct? This glob issue is related to Vite and I remember it being fixed, but v1.9.2 might not include the Vite version that fixed it.

**Comment by cdtut** [comment]
I tried with latest and working with Astro.glob but import.meta.glob still not.

**Comment by lilnasy** [comment]
Tried with Astro 3 and 4.0.0-beta.4, neither resolve aliases.

**Comment by bluwy** [comment]
Ah I think I know why. It only works with Vite's `resolve.alias`. We implement the aliasing ourselves with `resolveId`, but when we get `@/something/*.css`, we resolve it as `/Users/.../project/something/*.css`, and then we check if this is valid here:

https://github.com/withastro/astro/blob/feaba2c7fc0a48d3af7dd98e6b750ec1e8274e33/packages/astro/src/vite-plugin-config-alias/index.ts#L85-L89

But of course a file like that doesn't exist, so it fails and the alias didn't work.

One way (I think) we could fix it is by not checking the existence when Vite is resolving for globs (e.g. check if string contains `*` or this [Vite-provided hint](https://github.com/vitejs/vite/blob/fa7976732e815a7f4268369596f6df872201d0e9/packages/vite/src/node/plugins/importMetaGlob.ts#L546)), and in which case we just return the resolved value directly.

**Comment by cdtut** [comment]
@bluwy it should create  `'@dir/1.png': [Function: /src/resolved/dir/1.png],` so that we can reference it but it creates `'/src/resolved/dir/1.png': [Function: /src/resolved/dir/1.png],`.
