### ISSUE TITLE
Astro.slots.has() wrongly returns true

### ISSUE THREAD

**Issue by silveltman** [withastro/astro#9278]
### Astro Info

```block
Astro                    v3.6.3
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
                         @astrojs/sitemap
                         astro-robots-txt
                         bookshop
                         unocss
```

### If this issue only occurs in one browser, which browser is a problem?

/

### Describe the Bug

Astro.slots.has('default') return true, even though the slot is empty.

my usecase:
```
<List {...list}>
      <Socials {socials} />
</List>
```

after running Astro.slots.render('default') I found out that it returns 2 empty spaces. When changing my component to the following it does work as expected:
```
<List {...list}> <Socials {socials} /></List>
```

### What's the expected result?

I expect Astro to not count it as a slot if it's just empty spaces. Otherwise we would need to write very uggly code, especially when having a more nested structure. This quickly looks like this:
```
<Section {...section}><Segment {...segment}><List {...list}><Socials {socials} /></List></Segment></Section>
```

Not only is it way too hard to read, prettier actually wont allow it with the astro plugin.

### Link to Minimal Reproducible Example

na

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Talked about this with some others on the core team and this is indeed expected behavior, `has()` just says that a slot was passed. Use `render()` to check on its value.
