### ISSUE TITLE
`astro preview` fails silently with missing `dist` folder

### ISSUE THREAD

**Issue by hirasso** [withastro/astro#9297]
### Astro Info

```block
Astro                    v3.6.4
Node                     v18.19.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-expressive-code
                         @astrojs/mdx
```

### Describe the Bug

Hi there! I'm really not sure if this is a problem with Astro, PlayWright's [`webServer`](https://playwright.dev/docs/test-webserver) or GitHub actions 😅 

I have a little [package](https://github.com/hirasso/scrollmirror) where I create the docs with Astro and also use the same docs to test my package through PlayWright ([see the config](https://github.com/hirasso/scrollmirror/blob/main/tests/e2e/config.playwright.ts)). This is what I tried first for PlayWright's `webServer.command` (contrived example, actually the commands are in npm scripts to make sure they are being run from the root of my package): 

```bash
astro preview --root docs
```

It was working nicely locally, but as soon as I put it in a GitHub action, playWright was hanging indefinitely.

### What's the expected result?

The PlayWright tests should be able to resolve the provided server (created by `astro preview`)

Turns out *first building* Astro before serving the preview fixed my issue in CI:

```bash
astro build --root docs && astro preview --root docs
```

Now I'm curious: What's the difference here? Doesn't `astro preview` *also* build the astro site?

There is a related thread [over at PlayWright](https://github.com/microsoft/playwright/issues/16834) and I'll happily close this issue if the astro maintainers think this is an issue with PlayWright. But then I'd still love to learn why combining `astro build` and `astro preview` isn't the same as `astro preview` alone.

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by hirasso** [comment]
Does a minimal reproducible example make sense here? I'd say my [package](https://github.com/hirasso/scrollmirror) is as minimal as it gets 😄. It contains an astro site, a playwright test suite and a github action to run the tests.

**Comment by lilnasy** [comment]
This seems like a general question, so a reproduction is not necessary. Although our discord server is where queries similar to yours would get a faster response: https://astro.build/chat.

To answer the question: no, `astro preview` does not run build, it simply runs a static file server for whatever it finds in the "dist" folder, which in this case was nothing. [Relevant docs](https://docs.astro.build/en/reference/cli-reference/#astro-preview).

**Comment by hirasso** [comment]
Oh my god. That's why it was working locally. The build folder was already there 🤪 Thanks for the quick reply!

**Comment by hirasso** [comment]
...revisiting the docs I must confess that it didn't make it fully clear to me that `astro preview` wouldn't build also. Maybe a little Hint box would be helpful here for others as well? I'll create a PR to the docs tomorrow. Thanks again for the help!

**Comment by lilnasy** [comment]
Awesome! Thanks for the help.

**Comment by hirasso** [comment]
I just tested running `astro preview` without first building. This is the output in the console (no warning about a missing `dist` folder!):

```bash
❯ npx astro preview --root docs
  🚀  astro  v3.6.4 started in 14ms
  
  ┃ Local    http://localhost:8274/
  ┃ Network  use --host to expose
```
...and in the browser I get a 404:

![CleanShot 2023-12-05 at 09 43 04@2x](https://github.com/withastro/astro/assets/869813/dd04ca8e-9c4b-487f-bc90-39b73c05a467)

@lilnasy I think some kind of warning in the console (or even in the browser?) would be helpful here? if you agree, should I create a feature request?

**Comment by lilnasy** [comment]
Yes, this is something new users frequently encounter. So if you contribute a warning, it will really help!

We are planning to show the list of all routes on the 404 page in the dev server, we will probably tackle the same for preview server as well. For now, a warning about dist being empty would be valuable.

**Comment by rishi-raj-jain** [comment]
> I just tested running `astro preview` without first building. This is the output in the console (no warning about a missing `dist` folder!):
> 
> ```shell
> ❯ npx astro preview --root docs
>   🚀  astro  v3.6.4 started in 14ms
>   
>   ┃ Local    http://localhost:8274/
>   ┃ Network  use --host to expose
> ```
> 
> ...and in the browser I get a 404:
> 
> ![CleanShot 2023-12-05 at 09 43 04@2x](https://private-user-images.githubusercontent.com/869813/287978773-dd04ca8e-9c4b-487f-bc90-39b73c05a467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTMyMTgsIm5iZiI6MTcwMTc5MjkxOCwicGF0aCI6Ii84Njk4MTMvMjg3OTc4NzczLWRkMDRjYThlLTljNGItNDg3Zi1iYzkwLTM5YjczYzA1YTQ2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNjE1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2E4MTBiZGY3YzhhM2NhY2U3OTM1OTgyZDRhYzk5MGFkNTMyYTM2NTc4ZDIzMDNmNTJmNjA2NmJlNDQxN2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4-BOVgABLgcYKssslj9uQGhSGJgYLcVgh91CLRUarEQ)
> 
> @lilnasy I think some kind of warning in the console (or even in the browser?) would be helpful here. If you agree, should I create a feature request?

Do we want to show a warning here or no preview message (like we do for adapters like Vercel), @lilnasy?

**Comment by bluwy** [comment]
I think a warning/message that bails like Vercel (because it doesn't support the preview command) works for me. So technically speaking, around this code:

https://github.com/withastro/astro/blob/270c6cc27f20995883fcdabbff9b56d7f041f9e4/packages/astro/src/core/preview/index.ts#L34-L45

We could also simply throw an error for consistency. I don't think there's a case where we still want to start the preview server.

**Comment by hirasso** [comment]
I'd also like it to fail with an error.
