### ISSUE TITLE
SolidJS hydration error when using resolved children

### ISSUE THREAD

**Issue by GiyoMoon** [withastro/astro#9323]
### Astro Info

```block
Astro                    v4.0.1
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
```

### Describe the Bug

SolidJS produces hydration errors when resolving children that aren't attached to the DOM.

Picture this:
```tsx
const Component = (props) => {
  const resolvedChildren = children(() => props.children)
  return <Show when={false}>{resolvedChildren()}</Show>
}
```

Here, the children resolve but aren't attached to the actual DOM.

### What's the expected result?

Solid shouldn't produce a hydration error in this case. I created the same setup on the Solid playground and it works, I think this is an issue with the solidjs adapter?
For reference: https://playground.solidjs.com/anonymous/3dad9c37-5022-4b33-9b9b-09c7bf7055e5

### Link to Minimal Reproducible Example

https://github.com/GiyoMoon/astro-solid-hydration-bug

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by ryansolid** [comment]
@matthewp very good chance this is on Solid's side. Looking at the issue this is likely a result of more aggressive erroring on hydration since Solid 1.8.

**Comment by GiyoMoon** [comment]
yes I just confirmed that this also happens without astro. I will close this issue and open one on the Solid repository.

**Comment by GiyoMoon** [comment]
For reference: https://github.com/solidjs/solid/issues/1977
