### ISSUE TITLE
data-astro-source-file added when devToolbar disabled

### ISSUE THREAD

**Issue by cdtut** [withastro/astro#9324]
### Astro Info

```block
Astro                    v4.0.1
```

### Describe the Bug

Disable devToolbar globally and run dev mode. `data-astro-source-file` and `data-astro-source-loc` still on every astro element. Makes reading source difficult to find what you are looking for in browser dev tool and inspecting plain html.

### What's the expected result?

Attributes shouldn't be added when devToolbar is disabled.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1o5lsw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
As a quick work-around, generation of source-file and source-loc can be switched off by setting
```
export default defineConfig({
  devToolbar: { enabled: false },

```
in astro.config.ts

**Comment by gonwms** [comment]
Is it possible to force the data attribute not to be removed? It could be very useful for locating files.

**Comment by martrapp** [comment]
> Is it possible to force the data attribute not to be removed? It could be very useful for locating files.

Hi @gonwms 👋🏼, what stops you from setting 
```
export default defineConfig({
  devToolbar: { enabled: true},
```
in astro.config?

**Comment by gonwms** [comment]
> > Is it possible to force the data attribute not to be removed? It could be very useful for locating files.
> 
> Hi [@gonwms](https://github.com/gonwms) 👋🏼, what stops you from setting
> 
> ```
> export default defineConfig({
>   devToolbar: { enabled: true},
> ```
> 
> in astro.config?

"Hi there! It seems that setting devToolbar: { enabled: true } doesn't preserve data attributes. From what I’ve observed, it strips them from the HTML to use them internally. At least, that’s what appears to be happening on my end."
