### ISSUE TITLE
Vue `appEntrypoint` not working

### ISSUE THREAD

**Issue by ffxsam** [withastro/astro#9330]
### Astro Info

```block
Astro                    v4.0.1
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  astro-sst
Integrations             @astrojs/vue
                         vuetify
```

### Describe the Bug

I'm not able to specify a Vue entry point like I could in Astro 2.x and 3.x, despite [following the docs](https://docs.astro.build/en/guides/integrations-guide/vue/#appentrypoint).

### What's the expected result?

I expected my app to load up properly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-y49v7g?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ffxsam** [comment]
I appreciate your prompt help with this—as always! 🙌

**Comment by ffxsam** [comment]
@szv I believe the bug lies in `@astrojs/vue`, not `astro`. And I haven't seen an update come through for that yet, so you'll have to pin `@astrojs/vue` at `4.0.0` for now.

**Comment by szv** [comment]
@ffxsam Thank you for your answer. But for me it doesn't work with 4.0.0 eighter 😅
I think I will have to wait for future versions.

**Comment by AngeloFornerino** [comment]
Hi @natemoo-re , has there been any progress on this issue? I continue to encounter the same problem. After updating `@astrojs/vue` to version 4.0.0, the build completes without issues. However, as soon as I open the webpage, the error returns.

Error message:
`ReferenceError: Cannot access '_export_sfc' before initialization`

**Comment by AngeloFornerino** [comment]
I was able to eliminate the error, which was related to the import from "astro/zod". By switching them back to "astro:content", the error disappeared. This is peculiar because there's a warning in the console that says:

"`astro:content` is only supported when running server-side. Using it in the browser will result in bloated bundles and slower page loading times. It will not be supported in the future."
