### ISSUE TITLE
SSG console prints _after_ page generation, preventing from debugging

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#9335]
### Astro Info

```block
Astro                    v3.6.0
Node                     v18.14.2
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astro-aws/adapter
Integrations             @y_nk/cached-fetch
                         @astrojs/tailwind
                         @astrojs/react
                         astro-robots-txt
                         @astrojs/sitemap
```

### Describe the Bug

When generating static content, we have a nice print out in the console with url generated such as:

```
  ├─ /ja/__test/index.html (+309ms)
  ├─ /ja/legal/index.html (+1.26s)
  ├─ /de/people-management/index.html (+490ms)
  ├─ /taskcards/index.html (+585ms)
  ├─ /fr/taskcards/index.html (+576ms)
  ├─ /de/stickyad/index.html (+563ms)
```

...but these lines happen **after** the pages being **successfully** generated. If an error occur there's no way to know which page crashed the build, since the log is only printed _after_ the page built, not before.

### What's the expected result?

In my wildest dreams, I'd love to see the console printings such as:

1. at build start (before the `generatePath` call), url of the page only`  ├─ /de/stickyad/index.html` 
2. at build end (after the `generatePath` call), line amended with the build time of the path such as `  ├─ /de/stickyad/index.html (+563ms)`

Optionally, for long builds it would be nice to have absolute time and completion % (based on pre computed page number) with the atomic build path duration. It is useful to know the build duration to spot slow pages, but it's also nice to have an idea of where are we in the build.

### Link to Minimal Reproducible Example

https://example.com

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
As you suggested, you want to **debug** something, I think your suggestion might make sense for cases where the user uses `--verbose` logging output, I think it makes more sense to have more output using the `.debug`.

**Comment by ematipico** [comment]
Let me work on this. I have few ideas in mind
