### ISSUE TITLE
Dev Toolbar blocking view from elements

### ISSUE THREAD

**Issue by at-the-vr** [withastro/astro#9337]
### Astro Info

```block
Astro                    v4.0.2
Node                     v20.10.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
                         unocss
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

- Dev Toolbar tends to block elements behind it
- In this case its a Astro Badge behind the toolbar
- Eventually the toolbar fades away but so does the audit error behind it
- [Repo to replicate](https://github.com/at-the-vr/brutal), I could not visualize Dev Toolbar on stackblitz, the repo needs to be run locally for that reason
- Exemplar Photo ⤵
![image](https://github.com/withastro/astro/assets/88548999/4cbc1b2d-674d-455a-aa87-ae620a7da50b)

### What's the expected result?

No comments

### Link to Minimal Reproducible Example

https://github.com/at-the-vr/brutal

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JeroenReumkens** [comment]
I have a similar issue in my website. There's a sticky element at the bottom of the screen. For me it would make a lof of sense if we could configure the position of the bar. 

For anyone unaware: You can disable the toolbar by running `npm run astro preferences disable devToolbar`

**Comment by ematipico** [comment]
> I have a similar issue in my website. There's a sticky element at the bottom of the screen. For me it would make a lof of sense if we could configure the position of the bar.
> 
> For anyone unaware: You can disable the toolbar by running `npm run astro preferences disable devToolbar`
