### ISSUE TITLE
Astro Dev Toolbar doesn't show full audit

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/astro#9346]
### Astro Info

```
Astro                    v4.0.2
Node                     v20.10.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
                         @astrojs/tailwind
                         astro-expressive-code
                         @astrojs/sitemap
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

MS Edge

### Describe the Bug

I can't see the full audit in the right corner.

![image](https://github.com/withastro/astro/assets/27698189/01f1d988-8d22-4c50-b3fd-eec7f379ff94)

### What's the expected result?

See it clearly.

### Link to Minimal Reproducible Example

https://github.com/withastro/starlight/tree/main/examples/basics

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kenji-webdev** [comment]
Also happening on Chrome 120.0.6099.72
