### ISSUE TITLE
"Input image exceeds pixel limit" error is too vague

### ISSUE THREAD

**Issue by tmcw** [withastro/astro#9351]
### Astro Info

```block
Astro                    v4.0.2
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

When I start importing content into Astro I get the error:

```
 generating optimized images
16:06:30   ▶ /_astro/untitled-1.TT4nkGxv_Z2rFvbz.webp (before: 107kB, after: 15kB) (+30ms) (1/101)
16:06:30   ▶ /_astro/frame_1.G23pLodK_1l8Gb9.webp (before: 101kB, after: 54kB) (+48ms) (7/101)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Input image exceeds pixel limit]
```

Which image? I have many images. Astro probably knows which one, and it should tell me.

### What's the expected result?

The error message is instructive and identifies the file that caused the error

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bvk5u3?file=src%2Fcontent%2Fblog%2Ffirst-post.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please do provide an example even if it only happens when building. This helps us track down the source of the bug.

**Comment by tmcw** [comment]
I'll try - the problem is that, because this error is not specific, I can't figure out what file is triggering it so I can't just use that for a repro. I did file a PR at #9352.

**Comment by tmcw** [comment]
Stackblitz also has a free tier limit of 1MB per file and the files that trigger this are likely > 1MB.

**Comment by Princesseuh** [comment]
This error is from Sharp, it's a bit of a weird one, typically happens on large images or animated ones with many pages
