### ISSUE TITLE
Middleware works locally, doesn't run at all when deployed to Vercel

### ISSUE THREAD

**Issue by bstro** [withastro/astro#9357]
### Astro Info

```block
Astro                    v4.0.3
Node                     v21.1.0
System                   macOS (x64)
Package Manager          yarn
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### Describe the Bug

Trying to deploy my Astro app to vercel. I wrote a middleware that implements basic HTTP authentication. 

When I run my app locally on the astro dev server, everything works as expected—the user/password prompt appears and if I enter the correct credentials, I am forwarded to the correct page. 

When I deploy to Vercel, there is no authentication at all, as if the middleware isn't being run.

### What's the expected result?

Middleware should behave identically whether I am running the project locally or when deploying to Vercel.
**Stackblitz**: https://stackblitz.com/~/github.com/bstro/github-pw6m1w (note the Auth required response)
**Deployment**: https://github-pw6m1w.vercel.app/ (note that the middleware doesn't seem to run at all)

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/bstro/github-pw6m1w

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@bstro  I furtherly checked, and it seems that we are emitting the edge middleware correctly, and it seems to be a Vercel issue where it doesn't run the file `middleware.mjs`. 

I'll keep you posted

**Comment by Mokto** [comment]
What if we run something like : `babel --plugins @babel/plugin-transform-modules-commonjs .vercel/output/functions/render.func/dist/middleware.mjs > .vercel/output/functions/render.func/dist/middleware.js` ? To transform the file back into something vercel can understand.

**Comment by ematipico** [comment]
> What if we run something like : `babel --plugins @babel/plugin-transform-modules-commonjs .vercel/output/functions/render.func/dist/middleware.mjs > .vercel/output/functions/render.func/dist/middleware.js` ? To transform the file back into something vercel can understand.

You could try it on your local environment, but I think Vercel must support this format. After all they support it for their normal functions.

**Comment by lilnasy** [comment]
Switching `middleware.mjs` to `middleware.js` made no difference. It doesn't seem to be part of Vercel's build output API at all. A comment in the relevant part points to the convention of `middleware.js` in root, next to `astro.config.mjs` and sure enough, that works.

<img width="356" alt="image" src="https://github.com/withastro/astro/assets/69170106/6dcac8c5-eabd-4b13-99a5-7c6fb3cce510">


...but not before it complained about being bundled incorrectly...

<img width="504" alt="image" src="https://github.com/withastro/astro/assets/69170106/08cbb244-25d2-4bd8-8b83-578eb1e614a1">

...which makes me wonder if edge middleware ever worked - vercel expects the edge middleware to be its own function in [this format](https://github.com/withastro/astro/assets/69170106/f1e1dcbd-7281-4eb2-9f50-38609d30ab32) which we never created.

**Comment by GiikiS2** [comment]
im having the same problem :/
