### ISSUE TITLE
`<ViewTransitions />` causes error, treats `<form method="post">` as `<form method="get">`

### ISSUE THREAD

**Issue by thuongvux** [withastro/astro#9368]
### Astro Info

```block
Astro                    v4.0.3
Node                     v21.2.0
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
```

### Describe the Bug

Enable `<ViewTransitions />` causes error
Submit form `<form action="/api/example" method="post">` will not work and it will treat like `<form action="/api/example" method="get">`
I have temporary solutions is disable `<ViewTransitions />` or go back to Astro v3.6.4.

### What's the expected result?

Open stackblitz link to see!

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/thuongvux/thuongvux-astro-v4.0.3-viewtransitions-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @thuongvux, 
in 3.x you had to explicitly enable view transitions for forms: 
```
<ViewTransitions handleForms/>
```
In 4.x form handling is active by default, see CHANGELOG.md entry for 4.0.0:
> https://github.com/withastro/astro/pull/9225 [c421a3d17](https://github.com/withastro/astro/commit/c421a3d17911aeda29b5204f6d568ae87e329eaf) Thanks [@natemoo-re](https://github.com/natemoo-re)! - Removes the opt-in handleForms property for `<ViewTransitions />`. Form submissions are now handled by default and this property is no longer necessary. This default behavior can be disabled by setting data-astro-reload on relevant `<form />` elements.

For your example:
```
<form action="/api/example" method="post" data-astro-reload>
```

**Comment by Titou325** [comment]
Hi! Stumbled across this as well. Maybe we could add a reference in https://docs.astro.build/en/recipes/build-forms/ as well to prevent this from happening?
