### ISSUE TITLE
Github mirrored Vercel deployments broken with pnpm

### ISSUE THREAD

**Issue by jon-xo** [withastro/astro#9382]
### Astro Info

```block
Astro                    v4.0.3
Node                     v20.10.0
System                   Linux (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/sitemap
                         unocss
                         @astrojs/preact
                         @astrojs/tailwind
```

### Describe the Bug

When deploying an Astro site inside a pnpm monorepo to Vercel via Github integration (using the `@astrojs/vercel/serverless adapter`), the deployment succeeds, but all requests fail with 500 errors. 

_Alternatively_ using the `vercel` cli to deploy the same repo/branch will succeed.

<details>
  <summary><i>Vercel error message</i></summary>

  `16:35:47 [ERROR] TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:637:13)
    at fetchApi (file:///var/task/dist/chunks/pages/404_XMCNvEM8.mjs:164:15)
    at file:///var/task/dist/chunks/pages/index_79s_JUYp.mjs:98:29
    at index (file:///var/task/dist/chunks/astro_iUOlBhcd.mjs:330:12)
    at callComponentAsTemplateResultOrResponse (file:///var/task/dist/chunks/astro_iUOlBhcd.mjs:1400:31)
    at renderToReadableStream (file:///var/task/dist/chunks/astro_iUOlBhcd.mjs:1350:32)
    at renderPage (file:///var/task/dist/chunks/astro_iUOlBhcd.mjs:2063:18)
    at renderPage (file:///var/task/dist/entry.mjs:1602:26)
    at #tryRenderRoute (file:///var/task/dist/entry.mjs:1721:24)`

</details>

<details>
<summary><I>Vercel screenshot</i></summary>

![Screenshot 2023-12-08 115000](https://github.com/withastro/astro/assets/73410390/37c98330-fccf-453f-840c-78b4d5616ec6)

</details>

### What's the expected result?

Vercel confirms a successful deployment and Astro site root URL returns HTTP code 200
OR
Vercel shows a failed deployment and Astro site root URL returns HTTP code 500

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/jon-xo/astro-min

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jon-xo** [comment]
_Update:_ Looks like the minimal reproduction **is** currently working, so I'm stumped on this one.
FWIW -- The fix [mentioned ](https://github.com/withastro/astro/issues/5020#issuecomment-1272754702) in issue #5020  is currently inoperable for Astro 4.0

**Comment by lilnasy** [comment]
Since your mention the minimal project with vercel and pnpm is not affected, could you try switching to node and testing locally?

**Comment by bluwy** [comment]
From the stack trace, it shows that the error comes from a function that called `fetchApi` in a 404 file, however I don't see that in the repro. I think it's likely that the function in your project called `new URL()` incorrectly that caused the error in prod, perhaps of an unexpected URL passed? I'll close this for now as there hasn't been a response in a while, but feel free to let us know if it's an issue on Astro side.
