### ISSUE TITLE
`npx @astrojs/upgrade` fails with "Version latest could not be found"

### ISSUE THREAD

**Issue by joeyfigaro** [withastro/astro#9384]
### Astro Info

```block
Astro                    v3.1.0
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/mdx
                         @astrojs/react
```

### Describe the Bug

Attempting to upgrade to v4.0.3 using `npx @astrojs/upgrade` fails with the following:
`▲  error Version latest could not be found!`

Trying to pass in an existing tag fails with the same error. I tried passing in both `astro@4.0.3` and `4.0.3` via:
`npx @astrojs/upgrade astro@4.0.3`
`npx @astrojs/upgrade 4.0.3`

![image](https://github.com/withastro/astro/assets/1386477/faa0a22f-d388-4f61-96a6-966ffceef2a8)

---

I'm not sure that a reproduction makes sense here since it's unrelated to using Astro and only occurs when attempting to upgrade. If you believe that's wrong and a repro could be useful for this, I will add one.

### What's the expected result?

Astro should successfully upgrade to 4.0.3.

### Link to Minimal Reproducible Example

N/A

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jacobthesheep** [comment]
Check again, it was probably caused by the npmjs outage.

**Comment by joeyfigaro** [comment]
![image](https://github.com/withastro/astro/assets/1386477/b9f2eefd-14e8-43d2-88b0-54d9058dc6ec)

@jacobthesheep that was it! I wasn't even aware of the outage. Thank you.
