### ISSUE TITLE
`transition:persist` and `astro:beforeload` listener are not working after switching between pages

### ISSUE THREAD

**Issue by bozzhik** [withastro/astro#9385]
### Astro Info

```block
Astro                    v4.0.3
Node                     v18.18.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

I have an error with `transition:persist` and with `document.addEventListener('astro:beforeload', handleScroll)`.
I wrote code that does not work in a project with astro `4.0`, as soon as I moved it, without changing it to the asro `3.4` project, it immediately worked.

I can't say anything, but maybe the problem isn't with a third-party library.
If necessary, I could probably make it into a new issue.

```javascript
---
import {widthLimit} from '../../layouts/Container.astro'
---

<header transition:persist class="fixed inset-0 h-fit z-[99] w-full bg-custom-black">
  <section class="grid grid-cols-2 pt-8 pb-2 text-2xl duration-300 xl:text-xl sm:text-lg place-items-center" class:list={widthLimit}>
    <a class="justify-self-start" href="/">
      <ul class="flex gap-10 sm:gap-5 justify-self-end">
        <li><a class="duration-300 hover:text-custom-yellow" href="/catalog/">Каталог</a></li>
        <li><a class="duration-300 hover:text-custom-yellow" href="/index.html#CONTACTS">Контакты</a></li>
      </ul>
    </a>
  </section>
</header>

<script>
  const header = document.querySelector('header')
  const headerBody = header.querySelector('section')
  const headerHeight = header.offsetHeight

  function handleScroll() {
    console.log('handleScroll')
    window.addEventListener('scroll', () => {
      const scrollPosition = window.scrollY

      if (scrollPosition >= headerHeight) {
        headerBody.classList.add('!py-2')
      } else {
        headerBody.classList.remove('!py-2')
      }
    })
  }

  handleScroll()
  document.addEventListener('astro:beforeload', handleScroll)
  document.addEventListener('astro:beforeload', handleScroll)
</script>

``` 

### What's the expected result?

The header should stick even after switching to another page. this is how this code works for me in the astro `3.0` project

### Link to Minimal Reproducible Example

https://tutea-git-fixedheader-mbozhik.vercel.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @bozzhik the `astro:beforeload` was used in the experimental view transition function before Astro 3.0. The event has been renamed. Its name is now `astro:after-swap`.

The `transition:persist` annotation has not been changed and works as before.  However, I would recommend adding a name, e.g. `transition:persist="header"`. This makes the matching of related elements deterministic.
