### ISSUE TITLE
Cannot read properties of undefined (reading 'postcss')

### ISSUE THREAD

**Issue by bfblackjack** [withastro/astro#9386]
### Astro Info

```block
Astro                    v4.0.3
Node                     v18.18.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

In dev environment, the issue does not occur. When building to production, _astro build_ fails with the following error: 

`Cannot read properties of undefined (reading 'postcss')`

The error can be replicated with a custom tailwind config file. When styles are defined in the config file, the error occurs. Th stackblitz attached replicates the error as described. Run `npm run build` and the error will occur.

### What's the expected result?

Astro builds the website for production.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7s5gfj?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jacobthesheep** [comment]
what are these unknown package managers?

**Comment by jacobthesheep** [comment]
> Package Manager          unknown

I'm wondering why it says `unknown` when you're using NPM.

**Comment by Princesseuh** [comment]
Your Tailwind integration is majorly outdated.

**Comment by lzm0x219** [comment]
I had the same problem, my package management tool was pnpm.

**Comment by lzm0x219** [comment]
Please modify it like this：`tailwind.config.mjs  -> tailwind.config.cjs `
