### ISSUE TITLE
Format code is wrong and breaks my project

### ISSUE THREAD

**Issue by SoyDiego** [withastro/astro#9394]
### Astro Info

```block
❯ npx astro info
Astro                    v4.0.3
Node                     v20.10.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
which: no xclip in (/home/diego/projects/SoyDiego-v4/node_modules/.bin:/home/diego/projects/SoyDiego-v4/node_modules/.bin:/home/diego/projects/node_modules/.bin:/home/diego/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/home/diego/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/home/diego/.nvm/versions/node/v20.10.0/bin:/home/diego/.pnpm-global:/home/diego/.pnpm-global/bin:/home/diego/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/diego/Android/Sdk/emulator:/home/diego/Android/Sdk/platform-tools:/home/diego/Android/Sdk/cmdline-tools/latest/bin)
```

### Describe the Bug

I don't know if a bug or i'm doing something wrong. It's my first time with Astro.
When I format the code, change the position of some `div` and is wrong.
I'm using VSCode and the Astro extension.

Here you have a video, when I format my code, breaks all the structure.

![wrong](https://github.com/withastro/astro/assets/19764334/6cc316f7-d7ed-415c-ada4-8597c4b00c22)

### What's the expected result?

Format in the correct way

### Link to Minimal Reproducible Example

-

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by arch-fan** [comment]
1. This should be on the repo https://github.com/withastro/language-tools, where the extension is maintained.
2. Send the html to replicate the problem.

**Comment by arch-fan** [comment]
It seems to be the something with ``

**Comment by SoyDiego** [comment]
> It seems to be the something with `</br>`, there's a typo. It should be `<br />`

Thanks for reply. I will write in the correct place.
And no, it's not that. I modified the typo and also removed br and the code continue breaks.
Tomorrow I will share the code. Thanks

**Comment by bluwy** [comment]
Yeah, I'd suggest opening an issue at https://github.com/withastro/language-tools instead, and please include a repro 🙏

**Comment by SoyDiego** [comment]
> Yeah, I'd suggest opening an issue at https://github.com/withastro/language-tools instead, and please include a repro 🙏

thanks @bluwy I will do it  :)
