### ISSUE TITLE
The statusText property of the response object in the endpoint should be preserved.

### ISSUE THREAD

**Issue by izure1** [withastro/astro#9401]
### Astro Info

```block
Astro                    v4.0.3
Node                     v18.18.2
System                   Windows (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

The `statusText` value of the new Response returned from the endpoint is not preserved. Here is an example code:

```
// /api/custom.ts
const { message } = error
return new Response(null, {
  status: 500,
  statusText: 'custom error message'
})
```

Afterwards, when checking the endpoint value with fetch in the browser, the `statusText` property of the response is changed to `Internal Server Error`.

I'm not sure if this is the intended behavior.

### What's the expected result?

The specified statusText value provided by the user should be displayed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1dagae?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
- Related https://github.com/withastro/astro/issues/8627

Implicit rerouting (basically returning any response with a status code of 404 or 500) has several caveats. This is one of them. If you can't avoid using it, I'd recommend using locals to pass data to the 500 route instead.

[Docs: Storing data in `context.locals`](https://docs.astro.build/en/guides/middleware/#storing-data-in-contextlocals)

**Comment by lilnasy** [comment]
Thanks for explaining your use case, it really helps! You might run into issues after deploying to production because statusText does not exist in http 2 or 3. If your platform hosts your app on these newer protocols, statusText will be removed. For your use case a response header might be better.
