### ISSUE TITLE
CSS Modules: duplicated CSS in production and dev

### ISSUE THREAD

**Issue by arty-name** [withastro/astro#9405]
### Astro Info

```block
Astro                    v4.0.4
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I have a shared CSS module and compose its declarations in other CSS modules. The contents of the shared module ends up in multiple CSS files, which are sometimes included on the same page, so the same CSS class is redefined multiple times on this page. In the dev mode I could understand this, but it also happens in production build.

### What's the expected result?

I guess the deduplication needs to be smarter, so that a СSS class is not re-defined on the page. I could understand if the current state is a tradeoff to reduce the number of loaded resources or something.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dzmctt?file=src%2Fcomponents%2Fshared.module.css

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is an upstream issue in Vite: https://github.com/vitejs/vite/issues/7504. Unfortunately there's not much we can do, so I'm closing in favour of it for now.

**Comment by arty-name** [comment]
Thank you! I wasn’t sure whether it’s really vite or the way Astro uses vite.
