### ISSUE TITLE
Support Node v20 in Vercel adapter

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#9408]
### Astro Info

```block
Astro                    v4.0.3
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none (it's @astrojs/vercel 6.0.1 in real deployment)
Integrations             none
```

### Describe the Bug

Astro fails to deploy on Vercel with Node 20 runtime configured:

```
[20:32:36.245] 19:32:36 [build] Complete!
[20:32:36.315] Build Completed in /vercel/output [51s]
[20:32:36.519] Deploying outputs...
[20:32:36.529] Error: The following Serverless Functions contain an invalid "runtime":
[20:32:36.529]   - render (nodejs18.x). Learn More: https://vercel.com/guides/serverless-function-contains-invalid-runtime-error
```

In a local build, adapter warns about Node 20 not supported (due to [this hardcoded list](https://github.com/withastro/astro/blob/8aa17a64b46b8eaabfd1375fd6550ff93727aa81/packages/integrations/vercel/src/serverless/adapter.ts#L36-L43) of supported version).

### What's the expected result?

If there are no known issues, Node 20 should be added to the supported list.

### Link to Minimal Reproducible Example

not reproducible on stackblitz, the issue is only on vercel

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by shishkin** [comment]
@matthewp Probably should have done it upfront. @jacobdalamb was first :)

@jacobdalamb yes, I have and got the error in the output as described above.

**Comment by jacobdalamb** [comment]
> @matthewp Probably should have done it upfront. @jacobdalamb was first :)
> 
> @jacobdalamb yes, I have and got the error in the output as described above.

My PR doesn't fix the bug though. Someone smarter can figure that one out.

**Comment by jacobdalamb** [comment]
> Adapter                  none (it's @astrojs/vercel 6.0.1 in real deployment)

I understand this part. Is @astrojs/vercel installed in your project?

**Comment by shishkin** [comment]
Yes, I have @astrojs/vercel@6.0.1 installed in my project. I think I ran `astro info` in a repo root instead of the web package.
