### ISSUE TITLE
Astro Image calculates SVG image width and height that is too small for SVGs using mm units

### ISSUE THREAD

**Issue by PaulMorris** [withastro/astro#9420]
### Astro Info

```block
Astro                    v4.0.4
Node                     v18.14.1
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
                         @astrojs/mdx
                         @astrojs/solid-js
```

### Describe the Bug

When I try to use Astro's `Image` component with my SVG images, the automatically calculated width and height is too small. On the page the SVG image is much smaller than when using the standard `img` HTML tag (with no width and height set).

It appears to happen with all of the images on my site, which were automatically generated by LilyPond (https://clairnote.org). Perhaps it is something about these particular SVGs?

### What's the expected result?

I would expect the size of the SVG to be the same when using `Image` as when using the img tag (with no width and height specified).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-eg6rsh?file=src%2Fpages%2Findex.astro,src%2Fimages%2FClairnote-blue-danube-excerpt.svg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
The library we're using to calculate image dimensions does not seem to support `mm` units correctly, as it returns them in pixel. I'm not surprised, considering this is the first time I see this unit used in the past 15 years I've been programming.

Unfortunately, there's no good replacement to this library at the moment and it is unmaintained, so unlikely for this to be fixed. In the meantime, I would suggest either manually updating your SVGs to use pixels, as it is the most common unit to use by far or specifying the proper size in the `width` and `height` attributes. 

There are many tools you can use to do this manually, such as this one: https://www.unitconverters.net/typography/pixel-x-to-millimeter.htm or. you can calculate it automatically in your code by doing a millimeter to pixel converter (returned `width` and `height` times `3.7795275591`).

**Comment by PaulMorris** [comment]
Thanks for the quick and helpful reply. It all makes sense. LilyPond is more focused on PDF and print media, so I'm not surprised its SVGs are atypical. Too bad the image library is unmaintained. LilyPond should probably provide a way to use pixel units in its SVG output.

Anyway, I've created a wrapper component that gets the width and height values (which are in mm units) from the ImageMetadata, calculates the pixel values by multiplying as you suggested, and then passes them to Image as props. That's working well as a workaround.
