### ISSUE TITLE
Compilation error occurs when using Japanese in .astro component.

### ISSUE THREAD

**Issue by fujitsuna-mediba** [withastro/astro#9421]
### Astro Info

```block
Astro                    v4.0.4
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome,Safari,Firefox

### Describe the Bug

Overview:
I want to use Japanese in the .astro component, but it results in a compilation error.

Details:
When using Japanese within the HTML tags of the .astro component, a compilation error occurs.  
This issue occurs with astro version 4.0.4. When downgrading to version 3.6.4, the error does not occur, and compilation proceeds as expected.
We have confirmed that errors occur in languages other than Japanese, such as Chinese and Korean.
Is this a bug in version 4?

We hope for an early resolution to this issue.

<img width="366" alt="スクリーンショット 2023-12-13 14 16 02" src="https://github.com/withastro/astro/assets/102793214/92ce13f4-2291-466e-8f38-f0880e5564a5">
<img width="199" alt="スクリーンショット 2023-12-13 14 15 46" src="https://github.com/withastro/astro/assets/102793214/8163e1de-5fb3-441b-b723-ab746b2bbbce">
<img width="835" alt="スクリーンショット 2023-12-13 14 14 51" src="https://github.com/withastro/astro/assets/102793214/70394b48-26e9-4725-9645-9eb293428f87">

### What's the expected result?

The expected result is that the errors are resolved in version 4 or later.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-raomph?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This seems to be related to the compiler code that's being added when the dev toolbar is enabled. Disabling it fixes the issue in the meantime:

```ts
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  devToolbar: {
    enabled: false
  }
});
```

We'll investigate what's causing this, apologies for the inconvenience!
