### ISSUE TITLE
astro 4 regression in using middleware' locals

### ISSUE THREAD

**Issue by morriq** [withastro/astro#9427]
### Astro Info

```block
Astro                    v4.0.4
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

every browser

### Describe the Bug

after upgrading to astro 4 from 3, my locals defined in middleware stopped working.

I have defined apollo client in middleware but in astro 4 I can not use it, components don't have access to this local.
The only errors I have is when I try to use this locals.

It works for simple locals, but fails with apollo client

middleware.ts (it's in sample)

```typescript
import {
  ApolloClient,
  ApolloLink,
  HttpLink,
  InMemoryCache,
  from,
  gql,
} from '@apollo/client/core';

export function onRequest({ locals, request }, next) {
  const client = new ApolloClient({
    ssrMode: true,
    cache: new InMemoryCache({
      resultCacheMaxSize: 10_000,
    }),
    defaultOptions: {
      watchQuery: {
        // it caches without user context, diffrent users can see same data,
        fetchPolicy: 'no-cache',
      },
      query: {
        // it caches without user context, diffrent users can see same data
        fetchPolicy: 'no-cache',
      },
    },
  });

  const httpLink = new HttpLink({
    uri: 'http://localhost:4321/api/graphql',
    credentials: 'include',
    headers: {
      cookie: request.headers.get('cookie') || '',
    },
  });

  locals.title = 'New title3';
  locals.client = client;

  // return a Response or the result of calling `next()`
  return next();
}

```

Attempt to using it in pages/index.astro:

```typescript
const data = Astro.locals;

console.log(data.client.query);
```

gives:

> [ERROR] Cannot read properties of undefined (reading 'query')

### What's the expected result?

Defined locals in middleware is accesible via Astro.locals.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ypwscr-wkksqr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@morriq  I noticed that removing the apollo client from the `middleware.ts` makes the `locals` work.

**Comment by ematipico** [comment]
It seems that `ApolloLink`, `HttpLink` are doing something that I can't trace. When importing them, logs inside the middleware aren't even appearing, which means that the middleware isn't even run

**Comment by lilnasy** [comment]
This works. Looks like vite trips up over CJS, and fails silently.
```ts
import x from '@apollo/client/core';
const {
  ApolloClient,
  ApolloLink,
  HttpLink,
  InMemoryCache,
  from,
  gql,
} = x
```

**Comment by ematipico** [comment]
Closing, as it seems to be a bug of Vite
