### ISSUE TITLE
Astro 4.0.5 i18n build returns unwanted html

### ISSUE THREAD

**Issue by Cacamoto** [withastro/astro#9436]
### Astro Info

```block
Astro                    v4.0.5
Node                     v21.3.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/solid-js
```

### Describe the Bug

I'm using   prefixDefaultLocale: true,
Which should redirect to /en_
Instead it lands me to / which undesired html that looks like this:
<img width="740" alt="Screenshot 2023-12-14 at 23 20 20" src="https://github.com/withastro/astro/assets/98987772/9a2d0f9c-5163-478c-b2e5-0e4630586711">

### What's the expected result?

For it to work as it does on localhost.

### Link to Minimal Reproducible Example

stackblitz didnt let me to add node adapter

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Hey @Cacamoto , we need a reproduction. Without it, we can't help. If you can't share a stackblitz project, create a minimal repository.

**Comment by Cacamoto** [comment]
Sorry, been busy, here it is:
https://github.com/Cacamoto/test

**Comment by Reaver86** [comment]
I'm facing the same issue, without any adapters/integrations. just latest cli result, adding i18n + prefixDefaultLocale: true and the build is missing the index.html of the default locale

**Comment by castarco** [comment]
I'm not sure if it's exactly the same, but when using the cloudflare adapter, the option `prefixDefaultLocale` does not help anymore to ensure that the default locale has its own prefix, and "goes back" to the default behaviour (the default locale does not have its own directory in the generated code).

**Comment by ematipico** [comment]
@castarco @Reaver86 Is this an issue with the `@astrojs/node` adapter? 

The instructions aren't very clear, and the reproduction doesn't say anything.

**Comment by castarco** [comment]
> The instructions aren't very clear, and the reproduction doesn't say anything. Please tell me exactly what's the expected behaviour and how to reproduce the issue.

Hi. In my case it was an issue with the cloudflare adapter, but adding an index.astro file to the pages root solved my problem.

**Comment by ematipico** [comment]
I used the `preview` command, and it seems to be working as expected. 

@Cacamoto You are using `output: "hybrid"`, which means that your homepage is emitted as an HTML file, which contains the redirect instructions. If you wait 2/3 seconds, the browser does the redirect.

That's how static redirects are emitted in Astro.

**Comment by Cacamoto** [comment]
@ematipico

**Comment by LaundroMat** [comment]
Is there a way to configure the redirect message or disable it alltogether and redirect immediately? (I'm using Netlify, but using its redirect rules does not override the Astro redirect message).

**Comment by ematipico** [comment]
> Is there a way to configure the redirect message or disable it alltogether and redirect immediately? (I'm using Netlify, but using its redirect rules does not override the Astro redirect message).

The next release will allow an option to disable the redirect

**Comment by LaundroMat** [comment]
Thanks for the heads-up. Fwiw, I moved my default language contents and pages to their root directories and set `prefixDefaultLocale` to `false` to eliminate the redirect.

**Comment by TheElegantCoding** [comment]
@ematipico There is already an option to disable the 2 seconds wait if the redirect ?

**Comment by teamzz111** [comment]
Still happening: when I disable the redirect option, it returns the default page.

The expected behavior should be: 'User enters the page and is immediately redirected to the route with i18n, without any blank screens.'

**Comment by artt** [comment]
I think setting default delay to 0 seconds, or providing a way to specify this like @TheElegantCoding suggests would be nice.

**Comment by artt** [comment]
@Cacamoto As I understand, the issue hasn't been resolved for you, right? Would you mind reopen the issue? Thanks!

**Comment by TheElegantCoding** [comment]
@artt  My suggestion is something that by default Astro cant make, it is something that I suggest to be added, we should be able to control the seconds of the redirect Astro makes

**Comment by artt** [comment]
Yes agree. So I'm wondering if this issue should be reopened.

**Comment by Ricardo-MT** [comment]
It would be nice to either remove the delay or have a way to customize either the message or the component being displayed whilst the redirection happens.

**Comment by ematipico** [comment]
I created a proposal for that 

https://github.com/withastro/roadmap/discussions/844
