### ISSUE TITLE
Query Params Shouldn't Be Accessible in Pre-rendered Pages During Development

### ISSUE THREAD

**Issue by jamesqquick** [withastro/astro#9440]
### Astro Info

```block
Astro                    v4.0.5
Node                     v20.6.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

Query string parameters from the URL should not be available when the page is pre-rendered. This is working correctly when deployed (can't access query string params), but doesn't work when running locally (can have access to query string params). 

This made debugging much more difficult for me as my code (incorrectly) worked when running locally, but then didn't appear to work when deployed.

### What's the expected result?

When running locally, I would expect for my code not to have access to query string parameters for a prerendered page.

Additionally, I would love for there to be a warning or error shown when trying to access query string params on a prerendered page. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7xnqph?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
IMO, query params shall be preserved even if `prerender` is set to true. Simply to maintain the consistency in writing idiomatic Astro code that does allow access to Astro.url and it's properties even when it's being pre-rendered.

**Comment by jamesqquick** [comment]
@rishi-raj-jain Any suggestions on how to avoid the confusion when being deployed to production? Right now, there's a disconnect between dev and prod which becomes really hard to debug.
