### ISSUE TITLE
No loader is configured for ".node" files: ...sharp-darwin-arm64v8.node

### ISSUE THREAD

**Issue by xriter** [withastro/astro#9442]
### Astro Info

```block
Astro                    v4.0.5
Node                     v18.19.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

I tried upgrading to Astro 4.0.5 from the 3.x. But now when i run `npm run dev` I get greeted with this error:

```
✘ [ERROR] No loader is configured for ".node" files: node_modules/astro/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node

    node_modules/astro/node_modules/sharp/lib/sharp.js:10:27:
      10 │   module.exports = require(`../build/Release/sharp-${platformAndArch}.node`);
```

<img width="948" alt="Scherm­afbeelding 2023-12-15 om 17 49 40" src="https://github.com/withastro/astro/assets/70454441/1a919300-201e-4a4c-a669-a78c21c89c96">

### What's the expected result?

I am not sure if this is a platform specific issue? But this error should not be here I guess. I don't know how to solve it.
I tried `npm uninstall sharp` and `npm install sharp`. (now on version `"sharp": "^0.33.0"`
(I do think sharp is included with Astro these days? So no separate sharp install should be necessary?)

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jacobdalamb** [comment]
Try removing your `node_modules` folder and `package-lock.json` file and reinstall your packages.

**Comment by jacobdalamb** [comment]
Can you reproduce it in stackblitz?
