### ISSUE TITLE
astro.config doesn't warn user

### ISSUE THREAD

**Issue by whit3st** [withastro/astro#9448]
### Astro Info

```block
Astro                    v4.0.5
Node                     v21.1.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         astro-robots-txt
```

### Describe the Bug

astro.config didn't warn me when I had two same instances.
![astroconf](https://github.com/withastro/astro/assets/33714079/5fc57fbe-b8b8-45ab-b33e-510fd9e6f70d)

### What's the expected result?

Normally, I would want to be warned if there is a mistake in this file. On top of that, because of this issue, CSS file is not created at build. Everything works fine, I can make a build but CSS file is not created. That was the reason I found this issue.

I was just testing astro so wanted to create some sort of portfolio website. With this mistake, CSS file is not generated. You can see the result website down below.

### Link to Minimal Reproducible Example

https://boisterous-rabanadas-8e49b7.netlify.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SerekKiri** [comment]
That's a normal javascript behaviour, I don't think this would be something doable to do within astro itself as astro only receives one of those properties (the latter one only) not both, although that probably could be implemented in IDE extensions for astro 🤔

**Comment by whit3st** [comment]
Yes, you're correct. I just wanted to mention because it can be hard to find when you use too many add-ons and there is an another line of integrations with just one add-on (maybe? can happen). Adding this feature to the extension is a great idea.

**Comment by ematipico** [comment]
@whit3st you could propose a rule to https://github.com/ota-meshi/eslint-plugin-astro

But we can't do anything about it. That's JavaScript
