### ISSUE TITLE
version 4.0.4+ leaves manifest_HASH.mjs file behind in the build ouput folder

### ISSUE THREAD

**Issue by kireerik** [withastro/astro#9450]
### Astro Info

```block
Astro                    v4.0.4
Node                     v21.4.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

See the title.

### What's the expected result?

Works the same as before version 4.0.4.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4ckdit (created by @vedxp)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jacobdalamb** [comment]
Please reproduce the issue.

**Comment by vedxp** [comment]
> Please reproduce the issue.

Here's a minimal reproduction on StackBlitz:
https://stackblitz.com/edit/github-4ckdit?file=dist%2Fmanifest_CxEKb7vn.mjs
