### ISSUE TITLE
JSON import data mutation is shared between pages

### ISSUE THREAD

**Issue by ijanos** [withastro/astro#9454]
### Astro Info

```block
Astro                    v4.0.6
Node                     v18.18.2
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Consider these files:

data.json
```
[ 1, 2, 3, 4, 5, 6, 7 ]
```

a.astro
```
---
import array from "../data.json";
---

{ array.reverse().map((n) => ( `${n}, `)) }

```

b.astro
```
---
import array from "../data.json";
---

{ array.map((n) => ( `${n}, `)) }
```

Both `dist/a/index.html` and `dist/b/index.html` contains the reversed list:
```
<!DOCTYPE html>7, 6, 5, 4, 3, 2, 1, 
```

The output of `build` depends on the order of the files. If I rename `a.astro` to `c.astro` then the output of `b.astro` will change.

### What's the expected result?

I expected mutating an import in one file to not mutate the same import data in other files. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dk4dwa-lo26ey?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
This is unfortunately just how imports work. A json "module" is the same as `export default JSON.parse(readFile(...))`, which you would expect to be singular. It might possible to prevent this behavior just for json imports, but we would be going against the platform by doing that.
