### ISSUE TITLE
[astrojs/netlify] generated adapter config should use `@astrojs/netlify` import

### ISSUE THREAD

**Issue by Skn0tt** [withastro/astro#9459]
### Astro Info

```block
n/a
```

### Describe the Bug

When running `npx astro add netlify`, the generated code uses the `@astrojs/netlify/functions` import. This deprecated with  v4 of the adapter.

### What's the expected result?

It should use the `@astrojs/netlify` import instead. 

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jacobdalamb** [comment]
This sounds correct per the docs, the Netlify example page and release notes for v3.0 [@astrojs/netlify@3.0.0](https://github.com/withastro/astro/releases/tag/%40astrojs%2Fnetlify%403.0.0).

**Comment by jacobdalamb** [comment]
> We've published v4 this morning, which deprecated it in favour of the `@astrojs/netlify` import: [withastro/adapters@`e21ffd2`/packages/netlify/src/functions.ts#L4-L6](https://github.com/withastro/adapters/blob/e21ffd29edd63d7f9d7024071f5e933f433a5686/packages/netlify/src/functions.ts#L4-L6)

Oh.
