### ISSUE TITLE
DevTool Bar have shadow when Printing on Development Mode

### ISSUE THREAD

**Issue by withered-flowers** [withastro/astro#9468]
### Astro Info

```block
Astro                    v4.0.6
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

When I tried to click a button with "window.print" on the page that have devtoolbar enabled, it will show an "artefact" / "border" in the page.

<img width="355" alt="Screenshot 2023-12-19 at 13 05 03" src="https://github.com/withastro/astro/assets/1587199/19d7d1a1-a84a-4925-a529-c1f61d1282d7">

### What's the expected result?

It should not have an "artefact" / "border" shown

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/devtool-problem?file=src%2Fpages%2Findex.astro&title=Astro%20Starter%20Kit:%20Blog

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Hi @withered-flowers , this is out of scope. The toolbar doesn't aim to be "hidden" when trying to print a page. 

You can disable the toolbar from your astro config, print the page, and put it back.
