### ISSUE TITLE
slotted react children get wrapped with `astro-slot`

### ISSUE THREAD

**Issue by gVguy** [withastro/astro#9474]
### Astro Info

```block
Astro                    v3.6.0
Node                     v18.14.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### Describe the Bug

When passing astro children from astro component into a react component, the resulting DOM looks like this:
```
<ReactComponent>
  <astro-slot>
    <AstroChild />
    <AstroChild />
  <astro-slot>
</ReactComponent>
```
This gets in the way when react component's functionality tracks and depends on children length.

It would be very helpful in such cases if we could slot children without wrapping them in `<astro-slot>`

### What's the expected result?

Provided children are not wrapped by <astro-slot> element (or at least there's an option to unwrap)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zeeic2?file=src%2Fcomponents%2FReactComponent.jsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
I'm not sure but I think that's an Astro limitation. Islands require this web component to work

**Comment by bluwy** [comment]
Yeah this is a limitation with how the islands work. It won't be changed any time soon, so if you rely on it, you may need to workaround at the meantime. The React integration also has the `experimentalReactChildren` option but I'm not sure if that would fix it. I'll close this for now.
