### ISSUE TITLE
🐛 BUG: `.html` pages unescape escaped entities in JS strings

### ISSUE THREAD

**Issue by delucis** [withastro/astro#9480]
### What version of `@astrojs/compiler` are you using?

0.27.2 (astro@1.5.2)

### What package manager are you using?

npm

### What operating system are you using?

macOS / Stackblitz

### Describe the Bug

It appears that `.html` pages unescape escaped entities in JS strings causing issues when Vite tries to load the output.

For example:

```html
<script>
  const count = 6;
  console.log(`There are \`${count}\`!`);
  console.log('Multiline\n string.');
</script>
```

- The escaped backticks cause a `Parse failure: Expecting Unicode escape sequence \uXXXX` error
- The `\n` gets converted into a literal new line character, breaking the JS string syntax.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-prairu?file=src/pages/index.html

**Comment by MoustaphaDev** [comment]
Anyone feel anyone feel free to snag this one, the bug should be in this rehype plugin
https://github.com/withastro/astro/blob/2fea174303ca60f4765c6294d99ebc7a19e73403/packages/astro/src/vite-plugin-html/transform/escape.ts#L8

**Comment by eryue0220** [comment]
Can I have a try for this?

**Comment by MoustaphaDev** [comment]
Sure, go ahead @eryue0220!
