### ISSUE TITLE
Can't prevent form's submission (page reload) if ViewTransitions is used

### ISSUE THREAD

**Issue by slaetthult** [withastro/astro#9488]
### Astro Info

```block
Astro                    v4.0.6
Node                     v18.18.2
System                   macOS (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/alpinejs
                         @astrojs/partytown
```

### Describe the Bug

I can't prevent form's submission if ViewTransitions is used. Or at least page gets reloaded.

```
<form onsubmit="return false;" method="POST">
    <button type="submit">Submit</button>
</form>
```
This form gets still submitted even though return false is used. Or at least page gets reloaded.
As soon as I remove ViewTransitions, everything works like expected.

Everytime I click the button, I get the following in terminal:
![Bildschirmfoto 2023-12-20 um 17 04 17](https://github.com/withastro/astro/assets/22275417/c8913d60-63eb-43d0-b76e-bf195e748deb)

### What's the expected result?

Form should not get submitted if onsubmit="return false;" is used and page should not reload.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ihjv95?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @slaetthult, starting with Astro v4.0.7 you can call event.preventDefault() from a submit event listener to prevent the default behavior, see #9486

**Comment by martrapp** [comment]
please upgrade to 4.0.7 and try this:
```astro
---
import Layout from '../layouts/Layout.astro';
import Card from '../components/Card.astro';
---

<Layout title="Welcome to Astro.">
  <main>
    <form  method="POST">
      <button type="submit">Submit</button>
    </form>
  </main>
</Layout>
<script>document.querySelector("form").addEventListener('submit',(e)=>e.preventDefault())</script>
```

**Comment by slaetthult** [comment]
It works, thank you a lot!

**Comment by martrapp** [comment]
👍🏼 Good to hear!

**Comment by ArthurSalle** [comment]
Hi @martrapp , I'm currently facing the same problem but I'm using Astro with SSR for my form submission, is there any solution like the preventDefault() method but not on the client side?
At the first page load, every thing is fine but once I submit the form and then refresh multiple time my page it submit my form and my log('here') still appears.

I'm using it like this: 

`---
if (Astro.request.method === "POST") {
  console.log("here");
}
---

<form method="POST"></form>`

Thanks 🙂

**Comment by martrapp** [comment]
Hi @ArthurSalle 👋🏼, sadly I have no experience with SSR. But you should ask in the #support channel [over at discord](https://discord.gg/astrodotbuild)!

**Comment by CaseoJKL** [comment]
> Ok, I'll take a look at it, thanks for your quick reply! 🚀

Any updates on this issue ?

**Comment by ArthurSalle** [comment]
> > Ok, I'll take a look at it, thanks for your quick reply! 🚀
> 
> Any updates on this issue ?

No, not yet 🤷🏼‍♂️

**Comment by CaseoJKL** [comment]
https://docs.astro.build/en/recipes/build-forms-api/

I wonder why it requires `A UI Framework integration` installed.
Can we not do this without a UI Framework integration ?

**Comment by ArthurSalle** [comment]
Yes you can but it seems to be a lit bit more tricky without an ui framework. 


If I submit my form "normally" by clicking my submit button every thing is okay. But then if I refresh the page my form is being submitted again and again. So, I've added a button with a name and a value.


```javascript
---
if (Astro.request.method === "POST") {
  console.log("here"); // execute on the first submit & every time I refresh the page

try {
    const formData = await Astro.request.formData()
    const submitBtn = formData.get('submit');

    if (submitBtn === 'submit-btn') {
        console.log('log only when btn clicked') // execute only when the submit btn is clicked and never again
    }
 
} catch {}

}

---

<form method="POST">

//input 

 <button name="submit" value="submit-btn">Submit</button>
</form>
```

I hope it can help you ! If not, tell me more details about your problem !

**Comment by CaseoJKL** [comment]
This kind of looks cursed, there should be a simpler solution to be honest. like reasonable as to why the issue is happening to begin with.

**Comment by evokeapps** [comment]
I fixed it by adding a `return Astro.redirect(REDIRECT_URL)`
