### ISSUE TITLE
RSS: including full content renders JSX

### ISSUE THREAD

**Issue by alexschcom** [withastro/astro#9489]
### Astro Info

```block
Astro                    v4.0.7
Node                     v20.5.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

When including the full blog post content in `rss.xml.js` [according to Astro's docs](https://docs.astro.build/en/guides/rss/#including-full-post-content), JSX expressions are not evaluated, but instead rendered as plain text.

### What's the expected result?

JSX expressions should be processed and rendered just as they are on the webpage. The only way I can think of doing that is to have Astro's own MDX compiler render the blog posts body, instead of some third-party plugin...

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-m7fr8o?file=src%2Fcontent%2Fblog%2Fpost.mdx,src%2Fpages%2Findex.astro,src%2Fpages%2Frss.xml.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is tracked at https://github.com/withastro/roadmap/discussions/419
