### ISSUE TITLE
Astro build takes 6 minutes for build

### ISSUE THREAD

**Issue by mProjectsCode** [withastro/astro#9494]
### Astro Info

```block
Astro                    v4.0.7
Node                     v20.9.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
                         @astrojs/svelte
```

### Describe the Bug

Running astro build in [my project](https://github.com/mProjectsCode/obsidian-stats/tree/master/website) takes 6 minutes on my machine and 9 minutes on github actions. People on the discord told me that that is quite long and that I should open an issue for it.

I have around 1.6k mdx files in the project, each of which is importing an astro component which is importing one client-only svelte component.

### What's the expected result?

Astro build to be faster.

### Link to Minimal Reproducible Example

not applicable

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
This is being worked on behind the experimental content collection cache flag.

https://docs.astro.build/en/reference/configuration-reference/#experimentalcontentcollectioncache

**Comment by mProjectsCode** [comment]
![image](https://github.com/withastro/astro/assets/61602848/c75d2c63-977b-4c91-838b-a86a731d0da6)

I guess there is a good reason why it is experimental.

**Comment by ematipico** [comment]
@mProjectsCode I strongly suggest filing any issue you find, this will help us to make it stable faster. Thank you!

**Comment by mProjectsCode** [comment]
can do

**Comment by mProjectsCode** [comment]
just opened #9499
