### ISSUE TITLE
`experimental.contentCollectionCache` causes error on build

### ISSUE THREAD

**Issue by mProjectsCode** [withastro/astro#9499]
### Astro Info

```block
Astro                    v4.0.7
Node                     v20.9.0
System                   Linux (x64)
Package Manager          bun (also happens with node)
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
                         @astrojs/svelte
```

### Describe the Bug

When enabling the [content collection cache](https://docs.astro.build/en/reference/configuration-reference/#experimentalcontentcollectioncache) flag, my project fails to build with some import error.

Edit: Here is a picture of the error:
![image](https://github.com/withastro/astro/assets/61602848/544514bb-6ebc-473e-868a-f5b40adc493d)

### What's the expected result?

The project builds without error.

### Link to Minimal Reproducible Example

https://github.com/mProjectsCode/obsidian-stats/tree/346c047c3aea51d6e69a4b80e8f7a28a54830895

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by raygesualdo** [comment]
Came here to file the same bug.

```
Astro                    v4.4.4
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         astro-expressive-code
```

I don't have it configured at the moment, but it's happening locally in this repo: https://github.com/raygesualdo/raygesualdo.com

**Comment by dawaltconley** [comment]
I am wondering if this is related to content files having duplicate content? I was able to reproduce in a fresh Astro project like this:

1. run `npm create astro@latest` and select the blog template
2. enable the content collection cache in the astro config
3. build any number of times (builds fine)
4. copy `src/content/first-post.md` and rename it anything else (e.g. `src/content/first-post-copy.md`)
5. run astro build twice

This reliably fails for me on the second build after copying a content file without changing its contents.

**Comment by techguysimon** [comment]
Any update on this? I am experiencing the same issue. @dawaltconley's theory might add up as in my situation I have events where some are recurring. In these cases the file is copied to an occurences collection with a dated filename but the same content.

**Comment by Marocco2** [comment]
I found that caching inside node_modules were unreliable. Setting a /cache folder on root project would alleviate all the issues

**Comment by techguysimon** [comment]
> I found that caching inside node_modules were unreliable. Setting a /cache folder on root project would alleviate all the issues

I just tried that and I am getting the same error. 

` experimental: {
    contentCollectionCache: true
  },
  cacheDir: './_astro_cache'`

**Comment by Marocco2** [comment]
> > I found that caching inside node_modules were unreliable. Setting a /cache folder on root project would alleviate all the issues
> 
> I just tried that and I am getting the same error. 
> 
> ` experimental: {
>     contentCollectionCache: true
>   },
>   cacheDir: './_astro_cache'`

Clean node_modules and retry that if you haven't
