### ISSUE TITLE
Dynamic routing: getStaticPaths() is trying to generate paths for my font files in the public folder?

### ISSUE THREAD

**Issue by leone6** [withastro/astro#9505]
### Astro Info

```block
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/preact
```

### Describe the Bug

not sure why i am getting warning messages in the terminal that don't make any sense. i have a folder in the public folder for some font files, and i'm trying to use dynamic routing for a content collection. but for some reason, the warning messages are telling me that getStaticPaths() is trying to generate a dynamic path for each of my font files? why is it doing this?

[WARN] [router] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `*RANDOMLY TRUNCATED DYNAMIC PATH HERE*/fonts/*FONT FILE NAME HERE*`.

### What's the expected result?

stop generating dynamic paths for my font files in the public folder

### Link to Minimal Reproducible Example

https://www.sorryidonthavetimeforthis.com

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by leone6** [comment]
UPDATE: this was an error on my end. in my global css file, i had set the font face urls like this:
"../fonts/*.woff2" instead of "/fonts/*.woff2"

removing the two periods in the url seems to have fixed the problem, and paths are not being generated for the font files anymore.

**Comment by g-beier** [comment]
I had a similar issue, but instead of using `(../fonts`, I wrote `(font/...` without the slash.
