### ISSUE TITLE
Styles Not Loading When Executing 'npm run dev' Command in PowerShell Terminal

### ISSUE THREAD

**Issue by Eliseo500** [withastro/astro#9506]
### Astro Info

```block
Astro                    v4.0.7
Node                     v20.9.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When executing the npm run dev command on a PowerShell terminal in an empty project with no integrations, the server functions correctly. However, the rendered app consists of plain HTML, and the styles defined in the <style> tags within the template do not take effect.

![image](https://github.com/withastro/astro/assets/105016561/262f2f71-be28-4bf4-b84f-43ecac0a5c81)

When the command is executed in the windows command prompt, the server works correctly and all styles are loaded

![image](https://github.com/withastro/astro/assets/105016561/a0c2d58a-eeba-4c00-8368-ca5990ab11b1)

Terminal used during testing

![image](https://github.com/withastro/astro/assets/105016561/a7566638-e45c-4664-a69c-9e225ce936ba)

### What's the expected result?

The expected result is that the styles are processed correctly regardless of the terminal used

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-vm4tdn?file=README.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
I could not reproduce it. Is there something else about your setup that could be involved?
<img width="701" alt="image" src="https://github.com/withastro/astro/assets/69170106/af856a0b-9f57-4bd5-9c56-284b76815b41">
