### ISSUE TITLE
Svelte island does not expect unknown props, causes warning

### ISSUE THREAD

**Issue by nikhilk** [withastro/astro#9508]
### Astro Info

```block
Astro                    v4.0.7
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
                         @astrojs/tailwind
```

### Describe the Bug

I have a very simple counter svelte component included into an Astro component.

When viewing the page after running "astro dev", I see the following warning in the console.

```
<Counter> was created with unknown prop 'data-astro-cid-j7pv25f6'
```

I see this is a warning generated from the stackblitz sample for Svelte as well (linked as reproducible example)

### What's the expected result?

Ideally this warning should not appear, as it adds noise to the console. With a warning per component, this can easily make the experience poor.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-svelte?file=src%2Fcomponents%2FCounter.svelte

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by Indyandie** [comment]
:relieved: Phew… I'm glad I found this! I thought it had something to do with one of my dependencies. 

```
Card.svelte:82 <Card> was created with unknown prop 'data-astro-cid-bqi7seht'
```

I'm in the of upgrading to astro 4
