### ISSUE TITLE
Astro Image remote url is not working with Firebase Storage

### ISSUE THREAD

**Issue by zenshindm** [withastro/astro#9511]
### Astro Info

```block
NPM 
Astro 4.0.6
Node 20.10
Yes, i did included image authority 
image: {
    domains: ["firebasestorage.googleapis.com", "placehold.co", "res.cloudinary.com"],
  },
```

### Describe the Bug

Astro Image remote url with firebase storage Work in npm run dev but fail in npm run build

build error:
file:///D:/webproject/astro/ecliptic-equinox/node_modules/astro/dist/assets/build/generate.js:109
        throw new Error(`An error was encountered while reading the cache file. Error: ${e}`);
              ^

Error: An error was encountered while reading the cache file. Error: TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must not include encoded \ or / characters

main issue is the generate.js does not allow these character "%2F" in firebase storage url 
eg: https://firebasestorage.googleapis.com/v0/b/hari-ecom.appspot.com/o/documents%2FProductCoverPhotos%2Fdisruptivo%20(Small).jpg?alt=media&token=529e428d-0eaf-4618-aed3-c6b9fe28b6d2

meanwhile, other remote url from placehold or cloudinary work fine 
 <Image
      src="https://placehold.co/600x400"
      alt=""
      width="500"
      height="500"
    />

Can you make it accept the firebase storage url ? thanks 
and firebase storage unable to customize url structure 

### What's the expected result?

` <Image
      src="https://firebasestorage.googleapis.com/v0/b/hari-ecom.appspot.com/o/documents%2FProductCoverPhotos%2Fdisruptivo%20(Small).jpg?alt=media&token=529e428d-0eaf-4618-aed3-c6b9fe28b6d2"
      alt="test"
      width="500"
      height="500"
    />`
    
    expected no build error

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/quizzical-montalcini-kxxyvm

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by davidjss04** [comment]
Hello friend, I have the same problem, when I build the project, the upload image in Firebase shows an error.

![image](https://github.com/withastro/astro/assets/62025422/0bc60cfe-e286-4743-ac36-c1251e72a52a)
