### ISSUE TITLE
import.meta.env.PROD = false when env.MODE = production

### ISSUE THREAD

**Issue by ppo** [withastro/astro#9515]
### Astro Info

```block
Astro                    v4.0.3
Node                     v21.2.0
System                   macOS (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/mdx
                         @astrojs/partytown
                         @astrojs/sitemap
```

### Describe the Bug

Running `pnpm build && pnpm preview`, `import.meta.env.MODE == production` but `import.meta.env.PROD == false` (and `DEV == true`).

Same after deploying the site on my server (using the node adapter).

In the doc: _`import.meta.env.MODE`: The mode your site is running in. This is `development` when running `astro dev` and `production` when running `astro build`._

Are `DEV` and `PROD` well based on `MODE`?

It works fine on StackBlitz 🫤  
As they're running Astro 4.0.7, I upgraded my version but it doesn't fix the problem.

#7463 and #6241 reported a kind of similar but opposite problem, `MODE` being always development, and `DEV`and `PROD` changing correctly.

### What's the expected result?

Running `pnpm build && pnpm preview`…

```
import.meta.env.MODE == production
import.meta.env.PROD == true
import.meta.env.DEV == false
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tkk8yu

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by y-nk** [comment]
https://vitejs.dev/guide/env-and-mode#node-env-and-modes

**Comment by ppo** [comment]
Thanks @y-nk… and sorry, coding asleep 🙄, didn't read the first line of Astro docs 🫤
