### ISSUE TITLE
Using solidjs component SUID gets Error

### ISSUE THREAD

**Issue by geohuz** [withastro/astro#9517]
### Astro Info

```block
Astro                    v4.0.6
Node                     v20.10.0
System                   macOS (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/solid-js
```

### Describe the Bug

In a solidjs file add the following:
```
import { Button } from "@suid/material";
```

And astro gives the following error in browser:
```
SyntaxError
An error occurred.
Unexpected token 'export'
Stack Trace
/Users/geohuz/Coding/newtreeorg/node_modules/@suid/system/colorManipulator.js:21
export function hexToRgb(color) {
^^^^^^
```

### What's the expected result?

The @suid does work in vanilla vitejs environment.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vfwwej?file=src%2Fcomponents%2Fsolid%2FSButton.jsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
The library is not properly packaged for Node.js, hence it errors: https://publint.dev/@suid/material@0.15.1
