### ISSUE TITLE
Can't build anymore since upgrading v3 to v4

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#9518]
### Astro Info

```block
Astro                    v4.0.7
Node                     v18.14.2
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astro-aws/adapter
Integrations             @y_nk/cached-fetch
                         @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

There's an esbuild/config related error which i can't seem to fix myself. At the end of `astro build`, i get this error:

```
17:18:41
 finalizing server assets

17:18:41 [build] Rearranging server assets...
✘ [ERROR] No loader is configured for ".node" files: node_modules/sharp/build/Release/sharp-darwin-arm64v8.node

    node_modules/sharp/lib/sharp.js:10:27:
      10 │   module.exports = require(`../build/Release/sharp-${platformAndArch}.node`);
         ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve require("../vendor/**/*/**/*/versions.json")

    node_modules/sharp/lib/utility.js:58:21:
      58 │   versions = require(`../vendor/${versions.vips}/${platformAndArch}/versions.json`);
         ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

No loader is configured for ".node" files: node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
  Stack trace:
    at failureErrorWithLog (~/node_modules/esbuild/lib/main.js:1650:15)
    at ~/node_modules/esbuild/lib/main.js:1003:52
    at ~/node_modules/esbuild/lib/main.js:1085:16
    at handleIncomingPacket (~/node_modules/esbuild/lib/main.js:763:9)
    at Socket.emit (node:events:513:28)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

I believe this has to do with the installation of `sharp` coming with astro:assets, but since `@astro-aws/adapter` also has a pass on esbuild i'm not yet 100% sure that it's an astro issue.

although, _if_ astro forces-pack sharp it should be able to not include it. i'm releasing to lambda@edge where sharp _seems to be_ not supported.

### What's the expected result?

Should be able to build correctly

### Link to Minimal Reproducible Example

https://example.com/

### Side notes

Merry xmas 🎅 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by y-nk** [comment]
I removed the adapter in favor of @astrojs/node and it builds, so i'll close this and help fix the adapter. (FYI)

**Comment by y-nk** [comment]
FYI https://github.com/lukeshay/astro-aws/issues/119

**Comment by lukesteinbicker** [comment]
> I removed the adapter in favor of @astrojs/node and it builds, so i'll close this and help fix the adapter. (FYI)

I'm using @astrojs/node as my adapter and still encountering this issue.
