### ISSUE TITLE
Astro react integration results in a build error in a monorepo setup

### ISSUE THREAD

**Issue by nikhilk** [withastro/astro#9525]
### Astro Info

```block
Astro                    v4.0.7
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

I have a monorepo setup. In particular:

* packages.json and node_modules at root contains all the dependencies
* packages.json declares `workspaces: ["packages/*"]`
* Astro app is in packages/ui
* packages/ui/package.json does not declare any dependencies
* packages/ui is a simple astro app created using `npm create astro@latest` and `npx astro add react`

On the root of the monorepo
```
❯ npm run build

> example@0.0.1 build
> npm run --workspaces  build


> @example/ui@0.0.1 build
> astro build

15:14:46 [build] output: "static"
15:14:46 [build] directory: /home/projects/github-wjhcog/packages/ui/build/
15:14:46 [build] Collecting build info...
15:14:46 [build] ✓ Completed in 36ms.
15:14:46 [build] Building static entrypoints...
15:14:47 [build] ✓ Completed in 944ms.

 building client (vite) 
15:14:47 [vite] ✓ 31 modules transformed.
15:14:47 [vite] build/_astro/home.Xc8wNQS-.css      0.15 kB │ gzip:  0.14 kB
15:14:47 [vite] build/_astro/Counter.a6RvEjHi.js    1.31 kB │ gzip:  0.74 kB
15:14:47 [vite] build/_astro/index.LFf77hJu.js      6.71 kB │ gzip:  2.67 kB
15:14:47 [vite] build/_astro/client.olTvLX7Y.js   135.32 kB │ gzip: 43.72 kB
15:14:47 [vite] ✓ built in 618ms
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'astro:'
  Stack trace:
    at __node_internal_ (https://githubwjhcog-gxxy.w-credentialless.staticblitz.com/blitz.a2aabdd9.js:36:5406)
    at https://githubwjhcog-gxxy.w-credentialless.staticblitz.com/blitz.a2aabdd9.js:254:780
    at nextLoad (https://githubwjhcog-gxxy.w-credentialless.staticblitz.com/blitz.a2aabdd9.js:248:2120)
    at ESMLoader.<anonymous> (https://githubwjhcog-gxxy.w-credentialless.staticblitz.com/blitz.a2aabdd9.js:248:8230)
    at ESMLoader._createModuleJob2 (https://githubwjhcog-gxxy.w-credentialless.staticblitz.com/blitz.a2aabdd9.js:248:8151)
    at async https://githubwjhcog-gxxy.w-credentialless.staticblitz.com/blitz.a2aabdd9.js:181:966
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @example/ui@0.0.1 
npm ERR!   at location: /home/projects/github-wjhcog/packages/ui 
```

For some reason the empty dependencies list in packages/ui/package.json is causing build issues.

**Workaround**

Update packages/app/ui/package.json to include @astrojs/react as a dependency, even though its already declared in the package.json at the root of the monorepo:

```diff
   "dependencies": {
+    "@astrojs/react": "^3.0.8"
   }
```

```
❯ npm run build

> example@0.0.1 build
> npm run --workspaces  build


> @example/ui@0.0.1 build
> astro build

15:21:16 [build] output: "static"
15:21:16 [build] directory: /home/projects/github-wjhcog/packages/ui/build/
15:21:16 [build] Collecting build info...
15:21:16 [build] ✓ Completed in 38ms.
15:21:16 [build] Building static entrypoints...
15:21:17 [build] ✓ Completed in 965ms.

 building client (vite) 
15:21:18 [vite] ✓ 31 modules transformed.
15:21:18 [vite] build/_astro/home.Xc8wNQS-.css      0.15 kB │ gzip:  0.14 kB
15:21:18 [vite] build/_astro/Counter.a6RvEjHi.js    1.31 kB │ gzip:  0.74 kB
15:21:18 [vite] build/_astro/index.LFf77hJu.js      6.71 kB │ gzip:  2.67 kB
15:21:18 [vite] build/_astro/client.olTvLX7Y.js   135.32 kB │ gzip: 43.72 kB
15:21:18 [vite] ✓ built in 578ms

 generating static routes 
15:21:18 ▶ src/pages/index.astro
15:21:18   └─ /index.html (+10ms)
15:21:18 ▶ src/pages/home.astro
15:21:18   └─ /home/index.html (+4ms)
15:21:18 ✓ Completed in 49ms.

15:21:18 [build] 2 page(s) built in 1.65s
15:21:18 [build] Complete!
```

### What's the expected result?

Expected a monorepo setup to work.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wjhcog

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by enmanuelr** [comment]
I have lost a week to this problem. Thank you so much for taking the time to report it and to provide the result.

This really needs to be documented, if it can't be immediately mitigated. It's a very opaque situation. Very difficult to solve for.

**Comment by bluwy** [comment]
I wouldn't recommend structuring the monorepo this way as Astro has special heuristic that relies on Astro packages to be inside your project. It's not something we can easily fix without causing other perf issues.

This is already documented at https://docs.astro.build/en/guides/troubleshooting/#adding-dependencies-to-astro-in-a-monorepo. You can use `vite.ssr.noExternal: ['@astrojs/react']` to work around it.

**Comment by airtonix** [comment]
@bluwy Could you be more specific as to what you mean by: 

> I wouldn't recommend structuring the monorepo this way as Astro has special heuristic that relies on Astro packages to be inside your project.

Is it specific to the position of `astro.config.mjs` or just `CWD`  ? 

In my nxdev monorepo, my astro project has no package.json at all and there's only one at the root of the repo.

**Comment by bluwy** [comment]
I mean that if you have your Astro project at `my-project/packages/astro-app` for example, your dependencies should ideally be in `my-project/packages/astro-app/node_modules/*` and specified in `my-project/packages/astro-app/package.json`.

Though for your case:

> In my nxdev monorepo, my astro project has no package.json at all and there's only one at the root of the repo.

This _could_ be fine due to how the internals work. As a quick run through, our internal handling will read the closest `package.json` from your Astro project root, and will try to identify packages that needs special handling in Vite.

If your closest `package.json` file for your Astro project is the root, and it contains the dependencies like `@astrojs/react` etc, then that might work fine.
