### ISSUE TITLE
@astrojs/partytown: TypeError Failed to fetch when using Google Analytics 4

### ISSUE THREAD

**Issue by SuperSandyman** [withastro/astro#9528]
### Astro Info

```block
Astro                    v4.0.7
Node                     v20.9.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
                         astro-expressive-code
                         @astrojs/partytown
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome (MS Edge)

### Describe the Bug

When implementing Google Analytics 4 using @astrojs/partytown, the following error appears in the console.
```
 TypeError: Failed to fetch
    at c064db33-abc4-4bbd-8..11ce4b8b1fd:2:21128
    at rt (c064db33-abc4-4bbd-8..11ce4b8b1fd:2:21531)
(anonymous) @ c064db33-abc4-4bbd-8709-311ce4b8b1fd:2
```

I also get the following error in the data-pterror of the script tag in <head>.
```
<script type="text/partytown" src="https://www.googletagmanager.com/gtag/js?id=G-xxxxxx" data-pterror="TypeError: Failed to fetch
    at blob:https://www.sandyman.dev/c064db33-abc4-4bbd-8709-311ce4b8b1fd:2:21128
    at rt (blob:https://www.sandyman.dev/c064db33-abc4-4bbd-8709-311ce4b8b1fd:2:21531)"></script>
```

Both were displayed in Chromium-based browsers, and only the former in Firefox.

I have tried to reproduce this problem, but Stackblitz could not reproduce it. However, when I ran the code locally, the same problem appeared.

Sorry for my poor English:)

### What's the expected result?

Correctly measured number of accesses.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ysvmcv?file=src%2Fcomponents%2FBaseHead.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Maybe some notes from https://partytown.builder.io/google-tag-manager#forward-events and https://github.com/withastro/astro/pull/8588 might help, but I'm not really sure if `@astrojs/partytown` is doing something that's causing the error. It seems like a core partytown or configuration issue.

**Comment by lilnasy** [comment]
- Could be https://github.com/withastro/astro/pull/9419
Worth checking whether astro 4.0.5 is unaffected.

**Comment by matthewp** [comment]
The repro is not using ViewTransitions so this is unrelated to that.

This is an upstream issue, all the integration does is add the script to the page. 

Check out the partytown issue tracker, lots of discussions on how to get it to work with GA. For ex. https://github.com/BuilderIO/partytown/issues/519
