### ISSUE TITLE
Vue compilerOptions isCustomElement for <search></search>

### ISSUE THREAD

**Issue by felix-berlin** [withastro/astro#9549]
### Astro Info

```block
Astro                    v4.0.8
Node                     v20.9.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/vue
                         @astrojs/sitemap
                         astro-matomo
                         @vite-pwa/astro-integration
                         @sentry/astro
                         @spotlightjs/astro
```

### Describe the Bug

Hey, I'm not sure if my problem is a Vue error, I didn't create the config correctly or if it's the Astro Vue integration.

In my project, I'm using the HTML `<search></search>` [Element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search) which generating the following warning:

![image](https://github.com/withastro/astro/assets/17964384/59ff4e8a-c9bc-4f9f-aa77-f71ac7af38b5)

Accordingly, to this, I updated my Vue compiler settings:
 
```mjs
    vue({
      appEntrypoint: "/src/pages/_app",
      template: {
        compilerOptions: {
          isCustomElement: (tag) => tag === "search",
        },
      },
    }),
```

As I understand it, Vue should now know that search is a "custom element" (it's just a normal HTML tag).

### What's the expected result?

Vue should use the compiler options, so there should no longer be a warning.

### Link to Minimal Reproducible Example

https://github.com/felix-berlin/berliner-schnauze/tree/improvement/new-light-dark-mode

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
You shouldn't have to define this config since it's a regular html element. On phone rn so I can't try the repro

**Comment by lilnasy** [comment]
This seems like a vue bug. It shouldn't be trying to give <search> any special treatment to begin with. Feel free to re-open if you think that is not the case.

**Comment by felix-berlin** [comment]
@lilnasy you're right it's an Vue bug. See → https://github.com/vuejs/core/issues/9247
