### ISSUE TITLE
React island string props encoding issue

### ISSUE THREAD

**Issue by Vyacheslav1557** [withastro/astro#9552]
### Astro Info

```block
Astro                    v3.5.4
Node                     v21.1.0
System                   Windows (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

Any

### Describe the Bug

I have some pdf filenames as an array (some of them contain russian symbols). But when I pass an array as props to the react client component an expected array becomes so
![image](https://github.com/withastro/astro/assets/118120073/49ea7600-2fbb-4806-94b9-a8dce81754e6)

### What's the expected result?

![image](https://github.com/withastro/astro/assets/118120073/3cff2979-27d7-4fe0-948e-a58479190f17)

index.astro
```js
---
import MyDocument from "../../components/pdf-viewer/pdfViewer.jsx";

const files = await Astro.glob("/src/assets/pdf/*.pdf");

---
<main>
  <MyDocument files={files} client:only="react" />
</main>
```

pdfViewer.jsx
```jsx
const MyDocument = ({ files }) => {
  console.log(files)
return (<></>
)
}
```

### Link to Minimal Reproducible Example

https://github.com/Vyacheslav1557/astro-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
I see the text rendering as expected.

<img width="354" alt="image" src="https://github.com/withastro/astro/assets/69170106/a8d51ef2-31e5-4282-839b-11bd7c93ed45">

Could there be something else in your page or browser causing this?
