### ISSUE TITLE
GSAP registerPlugin breaking import

### ISSUE THREAD

**Issue by ThatXliner** [withastro/astro#9553]
### Astro Info

StackBlitz:
```block
Astro                    v4.0.8
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

Repro on my machine:
```
Astro                    v4.0.8
Node                     v21.3.0
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
                         @astrojs/tailwind
```
### If this issue only occurs in one browser, which browser is a problem?

Likely all browser, as this is a build problem

### Describe the Bug

I cannot run [`gsap.registerPlugin`](https://gsap.com/docs/v3/Installation#install-helper) to notify GSAP of a new plugin. If I uncomment the line running `gsap.registerPlugin`, I get

```
SyntaxError: Cannot use import statement outside a module
  Stack trace:
    at internalCompileFunction (node:internal/vm:77:18)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at cjsLoader (node:internal/modules/esm/translators:356:17)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)

```

### What's the expected result?

the `registerPlugin` function call works without any errors.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yprlj1?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ThatXliner** [comment]
I looked at other issues:

 - https://github.com/withastro/astro/issues/1852 (original issue appears to have been fixed
 - https://github.com/withastro/astro/issues/7758 (issue closed without repro)
 - https://github.com/withastro/astro/issues/5530 (closed as it was not an issue with astro)

**Comment by ThatXliner** [comment]
Interesting, this works in Astro components in a `script type="module"` block

```js
import { gsap } from "gsap";
import { TextPlugin } from "gsap/TextPlugin";
gsap.registerPlugin(TextPlugin);
```

But if I put this in a top-level `script` tag in a Svelte component loaded via `client:load` it fails:

```js
import { TextPlugin } from "gsap/TextPlugin";
```

**Comment by ThatXliner** [comment]
it appears that this issue isn't specific to Astro

**Comment by leolorenzoluis** [comment]
@ThatXliner what was the issue?

**Comment by ThatXliner** [comment]
> @ThatXliner what was the issue?

Importing GSAP plugins (for `.registerPlugin`) breaks when I try to import the package in a top level, but it won’t break when you dynamically import it in, say `onMount`.

For example, in Svelte, this would break:

```svelte
<script>

import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);
</script>
```

but this works:

```svelte
<script>

import { gsap } from "gsap";
import { onMount } from "svelte";
onMount(async () => {

const { ScrollTrigger } = await import("gsap/ScrollTrigger");

gsap.registerPlugin(ScrollTrigger);
})
</script>
```

**Comment by lameuler** [comment]
if anyone finds this and still has the issue, one way I've found to fix it is by changing the vite config. I believe this tells vite to also bundle gsap for ssr so that gsap can also run on commonjs.

```js
// in astro.config.mjs
... ,
vite: {
    ssr: {
        noExternal: [
            'gsap'
        ]
    }
}
```

https://gsap.com/community/forums/topic/29801-getting-error-cannot-use-import-statement-outside-a-module-when-importing-flip/#comment-189587

https://vitejs.dev/config/ssr-options#ssr-noexternal
