### ISSUE TITLE
No matching export for import

### ISSUE THREAD

**Issue by NewfrontBE** [withastro/astro#9555]
### Astro Info

```block
Astro info is not running.
```

### Describe the Bug

No matching export in "html:C:/Users/nick/Documents/astro/lividum/src/components/Header.astro" for import "menuItems"

I have a js file that contains navigation items. It looks like this:
```
const menuItems = [
    {'name': 'Home', 'link': '/'},
    {'name': 'Programs', 'link': '/programs'}
    ]

export default menuItems
```

I then import this file in the Header and in the Footer. It works in the Footer, but not in the Header.
I import like this:
`import menuItems from '../lib/js/menuItems';`

I also use a map function to iterate over the values, like this:
`{menuItems.map((menuItem) => <li><a href={menuItem.link} target={menuItem.target}>{menuItem.name}</a></li>)}`

This all works flawlessly in the Footer component, but I get following error in the Header component:
**No matching export in "/src/components/Header.astro" for import "menuItems"**

Weird thing is, yesterday it worked. Today when using npm run dev, it does not.
It does let me preview and run a build (but the menu items are only displaying on the footer, not header).

Any help would be highly appreciated.

### What's the expected result?

It expect the Header component to work just like the footer component.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9f9nwe

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
I could not reproduce it. The menu items appear on the header same as the footer, in both dev and build. Is there something else about your setup that could be involved?
<img width="789" alt="image" src="https://github.com/withastro/astro/assets/69170106/4dae29f0-3fdc-4df8-9393-cd0e676dc825">

**Comment by NewfrontBE** [comment]
I'm not sure why, but a TSX file was generated that used the import as well. I removed the tsx file from the components and all works again. Probably my mistake, my apologies!
