### ISSUE TITLE
custom status code does not seem to be respected in configured redirects

### ISSUE THREAD

**Issue by JulioGrajales** [withastro/astro#9568]
### Astro Info

```block
Astro                    v4.0.8
Node                     v21.5.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

[Configured redirects](https://docs.astro.build/en/core-concepts/routing/#configured-redirects) don't seem to respect a custom status code when provided using an object. using the following configuration: 
```js
redirects: {
    '/hello': {
      status: 302,
      destination: '/other',
    },
  },
```

does not use 302 status code and instead uses 301 status code (the default). I'm in SSR mode, using node adapter.
![redirect-astro](https://github.com/withastro/astro/assets/29667371/bd3bb64b-bddc-4fee-aaf4-90a8225c5f79)

### What's the expected result?

It should redirect me using 302 status code or any other valid custom status code provided in the configured redirect object.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9cfd3y?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
An interesting to check would be to see if it's node specific or if it also happens with other adapters like vercel

**Comment by ematipico** [comment]
> An interesting thing to check would be to see if it's node specific or if it also happens with other adapters like vercel

I can replicate it in dev using the stackblitz example, so it's probably an issue in core

**Comment by Runeloon** [comment]
Appears this fix doesn't work in the latest 4.2.4 release. Bit difficult to work out why, as the create.ts appears to have gone through a bit of a rework.
Have verified at least that upon hitting redirectRouteStatus, the redirectRoute.redirectRoute property is null, meaning it never bothers checking the redirectRoute.redirect.status, which is set.
Testing example of input to redirectRouteStatus in 4.2.4:
`{ type: 'redirect', isIndex: false, route: '/test1', pattern: /^\/test1\/?$/, segments: [ [ [Object] ] ],       params: [], component: '/test1', generate: [Function (anonymous)], pathname: '/test1', prerender: false, redirect: { status: 302, destination: '/test2' }, redirectRoute: undefined, fallbackRoutes: [] }`

**Comment by ematipico** [comment]
@Runeloon can you provide a reproduction?

**Comment by lilnasy** [comment]
The reproduction provided here behaves as expected now. If there's still a case where it doesn't work, it would be a distinct issue.

**Comment by JulioGrajales** [comment]
I did some tests myself and discovered a strange behavior.

### Astro info:

```
Astro                    v4.2.5
Node                     v21.6.1
System                   Windows (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

there is apparently a difference in behavior depending on whether you add a trailing slash ( / ) to the `destination` property of the configured redirect object or not.

### no trailing slash:

astro.config.mjs:

```js
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  redirects: {
    '/hello': {
      status: 302,
      destination: '/other',
    },
  },
});

```

![no_trailing](https://github.com/withastro/astro/assets/29667371/5b0f8d2b-93ea-482c-94ad-e9f72143c59c)

### trailing slash:


astro.config.mjs:


```js
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  redirects: {
    '/hello': {
      status: 302,
      destination: '/other/',
    },
  },
});

```


![trailing](https://github.com/withastro/astro/assets/29667371/5c40ad05-2e15-424d-b808-796ea4102a87)


Reproduction:
https://stackblitz.com/edit/github-paatym?file=astro.config.mjs
