### ISSUE TITLE
Setting `mode: "production"` in programmatic `build()` doesn’t set `NODE_ENV`

### ISSUE THREAD

**Issue by KonnorRogers** [withastro/astro#9574]
### What version of `starlight` are you using?

0.15.0

### What version of `astro` are you using?

4.0.6

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

Firefox

### Describe the Bug

When using programmatic JS APIs, setting `mode: "production"`, still requires setting: `process.env.NODE_ENV = "production"` to enable pagefind.

Example:

```js
   import { build } from "astro"
   // Pagefind doesn't work
    await build({
      ...config,
      mode: "production"
    })
   
    // Enables pagefind
    process.env.NODE_ENV = "production"
    await build({
      ...config,
      mode: "production"
    })
```

I'm not sure if this is expected behavior, or if its a bug. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-a6bay1?file=README.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Chatted with @bluwy and confirmed we can fix this upstream in the main Astro repo. Thanks again for reporting @KonnorRogers!

**Comment by KonnorRogers** [comment]
❤️ thank you all! Astro rocks 🤘
