### ISSUE TITLE
Custom 404 page not working on Vercel (output mode static)

### ISSUE THREAD

**Issue by devmatteini** [withastro/astro#9578]
### Astro Info

```block
Astro                    v4.0.9
Node                     v18.18.2
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/vercel
Integrations             @astrojs/tailwind
                         astro-icon
                         @astrojs/mdx
```

### Describe the Bug

- Create a custom [404.astro](https://github.com/devmatteini/website/blob/280e7ef1914025fc514a38eef23f4dd51867502b/src/pages/404.astro) page.
- Deploy to Vercel with Astro output mode on `static`
  I use vercel cli:
  ```
  vercel pull --yes --environment production --token "$VERCEL_TOKEN"
  astro build
  vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"
  ```
- Open your website in a non-existing route and the custom 404 page is not shown. The vercel 404 default page is shown instead.
  ![vercel default 404 page](https://github.com/withastro/astro/assets/48568026/ee5f2b9c-6bc3-446d-a9f0-5024159d9644)
 
This is the repository: https://github.com/devmatteini/website
I just ported this repository from Next.js to Astro, so I might have done something wrong somewhere.

Just to give more information, I can see from Vercel deployment `Source` tab that the deployed files and the 404.html exists (`.vercel/output/static/404.html`).

This is the rest of the content:
![vercel deployed source](https://github.com/withastro/astro/assets/48568026/17cd360f-823e-465b-9c6e-d419ae4a6e0c)

Interestingly, if you go to `https://<domain>/404.html` the custom 404 page is rendered correctly.  

### What's the expected result?

The custom defined 404 page should be used instead of Vercel's default one when reaching a non-existing route

### Link to Minimal Reproducible Example

I'm not sure a minimal example with Vercel is doable since it would require a personal Vercel account

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Instead of a repro, you could create a minimal github repo (I didn't have a look but looks like it's already the case) and host the website on vercel until this issue is closed

**Comment by devmatteini** [comment]
Hi! If you consider this [repository](https://github.com/devmatteini/website) minimal, it's already hosted on vercel (https://cosimomatteini.com/).

Otherwise, I can create a new repository with minimal setup.

**Comment by florian-lefebvre** [comment]
Not really minimal imo. Have a look at #9206 to see an example

**Comment by lilnasy** [comment]
Can you try `@astrojs/vercel@experimental--9591`?

**Comment by devmatteini** [comment]
Here it is a minimal repo to reproduce the issue: https://github.com/devmatteini/astro-vercel-404-issue
Website: https://astro-vercel-404-issue.vercel.app/

**Comment by devmatteini** [comment]
> Can you try `@astrojs/vercel@experimental--9591`?

I installed it, but It didn't solve the issue

**Comment by devmatteini** [comment]
@lilnasy Starting from your patch, I changed the `src` value to `/.*` and now it works!

**Comment by lilnasy** [comment]
Forgot I was doing regex 😭 

Thanks for looking into it!

**Comment by devmatteini** [comment]
Thank you @lilnasy for your work!
