### ISSUE TITLE
Cannot use `.tsx` files in static file endpoints

### ISSUE THREAD

**Issue by orf** [withastro/astro#9588]
### Astro Info

```block
Astro                    v4.0.9
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
                         astro-robots-txt
```

### Describe the Bug

The [static file endpoint](https://docs.astro.build/en/core-concepts/endpoints/#static-file-endpoints) docs specify that only `.js` and `.ts` files can be used for creating endpoints, and indeed creating a `.tsx` file results in the route not being loaded.

If I want to use JSX in this route, this means I have to create a separate `.tsx` file and import that from my `.ts` file which is annoying.

If there is no specific technical reason why only `.ts` files are allowed, then we should also allow `.tsx` files.

For reference, I'm using [satori](https://github.com/vercel/satori) which accepts JSX elements.

### What's the expected result?

Adding a `.tsx` file that contains an endpoint should work.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dclnmg?file=src%2Fpages%2Ftest.json.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
This isn't a bug, but it a nice to have, because as you said we don't accept `tsx`/`jsx` by design. I suppose you have some niche use case. You also need to be aware that JSX is compiled, and the compiler depends on the library you used: react, preact, solid, etc.

I suggest you open a discussion in the Roadmap and explain there what are the use cases.

**Comment by activenode** [comment]
Not necessarily niche: est.dev.dailystorytelling.com/

**Comment by activenode** [comment]
Not necessarily niche: https://www.kozhuhds.com/blog/generating-static-open-graph-og-images-in-astro-using-vercel-og/
