### ISSUE TITLE
Vercel speed Anaytics - new version

### ISSUE THREAD

**Issue by ref-thomasledoux1** [withastro/astro#9590]
### Astro Info

```block
Not relevant
```

### Describe the Bug

At the moment in the docs it's recommended to use `speedInsights` through the `vercel` adapter to enable Speed Analytics on Vercel.
But in the newest version of the Speed Analytics, it's recommended by Vercel to use their package to do tracking of speed analytics, not longer matching the current approach which the adapter option provides.
The migration docs can be found here: https://vercel.com/docs/speed-insights/migrating-from-legacy

Now the question is: can the adapter be changed to support the new way of working for Speed Analytics measurement, or should the option be deleted from the adapter, and should the docs point to the Vercel + Astro Speed analytics example here: https://github.com/vercel/speed-insights/blob/main/apps/astro ?

### What's the expected result?

Answer to above :-)

### Link to Minimal Reproducible Example

Not possible

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Hi, thanks for bringing this up. The vercel adapter does not prevent you from using the new API. In fact, users in this thread have already been using it.
- https://github.com/withastro/astro/blob/af59b83/packages/integrations/node/src/nodeMiddleware.ts

The update in the adapter will only deprecate the old system that requires adapter involvement.

**Comment by thomasledoux1** [comment]
> Hi, thanks for bringing this up. The vercel adapter does not prevent you from using the new API. In fact, users in this thread have already been using it.
> 
> - https://github.com/withastro/astro/issues/7573
> 
> 
> 
> The update in the adapter will only deprecate the old system that requires adapter involvement.

Alright, I thought so. Thanks for the reply. I indeed found the thread you mentioned already and implemented it as per the example, works perfectly fine.
