### ISSUE TITLE
Fresh Astro project breaks on Safari 13

### ISSUE THREAD

**Issue by ffxsam** [withastro/astro#9601]
### Astro Info

```block
Astro                    v4.0.9
Node                     v18.17.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Safari 13

### Describe the Bug

Created a fresh Astro project (TypeScript), ran `pnpm dev`, and opened the site with Safari. The following errors show up in the console:

```
[Error] SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.
	promiseReactionJob
[Error] Unhandled Promise Rejection: SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.
	(anonymous function) (entrypoint.js:22)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

### What's the expected result?

I'd expect no errors.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/example-basics-0jll5x

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Vite 5 which Astro uses [doesn't support Safari 13](https://vitejs.dev/guide/build.html#browser-compatibility) in dev, so this seems expected to me. Likely some syntax was used that Safari 13 doesn't understand.

**Comment by ematipico** [comment]
I am going to close because that's expected. There isn't much we can do.

**Comment by ffxsam** [comment]
Ahh, thank you! I couldn't find any minimum browser requirements. These ought to be listed on Astro's website, IMO.

**Comment by ffxsam** [comment]
Seems like adding `build.target: 'es2015'` to the vite config fixes the issue.

**Comment by ematipico** [comment]
> This won't have any negative impact on the Astro app for more modern browsers, will it?

It's possible it will, because "new features" are compiled to "old features" using babel. For example `async/await` isn't supported by Safari, so it's transformed to something else.

**Comment by ffxsam** [comment]
@ematipico Thanks! It makes little sense to potentially break newer features for a portion of our audience (0.8% using Safari 13), so I'll just put up a warning message.
