### ISSUE TITLE
Partytown + VT website giving 404 errors to the google search engine

### ISSUE THREAD

**Issue by suhaylmv** [withastro/astro#9607]
### Astro Info

```block
Astro                    v4.0.8
Node                     v21.2.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
                         @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/partytown
                         @astrojs/markdoc
```

### Describe the Bug

![image](https://github.com/withastro/astro/assets/64747225/b1e1ccec-3ae5-49f0-b336-2ea3d365089e)

Google search console is giving me 404 errors on these "pages", every time my website is crawled (when I submit a new sitemap for example):
![image](https://github.com/withastro/astro/assets/64747225/8628ae93-414a-471b-b3d5-e438319d89d4)

It's been happening since august when I created this website:
![image](https://github.com/withastro/astro/assets/64747225/cff72391-4ff6-4898-ae1b-2cfa95313956)

The website itself is totally functional and nothing weird is happening there. The only problem is that it's giving errors to the Google Search Engine. However apart from it being annoying, as far as I know such errors affect negatively for SEO of a website. So I would like to fix it as soon as possible. 

I have another onepager website which uses astro with partytown but doesn't use VT, and I've never had such an issue, so I'm suspecting this may be causing the issue. But I have no idea and I may be completely wrong.

Also I don't think it's sensible to create a minimal reproducible example. I would need to create an astro website with partytown, GA4 and VT, host it on a new domain, create a google search console property for it, and wait a week for google to crawl it.

### What's the expected result?

Not getting such errors

### Link to Minimal Reproducible Example

no

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Hi, thanks for the report! Unfortunately, the `@astrojs/partytown` does not generate these links, nor serves them. It is served by partytown's service worker instead, so it makes sense why it would be a 404 when google makes a request to the server for it.

You might want to open an issue in [BuilderIO/partytown](https://github.com/BuilderIO/partytown).
