### ISSUE TITLE
Pages in root `src/pages/` directory are not built to output root when using i18n

### ISSUE THREAD

**Issue by sceee** [withastro/astro#9611]
### Astro Info

```block
Astro                    v4.1.0
Node                     v18.18.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
```

### Describe the Bug

When building a page with `i18n` enabled using the following config
```
export default defineConfig({
  i18n: {
    defaultLocale: "de",
    locales: ["de", "en"],
    routing: {
      prefixDefaultLocale: true,
    },
  }
});
```

and the following source page structure
```
- src
  - pages
    - [lang]
      - index.astro
    - index.astro (this has just the meta redirect)
    - 404.astro
```

...I cannot get the 404 page to be built in the root of the build output.

### What's the expected result?

The expected build output file structure is
```
- dist
  - de
    - index.html
  - en
    - index.html
  - 404.html
```

This means that the url `/en/` works (and weirdly also `/en/404`) but `/404` does not work.

So my desire is that pages outside the [lang] directory (=directly in `src/pages/x.astro`) are build to the root of the `dist` output directory but I cannot get this working.

I've read through multiple issues like https://github.com/withastro/astro/issues/9096#issuecomment-1810500451 which seems to be the same/a similar issue but this was closed yet it's still not working for me in the latest version.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yqe4u9?file=src%2Fpages%2F404.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Thanks for the clean reproduction!

I'm noticing two issues here:
- `404.html` never appears on disk even though the logs report it being written.
- `pages/index.astro` needs to exist but will be ignored. If it does not exist, `dist/de` and `dist/en` are not created. If it exists, its result is overwritten with a redirect to `/de`, the default locale (this part seems intended but should maybe warn).

**Comment by sceee** [comment]
@lilnasy thanks for the fast response.
Yeah, the first (logs report it being written but it is not) is also something I noticed.

Just for information, my use case is not only about the _special_ `404.html` but I also want to provide other pages like this:

```
- src
  - pages
    - [lang]
      - about.astro
      - index.astro
      - [dynamic].astro
      - ...
    - about.astro
    - index.astro
    - 404.astro
    - [dynamic2].astro
    - ...
```

Background for this is that I want to have such a structure in the end:
```
- dist
  - index.html
  - about.html <-- in this file I want to do a JS redirect to /detected-user-lang/about/
  - somedynamic.html <-- in this generated dynamic file I also want to do a JS redirect to /detected-user-lang/somedynamic/
  - 404.html
  - en
    - index.html
    - about.html
    - somedynamic.html
    - ...
  - de
    - index.html
    - about.html
    - ...
```

So basically I want to be able to additionally create files for translated files in the root that will detect the browser language via client-side JS and redirect to the respective language subfolder.

But I guess if these issues are fixed for the 404 case it will also work for the other files.

**Comment by ematipico** [comment]
As far as I understand, you want to have both routing strategies simultaneously, which is currently impossible. We are considering more low-level APIs for these cases, but at the moment, you can't achieve this.

**Comment by sceee** [comment]
@ematipico what do you mean with both routing strategies? Mixing file-based routing and dynamic routing?

I thought my use case is very basic, essentially I only want to be able to end up with the following Url paths at the end:
```
/somepage -> has some static content - e.g. JS code to redirect to the language specific page
/en/somepage -> shows the page translated in English
/de/somepage -> shows the page translated in German
```

Is it not possible to achieve such a result with astro at the moment?

**Comment by ematipico** [comment]
> @ematipico what do you mean with both routing strategies? 

What I mean is that:
- when `prefixDefaultLocale` is `false` ALL your pages that **AREN'T** inside a locale folder *are* your default locale
- when `prefixDefaultLocale` is `true` ALL your pages *must* be inside a locale folder. The only exception is the index, because we require it to do a redirect to `/<defaultLocale>`. Pages that aren't inside a locale folder will return a 404.

It seems that you want both, which isn't allowed at the moment.

**Comment by sceee** [comment]
Thanks for the information @ematipico !
Nice to hear that soon there might be an option to achieve that.

**Comment by SalahAdDin** [comment]
We need to implement this way:
```
- src
  - pages
    - [lang]
      - index.astro
```
