### ISSUE TITLE
The generic of the APIRoute type does not specify the second generic type of APIContext.

### ISSUE THREAD

**Issue by ldh3907** [withastro/astro#9612]
### Astro Info

```block
Astro                    v4.1.0
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

While typing through the APIRoute type to create an API based on the pages folder, the params parameter was not typed, so I checked the type and found that the APIRoute type was receiving one less generic.

- The code I was facing the problem with is the screenshot below.
<img width="781" alt="스크린샷 2024-01-05 오전 3 26 53" src="https://github.com/withastro/astro/assets/79711744/296a6c53-b54b-4bd6-a6e2-5c213de88d87">

- Even if you type the parameters separately, the type will be broken.
<img width="1013" alt="스크린샷 2024-01-05 오전 3 25 34" src="https://github.com/withastro/astro/assets/79711744/2608abba-c4ec-4fb4-870c-ba2173da12ef">

- The problem occurred because the APIRoute type only received one generic, and only one of the two generics of the APIContext type was set.
<img width="833" alt="스크린샷 2024-01-05 오전 2 53 17" src="https://github.com/withastro/astro/assets/79711744/c25de945-c37e-410d-bb8f-436da501ef11">

- The second generic of the APIContext type is just typing params 🥲
<img width="1186" alt="스크린샷 2024-01-05 오전 2 55 52" src="https://github.com/withastro/astro/assets/79711744/05ed00d3-8287-4e1c-971a-29296569e7fb">

- So adding a second generic to APIRoute solves the problem. I tried changing astro.d.ts in my personal project and it worked well. Would it be okay if I contributed by uploading a PR related to this?

### What's the expected result?

- explained above

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-eyozpb?file=src%2Fpages%2Fapi%2Fblog%2Fviews%2F%5Bslug%5D.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Thanks for looking into it! Seems like a reasonable follow-up to adding the first generic to `APIRoute`.
- https://github.com/withastro/astro/pull/7521

**Comment by ldh3907** [comment]
@lilnasy Thanks for checking out! Could I possibly upload a PR related to this?
