### ISSUE TITLE
Vercel analytics not working

### ISSUE THREAD

**Issue by RobbieTheWagner** [withastro/astro#9623]
### Astro Info

```block
Astro                    v4.0.9
Node                     v20.6.1
System                   macOS (x64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/vercel
Integrations             @astrojs/tailwind
                         @astrojs/starlight
```

### Describe the Bug

The Vercel analytics integration seems to not work. I have enabled it as the docs said, but the analytics tab on Vercel is getting no data. The code for the site can be found at https://github.com/shipshapecode/swach-website-astro and the site can be visited at swach.io.

This is our Astro config:

```js
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import vercelStatic from '@astrojs/vercel/static';

import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  output: 'static',
  adapter: vercelStatic({
    imageService: true,
    speedInsights: {
      enabled: true,
    },
    webAnalytics: {
      enabled: true,
    },
  }),
  site: 'https://swach.io/',
  integrations: [
    tailwind(),
    starlight({
      title: 'Swach Documentation',
      logo: {
        dark: './src/assets/svgs/swach-logo-line.svg',
        light: './src/assets/svgs/swach-dock-icon.svg',
      },
    }),
  ],
});

```

### What's the expected result?

Analytics should work and log visits to the site.

### Link to Minimal Reproducible Example

https://github.com/shipshapecode/swach-website-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
It seems to work fine.

![image](https://github.com/withastro/astro/assets/69170106/75a5adde-5daa-4ccf-bfe8-b30022c60911)

Could the analytics request have failed because you had adblock enabled in your browser?

**Comment by RobbieTheWagner** [comment]
@lilnasy ah, it is possible that ad blocking was the issue. Sorry for the noise!
