### ISSUE TITLE
[Astro 4] - Dev Overlay asset gets failed to serve: "The request url "...node_modules/astro/dist/runtime/client/dev-overlay/entrypoint.js" is outside of Vite serving allow list." if different folder structure OR on Monorepo

### ISSUE THREAD

**Issue by arvilmena** [withastro/astro#9628]
### Astro Info

```block
Astro                    v4.1.1
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             project-name-vite-config
```

### Describe the Bug

1. On setup where Astro's source files are not in the root folder (not a sibling of node_modules nor astro.config.ts), for example monorepo, Vite complains: 
```
08:08:49 [ERROR] [vite] The request url "/Users/arvil/Repos/astro-fails-to-serve-dev-overlay/node_modules/.pnpm/astro@4.1.1_@types+node@18.16.9_typescript@5.2.2/node_modules/astro/dist/runtime/client/dev-overlay/entrypoint.js" is outside of Vite serving allow list.
08:08:49 [WARN] [vite] 
- /Users/arvil/Repos/astro-fails-to-serve-dev-overlay/apps/frontend-astro
- /Users/arvil/Repos/astro-fails-to-serve-dev-overlay/node_modules/.pnpm/vite@5.0.11_@types+node@18.16.9/node_modules/vite/dist/client
Refer to docs https://vitejs.dev/config/server-options.html#server-fs-allow for configurations and more details.
```

2. Trying to override the config's server.fs.strict and setting it to false does not seem to work at all.
@see https://github.com/withastro/astro/issues/2776
Even [tried to override it via creating custom Integration](https://github.com/arvilmena/issue--astro-monorepo-nx/blob/e3035c96eb67e93e1b5279b937eaff95cd3fb083/astro.config.ts#L8-L26), but learned later that we are whitelisting overridable config props.

### What's the expected result?

Either:

1. Allow dev-overlay assets to get served, or any other assets to get served without any issue on monorepos or different folder structure.

2. Allow overriding of Vite's server.fs config. I just really want to allow setting `vite.server.fs.strict = false` in my development/local

Note: on the Repro Git Repo I linked, to run the `dev` the command is:
```pnpm exec nx run frontend-astro:dev```

### Link to Minimal Reproducible Example

https://github.com/arvilmena/issue--astro-monorepo-nx/tree/issue/astro-fails-to-serve-dev-overlay-on-monorepo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Setting `vite.server.fs.strict` to `false` should work, I do it all the time when I'm working on the overlay.

```ts
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  vite: {
    server: {
      fs: {
        strict: false
      }
    }
  }
});
```

**Comment by arvilmena** [comment]
@Princesseuh thank you for confirming that vite.server.fs.strict config override works because of that I spent some more time

So after more 👀 the solution is changing the working directory of the script to the same folder of the root directory:

```
"scripts": {
    "dev": "pnpm -C \"./../../\" exec astro dev",
  }
```
