### ISSUE TITLE
`Astro.slots.has("default")` `true` when default `<slot>` empty

### ISSUE THREAD

**Issue by srsgores** [withastro/astro#9654]
### Astro Info

```block
Astro                    v4.0.8
Node                     v21.5.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @sanity/astro
                         @astrojs/react
                         @astrojs/sitemap
                         astro-robots-txt
```

### Describe the Bug

When the `default` `<slot>` has **no content** in it, `Astro.slots.has("default")` still remains `true`.

Example:

`Card.astro`
```jsx
---
const hasContent = Astro.slots.has("default");
---

<div class="card">
  {hasContent && <div class="card-content"><slot/></div>}
</div>
```

`Post.astro`
```jsx
---
import Card from "./Card.astro";
const hasContent = Astro.slots.has("default");
---

<article class="post">
  <Card>
    {hasContent && <div class="post-content"><slot/></div>}
  </Card>
</article>
```

`pages/index.astro`
```jsx
---
import Post from "../components/Page.astro";
---

<Post/> <!-- empty -->
```

### What's the expected result?

`.post-content` should not exist.

**Comment by natemoo-re** [comment]
This is a long-standing design limitation of `Astro.slots`. See previous discussion: https://github.com/withastro/astro/issues/3884. There's a potential workaround mentioned here https://github.com/withastro/astro/issues/3884#issuecomment-1551035234

**Comment by matthewp** [comment]
Thanks for explaining @natemoo-re! I'm going to close as this is working as designed, even though it's not what people always want. We are aware of the desire and might create a new API to accommodate the need in the future, but that would go through the roadmap process.

**Comment by robclancy** [comment]
"Thanks for explaining @natemoo-re! I'm going to close as this is working as designed"

Well you always get into a project long enough to finally see the cracks in it like when moving from something else. Working as designed lmao... well the design is fucking stupid and the docs are wrong.
