### ISSUE TITLE
I want to control SSG mode, 404 under dynamic path

### ISSUE THREAD

**Issue by 516310460** [withastro/astro#9655]
### Astro Info

```block
In setting up SSG mode, access: http://localhost:4321/sequences/asdasd .

There is no sequence/asdasd set in getStaticPaths, resulting in 404.

But I hope there is a configuration that allows me to directly use sequences/index instead of 404.
```

### Describe the Bug

There is no sequence/asdasd set in getStaticPaths, resulting in 404.

### What's the expected result?

But I hope there is a configuration that allows me to directly use sequences/index instead of 404.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-izjptd?file=src%2Fpages%2F404.astro,src%2Fpages%2Fsequences%2F[...path].astro,src%2Fpages%2Findex.astro,src%2Fpages%2Fsequences%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by 516310460** [comment]
@florian-lefebvre https://stackblitz.com/edit/github-izjptd?file=src%2Fpages%2F404.astro,src%2Fpages%2Fsequences%2F[...path].astro,src%2Fpages%2Findex.astro,src%2Fpages%2Fsequences%2Findex.astro

**Comment by ematipico** [comment]
Hi @516310460 

Can you explain the issue? I don't understand what's the issue. Astro prints a warning in a console: 

```
13:20:48 [WARN] [router] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/sequences/aaa`.

Possible dynamic routes being matched: src/pages/sequences/[...path].astro.
```

**Comment by 516310460** [comment]
> Hi @516310460
> 
> Can you explain the issue? I need help understanding what's the issue. Astro prints a warning in a console:
> 
> ```
> 13:20:48 [WARN] [router] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/sequences/aaa`.
> 
> Possible dynamic routes being matched: src/pages/sequences/[...path].astro.
> ```

Can I control it myself Instead of using 404.astro by default, I would like to use index.astro

**Comment by 516310460** [comment]
I want to independently control the route and status code where the 404 file is located

**Comment by lilnasy** [comment]
In static mode, astro only generates html css and js files. All routing behavior is controlled by the static server (nginx, apache, traeffik, netlify, github pages). You might find something in their docs about serving `/sequences/index.html` for `/sequences/asdasd`.

Feel free to reopen if you think I misunderstood.
