### ISSUE TITLE
Flickering when redirecting on astro website deployed to GitHub Pages

### ISSUE THREAD

**Issue by gregorobreza** [withastro/astro#9662]
### Astro Info

```block
Astro                    v4.1.2
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When configured redirection in `astro.config.mjs` there is a short flickering noticed on live website deployed to GitHub Pages. It works perfectly fine locally. 

### What's the expected result?

Redirections should happen seamlessly same as when developing locally. 

### Link to Minimal Reproducible Example

Deployed page:
https://gregorobreza.github.io/astro-redirect-issue/

GitHub repo:
https://github.com/gregorobreza/astro-redirect-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by gregorobreza** [comment]
Sure updated issue description with [GithHub repo](https://github.com/gregorobreza/astro-redirect-issue)

**Comment by Princesseuh** [comment]
I'd be happy to be proved wrong, but I don't think there's really a way to fix this, on GitHub Pages the only way to do a redirect is through a `meta` tag, which is what we use. 

We could maybe allow a custom templates for redirect pages so that people can customize it at least

**Comment by ematipico** [comment]
Yes, that's how redirects via HTML files work. That's the expected behaviour. Closing.

**Comment by ematipico** [comment]
> We could maybe allow a custom templates for redirect pages so that people can customize it at least

Sounds like good material  for an improvement :)
