### ISSUE TITLE
Web component links do not trigger view transitions

### ISSUE THREAD

**Issue by reecemcd** [withastro/astro#9670]
### Astro Info

```block
Astro                    v4.1.2
Node                     v18.16.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             auto-import
                         @astrojs/lit
                         @astrojs/mdx
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

Any

### Describe the Bug

Because Astro View Transitions only listen for navigation events on `a` tags, they flat out do not work with web components that either act like a link/contain internal `a` tags.

Example:

Say we have a custom button web component that renders an internal `a` tag when an `href` prop is passed.

```html
<my-custom-button href="/some/link"></my-custom-button>
```

This element will never trigger a navigation event in Astro with view transitions. When clicked it will always trigger a full load of the new page.

---

I included a stackblitz that showcases this behavior. It also showcases that when a view-transition does occur via a normal `a` tag element, the web components don't seem to hydrate properly (and thus are not visible)? I'm not sure what is going on there, but it could be a separate issue.

### What's the expected result?

Perhaps we should be able to specify a custom selector that is used to locate elements from which click events should be treated like navigation events. The assumption would be they must have an `href` attribute like `a` tags do. 

Something like this in the config would work wonderfully:
```typescript
export default defineConfig({
  // ...
  viewTransitions: {
    linkSelector: 'a, [href]'
  }
});
```

Really this same issue prevents page prefetching from working for the same reasons, so if there was a more generic setting for this beyond just view transitions that would be even better.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-cwuduu?file=src%2Fpages%2Findex.astro&title=Astro%20Starter%20Kit:%20Blog

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Web components will trigger view transitions, but there has to be an indication that there is an `<a>` tag causing it. In your case, the`<a>` is within the shadow DOM, which naturally does not like to share things.

**Comment by reecemcd** [comment]
Right, but there are many cases where we need web components that act like links by including `<a>` links within their shadowDOM.

Examples:
- https://shoelace.style/components/button#link-buttons
- https://opensource.adobe.com/spectrum-web-components/components/button/
- https://opensource.adobe.com/spectrum-web-components/components/link/
- https://nordhealth.design/components/button/

Our design system is internal but these are all nearly identical use cases. I could keep going here with examples if we need to.

My assumption here is that astro is looking for `<a>` elements on the page and listening for click events on them to handle navigation. My ask is that to enable this same behavior with custom web component "links" we be able to specify a selector to tell astro that any element with an `[href]` attribute also be treated like a link it should listen for clicks to.
