### ISSUE TITLE
ViewTransition doesn't respect form method="post" when the action of form targets external URL.

### ISSUE THREAD

**Issue by kidylee** [withastro/astro#9676]
### Astro Info

```block
Astro                    v4.0.4
Node                     v19.7.0
System                   macOS (arm64)
Package Manager          unknown
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
                         astro-robots-txt
                         @astrojs/react
```

### Describe the Bug

# Background

I have a form on my blog which will be submitted to a cross domain URL. 

# Issue

When using ViewTransition and the ``<form method="post">`` is working fine, but when the action is targeting external URL
``<form action="https://example.com" method="post">``, the method of request will be change from `post` to `get` and the body payload lost simultaneously, due to get doesn't support payload.

The issue can be fixed by adding `data-astro-reload` attribute to the form like this: ``<form action="https://example.com" data-astro-reload>``

### What's the expected result?

I expected ViewTransition do not change form method from ``POST`` to ``GET`` by default.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-vlaect?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @kidylee thank you for submitting this issue! 

This issue can be fixed by leaving the submit handler in ViewTransitions.astro before calling preventDefault() and navigate(), if the action is cross origin.

Do you want to open a PR for this change including a new e2e test case?

**Comment by kidylee** [comment]
> Hi @kidylee thank you for submitting this issue!
> 
> This issue can be fixed by leaving the submit handler in ViewTransitions.astro before calling preventDefault() and navigate(), if the action is cross origin.
> 
> Do you want to open a PR for this change including a new e2e test case?

Thanks @martrapp, sure, I would like to do it. 

One more question: how do we detect cross origin? There are two options in my mind: comparing `action url` to the `astro.config.site`, and comparing action url to the `window.location.href`.

I prefer `window.location.href` because it is more accurate and the `site` some times is unavailable since it is optional in the config.

**Comment by martrapp** [comment]
Great! Yes, indeed, that should definitely be `window.location.origin`. We are missing this test for forms, but we have it for links:  https://github.com/withastro/astro/blob/c7dbb9d5c08c77fa8b964a972f23c6bf10118956/packages/astro/components/ViewTransitions.astro#L79

**Comment by martrapp** [comment]
@kidylee, if you would like to discuss the required e2e test, please contact me on Discord
