### ISSUE TITLE
i18n Feature Not Building Default Locale's index.html with astro build Command

### ISSUE THREAD

**Issue by mfk-smart** [withastro/astro#9677]
### Astro Info

```block
Astro                    v4.1.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

All browsers

### Describe the Bug

When utilizing the internationalization (i18n) feature in Astro, running the astro build command does not generate all the expected files and folders. More specifically, the command fails to build the index.html file within the directory corresponding to the default locale as specified in the Astro configuration. This issue seems to occur only for the default locale, as other locales' directories and files are generated as expected.

### What's the expected result?

When running the astro build command with the i18n feature enabled, the build process should generate the index.html file for every locale, including the default locale specified in the Astro configuration. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-17tuzs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Oh, I see the issue. This is a technical restriction we have in Astro. You **must** an `src/pages/index. Astro` in your file system to make it work. 

It's odd, I know, but we require `src/pages/index.astro` to generate a redirect from the home page to the home of the default locale.

**Comment by ematipico** [comment]
I'll make sure to add a warning/message in the upcoming release to tell that to the developers.

**Comment by LaundroMat** [comment]
Is there a way to suppress the redirect message?
