### ISSUE TITLE
Vite `server.origin` option does not affect script paths in development

### ISSUE THREAD

**Issue by michaelhthomas** [withastro/astro#9679]
### Astro Info

```block
Astro                    v4.0.9
Node                     v18.19.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/vue
                         astro-global
```

### Describe the Bug

Setting the vite `server.origin` option gives images and other assets an absolute url in development, but not scripts. Looking at the HTML in the reproduction linked below, the paths to Astro's HMR scripts and others simply begin with a `/`, while the image link is properly prefixed with `https://example.com/`.

### What's the expected result?

The `server.origin` option results in all asset urls being prefixed with the provided origin. The use case for this option is similar to Vite's "backend integration" seciton, I would like to be able to proxy the HTML served by the development server while still having all scripts and assets served by the development server directly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-42qtqu

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by smnbbrv** [comment]
This actually breaks any setup with vite behind proxy. E.g. this config

```
const port = 1234;

export default defineConfig({
  output: "server",
  base: "/ui/",
  server: {
    host: '0.0.0.0',
    port,
  },
  adapter: node({
    mode: "standalone"
  }),
  integrations: [tailwind(), react()],
  devToolbar: {
    enabled: false,
  },
  vite: {
    server: {
      strictPort: true,
      origin: `http://localhost:${port}`,
    },
  }
});
```

is supposed to server everything from /ui/, unless it is a static asset. For the assets it is possible to add `origin` config, however it does not work for all scripts.

<img width="470" alt="image" src="https://github.com/withastro/astro/assets/13453858/508ecc8e-dc14-4138-ba1f-2b18ea6c92b8">

**Comment by matthewp** [comment]
The provided example does not include a script. Can you provide one?

**Comment by michaelhthomas** [comment]
Updated the repro to explicitly import a script import, which works even though it should not.

**Comment by michaelhthomas** [comment]
@matthewp Reproduction has been updated, let me know if there's anything else I can do to help with this.

**Comment by dave1010** [comment]
This workaround worked for me. Setup was `vite.config.ts` in the root for the main project, with Astro in `./docs`. 

Vite's built in proxy handles `/docs`, then if Astro tries to load resources from `/`, Vite then proxies them back to Astro.

A bit complicated but it works perfectly.

```
export default defineConfig({
  plugins: [
    preact(),
    
    // Custom plugin to proxy asset requests from the Astro docs to the Astro dev server
    {
      name: 'proxy-astro-docs-assets',
      configureServer(server) {
        server.middlewares.use((req, res, next) => {
          const referer = req.headers.referer || '';
          
          // If the request was triggered by a page under /docs, 
          // and it's not trying to hit /docs directly...
          if (
            referer.includes('/docs') && 
            req.url &&
            !req.url.startsWith('/docs')
          ) {
            // Redirect it to the Astro dev server
            res.writeHead(302, { Location: `http://localhost:4321${req.url}` });
            res.end();
            return;
          }
          next();
        });
      }
    }
  ],
	server: {
		proxy: {
      '/docs': 'http://localhost:4321', // Proxy /docs to Astro dev server (run with npm run dev:docs)
		},
	},
});
```
