### ISSUE TITLE
`--host` on npm doesn't expose development server

### ISSUE THREAD

**Issue by gene-fls** [withastro/astro#9686]
### Astro Info

```block
Astro                    v4.1.2
Node                     v21.5.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

When I run `npm run dev -- --host` (or `npm run dev --host`), the development server is not exposed.

```
PS C:\Users\XXXXX\Desktop\XXXXX> npm run dev -- --host

> XXXXX@0.0.1 dev
> astro dev


 astro  v4.1.2 ready in 662 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose
```

### What's the expected result?

I expect it to expose the development server to my network and output the IPs that it's on. 

### Link to Minimal Reproducible Example

Not applicable. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mandar1jn** [comment]
Discussion around this issue can be found [on discord](https://discord.com/channels/830184174198718474/1195086722971746455/1195086722971746455). Issue verified by Dreyfus

**Comment by TheElegantCoding** [comment]
same here preview and server options are not working

```js
import sitemap from '@astrojs/sitemap';
import { defineConfig } from 'astro/config';
import { loadEnv } from 'vite';

const environment = loadEnv(process.env.NODE_ENV ?? 'development', './src/global/env', '');

export default defineConfig({
  build:
  {
    assetsPrefix: process.env.NODE_ENV === 'production' ? environment.BASE_URL : undefined,
    inlineStylesheets: 'never'
  },
  integrations: [ sitemap() ],
  site: environment.BASE_URL,
  vite:
  {
    envDir: './src/global/env',
    preview:
    {
      host: true,
      open: true
    },
    server:
    {
      host: true,
      open: true
    }
  }
});
```

Here is the repo for reproduction [Astro template](import sitemap from '@astrojs/sitemap';
import { defineConfig } from 'astro/config';
import { loadEnv } from 'vite';

const environment = loadEnv(process.env.NODE_ENV ?? 'development', './src/global/env', '');

export default defineConfig({
  build:
  {
    assetsPrefix: process.env.NODE_ENV === 'production' ? environment.BASE_URL : undefined,
    inlineStylesheets: 'never'
  },
  integrations: [ sitemap() ],
  site: environment.BASE_URL,
  vite:
  {
    envDir: './src/global/env',
    preview:
    {
      host: true,
      open: true
    },
    server:
    {
      host: true,
      open: true
    }
  }
});)

**Comment by ruohki** [comment]
```
> strong-star@0.0.1 astro
> astro info

Astro                    v4.1.2
Node                     v18.16.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
```

```
> strong-star@0.0.1 astro
> astro dev --host


 astro  v4.1.2 ready in 427 ms

┃ Local    http://localhost:4321/
┃ Network  http://172.17.112.1:4321/
           http://192.168.45.1:4321/
           http://192.168.249.1:4321/
           http://10.25.94.237:4321/
```

Running node 18 here — since it's windows, maybe a UAC issue?

**Comment by ematipico** [comment]
I can't replicate the issue, although the script works when using `npm run dev -- --host`. Using `npm run dev --host` won't work.

**Comment by TheElegantCoding** [comment]
@ematipico and using the astro config file works for you ?

**Comment by ematipico** [comment]
> @ematipico and using the astro config file works for you ?

If you mean `vite.server.host`, no, it doesn't. Although I think should be a separate issue.

**Comment by luckman212** [comment]
Thanks.

`npm run dev -- --host` did the trick for me 🚀

**Comment by ruohki** [comment]
> Thanks.
> 
> `npm run dev -- --host` did the trick for me 🚀

Yeah if you miss the first `--` you are passing the `--host` to npm rather than the astro command that is behind `run dev`

**Comment by BryanHogan** [comment]
Also running into this issue. `npm run dev -- --host` to expose it does not work anymore.

**Comment by VeryKumar** [comment]
> Thanks.
> 
> `npm run dev -- --host` did the trick for me 🚀

Thats both amazing,


and amazingly frustrating haha
