### ISSUE TITLE
Glob search

### ISSUE THREAD

**Issue by Its-Just-Nans** [withastro/astro#9689]
### Astro Info

```block
Astro                    v3.3.2
Node                     v20.2.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
```

### Describe the Bug

```ts
const imgs = await Astro.glob("/**/*.(jpg|png|gif|jpeg|webp|svg)");
```

returns only

```ts
// array of module like this
{
  default: {
    format: 'jpg',
    height: 1440,
    src: '/@fs/tmp/tmp.Ynu6ndRAHU/...../escape.jpg?origWidth=1080&origHeight=1440&origFormat=jpg',
    width: 1080,
    [[Prototype]]: Object,
    __esModule: true,
  }
  Symbol(Symbol.toStringTag): 'Module'
  __esModule: true
  [[Prototype]]:Object
}
```

```ts
const imgs = await Astro.glob("/**/*.mdx");
```

returns only

```ts
// array of module like this
{
  __usesAstroImage: ƒ get(){ return __usesAstroImage },
  Content: ƒ get(){ return Content },
  default: ({})=>MDXContent,
  file: ƒ get(){ return file },
  frontmatter: ƒ get(){ return frontmatter },
  getHeadings: ƒ get(){ return getHeadings },
  Symbol(Symbol.toStringTag): 'Module',
  url: ƒ get(){ return url },
}
```

When it's non (md|mdx) files glob doesn't return `url` and `file` params which can be very useful, why ?

### What's the expected result?

To see the `url` and `file` options on non md|mdx files during dev dans build

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Its-Just-Nans** [comment]
For markdown files, url and file are added here : https://github.com/withastro/astro/blob/c7dbb9d5c08c77fa8b964a972f23c6bf10118956/packages/astro/src/vite-plugin-markdown/index.ts#L76

For assets, it's here https://github.com/withastro/astro/blob/main/packages/astro/src/assets/utils/emitAsset.ts

**Comment by Its-Just-Nans** [comment]
https://github.com/withastro/astro/pull/9691 fix the issue by adding a the `url` and `file`

https://github.com/withastro/astro/pull/9690 fix the issue by adding a filePathAttribute to add glob import

**Comment by bluwy** [comment]
The `url` and `file` do not need to belong to the exports. If you want that in a reliable way that works with all kinds of files, you should use `import.meta.glob` instead. The keys are the urls you can use.

**Comment by Its-Just-Nans** [comment]
The goal of this issue was to add the `url` and `file` attibute because they can be very very useful
