### ISSUE TITLE
& encoding with server rendered strings affects head URLs with multiple params

### ISSUE THREAD

**Issue by alexnguyennz** [withastro/astro#9695]
### Astro Info

```block
Astro                    v4.1.2
Node                     v20.9.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
```

### Describe the Bug

Seems intentional but when strings with `&` are used in a meta head tag, they're encoded as `&#38;` during development and build which affects URLs with a query string with multiple search params e.g. an `og:image` link pointing to an API that dynamically generates the image with a title and description.

```html
<meta  
  name="og:image"  
  content={'https://example.com/api/og?title=hello&description=somedescription'}  
/>

<!-- <meta name="og:image" content="https://example.com/api/og?title=hello&#38;description=somedescription"> --> 
<!-- title=hello -->
```

For the Stackblitz example, when built, it is transformed into `&#38;` .

### What's the expected result?

Not escaped in this case?

```html
<meta  
  name="og:image"  
  content={'https://example.com/api/og?title=hello&description=somedescription'}  
/>

<!-- <meta name="og:image" content="https://example.com/api/og?title=hello&description=somedescription"> --> 
<!-- title=hello description=somedescription -->
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2f3s26?file=src%2Flayouts%2FLayout.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
I can confirm this, I had the issue in a project of mine and added `// TODO: fix in Astro` (but never even reported 😂)

**Comment by alexnguyennz** [comment]
Thanks Florian, should I make a PR?

**Comment by alexnguyennz** [comment]
I've made it here: https://github.com/withastro/astro/pull/9820
