### ISSUE TITLE
Astro Deno deploy adpater support 

### ISSUE THREAD

**Issue by bis0072** [withastro/astro#9699]
### Astro Info

```block
Astro                    v4.1.2
Node                     v20.10.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
                         astro-icon
```

### Describe the Bug

uanble to install @astrojs/deno as it does not support astro v4.1.2

$ npx astro add deno
✔ Resolving packages...
15:02:29 
  Astro will run the following command:
  If you skip this step, you can always run it yourself later

 ╭───────────────────────────────────╮
 │ npm install @astrojs/deno@^5.0.1  │
 ╰───────────────────────────────────╯

√ Continue? ... yes
✖ Installing dependencies...

 Command failed with exit code 1: npm install @astrojs/deno@^5.0.1
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: astro-admin@0.0.1
npm ERR! Found: astro@4.1.2
npm ERR! node_modules/astro
npm ERR!   astro@"^4.1.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer astro@"^3.1.4" from @astrojs/deno@5.0.1
npm ERR! node_modules/@astrojs/deno
npm ERR!   @astrojs/deno@"^5.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\Latu\AppData\Local\npm-cache\_logs\2024-01-15T09_32_32_978Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\Latu\AppData\Local\npm-cache\_logs\2024-01-15T09_32_32_978Z-debug-0.log

Astro could not update your astro.config.js file safely.
Reason: Unable to install dependencies

You will need to add these integration(s) manually.
Documentation: https://docs.astro.build/en/guides/integrations-guide/
  Stack trace:
    at add (file:///D:/1%20Projects/A%20Latu%20Solutions/LATU%20SOLUTIONS/ASTRO%20SITES/astro-admin/node_modules/astro/dist/cli/add/index.js:181:31)
    at async runCommand (file:///D:/1%20Projects/A%20Latu%20Solutions/LATU%20SOLUTIONS/ASTRO%20SITES/astro-admin/node_modules/astro/dist/cli/index.js:107:7)

### What's the expected result?

support for  astro v4

### Link to Minimal Reproducible Example

na

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
This adapter is now managed by the deno team. There's an issue opened about this on their repo https://github.com/denoland/deno-astro-adapter/issues/10
