### ISSUE TITLE
Vite config `base` and `experimental` is all not work

### ISSUE THREAD

**Issue by peng** [withastro/astro#9700]
### Astro Info

```block
Astro                    v4.0.8
Node                     v18.18.1
System                   macOS (arm64)
Package Manager          yarn
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/vue
```

### If this issue only occurs in one browser, which browser is a problem?

build

### Describe the Bug

It possible not a bug.

I want to config two cdn url, js file is https://a.com/static prefix url, css file is https://b.com/static prefix url. I found vite has renderBuiltUrl mehthod.

```
import { defineConfig } from 'astro/config';

const config = {
  vite: {
    experimental: {
      renderBuiltUrl(filename, { hostType }) {
            return 'https://a.com/static'
      }
    }
  }
}

export default defineConfig(config);
```

But vite.experimental.renderBuiltUrl is not work.

Is support vite.experimental.renderBuiltUrl  config ?

### What's the expected result?

Js, css, ... file can use different cdn url

### Link to Minimal Reproducible Example

https://github.com/peng/astro-demo/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
It's possible that Astro's version of `vite` is outdated and doesn't have that option. Make sure you are using the correct version of vite.

**Comment by peng** [comment]
vite/5.0.10 darwin-arm64 node-v18.18.1, but vite `base` options is not work either.

> It's possible that Astro's version of `vite` is outdated and doesn't have that option. Make sure you are using the correct version of vite.

**Comment by peng** [comment]
> In what way does it not work? I guess the feature does work partially, but it's not taking effect on all files that you expected, hence it isn't working well. Astro also uses that config internally (but you can override it) with its [assetsPrefix](https://docs.astro.build/en/reference/configuration-reference/#buildassetsprefix) option, but it's opinionated that it applies to both JS and CSS files. But that option should also cover cases where it would fail if you only used `renderBuiltUrl` yourself.

Is `vite.experimental.renderBuiltUrl` can't replace `build.assetsPrefix` options ?

**Comment by peng** [comment]
> Yeah there is not support for this. Astro only supports the prefix for both JS and CSS, and you can't choose between it. If you want to see support for it, you can open a discussion in https://github.com/withastro/roadmap. Closing this for now as it's not a bug.
Ok, I have opened a discussion.  And I want open a PR to reslove it.
Discussion: https://github.com/withastro/roadmap/discussions/818.
