### ISSUE TITLE
Dev server hangs

### ISSUE THREAD

**Issue by theurgi** [withastro/astro#9703]
### Astro Info

```block
Astro                    v4.1.2
Node                     v21.5.0
System                   macOS (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             astro-icon
                         @astrojs/mdx
```

### Describe the Bug

I'm encountering an issue where the dev server hangs for a small Astro app. This occurs either immediately after running `pnpm dev` or, if the app loads, after a few minor changes are made to source files. To the degree that the dev server does work, it's very slow.

I was able to complete a significant amount of development without any such issue before the problem appeared suddenly. The logical conclusion was that it must be related to my most recently developed feature: using `getCollection` to render collections. It appears there may be some precedent for this:

- https://github.com/withastro/astro/issues/9616
- https://github.com/withastro/astro/issues/6173
- https://github.com/withastro/astro/pull/6257

Oddly, even after reverting these changes, the dev server starts but hangs again when I modify even a single style in a global stylesheet.

Here are some things I tried with out any luck:

- ❌ Deleting `node_modules` and `package.lock.json`, followed by reinstallation.
- ❌ Reverting to `astro@3.6.4`.
- ❌ Switching to `bun`.
- ❌ Trying different browsers like Chrome and Firefox.
- ❌ Clearing the browser cache and deleting the `.astro` directory.

I see no errors in the browser console or in the output of `pnpm dev --verbose`.

Unfortunately, I'm unable to publish the repository. Attempts to replicate the issue in a new project have been unsuccessful. 

The project still seems to build correctly.

I'll try to migrate the project to a new repo, piece by piece, and see if I can isolate the issue.

If there's any specific code, configuration, or output that may be helpful in diagnosing the issue, please let me know.

### What's the expected result?

For the dev server to serve the application and not hang.

### Link to Minimal Reproducible Example

[reproduction](https://github.com/theurgi/repro-astro-dev-server-hang)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Unfortunately, without a reproduction there's nothing we can do. Astro is a large enough software that it's not really obvious where the issue could be, and we can't even begin to investigate without any leads.

**Comment by theurgi** [comment]
I understand. I'll continue trying to reproduce the issue, hopefully succeeding before this issue self destructs in 3 days. Just wanted to put this out there in the mean time to increase visibility in the case that it's a newly introduced bug and others stumble across it.

Will report back soon. 🙏

**Comment by theurgi** [comment]
@Princesseuh 

Updated with a [reproduction](https://github.com/theurgi/repro-astro-dev-server-hang). There's additional context in the repo's readme.

**Comment by Princesseuh** [comment]
Awesome, thank you!

**Comment by theurgi** [comment]
A little more insight that may help debug this issue and which certainly points to content collections as being the source of the problem:

When I comment all code that uses `getCollection`, including the entire contents of `pages/[...slug].astro`, as well as comment `content/config.ts` and rename `content` to `_content`, I have no dev server issues what so ever.

Given that I can still successfully build using the content collections API, temporally doing the above during development has been an amendable workaround.

**Comment by lilnasy** [comment]
I have been able to run the dev server after commenting out this line.

![image](https://github.com/withastro/astro/assets/69170106/6f6dab96-20b3-4241-923e-b30a3ce37812)

Can you simplify the repro based on this info?

**Comment by theurgi** [comment]
@lilnasy 

In both my project and in the reproduction, I don't have any issues loading any of the layouts. By commenting out all content collections code, I've been able continue developing the UI (including the `GridLayout`) on the dev server. 

Were you at least able to reproduce the dev server hanging occasionally, to rule out an "on my machine" scenario? 

![repro-dev-server-hang](https://github.com/withastro/astro/assets/58859663/569c8b9a-5964-453a-b34a-7846ffd2b25b)

**Comment by lilnasy** [comment]
I was able to reproduce the dev server hanging, and I have been able to drill further and find a single change that unblocks the dev server to let it serve requests.

<img width="532" alt="image" src="https://github.com/withastro/astro/assets/69170106/e3415c2a-1711-47c2-8a19-c81f6eb4ea27">

The spread route page, `pages/[...slug].astro` imports `layouts/grid/GridLayout.astro` through an alias, which indirectly imports `layouts/global/GlobalLayout.astro` through an alias.

Even though `pages/index.astro` also imports `GridLayout`, it doesn't make the dev server hang.

**Comment by lilnasy** [comment]
Tried looking into it further, could not find where astro gets it wrong but I was able to simplify the project.
https://github.com/lilnasy/repro-astro-9703

- The presence of a spread route is necessary.
- It must import the same component as another route but using a different alias.

**Comment by vadimkantorov** [comment]
`npm run dev` hangs also happen for me - without a way to diagnose the problem. Maybe a more verbose mode is needed

`--verbose` does not help. it prints nothing for me when a requests comes in

`npm run build` works correctly, but `npm run dev` now hangs every time and serves no pages. I wonder if it's some i18n routes problem, but complete hang is not workable :(
