### ISSUE TITLE
Tailwind integration does not work with injected routes in SSR mode

### ISSUE THREAD

**Issue by antoinert** [withastro/astro#9707]
### Astro Info

```block
Astro                    v4.1.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         assets
```

### Describe the Bug

Tailwind integration does not work with injected routes using `injectRoute` when using SSR mode.

See the stackblitz repro. I have two integrations:
```
  [
    tailwind(),
    {
      name: 'assets',
      hooks: {
        'astro:config:setup': async ({ injectRoute }) => {
          injectRoute({
            pattern: 'injected',
            entryPoint: './src/pages/_injected.astro',
          });
        },
      },
    },
  ]
```

The ordering of the integrations does not seem to matter.

I would expect the tailwind styles to be loaded when accessing the injected route, however that is not the case. You can see this behavior in the stackblitz repro by navigating to `/injected`.

### What's the expected result?

Tailwind styles should work

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dlxp5v-hpvcmu?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@antoinert , is there some documentation that we violated?

**Comment by antoinert** [comment]
@ematipico not directly, no. There isn't much details about how injected routes are expected to behave in Astro docs.

Since you can inject `.astro` pages with `injectRoute` personally I would expect them to behave similar to "normal" routes from pages.

**Comment by florian-lefebvre** [comment]
I don't think anything is broken, it's just that injected routes won't have the injected tailwind style. Solution:
1. If you're have `applyBaseStyles: false`, import your custom css in your custom route
2. If not, just import `@astrojs/tailwind/base.css` (https://stackblitz.com/edit/github-dlxp5v-ptuqd6?file=src%2Fpages%2F_injected.astro)

Does that work for you?
