### ISSUE TITLE
Malformed entry filename is not reported

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#9711]
### Astro Info

```block
Astro                    v4.1.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

When an entry has an invalid frontmatter, the parsing library throws an error but the associated Astro error is irrelevant: it points to the `content/config.*` instead of the faulty file. For example, the following mdx file
```md
---
# example.mdx
title: 'Here's a wrong pair'
---
```
will throw this:
```
[GenerateContentTypesError] `astro sync` command failed to generate content collection types: can not read an implicit mapping pair; a colon is missed
  Hint:
    Check your `src/content/config.*` file for typos.
  Error reference:
    https://docs.astro.build/en/reference/errors/generate-content-types-error/
  Stack trace:
```

### What's the expected result?

Have a new error that specifies what file is failing. I don't think it's realistic to also want the exact location since it depends on the parsing library

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-se3vcm?file=src%2Fcontent%2Fblog%2Ffirst-post.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
It doesn't show very well for some reason, but right under the stack trace you have the `cause` of the error telling you why it happened

**Comment by florian-lefebvre** [comment]
I don't think the file is specified? So that's for md files. I updated the repro to have the error in the mdx file instead and there are even less indications
