### ISSUE TITLE
Importing mind-ar in an Astro component doesn't work in dev mode

### ISSUE THREAD

**Issue by MoritzLost** [withastro/astro#9722]
### Astro Info

```block
Astro                    v4.2.0
Node                     v18.17.1
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

We're trying to use [`mind-ar`](https://www.npmjs.com/package/mind-ar) in an Astro project. Unfortunately, this doesn't work because the package requires `node-fetch` which in turn has a dependency on `whatwg-url`. The latter is written in CommonJS, which means Vite has to bundle it in order to work in dev mode. Building the app works fine, but in dev mode, Vite doesn't bundle this dependency, so you get an error:

> Uncaught SyntaxError: ambiguous indirect export: default

That's coming from the `whatwgUrl` import in `node_modules/node-fetch/lib/index.mjs`

```javascript
import Stream from "/@id/__vite-browser-external:stream";
import http from "/@id/__vite-browser-external:http";
import Url from "/@id/__vite-browser-external:url";
import whatwgUrl from "/node_modules/whatwg-url/lib/public-api.js?v=9363c105";
import https from "/@id/__vite-browser-external:https";
import zlib from "/@id/__vite-browser-external:zlib";
```

Looks like that's the only dependency that isn't pre-bundled for some reason?

This issue came up in #6988, but was closed without a resolution. I don't think it's a Vite problem, as mentioned in that issue. Building the app does work, so it's definitely possible to get this working.

Another important factor: **If you create a new vite app without Astro, the import works fine in dev mode.** So it has to be related to something Astro does. Maybe related to how Vite discovers modules to pre-bundle in Astro components? I've tried to force Vite to pre-bundle those dependencies, but that's not working:

```typescript
// vite.config.js
import { defineConfig } from 'vite';

export default defineConfig({
    optimizeDeps: {
        entries: [
            'node_modules/node-fetch/lib/*.mjs',
            'node_modules/node-fetch/lib/*.js',
            'node_modules/whatwg-url/lib/*.js',
        ],
        include: [
            'node_modules/node-fetch/lib/*.mjs',
            'node_modules/node-fetch/lib/*.js',
            'node_modules/whatwg-url/lib/*.js',
        ],
    },
});
```

### What's the expected result?

Importing `mind-ar` should not cause errors.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hql7qf?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

(Willing yes, but probably not able to, I don't understand the cause of the issue well enough)

**Comment by florian-lefebvre** [comment]
@MoritzLost does it solve your issue?

**Comment by MoritzLost** [comment]
@florian-lefebvre Wow, looks like this works, thank you! The library initializes correctly with this. I'll have to check on Monday if the app is actually working correctly with this adjustment, but it's looking good.

I'm pretty confused, though – why does excluding the library from pre-bundling fix this issue? I thought the transformation from CommonJS to ES modules is what pre-bundling is for, so seems like the exact opposite should work? Maybe I'm misunderstanding how Vite works here …

Also, any ideas why the import works in a plain Vite project, but not in an Astro component?

I was stuck on this for days, thanks again for your help!

**Comment by florian-lefebvre** [comment]
idk tbh, I always try those 3:
- `vite.build.rollupOptions.external`
- `vite.ssr.external` (or `noExternal` in some cases)
- `vite.optimizeDeps.exclude`

@bluwy can you explain how this works?

**Comment by MoritzLost** [comment]
@florian-lefebvre @bluwy Would still be good to get an explanation on this issue and why the fix works. As mentioned, it doesn't happen in a plain Vite project, so probably related to something Astro does? Maybe a symptom of some other issue?
