### ISSUE TITLE
Dynamic routes take precedence over index.astro in 4.2

### ISSUE THREAD

**Issue by whatthewhat** [withastro/astro#9724]
### Astro Info

```block
Astro                    v4.2.0
Node                     v18.17.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  none
Integrations             none
```

### Describe the Bug

I've hit a potentially breaking change when updating from 3.5.5 to 4.2.0: `[...dynamic].astro` routes seem to have higher priority than `index.astro` after the upgrade. Apologies if this is an expected change, but I was unable to find 
it in the changelog.

There is a minimal stackblitz reproduction - with 3.x this would have rendered the Index page.

### What's the expected result?

In the stackblitz example I would expect the **Index** page to be rendered, but instead the **dynamic** route is rendered.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pqgx5b?file=src%2Fpages%2F%5B...dynamic%5D.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Fryuni** [comment]
Hey, thanks for the report. There was a patch to define an edge case on the routing, but it shouldn't have affected this use case, so it is indeed a bug.

I'm looking into it
