### ISSUE TITLE
Localhost doesn't load in Codespaces VS Code Desktop

### ISSUE THREAD

**Issue by stepmixx** [withastro/astro#9732]
### Astro Info

```block
Astro                    v4.2.1
Node                     v20.11.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Edge

### Describe the Bug

How can i to run Astro in Github Codespaces in VS Code Desktop, you didn't put any of that in the documentation. Creating a new project and doing `npm run dev` doesn't work. I saw that you have some devcontainers to run the example projects in codespaces, but nowhere in the documentation talks about that. In the browser works, but in VS Code Desktop with local port fowarding doesn't.

### What's the expected result?

Codespaces development environment should work when doing `npm run dev`

### Link to Minimal Reproducible Example

https://github.com/stepmixx/astro-codespaces (It's a new astro project, just open it in codespaces  in VS Code Desktop and run `npm run dev`)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
I can reproduce the issue on a starter astro template. I can also reproduce the issue on a starter sveltekit template. It isn't an astro bug. You might want to report this issue with github codespaces.
