### ISSUE TITLE
`injectRoute` request url is missing search params

### ISSUE THREAD

**Issue by mattiaz9** [withastro/astro#9737]
### Astro Info

```block
Astro                    v4.2.1
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Example:

index.ts
```ts
export default function filesIntegration(): AstroIntegration {
  return {
    name: "files-integration",
    hooks: {
      "astro:config:setup": ({ injectRoute, command }) => {
        if (command === "dev") {
          injectRoute({
            pattern: "/_file",
            entrypoint: "./files-integration/endpoint.ts",
            prerender: false,
          });
        }
      },
    },
  };
}
```

endpoint.ts
```ts
export const GET: APIRoute = async ({ request, url }) => {
  return new Response(url.href, {
    status: 200,
    headers: {
      "Content-Type": `text/plain`,
      "Cache-Control": "public, max-age=31536000",
    },
  });
};
```

In this `GET` request the `url.searchParams` is empty even though the url has some.

### What's the expected result?

`url.searchParams` should be filled with the url params

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/astro-injected-route-jvptjh

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Is it the same for `const url = new URL(request.url)`?

**Comment by lilnasy** [comment]
It works if you set output to server, the dev server is acting according the configuration. Feel free to reopen if you think there is still an issue.

**Comment by mattiaz9** [comment]
thank you @lilnasy for the clarification. 
Maybe I'm missing something. I'm trying to "reverse engineering" the `astro:assets` integration but for files.

Looking at this: https://github.com/withastro/astro/blob/53c69dcc82cdf4000aff13a6c11fffe19096cf45/packages/astro/src/assets/endpoint/node.ts seems like the request has the search params. How is this working without having to change the output?

**Comment by lilnasy** [comment]
The file you linked only gets executed on node-based adapters in production server builds.

**Comment by lilnasy** [comment]
What I said earlier was incorrect. The node endpoint is used both by the node adapter and the dev server which special cases `/_image`.

https://github.com/withastro/astro/blob/53c69dcc82cdf4000aff13a6c11fffe19096cf45/packages/astro/src/vite-plugin-astro-server/request.ts#L46-L47

**Comment by mattiaz9** [comment]
@lilnasy So basically there is no way to make it work right? I can't use search params and neither path params because `getStaticPaths()` is required.

Is there any possibilities to change the codebase to be more flexible? like for instance using this check `if (!buildingToSSR && !pathname.startsWith('/_'))`

**Comment by lilnasy** [comment]
I'm guessing what you want is this:

https://github.com/withastro/astro/issues/8847

Your issue prompted a discussion of possible options in our discord:
https://discord.com/channels/830184174198718474/845430950191038464/1197974743589077014
