### ISSUE TITLE
Dot files not copied over from `public` folder if not running build from root folder

### ISSUE THREAD

**Issue by taktran** [withastro/astro#9740]
### Astro Info

```block
✗ npx astro info
Astro                    v3.6.4
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/markdoc
                         @astrojs/sitemap
```

### Describe the Bug

I have a `public/.htaccess` file and when running `astro build`, it doesn't get copied over to the dist folder. I also have a custom `outDir` set to something like `../../dist/packages/folder`.

~~The strange thing is, I can't quite replicate it on stackblitz. This is my attempt, where the `.htaccess` **does** get generated when you run `npm run build` in the terminal: https://stackblitz.com/edit/github-es2mdg-rajrjb?file=README.md~~ (it can be reproduced when run from another directory - see stackblitz below)

However, looking at the code and patching the file locally, it does fix it on my local machine:

https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/static-build.ts#L439-L445

From

```
if (out.toString() !== opts.settings.config.outDir.toString()) {
  // Copy assets before cleaning directory if outside root
  await copyFiles(out, opts.settings.config.outDir);
  await fs.promises.rm(out, { recursive: true });
  return;
}

// Where
copyFiles(fromFolder: URL, toFolder: URL, includeDotfiles = false) 
```

it looks like `copyFiles` should set `includedDotfiles` parameter to true ie,

```
await copyFiles(out, opts.settings.config.outDir, true);
```

The `out.toString() !== opts.settings.config.outDir.toString()` check seems to match with my scenario where `outDir` is set, and I can't think of a reason why it wouldn't copy dot files (or a least make it configurable somewhere).

The `includedDotfiles` parameter seems to have been added in https://github.com/withastro/astro/pull/5832, if that is useful.

Am I missing something?

### What's the expected result?

Expect `.htaccess` to appear in the dist folder when running `astro build`. ~~Don't see the bug in the attached stackblitz, but can replicate locally and looking at the code, it does seem like it's a legitimate bug.~~

### Link to Minimal Reproducible Example

~~https://stackblitz.com/edit/github-es2mdg-rajrjb (not a reproducible example, but it's the gist of the steps - see above)~~

https://stackblitz.com/edit/github-es2mdg-xzyijr?file=README.md (actual reproducible example)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by taktran** [comment]
Oh, I checked out the stackblitz (https://stackblitz.com/edit/github-es2mdg-rajrjb) that was working locally, and looked at `out.toString() !== opts.settings.config.outDir.toString()`, which turns out to be `false` ie, `out` and `opts.settings.config.outDir` are the same on this simple example. So my original set up isn't so simple. It's using `nx` and `@nxtensions/astro`, which might be causing the differences in the out folders (I need to dig into this more).

However, although I'm not able to replicate atm, the code still does seem like there's an issue here in situations where the out folders are different.

**Comment by taktran** [comment]
Actually my initial assumption that it was related to the `outDir` is wrong, it's just about running astro build in another folder and using the `--root` parameter. Here is an example of the bug without changing the default `outDir`: https://stackblitz.com/edit/github-es2mdg-tnkbfm?file=README.md

**Comment by lilnasy** [comment]
You seem to have identified the right place for the fix from the PR. A PR would be welcome. Feel free to ask if you want pointers.

**Comment by taktran** [comment]
@lilnasy , have set up a PR here: https://github.com/withastro/astro/pull/9741 - give me a shout if it requires any more changes
