### ISSUE TITLE
Inconsistent Adapter Behavior When Deploying

### ISSUE THREAD

**Issue by thejackshelton** [withastro/astro#9748]
### Describe the Bug

I currently maintain the `@qwikdev/astro` integration, and I really feel stuck figuring out where the files should be built with different Astro adapters 😅 .

(works fine in dev and preview)

I would not be making this issue if I did not feel completely lost and unsure of the path forward, to the point of where we are in circles seemingly fixing the same things.

I want to ensure that people using Astro continue to have an awesome experience.

---

In the Qwik build step, virtual files are created called q-chunks. When users click on a button for example, those javascript files are executed. Looking for:
 `https://localhost:4321/build/q-2adaj3.js`

A chunk associated with the button's `onClick` handler. These files should be served from the root path of the consumer's site, and should be in whatever the "static" directory is.

<img width="309" alt="image" src="https://github.com/withastro/astro/assets/104264123/7770159a-2730-4b01-b8eb-e34052b484b0">

For some adapters, different paths are needed in order for them to work. For example, The `@astrojs/node` adapter uses the nested `client` folder in server/hybrid.

The Vercel adapter uses the `.vercel` directory, and if we don't use the client build path `astroConfig.build.client.pathname`, then the q-chunk files are not placed properly into the static folder

<img width="365" alt="image" src="https://github.com/withastro/astro/assets/104264123/71a0a8b5-a527-4388-922f-bedb475aec38">

I started to notice a trend, and used this ternary in the Qwik integration:
```tsx
    astroConfig.output === "server" || astroConfig.output === "hybrid"
      ? astroConfig.build.client.pathname
      : astroConfig.outDir.pathname;
```

This did in fact fix the issues of it not properly finding the q-chunks, but we now get an issue specifically with Astro.

**Problem:**

If the cloudflare or vercel integrations use the `server` or `hybrid` output

When an Astro API is added to the user's file, for example `<ViewTransitions />`

Then the `_astro` folder cannot be found.

--

In static mode, it uses `astroConfig.outDir.pathname`, and this seems to put the `_astro` folder in the correct place:

<img width="372" alt="image" src="https://github.com/withastro/astro/assets/104264123/3ae7e652-a658-4a98-b0bf-9a69d41c4310">

This behavior looks correct.

In the cloudflare integration with `server`, it exists, but inside of the `client` folder / path. Instead, `_astro` should be served at the root.

<img width="376" alt="image" src="https://github.com/withastro/astro/assets/104264123/6df17bbe-553d-41c3-93ad-64fe38fc8b7e">

reproduction: https://github.com/thejackshelton/qwik-astro-cloudflare
site: https://d519c0ff.qwik-astro-cloudflare.pages.dev/
where hoisted js actually is: https://d519c0ff.qwik-astro-cloudflare.pages.dev/client/_astro/hoisted.l-JsOPk0.js

--

In the vercel integration, `_astro` cannot be found in the vercel output at all.

<img width="373" alt="image" src="https://github.com/withastro/astro/assets/104264123/8fa6b792-3d5a-42ee-b428-89b125f82a3a">

reproduction: https://github.com/thejackshelton/debug-vercel
site: https://qwik-astro-vercel-9ldorfmhw-thejackshelton.vercel.app/

```
qwik-astro-vercel-9ldorfmhw-thejackshelton.vercel.app/:2  GET https://qwik-astro-vercel-9ldorfmhw-thejackshelton.vercel.app/_astro/hoisted.l-JsOPk0.js net::ERR_ABORTED 404 (Not Found)
```

I am happy to pair up and figure out this problem. My goal is making sure that people have an awesome experience building extremely performant and interactive apps. Qwik happened to be what I was looking for to achieve that inside of Astro.

### What's the expected result?

I expected the consumers `_astro` folder in the build directory to be found, same with the qwik virtual files across adapters. Both being served alongside the root path.

### Link to Minimal Reproducible Example

https://github.com/thejackshelton/qwik-astro-cloudflare

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
The addition of qwik integration switches the folder where client assets are written.

The path they get written to matches the variable the qwik integration code calls `distDir`

`distDir` is being passed to qwikVite plugin as `outDir`.

Could the vite plugin be overwriting vite config with the incorrect outDir?

**Comment by lilnasy** [comment]
Closing as astro and first-party integrations are behaving correctly.

**Comment by thejackshelton** [comment]
> The addition of qwik integration switches the folder where client assets are written.
> 
> The path they get written to matches the variable the qwik integration code calls `distDir`
> 
> `distDir` is being passed to qwikVite plugin as `outDir`.
> 
> Could the vite plugin be overwriting vite config with the incorrect outDir?

I'm not sure what to do at this point. Tried playing with it a couple more hours today. The `_astro` folder is still being moved, and it seems like I can't change that without changing the client build path, just to put the proper qwik files in the right directory.

This does not seem like something I can do as an integration author, thus I created this issue.
