### ISSUE TITLE
Samsung Internet 'go to top'-button don't work with ViewTransitions

### ISSUE THREAD

**Issue by zokkis** [withastro/astro#9752]
### Astro Info

```block
Astro                    v4.2.1
Node                     v20.10.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-purgecss
                         astro-compress
                         @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Samsung Internet

### Describe the Bug

Normally, when there is a lot of scrolling on a page, the 'go to top' button pops up on Samsung Internet. This works, but not when ViewTransitions is activated

I'm 95% sure its because of this line https://github.com/withastro/astro/blob/d0742bcfdaa124cc06b2edd5963b90797ef564fa/packages/astro/src/transitions/router.ts#L24

### What's the expected result?

Like on other Websites, the  'go to top' button should be visible and clickable.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-umcujs?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Can you investigate further? Why does that line cause it not to appear?

**Comment by gitZokki** [comment]
This is a native js function and i dont know whats the problem.

Even on the internet I dont get any infos about this button. Maybe because its a native button from Samsung Internet

**Comment by matthewp** [comment]
Closing since we can't investigate and fix this issue, but would accept a PR if you can figure it out.
