### ISSUE TITLE
[🐛] bug: error in build with astro 404 sitemap

### ISSUE THREAD

**Issue by TheElegantCoding** [withastro/astro#9754]
### Astro Info

```block
Astro                    v4.2.1
Node                     v20.10.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
                         @qwikdev/astro
```

### Describe the Bug

i have a qwik astro template with some basic stuff i add a 404.astro file and i get and error in the build step, i dont have nothing more is just a template

![image](https://github.com/withastro/astro/assets/70770072/9f239280-311a-44e9-abe1-ff1f3b1fb89c)

### What's the expected result?

A good build

### Link to Minimal Reproducible Example

https://github.com/TheElegantCoding/astro_template_webpage

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by thejackshelton** [comment]
Hey @TheElegantCoding, try `@qwikdev/astro` 0.4.5, does that fix your issue?
