### ISSUE TITLE
Error message about missing baseUrl should reflect publicDir config

### ISSUE THREAD

**Issue by Mitsunee** [withastro/astro#9759]
### Astro Info

```block
Astro                    v4.2.1
Node                     v18.19.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
which: no xclip (didn't even know I don't have that installed)
```

### If this issue only occurs in one browser, which browser is a problem?

unrelated

### Describe the Bug

After creating a repo using the framework-solid template and changing the baseUrl and publicDir configs according to the Gitlab Deployment guide I got the following error message:

```
[ERROR] [router] Request URLs for public/ assets must also include your base. "/favicon.svg" expected, but received "/favicon.svg".
```

1. This error message should probably reference the publicDir config instead of having `public/` hardcoded
2. The paths in the second half of the error message are the same. It appears the first should read something like `/{baseUrl}/favicon.svg`

### What's the expected result?

The error message should read:

```
[ERROR] [router] Request URLs for static/ assets must also include your base. "/my-page/favicon.svg" expected, but received "/favicon.svg".
```

for the following astro config:

```
import solid from "@astrojs/solid-js";
import { defineConfig } from "astro/config";

// https://astro.build/config
export default defineConfig({
  site: "https://gitlab-user.gitlab.io",
  base: "/my-page",
  integrations: [solid()],
  outDir: "public",
  publicDir: "static"
});
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xhj8bw-sw2zrn?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Hey @Mitsunee , can you update the reproduction with the correct information to reproduce the issue?  The configuration file doesn't have any `publicDir` set, for example.

**Comment by Mitsunee** [comment]
@ematipico I tried updating the stackblitz thing again, really dislike that site as it's never clear to what url it publishes and it doesn't work properly in any browser I've tried, it might just hate linux and/or flatpak.

The error does not seem to appear there either. Might need to do it locally. I basically just changed the config as seen above on the framework-solid template.

**Comment by ematipico** [comment]
Even a basic repository works

**Comment by Mitsunee** [comment]
can you remove the "needs repro" label please (or tell me why it's still there)? I have tried to provide a stackblitz repro and also given reproduction steps (which in itself should be sufficient to report such a basic issue).
