### ISSUE TITLE
HMR is not working properly

### ISSUE THREAD

**Issue by amirrezaDev1378** [withastro/astro#9771]
### Astro Info

```block
Astro                    v4.2.1
Node                     v18.18.2
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/react
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Firefox,Chrome

### Describe the Bug

With any of the provided templates, the whole page reloads when you change a file.

### What's the expected result?

instead of page reload, only part of my code which is changed be updated

### Link to Minimal Reproducible Example

any provided template

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is how Astro HMR works. If you use, for example, a React component it will only update that component in isolation.

**Comment by amirrezaDev1378** [comment]
Oh, thanks I didn't know that.

> This is how Astro HMR works. If you use, for example, a React component it will only update that component in isolation.
