### ISSUE TITLE
Typescript alias in the config.ts does't work

### ISSUE THREAD

**Issue by gitZokki** [withastro/astro#9777]
### Astro Info

```block
Astro                    v4.2.1
Node                     v20.10.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-purgecss
                         astro-compress
                         @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

When I use an alias to import a script or anything else into the astro-config then there is an error like

```bash
❯ npx astro build
2:01:18 AM [vite] Pre-transform error: Failed to load url @my-alias/helpers (resolved id: @my-alias/helpers) in /home/projects/github-umcujs-xnwaz8/astro.config.ts. Does the file exist?
2:01:18 AM [vite] Error when evaluating SSR module /home/projects/github-umcujs-xnwaz8/astro.config.ts: failed to import "@my-alias/helpers"
|- Error: Cannot find module '@my-alias/helpers' imported from '/home/projects/github-umcujs-xnwaz8/astro.config.ts'
    at nodeImport (/home/projects/github-umcujs-xnwaz8/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50938:25)
    at ssrImport (/home/projects/github-umcujs-xnwaz8/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50845:30)

[astro] Unable to load your Astro config

Cannot find module '@my-alias/helpers' imported from '/home/projects/github-umcujs-xnwaz8/astro.config.ts'
  Stack trace:
    at nodeImport (/home/projects/github-umcujs-xnwaz8/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50938:25)
```

### What's the expected result?

Astro should allow imports into the astro-config

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-umcujs-xnwaz8?file=package.json,tsconfig.json,astro.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
The astro config has to be loaded _before_ anything fancy can be done. This is explained in a note here: https://docs.astro.build/en/guides/configuring-astro.

**Comment by gitZokki** [comment]
> The astro config has to be loaded _before_ anything fancy can be done. This is explained in a note here: https://docs.astro.build/en/guides/configuring-astro.

This is a absolute stupid response to this... Because its 100% working with relative and absolute paths, the only problem is the alias...

So please look into it or give me a reason why it's not a bug, that I can't use aliases

**Comment by ematipico** [comment]
> This is a absolute stupid response to this... Because its 100% working with relative and absolute paths, the only problem is the alias...

Relative and absolute paths are Node.js/spec things, while aliases are tooling things (TypeScript, vite, webpack, etc.). And as we explained, we run our tooling after we load the configuration. 

If you feel so adamant about it, **you** are free to **look** into it.
