### ISSUE TITLE
Monaco Editor Syntax Highlighting Not Working in Astro with React

### ISSUE THREAD

**Issue by Rokiis1** [withastro/astro#9783]
### Astro Info

```block
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

All browsers

### Describe the Bug

When trying to use Monaco Editor in an Astro project with React, the CSS for Monaco Editor is not being loaded correctly, resulting in the syntax highlighting not working.  I see default color. The issue persists even after manually copying the `vs` directory from `node_modules/monaco-editor/min` to the public directory and importing the CSS in the component.

If I use just Vite and React it's works correctly .

### What's the expected result?

 The Monaco Editor should load with correct styles and syntax highlighting.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/astroissuesmonacoeditor-nj3fjc?file=%2Fsrc%2Fcomponents%2FCodeEditorComponent.jsx%3A4%2C58

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your reproduction does not seem to include the necessary dependencies, could you please update it?

**Comment by florian-lefebvre** [comment]
Can confirm what Erika says. Anyway, I added the missing deps a few deps and gave it a shot. I couldn't find what goes wrong. I tried the workarounds for ESM (as documented on monaco's github) but didn't work either. It's weird that it works in a plain vite app and not in astro

**Comment by Rokiis1** [comment]
My dependencies:

`
	"dependencies": {
		"@astrojs/react": "^3.0.9",
		"@astrojs/renderer-react": "^0.5.0",
		"@astrojs/tailwind": "^5.1.0",
		"@babel/standalone": "^7.23.8",
		"@types/react-dom": "^18.2.18",
		"astro": "^4.1.2",
		"monaco-editor": "^0.44.0",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"react-monaco-editor": "^0.55.0",
		"tailwindcss": "^3.4.1"
	},
	"devDependencies": {
		"@babel/cli": "^7.23.4",
		"@babel/core": "^7.23.7",
		"@babel/preset-env": "^7.23.8",
		"@types/react": "^18.2.47",
		"lodash": "^4.17.21",
		"vite": "^5.0.11"
	}
}
`

[github: Repo](https://github.com/Rokiis1/IDE/blob/main/client/src/components/CodeEditorComponent.jsx)

I readed docs from astro and monaco, but still can't find the solution, I also try babel to compile, but still doesn't help.

Maybe in this case it would be if I choose a plain vite, but I don't wanna, because astro would be better chooise.

**Comment by daniellizik** [comment]
this guy has a working example of monaco editor in astro 

https://dev.to/thepassle/trying-out-astro-ssr-astro-10-hackaton-3h0g

https://github.com/thepassle/passle-courses
