### ISSUE TITLE
`create astro` does not add additional dependencies in certain cases

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#9791]
### Astro Info

```block
Astro                    v4.2.3
Node                     v18.19.0
System                   Windows (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             astro-env
```

### Describe the Bug

When running `pnpm create astro@latest` and choosing the following options:
- TS: Yes
- Strictness: Strict
- Install deps: No

`@astrojs/check` and `typescript` are not added as `devDependencies`.

### What's the expected result?

Well, just add them to the `package.json`: https://github.com/withastro/astro/blob/main/packages%2Fcreate-astro%2Fsrc%2Factions%2Ftypescript.ts#L93-L97

### Link to Minimal Reproducible Example

N/A

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jacobdalamb** [comment]
Same is true with `install deps: yes`...
