### ISSUE TITLE
inline scripts in layout with view transitions not re-executing

### ISSUE THREAD

**Issue by OliverSpeir** [withastro/astro#9798]
### Astro Info

```block
Astro                    v4.2.3
Node                     v18.19.0
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Before 3.5 (I think or at least around there) `<script is:inline>`s that existed on both the original and the page being transitioned to would re execute after transition and this is documented [here](https://docs.astro.build/en/guides/view-transitions/#script-behavior-during-page-navigation). 

>If you have code that sets up global state, this state will need to take into account that the script might execute more than once. Check for the global state in your <script> tag, and conditionally execute your code where possible:
```
<script is:inline>
  if(!window.SomeGlobal) {
    window.SomeGlobal = {} // ....
  }
</script>
```

Although this is not explicitly stating that inline scripts in your layout will re-execute after transition, I assume it is the spirit of providing the global check. 

Inline scripts do execute after transition (obviously), the only change is that if there is an identical script on the page that is being transitioned to, it remains marked as "already been ran" 

### What's the expected result?

I believe inline scripts should re-execute, as I think that is the point of an inline script. If not, I think there should be a way to specify built in similar to `astro-data-reload`. I'm creating this issue as a means of sparking discussion about why this behavior is happening. I might be missing something in terms of why this is important behavior. 

Side note: Stackblitz has a seperate behavior for this issue in their preview so if you do use the minimal reproduction it's better to run it locally. The `<h1>` should be turned green after moving between pages, in my opinion. 

### Link to Minimal Reproducible Example

https://github.com/OliverSpeir/vt-inline

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Current behavior: Scripts of the new page are executed if they have not yet been seen (since the page was last fully loaded). We should update the documents to be consistent. 

Users often had problems when scripts that were not intended to be automatically executed multiple times. Typical errors were complaints about re-declared constants and the like.

Users should use the lifecycle events to re-execute the code where needed and adapt it where necessary to avoid re-declarations.

On the other hand: For re-execution robust inline scripts, having a way to opt-in on re-execution doesn't sound too bad to me.

**Comment by morja** [comment]
I am having the exact opposite problem. See https://github.com/withastro/astro/issues/8466#issuecomment-1907084538

**Comment by OliverSpeir** [comment]
Thanks Morja for the reference I think this is the PR where the behavior changed 
https://github.com/withastro/astro/pull/8603 


What this PR is trying to solve is what Martin describes
> Users often had problems when scripts that were not intended to be automatically executed multiple times. Typical errors were complaints about re-declared constants and the like.

Although, not reexecuting in order to avoid re-declaration I think is more of a workaround than solving the larger issue. The issue is that top level `let/const` variables are preserved during the transfer. These variables should be attached to document and thus not be brought over to the new document. At least I ***think*** this is what is going on.

**Comment by matthewp** [comment]
If we switched back to re-execute (which we can't do until 5.0) then we'll just have new bug reports about errors caused through scripts that don't expect to be run more than once. Which is the right "default" I don't know, but I think it's close enough to 50/50 that changing the default now would be the wrong call.

Some sort of attribute to say "i want this to re-execute" could be ok to me. I suppose the use-case is a third party script, not one under your control?

As far as consts, etc. that is indeed not something we can fix. That's where the abstraction breaks down, there is indeed only 1 window, these are not actually separate pages. So there's really no solution for scripts that have trouble with this.

**Comment by OliverSpeir** [comment]
Cool sounds like an opt in flag will be acceptable! 

Works for me

**Comment by martrapp** [comment]
why not have it closed with the PR that introduces the flag?

**Comment by OliverSpeir** [comment]
Dang it that would make a lot more sense
