### ISSUE TITLE
Response headers are not set

### ISSUE THREAD

**Issue by fstojanac** [withastro/astro#9805]
### Astro Info

```block
Astro                    v4.2.4
Node                     v18.18.0
System                   Linux (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

I have a problem setting headers when the `prerender` flag is set to `true`. 

Everything works as expected when you run `astro dev` but headers are omitted from the produced build bundle as soon as you try to do `astro build`.

### What's the expected result?

The same headers should be included in the build output as they are in the dev build.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cknhdd?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
@fstojanac, can you update your reproduction and tell us how to check if the headers aren't set?

**Comment by lilnasy** [comment]
Unless I am misunderstanding, this is expected bheavior. Prerendering involves creating html files out of your pages. Headers don't retain in html files. To achieve the same effect, you might want to use http-equiv meta html tag.
