### ISSUE TITLE
Anchor tag automatically closes when another anchor tag is nested inside

### ISSUE THREAD

**Issue by ezaz-ahmed** [withastro/astro#9806]
### Astro Info

```block
Astro                    v4.2.3
Node                     v18.19.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-icon
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Microsft Edge

### Describe the Bug

When attempting to nest one anchor (<a>) tag inside another within in a component, the outer anchor tag automatically closes. 
This issue results in unexpected HTML structure and causing unintended rendering in web browsers.

### What's the expected result?

The expected behavior is anchor (<a>) tag will not close automatically. Instead, it'll render components what's inside in it and then it'll close the tag.

If it's a violation of HTML rules, then it should provide an error or warning, instead of unexpected rendering. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2tmyyl?file=src%2Fcomponents%2FCard.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Yeah this happens because of the invalid html (an anchor tag nested inside another anchor tag) which Astro tries to correct following the html standard. We don't show warnings for invalid html currently, but you can create a discussion in the [roadmap](https://github.com/withastro/roadmap) repo so we can track that feature request.
