### ISSUE TITLE
error 500 in vercel adapter 7.0.1

### ISSUE THREAD

**Issue by viclunam** [withastro/astro#9810]
### Astro Info

```block
Astro                    v4.1.2
Node                     v20.10.0
System                   macOS (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

All

### Describe the Bug

on @astrojs/vercel@7.0.1 there is no problem in the build, but the site is inaccessible throwing a 500 error.

``` sh
TypeError: NodeApp.writeResponse is not a function
    at Server.handler (file:///var/task/.vercel/output/_functions/entry.mjs:8956:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (/opt/node-bridge/bridge-server-NOEMJORR.js:1:8898)
```

### What's the expected result?

by downgrading to version 6.1.3, it just worked, everything being ok.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mq9gzr?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
@astrojs/vercel v7 depends on astro 4.2+, which introduces `NodeApp.writeResponse`. I see you are on 4.1.2. Could you try upgrading?

**Comment by lilnasy** [comment]
Thanks for reporting back!
