### ISSUE TITLE
_image endpoint not working on firebase hosting

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [withastro/astro#9811]
### Astro Info

```block
Astro                    v4.2.4
Node                     v20.5.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/lit
                         @astrojs/prefetch
                         astrojs-service-worker
```

### Describe the Bug

In production, the endpoint does not seem to find the image to transform.

Indeed after a deployment, it looks like the endpoint cannot obtain the image to create the inputBuffer variable and returns "NOT FOUND".

On the other hand, when I try the _image address without href, the endpoint returns "Server Error: Error: Incorrect transform returned by `parseURL`" so it works well and somewhat confirms my theory.

While everything works correctly locally.

### What's the expected result?

that the endpoint returns the optimized image

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
This might be a difficult to confirm since firebase functions requires a paid plan to test on. Do you notice the same issue locally with `node dist/server/entry.mjs`?

**Comment by Geoffrey-Pliez** [comment]
@lilnasy 

no, locally everything works

**Comment by lilnasy** [comment]
Can you share the error message from firebase dashboard?

**Comment by Geoffrey-Pliez** [comment]
{
  "insertId": "65b13e28000ef389e3e3b2b6",
  "httpRequest": {
    "requestMethod": "GET",
    "requestUrl": "***/_image?f=webp&href=%2F_astro%2FM_M.GWJQyD8M.webp&w=420",
    "requestSize": "1672",
    "status": 404,
    "responseSize": "670",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "remoteIp": "***",
    "referer": "***",
    "serverIp": "216.239.34.53",
    "latency": "0.499410173s",
    "protocol": "HTTP/1.1"
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "location": "europe-west1",
      "revision_name": "***",
      "service_name": "ssr",
      "configuration_name": "ssr",
      "project_id": "***"
    }
  },
  "timestamp": "2024-01-24T16:43:20.478419Z",
  "severity": "WARNING",
  "labels": {
    "goog-managed-by": "cloudfunctions",
    "instanceId": "0087599d424b1d1afbd6637c03efced6b97fef6d09c9e28ef7b759b0f43ba7600ad8329e6f6683a8571ee69b9f74a01e9c4882f0a80348a37c39479bbd3ec961"
  },
  "logName": "projects/project-359443804751131057/logs/run.googleapis.com%2Frequests",
  "trace": "projects/project-359443804751131057/traces/ea029e0a4730a494c8bc110c8fbb9320",
  "receiveTimestamp": "2024-01-24T16:43:21.109852702Z",
  "spanId": "5368813349973126890"
}

**Comment by levimoore** [comment]
I am experiencing this same problem. 

I am importing a logo file in a Layout like this:
```
import { Image } from 'astro:assets';
import Logo from '../images/logo.png';
```
this image is optimized during build:
```
 generating optimized images
10:27:17   ▶ /_astro/logo.8FgpA393_1fKHTS.webp (before: 16kB, after: 2kB) (+406ms) (1/12)
10:27:17   ▶ /_astro/logo.8FgpA393_Z15yRO3.webp (reused cache entry) (+1ms) (2/12)
```
I use the Layout on the /register and /login pages. 
on the register page this is the <img /> tag:
```
<img src="/_astro/logo.8FgpA393_1fKHTS.webp" class="h-20 w-auto" alt="logo" data-astro-cid-sckkx6r4="" width="80" height="80" loading="lazy" decoding="async">
```
on the login page this is the <img /> tag:
```
<img src="/_image?href=%2F_astro%2Flogo.8FgpA393.png&amp;w=80&amp;h=80&amp;f=webp" class="h-20 w-auto" alt="logo" data-astro-cid-sckkx6r4="" width="80" height="80" loading="lazy" decoding="async">
```

**Comment by levimoore** [comment]
@Geoffrey-Pliez I am not sure if this will help you, but adding:
```
export const prerender = true;
```
to the login page fixed the error for me.

**Comment by Geoffrey-Pliez** [comment]
@levimoore 
your solution works but only for pages which can be static but not in ssr.
And in this case, the endpoint is not called.

But this proves that the image (/_astro/pathToImage) exists but that the endpoint (/_image) cannot reach it

**Comment by Geoffrey-Pliez** [comment]
I just noticed that the endpoint _image works correctly when the images are external.
So the problem is only a local access problem.

**Comment by matthewp** [comment]
The reproduction doesn't use Firebase. Can you update it?

**Comment by Geoffrey-Pliez** [comment]
Here is the [minimal reproduction](https://stackblitz.com/edit/withastro-astro-ksqg6x?file=package.json).
You must then host it on firebase hosting.
But the problem doesn't seem to be happening anymore.

Current packages:
 - @astrojs/node@8.2.5
 - astro@4.5.18
- firebase-admin@11.11.1
- firebase@10.10.0
- firebase-tools@13.7.3

**Comment by matthewp** [comment]
Thanks @Geoffrey-Pliez ! My favorite kind of issues are the ones that have already resolved themselves.  Please do file a new issue if you encounter this again.
