### ISSUE TITLE
[GenerateContentTypesError] `astro sync` command failed to generate content collection types: image

### ISSUE THREAD

**Issue by godalming123** [withastro/astro#9814]
### Astro Info

```block
Astro                    v4.2.4
Node                     v20.10.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
which: no xclip in (/home/jg/.npm/_npx/aa98e6899c6baff3/node_modules/.bin:/home/jg/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/lib/node_modules_20/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:~/go/bin/:~/go/bin/:/home/jg/.local/bin:/home/jg/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
```

### Describe the Bug

I'm trying to follow the docs (https://docs.astro.build/en/guides/images/#images-in-content-collections) which say:
> The `image` helper for the content collections schema lets you validate the image metadata using Zod.
> `src/content/config.ts`
> ```astro
> import { defineCollection, z } from "astro:content";
>
> const blogCollection = defineCollection({
>   schema: ({ image }) => z.object({
>     title: z.string(),
>     cover: image().refine((img) => img.width >= 1080, {
>       message: "Cover image must be at least 1080 pixels wide!",
>     }),
>     coverAlt: z.string(),
>   }),
> });
>
> export const collections = {
>   blog: blogCollection,
> };
> ```
But I get the following error message when I run `npx astro build`, I get the following error message:
```
[GenerateContentTypesError] `astro sync` command failed to generate content collection types: image is not defined
  Hint:
    Check your `src/content/config.*` file for typos.
  Error reference:
    https://docs.astro.build/en/reference/errors/generate-content-types-error/
  Stack trace:
    at syncInternal (file:///home/jg/Documents/antonioPerforms/node_modules/astro/dist/core/sync/index.js:78:11)
    at async AstroBuilder.run (file:///home/jg/Documents/antonioPerforms/node_modules/astro/dist/core/build/index.js:167:23)
    at async build (file:///home/jg/Documents/antonioPerforms/node_modules/astro/dist/cli/build/index.js:20:3)
    at async cli (file:///home/jg/Documents/antonioPerforms/node_modules/astro/dist/cli/index.js:149:5)
  Caused by:
  image is not defined
    at eval (/home/jg/Documents/antonioPerforms/src/content/config.ts:9:39)
```
Here is my `src/content/config.ts` file:
```ts
import { defineCollection, z } from "astro:content";

export const collections = {
  content:
    defineCollection({
      schema: z.object({
        title: z.string(),
        images: z.array(image()),
      }),
    }),
};
```
***Note***: This issue was first reported [here, on discord](https://discord.com/channels/830184174198718474/1198291517329121320/1198291517329121320)

### What's the expected result?

The build would be succesful

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gdluhf (you need to run `npx astro build` from the command line)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
This is expected, the schema can either be a zod schema (like yours currently) or a function that returns a schema (that's what you want). Just update this line:

```diff
- schema: z.object({
+ schema: ({ image }) => z.object({
```
