### ISSUE TITLE
Dev toolbar App with absolute file path does not work on Windows

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#9824]
### Astro Info

```block
Astro                    v4.2.4
Node                     v18.19.0
System                   Windows (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @sentry/astro
                         @spotlightjs/astro
```

### Describe the Bug

When provided an absolute file path to a dev toolbar app (for example using the Spotlight integration) on Windows, it fails to load:
```
10:32:50 [ERROR] [toolbar] Failed to load dev toolbar app from D:\DEV\PROJECTS\florian-lefebvre\astro-spotlight-repro\node_modules\@spotlightjs\astro\src\overlay\index.ts: Failed to fetch dynamically imported module: file:///D:/DEV/PROJECTS/florian-lefebvre/astro-spotlight-repro/node_modules/@spotlightjs/astro/src/overlay/index.ts
```

### What's the expected result?

It should load properly

### Link to Minimal Reproducible Example

https://github.com/florian-lefebvre/astro-spotlight-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Ah, I didn't mean to remove anything in that PR, I'll send a PR. Sorry for the inconvenience!

**Comment by KyTiXo** [comment]
Welp.. wasted a whole hour trying to figure out why my toolbar wouldn't import in a fresh project haha
