### ISSUE TITLE
Custom error pages are not served in production

### ISSUE THREAD

**Issue by alatielle** [withastro/astro#9829]
### Astro Info

```block
Astro                    v4.2.4
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          unknown
Output                   hybrid
Adapter                  @astrojs/node
Integrations             astro-i18next
                         @astrojs/react
```

### Describe the Bug

Given an endpoint returning `return new Response(null, { status: 404 })`,
I've noticed different behaviours when serving the site with `astro dev` or `astro preview`.

astro dev: custom 404 page is shown
astro preview: blank page is shown

It also works as expected, when a 404 Response is returned in the code-fence of Astro page, but not in an endpoint.

### What's the expected result?

If in production the endpoint returns a response with 404 status and the custom 404 page is present, it should show up

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-s7uxf1?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I know that @lilnasy is working on a number of refactors to our routing logic at the moment, which will hopefully solve this category of issues!

Error pages have been a suprisingly challenging problem that frankly has felt like a constant  issue whack-a-mole. Thanks for your patience as we work on some larger refactors to make this behavior more reliable and consistent.

**Comment by lilnasy** [comment]
In this case, dev is being incorrect. Endpoints returning a response with an error status code are supposed to be served untouched.

**Comment by alatielle** [comment]
Ah, the incorrect dev behaviour would be desired in our case :D How can we better achieve serving a 404 page here? By manual redirection?

**Comment by natemoo-re** [comment]
> Ah, the incorrect dev behaviour would be desired in our case :D How can we better achieve serving a 404 page here? By manual redirection?

In lieu of a [better API](https://github.com/withastro/roadmap/discussions/681) for rendering the error page manually, a redirect is probably the cleanest solution at the moment! Hopefully we can tackle that (or something similar) as part of our larger efforts here.

The inconsistency is definitely still a relevant current bug, though!
