### ISSUE TITLE
`experimentalReactChildren` flag has issues when passing Image elements

### ISSUE THREAD

**Issue by StandardGage** [withastro/astro#9833]
### Astro Info

```block
Astro                    v4.1.2
Node                     v20.10.0
System                   Windows (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

When passing any sort of image to a React component (such as Astro's Image component or a simple `<img>` element), specifically when the client directive is used, the image will appear for a split second before disappearing. Looking at the console shows an error:
`Warning: An error occurred during hydration. The server HTML was replaced with client content in <astro-island>.` So it seems Astro is replacing the content. The component works perfectly if hydration is not used, but this kind of defeats the purpose of using react here.

My example below shows multiple different image variations that I tried to pass as children to a React component.

### What's the expected result?

The Image should be handed off to React without issues as if it was any other child.

### Link to Minimal Reproducible Example

[sandbox](https://codesandbox.io/p/devbox/astro-image-as-react-children-sysvvn?embed=1&file=%2Fsrc%2Fpages%2Findex.astro&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrfpm14k00072a66bsg2pn29%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrfpm14k00022a66hlr2pewl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrfpm14k00042a66tdrat1xk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrfpm14k00062a66nu8jzc6c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B62.34511087824278%252C37.65488912175722%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrfpm14k00022a66hlr2pewl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrfpm14k00012a66hakexvxe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clrfpm14k00022a66hlr2pewl%2522%252C%2522activeTabId%2522%253A%2522clrfpm14k00012a66hakexvxe%2522%257D%252C%2522clrfpm14k00062a66nu8jzc6c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrfpm14k00052a66hxkdhcok%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A4321%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrfpm14k00062a66nu8jzc6c%2522%252C%2522activeTabId%2522%253A%2522clrfpm14k00052a66hxkdhcok%2522%257D%252C%2522clrfpm14k00042a66tdrat1xk%2522%253A%257B%2522id%2522%253A%2522clrfpm14k00042a66tdrat1xk%2522%252C%2522activeTabId%2522%253A%2522clrfpo4pi00bv2a66k0bi5mun%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrfpm14k00032a660eopvxdb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clrfpo4pi00bv2a66k0bi5mun%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrfpo4dh000edxfmagui9ahn%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%252C%2522id%2522%253A%2522clrfpp43300f22a662spwk92a%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
## Good first issue!
This is an opportunity for astro users to learn about how astro works by fixing a small but real bug. You can expect to get help setting up the dev environment, and understanding the project structure in `#dev` channel of our discord server (https://astro.build/chat).

### What's the bug?
Presence of void elements (img, source, br) in slotted children of a react component breaks hydration with `experimentalReactChildren` enabled.

### What's going wrong here?
When `experimentalReactChildren` is enabled, the react integration's client-side code parses the slotted html to turn it into virtual nodes. It always creates an array as `props.children` of the virtual nodes it creates, even when there are 0 children elements. React breaks when it finds an empty array as `props.children` of an `img` tag.

### Where do I start looking?
The part where the the react integration's client-side code generates virtual DOM nodes using html strings is here:
https://github.com/withastro/astro/blob/8281ebddaac1bd1355f1d2bc7967ec36b6d61299/packages/integrations/react/client.js#L37-L44

A similar fix was made for the server-side code in https://github.com/withastro/astro/pull/9141.
