### ISSUE TITLE
Error executing astro cli using `pnpm astro <commands, options, and args>`

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [withastro/astro#9844]
### Astro Info

```block
All system informations, including `astro` version : 
* I am using Git baash for Windows
* Here are the exact versions of the tools I use : 




$ pnpm exec astro --version

   astro  v4.2.4


$ node -v
v18.18.0


$ pnpm -v
8.14.1


$ npm -v
9.8.1


$ bash --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```
Note I open this issue as suggested by theteam, cf. https://github.com/withastro/docs/pull/6558#issuecomment-1910713922
```


### If this issue only occurs in one browser, which browser is a problem?

it is an error with the cli, not any browser

### Describe the Bug

Indeed, if you run `pnpm astro add preact`, you get the following error : 

```bash
$ pnpm astro add preact

> ossified-orbit@0.0.1 astro C:\Users\Utilisateur\radio_jaune_2024
> astro "add" "preact"

'astro' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
 ELIFECYCLE  Command failed with exit code 1.
```

The error message is in French, translation is `astro is not recognized as a command, internal  or external`

### What's the expected result?

That the astro command does execute, whatever the result.

I will add here more detail and analysis, because the error is not repoductible in an environment like stackblitz, is certainly is specific to the OS and shell environment. The issue is important, because the OS and shell environment that are concerned, are widely used by developers: Windows (here Windows 10 pro), and git bash for windows.

Here is therefore, the detailed steps to reproduce the issue on the reader's machine.

As I was setting up a new astro project, I had to execute `pnpm dlx` to execute `astro add preact`.

But after successfully adding preact astro integration using `pnpm dlx`, I experienced an issue:
* I then tried to add another package, `lucide-preact`
* to do that,  I executed `pnpm add --save lucide-preact`
* I ended up with the following error : 

```bash
$ pnpm add --save lucide-preact
 WARN  Moving astro that was installed by a different package manager to "node_modules/.ignored"
 WARN  Moving preact that was installed by a different package manager to "node_modules/.ignored"
 EPERM  EPERM: operation not permitted, rename 'C:\Users\Utilisateur\my_project_here\node_modules\astro' -> 'C:\Users\Utilisateur\my_project_here\node_modules\.ignored\astro'


```

Now, to solve that, I had to roll back the astro preact integration installation, by : 

* running  : 

```bash
rm -fr ./node_modules/
pnpm remove @astrojs/preact preact
```
* I di not change my `astro.config.mjs` : 

```TypeScript
import tailwind from "@astrojs/tailwind";
import icon from "astro-icon";
import { defineConfig } from "astro/config";

import preact from "@astrojs/preact";

// https://astro.build/config
export default defineConfig({
  site: "https://astro-moon-landing.netlify.app/",
  integrations: [tailwind(), icon(), preact({ compat: true })]
});
```

* to : 
```TypeScript
import tailwind from "@astrojs/tailwind";
import icon from "astro-icon";
import { defineConfig } from "astro/config";

// https://astro.build/config
export default defineConfig({
  site: "https://astro-moon-landing.netlify.app/",
  integrations: [tailwind(), icon()]
});
```

* Then I manually installed the astro preact integration, and the lucide-preact package : 

```bash
pnpm add @astrojs/preact preact
pnpm add @preact/compat
pnpm add lucide-preact
```

Note that after that, I tested creating a bare new astro project, to try and use `pnpm exec` instead of `pnpm dlx`, and that confirmed to se astro cli with pnpm, one should use `pnpm exec astro`: 

```bash
Utilisateur@Utilisateur-PC MINGW64 ~/pr_test/retrograde-ring
$ pnpm exec astro add preact
- Resolving packages...
√ Resolving packages...
05:03:04
  Astro will run the following command:
  If you skip this step, you can always run it yourself later

 ╭──────────────────────────────────────────────────╮
 │ pnpm add @astrojs/preact@^3.1.0 preact@^10.19.3  │
 ╰──────────────────────────────────────────────────╯

? Continue? » (Y/n)Y
√ Continue? ... yes
- Installing dependencies...
√ Installing dependencies...
05:03:25
  Astro will make the following changes to your config file:

 ╭ astro.config.mjs ─────────────────────────────╮
 │ import { defineConfig } from 'astro/config';  │
 │                                               │
 │ import preact from "@astrojs/preact";         │
 │                                               │
 │ // https://astro.build/config                 │
 │ export default defineConfig({                 │
 │   integrations: [preact()]                    │
 │ });                                           │
 ╰───────────────────────────────────────────────╯

? Continue? » (Y/n)Y
√ Continue? ... yes
05:03:32
   success  Added the following integration to your project:
  - @astrojs/preact
05:03:32
  Astro will make the following changes to your tsconfig.json:

 ╭ tsconfig.json ─────────────────────────────╮
 │ {                                          │
 │   "extends": "astro/tsconfigs/strictest",  │
 │   "compilerOptions": {                     │
 │     "jsx": "react-jsx",                    │
 │     "jsxImportSource": "preact"            │
 │   }                                        │
 │ }                                          │
 ╰────────────────────────────────────────────╯

? Continue? » (Y/n)Y
√ Continue? ... yes
05:03:34
   success  Successfully updated TypeScript settings

Utilisateur@Utilisateur-PC MINGW64 ~/pr_test/retrograde-ring
$ pnpm add --save preact @preact/compat lucide-preact
Progress: resolved 0, reused 1, downloaded 0, added 0
Progress: resolved 3, reused 3, downloaded 0, added 0
Progress: resolved 209, reused 185, downloaded 0, added 0
Packages: +2
++
Progress: resolved 479, reused 444, downloaded 0, added 1
Progress: resolved 479, reused 444, downloaded 0, added 2
Progress: resolved 479, reused 444, downloaded 0, added 2, done

dependencies:
+ @preact/compat 17.1.2
+ lucide-preact 0.314.0

Done in 6.9s

```

The astro version I used at the time of my test is `^4.2.4`,  : 

```bash
$ cat package.json
{
  "name": "retrograde-ring",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "astro": "^4.2.4"
  }
}

```

My guessed explanation is that using `pnpm dlx` invokes `npm` ( `npx` ), while we want to use pnpm, and that's why one should use `pnpm exec`.

So I think it would be useful to add a warning about that point in the astro docs, for the `pnpm` `astro` projects. I would say this warning should appear at least for every astro integration commands for frameworks, like here for preact in this PR.  

### Link to Minimal Reproducible Example

https://github.com/withastro/docs/pull/6558#issuecomment-1907348078

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
I use Git Bash for Windows with pnpm exclusively as well, and I've had anything like this happen.

Can you share the result of running these 4 commands:

<details>
<summary>

```bash
mkdir x
cd x
pnpm create astro --template basics --yes .
pnpm astro add preact --yes
```

</summary>

![image](https://github.com/withastro/astro/assets/69170106/ec7cde07-106f-49a5-b121-00479711f7c6)

</details>

<details>
<summary>

`pnpm dlx` works just as well.

</summary>

![image](https://github.com/withastro/astro/assets/69170106/2752a3a5-66be-4a21-812a-017630069c2d)

</details>

**Comment by Jean-Baptiste-Lasselle** [comment]
> ```shell
> pnpm astro add preact --yes
> ```

Hello, @lilnasy , thank you for ckecking on that, I do get an error, the same error I described: 

![image](https://github.com/withastro/astro/assets/35227860/2086b8a3-0922-417c-93fa-b2c52d1cbf3b)

since you don't have the same result as i do, I assume this is caused by an unappropriate nodejs or pnpm installation on my machine.
