### ISSUE TITLE
ESBuild unable to build .node files when using Node with Astro

### ISSUE THREAD

**Issue by lukesteinbicker** [withastro/astro#9845]
### Astro Info

```block
Astro                    v4.2.6
Node                     v18.17.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

I received this error message when attempting to run my project after building:
 No loader is configured for ".node" files: node_modules/sharp/build/Release/sharp-win32-x64.node

    node_modules/sharp/lib/sharp.js:10:27:
      10 │   module.exports = require(`../build/Release/sharp-${platformAndArch}.node`);

It appears that this is a common issue with ESBuild but not resolved within the Astro build files:
https://github.com/getsentry/profiling-node/issues/189
https://stackoverflow.com/questions/68576780/esbuild-error-no-loader-is-configured-for-node-files-node-modules-sharp-bui

It's pretty easy to resolve this issue if you're bundling with vanilla ESBuild but the Astro build process is a lot more complex and likely requires changing the source code.

I would provide a reproducible link but this takes a while to set up and I'm fairly sure that the problem is clear as is.

### What's the expected result?

A completed build with my server running in the background

### Link to Minimal Reproducible Example

https://google.com

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lukesteinbicker** [comment]
https://github.com/withastro/astro/issues/9518

This issue appears to bring up the same thing but it's unclear how to remove Sharp from ESBuild. I am using the Node adapter, which should not have any issues in the first place.

**Comment by lilnasy** [comment]
The problem is not clear. `sharp` is used by default for all build. If there's a common issue, I would expect be caught in testing or at least reported widely. Is manual usage of sharp involved? Is it possible it is being imported into code that runs on the browser or an edge runtime?
