### ISSUE TITLE
ASTRO_ASSET (string) field definition missing from type ImageFunction return value and interface ImageMetadata

### ISSUE THREAD

**Issue by aripalo** [withastro/astro#9852]
### Astro Info

```block
Astro                    v4.2.1
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/netlify
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         astro-icon
```

### Describe the Bug

`ASTRO_ASSET: string` field definition missing from [`type ImageFunction` return value](https://github.com/withastro/astro/blob/70fdf1a5c660057152c1ca111dcc89ceda5c8840/packages/astro/content-types.template.d.ts#L23) and [interface ImageMetadata](https://github.com/withastro/astro/blob/70fdf1a5c660057152c1ca111dcc89ceda5c8840/packages/astro/src/assets/types.ts#L34).

**Having access to `ASTRO_ASSET` is useful: For example one could use it to create blurhash string (or other image placeholder values) _centrally_ within content collection schema definitions – without having to do it in various views/layouts.**

In comparison [`ImageMetadata["fsPath"]`](https://github.com/withastro/astro/blob/70fdf1a5c660057152c1ca111dcc89ceda5c8840/packages/astro/src/assets/types.ts#L40-L41) has been marked `@internal`, but `ASTRO_ASSET` is not marked internal, it's just missing from type definitions.

Of course I can workaround the issue by doing something like:
```ts
import {  type ImageFunction } from 'astro:content';

type CtxImage = z.infer<ReturnType<ImageFunction>>;

type CtxImageAsset = CtxImage & {
  ASTRO_ASSET: string;
};

function isCtxImageAsset(img: CtxImage): img is CtxImageAsset {
  return 'ASTRO_ASSET' in img;
}
```

... but I would feel much more comfortable with depending on that value if it were present in Astro's own type definitions as well (not just runtime JavaScript).

### What's the expected result?

I would like to see `ASTRO_ASSET` as part of `type ImageFunction` and/or `interface ImageMetadata`.

I'm willing to make a pull request, but I'd require some guidance if it's okay to add it and if yes, then for both or just to `ImageFunction` for example.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-avs1k5?file=src%2Fcontent%2Fconfig.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by aripalo** [comment]
I'm thinking the most logical place to add `ASTRO_ASSET` is the type `ImageFunction`. That being said, there is a comment:
```ts
// This needs to be in sync with ImageMetadata
```
… so maybe the change should be reflected there too?

**Comment by aripalo** [comment]
So I went ahead and created PR https://github.com/withastro/astro/pull/9853

- Though that being my first time contributing to Astro, I'm not sure if all is correct (at least I tried to follow `CONTRIBUTING.md`)
- As I mentioned in the PR, there was a test failure but that failure happened also on `main` branch without my modifications
- Again, this is just a suggestion, I don't know Astro internals that well yet so I can't be sure if my suggestion makes any sense (in the bigger picture even though it makes sense for me)

**Comment by Princesseuh** [comment]
This is intended, `ASTRO_ASSET` is just an internal way of tracking assets through the content collection pipeline, you're not intended to rely on it in any way.

We'd prefer adding a blessed way to do this if we were to, because at the moment you cannot at all rely on either `ASTRO_ASSET` or `fsPath` in certain contexts (ex: SSR in certain envs)

**Comment by aripalo** [comment]
Makes sense. Well I'll keep on relying on it for now until it is removed/changed 😅 (luckily it's just my personal static website, so nothing major).

Thanks for the clarification!
