### ISSUE TITLE
Bug: Transform Error on Script Update within Component

### ISSUE THREAD

**Issue by ImEins** [withastro/astro#9855]
### Astro Info

```block
Astro                    v4.1.1
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         astro-icon
                         @astrojs/preact
                         astro-imagetools
```

### Describe the Bug

Created a script at src/scripts/Test.ts and utilized it within a component using the script tag. When modifications are made to the script file, an error occurs:

```
[ERROR] [vite] Internal server error: Transform failed with 1 error:
/xx/src/components/Test.astro?astro&type=script&index=0&lang.ts:2:9: ERROR: Expected "(" but found "Test"
```

Will provide a minimal reproduction, but encountered the issue on a large-scale website, initially attributing it to a syntax problem. Note that the problem only occurs upon the first save of the file.

### What's the expected result?

It's weird, I would like to fix it if possible :)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cpurh1?file=src%2Fscripts%2FTest.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Do I understand correctly that when you save the Test.ts file you are getting that error, but just the first time?

**Comment by ImEins** [comment]
exactly, when modifying something in the script file then saving it.

**Comment by florian-lefebvre** [comment]
I can't reproduce on the stackblitz reproduction, can you give me some more precise steps? Like what file should be edited in what order

**Comment by lilnasy** [comment]
@ImEins The stackblitz didn't error for me either. Do you know if it is specific to an OS?

https://github.com/withastro/astro/assets/69170106/36201dcc-577a-450b-8a85-b1361056426b
