### ISSUE TITLE
i18n redirect does not respect "hybrid output mode" configuration

### ISSUE THREAD

**Issue by castarco** [withastro/astro#9858]
### Astro Info

```block
Astro                    v4.2.6
Node                     v21.4.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/sitemap
                         @astrojs/mdx
```

### Describe the Bug

As a developer of a "hybrid output" web app (where most of my pages are static, except for a few ones where I need an extra pinch of dynamism):
- I'm writing static localised pages (each one inside its corresponding [lang] directory
- I'm using English as default language
- I'm using `prefixDefaultLocale: true`
- I'm using `trailingSlash: 'always'`

I want that the non-prefixed version of the page (namely `/`) redirects (via 302) to the best lang match given the headers sent by the user agent.

Currently, I have no way to indicate Astro that I want that process to happen dynamically:
- If I introduce an `index.astro` file where I set the `export prerender = false` statement... the `/` is not properly served anymore (I just get a 404).
- If I don't have an `index.astro` file, the `build` step complains that this file is missing, and that it is necessary to introduce the redirect imposed by the `prefixDefaultLocale: true` setting.
- If I leave an empty `index.astro` file, Astro is able to build, and I get a "weak version" of the redirect I really need: a static page with a refresh meta tag (hardcoded to the default lang, nothing dynamic). This presents several problems:
   - User experience: The redirect takes 3 seconds (and I can't configure it)... and even if I wanted to configure it, that would go against many accessibility guidelines because of the sudden and surprising redirect that is visible on the user side.
   - User experience: Having a hardcoded language value goes against what I want to achieve with the language autodetect.
   - SEO: a redirect imposed via meta refresh is not as nice as a clean 302 status code

On top of that, if I try to introduce my own redirect logic (because Astro does not provide the ability to do so) I'm forced to completely disable the i18n feature, having to roll my own hyper-custom version of it just so I can have proper redirects.

### What's the expected result?

I need to:
- either having the ability to define my own redirection behaviour without having to completely disable the i18n feature
- or having a sane default on Astro side to have dynamic i18n redirects for the case of `prefixDefaultLocale: true` (for many reasons I don't want to give a "privileged" path to any language, even if it's my default one).

**NOTE:** The linked Stackblitz example shows what I'd like to get from Astro, we need to comment out (or uncomment) some code to show the current behaviour (in `astro.config.mjs` and `pages/index.astro`).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-8vt68u?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
We recently shipped a new option https://docs.astro.build/en/guides/internationalization/#redirecttodefaultlocale

Use this option to disable the index redirect and roll out your own redirect logic.

**Comment by castarco** [comment]
Thank you, that reference helped.
