### ISSUE TITLE
http localhost failing in Chrome

### ISSUE THREAD

**Issue by slaetthult** [withastro/astro#9861]
### Astro Info

```block
Astro                    v4.2.6
Node                     v20.11.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Only in Chrome Version 120.0.6099.234 (x86_64)

### Describe the Bug

Standard astro installation with node 20.
When I want to run "npm run dev" everytime I get this error message and localhost doesnt work anymore in Chrome:
Do you know this issue?
(node:19821) Warning: An error event has already been emitted on the socket. Please use the destroy method on the socket while handling a 'clientError' event.
(Use `node --trace-warnings ...` to show where the warning was created)

![Bildschirmfoto 2024-01-29 um 11 10 26](https://github.com/withastro/astro/assets/22275417/76316861-582e-487d-b369-4348b2d73a60)

When I use node --trace-warnings, I get the following:
```
(node:26244) Warning: An error event has already been emitted on the socket. Please use the destroy method on the socket while handling a 'clientError' event.
    at warnUnclosedSocket (node:_http_server:866:11)
    at Socket.socketOnError (node:_http_server:880:5)
    at onParserExecuteCommon (node:_http_server:915:19)
    at onParserExecute (node:_http_server:836:3)
```
It seems that Chrome doesnt't accept http localhosts.

Unfortunately, I cant reprouce this on Stackblitz

### What's the expected result?

localhost should work in Chrome with and without https.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I can't reproduce this locally. Searching on the web, I found this though: https://stackoverflow.com/questions/76652485/how-to-stop-a-random-node-error-node196569-warning-an-error-event-has-alre

Maybe you also try other browsers, node version, or restart the server in case some websocket servers didn't close down properly.

**Comment by lilnasy** [comment]
Thanks for looking into it!
