### ISSUE TITLE
Image references in Markdown files are strange

### ISSUE THREAD

**Issue by ktym4a** [withastro/astro#9863]
### Astro Info

```block
Astro                    v4.2.6
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
```

### Describe the Bug

The documentation describes how to handle images in Markdown files as follows.
```
<!-- Local image stored in src/assets/ -->
<!-- Use a relative file path or import alias -->
![A starry night sky.](../assets/stars.png)

<!-- Image stored in public/images/ -->
<!-- Use the file path relative to public/ -->
![A starry night sky.](/images/stars.png)

<!-- Remote image on another server -->
<!-- Use the full URL of the image -->
![Astro](https://example.com/images/remote-image.png)
```
https://docs.astro.build/en/guides/images/#images-in-markdown-files

but we can use file path to access `/src/*`, which will show up as dev mode. but when after build, image path is not correct (The path is under the public directory).

Actually, I noticed it while researching #9842.

### What's the expected result?

I personally expect to not allow file path routing with `/src/*`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gzbaza-e3pwij?file=src/content/docs/index.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
That's a Vite thing, it serves the entire project through HTTP, you can actually access all the project's files this way. We don't process any files starting with a `/` though, it's a bit ambiguous what the user means by it, so we just assume it's something in `public`
