### ISSUE TITLE
Relative paths do not display images with Japanese file names

### ISSUE THREAD

**Issue by ktym4a** [withastro/astro#9864]
### Astro Info

```block
Astro                    v4.2.6
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
```

### Describe the Bug

Images are not displayed when Japanese file names are used in relative paths.
and Even after build, images are not displayed.

I noticed it while researching #9842.

Maybe he used the file path because the relative path did not show the image.

### What's the expected result?

Images are displayed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gzbaza-khzbru?file=src/content/docs/guides/example.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I believe the issue is the same, so let's track the progress in https://github.com/withastro/astro/issues/9842
