### ISSUE TITLE
ContentCollections type generation generates faulty .d.ts on windows

### ISSUE THREAD

**Issue by fabiankachlock** [withastro/astro#9869]
### Astro Info

```block
Astro                    v4.2.6
Node                     v20.11.0
System                   Windows (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             astro-i18next
                         @astrojs/prefetch
                         @astrojs/sitemap
                         @astrojs/vue
                         astro-compress
                         @astrojs/mdx
```

### Describe the Bug

When running `yarn astro sync` on windows the following line will be generated at the end of the `.astro/types.d.ts` file:

```ts
type ContentConfig = typeof import("./..\src\content\config.js");
```

The dynamic import statement contains a faulty file path which results in all `CollectionEntry<xy>['data']` properties having the `any` type.

### What's the expected result?

The path to the `content/config.ts` should either use only normal slashes `/` or when using backslaches they need to be escaped like so `\\`.

```ts
type ContentConfig = typeof import("./../src/content/config.js");
// or
type ContentConfig = typeof import(".\\..\\src\\content\\config.js");
```

### Link to Minimal Reproducible Example

not possible

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Feel free to send a PR!
