### ISSUE TITLE
Astro.url ignores trailingSlash in build output

### ISSUE THREAD

**Issue by GiyoMoon** [withastro/astro#9870]
### Astro Info

```block
Astro                    v4.2.6
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

In the build output, astro seems to ignore `trailingSlash: 'never'` and `Astro.url` always creates URLs with a trailing slash.

Go to the Stackblitz reproduction and build the project with `npm run build`. Then check the generated html file at `./dist/subpath/index.html`. The canonical link has a trailing slash.

### What's the expected result?

`trailingSlash: 'never'` should be considered for `Astro.url`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gs5j67?file=src%2Fpages%2Fsubpath.astro,astro.config.mjs%3AL7

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wkeizer** [comment]
+1

**Comment by GiyoMoon** [comment]
@patryk-smc That's expected.
```ts
new URL('https://example.com').toString() // Will print "https://example.com/"
new URL('https://example.com/').toString() // Will print "https://example.com/"
```
Home page URLs with or without a trailing slash are being treated the same and doesn't cause issues with SEO.
This also is the case for the `@astrojs/sitemap` package. Have a look here: https://github.com/withastro/astro/issues/8517
