### ISSUE TITLE
Endpoint Response.redirect header modification

### ISSUE THREAD

**Issue by friedemannsommer** [withastro/astro#9871]
### Astro Info

```block
Astro                    v4.2.6
Node                     v20.11.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

When returning [`Response.redirect`](https://developer.mozilla.org/en-US/docs/Web/API/Response/redirect_static) from an endpoint, the `renderEndpoint` function tries to [set an HTTP response header](https://github.com/withastro/astro/blob/44c957f893c6bf5f5b7c78301de7b21c5975584d/packages/astro/src/runtime/server/endpoint.ts#L42-L46) on the [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) object of the `handler`. This will throw a `TypeError: immutable` and return an HTTP 500 error to the client.

Note that [`new Response(..)`](https://developer.mozilla.org/en-US/docs/Web/API/Response/Response) and [`Response.json`](https://developer.mozilla.org/en-US/docs/Web/API/Response/json_static) are not affected by this issue, even though they technically should be :thinking:.

---

This is a relatively new change introduced by [`075706f26d2e11e66ef8b52288d07e3c0fa97eb1`](https://github.com/withastro/astro/commit/075706f26d2e11e66ef8b52288d07e3c0fa97eb1).
These changes are included in Astro from version `4.2.4` and later.

### What's the expected result?

The client should receive a HTTP 30X response with a `Location` header.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-2fktbw?file=README.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Sad. I'll look into it.

**Comment by lilnasy** [comment]
Thanks for looking into it, this is all spot on!

I didn't know Response.redirect would have immutable headers, but it would make sense. The directive would have to be something other than a header.

**Comment by lilnasy** [comment]
I have written a test based on your repro here: https://github.com/withastro/astro/compare/main...lilnasy:astro:fix/9871

Feel free to take that and attempt a fix. I would guess putting the `.set()` in a try-catch block helps.
