### ISSUE TITLE
☂️ Move Astro tests to `node:test` 

### ISSUE THREAD

**Issue by ematipico** [withastro/astro#9873]
## Description

Internally, the team decided to move our testing infrastructure to use `node:test` instead of Mocha.

While Mocha **is good**, it has its own quirks. Also, we believe that the Node.js test runner will improve with time. 

This is an **excellent opportunity** to contribute to Astro and help us with the migration because you don't need to understand Astro logic. So if you have been looking for an opportunity to contribute to Astro, this is the **perfect chance for you**!

## Plan

**Comment here which integration/adapter** you want to migrate first. Failing to comment might nullify your contribution if someone else did the work and **commented** on the issue. This will help us to avoid having multiple people working on the same thing.

The plan should be as follows:
1. Migrate tests of our `@astrojs/*` packages. This can be done in one PR, because we only have a few tests inside our integrations/adapters. You can use this PR as a blueprint of what we're looking for: https://github.com/withastro/astro/pull/9758
2. **Progressively** migrate the tests we have in core, starting with the unit tests, then integrations tests. This means that we need to have **two** scripts, one that will run the tests using Mocha, and one that will run the tests using Node.js

### Integrations/adapters

List of the integrations/adapters

- [x] Migrate tests of [`@astrojs/vue`](https://github.com/withastro/astro/tree/main/packages/integrations/vue)
- [x] Migrate tests of [`@astrojs/alpinejs`](https://github.com/withastro/astro/tree/main/packages/integrations/alpinejs)
- [x] Migrate tests of [`@astrojs/lit`](https://github.com/withastro/astro/tree/main/packages/integrations/lit) @xMohamd 
- [x] Migrate tests of [`@astrojs/markdoc`](https://github.com/withastro/astro/tree/main/packages/integrations/markdoc)
- [x] Migrate tests of [`@astrojs/mdx`](https://github.com/withastro/astro/tree/main/packages/integrations/mdx)
- [x] Migrate tests of [`@astrojs/partytown`](https://github.com/withastro/astro/tree/main/packages/integrations/partytown)
- [x] Migrate tests of [`@astrojs/preact`](https://github.com/withastro/astro/tree/main/packages/integrations/preact)
- [x] Migrate tests of [`@astrojs/react`](https://github.com/withastro/astro/tree/main/packages/integrations/react)
- [x] Migrate tests of [`@astrojs/sitemap`](https://github.com/withastro/astro/tree/main/packages/integrations/sitemap)
- [x] Migrate tests of [`@astrojs/solid`](https://github.com/withastro/astro/tree/main/packages/integrations/solid)
- [x] Migrate tests of [`@astrojs/svelte`](https://github.com/withastro/astro/tree/main/packages/integrations/svelte)
- [x] Migrate tests of [`@astrojs/tailwind`](https://github.com/withastro/astro/tree/main/packages/integrations/tailwind)
- [x] Migrate tests of [`@astrojs/vercel`](https://github.com/withastro/astro/tree/main/packages/integrations/vercel) @mingjunlu 

### Core
- [x] Migrate tests of [@astrojs/rss](https://github.com/withastro/astro/tree/main/packages/astro-rss)
- [x] Migrate tests of [@astrojs/internal-helpers](https://github.com/withastro/astro/tree/main/packages/internal-helpers)
- [x] Migrate tests of [telemetry](https://github.com/withastro/astro/tree/main/packages/telemetry) @VoxelMC 
- [x] Migrate tests of [@astrojs/underscore-redirects](https://github.com/withastro/astro/tree/main/packages/underscore-redirects)
- [x] Migrate tests of [@astrojs/upgrade](https://github.com/withastro/astro/tree/main/packages/upgrade)

#### `astro`

After https://github.com/withastro/astro/pull/10002 is merged, we can **progressively** start migrating tests.

Instructions:
- rename a `*.test.js` file to `*.nodetest.js`, e.g. `api.test.js` -> `api.nodetest.js`
- migrate the content of the test to use Node.js test runner
- use the command `pnpm test:node` to run **only** the files that use Node.js test runner

> [!WARNING]
> Node.js test runner doesn't handler deep nested `describe,` so it's possible your test could hang and timeout. If that happens, lift the `describe` function.

- [x] Migrate tests of [astro](https://github.com/withastro/astro/tree/main/packages/astro)

### External adapters

https://github.com/withastro/adapters/issues/144

**Comment by log101** [comment]
Been looking to contribute for a few days, I'd like to grab `@astrojs/tailwind` if that's OK?

**Comment by mingjunlu** [comment]
I'm willing to migrate tests of `@astrojs/sitemap` 🗺️

**Comment by VoxelMC** [comment]
I'll try first with `telemetry`!

**Comment by at-the-vr** [comment]
I will take a hit on [`@astrojs/vue`](https://github.com/withastro/astro/tree/main/packages/integrations/vue?rgh-link-date=2024-01-30T10%3A58%3A53Z)

**Comment by alexnguyennz** [comment]
Working on `@astrojs/mdx`.

**Comment by ktym4a** [comment]
I will take `@astrojs/markdoc`.

**Comment by VoxelMC** [comment]
I will do `@astrojs/svelte`!

**Comment by ematipico** [comment]
> I will do `@astrojs/react`!
> Does `@astrojs/svelte` have tests?

It seems not, thank you for checking

**Comment by xMohamd** [comment]
> > I will do `@astrojs/react`!
> > Does `@astrojs/svelte` have tests?
> 
> It seems not, thank you for checking

I think also `@astrojs/solid`, '@astrojs/preact', and `@astrojs/partytown` don't have tests

**Comment by VoxelMC** [comment]
Doing `@astrojs/alpinejs` now!

**Comment by xMohamd** [comment]
I will try with `@astrojs/lit` later today

**Comment by VoxelMC** [comment]
> > Doing `@astrojs/alpinejs` now!
> > I may need some assistance for this, as it uses Playwright instead of Mocha. Either that, or someone else should take it!
> 
> If there aren't any mocha tests, we can skip the package

I will take on `@astro/rss` instead, then :)

**Comment by at-the-vr** [comment]
I will take a hit on [`@astrojs/underscore-redirects`](https://github.com/withastro/astro/tree/main/packages/underscore-redirects?rgh-link-date=2024-01-30T10%3A58%3A53Z)

**Comment by VoxelMC** [comment]
@ematipico there are no tests for `internal-helpers` either :)

**Comment by ematipico** [comment]
`@astrojs/vercel` is missing, if anyone wants to help.

**Comment by mingjunlu** [comment]
@ematipico I'd be happy to help!

**Comment by ematipico** [comment]
Perfect, we can start slowly porting the test files we have in core. 

Let's comment here by saying the files we want to port, so we don't do double work

**Comment by VoxelMC** [comment]
I will start on the `astro-markdown-*` tests! Let's get this party started

**Comment by at-the-vr** [comment]
I will take a hit on the `vue` tests

**Comment by ktym4a** [comment]
I will take `custom-404-*` tests!

**Comment by xMohamd** [comment]
I will start on the `error-*` tests

**Comment by mingjunlu** [comment]
I'll take `static-*` tests

**Comment by xMohamd** [comment]
I'll take `ssr-*` tests

**Comment by at-the-vr** [comment]
I will take `collection-collection-*` tests

**Comment by ematipico** [comment]
I will take `units/config`, `units/cookies` and `units/content-collections`

**Comment by ematipico** [comment]
I will take ALL the `units/*` tests :)

**Comment by shoaibkh4n** [comment]
hey guys, Anything left for me 🙂. 
I think no one is doing for `packages/create-astro/test` so I'm taking it ✌.

**Comment by VoxelMC** [comment]
I can take the `slots-*` tests while I wait for confirmation on my next PR!

**Comment by at-the-vr** [comment]
> I will take `collection-collection-*` tests

This one is a brainteaser, if someone else could do this that would be super helpful 🙏 (looking at ya Voxel 👀 )

**Comment by at-the-vr** [comment]
I will take the alias-**.test.js

**Comment by ematipico** [comment]
I'll take files that:
- starts with the letter `d*`
- starts with the letter `e*`

**Comment by ematipico** [comment]
I'll take files that:
- starts with `v`
- starts with `u`
- starts with `s`

**Comment by at-the-vr** [comment]
I will take `css-*` tests

**Comment by ematipico** [comment]
I'll take files that start with `p*` and `r*`

**Comment by ktym4a** [comment]
I'll take files that start with `f*`, `g*` and `h*`

**Comment by marwan-mohamed12** [comment]
I made this files `featuresSupport`, `fetch`, `fontsource` in PR #10115

**Comment by ematipico** [comment]
I'll take files that start with `m*`, `n*` and `l*`

**Comment by ktym4a** [comment]
JUST MEMO

If my checks are correct, the remaining tests are these:

- [ ] start with `0*`
- [ ] start with `a*`
- [ ] start with `c*`
- [ ] start with `g*` #10125 
- [ ] start with `h*` #10125 
- [ ] start with `i*`
- [ ] start with `j*`
- [ ] start with `l*` @ematipico  
- [ ] start with `m*` @ematipico 
- [ ] start with `n*` @ematipico 
- [ ] start with `p*` #10123
- [ ] start with `r*` #10123

**Comment by ktym4a** [comment]
I'll take `0*` and `c*`.

**Comment by mingjunlu** [comment]
I'll take `a*`
