### ISSUE TITLE
Add name property to details element

### ISSUE THREAD

**Issue by LarryIVC** [withastro/astro#9881]
### Astro Info

```block
Astro                    v4.2.1
Node                     v18.18.2
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

The <details> element does not support a name property.

![image](https://github.com/withastro/astro/assets/110146573/432c076f-5b04-4a7c-b096-6bde717fe3c4)
![image](https://github.com/withastro/astro/assets/110146573/9db8a6f6-5f21-45cc-83c5-920df59920b5)

### What's the expected result?

With the name property, we can group several <details> elements.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! If possible, please make sure to correct your issue formatting. There seems to be some weirdness going on with the `<details>` markup.

Is this request to support the `name` property on the `HTMLDetailsElement` type interface?

**Comment by LarryIVC** [comment]
Hi @natemoo-re, yes I need to add support for the `name`property on the `HTMLDetailsElement` type interface.

**Comment by jacobdalamb** [comment]
If you want to create the PR yourself @LarryIVC you can just add it to https://github.com/jacobdalamb/astro/blob/457e8b6422704ba23347c766a8bb9c101c2aba0b/packages/astro/astro-jsx.d.ts#L671

**Comment by LarryIVC** [comment]
I created a pull request
https://github.com/withastro/astro/pull/9918
