### ISSUE TITLE
Bug/Tests: some tests that expect errors to be thrown can never fail

### ISSUE THREAD

**Issue by espy** [withastro/astro#9905]
### Astro Info

```block
This is a bug in the Astro tests on `main`, so this field does not apply.
```

### Describe the Bug

There’s a specific style of test that will always pass, for example in [packages/astro/test/i18n-routing.test.js#L555-L564](https://github.com/withastro/astro/blob/main/packages/astro/test/i18n-routing.test.js#L555-L564)`, where the expected outcome is that an error _is_ thrown:

```js
it("should render a 404 because the route `fr` isn't included in the list of locales of the configuration", async () => {
  try {
    await fixture.readFile('/fr/start/index.html');
    // failed
    return false;
  } catch {
    // success
    return true;
  }
});
```

~~However, if you switch the `return false;` and the `return true;`, the test still passes.~~
**Correction:** that ☝️ is not the correct way to reproduce this problem. The correct reproduction is to have the `try` block _not_ throw an error, which should make the test fail:

```js
it("This test should pass, success means an error was thrown", async () => {
  try {
    throw new Error('assume readFile failed')
    // failed
    return false;
  } catch {
    // success
    console.log('expected')
    return true;
  }
});

it("This test should fail, success means an error was thrown", async () => {
  try {
    const something = "unexpected"
    console.log(something)
    // failed
    return false;
  } catch {
    // success
    return true;
  }
});

```

However, both tests pass:

```bash
expected
      ✔ This test should pass, success means an error was thrown
unexpected
      ✔ This test should fail, success means an error was thrown
```

 I assume this requires the use of something like `assert.throws`, but I’m not an expert here.

### What's the expected result?

The tests that expect caught errors actually fail if no errors are caught.

### Link to Minimal Reproducible Example

Does not apply, bug is in the Astro tests

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by espy** [comment]
Updated the issue, I had made a mistake by simplifying the reproduction too far. Switching the return statements only demonstrates that this test format will never fail if you’re using it to test than an error should _not_ be thrown, which doesn’t actually cover the described problem. Apologies if this caused any confusion.

**Comment by ematipico** [comment]
Wanna send a PR? It should be fairly easy to update it. 

Make that a function, and use the `.to.throw`  function from chai

**Comment by espy** [comment]
There are 60 instances of `try {` in the tests directory in a variety of packages, I’m afraid I don’t have the time to check whether this applies to each of them, and if so to figure out what to do if any of them start failing. 

I'm currently working on a fix for a different i18n bug, which I’m having to re-do due to yesterday’s merge event, so maybe I can at least take care of the instances in the `packages/astro/test/i18n-routing.test.js` file, which I’m working on anyway.

**Comment by ematipico** [comment]
Oh yeah, sorry, I actually meant the tests inside `packages/astro/test/i18n-routing.test.js` :)

**Comment by VoxelMC** [comment]
> Oh yeah, sorry, I actually meant the tests inside `packages/astro/test/i18n-routing.test.js` :)

Since these are promises, wouldn't we need to check for rejection using `chai-as-promised`?
I have tried fixing these using `expect(...).to.throw();` and it doesn't work! It throws an `ENOENT` but the test doesn't catch that.

In my own branch, I experimented using `chai-as-promised` to make these tests work, and found that they can be refactored to this:

```js
import { use, expect } from 'chai';
import chaiAsPromised from 'chai-as-promised';
use(chaiAsPromised);
...
const filePromise = fixture.readFile('/fr/start/index.html');
expect(filePromise).to.eventually.throw();
```

This would add a devDependency to the project, but other than that, what do you think?
*An alternative would be to delay fixing these tests until they are moved to `node:test`.*

**Comment by abidjappie** [comment]
Since the tests have been moved to `node:test` is it okay to start looking into these again?
Is there any thing that needs help, I wouldn't mind assisting to fix some tests here 🙇

**Comment by ematipico** [comment]
@abidjappie the premises made by @espy are correct; in order to fix those tests, we can use the assertion utility `assert.fail` 

Feel free to send a PR

**Comment by abidjappie** [comment]
Something like this seems to do the job
```
		it("should NOT render the default locale if there isn't a fallback and the route is missing", async () => {
			try {
				await fixture.readFile('/it/start/index.html');
				// It should throw before reaching this point
				assert.fail('The file should not exist');
			} catch (e) {
				assert.equal(e.message.includes('ENOENT'), true);
			}
		});
```
For now I'll fix all the cases in `i18n-routing.test.js`

**Comment by ematipico** [comment]
Closing, fixed by https://github.com/withastro/astro/pull/10156
