### ISSUE TITLE
Astro wrongly process markdown code

### ISSUE THREAD

**Issue by LunaticMuch** [withastro/astro#9909]
### Astro Info

```block
❯ astro info
Re-optimizing dependencies because vite config has changed
Astro                    v4.2.7
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             astro-expressive-code
```

### Describe the Bug

It looks like Astro preprocesses the [hast](https://github.com/syntax-tree/hast) in a way that’s incompatible with this plugin (other rehype plugins). [rehype-mermaidjs](https://github.com/remcohaszing/rehype-mermaidjs) searches for `<pre>` and `<code>` elements, but Astro turns them into raw nodes. This is a bug in Astro. I suggest you open an issue there. Maybe you can work around it using [rehype-raw](https://github.com/rehypejs/rehype-raw).

This bug was initially coded as https://github.com/remcohaszing/remark-mermaidjs/issues/23 and later identified in https://github.com/remcohaszing/rehype-mermaid/issues/10

(Citing @remcohaszing )

### What's the expected result?

The processed hast should allow for a further processing by any `rehype` plugin.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ekqekg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Can you submit a PR that fixes this?
