### ISSUE TITLE
The route functions from `astro:i18n` are adding a trailing slash when it's not supposed to

### ISSUE THREAD

**Issue by mishimalisa** [withastro/astro#9919]
### Astro Info

```block
Astro                    v4.2.8
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

Using the config below, `getRelativeLocaleUrl("es", "/")` outputs `/es/` instead of `/es`. It seems that this only happens with the home path. This also affects the other i18n functions.

```js
const config = {
  trailingSlash: 'never',
  build: {
    format: 'file',
  },
  i18n: {
    defaultLocale: "en",
    locales: ["en", "es"],
    routing: {
      prefixDefaultLocale: false,
    }
  }
```

### What's the expected result?

I expected that  `trailingSlash: 'never'` option should never output urls with trailing slash.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xz2dyx?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
If you need to home path, `getRelativeLocaleUrl("es")` should be enough, right?

**Comment by mishimalisa** [comment]
The workaround works, but it's worth noting that when using the default locale without a prefix, it is still necessary to use '/' for the default language to obtain the correct relative URL.

```js
const home = getRelativeLocaleUrl(Astro.currentLocale, Astro.currentLocale === "en" ? "/" : undefined)
```

**Comment by ematipico** [comment]
> The workaround works, but it's worth noting that when using the default locale without a prefix, it is still necessary to use '/' for the default language to obtain the correct relative URL.

Sorry, I am not sure I understand your use case. Can you update the stackblitz example and show it to me?

**Comment by mishimalisa** [comment]
> > The workaround works, but it's worth noting that when using the default locale without a prefix, it is still necessary to use '/' for the default language to obtain the correct relative URL.
> 
> Sorry, I am not sure I understand your use case. Can you update the stackblitz example and show it to me?

I updated:
https://stackblitz.com/edit/github-xz2dyx?file=src%2Fcomponents%2FHeader.astro

To replicate the issue (demo 1):
1. Click to switch the locale to Spanish (es).
2. While in the Spanish locale, click to change the locale back to English.

Demo 2:
1. Navigate to the blog page (/blog).
2. Attempt to click on the 'Go to Home' link located in the footer.

Notice that `getRelativeLocaleUrl(locale)` works for switching to Spanish, but it doesn't work for switching back to English because the relative locale path is not the home path when you are in the Spanish language.

The function, as it stands, is fine when you can just hardcode the locale. However, for components present in every locale, the edge case must be handled like I showed you.

**Comment by Vipermaseg** [comment]
This is still a problem in Astro 4.12.2. Thanks @mishimalisa for the workaround. Let me take a stab at explaining the issue.

My header has a logo that is supposed to go to my index: http://mysite.com, and when I am in Portuguese I should get the link http://mysite.com/pt

Using getRelativeLocaleUrl(locale, "/") will yield:
locale = en -> http://mysite.com
locale = pt -> http://mysite.com/pt/

Using getRelativeLocaleUrl(locale) will yield:
locale = en -> http://mysite.com/currentpage
locale = pt -> http://mysite.com/pt

And what I mean by current page is any page I'm on, because this link is in my logo in the header.

**Comment by ematipico** [comment]
@Vipermaseg Please create a new issue with a new reproduction.

**Comment by Vipermaseg** [comment]
#11630 I hope this is helpful.

**Comment by ADTC** [comment]
@ematipico `getRelativeLocaleUrl` will add a trailing slash even if the URL has query params or a hash anchor....

```js
getRelativeLocaleUrl('es', '/page?query=Something') // ---> gives /es/page?query=Something/ ... why?

getRelativeLocaleUrl('es', '/page#anchor') // ---> gives /es/page#anchor/ ... why?
```

Because of this, I have to add `.replace(/\/$/, '')` to it. (I wrapped the whole thing in a reusable function.)

I don't have time to make a StackBlitz repro for you, but this is a pretty basic bug.

**Comment by ematipico** [comment]
@ADTC please open a new issue and provide a reproduction when you have time

**Comment by ADTC** [comment]
I hope you're not implying that this case of an unmet basic expectation of how links are expected to work in general won't be fixed unless someone gives you a reproduction LOL.

I mean, why **_blindly_** add a slash at the end of the given path with no regard for query params or anchor links?

PS: Anyway I don't have time. Busy with life, family and work. I'm hoping to call your attention to this, but I hope I don't have to work hard before you will fix it.
