### ISSUE TITLE
Node.js SSR redirect timeout

### ISSUE THREAD

**Issue by friedemannsommer** [withastro/astro#9925]
### Astro Info

```block
Astro                    v4.3.0
Node                     v20.11.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

When returning an HTTP 30X (for example via an `Astro.redirect` in a `.astro` component), the HTTP response is not flushed and therefore not completed, resulting in a timeout while waiting for it.

This behavior was introduced by 2f6d1faa6f2d6de2d4ccd2a48adf5adadc82e593 in #9908.

### What's the expected result?

The HTTP response should be flushed immediately since (in most cases) there is no HTTP body.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-y5eicp?file=README.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
If we're able to add a test for this case and fix it, I think it's a reasonable change!

**Comment by friedemannsommer** [comment]
> If we're able to add a test for this case and fix it, I think it's a reasonable change!

I will take a look at it.

**Comment by friedemannsommer** [comment]
Should i still look into a possible test implementation for this issue or will it be implemented in a separate PR? (I've seen the code change in #9931)

**Comment by lilnasy** [comment]
Funnily enough, a new test is not necessary. Our existing tests failed with 9908, they just weren't running at that time.
