### ISSUE TITLE
Vercel Adapter doesn't bundle `@libsql/client`

### ISSUE THREAD

**Issue by binyamin** [withastro/astro#9936]
### Astro Info

```block
Astro                    v4.3.0
Node                     v20.9.0
System                   Linux (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/solid-js
which: no xclip in (./node_modules/.bin:/home/binyamin/.turso:/home/binyamin/.local/share/pnpm:/home/binyamin/.cargo/bin:/home/binyamin/.bun/bin:/home/binyamin/.deno/bin:/run/user/1000/fnm_multishells/3534986_1706800354736/bin:/home/binyamin/.local/share/fnm:/home/binyamin/.local/share/zinit/polaris/bin:/home/binyamin/.local/bin:/home/binyamin/bin:/home/binyamin/.local/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/home/binyamin/go/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/var/lib/snapd/snap/bin:/usr/local/go/bin)
```

### Describe the Bug

When a project uses the `@astrojs/vercel/serverless` as an adapter, the module `@libsql/client` will never be bundled. This is hardcoded in [`src/lib/nft.ts`](https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/lib/nft.ts#L11). This behavior is not noted in the docs, and there's no warning from the CLI. The serverless function just fails.

The only hint to this is that the `.vercel/output` folder contains a broken symlink in the `node_modules` for `@libsql/client`.

### What's the expected result?

The function should bundle appropriately. I can see from the code that it ignores `@libsql/client` for a reason. I don't understand the reason, but I am willing to brainstorm for a different solution.

**Note**: The reproduction on stackblitz will probably be useless, since stackblitz doesn't show the `.vercel` folder. See [the source file](https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/lib/nft.ts#L11) instead.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4vea6g

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @binyamin, are you trying to use `@libsql/client` and it's not working for you? That ignore is just ignoring copying over of native dependencies that Vercel's file tracer thinks should be moved.

Node dependencies are not bundled by default, so this is normal behavior.

**Comment by binyamin** [comment]
I did some digging. `@libsql/client` _does_ support Vercel Edge functions, but through a subpath (`@libsql/client/web`). See https://github.com/tursodatabase/libsql-client-ts/?tab=readme-ov-file#importing. Astro won't even if I change it to the subpath.

**Comment by binyamin** [comment]
Note that I am getting the same 500 error mentioned in #9801. Also, nft _does_ write a file `node_modules/@libsql/client`. It's a broken symlink. So the import fails.

**Comment by matthewp** [comment]
Astro doesn't support Vercel Edge functions for app deployment. Are you saying you have a project you're deploying to Serverless that's failing for this reason? That line you linked to that ignores `@libsql/client` is for an optimization.

They just released a wasm version of their library, `@libsql/client-wasm` but it's pretty experimental from what I understand.

**Comment by binyamin** [comment]
I still don't get what's being optimized. What happens without the ignore? See https://github.com/withastro/astro/issues/9936#issuecomment-1922086365
