### ISSUE TITLE
Pages created inside pages build into page/index.html

### ISSUE THREAD

**Issue by user112200** [withastro/astro#9941]
### Astro Info

```block
Astro                    v4.2.4
Node                     v18.15.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When creating `login.astro` page inside `src/pages` page gets built to `dist/login/index.html` instead of `dist/login.html`.

Am I missing any config?

### What's the expected result?

`pages/page.astro` should built to `dist/page.html`.

**Comment by Princesseuh** [comment]
This is intended behavior. You can change `build.format` to control this https://docs.astro.build/en/reference/configuration-reference/#buildformat
