### ISSUE TITLE
Generating a sitemap for [...slug].astro pages with slugs starting with / results in broken URLs

### ISSUE THREAD

**Issue by moose96** [withastro/astro#9946]
### Astro Info

```block
Astro                    v4.3.1
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

### Describe the Bug

I am creating my own integration with CMS and I've decided to store all slugs inside content management system. Thus, my `pages` folder contains only one page - `[...slug].astro`. I have complicated logic in `getStaticPaths` but it migth be simplified to this:
```ts
export async function getStaticPaths() {
  return [
    {
      params: {
        slug: undefined,
      }
    },
    {
      params: {
        slug: '/blog'
      }
    },
    {
      params: {
        slug: '/test'
      }
    }
  ];
}
```
Let's assume my `astro.config.mjs` looks like:
```js
export default defineConfig({
  site: 'https://example.com',
  integrations: [sitemap()],
});
``` 
In this case I get sitemap:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
    <url>
        <loc>https://blog/</loc> <!-- <- wrong url here -->
    </url>
    <url>
        <loc>https://example.com/</loc>
    </url>
    <url>
        <loc>https://test/</loc><!-- <- wrong url here -->
    </url>
</urlset>
```

### What's the expected result?

I expect sitemap to be:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
    <url>
        <loc>https://example.com/blog/</loc>
    </url>
    <url>
        <loc>https://example.com/</loc>
    </url>
    <url>
        <loc>https://example.com/test/</loc>
    </url>
</urlset>

```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-e5zwsf?file=dist%2Fsitemap-0.xml

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I'm not sure if slugs should have a leading slash or trailing slash, I feel like there would be more bugs down the line if you do so, and not just an issue with the sitemap integration 🤔

**Comment by moose96** [comment]
> I'm not sure if slugs should have a leading slash or trailing slash, I feel like there would be more bugs down the line if you do so, and not just an issue with the sitemap integration 🤔

What kind of bugs? We use leading slashes in our application and everything works except generating sitemap. That's why I think it's the issue with the sitemap integration. If using leading or trailing slashes was forbidded there should be any validation while generating static paths or there should be a note in a documentation that you can't use this kind of slashes in the code with explanation.

**Comment by florian-lefebvre** [comment]
I agree with @bluwy, I didn't think leading slashes would be allowed as parameters. Not sure what's the best way here, maybe we should do the following:
1. If a param starts or ends with a `/`, remove it
2. Log a warning
3. In Astro 5, update the regex and fail is specified?

**Comment by ematipico** [comment]
@florian-lefebvre, where should this warning be printed?

**Comment by ematipico** [comment]
@matthewp what do you think? Does it make sense to you?

**Comment by matthewp** [comment]
I think @florian-lefebvre's plan makes sense. There was a related issue where someone was confused today.

**Comment by matthewp** [comment]
After discussing this we realized that having double slashes is valid in a URL path, (`/foo//about` is a valid URL!), so we don't want to remove those even though it's what you would want most of the time.

Another idea that could help is having a utility like `pathToParam(path)` that people can use for this scenario, given that it's a common thing to try and do. With this utility method we can do whatever we want/need to normalize the param.

**Comment by ematipico** [comment]
Closing. This will be fixed in Astro v5. Follow https://github.com/withastro/astro/issues/7962#issuecomment-2401897569 for more information.

Params can contain slashes, but they must be **encoded** inside `getStaticPaths`, then the use must decode them when using them
