### ISSUE TITLE
`free(): invalid size` on dev server

### ISSUE THREAD

**Issue by Steffan153** [withastro/astro#9959]
### Astro Info

```block
Astro                    v4.3.2
Node                     v21.1.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/mdx
                         astro-compress
                         astro-critters
                         @sentry/astro
                         @spotlightjs/astro
```

### Describe the Bug

Running the Astro dev server crashes shortly after loading a page:
```
astro  v4.3.2 ready in 2513 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

18:05:26 [@spotlightjs/astro] Sidecar listening on 8969
18:05:27 watching for file changes...
18:05:42 [200] / 640ms
free(): invalid size
Aborted (core dumped)
```
I didn't have this problem on Astro v4 (I updated directly to v4.3). `astro build` works fine, and it also works fine on a different computer.

### What's the expected result?

I would expect the server to work properly.

### Link to Minimal Reproducible Example

Not reproductible on Stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Does it work if you uninstall `astro-compress`?

**Comment by Steffan153** [comment]
Thanks, that fixed it. 👍

**Comment by Princesseuh** [comment]
Weird, but that probably means it's unrelated to Astro itself. Glad it works!

**Comment by Steffan153** [comment]
I'm having this issue with Netlify as well. Should I reopen in the astro compress repo?
![image](https://github.com/withastro/astro/assets/40404519/63180eb1-38ac-47db-9bc4-28b8ea7812a1)
