### ISSUE TITLE
Version 4.2.7 breaks internacionalization of URLs when the locale is within rest parameters

### ISSUE THREAD

**Issue by Frondor** [withastro/astro#9970]
### Astro Info

```block
Astro                    v4.3.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

This used to work prior to 4.2.7 when this [PR ](https://github.com/withastro/astro/pull/9865) got merged.
`Astro.currentLocale` is no longer getting configured correctly since we are not splitting the path segments to find it anymore.

Provide a fallback, maybe?

### What's the expected result?

I have a variety of routes under `/blog`, for instance, these are valid routes

- `/blog` (spanish version / default locale)
- `/blog/en` (english version)
- `/blog/en/tags/some-tag`
- `/blog/tags/algun-tag`
- etc

Since we are not splitting the path anymore, Astro can't get currentLocale from URLs.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/edit/withastro-astro-dtu37f?file=README.md&initialPath=%2Fblog%2Fen

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by philipschm1tt** [comment]
I observed the same behavior for my `[...page].astro`.

I verified that the issue started exactly with Astro 4.2.7.

**Comment by philipschm1tt** [comment]
Looping in @ematipico

**Comment by Frondor** [comment]
I suggest to get back to the original implementation. The approach at #9865 looks a bit _invasive_ to me and as @philipschm1tt said, it may brake some i18n things.

@ematipico what do you thing about it?
I think what you wanted to fix in that PR could also be done by passing a regex to the split.
For instance:
```diff
	const requestUrl = new URL(request.url);
-	for (const segment of requestUrl.pathname.split('/')) {
+       const segments = requestUrl.pathname.split(/\/|\.\w+$/).filter(Boolean);
+	for (const segment of segments) {
```

**Comment by jurajkapsz** [comment]
> I observed the same behavior for my [...page].astro.

For me the same. `Astro.currentLocale` is no longer defined.

I went with a [Middleware](https://docs.astro.build/en/guides/middleware/) solution for the time being, where I create `currentLocale` from request `pathname`, actually it works pretty well for my use case (though I guess I don't utilize the i18n suite features in my project in general).

**Comment by ematipico** [comment]
@Frondor could you be more clear about the "expected result", please?

You listed a bunch of routes, but you didn't explain to use what would you expect from those routes.

**Comment by Frondor** [comment]
Sup @ematipico!

> @Frondor could you be more clear about the "expected result", please?
> 
> You listed a bunch of routes, but you didn't explain to us what would you expect from those routes.

I see you've been working on a fix, I'll try it now in my project.
Regarding to your reply, the expected result is right in the reproducible example, as you can visit any of those routes I listed above and verify that `currentLocale` was still the default (`es`) even for `en` routes.

I've forked the previous example with  `4.3.3` and confirm it is working as intended now. Thank you!
https://stackblitz.com/~/edit/withastro-astro-yrzlj1?file=README.md&initialPath=/blog/en
