### ISSUE TITLE
Weird jsx syntax bug  /  doesn't crash but renders page partially

### ISSUE THREAD

**Issue by Britnell** [withastro/astro#9972]
### Astro Info

```block
Hey, i just had this weird bug where my root page component stopped working.
no changes to code, or packages, the page suddenly only rendered the footer.
Here the code : 

<>
  {
    typeof blok?.global === "object" ? (
      <Header blok={blok.global} slug={blok.slug} />
    ) : (
      <header>No global data selected</header>
    )
  }
  
  <main>    ...    </main>
  {
    typeof blok?.global === "object" ? (
      <Footer blok={blok.global} />
    ) : (
      <footer>No global data selected</footer>
    )
  }
</>

```

not the greatest code, I admit, but it always worked.
then today after other changes (which i reverted) this would ONLY render the footer, but no errors nothing.

I finally fixed it by just simplifying the logic :
```

<>
  {blok?.global && <Header blok={blok.global} slug={blok.slug} />}
  <main > ...   </main>
  {blok?.global && <Footer blok={blok.global} />}
</>
```

please tell me if there is something wrong with the first code, but i thought it should have at least worked.
instead it didnt fail but only rendered the footer ...
i checked the html, its not like a closing tag was missing and it skipped parts, <main> and <header> were just empty ...
is there anything special about astro jsx syntax i should know? 
is there somethign like verbose mode to get output from the renderer?

- blok is coming from storyblok

package.json : 
```
  ...
  "dependencies": {
    "@astrojs/check": "^0.3.3",
    "@astrojs/node": "^7.0.2",
    "@astrojs/tailwind": "^5.0.3",
    "@builder.io/qwik": "^1.3.1",
    "@qwikdev/astro": "^0.3.1",
    "@storyblok/astro": "^3.0.1",
    "@storyblok/js": "^3.0.0",
    "astro": "^4.0.6",
    "tailwindcss": "^3.3.6",
    "typescript": "^5.3.3"
  },
```

PS thanks, shoutout to astro team killing it, this is my new gospel so please tell me if I'm getting somethign wrong
```


### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

only partially renders the page, skipping the <header> and <main>, and rendering only the last <footer>

### What's the expected result?

normal fully rendered page

### Link to Minimal Reproducible Example

can't do this today, will setup asap

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Thanks for taking the time to report this!
I can see that it's the same issue issue reported in https://github.com/withastro/compiler/issues/955. We're already tracking the problem there, so I'm going to close this as a duplicate.

**Comment by Britnell** [comment]
ah sorry i didnt see that. ok glad i'm not going insane haha

thanks team :pray:
