### ISSUE TITLE
JSX Data inline in JSON causes a compiler error

### ISSUE THREAD

**Issue by gvkhna** [withastro/astro#9974]
### Astro Info

```block
Latest astro version on stackblitz
```

### Describe the Bug

JSX syntax in javascript causes a compiler error, here's the syntax brief: 

```jsx
<QuestionAnswers questions={[{
	q: <>My Question</>,
	a: <>My Answer</>
}]} />
```

The error also doesn't point to this code but once it's removed there is no issue so it's clearly the parser failing to handle this kind of syntax.

### What's the expected result?

This should work like React JSX

### Link to Minimal Reproducible Example

https://stackblitz.com/~/edit/github-nvapn7

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is currently an intentional limitation of Astro, we don't support passing JSX elements as props anywhere. If you would like for this to be supported, please create a discussion on our roadmap repo: https://github.com/withastro/roadmap/discussions

**Comment by gvkhna** [comment]
Posted https://github.com/withastro/roadmap/discussions/833
