### ISSUE TITLE
Getting "[ERROR] Failed to parse URL from..." if I don't supply a base URL

### ISSUE THREAD

**Issue by sashafklein** [withastro/astro#9979]
### Astro Info

```block
Astro                    v4.3.2
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/react
```

### Describe the Bug

If I do:

`fetch("/api/some-url")`

or, in a server endpoint:

```ts
Response.redirect("/")
```

I get:

```ts
18:54:41 [ERROR] Failed to parse URL from 
```

This seems like a bug/issue to me. Shouldn't it be able to redirect/fetch locally without a full path that may vary by environment?

### What's the expected result?

That it infers the base URL

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/sashafklein/astro-cookie-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
I don't think this is an Astro issue. You would see the same behavior in a node repl.

> This seems like a bug/issue to me. Shouldn't it be able to redirect/fetch locally without a full path that may vary by environment?

That is not the case, unfortunately. It works in browsers because they always have a `location`. A server is not tied to a specific domain or protocol, so you need to provide one to `fetch` and `Response.redirect`.

**Comment by sashafklein** [comment]
Makes sense, thank you!
