### ISSUE TITLE
Deno adapter issue

### ISSUE THREAD

**Issue by jamesli2021** [withastro/astro#9981]
### Astro Info

```block
Since the previous issue was closed, I file new issue
https://github.com/withastro/astro/issues/9961


All default option:
npm create astro@latest

cd to project and:
npx astro add deno

You can see the error on macOS.
```

### If this issue only occurs in one browser, which browser is a problem?

NA

### Describe the Bug

As above.

### What's the expected result?

As above.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
We don't maintain the Deno adapter, please report issues to Deno. https://github.com/denoland/deno-astro-adapter
