### ISSUE TITLE
Dashes are not allowed in dynamic routing params

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#9982]
### Astro Info

```block
Astro                    v4.3.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Using a `dash` in a dynamic route param throws an error:
```
Error: Invalid route src/pages/blog/[some-slug].astro — parameter name must match /^[a-zA-Z0-9_$]+$/
```

### What's the expected result?

I'd like more characters to be supported. If this value is just used as a key, we could basically allow anything (`/^[^\[\]]+$/` from Chris on Discord)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hr32jk?file=src%2Fpages%2Fblog%2F[some-slug].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
> I'd like more characters to be supported.

That's... concerning, in the sense that allowing other characters would mean applying a specific encoding based on the characters we want to support. 

I believe it should require a longer discussion and some requirements.

**Comment by matthewp** [comment]
I also don't think we should support this. Keeping a narrow scope of allowed params helps avoid security issues like prototype pollution.
