### ISSUE TITLE
Text encoding problem

### ISSUE THREAD

**Issue by alexpresently** [withastro/astro#9984]
### Astro Info

```block
Astro 4.3.2
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

Encoding for languages other than English breaks on pages, but works on layout and index page

### What's the expected result?

test page content needs to be "кодировка не работает - Not OK" but I get "ÐºÐ¾Ð´Ð¸Ñ€Ð¾Ð²ÐºÐ° Ð½Ðµ Ñ€Ð°Ð±Ð¾Ñ‚Ð°ÐµÑ‚ - Not OK"

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ngr3mk-9jpq56?file=src%2Fpages%2Ftest.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You need to specify a `charset` meta on the page, like such: `<meta charset="utf-8" />`, see this page for more information: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#charset (this is a standard HTML thing, not specific to Astro!)

**Comment by alexpresently** [comment]
My bad. I forgot to wrap page in layout or add meta to page.astro as it is just a component to render.
