### ISSUE TITLE
Conditionally rendered content overrides other content in slot

### ISSUE THREAD

**Issue by MGSE97** [withastro/astro#9990]
### Astro Info

```block
Astro                    v4.3.2
Node                     v19.8.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Firefox, Opera

### Describe the Bug

Hello,
I've been going through _Build a blog_ tutorial, and I've noticed some content disappeared, when I wrapped it in layout.

When using ternary operator `?:`, or `&&` and `||` operators to render content in slot, only last resolved conditional content remains. Any other content passed into slot is removed.

Example:
```astro
<!-- wrapper.astro -->
<section>
  <slot />
</section>
```

```astro
---
const showContent = true;
---
<Wrapper>
  <p> Before content </p>
  {showContent ? <p> Some shown content </p> : <p> Some hidden content </p>}
  <p> After content </p>
</Wrapper>
```
Becomes:
```astro
<section>
  <p> Some shown content </p>
</section>
```
Instead of:
```astro
<section>
  <p> Before content </p>
  <p> Some shown content </p>
  <p> After content </p>
</section>
```

Without using `<slot />`, content renders as expected. 
Workaround is to wrap condition in some other element (e.g. `div`).
```astro
<Wrapper>
  <p> Before content </p>
  <div>
     {showContent ? <p> Some shown content </p> : <p> Some hidden content </p>}
  </div>
  <p> After content </p>
</Wrapper>
```

### What's the expected result?

- Other content should not be removed/overwritten.
- Conditional rendering should work same way with and without using slot. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-yfzk5c-slot-issues?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Thanks for taking the time to report the issue!
We're aware of the regression and we're working on a fix, so I'm going to close this in favor of  this in https://github.com/withastro/compiler/issues/955
