### ISSUE TITLE
Elements not rendered in Fragment when using ternary

### ISSUE THREAD

**Issue by ferencalmasi** [withastro/astro#9997]
### Astro Info

```block
Astro                    v4.3.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Using ternary operators inside a `Fragment` breaks the rendering of adjacent elements:
```astro
<Fragment>
  <h1>title</h1>
  {true ? <h2>sub title</h2> : <strong>strong tag</>}
</Fragment>
```
In the above example, the `h1` will not be rendered. It'll only be rendered if:
- Using two separate logical AND operators inside the `Fragment`
- Nesting the condition inside another `Fragment`

This functionality was working as expected in previous versions (e.g. 2.4.5).
Please see repro for examples.

### What's the expected result?

- Elements inside a `Fragment` without conditions should be rendered
- Elements inside a `Fragment` with conditions should be rendered based on the evaluation of the condition, without the need of nesting `Fragment`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-cwjduy?file=src%2Fpages%2Findex.astro&title=Astro%20Starter%20Kit:%20Blog

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Hey thanks for taking the time to report! We're tracking the issue in https://github.com/withastro/compiler/issues/955 and I made a PR that should fix it in https://github.com/withastro/compiler/pull/963, so I'll close this as duplicate.
